### PR TITLE
ui: txn insights v2

### LINKED ISSUE #88847: ui: use async/await instead of promise chaining in insights SQL API queries
The [transaction insights SQL API queries](https://github.com/cockroachdb/cockroach/blob/ae38d903c527fdd85a0183b6245d191e51d79578/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L406) currently use promise chains to get and process transaction contention results from the DB. We should use async/await instead, as promise chaining makes the code more difficult to read and maintain.

### LINKED ISSUE #91696: ui: aggregate stmt insights to show at txn level
We can aggregate existing statement insights from the `crdb_internal.cluster_execution_insights` table, which are already surfaced in DB console, as transactions. We can then show statement insights aggregated at the txn level on the txn insights overview page.

Following information will be added to txns from the current cluster exec insights response:
- User name
- Session ID
- rows processed
- rows read
- rows written
- retries
- last retry reason
- Full scan
- Transaction priority
- slow stmt execution
- index recommendations
- plan regression
- 
Jira issue: [CRDB-20749](https://cockroachlabs.atlassian.net/browse/CRDB-20749)
Epic [CRDB-20389](https://cockroachlabs.atlassian.net/browse/CRDB-20389)

### PR DESCRIPTION
**Pull request by xinhaoz**
Closes https://github.com/cockroachdb/cockroach/issues/91696
Closes https://github.com/cockroachdb/cockroach/issues/88847

For the next version of txn insights, we want to show
the insights of the stmts involved in the txn. This
commit aggregates stmt insights to show at the txn
level on the txn insights overview page and the details
page.

Previously, the txn insights only showed contention
information, which we pull from a different source
(contention registry over insights system). To preserve
the information we were already showing, the aggregated
stmt insights were merged with the previous data.

Some considerations to be addressed in future PRs:
1. We don't currently track txn start and end time
in the insights system. Since there is no guarantee that
a txn in the contention registry has an entry in the insights
system, there is currently a gap in execution details for
txn contention insights being displayed.

2. For insights we only display the most recent txn execution
for a txn fingerprint that has an insight. Since the insights
system does not track txn end time, we can't know which
executed more recently when we have a txn from the contention
response and one from the insights response with the same
fingerprint, so for now we default to showing the contention
insight.

Release note (ui change): Txn insights pages now show insights
about slow execution with unknown causes, plan regressions,
index recommendations, and failed executions. The following
fields have also been added on the details page, but are not
available for txns where the insight is 'High Contention':
- User name
- Session ID
- rows processed
- rows read
- rows written
- retries
- last retry reason
- Full scan
- Transaction priority

image
image

Image below contains a fixed bug seen in loom where time spent waiting showed NaN
image

https://www.loom.com/share/640d0e464d1c40978d44ea1df8ac4581

CC Console Insight pages:
https://www.loom.com/share/4b01cef66aec4c1aa5a7f44b9a962237

### CODE REVIEW

**Review by ericharmeling — APPROVED** [review]
This is awesome. Looks great! After a first pass, I just had a few comments/suggestions, mainly related to code comments. But otherwise, LGTM.

I do think there are a few things that I don't quite understand that I might need to ask you about offline - so it might be best to get an approval from a second person too. :)

> Reviewed 5 of 22 files at r2, 36 of 36 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-:-NGYY4i62hd9njX3Vj1c:b-be9r93)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/insights/types.ts` line 58 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYNhkj-cuUX7t5qQwj:-NGYNhkj-cuUX7t5qQwk:bcn95ln) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bdc7cb2240500217255fead1add7a24b4aa406a/pkg/ui/workspaces/cluster-ui/src/insights/types.ts#L58)):*
> ```XML
> };
> 
> // TODO (xinhaoz these fields should be placed required and placed into
> ```

These fields appear to already be required and part of `TxnInsightEvent`?



_Suggestion:_
```XML
should be required 
```
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/types.ts` line 331 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYPABw5-Lw9zhJ87Qf:-NGYPABw5-Lw9zhJ87Qg:b-irpj9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bdc7cb2240500217255fead1add7a24b4aa406a/pkg/ui/workspaces/cluster-ui/src/insights/types.ts#L331)):*
> ```XML
> export interface InsightRecommendation {
>   type: InsightType;
>   database?: string;
> ```

Can we remove this if we already have `databaseName` in `ExecutionDetails`?



_Code quote:_
```XML
database?: string;
```
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/utils.ts` line 42 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYQD5C8VDXScs-CwUa:-NGYQD5C8VDXScs-CwUb:bhgpu93) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bdc7cb2240500217255fead1add7a24b4aa406a/pkg/ui/workspaces/cluster-ui/src/insights/utils.ts#L42)):*
> ```XML
>   let filteredTransactions = transactions;
> 
>   const isInternal = (txn: { application?: string }) =>
> ```

(I might not be understanding this type check properly)



_Suggestion:_
```XML
(txn: MergedTxnInsightEvent)
```
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/utils.ts` line 304 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYQveO4gu1tKFymYEp:-NGYQveO4gu1tKFymYEq:undefined) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bdc7cb2240500217255fead1add7a24b4aa406a/pkg/ui/workspaces/cluster-ui/src/insights/utils.ts#L304)):*
> ```XML
>  * aggregated from stmt insights, and a list of txn contention insights.
>  * If a txn exists in both lists, its information will be merged.
>  * @param txnInsightsFromStmts txn insights aggreaged from stmts
> ```





_Suggestion:_
```XML
aggregated 
```
___
*[`pkg/ui/workspaces/cluster-ui/src/insightsTable/insightsTable.tsx` line 309 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYUUJG8_km-rCoMvHW:-NGYUUJG8_km-rCoMvHX:b-qnv2z6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bdc7cb2240500217255fead1add7a24b4aa406a/pkg/ui/workspaces/cluster-ui/src/insightsTable/insightsTable.tsx#L309)):*
> ```XML
>       title: insightsTableTitles.query(),
>       cell: (item: InsightRecommendation) =>
>         limitText(item.execution?.statement, 100) ?? "N/A",
> ```

(just a suggestion for something a little more specific)



_Suggestion:_
```XML
"No query"
```

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91698)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/insights/types.ts` line 331 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYPABw5-Lw9zhJ87Qf:-NGYjmepB5Zo8fAU88oT:bjqsgqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bdc7cb2240500217255fead1add7a24b4aa406a/pkg/ui/workspaces/cluster-ui/src/insights/types.ts#L331)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

Can we remove this if we already have `databaseName` in `ExecutionDetails`?
</blockquote></details>

or remove from the execution details. This value here is used on schema insights, index stats page and statement details page. It's used to be able to apply a recommendation, and it's not an "execution", so I would prefer to keep this one

**Review by maryliag — COMMENTED** [review]
really nice refactor and work on the new features!

> Reviewed 1 of 1 files at r1, 22 of 22 files at r2, 36 of 36 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-:-NGYuelIEYWWOpG7emqO:b-3hw94h)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @xinhaoz)

___
*[`-- commits` line 63 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYozxP1I9R7u79KUEZ):*
nit: you probably saw that we prepare this type, but right now we're not really collecting any info to identify a plan regression, so you can remove from the list.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 407 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYlHe7EUZUzwVe88yS:-NGYlHe7EUZUzwVe88yT:blkvqbh) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc22652bf7edda6f9d22d4208fb30bac151f0af8/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L407)):*
> ```XML
>   req: TransactionInsightEventDetailsRequest,
> ): Promise<TransactionInsightEventDetailsResponse> {
>   // Note that any errors encountered fetching these results are caught // earlier in the call stack.
> ```

nit: add the new line on `// earlier`
___
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 615 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYpqhN2igaNW6Kar7j:-NGYpqhN2igaNW6Kar7k:bx52dp4) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bdc7cb2240500217255fead1add7a24b4aa406a/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L615)):*
> ```XML
>     }, []);
> 
>     // Sort stmt insights for each txn by start time.
> ```

why you need to sort this?
___
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 632 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYqiJx-bf6knZWeFds:-NGYqiJx-bf6knZWeFdt:b-qchfn7) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bdc7cb2240500217255fead1add7a24b4aa406a/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L632)):*
> ```XML
> };
> 
> const executionInsightsQuery: InsightQuery<
> ```

if you changed this from statement because now you use for both statement and transaction, you can use the word "workload" to align with the name we use on the UI
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/types.ts` line 218 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYsSJA55FJ83qLyzPq:-NGYsSJA55FJ83qLyzPr:bpttgrd) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bdc7cb2240500217255fead1add7a24b4aa406a/pkg/ui/workspaces/cluster-ui/src/insights/types.ts#L218)):*
> ```XML
>     tooltipDescription:
>       description + ` Click the ${execType} execution ID to see more details.`,
>     count: 1,
> ```

if the value is 1 for all examples, why do you need this?
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/utils.ts` line 278 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYsm419TuTM_NhTLQN:-NGYsm419TuTM_NhTLQO:bgv0e9s) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bdc7cb2240500217255fead1add7a24b4aa406a/pkg/ui/workspaces/cluster-ui/src/insights/utils.ts#L278)):*
> ```XML
> /**
>  * flattenTxnInsightsToStmts flattens the txn insights array
>  * into its stmt insights. Only stmts with  non-empty insights
> ```

nit: extra space between `with` and `non-empty`
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/utils.ts` line 335 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYt2W19XSMu0oMrxw2:-NGYt2W19XSMu0oMrxw3:b-112r7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bdc7cb2240500217255fead1add7a24b4aa406a/pkg/ui/workspaces/cluster-ui/src/insights/utils.ts#L335)):*
> ```XML
>         txn.transactionExecutionID
>       ) {
>         // TODO (xinhaoz) find one that executed more recently one we
> ```

this phrase has some extra words and it's confusing :grimacing: 
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/transactionInsightDetailsOverviewTab.tsx` line 92 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYs9OsDAqJrqRGWkZ-:-NGYs9OsDAqJrqRGWkZ0:b-dh3buv) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bdc7cb2240500217255fead1add7a24b4aa406a/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/transactionInsightDetailsOverviewTab.tsx#L92)):*
> ```XML
> 
>   const rowsRead =
>     stmtInsights?.reduce((count, stmt) => (count += stmt.rowsRead), 0) ?? "N/A";
> ```

is this the count that you started with 1? if yes, it means you're adding an extra 1 to the total
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/statementInsights/statementInsightsView.tsx` line 206 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYo9kb60Esr4j9F4ty:-NGYo9kb60Esr4j9F4tz:btd3cno) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc22652bf7edda6f9d22d4208fb30bac151f0af8/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/statementInsights/statementInsightsView.tsx#L206)):*
> ```XML
>   );
> 
>   // const statementInsights =
> ```

remove this comment
___
*[`pkg/ui/workspaces/cluster-ui/src/insightsTable/insightsTable.tsx` line 44 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYuC8UBDjLbmcDTFBf:-NGYuC8UBDjLbmcDTFBg:byddp2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bdc7cb2240500217255fead1add7a24b4aa406a/pkg/ui/workspaces/cluster-ui/src/insightsTable/insightsTable.tsx#L44)):*
> ```XML
> 
> type InsightsTableTitleType = {
>   [key in InsightsTableColumnKeys]: () => React.ReactNode;
> ```

use `ReactElement` -> https://github.com/cockroachlabs/managed-service/blob/master/docs/frontend-codereview-guide.md#prop-typing
___
*[`pkg/ui/workspaces/cluster-ui/src/selectors/common.ts` line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYoKM90hB87dZ_PwJG:-NGYoKM90hB87dZ_PwJH:b-7m74ox) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc22652bf7edda6f9d22d4208fb30bac151f0af8/pkg/ui/workspaces/cluster-ui/src/selectors/common.ts#L18)):*
> ```XML
> // and combiners that can be reused across both packages.
> // This is to avoid unnecessary repeated logic in the creation of selectors
> // between db-console and cluster-ui.
> ```

nice!

**Comment by ericharmeling** [comment]
I think this also closes https://github.com/cockroachdb/cockroach/issues/88847 :)

**Review by xinhaoz — COMMENTED** [review]
@ericharmeling Ah you're right, added that issue to the commit!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-:-NGc1awB1N-Vh5v6wk26:b-tpw8j7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @maryliag)

___
*[`-- commits` line 63 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYozxP1I9R7u79KUEZ):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: you probably saw that we prepare this type, but right now we're not really collecting any info to identify a plan regression, so you can remove from the list.
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 407 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYlHe7EUZUzwVe88yS:-NGbub9aBQMlnIx6FWjP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc22652bf7edda6f9d22d4208fb30bac151f0af8/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L407)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: add the new line on `// earlier`
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 615 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYpqhN2igaNW6Kar7j:-NGbudgZ7LcDwytMyOGR:b-p0a96d) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bdc7cb2240500217255fead1add7a24b4aa406a/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L615)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

why you need to sort this?
</blockquote></details>

More for convenience of organizatio -- I just thought it'd be good to have the stmts  in the order they were executed in case we need to access some field within them in execution order.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 632 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYqiJx-bf6knZWeFds:-NGbv-i_0CAFz7brKQlr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bdc7cb2240500217255fead1add7a24b4aa406a/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L632)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

if you changed this from statement because now you use for both statement and transaction, you can use the word "workload" to align with the name we use on the UI
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/types.ts` line 58 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYNhkj-cuUX7t5qQwj:-NGbv66j9u5qVcxrbrh2:b-w6fnfe) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bdc7cb2240500217255fead1add7a24b4aa406a/pkg/ui/workspaces/cluster-ui/src/insights/types.ts#L58)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

These fields appear to already be required and part of `TxnInsightEvent`?
</blockquote></details>

Changed the comment to be more clear!
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/types.ts` line 218 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYsSJA55FJ83qLyzPq:-NGbvtWt9HjIIoYgOmyU:bs3agku) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bdc7cb2240500217255fead1add7a24b4aa406a/pkg/ui/workspaces/cluster-ui/src/insights/types.ts#L218)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

if the value is 1 for all examples, why do you need this?
</blockquote></details>

Agh this was left over from something I was playing around with for counting repeated insights for txns. Removed!
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/types.ts` line 331 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYPABw5-Lw9zhJ87Qf:-NGbw1oU1FGDhOANuO6N:bhuyln5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bdc7cb2240500217255fead1add7a24b4aa406a/pkg/ui/workspaces/cluster-ui/src/insights/types.ts#L331)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

or remove from the execution details. This value here is used on schema insights, index stats page and statement details page. It's used to be able to apply a recommendation, and it's not an "execution", so I would prefer to keep this one
</blockquote></details>

Since we need them in both let's keep them in both. The ExecutionDetails describes what is needed by insight recs. Left a comment to detail that.
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/utils.ts` line 42 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYQD5C8VDXScs-CwUa:-NGbwGtF6js_f27r_lHW:b-mshm0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bdc7cb2240500217255fead1add7a24b4aa406a/pkg/ui/workspaces/cluster-ui/src/insights/utils.ts#L42)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

(I might not be understanding this type check properly)
</blockquote></details>

It's saying that it takes an object that has an application string field. I was actually thinking if we use this check in other places we can probably lift this out to a broader utilis, what do you think?
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/utils.ts` line 278 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYsm419TuTM_NhTLQN:-NGbx9x4EA8uNF_8Z7xo:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bdc7cb2240500217255fead1add7a24b4aa406a/pkg/ui/workspaces/cluster-ui/src/insights/utils.ts#L278)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: extra space between `with` and `non-empty`
</blockquote></details>

Fixed.
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/utils.ts` line 304 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYQveO4gu1tKFymYEp:-NGbxJDL0t_hNhrVZk0C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bdc7cb2240500217255fead1add7a24b4aa406a/pkg/ui/workspaces/cluster-ui/src/insights/utils.ts#L304)):*
> ```XML
>  * aggregated from stmt insights, and a list of txn contention insights.
>  * If a txn exists in both lists, its information will be merged.
>  * @param txnInsightsFromStmts txn insights aggreaged from stmts
> ```

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/utils.ts` line 335 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYt2W19XSMu0oMrxw2:-NGbxORgCHdP_QdyvlGe:bb3lzhu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bdc7cb2240500217255fead1add7a24b4aa406a/pkg/ui/workspaces/cluster-ui/src/insights/utils.ts#L335)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

this phrase has some extra words and it's confusing :grimacing: 
</blockquote></details>

Oops, cleaned up!
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/transactionInsightDetailsOverviewTab.tsx` line 92 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYs9OsDAqJrqRGWkZ-:-NGbxepT3p3WmTqGacbO:b-8m9js2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bdc7cb2240500217255fead1add7a24b4aa406a/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/transactionInsightDetailsOverviewTab.tsx#L92)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

is this the count that you started with 1? if yes, it means you're adding an extra 1 to the total
</blockquote></details>

Removed the `count` stuff, but this field is unrelated. It's the accumulator in the reduce.
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/statementInsights/statementInsightsView.tsx` line 206 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYo9kb60Esr4j9F4ty:-NGbxyJn8jExCjyn6je7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc22652bf7edda6f9d22d4208fb30bac151f0af8/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/statementInsights/statementInsightsView.tsx#L206)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

remove this comment
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/insightsTable/insightsTable.tsx` line 44 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYuC8UBDjLbmcDTFBf:-NGc1YwX-Nui4AdhPjAU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bdc7cb2240500217255fead1add7a24b4aa406a/pkg/ui/workspaces/cluster-ui/src/insightsTable/insightsTable.tsx#L44)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

use `ReactElement` -> https://github.com/cockroachlabs/managed-service/blob/master/docs/frontend-codereview-guide.md#prop-typing
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/insightsTable/insightsTable.tsx` line 309 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYUUJG8_km-rCoMvHW:-NGc16vsCYpEZFR4NM9v:b3gwiaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bdc7cb2240500217255fead1add7a24b4aa406a/pkg/ui/workspaces/cluster-ui/src/insightsTable/insightsTable.tsx#L309)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

(just a suggestion for something a little more specific)
</blockquote></details>

Hmmm, I don't know if we want to say 'no query' since that might imply no query is attached to this insight. There might be one associated with the problem, but that information just isn't available to us. What do you think?

**Review by maryliag — COMMENTED** [review]
> Reviewed 36 of 36 files at r4, 36 of 36 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91698)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/insights/types.ts` line 58 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGc3YOY87D-CgJd4MuT:-NGc3YOY87D-CgJd4MuU:b-8u7nrv) ([raw file](https://github.com/cockroachdb/cockroach/blob/bea10a9d9ce7c47f3613b2653b3df6947bbcb9d1/pkg/ui/workspaces/cluster-ui/src/insights/types.ts#L58)):*
> ```XML
> };
> 
> // TODO (xinhaoz these fields should be placed into TxnInsightEvent
> ```

nit: you forgot the `)` after `(xinhaoz`
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/types.ts` line 338 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGc3kqo3ZYKF14CAVpR:-NGc3kqo3ZYKF14CAVpS:b-s9gxuh) ([raw file](https://github.com/cockroachdb/cockroach/blob/bea10a9d9ce7c47f3613b2653b3df6947bbcb9d1/pkg/ui/workspaces/cluster-ui/src/insights/types.ts#L338)):*
> ```XML
> }
> 
> // These are the fields used by insight recommendations.
> ```

not sure if this comment is helpful, since all fields including the ones above are for insight recommendations, that is even the name right above :) 
you can clarify this is used for execution/workload recommendations, (and not schema for example)
___
*[`pkg/ui/workspaces/cluster-ui/src/insightsTable/insightsTable.tsx` line 309 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYUUJG8_km-rCoMvHW:-NGc4XpI8yoVqIbwUa9B:bljfxyc) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bdc7cb2240500217255fead1add7a24b4aa406a/pkg/ui/workspaces/cluster-ui/src/insightsTable/insightsTable.tsx#L309)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Hmmm, I don't know if we want to say 'no query' since that might imply no query is attached to this insight. There might be one associated with the problem, but that information just isn't available to us. What do you think?
</blockquote></details>

The `N/A` would make more sense in this case indeed

**Review by ericharmeling — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91698)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/insights/utils.ts` line 42 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYQD5C8VDXScs-CwUa:-NGc6HzJ1na2oGYO-Zsa:b1vfofj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bdc7cb2240500217255fead1add7a24b4aa406a/pkg/ui/workspaces/cluster-ui/src/insights/utils.ts#L42)):*
Ah okay - makes sense then.


> I was actually thinking if we use this check in other places we can probably lift this out to a broader utilis, what do you think?

I think that's a good idea. We have basically the same function further down in the same file, and then have one for both the statements and transactions pages. But IDK if you absolutely have to do that in this PR.
___
*[`pkg/ui/workspaces/cluster-ui/src/insightsTable/insightsTable.tsx` line 309 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGYUUJG8_km-rCoMvHW:-NGc7aq6EwqH3qQxlvEx:bkc4rs) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bdc7cb2240500217255fead1add7a24b4aa406a/pkg/ui/workspaces/cluster-ui/src/insightsTable/insightsTable.tsx#L309)):*
>  There might be one associated with the problem, but that information just isn't available to us.

Right on. `N/A` works! It's just a little vague. SGTM though.

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91698)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/insights/types.ts` line 58 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGc3YOY87D-CgJd4MuT:-NGqjTYA7ReXOSCH1su3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bea10a9d9ce7c47f3613b2653b3df6947bbcb9d1/pkg/ui/workspaces/cluster-ui/src/insights/types.ts#L58)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: you forgot the `)` after `(xinhaoz`
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/types.ts` line 338 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-NGc3kqo3ZYKF14CAVpR:-NGqkdEhCV3i8lA4GQ3r:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bea10a9d9ce7c47f3613b2653b3df6947bbcb9d1/pkg/ui/workspaces/cluster-ui/src/insights/types.ts#L338)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

not sure if this comment is helpful, since all fields including the ones above are for insight recommendations, that is even the name right above :) 
you can clarify this is used for execution/workload recommendations, (and not schema for example)
</blockquote></details>

Done.

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91698#-:-NGqmEjAE_6Ovh9V4x59:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

**Comment by kevin-v-ngo** [comment]
@dongniwang, let's chat with @xinhaoz. I don't think we'd want to list out each statement (there can be many) in the transaction insight details view here. We should guide the user to the statement executions tab, pre-filtered by the insight. 

image

**Comment by kevin-v-ngo** [comment]
> @dongniwang, let's chat with @xinhaoz. I don't think we'd want to list out each statement (there can be many) in the transaction insight details view here. We should guide the user to the statement executions tab, pre-filtered by the insight.
> 
> image

We need to update the [UX mockup](https://www.figma.com/file/xpnRkP9cLXERVceRC4cec4?node-id=1086:73210#307937137) @dongniwang

**Pull request merged**
