### PR TITLE
sql: change index field visible to invisibility

### PR DESCRIPTION
**Pull request by wenyihu6**
This commit changes the field NotVisible to visibility in the struct
IndexDescriptor. All existing behavior should stay the same.

Invisibility specifies the invisibility of an index to the optimizer and can
be any float64 between [0.0, 1.0]. An index with invisibility 0.0 means that
the index is visible. An index with invisibility 1.0 means that the index is
fully not visible. By default, an index should be visible or invisibility 0.0.
An index with invisibility 1.0 is ignored by the optimizer unless it is used
for constraint check or is explicitly selected with index hinting. An index
with invisibility between (0.0, 1.0) would be made fully not visible to a
corresponding fraction of the queries (this will be supported in a future
commit). By convention, we will refer any indexes with invisibility == 0.0
as visible, any indexes with invisibility == 1.0 as fully not visible, and any
indexes with index visibility in-between as partially not visible.

Visibility is not chosen here because we want the default value to be 0.0 (by
default, index should be visible). NotVisibility is not chosen here because it
sounds awkward.

Informs: #82363

Release note: None

### CODE REVIEW

**Comment by wenyihu6** [comment]
I should have split the work for introducing a new column `visibility` to another PR 😬

**Comment by rytaft** [comment]
Hey team, I'm reviving this PR. I've rebased and made some tweaks, but it's mostly unchanged as it was very nearly ready to go (nice work, @wenyihu6!).

**Review by mgartner — COMMENTED** [review]
Thanks for reviving this :zombie: !

> Reviewed 3 of 40 files at r1, 38 of 40 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87259#-:-NSlVUzCC9f_qm1TkpDl:b7xp8jc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @michae2, @srosenberg, and @wenyihu6)

___
*[`-- commits` line 39 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87259#-NSlSFxWD2XT_DOUCzru):*
~~nit: We should have a release note for this. Some examples of how to use this new feature in the commit message would be helpful too.~~

Oh, is there no release note because there is no syntax to support using this yet?
___
*[`pkg/sql/catalog/catformat/index.go` line 188 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87259#-NSlT7MHBFibJUD0H_Ea:-NSlT7MHBFibJUD0H_Eb:b-llhsbf) ([raw file](https://github.com/cockroachdb/cockroach/blob/818f6bdd599475a8b196567b6d5c6d235801f4f5/pkg/sql/catalog/catformat/index.go#L188)):*
> ```Go
> 			f.WriteString(" NOT VISIBLE")
> 		} else {
> 			f.WriteString(" VISIBILITY=")
> ```

nit: I'd prefer a syntax without the `=`, e.g. `ALTER INDEX i VISIBILITY 0.33`. Do you think that's possible to implement in the parser?
___
*[`pkg/sql/catalog/catformat/index.go` line 189 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87259#-NSlTISG2T_i060crIYn:-NSlTISG2T_i060crIYo:biuvuyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/818f6bdd599475a8b196567b6d5c6d235801f4f5/pkg/sql/catalog/catformat/index.go#L189)):*
> ```Go
> 		} else {
> 			f.WriteString(" VISIBILITY=")
> 			f.WriteString(fmt.Sprintf("%.2f", 1-index.Invisibility))
> ```

This formatting makes me wonder if we'd be better off using an integer (e.g., representing hundredths or thousandths) for invisibility rather than a float. With a float, these statements might not round-trip exactly the same. I don't feel too strongly. A float is more intuitive and obvious, which is nice. Just thought I'd bring it up.
___
*[`pkg/sql/catalog/descpb/structured.proto` line 506 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87259#-NSlUTe41hlO_oWhpaYd:-NSlUTe41hlO_oWhpaYe:bl3pepj) ([raw file](https://github.com/cockroachdb/cockroach/blob/818f6bdd599475a8b196567b6d5c6d235801f4f5/pkg/sql/catalog/descpb/structured.proto#L506)):*
> ```protobuf
>   // any indexes with invisibility == 1.0 as fully not visible, and any indexes
>   // with index visibility in-between as partially not visible.
>   optional double invisibility = 29 [(gogoproto.nullable) = false];
> ```

I beleive we need to write some logic to update this value to 1.0 when `not_visible` is `false` so that upgrading the cluster doesn't suddenly make all hidden indexes visible. I believe we usually do this here: https://github.com/cockroachdb/cockroach/blob/853aa646aeda6993d780f64b3ffc31528144e8e6/pkg/sql/catalog/tabledesc/table_desc_builder.go#L657

But I'm hoping someone on @cockroachdb/sql-schema can give us a hint if there's more we need to do here.

**Comment by chengxiong-ruan** [comment]
*[`pkg/sql/catalog/descpb/structured.proto` line 506 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87259#-NSlUTe41hlO_oWhpaYd:-NSljFsPBBFvK_1JP_Pi:b-j9bprq) ([raw file](https://github.com/cockroachdb/cockroach/blob/818f6bdd599475a8b196567b6d5c6d235801f4f5/pkg/sql/catalog/descpb/structured.proto#L506)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I beleive we need to write some logic to update this value to 1.0 when `not_visible` is `false` so that upgrading the cluster doesn't suddenly make all hidden indexes visible. I believe we usually do this here: https://github.com/cockroachdb/cockroach/blob/853aa646aeda6993d780f64b3ffc31528144e8e6/pkg/sql/catalog/tabledesc/table_desc_builder.go#L657

But I'm hoping someone on @cockroachdb/sql-schema can give us a hint if there's more we need to do here.
</blockquote></details>

Agree with @mgartner that we should keep the `not_visible` field as deprecated instead of removing it at this moment.
So 2 options:
1. Do the migration lazily in [here](https://github.com/cockroachdb/cockroach/blob/1abff58155b195aa0d436250680bef472176d5ff/pkg/sql/catalog/tabledesc/table_desc_builder.go#L265-L265) by adding a new post-deserialization change type.
2. Add an actual upgrades to do so.
But in either case we need to think about mixed-version state so that the visibility of an index created on new binary node still works properly on an old binary node.

**Review by rytaft — COMMENTED** [review]
> Reviewed 3 of 40 files at r1, 21 of 40 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 29 of 32 files at r5, 3 of 3 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87259)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @mgartner, @michae2, and @srosenberg)

___
*[`-- commits` line 39 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87259#-NSlSFxWD2XT_DOUCzru):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

~~nit: We should have a release note for this. Some examples of how to use this new feature in the commit message would be helpful too.~~

Oh, is there no release note because there is no syntax to support using this yet?
</blockquote></details>

That's right -- from a user's perspective there should be nothing visible about this change.
___
*[`pkg/sql/catalog/catformat/index.go` line 188 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87259#-NSlT7MHBFibJUD0H_Ea:-NSpeZYB3Rc0XcVtxA-b:b7lspi6) ([raw file](https://github.com/cockroachdb/cockroach/blob/818f6bdd599475a8b196567b6d5c6d235801f4f5/pkg/sql/catalog/catformat/index.go#L188)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: I'd prefer a syntax without the `=`, e.g. `ALTER INDEX i VISIBILITY 0.33`. Do you think that's possible to implement in the parser?
</blockquote></details>

Seems like it works fine in the parser. Updated.
___
*[`pkg/sql/catalog/catformat/index.go` line 189 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87259#-NSlTISG2T_i060crIYn:-NSmnBmV-3oYuE_IuusE:bs1xw3o) ([raw file](https://github.com/cockroachdb/cockroach/blob/818f6bdd599475a8b196567b6d5c6d235801f4f5/pkg/sql/catalog/catformat/index.go#L189)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This formatting makes me wonder if we'd be better off using an integer (e.g., representing hundredths or thousandths) for invisibility rather than a float. With a float, these statements might not round-trip exactly the same. I don't feel too strongly. A float is more intuitive and obvious, which is nice. Just thought I'd bring it up.
</blockquote></details>

Yea, good point. Let's try the float and if it makes tests flaky we can consider switching to an int.
___
*[`pkg/sql/catalog/descpb/structured.proto` line 506 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87259#-NSlUTe41hlO_oWhpaYd:-NSmorp00HUesLbkpkF9:b-7wx6dp) ([raw file](https://github.com/cockroachdb/cockroach/blob/818f6bdd599475a8b196567b6d5c6d235801f4f5/pkg/sql/catalog/descpb/structured.proto#L506)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

Agree with @mgartner that we should keep the `not_visible` field as deprecated instead of removing it at this moment.
So 2 options:
1. Do the migration lazily in [here](https://github.com/cockroachdb/cockroach/blob/1abff58155b195aa0d436250680bef472176d5ff/pkg/sql/catalog/tabledesc/table_desc_builder.go#L265-L265) by adding a new post-deserialization change type.
2. Add an actual upgrades to do so.
But in either case we need to think about mixed-version state so that the visibility of an index created on new binary node still works properly on an old binary node.
</blockquote></details>

Great point -- thanks for catching this!

I added the lazy migration, but it doesn't seem to be fully working, since CI is failing in a bunch of places with "test was successful but validation upon completion failed: some descriptors did not round-trip". Any ideas?

**Comment by chengxiong-ruan** [comment]
*[`pkg/sql/catalog/descpb/structured.proto` line 506 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87259#-NSlUTe41hlO_oWhpaYd:-NSq90Te3hY7BOh9wlFr:b-xi8kpu) ([raw file](https://github.com/cockroachdb/cockroach/blob/818f6bdd599475a8b196567b6d5c6d235801f4f5/pkg/sql/catalog/descpb/structured.proto#L506)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Great point -- thanks for catching this!

I added the lazy migration, but it doesn't seem to be fully working, since CI is failing in a bunch of places with "test was successful but validation upon completion failed: some descriptors did not round-trip". Any ideas?
</blockquote></details>

So... we bootstrap a node with hardcoded system table definitions. In mixed version test config, nodes are bootstraped with older version of the system tables which don't include the new field in the protobuf. But then [this validation](https://github.com/cockroachdb/cockroach/blob/372cf8dd50b1d031b8d751611932480301250d81/pkg/sql/logictest/logic.go#L3880) is run on the new node, and and the new field is populated in the protobuf :(

I think we could skip the roundtrip validation in the mixed version config.

**Review by rytaft — COMMENTED** [review]
> Reviewed 8 of 18 files at r8, 31 of 31 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87259)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @mgartner, @michae2, and @srosenberg)

___
*[`-- commits` line 39 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87259#-NSlSFxWD2XT_DOUCzru):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Although actually, we are adding an extra column to all of these SHOW commands. These really should be a separate commit -- maybe a separate PR altogether. I'll do that now since this PR is starting to explode with changes.
</blockquote></details>

Split into a new PR: https://github.com/cockroachdb/cockroach/pull/101334

**Review by rytaft — COMMENTED** [review]
> Reviewed 1 of 40 files at r2, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87259)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @mgartner, @michae2, and @srosenberg)

___
*[`pkg/sql/catalog/descpb/structured.proto` line 506 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87259#-NSlUTe41hlO_oWhpaYd:-NSqJWNGD6zctLvXKgqt:b6oeuvz) ([raw file](https://github.com/cockroachdb/cockroach/blob/818f6bdd599475a8b196567b6d5c6d235801f4f5/pkg/sql/catalog/descpb/structured.proto#L506)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

So... we bootstrap a node with hardcoded system table definitions. In mixed version test config, nodes are bootstraped with older version of the system tables which don't include the new field in the protobuf. But then [this validation](https://github.com/cockroachdb/cockroach/blob/372cf8dd50b1d031b8d751611932480301250d81/pkg/sql/logictest/logic.go#L3880) is run on the new node, and and the new field is populated in the protobuf :(

I think we could skip the roundtrip validation in the mixed version config.
</blockquote></details>

Thanks, I just updated logic.go to check `DisableUpgrade`, since only local-mixed-22.2-23.1 has that set.

**Comment by chengxiong-ruan** [comment]
*[`pkg/sql/logictest/logic.go` line 3866 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/87259#-NSqNiF_0DOcRPEtb77E:-NSqNiF_0DOcRPEtb77F:b-rgnaug) ([raw file](https://github.com/cockroachdb/cockroach/blob/e837d7f26bc5237cf9b677d6629da2eafaca2d1c/pkg/sql/logictest/logic.go#L3866)):*
> ```Go
> 		// this may fail if we're in between migrations that
> 		// upgrade the descriptors.
> 		if !t.cfg.UseCockroachGoTestserver && !t.cfg.DisableUpgrade {
> ```

Thanks, could you also add `cfg.BootstrapVersion != clusterversion.Key(0)` to it? so it'd look like this:

`if !t.cfg.UseCockroachGoTestserver && !(t.cfg.DisableUpgrade && cfg.BootstrapVersion != clusterversion.Key(0)) `?

Also some commentary would be highly appreciated, thanks!

**Review by mgartner — APPROVED** [review]
:lgtm: modulo @chengxiong-ruan's suggestions

> Reviewed 1 of 2 files at r4, 15 of 32 files at r5, 2 of 3 files at r6, 5 of 5 files at r7, 8 of 18 files at r8, 3 of 31 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87259#-:-NSqQkU74Drd0cfuivYg:b5g9etx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @michae2, and @srosenberg)

___
*[`-- commits` line 39 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87259#-NSlSFxWD2XT_DOUCzru):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Split into a new PR: https://github.com/cockroachdb/cockroach/pull/101334
</blockquote></details>

Nice, thanks!
___
*[`pkg/sql/catalog/catformat/index.go` line 189 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87259#-NSlTISG2T_i060crIYn:-NSqOwse0bAg_j8OQ-8t:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/818f6bdd599475a8b196567b6d5c6d235801f4f5/pkg/sql/catalog/catformat/index.go#L189)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Yea, good point. Let's try the float and if it makes tests flaky we can consider switching to an int.
</blockquote></details>

:+1:

**Review by rytaft — COMMENTED** [review]
TFTR!

> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87259#-:-NSqqU56DkmrqQ87l9_H:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @herkolategan, @mgartner, @michae2, and @srosenberg)

___
*[`pkg/sql/logictest/logic.go` line 3866 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/87259#-NSqNiF_0DOcRPEtb77E:-NSqqPKpAKBNkVqajh__:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e837d7f26bc5237cf9b677d6629da2eafaca2d1c/pkg/sql/logictest/logic.go#L3866)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

Thanks, could you also add `cfg.BootstrapVersion != clusterversion.Key(0)` to it? so it'd look like this:

`if !t.cfg.UseCockroachGoTestserver && !(t.cfg.DisableUpgrade && cfg.BootstrapVersion != clusterversion.Key(0)) `?

Also some commentary would be highly appreciated, thanks!
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
Looks like all tests are passing now. @chengxiong-ruan did you want to take another look at this or is it good to go? @srosenberg it looks like you were drafting a comment -- anything you want me to change?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87259#-:-NSr66vF65K4zp0No2KM:b-98odro)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @herkolategan, @mgartner, @michae2, and @srosenberg)

**Review by chengxiong-ruan — APPROVED** [review]
LGTM!

**Review by rytaft — APPROVED** [review]
TFTRs! @srosenberg I can make any additional changes in another PR if you have any comments.

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87259#-:-NSvGi8F1hNr22E-tB2o:b-rjhzdd)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @herkolategan, @mgartner, @michae2, and @srosenberg)

**Pull request merged**
