### PR TITLE
storage: switch Store.{replicas,replicaQueues} from sync.Map to IntMap

### PR DESCRIPTION
**Pull request by petermattis**
Motivated by seeing sync.Map.Load() high on profiles when there are large
numbers of replicas on a node. See #17609.

```
name               old time/op  new time/op  delta
StoreGetReplica-8  9.12ns ±10%  3.22ns ± 5%  -64.65%  (p=0.000 n=10+8)  
```

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
:lgtm_strong:

The switch of `IntMap.read` from an `atomic.Value` to an `unsafe.Pointer` should certainly be upstreamed. Out of curiosity, did you look into how much each of the three changes (the `int` key specialization to preventing boxing/unboxing, the `unsafe.Pointer` value specialization, and the `IntMap.read` change) individually impacted the benchmarks? Or is it difficult to separate them out?

Also, we might as well use this for `storeMap` and some of the `RaftTransport` maps.

---

Reviewed 4 of 4 files at r1, 4 of 4 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17625#-:-KrSqhZcPj3UHrH2TFf2:bjeutat)*

**Comment by petermattis** [comment]
The `IntMap.read` change provided a 14% improvement in the `StoreGetReplica` benchmark. I didn't break apart the specialization of the key and value, but that change account for the majority of the benefit.

> Also, we might as well use this for storeMap and some of the RaftTransport maps.

Yes, we can use it for everything except `RaftTransport.handlers`. Well, I suppose we could use it for that too if we store a pointer to the handler. 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17625#-:-KrT3jElkatDr3qGT-ls:b-nkbd0i)*

**Comment by petermattis** [comment]
Btw, do you happen to know how to run benchmarks in the Go runtime:

```
~/Development/go-tip/src/sync master go test -v -run - -bench .
mutex.go:14:2: use of internal package not allowed
```

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17625#-:-KrT4F_AZemf7fbfzJVB:bn5b5kj)*

**Comment by petermattis** [comment]
Add 2 more commits to convert `RaftTransport` and `Stores` to use `IntMap`.

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 6 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17625#-:-KrWILSDG1S5zE2yDfOv:bnfp4nl)*

**Comment by nvanbenschoten** [comment]
I'm not sure about running benchmarks in the Go runtime. I guess you could just create a wrapper benchmark around whatever you want to measure, but it seems strange that you'd need to.

**Pull request merged**
