### PR TITLE
sql: add an example distsql tenant logic test with split ranges

### PR DESCRIPTION
**Pull request by rharding6373**
This PR adds an example distsql logic test, `distsql_tenant_locality`,
that splits ranges and assigns them to spcific leaseholders, for future
use in testing locality-aware distsql changes.

This PR also introduces the following logic test improvements:
* A new logic test config for multi-tenant multi-region testing,
    `3node-tenant-multiregion`.
* Blocklists in logic tests can now include default config lists.
* Skip directives in logic tests can now include default config lists.
* A default config list for multi-tenant configurations that include
    `3node-tenant` and `3node-tenant-multi-region`.
* `TestTenantLogic` and `TestTenantExecBuild` now run the 3 node
      tenant configuration by default and any logic/exec builder tests
      that have the 3 node tenant multiregion directive.

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 24 of 26 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82844)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @rharding6373)

___
*[`pkg/sql/logictest/logic.go` line 2258 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82844#-N4bkQL84HJ-rco3mBhp:-N4bkQL84HJ-rco3mBhq:b-vmqllr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e97c11dd86581b24d8c791f98408e7dc0ab7aee/pkg/sql/logictest/logic.go#L2258)):*
> ```Go
> 		// config list.
> 		var blockedConfigNames []string
> 		switch blockedConfig {
> ```

nit: maybe introduce a helper function for this switch? I think we now have it in three places.
___
*[`pkg/sql/logictest/logic.go` line 4408 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82844#-N4bk6t70O5sVqBJs0Ac:-N4bk6t70O5sVqBJs0Ad:b-3ifgve) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3370ab16bb0f7ec23e4125b89c329bd0e755c84/pkg/sql/logictest/logic.go#L4408)):*
> ```Go
> 						!cfg.useTenant &&
> 						cfg.numNodes <= 5 {
> 						// We also cannot parallelise tests that use tenant servers
> ```

nit: Oliver wouldn't not approve of this change :D
___
*[`pkg/sql/logictest/testdata/logic_test/distsql_tenant` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82844#-N4bkwrq1sYUQmi3xTp0:-N4bkwrr1m1Zcv6FWLQz:bav86na) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e97c11dd86581b24d8c791f98408e7dc0ab7aee/pkg/sql/logictest/testdata/logic_test/distsql_tenant#L1)):*
> ```
> # LogicTest: 3node-tenant 3node-tenant-multiregion
> ```

nit: use `3node-tenant-default-configs`?
___
*[`pkg/sql/logictest/testdata/logic_test/distsql_tenant_locality` line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82844#-N4bmMBc2P_h5FJm4oM2:-N4bmMBc2P_h5FJm4oM3:b6fvdqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e97c11dd86581b24d8c791f98408e7dc0ab7aee/pkg/sql/logictest/testdata/logic_test/distsql_tenant_locality#L35)):*
> ```
> user root
> 
> # TODO(harding): Once locality-aware distribution is implemented, this should
> ```

We already can execute the query in a distributed fashion, right? What's stopping us from testing that here?
___
*[`pkg/sql/logictest/testdata/logic_test/distsql_tenant_locality` line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82844#-N4blfP78WDXqaKgkI0Q:-N4blfP78WDXqaKgkI0R:bb1cqq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e97c11dd86581b24d8c791f98408e7dc0ab7aee/pkg/sql/logictest/testdata/logic_test/distsql_tenant_locality#L39)):*
> ```
> # only utilize the gateway instance.
> query T
> EXPLAIN (DISTSQL) SELECT * FROM t WHERE v = 1 OR v = 2 OR v = 3
> ```

nit: is the goal of this test is to verify the physical planning? If so, it should go into the execbuilder tests. If - when the TODO is addressed - we want to also actually run the query, then that should stay in the main logic test folder.

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82844)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @yuzefovich)

___
*[`pkg/sql/logictest/logic.go` line 2258 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82844#-N4bkQL84HJ-rco3mBhp:-N4c2K8L1_d7SmOxw8Uk:b-wdadj2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e97c11dd86581b24d8c791f98408e7dc0ab7aee/pkg/sql/logictest/logic.go#L2258)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: maybe introduce a helper function for this switch? I think we now have it in three places.
</blockquote></details>

Good idea. Cleaned this up a bit.
___
*[`pkg/sql/logictest/logic.go` line 4408 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82844#-N4bk6t70O5sVqBJs0Ac:-N4c30zp6gA94RGg4p59:btse6j4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3370ab16bb0f7ec23e4125b89c329bd0e755c84/pkg/sql/logictest/logic.go#L4408)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: Oliver wouldn't not approve of this change :D
</blockquote></details>

Sigh...fine, I can be more open to alternate spellings. I've been spending lots of time lately in this file and it's been buggering (:-O) me, that's all.

In my defen[s|c]e, this is the only usage of this particular spelling outside of pkg/ui.
___
*[`pkg/sql/logictest/testdata/logic_test/distsql_tenant_locality` line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82844#-N4bmMBc2P_h5FJm4oM2:-N4c8Q49ALzG22v-puCs:b-csg05z) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e97c11dd86581b24d8c791f98408e7dc0ab7aee/pkg/sql/logictest/testdata/logic_test/distsql_tenant_locality#L35)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

We already can execute the query in a distributed fashion, right? What's stopping us from testing that here?
</blockquote></details>

The query currently only uses a single span, so it won't be distributed.
___
*[`pkg/sql/logictest/testdata/logic_test/distsql_tenant_locality` line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82844#-N4blfP78WDXqaKgkI0Q:-N4c6lZSE-NThUJy00br:b-o0fhrw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e97c11dd86581b24d8c791f98408e7dc0ab7aee/pkg/sql/logictest/testdata/logic_test/distsql_tenant_locality#L39)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: is the goal of this test is to verify the physical planning? If so, it should go into the execbuilder tests. If - when the TODO is addressed - we want to also actually run the query, then that should stay in the main logic test folder.
</blockquote></details>

I only included it as an example placeholder. The purpose of the test as a whole is to demonstrate how to set up the distribution for future testing. I removed the query altogether and just left a TODO, since it doesn't fulfill any real purpose in this PR.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82844#-:-N4cIII35oGnjfPu2Yq3:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @rharding6373)

___
*[`pkg/sql/logictest/testdata/logic_test/distsql_tenant_locality` line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82844#-N4blfP78WDXqaKgkI0Q:-N4cI3e24SEGngYhmIup:bcr5s31) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e97c11dd86581b24d8c791f98408e7dc0ab7aee/pkg/sql/logictest/testdata/logic_test/distsql_tenant_locality#L39)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I only included it as an example placeholder. The purpose of the test as a whole is to demonstrate how to set up the distribution for future testing. I removed the query altogether and just left a TODO, since it doesn't fulfill any real purpose in this PR.
</blockquote></details>

Got it, thanks.

**Comment by rharding6373** [comment]
TFTR!

bors r+

**Comment by rharding6373** [comment]
The extra tenant logic test config was causing a test timeout in bors. The new config wasn't adding much value as a default test config, so I provided an option in the logic test infrastructure to provide a config that could be run only if it was included in a test directive.

**Review by yuzefovich — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82844)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @rharding6373)

___
*[`pkg/sql/logictest/logic.go` line 21 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82844#-N55utb_0Nfq0aaJCqk-:-N55utba85QMTdvC0UdI:boy4q7u) ([raw file](https://github.com/cockroachdb/cockroach/blob/a068d9baf8686aa53488a9bd64b9b7763ba5a5f6/pkg/sql/logictest/logic.go#L21)):*
> ```Go
> 	"flag"
> 	"fmt"
> 	"github.com/cockroachdb/cockroach/pkg/build/bazel"
> ```

nit: the order is off.

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82844)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @yuzefovich)

___
*[`pkg/sql/logictest/logic.go` line 21 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82844#-N55utb_0Nfq0aaJCqk-:-N55wFJoAHjyeNBTEYcv:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/a068d9baf8686aa53488a9bd64b9b7763ba5a5f6/pkg/sql/logictest/logic.go#L21)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: the order is off.
</blockquote></details>

Fixed.

**Comment by rharding6373** [comment]
TFTR!

bors r+

**Pull request merged**
