### PR TITLE
sql: add memory monitoring for leased descriptors

### PR DESCRIPTION
**Pull request by jameswsj10**
See #67049. Previously, there was no memory metric that was being kept in
track of for lease acquire and release events. This change allows us to
observe the memory usage of leased descriptors at the manager level.

Release note (sql change): memory monitoring for leased descriptors
for better observability.

### CODE REVIEW

**Comment by ajwerner** [comment]
I feel like you picked up changes you didn't mean to somehow.

**Comment by RichardJCai** [comment]
> I feel like you picked up changes you didn't mean to somehow.

Rebasing onto master might fix it. (Remove the other commits from this Github PR)

**Review by jameswsj10 — COMMENTED** [review]
thanks Andrew and Richard! It should only reflect my changes now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73579#-:-MqQEA3IAZu9jEFIL5GM:bdqofti)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

**Comment by ajwerner** [comment]
please rebase master again and stress the `lease` package, it seems to have some timeout bug.

**Pull request closed without merging**
