### PR TITLE
spanconfig/store: implement cloning and an overlapping iterator

### PR DESCRIPTION
**Pull request by irfansharif**
We'll use both in spanconfig.Reconciler (#71994).

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73402)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @irfansharif, and @nvanbenschoten)

___
*[pkg/spanconfig/spanconfigstore/store.go, line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73402#-MpxLJi25x8s_U5N_EMM:-MpxLJi25x8s_U5N_EMN:b-168kd8) ([raw file](https://github.com/cockroachdb/cockroach/blob/053b76b5c70e47f9b0f0809bc623a151678b447d/pkg/spanconfig/spanconfigstore/store.go#L146)):*
> ```Go
> // Clone returns a copy of the underlying Store.
> func (s *Store) Clone(ctx context.Context) *Store {
> 	clone := New(s.fallback)
> ```

don't we need to appropriately increment the idAlloc in the clone?
___
*[pkg/spanconfig/spanconfigstore/store.go, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73402#-MpxJs9n8e-gxsVU7f-Y:-MpxJs9n8e-gxsVU7f-Z:b-o54lsf) ([raw file](https://github.com/cockroachdb/cockroach/blob/053b76b5c70e47f9b0f0809bc623a151678b447d/pkg/spanconfig/spanconfigstore/store.go#L148)):*
> ```Go
> 	clone := New(s.fallback)
> 	for _, entry := range s.GetAllOverlapping(ctx, keys.EverythingSpan) {
> 		clone.Apply(ctx, false /* */, spanconfig.Update{
> ```

`/* */`
___
*[pkg/spanconfig/spanconfigstore/store.go, line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73402#-MpxJxoPBEw6wnPjNZHf:-MpxJxoPBEw6wnPjNZHg:blyp91x) ([raw file](https://github.com/cockroachdb/cockroach/blob/053b76b5c70e47f9b0f0809bc623a151678b447d/pkg/spanconfig/spanconfigstore/store.go#L158)):*
> ```
> // GetAllOverlapping retrieves the set of entries that overlap with the given
> // span in sorted order.
> func (s *Store) GetAllOverlapping(_ context.Context, sp roachpb.Span) []roachpb.SpanConfigEntry {
> ```
nit: is this really better than

```
// ForAllOverlapping retrieves the set of entries that overlap with the given
// span in non-decreasing order.
func (s *Store) ForEachOverlapping(_ context.Context, sp roachpb.Span, f func(e roachpb.SpanConfigEntry) error) error {
    	s.mu.RLock()
	defer s.mu.RUnlock()

	// Iterate over all overlapping ranges and return corresponding span config
	// entries.
        for _, overlapping := range s.mu.tree.Get(sp.AsRange()) {
            for _, e := range overlapping {
                  if err := f(e); err != nil {
                       if iterutil.Done(err) {
                            err = nil
                       }
                       return err
                  }
            }
        }        
}
```

**Review by irfansharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73402)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @nvanbenschoten)

___
*[pkg/spanconfig/spanconfigstore/store.go, line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73402#-MpxLJi25x8s_U5N_EMM:-MpxnAwV0ni_nRsqXhFM:b-o30zzm) ([raw file](https://github.com/cockroachdb/cockroach/blob/053b76b5c70e47f9b0f0809bc623a151678b447d/pkg/spanconfig/spanconfigstore/store.go#L146)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

don't we need to appropriately increment the idAlloc in the clone?
</blockquote></details>

Do we? I don't see how users of the cloned store would care about it using different internal IDs; raw `storeEntry` types from one store aren't compared across clones, just the embedded roachpb.SpanConfigEntries.
___
*[pkg/spanconfig/spanconfigstore/store.go, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73402#-MpxJs9n8e-gxsVU7f-Y:-MpxnAfY2tS0EQD0gOvk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/053b76b5c70e47f9b0f0809bc623a151678b447d/pkg/spanconfig/spanconfigstore/store.go#L148)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

`/* */`
</blockquote></details>

Done.
___
*[pkg/spanconfig/spanconfigstore/store.go, line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73402#-MpxJxoPBEw6wnPjNZHf:-Mpxngu7AZjYf1FPasMH:ba2o7y) ([raw file](https://github.com/cockroachdb/cockroach/blob/053b76b5c70e47f9b0f0809bc623a151678b447d/pkg/spanconfig/spanconfigstore/store.go#L158)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> // GetAllOverlapping retrieves the set of entries that overlap with the given
> // span in sorted order.
> func (s *Store) GetAllOverlapping(_ context.Context, sp roachpb.Span) []roachpb.SpanConfigEntry {
> ```
nit: is this really better than

```
// ForAllOverlapping retrieves the set of entries that overlap with the given
// span in non-decreasing order.
func (s *Store) ForEachOverlapping(_ context.Context, sp roachpb.Span, f func(e roachpb.SpanConfigEntry) error) error {
    	s.mu.RLock()
	defer s.mu.RUnlock()

	// Iterate over all overlapping ranges and return corresponding span config
	// entries.
        for _, overlapping := range s.mu.tree.Get(sp.AsRange()) {
            for _, e := range overlapping {
                  if err := f(e); err != nil {
                       if iterutil.Done(err) {
                            err = nil
                       }
                       return err
                  }
            }
        }        
}
```
</blockquote></details>

Done, updated tests accordingly.

**Review by irfansharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73402)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @nvanbenschoten)

___
*[pkg/spanconfig/spanconfigstore/store.go, line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73402#-MpxLJi25x8s_U5N_EMM:-MpxpNGW9rApPPCMT3k3:b-luygiq) ([raw file](https://github.com/cockroachdb/cockroach/blob/053b76b5c70e47f9b0f0809bc623a151678b447d/pkg/spanconfig/spanconfigstore/store.go#L146)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Do we? I don't see how users of the cloned store would care about it using different internal IDs; raw `storeEntry` types from one store aren't compared across clones, just the embedded roachpb.SpanConfigEntries.
</blockquote></details>

Renamed to Copy instead, perhaps that makes it clearer?

**Review by ajwerner — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73402)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[pkg/spanconfig/spanconfigstore/store.go, line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73402#-MpxLJi25x8s_U5N_EMM:-MpxuGij1Xg51xR3GAu2:b-dq6h3p) ([raw file](https://github.com/cockroachdb/cockroach/blob/053b76b5c70e47f9b0f0809bc623a151678b447d/pkg/spanconfig/spanconfigstore/store.go#L146)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Renamed to Copy instead, perhaps that makes it clearer?
</blockquote></details>

Either way. This is fine. 
___
*[pkg/spanconfig/spanconfigstore/store.go, line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73402#-MpxJxoPBEw6wnPjNZHf:-MpxudE37mXVm3M67DuN:bv7a5ch) ([raw file](https://github.com/cockroachdb/cockroach/blob/053b76b5c70e47f9b0f0809bc623a151678b447d/pkg/spanconfig/spanconfigstore/store.go#L158)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Done, updated tests accordingly.
</blockquote></details>

You could just `_ = s.ForEachOverlapping` and I wouldn't mind. I think it's a fine contract that you won't return an error if the function doesn't. I used to do the whole boolean thing but then there were too many bugs between `done` vs `wantMore` for the meaning of the returned boolean. Anyway, thanks.

**Comment by irfansharif** [comment]
Thanks for the quick review!

bors r+

**Pull request merged**
