### PR TITLE
vendor: upgrade jordanlewis/gcassert

### PR DESCRIPTION
**Pull request by yuzefovich**
**lint: add missing packages for GCAssert**

This commit adds some packages for the linter to run against which
already have some `gcassert` assertions. It also adds a linter for
making sure that we don't forget to include all packages that we use
gcassert in to be checked.

Release note: None

**vendor: upgrade jordanlewis/gcassert**

This also required bumping `x/tools`.

Release note: None

Epic: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
It seems like `TestGolint` becomes extremely slow due to a bump of dependencies in the last commit - it took almost an hour on my gceworker when nothing else was running on it:
```
PASS: TestLint/TestGolint (2734.25s)
```

**Comment by yuzefovich** [comment]
@rickystewart I wonder whether I could get some pointers from you to address #65485. When I run GCAssert linter locally via `./dev lint -f=TestGCAssert` it succeeds (and the same for manual run via `make`), yet when run through bazel CI it fails.

**Comment by rickystewart** [comment]
@yuzefovich The gcassert test has never worked in Bazel. If it's working for you locally it's probably that you've `dev gen`'ed and that's causing everything to work. Probably you could `git clean -dfx pkg` and it will start failing for you locally too.

**Comment by yuzefovich** [comment]
Indeed, Ricky, you're spot on, thanks.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Do we have a way to ensure we aren't adding assertions to packages the linter doesn't check?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90807#-:-NGYau72DCtckF660UwI:b-pod6ug)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by yuzefovich — COMMENTED** [review]
Good point, extended the first commit to also include the linter to not miss any more packages in the future, PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90807#-:-NGYhUz194LdMUuIGaFI:bgs9j2w)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by DrewKimball — APPROVED** [review]
:lgtm: Thanks for adding that!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90807#-:-NGYm5J02_Zg3XKa7Pp5:b-x342cm)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
Thanks for the idea and review!

bors r+

**Pull request merged**
