### PR TITLE
distsql: add EXPLAIN (DIST_SQL), tests for auto mode

### PR DESCRIPTION
**Pull request by RaduBerinde**
See the individual commits. The first ones are just some cleanups that make this easier.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13754)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
I am open to suggestions about the schema and/or field names for `EXPLAIN (DIST_SQL)` (see `explainDistSQLNode`).

**Comment by knz** [comment]
First suggestion: have the xplain mode called `distsql` instead of `dist_sql`.

Then I'm not too fond of the schema indeed.

What about having just one row of result, with columns of the right types for each field?
Proposed schema:
- "Automatic" / bool 
- "URL" / string (can become URL once we support that later)
- "JSON" / string (can become JSON once we support that)

Also this way a user can extract just the json field with `select json from [explain(distsql) ...]`
and that would also be typed properly once we support json fields.

---

Reviewed 4 of 4 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, 9 of 9 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql_physical_planner.go, line 296 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-Kdg83SVdz-H-qXTqwl7:-Kdg83SVdz-H-qXTqwl8:b-zeu799) ([raw file](https://github.com/cockroachdb/cockroach/blob/92240aa52431c10bf7071c8ff808e7c80927b39c/pkg/sql/distsql_physical_planner.go#L296)):*
> ```Go
> 		}
> 		// We should distribute aggregations if possible.
> 		return rec.compose(shouldDistribute), nil
> ```

That was a bug right? Is there a way to test?

---

*[pkg/sql/executor.go, line 1344 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-Kdg87WXxpG2jNp0L7uq:-Kdg87WXxpG2jNp0L7ur:b-kxc7ii) ([raw file](https://github.com/cockroachdb/cockroach/blob/a964d035f35a954ea270e706f041c518a21bdab8/pkg/sql/executor.go#L1344)):*
> ```Go
> 	} else {
> 		// Trigger limit propagation.
> 		setUnlimited(plan)
> ```

That was a bug? Perhaps a test for this would be warranted.

---

*[pkg/sql/explain.go, line 57 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-Kdg7mN-u44IIMshHe-T:-Kdg7mN-u44IIMshHe-U:b7qmg4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/207a7d3ac0d742f8c4a12e17f6f2e85f0a0fcb7b/pkg/sql/explain.go#L57)):*
> ```Go
> 		newMode := explainNone
> 		switch {
> 		case strings.EqualFold(opt, "DEBUG"):
> ```

While you're at it please lowercase/uppercase `opt` once and then just use a plain case each time.

---

*[pkg/sql/explain.go, line 272 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-KdgDkL0T2d3Qys-AZ08:-KdgDkL0T2d3Qys-AZ09:b-5msyjl) ([raw file](https://github.com/cockroachdb/cockroach/blob/41222ececedff8323b19aa4c98535290e8a45514/pkg/sql/explain.go#L272)):*
> ```Go
> func (*explainDistSQLNode) MarkDebug(_ explainMode)  {}
> func (*explainDistSQLNode) DebugValues() debugValues { return debugValues{} }
> func (n *explainDistSQLNode) Close()                 {}
> ```

`n.plan` needs to be `Close()`d somewhere.

---

*[pkg/sql/explain.go, line 275 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-KdgEMnwIC3Yx7nptKM6:-KdgEMnwIC3Yx7nptKM7:bsjrd9r) ([raw file](https://github.com/cockroachdb/cockroach/blob/8846c670d92ae5d10be98833a8f162f5b3bfc850/pkg/sql/explain.go#L275)):*
> ```Go
> 
> func (*explainDistSQLNode) Columns() ResultColumns {
> 	return ResultColumns{
> ```

I recommend storing the column set in the node instead of re-instantiating it on each call to `Columns()`.

---

*[pkg/sql/limit_opt.go, line 148 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-Kdg8FtgPX7vr963Iwbv:-Kdg8FtgPX7vr963Iwbw:b3qn7lu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a964d035f35a954ea270e706f041c518a21bdab8/pkg/sql/limit_opt.go#L148)):*
> ```Go
> 		setUnlimited(n.plan)
> 	case *explainPlanNode:
> 		if n.expanded {
> ```

Not sure this belongs to `.expanded`, isn't `.optimized` more appropriate? (I'm not 100% sure.)

---

*[pkg/sql/distsqlrun/flow_diagram.go, line 388 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-Kdg6wR4WMv09HBLKKhC:-Kdg6wR4WMv09HBLKKhD:bfukewj) ([raw file](https://github.com/cockroachdb/cockroach/blob/220169aafc1c5c99a8c95277a4139528dd35b492/pkg/sql/distsqlrun/flow_diagram.go#L388)):*
> ```Go
> 		return "", url.URL{}, err
> 	}
> 	// TODO(radu): using raduberinde.github.io is temporary.
> ```

This is a serious issue. There's no way we're going to ship v1.0 unless this is addressed.
Please reference #13758 in this TODO.

---

*[pkg/sql/testdata/explain_distsql, line 11 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-KdgEE9YpEKwex414RqI:-KdgEE9YpEKwex414RqJ:b-k7idvz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8846c670d92ae5d10be98833a8f162f5b3bfc850/pkg/sql/testdata/explain_distsql#L11)):*
> ```
> EXPLAIN (DIST_SQL) SELECT * FROM kv
> 
> # Full table scan - distribute.
> ```

Have at least one of the tests use `colname` to test the column titles.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-:-KdgF0YeXruNsG2wXtt7:bqysnbs)*

**Comment by knz** [comment]
Also please use the syntax `select ... from [explain(distsql) ...]` to test without `noplan` specified.

**Comment by andreimatei** [comment]
:lgtm: with Rafa's comments

+1 to the comment about using `select ... from [explain(distsql) ...]`. Hott.

---

Review status: all files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql_physical_planner.go, line 295 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-KdgqvEo6VdTwReihUK6:-KdgqvEo6VdTwReihUK7:b-m1syke) ([raw file](https://github.com/cockroachdb/cockroach/blob/92240aa52431c10bf7071c8ff808e7c80927b39c/pkg/sql/distsql_physical_planner.go#L295)):*
> ```Go
> 			return 0, err
> 		}
> 		// We should distribute aggregations if possible.
> ```

nit: "we should distribute" in this comment sounds like a TODO. I'd say just "we distribute", regardless of the enum name.

---

*[pkg/sql/explain.go, line 37 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-KdgtQ0SV62g2uAlEaXg:-KdgtQ0SV62g2uAlEaXh:b-lli9e6) ([raw file](https://github.com/cockroachdb/cockroach/blob/41222ececedff8323b19aa4c98535290e8a45514/pkg/sql/explain.go#L37)):*
> ```Go
> 	explainPlan
> 	explainTrace
> 	explainDistSQL
> ```

Mind adding a comment here about what this explain mode will do? (or link to `explainDistSQLNode`, but it'd be cool if that had a more descriptive comment too about the results)

---

*[pkg/sql/explain.go, line 100 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-Kdgtn1llxOvCYOLH-9d:-Kdgtn1llxOvCYOLH-9e:b8nyyc5) ([raw file](https://github.com/cockroachdb/cockroach/blob/41222ececedff8323b19aa4c98535290e8a45514/pkg/sql/explain.go#L100)):*
> ```Go
> 		case strings.EqualFold(opt, "DIST_SQL"):
> 			mode = explainDistSQL
> 		case strings.EqualFold(opt, "NOPLAN"):
> ```

is the `NOPLAN` option valid only in conjunction with `DIST_SQL`? Can we error otherwise?

---

*[pkg/sql/explain.go, line 261 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-Kdgu0etJtvIpXbx65so:-Kdgu0etJtvIpXbx65sp:b-fll633) ([raw file](https://github.com/cockroachdb/cockroach/blob/41222ececedff8323b19aa4c98535290e8a45514/pkg/sql/explain.go#L261)):*
> ```Go
> type explainDistSQLNode struct {
> 	plan           planNode
> 	distSQLPlanner *distSQLPlanner
> ```

mind commenting all the members but `plan, distSQLPlanner`? :)

---

*[pkg/sql/explain.go, line 266 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-KdguXajiLBfXQ_dIhmU:-KdguXakkHVO8CJmykPZ:b-9w3xp3) ([raw file](https://github.com/cockroachdb/cockroach/blob/41222ececedff8323b19aa4c98535290e8a45514/pkg/sql/explain.go#L266)):*
> ```Go
> 
> 	rowIdx int
> 	rows   []parser.Datums
> ```

I would get rid of `rowIdx`, rename `rows` to `remainingRows`, and keep reslicing that when rows are consumed.

---

*[pkg/sql/explain.go, line 289 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-Kdgw3X0KEUYQQ8OyNaV:-Kdgw3X0KEUYQQ8OyNaW:bbf4nez) ([raw file](https://github.com/cockroachdb/cockroach/blob/8846c670d92ae5d10be98833a8f162f5b3bfc850/pkg/sql/explain.go#L289)):*
> ```Go
> 		return err
> 	}
> 	autoStr := "No"
> ```

how about making this a boolean?

---

*[pkg/sql/limit_opt.go, line 148 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-Kdg8FtgPX7vr963Iwbv:-Kdgs7UD96gTkwy-Cf6R:b-yz5c5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/a964d035f35a954ea270e706f041c518a21bdab8/pkg/sql/limit_opt.go#L148)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Not sure this belongs to `.expanded`, isn't `.optimized` more appropriate? (I'm not 100% sure.)
</blockquote></details>

I see that `doExpandPlan` calls `setUnlimited()` on `n.plan` for an `explainPlanNode`. Isn't that redundant with this call

---

*[pkg/sql/distsqlplan/physical_plan.go, line 679 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-KdgpcmYdCSxfYbf_43m:-KdgpcmYdCSxfYbf_43n:bwykl80) ([raw file](https://github.com/cockroachdb/cockroach/blob/220169aafc1c5c99a8c95277a4139528dd35b492/pkg/sql/distsqlplan/physical_plan.go#L679)):*
> ```Go
> // plan.
> func (p *PhysicalPlan) GenerateFlowSpecs(
> 	nodeAddresses map[roachpb.NodeID]string,
> ```

you're only using `nodeAddresses` for its length... I would get rid of it.

---

*[pkg/sql/distsqlplan/physical_plan.go, line 691 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-KdgqK-uh2Zbp9loqRgE:-KdgqK-uh2Zbp9loqRgF:b-73yuro) ([raw file](https://github.com/cockroachdb/cockroach/blob/220169aafc1c5c99a8c95277a4139528dd35b492/pkg/sql/distsqlplan/physical_plan.go#L691)):*
> ```Go
> 		flowSpec, ok := flows[proc.Node]
> 		if !ok {
> 			flowSpec = distsqlrun.FlowSpec{FlowID: flowID}
> ```

don't we need to initialize `FlowID` otherwise?

---

*[pkg/sql/distsqlrun/flow_diagram.go, line 388 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-Kdg6wR4WMv09HBLKKhC:-Kdguz3Whh4wRYX1TWQm:bps9hus) ([raw file](https://github.com/cockroachdb/cockroach/blob/220169aafc1c5c99a8c95277a4139528dd35b492/pkg/sql/distsqlrun/flow_diagram.go#L388)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This is a serious issue. There's no way we're going to ship v1.0 unless this is addressed.
Please reference #13758 in this TODO.
</blockquote></details>

I was just talking to @kuanluo about displaying plans in our UI. This is to inform her of what's about to go on - Radu's introducing a `EXPLAIN (DIST_SQL) SELECT ...` query syntax which will generate a link to `raduberinde.github.io`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-:-KdgwEMleB5wpu2-VGA7:bxb9322)*

**Comment by RaduBerinde** [comment]
The suggestion to use columns is great!! Thanks, switching to that!

---

Review status: all files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql_physical_planner.go, line 296 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-Kdg83SVdz-H-qXTqwl7:-Kdh9jyNPGT-_X4F0y9X:b3kt5kk) ([raw file](https://github.com/cockroachdb/cockroach/blob/92240aa52431c10bf7071c8ff808e7c80927b39c/pkg/sql/distsql_physical_planner.go#L296)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

That was a bug right? Is there a way to test?
</blockquote></details>

yes, the new tests i'm adding (that's how it was found)

---

*[pkg/sql/explain.go, line 272 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-KdgDkL0T2d3Qys-AZ08:-KdhA46JDPSh_LWe-rzf:b-t8jykj) ([raw file](https://github.com/cockroachdb/cockroach/blob/41222ececedff8323b19aa4c98535290e8a45514/pkg/sql/explain.go#L272)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`n.plan` needs to be `Close()`d somewhere.
</blockquote></details>

even if it wasn't `Start`ed?

---

*[pkg/sql/limit_opt.go, line 148 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-Kdg8FtgPX7vr963Iwbv:-KdhBcDHlSh6rhdMz_rC:b-1il7tb) ([raw file](https://github.com/cockroachdb/cockroach/blob/a964d035f35a954ea270e706f041c518a21bdab8/pkg/sql/limit_opt.go#L148)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I see that `doExpandPlan` calls `setUnlimited()` on `n.plan` for an `explainPlanNode`. Isn't that redundant with this call
</blockquote></details>

Indeed it looks redundant, I will try to remove it altogether.

---

*[pkg/sql/distsqlplan/physical_plan.go, line 691 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-KdgqK-uh2Zbp9loqRgE:-KdhAeAdFH8dOPg2HRGd:bwzx4ht) ([raw file](https://github.com/cockroachdb/cockroach/blob/220169aafc1c5c99a8c95277a4139528dd35b492/pkg/sql/distsqlplan/physical_plan.go#L691)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

don't we need to initialize `FlowID` otherwise?
</blockquote></details>

if it's in the map, we must have already initialized it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-:-Kdh9bSkJU76OhAZl6Y4:bbp8nuc)*

**Comment by RaduBerinde** [comment]
Wait, when I was working on this change, I assumed that you can't SELECT FROM an EXPLAIN node.. (otherwise I would have used a LIMIT instead of NOPLAN). I verified and indeed you can't.
Note that I can't have any plan JSONs or URLs in the tests because they are non-determinstic (because of the fake span resolver).

---

Review status: all files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-:-KdhE4mGhYHxz1yprtRg:b8gcq7a)*

**Comment by knz** [comment]
What do you mean "you can't"?
This works here:
```
root@:26257/> select * from [explain select 1];
+-------+---------+-------+-------------+
| Level |  Type   | Field | Description |
+-------+---------+-------+-------------+
|     0 | render  |       |             |
|     1 | nullrow |       |             |
+-------+---------+-------+-------------+
(2 rows)
root@:26257/> select * from [explain select 1] limit 1;
+-------+--------+-------+-------------+
| Level |  Type  | Field | Description |
+-------+--------+-------+-------------+
|     0 | render |       |             |
+-------+--------+-------+-------------+
(1 row)

```

**Comment by RaduBerinde** [comment]
Oh, with square bracket.. Haha, I had no idea that's even valid! Nice!

**Comment by knz** [comment]
(the SQL grammar is ambiguous if we use regular brackets)

**Comment by RaduBerinde** [comment]
Very cool!  Another question - I chose `DIST_SQL` for consistency with the session var (`SET DIST_SQL = ON`). I am ok with switching the explain to `DISTSQL` but wanted to point that out.. Should we maybe change the session var to `DISTSQL`?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-:-KdhIJUdj_toe-OkJUfj:b-ewg7lv)*

**Comment by knz** [comment]
I'd like it better. In general I'm not too fond of underscores unless a spec doc mandates them.

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql_physical_planner.go, line 296 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-Kdg83SVdz-H-qXTqwl7:-KdhJW_sUcdbK_YGt91x:bp5t3r9) ([raw file](https://github.com/cockroachdb/cockroach/blob/92240aa52431c10bf7071c8ff808e7c80927b39c/pkg/sql/distsql_physical_planner.go#L296)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

yes, the new tests i'm adding (that's how it was found)
</blockquote></details>

Please point me (here in PR) to the test checking this, I'm not sure I am recognizing it.

---

*[pkg/sql/explain.go, line 272 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-KdgDkL0T2d3Qys-AZ08:-KdhJtOrz-b31xL9Zddy:b-txghro) ([raw file](https://github.com/cockroachdb/cockroach/blob/41222ececedff8323b19aa4c98535290e8a45514/pkg/sql/explain.go#L272)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

even if it wasn't `Start`ed?
</blockquote></details>

Oh, right. Never mind.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/distsql_physical_planner.go, line 296 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-Kdg83SVdz-H-qXTqwl7:-KdhNBDKPi3XOmqLkvjb:bihvbpl) ([raw file](https://github.com/cockroachdb/cockroach/blob/92240aa52431c10bf7071c8ff808e7c80927b39c/pkg/sql/distsql_physical_planner.go#L296)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please point me (here in PR) to the test checking this, I'm not sure I am recognizing it.
</blockquote></details>

`SELECT k, SUM(v) FROM kv WHERE k>1 GROUP BY k`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754)*

**Comment by RaduBerinde** [comment]
Thanks for the great suggestions. PTAL

---

Review status: all files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql_physical_planner.go, line 295 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-KdgqvEo6VdTwReihUK6:-KdhPu-G_YeebJPHv55p:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/92240aa52431c10bf7071c8ff808e7c80927b39c/pkg/sql/distsql_physical_planner.go#L295)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: "we should distribute" in this comment sounds like a TODO. I'd say just "we distribute", regardless of the enum name.
</blockquote></details>

Done.

---

*[pkg/sql/executor.go, line 1344 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-Kdg87WXxpG2jNp0L7uq:-KdhQVEAdrSyOUGQagI7:b-j9nioo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a964d035f35a954ea270e706f041c518a21bdab8/pkg/sql/executor.go#L1344)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

That was a bug? Perhaps a test for this would be warranted.
</blockquote></details>

Yeah, it was. I'm hesitant to add a test just for this as it would be duplicate in intent with some of the new testcases (even though it's technically verifying another path).

I think a better, more general thing would be to keep track of what happened to plan nodes (did we propagate limits? did we optimize filters? did we expand?) so that various code (like `CheckSupport` here) can assert that. This may be useful in other places too.

---

*[pkg/sql/explain.go, line 57 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-Kdg7mN-u44IIMshHe-T:-KdhPxTJckX84csZh6Ke:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/207a7d3ac0d742f8c4a12e17f6f2e85f0a0fcb7b/pkg/sql/explain.go#L57)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

While you're at it please lowercase/uppercase `opt` once and then just use a plain case each time.
</blockquote></details>

Done.

---

*[pkg/sql/explain.go, line 37 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-KdgtQ0SV62g2uAlEaXg:-KdhQHb2ojslSgnTOeJa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/41222ececedff8323b19aa4c98535290e8a45514/pkg/sql/explain.go#L37)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Mind adding a comment here about what this explain mode will do? (or link to `explainDistSQLNode`, but it'd be cool if that had a more descriptive comment too about the results)
</blockquote></details>

Done.

---

*[pkg/sql/explain.go, line 100 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-Kdgtn1llxOvCYOLH-9d:-KdhQMy0PIZN-9yCcqe_:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/41222ececedff8323b19aa4c98535290e8a45514/pkg/sql/explain.go#L100)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

is the `NOPLAN` option valid only in conjunction with `DIST_SQL`? Can we error otherwise?
</blockquote></details>

Removed.

---

*[pkg/sql/explain.go, line 261 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-Kdgu0etJtvIpXbx65so:-KdhLdX6yyC2qvKGXmcw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/41222ececedff8323b19aa4c98535290e8a45514/pkg/sql/explain.go#L261)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

mind commenting all the members but `plan, distSQLPlanner`? :)
</blockquote></details>

Done.

---

*[pkg/sql/explain.go, line 266 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-KdguXajiLBfXQ_dIhmU:-KdhNgHL7rg7sEVchK71:b-7evjln) ([raw file](https://github.com/cockroachdb/cockroach/blob/41222ececedff8323b19aa4c98535290e8a45514/pkg/sql/explain.go#L266)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I would get rid of `rowIdx`, rename `rows` to `remainingRows`, and keep reslicing that when rows are consumed.
</blockquote></details>

Now we return a single row. Note that for your solution to work, we would have needed a "dummy" first row because we call `Next()` before the first row.

---

*[pkg/sql/explain.go, line 275 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-KdgEMnwIC3Yx7nptKM6:-KdhLo-Dg9uTlUebt22c:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8846c670d92ae5d10be98833a8f162f5b3bfc850/pkg/sql/explain.go#L275)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I recommend storing the column set in the node instead of re-instantiating it on each call to `Columns()`.
</blockquote></details>

Done.

---

*[pkg/sql/explain.go, line 289 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-Kdgw3X0KEUYQQ8OyNaV:-KdhLolWJrq7JR-W8b_1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8846c670d92ae5d10be98833a8f162f5b3bfc850/pkg/sql/explain.go#L289)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

how about making this a boolean?
</blockquote></details>

Done.

---

*[pkg/sql/distsqlplan/physical_plan.go, line 679 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-KdgpcmYdCSxfYbf_43m:-KdhLq5LCklLqVskbVxb:b-q82i6k) ([raw file](https://github.com/cockroachdb/cockroach/blob/220169aafc1c5c99a8c95277a4139528dd35b492/pkg/sql/distsqlplan/physical_plan.go#L679)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

you're only using `nodeAddresses` for its length... I would get rid of it.
</blockquote></details>

Lol, done.

---

*[pkg/sql/distsqlrun/flow_diagram.go, line 388 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-Kdg6wR4WMv09HBLKKhC:-KdhPcFkX1N3tCoFAH3f:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/220169aafc1c5c99a8c95277a4139528dd35b492/pkg/sql/distsqlrun/flow_diagram.go#L388)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I was just talking to @kuanluo about displaying plans in our UI. This is to inform her of what's about to go on - Radu's introducing a `EXPLAIN (DIST_SQL) SELECT ...` query syntax which will generate a link to `raduberinde.github.io`
</blockquote></details>

Done.

---

*[pkg/sql/testdata/explain_distsql, line 11 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-KdgEE9YpEKwex414RqI:-KdhLx_jMAOhFbXBVEnY:b-ch2nnw) ([raw file](https://github.com/cockroachdb/cockroach/blob/8846c670d92ae5d10be98833a8f162f5b3bfc850/pkg/sql/testdata/explain_distsql#L11)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Have at least one of the tests use `colname` to test the column titles.
</blockquote></details>

Now that we have the new columns, I can't quite have a test that shows all of them (the plans are non-deterministic because of the fake span resolver). I am adding a few `statement ok; SELECT col FROM` instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-:-KdhTXXspacNO3f_HEZo:b-sjumyj)*

**Comment by knz** [comment]
Mostly good, just one nit left with the test.

Also reminder for later, please ping me when the PR is merged, I need to tweak the latest join blog post which mentions `set dist_sql`.

---

Reviewed 1 of 16 files at r8, 3 of 4 files at r9, 1 of 2 files at r10, 1 of 3 files at r12, 9 of 9 files at r13, 1 of 1 files at r14, 4 of 4 files at r15.
Review status: 19 of 20 files reviewed at latest revision, 13 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 296 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-Kdg83SVdz-H-qXTqwl7:-KdjW7JDU_uPoW6OAq9E:bd5vug7) ([raw file](https://github.com/cockroachdb/cockroach/blob/92240aa52431c10bf7071c8ff808e7c80927b39c/pkg/sql/distsql_physical_planner.go#L296)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`SELECT k, SUM(v) FROM kv WHERE k>1 GROUP BY k`
</blockquote></details>

Thanks, indeed.

---

*[pkg/sql/executor.go, line 1344 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-Kdg87WXxpG2jNp0L7uq:-KdjWGqpy9V1uSDROyBS:bbv50pd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a964d035f35a954ea270e706f041c518a21bdab8/pkg/sql/executor.go#L1344)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yeah, it was. I'm hesitant to add a test just for this as it would be duplicate in intent with some of the new testcases (even though it's technically verifying another path).

I think a better, more general thing would be to keep track of what happened to plan nodes (did we propagate limits? did we optimize filters? did we expand?) so that various code (like `CheckSupport` here) can assert that. This may be useful in other places too.
</blockquote></details>

Yes, actually i was working on this last week. Let's talk about this soon. I'm ok with delaying this test for now.

---

*[pkg/sql/testdata/explain_distsql, line 11 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-KdgEE9YpEKwex414RqI:-KdjX1K5Z-yoIgOgX-DG:badf5ml) ([raw file](https://github.com/cockroachdb/cockroach/blob/8846c670d92ae5d10be98833a8f162f5b3bfc850/pkg/sql/testdata/explain_distsql#L11)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Now that we have the new columns, I can't quite have a test that shows all of them (the plans are non-deterministic because of the fake span resolver). I am adding a few `statement ok; SELECT col FROM` instead.
</blockquote></details>

you could test them with `select * from [explain...] where false`, which would return zero rows.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-:-KdjXI281YxeB5K_FMcJ:bdo4k2n)*

**Comment by RaduBerinde** [comment]
Review status: 18 of 20 files reviewed at latest revision, 11 unresolved discussions, some commit checks pending.

---

*[pkg/sql/testdata/explain_distsql, line 11 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754#-KdgEE9YpEKwex414RqI:-KdkCtF_Ak8QwEaqP_gL:b-ol9l4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/8846c670d92ae5d10be98833a8f162f5b3bfc850/pkg/sql/testdata/explain_distsql#L11)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

you could test them with `select * from [explain...] where false`, which would return zero rows.
</blockquote></details>

Nice! Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13754)*

**Comment by RaduBerinde** [comment]
I can't get teamcity to pass (due to #13784)

**Comment by knz** [comment]
I had this earlier then I rebased then somehow it went away...
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by RaduBerinde** [comment]
Ok, merged.

**Pull request merged**
