### PR TITLE
sql: support COPY CSV

### LINKED ISSUE #51891: sql: add COPY ... CSV support
See comments in #8585

### PR DESCRIPTION
**Pull request by madelynnblue**
Resolves #51891

### CODE REVIEW

**Comment by mjibson** [comment]
First two commits from #51890.

**Comment by mjibson** [comment]
RFAL!

**Review by arulajmani — CHANGES_REQUESTED** [review]
Looks good in general, I especially like the new tests! Left a couple minor comments. 

> Reviewed 2 of 5 files at r1, 8 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52236#-:-MEVIxfD5jghy3v1fh3j:b-xv88sq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @mjibson)

___
*[pkg/sql/copy.go, line 141 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52236#-MEVIFyACZkMUr48FERn:-MEVIFyACZkMUr48FERo:bcutxxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f705d06538021dbb6cec286dd681b4f32e981f9f/pkg/sql/copy.go#L141)):*
> ```Go
> 	}
> 
> 	if n.Options.Delimiter != nil {
> ```

Do we need a check here (or maybe in the `CombineWith` logic in `tree/copy.go`) to ensure that a Delimiter is not provided if the format is binary? O
___
*[pkg/sql/copy.go, line 155 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52236#-MEVIOEqEHlGJ6FUVh6r:-MEVIOEqEHlGJ6FUVh6s:b-efl3go) ([raw file](https://github.com/cockroachdb/cockroach/blob/f705d06538021dbb6cec286dd681b4f32e981f9f/pkg/sql/copy.go#L155)):*
> ```Go
> 		c.delimiter = delim[0]
> 	}
> 	if n.Options.Null != nil {
> ```

Same as above, do we need to ensure that Null isn't provided for format binary? 
___
*[pkg/sql/sem/tree/copy.go, line 110 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52236#-MEVEaAJE_nfZv89OrJn:-MEVEaAK7hoBEyFXp7ng:b-xio33t) ([raw file](https://github.com/cockroachdb/cockroach/blob/f705d06538021dbb6cec286dd681b4f32e981f9f/pkg/sql/sem/tree/copy.go#L110)):*
> ```Go
> 		o.CopyFormat = other.CopyFormat
> 	}
> 	if o.Delimiter != nil {
> ```

nit: Could you switch this to other.Delimiter and the inside if condition to o.Delimiter so that things are uniform here and we don't need a nested else condition? 
___
*[pkg/sql/sem/tree/copy.go, line 117 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52236#-MEVF6Il2-LrM2YScYbe:-MEVF6Il2-LrM2YScYbf:b-nbd2cp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f705d06538021dbb6cec286dd681b4f32e981f9f/pkg/sql/sem/tree/copy.go#L117)):*
> ```Go
> 		o.Delimiter = other.Delimiter
> 	}
> 	if o.Null != nil {
> ```

same comment as above.

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52236)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[pkg/sql/copy.go, line 141 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52236#-MEVIFyACZkMUr48FERn:-MFCwZjl43s27WGMq4UK:b-1qqn5u) ([raw file](https://github.com/cockroachdb/cockroach/blob/f705d06538021dbb6cec286dd681b4f32e981f9f/pkg/sql/copy.go#L141)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Do we need a check here (or maybe in the `CombineWith` logic in `tree/copy.go`) to ensure that a Delimiter is not provided if the format is binary? O
</blockquote></details>

good idea, checked
___
*[pkg/sql/copy.go, line 155 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52236#-MEVIOEqEHlGJ6FUVh6r:-MFCwbLL2ydab1Cf7qKR:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f705d06538021dbb6cec286dd681b4f32e981f9f/pkg/sql/copy.go#L155)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Same as above, do we need to ensure that Null isn't provided for format binary? 
</blockquote></details>

done
___
*[pkg/sql/sem/tree/copy.go, line 117 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52236#-MEVF6Il2-LrM2YScYbe:-MFCxipsBTnvH_iSt1E1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f705d06538021dbb6cec286dd681b4f32e981f9f/pkg/sql/sem/tree/copy.go#L117)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

same comment as above. 
</blockquote></details>

Done.

**Review by arulajmani — APPROVED** [review]
LGTM! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52236#-:-MFVmWFZ2s5AEWJc0t8w:bvdsyag)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @mjibson)

**Comment by jordanlewis** [comment]
@mjibson, was this unmergeable?

**Comment by mjibson** [comment]
Code works fine, but wasn't ready during the release freeze window. I merged all the other commits dealing with testing and bug fixes. Someone could extract just the CSV parts and should merge fine.

**Comment by arulajmani** [comment]
I can take over this and extract the CSV part.

**Comment by jordanlewis** [comment]
Great! Thank you, Arul.

**Pull request closed without merging**
