### PR TITLE
testing: rewrite TestRepartitioning as SQLTranslator tests

### LINKED ISSUE #49112: ccl/partitionccl: TestRepartitioning failed
[(ccl/partitionccl).TestRepartitioning failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=1945764&tab=buildLog) on [master@68ca7367a1bf4c986e7f85de71c099b46bc435ab](https://github.com/cockroachdb/cockroach/commits/68ca7367a1bf4c986e7f85de71c099b46bc435ab):

```
              [n2,txn=0d7cbab8] recording span to refresh: /Table/70/1/{5/9-6}
               === SPAN START: count rows ===
            cockroach.flowid: 5879a52f-c9fe-4614-a209-07215f515aad
            cockroach.processorid: 3
            cockroach.stat.aggregator.input.rows: 0
            cockroach.stat.aggregator.mem.max: 0 B
            cockroach.stat.aggregator.stalltime: 510µs
              [n1,s1,r109/2:/Table/70/1/5/{8-9}] executing read-only batch
              [n1,s1,r109/2:/Table/70/1/5/{8-9}] read completed
              [n1,client=127.0.0.1:37008,hostssl,user=root,txn=0d7cbab8] querying next range at /Table/70/1/6
              [n1,client=127.0.0.1:37008,hostssl,user=root,txn=0d7cbab8] r112: sending batch 1 Scan to (n1,s1):2
              [n1,client=127.0.0.1:37008,hostssl,user=root,txn=0d7cbab8] sending request to local client
               === SPAN START: /cockroach.roachpb.Internal/Batch ===
              [n1] node received request: 1 Scan
              [n1,s1] executing [txn: 0d7cbab8], Scan [/Table/70/1/6,/Table/70/2)
              [n1,s1,r112/2:/Table/70/{1/6-2}] read-only path
              [n1,s1,r112/2:/Table/70/{1/6-2}] read has no clock uncertainty
              [n1,s1,r112/2:/Table/70/{1/6-2}] sequencing request
              [n1,s1,r112/2:/Table/70/{1/6-2}] acquiring latches
              [n1,s1,r112/2:/Table/70/{1/6-2}] scanning lock table for conflicting locks
              [n1,s1,r112/2:/Table/70/{1/6-2}] executing read-only batch
              [n1,s1,r112/2:/Table/70/{1/6-2}] read completed
              [n1,client=127.0.0.1:37008,hostssl,user=root,txn=0d7cbab8] recording span to refresh: /Table/70/1/5/{8-9}
              [n1,client=127.0.0.1:37008,hostssl,user=root,txn=0d7cbab8] recording span to refresh: /Table/70/{1/6-2}
               === SPAN START: count rows ===
            cockroach.flowid: 5879a52f-c9fe-4614-a209-07215f515aad
            cockroach.processorid: 2
            cockroach.stat.aggregator.input.rows: 0
            cockroach.stat.aggregator.mem.max: 0 B
            cockroach.stat.aggregator.stalltime: 710µs
              [n1,client=127.0.0.1:37008,hostssl,user=root] accumulation complete
              [n1,client=127.0.0.1:37008,hostssl,user=root] exiting aggregator
              [n1,client=127.0.0.1:37008,hostssl,user=root] execution ends
              [n1,client=127.0.0.1:37008,hostssl,user=root] rows affected: 1
              [n1,client=127.0.0.1:37008,hostssl,user=root] AutoCommit. err: <nil>
              [n1,client=127.0.0.1:37008,hostssl,user=root] releasing 1 tables
               === SPAN START: exec stmt ===
              [n1,client=127.0.0.1:37008,hostssl,user=root] [NoTxn pos:4786] executing ExecStmt: SET TRACING = off
              [n1,client=127.0.0.1:37008,hostssl,user=root] executing: SET TRACING = off in state: NoTxn
            goroutine 1452672 [running]:
            runtime/debug.Stack(0xc00946e030, 0x70b4e00, 0xc00991b440)
            	/usr/local/go/src/runtime/debug/stack.go:24 +0xab
            github.com/cockroachdb/cockroach/pkg/testutils.SucceedsSoon(0x71bf780, 0xc00a24c900, 0xc00946e030)
            	/go/src/github.com/cockroachdb/cockroach/pkg/testutils/soon.go:36 +0x87
            github.com/cockroachdb/cockroach/pkg/ccl/partitionccl.TestRepartitioning.func1(0xc00a24c900)
            	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/partitionccl/partition_test.go:1365 +0xb41
            testing.tRunner(0xc00a24c900, 0xc0141b1770)
            	/usr/local/go/src/testing/testing.go:909 +0x19a
            created by testing.(*T).Run
            	/usr/local/go/src/testing/testing.go:960 +0x652

```

<details><summary>More</summary><p>
Parameters:

- GOFLAGS=-json

```
make stressrace TESTS=TestRepartitioning PKG=./pkg/ccl/partitionccl TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestRepartitioning.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

Jira issue: CRDB-4256

### LINKED ISSUE #109935: spanconfigsqltranslatorccl: TestDataDriven/tenant/misc  timed out
See CI failure on unrelated branch [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=11594668&buildTypeId=Cockroach_BazelEssentialCi)

Jira issue: CRDB-31160

### LINKED ISSUE #109985: pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/spanconfigsqltranslatorccl_test: TestDataDriven failed
pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/spanconfigsqltranslatorccl_test.TestDataDriven [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/11615363?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/11615363?buildTab=artifacts#/) on release-23.1 @ [fde98bbb2423906a7e3bfd9cd7956bc3f29918ad](https://github.com/cockroachdb/cockroach/commits/fde98bbb2423906a7e3bfd9cd7956bc3f29918ad):

Fatal error:

```
panic: test timed out after 4m55s

```
Stack: 

```
goroutine 433163 [running]:
testing.(*M).startAlarm.func1()
	GOROOT/src/testing/testing.go:2036 +0x88
created by time.goFunc
	GOROOT/src/time/sleep.go:176 +0x38
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   TestDataDriven/partition/single_col_list_partitioning_default
    datadriven.go:144: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/8121/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/spanconfigsqltranslatorccl_test_/spanconfigsqltranslatorccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/single_col_list_partitioning_default:1:
        exec-sql [0 args]
        CREATE DATABASE db;
        CREATE TABLE db.tbl (a INT PRIMARY KEY) PARTITION BY LIST (a) (
          PARTITION p4 VALUES IN (4),
          PARTITION p5 VALUES IN (5),
          PARTITION pd VALUES IN (DEFAULT)
        );
        ALTER PARTITION p4 OF INDEX db.tbl@tbl_pkey CONFIGURE ZONE USING constraints = '[+n2]';
        ALTER PARTITION p5 OF INDEX db.tbl@tbl_pkey CONFIGURE ZONE USING constraints = '[+n3]';
        ALTER PARTITION pd OF INDEX db.tbl@tbl_pkey CONFIGURE ZONE USING constraints = '[+n1]';
        ----
    datadriven.go:144: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/8121/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/spanconfigsqltranslatorccl_test_/spanconfigsqltranslatorccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/single_col_list_partitioning_default:13:
        translate [2 args]
        <no input to command>
        ----
        /Table/106{-/1}                            range default
        /Table/106/1{-/4}                          constraints=[+n1]
        /Table/106/1/{4-5}                         constraints=[+n2]
        /Table/106/1/{5-6}                         constraints=[+n3]
        /Table/106/{1/6-2}                         constraints=[+n1]
        /Table/10{6/2-7}                           range default
=== RUN   TestDataDriven/partition/single_col_range_partitioning_maxvalue
    datadriven.go:144: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/8121/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/spanconfigsqltranslatorccl_test_/spanconfigsqltranslatorccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/single_col_range_partitioning_maxvalue:1:
        exec-sql [0 args]
        CREATE DATABASE db;
        CREATE TABLE db.tbl (a INT PRIMARY KEY) PARTITION BY RANGE (a) (
          PARTITION p4 VALUES FROM (MINVALUE) TO (4),
          PARTITION p5 VALUES FROM (4) TO (5),
          PARTITION px VALUES FROM (5) TO (MAXVALUE)
        );
        ALTER PARTITION p4 OF INDEX db.tbl@tbl_pkey CONFIGURE ZONE USING constraints = '[+n1]';
        ALTER PARTITION p5 OF INDEX db.tbl@tbl_pkey CONFIGURE ZONE USING constraints = '[+n2]';
        ALTER PARTITION px OF INDEX db.tbl@tbl_pkey CONFIGURE ZONE USING constraints = '[+n3]';
        ----
    datadriven.go:144: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/8121/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/spanconfigsqltranslatorccl_test_/spanconfigsqltranslatorccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/single_col_range_partitioning_maxvalue:13:
        translate [2 args]
        <no input to command>
        ----
        /Table/106{-/1}                            range default
        /Table/106/1{-/4}                          constraints=[+n1]
        /Table/106/1/{4-5}                         constraints=[+n2]
        /Table/106/{1/5-2}                         constraints=[+n3]
        /Table/10{6/2-7}                           range default
=== RUN   TestDataDriven/tenant/databases
```
</p>
</details>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestDataDriven.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-31201

### PR DESCRIPTION
**Pull request by ecwall**
Fixes #49112
Fixes https://github.com/cockroachdb/cockroach/issues/109935
Fixes https://github.com/cockroachdb/cockroach/issues/109985

This rewrites TestRepartitioning subtests as SQLTranslator tests so that they
can be unskipped.

Release note: None

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109911)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall)

___
*[`pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/datadriven_test.go` line 84 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/109911#-NdbAWYE3XLnzYev26Wh:-NdbAWYE3XLnzYev26Wi:btslp2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee4b05e70b5184a014ca67845284d3e61a017ffe/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/datadriven_test.go#L84)):*
> ```Go
> 	t.Cleanup(leaktest.AfterTest(t))
> 	t.Cleanup(func() {
> 		log.Scope(t).Close(t)
> ```

i don't think this is equivalent - by wrapping it in the outer `func() {}`, now the `log.Scope(t)` function isn't called until the very end. i think we want:
```
scope := log.Scope(t)
t.Cleanup(func() { scope.Close(t) })
```
___
*[`pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/all_indexes` line 2 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/109911#-Ndb97iaEw_ZPYTr_6Cr:-Ndb97iaEw_ZPYTr_6Cs:bkbfj5c) ([raw file](https://github.com/cockroachdb/cockroach/blob/137f50cea3b32d6768cf03a4f1be6e08ae9732b6/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/all_indexes#L2)):*
> ```
> exec-sql
> CREATE DATABASE IF NOT EXISTS db;
> ```

wouldn't it be better to always start off with a `DROP DATABASE IF EXISTS db` and then have each test create the db? That way a test doesn't inherit anything that was configured by a previous test.

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109911)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/datadriven_test.go` line 84 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/109911#-NdbAWYE3XLnzYev26Wh:-NdbC3lbDzFMWKganZlX:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee4b05e70b5184a014ca67845284d3e61a017ffe/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/datadriven_test.go#L84)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i don't think this is equivalent - by wrapping it in the outer `func() {}`, now the `log.Scope(t)` function isn't called until the very end. i think we want:
```
scope := log.Scope(t)
t.Cleanup(func() { scope.Close(t) })
```
</blockquote></details>

Fixed.
___
*[`pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/all_indexes` line 2 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/109911#-Ndb97iaEw_ZPYTr_6Cr:-NdbBdf9-8i70b9IiFrk:bu5igvf) ([raw file](https://github.com/cockroachdb/cockroach/blob/137f50cea3b32d6768cf03a4f1be6e08ae9732b6/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/all_indexes#L2)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

wouldn't it be better to always start off with a `DROP DATABASE IF EXISTS db` and then have each test create the db? That way a test doesn't inherit anything that was configured by a previous test.
</blockquote></details>

We want the "to" state of the repartition tests to inherit the "from" state so the database should not be dropped.

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109911)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall)

___
*[`pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/all_indexes` line 2 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/109911#-Ndb97iaEw_ZPYTr_6Cr:-NdbEeIk7sZJUPbaz6Pl:b985c4d) ([raw file](https://github.com/cockroachdb/cockroach/blob/137f50cea3b32d6768cf03a4f1be6e08ae9732b6/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/all_indexes#L2)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

We want the "to" state of the repartition tests to inherit the "from" state so the database should not be dropped.
</blockquote></details>

ah i see, thanks for explaining

**Comment by ecwall** [comment]
bors r=rafiss

**Pull request merged**
