### PR TITLE
kv: Retry some roachpb.Errors in send.go

### PR DESCRIPTION
**Pull request by bdarnell**
send.go is the best place to retry errors such as NotLeaderError because it ensures that all replicas will be tried (as opposed to DistSender which may counter-productively apply the same ordering heuristics on every attempt). This change is the first phase of testing and preparation for this change; actually retrying NotLeaderError at this level will require some more refactoring.

See #2500

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6578)

### CODE REVIEW

**Comment by tamird** [comment]
The separation of responsibility described in the commit message deserves a comment in the code.

<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> #### kv: Retry some roachpb\.Errors in send\.go
> 
> send.go is the best place to retry errors such as NotLeaderError because it ensures that all replicas will be tried (as opposed to DistSender which may counter-productively apply the same ordering heuristics on every attempt). This change is the first phase of testing and preparation for this change; actually retrying NotLeaderError at this level will require some more refactoring.
> 
> 
> 
> See #2500
> 
> 
> </details>


---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[kv/send.go, line 166 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6578#-KHH4y_Ef0iXndeo8sqk:-KHH4y_FsxQ-OAOXukPu:-725876768) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5f19880cff93357a33de4558dc33d82d2f1cd98/kv/send.go#L166)):*
> ```Go
> 				if log.V(2) {
> 					log.Infof("RPC reply: %+v", call.reply)
> 				} else if call.reply.Error != nil && log.V(1) {
> ```

nit: i think this might be more readable with `log.V(1)` first

---

*[kv/send_test.go, line 241 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6578#-KHGch1uZH51wnGRhU2l:-KHGch1vrX0sZgv_Y42n:1110527492) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed12c322a3770042a20a6d768886e060e930deec/kv/send_test.go#L241)):*
> ```Go
> 	}()
> 
> 	var doneChans []chan batchCall
> ```

preallocate this for consistency

---

*[kv/send_test.go, line 336 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6578#-KHGdhuStw_r-ylr2tHe:-KHGdhuTOYa7x4a0rYVY:1595298735) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed12c322a3770042a20a6d768886e060e930deec/kv/send_test.go#L336)):*
> ```Go
> 		t.Errorf("did not get expected SendError; got %T instead", bc.err)
> 	} else if !sErr.CanRetry() {
> 		t.Errorf("expected a retryable error")
> ```

consider loggin sErr in this case

---

*[kv/send_test.go, line 361 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6578#-KHGdpAeXaLtO-Xyez_6:-KHGdpAeXaLtO-Xyez_7:-469765787) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed12c322a3770042a20a6d768886e060e930deec/kv/send_test.go#L361)):*
> ```Go
> 		t.Errorf("did not get expected SendError; got %T instead", bc.err)
> 	} else if sErr.CanRetry() {
> 		t.Errorf("expected a non-retryable error")
> ```

ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6578#-:-KHH5riNh9cVIJaJcNQ9:973581860)*

**Comment by tschottdorf** [comment]
^-- agreed.

LGTM otherwise. Do we plan to do anything in particular with requests that repeatedly bubble up to DistSender with a SendError? At some point, you do want to go back to the client, right (if nothing else, to keep it from piling up more new requests on top of  the existing trapped ones).

<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> The separation of responsibility described in the commit message deserves a comment in the code.</details>


---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[kv/send.go, line 181 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6578#-KHLFWRy55zBzRMG0EAD:-KHLFWRy55zBzRMG0EAE:-871996029) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5f19880cff93357a33de4558dc33d82d2f1cd98/kv/send.go#L181)):*
> ```Go
> 				// we've seen (for example, a NotLeaderError conveys more
> 				// information than a RangeNotFound).
> 				err = call.reply.Error.GetDetail()
> ```

should this be `GoError()`?

---

*[kv/send_test.go, line 215 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6578#-KHL4AXq8Jnc7Li12Rx0:-KHL46OKWa-Flxa5C_M0:-1402103631) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed12c322a3770042a20a6d768886e060e930deec/kv/send_test.go#L215)):*
> ```Go
> 
> 	// Using a real listener here speeds up the tests, compared to using
> 	// a fake non-resolving address.
> ```

Interesting, why is that? I thought we weren't touching the network.

---

*[kv/send_test.go, line 216 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6578#-KHL4vcjeDknsUnSUNv2:-KHL4vcjeDknsUnSUNv3:1644690626) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed12c322a3770042a20a6d768886e060e930deec/kv/send_test.go#L216)):*
> ```Go
> 	// Using a real listener here speeds up the tests, compared to using
> 	// a fake non-resolving address.
> 	_, ln := newTestServer(t, nodeContext)
> ```

Is this ever closed?

---

*[kv/send_test.go, line 243 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6578#-KHLBpMHvzd476LR8pPP:-KHLBpMHvzd476LR8pPQ:1365602040) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed12c322a3770042a20a6d768886e060e930deec/kv/send_test.go#L243)):*
> ```Go
> 	var doneChans []chan batchCall
> 	for i := 0; i < len(addrs); i++ {
> 		doneChans = append(doneChans, <-doneChanChan)
> ```

> // Note that this blocks until a replica has been contacted.

---

*[kv/send_test.go, line 340 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6578#-KHLCNtx-RkLAkcDjU0Q:-KHLCNtx-RkLAkcDjU0R:1427761621) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed12c322a3770042a20a6d768886e060e930deec/kv/send_test.go#L340)):*
> ```Go
> }
> 
> // Test the behavior of SendNextTimeout when one server returns a
> ```

s/one server/all servers/.

What's with the case in which it's only one?

Edit: disregard, I saw that you're removing that test later.

---

*[kv/send_test.go, line 353 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6578#-KHLFpE-8koHXEx665Wx:-KHLFpE-8koHXEx665Wy:1345881148) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5f19880cff93357a33de4558dc33d82d2f1cd98/kv/send_test.go#L353)):*
> ```Go
> 	} else if _, ok := bc.err.(*roachpb.SendError); !ok {
> 		t.Fatalf("expected SendError, got err=%s", bc.err)
> 	} else if !testutils.IsError(bc.err, "range 1 was not found") {
> ```

nit:
```go
else if exp := "range 1 was not found"; !testutils.IsError(bc.err, exp); {
  t.Errorf("expected SendError to contain '%s', but got %s", exp, bc.err)
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6578#-:-KHLGB5rZLwVbF9sIk_3:394730132)*

**Comment by bdarnell** [comment]
Updated comments in both files.

Added a TODO in DistSender to detect loops by comparing the range descriptor before and after eviction.

<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> ^-- agreed.
> 
> LGTM otherwise. Do we plan to do anything in particular with requests that repeatedly bubble up to DistSender with a SendError? At some point, you do want to go back to the client, right (if nothing else, to keep it from piling up more new requests on top of  the existing trapped ones).</details>


---

Review status: all files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[kv/send.go, line 166 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6578#-KHH4y_Ef0iXndeo8sqk:-KHPpiLPVzBjFL7RElug:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5f19880cff93357a33de4558dc33d82d2f1cd98/kv/send.go#L166)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: i think this might be more readable with `log.V(1)` first</details>
Done.

---

*[kv/send.go, line 181 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6578#-KHLFWRy55zBzRMG0EAD:-KHPpkzpKiymEdJUBG7D:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5f19880cff93357a33de4558dc33d82d2f1cd98/kv/send.go#L181)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> should this be `GoError()`?</details>
Done.

---

*[kv/send_test.go, line 215 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6578#-KHL4AXq8Jnc7Li12Rx0:-KHPq6Bl60eZLNk_n8KZ:1388113796) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed12c322a3770042a20a6d768886e060e930deec/kv/send_test.go#L215)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Interesting, why is that? I thought we weren't touching the network.</details>
Mocking in this code is kind of a mess; we replace `sendOneFn` but that's not used until after the connections have been created. My next PR cleans this up.

---

*[kv/send_test.go, line 216 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6578#-KHL4vcjeDknsUnSUNv2:-KHPpxTzEASQfr5ZIZT8:313621843) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed12c322a3770042a20a6d768886e060e930deec/kv/send_test.go#L216)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Is this ever closed?</details>
Yes, it respects the stopper we created above.

---

*[kv/send_test.go, line 241 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6578#-KHGch1uZH51wnGRhU2l:-KHPqZTaCFYpXVxQj06S:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed12c322a3770042a20a6d768886e060e930deec/kv/send_test.go#L241)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> preallocate this for consistency</details>
Done.

---

*[kv/send_test.go, line 243 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6578#-KHLBpMHvzd476LR8pPP:-KHPqhfYgbvH1y_hX40b:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed12c322a3770042a20a6d768886e060e930deec/kv/send_test.go#L243)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> > // Note that this blocks until a replica has been contacted.</details>
Done.

---

*[kv/send_test.go, line 336 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6578#-KHGdhuStw_r-ylr2tHe:-KHPqll0ovwfJyHDe60y:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed12c322a3770042a20a6d768886e060e930deec/kv/send_test.go#L336)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> consider loggin sErr in this case</details>
Done.

---

*[kv/send_test.go, line 353 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6578#-KHLFpE-8koHXEx665Wx:-KHPqyfJioOrxiVskfiC:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5f19880cff93357a33de4558dc33d82d2f1cd98/kv/send_test.go#L353)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> nit:
> ```go
> else if exp := "range 1 was not found"; !testutils.IsError(bc.err, exp); {
>   t.Errorf("expected SendError to contain '%s', but got %s", exp, bc.err)
> }
> ```</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6578#-:-KHPp2fwe1NpWUWUe-LB:467601834)*

**Comment by tschottdorf** [comment]
:lgtm:

<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Updated comments in both files.
> 
> Added a TODO in DistSender to detect loops by comparing the range descriptor before and after eviction.</details>


---

Reviewed 3 of 3 files at r4, 5 of 5 files at r5, 2 of 2 files at r6, 2 of 2 files at r7, 3 of 3 files at r8, 3 of 3 files at r9.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6578#-:-KHPsQEQGzxYIShiyiKa:1417088721)*

**Comment by tamird** [comment]
:lgtm:

<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> :lgtm:</details>


---

Reviewed 2 of 2 files at r6, 2 of 3 files at r9, 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6578#-:-KHQ3-q9dcCWIfwzIg97:1417088721)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6578)*

**Pull request merged**
