### PR TITLE
	storageccl: use UnsafeKey in MVCCIncrementalIterator

### PR DESCRIPTION
**Pull request by danhhz**
It saves some allocations.

name             old time/op    new time/op    delta
ClusterBackup-8    1.75µs ±34%    1.90µs ±27%     ~     (p=0.690 n=5+5)

name             old speed      new speed      delta
ClusterBackup-8  74.9MB/s ±30%  67.2MB/s ±32%     ~     (p=0.690 n=5+5)

name             old alloc/op   new alloc/op   delta
ClusterBackup-8      200B ±35%       5B ±120%  -97.50%  (p=0.016 n=5+4)

name             old allocs/op  new allocs/op  delta
ClusterBackup-8      3.00 ± 0%     0.00 ±NaN%     ~     (p=0.079 n=4+5)

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14573)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14573)*

**Comment by benesch** [comment]
Do we have a way of ensuring that benchmarks don't rot? Mostly curious. Seems like it would be great if TC would just run them through once to ensure they don't error.

Anyway, :lgtm:! I'll leave the note below about leaving the original `Key()` and `Value()` methods unchanged up to you—I'm assuming that you think removing `Key()` and `Value()` will make it harder to misuse the API?

---

Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/storageccl/export.go, line 106 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14573#-Kgp9ajJE5L8lTBNQOPk:-Kgp9ajJE5L8lTBNQOPl:bt15jje) ([raw file](https://github.com/cockroachdb/cockroach/blob/88468645c3eab8f171258b85681e764fcdeb2166/pkg/ccl/storageccl/export.go#L106)):*
> ```Go
> 		if log.V(3) {
> 			v := roachpb.Value{RawBytes: iter.UnsafeValue()}
> 			log.Infof(ctx, "Export %s %s", iter.UnsafeKey(), v.PrettyPrint())
> ```

Do you think this better than leaving `.Key()`, `.Value()` unchanged and using them directly here? (I.e., introduce `.UnsafeKey()` and `.UnsafeValue()` methods in addition to the existing `.Key()` and `.Value()` methods? Genuinely asking.

---

*[pkg/ccl/storageccl/engineccl/mvcc.go, line 124 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14573#-Kgp9tg8NycALFRVlY-K:-Kgp9tg8NycALFRVlY-L:b-6uigl9) ([raw file](https://github.com/cockroachdb/cockroach/blob/88468645c3eab8f171258b85681e764fcdeb2166/pkg/ccl/storageccl/engineccl/mvcc.go#L124)):*
> ```Go
> 				key := append([]byte(nil), unsafeMetaKey.Key...)
> 				i.err = &roachpb.WriteIntentError{
> 					Intents: []roachpb.Intent{{Span: roachpb.Span{Key: key}, Status: roachpb.PENDING, Txn: *i.meta.Txn}},
> ```

Then this could be `i.iter.Key()`...

---

*[pkg/ccl/storageccl/engineccl/mvcc_test.go, line 60 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14573#-Kgp9wNLlmDzPb5eDg1A:-Kgp9wNLlmDzPb5eDg1B:b-q96lk1) ([raw file](https://github.com/cockroachdb/cockroach/blob/88468645c3eab8f171258b85681e764fcdeb2166/pkg/ccl/storageccl/engineccl/mvcc_test.go#L60)):*
> ```Go
> 				Value: append([]byte(nil), iter.UnsafeValue()...),
> 			}
> 			kvs = append(kvs, kv)
> ```

...and this could be completely unchanged.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14573#-:-Kgp2eVYr4TIguS3xxvy:bkxq25j)*

**Comment by benesch** [comment]
Reviewed 1 of 1 files at r1, 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14573)*

**Comment by danhhz** [comment]
I was having the same thoughts myself about benchmark rot. Unfortunately a `make bench PKG=./pkg/... TESTFLAGS='-benchtime 1ns'` takes forever, because some benchmarks take longer than a second even for a b.N of 1

---

Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/storageccl/export.go, line 106 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14573#-Kgp9ajJE5L8lTBNQOPk:-KgpDpWprQWjapq1tvvT:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/88468645c3eab8f171258b85681e764fcdeb2166/pkg/ccl/storageccl/export.go#L106)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Do you think this better than leaving `.Key()`, `.Value()` unchanged and using them directly here? (I.e., introduce `.UnsafeKey()` and `.UnsafeValue()` methods in addition to the existing `.Key()` and `.Value()` methods? Genuinely asking.
</blockquote></details>

Good idea. Done.

---

*[pkg/ccl/storageccl/engineccl/mvcc.go, line 124 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14573#-Kgp9tg8NycALFRVlY-K:-KgpDoeD7ItbSz4eNByE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/88468645c3eab8f171258b85681e764fcdeb2166/pkg/ccl/storageccl/engineccl/mvcc.go#L124)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Then this could be `i.iter.Key()`...
</blockquote></details>

Done.

---

*[pkg/ccl/storageccl/engineccl/mvcc_test.go, line 60 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14573#-Kgp9wNLlmDzPb5eDg1A:-KgpDnt09MbcWinaXzgB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/88468645c3eab8f171258b85681e764fcdeb2166/pkg/ccl/storageccl/engineccl/mvcc_test.go#L60)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

...and this could be completely unchanged.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14573#-:-KgpDrRuoLFUaN82RUva:b-waszsj)*

**Pull request merged**
