### PR TITLE
plpgsql: implement rollback behavior for EXCEPTION blocks

### LINKED ISSUE #105253: plpgsql: implement exception handling
PLpgSQL blocks allow an `EXCEPTION` clause, which is able to catch and examine errors thrown in the block body. Once an error is caught, the statements in that branch of the `EXCEPTION` clause are executed as normal PLpgSQL statements. Any postgres error can be caught, for example `division_by_zero`: https://www.postgresql.org/docs/current/plpgsql-control-structures.html#PLPGSQL-ERROR-TRAPPING

This will take special care to ensure errors are caught and propagated correctly. I've prototyped an approach here: https://github.com/cockroachdb/cockroach/commit/a5f1766239a55c75ff34b170a2a5720e59c2bdf8

Epic: CRDB-799

Jira issue: CRDB-28942

### PR DESCRIPTION
**Pull request by DrewKimball**
#### plpgsql: implement rollback behavior for EXCEPTION blocks

When an exception occurs within the EXCEPTION block of a PLpgSQL routine,
all changes to database state are rolled back, but the updated values for
the variables are still visible to the exception handler. For example:
```
CREATE FUNCTION f() RETURNS INT AS $$
  DECLARE
    i INT;
  BEGIN
    INSERT INTO xy VALUES (-100, -100);
    i := 100;
    RETURN 1 // 0;
  EXCEPTION WHEN division_by_zero THEN
    RETURN i;
  END
$$ LANGUAGE PLpgSQL;
```
The above function would not modify `xy`, since the exception would
revert the insert. However, the function would return `100`, since the
variable assignment occurred before the error was thrown.

This patch implements the required rollback behavior through internal
savepoints; when the top-level routine of a PLpgSQL block begins
executing, it creates a savepoint (if it has an exception handler).
When the exception handler catches an error, it calls `RollbackSavepoint`
to revert any changes to database state within the scope of the block.

Note that some errors can leave the transaction in a poisoned state,
where immediately rolling back the nested transaction is not possible.
The transaction can be returned to a normal state in some cases
(as is done for the read committed retry loop), but this will be left
as a TODO in 23.2, tracked in #111446. Until this is fixed, catching
`40001` and `40003` errors is not permitted.

Fixes #105253

Release note (sql change): When a PLpgSQL exception handler catches an
error, it now rolls back any changes to database state that occurred
within the block. Exception blocks are not currently permitted to catch
`40001` and `40003` errors.

### CODE REVIEW

**Comment by DrewKimball** [comment]
I think I'll have to special-case some KV errors, so some extra tests and checks in exception-handling will be incoming.

**Comment by DrewKimball** [comment]
This is RFAL. The plan is to disable catching 40001 and 40003 errors for the 23.2 release, since these leave the transaction in a poisoned state that must be properly handled (and sometimes requires a complete txn restart).

**Review by rharding6373 — COMMENTED** [review]
Very cool to see exception handling in action! My main concerns are if we're disabling all the right errors from exception handling, and adding a bit more test coverage.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110998#-:-NfSIXo9DTl0FaofNUmb:b-xiqe0m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @michae2)

___
*[`-- commits` line 21 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110998#-NfS4NiR9nyQg3MM8YBq):*
nit: This should return 100.
___
*[`pkg/sql/routine.go` line 296 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110998#-NfS5GxGCHZGGDjnqPrD:-NfS5GxGCHZGGDjnqPrE:bct48xv) ([raw file](https://github.com/cockroachdb/cockroach/blob/f59cf63c56eca6dad337801b6fde453d11b03b3e/pkg/sql/routine.go#L296)):*
> ```Go
> 	if !g.p.Txn().IsOpen() {
> 		// It is not safe to catch an error unless the transaction is open.
> 		// TODO(drewk): some retryable errors allow the transaction to be rolled
> ```

Could you open an issue for this? Seems important for supporting expected PL/pgSQL behavior in read committed, but it also seems unlikely to get done for this release.
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 208 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110998#-NfS8UgQ6VpR7Tw-ViPJ:-NfS8UgQ6VpR7Tw-ViPK:bshx6g9) ([raw file](https://github.com/cockroachdb/cockroach/blob/f59cf63c56eca6dad337801b6fde453d11b03b3e/pkg/sql/opt/optbuilder/plpgsql.go#L208)):*
> ```Go
> 		blockCon := b.makeContinuation("exception_block")
> 		blockCon.def.ExceptionBlock = exceptions
> 		blockCon.def.Volatility = volatility.Volatile
> ```

Should an exception block override the whole UDF as volatile? Or is the rest of the UDF body ok to inline?
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 780 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110998#-NfSBFIW-onrXFP48WxB:-NfSBFIW-onrXFP48WxC:b-bxmerp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f59cf63c56eca6dad337801b6fde453d11b03b3e/pkg/sql/opt/optbuilder/plpgsql.go#L780)):*
> ```Go
> 		code := pgcode.MakeCode(strings.ToUpper(codeStr))
> 		switch code {
> 		case pgcode.SerializationFailure:
> ```

Do we also need to catch `pgcode.StatementCompletionUnknown` (40003) here?

Are we able to catch other transaction-related errors correctly? E.g., transaction rollback 40000 seems like it might be tricky, especially if the exception block contains an insert.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 1942 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110998#-NfSEQpM4CJ3DxTWrpmH:-NfSEQpM4CJ3DxTWrpmI:b-d3uwx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f59cf63c56eca6dad337801b6fde453d11b03b3e/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L1942)):*
> ```
> NOTICE: outside IF
> 
> statement ok
> ```

Would be nice to have one example of an exception block in an opt builder test so we could see the plan.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 1958 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110998#-NfSEb9lBbkndpR795Id:-NfSEb9lBbkndpR795Ie:b-85nfl1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f59cf63c56eca6dad337801b6fde453d11b03b3e/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L1958)):*
> ```
>     INSERT INTO xy VALUES (-200, -200);
>     IF n > 0 THEN
>       RAISE EXCEPTION 'foo';
> ```

Test suggestions:
* Multiple exception blocks
* Multiple exception blocks where one is raised from another. I think in this case it shouldn't actually execute the second exception block?

**Review by DrewKimball — COMMENTED** [review]
Thanks for taking a look!

>My main concerns are if we're disabling all the right errors from exception handling

It's worth mentioning that we should be guaranteed not to catch any error that puts the transaction in a bad state by the `g.p.Txn().IsOpen()` check during execution. So, we just need to make sure to provide a user-friendly error during function creation if they attempt to catch such an error.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110998#-:-NfSY3iB0EsKI-qNmX5R:b-32e3bc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @rharding6373)

___
*[`-- commits` line 21 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110998#-NfS4NiR9nyQg3MM8YBq):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

nit: This should return 100.
</blockquote></details>

Good catch. Done.
___
*[`pkg/sql/routine.go` line 296 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110998#-NfS5GxGCHZGGDjnqPrD:-NfS_v2V8Yeq_nY_xBeq:b-g7h0iz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f59cf63c56eca6dad337801b6fde453d11b03b3e/pkg/sql/routine.go#L296)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Could you open an issue for this? Seems important for supporting expected PL/pgSQL behavior in read committed, but it also seems unlikely to get done for this release.
</blockquote></details>

Done: https://github.com/cockroachdb/cockroach/issues/111446. I added a reference in the user-facing "unimplemented" error.
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 208 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110998#-NfS8UgQ6VpR7Tw-ViPJ:-NfSaNgN-n-qWJyWtDYD:btf0di9) ([raw file](https://github.com/cockroachdb/cockroach/blob/f59cf63c56eca6dad337801b6fde453d11b03b3e/pkg/sql/opt/optbuilder/plpgsql.go#L208)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Should an exception block override the whole UDF as volatile? Or is the rest of the UDF body ok to inline?
</blockquote></details>

The block and variable-assignment continuations need to be volatile, but anything else is OK to inline. I added a comment and pointer to the `buildExceptions` comment, which gives more detail.
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 780 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110998#-NfSBFIW-onrXFP48WxB:-NfSXrkZAzDuBGHg4SY_:bewslu5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f59cf63c56eca6dad337801b6fde453d11b03b3e/pkg/sql/opt/optbuilder/plpgsql.go#L780)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Do we also need to catch `pgcode.StatementCompletionUnknown` (40003) here?

Are we able to catch other transaction-related errors correctly? E.g., transaction rollback 40000 seems like it might be tricky, especially if the exception block contains an insert.
</blockquote></details>

Good point. I've added all the `4000*` errors to this check.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 1942 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110998#-NfSEQpM4CJ3DxTWrpmH:-NfSapPgEzn6T04Urm0R:b1g8rk1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f59cf63c56eca6dad337801b6fde453d11b03b3e/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L1942)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Would be nice to have one example of an exception block in an opt builder test so we could see the plan.
</blockquote></details>

I added some of those in the original exception block PR: https://github.com/cockroachdb/cockroach/blob/81a06c6b1fc38fda134118b9e4541e61a4bce5ef/pkg/sql/opt/optbuilder/testdata/udf_plpgsql#L3400
___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 1958 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110998#-NfSEb9lBbkndpR795Id:-NfSb7Ql3EuXijv1ZxZO:b-6s83gb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f59cf63c56eca6dad337801b6fde453d11b03b3e/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L1958)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Test suggestions:
* Multiple exception blocks
* Multiple exception blocks where one is raised from another. I think in this case it shouldn't actually execute the second exception block?
</blockquote></details>

For now we only support the one top-level block, so I don't think this is possible yet. We do have tests where we verify that an exception block doesn't catch its own error: https://github.com/cockroachdb/cockroach/blob/81a06c6b1fc38fda134118b9e4541e61a4bce5ef/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L1500-L1511
And also one with duplicate catch branches: https://github.com/cockroachdb/cockroach/blob/81a06c6b1fc38fda134118b9e4541e61a4bce5ef/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L1449

**Comment by DrewKimball** [comment]
I've added some tests for the newly introduced `CanUseSavepoint` method.

**Review by rharding6373 — APPROVED** [review]
:lgtm: Nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110998#-:-NflYNRq1k-Rv8TeZM9G:bcmw7ss)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/routine.go` line 296 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110998#-NfS5GxGCHZGGDjnqPrD:-NflSh8j7xHZIqGhJHZ4:b-5efez) ([raw file](https://github.com/cockroachdb/cockroach/blob/f59cf63c56eca6dad337801b6fde453d11b03b3e/pkg/sql/routine.go#L296)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Done: https://github.com/cockroachdb/cockroach/issues/111446. I added a reference in the user-facing "unimplemented" error.
</blockquote></details>

Could you s/drewk/111446?
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 208 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110998#-NfS8UgQ6VpR7Tw-ViPJ:-NflSuLa7AHwBxyiYwOy:bkjrzei) ([raw file](https://github.com/cockroachdb/cockroach/blob/f59cf63c56eca6dad337801b6fde453d11b03b3e/pkg/sql/opt/optbuilder/plpgsql.go#L208)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

The block and variable-assignment continuations need to be volatile, but anything else is OK to inline. I added a comment and pointer to the `buildExceptions` comment, which gives more detail.
</blockquote></details>

Thanks, great that you've figured out how to inline as much of the overall function as possible.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 1942 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110998#-NfSEQpM4CJ3DxTWrpmH:-NflTb6W9PU6rRKP9Y3t:b-5kbawn) ([raw file](https://github.com/cockroachdb/cockroach/blob/f59cf63c56eca6dad337801b6fde453d11b03b3e/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L1942)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I added some of those in the original exception block PR: https://github.com/cockroachdb/cockroach/blob/81a06c6b1fc38fda134118b9e4541e61a4bce5ef/pkg/sql/opt/optbuilder/testdata/udf_plpgsql#L3400
</blockquote></details>

Thanks for the pointer.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 1958 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110998#-NfSEb9lBbkndpR795Id:-NflWooe8yzos93mGZhK:b3sxpaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f59cf63c56eca6dad337801b6fde453d11b03b3e/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L1958)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

For now we only support the one top-level block, so I don't think this is possible yet. We do have tests where we verify that an exception block doesn't catch its own error: https://github.com/cockroachdb/cockroach/blob/81a06c6b1fc38fda134118b9e4541e61a4bce5ef/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L1500-L1511
And also one with duplicate catch branches: https://github.com/cockroachdb/cockroach/blob/81a06c6b1fc38fda134118b9e4541e61a4bce5ef/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L1449
</blockquote></details>

My terminology is poor, so I'm not sure if we're talking about the same thing. What I meant by multiple blocks was something like:
```
EXCEPTION
WHEN code1 THEN  
  INSERT INTO xy VALUES (-200,-200);
  RAISE code2;  
WHEN code2 THEN  
  RETURN 100;
END
```
In the other example test that does this, the codes are the same and we only pick the first WHEN/THEN block. Are you saying that even if the codes are different we only build that first block?

**Review by mgartner — APPROVED** [review]
Very cool! :lgtm: 

> Reviewed 2 of 13 files at r1, 1 of 5 files at r2, 8 of 13 files at r5, 4 of 5 files at r6, 3 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110998#-:-Nflfo_tAOVLneutKtc3:b1n0kfb)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball and @rharding6373)

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110998)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`pkg/sql/routine.go` line 296 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110998#-NfS5GxGCHZGGDjnqPrD:-NfloGvS8VdOeAwBuopZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f59cf63c56eca6dad337801b6fde453d11b03b3e/pkg/sql/routine.go#L296)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Could you s/drewk/111446?
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 1958 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110998#-NfSEb9lBbkndpR795Id:-NflphJCCxSMpYoC8WEq:bvnxl5d) ([raw file](https://github.com/cockroachdb/cockroach/blob/f59cf63c56eca6dad337801b6fde453d11b03b3e/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L1958)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

My terminology is poor, so I'm not sure if we're talking about the same thing. What I meant by multiple blocks was something like:
```
EXCEPTION
WHEN code1 THEN  
  INSERT INTO xy VALUES (-200,-200);
  RAISE code2;  
WHEN code2 THEN  
  RETURN 100;
END
```
In the other example test that does this, the codes are the same and we only pick the first WHEN/THEN block. Are you saying that even if the codes are different we only build that first block?
</blockquote></details>

I think I understand. I've added a case to verify that branches of an exception block don't interact with one another - LMK if you had something different in mind.

**Comment by DrewKimball** [comment]
TFTRs!

**Review by rharding6373 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110998)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner)

___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 1958 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110998#-NfSEb9lBbkndpR795Id:-NfmMULn6CBO-w644RJ6:b-sxnpcr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f59cf63c56eca6dad337801b6fde453d11b03b3e/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L1958)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I think I understand. I've added a case to verify that branches of an exception block don't interact with one another - LMK if you had something different in mind.
</blockquote></details>

That's exactly what I had in mind. Thanks!

**Pull request merged**
