### PR TITLE
Add a `make stress` target to mirror our other test runners

### PR DESCRIPTION
**Pull request by bdarnell**
[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3156)

### CODE REVIEW

**Comment by tamird** [comment]
Any reason not to add `stress` to GLOCKFILE?

**Comment by bdarnell** [comment]
Nope. Done.

**Comment by tschottdorf** [comment]
`-c` puts the `.test` binary into the parent directory of the package tested. For example, with `PKG=./sql/driver` it ends up in `./sql`. The helper needs to be aware of that (`go list ${PKG}` can probably help).

**Comment by bdarnell** [comment]
Ah, I didn't know that. I'll just pass `-o` when building the binary to put it in a known location.

**Comment by tamird** [comment]
It might be worth adding a `stressrace` target; I've always found `stress` to be more useful when running with the race detector.

**Comment by bdarnell** [comment]
Sure. `-race` is just a build-time flag, right? Nothing extra when running the test?

**Comment by tamird** [comment]
Yeah, I think that's right.

**Comment by bdarnell** [comment]
PTAL

**Comment by tamird** [comment]
LGTM

**Pull request merged**
