### PR TITLE
cli: inform the user when the sql shell automatically reconnects.

### LINKED ISSUE #9576: cli: Inform sql shell user when connection to the server is restarted
Our sql shell may drop and reconnect to the server on occasion. When this happens, any session-specific configurations defined via `SET` statements are lost. Although the docs recommend more reliable ways to define these settings, it'd nonetheless be helpful to inform users, directly in the sql shell, when a connection is restarted.

@knz

### PR DESCRIPTION
**Pull request by knz**
Fixes #9576.

cc @jseldess

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9613)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
LGTM (modulo the TestDockerCli error in TeamCity)

**Comment by knz** [comment]
Yes this is pending #9614.

**Comment by jseldess** [comment]
Message LGTM. Thanks, @knz!

**Comment by knz** [comment]
TFYR!

**Pull request merged**
