### PR TITLE
cli: ensure that `cockroach sql` doesn't choke on final comments.

### PR DESCRIPTION
**Pull request by knz**
Prior to this patch, `cockroach sql` would fail if the input data
would terminate with a SQL comment without a terminating semicolon
(semicolons are not required in comments!)

This patch addresses the issue by ensuring that `cockroach sql`
properly ignores lines what contain only whitespace, which includes
lines that contain only comments.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9243)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[cli/sql.go, line 96 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9243#-KRG6bzRWbYkHkBpJa96:-KRG6bzRWbYkHkBpJa97:bmr1mtu) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a3d82ee33d048d3f1b0ce19657a1135078b7a59/cli/sql.go#L96)):*
> ```Go
> // run a client-side command, print some help or continue with
> // a regular query.
> func handleInputLine(ins *readline.Instance, stmt *[]string, line string, syntax parser.Syntax) (status int, hasSet bool, isEmpty bool) {
> ```

[nit] long line

---

*[cli/sql_test.go, line 175 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9243#-KRG6uxHPigL4CCmqfUU:-KRG6uxHPigL4CCmqfUV:b7l07ot) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a3d82ee33d048d3f1b0ce19657a1135078b7a59/cli/sql_test.go#L175)):*
> ```Go
> 			syntax = parser.Traditional
> 		}
> 		_, isEnd, hasSet := isEndOfStatement(syntax, &[]string{test.in})
> ```

can we test the isEmpty return value too?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9243#-:-KRG7Da3B__w64KCjm8Q:bnfp4nl)*

**Comment by knz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[cli/sql.go, line 96 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9243#-KRG6bzRWbYkHkBpJa96:-KRG97HxPv8YBkrZ-qTC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a3d82ee33d048d3f1b0ce19657a1135078b7a59/cli/sql.go#L96)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> [nit] long line
</details>
Done.

---

*[cli/sql_test.go, line 175 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9243#-KRG6uxHPigL4CCmqfUU:-KRG980PL74wOrwyPJci:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a3d82ee33d048d3f1b0ce19657a1135078b7a59/cli/sql_test.go#L175)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> can we test the isEmpty return value too?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9243)*

**Comment by knz** [comment]
Waiting on #9250 resolution to merge.

**Comment by RaduBerinde** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9243)*

**Comment by knz** [comment]
Waiting on #9385 to merge which should fix #9250 and enable this one to go forward.

**Pull request merged**
