### PR TITLE
sql: support the `ALTER TYPE ... ADD VALUE` command

### LINKED ISSUE #48670: sql: support the ALTER TYPE ADD VALUE command
See https://www.postgresql.org/docs/9.1/sql-altertype.html.

### LINKED ISSUE #50972: sql: user defined type metadata should track descriptor version
The descriptor version should be part of the in memory type metadata stored in the `*types.T`. This information should be used to invalidate cached plans once types change.

### PR DESCRIPTION
**Pull request by rohany**
This PR adds support for `ALTER TYPE ... ADD VALUE` command. New values
added to the enum are added in a "non-writeable" state. Values in this
state are not constructible from the logical representation and are not
visible from enum builtins.

Fixes #50972.
Fixes #48670.

Release note: None

### CODE REVIEW

**Comment by rohany** [comment]
cc @RaduBerinde for `opt_catalog` related changes.

**Comment by RaduBerinde** [comment]
opt_catalog changes LGTM. I'd add some logictests in `prepare`, something where a prepared statement would return the wrong thing if it wasn't deemed stale because of an change in enums.

**Comment by rohany** [comment]
> I'd add some logictests in prepare, something where a prepared statement would return the wrong thing if it wasn't deemed stale because of a change in enums.

Done, thanks!

**Comment by rohany** [comment]
Pinging @lucy-zhang and @ajwerner for review

**Comment by rohany** [comment]
Friendly ping!

**Review by ajwerner — COMMENTED** [review]
What's the deal with backups when you restore an enum that has a value that's still in the read-only state?

> Reviewed 2 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51094#-:-MDFlNCqDjVOqHVq6o5j:b-tikbd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @lucy-zhang)

**Comment by rohany** [comment]
> What's the deal with backups when you restore an enum that has a value that's still in the read-only state?

Not much. We have two options:
* On restore, promote the values into public
* Like tables, start a type schema change job to do it (https://github.com/cockroachdb/cockroach/issues/50322). This option is probably more general.

**Review by ajwerner — COMMENTED** [review]
IIUC making them public should be safe and I expect is easier though I agree perhaps less general. Do we want to do anything or add a TODO around that?

> Reviewed 4 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51094#-:-MDGdhH_-3brCUvy---M:btrsna7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[pkg/sql/alter_type.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51094#-MDGe4Jx8Zs-b2B6dSsd:-MDGe4Jx8Zs-b2B6dSse:bl5wd25) ([raw file](https://github.com/cockroachdb/cockroach/blob/8583230f0362d53505f44495d57a202ddaeebe98/pkg/sql/alter_type.go#L76)):*
> ```Go
> 
> func (p *planner) addEnumValue(
> 	params runParams, n *alterTypeNode, node *tree.AlterTypeAddValue,
> ```

More a discussion of values, where would you like most of this logic to be ultimately? I feel like the process of interpretting the ast node should be here but the modifying the descriptor should live in `typedesc` as a method on a `MutableTypeDescriptor`. Thoughts?
___
*[pkg/sql/logictest/testdata/logic_test/enums, line 465 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51094#-MDGehbB43VJxoiAPNNQ:-MDGehbB43VJxoiAPNNR:b-v3290s) ([raw file](https://github.com/cockroachdb/cockroach/blob/8583230f0362d53505f44495d57a202ddaeebe98/pkg/sql/logictest/testdata/logic_test/enums#L465)):*
> ```
>   descriptor_name = 'enum_array' AND column_name = 'x'
> ----
> x  family:ArrayFamily width:0 precision:0 locale:"" visible_type:0 oid:100064 array_contents:<InternalType:<family:EnumFamily width:0 precision:0 locale:"" visible_type:0 oid:100063 time_precision_is_set:false udt_metadata:<stable_type_id:63 stable_array_type_id:64 > > TypeMeta:<Version:0 > > time_precision_is_set:false udt_metadata:<stable_type_id:64 stable_array_type_id:0 >
> ```

Do we like that this version is `0`? Should we reserve version zero as an invalid value? I thought we always start at `1` for descriptor versions.

**Review by ajwerner — COMMENTED** [review]
FWIW lgtm other than wanting to have some discussions here. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51094#-:-MDGf5qR78Bq9hwD3K_h:b-qtpl7h)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)

**Comment by rohany** [comment]
> IIUC making them public should be safe and I expect is easier though I agree perhaps less general. Do we want to do anything or add a TODO around that?

There is an issue tracking it, so we can tackle it there. The only hesitation around making them public is that it's not truly "the state that was backed up", but that's probably not a real concern.

> More a discussion of values, where would you like most of this logic to be ultimately? I feel like the process of interpretting the ast node should be here but the modifying the descriptor should live in typedesc as a method on a MutableTypeDescriptor. Thoughts?

It seems like it would make sense to put this on the typedesc -- it can even take in the AST node too. I'll update that.

> Do we like that this version is 0? Should we reserve version zero as an invalid value? I thought we always start at 1 for descriptor versions.

This is a bug that has been fixed already on master. It will be 1 once I rebase.

**Review by thoszhang — APPROVED** [review]
> There is an issue tracking it, so we can tackle it there. The only hesitation around making them public is that it's not truly "the state that was backed up", but that's probably not a real concern.

I think this is fine.

LGTM, aside from moving the logic for mutating the type descriptor.

> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51094#-:-MDGwho-C_8MVVFxwjR9:b-jkgv0l)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by rohany** [comment]
> Do we like that this version is 0? Should we reserve version zero as an invalid value? I thought we always start at 1 for descriptor versions.
This is a bug that has been fixed already on master. It will be 1 once I rebase.

Looked at this more -- the type metadata version field is getting set correctly, it's just that proto isn't printing it out correctly (because these fields exist outside of the proto representation).

**Comment by rohany** [comment]
TFTRs!

bors r+

**Pull request merged**
