### PR TITLE
opt: Add rule to simplify Is/IsNot conditions

### PR DESCRIPTION
**Pull request by andy-kimball**
The new SimplifyJoinNotNullCondition rules simplifies an Is/IsNot equality
filtercondition when it's not possible for it to be null (because the compared
variables can never be null). This pattern can be generated by the
NormalizeNotAnyFilter rule, and its simplification is necessary for making
anti-joins efficient, such as in TPCH query 16.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30248)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/join.go, line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30248#-LMSNwh29BLnBFeerfDx:-LMSNwh29BLnBFeerfDy:b-raaksy) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b69b56373e08baf1c51e4118121be53fb7dbb8c/pkg/sql/opt/norm/join.go#L85)):*
> ```Go
> 	case opt.IsOp:
> 		switch constOp {
> 		case opt.TrueOp:
> ```

For IS, aren't these true and false transformation correct regardless if the variables are not null?
Under a Filters, `x IS TRUE` should be the same with `x`, and `x IS FALSE` should be the same with `NOT x`. Would it be better to have a separate rules for these?
___
*[pkg/sql/opt/norm/rules/join.opt, line 352 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30248#-LMSMWI9DsREtRjSR5u8:-LMSMWIA5CtFwN9OK_aE:bpmj2gi) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b69b56373e08baf1c51e4118121be53fb7dbb8c/pkg/sql/opt/norm/rules/join.opt#L352)):*
> ```
> )
> 
> # SimplifyJoinNotNullCondition simplifies an Is/IsNot equality filter condition
> ```

It's not immediately clear what "Is/IsNot equality filter condition" means, can you write out an example in SQL? `(a=b) IS NOT NULL`?
___
*[pkg/sql/opt/norm/rules/join.opt, line 352 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30248#-LMSMtd_DpW4z3m48ea_:-LMSMtd_DpW4z3m48eaa:bu9x4in) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b69b56373e08baf1c51e4118121be53fb7dbb8c/pkg/sql/opt/norm/rules/join.opt#L352)):*
> ```
> )
> 
> # SimplifyJoinNotNullCondition simplifies an Is/IsNot equality filter condition
> ```

The name sounds more general than what it's doing, maybe `SimplifyJoinNotNullEquality`?
___
*[pkg/sql/opt/norm/rules/join.opt, line 365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30248#-LMSNJ7V4kYzlO7Sr77H:-LMSNJ7V4kYzlO7Sr77I:bl00cu) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b69b56373e08baf1c51e4118121be53fb7dbb8c/pkg/sql/opt/norm/rules/join.opt#L365)):*
> ```
>         $condition:(Is | IsNot
>             $eq:(Eq
>                 (Variable $col1:* & (IsColNotNull2 $col1 $left $right))
> ```

[nit] Add an inline comment here and say that each variable is either from the left or the right side (for a little while I wondered why we don't want it to be null on both sides, which of course does not make sense).

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30248)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/join.go, line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30248#-LMSNwh29BLnBFeerfDx:-LMSVhUwEgLHJpGYC8YF:bre9bkp) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b69b56373e08baf1c51e4118121be53fb7dbb8c/pkg/sql/opt/norm/join.go#L85)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

For IS, aren't these true and false transformation correct regardless if the variables are not null?
Under a Filters, `x IS TRUE` should be the same with `x`, and `x IS FALSE` should be the same with `NOT x`. Would it be better to have a separate rules for these?
</blockquote></details>

Yes, it's true that `IS` could be simplified in additional cases. However, I thought I'd include it here b/c there's very little extra cost to do so. I'm hesitant to add an extra rule for `IS`, b/c I don't know of cases that need it, and it would require another traversal of the `Filters` list. Maybe once I'm done merging adjacent rules in `optgen` we could add more traversal rules (then it will have very low cost b/c we traverse only once).

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> Reviewed 3 of 6 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30248#-:-LMSjLUlCTQDM9W9Eg7D:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/norm/join.go, line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30248#-LMSNwh29BLnBFeerfDx:-LMSjGnI2AVawJUxhjrx:brxp9sq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b69b56373e08baf1c51e4118121be53fb7dbb8c/pkg/sql/opt/norm/join.go#L85)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Yes, it's true that `IS` could be simplified in additional cases. However, I thought I'd include it here b/c there's very little extra cost to do so. I'm hesitant to add an extra rule for `IS`, b/c I don't know of cases that need it, and it would require another traversal of the `Filters` list. Maybe once I'm done merging adjacent rules in `optgen` we could add more traversal rules (then it will have very low cost b/c we traverse only once).
</blockquote></details>

Sounds good.

**Review by rytaft — APPROVED** [review]
:lgtm:

[nit] in the commit message:  rules simplifies -> rule simplifies

> Reviewed 3 of 6 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30248#-:-LMZK7zD0X-8Rptg9JJ9:b8t5ybm)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/norm/join.go, line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30248#-LMZJUds0IvR3MXNFJ5G:-LMZJUdt8CaWz7fU4vTS:b-z608tm) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d8e7d3789be9a457a1cead17b70ef9d989037eb/pkg/sql/opt/norm/join.go#L74)):*
> ```Go
> // SimplifyNotNullEquality simplifies an expression of the following form:
> //
> //   (Is | IsNot (Eq) (True | False | Null)
> ```

[nit] missing right parentheses

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30248)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/norm/join.go, line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30248#-LMZJUds0IvR3MXNFJ5G:-LN0z1q26IamCcE2xpQC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d8e7d3789be9a457a1cead17b70ef9d989037eb/pkg/sql/opt/norm/join.go#L74)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] missing right parentheses
</blockquote></details>

Done.

**Pull request merged**
