### PR TITLE
build: delete `vendor` submodule

### PR DESCRIPTION
**Pull request by rickystewart**
The `vendor` submodule is not really necessary for anything any more.
For the Bazel build, we have mirrored all of our dependencies, so
vendoring provides no additional value. `go` tooling is also generally
happy to point to the module cache for e.g. go-to-definition. Dealing
with the submodule is a pain, so it behooves us to get rid of it.

For `make` builds, the `vendor` directory will be synthesized
automatically. It is now a `gitignore`'d directory. You can also
still `make vendor_rebuild` if you want to force synthesizing the
directory. Tooling can be updated to just not use `-mod=vendor` and the
`go` module cache should be used in its place transparently.

Epic: None
Release note: None

### CODE REVIEW

**Comment by rickystewart** [comment]
Note the first commit is from #93290 and can be ignored.

**Comment by rickystewart** [comment]
This might need a few more tweaks to make CI happy but other than that this PR is ready.

**Comment by rickystewart** [comment]
Screen Shot 2022-12-09 at 4 44 31 PM

With any luck this is the last `vendor` conflict. 🤞

**Review by knz — APPROVED** [review]
- Why did you not need to update the paths to `github.com/pkg/sftp.clientConn` etc in `pkg/testutils/lint/testdata/errcheck_excludes.txt`?
- the `scripts/deplicense.sh` script needs to be updated (at the end)
- might need to strip a remaining reference to `vendor` in `pkg/cli/flags_test.go`

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89442#-:-NIt6kPlB9kRgOPaUCMc:b-c8qrb8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @healthy-pod)

**Comment by rickystewart** [comment]
> Why did you not need to update the paths to github.com/pkg/sftp.clientConn etc in pkg/testutils/lint/testdata/errcheck_excludes.txt?

Evidently this dependency is not used any more; it's not present in `go.mod`. I've deleted the stale entries from this file.

> the scripts/deplicense.sh script needs to be updated (at the end)

I am not sure this script actually works, but I added a `make vendor_rebuild` here so the script won't break if it is used.

> might need to strip a remaining reference to vendor in pkg/cli/flags_test.go

The test here is actually completely broken, so it doesn't matter. See #81526 for the standing bug to pull its functionality into a linter. However I did update the test anyway.

**Comment by knz** [comment]
thanks

**Review by dt — APPROVED** [review]

**Comment by rickystewart** [comment]
bors r=knz,dt

**Pull request merged**
