### PR TITLE
storage: return a retryable error on transaction deadline exceeded

### LINKED ISSUE #18684: sql: TransactionStatusError: transaction deadline exceeded
When running TPCC with more than a single thread, occasionally a transaction will fail with the following error:

` pq: TransactionStatusError: transaction deadline exceeded`

What is this about? What is the referenced deadline? It seems like a bug that this message is propagated to the user, but what internal condition is causing this scenario and why?

Any ideas? cc @andreimatei @bdarnell

### PR DESCRIPTION
**Pull request by spencerkimball**
Previously, transaction deadline exceeded would return a
`TransactionStatusError`, a non-retryable error condition which would
fail the transaction unrecoverably. The transaction deadlines are used
to ensure that no transaction commits after the expiration of table
leases which were acquired during the transaction based on accessed
tables.

This change instead returns a `TransactionRetryError` and introduces a
new reason: `roachpb.RETRY_DEADLINE_EXCEEDED`. We might have created a
new error, but that would introduce a lot of additional special casing
to allow retries.

Fixes #18684

Release note (sql change): clients should stop seeing "transaction
deadline exceeded" errors.

### CODE REVIEW

**Comment by andreimatei** [comment]
See https://github.com/cockroachdb/cockroach/issues/18684#issuecomment-371295769

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23569#-:-L71RYKI2NLy0UUhEMjC:b-9ab3yn)*

**Comment by vivekmenezes** [comment]
This change will make me happier if we have a test that writes a value, attempts to commit hits the retryable error and writes the value again and succeeds. I say this because the last time I tried doing this change the intents were not cleared out and such a test would fail.

**Comment by andreimatei** [comment]
Yeah, I have become increasingly unsure why TPCC is seeing this. The error would need to be encountered by a query accessing a table that hasn't been accessed in a minute, or by a transaction that has been pushed by a minute. These seem... unlikely.

If we can explain why the error happens, then, although I was arguing thing similar to Ben in https://github.com/cockroachdb/cockroach/issues/18684#issuecomment-371295769 , I have failed to convince Spencer of anything and I've come to think that this PR is good enough for me.

@jordanlewis would you be interested in getting some traces from TPCC for a deadlined txn?

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23569#-:-L7655JzE5Un2ubIeuP3:b-c4jbyy)*

**Comment by bdarnell** [comment]
I was remembering an old version of the code - we used to guarantee that there was at least a minute left on the lease, but it looks like we stopped in #16842. This is allowing transactions to be run with much shorter deadlines, making this error more common. (see https://github.com/cockroachdb/cockroach/issues/18684#issuecomment-371599985)

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23569#-:-L767BByIBt8-rn9sWNf:bwed59s)*

**Comment by jordanlewis** [comment]
Ping. If this fixes #18684 then it would be great to get this in very soon.

**Comment by andreimatei** [comment]
It'd be great if you could produce a trace for a transaction like this so we can understand better exactly how TPCC is getting such an error. The straight-forward explanation (a query accessing a table that hasn't been accessed previously for a minute just below the point where the lease expires, and then its transaction being pushed) seems a bit unlikely to me.

**Comment by jordanlewis** [comment]
How would you suggest producing such a trace? Observing it is unpredictable.

**Comment by andreimatei** [comment]
> How would you suggest producing such a trace? Observing it is unpredictable.

One way is to wrap whatever transaction gets this error on occasion in `set tracing=on; ... set tracing=off` and, when the client sees the error, printing the results of `show trace for session`.
Or, server-side, also trapping the error somewhere in SQL and printing a) information on the txn - the OrigTimestamp and the RefreshedTimestamp, and b) information on the leases used - I think that can be found in the `connExecutor's` `tableCollection`.

Or, the cleanest way if you can pull it off, is to trace everything and, when the server sees the error, annotate the trace in whatever way can be queried by jaeger.

**Comment by benesch** [comment]
Ok, I managed to grab a trace of this error:

https://gist.github.com/benesch/2ab0424760d98f70f5031d9d4e57c0c8

@andreimatei and I dug in and everything in the trace seems "normal". We have a transaction that does some stuff, commits, gets pushed, update spans, and then fails on the second end transaction because it's now past the deadline. So the question remains: why is it using a table descriptor that's so close to its expiration?

There's also some unrelated funny business in the trace: specifically, the second end transaction fails with a retryable error (?!) when in fact it seems like it might have succeeded. Looks like it might be a bug in txnCoordSender.appendRefreshSpansLocked.

Apologies if none of this makes sense. I need to call it a night.

**Comment by bdarnell** [comment]
We should add some more tracing to `sql/lease.go` to get more details about how much time is left on the lease when it is acquired. We can also trace the background lease renewal transactions. In theory, leases last for at least 4 minutes (nominally 5 minutes, but jittered by +/- 25%, which seems awfully high), and when we try to use a lease with less than a minute remaining it queues up a refresh in the background. So while there is no formal minimum time left on the lease, we would expect to have a minimum of one minute minus the duration of the lease renewal itself.

**Comment by benesch** [comment]
I should have mentioned: I turned the lease duration way down (~15s) to get this trace. It's possible that doing so triggers different behavior.

**Comment by benesch** [comment]
I managed to get a trace of the deadline exceeded error on a binary with the default 5m leases:

https://gist.github.com/benesch/3a828bb611a1eedd8cb61e09ff7d169c

...the culprit appears to be a 2m long (!) txn.

**Comment by benesch** [comment]
Jordan points out that I've been using an underprovisioned cluster, so it seems the deadline expired errors I saw may have been related to stuck transactions and not a bug in the lease code. Attempting to repro again with heftier nodes.

**Comment by benesch** [comment]
Moving conversation back to #18684.

**Comment by vivekmenezes** [comment]
We will not be needing this. Thanks!

**Comment by jordanlewis** [comment]
Wait, why won't we be needing it? Unless you can guarantee a client will never see one of these, they need to be retryable.

**Comment by vivekmenezes** [comment]
for 2.1 I'm planning to completely eliminate the error. I'm going to update the issue with the plan.

**Pull request closed without merging**
