### PR TITLE
sql: add a comment that JSON behaviour is similar to JSONB

### LINKED ISSUE #44465: `to_json()` results don't match Postgres
For example the following query:
```sql
SELECT to_json(x.*) FROM (VALUES (1,2)) AS x(column2);
```
currently returns a "duplicate column" error. 

After #41557  is merged, CockroachDB will return
```
   to_json
------------------
  {"column2": 2}
```

but Postgres returns
```
   to_json
------------------
{"column2":1,"column2":2}
```

So, duplicate column names in the input of `to_json` need to be included as duplicate keys in the resulting JSON object.

The correct test cases have been added as a TODO comment in #41557 https://github.com/cockroachdb/cockroach/pull/41557/files#diff-e9dd4e05509f6f7fc35050a751db0ea0R327.

I am willing to tackle this issue but feel free to re-assign if needed.

### PR DESCRIPTION
**Pull request by giorgosp**
Closes #44465
Release note : None

### CODE REVIEW

**Comment by giorgosp** [comment]
Sorry just noticed the CI failure. Fixed!

**Comment by tbg** [comment]
@jordanlewis did this slip?

**Comment by jordanlewis** [comment]
Sure did! Sorry @giorgosp and thanks

bors r+

**Comment by giorgosp** [comment]
No problem!

**Comment by SWDevAngel** [comment]
@giorgosp Hi George. Thank you for contributing to CockroachDB this year. As a token of our appreciation we would like to send you a gift. Please DM me on our [community Slack](https://cockroa.ch/slack) `@lisa` so I can send you a link. (If you don’t want a gift, we also have a charitable contribution choice.) All orders need to be in by December 13, so please send this asap. :)

**Pull request merged**
