### PR TITLE
Upgrade google.golang.org/grpc, fixing gogoproto incompatibility

### LINKED ISSUE #60531: vendor: can't upgrade to grpc-go v1.34
**Describe the problem**

Cockroach built with grpc-go v1.34 panics shortly after start with the following error when running `./cockroach demo`:

```
panic: field cockroach.rpc.PingRequest.ping has invalid type: got string, want pointer [recovered]
        panic: field cockroach.rpc.PingRequest.ping has invalid type: got string, want pointer [recovered]
        panic: field cockroach.rpc.PingRequest.ping has invalid type: got string, want pointer

goroutine 6034 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc000b5e540, 0x91db960, 0xc0003ca9c0)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:231 +0x126
panic(0x7c5cf40, 0xc000e7e9d0)
        /usr/local/Cellar/go/1.15.7_1/libexec/src/runtime/panic.go:969 +0x1b9
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc000b5e540, 0x91db960, 0xc0003ca9c0)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:231 +0x126
panic(0x7c5cf40, 0xc000e7e9d0)
        /usr/local/Cellar/go/1.15.7_1/libexec/src/runtime/panic.go:969 +0x1b9
google.golang.org/protobuf/internal/impl.fieldInfoForScalar(0x932f640, 0xc0021eae00, 0x7b876a7, 0x4, 0x0, 0x0, 0x932f760, 0x7c5cf40, 0x7b876ad, 0x2c, ...)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/protobuf/internal/impl/message_reflect_field.go:228 +0x7d7
google.golang.org/protobuf/internal/impl.(*MessageInfo).makeKnownFieldsFunc(0xc002152000, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xc002544150, 0xc002544180, 0xc0025441b0, 0xc0025441e0)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/protobuf/internal/impl/message_reflect.go:67 +0x97d
google.golang.org/protobuf/internal/impl.(*MessageInfo).makeReflectFuncs(0xc002152000, 0x932f760, 0x829db40, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xc002544150, 0xc002544180, 0xc0025441b0, ...)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/protobuf/internal/impl/message_reflect.go:36 +0x65
google.golang.org/protobuf/internal/impl.(*MessageInfo).initOnce(0xc002152000)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/protobuf/internal/impl/message.go:90 +0x192
google.golang.org/protobuf/internal/impl.(*MessageInfo).init(...)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/protobuf/internal/impl/message.go:72
google.golang.org/protobuf/internal/impl.(*messageReflectWrapper).ProtoMethods(0xc000e7e6d0, 0xc002095218)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/protobuf/internal/impl/message_reflect_gen.go:150 +0x53
google.golang.org/protobuf/proto.protoMethods(...)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/protobuf/proto/proto_methods.go:18
google.golang.org/protobuf/proto.MarshalOptions.marshal(0xc000000001, 0x0, 0x0, 0x0, 0x93222e0, 0xc000e7e6d0, 0xc000e7e6d0, 0x93222e0, 0xc000e7e6d0, 0x827bf40, ...)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/protobuf/proto/encode.go:143 +0x49
google.golang.org/protobuf/proto.MarshalOptions.MarshalAppend(0x8000001, 0x0, 0x0, 0x0, 0x9143a00, 0xc000e7e6d0, 0x0, 0x14f790d8, 0x8, 0x7ca0d20, ...)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/protobuf/proto/encode.go:125 +0x98
github.com/golang/protobuf/proto.marshalAppend(0x0, 0x0, 0x0, 0x14f790d8, 0xc001b04e40, 0x4054000, 0xc001030ba8, 0x0, 0x0, 0xc001030ba8, ...)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/github.com/golang/protobuf/proto/wire.go:40 +0xc7
github.com/golang/protobuf/proto.Marshal(...)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/github.com/golang/protobuf/proto/wire.go:23
google.golang.org/grpc/encoding/proto.codec.Marshal(0x827bf40, 0xc001b04e40, 0xc001030ba8, 0xc002095468, 0xc002095468, 0x486316b, 0x7ca0d20)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/encoding/proto/proto.go:39 +0x5f
google.golang.org/grpc.encode(0x14b9cf40, 0xc000ac60d0, 0x827bf40, 0xc001b04e40, 0xc001380a60, 0xc0020956c8, 0xc000100000, 0x0, 0x0)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/rpc_util.go:592 +0x52
google.golang.org/grpc.prepareMsg(0x827bf40, 0xc001b04e40, 0x14b9cf40, 0xc000ac60d0, 0x0, 0x0, 0x91b6d20, 0xb4fa868, 0x2, 0xc0021bced0, ...)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:1559 +0x107
google.golang.org/grpc.(*clientStream).SendMsg(0xc002735e60, 0x827bf40, 0xc001b04e40, 0x0, 0x0)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:740 +0x165
google.golang.org/grpc.invoke(0x91db9e0, 0xc001b04f60, 0x84bd3b3, 0x1d, 0x827bf40, 0xc001b04e40, 0x827c060, 0xc0027fc640, 0xc002279180, 0xc0027fc1c0, ...)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/call.go:70 +0xe4
github.com/cockroachdb/cockroach/pkg/util/tracing.ClientInterceptor.func2(0x91db9e0, 0xc001b04f60, 0x84bd3b3, 0x1d, 0x827bf40, 0xc001b04e40, 0x827c060, 0xc0027fc640, 0xc002279180, 0x8b4ed88, ...)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/util/tracing/grpc_interceptor.go:257 +0x158
google.golang.org/grpc.(*ClientConn).Invoke(0xc002279180, 0x91db9e0, 0xc001b04f60, 0x84bd3b3, 0x1d, 0x827bf40, 0xc001b04e40, 0x827c060, 0xc0027fc640, 0x0, ...)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/call.go:35 +0x109
github.com/cockroachdb/cockroach/pkg/rpc.(*heartbeatClient).Ping(0xc0003de498, 0x91db9e0, 0xc001b04f60, 0xc001b04e40, 0x0, 0x0, 0x0, 0x91db960, 0xc0003ca9c0, 0xc001c0c3a1ccb1d8)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/rpc/heartbeat.pb.go:199 +0xcf
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).runHeartbeat.func3.2(0x91db9e0, 0xc001b04f60, 0x165a0bc00, 0x91db9e0)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:1161 +0xb8
github.com/cockroachdb/cockroach/pkg/util/contextutil.RunWithTimeout(0x91db9e0, 0xc001b04f60, 0x847a1e0, 0xd, 0x165a0bc00, 0xc000c5ac30, 0x0, 0x0)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/util/contextutil/context.go:140 +0x9e
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).runHeartbeat.func3(0x91db960, 0xc0003ca9c0, 0x40d5669, 0xc000c5ae28)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:1166 +0x332
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr(0xc000b5e540, 0x91db960, 0xc0003ca9c0, 0x847a1e0, 0xd, 0xc000c5ad78, 0x0, 0x0)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:331 +0xb2
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).runHeartbeat(0xc00013afc0, 0xc0029119f0, 0xc00189ce10, 0xf, 0xc000ce08a0, 0x0, 0x0)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:1134 +0x42b
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).grpcDialNodeInternal.func1.1(0x91db960, 0xc0003ca9c0)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:1054 +0x79
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc000b5e540, 0x91db960, 0xc0003ca9c0, 0x0, 0xc002911ae0)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:352 +0xb9
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:347 +0xfc
```

I believe the likely cause is https://github.com/grpc/grpc-go/pull/3958.

It isn't immediately necessary to upgrade this dependency, so there is no impact at the moment.

### PR DESCRIPTION
**Pull request by stevendanna**
In a different line of work, attempting to upgrade a client library for
google cloud APIs brought in an upgrade to google.golang.org/grpc and revealed
that a recent changes to google.golang.org/grpc have modified the default
proto codec such that it is incompatible with gogoproto:

grpc/grpc-go#3958

While `proto.Marshal` does do a check for the Marshal/Unmarshal it
appears to do this through reflection methods that will panic on
fields using gogoproto.nullable.

To avoid this, we install a proto codec that does an interface check
before dispatching to proto.Marshal/proto.Unmarshal.

Note that I haven't replicated the protobuffer caching that previously
existed in google.golang.org/grpc. The referenced change claims
removing the caching may be a small performance win; however, they
also removed the typecheck that we need to do, so it is unclear.

The upgrade of google.golang.org/grpc is larger than I might like, but I 
was unable to convince Go to upgrade fewer dependencies as the grpc update
forces an update of google.golang.org/api, which then forces an upgrade
of a number of other dependencies.  If we don't want to take the dependency 
upgrade yet, we can merge the first commit to unblock future upgrades.

Fixes #60531

### CODE REVIEW

**Review by tbg — COMMENTED** [review]
Thank you @stevendanna and sorry for letting this sit! Due to the stability period, I would postpone the merge to after the release branch has been cut. I have held off on scrutinizing the dep bump so far, so we'd have to do that before the merge.

Also cc @knz for server/networking.

> Reviewed 4 of 4 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60709#-:-MUi67A96ttRSjBzDB9f:bsg9xnb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif)

**Review by knz — COMMENTED** [review]
wowzer that's a lot of dep changes.

The changes inside crdb LGTM, but as usual we will want to scrutinize the upstream changes as well. Agreed with Tobias that may not be suitable for the 21.1 release but we should get this started soon afterwards.

> Reviewed 3 of 4 files at r1, 7 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60709#-:-MUi7b209vhQit81pTeD:buf73nw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif)

**Review by stevendanna — COMMENTED** [review]
@knz @tbg Completely understandable and likely very prudent.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60709#-:-MUiB1s60DmWHpGBgV3Y:b-1elpe9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif)

___
*[pkg/rpc/codec.go, line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60709#-MUiBE0k71XNgdkV_QK_:-MUiBE0k71XNgdkV_QKa:bpfnp8i) ([raw file](https://github.com/cockroachdb/cockroach/blob/eec99848347d0841f73fa31350ab2db48497c74f/pkg/rpc/codec.go#L29)):*
> ```Go
> 		return pm.Marshal()
> 	}
> 	return protoutil.Marshal(v.(protoutil.Message))
> ```

I updated this line to use protoutil in accordance with the linter.  But, I think we should probably exclude this file from the linter and move this back to calling one of the proto libraries directly.  My concern is that the conversion to protoutil.Message requires that the MarshalTo method be implemented which I don't think is going to be the case for various third party libraries.

**Comment by stevendanna** [comment]
I've pulled out the first commit and added some tests for it here: https://github.com/cockroachdb/cockroach/pull/61333

I still think both the new codec and this upgrade can wait until we cut a new branch though.

**Pull request closed without merging**
