### PR TITLE
acceptance: update how we build the `python` compose image

### PR DESCRIPTION
**Pull request by rickystewart**
Up until this point we were using `apt install postgresql-client` to
install the `psql` binary in this image. Because the `postgresql-client`
`apt` package was apparently updated to a later version of `postgres`
last week that includes [this change](https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=a59c79564bdc209a5bc7b02d706f0d7352eb82fa),
the `TestComposeGSSPython` `acceptance` test started failing with the
following error:

```
psql: error: private key file "/certs/client.root.key" must be owned by the current user or root
```

Less recent versions of `psql` are more permissive about cert
permissions, so we work around this by simply copying a less recent
version of `psql` from the older `postgres:11` image.

Release note: None
Release justification: Test-only change

### CODE REVIEW

**Review by otan — APPROVED** [review]
thanks for looking into this!!!

**Comment by otan** [comment]
hmm, looks like it's failing with

```

        python_1     | Creating a k5s token...
        kdc_1        | krb5kdc: starting...
        python_1     | Password for tester@MY.EX: 
        python_1     | Creating test user
        python_1     | Error: You must install at least one postgresql-client-<version> package
```

**Comment by rickystewart** [comment]
Yep, I think I'll have to do a couple more iterations on this. 🙄 Very annoying. Stay tuned.

**Comment by rickystewart** [comment]
bors r=otan

**Pull request merged**
