### PR TITLE
kv: add WaitPolicy option to BatchRequest

### PR DESCRIPTION
**Pull request by nvb**
Informs #40476.
Informs #51624.

This commit introduces the concept of request "wait policies". A
WaitPolicy specifies the behavior of a request when it encounters
conflicting locks held by other active transactions. The default
behavior is to block until the conflicting lock is released, but other
policies can make sense in special situations.

Within this new formalization, the commit creates two initial wait
policy variants:
```
// Block indicates that if a request encounters a conflicting locks held by
// another active transaction, it should wait for the conflicting lock to be
// released before proceeding.
Block = 0;

// Error indicates that if a request encounters a conflicting locks held by
// another active transaction, it should raise an error instead of blocking.
Error = 1;
```

`Block` is equivalent to the current behavior, so there's no further
action needed for that variant.

However, the `Error` policy is new, and this commit teaches the
`lockTableWaiter` about it. It ensures that when a request with the
`Error` wait policy encounters a conflicting lock, it uses a PUSH_TOUCH
PushRequest to determine whether the lock is abandoned or whether its
holder is still active. If the holder is abandoned, the request cleans
up the lock and proceeds. If the holder is still active, a
WriteIntentError is returned to the client.

This will unblock both of the referenced issues.

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
Pls tell me again why it'd be harder to set the policy at the request level instead of the batch level? I think allowing it to *also* be set on the batch would be ideal in which case it'd override the individual requests (or it could even error if an individual request also sets it).

How does the `Error` policy behave within high-pri txns? I think we want to make sure that it's pushes *only* succeed on abandoned txns, not also on lower-pri live txns, but that's not what the code does (is it?). Or better yet, how about splitting `Error` into `ErrorOnEqualOrHigherPri` and `ErrorOnAny`?

Have you put any though into a policy for `select... skip locked` ?

Pls make sure that the no-wait policy is reflected in `ba.String()`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52388#-:-MDzF8qO46d9no_DkIei:b-4kznwe)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52388#-MDzKIrt4QeT3LJY4RGy:-MDzKIrt4QeT3LJY4RGz:b-4ynoxb) ([raw file](https://github.com/cockroachdb/cockroach/blob/afb9d1091b9cac9f7caded5902683731f78b68b0/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L173)):*
> ```Go
> 						err = w.pushLockTxn(ctx, req, state)
> 					} else {
> 						err = newWriteIntentErr(state)
> ```

what about non-replicated locks? Do we want `WriteIntentError` for those?
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 442 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52388#-MDzLPbjADZIP8Ef41GT:-MDzLPbjADZIP8Ef41GU:b-efpd87) ([raw file](https://github.com/cockroachdb/cockroach/blob/afb9d1091b9cac9f7caded5902683731f78b68b0/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L442)):*
> ```Go
> 	switch req.WaitPolicy {
> 	case lock.WaitPolicy_Block:
> 		// The wait policy signifies that the request wants to wait until the
> ```

nit: s/The wait policy/This wait policy

same below
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 450 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52388#-MDzKorzAlgVfh-LkxnZ:-MDzKorzAlgVfh-Lkxn_:b-k78qk) ([raw file](https://github.com/cockroachdb/cockroach/blob/afb9d1091b9cac9f7caded5902683731f78b68b0/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L450)):*
> ```Go
> 		switch ws.guardAccess {
> 		case spanset.SpanReadOnly:
> 			pushType = roachpb.PUSH_TIMESTAMP
> ```

Not related to this patch, but please remind me - if a `PUSH_TIMESTAMP` succeeds, will that unblock other readers at lower timestamps (besides the one that did the successful push)?
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52388#-MDzLEk2E4NgsbMD8JYm:-MDzLEk2E4NgsbMD8JYn:b-mzlm4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/afb9d1091b9cac9f7caded5902683731f78b68b0/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L451)):*
> ```Go
> 		case spanset.SpanReadOnly:
> 			pushType = roachpb.PUSH_TIMESTAMP
> 			log.VEventf(ctx, 3, "pushing timestamp of txn %s above %s", ws.txn.ID.Short(), h.Timestamp)
> ```

`3` seems high here and below. Let's use the more standard 2.
___
*[pkg/kv/kvserver/concurrency/lock/locking.proto, line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52388#-MDzFMZ6-OmaznHmlobv:-MDzFMZ6-OmaznHmlobw:b4n047q) ([raw file](https://github.com/cockroachdb/cockroach/blob/afb9d1091b9cac9f7caded5902683731f78b68b0/pkg/kv/kvserver/concurrency/lock/locking.proto#L176)):*
> ```protobuf
> 
>   // Error indicates that if a request encounters a conflicting locks held by
>   // another active transaction, it should raise an error instead of blocking.
> ```

spell out what error

Also spell out that this doesn't apply to abandoned locks.

**Review by nvb — COMMENTED** [review]
> Pls tell me again why it'd be harder to set the policy at the request level instead of the batch level? I think allowing it to also be set on the batch would be ideal in which case it'd override the individual requests (or it could even error if an individual request also sets it).

Because we aggregate and deduplicate all of a batch request's spans before entering the concurrency manager. So the concurrency manager doesn't know which spans correspond to which (it could be multiple) individual requests. I don't disagree that this could be a nice thing to support, but since we don't need it, I don't think we should go out of our way to support it.

> How does the Error policy behave within high-pri txns? I think we want to make sure that it's pushes only succeed on abandoned txns, not also on lower-pri live txns, but that's not what the code does (is it?). Or better yet, how about splitting Error into ErrorOnEqualOrHigherPri and ErrorOnAny?

That's a good question. Its pushes do only succeed on abandoned txns, see:
https://github.com/cockroachdb/cockroach/blob/d013d122c6a0ec135f933afa4fa5a31fe40697c3/pkg/kv/kvserver/batcheval/cmd_push_txn.go#L230-L236

And also see `TestPushTxnHeartbeatTimeout`, which tests the push behavior.

I added this case to `TestTxnWaitPolicies`.

> Have you put any though into a policy for select... skip locked ?

Not a lot. Only that I'm not as eager to implement it because we haven't seen any interest in it from users and also because it violates serializability, whereas `nowait` does not.

> Pls make sure that the no-wait policy is reflected in ba.String()

Good point. Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52388#-:-ME3tQjG3-PqWr-x6Q4X:b5sxzka)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52388#-MDzKIrt4QeT3LJY4RGy:-ME3rOKIA3Kt6A0MucvY:b-gf0gsr) ([raw file](https://github.com/cockroachdb/cockroach/blob/afb9d1091b9cac9f7caded5902683731f78b68b0/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L173)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what about non-replicated locks? Do we want `WriteIntentError` for those?
</blockquote></details>

Yes, that's ok. WriteIntentError is a bit of a misnomer at this point now that we have different forms of locks, but it's exactly what we want.
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 442 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52388#-MDzLPbjADZIP8Ef41GT:-ME3rslYBekYXeMedp3F:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/afb9d1091b9cac9f7caded5902683731f78b68b0/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L442)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: s/The wait policy/This wait policy

same below
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 450 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52388#-MDzKorzAlgVfh-LkxnZ:-ME3s-Sv8g6du_CEKXyW:bt2mlrj) ([raw file](https://github.com/cockroachdb/cockroach/blob/afb9d1091b9cac9f7caded5902683731f78b68b0/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L450)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Not related to this patch, but please remind me - if a `PUSH_TIMESTAMP` succeeds, will that unblock other readers at lower timestamps (besides the one that did the successful push)?
</blockquote></details>

Let on in this function we use the IntentResolver to move the lock's timestamp forward. Doing so triggers a state transition in the lock-table which unblocks the other readers. This is discussed in this method's comment.
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52388#-MDzLEk2E4NgsbMD8JYm:-ME3rvue2EgsMshPnuJ-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/afb9d1091b9cac9f7caded5902683731f78b68b0/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L451)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

`3` seems high here and below. Let's use the more standard 2.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/concurrency/lock/locking.proto, line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52388#-MDzFMZ6-OmaznHmlobv:-ME3sKLb77v8UI8egE-K:be5fxgx) ([raw file](https://github.com/cockroachdb/cockroach/blob/afb9d1091b9cac9f7caded5902683731f78b68b0/pkg/kv/kvserver/concurrency/lock/locking.proto#L176)):*
> spell out what error

I actually omitted this deliberately, as the error type is not a concern of this package. This package is merely defining the locking concepts that the KV API uses. The comment on `Header.wait_policy` spells out what error is returned by the KV API when this wait policy is used.

> Also spell out that this doesn't apply to abandoned locks.

That's what the "active transaction" was meant to indicate, but I agree that it's better to be explicit. Done.

**Review by andreimatei — APPROVED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52388#-:-ME8iGqz7QkHnjE6_cIk:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52388#-MDzKIrt4QeT3LJY4RGy:-ME8gQyG2MeuuKiSZq2Z:b2nhysk) ([raw file](https://github.com/cockroachdb/cockroach/blob/afb9d1091b9cac9f7caded5902683731f78b68b0/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L173)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yes, that's ok. WriteIntentError is a bit of a misnomer at this point now that we have different forms of locks, but it's exactly what we want.
</blockquote></details>

ack
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 450 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52388#-MDzKorzAlgVfh-LkxnZ:-ME8ggz7Bh5y_upyKRY7:b2nhysk) ([raw file](https://github.com/cockroachdb/cockroach/blob/afb9d1091b9cac9f7caded5902683731f78b68b0/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L450)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let on in this function we use the IntentResolver to move the lock's timestamp forward. Doing so triggers a state transition in the lock-table which unblocks the other readers. This is discussed in this method's comment.
</blockquote></details>

ack
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 477 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52388#-ME8hbyA7-fSpZKyBI5l:-ME8hbyA7-fSpZKyBI5m:bstfiu6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a89adf93a7457a9ac28443cf79e6ffa5711808a2/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L477)):*
> ```Go
> 		// until completion (except when DontRetryPushTxnFailures is set).
> 		// Transform the error into a WriteIntentError.
> 		if _, ok := err.GetDetail().(*roachpb.TransactionPushError); ok && pushType == roachpb.PUSH_TOUCH {
> ```

consider looking at the `req.WaitPolicy` again instead of looking at the `pushType`. I think I'd find that clearer and you wouldn't need the comment above.

**Review by nvb — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52388#-:-ME8lrPDBXZ_wb4B5vHd:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 477 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52388#-ME8hbyA7-fSpZKyBI5l:-ME8kdhf5KIey1IQQZ5H:bv3e0ri) ([raw file](https://github.com/cockroachdb/cockroach/blob/a89adf93a7457a9ac28443cf79e6ffa5711808a2/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L477)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

consider looking at the `req.WaitPolicy` again instead of looking at the `pushType`. I think I'd find that clearer and you wouldn't need the comment above.
</blockquote></details>

That's actually how I had it, and I switched to this because I was thinking that other wait policies might use a PUSH_TOUCH in the future. But I think you're right that mapping a TransactionPushError to a WriteIntentError is a property of the wait policy, not the push type. I'll switch back.

**Pull request merged**
