### PR TITLE
Enhance CONTRIBUTING.md

### LINKED ISSUE #4555: ui: `go generate` fails on Linux because of osx-specific dependency
While working on #4548 I needed to run `go generate` and encountered the following:

```
npm install --progress=false
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated object-pick@0.1.2: Deprecated as of version 0.1.2 please use object.pick instead.
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.0.7
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! System Linux 4.2.0-27-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--progress=false"
npm ERR! cwd /home/kena/go/src/github.com/cockroachdb/cockroach/ui
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code EBADPLATFORM
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0
 as soon as possible.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0
 as soon as possible.
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/kena/go/src/github.com/cockroachdb/cockroach/ui/npm-debug.log
npm ERR! not ok code 0
Makefile:102: recipe for target 'npm.installed' failed
make: *** [npm.installed] Error 1
ui/ui.go:21: running "make": exit status 2
```

### PR DESCRIPTION
**Pull request by knz**
As suggested by @bdarnell.

Fixes #4555.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4575)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CONTRIBUTING.md, line 43 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4575#-KB9Sr5m1lIOrsM0mN5w:-KB9Sr5m1lIOrsM0mN5x:1231857670) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a6a37fd0b7f21ef98d80c739922e8594f86801d/CONTRIBUTING.md#L43)):*
i think that documenting this oddity at all is just asking for trouble, where people will come in and contribute further oddities. we don't want to maintain that list.

let's advise people use the builder image and stop there.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4575)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CONTRIBUTING.md, line 43 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4575#-KB9Sr5m1lIOrsM0mN5w:-KB9TKzd1EoV_PQBmg9_:1718959820) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a6a37fd0b7f21ef98d80c739922e8594f86801d/CONTRIBUTING.md#L43)):*
I beg to disagree (not very had but still) -- Debian and Ubuntu are  the most commonly used distros and also the first choice for people doing Dev from VMs (like I do). We're not catering to a niche here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4575)*

**Comment by tamird** [comment]
I'm not saying it's a niche, I'm just saying you're inviting headaches.
It's just not worth it.

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CONTRIBUTING.md, line 30 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4575#-KB9UpgXdu0CoVla3MXo:-KB9UpgXdu0CoVla3MXp:1544456869) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a6a37fd0b7f21ef98d80c739922e8594f86801d/CONTRIBUTING.md#L30)):*
We may want to recommend running `go generate` on the package you're editing instead of `./...`. That way if you don't touch anything in the `ui` directory you don't need to worry about nodejs/npm.

---

*[CONTRIBUTING.md, line 43 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4575#-KB9Sr5m1lIOrsM0mN5w:-KB9UEAAozrPexvx0qRV:-726676774) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a6a37fd0b7f21ef98d80c739922e8594f86801d/CONTRIBUTING.md#L43)):*
Does this symlink even matter? The ui makefile doesn't run `node`, it runs `npm`. As long as you have matching versions of `npm` and `node(js)`, shouldn't it still work? 

I think that ubuntu is as important a platform for us as OSX; if we're not going to tell people how to run `go generate` without docker on ubuntu we should remove the part about `brew install node` too. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4575)*

**Comment by knz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[CONTRIBUTING.md, line 30 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4575#-KB9UpgXdu0CoVla3MXo:-KB9hkPGLHtsUDYDH52n:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a6a37fd0b7f21ef98d80c739922e8594f86801d/CONTRIBUTING.md#L30)):*
Done.

---

*[CONTRIBUTING.md, line 43 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4575#-KB9Sr5m1lIOrsM0mN5w:-KB9hmYCqQ1f973WP7Tj:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a6a37fd0b7f21ef98d80c739922e8594f86801d/CONTRIBUTING.md#L43)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4575)*

**Comment by tamird** [comment]
LGTM

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CONTRIBUTING.md, line 30 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4575#-KB9UpgXdu0CoVla3MXo:-KB9jbbW8KDy4QVFaUQa:1081306398) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a6a37fd0b7f21ef98d80c739922e8594f86801d/CONTRIBUTING.md#L30)):*
Doesn't look like this was done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4575#-:-KB9jddTPgCyEwgLJl64:676834233)*

**Comment by knz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[CONTRIBUTING.md, line 30 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4575#-KB9UpgXdu0CoVla3MXo:-KBA3cZe_tfp2sFKbq6X:-2094067690) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a6a37fd0b7f21ef98d80c739922e8594f86801d/CONTRIBUTING.md#L30)):*
It was but I forgot to commit the result :) It is there now.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4575)*

**Pull request merged**
