### PR TITLE
insights: stop ingesting on shutdown

### LINKED ISSUE #87673: unknown: (unknown) failed [sqlstats/persistedsqlstats: stuck when flushing during shutdown]
unknown.(unknown) [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RandomSyntaxTestsBazel/6400384?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RandomSyntaxTestsBazel/6400384?buildTab=artifacts#/) on master @ [a82711442c65cf14489c55041b45b11a1e38415b](https://github.com/cockroachdb/cockroach/commits/a82711442c65cf14489c55041b45b11a1e38415b):

```
Slow failing tests:
TestRandomSyntaxGeneration - 355.98s
TestRandomSyntaxFunctions - 238.45s

Slow passing tests:
TestRandomSyntaxSelect - 300.57s
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #78002 unknown: (unknown) failed [C-test-failure O-robot branch-release-22.1]
- #69997 unknown: (unknown) failed [C-test-failure O-robot branch-release-21.2 sync-me-8]
- #65139 unknown: (unknown) failed [C-test-failure O-robot branch-release-21.1]
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*\(unknown\).*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-19467

### LINKED ISSUE #88087: unknown: (unknown) failed [sqlstats/persistedsqlstats: stuck when flushing during shutdown]
unknown.(unknown) [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RandomSyntaxTestsBazel/6495728?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RandomSyntaxTestsBazel/6495728?buildTab=artifacts#/) on release-22.2 @ [aac413cd4ca62f3392029b42219ebb2788979fb8](https://github.com/cockroachdb/cockroach/commits/aac413cd4ca62f3392029b42219ebb2788979fb8):

```
Slow failing tests:
TestRandomSyntaxGeneration - 349.45s
TestRandomSyntaxFunctions - 245.04s

Slow passing tests:
TestRandomSyntaxSelect - 300.51s
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #87673 unknown: (unknown) failed [C-test-failure O-robot branch-master]
- #78002 unknown: (unknown) failed [C-test-failure O-robot branch-release-22.1]
- #69997 unknown: (unknown) failed [C-test-failure O-robot branch-release-21.2 sync-me-8]
- #65139 unknown: (unknown) failed [C-test-failure O-robot branch-release-21.1]
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*\(unknown\).*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-19674

### PR DESCRIPTION
**Pull request by matthewtodd**
Fixes #87673.
Fixes #88087.

Previously, the insights ingester could block if observing a high enough volume of SQL traffic on server shutdown, after its consumption loop had already quiesced. (We suspect this high volume of traffic is most likely due to flushing SQL stats at shutdown time.)

Here we avoid blocking by simply dropping these observations. They are most likely for internal executions anyway and thus not particularly interesting from an insights perspective.

Release justification: Fixes for high-priority or high-severity bugs in existing functionality.

Release note: None

### CODE REVIEW

**Review by j82w — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89337)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @matthewtodd)

___
*[`pkg/sql/sqlstats/insights/ingester_test.go` line 149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89337#-ND_J13vE4xZt8NAoU4X:-ND_J13vE4xZt8NAoU4Y:b-ezag65) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c885b8728b212168cfb2c9b2ec2a257c092b241/pkg/sql/sqlstats/insights/ingester_test.go#L149)):*
> ```Go
> 	go func() {
> 		// We push enough observations to fill the ingester's channel at least
> 		// twice. With no consumer of the channel running and no safeguards in
> ```

Why is the consumer allowed to shutdown before the ingestor? Shouldn't it have to wait for the ingestor to finish and then it can shutdown?

**Review by matthewtodd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89337)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

___
*[`pkg/sql/sqlstats/insights/ingester_test.go` line 149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89337#-ND_J13vE4xZt8NAoU4X:-ND_NtJ-2frjM1LfEAW0:b-2dyiw0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c885b8728b212168cfb2c9b2ec2a257c092b241/pkg/sql/sqlstats/insights/ingester_test.go#L149)):*
<details><summary><i>Previously, j82w wrote…</i></summary><blockquote>

Why is the consumer allowed to shutdown before the ingestor? Shouldn't it have to wait for the ingestor to finish and then it can shutdown? 
</blockquote></details>

See `concurrentBufferIngester.Start()`. There's a producing and a consuming side to the ingester, the producer driven by statement executions, and the consumer this background goroutine.

**Review by j82w — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89337)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd)

___
*[`pkg/sql/sqlstats/insights/ingester.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89337#-NDcLh7b8fer2ZayDAkR:-NDcLh7b8fer2ZayDAkS:b3uk92c) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c885b8728b212168cfb2c9b2ec2a257c092b241/pkg/sql/sqlstats/insights/ingester.go#L62)):*
> ```Go
> 	// underlying registry.
> 	_ = stopper.RunAsyncTask(ctx, "insights-ingester", func(ctx context.Context) {
> 		atomic.StoreUint64(&i.running, 1)
> ```

Nit: Make 0 and 1 a const

**Comment by j82w** [comment]
*[`pkg/sql/sqlstats/insights/ingester_test.go` line 149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89337#-ND_J13vE4xZt8NAoU4X:-ND_JwD64kkZwB4YcHT3:b-nwdh5p) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c885b8728b212168cfb2c9b2ec2a257c092b241/pkg/sql/sqlstats/insights/ingester_test.go#L149)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

See `concurrentBufferIngester.Start()`. There's a producing and a consuming side to the ingester, the producer driven by statement executions, and the consumer this background goroutine.
</blockquote></details>

Shouldn't the consumer background goroutine continue to run until the ingester is stopped?

**Review by matthewtodd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89337)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd)

___
*[`pkg/sql/sqlstats/insights/ingester_test.go` line 149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89337#-ND_J13vE4xZt8NAoU4X:-NDcUn1gA-i-Y2aTedFj:bnn5rbh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c885b8728b212168cfb2c9b2ec2a257c092b241/pkg/sql/sqlstats/insights/ingester_test.go#L149)):*
<details><summary><i>Previously, j82w wrote…</i></summary><blockquote>

Shouldn't the consumer background goroutine continue to run until the ingester is stopped?
</blockquote></details>

Stopping the ingester is the same thing as stopping that background coroutine.

**Review by matthewtodd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89337)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd)

___
*[`pkg/sql/sqlstats/insights/ingester_test.go` line 149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89337#-ND_J13vE4xZt8NAoU4X:-NDcbAUnEzuJOtJwwT3_:b7538bx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c885b8728b212168cfb2c9b2ec2a257c092b241/pkg/sql/sqlstats/insights/ingester_test.go#L149)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Stopping the ingester is the same thing as stopping that background coroutine.
</blockquote></details>

Talked in-person and captured follow-up work in #89390.

**Pull request merged**
