### PR TITLE
optbuilder: do not CAST recursive CTE seed columns to output types

### LINKED ISSUE #93371: sql: internal type mismatch error from vectorized engine caused by recursive CTE
The following query produces a type mismatch error on CockroachDB. On Postgres, it returns a more pleasant user-visible error.

```
 WITH RECURSIVE foo(i) AS
    (SELECT i FROM (VALUES(1),(2)) t(i)
    UNION ALL
    SELECT (i+1)::numeric(10,0) FROM foo WHERE i < 10)
 SELECT * FROM foo;
```

CRDB:

```
demo@127.0.0.1:26257/defaultdb> WITH RECURSIVE foo(i) AS                                                                                                                                                                               ->     (SELECT i FROM (VALUES(1),(2)) t(i)                                                                                                                                                                ->     UNION ALL                                                                                                                                                                                          ->     SELECT (i+1)::numeric(10,0) FROM foo WHERE i < 10)                                                                                                                                                 ->  SELECT * FROM foo;

  i
-----
  1
(1 row)
(error encountered after some results were delivered)
ERROR: internal error: unexpected error from the vectorized engine: interface conversion: coldata.Column is coldata.Int64s, not coldata.Decimals
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:89: func1()
GOROOT/src/runtime/panic.go:884: gopanic()
GOROOT/src/runtime/iface.go:262: panicdottypeE()
GOROOT/src/runtime/iface.go:272: panicdottypeI()
github.com/cockroachdb/cockroach/pkg/col/coldata/vec.go:245: Decimal()
github.com/cockroachdb/cockroach/bazel-out/k8-fastbuild/bin/pkg/sql/colexec/colexecprojconst/proj_const_right_ops.eg.go:2607: func1()
github.com/cockroachdb/cockroach/pkg/sql/colmem/allocator.go:441: PerformOperation()
github.com/cockroachdb/cockroach/bazel-out/k8-fastbuild/bin/pkg/sql/colexec/colexecprojconst/proj_const_right_ops.eg.go:2603: Next()
github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/operator.go:137: Next()
github.com/cockroachdb/cockroach/bazel-out/k8-fastbuild/bin/pkg/sql/colexec/colexecbase/cast.eg.go:7795: Next()
github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase/simple_project.go:124: Next()
github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:278: next()
github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:303: nextAdapter()
github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92: CatchVectorizedRuntimeError()
github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:309: Next()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:130: next()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:147: nextAdapter()
github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92: CatchVectorizedRuntimeError()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:152: Next()
github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:186: Run()
github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:733: Run()
github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:483: Run()
github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:296: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:815: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1768: PlanAndRun()
github.com/cockroachdb/cockroach/pkg/sql/apply_join.go:334: runPlanInsidePlan()
github.com/cockroachdb/cockroach/pkg/sql/recursive_cte.go:151: Next()
github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:218: Next()
github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:243: Next()
github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:116: next()
github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92: CatchVectorizedRuntimeError()
github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:124: Next()
```

PG:

```
jordan=#  WITH RECURSIVE foo(i) AS
jordan-#     (SELECT i FROM (VALUES(1),(2)) t(i)
jordan(#     UNION ALL
jordan(#     SELECT (i+1)::numeric(10,0) FROM foo WHERE i < 10)
jordan-#  SELECT * FROM foo;
ERROR:  recursive query "foo" column 1 has type integer in non-recursive term but type numeric overall
LINE 2:     (SELECT i FROM (VALUES(1),(2)) t(i)
                    ^
HINT:  Cast the output of the non-recursive term to the correct type.
```

Jira issue: CRDB-22290

### PR DESCRIPTION
**Pull request by msirek**
Fixes #93371

Given the query:
```
SET VECTORIZE=off;
WITH RECURSIVE foo(i) AS
    (SELECT i FROM (VALUES(1),(2)) t(i)
    UNION ALL
    SELECT (i+1)::numeric(10,0) FROM foo WHERE i < 10)
 SELECT * FROM foo;
```
column `i` is CAST to the output type of the UNION ALL due to #62808 in order to support more recursive CTEs without explicit CASTS in seed (initial) expressions:
https://github.com/cockroachdb/cockroach/blob/0eac48e70abbdd163d4617e50659321b99d678d4/pkg/sql/opt/optbuilder/with.go#L335-L337

Column `i` is assigned column id 3 in `WithScanPrivate.InCols` and the expression in `recursiveScope.cols[0].scalar` references it as follows:
```
recursiveScope.cols[0].scalar:
result = {opt.ScalarExpr | *memo.CastExpr}
 Input = {opt.ScalarExpr | *memo.PlusExpr}
  Left = {opt.ScalarExpr | *memo.VariableExpr}
   Col = {opt.ColumnID} 3
   Typ = {*types.T | 0x976b060}
    InternalType = {types.InternalType}
     Family = {types.Family} IntFamily (1)
...
    TypeMeta = {types.UserDefinedTypeMetadata}
   rank = {opt.ScalarRank} 5
  Right = {opt.ScalarExpr | *memo.ConstExpr}
   Value = {tree.Datum | *tree.DInt} 1
```
After the CAST is applied, column id 3 is initialized as:
```
initialScope.cols[0].scalar:
 result = {opt.ScalarExpr | *memo.CastExpr}
 Input = {opt.ScalarExpr | *memo.VariableExpr}
  Col = {opt.ColumnID} 1
  Typ = {*types.T | 0x976b060}
  rank = {opt.ScalarRank} 12
 Typ = {*types.T | 0xc0037f2780}
  InternalType = {types.InternalType}
   Family = {types.Family} DecimalFamily (3)
   Width = {int32} 0
   Precision = {int32} 10
```
During execution, an assertion fails where the input to the `PlusExpr` is expected to be an integer, but is a decimal:
```
tree.MustBeDInt (datum.go:722) github.com/cockroachdb/cockroach/pkg/sql/sem/tree
eval.(*evaluator).EvalPlusIntOp (binary_op.go:1325) github.com/cockroachdb/cockroach/pkg/sql/sem/eval
tree.(*PlusIntOp).Eval (eval_op_generated.go:761) github.com/cockroachdb/cockroach/pkg/sql/sem/tree
eval.(*evaluator).EvalBinaryExpr (expr.go:120) github.com/cockroachdb/cockroach/pkg/sql/sem/eval
tree.(*BinaryExpr).Eval (eval_expr_generated.go:86) github.com/cockroachdb/cockroach/pkg/sql/sem/tree
eval.(*evaluator).EvalCastExpr (expr.go:180) github.com/cockroachdb/cockroach/pkg/sql/sem/eval
tree.(*CastExpr).Eval (eval_expr_generated.go:96) github.com/cockroachdb/cockroach/pkg/sql/sem/tree
eval.Expr (expr.go:26) github.com/cockroachdb/cockroach/pkg/sql/sem/eval
execinfrapb.(*ExprHelper).Eval (expr.go:248) github.com/cockroachdb/cockroach/pkg/sql/execinfrapb
execinfra.(*ProcOutputHelper).ProcessRow (processorsbase.go:275) github.com/cockroachdb/cockroach/pkg/sql/execinfra
...
```
The left of the Plus is referring to the `IndexedVar` column at ordinal 0:
```
result = {*tree.BinaryExpr | 0xc0022e27c0}
 Operator = {treebin.BinaryOperator}
  Symbol = {treebin.BinaryOperatorSymbol} Plus (3)
  IsExplicitOperator = {bool} false
 Left = {tree.Expr | *tree.IndexedVar}
  Idx = {int} 0
  Used = {bool} true
  col = {tree.NodeFormatter | *colinfo.varFormatter}
  typeAnnotation = {tree.typeAnnotation}
 Right = {tree.Expr | *tree.DInt} 1
 typeAnnotation = {tree.typeAnnotation}
 Op = {*tree.BinOp | 0xc0001817a0}
 ```
which has been CAST as a decimal, as indicated above.

To fully support casting of seed expressions, that may require replacing
all occurences of those expressions in `recursiveScope` with the new
CASTed expressions, and possibly re-doing type checking to catch any
illegal casts, etc.

This issue is solved by reverting #62808 in order to maintain
compatibility with Postgres, which errors out this query.
Relaxing the requirement for explicit CASTs in recursive CTE seed
expressions could possibly be supported in the future, but more work is
required to substitute seed expressions present in the recursive branch
with the implicitly CASTed expressions and make sure type checking is
complete.

Release note(bug fix): This patch fixes recursive CTE expressions which
cause internal errors when explicit CASTs of initial expressions to
output types are missing.

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
Nice find! It's a bit surprising that Postgres won't automatically cast when an implicit cast is allowed, like a cast from `INT -> NUMERIC`:

```
marcus=# select * from pg_cast where castsource = 'int4'::regtype and casttarget = 'numeric'::regtype;
  oid  | castsource | casttarget | castfunc | castcontext | castmethod
-------+------------+------------+----------+-------------+------------
 10014 |         23 |       1700 |     1740 | i           | f
(1 row)
```

I checked PG's [type conversion docs](https://www.postgresql.org/docs/15/typeconv.html) to see if there was any explanation of this, but couldn't find anything. :shrug: 

:lgtm: Once you fixup the two tests.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94581#-:-NKsnUXG-kP_Fp4PGAWh:b78eo9j)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek and @yuzefovich)

___
*[`pkg/sql/opt/norm/testdata/rules/with` line 1872 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94581#-NKsmsiwAgUGQU910ayl:-NKsmsixC1NOAoFQPesQ:b-ecy4hc) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b574c566a77b0ed50dcc2e6a43359b726829750/pkg/sql/opt/norm/testdata/rules/with#L1872)):*
> ```
>   (SELECT 1, 2)
>   UNION ALL
>   (SELECT i+1, sum(j) FROM cte WHERE i <= 10 GROUP BY i)
> ```

nit: sum(j)::INT to avoid the error
___
*[`pkg/sql/opt/norm/testdata/rules/with` line 2422 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94581#-NKsmxA83WJMJTBbslmf:-NKsmxA9BuYRZ3YH0-QZ:bdgxup0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b574c566a77b0ed50dcc2e6a43359b726829750/pkg/sql/opt/norm/testdata/rules/with#L2422)):*
> ```
>   (SELECT 1, 2)
>   UNION ALL
>   (SELECT i+1, sum(x) FROM cte INNER JOIN xy ON j = y WHERE i <= 10 GROUP BY i)
> ```

nit: `sum(x)::INT` to avoid the error

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94581#-:-NKssC6n2hSF_86Md42z:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @msirek and @yuzefovich)

**Review by yuzefovich — APPROVED** [review]
I agree with Marcus that it'd be nicer to add explicit casts in some of the affected tests. :lgtm: though.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94581#-:-NKtFU_32YCTWE1XqluP:bu31eg3)* status: :shipit: complete! 3 of 0 LGTMs obtained (waiting on @msirek)

___
*[`pkg/sql/opt/optbuilder/with.go` line 341 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94581#-NKtEXLR9392hnT7r5K_:-NKtEXLR9392hnT7r5Ka:b-qkrpcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b574c566a77b0ed50dcc2e6a43359b726829750/pkg/sql/opt/optbuilder/with.go#L341)):*
> ```Go
> 				panic(pgerror.Newf(
> 					pgcode.DatatypeMismatch,
> 					"UNION types %s and %s cannot be matched for WITH RECURSIVE",
> ```

nit: I see that this is the error message we had prior to #62808, but we generally try to match the postgres error message as close as possible (at least that what I was told during my internship four years ago), and PG returns:
```
ERROR:  recursive query "foo" column 1 has type integer in non-recursive term but type numeric overall
```
for the original repro from the issue.

**Comment by mgartner** [comment]
*[`pkg/sql/opt/optbuilder/with.go` line 341 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94581#-NKtEXLR9392hnT7r5K_:-NKtNrtk71UbS6E44wdb:b-40bi5p) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b574c566a77b0ed50dcc2e6a43359b726829750/pkg/sql/opt/optbuilder/with.go#L341)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I see that this is the error message we had prior to #62808, but we generally try to match the postgres error message as close as possible (at least that what I was told during my internship four years ago), and PG returns:
```
ERROR:  recursive query "foo" column 1 has type integer in non-recursive term but type numeric overall
```
for the original repro from the issue.
</blockquote></details>

Good catch. Let's match PG error messages as close as reasonably possible :+1:

**Review by msirek — COMMENTED** [review]
Added explicit casts in `pkg/sql/opt/norm/testdata/rules/with` as suggested. Explicit casts are not added in `pkg/sql/opt/optbuilder/with.go` as those were originally testing for presence of an implicit cast, so now are testing for the absence of an implicit cast.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94581#-:-NKuHn4E-aMZAmnjvsW2:b-x46ng7)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale) (waiting on @mgartner and @yuzefovich)

___
*[`pkg/sql/opt/optbuilder/with.go` line 341 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94581#-NKtEXLR9392hnT7r5K_:-NKuIJZv0oWPZ9EKoYsB:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b574c566a77b0ed50dcc2e6a43359b726829750/pkg/sql/opt/optbuilder/with.go#L341)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Good catch. Let's match PG error messages as close as reasonably possible :+1: 
</blockquote></details>

Done
___
*[`pkg/sql/opt/norm/testdata/rules/with` line 1872 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94581#-NKsmsiwAgUGQU910ayl:-NKuIMUm38BhJHLImFsa:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b574c566a77b0ed50dcc2e6a43359b726829750/pkg/sql/opt/norm/testdata/rules/with#L1872)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: sum(j)::INT to avoid the error
</blockquote></details>

Done
___
*[`pkg/sql/opt/norm/testdata/rules/with` line 2422 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94581#-NKsmxA83WJMJTBbslmf:-NKuINO1DJeY8FssEEko:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b574c566a77b0ed50dcc2e6a43359b726829750/pkg/sql/opt/norm/testdata/rules/with#L2422)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: `sum(x)::INT` to avoid the error
</blockquote></details>

Done

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94581#-:-NKwy7wd3CN4mWvu1a6X:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @msirek)

**Review by msirek — COMMENTED** [review]
TFTRs! 
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94581#-:-NKxYRSlDmcHBCReiSj6:bn2quta)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @msirek)

**Pull request merged**
