### PR TITLE
sql/sem/builtins: mark timeofday as impure

### PR DESCRIPTION
**Pull request by madelynnblue**

### CODE REVIEW

**Review by otan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44268)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/44268#-LzI5IaWCtuiyMdpMfWV:-LzI5IaX5rcTV-8AfNXM:bw41dv9) (no related file):*
Ah what happens if we don't do this?
Also, not sure release note is necessary as timeofday hasn't been released yet. 

---

**Review by otan — APPROVED** [review]

**Comment by mjibson** [comment]
Incorrectly marked impure functions can change how plan caching is done and maybe some other stuff? It's like a theoretical correctness issue I think.

**Comment by mjibson** [comment]
Oh also sqlsmith uses function purity to decide if a query can be run in two places identically.

**Pull request merged**
