### PR TITLE
storage: expose LazyValue for reverse scanning in pebbleMVCCScanner

### PR DESCRIPTION
**Pull request by sumeerbhola**
Informs cockroachdb/pebble#1170

Epic: CRDB-20378

### CODE REVIEW

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94725#-:-NL1l5mSCvcg06Bbp-ub:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

___
*[`pkg/storage/engine.go` line 309 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94725#-NL1jL4pCxdy5QgY_iVU:-NL1inNe8ORKipVJfDgD:b-r9769l) ([raw file](https://github.com/cockroachdb/cockroach/blob/019299b0443d1a242afda4a655090dbcc5872d7a/pkg/storage/engine.go#L309)):*
> ```Go
> 	//
> 	// REQUIRES: Valid() returns true.
> 	UnsafeLazyValue() pebble.LazyValue
> ```

nit: do any non-pkg/storage implementations need to provide an implementation? If not, I think we could  unexport it as `unsafeLazyValue` to make it only be visible within the storage package.

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94725#-:-NL1oKb5ERGBAFo-EXay:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @jbowens)

___
*[`pkg/storage/engine.go` line 309 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94725#-NL1jL4pCxdy5QgY_iVU:-NL1nu88ELONYtV26mMK:b-xbwae8) ([raw file](https://github.com/cockroachdb/cockroach/blob/019299b0443d1a242afda4a655090dbcc5872d7a/pkg/storage/engine.go#L309)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

nit: do any non-pkg/storage implementations need to provide an implementation? If not, I think we could  unexport it as `unsafeLazyValue` to make it only be visible within the storage package.
</blockquote></details>

`spanset.MVCCIterator` needs to implement `storage.MVCCIterator`, which it can't do if the interface method is unexported. Is there some Golang magic I am missing?

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94725)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

___
*[`pkg/storage/engine.go` line 309 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94725#-NL1jL4pCxdy5QgY_iVU:-NL2-iOJ5Z1c6R4WlKom:b-39f65) ([raw file](https://github.com/cockroachdb/cockroach/blob/019299b0443d1a242afda4a655090dbcc5872d7a/pkg/storage/engine.go#L309)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

`spanset.MVCCIterator` needs to implement `storage.MVCCIterator`, which it can't do if the interface method is unexported. Is there some Golang magic I am missing?
</blockquote></details>

If `spanset.MVCCIterator` can implement the method by relying on an embedded type that implements the method, I _think_ it can still implement the interface. eg,

```
type MVCCIterator struct {
    storage.MVCCIterator
}
```

but might not be worth the inflexibility :man_shrugging:

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94725)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @jbowens)

___
*[`pkg/storage/engine.go` line 309 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94725#-NL1jL4pCxdy5QgY_iVU:-NL2FiAa3FT4q2Ossq3z:b6pw92a) ([raw file](https://github.com/cockroachdb/cockroach/blob/019299b0443d1a242afda4a655090dbcc5872d7a/pkg/storage/engine.go#L309)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

If `spanset.MVCCIterator` can implement the method by relying on an embedded type that implements the method, I _think_ it can still implement the interface. eg,

```
type MVCCIterator struct {
    storage.MVCCIterator
}
```

but might not be worth the inflexibility :man_shrugging: 
</blockquote></details>

Agreed about embedded type. I don't want to do that for `spanset.MVCCIterator` since then it will automatically implement any new methods added to the interface, without a conscious choice that the new method needs the span checking or not.

**Comment by sumeerbhola** [comment]
bors r=jbowens

**Pull request merged**
