### PR TITLE
opt: consider limit hint for select filter cost

### LINKED ISSUE #59713: opt: select cost is incorrect when there is a limit hint
Consider the following example:
```
SET CLUSTER SETTING sql.stats.automatic_collection.enabled = false;

CREATE TABLE tab (
	id INT PRIMARY KEY,
	geog GEOGRAPHY,
	INVERTED INDEX (geog)
);

ALTER TABLE tab INJECT STATISTICS '[
    {
        "columns": [
            "id"
        ],
        "created_at": "2021-01-01 00:00:00",
        "distinct_count": 500000,
        "name": "__auto__",
        "row_count": 500000
    }
]';

EXPLAIN (OPT, VERBOSE) SELECT id FROM tab@primary
WHERE st_dwithin(geog, st_makepoint(1.0, 1.0)::geography, 200)
LIMIT 10;
                                                                            info
------------------------------------------------------------------------------------------------------------------------------------------------------------
  project
   ├── columns: id:1
   ├── cardinality: [0 - 10]
   ├── immutable
   ├── stats: [rows=10]
   ├── cost: 505200.624
   ├── key: (1)
   ├── prune: (1)
   └── limit
        ├── columns: id:1 geog:2
        ├── cardinality: [0 - 10]
        ├── immutable
        ├── stats: [rows=10]
        ├── cost: 505200.514
        ├── key: (1)
        ├── fd: (1)-->(2)
        ├── select
        │    ├── columns: id:1 geog:2
        │    ├── immutable
        │    ├── stats: [rows=55000, distinct(2)=50000, null(2)=0]
        │    ├── cost: 505200.404
        │    ├── key: (1)
        │    ├── fd: (1)-->(2)
        │    ├── limit hint: 10.00
        │    ├── prune: (1)
        │    ├── scan tab
        │    │    ├── columns: id:1 geog:2
        │    │    ├── flags: force-index=primary
        │    │    ├── stats: [rows=500000, distinct(1)=500000, null(1)=0, distinct(2)=50000, null(2)=5000]
        │    │    ├── cost: 200.383636
        │    │    ├── key: (1)
        │    │    ├── fd: (1)-->(2)
        │    │    ├── limit hint: 90.91
        │    │    └── prune: (1,2)
        │    └── filters
        │         └── st_dwithin(geog:2, '0101000020E6100000000000000000F03F000000000000F03F', 200.0) [outer=(2), immutable, constraints=(/2: (/NULL - ])]
        └── 10
(37 rows)
```
Notice that the cost of the scan is relatively small (~200), which is due to the limit hint. The cost of the select, however, is over 500,000, because it is not taking the limit hint into account. The predicate `st_dwithin` is relatively expensive to execute, so the assumption that it must be executed on 500,000 rows (the number of input rows ignoring the limit hint) results in a significantly higher cost than if the limit hint were taken into account and an estimate of ~90 rows were used instead.

### PR DESCRIPTION
**Pull request by mgartner**
This commit updates the coster to take a limit hint into account when
calculating the cost of a Select. If a limit hint `n` exists, the filter
is expected to only be evaluated on the number of rows required to
produce `n` rows after the filter is applied. This is especially
important for filters with very expensive functions, such as geo-spatial
functions.

Fixes #59713

Release justification: This is a low-risk change that improves optimizer
costing, especially for geo-spatial queries.

Release note (performance improvement): The optimizer now estimates the
cost of evaluating query filters more accurately for queries with a
LIMIT. Previously, it was assumed that the filter would be evaluated on
each input row. Now, the optimizer assumes that the filter will only be
evaluated on the number of rows required to produce the LIMIT's number
of rows after filtering. This may lead to more efficient query plans in
some cases.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61745)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/memo/testdata/stats/inverted-geo, line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61745#-MVO-KgY3YmLegnB-6H5:-MVO-KgY3YmLegnB-6H6:bozy7no) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc616af0f8bd70a051e9aefea1ddedd2053a8a2a/pkg/sql/opt/memo/testdata/stats/inverted-geo#L87)):*
> ```
>       │    │         ├── columns: i:1(int) g:2(geometry)
>       │    │         └── stats: [rows=2000, distinct(2)=7, null(2)=0]
>       │    └── filters
> ```

Interesting plan change.. Given that the filter is expensive, we prefer to first sort everything and then apply the filter only on as many rows as we need. Pretty cool!
___
*[pkg/sql/opt/xform/coster.go, line 643 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61745#-MVO-Z_DDSEBV4EA-cd0:-MVO-Z_DDSEBV4EA-cd1:bdosl7m) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc616af0f8bd70a051e9aefea1ddedd2053a8a2a/pkg/sql/opt/xform/coster.go#L643)):*
> ```Go
> 	// evaluated on the number of rows required to produce n rows.
> 	if required.LimitHint != 0 {
> 		inputRowCount = math.Min(inputRowCount, required.LimitHint / sel.Relational().Stats.Selectivity.AsFloat())
> ```

If Selectivity is 0, this would still work, right? It would be nice to add a test (it would probably need to use `build` to avoid normalization).
___
*[pkg/sql/opt/xform/testdata/coster/select, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61745#-MVO-1KI06-_0goD_UU4:-MVO-1KI06-_0goD_UU5:b4m3gx8) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc616af0f8bd70a051e9aefea1ddedd2053a8a2a/pkg/sql/opt/xform/testdata/coster/select#L25)):*
> ```
> exec-ddl
> CREATE TABLE g (
> 	id INT PRIMARY KEY,
> ```

[nit] use spaces

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61745#-:-MVO0ACt6dsZrDf04HCR:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61745)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

___
*[pkg/sql/opt/memo/testdata/stats/inverted-geo, line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61745#-MVO-KgY3YmLegnB-6H5:-MVO1v4wDmWc4yASXR8d:br2vlnr) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc616af0f8bd70a051e9aefea1ddedd2053a8a2a/pkg/sql/opt/memo/testdata/stats/inverted-geo#L87)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Interesting plan change.. Given that the filter is expensive, we prefer to first sort everything and then apply the filter only on as many rows as we need. Pretty cool!
</blockquote></details>

Haha ya... I stared confusedly at it for a while because it breaks the common pattern of filtering before sorting.
___
*[pkg/sql/opt/xform/coster.go, line 643 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61745#-MVO-Z_DDSEBV4EA-cd0:-MVO4ZWG7faEIypucCAH:b54z2nn) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc616af0f8bd70a051e9aefea1ddedd2053a8a2a/pkg/sql/opt/xform/coster.go#L643)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

If Selectivity is 0, this would still work, right? It would be nice to add a test (it would probably need to use `build` to avoid normalization).
</blockquote></details>

Good point. It works fine because `10.0 / 0.0 = +Inf` (no panic), so `math.Min` returns `inputRowCount`. Test added.
___
*[pkg/sql/opt/xform/testdata/coster/select, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61745#-MVO-1KI06-_0goD_UU4:-MVO5UdAC_k978OILbgQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc616af0f8bd70a051e9aefea1ddedd2053a8a2a/pkg/sql/opt/xform/testdata/coster/select#L25)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] use spaces
</blockquote></details>

Done.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61745#-:-MVO6SGs3NUFQxrRDNJX:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Comment by mgartner** [comment]
TFTR!

bors r+

**Pull request merged**
