### PR TITLE
distsql: implement evaluator (processor core type)

### PR DESCRIPTION
**Pull request by irfansharif**
Implementation of the `Evaluator` processor core type, a fully
programmable no-grouping aggregator that runs a 'program' on each
individual row. The 'program' is a set of expressions evaluated in
order, the results of evaluating each of these expressions on the input
row form the output.

Part of #7587, pulled out of the original work in #9793 (see [this](https://github.com/cockroachdb/cockroach/pull/9793#issuecomment-252951500) and [this](https://github.com/cockroachdb/cockroach/pull/9793#issuecomment-252087189)).

CC @RaduBerinde @andreimatei

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9916)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Review status: 0 of 8 files reviewed at latest revision, 9 unresolved discussions.

---

*[sql/distsql/evaluator.go, line 56 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9916#-KTtujWQ9WXdF8I3hX04:-KTtujWQ9WXdF8I3hX05:b-eesvp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/285388185ddf94c39b24e4fe0b3e623fb08a2c9e/sql/distsql/evaluator.go#L56)):*
> ```Go
> 	}
> 
> 	// Loop over the expressions in our expression set and extract out fully typed expressions, this
> ```

[nit] comments are usually wrapped at 80 cols

---

*[sql/distsql/evaluator.go, line 74 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9916#-KTty3CPRoVbYO3YckxH:-KTty3CPRoVbYO3YckxI:b1rxfb6) ([raw file](https://github.com/cockroachdb/cockroach/blob/285388185ddf94c39b24e4fe0b3e623fb08a2c9e/sql/distsql/evaluator.go#L74)):*
> ```Go
> 		defer wg.Done()
> 	}
> ```

should open a tracing span, see e.g. sorter.Run

---

*[sql/distsql/evaluator.go, line 101 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9916#-KTtxTfoBt1eZFYfcTyb:-KTtxTfoBt1eZFYfcTyc:b4hb15o) ([raw file](https://github.com/cockroachdb/cockroach/blob/285388185ddf94c39b24e4fe0b3e623fb08a2c9e/sql/distsql/evaluator.go#L101)):*
> ```Go
> 
> func (ev *evaluator) next() (sqlbase.EncDatumRow, error) {
> 	row, err := ev.input.NextRow()
> ```

[nit] more straightforward if we just do this directly inside Run, we're duplicating the end condition checks just to separate out a couple of lines

---

*[sql/distsql/evaluator.go, line 111 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9916#-KTtxFtnYrrMCTeJ_oEd:-KTtxFtnYrrMCTeJ_oEe:bb1lhor) ([raw file](https://github.com/cockroachdb/cockroach/blob/285388185ddf94c39b24e4fe0b3e623fb08a2c9e/sql/distsql/evaluator.go#L111)):*
> ```Go
> }
> 
> func (ev *evaluator) extract(row sqlbase.EncDatumRow) (sqlbase.EncDatumRow, error) {
> ```

s/extract/eval

---

*[sql/distsql/evaluator.go, line 112 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9916#-KTtwscZ8ASgLPDFc_UE:-KTtwscZ8ASgLPDFc_UF:bybebku) ([raw file](https://github.com/cockroachdb/cockroach/blob/285388185ddf94c39b24e4fe0b3e623fb08a2c9e/sql/distsql/evaluator.go#L112)):*
> ```Go
> 
> func (ev *evaluator) extract(row sqlbase.EncDatumRow) (sqlbase.EncDatumRow, error) {
> 	tuple := make(parser.DTuple, len(ev.exprs))
> ```

we should avoid allocating this for every row. we could allocate it once and reuse it. Might be easier to just do everything directly inside `Run`.

---

*[sql/distsql/expr.go, line 153 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9916#-KTtwQQT44Vw0U1_H12l:-KTtwQQT44Vw0U1_H12m:bb1lhor) ([raw file](https://github.com/cockroachdb/cockroach/blob/285388185ddf94c39b24e4fe0b3e623fb08a2c9e/sql/distsql/expr.go#L153)):*
> ```Go
> //  '$0' would return '1'
> //  '$1 + 10' would return '12'
> func (eh *exprHelper) extract(row sqlbase.EncDatumRow) (parser.Datum, error) {
> ```

s/extract/eval

---

*[sql/distsql/expr.go, line 156 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9916#-KTtvoEuq-iilwVH5_s1:-KTtvoEuq-iilwVH5_s2:b-i1x9l7) ([raw file](https://github.com/cockroachdb/cockroach/blob/285388185ddf94c39b24e4fe0b3e623fb08a2c9e/sql/distsql/expr.go#L156)):*
> ```Go
> 	eh.row = row
> 
> 	//  TODO(irfansharif): extract here is very permissive, if expr is of type *parser.FuncExpr for
> ```

[nit] wrap at 80

---

*[sql/distsql/expr.go, line 166 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9916#-KTtw0EkCgfAGtpUkZiu:-KTtw0EkCgfAGtpUkZiv:bpiujzw) ([raw file](https://github.com/cockroachdb/cockroach/blob/285388185ddf94c39b24e4fe0b3e623fb08a2c9e/sql/distsql/expr.go#L166)):*
> ```Go
> 	//  NullIfExpr.
> 	//
> 	//  TODO(irfansharif): We need to determine when exactly the 'argument extraction' takes place,
> ```

This is not something this processor (or any part of the physical plan) should be worried about. It's up to the code that will build logica and physical plans to extract expressions from aggregate and configure the processors with the correct expressions.

---

*[sql/sqlbase/encoded_datum.go, line 240 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9916#-KTtx3KUlaJJGy7BwzeP:-KTtx3KUlaJJGy7BwzeQ:b-vni8l4) ([raw file](https://github.com/cockroachdb/cockroach/blob/285388185ddf94c39b24e4fe0b3e623fb08a2c9e/sql/sqlbase/encoded_datum.go#L240)):*
> ```Go
> 
> func DTupleToEncDatumRow(tuple parser.DTuple) (EncDatumRow, error) {
> 	row := make(EncDatumRow, len(tuple))
> ```

We should use a `EncDatumRowAlloc`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9916)*

**Comment by irfansharif** [comment]
Review status: 0 of 8 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[sql/distsql/evaluator.go, line 56 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9916#-KTtujWQ9WXdF8I3hX04:-KTu-AHb-ukCzmXBM1KR:bo9bs10) ([raw file](https://github.com/cockroachdb/cockroach/blob/285388185ddf94c39b24e4fe0b3e623fb08a2c9e/sql/distsql/evaluator.go#L56)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> [nit] comments are usually wrapped at 80 cols
</details>
ah, messed up my editor configs. Done.

---

*[sql/distsql/evaluator.go, line 74 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9916#-KTty3CPRoVbYO3YckxH:-KTu06sKXP3viH5wUOLe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/285388185ddf94c39b24e4fe0b3e623fb08a2c9e/sql/distsql/evaluator.go#L74)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> should open a tracing span, see e.g. sorter.Run
</details>
Done.

---

*[sql/distsql/evaluator.go, line 101 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9916#-KTtxTfoBt1eZFYfcTyb:-KTu6X37MVd6n0EU_F14:bba2h23) ([raw file](https://github.com/cockroachdb/cockroach/blob/285388185ddf94c39b24e4fe0b3e623fb08a2c9e/sql/distsql/evaluator.go#L101)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> [nit] more straightforward if we just do this directly inside Run, we're duplicating the end condition checks just to separate out a couple of lines
</details>
agreed, done.

---

*[sql/distsql/evaluator.go, line 111 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9916#-KTtxFtnYrrMCTeJ_oEd:-KTu0SKagBB_v2e48AND:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/285388185ddf94c39b24e4fe0b3e623fb08a2c9e/sql/distsql/evaluator.go#L111)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> s/extract/eval
</details>
Done.

---

*[sql/distsql/evaluator.go, line 112 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9916#-KTtwscZ8ASgLPDFc_UE:-KTu6bxqtaC5_OeODxmq:b-zi0ktr) ([raw file](https://github.com/cockroachdb/cockroach/blob/285388185ddf94c39b24e4fe0b3e623fb08a2c9e/sql/distsql/evaluator.go#L112)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> we should avoid allocating this for every row. we could allocate it once and reuse it. Might be easier to just do everything directly inside `Run`.
</details>
I've still kept this `extract/eval` separately but changed so as to not reallocate per row. no strong opinions here, will pull it into `Run` if you still don't feel it adds to much clarity.

---

*[sql/distsql/expr.go, line 153 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9916#-KTtwQQT44Vw0U1_H12l:-KTu0WOWevv93ZW5xaKC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/285388185ddf94c39b24e4fe0b3e623fb08a2c9e/sql/distsql/expr.go#L153)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> s/extract/eval
</details>
Done.

---

*[sql/distsql/expr.go, line 156 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9916#-KTtvoEuq-iilwVH5_s1:-KTu-IHHLLVjh4Jgi5mj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/285388185ddf94c39b24e4fe0b3e623fb08a2c9e/sql/distsql/expr.go#L156)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> [nit] wrap at 80
</details>
Done.

---

*[sql/distsql/expr.go, line 166 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9916#-KTtw0EkCgfAGtpUkZiu:-KTu0blVdKP4HL11Fmtv:b-nv9xq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/285388185ddf94c39b24e4fe0b3e623fb08a2c9e/sql/distsql/expr.go#L166)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> This is not something this processor (or any part of the physical plan) should be worried about. It's up to the code that will build logica and physical plans to extract expressions from aggregate and configure the processors with the correct expressions.
</details>
Cool, wasn't sure if it would come here or outside when setting up the flow. thanks for clarifying.

---

*[sql/sqlbase/encoded_datum.go, line 240 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9916#-KTtx3KUlaJJGy7BwzeP:-KTu4BVsTX-6ATuxa-IG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/285388185ddf94c39b24e4fe0b3e623fb08a2c9e/sql/sqlbase/encoded_datum.go#L240)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> We should use a `EncDatumRowAlloc`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9916)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/distsql/evaluator.go, line 81 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9916#-KTuA2Q9UDmyDpCeOn7l:-KTuA2QAndcQxhmhS4mL:b-lhb7ao) ([raw file](https://github.com/cockroachdb/cockroach/blob/20d2465b11c6232a4ed5a738686617aad3e441c4/sql/distsql/evaluator.go#L81)):*
> ```Go
> 	}
> 
> 	ctx, span := tracing.ChildSpan(ev.ctx, "sorter")
> ```

"evaluator"

---

*[sql/sqlbase/encoded_datum.go, line 230 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9916#-KTuAl36IvSAl0qzKseh:-KTuAl36IvSAl0qzKsei:b-prepyi) ([raw file](https://github.com/cockroachdb/cockroach/blob/20d2465b11c6232a4ed5a738686617aad3e441c4/sql/sqlbase/encoded_datum.go#L230)):*
> ```Go
> func DatumToEncDatum(datum parser.Datum) (EncDatum, error) {
> 	if dType, ok := ColumnType_Kind_value[strings.ToUpper(datum.Type())]; !ok {
> 		return EncDatum{}, errors.Errorf("Unknown type, could not convert to EncDatum")
> ```

Include the type in the error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9916#-:-KTuAuPG0Z8ps-k1BAII:bnfp4nl)*

**Comment by irfansharif** [comment]
TFTR! pulling this in now.

---

Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsql/evaluator.go, line 81 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9916#-KTuA2Q9UDmyDpCeOn7l:-KTuRVhAi2q6dU58dpw8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/20d2465b11c6232a4ed5a738686617aad3e441c4/pkg/sql/distsql/evaluator.go#L81)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> "evaluator"
</details>
Done.

---

*[sql/sqlbase/encoded_datum.go, line 230 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9916#-KTuAl36IvSAl0qzKseh:-KTuRXR7SIU6qqxaLOUw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/20d2465b11c6232a4ed5a738686617aad3e441c4/sql/sqlbase/encoded_datum.go#L230)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Include the type in the error.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9916#-:-KTuRYzkmA5WP4nnNjXg:be8xcnc)*

**Pull request merged**
