### PR TITLE
[wip] kvserver: online recovery for unavailable ranges

### PR DESCRIPTION
**Pull request by tbg**
TODO

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
What's the vision for doing this on a 19.2 cluster without adding a new node? Or is the vision to briefly add a node which serves this RPC?

> Reviewed 5 of 5 files at r1, 3 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50268#-:-M9xQAYs8qF1pLTEEz_7:b5bmxgq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @bdarnell)

___
*[pkg/server/node.go, line 973 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50268#-M9xQdQ481SdHlRMCi7C:-M9xQdQ481SdHlRMCi7D:b-rvlxla) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b8a6b33e62a415721e4e7f0b3a92c263a84b171/pkg/server/node.go#L973)):*
> ```Go
> 	// TODO(tbg): should translate storeID -> nodeID or at least validate that
> 	// they fit together.
> 	// TODO(tbg): write the meta descriptor last
> ```

Why write the meta descriptor last? 

Are there other sanity checks we should do like ensure that the range descriptor as it is only contains dead nodes?

**Review by bdarnell — COMMENTED** [review]
I had envisioned the client command sending the raft snapshot directly. Is it necessary to introduce a server-side RPC to send the snapshot? 

> Reviewed 3 of 5 files at r1, 13 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50268#-:-M9xV8qb1AT_Fe8Jn0FE:b-jk7324)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/cli/debug_unsafe_missing_range.go, line 51 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50268#-M9xVir41g8qfVuc7VwA:-M9xVir59UHTPufG2RWH:b-4bs124) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b8a6b33e62a415721e4e7f0b3a92c263a84b171/pkg/cli/debug_unsafe_missing_range.go#L51)):*
> ```Go
> 	}
> 
> 	sNodeID := args[1]
> ```

The node and store ID used here don't matter at all, right? (it just has to be a live node) Maybe they don't need to be arguments and we just use the NodeID/StoreID of the node we connect to (this needs a `--host` argument, right?)
___
*[pkg/server/node.go, line 973 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50268#-M9xQdQ481SdHlRMCi7C:-M9xUo6E7TODkFpWrX3p:ba17df3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b8a6b33e62a415721e4e7f0b3a92c263a84b171/pkg/server/node.go#L973)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Why write the meta descriptor last? 

Are there other sanity checks we should do like ensure that the range descriptor as it is only contains dead nodes?
</blockquote></details>

Do we need to write the meta descriptor at all? In `unsafe-remove-dead-replicas` we don't touch it, and it will get updated and overwritten when upreplication happens on its own.

**Review by tbg — COMMENTED** [review]
> Is it necessary to introduce a server-side RPC to send the snapshot?

I started off that way but in the interested of validating the approach quickly moved it to an endpoint. I will see if there's any reason to not do this in the client.

> What's the vision for doing this on a 19.2 cluster without adding a new node? Or is the vision to briefly add a node which serves this RPC?

Hopefully we can just use the cli! But if we're extra cautious we would possibly want to add a new node to the cluster, configure it so that it doesn't receive any replicas (however we would achieve this is open) and create the new replica on that node, to guard against fallout from it crashing as a result. I will see if the `cli` approach works first before I think about this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50268#-:-M9y-yRG8zmPA63te0l7:b1s79bk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell)

___
*[pkg/cli/debug_unsafe_missing_range.go, line 51 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50268#-M9xVir41g8qfVuc7VwA:-MA1PwkM-TjogVXTa7fh:b-v8mntx) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b8a6b33e62a415721e4e7f0b3a92c263a84b171/pkg/cli/debug_unsafe_missing_range.go#L51)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

The node and store ID used here don't matter at all, right? (it just has to be a live node) Maybe they don't need to be arguments and we just use the NodeID/StoreID of the node we connect to (this needs a `--host` argument, right?)
</blockquote></details>

Yes, I can use SQL:

```go
SELECT
	node_id, store_id
FROM
	crdb_internal.node_build_info
	JOIN crdb_internal.kv_store_status USING (node_id)
WHERE
	field = 'Version';
```
___
*[pkg/server/node.go, line 973 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50268#-M9xQdQ481SdHlRMCi7C:-MA1Q_L79bIrWjWxtGjj:b-jknl27) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b8a6b33e62a415721e4e7f0b3a92c263a84b171/pkg/server/node.go#L973)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Do we need to write the meta descriptor at all? In `unsafe-remove-dead-replicas` we don't touch it, and it will get updated and overwritten when upreplication happens on its own. 
</blockquote></details>

We are minting a replica that is not in the descriptor, so that replica is automatically replicaGC'able. If it decided to replicaGC itself, and it is the sole remaining replica, that seems wise to avoid. Naively at worst it brings us back to the same state, but I don't want to risk it tickling any assertions along the way. So - update the descriptor.

But the comment here is bogus, we should be doing it first for the reason just mentioned. I think I was thinking about sanity checks here.

**Review by tbg — COMMENTED** [review]
It's quite painful to set up the KV parts of this in cli. It's fine to send the snapshot, but I have a hard time getting the descriptor since that requires me to first find the end key of the range (via SQL), then find the replicas of the meta2 range containing the descriptor, and only then can I hope to send requests at them. This is so complicated because I don't have a DistSender that would do the routing for me.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50268#-:-MA1T7fm0BWAngPXdJJM:brlb4z5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell)

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50268)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell)

___
*[pkg/server/node.go, line 973 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50268#-M9xQdQ481SdHlRMCi7C:-MA2IWHvB8ZNIRA0Ix9F:b35gkij) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b8a6b33e62a415721e4e7f0b3a92c263a84b171/pkg/server/node.go#L973)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

We are minting a replica that is not in the descriptor, so that replica is automatically replicaGC'able. If it decided to replicaGC itself, and it is the sole remaining replica, that seems wise to avoid. Naively at worst it brings us back to the same state, but I don't want to risk it tickling any assertions along the way. So - update the descriptor.

But the comment here is bogus, we should be doing it first for the reason just mentioned. I think I was thinking about sanity checks here.
</blockquote></details>

Yeah, without updating meta2 to hold the replica in place we're racing the replica GC queue against the replication queue. But maybe that's OK since you can just retry? I feel a little more nervous about updating meta2 in this transaction than creating the replica with a descriptor that's different from meta2. (and if we don't update meta2, the CLI-side implementation is a lot easier, right?)

**Review by tbg — COMMENTED** [review]
I'm giving up on forcing this cli-side. I realized that we *need* to rewrite the meta2 descriptor because that is what we use to look up the replicas. Without it, the newly minted replica is in effect unable to talk to itself because it will go through DistSender and get stuck on the range lookup.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50268#-:-MA5W1_UDIF5E5oJBbET:b-iue17i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell)

___
*[pkg/server/node.go, line 973 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50268#-M9xQdQ481SdHlRMCi7C:-MA5WKOU2jPEqwfjYQhM:brpqmho) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b8a6b33e62a415721e4e7f0b3a92c263a84b171/pkg/server/node.go#L973)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Yeah, without updating meta2 to hold the replica in place we're racing the replica GC queue against the replication queue. But maybe that's OK since you can just retry? I feel a little more nervous about updating meta2 in this transaction than creating the replica with a descriptor that's different from meta2. (and if we don't update meta2, the CLI-side implementation is a lot easier, right?)
</blockquote></details>

See main thread for the problem with not updating meta2.

**Comment by tbg** [comment]
I ported this PR over to 19.2: https://github.com/cockroachdb/cockroach/pull/50387
This was mildly annoying due to package renames, but otherwise seems to have gone through smoothly. I added the roachtest to the acceptance suite to make sure it runs in CI.

**Review by bdarnell — APPROVED** [review]
> Reviewed 1 of 14 files at r3, 1 of 1 files at r4, 13 of 13 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50268)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/roachpb/api.proto, line 2073 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50268#-MA7P1f70WDa_QbSnLNx:-MA7P1f70WDa_QbSnLNy:b89j8r2) ([raw file](https://github.com/cockroachdb/cockroach/blob/13eae38ca2a281c3e8ea5b9c5a98db549c488095/pkg/roachpb/api.proto#L2073)):*
> ```protobuf
>   rpc RangeFeed (RangeFeedRequest) returns (stream RangeFeedEvent) {}
> 
>   rpc UnsafeHealRange (UnsafeHealRangeRequest) returns (UnsafeHealRangeResponse) {}
> ```

I don't love putting this on the same service as our "real" Batch and RangeFeed interfaces. But I'm not sure it's worth moving it elsewhere. 

Please make sure it requires an admin client certificate. 
___
*[pkg/server/node.go, line 971 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50268#-MA7Pq5b0rMvSX3UjAv7:-MA7Pq5cAXXPo9EfJS1U:b-vgvubo) ([raw file](https://github.com/cockroachdb/cockroach/blob/13eae38ca2a281c3e8ea5b9c5a98db549c488095/pkg/server/node.go#L971)):*
> ```Go
> 	ctx context.Context, req *roachpb.UnsafeHealRangeRequest,
> ) (_ *roachpb.UnsafeHealRangeResponse, rErr error) {
> 	// TODO(tbg): should translate storeID -> nodeID or at least validate that
> ```

These comments are obsolete now, right?
___
*[pkg/server/node.go, line 974 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50268#-MA7Q-Y_4eePrh-fd1my:-MA7Q-Y_4eePrh-fd1mz:biu1uoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/13eae38ca2a281c3e8ea5b9c5a98db549c488095/pkg/server/node.go#L974)):*
> ```Go
> 	// they fit together.
> 	// TODO(tbg): write the meta descriptor last
> 	defer func() {
> ```

This is not something we generally do; I don't really like ad-hoc sprinkling of panic-to-error transformations like this. 
___
*[pkg/server/node.go, line 1017 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50268#-MA7QCr4-mCctTzGsSRq:-MA7QCr4-mCctTzGsSRr:brjsik8) ([raw file](https://github.com/cockroachdb/cockroach/blob/13eae38ca2a281c3e8ea5b9c5a98db549c488095/pkg/server/node.go#L1017)):*
> ```Go
> 	storeID, nodeID := s.Ident.StoreID, s.Ident.NodeID
> 
> 	dead := append([]roachpb.ReplicaDescriptor(nil), desc.Replicas().All()...)
> ```

Add a TODO to verify that all these replicas are actually dead/decommissioned.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50268)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @tbg)

___
*[pkg/roachpb/api.proto, line 2073 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50268#-MA7P1f70WDa_QbSnLNx:-MAAZ_R1Dmeamb7rTgY-:bddg002) ([raw file](https://github.com/cockroachdb/cockroach/blob/13eae38ca2a281c3e8ea5b9c5a98db549c488095/pkg/roachpb/api.proto#L2073)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I don't love putting this on the same service as our "real" Batch and RangeFeed interfaces. But I'm not sure it's worth moving it elsewhere. 

Please make sure it requires an admin client certificate. 
</blockquote></details>

I don't either, but something I should've mentioned is that I wasn't actually planning on merging this. Do you feel strongly that I should? As far as I'm concerned we'll build the custom binary from the branch after it's clear that it "works" (I will port this commit on the exact SHA customer is using right now)
___
*[pkg/server/node.go, line 971 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50268#-MA7Pq5b0rMvSX3UjAv7:-MAAZtG53XZ_NYARkvCu:b2nhswy) ([raw file](https://github.com/cockroachdb/cockroach/blob/13eae38ca2a281c3e8ea5b9c5a98db549c488095/pkg/server/node.go#L971)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

These comments are obsolete now, right?
</blockquote></details>

Yes
___
*[pkg/server/node.go, line 974 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50268#-MA7Q-Y_4eePrh-fd1my:-MAAZtyG-sf4Sx4_zdFV:brgemcx) ([raw file](https://github.com/cockroachdb/cockroach/blob/13eae38ca2a281c3e8ea5b9c5a98db549c488095/pkg/server/node.go#L974)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This is not something we generally do; I don't really like ad-hoc sprinkling of panic-to-error transformations like this. 
</blockquote></details>

This wasn't supposed to be checked in - I was chasing down some error where the CRDB process would call `os.Exit(2)` somewhere (I never found it, but believe it's somewhere in proto marshaling, based on hazy memory)

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50268)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @tbg)

___
*[pkg/server/node.go, line 971 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50268#-MA7Pq5b0rMvSX3UjAv7:-MAA_7Tx4Mz4pDVpmCWC:b-e2nkpw) ([raw file](https://github.com/cockroachdb/cockroach/blob/13eae38ca2a281c3e8ea5b9c5a98db549c488095/pkg/server/node.go#L971)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Yes
</blockquote></details>

(Note that the up-to-date version, in a sense, is the one on 19.2)

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50268)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @tbg)

___
*[pkg/roachpb/api.proto, line 2073 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50268#-MA7P1f70WDa_QbSnLNx:-MAS-Acx5YjYL1wwHIqY:b-5l4zmn) ([raw file](https://github.com/cockroachdb/cockroach/blob/13eae38ca2a281c3e8ea5b9c5a98db549c488095/pkg/roachpb/api.proto#L2073)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I don't either, but something I should've mentioned is that I wasn't actually planning on merging this. Do you feel strongly that I should? As far as I'm concerned we'll build the custom binary from the branch after it's clear that it "works" (I will port this commit on the exact SHA customer is using right now)
</blockquote></details>

Experience with the existing `unsafe-remove-dead-replicas` tool suggests that it's never just a one-off, and we'll need to use this again some day. I think it's worth committing this code at least to the master branch.

**Pull request closed without merging**
