### PR TITLE
roachprod: retry dns lookup on network failures

### LINKED ISSUE #110884: roachprod: DNS infra flakes
Infra flake related issues have started to present after DNS services were introduced to `roachprod`.
Intermittent network problems causes the DNS lookup to fail and will appear in the logs as a "lookup" error.

These intermittent network problems should preferably not cause a `roachtest` to fail and there should at least be a few retries in the event of network flakiness.

### PR DESCRIPTION
**Pull request by herkolategan**
Previously we had failures in net.LookupSRV that appear to be network flakes. It would be preferable to not fail a whole roachtest on a single DNS network flake. This change wraps a retry around the dns lookup in order to prevent flakiness and have a chance of recovery.

Fixes: https://github.com/cockroachdb/cockroach/issues/110884

Epic: None
Release Note: None

### CODE REVIEW

**Comment by renatolabs** [comment]
Should we unify `waitForRecordsAvailable` and `lookupSRVRecords`? Now the former will have a nested retry loop, making it a little difficult to reason about its behaviour.

Maybe the lookup function can always retry and the wait function can just be a loop around `lookup`.

**Review by herkolategan — COMMENTED** [review]
The `retry` in `waitForRecordsAvailable` is convenient, I'd like to keep it if possible to handle the errors (which could either result from a lookup error, or from waiting too long for all the records). But I agree it could result in some lengthy combinations, especially if there is a network outage. A compromise might be to pass the number of attempts with the other functions and for the wait function just a single attempt. It adds another parameter, but will ensure the above scenario doesn't happen.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110832#-:-Neggf9264DFmTfiocQm:bbdkr4a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @rachitgsrivastava, and @renatolabs)

**Review by renatolabs — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110832)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @herkolategan, and @rachitgsrivastava)

___
*[`pkg/roachprod/vm/gce/dns.go` line 258 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110832#-NehgAvr4VQU-GGpVg__:-NehgAvr4VQU-GGpVg_a:buzoflf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab93ac8e54740ba4d51cade765ae06879c0912dd/pkg/roachprod/vm/gce/dns.go#L258)):*
> ```Go
> 		for key := range notAvailable {
> 			// The number of lookup attempts is set to 1 here since this is already a retry loop.
> 			foundRecords, err := n.lookupSRVRecords(ctx, "", "", key.name, 1)
> ```

I agree that we should retry on `waitForRecordsAvailable`. IMO, the retry-on-retry behaviour is still more confusing than it could be. What if the only `retry` call happened on the lookup function, but that function also took retry options as parameter? Then we could inject the retry policy we want; I think it makes the code more understandable. But I'll leave that to your judgement.

**Review by herkolategan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110832)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @rachitgsrivastava, and @renatolabs)

___
*[`pkg/roachprod/vm/gce/dns.go` line 258 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110832#-NehgAvr4VQU-GGpVg__:-NehjfBECVNOoYzunqXz:b2xzuv2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab93ac8e54740ba4d51cade765ae06879c0912dd/pkg/roachprod/vm/gce/dns.go#L258)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

I agree that we should retry on `waitForRecordsAvailable`. IMO, the retry-on-retry behaviour is still more confusing than it could be. What if the only `retry` call happened on the lookup function, but that function also took retry options as parameter? Then we could inject the retry policy we want; I think it makes the code more understandable. But I'll leave that to your judgement.
</blockquote></details>

Good point, I think that will make more sense. Thanks.

**Comment by herkolategan** [comment]
bors r=renatolabs

**Pull request merged**
