### PR TITLE
ui: add connected components for insights

### LINKED ISSUE #87693: Insights page added to Cloud Dedicated
Once SQL over http is available on Cloud, the Insights page should be added to Cloud Dedicated

Jira issue: CRDB-19482

### PR DESCRIPTION
**Pull request by ericharmeling**
This commit adds connected components for the workload and schema insights pages, for use in the CC Console.

Fixes #87693.

https://www.loom.com/share/08163a7c125948119ca71ac097099a29

Release note: None

### CODE REVIEW

**Comment by ericharmeling** [comment]
FYI, the statement fingerprint details pages are returning an undefined error:

```
TypeError
Cannot read properties of undefined (reading 'apply')
```

**Review by maryliag — COMMENTED** [review]
when do you see this error? is just on the browser when you open the details page or it doesn't even load the page?

> Reviewed 35 of 37 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88419#-:-NCvqVLnEm13IZveInid:b-sptzfh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/store/sagas.ts` line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88419#-NCvpO8UDrRA2pn8bjT3:-NCvpO8UDrRA2pn8bjT4:b4btkl7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b05415f058d7321874defff7a24eaa417cb46bc5/pkg/ui/workspaces/cluster-ui/src/store/sagas.ts#L40)):*
> ```XML
>     fork(transactionInsightsSaga),
>     fork(transactionInsightDetailsSaga),
>     fork(statementInsightsSaga),
> ```

to confirm: there is no statementInsightsDetailsSaga because we don't do a call for the details here like we do on the transactions, right?

**Review by ericharmeling — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88419)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/store/sagas.ts` line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88419#-NCvpO8UDrRA2pn8bjT3:-NCz85MN7TGLGTAq5TwU:b-4p5pdp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b05415f058d7321874defff7a24eaa417cb46bc5/pkg/ui/workspaces/cluster-ui/src/store/sagas.ts#L40)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

to confirm: there is no statementInsightsDetailsSaga because we don't do a call for the details here like we do on the transactions, right?
</blockquote></details>

Yes! Exactly.

**Review by maryliag — APPROVED** [review]
With the error on the SQL Activity aside, the changes made here to make it available on CC Console Dedicated: :lgtm: 

> Reviewed 2 of 37 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88419#-:-NCzJKZT50wHlWuvtOu7:b-y1obe4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling)

**Review by ericharmeling — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88419#-:-NCzRjDjEmNQcWs2YxLK:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling)

**Comment by ericharmeling** [comment]
> FYI, the statement fingerprint details pages are returning an undefined error:
> 
> ```
> TypeError
> Cannot read properties of undefined (reading 'apply')
> ```
> 
> Loom: https://www.loom.com/share/09deb18b98044502a7f41320081f7c8e

Following up on this error:

It does not affect DB Console, and it does not occur in the commits before this PR.

To reproduce:

(from `cockroach`):
```
git checkout 15e83552f6d498a308897b85dbdf1424a4b52e9a
./dev build
./dev ui watch
```

(from `managed-service`):
```
git checkout master
./scripts/crl-vault-shell staging
make console-symlink-cluster-ui CLUSTER_UI_VERSION=22-2 GOPATH=$HOME/go CLUSTER_UI_PATH=~/go/src/github.com/cockroachdb/cockroach/_bazel/bin/pkg/ui/workspaces/cluster-ui
yarn --cwd console start:staging --env watch_cluster_ui
```

Navigate to localhost:8081 -> sql-obs-latest -> SQL Activity -> select any statement fingerprint

image

**Pull request merged**
