### PR TITLE
storage: on unquiesce, only bump lastUpdateTimes for replicating followers

### PR DESCRIPTION
**Pull request by tbg**
On a range that unquiesces every couple of seconds (not untypical),
followers always seem alive. Probing followers can block Raft log
truncation, so this is problematic.

This problem is arguably better fixed by rethinking the log truncation
heuristics, but this is a larger project.

Release note (bug fix): Prevent down nodes from obstructing log truncation
on ranges they are a member of. This problem could cause replication to
fail due to an overly large Raft log.

### CODE REVIEW

**Comment by tbg** [comment]
(This needs a test, but putting this out there)

We'll want this in 2.1.5.

**Review by petermattis — APPROVED** [review]
:lgtm: modulo the need for a test.

I changed my mind about a Raft log truncation tech-note. Describing all of the truncation heuristics would be useful. I had forgotten about this one around `RecentActive`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34712#-:-LY7TCYF3d8J58z5j3IC:bgp44y0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/storage/replica_raft_quiesce.go, line 82 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34712#-LY7StFvBT4OWkR9nPCR:-LY7StFvBT4OWkR9nPCS:buxls4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/42ddc847cd769dc5e318351172608ee798966d91/pkg/storage/replica_raft_quiesce.go#L82)):*
> ```Go
> 		}
> 		now := timeutil.Now()
> 		status := *r.raftStatusRLocked() // we know it's not nil because raftGroup isn't
> ```

You don't need to dereference it here. Does doing that buy you anything?

**Review by tbg — COMMENTED** [review]
Test added, PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34712#-:-LYBJQqK9CtwUYv6HGdQ:b-lvl424)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @petermattis)

___
*[pkg/storage/replica_raft_quiesce.go, line 82 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34712#-LY7StFvBT4OWkR9nPCR:-LYBJIdK5tjCmPOwxFev:befr7mo) ([raw file](https://github.com/cockroachdb/cockroach/blob/42ddc847cd769dc5e318351172608ee798966d91/pkg/storage/replica_raft_quiesce.go#L82)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

You don't need to dereference it here. Does doing that buy you anything?
</blockquote></details>

This has gone away. It also didn't buy me anything.

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34712)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tbg)

___
*[pkg/storage/replica_raft_quiesce.go, line 82 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34712#-LY7StFvBT4OWkR9nPCR:-LYCko5nCr4xJ9jjHSPT:b-pvmfqr) ([raw file](https://github.com/cockroachdb/cockroach/blob/42ddc847cd769dc5e318351172608ee798966d91/pkg/storage/replica_raft_quiesce.go#L82)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This has gone away. It also didn't buy me anything.
</blockquote></details>

This approach is cleaner (and more testable).  Nit: please wrap the line above to be less than 100 cols to make it easier to view in reviewable.

**Review by tbg — COMMENTED** [review]
TFTR!

bors r=petermattis

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34712#-:-LYCyqqA1PzQgwOLdJUT:b-spmsx3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @petermattis)

___
*[pkg/storage/replica_raft_quiesce.go, line 82 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34712#-LY7StFvBT4OWkR9nPCR:-LYCyqDd4yy1aBB1omnX:b-yzf98q) ([raw file](https://github.com/cockroachdb/cockroach/blob/42ddc847cd769dc5e318351172608ee798966d91/pkg/storage/replica_raft_quiesce.go#L82)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This approach is cleaner (and more testable).  Nit: please wrap the line above to be less than 100 cols to make it easier to view in reviewable.
</blockquote></details>

I went ahead and did this, but I feel a lot less strongly about it (also have never experienced this as a nuisance myself, not sure why). I hought we had decided that we'd either teach crlfmt these tricks or avoid the overhead of pointing them out in PRs. (I'm guilty of other kinds of nits that I have a hard time letting go).

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34712)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tbg)

___
*[pkg/storage/replica_raft_quiesce.go, line 82 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34712#-LY7StFvBT4OWkR9nPCR:-LYD5iyzBTYwLWICltCD:b-h4y4a6) ([raw file](https://github.com/cockroachdb/cockroach/blob/42ddc847cd769dc5e318351172608ee798966d91/pkg/storage/replica_raft_quiesce.go#L82)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I went ahead and did this, but I feel a lot less strongly about it (also have never experienced this as a nuisance myself, not sure why). I hought we had decided that we'd either teach crlfmt these tricks or avoid the overhead of pointing them out in PRs. (I'm guilty of other kinds of nits that I have a hard time letting go).
</blockquote></details>

Thank you. The line wrapping in reviewable isn't hard for you to read? Am I alone in being deficient in this area?

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34712)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @petermattis)

___
*[pkg/storage/replica_raft_quiesce.go, line 82 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34712#-LY7StFvBT4OWkR9nPCR:-LYRGUvBC_FXgfF584LC:b-5pf47k) ([raw file](https://github.com/cockroachdb/cockroach/blob/42ddc847cd769dc5e318351172608ee798966d91/pkg/storage/replica_raft_quiesce.go#L82)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Thank you. The line wrapping in reviewable isn't hard for you to read? Am I alone in being deficient in this area?
</blockquote></details>

I'll pay more attention to it, but I don't remember it ever having bothered me. Maybe I just never run into long lines into reviews.

**Pull request merged**
