### PR TITLE
sql: TRUNCATE table as soon as possible

### PR DESCRIPTION
**Pull request by vivekmenezes**
I'll add some more tests shortly. Probably should also consolidate some code between this change and restore. Let's get the DROP change merged first.

### CODE REVIEW

**Comment by dt** [comment]
Reviewed 1 of 1 files at r1, 6 of 6 files at r2.
Review status: 5 of 10 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/truncate.go, line 102 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17045#-KpGr5SPpronWyoj4cg1:-KpGr5SPpronWyoj4cg2:b-md3rbc) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c57d6dc19ce57f0a9bfc60d1d61c7214b9cebc7/pkg/sql/truncate.go#L102)):*
> ```Go
> 	// TODO(knz): move truncate logic to Start/Next so it can be used with SHOW TRACE FOR.
> 	traceKV := p.session.Tracing.KVTracingEnabled()
> 	for id, _ := range toTruncate {
> ```

nit: `for id := range`

---

*[pkg/sql/truncate.go, line 154 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17045#-KpGsR_c0C6tK8nRrhWi:-KpGsR_c0C6tK8nRrhWj:b-9fqcld) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c57d6dc19ce57f0a9bfc60d1d61c7214b9cebc7/pkg/sql/truncate.go#L154)):*
> ```Go
> 		return err
> 	}
> 	assignment := make(map[sqlbase.ID]sqlbase.ID)
> ```

imo, i think this would be clearer, and cheaper, as a literal arg?

---

*[pkg/sql/truncate.go, line 164 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17045#-KpGt3JLThB3sPFxGzhI:-KpGt3JLThB3sPFxGzhJ:b-11ojum) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c57d6dc19ce57f0a9bfc60d1d61c7214b9cebc7/pkg/sql/truncate.go#L164)):*
> ```Go
> 			return err
> 		}
> 		if err := p.writeTableDesc(ctx, table); err != nil {
> ```

Hmm, I think we also need to wait for these updated backwards references before we can allow writes on the the new table? 

---

*[pkg/sql/truncate.go, line 251 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17045#-KpGroQimQT1kYwWl_bD:-KpGroQimQT1kYwWl_bE:b-jcq12t) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c57d6dc19ce57f0a9bfc60d1d61c7214b9cebc7/pkg/sql/truncate.go#L251)):*
> ```Go
> }
> 
> // reassign all the references from all the tables that match those in newTableIDs.
> ```

this is pretty similar to the code in restore.go -- ideally I'd prefer to move it to structured.go and then share it here and in restore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17045)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/truncate.go, line 102 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17045#-KpGr5SPpronWyoj4cg1:-KpGzlVHOF7pK0ugFGFG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c57d6dc19ce57f0a9bfc60d1d61c7214b9cebc7/pkg/sql/truncate.go#L102)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

nit: `for id := range`
</blockquote></details>

Done.

---

*[pkg/sql/truncate.go, line 154 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17045#-KpGsR_c0C6tK8nRrhWi:-KpGwgdiGTwbW0j8lCym:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c57d6dc19ce57f0a9bfc60d1d61c7214b9cebc7/pkg/sql/truncate.go#L154)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

imo, i think this would be clearer, and cheaper, as a literal arg?
</blockquote></details>

Done.

---

*[pkg/sql/truncate.go, line 164 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17045#-KpGt3JLThB3sPFxGzhI:-KpGwlvq0nUjtJPKHFgI:b-w216ve) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c57d6dc19ce57f0a9bfc60d1d61c7214b9cebc7/pkg/sql/truncate.go#L164)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Hmm, I think we also need to wait for these updated backwards references before we can allow writes on the the new table? 
</blockquote></details>

Good point! I've added some code to put the new  table descriptor in the ADD state so that it waits until these tables are live. I've added two tests to clarify what the states of the table are and check that they indeed get into that state.

---

*[pkg/sql/truncate.go, line 251 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17045#-KpGroQimQT1kYwWl_bD:-KpGyLcxYJnGgHOjmqCi:b-q3cqun) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c57d6dc19ce57f0a9bfc60d1d61c7214b9cebc7/pkg/sql/truncate.go#L251)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

this is pretty similar to the code in restore.go -- ideally I'd prefer to move it to structured.go and then share it here and in restore.
</blockquote></details>

I'd like to do that but it does look like restore has more requirements on the function returning errors when certain requirements are not met.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17045)*

**Comment by vivekmenezes** [comment]
Is this good to merge?

**Comment by vivekmenezes** [comment]
@dt I've rebased this PR. Do let me know if there is anything else I need to do?

**Review by dt — APPROVED** [review]
Nice!

(Sorry about that slow review)

**Pull request merged**
