### PR TITLE
sql: permit forward indexes on arrays

### LINKED ISSUE #17154: sql: allow ARRAYs in forward indexes
Arrays support inverted indexes, but not forward indexes. If you want to index arrays, starting in CockroachDB 20.1 consider using an inverted index on your column.

This issue tracks adding forward indexes to array types.

Jira issue: CRDB-6049

### PR DESCRIPTION
**Pull request by jordanlewis**
Closes #17154

This functionality has been unlocked since we added trigram indexes - the blocker before was the ability to support both forward and inverted indexes on a given type.

This commit simply permits forward indexes on arrays, where they were previously not supported at all.

Release note (sql change): enable forward indexes on arrays

### CODE REVIEW

**Comment by jordanlewis** [comment]
This needs to take into account enum values in partitioning columns: https://github.com/cockroachdb/cockroach/issues/17154#issuecomment-1312081934

**Comment by ajwerner** [comment]
One reasonable way to sidestep the array enums would be to disallow partitioning by arrays altogether. It's not clear to me that the partitioning code knows how to think about arrays. We'd want to add testing to cover both the simpler case of primitive arrays and then the more complex case of udts in arrays.

**Review by michae2 — COMMENTED** [review]
Cool!

Would be nice to have some test cases in `pkg/sql/logictest/testdata/logic_test/distsql_stats` creating stats on an indexed array column. Maybe a case where there is both a forward and an inverted index on the same array column.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91762#-:-NGc6myGEN4WvAc59BYG:b-kho4wy)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by jordanlewis** [comment]
TFTR! Added a bunch of tests.

There's a bit of an annoying problem: the index recommendation engine doesn't properly handle types that are both inverted and forward indexable.

In particular, if a type is forward indexable, an inverted index will never be recommended even if it's possible and optimal to create one.

For now, I'm going to propose that we accept the regression (array inverted indexes will no longer be recommended). We already do not recommend trigram inverted indexes for this same reason.

I'll open an issue to track solving this problem. It's a little bit annoying and will require some light refactoring of the index recommender, which currently uses data structures that do not permit adding the required extra bit (inverted or not) without changing the datatype (which is used in a bunch of different places).

**Comment by jordanlewis** [comment]
Also, I added a commit that disables partitioning tables and indexes by array columns to avoid the problem that @ajwerner was talking about.

PTAL.

**Review by michae2 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 5 files at r2, 8 of 8 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91762#-:-NH0xz5F7AsKf9qw0IJ1:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[`pkg/sql/randgen/schema.go` line 572 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91762#-NH0XocV8B_orbl412tD:-NH0XocV8B_orbl412tE:b-1w78fi) ([raw file](https://github.com/cockroachdb/cockroach/blob/519fb8a7f0ea3cb9509b409c9c997ec3556a77fd/pkg/sql/randgen/schema.go#L572)):*
> ```Go
> 	// TODO(harding): Allow partitioning the primary index. This will require
> 	// massaging the syntax.
> 	if !isMultiRegion && !isPrimaryIndex && !partitioningNotSupported && len(prefix) > 0 && rng.Intn(10) == 0 {
> ```

Thank you for preemptively fixing randgen!
___
*[`pkg/sql/logictest/testdata/logic_test/alter_table` line 2674 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/91762#-NH0YX6b9ICyZGCMN4n5:-NH0YX6b9ICyZGCMN4n6:bu11s4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/40329420b0a4b57b369ef9b5dc7c702ff09a08fe/pkg/sql/logictest/testdata/logic_test/alter_table#L2674)):*
> ```
> 
> statement ok
> CREATE TABLE t1_non_indexable (n INT8);
> ```

nit: the name "t1_non_indexable" doesn't make sense any more :slightly_smiling_face: maybe "t1_indexable"?
___
*[`pkg/sql/logictest/testdata/logic_test/array` line 1461 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/91762#-NH0_8gx0GDY1KoVO-vs:-NH0_8gx0GDY1KoVO-vt:bti35nu) ([raw file](https://github.com/cockroachdb/cockroach/blob/40329420b0a4b57b369ef9b5dc7c702ff09a08fe/pkg/sql/logictest/testdata/logic_test/array#L1461)):*
> ```
> CREATE INDEX i ON t(x DESC)
> 
> # Add "t@i" index annotation once #50659 is fixed.
> ```

nit: We should get rid of this todo (and probably do it, right? I guess we do this below, so maybe it's not necessary here).
___
*[`pkg/sql/logictest/testdata/logic_test/array` line 1469 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/91762#-NH0_GkZ3RsYYKTroPKn:-NH0_GkZ3RsYYKTroPKo:b-pzuqdz) ([raw file](https://github.com/cockroachdb/cockroach/blob/40329420b0a4b57b369ef9b5dc7c702ff09a08fe/pkg/sql/logictest/testdata/logic_test/array#L1469)):*
> ```
> {NULL}
> 
> # Add "t@i" index annotation once #50659 is fixed.
> ```

This one as well.
___
*[`pkg/sql/logictest/testdata/logic_test/distsql_stats` line 1946 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/91762#-NH0kKLGEGR6OajmDwJy:-NH0kKLGEGR6OajmDwJz:bandihx) ([raw file](https://github.com/cockroachdb/cockroach/blob/40329420b0a4b57b369ef9b5dc7c702ff09a08fe/pkg/sql/logictest/testdata/logic_test/distsql_stats#L1946)):*
> ```
> ORDER BY statistics_name, column_names::STRING
> ----
> NULL  {a}      10000  true
> ```

Should there be two rows for {a} here, one with the forward histogram and one with the inverted histogram?

Hmm, now that I'm trying this with strings it looks like we only get the forward histogram when both indexes exist. I remember in https://github.com/cockroachdb/cockroach/pull/84927 you fixed statistics_builder to handle coexistence of both types of histogram, so I assumed `ANALYZE` would create both, but maybe that's not the case?

Well, this doesn't seem like a blocker anyway. We can fix this in another PR.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91762)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2)

___
*[`pkg/sql/randgen/schema.go` line 572 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91762#-NH0XocV8B_orbl412tD:-NH32VU59O5Wfa9v4giC:bt8egcf) ([raw file](https://github.com/cockroachdb/cockroach/blob/519fb8a7f0ea3cb9509b409c9c997ec3556a77fd/pkg/sql/randgen/schema.go#L572)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Thank you for preemptively fixing randgen!
</blockquote></details>

Thankfully, this was actually caught by some randgen tests! No way I would have remembered otherwise.
___
*[`pkg/sql/logictest/testdata/logic_test/alter_table` line 2674 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/91762#-NH0YX6b9ICyZGCMN4n5:-NH31FUL-ZQZQm3K7LHN:bt2vr0y) ([raw file](https://github.com/cockroachdb/cockroach/blob/40329420b0a4b57b369ef9b5dc7c702ff09a08fe/pkg/sql/logictest/testdata/logic_test/alter_table#L2674)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: the name "t1_non_indexable" doesn't make sense any more :slightly_smiling_face: maybe "t1_indexable"?
</blockquote></details>

Fixed!
___
*[`pkg/sql/logictest/testdata/logic_test/array` line 1461 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/91762#-NH0_8gx0GDY1KoVO-vs:-NH31hlM255Y04apy57D:bakh85v) ([raw file](https://github.com/cockroachdb/cockroach/blob/40329420b0a4b57b369ef9b5dc7c702ff09a08fe/pkg/sql/logictest/testdata/logic_test/array#L1461)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: We should get rid of this todo (and probably do it, right? I guess we do this below, so maybe it's not necessary here).
</blockquote></details>

Thanks for noticing this. Removed the TODOs and added the hints. I guess it's a bit redundant but these also test range scans a little bit so I'll leave these cases.
___
*[`pkg/sql/logictest/testdata/logic_test/array` line 1469 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/91762#-NH0_GkZ3RsYYKTroPKn:-NH31iI1CJcLY3O_QskU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/40329420b0a4b57b369ef9b5dc7c702ff09a08fe/pkg/sql/logictest/testdata/logic_test/array#L1469)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

This one as well.
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/distsql_stats` line 1946 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/91762#-NH0kKLGEGR6OajmDwJy:-NH31w8r027FCLpX273Q:b-460vn3) ([raw file](https://github.com/cockroachdb/cockroach/blob/40329420b0a4b57b369ef9b5dc7c702ff09a08fe/pkg/sql/logictest/testdata/logic_test/distsql_stats#L1946)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Should there be two rows for {a} here, one with the forward histogram and one with the inverted histogram?

Hmm, now that I'm trying this with strings it looks like we only get the forward histogram when both indexes exist. I remember in https://github.com/cockroachdb/cockroach/pull/84927 you fixed statistics_builder to handle coexistence of both types of histogram, so I assumed `ANALYZE` would create both, but maybe that's not the case?

Well, this doesn't seem like a blocker anyway. We can fix this in another PR.
</blockquote></details>

Yeah, this appears to be broken.

Since it's not a regression, I'll file a new issue.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91762)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2)

___
*[`pkg/sql/logictest/testdata/logic_test/distsql_stats` line 1946 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/91762#-NH0kKLGEGR6OajmDwJy:-NH36-o9C5RrLrr55CsV:bbqn17g) ([raw file](https://github.com/cockroachdb/cockroach/blob/40329420b0a4b57b369ef9b5dc7c702ff09a08fe/pkg/sql/logictest/testdata/logic_test/distsql_stats#L1946)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Yeah, this appears to be broken.

Since it's not a regression, I'll file a new issue.
</blockquote></details>

#92036

**Review by michae2 — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91762)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis)

___
*[`pkg/sql/logictest/testdata/logic_test/distsql_stats` line 1946 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/91762#-NH0kKLGEGR6OajmDwJy:-NH5ZYmS3Eakr0dQn2w1:b-9755fn) ([raw file](https://github.com/cockroachdb/cockroach/blob/40329420b0a4b57b369ef9b5dc7c702ff09a08fe/pkg/sql/logictest/testdata/logic_test/distsql_stats#L1946)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

#92036
</blockquote></details>

Thank you!

**Comment by jordanlewis** [comment]
Thanks for the review!

bors r+

**Comment by jordanlewis** [comment]
A randomized test failed. I needed to teach the random schema generator that arrays with types that are only inverted-indexable are themselves only inverted-indexable.

bors r+

**Pull request merged**
