### PR TITLE
cli: pass --database value to sql connection

### LINKED ISSUE #4870: cli: setting --database does nothing
```
$ ./cockroach sql --insecure --database system -e "show database"
1 row
DATABASE

$ ./cockroach sql --insecure -e "show database"
1 row
DATABASE

```

### PR DESCRIPTION
**Pull request by dt**
Fixes #4870

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4871)

### CODE REVIEW

**Comment by petermattis** [comment]
LGTM

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[cli/sql_util.go, line 140 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4871#-KC2KKoSho5mJPww9Txp:-KC2KKoSho5mJPww9Txq:1981821564) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7f01467ff3d9da92d068f4dff22fa9ca055e2c0/cli/sql_util.go#L140)):*
Since you're setting `Path` here, I think you can leave `connectToDb` out of  `cliContext` and just use `connDBName`. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4871#-:-KC2KYOgEy6BBQZEQaTG:676834233)*

**Comment by dt** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[cli/sql_util.go, line 140 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4871#-KC2KKoSho5mJPww9Txp:-KC2Kxckw9HIxYzgbye9:-949859782) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7f01467ff3d9da92d068f4dff22fa9ca055e2c0/cli/sql_util.go#L140)):*
oh, true. Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4871)*

**Comment by petermattis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[cli/start.go, line 156 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4871#-KC2LUksU1-iC0e253ei:-KC2LUksU1-iC0e253ej:539379052) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8fc60ba18580ff7040b81523f4de7f713a970fc/cli/start.go#L156)):*
The call to `.String()` is superfluous. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4871)*

**Comment by tamird** [comment]
Reviewed 2 of 5 files at r1, 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[cli/sql_util.go, line 140 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4871#-KC2KKoSho5mJPww9Txp:-KC2Ly-RNDlJ6uwL9Hti:2129280372) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7f01467ff3d9da92d068f4dff22fa9ca055e2c0/cli/sql_util.go#L140)):*
can you rename this to something other than `s`? it's a URL struct.

---

*[server/context.go, line 254 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4871#-KC2Lsnl5VsBB9S7oNEM:-KC2Lsnl5VsBB9S7oNEN:1268006393) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8fc60ba18580ff7040b81523f4de7f713a970fc/server/context.go#L254)):*
why does this return a pointer?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4871)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[server/context.go, line 254 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4871#-KC2Lsnl5VsBB9S7oNEM:-KC2MNyyeBNpKZyxRxqw:320805164) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8fc60ba18580ff7040b81523f4de7f713a970fc/server/context.go#L254)):*
I think you're getting too hung up on pointer vs value. It definitely matters in certain code. It doesn't matter here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4871)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[server/context.go, line 254 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4871#-KC2Lsnl5VsBB9S7oNEM:-KC2Mj46eqOkkotMvamt:1750033573) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8fc60ba18580ff7040b81523f4de7f713a970fc/server/context.go#L254)):*
Also `URL.String` has a pointer receiver. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4871)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[server/context.go, line 254 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4871#-KC2Lsnl5VsBB9S7oNEM:-KC2Mtrm9f6tpkzp3-yW:1889049466) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8fc60ba18580ff7040b81523f4de7f713a970fc/server/context.go#L254)):*
Heh, I was just about to point that out: http://play.golang.org/p/5bGBnV1Fxd

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4871)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[server/context.go, line 254 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4871#-KC2Lsnl5VsBB9S7oNEM:-KC2N3GnoeB6j3XAHn9G:25035849) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8fc60ba18580ff7040b81523f4de7f713a970fc/server/context.go#L254)):*
My comment wasn't meant to imply that this is a performance concern, sorry if that was unclear. Using pointers like this (where they are not needed) creates opportunities for confusion because pointers are nullable. In general, I'd like us to use values everywhere, and pointers where it matters. Since this case doesn't matter, it should be a value.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4871)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[cli/start.go, line 156 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4871#-KC2LUksU1-iC0e253ei:-KC2PK8pmTbisavoC40D:667903367) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8fc60ba18580ff7040b81523f4de7f713a970fc/cli/start.go#L156)):*
Hm, I think I prefer the explicit call to the `String` logic, esp in light of the easy (and untypechecked) mistake that you pointed out in the pointer discussion.

---

*[server/context.go, line 254 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4871#-KC2Lsnl5VsBB9S7oNEM:-KC2OyxeX4cyLKzBSbiI:651857087) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8fc60ba18580ff7040b81523f4de7f713a970fc/server/context.go#L254)):*
Given that it has pointer receiver methods, I'm not sure what you're suggesting. You want it to return a value, and then make a local variable at every callsite so I can take its address to call those methods?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4871)*

**Comment by tamird** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[cli/start.go, line 156 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4871#-KC2LUksU1-iC0e253ei:-KC2SjCjB94tL2KITr4Q:-2118675884) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8fc60ba18580ff7040b81523f4de7f713a970fc/cli/start.go#L156)):*
`vet` doesn't catch this?

---

*[server/context.go, line 254 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4871#-KC2Lsnl5VsBB9S7oNEM:-KC2S6FzkjhkYO-ORzfU:817825277) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8fc60ba18580ff7040b81523f4de7f713a970fc/server/context.go#L254)):*
Ah, I misunderstood the reason for bringing up that String had a pointer receiver, my apologies. A comment explaining why this is a pointer would be good.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4871)*

**Comment by dt** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[cli/sql_util.go, line 140 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4871#-KC2KKoSho5mJPww9Txp:-KC2TybXoQtjI_pkc81B:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7f01467ff3d9da92d068f4dff22fa9ca055e2c0/cli/sql_util.go#L140)):*
Done.

---

*[cli/start.go, line 156 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4871#-KC2LUksU1-iC0e253ei:-KC2UIgWbAvSFw3Ma9CR:2129172373) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8fc60ba18580ff7040b81523f4de7f713a970fc/cli/start.go#L156)):*
doesn't look like it: https://github.com/golang/go/blob/master/src/cmd/vet/print.go#L190

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4871)*

**Comment by petermattis** [comment]
LGTM (again)

---

Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4871#-:-KC2YGLIwKG95Khb-NiG:-1469122166)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[cli/start.go, line 156 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4871#-KC2LUksU1-iC0e253ei:-KC2YJyAmd_YkpXL13Aj:-361852537) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8fc60ba18580ff7040b81523f4de7f713a970fc/cli/start.go#L156)):*
Not sure what I'm looking at there, but tested this and indeed `vet` did not catch it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4871)*

**Pull request merged**
