### PR TITLE
opt: add a per-span cost to scan

### LINKED ISSUE #41701: opt: hash join instead of lookup join on small tables
On small tables, we get hash join when we would normally get a lookup join:

```
create table parent (p int primary key, data int);
insert into parent values (1,1);
create table t (a int, b int);
insert into t values (1,1);
create statistics foo from parent;
create statistics foo from t;
explain (opt) select 1 from parent, t where p=a;

           text           
+------------------------+
  project                 
   ├── inner-join (hash)  
   │    ├── scan parent   
   │    ├── scan t        
   │    └── filters       
   │         └── p = a    
   └── projections        
        └── const: 1      
```

With up to 5 rows in the parent, I still get a hash join. We need to adjust the costs so this doesn't happen. I think the root cause is that we add a `randIOCostFactor` per lookup but the scan doesn't have a `randIOCostFactor` component at all. Maybe we want to exempt the first lookup from that random cost.

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change adds a per-span "random IO" cost for scans. This is more consistent
with how lookup joins are costed. This fixes an issue where we prefer hash join
instead of lookup join even for a single left row when the right table is small,
improving a handful of TPCE queries.

The changes to TPCH Q2 and Q8 seem mildly beneficial from my testing.

Fixes #41701.

Release justification: low risk, high benefit change to existing functionality.

Release note (performance improvement): Joins between very small tables are more
likely to use lookup join.

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm: Just a small nit regarding one of the test changes.

> Reviewed 49 of 49 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53849#-:-MGF__Ep9T-63jmFgHiV:b-fn7cdg)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/xform/testdata/external/tpce, line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53849#-MGFYooM2jhN9Vyb37xZ:-MGFYooM2jhN9Vyb37x_:b41y6if) ([raw file](https://github.com/cockroachdb/cockroach/blob/507f226a86a5e7c214cfa24a245c8a4fbb0a086e/pkg/sql/opt/xform/testdata/external/tpce#L93)):*
> ```
>       │    │    │    │    │    │    │    │    └── fd: (42)-->(44), (44)-->(42)
>       │    │    │    │    │    │    │    └── filters
>       │    │    │    │    │    │    │         └── b_name:44 IN ('Broker1', 'Broker10', 'Broker11', 'Broker12', 'Broker13', 'Broker14', 'Broker15', 'Broker16', 'Broker17', 'Broker18', 'Broker19', 'Broker2', 'Broker20', 'Broker21', 'Broker22', 'Broker23', 'Broker24', 'Broker25', 'Broker26', 'Broker27', 'Broker28', 'Broker29', 'Broker3', 'Broker30', 'Broker4', 'Broker5', 'Broker6', 'Broker7', 'Broker8', 'Broker9') [outer=(44), constraints=(/44: [/'Broker1' - /'Broker1'] [/'Broker10' - /'Broker10'] [/'Broker11' - /'Broker11'] [/'Broker12' - /'Broker12'] [/'Broker13' - /'Broker13'] [/'Broker14' - /'Broker14'] [/'Broker15' - /'Broker15'] [/'Broker16' - /'Broker16'] [/'Broker17' - /'Broker17'] [/'Broker18' - /'Broker18'] [/'Broker19' - /'Broker19'] [/'Broker2' - /'Broker2'] [/'Broker20' - /'Broker20'] [/'Broker21' - /'Broker21'] [/'Broker22' - /'Broker22'] [/'Broker23' - /'Broker23'] [/'Broker24' - /'Broker24'] [/'Broker25' - /'Broker25'] [/'Broker26' - /'Broker26'] [/'Broker27' - /'Broker27'] [/'Broker28' - /'Broker28'] [/'Broker29' - /'Broker29'] [/'Broker3' - /'Broker3'] [/'Broker30' - /'Broker30'] [/'Broker4' - /'Broker4'] [/'Broker5' - /'Broker5'] [/'Broker6' - /'Broker6'] [/'Broker7' - /'Broker7'] [/'Broker8' - /'Broker8'] [/'Broker9' - /'Broker9']; tight)]
> ```

Nice! This full table scan seems like a better option because the `broker` table has only 50 rows.
___
*[pkg/sql/opt/xform/testdata/rules/scan, line 611 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53849#-MGFZdKo2AqoAOEYwyFu:-MGFZdKo2AqoAOEYwyFv:b-eipg4k) ([raw file](https://github.com/cockroachdb/cockroach/blob/507f226a86a5e7c214cfa24a245c8a4fbb0a086e/pkg/sql/opt/xform/testdata/rules/scan#L611)):*
Based on the comment above, it seems like this test was trying to prove something about GenerateConstrainedScans. But it is a bit cryptic. These tests should really be in `testdata/rules/select`, and there may be overlap with the tests for GenerateConstrainedScans there, but we'll leave that worry for another day.

If you can decipher what the test was trying to prove based on the comment, maybe there is a way to alter it so that a constrained scan is chosen. If not, I'd rather delete the test to avoid future confusion.

> ```
> # Realistic example where using constraints as filters help.
> # An even more realistic exmple would have a creation timestamp instead of a
> # seq_num integer, but that makes the plans much more cluttered.
> ```

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53849)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/xform/testdata/rules/scan, line 611 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53849#-MGFZdKo2AqoAOEYwyFu:-MGFzyog4FYm_eFfuGxl:b-4xlejr) ([raw file](https://github.com/cockroachdb/cockroach/blob/507f226a86a5e7c214cfa24a245c8a4fbb0a086e/pkg/sql/opt/xform/testdata/rules/scan#L611)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Based on the comment above, it seems like this test was trying to prove something about GenerateConstrainedScans. But it is a bit cryptic. These tests should really be in `testdata/rules/select`, and there may be overlap with the tests for GenerateConstrainedScans there, but we'll leave that worry for another day.

If you can decipher what the test was trying to prove based on the comment, maybe there is a way to alter it so that a constrained scan is chosen. If not, I'd rather delete the test to avoid future confusion.

> ```
> # Realistic example where using constraints as filters help.
> # An even more realistic exmple would have a creation timestamp instead of a
> # seq_num integer, but that makes the plans much more cluttered.
> ```
 
</blockquote></details>

Good catch, I fixed it by making the range smaller.

**Review by mgartner — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53849)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 48 of 49 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53849#-:-MGJMGHz8LlZVy4m5eo7:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
