### PR TITLE
cli: add cgosymbolizer

### PR DESCRIPTION
**Pull request by tamird**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14130)

### CODE REVIEW

**Comment by petermattis** [comment]
I thought `runtime._ExternalCode` was the stub the Go runtime used when it couldn't get a stacktrace? Do you have an example which shows `rocksdb` stacktraces?

---

Reviewed 1 of 1 files at r1.
Review status: 1 of 14 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14130#-:-Kf9H7gqacDVi0NoyiXA:b3pg0px)*

**Comment by tamird** [comment]
Does `rocksdb::GetLengthPrefixedSlice` not count?

**Comment by petermattis** [comment]
> Does rocksdb::GetLengthPrefixedSlice not count?

It does. So why is so much time still spent in `runtime._ExternalCode`?

**Comment by tamird** [comment]
I don't know, but the possibilities seem to be:
- we don't understand what `runtime._ExternalCode` is
- there is a bug or missing functionality in github.com/ianlancetaylor/cgosymbolizer

I'll dig further into it tomorrow. Is this good to go as-is for the incremental improvement?

**Comment by petermattis** [comment]
Review status: 1 of 15 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[glide.lock, line 181 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14130#-Kf9Lj7qhR3SsNCbGgNf:-Kf9Lj7qhR3SsNCbGgNg:bew9gde) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb3be27ac12bbc9791148671a4839af683037022/glide.lock#L181)):*
> ```
>   subpackages:
>   - query
> - name: github.com/google/pprof
> ```

Shouldn't there be an entry in `glide.yaml` for this? Am I missing something?

---

*[glide.yaml, line 22 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14130#-Kf9LOEKWFWeiX421jaQ:-Kf9LOELew99Oz0Pqdsf:b-p3k6t8) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb3be27ac12bbc9791148671a4839af683037022/glide.yaml#L22)):*
> ```YAML
> # https://github.com/dominikh/go-tools/issues/58
> - package: honnef.co/go/tools
>   version: 063a687828ad7d9e5a0366e1c3b3bfe11b31109b
> ```

Why are all of these other packages being updated? These updates seem unrelated to this PR.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 145 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14130#-Kf9Lx6Psaddx8T-fsP_:-Kf9Lx6Psaddx8T-fsPa:b-uudkku) ([raw file](https://github.com/cockroachdb/cockroach/blob/2eccf441e423e876b89a1b91ff5e4d4e46fce8d9/pkg/sql/distsqlrun/hashjoiner.go#L145)):*
> ```Go
> 		}
> 
> 		b, _ := h.buckets[string(encoded)]
> ```

This seems unrelated to this PR? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14130)*

**Comment by tamird** [comment]
Review status: 1 of 15 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[glide.lock, line 181 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14130#-Kf9Lj7qhR3SsNCbGgNf:-Kf9O6Sth8LWf8mLmb4r:b1cancn) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb3be27ac12bbc9791148671a4839af683037022/glide.lock#L181)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Shouldn't there be an entry in `glide.yaml` for this? Am I missing something?
</blockquote></details>

Yes - this is specified in `build/tool_imports.go`, same as the rest of our `cmd` dependencies.

---

*[glide.yaml, line 22 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14130#-Kf9LOEKWFWeiX421jaQ:-Kf9NvLxTayG9QpZe1WP:b3pk8nh) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb3be27ac12bbc9791148671a4839af683037022/glide.yaml#L22)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Why are all of these other packages being updated? These updates seem unrelated to this PR.
</blockquote></details>

You're not wrong, but I was in there, and these updates are not scary (and updating has the benefit of uncovering various upstream issues which I filed while preparing this PR)

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 145 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14130#-Kf9Lx6Psaddx8T-fsP_:-Kf9O4vTJJETBFA1YumM:b6zmn0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/2eccf441e423e876b89a1b91ff5e4d4e46fce8d9/pkg/sql/distsqlrun/hashjoiner.go#L145)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This seems unrelated to this PR? 
</blockquote></details>

Caught by staticcheck.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14130)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 1 of 15 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[glide.yaml, line 22 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14130#-Kf9LOEKWFWeiX421jaQ:-Kf9QsUY90qKzeHkZCl4:b-f0e9y8) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb3be27ac12bbc9791148671a4839af683037022/glide.yaml#L22)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

You're not wrong, but I was in there, and these updates are not scary (and updating has the benefit of uncovering various upstream issues which I filed while preparing this PR)
</blockquote></details>

You could have updated in another PR and still uncovered the upstream issues.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14130#-:-Kf9R-F2egWTpty-omSv:bnfp4nl)*

**Comment by tamird** [comment]
Review status: 1 of 15 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[glide.yaml, line 22 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14130#-Kf9LOEKWFWeiX421jaQ:-Kf9RLGKSrftqu7W0caP:b9pyt8l) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb3be27ac12bbc9791148671a4839af683037022/glide.yaml#L22)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

You could have updated in another PR and still uncovered the upstream issues.
</blockquote></details>

True, but updating vendor in two PRs is quite annoying, as you know.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14130)*

**Comment by petermattis** [comment]
Review status: 1 of 15 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[glide.yaml, line 22 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14130#-Kf9LOEKWFWeiX421jaQ:-Kf9R_2RTk5j-I9OuQez:b-tktb8a) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb3be27ac12bbc9791148671a4839af683037022/glide.yaml#L22)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

True, but updating vendor in two PRs is quite annoying, as you know.
</blockquote></details>

Yes it is, but I want to get out of the habit of updating deps whenever a new one is added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14130)*

**Comment by bdarnell** [comment]
Reviewed 1 of 1 files at r1, 14 of 14 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[glide.yaml, line 22 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14130#-Kf9LOEKWFWeiX421jaQ:-Kf9q0kqnYk0ZF9_HoTn:b-4zji1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb3be27ac12bbc9791148671a4839af683037022/glide.yaml#L22)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Yes it is, but I want to get out of the habit of updating deps whenever a new one is added.
</blockquote></details>

It's probably time to freeze most of our deps for 1.0 anyway. I think from this point until release we should only upgrade deps with a specific reason. 

---

*[scripts/pprof, line 36 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14130#-Kf9q_gVT89xuV88JC9B:-Kf9q_gVT89xuV88JC9C:b-46vr7o) ([raw file](https://github.com/cockroachdb/cockroach/blob/2eccf441e423e876b89a1b91ff5e4d4e46fce8d9/scripts/pprof#L36)):*
> ```
> trap cleanup EXIT
> 
> go tool pprof "http://127.0.0.1:${port}/debug/pprof/${profile_type}"
> ```

I think this script is still useful because it lets you profile a secure server for which you don't have the binary. Does it work if you replace `go tool pprof` with `pprof`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14130)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[scripts/pprof, line 36 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14130#-Kf9q_gVT89xuV88JC9B:-Kf9rdLM-0d7XjLLbsaa:b2cdh5c) ([raw file](https://github.com/cockroachdb/cockroach/blob/2eccf441e423e876b89a1b91ff5e4d4e46fce8d9/scripts/pprof#L36)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I think this script is still useful because it lets you profile a secure server for which you don't have the binary. Does it work if you replace `go tool pprof` with `pprof`?
</blockquote></details>

Nope, but https://github.com/google/pprof/pull/111 is about to fix this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14130)*

**Pull request merged**
