### PR TITLE
jobspb,changefeedccl: finalize ChangefeedDetails job proto for 2.1

### PR DESCRIPTION
**Pull request by danhhz**
For now, this commit removes remove any table expansions, including
databases. Getting it right as tables enter and leave the set over time
is tricky (as we learned fixing it in incremental backup).

This simplification allows us to store the targeted tables as a list of
IDs. Table IDs can change over time, such as with TRUNCATE, and the
changefeed is responsible for detecting this or preventing it. Post 2.1,
we'll reconsider supporting name expansions and how that should be
represented in this proto.

Release note (enterprise change): CHANGEFEEDs can now only target lists
of physical tables

### CODE REVIEW

**Review by nvb — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27996)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 455 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27996#-LImVto3EiaPyVaU3dQT:-LImVto4D9dyZ8RY2x3X:b-homz5r) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f5bc817decdd9000addc6dbb850d07ed07fa67a/pkg/ccl/changefeedccl/changefeed_test.go#L455)):*
> ```Go
> 	); !testutils.IsError(err, `CHANGEFEED cannot target views: vw`) {
> 		t.Errorf(`expected 'CHANGEFEED cannot target views: vw' error got: %+v`, err)
> 	}
> ```

Are we testing virtual tables somewhere?
___
*[pkg/sql/jobs/jobspb/jobs.proto, line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27996#-LImW9nqDvXGMah8Zo8c:-LImW9nqDvXGMah8Zo8d:b-oiyiap) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f5bc817decdd9000addc6dbb850d07ed07fa67a/pkg/sql/jobs/jobspb/jobs.proto#L130)):*
> ```protobuf
> 
> message ChangefeedDetails {
>   // Changefeeds target a list of tables, which are identified here by ID. Table
> ```

Is the plan to eventually add support back in for creating changefeeds over entire databases? In that case, how do you envision the migration happening? If we constrain the proto then it's going to be hard to make more general again later.

**Review by danhhz — COMMENTED** [review]
Thanks for the review! RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27996#-:-LIrOgWX43IFpiG1mCyp:b-6sx6b6)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 455 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27996#-LImVto3EiaPyVaU3dQT:-LIrMAaj4mA3PaGxXfG7:b-iuvk7u) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f5bc817decdd9000addc6dbb850d07ed07fa67a/pkg/ccl/changefeedccl/changefeed_test.go#L455)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Are we testing virtual tables somewhere?
</blockquote></details>

Done. The error message is wrong, but I don't have time to fix it right now.
___
*[pkg/sql/jobs/jobspb/jobs.proto, line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27996#-LImW9nqDvXGMah8Zo8c:-LIrNuwT7xt6UhYvX9mh:bwq288n) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f5bc817decdd9000addc6dbb850d07ed07fa67a/pkg/sql/jobs/jobspb/jobs.proto#L130)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is the plan to eventually add support back in for creating changefeeds over entire databases? In that case, how do you envision the migration happening? If we constrain the proto then it's going to be hard to make more general again later.
</blockquote></details>

Good point, I left some thoughts while it's loaded up. I think this is pretty easy. Gate the ability to target databases behind a cluster version, then allow putting database IDs in this field.

**Comment by danhhz** [comment]
Hold up on this for a bit. I thought of a better representation

**Review by danhhz — COMMENTED** [review]
Okay, much better. RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27996#-:-LIvGrzCBwr6AZ62DvWY:b-xp9qmx)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27996#-:-LIyUQEH8ayUoKqd52PH:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by danhhz** [comment]
TFTR!

bors r=nvanbenschoten

**Pull request merged**
