### PR TITLE
authors: add pseudomuto to authors

### PR DESCRIPTION
**Pull request by pseudomuto**
Release note: None

### CODE REVIEW

**Review by udnay — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68596)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jreut)

**Comment by udnay** [comment]
LGTM

**Review by udnay — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68596#-:-Mgl3Vqh43F05oDOCELw:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @pseudomuto)

**Comment by pseudomuto** [comment]
bors d+

**Comment by pseudomuto** [comment]
^ whew...no permission escalation here! 😄

**Pull request merged**
