### PR TITLE
schemachanger: remove discard named range fallback

### LINKED ISSUE #133157: schemachanger: support configure zone discard for zone configs
This issue tracks our progress of supporting zone configs in declarative schema changer; in particular, this tracks support for `ALTER { RANGE | DATABASE | TABLE } ... CONFIGURE ZONE DISCARD` in the declarative schema changer.

Jira issue: CRDB-43481

Epic CRDB-43532

### PR DESCRIPTION
**Pull request by annrpom**
This patch removes the fallback to legacy schema changer
path we have for discarding named ranges. This includes
ensuring we block the ability to discard the system range.

Fixes: #133157

Epic: none
Release note: None

### CODE REVIEW

**Review by spilchen — COMMENTED** [review]
Looks good. I just had a couple of questions.

> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135909#-:-OCZO0la7e0Y2MuIm6fH:blprirf)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom)

___
*[`pkg/sql/schemachanger/testdata/end_to_end/alter_named_range_configure_zone_discard/alter_named_range_configure_zone_discard.definition` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135909#-OCZMtcE2NGhozAhGAXV:-OCZMtcE2NGhozAhGAXW:ber7ae6) ([raw file](https://github.com/cockroachdb/cockroach/blob/18e29f95498e16824aecfcd50d43238b6c5bae88/pkg/sql/schemachanger/testdata/end_to_end/alter_named_range_configure_zone_discard/alter_named_range_configure_zone_discard.definition#L4)):*
> ```
> ALTER RANGE meta CONFIGURE ZONE USING num_replicas = 7;
> ALTER RANGE meta CONFIGURE ZONE USING gc.ttlseconds = 10000;
> ALTER RANGE meta CONFIGURE ZONE DISCARD;
> ```

Can we add a test that first discards the configuration and then applies updates in the same transaction? For example:
```
ALTER RANGE meta CONFIGURE ZONE DISCARD; 
ALTER RANGE meta CONFIGURE ZONE USING num_replicas = 7; 
ALTER RANGE meta CONFIGURE ZONE USING gc.ttlseconds = 10000;
```

I'm curious if we handle the operation ordering correctly, ensuring `num_replicas` and `gc.ttlseconds` are applied after the discard.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go` line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135909#-OCZOayq7HnYxhnR1HRc:-OCZOayq7HnYxhnR1HRd:b-tvz4yk) ([raw file](https://github.com/cockroachdb/cockroach/blob/18e29f95498e16824aecfcd50d43238b6c5bae88/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go#L128)):*
> ```Go
> 		id, found := zonepb.NamedZones[namedZone]
> 		if !found {
> 			return nil, fmt.Errorf("%q is not a built-in zone", string(zs.NamedZone))
> ```

Should this error have a proper pgcode set? I was able to find the error in the legacy schema changer that this mirrors.

**Review by annrpom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135909)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go` line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135909#-OCZOayq7HnYxhnR1HRc:-OCZXbAwAb0zRR82pETa:bs805by) ([raw file](https://github.com/cockroachdb/cockroach/blob/18e29f95498e16824aecfcd50d43238b6c5bae88/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go#L128)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Should this error have a proper pgcode set? I was able to find the error in the legacy schema changer that this mirrors.
</blockquote></details>

done -- ah as in add a pgcode for this + the legacy schema changer? i can do that; i think 42602 might make the most sense (InvalidName)
___
*[`pkg/sql/schemachanger/testdata/end_to_end/alter_named_range_configure_zone_discard/alter_named_range_configure_zone_discard.definition` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135909#-OCZMtcE2NGhozAhGAXV:-OCZZTaJ9GAvfTEqqxL_:b81c33e) ([raw file](https://github.com/cockroachdb/cockroach/blob/18e29f95498e16824aecfcd50d43238b6c5bae88/pkg/sql/schemachanger/testdata/end_to_end/alter_named_range_configure_zone_discard/alter_named_range_configure_zone_discard.definition#L4)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Can we add a test that first discards the configuration and then applies updates in the same transaction? For example:
```
ALTER RANGE meta CONFIGURE ZONE DISCARD; 
ALTER RANGE meta CONFIGURE ZONE USING num_replicas = 7; 
ALTER RANGE meta CONFIGURE ZONE USING gc.ttlseconds = 10000;
```

I'm curious if we handle the operation ordering correctly, ensuring `num_replicas` and `gc.ttlseconds` are applied after the discard.
</blockquote></details>

done  -- added a logictest as that seemed better suited; wdyt?

**Review by spilchen — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135909#-:-OC_BMD64kEEhJMYuJ_Y:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @annrpom)

___
*[`pkg/sql/schemachanger/testdata/end_to_end/alter_named_range_configure_zone_discard/alter_named_range_configure_zone_discard.definition` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135909#-OCZMtcE2NGhozAhGAXV:-OC_Aic59gDr85kD9GYE:b-czspp9) ([raw file](https://github.com/cockroachdb/cockroach/blob/18e29f95498e16824aecfcd50d43238b6c5bae88/pkg/sql/schemachanger/testdata/end_to_end/alter_named_range_configure_zone_discard/alter_named_range_configure_zone_discard.definition#L4)):*
<details><summary><i>Previously, annrpom (annie pompa) wrote…</i></summary><blockquote>

done  -- added a logictest as that seemed better suited; wdyt?
</blockquote></details>

Logic tests are much simpler! It seems mutations are applied in statement order, even when they involve different types of operations (e.g., discard vs. setting specific values).
___
*[`pkg/sql/logictest/testdata/logic_test/zone_config` line 450 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135909#-OC_ASpq4hYr8zWiJU-6:-OC_ASpq4hYr8zWiJU-7:b33355) ([raw file](https://github.com/cockroachdb/cockroach/blob/75b6d58a259ec3c22c1bed269fbf8b5f5cf54ffc/pkg/sql/logictest/testdata/logic_test/zone_config#L450)):*
> ```
> 
> statement ok
> RESET use_declarative_schema_changer;
> ```

Is this safe to apply to the local legacy schema changer? We won't lose track of the fact that it's operating under the legacy schema changer, correct?

**Review by annrpom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135909)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/sql/logictest/testdata/logic_test/zone_config` line 450 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135909#-OC_ASpq4hYr8zWiJU-6:-OC_CeuNAQLnRkXnly2Q:b7ak2yo) ([raw file](https://github.com/cockroachdb/cockroach/blob/75b6d58a259ec3c22c1bed269fbf8b5f5cf54ffc/pkg/sql/logictest/testdata/logic_test/zone_config#L450)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Is this safe to apply to the local legacy schema changer? We won't lose track of the fact that it's operating under the legacy schema changer, correct?
</blockquote></details>

ooo good question! it looks like we will not lose track since that config overrides the cluster setting -- not the session variable (i also just confirmed this real quick by showing the session var value under the legacy config and it is confirmed off) https://github.com/cockroachdb/cockroach/blob/0d3d74c278b920f425ce95f1b222182091371d86/pkg/sql/logictest/logic.go#L1770-L1777

**Comment by annrpom** [comment]
TFTR! ('-')7 

bors r+

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135909)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained

___
*[`pkg/sql/logictest/testdata/logic_test/zone_config` line 450 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135909#-OC_ASpq4hYr8zWiJU-6:-OC_dcJc1a1Q0APfAwO0:bzbpuo3) ([raw file](https://github.com/cockroachdb/cockroach/blob/75b6d58a259ec3c22c1bed269fbf8b5f5cf54ffc/pkg/sql/logictest/testdata/logic_test/zone_config#L450)):*
<details><summary><i>Previously, annrpom (annie pompa) wrote…</i></summary><blockquote>

ooo good question! it looks like we will not lose track since that config overrides the cluster setting -- not the session variable (i also just confirmed this real quick by showing the session var value under the legacy config and it is confirmed off) https://github.com/cockroachdb/cockroach/blob/0d3d74c278b920f425ce95f1b222182091371d86/pkg/sql/logictest/logic.go#L1770-L1777
</blockquote></details>

Thanks for confirming.

**Pull request merged**
