### PR TITLE
spanconfig: add a static split point at the start of meta2

### LINKED ISSUE #119421: kv: meta1 prevents meta2 from load-based splitting
In a 1000 node cluster, we saw that meta2 became a load hotspot. The keyspace was consolidated on a single range, range 1. This was despite the fact that meta2 is allowed to split.

The reason the range wasn't splitting and rebalancing was because it was part of meta1's range. Meta1 is not allowed to split, and this was preventing load-based splitting from applying to meta2.

To fix this, I manually split the range at the meta2 start key:
```bash
$ cat req.json
{"header":{},"requests":[{"adminSplit":{"header":{"key":"Ag=="},"splitKey":"Aw==","expirationTime":{}}}]}

$ ./cockroach debug send-kv-batch --insecure --port=29000 req.json
```

With this change, meta2 quickly split (from load) dozens of times and the hotspot disappeared (5:57):

Screenshot 2024-02-20 at 4 00 37 PM

There are a few possible solutions for this. The most straightforward is probably to install an initial static split point at `Meta2Prefix` so that meta1 and meta2 are always stored on separate ranges.

Jira issue: CRDB-36188

Epic CRDB-52413

### PR DESCRIPTION
**Pull request by arulajmani**
Meta1 is not allowed to split, whereas meta2 is. This could prevent load based splitting from applying to meta2. This patch now installs a static split point at the start of meta2 so that load based splitting can do its thing.

Resolves https://github.com/cockroachdb/cockroach/issues/119421

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119594#-:-Ns9NMoLDtPaz8VLFmXa:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @rafiss)

___
*[`pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go` line 261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119594#-Ns9MNsl8IQIvTsqr7E-:-Ns9MNsl8IQIvTsqr7E0:b-3znd7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/238868befd15de9f601cebbf2059e33de0f6706c/pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go#L261)):*
> ```Go
> 		// apply to meta2. See
> 		// https://github.com/cockroachdb/cockroach/issues/119421.
> 		spans = append(spans, keys.Meta1Span)
> ```

How will this behave on existing clusters that get upgraded to v24.1? Will span configs be asynchronously re-reconciled, and then r1's split queue will notice and eventually decide to split at meta2 prefix? That seems fine — just want to make sure we've thought through this transition and that things will work without issue.
___
*[`pkg/ccl/spanconfigccl/spanconfigreconcilerccl/testdata/protectedts` line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119594#-Ns9N7qZ2qVoRBSqPsEF:-Ns9N7qZ2qVoRBSqPsEG:b-q19822) ([raw file](https://github.com/cockroachdb/cockroach/blob/238868befd15de9f601cebbf2059e33de0f6706c/pkg/ccl/spanconfigccl/spanconfigreconcilerccl/testdata/protectedts#L136)):*
> ```
> delete {source=1,target=2}
> 
> state limit=2
> ```

Should we use `limit=3` here so we continue to see the data range config?
___
*[`pkg/ccl/spanconfigccl/spanconfigreconcilerccl/testdata/multitenant/protectedts` line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119594#-Ns9NJ7L72cLB-3g6oBi:-Ns9NJ7L72cLB-3g6oBj:b96yxcn) ([raw file](https://github.com/cockroachdb/cockroach/blob/238868befd15de9f601cebbf2059e33de0f6706c/pkg/ccl/spanconfigccl/spanconfigreconcilerccl/testdata/multitenant/protectedts#L179)):*
> ```
> 
> # All system span config targets should have been removed at this point.
> state limit=4
> ```

`limit=5` here?

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119594)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @rafiss)

___
*[`pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go` line 261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119594#-Ns9MNsl8IQIvTsqr7E-:-Ns9Sp4mAXx2LyJm3IFC:b-9t68n2) ([raw file](https://github.com/cockroachdb/cockroach/blob/238868befd15de9f601cebbf2059e33de0f6706c/pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go#L261)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

How will this behave on existing clusters that get upgraded to v24.1? Will span configs be asynchronously re-reconciled, and then r1's split queue will notice and eventually decide to split at meta2 prefix? That seems fine — just want to make sure we've thought through this transition and that things will work without issue.
</blockquote></details>

For clusters that upgrade to v24.1, we'll be in the incremental reconciliation regime, so we'll not re-recocile using this static split point. We'll do a full reconciliation if/when the job moves to a different node because of this TODO:

https://github.com/cockroachdb/cockroach/blob/611ac957fd235ba1087f7a1f3950138eb6a250ef/pkg/spanconfig/spanconfigreconciler/reconciler.go#L147-L150

We could add a migration that installs this static split point if we wanted to be more proactive about this. I chose not to because it'll eventually happen and it didn't feel critical -- no strong feelings here, so I'm happy to add a migration if you think it's worth doing.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119594)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @rafiss)

___
*[`pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go` line 261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119594#-Ns9MNsl8IQIvTsqr7E-:-NsKVgqvDdR5MVutGKvE:bqevp0z) ([raw file](https://github.com/cockroachdb/cockroach/blob/238868befd15de9f601cebbf2059e33de0f6706c/pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go#L261)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

For clusters that upgrade to v24.1, we'll be in the incremental reconciliation regime, so we'll not re-recocile using this static split point. We'll do a full reconciliation if/when the job moves to a different node because of this TODO:

https://github.com/cockroachdb/cockroach/blob/611ac957fd235ba1087f7a1f3950138eb6a250ef/pkg/spanconfig/spanconfigreconciler/reconciler.go#L147-L150

We could add a migration that installs this static split point if we wanted to be more proactive about this. I chose not to because it'll eventually happen and it didn't feel critical -- no strong feelings here, so I'm happy to add a migration if you think it's worth doing.
</blockquote></details>

Will the rolling restart needed to upgrade each binary to v24.1 be enough to kick off the reconciliation?

Also, if the job switches back and forth between a v24.1 binary and a v23.2 binary in a mixed-version state, will the split point be created a removed multiple times?

**Review by arulajmani — COMMENTED** [review]
Sorry for not responding earlier. Completely dropped off my list, I thought this had merged already.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119594#-:-NtxwbKC36l62evQA2Cn:bh0z453)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten and @rafiss)

___
*[`pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go` line 261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119594#-Ns9MNsl8IQIvTsqr7E-:-NtxrNseCYlADMgKQNvV:b-ugkgz0) ([raw file](https://github.com/cockroachdb/cockroach/blob/238868befd15de9f601cebbf2059e33de0f6706c/pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go#L261)):*
> Will the rolling restart needed to upgrade each binary to v24.1 be enough to kick off the reconciliation?

Yeah, it should be. The job will move at-least once during the rolling re-start, and it'll end up on a v24.1 node at the end -- that should kick off a full reconciliation and leave us with this static split point.

> Also, if the job switches back and forth between a v24.1 binary and a v23.2 binary in a mixed-version state, will the split point be created a removed multiple times?

Unfortunately, yes, it could be created and removed multiple times. Once the upgrade finishes, the last full reconciliation is guaranteed to be done by a v24.1 node, so we'll have the split point in the end. It's not ideal, but maybe it's okay? 

An alternative would be to add a version gate here and conditionally split out this split point. That'll mean we won't create and remove the split point multiple times, but then we're in the "when the job moves to a different node" scenario. Do you like this approach better?

----

My initial suggestion of adding a migration that installs a static split point, and ensuring it doesn't get clobbered by the reconciliation job seems tricky to get right.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119594)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani and @rafiss)

___
*[`pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go` line 261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119594#-Ns9MNsl8IQIvTsqr7E-:-NtxxFXgElF15aMWc-x9:b-lknpev) ([raw file](https://github.com/cockroachdb/cockroach/blob/238868befd15de9f601cebbf2059e33de0f6706c/pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go#L261)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

> Will the rolling restart needed to upgrade each binary to v24.1 be enough to kick off the reconciliation?

Yeah, it should be. The job will move at-least once during the rolling re-start, and it'll end up on a v24.1 node at the end -- that should kick off a full reconciliation and leave us with this static split point.

> Also, if the job switches back and forth between a v24.1 binary and a v23.2 binary in a mixed-version state, will the split point be created a removed multiple times?

Unfortunately, yes, it could be created and removed multiple times. Once the upgrade finishes, the last full reconciliation is guaranteed to be done by a v24.1 node, so we'll have the split point in the end. It's not ideal, but maybe it's okay? 

An alternative would be to add a version gate here and conditionally split out this split point. That'll mean we won't create and remove the split point multiple times, but then we're in the "when the job moves to a different node" scenario. Do you like this approach better?

----

My initial suggestion of adding a migration that installs a static split point, and ensuring it doesn't get clobbered by the reconciliation job seems tricky to get right.
</blockquote></details>

A version gate seems like a reasonable approach to me. I'm less concerned about a hard bound on how quickly the split point is installed, and more concerned about instability during an upgrade. So delaying the split to a point where we know it won't be removed SGTM, as long as you also like that approach.

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119594)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten and @rafiss)

___
*[`pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go` line 261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119594#-Ns9MNsl8IQIvTsqr7E-:-Nty74ew3gbEkMVVhflE:bdaf9qq) ([raw file](https://github.com/cockroachdb/cockroach/blob/238868befd15de9f601cebbf2059e33de0f6706c/pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go#L261)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

A version gate seems like a reasonable approach to me. I'm less concerned about a hard bound on how quickly the split point is installed, and more concerned about instability during an upgrade. So delaying the split to a point where we know it won't be removed SGTM, as long as you also like that approach.
</blockquote></details>

Yeah, version gating sounds good to me as well. Added one, and also added a test to show how the mixed version state will look like.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119594#-:-NtyA5be00gn5wLrGH6_:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rafiss)

**Pull request closed without merging**
