### PR TITLE
security: prevent PEM decoding errors by careful newline insertation

### LINKED ISSUE #71588: security: certificates without an end-of-line character will not be loaded properly by the UI's TLS logic
**Describe the problem**

When using certificate authority files that do not have an end-of-line character at the end of a file, the `GetTenantTLSConfig` and `GetUIClientTLSConfig` methods of CertificateManager will create unreadable certificate authority blobs. `getTenantCACertLocked` will resolve to whatever certificate authority exists, regardless of if the code is running in a multi-tenant environment or not, which means `GetTenantTLSConfig` and `GetUIClientTLSConfig` will always return two certificates in a blob.

While `GetTenantTLSConfig` is only called in a multi-tenant environment, `GetUIClientTLSConfig` is called in dedicated environments and will try to concatenate whatever certificates it receives from `getUICACertLocked` and `getTenantCACertLocked`. As mentioned before, this could result in two copies of `ca.crt`, or a combination of other certificate authorities.

If the certificate does not have an end-of-line character, the resulting loaded certificate would appear as follows:

```
-----BEGIN CERTIFICATE-----
MIIBITCB1KADAgECAgEBMAUGAytlcDASMRAwDgYDVQQDEwdUZXN0IENBMCAYDzAw
MDEwMTAxMDAwMDAwWhcNMjEwOTI5MTY1NTMwWjARMQ8wDQYDVQQDEwZDbGllbnQw
KjAFBgMrZXADIQDVQnGdqEybPlhb5PFCkHceGlAD7su0u8HP8gvIK/IoqaNOMEww
EwYDVR0lBAwwCgYIKwYBBQUHAwIwHwYDVR0jBBgwFoAU/aMVid2wZ4G0EYfp2cKK
j0tLDo4wFAYDVR0RBA0wC4IJbXktY2xpZW50MAUGAytlcANBAPBgz2jFGF3z4OUK
iXpxklAt6NRRFxSz/pUj/eayKnu4L4xi9UjRZ17mwDxWiwwkDuASD04+e8CvxMwS
O9dpkgY=
-----END CERTIFICATE----------BEGIN CERTIFICATE-----
MIIBITCB1KADAgECAgEBMAUGAytlcDASMRAwDgYDVQQDEwdUZXN0IENBMCAYDzAw
MDEwMTAxMDAwMDAwWhcNMjEwOTI5MTY1NTMwWjARMQ8wDQYDVQQDEwZDbGllbnQw
KjAFBgMrZXADIQDVQnGdqEybPlhb5PFCkHceGlAD7su0u8HP8gvIK/IoqaNOMEww
EwYDVR0lBAwwCgYIKwYBBQUHAwIwHwYDVR0jBBgwFoAU/aMVid2wZ4G0EYfp2cKK
j0tLDo4wFAYDVR0RBA0wC4IJbXktY2xpZW50MAUGAytlcANBAPBgz2jFGF3z4OUK
iXpxklAt6NRRFxSz/pUj/eayKnu4L4xi9UjRZ17mwDxWiwwkDuASD04+e8CvxMwS
O9dpkgY=
-----END CERTIFICATE-----
```

As this is not a valid PEM, an error will be received along the lines of:

> problem using security settings: failed to parse PEM data to pool

**To Reproduce**

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster with a normal set of certificate authorities (just `ca.crt` on its own is acceptable)
2. Delete the newlines from the end of your `ca.crt` and other certificate authorities. (For example, using `truncate -s -1 ca.crt`)
3. Attempt to start the server

**Expected behavior**
Only the UI certificate authority should be loaded and no error should occur.

**Additional context**
This issue was introduced by a PR (https://github.com/cockroachdb/cockroach/pull/71248) to fix a security issue in the multi-tenant environment. Unfortunately I missed this issue during code review.

### PR DESCRIPTION
**Pull request by catj-cockroach**
Fixes https://github.com/cockroachdb/cockroach/issues/71588

> Previously, we assumed that the Tenant CA certificate and the CA
> certificate would not be the same, and that they would be saved as
> files with an end of file newline character.
> 
> This change adds support for not loading the Tenant CA Certificate
> if it will just be a second copy of the CA certificate.
> 
> This change also adds a helper function to concatenate certificates
> with a newline separating each, to ensure that the easiest way to
> make a certificate bundle is the correct way.
> 
> Release note: bugfix for certificate loading logic

The bug in question was introduced in https://github.com/cockroachdb/cockroach/pull/71248 (and back ported in https://github.com/cockroachdb/cockroach/pull/71402).

### CODE REVIEW

**Review by chrisseto — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71548#-:-Mlz6vu015DEgA30wScp:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @catj-cockroach, @jaylim-crl, and @knz)

___
*[pkg/security/certs_test.go, line 652 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71548#-Mlz7--W0pmRP-7vrUaX:-Mlz7--W0pmRP-7vrUaY:bkcxb4r) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed7060e3943a5576b31b16abdc704e85f63ccc48/pkg/security/certs_test.go#L652)):*
> ```Go
> 
> 	for _, certFilename := range []string{
> 		//		security.EmbeddedClientCACert,
> ```

Uncomment or remove these lines?
___
*[pkg/security/certs_test.go, line 675 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71548#-Mlz7AB97l2bHk1O9_U0:-Mlz7AB97l2bHk1O9_U1:b-uf019a) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed7060e3943a5576b31b16abdc704e85f63ccc48/pkg/security/certs_test.go#L675)):*
> ```Go
> 			t.Fatalf("appendCertificatesToBlob failed to properly concatenate the test certificates together:\n===\n%s===\n", caBlob)
> 		} else {
> 			t.Fatal("appendCertificatesToBlob failed to properly concatenate the test certificates together. Run with the verbose flag set to see the output.")
> ```

nit: `s/with the verbose flag set/-v/`to be a bit more clear

**Comment by catj-cockroach** [comment]
blathers backport 21.2

**Review by bdarnell — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71548)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @catj-cockroach, @jaylim-crl, and @knz)

**Review by rauchenstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71548)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @catj-cockroach, @jaylim-crl, and @knz)

___
*[pkg/security/certs_test.go, line 669 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71548#-Mm0D0rmElG1_tYA5ul8:-Mm0D0rnBrLA0E8FyhNY:b-s98sdx) ([raw file](https://github.com/cockroachdb/cockroach/blob/94956131c2211af3701d04afbf5365b8abf18529/pkg/security/certs_test.go#L669)):*
> ```Go
> 
> 	caBlob = security.AppendCertificatesToBlob(
> 		bytes.TrimRight(caBlob, "\n"),
> ```

Would it make sense for AppendCertificatesToBlob to trim its inputs instead of having the caller do it?

**Review by knz — COMMENTED** [review]
LGTM

**Pull request merged**
