### PR TITLE
Move Stores out of LocalSender

### PR DESCRIPTION
**Pull request by vivekmenezes**
@tschottdorf is this what you had in mind?

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3183)

### CODE REVIEW

**Comment by tschottdorf** [comment]
Sorry, in my comment I thought you referred to `kv/node` which is obviously not what you were talking about. I don't see how this would eventually help you avoid `sql -> server`. My pet peeve with `LocalSender` is that it lets `kv` depend on `storage` for no good reason.

**Comment by vivekmenezes** [comment]
Tobi,

Id like to still consider this change. The problem is that SQL needs to
access the stores to figure out whether the local node is a leader for the
table key prefix and now that involves making a  dependency on server which
sits right at the top. Id like to make this change move stores to storage
and have SQL depend on storage. Server will pass in the stores into SQL at
start time.

**Comment by petermattis** [comment]
@vivekmenezes Can't an interface be used to remove a direct dependency from `sql` to `storage`?

**Comment by vivekmenezes** [comment]
Yes that's what we did in the original change i had made but i think it
will be valuable to create a stores interface, instead of having to always
go through the lsender for stores which feels wrong. This is not a major
refactoring IMHO.

**Comment by bdarnell** [comment]
I agree that going through the local sender feels wrong, but I think the only problem is the name. As we've moved to implementing the `Sender` interface directly on types like `Store` and `Replica`, I think it would be natural to move `LocalSender.Send` to `Stores`, leaving nothing behind in `LocalSender`. I think my preference would be to just move `LocalSender` as-is to `storage` (exporting the `RangeDescriptorDB` interface), and maybe rename it to `LocalStores` or just `Stores`.

**Comment by vivekmenezes** [comment]
I'm fine with doing what ben suggested. Ill send out a pr when i get a
chance.

**Pull request closed without merging**
