### PR TITLE
sql: use correct context when calling waitForCacheToDropDatabases

### LINKED ISSUE #26147: roachtest: drop/tpcc/w=100,nodes=9 failed on master
SHA: https://github.com/cockroachdb/cockroach/commits/83e98d996b3ba3537afd7bc67e439eb5d3ea1659

Parameters:

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=683712&tab=buildLog

```
	drop.go:139,cluster.go:960,errgroup.go:58: Node 3 space after deletion used: 5.7 GiB
		disk space usage has not dropped below 100 MiB on all nodes.

```

### PR DESCRIPTION
**Pull request by vivekmenezes**
fixes #26147

Release note: None

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
was this a span-use-after-finish cause `ApplyWithPayload` finishes it?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28976#-:-LKYSlwl-0lIVd6pimCi:b-ibv668)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by vivekmenezes** [comment]
This seems to be a bad context being passed to log.vevent on a rollback of
a txn trying to read a database descriptor. Not sure if it will actually
fix the bug but fortunately this test is failing every day in the same
spot, and that spot has the wrong ctx.

**Review by andreimatei — COMMENTED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28976#-:-LKYW2S4EA8PSVzx95ak:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
