### PR TITLE
opt: support JSON operators and comparisons

### PR DESCRIPTION
**Pull request by justinj**
Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
Search around for usages of `Comparison` in the opt directories. There are several other places that will need to be updated. At least these:

1. Add new comparison operators to `ComparisonOpReverseMap`.
2. `NegateComparison` rule in `bool.opt` needs to do something like `^(Contains|JsonExists|JsonAllExists|...)`, since these new ops don't have negated versions of themselves (otherwise you'd add to `Factory.negateComparison`).
3. Determine correct null behavior for `FoldNullComparisonLeft` and `FoldNullComparisonRight` rules. My assumption is that these new operators work like `Contains`, and so you might not need to do anything there.

Also, make sure that you add regression test cases for anything you determine you missed (`bool` file is one place you'll want to add a negation case).

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24369#-:-L8sBgvU52jiGeyXca2o:b-o9odus)*

**Comment by rytaft** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/sql/opt/exec/execbuilder/testdata/scalar, line 335 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24369#-L8t2FcyDukYx9eCfPXo:-L8t2FcyDukYx9eCfPXp:b-eh5x6g) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb7dca7bb34c500860893b2b5172833e5cd58bc7/pkg/sql/opt/exec/execbuilder/testdata/scalar#L335)):*
> ```
> ·          1  ·       spans     ALL              ·          ·
> 
> exec-explain
> ```

Can you add some tests here for the JSON operators ?, ?| and ?& ?

---

*[pkg/sql/opt/optbuilder/testdata/scalar, line 599 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24369#-L8t17gS4GSBu4EURhvW:-L8t17gS4GSBu4EURhvX:b-y4s83p) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bbc9eedcd31bbfcb4727afa76e79351615a1036/pkg/sql/opt/optbuilder/testdata/scalar#L599)):*
> ```
>       └── const: 'baz' [type=string]
> 
> build-scalar vars=(json) allow-unsupported
> ```

Can you add some other scalar expression that is still unsupported as a test of allow-unsupported?

---

*[pkg/sql/opt/optbuilder/testdata/scalar, line 631 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24369#-L8t2lAyBTB0syKXYMuc:-L8t2lAyBTB0syKXYMud:b-bnjyur) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb7dca7bb34c500860893b2b5172833e5cd58bc7/pkg/sql/opt/optbuilder/testdata/scalar#L631)):*
> ```
>  │    ├── variable: @1 [type=jsonb]
>  │    └── const: 'a' [type=string]
>  └── const: 'b' [type=string]
> ```

Can you also add tests for ->, #> and #>>?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24369)*

**Comment by justinj** [comment]
Thanks for the pointers! Think I added all the cases I missed - PTAL

---

Review status: 4 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/opt/exec/execbuilder/testdata/scalar, line 335 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24369#-L8t2FcyDukYx9eCfPXo:-L8z5Op7-rhw95fefFFf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb7dca7bb34c500860893b2b5172833e5cd58bc7/pkg/sql/opt/exec/execbuilder/testdata/scalar#L335)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Can you add some tests here for the JSON operators ?, ?| and ?& ?
</blockquote></details>

Done.

---

*[pkg/sql/opt/norm/testdata/scalar, line 357 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24369#-L96Fq0A3ReIE2juNUJd:-L96Fq0A3ReIE2juNUJe:b130pjm) ([raw file](https://github.com/cockroachdb/cockroach/blob/1397fcb57a81d48628be7b151de17731c4d78e61/pkg/sql/opt/norm/testdata/scalar#L357)):*
> ```
>       ├── null [type=string]
>       ├── null [type=jsonb]
>       ├── null [type=unknown]
> ```

This looks odd - I'm not sure yet why this type fails to be inferred correctly when all the others are.

---

*[pkg/sql/opt/optbuilder/testdata/scalar, line 599 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24369#-L8t17gS4GSBu4EURhvW:-L96G3iv0tPGdf3oHrde:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bbc9eedcd31bbfcb4727afa76e79351615a1036/pkg/sql/opt/optbuilder/testdata/scalar#L599)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Can you add some other scalar expression that is still unsupported as a test of allow-unsupported?
</blockquote></details>

Done.

---

*[pkg/sql/opt/optbuilder/testdata/scalar, line 631 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24369#-L8t2lAyBTB0syKXYMuc:-L96GhCx1HwCRc7H0xS1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb7dca7bb34c500860893b2b5172833e5cd58bc7/pkg/sql/opt/optbuilder/testdata/scalar#L631)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Can you also add tests for ->, #> and #>>?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24369#-:-L96MgKGD5pxtronUbBg:b3dm54j)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 4 of 13 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/ops/scalar.opt, line 321 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24369#-L96OBO14GNO4aByr916:-L96OBO14GNO4aByr917:b-u5zefw) ([raw file](https://github.com/cockroachdb/cockroach/blob/071e4189d233aa5d6f51aa2f2b612b845ebfcb23/pkg/sql/opt/ops/scalar.opt#L321)):*
> ```
> }
> 
> [Scalar, Comparison]
> ```

At a high level, these aren't really comparisons. I wonder if it's a good idea to use a different tag for these (e.g. JsonOperator)? We wouldn't need the exceptions to existing Comparison rules.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24369#-:-L96PGGj3FkfWc5ojUN1:bnfp4nl)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 4 of 9 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/norm/testdata/scalar, line 357 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24369#-L96Fq0A3ReIE2juNUJd:-L96RNho8D9zHnI1Sjeb:b-er9qf1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1397fcb57a81d48628be7b151de17731c4d78e61/pkg/sql/opt/norm/testdata/scalar#L357)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

This looks odd - I'm not sure yet why this type fails to be inferred correctly when all the others are.
</blockquote></details>

It's also odd that it seems to think `'{}'::jsonb#>NULL` and `'{}'::jsonb#>>NULL` are the same thing (both column 14, unknown type). Does `symbolicExprStr` (in `sql/opt/optbuilder/util.go`) return the same thing for both expressions?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24369#-:-L96T35Z9g_35zbAsj2l:bnfp4nl)*

**Comment by justinj** [comment]
TFTRs!

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/norm/testdata/scalar, line 357 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24369#-L96Fq0A3ReIE2juNUJd:-L96b59M-6RPxErk67Tg:b35b100) ([raw file](https://github.com/cockroachdb/cockroach/blob/1397fcb57a81d48628be7b151de17731c4d78e61/pkg/sql/opt/norm/testdata/scalar#L357)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

It's also odd that it seems to think `'{}'::jsonb#>NULL` and `'{}'::jsonb#>>NULL` are the same thing (both column 14, unknown type). Does `symbolicExprStr` (in `sql/opt/optbuilder/util.go`) return the same thing for both expressions?
</blockquote></details>

Looked into this a bit and it looks like they're getting constant folded into "`NULL`" by the typechecking process and then considered a repeat render, which I guess is somewhat surprising, but not really incorrect, so I think it's not a big deal as far as this PR goes.

---

*[pkg/sql/opt/ops/scalar.opt, line 321 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24369#-L96OBO14GNO4aByr916:-L96QpaK3JSltnMlbA46:bsxb449) ([raw file](https://github.com/cockroachdb/cockroach/blob/071e4189d233aa5d6f51aa2f2b612b845ebfcb23/pkg/sql/opt/ops/scalar.opt#L321)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

At a high level, these aren't really comparisons. I wonder if it's a good idea to use a different tag for these (e.g. JsonOperator)? We wouldn't need the exceptions to existing Comparison rules.
</blockquote></details>

I guess that depends on how we define "comparison", it could be reasonable to consider them as "comparisons" if you think of "comparison" as "filter which can be directly translated into spans"? But perhaps that's a distinct concept which needs its own name. I'll leave that as an open question for now and merge this PR.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24369#-:-L9B-81f8_uhhEBGq9Z-:bz5mair)*

**Comment by rytaft** [comment]
*[pkg/sql/opt/norm/testdata/scalar, line 357 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24369#-L96Fq0A3ReIE2juNUJd:-L96RIEu40_yhWjLvl-t:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1397fcb57a81d48628be7b151de17731c4d78e61/pkg/sql/opt/norm/testdata/scalar#L357)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Looked into this a bit and it looks like they're getting constant folded into "`NULL`" by the typechecking process and then considered a repeat render, which I guess is somewhat surprising, but not really incorrect, so I think it's not a big deal as far as this PR goes.
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24369)*

**Pull request merged**
