### PR TITLE
parser: parse hash sharded unique constraints

### LINKED ISSUE #65475: sql/tests: TestRandomSyntaxGeneration failed
sql/tests.TestRandomSyntaxGeneration [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2998288&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=2998288&tab=artifacts#/) on master @ [c305dbcff1bcf621ae8edf058b220033c98d6526](https://github.com/cockroachdb/cockroach/commits/c305dbcff1bcf621ae8edf058b220033c98d6526):

```
    rsg_test.go:731: 3m40s of 5m0s: 937921 executions, 11158 successful
E210519 18:19:03.328927 2394414 kv/kvserver/queue.go:1093  [n1,split,s1,r6/1:/Table/{SystemCon…-11}] 71  unable to split [n1,s1,r6/1:/Table/{SystemCon…-11}] at key /Table/3/1/196: cannot split range at key /Table/3/1/196
E210519 18:19:05.640539 2420244 kv/kvserver/queue.go:1093  [n1,split,s1,r6/1:/Table/{SystemCon…-11}] 72  unable to split [n1,s1,r6/1:/Table/{SystemCon…-11}] at key /Table/3/1/196: cannot split range at key /Table/3/1/196
    rsg_test.go:731: 3m45s of 5m0s: 960266 executions, 11430 successful
E210519 18:19:07.345589 2439246 kv/kvserver/queue.go:1093  [n1,split,s1,r6/1:/Table/{SystemCon…-11}] 73  unable to split [n1,s1,r6/1:/Table/{SystemCon…-11}] at key /Table/3/1/196: cannot split range at key /Table/3/1/196
E210519 18:19:09.756249 2465701 kv/kvserver/queue.go:1093  [n1,split,s1,r6/1:/Table/{SystemCon…-11}] 74  unable to split [n1,s1,r6/1:/Table/{SystemCon…-11}] at key /Table/3/1/196: cannot split range at key /Table/3/1/196
E210519 18:19:11.268076 2482298 kv/kvserver/queue.go:1093  [n1,split,s1,r6/1:/Table/{SystemCon…-11}] 75  unable to split [n1,s1,r6/1:/Table/{SystemCon…-11}] at key /Table/3/1/196: cannot split range at key /Table/3/1/196
    rsg_test.go:731: 3m50s of 5m0s: 982103 executions, 11696 successful
E210519 18:19:13.478260 2505952 kv/kvserver/queue.go:1093  [n1,split,s1,r6/1:/Table/{SystemCon…-11}] 76  unable to split [n1,s1,r6/1:/Table/{SystemCon…-11}] at key /Table/3/1/196: cannot split range at key /Table/3/1/196
E210519 18:19:15.827264 2531085 kv/kvserver/queue.go:1093  [n1,split,s1,r6/1:/Table/{SystemCon…-11}] 77  unable to split [n1,s1,r6/1:/Table/{SystemCon…-11}] at key /Table/3/1/196: cannot split range at key /Table/3/1/196
    rsg_test.go:731: 3m55s of 5m0s: 1003707 executions, 11974 successful
E210519 18:19:18.030964 2553441 kv/kvserver/queue.go:1093  [n1,split,s1,r6/1:/Table/{SystemCon…-11}] 78  unable to split [n1,s1,r6/1:/Table/{SystemCon…-11}] at key /Table/3/1/196: cannot split range at key /Table/3/1/196
E210519 18:19:18.112003 2554443 kv/kvserver/queue.go:1093  [n1,split,s1,r6/1:/Table/{SystemCon…-11}] 79  unable to split [n1,s1,r6/1:/Table/{SystemCon…-11}] at key /Table/3/1/196: cannot split range at key /Table/3/1/196
E210519 18:19:19.298814 2566853 kv/kvserver/queue.go:1093  [n1,split,s1,r6/1:/Table/{SystemCon…-11}] 80  unable to split [n1,s1,r6/1:/Table/{SystemCon…-11}] at key /Table/3/1/196: cannot split range at key /Table/3/1/196
E210519 18:19:21.314221 2590798 kv/kvserver/queue.go:1093  [n1,split,s1,r6/1:/Table/{SystemCon…-11}] 81  unable to split [n1,s1,r6/1:/Table/{SystemCon…-11}] at key /Table/3/1/196: cannot split range at key /Table/3/1/196
    rsg_test.go:731: 4m0s of 5m0s: 1025143 executions, 12230 successful
E210519 18:19:23.654021 2618282 kv/kvserver/queue.go:1093  [n1,split,s1,r6/1:/Table/{SystemCon…-11}] 82  unable to split [n1,s1,r6/1:/Table/{SystemCon…-11}] at key /Table/3/1/196: cannot split range at key /Table/3/1/196
E210519 18:19:25.119152 2634609 kv/kvserver/queue.go:1093  [n1,split,s1,r6/1:/Table/{SystemCon…-11}] 83  unable to split [n1,s1,r6/1:/Table/{SystemCon…-11}] at key /Table/3/1/196: cannot split range at key /Table/3/1/196
E210519 18:19:25.163153 2635322 kv/kvserver/queue.go:1093  [n1,split,s1,r6/1:/Table/{SystemCon…-11}] 84  unable to split [n1,s1,r6/1:/Table/{SystemCon…-11}] at key /Table/3/1/196: cannot split range at key /Table/3/1/196
    rsg_test.go:731: 4m5s of 5m0s: 1048318 executions, 12533 successful
E210519 18:19:27.608395 2664407 kv/kvserver/queue.go:1093  [n1,split,s1,r6/1:/Table/{SystemCon…-11}] 85  unable to split [n1,s1,r6/1:/Table/{SystemCon…-11}] at key /Table/3/1/196: cannot split range at key /Table/3/1/196
E210519 18:19:29.212066 2683738 kv/kvserver/queue.go:1093  [n1,split,s1,r6/1:/Table/{SystemCon…-11}] 86  unable to split [n1,s1,r6/1:/Table/{SystemCon…-11}] at key /Table/3/1/196: cannot split range at key /Table/3/1/196
E210519 18:19:30.404779 2697417 kv/kvclient/kvcoord/txn_interceptor_committer.go:452  [-] 87  making txn commit explicit failed for "unnamed" meta={id=b7402754 pri=0.08700797 epo=0 ts=1621448370.402347790,0 min=1621448370.402347790,0 seq=2} lock=true stat=STAGING rts=1621448370.402347790,0 wto=false gul=1621448370.902347790,0 ifw=1: EndTxn hasSystemKey=true, but hasSystemConfigTrigger=false
    rsg_test.go:731: 4m10s of 5m0s: 1069272 executions, 12796 successful
E210519 18:19:35.413648 2701492 kv/kvclient/kvcoord/txn_interceptor_committer.go:452  [-] 88  making txn commit explicit failed for "unnamed" meta={id=eb19b66d pri=0.07518963 epo=0 ts=1621448375.410953655,0 min=1621448375.410953655,0 seq=2} lock=true stat=STAGING rts=1621448375.410953655,0 wto=false gul=1621448375.910953655,0 ifw=1: EndTxn hasSystemKey=true, but hasSystemConfigTrigger=false
    rsg_test.go:731: 4m15s of 5m0s: 1071288 executions, 12829 successful
    rsg_test.go:731: 4m20s of 5m0s: 1075511 executions, 12887 successful
    rsg_test.go:731: 4m25s of 5m0s: 1098674 executions, 13196 successful
    rsg_test.go:731: 4m30s of 5m0s: 1122321 executions, 13512 successful
E210519 18:19:51.681452 2837116 kv/kvserver/queue.go:1093  [n1,split,s1,r6/1:/Table/{SystemCon…-11}] 89  unable to split [n1,s1,r6/1:/Table/{SystemCon…-11}] at key /Table/3/1/249: cannot split range at key /Table/3/1/249
E210519 18:19:52.631105 2847533 kv/kvclient/kvcoord/txn_interceptor_committer.go:452  [-] 90  making txn commit explicit failed for "unnamed" meta={id=21cee266 pri=0.04313355 epo=0 ts=1621448392.629346764,0 min=1621448392.629346764,0 seq=2} lock=true stat=STAGING rts=1621448392.629346764,0 wto=false gul=1621448393.129346764,0 ifw=1: EndTxn hasSystemKey=true, but hasSystemConfigTrigger=false
    rsg_test.go:731: 4m35s of 5m0s: 1130056 executions, 13599 successful
E210519 18:19:57.642027 2850336 kv/kvclient/kvcoord/txn_interceptor_committer.go:452  [-] 91  making txn commit explicit failed for "unnamed" meta={id=7d5412c0 pri=0.00227117 epo=0 ts=1621448397.640313942,0 min=1621448397.640313942,0 seq=2} lock=true stat=STAGING rts=1621448397.640313942,0 wto=false gul=1621448398.140313942,0 ifw=1: EndTxn hasSystemKey=true, but hasSystemConfigTrigger=false
    rsg_test.go:731: 4m40s of 5m0s: 1133432 executions, 13629 successful
    rsg_test.go:731: 4m45s of 5m0s: 1150978 executions, 13879 successful
    rsg_test.go:731: 4m50s of 5m0s: 1174161 executions, 14176 successful
E210519 18:20:14.062961 2994054 kv/kvserver/queue.go:1093  [n1,split,s1,r6/1:/Table/{SystemCon…-11}] 92  unable to split [n1,s1,r6/1:/Table/{SystemCon…-11}] at key /Table/3/1/269: cannot split range at key /Table/3/1/269
E210519 18:20:15.489438 3010266 kv/kvserver/queue.go:1093  [n1,split,s1,r6/1:/Table/{SystemCon…-11}] 93  unable to split [n1,s1,r6/1:/Table/{SystemCon…-11}] at key /Table/3/1/269: cannot split range at key /Table/3/1/269
    rsg_test.go:731: 4m55s of 5m0s: 1197564 executions, 14417 successful
E210519 18:20:17.237680 3030503 kv/kvserver/queue.go:1093  [n1,split,s1,r6/1:/Table/{SystemCon…-11}] 94  unable to split [n1,s1,r6/1:/Table/{SystemCon…-11}] at key /Table/3/1/269: cannot split range at key /Table/3/1/269
E210519 18:20:19.772351 3058624 kv/kvserver/queue.go:1093  [n1,split,s1,r6/1:/Table/{SystemCon…-11}] 95  unable to split [n1,s1,r6/1:/Table/{SystemCon…-11}] at key /Table/3/1/269: cannot split range at key /Table/3/1/269
E210519 18:20:21.056237 3073801 kv/kvclient/kvcoord/txn_interceptor_committer.go:452  [-] 96  making txn commit explicit failed for "unnamed" meta={id=b7de4059 pri=0.04126364 epo=0 ts=1621448421.054842535,0 min=1621448421.054842535,0 seq=2} lock=true stat=STAGING rts=1621448421.054842535,0 wto=false gul=1621448421.554842535,0 ifw=1: EndTxn hasSystemKey=true, but hasSystemConfigTrigger=false
    rsg_test.go:731: 5m0s of 5m0s: 1218918 executions, 14677 successful
E210519 18:20:26.073704 3075724 kv/kvclient/kvcoord/txn_interceptor_committer.go:452  [-] 97  making txn commit explicit failed for "unnamed" meta={id=6dbae37d pri=0.01573656 epo=0 ts=1621448426.072800028,0 min=1621448426.072800028,0 seq=2} lock=true stat=STAGING rts=1621448426.072800028,0 wto=false gul=1621448426.572800028,0 ifw=1: EndTxn hasSystemKey=true, but hasSystemConfigTrigger=false
    rsg_test.go:731: 5m5s of 5m0s: 1218921 executions, 14679 successful
    rsg_test.go:767: 1218922 executions, 14680 successful
    rsg_test.go:775: cannot parse output of Format: sql="PREPARE EXECUTION AS IMPORT TABLE INDEX . STRING ( UNIQUE INDEX ( SESSION_USER ASC ) USING HASH WITH BUCKET_COUNT = DEFAULT ) TIME DATA ( PLACEHOLDER ) WITH 'string' = PLACEHOLDER", formattedSQL="PREPARE execution AS IMPORT TABLE \"index\".\"string\" (UNIQUE (current_user() ASC) USING HASH WITH BUCKET_COUNT = DEFAULT) TIME DATA ('placeholder') WITH \"string\" = 'placeholder'": at or near "using": syntax error
    rsg_test.go:232: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestRandomSyntaxGeneration796737888
--- FAIL: TestRandomSyntaxGeneration (305.93s)
```
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
make stressrace TESTS=TestRandomSyntaxGeneration PKG=./pkg/sql/tests TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```
</p>
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #65210 sql/tests: TestRandomSyntaxGeneration failed [C-test-failure O-robot branch-release-21.1]
- #63331 sql/tests: TestRandomSyntaxGeneration failed [C-test-failure O-robot branch-release-20.1]
</p>
</details>
<details><summary>Internal log</summary>
<p>

```
mjibson marked as alumn{us/a}; resolving to rafiss instead
```
</p>
</details>

/cc @cockroachdb/sql-queries rafiss
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRandomSyntaxGeneration.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by mgartner**
The parser now parses hash-sharded unique constraints in the formats
below.

    CREATE TABLE t (
      a INT,
      UNIQUE (a) USING HASH WITH BUCKET_COUNT = 10,
      CONSTRAINT d UNIQUE (a) USING HASH WITH BUCKET_COUNT = 10
    )

With this change, these types of table constraints can round-trip after
AST pretty-printing.

Fixes #65475

There is no release note because hash-sharded indexes are gated behind
an experimental feature flag.

Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
I wonder how often this comes up. Generally things you want to be unique that aren't the primary key tend not to be sequential. How do you feel about not putting it into the text documentation (it'll still end up the syntax diagrams). The text documentation today is far from complete IIRC. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65788#-:-MaitZ_xCkDOJ-qKDHlH:bmdapad)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by mgartner** [comment]
I need to disallow hash-sharded `UNIQUE WITHOUT INDEX` constraints:

```
demo@127.0.0.1:26257/defaultdb> SET experimental_enable_unique_without_index_constraints = true
;
SET

Time: 0ms total (execution 0ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> create table t (a int, unique without index (a) using hash with bucket_count = 10);
CREATE TABLE

Time: 3ms total (execution 3ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> show create table t;
  table_name |                      create_statement
-------------+--------------------------------------------------------------
  t          | CREATE TABLE public.t (
             |     a INT8 NULL,
             |     rowid INT8 NOT VISIBLE NOT NULL DEFAULT unique_rowid(),
             |     CONSTRAINT "primary" PRIMARY KEY (rowid ASC),
             |     FAMILY "primary" (a, rowid),
             |     CONSTRAINT unique_a UNIQUE WITHOUT INDEX (a)
             | )
(1 row)

Time: 7ms total (execution 6ms / network 0ms)
```

**Review by ajwerner — COMMENTED** [review]
> I need to disallow hash-sharded UNIQUE WITHOUT INDEX constraints:

:thumbsup: 

What's motivating adding support for this syntax? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65788#-:-Maj0w6F0_Dz5EDtkxKL:b-py9zsc)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by mgartner** [comment]
> What's motivating adding support for this syntax?

Which syntax?

`UNIQUE WITHOUT INDEX` was added in 21.1 to aid testing multi-region functionality in the optimizer. It is gated behind an experimental feature flag.

The motivation for `UNIQUE (a) USING HASH WITH BUCKET_COUNT = 10` is to make `UNIQUE INDEX (a) USING HASH WITH BUCKET_COUNT = 10` round-trippable. If that's not clear from the commit and linked issue, let me know.

**Comment by ajwerner** [comment]
> > What's motivating adding support for this syntax?
> 
> Which syntax?
> 
> `UNIQUE WITHOUT INDEX` was added in 21.1 to aid testing multi-region functionality in the optimizer. It is gated behind an experimental feature flag.
> 
> The motivation for `UNIQUE (a) USING HASH WITH BUCKET_COUNT = 10` is to make `UNIQUE INDEX (a) USING HASH WITH BUCKET_COUNT = 10` round-trippable. If that's not clear from the commit and linked issue, let me know.

I don't think I understand. Today we don't support `UNIQUE (a) USING HASH WITH BUCKET_COUNT = 10`; it fails to parse. We do support `UNIQUE INDEX (a) USING HASH WITH BUCKET_COUNT = 10`. That does seem to round-trip:

```
 CREATE TABLE t (
  a INT,
  UNIQUE INDEX (a) USING HASH WITH BUCKET_COUNT = 10
  );
  
  
 HINT: try \h CREATE TABLE
root@localhost:26257/defaultdb> SELECT create_statement FROM [SHOW CREATE TABLE t];
                                                           create_statement
---------------------------------------------------------------------------------------------------------------------------------------
  CREATE TABLE public.t (
      a INT8 NULL,
      crdb_internal_a_shard_10 INT4 NOT VISIBLE NOT NULL AS (mod(fnv32(COALESCE(CAST(a AS STRING), '':::STRING)), 10:::INT8)) STORED,
      rowid INT8 NOT VISIBLE NOT NULL DEFAULT unique_rowid(),
      CONSTRAINT "primary" PRIMARY KEY (rowid ASC),
      UNIQUE INDEX t_a_key (a ASC) USING HASH WITH BUCKET_COUNT = 10,
      FAMILY "primary" (a, crdb_internal_a_shard_10, rowid)
  )
(1 row)

root@localhost:26257/defaultdb> DROP TABLE t;
DROP TABLE

Time: 516ms total (execution 516ms / network 0ms)

root@localhost:26257/defaultdb> CREATE TABLE public.t (
      a INT8 NULL,
      crdb_internal_a_shard_10 INT4 NOT VISIBLE NOT NULL AS (mod(fnv32(COALESCE(CAST(a AS STRING), '':::STRING)), 10:::INT8)) STORED,
      rowid INT8 NOT VISIBLE NOT NULL DEFAULT unique_rowid(),
      CONSTRAINT "primary" PRIMARY KEY (rowid ASC),
      UNIQUE INDEX t_a_key (a ASC) USING HASH WITH BUCKET_COUNT = 10,
      FAMILY "primary" (a, crdb_internal_a_shard_10, rowid)
  )
;
CREATE TABLE

Time: 115ms total (execution 115ms / network 0ms)

root@localhost:26257/defaultdb> SELECT create_statement FROM [SHOW CREATE TABLE t];
                                                           create_statement
---------------------------------------------------------------------------------------------------------------------------------------
  CREATE TABLE public.t (
      a INT8 NULL,
      crdb_internal_a_shard_10 INT4 NOT VISIBLE NOT NULL AS (mod(fnv32(COALESCE(CAST(a AS STRING), '':::STRING)), 10:::INT8)) STORED,
      rowid INT8 NOT VISIBLE NOT NULL DEFAULT unique_rowid(),
      CONSTRAINT "primary" PRIMARY KEY (rowid ASC),
      UNIQUE INDEX t_a_key (a ASC) USING HASH WITH BUCKET_COUNT = 10,
      FAMILY "primary" (a, crdb_internal_a_shard_10, rowid)
  )
```

**Comment by mgartner** [comment]
`UNIQUE INDEX (a) USING HASH WITH BUCKET_COUNT = 10` round-trips through a descriptor and `SHOW CREATE TABLE`:

```
 SQL ──► AST ──► TABLE DESCRIPTOR
  ▲                       │
  └── SHOW CREATE TABLE ──┘
```

But it does not round-trip when pretty printing an AST:

```
SQL ─────────────► AST
 ▲                  │
 └── PRETTY PRINT ──┘
```

Because the pretty printer omits the `INDEX`, the pretty-printed SQL is:

```
CREATE TABLE foo (
    a INT8,
    UNIQUE (a) USING HASH WITH BUCKET_COUNT =  10
)
```

We had no tests for this, so it wasn't caught until SQLSmith produced it.

Given that `UNIQUE` constraints and `UNIQUE INDEX`es are synonymous in CRDB, I think it's good to support both syntaxes for creating unique hash-sharded indexes.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65788#-:-MakhN9SExglTZIqjM5l:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Review by ajwerner — COMMENTED** [review]
Got it. I think this runs pretty deep.

While they are functionally roughly the same, they are not identical.  I suspect part of this rough edge is that postgres doesn't allow directly adding indexes inside of the `CREATE TABLE` statement. I really don't like the idea that we forget about whether it was a unique index vs unique constraint in just this context. I don't think there was any intention behind that. Also, while we're tracking this state, we seem to be losing it when serializing back to SQL. That seems like a bug.

The main thing that makes them not the same is that you can't use `ALTER TABLE ... DROP CONSTRAINT` on the index and you can't use `DROP INDEX` on the constraint. 

```
root@localhost:26257/test> CREATE TABLE t (i INT PRIMARY KEY, j INT, k INT);
CREATE TABLE

root@localhost:26257/test> ALTER TABLE t ADD CONSTRAINT c UNIQUE (j);
ALTER TABLE

root@localhost:26257/test> CREATE UNIQUE INDEX idx ON t(k);
CREATE INDEX

root@localhost:26257/test> ALTER TABLE t DROP CONSTRAINT idx;
ERROR: unimplemented: cannot drop UNIQUE constraint "idx" using ALTER TABLE DROP CONSTRAINT, use DROP INDEX CASCADE instead
SQLSTATE: 0A000
HINT: You have attempted to use a feature that is not yet implemented.
See: https://go.crdb.dev/issue-v/42840/v21.2

root@localhost:26257/test> DROP INDEX t@c;
ERROR: index "c" is in use as unique constraint
SQLSTATE: 2BP01
HINT: use CASCADE if you really want to drop it.
```

I typed up a draft of what I have in mind (but have not attempted testing, it's late): https://github.com/cockroachdb/cockroach/pull/65825

Please give the above two commits a look and see how they make you feel. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65788#-:-MakzL-YB4BANlMMMkfK:b-5bexph)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by mgartner** [comment]
Thanks for the addition context @ajwerner! I like the approach in #65825, so I'll close this.

**Pull request closed without merging**
