### PR TITLE
storage: allow transactions to run at a lower sequence

### PR DESCRIPTION
**Pull request by ridwanmsharif**
Continuing off https://github.com/cockroachdb/cockroach/pull/32688, final part of https://github.com/cockroachdb/cockroach/issues/5861#issuecomment-425990038.

Adds support to have transactions run at a lower sequence
at a given key. It asserts the value it computes with the
value written for the sequence in the intent history instead
or returning a retry-able error.

Release note: None

### CODE REVIEW

**Review by nvb — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33001)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 3429 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTPTP_c6jz3N0cp41rd:-LTPTP_dAfVQV88yetXW:bkgyaha) ([raw file](https://github.com/cockroachdb/cockroach/blob/fee6c91eb0943618f732ffb241851506beaa2042/pkg/storage/replica.go#L3429)):*
For other reviewers - Ridwan and I discussed this and decided it was fine to remove the assertion. 

> I added that assertion in when trying to smoke out any operations that would violate the invariants necessary for transactional pipelining to work properly. Now that everything’s in, I think I’d be ok with removing the assertion entirely
> It already isn’t foolproof
___
*[pkg/storage/replica_test.go, line 2894 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTPTvzr4YWUQ5jSDI9S:-LTPTvzr4YWUQ5jSDI9T:b-ewbxx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd24a5ef460fc004ab937b4b2daec534e97b24a3/pkg/storage/replica_test.go#L2894)):*
> ```Go
> }
> 
> // TestReplicaAbortSpanStoredTxnRetryError verifies that if a cached
> ```

Does this test need a name and a new description?
___
*[pkg/storage/engine/mvcc.go, line 1238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTPVIHzA-FfPAZ-8oWe:-LTPVIHzA-FfPAZ-8oWf:bg7fran) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd24a5ef460fc004ab937b4b2daec534e97b24a3/pkg/storage/engine/mvcc.go#L1238)):*
> ```Go
> 				(txn.Sequence < meta.Txn.Sequence ||
> 					(txn.Sequence == meta.Txn.Sequence &&
> 						txn.DeprecatedBatchIndex <= meta.Txn.DeprecatedBatchIndex)) {
> ```

If you feel up to it, we can remove all references to this `DeprecatedBatchIndex` now.

Then we can make this condition `if txn.Epoch == meta.Txn.Epoch && txn.Sequence <= meta.Txn.Sequence`.
___
*[pkg/storage/engine/mvcc.go, line 1241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTPWPDo2ZdQHslDl9LJ:-LTPWPDo2ZdQHslDl9LK:b-gj9wyx) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd24a5ef460fc004ab937b4b2daec534e97b24a3/pkg/storage/engine/mvcc.go#L1241)):*
> ```Go
> 				// Find the previous value at this key so the current value can be computed.
> 				// If a previous intent value doesn't exist, get the last versioned value
> 				// and apply the valueFn where necessary.
> ```

Feel free to expand this comment past what we're doing. Explain why we're doing this too! It's a little non-intuitive if you stumble into it.
___
*[pkg/storage/engine/mvcc.go, line 1243 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTPXCjo66BcBfMZFdmt:-LTPXCjo66BcBfMZFdmu:b-fgwjn) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd24a5ef460fc004ab937b4b2daec534e97b24a3/pkg/storage/engine/mvcc.go#L1243)):*
> ```Go
> 				// and apply the valueFn where necessary.
> 				prevSeq, prevValueWritten := meta.GetPrevIntentSeq(txn.Sequence)
> 				if prevValueWritten {
> ```

Add comments to these cases that explain what they logically mean. Comments like:

```
// There was an intent on this key at a lower sequence number that this write.

and

// This was the first write in the transaction to this key.
```

As a more macro level nit, I this would be easier to narrate in comments if you did `writtenValue, found := meta.GetIntentValue(txn.Sequence)` first. The flow would then be:
1. find the result of this write, erroring if it isn't found
2. find the value that preceded it
3. verify that a re-evaluation would end up with the same result
4. conclude that nothing needs to be done because we're idempotent!

This reveals that looking at the previous value is only necessary if `valueFn != nil`.
___
*[pkg/storage/engine/mvcc.go, line 1263 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTPYpby8g_rsFjfd4D1:-LTPYpby8g_rsFjfd4D2:b-8m6i2y) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd24a5ef460fc004ab937b4b2daec534e97b24a3/pkg/storage/engine/mvcc.go#L1263)):*
> ```Go
> 						var exVal *roachpb.Value
> 						var err error
> 						if exVal, _, _, err = mvccGetInternal(
> ```

Explain why this is inconsistent. You mentioned on slack that you thought that was incorrect. I'm curious why. It seems right to me.
___
*[pkg/storage/engine/mvcc.go, line 1264 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTPZ4j38yngRZpYayN3:-LTPZ4j38yngRZpYayN4:bxzoyvm) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd24a5ef460fc004ab937b4b2daec534e97b24a3/pkg/storage/engine/mvcc.go#L1264)):*
> ```Go
> 						var err error
> 						if exVal, _, _, err = mvccGetInternal(
> 							ctx, iter, metaKey, timestamp, false /* consistent */, safeValue, txn, getBuf); err != nil {
> ```

Can we pass `unsafeValue` here?
___
*[pkg/storage/engine/mvcc.go, line 1274 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTPYRBHEJIou-5CECpu:-LTPYRBHEJIou-5CECpv:bbbnmkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd24a5ef460fc004ab937b4b2daec534e97b24a3/pkg/storage/engine/mvcc.go#L1274)):*
> ```Go
> 				}
> 				// Assert that the value computed is the same as the value written previously.
> 				writtenValue, found := meta.GetIntentValue(txn.Sequence)
> ```

Does this handle the case where we replay the last intent written, before it makes it into the intent history?
___
*[pkg/storage/engine/mvcc_test.go, line 3303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTPU-p-8YzXESu9fnQN:-LTPU-p00xk_9I1JaaKk:b8z8la1) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd24a5ef460fc004ab937b4b2daec534e97b24a3/pkg/storage/engine/mvcc_test.go#L3303)):*
> ```Go
> 		sequence   int32
> 		batchIndex int32
> 		expRetry   bool
> ```

Looks like we never retry anymore, which is exactly what we want!

There are two new variants of tests that we need, for the "different value after recomputing" error and for the "missing an intent with lower sequence" error.
___
*[pkg/storage/engine/enginepb/mvcc.go, line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTPUOmo2DEx_jqYxpAc:-LTPUOmo2DEx_jqYxpAd:bcl5qbs) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd24a5ef460fc004ab937b4b2daec534e97b24a3/pkg/storage/engine/enginepb/mvcc.go#L140)):*
> ```Go
> 
> // GetPrevIntentSeq goes through the intent history and finds the previous
> // intents sequence number given the current sequence
> ```

"intent's"

Also, period at the end.
___
*[pkg/storage/engine/enginepb/mvcc.go, line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTPUnL5Auj70KjmEIjy:-LTPUnL5Auj70KjmEIjz:b-uvzhpc) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd24a5ef460fc004ab937b4b2daec534e97b24a3/pkg/storage/engine/enginepb/mvcc.go#L142)):*
> ```Go
> // intents sequence number given the current sequence
> func (meta *MVCCMetadata) GetPrevIntentSeq(seq int32) (prevSeq int32, found bool) {
> 	for i := len(meta.IntentHistory) - 1; i > 0; i-- {
> ```

Think it's worth performing a binary search here?
___
*[pkg/storage/engine/enginepb/mvcc.go, line 145 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTPV9EW-snp5kImXNTu:-LTPV9EW-snp5kImXNTv:bijenys) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd24a5ef460fc004ab937b4b2daec534e97b24a3/pkg/storage/engine/enginepb/mvcc.go#L145)):*
> ```Go
> 		intent := meta.IntentHistory[i]
> 		if seq == intent.Sequence {
> 			prevSeq = meta.IntentHistory[i-1].Sequence
> ```

nit: why not just return here?
___
*[pkg/storage/engine/enginepb/mvcc.go, line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTPVC2O8o49T3QtBxDt:-LTPVC2P7D1tBeOy-X2c:buodkiy) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd24a5ef460fc004ab937b4b2daec534e97b24a3/pkg/storage/engine/enginepb/mvcc.go#L158)):*
> ```Go
> 	for _, intent := range meta.IntentHistory {
> 		if seq == intent.Sequence {
> 			found = true
> ```

Same nit.

**Review by ridwanmsharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33001)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 3429 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTPTP_c6jz3N0cp41rd:-LTUILio90xWV7b4DIe0:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/fee6c91eb0943618f732ffb241851506beaa2042/pkg/storage/replica.go#L3429)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

For other reviewers - Ridwan and I discussed this and decided it was fine to remove the assertion. 

> I added that assertion in when trying to smoke out any operations that would violate the invariants necessary for transactional pipelining to work properly. Now that everything’s in, I think I’d be ok with removing the assertion entirely
> It already isn’t foolproof
</blockquote></details>

Ack.
___
*[pkg/storage/replica_test.go, line 2894 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTPTvzr4YWUQ5jSDI9S:-LTUINab6wT2LvrheRD6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd24a5ef460fc004ab937b4b2daec534e97b24a3/pkg/storage/replica_test.go#L2894)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does this test need a name and a new description?
</blockquote></details>

Done.
___
*[pkg/storage/engine/mvcc.go, line 1238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTPVIHzA-FfPAZ-8oWe:-LTUIPV61twVz4VLRXib:bxg0a61) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd24a5ef460fc004ab937b4b2daec534e97b24a3/pkg/storage/engine/mvcc.go#L1238)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

If you feel up to it, we can remove all references to this `DeprecatedBatchIndex` now.

Then we can make this condition `if txn.Epoch == meta.Txn.Epoch && txn.Sequence <= meta.Txn.Sequence`.
</blockquote></details>

Done. See 2nd commit.
___
*[pkg/storage/engine/mvcc.go, line 1241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTPWPDo2ZdQHslDl9LJ:-LTUISo4-TBXbvq69FOB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd24a5ef460fc004ab937b4b2daec534e97b24a3/pkg/storage/engine/mvcc.go#L1241)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Feel free to expand this comment past what we're doing. Explain why we're doing this too! It's a little non-intuitive if you stumble into it.
</blockquote></details>

Done.
___
*[pkg/storage/engine/mvcc.go, line 1243 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTPXCjo66BcBfMZFdmt:-LTUIU182VpwxF1oyRZq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd24a5ef460fc004ab937b4b2daec534e97b24a3/pkg/storage/engine/mvcc.go#L1243)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Add comments to these cases that explain what they logically mean. Comments like:

```
// There was an intent on this key at a lower sequence number that this write.

and

// This was the first write in the transaction to this key.
```

As a more macro level nit, I this would be easier to narrate in comments if you did `writtenValue, found := meta.GetIntentValue(txn.Sequence)` first. The flow would then be:
1. find the result of this write, erroring if it isn't found
2. find the value that preceded it
3. verify that a re-evaluation would end up with the same result
4. conclude that nothing needs to be done because we're idempotent!

This reveals that looking at the previous value is only necessary if `valueFn != nil`.
</blockquote></details>

Done.
___
*[pkg/storage/engine/mvcc.go, line 1263 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTPYpby8g_rsFjfd4D1:-LTUIVqcBovjYjrkLLik:b-3ny6wd) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd24a5ef460fc004ab937b4b2daec534e97b24a3/pkg/storage/engine/mvcc.go#L1263)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Explain why this is inconsistent. You mentioned on slack that you thought that was incorrect. I'm curious why. It seems right to me.
</blockquote></details>

Elaborated here. using `nil` for the `txn` param tho. Could you confirm if this is correct though? Seems alright to me.
___
*[pkg/storage/engine/mvcc.go, line 1264 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTPZ4j38yngRZpYayN3:-LTUIjuyCom98Qv6Kn0E:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd24a5ef460fc004ab937b4b2daec534e97b24a3/pkg/storage/engine/mvcc.go#L1264)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we pass `unsafeValue` here?
</blockquote></details>

Done.
___
*[pkg/storage/engine/mvcc.go, line 1274 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTPYRBHEJIou-5CECpu:-LTUIlS243XVIN0ja6eK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd24a5ef460fc004ab937b4b2daec534e97b24a3/pkg/storage/engine/mvcc.go#L1274)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does this handle the case where we replay the last intent written, before it makes it into the intent history?
</blockquote></details>

Done.
___
*[pkg/storage/engine/mvcc_test.go, line 3303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTPU-p-8YzXESu9fnQN:-LTUIp8yE39VNqb43Xuu:bujoljy) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd24a5ef460fc004ab937b4b2daec534e97b24a3/pkg/storage/engine/mvcc_test.go#L3303)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Looks like we never retry anymore, which is exactly what we want!

There are two new variants of tests that we need, for the "different value after recomputing" error and for the "missing an intent with lower sequence" error.
</blockquote></details>

Done. See the test I added.
___
*[pkg/storage/engine/enginepb/mvcc.go, line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTPUOmo2DEx_jqYxpAc:-LTUIt3VBFmoN1AMf3Ei:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd24a5ef460fc004ab937b4b2daec534e97b24a3/pkg/storage/engine/enginepb/mvcc.go#L140)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"intent's"

Also, period at the end.
</blockquote></details>

Done.
___
*[pkg/storage/engine/enginepb/mvcc.go, line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTPUnL5Auj70KjmEIjy:-LTUItyq-GJvvIxIz8Mw:bey9eof) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd24a5ef460fc004ab937b4b2daec534e97b24a3/pkg/storage/engine/enginepb/mvcc.go#L142)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Think it's worth performing a binary search here?
</blockquote></details>

Well its always tiny, may not be worth it but lets leave no stone unturned. Done.
___
*[pkg/storage/engine/enginepb/mvcc.go, line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTPVC2O8o49T3QtBxDt:-LTUJ3_Z4C1A3vIsNSRX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd24a5ef460fc004ab937b4b2daec534e97b24a3/pkg/storage/engine/enginepb/mvcc.go#L158)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Same nit.
</blockquote></details>

Done.

**Review by nvb — CHANGES_REQUESTED** [review]
Just nits now, the logic all looks good.

@tbg might be interested in reviewing this too.

> Reviewed 4 of 5 files at r2, 6 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-:-LTUlZLgE48UAWhIh2TO:b-6k6uy5)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 6380 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTUm6ie55YMQOUc3PCn:-LTUm6ie55YMQOUc3PCo:b-ia19it) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d78871aeeedbd4e0399306e0299bad353da48d3/pkg/storage/replica.go#L6380)):*
> ```Go
> 				// the TxnMeta, which is stored as part of an intent.
> 				ba.Txn.Sequence = seqNum
> 			} else {
> ```

I think we can remove this entire `else` case and `DisallowUnsequencedTransactionalWrites`.
___
*[pkg/storage/engine/mvcc.go, line 1238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTPVIHzA-FfPAZ-8oWe:-LTUjuHv0SdyVigSjsGV:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd24a5ef460fc004ab937b4b2daec534e97b24a3/pkg/storage/engine/mvcc.go#L1238)):*
<details><summary><i>Previously, ridwanmsharif (Ridwan Sharif) wrote…</i></summary><blockquote>

Done. See 2nd commit.
</blockquote></details>

:thumbsup: 
___
*[pkg/storage/engine/mvcc.go, line 1241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTPWPDo2ZdQHslDl9LJ:-LTUjwFu0kMy93el2OFg:b-fc6ebk) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd24a5ef460fc004ab937b4b2daec534e97b24a3/pkg/storage/engine/mvcc.go#L1241)):*
<details><summary><i>Previously, ridwanmsharif (Ridwan Sharif) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nice comment!
___
*[pkg/storage/engine/mvcc.go, line 1263 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTPYpby8g_rsFjfd4D1:-LTUkZQJD7-Ehg-GL5lc:bevjrvf) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd24a5ef460fc004ab937b4b2daec534e97b24a3/pkg/storage/engine/mvcc.go#L1263)):*
<details><summary><i>Previously, ridwanmsharif (Ridwan Sharif) wrote…</i></summary><blockquote>

Elaborated here. using `nil` for the `txn` param tho. Could you confirm if this is correct though? Seems alright to me.
</blockquote></details>

Yep, it's good.
___
*[pkg/storage/engine/mvcc.go, line 1239 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTUkjyi7D5HCPSahKrX:-LTUkjyi7D5HCPSahKrY:bk6fv95) ([raw file](https://github.com/cockroachdb/cockroach/blob/79a357a80ee4af6de923a4c3048bf9d5c867f7a8/pkg/storage/engine/mvcc.go#L1239)):*
> ```Go
> 					(txn.Sequence == meta.Txn.Sequence &&
> 						txn.DeprecatedBatchIndex <= meta.Txn.DeprecatedBatchIndex)) {
> 				// Since transactions should be idempotent, we must be particularly careful
> ```

Do you think all of this logic should be pulled into a separate function? It would allow you to test the error cases more closely.
___
*[pkg/storage/engine/mvcc.go, line 1252 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTUjW_w3gOnrnzHsFYW:-LTUjW_w3gOnrnzHsFYX:b-lk5szh) ([raw file](https://github.com/cockroachdb/cockroach/blob/79a357a80ee4af6de923a4c3048bf9d5c867f7a8/pkg/storage/engine/mvcc.go#L1252)):*
> ```Go
> 				// Ensure all intents are found and that the values are always accurate for
> 				// transactional idempotency.
> 				writtenValue, found := meta.GetIntentValue(txn.Sequence)
> ```

Let's either not call this method at all when `txn.Sequence == meta.Txn.Sequence` or assert that `found == false` when `txn.Sequence == meta.Txn.Sequence`. FWIW, I don't really care about the cost of calling `GetIntentValue`, I'm just concerned about how this reads and how understandable it is.
___
*[pkg/storage/engine/mvcc.go, line 1283 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTUkDQn9POw6SlK2ZaS:-LTUkDQn9POw6SlK2ZaT:bri2xvv) ([raw file](https://github.com/cockroachdb/cockroach/blob/79a357a80ee4af6de923a4c3048bf9d5c867f7a8/pkg/storage/engine/mvcc.go#L1283)):*
> ```Go
> 						prevVal, _ := meta.GetIntentValue(prevSeq)
> 						// TODO(ridwanmsharif): Confirm the timestamp is correct.
> 						value, err = valueFn(&roachpb.Value{RawBytes: prevVal, Timestamp: txn.Timestamp})
> ```

This is interesting. Do we ever use the timestamp? If not, I'd leave it out entirely.
___
*[pkg/storage/engine/mvcc.go, line 1316 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTUkeyPAupbi8RLgQR_:-LTUkeyPAupbi8RLgQRa:bih5be9) ([raw file](https://github.com/cockroachdb/cockroach/blob/79a357a80ee4af6de923a4c3048bf9d5c867f7a8/pkg/storage/engine/mvcc.go#L1316)):*
> ```Go
> 				// written.
> 				if !bytes.Equal(value, writtenValue) {
> 					return errors.Errorf("transaction %s has a different value %+v after recomputing from what was written: %+v",
> ```

Include the sequence number in this error.
___
*[pkg/storage/engine/mvcc.go, line 1235 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTUluNiAWI0o10Mg3qJ:-LTUluNiAWI0o10Mg3qK:b-kp9jx1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d78871aeeedbd4e0399306e0299bad353da48d3/pkg/storage/engine/mvcc.go#L1235)):*
> ```Go
> 				return errors.Errorf("put with epoch %d came after put with epoch %d in txn %s",
> 					txn.Epoch, meta.Txn.Epoch, txn.ID)
> 			} else if txn.Epoch == meta.Txn.Epoch &&
> ```

minor nit: can we remove the line wrap now?
___
*[pkg/storage/engine/mvcc_test.go, line 4435 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTUl5kq6OEJU62_8pm5:-LTUl5kq6OEJU62_8pm6:b2hl805) ([raw file](https://github.com/cockroachdb/cockroach/blob/79a357a80ee4af6de923a4c3048bf9d5c867f7a8/pkg/storage/engine/mvcc_test.go#L4435)):*
> ```Go
> 	// Lay down an intent without increasing the sequence but with a different value.
> 	if err := MVCCPut(ctx, engine, nil, key, ts1, newValue, txn); err != nil {
> 		if !strings.Contains(err.Error(), "has a different value") {
> ```

Replace these type of assertions with `testutils.IsError`/`testutils.IsPError`.
___
*[pkg/storage/engine/enginepb/mvcc.go, line 148 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTUlOr_CAoBvC6-A-l6:-LTUlOr_CAoBvC6-A-l7:b1mft09) ([raw file](https://github.com/cockroachdb/cockroach/blob/79a357a80ee4af6de923a4c3048bf9d5c867f7a8/pkg/storage/engine/enginepb/mvcc.go#L148)):*
> ```Go
> 	})
> 	if index > 0 && index < len(meta.IntentHistory) &&
> 		meta.IntentHistory[index].Sequence == seq {
> ```

Should we require that a sequence equal to `seq` exist? Seems a little overly restrictive.

**Review by ridwanmsharif — COMMENTED** [review]
TFTR! Fixed all the nits!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-:-LTVXei807ZORPAKInm4:b-qydso7)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 6380 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTUm6ie55YMQOUc3PCn:-LTVO3wY2CeZcelWRhYc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d78871aeeedbd4e0399306e0299bad353da48d3/pkg/storage/replica.go#L6380)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think we can remove this entire `else` case and `DisallowUnsequencedTransactionalWrites`.
</blockquote></details>

Done.
___
*[pkg/storage/engine/mvcc.go, line 1263 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTPYpby8g_rsFjfd4D1:-LTVCO9T5HwjxED21EFe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd24a5ef460fc004ab937b4b2daec534e97b24a3/pkg/storage/engine/mvcc.go#L1263)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yep, it's good.
</blockquote></details>

Done.
___
*[pkg/storage/engine/mvcc.go, line 1239 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTUkjyi7D5HCPSahKrX:-LTVM8v_7CQ-Iv5-5Hzz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/79a357a80ee4af6de923a4c3048bf9d5c867f7a8/pkg/storage/engine/mvcc.go#L1239)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you think all of this logic should be pulled into a separate function? It would allow you to test the error cases more closely.
</blockquote></details>

Done.
___
*[pkg/storage/engine/mvcc.go, line 1252 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTUjW_w3gOnrnzHsFYW:-LTVGIZXEx2dCs9Q1cO-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/79a357a80ee4af6de923a4c3048bf9d5c867f7a8/pkg/storage/engine/mvcc.go#L1252)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's either not call this method at all when `txn.Sequence == meta.Txn.Sequence` or assert that `found == false` when `txn.Sequence == meta.Txn.Sequence`. FWIW, I don't really care about the cost of calling `GetIntentValue`, I'm just concerned about how this reads and how understandable it is.
</blockquote></details>

Done.
___
*[pkg/storage/engine/mvcc.go, line 1283 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTUkDQn9POw6SlK2ZaS:-LTVICERBfEpVLdnxmCO:b-z6bamc) ([raw file](https://github.com/cockroachdb/cockroach/blob/79a357a80ee4af6de923a4c3048bf9d5c867f7a8/pkg/storage/engine/mvcc.go#L1283)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is interesting. Do we ever use the timestamp? If not, I'd leave it out entirely.
</blockquote></details>

Done. Just used for  `MVCCIncrement` so we can get rid of it.
___
*[pkg/storage/engine/mvcc.go, line 1316 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTUkeyPAupbi8RLgQR_:-LTVCoxBB3uvvBXVOKRX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/79a357a80ee4af6de923a4c3048bf9d5c867f7a8/pkg/storage/engine/mvcc.go#L1316)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Include the sequence number in this error.
</blockquote></details>

Done.
___
*[pkg/storage/engine/mvcc_test.go, line 4435 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTUl5kq6OEJU62_8pm5:-LTVEMIr5Qnd9NiRnO-k:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/79a357a80ee4af6de923a4c3048bf9d5c867f7a8/pkg/storage/engine/mvcc_test.go#L4435)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Replace these type of assertions with `testutils.IsError`/`testutils.IsPError`.
</blockquote></details>

Done.
___
*[pkg/storage/engine/enginepb/mvcc.go, line 148 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-LTUlOr_CAoBvC6-A-l6:-LTVEgdQ3dA-hwcNO0Jg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/79a357a80ee4af6de923a4c3048bf9d5c867f7a8/pkg/storage/engine/enginepb/mvcc.go#L148)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we require that a sequence equal to `seq` exist? Seems a little overly restrictive.
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33001#-:-LTYJPJg3JvQvryN1k5v:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
