### PR TITLE
UI: Display a warning when the cluster is unreachable

### LINKED ISSUE #4349: ui: display prominent warning when cluster is unreachable
Start a local dev cluster using `cockroach start --dev`. Visit the admin UI page. Now kill the cluster. The UI will eventually display a whole bunch of "No Data Available" messages, but it doesn't give a strong and clear indication that the cluster is unreachable.

### PR DESCRIPTION
**Pull request by maxlang**
Fixes #4349

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6042)

### CODE REVIEW

**Comment by maxlang** [comment]
screen shot 2016-04-13 at 1 58 42 pm

**Comment by petermattis** [comment]
That's attention grabbing. Nice!

**Comment by mrtracy** [comment]
Reviewed 2 of 7 files at r1.
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[ui/ts/models/health.ts, line 16 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6042#-KFGBWdZuG2LDRScLjNA:-KFGBWdZuG2LDRScLjNB:1049881451) ([raw file](https://github.com/cockroachdb/cockroach/blob/19c20f32b1897c949e906524912c94d552e691b4/ui/ts/models/health.ts#L16)):*
False by default?  Honestly, I don't think that this adds *anything* to our experience, especially with our support for a disconnected banner.  As far as I can tell, it's just going to flicker distractingly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6042)*

**Comment by mrtracy** [comment]
:lgtm:, although I would consider removing the "refreshing" indicator entirely for now.  In fact, I thought we already *had* removed it.  The user gets this banner as a notification if things aren't working, no need to pedantically inform them of every background request.

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6042#-:-KFGCspPgtkxseOwNHM8:796863515)*

**Comment by maxlang** [comment]
It's removed visually but the status is still present in the model.

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[ui/ts/models/health.ts, line 16 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6042#-KFGBWdZuG2LDRScLjNA:-KFGEPEoDAZtZg7axWTf:1420814580) ([raw file](https://github.com/cockroachdb/cockroach/blob/19c20f32b1897c949e906524912c94d552e691b4/ui/ts/models/health.ts#L16)):*
Currently it isn't displayed in the UI. `false` by default makes sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6042#-:-KFGFEY0tB9EwKnu7wE7:-1076766675)*

**Pull request merged**
