### PR TITLE
changefeedccl: protect system.comments and system.zones

### PR DESCRIPTION
**Pull request by stevendanna**
The catalog reader reads from system.descriptor, system.comments, and system.zones when reading a table descriptor from disk. We were only protecting system.descriptors.

Further, the test here previously wasn't testing anything because it was only forcing the GC-threshold to 1 second before read timestamp it was using.

Informs #128806

Release note (bug fix): Fix bug that could prevent a CHANGEFEED from being able to resume after being paused for prolonged period of time.

### CODE REVIEW

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130622)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

___
*[`pkg/ccl/changefeedccl/protected_timestamps.go` line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130622#-O6gum-C-0cKjmXWTBFv:-O6gum-C-0cKjmXWTBFw:bcmeqb9) ([raw file](https://github.com/cockroachdb/cockroach/blob/650199579861b78af7ec23cf287926c95a8090b2/pkg/ccl/changefeedccl/protected_timestamps.go#L49)):*
> ```Go
> 	// We protect system.descriptors because a changefeed needs all of the history
> 	// of table descriptors to version data.
> 	tablesToProtect := make(descpb.IDs, 0, targets.NumUniqueTables()+1)
> ```

fyi might want to consider updating this number 
___
*[`pkg/ccl/changefeedccl/protected_timestamps.go` line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130622#-O6gwAEt1dkX1lxOeEry:-O6gwAEt1dkX1lxOeErz:bnw4ybs) ([raw file](https://github.com/cockroachdb/cockroach/blob/650199579861b78af7ec23cf287926c95a8090b2/pkg/ccl/changefeedccl/protected_timestamps.go#L74)):*
> ```Go
> 		return nil
> 	})
> 	addTablePrefix(keys.DescriptorTableID)
> ```

should we also add it here?
___
*[`pkg/ccl/changefeedccl/protected_timestamps_test.go` line 510 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130622#-O6h9KLbBsCEJGJPYPMD:-O6h9KLbBsCEJGJPYPME:b-92v59x) ([raw file](https://github.com/cockroachdb/cockroach/blob/650199579861b78af7ec23cf287926c95a8090b2/pkg/ccl/changefeedccl/protected_timestamps_test.go#L510)):*
> ```Go
> 		row := sqlDB.QueryRow(t, fmt.Sprintf("SELECT range_id FROM [SHOW RANGES FROM TABLE %s.%s]", tableName, databaseName))
> 		var rangeID int64
> 		row.Scan(&rangeID)
> ```

Could there ever be more than one range?
___
*[`pkg/ccl/changefeedccl/protected_timestamps_test.go` line 513 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130622#-O6h8Qur8h9OG6greuUQ:-O6h8Qur8h9OG6greuUR:bjudk2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/650199579861b78af7ec23cf287926c95a8090b2/pkg/ccl/changefeedccl/protected_timestamps_test.go#L513)):*
> ```Go
> 		refreshPTSReaderCache(s.Clock().Now(), tableName, databaseName)
> 		t.Logf("enqueuing range %d for mvccGC", rangeID)
> 		sqlDB.Exec(t, `SELECT crdb_internal.kv_enqueue_replica($1, 'mvccGC', true)`, rangeID)
> ```

Wanted to double check my understanding: this would trigger a manual synchronous GC on the range for the tables and we would expect it to not affect the tables that are protected by the PTS?
___
*[`pkg/ccl/changefeedccl/protected_timestamps_test.go` line 520 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130622#-O6h8fgl1hFNZUwn_O36:-O6h8fgl1hFNZUwn_O37:bxup32p) ([raw file](https://github.com/cockroachdb/cockroach/blob/650199579861b78af7ec23cf287926c95a8090b2/pkg/ccl/changefeedccl/protected_timestamps_test.go#L520)):*
> ```Go
> 	sqlDB.Exec(t, "ALTER TABLE foo ADD COLUMN d STRING")
> 	time.Sleep(2 * time.Second)
> 	// If you want to GC all sytem tables:
> ```

nit: s/sytem/system/

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130622)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andyyang890)

___
*[`pkg/ccl/changefeedccl/protected_timestamps.go` line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130622#-O6gum-C-0cKjmXWTBFv:-O6tofeiE0BfZ3et8-co:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/650199579861b78af7ec23cf287926c95a8090b2/pkg/ccl/changefeedccl/protected_timestamps.go#L49)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

fyi might want to consider updating this number
</blockquote></details>

Done.
___
*[`pkg/ccl/changefeedccl/protected_timestamps.go` line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130622#-O6gwAEt1dkX1lxOeEry:-O6toeS5DcBE4dgWRgiX:b-hakueo) ([raw file](https://github.com/cockroachdb/cockroach/blob/650199579861b78af7ec23cf287926c95a8090b2/pkg/ccl/changefeedccl/protected_timestamps.go#L74)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

should we also add it here?
</blockquote></details>

Done. Nice catch!
___
*[`pkg/ccl/changefeedccl/protected_timestamps_test.go` line 510 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130622#-O6h9KLbBsCEJGJPYPMD:-O6toNvK7IZ2SldqMajV:bw4gfq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/650199579861b78af7ec23cf287926c95a8090b2/pkg/ccl/changefeedccl/protected_timestamps_test.go#L510)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Could there ever be more than one range?
</blockquote></details>

In production absolutely.  In this test, it would be very surprising.
___
*[`pkg/ccl/changefeedccl/protected_timestamps_test.go` line 513 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130622#-O6h8Qur8h9OG6greuUQ:-O6tlfm_4WriH92wKq0r:b-8hv3ja) ([raw file](https://github.com/cockroachdb/cockroach/blob/650199579861b78af7ec23cf287926c95a8090b2/pkg/ccl/changefeedccl/protected_timestamps_test.go#L513)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Wanted to double check my understanding: this would trigger a manual synchronous GC on the range for the tables and we would expect it to not affect the tables that are protected by the PTS?
</blockquote></details>

Yes, this will run the replica through the MVCC GC queue synchronously.  The `true` as the final argument is for `skipShouldQueue` which means we will alway run the queue's `process` callback which is what handles running the GC process.

The GC might _affect_ tables even with the PTS record in place, but we expect that the gc threshold to not advance past the PTS.  Thus we expect any read at `ts` to proceed even after sleeping for a little bit.

**Review by andyyang890 — APPROVED** [review]
:lgtm: Thanks!

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130622#-:-O6vRYG1COJ6jdmrGpn0:b-g2a5fb)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @stevendanna)

**Comment by stevendanna** [comment]
bors r=andyyang890

**Pull request merged**
