### PR TITLE
opt: Add TryDecorrelateGroupBy rule

### PR DESCRIPTION
**Pull request by andy-kimball**
This series of commits adds a new TryDecorrelateGroupBy rule. It
overlaps quite a bit with the existing TryDecorrelateScalarGroupBy rule.
Therefore, this PR contains changes to Optgen that enable the two
rules to be expressed more naturally in the Optgen language and to
more easily share custom functions between themselves.

### CODE REVIEW

**Review by rytaft — CHANGES_REQUESTED** [review]
:lgtm_strong: 

> Reviewed 12 of 12 files at r1, 6 of 6 files at r2, 4 of 4 files at r3, 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27342#-:-LH4xDZrEBDYLPHyrLfk:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/decorrelate.go, line 219 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27342#-LH4sI5q1smkoLFkgSdD:-LH4sI5q1smkoLFkgSdE:b-n8wzcj) ([raw file](https://github.com/cockroachdb/cockroach/blob/196ce68498e5116d0469c19bba4f513cd11c0279/pkg/sql/opt/norm/decorrelate.go#L219)):*
> ```Go
> // that is not-null. EnsureNotNullIfCountRows returns the input group, possibly
> // wrapped in a new Project if a new column was synthesized.
> func (c *CustomFuncs) EnsureNotNullIfCountRows(in, aggs memo.GroupID) memo.GroupID {
> ```

Can you add a bit of context about why this function is necessary? (Maybe just a reference to the rule that uses it)
___
*[pkg/sql/opt/norm/decorrelate.go, line 272 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27342#-LH4szb6437KpXtxDOgM:-LH4szb6437KpXtxDOgN:bk221vx) ([raw file](https://github.com/cockroachdb/cockroach/blob/196ce68498e5116d0469c19bba4f513cd11c0279/pkg/sql/opt/norm/decorrelate.go#L272)):*
> ```Go
> // appends an AnyNotNull aggregate function to the end of the given Aggregations
> // operator, and returns a new Aggregations operator.
> func (c *CustomFuncs) AppendNonKeyCols(in, aggs memo.GroupID) memo.GroupID {
> ```

Can you add some context about why this is needed? (Or a reference to the rule that uses it)
___
*[pkg/sql/opt/norm/decorrelate.go, line 325 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27342#-LH4vEjP2X8oDCCqDcN6:-LH4vEjP2X8oDCCqDcN7:b-93omps) ([raw file](https://github.com/cockroachdb/cockroach/blob/6554397b077e6116c08f456b7f0aec3339b37178/pkg/sql/opt/norm/decorrelate.go#L325)):*
> ```Go
> 	}
> 	return c.f.InternGroupByDef(&memo.GroupByDef{
> 		GroupingCols: groupingCols.Union(keyCols),
> ```

Add a comment that this function is only called on unordered GroupBy expressions.
___
*[pkg/sql/opt/optgen/cmd/optgen/rule_gen.go, line 245 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27342#-LH4gj0O6imVqs35xqLW:-LH4gj0O6imVqs35xqLX:b-xtkouc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2afb4440774232317f4fcd1e70264bf9422f4d31/pkg/sql/opt/optgen/cmd/optgen/rule_gen.go#L245)):*
> ```Go
> 	isFirst := false
> 	isLast := false
> 	for i, item := range match.Items {
> ```

A comment would help here -- maybe just a reminder that `ListAnyOp` is `...`.
___
*[pkg/sql/opt/optgen/lang/doc.go, line 483 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27342#-LH4mVIY-yWdhgUg2E89:-LH4mVIY-yWdhgUg2E8A:bjwdi5u) ([raw file](https://github.com/cockroachdb/cockroach/blob/2afb4440774232317f4fcd1e70264bf9422f4d31/pkg/sql/opt/optgen/lang/doc.go#L483)):*
> ```Go
>   names        = name ('|' name)*
>   arg          = bind and | ref | and
>   and          = and-input ('&' and)
> ```

what is `and-input`?
___
*[pkg/sql/opt/optgen/lang/doc.go, line 157 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27342#-LH4r0Ap49X1MH2Vj138:-LH4r0Ap49X1MH2Vj139:bdm4nxs) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee5ad0405ab141bd7f0ca052902b7ab9d7702095/pkg/sql/opt/optgen/lang/doc.go#L157)):*
> ```Go
> Child patterns within match and replace patterns can be "bound" to a named
> variable. These variables can then be referenced later in the match pattern or
> in the  replace pattern. This is a critical part of the Optgen language, since
> ```

[nit] extra space

**Review by RaduBerinde — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27342#-:-LH8UyJQ7FcIjbU3sWRR:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 240 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27342#-LH8T-PGAPguDLqOtNZt:-LH8T-PGAPguDLqOtNZu:b2p8tsp) ([raw file](https://github.com/cockroachdb/cockroach/blob/196ce68498e5116d0469c19bba4f513cd11c0279/pkg/sql/opt/norm/rules/decorrelate.opt#L240)):*
> ```
> =>
> (Select
>     (GroupBy
> ```

Much nicer to be able to read here what the rule does!
___
*[pkg/sql/opt/optgen/cmd/optgen/rule_gen.go, line 269 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27342#-LH8RIbD6efIx0yfzhZB:-LH8RIbE2GtnCLOYE2Q9:b3nuvg8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2afb4440774232317f4fcd1e70264bf9422f4d31/pkg/sql/opt/optgen/cmd/optgen/rule_gen.go#L269)):*
> ```Go
> 	}
> 
> 	if isFirst {
> ```

[nit] it's hard to keep track of the `if/else`s here, it would be easier to read if it was something like
```
switch {
  case isFirst && isLast: ...
  case isFirst && !isLast: ...
  case !isFirst && isLast: ...
  case !isFirst && !isLast: ...
}
```

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27342)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/norm/decorrelate.go, line 219 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27342#-LH4sI5q1smkoLFkgSdD:-LHDfxgEDnOK4xCpvAey:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/196ce68498e5116d0469c19bba4f513cd11c0279/pkg/sql/opt/norm/decorrelate.go#L219)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Can you add a bit of context about why this function is necessary? (Maybe just a reference to the rule that uses it)
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/decorrelate.go, line 272 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27342#-LH4szb6437KpXtxDOgM:-LHDiVr98tq-kxHuSNCq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/196ce68498e5116d0469c19bba4f513cd11c0279/pkg/sql/opt/norm/decorrelate.go#L272)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Can you add some context about why this is needed? (Or a reference to the rule that uses it)
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/decorrelate.go, line 325 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27342#-LH4vEjP2X8oDCCqDcN6:-LHDibuC4MhaQWUBNxfo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6554397b077e6116c08f456b7f0aec3339b37178/pkg/sql/opt/norm/decorrelate.go#L325)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Add a comment that this function is only called on unordered GroupBy expressions.
</blockquote></details>

Done.
___
*[pkg/sql/opt/optgen/cmd/optgen/rule_gen.go, line 245 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27342#-LH4gj0O6imVqs35xqLW:-LHDkIEB6yQlkLaQXr-S:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2afb4440774232317f4fcd1e70264bf9422f4d31/pkg/sql/opt/optgen/cmd/optgen/rule_gen.go#L245)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

A comment would help here -- maybe just a reminder that `ListAnyOp` is `...`.
</blockquote></details>

Done.
___
*[pkg/sql/opt/optgen/cmd/optgen/rule_gen.go, line 269 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27342#-LH8RIbD6efIx0yfzhZB:-LHDkG9oAP2eNYVDP8wR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2afb4440774232317f4fcd1e70264bf9422f4d31/pkg/sql/opt/optgen/cmd/optgen/rule_gen.go#L269)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] it's hard to keep track of the `if/else`s here, it would be easier to read if it was something like
```
switch {
  case isFirst && isLast: ...
  case isFirst && !isLast: ...
  case !isFirst && isLast: ...
  case !isFirst && !isLast: ...
}
```
</blockquote></details>

Done.
___
*[pkg/sql/opt/optgen/lang/doc.go, line 483 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27342#-LH4mVIY-yWdhgUg2E89:-LHDlv7HEeBp7iwdbaOB:b-6cip90) ([raw file](https://github.com/cockroachdb/cockroach/blob/2afb4440774232317f4fcd1e70264bf9422f4d31/pkg/sql/opt/optgen/lang/doc.go#L483)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

what is `and-input`?
</blockquote></details>

Should be `expr`. Fixed.
___
*[pkg/sql/opt/optgen/lang/doc.go, line 157 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27342#-LH4r0Ap49X1MH2Vj138:-LHDlpY70k3O7pDaC5Bm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee5ad0405ab141bd7f0ca052902b7ab9d7702095/pkg/sql/opt/optgen/lang/doc.go#L157)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] extra space
</blockquote></details>

Done.

**Review by rytaft — CHANGES_REQUESTED** [review]
opt changes look good - what happened with all those libroach files?

> Reviewed 8 of 12 files at r6, 6 of 6 files at r7, 2 of 4 files at r8, 6 of 6 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27342#-:-LHDpH9uC4yYqn57Og5G:bfjuwtb)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/norm/decorrelate.go, line 325 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27342#-LH4vEjP2X8oDCCqDcN6:-LHDo1-0-V0d7O2eKpuT:b2h1h8) ([raw file](https://github.com/cockroachdb/cockroach/blob/6554397b077e6116c08f456b7f0aec3339b37178/pkg/sql/opt/norm/decorrelate.go#L325)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Doesn't look like that change was pushed.

**Review by andy-kimball — COMMENTED** [review]
Hm, not sure. Fixed.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27342#-:-LHE2SI10NqxS8dBgMlI:b-1owllg)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/norm/decorrelate.go, line 325 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27342#-LH4vEjP2X8oDCCqDcN6:-LHE5VRb1Xk-eI7dZfhg:b-bvzp92) ([raw file](https://github.com/cockroachdb/cockroach/blob/6554397b077e6116c08f456b7f0aec3339b37178/pkg/sql/opt/norm/decorrelate.go#L325)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Doesn't look like that change was pushed.
</blockquote></details>

Whoops, got removed when rebasing. I added the phrase "constructs a new unordered GroupByDef" in header comment, both for this and `GroupByKey`.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r11, 2 of 4 files at r12, 6 of 6 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27342#-:-LHE7CcBAetKHrnJmaUG:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
