### PR TITLE
sql: change ^ to be power instead of xor

### PR DESCRIPTION
**Pull request by madelynnblue**
The ^ operator in Postgres has been the pow function since at least
version 7.0, according to their documentation. Since we are supporting
Postgres ORMs, having operators perform the same operation as Postgres
is probably more expected by users than having it do something else.

This is a backward-incompatible change with Cockroach, and users must
update their queries if they relied on this behavior.

Traditional and Modern are both being updated here. Modern is
ostensibly based on the Google Spanner SQL syntax, which uses `^`
as bitwise xor. It would be nice to keep that behavior, but our
current parser only allows for syntaxes to be lexed differently,
not parsed differently, so we can't maintain compat with Modern in
this case. This can be changed in the future.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
I'm not completely sure what the differences between Modern and Traditional syntaxes are, but should we be making this change for both? Also, there are compatibility concerns with this change. Could you expand the commit message to explain your rationale for the change and address some of these questions?

---

Reviewed 1 of 7 files at r2.
Review status: 1 of 7 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/eval.go, line 912 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14882#-KhameAPuemO3cpg-qwR:-KhameAPuemO3cpg-qwS:b-reb3a8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e5b7ecae1d382aba6b5646fc8eff02c25cc9444/pkg/sql/parser/eval.go#L912)):*
> ```Go
> 				}
> 				i, err := dd.Int64()
> 				if err != nil {
> ```

We don't need to check this error value before assuming the cause is `errIntOutOfRange`?

---

*[pkg/sql/parser/expr.go, line 750 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14882#-KhamtU4Nc2Yf5jLjrtd:-KhamtU4Nc2Yf5jLjrte:b-4sj0lm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e5b7ecae1d382aba6b5646fc8eff02c25cc9444/pkg/sql/parser/expr.go#L750)):*
> ```Go
> 	LShift
> 	RShift
> 	Pow
> ```

nit throughout (here and in BinOps): could we move this to beneath `Mod`? These operators are nicely grouped.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14882#-:-KhanIgKZG37-KSLTuhW:b-hozkvc)*

**Comment by knz** [comment]
I'm OK with the 2nd commit, however you're shipping the first as a side-car here and I'm not OK with that until we resolve https://github.com/cockroachdb/cockroach/issues/14814#issuecomment-293873946

**Comment by jordanlewis** [comment]
commit 2 :lgtm:. I think the extra usability gained by having ^ mean pow is 100% worth the backward incompatibility we're introducing. Postgres uses ^ for pow as well, actually.

---

Reviewed 3 of 3 files at r1.
Review status: 1 of 7 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/eval.go, line 964 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14882#-KhcO-nhemwoHGzMoO1Z:-KhcO-nhemwoHGzMoO1_:bti7hj5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e5b7ecae1d382aba6b5646fc8eff02c25cc9444/pkg/sql/parser/eval.go#L964)):*
> ```Go
> 				return dd, err
> 			},
> 		},
> ```

Do we not need Int<->Float  implementations as well? Or Decimal<->Float?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14882#-:-KhcOBlvB8iEqf3oHWng:b-11rx0b)*

**Comment by knz** [comment]
Yes for this operator (exponent) I'm rather comfortable too!

**Comment by knz** [comment]
(In general I don't care too much about which punctuation sign is used for which meaning; what matters most is that given a table of operators and their description a user knows how to assemble expressions. Here, there is no doubt; for the priority change in the 1st commit I still have doubts.)

**Comment by mjibson** [comment]
I've removed the first commit from the batch and addressed the comments. RFAL.

---

Review status: 1 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/parser/eval.go, line 912 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14882#-KhameAPuemO3cpg-qwR:-KhcQgrEVVK30PMhWoQ7:byccnq5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e5b7ecae1d382aba6b5646fc8eff02c25cc9444/pkg/sql/parser/eval.go#L912)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We don't need to check this error value before assuming the cause is `errIntOutOfRange`?
</blockquote></details>

The only reason that function returns an error is if it isn't an integer or can't fit in an int64, so there's no need to check the error value.

---

*[pkg/sql/parser/eval.go, line 964 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14882#-KhcO-nhemwoHGzMoO1Z:-KhcR7-cEIDN--NNxupU:b9w498p) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e5b7ecae1d382aba6b5646fc8eff02c25cc9444/pkg/sql/parser/eval.go#L964)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Do we not need Int<->Float  implementations as well? Or Decimal<->Float?
</blockquote></details>

Not for now, for the same reason those don't exist for `/`.

---

*[pkg/sql/parser/expr.go, line 750 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14882#-KhamtU4Nc2Yf5jLjrtd:-KhcRF7nHF0ay-EkiKru:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e5b7ecae1d382aba6b5646fc8eff02c25cc9444/pkg/sql/parser/expr.go#L750)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit throughout (here and in BinOps): could we move this to beneath `Mod`? These operators are nicely grouped.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14882#-:-KhcSr9PVz2DDmhICE8C:b-rseevf)*

**Comment by mjibson** [comment]
Updated with the integer power function and operator using the same implementation that correctly checks for overflow.

**Comment by mjibson** [comment]
Note that this change also changes the result of `pow(0::int, 0::int)` and `pow(X::int, -Y::int)`.

**Comment by knz** [comment]
:lgtm:

---

Reviewed 2 of 7 files at r2, 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14882#-:-KhfW019sxPIKAMq4D6n:bnfp4nl)*

**Pull request merged**
