### PR TITLE
backupccl: add random backup/restore test

### PR DESCRIPTION
**Pull request by jordanlewis**
This test creates random tables using SQLSmith's random table generator,
    then backs up and restores them, checking for schema roundtrippability.
    It checks both full DB backup/restore as well as all per-table
    backup/restore for all subsets of the random tables.

    Release note: None

### CODE REVIEW

**Review by msbutler — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71627)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @msbutler)

___
*[pkg/ccl/backupccl/backup_rand_test.go, line 102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71627#-MmJucb21zdA1TYyiOvd:-MmJucb21zdA1TYyiOve:b8soa1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/91638006a122b6bb98ab4c2bcd749c1c2a939b59/pkg/ccl/backupccl/backup_rand_test.go#L102)):*
> ```Go
> 		assert.Equal(t, createStatement1, createStatement2, "SHOW CREATE %s not equal after RESTORE", tableName)
> 	}
> ```

Right now, this test first compares a database level Backup to a table level Restore. Then, it compares every combo of tables using a table level Backup and a table level Restore. Before doing the table combo tests, perhaps it's also worth verifying that a table level backup and a db level backup are both valid against a db level restore?  You could add another backup db with "BACKUP TABLE rand.* TO $1" and another restored db "RESTORE DATABASE FROM $1 WITH OPTIONS (new_db_name = 'rand3')", and then test each B/R flavor that logically backs up and restores a whole database. 
___
*[pkg/ccl/backupccl/backup_rand_test.go, line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71627#-MmK26Mt3XuncXny_CXz:-MmK26Mt3XuncXny_CY-:b-4rwfey) ([raw file](https://github.com/cockroachdb/cockroach/blob/91638006a122b6bb98ab4c2bcd749c1c2a939b59/pkg/ccl/backupccl/backup_rand_test.go#L128)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> 			var ignored, createStatement string
> 			table := sqlDB.QueryRow(t, fmt.Sprintf("SHOW CREATE TABLE restoredb.%s", tableName))
> 			table.Scan(&ignored, &createStatement)
> 
> 			assert.Equal(t, createStatement, expectedCreateTableStmt[tableName], "SHOW CREATE %s not equal after RESTORE",
> 				tableName)
> ```
</details>

Given that this block of code is used above, perhaps it's worth creating a nested function that gets called here and above?

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71627)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msbutler)

___
*[pkg/ccl/backupccl/backup_rand_test.go, line 102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71627#-MmJucb21zdA1TYyiOvd:-Mmdq8I_9S4tkk-JrYpR:b-l4ult) ([raw file](https://github.com/cockroachdb/cockroach/blob/91638006a122b6bb98ab4c2bcd749c1c2a939b59/pkg/ccl/backupccl/backup_rand_test.go#L102)):*
<details><summary><i>Previously, msbutler (Michael Butler) wrote…</i></summary><blockquote>

Right now, this test first compares a database level Backup to a table level Restore. Then, it compares every combo of tables using a table level Backup and a table level Restore. Before doing the table combo tests, perhaps it's also worth verifying that a table level backup and a db level backup are both valid against a db level restore?  You could add another backup db with "BACKUP TABLE rand.* TO $1" and another restored db "RESTORE DATABASE FROM $1 WITH OPTIONS (new_db_name = 'rand3')", and then test each B/R flavor that logically backs up and restores a whole database. 
</blockquote></details>

Done, good idea.
___
*[pkg/ccl/backupccl/backup_rand_test.go, line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71627#-MmK26Mt3XuncXny_CXz:-Mmdq7rG8xueklXcIxaA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/91638006a122b6bb98ab4c2bcd749c1c2a939b59/pkg/ccl/backupccl/backup_rand_test.go#L128)):*
<details><summary><i>Previously, msbutler (Michael Butler) wrote…</i></summary><blockquote>

> ```
> 			var ignored, createStatement string
> 			table := sqlDB.QueryRow(t, fmt.Sprintf("SHOW CREATE TABLE restoredb.%s", tableName))
> 			table.Scan(&ignored, &createStatement)
> 
> 			assert.Equal(t, createStatement, expectedCreateTableStmt[tableName], "SHOW CREATE %s not equal after RESTORE",
> 				tableName)
> ```
Given that these four lines of code are used above, perhaps it's worth creating a nested function that gets called here and above?
</blockquote></details>

Done.

**Review by msbutler — APPROVED** [review]
Left a few non-blocking comments!

> Reviewed 3 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71627#-:-Mn2aZR02f_uBylZqhSs:b-cncnhf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/ccl/backupccl/backup_rand_test.go, line 102 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71627#-Mn2XWfr85WXAUb6s4E1:-Mn2XWfr85WXAUb6s4E2:b-1djv5q) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0e865a259d2d9278ae58c7da87acdd821874c59/pkg/ccl/backupccl/backup_rand_test.go#L102)):*
> ```Go
> 		t.Fatal(err)
> 	}
> ```

perhaps it's worth adding a small comment for this function, as this is the first place the code reader is introduced to the name of the restored database.

// verifyTables asserts that a list of tables in the restored database, named restoredb, contains the same schema as the original randomly generated tables
___
*[pkg/ccl/backupccl/backup_rand_test.go, line 110 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71627#-Mn2Yv-bCD2MjV1cuPEg:-Mn2Yv-bCD2MjV1cuPEh:b8vt474) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0e865a259d2d9278ae58c7da87acdd821874c59/pkg/ccl/backupccl/backup_rand_test.go#L110)):*
> ```Go
> 		}
> 	}
> ```

perhaps worth adding a comment, to spell out the motivation of the two flavors of all table B/Rs

// this loop tests that two kinds of all table restores are round-tripable to two kinds of backups, which also contain all tables

**Review by jordanlewis — COMMENTED** [review]
TFTR!

@dt suggested in Slack that I break this test out into another package. I tried this, but it requires a bit of refactoring, so I'll leave it like this for now.

I hope you will adopt this test and make it better over time! This kind of testing has caught an enormous amount of issues in SQL Schema and SQL Queries, and as we enhance the to include more schema features, we'll add these schema features to the random schema generators, which will then automatically send new combinations of features to this kind of test and (hopefully) catch bugs we didn't think of.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71627#-:-Mn3FfX-2wtE9SalfqMb:b-4pzf6j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msbutler)

___
*[pkg/ccl/backupccl/backup_rand_test.go, line 102 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71627#-Mn2XWfr85WXAUb6s4E1:-Mn3FKpD2k1Uc59fnYIe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0e865a259d2d9278ae58c7da87acdd821874c59/pkg/ccl/backupccl/backup_rand_test.go#L102)):*
<details><summary><i>Previously, msbutler (Michael Butler) wrote…</i></summary><blockquote>

i.e. for the following function ( still getting used to reviewable!)
> ```
> 	verifyTables := func(t *testing.T, tableNames []string) {
> 		for _, tableName := range tableNames {
> 			t.Logf("Verifying table %s", tableName)
> 			createStatement := getCreateStatementForTable("restoredb." + tableName)
> 			assert.Equal(t, expectedCreateTableStmt[tableName], createStatement, "SHOW CREATE %s not equal after RESTORE", tableName)
> 		}
> ```
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/backup_rand_test.go, line 110 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71627#-Mn2Yv-bCD2MjV1cuPEg:-Mn3FeR34TRWwUBPjkzL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0e865a259d2d9278ae58c7da87acdd821874c59/pkg/ccl/backupccl/backup_rand_test.go#L110)):*
<details><summary><i>Previously, msbutler (Michael Butler) wrote…</i></summary><blockquote>

> ```
> for _, backup := range dbBackups {
> ```

</blockquote></details>

Done.

**Comment by jordanlewis** [comment]
The tests that are failing are BackupRestorePartitioned, which I didn't edit. But maybe the failure is really caused by my patch?

I'm going to roll the dice once more and see what happens:

bors r+

**Comment by shermanCRL** [comment]
@msbutler would you have a look at these test runs -- it’s been suspiciously quiet. Are the tests doing what we expect?

**Pull request merged**
