### PR TITLE
importccl: Added row limit option for importing DELIMITED, AVRO formats

### PR DESCRIPTION
**Pull request by mokaixu**
A row limit option allows users to specify a fixed number of rows
    that they want to import. This functionality is only available for
    CSV formats.
    
    With this code change, users can limit the number of rows they want
    to import for DELIMITED and AVRO data forms. That is, they can
    specify: `WITH row_limit="{$num}"` to only import $num rows.
    
    Release note (sql change): Added WITH row_limit="{$num}" option for importing
    DELIMITED/AVRO data to allow users to do a quick test run on an import of $num rows.
    Ex. IMPORT TABLE test ... DELIMITED/AVRO DATA ... WITH row_limit="3";

DIFF BASE on PR: #56080

### CODE REVIEW

**Review by miretskiy — APPROVED** [review]
You seem to have 2 commits with the same title... Not sure if you need to squash them, or perhaps update one of the commits w/ correct description.

Nice job!  I have mostly nits.  Giving you a big :lgtm: 
Feel free to ping me if you have any questions re my minor requests.

> Reviewed 2 of 6 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56135#-:-MKtboBP284XvC78PKXs:b-gowo9n)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mokaixu)

___
*[pkg/ccl/importccl/import_stmt.go, line 456 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56135#-MKtc6oIBqyu7iKiPgjE:-MKtc6oIBqyu7iKiPgjF:b-nwto8g) ([raw file](https://github.com/cockroachdb/cockroach/blob/3247b2725ff6173aafa1442be925e92fce9cf814/pkg/ccl/importccl/import_stmt.go#L456)):*
> ```Go
> 				rowLimit, err := strconv.Atoi(override)
> 				if err != nil {
> 					return pgerror.Wrapf(err, pgcode.Syntax, "invalid %s value", csvRowLimit)
> ```

perhaps `invalid numeric value %s` to make it clear we expect a number there?
___
*[pkg/ccl/importccl/import_stmt.go, line 522 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56135#-MKtcEm_8b_FHcyT_9ER:-MKtcEm_8b_FHcyT_9ES:b-s9onyh) ([raw file](https://github.com/cockroachdb/cockroach/blob/3247b2725ff6173aafa1442be925e92fce9cf814/pkg/ccl/importccl/import_stmt.go#L522)):*
> ```Go
> 				format.SaveRejected = true
> 			}
> 			// TODO(mokaixu): rename csvRowLimit to rowLimit
> ```

Maybe just rename it?
Or keep it as csvRowLimit -- that's fine, I think (and drop this todo).  We already use csv named vars in other formats.
Or... if you feel strongly, move this todo on top of this file and make it generic to all csv* options that we use in other formats (e.g. csvNullIf, etc)
___
*[pkg/ccl/importccl/import_stmt.go, line 913 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56135#-MKtcpUL1wwPTZlILBX_:-MKtcpUL1wwPTZlILBXa:b-113pjy) ([raw file](https://github.com/cockroachdb/cockroach/blob/3247b2725ff6173aafa1442be925e92fce9cf814/pkg/ccl/importccl/import_stmt.go#L913)):*
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
> 	if override, ok := opts[csvRowLimit]; ok {
> 		rowLimit, err := strconv.Atoi(override)
> 		if err != nil {
> 			return pgerror.Wrapf(err, pgcode.Syntax, "invalid %s value", csvRowLimit)
> 		}
> 		if rowLimit <= 0 {
> 			return pgerror.Newf(pgcode.Syntax, "%s must be > 0", csvRowLimit)
> 		}
> 		format.Avro.RowLimit = uint32(rowLimit)
> 	}
> ```
</details>


Perhaps let's move this into a helper

```
  func setNumericOption(opt string, opts map[string]string, int32* val) error {
     ....
  }
```
___
*[pkg/ccl/importccl/import_stmt_test.go, line 344 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56135#-MKtdB8O8IL0pW40F7JW:-MKtdB8O8IL0pW40F7JX:b-4cr6j9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3247b2725ff6173aafa1442be925e92fce9cf814/pkg/ccl/importccl/import_stmt_test.go#L344)):*
> ```Go
> 			typ:    "CSV",
> 			data:   "a string, b string\nfoo,normal\nbar,baz\nchocolate,cake\n",
> 			err:    "pq: row_limit must be > 0",
> ```

would row limit of 0 be useful? Perhaps I just want to create the table and check it worked?
___
*[pkg/ccl/importccl/import_stmt_test.go, line 376 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56135#-MKtdOn1-6PoQC8PazMa:-MKtdOn1-6PoQC8PazMb:byvtyrt) ([raw file](https://github.com/cockroachdb/cockroach/blob/3247b2725ff6173aafa1442be925e92fce9cf814/pkg/ccl/importccl/import_stmt_test.go#L376)):*
> ```Go
> 			typ:    "CSV",
> 			data:   "a string, b string\nfoo,normal\nbar,baz\nchocolate,cake\n",
> 			query:  map[string][][]string{`SELECT * from t`: {{"foo", "normal"}, {"bar", "baz"}, {"chocolate", "cake"}}},
> ```

do we want test case w/ skip > max rows?
skip < 0?
___
*[pkg/ccl/importccl/import_stmt_test.go, line 1443 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56135#-MKtds2J2n7VoJFURgfO:-MKtds2J2n7VoJFURgfP:b5njd4k) ([raw file](https://github.com/cockroachdb/cockroach/blob/3247b2725ff6173aafa1442be925e92fce9cf814/pkg/ccl/importccl/import_stmt_test.go#L1443)):*
> ```Go
> 	// Set up a directory for the data files.
> 	err := os.Mkdir(filepath.Join(baseDir, "test"), 0777)
> 	require.NoError(t, err)
> ```

you don't need this.  Your baseDir already points to a temporary directory.
___
*[pkg/ccl/importccl/import_stmt_test.go, line 1450 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56135#-MKtdvcRBioOvmLqSXHr:-MKtdvcRBioOvmLqSXHs:byn800r) ([raw file](https://github.com/cockroachdb/cockroach/blob/3247b2725ff6173aafa1442be925e92fce9cf814/pkg/ccl/importccl/import_stmt_test.go#L1450)):*
> ```Go
> 
> 			// Create temporary file for test data.
> 			err := ioutil.WriteFile(filepath.Join(baseDir, "test", "data"), []byte(test.data), 0666)
> ```

You probably should create a different file for each test.  And you probably don't need to create subdirectoreis (filepath.Join) since basedir is a temp directory.
___
*[pkg/ccl/importccl/read_import_base.go, line 411 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56135#-MKteHRi1U6vk868u9rX:-MKteHRi1U6vk868u9rY:b3d88lz) ([raw file](https://github.com/cockroachdb/cockroach/blob/3247b2725ff6173aafa1442be925e92fce9cf814/pkg/ccl/importccl/read_import_base.go#L411)):*
> ```Go
> 	skip     int64       // Number of records to skip
> 	rejected chan string // Channel for reporting corrupt "rows"
> 	rowLimit uint32      // Number of records to process.
> ```

Just noticed.  Let's not use uint (here and throughout).  Use unsigned types *only* when representing bit patters. Check for invalid values (like you already do when checking for negative offset and return errors).    See below.
___
*[pkg/ccl/importccl/read_import_base.go, line 555 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56135#-MKtgfXr0CK4WlOYA33I:-MKtgfXr0CK4WlOYA33J:b85dol1) ([raw file](https://github.com/cockroachdb/cockroach/blob/3247b2725ff6173aafa1442be925e92fce9cf814/pkg/ccl/importccl/read_import_base.go#L555)):*
> ```Go
> 			// Stop when we have processed row limit number of rows.
> 			numRowsToProcess := count - numSkipped
> 			if fileCtx.rowLimit != 0 && numRowsToProcess > int64(fileCtx.rowLimit) {
> ```

This is why rowLimit should be a signed quantity.  Not that your code is effected (for now), but it's because signed extensions and conversions are rather subtle, language dependent and a source of bugs.  See https://play.golang.org/p/O8_ERDumpvu

**Review by mokaixu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56135)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @miretskiy and @mokaixu)

___
*[pkg/ccl/importccl/import_stmt.go, line 456 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56135#-MKtc6oIBqyu7iKiPgjE:-MKufIP42RygO4V4aTNQ:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3247b2725ff6173aafa1442be925e92fce9cf814/pkg/ccl/importccl/import_stmt.go#L456)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

perhaps `invalid numeric value %s` to make it clear we expect a number there?
</blockquote></details>

done
___
*[pkg/ccl/importccl/import_stmt.go, line 522 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56135#-MKtcEm_8b_FHcyT_9ER:-MKufWHZDm_wyBbteSRD:bw314bn) ([raw file](https://github.com/cockroachdb/cockroach/blob/3247b2725ff6173aafa1442be925e92fce9cf814/pkg/ccl/importccl/import_stmt.go#L522)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Maybe just rename it?
Or keep it as csvRowLimit -- that's fine, I think (and drop this todo).  We already use csv named vars in other formats.
Or... if you feel strongly, move this todo on top of this file and make it generic to all csv* options that we use in other formats (e.g. csvNullIf, etc)
</blockquote></details>

ack. i'll keep it as csvRowLimit for the CSV only PR and will address this change in the next PR that covers AVRO & DELIMITED
___
*[pkg/ccl/importccl/import_stmt.go, line 913 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56135#-MKtcpUL1wwPTZlILBX_:-ML8xcFj0yB4MpFz4bS4:b-q67yoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/3247b2725ff6173aafa1442be925e92fce9cf814/pkg/ccl/importccl/import_stmt.go#L913)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

> ```
> 	if override, ok := opts[csvRowLimit]; ok {
> 		rowLimit, err := strconv.Atoi(override)
> 		if err != nil {
> 			return pgerror.Wrapf(err, pgcode.Syntax, "invalid %s value", csvRowLimit)
> 		}
> 		if rowLimit <= 0 {
> 			return pgerror.Newf(pgcode.Syntax, "%s must be > 0", csvRowLimit)
> 		}
> 		format.Avro.RowLimit = uint32(rowLimit)
> 	}
> ```

Perhaps let's move this into a helper

```
  func setNumericOption(opt string, opts map[string]string, int32* val) error {
     ....
  }
```
</blockquote></details>

I refactored this for rowLimit, but will this apply to skip as well?
___
*[pkg/ccl/importccl/import_stmt_test.go, line 344 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56135#-MKtdB8O8IL0pW40F7JW:-MKuibuP6SAFIcRNkuov:b-w7p4h9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3247b2725ff6173aafa1442be925e92fce9cf814/pkg/ccl/importccl/import_stmt_test.go#L344)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

would row limit of 0 be useful? Perhaps I just want to create the table and check it worked?
</blockquote></details>

Not sure how frequently this would come up, but right now 0 is used as a sentinel value, so I'm enforcing row_limit to be strictly greater than 0.
___
*[pkg/ccl/importccl/import_stmt_test.go, line 1443 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56135#-MKtds2J2n7VoJFURgfO:-ML8vYTG6WmVYqDVf0hN:b2nhysk) ([raw file](https://github.com/cockroachdb/cockroach/blob/3247b2725ff6173aafa1442be925e92fce9cf814/pkg/ccl/importccl/import_stmt_test.go#L1443)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

you don't need this.  Your baseDir already points to a temporary directory.
</blockquote></details>

ack
___
*[pkg/ccl/importccl/import_stmt_test.go, line 1450 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56135#-MKtdvcRBioOvmLqSXHr:-ML8uaaYB-OeTyFuvptN:b-m8oyg1) ([raw file](https://github.com/cockroachdb/cockroach/blob/3247b2725ff6173aafa1442be925e92fce9cf814/pkg/ccl/importccl/import_stmt_test.go#L1450)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

You probably should create a different file for each test.  And you probably don't need to create subdirectoreis (filepath.Join) since basedir is a temp directory.
</blockquote></details>

pinged you about this one!
___
*[pkg/ccl/importccl/read_import_base.go, line 411 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56135#-MKteHRi1U6vk868u9rX:-MKuhVO16K6Ijtff8heH:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3247b2725ff6173aafa1442be925e92fce9cf814/pkg/ccl/importccl/read_import_base.go#L411)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Just noticed.  Let's not use uint (here and throughout).  Use unsigned types *only* when representing bit patters. Check for invalid values (like you already do when checking for negative offset and return errors).    See below.
</blockquote></details>

done
___
*[pkg/ccl/importccl/read_import_base.go, line 555 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56135#-MKtgfXr0CK4WlOYA33I:-MKuhXBTAr7hcaoregV8:b-e0txtm) ([raw file](https://github.com/cockroachdb/cockroach/blob/3247b2725ff6173aafa1442be925e92fce9cf814/pkg/ccl/importccl/read_import_base.go#L555)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

This is why rowLimit should be a signed quantity.  Not that your code is effected (for now), but it's because signed extensions and conversions are rather subtle, language dependent and a source of bugs.  See https://play.golang.org/p/O8_ERDumpvu
</blockquote></details>

makes sense, thanks for the resource :)

**Review by mokaixu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56135)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @miretskiy and @mokaixu)

___
*[pkg/ccl/importccl/import_stmt.go, line 913 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56135#-MKtcpUL1wwPTZlILBX_:-ML8z-gY0qqQCvoOUbBw:bw9wifp) ([raw file](https://github.com/cockroachdb/cockroach/blob/3247b2725ff6173aafa1442be925e92fce9cf814/pkg/ccl/importccl/import_stmt.go#L913)):*
<details><summary><i>Previously, mokaixu (Monica Xu) wrote…</i></summary><blockquote>

I refactored this for rowLimit, but will this apply to skip as well?
</blockquote></details>

Following up, I reverted this code refactor because I feel like the error that could be thrown might be different for other numeric options. Wasn't sure how to cleanly account for this in a helper

**Review by mokaixu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56135)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 376 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56135#-MKtdOn1-6PoQC8PazMa:-ML8zi0r9BSXiGZH3bIF:bxg4rbh) ([raw file](https://github.com/cockroachdb/cockroach/blob/3247b2725ff6173aafa1442be925e92fce9cf814/pkg/ccl/importccl/import_stmt_test.go#L376)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

do we want test case w/ skip > max rows?
skip < 0?
</blockquote></details>

this is already tested in `TestImportData`
name: "skip -1 lines"
name: "skip > all lines"

**Review by adityamaru — APPROVED** [review]

**Comment by mokaixu** [comment]
bors r=adityamaru,miretskiy

**Pull request merged**
