### PR TITLE
workload: generate initial table data in batches of rows

### PR DESCRIPTION
**Pull request by danhhz**
It used to be a row at a time. For two reasons:

1) The TPCC order_line table needs rand(5, 15) rows per row in the order
    table and this was very difficult to do before. This is the last
    known piece needed to make TPCC consistent with the spec.

2) So we can make rng seeding per batch. It's great to make initial data
    totally deterministic, but when creating large TPCC fixtures, doing
    one rng seed per row proved to be too expensive.

Unfortunately, this has a noticable impact on the speed of generating
TPCC data, which will likely show up in fixture generation. There's
definitely some tuning of the TPCC batch sizes left on the table here,
but this commit is already big enough.

    name                     old time/op    new time/op    delta
    InitTPCC/warehouses=1-8     1.83s ± 2%     2.39s ± 1%  +30.42%  (p=0.008 n=5+5)

    name                     old speed      new speed      delta
    InitTPCC/warehouses=1-8  38.7MB/s ± 2%  29.6MB/s ± 1%  -23.32%  (p=0.008 n=5+5)

    name                     old alloc/op   new alloc/op   delta
    InitTPCC/warehouses=1-8     301MB ± 0%     329MB ± 0%   +9.28%  (p=0.008 n=5+5)

    name                     old allocs/op  new allocs/op  delta
    InitTPCC/warehouses=1-8     8.94M ± 0%     9.38M ± 0%   +4.88%  (p=0.008 n=5+5)

This also makes a few changes that came out of a discussion with
@jordanlewis. ValidateInitialData has turned out to be too slow to run
in practice, so it's removed. Accordingly, the `./workload fixtures load
--checks` flag default is changed to true so it actually does some good.

Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
:lgtm_strong:  thanks!

---

Review status: 0 of 26 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24176#-:-L8Y3BwPnh-wRJ8uQP3O:b9jg8y3)*

**Comment by danhhz** [comment]
FYI if anyone is following along, we're waiting to submit this until it's not going to break people's use of tpcc fixtures (the version got bumped so it currently would think they're missing).

**Comment by danhhz** [comment]
@jordanlewis did we get the fixtures generated for this? shall I merge?

**Comment by jordanlewis** [comment]
Yes, the fixtures are generated. Some of them still have the spurious flag in their filenames that we removed recently - I think those are the ones you generated. Feel free to merge and if you could move those files that would be great too!

**Comment by danhhz** [comment]
Great, files are moving now!

**Pull request merged**
