### PR TITLE
server: compress gzip-encoded HTTP responses

### LINKED ISSUE #88934: gzip-encoded HTTP responses aren't compressed (but are valid gzip)
**Describe the problem**
It appears that HTTP requests that request gzip compression (via `Accept-Encoding: gzip` or any variant that includes "gzip" in the value) don't get compressed in their response. The `Content-Encoding: gzip` response header is properly set, and the response includes the standard gzip header and trailer, but the body isn't actually DEFLATE-compressed; it's just the standard response.

**To Reproduce**
There's a bunch of ways to repro this, but let's go with the low-level one for now:

1. Start a cluster with `./cockroach demo movr` (any other valid invocation works too)
2. Log into that cluster via `curl`: 
```
# replace "demo507935" below with the demo password provided in `./cockroach demo movr`'s output
curl -d "username=demo&password=demo507835" -H 'Content-Type: application/x-www-form-urlencoded' localhost:8080/api/v2/login/
{"session":"CIGAwouEz4uOCxIQXINhIjZAEL5h2ys6LiTWuw=="}
```
3. Use the Cluster API to request node metadata and confirm some metadata about the response (uncompressed):
```
# response as reported by curl
curl -H "X-Cockroach-API-Session: CIGAktqtnIuOCxIQbn1A1FU4ioeVuiSEK9p19Q==" localhost:8080/api/v2/nodes/ --silent
{"nodes":[{"node_id":1,"address":{"network_field":"tcp","address_field":"127.0.0.1:33639"},"attrs":{},"locality":{"tiers":[{"key":"region","value":"us-east1"},{"key":"az","value":"b"}]}, "...clipped for brevity"

# response size
curl -H "X-Cockroach-API-Session: CIGAktqtnIuOCxIQbn1A1FU4ioeVuiSEK9p19Q==" localhost:8080/api/v2/nodes/ --silent --output /dev/null --write-out '%{stderr}downloaded bytes: %{size_download}'
downloaded bytes: 43283

# response filetype
curl -H "X-Cockroach-API-Session: CIGAktqtnIuOCxIQbn1A1FU4ioeVuiSEK9p19Q==" localhost:8080/api/v2/nodes/ --silent | file -
/dev/stdin: JSON data

# raw response bytes
curl -H "X-Cockroach-API-Session: CIGAktqtnIuOCxIQbn1A1FU4ioeVuiSEK9p19Q==" localhost:8080/api/v2/nodes/ --silent | hd | head
00000000  7b 22 6e 6f 64 65 73 22  3a 5b 7b 22 6e 6f 64 65  |{"nodes":[{"node|
00000010  5f 69 64 22 3a 31 2c 22  61 64 64 72 65 73 73 22  |_id":1,"address"|
00000020  3a 7b 22 6e 65 74 77 6f  72 6b 5f 66 69 65 6c 64  |:{"network_field|
00000030  22 3a 22 74 63 70 22 2c  22 61 64 64 72 65 73 73  |":"tcp","address|
00000040  5f 66 69 65 6c 64 22 3a  22 31 32 37 2e 30 2e 30  |_field":"127.0.0|
00000050  2e 31 3a 33 33 36 33 39  22 7d 2c 22 61 74 74 72  |.1:33639"},"attr|
00000060  73 22 3a 7b 7d 2c 22 6c  6f 63 61 6c 69 74 79 22  |s":{},"locality"|
00000070  3a 7b 22 74 69 65 72 73  22 3a 5b 7b 22 6b 65 79  |:{"tiers":[{"key|
00000080  22 3a 22 72 65 67 69 6f  6e 22 2c 22 76 61 6c 75  |":"region","valu|
00000090  65 22 3a 22 75 73 2d 65  61 73 74 31 22 7d 2c 7b  |e":"us-east1"},{|
```

4. Do the same things, but with `-H 'Accept-Encoding: gzip'` to request gzip compression.  Don't use curl's built-in `--compressed` flag, which will automatically gunzip the response: we need to see raw bytes here.
```
# response as reported by curl
curl -H 'Accept-encoding: gzip' -H "X-Cockroach-API-Session: CIGAuuOo+ouOCxIQmTHhEixf09J+/RlLspB1WQ==" localhost:8080/api/v2/nodes/
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.

# response size
curl -H 'Accept-encoding: gzip' -H "X-Cockroach-API-Session: CIGAuuOo+ouOCxIQmTHhEixf09J+/RlLspB1WQ==" localhost:8080/api/v2/nodes/ --silent --output /dev/null --write-out '%{stderr}downloaded bytes: %{size_download}'
downloaded bytes: 43340

# response filetype
curl -H 'Accept-encoding: gzip' -H "X-Cockroach-API-Session: CIGAuuOo+ouOCxIQmTHhEixf09J+/RlLspB1WQ==" localhost:8080/api/v2/nodes/ --silent | file -
/dev/stdin: gzip compressed data

# raw response bytes
curl -H 'Accept-encoding: gzip' -H "X-Cockroach-API-Session: CIGAuuOo+ouOCxIQmTHhEixf09J+/RlLspB1WQ==" localhost:8080/api/v2/nodes/ --silent | hd | head
00000000  1f 8b 08 00 00 00 00 00  00 ff 00 0c aa f3 55 7b  |..............U{|
00000010  22 6e 6f 64 65 73 22 3a  5b 7b 22 6e 6f 64 65 5f  |"nodes":[{"node_|
00000020  69 64 22 3a 31 2c 22 61  64 64 72 65 73 73 22 3a  |id":1,"address":|
00000030  7b 22 6e 65 74 77 6f 72  6b 5f 66 69 65 6c 64 22  |{"network_field"|
00000040  3a 22 74 63 70 22 2c 22  61 64 64 72 65 73 73 5f  |:"tcp","address_|
00000050  66 69 65 6c 64 22 3a 22  31 32 37 2e 30 2e 30 2e  |field":"127.0.0.|
00000060  31 3a 33 38 39 38 39 22  7d 2c 22 61 74 74 72 73  |1:38989"},"attrs|
00000070  22 3a 7b 7d 2c 22 6c 6f  63 61 6c 69 74 79 22 3a  |":{},"locality":|
00000080  7b 22 74 69 65 72 73 22  3a 5b 7b 22 6b 65 79 22  |{"tiers":[{"key"|
00000090  3a 22 72 65 67 69 6f 6e  22 2c 22 76 61 6c 75 65  |:"region","value|
```

Note that `file` reports gzip compressed data (in the second command) and curl warns about binary data (in the first command), as expected. Looking at the firest few lines of a hexdump (via `hd`), we see `1f 8b` as the leading two bytes (the [gzip magic number](https://en.wikipedia.org/wiki/Gzip#File_format)) and `08` as the next byte indicating the compression method (`DEFLATE`), but the remaining text is uncompressed: it still begins with `{"nodes":[{"node_id":1`. Because of the gzip header and trailer, the number of bytes downloaded is slightly larger with compression requested than without.

This is especially rough for the DB Console JS bundle (`/bundle.js`), which weighs in at 25MB uncompressed:

```
curl localhost:8080/bundle.js --silent --output /dev/null --write-out '%{stderr}downloaded bytes: %{size_download}'
downloaded bytes: 25242299

curl -H 'accept-encoding: gzip' localhost:8080/bundle.js --silent --output /dev/null --write-out '%{stderr}downloaded bytes: %{size_download}'
downloaded bytes: 25244252
```

**Expected behavior**
gzip-encoded responses are smaller than their non-gzip-encoded counterparts.

**Additional data / screenshots**
I repro'd on linux, but I imagine this impacts all binaries.

**Additional context**
What was the impact?

HTTP transfers are generally quite unoptimized at the moment.  The biggest place this is noticeable is when loading the admin UI (AKA DB Console), which requires downloading a 25MB JS bundle.  While that bundle is cached client-side, the initial transfer can take quite a long time.  Actually gzip-compressing the response can significantly reduce the transferred file size, accelerating that pageload.

Jira issue: CRDB-20044

### PR DESCRIPTION
**Pull request by sjbarag**
HTTP requests with `Accept-encoding: gzip` result in a gzip-encoded response with `Content-encoding: gzip` as expected, but with a gzip body that was uncompressed. This resulted in responses that were slightly larger than their uncompressed versions due to the inclusion of gzip headers and trailers. Replace gzip_response_writer with github.com/NYTimes/gziphandler, and compress gzip-encoded HTTP responses. This increases response time for extremely large responses (e.g. 25MB uncompressed for /bundle.js) to approximately 500ms in exchange for a reduced transfer size (e.g. transferring 7MB compressed for /bundle.js).

fixes https://github.com/cockroachdb/cockroach/issues/88934

Release note (performance improvement): HTTP requests with 'Accept-encoding: gzip' previously resulted in valid gzip-encoded but uncompressed responses. This resulted in inefficient HTTP transfer times, as far more bytes were transferred than necessary. Those responses are now properly compressed, resulting in smaller network responses.

### CODE REVIEW

**Review by knz — APPROVED** [review]
oooh good find :facepalm: 

thank you for figuring it out! and please get this backported :)

**Comment by knz** [comment]
cc @dhartunian FYI

**Review by sjbarag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88950)* status: :shipit: complete! 0 of 0 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/88950#-ND9C4112Ms3Yuacm4I_:-ND9C4112Ms3Yuacm4Ia:bi2elny) (no related file):*
Thanks for reviewing @knz !

Changed in r2: ran `go mod tidy` :)

___

**Comment by sjbarag** [comment]
Ah right, the vendor tree!  https://github.com/cockroachdb/vendored/pull/60

**Comment by knz** [comment]
This does not sound right 
image

**Comment by knz** [comment]
so it looks like you've borked your vendor tree.
(I don't blame you - this stuff is hard)

Let's see how to fix this. The way I would do is this:

1. restore the original vendor tree before your change: `cd vendor && git checkout <prev-SHA>`
2. ascertain you did this well: it should be the same SHA now as the one in the `master` branch.
3. run `make vendor_rebuild` at top
4. in vendor tree, run the following:
   ```
   git chechkout -b gzip-thing-this-is-your-banch-name
   git add .
   git commit -m "add gzip-thing"
   git commit --set-upstream origin gzip-thing-this-is-your-banch-name
   ```

   (do NOT create a PR in the vendor repo. This is not needed.)

5. at top, do `git add vendor`
6. then `git commit --amend --no-edit`    (to replace the new vendor pointer in the crdb repo)
7. git push -f as usual

**Comment by sjbarag** [comment]
> so it looks like you've borked your vendor tree.
> (I don't blame you - this stuff is hard)

Ah heck, I had a feeling that'd happen.  I had no idea we didn't use the `master` branch — that's used pretty exclusively for `yarn-vendored` 😅 

I'll get this fixed.  Thanks for the tip!

**Comment by sjbarag** [comment]
Fixed — this feels better.  Thanks again for the help @knz !

image

**Comment by knz** [comment]
this will alas need another rebase

**Review by knz — APPROVED** [review]

**Comment by sjbarag** [comment]
bors r=knz

**Pull request merged**
