### PR TITLE
storage, kv: provide additional stats on reason for txn restarts

### LINKED ISSUE #14844: storage: Add metrics for txns that differ between serializable and snapshot
It's difficult to tell when changing the transaction isolation level between SERIALIZABLE and SNAPSHOT will be beneficial, or have any effect at all. We should export metrics to show how often the kind of contention in which the isolation level will make any difference is happening. The obvious place to put that metric is [here](https://github.com/cockroachdb/cockroach/blob/b017df80b9899961194dd2af803220528d72796c/pkg/storage/replica_command.go#L817), although that code may be run multiple times per transaction (once per retry and potentially an extra time for the 1PC optimization), so we may want to figure out a more accurate place to count it.

### PR DESCRIPTION
**Pull request by spencerkimball**
Add stats to differentiate reasons for txn restarts. They fall into
four buckets: write-too-old, forwarded-ts (iso=serializable), forwarded-ts
(iso=snapshot), & possible replay.

Added a new graphs dashboard for transactions and now include some of the
stats already being collected by the txn-coord-sender with the addition of
the restart reason stats.

Fixes #14844

### CODE REVIEW

**Comment by bdarnell** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/kv/txn_coord_sender.go, line 146 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15234#-KiCxhFVfhPPtLqzbr4M:-KiCxhFVfhPPtLqzbr4N:bv7tbdm) ([raw file](https://github.com/cockroachdb/cockroach/blob/7079dd702fd8e1f841ea7d6aec7fcc4a5f37fde1/pkg/kv/txn_coord_sender.go#L146)):*
> ```Go
> 	metaRestartsSnapshot = metric.Metadata{
> 		Name: "txn.restarts.snapshot",
> 		Help: "Number of restarts due to a DelRange, forwarded commit timestamp, and isolation=SNAPSHOT"}
> ```

It looks like this happens when a DelRange restarts due to a forwarded commit timestamp, regardless of isolation. That's what we want (the distinction we want to make is not how many transactions of each isolation level were restarted, but how many would have restarted if the isolation level were changed), but it means this metric is kind of misnamed. 

---

*[pkg/kv/txn_coord_sender.go, line 873 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15234#-KiCwWV_4h66GtSya5jz:-KiCwWV_4h66GtSya5k-:bdw0khi) ([raw file](https://github.com/cockroachdb/cockroach/blob/7079dd702fd8e1f841ea7d6aec7fcc4a5f37fde1/pkg/kv/txn_coord_sender.go#L873)):*
> ```Go
> 		case roachpb.RETRY_SNAPSHOT:
> 			tc.metrics.RestartsSnapshot.Inc(1)
> 		case roachpb.RETRY_SERIALIZABLE:
> ```

What about POSSIBLE_REPLAY? Is the assumption that those don't make it back to the client?

---

*[pkg/roachpb/errors.proto, line 104 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15234#-KiCvjlRHQ2mPOJlxHcZ:-KiCvjlRHQ2mPOJlxHc_:b1el0xk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7079dd702fd8e1f841ea7d6aec7fcc4a5f37fde1/pkg/roachpb/errors.proto#L104)):*
> ```protobuf
> }
> 
> // ReadConsistencyType specifies what type of consistency is observed
> ```

Copy/paste error. 

---

*[pkg/storage/store.go, line 2575 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15234#-KiCwIZ7XcDAC9NlAKa8:-KiCwIZ7XcDAC9NlAKa9:bm270p9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7079dd702fd8e1f841ea7d6aec7fcc4a5f37fde1/pkg/storage/store.go#L2575)):*
> ```Go
> 				// to guarantee a retry.
> 				if ba.Txn != nil {
> 					return nil, roachpb.NewErrorWithTxn(roachpb.NewTransactionRetryError(0), ba.Txn)
> ```

Use the `UNKNOWN` constant. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15234)*

**Comment by spencerkimball** [comment]
I've additionally added other stats from kv and called the whole kit and kaboodle "distributed", which was the best name I could come up with.

---

Review status: 3 of 16 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/kv/txn_coord_sender.go, line 146 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15234#-KiCxhFVfhPPtLqzbr4M:-KiFfrpttY8KmbU8eH1G:bz716if) ([raw file](https://github.com/cockroachdb/cockroach/blob/7079dd702fd8e1f841ea7d6aec7fcc4a5f37fde1/pkg/kv/txn_coord_sender.go#L146)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

It looks like this happens when a DelRange restarts due to a forwarded commit timestamp, regardless of isolation. That's what we want (the distinction we want to make is not how many transactions of each isolation level were restarted, but how many would have restarted if the isolation level were changed), but it means this metric is kind of misnamed. 
</blockquote></details>

I've renamed this one to `txn.restarts.delrange`

---

*[pkg/kv/txn_coord_sender.go, line 873 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15234#-KiCwWV_4h66GtSya5jz:-KiFh4HYX0kVcDljXdWI:b-vorth4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7079dd702fd8e1f841ea7d6aec7fcc4a5f37fde1/pkg/kv/txn_coord_sender.go#L873)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

What about POSSIBLE_REPLAY? Is the assumption that those don't make it back to the client?
</blockquote></details>

Oops. Added.

---

*[pkg/roachpb/errors.proto, line 104 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15234#-KiCvjlRHQ2mPOJlxHcZ:-KiFhC4fA78_OlzDsUd7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7079dd702fd8e1f841ea7d6aec7fcc4a5f37fde1/pkg/roachpb/errors.proto#L104)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Copy/paste error. 
</blockquote></details>

Done.

---

*[pkg/storage/store.go, line 2575 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15234#-KiCwIZ7XcDAC9NlAKa8:-KiHFZH97EWtkSt_DYx6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7079dd702fd8e1f841ea7d6aec7fcc4a5f37fde1/pkg/storage/store.go#L2575)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Use the `UNKNOWN` constant. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15234#-:-KiHFeAN96cUOSc29_j8:b83vnuy)*

**Comment by andreimatei** [comment]
Spencer would you mind waiting to merge this for me to be done with #15187? I still have to so some intrusive stuff to the `TxnCoordSender` and I think rebasing this on top of mine would be way easier than the other way around.

---

Review status: 3 of 16 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15234#-:-KiHM8DF70aurJEKCqTc:b6woyp6)*

**Comment by spencerkimball** [comment]
@andreimatei: sure thang.

---

Review status: 3 of 16 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15234#-:-KiHTtOt9qaj95s14eH3:b-m3fhj1)*

**Comment by bdarnell** [comment]
:lgtm: (pending rebase onto #15187)

---

Reviewed 13 of 13 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15234#-:-KiNEMVlBk_d3umQzSgO:b-nxsnl8)*

**Pull request merged**
