### PR TITLE
sql,auth: fix broken NOSQLLOGIN global privilege

### LINKED ISSUE #96465: sql, server: NOSQLLOGIN global privilege does not work
**Describe the problem**

The `GRANT SYSTEM NOSQLLOGIN TO my_user` command does not have any effect.

The NOSQLLOGIN role option works. (`ALTER ROLE my_user WITH NOSQLLOGIN`)

**To Reproduce**

```
root@localhost:26257/defaultdb> create user my_user;
CREATE ROLE

root@localhost:26257/defaultdb> grant system nosqllogin to my_user;
GRANT

## in a different shell, this works but it shouldn't
./cockroach sql --url 'postgresql://my_user@localhost:26257/?sslmode=disable'
```

**Expected behavior**

Expected to see "ERROR: my_user does not have login privilege"

**Environment:**
 CRDB v22.2 and later is affected.

**Additional context**

This code was added in https://github.com/cockroachdb/cockroach/pull/85769 but it didn't have tests, so this was not caught. The bug is due to [this code](https://github.com/cockroachdb/cockroach/blob/ed9928ff27dc70c6d423ec1cebb3840610e26390/pkg/sql/user.go#L196-L213); the check for [HasAdminRole](https://github.com/cockroachdb/cockroach/blob/ed9928ff27dc70c6d423ec1cebb3840610e26390/pkg/sql/user.go#L301-L315) always passes since it's checking for root rather than the user who is logging in.

Jira issue: CRDB-24137

Epic CRDB-17785

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/96465

In addition to the bug fix, this cleans up some code so we don't have to construct planners on the fly during authentication.

Tests were added, since the initial PR that added the NOSQLLOGIN global privilege did not have any tests.

Release note (bug fix): The global NOSQLLOGIN privilege had a bug that made CockroachDB ignore it entirely, so it had no effect. This is now fixed. The bug was introduced in v22.2.0-alpha.1. The NOSQLLOGIN role option is unaffected by this bug.

### CODE REVIEW

**Review by ecwall — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96466)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @Santamaura)

___
*[`pkg/sql/user.go` line 141 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96466#-NNMiWYN4Wtho-a6uEIE:-NNMiWYO9qWRJxydB0ke:bux4il7) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdf550934b246b659502f1bb510fd7ce469e031b/pkg/sql/user.go#L141)):*
> ```Go
> 			// If we already know that the user has CanLoginSQL=true (from the
> 			// NOSQLLOGIN role option), there's no need to check the global privilege.
> 			if authInfo.CanLoginSQL {
> ```

Is the value of `CanLoginSQL` possibly wrong until this block of code corrects it?

**Review by ecwall — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96466)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @Santamaura)

___
*[`pkg/sql/sessioninit/cache_test.go` line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96466#-NNMjH_i68rGA_pBC4nm:-NNMjH_i68rGA_pBC4nn:buvis7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/067dc92538d0d433218c588187263fc93b19985d/pkg/sql/sessioninit/cache_test.go#L76)):*
> ```Go
> 	}
> 	getAuthInfoFromCache := func() (sessioninit.AuthInfo, bool, error) {
> 		makePlanner := func(opName string) (interface{}, func()) {
> ```

Nice work removing this callback. The code is much easier to follow without it.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96466)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @Santamaura)

___
*[`pkg/sql/user.go` line 141 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96466#-NNMiWYN4Wtho-a6uEIE:-NNMob298cXyl93qEj6O:b-wmrxia) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdf550934b246b659502f1bb510fd7ce469e031b/pkg/sql/user.go#L141)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

Is the value of `CanLoginSQL` possibly wrong until this block of code corrects it?
</blockquote></details>

yeah. the reason is that there is both a NOSQLLOGIN role option (older and getting deprecated) and a NOSQLLOGIN global privilege (newer). if either are set, CanLoginSQL should be false. the role options are read inside of the retrieveSessionInitInfoWithCache call above, so we can't easily check both in the same place.

**Review by ecwall — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96466)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @Santamaura)

___
*[`pkg/sql/user.go` line 141 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96466#-NNMiWYN4Wtho-a6uEIE:-NNMsK6P05zuZFQRaPVn:b-dmtmk8) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdf550934b246b659502f1bb510fd7ce469e031b/pkg/sql/user.go#L141)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

yeah. the reason is that there is both a NOSQLLOGIN role option (older and getting deprecated) and a NOSQLLOGIN global privilege (newer). if either are set, CanLoginSQL should be false. the role options are read inside of the retrieveSessionInitInfoWithCache call above, so we can't easily check both in the same place.
</blockquote></details>

Can you keep track of them separately so that the field does not change meaning after this block runs?

Rename `authInfo.CanLoginSQL` -> `authInfo.hasNoSQLLoginRoleOption` and set once when checking the role option.

Create this wrapper type here and populate `hasNoSQLLoginPrivilege`.
```
type AuthInfoWithPrivilege struct {
  AuthInfo
  hasNoSQLLoginPrivilege bool
}

func (a AuthInfoWithPrivilege) CanLoginSQL() {
  return !a.hasNoSQLLoginRoleOption && !a.hasNoSQLLoginPrivilege
}
```

The wrapper should be used anywhere `CanLoginSQL` needs to be checked.


I think using the wrapper will ensure that the `AuthInfo` is not read from directly without reading the privileges first since it is in a possibly invalid state.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96466)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @Santamaura)

___
*[`pkg/sql/user.go` line 141 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96466#-NNMiWYN4Wtho-a6uEIE:-NNMytWODHpJKsHkpmqp:b-934tnh) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdf550934b246b659502f1bb510fd7ce469e031b/pkg/sql/user.go#L141)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

Can you keep track of them separately so that the field does not change meaning after this block runs?

Rename `authInfo.CanLoginSQL` -> `authInfo.hasNoSQLLoginRoleOption` and set once when checking the role option.

Create this wrapper type here and populate `hasNoSQLLoginPrivilege`.
```
type AuthInfoWithPrivilege struct {
  AuthInfo
  hasNoSQLLoginPrivilege bool
}

func (a AuthInfoWithPrivilege) CanLoginSQL() {
  return !a.hasNoSQLLoginRoleOption && !a.hasNoSQLLoginPrivilege
}
```

The wrapper should be used anywhere `CanLoginSQL` needs to be checked.


I think using the wrapper will ensure that the `AuthInfo` is not read from directly without reading the privileges first since it is in a possibly invalid state.
</blockquote></details>

instead of adding a wrapper. i renamed the field in `AuthInfo` to clarify that it's just caching the role option value

the wrapper would have only been used within this one function, so i don't think it would have made the code more clear. (i.e. there would have been zero callers of the new `CanLoginSQL()` function.

**Review by ecwall — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96466)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @Santamaura)

___
*[`pkg/sql/user.go` line 141 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96466#-NNMiWYN4Wtho-a6uEIE:-NNMzqbO49Ot5b789cT9:b-8z07ox) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdf550934b246b659502f1bb510fd7ce469e031b/pkg/sql/user.go#L141)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

instead of adding a wrapper. i renamed the field in `AuthInfo` to clarify that it's just caching the role option value

the wrapper would have only been used within this one function, so i don't think it would have made the code more clear. (i.e. there would have been zero callers of the new `CanLoginSQL()` function.
</blockquote></details>

Oh I see, yeah that is more clear then.

**Comment by ecwall** [comment]
Does this need a backport to 22.2?

**Pull request merged**
