### PR TITLE
raft: remove unused read-only requests

### PR DESCRIPTION
**Pull request by pav-kv**
This PR removes the read-only requests from `pkg/raft`. We don't use them in CRDB, and the leases implementation is known to be incorrect (e.g. see https://github.com/etcd-io/raft/issues/166 and https://github.com/etcd-io/etcd/issues/10082).

Epic: none
Release note: none

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 14 of 14 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120613)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv)

___
*[`-- commits` line 8 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120613#-Nv2OUO12vb99p-VXGxs):*
Does this allow us to delete the `Context` field from the `Message` proto?
___
*[`pkg/raft/raftpb/raft.proto` line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120613#-Nv2O9Ob6RgPP6hpBUwW:-Nv2O9Ob6RgPP6hpBUwX:b-n8plyo) ([raw file](https://github.com/cockroachdb/cockroach/blob/00857da71eb46e6f1d6e67d21cd4cddd06fdcf4c/pkg/raft/raftpb/raft.proto#L69)):*
> ```proto
> 	// raft/util_test.go.
> 
>   reserved 15, 16; // used to be MsgReadIndex(Resp)
> ```

nit: tab to align with above.

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120613)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv)

___
*[`-- commits` line 8 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120613#-Nv2OUO12vb99p-VXGxs):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does this allow us to delete the `Context` field from the `Message` proto?
</blockquote></details>

This field is still used by other bits, e.g. by leader transfers: https://github.com/cockroachdb/cockroach/blob/e89a1a663727028cfca80c7362e7309a73547c1d/pkg/raft/raft.go#L1054.
___
*[`pkg/raft/raftpb/raft.proto` line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120613#-Nv2O9Ob6RgPP6hpBUwW:-Nv2RzqzADwnWI6HBogE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/00857da71eb46e6f1d6e67d21cd4cddd06fdcf4c/pkg/raft/raftpb/raft.proto#L69)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: tab to align with above.
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120613#-:-Nv2kbbk5YE7HiXGHGvq:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv)

**Comment by pav-kv** [comment]
bors r=nvanbenschoten

**Pull request merged**
