### PR TITLE
sqlsmith: teach CREATE INDEX about inverted indexes

### PR DESCRIPTION
**Pull request by madelynnblue**
Also add one to the seed table.

### CODE REVIEW

**Comment by awoods187** [comment]
Exciting!

**Review by yuzefovich — APPROVED** [review]
:lgtm:

TIL about inverted indexes :)

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42555#-:-Lu0JDWw8dzvkihK-Q2Y:b8i4sdp)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
