### PR TITLE
change startTestWriter

### PR DESCRIPTION
**Pull request by tbg**
as (or close to that) suggested by @bdarnell

### CODE REVIEW

**Comment by bdarnell** [comment]
LGTM. I was thinking the channel write would stay in the same place it was before, but I don't think it matters. 

You should be able to change the `txnChannel := make(chan struct{}, 1000)` line below to use the `concurrency` variable too.

**Comment by tschottdorf** [comment]
yeah, while I was at it I put it in an even more appropriate place. I'll change the buffered channel as you suggest.

**Comment by tschottdorf** [comment]
I think we (or at least I) mislead ourselves a little: the `txnChannel` is read from 10 times before **each** split, so writing once for each test writer really only treats the first split specially (which is probably worse). I think the old code managed pretty neatly to have intents around for each split and the buffered channel with a `select {}` to write seems like the right thing to do. Closing this.

**Comment by bdarnell** [comment]
Ah, OK.

**Pull request closed without merging**
