### PR TITLE
roachtest: avoid database backups in for pre-22.1 versions

### LINKED ISSUE #109975: roachtest: backup-restore/mixed-version failed
roachtest.backup-restore/mixed-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11606168?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11606168?buildTab=artifacts#/backup-restore/mixed-version) on release-23.1 @ [58ac87a9b24e1cfb446143dafe04808ea186637f](https://github.com/cockroachdb/cockroach/commits/58ac87a9b24e1cfb446143dafe04808ea186637f):

```
(mixedversion.go:537).Run: mixed-version test failure while running step 35 (run "verify all backups"): 4 errors during restore:
1: 21.2.17: waiting for job to finish: job 896728771340238850 failed with error: restoring 122 TableDescriptors from 6 databases: restoring table desc and namespace entries: table already exists (artifacts collected in restore_failure_1)
2: 21.2.17: waiting for job to finish: job 896728928836190211 failed with error: restoring 122 TableDescriptors from 6 databases: restoring table desc and namespace entries: table already exists (artifacts collected in restore_failure_2)
3: 21.2.17: backup 6_21.2.17-to-22.1.22_database-tpcc_all-planned-and-executed-on-random-node: error in restore statement: pq: at or near "new_db_name": syntax error (artifacts collected in restore_failure_3)
4: 21.2.17: waiting for job to finish: job 896729602538962946 failed with error: restoring 124 TableDescriptors from 8 databases: restoring table desc and namespace entries: table already exists (artifacts collected in restore_failure_4)
test artifacts and logs in: /artifacts/backup-restore/mixed-version/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/p/roachfana/teamcity-11606168-1693719834-21-n5cpu4/1693725444158/1693731903265)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backup-restore/mixed-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-31195

### PR DESCRIPTION
**Pull request by stevendanna**
To validate database backups, we use `new_db_name` to restore the database under a new name.  This feature was added in 22.1 and cannot be used if our cluster is at 21.2.

Here, we only select table or database backups if a 21.2 node is involved in the test.

We could instead come up with an alternate verification strategy on that older version. But I think we get most of the value here with table and cluster backups.

Fixes #109975

Release note: None

Epic: none

### CODE REVIEW

**Comment by renatolabs** [comment]
I think this should work. Alternatively, we could just change the `release-23.1` version of this test and keep master as-is (since this change is not applicable on master).

Passing `mixedversion.MaxUpgrades(2)` to the release-23.1 test will ensure that we run at most 2 upgrades (22.1 -> 22.2 -> current). No point testing a 21.2 -> 22.1 upgrade in that branch: the releases are too old and there might be other incompatibilities.

**Comment by stevendanna** [comment]
@renatolabs That works for me as well.  Even investigating issues against 21.2 is pretty expensive since  the system has changed substantially since then.

**Comment by renatolabs** [comment]
Agreed; sorry about that, I should have caught this before merging the backport.

**Comment by stevendanna** [comment]
Superceded by some other work.

**Pull request closed without merging**
