### PR TITLE
distsql: preserve input ordering in joinreader

### LINKED ISSUE #32108: sql: join processor does not preserve order of left operand
**Describe the problem**

My schema has several interleaved tables that are joined together in a select query. When filtering results using a `where` clause the results come back as expected. When I instead try to filter on the same column in an `on` clause referencing a boolean column that comes back `NULL` in a left join when I'm checking for the value `false` (Yes, it's a mouthful and pretty convoluted) the query fails with `ERROR:  detected badly ordered input.`

Example queries:

Success (Filter on `deleted` in `where`)
```
test_db=> SELECT * FROM cr_users u LEFT JOIN cr_relationships r ON u.user_key=r.user_key LEFT JOIN cr_user_emails e ON u.user_key = e.user_key AND e.deleted = false WHERE (r.deleted IS NOT NULL AND r.deleted = false) AND u.user_key=ANY ARRAY ['5477d5d7-64e3-4e31-979a-8eb59a775214', '4efd269c-f755-4f8b-a7ce-b0d10eba19c3'];
```

Success (Filter on `deleted=true` in `on`)
```
test_db=> SELECT * FROM cr_users u LEFT JOIN cr_relationships r ON u.user_key=r.user_key AND r.deleted = true LEFT JOIN cr_user_emails e ON u.user_key = e.user_key AND e.deleted = false WHERE u.user_key=ANY ARRAY ['5477d5d7-64e3-4e31-979a-8eb59a775214', '4efd269c-f755-4f8b-a7ce-b0d10eba19c3'];
```

Fail (Filter on `deleted=false` in `on`)
```
test_db=> SELECT * FROM cr_users u LEFT JOIN cr_relationships r ON u.user_key=r.user_key AND r.deleted = false LEFT JOIN cr_user_emails e ON u.user_key = e.user_key AND e.deleted = false WHERE u.user_key=ANY ARRAY ['5477d5d7-64e3-4e31-979a-8eb59a775214', '4efd269c-f755-4f8b-a7ce-b0d10eba19c3'];
ERROR:  detected badly ordered input: ...
```

**To Reproduce**

I've attached a sql file taken from our test database (Sorry, I didn't clean up column names and such) that you can use to reproduce.

[backup.txt](https://github.com/cockroachdb/cockroach/files/2539999/backup.txt)

```
cockroach sql --database=... < ~/backup.sql
```
Then run the query:
```
select * from cr_users u left join cr_relationships r on u.user_key=r.user_key and r.deleted = false left join cr_user_emails e on u.user_key = e.user_key and e.deleted = false where u.user_key=any array ['5477d5d7-64e3-4e31-979a-8eb59a775214', '4efd269c-f755-4f8b-a7ce-b0d10eba19c3'];

ERROR:  detected badly ordered input: [***SNIP***] > [***SNIP***], but expected '<'
```
to see the error.

**Expected behavior**
I should get results back not an error.

**Additional data / screenshots**
Attached

**Environment:**
```
$ cockroach version
Build Tag:    v2.1.0
Build Time:   2018/10/30 12:32:34
Distribution: CCL
Platform:     linux amd64 (x86_64-unknown-linux-gnu)
Go Version:   go1.10.3
C Compiler:   gcc 6.3.0
Build SHA-1:  f0dd1dc2d2500155c8b36330ae3d6932c13c1027
Build Type:   release
```

Connected via psql client
```
$ psql --version
psql (PostgreSQL) 10.5
```

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by solongordon**
distsql: preserve input ordering in joinreader

The optimizer presumes the lookup joins preserve the input ordering, but
this was not always the case in the implementation. Specifically in the
case of left joins, joinreader was emitting matched rows prior to
unmatched rows. I fixed this by maintaining a map from input rows to
lookup rows, which we now iterate over in order when emitting rows.

Furthermore, I found that the distsql physical planner was failing to
propagate physical properties for lookup join nodes, so an ordered
synchronizer was not being planned. I fixed this oversight and made the
`planPhysicalProps` function more explicit so we don't make this mistake
again if new plan nodes are added in the future.

Release note (bug fix): Lookup joins now properly preserve ordering for
outer joins. Prior to this fix, LEFT JOIN queries under specific
conditions could produce results which did not respect the ORDER BY
clause.

Fixes #32108

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Thanks for the fix! Do you have any concerns w.r.t overhead? Is there some benchmark we could run?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32317#-:-LRIrKQ71RGfO-ZrcLII:bv6lmqh)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by RaduBerinde** [comment]
Wow, nice find.. I think fixing these in 2.1.2 is reasonable given that we haven't seen any problem reports from users.

**Comment by solongordon** [comment]
Please hold off on reviewing actually. I just took a second look and there are a couple things I'd like to adjust.

**Comment by solongordon** [comment]
All set, PTAL.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32317#-:-LSKwebo16UbQtdbCFo_:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
