### PR TITLE
roachtest: restart chaos'd node on choas ctx cancellation

### PR DESCRIPTION
**Pull request by danhhz**
As of recently, roachtests now assert that all CockroachDB nodes are
running at the end of the test. When chaos is used, we intentionally
bring nodes down for a while and bring them back up. If the choas loop's
ctx is cancelled during one of these periods, the final down node
detector will fire, failing the test. Instead, make sure we bring the
node back up before returning. We were already doing this on stopper
cancellation, this commit simply does the same thing for context
cancellation.

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
:lgtm: merci!

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36492#-:-LbYydmL4Dw_ho6hOMsJ:b-yjmrg0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz)

___
*[pkg/cmd/roachtest/chaos.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36492#-LbYyTVy584P2H_ZBchK:-LbYyTVy584P2H_ZBchL:b-t83vbd) ([raw file](https://github.com/cockroachdb/cockroach/blob/575b70c0de6e4a88696b086156b18e438be54e9c/pkg/cmd/roachtest/chaos.go#L106)):*
> ```Go
> 				// all nodes that have data also have a running process.
> 				l.Printf("restarting %v (chaos is done)\n", target)
> 				c.Start(ctx, c.t.(*test), target)
> ```

While you are here, could you move all `c.Start` methods to use `StartE` and a return branch? This will make the error reporting better.

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36492)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tbg)

___
*[pkg/cmd/roachtest/chaos.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36492#-LbYyTVy584P2H_ZBchK:-LbZ1Jjx1fqb_cgBzHG9:b-wx500t) ([raw file](https://github.com/cockroachdb/cockroach/blob/575b70c0de6e4a88696b086156b18e438be54e9c/pkg/cmd/roachtest/chaos.go#L106)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

While you are here, could you move all `c.Start` methods to use `StartE` and a return branch? This will make the error reporting better.
</blockquote></details>

Something like this?

**Review by tbg — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36492)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @danhhz)

___
*[pkg/cmd/roachtest/chaos.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36492#-LbYyTVy584P2H_ZBchK:-LbZXpG9E_soWbKj_WKK:b-ecsl77) ([raw file](https://github.com/cockroachdb/cockroach/blob/575b70c0de6e4a88696b086156b18e438be54e9c/pkg/cmd/roachtest/chaos.go#L106)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Something like this?
</blockquote></details>

Wonderful, you went above and beyond with all the `Wrapf`s, good call.

**Review by danhhz — COMMENTED** [review]
TFTR!

bors r=tbg

(I almost bors'd btg, heh)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36492#-:-LbZamHZ2nFdysLkzz8x:bnaulu5)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @danhhz)

**Pull request merged**
