### PR TITLE
scripts: add vim syntax file for logic tests

### PR DESCRIPTION
**Pull request by RaduBerinde**
Screenshot:
image

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14374)

### CODE REVIEW

**Comment by benesch** [comment]
Since no one has commented yet: this is awesome! I might try my hand at making the equivalent `.tmLanguage` for us VS Code and Sublime users.

**Comment by andreimatei** [comment]
LGTM :dog: 
awesome!

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[scripts/crlogictest.vim, line 6 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14374#-KgKU4dm_mVXpHjBZBnY:-KgKU4dm_mVXpHjBZBnZ:bj6w2hh) ([raw file](https://github.com/cockroachdb/cockroach/blob/5dc7e4796b5381b0238778cbaa94479995040a3a/scripts/crlogictest.vim#L6)):*
> ```vim
> "
> " Recommended in .vimrc:
> "    autocmd BufNewFile,BufRead */sql/testdata/* set filetype=crlogictest tw=0
> ```

mind telling people where how to tell vim to find this file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14374#-:-KgKUBHBOCOurLUuylA9:bq4equ1)*

**Comment by benesch** [comment]
Now that I think about it, perhaps this would be better in a cockroachdb/vim-sqllogic repository where it can be [installable with Pathogen and Vundle](http://stevelosh.com/blog/2011/09/writing-vim-plugins/#be-pathogen-compatible)? I'm no Vim expert, though, so ignore me if your approach is a more standard way of shipping custom Vim syntaxes.

**Comment by RaduBerinde** [comment]
@benesch That sounds like a great idea.. I just don't have time to look into it right now. I figured this is ok for now, since we already have the `crlog.vim` syntax file in there (used by `log2html.sh` which we didn't end up using in teamcity haha)

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[scripts/crlogictest.vim, line 6 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14374#-KgKU4dm_mVXpHjBZBnY:-KgKYmu-F0R3twhtTxk1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5dc7e4796b5381b0238778cbaa94479995040a3a/scripts/crlogictest.vim#L6)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

mind telling people where how to tell vim to find this file?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14374#-:-KgKYpP9lupcJcr1UbcZ:bxnoj1e)*

**Pull request merged**
