### PR TITLE
roachtest: add roachtest for postgres nodejs driver

### LINKED ISSUE #63116: roachtest: add pg (nodejs) driver test suite to nightly

### PR DESCRIPTION
**Pull request by RichardJCai**
roachtest: add roachtest for postgres nodejs driver

Release note: None

Fixes #63116

### CODE REVIEW

**Comment by RichardJCai** [comment]
Had to change the test to work off my branch but this is ready for review.

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63344)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[BUILD.bazel, line 200 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63344#-MYjr3dx6kJKu_2-k1pQ:-MYjr3dx6kJKu_2-k1pR:bq6aryk) ([raw file](https://github.com/cockroachdb/cockroach/blob/20523adc5b71a227142239bd54f46134eeed39eb/BUILD.bazel#L200)):*
> ```Starlark
> ])
> 
> go_library(
> ```

what is this doing? i'm surprised we have to chance the root bazel config to add a test
___
*[pkg/cmd/roachtest/canary.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63344#-MYjrHYmEidiXo3LiUbO:-MYjrHYmEidiXo3LiUbP:bmdquhn) ([raw file](https://github.com/cockroachdb/cockroach/blob/20523adc5b71a227142239bd54f46134eeed39eb/pkg/cmd/roachtest/canary.go#L70)):*
> ```Go
> // If optional args are passed, it is assumed we want to create a secure conn
> // and that arg[0] is the username, arg[1] is the certificate directory
> // arg[2] is the port.
> ```

i think it would be better to introduce a new function that accepts username, cert, port as named parameters. (or as a config struct with those parameters) -- one of the first two options here: https://petomalina.medium.com/dealing-with-optional-parameters-in-go-9780f9bfbd1d

the existing insecure function can delegate to the new function you add
___
*[pkg/cmd/roachtest/cluster.go, line 2408 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63344#-MYjsLK76zECJKKsp0g6:-MYjsLK76zECJKKsp0g7:b-kvugeo) ([raw file](https://github.com/cockroachdb/cockroach/blob/20523adc5b71a227142239bd54f46134eeed39eb/pkg/cmd/roachtest/cluster.go#L2408)):*
> ```Go
> // nodes.
> func (c *cluster) ExternalPGUrlSecure(
> 	ctx context.Context, node nodeListOption, user string, certsDir string, port string,
> ```

any reason to have port as a string instead of int?
___
*[pkg/cmd/roachtest/cluster.go, line 2540 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63344#-MYjsO9TDV91e8d6ikKl:-MYjsO9TDV91e8d6ikKm:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/20523adc5b71a227142239bd54f46134eeed39eb/pkg/cmd/roachtest/cluster.go#L2540)):*
> ```Go
> // ConnSecure returns a secure SQL connection to the specified node.
> func (c *cluster) ConnSecure(
> 	ctx context.Context, node int, user string, certsDir string, port string,
> ```

ditto
___
*[pkg/cmd/roachtest/orm_helpers.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63344#-MYjsRv18iKz5CDycGut:-MYjsRv18iKz5CDycGuu:bvtgiwq) ([raw file](https://github.com/cockroachdb/cockroach/blob/20523adc5b71a227142239bd54f46134eeed39eb/pkg/cmd/roachtest/orm_helpers.go#L27)):*
> ```Go
> // rapidly, thereby decreasing performance.
> func alterZoneConfigAndClusterSettings(
> 	ctx context.Context, version string, c *cluster, nodeIdx int, args ...string,
> ```

i think having user, cert, port as varargs like this is too obfuscated
___
*[pkg/cmd/roachtest/postgres_node.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63344#-MYjqawdDrBd3I2rHEQr:-MYjqawdDrBd3I2rHEQs:bryit2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/20523adc5b71a227142239bd54f46134eeed39eb/pkg/cmd/roachtest/postgres_node.go#L29)):*
> ```Go
> var supportedBranch = "allowing_passing_certs_through_pg_env"
> 
> func registerPostgresNode(r *testRegistry) {
> ```

nit: I think `PostgresNode` is a potentially confusing name, since it sounds like we're talking about a node of a Postgres server. Can we call it `PostgresNodeJS`? (and also rename this file)
___
*[pkg/cmd/roachtest/postgres_node.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63344#-MYjsgc40erZ_ShsdCij:-MYjsgc40erZ_ShsdCik:b3ax03m) ([raw file](https://github.com/cockroachdb/cockroach/blob/20523adc5b71a227142239bd54f46134eeed39eb/pkg/cmd/roachtest/postgres_node.go#L50)):*
> ```Go
> 		require.NoError(t, err)
> 
> 		err = c.RunE(ctx, node,
> ```

i think this should be using `repeatRunE()` -- that also lets you pass in a description of what the command is doing
___
*[pkg/cmd/roachtest/postgres_node.go, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63344#-MYjsvK28e9TgNFa4qEK:-MYjsvK28e9TgNFa4qEL:bdeq756) ([raw file](https://github.com/cockroachdb/cockroach/blob/20523adc5b71a227142239bd54f46134eeed39eb/pkg/cmd/roachtest/postgres_node.go#L84)):*
> ```Go
> 		})
> 
> 		urls := c.ExternalPGUrlSecure(ctx, node, user, certsDir, "26257")
> ```

most of the setup up to here maybe could be extracted to a function in orm_helpers.go to make it easier to make secure clusters in other tests too
___
*[pkg/cmd/roachtest/postgres_node.go, line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63344#-MYjt8ZM0iQLpxlyJW86:-MYjt8ZM0iQLpxlyJW87:b5x4h17) ([raw file](https://github.com/cockroachdb/cockroach/blob/20523adc5b71a227142239bd54f46134eeed39eb/pkg/cmd/roachtest/postgres_node.go#L123)):*
> ```Go
> 
> 		err = repeatRunE(
> 			ctx, c, node, "remove old postgres-node", `sudo rm -rf /mnt/data1/postgres-node`,
> ```

isn't it called `node-postgres` technically?
___
*[pkg/cmd/roachtest/postgres_node.go, line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63344#-MYjtF-_5C22OHygJERv:-MYjtF-_5C22OHygJERw:b-wfid4u) ([raw file](https://github.com/cockroachdb/cockroach/blob/20523adc5b71a227142239bd54f46134eeed39eb/pkg/cmd/roachtest/postgres_node.go#L142)):*
> ```Go
> 			c,
> 			node,
> 			"building postgres-node",
> ```

nit: `node-postgres`
___
*[pkg/cmd/roachtest/postgres_node.go, line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63344#-MYjtIJL0GfTvMnULEV0:-MYjtIJL0GfTvMnULEV1:b-wfid4u) ([raw file](https://github.com/cockroachdb/cockroach/blob/20523adc5b71a227142239bd54f46134eeed39eb/pkg/cmd/roachtest/postgres_node.go#L147)):*
> ```Go
> 		require.NoError(t, err)
> 
> 		t.Status("running postgres-node tests")
> ```

nit: `node-postgres`
___
*[pkg/cmd/roachtest/postgres_node.go, line 164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63344#-MYjtaYh5Jdfch6rD_sU:-MYjtaYh5Jdfch6rD_sV:b-xyrttl) ([raw file](https://github.com/cockroachdb/cockroach/blob/20523adc5b71a227142239bd54f46134eeed39eb/pkg/cmd/roachtest/postgres_node.go#L164)):*
> ```Go
> 			// not implemented in CRDB.
> 			if strings.Contains(rawResultsStr, "1 failing") &&
> 				strings.Contains(rawResultsStr, "Error: expected [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] to sort of equal [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ]") {
> ```

is there a way to filter based on the test name rather than the error message? just seems like it would be easier to read the code that way

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63344)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[pkg/cmd/roachtest/postgres_node.go, line 178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63344#-MYjuKl15qdCv4cF6y-N:-MYjuKl15qdCv4cF6y-O:bqtaia9) ([raw file](https://github.com/cockroachdb/cockroach/blob/20523adc5b71a227142239bd54f46134eeed39eb/pkg/cmd/roachtest/postgres_node.go#L178)):*
> ```Go
> 		Cluster:    makeClusterSpec(1),
> 		MinVersion: "v20.1.0",
> 		Tags:       []string{`default`, `orm`},
> ```

the tag should be `default, driver` -- this is a driver not ORM

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63344)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[BUILD.bazel, line 200 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63344#-MYjr3dx6kJKu_2-k1pQ:-MYkKIPz2y45MiqkyJRv:b-e9hbao) ([raw file](https://github.com/cockroachdb/cockroach/blob/20523adc5b71a227142239bd54f46134eeed39eb/BUILD.bazel#L200)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

what is this doing? i'm surprised we have to chance the root bazel config to add a test
</blockquote></details>

Yeah I'm not sure I just did a `make bazel-generate` I'll remove and see if it complains.
___
*[pkg/cmd/roachtest/canary.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63344#-MYjrHYmEidiXo3LiUbO:-MYkHvaoCvMq0RCoQ3op:b-giwa57) ([raw file](https://github.com/cockroachdb/cockroach/blob/20523adc5b71a227142239bd54f46134eeed39eb/pkg/cmd/roachtest/canary.go#L70)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think it would be better to introduce a new function that accepts username, cert, port as named parameters. (or as a config struct with those parameters) -- one of the first two options here: https://petomalina.medium.com/dealing-with-optional-parameters-in-go-9780f9bfbd1d

the existing insecure function can delegate to the new function you add
</blockquote></details>

Took the suggestion to add a config struct, delegating made less sense here since since the only different part is creating the connection. Thought about passing the connection into the function instead but that duplicates code for creating the conn.
___
*[pkg/cmd/roachtest/cluster.go, line 2408 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63344#-MYjsLK76zECJKKsp0g6:-MYkIBXZ7NwMm4Lp6wt4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/20523adc5b71a227142239bd54f46134eeed39eb/pkg/cmd/roachtest/cluster.go#L2408)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

any reason to have port as a string instead of int?
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/cluster.go, line 2540 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63344#-MYjsO9TDV91e8d6ikKl:-MYkIBsC-rl2FpnY8xNO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/20523adc5b71a227142239bd54f46134eeed39eb/pkg/cmd/roachtest/cluster.go#L2540)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/orm_helpers.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63344#-MYjsRv18iKz5CDycGut:-MYkICW0-XJQeu6sAhqI:bvosu4t) ([raw file](https://github.com/cockroachdb/cockroach/blob/20523adc5b71a227142239bd54f46134eeed39eb/pkg/cmd/roachtest/orm_helpers.go#L27)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think having user, cert, port as varargs like this is too obfuscated
</blockquote></details>

Updated to be same as `fetchCockroachVersion`
___
*[pkg/cmd/roachtest/postgres_node.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63344#-MYjqawdDrBd3I2rHEQr:-MYkIY3o6jGvEqqFTXI6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/20523adc5b71a227142239bd54f46134eeed39eb/pkg/cmd/roachtest/postgres_node.go#L29)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: I think `PostgresNode` is a potentially confusing name, since it sounds like we're talking about a node of a Postgres server. Can we call it `PostgresNodeJS`? (and also rename this file)
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/postgres_node.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63344#-MYjsgc40erZ_ShsdCij:-MYkJNwgDq8Db1kHPwQI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/20523adc5b71a227142239bd54f46134eeed39eb/pkg/cmd/roachtest/postgres_node.go#L50)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think this should be using `repeatRunE()` -- that also lets you pass in a description of what the command is doing
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/postgres_node.go, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63344#-MYjsvK28e9TgNFa4qEK:-MYkJjL-9LyDKj6FQqec:bfexqxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/20523adc5b71a227142239bd54f46134eeed39eb/pkg/cmd/roachtest/postgres_node.go#L84)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

most of the setup up to here maybe could be extracted to a function in orm_helpers.go to make it easier to make secure clusters in other tests too
</blockquote></details>

Not sure exactly what to extract as of now. Probably creating certs / and `alterZoneConfigAndClusterSettings` can be extracted but I think it's not worth extracting until we know what pattern is common. I'll keep it in mind when I update the ruby one to secure as well.
___
*[pkg/cmd/roachtest/postgres_node.go, line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63344#-MYjt8ZM0iQLpxlyJW86:-MYkJR_B-mWkCP0K6VTb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/20523adc5b71a227142239bd54f46134eeed39eb/pkg/cmd/roachtest/postgres_node.go#L123)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

isn't it called `node-postgres` technically?
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/postgres_node.go, line 164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63344#-MYjtaYh5Jdfch6rD_sU:-MYkJesC6T9lFC4C796n:b-u12c93) ([raw file](https://github.com/cockroachdb/cockroach/blob/20523adc5b71a227142239bd54f46134eeed39eb/pkg/cmd/roachtest/postgres_node.go#L164)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

is there a way to filter based on the test name rather than the error message? just seems like it would be easier to read the code that way
</blockquote></details>

Changed to filter based on test name
___
*[pkg/cmd/roachtest/postgres_node.go, line 178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63344#-MYjuKl15qdCv4cF6y-N:-MYkJiPX8tYQ-nv6m9I0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/20523adc5b71a227142239bd54f46134eeed39eb/pkg/cmd/roachtest/postgres_node.go#L178)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

the tag should be `default, driver` -- this is a driver not ORM
</blockquote></details>

Done.

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63344)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/cmd/roachtest/canary.go, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63344#-MYpDZGXAMQiXyc9WkE7:-MYpDZGXAMQiXyc9WkE8:b-fo0t12) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad4da227f1f65c5efe6bf35262fb4e7c0e4401b3/pkg/cmd/roachtest/canary.go#L66)):*
> ```Go
> // NewDBConnectionParams creates a DBConnectionParams struct for creating
> // an insecure connection.
> func NewDBConnectionParams() *DBConnectionParams {
> ```

nit: it seems like we don't really need this -- we could just pass `nil` instead of calling this to make an empty one

if you think that's a good idea, then the type could be renamed to `SecureDBConnectionParams` and the `secure` flag could be removed from it. (and the functiom below renamed to `NewSecureDBConnectionParams`

if you disagree, then i'm fine to go ahead as is!

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63344)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/cmd/roachtest/canary.go, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63344#-MYpDZGXAMQiXyc9WkE7:-MYq-PhsEYBOZkHLmETf:b-fznogt) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad4da227f1f65c5efe6bf35262fb4e7c0e4401b3/pkg/cmd/roachtest/canary.go#L66)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: it seems like we don't really need this -- we could just pass `nil` instead of calling this to make an empty one

if you think that's a good idea, then the type could be renamed to `SecureDBConnectionParams` and the `secure` flag could be removed from it. (and the functiom below renamed to `NewSecureDBConnectionParams`

if you disagree, then i'm fine to go ahead as is!
</blockquote></details>

Good idea, done.

**Review by rafiss — APPROVED** [review]
lgtm!

> Reviewed 19 of 19 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63344#-:-MYzG0AQ8IgmCRGzX2wY:b-7nbn20)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Comment by RichardJCai** [comment]
Thanks! 

bors r=rafiss

**Comment by RichardJCai** [comment]
Merge skew with #63958

**Comment by RichardJCai** [comment]
bors r=rafiss

**Comment by RichardJCai** [comment]
bors r=rafiss

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63344)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/cluster.go, line 2628 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63344#-MZUmOb151mahidlNLMz:-MZUmOb151mahidlNLN-:bjp6cy6) ([raw file](https://github.com/cockroachdb/cockroach/blob/532f060700dc97bb0432fd4a0a7e12f45b24c605/pkg/cmd/roachtest/cluster.go#L2628)):*
> ```Go
> 	ctx context.Context, node int, user string, certsDir string, port int,
> ) (*gosql.DB, error) {
> 	url := c.ExternalPGUrlSecure(ctx, c.Node(node), user, certsDir, port)[0]
> ```

please don't call fatal-ing functions (like `ExternalPGUrlSecure`) from error-returning functions. The error-returning functions indicate that they're safe to call on goroutines other than a test's main goroutine. On such goroutines, it's illegal to Fatal (just like in unit tests).
In fact, please don't introduce any new fataling methods to `cluster`; it was a mistake to ever have them and we've been trying to dig ourselves up from the whole. Where you're not willing to modify existing fataling functions (because they have too many callers), make a new `fooE` flavor that returns an error.

Do you mind kindly fixing?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63344)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/cluster.go, line 2628 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63344#-MZUmOb151mahidlNLMz:-MZUo1m0Ay_xpjxj-U5p:bii68bp) ([raw file](https://github.com/cockroachdb/cockroach/blob/532f060700dc97bb0432fd4a0a7e12f45b24c605/pkg/cmd/roachtest/cluster.go#L2628)):*
> make a new fooE flavor that returns an error.

And mark the old one as deprecated, I wanted to say.

**Comment by RichardJCai** [comment]
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63344)_ status: :shipit: complete! 0 of 0 LGTMs obtained
> 
> _[pkg/cmd/roachtest/cluster.go, line 2628 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63344#-MZUmOb151mahidlNLMz:-MZUmOb151mahidlNLN-:bjp6cy6) ([raw file](https://github.com/cockroachdb/cockroach/blob/532f060700dc97bb0432fd4a0a7e12f45b24c605/pkg/cmd/roachtest/cluster.go#L2628)):_
> 
> > ```go
> > 	ctx context.Context, node int, user string, certsDir string, port int,
> > ) (*gosql.DB, error) {
> > 	url := c.ExternalPGUrlSecure(ctx, c.Node(node), user, certsDir, port)[0]
> > ```
> 
> please don't call fatal-ing functions (like `ExternalPGUrlSecure`) from error-returning functions. The error-returning functions indicate that they're safe to call on goroutines other than a test's main goroutine. On such goroutines, it's illegal to Fatal (just like in unit tests).
> In fact, please don't introduce any new fataling methods to `cluster`; it was a mistake to ever have them and we've been trying to dig ourselves up from the whole. Where you're not willing to modify existing fataling functions (because they have too many callers), make a new `fooE` flavor that returns an error.
> 
> Do you mind kindly fixing?

Thanks for catching this, will fix.

**Pull request merged**
