### PR TITLE
sql/opt: add session setting to disable stats forecast use in optimizer

### PR DESCRIPTION
**Pull request by michae2**
Add a new session setting, `optimizer_use_forecasts`, which can be used
to disable forecast usage in the optimizer. Forecasts will still be
generated in the stats cache (this will be controlled by a different
setting).

Assists: #86350

Release justification: Low-risk update to new functionality.

Release note (sql change): This commit adds a new session setting,
`optimizer_use_forecasts`, which can be set to false to disable usage of
statistics forecasts when optimizing a query.

### CODE REVIEW

**Comment by michae2** [comment]
Note that the first two commits are #86634 and can be ignored.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86834#-:-NALUYdb-BkCwoNjA7Ny:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @michae2)

___
*[`pkg/sql/logictest/testdata/logic_test/crdb_internal` line 788 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86834#-NALTemt7gc5SlebZJ4W:-NALTemu0x9cosHTUuvC:b2tndnw) ([raw file](https://github.com/cockroachdb/cockroach/blob/67f9187f7058056b64b36778cda7fd3e265bab6f/pkg/sql/logictest/testdata/logic_test/crdb_internal#L788)):*
> ```
> # Ensure that there are no longer any splits left over on the original indexes.
> # TRUNCATE will have created equivalent splits points on the new indexes, so
> # this test just checks that there are no more on the old indexes.
> ```

Does this comment need an update?

**Review by michae2 — COMMENTED** [review]
TFTR!

bors r=rytaft

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86834#-:-NANlM1n-U69yXYXSvq3:b-owjbl9)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach, @mgartner, and @rytaft)

___
*[`pkg/sql/logictest/testdata/logic_test/crdb_internal` line 788 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86834#-NALTemt7gc5SlebZJ4W:-NANkQKc7O6SFT-iuIvV:b-fkfq29) ([raw file](https://github.com/cockroachdb/cockroach/blob/67f9187f7058056b64b36778cda7fd3e265bab6f/pkg/sql/logictest/testdata/logic_test/crdb_internal#L788)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Does this comment need an update?
</blockquote></details>

Ah, this snuck in from a `./dev testlogic --config=local --rewrite`. I've reverted it. (I think the `retry` hides the flakiness?)

**Comment by michae2** [comment]
"Cannot find commit" hmm. Let's try this again with a rebase.

bors r=rytaft

**Pull request merged**
