### PR TITLE
release-2.0: importccl: Preserve '\r\n' during CSV import

### PR DESCRIPTION
**Pull request by dt**
Backport 1/1 commits from #28181.

/cc @cockroachdb/release

---

See #25344.

### CODE REVIEW

**Review by benesch — APPROVED** [review]
Backport LGTM but please double-check with @bdarnell!

**Review by neeral — COMMENTED** [review]
Note: import_stmt_test.go in master was renamed from csv_test.go in branch release-2.0 -- the unit test from #28181 hasn't made it into this PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28225#-:-LIyTAfyCZyiXABNOxs8:b-bluhfv)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by bdarnell — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28225)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/util/encoding/csv/example_test.go, line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28225#-LJ-nUt0-qN2GzT9bG7K:-LJ-nUt0-qN2GzT9bG7L:b-735guk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7872a97d1a0ce6e4d0788f76e06cfe1ffe83272d/pkg/util/encoding/csv/example_test.go#L3)):*
> ```Go
> // Copyright 2015 The Go Authors. All rights reserved.
> // Use of this source code is governed by a BSD-style
> // license that can be found in the LICENSE file.
> ```

The copyright headers in all copied files need to be updated to point to the license in licenses/BSD-golang.txt (see syncutil for an example)

**Comment by dt** [comment]
nice catch! cherrypicked #28283 into this to fix the headers too. @neeral Yeah, I'd originally just nuked the test since I thought we didn't have the larger test runner it was in on the 2.0 branch, but I looked again just now and saw the byte reader test to which i've added it.

**Review by benesch — APPROVED** [review]

**Comment by dt** [comment]
now just need to run the flaky 2.0 test gauntlet

**Pull request merged**
