### PR TITLE
server,cli: ensure the server identifiers are properly logged in SQL pds

### PR DESCRIPTION
**Pull request by knz**
This is a forward-port of a change (#58708) we've discovered was necessary in v20.2.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
Now also includes roachtest.

**Comment by knz** [comment]
Nb: the `log.TestingClearServerIdentifier()` logic is ugly but hard to avoid until we fix #58938

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 6 of 9 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58862#-:-MR0cufj6x5kZB0CaTxF:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

**Comment by knz** [comment]
thanks!

bors r=itsbilal

**Pull request merged**
