### PR TITLE
cherrypick: sql: restore sanity in the handling of special column names (#16815)

### LINKED ISSUE #16813: sql: catastrophic handling of special characters in column names (1/2)
This one, with views

```
> create table foo("x;y" int);
> create view waa as select @1 from foo;
> select * from waa;
pq: failed to parse underlying query from view "waa": syntax error at or near "y"
SELECT x;y FROM t.foo
```

cc @cockroachdb/sql-language

### LINKED ISSUE #16814: sql: catastrophic handling of special characters in column names (2/2)
```
> create table foo("x;y" int);
> create table waa as select @1 from foo;
driver: bad connection
connection lost; opening new connection: all session settings will be lost
error retrieving the transaction status: driver: bad connection
```

Server crash:
```
        panic: panic while executing "create table waa as select @1 from foo;": indexed var linked to different container (*sql.renderNode) &{planner:0xc4214681c8 source:{info:0xc420322840 plan:0xc42080a000} sourceInfo:[0xc420322840] ivarHelper:{vars:[{Idx:0 container:0xc420466400} {Idx:0 container:<nil>}] container:0xc420466400} render:[0xc421056000] columns:[{Name:@1 Typ:{} Hidden:false Omitted:false}] isStar:false numOriginalCols:1 ordering:{exactMatchCols:map[] ordering:[] unique:false} curSourceRow:[] row:[] noCopy:{}}, expected (*sql.renderNode) &{planner:0xc4214681c8 source:{info:0xc420588e40 plan:0xc421050000} sourceInfo:[0xc420588e40] ivarHelper:{vars:[{Idx:0 container:<nil>} {Idx:0 container:<nil>}] container:0xc42067ce00} render:[] columns:[] isStar:false numOriginalCols:0 ordering:{exactMatchCols:map[] ordering:[] unique:false} curSourceRow:[] row:[] noCopy:{}}

goroutine 234 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc4205a3950, 0x7f5a08d5b1c8, 0xc4204e25d0)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:180 +0xb1
panic(0x193c180, 0xc42034d840)
        /mnt/kena/go1.8/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve.func1(0xc421474600, 0x7f5a08d5b1c8, 0xc420acb140)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:360 +0xa1
panic(0x193c180, 0xc42034d840)
        /mnt/kena/go1.8/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql.(*Session).maybeRecover(0xc421468000, 0x1ae42ea, 0x9, 0xc42146b2ca, 0x27)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/sql/session.go:1072 +0x298
panic(0x188b6c0, 0xc4201e7370)
        /mnt/kena/go1.8/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql/parser.(*IndexedVarHelper).AssertSameContainer(0xc4214699a0, 0xc4202f4ea0)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/indexed_vars.go:139 +0x18c
github.com/cockroachdb/cockroach/pkg/sql.(*nameResolutionVisitor).VisitPre(0xc421469960, 0x27c8100, 0xc4202f4ea0, 0x10, 0x188ac00, 0xc4202f4e01)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/sql/select_name_resolution.go:74 +0x3b7
github.com/cockroachdb/cockroach/pkg/sql/parser.WalkExpr(0x27b6c80, 0xc421469960, 0x27c8100, 0xc4202f4ea0, 0x1, 0x1, 0x0)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/walk.go:555 +0x4c
github.com/cockroachdb/cockroach/pkg/sql.(*planner).resolveNames(0xc4214681c8, 0x27c8100, 0xc4202f4ea0, 0xc4203f0138, 0x1, 0x1, 0xc42177f170, 0x2, 0x2, 0x27bfe40, ...)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/sql/select_name_resolution.go:201 +0x205
github.com/cockroachdb/cockroach/pkg/sql.(*planner).analyzeExpr(0xc4214681c8, 0x7f5a08d5b1c8, 0xc420395500, 0x27c8100, 0xc4202f4ea0, 0xc4203f0138, 0x1, 0x1, 0xc42177f170, 0x2, ...)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/sql/analyze.go:1654 +0x28d
github.com/cockroachdb/cockroach/pkg/sql.(*planner).computeRender(0xc4214681c8, 0x7f5a08d5b1c8, 0xc420395500, 0x27c8100, 0xc4202f4ea0, 0x0, 0x0, 0x27cef80, 0x2c862c0, 0xc4203f0138, ...)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/sql/targets.go:48 +0x164
github.com/cockroachdb/cockroach/pkg/sql.(*planner).computeRenderAllowingStars(0xc4214681c8, 0x7f5a08d5b1c8, 0xc420395500, 0x27c8100, 0xc4202f4ea0, 0x0, 0x0, 0x27cef80, 0x2c862c0, 0xc4203f0138, ...)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/sql/targets.go:78 +0x21c
github.com/cockroachdb/cockroach/pkg/sql.(*renderNode).initTargets(0xc42067ce00, 0x7f5a08d5b1c8, 0xc420395500, 0xc4202f4ee0, 0x1, 0x1, 0xc42034d7c0, 0x2, 0x2, 0x1, ...)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/sql/render.go:338 +0x29a
github.com/cockroachdb/cockroach/pkg/sql.(*planner).SelectClause(0xc4214681c8, 0x7f5a08d5b1c8, 0xc420395500, 0xc420162bd0, 0x0, 0x0, 0x0, 0x0, 0xc42034d7c0, 0x2, ...)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/sql/render.go:233 +0x2dc
github.com/cockroachdb/cockroach/pkg/sql.(*planner).newPlan(0xc4214681c8, 0x7f5a08d5b1c8, 0xc420395500, 0x27c8540, 0xc420162bd0, 0xc42034d7c0, 0x2, 0x2, 0x2, 0xc42034d620, ...)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:325 +0x105a
github.com/cockroachdb/cockroach/pkg/sql.(*planner).Insert(0xc4214681c8, 0x7f5a08d5b1c8, 0xc420395500, 0xc4213cddb0, 0x0, 0x0, 0x0, 0x19a1c00, 0xc421057b60, 0x0, ...)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/sql/insert.go:122 +0x4ea
github.com/cockroachdb/cockroach/pkg/sql.(*createTableNode).Start(0xc42162fef0, 0x7f5a08d5b1c8, 0xc420395500, 0x0, 0x0)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/sql/create.go:688 +0xae1
github.com/cockroachdb/cockroach/pkg/sql.(*planner).startPlan(0xc4214681c8, 0x7f5a08d5b1c8, 0xc420395500, 0x27c6c80, 0xc42162fef0, 0x0, 0xffffffee)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:208 +0x8e
```

### PR DESCRIPTION
**Pull request by knz**
Fixes #16813.
Fixes #16814.

### CODE REVIEW

**Comment by bdarnell** [comment]
LGTM, but it needs a test.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16783#-:-KnoRw5ouNpDupjiVgW5:b-x96w4v)*

**Comment by knz** [comment]
Will incorporate tests and additional fixes from #16815 when it merges.

**Comment by knz** [comment]
done

**Review by bdarnell — APPROVED** [review]

**Comment by knz** [comment]
Has 1.0.3 been cut already?

**Comment by jordanlewis** [comment]
It can go into 1.0.4.

**Pull request merged**
