### PR TITLE
acceptanceccl: SET CLUSTER SETTING enterprise.enabled

### PR DESCRIPTION
**Pull request by dt**

### CODE REVIEW

**Comment by danhhz** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/ccl/acceptanceccl/backup_test.go, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14855#-KhYR-QwDd_iXcPMbcmi:-KhYR-QwDd_iXcPMbcmj:bahjw73) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ecb3627d5f83384f61c0ab8c75d132cfc55c376/pkg/ccl/acceptanceccl/backup_test.go#L80)):*
> ```Go
> 	}
> 	defer sqlDB.Close()
> 	sqlutils.MakeSQLRunner(bt.b, sqlDB).Exec("SET CLUSTER SETTING enterprise.enabled = true")
> ```

seems just as easy to inline the error checking ¯\_(ツ)_/¯

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14855#-:-KhYR7Ja6JrjJVX2cnTc:bnfp4nl)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/ccl/acceptanceccl/backup_test.go, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14855#-KhYR-QwDd_iXcPMbcmi:-KhYVNeh1t7xK5Uoyqat:b-m77ynf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ecb3627d5f83384f61c0ab8c75d132cfc55c376/pkg/ccl/acceptanceccl/backup_test.go#L80)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

seems just as easy to inline the error checking ¯\_(ツ)_/¯
</blockquote></details>

That would make sqlDB out of scope after the if block.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14855#-:-KhYVSg47ObtfaG5Pr6Y:bnfp4nl)*

**Comment by dt** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ccl/acceptanceccl/backup_test.go, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14855#-KhYR-QwDd_iXcPMbcmi:-KhYU91ok6U6xgbEsyYZ:b-uhauly) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ecb3627d5f83384f61c0ab8c75d132cfc55c376/pkg/ccl/acceptanceccl/backup_test.go#L80)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

That would make sqlDB out of scope after the if block.
</blockquote></details>

how would that change the scope of sqlDB?  it goes out of scop at the end of the function (the line below this) no matter what, no? we're not holding a reference to the runner or anything.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14855)*

**Comment by dt** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ccl/acceptanceccl/backup_test.go, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14855#-KhYR-QwDd_iXcPMbcmi:-KhY_JapeXkezkK1aDUb:b-35babf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ecb3627d5f83384f61c0ab8c75d132cfc55c376/pkg/ccl/acceptanceccl/backup_test.go#L80)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

how would that change the scope of sqlDB?  it goes out of scop at the end of the function (the line below this) no matter what, no? we're not holding a reference to the runner or anything.
</blockquote></details>

I mean, you could try to define it inline with it's `err != nil` check `Open`, but then you'd need to put all this in an `else` and we have a linter that would then tell you to just take it out of the `else` for some reason.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14855)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ccl/acceptanceccl/backup_test.go, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14855#-KhYR-QwDd_iXcPMbcmi:-KhYaKU-Vu2ze-2D3Qxb:bmgpz67) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ecb3627d5f83384f61c0ab8c75d132cfc55c376/pkg/ccl/acceptanceccl/backup_test.go#L80)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I mean, you could try to define it inline with it's `err != nil` check `Open`, but then you'd need to put all this in an `else` and we have a linter that would then tell you to just take it out of the `else` for some reason.
</blockquote></details>

The linter doesn't "understand" b.Fatal, so it won't complain.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14855)*

**Comment by dt** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ccl/acceptanceccl/backup_test.go, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14855#-KhYR-QwDd_iXcPMbcmi:-KhYbN_VOghRWjKZEDAK:b-8r8m43) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ecb3627d5f83384f61c0ab8c75d132cfc55c376/pkg/ccl/acceptanceccl/backup_test.go#L80)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

The linter doesn't "understand" b.Fatal, so it won't complain.
</blockquote></details>

well, theoretically it's motivation still holds even if it isn't able to spot this case?

anyway, does anyone have a preference for any particular combination of err checks here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14855)*

**Comment by mjibson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ccl/acceptanceccl/backup_test.go, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14855#-KhYR-QwDd_iXcPMbcmi:-KhYikhPG4X5kXE4Kcss:bsz44pv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ecb3627d5f83384f61c0ab8c75d132cfc55c376/pkg/ccl/acceptanceccl/backup_test.go#L80)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

well, theoretically it's motivation still holds even if it isn't able to spot this case?

anyway, does anyone have a preference for any particular combination of err checks here?
</blockquote></details>

My preference is to merge as is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14855)*

**Pull request merged**
