### PR TITLE
roachtest: skip multitenant/fairness

### PR DESCRIPTION
**Pull request by yuzefovich**
Informs: #82926.

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: Thanks!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83340#-:-N5LfWiZ3aRRxx0DVo63:b-g2a5fb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @mgartner)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Review by mgartner — APPROVED** [review]
Thanks!!!

**Comment by cucaroach** [comment]
I think this was fixed: https://github.com/cockroachdb/cockroach/pull/82927

**Pull request merged**
