### PR TITLE
distsqlpb: split processors

### PR DESCRIPTION
**Pull request by RaduBerinde**
The processors file has gotten very unwieldy over time. Splitting into
sql, bulk-io, changefeeds, table-stats.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Ping - nothing to review (stuff just moved around), just need a confirmation that it's ok to split these.

**Comment by jordanlewis** [comment]
I don't see a reason why you couldn't split these. LGTM.

You didn't rename any messages, right? That can mess stuff up. You might want to briefly test on a cross-version cluster... we should probably write a simple set of tests for that.

**Comment by RaduBerinde** [comment]
No changes. BTW the min accepted version was bumped in #36943 anyway, so there won't be interop with pre-19.2.

**Comment by jordanlewis** [comment]
Yeah, but you can still break things if you change the message names in weird enough ways. I made that mistake when moving some of the protos to a different package.

**Comment by RaduBerinde** [comment]
Tested a distributed query on two nodes (with and without this PR).

bors r+

**Pull request merged**
