### PR TITLE
cli: sanitize the host/port command-line flags

### LINKED ISSUE #27702: cli: More clearly differentiate between node listening and node advertising
Currently, there's a confusing permutation of effects that can result from using `--host` and `--advertise-host`:

|   | `--host` not specified | `--host` specified |
|---|---|----|
| `--advertise-host` not specified | Listen on all interfaces. Advertise the canonical host name to other nodes. | Listen on the interface specified by `--host`. Advertise the value of `--host` to other nodes. |
| `--advertise-host` specified | Listen on all interfaces. Advertise the value of `--advertise-host` to other nodes. | Listen on the interface specified by `--host`. Advertise the value of `--advertise-host` to other nodes  |

Sometimes, `--host` is just for listening and `--advertise-host` is for advertising; other times, `--host` is for both listening and advertising.

From a UX perspective, it'd be ideal to clearly differentiate between listening and advertising. As @bdarnell has explained, changing `--host` is very backwards-incompatible, but perhaps there are other options (e.g., adding and emphasizing another flag like `--listen-host` while continuing to support `--host`).

cc: @knz, @bdarnell, @mberhault

### PR DESCRIPTION
**Pull request by knz**
Fixes  #27702.

This patch achieves the following:

- deprecates --host/--port in favor of --listen-addr/--listen-port for
  `cockroach start`
- produces a warning if neither --host/--listen nor --advertise are
  specified.
- deprecates --advertise-host in favor of --advertise-addr
- deprecates --http-host in favor of --http-addr
- suggests that "addresses" are also acceptable next to host names in
  the flag descriptions.
- suggests that the argument to --advertise must be routable
  everywhere.
- un-hides --advertise-port. This flag is actually useful when
  there is a NAT router with X:Y port forwarding.

Release note (cli change): the flags `--host` and `--port` to
`cockroach start` are deprecated in favor of `--listen-addr` and
`--listen-port`. They remain valid for other *client* commands.  The
flags `--advertise-host` and `--http-host` are deprecated in favor of
`--advertise-addr` and `--http-addr` and do not change meaning.

cc @jseldess

### CODE REVIEW

**Review by a-robinson — COMMENTED** [review]
I'm not gonna try to block this change since I haven't been involved in the conversation and these flags do cause confusion, but I do want to point out that `--host` (or now `--listen-host`) controls more than just where the process listens. If you don't provide a separate `--advertise-host`, then `--host` also controls what address the process advertises. You can create a cleaner separation between the names of the two flags, but the behavior is still muddled.

**Comment by knz** [comment]
It seems to me reasonable that the default value of --advertise is the value given to --listen, and that would be reasonable (to me) with any server software not just CockroachDB

**Comment by a-robinson** [comment]
I agree that it's the right behavior, but it means that `--listen-host` does more than just configuring which host is listened on, so the documentation will still require some subtlety.

**Comment by knz** [comment]
I'll let Jesse comment here then. He was the one requesting.

**Comment by jseldess** [comment]
Yes, I think the docs would still require subtlety if `--listen-host` were to behave the same as the current `--host` flag. In that case, it seems the only value to this change would be clearer naming. (Is there such a thing as flag aliases, btw, where users could use either `--host` or `--listen-host`?). 

If we could do whatever we wanted, I'd suggest de-coupling `--listen-host` and `--advertise-host`,  making the former purely about listening and the latter purely about advertising. That might mean both could be unspecified (and default to `localhost`), but if one is specified, the other would probably have to be specified.

**Comment by mberhault** [comment]
+1 on Jesse's point: the confusion stems from the link between both flags and what they really mean, not the naming.
Defaulting both to `hostname()` and requiring both to be set independently of each other might clarify things. Renaming (or aliasing, which is what happens here) `--host` to `--listen-host` makes this behavior even clearer and separates it nicely from `--advertise-host`.

**Comment by knz** [comment]
Ok I think I see a way forward. I will first attempt to answer the questions you've asked above, then make an important point, then I'll name several strategies and you'll chime in to indicate where your preferences lie.

So first to answer open points:

> is there such a thing as flag aliases, btw, where users could use either --host or --listen-host?

Yes this is one of the things this PR is doing.

>  it seems the only value to this change would be clearer naming.

The clearer naming is an important improvement already. We should not under-estimate it. Also let us not ignore the other improvements listed at the top:

- suggests that "addresses" are also acceptable next to host names in the flag descriptions.
- suggests that the argument to --advertise must be routable everywhere.
- un-hides --advertise-port. This flag is actually useful when there is a NAT router with X:Y port forwarding. 

Then moving on to the important point:

1. let's suspend disbelief for a second and re-contextualize the discussion in a world where:
   - there are now two flags --listen-host and --advertise-host
   - the default value of --listen-host is the canonical hostname, as currently
   - if --advertise-host is not specified, it defaults to whatever value is given to --listen-host (or the canonical hostname if none is specified)

2. let's spell out the basis of the discussion in this new situation:
    - the flags have descriptive names and it is already **much easier** to explain their role
    - their description in --help is now more clearly linking them to each other and suggests better how they should be used
    - this behavior, where --listen-host is the "main" flag and --advertise-host is optional but taking its default from the first, is common across other server software. Us appearing to struggle with this in this discussion may be a symptom of  lack of experience, rather than an inherent flaw in the design.

From then on, I will spell out what I think are the real problems we should be cautious with:

- if the two flags were truly "de-coupled" as suggested while keeping them optional, we'll enter a new world where users will set one and forget to set the other, and we'll thereby enter a world of troubleshooting pain. I don't think this is acceptable at all.
- if we "de-couple" them and then **mandate** (with an error otherwise) that they either be both specified together, or not specified at all, we're going to make the product objectively harder to use and operate, even though it'll appear to you, Jesse, as a moderate simplification to the docs. I am personally not convinced this is a productive way forward. I could be convinced otherwise but I'll want the pros and cons of this proposal to be discussed with more people with operational experience.
- so far we have failed to consider other alternatives which could constitute solid middle ground.

What about the following scenarios

1. the "don't overthink this" scenario:
   - in the **documentation**, document the flags as fully independent and say their default is the canonical host name
   - in the product, make them work as they work currently, with --advertise-host auto-defaulting to the value of --listen-host if not specified, **but** extend this situation as follows:
     -  **do not document this behavior.**
     - if --advertise-host is specified but --listen-host is not, then **produce a warning** (perhaps that could be an error? not sure)
   - **print out the join address** (the value to provide via --join on other nodes, based off --advertise-host) in the server startup messages. It is currently missing from there! There is currently no startup feedback about the two flags under discussion, and I think that's one of the main source of user uncertainty.
        
2. the "help me help you" scenario:
    - everything from scenario 1 already included
    - derive the default values of --listen-host and/or --advertise-host from the provided node certificate. if the certificate has problems, that will cause the server to fail early instead of failing (as currently) silently and in a way hard to understand

3. the "perhaps too smart for our own good" scenario:
    - everything from scenario 1 already included
    - if --listen-host is non-default, have the node attempt to reach out to some internet server like http://whatismyipaddress.com (we could provide our own) and set --advertise-host to what this service returns. This behavior would be opt-out.


So, there. I'd like to convince you that scenario 1 would already put us in a much better situation than today, without changing the product behavior too much. I'll hear your thoughts about that and the other two scenarios.

**Comment by jseldess** [comment]
@knz, I unfortunately don't have time to respond to this properly (probably until after I'm back from vacation next Thurs). But there's a point in your response that I want to focus on:

> this behavior, where --listen-host is the "main" flag and --advertise-host is optional but taking its default from the first, is common across other server software. Us appearing to struggle with this in this discussion may be a symptom of lack of experience, rather than an inherent flaw in the design.

In my opinion, the ways these flags are interdependent is exactly what is so confusing. On many occasions, I have gotten uncertain and confused answers from our own developers on this, and I think there is evidence we could track down that external users have also been confused. Historically, we started with only `--host`, which controlled both listening and advertising. Then we added `--advertise-host` specifically because sometimes you need to advertise a specific address to nodes but listen on all interfaces. So it wasn't a design decision as much as an organic evolution. @bdarnell, @a-robinson, please correct me if I'm remembering wrong.

So: **Is the claim that `this behavior, where --listen-host is the "main" flag and --advertise-host is optional but taking its default from the first, is common across other server software.` really true?** Can you point to other databases that behave this way? If so, I'd say it's totally fine and we just need to improve our docs (as I'm trying to do in https://github.com/cockroachdb/docs/pull/3352) along with the other improvements you've made.

**Comment by jseldess** [comment]
I've been looking at Cassandra docs. That db seems to match @knz's expectations, at least to some extent: [`broadcast_address`](https://docs.datastax.com/en/cassandra/2.1/cassandra/configuration/configCassandra_yaml_r.html#configCassandra_yaml_r__broadcast_address) is classified as "advanced" and defaults to [`listen_address`](https://docs.datastax.com/en/cassandra/2.1/cassandra/configuration/configCassandra_yaml_r.html#configCassandra_yaml_r__listen_address). However, that's only for node communication. There's a separate listening option for clients, [`rpc_address`](https://docs.datastax.com/en/cassandra/2.1/cassandra/configuration/configCassandra_yaml_r.html#configCassandra_yaml_r__rpc_address) or `rpc_interface`.

Another difference is that, for each, Cassandra offers either an address option or an interface option. It's either/or.

**Comment by jseldess** [comment]
[Rethinkdb's network options](https://www.rethinkdb.com/docs/cli-options/) are less clear: Each instance seems to have a `--bind` option for listening for (client?) connections, and a `--canonical-address` option for specifying the address(es) for other RethinkDB instances to use (advertising?).

**Comment by a-robinson** [comment]
I have one important correction to points made by both @mberhault and @knz:

> Defaulting both to `hostname()` and requiring both to be set independently of each other might clarify things.

> the default value of --listen-host is the canonical hostname, as currently

The current default of `--host` is to listen on all interfaces, not just the canonical hostname. This is an important difference, and I think we should keep the current behavior. It's much less likely to surprise people in a bad way, especially when it comes to being able to talk to the server on localhost.

Other than that confusion, though, I'm fine with the change @knz is proposing here. The behavior would be:

`--listen-host`: defaults to empty, i.e. listen on all interfaces, but can be set by flag
`--advertise-host`: defaults to hostname, which can be overridden by a non-empty value of `--listen-host`, which can be overridden by setting `--advertise-host`

This is the same as today, just with a slightly clearer flag name. I think we'll still get plenty of user issues. I'd recommend digging through relevant past issues to see if this would really help. I seem to recall the problem often being that people aren't even aware of the flags, not that the names confuse them. For example, in https://github.com/cockroachdb/cockroach/issues/27828 from yesterday, the user at first was running without either flag, so we still would have gotten an issue. They then discovered the `--host` flag and found that it solved their initial problem but created a new problem. They made no mention of considering the `--advertise-host` flag in their post, so they presumably never even noticed it.

My intuition is that a more detailed explanation in the flag help text may be the most impactful change we can make, along with some targeted references/explanation in the docs and ideally some log messages pointing to the flags when we can detect that the servers aren't able to connect to each other.

And thanks for the references, @jseldess. It sounds like both Cassandra and Rethink are doing roughly the same thing as us. Rethink's `--bind` is effectively our `--host`, and `--canonical-address` is effectively `--advertise-host`. Cassandra's `--listen-address` is our `-host`/`--listen-host`, and `--broadcast-address` is our `--advertise-host`. `--rpc-address` is just an artifact of the fact that they allow you to separate out internal node traffic from client traffic, while we run both through the same port. Our `--advertise-host` never has any effect on clients of cockroach.

**Comment by bdarnell** [comment]
> this behavior, where --listen-host is the "main" flag and --advertise-host is optional but taking its default from the first, is common across other server software. Us appearing to struggle with this in this discussion may be a symptom of lack of experience, rather than an inherent flaw in the design.

The fact that the "main" host/address flag sets the listening address in most server software is exactly why we called our flag for this `--host`. However, this was a mistake. For most server software, the listening address is the main address flag because that's all there is and there is no concept of "advertising" a different address. Furthermore, for most software binding to localhost-only is a reasonable choice, so there is more need to set the listening address.

For cockroach, binding to all network address is the right behavior in the overwhelming majority of cases. However, we often cannot deduce a correct advertise address on our own, so it is much more common for users to need to set the `--advertise-host` flag. Our biggest problem here is that by naming the flag to set the listening address `--host`, it is more attractive to users figuring out how to set things up. I think renaming `--host` to `--listen-host` and making `--advertise-host` more prominent in the docs is the way to go.

The interaction between the flags is somewhat confusing; I'd prefer to disconnect them so that `--advertise-host` defaults to the machine's default hostname no matter what is used for `--listen-host`. If we make this change we'd (temporarily) have a more complicated arrangement since `--host` would set the default advertise address while `--listen-host` would not. We'd want to deprecate and remove the `--host` flag to eventually clear up this confusion (if `--host` and `--listen-host` act the same way we could just leave `--host` around as a semi-hidden alias).

One more thing while we're cleaning things up here: I generally prefer "address" instead of "host" for this (and prefer flags that take host:port pairs instead of separate flags). I don't know if it's worth renaming everything, though.

**Comment by knz** [comment]
Thanks Jesse for checking.

A few responses to previous points, then please consider my proposal below.

> @a-robinson They then discovered the --host flag and found that it solved their initial problem but created a new problem. They made no mention of considering the --advertise-host flag in their post, so they presumably never even noticed it.

1) This problem would be solved by copious cross-referencing. 
2) I have another proposal, see below.

> My intuition is that a more detailed explanation in the flag help text may be the most impactful change we can make

Agreed; please check the commit in this PR.
Also see my proposal below.

> @bdarnell For most server software, the listening address is the main address flag because that's all there is and there is no concept of "advertising" a different address. 

Yes; please check my comment here for the extended discussion: https://reviewable.io/reviews/cockroachdb/docs/3352#-LHwZkeC9ZWYPIdS7omM

> if --host and --listen-host act the same way we could just leave --host around as a semi-hidden alias

This is what the PR currently does.

> I generally prefer "address" instead of "host" for this 

OK, will modify this.

> prefer flags that take host:port pairs instead of separate flags 

That's a separate issue: #23277
I'll look into providing a fix for that too. Would be nice to kill two birds with one stone.

As to the proposals:

- (Ben's): make "--advertise-host defaults to the machine's default hostname no matter what is used for --listen-host"
- (mine): keep the same behavior as currently (will simplify the transition), but:
  - add copious cross-references in the flag docs
  - **add a warning** if --listen is set but --advertise is not
  - add another warning when neither --listen and --advertise are set, and all of the bind addresses are [rfc1918](https://tools.ietf.org/html/rfc1918).

What do you think?

**Comment by bdarnell** [comment]
> (mine): keep the same behavior as currently (will simplify the transition), but:
> - add copious cross-references in the flag docs
> - add a warning if --listen is set but --advertise is not

Yes.

> - add another warning when neither --listen and --advertise are set, and all of the bind addresses are loopback, private rfc1918 or link-local rfc3927.

👎 

RFC 1918 addresses are the common case for database deployments, so this amounts to a warning in most cases if neither host flag is set. I don't think that's warranted. We already have errors if the canonical hostname doesn't resolve to an address we can bind to. The question is whether we can distinguish hostnames that will only resolve on this host from ones that will resolve on our peers. I don't think the public/private status of our IP addresses helps with that. 

Instead, a couple of heuristics that seem useful are whether the hostname comes from `/etc/hosts` (as opposed to DNS), or if our "fully-qualified" hostname doesn't contain a dot. But these are still imperfect - I believe docker swarm puts bare hostnames in /etc/hosts, but they still work from multiple hosts. Should we err on the side of warning or silence? This depends in part on how visible the warnings are. If they're too visible, then false positives will be annoying and people will add unnecessary `--advertise-host` flags just to silence the warning. If they're not visible enough, what's the point? (and I think that our logs are mostly "not visible enough")

**Comment by knz** [comment]
Added warning and changed to use "addr" instead of "host" in flag names. RFAL!

**Review by bdarnell — APPROVED** [review]
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27800)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/flags.go, line 441 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27800#-LIw0W4y0uvKRB6h_T_b:-LIw0W4y0uvKRB6h_T_c:b-fm67in) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0dec0e68c870d444e37d967a650a357fe983138/pkg/cli/flags.go#L441)):*
> ```Go
> 	advAddrSpecified := pf.Lookup(cliflags.AdvertiseAddr.Name).Changed || pf.Lookup(cliflags.AdvertiseAddrAlias.Name).Changed
> 	if listenAddrSpecified && !advAddrSpecified {
> 		// We can't use log.Shout here, because at this point logging has
> ```

I don't like another non-standard form of output for things that are meant to reliably reach human eyes. Can we postpone this until log.Shout is ready?
___
*[pkg/cli/cliflags/flags.go, line 335 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27800#-LIw-9fc29Wpm37ptGuT:-LIw-9fc29Wpm37ptGuU:buugldy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0dec0e68c870d444e37d967a650a357fe983138/pkg/cli/cliflags/flags.go#L335)):*
> ```Go
> container deployments or any setup where NAT is present between
> cluster nodes.`,
> 	}
> ```

The help text for `listen-addr` should specify that it supports either bare hostnames or strings of the form `host:port` (and what about ipv6 literals? do we support square brackets as in URLs?)
___
*[pkg/cli/cliflags/flags.go, line 337 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27800#-LIvzShA7bFQdV-dXB8p:-LIvzShA7bFQdV-dXB8q:b2kmwm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0dec0e68c870d444e37d967a650a357fe983138/pkg/cli/cliflags/flags.go#L337)):*
> ```Go
> 	}
> 
> 	ListenAddrAlias = FlagInfo{
> ```

I think it's confusing that this is called `ListenAddrAlias` instead of `Host`; I'd keep this variable named `ServerHost`. 
___
*[pkg/cli/cliflags/flags.go, line 349 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27800#-LIvzhxEAuOsBT6OSzwW:-LIvzhxEAuOsBT6OSzwX:bqj0t4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0dec0e68c870d444e37d967a650a357fe983138/pkg/cli/cliflags/flags.go#L349)):*
> ```Go
> will also announce this port for use by other nodes. It is strongly
> recommended to use --advertise-port in any setup where NAT is present
> between cluster nodes.`,
> ```

I would remove this last sentence. When `--advertise-port` is used, it'll be absolutely required, not just recommended (and when it's not required, specifying it is useless).
___
*[pkg/cli/interactive_tests/test_flags.tcl, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27800#-LIw1fjd0xAn5bAJDljb:-LIw1fjd0xAn5bAJDljc:bks3k1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0dec0e68c870d444e37d967a650a357fe983138/pkg/cli/interactive_tests/test_flags.tcl#L38)):*
> ```Tcl
> end_test
> 
> start_test "Check that --host without --advertise causes a user warning."
> ```

This warning will be mildly annoying in our local cluster tutorials (which use `--host=localhost` without `--advertise-host`, and this does the right thing because the listen address is propagated to the advertise address if the latter is unspecified). I gave the OK to this warning earlier, but now I'm less sure about it - I think different values for listen and advertise addresses are actually fairly rare in practice (unless we're listening on all interfaces). 
___
*[pkg/cli/interactive_tests/test_flags.tcl, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27800#-LIw-e3jDCOLvVs3wfOq:-LIw-e3jDCOLvVs3wfOr:bkwu04w) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0dec0e68c870d444e37d967a650a357fe983138/pkg/cli/interactive_tests/test_flags.tcl#L54)):*
> ```Tcl
> end_test
> 
> start_test "Check that --port without --advertise causes a user warning."
> ```

I don't think this needs a warning. We'll use the listening port in our advertise address by default, and this will almost always work.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27800)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/flags.go, line 441 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27800#-LIw0W4y0uvKRB6h_T_b:-LIzoR8SCxLhf1QOEPqI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0dec0e68c870d444e37d967a650a357fe983138/pkg/cli/flags.go#L441)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I don't like another non-standard form of output for things that are meant to reliably reach human eyes. Can we postpone this until log.Shout is ready?
</blockquote></details>

Done.
___
*[pkg/cli/cliflags/flags.go, line 335 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27800#-LIw-9fc29Wpm37ptGuT:-LIzke_L8X-vos4-sxm4:bpx51qx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0dec0e68c870d444e37d967a650a357fe983138/pkg/cli/cliflags/flags.go#L335)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

The help text for `listen-addr` should specify that it supports either bare hostnames or strings of the form `host:port` (and what about ipv6 literals? do we support square brackets as in URLs?)
</blockquote></details>

It does not (yet) support the form `host:port`. This is issue  #23277.  I plan to do this in a separate PR.
And yes IPV6 literals can be input using the standard format with brackets. Added example to the comment.
___
*[pkg/cli/cliflags/flags.go, line 337 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27800#-LIvzShA7bFQdV-dXB8p:-LIzmTHc-XdXrZcQI4rh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0dec0e68c870d444e37d967a650a357fe983138/pkg/cli/cliflags/flags.go#L337)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I think it's confusing that this is called `ListenAddrAlias` instead of `Host`; I'd keep this variable named `ServerHost`. 
</blockquote></details>

Done.
___
*[pkg/cli/cliflags/flags.go, line 349 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27800#-LIvzhxEAuOsBT6OSzwW:-LIzmsO27JqTbY_6Xk6P:b-un4liz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0dec0e68c870d444e37d967a650a357fe983138/pkg/cli/cliflags/flags.go#L349)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I would remove this last sentence. When `--advertise-port` is used, it'll be absolutely required, not just recommended (and when it's not required, specifying it is useless).
</blockquote></details>

I think my help text wasn't clear. Rephrased.
___
*[pkg/cli/interactive_tests/test_flags.tcl, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27800#-LIw1fjd0xAn5bAJDljb:-LIzp68i6GI7CGejcm6g:bjcsh60) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0dec0e68c870d444e37d967a650a357fe983138/pkg/cli/interactive_tests/test_flags.tcl#L38)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This warning will be mildly annoying in our local cluster tutorials (which use `--host=localhost` without `--advertise-host`, and this does the right thing because the listen address is propagated to the advertise address if the latter is unspecified). I gave the OK to this warning earlier, but now I'm less sure about it - I think different values for listen and advertise addresses are actually fairly rare in practice (unless we're listening on all interfaces). 
</blockquote></details>

Isn't that the right heuristic though? If neither `--host` nor `--advertise` is specify, recommend using either `--host=localhost` (testing) or `--advertise` (multi-node cluster)?
I just implemented that, let me know what you think:

```
*
* WARNING: neither --listen-addr nor --advertise-addr was specified.
* The server will advertise "kenax" to other nodes, is this routable?
*
* Consider using:
* - for local-only servers:  --listen-addr=localhost
* - for multi-node clusters: --advertise-addr=<public host/addr>
*
*
```
___
*[pkg/cli/interactive_tests/test_flags.tcl, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27800#-LIw-e3jDCOLvVs3wfOq:-LIznajV572S4fJ6-WDU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0dec0e68c870d444e37d967a650a357fe983138/pkg/cli/interactive_tests/test_flags.tcl#L54)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I don't think this needs a warning. We'll use the listening port in our advertise address by default, and this will almost always work.
</blockquote></details>

Done.

**Review by bdarnell — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27800)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/interactive_tests/test_flags.tcl, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27800#-LIw1fjd0xAn5bAJDljb:-LJEioEY-OFNSMcBCZCx:bk9u3zh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0dec0e68c870d444e37d967a650a357fe983138/pkg/cli/interactive_tests/test_flags.tcl#L38)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Isn't that the right heuristic though? If neither `--host` nor `--advertise` is specify, recommend using either `--host=localhost` (testing) or `--advertise` (multi-node cluster)?
I just implemented that, let me know what you think:

```
*
* WARNING: neither --listen-addr nor --advertise-addr was specified.
* The server will advertise "kenax" to other nodes, is this routable?
*
* Consider using:
* - for local-only servers:  --listen-addr=localhost
* - for multi-node clusters: --advertise-addr=<public host/addr>
*
*
```


</blockquote></details>

That seems a little heavyweight (given that the defaults should work in theory), but I guess we have enough empirical evidence  that `--advertise-addr` is usually required.

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27800)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/interactive_tests/test_flags.tcl, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27800#-LIw1fjd0xAn5bAJDljb:-LJEjaGfBkZz2Wu3Ewgf:b-2uihpg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0dec0e68c870d444e37d967a650a357fe983138/pkg/cli/interactive_tests/test_flags.tcl#L38)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

That seems a little heavyweight (given that the defaults should work in theory), but I guess we have enough empirical evidence  that `--advertise-addr` is usually required. 
</blockquote></details>

I wouldn't use the word "public", though. When nodes have both public and private IPs, the private one is usually what you want here. I'd make the suggestion `--advertise-addr=<IP addr/hostname>`

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27800)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/interactive_tests/test_flags.tcl, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27800#-LIw1fjd0xAn5bAJDljb:-LJIbNTEAK7pdkKELFvR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0dec0e68c870d444e37d967a650a357fe983138/pkg/cli/interactive_tests/test_flags.tcl#L38)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I wouldn't use the word "public", though. When nodes have both public and private IPs, the private one is usually what you want here. I'd make the suggestion `--advertise-addr=<IP addr/hostname>`
</blockquote></details>

Done.

**Pull request merged**
