### PR TITLE
release-19.2: colexec: allow unneeded index columns to be skipped in cfetcher

### PR DESCRIPTION
**Pull request by rohany**
Backport 1/1 commits from #43024.

/cc @cockroachdb/release

---

It seems like all indexed columns were being marked as needed in
the cfetcher initialization steps, whether they were actually
in neededCols or not. This meant that unneeded columns weren't
actually getting skipped.

Release note: None

### CODE REVIEW

**Comment by rohany** [comment]
Next step in the backport process. Again, take a close look because the backport wasn't clean.

**Review by asubiotto — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43939)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @rohany, and @yuzefovich)

___
*[pkg/sql/colexec/cfetcher.go, line 273 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43939#-Ly_w7Am7o9ocMgZ16N6:-Ly_w7Am7o9ocMgZ16N7:b-dqovoe) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5c3cf2195c82c8a8773d771e0748760dcfb77a/pkg/sql/colexec/cfetcher.go#L273)):*
> ```Go
> 	for i := range typs {
> 		typs[i] = typeconv.FromColumnType(&colDescriptors[i].Type)
> 		if typs[i] == coltypes.Unhandled && tableArgs.ValNeededForCol.Contains(i) {
> ```

Wait, I think this is wrong. This commit doesn't include the addition of placeholder vecs, so the fact that we don't error out here on an unsupported type should error out `NewMemBatch` below, right?

**Comment by rohany** [comment]
Does that mean you should land the PR that introduces the placeholder vecs etc then let me rebase this on top of that?

**Comment by asubiotto** [comment]
Yeah, doing that now.

**Comment by asubiotto** [comment]
#44014

**Comment by asubiotto** [comment]
Done, this should be ready for a rebase.

**Comment by rohany** [comment]
rebased, PTAL

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43939#-:-LyfAJzM2cKYLp9Ci3en:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rohany and @yuzefovich)

**Pull request merged**
