### PR TITLE
sql/pgwire: prevent overflow during decimal decoding

### LINKED ISSUE #38139: sentry: conn_executor.go:434: panic while executing 0 statements: : caused by <redacted>
This issue was autofiled by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry link: https://sentry.io/organizations/cockroach-labs/issues/1067844166/?referrer=webhooks_plugin

Panic message:

>conn_executor.go:434: panic while executing 0 statements: : caused by <redacted>

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

https://github.com/cockroachdb/cockroach/blob/c8bda1de440cfe90cf23a433119d77795cfa0047/pkg/sql/conn_executor.go#L433-L435 in pkg/sql.(*Server).ServeConn.func1
/usr/local/go/src/runtime/asm_amd64.s#L521-L523 in runtime.call32
/usr/local/go/src/runtime/panic.go#L512-L514 in runtime.gopanic
/usr/local/go/src/runtime/slice.go#L51-L53 in runtime.makeslice
/usr/local/go/src/runtime/slice.go#L66-L68 in runtime.makeslice
https://github.com/cockroachdb/cockroach/blob/c8bda1de440cfe90cf23a433119d77795cfa0047/pkg/sql/pgwire/pgwirebase/encoding.go#L442-L444 in pkg/sql/pgwire/pgwirebase.DecodeOidDatum
https://github.com/cockroachdb/cockroach/blob/c8bda1de440cfe90cf23a433119d77795cfa0047/pkg/sql/conn_executor_prepare.go#L346-L348 in pkg/sql.(*connExecutor).execBind
https://github.com/cockroachdb/cockroach/blob/c8bda1de440cfe90cf23a433119d77795cfa0047/pkg/sql/conn_executor.go#L1261-L1263 in pkg/sql.(*connExecutor).run
https://github.com/cockroachdb/cockroach/blob/c8bda1de440cfe90cf23a433119d77795cfa0047/pkg/sql/conn_executor.go#L435-L437 in pkg/sql.(*Server).ServeConn
https://github.com/cockroachdb/cockroach/blob/c8bda1de440cfe90cf23a433119d77795cfa0047/pkg/sql/pgwire/conn.go#L579-L581 in pkg/sql/pgwire.(*conn).processCommandsAsync.func1
</details>

```
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn.func1 at line 434
/usr/local/go/src/runtime/asm_amd64.s in runtime.call32 at line 522
/usr/local/go/src/runtime/panic.go in runtime.gopanic at line 513
/usr/local/go/src/runtime/slice.go in runtime.makeslice at line 52
/usr/local/go/src/runtime/slice.go in runtime.makeslice at line 67
pkg/sql/pgwire/pgwirebase/encoding.go in pkg/sql/pgwire/pgwirebase.DecodeOidDatum at line 443
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).execBind at line 347
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 1262
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 436
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 580
```

| Tag | Value |
|---|---|
| Cockroach Release | `v19.1.1` |
| Cockroach SHA: | c8bda1de440cfe90cf23a433119d77795cfa0047 |
| Platform | linux amd64 |
| Distribution | CCL |
| Environment | v19.1.1 |
| Command | server |
| Go Version | `go1.11.6`|
| # of CPUs |4 |
| # of Goroutines |151 |

### PR DESCRIPTION
**Pull request by madelynnblue**
All the binary decimal fields are int16s. When multiplying by 4
(PGDecDigits), a value that was greater than math.MaxInt16/4 could thus
overflow to negative, causing the make to panic. Converting to an int
before multiplying prevents the panic.

Fixes #38139

Release note (bug fix): Fix a panic that could occur when decoding
decimals as query parameters.

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
:lgtm:  I like that test case :)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38304#-:-Lhlink97jNdwwFt0H1A:bo6086h)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @rafiss, and @solongordon)

**Review by jordanlewis — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
