### PR TITLE
sql: add missing OID entries

### PR DESCRIPTION
**Pull request by knz**
Needed for / extracted from #28690.

CockroachDB supports `int2`, `int4`, `varchar`, `bpchar` (`char`),
`"char"`. We should present the OID for them.

Release note: None

### CODE REVIEW

**Review by jordanlewis — CHANGES_REQUESTED** [review]
:lgtm: , couple questions

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28754#-:-LK7V4XC1TbNPKRuWSio:bgn18gg)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/parser/parse_test.go, line 1121 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28754#-LK7V-tn4G3yUY7YuCH0:-LK7V-tn4G3yUY7YuCH1:b8id4fa) ([raw file](https://github.com/cockroachdb/cockroach/blob/df9b6716dea08f2526baa9a36525609167a8eed0/pkg/sql/parser/parse_test.go#L1121)):*
> ```Go
> 		{`SELECT TIMESTAMP WITHOUT TIME ZONE 'foo'`, `SELECT TIMESTAMP 'foo'`},
> 		{`SELECT CAST('foo' AS TIMESTAMP WITHOUT TIME ZONE)`, `SELECT CAST('foo' AS TIMESTAMP)`},
> 		{`SELECT CAST(1 AS "char")`, `SELECT CAST(1 AS CHAR)`},
> ```

why did you remove this test case?
___
*[pkg/sql/sem/tree/format_test.go, line 288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28754#-LK7TSHvDuDDQVdVRDlF:-LK7TSHvDuDDQVdVRDlG:bs8aysw) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc79a3532073124f0349cdeb99cfa4c8a77e5e20/pkg/sql/sem/tree/format_test.go#L288)):*
> ```Go
> 	}{
> 		{tree.NewDOidWithName(tree.DInt(10), coltypes.RegClass, "foo"),
> 			tree.FmtParsable, `crdb_internal.create_REGCLASS(10,'foo'):::REGCLASS`},
> ```

This grossness is why I toLower'd it... but either way

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28754)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/parser/parse_test.go, line 1121 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28754#-LK7V-tn4G3yUY7YuCH0:-LK7V_Vs4Mb_77x25Z3s:bns207t) ([raw file](https://github.com/cockroachdb/cockroach/blob/df9b6716dea08f2526baa9a36525609167a8eed0/pkg/sql/parser/parse_test.go#L1121)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

why did you remove this test case?
</blockquote></details>

It's still there! moved up in `TestParse`.
___
*[pkg/sql/sem/tree/format_test.go, line 288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28754#-LK7TSHvDuDDQVdVRDlF:-LK7VbWK07-qcRCRiZJ4:b-k6i8fy) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc79a3532073124f0349cdeb99cfa4c8a77e5e20/pkg/sql/sem/tree/format_test.go#L288)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This grossness is why I toLower'd it... but either way
</blockquote></details>

Yes I figured it was equivalent but I'd rather keep the `Format` methods as simple as possible.

**Comment by knz** [comment]
don't forget to change your review disposition if you're happy

**Review by jordanlewis — APPROVED** [review]

**Comment by knz** [comment]
thank you!

bors r+

**Comment by knz** [comment]
Encountered #28664.

bors r+

**Pull request merged**
