### PR TITLE
sql: Move SplitTable into TestCluster

### PR DESCRIPTION
**Pull request by ecwall**
refs https://github.com/cockroachdb/cockroach/issues/85800

Move this function to make it accessible by the TTL (and other) tests.

Release note: None

Release justification: Test refactor for TTL.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86165#-:-N9XsK5L8HxGU9_Os-ke:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ecwall, @RaduBerinde, and @rafiss)

___
*[`pkg/testutils/testcluster/testcluster.go` line 1754 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86165#-N9XsDF1Eu7HDCPQSWO0:-N9XsDF1Eu7HDCPQSWO1:blbmmi9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed16928b0aa8b72bf704688400bcf5c4c1392eb1/pkg/testutils/testcluster/testcluster.go#L1754)):*
> ```Go
> 
> type rangeAndKT struct {
> 	Range roachpb.RangeDescriptor
> ```

nit: these two fields can be unexported.

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86165)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde, @rafiss, and @yuzefovich)

___
*[`pkg/testutils/testcluster/testcluster.go` line 1754 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86165#-N9XsDF1Eu7HDCPQSWO0:-N9XuqBwC7TRAsLBV9eF:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed16928b0aa8b72bf704688400bcf5c4c1392eb1/pkg/testutils/testcluster/testcluster.go#L1754)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: these two fields can be unexported.
</blockquote></details>

Done

**Review by rafiss — APPROVED** [review]
ty!

**Comment by rafiss** [comment]
looks like there are some issues to address first
```
        package github.com/cockroachdb/cockroach/pkg/sql/randgen
          imports github.com/cockroachdb/cockroach/pkg/testutils/testcluster: import cycle not allowed in test
        pkg/sql/distsql_plan_backfill_test.go:83:21: github.com/cockroachdb/cockroach/pkg/testutils/serverutils.SplitPoint composite literal uses unkeyed fields
```

**Comment by ecwall** [comment]
bors r=rafiss

**Pull request merged**
