### PR TITLE
sql: Add support for Postgres-like regexp match operators

### LINKED ISSUE #7515: sql: Support Postgres-like regexp match operators
See https://www.postgresql.org/docs/9.0/static/functions-matching.html#FUNCTIONS-POSIX-REGEXP.

In addition to querying for unsupported catalogs (`pg_catalog`, `pg_class`), Hibernate and its use of the Postgres JDBC issues a few queries which contain Postgres-specific regular expression match operators. While it looks like the ORM is actually handling the missing table errors fairly well, the parsing errors caused by the use of these operators is blocking its use. Now that there is a need for them, there doesn't seem to be any strong reason against adding support for these operators.

Thoughts @petermattis?

### PR DESCRIPTION
**Pull request by nvb**
Fixes #7515.

This change adds support for the operators:
- `~`  regexp match
- `!~`  not regexp match
- `~*` regexp match case insensitive
- `!~*` not regexp match case insensitive

Support for these Postgres-specific operators was needed to increase
compatibility with the Postgres JDBC driver.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7686)

### CODE REVIEW

**Comment by knz** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/parser/eval_test.go, line 617 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7686#-KMAlgp_5WRc-LH9Fw4q:-KMAlgparWA26plTaCfo:-530962840) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ab8e0422e53e83bcc60b15256432aa080ed74ef/sql/parser/eval_test.go#L617)):*
> ```Go
> 		{SimilarTo, `abc`, `(b|c)%`, 1},
> 		{NotSimilarTo, `abc`, `%(b|d)%`, 1},
> 		// ~, !~, ~*, an !~*
> ```

"and"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7686#-:-KMAmBUlmu9dtQYLbXj5:1417088721)*

**Comment by nvanbenschoten** [comment]
TFTR

---

Review status: 11 of 12 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/parser/eval_test.go, line 617 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7686#-KMAlgp_5WRc-LH9Fw4q:-KMAv9TJK4JTUZYijU9T:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ab8e0422e53e83bcc60b15256432aa080ed74ef/sql/parser/eval_test.go#L617)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> "and"
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7686#-:-KMAvAQiA2XBbt30beIM:677071605)*

**Comment by jseldess** [comment]
@nvanbenschoten, I'm seeing only `~` in the operators list on https://www.cockroachlabs.com/docs/functions-and-operators.html. Do we just need to regenerate that page?

**Comment by nvanbenschoten** [comment]
@jseldess I hope it's as easy as that. Let's try it and see.

**Pull request merged**
