### PR TITLE
kv: don't ingest aborted TxnCoordMeta

### LINKED ISSUE #33698: roachtest: scaledata/distributed_semaphore/nodes=3 failed
SHA: https://github.com/cockroachdb/cockroach/commits/766a53defc27940d41ae8987792ecd79e76d2b65

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=scaledata/distributed_semaphore/nodes=3 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1090948&tab=buildLog

```
The test failed on master:
	test.go:1101: test timed out (20m0s)
	test.go:696,cluster.go:1511,scaledata.go:126,scaledata.go:53: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-1090948-scaledata-distributed-semaphore-nodes-3:4 -- ./distributed_semaphore  --duration_secs=600 --num_workers=16 --cockroach_ip_addresses_csv='10.128.0.154:26257,10.128.0.124:26257,10.128.0.155:26257'  returned:
		stderr:
		13 12:19:43.818029251 +0000 UTC m=+574.303702067, now = 2019-01-13 12:19:58.760941404 +0000 UTC m=+589.246614276, took 14.942912209s
		2019/01/13 12:19:58 Aborting Retries because this error of type *crdb.AmbiguousCommitError is not retryable : pq: result is ambiguous (error=initial connection heartbeat failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 10.128.0.124:26257: connect: connection refused" [exhausted])
		2019/01/13 12:19:58 RobustDB.RandomDB chose DB at index 0
		2019/01/13 12:19:58 [/Users/nathan/Go/src/github.com/scaledata/rksql/src/go/src/rubrik/sqlapp/tx.go:29 pq: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_ASYNC_WRITE_FAILURE): "sql txn" id=4ed1fae5 key=/Table/54/1/417173639025852417/0 rw=true pri=0.00407482 stat=PENDING epo=0 ts=1547381994.115138047,1 orig=1547381983.836350074,0 max=1547381984.336350074,0 wto=true seq=2]
		
		stdout:
		e timestamp 1547381409.525352672,1 within uncertainty interval `t <= 1547381409.538741774,0`; observed timestamps: [{1 1547381409.538741774,0} {2 1547381409.524794522,0}]
		pq: restart transaction: TransactionRetryWithProtoRefreshError: WriteTooOldError: write at timestamp 1547381409.540432066,0 too old; wrote at 1547381409.540432066,2
		pq: restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1547381409.523763080,0 encountered previous write with future timestamp 1547381409.540432066,1 within uncertainty interval `t <= 1547381409.603062510,0`; observed timestamps: [{1 1547381409.603062510,0} {3 1547381409.523763080,0}]
		pq: restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1547381409.524120255,0 encountered previous write with future timestamp 1547381409.540432066,1 within uncertainty interval `t <= 1547381409.603154178,0`; observed timestamps: [{1 1547381409.603154178,0} {3 1547381409.524120255,0}]
		: signal: killed

```

### LINKED ISSUE #34341: *log.safeError: txn_interceptor_heartbeat.go:429: txn status: %s, but heartbeat loop hasn't been signaled to stop...
Sentry Issue: [COCKROACHDB-QW](https://sentry.io/cockroach-labs/cockroachdb/issues/846983785/?referrer=github_integration)

```
*log.safeError: txn_interceptor_heartbeat.go:429: txn status: %s, but heartbeat loop hasn't been signaled to stop | roachpb.TransactionStatus
  File "github.com/cockroachdb/cockroach/pkg/kv/txn_interceptor_heartbeat.go", line 393, in heartbeatLoop
  File "github.com/cockroachdb/cockroach/pkg/kv/txn_interceptor_heartbeat.go", line 352, in func1
  File "github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go", line 324, in func1

txn_interceptor_heartbeat.go:429: txn status: %s, but heartbeat loop hasn't been signaled to stop | roachpb.TransactionStatus
```

### LINKED ISSUE #34695: roachtest: scaledata/distributed_semaphore/nodes=6 failed
SHA: https://github.com/cockroachdb/cockroach/commits/66f13c1d9a12c31e18a198da4ff5ac0bbe2db781

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=scaledata/distributed_semaphore/nodes=6 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1127849&tab=buildLog

```
The test failed on provisional_201902062125_v2.2.0-alpha.20190211:
	test.go:743,cluster.go:1585,scaledata.go:126,scaledata.go:53: unexpected node event: 5: dead

```

### PR DESCRIPTION
**Pull request by andreimatei**
Remote DistSQL flows pass TxnCoordMeta records to the Root
Txn(CoordSender) as trailing metadata. The TCS ingests these records and
updates its state (mostly for read spans).
This patch makes it so that we don't ingest records with an ABORTED txn
proto. Why not? Because, well, unfortunately we are not well equiped at
the moment for finding out about an aborted txn this way.
The idea is that, if the Root was running along happily and all of a
sudden ingests one of these Aborted protos, it would put it in an
inconsistent state: with an Aborted proto but with the heartbeat loop
still running. We don't like that state and we have assertions against
it. The expectation is that the TCS finds out about aborted txns in one
of two ways: through a TxnAbortedError, in which case it rolls back the
txn, or through the heartbeat loop discovering the aborted txn, in which
case it again rolls back (and a 3rd way through a remote TxnAbortedErr;
see below). We have not considered this 4th way of finding
out, through a remote TxnCoordMeta, and I don't really want to deal with
it because, with current code, it's already awkward enough to handle the
other cases.

In practice, a TxnCoordMeta with an ABORTED proto is expected to follow
a TxnAbortedError that is passed through DistSQL to the gateway (the
DistSQLReceiver) before the TxnCoordMeta. That case we handle; we inject
retriable errors into the Root txn and the TCS rolls back. After this
rollback, injesting the ABORTED proto just works (it's a no-op).
However, alas, there's a case where the TxnAbortedError is not passed to
the TCS: this is when another concurrent error was received first by the
DistSQLReceiver. In that case, the 2nd error is ignored, and so this
patch makes it so that we also effectively ignore the upcoming
TxnCoordMeta.

I'm separately reworking the way error handling happens in the Txn/TCS
and that work should make this unfortunate patch unnecessary.

(since #35105 not all preceding errors cause the TxnAbortedError to be
ignored; other retriable errors no longer cause it to be ignored and
that has fixed the some crashes that we've seen because
of this inconsistent state that this patch is trying to avoid. However,
non-retriable errors racing with a TxnAbortedError are also possible,
and we've seen them happen and leading to crashes - in particular, we've
seen RPC errors).

Fixes #34695
Fixes #34341
Fixes #33698

Release note (bug fix): Fix crashes with the message "unexpected
non-pending txn in augmentMetaLocked" caused by distributed queries
encountering multiple errors.

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm: but would be nice to see this tested.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35249#-:-LZpS9S6A3nDENpp88ml:b-s787hu)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
I've added a small unit test checking that calling `AugmentMeta()` with an aborted txn is a no-op.
@tbg has reproduced the crashes in #34695 and explained them - we had RPC errors racing with `TransactionAbortedErrors`. So now I feel good about this patch.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35249#-:-LaWrLub11ylGXQrWmtA:bfl7bzx)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35249#-:-LaX43lyDmFlXkFEAwXR:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35249#-:-LaXAgqN00Mh7LQvNu3W:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
