### PR TITLE
acceptance: remove TestBuildInfo

### PR DESCRIPTION
**Pull request by benesch**
@petermattis looks like you added this test long, long ago. Doesn't seem to be any compelling reason to keep it.

---

TestBuildInfo is redundant with pkg/server.TestStatusJson. Remove
TestBuildInfo because acceptance tests are slow.

### CODE REVIEW

**Comment by petermattis** [comment]
@benesch `TestStatusJson` doesn't verify that the build info was baked into the binary. Do we have some other verification that the build info was baked into the binary? We don't really need an acceptance test to do this, perhaps some part of the teamcity process can run `cockroach version`.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17688#-:-KrfqsGGLYm_MZvZewaC:b-xawfbr)*

**Comment by benesch** [comment]
Ah, good point. We will soon: https://github.com/benesch/bincheck/blob/master/bincheck#L48-L51

**Review by petermattis — APPROVED** [review]
Does `bincheck` happen as part of the `teamcity` build process? If yes, this LGTM.

**Comment by benesch** [comment]
No, it doesn't, but it should. I'll hold off on merging this until then.

**Pull request closed without merging**
