### PR TITLE
pkg/util/log: always tag crdb_v2 & JSON logs with tenant ID

### PR DESCRIPTION
**Pull request by abarganier**
In CockroachDB's unified architecture future, logs for both the system and predefined app tenant will both go to the same file and directory (at least for our first iteration of this architecture).

With log entries from multiple tenants being written to a single file, it's necessary that we tag each log entry with the tenant ID that the log entry pertains to. Furthermore, if the context accompanying the log entry has a ServerIdentificationPayload, we should by default tag log entries with the system tenant ID. To make sure of this, `idPayload` has been updated with a `TenantID()` accessor function which returns the default system tenant ID in the event that the tenant ID in the `idPayload` is unpopulated.

This patch updates the crdb_v2 format to always be tagged with the tenant ID. With this patch, the crdb_v2 format makes use of the existing log tags to tag each log entry with a tenant ID. Once this change is merged, we no longer expect any log entries in the crdb_v2 format to have empty log tags (previously identified by `[-]`).

Now, we always expect the first v2 log tag in the list to identify the tenant that the entry belongs to. The log tag key used will be `T`, followed by the tenant ID. For example:

```
I060102 15:04:05.654321 11 util/log/format_crdb_v2_test.go:123 ⋮ [T1,noval,s‹1›]   I'm the system tenant
I060102 15:04:05.654321 11 util/log/format_crdb_v2_test.go:123 ⋮ [T2,noval,s‹1›]   I’m the app tenant
```

Since we make use of existing structures within the v2 format (tags), these changes should be backwards compatible.

When decoding, the logpb.Entry has been updated with an IdentificationPayload to explicitly store the tenant ID associated with a log entry. Decoding will also default to the system tenant ID across all formats in the event that no tenant ID tag is included in a log entry.

Finally, note that the JSON format is now always expected to include the tenant ID tag, given the above mentioned changes to add a `TenantID()` accessor function to the `idPayload`, which by default returns the system tenant ID if no tenant ID is available.

Future patches will update `debug merge-logs` with tenant ID filtering logic in a future patch to help users filter logs to specific tenants.

Release note (ops change): the crdb_v2 log format will now always contain a tenant ID in the logging tags for each log entry. This is to distinguish log entries between tenants when logs for multiple tenants are being written. These tenant ID tags will always come first in the list of logging tags, with a tag key of `T`.

For example, for the system tenant (tenant ID = 1), a log entry would look like:
```
I060102 15:04:05.654321 11 util/log/format_crdb_v2_test.go:123 ⋮ [T1,noval,s‹1›]   I'm the system tenant
```

For a secondary tenant, where tenant ID = 2, a log entry would look like:
```
I060102 15:04:05.654321 11 util/log/format_crdb_v2_test.go:123 ⋮ [T2,noval,s‹1›]   I’m an app tenant
```

Epic: https://cockroachlabs.atlassian.net/browse/CRDB-14486

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94432)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @knz)

___
*[`pkg/util/log/format_crdb_v2.go` line 631 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94432#-NKsEVrQA4szkHOvQlnE:-NKsEVrQA4szkHOvQlnF:b-f102hg) ([raw file](https://github.com/cockroachdb/cockroach/blob/393e017ce6adc47a399daa2eb46c8def00f98f87/pkg/util/log/format_crdb_v2.go#L631)):*
> ```Go
> 		Redactable: m.isRedactable(),
> 		Tags:       m.getTags(d.sensitiveEditor),
> 		IDPayload:  m.getIDPayload(),
> ```

I don't understand what we gain from having this field in the `Entry` struct. Can't it just sit in the tags like everything else? The special casing in the decoder just seems a bit brittle.

**Review by abarganier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94432)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @knz)

___
*[`pkg/util/log/format_crdb_v2.go` line 631 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94432#-NKsEVrQA4szkHOvQlnE:-NKsJERQ1RckRVN-MEMP:b-w3hdt6) ([raw file](https://github.com/cockroachdb/cockroach/blob/393e017ce6adc47a399daa2eb46c8def00f98f87/pkg/util/log/format_crdb_v2.go#L631)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I don't understand what we gain from having this field in the `Entry` struct. Can't it just sit in the tags like everything else? The special casing in the decoder just seems a bit brittle.
</blockquote></details>

I can understand why you're puzzled by this. I'll explain my reasoning.

We have various use cases (DB Console provided debug log endpoints, upcoming tenant ID filters for `debug merge logs`) where we are going to have to filter these `logpb.Entry` structs based on their tenant IDs. 

If we hold the ID with the rest of the tags, then we'll need to parse the ID tag out of the `Tags` string across all of these use cases. I figured it easier to hold them in a separate field when decoding the log entry to make our lives easier across these use cases, rather than having to parse/split it out from the tags within each. It also allows us to expand the identifiers in the future more easily when they're encapsulated in their own struct. Maybe the other way around is better, though? I'm open to suggestions for alternatives!

**Review by abarganier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94432)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @knz)

___
*[`pkg/util/log/format_crdb_v2.go` line 631 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94432#-NKsEVrQA4szkHOvQlnE:-NKtlV6mEGxnt6vHxZOi:bxbf1y0) ([raw file](https://github.com/cockroachdb/cockroach/blob/393e017ce6adc47a399daa2eb46c8def00f98f87/pkg/util/log/format_crdb_v2.go#L631)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

I can understand why you're puzzled by this. I'll explain my reasoning.

We have various use cases (DB Console provided debug log endpoints, upcoming tenant ID filters for `debug merge logs`) where we are going to have to filter these `logpb.Entry` structs based on their tenant IDs. 

If we hold the ID with the rest of the tags, then we'll need to parse the ID tag out of the `Tags` string across all of these use cases. I figured it easier to hold them in a separate field when decoding the log entry to make our lives easier across these use cases, rather than having to parse/split it out from the tags within each. It also allows us to expand the identifiers in the future more easily when they're encapsulated in their own struct. Maybe the other way around is better, though? I'm open to suggestions for alternatives!
</blockquote></details>

So, it turns out that adding a nested proto message within `logpb.Entry` for the server identifiers didn't play nicely with debug merge logs. This is because debug merge-logs relies on the ability to compare two `logpb.Entry`'s using `==`, and having a nested message broke these equality checks since a deep-equals was required.

I've opted to switch to a single `tenant_id` field at the root of `logpb.Entry` as a solution. I think the part of my argument that a separate struct "will make it easier to expand in the future" was not a very strong argument anyway.

PTAL

**Review by dhartunian — APPROVED** [review]
:lgtm: thanks for the detailed commit message. my one concern here is whether we've introduced a performance regression with the indirection around looking up a tenantID in the critical path of log serialization. Maybe we can run some benchmarks separately to see.

> Reviewed 3 of 17 files at r1, 5 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94432#-:-NKxYn6LDlHdTrKI6s8n:b-hktnxe)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier and @knz)

___
*[`-- commits` line 25 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94432#-NKxR8UV09L0KzSq4zdU):*
does log tag order matter?

**Review by abarganier — COMMENTED** [review]
Thanks for the review! Benchmarks sound like a good idea. It'd be cool to pair on that together sometime. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94432#-:-NKxdWz-3Fb1jwV98bpz:b-2gaqsi)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian and @knz)

___
*[`-- commits` line 25 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94432#-NKxR8UV09L0KzSq4zdU):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

does log tag order matter?
</blockquote></details>

For the v2 format it does - we always expect the first tag to be the tenant ID.

**Comment by abarganier** [comment]
TFTR!

bors r=dhartunian

**Pull request merged**
