### PR TITLE
roachprod: validate host before running command

### LINKED ISSUE #63637: roachprod: `roachprod ssh` can connect you to an unrelated cluster besides the one you requested
```
cockroach$ ./bin/roachprod ssh ricky-test:1
Warning: Permanently added '35.185.81.185' (ECDSA) to the list of known hosts.
Welcome to Ubuntu 16.04.6 LTS (GNU/Linux 4.15.0-1052-gcp x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
0 packages can be updated.
0 updates are security updates.
New release '18.04.5 LTS' available.
Run 'do-release-upgrade' to upgrade to it.
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.
ubuntu@davidh-large-console-test-0024:~$ ls
cockroach  lib  logs
```

The node I was connected to is node 24 of the cluster `davidh-large-console-test`, which is definitely not `ricky-test`.

I think the cluster `ricky-test` was deleted by the time I tried to SSH in, though I don't know why it would have chosen a completely different node/cluster and silently connected me.

Epic CRDB-10428

Jira issue: CRDB-6679

### LINKED ISSUE #89437: roachprod: validate host before running a command
**Describe the problem**

When running a roachprod command that doesn't synchronize the local cache, it's possible that the underlying cluster may have expired and the IPs associated with the VMs have been reused by a new cluster. In such cases, roachprod will happily run the commands on those hosts thinking it belongs to the old cluster.

This has happened in #88445, and debugging the aftermath of this type of error can be very puzzling and time consuming

**Desired behavior**

`roachprod` could validate the host before running a command. This could be done by checking hostnames, creation timestamps, or something else.

Jira issue: CRDB-20253

### PR DESCRIPTION
**Pull request by renatolabs**
This commit adds a wrapper to every command run on a remote roachprod cluster with checks that the node still belongs to the cluster roachprod thinks it does. Specifically, it stops roachprod commands from interfering with unrelated clusters if the roachprod cache is not up to date.

Consider the following set of steps:

```console
$ roachprod create cluster-a -n 1 --lifetime 1h
$ roachprod put cluster-a ./cockroach ./cockroach
$ roachprod start cluster-a
```

One hour later, `cluster-a`'s lifetime expires and the VM is destroyed. Another user (or a Team City agent) creates another cluster:

```console
$ roachprod create cluster-b -n 1
$ roachprod put cluster-b ./cockroach ./cockroach
$ roachprod start cluster-b
```

In the process of creating `cluster-b`, it is possible that the public IP for cluster A's VM is reused and assigned to cluster B's VM. To simulate that situation on a single client, we can manually edit roachprod's cache.

Now suppose the creator of `cluster-a`, not knowing the cluster was expired and now with a stale cache, runs:

```console
$ roachprod stop cluster-a
```

This will unintentionally stop cockroach on `cluster-b`! A client with an updated cache will see the following output:

```console
$ roachprod status cluster-b
cluster-b: status 1/1
17:14:31 main.go:518:    1: not running
```

In addition, it's confusing, from cluster B's perspective, why the cockroach process died -- all we know is that it was killed and the process exited with code 137:

```console
$ roachprod run cluster-b 'sudo journalctl' | grep cockroach
Mar 06 17:18:33 renato-cluster-b-0001 systemd[1]: Starting /usr/bin/bash ./cockroach.sh run...
Mar 06 17:18:33 renato-cluster-b-0001 bash[13384]: cockroach start: Mon Mar  6 17:18:33 UTC 2023, logging to logs
Mar 06 17:18:34 renato-cluster-b-0001 systemd[1]: Started /usr/bin/bash ./cockroach.sh run.
Mar 06 17:19:04 renato-cluster-b-0001 bash[13381]: ./cockroach.sh: line 67: 13386 Killed                  "${BINARY}" "${ARGS[@]}" >> "${LOG_DIR}/cockroach.stdout.log" 2>> "${LOG_DIR}/cockroach.stderr.log"
Mar 06 17:19:04 renato-cluster-b-0001 bash[13617]: cockroach exited with code 137: Mon Mar  6 17:19:04 UTC 2023
Mar 06 17:19:04 renato-cluster-b-0001 systemd[1]: cockroach.service: Main process exited, code=exited, status=137/n/a
Mar 06 17:19:04 renato-cluster-b-0001 systemd[1]: cockroach.service: Failed with result 'exit-code'.
```

With the changes in this commit, the `roachprod stop` call will now fail since the hostnames don't match:

```console
$ roachprod stop cluster-a
cluster-a: stopping and waiting 1/1
0: COMMAND_PROBLEM: exit status 1
(1) COMMAND_PROBLEM
Wraps: (2) exit status 1
Error types: (1) errors.Cmd (2) *exec.ExitError: expected host to be part of cluster-a, but is cluster-b-0001
```

Finally, `roachprod ssh` calls will now also fail if the hostnames do not match, instead of silently connecting to the wrong cluster.

Resolves #89437.
Resolves #63637.

Release note: None

### CODE REVIEW

**Review by herkolategan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98076)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs and @srosenberg)

___
*[`pkg/roachprod/install/cluster_synced.go` line 331 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98076#-NPsdTxLEVq7EzE3bv_K:-NPsdTxLEVq7EzE3bv_L:b-eq4i7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/13b30212911b89563584f275442e2254f993651e/pkg/roachprod/install/cluster_synced.go#L331)):*
> ```Go
> // By wrapping every command with a hostname check as is done here, we
> // ensure that the cached cluster information is still correct.
> func (c *SyncedCluster) validateHost(cmd string, node Node) string {
> ```

Nit: The name of this function could be a bit more descriptive to let the caller know it's not actually validating the host, but rather supplying a wrapped command that can do so (I guess the return type is somewhat indicative of this). But having tried to think of a better name, I couldn't really come up with one.
___
*[`pkg/roachprod/install/cluster_synced.go` line 343 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98076#-NPsf2VL17BAvohiZngY:-NPsf2VL17BAvohiZngZ:b4c6v58) ([raw file](https://github.com/cockroachdb/cockroach/blob/13b30212911b89563584f275442e2254f993651e/pkg/roachprod/install/cluster_synced.go#L343)):*
> ```Go
> 	}
> 
> 	return fmt.Sprintf(`
> ```

I almost want to recommend using `text/template` for the contents of this function, but I think here it might be more effort than it's worth. And the `elseBranch` logic might be a challenge. Since the `exit 1` short circuits the script, the branch might not be required (just append the command). But you most likely already considered this.

**Review by herkolategan — APPROVED** [review]
LGTM, left a few comments in general, but just for thought, not necessarily actionable.

> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98076#-:-NPsh_lB8pXm4ltJsJg0:b-79lt8e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs and @srosenberg)

**Review by srosenberg — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98076)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @renatolabs)

___
*[`pkg/roachprod/install/cluster_synced.go` line 331 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98076#-NPsdTxLEVq7EzE3bv_K:-NPwsHlT-a8qUJ77jaWg:bqkdjp) ([raw file](https://github.com/cockroachdb/cockroach/blob/13b30212911b89563584f275442e2254f993651e/pkg/roachprod/install/cluster_synced.go#L331)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

Nit: The name of this function could be a bit more descriptive to let the caller know it's not actually validating the host, but rather supplying a wrapped command that can do so (I guess the return type is somewhat indicative of this). But having tried to think of a better name, I couldn't really come up with one.
</blockquote></details>

`validateHostnameCmd`?
___
*[`pkg/roachprod/install/cluster_synced.go` line 332 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98076#-NPwtznE1JSE5GV4MO4y:-NPwtznE1JSE5GV4MO4z:b-4tr1vq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3de9c693d5524f207565b954066368fd06696e69/pkg/roachprod/install/cluster_synced.go#L332)):*
> ```Go
> // ensure that the cached cluster information is still correct.
> func (c *SyncedCluster) validateHost(cmd string, node Node) string {
> 	isValidHost := fmt.Sprintf("[[ `hostname` == '%s' ]]", vm.Name(c.Name, int(node)))
> ```

I see two potential issues with this type of check,

* is `hostname` guaranteed to be set to the expected value across all supported cloud providers?
* what about the case when a fresh cluster with the _same_ name is created?

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98076)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @srosenberg)

___
*[`pkg/roachprod/install/cluster_synced.go` line 332 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98076#-NPwtznE1JSE5GV4MO4y:-NPxpZaQACAkSleWsww_:b-moptmc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3de9c693d5524f207565b954066368fd06696e69/pkg/roachprod/install/cluster_synced.go#L332)):*
> is hostname guaranteed to be set to the expected value across all supported cloud providers?

Good call; the default hostname for AWS is indeed different, but it's thankfully easy to update (see changes in start script now included in this PR); I confirmed we get the same behavior on AWS now.

As for Azure, I think it should also work without changes from what I read in their documentation, but I'll run some tests soon to verify.

> what about the case when a fresh cluster with the same name is created?

This will indeed not reject commands if 1) cluster has the same name; and 2) it was deleted and re-created and the same IP was reused.

I'm struggling to think of a scenario where this could actually happen. The timing for the events needs to be very precise; coupled with the fact that 1) we typically prefix cluster names with our usernames and 2) teamcity cluster names are unique, I think the hostname check is a fairly reasonable compromise.

That said, I'm open to other solutions if we think there's a better path here. I see that one comment in the original issue was to use instance metadata or labels. That would not be susceptible to your second issue, but a couple of downsides of that is that we would rely on cloud-specific code to do this check and also querying that data would add potentially non-negligible delay to every remote session.

Thoughts?

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98076)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @srosenberg)

___
*[`pkg/roachprod/install/cluster_synced.go` line 331 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98076#-NPsdTxLEVq7EzE3bv_K:-NPy2BubDx5FTyZRBieh:b-93rb52) ([raw file](https://github.com/cockroachdb/cockroach/blob/13b30212911b89563584f275442e2254f993651e/pkg/roachprod/install/cluster_synced.go#L331)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

`validateHostnameCmd`?
</blockquote></details>

Updated to `validateHostnameCmd`.
___
*[`pkg/roachprod/install/cluster_synced.go` line 343 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98076#-NPsf2VL17BAvohiZngY:-NPy2EIl48iIM8KKVTGI:b-du1525) ([raw file](https://github.com/cockroachdb/cockroach/blob/13b30212911b89563584f275442e2254f993651e/pkg/roachprod/install/cluster_synced.go#L343)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

I almost want to recommend using `text/template` for the contents of this function, but I think here it might be more effort than it's worth. And the `elseBranch` logic might be a challenge. Since the `exit 1` short circuits the script, the branch might not be required (just append the command). But you most likely already considered this.
</blockquote></details>

I thought about it and came to the same conclusion as you: it seemed more work than it's worth. I believe the size of the script here is small enough that it should be relatively straightforward to understand what is going on; we can change that if we see ourselves updating this logic (which I hope wouldn't happen in a long time).

**Review by srosenberg — APPROVED** [review]
:lgtm:

Thanks for testing this in AWS and Azure!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98076#-:-NPyDXpm8tTC5_7RYXIa:ba07yxw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan and @renatolabs)

___
*[`pkg/roachprod/install/cluster_synced.go` line 332 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98076#-NPwtznE1JSE5GV4MO4y:-NPyBNV72PCBgqf-uHqb:b4516ty) ([raw file](https://github.com/cockroachdb/cockroach/blob/3de9c693d5524f207565b954066368fd06696e69/pkg/roachprod/install/cluster_synced.go#L332)):*
> I think the hostname check is a fairly reasonable compromise.

Yep, I completely agree. I only raised it as a _potential_, _secondary_ issue. It's indeed rare, and we have safeguards like unique cluster names. The contrived scenario is someone creating a shared cluster, say `$team-test`; someone else destroys; subsequently, it's created again, and that initial someone with the stale (local) cache does `roachprod stop` or something else that's destructive. :)

> That said, I'm open to other solutions if we think there's a better path here.

Considering (a) `hostname` check works everywhere, (b) extremely low probability of the contrived scenario, and (c) other workarounds add either more overhead or coupling, or both, I am perfectly content with the one in this PR!

**Review by srosenberg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98076)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan and @renatolabs)

___
*[`pkg/roachprod/vm/aws/support.go` line 154 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/98076#-NPyFZzh4fEiZdp6tM0v:-NPyFZzh4fEiZdp6tM0w:by9wy2h) ([raw file](https://github.com/cockroachdb/cockroach/blob/465a0f4fab182f6c4d2d641d0e7548e47ebe6388/pkg/roachprod/vm/aws/support.go#L154)):*
> ```Go
> # set hostname according to the name used by roachprod. There's host
> # validation logic that relies on this -- see comment on cluster_synced.go
> sudo hostnamectl set-hostname {{.VMName}}
> ```

Let's add `--static` so that it survives reboot. None of the existing roachtests do this today, although tpccbench has/had that option I believe. The manually created clusters could in theory be rebooted albeit not frequently.

**Review by renatolabs — COMMENTED** [review]
Since this change has the potential for significant disruption (as it changes the actual command run in every session), I ran a nightly build on this branch on both GCP [1] and AWS [2]. Everything looks good, failures observed are the same failures we see on master, so this is ready to merge.

I also ran a manual test on Azure, and the hostname validation works without changes.

[1] <https://teamcity.cockroachdb.com/viewLog.html?buildId=8962079&tab=buildResultsDiv&buildTypeId=Cockroach_Nightlies_RoachtestNightlyGceBazel>
[2] https://teamcity.cockroachdb.com/viewLog.html?buildId=8972458&buildTypeId=Cockroach_Nightlies_RoachtestNightlyAwsBazel

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98076#-:-NQ2WoWo4sHCUfPMx9Lh:b31nikn)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan and @srosenberg)

___
*[`pkg/roachprod/vm/aws/support.go` line 154 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/98076#-NPyFZzh4fEiZdp6tM0v:-NQ2XGjN3HjXJ9HJu-b0:bhudhz8) ([raw file](https://github.com/cockroachdb/cockroach/blob/465a0f4fab182f6c4d2d641d0e7548e47ebe6388/pkg/roachprod/vm/aws/support.go#L154)):*
According to the documentation for `set-hostname` [1]:

> Set the system hostname to NAME. By default, this will alter the pretty, the static, and the transient hostname alike; however, if one or more of --static, --transient, --pretty are used, only the selected hostnames are changed.

So what we're doing here is a superset of what would be done if we passed `--static`. I verified that rebooting an AWS VM created by roachprod does not reset the hostname.

[1] <https://manpages.ubuntu.com/manpages/xenial/man1/hostnamectl.1.html>

**Comment by renatolabs** [comment]
bors r=herkolategan,srosenberg

TFTRs!

**Pull request merged**
