### PR TITLE
acceptance, ccl, cli, cmd, config, gossip, internal, jobs: cleanup lock usages

### PR DESCRIPTION
**Pull request by Santamaura**
This PR updates unsafe/unnecessary manual unlocks to defer unlocks.
The criteria for leaving some unlocks as is:
 - will not cause a leak
 - releases the resources much earlier
 - deferring will cause a deadlock without significant refactor

Part of #107946

Release note: None

Signoffs
- [x] acceptance
- [x] backupccl
- [x] changefeedccl
- [x] multitenantccl
- [x] sqlproxyccl
- [x] cli
- [x] cmd
- [x] config
- [x] gossip
- [x] internal
- [x] jobs

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
I took a brief look and gave some advice on a few instances where your refactor should be reconsidered. Maybe as a first pass, you can make a PR for all the "simple" refactors where adding a `defer` is less disruptive.

One thing I'm not 100% clear on is the impact of adding the `defer` inside an immediately executed anonymous function. Maybe a good topic to discuss at tech pod.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-:-Navj5zC3RDMZOdmCd3R:b-96tjca)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Santamaura)

___
*[`pkg/acceptance/localcluster/cluster.go` line 488 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-NavgvPp9RY1mZKoHeq7:-NavgvPp9RY1mZKoHeq8:b-e2oxbd) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbaf90c1d2944ffcdbd199dad12f587b4dcbb21d/pkg/acceptance/localcluster/cluster.go#L488)):*
> ```Go
> func (n *Node) StatusClient(ctx context.Context) serverpb.StatusClient {
> 	n.Lock()
> 	defer n.Unlock()
> ```

Adding this defer here, moves the unlock until *after* the `GRPCUnvalidatedDial...Connect()` call which could take an unknown amount of time.

The unlock was likely put at the top here in order to keep it from being held for a long time. Basically just to grab the `statusClient` safely.

Consider doing this within an anonymous function like:

```
var existingClient ...
func () {
  n.Lock()
  defer n.Unlock()
  existingClient = ...
}()
```

Although in this *particular* case it's impossible for the code between the Lock/Unlock to panic so it's less of a concern. But consider this pattern in the situations below.
___
*[`pkg/acceptance/localcluster/cluster.go` line 704 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-NavhWoi0M_G1ATg3FA0:-NavhWoi0M_G1ATg3FA1:b-sv8u0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbaf90c1d2944ffcdbd199dad12f587b4dcbb21d/pkg/acceptance/localcluster/cluster.go#L704)):*
> ```Go
> 	}
> 	n.Lock()
> 	defer n.Unlock()
> ```

Replacing multiple Lock/Unlock calls with a single one could radically change the performance profile of the code. It's unlikely that this is a valid refactor.

The locks were carefully taken in the original code around specific variables that needed to be lifted out from `n`.

One thing that's a hint much like the gRPC example above is that we have an `os.ReadFile` that's originally done without a lock held which after your change does happen during the Lock. Reading a file could take an *extremely* long time compared to a Lock being held. This causes problems when requests are made concurrently on the function and all concurrent requests then have to wait for the Lock. If you hold the Lock while reading the file, no one else can make progress until you're done reading the file, whereas if you maintain the fine-grained locking, many calls can proceed concurrently because they block each other for only a miniscule period of time.

Consider the measured difference on pages like https://colin-scott.github.io/personal_website/research/interactive_latency.html where mutex lock/unlock is on the order of 17ns while SSD random read is 16,000ns. So do not perceive many Lock/Unlock operations as "bad" necessarily.
___
*[`pkg/ccl/backupccl/restore_job.go` line 2133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-NavihizEUfkqDhY9FQL:-NavihizEUfkqDhY9FQM:bi0d4uz) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbaf90c1d2944ffcdbd199dad12f587b4dcbb21d/pkg/ccl/backupccl/restore_job.go#L2133)):*
> ```Go
> 					}
> 					mu.Lock()
> 					defer mu.Unlock()
> ```

`defer` moves the `mu.Unlock()` to the end of the function call, not the `select` or the `for` loop. In this case you would immediately create a deadlock because the `for` loop runs forever and would never unlock.

This is another case where an anonymous function immediately executed can help.

**Review by jayshrivastava — COMMENTED** [review]
changefeedccl/ changes lgtm!

**Review by RaduBerinde — COMMENTED** [review]
I made a pass. I suggest going back through all the changes and making sure the critical sections are not modified. We want this to be a cosmetic change and nothing more. I'd error on the side of adding the nolint comment rather than changing what the critical section covers. Sometimes innocuous looking changes are not that innocuous.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-:-NbRKqZO-o27mUt-fAcm:b-62py2t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @bananabrick, @DrewKimball, and @Santamaura)

___
*[`pkg/acceptance/localcluster/cluster.go` line 697 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-NbRIfVz2pbkAvUngKcl:-NbRIfVz2pbkAvUngKcm:bh8hkcj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e879113f2e24cfc3da50488819611fc3d44dc697/pkg/acceptance/localcluster/cluster.go#L697)):*
> ```Go
> 	for r := retry.Start(opts); r.Next(); {
> 		var pid int
> 		if n.cmd != nil {
> ```

Here we're accessing `n.cmd` outside of the lock but in one of the fragments below (line 784) we lock just to get `n.cmd`
___
*[`pkg/acceptance/localcluster/cluster.go` line 698 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-NbRIUfKC_auQetwoS_2:-NbRIUfKC_auQetwoS_3:b-99u9b3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aa46154a922a5dfdabb3e5f8f1ae990d645ada1/pkg/acceptance/localcluster/cluster.go#L698)):*
> ```Go
> 			pid = n.cmd.Process.Pid
> 		}
> 		n.Unlock()
> ```

[nit] I would just add the linter comment here, it's cleaner the old way here
___
*[`pkg/ccl/changefeedccl/event_processing.go` line 661 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-NbRJ5Jl9L1gX03HSjw5:-NbRJ5Jl9L1gX03HSjw6:b-1khg7d) ([raw file](https://github.com/cockroachdb/cockroach/blob/e879113f2e24cfc3da50488819611fc3d44dc697/pkg/ccl/changefeedccl/event_processing.go#L661)):*
> ```Go
> 	// that there are no more events.
> 	if notifyFlush {
> 		c.flushCh <- struct{}{}
> ```

We weren't holding the lock here before.. In principle, this can block.
___
*[`pkg/ccl/changefeedccl/sink_kafka.go` line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-NbRJKwg6euxrOZjK68e:-NbRJKwg6euxrOZjK68f:b-ulix0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/e879113f2e24cfc3da50488819611fc3d44dc697/pkg/ccl/changefeedccl/sink_kafka.go#L55)):*
> ```Go
> func (l *maybeLocker) Unlock() {
> 	if l.locked {
> 		defer l.wrapped.Unlock()
> ```

This is probably incorrect (we set `locked=false` before actually unlocking)
___
*[`pkg/ccl/changefeedccl/kvevent/blocking_buffer.go` line 157 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-NbRJ_XR5qdL2zTu5YAT:-NbRJ_XR5qdL2zTu5YAU:b-mdpd71) ([raw file](https://github.com/cockroachdb/cockroach/blob/e879113f2e24cfc3da50488819611fc3d44dc697/pkg/ccl/changefeedccl/kvevent/blocking_buffer.go#L157)):*
> ```Go
> 	if canFlush {
> 		select {
> 		case b.signalCh <- struct{}{}:
> ```

We weren't holding the lock here before. In principle it could matter if `signalCh` is unbuffered and the receiver needs the lock.
___
*[`pkg/ccl/sqlproxyccl/tenantdirsvr/test_directory_svr.go` line 203 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-NbRJrqA55lRDeFcPejv:-NbRJrqA55lRDeFcPejw:b-1w64uu) ([raw file](https://github.com/cockroachdb/cockroach/blob/e879113f2e24cfc3da50488819611fc3d44dc697/pkg/ccl/sqlproxyccl/tenantdirsvr/test_directory_svr.go#L203)):*
> ```Go
> 				case <-s.stopper.ShouldQuiesce():
> 					func() {
> 						s.mu.eventListeners.Remove(elem)
> ```

missing lock/unlock here. Consider adding a method on `s` for removing an event listener
___
*[`pkg/gossip/client.go` line 156 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-NbRKDkpC1p2SEi8jjUp:-NbRKDkpC1p2SEi8jjUq:bwrtvuk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e879113f2e24cfc3da50488819611fc3d44dc697/pkg/gossip/client.go#L156)):*
> ```Go
> // timestamps.
> func (c *client) requestGossip(g *Gossip, stream Gossip_GossipClient) error {
> 	args := func() *Request {
> ```

[nit] it would be cleaner if this func only returned NodeAddr and highwaterstamps
___
*[`pkg/internal/sqlsmith/bulkio.go` line 219 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-NbRKT3l9IajHMpgAodY:-NbRKT3l9IajHMpgAodZ:bjem7dj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e879113f2e24cfc3da50488819611fc3d44dc697/pkg/internal/sqlsmith/bulkio.go#L219)):*
> ```Go
> 		defer s.lock.Unlock()
> 		return len(s.bulkExports) == 0
> 	}(); !noBulkExports {
> ```

The ! here seems wrong, we want to exit if there are no bulkExport. Also, dropping the lock and reacquiring is not the same as before. In principle, bulkExports could change in-between. I think we want a function that returns the `files`. We already check for empty files afterwards.

**Review by otan — COMMENTED** [review]
spatial changes look ok, but unconfident on reviewing the rest

**Review by Santamaura — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-:-NbVtX8W3k-S-JGWzhg9:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @bananabrick, @dhartunian, @DrewKimball, and @RaduBerinde)

___
*[`pkg/acceptance/localcluster/cluster.go` line 698 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-NbRIUfKC_auQetwoS_2:-NbVtw2e3xuV__Pg1gYR:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aa46154a922a5dfdabb3e5f8f1ae990d645ada1/pkg/acceptance/localcluster/cluster.go#L698)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I would just add the linter comment here, it's cleaner the old way here
</blockquote></details>

Done
___
*[`pkg/ccl/backupccl/restore_job.go` line 2133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-NavihizEUfkqDhY9FQL:-NbVu3iN2IRd27k9AxH3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbaf90c1d2944ffcdbd199dad12f587b4dcbb21d/pkg/ccl/backupccl/restore_job.go#L2133)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

`defer` moves the `mu.Unlock()` to the end of the function call, not the `select` or the `for` loop. In this case you would immediately create a deadlock because the `for` loop runs forever and would never unlock.

This is another case where an anonymous function immediately executed can help.
</blockquote></details>

Done.
___
*[`pkg/ccl/changefeedccl/event_processing.go` line 661 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-NbRJ5Jl9L1gX03HSjw5:-NbVu6EQ45Iuqet-l07B:b-bu91xm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e879113f2e24cfc3da50488819611fc3d44dc697/pkg/ccl/changefeedccl/event_processing.go#L661)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We weren't holding the lock here before.. In principle, this can block.
</blockquote></details>

Updated
___
*[`pkg/ccl/changefeedccl/sink_kafka.go` line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-NbRJKwg6euxrOZjK68e:-NbVuB3P13tqG-wv7-uD:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e879113f2e24cfc3da50488819611fc3d44dc697/pkg/ccl/changefeedccl/sink_kafka.go#L55)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is probably incorrect (we set `locked=false` before actually unlocking)
</blockquote></details>

Done
___
*[`pkg/ccl/changefeedccl/kvevent/blocking_buffer.go` line 157 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-NbRJ_XR5qdL2zTu5YAT:-NbVuEvF04cemwh5sSTQ:b-bu91xm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e879113f2e24cfc3da50488819611fc3d44dc697/pkg/ccl/changefeedccl/kvevent/blocking_buffer.go#L157)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We weren't holding the lock here before. In principle it could matter if `signalCh` is unbuffered and the receiver needs the lock.
</blockquote></details>

Updated
___
*[`pkg/ccl/sqlproxyccl/tenantdirsvr/test_directory_svr.go` line 203 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-NbRJrqA55lRDeFcPejv:-NbVuInlCDbdgsKk4CiW:b-8b11j9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e879113f2e24cfc3da50488819611fc3d44dc697/pkg/ccl/sqlproxyccl/tenantdirsvr/test_directory_svr.go#L203)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

missing lock/unlock here. Consider adding a method on `s` for removing an event listener
</blockquote></details>

Added
___
*[`pkg/gossip/client.go` line 156 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-NbRKDkpC1p2SEi8jjUp:-NbVuKAmE-xVL_7DYnMP:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e879113f2e24cfc3da50488819611fc3d44dc697/pkg/gossip/client.go#L156)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] it would be cleaner if this func only returned NodeAddr and highwaterstamps
</blockquote></details>

Done
___
*[`pkg/internal/sqlsmith/bulkio.go` line 219 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-NbRKT3l9IajHMpgAodY:-NbVuMdY6gPy7anqkM0W:b-bu91xm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e879113f2e24cfc3da50488819611fc3d44dc697/pkg/internal/sqlsmith/bulkio.go#L219)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The ! here seems wrong, we want to exit if there are no bulkExport. Also, dropping the lock and reacquiring is not the same as before. In principle, bulkExports could change in-between. I think we want a function that returns the `files`. We already check for empty files afterwards.
</blockquote></details>

Updated

**Review by adityamaru — COMMENTED** [review]
backupccl lgtm, thanks

**Comment by Santamaura** [comment]
Could I have someone from @cockroachdb/sqlproxy-prs review the `sqlproxyccl` changes? Thanks in advance.

**Review by jeffswenson — APPROVED** [review]
sqlproxyccl and tenantcostclient changes LGTM

**Review by adityamaru — COMMENTED** [review]
jobs lgtm

**Review by nvb — COMMENTED** [review]
gossip LGTM

As we make these changes, are we verifying that escape analysis is doing the right thing and avoiding new heap allocations around these closures?

> Reviewed 3 of 18 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-:-NdeqqOx4UCXp9bHnA4L:b-pmtfff)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick, @dhartunian, @DrewKimball, @otan, @RaduBerinde, and @Santamaura)

**Review by Santamaura — COMMENTED** [review]
From what I understand, as long as any captured variables are only used within the scope of the main functions then it will not allocate to the heap.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-:-NdevjN09PtdHluuuK--:bv36cwu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick, @dhartunian, @DrewKimball, @otan, and @RaduBerinde)

**Comment by nvanbenschoten** [comment]
That should be the case, but escape analysis has a way of being finicky around closures, especially if those closures are calling other functions that accept pointer arguments. It's worth verifying now instead of searching for small performance regressions later.

**Review by knz — COMMENTED** [review]
> Reviewed 4 of 22 files at r2, 9 of 18 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108064)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick, @dhartunian, @DrewKimball, @otan, @RaduBerinde, and @Santamaura)

___
*[`pkg/gossip/client.go` line 129 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-NdfCZy267oC1bhgSEQR:-NdfCZy267oC1bhgSEQS:b-jgrg35) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b8984dfdf66d9a0e83fa57bd34208008744086e/pkg/gossip/client.go#L129)):*
> ```Go
> 				func() {
> 					g.mu.RLock()
> 					defer g.mu.RUnlock()
> ```

let's avoid logging under this lock. try this:
```go
peerID, addr := func() { /* locking here */}()
if peerID != 0 {
   /* use copy here */
} else { /*ditto*/ }
```
___
*[`pkg/gossip/gossip.go` line 546 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-NdfCmT14cqBQM4HgTGM:-NdfCmT14cqBQM4HgTGN:b-6meo66) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b8984dfdf66d9a0e83fa57bd34208008744086e/pkg/gossip/gossip.go#L546)):*
> ```Go
> 	var n int
> 	var status redact.SafeString
> 	func() {
> ```

nit: `n, status := func() ...`
___
*[`pkg/internal/sqlsmith/bulkio.go` line 215 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-NdfDEn-5m3JL4uEVJx8:-NdfDEn-5m3JL4uEVJx9:bmj54uu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b8984dfdf66d9a0e83fa57bd34208008744086e/pkg/internal/sqlsmith/bulkio.go#L215)):*
> ```Go
> 	var exp string
> 	// Find all CSV files created by the EXPORT.
> 	files := func() tree.Exprs {
> ```

nit: consider making the function return `exp` too.
___
*[`pkg/internal/sqlsmith/bulkio.go` line 240 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-NdfDKQQ9hvrH0dIVhwX:-NdfDKQQ9hvrH0dIVhwY:b-vkly78) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b8984dfdf66d9a0e83fa57bd34208008744086e/pkg/internal/sqlsmith/bulkio.go#L240)):*
> ```Go
> 	var schema string
> 	var tableSchema []byte
> 	func() {
> ```

nit: `schema, tableSchema := func() ...`
___
*[`pkg/jobs/adopt.go` line 433 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-NdfDNsBCSNLYBCH4p2T:-NdfDNsBCSNLYBCH4p2U:b-ifj86j) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b8984dfdf66d9a0e83fa57bd34208008744086e/pkg/jobs/adopt.go#L433)):*
> ```Go
> 	var username username.SQLUsername
> 	var typ jobspb.Type
> 	func() {
> ```

nit: `username, typ := func() ...`
___
*[`pkg/jobs/progress.go` line 143 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-NdfDWQz8xPxbtmpY57E:-NdfDWQz8xPxbtmpY57F:b-wlklyy) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b8984dfdf66d9a0e83fa57bd34208008744086e/pkg/jobs/progress.go#L143)):*
> ```Go
> // new progress amount.
> func (p *ProgressUpdateBatcher) Add(ctx context.Context, delta float32) error {
> 	var shouldReport bool
> ```

nit: `shouldReport, completed := func() ...`

**Review by Santamaura — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108064)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick, @dhartunian, @DrewKimball, @knz, @nvanbenschoten, @otan, and @RaduBerinde)

___
*[`pkg/gossip/client.go` line 129 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-NdfCZy267oC1bhgSEQR:-NdfN86fD90oik5DNP_c:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b8984dfdf66d9a0e83fa57bd34208008744086e/pkg/gossip/client.go#L129)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

let's avoid logging under this lock. try this:
```go
peerID, addr := func() { /* locking here */}()
if peerID != 0 {
   /* use copy here */
} else { /*ditto*/ }
```
</blockquote></details>

Done.
___
*[`pkg/gossip/gossip.go` line 546 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-NdfCmT14cqBQM4HgTGM:-NdfNF3X5vZmpPmSBB9E:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b8984dfdf66d9a0e83fa57bd34208008744086e/pkg/gossip/gossip.go#L546)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: `n, status := func() ...`
</blockquote></details>

Done.
___
*[`pkg/internal/sqlsmith/bulkio.go` line 215 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-NdfDEn-5m3JL4uEVJx8:-NdfNH3i94QXVDFDjjDT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b8984dfdf66d9a0e83fa57bd34208008744086e/pkg/internal/sqlsmith/bulkio.go#L215)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: consider making the function return `exp` too.
</blockquote></details>

Done.
___
*[`pkg/internal/sqlsmith/bulkio.go` line 240 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-NdfDKQQ9hvrH0dIVhwX:-NdfNJSp6VsNEi0mxLtu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b8984dfdf66d9a0e83fa57bd34208008744086e/pkg/internal/sqlsmith/bulkio.go#L240)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: `schema, tableSchema := func() ...`
</blockquote></details>

Done.
___
*[`pkg/jobs/adopt.go` line 433 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-NdfDNsBCSNLYBCH4p2T:-NdfNMtZEuYMDHiYgehV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b8984dfdf66d9a0e83fa57bd34208008744086e/pkg/jobs/adopt.go#L433)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: `username, typ := func() ...`
</blockquote></details>

Done.
___
*[`pkg/jobs/progress.go` line 143 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-NdfDWQz8xPxbtmpY57E:-NdfNPvM1XQOw4UayU6h:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b8984dfdf66d9a0e83fa57bd34208008744086e/pkg/jobs/progress.go#L143)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: `shouldReport, completed := func() ...`
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
> Reviewed 4 of 5 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108064)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick, @dhartunian, @DrewKimball, @otan, @RaduBerinde, and @Santamaura)

**Review by Santamaura — COMMENTED** [review]
> That should be the case, but escape analysis has a way of being finicky around closures, especially if those closures are calling other functions that accept pointer arguments. It's worth verifying now instead of searching for small performance regressions later.

I found your `goescape` script it was very useful :slightly_smiling_face: . I reviewed all the files and there's only 1 occurrence of a closure from the changes escaping to the heap, which I think should have minimal perf impact.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108064#-:-NdlAotgAFiwLsEDNPWB:b-z648y0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick, @dhartunian, @DrewKimball, @otan, and @RaduBerinde)

**Pull request merged**
