### PR TITLE
roachtest: update ORM blocklists for v21.2

### LINKED ISSUE #64301: roachtest: pgjdbc failed
roachtest.pgjdbc [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2928832&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=2928832&tab=artifacts#/pgjdbc) on master @ [9f198e190812bf301e8a2126cf43cd78e1cfb163](https://github.com/cockroachdb/cockroach/commits/9f198e190812bf301e8a2126cf43cd78e1cfb163):

```
		--- FAIL: org.postgresql.test.jdbc2.UpdateableResultTest.testUpdateStreams - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.DatabaseMetaDataTest.testAscDescIndexInfo[binary = FORCE] - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.PGObjectGetTest.getAsPGobjectSubtype[binary = REGULAR, sql = null::box, type = class org.postgresql.geometric.PGbox] - unknown (unexpected)
		--- FAIL: org.postgresql.replication.LogicalReplicationTest.testDoesNotHavePendingMessageWhenStartFromLastLSN - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.PGObjectSetTest.setNullAsPGobjectSubtype[binary = FORCE, sql = box, type = class org.postgresql.geometric.PGbox] - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.PGObjectGetTest.getAsPGobjectSubtype[binary = FORCE, sql = null::box, type = class org.postgresql.geometric.PGbox] - unknown (unexpected)
		--- FAIL: org.postgresql.jdbc.PgSQLXMLTest.testGetSourceXxeSAXSource - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.DatabaseMetaDataTest.testFuncReturningTable[binary = REGULAR] - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.PGObjectGetTest.getAsPGobjectSubtype[binary = REGULAR, sql = null::lseg, type = class org.postgresql.geometric.PGlseg] - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.PGObjectGetTest.getAsPGobjectSubtype[binary = FORCE, sql = null::path, type = class org.postgresql.geometric.PGpath] - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.DatabaseMetaDataTest.testForeignKeyActions[binary = FORCE] - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.PGObjectSetTest.setNullAsPGobject[binary = FORCE, sql = line, type = class org.postgresql.geometric.PGline] - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc4.JsonbTest.jsonbArray[binary = REGULAR] - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.PGObjectGetTest.getAsPGobject[binary = FORCE, sql = null::path, type = class org.postgresql.geometric.PGpath] - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.DatabaseMetaDataTest.testForeignKeysToUniqueIndexes[binary = REGULAR] - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.DatabaseMetaDataTest.testFuncWithNames[binary = REGULAR] - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.ArrayTest.testIndexAccess[binary = FORCE] - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.DatabaseMetaDataTest.testTables[binary = REGULAR] - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.ResultSetMetaDataTest.testSmallSerialColumns[databaseMetadataCacheFields = null, databaseMetadataCacheFieldsMib = 0] - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.PGObjectGetTest.getAsPGobjectSubtype[binary = REGULAR, sql = null::circle, type = class org.postgresql.geometric.PGcircle] - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.PGObjectSetTest.setNullAsPGobject[binary = REGULAR, sql = money, type = class org.postgresql.util.PGmoney] - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.DatabaseMetaDataTest.testGetUDT3[binary = FORCE] - unknown (unexpected)
		--- FAIL: org.postgresql.replication.LogicalReplicationStatusTest.testApplyLocationDoNotDependOnFlushLocation - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.PGObjectSetTest.setNullAsPGobjectSubtype[binary = REGULAR, sql = box, type = class org.postgresql.geometric.PGbox] - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.PGObjectGetTest.getAsString[binary = FORCE, sql = null::polygon, type = class org.postgresql.geometric.PGpolygon] - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.DatabaseMetaDataTest.testTables[binary = FORCE] - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.PGObjectGetTest.getAsString[binary = FORCE, sql = null::point, type = class org.postgresql.geometric.PGpoint] - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.ServerErrorTest.testForeignKeyConstraint - unknown (unexpected)
		--- FAIL: org.postgresql.replication.ReplicationConnectionTest.testConnectionNotValidWhenSessionTerminated - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.PGObjectSetTest.setNullAsPGobjectSubtype[binary = FORCE, sql = polygon, type = class org.postgresql.geometric.PGpolygon] - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.DatabaseMetaDataTest.testFuncWithDirection[binary = FORCE] - unknown (unexpected)
		--- FAIL: org.postgresql.replication.LogicalReplicationStatusTest.testFlushLocationEqualToSetLocation - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.PGObjectSetTest.setNullAsPGobjectSubtype[binary = FORCE, sql = circle, type = class org.postgresql.geometric.PGcircle] - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.ResultSetTest.testRowResultPositioning - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.PGObjectGetTest.getAsPGobject[binary = REGULAR, sql = null::circle, type = class org.postgresql.geometric.PGcircle] - unknown (unexpected)
		--- FAIL: org.postgresql.jdbc.ScramTest.[1] My Space - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.DatabaseMetaDataTest.testTypeInfoQuoting[binary = FORCE] - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.DatabaseMetaDataTest.testArrayTypeInfo[binary = FORCE] - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.ResultSetMetaDataTest.testSmallSerialSequenceLikeColumns[databaseMetadataCacheFields = null, databaseMetadataCacheFieldsMib = 0] - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.PGObjectGetTest.getAsPGobject[binary = FORCE, sql = null::lseg, type = class org.postgresql.geometric.PGlseg] - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc42.Jdbc42CallableStatementTest.testRegisterOutParameter - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.DatabaseMetaDataTest.testTypeInfoQuoting[binary = REGULAR] - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.PGObjectGetTest.getAsPGobject[binary = REGULAR, sql = null::lseg, type = class org.postgresql.geometric.PGlseg] - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.DatabaseMetaDataTest.testIndexInfoColumnOrder[binary = FORCE] - unknown (unexpected)
		--- FAIL: org.postgresql.replication.ReplicationSlotTest.testCreateTemporaryLogicalSlotPg10AndHigher - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.DatabaseMetaDataTest.testTypes[binary = FORCE] - unknown (unexpected)
		--- FAIL: org.postgresql.test.jdbc2.StatementTest.testCancelQueryWithBrokenNetwork - unknown (unexpected)
		For a full summary look at the pgjdbc artifacts 
		
		An updated blocklist (pgjdbcBlockList21_1) is available in the artifacts' pgjdbc log
```
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
# From https://go.crdb.dev/p/roachstress, perhaps edited lightly.
caffeinate ./roachstress.sh pgjdbc
```
</p>
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #63698 roachtest: pgjdbc failed [C-test-failure O-roachtest O-robot branch-release-20.2]
- #63680 roachtest: pgjdbc failed [C-test-failure O-roachtest O-robot branch-release-21.1]
</p>
</details>
/cc @cockroachdb/sql-experience
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*pgjdbc.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #64366: roachtest: hibernate failed
roachtest.hibernate [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2934234&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=2934234&tab=artifacts#/hibernate) on master @ [394543ab7bd9ff4be8acad9d1fdc892722032293](https://github.com/cockroachdb/cockroach/commits/394543ab7bd9ff4be8acad9d1fdc892722032293):

```
		--- FAIL: org.hibernate.jpa.test.packaging.PackagedEntityManagerTest.testExternalJar - unknown (unexpected)
		--- FAIL: org.hibernate.jpa.test.packaging.PackagedEntityManagerTest.testRelativeJarReferences - unknown (unexpected)
		--- FAIL: org.hibernate.test.annotations.entity.Java5FeaturesTest.testEnums - unknown (unexpected)
		--- FAIL: org.hibernate.test.bytecode.enhancement.lazy.proxy.inlinedirtychecking.ManyToOnePropertyAccessByFieldTest.testUpdate - unknown (unexpected)
		--- FAIL: org.hibernate.test.event.collection.association.bidirectional.onetomany.BidirectionalOneToManyBagSubclassCollectionEventTest.testUpdateParentOneChildToNoneByClear - unknown (unexpected)
		--- FAIL: org.hibernate.test.bytecode.enhancement.lazy.proxy.DeepInheritanceWithNonEntitiesProxyTest.testLeafGetValueInNonEntity - unknown (unexpected)
		--- FAIL: org.hibernate.test.naturalid.inheritance.cache.InheritedNaturalIdNoCacheTest.testLoadExtendedByNormal - unknown (unexpected)
		--- FAIL: org.hibernate.test.discriminator.SimpleInheritanceTest.testDiscriminatorSubclass - unknown (unexpected)
		--- FAIL: org.hibernate.jpa.test.query.QueryTest.testParameterCollectionSingletonParenthesesAndPositional - unknown (unexpected)
		--- FAIL: org.hibernate.test.event.collection.association.bidirectional.onetomany.BidirectionalOneToManyBagSubclassCollectionEventTest.testDeleteParentAndChild - unknown (unexpected)
		--- FAIL: org.hibernate.test.inheritance.TransientOverrideAsPersistentMappedSuperclass.testFindBySubclass - unknown (unexpected)
		--- FAIL: org.hibernate.jpa.test.packaging.PackagedEntityManagerTest.testORMFileOnMainAndExplicitJars - unknown (unexpected)
		--- FAIL: org.hibernate.test.event.collection.association.bidirectional.onetomany.BidirectionalOneToManyBagSubclassCollectionEventTest.testUpdateParentNullToOneChild - unknown (unexpected)
		--- FAIL: org.hibernate.test.event.collection.association.bidirectional.onetomany.BidirectionalOneToManyBagSubclassCollectionEventTest.testMoveCollectionToDifferentParent - unknown (unexpected)
		--- FAIL: org.hibernate.test.inheritance.discriminator.MultiSingleTableLoadTest.testFetchJoinLoadMultipleHoldersWithDifferentSubtypes - unknown (unexpected)
		--- FAIL: org.hibernate.test.annotations.access.jpa.AccessTest.testDefaultConfigurationModeIsInherited - unknown (unexpected)
		--- FAIL: org.hibernate.test.dynamicentity.tuplizer.TuplizerDynamicEntityTest.testIt - unknown (unexpected)
		--- FAIL: org.hibernate.test.event.collection.association.bidirectional.onetomany.BidirectionalOneToManyBagSubclassCollectionEventTest.testMoveChildToDifferentParent - unknown (unexpected)
		--- FAIL: org.hibernate.jpa.test.packaging.PackagedEntityManagerTest.testExcludeHbmPar - unknown (unexpected)
		--- FAIL: org.hibernate.test.annotations.access.jpa.AccessTest.testEmbeddableUsesAccessStrategyOfContainingClass - unknown (unexpected)
		--- FAIL: org.hibernate.test.hql.BulkManipulationTest.testUpdateWithSubquery - unknown (unexpected)
		--- FAIL: org.hibernate.test.legacy.FooBarTest.testVersioning - unknown (unexpected)
		--- FAIL: org.hibernate.jpa.test.transaction.CloseEntityManagerWithActiveTransactionTest.testUpdateThenCloseWithAnActiveTransaction - unknown (unexpected)
		--- FAIL: org.hibernate.test.event.collection.association.bidirectional.onetomany.BidirectionalOneToManyBagSubclassCollectionEventTest.testDeleteParentWithNoChildren - unknown (unexpected)
		--- FAIL: org.hibernate.test.event.collection.association.bidirectional.onetomany.BidirectionalOneToManyBagSubclassCollectionEventTest.testUpdateParentTwoChildrenToOne - unknown (unexpected)
		--- FAIL: org.hibernate.test.annotations.access.AccessTest.testNonOverridenSubclass - unknown (unexpected)
		--- FAIL: org.hibernate.jpa.test.packaging.PackagedEntityManagerTest.testExtendedEntityManager - unknown (unexpected)
		--- FAIL: org.hibernate.test.event.collection.association.bidirectional.onetomany.BidirectionalOneToManyBagSubclassCollectionEventTest.testMoveAllChildrenToDifferentParent - unknown (unexpected)
		--- FAIL: org.hibernate.test.event.collection.association.bidirectional.onetomany.BidirectionalOneToManyBagSubclassCollectionEventTest.testSaveParentEmptyChildren - unknown (unexpected)
		--- FAIL: org.hibernate.test.annotations.onetomany.OrderByTest.testOrderByNoElement - unknown (unexpected)
		--- FAIL: org.hibernate.test.where.annotations.EagerManyToOneFetchModeSelectWhereTest.testAssociatedWhereClause - unknown (unexpected)
		--- FAIL: org.hibernate.test.annotations.access.jpa.AccessTest.testOverridenSubclass - unknown (unexpected)
		--- FAIL: org.hibernate.test.event.collection.association.bidirectional.onetomany.BidirectionalOneToManyBagSubclassCollectionEventTest.testUpdateParentOneToTwoSameChildren - unknown (unexpected)
		--- FAIL: org.hibernate.test.joinedsubclass.JoinedSubclassTest.testLockingJoinedSubclass - unknown (unexpected)
		--- FAIL: org.hibernate.test.bytecode.enhancement.lazy.proxy.DeepInheritanceWithNonEntitiesProxyTest.testLeafSetValueInNonEntity - unknown (unexpected)
		--- FAIL: org.hibernate.test.event.collection.association.bidirectional.onetomany.BidirectionalOneToManyBagSubclassCollectionEventTest.testMoveCollectionToDifferentParentFlushMoveToDifferentParent - unknown (unexpected)
		--- FAIL: org.hibernate.test.event.collection.association.bidirectional.onetomany.BidirectionalOneToManyBagSubclassCollectionEventTest.testUpdateParentOneChildDiffCollectionSameChild - unknown (unexpected)
		--- FAIL: org.hibernate.jpa.test.packaging.PackagedEntityManagerTest.testListenersDefaultPar - unknown (unexpected)
		--- FAIL: org.hibernate.test.inheritance.TransientOverrideAsPersistentSingleTable.testFindBySubclass - unknown (unexpected)
		--- FAIL: org.hibernate.test.dynamicentity.tuplizer2.ImprovedTuplizerDynamicEntityTest.testIt - unknown (unexpected)
		--- FAIL: org.hibernate.jpa.test.packaging.PackagedEntityManagerTest.testDefaultParForPersistence_1_0 - unknown (unexpected)
		--- FAIL: org.hibernate.test.event.collection.association.bidirectional.onetomany.BidirectionalOneToManyBagSubclassCollectionEventTest.testDeleteParentButNotChild - unknown (unexpected)
		--- FAIL: org.hibernate.jpa.test.graphs.FetchGraphTest.testCollectionEntityGraph - unknown (unexpected)
		--- FAIL: org.hibernate.test.annotations.access.jpa.AccessTest.testNonOverridenSubclass - unknown (unexpected)
		--- FAIL: org.hibernate.test.annotations.id.IdTest.testIdClass - unknown (unexpected)
		--- FAIL: org.hibernate.test.jpa.compliance.tck2_2.caching.InheritedCacheableTest.testOnlySubclassIsCached - unknown (unexpected)
		--- FAIL: org.hibernate.test.event.collection.association.bidirectional.onetomany.BidirectionalOneToManyBagSubclassCollectionEventTest.testDeleteParentWithNullChildren - unknown (unexpected)
		For a full summary look at the hibernate artifacts 
		
		An updated blocklist (hibernateBlockList21_1) is available in the artifacts' hibernate log
```
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
# From https://go.crdb.dev/p/roachstress, perhaps edited lightly.
caffeinate ./roachstress.sh hibernate
```
</p>
</p>
</details>
/cc @cockroachdb/sql-experience
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*hibernate.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #64524: roachtest: gopg failed
roachtest.gopg [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2944550&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=2944550&tab=artifacts#/gopg) on master @ [684e753c15f3fc58df79b6ea70e7b6715eae4835](https://github.com/cockroachdb/cockroach/commits/684e753c15f3fc58df79b6ea70e7b6715eae4835):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/gopg/run_1
	gopg.go:91,gopg.go:154,test_runner.go:777: No gopg blocklist defined for cockroach version v21.2.0-alpha.00000000-135-g684e753c15
```
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
# From https://go.crdb.dev/p/roachstress, perhaps edited lightly.
caffeinate ./roachstress.sh gopg
```
</p>
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #64105 roachtest: gopg failed [C-test-failure O-roachtest O-robot branch-release-20.1]
</p>
</details>
/cc @cockroachdb/sql-experience
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*gopg.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #64526: roachtest: gorm failed
roachtest.gorm [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2944550&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=2944550&tab=artifacts#/gorm) on master @ [684e753c15f3fc58df79b6ea70e7b6715eae4835](https://github.com/cockroachdb/cockroach/commits/684e753c15f3fc58df79b6ea70e7b6715eae4835):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/gorm/run_1
	gorm.go:91,test_runner.go:777: No gorm blocklist defined for cockroach version v21.2.0-alpha.00000000-135-g684e753c15
```
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
# From https://go.crdb.dev/p/roachstress, perhaps edited lightly.
caffeinate ./roachstress.sh gorm
```
</p>
</p>
</details>
/cc @cockroachdb/sql-experience
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*gorm.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #64529: roachtest: hibernate-spatial failed
roachtest.hibernate-spatial [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2944550&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=2944550&tab=artifacts#/hibernate-spatial) on master @ [684e753c15f3fc58df79b6ea70e7b6715eae4835](https://github.com/cockroachdb/cockroach/commits/684e753c15f3fc58df79b6ea70e7b6715eae4835):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/hibernate-spatial/run_1
	hibernate.go:170,hibernate.go:235,test_runner.go:777: No hibernate blocklist defined for cockroach version v21.2.0-alpha.00000000-135-g684e753c15
```
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
# From https://go.crdb.dev/p/roachstress, perhaps edited lightly.
caffeinate ./roachstress.sh hibernate-spatial
```
</p>
</p>
</details>
/cc @cockroachdb/sql-experience
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*hibernate-spatial.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #64532: roachtest: lib/pq failed
roachtest.lib/pq [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2944550&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=2944550&tab=artifacts#/lib/pq) on master @ [684e753c15f3fc58df79b6ea70e7b6715eae4835](https://github.com/cockroachdb/cockroach/commits/684e753c15f3fc58df79b6ea70e7b6715eae4835):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/lib/pq/run_1
	libpq.go:88,test_runner.go:777: No lib/pq blocklist defined for cockroach version v21.2.0-alpha.00000000-135-g684e753c15
```
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
# From https://go.crdb.dev/p/roachstress, perhaps edited lightly.
caffeinate ./roachstress.sh lib/pq
```
</p>
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #62856 roachtest: lib/pq failed [C-test-failure O-roachtest O-robot branch-release-21.1]
- #54338 roachtest: lib/pq failed [C-test-failure O-roachtest O-robot branch-release-20.1]
</p>
</details>
/cc @cockroachdb/sql-experience
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*lib/pq.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #64534: roachtest: psycopg failed
roachtest.psycopg [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2944550&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=2944550&tab=artifacts#/psycopg) on master @ [684e753c15f3fc58df79b6ea70e7b6715eae4835](https://github.com/cockroachdb/cockroach/commits/684e753c15f3fc58df79b6ea70e7b6715eae4835):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/psycopg/run_1
	psycopg.go:98,psycopg.go:137,test_runner.go:777: No psycopg blocklist defined for cockroach version v21.2.0-alpha.00000000-135-g684e753c15
```
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
# From https://go.crdb.dev/p/roachstress, perhaps edited lightly.
caffeinate ./roachstress.sh psycopg
```
</p>
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #64196 roachtest: psycopg failed [C-test-failure O-roachtest O-robot branch-release-21.1]
</p>
</details>
/cc @cockroachdb/sql-experience
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*psycopg.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #64535: roachtest: pgx failed
roachtest.pgx [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2944550&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=2944550&tab=artifacts#/pgx) on master @ [684e753c15f3fc58df79b6ea70e7b6715eae4835](https://github.com/cockroachdb/cockroach/commits/684e753c15f3fc58df79b6ea70e7b6715eae4835):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/pgx/run_1
	pgx.go:82,pgx.go:133,test_runner.go:777: No pgx blocklist defined for cockroach version v21.2.0-alpha.00000000-135-g684e753c15
```
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
# From https://go.crdb.dev/p/roachstress, perhaps edited lightly.
caffeinate ./roachstress.sh pgx
```
</p>
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #64113 roachtest: pgx failed [C-test-failure O-roachtest O-robot branch-release-20.1]
</p>
</details>
/cc @cockroachdb/sql-experience
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*pgx.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #64538: roachtest: sqlalchemy failed
roachtest.sqlalchemy [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2944550&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=2944550&tab=artifacts#/sqlalchemy) on master @ [684e753c15f3fc58df79b6ea70e7b6715eae4835](https://github.com/cockroachdb/cockroach/commits/684e753c15f3fc58df79b6ea70e7b6715eae4835):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/sqlalchemy/run_1
	sqlalchemy.go:148,sqlalchemy.go:38,test_runner.go:777: No sqlalchemy blocklist defined for cockroach version v21.2.0-alpha.00000000-135-g684e753c15
```
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
# From https://go.crdb.dev/p/roachstress, perhaps edited lightly.
caffeinate ./roachstress.sh sqlalchemy
```
</p>
</p>
</details>
/cc @cockroachdb/sql-experience
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlalchemy.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/64538
fixes https://github.com/cockroachdb/cockroach/issues/64535
fixes https://github.com/cockroachdb/cockroach/issues/64534
fixes https://github.com/cockroachdb/cockroach/issues/64532
fixes https://github.com/cockroachdb/cockroach/issues/64529
fixes https://github.com/cockroachdb/cockroach/issues/64526
fixes https://github.com/cockroachdb/cockroach/issues/64524
fixes https://github.com/cockroachdb/cockroach/issues/64366
fixes https://github.com/cockroachdb/cockroach/issues/64301

Release note: None

### CODE REVIEW

**Review by RichardJCai — APPROVED** [review]
Awesome thanks for cleaning this up!

**Comment by rafiss** [comment]
tftr!

bors r=RichardJCai

**Comment by rafiss** [comment]
ah wait, gotta fix the hibernate one

bors r-

**Comment by rafiss** [comment]
bors r=RichardJCai

**Pull request merged**
