### PR TITLE
storage/bulk: push buffer-sort down to BulkAdder

### PR DESCRIPTION
**Pull request by dt**
This pushes the buffering and sorting of out-of-order keys down to the
BulkAdder. This pattern is common everywhere we produce out-of-order KVs
that we want to ingest in bulk -- we need to sort them, both for the
ordering property of SSTs but also for grouping.

Evidence suggests that changes in buffering and splitting could lead to
significant changes in overall ingest performance -- buffering more or
even just buffering/splitting smarter affects the spans of produced SSTs
which in turn directly affects how expensive overall ingestion is -- due
to both some cockroach-specific factors like stats recomputation as well
as other factors like compaction-derived write-amplification.

While I'm here: Embedding `backfiller` in the `chunkbackfiller`
implementations, and in turn embedding `chunkbackfiller` in `backfiller`
created a loop, whereby a stuct with no methods could implement
`chunkbackfiller` (leading to a NPE at runtime?).

Release note: none.

### CODE REVIEW

**Comment by dt** [comment]
@vivekmenezes I think this subsumes #35855: inspired by your change, I moved the adder out so it is reused across chunks, except it still has the option to choose to flush as it goes if it needs to to maintain bounded memory.

**Review by vivekmenezes — APPROVED** [review]
> Reviewed 9 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36192)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lucy-zhang, and @vivekmenezes)

___
*[pkg/ccl/importccl/read_import_proc.go, line 652 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-Lb43s6V-O0FUFs2NL4a:-Lb43s6V-O0FUFs2NL4b:bmyzvx1) ([raw file](https://github.com/cockroachdb/cockroach/blob/843876485ac25139e9afa0f42dd5f828e5bab4b3/pkg/ccl/importccl/read_import_proc.go#L652)):*
> ```Go
> 	sizeByTableIDIndexID := make(map[string]int64)
> 
> 	flush := func(ctx context.Context, buf roachpb.KeyValueByKey) error {
> ```

s/flush/add
___
*[pkg/ccl/importccl/read_import_proc.go, line 659 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-Lb43MyX26_WE9_Ql-yP:-Lb43MyX26_WE9_Ql-yQ:bk87vnu) ([raw file](https://github.com/cockroachdb/cockroach/blob/843876485ac25139e9afa0f42dd5f828e5bab4b3/pkg/ccl/importccl/read_import_proc.go#L659)):*
> ```Go
> 			if err := adder.Add(ctx, buf[i].Key, buf[i].Value.RawBytes); err != nil {
> 				if _, ok := err.(storagebase.DuplicateKeyError); ok {
> 					return pgerror.Wrap(err, pgerror.CodeDataExceptionError, "duplicate key")
> ```

"duplicate key" is already a part of the message
___
*[pkg/ccl/importccl/read_import_proc.go, line 701 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-Lb43jxv4WN-ERAMHnbw:-Lb43jxv4WN-ERAMHnbx:bb7od0r) ([raw file](https://github.com/cockroachdb/cockroach/blob/843876485ac25139e9afa0f42dd5f828e5bab4b3/pkg/ccl/importccl/read_import_proc.go#L701)):*
> ```Go
> 	if err := adder.Flush(ctx); err != nil {
> 		if err, ok := err.(storagebase.DuplicateKeyError); ok {
> 			return pgerror.Wrap(err, pgerror.CodeDataExceptionError, "duplicate key")
> ```

same
___
*[pkg/sql/schema_changer_test.go, line 1519 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-Lb44OhU0Xa7Adh1ZTVu:-Lb44OhU0Xa7Adh1ZTVv:b362bg9) ([raw file](https://github.com/cockroachdb/cockroach/blob/843876485ac25139e9afa0f42dd5f828e5bab4b3/pkg/sql/schema_changer_test.go#L1519)):*
> ```Go
> 				return nil
> 			},
> 			// a non-nil RunAfterBackfillChunk fn will trigger flushing every chunk.
> ```

hard to see why?
___
*[pkg/sql/distsqlrun/backfiller.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-Lb44e12029tuy5cvRSp:-Lb44e12029tuy5cvRSq:b-8ebwfv) ([raw file](https://github.com/cockroachdb/cockroach/blob/843876485ac25139e9afa0f42dd5f828e5bab4b3/pkg/sql/distsqlrun/backfiller.go#L48)):*
> ```Go
> 	) (roachpb.Key, error)
> 
> 	prepare(ctx context.Context) error
> ```

// Call prepare() before runChunk()
___
*[pkg/sql/distsqlrun/backfiller.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-Lb44hFa8_sAb-UguNZ0:-Lb44hFa8_sAb-UguNZ1:bcek4dz) ([raw file](https://github.com/cockroachdb/cockroach/blob/843876485ac25139e9afa0f42dd5f828e5bab4b3/pkg/sql/distsqlrun/backfiller.go#L49)):*
> ```Go
> 
> 	prepare(ctx context.Context) error
> 	flush(ctx context.Context) error
> ```

// perhaps we should call flush(), done()
___
*[pkg/sql/distsqlrun/indexbackfiller.go, line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-Lb45t3D0eZZNVlY7Ct0:-Lb45t3D0eZZNVlY7Ct1:b-7m74ox) ([raw file](https://github.com/cockroachdb/cockroach/blob/843876485ac25139e9afa0f42dd5f828e5bab4b3/pkg/sql/distsqlrun/indexbackfiller.go#L93)):*
> ```Go
> }
> 
> func (ib *indexBackfiller) wrapDupError(ctx context.Context, orig error) error {
> ```

nice!
___
*[pkg/sql/distsqlrun/indexbackfiller.go, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-Lb45huW3jTpCqLW57rZ:-Lb45huW3jTpCqLW57r_:bd8d7u9) ([raw file](https://github.com/cockroachdb/cockroach/blob/843876485ac25139e9afa0f42dd5f828e5bab4b3/pkg/sql/distsqlrun/indexbackfiller.go#L107)):*
> ```Go
> 		return err
> 	}
> 	v := &roachpb.Value{RawBytes: typed.Value}
> ```

why do we need this?
___
*[pkg/sql/distsqlrun/indexbackfiller.go, line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-Lb46Fv085K1nQWPl_Jk:-Lb46Fv085K1nQWPl_Jl:b-10yo0m) ([raw file](https://github.com/cockroachdb/cockroach/blob/843876485ac25139e9afa0f42dd5f828e5bab4b3/pkg/sql/distsqlrun/indexbackfiller.go#L176)):*
> ```Go
> 			}
> 		}
> 		if ib.flowCtx.testingKnobs.RunAfterBackfillChunk != nil {
> ```

It probably would be better to move this code to where we call RunAfterBackfillChunk
___
*[pkg/storage/bulk/buffering_adder.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-Lb471IHA5--1ey9vV0E:-Lb471IHA5--1ey9vV0F:b-b1dtt3) ([raw file](https://github.com/cockroachdb/cockroach/blob/843876485ac25139e9afa0f42dd5f828e5bab4b3/pkg/storage/bulk/buffering_adder.go#L35)):*
> ```Go
> type BufferingAdder struct {
> 	SSTBatcher
> 	timestamp      hlc.Timestamp
> ```

// Ingest data with this timestamp
___
*[pkg/storage/bulk/buffering_adder.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-Lb475IM6B1MXJOdwAMM:-Lb475IM6B1MXJOdwAMN:b-kct6u4) ([raw file](https://github.com/cockroachdb/cockroach/blob/843876485ac25139e9afa0f42dd5f828e5bab4b3/pkg/storage/bulk/buffering_adder.go#L36)):*
> ```Go
> 	SSTBatcher
> 	timestamp      hlc.Timestamp
> 	skipDuplicates bool
> ```

ignore duplicates. This is useful when ingesting inverted indexes.
___
*[pkg/storage/bulk/buffering_adder.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-Lb47CjT3SN4Z3PEO4Bd:-Lb47CjT3SN4Z3PEO4Be:b9wh2vf) ([raw file](https://github.com/cockroachdb/cockroach/blob/843876485ac25139e9afa0f42dd5f828e5bab4b3/pkg/storage/bulk/buffering_adder.go#L38)):*
> ```Go
> 	skipDuplicates bool
> 
> 	flushSize int64
> ```

// flush once this threshold is reached
___
*[pkg/storage/bulk/buffering_adder.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-Lb47VG5CqeNhrIsDrO9:-Lb47VG5CqeNhrIsDrOA:bv0x1uc) ([raw file](https://github.com/cockroachdb/cockroach/blob/843876485ac25139e9afa0f42dd5f828e5bab4b3/pkg/storage/bulk/buffering_adder.go#L46)):*
> ```Go
> }
> 
> const kvOverhead = 24 + 24 // 2 slice headers, each assuming each is 8 + 8 + 8.
> ```

can we derive this? you also move it to where it is being used.
___
*[pkg/storage/bulk/buffering_adder.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-Lb4A8nm34_-8S_oefSq:-Lb4A8nm34_-8S_oefSr:b-yuex9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/843876485ac25139e9afa0f42dd5f828e5bab4b3/pkg/storage/bulk/buffering_adder.go#L71)):*
> ```Go
> // Add adds a key to the buffer and checks if it needs to flush.
> func (b *BufferingAdder) Add(ctx context.Context, key roachpb.Key, value []byte) error {
> 	if len(b.curBuf) == 0 {
> ```

if b.curBufSize == 0 

you can also set b.curBuf = b.curBuf[:0] here
___
*[pkg/storage/bulk/buffering_adder.go, line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-Lb49zvlAXYOeG4fdbnh:-Lb49zvmBu7mcgUcfyY3:b-aokyi6) ([raw file](https://github.com/cockroachdb/cockroach/blob/843876485ac25139e9afa0f42dd5f828e5bab4b3/pkg/storage/bulk/buffering_adder.go#L87)):*
> ```Go
> // Flush flushes any buffered kvs to the batcher.
> func (b *BufferingAdder) Flush(ctx context.Context) error {
> 	if len(b.curBuf) == 0 {
> ```

if b.curBufSize == 0
___
*[pkg/storage/bulk/buffering_adder.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-Lb4A4XF30BDXD1fU4OU:-Lb4A4XF30BDXD1fU4OV:b-3ldbp7) ([raw file](https://github.com/cockroachdb/cockroach/blob/843876485ac25139e9afa0f42dd5f828e5bab4b3/pkg/storage/bulk/buffering_adder.go#L104)):*
> ```Go
> 	}
> 	b.curBufSize = 0
> 	b.curBuf = b.curBuf[:0]
> ```

reset it above when you call Add()

**Review by dt — COMMENTED** [review]
added some flush reason counting/logging to this RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-:-Lb4wPzR9led4cSCdv-o:b-j5uof4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lucy-zhang, and @vivekmenezes)

___
*[pkg/ccl/importccl/read_import_proc.go, line 652 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-Lb43s6V-O0FUFs2NL4a:-Lb4dJBQAgCACFPTkeP-:b-j32iky) ([raw file](https://github.com/cockroachdb/cockroach/blob/843876485ac25139e9afa0f42dd5f828e5bab4b3/pkg/ccl/importccl/read_import_proc.go#L652)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

s/flush/add
</blockquote></details>

it is still "flushing" a bucket -- this is experimental import and it currently has per-table/index buffering and those buffers are "flushed" both before and after this change -- the main difference is now that they 
___
*[pkg/ccl/importccl/read_import_proc.go, line 659 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-Lb43MyX26_WE9_Ql-yP:-Lb4m79E7QPEgmGISKUU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/843876485ac25139e9afa0f42dd5f828e5bab4b3/pkg/ccl/importccl/read_import_proc.go#L659)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

"duplicate key" is already a part of the message
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/read_import_proc.go, line 701 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-Lb43jxv4WN-ERAMHnbw:-Lb4m7Y1A1DeWstqz2W5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/843876485ac25139e9afa0f42dd5f828e5bab4b3/pkg/ccl/importccl/read_import_proc.go#L701)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[pkg/sql/schema_changer_test.go, line 1519 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-Lb44OhU0Xa7Adh1ZTVu:-Lb4wKXrBGb9ZRr3Ilzv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/843876485ac25139e9afa0f42dd5f828e5bab4b3/pkg/sql/schema_changer_test.go#L1519)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

hard to see why?
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/backfiller.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-Lb44e12029tuy5cvRSp:-Lb4lFaB9osUW1wYLpSr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/843876485ac25139e9afa0f42dd5f828e5bab4b3/pkg/sql/distsqlrun/backfiller.go#L48)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

// Call prepare() before runChunk()
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/backfiller.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-Lb44hFa8_sAb-UguNZ0:-Lb4kR6KE33BnosATV-A:b-qcdxod) ([raw file](https://github.com/cockroachdb/cockroach/blob/843876485ac25139e9afa0f42dd5f828e5bab4b3/pkg/sql/distsqlrun/backfiller.go#L49)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

// perhaps we should call flush(), done()
</blockquote></details>

eh, we can call it any time so it isn't quite `done` -- i.e. we call it to make work visible to tests.
___
*[pkg/sql/distsqlrun/indexbackfiller.go, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-Lb45huW3jTpCqLW57rZ:-Lb4e-fBBM2wYGY2JFgE:b1axl21) ([raw file](https://github.com/cockroachdb/cockroach/blob/843876485ac25139e9afa0f42dd5f828e5bab4b3/pkg/sql/distsqlrun/indexbackfiller.go#L107)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

why do we need this?
</blockquote></details>

The uniqueness error generator wants the value for its error.
___
*[pkg/sql/distsqlrun/indexbackfiller.go, line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-Lb46Fv085K1nQWPl_Jk:-Lb4eFSC6lu-IgmxIBwC:betm5wa) ([raw file](https://github.com/cockroachdb/cockroach/blob/843876485ac25139e9afa0f42dd5f828e5bab4b3/pkg/sql/distsqlrun/indexbackfiller.go#L176)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

It probably would be better to move this code to where we call RunAfterBackfillChunk
</blockquote></details>

we defer it, but we don't actually want to defer this code i.e. this code should not be run on every early return. 
___
*[pkg/storage/bulk/buffering_adder.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-Lb47VG5CqeNhrIsDrO9:-Lb4jANR0Q9tSlyiUYmE:b-tkk86j) ([raw file](https://github.com/cockroachdb/cockroach/blob/843876485ac25139e9afa0f42dd5f828e5bab4b3/pkg/storage/bulk/buffering_adder.go#L46)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

can we derive this? you also move it to where it is being used.
</blockquote></details>

not without importing unsafe -- I'm fine with it being a hardcoded estimate.
___
*[pkg/storage/bulk/buffering_adder.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-Lb4A8nm34_-8S_oefSq:-Lb4fxWnDZ85QdkM0hsx:bm5gwbx) ([raw file](https://github.com/cockroachdb/cockroach/blob/843876485ac25139e9afa0f42dd5f828e5bab4b3/pkg/storage/bulk/buffering_adder.go#L71)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

if b.curBufSize == 0 

you can also set b.curBuf = b.curBuf[:0] here
</blockquote></details>

eh, I'm not sure I prefer that: `curBufSize` is used _estimate_ memory usage of `curBuf` so we can decide if we want to call `Flush` to keep it bounded.  Decisions made based on whether or not we have things actually buffered should be made by looking at if we actually have a non-empty buffer, imo.
___
*[pkg/storage/bulk/buffering_adder.go, line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-Lb49zvlAXYOeG4fdbnh:-Lb4eYjcAI3ZcH7bXABd:b-t2r7ia) ([raw file](https://github.com/cockroachdb/cockroach/blob/843876485ac25139e9afa0f42dd5f828e5bab4b3/pkg/storage/bulk/buffering_adder.go#L87)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

if b.curBufSize == 0
</blockquote></details>

ditto above: I think looking at the actual buffer to decide if there's buffered things to flush is the right answer here.
___
*[pkg/storage/bulk/buffering_adder.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-Lb4A4XF30BDXD1fU4OU:-Lb4guep4B6jLF8zLH8q:b-y0d6x5) ([raw file](https://github.com/cockroachdb/cockroach/blob/843876485ac25139e9afa0f42dd5f828e5bab4b3/pkg/storage/bulk/buffering_adder.go#L104)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

reset it above when you call Add()
</blockquote></details>

Eh? once we've flushed things seems like the right time to stop holding them in a buffer? why wait?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36192)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lucy-zhang, and @vivekmenezes)

___
*[pkg/storage/bulk/buffering_adder.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-Lb471IHA5--1ey9vV0E:-Lb54gHQ35vr0X3muOeI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/843876485ac25139e9afa0f42dd5f828e5bab4b3/pkg/storage/bulk/buffering_adder.go#L35)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

// Ingest data with this timestamp
</blockquote></details>

Done.
___
*[pkg/storage/bulk/buffering_adder.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-Lb475IM6B1MXJOdwAMM:-Lb54hKP6OlrfrhKY4Tx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/843876485ac25139e9afa0f42dd5f828e5bab4b3/pkg/storage/bulk/buffering_adder.go#L36)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

ignore duplicates. This is useful when ingesting inverted indexes.
</blockquote></details>

Done.
___
*[pkg/storage/bulk/buffering_adder.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-Lb47CjT3SN4Z3PEO4Bd:-Lb54j5b4LZhLfYJV8vG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/843876485ac25139e9afa0f42dd5f828e5bab4b3/pkg/storage/bulk/buffering_adder.go#L38)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

// flush once this threshold is reached
</blockquote></details>

Done.

**Comment by vivekmenezes** [comment]
Lgtm

**Review by vivekmenezes — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36192#-:-Lb9707G2_fmYZM8yDEv:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lucy-zhang and @vivekmenezes)

**Comment by dt** [comment]
@lucy-zhang I reproduced <1mb SSTs pretty trivially with this once my index started splitting into ranges. The 32mb buffer worked out to ~24mb of sst that, once the index split ~10 ways and then evetually 25 ways, easily explained the small chunks. Upping the default buffer size (with a setting to turn it back down if needed) should help with that I think.

**Comment by vivekmenezes** [comment]
nice work on this PR @dt

**Pull request merged**
