### PR TITLE
sql: remove the broken support for BIT

### LINKED ISSUE #20991: sql: BIT(n) and BIT VARYING(n) columns do not match PostgreSQL behaviour
When creating a column `BIT(n)` where n is the size limit of the bit string as a property of the column type, values can only be inserted in CockroachDB if the value is _strictly_ less than the limit. In PostgreSQL, values can only be inserted if the value is of _equal_ length to the limit, i.e. greater than `2^n-1` and smaller than `2^n + 1`. Varying bit strings allow any bit string smaller than `2^n + 1`.

```sql
root@:26257/test> CREATE TABLE bit_strings (a_bit BIT(8));
CREATE TABLE

Time: 3.219933ms

# A bit string of equal length fails.
root@:26257/test> INSERT INTO bit_strings (a_bit) VALUES ('00001010');
pq: integer out of range for type BIT (column "a_bit")

# But bit strings of smaller length succeed.
root@:26257/test> INSERT INTO bit_strings (a_bit) VALUES ('0000101');
INSERT 1

Time: 1.180875ms

```

Expected:

```sql
postgres=# CREATE TABLE bit_strings (a_bit BIT(8));
CREATE TABLE
postgres=# INSERT INTO bit_strings (a_bit) VALUES ('00001010');
INSERT 0 1
postgres=# SELECT * FROM bit_strings;
  a_bit
----------
 00001010
(1 row)
```

### PR DESCRIPTION
**Pull request by knz**
Part of #28690.

This is a prior PR to #28807. I foresee that the other PR will need some iteration (and perhaps some consensus gathering) and may merge later in the 2.2 cycle. In the meantime we need to remove the brokenness from client apps. This PR disables the BIT type (in a backward-compatible manner!) until we can actually address #20991.

-----

Previously CockroachDB was handling the keyword BIT as an alias for
INT (specifically: INT with a "visible type" of BIT). With regards to
storing values, performing arithmetic, comparisons, etc, "BIT" values
were considered just integers.

In the PostgreSQL dialect however, bit arrays are a completely
different thing: they are arbitrary long strings of bits, possibly
longer (or shorter) than 64 bits, with odd number of bits, etc. They
use different literal formats, have different semantics for arithmetic
and concatenation, etc.

Unfortunately, this mismatch confuses clients that either want to use
the pg BIT semantics, or do introspection (e.g. ORMs).

To prevent this confusion, this patch removes the broken support for
BIT until proper support is actually introduced. Now clients that
attempt to use the BIT keyword will see an unimplemented feature error
linking back to issue #20991. As uninmplemented errors are also
reported, we will be able to track demand for it.

Release note (backward-incompatible change): CockroachDB previously
included some preliminary support for the data type
"BIT". Unfortunately this functionality was both incorrectly
implemented and was found to cause incompatibility with client
apps. It is thus removed; it will be replaced by a
PostgreSQL-compatible replacement at a later time.

Release note (sql change): Tables columns created prior to this patch
with the type name "BIT" will continue to work but will see their type
automatically changed to INT in the output of SHOW TABLES,
`information_schema`, etc. This is backward-compatible insofar that
the previous BIT type in CockroachDB was actually a simple
integer. Only the name of the type of these columns changes; their
values are unaffected and can continue to be used in queries without
visible changes to query results in client apps which actually
utilized the incorrect pre-2.1 BIT semantics.

### CODE REVIEW

**Comment by knz** [comment]
rebased to fix the merge conflicts

**Review by BramGruneir — APPROVED** [review]
:lgtm:

How about adding a test that produces the error?

> Reviewed 1 of 1 files at r1, 42 of 42 files at r2, 21 of 21 files at r3, 11 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28814#-:-LKNuGPo1gwUNfI51T6n:b3359tq)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by knz — COMMENTED** [review]
> How about adding a test that produces the error?

Sounds like a plan! Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28814#-:-LKO378h5OLkFiLqSQJL:bfk3heu)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by BramGruneir — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28814)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
