### PR TITLE
roachtest: enable READ COMMITTED for ORM tests

### LINKED ISSUE #115203: roachtest: run 3rd party ORM test suites under weak isolation levels
We run a collection of 3rd party ORM test suites. We can use them to get useful coverage of Read Committed and Snapshot isolation by running them with these isolation levels configured as the default.

### PR DESCRIPTION
**Pull request by rafiss**
### sql: make autocommit_before_ddl apply to Parse cmd

The pgwire Parse command is used to prepare a statement. If it is
preparing a DDL statement, then we should autocommit before preparing it
if autocommit_before_ddl is on. Otherwise, the autocommit would occur
later when the prepared statement is being executed, which is too late.

---

fixes https://github.com/cockroachdb/cockroach/issues/115203
Release note: None

### CODE REVIEW

**Comment by rafiss** [comment]
testing here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13805936?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true

**Comment by rafiss** [comment]
a second run: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13807034?hideProblemsFromDependencies=false&hideTestsFromDependencies=false

**Comment by rafiss** [comment]
another run: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/15090898?hideProblemsFromDependencies=false&hideTestsFromDependencies=false

this one has a fix for autocommit_before_ddl for prepared statements, which is included in this PR too.

**Review by fqazi — APPROVED** [review]
Nice! :lgtm:

> Reviewed 4 of 4 files at r1, 3 of 3 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118641#-:-NxJ0uV07CT6w2V3Dtol:bfd61q5)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @rafiss, and @srosenberg)

___
*[`pkg/sql/sem/tree/stmt.go` line 152 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118641#-NxJ0riK-lAFeLlBU-DW:-NxJ0riK-lAFeLlBU-DX:b-we97ir) ([raw file](https://github.com/cockroachdb/cockroach/blob/8207fcf2b92784e09f489a6c5f04bc0ce13aa073/pkg/sql/sem/tree/stmt.go#L152)):*
> ```Go
> // the database schema.
> func CanModifySchema(stmt Statement) bool {
> 	if stmt == nil {
> ```

Surprised we didn't run into this before?

**Comment by rafiss** [comment]
tftr!

bors r+

**Pull request merged**
