### PR TITLE
kv: don't start a second heartbeat loop after retriable errors

### PR DESCRIPTION
**Pull request by andreimatei**
Before this patch, we used to start a txn's heartbeat loop whenever the
TCS sees a BeginTxn. That wasn't good enough: we send BeginTxn's again
after transaction restart errors because we conservatively protect
against the transaction record not having been written. So, we were
starting multiple heartbeat loops, which is no good (for one, we're only
shutting down the last started loop when the transaction finishes).
This patch makes sure we don't start a second loop.

Release note: None

### CODE REVIEW

**Review by bdarnell — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27973)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/kv/txn_coord_sender.go, line 942 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27973#-LINvx1sEgz9ddP_5ZHC:-LINvx1sEgz9ddP_5ZHD:b-foilde) ([raw file](https://github.com/cockroachdb/cockroach/blob/39bbee13ac0ab2021cb7c1d1d724d67fc3c67905/pkg/kv/txn_coord_sender.go#L942)):*
> ```Go
> 	// Create a new context so that the heartbeat loop doesn't inherit the
> 	// caller's cancelation.
> 	// We want the loop to run in a span linked to the current one, though, so we
> ```

Are you sure about this? I don't know that the context of the goroutine that caused this one to be started is guaranteed to live long enough. For the cherry-pick, I think I'd rather just add the check for tc.mu.txnEnd instead of touching contexts (unless it's necessary for some non-obvious reason)

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27973)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/kv/txn_coord_sender.go, line 942 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27973#-LINvx1sEgz9ddP_5ZHC:-LINxcIaArKnGxvHIQ55:b-45a1wa) ([raw file](https://github.com/cockroachdb/cockroach/blob/39bbee13ac0ab2021cb7c1d1d724d67fc3c67905/pkg/kv/txn_coord_sender.go#L942)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Are you sure about this? I don't know that the context of the goroutine that caused this one to be started is guaranteed to live long enough. For the cherry-pick, I think I'd rather just add the check for tc.mu.txnEnd instead of touching contexts (unless it's necessary for some non-obvious reason)
</blockquote></details>

The lifetime of the parent ctx/span doesn't matter. The relationship between the span created by `RunAsyncTask` and the parent span is `FollowsFrom`, which doesn't imply anything about the respective lifetimes. What the relationship between the spans does do, however, is that it makes the child be part of the "recording" of the parent - which is how I get the hb trace in the new test. For recording purposes, the lifetime of the spans involved also doesn't matter - you can get a (possibly partial) recording while some of the spans are still live.

But anyway, that's why this is a different commit. We don't have to cherry-pick.

**Review by tbg — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27973)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/kv/txn_coord_sender.go, line 942 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27973#-LINvx1sEgz9ddP_5ZHC:-LIX6pHIAlbImrEWCDXf:be2fuyy) ([raw file](https://github.com/cockroachdb/cockroach/blob/39bbee13ac0ab2021cb7c1d1d724d67fc3c67905/pkg/kv/txn_coord_sender.go#L942)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

The lifetime of the parent ctx/span doesn't matter. The relationship between the span created by `RunAsyncTask` and the parent span is `FollowsFrom`, which doesn't imply anything about the respective lifetimes. What the relationship between the spans does do, however, is that it makes the child be part of the "recording" of the parent - which is how I get the hb trace in the new test. For recording purposes, the lifetime of the spans involved also doesn't matter - you can get a (possibly partial) recording while some of the spans are still live.

But anyway, that's why this is a different commit. We don't have to cherry-pick.
</blockquote></details>

You could also avoid this subtlety and trace an event in the parent span and match that in the test. I'd prefer this because it's less subtle and will achieve the desired effect.

**Review by tbg — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27973)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27973)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/kv/txn_coord_sender.go, line 942 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27973#-LINvx1sEgz9ddP_5ZHC:-LIfTTdf7tADprOTY_cl:bpkeltd) ([raw file](https://github.com/cockroachdb/cockroach/blob/39bbee13ac0ab2021cb7c1d1d724d67fc3c67905/pkg/kv/txn_coord_sender.go#L942)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

You could also avoid this subtlety and trace an event in the parent span and match that in the test. I'd prefer this because it's less subtle and will achieve the desired effect.
</blockquote></details>

Well but there's not really any new subtlety here. The subtlety that exists is old, due to getting rid of the caller's cancelation. Doing the `RunAsyncTask` with the caller's span is natural; it's the usual way of doing things (thus, you can argue that my additions to the comment are not necessary).
Besides, tracing heartbeats when you trace the SQL statement is a good thing, I'd say, and also you had a TODO asking for just that.

**Comment by tschottdorf** [comment]
LGTM

**Pull request merged**
