### PR TITLE
Make DistSender.sendRPC() return an error when a replica set is empty

### PR DESCRIPTION
**Pull request by kkaneda**
This addresses tschottdorf's TODO comment.

The first commit was needed to make all tests pass (similar to what we made to multiTestContext).

### CODE REVIEW

**Comment by tamird** [comment]
LGTM modulo comment left on 4f6a86d

**Comment by tschottdorf** [comment]
LGTM (after @tamird's comment). Thanks for cleaning this up.

**Comment by kkaneda** [comment]
Hmm, I thought we need this pattern to put gossip info with a non-default TTL, but I'm not totally sure. Wil check.. I guess we can also change `SetNodeDescriptor

**Comment by kkaneda** [comment]
Removed `AddInfoProto` as @tamird suggested (from `LocalTestCluster` and `multiTestContext`). All tests still passed.

**Pull request merged**
