### PR TITLE
release-21.2: backupccl: backup processor goroutines may outlive the processor

### PR DESCRIPTION
**Pull request by adityamaru**
Backport 2/7 commits from #72624.

/cc @cockroachdb/release

---

See individual commits.
This is all happening because I want to make using Spans after they've been FInish()ed less tolerated than it has historically been.

Fixes: https://github.com/cockroachdb/cockroach/issues/75754

Release justification (bug fix): goroutines spawned by the backup processor
were mutating BoundAccounts used for memory monitoring, after the BoundAccount
was closed by the processor on shutdown. To prevent this, we teach the processor
to wait for all goroutines to terminate before running its cleanup on shutdown.

### CODE REVIEW

**Comment by adityamaru** [comment]
We're considering this backport because of the reason described in this [internal thread](https://cockroachlabs.slack.com/archives/C2C5FKPPB/p1643645145821079).

**Comment by adityamaru** [comment]
@andreimatei I want to get your temperature on this backport given the original motivation of these commits. Do you think it is safe given the fairly involved diffs?

**Review by dt — APPROVED** [review]
I like it if @andreimatei likes it

**Review by andreimatei — COMMENTED** [review]
:lgtm: 

But if you only need some of the commits to fix the bug that prompted this, it'd probably be preferable to backport only those.
Please make a note in the commit message about the issues that prompted this.

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75744#-:-MuqzL0n7VT-mvv8hLSm:b-pi5rqw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @HonoreDB)

**Comment by adityamaru** [comment]
> But if you only need some of the commits to fix the bug that prompted this, it'd probably be preferable to backport only those.

We can get away with just the first two commits that touch the backup processor.  The remainder of them fix up the split and scatter proc, changefeed proc, and restore proc. I'm okay minimizing this backport given the urgency of the merge, and then maybe opening an independent backport with bake time as a bug fix for the other processors.

**Pull request merged**
