### PR TITLE
quickly refresh table lease to the latest version

### PR DESCRIPTION
**Pull request by vivekmenezes**
Use the gossip of the system config to discover a new version of a
table, and reacquire a new lease on the table.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3243)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM. Anything to test or benchmark here?

**Comment by vivekmenezes** [comment]
This is tested by all the schema change tests in SQL/testdata that depend
on leases upgrading quickly. Without this change the executor directly
upgrades the version in releaseleases, now its done via gossip.

**Comment by petermattis** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/lease.go, line 605 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3243#-K4NaEUzHZEWyaNv_-ul:-K4NaEUzHZEWyaNv_-um:769008333) ([raw file](https://github.com/cockroachdb/cockroach/blob/80c030fd1ba72300030be362e51914d7de5ca445/sql/lease.go#L605)):*
I think you should examine the key here to determine if it belongs to the descriptor table. Blindly attempting to decode the value as a descriptor might succeed incorrectly.

---

*[sql/lease.go, line 664 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3243#-K4Naduwxdzv5e5Mlxku:-K4Naduwxdzv5e5Mlxkv:684991891) ([raw file](https://github.com/cockroachdb/cockroach/blob/80c030fd1ba72300030be362e51914d7de5ca445/sql/lease.go#L664)):*
This method name was slightly confusing to me. Perhaps `waitForVersion`?

---

*[sql/lease.go, line 670 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3243#-K4NbCVDgrWkoo-O0BdA:-K4NbCVDgrWkoo-O0BdB:-1846673870) ([raw file](https://github.com/cockroachdb/cockroach/blob/80c030fd1ba72300030be362e51914d7de5ca445/sql/lease.go#L670)):*
Won't it be bad if `MaxRetries` occurs without the version being upgraded? I think we'd get spurious test failures. Rather than this `tryWait` mechanism, perhaps we should have some sort of `wait` mechanism that performs registration instead of polling. Since we're only waiting for the local lease version to be upgraded, I think this can be add to `tableState` without much complication.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3243)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/lease.go, line 605 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3243#-K4NaEUzHZEWyaNv_-ul:-K4O7QUxMrmMHWUBYEht:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/80c030fd1ba72300030be362e51914d7de5ca445/sql/lease.go#L605)):*
done

---

*[sql/lease.go, line 664 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3243#-K4Naduwxdzv5e5Mlxku:-K4NvhAT7Iyh093BieI-:38388861) ([raw file](https://github.com/cockroachdb/cockroach/blob/80c030fd1ba72300030be362e51914d7de5ca445/sql/lease.go#L664)):*
I now use Publish().

---

*[sql/lease.go, line 670 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3243#-K4NbCVDgrWkoo-O0BdA:-K4Nvle21c6yma4DbYaw:-265839344) ([raw file](https://github.com/cockroachdb/cockroach/blob/80c030fd1ba72300030be362e51914d7de5ca445/sql/lease.go#L670)):*
Changed to use Publish(). I had to actively give up old leases to get it to work, but that's the right long term approach. See the change to acquire()

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3243)*

**Comment by petermattis** [comment]
LGTM

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/lease.go, line 648 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3243#-K4OCJJA6jRQIS3xn01M:-K4OCJJA6jRQIS3xn01N:405792841) ([raw file](https://github.com/cockroachdb/cockroach/blob/806034a4b965efea697962204d594fc5fe0efd93/sql/lease.go#L648)):*
Eventually we'll want to only gossip the table IDs, not the entire table descriptor. I think it should be fine to pass `0` instead of `table.Version` here. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3243#-:-K4OCcUgbTjYF463mdiR:676834233)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/lease.go, line 648 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3243#-K4OCJJA6jRQIS3xn01M:-K4OD0FSDG1SVT-HOl5R:-1314411122) ([raw file](https://github.com/cockroachdb/cockroach/blob/806034a4b965efea697962204d594fc5fe0efd93/sql/lease.go#L648)):*
We want to pass the version in here because we want to force Acquire() to acquire a lease with a min version. Passing in 0 will increment the refcount on the latest valid lease.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3243)*

**Comment by tamird** [comment]
Reviewed 3 of 5 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/lease.go, line 624 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3243#-K4OEvZfr9Z2aJq3Ds_j:-K4OEvZfr9Z2aJq3Ds_k:-1738997640) ([raw file](https://github.com/cockroachdb/cockroach/blob/806034a4b965efea697962204d594fc5fe0efd93/sql/lease.go#L624)):*
the tag is meant to be private, i don't think you need to check it now that you're checking the key prefix

---

*[sql/plan.go, line 220 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3243#-K4OFFa8WVgV5QgZ8IFc:-K4OFFa8WVgV5QgZ8IFd:1601536700) ([raw file](https://github.com/cockroachdb/cockroach/blob/806034a4b965efea697962204d594fc5fe0efd93/sql/plan.go#L220)):*
This error leaves me wondering; why "dont update table descriptor"? the context in which it's used is already exclusive to table descriptors...can you make this clearer?

---

*[sql/plan.go, line 243 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3243#-K4OFD2VRQCYLkEg_opt:-K4OFD2VRQCYLkEg_opu:1202131648) ([raw file](https://github.com/cockroachdb/cockroach/blob/806034a4b965efea697962204d594fc5fe0efd93/sql/plan.go#L243)):*
can you break this line?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3243)*

**Comment by vivekmenezes** [comment]
I merged this. 'll send out another PR to address your feedback. Thanks!

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[sql/lease.go, line 648 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3243#-K4OCJJA6jRQIS3xn01M:-K4OGWbLRSdks2TiVc_z:-95964447) ([raw file](https://github.com/cockroachdb/cockroach/blob/806034a4b965efea697962204d594fc5fe0efd93/sql/lease.go#L648)):*
Ah, good point.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3243)*

**Pull request merged**
