### PR TITLE
*: remove use of `import weak`

### PR DESCRIPTION
**Pull request by tamird**
This feature is non standard, and we're better off not relying on it.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8984)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 84 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8984#-:-KQWWBpwl8YNLlPNwsc6:bnfp4nl)*

**Comment by tschottdorf** [comment]
LGTM

**Comment by maxlang** [comment]
@tamird why did this require changing the UI proto namespacing?

**Comment by tamird** [comment]
The UI proto namespaces are defined by generated code. I can explain in person, but TL;DR is "because that's what the tools did".

**Pull request merged**
