### PR TITLE
sql: add syntax to create unique constraints without an index

### PR DESCRIPTION
**Pull request by rytaft**
This commit adds support for the syntax `... UNIQUE WITHOUT INDEX ...`,
both when adding `UNIQUE` constraints and when adding `UNIQUE` columns. Using
this syntax will currently return the error "unique constraints without
an index are not yet supported", but support for the syntax serves as a
starting point for adding support for these unique constraints.

Informs #41535

Release note (sql change): Added support for using the syntax
`... UNIQUE WITHOUT INDEX ...` in CREATE TABLE and ALTER TABLE statements,
both when defining columns and unique constraints. Although this syntax
can now be parsed successfully, using this syntax currently returns an
error "unique constraints without an index are not yet supported".

### CODE REVIEW

**Review by knz — APPROVED** [review]
parser code changes LGTM

(did not review whether it matches the desired spec)

i'd say @otan is maybe the better person to review the change holistically.

**Comment by rytaft** [comment]
TFTR! Added @otan as a reviewer.

**Comment by RaduBerinde** [comment]
One alternative that I want to run by you is specifying something like `UNIQUE INDEX (a) PARTITIONED BY (region)`, which would create unique index `(region, a)` to be used for the uniqueness checks. That would make it harder to misuse (creating uniqueness constraints without any useful index).

Maybe `PARTITIONED BY` is not the right word, as there's nothing specific about regions, other ideas are `SHARDED BY`, `PREFIXED BY`

**Comment by mgartner** [comment]
I'm a +1 for eliminating the possibility for users to introduce full table scans for simple INSERTs: https://github.com/cockroachdb/cockroach/issues/41535#issuecomment-712416189

**Comment by rytaft** [comment]
My understanding is that we want customers to be able to move from a single-region deployment to a multi-region deployment without changing their schema, and everything should "just work". So `UNIQUE INDEX (a)` would effectively become syntactic sugar for something like `UNIQUE INDEX (a) PARTITIONED BY (region)` (and we don't necessarily even need to support the `PARTITIONED BY` syntax). I'm not opposed to adding that syntax in case power users want to specify a column other than `region` to use for partitioning -- but that would be a separate PR.

The syntax in this PR is unrelated to the new Multi-Region abstractions, and will allow us to separate the concept of unique constraints from unique indexes. I don't think it will be easy to misuse, because users will need to knowingly write `WITHOUT INDEX` in their schema.  I also don't expect it to be a commonly used feature other than for advanced users and for testing purposes.

By separating the concept of unique constraints from unique indexes, we'll be able to add a unique check by default to any mutation that touches a unique column or set of columns, and as an optimization, remove it if there exists a unique index with those columns. Otherwise, the check itself can be optimized by taking advantage of any indexes available (such as a partitioned unique index). This has the advantage of keeping the uniqueness checks general and not tied to the concept of regions.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55700)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @otan, and @rytaft)

___
*[docs/generated/sql/bnf/col_qualification.bnf, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55700#-MK1dKCvEixhHWro1ucO:-MK1dKCw-HluVgbAMaA_:bdmh1dm) ([raw file](https://github.com/cockroachdb/cockroach/blob/51387f6ddc96654b62a52781589a535bf1a308c8/docs/generated/sql/bnf/col_qualification.bnf#L13)):*
> ```
> 	| 'NOT' 'NULL'
> 	| 'NULL'
> 	| 'UNIQUE' opt_without_index
> ```

i'm reading https://medium.com/flatiron-engineering/uniqueness-in-postgresql-constraints-versus-indexes-4cf957a472fd and it seems as though indexes and constraints for UNIQUE have different properties. 

it sounds like for this case, this should be a constraint, not an index, and so only a constraint CONSTRAINT ... WITHOUT INDEX syntax is the thing we want.

is this something we care about?

**Comment by rytaft** [comment]
___
*[docs/generated/sql/bnf/col_qualification.bnf, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55700#-MK1dKCvEixhHWro1ucO:-MK1eaTLDyjiSGwy2JtB:b-1gor53) ([raw file](https://github.com/cockroachdb/cockroach/blob/51387f6ddc96654b62a52781589a535bf1a308c8/docs/generated/sql/bnf/col_qualification.bnf#L13)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i'm reading https://medium.com/flatiron-engineering/uniqueness-in-postgresql-constraints-versus-indexes-4cf957a472fd and it seems as though indexes and constraints for UNIQUE have different properties. 

it sounds like for this case, this should be a constraint, not an index, and so only a constraint CONSTRAINT ... WITHOUT INDEX syntax is the thing we want.

is this something we care about?
</blockquote></details>

My understanding from reading that article is that `UNIQUE` constraints and `UNIQUE` indexes in Postgres are in fact identical due to the implementation of `UNIQUE` constraints using an index. I know it says "the preferred method is to use constraints", but that seems to be purely for academic reasons.

But either way, it's not clear to me that there is a difference between `CONSTRAINT foo UNIQUE (a)` and `UNIQUE (a)` other than the fact that the first one has a name. I don't think the second one necessarily implies the presence of an index any more than the first one does. Am I missing something?

**Review by otan — APPROVED** [review]
> Reviewed 1 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55700)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @rytaft)

___
*[docs/generated/sql/bnf/col_qualification.bnf, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55700#-MK1dKCvEixhHWro1ucO:-MK1lKTnDLU4PV0-uXtA:bss9kjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/51387f6ddc96654b62a52781589a535bf1a308c8/docs/generated/sql/bnf/col_qualification.bnf#L13)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

My understanding from reading that article is that `UNIQUE` constraints and `UNIQUE` indexes in Postgres are in fact identical due to the implementation of `UNIQUE` constraints using an index. I know it says "the preferred method is to use constraints", but that seems to be purely for academic reasons.

But either way, it's not clear to me that there is a difference between `CONSTRAINT foo UNIQUE (a)` and `UNIQUE (a)` other than the fact that the first one has a name. I don't think the second one necessarily implies the presence of an index any more than the first one does. Am I missing something?
</blockquote></details>

Taking a read of https://stackoverflow.com/questions/23542794/postgres-unique-constraint-vs-index

It seems like UNIQUE CONSTRAINT doesn't actually need to be backed by an index -- just that all the databases decided to implemented that way.

From what I can tell online, there are things CONSTRAINTS cannot do that indexes can or vice versa, e.g. DEFERRED (constraints only), CONCURRENTLY (index only), ON CONFLICT (constraints only).

The difference seems subtle but I would not be surprised if people relied on it (and not surprised if we treat them the same when we shouldn't).

Taking a re-read of this though, seems like `UNIQUE` in this clause makes it a constraint so it doesn't really matter, my bad.

**Comment by otan** [comment]
___
*[docs/generated/sql/bnf/col_qualification.bnf, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55700#-MK1dKCvEixhHWro1ucO:-MK1nC_v7cOGwHTjrJNV:b5702sv) ([raw file](https://github.com/cockroachdb/cockroach/blob/51387f6ddc96654b62a52781589a535bf1a308c8/docs/generated/sql/bnf/col_qualification.bnf#L13)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Taking a read of https://stackoverflow.com/questions/23542794/postgres-unique-constraint-vs-index

It seems like UNIQUE CONSTRAINT doesn't actually need to be backed by an index -- just that all the databases decided to implemented that way.

From what I can tell online, there are things CONSTRAINTS cannot do that indexes can or vice versa, e.g. DEFERRED (constraints only), CONCURRENTLY (index only), ON CONFLICT (constraints only).

The difference seems subtle but I would not be surprised if people relied on it (and not surprised if we treat them the same when we shouldn't).

Taking a re-read of this though, seems like `UNIQUE` in this clause makes it a constraint so it doesn't really matter, my bad.
</blockquote></details>

(there's also some fun differences involving NULLS on constraints vs indexes too, but I'm going to stop reading there because my head hurts)

**Comment by rytaft** [comment]
___
*[docs/generated/sql/bnf/col_qualification.bnf, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55700#-MK1dKCvEixhHWro1ucO:-MK1q36-AVkoB7Jz96Tr:bwgtihx) ([raw file](https://github.com/cockroachdb/cockroach/blob/51387f6ddc96654b62a52781589a535bf1a308c8/docs/generated/sql/bnf/col_qualification.bnf#L13)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

(there's also some fun differences involving NULLS on constraints vs indexes too, but I'm going to stop reading there because my head hurts)
</blockquote></details>

Haha sounds good -- thanks for checking this out. I don't think we currently treat the two concepts differently in CRDB, but that's good to know that there are differences in other DBs.

**Comment by mgartner** [comment]
Thanks for the additional context @rytaft. LGTM!

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55700#-:-MK6CqdO5iHtX-0iv4LE:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @otan, and @rytaft)

___
*[pkg/sql/sem/tree/create.go, line 372 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55700#-MK6CU3t5uuRLdvfpu6I:-MK6CU3t5uuRLdvfpu6J:be65kah) ([raw file](https://github.com/cockroachdb/cockroach/blob/51387f6ddc96654b62a52781589a535bf1a308c8/pkg/sql/sem/tree/create.go#L372)):*
> ```Go
> 		ShardBuckets Expr
> 	}
> 	Unique               bool
> ```

[nit] maybe group these into a `Unique struct` like the others. Also maybe `WithoutIndex` instead of `NoIndex` would make it easier for people to discover the corresponding syntax.

**Review by rytaft — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55700#-:-MK7Fimm3NUjY9-VrhTI:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @otan)

___
*[pkg/sql/sem/tree/create.go, line 372 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55700#-MK6CU3t5uuRLdvfpu6I:-MK7Fku97Rc6AZHd10mN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/51387f6ddc96654b62a52781589a535bf1a308c8/pkg/sql/sem/tree/create.go#L372)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] maybe group these into a `Unique struct` like the others. Also maybe `WithoutIndex` instead of `NoIndex` would make it easier for people to discover the corresponding syntax.
</blockquote></details>

Done.

**Comment by awoods187** [comment]
I like the proposed syntax and think we may not need Radus suggestion but its good to have in reserve if we need it.

**Review by rytaft — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55700#-:-MK7gQVk4YZpA_43j_PW:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @otan)

**Pull request merged**
