### PR TITLE
sql: fix statement tags for CREATE and DROP PROCEDURE

### PR DESCRIPTION
**Pull request by mgartner**
Epic: CRDB-25388

Release note: None

### CODE REVIEW

**Review by rharding6373 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112054#-:-NgKbZtE8DWU2gHT8UyN:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112054#-:-NgLU4z_6TS_pRFrLzya:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by mgartner** [comment]
I had to make some changes to statement tag usage in `scbuildstmt`. @fqazi can you please take a look?

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112054)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball, @fqazi, and @mgartner)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go` line 32 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112054#-NgPU_Pb8nPYmmVItm-p:-NgPU_Pb8nPYmmVItm-q:bkgpz6k) ([raw file](https://github.com/cockroachdb/cockroach/blob/27153154398d989da9ffc0407a8f01532e27d609/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go#L32)):*
> ```Go
> 	// altStatements are concrete statements that correspond to each of the
> 	// tags in statementTags, if statementTags has more than one element.
> 	altStatements []tree.Statement
> ```

Is this only being used by tests? I think you could define it in the test and have an assertion that it is specified for the test when `len(statementTags) > 1`.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go` line 71 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112054#-NgPTSWoAaYyoaJFo45m:-NgPTSWoAaYyoaJFo45n:b-ok8lnc) ([raw file](https://github.com/cockroachdb/cockroach/blob/27153154398d989da9ffc0407a8f01532e27d609/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go#L71)):*
> ```Go
> 		fn:            DropFunction,
> 		statementTags: []string{tree.DropFunctionTag, tree.DropProcedureTag},
> 		altStatements: []tree.Statement{&tree.DropRoutine{}, &tree.DropRoutine{Procedure: true}},
> ```

It might be more st

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112054)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball, @ecwall, and @fqazi)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go` line 32 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112054#-NgPU_Pb8nPYmmVItm-p:-NgZUvgH1nxaYlcNFxEj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/27153154398d989da9ffc0407a8f01532e27d609/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go#L32)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

Is this only being used by tests? I think you could define it in the test and have an assertion that it is specified for the test when `len(statementTags) > 1`.
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go` line 71 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112054#-NgPTSWoAaYyoaJFo45m:-NgZT1oP9XNs-JiAEbzX:brz4esc) ([raw file](https://github.com/cockroachdb/cockroach/blob/27153154398d989da9ffc0407a8f01532e27d609/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go#L71)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

It might be more st
</blockquote></details>

Looks like your comment was cutoff here. Do you remember your feedback here?

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112054)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball and @fqazi)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go` line 71 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112054#-NgPTSWoAaYyoaJFo45m:-Nga1vNkBR1pJNL9CXFz:bcx8ko7) ([raw file](https://github.com/cockroachdb/cockroach/blob/27153154398d989da9ffc0407a8f01532e27d609/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go#L71)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Looks like your comment was cutoff here. Do you remember your feedback here?
</blockquote></details>

Oh I got distracted mid review and ended up rephrasing what I was going to type here in the other comment.

**Review by ecwall — APPROVED** [review]
> Reviewed 2 of 9 files at r3, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112054)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @fqazi)

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
