### PR TITLE
smith: add all argument columns to ORDER BY

### LINKED ISSUE #85318: roachtest: unoptimized-query-oracle/disable-rules=all failed
roachtest.unoptimized-query-oracle/disable-rules=all [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/5902767?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/5902767?buildTab=artifacts#/unoptimized-query-oracle/disable-rules=all) on master @ [1129fbc650fe3a037b03aea1e5f1d8078618cb1c](https://github.com/cockroachdb/cockroach/commits/1129fbc650fe3a037b03aea1e5f1d8078618cb1c):

```
		  |   	"-Infinity,010700000000000000,0010001010111110001111110",
		  |   	strings.Join({
		  |   		"1.485516215647236566",
		  | + 		"0",
		  |   		"E+32,010700000000000000,0110000010000010110000000",
		  |   	}, ""),
		  |   	strings.Join({
		  |   		"2.755603564428860743453",
		  | + 		"000",
		  |   		"E+37,010700000000000000,0001010011100010101101110",
		  |   	}, ""),
		  |   	strings.Join({
		  |   		"3.123916611966922154",
		  | + 		"0",
		  |   		"E+32,010700000000000000,1001100001110110101111100",
		  |   	}, ""),
		  |   	strings.Join({
		  |   		"6.10440982912751745153",
		  | + 		"000",
		  |   		"E+36,010700000000000000,0000000000000000000000000",
		  |   	}, ""),
		  |   	"7.989390758504398128393E+31,010700000000000000,01001100010001111"...,
		  |   	"7.9920344431208130711696565E+31,010700000000000000,0000000000000"...,
		  |   	... // 2 identical elements
		  |   	"7.992034959937127520353632372E+31,010700000000000000,00000000000"...,
		  |   	"7.9920349667646091435806116843E+31,010700000000000000,0000000000"...,
		  |   	strings.Join({
		  |   		"7.9920349668165283642055406424",
		  | + 		"0",
		  |   		"E+31,010700000000000000,0111111111111111111111111",
		  |   	}, ""),
		  |   	"7.9920349669084530000000000001E+31,010700000000000000,0000000000"...,
		  |   	"7.99203496690845300001201E+31,010700000000000000,000000000000000"...,
		  | - 	"7.992034966908453E+31,010700000000000000,1010001100111011101100010",
		  |   	"7.992034966915241332180986727519E+31,010700000000000000,00000000"...,
		  |   	"7.99203496695820375563012709761E+31,010700000000000000,000000000"...,
		  |   	"7.992034967456274663078081736E+31,010700000000000000,00000000000"...,
		  |   	"7.99203497983829097165656138E+31,010700000000000000,000000000000"...,
		  |   	strings.Join({
		  |   		"7.992034990447552932433382",
		  | + 		"0",
		  |   		"E+31,010700000000000000,1111111111111111111111111",
		  |   	}, ""),
		  |   	... // 43 identical, 1 inserted, and 5 modified elements
		  |   }
		  | sql: SELECT
		  | 	tab_431.col1_12 AS col_1257, '010700000000000000':::GEOMETRY AS col_1258, tab_431.col1_9 AS col_1259
		  | FROM
		  | 	defaultdb.public.table1@[0] AS tab_431
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.leafError
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*unoptimized-query-oracle/disable-rules=all.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-18183

### LINKED ISSUE #87023: roachtest.unoptimized-query-oracle/disable-rules=half
roachtest.unoptimized-query-oracle/disable-rules=half [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6231545?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6231545?buildTab=artifacts#/unoptimized-query-oracle/disable-rules=half) on master @ [524fd14da3fefcd849f44a835cc5f88f5dbdadcc](https://github.com/cockroachdb/cockroach/commits/524fd14da3fefcd849f44a835cc5f88f5dbdadcc):

```
		  |   	"-99,a\n,NULL,BOX(-1 15,0 16),0,{\"\\\\xc5b5f3991f524f\"},NULL,\ta",
		  |   	... // 15 identical elements
		  |   	"-99,a\n,NULL,BOX(-1.2958624195456403 -0.7007902262760126,-0.76394"...,
		  |   	"-99,a\n,NULL,BOX(-1.3207114753925442 0.07543733824577625,0.411722"...,
		  |   	strings.Join({
		  |   		"-99,a\n,NULL,BOX(-1.371471829151467 1.5445529591343243,-0.4097185",
		  |   		``8119740223 1.5844682297595416),0,{"\\x97","\\x4161"},``,
		  | + 		"NULL",
		  |   		``,	a``,
		  |   	}, ""),
		  |   	"-99,a\n,NULL,BOX(-1.3926406249344883 -0.6842762115529295,-0.23034"...,
		  |   	"-99,a\n,NULL,BOX(-1.3965146560734436 -0.5498867231573248,-0.99270"...,
		  |   	... // 35 identical elements
		  |   	"-99,a\n,NULL,BOX(-10 -10,10 10),0,{\"\\\\x\",\"\\\\x2061\"},NULL,\ta",
		  |   	"-99,a\n,NULL,BOX(-10 -10,10 10),0,{\"\\\\x\",\"\\\\x2f78f42ae5ad84f2\",\"\\"...,
		  |   	strings.Join({
		  |   		"-99,a\n,NULL,BOX(-10 -10,10 10),0,{\"\\\\x\",\"\\\\x6120\",\"\\\\x\",\"\\\\x840c",
		  |   		"148fef14\"},\xc3",
		  | - 		"\x80",
		  | + 		"\xa0",
		  |   		",h\xc5",
		  |   	}, ""),
		  |   	"-99,a\n,NULL,BOX(-10 -10,10 10),0,{\"\\\\x\",\"\\\\x616162\",\"\\\\xaf928150"...,
		  |   	"-99,a\n,NULL,BOX(-10 -10,10 10),0,{\"\\\\x\",\"\\\\x7c3fdc0d748201\"},NUL"...,
		  |   	... // 55 identical elements
		  |   	"-99,a\n,NULL,BOX(-10 -10,10 10),0,{\"\\\\x58\"},',\ta",
		  |   	"-99,a\n,NULL,BOX(-10 -10,10 10),0,{\"\\\\x5b\"},\f,\ta",
		  |   	strings.Join({
		  |   		"-99,a\n,NULL,BOX(-10 -10,10 10),0,{\"\\\\x5f\",\"\\\\x4161\",\"\\\\xc3a0c3a1",
		  |   		``","\\x3a9d1d5c8d"},``,
		  | - 		"\x00",
		  |   		",aaaaaa",
		  |   	}, ""),
		  |   	... // 347 identical and 12 modified elements
		  |   }
		  | sql: SELECT
		  | 	(-99):::INT8 AS col_3616,
		  | 	e'a\n':::STRING AS col_3617,
		  | 	tab_1118.col1_0 AS col_3618,
		  | 	tab_1118.col1_7 AS col_3619,
		  | 	0:::OID AS col_3620,
		  | 	tab_1118.col1_1 AS col_3621,
		  | 	lag(tab_1118.col1_2::STRING) OVER (PARTITION BY tab_1118.col1_3, tab_1118.crdb_internal_mvcc_timestamp ORDER BY tab_1118.col1_16, tab_1118.col1_2 ROWS CURRENT ROW)::STRING
		  | 		AS col_3622,
		  | 	tab_1118.col1_6 AS col_3623
		  | FROM
		  | 	defaultdb.public.table1@[0] AS tab_1118
		  | ORDER BY
		  | 	tab_1118.col1_15 DESC
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.leafError
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*unoptimized-query-oracle/disable-rules=half.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

_Originally posted by @cockroach-teamcity in https://github.com/cockroachdb/cockroach/issues/86308#issuecomment-1227382488_

Jira issue: CRDB-19105

### PR DESCRIPTION
**Pull request by DrewKimball**
This commit ensures that sqlsmith adds all function argument columns to
the `ORDER BY` clause when nondetermistic functions are disabled. This is
necessary for functions like `string_agg`, for which there may be multiple
possible values for each argument when the order is not specified.

As a special case, `lead` and `lag` require all input columns to be added
to the `ORDER BY` clause. This is because while they respect the specified
order, they can still access any value in the partition. This means that we
need to uniquely specify which rows fall on the boundaries of each peer group.
We can ensure this is the case by ordering on a key, and we can trivially
order on a key by ordering on all columns.

Partially addresses #85318
Fixes #87023

Release justification: testing-only change

Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87085#-:-NAj_GIn-5c8zu06r2x6:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`-- commits` line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87085#-NAjZK1WAJXzYYrCO4Y-):*
nit: this will close the issue - is it desirable? If not, maybe do `s/fixes/addresses/`.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87085)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`-- commits` line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87085#-NAjZK1WAJXzYYrCO4Y-):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: this will close the issue - is it desirable? If not, maybe do `s/fixes/addresses/`.
</blockquote></details>

Done.

**Comment by DrewKimball** [comment]
TFTR!

**Review by mgartner — APPROVED** [review]
Nice find!

**Comment by DrewKimball** [comment]
Thanks!
bors r+

**Comment by mgartner** [comment]
@DrewKimball Do you think the `lead`/`lag` special case mentioned about would also apply to other aggregates, like `concat_agg`? It seems like that might be causing failures like this one: https://github.com/cockroachdb/cockroach/issues/87335#issuecomment-1237128778 and this one: https://github.com/cockroachdb/cockroach/issues/87353#issue-1360781902.

**Comment by DrewKimball** [comment]
Now that you mention it, I think it's better to think in terms of what window functions _don't_ need to order on a key - `rank` and `dense_rank` should be ok, since the result is always the same within a peer group. I think basically everything else (including aggregate functions) needs to be ordering on a key - anything that doesn't explicitly return the same value for every row in a given peer group. As an example, `row_number` obviously will care if the ith row is switched with the (i-1)th row. Many aggregate functions are order-agnostic, but they respect window frames, which are not order-agnostic (in general).

**Pull request merged**
