### PR TITLE
config: Remove an unnecessary static split

### PR DESCRIPTION
**Pull request by bdarnell**
No data is ever written between SystemPrefix and NodeLivenessPrefix,
so splitting there just creates a range which will always be
empty (and requires an expiration-based lease). Since this range is
never touched by anything but the replica scanner, it sometimes lacks
an active lease and is misleadingly reported as a problem range.

Removing this static split will stop creating this empty range for new
clusters, and allow the merge queue to remove it for clusters
upgrading to this version.

Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33233)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/client_replica_test.go, line 1682 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33233#-LU0hAiF9CwsccbXkTyS:-LU0hAiGDFU2UlqmdflI:b-gvrh5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/89a0eca98b4ea2b86ebff68645f93723ab32b0bb/pkg/storage/client_replica_test.go#L1682)):*
> ```Go
> 	// two system ranges, which we have to take into account here.
> 	sqlutils.SetZoneConfig(t, sqlDB, "RANGE system", "num_replicas: 7")
> 	expectedReplicas += 4
> ```

Why is the expected replica count dropping by 2? I would think it would only decrease by 1 from removing this unnecessary split.

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33233)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/client_replica_test.go, line 1682 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33233#-LU0hAiF9CwsccbXkTyS:-LU0iaFhCqS0tDzFOTut:bty66cj) ([raw file](https://github.com/cockroachdb/cockroach/blob/89a0eca98b4ea2b86ebff68645f93723ab32b0bb/pkg/storage/client_replica_test.go#L1682)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Why is the expected replica count dropping by 2? I would think it would only decrease by 1 from removing this unnecessary split.
</blockquote></details>

We're testing the impact of changing from the default r=5 to r=7, which adds two replicas to each range (total replicas across the cluster, not on one node). There used to be three system ranges (the comment had rotted); now there are two.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33233#-:-LU0lCWz7_42deJ9HXLE:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/storage/client_replica_test.go, line 1682 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33233#-LU0hAiF9CwsccbXkTyS:-LU0l9NCB1OBPeDINkTJ:b-8yabji) ([raw file](https://github.com/cockroachdb/cockroach/blob/89a0eca98b4ea2b86ebff68645f93723ab32b0bb/pkg/storage/client_replica_test.go#L1682)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

We're testing the impact of changing from the default r=5 to r=7, which adds two replicas to each range (total replicas across the cluster, not on one node). There used to be three system ranges (the comment had rotted); now there are two. 
</blockquote></details>

Ah, replicas vs ranges confused me. Got it.

**Comment by bdarnell** [comment]
bors r=petermattis

**Pull request merged**
