### PR TITLE
catalog: don't set modification time for offline descriptors

### LINKED ISSUE #109976: roachtest: backup-restore/mixed-version failed [descriptor version conflict when RESTORE and 22.2 upgrade overlaps]
roachtest.backup-restore/mixed-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11606142?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11606142?buildTab=artifacts#/backup-restore/mixed-version) on master @ [b994d025c678f495cb8b93044e35a8c59595bd78](https://github.com/cockroachdb/cockroach/commits/b994d025c678f495cb8b93044e35a8c59595bd78):

```
(mixedversion.go:537).Run: mixed-version test failure while running step 33 (run "verify some backups"): mixed-version: waiting for job to finish: job 896745437416751105 failed with error: version mismatch for descriptor 201, expected version 2, got 1
test artifacts and logs in: /artifacts/backup-restore/mixed-version/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/p/roachfana/teamcity-11606142-1693720070-28-n5cpu4/1693732931983/1693735451452)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #109975 roachtest: backup-restore/mixed-version failed [C-test-failure O-roachtest O-robot T-disaster-recovery branch-release-23.1 release-blocker]
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backup-restore/mixed-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-31196

### PR DESCRIPTION
**Pull request by rafiss**
There is a post-deserialization change that automatically sets the
modification time for all descriptors if it is not present. Notably,
there is also a cluster upgrade step that rewrites all descriptors with
post-deserialization changes, and bumps their version.

If a RESTORE is running during an upgrade, the descriptors it tries to
rewrite could have been also bumped by the upgrade step. That
would cause the RESTORE to fail.

Now, the change to automatically set the modification time is disabled
if the descriptor is on the offline state, as it is during RESTORE.

fixes https://github.com/cockroachdb/cockroach/issues/109976

Release note (bug fix): Fixed a bug that could prevent RESTORE from
working if it was performed during a cluster upgrade.

### CODE REVIEW

**Review by stevendanna — COMMENTED** [review]
Thanks for digging into this. Overall the code looks good but I'm not 100% sure on the test.

Have we seen this fail without the early return in place in one of the MustSetModificationTime functions?  I ask because I thought that the descriptor version is only bumped in WriteDescToBatch and a few other places, so it is possible that while TestingGetSchemaDescriptor would previously have resulted in the modification time being set, it wouldn't have actually bumped the desc version so this test still would have passed.  But, I may be missing something.

If I'm not missing something, maybe an alternative would be to assert that we don't have any deserialisation changes queued up with something like `dbDesc.NewBuilder().BuildImmutable().GetPostDeserializationChanges().HasChanges()`. Since the test you've modified here doesn't cross any versions it _seems_ to me that it would be a correct assertion.


On the DR side, I think we should probably write a test that runs all of the upgrades before publishing descriptors to future proof us against other kinds of changes, but I don't think that is on you to add. We can follow up with such a test on master.

**Comment by rafiss** [comment]
> If I'm not missing something, maybe an alternative would be to assert that we don't have any deserialisation changes queued up with something like dbDesc.NewBuilder().BuildImmutable().GetPostDeserializationChanges().HasChanges(). Since the test you've modified here doesn't cross any versions it seems to me that it would be a correct assertion.

Thanks for that extra nudge and the information. You're right - that is the correct assertion to have. I've made the change and added comments explaining why it's being checked.

**Review by stevendanna — APPROVED** [review]
LGTM. Thanks!

**Comment by rafiss** [comment]
tftr!

bors r+

**Pull request merged**
