### PR TITLE
jobs,*: make job clients responsible for generating IDs

### LINKED ISSUE #57492: jobs: generate IDs from the client
Today job IDs are created by the `DEFAULT` expression on the primary key column. The problem with this is that the job IDs are often referenced inside of other objects. Given we don't know the job ID until we write the job record, constructing other things which reference a job in a transaction is awkward. Worse, we have some code that ends up leaking jobs because we create a new ID upon transaction retries, making the whole thing hard to make idempotent.

### PR DESCRIPTION
**Pull request by thoszhang**
jobs,*: make job clients responsible for generating IDs

Job IDs used to be randomly generated in the job registry when creating
a job, which meant that they were not stable across restarts when jobs
were created in a txn closure meant to be idempotent. For
`StartableJobs`, we also created a tracing span and registered the "new"
job each time `CreateStartableJobWithTxn` was called, so these would
leak in the presence of restarts.

This commit adds a job ID argument to registry methods that create jobs,
so that callers can generate stable IDs. It also modifies the
`StartableJob` API to help ensure jobs (identified by a stable ID) are
only registered once in the presence of restarts:
`CreateStartableJobWithTxn` now takes a `*StartableJob`, and will not
create a tracing span and register the job again if the reference is
non-nil. This API is not ideal because it's probably easy to use it
incorrectly, but it at least makes the correct behavior on txn restarts
possible.

Closes #57492

Release note: None

----

jobs: remove workaround for tracing span leak in registry

This reverts the workaround added in
3ae0f0638a7a8e2b5911ef57f88aa8494f2ac06c to close the tracing span
for job resumers prematurely to avoid a leak.

Related to #60671.

Release note: None

### CODE REVIEW

**Comment by lucy-zhang** [comment]
@tbg I ran `make stress PKG=./pkg/ccl/backupccl/ TESTS=TestConcurrentBackupRestores` (per https://github.com/cockroachdb/cockroach/issues/60671#issuecomment-780835710) and got no failures in 4000 runs on my gceworker. I think this should unblock tracing. I'll leave the issue open, though, since the API is still just as bad.

**Review by ajwerner — COMMENTED** [review]
> Reviewed 29 of 29 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60714)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @miretskiy)

___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 360 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60714#-MUC0GsqB31xXfo3Kwe2:-MUC0GsqB31xXfo3Kwe3:b-k1w6b9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b080a9863a0b50c77d4ffc0004b0f66151fe732/pkg/ccl/changefeedccl/changefeed_stmt.go#L360)):*
> ```
> 				ptr := jobsprotectedts.MakeRecord(protectedTimestampID, jobID,
> 					statementTime, spansToProtect)
> ```
You don't need to do it but one nice thing this enables is that we can construct this record above the closure. The reason the code is structured with this separated closure is at least in part because of the awkwardness of needing to inject the job ID inside the transaction.
___
*[pkg/jobs/registry.go, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60714#-MUBwk-b9Y58sb0gZDaD:-MUBwk-b9Y58sb0gZDaE:bf8xsgr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef8568a9cae15f23b2f390cb68fd74b1ac3d161d/pkg/jobs/registry.go#L289)):*
> ```Go
> }
> 
> // CreateAndStartJobTesting creates and asynchronously starts a job from record.
> ```

nit: we tend to prefix these with `Testing` so `TestingCreateAndStartJob`
___
*[pkg/jobs/registry.go, line 520 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60714#-MUC-GM70deIhSVZsBmY:-MUC-GM70deIhSVZsBmZ:bvqb6yj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef8568a9cae15f23b2f390cb68fd74b1ac3d161d/pkg/jobs/registry.go#L520)):*
> ```Go
> 	ctx context.Context, sj *StartableJob, jobID int64, txn *kv.Txn, record Record,
> ) (*StartableJob, error) {
> 	alreadyInitialized := sj != nil
> ```

can you assert that the id inside the job inside the sj (if `alreadyInitialized`) is equal to `jobID`?

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60714)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @miretskiy)

___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 360 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60714#-MUC0GsqB31xXfo3Kwe2:-MUEac8585C_bvfdGJel:br2xpbj) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b080a9863a0b50c77d4ffc0004b0f66151fe732/pkg/ccl/changefeedccl/changefeed_stmt.go#L360)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 				ptr := jobsprotectedts.MakeRecord(protectedTimestampID, jobID,
> 					statementTime, spansToProtect)
> ```
You don't need to do it but one nice thing this enables is that we can construct this record above the closure. The reason the code is structured with this separated closure is at least in part because of the awkwardness of needing to inject the job ID inside the transaction.
</blockquote></details>

Done. I'm not sure I follow why there was a separate closure defined, but I inlined it.
___
*[pkg/jobs/registry.go, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60714#-MUBwk-b9Y58sb0gZDaD:-MUEalHe2L8zkTFYsT6U:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef8568a9cae15f23b2f390cb68fd74b1ac3d161d/pkg/jobs/registry.go#L289)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: we tend to prefix these with `Testing` so `TestingCreateAndStartJob`
</blockquote></details>

Done.
___
*[pkg/jobs/registry.go, line 520 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60714#-MUC-GM70deIhSVZsBmY:-MUEam2_-XIb-K1ziamO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef8568a9cae15f23b2f390cb68fd74b1ac3d161d/pkg/jobs/registry.go#L520)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

can you assert that the id inside the job inside the sj (if `alreadyInitialized`) is equal to `jobID`?
</blockquote></details>

Done.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60714)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/jobs/registry.go, line 520 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60714#-MUC-GM70deIhSVZsBmY:-MUEq9_d-sRkIyXYpMvh:bmn1ff5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef8568a9cae15f23b2f390cb68fd74b1ac3d161d/pkg/jobs/registry.go#L520)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I have to say it's strange to pass in sj and return sj as well... Can we do something better?

**Review by thoszhang — COMMENTED** [review]
@ajwerner do you have any idea, off the top of your head, what is going on with the newly failing changefeed tests on this branch (https://teamcity.cockroachdb.com/viewLog.html?buildId=2709636&buildTypeId=Cockroach_UnitTests)? I just rebased, so I probably picked up some changes on master, but I don't see anything that would obviously have caused this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60714#-:-MUExmQyCe4gknA-7D_5:b-6thygf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/jobs/registry.go, line 520 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60714#-MUC-GM70deIhSVZsBmY:-MUEvE9iDInkfTciI4js:bfmqwkd) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef8568a9cae15f23b2f390cb68fd74b1ac3d161d/pkg/jobs/registry.go#L520)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I have to say it's strange to pass in sj and return sj as well... Can we do something better?
</blockquote></details>

Do you have a proposal? I see the main difficulty as keeping track of the existing tracing span on restarts. I think we could avoid returning the `*StartableJob` if we require callers to allocate it themselves and then always mutate the existing one. Is that more palatable to you?

There are also more significant changes we could make, but honestly I'm eager to unblock tracing for jobs.

@ajwerner and I think that the best long-term solution for the `StartableJob` API is to add hooks prior to committing a transaction and when cleaning up an uncommitted transaction's state, so that callers don't have to deal with managing this state manually. We could write up an issue for further discussion and work.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60714)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/jobs/registry.go, line 520 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60714#-MUC-GM70deIhSVZsBmY:-MUEzpqLBMF9H2gVsFpX:bz7kit1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef8568a9cae15f23b2f390cb68fd74b1ac3d161d/pkg/jobs/registry.go#L520)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Do you have a proposal? I see the main difficulty as keeping track of the existing tracing span on restarts. I think we could avoid returning the `*StartableJob` if we require callers to allocate it themselves and then always mutate the existing one. Is that more palatable to you?

There are also more significant changes we could make, but honestly I'm eager to unblock tracing for jobs.

@ajwerner and I think that the best long-term solution for the `StartableJob` API is to add hooks prior to committing a transaction and when cleaning up an uncommitted transaction's state, so that callers don't have to deal with managing this state manually. We could write up an issue for further discussion and work.
</blockquote></details>

@lucy-zhang How about

```
func (r *Registry) CreateStartableJobWithTxn(
	ctx context.Context, sj **StartableJob, jobID int64, txn *kv.Txn, record Record,
) error {
...
```

**Review by thoszhang — COMMENTED** [review]
Never mind, I was too zealous in rearranging. Should be fixed now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60714#-:-MUF8tiC02j62_7LSAkw:b-idsz19)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/jobs/registry.go, line 520 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60714#-MUC-GM70deIhSVZsBmY:-MUFA7grA0jN7RilEzn2:b-pk7itj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef8568a9cae15f23b2f390cb68fd74b1ac3d161d/pkg/jobs/registry.go#L520)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

@lucy-zhang How about

```
func (r *Registry) CreateStartableJobWithTxn(
	ctx context.Context, sj **StartableJob, jobID int64, txn *kv.Txn, record Record,
) error {
...
```


</blockquote></details>

Done. I think this is an improvement.

**Review by miretskiy — COMMENTED** [review]
I'll let @ajwerner to be final arbiter on lg... 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60714#-:-MUFDFEzA-laS0onHpfU:bgtopbn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60714)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @lucy-zhang)

___
*[pkg/jobs/registry.go, line 293 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/60714#-MUFOOk45zDqXxTUzlkg:-MUFOOk45zDqXxTUzlkh:b-e26a5x) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbb84a3ddea180e51ca5c7f3fb971a74e098e888/pkg/jobs/registry.go#L293)):*
> ```Go
> // RegisterConstructor. The ctx passed to this function is not the context the
> // job will be started with (canceling ctx will not cause the job to cancel).
> func (r *Registry) TestingCreateAndStartJob(
> ```

I wonder... can we move this function to testutils file, and possibly change it to take registry as an argument?
(personal preference not to have testing function on a real implementation)

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60714)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @miretskiy)

___
*[pkg/jobs/registry.go, line 293 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/60714#-MUFOOk45zDqXxTUzlkg:-MUFl1BdCXKzrJRarPE9:b9bid4m) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbb84a3ddea180e51ca5c7f3fb971a74e098e888/pkg/jobs/registry.go#L293)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I wonder... can we move this function to testutils file, and possibly change it to take registry as an argument?
(personal preference not to have testing function on a real implementation)
</blockquote></details>

I converted it to a function but left it in this file, since it wasn't clear to me what other file it should go in. testutils_test.go seems to only have unexported stuff related to scheduled jobs. I'll move it there if you want. (I don't think moving to the `jobutils` package is an option since it would have to import `jobs`....)

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 14 of 15 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 8 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60714#-:-MUFqKBY6auXnz5t6w94:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @miretskiy)

**Review by miretskiy — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60714)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[pkg/jobs/registry.go, line 293 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/60714#-MUFOOk45zDqXxTUzlkg:-MUFsATE3xdOfCNo4ODZ:bpta4dd) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbb84a3ddea180e51ca5c7f3fb971a74e098e888/pkg/jobs/registry.go#L293)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

I converted it to a function but left it in this file, since it wasn't clear to me what other file it should go in. testutils_test.go seems to only have unexported stuff related to scheduled jobs. I'll move it there if you want. (I don't think moving to the `jobutils` package is an option since it would have to import `jobs`....)
</blockquote></details>

Thanks! That's perfect.

**Comment by lucy-zhang** [comment]
TFTRs

bors r+

**Pull request merged**
