### PR TITLE
acceptance test: let v2.0 node join v1.1 cluster in TestVersionUpgrade

### PR DESCRIPTION
**Pull request by ghost**
Added a step in TestVersionUpgrade that tests a node running v2.0 can join a
cluster with version v1.1.

Fixes: #24248.
Release note: None

### CODE REVIEW

**Comment by windchan7** [comment]
ping! @tschottdorf

**Comment by benesch** [comment]
Hmm, by my read of #24248 @tschottdorf intended for this to go in the version roachtest, not this acceptance test. Definitely doesn't hurt to have coverage in both places, though. Left a comment below.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[pkg/acceptance/version_upgrade_test.go, line 248 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25116#-LBNjvS61GsIMUUtrFoR:-LBNjvS7EIfJWTt1YMQ5:b2x5qdm) ([raw file](https://github.com/cockroachdb/cockroach/blob/70c2ee1896cb3e532e83d2f6d934144867945da8/pkg/acceptance/version_upgrade_test.go#L248)):*
> ```Go
> 	// this should all be pushed to nightly migration tests instead.
> 	time.Sleep(1 * time.Second)
> }
> ```

Hmm, this is a lot of duplicated code. I think it would be cleaner if you changed the type of `binaryVersionUpgrade` from `string` to a struct:

```go
type binaryVersionUpgrade struct {
  newVersion string

  // The node to run the upgrade on. If unset, runs on all nodes.
  nodes       []int
}
```

Then adjust the loop in `binaryVersionUpgrade.run` appropriately.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25116#-:-LBNlqkU0UGnkPw5WENS:b-tdp1m2)*

**Comment by windchan7** [comment]
@benesch Tobi and I had a discussion offline and decided to add the test logic to this acceptance test. It's mainly because the version roachtest now has a base version of 2.0 instead of 1.1. So it's no longer applicable.

**Comment by benesch** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/acceptance/version_upgrade_test.go, line 248 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25116#-LBNjvS61GsIMUUtrFoR:-LBRTQiy78kK6qJB9_7Y:b4672g) ([raw file](https://github.com/cockroachdb/cockroach/blob/70c2ee1896cb3e532e83d2f6d934144867945da8/pkg/acceptance/version_upgrade_test.go#L248)):*
<details><summary><i>Previously, windchan7 (Victor Chen) wrote…</i></summary><blockquote>

Done. Indeed I need to learn to refactor cockroach code!
</blockquote></details>

That's what code reviews are for!

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25116#-:-LBRThGX8GPHd-Zrphsg:bnfp4nl)*

**Comment by tschottdorf** [comment]
Sorry for not taking a look sooner! If my reading of this code is correct, this isn't doing the right thing. What we need is for a sparkling new 2.0 node to join a 1.1 cluster. This test still only seems to upgrade nodes that keep their data directories. We need to add a fresh node with the 2.0 binary to the existing 1.1 cluster at some point.

> Hmm, by my read of #24248 @tschottdorf intended for this to go in the version roachtest, not this acceptance test. Definitely doesn't hurt to have coverage in both places, though. Left a comment below.

As we discussed in this weeks CF&S weekly, we generally want all the non-docker acceptance tests to live in `roachtest` at some point. However, I don't think we want to put stuff into roachtest until that actually runs on every CI (in local mode). In this particular one it was just more convenient to add it here.

**Pull request merged**
