### PR TITLE
rpc: Measure inter-node round trip latency of heartbeats

### PR DESCRIPTION
**Pull request by a-robinson**
Will be used to inform locality-based leaseholder placement, as
described in docs/RFCs/leaseholder_locality.md

@tamird @petermattis

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13533)

### CODE REVIEW

**Comment by a-robinson** [comment]
cc #13232

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/rpc/clock_offset.go, line 67 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13533#-Kch6Ml9CluLWPvcnuRr:-Kch6Ml9CluLWPvcnuRs:b-ghyms2) ([raw file](https://github.com/cockroachdb/cockroach/blob/865b98e9cc14a80acb9e3d2363289002eccc7756/pkg/rpc/clock_offset.go#L67)):*
> ```Go
> 		syncutil.Mutex
> 		offsets   map[string]RemoteOffset
> 		latencies map[string]ewma.MovingAverage
> ```

this name should indicate the units

---

*[pkg/rpc/clock_offset.go, line 142 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13533#-Kch6QbOpcr3TwKVeHV9:-Kch6QbOpcr3TwKVeHVA:b-4y6xsw) ([raw file](https://github.com/cockroachdb/cockroach/blob/865b98e9cc14a80acb9e3d2363289002eccc7756/pkg/rpc/clock_offset.go#L142)):*
> ```Go
> 			r.mu.latencies[addr] = latencyAvg
> 		}
> 		latencyAvg.Add(float64(roundTripLatency))
> ```

.Nanoseconds() for clarity

---

*[pkg/rpc/clock_offset.go, line 203 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13533#-Kch6baWTTxhoZLzVsRo:-Kch6baXvs7W5czbP-KU:b-rxxwut) ([raw file](https://github.com/cockroachdb/cockroach/blob/865b98e9cc14a80acb9e3d2363289002eccc7756/pkg/rpc/clock_offset.go#L203)):*
> ```Go
> 			return err
> 		}
> 		r.metrics.LatencyMeanNanos.Update(int64(meanLatency))
> ```

move this below the error check below

---

*[pkg/rpc/clock_offset_test.go, line 232 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13533#-Kch74O-wpBZVmBw0bB4:-Kch74O0zYLQeBinCBC3:b-f35zf7) ([raw file](https://github.com/cockroachdb/cockroach/blob/865b98e9cc14a80acb9e3d2363289002eccc7756/pkg/rpc/clock_offset_test.go#L232)):*
> ```Go
> 		monitor.mu.Lock()
> 		if l, ok := monitor.mu.latencies[key]; !ok {
> 			t.Errorf("missing latency measurement for test %q", key)
> ```

prefix with %q: for consistency with the next case or use subtests

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13533#-:-Kch7FMNpm9uYgD-EX-E:bnfp4nl)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 2 of 4 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/rpc/clock_offset.go, line 41 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13533#-Kck1hHU6nvcxs3RMziH:-Kck1hHU6nvcxs3RMziI:bjknr7b) ([raw file](https://github.com/cockroachdb/cockroach/blob/865b98e9cc14a80acb9e3d2363289002eccc7756/pkg/rpc/clock_offset.go#L41)):*
> ```Go
> 	ClockOffsetStdDevNanos *metric.Gauge
> 	LatencyMeanNanos       *metric.Gauge
> 	LatencyStdDevNanos     *metric.Gauge
> ```

I wonder how useful having metrics for the mean and stddev for latency will be. The per-remote latency numbers seem useful, but the average across all the remotes seems strange, especially in multi-datacenter deployments. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13533#-:-Kck27J4uXmKuc-9gxIN:bnfp4nl)*

**Comment by a-robinson** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/rpc/clock_offset.go, line 41 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13533#-Kck1hHU6nvcxs3RMziH:-KcpvxIvQJmFFw3_1NI3:bod9k7m) ([raw file](https://github.com/cockroachdb/cockroach/blob/865b98e9cc14a80acb9e3d2363289002eccc7756/pkg/rpc/clock_offset.go#L41)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I wonder how useful having metrics for the mean and stddev for latency will be. The per-remote latency numbers seem useful, but the average across all the remotes seems strange, especially in multi-datacenter deployments. 
</blockquote></details>

It's true that it won't be particularly meaningful in multi-DC deployments, but our metrics package isn't flexible enough to do anything significantly more informative here. We could use a histogram to get somewhat more fidelity, but it won't indicate which nodes are responsible for the which measurements.

I've removed the metric for now. I'd switch to a Histogram, but plumbing the recently-added `HistogramWindowInterval` down in all the tests that set up an `rpc.Context` gets ugly really quick. It wouldn't be so bad if it was part of the `base.Config` (instead of `server.Config`), which already gets passed down into the rpc package. cc @mrtracy for an opinion on moving it or on other suggestions, since it's not clear how permanent the `HistogramWindowInterval` option is.

---

*[pkg/rpc/clock_offset.go, line 67 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13533#-Kch6Ml9CluLWPvcnuRr:-KcpwrAPMWiUU2GHJY37:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/865b98e9cc14a80acb9e3d2363289002eccc7756/pkg/rpc/clock_offset.go#L67)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this name should indicate the units
</blockquote></details>

Done.

---

*[pkg/rpc/clock_offset.go, line 142 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13533#-Kch6QbOpcr3TwKVeHV9:-KcpwvQ2rUhYnYBXgzPI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/865b98e9cc14a80acb9e3d2363289002eccc7756/pkg/rpc/clock_offset.go#L142)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

.Nanoseconds() for clarity
</blockquote></details>

Done.

---

*[pkg/rpc/clock_offset.go, line 203 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13533#-Kch6baWTTxhoZLzVsRo:-Kcpx5lvHUX2qpBmHVuP:b-9xsykr) ([raw file](https://github.com/cockroachdb/cockroach/blob/865b98e9cc14a80acb9e3d2363289002eccc7756/pkg/rpc/clock_offset.go#L203)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

move this below the error check below
</blockquote></details>

Done for the clock offset mean. Not very relevant for latency after removing the metrics due to @petermattis's comment.

---

*[pkg/rpc/clock_offset_test.go, line 232 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13533#-Kch74O-wpBZVmBw0bB4:-KcpxW_OthiKHPbeWviL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/865b98e9cc14a80acb9e3d2363289002eccc7756/pkg/rpc/clock_offset_test.go#L232)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

prefix with %q: for consistency with the next case or use subtests
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13533)*

**Comment by tamird** [comment]
Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13533)*

**Comment by a-robinson** [comment]
Review status: 2 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/rpc/clock_offset.go, line 41 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13533#-Kck1hHU6nvcxs3RMziH:-Kd2GEYbY1CIr4Ikbzl8:b39e78j) ([raw file](https://github.com/cockroachdb/cockroach/blob/865b98e9cc14a80acb9e3d2363289002eccc7756/pkg/rpc/clock_offset.go#L41)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

It's true that it won't be particularly meaningful in multi-DC deployments, but our metrics package isn't flexible enough to do anything significantly more informative here. We could use a histogram to get somewhat more fidelity, but it won't indicate which nodes are responsible for the which measurements.

I've removed the metric for now. I'd switch to a Histogram, but plumbing the recently-added `HistogramWindowInterval` down in all the tests that set up an `rpc.Context` gets ugly really quick. It wouldn't be so bad if it was part of the `base.Config` (instead of `server.Config`), which already gets passed down into the rpc package. cc @mrtracy for an opinion on moving it or on other suggestions, since it's not clear how permanent the `HistogramWindowInterval` option is.
</blockquote></details>

Reworked to add in a latency histogram after confirming with @mrtracy that `HistogramWindowInterval` isn't permanent and should only be around for about a month longer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13533)*

**Pull request merged**
