### PR TITLE
sql/pgwire: correctly encode and decode empty arrays

### LINKED ISSUE #42942: pgwire invalid empty array decoding
**Describe the problem**

PostgreSQL will happily decode a 0-dimensional array which does not have a dimsize and lower bound (the last 2 bytes of the array header). For example, `[0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 23]` is acceptable for an empty int4 array in postgresql. However, this fails in CockroachDB (you get an EOF error).

I couldn't figure out how to write a test to send arbitrary bytes, but I'm pretty sure the error happens because of the last two fields in the `hdr` structure and the subsequent call to `binary.Read` https://github.com/cockroachdb/cockroach/blob/2c3ade727e6db5f8eee0d6dfbe53e237d3e2437e/pkg/sql/pgwire/pgwirebase/encoding.go#L741

The solution would be to remove these two fields, and only read them if Ndims > 0

**To Reproduce**

You need a driver that generates the concise array format. I ran into this with the elixir Postgrex driver (my PR has been accepted to "fix" this on the driver side). But using a version that doesn't have this fix (v0.15.2 or before), `Postgrex.query!(pid, "select $1", [[]])` causes the error.

**Expected behavior**
Error: Get an EOF error
Expected: Parser to be consistent with postgres 

**Additional context**
Any driver that encodes an empty array using a concise binary format will be unusable

Postgrex workaround: https://github.com/elixir-ecto/postgrex/commit/d887ed813f437aa630ef9be0d047a0f20ecdd95e

### PR DESCRIPTION
**Pull request by madelynnblue**
Empty arrays don't have any dimension parts.

Fixes #42942

Release note (bug fix): Empty arrays are now correctly encoded and decode
over the binary protocol.

### CODE REVIEW

**Review by otan — APPROVED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42949)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson and @otan)

___
*[pkg/sql/pgwire/types.go, line 461 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42949#-LvHBKOsEPQ6FhjOuOCk:-LvHBKOsEPQ6FhjOuOCl:b-w2ygxo) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b2b9690938e74d03b6b65f23ad4f24daeba9470/pkg/sql/pgwire/types.go#L461)):*
> ```Go
> 		subWriter := newWriteBuffer(nil /* bytecount */)
> 		// Put the number of dimensions. We currently support 1d arrays only.
> 		var ndims int32 = 1
> ```

question: do we prefer this style over `ndims := int32(1)`?

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42949)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dbist and @otan)

___
*[pkg/sql/pgwire/types.go, line 461 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42949#-LvHBKOsEPQ6FhjOuOCk:-LvHEHRq-l6PU9Gx3_fP:blb0yvp) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b2b9690938e74d03b6b65f23ad4f24daeba9470/pkg/sql/pgwire/types.go#L461)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

question: do we prefer this style over `ndims := int32(1)`?
</blockquote></details>

either is fine. i just like this one more.

**Review by dbist — APPROVED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42949)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

**Pull request merged**
