### PR TITLE
sql: desugar TEXT to STRING

### PR DESCRIPTION
**Pull request by knz**
First commits from #28949 and priors.
Forked off from #28690.

The distinction between "TEXT" and "STRING" inside CockroachDB is
inconsequential. Remove it. The data type is already properly reported
in pg_catalog and information_schema as "text".

Release note: None

### CODE REVIEW

**Review by BramGruneir — APPROVED** [review]
:lgtm: Just some questions on leaving in tests for TEXT.

> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, 18 of 18 files at r3, 2 of 2 files at r4, 7 of 7 files at r5, 3 of 3 files at r6, 13 of 13 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28950#-:-LKYHNNL2tOCC6e66FeV:bpy4cpv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/ccl/importccl/read_import_pgdump_test.go, line 126 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/28950#-LKYGmdO1GWIAdLRVzV0:-LKYGmdP6UCETFlKuXVW:b-hfbm4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/73136f9f8cbcfa7832334cff847afee44d77497b/pkg/ccl/importccl/read_import_pgdump_test.go#L126)):*
> ```Go
> 		fmt.Fprintf(&sb, "%s;\n", s)
> 	}
> 	const expect = `CREATE TABLE public.second (i INTEGER NOT NULL, s STRING);
> ```

Does pgdump ever dump a TEXT column?  If so, this should still be tested.
___
*[pkg/sql/sem/tree/col_types_test.go, line 57 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/28950#-LKYH2Ip68esd_mEwaF1:-LKYH2Ip68esd_mEwaF2:b83x83z) ([raw file](https://github.com/cockroachdb/cockroach/blob/00f3f5de729ce9e9a1664f431a40fe1adc149c75/pkg/sql/sem/tree/col_types_test.go#L57)):*
> ```Go
> 		{"VARCHAR", &coltypes.TString{Name: "VARCHAR"}},
> 		{"CHAR(11)", &coltypes.TString{Name: "CHAR", N: 11}},
> 		{"TEXT", &coltypes.TString{Name: "TEXT"}},
> ```

Shouldn't this now just report STRING instead?  Why remove the test and not just fix the expected?
___
*[pkg/sql/sem/tree/testdata/pretty/join1.align-deindent.golden, line 1 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/28950#-LKYHDIb1E_zbQagYSLG:-LKYHDIb1E_zbQagYSLH:bwtkem8) ([raw file](https://github.com/cockroachdb/cockroach/blob/00f3f5de729ce9e9a1664f431a40fe1adc149c75/pkg/sql/sem/tree/testdata/pretty/join1.align-deindent.golden#L1)):*
> ```
> 1:
> ```

We need to mark this file as auto-generated somehow.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28950)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/ccl/importccl/read_import_pgdump_test.go, line 126 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/28950#-LKYGmdO1GWIAdLRVzV0:-LKaGyn1DLxrEGF1VmgU:be80yc8) ([raw file](https://github.com/cockroachdb/cockroach/blob/73136f9f8cbcfa7832334cff847afee44d77497b/pkg/ccl/importccl/read_import_pgdump_test.go#L126)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Does pgdump ever dump a TEXT column?  If so, this should still be tested.
</blockquote></details>

This is tested, the input SQL uses `text` as type; we're verifying here that it is desugared to string.
___
*[pkg/sql/sem/tree/col_types_test.go, line 57 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/28950#-LKYH2Ip68esd_mEwaF1:-LKaH89f9ypSNteOXVQ0:b21uede) ([raw file](https://github.com/cockroachdb/cockroach/blob/00f3f5de729ce9e9a1664f431a40fe1adc149c75/pkg/sql/sem/tree/col_types_test.go#L57)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Shouldn't this now just report STRING instead?  Why remove the test and not just fix the expected?
</blockquote></details>

No, CHAR is now a separate type from TEXT/STRING (and also separate from VARCHAR, and separate from `"char"`).
___
*[pkg/sql/sem/tree/testdata/pretty/join1.align-deindent.golden, line 1 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/28950#-LKYHDIb1E_zbQagYSLG:-LKaHEA73JCnBTGMFK7X:bkft9jh) ([raw file](https://github.com/cockroachdb/cockroach/blob/00f3f5de729ce9e9a1664f431a40fe1adc149c75/pkg/sql/sem/tree/testdata/pretty/join1.align-deindent.golden#L1)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

We need to mark this file as auto-generated somehow.
</blockquote></details>

Agreed. Done.

**Comment by knz** [comment]
bors just detected a legitimate merge skew! good bors

bors r+

**Pull request merged**
