### PR TITLE
opt/constraint: allow column directions

### PR DESCRIPTION
**Pull request by RaduBerinde**
The index constraints code will use the new primitives from the
constraints package; we need to generalize the code a bit to allow
descending indexes. We also need to export more functionality - the
index selection code will need to create Constraints.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Thinking maybe OrderingColumn should be renamed to something more general. `DirectionalColumn`?

**Comment by andy-kimball** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/constraint/constraint.go, line 53 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23887#-L7eySSpjN9P9C051mer:-L7eySSpjN9P9C051mes:b-jbiv5g) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b3730672ad3896d6c8fc844d4f21330e56fd735/pkg/sql/opt/constraint/constraint.go#L53)):*
> ```Go
> 
> // Init initializes a Constraint on the given columns with a single span.
> func (c *Constraint) Init(cols []opt.OrderingColumn, sp *Span) {
> ```

re: our discussion, we shouldn't need to export this right now (pending perf analysis)

---

*[pkg/sql/opt/constraint/key.go, line 150 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23887#-L7ez7l7pTGcJszhmE8X:-L7ez7l7pTGcJszhmE8Y:big5l4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b3730672ad3896d6c8fc844d4f21330e56fd735/pkg/sql/opt/constraint/key.go#L150)):*
> ```Go
> //   [... - /1/2] (inclusive end key)  : ExtendHigh: /1/2/High
> //   [... - /1/2) (exclusive end key)  : ExtendLow : /1/2/Low
> func (c KeyContext) Compare(k Key, kext KeyExtension, l Key, lext KeyExtension) int {
> ```

I think we should only push the value comparison into `KeyContext`:

`func (c KeyContext) Compare(left, right tree.Datum) int`

I think I may have miscommunicated about that before.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23887)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/opt/constraint/constraint.go, line 53 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23887#-L7eySSpjN9P9C051mer:-L7fHYDAhBvOrfaHBBVy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b3730672ad3896d6c8fc844d4f21330e56fd735/pkg/sql/opt/constraint/constraint.go#L53)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

re: our discussion, we shouldn't need to export this right now (pending perf analysis)
</blockquote></details>

Done.

---

*[pkg/sql/opt/constraint/key.go, line 150 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23887#-L7ez7l7pTGcJszhmE8X:-L7fHZslBpA7ZPQEDtcJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b3730672ad3896d6c8fc844d4f21330e56fd735/pkg/sql/opt/constraint/key.go#L150)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I think we should only push the value comparison into `KeyContext`:

`func (c KeyContext) Compare(left, right tree.Datum) int`

I think I may have miscommunicated about that before.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23887)*

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23887#-:-L7fMpuThIhFqTAPOlzX:bnfp4nl)*

**Pull request merged**
