### PR TITLE
protectedts,storage,server: finish plumbing for the protected timestamp subsystem

### PR DESCRIPTION
**Pull request by ajwerner**
These commits represent the currently unmerged portion of the basic protected timestamp subsystem.

* The first commit adds a `protectedts.Provider` implementation to encapsulate the subsystem.
* The second commit constructs the provider and plumbs it through to the storage layer.
* The third commit is an end-to-end test in the storage package
    * This test is relatively slow. It certainly isn't the slowest test out there but it does take ~7s.

After these merge the remaining steps for the project on the whole are:

* Adoption in jobs
     * IMPORT INTO
     * Index backfills
     * CDC table scans due to initial startup and schema changes
     * Backups
* Background reconciliation mechanism between jobs and protected timestamps
* Metrics
* Add an interval tree to the `Cache` to make `Iterate` more efficient
* Memory monitoring
    * Not obviously that important given the entire subsystem should consume less than 1MB

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43743)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/storage/client_protectedts_test.go, line 43 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-LyBMQan-S5a3oNJsSwx:-LyBMQan-S5a3oNJsSwy:b-p1e4re) ([raw file](https://github.com/cockroachdb/cockroach/blob/026ffc5d0dcfe9cb7c5601cfe2d45106b9b13fa5/pkg/storage/client_protectedts_test.go#L43)):*
> ```Go
> // nevertheless it's a useful test.
> //
> // TODO(ajwerner): Make this test cheaper or skip it.
> ```

Want to at least skip it when `testing.Short()`?
___
*[pkg/storage/client_protectedts_test.go, line 162 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-LyBPuH27O6yctvizITf:-LyBPuH27O6yctvizITg:b-1ydthz) ([raw file](https://github.com/cockroachdb/cockroach/blob/026ffc5d0dcfe9cb7c5601cfe2d45106b9b13fa5/pkg/storage/client_protectedts_test.go#L162)):*
> ```Go
> 	// Verify that it indeed did fail.
> 	verifyErr := ptv.Verify(ctx, failedRec.ID)
> 	require.True(t, testutils.IsError(verifyErr, "failed to verify protection"),
> ```

Out of curiosity, why not `require.Regexp`?
___
*[pkg/storage/client_protectedts_test.go, line 166 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-LyBQ9d_EsQ7_z4NDhXS:-LyBQ9d_EsQ7_z4NDhXT:b-8rxdnn) ([raw file](https://github.com/cockroachdb/cockroach/blob/026ffc5d0dcfe9cb7c5601cfe2d45106b9b13fa5/pkg/storage/client_protectedts_test.go#L166)):*
> ```Go
> 
> 	// Release the record that had succeeded and ensure that GC eventually
> 	// happens.
> ```

This test seems to be relying on the fact that a protected timestamp will block all GC, but that's not really the contract of protected timestamps, right? The contract is only that it won't allow GC above the protected timestamp. So isn't that what we should be testing? Concretely, shouldn't we test that we can now GC past what was previously protected here?

**Review by ajwerner — COMMENTED** [review]
Posted #43946 to deal with the comments

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-:-LyWOo-iAAcNQCNtc4mr:bsrp7qb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/storage/client_protectedts_test.go, line 166 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-LyBQ9d_EsQ7_z4NDhXS:-LyUVqwG8wKwa7LdAopn:b6obpma) ([raw file](https://github.com/cockroachdb/cockroach/blob/026ffc5d0dcfe9cb7c5601cfe2d45106b9b13fa5/pkg/storage/client_protectedts_test.go#L166)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This test seems to be relying on the fact that a protected timestamp will block all GC, but that's not really the contract of protected timestamps, right? The contract is only that it won't allow GC above the protected timestamp. So isn't that what we should be testing? Concretely, shouldn't we test that we can now GC past what was previously protected here?
</blockquote></details>

Yes, this is a major shortcoming of the code right now. Currently we bail out of shouldQueue prior to looking at the score. It is the scoring which is responsible for aging the bytes. 

Probably instead what the code should do is determine the latest new threshold allowed under the protected timestamp and then age the MVCC stats to that point and make a determination. 

I'm adding a new commit for the purpose of this.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43743)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/client_protectedts_test.go, line 43 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-LyBMQan-S5a3oNJsSwx:-LziOUtrA5JrEGNAfh9B:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/026ffc5d0dcfe9cb7c5601cfe2d45106b9b13fa5/pkg/storage/client_protectedts_test.go#L43)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Want to at least skip it when `testing.Short()`?
</blockquote></details>

Done.
___
*[pkg/storage/client_protectedts_test.go, line 162 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-LyBPuH27O6yctvizITf:-LziOWQyBV-KhCC_6T3U:b-b90f6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/026ffc5d0dcfe9cb7c5601cfe2d45106b9b13fa5/pkg/storage/client_protectedts_test.go#L162)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Out of curiosity, why not `require.Regexp`?
</blockquote></details>

No good reason. Done.
___
*[pkg/storage/client_protectedts_test.go, line 166 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-LyBQ9d_EsQ7_z4NDhXS:-LziTkTM2-DdtSrb5ZLr:b-pxh57k) ([raw file](https://github.com/cockroachdb/cockroach/blob/026ffc5d0dcfe9cb7c5601cfe2d45106b9b13fa5/pkg/storage/client_protectedts_test.go#L166)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Yes, this is a major shortcoming of the code right now. Currently we bail out of shouldQueue prior to looking at the score. It is the scoring which is responsible for aging the bytes. 

Probably instead what the code should do is determine the latest new threshold allowed under the protected timestamp and then age the MVCC stats to that point and make a determination. 

I'm adding a new commit for the purpose of this. 
</blockquote></details>

Okay I took a stab at addressing this. I think it works reasonably well. More testing won't hurt but I think this should be sufficient to merge. More exercise of the code will happen as I adopt. 
___
*[pkg/storage/replica_protected_timestamp.go, line 176 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-LzjdwflDWBueLJkBO1H:-Lzjdwfm7woL4Jl3B3In:bcp4k1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/69184ce76b784bebc5aad877eb99eee2a2cc7be2/pkg/storage/replica_protected_timestamp.go#L176)):*
> ```Go
> 		// rather than returning the timestamp from which we'll derive the threshold
> 		// but oh well.
> 		// XXX(ajwerner): Is it good to have a GC threshold with a maximum logical
> ```

I want to figure this out before merging. I think it's probably fine the way it is. It seems like today we generally have a GC TTL with a zero or on very rare occasions small logical portion. This will make a lot of GC TTLs look like `hlc.Timestamp{WallTime:1580273006786378275, Logical:2147483647}`

**Review by ajwerner — COMMENTED** [review]
This is RFAL. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-:-Lzn1y8I2ebuRz1gQrvk:b-n4viu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by nvb — COMMENTED** [review]
> Reviewed 4 of 4 files at r4, 4 of 4 files at r5, 2 of 2 files at r6, 1 of 5 files at r7, 7 of 7 files at r9, 5 of 5 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43743)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/storage/client_protectedts_test.go, line 166 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-LyBQ9d_EsQ7_z4NDhXS:-LzoEy0O-XoANDIACGkC:b-r61ggq) ([raw file](https://github.com/cockroachdb/cockroach/blob/026ffc5d0dcfe9cb7c5601cfe2d45106b9b13fa5/pkg/storage/client_protectedts_test.go#L166)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Okay I took a stab at addressing this. I think it works reasonably well. More testing won't hurt but I think this should be sufficient to merge. More exercise of the code will happen as I adopt. 
</blockquote></details>

Thanks, this is a nice improvement.
___
*[pkg/storage/client_protectedts_test.go, line 192 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-LzoF-Zp9c51M4KCdifK:-LzoF-Zp9c51M4KCdifL:bgxdl6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/39844e1d095c3f4c6aaa8fa4e7d75e847e6e491b/pkg/storage/client_protectedts_test.go#L192)):*
> ```Go
> 	require.Regexp(t, "failed to verify protection", verifyErr)
> 
> 	// Add a new record that is after the old record
> ```

nit: missing period.
___
*[pkg/storage/client_protectedts_test.go, line 209 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-LzoF8_E9GqnXIoK6UtK:-LzoF8_E9GqnXIoK6UtL:b-f54z21) ([raw file](https://github.com/cockroachdb/cockroach/blob/39844e1d095c3f4c6aaa8fa4e7d75e847e6e491b/pkg/storage/client_protectedts_test.go#L209)):*
> ```Go
> 			return errors.Errorf("%q does not match %q", trace.String(), processedRegexp)
> 		}
> 		require.Truef(t, ptsRec.Timestamp.Less(thresholdFromTrace(trace)), "%v >= %v",
> ```

Can we check that this is once again below the new record's timestamp?
___
*[pkg/storage/replica_protected_timestamp.go, line 149 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-LzoD10f-3fr46xCe-ak:-LzoD10g0pjVCZkznobK:b47g72i) ([raw file](https://github.com/cockroachdb/cockroach/blob/095e453af73d81c17ac0b8060f94a48047bb935f/pkg/storage/replica_protected_timestamp.go#L149)):*
> ```Go
> 	lease := *r.mu.state.Lease
> 	r.mu.RUnlock()
> 	var earliestRecord *ptpb.Record
> ```

This is the `earliestValidRecord` or something along those lines, right? Or what is the adjective you're using to represent the `gcThreshold.LessEq(rec.Timestamp)` state?
___
*[pkg/storage/replica_protected_timestamp.go, line 150 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-LzoCRnjBf8K5TqtNdW4:-LzoCRnjBf8K5TqtNdW5:b-1ci33e) ([raw file](https://github.com/cockroachdb/cockroach/blob/095e453af73d81c17ac0b8060f94a48047bb935f/pkg/storage/replica_protected_timestamp.go#L150)):*
> ```Go
> 	r.mu.RUnlock()
> 	var earliestRecord *ptpb.Record
> 	gcTimestamp = r.store.protectedtsCache.Iterate(ctx,
> ```

One thing that isn't clear to me upon a reread of this is whether the synchronization performed in `Iterate` is sufficient once we start pulling out references to `ptpb.Record`s. Are these records ever mutated internally? Either way, it's worth adding a comment to `protectedts.Cache.Iterate`.
___
*[pkg/storage/replica_protected_timestamp.go, line 169 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-LzoDy0E-omJR2oURiCy:-LzoDy0E-omJR2oURiCz:b-5za1ib) ([raw file](https://github.com/cockroachdb/cockroach/blob/095e453af73d81c17ac0b8060f94a48047bb935f/pkg/storage/replica_protected_timestamp.go#L169)):*
> ```Go
> 		// If we've already GC'd right up to this record, there's no reason to
> 		// gc again.
> 		if earliestRecord.Timestamp.Equal(gcThreshold) {
> ```

If we're always GCing up to but below (either by 1 logical tick or 1 ns) the earliest protected record's timestamp, do we expect to ever short-circuit here?
___
*[pkg/storage/replica_protected_timestamp.go, line 172 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-LzoDTg_5UL5_lCPHMXI:-LzoDTg_5UL5_lCPHMXJ:bncv0yd) ([raw file](https://github.com/cockroachdb/cockroach/blob/095e453af73d81c17ac0b8060f94a48047bb935f/pkg/storage/replica_protected_timestamp.go#L172)):*
> ```Go
> 			return false, hlc.Timestamp{}
> 		}
> 		// NB: we add the gcTTL to the timestamp here so because it will be
> ```

s/so because/because/
___
*[pkg/storage/replica_protected_timestamp.go, line 173 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-LzoDZyT3aGB1hmpvNsc:-LzoDZyT3aGB1hmpvNsd:bewto15) ([raw file](https://github.com/cockroachdb/cockroach/blob/095e453af73d81c17ac0b8060f94a48047bb935f/pkg/storage/replica_protected_timestamp.go#L173)):*
> ```Go
> 		}
> 		// NB: we add the gcTTL to the timestamp here so because it will be
> 		// subtracted later. Probably it should be this method selecting the new
> ```

"the new" what?
___
*[pkg/storage/replica_protected_timestamp.go, line 175 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-LzoDroU-Gpk8HgAze1J:-LzoDroU-Gpk8HgAze1K:bhg0u0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/095e453af73d81c17ac0b8060f94a48047bb935f/pkg/storage/replica_protected_timestamp.go#L175)):*
> ```Go
> 		// subtracted later. Probably it should be this method selecting the new
> 		// rather than returning the timestamp from which we'll derive the threshold
> 		// but oh well.
> ```

Is this a hard change? It's awfully strange to see this added here.
___
*[pkg/storage/replica_protected_timestamp_test.go, line 358 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-LzoEgP77xht3nvejEpe:-LzoEgP77xht3nvejEpf:bam74x3) ([raw file](https://github.com/cockroachdb/cockroach/blob/095e453af73d81c17ac0b8060f94a48047bb935f/pkg/storage/replica_protected_timestamp_test.go#L358)):*
> ```Go
> 					},
> 				})
> 				// We should allow gc to proceed with the normal new threshold if that
> ```

Is this comment correct?
___
*[pkg/util/hlc/timestamp.go, line 105 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-LzjpaFu17Ruwdc7EwNI:-LzjpaFu17Ruwdc7EwNJ:b-i6m17w) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e51021b501379fc9888e5e94307f4efd683bdbc/pkg/util/hlc/timestamp.go#L105)):*
> ```Go
> // ParseTimestamp attempts to parse the string generated from
> // Timestamp.String().
> func ParseTimestamp(str string) (_ Timestamp, err error) {
> ```

I remembered after our discussion today that we have code like `sql.ParseHLC` sitting around. Can we unify that logic with this?

**Review by ajwerner — COMMENTED** [review]
Thanks for the review and sorry for the sloppiness. Just minor details left. I'm going to have `checkProtectedTimestampsForGC()` return a new threshold too. I'll do that in the morning. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-:-LzowjW250s_taeNIaQI:b2yk0az)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/storage/client_protectedts_test.go, line 209 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-LzoF8_E9GqnXIoK6UtK:-LzowhN42loMYp4edywL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/39844e1d095c3f4c6aaa8fa4e7d75e847e6e491b/pkg/storage/client_protectedts_test.go#L209)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we check that this is once again below the new record's timestamp?
</blockquote></details>

Done.
___
*[pkg/storage/replica_protected_timestamp.go, line 149 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-LzoD10f-3fr46xCe-ak:-LzosAfC89Irv6y2ouPt:b-wv2yt0) ([raw file](https://github.com/cockroachdb/cockroach/blob/095e453af73d81c17ac0b8060f94a48047bb935f/pkg/storage/replica_protected_timestamp.go#L149)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is the `earliestValidRecord` or something along those lines, right? Or what is the adjective you're using to represent the `gcThreshold.LessEq(rec.Timestamp)` state?
</blockquote></details>

correct, renamed and commented.
___
*[pkg/storage/replica_protected_timestamp.go, line 150 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-LzoCRnjBf8K5TqtNdW4:-LzosCx-06Vb-ouQcP1T:bvq3lmz) ([raw file](https://github.com/cockroachdb/cockroach/blob/095e453af73d81c17ac0b8060f94a48047bb935f/pkg/storage/replica_protected_timestamp.go#L150)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

One thing that isn't clear to me upon a reread of this is whether the synchronization performed in `Iterate` is sufficient once we start pulling out references to `ptpb.Record`s. Are these records ever mutated internally? Either way, it's worth adding a comment to `protectedts.Cache.Iterate`.
</blockquote></details>

Added a comment to Iterate to state that values must never be mutated. 
___
*[pkg/storage/replica_protected_timestamp.go, line 169 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-LzoDy0E-omJR2oURiCy:-LzosR-x1Rwoq7Dfn--W:b-2ith89) ([raw file](https://github.com/cockroachdb/cockroach/blob/095e453af73d81c17ac0b8060f94a48047bb935f/pkg/storage/replica_protected_timestamp.go#L169)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

If we're always GCing up to but below (either by 1 logical tick or 1 ns) the earliest protected record's timestamp, do we expect to ever short-circuit here?
</blockquote></details>

Good catch. This needs a next. I think I need to use a `Prev()`. 
___
*[pkg/storage/replica_protected_timestamp.go, line 175 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-LzoDroU-Gpk8HgAze1J:-Lzos_0MBSl_271itVZL:b45f2zv) ([raw file](https://github.com/cockroachdb/cockroach/blob/095e453af73d81c17ac0b8060f94a48047bb935f/pkg/storage/replica_protected_timestamp.go#L175)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this a hard change? It's awfully strange to see this added here.
</blockquote></details>

I don't disagree. The awkwardness is that in `shouldQueue` and `process` we want a "now" timestamp to which to age the bytes and to report in the score. I added more words here about what I think I should do, I'll do it next. 
___
*[pkg/storage/replica_protected_timestamp_test.go, line 358 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-LzoEgP77xht3nvejEpe:-LzosySK9I8vSYRDidkg:bfwznfw) ([raw file](https://github.com/cockroachdb/cockroach/blob/095e453af73d81c17ac0b8060f94a48047bb935f/pkg/storage/replica_protected_timestamp_test.go#L358)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this comment correct?
</blockquote></details>

No, copy-pasta. Thanks
___
*[pkg/util/hlc/timestamp.go, line 105 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-LzjpaFu17Ruwdc7EwNI:-Lzot6Wv2S54a9vdp0TY:b7xcnii) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e51021b501379fc9888e5e94307f4efd683bdbc/pkg/util/hlc/timestamp.go#L105)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I remembered after our discussion today that we have code like `sql.ParseHLC` sitting around. Can we unify that logic with this?
</blockquote></details>

We represent the `hlc.Timestamp.String()` quite differently than we represent the hlc timestamp in SQL. In SQL we represent hlc timestamps as DECIMAL where the integer part is unix nanos and the fractional part represents the logical component. For example:

```
root@127.243.116.248:44759/movr> SELECT cluster_logical_timestamp();                                    
    cluster_logical_timestamp
----------------------------------
  1580361670629466905.0000000000
```

That's what `sql.ParseHLC` expects. We serialize HLC timestamps using `<seconds>.<nanos>,<logical>` elsewhere. 


I added some more commentary on the `sql` function.

**Review by ajwerner — COMMENTED** [review]
RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-:-Lzqsr_yBHwYTMlgKtPN:bb72pd0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/storage/replica_protected_timestamp.go, line 176 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-LzjdwflDWBueLJkBO1H:-LzqsiFGBf52AAKgp1kW:btthu0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/69184ce76b784bebc5aad877eb99eee2a2cc7be2/pkg/storage/replica_protected_timestamp.go#L176)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I want to figure this out before merging. I think it's probably fine the way it is. It seems like today we generally have a GC TTL with a zero or on very rare occasions small logical portion. This will make a lot of GC TTLs look like `hlc.Timestamp{WallTime:1580273006786378275, Logical:2147483647}`
</blockquote></details>

I decided it's fine. 
___
*[pkg/storage/replica_protected_timestamp.go, line 175 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-LzoDroU-Gpk8HgAze1J:-Lzqslpz-2xdP7G47hSm:b-8oj4z2) ([raw file](https://github.com/cockroachdb/cockroach/blob/095e453af73d81c17ac0b8060f94a48047bb935f/pkg/storage/replica_protected_timestamp.go#L175)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I don't disagree. The awkwardness is that in `shouldQueue` and `process` we want a "now" timestamp to which to age the bytes and to report in the score. I added more words here about what I think I should do, I'll do it next. 
</blockquote></details>

Okay, see how you feel about this.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r13, 3 of 3 files at r14, 10 of 10 files at r15, 1 of 1 files at r16.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-:-Lzr_xyE9y_a7uA5XW7c:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/storage/replica_protected_timestamp.go, line 143 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-LzrZtUaA0pNKTrU2txK:-LzrZtUaA0pNKTrU2txL:b-etmdnh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d09c70805a82c20838ec0e5a2b57e8d4ae111e94/pkg/storage/replica_protected_timestamp.go#L143)):*
> ```Go
> // for this calculation is used later.
> //
> // In the case that GC can proceed Three timestamps are returned: The timestamp
> ```

s/Three/three/
___
*[pkg/util/hlc/timestamp.go, line 105 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/43743#-LzjpaFu17Ruwdc7EwNI:-Lzr_hR-D74bZKfFV5wA:b-lg05o9) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e51021b501379fc9888e5e94307f4efd683bdbc/pkg/util/hlc/timestamp.go#L105)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

We represent the `hlc.Timestamp.String()` quite differently than we represent the hlc timestamp in SQL. In SQL we represent hlc timestamps as DECIMAL where the integer part is unix nanos and the fractional part represents the logical component. For example:

```
root@127.243.116.248:44759/movr> SELECT cluster_logical_timestamp();                                    
    cluster_logical_timestamp
----------------------------------
  1580361670629466905.0000000000
```

That's what `sql.ParseHLC` expects. We serialize HLC timestamps using `<seconds>.<nanos>,<logical>` elsewhere. 


I added some more commentary on the `sql` function.
</blockquote></details>

I see, thanks for the explanation.

**Comment by ajwerner** [comment]
bors r=nvanbenschoten

**Pull request merged**
