### PR TITLE
roachprod: Support AWS GP3 drives.

### PR DESCRIPTION
**Pull request by miretskiy**
Add support for spinning up VMs with GP3 drives.
Make it possible to specify multiple, possibly different EBS
volumes for each aws instance.

Release Notes: None

### CODE REVIEW

**Comment by knz** [comment]
cc @kenliu for triage - this should be reviewed by the dev inf team

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58275)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58275#-MR5BcW2DBjC9kl2zPhj:-MR5BcW2DBjC9kl2zPhk:b1z72n6) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd91d24cab42ea2d1b1547f5f03b1898735e632c/pkg/cmd/roachprod/vm/aws/aws.go#L90)):*
> ```Go
> 	type disk ebsDisk
> 	return json.Marshal(&struct {
> 		DeleteOnTermination bool `json:"DeleteOnTermination"`
> ```

Is this structuring used simply so that `DeleteOnTermination` is not present in `ebsDisk`? It might be slightly less awkward to used a named struct:

```
type extendedDisk struct {
  ebsDisk
  DeleteOnTermination bool ...
}
```
___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58275#-MR5DWGt8YK8fjM5F9mr:-MR5DWGt8YK8fjM5F9ms:bp2ta6r) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd91d24cab42ea2d1b1547f5f03b1898735e632c/pkg/cmd/roachprod/vm/aws/aws.go#L107)):*
> ```Go
> 	// This is not strictly needed since AWS sdk would return error anyway,
> 	// but we can return a nicer error message sooner.
> 	if d.VolumeSize == 0 {
> ```

Could we instead use the flag default for `--aws-ebs-volume-size` of 500 GB?
___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58275#-MR5CE5S1gPBPEnNl9Q9:-MR5CE5S1gPBPEnNl9QA:b-eluiuo) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd91d24cab42ea2d1b1547f5f03b1898735e632c/pkg/cmd/roachprod/vm/aws/aws.go#L115)):*
> ```Go
> 		// Nothing -- size checked above.
> 	case "gp3":
> 		if d.IOPs == 0 || d.IOPs > 16000 {
> ```

Should this be `d.IOPS < 3000`?
___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58275#-MR5CL0vB3mbr4nqQZVW:-MR5CL0vB3mbr4nqQZVX:b-454cm2) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd91d24cab42ea2d1b1547f5f03b1898735e632c/pkg/cmd/roachprod/vm/aws/aws.go#L118)):*
> ```Go
> 			return errors.AssertionFailedf("Iops required for gp3 disk: [3000, 16000]")
> 		}
> 		if d.Throughput == 0 {
> ```

Could we provide a reasonable default if throughput isn't specified?
___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 141 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58275#-MR5CYgQ3KmYqRxGHh2I:-MR5CYgQ3KmYqRxGHh2J:b-1zafox) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd91d24cab42ea2d1b1547f5f03b1898735e632c/pkg/cmd/roachprod/vm/aws/aws.go#L141)):*
> ```Go
> }
> 
> type eBSVolumeList []*ebsVolume
> ```

Nit: elsewhere you're using the capitalization `ebs`, but here you're using `eBS`. I don't have a preference except for consistency.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58275)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis)

___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58275#-MR5BcW2DBjC9kl2zPhj:-MR5Ly2A-GYPj47pJR29:brfg1ol) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd91d24cab42ea2d1b1547f5f03b1898735e632c/pkg/cmd/roachprod/vm/aws/aws.go#L90)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is this structuring used simply so that `DeleteOnTermination` is not present in `ebsDisk`? It might be slightly less awkward to used a named struct:

```
type extendedDisk struct {
  ebsDisk
  DeleteOnTermination bool ...
}
```
</blockquote></details>

Agreed... Code started off a bit more complex -- but now marshal is just as you say, to add one more attribute.  Made it explicit, as you suggested.
___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58275#-MR5DWGt8YK8fjM5F9mr:-MR5Lqib99h6KeQGTHP9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd91d24cab42ea2d1b1547f5f03b1898735e632c/pkg/cmd/roachprod/vm/aws/aws.go#L107)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Could we instead use the flag default for `--aws-ebs-volume-size` of 500 GB?
</blockquote></details>

Done.
___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58275#-MR5CE5S1gPBPEnNl9Q9:-MR5LTuF1QfTcC5fZjxO:bl017ka) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd91d24cab42ea2d1b1547f5f03b1898735e632c/pkg/cmd/roachprod/vm/aws/aws.go#L115)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Should this be `d.IOPS < 3000`?
</blockquote></details>

No, gp3 drives have minimum 3000 iops.  I changed this error condition to check for >16000 and added default 3000 IOPs if not set.
___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58275#-MR5CL0vB3mbr4nqQZVW:-MR5LQdO8Iy_TKHDFqz8:b-btdbgd) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd91d24cab42ea2d1b1547f5f03b1898735e632c/pkg/cmd/roachprod/vm/aws/aws.go#L118)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Could we provide a reasonable default if throughput isn't specified?
</blockquote></details>

Yup -- set to 125MB, which is base throughput.
___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 141 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58275#-MR5CYgQ3KmYqRxGHh2I:-MR5KuFq87e0CHvWoZ5A:bq86jqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd91d24cab42ea2d1b1547f5f03b1898735e632c/pkg/cmd/roachprod/vm/aws/aws.go#L141)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: elsewhere you're using the capitalization `ebs`, but here you're using `eBS`. I don't have a preference except for consistency. 
</blockquote></details>

Ooops -- a typo.  Changed to "ebsVolumeList" -- no need to export.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58275#-:-MR5mJMT80LQ1wZe4fuB:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by miretskiy** [comment]
tftr

**Comment by miretskiy** [comment]
bors r=petermattis

**Pull request merged**
