### PR TITLE
opt: Make TPCH schema consistent and easier to generate

### PR DESCRIPTION
**Pull request by andy-kimball**
Make TPCH schema consistent in the optimizer and workload tests, matching them to
the schema we store in Google storage (gs://cockroach-fixtures/tpch-csv). Use same
data types, not-null settings, index names, etc.

Also, create scripts to make loading TPCH tables from CSV's easier.

Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
I'm also generating new backups for the schema so that those are consistent as well.

**Review by danhhz — COMMENTED** [review]
:lgtm: thanks for picking this up

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30221#-:-LMNi7hUCj-tqeK26K05:b-s1tstd)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/workload/tpch/import-sf1.sql, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30221#-LMNhyqV5lAx6osouhd3:-LMNhyqV5lAx6osouhd4:b-x023u3) ([raw file](https://github.com/cockroachdb/cockroach/blob/95f46bc933aea352accdef8648d66b3cd19ecca3/pkg/workload/tpch/import-sf1.sql#L90)):*
> ```SQLPL
> ) WITH delimiter='|';
> 
> ALTER TABLE orders ADD CONSTRAINT orders_fkey_customer FOREIGN KEY (o_custkey) references public.customer (c_custkey);
> ```

any particular reason this one has a "public." prefix?

**Review by RaduBerinde — COMMENTED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30221#-:-LMNmFz72Qrtql21mAXu:bb6ywmx)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30221)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/workload/tpch/import-sf1.sql, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30221#-LMNhyqV5lAx6osouhd3:-LMNmzxPBPXgZvaMm2yf:bc2c1dx) ([raw file](https://github.com/cockroachdb/cockroach/blob/95f46bc933aea352accdef8648d66b3cd19ecca3/pkg/workload/tpch/import-sf1.sql#L90)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

any particular reason this one has a "public." prefix?
</blockquote></details>

Was cut and paste from somewhere else. Removed it.

**Comment by petermattis** [comment]
Feel free to rubber stamp https://github.com/cockroachdb/cockroach/pull/30253 if you want to see that CI failure fixed.

**Pull request merged**
