### PR TITLE
sql: fix racey lease test

### LINKED ISSUE #6810: circleci: failed tests: TestPurgeOldLeases
The following test appears to have failed:

[#18127](https://circleci.com/gh/cockroachdb/cockroach/18127):

```
E160519 20:25:59.145658 storage/queue.go:446  [split] range=6 [/Table/50-/Max): error: storage/split_queue.go:103: unable to split range=6 [/Table/50-/Max) at key "/Table/51/0": storage/replica_command.go:2064: split at key /Table/51 failed: node unavailable; try another peer
I160519 20:26:00.143159 /go/src/google.golang.org/grpc/clientconn.go:499  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:37408: getsockopt: connection refused"; Reconnecting to "127.0.0.1:37408"
I160519 20:26:01.567588 /go/src/google.golang.org/grpc/clientconn.go:499  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:37408: getsockopt: connection refused"; Reconnecting to "127.0.0.1:37408"
I160519 20:26:01.568134 /go/src/google.golang.org/grpc/clientconn.go:351  Failed to dial 127.0.0.1:37408: grpc: timed out trying to connect; please retry.
I160519 20:26:01.568497 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
--- FAIL: TestPurgeOldLeases (3.06s)
	lease_internal_test.go:148: found 2 leases instead of 3
=== RUN   TestNameCacheIsUpdated
W160519 20:26:01.626028 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
I160519 20:26:01.632256 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
W160519 20:26:01.636174 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
I160519 20:26:01.637370 server/node.go:401  store store=0:0 ([]=) not bootstrapped
I160519 20:26:01.645034 storage/replica_command.go:1470  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 406580h26m2.643877175s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-05-19 20:26:01.644854963 +0000 UTC]
I160519 20:26:01.645633 storage/replica.go:1524  reproposing 1 commands after empty entry
E160519 20:26:01.647609 storage/replica.go:1615  [node=1,store=1,range=1] error executing raft command: write at timestamp 1463689561.643683939,0 too old; wrote at 1463689561.643683939,1
I160519 20:26:01.648572 server/node.go:327  **** cluster {1ce91edf-ae90-4afe-bbaf-8ec260ecfe6e} has been created
--
I160519 20:29:01.169010 kv/dist_sender.go:974  application error: retry txn "sql/executor.go:420 sql txn" id=228a2eaa key=/Table/51/1/"g"/0 rw=true pri=0.00407542 iso=SERIALIZABLE stat=PENDING epo=0 ts=1463689741.081965649,0 orig=1463689741.081965649,0 max=1463689741.081965649,0 wto=false rop=false
W160519 20:29:01.169171 kv/dist_sender.go:719  failed to invoke EndTransaction [/Table/51/1/"g"/0,/Min): retry txn "sql/executor.go:420 sql txn" id=228a2eaa key=/Table/51/1/"g"/0 rw=true pri=0.00407542 iso=SERIALIZABLE stat=PENDING epo=0 ts=1463689741.081965649,0 orig=1463689741.081965649,0 max=1463689741.081965649,0 wto=false rop=false
I160519 20:29:01.169579 client/db.go:474  failed batch: retry txn "sql/executor.go:420 sql txn" id=228a2eaa key=/Table/51/1/"g"/0 rw=true pri=0.01335596 iso=SERIALIZABLE stat=PENDING epo=1 ts=1463689741.081965649,0 orig=1463689741.081965649,0 max=1463689741.131965649,0 wto=false rop=false
I160519 20:29:01.175687 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
--- PASS: TestRollbackInRestartWait (1.13s)
FAIL
FAIL	github.com/cockroachdb/cockroach/sql	183.317s
I160519 20:26:12.790986 rand.go:76  Random seed: 5117411435364211007
=== RUN   TestProcessExpression
--- PASS: TestProcessExpression (0.01s)
=== RUN   TestServer
W160519 20:26:12.834804 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
I160519 20:26:12.862682 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
W160519 20:26:12.869207 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
I160519 20:26:12.870734 server/node.go:401  store store=0:0 ([]=) not bootstrapped
I160519 20:26:12.889583 storage/replica_command.go:1470  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 406580h26m13.888032954s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-05-19 20:26:12.889276071 +0000 UTC]
I160519 20:26:12.892139 server/node.go:327  **** cluster {3eba6378-dc1b-4650-a26f-a213ef53c4df} has been created

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by andreimatei**
... by blocking gossip that wrecks havoc on leases.

Fixes #6810

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6834)

### CODE REVIEW

**Comment by vivekmenezes** [comment]
:lgtm:

<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> #### sql: fix racey lease test
> 
> ... by blocking gossip that wrecks havoc on leases.
> 
> 
> 
> Fixes #6810
> 
> 
> 
</details>


---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[sql/lease.go, line 753 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6834#-KIG0RaDhMVpj1FWq_cx:-KIG0RaDhMVpj1FWq_cy:-1592963862) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3b97b963e622176167c8f70a7c0de2c532d86fe/sql/lease.go#L753)):*
> ```Go
> 	// refreshed. Careful when using this to block for too long - you can block
> 	// all the gossip users in the system. Also keep in mind that this doesn't
> 	// synchronize with a possible current update being processed.
> ```

what do you mean by current update being processed

---

*[sql/lease_internal_test.go, line 161 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6834#-KIG0Y1uyTJPdRzLl_yo:-KIG0Y1uyTJPdRzLl_yp:-1280936503) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3b97b963e622176167c8f70a7c0de2c532d86fe/sql/lease_internal_test.go#L161)):*
> ```Go
> 	}
> 
> 	log.Infof("!!! test starting")
> ```

remove

---

*[sql/lease_internal_test.go, line 196 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6834#-KIG0pQ85m_oANIE3sLE:-KIG0pQ85m_oANIE3sLF:-218708298) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3b97b963e622176167c8f70a7c0de2c532d86fe/sql/lease_internal_test.go#L196)):*
> ```Go
> 	ts.mu.Lock()
> 	defer ts.mu.Unlock()
> 	if ts.active.data[0] != leases[2] {
> ```

better to set a boolean while the lock is held and then check it here instead of using defer above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6834#-:-KIG1SV6BU2GtSI2QSvO:1417088721)*

**Comment by bdarnell** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/lease_internal_test.go, line 139 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6834#-KIJ5KVDZUJWgGo2B3Ct:-KIJ5KVE43ZhWz2jWdk7:-1427401111) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3b97b963e622176167c8f70a7c0de2c532d86fe/sql/lease_internal_test.go#L139)):*
> ```Go
> 					mu.Lock()
> 					defer mu.Unlock()
> 					if gossipBlocked {
> ```

I think this could be simplified by using a channel as a semaphore. Replace `unblockGossip`, `mu`, and `gossipBlocked` with `gossipBlocker := make(chan struct{}, 1)`. In `GossipUpdateEvent`, do `gossipBlocker <- struct{}{}; <-gossipBlocker` to acquire and release the semaphore. In the main body of the test, do `gossipBlocker <- struct{}{}` to block gossip and `<-gossipBlocker` to unblock it. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6834)*

**Comment by andreimatei** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/lease_internal_test.go, line 139 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6834#-KIJ5KVDZUJWgGo2B3Ct:-KIZ8bkvasMJUMVO3PSb:600473809) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3b97b963e622176167c8f70a7c0de2c532d86fe/sql/lease_internal_test.go#L139)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> I think this could be simplified by using a channel as a semaphore. Replace `unblockGossip`, `mu`, and `gossipBlocked` with `gossipBlocker := make(chan struct{}, 1)`. In `GossipUpdateEvent`, do `gossipBlocker <- struct{}{}; <-gossipBlocker` to acquire and release the semaphore. In the main body of the test, do `gossipBlocker <- struct{}{}` to block gossip and `<-gossipBlocker` to unblock it. 
</details>
excellent

---

*[sql/lease_internal_test.go, line 161 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6834#-KIG0Y1uyTJPdRzLl_yo:-KIZ9DxBAtm66T-k-nTI:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3b97b963e622176167c8f70a7c0de2c532d86fe/sql/lease_internal_test.go#L161)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> remove
</details>
Done.

---

*[sql/lease_internal_test.go, line 196 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6834#-KIG0pQ85m_oANIE3sLE:-KIZ9C9Urgs1ZjVoqzOb:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3b97b963e622176167c8f70a7c0de2c532d86fe/sql/lease_internal_test.go#L196)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> better to set a boolean while the lock is held and then check it here instead of using defer above.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6834)*

**Comment by andreimatei** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/lease.go, line 753 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6834#-KIG0RaDhMVpj1FWq_cx:-KIZGfPaHQ0rk8qG1Yr1:-542800976) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3b97b963e622176167c8f70a7c0de2c532d86fe/sql/lease.go#L753)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> what do you mean by current update being processed
</details>
removed. I think this was leftover form another try and no longer makes any sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6834)*

**Pull request merged**
