### PR TITLE
c-deps: bump jemalloc to pick up Darwin deadlock fix

### LINKED ISSUE #35620: jemalloc: deadlocks under go1.12 (at least under darwin)
The following script results in a wedged single node cluster most of the time (if not immediately, then after a dozen or so seconds). I don't think that the specific script here plays a role, but it's an issue in Go 1.12 and not before.

```
#!/usr/bin/env bash
set -euo pipefail

export COCKROACH_ENGINE_MAX_SYNC_DURATION=60s

killall -9 cockroach || true
rm -rf cockroach-data* || true
#for i in 0 1 2 3; do
for i in 0; do
  ./cockroach start --vmodule=rocksdb=5 --max-offset 10ms --insecure --host 127.0.0.1 --port $((26257+i)) --http-port $((8080+i)) --background --store "cockroach-data${i}" --join 127.0.0.1:26257
  if [ $i -eq 0 ]; then ./cockroach init --insecure; fi
done
echo "
SET CLUSTER SETTING kv.range_merge.queue_enabled = false;
CREATE TABLE IF NOT EXISTS data (id INT PRIMARY KEY);
ALTER TABLE data SPLIT AT SELECT i FROM generate_series(1, 1000) AS g(i);
" | ./cockroach sql --insecure
```

I've `lldb`'ed the deadlocks to look like the following (in various C calls, they all look similar once they hit jemalloc)

```
(lldb) bt
* thread #29
  * frame #0: 0x00007fff75e2c36a libsystem_kernel.dylib`__ulock_wait + 10
    frame #1: 0x00007fff75ed8c57 libsystem_platform.dylib`_os_unfair_lock_lock_slow + 140
    frame #2: 0x0000000005fd3bbb cockroach`je_arena_choose_hard [inlined] je_malloc_mutex_lock at mutex.h:97 [opt]
    frame #3: 0x0000000005fd3baf cockroach`je_arena_choose_hard at jemalloc.c:614 [opt]
    frame #4: 0x000000000601d106 cockroach`je_tcache_get_hard [inlined] je_arena_choose_impl at jemalloc_internal.h:909 [opt]
    frame #5: 0x000000000601d0fc cockroach`je_tcache_get_hard [inlined] je_arena_choose at jemalloc_internal.h:918 [opt]
    frame #6: 0x000000000601d0fc cockroach`je_tcache_get_hard at tcache.c:314 [opt]
    frame #7: 0x0000000005fd4cf1 cockroach`je_malloc [inlined] je_tcache_get at tcache.h:237 [opt]
    frame #8: 0x0000000005fd4cdd cockroach`je_malloc [inlined] je_ialloc at jemalloc_internal.h:1079 [opt]
    frame #9: 0x0000000005fd4cdd cockroach`je_malloc [inlined] ialloc_body at jemalloc.c:1605 [opt]
    frame #10: 0x0000000005fd4c68 cockroach`je_malloc at jemalloc.c:1644 [opt]
    frame #11: 0x00007fff75e9e807 libsystem_malloc.dylib`malloc_zone_malloc + 103
    frame #12: 0x00007fff75e9e783 libsystem_malloc.dylib`malloc + 24
    frame #13: 0x00007fff73418f48 libc++abi.dylib`operator new(unsigned long) + 40
    frame #14: 0x0000000006070d12 cockroach`::DBNewBatch() at db.cc:479 [opt]
    frame #15: 0x0000000005f3d9e1 cockroach`_cgo_399a283c451a_Cfunc_DBNewBatch + 33
    frame #16: 0x000000000405e180 cockroach`runtime.asmcgocall + 112
    frame #17: 0x0000000004033930 cockroach`runtime.startTheWorldWithSema + 624
    frame #18: 0x0000000004caa3fe cockroach`github.com/cockroachdb/cockroach/pkg/storage/engine._Cfunc_DBNewBatch + 78
    frame #19: 0x0000000004cc10e9 cockroach`github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).ensureBatch.func1 + 121
    frame #20: 0x0000000004cb35cc cockroach`github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).ensureBatch + 60
    frame #21: 0x0000000004cb4576 cockroach`github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).NewIterator + 534
    frame #22: 0x0000000004c96648 cockroach`github.com/cockroachdb/cockroach/pkg/storage/engine.MVCCGet + 104
    frame #23: 0x0000000004c96232 cockroach`github.com/cockroachdb/cockroach/pkg/storage/engine.MVCCGetProto + 226
    frame #24: 0x0000000004e0bd6c cockroach`github.com/cockroachdb/cockroach/pkg/storage/abortspan.(*AbortSpan).Get + 220
    frame #25: 0x000000000530c4e5 cockroach`github.com/cockroachdb/cockroach/pkg/storage.checkIfTxnAborted + 197
    frame #26: 0x000000000531cd6f cockroach`github.com/cockroachdb/cockroach/pkg/storage.evaluateBatch + 4015
    frame #27: 0x0000000005352a3b cockroach`github.com/cockroachdb/cockroach/pkg/storage.(*Replica).evaluateWriteBatchWithLocalRetries + 507
```

What sticks out to my greenhorn eye in the [release notes for Go 1.12](https://golang.org/doc/go1.12) is that

> libSystem is now used when making syscalls on Darwin, ensuring forward-compatibility with future versions of macOS and iOS. The switch to libSystem triggered additional App Store checks for private API usage. Since it is considered private, syscall.Getdirentries now always fails with ENOSYS on iOS. 

We're using a fairly ancient version of jemalloc (https://github.com/cockroachdb/cockroach/issues/17013), so if this is a bug in that version, it's been around forever and is only being tickled reliably now.

Either way, we need to figure this out before we move to Go 1.12. One first step should be seeing whether this applies to Linux. My expectation would be that Linux binaries work just fine, but I haven't verified this yet.

### PR DESCRIPTION
**Pull request by petermattis**
Under go1.12, `cockroach` can deadlock deep within jemalloc. An upstream
change in jemalloc fixed this in the 5.1.0 release, but we're hesitant
to bump the jemalloc version as the last time we tried we ran into slow
memory leaks. It is unclear why this deadlock started to appear in
go1.12 but does not manifest with earlier versions of go. Perhaps the
switch to perform system calls via `libSystem` is to blame. Perhaps
there was a change to how fork is handled in go1.12.

Fixes #35620

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
Depends on https://github.com/cockroachdb/jemalloc/pull/1. Note that https://github.com/cockroachdb/jemalloc/pull/1 only changes code that is used on Darwin, so this is relatively safe (unless we suspect Darwin builds are being used in production somewhere). The only concern would be if this disrupts development on Mac's somehow.

**Comment by petermattis** [comment]
The alternative to this change would be to disable jemalloc on Darwin.

**Comment by tbg** [comment]
LGTM. Thanks for figuring this out.

**Comment by petermattis** [comment]
@bdarnell Let me know your thoughts on this.

**Review by bdarnell — APPROVED** [review]
LGTM. I'm surprised this makes a difference because we don't use `fork()` (and IIRC go is generally not compatible with fork-without-exec), but if we've empirically verified that it fixes the problem I'm happier backporting this than upgrading jemalloc at this stage.

**Comment by petermattis** [comment]
> I'm surprised this makes a difference because we don't use fork()

We `fork` when using `--background` (don't we?), though an exec happens almost immediately. I'll note that I can reproduce the deadlock without this PR even without `--background`. I can't reproduce a deadlock at all with this patch. Hmm, looking at `dtruss ./cockroach` I see there are several `fork` system calls. Note sure where those are coming from.

**Comment by petermattis** [comment]
`dtruss -t fork -s ./cockroach ...` prints the stacktrace when the `fork` system call is invoked:

```
              libsystem_kernel.dylib`__fork+0xb
              cockroach`runtime.syscall+0x1f
              cockroach`runtime.asmcgocall+0x70
              cockroach`syscall.rawSyscall+0x4e
              cockroach`syscall.forkAndExecInChild+0xe2
              cockroach`syscall.forkExec+0x360
              cockroach`os.startProcess+0x262
              cockroach`os.StartProcess+0x7c
              cockroach`os/exec.(*Cmd).Start+0x4a1
              cockroach`github.com/cockroachdb/cockroach/vendor/github.com/shirou/gopsutil/internal/common.Invoke.CommandWithContext+0xf1
              cockroach`github.com/cockroachdb/cockroach/vendor/github.com/shirou/gopsutil/internal/common.(*Invoke).CommandWithContext+0x96
              cockroach`github.com/cockroachdb/cockroach/vendor/github.com/shirou/gopsutil/net.IOCountersWithContext+0x112
              cockroach`github.com/cockroachdb/cockroach/pkg/server/status.getSummedNetStats+0x69
              cockroach`github.com/cockroachdb/cockroach/pkg/server/status.(*RuntimeStatSampler).SampleEnvironment+0x3e7
              cockroach`github.com/cockroachdb/cockroach/pkg/server.(*Server).startSampleEnvironment.func2+0x19c
              cockroach`github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1+0xfb
              cockroach`runtime.goexit+0x1
```

Note that with go1.11 system calls on Darwin didn't use `libSystem`:

```
              cockroach`syscall.RawSyscall+0x31
              cockroach`syscall.forkExec+0x365
              cockroach`syscall.StartProcess+0x64
              cockroach`os.startProcess+0x213
              cockroach`os.StartProcess+0x7c
              cockroach`os/exec.(*Cmd).Start+0x4bc
              cockroach`github.com/cockroachdb/cockroach/vendor/github.com/shirou/gopsutil/internal/common.Invoke.CommandWithContext+0xd7
              cockroach`github.com/cockroachdb/cockroach/vendor/github.com/shirou/gopsutil/internal/common.(*Invoke).CommandWithContext+0x96
              cockroach`github.com/cockroachdb/cockroach/vendor/github.com/shirou/gopsutil/net.IOCountersWithContext+0x112
              cockroach`github.com/cockroachdb/cockroach/pkg/server/status.getSummedNetStats+0x74
              cockroach`github.com/cockroachdb/cockroach/pkg/server/status.NewRuntimeStatSampler+0x5be
              cockroach`github.com/cockroachdb/cockroach/pkg/server.NewServer+0x1f34
              cockroach`github.com/cockroachdb/cockroach/pkg/cli.runStart.func3.2+0x64
              cockroach`github.com/cockroachdb/cockroach/pkg/cli.runStart.func3+0x11c
              cockroach`runtime.goexit+0x1
```

I wonder if that makes a difference.

**Comment by bdarnell** [comment]
Oh, I think I get it now. I thought fork+exec was safe because no memory is allocated in the child process before the exec system call. But thanks to a post-fork hook used here, there is activity in the malloc system even if the code between fork+exec is restricted to non-allocating signal-safe functions. 

I also forgot about how some of our metric-collection libraries work by shelling out to subprocesses on macos, so we do fork+exec all the time even without --background.

**Comment by petermattis** [comment]
bors r=tbg,bdarnell

**Comment by petermattis** [comment]
Should this be backported to 2.1, or are we close enough to the 19.1 release to not bother?

**Comment by bdarnell** [comment]
I think this should be backported (and also the PRs linked in #35197). The next release from the 2.1 branch may not come until after 19.1.0 (so they'll never go into homebrew), but there will still be more 2.1 releases and we'll want them to be able to build with newer versions of go (we've done this for past releases)

**Pull request merged**
