### PR TITLE
opt: remove conflicting input rows in ON CONFLICT DO NOTHING case

### LINKED ISSUE #37880: sql: UPSERT behavior change in optimizer
With the CBO on, `UPSERT` produces different results than the HP when there are tuples with duplicate values in a column with a constraint.

It seems that the CBO will reject such upserts, but the HP accepted them and preferred the later tuples. I'm not sure if this is intended, but it's causing errors in the `kv/contention` workload, which is showing up here: #36089. (The `kv` benchmark produces duplicate tuples in its upserts, which should be fixed regardless of how we resolve this issue.)

Note that Postgres outright bans this case with their `UPSERT` equivalent:

```
jordan=# insert into a values(1,2),(1,3) on conflict(a) do update set b=excluded.b;
ERROR:  ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
```

Expected, pre-CBO behavior:

```
root@127.0.0.1:59593/defaultdb> create table a (a int primary key, b int, index(b));
CREATE TABLE

Time: 2.238ms

root@127.0.0.1:59593/defaultdb> set optimizer=off;
SET

Time: 236µs

root@127.0.0.1:59662/defaultdb> \set auto_trace=on,kv
root@127.0.0.1:59662/defaultdb> upsert into a values(1,2),(1,3);
INSERT 2

Time: 1.411ms

             timestamp             |       age       |                                  message                                  |                        tag                         | location |      operation      | span
+----------------------------------+-----------------+---------------------------------------------------------------------------+----------------------------------------------------+----------+---------------------+------+
  2019-05-28 04:19:13.572524+00:00 | 00:00:00.000466 | Scan /Table/52/1/1{-/#}                                                   | [n1,client=127.0.0.1:59664,user=root]              |          | flow                |    6
  2019-05-28 04:19:13.57255+00:00  | 00:00:00.000492 | querying next range at /Table/52/1/1                                      | [n1,client=127.0.0.1:59664,user=root,txn=6052b0ab] |          | dist sender send    |    8
  2019-05-28 04:19:13.572573+00:00 | 00:00:00.000515 | r21: sending batch 1 Scan to (n1,s1):1                                    | [n1,client=127.0.0.1:59664,user=root,txn=6052b0ab] |          | dist sender send    |    8
  2019-05-28 04:19:13.572801+00:00 | 00:00:00.000743 | CPut /Table/52/1/1/0 -> /TUPLE/2:2:Int/2                                  | [n1,client=127.0.0.1:59664,user=root]              |          | flow                |    6
  2019-05-28 04:19:13.572809+00:00 | 00:00:00.000751 | InitPut /Table/52/2/2/1/0 -> /BYTES/                                      | [n1,client=127.0.0.1:59664,user=root]              |          | flow                |    6
  2019-05-28 04:19:13.572831+00:00 | 00:00:00.000773 | Put /Table/52/1/1/0 -> /TUPLE/2:2:Int/3                                   | [n1,client=127.0.0.1:59664,user=root]              |          | flow                |    6
  2019-05-28 04:19:13.572839+00:00 | 00:00:00.000781 | Del /Table/52/2/2/1/0                                                     | [n1,client=127.0.0.1:59664,user=root]              |          | flow                |    6
  2019-05-28 04:19:13.572843+00:00 | 00:00:00.000785 | CPut /Table/52/2/3/1/0 -> /BYTES/ (expecting does not exist)              | [n1,client=127.0.0.1:59664,user=root]              |          | flow                |    6
  2019-05-28 04:19:13.572875+00:00 | 00:00:00.000817 | querying next range at /Table/52/1/1/0                                    | [n1,client=127.0.0.1:59664,user=root,txn=6052b0ab] |          | dist sender send    |   11
  2019-05-28 04:19:13.572888+00:00 | 00:00:00.00083  | r21: sending batch 1 Put, 2 CPut, 1 Del, 1 EndTxn, 1 InitPut to (n1,s1):1 | [n1,client=127.0.0.1:59664,user=root,txn=6052b0ab] |          | dist sender send    |   11
  2019-05-28 04:19:13.573423+00:00 | 00:00:00.001365 | fast path completed                                                       | [n1,client=127.0.0.1:59664,user=root]              |          | flow                |    6
  2019-05-28 04:19:13.57345+00:00  | 00:00:00.001392 | rows affected: 2                                                          | [n1,client=127.0.0.1:59664,user=root]              |          | exec cmd: exec stmt |    4
(12 rows)

Time: 2.338ms
```

Actual CBO behavior:

```
root@127.0.0.1:59607/defaultdb> create table a (a int primary key, b int, index(b));
CREATE TABLE

Time: 2.624ms

root@127.0.0.1:59628/defaultdb> \set auto_trace=on,kv
root@127.0.0.1:59607/defaultdb> upsert into a values(1,2),(1,3);
pq: duplicate key value (a)=(1) violates unique constraint "primary"
             timestamp             |       age       |                                             message                                             |                        tag                         | location |      operation      | span
+----------------------------------+-----------------+-------------------------------------------------------------------------------------------------+----------------------------------------------------+----------+---------------------+------+
  2019-05-28 04:18:07.110666+00:00 | 00:00:00.000596 | Scan /Table/52/1/1{-/#}                                                                         | [n1,client=127.0.0.1:59630,user=root]              |          | join reader         |   16
  2019-05-28 04:18:07.11069+00:00  | 00:00:00.00062  | querying next range at /Table/52/1/1                                                            | [n1,client=127.0.0.1:59630,user=root,txn=7fc2e5fc] |          | dist sender send    |   18
  2019-05-28 04:18:07.110712+00:00 | 00:00:00.000642 | r21: sending batch 1 Scan to (n1,s1):1                                                          | [n1,client=127.0.0.1:59630,user=root,txn=7fc2e5fc] |          | dist sender send    |   18
  2019-05-28 04:18:07.110835+00:00 | 00:00:00.000765 | CPut /Table/52/1/1/0 -> /TUPLE/2:2:Int/2                                                        | [n1,client=127.0.0.1:59630,user=root]              |          | flow                |    6
  2019-05-28 04:18:07.110844+00:00 | 00:00:00.000774 | InitPut /Table/52/2/2/1/0 -> /BYTES/                                                            | [n1,client=127.0.0.1:59630,user=root]              |          | flow                |    6
  2019-05-28 04:18:07.110855+00:00 | 00:00:00.000785 | CPut /Table/52/1/1/0 -> /TUPLE/2:2:Int/3                                                        | [n1,client=127.0.0.1:59630,user=root]              |          | flow                |    6
  2019-05-28 04:18:07.110859+00:00 | 00:00:00.000789 | InitPut /Table/52/2/3/1/0 -> /BYTES/                                                            | [n1,client=127.0.0.1:59630,user=root]              |          | flow                |    6
  2019-05-28 04:18:07.110924+00:00 | 00:00:00.000854 | querying next range at /Table/52/1/1/0                                                          | [n1,client=127.0.0.1:59630,user=root,txn=7fc2e5fc] |          | dist sender send    |    8
  2019-05-28 04:18:07.110937+00:00 | 00:00:00.000867 | r21: sending batch 2 CPut, 1 EndTxn, 2 InitPut to (n1,s1):1                                     | [n1,client=127.0.0.1:59630,user=root,txn=7fc2e5fc] |          | dist sender send    |    8
  2019-05-28 04:18:07.111263+00:00 | 00:00:00.001193 | execution failed after 0 rows: duplicate key value (a)=(1) violates unique constraint "primary" | [n1,client=127.0.0.1:59630,user=root]              |          | exec cmd: exec stmt |    4
  2019-05-28 04:18:07.111288+00:00 | 00:00:00.001218 | querying next range at /Table/52/1/1/0                                                          | [n1,client=127.0.0.1:59630,user=root,txn=7fc2e5fc] |          | dist sender send    |   11
  2019-05-28 04:18:07.111297+00:00 | 00:00:00.001227 | r21: sending batch 1 EndTxn to (n1,s1):1                                                        | [n1,client=127.0.0.1:59630,user=root,txn=7fc2e5fc] |          | dist sender send    |   11
(12 rows)
```

Assigning @andy-kimball for initial remarks. Did you come across this case while porting mutations tot he CBO?

### LINKED ISSUE #44434: BUG - INSERT ON CONFLICT IGNORE does not work when there is a duplicate key within the insert statement itself
**Describe the problem**

While a big data import migrating a huge mongo database into cockroachdb, suddenly the processed stopped importing. The reason: duplicate key value. But I do have `ON CONFLICT DO NOTHING` active. I got a doubt and was just able to reproduce it. The reason for this is:

We do bulk inserts to go through the import faster. But it turns out in the same batch the same key pair (a distinct key made from 3 fields) appeared at least twice. Cockroachdb does not handle this well yet. This is clearly a bug and only happens in this scenario, if the database holds a value for the duplication already, the conflict handling will work even though there are multiple entries for this key in the statement.

# Expectation

The expectation I have from cockroachdb is: If in the same bulk insert statement a key conflict exists and there is an `ON CONFLICT DO NOTHING`, write the first value and ignore further ones. This is how they would be treated should a value exist in the database already anyways though.

**To Reproduce**

Create a table with some unique value (we had a primaryKey spanned over 3 columns) and execute a bulk statement. The table should not have any record yet with the same key.

`INSERT INTO "table" ("key1", "key2", "key3", "randomfield") VALUES (12,12,13,"1"), (12,12,13,"2") ON CONFLICT DO NOTHING`

### LINKED ISSUE #44466: Multi-record UPSERT inserts duplicate values in PRIMARY KEY, resulting in inconsistent results
Consider the following testcase:

```sql
CREATE TABLE t0(c0 INT PRIMARY KEY, c1 BOOL, c2 INT UNIQUE);
INSERT INTO t0(c0) VALUES (0);
UPSERT INTO t0(c2, c0) VALUES (0, 0), (1, 0);
SELECT * FROM t0; -- {0 | NULL | 1}
```
A single row is fetched, while the following query fetches two records with a duplicate value for c0:

```sql
SELECT c0 FROM t0; -- {0, 0}
```
I found this issue in CockroachDB based on commit `1917a12003daad100b491e2b0195d7df5909e63f`.

### PR DESCRIPTION
**Pull request by andy-kimball**
Previously, the INSERT..ON CONFLICT DO NOTHING statement raised an error
if its input contained rows which conflicted with one another. For example:

  CREATE TABLE t (x INT PRIMARY KEY)
  INSERT INTO t (x) VALUES (1), (1) ON CONFLICT DO NOTHING

This raised a unique key conflict error rather than doing nothing.

This commit fixes that by wrapping the input in one or more UpsertDistinctOn
operators - one for each unique key in the target table. This ensures that
any duplicates which might cause a conflict are removed from the input.

Fixes #37880
Fixes #44434

Release note (sql change): Duplicate rows in the input to an INSERT..ON
CONFLICT DO NOTHING statement will now be ignored rather than triggering
an error.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45443)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/ops/relational.opt, line 533 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45443#-M11svS-By1IG41KmrY5:-M11svS-By1IG41KmrY6:b4rgp5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bb6021bf1c2b10deb736f83455eb6487e279424/pkg/sql/opt/ops/relational.opt#L533)):*
> ```
>     # ErrorOnDup, if true, triggers an error if any aggregation group contains
>     # more than one row. This can only be true for the UpsertDistinctOn operator.
>     ErrorOnDup bool
> ```

I think this code needs to be updated to check the new field instead: https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/opt/memo/statistics_builder.go#L1500

**Review by rytaft — APPROVED** [review]
:lgtm: (once you address Radu's point)

> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45443#-:-M12fUIV3FLbR0xnFwAZ:b-n2peva)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball)

___
*[pkg/sql/opt/memo/testdata/logprops/upsert, line 222 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45443#-M12ZKWr4YzRhglt8fgN:-M12ZKWr4YzRhglt8fgO:b-vuovdx) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bb6021bf1c2b10deb736f83455eb6487e279424/pkg/sql/opt/memo/testdata/logprops/upsert#L222)):*
> ```
>       ├── key: (1)
>       ├── fd: (1)-->(2-4), (2)-->(3), (4)~~>(1-3), (2,3)~~>(1,4)
>       └── upsert-distinct-on
> ```

should ErrOnDup be printed here?
___
*[pkg/sql/opt/norm/groupby.go, line 219 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45443#-M12_Aql7rGcWDSkaUh8:-M12_AqmCfk2BhirLCx5:b-gt2mel) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bb6021bf1c2b10deb736f83455eb6487e279424/pkg/sql/opt/norm/groupby.go#L219)):*
> ```Go
> 		}
> 
> 	case *memo.UpsertDistinctOnExpr:
> ```

Can you also include regular `DistinctOn` here?
___
*[pkg/sql/opt/optbuilder/insert.go, line 741 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45443#-M12dk_G8d6I-YM-BZpS:-M12dk_G8d6I-YM-BZpT:bxhcaha) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bb6021bf1c2b10deb736f83455eb6487e279424/pkg/sql/opt/optbuilder/insert.go#L741)):*
> ```Go
> 
> 		// Add an UpsertDistinctOn operator to ensure there are no duplicate input
> 		// rows for this unique index. Duplicate rows trigger conflict errors,
> ```

Might help to specify that these conflict errors happen at execution time

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45443)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/memo/testdata/logprops/upsert, line 222 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45443#-M12ZKWr4YzRhglt8fgN:-M13pknF7NCyee3PRNw6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bb6021bf1c2b10deb736f83455eb6487e279424/pkg/sql/opt/memo/testdata/logprops/upsert#L222)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

should ErrOnDup be printed here?
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/groupby.go, line 219 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45443#-M12_Aql7rGcWDSkaUh8:-M13pu865NkTXO034DJO:b-8tgdnb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bb6021bf1c2b10deb736f83455eb6487e279424/pkg/sql/opt/norm/groupby.go#L219)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Can you also include regular `DistinctOn` here?
</blockquote></details>

I think it could in theory be included, but I think the case would be so rare as to be not worth the extra complication to test and maintain. I want to keep the cases constrained to what we might see in upsert queries (I added `DistinctOn` at the top-level mostly to make it easier to test). I thought about using a Rule property so that we don't descend the tree on every distinct operator, but figured it was OK as-is, since we only descend down a single path here, and not the entire subtree.
___
*[pkg/sql/opt/ops/relational.opt, line 533 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45443#-M11svS-By1IG41KmrY5:-M18XJArBV_2jOw7gsnm:b-qm4979) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bb6021bf1c2b10deb736f83455eb6487e279424/pkg/sql/opt/ops/relational.opt#L533)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I think this code needs to be updated to check the new field instead: https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/opt/memo/statistics_builder.go#L1500
</blockquote></details>

Yes, I missed that. Fixed.
___
*[pkg/sql/opt/optbuilder/insert.go, line 741 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45443#-M12dk_G8d6I-YM-BZpS:-M18Y1q-ERlQY_KKMCk0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bb6021bf1c2b10deb736f83455eb6487e279424/pkg/sql/opt/optbuilder/insert.go#L741)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Might help to specify that these conflict errors happen at execution time
</blockquote></details>

Done.

**Review by andy-kimball — COMMENTED** [review]
Note that I also fixed the problem that Radu found in the previous review, regarding incorrect removal of upsert-distinct-on when it wraps left-join.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45443#-:-M18Yu5I7f8VzTW7eYuL:b7ml7zn)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @rytaft)

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45443)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/norm/groupby.go, line 238 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45443#-M1Baqek8ZMk-aXMCCLS:-M1Baqek8ZMk-aXMCCLT:bafkui2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a2c1b190f304259aa3eb24c17f4e22cde140cd9/pkg/sql/opt/norm/groupby.go#L238)):*
> ```Go
> 			}
> 		}
> 		if !keyCols.SubsetOf(eqCols) {
> ```

Don't we want to use `ColsAreLaxKey`? This won't work well if we have multiple keys.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45443)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/norm/groupby.go, line 238 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45443#-M1Baqek8ZMk-aXMCCLS:-M1BteoI0s_9zUcwqyv3:bcsnch9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a2c1b190f304259aa3eb24c17f4e22cde140cd9/pkg/sql/opt/norm/groupby.go#L238)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Don't we want to use `ColsAreLaxKey`? This won't work well if we have multiple keys.
</blockquote></details>

Yes, `ColsAreLaxKey` is better. Switched to that.

The current code was able to work OK b/c we always left-join with an index scan having a key that matches the upsert-distinct-on grouping cols.

**Review by andy-kimball — COMMENTED** [review]
Another possibility I've thought about is whether we should instead have an `insert-distinct-on` operator rather than adding `ErrorOnDup` to `upsert-distinct-on`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45443#-:-M1BvjNmEisxQiEZ4K9k:bx6w5y2)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @rytaft)

**Review by rytaft — COMMENTED** [review]
I like the idea of having a separate operator so you don't need the extra field

> Reviewed 9 of 12 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45443#-:-M1R6gYc9Ynmg0VyoNH2:b-fycyxj)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @RaduBerinde)

___
*[pkg/sql/opt/memo/extract.go, line 227 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45443#-M1R3kQ1AfpvvnhRp-tU:-M1R3kQ1AfpvvnhRp-tV:b6j27v1) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf2f9c8f4977570f3fbf6f2bde37a86dd553252a/pkg/sql/opt/memo/extract.go#L227)):*
> ```Go
> // ExtractJoinEquality returns true if the given condition is a simple equality
> // condition with two variables (e.g. a=b), where one of the variables (returned
> // as "left") is in the set of leftCols and the other (returned as "right") in
> ```

[nit] (returned as "right") in -> (returned as "right") is in
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1554 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45443#-M1R4rKk5fVlUb9EqG5V:-M1R4rKl5LYeaKJ0hMqW:bf9qzx9) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf2f9c8f4977570f3fbf6f2bde37a86dd553252a/pkg/sql/opt/memo/statistics_builder.go#L1554)):*
> ```Go
> 		// will raise an error, so in non-error cases its distinct count is the
> 		// same as its row count.
> 		colStat.DistinctCount = s.RowCount
> ```

But this only applies if the columns in colSet match the grouping columns, right? I think the code above will already do what you want in that case.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45443)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/memo/extract.go, line 227 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45443#-M1R3kQ1AfpvvnhRp-tU:-M1SjagE7AyfToZqtbmh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf2f9c8f4977570f3fbf6f2bde37a86dd553252a/pkg/sql/opt/memo/extract.go#L227)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] (returned as "right") in -> (returned as "right") is in
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1554 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45443#-M1R4rKk5fVlUb9EqG5V:-M1SkP_H4wveQLXJ9OFA:b-kzpimz) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf2f9c8f4977570f3fbf6f2bde37a86dd553252a/pkg/sql/opt/memo/statistics_builder.go#L1554)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

But this only applies if the columns in colSet match the grouping columns, right? I think the code above will already do what you want in that case.
</blockquote></details>

How so? The `RowCount` of the distinct operator in the error case is equal to the `RowCount` of its input. But it's `DistinctCount` should also be equal to the `RowCount` of its input, which the code above would not do.

Maybe I should put this new code only in the 2nd branch of that code (when cols are grouping cols). So `DistinctCount` would equal `RowCount` when cols are grouping cols, but `DistinctCount` would be equal to 1st branch if not.

**Review by andy-kimball — COMMENTED** [review]
Re: the separate operator, I think I'll just keep as-is for now. There are pros and cons to each approach, and I don't think we gain much by switching. We can always change later if we decide it's not working well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45443#-:-M1TWEEu1AH4i-Mt0rxX:b6wa214)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @rytaft)

**Review by rytaft — COMMENTED** [review]
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45443)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @RaduBerinde)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 1554 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45443#-M1R4rKk5fVlUb9EqG5V:-M1WOYIJ8EqXNKUaM0yA:bftarx5) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf2f9c8f4977570f3fbf6f2bde37a86dd553252a/pkg/sql/opt/memo/statistics_builder.go#L1554)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

How so? The `RowCount` of the distinct operator in the error case is equal to the `RowCount` of its input. But it's `DistinctCount` should also be equal to the `RowCount` of its input, which the code above would not do.

Maybe I should put this new code only in the 2nd branch of that code (when cols are grouping cols). So `DistinctCount` would equal `RowCount` when cols are grouping cols, but `DistinctCount` would be equal to 1st branch if not.
</blockquote></details>

But you'd need to be sure that the `colSet` is equal to `groupingColSet`. If there are two grouping columns and `colSet` only contains one of them, then this logic is incorrect. The `GroupBy` and `DistinctOn` operators don't change the distinct counts of grouping columns, regardless of whether `ErrOnDup` is set or not. (`ErrOnDup` *does* indicate something about the row count, though, which you've already handled above in `buildGroupBy`). 

So the distinct count for `colSet` here should be the same as the distinct count of `colSet` in the input, which is what line 1546 is already doing (copying from input).

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45443)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 1554 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45443#-M1R4rKk5fVlUb9EqG5V:-M1a_qnJ4tfqTztwdSkl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf2f9c8f4977570f3fbf6f2bde37a86dd553252a/pkg/sql/opt/memo/statistics_builder.go#L1554)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

But you'd need to be sure that the `colSet` is equal to `groupingColSet`. If there are two grouping columns and `colSet` only contains one of them, then this logic is incorrect. The `GroupBy` and `DistinctOn` operators don't change the distinct counts of grouping columns, regardless of whether `ErrOnDup` is set or not. (`ErrOnDup` *does* indicate something about the row count, though, which you've already handled above in `buildGroupBy`). 

So the distinct count for `colSet` here should be the same as the distinct count of `colSet` in the input, which is what line 1546 is already doing (copying from input).
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45443#-:-M1aopcM1wxdONldqS-T:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Review by andy-kimball — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45443#-:-M1aqn3F3MvxcX-15bzO:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Comment by RaduBerinde** [comment]
bors r-

optbuilder testfiles need a rewrite: https://teamcity.cockroachdb.com/viewLog.html?buildId=1785780&buildTypeId=Cockroach_UnitTests

**Pull request merged**
