### PR TITLE
Revert "kvserver: separate repl q decision from action"

### PR DESCRIPTION
**Pull request by nvb**
This reverts commit d9448f41f017db32c127e5214deccf49ad2c3f14.

The commit was causing `TestPartialZip` to reliably fail. The cause of the failure has not been investigated, but this revert allows us to do so async without blocking master.

Epic: None

### CODE REVIEW

**Review by AlexTalks — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91043#-:-NFl7beaANupf0RaqN4d:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

**Comment by nvanbenschoten** [comment]
There's a circular dependency between this PR and https://github.com/cockroachdb/cockroach/pull/91031. We're going to have to hope that they end up in the same bors batch 🤞 

TFTR!

bors r+

**Comment by nvanbenschoten** [comment]
Screen Shot 2022-10-31 at 11 02 17 PM

**Comment by nvanbenschoten** [comment]
bors r-

Flake on `TestExternalSortMemoryAccounting`, which was meant to be resolved by https://github.com/cockroachdb/cockroach/pull/91008. See https://cockroachlabs.slack.com/archives/C016CAD2HQ8/p1667251438538819.

**Comment by ajwerner** [comment]
> Flake on TestExternalSortMemoryAccounting, which was meant to be resolved by https://github.com/cockroachdb/cockroach/pull/91008. See [cockroachlabs.slack.com/archives/C016CAD2HQ8/p1667251438538819](https://cockroachlabs.slack.com/archives/C016CAD2HQ8/p1667251438538819).

https://github.com/cockroachdb/cockroach/pull/91044 take two

**Pull request merged**
