### PR TITLE
catalog/lease: block liveness heartbeats if leases cannot be written

### LINKED ISSUE #119347: roachtest: failover/chaos/read-only/lease=expiration failed
roachtest.failover/chaos/read-only/lease=expiration [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14049702?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14049702?buildTab=artifacts#/failover/chaos/read-only/lease=expiration) on master @ [e39dafe6d8c153301ff43ed2b3ed3e13af9ec72a](https://github.com/cockroachdb/cockroach/commits/e39dafe6d8c153301ff43ed2b3ed3e13af9ec72a):

```
(test_runner.go:1153).runTest: test timed out (1h0m0s)
test artifacts and logs in: /artifacts/failover/chaos/read-only/lease=expiration/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=2</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-14049702/failover-chaos-read-only-lease-expiration/1708265062907/1708268818838)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #119334 roachtest: failover/chaos/read-only/lease=expiration failed [C-test-failure O-roachtest O-robot T-kv branch-release-23.2.1-rc release-blocker]
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*failover/chaos/read-only/lease=expiration.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-36161

### LINKED ISSUE #119654: catalog/lease: avoid updating sqlliveness cannot be written or deleted
In https://github.com/cockroachdb/cockroach/issues/119347 we noticed that if writes / deletes to the system.lease keep hitting retryable replica errors we should eventually stop renewing the sqlliveness once enough time has gone by. Its possible for the system.lease table to have partition failure where the sqlliveness can be emitted, but leases cannot be modified / deleted. This could cause the entire cluster from being able to execute new schema changes, since this node will be stuck holding leases.

In the expiry leasing model this condition would clear once the lease expires, but in the session based model the lease could linger forever.

Jira issue: CRDB-36217

Epic CRDB-35665

### PR DESCRIPTION
**Pull request by fqazi**
Previously, if we had any type of partition failure where a single node could not write / delete leases it could cause the schema changes to be blocked on descriptors held by it. This was made worse with the session based model where leases no longer expire, so any failure of this nature will last until the problematic node is restarted. To address this, this patch will prevent the sqlliveness from extending the expiration if the leases table cannot be accessed any longer.

Fixes: #119654
Fixes: https://github.com/cockroachdb/cockroach/issues/119347

Release note: None

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119739)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/catalog/lease/storage.go` line 235 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119739#-NrqSk1bCkj9NiX5ZxWA:-NrqSk1bCkj9NiX5ZxWB:b-kwx0v1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2d8bf643648abea1b59fac803f18c22c6730201/pkg/sql/catalog/lease/storage.go#L235)):*
> ```Go
> 	// Run a retry loop to deal with AmbiguousResultErrors. All other error types
> 	// are propagated up to the caller.
> 	maxRetryDuration := s.jitteredLeaseDuration()
> ```

nit: i don't follow why this defaults to `s.jitteredLeaseDuration()` but the `else` block sets this to 0. also, why does it subtract the ttl time? some comments could help

(same for the `release` logic below)
___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119739#-NrqTDeAAxry1f-HA1ht:-NrqTDeAAxry1f-HA1hu:b376hwi) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2d8bf643648abea1b59fac803f18c22c6730201/pkg/sql/sqlliveness/slinstance/slinstance.go#L131)):*
> ```Go
> 		// blockExtensions indicates if extensions are disallowed because of availability
> 		// issues on dependent tables.
> 		blockExtensions int
> ```

nit: maybe call it `blockedExtensions` to make it more clear it's a count
___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119739#-NrqTdv945x8Lsr8zzTb:-NrqTdv945x8Lsr8zzTc:be63vis) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2d8bf643648abea1b59fac803f18c22c6730201/pkg/sql/sqlliveness/slinstance/slinstance.go#L257)):*
> ```Go
> 
> 	// If extensions are disallowed we are only going to heartbeat the same
> 	// timestamp.
> ```

is it important to hearbeat the same timestamp, rather than just short-circuit return here?
___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 466 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119739#-NrqSZlf5_HSWSbYjhFp:-NrqSZlf5_HSWSbYjhFq:ba1ekyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2d8bf643648abea1b59fac803f18c22c6730201/pkg/sql/sqlliveness/slinstance/slinstance.go#L466)):*
> ```Go
> 	firstToBlock := l.mu.blockExtensions == 0
> 	l.mu.blockExtensions++
> 	defer l.mu.Unlock()
> ```

nit: the defer should be immediately after the Lock. (same for the next function)

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119739)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/catalog/lease/storage.go` line 235 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119739#-NrqSk1bCkj9NiX5ZxWA:-NruYbg225PA_QGX5f8b:bjy363) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2d8bf643648abea1b59fac803f18c22c6730201/pkg/sql/catalog/lease/storage.go#L235)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: i don't follow why this defaults to `s.jitteredLeaseDuration()` but the `else` block sets this to 0. also, why does it subtract the ttl time? some comments could help

(same for the `release` logic below)
</blockquote></details>

Added a comment to clarify and fixed the variable names:

// Compute the maximum time we will retry ambiguous replica errors before  
// disabling the SQL liveness heartbeat. The time chosen will guarantee that  
// the sqlliveness TTL expires once the lease duration has surpassed.
___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119739#-NrqTdv945x8Lsr8zzTb:-NruancE0BKjk4L3SqWw:bpiotr5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2d8bf643648abea1b59fac803f18c22c6730201/pkg/sql/sqlliveness/slinstance/slinstance.go#L257)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

is it important to hearbeat the same timestamp, rather than just short-circuit return here?
</blockquote></details>

The update logic also detects if the session has been deleted, so thats why I was heart beating the same timestamp. Updated the comment to:

// If extensions are disallowed we are only going to heartbeat the same  
// timestamp, so that we can detect if the sqlliveness row was removed.

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119739)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/catalog/lease/lease_test.go` line 3740 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119739#-NrukxiL8t-PB6oQXxuX:-NrukxiL8t-PB6oQXxuY:baxqx4g) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc419b4293de5d8937406f278acdfe5914b54fd8/pkg/sql/catalog/lease/lease_test.go#L3740)):*
> ```Go
> 	// failure, the retry happens, and there is just one lease.
> 	selectErr := make(chan error)
> 	go func() {
> ```

could this one use the ctxgroup also?

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119739)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/catalog/lease/lease_test.go` line 3740 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119739#-NrukxiL8t-PB6oQXxuX:-NruzBpZ2-Ieu_4tYynw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc419b4293de5d8937406f278acdfe5914b54fd8/pkg/sql/catalog/lease/lease_test.go#L3740)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could this one use the ctxgroup also?
</blockquote></details>

Done.

**Comment by fqazi** [comment]
@rafiss TFTR!

bors r+

**Pull request merged**
