### PR TITLE
opt: support UPSERT with virtual columns

### PR DESCRIPTION
**Pull request by RaduBerinde**
Release note: None

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm: Nice and thorough! I know those tests are tedious to write...

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59500#-:-MS94BU79efqGc7HbV-G:bvhd155)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/logictest/testdata/logic_test/virtual_columns, line 268 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59500#-MS8zBU-6eDbBMEr0jTU:-MS8zBU-6eDbBMEr0jTV:b-3nlrxy) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ec3ab80d8fef090c2f445885028d8a0f073e9f4/pkg/sql/logictest/testdata/logic_test/virtual_columns#L268)):*
> ```
> #  INDEX (v),
> #  UNIQUE (w)
> #)
> ```

[nit] remove comments
___
*[pkg/sql/logictest/testdata/logic_test/virtual_columns, line 380 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59500#-MS91Bw07xab3QJXsaVC:-MS91Bw07xab3QJXsaVD:b26dbtk) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ec3ab80d8fef090c2f445885028d8a0f073e9f4/pkg/sql/logictest/testdata/logic_test/virtual_columns#L380)):*
> ```
> # Some rows conflict on the PK, some on w.
> query I colnames,rowsort
> INSERT INTO t_idx VALUES (4, 41, 301), (6, 60, 600), (7, 70, 100) ON CONFLICT DO NOTHING RETURNING w
> ```

[nit] add tests like:

```
# Conflict with a.
statement error violated unique constraint
INSERT INTO t_idx VALUES (1, 80, 900) ON CONFLICT (w) DO NOTHING

# Conflict with w.
statement error violated unique constraint
INSERT INTO t_idx VALUES (8, 80, 100) ON CONFLICT (a) DO NOTHING
```
___
*[pkg/sql/opt/exec/execbuilder/testdata/virtual_columns, line 811 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59500#-MS92kn33_1_qnhfRVyf:-MS92kn33_1_qnhfRVyg:b-1gtekt) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ec3ab80d8fef090c2f445885028d8a0f073e9f4/pkg/sql/opt/exec/execbuilder/testdata/virtual_columns#L811)):*
> ```
>         │ render v: v
>         │
>         └── • merge join (right outer)
> ```

I'm surprised this is a merge join and not a lookup join. Maybe due to the lack of statistics?

**Comment by mgartner** [comment]
Also, now that #59497 is merged you'll have to rebase and rewrite the upsert tests I added and remove the TODOs above them.

**Review by RaduBerinde — COMMENTED** [review]
Updated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59500#-:-MS99-jS-uGS6tTvCyXi:b-bw8e14)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[pkg/sql/opt/exec/execbuilder/testdata/virtual_columns, line 811 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59500#-MS92kn33_1_qnhfRVyf:-MS96VItE8eULh0_ORDG:b3a8vlt) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ec3ab80d8fef090c2f445885028d8a0f073e9f4/pkg/sql/opt/exec/execbuilder/testdata/virtual_columns#L811)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I'm surprised this is a merge join and not a lookup join. Maybe due to the lack of statistics?
</blockquote></details>

Good point. I am guessing that the Project prevents the lookup join rules from firing. Adding a TODO and I'll investigate separately.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59500)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[pkg/sql/opt/exec/execbuilder/testdata/virtual_columns, line 811 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59500#-MS92kn33_1_qnhfRVyf:-MS9AFMU4j_y7OtDa6lE:b7zerpf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ec3ab80d8fef090c2f445885028d8a0f073e9f4/pkg/sql/opt/exec/execbuilder/testdata/virtual_columns#L811)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Good point. I am guessing that the Project prevents the lookup join rules from firing. Adding a TODO and I'll investigate separately.
</blockquote></details>

It is an interesting case.. We can do the projections after the join, but we must modify them to return NULL if the canary column is NULL.

**Review by mgartner — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59500)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 4 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59500#-:-MS9iSG69H-SwIQTKFx4:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/testdata/virtual-columns, line 620 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59500#-MS9hqwbCiIkCn-YYUbO:-MS9hqwbCiIkCn-YYUbP:bcaunfx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c642cfa3c3b4ed3adc379b72a9b010a7473d4b67/pkg/sql/opt/optbuilder/testdata/virtual-columns#L620)):*
> ```
>                 └── c:9 + 1 [as=column15:15]
> 
> # -- UPSERT / INSERT ON CONFLIC tests --
> ```

[nit] ON CONFLICT

**Review by RaduBerinde — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59500#-:-MSA6KYFDA4lslwRoQZc:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/optbuilder/testdata/virtual-columns, line 620 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59500#-MS9hqwbCiIkCn-YYUbO:-MSA6JKj2GpyUJ6YbgUB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c642cfa3c3b4ed3adc379b72a9b010a7473d4b67/pkg/sql/opt/optbuilder/testdata/virtual-columns#L620)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] ON CONFLICT
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59500)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner)

**Pull request merged**
