### PR TITLE
engine: fix bug in Distinct() after ApplyBatchRepr()

### PR DESCRIPTION
**Pull request by tbg**
Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
This doesn't actually fix it yet because I just figured out why my WIP would fail randomly. Perhaps @petermattis knows what's up here, or I'll figure it out myself later (probably straightforward anyway).

**Review by petermattis — COMMENTED** [review]
Looks like we're missing setting the `distinctNeedsFlush` flag in `ApplyBatchRepr`. How did you discover this? Seems like it could cause reads to miss earlier writes?

```
diff --git a/pkg/storage/engine/rocksdb.go b/pkg/storage/engine/rocksdb.go
index 882a2ff9de..a2690df2af 100644
--- a/pkg/storage/engine/rocksdb.go
+++ b/pkg/storage/engine/rocksdb.go
@@ -1632,6 +1632,7 @@ func (r *rocksDBBatch) ApplyBatchRepr(repr []byte, sync bool) error {
        if r.distinctOpen {
                panic("distinct batch open")
        }
+       r.distinctNeedsFlush = true
        return r.builder.ApplyRepr(repr)
 }
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34493#-:-LXdbfS_0bPIqfVuyGRN:b-sdxxak)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by tbg** [comment]
I discovered this working on #34287 (migrating the truncated state to a new key). It adds a write of this unreplicated key downstream of Raft, after the write batch is applied and the Distinct() is taken. My tests were failing and this was why. I'll have to take stock of what else could be affected by this bug. Hopefully not much as we don't typically use Distinct() much.

PS are you married to the fact that a Distinct() on top of a WriteOnlyBatch allows reads, but reads straight from the underlying engine? That was another troublemaker that caused me some time. Very unintuitive as you can't read from a WriteOnlyBatch.

**Comment by petermattis** [comment]
> PS are you married to the fact that a Distinct() on top of a WriteOnlyBatch allows reads, but reads straight from the underlying engine? That was another troublemaker that caused me some time. Very unintuitive as you can't read from a WriteOnlyBatch.

I agree that seems unintuitive. No, I'm not wedded to that behavior and would be surprised if we're relying on it.

`Distinct` is really a hack. I hope someday that we can make it go away.

**Comment by tbg** [comment]
> I agree that seems unintuitive. No, I'm not wedded to that behavior and would be surprised if we're relying on it.

Looks like we relied on it https://github.com/cockroachdb/cockroach/issues/13402 at some point. The code referenced there is still there today, so I doubt we can change the semantics easily. (Ideally the read would use the engine directly and not through the batch, but that plumbing seems awkward).

Updated the PR with proper fix, ready for review.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34493#-:-LXl4jVV5hfujBQvqnRn:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by tbg** [comment]
bors r=petermattis

**Pull request merged**
