### PR TITLE
geo,geoindex: use bounding box for geography coverings that are bad

### PR DESCRIPTION
**Pull request by sumeerbhola**
This change uses a covererInterface implementation for geography
that notices when a covering is using top-level cells of all faces
and in that case uses the bounding box to compute the covering.

Also changed the bounding box calculation for geography shapes to
use only the points and not first construct s2.Regions. The latter
causes marginally bad shapes to continue to have bad coverings since
the bounding box also covers the whole earth.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
btw, data driven tests that are not `datadriven` tests, like `bbox_test.go` are painful to modify.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51305#-:-MBu6Gip9JOKgUGf4mha:bhufjsp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51305)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/geo/parse_test.go, line 395 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51305#-MBu6auA-ZjuF_ENTutF:-MBu6auA-ZjuF_ENTutG:b-3ioicc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab7edc34e1cefd8dde6108b102de0e05d06d5af1/pkg/geo/parse_test.go#L395)):*
> ```Go
> 					ShapeType: geopb.ShapeType_Point,
> 					BoundingBox: &geopb.BoundingBox{
> 						LoX: 0.017453292519943295,
> ```

the values in the tests change since we are avoiding the roundtrip to `s2.Point` which is using X, Y, Z coordinates and not lat-lng.
___
*[pkg/geo/geogfn/covers_test.go, line 407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51305#-MBu6wn524a7k72s1vSZ:-MBu6wn524a7k72s1vS_:b-ralii7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab7edc34e1cefd8dde6108b102de0e05d06d5af1/pkg/geo/geogfn/covers_test.go#L407)):*
> ```Go
> 		{
> 			"POLYGON covers POINT lying inside latitudinal boundary",
> 			"POLYGON((150 85, 160 85, -20 85, -30 85, 150 85))",
> ```

this "self intersecting" polygon was probably generating an earth size polygon so the buggy test was passing.

**Review by otan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51305)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/geo/bbox.go, line 166 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51305#-MBuE0-o4UM1tnkV1_MR:-MBuE0-o4UM1tnkV1_MS:bz3re1r) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab7edc34e1cefd8dde6108b102de0e05d06d5af1/pkg/geo/bbox.go#L166)):*
> ```Go
> 		flatCoords := g.FlatCoords()
> 		for i := 0; i < len(flatCoords); i += g.Stride() {
> 			rect = rect.AddPoint(s2.LatLngFromDegrees(flatCoords[i+1], flatCoords[i]))
> ```

this will not work for bounding boxes crossing lat/lng boundaries. you will need to use `s2.RectBounder` here.
___
*[pkg/geo/geogfn/covers_test.go, line 407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51305#-MBu6wn524a7k72s1vSZ:-MBuEBjk8LteuOpNe89S:b-ixmxb7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab7edc34e1cefd8dde6108b102de0e05d06d5af1/pkg/geo/geogfn/covers_test.go#L407)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this "self intersecting" polygon was probably generating an earth size polygon so the buggy test was passing. 
</blockquote></details>

no this was deliberate. this should return true. you have passed the poles and generated an invalid bounding box.
___
*[pkg/geo/geogfn/intersects_test.go, line 192 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51305#-MBuEG2x2qZbUmGM3bpf:-MBuEG2x2qZbUmGM3bpg:bx0yen5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab7edc34e1cefd8dde6108b102de0e05d06d5af1/pkg/geo/geogfn/intersects_test.go#L192)):*
> ```Go
> 			"POLYGON intersects POINT lying inside latitudinal boundary",
> 			"POLYGON((150 85, 160 85, -20 85, -30 85, 150 85))",
> 			"POINT (150 85)",
> ```

same as above. this should be true for 88.

**Comment by otan** [comment]
___
*[pkg/geo/geogfn/covers_test.go, line 407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51305#-MBu6wn524a7k72s1vSZ:-MBuEp5A0qaJT8r70zJH:b-2az6ip) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab7edc34e1cefd8dde6108b102de0e05d06d5af1/pkg/geo/geogfn/covers_test.go#L407)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

no this was deliberate. this should return true. you have passed the poles and generated an invalid bounding box.
</blockquote></details>

(if you draw this out on a map, this polygon covers the north pole. try `drawgeography,Example,,"POLYGON((150 85, 160 85, -20 85, -30 85, 150 85))"` on geoviz)

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51305)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/geo/bbox.go, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51305#-MBuQqFuA4uA-_RcSyP5:-MBuQqFuA4uA-_RcSyP6:buu4kmg) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab7edc34e1cefd8dde6108b102de0e05d06d5af1/pkg/geo/bbox.go#L148)):*
> ```Go
> // results in S2 and the other libraries we use. Therefore, instead of constructing s2.Region(s)
> // from the shape, which will expose us to S2's validity checks, we use the points directly to
> // compute the bounding box.
> ```

[nit] comments should be 80 columns wide

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51305)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/geo/geogfn/covers_test.go, line 407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51305#-MBu6wn524a7k72s1vSZ:-MBuagSY7HcQJuUj2e76:b-6lqe90) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab7edc34e1cefd8dde6108b102de0e05d06d5af1/pkg/geo/geogfn/covers_test.go#L407)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

(if you draw this out on a map, this polygon covers the north pole. try `drawgeography,Example,,"POLYGON((150 85, 160 85, -20 85, -30 85, 150 85))"` on geoviz)
</blockquote></details>

ah yes, this bounding box logic change is totally misguided.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51305)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/geo/bbox.go, line 168 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51305#-MBumXhQBZD9po0K_0gw:-MBumXhQBZD9po0K_0gx:b-gqsb1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/596476d42c1e7adbf85d7eef0f2445996feccdfc/pkg/geo/bbox.go#L168)):*
> ```Go
> 	case *geom.Polygon:
> 		for i := 0; i < g.NumLinearRings(); i++ {
> 			rect = rect.Union(lineBBox(g.LinearRing(i), true /* isRing */))
> ```

does this have to be forced as CCW? I think the original code was this way to account for that.
(and was one of the reasons i let it be translated to S2 regions first -- s2 does this complex logic for us :P) 
___
*[pkg/geo/bbox.go, line 206 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51305#-MBumk6_1qYPzVNu1vnS:-MBumk6a1iq8aoT2l6fh:b-ujx3ak) ([raw file](https://github.com/cockroachdb/cockroach/blob/596476d42c1e7adbf85d7eef0f2445996feccdfc/pkg/geo/bbox.go#L206)):*
> ```Go
> }
> 
> func lineBBox(g flatGeom, isRing bool) s2.Rect {
> ```

can you add comments for and flatBBox and above what what the difference is ?

I'd probalbly rename it to `lineS2Rect` (and above) to make it a little clearer.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51305)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan, @rytaft, and @sumeerbhola)

___
*[pkg/geo/bbox.go, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51305#-MBuQqFuA4uA-_RcSyP5:-MBumPSbAya04VtbPKeR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab7edc34e1cefd8dde6108b102de0e05d06d5af1/pkg/geo/bbox.go#L148)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] comments should be 80 columns wide
</blockquote></details>

Done.
___
*[pkg/geo/bbox.go, line 166 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51305#-MBuE0-o4UM1tnkV1_MR:-MBumbdaCiPnpVfpFyUl:b-4ocp4y) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab7edc34e1cefd8dde6108b102de0e05d06d5af1/pkg/geo/bbox.go#L166)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

this will not work for bounding boxes crossing lat/lng boundaries. you will need to use `s2.RectBounder` here.
</blockquote></details>

Switched to using `s2.RectBounder` for line segments. I haven't changed the calculation for points.
This seems to work, but I need to think about this more.
___
*[pkg/geo/geogfn/covers_test.go, line 407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51305#-MBu6wn524a7k72s1vSZ:-MBunEjL5YIHdQL7ayRk:b-9ndy11) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab7edc34e1cefd8dde6108b102de0e05d06d5af1/pkg/geo/geogfn/covers_test.go#L407)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

ah yes, this bounding box logic change is totally misguided.
</blockquote></details>

Undid this change.
___
*[pkg/geo/geogfn/intersects_test.go, line 192 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51305#-MBuEG2x2qZbUmGM3bpf:-MBunHW9CvdSTqpODzz_:b-9ndy11) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab7edc34e1cefd8dde6108b102de0e05d06d5af1/pkg/geo/geogfn/intersects_test.go#L192)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

same as above. this should be true for 88.
</blockquote></details>

Undid this change.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51305)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rytaft)

___
*[pkg/geo/bbox.go, line 168 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51305#-MBumXhQBZD9po0K_0gw:-MDKolbr3ImA4KlhAXnM:b-n4zpj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/596476d42c1e7adbf85d7eef0f2445996feccdfc/pkg/geo/bbox.go#L168)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

does this have to be forced as CCW? I think the original code was this way to account for that.
(and was one of the reasons i let it be translated to S2 regions first -- s2 does this complex logic for us :P) 
</blockquote></details>

I added some test cases to `bbox_test.go` and it doesn't change the result. But I can't interpret a couple of results (same question as in `covers_test.go`)
___
*[pkg/geo/bbox.go, line 206 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51305#-MBumk6_1qYPzVNu1vnS:-MDKk1cSBfzhfsCMbU9x:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/596476d42c1e7adbf85d7eef0f2445996feccdfc/pkg/geo/bbox.go#L206)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

can you add comments for and flatBBox and above what what the difference is ?

I'd probalbly rename it to `lineS2Rect` (and above) to make it a little clearer.
</blockquote></details>

Done
___
*[pkg/geo/geogfn/covers_test.go, line 414 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51305#-MDKiT_Z8Rv4B0BsEKNp:-MDKiT_Z8Rv4B0BsEKNq:b-kmp0gx) ([raw file](https://github.com/cockroachdb/cockroach/blob/596476d42c1e7adbf85d7eef0f2445996feccdfc/pkg/geo/geogfn/covers_test.go#L414)):*
> ```Go
> 			"POLYGON does not cover POINT lying outside latitudinal boundary",
> 			"POLYGON((150 85, 160 85, -20 85, -30 85, 150 85))",
> 			"POINT (170 88)",
> ```

Can you remind me why this returns false? It seems that this polygon covers the north pole and includes every latitude >= 85.
Hmm, this doesn't look like a correct polygon since it is going east from the prime meridian due to longitudes 150, 160, then after it loops around from 160 to -20, it then turns around to go back to -30. Am I missing something?

**Comment by otan** [comment]
___
*[pkg/geo/geogfn/covers_test.go, line 414 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51305#-MDKiT_Z8Rv4B0BsEKNp:-MDb4xJtCvGwh-WpTFAv:bul99yn) ([raw file](https://github.com/cockroachdb/cockroach/blob/596476d42c1e7adbf85d7eef0f2445996feccdfc/pkg/geo/geogfn/covers_test.go#L414)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you remind me why this returns false? It seems that this polygon covers the north pole and includes every latitude >= 85.
Hmm, this doesn't look like a correct polygon since it is going east from the prime meridian due to longitudes 150, 160, then after it loops around from 160 to -20, it then turns around to go back to -30. Am I missing something?
</blockquote></details>

The point lies outside the box: https://geoviz.crdb.dev/#ZHJhd2dlb2dyYXBoeSxQb2x5Z29uLCwiUE9MWUdPTigoMTUwIDg1LCAxNjAgODUsIC0yMCA4NSwgLTMwIDg1LCAxNTAgODUpKSIKZHJhd2dlb2dyYXBoeSxQb2ludCwsIlBPSU5UICgxNzAgODgpIgo=

**Comment by otan** [comment]
___
*[pkg/geo/geogfn/covers_test.go, line 414 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51305#-MDKiT_Z8Rv4B0BsEKNp:-MDb58Cu3YIkCEBlyPtq:b4cfjlg) ([raw file](https://github.com/cockroachdb/cockroach/blob/596476d42c1e7adbf85d7eef0f2445996feccdfc/pkg/geo/geogfn/covers_test.go#L414)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

The point lies outside the box: https://geoviz.crdb.dev/#ZHJhd2dlb2dyYXBoeSxQb2x5Z29uLCwiUE9MWUdPTigoMTUwIDg1LCAxNjAgODUsIC0yMCA4NSwgLTMwIDg1LCAxNTAgODUpKSIKZHJhd2dlb2dyYXBoeSxQb2ludCwsIlBPSU5UICgxNzAgODgpIgo=
</blockquote></details>

Exaggerating the latitudes a little here -- https://geoviz.crdb.dev/#ZHJhd2dlb2dyYXBoeSxQb2x5Z29uLCwiUE9MWUdPTigoMTUwIDc1LCAxNjAgNzUsIC0yMCA3NSwgLTMwIDc1LCAxNTAgNzUpKSIKZHJhd2dlb2dyYXBoeSxQb2ludCwsIlBPSU5UICgxNzAgODApIgo=

160 -> -20 just goes to the other side of the pole.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51305)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rytaft)

___
*[pkg/geo/bbox_test.go, line 58 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51305#-MDogsTyEdlawkpZqH8P:-MDogsTzCWez-E98yeSH:bxvpqhx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e17dd00c820f88da75ba23c378eac90250e98880/pkg/geo/bbox_test.go#L58)):*
> ```Go
> 			&geopb.BoundingBox{LoX: 0.017453292519943292, LoY: 0.01745329251994285, HiX: 0.03490658503988659, HiY: 0.03490791314678354}},
> 		{geopb.SpatialObjectType_GeographyType, geom.NewPolygonFlat(geom.XY, []float64{150, 85, 160, 85, -20, 85, -30, 85, 150, 85}, []int{10}),
> 			&geopb.BoundingBox{LoX: -3.141592653589793, LoY: 1.4835298641951797, HiX: 3.141592653589793, HiY: 1.5707963267948966}},
> ```

I've changed this test to use the same polygon as in covers_test.go and in both orientations.
___
*[pkg/geo/geogfn/covers_test.go, line 414 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51305#-MDKiT_Z8Rv4B0BsEKNp:-MDogxn-4_Fl6dmRmQ1y:buzdhk) ([raw file](https://github.com/cockroachdb/cockroach/blob/596476d42c1e7adbf85d7eef0f2445996feccdfc/pkg/geo/geogfn/covers_test.go#L414)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Exaggerating the latitudes a little here -- https://geoviz.crdb.dev/#ZHJhd2dlb2dyYXBoeSxQb2x5Z29uLCwiUE9MWUdPTigoMTUwIDc1LCAxNjAgNzUsIC0yMCA3NSwgLTMwIDc1LCAxNTAgNzUpKSIKZHJhd2dlb2dyYXBoeSxQb2ludCwsIlBPSU5UICgxNzAgODApIgo=

160 -> -20 just goes to the other side of the pole.
</blockquote></details>

Duh, I forgot that the line connecting two points on the same latitude is a great circle and not a constant latitude line.
But is this a valid geography polygon? Don't the lines (160 85, -20 85) and (-30 85, 150 85) intersect? Is there a validity function for geography analogous to `ST_IsValid` for geometry?

**Review by otan — APPROVED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51305)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan, @rytaft, and @sumeerbhola)

___
*[pkg/geo/bbox.go, line 199 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51305#-MDppdDC3Np0geOfbUB2:-MDppdDD0Bn2YtP1jWPc:bu3l8qs) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ae325e2b4285c950d951a6f19c1afa4189577ff/pkg/geo/bbox.go#L199)):*
> ```Go
> // geogPointsBBox constructs a bounding box, represented as a s2.Rect, for the set
> // of points contained in g.
> func geogPointsBBox(g flatGeom) s2.Rect {
> ```

probably just take geom.T and take the interface?
___
*[pkg/geo/bbox.go, line 213 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51305#-MDpplUqCSp1-W205AZB:-MDpplUqCSp1-W205AZC:beb70z6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ae325e2b4285c950d951a6f19c1afa4189577ff/pkg/geo/bbox.go#L213)):*
> ```Go
> 	bounder := s2.NewRectBounder()
> 	flatCoords := g.FlatCoords()
> 	for i := 0; i < len(flatCoords); i += g.Stride() {
> ```

for linear rings, we always include the last point as the first point so i don't think you need the `isRing` condition. unless we deleted it somewhere.
___
*[pkg/geo/geogfn/covers_test.go, line 414 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51305#-MDKiT_Z8Rv4B0BsEKNp:-MDpoijN98WxnjaY4Fu8:b6o36xp) ([raw file](https://github.com/cockroachdb/cockroach/blob/596476d42c1e7adbf85d7eef0f2445996feccdfc/pkg/geo/geogfn/covers_test.go#L414)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Duh, I forgot that the line connecting two points on the same latitude is a great circle and not a constant latitude line.
But is this a valid geography polygon? Don't the lines (160 85, -20 85) and (-30 85, 150 85) intersect? Is there a validity function for geography analogous to `ST_IsValid` for geometry?
</blockquote></details>

They look parallel to me: https://geoviz.crdb.dev/#ZHJhd2dlb2dyYXBoeSxMaW5lIEEsLCJMSU5FU1RSSU5HKDE2MCA4NSwgLTIwIDg1KSIKZHJhd2dlb2dyYXBoeSxMaW5lIEIsLCJMSU5FU1RSSU5HICgtMzAgODUsIDE1MCA4NSkgIgo=

There's no analogous ST_IsValid for Geography in PostGIS. We could do our own.

**Review by otan — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, 1 of 4 files at r2, 3 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51305)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan, @rytaft, and @sumeerbhola)

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51305#-:-MDuLRbT5dOwh2JWltHm:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan, @rytaft, and @sumeerbhola)

___
*[pkg/geo/bbox.go, line 199 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51305#-MDppdDC3Np0geOfbUB2:-MDuJqkyCIKN1bCGd2KI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ae325e2b4285c950d951a6f19c1afa4189577ff/pkg/geo/bbox.go#L199)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

probably just take geom.T and take the interface?
</blockquote></details>

Done.
___
*[pkg/geo/bbox.go, line 213 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51305#-MDpplUqCSp1-W205AZB:-MDuKtQrCyWRS3O9oO-e:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ae325e2b4285c950d951a6f19c1afa4189577ff/pkg/geo/bbox.go#L213)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

for linear rings, we always include the last point as the first point so i don't think you need the `isRing` condition. unless we deleted it somewhere.
</blockquote></details>

Done.
___
*[pkg/geo/geogfn/covers_test.go, line 414 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51305#-MDKiT_Z8Rv4B0BsEKNp:-MDuL6ou7p9btKAK4vL3:b3l9pif) ([raw file](https://github.com/cockroachdb/cockroach/blob/596476d42c1e7adbf85d7eef0f2445996feccdfc/pkg/geo/geogfn/covers_test.go#L414)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

They look parallel to me: https://geoviz.crdb.dev/#ZHJhd2dlb2dyYXBoeSxMaW5lIEEsLCJMSU5FU1RSSU5HKDE2MCA4NSwgLTIwIDg1KSIKZHJhd2dlb2dyYXBoeSxMaW5lIEIsLCJMSU5FU1RSSU5HICgtMzAgODUsIDE1MCA4NSkgIgo=

There's no analogous ST_IsValid for Geography in PostGIS. We could do our own.
</blockquote></details>

Hmm -- I think they look parallel since it isn't showing the effect of the sphere wrapping around.

**Comment by otan** [comment]
___
*[pkg/geo/geogfn/covers_test.go, line 414 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51305#-MDKiT_Z8Rv4B0BsEKNp:-MDuWw-s0Sp4_TPbfVZh:bqrd98x) ([raw file](https://github.com/cockroachdb/cockroach/blob/596476d42c1e7adbf85d7eef0f2445996feccdfc/pkg/geo/geogfn/covers_test.go#L414)):*
> ```
> POLYGON((150 85, 160 85, -20 85, -30 85, 150 85))
> ```

I think -30 is on the opposite side to 150, and 160 is opposite of -20 (both is an addition/subtraction of 180 degrees), hence forming a rectangle.

**Pull request merged**
