### PR TITLE
ui: Update empty states for table components

### LINKED ISSUE #53422: ui: update empty states
Update the following empty states to align with the latest Cockroach Cloud/Design System empty states:

- statement table
- jobs table
- statement diagnostics table (on statement detail page)
- statement diagnostic history table (advanced debug)
- sessions table
- transaction table

Figma design links:
- [Console empty state designs](https://www.figma.com/file/uU9C1XSleeAu26CvTWwekX/obsrv_admin-ui-empty-states?node-id=128%3A0)
- Design system - [empty state component ](https://www.figma.com/file/B5AtEGdRbW3VxiBdg62TB8Xw/CRDB-Design-System_V2?node-id=1018%3A0)
- Design system - [empty state illustrations ](https://www.figma.com/file/B5AtEGdRbW3VxiBdg62TB8Xw/CRDB-Design-System_V2?node-id=46%3A3634) (scroll to bottom of page)

sample screenshot
Screen Shot 2020-08-25 at 1 24 14 PM

### PR DESCRIPTION
**Pull request by koorosh**
Resolves #53422 
~~Depends on https://github.com/cockroachdb/admin-ui-components/pull/29~~
Depends on https://github.com/cockroachdb/yarn-vendored/pull/41

Previously, tables with no data provided were replaced with
placeholders and weren't displayed at all.

Now, the representation of empty states for tables (statements,
transactions, sessions, statement diagnostics) is updated
according to designs. Empty state placeholder is rendered
inside of table with unified view and messages.

Release note (admin ui change): changed view for tables without
data on main pages.

Screens

Screen Shot 2020-09-28 at 7 12 47 PM
Screen Shot 2020-09-28 at 6 44 09 PM
Screen Shot 2020-09-29 at 5 40 37 PM
Screen Shot 2020-09-29 at 5 40 28 PM

### CODE REVIEW

**Review by nathanstilwell — COMMENTED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54943)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh)

___
*[pkg/ui/src/components/anchor/anchor.tsx, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54943#-MIyT5cw1JleWa-J4A8D:-MIyT5cw1JleWa-J4A8E:bmwkntc) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e5cad8f9971acd3f01aceec944c698d6f742b58/pkg/ui/src/components/anchor/anchor.tsx#L16)):*
I'm wondering what we are really getting out of this component over just creating an `<a>` for links in the application. I believe the biggest value comes from pairing an explicit component with a style module. I wonder if we could gain some efficiently by expending the `HTMLAnchorElement` props. We could then only explicitly set the `classname` and `onClick` prop.

```
type OwnProps = {
  onClick?: (event: React.MouseEvent<HTMLAnchorElement, MouseEvent>) => void;
};

type NativeAnchorProps = Omit<
  React.HTMLAttributes<HTMLAnchorElement>,
  keyof OwnProps
>;

type AnchorProps = NativeAnchorProps & OwnProps;

const cx = classnames.bind(styles);

export const Anchor: FunctionComponent<AnchorProps> = ({ onClick, className, children, ...rest}) =>(
    <a
      className={cx("crl-anchor", className)}
      onClick={onClick}
      {...rest}
    >
      {children}
    </a>
  );
}

```

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54943)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nathanstilwell)

___
*[pkg/ui/src/components/anchor/anchor.tsx, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54943#-MIyT5cw1JleWa-J4A8D:-MJ1KZWS5XNR8s0M-kP2:biusylf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e5cad8f9971acd3f01aceec944c698d6f742b58/pkg/ui/src/components/anchor/anchor.tsx#L16)):*
<details><summary><i>Previously, nathanstilwell (Nathan Stilwell) wrote…</i></summary><blockquote>

I'm wondering what we are really getting out of this component over just creating an `<a>` for links in the application. I believe the biggest value comes from pairing an explicit component with a style module. I wonder if we could gain some efficiently by expending the `HTMLAnchorElement` props. We could then only explicitly set the `classname` and `onClick` prop.

```
type OwnProps = {
  onClick?: (event: React.MouseEvent<HTMLAnchorElement, MouseEvent>) => void;
};

type NativeAnchorProps = Omit<
  React.HTMLAttributes<HTMLAnchorElement>,
  keyof OwnProps
>;

type AnchorProps = NativeAnchorProps & OwnProps;

const cx = classnames.bind(styles);

export const Anchor: FunctionComponent<AnchorProps> = ({ onClick, className, children, ...rest}) =>(
    <a
      className={cx("crl-anchor", className)}
      onClick={onClick}
      {...rest}
    >
      {children}
    </a>
  );
}

```
</blockquote></details>

Nathan, I see your point, indeed, this component is only a wrapper on top of standard <a> tag.

Currently, it's "styled components" approach where target element is wrapped with custom styles and it provides us a good level of encapsulation for changes we apply to target element.

Do you mean to globally redefine `onClick` behavior and styles for <a> tag?

**Comment by dhartunian** [comment]
@koorosh this does not pass typecheck, can you update?

**Comment by koorosh** [comment]
> @koorosh this does not pass typecheck, can you update?

Looks okay now, may it be merged?

**Review by dhartunian — CHANGES_REQUESTED** [review]
Thanks for updating the PR, one last small issue to clean interfaces up.

> Reviewed 5 of 12 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54943#-:-MMq_TzrE4ztqW6zO6Gz:b-ce7ap)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh and @nathanstilwell)

___
*[pkg/ui/src/components/anchor/anchor.tsx, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54943#-MIyT5cw1JleWa-J4A8D:-MMqSDch-0ajmpsynZMH:b-oi0m1z) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e5cad8f9971acd3f01aceec944c698d6f742b58/pkg/ui/src/components/anchor/anchor.tsx#L16)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Nathan, I see your point, indeed, this component is only a wrapper on top of standard <a> tag.

Currently, it's "styled components" approach where target element is wrapped with custom styles and it provides us a good level of encapsulation for changes we apply to target element.

Do you mean to globally redefine `onClick` behavior and styles for <a> tag?
</blockquote></details>

@koorosh what Nathan means here is that the `Anchor` component doesn't pass through all standard `a` tag props and is therefore not a drop-in replacement for an `a` tag on its own since it doesn't implement the full DOM API.
___
*[pkg/ui/src/views/jobs/jobTable.tsx, line 138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54943#-MMq_96_-kMJ3OLVX_Rp:-MMq_96_-kMJ3OLVX_Rq:b-dfotzm) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d2ce39b90889679e8eeaaedea6a739ac661fc7b/pkg/ui/src/views/jobs/jobTable.tsx#L138)):*
> ```XML
>           columns={jobsTableColumns}
>           renderNoResult={this.noJobResult()}
>           empty={isEmpty(jobs) && !this.props.isUsedFilter}
> ```

Can we remove the `empty` and `emptyProps` fields from the `SortedTable` props definition? I think it would be good to stop using them.

**Comment by koorosh** [comment]
@dhartunian , thanks for clarification! I've updated PR with those changes.

**Review by dhartunian — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54943#-:-MMv4nVx8CAluKnUSgjN:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @koorosh and @nathanstilwell)

**Pull request merged**
