### PR TITLE
sql: refactor IndexedVars and remove Used field

### PR DESCRIPTION
**Pull request by mgartner**
#### sql: remove unused "source" parameter in planner.analyzeExpr

The `source` parameter of `planner.analyzeExrp` was unused, so it has
been removed. The `planner.resolveNames` function and the
`planner.nameResolutionVisitor` field have also been removed as a
result.

Release note: None

#### schemaexpr: refactor NameResolutionVisitor

The `NameResolutionVisitor` is not used outside the `schemaexpr`
package, so it has been unexported. Additionally, it no longer attempts
to rebind indexed vars or normalized function names. Neither of these
steps are necessary because this struct is only used to resolved column
names to indexed vars for computed column and partial index expressions.

Release note: None

#### schemaexpr: rename select_name_resolution.go to name.go

Release note: None

#### sem/tree: add IndexedVarHelper.RebindTyped

This commit splits `IndexedVarHelper.Rebind` into two functions, one to
rebind untyped expressions, and one to rebind typed expressions. This is
a mechanical change that will make subsequent changes easier.

Release note: None

#### sem/tree,execinfrapb: remove ivarBinder

The `execinfrapb.ivarBinder` struct has been removed. In its place we
use the `IndexedVarHelper.Rebind` method. I believe that the special
behavior of `BindIfUnbound` where it does not bind an already bound
indexed var is vestigial and unused. Therefore, that logic is not
preserved.

Release note: None

#### sem/tree: remove IndexedVarHelper.IndexedVarUsed method

The `IndexedVarHelper.IndexedVarUsed` method was only used in tests. It
has been removed. Tests that used it now track usage of indexed vars in
their own implementation of the `IndexedVarContainer` interface.

Release note: None

#### sem/tree: remove IndexedVar.Used field

The `IndexedVar.Used` field has been removed because it was no longer
used. This shrinks the size of the `IndexedVar` struct from 40 bytes to
32 bytes, a 20% reduction. This reduces allocate memory, especially for
workloads with queries involving many columns.

Informs #117546

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 13 of 13 files at r1, 5 of 5 files at r2, 4 of 4 files at r3, 2 of 2 files at r4, 9 of 9 files at r5, 2 of 2 files at r6, 6 of 6 files at r7, 4 of 4 files at r8, 3 of 3 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118683)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @michae2)

___
*[`pkg/sql/sem/tree/indexed_vars.go` line 254 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118683#-NpfozYjCpf-yM8_gCq_:-NpfozYjCpf-yM8_gCqa:bhaqh4j) ([raw file](https://github.com/cockroachdb/cockroach/blob/3eb883095a7ad2e85227359097a9898b5ed5ff68/pkg/sql/sem/tree/indexed_vars.go#L254)):*
> ```Go
> // MakeTypesOnlyIndexedVarHelper creates an IndexedVarHelper which provides
> // the given types for indexed vars. It does not support evaluation, unless
> // RebindTyped is used with another container which supports evaluation.
> ```

nit: probably should mention both `Rebind` and `RebindTyped`?
___
*[`pkg/sql/sem/tree/indexed_vars.go` line 211 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/118683#-Npfq01D4TaMSw7YOJtU:-Npfq01D4TaMSw7YOJtV:b91o9up) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b4d5345d07e3c77f091b92b1e5bf76b460fbbad/pkg/sql/sem/tree/indexed_vars.go#L211)):*
> ```Go
> // VisitPre implements the Visitor interface.
> func (h *IndexedVarHelper) VisitPre(expr Expr) (recurse bool, newExpr Expr) {
> 	if iv, ok := expr.(*IndexedVar); ok && !h.reboundIVars.Contains(iv.Idx) {
> ```

Hm, this seems somewhat suspicious to me - like is it possible that we have two different `tree.IndexedVar` objects that have the same index? If so, previously we would bind both to the same index, but now we bind the first one and ignore the second one (?).

**Comment by mgartner** [comment]
*[`pkg/sql/sem/tree/indexed_vars.go` line 211 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/118683#-Npfq01D4TaMSw7YOJtU:-NpfvuO36oqnbY-9zOUY:b-83y3gi) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b4d5345d07e3c77f091b92b1e5bf76b460fbbad/pkg/sql/sem/tree/indexed_vars.go#L211)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Hm, this seems somewhat suspicious to me - like is it possible that we have two different `tree.IndexedVar` objects that have the same index? If so, previously we would bind both to the same index, but now we bind the first one and ignore the second one (?).
</blockquote></details>

Ehh ya, maybe this is wrong. I just can't figure what on earth BindIfUnbound was trying to do. Maybe I can just remove this check.

**Comment by mgartner** [comment]
*[`pkg/sql/sem/tree/indexed_vars.go` line 254 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118683#-NpfozYjCpf-yM8_gCq_:-NpfwCuG9cwgIvxBcJKo:b-erh7p1) ([raw file](https://github.com/cockroachdb/cockroach/blob/3eb883095a7ad2e85227359097a9898b5ed5ff68/pkg/sql/sem/tree/indexed_vars.go#L254)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: probably should mention both `Rebind` and `RebindTyped`?
</blockquote></details>

I suppose, though you won't be able to evaluate an untyped expression.

**Comment by mgartner** [comment]
*[`pkg/sql/sem/tree/indexed_vars.go` line 211 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/118683#-Npfq01D4TaMSw7YOJtU:-Npg3WSjDqxNtz-QPhMx:b-l5ogvz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b4d5345d07e3c77f091b92b1e5bf76b460fbbad/pkg/sql/sem/tree/indexed_vars.go#L211)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Ehh ya, maybe this is wrong. I just can't figure what on earth BindIfUnbound was trying to do. Maybe I can just remove this check.
</blockquote></details>

I don't believe `BindIfUnbound` was doing anything meaningful in the presence of the `Used` boolean. In fact, I believe it was probably buggy, but nothing surfaced because it would never encounter a `Used=true` boolean. I've removed the check here.

**Review by yuzefovich — APPROVED** [review]
:lgtm: (assuming the CI is green :smiley: )

> Reviewed 4 of 4 files at r11, 2 of 2 files at r12, 3 of 3 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118683#-:-Npg5P1QAsAvjnCOjwRK:bn580u)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @michae2)

___
*[`pkg/sql/sem/tree/indexed_vars.go` line 211 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/118683#-Npfq01D4TaMSw7YOJtU:-Npg59SOAYaup-07RE_a:bj2oikd) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b4d5345d07e3c77f091b92b1e5bf76b460fbbad/pkg/sql/sem/tree/indexed_vars.go#L211)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I don't believe `BindIfUnbound` was doing anything meaningful in the presence of the `Used` boolean. In fact, I believe it was probably buggy, but nothing surfaced because it would never encounter a `Used=true` boolean. I've removed the check here.
</blockquote></details>

Sounds reasonable to me - don't forget to update the commit message of the fifth commit to reflect this change.

**Comment by mgartner** [comment]
*[`pkg/sql/sem/tree/indexed_vars.go` line 211 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/118683#-Npfq01D4TaMSw7YOJtU:-Npg8EDeDSUAOQUL_416:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b4d5345d07e3c77f091b92b1e5bf76b460fbbad/pkg/sql/sem/tree/indexed_vars.go#L211)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Sounds reasonable to me - don't forget to update the commit message of the fifth commit to reflect this change.
</blockquote></details>

Done.

**Comment by mgartner** [comment]
TFTR!

bors r+

**Pull request merged**
