### PR TITLE
allow custom list of range ID for RangesRequest and RaftDeb…

### PR DESCRIPTION
**Pull request by mberhault**
…ugRequest

the raft debug endpoint can be painfully slow when working with a large
cluster, and pointless if we only care about a specific range (see some
examples in #10736)

google.api.http automatically allows fields to be filled in from query
parameters (well, only fields that are not already specified in the
path).

This means that for both the `/_status/raft` and `/_status/ranges`
endpoints, we can specify something along the lines of:

`/_status/raft?range_ids=21&range_ids=2`

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13587)

### CODE REVIEW

**Comment by mberhault** [comment]
my UI generator stuff does not work, so none of the generated files in pkg/ui/ have been refreshed.

**Comment by BramGruneir** [comment]
I've generated the files for you, amended the commit and pushed it to my branch, you can grab it if you want.
https://github.com/BramGruneir/cockroach/tree/marc/specify_ranges

**Comment by BramGruneir** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/server/status.go, line 635 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-Kd-QEaCM6fW_emIJWUS:-Kd-QEaCM6fW_emIJWUT:by48ip) ([raw file](https://github.com/cockroachdb/cockroach/blob/761f357d25e1a8e4bcdc780c1c98f40df9b80590/pkg/server/status.go#L635)):*
> ```Go
> 		// Specific ranges requested:
> 		for _, rid := range req.Ranges {
> 			rep, err := store.GetReplica(rid)
> ```

Could you reuse the function from the all ranges case?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-:-Kd-QSlmq-yRvtBIyMeC:bnfp4nl)*

**Comment by tamird** [comment]
Should be easy to add a test for this.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/server/status.go, line 486 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-Kd07fSVYzIz8ZyW__x4:-Kd07fSWs1KbRLses7y9:blxuf9o) ([raw file](https://github.com/cockroachdb/cockroach/blob/761f357d25e1a8e4bcdc780c1c98f40df9b80590/pkg/server/status.go#L486)):*
> ```Go
> 		go func() {
> 			defer wg.Done()
> 			ranges, err := s.Ranges(ctx, &serverpb.RangesRequest{NodeId: nodeID.String(), Ranges: req.Ranges})
> ```

probably better to make a shallow copy and only overwrite the node id:
```
nodeReq := *req
nodeReq.NodeID = nodeID.String()
ranges, err := s.Ranges(ctx, &nodeReq)
```

---

*[pkg/server/status.go, line 611 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-Kd08-jWdta3luV3cRf6:-Kd08-jWdta3luV3cRf7:b51li62) ([raw file](https://github.com/cockroachdb/cockroach/blob/761f357d25e1a8e4bcdc780c1c98f40df9b80590/pkg/server/status.go#L611)):*
> ```Go
> 	err = s.stores.VisitStores(func(store *storage.Store) error {
> 		if len(req.Ranges) == 0 {
> 			// All ranges requested:
> ```

these are separate comments, better to leave a newline between them.

---

*[pkg/server/serverpb/status.proto, line 105 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-Kd07SUyseRn6SJWwbEs:-Kd07SUzm9GuLf4rmNSR:bk50gok) ([raw file](https://github.com/cockroachdb/cockroach/blob/761f357d25e1a8e4bcdc780c1c98f40df9b80590/pkg/server/serverpb/status.proto#L105)):*
> ```protobuf
>   // forwarding is necessary.
>   string node_id = 1;
>   repeated int64 ranges = 2
> ```

why not `range_ids`? ditto below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-:-Kd08G7aZnELaSJRlNgw:b-6kxegr)*

**Comment by mberhault** [comment]
@BramGruneir: go ahead and grab it if you like, you're working on that part of the code anyway.

**Comment by tamird** [comment]
@bramgruneir you can push to this branch on Marc's fork, too.

On Feb 15, 2017 08:32, "marc" <notifications@github.com> wrote:

@BramGruneir <https://github.com/BramGruneir>: go ahead and grab it if you
like, you're working on that part of the code anyway.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/cockroachdb/cockroach/pull/13587#issuecomment-280011284>,
or mute the thread

**Comment by BramGruneir** [comment]
Of course, but I don't like to push (force push at that) to other's branches without permission.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-:-Kd1Hqkr8y-p48vurDFN:b-lgxtet)*

**Comment by tamird** [comment]
Seems like you have marc's permission, I mean.

**Comment by mberhault** [comment]
I wasn't going to merge this, but I got the UI dependencies installed properly, so I can now generate js.

---

Review status: 1 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/server/status.go, line 486 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-Kd07fSVYzIz8ZyW__x4:-Kd6Lva8Vnl9j7HWSFhU:bylo0tm) ([raw file](https://github.com/cockroachdb/cockroach/blob/761f357d25e1a8e4bcdc780c1c98f40df9b80590/pkg/server/status.go#L486)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

probably better to make a shallow copy and only overwrite the node id:
```
nodeReq := *req
nodeReq.NodeID = nodeID.String()
ranges, err := s.Ranges(ctx, &nodeReq)
```
</blockquote></details>

not sure how that helps. it doesn't cut down on the allocations.

---

*[pkg/server/status.go, line 611 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-Kd08-jWdta3luV3cRf6:-Kd6M659hIKUHQ5DkOJ8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/761f357d25e1a8e4bcdc780c1c98f40df9b80590/pkg/server/status.go#L611)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

these are separate comments, better to leave a newline between them.
</blockquote></details>

Done.

---

*[pkg/server/status.go, line 635 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-Kd-QEaCM6fW_emIJWUS:-Kd6LZSrnF66hU52HzJo:b-u3p0qx) ([raw file](https://github.com/cockroachdb/cockroach/blob/761f357d25e1a8e4bcdc780c1c98f40df9b80590/pkg/server/status.go#L635)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Could you reuse the function from the all ranges case?
</blockquote></details>

I could, but that would only be for the append, the rest is different.

---

*[pkg/server/serverpb/status.proto, line 105 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-Kd07SUyseRn6SJWwbEs:-Kd6LgoCI4uZU5Zym2Ak:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/761f357d25e1a8e4bcdc780c1c98f40df9b80590/pkg/server/serverpb/status.proto#L105)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why not `range_ids`? ditto below.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-:-Kd6MFMfST1ZpJi2vDFZ:b-rwbd6b)*

**Comment by mberhault** [comment]
Still need tests, to do-no-merge remains.

---

Review status: 1 of 7 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-:-Kd6MQkYAuFGS0-SpNez:b-e9qyju)*

**Comment by mberhault** [comment]
this is now `/_status/raft?range_ids=21&range_ids=2`
I really don't like how using singular in the field makes the use of the array weird, but pluralizing makes individual use weird.

**Comment by mberhault** [comment]
Added test for `RaftDebug` endpoint.

**Comment by tamird** [comment]
@mberhault is that really the only URL that grpc-gateway will accept? I'm surprised but haven't looked at the docs or code.

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/server/status.go, line 486 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-Kd07fSVYzIz8ZyW__x4:-Kd6TJovxIrXXbU5I_UP:b9e6ea8) ([raw file](https://github.com/cockroachdb/cockroach/blob/761f357d25e1a8e4bcdc780c1c98f40df9b80590/pkg/server/status.go#L486)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

not sure how that helps. it doesn't cut down on the allocations.
</blockquote></details>

Sorry, I should have clarified - it is more indicative of the intent; you're wanting to reuse the original request except for the one field which you want to override.

---

*[pkg/server/status_test.go, line 470 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-Kd6Tw0uCNUSwFOL8CTE:-Kd6Tw0uCNUSwFOL8CTF:b-a21zrt) ([raw file](https://github.com/cockroachdb/cockroach/blob/d51d3cff5eb6180f0d08ca6e745f80660c2f5e7e/pkg/server/status_test.go#L470)):*
> ```Go
> 	}
> 
> 	req := "raft"
> ```

why not use https://godoc.org/net/url#Values here? then you'd have `url := "raft?" + queryValues.Encode()`.

---

*[pkg/server/status_test.go, line 489 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-Kd6ULnbKvzq0vAKUPeS:-Kd6ULnbKvzq0vAKUPeT:bdr239q) ([raw file](https://github.com/cockroachdb/cockroach/blob/d51d3cff5eb6180f0d08ca6e745f80660c2f5e7e/pkg/server/status_test.go#L489)):*
> ```Go
> 	}
> 	if len(resp.Ranges) != 2 {
> 		t.Errorf("expected exactly two ranges in response, got %d", len(resp.Ranges))
> ```

isn't this redundant with the check below?

---

*[pkg/server/status_test.go, line 494 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-Kd6UEyJKrpxo8bunYUt:-Kd6UEyJKrpxo8bunYUu:beq24vz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d51d3cff5eb6180f0d08ca6e745f80660c2f5e7e/pkg/server/status_test.go#L494)):*
> ```Go
> 	for _, reqID := range requestedIDs {
> 		if _, ok := resp.Ranges[reqID]; !ok {
> 			t.Errorf("request was %s, but range ID %d not returned: %+v", req, reqID, resp.Ranges)
> ```

"request" is really a URL so this message is slightly misleading

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-:-Kd6Te9Mk0yHk9CCdV5m:bej52cl)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/server/status_test.go, line 489 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-Kd6ULnbKvzq0vAKUPeS:-Kd6USj21HgxpOhoY71J:b-yjg781) ([raw file](https://github.com/cockroachdb/cockroach/blob/d51d3cff5eb6180f0d08ca6e745f80660c2f5e7e/pkg/server/status_test.go#L489)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

isn't this redundant with the check below?
</blockquote></details>

Ah nevermind, it's checking that no unexpected ranges were also included. might be clearer if this checked for at most two ranges (to avoid duplicate errors below)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587)*

**Comment by mberhault** [comment]
not sure what you mean here.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/server/status.go, line 486 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-Kd07fSVYzIz8ZyW__x4:-Kd6b8Vw8SVxgJCNqzBl:b-e4myu5) ([raw file](https://github.com/cockroachdb/cockroach/blob/761f357d25e1a8e4bcdc780c1c98f40df9b80590/pkg/server/status.go#L486)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Sorry, I should have clarified - it is more indicative of the intent; you're wanting to reuse the original request except for the one field which you want to override.
</blockquote></details>

this feels pretty clear as is.

---

*[pkg/server/status_test.go, line 470 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-Kd6Tw0uCNUSwFOL8CTE:-Kd6bWIZdfiHlgN1xhkq:bqihu2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/d51d3cff5eb6180f0d08ca6e745f80660c2f5e7e/pkg/server/status_test.go#L470)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why not use https://godoc.org/net/url#Values here? then you'd have `url := "raft?" + queryValues.Encode()`.
</blockquote></details>

feels a little heavy to use a URL object when we don't really need to.

---

*[pkg/server/status_test.go, line 489 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-Kd6ULnbKvzq0vAKUPeS:-Kd6bmr49yWJilUQAdaD:bbvj7jb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d51d3cff5eb6180f0d08ca6e745f80660c2f5e7e/pkg/server/status_test.go#L489)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Ah nevermind, it's checking that no unexpected ranges were also included. might be clearer if this checked for at most two ranges (to avoid duplicate errors below)
</blockquote></details>

added comments to clarify checks.

---

*[pkg/server/status_test.go, line 494 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-Kd6UEyJKrpxo8bunYUt:-Kd6bV0cKAeV2ouhiRXl:b-n5a8s4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d51d3cff5eb6180f0d08ca6e745f80660c2f5e7e/pkg/server/status_test.go#L494)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

"request" is really a URL so this message is slightly misleading
</blockquote></details>

changed to reqURI.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-:-Kd6b2zBPhSPc4A96Eni:b-sjzoop)*

**Comment by tamird** [comment]
I was thinking there might be a different way to encode an array in the URL, but it seems there isn't.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/server/status.go, line 486 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-Kd07fSVYzIz8ZyW__x4:-Kd6dCZUw0y78UZDMvxF:bl8hnss) ([raw file](https://github.com/cockroachdb/cockroach/blob/761f357d25e1a8e4bcdc780c1c98f40df9b80590/pkg/server/status.go#L486)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

this feels pretty clear as is.
</blockquote></details>

You're kicking the can to the next person who adds a parameter here, but OK.

---

*[pkg/server/status_test.go, line 470 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-Kd6Tw0uCNUSwFOL8CTE:-Kd6ccfGHQH9nY_BmC0z:b-uwfram) ([raw file](https://github.com/cockroachdb/cockroach/blob/d51d3cff5eb6180f0d08ca6e745f80660c2f5e7e/pkg/server/status_test.go#L470)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

feels a little heavy to use a URL object when we don't really need to.
</blockquote></details>

you mean a url.Values object? feels unnecessarily opaque to not use one when the precedent for it is everywhere.

---

*[pkg/server/status_test.go, line 489 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-Kd6ULnbKvzq0vAKUPeS:-Kd6d3uQfEc2KHyQ-FuN:b-w06qvx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d51d3cff5eb6180f0d08ca6e745f80660c2f5e7e/pkg/server/status_test.go#L489)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

added comments to clarify checks.
</blockquote></details>

I don't think these comments help. Feel free to remove them if you don't intend to make the checks non-overlapping.

---

*[pkg/server/status_test.go, line 494 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-Kd6UEyJKrpxo8bunYUt:-Kd6cSZ5fBK3wedfkTTy:b1m01n) ([raw file](https://github.com/cockroachdb/cockroach/blob/d51d3cff5eb6180f0d08ca6e745f80660c2f5e7e/pkg/server/status_test.go#L494)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

changed to reqURI.
</blockquote></details>

I was saying the error string is misleading.

---

*[pkg/server/status_test.go, line 480 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-Kd6cxV_6KOx7lRQAvjI:-Kd6cxV_6KOx7lRQAvjJ:bnk5xkm) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b46aa5001feafd336c18066ea4ee5b7966da2ec/pkg/server/status_test.go#L480)):*
> ```Go
> 		reqURI += fmt.Sprintf("range_ids=%d", id)
> 		requestedIDs = append(requestedIDs, id)
> 		if len(requestedIDs) >= 2 {
> ```

why not `for id, _ := resp.Ranges[:2] {` instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-:-Kd6eC0KOneIxwpTvJ02:b-dqiana)*

**Comment by mberhault** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/server/status_test.go, line 489 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-Kd6ULnbKvzq0vAKUPeS:-Kd6f4c7igCQsENu27Cl:bxymc60) ([raw file](https://github.com/cockroachdb/cockroach/blob/d51d3cff5eb6180f0d08ca6e745f80660c2f5e7e/pkg/server/status_test.go#L489)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I don't think these comments help. Feel free to remove them if you don't intend to make the checks non-overlapping.
</blockquote></details>

one checks that we get the right number of ranges back, the other checks that they are the right ranges. I could do the first check to make sure that we don't get more than two, but at that point, why not check for exactly two?

---

*[pkg/server/status_test.go, line 494 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-Kd6UEyJKrpxo8bunYUt:-Kd6f3gl9NU7AzkpWaNj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d51d3cff5eb6180f0d08ca6e745f80660c2f5e7e/pkg/server/status_test.go#L494)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I was saying the error string is misleading.
</blockquote></details>

Done.

---

*[pkg/server/status_test.go, line 480 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-Kd6cxV_6KOx7lRQAvjI:-Kd6fJYecap94oBlMhkD:b-unisnh) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b46aa5001feafd336c18066ea4ee5b7966da2ec/pkg/server/status_test.go#L480)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why not `for id, _ := resp.Ranges[:2] {` instead?
</blockquote></details>

because it's a map

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/server/status_test.go, line 489 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-Kd6ULnbKvzq0vAKUPeS:-Kd6h71vjIf_nDndb5KY:bmfkh1z) ([raw file](https://github.com/cockroachdb/cockroach/blob/d51d3cff5eb6180f0d08ca6e745f80660c2f5e7e/pkg/server/status_test.go#L489)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

one checks that we get the right number of ranges back, the other checks that they are the right ranges. I could do the first check to make sure that we don't get more than two, but at that point, why not check for exactly two?
</blockquote></details>

Just to avoid the same error being reported twice, as I stated initially.

---

*[pkg/server/status_test.go, line 480 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-Kd6cxV_6KOx7lRQAvjI:-Kd6h496ohVNYzgOUocB:b-5hynej) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b46aa5001feafd336c18066ea4ee5b7966da2ec/pkg/server/status_test.go#L480)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

because it's a map
</blockquote></details>

Ah, thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587)*

**Comment by bdarnell** [comment]
> I was thinking there might be a different way to encode an array in the URL, but it seems there isn't.

This is the only way to encode an array that can be generated by a standard HTML form, but if you don't care about HTML forms (i.e. because you're constructing the URL in JS or by hand), you can put whatever you want in the URL (e.g. a JSON string). Form-encoding has a lot of flaws and I tend to recommend that people stay away from it when they don't need compatibility with forms, but in this case I think it's a good fit (because hand-editing urls will be relatively common, and it's nearly always a single id) so we should keep it as-is.

**Comment by BramGruneir** [comment]
:lgtm: 

---

Reviewed 1 of 7 files at r2, 1 of 2 files at r5.
Review status: 8 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-:-Kd1Qo4cHknpbgDOeUmq:bg7igkv)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 8 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-:-KdWIC3V-rabxQXBwYxg:bnfp4nl)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 3 of 7 files at r2, 1 of 2 files at r5, 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/server/status.go, line 642 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-KdWsgOBvFjsLwgp_N1I:-KdWsgOBvFjsLwgp_N1J:bfyccht) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9048669e088d281bdf2b2b208d81d28c0064560/pkg/server/status.go#L642)):*
> ```Go
> 			}
> 			desc := rep.Desc()
> 			output.Ranges = append(output.Ranges, serverpb.RangeInfo{
> ```

There should probably be a separate function to convert a `RangeDescriptor` and `*Replica` to a `RangeInfo`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-:-KdWtHAHHacQhSZWwcFl:bnfp4nl)*

**Comment by mberhault** [comment]
Review status: 8 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/server/status.go, line 642 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587#-KdWsgOBvFjsLwgp_N1I:-KdWz3qTs3-pZX2aH3tG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9048669e088d281bdf2b2b208d81d28c0064560/pkg/server/status.go#L642)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

There should probably be a separate function to convert a `RangeDescriptor` and `*Replica` to a `RangeInfo`. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13587)*

**Pull request merged**
