### PR TITLE
keys: highlight a panic in EnsureSafeSplitKey

### PR DESCRIPTION
**Pull request by tbg**
cc @petermattis

### CODE REVIEW

**Comment by petermattis** [comment]
Thanks for finding this.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/keys/keys.go, line 655 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18628#-KuVcXOFz4z0vPXkd8lB:-KuVcXOFz4z0vPXkd8lC:byh3xq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d55d12912e9ee0892e57be93dd05a990b1a1711e/pkg/keys/keys.go#L655)):*
> ```Go
> 	}
> 	from := len(key) - int(colIDLen) - 1
> 	if from > len(key) {
> ```

The real problem is that `colIDLen` is being decoded as `18446744073709551610` and then cast to an `int` which gives a value of `-6`. I think we want to enhance the conditional above:

```
if int(colIDLen) < 0 || int(colIDLen)+1 > n {
  ...
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18628#-:-KuVdsTAJEjK8w4GRxh3:bkgq834)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/keys/keys.go, line 655 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18628#-KuVcXOFz4z0vPXkd8lB:-KuVyH6jdlrLMhIIcz1e:basro9g) ([raw file](https://github.com/cockroachdb/cockroach/blob/d55d12912e9ee0892e57be93dd05a990b1a1711e/pkg/keys/keys.go#L655)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The real problem is that `colIDLen` is being decoded as `18446744073709551610` and then cast to an `int` which gives a value of `-6`. I think we want to enhance the conditional above:

```
if int(colIDLen) < 0 || int(colIDLen)+1 > n {
  ...
}
```
</blockquote></details>

Did you want me to take over this PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18628)*

**Comment by tschottdorf** [comment]
I've done a first pass, but if you think you can do better, feel free to take this over.

**Comment by tschottdorf** [comment]
(but take note that I *just* pushed).

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18628#-:-KuW6Bh8-7dVSul9MrmB:bnfp4nl)*

**Pull request merged**
