### PR TITLE
acceptance: move control plane to Go, remove supervisor

### PR DESCRIPTION
**Pull request by tamird**
Lots of golf here; unfortunately going to require a pretty careful review. I'm also going to attempt to test this manually.

### CODE REVIEW

**Comment by petermattis** [comment]
The terraform/terrafarm stuff is outside of my knowledge, but I'm a fan of getting rid of using supervisor for starting cockroach and the load generator. My experience is that using ssh for this is much more straightforward as well as being more flexible.

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 5 of 5 files at r3, 3 of 3 files at r4, 1 of 1 files at r5.
Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/acceptance/terrafarm/farmer.go, line 348 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-KqYrrpzaqIV69jAlYbE:-KqYrrpzaqIV69jAlYbF:bbxmej7) ([raw file](https://github.com/cockroachdb/cockroach/blob/145c6d71704225fcf472784f510f9f80fba69ead/pkg/acceptance/terrafarm/farmer.go#L348)):*
> ```Go
> func (f *Farmer) Assert(ctx context.Context, t testing.TB) {
> 	for i, node := range f.nodes {
> 		if err := f.Exec(i, "ps "+node.pid); err != nil {
> ```

I wonder if it would be better to `pidof <processname>` and verify the id is what you expect. The `ps <pid>` approach has the very small chance of returning success after the process crashes and the pids wrap around.

---

*[pkg/acceptance/terrafarm/farmer.go, line 457 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-KqYsgRFbaQceT86tea5:-KqYsgRFbaQceT86tea6:b-uo9r13) ([raw file](https://github.com/cockroachdb/cockroach/blob/145c6d71704225fcf472784f510f9f80fba69ead/pkg/acceptance/terrafarm/farmer.go#L457)):*
> ```Go
> 	cmd := "./" + name
> 	switch name {
> 	case "block_writer":
> ```

Should really be using `kv` here. Can you add a TODO?

---

*[pkg/acceptance/terrafarm/farmer.go, line 459 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-KqYscledleH_jyAfF4z:-KqYscledleH_jyAfF5-:b-dhn2jy) ([raw file](https://github.com/cockroachdb/cockroach/blob/145c6d71704225fcf472784f510f9f80fba69ead/pkg/acceptance/terrafarm/farmer.go#L459)):*
> ```Go
> 	case "block_writer":
> 		cmd += fmt.Sprintf("--tolerate-errors --min-block-bytes=8 --max-block-bytes=128 --benchmark-name %s %s", f.BenchmarkName, f.nodes[i].url)
> 	case "photots":
> ```

`s/photots/photos/g`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-:-KqYssKWP6TbdaWNkRbc:b2s336n)*

**Comment by tamird** [comment]
Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/acceptance/terrafarm/farmer.go, line 348 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-KqYrrpzaqIV69jAlYbE:-KqYy0PdDXMJl61Diziy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/145c6d71704225fcf472784f510f9f80fba69ead/pkg/acceptance/terrafarm/farmer.go#L348)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I wonder if it would be better to `pidof <processname>` and verify the id is what you expect. The `ps <pid>` approach has the very small chance of returning success after the process crashes and the pids wrap around.
</blockquote></details>

Done.

---

*[pkg/acceptance/terrafarm/farmer.go, line 457 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-KqYsgRFbaQceT86tea5:-KqYxswnrnUhhTpuFhoC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/145c6d71704225fcf472784f510f9f80fba69ead/pkg/acceptance/terrafarm/farmer.go#L457)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Should really be using `kv` here. Can you add a TODO?
</blockquote></details>

Done.

---

*[pkg/acceptance/terrafarm/farmer.go, line 459 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-KqYscledleH_jyAfF4z:-KqYxvXFfLtX18l45mV0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/145c6d71704225fcf472784f510f9f80fba69ead/pkg/acceptance/terrafarm/farmer.go#L459)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/photots/photos/g`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393)*

**Comment by mjibson** [comment]
Review status: 0 of 14 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/acceptance/terrafarm/farmer.go, line 405 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-KqZ0xH9kpDeiaUXhi-w:-KqZ0xHAFKoGBpvab8kv:b-fcmcci) ([raw file](https://github.com/cockroachdb/cockroach/blob/7741c532c172d0f93bc95b93425be56c7c580e87/pkg/acceptance/terrafarm/farmer.go#L405)):*
> ```Go
> 	)
> 	if i > 0 {
> 		cmd += " --join=" + f.nodes[0].hostname
> ```

The skipClusterInit option was to get around #13027, which is still an open bug. This change appears make it so node 0 gets no join flags and sends node 0's hostname as the only join flag to the other nodes. This will certainly trigger that bug in the 2TB test since (for that specific dataset) all nodes happen to need node 3's hostname in the join flag.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393)*

**Comment by tschottdorf** [comment]
This looks pretty good! Were you able to get a test run with this in? Really glad to see how much you stripped from the terraform configs.

---

Reviewed 14 of 14 files at r7, 5 of 5 files at r8, 3 of 3 files at r9, 1 of 1 files at r10, 13 of 13 files at r11, 1 of 1 files at r12.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[pkg/acceptance/terrafarm/farmer.go, line 58 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-KqZ1cY5Wl5iEtwQjbeW:-KqZ1cY62Y1k_KwdY70f:b-aa6xob) ([raw file](https://github.com/cockroachdb/cockroach/blob/c76439ce72cde702880d57ce0fa15dd91f07c5b7/pkg/acceptance/terrafarm/farmer.go#L58)):*
> ```Go
> type node struct {
> 	hostname  string
> 	pid       string
> ```

pid of what? Running cockroach binary? Don't we have loadgen-only nodes, and do those have a `node` struct too? Perhaps a rename would be helpful (->cockroachNode).

---

*[pkg/acceptance/terrafarm/farmer.go, line 71 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-KqZ1sd8If8CGhv0P7hD:-KqZ1sd8If8CGhv0P7hE:b1ps4j7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c76439ce72cde702880d57ce0fa15dd91f07c5b7/pkg/acceptance/terrafarm/farmer.go#L71)):*
> ```Go
> 	CockroachBinary string
> 	CockroachFlags  string
> 	CockroachEnv    string
> ```

Would make more sense as a map, but seems OK to just slap a TODO and leave for now.

---

*[pkg/acceptance/terrafarm/farmer.go, line 389 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-KqZ2mBQjzC1Ozfk3WHN:-KqZ2mBQjzC1Ozfk3WHO:b-1buuw7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c76439ce72cde702880d57ce0fa15dd91f07c5b7/pkg/acceptance/terrafarm/farmer.go#L389)):*
> ```Go
> 	)
> 	cmd := fmt.Sprintf(
> 		"%s ./cockroach start %s --insecure --background --listening-url-file %s --pid-file %s --cache=2GiB --log-dir logs/cockroach",
> ```

`ulimit -c unlimited && %s ./cockroach start`?

---

*[pkg/acceptance/terrafarm/farmer.go, line 416 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-KqZ71rteG_3T0Pu-4ue:-KqZ71rteG_3T0Pu-4uf:b-dekwkx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c76439ce72cde702880d57ce0fa15dd91f07c5b7/pkg/acceptance/terrafarm/farmer.go#L416)):*
> ```Go
> 
> 	if err := util.RetryForDuration(10*time.Second, func() error {
> 		stdout, stderr, err := f.ssh(f.Hostname(i), f.defaultKeyFile(), "cat "+listeningURLFileName)
> ```

Delete this file before starting the process so you can "guarantee" that it's not left-over from the last process.

---

*[pkg/acceptance/terrafarm/farmer.go, line 426 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-KqZ7H3uIElxV6iKvkll:-KqZ7H3vGaXrGiDS8IxJ:b-89a4l7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c76439ce72cde702880d57ce0fa15dd91f07c5b7/pkg/acceptance/terrafarm/farmer.go#L426)):*
> ```Go
> 	}
> 
> 	stdout, stderr, err := f.ssh(f.Hostname(i), f.defaultKeyFile(), "cat "+pidFileName)
> ```

Ditto

---

*[pkg/acceptance/terrafarm/farmer.go, line 450 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-KqZ7V4QNJZuSWZW2QLg:-KqZ7V4QNJZuSWZW2QLh:bcq4rod) ([raw file](https://github.com/cockroachdb/cockroach/blob/c76439ce72cde702880d57ce0fa15dd91f07c5b7/pkg/acceptance/terrafarm/farmer.go#L450)):*
> ```Go
> 	}
> 	done := make(chan error, 1)
> 	f.nodes[i].processes = append(f.nodes[i].processes, process{
> ```

`processes` wouldn't naturally be a map?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-:-KqZ8jEML03XwpY7GXBn:b-vzu9hc)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/acceptance/terrafarm/farmer.go, line 349 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-KqZCuUl1p_FgEV3Ko-b:-KqZCuUl1p_FgEV3Ko-c:b-18ktpd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7741c532c172d0f93bc95b93425be56c7c580e87/pkg/acceptance/terrafarm/farmer.go#L349)):*
> ```Go
> 	const cmd = "pidof cockroach"
> 
> 	for i, node := range f.nodes {
> ```

Not for this PR, but w/ Go it is fairly straightforward to parallelize this. See the code in `roachperf.cluster.parallel()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393)*

**Comment by cuongdo** [comment]
This looks great! I love the simplifications. I'm testing this now with a sampling of the nightlies.

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 5 of 5 files at r3, 14 of 14 files at r7, 5 of 5 files at r8, 3 of 3 files at r9, 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/acceptance/terrafarm/farmer.go, line 58 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-KqZ1cY5Wl5iEtwQjbeW:-KqZq9wsvtkx__GG6nlH:b-ua2e9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/c76439ce72cde702880d57ce0fa15dd91f07c5b7/pkg/acceptance/terrafarm/farmer.go#L58)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

pid of what? Running cockroach binary? Don't we have loadgen-only nodes, and do those have a `node` struct too? Perhaps a rename would be helpful (->cockroachNode).
</blockquote></details>

+1 on the rename

There are no loadgen-only nodes. We're running the load generators on the Cockroach nodes, similar to the prod clusters.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-:-KqZspWzpThmBcxf_Xkq:b-jcmic1)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/acceptance/terrafarm/farmer.go, line 58 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-KqZ1cY5Wl5iEtwQjbeW:-KqZxbh76QNkVSZ6my1R:b-i1pi5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/c76439ce72cde702880d57ce0fa15dd91f07c5b7/pkg/acceptance/terrafarm/farmer.go#L58)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

+1 on the rename

There are no loadgen-only nodes. We're running the load generators on the Cockroach nodes, similar to the prod clusters.
</blockquote></details>

Ack. Maybe I'm misremembering, but don't we also want to run nightly cluster benchmarks? Putting the loadgens on the running nodes doesn't seem appropriate for that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393)*

**Comment by cuongdo** [comment]
While running my manual tests with your branch, I ran into this issue:

```
error collecting cluster logs: could not create destination directory "/Users/cdocr/go/src/github.com/cockroachdb/cockroach/pkg/acceptance/artifacts/node.0": mkdir /Users/cdocr/go/src/github.com/cockroachdb/cockroach/pkg/acceptance/artifacts/node.0: no such file or directory
```

It seems like there's an `os.MkdirAll` missing somewhere.

Also, I ran into this failure during the schema change test:

```
--- FAIL: TestRebalance_3To5Small_WithSchemaChanges (666.32s)
	allocator_test.go:162: error restarting node 0: failed: kill -9 12824: Process exited with status 1
		stdout:

		stderr:
		bash: line 0: kill: (12824) - No such process
	farmer.go:268: cannot destroy cluster: close tcp 192.168.1.21:53049->52.170.85.200:22: use of closed network connection
```

---

Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[pkg/acceptance/terrafarm/farmer.go, line 427 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-KqZw1SDKXBAd1IhBDwC:-KqZw1SDKXBAd1IhBDwD:b-r6m066) ([raw file](https://github.com/cockroachdb/cockroach/blob/7741c532c172d0f93bc95b93425be56c7c580e87/pkg/acceptance/terrafarm/farmer.go#L427)):*
> ```Go
> 		stdout, stderr, err := f.ssh(f.Hostname(i), f.defaultKeyFile(), "cat "+listeningURLFileName)
> 		if err != nil {
> 			return fmt.Errorf("failed: %s: %s\nstdout:\n%s\nstderr:\n%s", cmd, err, stdout, stderr)
> ```

This causes some log spam while `cockroach` is coming up. For example:

```
cat: cockroachdb-url: No such file or directory
+ cat cockroachdb-url
cat: cockroachdb-url: No such file or directory
+ cat cockroachdb-url
cat: cockroachdb-url: No such file or directory
+ cat cockroachdb-url
(repeated many more times)
```

Is there a way to suppress this output for the failures that happen during the retry interval?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-:-KqZxSGSUkjwNRyEJQ4s:b5jiv9)*

**Comment by tamird** [comment]
The missing MkdirAll is intentional - note that our scripts which call the acceptance tests take care to create the logging directories they intend to use.

I've added a commit that rearranges Resize to avoid the connection closure error. I'll run that same test when I get a chance, too.

TFYRs, PTAL!

---

Review status: 0 of 14 files reviewed at latest revision, 9 unresolved discussions, some commit checks pending.

---

*[pkg/acceptance/terrafarm/farmer.go, line 58 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-KqZ1cY5Wl5iEtwQjbeW:-Kq_Jr3v-AMNKHxIINPK:b-vwgezt) ([raw file](https://github.com/cockroachdb/cockroach/blob/c76439ce72cde702880d57ce0fa15dd91f07c5b7/pkg/acceptance/terrafarm/farmer.go#L58)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Ack. Maybe I'm misremembering, but don't we also want to run nightly cluster benchmarks? Putting the loadgens on the running nodes doesn't seem appropriate for that.
</blockquote></details>

Yeah, we do - that will change in upcoming work, though. For now, I've prepended both this and `url` with "cockroach".

---

*[pkg/acceptance/terrafarm/farmer.go, line 71 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-KqZ1sd8If8CGhv0P7hD:-Kq_FEWRVKQ4z8V5vlov:b7qoawr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c76439ce72cde702880d57ce0fa15dd91f07c5b7/pkg/acceptance/terrafarm/farmer.go#L71)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Would make more sense as a map, but seems OK to just slap a TODO and leave for now.
</blockquote></details>

Added a comment explaining this choice.

---

*[pkg/acceptance/terrafarm/farmer.go, line 389 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-KqZ2mBQjzC1Ozfk3WHN:-Kq_G9Xc_QL0CV8wZy__:b-lpos0q) ([raw file](https://github.com/cockroachdb/cockroach/blob/c76439ce72cde702880d57ce0fa15dd91f07c5b7/pkg/acceptance/terrafarm/farmer.go#L389)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

`ulimit -c unlimited && %s ./cockroach start`?
</blockquote></details>

Was this previously provided?

---

*[pkg/acceptance/terrafarm/farmer.go, line 416 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-KqZ71rteG_3T0Pu-4ue:-Kq_JI5l8HHyDRmdU5sE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c76439ce72cde702880d57ce0fa15dd91f07c5b7/pkg/acceptance/terrafarm/farmer.go#L416)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Delete this file before starting the process so you can "guarantee" that it's not left-over from the last process.
</blockquote></details>

Done.

---

*[pkg/acceptance/terrafarm/farmer.go, line 426 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-KqZ7H3uIElxV6iKvkll:-Kq_JIQnCIt1I3MXcbms:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c76439ce72cde702880d57ce0fa15dd91f07c5b7/pkg/acceptance/terrafarm/farmer.go#L426)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.

---

*[pkg/acceptance/terrafarm/farmer.go, line 450 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-KqZ7V4QNJZuSWZW2QLg:-Kq_JoRrbtN1ROCpfFm3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c76439ce72cde702880d57ce0fa15dd91f07c5b7/pkg/acceptance/terrafarm/farmer.go#L450)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

`processes` wouldn't naturally be a map?
</blockquote></details>

Done.

---

*[pkg/acceptance/terrafarm/farmer.go, line 349 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-KqZCuUl1p_FgEV3Ko-b:-Kq_G0ThjIKzZmwNoEzj:b-69zi30) ([raw file](https://github.com/cockroachdb/cockroach/blob/7741c532c172d0f93bc95b93425be56c7c580e87/pkg/acceptance/terrafarm/farmer.go#L349)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Not for this PR, but w/ Go it is fairly straightforward to parallelize this. See the code in `roachperf.cluster.parallel()`.
</blockquote></details>

That's a lot of code! Do you think that's worth it here?

---

*[pkg/acceptance/terrafarm/farmer.go, line 405 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-KqZ0xH9kpDeiaUXhi-w:-Kq_GsyKwLWLsAXIBrh4:b-lawjcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/7741c532c172d0f93bc95b93425be56c7c580e87/pkg/acceptance/terrafarm/farmer.go#L405)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

The skipClusterInit option was to get around #13027, which is still an open bug. This change appears make it so node 0 gets no join flags and sends node 0's hostname as the only join flag to the other nodes. This will certainly trigger that bug in the 2TB test since (for that specific dataset) all nodes happen to need node 3's hostname in the join flag.
</blockquote></details>

Thanks for the pointer! Restored.

---

*[pkg/acceptance/terrafarm/farmer.go, line 427 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-KqZw1SDKXBAd1IhBDwC:-Kq_Ioikdw7Hfvl7UmKv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7741c532c172d0f93bc95b93425be56c7c580e87/pkg/acceptance/terrafarm/farmer.go#L427)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

This causes some log spam while `cockroach` is coming up. For example:

```
cat: cockroachdb-url: No such file or directory
+ cat cockroachdb-url
cat: cockroachdb-url: No such file or directory
+ cat cockroachdb-url
cat: cockroachdb-url: No such file or directory
+ cat cockroachdb-url
(repeated many more times)
```

Is there a way to suppress this output for the failures that happen during the retry interval?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-:-Kq_L9GphqX-Hf8yx25p:b-8rup6d)*

**Comment by cuongdo** [comment]
I've pulled down your latest changes, but I'm still having a hard time getting a basic test to run.

This is the error:

```
+ kill -9 12831 && rm -f cockroachdb-url cockroachdb-pid
bash: line 0: kill: (12831) - No such process
```

This is my command-line:

```
   make test \
        PKG=./pkg/acceptance \
        TESTTIMEOUT=6h \
        TESTS='Rebalance_3To5Small\z' \
        TESTFLAGS='-v -remote -key-name google_compute_engine -cwd terraform/azure -at.std-dev=14 -tf.cockroach-env=COCKROACH_PREEMPTIVE_SNAPSHOT_RATE=8388608 -show-logs'
```

---

Review status: 0 of 14 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-:-KqcSMizNFvocfLAhNex:bvxioer)*

**Comment by tamird** [comment]
OK so the remaining issue is restarting cockroach nodes where a node has already been running won't consider itself ready until after it has achieved quorum. IOW, we need to be able to start nodes in parallel. @tschottdorf I think I'll have to change the cluster interface to do this; any opinions?

**Comment by tschottdorf** [comment]
Sounds good to me, though I wonder how that's gonna work with the docker stuff. Probably still just do it serially there for now even though the interface allows more. Keep in mind that we may want to rip Docker out of the acceptance tests.

---

Review status: 0 of 14 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-:-Kqd0tJgbM95D7V-yluf:bnfqnir)*

**Comment by mjibson** [comment]
skipClusterInit stuff LGTM

---

Review status: 0 of 14 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-:-Kqd9iqbNtxIca7_gHXE:b-vrkmrq)*

**Comment by tamird** [comment]
OK, I made those restarts concurrent. @cuongdo would you try another run, please?

**Comment by tschottdorf** [comment]
Reviewed 14 of 14 files at r13, 5 of 5 files at r14, 3 of 3 files at r15, 1 of 1 files at r16, 7 of 7 files at r17, 15 of 15 files at r18.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/acceptance/terrafarm/farmer.go, line 389 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-KqZ2mBQjzC1Ozfk3WHN:-KqdwiWjNRU78UJGgfsC:b-24ajs1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c76439ce72cde702880d57ce0fa15dd91f07c5b7/pkg/acceptance/terrafarm/farmer.go#L389)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Was this previously provided?
</blockquote></details>

No, but would be good to do it in the future. If it gives you any trouble, we can postpone (TODO in that case, or issue).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393)*

**Comment by tschottdorf** [comment]
:lgtm:, but your first commit's message is stale (skipInitCluster).

---

Reviewed 16 of 16 files at r19, 5 of 5 files at r20, 3 of 3 files at r21, 1 of 1 files at r22, 7 of 7 files at r23, 1 of 1 files at r24, 15 of 15 files at r25.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17393#-:-Kqi5JRIwPJQh4WMptjZ:bd1nwaw)*

**Comment by tamird** [comment]
Updated the commit message, thanks!

On Fri, Aug 4, 2017 at 12:35 PM, Tobias Schottdorf <notifications@github.com

**Comment by tamird** [comment]
Alrighty, here goes.

**Pull request merged**
