### PR TITLE
cli,server: allow user to specify port range for secondary VCs

### LINKED ISSUE #111848: server: the internal RPC port for secondary tenant servers is unpredictable
This is auto-allocated with a semi-random port number. It makes it hard to configure firewalls, etc.

Epic: CRDB-26691

Jira issue: CRDB-32094

### PR DESCRIPTION
**Pull request by stevendanna**
Previously, the user could set a port range offset that would instruct
the tenant controller to choose a gRPC port starting at the KV
server's RPC port + the offset + an index.

While this provides the user some predictability, there is no upper
bound on the port that could be picked.

Here, we add a new option

   --secondary-tenant-port-range

That allows the user to specify an explicit range.

Fixes #111848.
Epic: CRDB-26691

Release note: None

### CODE REVIEW

**Comment by stevendanna** [comment]
I need to add some tests, but let me know if this has a shape that lines up with what you were expecting given our conversation.

**Review by knz — COMMENTED** [review]
Very good work. Overall approach LGTM. 

> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111798#-:-Ng0ZxtL3qO4KYGDJFq6:b-e83tx2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @stevendanna)

___
*[`pkg/base/config.go` line 429 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111798#-Ng0ZItD-8obSKR9LUYy:-Ng0ZItE1H2FdU-g_TqC:b-ik6h3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/4920043e85b6efb71f4becb739aac58d583cf88f/pkg/base/config.go#L429)):*
> ```Go
> 	// ports used by secondary tenants.
> 	SecondaryTenantPortMin int
> 	SecondaryTenantPortMax int
> ```

don't forget to set to default values in `InitDefaults` below.
___
*[`pkg/cli/flags.go` line 548 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111798#-Ng0Z1CK8VMecpAMCkd1:-Ng0Z1CK8VMecpAMCkd2:b6y8hxe) ([raw file](https://github.com/cockroachdb/cockroach/blob/4920043e85b6efb71f4becb739aac58d583cf88f/pkg/cli/flags.go#L548)):*
> ```Go
> 		_ = f.MarkHidden(cliflags.SecondaryTenantPortOffset.Name)
> 
> 		cliflagcfg.IntFlag(f, &baseCfg.SecondaryTenantPortMin, cliflags.SecondaryTenantPortMin)
> ```

Before this merges, let's make it a single flag with a setter that parses a range (N-M). See what is done for ListenSQLAddr for an example.
___
*[`pkg/server/listen_and_update_addrs.go` line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111798#-Ng0ZiqV3duyq4EjCbks:-Ng0ZiqV3duyq4EjCbkt:bb6mt9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/4920043e85b6efb71f4becb739aac58d583cf88f/pkg/server/listen_and_update_addrs.go#L42)):*
> ```Go
> func ListenerFactoryForConfig(cfg *BaseConfig, portStartHint int) (RPCListenerFactory, error) {
> 	// TODO:(ssd): We use != here becauses demo uses a negative
> 	// port offset. But, demo could now just pass a min/max.
> ```

:+1:
___
*[`pkg/server/listen_and_update_addrs.go` line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111798#-Ng0ZoqQC4vgisvKwLw2:-Ng0ZoqQC4vgisvKwLw3:b-30ekeo) ([raw file](https://github.com/cockroachdb/cockroach/blob/4920043e85b6efb71f4becb739aac58d583cf88f/pkg/server/listen_and_update_addrs.go#L124)):*
> ```Go
> 			return nil, err
> 		}
> 		// TODO(ssd): check for EADDRINUSE and return any other error.
> ```

Let's do that before this merges.

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111798)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @knz)

___
*[`pkg/base/config.go` line 429 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111798#-Ng0ZItD-8obSKR9LUYy:-Ng8Sp0p4TzzCyVFelzA:bd5yf42) ([raw file](https://github.com/cockroachdb/cockroach/blob/4920043e85b6efb71f4becb739aac58d583cf88f/pkg/base/config.go#L429)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

don't forget to set to default values in `InitDefaults` below.
</blockquote></details>

Thanks. Done
___
*[`pkg/cli/flags.go` line 548 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111798#-Ng0Z1CK8VMecpAMCkd1:-Ng8SuDu6_vsv0CRpEe8:b-kgkkmi) ([raw file](https://github.com/cockroachdb/cockroach/blob/4920043e85b6efb71f4becb739aac58d583cf88f/pkg/cli/flags.go#L548)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Before this merges, let's make it a single flag with a setter that parses a range (N-M). See what is done for ListenSQLAddr for an example.
</blockquote></details>

Nice suggestion, done.
___
*[`pkg/server/listen_and_update_addrs.go` line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111798#-Ng0ZoqQC4vgisvKwLw2:-Ng8SxiH2TtfWHsdijQV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4920043e85b6efb71f4becb739aac58d583cf88f/pkg/server/listen_and_update_addrs.go#L124)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Let's do that before this merges.
</blockquote></details>

Done.

**Review by knz — COMMENTED** [review]
> Reviewed 17 of 18 files at r4, 15 of 16 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111798)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @stevendanna)

___
*[`-- commits` line 18 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/111798#-NgImSoXDVBGvrkHlhiV):*
This needs an explanatory release note, including what problem this solves, when to use.
___
*[`pkg/base/addr_validation.go` line 86 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/111798#-NgImZub3vBi5gWvfTCq:-NgImZub3vBi5gWvfTCr:bcsupu7) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ecd54cd5885877d67a3bc23ceeb3186b2c3e79f/pkg/base/addr_validation.go#L86)):*
> ```Go
> 	cfg.HTTPAddr = net.JoinHostPort(httpHost, httpPort)
> 
> 	// Validate secondary tenant port configuration
> ```

nit: period at end of sentence.
___
*[`pkg/base/addr_validation.go` line 87 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/111798#-NgImcFU8GvHMw6B2Awz:-NgImcFU8GvHMw6B2Ax-:b15kbq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ecd54cd5885877d67a3bc23ceeb3186b2c3e79f/pkg/base/addr_validation.go#L87)):*
> ```Go
> 
> 	// Validate secondary tenant port configuration
> 	if cfg.SecondaryTenantPortOffset > 0 && cfg.SecondaryTenantPortMin > 0 {
> ```

why did you choose to keep SecondaryTenantPortOffset? I don't think it's prudent to keep 2 different mechanisms to achieve the same.
___
*[`pkg/base/config.go` line 427 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/111798#-NgImncOAK88XZ6GgsfR:-NgImncP7dBuM0yTL-OE:b-l878qu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ecd54cd5885877d67a3bc23ceeb3186b2c3e79f/pkg/base/config.go#L427)):*
> ```Go
> 	// SecondaryTenantPortMin and SecondaryTenantPortMax allow the
> 	// user to specify the upper and lower bound of the range of
> 	// ports used by secondary tenants.
> ```

This explanation is both too specific and not specific enough.

Anything network-related needs to explain _what service_ the TCP ports are for.

(Let's not use the existing "SecondaryTenantPortOffset" as guide — this is 1) poorly named 2) needs to be removed altogether)

What service:
- not SQL, not HTTP -- it's specifically the RPC service
- which RPC service specifically? The one mainly used for server-to-server connections (i.e. internal traffic)—for the time being, also still used for `debug zip`, but that's also 'internal' enough.

What do you think of this:
```go
// ApplicationInternalRPCPortMin/PortMax define the range of TCP ports used to start
// the internal RPC service for application-level servers. This service is used for
// node-to-node RPC traffic and to serve data for 'debug zip'.
ApplicationInternalRPCPortMin int
ApplicationInternalRPCPortMax int
```
___
*[`pkg/server/listen_and_update_addrs.go` line 102 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/111798#-NgIqcuHB3s1wiUFFOI3:-NgIqcuHB3s1wiUFFOI4:br91oa9) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ecd54cd5885877d67a3bc23ceeb3186b2c3e79f/pkg/server/listen_and_update_addrs.go#L102)):*
> ```Go
> 		return nil, err
> 	}
> 	if rlf.upperBound > 0 && rlf.lowerBound > rlf.upperBound {
> ```

`if rlf.upperBound - rlf.lowerBound < 1 { assert }`
___
*[`pkg/server/listen_and_update_addrs.go` line 106 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/111798#-NgIpc2Y-Go9Yv-bTy7X:-NgIpc2Y-Go9Yv-bTy7Y:b-4o3i2o) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ecd54cd5885877d67a3bc23ceeb3186b2c3e79f/pkg/server/listen_and_update_addrs.go#L106)):*
> ```Go
> 	}
> 
> 	nextPort := rlf.lowerBound + rlf.startHint
> ```

I was expecting `numCandidates := (rlf.upperBound - rlf.lowerBound);   nextPort := rlf.lowerBound + (rls.startHint % numCandidates)`
why is the conditional more complicated than that?
___
*[`pkg/server/listen_and_update_addrs.go` line 112 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/111798#-NgIpmz_E3BIbA5ahKLd:-NgIoKWu7PwDxBw4Se6h:bu92r0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ecd54cd5885877d67a3bc23ceeb3186b2c3e79f/pkg/server/listen_and_update_addrs.go#L112)):*
> ```Go
> 
> 	var ln net.Listener
> 	for rlf.upperBound == 0 || nextPort <= rlf.upperBound {
> ```

maybe?
```go
for numAttempts := 0; numAttempts < numCandidates; numAttempts++ {
    ...
    nextPort = ((nextPort - rlf.lowerBound + 1) % numCandidates) + rlf.lowerBound
}
```
___
*[`pkg/util/netutil/addr/addr.go` line 114 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/111798#-NgIp7pl8oiC3GbHo2o9:-NgIp7pl8oiC3GbHo2oA:b-jzkzql) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ecd54cd5885877d67a3bc23ceeb3186b2c3e79f/pkg/util/netutil/addr/addr.go#L114)):*
> ```Go
> func (a portRangeSetter) String() string {
> 	if *a.upper == 0 {
> 		return fmt.Sprintf("%d-", *a.lower)
> ```

This open upper limit will be hard to explain and reason about. It also creates uncomfortable special cases in the implementation.
Since I don't remember we have a clear motivation for it, I recommend we remove it (and simplify the code) until we have proof it's required. 
___
*[`pkg/util/netutil/addr/addr.go` line 146 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/111798#-NgIqQGv9OeWGhgZoj2D:-NgIqQGv9OeWGhgZoj2E:b-an9kr1) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ecd54cd5885877d67a3bc23ceeb3186b2c3e79f/pkg/util/netutil/addr/addr.go#L146)):*
> ```Go
> 		return errors.Wrap(err, "invalid port range")
> 	}
> 	if lower > upper {
> ```

let's assert the interval contains at least 1 port i.e. `(upper - lower) > 1`.

**Review by stevendanna — COMMENTED** [review]
Thanks for the review.  

I've pushed some changes, still need to do the rename and then decide if I really want to pull out the PortOffset option completely.  I think we do since if we let it live another release, it will just be even more annoying to remove.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111798#-:-NgJNUus-VoWCAu9ihCN:bqzcfub)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @dt, @knz, and @renatolabs)

___
*[`pkg/base/config.go` line 427 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/111798#-NgImncOAK88XZ6GgsfR:-NgJL1q69uZ1IVEXdfGM:bwwjg8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aa8db0b015388305ce0dad2bb22e990b9e29b06/pkg/base/config.go#L427)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

This explanation is both too specific and not specific enough.

Anything network-related needs to explain _what service_ the TCP ports are for.

(Let's not use the existing "SecondaryTenantPortOffset" as guide — this is 1) poorly named 2) needs to be removed altogether)

What service:
- not SQL, not HTTP -- it's specifically the RPC service
- which RPC service specifically? The one mainly used for server-to-server connections (i.e. internal traffic)—for the time being, also still used for `debug zip`, but that's also 'internal' enough.

What do you think of this:
```go
// ApplicationInternalRPCPortMin/PortMax define the range of TCP ports used to start
// the internal RPC service for application-level servers. This service is used for
// node-to-node RPC traffic and to serve data for 'debug zip'.
ApplicationInternalRPCPortMin int
ApplicationInternalRPCPortMax int
```
</blockquote></details>

My only misgiving about this name is that it is mildly still a misnomer depending on wether you consider the system tenant the Application layer in the single-tenant use case. But, I can live with that for now.

Before I do this rename, how do you feel about the _command line option name_?
___
*[`pkg/server/listen_and_update_addrs.go` line 102 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/111798#-NgIqcuHB3s1wiUFFOI3:-NgJMvpl7A-qzxVsv6sG:b-nkpn98) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aa8db0b015388305ce0dad2bb22e990b9e29b06/pkg/server/listen_and_update_addrs.go#L102)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

`if rlf.upperBound - rlf.lowerBound < 1 { assert }`
</blockquote></details>

Since it is an inclusive range lowerBound = upperBound is valid and is one port.
___
*[`pkg/server/listen_and_update_addrs.go` line 106 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/111798#-NgIpc2Y-Go9Yv-bTy7X:-NgJN1aD8EMeQ0gpHVM-:bh79h1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aa8db0b015388305ce0dad2bb22e990b9e29b06/pkg/server/listen_and_update_addrs.go#L106)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I was expecting `numCandidates := (rlf.upperBound - rlf.lowerBound);   nextPort := rlf.lowerBound + (rls.startHint % numCandidates)`
why is the conditional more complicated than that?
</blockquote></details>

There was actually a bug hidden here so I'm glad we took a second look.
___
*[`pkg/server/listen_and_update_addrs.go` line 112 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/111798#-NgIpmz_E3BIbA5ahKLd:-NgJNHqMEBBu3Vj3DSV1:b-t8yfy6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aa8db0b015388305ce0dad2bb22e990b9e29b06/pkg/server/listen_and_update_addrs.go#L112)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

maybe?
```go
for numAttempts := 0; numAttempts < numCandidates; numAttempts++ {
    ...
    nextPort = ((nextPort - rlf.lowerBound + 1) % numCandidates) + rlf.lowerBound
}
```
</blockquote></details>

Used slightly different arithmetic but I think the spirit is the same.
___
*[`pkg/util/netutil/addr/addr.go` line 114 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/111798#-NgIp7pl8oiC3GbHo2o9:-NgJNNIv2ioT5OTOkb8j:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aa8db0b015388305ce0dad2bb22e990b9e29b06/pkg/util/netutil/addr/addr.go#L114)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

This open upper limit will be hard to explain and reason about. It also creates uncomfortable special cases in the implementation.
Since I don't remember we have a clear motivation for it, I recommend we remove it (and simplify the code) until we have proof it's required.
</blockquote></details>

Done.
___
*[`pkg/util/netutil/addr/addr.go` line 146 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/111798#-NgIqQGv9OeWGhgZoj2D:-NgJNOAM9KzzmaZa3qHb:bozpxfj) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aa8db0b015388305ce0dad2bb22e990b9e29b06/pkg/util/netutil/addr/addr.go#L146)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

let's assert the interval contains at least 1 port i.e. `(upper - lower) > 1`.
</blockquote></details>

Since the range is inclusive, there is always at least one port as long as the range isn't inverted.

**Review by knz — COMMENTED** [review]
> Reviewed 3 of 3 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111798)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @dt, @renatolabs, and @stevendanna)

___
*[`pkg/base/config.go` line 427 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/111798#-NgImncOAK88XZ6GgsfR:-NgJheJm8tL7OsOEipzp:bpd2a62) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aa8db0b015388305ce0dad2bb22e990b9e29b06/pkg/base/config.go#L427)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

My only misgiving about this name is that it is mildly still a misnomer depending on wether you consider the system tenant the Application layer in the single-tenant use case. But, I can live with that for now.

Before I do this rename, how do you feel about the _command line option name_?
</blockquote></details>

in the no-virtualization use case, this flag is not used. So there's no confusion about whether/how it applies to the system tenant.

And yes it goes without saying that the flag should be renamed as well. How do you feel about `--internal-rpc-port-range`? 
___
*[`pkg/server/listen_and_update_addrs.go` line 117 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111798#-NgJhDRE5CmPhWVi4v-E:-NgJhDRF8WlHZv60YfuZ:b-l11amt) ([raw file](https://github.com/cockroachdb/cockroach/blob/76732f59733a4d6051939b8d8f7db0ff874ab2e7/pkg/server/listen_and_update_addrs.go#L117)):*
> ```Go
> 	var ln net.Listener
> 	for numAttempts := 0; numAttempts < numCandidates; numCandidates++ {
> 		nextPort = nextPort + (numAttempts % numCandidates)
> ```

this does not properly wrap around. 

If, say, your range is 100-199. 
numCandidates == 100.

and assume `startHint` is 99 already.

Then rlf.lowerBound + startHint%numCandidates == 199.
At numAttempts == 0, you'll assign `nextPort = 199` so everything is still fine. But what if that port is occupied?
then at numAttempts == 1, you'll assign `nextPort = 200` which is outside of the range.

That's because you're forgetting to normalize `nextPort` to the range 0...numCandidates before doing the +1 and modulo.

I think you need `nextPort = ((nextPort - rlf.lowerBound + 1) % numCandidates) + rlf.lowerBound`.

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111798)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @dt, @knz, and @renatolabs)

___
*[`-- commits` line 18 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/111798#-NgImSoXDVBGvrkHlhiV):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

This needs an explanatory release note, including what problem this solves, when to use.
</blockquote></details>

Done.
___
*[`pkg/base/addr_validation.go` line 87 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/111798#-NgImcFU8GvHMw6B2Awz:-NgK7p5v8X5kSDT-s6h_:b-ptoh0j) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aa8db0b015388305ce0dad2bb22e990b9e29b06/pkg/base/addr_validation.go#L87)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

why did you choose to keep SecondaryTenantPortOffset? I don't think it's prudent to keep 2 different mechanisms to achieve the same.
</blockquote></details>

I agree we should remove it but I would like to do that in a follow up PR (today)
___
*[`pkg/base/config.go` line 427 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/111798#-NgImncOAK88XZ6GgsfR:-NgJl_w2BGpGfMemsoPS:b-acplz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aa8db0b015388305ce0dad2bb22e990b9e29b06/pkg/base/config.go#L427)):*
>in the no-virtualization use case, this flag is not used. So there's no confusion about whether/how it applies to the system tenant.

Well, yes, if you know what the flag is used for then there is no confusion about what the flag is used for.

But, your name is certainly an improvement over my name and I haven't thought of a better one so I've taken these recommendations wholesale.
___
*[`pkg/server/listen_and_update_addrs.go` line 117 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111798#-NgJhDRE5CmPhWVi4v-E:-NgK7n6Y68KYYdhU5jmM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/76732f59733a4d6051939b8d8f7db0ff874ab2e7/pkg/server/listen_and_update_addrs.go#L117)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

this does not properly wrap around. 

If, say, your range is 100-199. 
numCandidates == 100.

and assume `startHint` is 99 already.

Then rlf.lowerBound + startHint%numCandidates == 199.
At numAttempts == 0, you'll assign `nextPort = 199` so everything is still fine. But what if that port is occupied?
then at numAttempts == 1, you'll assign `nextPort = 200` which is outside of the range.

That's because you're forgetting to normalize `nextPort` to the range 0...numCandidates before doing the +1 and modulo.

I think you need `nextPort = ((nextPort - rlf.lowerBound + 1) % numCandidates) + rlf.lowerBound`.
</blockquote></details>

Done.

**Comment by knz** [comment]
can you push your latest update

**Review by knz — APPROVED** [review]
LGTM although I believe the previous CI run was telling you something about the new flag test.

> Reviewed 18 of 18 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111798#-:-NgK8kHuCbRqVT-gXZpB:b-gznsym)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @dt, @renatolabs, and @stevendanna)

___
*[`-- commits` line 26 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/111798#-NgK8WHp5PFsuSYCNc5u):*
The release note category is missing. -- `Release note (cluster virtualization): ...`

**Comment by stevendanna** [comment]
@knz TFTR!

The test is passing locally, so hopefully says the same on this run. I made some changes to the error conditions that caused the test to fail but I think they are fixed now.

```
> ./dev test ./pkg/util/netutil/addr/ --verbose
$ bazel test pkg/util/netutil/addr:all --test_env=GOTRACEBACK=all --test_arg -test.v --test_output all
INFO: Invocation ID: 813bb286-17cb-45e8-907c-ddbf463b58f2
INFO: Analyzed 2 targets (0 packages loaded, 0 targets configured).
INFO: Found 1 target and 1 test target...
INFO: Elapsed time: 0.653s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
PASSED: //pkg/util/netutil/addr:addr_test (see /private/var/tmp/_bazel_ssd/a51ea94df2f483aee3088dde6a3dde4e/execroot/com_github_cockroachdb_cockroach/bazel-out/darwin_arm64-fastbuild/testlogs/pkg/util/netutil/addr/addr_test/test.log)
INFO: From Testing //pkg/util/netutil/addr:addr_test
==================== Test output for //pkg/util/netutil/addr:addr_test:
=== RUN   TestPortRangeSetter
=== RUN   TestPortRangeSetter/5-10
=== RUN   TestPortRangeSetter/5-
=== RUN   TestPortRangeSetter/5
=== RUN   TestPortRangeSetter/5-8-10
=== RUN   TestPortRangeSetter/a-5
=== RUN   TestPortRangeSetter/5-b
=== RUN   TestPortRangeSetter/10-5
--- PASS: TestPortRangeSetter (0.00s)
    --- PASS: TestPortRangeSetter/5-10 (0.00s)
    --- PASS: TestPortRangeSetter/5- (0.00s)
    --- PASS: TestPortRangeSetter/5 (0.00s)
    --- PASS: TestPortRangeSetter/5-8-10 (0.00s)
    --- PASS: TestPortRangeSetter/a-5 (0.00s)
    --- PASS: TestPortRangeSetter/5-b (0.00s)
    --- PASS: TestPortRangeSetter/10-5 (0.00s)
```

> The release note category is missing. -- Release note (cluster virtualization): ...

Thanks. Very odd...I thought I had a post-commit hook for this.

**Comment by stevendanna** [comment]
bors r=knz

**Pull request merged**
