### PR TITLE
sql,distsql: Streaming GROUP BY

### PR DESCRIPTION
**Pull request by abhimadan**
See individual commits for details.

### CODE REVIEW

**Comment by jordanlewis** [comment]
@knz could you review commit 3, the changes to local group by?
@RaduBerinde could you review commit 4, the changes to planning?

---

Reviewed 1 of 1 files at r1, 8 of 8 files at r2, 1 of 1 files at r3.
Review status: 8 of 18 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/sql/distsqlrun/aggregator.go, line 285 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113#-L9RTmyXEfobFHGeOweU:-L9RTmyXEfobFHGeOweV:b-bzs7uk) ([raw file](https://github.com/cockroachdb/cockroach/blob/d43fc17545a0760f09e00cbe107369e3165dfa05/pkg/sql/distsqlrun/aggregator.go#L285)):*
> ```Go
> 	ag.buckets = nil
> 
> 	log.VEvent(ag.ctx, 1, "accumulation complete")
> ```

Why did this get deleted? It's useful to keep stuff like this for traces. Perhaps it belongs near the state machine transitions.

---

*[pkg/sql/distsqlrun/aggregator.go, line 367 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113#-L9RPfsT3wkWCqQkBQV4:-L9RPfsT3wkWCqQkBQV5:bif87a0) ([raw file](https://github.com/cockroachdb/cockroach/blob/d43fc17545a0760f09e00cbe107369e3165dfa05/pkg/sql/distsqlrun/aggregator.go#L367)):*
> ```Go
> 		}
> 
> 		if row != nil || meta != nil || ag.state == aggDone {
> ```

What does it mean if row == nil and meta == nil?

---

*[pkg/sql/distsqlrun/aggregator.go, line 292 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113#-L9RUp3u8KCvcHg4x4vd:-L9RUp3u8KCvcHg4x4ve:b-jf8vwf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d18c7efe9c32d8cde97f269c226dfaa824fabb8/pkg/sql/distsqlrun/aggregator.go#L292)):*
> ```Go
> 			ag.lastOrdGroupCols = row
> 		}
> 		matched, err := ag.matchLastOrdGroupCols(row)
> ```

It seems wrong that we always run `matchLastOrdGroupCols` the first time. Can you fix this so that if you've just assigned to `lastOrdGrouCols`, you don't have to run the matcher?

---

*[pkg/sql/distsqlrun/aggregator.go, line 353 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113#-L9RVmz70EyVytPCosLv:-L9RVmz70EyVytPCosLw:bbg3r4d) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d18c7efe9c32d8cde97f269c226dfaa824fabb8/pkg/sql/distsqlrun/aggregator.go#L353)):*
> ```Go
> 				return aggDraining, nil, ag.producerMeta(nil /* err */)
> 			}
> ```

Can you include a comment here that describes when this whole stanza happens? I assume it's only in the new case where there are ordered columns, right?

---

*[pkg/sql/distsqlrun/flow_diagram.go, line 265 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113#-L9RUVI5BBMZ6fnl6kb6:-L9RUVI5BBMZ6fnl6kb7:banhasn) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d18c7efe9c32d8cde97f269c226dfaa824fabb8/pkg/sql/distsqlrun/flow_diagram.go#L265)):*
> ```Go
> 	}
> 	if len(d.OrderedColumns) > 0 {
> 		details = append(details, fmt.Sprintf("Ordered: %s", colListStr(d.OrderedColumns)))
> ```

Whoa, this is just a random bug I guess - why did no tests catch this? What is this summary() for?

---

*[pkg/sql/distsqlrun/processors.proto, line 444 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113#-L9RUKgi6xYHt9xR1rZx:-L9RUKgi6xYHt9xR1rZy:b-au55zw) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d18c7efe9c32d8cde97f269c226dfaa824fabb8/pkg/sql/distsqlrun/processors.proto#L444)):*
> ```protobuf
>   // If some of the group columns have an ordering, we can perform a streaming
>   // aggregation, so this field can be specified if additional optimizations are
>   // possible.
> ```

This comment could be improved. ordered_group_cols is the subset of group_cols that are also known to be ordered.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113#-:-L9RWqT93vejBCIsiSPv:bv51l2s)*

**Comment by abhimadan** [comment]
Just quickly addressing some comments now; I'll address the remaining comments and make changes a bit later.

I'm also moving the first commit to its own PR, since this PR is pretty large right now, and that commit may be of interest independent of the streaming aggregation work.

---

Review status: 8 of 18 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/aggregator.go, line 285 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113#-L9RTmyXEfobFHGeOweU:-L9RY-860LL0yFpucUpo:b-3tl53w) ([raw file](https://github.com/cockroachdb/cockroach/blob/d43fc17545a0760f09e00cbe107369e3165dfa05/pkg/sql/distsqlrun/aggregator.go#L285)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Why did this get deleted? It's useful to keep stuff like this for traces. Perhaps it belongs near the state machine transitions.
</blockquote></details>

The log isn't entirely accurate in its current place anymore, because starting to emit rows doesn't imply that the input has been fully accumulated. Also, even if it was reworded, this state transition could happen enough that the log would be spammy. I should probably move it to another place though (when `inputDone` gets set).

---

*[pkg/sql/distsqlrun/aggregator.go, line 367 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113#-L9RPfsT3wkWCqQkBQV4:-L9RYLT23OLnPwt2_ePb:b-jn7scd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d43fc17545a0760f09e00cbe107369e3165dfa05/pkg/sql/distsqlrun/aggregator.go#L367)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

What does it mean if row == nil and meta == nil?
</blockquote></details>

`row == nil` and `meta == nil` without being in the `aggDone` state indicate a state transition without any associated output (being in the `aggDone` state with those conditions is the termination condition for the processor's execution). Another loop iteration needs to happen to get rows. This should definitely be documented though, so I'll add a comment about that.

---

*[pkg/sql/distsqlrun/flow_diagram.go, line 265 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113#-L9RUVI5BBMZ6fnl6kb6:-L9RYYjf8YXWco8oB39o:b-frbbh2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d18c7efe9c32d8cde97f269c226dfaa824fabb8/pkg/sql/distsqlrun/flow_diagram.go#L265)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Whoa, this is just a random bug I guess - why did no tests catch this? What is this summary() for?
</blockquote></details>

We don't really have tests for `EXPLAIN` diagrams except logic tests, and those don't really verify that the `EXPLAIN` output is sensible. This changes the `summary()` for `DistinctSpec`, and some logic tests did actually change as a result of this, in `distsql_distinct_on`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113#-:-L9RXqhU5UZUceXTJd2y:b-10lqxu)*

**Comment by abhimadan** [comment]
The first commit is now part of #24573, so PTAL at that PR if you have comments on the state machine refactor.

---

Review status: 0 of 18 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsqlrun/aggregator.go, line 367 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113#-L9RPfsT3wkWCqQkBQV4:-L9RioIt8A1S-foLBuUT:b-60l5lp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d43fc17545a0760f09e00cbe107369e3165dfa05/pkg/sql/distsqlrun/aggregator.go#L367)):*
<details><summary><i>Previously, abhimadan (Abhishek Madan) wrote…</i></summary><blockquote>

`row == nil` and `meta == nil` without being in the `aggDone` state indicate a state transition without any associated output (being in the `aggDone` state with those conditions is the termination condition for the processor's execution). Another loop iteration needs to happen to get rows. This should definitely be documented though, so I'll add a comment about that.
</blockquote></details>

Improved the `return ... nil, nil` comments, and commented here as well.

---

*[pkg/sql/distsqlrun/aggregator.go, line 292 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113#-L9RUp3u8KCvcHg4x4vd:-L9RiT_b7NMcJj0m0mid:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d18c7efe9c32d8cde97f269c226dfaa824fabb8/pkg/sql/distsqlrun/aggregator.go#L292)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

It seems wrong that we always run `matchLastOrdGroupCols` the first time. Can you fix this so that if you've just assigned to `lastOrdGrouCols`, you don't have to run the matcher?
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/aggregator.go, line 353 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113#-L9RVmz70EyVytPCosLv:-L9RiibKA6xk57lnACmf:bzf8v5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d18c7efe9c32d8cde97f269c226dfaa824fabb8/pkg/sql/distsqlrun/aggregator.go#L353)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Can you include a comment here that describes when this whole stanza happens? I assume it's only in the new case where there are ordered columns, right?
</blockquote></details>

You're right about what this part is for. Added a comment.

---

*[pkg/sql/distsqlrun/processors.proto, line 444 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113#-L9RUKgi6xYHt9xR1rZx:-L9Rirs2EDty3fiXe34w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d18c7efe9c32d8cde97f269c226dfaa824fabb8/pkg/sql/distsqlrun/processors.proto#L444)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This comment could be improved. ordered_group_cols is the subset of group_cols that are also known to be ordered.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113#-:-L9RiIYvEzdC9kqcT3eS:bw8mjdq)*

**Comment by RaduBerinde** [comment]
Very nice work!

---

Review status: 0 of 18 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 1245 at r8](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113#-L9XArwtCyf4pv4_ZLQa:-L9XArwtCyf4pv4_ZLQb:b-klclet) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eddc4099bff73f3da52eea004ad472dff1920e5/pkg/sql/distsql_physical_planner.go#L1245)):*
> ```Go
> 		finalIdxMap := make([]uint32, nFinalAgg)
> 		finalGroupCols := make([]uint32, len(groupCols))
> 		finalOrderedGroupCols := make([]uint32, 0, len(orderedGroupCols))
> ```

[nit] a comment would help. I think it would be clearer to calculate this at the end, using something like
```go
for i, c := range orderedGroupCols {
  finalOrderedGroupCols[i] = finalGroupCols[c]
}
```
  

---

*[pkg/sql/distsql_physical_planner.go, line 1408 at r8](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113#-L9XNoN33o8CS_meR0D5:-L9XNoN33o8CS_meR0D6:b-1mivje) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eddc4099bff73f3da52eea004ad472dff1920e5/pkg/sql/distsql_physical_planner.go#L1408)):*
> ```Go
> 
> 		// Create the merge ordering for the local stage.
> 		childGroupProps := planPhysicalProps(n.plan)
> ```

[nit] I would name this `groupColProps` (same in doExpandPlan)

---

*[pkg/sql/distsql_physical_planner.go, line 1413 at r8](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113#-L9XD2QV0bHVNtgiP-rF:-L9XD2QV0bHVNtgiP-rG:b-6b54iv) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eddc4099bff73f3da52eea004ad472dff1920e5/pkg/sql/distsql_physical_planner.go#L1413)):*
> ```Go
> 	OrderingLoop:
> 		for _, o := range childGroupProps.ordering {
> 			for i, agg := range localAggs {
> ```

Going through localAggs seems a bit hacky, we could find which group column it is and then use `finalOrderedGroupCols`

---

*[pkg/sql/expand_plan.go, line 677 at r8](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113#-L9XQWn78BDE3YLQaGQA:-L9XQWn78BDE3YLQaGQB:bragak9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eddc4099bff73f3da52eea004ad472dff1920e5/pkg/sql/expand_plan.go#L677)):*
> ```Go
> 		n.source = p.simplifyOrderings(n.source, usefulOrdering)
> 
> 	case *groupNode:
> ```

here we need to trim the ordering in `n.props`. We don't want to maintain whatever output ordering it promises unless we need it

---

*[pkg/sql/group.go, line 371 at r7](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113#-L9XA14LCtuM4ECcg0RS:-L9XA14LCtuM4ECcg0RT:blz5mxu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a7ed0e9a4f8628189d818efb6d26557e9f16b5e/pkg/sql/group.go#L371)):*
> ```Go
> }
> 
> func (n *groupNode) accumulateRow(params runParams, values tree.Datums) error {
> ```

[nit] could use a comment

---

*[pkg/sql/group.go, line 406 at r7](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113#-L9X9Y5I9MIzl7PWYqcM:-L9X9Y5I9MIzl7PWYqcN:b-xucght) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a7ed0e9a4f8628189d818efb6d26557e9f16b5e/pkg/sql/group.go#L406)):*
> ```Go
> 
> func (n *groupNode) Next(params runParams) (bool, error) {
> 	// We're going to consume n.plan and accumulate its rows until it's either
> ```

[nit] consume usually means we read it all, I'd just say "We're going to accumulate rows from n.plan"

---

*[pkg/sql/distsqlrun/aggregator.go, line 253 at r6](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113#-L9X7QiJ8uOA-9dQ0asc:-L9X7QiJ8uOA-9dQ0asd:b-jday5r) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f9a29a21a1407449bfdd328590693ce6486016/pkg/sql/distsqlrun/aggregator.go#L253)):*
> ```Go
> }
> 
> func (ag *aggregator) matchLastOrdGroupCols(row sqlbase.EncDatumRow) (bool, error) {
> ```

[nit] this function needs a comment

---

*[pkg/sql/distsqlrun/aggregator.go, line 434 at r6](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113#-L9X7qI09odMs3xjCNVv:-L9X7qI09odMs3xjCNVw:btl5ldy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f9a29a21a1407449bfdd328590693ce6486016/pkg/sql/distsqlrun/aggregator.go#L434)):*
> ```Go
> 		// indicates that we have a state transition without any output. As a
> 		// result, we need to execute the next state to produce output.
> 		if row != nil || meta != nil || ag.state == aggDone {
> ```

[nit] I would write this as `!(row == nil && meta == nil && ag.state != aggDone)` to match the comment

---

*[pkg/sql/distsqlrun/aggregator_test.go, line 19 at r6](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113#-L9X7xeN3rmwxVS4NT6R:-L9X7xeN3rmwxVS4NT6S:b-vc9b95) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f9a29a21a1407449bfdd328590693ce6486016/pkg/sql/distsqlrun/aggregator_test.go#L19)):*
> ```Go
> import (
> 	"context"
> 	math "math"
> ```

just "math"

---

*[pkg/sql/logictest/testdata/logic_test/aggregate, line 1520 at r8](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113#-L9XQhPbBu4cD3t29QI_:-L9XQhPbBu4cD3t29QIa:b-9ssjd5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eddc4099bff73f3da52eea004ad472dff1920e5/pkg/sql/logictest/testdata/logic_test/aggregate#L1520)):*
> ```
> EXPLAIN (VERBOSE) SELECT x, max(y) FROM group_ord GROUP BY x
> ----
> group           0  group   ·            ·                        (x, max)            x!=NULL; key(x); +x
> ```

This is an example relevant to trimming the props: the `+x` should only be here if it's actually used by the query. In this case, if we have multiple final aggregator stages, we will use ordered synchronizers on the results where we could use just unordered.

I'd add a test case with the same query and ORDER BY x

---

*[pkg/sql/logictest/testdata/logic_test/distsql_agg, line 702 at r8](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113#-L9XRO503mJeXK6qiyEQ:-L9XRO503mJeXK6qiyER:bv1zf81) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eddc4099bff73f3da52eea004ad472dff1920e5/pkg/sql/logictest/testdata/logic_test/distsql_agg#L702)):*
> ```
> SELECT "URL" FROM [EXPLAIN (DISTSQL) SELECT a, max(b) FROM sorted_data GROUP BY a]
> ----
> https://cockroachdb.github.io/distsqlplan/decode.html?eJzUlk1r20AQhu_9FWFOCd1CdiW7iU4KtAcfapeQQ6GIsvEOisHxit01NAT_9yLvQbFNZhK2QdJRH8-8s3nEGz_Dxhqc60f0UPwGCQIUCMhAQA4CJlAJaJxdovfWta9EYGb-QnEpYLVptqG9XQlYWodQPENYhTVCAXf6fo23qA06EGAw6NV6H9K41aN2T6W3LqD5Y3TQIGCxDcVZKUWpoNoJsNvQjfZB1wiF3Im3x9_UtcNaB3uUXrZnXDiDDk0bCAJm377P785LeQECftz8Oi_VxdEO3dj7p7MH7R9OZla7bk_16p7dHBs3OJ7zOQ760MN0i2b_fdG5_WKbg3dfy84PsmW_3xITP5hvSY7lW1L9-mTiB-NTjcVn1q9PJn4wPrOx-Mz79cnED8ZnPhafzI-hW_SN3Xh803_my_YUaGqMp_Z265b409nlPiZeLvbc_oZBH-JTGS9mm_ioXfAlLI9h-RJWB7B8HzxNga9TYJm0t5zQtCL_3hkNZ7SsKW0rJ-kJDU9SVNMwo5qGGdU0zKlmaEb1NEX1VxK-omVdpciiYUYWDTOyaJiTxdCMrOsUWZJpUa5G03o0rUjTmjSxStO6VCaVqWTaNGekndTpu6TRNCeNpjlpNM1KY3BO2kmpktKq3ad_AQAA__9Z3R2M
> ```

Note the final ordered synchronizer here: it should be unordered. Using ordered is not incorrect, just slower.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113#-:-L9XRZeA6sJURnN_HK62:bdm1mhe)*

**Comment by abhimadan** [comment]
Review status: 0 of 18 files reviewed at latest revision, 10 unresolved discussions.

---

*[pkg/sql/distsql_physical_planner.go, line 1245 at r8](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113#-L9XArwtCyf4pv4_ZLQa:-L9frtilDtVzYZMs6WPw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eddc4099bff73f3da52eea004ad472dff1920e5/pkg/sql/distsql_physical_planner.go#L1245)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] move the definition of the field right before the loop
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113)*

**Comment by abhimadan** [comment]
Review status: 7 of 18 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/sql/distsqlrun/aggregator.go, line 373 at r15](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113#-L9qVABe4WHD2RsjdmFf:-L9qYW_-4RTaZOuXQTKd:bs3jwlc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4759b38f16208fe65f4338b0377547974b0cbb60/pkg/sql/distsqlrun/aggregator.go#L373)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

something about this english seems confusing - double check it?
</blockquote></details>

Thanks for catching this; I forgot to proofread this comment. Should be at least grammatically correct now.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113)*

**Comment by abhimadan** [comment]
Improved the commit messages and added a new SQL`bench_test` benchmark for an example query that benefits from streaming aggregations. TFTRs everyone!

---

Review status: 8 of 19 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24113#-:-L9uQk2b2dUIG7hn0OBy:bfwqzjk)*

**Pull request merged**
