### PR TITLE
pgwire,logpb,eventpb: various structured logging doc updates

### LINKED ISSUE #63762: server: SQL_PERF documentation should mention sql.log.slow_query.experimental_full_table_scans.enabled
The SQL_PERF logging channel can report all queries performing full table or index scans. In order to do this, the cluster setting `sql.log.slow_query.experimental_full_table_scans.enabled` must first be set. This is missing from the [auto-generated logging documentation](https://github.com/cockroachdb/cockroach/blob/master/docs/generated/eventlog.md) for "SQL Slow Query Log".

cc @knz

### LINKED ISSUE #63764: server: setting to enable pgwire events logging in SQL_EXEC channel
The SQL_EXEC logging channel can log pgwire events, according to the [auto-generated doc](https://github.com/cockroachdb/cockroach/blob/master/docs/generated/logging.md). This states that a setting must be enabled. This setting is not yet created or implemented.

cc @knz

### PR DESCRIPTION
**Pull request by knz**
First commit from #62629.
Fixes #63764. 
Fixes #63762. 

See individual commits for details.

cc @taroface

### CODE REVIEW

**Comment by knz** [comment]
friendly ping

**Comment by knz** [comment]
@rauchenstein could you review this as well? Thanks

cc @taroface

**Review by taroface — APPROVED** [review]
LGTM, and I updated the logging docs PR to reflect the update to `SQL_EXEC`. Thank you!

> Reviewed 1 of 1 files at r1, 5 of 5 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63841#-:-MZxjlOX202wsnfsjMVY:b-fbum5q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @rauchenstein)

**Comment by knz** [comment]
bors r=taroface

**Pull request merged**
