### PR TITLE
sql: assorted mutation fixes

### LINKED ISSUE #25742: sql: computed columns panic with mismatched types with INSERT data sources
This is a follow-on from #25721.

```
root@127.0.0.1:50885/demo> create table a (a decimal primary key);
CREATE TABLE

Time: 4.222863ms

root@127.0.0.1:50885/demo> create table b (a int primary key, b int as (a + 1) stored);
CREATE TABLE

Time: 4.76973ms

root@127.0.0.1:50885/demo> insert into a values(1.1);
INSERT 1

Time: 2.899824ms

root@127.0.0.1:50885/demo> insert into b select a from a;
```

This panics the server for the same reason as in #25721 - although #25741 forces `VALUES` clauses to type-check themselves up front, using other data sources as inputs to `INSERT` still don't get properly type checked.

The root cause for this is that the `desiredTypes` parameter to `newPlan` is never actually validated - we just use those types as hints. The solution is to audit all uses of `desiredTypes` and ensure that they're being required, not just used as hints.

### LINKED ISSUE #29494: sql: `UPDATE RETURNING` can return mutation columns
SQL is never allowed to show mutation columns to the user, but `UPDATE RETURNING` allows this:

```
root@:26257/defaultdb> show create table b;
+------------+-----------------------------------------------+
| table_name |               create_statement                |
+------------+-----------------------------------------------+
| b          | CREATE TABLE b (                              |
|            |                                               |
|            |     a INT NOT NULL,                           |
|            |                                               |
|            |     b INT NOT NULL DEFAULT 1:::INT,           |
|            |                                               |
|            |     CONSTRAINT "primary" PRIMARY KEY (a ASC), |
|            |                                               |
|            |     FAMILY "primary" (a, b)                   |
|            |                                               |
|            | )                                             |
+------------+-----------------------------------------------+
(1 row)

Time: 5.947ms

root@:26257/defaultdb> update b set b=-2 where a=-2 returning c;
+---+
| c |
+---+
| 1 |
+---+
(1 row)

Time: 9.762ms
```

To produce this state, I added a new column `c` and restarted the server before the backfill could complete.

### LINKED ISSUE #29497: sql: `INSERT ON CONFLICT DO UPDATE` can reference mutation columns
Similar to #29494:

```
root@:26257/defaultdb> select *,d from b where a=-10;
pq: column "d" does not exist
root@:26257/defaultdb> insert into b values(1,2) on conflict(a) do update set d=3 returning c;
+---+
| c |
+---+
| 1 |
+---+
(1 row)
```

The second statement shouldn't be able to see `d` - it's a mutation column.

### LINKED ISSUE #31255: sql: `INSERT ON CONFLICT DO UPDATE` can reference computed columns
```sql
> create table tc(x int primary key, y int as (x+1) stored);
> insert into tc(x) values(1) on conflict(x) do update set y = 456; -- woops?
> select * from tc;
 x | y
 1 | 2
> insert into tc(x) values(1) on conflict(x) do update set y = 123; -- woops?
> select * from tc;
 x | y
 1 | 2
```

The SET is allowed on computed columns, the assignment is internally processed but then discarded (overwritten) by  the computed column computation.

cc @jordanlewis

### PR DESCRIPTION
**Pull request by knz**
Fixes #25742.
Fixes #26106.
Fixes #29494.
Fixes #31255.
Fixes #29497.

~This may even full address #26106 but I have a couple more checks to add first to confirm this.~ edit: it does

### CODE REVIEW

**Comment by knz** [comment]
I did manually check that the insert fast path do verify check and column constraints. Also in the code it's pretty clear because both the slow and fast path the same `GenerateInsertRow()` method which performs the check.

This was not true in previous versions, but I had forgotten that I fixed this at some point :)

**Comment by knz** [comment]
I think I squashed them all. It would be great if this got reviewed and backported this week.

**Comment by knz** [comment]
yay it's green

**Review by BramGruneir — APPROVED** [review]
:lgtm:

Just a few of small comments.  

Well done!

> Reviewed 10 of 10 files at r1, 3 of 3 files at r2, 4 of 4 files at r3, 2 of 2 files at r4, 6 of 6 files at r5, 3 of 3 files at r6, 1 of 1 files at r7, 2 of 2 files at r8, 2 of 2 files at r9, 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31222#-:-LOYppNRExbfcDWwRZuL:bu6w1zj)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/descriptor_mutation_test.go, line 307 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/31222#-LOYp0tJCB56sABBw3nC:-LOYp0tJCB56sABBw3nD:bk2dqjx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b93307e262f917ddfcae60e49152f3faaa216de7/pkg/sql/descriptor_mutation_test.go#L307)):*
> ```Go
> 						_, err = sqlDB.Exec(`INSERT INTO t.test VALUES ('b', 'y', 'i')`)
> 					}
> 					if !testutils.IsError(err, "(IN|UP)SERT has more expressions than target columns, 3 expressions for 2 targets") {
> ```

Why would this be upsert?
___
*[pkg/sql/logictest/testdata/logic_test/collatedstring, line 219 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31222#-LOYl161-poRWIi8XNQj:-LOYl161-poRWIi8XNQk:bl5cx6k) ([raw file](https://github.com/cockroachdb/cockroach/blob/552f42a7572bc8b33cbe2220fdbe776b10b1c1c5/pkg/sql/logictest/testdata/logic_test/collatedstring#L219)):*
> ```
>   ('ü' COLLATE en)
> 
> statement error value type collatedstring{de} doesn't match type STRING COLLATE en of column "a"
> ```

I prefer the earlier error.  It was clearer on what was wrong.
___
*[pkg/sql/logictest/testdata/logic_test/delete, line 187 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31222#-LOYnOTA786yoxgsrsmR:-LOYnOTA786yoxgsrsmS:b592e65) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8e5b9bc5382b21e1b021b2487b246e1c1c2da4/pkg/sql/logictest/testdata/logic_test/delete#L187)):*
> ```
> 1
> 
> # Regression tests for #29494
> ```

subtest please
___
*[pkg/sql/logictest/testdata/logic_test/insert, line 545 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31222#-LOYmEXN5W0WOBWnHpIe:-LOYmEXN5W0WOBWnHpIf:b3guhj8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7276f260bc5ccb83a71a49ae4ab983a9af1e9c19/pkg/sql/logictest/testdata/logic_test/insert#L545)):*
> ```
> # This test requires that the error message for a CHECK constraint
> # validation error be different than a column validation error. So we
> # test the former first, as a sanity check.
> ```

Subtest please, and please pass these through sqlfmt.
___
*[pkg/sql/logictest/testdata/logic_test/insert, line 566 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31222#-LOYmf_w-4vN3cM02A2D:-LOYmf_w-4vN3cM02A2E:b592e65) ([raw file](https://github.com/cockroachdb/cockroach/blob/16e8b340c716b6d4fbea9f20fd68d45c179ec4c0/pkg/sql/logictest/testdata/logic_test/insert#L566)):*
> ```
> 
> # Verify that column constraints and CHECK handling occur before
> # foreign key validation.
> ```

subtest please
___
*[pkg/sql/logictest/testdata/logic_test/insert, line 577 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31222#-LOYmx4D3ISPFkRcQPQe:-LOYmx4E-ny5N9Xh7US-:b-n56zwj) ([raw file](https://github.com/cockroachdb/cockroach/blob/16e8b340c716b6d4fbea9f20fd68d45c179ec4c0/pkg/sql/logictest/testdata/logic_test/insert#L577)):*
> ```
> 
> statement error failed to satisfy CHECK constraint
> INSERT INTO derived(y) VALUES('abcd')
> ```

please add an FK violation here too then one that passes all checks, just to complete the test
___
*[pkg/sql/logictest/testdata/logic_test/insert, line 579 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31222#-LOYnRYmAmZ7bVS3NdV8:-LOYnRYmAmZ7bVS3NdV9:b592e65) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8e5b9bc5382b21e1b021b2487b246e1c1c2da4/pkg/sql/logictest/testdata/logic_test/insert#L579)):*
> ```
> INSERT INTO derived(y) VALUES('abcd')
> 
> # Regression tests for #29494
> ```

subtest please
___
*[pkg/sql/logictest/testdata/logic_test/update, line 395 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31222#-LOYmM-vC8yuEkBYFw6j:-LOYmM-vC8yuEkBYFw6k:b4aak6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/7276f260bc5ccb83a71a49ae4ab983a9af1e9c19/pkg/sql/logictest/testdata/logic_test/update#L395)):*
> ```
> # validation error be different than a column validation error. So we
> # test the former first, as a sanity check.
> statement ok
> ```

subtest please, and sqlfmt.
___
*[pkg/sql/logictest/testdata/logic_test/update, line 416 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31222#-LOYn6Sz2nk6ADUCqRtp:-LOYn6Sz2nk6ADUCqRtq:b-j1nqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/16e8b340c716b6d4fbea9f20fd68d45c179ec4c0/pkg/sql/logictest/testdata/logic_test/update#L416)):*
> ```
> UPDATE tn2 SET y = 'abcd'
> 
> # Verify that column constraints and CHECK handling occur before
> ```

subtest, and add an fk violation and then a case that passes all.
___
*[pkg/sql/logictest/testdata/logic_test/update, line 431 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31222#-LOYnYqm0rkBRVSksA0l:-LOYnYqn0mITlLVov_rO:b-flz53e) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8e5b9bc5382b21e1b021b2487b246e1c1c2da4/pkg/sql/logictest/testdata/logic_test/update#L431)):*
> ```
> UPDATE derived SET y = 'abcd'
> 
> # Regression tests for #29494
> ```

subtest please

Nice test.
___
*[pkg/sql/logictest/testdata/logic_test/upsert, line 601 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31222#-LOYmVqc6yhi4x_ouqiu:-LOYmVqc6yhi4x_ouqiv:b6pcdnv) ([raw file](https://github.com/cockroachdb/cockroach/blob/7276f260bc5ccb83a71a49ae4ab983a9af1e9c19/pkg/sql/logictest/testdata/logic_test/upsert#L601)):*
> ```
> # validation error be different than a column validation error. So we
> # test the former first, as a sanity check.
> statement ok
> ```

subtest please and sqlfmt
___
*[pkg/sql/logictest/testdata/logic_test/upsert, line 620 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31222#-LOYnisq7TyaGuaAidlC:-LOYnisq7TyaGuaAidlD:b592e65) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8e5b9bc5382b21e1b021b2487b246e1c1c2da4/pkg/sql/logictest/testdata/logic_test/upsert#L620)):*
> ```
> UPSERT INTO tn2(x, y) VALUES (123, 'abcd')
> 
> # Regression tests for #29494
> ```

subtest please
___
*[pkg/sql/logictest/testdata/logic_test/upsert, line 648 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/31222#-LOYocoOCPiVjY35FIP8:-LOYocoPBqgPelCIsvYB:b592e65) ([raw file](https://github.com/cockroachdb/cockroach/blob/44d890dca9e62d2cdbecc61682fa1276d6b8b1ba/pkg/sql/logictest/testdata/logic_test/upsert#L648)):*
> ```
> ROLLBACK
> 
> # Regression test for #31255
> ```

subtest please
___
*[pkg/sql/logictest/testdata/logic_test/upsert, line 662 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/31222#-LOYpisO9n1PHG4TspcA:-LOYpisO9n1PHG4TspcB:b592e65) ([raw file](https://github.com/cockroachdb/cockroach/blob/b89b30434adf848fce689af604553610b5495cf9/pkg/sql/logictest/testdata/logic_test/upsert#L662)):*
> ```
> UPSERT INTO tc VALUES (1,2)
> 
> # Regression test for #29497
> ```

subtest please

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31222)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/descriptor_mutation_test.go, line 307 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/31222#-LOYp0tJCB56sABBw3nC:-LOYrWh_9Sl-aeStHgLw:bxyywxg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b93307e262f917ddfcae60e49152f3faaa216de7/pkg/sql/descriptor_mutation_test.go#L307)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why would this be upsert?
</blockquote></details>

See the 5 lines before: the test uses both forms one after the other.
___
*[pkg/sql/logictest/testdata/logic_test/collatedstring, line 219 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31222#-LOYl161-poRWIi8XNQj:-LOYrd4t-KKBs04KvExJ:bh1f85q) ([raw file](https://github.com/cockroachdb/cockroach/blob/552f42a7572bc8b33cbe2220fdbe776b10b1c1c5/pkg/sql/logictest/testdata/logic_test/collatedstring#L219)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

I prefer the earlier error.  It was clearer on what was wrong.
</blockquote></details>

I'll file a followup PR to clarify. Having a detailed error message requires more and more complex code.
___
*[pkg/sql/logictest/testdata/logic_test/delete, line 187 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31222#-LOYnOTA786yoxgsrsmR:-LOZAMtJ6PIZTiq9HKdk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8e5b9bc5382b21e1b021b2487b246e1c1c2da4/pkg/sql/logictest/testdata/logic_test/delete#L187)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

subtest please
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/insert, line 545 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31222#-LOYmEXN5W0WOBWnHpIe:-LOZAUoX0CMKCSIEQdT7:b-c5i0v) ([raw file](https://github.com/cockroachdb/cockroach/blob/7276f260bc5ccb83a71a49ae4ab983a9af1e9c19/pkg/sql/logictest/testdata/logic_test/insert#L545)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Subtest please, and please pass these through sqlfmt.
</blockquote></details>

Done.

sqlfmt doesn't make any change - it all fits on 1 line.
___
*[pkg/sql/logictest/testdata/logic_test/insert, line 566 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31222#-LOYmf_w-4vN3cM02A2D:-LOZAsCQ66L0QGju0h0z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/16e8b340c716b6d4fbea9f20fd68d45c179ec4c0/pkg/sql/logictest/testdata/logic_test/insert#L566)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

subtest please
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/insert, line 577 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31222#-LOYmx4D3ISPFkRcQPQe:-LOZCoZc7ksEGspf6S-s:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/16e8b340c716b6d4fbea9f20fd68d45c179ec4c0/pkg/sql/logictest/testdata/logic_test/insert#L577)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

please add an FK violation here too then one that passes all checks, just to complete the test
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/insert, line 579 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31222#-LOYnRYmAmZ7bVS3NdV8:-LOZCoD53wogMZxeE5jM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8e5b9bc5382b21e1b021b2487b246e1c1c2da4/pkg/sql/logictest/testdata/logic_test/insert#L579)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

subtest please
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/update, line 395 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31222#-LOYmM-vC8yuEkBYFw6j:-LOZAwszDiYH2kyEdwJh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7276f260bc5ccb83a71a49ae4ab983a9af1e9c19/pkg/sql/logictest/testdata/logic_test/update#L395)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

subtest please, and sqlfmt.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/update, line 416 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31222#-LOYn6Sz2nk6ADUCqRtp:-LOZBSni3NJfEDbGi_ba:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/16e8b340c716b6d4fbea9f20fd68d45c179ec4c0/pkg/sql/logictest/testdata/logic_test/update#L416)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

subtest, and add an fk violation and then a case that passes all.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/update, line 431 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31222#-LOYnYqm0rkBRVSksA0l:-LOZBwaU85Ig0W1QLtfy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8e5b9bc5382b21e1b021b2487b246e1c1c2da4/pkg/sql/logictest/testdata/logic_test/update#L431)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

subtest please

Nice test.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/upsert, line 601 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31222#-LOYmVqc6yhi4x_ouqiu:-LOZAzxN8SAUNeYUUWgb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7276f260bc5ccb83a71a49ae4ab983a9af1e9c19/pkg/sql/logictest/testdata/logic_test/upsert#L601)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

subtest please and sqlfmt
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/upsert, line 620 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31222#-LOYnisq7TyaGuaAidlC:-LOZCJC5-glzaeMDlRXc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8e5b9bc5382b21e1b021b2487b246e1c1c2da4/pkg/sql/logictest/testdata/logic_test/upsert#L620)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

subtest please
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/upsert, line 648 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/31222#-LOYocoOCPiVjY35FIP8:-LOZCK06E8kZPij5aPeW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/44d890dca9e62d2cdbecc61682fa1276d6b8b1ba/pkg/sql/logictest/testdata/logic_test/upsert#L648)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

subtest please
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/upsert, line 662 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/31222#-LOYpisO9n1PHG4TspcA:-LOZCmAj0Ak1N83qPmSG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b89b30434adf848fce689af604553610b5495cf9/pkg/sql/logictest/testdata/logic_test/upsert#L662)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

subtest please
</blockquote></details>

Done.

**Comment by knz** [comment]
should I prepare the backport already?

**Review by BramGruneir — COMMENTED** [review]
:lgtm:

And yes, go for it.

> Reviewed 1 of 3 files at r12, 4 of 6 files at r15, 2 of 3 files at r16, 1 of 2 files at r19, 2 of 2 files at r20.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31222#-:-LOZRui0BVmdHKS3yNRY:b3ni5at)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by jordanlewis — APPROVED** [review]
:lgtm: wow, great work

> Reviewed 5 of 10 files at r1, 12 of 12 files at r11, 3 of 3 files at r12, 4 of 4 files at r13, 2 of 2 files at r14, 5 of 6 files at r15, 2 of 3 files at r16, 1 of 1 files at r17, 2 of 2 files at r18, 2 of 2 files at r19.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31222#-:-LOZT9Fe5-0AtZdrlwqV:bz5uyo8)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/sqlbase/column_type_properties.go, line 654 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/31222#-LOZRq8k0XTeFWa8UtW-:-LOZRq8k0XTeFWa8UtW0:b-s6d3yh) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c7d584fd5e1de1c358231d424d2fbe26cb3ee0c/pkg/sql/sqlbase/column_type_properties.go#L654)):*
> ```Go
> 
> 		if typ.Width > 0 && utf8.RuneCountInString(sv) > int(typ.Width) {
> 			return pgerror.NewErrorf(pgerror.CodeStringDataRightTruncationError,
> ```

yay! nice precise pg errors.

**Comment by knz** [comment]
cool thanks

bors r+

**Pull request merged**
