### PR TITLE
distsql: router by hash

### PR DESCRIPTION
**Pull request by RaduBerinde**
Implementation of BY_HASH router, which distributes rows to multiple streams so
that all rows that have the same values on certain columns end up into the same
stream.

Part of #7588.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8426)

### CODE REVIEW

**Comment by paperstreet** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/distsql/routers.go, line 40 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8426#-KOkzNqeKREnpL9j57px:-KOkzNqeKREnpL9j57py:b-r7zu61) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4198c70b88894fba5390d5efe6404e2a8426d02/sql/distsql/routers.go#L40)):*
> ```Go
> 	case OutputRouterSpec_BY_HASH:
> 		if len(spec.HashColumns) == 0 {
> 			return nil, errors.Errorf("no hash columns for BY_HASH router")
> ```

nit: I'd expect makeHashRouter to be responsible for this check

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8426)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/distsql/routers.go, line 40 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8426#-KOkzNqeKREnpL9j57px:-KOl3zdyMSC-OVh4D99C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4198c70b88894fba5390d5efe6404e2a8426d02/sql/distsql/routers.go#L40)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> nit: I'd expect makeHashRouter to be responsible for this check
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8426)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[sql/distsql/data.proto, line 111 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8426#-KOqoBeh2CzIm6DI3me8:-KOqoBeh2CzIm6DI3me9:b868tnw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4198c70b88894fba5390d5efe6404e2a8426d02/sql/distsql/data.proto#L111)):*
> ```protobuf
>     MIRROR = 0;
>     // Each row is sent to one stream, chosen by hashing certain columns of
>     // the row. TODO(radu): an extra optional structure below for the hashing
> ```

remove TODO now?

---

*[sql/distsql/routers.go, line 45 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8426#-KOqpZCxKtPwH658A5p5:-KOqpZCxKtPwH658A5p6:bqp91f0) ([raw file](https://github.com/cockroachdb/cockroach/blob/711450859f5940a9b45a9b546961d6d28591941c/sql/distsql/routers.go#L45)):*
> ```Go
> }
> 
> type hashRouter struct {
> ```

maybe now's a good time to add a file-level comment about routers.

---

*[sql/distsql/routers.go, line 96 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8426#-KOqplMc43SNtdgAWe2a:-KOqplMc43SNtdgAWe2b:br0e2la) ([raw file](https://github.com/cockroachdb/cockroach/blob/711450859f5940a9b45a9b546961d6d28591941c/sql/distsql/routers.go#L96)):*
> ```Go
> 	streamIdx := crc32.Update(0, crc32Table, hr.buffer) % uint32(len(hr.streams))
> 
> 	// We can't return false if this stream happened to not need any more rows. We
> ```

hmmm is it expected that a receiver from a hash router would say "no more rows"? Maybe that's an unexpected error?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8426#-:-KOqq2NrTpkwpnITRMqZ:bnfp4nl)*

**Comment by RaduBerinde** [comment]
TFTR!

---

Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/distsql/data.proto, line 111 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8426#-KOqoBeh2CzIm6DI3me8:-KOqtduk80YcQii9c-AU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4198c70b88894fba5390d5efe6404e2a8426d02/sql/distsql/data.proto#L111)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> remove TODO now?
</details>
Done.

---

*[sql/distsql/routers.go, line 45 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8426#-KOqpZCxKtPwH658A5p5:-KOqtaw5D03HajkY1e3d:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/711450859f5940a9b45a9b546961d6d28591941c/sql/distsql/routers.go#L45)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> maybe now's a good time to add a file-level comment about routers.
</details>
Done.

---

*[sql/distsql/routers.go, line 96 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8426#-KOqplMc43SNtdgAWe2a:-KOqsDVAz__2x7OQpduX:bpm83qc) ([raw file](https://github.com/cockroachdb/cockroach/blob/711450859f5940a9b45a9b546961d6d28591941c/sql/distsql/routers.go#L96)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> hmmm is it expected that a receiver from a hash router would say "no more rows"? Maybe that's an unexpected error?
</details>
I think any receiver can say that. It can definitely happen if something hits an error down the line in that stream, but it could be possible in non-error cases too - think of a distributed join with a limit where we are pushing the rows in the order needed by join. If we know we only need 100 results, we can set that limit on each node doing the join. Granted in most of these limit cases we probably won't want to distribute the join in the first place but who knows (maybe we have a very restrictive filter or something).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8426#-:-KOqtg3bQ5_Ri_6GO8dD:b-814g8k)*

**Pull request merged**
