### PR TITLE
ci: build and publish cockroach-sql

### LINKED ISSUE #75800: ci: build and publish `cockroach-sql` alongside the other release artifacts
We'd like to ship the small(er) `cockroach-sql` binary to our end-users.
For this it needs to be downloadable from our release buckets.
For this it needs to be built in CI.

So the request here is to update the rules in CI to build and publish the `cockroach-sql` binary (`bazel build //pkg/cmd/cockroach-sql` and `strip cockroach-sql`) alongside the other `cockroach` binary, for all the target platforms that we publish artifacts for.

Also it would be useful to run `strip` on the resulting binary, to reduce its size further. (but run strip just on cockroach-sql, not cockroach)

Jira issue: CRDB-12841

### PR DESCRIPTION
**Pull request by rail**
This patch adds `cockroach-sql` as a separate artifact published to S3.
The binary is not stripped (TBD).

Fixes #75800

Release note: None

### CODE REVIEW

**Comment by rail** [comment]
TBH, I'm not 100% happy with the implementation. I tried a few different approaches, but all of them require a lot of refactoring. I'd rather refactor the code as a separate task.

Stripping is not enabled, because it feels like it should be done in Bazel. I'm not sure if we can strip individual files yet.

**Review by rickystewart — APPROVED** [review]
LGTM. This binary could probably use another refactor as we add more functionality over time.

**Comment by rail** [comment]
bors r=rickystewart

**Comment by rail** [comment]
blathers backport release-22.1

**Pull request merged**
