### PR TITLE
sql: encode and decode sequence regclasses, and allow sequence renaming

### LINKED ISSUE #51090: sql: sequences created by `SERIAL` have weird semantics with regards to database
**Describe the problem**

When we create `SERIAL` types and we have `serial_normalization` set to `'sql_sequence'` we construct a new sequence. Unfortunately, the sequence we construct is in the current database rather than the database of the table. This leads to strange semantics where the table can only be written to if the current session is in the database of the sequence.

The problem here is that we use the session's database to resolve the sequence rather than the table's. In postgres, IIUC, the table's database and schema are used to resolve the sequence.

**To Reproduce**

```sql
root@localhost:26257/defaultdb> SET serial_normalization = 'sql_sequence';
SET

root@localhost:26257/defaultdb> CREATE DATABASE other_db;
CREATE DATABASE

root@localhost:26257/defaultdb> CREATE TABLE other_db.t (s SERIAL PRIMARY KEY, i INT);
CREATE TABLE

root@localhost:26257/defaultdb> INSERT INTO other_db.t (i) VALUES (1);
INSERT 1

root@localhost:26257/defaultdb> USE other_db;
SET

root@localhost:26257/other_db> INSERT INTO t (i) VALUES (2);
ERROR: nextval(): relation "t_s_seq" does not exist
SQLSTATE: 42P01
```

Even worse, if I create a sequence in that database with that name, it'll get used:

```sql
root@localhost:26257/other_db> CREATE SEQUENCE t_s_seq;
CREATE SEQUENCE

root@localhost:26257/other_db> INSERT INTO t (i) VALUES (2);
ERROR: duplicate key value (s)=(1) violates unique constraint "primary"
SQLSTATE: 23505
```

**Expected behavior**
The `SERIAL` column will work regardless of which database the current session is in. Furthermore, as we move to user-defined schemas, it should refer to a single sequence regardless of the current session's `search_path`.

### PR DESCRIPTION
**Pull request by the-ericwang35**
This patch builds upon https://github.com/cockroachdb/cockroach/pull/59396,
where we overloaded sequence operators to accept a regclass.
Now that sequence operators can accept a regclass,
this patch starts using this change by storing sequences
via their `ID::regclass`, updating back references to distinguish
between references via names and IDs, and then transforming
these IDs back to their fully qualified names for printing.
This patch also starts allowing sequences that are referenced only
via ID to be renamed.
Lastly, tests were added to demonstrate all of this new functionality.

Release note (sql change): encode and decode sequence regclasses,
and allow renaming sequences

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> Reviewed 1 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59864)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @the-ericwang35)

___
*[pkg/sql/catalog/schemaexpr/column.go, line 324 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59864#-MTEmFxR8VW8I4NL_Itl:-MTEmFxR8VW8I4NL_Itm:b-o88yqy) ([raw file](https://github.com/cockroachdb/cockroach/blob/14243f7dd0c08905d16204a322d42ab154e929f6/pkg/sql/catalog/schemaexpr/column.go#L324)):*
> ```Go
> 		// Swap out this node to use the qualified table name for the sequence.
> 		return false, &tree.AnnotateTypeExpr{
> 			Type:       types.String,
> ```

I think we want this to say regclass.

**Review by the-ericwang35 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59864)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/catalog/schemaexpr/column.go, line 324 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59864#-MTEmFxR8VW8I4NL_Itl:-MTGzHcz-V24lQ2r4oxx:b-3dqwj4) ([raw file](https://github.com/cockroachdb/cockroach/blob/14243f7dd0c08905d16204a322d42ab154e929f6/pkg/sql/catalog/schemaexpr/column.go#L324)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think we want this to say regclass. 
</blockquote></details>

Done, as discussed the formatting now looks something like `'test.public.seq':::STRING::REGCLASS`.

**Review by ajwerner — COMMENTED** [review]
Nice! Very close

> Reviewed 6 of 21 files at r1, 2 of 4 files at r2, 8 of 16 files at r3, 14 of 18 files at r4, 9 of 9 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59864#-:-MTiE_qw9wEFWShIvclt:beerqxb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @the-ericwang35)

___
*[pkg/ccl/backupccl/restore_planning.go, line 1052 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59864#-MTiEPC60LePh9eb0hF8:-MTiEPC60LePh9eb0hF9:b-z7keh5) ([raw file](https://github.com/cockroachdb/cockroach/blob/033cb2b1f0c89f26ccaaa285b1d6e7ed566f143e/pkg/ccl/backupccl/restore_planning.go#L1052)):*
> ```Go
> 				return err
> 			}
> 			*expr = newExpr
> ```

you can just do it right here in the same iteration loop. 
___
*[pkg/sql/rename_database.go, line 317 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59864#-MTi9v5C28x8LTjxuRde:-MTi9v5D0THyztpmDL57:b-7wxpzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/033cb2b1f0c89f26ccaaa285b1d6e7ed566f143e/pkg/sql/rename_database.go#L317)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 				// We only don't allow this if the database name is in there.
> 				// This is always the last argument.
> 				if tree.Name(parsedSeqName.Parts[parsedSeqName.NumParts-1]).Normalize() == tree.Name(dbName).Normalize() {
> 					return false, column.GetName(), nil
> 				}
> ```
</details>

This is pretty :facepalm: - I'm inclined to remove it but let's do it as a follow up. 
___
*[pkg/sql/sequence.go, line 607 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59864#-MTiAbEa1jQ9OYqNNc2R:-MTiAbEa1jQ9OYqNNc2S:b-t7jwyj) ([raw file](https://github.com/cockroachdb/cockroach/blob/033cb2b1f0c89f26ccaaa285b1d6e7ed566f143e/pkg/sql/sequence.go#L607)):*
> ```Go
> 
> 		var seqDesc *tabledesc.Mutable
> 		var err error
> ```

nit: lower the error checking out of this branch. 
___
*[pkg/sql/sequence.go, line 649 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59864#-MTiAohG2kp9--zkXO0w:-MTiAohG2kp9--zkXO0x:b3epk0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/033cb2b1f0c89f26ccaaa285b1d6e7ed566f143e/pkg/sql/sequence.go#L649)):*
> ```Go
> 	}
> 
> 	if len(seqIdentifiers) > 0 && byID {
> ```

This probably deserves some commentary explaining what's going on. 
___
*[pkg/sql/catalog/descpb/structured.proto, line 972 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59864#-MTiAtqj4zCIOXSIvMiG:-MTiAtqj4zCIOXSIvMiH:b61ff4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/033cb2b1f0c89f26ccaaa285b1d6e7ed566f143e/pkg/sql/catalog/descpb/structured.proto#L972)):*
> ```protobuf
>     repeated uint32 column_ids = 3 [(gogoproto.customname) = "ColumnIDs",
>              (gogoproto.casttype) = "ColumnID"];
>     // Indicates whether the relation is referenced via its name or its ID.
> ```

Maybe a bit more commentary about what it means for it to be referenced by name or by id. 
___
*[pkg/sql/catalog/schemaexpr/column.go, line 290 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59864#-MTiCRag1nCnzbTH0MHG:-MTiCRag1nCnzbTH0MHH:b-pt31kk) ([raw file](https://github.com/cockroachdb/cockroach/blob/033cb2b1f0c89f26ccaaa285b1d6e7ed566f143e/pkg/sql/catalog/schemaexpr/column.go#L290)):*
> ```Go
> 
> // replaceWithSequenceNames replaces occurrences of sequence regclasses in an expression with
> // the sequence's fully qualified names.
> ```

This deserves more commentary explaining what it actually does. 
___
*[pkg/sql/catalog/schemaexpr/column.go, line 291 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59864#-MTiB8bP1jCiyn_l2t_9:-MTiB8bP1jCiyn_l2t_A:boy7yco) ([raw file](https://github.com/cockroachdb/cockroach/blob/033cb2b1f0c89f26ccaaa285b1d6e7ed566f143e/pkg/sql/catalog/schemaexpr/column.go#L291)):*
> ```
> // replaceWithSequenceNames replaces occurrences of sequence regclasses in an expression with
> // the sequence's fully qualified names.
> func replaceWithSequenceNames(
> ```

There's nothing that makes this actually about sequences... If the expression were `8:::REGCLASS` it'd end up here, right? I think that's find and good but means that we should make these function names more generic. 
___
*[pkg/sql/schemachanger/scpb/scpb.proto, line 86 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59864#-MTiDS4e2qk1CpeLhmCf:-MTiDS4f7FsCcnTrC-g1:bcnkg64) ([raw file](https://github.com/cockroachdb/cockroach/blob/033cb2b1f0c89f26ccaaa285b1d6e7ed566f143e/pkg/sql/schemachanger/scpb/scpb.proto#L86)):*
> ```protobuf
>   uint32 sequence_id = 3 [(gogoproto.customname) = "SequenceID", (gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/sql/catalog/descpb.ID"];
>   Type type = 4;
>   bool by_id = 5 [(gogoproto.customname) = "ByID"];
> ```

commentary please
___
*[pkg/util/sequence/sequence.go, line 127 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59864#-MTiDuxV4TXM7DBDCN0S:-MTiDuxWEmps5X07mrm2:b-x3p5sm) ([raw file](https://github.com/cockroachdb/cockroach/blob/033cb2b1f0c89f26ccaaa285b1d6e7ed566f143e/pkg/util/sequence/sequence.go#L127)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> // ReplaceSequenceNamesWithIDs walks the given expression, and replaces
> // any sequence names in the expression by their IDs instead.
> // e.g. nextval('foo') => nextval(123::regclass)
> func ReplaceSequenceNamesWithIDs(
> 	defaultExpr tree.Expr, nameToID map[string]int64,
> ```
</details>



This feels very much like the sort of thing that could be easy to unit test. Honestly, so too could the other function in this package. I think it's worth it.

**Review by the-ericwang35 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59864)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/ccl/backupccl/restore_planning.go, line 1052 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59864#-MTiEPC60LePh9eb0hF8:-MTkkJ1yBuX95olMk3xa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/033cb2b1f0c89f26ccaaa285b1d6e7ed566f143e/pkg/ccl/backupccl/restore_planning.go#L1052)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

you can just do it right here in the same iteration loop. 
</blockquote></details>

Done.
___
*[pkg/sql/sequence.go, line 607 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59864#-MTiAbEa1jQ9OYqNNc2R:-MTkuRxV82ueS4QdVcmY:bz81tjq) ([raw file](https://github.com/cockroachdb/cockroach/blob/033cb2b1f0c89f26ccaaa285b1d6e7ed566f143e/pkg/sql/sequence.go#L607)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: lower the error checking out of this branch. 
</blockquote></details>

I realized declaring `err` is not even needed so I just removed it.
___
*[pkg/sql/sequence.go, line 649 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59864#-MTiAohG2kp9--zkXO0w:-MTkgloTB_b95Uz5Xb1k:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/033cb2b1f0c89f26ccaaa285b1d6e7ed566f143e/pkg/sql/sequence.go#L649)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This probably deserves some commentary explaining what's going on. 
</blockquote></details>

Done.
___
*[pkg/sql/catalog/descpb/structured.proto, line 972 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59864#-MTiAtqj4zCIOXSIvMiG:-MTkiFLg6joy4j5jkk5e:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/033cb2b1f0c89f26ccaaa285b1d6e7ed566f143e/pkg/sql/catalog/descpb/structured.proto#L972)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Maybe a bit more commentary about what it means for it to be referenced by name or by id. 
</blockquote></details>

Done.
___
*[pkg/sql/catalog/schemaexpr/column.go, line 290 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59864#-MTiCRag1nCnzbTH0MHG:-MTkispdEjxoxW-l6M1F:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/033cb2b1f0c89f26ccaaa285b1d6e7ed566f143e/pkg/sql/catalog/schemaexpr/column.go#L290)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This deserves more commentary explaining what it actually does. 
</blockquote></details>

Done.
___
*[pkg/sql/catalog/schemaexpr/column.go, line 291 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59864#-MTiB8bP1jCiyn_l2t_9:-MTkj2SL8Elrqqxa9NMM:b-ldrohe) ([raw file](https://github.com/cockroachdb/cockroach/blob/033cb2b1f0c89f26ccaaa285b1d6e7ed566f143e/pkg/sql/catalog/schemaexpr/column.go#L291)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> // replaceWithSequenceNames replaces occurrences of sequence regclasses in an expression with
> // the sequence's fully qualified names.
> func replaceWithSequenceNames(
> ```

There's nothing that makes this actually about sequences... If the expression were `8:::REGCLASS` it'd end up here, right? I think that's find and good but means that we should make these function names more generic. 
</blockquote></details>

Yep that's a good point, renamed to `replaceIDsWithFQNames`
___
*[pkg/sql/schemachanger/scpb/scpb.proto, line 86 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59864#-MTiDS4e2qk1CpeLhmCf:-MTkjd8q7a5D0q__yEj-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/033cb2b1f0c89f26ccaaa285b1d6e7ed566f143e/pkg/sql/schemachanger/scpb/scpb.proto#L86)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

commentary please
</blockquote></details>

Done.
___
*[pkg/util/sequence/sequence.go, line 127 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59864#-MTiDuxV4TXM7DBDCN0S:-MTlo81bEzCFTa2AktaH:b-y8c1to) ([raw file](https://github.com/cockroachdb/cockroach/blob/033cb2b1f0c89f26ccaaa285b1d6e7ed566f143e/pkg/util/sequence/sequence.go#L127)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> // ReplaceSequenceNamesWithIDs walks the given expression, and replaces
> // any sequence names in the expression by their IDs instead.
> // e.g. nextval('foo') => nextval(123::regclass)
> func ReplaceSequenceNamesWithIDs(
> 	defaultExpr tree.Expr, nameToID map[string]int64,
> ```


This feels very much like the sort of thing that could be easy to unit test. Honestly, so too could the other function in this package. I think it's worth it. 
</blockquote></details>

Yep, I added some basic tests for all of the functions in this file in a new test file `sequence_test.go`,  I can add more later if needed.

**Review by ajwerner — APPROVED** [review]
Just the typo nit, then bors it!

:lgtm: 

> Reviewed 1 of 31 files at r10, 4 of 16 files at r11, 9 of 18 files at r12, 20 of 20 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59864#-:-MTnGbYj2y3Mg9ZhM7Ng:b-6gydhg)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/schemachanger/scpb/scpb.proto, line 86 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59864#-MTiDS4e2qk1CpeLhmCf:-MTnG5UB4pjmNWxRSqcJ:b-npm72u) ([raw file](https://github.com/cockroachdb/cockroach/blob/033cb2b1f0c89f26ccaaa285b1d6e7ed566f143e/pkg/sql/schemachanger/scpb/scpb.proto#L86)):*
<details><summary><i>Previously, the-ericwang35 (Eric Wang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

seqiemce

nit: start this with `ByID`

**Review by the-ericwang35 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59864)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

___
*[pkg/sql/schemachanger/scpb/scpb.proto, line 86 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59864#-MTiDS4e2qk1CpeLhmCf:-MTpjJ8Q6RtYkb0b8BLK:b-pbe9m1) ([raw file](https://github.com/cockroachdb/cockroach/blob/033cb2b1f0c89f26ccaaa285b1d6e7ed566f143e/pkg/sql/schemachanger/scpb/scpb.proto#L86)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

seqiemce

nit: start this with `ByID`
</blockquote></details>

Wow that spelling was not even close, fixed.

**Comment by the-ericwang35** [comment]
TFTR!

bors r+

**Pull request merged**
