### PR TITLE
sql: Add observability when schema change jobs are blocked by concurrent ones

### LINKED ISSUE #103733: sql: log when a schema job is blocking another schema job
Currently, it is difficult to tell if a schema change job gets stuck due to another schema change job. Having improved logging around this would help troubleshooting this much easier. Logging should at the very least include the job ID causing a particular schema change to get stuck with a clear message stating that it is being blocked.

Currently it is impossible to know what job is causing another job from progressing, unless we dig through logs and run queries to find this out, and many times, if the logs had already been rotated or for some reason we can’t access the jobs table, this information is not available. 

Take these stuck schema changes for example:
```
I230428 12:41:32.930025 7861 sql/schema_changer.go:614 ⋮ [n1,job=860526600554774529,scExec,id=229,mutation=6] 1246  schema change on ‹"transactions"› (v17): another change is still in progress
W230428 12:41:32.930418 7861 sql/schema_changer.go:2675 ⋮ [n1,job=860526600554774529] 1247  error while running schema change, retrying: schema change not first in line

I230428 12:40:56.947226 70388 sql/schema_changer.go:614 ⋮ [n1,job=860535423786385409,scExec,id=229,mutation=7] 1234  schema change on ‹"transactions"› (v17): another change is still in progress
W230428 12:40:56.947471 70388 sql/schema_changer.go:2675 ⋮ [n1,job=860535423786385409] 1235  error while running schema change, retrying: schema change not first in line

I230428 12:40:57.689804 4160 sql/schema_changer.go:614 ⋮ [n1,job=860497952732938241,scExec,id=229,mutation=5] 1236  schema change on ‹"transactions"› (v17): another change is still in progress
W230428 12:40:57.689925 4160 sql/schema_changer.go:2675 ⋮ [n1,job=860497952732938241] 1237  error while running schema change, retrying: schema change not first in line
```

All jobs above are stuck waiting on another job. What job is this? CRDB knows it is waiting on a job, so why not log the job it is waiting on? Please fix this so the job that is causing these jobs above to be stuck is displayed. A message like the example below would be much more helpful:
```
[n1,job=860535423786385409,scExec,id=229,mutation=7] 1162 schema change on ‹“transactions”› (v17): job #123456789 is still in progress and it is blocking this job from proceeding
```

Other have ran into this and you can see how cumbersome it is to troubleshoot this issue just because the logs do not have all the information:

https://cockroachlabs.slack.com/archives/CHVV403F0/p1661168600431089 

As a bonus point, it would be great if this information was also displayed in the DB Console, so users can see what job id is holding up another job id from progressing.

Jira issue: CRDB-28163

Epic CRDB-27756

### PR DESCRIPTION
**Pull request by Xiang-Gu**
Previously, when using legacy schema changes, concurrent schema changes will wait for preceding ones if it's not first in line but we didn't provide the blocking schema change job ID in the log nor error. This is inadequate in debugging and troubling shooting support ticket. This commit fixes that by providing the blocking schema change job ID if this happens.

Fix #103733
Release note (sql): When there are concurrent legacy schema change jobs, we will be able to know what the blocking schema change job ID is from the relevant log entries.

### CODE REVIEW

**Review by fqazi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107504)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Xiang-Gu)

___
*[`pkg/sql/schema_changer.go` line 616 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107504#-NaCXlne6b5h0iVEDiF5:-NaCXlne6b5h0iVEDiF6:b-pnhb05) ([raw file](https://github.com/cockroachdb/cockroach/blob/c27f616b95c3e3131e0c0c2d931864c051ec4309/pkg/sql/schema_changer.go#L616)):*
> ```Go
> 	}
> 	if jobID == catpb.InvalidJobID {
> 		panic(fmt.Sprintf("mutation job with mutation ID %v is not found in table %q",
> ```

Safer to return an error here, since I don't know if anything will catch the panic?
___
*[`pkg/sql/sqlerrors/errors.go` line 359 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107504#-NaCVJrP00RETEUZyzwy:-NaCVJrP00RETEUZyzwz:b-wrepop) ([raw file](https://github.com/cockroachdb/cockroach/blob/c27f616b95c3e3131e0c0c2d931864c051ec4309/pkg/sql/sqlerrors/errors.go#L359)):*
> ```Go
> }
> 
> func NewErrSchemaChangeNotFirstInLine(blockingJobID catpb.JobID) error {
> ```

Do we want this to be its own error type? Just something to think about in terms of other uses for this job ID.
___
*[`pkg/sql/schema_changer_test.go` line 8416 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107504#-NaCXBCv4ccqFb0yOsm5:-NaCXBCv4ccqFb0yOsm6:b-a7xxs6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c27f616b95c3e3131e0c0c2d931864c051ec4309/pkg/sql/schema_changer_test.go#L8416)):*
> ```Go
> 	jobID1 := pattern.FindString(err.Error())
> 	require.NotEmpty(t, jobID1)
> 	_, err = sqlDB.Exec(`ALTER TABLE t ADD COLUMN j INT DEFAULT 30;`)
> ```

Does this overlap with: TestSchemaChangeWaitsForOtherSchemaChanges?

**Review by rafiss — CHANGES_REQUESTED** [review]
nice! so just to check, the declarative schema changer already logs the blocking job ID?

added backport labels, since the goal is to make debugging existing clusters more easy

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107504#-:-NaCXv603sHNxg4RZEJz:b-b5uavj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @Xiang-Gu)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107504#-NaCXzpP7hDnuelxrPbw):*
nit: this is not a `sql` release note - there is no way to for anyone to interact with the logs using sql.

it would make sense as no release note, or as the `ops change` category.

my preference is no release note, since the intended usage of this change is just when debugging, not something anyone needs to proactively look for.
___
*[`pkg/sql/schema_changer.go` line 237 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107504#-NaCYbMt9FIDvpId_3Qo:-NaCYbMt9FIDvpId_3Qp:b-pugjfx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c27f616b95c3e3131e0c0c2d931864c051ec4309/pkg/sql/schema_changer.go#L237)):*
> ```Go
> 	}
> 
> 	if strings.Contains(err.Error(), "schema change is not first in line") {
> ```

this is not a recommended way of checking an error. error messages should not be considered stable - a future change could change the text, and the person making that change would never know to update this if statement.

see: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/1676804870/Error+concepts+and+handling+in+CockroachDB#Error-concepts

why did this need to change?
___
*[`pkg/sql/schema_changer.go` line 616 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107504#-NaCXlne6b5h0iVEDiF5:-NaCZfHR-ffJO3b_MaEH:b-3scw5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/c27f616b95c3e3131e0c0c2d931864c051ec4309/pkg/sql/schema_changer.go#L616)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Safer to return an error here, since I don't know if anything will catch the panic?
</blockquote></details>

+1 keep in mind the legacy schema changer does not do panic handling
___
*[`pkg/sql/sqlerrors/errors.go` line 359 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107504#-NaCVJrP00RETEUZyzwy:-NaCZ99Z6lfXwkn9fLMq:buzlisl) ([raw file](https://github.com/cockroachdb/cockroach/blob/c27f616b95c3e3131e0c0c2d931864c051ec4309/pkg/sql/sqlerrors/errors.go#L359)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Do we want this to be its own error type? Just something to think about in terms of other uses for this job ID.
</blockquote></details>

+1, let's keep the old error constant and use:
```
return errors.Wrapf(
  errSchemaChangeNotFirstInLine,
  "schema change is blocked by another schema change job %v,
  blockingJobID,
)
```

or i am also open to adding a new error type, if that feels more natural to you

**Review by Xiang-Gu — COMMENTED** [review]
Thanks for the feedback. I've addressed all of them and please take a look again. Thank you!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107504#-:-NaE6msHDbTfYBky8ljS:b-3mmso1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @rafiss)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107504#-NaCXzpP7hDnuelxrPbw):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: this is not a `sql` release note - there is no way to for anyone to interact with the logs using sql.

it would make sense as no release note, or as the `ops change` category.

my preference is no release note, since the intended usage of this change is just when debugging, not something anyone needs to proactively look for.
</blockquote></details>

done
___
*[`pkg/sql/schema_changer.go` line 237 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107504#-NaCYbMt9FIDvpId_3Qo:-NaE5frN68kEY6E5pf6y:b-h0jii0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c27f616b95c3e3131e0c0c2d931864c051ec4309/pkg/sql/schema_changer.go#L237)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this is not a recommended way of checking an error. error messages should not be considered stable - a future change could change the text, and the person making that change would never know to update this if statement.

see: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/1676804870/Error+concepts+and+handling+in+CockroachDB#Error-concepts

why did this need to change?
</blockquote></details>

done. I have reverted this part of changes and just wrap on top of the original error.
___
*[`pkg/sql/schema_changer.go` line 616 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107504#-NaCXlne6b5h0iVEDiF5:-NaE62sG0fwhk6PiVmz-:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c27f616b95c3e3131e0c0c2d931864c051ec4309/pkg/sql/schema_changer.go#L616)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

+1 keep in mind the legacy schema changer does not do panic handling
</blockquote></details>

done
___
*[`pkg/sql/schema_changer_test.go` line 8416 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107504#-NaCXBCv4ccqFb0yOsm5:-NaDdp-gCxHbHjXylTw9:bpe1zgp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c27f616b95c3e3131e0c0c2d931864c051ec4309/pkg/sql/schema_changer_test.go#L8416)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Does this overlap with: TestSchemaChangeWaitsForOtherSchemaChanges?
</blockquote></details>

my understanding is TestSchemaChangeWaitsForOtherSchemaChanges is testing how declarative schema changer behave when there is concurrent schema change (legacy or declarative). It's hence in package `sql/schemachanger`.

This test is about legacy + legacy code path, where the waiting occurred in a different place than the ones above.
___
*[`pkg/sql/sqlerrors/errors.go` line 359 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107504#-NaCVJrP00RETEUZyzwy:-NaDdVaZ1JZ9o3UD3BsN:b-o0blvp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c27f616b95c3e3131e0c0c2d931864c051ec4309/pkg/sql/sqlerrors/errors.go#L359)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

+1, let's keep the old error constant and use:
```
return errors.Wrapf(
  errSchemaChangeNotFirstInLine,
  "schema change is blocked by another schema change job %v,
  blockingJobID,
)
```

or i am also open to adding a new error type, if that feels more natural to you
</blockquote></details>

done. I chose to just wrap a layer with the blocking job ID on top.

**Review by fqazi — APPROVED** [review]
:lgtm: Great work!

> Reviewed 13 of 13 files at r2, 2 of 4 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107504#-:-NaHzVOa3yxZ49Swnl5M:bolbkdq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss)

**Comment by Xiang-Gu** [comment]
TFTR!

bors r+

**Review by rafiss — APPROVED** [review]
nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107504#-:-NaIm0Z68AkN564Q4YsZ:b-j4xmku)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @fqazi)

**Comment by Xiang-Gu** [comment]
TFTR!

bors r+

**Pull request merged**
