### PR TITLE
perf: shard LeaseHolderCache

### LINKED ISSUE #17388: perf: reduce LeaseHolderCache memory usage
#17202 was a non-starter because the `UnorderedCache` used internally by `LeaseHolderCache` updates an LRU list on every access. `LeaseHolderCache` is accessed on every RPC putting it in the critical path. Rather than a single `UnorderedCache`, we could shard `LeaseHolderCache` based on the range ID, providing a lock per shard. This would be relatively straightforward.

While we're mucking in this code, we might want to trim down the data stored by `LeaseHolderCache`. Currently it caches a `ReplicaDescriptor`, but only `ReplicaDescriptor.StoreID` is needed.

### PR DESCRIPTION
**Pull request by a6802739**
Fixes #17388. @petermattis.

I didn't trim down the data stored by LeaseHolderCache in this PR, I will try to fix this in another PR.

here is the benchmark test result for this PR:

```
before:
BenchmarkLeaseHolderCacheParallel-4   	  100000	     16587 ns/op
BenchmarkLeaseHolderCacheParallel-4   	  100000	     16618 ns/op
BenchmarkLeaseHolderCacheParallel-4   	  100000	     16684 ns/op
BenchmarkLeaseHolderCacheParallel-4   	  100000	     16589 ns/op
BenchmarkLeaseHolderCacheParallel-4   	  100000	     16416 ns/op

after:
BenchmarkLeaseHolderCacheParallel-4   	  200000	      7885 ns/op
BenchmarkLeaseHolderCacheParallel-4   	  200000	      9135 ns/op
BenchmarkLeaseHolderCacheParallel-4   	  100000	     10293 ns/op
BenchmarkLeaseHolderCacheParallel-4   	  200000	      9278 ns/op
BenchmarkLeaseHolderCacheParallel-4   	  200000	      7868 ns/op
```

### CODE REVIEW

**Comment by petermattis** [comment]
Approach, generally looks good, just a few small items below.

For comparing benchmarks, use [benchstat](https://godoc.org/golang.org/x/perf/cmd/benchstat). 

---

Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/kv/leaseholder_cache.go, line 27 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17987#-KsiM7hVcJoLOJqGMx2m:-KsiM7hVcJoLOJqGMx2n:bsmej5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff2426f7968aaabf72c163ba682536d9a00b743a/pkg/kv/leaseholder_cache.go#L27)):*
> ```Go
> 
> const (
> 	leaseHolderCacheShards = 16
> ```

I wonder if this should be a function of the number of cpus. 

---

*[pkg/kv/leaseholder_cache.go, line 53 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17987#-KsiLseEDZcwJsxgCkVN:-KsiLseEDZcwJsxgCkVO:betlu6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff2426f7968aaabf72c163ba682536d9a00b743a/pkg/kv/leaseholder_cache.go#L53)):*
> ```Go
> 			Policy: cache.CacheLRU,
> 			ShouldEvict: func(s int, key, value interface{}) bool {
> 				return int64(s) > size()
> ```

I think this should be `int64(s) > size()/int64(len(leaseholderCache.shards)))`. As it is currently you've made the total leaseholder cache size 16x larger. 

---

*[pkg/kv/leaseholder_cache.go, line 90 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17987#-KsiMEYoikIbkGVnkLXb:-KsiMEYoikIbkGVnkLXc:bm06u37) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff2426f7968aaabf72c163ba682536d9a00b743a/pkg/kv/leaseholder_cache.go#L90)):*
> ```Go
> 	if (repDesc == roachpb.ReplicaDescriptor{}) {
> 		if log.V(2) {
> 			log.Infof(ctx, "evicting lease holder for r%d", rangeID)
> ```

Is there a reason for this change? We generally prefix the range ID on log messages and this is now inconsistent with other log messages in this file. Also, `leaseholder` is one word. 

---

*[pkg/kv/leaseholder_cache_test.go, line 81 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17987#-KsiMJ6a4EKqjAWE94cV:-KsiMJ6a4EKqjAWE94cW:b-cbeajs) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff2426f7968aaabf72c163ba682536d9a00b743a/pkg/kv/leaseholder_cache_test.go#L81)):*
> ```Go
> 	b.RunParallel(func(pb *testing.PB) {
> 		for pb.Next() {
> 			for i := 1; i < 1<<6; i++ {
> ```

Idiomatic benchmarks execute a single iteration in the loop. I suggest doing something like:

```
  const numRanges = 1<<6
  ...
  var n int64
  for pb.Next() {
    rangeID := roachpb.RangeID(n % numRanges)
    n++
    if _, ok := lc.Lookup(ctx, rangeID); !ok {
      ...
    }
  }
```

---

*[pkg/kv/leaseholder_cache_test.go, line 83 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17987#-KsiMfT8WfQKz3mih1nW:-KsiMfT8WfQKz3mih1nX:b-mylyqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff2426f7968aaabf72c163ba682536d9a00b743a/pkg/kv/leaseholder_cache_test.go#L83)):*
> ```Go
> 			for i := 1; i < 1<<6; i++ {
> 				rangeID := roachpb.RangeID(i)
> 				replica := roachpb.ReplicaDescriptor{StoreID: roachpb.StoreID(i)}
> ```

This is only being used for logging. I'd get rid of it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17987#-:-KsiLhvK39BUR9OciSH9:b-p2xy4)*

**Comment by bdarnell** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/kv/leaseholder_cache.go, line 90 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17987#-KsiMEYoikIbkGVnkLXb:-KsiQTaJpxHuCvUFO3OE:b-4e20yb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff2426f7968aaabf72c163ba682536d9a00b743a/pkg/kv/leaseholder_cache.go#L90)):*
> Also, leaseholder is one word.

But we capitalize the H in the type name `LeaseHolderCache` as if it were two words. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17987)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/kv/leaseholder_cache.go, line 90 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17987#-KsiMEYoikIbkGVnkLXb:-KsiU-oZpx0f_hTBXcpR:b-qe50w8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff2426f7968aaabf72c163ba682536d9a00b743a/pkg/kv/leaseholder_cache.go#L90)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

> Also, leaseholder is one word.

But we capitalize the H in the type name `LeaseHolderCache` as if it were two words. 
</blockquote></details>

Yeah, we should fix that. I'm pretty sure we've standardized on `leaseholder` and `Leaseholder` elsewhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17987)*

**Comment by a6802739** [comment]
here is the result :
```
before:
BenchmarkLeaseHolderCacheParallel-4      5000000               279 ns/op
BenchmarkLeaseHolderCacheParallel-4      5000000               297 ns/op
BenchmarkLeaseHolderCacheParallel-4      5000000               287 ns/op
BenchmarkLeaseHolderCacheParallel-4      5000000               284 ns/op
BenchmarkLeaseHolderCacheParallel-4      5000000               292 ns/op

after:
BenchmarkLeaseHolderCacheParallel-4     10000000               175 ns/op
BenchmarkLeaseHolderCacheParallel-4     10000000               169 ns/op
BenchmarkLeaseHolderCacheParallel-4     10000000               172 ns/op
BenchmarkLeaseHolderCacheParallel-4     10000000               190 ns/op
BenchmarkLeaseHolderCacheParallel-4     10000000               176 ns/op
```


here is the `benchstat` result:
```
name                        old time/op  new time/op  delta
LeaseHolderCacheParallel-4   288ns ± 3%   176ns ± 8%  -38.71%  (p=0.008 n=5+5)
```

---

Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/kv/leaseholder_cache.go, line 27 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17987#-KsiM7hVcJoLOJqGMx2m:-Ksr7bWlDSYEB-do6Hs6:b30r698) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff2426f7968aaabf72c163ba682536d9a00b743a/pkg/kv/leaseholder_cache.go#L27)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I wonder if this should be a function of the number of cpus. 
</blockquote></details>

I have done this now. But I'm not sure it is appropriate.

---

*[pkg/kv/leaseholder_cache.go, line 53 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17987#-KsiLseEDZcwJsxgCkVN:-KsqyvIFUPAf9fZkGDoI:b7j0jo8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff2426f7968aaabf72c163ba682536d9a00b743a/pkg/kv/leaseholder_cache.go#L53)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think this should be `int64(s) > size()/int64(len(leaseholderCache.shards)))`. As it is currently you've made the total leaseholder cache size 16x larger. 
</blockquote></details>

Yeah, My mistake.

---

*[pkg/kv/leaseholder_cache.go, line 90 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17987#-KsiMEYoikIbkGVnkLXb:-Ksr8E2sO--fhhfs41h_:bsdcgy6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff2426f7968aaabf72c163ba682536d9a00b743a/pkg/kv/leaseholder_cache.go#L90)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Yeah, we should fix that. I'm pretty sure we've standardized on `leaseholder` and `Leaseholder` elsewhere.
</blockquote></details>

Because my branch is far behind the master branch. Fixed it now.

---

*[pkg/kv/leaseholder_cache_test.go, line 81 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17987#-KsiMJ6a4EKqjAWE94cV:-Ksr8UxmIpUMj4m4F9_1:boyexbg) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff2426f7968aaabf72c163ba682536d9a00b743a/pkg/kv/leaseholder_cache_test.go#L81)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Idiomatic benchmarks execute a single iteration in the loop. I suggest doing something like:

```
  const numRanges = 1<<6
  ...
  var n int64
  for pb.Next() {
    rangeID := roachpb.RangeID(n % numRanges)
    n++
    if _, ok := lc.Lookup(ctx, rangeID); !ok {
      ...
    }
  }
```
</blockquote></details>

Done. Thanks.

---

*[pkg/kv/leaseholder_cache_test.go, line 83 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17987#-KsiMfT8WfQKz3mih1nW:-Ksr8c-TTPxZSpmn6pob:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff2426f7968aaabf72c163ba682536d9a00b743a/pkg/kv/leaseholder_cache_test.go#L83)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This is only being used for logging. I'd get rid of it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17987#-:-Ksr8d8V5TmiE39r7s0Q:brvuor)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/kv/leaseholder_cache.go, line 33 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17987#-Ksru2iFWGkpl1S61sKS:-Ksru2iFWGkpl1S61sKT:b-6690dk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7327e9d3a813c884800498f3e9ca41dbb02d20c3/pkg/kv/leaseholder_cache.go#L33)):*
> ```Go
> 
> var (
> 	defaultShards = staticShards(defaultFactor)
> ```

This can be `defaultFactor * runtime.NumCPU()`.

On a style note, adding a constant for `defaultFactor` that is only used once doesn't add clarity (for me). I'd prefer `2 * runtime.NumCPU()`.

---

*[pkg/kv/leaseholder_cache.go, line 75 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17987#-KsruP1VZqPzg2qGbMTk:-KsruP1VZqPzg2qGbMTl:btc7cy4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7327e9d3a813c884800498f3e9ca41dbb02d20c3/pkg/kv/leaseholder_cache.go#L75)):*
> ```Go
> 	ctx context.Context, rangeID roachpb.RangeID,
> ) (roachpb.ReplicaDescriptor, bool) {
> 	ld := &lc.shards[int(rangeID)%defaultShards]
> ```

`s/defaultShards/len(lc.shards)/g`. Outside of the constructor, you should avoid using `defaultShards`.

---

*[pkg/kv/leaseholder_cache.go, line 96 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17987#-KsruUPOvn1CKKRLZxVt:-KsruUPOvn1CKKRLZxVu:b-by9q0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/7327e9d3a813c884800498f3e9ca41dbb02d20c3/pkg/kv/leaseholder_cache.go#L96)):*
> ```Go
> 	ctx context.Context, rangeID roachpb.RangeID, repDesc roachpb.ReplicaDescriptor,
> ) {
> 	ld := &lc.shards[int(rangeID)%defaultShards]
> ```

See other comment.

---

*[pkg/kv/leaseholder_cache_test.go, line 35 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17987#-Ksrua0fRYn-ZfCHP1YU:-Ksrua0fRYn-ZfCHP1YV:b9bjv68) ([raw file](https://github.com/cockroachdb/cockroach/blob/7327e9d3a813c884800498f3e9ca41dbb02d20c3/pkg/kv/leaseholder_cache_test.go#L35)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 	ctx := context.TODO()
> 	numRanges := 2 * staticShards(defaultFactor)
> ```

Rather that accessing `staticShards` here, I'd move this down a line and change it to: `numRanges := 2 * len(lc.shards)`. Either way you're making some assumption about the implementation of leaseholder cache, and the latter way seems more explicit. 

---

*[pkg/kv/leaseholder_cache_test.go, line 73 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17987#-KsrurTnN1I9yDKFf3w-:-KsrurTnN1I9yDKFf3w0:b-ul9d37) ([raw file](https://github.com/cockroachdb/cockroach/blob/7327e9d3a813c884800498f3e9ca41dbb02d20c3/pkg/kv/leaseholder_cache_test.go#L73)):*
> ```Go
> 	defer leaktest.AfterTest(b)()
> 	ctx := context.TODO()
> 	numRanges := 5 * staticShards(defaultFactor)
> ```

Similar to my comment above: `numRanges := 5 * len(lc.shards)`

---

*[pkg/kv/leaseholder_cache_test.go, line 84 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17987#-Ksrv03Z_CoiKpCMeH-q:-Ksrv03Z_CoiKpCMeH-r:b-55bcwl) ([raw file](https://github.com/cockroachdb/cockroach/blob/7327e9d3a813c884800498f3e9ca41dbb02d20c3/pkg/kv/leaseholder_cache_test.go#L84)):*
> ```Go
> 		for pb.Next() {
> 			rangeID := roachpb.RangeID(n%numRanges + 1)
> 			n++
> ```

`n` is being shared by multiple goroutines. Either move its definition inside the `b.RunParallel` or increment it using atomics. My original suggestion was for it to live inside `b.RunParallel`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17987)*

**Comment by a6802739** [comment]
@petermattis 

here is the newest result:

```
before:
before:
BenchmarkLeaseHolderCacheParallel-4      5000000               277 ns/op
BenchmarkLeaseHolderCacheParallel-4      5000000               275 ns/op
BenchmarkLeaseHolderCacheParallel-4      5000000               273 ns/op
BenchmarkLeaseHolderCacheParallel-4      5000000               276 ns/op
BenchmarkLeaseHolderCacheParallel-4      5000000               281 ns/op

after:
after:
BenchmarkLeaseHolderCacheParallel-4     10000000               121 ns/op
BenchmarkLeaseHolderCacheParallel-4     10000000               142 ns/op
BenchmarkLeaseHolderCacheParallel-4     10000000               158 ns/op
BenchmarkLeaseHolderCacheParallel-4     10000000               152 ns/op
BenchmarkLeaseHolderCacheParallel-4     10000000               129 ns/op

name                        old time/op  new time/op  delta
LeaseHolderCacheParallel-4   276ns ± 2%   140ns ±14%  -49.20%  (p=0.008 n=5+5)
```

I don't quite understand    `Rather that accessing staticShards here, I'd move this down a line and change it to: numRanges := 2 * len(lc.shards). Either way you're making some assumption about the implementation of leaseholder cache, and the latter way seems more explicit.`

Thanks for your kind review.

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/kv/leaseholder_cache_test.go, line 35 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17987#-Ksrua0fRYn-ZfCHP1YU:-KtCJLE_hg6YJNfjpEre:bhfau0p) ([raw file](https://github.com/cockroachdb/cockroach/blob/7327e9d3a813c884800498f3e9ca41dbb02d20c3/pkg/kv/leaseholder_cache_test.go#L35)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Rather that accessing `staticShards` here, I'd move this down a line and change it to: `numRanges := 2 * len(lc.shards)`. Either way you're making some assumption about the implementation of leaseholder cache, and the latter way seems more explicit. 
</blockquote></details>

The point was to avoid using `staticShards` and instead rely on `len(lc.shards)`. The current code looks fine. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17987#-:-KtCJAsviSKxxSx4qtq_:bnfp4nl)*

**Comment by a6802739** [comment]
@petermattis, Thank you very much. So could I merge this now?

**Comment by petermattis** [comment]
@a6802739 Yes, merge away!

**Pull request merged**
