### PR TITLE
misc cleanup

### PR DESCRIPTION
**Pull request by tamird**
cc @petermattis @cuongdo

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5675)

### CODE REVIEW

**Comment by petermattis** [comment]
Looks like the commit history has some churn, but the end result looks fine.

:lgtm:

---

Reviewed 5 of 5 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: 2 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/engine/mvcc.go, line 835 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5675#-KE2jOo4yjeTZ7RjwsGU:-KE2jOo4yjeTZ7RjwsGV:504638257) ([raw file](https://github.com/cockroachdb/cockroach/blob/331d9c95536152348cc311f73d059f6355d125ae/storage/engine/mvcc.go#L835)):*
What's with the churn?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5675#-:-KE2jhhtY1cEB8h7Sgb3:1220813548)*

**Comment by tamird** [comment]
Review status: 2 of 6 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/engine/mvcc.go, line 835 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5675#-KE2jOo4yjeTZ7RjwsGU:-KE2kCuSwZJsdVGR2_Eg:131886627) ([raw file](https://github.com/cockroachdb/cockroach/blob/331d9c95536152348cc311f73d059f6355d125ae/storage/engine/mvcc.go#L835)):*
Not sure what you mean. Reviewable might be messing with you?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5675)*

**Comment by petermattis** [comment]
Review status: 2 of 6 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/engine/mvcc.go, line 835 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5675#-KE2jOo4yjeTZ7RjwsGU:-KE2ksFNK0we_o-B6BXk:-1180335154) ([raw file](https://github.com/cockroachdb/cockroach/blob/331d9c95536152348cc311f73d059f6355d125ae/storage/engine/mvcc.go#L835)):*
Yep, reviewable has the diffs between commits horked up. It makes it appear that you performed a changed, revert it and then added it back.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5675)*

**Comment by tamird** [comment]
Review status: 2 of 6 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/engine/mvcc.go, line 835 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5675#-KE2jOo4yjeTZ7RjwsGU:-KE2lHu0GpHBjmYTBgwV:-177174850) ([raw file](https://github.com/cockroachdb/cockroach/blob/331d9c95536152348cc311f73d059f6355d125ae/storage/engine/mvcc.go#L835)):*
#rebaselife

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5675)*

**Pull request merged**
