### PR TITLE
hlc: improve/fix the representation of timestamps

### PR DESCRIPTION
**Pull request by knz**
Requested by @petermattis in https://github.com/cockroachdb/cockroach/pull/42250#pullrequestreview-332593782
Informs #43183.

Previously, a negative timestamp would be printed with a negative sign
in the middle, for example `0.-000000123` or `-123.-00000456`.
This patch fixes this by only emitting the sign once.

Additionally, this patch simplifies zero timestamps to just `"0"`.

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 30 of 30 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43185)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @petermattis)

___
*[pkg/util/hlc/timestamp.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43185#-LwEg6-QEIDhQx5LQ95E:-LwEg6-QEIDhQx5LQ95F:b-n0gff8) ([raw file](https://github.com/cockroachdb/cockroach/blob/54bf60fe4e8c41bf190219343f6230ce1f14a2d0/pkg/util/hlc/timestamp.go#L42)):*
> ```Go
> 	// The main problem with the original code was that it would put
> 	// a negative sign in the middle (after the decimal point) if
> 	// the value happened to be negative.
> ```

When do we see negative timestamps in practice?
___
*[pkg/util/hlc/timestamp.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43185#-LwEgWQkELIjvmEsfqQ5:-LwEgWQkELIjvmEsfqQ6:bhidgua) ([raw file](https://github.com/cockroachdb/cockroach/blob/54bf60fe4e8c41bf190219343f6230ce1f14a2d0/pkg/util/hlc/timestamp.go#L57)):*
> ```Go
> 		// expressed in nanoseconds
> 		timeS := strconv.FormatUint(u, 10)
> 		if len(timeS) < 10 {
> ```

Can we detect this condition ahead of time so that we can use `strconv.AppendUint` and avoid the intermediate buffer?
___
*[pkg/util/hlc/timestamp.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43185#-LwEfo4vBVlkpi_1Dw-U:-LwEfo4vBVlkpi_1Dw-V:byq7d9z) ([raw file](https://github.com/cockroachdb/cockroach/blob/54bf60fe4e8c41bf190219343f6230ce1f14a2d0/pkg/util/hlc/timestamp.go#L88)):*
> ```Go
> 	buf = strconv.AppendInt(buf, int64(t.Logical), 10)
> 	// Convert the byte array to a string without a copy. We follow the
> 	// examples of strings.Builder here.
> ```

Could we use `strings.Builder` with an initial `.Grow(12)` to avoid needing to have any unsafe code here?
___
*[pkg/util/hlc/timestamp_test.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43185#-LwEgsQ67SCcVghaY0W-:-LwEgsQ67SCcVghaY0W0:b-n5ijsb) ([raw file](https://github.com/cockroachdb/cockroach/blob/54bf60fe4e8c41bf190219343f6230ce1f14a2d0/pkg/util/hlc/timestamp_test.go#L111)):*
> ```Go
> 		exp string
> 	}{
> 		{makeTS(0, 0), "0,0"},
> ```

Some of these cases should probably have non-zero logical components.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43185)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @petermattis)

___
*[pkg/util/hlc/timestamp.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43185#-LwEg6-QEIDhQx5LQ95E:-LwEhs-l3ju4TVxwESf_:b8gfytf) ([raw file](https://github.com/cockroachdb/cockroach/blob/54bf60fe4e8c41bf190219343f6230ce1f14a2d0/pkg/util/hlc/timestamp.go#L42)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

When do we see negative timestamps in practice?
</blockquote></details>

In tests.
___
*[pkg/util/hlc/timestamp.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43185#-LwEgWQkELIjvmEsfqQ5:-LwEilEB2kuHyE51GBwK:b-h1difs) ([raw file](https://github.com/cockroachdb/cockroach/blob/54bf60fe4e8c41bf190219343f6230ce1f14a2d0/pkg/util/hlc/timestamp.go#L57)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we detect this condition ahead of time so that we can use `strconv.AppendUint` and avoid the intermediate buffer?
</blockquote></details>

Not so clear, no. We still need to pad the value on the left. `AppendUint` does not allow it.
The only fast path I can see is when the number of digits is exactly 9, but that seems extremely unlikely in practice.
___
*[pkg/util/hlc/timestamp.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43185#-LwEfo4vBVlkpi_1Dw-U:-LwEi2ZODwJogqRreLue:b-asvjj2) ([raw file](https://github.com/cockroachdb/cockroach/blob/54bf60fe4e8c41bf190219343f6230ce1f14a2d0/pkg/util/hlc/timestamp.go#L88)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could we use `strings.Builder` with an initial `.Grow(12)` to avoid needing to have any unsafe code here?
</blockquote></details>

Using a strings.Builder forces an extra check in every of its `.Write` methods. What do we gain from avoiding the unsafe cast?
___
*[pkg/util/hlc/timestamp_test.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43185#-LwEgsQ67SCcVghaY0W-:-LwEiMfs96jZCeiRwL05:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/54bf60fe4e8c41bf190219343f6230ce1f14a2d0/pkg/util/hlc/timestamp_test.go#L111)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Some of these cases should probably have non-zero logical components.
</blockquote></details>

Done.

**Review by petermattis — APPROVED** [review]
The format change :lgtm:. I'll leave it to you and @nvanbenschoten to work out the implementation discussion.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43185#-:-LwEos227IdpfjbS8IEF:b-h4sroh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @petermattis)

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43185)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/util/hlc/timestamp.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43185#-LwEgWQkELIjvmEsfqQ5:-LwFr5ya8TV7TmLxzVxd:b-vu0piy) ([raw file](https://github.com/cockroachdb/cockroach/blob/54bf60fe4e8c41bf190219343f6230ce1f14a2d0/pkg/util/hlc/timestamp.go#L57)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Not so clear, no. We still need to pad the value on the left. `AppendUint` does not allow it.
The only fast path I can see is when the number of digits is exactly 9, but that seems extremely unlikely in practice.
</blockquote></details>

We can't figure out these cases using modulus and integer division arithmetic and then turn the WallTime formatting into two `strconv.AppendUint` calls interleaved with a few conditions?
___
*[pkg/util/hlc/timestamp.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43185#-LwEfo4vBVlkpi_1Dw-U:-LwFq6Zg48p7tbxAG09u:bgumujb) ([raw file](https://github.com/cockroachdb/cockroach/blob/54bf60fe4e8c41bf190219343f6230ce1f14a2d0/pkg/util/hlc/timestamp.go#L88)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Using a strings.Builder forces an extra check in every of its `.Write` methods. What do we gain from avoiding the unsafe cast?
</blockquote></details>

Because it would hide this complexity. I'm ok leaving this as is if you are, but I'm a little surprised that you'd opt for this.

Also, when you say "forces an extra check", you don't mean the bounds check, right? Because the `appends` here are still going to need to perform bounds checks.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43185)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/util/hlc/timestamp.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43185#-LwEgWQkELIjvmEsfqQ5:-LwIg58y0jYq8CTR9W7v:bmgxz4v) ([raw file](https://github.com/cockroachdb/cockroach/blob/54bf60fe4e8c41bf190219343f6230ce1f14a2d0/pkg/util/hlc/timestamp.go#L57)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We can't figure out these cases using modulus and integer division arithmetic and then turn the WallTime formatting into two `strconv.AppendUint` calls interleaved with a few conditions?
</blockquote></details>

I dont' see how that's either more readable or faster, let alone both.
___
*[pkg/util/hlc/timestamp.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43185#-LwEfo4vBVlkpi_1Dw-U:-LwIgAWh-OmsScNPtR19:b-r6090h) ([raw file](https://github.com/cockroachdb/cockroach/blob/54bf60fe4e8c41bf190219343f6230ce1f14a2d0/pkg/util/hlc/timestamp.go#L88)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Because it would hide this complexity. I'm ok leaving this as is if you are, but I'm a little surprised that you'd opt for this.

Also, when you say "forces an extra check", you don't mean the bounds check, right? Because the `appends` here are still going to need to perform bounds checks.
</blockquote></details>

I mean the check that the builder was not copied.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43185)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/util/hlc/timestamp.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43185#-LwEgWQkELIjvmEsfqQ5:-LwRIU5DBBJlibXnaHvA:bbvnnm9) ([raw file](https://github.com/cockroachdb/cockroach/blob/54bf60fe4e8c41bf190219343f6230ce1f14a2d0/pkg/util/hlc/timestamp.go#L57)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I dont' see how that's either more readable or faster, let alone both.
</blockquote></details>

I'm thinking something like this: https://play.golang.org/p/YeGFi5naP3K

In my opinion, that's more readable (fewer conditions, appending in order, etc.) and is likely faster as well. I think it would be worthwhile to benchmark.
___
*[pkg/util/hlc/timestamp.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43185#-LwEfo4vBVlkpi_1Dw-U:-LwRJ1uG9_vCOx2HC6zg:bn9e1er) ([raw file](https://github.com/cockroachdb/cockroach/blob/54bf60fe4e8c41bf190219343f6230ce1f14a2d0/pkg/util/hlc/timestamp.go#L88)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I mean the check that the builder was not copied.
</blockquote></details>

Hm, I think the best argument for this is that it opens up the use of `strconv.AppendInt` and `strconv.AppendUint`.
___
*[pkg/util/hlc/timestamp.go, line 43 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43185#-LwRJdwHCAfo7T0-1uSm:-LwRJdwHCAfo7T0-1uSn:bpspl3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/74c1d628294aa7d5a22471d9ac0fd6c1834f9c8e/pkg/util/hlc/timestamp.go#L43)):*
> ```Go
> 	// a negative sign in the middle (after the decimal point) if
> 	// the value happened to be negative.
> 	buf := make([]byte, 0, 12)
> ```

Where did you get 12 for this capacity? Just curious.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43185)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/util/hlc/timestamp.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43185#-LwEgWQkELIjvmEsfqQ5:-LwRMACH6F81_f8e0iLG:bd4wb4z) ([raw file](https://github.com/cockroachdb/cockroach/blob/54bf60fe4e8c41bf190219343f6230ce1f14a2d0/pkg/util/hlc/timestamp.go#L57)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm thinking something like this: https://play.golang.org/p/YeGFi5naP3K

In my opinion, that's more readable (fewer conditions, appending in order, etc.) and is likely faster as well. I think it would be worthwhile to benchmark.
</blockquote></details>

I went ahead and did so with the following script: https://play.golang.org/p/8_RDCznlkwC. Here are the results:
```
name         old time/op    new time/op    delta
ToString-16    68.4ns ± 2%    60.3ns ± 2%  -11.84%  (p=0.000 n=10+10)

name         old alloc/op   new alloc/op   delta
ToString-16     24.0B ± 0%     16.0B ± 0%  -33.33%  (p=0.000 n=10+10)

name         old allocs/op  new allocs/op  delta
ToString-16      2.00 ± 0%      1.00 ± 0%  -50.00%  (p=0.000 n=10+10)
```
___
*[pkg/util/hlc/timestamp.go, line 43 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43185#-LwRJdwHCAfo7T0-1uSm:-LwRL7zv1FaaJdiMgGRb:blkeqbn) ([raw file](https://github.com/cockroachdb/cockroach/blob/74c1d628294aa7d5a22471d9ac0fd6c1834f9c8e/pkg/util/hlc/timestamp.go#L43)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Where did you get 12 for this capacity? Just curious.
</blockquote></details>

FWIW I needed to bump this in my benchmark to avoid an extra allocation. This should be tuned to avoid a second alloc in most cases. Is that where 12 came from?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43185)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @nvanbenschoten)

___
*[pkg/util/hlc/timestamp.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43185#-LwEgWQkELIjvmEsfqQ5:-LwTdNX43Ba7nbN6wxte:b6uxbz0) ([raw file](https://github.com/cockroachdb/cockroach/blob/54bf60fe4e8c41bf190219343f6230ce1f14a2d0/pkg/util/hlc/timestamp.go#L57)):*
> In my opinion, that's more readable (fewer conditions, appending in order, etc.) and is likely faster as well. 

I assume you wanted me to ignore the ugly `numDigits` function :laughing: 
But I'll take it. Everyone likes a good old fashioned `fastLog10` function anyway. 
___
*[pkg/util/hlc/timestamp.go, line 43 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43185#-LwRJdwHCAfo7T0-1uSm:-LwTdArtAxDGrFpjnRwb:b-tdjz6i) ([raw file](https://github.com/cockroachdb/cockroach/blob/74c1d628294aa7d5a22471d9ac0fd6c1834f9c8e/pkg/util/hlc/timestamp.go#L43)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

FWIW I needed to bump this in my benchmark to avoid an extra allocation. This should be tuned to avoid a second alloc in most cases. Is that where 12 came from?
</blockquote></details>

It's the value sufficient to avoid an allocation in our tests, as they last less than 10 seconds in the common case.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43185)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @nvanbenschoten)

___
*[pkg/util/hlc/timestamp.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43185#-LwEgWQkELIjvmEsfqQ5:-LwUAS013N-CtAJ81sVY:b-wzept9) ([raw file](https://github.com/cockroachdb/cockroach/blob/54bf60fe4e8c41bf190219343f6230ce1f14a2d0/pkg/util/hlc/timestamp.go#L57)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

> In my opinion, that's more readable (fewer conditions, appending in order, etc.) and is likely faster as well. 

I assume you wanted me to ignore the ugly `numDigits` function :laughing: 
But I'll take it. Everyone likes a good old fashioned `fastLog10` function anyway. 

</blockquote></details>

(Also FYI regarding your gist, the go compiler did constant propagation so that skewed your benchmark positively. )

**Comment by knz** [comment]
RFAL

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43185#-:-LwWeEpw-GYvIa63tWNU:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Comment by knz** [comment]
TFYRs!

bors r+

**Pull request merged**
