### PR TITLE
Write node clock offset interval to time series

### LINKED ISSUE #859: ui: write node clock offset interval to time series
We should periodically write the offset interval as measured by all nodes to a time series.

### PR DESCRIPTION
**Pull request by cuongdo**
Also reformatted util/metric/doc.go to follow 80-column guideline for comments and lightly updated the content.

Resolves #859

---

This change is [Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5229)

### CODE REVIEW

**Comment by tamird** [comment]
This is gonna be in conflict with #5107. Can you hold off until that's merged? Should be today.

**Comment by spencerkimball** [comment]
LGTM

**Comment by cuongdo** [comment]
Made a small change to avoid a data race after `TestClockOffsetMetrics` returns.

@tamird: yes, will hold off until your PR goes in

**Comment by cuongdo** [comment]
Rebased over @tamird's changes, which caused several changes to this PR

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[rpc/clock_offset.go, line 33 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5229#-KCqO1peXcB6A_QEVhJM:-KCqO1pfgpFc3cUCErhz:742628348) ([raw file](https://github.com/cockroachdb/cockroach/blob/117050c44389772cbef2e93e43580a65674cc91c/rpc/clock_offset.go#L33)):*
any reason for these to begin with upper case?

---

*[rpc/clock_offset_test.go, line 371 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5229#-KCqODbhWEtl_dYIajAw:-KCqODbhWEtl_dYIajAx:-1370848744) ([raw file](https://github.com/cockroachdb/cockroach/blob/117050c44389772cbef2e93e43580a65674cc91c/rpc/clock_offset_test.go#L371)):*
not safe to call this from the non-main goroutine.

---

*[rpc/clock_offset_test.go, line 377 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5229#-KCqOHYYIGpCXbyijcqL:-KCqOHYYIGpCXbyijcqM:1131006634) ([raw file](https://github.com/cockroachdb/cockroach/blob/117050c44389772cbef2e93e43580a65674cc91c/rpc/clock_offset_test.go#L377)):*
there are some magic values here. can you make this self-documenting?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5229#-:-KCqOLwPq7fpEGs49WHY:1417088721)*

**Comment by cuongdo** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[rpc/clock_offset.go, line 33 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5229#-KCqO1peXcB6A_QEVhJM:-KCqSt-zWRhZRnrm4ZMR:-1499250761) ([raw file](https://github.com/cockroachdb/cockroach/blob/117050c44389772cbef2e93e43580a65674cc91c/rpc/clock_offset.go#L33)):*
No, that was a holdover from a previous revision. Unexported them.

---

*[rpc/clock_offset_test.go, line 371 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5229#-KCqODbhWEtl_dYIajAw:-KCqVxDOSSfgtQ14S8AM:732432900) ([raw file](https://github.com/cockroachdb/cockroach/blob/117050c44389772cbef2e93e43580a65674cc91c/rpc/clock_offset_test.go#L371)):*
Changed to `Error`

---

*[rpc/clock_offset_test.go, line 377 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5229#-KCqOHYYIGpCXbyijcqL:-KCqW-1pwgoEwcJMCCXF:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/117050c44389772cbef2e93e43580a65674cc91c/rpc/clock_offset_test.go#L377)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5229)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5229)*

**Pull request merged**
