### PR TITLE
kv: fork context span for async GRPC transport

### LINKED ISSUE #12529: stability: span used after call to Finish()
```
panic: span used after call to Finish():
&{tracer:<nil> event:0xd9a140 Mutex:{state:0 sema:0} raw:{Context:{TraceID:6383740812092313299 SpanID:320797998694638280
3 Sampled:false Baggage:map[]} ParentSpanID:0 Operation:sql txn Start:{sec:63617893721 nsec:285667018 loc:0x2ae8660} Dur
ation:538694040 Tags:map[] Logs:[]} numDroppedLogs:0}

goroutine 1122428 [running]:
panic(0x1880780, 0xc431ec7220)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/vendor/github.com/opentracing/basictracer-go.(*spanImpl).maybeAssertSanityLocked(0xc42d
bfe6e0)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/opentracing/basictracer-go/debug.go:31 +0x341
github.com/cockroachdb/cockroach/vendor/github.com/opentracing/basictracer-go.(*spanImpl).Lock(0xc42dbfe6e0)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/opentracing/basictracer-go/debug.go:25 +0x3f
github.com/cockroachdb/cockroach/vendor/github.com/opentracing/basictracer-go.(*spanImpl).LogFields(0xc42dbfe6e0, 0xc431
fbe300, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/opentracing/basictracer-go/span.go:123 +0xd3
github.com/cockroachdb/cockroach/pkg/util/tracing.(*TeeSpan).LogFields(0xc42fae6280, 0xc431fbe300, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/tracing/tee_tracer.go:183 +0x73
github.com/cockroachdb/cockroach/pkg/util/log.eventInternal(0x7fc1bd6a69d0, 0xc42d00ef40, 0x100, 0x1a37b25, 0x15, 0xc428
2b9e28, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/trace.go:132 +0x4bc
github.com/cockroachdb/cockroach/pkg/util/log.VEventf(0x7fc1bd6a69d0, 0xc42d00ef40, 0xc400000002, 0x1a37b25, 0x15, 0xc42
82b9e28, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/trace.go:203 +0x107
github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).SendNext.func1.1(0xc427923590, 0xc42ad4d540, 0x7fc1bd6a69d0, 0x
c42d00ef40, 0xc420440f60, 0xc420440f70, 0xc420440f88)
        /go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:188 +0x14c
github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).SendNext.func1(0xc427923590, 0xc42ad4d540, 0x7fc1bd6a69d0, 0xc4
2d00ef40, 0xc42f8a03c0)
        /go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:198 +0x80
created by github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).SendNext
        /go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:201 +0x101
```

Cc @cockroachdb/stability, @spencerkimball

### PR DESCRIPTION
**Pull request by spencerkimball**
Fixes #12529

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12531)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/kv/transport.go, line 169 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12531#-KZWrPnP58XC775Vd6DF:-KZWrPnP58XC775Vd6DG:brkmc58) ([raw file](https://github.com/cockroachdb/cockroach/blob/f139604eca2ec09ca96df87f5db68df473d2cbfe/pkg/kv/transport.go#L169)):*
> ```Go
> 	// Fork the original context as this async send may outlast the
> 	// caller's context.
> 	ctx := tracing.ForkCtxSpan(ctx, "grpcTransport SendNext")
> ```

Not in love with that `opName`, but don't have a better suggestion right now. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12531)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12531#-:-KZWrkOlwwB5pa9BBytu:bnfp4nl)*

**Review by a-robinson — APPROVED** [review]
LGTM

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/kv/transport.go, line 169 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12531#-KZWrPnP58XC775Vd6DF:-KZWvBCg6qL_7AFNMJme:b-9bwxjk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f139604eca2ec09ca96df87f5db68df473d2cbfe/pkg/kv/transport.go#L169)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Not in love with that `opName`, but don't have a better suggestion right now. 
</blockquote></details>

Perhaps `RPC send` to match up with the `RPC reply` and `RPC error` events in `dist_sender.go`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12531)*

**Comment by a-robinson** [comment]
Merging so we can get the clusters up and running again

**Comment by tamird** [comment]
Copying my comment from #12529:
> This is caused by #12507 which moved a log line into the async part of SendNext. An alternative fix to #12531 would be to move those two log lines back out of the goroutine.

**Comment by BramGruneir** [comment]
Talked offline with @tamird, this is the correct solution.  Merging this.

**Pull request merged**
