### PR TITLE
sql: prevent dropping regions when regions <= 3 on SURVIVE REGION FAILURE

### PR DESCRIPTION
**Pull request by otan**
Refs: #61774

Release note (bug fix): Prevent regions being dropped on multi-region
databases when there are <= 3 regions left on the database.

### CODE REVIEW

**Review by ajstorm — APPROVED** [review]
Nit: Should commit record finish with "and the database is configured to SURVIVE REGION FAILURE"?

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62051#-:-MVv8kEI3T1BNfY7eHs3:ba2ky29)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/alter_database.go, line 367 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62051#-MVvAM3kEnzhDwWg13cQ:-MVvAM3kEnzhDwWg13cR:bk42xnm) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b72a8abfab1554b0f25ba556dcbbe994b1cd181/pkg/sql/alter_database.go#L367)):*
> ```Go
> 			return nil, err
> 		}
> 		if len(regionNames) <= 3 {
> ```

Nit: Can we add an assertion in here that the len is not <3?  Is there any way to get here and have the number of regions < 3?

**Review by arulajmani — COMMENTED** [review]
Excited for the rebase conflict! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62051#-:-MVwK9s42wtIkjB4eMc7:byawakc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/alter_database.go, line 367 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62051#-MVwJmzu7UouwKdybaZ3:-MVwJmzu7UouwKdybaZ4:b-x0qxyh) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b72a8abfab1554b0f25ba556dcbbe994b1cd181/pkg/sql/alter_database.go#L367)):*
> ```Go
> 			return nil, err
> 		}
> 		if len(regionNames) <= 3 {
> ```

nit: we have this `MinNumRegionsForSurviveRegionGoal` that you could use here.

**Comment by ajstorm** [comment]
I'm excited that I'm sitting this rebase conflict out, for once.

**Comment by otan** [comment]
> Excited for the rebase conflict!

This doesn't rebase conflict -- i originally had this against your branch @arulajmani and rebased onto master cleanly!

**Comment by otan** [comment]
bors r=ajstorm

**Comment by otan** [comment]
bors r=ajstorm

**Pull request merged**
