### PR TITLE
sql/catalog,migrations: propagate HasPostDeserializationChanges, simplify migrations

### PR DESCRIPTION
**Pull request by ajwerner**
This is an imperfect change that feels a bit ad-hoc for my liking, but does
improve the situation. The problem is that in recent changes, we no longer
just retrieve mutable descriptors and then sometimes clone Immutable
descriptors. Instead we create the more general Immutable descriptors and
clone out mutables. The problem is that when we did this, we threw away
information regarding whether the descriptor itself had been modified
by post-deserialization. In general, this is mostly an exercise in plumbing.
The key feature is that when we retreive a Mutable descriptor and it was
changed, we need to know that. This change tests that.

There is some ad-hoc code to propagate isUncommitedVersion in various places
which I don't feel great about, but it also felt wrong not to. A follow-up
should come through to really nail down the properties here.

The existence of NewBuilder and the fact that it's called in various places
is another mechanism by which this information could be erased, but that's
less of a concern for me. This change makes it possible to simplify migrations
around descriptor upgrades.

### migrations: simplify descriptor migrations

We have two migrations which have the goal of iterating through the descriptors
and re-writing them if there are any changes due to the post-deserialization
logic. They were needlessly complex and low-level. Probably part of the reason
was that we were swallowing this information. This commit reworks them to use
shared library code.

Probably one of them could be eliminated altogether.

Release note: None

### CODE REVIEW

**Review by postamar — APPROVED** [review]
> Reviewed 16 of 20 files at r1, 9 of 9 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76590)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @RichardJCai)

___
*[pkg/migration/migrations/descriptor_utils.go, line 74 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76590#-MvyeA7c80ZsyE_zFCsL:-MvyeA7c80ZsyE_zFCsM:bs4w5pi) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f5179c87127509424a208566658c2afb7fb0419/pkg/migration/migrations/descriptor_utils.go#L74)):*
> ```Go
> func runPostDeserializationChangesOnAllDescriptors(
> 	ctx context.Context, d migration.TenantDeps,
> ) error {
> ```

I'm glad you're putting this thing in our migration toolbox of sorts. I feel like there's bound to be at least one such migration in each release.
___
*[pkg/sql/catalog/descriptor.go, line 215 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76590#-MvycS2a8j47qNwBAMj9:-MvycS2a8j47qNwBAMjA:beat3sv) ([raw file](https://github.com/cockroachdb/cockroach/blob/17bcea77ad45aee885cfe746bc56c23daa7e397e/pkg/sql/catalog/descriptor.go#L215)):*
> ```Go
> 	GetDeclarativeSchemaChangerState() *scpb.DescriptorState
> 
> 	// HasPostDeserializationChanges returns if the MutableDescriptor was changed after running
> ```

nit: s/MutableDescriptor/Descriptor
___
*[pkg/sql/catalog/dbdesc/database_desc.go, line 48 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76590#-MvyciHZ-dF624pQSFdA:-MvyciHZ-dF624pQSFdB:bt1xher) ([raw file](https://github.com/cockroachdb/cockroach/blob/17bcea77ad45aee885cfe746bc56c23daa7e397e/pkg/sql/catalog/dbdesc/database_desc.go#L48)):*
> ```Go
> 	// changed represents whether or not the descriptor was changed
> 	// after RunPostDeserializationChanges.
> 	changed bool
> ```

While we're at it, consider:
- moving `PostDeserializationChangeType` to `catalog` and,
- store the `map[PostDeserializationChangeType]bool` in this `immutable` instead of this flag,
- same with other descriptor types,
- replace `HasPostDeserializationChanges` with, say, `ForEachPostDeserializationChange(func(PostDeserializationChangeType) error) error`
- provide `HasPostDeserializationChanges` as a helper function which calls this `ForEachPostDeserializationChange` instead.

Feel free to not bother if you don't want to, & file a follow-up issue based off this comment & assign it to me.
___
*[pkg/migration/migrations/ensure_constraint_id_test.go, line 126 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76590#-MvyeOQB08Nkvmo0JLtF:-MvyeOQB08Nkvmo0JLtG:bvy1g2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f5179c87127509424a208566658c2afb7fb0419/pkg/migration/migrations/ensure_constraint_id_test.go#L126)):*
> ```Go
> 		[][]string{{"false", "false"}},
> 	)
> 	log.Infof(ctx, "okay about to upgrade")
> ```

detritus?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76590)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @postamar, and @RichardJCai)

___
*[pkg/sql/catalog/dbdesc/database_desc.go, line 48 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76590#-MvyciHZ-dF624pQSFdA:-MvyzgQgELow5eog2cxX:bqx33hq) ([raw file](https://github.com/cockroachdb/cockroach/blob/17bcea77ad45aee885cfe746bc56c23daa7e397e/pkg/sql/catalog/dbdesc/database_desc.go#L48)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

While we're at it, consider:
- moving `PostDeserializationChangeType` to `catalog` and,
- store the `map[PostDeserializationChangeType]bool` in this `immutable` instead of this flag,
- same with other descriptor types,
- replace `HasPostDeserializationChanges` with, say, `ForEachPostDeserializationChange(func(PostDeserializationChangeType) error) error`
- provide `HasPostDeserializationChanges` as a helper function which calls this `ForEachPostDeserializationChange` instead.

Feel free to not bother if you don't want to, & file a follow-up issue based off this comment & assign it to me.
</blockquote></details>

I did this, more or less, 
___
*[pkg/migration/migrations/ensure_constraint_id_test.go, line 126 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76590#-MvyeOQB08Nkvmo0JLtF:-MvzHa0HEppoYgLlv2VX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f5179c87127509424a208566658c2afb7fb0419/pkg/migration/migrations/ensure_constraint_id_test.go#L126)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

detritus?
</blockquote></details>

Done.

**Review by postamar — APPROVED** [review]
> Reviewed 23 of 23 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76590)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @RichardJCai)

___
*[pkg/sql/catalog/dbdesc/database_desc.go, line 48 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76590#-MvyciHZ-dF624pQSFdA:-MvzIVvTAhzjSIhMIJiS:b-ao1qat) ([raw file](https://github.com/cockroachdb/cockroach/blob/17bcea77ad45aee885cfe746bc56c23daa7e397e/pkg/sql/catalog/dbdesc/database_desc.go#L48)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I did this, more or less, 
</blockquote></details>

Nicely done.

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Review by RichardJCai — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76590)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/migration/migrations/descriptor_utils.go, line 74 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76590#-MvyeA7c80ZsyE_zFCsL:-MvzdnhbC81E61u3yZK0:bdhvnbg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f5179c87127509424a208566658c2afb7fb0419/pkg/migration/migrations/descriptor_utils.go#L74)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I'm glad you're putting this thing in our migration toolbox of sorts. I feel like there's bound to be at least one such migration in each release.
</blockquote></details>

Huge +1, thanks for this.

**Pull request merged**
