### PR TITLE
internal/client: Make the lease manager thread-safe

### LINKED ISSUE #28222: datarace in LeaseManager exposed by TestReplicateQueueDownReplicate
Check out this test failure: https://github.com/cockroachdb/cockroach/issues/27783#issuecomment-409103410
Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=806649&tab=buildLog

```
[05:53:03] :	 [Step 2/2] WARNING: DATA RACE
[05:53:03] :	 [Step 2/2] Write at 0x00c422182738 by goroutine 514:
[05:53:03] :	 [Step 2/2]   github.com/cockroachdb/cockroach/pkg/internal/client.(*LeaseManager).ExtendLease()
[05:53:03] :	 [Step 2/2]       /go/src/github.com/cockroachdb/cockroach/pkg/internal/client/lease.go:154 +0x3d7
[05:53:03] :	 [Step 2/2]   github.com/cockroachdb/cockroach/pkg/sqlmigrations.(*Manager).EnsureMigrations.func2()
[05:53:03] :	 [Step 2/2]       /go/src/github.com/cockroachdb/cockroach/pkg/sqlmigrations/migrations.go:394 +0x192
[05:53:03] :	 [Step 2/2]   github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1()
[05:53:03] :	 [Step 2/2]       /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:324 +0xf3
[05:53:03] :	 [Step 2/2] 
[05:53:03] :	 [Step 2/2] Previous read at 0x00c422182738 by goroutine 1347:
[05:53:03] :	 [Step 2/2]   github.com/cockroachdb/cockroach/pkg/internal/client.(*LeaseManager).ReleaseLease()
[05:53:03] :	 [Step 2/2]       /go/src/github.com/cockroachdb/cockroach/pkg/internal/client/lease.go:161 +0x54
[05:53:03] :	 [Step 2/2]   github.com/cockroachdb/cockroach/pkg/sqlmigrations.(*Manager).EnsureMigrations.func1()
[05:53:03] :	 [Step 2/2]       /go/src/github.com/cockroachdb/cockroach/pkg/sqlmigrations/migrations.go:384 +0xd1
[05:53:03] :	 [Step 2/2]   github.com/cockroachdb/cockroach/pkg/sqlmigrations.(*Manager).EnsureMigrations()
[05:53:03] :	 [Step 2/2]       /go/src/github.com/cockroachdb/cockroach/pkg/sqlmigrations/migrations.go:462 +0x1429
[05:53:03] :	 [Step 2/2]   github.com/cockroachdb/cockroach/pkg/server.(*Server).Start()
[05:53:03] :	 [Step 2/2]       /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1591 +0x4f9d
[05:53:03] :	 [Step 2/2]   github.com/cockroachdb/cockroach/pkg/server.(*TestServer).Start()
[05:53:03] :	 [Step 2/2]       /go/src/github.com/cockroachdb/cockroach/pkg/server/testserver.go:344 +0x244
[05:53:03] :	 [Step 2/2]   github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartServerRaw()
[05:53:03] :	 [Step 2/2]       /go/src/github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_server_shim.go:206 +0x140
[05:53:03] :	 [Step 2/2]   github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartServer()
[05:53:03] :	 [Step 2/2]       /go/src/github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_server_shim.go:174 +0x73
[05:53:03] :	 [Step 2/2]   github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).doAddServer()
[05:53:03] :	 [Step 2/2]       /go/src/github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:251 +0x161
[05:53:03] :	 [Step 2/2]   github.com/cockroachdb/cockroach/pkg/testutils/testcluster.StartTestCluster()
[05:53:03] :	 [Step 2/2]       /go/src/github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:157 +0x6ff
[05:53:03] :	 [Step 2/2]   github.com/cockroachdb/cockroach/pkg/storage_test.TestReplicateQueueDownReplicate()
[05:53:03] :	 [Step 2/2]       /go/src/github.com/cockroachdb/cockroach/pkg/storage/replicate_queue_test.go:180 +0xce
[05:53:03] :	 [Step 2/2]   testing.tRunner()
[05:53:03] :	 [Step 2/2]       /usr/local/go/src/testing/testing.go:777 +0x16d
[05:53:03] :	 [Step 2/2] 
[05:53:03] :	 [Step 2/2] Goroutine 514 (running) created at:
[05:53:03] :	 [Step 2/2]   github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask()
[05:53:03] :	 [Step 2/2]       /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:319 +0x14c
[05:53:03] :	 [Step 2/2]   github.com/cockroachdb/cockroach/pkg/sqlmigrations.(*Manager).EnsureMigrations()
[05:53:03] :	 [Step 2/2]       /go/src/github.com/cockroachdb/cockroach/pkg/sqlmigrations/migrations.go:388 +0x9cd
[05:53:03] :	 [Step 2/2]   github.com/cockroachdb/cockroach/pkg/server.(*Server).Start()
[05:53:03] :	 [Step 2/2]       /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1591 +0x4f9d
[05:53:03] :	 [Step 2/2]   github.com/cockroachdb/cockroach/pkg/server.(*TestServer).Start()
[05:53:03] :	 [Step 2/2]       /go/src/github.com/cockroachdb/cockroach/pkg/server/testserver.go:344 +0x244
[05:53:03] :	 [Step 2/2]   github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartServerRaw()
[05:53:03] :	 [Step 2/2]       /go/src/github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_server_shim.go:206 +0x140
[05:53:03] :	 [Step 2/2]   github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartServer()
[05:53:03] :	 [Step 2/2]       /go/src/github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_server_shim.go:174 +0x73
[05:53:03] :	 [Step 2/2]   github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).doAddServer()
[05:53:03] :	 [Step 2/2]       /go/src/github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:251 +0x161
[05:53:03] :	 [Step 2/2]   github.com/cockroachdb/cockroach/pkg/testutils/testcluster.StartTestCluster()
[05:53:03] :	 [Step 2/2]       /go/src/github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:157 +0x6ff
[05:53:03] :	 [Step 2/2]   github.com/cockroachdb/cockroach/pkg/storage_test.TestReplicateQueueDownReplicate()
[05:53:03] :	 [Step 2/2]       /go/src/github.com/cockroachdb/cockroach/pkg/storage/replicate_queue_test.go:180 +0xce
[05:53:03] :	 [Step 2/2]   testing.tRunner()
[05:53:03] :	 [Step 2/2]       /usr/local/go/src/testing/testing.go:777 +0x16d
[05:53:03] :	 [Step 2/2] 
[05:53:03] :	 [Step 2/2] Goroutine 1347 (running) created at:
[05:53:03] :	 [Step 2/2]   testing.(*T).Run()
[05:53:03] :	 [Step 2/2]       /usr/local/go/src/testing/testing.go:824 +0x564
[05:53:03] :	 [Step 2/2]   testing.runTests.func1()
[05:53:03] :	 [Step 2/2]       /usr/local/go/src/testing/testing.go:1063 +0xa4
[05:53:03] :	 [Step 2/2]   testing.tRunner()
[05:53:03] :	 [Step 2/2]       /usr/local/go/src/testing/testing.go:777 +0x16d
[05:53:03] :	 [Step 2/2]   testing.runTests()
[05:53:03] :	 [Step 2/2]       /usr/local/go/src/testing/testing.go:1061 +0x4e1
[05:53:03] :	 [Step 2/2]   testing.(*M).Run()
[05:53:03] :	 [Step 2/2]       /usr/local/go/src/testing/testing.go:978 +0x2cd
[05:53:03] :	 [Step 2/2]   github.com/cockroachdb/cockroach/pkg/storage_test.TestMain()
[05:53:03] :	 [Step 2/2]       /go/src/github.com/cockroachdb/cockroach/pkg/storage/main_test.go:57 +0x2a8
[05:53:03] :	 [Step 2/2]   main.main()
[05:53:03] :	 [Step 2/2]       _testmain.go:1088 +0x22a
```

### PR DESCRIPTION
**Pull request by a-robinson**
This race was exceptionally rare due to how the lease manager is
typically used by the sqlmigrations package, but it is indeed a race.

Holding a mutex while making a remote RPC is usually a terrible idea,
but in the context of how it's used it's actually more dangerous to let
ExtendLease and ReleaseLease interleave, since if ReleaseLease's CPut
fails then the sqlmigrations package will log.Fatal, and the only
potential for lock contention is between one goroutine using ExtendLease
and one running ReleaseLseas. Perhaps this is tuning the package too
tightly to the needs of its client, but as of now it's its only client.

Fixes #28222

Release note: None

### CODE REVIEW

**Review by bdarnell — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28223)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/internal/client/lease.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28223#-LIwlt-U1IhCvm2seqW4:-LIwlt-U1IhCvm2seqW5:b801msj) ([raw file](https://github.com/cockroachdb/cockroach/blob/eeb347e25025378d9c4fe8a6d192174b036ee926/pkg/internal/client/lease.go#L61)):*
> ```Go
> 	key roachpb.Key
> 	val struct {
> 		syncutil.Mutex
> ```

This would be better with a single-element channel semaphore instead of a mutex. That way the lock acquisition can be composed with a select on `ctx.Done()`.

**Review by andreimatei — CHANGES_REQUESTED** [review]
LGTM as far as I'm concerned

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28223#-:-LIwyozD2suf2XatI2Tr:b-w2yzhs)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/internal/client/lease.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28223#-LIwxipf0XjHI6aDauOU:-LIwxipf0XjHI6aDauOV:bfs9clg) ([raw file](https://github.com/cockroachdb/cockroach/blob/eeb347e25025378d9c4fe8a6d192174b036ee926/pkg/internal/client/lease.go#L57)):*
> ```Go
> 
> // Lease contains the state of a lease on a particular key.
> // Should only be passed by pointer, not by value.
> ```

you can't pass it by value since it now has the mutex. I'd get rid of the comment.
___
*[pkg/internal/client/lease.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28223#-LIwlt-U1IhCvm2seqW4:-LIwyP_j4xMS8oAQl_lz:b-v0n1vo) ([raw file](https://github.com/cockroachdb/cockroach/blob/eeb347e25025378d9c4fe8a6d192174b036ee926/pkg/internal/client/lease.go#L61)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This would be better with a single-element channel semaphore instead of a mutex. That way the lock acquisition can be composed with a select on `ctx.Done()`. 
</blockquote></details>

But where would that composition be useful? This lock is never supposed to be held for long. IOW, why did you chose this particular lock to make this implementation point?
In fact we could make the `*LeaseVal` an atomic.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28223)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/internal/client/lease.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28223#-LIwlt-U1IhCvm2seqW4:-LJ-CZm35Xca9lOol050:b-kgnyg7) ([raw file](https://github.com/cockroachdb/cockroach/blob/eeb347e25025378d9c4fe8a6d192174b036ee926/pkg/internal/client/lease.go#L61)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

But where would that composition be useful? This lock is never supposed to be held for long. IOW, why did you chose this particular lock to make this implementation point?
In fact we could make the `*LeaseVal` an atomic.
</blockquote></details>

oh nvm, I missed where this lock was really held. Perhaps we should do something else indeed.

**Review by a-robinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28223)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/internal/client/lease.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28223#-LIwxipf0XjHI6aDauOU:-LJ-KHG95tYs1UpWSA6M:b-4zygyk) ([raw file](https://github.com/cockroachdb/cockroach/blob/eeb347e25025378d9c4fe8a6d192174b036ee926/pkg/internal/client/lease.go#L57)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

you can't pass it by value since it now has the mutex. I'd get rid of the comment.
</blockquote></details>

I always forget that about go. Done.
___
*[pkg/internal/client/lease.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28223#-LIwlt-U1IhCvm2seqW4:-LJ-Ngw3Dtt715OJfywn:b-6bzgb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/eeb347e25025378d9c4fe8a6d192174b036ee926/pkg/internal/client/lease.go#L61)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

oh nvm, I missed where this lock was really held. Perhaps we should do something else indeed.
</blockquote></details>

I had been relying on the calls to `m.db.CPut` respecting the ctx and bailing out early when it's cancelled, but you're right that this is a bit more explicit. Changed.

**Review by bdarnell — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28223)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/internal/client/lease.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28223#-LIwxipf0XjHI6aDauOU:-LJ-oByp4FrrmX6zaqkU:b-9ononu) ([raw file](https://github.com/cockroachdb/cockroach/blob/eeb347e25025378d9c4fe8a6d192174b036ee926/pkg/internal/client/lease.go#L57)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

I always forget that about go. Done.
</blockquote></details>

The lint warning about copying a mutex no longer applies since it is now a channel.

**Review by a-robinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28223)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/internal/client/lease.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28223#-LIwxipf0XjHI6aDauOU:-LJ-ukdG4Hr9hz9ESZg8:bs5ov9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/eeb347e25025378d9c4fe8a6d192174b036ee926/pkg/internal/client/lease.go#L57)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

The lint warning about copying a mutex no longer applies since it is now a channel. 
</blockquote></details>

Right, but it's also not dangerous to pass a channel by value.

**Pull request merged**
