### PR TITLE
colexec: use full memory limit in spilling queue until actual spilling

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, we would reduce the memory limit of the spilling queue by
the disk queue's buffer size right away. However, that memory is only
used when actual spilling occurs, so this commit adds relatively simple
logic to have more precise handling of the max memory limit. The core
idea is that once the spilling occurs, we need to move the tail of the
in-memory buffer onto the disk queue.

Release note: None

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59658)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/spilling_queue.go, line 415 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59658#-MSXg5Yw9M04PCjmdzvr:-MSXg5Yw9M04PCjmdzvs:bksridz) ([raw file](https://github.com/cockroachdb/cockroach/blob/974a37813cb3519de5cad0b09f9e55b59f62d393/pkg/sql/colexec/spilling_queue.go#L415)):*
> ```Go
> }
> 
> func (q *spillingQueue) maybeSpillToDisk(ctx context.Context) error {
> ```

One test that might be good to add is have a low memory limit = buffer size and add any number of batches then force the queue to spill by calling `maybeSpillToDisk` and assert that there are no in-memory batches left.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59658)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/spilling_queue.go, line 415 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59658#-MSXg5Yw9M04PCjmdzvr:-MS_PKy5CnD_JfK5bry-:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/974a37813cb3519de5cad0b09f9e55b59f62d393/pkg/sql/colexec/spilling_queue.go#L415)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

One test that might be good to add is have a low memory limit = buffer size and add any number of batches then force the queue to spill by calling `maybeSpillToDisk` and assert that there are no in-memory batches left.
</blockquote></details>

Good point, done.

**Review by asubiotto — APPROVED** [review]
:lgtm: thanks for adding the test!

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59658#-:-MSbWh_zDZRVpKF-l5KR:b-dory68)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by yuzefovich** [comment]
Flake.

bors r+

**Pull request merged**
