### PR TITLE
schemachanger: cleanup full type closure for type back refs

### PR DESCRIPTION
**Pull request by fqazi**
Previously, the declarative schema changer did not clean up the
type closure for back references, which could lead to dangling
references inside a type. This was inadequate because, type
drops could encounter validation failure due to phantom
back references. To address this, this patch always cleans
up the full closure for a given type at a time, when
cleaning up back references. Additionally, type references
in check constraints were not always cleaned up and
address with this patch.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
Just minor stuff 

> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73589#-:-MqN8BYIEpO7h8ykcYob:bbnyxy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @postamar)

___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_relation.go, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73589#-MqN6P2ZCOcDYAbmNuRQ:-MqN6P2ZCOcDYAbmNuRR:b80oaz0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b36605ec8b4b16acba4f3a30f541ad46ec8625f/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_relation.go#L117)):*
> ```
> // decomposeExprToTypeRef converts and inserts type references from
> // an expression.
> func decomposeExprToElements(
> ```
this could use better commentary. It could talk more about what these expressions are, what conversion might happen, what references might be added to what, etc. 
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_relation.go, line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73589#-MqN6w52DDfEihiD1Keg:-MqN6w52DDfEihiD1Keh:b-yzgbtt) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b36605ec8b4b16acba4f3a30f541ad46ec8625f/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_relation.go#L122)):*
> ```
> 	table catalog.TableDescriptor,
> 	column catalog.Column,
> ```
this function only seems to use these for their IDs, can we scope its arguments down to just the IDs? It'll make it easier to understand from a distance. 
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_relation.go, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73589#-MqN6Gvi-MpEeeiISMh2:-MqN6Gvi-MpEeeiISMh3:bnheky7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b36605ec8b4b16acba4f3a30f541ad46ec8625f/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_relation.go#L202)):*
> ```Go
> 		addOrDropForDir(b, dir, &expressionElem)
> 		// Decompose any elements required for expressions.
> 		decomposeExprToElements(b, defaultExpr, exprTypeDefault, table, column, 0, dir)
> ```

put `0` in a const/variable with a meaningful name or comment it.
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_relation.go, line 256 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73589#-MqN6BQA-3Vh9HHO4hME:-MqN6BQA-3Vh9HHO4hMF:bnheky7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b36605ec8b4b16acba4f3a30f541ad46ec8625f/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_relation.go#L256)):*
> ```Go
> 	decomposeDefaultExprToElements(b, tbl, column, dir)
> 	// Deal with computed and on update expressions
> 	decomposeExprToElements(b, column.GetComputeExpr(), exprTypeComputed, tbl, column, 0, dir)
> ```

put `0` in a const/variable with a meaningful name or comment it.
___
*[pkg/sql/schemachanger/scpb/scpb.proto, line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73589#-MqN5psO3GBPmPtdny5e:-MqN5psP4liJTFMASqUp:bt6h38n) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b36605ec8b4b16acba4f3a30f541ad46ec8625f/pkg/sql/schemachanger/scpb/scpb.proto#L227)):*
> ```protobuf
> }
> 
> message CheckTypeReference {
> ```

Can we call this `CheckConstraintTypeReference`? My brain does not interpret `CheckTypeReference` to mean that without serious effort. 
___
*[pkg/sql/schemachanger/scplan/opgen/opgen_check_type_reference.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73589#-MqN7SsV9BMjcEGhcGNq:-MqN7SsV9BMjcEGhcGNr:bdenlps) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b36605ec8b4b16acba4f3a30f541ad46ec8625f/pkg/sql/schemachanger/scplan/opgen/opgen_check_type_reference.go#L36)):*
> ```Go
> 				revertible(false),
> 				emit(func(this *scpb.CheckTypeReference) scop.Op {
> 					return &scop.RemoveTypeBackRef{
> ```

We can defer this concern for a bit, but it'll pop back up soon. I worry that the implementation of `RemoveTypeBackRef` is too simplistic, which is sad. Or, at least, we're going to be in trouble when later you can add or remove one of these constraints. Consider the case where you have a type reference for more than one reason and then we only change one of those reasons. Maybe the operation needs to be `RefreshTypeBackReference` or something which checks whether there should still be a back reference. It's all a hint that the type back reference tracking is not fine-grained enough.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73589)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @fqazi, and @postamar)

___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_relation.go, line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73589#-MqN6w52DDfEihiD1Keg:-MqPc_Y56NEpQ_FKELKa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b36605ec8b4b16acba4f3a30f541ad46ec8625f/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_relation.go#L122)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	table catalog.TableDescriptor,
> 	column catalog.Column,
> ```
this function only seems to use these for their IDs, can we scope its arguments down to just the IDs? It'll make it easier to understand from a distance. 
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_relation.go, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73589#-MqN6Gvi-MpEeeiISMh2:-MqPc_wb-YEZtYEgQGEu:bh28vwy) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b36605ec8b4b16acba4f3a30f541ad46ec8625f/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_relation.go#L202)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

put `0` in a const/variable with a meaningful name or comment it.
</blockquote></details>

I changed the approach here to have a single variable that either refers to the ColumnID or constraint ordinal
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_relation.go, line 256 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73589#-MqN6BQA-3Vh9HHO4hME:-MqPchyjEYMgi1TlEsDM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b36605ec8b4b16acba4f3a30f541ad46ec8625f/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_relation.go#L256)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

put `0` in a const/variable with a meaningful name or comment it.
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scpb/scpb.proto, line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73589#-MqN5psO3GBPmPtdny5e:-MqPcj0h6H5w4tsFnOhi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b36605ec8b4b16acba4f3a30f541ad46ec8625f/pkg/sql/schemachanger/scpb/scpb.proto#L227)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Can we call this `CheckConstraintTypeReference`? My brain does not interpret `CheckTypeReference` to mean that without serious effort. 
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scplan/opgen/opgen_check_type_reference.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73589#-MqN7SsV9BMjcEGhcGNq:-MqPcmJ44SFzPtJUYfwM:b-8rnkor) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b36605ec8b4b16acba4f3a30f541ad46ec8625f/pkg/sql/schemachanger/scplan/opgen/opgen_check_type_reference.go#L36)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

We can defer this concern for a bit, but it'll pop back up soon. I worry that the implementation of `RemoveTypeBackRef` is too simplistic, which is sad. Or, at least, we're going to be in trouble when later you can add or remove one of these constraints. Consider the case where you have a type reference for more than one reason and then we only change one of those reasons. Maybe the operation needs to be `RefreshTypeBackReference` or something which checks whether there should still be a back reference. It's all a hint that the type back reference tracking is not fine-grained enough. 
</blockquote></details>

It's definitely too simplistic, and I think we started off with the refreshing approach and then moved to this one since we felt the complexity should be kept in the builder. I think longer-term the right answer might be to have an accumulation-based approach of some sort at execution.

We could go back to the refresh, but there might be cases where there are extra steps.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 10 of 14 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73589#-:-MqQtx7y4pQ90Idv8TXg:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/schemachanger/scplan/opgen/opgen_check_type_reference.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73589#-MqN7SsV9BMjcEGhcGNq:-MqQtlg96DkuC8yjznMS:b-4mngv2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b36605ec8b4b16acba4f3a30f541ad46ec8625f/pkg/sql/schemachanger/scplan/opgen/opgen_check_type_reference.go#L36)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

It's definitely too simplistic, and I think we started off with the refreshing approach and then moved to this one since we felt the complexity should be kept in the builder. I think longer-term the right answer might be to have an accumulation-based approach of some sort at execution.

We could go back to the refresh, but there might be cases where there are extra steps.
</blockquote></details>

Let's leave it until it pops back up. It's going to pop up as soon as we do either `DROP COLUMN` or `DROP CONSTRAINT`.

**Comment by fqazi** [comment]
@ajwerner TRTR!

**Pull request merged**
