### PR TITLE
[DO NOT MERGE] rocksdbccl: split the enterprise c++ code into the ccl tree

### PR DESCRIPTION
**Pull request by danhhz**
@petermattis There's definitely cleanup left here, but everything seems to work. Would you mind very quickly checking the overall structure and file layout before I polish it up for full review?

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13141)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/ccl/storageccl/engineccl/rocksdbccl/db.cc, line 12 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13141#-KbLwU6Vzn3rFkCifeLx:-KbLwU6Vzn3rFkCifeLy:b-2skds8) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc72f245fe1a1337a09214c5f32f0bd8a61ad129/pkg/ccl/storageccl/engineccl/rocksdbccl/db.cc#L12)):*
> ```cpp
> #include <atomic>
> #include <stdarg.h>
> #include <google/protobuf/repeated_field.h>
> ```

are all these includes necessary?

---

*[pkg/ccl/storageccl/engineccl/rocksdbccl/rocksdb.go, line 16 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13141#-KbLwHGzLO5gpjJB3l1D:-KbLwHGzLO5gpjJB3l1E:b-oywwix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc72f245fe1a1337a09214c5f32f0bd8a61ad129/pkg/ccl/storageccl/engineccl/rocksdbccl/rocksdb.go#L16)):*
> ```Go
> )
> 
> // #cgo CPPFLAGS: -I ../../../../../vendor/github.com/cockroachdb/c-protobuf/internal/src -I ../../../../../vendor/github.com/cockroachdb/c-rocksdb/internal/include -I ../../../../../pkg/storage/engine/rocksdb
> ```

consider splitting this line into 3

---

*[pkg/storage/engine/rocksdb/db.cc, line 180 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13141#-KbLwjwihPveIa1U3CJB:-KbLwjwihPveIa1U3CJC:b40l1mz) ([raw file](https://github.com/cockroachdb/cockroach/blob/43b2528042bc013eb692033ac99661a569612ec3/pkg/storage/engine/rocksdb/db.cc#L180)):*
> ```cpp
> }  // extern "C"
> 
> namespace {
> ```

why this movement?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13141)*

**Comment by danhhz** [comment]
At @bdarnell's suggestion, I'm going to leave the apache 2 code where it is, which means RocksDBSst* will be staying put. But since this is already working, I'm going leave it as is until I get @petermattis's feedback on the approach. Then use the WriteBatch c++ code to PR for real

**Comment by danhhz** [comment]
Closing this in favor of https://github.com/cockroachdb/cockroach/pull/13347

**Comment by danhhz** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/storageccl/engineccl/rocksdbccl/rocksdb.go, line 16 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13141#-KbLwHGzLO5gpjJB3l1D:-KbvD5RkvIcMpHkxFBU1:b-4npadr) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc72f245fe1a1337a09214c5f32f0bd8a61ad129/pkg/ccl/storageccl/engineccl/rocksdbccl/rocksdb.go#L16)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

consider splitting this line into 3
</blockquote></details>

In case you see that this is still there in the new version of this PR....


I tried to wrap this line with `\` suffixes, but got an error about `invalid #cgo line:`. Is there some other way I can split it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13141)*

**Comment by bdarnell** [comment]
Reviewed 7 of 12 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/storageccl/engineccl/rocksdbccl/rocksdb.go, line 16 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13141#-KbLwHGzLO5gpjJB3l1D:-KbvHAgiGsGmKitLOIK3:b-7uezwx) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc72f245fe1a1337a09214c5f32f0bd8a61ad129/pkg/ccl/storageccl/engineccl/rocksdbccl/rocksdb.go#L16)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

In case you see that this is still there in the new version of this PR....


I tried to wrap this line with `\` suffixes, but got an error about `invalid #cgo line:`. Is there some other way I can split it?
</blockquote></details>

You can have multiple `// #cgo CPPFLAGS:` lines and they will be merged. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13141)*

**Pull request closed without merging**
