### PR TITLE
opt: Make separate operators for aggregate functions

### PR DESCRIPTION
**Pull request by andy-kimball**
Aggregate functions are currently represented as Function operators. This
commit makes each aggregate function its own operator, which allows for
easier construction and pattern matching.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm:

---

Reviewed 26 of 26 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[pkg/sql/opt/memo/typing.go, line 210 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25143#-LBDYl1SE2wbzL74MOR2:-LBDYl1SE2wbzL74MOR3:byregj0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4faeb4fdb5ab5aeb6b59c7535517d55f407a4d2d/pkg/sql/opt/memo/typing.go#L210)):*
> ```Go
> 	// types (i.e. pass nil to the ReturnTyper). Aggregates with return types
> 	// that depend on argument types are handled separately.
> 	overloads := builtins.Aggregates[aggName]
> ```

This is the same code with the one in `findAggOverload`, maybe we should move that func to `memo` and export it?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25143#-:-LBDZce27DTOMUyTZmBB:bnfp4nl)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 26 of 26 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/sem/tree/overload.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25143#-LBIFKBt918gJBOE_rc_:-LBIFKBt918gJBOE_rca:b-ro7eke) ([raw file](https://github.com/cockroachdb/cockroach/blob/4faeb4fdb5ab5aeb6b59c7535517d55f407a4d2d/pkg/sql/sem/tree/overload.go#L75)):*
> ```Go
> }
> 
> // Match implements the TypeList interface.
> ```

[nit] implements -> is part of

(and below too)

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25143#-:-LBIFYim-8MyU3qCo2AW:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25143)*

**Pull request merged**
