### PR TITLE
roachtest: use the rate from the log files

### LINKED ISSUE #129113: roachtest: perturbation/metamorphic/decommission failed
roachtest.perturbation/metamorphic/decommission [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16491798?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16491798?buildTab=artifacts#/perturbation/metamorphic/decommission) on master @ [ec66ae778100724b11f1b8978c915be1bcea390c](https://github.com/cockroachdb/cockroach/commits/ec66ae778100724b11f1b8978c915be1bcea390c):

```
(assertions.go:363).Fail: 
	Error Trace:	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/admission_control_latency.go:638
	            				main/pkg/cmd/roachtest/test_runner.go:1283
	            				src/runtime/asm_amd64.s:1695
	Error:      	Received unexpected error:
	            	Get "https://35.231.165.130:26258/_admin/v1/stmtbundle/995288234538729474": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
	Test:       	perturbation/metamorphic/decommission
(require.go:1357).NoError: FailNow called
test artifacts and logs in: /artifacts/perturbation/metamorphic/decommission/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=1</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-16491798/perturbation-metamorphic-decommission/1723807305667/1723809323573)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*perturbation/metamorphic/decommission.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-41385

### LINKED ISSUE #129618: roachtest: perturbation/metamorphic/partition failed
roachtest.perturbation/metamorphic/partition [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16608083?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16608083?buildTab=artifacts#/perturbation/metamorphic/partition) on master @ [9e48858c6c8b22af4ec1159bcff6e233e7bfddff](https://github.com/cockroachdb/cockroach/commits/9e48858c6c8b22af4ec1159bcff6e233e7bfddff):

```
(assertions.go:363).Fail: 
	Error Trace:	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/admission_control_latency.go:638
	            				main/pkg/cmd/roachtest/test_runner.go:1284
	            				src/runtime/asm_amd64.s:1695
	Error:      	Received unexpected error:
	            	Get "https://35.231.224.123:26258/_admin/v1/stmtbundle/997841884304277517": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
	Test:       	perturbation/metamorphic/partition
(require.go:1357).NoError: FailNow called
test artifacts and logs in: /artifacts/perturbation/metamorphic/partition/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_runtimeAssertionsBuild=false</code>
 - <code>ROACHTEST_ssd=1</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-16608083/perturbation-metamorphic-partition/1724586298763/1724589927232)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*perturbation/metamorphic/partition.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-41619

### PR DESCRIPTION
**Pull request by andrewbaptist**
Previously we would track the throughput and latency from the listener
on the nodes directly. This had problems in certain cases and added a
new failure mode. This change switches to pulling the rate from the log
files after the test completes.

Fixes: #129618
Fixes: #129113

Epic: none

Release note: None

### CODE REVIEW

**Review by kvoli — CHANGES_REQUESTED** [review]
Left some comments. It would help understand why we're making these changes if there were an example you could share on the PR, which motivates switching from the earlier workload recording to this.

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 3 of 3 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130107#-:-O6MBJ3f3vTCvxiFSujY:byi2hnx)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @DarrylWong, and @nameisbhaskar)

___
*[`-- commits` line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130107#-O6M7_kr-1XVr7HdkHc_):*
For what test? This could apply to many of the hundreds of roachtests under `roachtest`
___
*[`-- commits` line 24 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130107#-O6M9U9gEpquXq7Tz9fE):*
Same as above, although the change is in a util file, the only user is the `admission_control_latency` test.
___
*[`-- commits` line 35 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/130107#-O6MA3072J9ouB0clFEw):*
Same as above.
___
*[`-- commits` line 37 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/130107#-O6M9ys76DyNfaKBlehi):*
nit: Previously
___
*[`-- commits` line 49 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/130107#-O6MAeHl7SLh3j5-d8vH):*
Which test?
___
*[`-- commits` line 58 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/130107#-O6MAv2YD3OqdsIV4fC7):*
For which test? This isn't done generally for all roachtests.
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 578 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130107#-O6M9GolDom7rx3uUwy2:-O6M9GolDom7rx3uUwy3:boc6dzv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba4f619ce327a37d03aca347a14a6b2fad6d3a56/pkg/cmd/roachtest/tests/admission_control_latency.go#L578)):*
> ```Go
> 	clusterMaxRate := make(chan int)
> 	m.Go(func(ctx context.Context) error {
> 		waitDuration(ctx, 3*v.fillDuration/4)
> ```

Could you add a comment explaining the variables? I understand the /4 but not the 3 *. 
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 685 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/130107#-O6MADlWDCwc0udIK1Sr:-O6MADlWDCwc0udIK1Ss:be5lrmi) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec0ed34daf8c29812d3d4ab85dacbed50ece3ca/pkg/cmd/roachtest/tests/admission_control_latency.go#L685)):*
> ```Go
> 	t.Status("T5: validating results")
> 
> 	// collect files
> ```

nit: for this and the below comment, use proper sentences.
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 73 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/130107#-O6MAzbu-CaCL3bVCIsE:-O6MAzbu-CaCL3bVCIsF:b-7kooul) ([raw file](https://github.com/cockroachdb/cockroach/blob/229219f0e30df14b85df2975c06c7011453c74a5/pkg/cmd/roachtest/tests/admission_control_latency.go#L73)):*
> ```Go
> // TODO(baptist): Add a timeline describing the test in more detail.
> type variations struct {
> 	// cluster is set up at the start of the test run
> ```

nit: period.
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 74 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/130107#-O6MAyfu5xZVk9hKcJTE:-O6MAyfu5xZVk9hKcJTF:b-v7vusq) ([raw file](https://github.com/cockroachdb/cockroach/blob/229219f0e30df14b85df2975c06c7011453c74a5/pkg/cmd/roachtest/tests/admission_control_latency.go#L74)):*
> ```Go
> type variations struct {
> 	// cluster is set up at the start of the test run
> 	cluster.Cluster
> ```

nit: I'm not sure how much value this gets us, none of the call lines are that long or tedious that it makes sense. I'm fine merging this though.

**Review by andrewbaptist — COMMENTED** [review]
TFTR

I cleaned up the commit messages and some of the logs. I also added the two tests that this fixes. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130107#-:-O6WMLDlBnFLzM8PIyoP:b-jfk1bb)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @kvoli, and @nameisbhaskar)

___
*[`-- commits` line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130107#-O6M7_kr-1XVr7HdkHc_):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

For what test? This could apply to many of the hundreds of roachtests under `roachtest`
</blockquote></details>

I added `perturbation/*` to the commit message
___
*[`-- commits` line 24 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130107#-O6M9U9gEpquXq7Tz9fE):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Same as above, although the change is in a util file, the only user is the `admission_control_latency` test.
</blockquote></details>

I clarified that this is only used in perturbation tests today, but will likely be used in other tests in the future.
___
*[`-- commits` line 35 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/130107#-O6MA3072J9ouB0clFEw):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Fixed
___
*[`-- commits` line 37 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/130107#-O6M9ys76DyNfaKBlehi):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: Previously
</blockquote></details>

Fixed
___
*[`-- commits` line 49 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/130107#-O6MAeHl7SLh3j5-d8vH):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Which test?
</blockquote></details>

Added
___
*[`-- commits` line 58 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/130107#-O6MAv2YD3OqdsIV4fC7):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

For which test? This isn't done generally for all roachtests.
</blockquote></details>

Added
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 578 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130107#-O6M9GolDom7rx3uUwy2:-O6Se_MVAOamLLxKT4ch:boxwt8w) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba4f619ce327a37d03aca347a14a6b2fad6d3a56/pkg/cmd/roachtest/tests/admission_control_latency.go#L578)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Could you add a comment explaining the variables? I understand the /4 but not the 3 *.
</blockquote></details>

I added a comment and made it more clear that this is 3/4 of the time waiting and 1/4 collecting stats.
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 685 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/130107#-O6MADlWDCwc0udIK1Sr:-O6WMBXyA4izaA05UFqK:b82yo49) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec0ed34daf8c29812d3d4ab85dacbed50ece3ca/pkg/cmd/roachtest/tests/admission_control_latency.go#L685)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: for this and the below comment, use proper sentences.
</blockquote></details>

I removed these comments, these were placeholders for me initally that I left in. They weren't necessary based on the context.
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 73 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/130107#-O6MAzbu-CaCL3bVCIsE:-O6Sg6c9EQIYmajno653:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/229219f0e30df14b85df2975c06c7011453c74a5/pkg/cmd/roachtest/tests/admission_control_latency.go#L73)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: period.
</blockquote></details>

Done
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 74 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/130107#-O6MAyfu5xZVk9hKcJTE:-O6Sg7O0BpSlzAoSMdwY:bwevpod) ([raw file](https://github.com/cockroachdb/cockroach/blob/229219f0e30df14b85df2975c06c7011453c74a5/pkg/cmd/roachtest/tests/admission_control_latency.go#L74)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: I'm not sure how much value this gets us, none of the call lines are that long or tedious that it makes sense. I'm fine merging this though.
</blockquote></details>

It was slightly annoying to have to keep referring to the cluster. It was a fairly minor change though, so I'll leave it.

**Review by kvoli — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130107#-:-O6h8H7D0RoWouSmOeYs:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist, @DarrylWong, and @nameisbhaskar)

___
*[`-- commits` line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130107#-O6M7_kr-1XVr7HdkHc_):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

I added `perturbation/*` to the commit message
</blockquote></details>

Could you also add something to the commit header, like:

`roachtest: query throughput using SQL for pertubation tests`

**Review by andrewbaptist — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130107)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DarrylWong, @kvoli, and @nameisbhaskar)

___
*[`-- commits` line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130107#-O6M7_kr-1XVr7HdkHc_):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Could you also add something to the commit header, like:

`roachtest: query throughput using SQL for pertubation tests`
</blockquote></details>

Done

**Comment by andrewbaptist** [comment]
TFTR!

bors r=kvoli

**Pull request merged**
