### PR TITLE
EnsureHost for all command, so --addr=":8080" format can be used for all command

### PR DESCRIPTION
**Pull request by es-chow**
Currently, ./cockroach quit --addr=":8080" is not work, so make change to make it work and make all command look like consistent.

### CODE REVIEW

**Comment by MBerhault** [comment]
--addr has two different meanings depending on whether we're calling a server or client command (init/start are really the only server commands).
Singe EnsureHost only modifies empty hosts, it's technically ok, but I'm worried that a default of localhost for clients is a bit extreme.

If this is purely for the sake of consistency across commands, then we might as well remove --addr in client commands. We will ultimately want a more fully specified URL.

**Comment by bdarnell** [comment]
@MBerhault: we already have a default of localhost for clients; this change just moves it from the `kv` subcommand to a more central place where it applies to all client commands. Given the precedent set by other databases (mysql, postgresql, and mongodb all default to localhost), we should probably do the same.

I agree that in the long run we should refactor things so that clients take something more url-like (see the TODO in kv.go about users) while servers get a raw ip:port pair, but for now this LGTM.

**Comment by MBerhault** [comment]
Fair enough. I'll probably be changing the --addr flag for client calls, but even then, it seems ok to call EnsureHost on that part of the URL.
LGTM.

**Comment by es-chow** [comment]
Can we merge?

**Comment by tschottdorf** [comment]
yes, go for it.

**Pull request merged**
