### PR TITLE
vendor: bump Pebble to c06e0793dbf5; mark pre-Pebblev1 tables

### LINKED ISSUE #82678: storage: remove support for table properties
**Is your feature request related to a problem? Please describe.**

With the addition of block properties in 22.1, table-level properties are effectively obsolete, and we should consider removing support for them entirely.

There has been some work done to-date (see #82658) to cease writing table properties entirely. This issue tracks the sequence of migrations required in order to be able to remove the dependence on the Pebble feature entirely.

**Describe the solution you'd like**

Removal would most likely need to happen in stages.

In one release (say 22.2) we stop writing them into new sstables, while somehow "marking" existing sstables for re-writing. Some of the marked sstables will be re-written as part of the natural compaction process, but some files may linger.

In a subsequent release (say 23.1), we'd require something like a blocking migration that ensures that all existing, marked sstables have been removed from the LSM before finalizing the version upgrade. A naive rewrite of all existing marked files could be prohibitively expensive, so we may need to reconsider how we'd re-write such files.

**Describe alternatives you've considered**

Continue to support both table and block properties. To codepaths would need to be maintained. From a maintenance perspective this is sub-optimal.

Jira issue: CRDB-16562

Epic CRDB-2624

### PR DESCRIPTION
**Pull request by nicktrav**
Bump the Pebble version:

```
c06e0793 db: add format major versions and migrations for min table format
f0edf9c7 manifest: make `FileMetadata.Compacting` an enum
bce4897b db: skip TestCompactFlushQueuedMemTableAndFlushMetrics on windows
67f552b7 internal/rangekey: enforce iterator bounds beneath defragmentation
```

Add a migration that bumps the Pebble format major version to
`FormatPrePebblev1Marked`. This version first ratchets the minimum
supported SSTable format to `(Pebble,v1)` (block properties), and then
marks all existing SSTables with versions pre-`(Pebble,v1)` for a
rewrite-compaction. The blocking migration to compact all such files is
deferred to a subsequent release of Cockroach (likely 23.1).

Release note: None.

### CODE REVIEW

**Comment by nicktrav** [comment]
Oof - this patch seems to be quite broken. I'm going to strip out the version upgrade piece and see if that helps.

**Comment by nicktrav** [comment]
I forgot a couple lines as part of the migration code. Pushed a fixed to re-test.

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85992#-:-N9E-eDADFq4JaBa3S4q:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nicktrav)

**Comment by nicktrav** [comment]
TFTR!

bors r=jbowens

**Pull request merged**
