### PR TITLE
client: Proper timestamp initialization in aborted txns

### LINKED ISSUE #5588: sql: failure running SQL benchmarks
```
panic: zero transaction timestamp in EvalContext

goroutine 13571 [running]:
panic(0x4edb180, 0xc856f44bb0)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/cockroachdb/cockroach/sql/parser.(*EvalContext).GetTxnTimestamp(0xc849f62fc0, 0x0, 0x0)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/sql/parser/eval.go:777 +0xa8
github.com/cockroachdb/cockroach/sql/parser.glob.func91(0x1, 0xece87ee50, 0x234836b7, 0x5df39a0, 0x0, 0x0, 0xc842e15ec0, 0xc828526350, 0x0, 0x0, ...)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/sql/parser/builtins.go:1098 +0x54
github.com/cockroachdb/cockroach/sql/parser.(*FuncExpr).Eval(0xc82a952480, 0x1, 0xece87ee50, 0x234836b7, 0x5df39a0, 0x0, 0x0, 0xc842e15ec0, 0xc828526350, 0x0, ...)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/sql/parser/eval.go:1185 +0x53f
github.com/cockroachdb/cockroach/sql/parser.evalExprs(0x1, 0xece87ee50, 0x234836b7, 0x5df39a0, 0x0, 0x0, 0xc842e15ec0, 0xc828526350, 0x0, 0x0, ...)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/sql/parser/eval.go:1428 +0x138
github.com/cockroachdb/cockroach/sql/parser.(*Tuple).Eval(0xc849f63550, 0x1, 0xece87ee50, 0x234836b7, 0x5df39a0, 0x0, 0x0, 0xc842e15ec0, 0xc828526350, 0x0, ...)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/sql/parser/eval.go:1444 +0x7b
github.com/cockroachdb/cockroach/sql.(*planner).ValuesClause(0xc835346078, 0xc84123dae0, 0x0, 0x0, 0x1)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/sql/values.go:70 +0x8b3
github.com/cockroachdb/cockroach/sql.(*planner).makePlan(0xc835346078, 0x7219480, 0xc84123dae0, 0x7219400, 0x0, 0x0, 0xa)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/sql/plan.go:268 +0xb99
github.com/cockroachdb/cockroach/sql.(*planner).Insert(0xc835346078, 0xc856f78780, 0xe984f100, 0x0, 0x0, 0x51a6ea8)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/sql/insert.go:116 +0x9cd
github.com/cockroachdb/cockroach/sql.(*planner).makePlan(0xc835346078, 0x7219338, 0xc856f78780, 0xc82644cc00, 0x0, 0x0, 0x12e4)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/sql/plan.go:220 +0x1313
github.com/cockroachdb/cockroach/sql.(*Executor).execStmt(0xc8213562a0, 0x7219338, 0xc856f78780, 0xc835346078, 0xece87ee50, 0xc8234843c6, 0x5df39a0, 0x0, 0x0, 0x0, ...)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/sql/executor.go:867 +0x89
github.com/cockroachdb/cockroach/sql.(*Executor).execStmtInOpenTxn(0xc8213562a0, 0x7219338, 0xc856f78780, 0xc835346078, 0x0, 0x143f44946e8d56b7, 0x0, 0xc835346028, 0x0, 0x0, ...)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/sql/executor.go:774 +0x542
github.com/cockroachdb/cockroach/sql.(*Executor).execStmtsInCurrentTxn(0xc8213562a0, 0xc821f64d00, 0x7, 0x8, 0xc835346078, 0xc835346028, 0x100, 0x0, 0x0, 0x0, ...)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/sql/executor.go:556 +0x630
github.com/cockroachdb/cockroach/sql.runTxnAttempt(0xc8213562a0, 0xc835346078, 0x1, 0xc835346028, 0xc84123dfa0, 0xc821f64d00, 0x7, 0x8, 0xc849f65448, 0xc849f65460, ...)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/sql/executor.go:488 +0x147
github.com/cockroachdb/cockroach/sql.(*Executor).execRequest.func1(0xc82814b2c0, 0xc84123dfa0, 0xc82814b2c0)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/sql/executor.go:401 +0x325
github.com/cockroachdb/cockroach/client.(*Txn).Exec(0xc82814b2c0, 0x52a0001, 0x143f44946b262293, 0x0, 0xc849f65558, 0x0)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/client/txn.go:495 +0x410
github.com/cockroachdb/cockroach/sql.(*Executor).execRequest(0xc8213562a0, 0xc835346000, 0xc856f77000, 0x17e, 0x0, 0x0, 0x0, 0x1000)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/sql/executor.go:405 +0x8a5
github.com/cockroachdb/cockroach/sql.(*Executor).ExecuteStatements(0xc8213562a0, 0xc835346000, 0xc856f77000, 0x17e, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/sql/executor.go:294 +0xbe
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).executeStatements(0xc82096a900, 0xc856f77000, 0x17e, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2a952201, ...)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:592 +0x98
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc82096a900, 0xc82096a928, 0x0, 0x0)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:303 +0xcd
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).serve(0xc82096a900, 0xc8485486e0, 0x0, 0x0)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:263 +0xf8a
github.com/cockroachdb/cockroach/sql/pgwire.(*Server).ServeConn(0xc82047a058, 0x7219e70, 0xc848888600, 0x0, 0x0)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/sql/pgwire/server.go:157 +0x8df
github.com/cockroachdb/cockroach/server.(*Server).Start.func4.1(0x7219918, 0xc826392160)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/server/server.go:300 +0x4b
github.com/cockroachdb/cockroach/util.ServeHandler.func3.1(0xc824b51700, 0x7219918, 0xc826392160, 0xc84c2b6010)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/util/net.go:125 +0x5a
created by github.com/cockroachdb/cockroach/util.ServeHandler.func3
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/util/net.go:127 +0x31f
```

### PR DESCRIPTION
**Pull request by knz**
Fixes #5588.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5776)

### CODE REVIEW

**Comment by andreimatei** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/txn.go, line 526 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5776#-KED2Vd1JODWeXBo8hl7:-KED2Vd1JODWeXBo8hl8:-1868844391) ([raw file](https://github.com/cockroachdb/cockroach/blob/8682fe8ebc5106420b38e4eda9b40d81e35def04/client/txn.go#L526)):*
should this be a method on `client.Txn`, say, `SetMinInitialTimestamp()`, and make it the `Txn`'s responsibility to maintain it as it receives updated protos from the `send` functions?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5776)*

**Comment by knz** [comment]
Tests are in.

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/txn.go, line 526 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5776#-KED2Vd1JODWeXBo8hl7:-KEDs7Q6qsK1az2X9DwE:605592929) ([raw file](https://github.com/cockroachdb/cockroach/blob/8682fe8ebc5106420b38e4eda9b40d81e35def04/client/txn.go#L526)):*
This sounds better than what you can achieve: you need the TxnExecOptions to do this and this is only known in Exec.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5776#-:-KEDs56uHf4yAczmWwjZ:-448874535)*

**Comment by andreimatei** [comment]
:lgtm: 

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/txn.go, line 526 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5776#-KED2Vd1JODWeXBo8hl7:-KEhc-_8FiWB7IKXgD5B:-1790169231) ([raw file](https://github.com/cockroachdb/cockroach/blob/8682fe8ebc5106420b38e4eda9b40d81e35def04/client/txn.go#L526)):*
I'm saying that instead of `MinInitialTimestamp` being a field on `opt`, it can be passed to a separate method on the `client.Txn`, which needs to be called before `Exec()` is called.

---

*[sql/txn_restart_test.go, line 218 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5776#-KEhbi8fAKFAk0OeZB5j:-KEhbi8fAKFAk0OeZB5k:-64216825) ([raw file](https://github.com/cockroachdb/cockroach/blob/c58032bca74f9e35a916a92111ede37693aaf337/sql/txn_restart_test.go#L218)):*
do you need the changes to this test? I don't see you testing anything with the new columns?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5776#-:-KEhcVm1Ow0qPxZn_0cK:980077423)*

**Comment by knz** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[client/txn.go, line 526 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5776#-KED2Vd1JODWeXBo8hl7:-KEhgVhqYydPxl3dRUMP:-1267152760) ([raw file](https://github.com/cockroachdb/cockroach/blob/8682fe8ebc5106420b38e4eda9b40d81e35def04/client/txn.go#L526)):*
We still need to store the MinInitialTimestamp somewhere else than the txn object, because the txn object may get reinitialized between retries within Exec. The question is then -- where? the ExecOptions seems to be the only reliable place to keep this between retries.

---

*[sql/txn_restart_test.go, line 218 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5776#-KEhbi8fAKFAk0OeZB5j:-KEhh0kUQ7J1UezoFOuw:642150524) ([raw file](https://github.com/cockroachdb/cockroach/blob/c58032bca74f9e35a916a92111ede37693aaf337/sql/txn_restart_test.go#L218)):*
There is a test, see below. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5776)*

**Comment by andreimatei** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/txn.go, line 526 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5776#-KED2Vd1JODWeXBo8hl7:-KEhhYzZ8LvBSr5aGdB4:-1577215472) ([raw file](https://github.com/cockroachdb/cockroach/blob/8682fe8ebc5106420b38e4eda9b40d81e35def04/client/txn.go#L526)):*
the proto gets reinitialized, not the client.Txn object.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5776)*

**Comment by knz** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/txn.go, line 526 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5776#-KED2Vd1JODWeXBo8hl7:-KEhpmgi9KYQmOcEJgJu:205841116) ([raw file](https://github.com/cockroachdb/cockroach/blob/8682fe8ebc5106420b38e4eda9b40d81e35def04/client/txn.go#L526)):*
Ok now I understand. Done.

---

*[sql/txn_restart_test.go, line 253 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5776#-KEhpqDYnGH4I4jG3uaT:-KEhpqDYnGH4I4jG3uaU:-116428664) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d0d77552d33ddbb846f38279c761a40752e08a5/sql/txn_restart_test.go#L253)):*
Comment added as requested.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5776)*

**Comment by knz** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[client/txn.go, line 526 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5776#-KED2Vd1JODWeXBo8hl7:-KEkVPK051GCK5JgCLbi:520347781) ([raw file](https://github.com/cockroachdb/cockroach/blob/8682fe8ebc5106420b38e4eda9b40d81e35def04/client/txn.go#L526)):*
Actually no this doesn't work :) Because of user-directed retries, the txn object may be rejected. The only thing that is preserved across retries is the txnState, but that one is invisible from txn.Exec. So ExecOptions it goes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5776)*

**Comment by andreimatei** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/txn.go, line 526 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5776#-KED2Vd1JODWeXBo8hl7:-KEl7LCAqNMph1CGFX12:-660007939) ([raw file](https://github.com/cockroachdb/cockroach/blob/8682fe8ebc5106420b38e4eda9b40d81e35def04/client/txn.go#L526)):*
but the `txnState` has (and owns) a `*client.Txn`, which I think sticks around for the duration of the whole SQL transaction (including user retries). What gets rejected?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5776)*

**Comment by knz** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/txn.go, line 526 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5776#-KED2Vd1JODWeXBo8hl7:-KEl8nMX4A6M8n3GTTwS:791316855) ([raw file](https://github.com/cockroachdb/cockroach/blob/8682fe8ebc5106420b38e4eda9b40d81e35def04/client/txn.go#L526)):*
What you say here does not appear to be accurate. When I implement the way you suggest (placing the mininitialtimestamp in the txn object) then TestTxnUserRetries fails. That's how I drew my conclusion above. I am not sure of the reason why, but I reckon you would?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5776)*

**Comment by andreimatei** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/txn.go, line 526 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5776#-KED2Vd1JODWeXBo8hl7:-KElFsS3B0yVbMo5_wpC:1070820472) ([raw file](https://github.com/cockroachdb/cockroach/blob/8682fe8ebc5106420b38e4eda9b40d81e35def04/client/txn.go#L526)):*
if you give me a test showing two different instances of client.Txn (for example, `log.Infof("%p", txn)` within the same sql transaction, I'll debug :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5776)*

**Comment by knz** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/txn.go, line 526 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5776#-KED2Vd1JODWeXBo8hl7:-KElH1Zs4xVNcd164ZHN:455665265) ([raw file](https://github.com/cockroachdb/cockroach/blob/8682fe8ebc5106420b38e4eda9b40d81e35def04/client/txn.go#L526)):*
Ok but then I want to do this as a separate issue: #5920. 
The problem I see is that "make bench" is currently broken, this PR proposes a working fix available today and the solution you'd like to implement requires an unclear amount of time to get right / troubleshoot.  Let's decouple.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5776)*

**Comment by knz** [comment]
Merging with approval from @andreimatei

**Pull request merged**
