### PR TITLE
ts: Collect metrics on time series system

### LINKED ISSUE #9386: monitoring: metrics for tsdb activity
It would be nice to have a few metrics about the amount of data flowing in and out of our internal tsdb.

Not knowing that part of the code, these are just suggestions:
- number of metric entries written per node/store
- size (key and value) of metrics per node/store
- separate original metric write and rewrite (from upcoming culling: #9343)

### PR DESCRIPTION
**Pull request by mrtracy**
Begin collecting metrics on the activity of the time series system.
Currently only three metrics are collected:

+ Total samples written.
+ Total bytes written at the KV layer (not equal to actual disk usage,
which is highly compressed).
+ Total count of errors when writing.

Added two new graphs on the "storage" dashboard with these charts.

Resolves #9386

Release note: Added new graphs for monitoring activity of the time
series system.

screen shot 2018-02-13 at 7 32 48 pm

### CODE REVIEW

**Comment by couchand** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/ts/db.go, line 197 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22672#-L5K6J4nVyvpupeztk6m:-L5K6J4nVyvpupeztk6n:bypi0c4) ([raw file](https://github.com/cockroachdb/cockroach/blob/57138a912624509235ae41da756e79d7e6e14cc8/pkg/ts/db.go#L197)):*
> ```Go
> 			})
> 			totalSamples += int64(len(idata.Samples))
> 			totalSizeOfKvs += int64(len(value.RawBytes)+len(key)) + sizeOfTimestamp
> ```

I'm confused where `sizeOfTimestamp` fits in here.  Isn't the timestamp already included in `len(key)`?

---

*[pkg/ts/resolution.go, line 48 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22672#-L5K4Q1uVAi58sCNfSRy:-L5K4Q1v7_DyCxF68XaB:b-ftj914) ([raw file](https://github.com/cockroachdb/cockroach/blob/57138a912624509235ae41da756e79d7e6e14cc8/pkg/ts/resolution.go#L48)):*
> ```Go
> 	// resolutionInvalid is an invalid resolution used only for testing. It causes
> 	// an error to be thrown in certain methods. It is invalid because its sample
> 	// period does not a divisor of its slab period.
> ```

"is not"

---

*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/storage.tsx, line 132 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22672#-L5K5HPV7GqG46LinZSL:-L5K5HPV7GqG46LinZSM:bo9fso2) ([raw file](https://github.com/cockroachdb/cockroach/blob/57138a912624509235ae41da756e79d7e6e14cc8/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/storage.tsx#L132)):*
> ```XML
>       sources={nodeSources}
>       tooltip={
>         `The number of bytes written by the time series system per second ${tooltipSelection}.`
> ```

I fear that if this doesn't clearly state that it isn't the number of bytes that end up on disk, we'll get bug reports about the mismatch, but maybe I'm overly concerned there.  This also makes me curious about your previous PR adding timeseries info to the databases page -- is that real disk usage?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22672)*

**Comment by bdarnell** [comment]
:lgtm:

> + Total bytes written at the KV layer (not equal to actual disk usage,
which is highly compressed).

The difference is not just compression - the disk usage is also subject to eventual GC, so the storage size will plateau even as this counter increases indefinitely. 

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22672#-:-L5KCit2y__q5W9GuQwg:b-o4ntqz)*

**Comment by mrtracy** [comment]
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/ts/db.go, line 197 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22672#-L5K6J4nVyvpupeztk6m:-L5L04htB2Z7xypGz7WV:b1hwgwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/57138a912624509235ae41da756e79d7e6e14cc8/pkg/ts/db.go#L197)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

I'm confused where `sizeOfTimestamp` fits in here.  Isn't the timestamp already included in `len(key)`?
</blockquote></details>

It's also in the `Value` itself; Value has RawBytes and a timestamp field.

---

*[pkg/ts/resolution.go, line 48 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22672#-L5K4Q1uVAi58sCNfSRy:-L5L0JO7JnzzR7MjO5En:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/57138a912624509235ae41da756e79d7e6e14cc8/pkg/ts/resolution.go#L48)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

"is not"
</blockquote></details>

Done.

---

*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/storage.tsx, line 132 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22672#-L5K5HPV7GqG46LinZSL:-L5L6IvhPQ677KonQfgy:b-pmezk4) ([raw file](https://github.com/cockroachdb/cockroach/blob/57138a912624509235ae41da756e79d7e6e14cc8/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/storage.tsx#L132)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

I fear that if this doesn't clearly state that it isn't the number of bytes that end up on disk, we'll get bug reports about the mismatch, but maybe I'm overly concerned there.  This also makes me curious about your previous PR adding timeseries info to the databases page -- is that real disk usage?
</blockquote></details>

I overhauled this comment a bit to be more descriptive of what it is, and what the relationship is to disk usage.

And yes, the disk usage on the databases page is real disk usage.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22672)*

**Comment by couchand** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22672#-:-L5L86QNwN2eFwsntRWq:bnfp4nl)*

**Pull request merged**
