### PR TITLE
parser: TableNameWithIndex cleanups

### PR DESCRIPTION
**Pull request by RaduBerinde**
The `SearchTable` stuff had me scratching my head for a while..

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14370)

### CODE REVIEW

**Comment by knz** [comment]
Huh can you motivate the removal of the pointer type? What you are doing here is making our parser sqlSymUnion bigger, which ... tends to hurt performance.

**Comment by RaduBerinde** [comment]
What am I making bigger? `sqlSymUnion` contains just an interface. If anything, we should be saving some allocations (though it won't matter, common statements wouldn't be affected). The vast majority of the similar things (like `NormalizableTableName`) are not pointers. I don't see the reasoning why this should be a pointer and the others not.

**Comment by knz** [comment]
@nvanbenschoten can you remind us what you explained to me last time about this? I forgot the argument.

**Comment by mjibson** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/drop.go, line 237 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14370#-KgDEUWH19pq_ztJIpgM:-KgDEUWH19pq_ztJIpgN:b9i9cbv) ([raw file](https://github.com/cockroachdb/cockroach/blob/41f47f46f9506c4a999da8f845c8c89ada02ea2a/pkg/sql/drop.go#L237)):*
> ```Go
> func (p *planner) DropIndex(ctx context.Context, n *parser.DropIndex) (planNode, error) {
> 	idxNames := make([]fullIndexName, len(n.IndexList))
> 	for i, index := range n.IndexList {
> ```

Why is `index` being removed?

---

*[pkg/sql/split_at.go, line 34 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14370#-KgDEYJ83nwS7SGkJejS:-KgDEYJ83nwS7SGkJejT:b-k9skuy) ([raw file](https://github.com/cockroachdb/cockroach/blob/14ec2498f405c5c2430cf1642a0676c0d4590c2a/pkg/sql/split_at.go#L34)):*
> ```Go
> 	var tn *parser.TableName
> 	var err error
> 	if n.Table.TableNameReference != nil {
> ```

Why is this better?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14370)*

**Comment by nvanbenschoten** [comment]
This isn't making the `sqlSymUnion` bigger, but it's also not saving any allocations because stuffing a (non-empty) struct inside an interface forces an alloc to provide the indirection. To be honest, I don't really see much of a benefit to the second commit, but if you think it makes things more consistent, I'm fine with it.

---

Reviewed 3 of 3 files at r1, 1 of 8 files at r2.
Review status: 1 of 8 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/drop.go, line 237 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14370#-KgDEUWH19pq_ztJIpgM:-KgDitiyyMmRDhPkMW22:bo5ufw0) ([raw file](https://github.com/cockroachdb/cockroach/blob/41f47f46f9506c4a999da8f845c8c89ada02ea2a/pkg/sql/drop.go#L237)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Why is `index` being removed?
</blockquote></details>

Because `TableNameWithIndexList` doesn't hold a slice of pointers anymore, so we need to do something like `&n.IndexList[i]` to pass a reference to the slice element itself, instead of a copy.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14370#-:-KgDgnCD_Ntn3_JjMnog:b-t1biqs)*

**Comment by RaduBerinde** [comment]
I wasn't trying to optimize (like I said, it doesn't matter given what statements use this); the main thing that bothers me is the inconsistency between `n.Index` and `n.Table`. Exactly one of them should be set; why should one be a pointer and one not? I am adding more nodes similar to splitNode (for `SHOW RANGES`, `TESTING_RELOCATE`, `SCATTER`) and I'd rather not carry over this weirdness.. If folks are against it, I can drop it though.

---

Review status: 1 of 8 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14370#-:-KgEtNyeFko4PQKrogfa:bfqcee0)*

**Comment by RaduBerinde** [comment]
To be more specific - at first when I saw `Table` and `*Index`, I assumed `Table` is always set and `Index` is optional (which made sense at a high level). Then I realized `Index` also contains a table name and I was confused, and it took me a bit to figure out that actually exactly one of them is set. Maybe just some comments would be enough to avoid this confusion. But it looked like the only reason it was a pointer in the first place was so we could compare it to `nil`, but we don't need that (we can just as easily check if `Table` is unset).

---

Review status: 1 of 8 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14370#-:-KgEyddRs_8ISdIGoW-s:b-k2yvfj)*

**Comment by knz** [comment]
Thanks for the explanation. Yes, this makes plenty of sense. (Although by your argument both things could have become pointers,  but I don't care much.) I'm good with the rest of the change.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by RaduBerinde** [comment]
I don't have a problem with making both pointers if you think that makes more sense. (I didn't choose that route because a lot more things are using a table)

**Comment by RaduBerinde** [comment]
Ok, it looks like we are already using both `Table` and `*Table` in our syntax, so switching the Table over to be a pointer is easier. The change is much more trivial now.

**Review by madelynnblue — APPROVED** [review]

**Pull request merged**
