### PR TITLE
sql: Sequelize fixes

### PR DESCRIPTION
**Pull request by cuongdo**
These fixes make basic Sequelize CRUD operations work, except for upsert.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13484)

### CODE REVIEW

**Comment by jordanlewis** [comment]
Reviewed 2 of 2 files at r1.
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/pg_catalog.go, line 817 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-KcTd4as5YBPAgiPGb1j:-KcTd4as5YBPAgiPGb1k:b-686x8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ac77e61b6faa1c12d09007c87b6a470eb627366/pkg/sql/pg_catalog.go#L817)):*
> ```Go
>     indislive BOOL,
>     indisreplident BOOL,
>     indkey STRING,
> ```

Nice idea! I... don't think that we should merge this, though. It may fix things for Sequelize, but int2vectors in Postgres are arrays - and because they are arrays, there's a lot of external code that uses them as arrays. I don't think we should do a quick fix for Sequelize and break a ton of other postgres compatible code.

For example, here's code within PGJDBC that assumes that indkey is an array: https://github.com/pgjdbc/pgjdbc/search?utf8=%E2%9C%93&q=indkey

And Django: https://github.com/django/django/blob/90db4bb0d72e4731052bd33500840fff00834768/django/db/backends/postgresql/introspection.py#L42

And some other kind of crazy looking PHP/wordpress thing: https://github.com/mfukano/wp-heroku/blob/a057cbeaf54297871c7cea7da73578fb3c6a4f12/wp-content/pg4wp/driver_pgsql_install.php#L99

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484)*

**Comment by cuongdo** [comment]
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/pg_catalog.go, line 817 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-KcTd4as5YBPAgiPGb1j:-KcTo2bfz097aSqD7cOe:byoxgrq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ac77e61b6faa1c12d09007c87b6a470eb627366/pkg/sql/pg_catalog.go#L817)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Nice idea! I... don't think that we should merge this, though. It may fix things for Sequelize, but int2vectors in Postgres are arrays - and because they are arrays, there's a lot of external code that uses them as arrays. I don't think we should do a quick fix for Sequelize and break a ton of other postgres compatible code.

For example, here's code within PGJDBC that assumes that indkey is an array: https://github.com/pgjdbc/pgjdbc/search?utf8=%E2%9C%93&q=indkey

And Django: https://github.com/django/django/blob/90db4bb0d72e4731052bd33500840fff00834768/django/db/backends/postgresql/introspection.py#L42

And some other kind of crazy looking PHP/wordpress thing: https://github.com/mfukano/wp-heroku/blob/a057cbeaf54297871c7cea7da73578fb3c6a4f12/wp-content/pg4wp/driver_pgsql_install.php#L99
</blockquote></details>

I believe there are other, harder issues blocking Django, and I'm not clear how that specific code in PGJDBC gets executed (my tests haven't hit that code yet). That said, I'll see what it takes to support this in a better way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484)*

**Comment by jordanlewis** [comment]
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/pg_catalog.go, line 817 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-KcTd4as5YBPAgiPGb1j:-KcTrhzHbD7sFss1vD8X:b6id9pe) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ac77e61b6faa1c12d09007c87b6a470eb627366/pkg/sql/pg_catalog.go#L817)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

I believe there are other, harder issues blocking Django, and I'm not clear how that specific code in PGJDBC gets executed (my tests haven't hit that code yet). That said, I'll see what it takes to support this in a better way.
</blockquote></details>

Agreed that this isn't the first failure in either PGJDBC or Django, but my point was just that there's a lot of code that already relies on `indkey` being an array out there on GitHub - and it would be a shame to break all of that now. I could be convinced that that's the right move, if it's too hard to do otherwise - it just wouldn't be my first choice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484)*

**Comment by cuongdo** [comment]
Rebased and introduced a new `INT2VECTOR` column type only usable by virtual tables. It seems that OIDs for result rows are tied to the column type. 

@nvanbenschoten Are there simpler ways to introduce a different serialization format for `Datum`s that use `DOidWrapper`? Or is this the best way to do this?

**Comment by cuongdo** [comment]
To confirm my understanding, it looks like `pgwire.(*writeBuffer).writeTextDatum` serializes the result. It's passed a `sql.ResultColumn`, which is created by `sql.makeResultColumns`. `makeResultColumns` takes a `[]ColumnDescriptor` as its only parameter, so unless we make deeper changes, the serialization of all outgoing `Datum`s is tied to the `ColumnDescriptor`. Unless I'm missing something?

**Comment by jordanlewis** [comment]
From what I recall when I was testing Sequelize, I believe that Sequelize will be happy as long as the output column in question is sent with an int2vector OID. In other words, I don't think we need to worry about the data appearing in the int2vector format in `./cockroach sql`.

You can test my belief by temporarily changing the switch in `tArray.Oid()` in `type.go` to return `T_int2vector` for `TypeInt` instead of `T__int8`.

---

Review status: 2 of 19 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-:-KcYpKnd1zLFdmP7O8qJ:b-8wgc4h)*

**Comment by cuongdo** [comment]
Regardless, I don't believe I can affect the OID of the outgoing column
without changing the ColumnDescriptor.

**Comment by cuongdo** [comment]
@jordanlewis You are right that if I return `T_int2vector` from `tArray.Oid()`, Sequelize seems to do the right thing (though I'm not clear *how* it's doing that). So, that would allow me to get rid of the `pgwire` changes. That still doesn't avoid the need to make some kind of change to the `ColumnDescriptor` for `indkey` to modify the OID.

---

Review status: 2 of 19 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-:-KcZG8w1xXyVR1GpAgVj:brv05i4)*

**Comment by cuongdo** [comment]
Also, I'm going to leave the serialization changes in. This line from Sequelize depends on the fact that `indkey` has spaces rather than commas:

https://github.com/sequelize/sequelize/blob/v3/lib/dialects/postgres/query.js#L150

While it doesn't complain when it receives a string like `{2,3}`, it's still doing the wrong thing silently.

---

Review status: 2 of 19 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-:-KcZLAk0G_590Sgt4IN_:bir6lrb)*

**Comment by nvanbenschoten** [comment]
Nice job tackling this!

---

Reviewed 2 of 2 files at r1, 3 of 3 files at r3, 17 of 17 files at r4.
Review status: all files reviewed at latest revision, 13 unresolved discussions, all commit checks successful.

---

*[pkg/sql/create.go, line 1160 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-Kc_iOSoZYPtBiDAKWml:-Kc_iOSoZYPtBiDAKWmm:b-twrixz) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a4d3042b22203a9759954d4358f5517e8c6cb8/pkg/sql/create.go#L1160)):*
> ```Go
> 			if !desc.IsVirtualTable() {
> 				if _, ok := d.Type.(*parser.ArrayColType); ok {
> 					return desc, util.UnimplementedWithIssueErrorf(2115, "ARRAY and INT2VECTOR column types are unsupported")
> ```

Throughout: "array" should correspond to "vector", because we're referring to a generic data type. So ` s/INT2VECTOR/VECTOR/`

---

*[pkg/sql/pg_catalog.go, line 828 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-Kc_jJP6TqX6V6NRWuNu:-Kc_jJP6TqX6V6NRWuNv:bek1s0h) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a4d3042b22203a9759954d4358f5517e8c6cb8/pkg/sql/pg_catalog.go#L828)):*
> ```Go
> 						}
> 					}
> 					indkeyArr, err := colIDArrayToDatum(index.ColumnIDs)
> ```

Let's change this to `colIDArrayToArray` and change the signature to return a `*parser.DArray`. Then we can create a new function right below it called `colIDArrayToVector` that performs this wrapping.

---

*[pkg/sql/show.go, line 171 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-Kc_djW7z3TpqJ8ayhJM:-Kc_djW7z3TpqJ8ayhJN:b-qemyia) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad21cfa1039bbd86a012931ef852c60e4442500e/pkg/sql/show.go#L171)):*
> ```Go
> 		}
> 	default:
> 		if _, ok := varGen[name]; !ok {
> ```

Why not just change the names in `varGen` to be lower case and switch `name := strings.ToUpper(n.Name)` to `name := strings.ToLower(n.Name)`. Will that break anything other than forcing a few more test changes?

---

*[pkg/sql/parser/col_types.go, line 328 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-Kc_fC53pe1sKisX657d:-Kc_fC53pe1sKisX657e:b-mue4cx) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a4d3042b22203a9759954d4358f5517e8c6cb8/pkg/sql/parser/col_types.go#L328)):*
> ```Go
> }
> 
> var int2vectorColType = &ArrayColType{
> ```

This was the approach I initially took with `NameColType` and `OidColType`. I would strongly suggest we create a new `ColumnType` implementation instead. The `if ct.Name == "INT2VECTOR" {` special cases are both ugly and fragile.

---

*[pkg/sql/parser/datum.go, line 2012 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-Kc_ej41nB9LVYJVzSgB:-Kc_ej41nB9LVYJVzSgC:b-m3pmj2) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a4d3042b22203a9759954d4358f5517e8c6cb8/pkg/sql/parser/datum.go#L2012)):*
> ```Go
> 		panic(fmt.Errorf("cannot wrap %T with an Oid", v))
> 	default:
> 		// Currently only *DInt and *DString are hooked up to work with *DOidWrapper.
> ```

For `DOidWrapper` support of `*DArray`, we're going to need to honor this comment. That means replacing all `.(*DArray)` type assertions with corresponding function calls implemented in the style of `AsDInt` and `MustBeDInt`.

---

*[pkg/sql/parser/datum.go, line 2159 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-Kc_eVfxgHTjesBmprVe:-Kc_eVfxgHTjesBmprVf:bajyyl3) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a4d3042b22203a9759954d4358f5517e8c6cb8/pkg/sql/parser/datum.go#L2159)):*
> ```Go
> }
> 
> // NewDIntVectorFromDArray is a helper routine to create a *DIntVector
> ```

let's move this up below `NewDOid`

---

*[pkg/sql/pgwire/types.go, line 181 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-Kc_g7kMHYk26WbgIwh0:-Kc_g7kMHYk26WbgIwh1:bok4h80) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a4d3042b22203a9759954d4358f5517e8c6cb8/pkg/sql/pgwire/types.go#L181)):*
> ```Go
> 
> 	case *parser.DArray:
> 		if w, ok := d.(*parser.DOidWrapper); ok {
> ```

I'd turn this into a `switch` statement based on the OID of `d` (`d.ResolvedType().OID()`) directly so that we don't need the checked type assertion.

---

*[pkg/sql/pgwire/types.go, line 185 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-Kc_gSVrD_LP0mjTTafL:-Kc_gSVrD_LP0mjTTafM:b79mpju) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a4d3042b22203a9759954d4358f5517e8c6cb8/pkg/sql/pgwire/types.go#L185)):*
> ```Go
> 			case oid.T_int2vector:
> 				// int2vectors are serialized as a string of space-separated values.
> 				a := w.Wrapped.(*parser.DArray)
> ```

`v` is already this array

---

*[pkg/sql/sqlbase/structured.go, line 1670 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-Kc_hkRoiyqLj_uJbbpl:-Kc_hkRoiyqLj_uJbbpm:b124lsw) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a4d3042b22203a9759954d4358f5517e8c6cb8/pkg/sql/sqlbase/structured.go#L1670)):*
> ```Go
> 	case parser.TypeInterval:
> 		ctyp.Kind = ColumnType_INTERVAL
> 	case parser.TypeIntVector:
> ```

nit: move to below `parser.TypeIntArray`.

---

*[pkg/sql/sqlbase/structured.go, line 1720 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-Kc_ho24ysCFz9RPkZRX:-Kc_ho24ysCFz9RPkZRY:bb7od0r) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a4d3042b22203a9759954d4358f5517e8c6cb8/pkg/sql/sqlbase/structured.go#L1720)):*
> ```Go
> 	case ColumnType_OID:
> 		return parser.TypeOid
> 	case ColumnType_INT2VECTOR:
> ```

same

---

*[pkg/sql/sqlbase/structured.proto, line 44 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-Kc_hqW5pKeym_hnJ4wk:-Kc_hqW5pKeym_hnJ4wl:b-4740n5) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a4d3042b22203a9759954d4358f5517e8c6cb8/pkg/sql/sqlbase/structured.proto#L44)):*
> ```protobuf
>     NAME = 11;
>     OID = 12;
>     INT2VECTOR = 13;
> ```

Let's do something similar to below. Make this `= 120` or something so that if/when we decide on a more general approach to this, we won't have baggage.

---

*[pkg/sql/sqlbase/testutils.go, line 136 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-Kc_i841o5o4lUvGR3nS:-Kc_i841o5o4lUvGR3nT:bg75mz8) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a4d3042b22203a9759954d4358f5517e8c6cb8/pkg/sql/sqlbase/testutils.go#L136)):*
> ```Go
> 		return parser.NewDOid(parser.DInt(rng.Int63()))
> 	case ColumnType_INT_ARRAY, ColumnType_INT2VECTOR:
> 		// TODO(cuongdo): we don't support for persistence of arrays yet
> ```

arrays or vectors

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-:-Kc_jpyonl32ZDzhe4K1:b-kz97ch)*

**Comment by cuongdo** [comment]
Review status: 1 of 23 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[pkg/sql/create.go, line 1160 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-Kc_iOSoZYPtBiDAKWml:-KccJ66fkzpb_haaYuKv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a4d3042b22203a9759954d4358f5517e8c6cb8/pkg/sql/create.go#L1160)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Throughout: "array" should correspond to "vector", because we're referring to a generic data type. So ` s/INT2VECTOR/VECTOR/`
</blockquote></details>

Done.

---

*[pkg/sql/pg_catalog.go, line 828 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-Kc_jJP6TqX6V6NRWuNu:-KccNI0_9pl8QBpICTsV:b-s60p4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a4d3042b22203a9759954d4358f5517e8c6cb8/pkg/sql/pg_catalog.go#L828)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's change this to `colIDArrayToArray` and change the signature to return a `*parser.DArray`. Then we can create a new function right below it called `colIDArrayToVector` that performs this wrapping.
</blockquote></details>

How do I return a `NULL` when `len(index.ColumnIDs) == 0`? That's what Postgres seems to do with various ARRAY columns, such as `pg_constraint.conkey`

---

*[pkg/sql/show.go, line 171 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-Kc_djW7z3TpqJ8ayhJM:-KccR39srAzH0Y_vkHpl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad21cfa1039bbd86a012931ef852c60e4442500e/pkg/sql/show.go#L171)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why not just change the names in `varGen` to be lower case and switch `name := strings.ToUpper(n.Name)` to `name := strings.ToLower(n.Name)`. Will that break anything other than forcing a few more test changes?
</blockquote></details>

Done.

---

*[pkg/sql/parser/col_types.go, line 328 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-Kc_fC53pe1sKisX657d:-KccTJbbW46XCui43wi0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a4d3042b22203a9759954d4358f5517e8c6cb8/pkg/sql/parser/col_types.go#L328)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This was the approach I initially took with `NameColType` and `OidColType`. I would strongly suggest we create a new `ColumnType` implementation instead. The `if ct.Name == "INT2VECTOR" {` special cases are both ugly and fragile.
</blockquote></details>

Done.

---

*[pkg/sql/parser/datum.go, line 2012 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-Kc_ej41nB9LVYJVzSgB:-KccZ3qcwgyBfyEK4V40:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a4d3042b22203a9759954d4358f5517e8c6cb8/pkg/sql/parser/datum.go#L2012)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

For `DOidWrapper` support of `*DArray`, we're going to need to honor this comment. That means replacing all `.(*DArray)` type assertions with corresponding function calls implemented in the style of `AsDInt` and `MustBeDInt`.
</blockquote></details>

Done.

---

*[pkg/sql/parser/datum.go, line 2159 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-Kc_eVfxgHTjesBmprVe:-KccakkALvMiGpVf_wLj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a4d3042b22203a9759954d4358f5517e8c6cb8/pkg/sql/parser/datum.go#L2159)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

let's move this up below `NewDOid`
</blockquote></details>

Done.

---

*[pkg/sql/pgwire/types.go, line 181 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-Kc_g7kMHYk26WbgIwh0:-KcccDNlrq-ku-ab-gbF:bfh2suh) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a4d3042b22203a9759954d4358f5517e8c6cb8/pkg/sql/pgwire/types.go#L181)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'd turn this into a `switch` statement based on the OID of `d` (`d.ResolvedType().OID()`) directly so that we don't need the checked type assertion.
</blockquote></details>

Much cleaner! Done

---

*[pkg/sql/pgwire/types.go, line 185 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-Kc_gSVrD_LP0mjTTafL:-KcccEcl_OQ1N8NHotId:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a4d3042b22203a9759954d4358f5517e8c6cb8/pkg/sql/pgwire/types.go#L185)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`v` is already this array
</blockquote></details>

Done.

---

*[pkg/sql/sqlbase/structured.go, line 1670 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-Kc_hkRoiyqLj_uJbbpl:-KccdhOT9YLHUPM3TFGI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a4d3042b22203a9759954d4358f5517e8c6cb8/pkg/sql/sqlbase/structured.go#L1670)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: move to below `parser.TypeIntArray`.
</blockquote></details>

Done.

---

*[pkg/sql/sqlbase/structured.go, line 1720 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-Kc_ho24ysCFz9RPkZRX:-Kccg7dItjwLkqa9MSJx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a4d3042b22203a9759954d4358f5517e8c6cb8/pkg/sql/sqlbase/structured.go#L1720)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

---

*[pkg/sql/sqlbase/structured.proto, line 44 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-Kc_hqW5pKeym_hnJ4wk:-Kcce4aDWOFG-6YUaerG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a4d3042b22203a9759954d4358f5517e8c6cb8/pkg/sql/sqlbase/structured.proto#L44)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's do something similar to below. Make this `= 120` or something so that if/when we decide on a more general approach to this, we won't have baggage.
</blockquote></details>

Done.

---

*[pkg/sql/sqlbase/testutils.go, line 136 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-Kc_i841o5o4lUvGR3nS:-KccTEenT_sM1uGxBvkY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a4d3042b22203a9759954d4358f5517e8c6cb8/pkg/sql/sqlbase/testutils.go#L136)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

arrays or vectors
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484)*

**Comment by cuongdo** [comment]
Thanks for the thorough review, as always!

Rebased and addressed comments

---

Review status: 0 of 23 files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-:-Kcck2Jzze022iObKud3:b7vycn8)*

**Comment by cuongdo** [comment]
@nvanbenschoten Any comments? There have been many recent changes to the type system, so I'd love to get further feedback.

**Comment by nvanbenschoten** [comment]
:lgtm: with two small changes

---

Reviewed 2 of 19 files at r5, 21 of 21 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/pg_catalog.go, line 828 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-Kc_jJP6TqX6V6NRWuNu:-KcyR39D2bRs_39cmKMk:b-toe8gt) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a4d3042b22203a9759954d4358f5517e8c6cb8/pkg/sql/pg_catalog.go#L828)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

How do I return a `NULL` when `len(index.ColumnIDs) == 0`? That's what Postgres seems to do with various ARRAY columns, such as `pg_constraint.conkey`
</blockquote></details>

Good point, `colIDArrayToArray ` will still return a `parser.Datum`. But you can handle the NULL case in `colIDArrayToVector`. Right now that won't even work because you blindly type assert below.

---

*[pkg/sql/pgwire/types.go, line 191 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-KcySYHIBsrlEhhjzd55:-KcySYHIBsrlEhhjzd56:b-axh2bu) ([raw file](https://github.com/cockroachdb/cockroach/blob/516563713a270ee01c8f5d37748b92493f989ebd/pkg/sql/pgwire/types.go#L191)):*
> ```Go
> 			}
> 			b.writeLengthPrefixedVariablePutbuf()
> 		case oid.T__int8, oid.T__text, oid.T__name:
> ```

Let's just put a default case instead of enumerating all of these.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-:-KcySuJkiOM4RafNB7sS:b-nqdot1)*

**Comment by cuongdo** [comment]
Review status: 2 of 23 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/pg_catalog.go, line 828 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-Kc_jJP6TqX6V6NRWuNu:-KczhoNhpJzBN-_TLMxI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a4d3042b22203a9759954d4358f5517e8c6cb8/pkg/sql/pg_catalog.go#L828)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Good point, `colIDArrayToArray ` will still return a `parser.Datum`. But you can handle the NULL case in `colIDArrayToVector`. Right now that won't even work because you blindly type assert below.
</blockquote></details>

Done.

---

*[pkg/sql/pgwire/types.go, line 191 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484#-KcySYHIBsrlEhhjzd55:-Kczhy3TBtcym65jXaGc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/516563713a270ee01c8f5d37748b92493f989ebd/pkg/sql/pgwire/types.go#L191)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's just put a default case instead of enumerating all of these.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13484)*

**Pull request merged**
