### PR TITLE
sql: add schema.sql and stats.sql back to redacted statement bundles

### PR DESCRIPTION
**Pull request by michae2**
**sql: add create_redactable column to crdb_internal.create_statements**

Add a new `create_redactable` column to the
`crdb_internal.create_statements` virtual table which provides the
`CREATE` statement for the table or view with all constants and literals
surrounded by redaction markers. Combined with the
`crdb_internal.redact` function this can be used to obtain a redacted
`CREATE` statement for any table.

Part of: #68570

Epic: CRDB-19756

Release note: None
 
**sql: add WITH REDACT option to SHOW CREATE**

Add a new `WITH REDACT` option to `SHOW CREATE` statements which reads
from `create_redactable` instead of `create_statement` when delegating
`SHOW CREATE` to `crdb_internal.create_statements`.

(The `WITH REDACT` syntax is intended to allow for additional options in
the future (if we want them) such as `REDACTABLE`)

Part of: #68570

Epic: CRDB-19756

Release note (sql change): Add a new `WITH REDACT` option to the
following statements:

- `SHOW CREATE`
- `SHOW CREATE TABLE`
- `SHOW CREATE VIEW`

which, when used, replaces constants and literals in the printed
`CREATE` statement with the redacted marker, '‹×›'.

**sql: add schema.sql and stats.sql back to redacted statement bundles**

Use `SHOW CREATE ... WITH REDACT` to generate `CREATE` statements for
schema.sql in redacted statement diagnostics bundles.

Also use statistics without histograms in redacted bundles.

Part of: #68570

Epic: CRDB-19756

Release note: None

### CODE REVIEW

**Comment by michae2** [comment]
Latest failure looks like a flake, so I think this is RFAL.

I'm not in love with the `WITH REDACTED_VALUES` syntax, so if you have a better idea please let me know!

**Review by msirek — APPROVED** [review]
Looks good!

> I'm not in love with the WITH REDACTED_VALUES syntax, so if you have a better idea please let me know!

Maybe just `REDACTED`?  I'm not sure what's best here either.
Too bad we have to redacted simple data too like booleans, in case knowing the values would help reproduce issues, but I guess it's hard to foresee cases.  Maybe even booleans could be used to derive PII.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98251#-:-NQ7fKBm-6A5QQdSKera:b-uoh73n)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373)

**Review by michae2 — COMMENTED** [review]
I shortened it to `WITH REDACT` which matches the `EXPLAIN (REDACT)` flag I added. :shrug:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98251#-:-NQSA9KmBSXlg6H1p8oo:b-g1plrd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373)

**Comment by michae2** [comment]
Assuming CI passes and there are no objections, I'll bors this later today.

**Review by rharding6373 — COMMENTED** [review]
Nice work! I just have a question about adding a new column to the internal table.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98251#-:-NQSHw1vEUEvWzpu-vq9:b-lvlijk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2)

___
*[`-- commits` line 6 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/98251#-NQSFpVgAPnxPcXp5nKi):*
I don't fully understand why this commit with the extra column to `create_statements` is necessary. Would it be possible to make the create statement with redaction markers on demand?

**Review by michae2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98251)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373)

___
*[`-- commits` line 6 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/98251#-NQSFpVgAPnxPcXp5nKi):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I don't fully understand why this commit with the extra column to `create_statements` is necessary. Would it be possible to make the create statement with redaction markers on demand?
</blockquote></details>

I explored changing [PrintCreateTable](https://github.com/cockroachdb/cockroach/blob/2d633784329ae8a1d14854a827db978296e0ed6c/pkg/sql/explain_bundle.go#L775-L777) to call [ShowCreateTable](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/show_create.go#L60-L75) directly, but this required figuring out table descriptor resolution, which `SHOW CREATE TABLE` takes care of. I decided to keep using `SHOW CREATE TABLE` in `PrintCreateTable`, and that meant the `crdb_internal.create_statements` virtual table had to change (which is how `SHOW CREATE TABLE` is implemented internally).

Because `crdb_internal.create_statements` is a virtual table, it _is_ on-demand, in a sense: reading from the table constructs the create statement. (But it is admittedly a little less direct than simply calling `ShowCreateTable`.)

There are some other advantages to changing `crdb_internal.create_statements`: we can use the new column in debug zips, and in tests (both of which this PR does).

**Review by rharding6373 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98251#-:-NQa2I7HEIgEVxkoDe_P:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by michae2** [comment]
TFYRs!

bors r=msirek,rharding6373

**Comment by michae2** [comment]
Starting to think this is not a flake...

bors r-

**Comment by michae2** [comment]
(I'm waiting to rebase this on https://github.com/cockroachdb/cockroach/pull/98758 which should fix the flake.)

**Comment by michae2** [comment]
Trying again.

bors r=msirek,rharding6373

**Pull request merged**
