### PR TITLE
obs, roachprod, rpc, spanconfig, storage, testutils: cleanup lock usages

### PR DESCRIPTION
**Pull request by Santamaura**
This PR updates unsafe/unnecessary manual unlocks to defer unlocks. 
The criteria for leaving some unlocks as is:
- will not cause a leak
- releases the resources much earlier
- deferring will cause a deadlock without significant refactor

Part of #107946

Release note: None

Signoffs

- [x] obs
- [x] roachprod
- [x] rpc
- [x] spanconfig
- [x] storage
- [x] testutils

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
> Reviewed 2 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108171)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @RaduBerinde, @renatolabs, @Santamaura, and @smg260)

___
*[`pkg/roachprod/vm/azure/azure.go` line 1042 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108171#-NbFXDsB70C6HTIOSTAR:-NbFXDsB70C6HTIOSTAS:b-f2y9dy) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7b35c4744aba63287608feac88ad077378e650d/pkg/roachprod/vm/azure/azure.go#L1042)):*
> ```Go
> 				p.mu.Lock()
> 				defer p.mu.Unlock()
> 				return p.mu.resourceGroups[vnetResourceGroupName(location)]
> ```

a bunch of these usages as identical so perhaps a method can be added to `p` that automatically locks/unlocks. then you can avoid the inline functions.

**Review by Santamaura — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108171)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, @RaduBerinde, @renatolabs, and @smg260)

___
*[`pkg/roachprod/vm/azure/azure.go` line 1042 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108171#-NbFXDsB70C6HTIOSTAR:-NbFsuQ70l9tga0xqoxy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7b35c4744aba63287608feac88ad077378e650d/pkg/roachprod/vm/azure/azure.go#L1042)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

a bunch of these usages as identical so perhaps a method can be added to `p` that automatically locks/unlocks. then you can avoid the inline functions.
</blockquote></details>

Done.

**Review by knz — COMMENTED** [review]
> Reviewed 7 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108171)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, @RaduBerinde, @renatolabs, @Santamaura, and @smg260)

___
*[`pkg/rpc/clock_offset.go` line 340 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108171#-NbVXAIe7DLdGSgqmUAf:-NbVXAIe7DLdGSgqmUAg:bb76mu4) ([raw file](https://github.com/cockroachdb/cockroach/blob/94a997f6d0b7f03fd617aa624a3afc6ef6debad6/pkg/rpc/clock_offset.go#L340)):*
> ```Go
> 	}
> 	numClocks := len(r.mu.offsets)
> 	// nolint:deferunlock
> ```

Why?

**Review by Santamaura — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108171)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, @knz, @RaduBerinde, @renatolabs, and @smg260)

___
*[`pkg/rpc/clock_offset.go` line 340 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108171#-NbVXAIe7DLdGSgqmUAf:-Nbo_wBX3ejqB-3aZDF9:b-ih2p5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/94a997f6d0b7f03fd617aa624a3afc6ef6debad6/pkg/rpc/clock_offset.go#L340)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Fair enough, updated.

**Review by knz — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108171)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @RaduBerinde, @renatolabs, @Santamaura, and @smg260)

___
*[`pkg/roachprod/vm/azure/azure.go` line 1060 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/108171#-NdfBUfv4NXvOxe-GE3t:-NdfBUfv4NXvOxe-GE3u:bb9nqx3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c297c31a8223f0d26e9ba80356d9d06017b31891/pkg/roachprod/vm/azure/azure.go#L1060)):*
> ```Go
> 	vnets := make([]network.VirtualNetwork, len(ret))
> 	for location, prefix := range prefixesByLocation {
> 		resourceGroup := p.getResourcesGroupByName(vnetResourceGroupName(location))
> ```

I think you want both calls under a single critical section. The two maps are meant to be accessed atomically.
___
*[`pkg/rpc/clock_offset.go` line 327 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/108171#-NdfBkT95BU_9N6WMTrw:-NdfBkT95BU_9N6WMTrx:b-5aycfo) ([raw file](https://github.com/cockroachdb/cockroach/blob/c297c31a8223f0d26e9ba80356d9d06017b31891/pkg/rpc/clock_offset.go#L327)):*
> ```Go
> 	var offsets stats.Float64Data
> 	var numClocks int
> 	func() {
> ```

nit: `offsets, numClocks := func() ... { ... }()`
___
*[`pkg/rpc/peer.go` line 811 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/108171#-NdfC-CF-H7bdIf4zYhO:-NdfC-CF-H7bdIf4zYhP:b-38gzfc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c297c31a8223f0d26e9ba80356d9d06017b31891/pkg/rpc/peer.go#L811)):*
> ```Go
> func touchOldPeers(peers *peerMap, now time.Time) {
> 	var sigs []circuit.Signal
> 	func() {
> ```

nit: `sigs := func() ...`
___
*[`pkg/spanconfig/spanconfigkvsubscriber/kvsubscriber.go` line 409 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/108171#-NdfC1h_2yTobTmMPGqp:-NdfC1h_2yTobTmMPGqq:bkoh2qp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c297c31a8223f0d26e9ba80356d9d06017b31891/pkg/spanconfig/spanconfigkvsubscriber/kvsubscriber.go#L409)):*
> ```Go
> 		freshStore.Apply(ctx, false /* dryrun */, ev.(*BufferEvent).Update)
> 	}
> 	var handlers []handler
> ```

nit: `handlers := func() ...`
___
*[`pkg/spanconfig/spanconfigkvsubscriber/kvsubscriber.go` line 433 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/108171#-NdfBqedDFZLuJ6XvnZg:-NdfBqedDFZLuJ6XvnZh:bswg9oa) ([raw file](https://github.com/cockroachdb/cockroach/blob/c297c31a8223f0d26e9ba80356d9d06017b31891/pkg/spanconfig/spanconfigkvsubscriber/kvsubscriber.go#L433)):*
> ```Go
> 	ctx context.Context, ts hlc.Timestamp, events []rangefeedbuffer.Event,
> ) {
> 	var handlers []handler
> ```

nit: `handlers := func() ... { ... }()`

**Review by Santamaura — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108171)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @knz, @RaduBerinde, @renatolabs, and @smg260)

___
*[`pkg/roachprod/vm/azure/azure.go` line 1060 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/108171#-NdfBUfv4NXvOxe-GE3t:-NdfjcwW2B05mu9Wv9bT:bgo8yit) ([raw file](https://github.com/cockroachdb/cockroach/blob/c297c31a8223f0d26e9ba80356d9d06017b31891/pkg/roachprod/vm/azure/azure.go#L1060)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I think you want both calls under a single critical section. The two maps are meant to be accessed atomically.
</blockquote></details>

I've consolidated it into 1 function.
___
*[`pkg/rpc/clock_offset.go` line 327 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/108171#-NdfBkT95BU_9N6WMTrw:-NdfjiHB5hNXpDwJwDkC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c297c31a8223f0d26e9ba80356d9d06017b31891/pkg/rpc/clock_offset.go#L327)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: `offsets, numClocks := func() ... { ... }()`
</blockquote></details>

Done.
___
*[`pkg/rpc/peer.go` line 811 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/108171#-NdfC-CF-H7bdIf4zYhO:-Ndfjzd3B07CO9SE-P3H:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c297c31a8223f0d26e9ba80356d9d06017b31891/pkg/rpc/peer.go#L811)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: `sigs := func() ...`
</blockquote></details>

Done.
___
*[`pkg/spanconfig/spanconfigkvsubscriber/kvsubscriber.go` line 409 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/108171#-NdfC1h_2yTobTmMPGqp:-Ndfk3RtDpgVnls1pa_i:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c297c31a8223f0d26e9ba80356d9d06017b31891/pkg/spanconfig/spanconfigkvsubscriber/kvsubscriber.go#L409)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: `handlers := func() ...`
</blockquote></details>

Done.
___
*[`pkg/spanconfig/spanconfigkvsubscriber/kvsubscriber.go` line 433 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/108171#-NdfBqedDFZLuJ6XvnZg:-Ndfk4DO6HhkAdxReMtn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c297c31a8223f0d26e9ba80356d9d06017b31891/pkg/spanconfig/spanconfigkvsubscriber/kvsubscriber.go#L433)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: `handlers := func() ... { ... }()`
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108171#-:-Ndft2OO1L1iQQWuxR1Y:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian, @RaduBerinde, @renatolabs, and @smg260)

___
*[`pkg/rpc/peer.go` line 810 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/108171#-NdfssSl6msysmbuaZqY:-NdfssSl6msysmbuaZqZ:bkybcvf) ([raw file](https://github.com/cockroachdb/cockroach/blob/724bf91e3e4fbd495fd97de9fa48a25a9a59e96a/pkg/rpc/peer.go#L810)):*
> ```Go
> 
> func touchOldPeers(peers *peerMap, now time.Time) {
> 	sigs := func() []circuit.Signal {
> ```

(tip for next time: `sigs := func() (sigs []circuit.Signal) {`)

**Review by Santamaura — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108171)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian, @knz, @RaduBerinde, @renatolabs, and @smg260)

___
*[`pkg/rpc/peer.go` line 810 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/108171#-NdfssSl6msysmbuaZqY:-Ndg0ZA47oRxuswKUHFm:b-wbd2f4) ([raw file](https://github.com/cockroachdb/cockroach/blob/724bf91e3e4fbd495fd97de9fa48a25a9a59e96a/pkg/rpc/peer.go#L810)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

(tip for next time: `sigs := func() (sigs []circuit.Signal) {`)
</blockquote></details>

This is helpful, TIL. Updated this while fixing linting problems.

**Comment by Santamaura** [comment]
Escape analysis looks good for these changes; no closures escape to the heap.

bors r+

**Pull request merged**
