### PR TITLE
sql: Decouple sql executor and pgwire from sql/driver

### PR DESCRIPTION
**Pull request by nvb**
This is the first step in phasing out the internal dependence on the Cockroach `sql/driver` package. It moves a number of protobuf structs to classic Go structs, and moves them into the `sql.Executor`. This had the result of removing a couple of allocation paths.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3987)

### CODE REVIEW

**Comment by dt** [comment]
Might want to check with Radu about renaming `resultColumn` back to `Column` -- he just renamed it from that in #3857. 

---

Review status: 0 of 15 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3987#-:-K93GLrV5w_fBUaEM06v:1815908342)*

**Comment by RaduBerinde** [comment]
Yeah, `Column` is too generic for what it is (we have a bunch of types that correspond to a column in some way). I'm guessing the rename undoing was unintentional, probably working on top of an older commit?

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3987#-:-K93ObrOUZUi8OTfXVPB:-1872770869)*

**Comment by nvanbenschoten** [comment]
Ah sorry, I didn't realize I was stepping on a recent change. Renamed `Column` to `ResultColumn` and `Row` to `ResultRow`.

---

Review status: 0 of 15 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3987#-:-K93Ss7mAUpocYRXQJpw:818993156)*

**Comment by tamird** [comment]
Reviewed 4 of 15 files at r1, 11 of 11 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/executor.go, line 360 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3987#-K93UymPIRd05yEyIBCR:-K93UymPIRd05yEyIBCS:-1651678399) ([raw file](https://github.com/cockroachdb/cockroach/blob/943e1cbb202805da1bcb80171516b2b84aaa5adb/sql/executor.go#L360)):*
like you did elsewhere, can you do:
```
row := ResultRow{Values: plan.Values()}
for _, val := range row.Values {
  if err := ...; ... {
    ...
  }
}
``

---

*[sql/executor.go, line 436 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3987#-K93VKaEEDCxxLGQBivb:-K93VKaEEDCxxLGQBivc:-446860574) ([raw file](https://github.com/cockroachdb/cockroach/blob/943e1cbb202805da1bcb80171516b2b84aaa5adb/sql/executor.go#L436)):*
`pErr.GoError()`?

---

*[sql/executor.go, line 570 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3987#-K93UOD5D8Ld8DsfynAs:-K93UOD5D8Ld8DsfynAt:-1578328533) ([raw file](https://github.com/cockroachdb/cockroach/blob/943e1cbb202805da1bcb80171516b2b84aaa5adb/sql/executor.go#L570)):*
do you think these proto conversion routines might fit better in sql/server.go?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3987)*
<!-- Sent from Reviewable.io -->

**Comment by nvanbenschoten** [comment]
Review status: 13 of 15 files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/executor.go, line 360 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3987#-K93UymPIRd05yEyIBCR:-K93XM4Lt1vL_RRQSiAt:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/943e1cbb202805da1bcb80171516b2b84aaa5adb/sql/executor.go#L360)):*
Done.

---

*[sql/executor.go, line 436 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3987#-K93VKaEEDCxxLGQBivb:-K93XjPHie8xRaUe3d_Y:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/943e1cbb202805da1bcb80171516b2b84aaa5adb/sql/executor.go#L436)):*
Done.

---

*[sql/executor.go, line 570 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3987#-K93UOD5D8Ld8DsfynAs:-K93Xk0wcUouHW8R3Yc-:1386559450) ([raw file](https://github.com/cockroachdb/cockroach/blob/943e1cbb202805da1bcb80171516b2b84aaa5adb/sql/executor.go#L570)):*
Ah yeah, I didn't like where theres were. `sql/server.go` is better. Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3987)*

**Comment by dt** [comment]
Reviewed 4 of 15 files at r1, 10 of 11 files at r2.
Review status: 13 of 15 files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/server.go, line 268 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3987#-K93_I0jwdyeNFWC759F:-K93_I0jwdyeNFWC759G:-946183763) ([raw file](https://github.com/cockroachdb/cockroach/blob/df87839c8895385a09e3e90bc97a7579932de1a7/sql/server.go#L268)):*
Guess it doesn't really matter since the panic crash trace will have files and line numbers, but in case it gets recovered or refactored later, does it make sense to use `util.Errorf` here?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3987)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/server.go, line 150 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3987#-K93_y1rw1IG84AkHrkg:-K93_y1rw1IG84AkHrkh:568878521) ([raw file](https://github.com/cockroachdb/cockroach/blob/df87839c8895385a09e3e90bc97a7579932de1a7/sql/server.go#L150)):*
ditto, return a value here.

---

*[sql/server.go, line 226 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3987#-K93_mZasSDu8u53npkN:-K93_mZasSDu8u53npkO:964232259) ([raw file](https://github.com/cockroachdb/cockroach/blob/df87839c8895385a09e3e90bc97a7579932de1a7/sql/server.go#L226)):*
return a value from here, not a pointer (the only callers always dereference).

---

*[sql/server.go, line 268 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3987#-K93_I0jwdyeNFWC759F:-K93aDMBDic0DUl6UiR4:5172523) ([raw file](https://github.com/cockroachdb/cockroach/blob/df87839c8895385a09e3e90bc97a7579932de1a7/sql/server.go#L268)):*
+1

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3987)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/server.go, line 268 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3987#-K93_I0jwdyeNFWC759F:-K93b8Y5y9h8_wRFsOVa:-1604143525) ([raw file](https://github.com/cockroachdb/cockroach/blob/df87839c8895385a09e3e90bc97a7579932de1a7/sql/server.go#L268)):*
Ah, though that clutters the signature with an error. Leave it as is, this code is provisional.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3987)*

**Comment by dt** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/server.go, line 268 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3987#-K93_I0jwdyeNFWC759F:-K93bMKRojIxFIqtgfhG:-1698919463) ([raw file](https://github.com/cockroachdb/cockroach/blob/df87839c8895385a09e3e90bc97a7579932de1a7/sql/server.go#L268)):*
To clarify: I wasn't suggesting changing the panic or signature, just how the error passed to it is generated.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3987)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/server.go, line 268 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3987#-K93_I0jwdyeNFWC759F:-K93c8OaeC8TOjTDF57D:-803434703) ([raw file](https://github.com/cockroachdb/cockroach/blob/df87839c8895385a09e3e90bc97a7579932de1a7/sql/server.go#L268)):*
Right. Ignore me.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3987)*

**Comment by nvanbenschoten** [comment]
Review status: 14 of 15 files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/server.go, line 150 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3987#-K93_y1rw1IG84AkHrkg:-K93h41Uqur8wDpj1j78:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/df87839c8895385a09e3e90bc97a7579932de1a7/sql/server.go#L150)):*
Done.

---

*[sql/server.go, line 226 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3987#-K93_mZasSDu8u53npkN:-K93h8cF1CuuVf2K0WsN:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/df87839c8895385a09e3e90bc97a7579932de1a7/sql/server.go#L226)):*
Done.

---

*[sql/server.go, line 268 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3987#-K93_I0jwdyeNFWC759F:-K93gymtMGA0X0B-J8EI:-2084458650) ([raw file](https://github.com/cockroachdb/cockroach/blob/df87839c8895385a09e3e90bc97a7579932de1a7/sql/server.go#L268)):*
Done. Good call.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3987)*

**Comment by tamird** [comment]
LGTM

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3987#-:-K93jdgQrbB6hxiGGobt:676834233)*

**Comment by dt** [comment]
```
name                  old time/op  new time/op  delta
Update10_Cockroach-8  10.0ms ± 8%   9.6ms ± 1%  -3.89%  (p=0.010 n=10+9)
```

**Pull request merged**
