### PR TITLE
kvserver: fix TestStoreRangeSplitAndMergeWithGlobalReads

### LINKED ISSUE #119230: kv/kvserver: TestStoreRangeSplitAndMergeWithGlobalReads failed
kv/kvserver.TestStoreRangeSplitAndMergeWithGlobalReads [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/14005299?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/14005299?buildTab=artifacts#/) on master @ [cc6ca026319024800395293b0fb18f05dd8eb50e](https://github.com/cockroachdb/cockroach/commits/cc6ca026319024800395293b0fb18f05dd8eb50e):

```
=== RUN   TestStoreRangeSplitAndMergeWithGlobalReads
    test_log_scope.go:170: test logs captured to: /artifacts/tmp/_tmp/3c632028e5b231a582105881dfd5d4b5/logTestStoreRangeSplitAndMergeWithGlobalReads54447473
    test_log_scope.go:81: use -show-logs to present logs inline
    client_split_test.go:3691: condition failed to evaluate within 45s: from client_split_test.go:3693: commit wait count is 2
    panic.go:523: -- test log scope end --
--- FAIL: TestStoreRangeSplitAndMergeWithGlobalReads (53.05s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestStoreRangeSplitAndMergeWithGlobalReads.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-36100

### PR DESCRIPTION
**Pull request by andrewbaptist**
Directly set the span config for the range under test rather than setting the ZoneConfig and waiting for it to propagate. In addition to simplifying the test it also makes it run faster.

Fixes: #119230

Epic: none

Release note: None

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
Looks great!

> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122710#-:-Nw5YH1qAsSyRy3GkR0g:b9bkkp1)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122710#-Nw5A7uTA4TqPAvM56jP):*
IIUC, we're not reverting the entire commit here, are we? We're only reverting the changes to this particular test?

It seems like that from the diff. Could you clarify this in the title?
___
*[`pkg/spanconfig/testing_knobs.go` line 159 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/122710#-Nw5XXNp2HelxzzbkYOT:-Nw5XXNq5ApnVbYhh1Tc:b-hrnmra) ([raw file](https://github.com/cockroachdb/cockroach/blob/075169ffaf53e7adfe3ab52a05b0c3ccb1adb946/pkg/spanconfig/testing_knobs.go#L159)):*
> ```Go
> // of DefaultZoneConfigOverride, DefaultSystemZoneConfigOverride,
> // OverrideFallbackConf, ConfReaderInterceptor, UseSystemConfigSpanForQueues,
> // SpanConfigUpdateInterceptor or SetSpanConfigInterceptor. By using this class
> ```

nit: given this is go, let's replace all mentions of class with struct.
___
*[`pkg/spanconfig/testing_knobs.go` line 162 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/122710#-Nw5XAYH1OviY8oqTOgn:-Nw5XAYI-3I4PN0oO9oP:b70kw5w) ([raw file](https://github.com/cockroachdb/cockroach/blob/075169ffaf53e7adfe3ab52a05b0c3ccb1adb946/pkg/spanconfig/testing_knobs.go#L162)):*
> ```Go
> // as an alternative to the others it mainly avoids any need to depend on
> // rangefeed timing to propagate the config change.
> type WrappingKVSubscriber struct {
> ```

Let's move this into the `spanconfigtestutils` package. Separately, should we rename this to `WrappedKVSubscriber`? 
___
*[`pkg/spanconfig/testing_knobs.go` line 163 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/122710#-Nw5Y2Mk91pKhHlyoxSb:-Nw5Y2Mk91pKhHlyoxSc:b-4zp5yj) ([raw file](https://github.com/cockroachdb/cockroach/blob/93d3023f7dbc131316801998780b01d70f10571a/pkg/spanconfig/testing_knobs.go#L163)):*
> ```Go
> // rangefeed timing to propagate the config change.
> type WrappingKVSubscriber struct {
> 	Wrapped KVSubscriber
> ```

Let's make these private fields and introduce a constructor to initialize the struct instead.
___
*[`pkg/kv/kvserver/client_split_test.go` line 4058 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/122710#-Nw5YG3HDdaKA_Y1HYPq:-Nw5YG3HDdaKA_Y1HYPr:b-ra3bk5) ([raw file](https://github.com/cockroachdb/cockroach/blob/07fa6cefadba2178c2d2564c78640fbe88626408/pkg/kv/kvserver/client_split_test.go#L4058)):*
> ```Go
> 	ctx := context.Background()
> 	s := serverutils.StartServerOnly(t, base.TestServerArgs{
> 		DisableSQLServer: true,
> ```

Nice :100:

**Review by andrewbaptist — COMMENTED** [review]
Thanks! Also thanks for the feedback on the changes!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122710#-:-Nw5ee8L3gsnRph2uIUg:b-8uoizg)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122710#-Nw5A7uTA4TqPAvM56jP):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

IIUC, we're not reverting the entire commit here, are we? We're only reverting the changes to this particular test?

It seems like that from the diff. Could you clarify this in the title?
</blockquote></details>

Done
___
*[`pkg/spanconfig/testing_knobs.go` line 159 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/122710#-Nw5XXNp2HelxzzbkYOT:-Nw5gLHsDgA59pElqtNN:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/075169ffaf53e7adfe3ab52a05b0c3ccb1adb946/pkg/spanconfig/testing_knobs.go#L159)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: given this is go, let's replace all mentions of class with struct.
</blockquote></details>

Done
___
*[`pkg/spanconfig/testing_knobs.go` line 162 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/122710#-Nw5XAYH1OviY8oqTOgn:-Nw5gLoi6sVLVIEkrUrX:b-fd3087) ([raw file](https://github.com/cockroachdb/cockroach/blob/075169ffaf53e7adfe3ab52a05b0c3ccb1adb946/pkg/spanconfig/testing_knobs.go#L162)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Let's move this into the `spanconfigtestutils` package. Separately, should we rename this to `WrappedKVSubscriber`?
</blockquote></details>

Moved - I didn't like where it was before, so this is much nicer.
___
*[`pkg/spanconfig/testing_knobs.go` line 163 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/122710#-Nw5Y2Mk91pKhHlyoxSb:-Nw6-yLX3oBH-hSskbJX:b-l8n92i) ([raw file](https://github.com/cockroachdb/cockroach/blob/93d3023f7dbc131316801998780b01d70f10571a/pkg/spanconfig/testing_knobs.go#L163)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Let's make these private fields and introduce a constructor to initialize the struct instead.
</blockquote></details>

Changed. I also made AddOverride a method rather than passing in construction. This helps a bit with adding multiple and does not' require `configOverride` to be public either. I'm not 100% sure its great since it somewhat implies that you can add an override after construction, but other than a comment I'm not sure the best way to do this. Let me know if you think this could be structured differently. 
___
*[`pkg/kv/kvserver/client_split_test.go` line 4058 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/122710#-Nw5YG3HDdaKA_Y1HYPq:-Nw5goxz0f2Tg0Ahb65J:b94tri3) ([raw file](https://github.com/cockroachdb/cockroach/blob/07fa6cefadba2178c2d2564c78640fbe88626408/pkg/kv/kvserver/client_split_test.go#L4058)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Nice :100:
</blockquote></details>

Thanks! I'm hoping we can keep rolling this out to more of the tests. It takes 20-25% off the time to run most of the tests so could be a big win in total. I'm tempted to just try and apply it to "all" the files and see which break and then keep any of the ones that don't. Maybe some friday when I have extra time.

**Review by arulajmani — APPROVED** [review]
:lgtm: :shipit: 

> Reviewed 5 of 5 files at r6, 3 of 3 files at r7, 3 of 3 files at r8, 3 of 3 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122710#-:-Nw6L_5980-ACmVPrOjI:byzm7aw)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist)

___
*[`-- commits` line 29 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/122710#-Nw6L1N48dqj2BL-IFZx):*
nit: test struct WrappedKVSubscriber now
___
*[`pkg/spanconfig/testing_knobs.go` line 163 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/122710#-Nw5Y2Mk91pKhHlyoxSb:-Nw6LAb2Dfy2ZptMc2Vm:b-l14jzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/93d3023f7dbc131316801998780b01d70f10571a/pkg/spanconfig/testing_knobs.go#L163)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

Changed. I also made AddOverride a method rather than passing in construction. This helps a bit with adding multiple and does not' require `configOverride` to be public either. I'm not 100% sure its great since it somewhat implies that you can add an override after construction, but other than a comment I'm not sure the best way to do this. Let me know if you think this could be structured differently.
</blockquote></details>

I can imagine cases where setting an override (or updating it) after construction could be useful. Previously, we would have to set zone configs and wait for them to reconcile; now, we can just override. I'm pro this change.
___
*[`pkg/kv/kvserver/client_split_test.go` line 4058 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/122710#-Nw5YG3HDdaKA_Y1HYPq:-Nw6KH4cBQg2L3GsLYuz:bosrd9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/07fa6cefadba2178c2d2564c78640fbe88626408/pkg/kv/kvserver/client_split_test.go#L4058)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

Thanks! I'm hoping we can keep rolling this out to more of the tests. It takes 20-25% off the time to run most of the tests so could be a big win in total. I'm tempted to just try and apply it to "all" the files and see which break and then keep any of the ones that don't. Maybe some friday when I have extra time.
</blockquote></details>

Yeah, this is neat -- now we have this testing knob to override specific span configs, there's really no need to go through the whole reconciliation process. Maybe one Friday ;)

**Comment by andrewbaptist** [comment]
TFTR! I fixed the commit message.

bors r=arulajmani

**Pull request merged**
