### PR TITLE
kvserver,inspectz: add rac2 inspectz support 

### LINKED ISSUE #128091: kvflowcontrol: add inspectz pages for replication ac v2
There are existing inspectz structures in place for querying replication admission control. This issue is to extend, or add new structure such that the v2 implementation supports the same functionality.

See https://github.com/sumeerbhola/cockroach/blob/5c2a50ec4d0dcf2502d742ac9036d39995886abc/pkg/kv/kvserver/kvflowcontrol/kvflowinspectpb/kvflowinspect.proto#L21 for v1.

Jira issue: CRDB-40795

Epic CRDB-37515

### PR DESCRIPTION
**Pull request by kvoli**
The existing flow control tables are:

```
crdb_internal.kv_flow_controller
crdb_internal.kv_flow_control_handles
crdb_internal.kv_flow_token_deductions
```

Which are used in testing to assert on flow control stream state and
transitions.

Introduce another set of three tables, most of which are identical to the
exsting tables but populating the table data using rac2.

```
crdb_internal.kv_flow_controller_v2
crdb_internal.kv_flow_control_handles_v2
crdb_internal.kv_flow_token_deductions_v2
```

`crdb_internal.kv_flow_controller_v2` has two additional columns,
tracking the amount of available (regular|elastic) send tokens. The
schema is:

```
CREATE TABLE crdb_internal.kv_flow_controller_v2 (
  tenant_id                     INT NOT NULL,
  store_id                      INT NOT NULL,
  available_eval_regular_tokens INT NOT NULL,
  available_eval_elastic_tokens INT NOT NULL,
  available_send_regular_tokens INT NOT NULL,
  available_send_elastic_tokens INT NOT NULL
);
```

Note that unless rac2 is enabled, the tables are unlikely to show
anything interesting. Both tables (v1 and v2) are kept for
compatibility, with an intent to replace the v1 tables with the v2 ones
after v1 replication flow control is removed entirely from the code.

Resolves: https://github.com/cockroachdb/cockroach/issues/128091
Release note: None

### CODE REVIEW

**Comment by kvoli** [comment]
Failure is from some missing crdb_internal datadriven test updates, I'll sort these out. Should be ready for a look.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, 13 of 13 files at r2, 7 of 7 files at r3, 4 of 4 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130270)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`-- commits` line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130270#-O6X0BrV68oHYWpiTiw6):*
nit: deductions.
___
*[`-- commits` line 83 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/130270#-O6XDAzt277iy7Gi2zcc):*
nit: existing
___
*[`pkg/inspectz/inspectz.go` line 148 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/130270#-O6XBn9bA9uFQHJRCw4D:-O6XBn9bA9uFQHJRCw4E:b-gf0e09) ([raw file](https://github.com/cockroachdb/cockroach/blob/e89bcbc8f1ca46f69c2dfa6e213087e7dbd6bfef/pkg/inspectz/inspectz.go#L148)):*
> ```Go
> 
> // KVFlowHandlesV2 implements the InspectzServer interface.
> func (s *Server) KVFlowHandlesV2(
> ```

This seems the same as `Server.KVFlowHandles` except for using `handlesV2`. Can this be unified into one function?
___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowcontrol.go` line 323 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130270#-O6X9ryQ3TBWgQLvlrcT:-O6X9ryQ3TBWgQLvlrcU:b6nmmdy) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0ef89d41ca509f2731b5779028bcf1ab7f7a817/pkg/kv/kvserver/kvflowcontrol/kvflowcontrol.go#L323)):*
> ```Go
> 	// Inspect returns the set of ranges that have an embedded
> 	// kvflowcontrol.Handle. It's used to power /inspectz.
> 	Inspect() []roachpb.RangeID
> ```

Now that we have a specialized lookup method for the inspectz path, do we need `LookupInspect` to return an `InspectHandle` or can we simply make it return `(kvflowinspectpb.Handle, bool)`?
___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowinspectpb/kvflowinspect.proto` line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130270#-O6X-XvvAsKyP1v-Nb1Z:-O6X-XvvAsKyP1v-Nb1_:b-k3jpp5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4d0713625be976516e5e46eb997ef3923625ae3/pkg/kv/kvserver/kvflowcontrol/kvflowinspectpb/kvflowinspect.proto#L84)):*
> ```proto
> // Stream represents a given kvflowcontrol.Stream and the number of tokens
> // available for it (as maintained by the node-level kvflowcontrol.Controller,
> // or in >= v25.1, by the node level StreamTokenCounterProvider).
> ```

v24.3?
___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowinspectpb/kvflowinspect.proto` line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130270#-O6X-bSn5tu5XPLtkKyD:-O6X-bSn5tu5XPLtkKyE:b-fybcmp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4d0713625be976516e5e46eb997ef3923625ae3/pkg/kv/kvserver/kvflowcontrol/kvflowinspectpb/kvflowinspect.proto#L93)):*
> ```proto
>     (gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/roachpb.StoreID"];
>   // AvailableEvalRegularTokens represents the currently available tokens for
>   // regular replication traffic, deducted before evaluation.
> ```

should this say "deducted for evaluation"?
(we don't actually deduct them before evaluation)
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 422 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130270#-O6X0ukOD3WLoj4_82bx:-O6X0ukOD3WLoj4_82by:b-3jo7ip) ([raw file](https://github.com/cockroachdb/cockroach/blob/4beff4715905afad323514d3caecc90b1470f6e4/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L422)):*
> ```Go
> func (rc *rangeController) Inspect(ctx context.Context) kvflowinspectpb.Handle {
> 	rc.mu.Lock()
> 	defer rc.mu.Unlock()
> ```

`rc.mu` does not protect `replicaMap`, IIRC.
We are relying on external synchronization, specifically `raftMu` for this.

As mentioned in https://cockroachlabs.slack.com/archives/C06UFBJ743F/p1726018900176919?thread_ts=1726008270.371049&cid=C06UFBJ743F, I think it is acceptable to rename this `InspectRaftMuLocked` and have the caller acquire `raftMu`. The higher latency is fine for inspectz and querying the internal tables.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130270#-O6X2bfC5P2qDJ40YfGP:-O6X2bfC5P2qDJ40YfGQ:bwjp6p8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4beff4715905afad323514d3caecc90b1470f6e4/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L112)):*
> ```Go
> 	slices.SortFunc(streams, func(a, b kvflowinspectpb.Stream) int { // for determinism
> 		return cmp.Or(
> 			cmp.Compare(a.TenantID.ToUint64(), b.TenantID.ToUint64()),
> ```

is there a reason this is sorting the tuple (tenant-id, store-id), while `rangeController.Inspect` is sorting `(store-id, tenant-id)`?
___
*[`pkg/server/server.go` line 1134 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/130270#-O6XCdR-60Te0E2yyvEg:-O6XCdR-60Te0E2yyvEh:b1raxok) ([raw file](https://github.com/cockroachdb/cockroach/blob/e89bcbc8f1ca46f69c2dfa6e213087e7dbd6bfef/pkg/server/server.go#L1134)):*
> ```Go
> 		cfg.BaseConfig.AmbientCtx,
> 		node.storeCfg.KVFlowHandles,
> 		kvserver.MakeStoresForRACv2(stores),
> ```

It just happens that `MakeStoresForRACv2` is casting `stores` and does not have some additional state, so calling `MakeStoresForRACv2` a second time does not accidentally create a second object when it is expected to be a singleton. We shouldn't rely on this. I think we already have `storesForRACv2` as a local variable from earlier in this function, and should use it here.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/inspect` line 224 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130270#-O6X41Aj0jJhCTqfhfuc:-O6X41Aj0jJhCTqfhfud:bladu6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/4beff4715905afad323514d3caecc90b1470f6e4/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/inspect#L224)):*
> ```
> 
> # Change the replica on s3 to StateSnapshot. This should untrack all entries
> # and result in the stream token counts being updated accordingly.
> ```

I think we should not consider s3 to have a connected stream. Currently the code does
```
		if rs.sendStream == nil {
			continue
		}
```
and since it was in StateReplicate and transitioned to StateSnapshot we still have the `replicaSendStream` and print the state below. Up to you whether you want to change this now, or wait until the equivalent of https://github.com/cockroachdb/cockroach/pull/130168 where all transitions to StateSnapshot close the `replicaSendStream`.

**Review by kvoli — COMMENTED** [review]
TYFTR! Addressed the comments, ptal.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130270#-:-O6avv7vBI5Kxo0okfsi:bnvptcy)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @sumeerbhola)

___
*[`-- commits` line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130270#-O6X0BrV68oHYWpiTiw6):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: deductions.
</blockquote></details>

Updated.
___
*[`-- commits` line 83 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/130270#-O6XDAzt277iy7Gi2zcc):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: existing
</blockquote></details>

Updated.
___
*[`pkg/inspectz/inspectz.go` line 148 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/130270#-O6XBn9bA9uFQHJRCw4D:-O6arkWT-odlTqWhzF7a:b-bhe2eg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e89bcbc8f1ca46f69c2dfa6e213087e7dbd6bfef/pkg/inspectz/inspectz.go#L148)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This seems the same as `Server.KVFlowHandles` except for using `handlesV2`. Can this be unified into one function?
</blockquote></details>

We need to have both methods for the internal tables to call. I've simplified the logic however to unify the logic into a function.
___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowcontrol.go` line 323 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130270#-O6X9ryQ3TBWgQLvlrcT:-O6alte231yan1PF7Meu:b-deyaae) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0ef89d41ca509f2731b5779028bcf1ab7f7a817/pkg/kv/kvserver/kvflowcontrol/kvflowcontrol.go#L323)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Now that we have a specialized lookup method for the inspectz path, do we need `LookupInspect` to return an `InspectHandle` or can we simply make it return `(kvflowinspectpb.Handle, bool)`?
</blockquote></details>

We can, updated.
___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowinspectpb/kvflowinspect.proto` line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130270#-O6X-XvvAsKyP1v-Nb1Z:-O6afzB8EeW0jsQJK8f_:budqad4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4d0713625be976516e5e46eb997ef3923625ae3/pkg/kv/kvserver/kvflowcontrol/kvflowinspectpb/kvflowinspect.proto#L84)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

v24.3?
</blockquote></details>

Should be v24.3, I've mixed these up a few times w/ the innovation release.
___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowinspectpb/kvflowinspect.proto` line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130270#-O6X-bSn5tu5XPLtkKyD:-O6agAWX4AMGoncEnYuk:b-wzoztk) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4d0713625be976516e5e46eb997ef3923625ae3/pkg/kv/kvserver/kvflowcontrol/kvflowinspectpb/kvflowinspect.proto#L93)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

should this say "deducted for evaluation"?
(we don't actually deduct them before evaluation)
</blockquote></details>

It should. Updated.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 422 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130270#-O6X0ukOD3WLoj4_82bx:-O6agxZEBDsyJrVuuJa1:bybt34w) ([raw file](https://github.com/cockroachdb/cockroach/blob/4beff4715905afad323514d3caecc90b1470f6e4/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L422)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

`rc.mu` does not protect `replicaMap`, IIRC.
We are relying on external synchronization, specifically `raftMu` for this.

As mentioned in https://cockroachlabs.slack.com/archives/C06UFBJ743F/p1726018900176919?thread_ts=1726008270.371049&cid=C06UFBJ743F, I think it is acceptable to rename this `InspectRaftMuLocked` and have the caller acquire `raftMu`. The higher latency is fine for inspectz and querying the internal tables.
</blockquote></details>

It doesn't. Updated the method naming and removed the locking.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130270#-O6X2bfC5P2qDJ40YfGP:-O6ahovTAtUcLZuDUNdQ:b-e5lmk0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4beff4715905afad323514d3caecc90b1470f6e4/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L112)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is there a reason this is sorting the tuple (tenant-id, store-id), while `rangeController.Inspect` is sorting `(store-id, tenant-id)`?
</blockquote></details>

There is no reason. I've updated rangeController to sort on tenant, store.
___
*[`pkg/server/server.go` line 1134 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/130270#-O6XCdR-60Te0E2yyvEg:-O6ariZvDaQQ94FvVnp5:b-evamch) ([raw file](https://github.com/cockroachdb/cockroach/blob/e89bcbc8f1ca46f69c2dfa6e213087e7dbd6bfef/pkg/server/server.go#L1134)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

It just happens that `MakeStoresForRACv2` is casting `stores` and does not have some additional state, so calling `MakeStoresForRACv2` a second time does not accidentally create a second object when it is expected to be a singleton. We shouldn't rely on this. I think we already have `storesForRACv2` as a local variable from earlier in this function, and should use it here.
</blockquote></details>

Updated to use the local var.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/inspect` line 224 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130270#-O6X41Aj0jJhCTqfhfuc:-O6aiLzn3g2ZAQI09enU:b-amwmyl) ([raw file](https://github.com/cockroachdb/cockroach/blob/4beff4715905afad323514d3caecc90b1470f6e4/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/inspect#L224)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think we should not consider s3 to have a connected stream. Currently the code does
```
		if rs.sendStream == nil {
			continue
		}
```
and since it was in StateReplicate and transitioned to StateSnapshot we still have the `replicaSendStream` and print the state below. Up to you whether you want to change this now, or wait until the equivalent of https://github.com/cockroachdb/cockroach/pull/130168 where all transitions to StateSnapshot close the `replicaSendStream`.
</blockquote></details>

I'll wait until the equivalent of #130168, you're right it shouldn't be included.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 27 files at r6, 5 of 16 files at r7, 6 of 9 files at r8, 3 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130270#-:-O6blAAZ1KPlxN0IaO8b:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/inspectz/inspectz.go` line 115 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/130270#-O6bjknXBbWm_6CgXQei:-O6bjknXBbWm_6CgXQej:bbgs7ry) ([raw file](https://github.com/cockroachdb/cockroach/blob/97e837cd63a662083d96f8baa4f3fddaaac5865c/pkg/inspectz/inspectz.go#L115)):*
> ```Go
> 	ctx context.Context, request *kvflowinspectpb.ControllerRequest,
> ) (*kvflowinspectpb.ControllerResponse, error) {
> 	return &kvflowinspectpb.ControllerResponse{
> ```

can this use the `kvFlowController` method?

**Review by kvoli — COMMENTED** [review]
TYFTR! I pushed a few more test file changes related to the new internal tables to appease logic tests which are affected.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130270#-:-O6c4Pqz58knvqN4kAf7:b-1l5o0l)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mw5h and @sumeerbhola)

___
*[`pkg/inspectz/inspectz.go` line 115 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/130270#-O6bjknXBbWm_6CgXQei:-O6c4O0D5b1iHomcRRYg:bk6okhh) ([raw file](https://github.com/cockroachdb/cockroach/blob/97e837cd63a662083d96f8baa4f3fddaaac5865c/pkg/inspectz/inspectz.go#L115)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can this use the `kvFlowController` method?
</blockquote></details>

It can, I missed it. Done.

**Comment by kvoli** [comment]
bors r=sumeerbhola

**Comment by kvoli** [comment]
Merge skew, going to rebase and go again.

**Comment by kvoli** [comment]
bors r=sumeerbhola

**Comment by msbutler** [comment]
@kvoli it looks like this pr modified the `crdb_internal_catalog` logic test to verify the schema of every crdb_internal vtable. what was the motivation for adding this check? I ask because now every time anybody updates a crdb_internal table (which my team at least does all the time), they need to rewrite this test, which is a minor annoyance and could lead to merge conflicts.

**Comment by kvoli** [comment]
@msbutler that was unintentional, I assumed it was necessary from gleaning other PRs but from your message I am guessing thats not correct. We can and should remove it if its causing inconvenience.

**Pull request merged**
