### PR TITLE
rac2,kvserver: do not quiesce if send tokens held

### LINKED ISSUE #129581: rac2: prevent range quiescing if admitted is lagging for any replica
Sequence after the work in https://github.com/cockroachdb/cockroach/issues/129508

Epic [CRDB-37515](https://cockroachlabs.atlassian.net/browse/CRDB-37515)

Jira issue: CRDB-41603

Epic CRDB-37515

### PR DESCRIPTION
**Pull request by pav-kv**
This PR prevents range quiescence if RACv2 holds any send tokens for this range. Quiescence would prevent `MsgApp` pings which ensure that the leader reliably learns about the follower store admitting log entries, and causes it to release tokens accordingly. We do not want to end up holding tokens permanently.

Resolves #129581

### CODE REVIEW

**Comment by pav-kv** [comment]
The 4th commit is the interesting one. The rest is clean-ups.

**Comment by pav-kv** [comment]
`TestFlowControlQuiescedRangeV2` is failing, need to fix.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 9 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132166#-:-O8h1DslCQSyZJ0pksFN:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

___
*[`pkg/kv/kvserver/replica_raft_quiesce.go` line 446 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/132166#-O8gzOpz7g_WAQ6xbD-b:-O8gzOpz7g_WAQ6xbD-c:b6v9ovt) ([raw file](https://github.com/cockroachdb/cockroach/blob/51e708c0e7dc176dc259aa4038095144021ee398/pkg/kv/kvserver/replica_raft_quiesce.go#L446)):*
> ```Go
> 	}
> 	slices.SortFunc(lagging, func(a, b livenesspb.Liveness) int {
> 		return cmp.Compare(a.NodeID, b.NodeID)
> ```

is this sorting for determinism in tests, since sorting by NodeID seems unnecessary?
___
*[`pkg/kv/kvserver/replica_raft_quiesce.go` line 216 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/132166#-O8h-WGr5MokiPYkeBSk:-O8h-WGr5MokiPYkeBSl:b5an9hq) ([raw file](https://github.com/cockroachdb/cockroach/blob/0301255407001b3e444cfd8846870648f0d1c83b/pkg/kv/kvserver/replica_raft_quiesce.go#L216)):*
> ```Go
> 	// TODO(pav-kv): this method is a one-off holding raftMu. It should be able to
> 	// do its job with only Replica.mu held.
> 	hasSendTokensRaftMuLocked() bool
> ```

If I am reading correctly, `shouldReplicaQuiesce` is only ever called with raftMu and Replica.mu held, so this seems unnecessary to fix. There is a performance cost to adding locking in `RangeController` where it currently manages with `raftMu` already being held (mutex locking shows up in cpu profiles), so I'd rather not add another Mutex.
___
*[`pkg/kv/kvserver/replica_raft_quiesce.go` line 284 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/132166#-O8h-zrT6uwu_evb6F8T:-O8h-zrUAxOWoYEDvzer:bmtvmii) ([raw file](https://github.com/cockroachdb/cockroach/blob/0301255407001b3e444cfd8846870648f0d1c83b/pkg/kv/kvserver/replica_raft_quiesce.go#L284)):*
> ```Go
> //
> // NOTE: The last 3 conditions are fairly, but not completely, overlapping.
> func shouldReplicaQuiesce(
> ```

suggest adding `RaftMuLockedReplicaMuLocked` suffix to this method.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 1169 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/132166#-O8h0U2P3aBdAPharkJ3:-O8h0U2P3aBdAPharkJ4:bnpkmtw) ([raw file](https://github.com/cockroachdb/cockroach/blob/0301255407001b3e444cfd8846870648f0d1c83b/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L1169)):*
> ```Go
> 	// TODO(pav-kv): in Replica.tick, we can call MaybeSendPingsRaftMuLocked
> 	// first, which does the same checks. It can return whether any tokens are
> 	// held, and this signal can be then used to prevent quiescence.
> ```

Would adding this logic into `MaybeSendPingsRaftMuLocked` help with code clarity (in the kvserver code) or performance?
Just trying to understand why this should be a TODO.

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132166)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/replica_raft_quiesce.go` line 446 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/132166#-O8gzOpz7g_WAQ6xbD-b:-O8qFLqO3m_xxgngWMrl:b-6elcex) ([raw file](https://github.com/cockroachdb/cockroach/blob/51e708c0e7dc176dc259aa4038095144021ee398/pkg/kv/kvserver/replica_raft_quiesce.go#L446)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is this sorting for determinism in tests, since sorting by NodeID seems unnecessary?
</blockquote></details>

I think so, but prefer not removing the sort in this PR. Looking at paths that use this `lagging` slice in the callers, they end up being [sent](https://github.com/cockroachdb/cockroach/blob/ee33a3c8d84d7319db468df952e6d2ddc63ec7ff/pkg/kv/kvserver/replica_raft.go#L1751) over the wire. I didn't find any usage of this proto field though... Might remove in another PR.
___
*[`pkg/kv/kvserver/replica_raft_quiesce.go` line 216 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/132166#-O8h-WGr5MokiPYkeBSk:-O8qIqMw1j8S4Sm_LOVE:bfpsm9i) ([raw file](https://github.com/cockroachdb/cockroach/blob/0301255407001b3e444cfd8846870648f0d1c83b/pkg/kv/kvserver/replica_raft_quiesce.go#L216)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

If I am reading correctly, `shouldReplicaQuiesce` is only ever called with raftMu and Replica.mu held, so this seems unnecessary to fix. There is a performance cost to adding locking in `RangeController` where it currently manages with `raftMu` already being held (mutex locking shows up in cpu profiles), so I'd rather not add another Mutex.
</blockquote></details>

The fact that `raftMu` is held in `tick` is odd and may change. Looking at the `tick` code, it is not used for anything (now used for RACv2 check). I am just documenting the interface irregularity here, but there is a bigger thing behind it.

The fact that RACv2 needs to hold `raftMu` everywhere in `Processer` is thus also a lucky coincidence. We might need to revisit that at some point, because we should be needing `raftMu` only for raft IO.
___
*[`pkg/kv/kvserver/replica_raft_quiesce.go` line 284 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/132166#-O8h-zrT6uwu_evb6F8T:-O8qIjHaAaFw5AfHzxAY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0301255407001b3e444cfd8846870648f0d1c83b/pkg/kv/kvserver/replica_raft_quiesce.go#L284)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

suggest adding `RaftMuLockedReplicaMuLocked` suffix to this method.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 1169 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/132166#-O8h0U2P3aBdAPharkJ3:-O8qEYNp9Nn3EADRIkQx:b-qr8fl2) ([raw file](https://github.com/cockroachdb/cockroach/blob/0301255407001b3e444cfd8846870648f0d1c83b/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L1169)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Would adding this logic into `MaybeSendPingsRaftMuLocked` help with code clarity (in the kvserver code) or performance?
Just trying to understand why this should be a TODO.
</blockquote></details>

Performance. We're doing the same loop over `rc.replicasMap` + locking in each `state`, so we could both send pings and check whether we can quiesce (none/any of `holdsTokens` returned false).

Clarified the comment.

**Comment by pav-kv** [comment]
bors r=sumeerbhola

**Comment by pav-kv** [comment]
One more test had to be fixed.

bors r=sumeerbhola

**Pull request merged**
