### PR TITLE
distsql: avoid unnecessary flushes in outbox

### PR DESCRIPTION
**Pull request by asubiotto**
Previously, the outbox would have a flush ticker that would fire whether
or not the outbox was empty. This change makes it so that we only ever
fire if we have rows to flush.

Addresses #22385 

Release note (performance improvement): performance improvement for
distributed sql queries.

`SELECT tpch.lineitem ORDER BY l_extendedprice LIMIT 1000`:`16%` improvement on a local 3-node cluster, `22%` improvement on a 6-node `roachprod` cluster.

This should be an across-the-board improvement noticed more with longer-running queries.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
*[pkg/sql/distsqlrun/outbox.go, line 246 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22471#-L4lhQHAgK3ILTBlvCo9:-L4lhQHAgK3ILTBlvCoA:b36px2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f167f206df6bfa304cce548bc3d48bfee84e25c9/pkg/sql/distsqlrun/outbox.go#L246)):*
> ```Go
> 				// this is our first row, restart the flushTimer.
> 				if m.numRows == 1 {
> 					flushTimer.Reset(outboxFlushPeriod)
> ```

See the [doc](https://golang.org/pkg/time/#Timer.Reset), I think Stop needs to be called.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22471)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/distsqlrun/outbox.go, line 201 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22471#-L4lhL2F8vwfMQ5nw0sH:-L4lhL2GEjaKg-JSajDM:b7lzis4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f167f206df6bfa304cce548bc3d48bfee84e25c9/pkg/sql/distsqlrun/outbox.go#L201)):*
> ```Go
> 	// TODO(asubiotto): Not sure if this is necessary. I want to avoid a useless
> 	// flush.
> 	flushTimer := time.NewTimer(0)
> ```

`time.Timer` is very hard to use correctly. You should use `timeutil.NewTimer` instead which is a small wrapper.  See the comment above `timeutil.Timer` for usage guidance. The upshot is that you create the timer as 

```
var flushTimer timeutil.Timer
defer flushTimer.Stop()
````

---

*[pkg/sql/distsqlrun/outbox.go, line 246 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22471#-L4lhQHAgK3ILTBlvCo9:-L4lhdpU6-12soQ3ZxVj:byy5r12) ([raw file](https://github.com/cockroachdb/cockroach/blob/f167f206df6bfa304cce548bc3d48bfee84e25c9/pkg/sql/distsqlrun/outbox.go#L246)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

See the [doc](https://golang.org/pkg/time/#Timer.Reset), I think Stop needs to be called.
</blockquote></details>

See my comment above. `time.Timer` is very hard to use correctly, thus we have `timeutil.Timer`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22471)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/distsqlrun/outbox.go, line 201 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22471#-L4lhhGGyLM9qGHXY7Mx:-L4lhhGGyLM9qGHXY7My:bsphszg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f167f206df6bfa304cce548bc3d48bfee84e25c9/pkg/sql/distsqlrun/outbox.go#L201)):*
> ```Go
> 	// TODO(asubiotto): Not sure if this is necessary. I want to avoid a useless
> 	// flush.
> 	flushTimer := time.NewTimer(0)
> ```

not a big deal, but this will probably make us go to sleep and require some other goroutine to wake us up immediately. Maybe just start with a large timeout

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22471)*

**Comment by petermattis** [comment]
Very nice that this achieves the performance benefit you were previously seeing with a longer flush interval.

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22471#-:-L4lhnnfCqCFA7PR0djJ:bq54zmj)*

**Comment by asubiotto** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/distsqlrun/outbox.go, line 201 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22471#-L4lhL2F8vwfMQ5nw0sH:-L4lkkQLKDFYR2s3eyJi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f167f206df6bfa304cce548bc3d48bfee84e25c9/pkg/sql/distsqlrun/outbox.go#L201)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`time.Timer` is very hard to use correctly. You should use `timeutil.NewTimer` instead which is a small wrapper.  See the comment above `timeutil.Timer` for usage guidance. The upshot is that you create the timer as 

```
var flushTimer timeutil.Timer
defer flushTimer.Stop()
````

</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/outbox.go, line 201 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22471#-L4lhhGGyLM9qGHXY7Mx:-L4lm8QrtgJT10qeoQwZ:b-th5z7c) ([raw file](https://github.com/cockroachdb/cockroach/blob/f167f206df6bfa304cce548bc3d48bfee84e25c9/pkg/sql/distsqlrun/outbox.go#L201)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

not a big deal, but this will probably make us go to sleep and require some other goroutine to wake us up immediately. Maybe just start with a large timeout
</blockquote></details>

Solved by the use of `timeutil.Timer`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22471)*

**Comment by jordanlewis** [comment]
:lgtm: the ratio of lines changed to performance improvement on this one is off the charts - awesome!

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22471#-:-L4llNqm6JJlCu9Awepk:bobpj6l)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22471#-:-L4lpkoPCppfbMXymXpq:bnfp4nl)*

**Comment by petermattis** [comment]
:lgtm:

You mentioned earlier that you saw a 25% improvement from a larger `outboxBufRows` and longer `ouboxFlushPeriod`. I'm wondering if there is a bit of further experimentation here (i.e. bumping `outboxBufRows`), or if that earlier 25% was really 22%.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22471#-:-L4luiXt-UWiwpunu713:b7cn6v8)*

**Comment by asubiotto** [comment]
Maybe, I'll definitely do some more experimenting.

**Pull request merged**
