### PR TITLE
sql: support array_agg with arrays as inputs

### LINKED ISSUE #117756: sql: support to array_agg() for arrays
**Is your feature request related to a problem? Please describe.**

Minimum reproduction:

```
        => SELECT version();
┌───────────────────────────────────────────────────────────────────────────────────────────┐
│                                          version                                          │
├───────────────────────────────────────────────────────────────────────────────────────────┤
│ CockroachDB CCL v22.2.17 (aarch64-unknown-linux-gnu, built 2023/11/20 16:09:42, go1.19.6) │
└───────────────────────────────────────────────────────────────────────────────────────────┘
(1 row)
        => CREATE TABLE __test_array_agg(a TEXT PRIMARY KEY, b TEXT, c TEXT);
CREATE TABLE
        => SELECT array_agg(array[a, b, c]) FROM __test_array_agg;
ERROR:  unknown signature: array_agg(string[])
```

**Describe alternatives you've considered**

> I was trying to come up with workarounds and got a close approximation, but it returns record[] instead of text[] like postgres does.
```
select array_agg(t.*) from __test_array_agg as t;
```

Jira issue: CRDB-35334

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit extends `array_agg` aggregate function to support arrays as their input. The result of such aggregation is a nested array, and the existing implementation simply works for that case.

The main complication of this change is that we currently don't support multidimensional arrays in all cases, so previously we would disallow it in a few places (like when creating a command result with a nested array type). This commit had to remove that limitation since it was too broad. There are still things that we don't support (e.g. in CREATE TABLE context, or when the nested array needs to be serialized (we don't have value encoding for it)), so in those cases we will keep on returning errors.

Fixes: #117756.

Release note (sql change): `array_agg` aggregate function can now support arrays as the input. Note, however, that CockroachDB still doesn't have full support of nested arrays (that is tracked by https://github.com/cockroachdb/cockroach/issues/32552), and `array_agg` doesn't support nested arrays as inputs either.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117838)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @michae2)

___
*[`pkg/sql/opt/optbuilder/scalar.go` line 154 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117838#-NoOYtn40cYoFyR4lZUY:-NoOYtn40cYoFyR4lZUZ:bheqmux) ([raw file](https://github.com/cockroachdb/cockroach/blob/624885c463ddd4eecb406b863c78b49b683bbca9/pkg/sql/opt/optbuilder/scalar.go#L154)):*
> ```Go
> 		// Thus, we reject a query that is correlated and over a type that we can't array_agg.
> 		typ := b.factory.Metadata().ColumnMeta(inCol).Type
> 		if !s.outerCols.Empty() && !memo.AggregateOverloadExists(opt.ArrayAggOp, typ) {
> ```

This seems like a thing we can remove since we now do have overloads for `array_agg` for all (or at least most) types, but let me know if we should keep this check, just to be safe.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117838)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @michae2, and @yuzefovich)

___
*[`pkg/sql/logictest/testdata/logic_test/array` line 121 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117838#-NoO_C5zCpf2cyLmXWVz:-NoO_C5zCpf2cyLmXWW-:b-5yy3vb) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c267aeabbef59f667f93e4b44d3918a5d9e1a2/pkg/sql/logictest/testdata/logic_test/array#L121)):*
> ```
> {1,2,1}
> 
> # This query works in local config but can fail in distributed config since the
> ```

could we also add a test for a non-local mode to make sure there is still a proper error message in those cases?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117838)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @michae2, and @rafiss)

___
*[`pkg/sql/logictest/testdata/logic_test/array` line 121 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117838#-NoO_C5zCpf2cyLmXWVz:-NoOcMOa-5AwdlDMJILe:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c267aeabbef59f667f93e4b44d3918a5d9e1a2/pkg/sql/logictest/testdata/logic_test/array#L121)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could we also add a test for a non-local mode to make sure there is still a proper error message in those cases?
</blockquote></details>

Good point, done.

**Review by DrewKimball — COMMENTED** [review]
What happens if the nesting is deeper than one level?
Ex:
```
WITH
  foo AS (SELECT array_agg(x) FROM generate_series(1, 3) g(x)),
  bar AS (SELECT array_agg(y) FROM (SELECT foo.* FROM foo, generate_series(1, 3)) v(y))
SELECT array_agg(z) FROM (SELECT bar.* FROM bar, generate_series(1, 3)) v(z);
```

> Reviewed 7 of 7 files at r1, 11 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117838#-:-NoQLwy25xxUbEStDq_F:b-czajve)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @michae2, @rafiss, and @yuzefovich)

___
*[`pkg/sql/opt/optbuilder/scalar.go` line 154 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117838#-NoOYtn40cYoFyR4lZUY:-NoQMBSbBv3Z3gKPkAaa:b-mm6jtq) ([raw file](https://github.com/cockroachdb/cockroach/blob/624885c463ddd4eecb406b863c78b49b683bbca9/pkg/sql/opt/optbuilder/scalar.go#L154)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

This seems like a thing we can remove since we now do have overloads for `array_agg` for all (or at least most) types, but let me know if we should keep this check, just to be safe.
</blockquote></details>

If we don't support nesting deeper than one level, we'd better still check for that case.

**Review by yuzefovich — COMMENTED** [review]
Indeed, good callout - we return an error because we cannot find the `array_agg` overload that takes in two-dimensional array as the input. Added a test and adjusted the release note to mention this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117838#-:-NoTV_1B81o80hwAbbEy:bfjpiym)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @michae2, and @rafiss)

___
*[`pkg/sql/opt/optbuilder/scalar.go` line 154 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117838#-NoOYtn40cYoFyR4lZUY:-NoTVtwc4hlNh-5dP8bR:b-xcpefx) ([raw file](https://github.com/cockroachdb/cockroach/blob/624885c463ddd4eecb406b863c78b49b683bbca9/pkg/sql/opt/optbuilder/scalar.go#L154)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

If we don't support nesting deeper than one level, we'd better still check for that case.
</blockquote></details>

Ack, reverted this deletion.

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 1 of 14 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117838#-:-NoTetUC4vCk4FSBTqcQ:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @rafiss)

**Comment by yuzefovich** [comment]
Thanks for the reviews!

bors r+

**Pull request merged**
