### PR TITLE
sql: Move NormalizeName to parser

### LINKED ISSUE #8320: sql: move NormalizeName to parser
Suggested by @tamird in https://github.com/cockroachdb/cockroach/pull/8152#issuecomment-236402119

This would enable NormalizeTableName to become a method of TableName in parser too, where it belongs.

### PR DESCRIPTION
**Pull request by a6802739**
Fixes #8320. @knz , sorry for late deal with this issue. please let me know if I've done it right.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10105)

### CODE REVIEW

**Comment by knz** [comment]
Thanks for dealing with this!

Please run `make check` locally first and deal with the error. I think there's something remaining there that TeamCity is not happy about.

**Comment by a6802739** [comment]
@knz, thanks for review this. 
I run `make check` in my local branch again, it seems ok.
```
--- PASS: TestStyle (0.00s)
    --- SKIP: TestStyle/TestReturnCheck (0.00s)
    	style_test.go:620: TODO(dt): need to update this upstream or pull it into repo
    --- PASS: TestStyle/TestCopyrightHeaders (0.11s)
    --- PASS: TestStyle/TestCrlfmt (3.46s)
    --- PASS: TestStyle/TestIneffassign (5.76s)
    --- PASS: TestStyle/TestMisspell (11.20s)
    --- PASS: TestStyle/TestImportNames (0.14s)
    --- PASS: TestStyle/TestProtoMarshal (0.07s)
    --- PASS: TestStyle/TestGofmtSimplify (14.77s)
    --- PASS: TestStyle/TestProtoClone (0.10s)
    --- PASS: TestStyle/TestVet (29.15s)
    --- PASS: TestStyle/TestGrpc (0.07s)
    --- PASS: TestStyle/TestTabsInShellScripts (0.01s)
    --- PASS: TestStyle/TestEnvutil (0.07s)
    --- PASS: TestStyle/TestMissingLeakTest (0.95s)
    --- PASS: TestStyle/TestTimeutil (0.07s)
    --- PASS: TestStyle/TestErrCheck (32.58s)
    --- PASS: TestStyle/TestSyncutil (0.07s)
    --- PASS: TestStyle/TestUnconvert (22.64s)
    --- PASS: TestStyle/TestForbiddenImports (2.21s)
    --- PASS: TestStyle/TestStaticcheck (29.73s)
    --- PASS: TestStyle/TestGolint (21.45s)
    --- PASS: TestStyle/TestGoSimple (26.04s)
    --- PASS: TestStyle/TestUnused (26.42s)
PASS
ok  	github.com/cockroachdb/cockroach/build	61.297s
```

**Comment by knz** [comment]
Thanks! It seems to work now.

LGTM.
@tamird what do you think? It was you who suggested this refactoring initially.

**Comment by tamird** [comment]
Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/table_name.go, line 140 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10105#-KUwap7cVtDerwsZHzX6:-KUwap7cVtDerwsZHzX7:b-3n2iri) ([raw file](https://github.com/cockroachdb/cockroach/blob/d84e4452736cdeac77eddd56edeaf8be3ec83aed/pkg/sql/parser/table_name.go#L140)):*
> ```Go
> // NormalizeForCompare normalizes to lowercase and Unicode Normalization Form C
> // (NFC).
> func NormalizeForCompare(name Name) string {
> ```

Didn't we want this to be a method?

---

*[pkg/sql/parser/table_name.go, line 156 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10105#-KUwaseFPTPS55xjJXSQ:-KUwaseFPTPS55xjJXSR:b-u1g0v2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d84e4452736cdeac77eddd56edeaf8be3ec83aed/pkg/sql/parser/table_name.go#L156)):*
> ```Go
> 
> // EqualName returns true iff the normalizations of a and b are equal.
> func EqualName(a, b Name) bool {
> ```

surely this can be a method as well (Equal)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10105)*

**Comment by tamird** [comment]
Please amend the commit message to include the string "Fixes #8320" so that GitHub automatically closes the issue when this merges. :lgtm: aside from minor comments.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10105#-:-KUwb0PP1B32mR_DqY4I:b-lgts8p)*

**Comment by a6802739** [comment]
@tamird, thanks for you review.
 It seems I still have no privilege to merge my PR right now.

**Comment by tamird** [comment]
@a6802739 do you see anything here? https://github.com/cockroachdb/cockroach/invitations

**Comment by tamird** [comment]
But also, please address my comments before merging.

**Comment by a6802739** [comment]
@tamird, yeah, I will first address your comments. 
It seems I need a two-factor authentication now.
thanks for your invite.

**Comment by a6802739** [comment]
Review status: 5 of 23 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/table_name.go, line 140 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10105#-KUwap7cVtDerwsZHzX6:-KV-PrD8d91_WQ2QBpxM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d84e4452736cdeac77eddd56edeaf8be3ec83aed/pkg/sql/parser/table_name.go#L140)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Didn't we want this to be a method?
</details>
Done.

---

*[pkg/sql/parser/table_name.go, line 156 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10105#-KUwaseFPTPS55xjJXSQ:-KV-Pwniel7q7V2G1kMP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d84e4452736cdeac77eddd56edeaf8be3ec83aed/pkg/sql/parser/table_name.go#L156)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> surely this can be a method as well (Equal)?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10105)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 19 of 19 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/normalize_test.go, line 22 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10105#-KV0PWCpvA4H5lY19Ac-:-KV0OPRYo3H0zJSIqk8c:b2ow70u) ([raw file](https://github.com/cockroachdb/cockroach/blob/464a22d786d480a8747d3356c66eefccbb263f6d/pkg/sql/parser/normalize_test.go#L22)):*
> ```Go
> import "github.com/cockroachdb/cockroach/pkg/util/leaktest"
> 
> func TestNormalizeName(t *testing.T) {
> ```

TestReNormalizeName

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10105#-:-KV0P-1VEQPcRWdFkT3f:bnfp4nl)*

**Comment by a6802739** [comment]
Review status: 22 of 23 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/parser/normalize_test.go, line 22 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10105#-KV0PWCpvA4H5lY19Ac-:-KV34hlKPcXvDcYoXFLI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/464a22d786d480a8747d3356c66eefccbb263f6d/pkg/sql/parser/normalize_test.go#L22)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> TestReNormalizeName
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10105)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10105)*

**Comment by a6802739** [comment]
@tamird , could I merge this PR now?

**Comment by knz** [comment]
Yes you can!

**Comment by mjibson** [comment]
@a6802739 This broke the master build due to a merge skew.

**Comment by knz** [comment]
on it

**Comment by tamird** [comment]
Yes

**Pull request merged**
