### PR TITLE
sqlproxyccl: statistically load balance across tenants

### PR DESCRIPTION
**Pull request by chrisseto**
Previously, the SQLProxy's Directory implementation would always
    select the first instance from the pods list. As part of the
    SQLProxy's duty is load balancing, this was inadequate. This commit
    upgrades the tenant dir to have pods report their CPU load. This
    load is then used to perform a weighted distribution across all
    running tenant pods.

Release note: None

### CODE REVIEW

**Review by andy-kimball — APPROVED** [review]
:lgtm:, except for the RNG thread-safety issue. @darinpp should also take a look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66850#-:-Md0N-CL3tQJ3XrxZ9OK:ba02qqu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @chrisseto)

___
*[pkg/ccl/sqlproxyccl/tenant/directory.go, line 175 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66850#-Md0HnCF4k8z8rZSZlm1:-Md0HnCF4k8z8rZSZlm2:b-5vfdn5) ([raw file](https://github.com/cockroachdb/cockroach/blob/eea8182998629c8ac82bf1680c09c7ce1aa8b358/pkg/ccl/sqlproxyccl/tenant/directory.go#L175)):*
> ```Go
> 			codes.NotFound, "tenant %d not in directory cache", tenantID.ToUint64())
> 	}
> 	tenantPods := entry.getPods()
> ```

UBER-NIT: Add a blank line before this. I treat blank lines like paragraph breaks; they break up code by cohesive "ideas". In this case, we're beginning a new idea, which is to get pod addresses. Doing this makes code easier to read, just as paragraphs do in writing.
___
*[pkg/ccl/sqlproxyccl/tenant/directory.go, line 341 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66850#-Md0I73H4oCyVRgg4gMS:-Md0I73H4oCyVRgg4gMT:bxmbiwm) ([raw file](https://github.com/cockroachdb/cockroach/blob/eea8182998629c8ac82bf1680c09c7ce1aa8b358/pkg/ccl/sqlproxyccl/tenant/directory.go#L341)):*
> ```Go
> 			}
> 
> 			podLoad := resp.Load
> ```

UBER-NIT: This is the reverse of the last comment: I'd remove the blank line after podLoad, b/c it's very much connected with the "idea", which is to extract and check pod fields.
___
*[pkg/ccl/sqlproxyccl/tenant/entry.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66850#-Md0InBZEpiF7VrNbRfF:-Md0InBZEpiF7VrNbRfG:bsgoecx) ([raw file](https://github.com/cockroachdb/cockroach/blob/eea8182998629c8ac82bf1680c09c7ce1aa8b358/pkg/ccl/sqlproxyccl/tenant/entry.go#L25)):*
> ```Go
> )
> 
> // tenantPod is a single instance of a tenant running at the specificed
> ```

NIT: I think we should break this struct and `selectTenantPod` into its own file. My general rule of thumb is to split out each struct into its own file unless it's trivial and doesn't force the main parts of the file (i.e. tenantEntry) so far down that I have to scroll down a ways to see it. Ideally, for a file called "entry", the "entry" struct is visible in the first page of an editor.
___
*[pkg/ccl/sqlproxyccl/tenant/entry.go, line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66850#-Md0Jy7_CCreBW1GvQWJ:-Md0Jy7_CCreBW1GvQWK:b5jzpvn) ([raw file](https://github.com/cockroachdb/cockroach/blob/eea8182998629c8ac82bf1680c09c7ce1aa8b358/pkg/ccl/sqlproxyccl/tenant/entry.go#L85)):*
> ```Go
> 	initError error
> 
> 	rng *rand.Rand
> ```

`randutil.NewPseudoRand` is not safe for concurrent access, so it needs to be protected by the `pods` mutex when used.
___
*[pkg/ccl/sqlproxyccl/tenant/entry.go, line 169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66850#-Md0KPFdEoBG-l9pIr4x:-Md0KPFdEoBG-l9pIr4y:bu1mf61) ([raw file](https://github.com/cockroachdb/cockroach/blob/eea8182998629c8ac82bf1680c09c7ce1aa8b358/pkg/ccl/sqlproxyccl/tenant/entry.go#L169)):*
> ```Go
> // are no pods available rather than blocking.
> //
> // TODO(andyk): Use better load-balancing algorithm once tenants can have more
> ```

NIT: Can remove this comment now.
___
*[pkg/ccl/sqlproxyccl/tenant/entry_test.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66850#-Md0MfXq-PLM4KAhXmmt:-Md0MfXq-PLM4KAhXmmu:bj6v0bd) ([raw file](https://github.com/cockroachdb/cockroach/blob/eea8182998629c8ac82bf1680c09c7ce1aa8b358/pkg/ccl/sqlproxyccl/tenant/entry_test.go#L36)):*
> ```Go
> 	}
> 
> 	// Assert that the distribution
> ```

NIT: comment is incomplete

**Review by chrisseto — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66850#-:-Md2sbbv0dq-u9YkClAU:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @chrisseto)

___
*[pkg/ccl/sqlproxyccl/tenant/directory.go, line 175 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66850#-Md0HnCF4k8z8rZSZlm1:-Md2q2Wp8PlujQX2keNV:bxj3foy) ([raw file](https://github.com/cockroachdb/cockroach/blob/eea8182998629c8ac82bf1680c09c7ce1aa8b358/pkg/ccl/sqlproxyccl/tenant/directory.go#L175)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

UBER-NIT: Add a blank line before this. I treat blank lines like paragraph breaks; they break up code by cohesive "ideas". In this case, we're beginning a new idea, which is to get pod addresses. Doing this makes code easier to read, just as paragraphs do in writing.
</blockquote></details>

Agreed, I'm not sure why I missed this line.
___
*[pkg/ccl/sqlproxyccl/tenant/directory.go, line 341 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66850#-Md0I73H4oCyVRgg4gMS:-Md2q6J2Aj4FqIm6iukk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eea8182998629c8ac82bf1680c09c7ce1aa8b358/pkg/ccl/sqlproxyccl/tenant/directory.go#L341)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

UBER-NIT: This is the reverse of the last comment: I'd remove the blank line after podLoad, b/c it's very much connected with the "idea", which is to extract and check pod fields.
</blockquote></details>

Done.
___
*[pkg/ccl/sqlproxyccl/tenant/entry.go, line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66850#-Md0Jy7_CCreBW1GvQWJ:-Md2qWVWBhRwwKUkZTwM:bnoa21v) ([raw file](https://github.com/cockroachdb/cockroach/blob/eea8182998629c8ac82bf1680c09c7ce1aa8b358/pkg/ccl/sqlproxyccl/tenant/entry.go#L85)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

`randutil.NewPseudoRand` is not safe for concurrent access, so it needs to be protected by the `pods` mutex when used.
</blockquote></details>

Done. Move the `rng` into the `pods` struct. I'm guessing it won't matter that much but we have added another point to lock just for the rng. Would it be better to give the rng its own mutex?
___
*[pkg/ccl/sqlproxyccl/tenant/entry.go, line 169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66850#-Md0KPFdEoBG-l9pIr4x:-Md2qUtk8CaVhTYPEj0E:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eea8182998629c8ac82bf1680c09c7ce1aa8b358/pkg/ccl/sqlproxyccl/tenant/entry.go#L169)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: Can remove this comment now.
</blockquote></details>

Done.
___
*[pkg/ccl/sqlproxyccl/tenant/entry_test.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66850#-Md0MfXq-PLM4KAhXmmt:-Md2rDO304YTusZDyyi3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eea8182998629c8ac82bf1680c09c7ce1aa8b358/pkg/ccl/sqlproxyccl/tenant/entry_test.go#L36)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: comment is incomplete
</blockquote></details>

Done.

**Review by andy-kimball — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66850)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @chrisseto)

___
*[pkg/ccl/sqlproxyccl/tenant/entry.go, line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66850#-Md0Jy7_CCreBW1GvQWJ:-Md3Nth71_95YRLA6qyx:b49hyp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/eea8182998629c8ac82bf1680c09c7ce1aa8b358/pkg/ccl/sqlproxyccl/tenant/entry.go#L85)):*
<details><summary><i>Previously, chrisseto (Chris Seto) wrote…</i></summary><blockquote>

Done. Move the `rng` into the `pods` struct. I'm guessing it won't matter that much but we have added another point to lock just for the rng. Would it be better to give the rng its own mutex?
</blockquote></details>

I do have one suggestion below to avoid locking for longer than necessary.
___
*[pkg/ccl/sqlproxyccl/tenant/entry.go, line 151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66850#-Md3NP8K0iYIJcO7doSr:-Md3NP8K0iYIJcO7doSs:b-uc5x3y) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dcf58b39af12dcefa68a7ccf40fde511c7af90d/pkg/ccl/sqlproxyccl/tenant/entry.go#L151)):*
> ```Go
> 	}
> 
> 	e.pods.Lock()
> ```

You only need a single random number for `selectTenantPod`. Perhaps generate it here and pass it in? Or maybe you could make `selectTenantPod` a member of `tenantEntry` so you have direct access to the rng and can put a bit of code directly into that routine:
```
func (e *tenantEntry) randFloat32() float32 {
  e.pods.Lock()
  defer e.pods.Unlock()
  return e.pods.rng.Float32()
}
```

**Review by darinpp — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66850)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @chrisseto)

___
*[pkg/ccl/sqlproxyccl/tenant/entry.go, line 171 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66850#-MdSnWGy9DOlJ3wv74hg:-MdSnWGy9DOlJ3wv74hh:bth5bd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f7ae1b179ee85a36b87862b5028ec298ca19534/pkg/ccl/sqlproxyccl/tenant/entry.go#L171)):*
> ```Go
> 	for i, existing := range e.pods.pods {
> 		if existing.Addr == addr {
> 			// Clone pods to avoid modifiying entries that may have been
> ```

It isn't clear why the entries shouldn't be modified. This needs a better comment explaining why that is the case.
___
*[pkg/ccl/sqlproxyccl/tenant/pod.go, line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66850#-MdSoxJb6y4e9L5X8S9Z:-MdSoxJb6y4e9L5X8S9_:b-omejku) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f7ae1b179ee85a36b87862b5028ec298ca19534/pkg/ccl/sqlproxyccl/tenant/pod.go#L25)):*
> ```Go
> // incoming traffic. Pods are weighted by their reported CPU load. rand must be
> // a pseudo random number within the bounds [0, 1).
> func selectTenantPod(rand float32, pods []tenantPod) tenantPod {
> ```

This also need an explanation. It isn't clear at a first glance how `rand` is used to choose a pod . Perhaps put an example here.

**Review by chrisseto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66850)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @darinpp)

___
*[pkg/ccl/sqlproxyccl/tenant/entry.go, line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66850#-Md0Jy7_CCreBW1GvQWJ:-MeR39CS0s2nYeLV7M3W:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eea8182998629c8ac82bf1680c09c7ce1aa8b358/pkg/ccl/sqlproxyccl/tenant/entry.go#L85)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I do have one suggestion below to avoid locking for longer than necessary.
</blockquote></details>

Done.
___
*[pkg/ccl/sqlproxyccl/tenant/entry.go, line 151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66850#-Md3NP8K0iYIJcO7doSr:-MeR38PJ0h_I-o5-OEpr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dcf58b39af12dcefa68a7ccf40fde511c7af90d/pkg/ccl/sqlproxyccl/tenant/entry.go#L151)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

You only need a single random number for `selectTenantPod`. Perhaps generate it here and pass it in? Or maybe you could make `selectTenantPod` a member of `tenantEntry` so you have direct access to the rng and can put a bit of code directly into that routine:
```
func (e *tenantEntry) randFloat32() float32 {
  e.pods.Lock()
  defer e.pods.Unlock()
  return e.pods.rng.Float32()
}
```
</blockquote></details>

Done.
___
*[pkg/ccl/sqlproxyccl/tenant/entry.go, line 171 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66850#-MdSnWGy9DOlJ3wv74hg:-MeR2vOjEt1hF8-O31vO:bo1q7up) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f7ae1b179ee85a36b87862b5028ec298ca19534/pkg/ccl/sqlproxyccl/tenant/entry.go#L171)):*
<details><summary><i>Previously, darinpp wrote…</i></summary><blockquote>

It isn't clear why the entries shouldn't be modified. This needs a better comment explaining why that is the case.
</blockquote></details>

entries are now a list of *Pod proto values and this no longer applies.
___
*[pkg/ccl/sqlproxyccl/tenant/pod.go, line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66850#-MdSoxJb6y4e9L5X8S9Z:-MeR349lBcBwiR0gMXps:b-ouyad8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f7ae1b179ee85a36b87862b5028ec298ca19534/pkg/ccl/sqlproxyccl/tenant/pod.go#L25)):*
<details><summary><i>Previously, darinpp wrote…</i></summary><blockquote>

This also need an explanation. It isn't clear at a first glance how `rand` is used to choose a pod . Perhaps put an example here. 
</blockquote></details>

Added a snippet and a suggestion to use rand.Float32()

**Review by jaylim-crl — COMMENTED** [review]
> Reviewed 9 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66850)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @chrisseto, and @darinpp)

___
*[pkg/ccl/sqlproxyccl/tenant/directory.proto, line 42 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66850#-MeR8AekDThArBFTzYIn:-MeR8AekDThArBFTzYIo:b-jppyn0) ([raw file](https://github.com/cockroachdb/cockroach/blob/56d7a82d3790cae668d72d939e24b34fc11dfb2b/pkg/ccl/sqlproxyccl/tenant/directory.proto#L42)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>   // UNKNOWN indicates that the pod values being reported are from a
>   // potentially out of date source. UNKNOWN may be used to notify updates to
>   // pod values when the pod's state may be out of date by the time the update
>   // is processed.
>   UNKNOWN = 3;
> ```
</details>


How do we know that the source is potentially out of date? Do you have an example of a scenario? In particular, I'm looking at the logic here: `tenantdir/main.go#L163-L191` in CC.

> Load reporters may elect to use the new UNKNOWN
    state to indicate their updates should be ignored if the proxy is
    unaware of a running pod at the given address.

What are the implications of using RUNNING in that case? I wonder if the new state is necessary, and whether we can piggy back on the existing states.
___
*[pkg/ccl/sqlproxyccl/tenant/entry.go, line 159 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66850#-MeR7D0d5fo3lIAE69qz:-MeR7D0d5fo3lIAE69r-:b-v5rqu7) ([raw file](https://github.com/cockroachdb/cockroach/blob/56d7a82d3790cae668d72d939e24b34fc11dfb2b/pkg/ccl/sqlproxyccl/tenant/entry.go#L159)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 			pods := e.pods.pods
> 			e.pods.pods = make([]*Pod, len(pods))
> 			copy(e.pods.pods, pods)
> 			e.pods.pods[i] = pod
> ```
</details>


Why do we need to perform a copy here? Maybe a comment would be helpful. Same goes to the logic in UpdatePod.

**Review by chrisseto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66850)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @darinpp, and @jaylim-crl)

___
*[pkg/ccl/sqlproxyccl/tenant/directory.proto, line 42 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66850#-MeR8AekDThArBFTzYIn:-MeRB2yxBxiM_z1OdaQR:b-bibhxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/56d7a82d3790cae668d72d939e24b34fc11dfb2b/pkg/ccl/sqlproxyccl/tenant/directory.proto#L42)):*
<details><summary><i>Previously, jaylim-crl (Jay Lim) wrote…</i></summary><blockquote>

> ```
>   // UNKNOWN indicates that the pod values being reported are from a
>   // potentially out of date source. UNKNOWN may be used to notify updates to
>   // pod values when the pod's state may be out of date by the time the update
>   // is processed.
>   UNKNOWN = 3;
> ```

How do we know that the source is potentially out of date? Do you have an example of a scenario? In particular, I'm looking at the logic here: `tenantdir/main.go#L163-L191` in CC.

> Load reporters may elect to use the new UNKNOWN
    state to indicate their updates should be ignored if the proxy is
    unaware of a running pod at the given address.

What are the implications of using RUNNING in that case? I wonder if the new state is necessary, and whether we can piggy back on the existing states.

</blockquote></details>

If a non-definitive source is sending load information (prometheus), there's always a chance that a pod could get deleted directly before a load update is sent to the proxy.

There's a test case in directory_test that show cases the example but concretely we may ship updated load metrics from a prometheus scrape without noticing that the pod was deleted. To avoid re-creating the in memory entry for a "zombie" state there needs to be some way to ensure that we only update the pod if it already exists.

We could check for pod existence before shipping over load information but there's still a very tiny race condition there. I also considered keeping around deleted pod entries so we could discard any modifications to them but that felt like a lot of effort compared to this.
___
*[pkg/ccl/sqlproxyccl/tenant/entry.go, line 159 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66850#-MeR7D0d5fo3lIAE69qz:-MeRD5Mr78cyyWYgaaiT:b-g257gs) ([raw file](https://github.com/cockroachdb/cockroach/blob/56d7a82d3790cae668d72d939e24b34fc11dfb2b/pkg/ccl/sqlproxyccl/tenant/entry.go#L159)):*
<details><summary><i>Previously, jaylim-crl (Jay Lim) wrote…</i></summary><blockquote>

> ```
> 			pods := e.pods.pods
> 			e.pods.pods = make([]*Pod, len(pods))
> 			copy(e.pods.pods, pods)
> 			e.pods.pods[i] = pod
> ```

Why do we need to perform a copy here? Maybe a comment would be helpful. Same goes to the logic in UpdatePod.
</blockquote></details>

Comment added. In the long run we may want to switch to copy on read now that this isn't just a slice of strings :thinking:

**Review by jaylim-crl — APPROVED** [review]
:lgtm: Just a heads up, we need to update the tenantdir to reflect the new proto changes in https://github.com/cockroachdb/cockroach/pull/67452 when we bump the vendor in CC.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66850#-:-MeRMkPO8XDOz66vkGyD:b2woue5)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @darinpp, and @jaylim-crl)

___
*[pkg/ccl/sqlproxyccl/tenant/directory.proto, line 42 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66850#-MeR8AekDThArBFTzYIn:-MeRMgUR7M5qyPWeYUCV:bxhnh4) ([raw file](https://github.com/cockroachdb/cockroach/blob/56d7a82d3790cae668d72d939e24b34fc11dfb2b/pkg/ccl/sqlproxyccl/tenant/directory.proto#L42)):*
<details><summary><i>Previously, chrisseto (Chris Seto) wrote…</i></summary><blockquote>

If a non-definitive source is sending load information (prometheus), there's always a chance that a pod could get deleted directly before a load update is sent to the proxy.

There's a test case in directory_test that show cases the example but concretely we may ship updated load metrics from a prometheus scrape without noticing that the pod was deleted. To avoid re-creating the in memory entry for a "zombie" state there needs to be some way to ensure that we only update the pod if it already exists.

We could check for pod existence before shipping over load information but there's still a very tiny race condition there. I also considered keeping around deleted pod entries so we could discard any modifications to them but that felt like a lot of effort compared to this.
</blockquote></details>

Ack. Thanks for the clarifications.

**Pull request merged**
