### PR TITLE
release-21.1: rowexec: fix zigzag joiner with ON expression in some cases

### PR DESCRIPTION
**Pull request by yuzefovich**
Backport 1/1 commits from #71226.
Backport 1/1 commits from #71289.

/cc @cockroachdb/release

---

Zigzag joiner needs to tell the row fetcher which columns are needed.
Previously, we forgot to include the columns that are needed by the ON
expression but are not needed in the output, so when evaluating such an
ON expression, we would hit an internal error. This commit fixes the
problem by including all columns referenced by the ON expression into
the set of columns to be fetched.

Fixes: #71093

Release note (bug fix): Previously, CockroachDB could encounter an
internal error when executing a zigzag join in some cases (when there
are multiple filters present and at least one filter refers to the
column that is part of STORING clause of the secondary index that is
used by the zigzag join), and this has been fixed.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71255#-:-MlPdKzg8O4_6PKRn9wK:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach)

**Review by cucaroach — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71255#-:-MlPvKNZ43kMk4O2RTup:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by yuzefovich** [comment]
Added #71289 in here.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71255#-:-Mlm4MHE3vTbpHpwr8_K:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

**Pull request merged**
