### PR TITLE
opt: normalize tuple equalities

### PR DESCRIPTION
**Pull request by RaduBerinde**
Add a rule normalizing equalities like
`  (a, b) = (x, y)`
to
`  (a = x) AND (b = y)`

This allows calculating index constraints for such expressions, without
introducing additional cases to that code.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm: 

This also simplifies predicate push-down.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/scalar.go, line 205 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20728#-L0LXG7HHr2iG7NWICqQ:-L0LXG7HHr2iG7NWICqR:b-v80dag) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2e08ff64b09a09417465be12628b963e507a7ac/pkg/sql/opt/scalar.go#L205)):*
> ```Go
> 		}
> 
> 	case eqOp:
> ```

`normalizeScalar` can turn into a best if we keep adding cases to the switch statement. An alternative would be to have a dispatch table indexed by `e.op`. At the very least, I think it is worthwhile to split the implementations here out into `normalizeScalarBool`, `normalizeScalarEq`, etc.

---

*[pkg/sql/opt/scalar.go, line 232 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20728#-L0LXzaDvOHYbFfmP0qV:-L0LXzaDvOHYbFfmP0qW:bx1fqu2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2e08ff64b09a09417465be12628b963e507a7ac/pkg/sql/opt/scalar.go#L232)):*
> ```Go
> 			// Normalize the new expression (some of the other rules, like coalescing
> 			// AND operations might apply now).
> 			normalizeScalar(e)
> ```

The recursion here is suspicious. I don't have a suggestion for removing it, but just putting it on notice. I've got my eye on you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20728#-:-L0LX0YaYUNg-SgSB3BA:b-vlfdmz)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/scalar.go, line 205 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20728#-L0LXG7HHr2iG7NWICqQ:-L0LaFXiOEuE57l6TxGb:b-5333op) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2e08ff64b09a09417465be12628b963e507a7ac/pkg/sql/opt/scalar.go#L205)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`normalizeScalar` can turn into a best if we keep adding cases to the switch statement. An alternative would be to have a dispatch table indexed by `e.op`. At the very least, I think it is worthwhile to split the implementations here out into `normalizeScalarBool`, `normalizeScalarEq`, etc.
</blockquote></details>

Agreed, I will look into making a dispatch table.

---

*[pkg/sql/opt/scalar.go, line 232 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20728#-L0LXzaDvOHYbFfmP0qV:-L0L_mGVmq3lGSAZCX9c:b-w8b5k2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2e08ff64b09a09417465be12628b963e507a7ac/pkg/sql/opt/scalar.go#L232)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The recursion here is suspicious. I don't have a suggestion for removing it, but just putting it on notice. I've got my eye on you.
</blockquote></details>

Haha. It does feel weird. Perhaps what we want is to call the normalization code but without the initial `for _, input := range e.children { normalizeScalar(input) }` part. There is no point in re-normalizing the grandchildren.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20728)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/scalar.go, line 205 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20728#-L0LXG7HHr2iG7NWICqQ:-L0LnRJyBMX5ndNNPpPM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2e08ff64b09a09417465be12628b963e507a7ac/pkg/sql/opt/scalar.go#L205)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Agreed, I will look into making a dispatch table.
</blockquote></details>

Done.

---

*[pkg/sql/opt/scalar.go, line 232 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20728#-L0LXzaDvOHYbFfmP0qV:-L0LnQjfoQHC3rNjXGwu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2e08ff64b09a09417465be12628b963e507a7ac/pkg/sql/opt/scalar.go#L232)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Haha. It does feel weird. Perhaps what we want is to call the normalization code but without the initial `for _, input := range e.children { normalizeScalar(input) }` part. There is no point in re-normalizing the grandchildren.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20728)*

**Comment by RaduBerinde** [comment]
@petermattis I will be OOO tomorrow and Monday, please merge this for me if it looks good. Thanks!

**Comment by petermattis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/opt/scalar.go, line 36 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20728#-L0PUozIy1OG_olfDnvc:-L0PUozIy1OG_olfDnvd:b-z9kkmi) ([raw file](https://github.com/cockroachdb/cockroach/blob/0abfd96832b9cec949331db813da2ee83c662c1e/pkg/sql/opt/scalar.go#L36)):*
> ```Go
> 		orderedListOp:       {name: "ordered-list"},
> 		andOp:               {name: "and", normalizeFn: normalizeAndOrOp},
> 		orOp:                {name: "or", normalizeFn: normalizeAndOrOp},
> ```

Rather than extending `operatorInfo`, I was thinking we'd have a separate table for scalar normalization funcs. Something like:

```
var scalarNormalizeFuncs = [numOperators]func(*expr) {
  andOp: normalizeAndOrOp,
  orOp:  normalizeAndOrOp,
  eqOp:  normalizeEqOp,
}
```

This is a bit less intrusive and keeps the normalization code grouped together. The downside is if we eventually have normalization functions for relational expressions. I don't have a strong preference for this approach vs extending `operatorInfo` right now, just pointing out an alternative.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20728)*

**Comment by RaduBerinde** [comment]
I figured we may need to have normalization for non-scalars (though I don't have something specific in mind).  But I'm ok with either approach, if you prefer the other one I can switch.

**Comment by petermattis** [comment]
> But I'm ok with either approach, if you prefer the other one I can switch.

I have no preference right now, so let's stick with the current approach. As this code develops, one approach might become more obviously preferable. For example, if `operatorInfo` starts to accrete too many random fields, splitting it into separate tables might provide better structure.

**Pull request merged**
