### PR TITLE
sql/logictest: fix flake in TestLogic_distinct_on

### LINKED ISSUE #93719: sql: TestLogic_distinct_on is flakey
```
=== RUN   TestLogic_distinct_on
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/b4be1ed0d1bda6f7c1621e4d2a3f503c/logTestLogic_distinct_on142130347
    test_log_scope.go:79: use -show-logs to present logs inline
[04:38:59] setting distsql_workmem='79007B';
    logic.go:2867: 
         
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/10789/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/fakedist-disk/fakedist-disk_test_/fakedist-disk_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/distinct_on:396: SELECT
          DISTINCT ON ("genre") *
        FROM
          "public"."author"
        ORDER BY
          "genre" ASC NULLS LAST,
          "id" ASC NULLS LAST
        expected:
            1  Alice  Action
            2  Bob    Biography
            3  Carol  Crime
            6  Bart   NULL
        but found (query options: "") :
            1  Alice  Action
            2  Bob    Biography
            5  Eve    Crime
            6  Bart   NULL
[04:39:00] --- done: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/10789/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/fakedist-disk/fakedist-disk_test_/fakedist-disk_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/distinct_on with config fakedist-disk: 49 tests, 1 failures
```

Build: <https://teamcity.cockroachdb.com/viewLog.html?buildId=7968848&buildTypeId=Cockroach_UnitTests_BazelUnitTests>.

This is easily reproduced by stressing the relevant test. I ran a bisection and found #93567 to be the change that introduced the issue.

Jira issue: CRDB-22498

### PR DESCRIPTION
**Pull request by rytaft**
Make sure the query results are deterministic.

Fixes #93719

Release note: None

### CODE REVIEW

**Comment by renatolabs** [comment]
Does it mean this test was previously working by "coincidence" (consequence of implementation vs actual spec behavior)?

**Comment by rytaft** [comment]
This test was just added yesterday. The query was previously non-deterministic, so sometimes it would output one set of rows, and sometimes a different set of rows. Now I've made it deterministic.

**Comment by renatolabs** [comment]
> This test was just added yesterday. The query was previously non-deterministic, so sometimes it would output one set of rows, and sometimes a different set of rows. Now I've made it deterministic.

Ah! 🤦 I didn't see the test was part of the PR. Thank you for the fix.

**Review by msirek — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93722#-:-NJLfHQ34wMbDP1B-xHA:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @renatolabs)

**Review by rytaft — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93722#-:-NJLkRSX4uWCMgz2Bg_Z:b-tlx7ko)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @renatolabs)

**Pull request merged**
