### PR TITLE
cast: remove invalid casts for REFCURSOR

### PR DESCRIPTION
**Pull request by DrewKimball**
#### cast: remove invalid casts for REFCURSOR

The initial implementation for the `REFCURSOR` data type included
assignment casts from and explicit casts to every other type. In postgres,
`REFCURSOR` has only the following valid casts:
1. Explicit casts from each string type.
2. Assignment casts to each string type.

This patch aligns the casts for `REFCURSOR` with those of postgres, and
adds according tests.

Informs #111560

Release note: None

### CODE REVIEW

**Comment by DrewKimball** [comment]
Sorry for the force-pushes; the commit message was a bit mangled.

**Comment by DrewKimball** [comment]
Hold off on this one for now; I think REFCURSOR needs its own type family.

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111884#-:-Ng5HkZUAdbULFf9_gX8:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

**Comment by DrewKimball** [comment]
TFTR!

**Pull request merged**
