### PR TITLE
storage/engine: add a function to get an engine.FS that uses

### PR DESCRIPTION
**Pull request by sumeerbhola**
either a previously created encrypted vfs.FS or the default
FS.

Needed for #44086

Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44614)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/pebble.go, line 406 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44614#-M--YuL14qBi4m_xiREW:-M--YuL14qBi4m_xiREX:b-4869ys) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6711b8e880812879af6a2b766adf9afced6cfac/pkg/storage/engine/pebble.go#L406)):*
> ```Go
> 		pebbleEncryptedFS.Lock()
> 		pebbleEncryptedFS.fs = cfg.Opts.FS
> 		pebbleEncryptedFS.Unlock()
> ```

This seems awkward and error prone. The last call to `NewPebble` which uses an encrypted FS will override the global. I'm not seeing how `GetEngineFS` will be used in this PR. Perhaps there is additional refactoring that could be done. Is there a reason that we can't use `Engine.(FS)` as the FS used for temp engines? I could also just be missing the bigger picture of how `GetEngineFS` will be used.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44614)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @itsbilal, and @petermattis)

___
*[pkg/storage/engine/pebble.go, line 406 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44614#-M--YuL14qBi4m_xiREW:-M-FUing6aixrsKP7N4o:b9d43bs) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6711b8e880812879af6a2b766adf9afced6cfac/pkg/storage/engine/pebble.go#L406)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This seems awkward and error prone. The last call to `NewPebble` which uses an encrypted FS will override the global. I'm not seeing how `GetEngineFS` will be used in this PR. Perhaps there is additional refactoring that could be done. Is there a reason that we can't use `Engine.(FS)` as the FS used for temp engines? I could also just be missing the bigger picture of how `GetEngineFS` will be used.
</blockquote></details>

This is indeed awkward. The main goal is to have an `engine.FS` implementation for query execution to use when spilling to disk. Currently that code path comes through `NewPebbleTempEngine()` so I'm assuming the creation of this `engine.FS` could use similar parameters. Also, I am assuming each store is its own file namespace, and so each store could have its own encrypted `vfs.FS`.  I suspect I am wrong in assuming a different namespace since the difference in the different stores wrt namespacing is just the file path -- so perhaps we don't support multiple stores when using encryption?

So the question is when to create the encrypted `vfs.FS` for a store: (a) only in `NewPebble()` under the assumption that it it called before needing the `engine.FS` for query execution, (b) either, whichever comes first, (c) reverse of (a). Reading the code more carefully, it looks like `NewTempEngine()` is called before the normal engines are created: the former is in `NewServer()` and the latter in `Server.Start()`. Can we change the ordering to (a) -- it seems more principled for `NewPebble()` to setup the encrypted `vfs.FS`? Also, this PR is incorrect in another way -- it decouples the `vfs.FS` from the `Engine` implementation, which works for Pebble but not RocksDB.
I think what we need is:
- creation ordering as in (a). Once created, the RocksDB or Pebble engine that implements `engine.FS` is stashed into a map keyed by the `StoreSpec.Path`.
- The call to `GetEngineFS` by the query execution code will provide that `StoreSpec` and lookup the map to return the appropriate `engine.FS`.
If the `StoreSpec.Path` is not unique for some reason, we could also use the index in `StoreSpecList.Specs`.

What do you think?

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44614)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @itsbilal, and @sumeerbhola)

___
*[pkg/storage/engine/pebble.go, line 406 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44614#-M--YuL14qBi4m_xiREW:-M-G6j140pR3a0Ve5VBH:b-6xkvw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6711b8e880812879af6a2b766adf9afced6cfac/pkg/storage/engine/pebble.go#L406)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This is indeed awkward. The main goal is to have an `engine.FS` implementation for query execution to use when spilling to disk. Currently that code path comes through `NewPebbleTempEngine()` so I'm assuming the creation of this `engine.FS` could use similar parameters. Also, I am assuming each store is its own file namespace, and so each store could have its own encrypted `vfs.FS`.  I suspect I am wrong in assuming a different namespace since the difference in the different stores wrt namespacing is just the file path -- so perhaps we don't support multiple stores when using encryption?

So the question is when to create the encrypted `vfs.FS` for a store: (a) only in `NewPebble()` under the assumption that it it called before needing the `engine.FS` for query execution, (b) either, whichever comes first, (c) reverse of (a). Reading the code more carefully, it looks like `NewTempEngine()` is called before the normal engines are created: the former is in `NewServer()` and the latter in `Server.Start()`. Can we change the ordering to (a) -- it seems more principled for `NewPebble()` to setup the encrypted `vfs.FS`? Also, this PR is incorrect in another way -- it decouples the `vfs.FS` from the `Engine` implementation, which works for Pebble but not RocksDB.
I think what we need is:
- creation ordering as in (a). Once created, the RocksDB or Pebble engine that implements `engine.FS` is stashed into a map keyed by the `StoreSpec.Path`.
- The call to `GetEngineFS` by the query execution code will provide that `StoreSpec` and lookup the map to return the appropriate `engine.FS`.
If the `StoreSpec.Path` is not unique for some reason, we could also use the index in `StoreSpecList.Specs`.

What do you think?
</blockquote></details>

I don't think there was any principled reason for creating the temp engine before the main engine. I seem to recall trying to invert the order at some point and ran into difficulties, but I could be misremembering. 

I feel I'm missing some constraints on the need for a global map. Will the new query execution code have access to the temp engine? Or is that being stripped out? If the temp engine still exists, can't the query execution code use `Engine.FS`?

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44614)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @itsbilal)

___
*[pkg/storage/engine/pebble.go, line 406 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44614#-M--YuL14qBi4m_xiREW:-M-Q657qCOrDZdQFs2w2:b-spscg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6711b8e880812879af6a2b766adf9afced6cfac/pkg/storage/engine/pebble.go#L406)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I don't think there was any principled reason for creating the temp engine before the main engine. I seem to recall trying to invert the order at some point and ran into difficulties, but I could be misremembering. 

I feel I'm missing some constraints on the need for a global map. Will the new query execution code have access to the temp engine? Or is that being stripped out? If the temp engine still exists, can't the query execution code use `Engine.FS`?


</blockquote></details>

@asubiotto Could you provide an opinion on this discussion?

@petermattis regarding the global map I was assuming that query execution wants some control over which store it is spilling to since `NewTempEngine()` is called with a particular `StoreSpec`, so keeping the map would allow `GetEngineFS` to satisfy that need.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44614)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @itsbilal, and @petermattis)

___
*[pkg/storage/engine/pebble.go, line 406 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44614#-M--YuL14qBi4m_xiREW:-M-QA6ss2Gci5s7_j7B9:bknen8i) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6711b8e880812879af6a2b766adf9afced6cfac/pkg/storage/engine/pebble.go#L406)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

@asubiotto Could you provide an opinion on this discussion?

@petermattis regarding the global map I was assuming that query execution wants some control over which store it is spilling to since `NewTempEngine()` is called with a particular `StoreSpec`, so keeping the map would allow `GetEngineFS` to satisfy that need.
</blockquote></details>

I don't think the idea of having a map of primary store to `engine.FS` (or some other way of exposing the primary store as an `engine.FS`, since we don't require the ability to choose) will work, because it's imperative that we have a separate store for temporary storage. In the case of row execution, this is to have distinct configuration options (e.g. disabling the WAL), but in the case of vectorized execution (that directly uses `engine.FS`) it is to ensure that we can throttle writes to the secondary store to avoid blocking the primary store.

@petermattis we only return a `DiskMapFactory` from `NewTempEngine`. We can easily return an `engine.FS` in the rocksDB case (since we wrap an `engine.RocksDB`), but we only ever instantiate a `pebble.DB` and wrap that in the case of pebble, while we need an `engine.Pebble` for an `engine.FS` implementation. Calling `NewPebble` seems overkill in order to just provide `engine.FS` functionality, but maybe that's the way we should go down?

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44614)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @itsbilal, and @sumeerbhola)

___
*[pkg/storage/engine/pebble.go, line 406 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44614#-M--YuL14qBi4m_xiREW:-M-QOL1LBSaZWH68ZH80:bhilfs) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6711b8e880812879af6a2b766adf9afced6cfac/pkg/storage/engine/pebble.go#L406)):*
> @petermattis we only return a DiskMapFactory from NewTempEngine. We can easily return an engine.FS in the rocksDB case (since we wrap an engine.RocksDB), but we only ever instantiate a pebble.DB and wrap that in the case of pebble, while we need an engine.Pebble for an engine.FS implementation. Calling NewPebble seems overkill in order to just provide engine.FS functionality, but maybe that's the way we should go down?

I'm not quite following with what the problem is. Can you provide some pointers to code regarding how this initialization is done?

As far as I can tell, `NewTempEngine` is only used for setting `execinfra.ServerConfig.TempStorage` which is only used by DistSQL. We can do whatever we want to the return value or the `diskmap.Factory` interface, including add an`FS()` method.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44614)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @petermattis)

___
*[pkg/storage/engine/pebble.go, line 406 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44614#-M--YuL14qBi4m_xiREW:-M-QbEuFEQzanulUBRyf:b-yhq4bw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6711b8e880812879af6a2b766adf9afced6cfac/pkg/storage/engine/pebble.go#L406)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

> @petermattis we only return a DiskMapFactory from NewTempEngine. We can easily return an engine.FS in the rocksDB case (since we wrap an engine.RocksDB), but we only ever instantiate a pebble.DB and wrap that in the case of pebble, while we need an engine.Pebble for an engine.FS implementation. Calling NewPebble seems overkill in order to just provide engine.FS functionality, but maybe that's the way we should go down?

I'm not quite following with what the problem is. Can you provide some pointers to code regarding how this initialization is done?

As far as I can tell, `NewTempEngine` is only used for setting `execinfra.ServerConfig.TempStorage` which is only used by DistSQL. We can do whatever we want to the return value or the `diskmap.Factory` interface, including add an`FS()` method.
</blockquote></details>

I don't think there is a big problem.`NewPebbleTempEngine` returns a `pebbleTempEngine{db: p}` where `p` is a `pebble.DB`. This is created using `pebble.Open`. The `pebbleMap` used for row execution only needs a `db`. However, `pebble.DB` doesn't implement `engine.FS` so we can't return that for the vectorized execution engine. I thought that calling `NewPebble` instead of `pebble.Open` would be overkill in order to solve this requirement, but I think that in the end we want to call `NewPebble` anyway for encryption (?).

I think that we just need to change `pebbleTempEngine` to use `engine.Pebble` and call `NewPebble` in `NewPebbleTempEngine`, which will allow us to also return that `engine.Pebble` as an `engine.FS`.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44614)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @petermattis)

___
*[pkg/storage/engine/pebble.go, line 406 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44614#-M--YuL14qBi4m_xiREW:-M-QrCNxB7fajofAVaUw:b-10hktu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6711b8e880812879af6a2b766adf9afced6cfac/pkg/storage/engine/pebble.go#L406)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I don't think there is a big problem.`NewPebbleTempEngine` returns a `pebbleTempEngine{db: p}` where `p` is a `pebble.DB`. This is created using `pebble.Open`. The `pebbleMap` used for row execution only needs a `db`. However, `pebble.DB` doesn't implement `engine.FS` so we can't return that for the vectorized execution engine. I thought that calling `NewPebble` instead of `pebble.Open` would be overkill in order to solve this requirement, but I think that in the end we want to call `NewPebble` anyway for encryption (?).

I think that we just need to change `pebbleTempEngine` to use `engine.Pebble` and call `NewPebble` in `NewPebbleTempEngine`, which will allow us to also return that `engine.Pebble` as an `engine.FS`.
</blockquote></details>

https://github.com/cockroachdb/cockroach/pull/44827

**Comment by sumeerbhola** [comment]
Closing since replaced by #44827

**Pull request closed without merging**
