### PR TITLE
cmd: Add tool for parsing contents of gossip debug page

### LINKED ISSUE #13023: gossip: I wish it were easier to view the deserialized gossip values a node has
On multiple occasions now, I've wished that I could see some particular info from the `/_status/gossip/local` page while looking into an issue. However, the actual gossip values are all serialized/encoded and thus not easy to use. It'd be nice if the real values were easier to get at.

While reworking the `serverpb/status.proto` protos to let us be smarter about printing meaningful values would be nice, realistically this likely just means some instructions and perhaps a small tool for taking a "rawValue" from the gossip debug page and printing out something more meaningful.

Also, for what it's worth, on all occasions that I've wanted to read gossip values, I was primarily interested in node liveness entries, so perhaps an easier alternative would just be to have a node liveness debug page.

### PR DESCRIPTION
**Pull request by a-robinson**
Fixes #13023 

The output looks like:
```
"cluster-id": a8995f48-5029-4705-b6d4-a01fdae347f3
"first-range": r1:/{Min-System/} [(n5,s5):3, (n3,s3):5, (n6,s6):7, next=8]
"liveness:1": {NodeID:1 Epoch:1 Expiration:1495137268.487952962,0 Draining:false}
"liveness:2": {NodeID:2 Epoch:3 Expiration:1495137265.687548343,0 Draining:false}
"liveness:3": {NodeID:3 Epoch:1 Expiration:1495137268.406753859,0 Draining:false}
"liveness:4": {NodeID:4 Epoch:1 Expiration:1495137267.467871337,0 Draining:false}
"liveness:5": {NodeID:5 Epoch:1 Expiration:1495137266.657675362,0 Draining:false}
"liveness:6": {NodeID:6 Epoch:3 Expiration:1495137266.872734133,0 Draining:false}
"node:1": {NodeID:1 Address:{NetworkField:tcp AddressField:10.197.64.1:26257} Attrs: Locality:}
"node:2": {NodeID:2 Address:{NetworkField:tcp AddressField:10.197.64.2:26257} Attrs: Locality:}
"node:3": {NodeID:3 Address:{NetworkField:tcp AddressField:10.197.64.4:26257} Attrs: Locality:}
"node:4": {NodeID:4 Address:{NetworkField:tcp AddressField:10.197.64.5:26257} Attrs: Locality:}
"node:5": {NodeID:5 Address:{NetworkField:tcp AddressField:10.197.64.6:26257} Attrs: Locality:}
"node:6": {NodeID:6 Address:{NetworkField:tcp AddressField:10.197.64.3:26257} Attrs: Locality:}
"sentinel": a8995f48-5029-4705-b6d4-a01fdae347f3
"store:1": {StoreID:1 Attrs: Node:{NodeID:1 Address:{NetworkField:tcp AddressField:10.197.64.1:26257} Attrs: Locality:} Capacity:{Capacity:984171765760 Available:933880942592 RangeCount:23 LeaseCount:9}}
"store:2": {StoreID:2 Attrs: Node:{NodeID:2 Address:{NetworkField:tcp AddressField:10.197.64.2:26257} Attrs: Locality:} Capacity:{Capacity:984171765760 Available:933824831488 RangeCount:23 LeaseCount:5}}
"store:3": {StoreID:3 Attrs: Node:{NodeID:3 Address:{NetworkField:tcp AddressField:10.197.64.4:26257} Attrs: Locality:} Capacity:{Capacity:984171765760 Available:934008590336 RangeCount:21 LeaseCount:3}}
"store:4": {StoreID:4 Attrs: Node:{NodeID:4 Address:{NetworkField:tcp AddressField:10.197.64.5:26257} Attrs: Locality:} Capacity:{Capacity:984171765760 Available:933885083648 RangeCount:23 LeaseCount:12}}
"store:5": {StoreID:5 Attrs: Node:{NodeID:5 Address:{NetworkField:tcp AddressField:10.197.64.6:26257} Attrs: Locality:} Capacity:{Capacity:984171765760 Available:934027681792 RangeCount:22 LeaseCount:8}}
"store:6": {StoreID:6 Attrs: Node:{NodeID:6 Address:{NetworkField:tcp AddressField:10.197.64.3:26257} Attrs: Locality:} Capacity:{Capacity:984171765760 Available:933934059520 RangeCount:20 LeaseCount:5}}
"system-db": omitted
```

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/cmd/gossip-parser/main.go, line 32 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16063#-Kkl1ujhSfhd73CwSvJt:-Kkl1ujhSfhd73CwSvJu:b-srngot) ([raw file](https://github.com/cockroachdb/cockroach/blob/a930a64d39112400e66bcfb64f38b688f684e80f/pkg/cmd/gossip-parser/main.go#L32)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/roachpb"
> 	"github.com/cockroachdb/cockroach/pkg/storage"
> 	"github.com/cockroachdb/cockroach/pkg/util/log"
> ```

since you're only using `log.Fatal`, you might consider using the standard library's `log `package, which is allowed here (and has `log.Panic` which produces slightly better (for our needs) output.

---

*[pkg/cmd/gossip-parser/main.go, line 35 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16063#-Kkl1pSU7cr86ejPFkWf:-Kkl1pSVm3RA0x_Det-P:btg0caz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a930a64d39112400e66bcfb64f38b688f684e80f/pkg/cmd/gossip-parser/main.go#L35)):*
> ```Go
> 	"github.com/gogo/protobuf/jsonpb"
> 	"github.com/gogo/protobuf/proto"
> 	uuid "github.com/satori/go.uuid"
> ```

can this use our uuid package? it probably doesn't matter here, but leaves me wondering.

---

*[pkg/cmd/gossip-parser/main.go, line 38 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16063#-Kkl25VQx1wIDqyIMjgy:-Kkl25VQx1wIDqyIMjgz:b5lrtji) ([raw file](https://github.com/cockroachdb/cockroach/blob/a930a64d39112400e66bcfb64f38b688f684e80f/pkg/cmd/gossip-parser/main.go#L38)):*
> ```Go
> )
> 
> var inputFile = flag.String("f", "", "file containing the JSON output from a node's _status/gossip/ endpoint")
> ```

can we make this accept stdin? that'd be quite convenient for piping from curl, I expect.

---

*[pkg/cmd/gossip-parser/main.go, line 68 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16063#-Kkl2OAzZUQpnUbDVVK9:-Kkl2OAzZUQpnUbDVVKA:bkx1v1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/a930a64d39112400e66bcfb64f38b688f684e80f/pkg/cmd/gossip-parser/main.go#L68)):*
> ```Go
> 			output = append(output, fmt.Sprintf("%q: %v", key, clusterID))
> 		} else if key == gossip.KeySystemConfig {
> 			// Uncomment this logic if you actually want to print the system config,
> ```

perhaps a flag?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16063#-:-Kkl2Zj4zXj4VIMYjpC5:bnfp4nl)*

**Comment by tamird** [comment]
Oh, is there a reason we don't want this as a CLI debug command?

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16063#-:-Kkl2hY39x4q0uzmqDUG:be0d193)*

**Comment by bdarnell** [comment]
Yeah, this seems like it should be a `cockroach debug` subcommand (and optionally take the address of a server instead of requiring you to download the page separately). Or even better, there should be a web-based version of his in the admin UI. 

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16063#-:-Kkl3qQKe3BUt_v36E7z:bd90cbo)*

**Comment by tschottdorf** [comment]
LGTM and share the order of preference `ui > debug-cli > cli` but then again it may not be worth your time doing that now.

**Comment by a-robinson** [comment]
Alright, I'll rework this into a `cockroach debug` command. This was just a quick and dirty hack to help investigate https://github.com/cockroachdb/cockroach/issues/16007, and I think we'll always need a CLI version for interpreting the gossip files in the output of `cockroach debug zip`.

**Comment by tschottdorf** [comment]
> Alright, I'll rework this into a cockroach debug command. This was just a quick and dirty hack to help investigate #16007, and I think we'll always need a CLI version for interpreting the gossip files in the output of cockroach debug zip.

`./cockroach debug zip` could just download the pretty-printed /debug page as well. (Not suggesting that what you've decided to do isn't completely fine by me).

**Comment by a-robinson** [comment]
Updated to be a `cockroach debug` command. TFTR!

---

Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/cmd/gossip-parser/main.go, line 32 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16063#-Kkl1ujhSfhd73CwSvJt:-KklgJlSGdxntLEr88u8:b-7wso34) ([raw file](https://github.com/cockroachdb/cockroach/blob/a930a64d39112400e66bcfb64f38b688f684e80f/pkg/cmd/gossip-parser/main.go#L32)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

since you're only using `log.Fatal`, you might consider using the standard library's `log `package, which is allowed here (and has `log.Panic` which produces slightly better (for our needs) output.
</blockquote></details>

Not relevant anymore

---

*[pkg/cmd/gossip-parser/main.go, line 35 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16063#-Kkl1pSU7cr86ejPFkWf:-KklgLfAxC2IkBTws_W3:byg8h2z) ([raw file](https://github.com/cockroachdb/cockroach/blob/a930a64d39112400e66bcfb64f38b688f684e80f/pkg/cmd/gossip-parser/main.go#L35)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can this use our uuid package? it probably doesn't matter here, but leaves me wondering.
</blockquote></details>

Good catch, thanks. That's just what my editor auto-included since I didn't have a rule forbidding it.

---

*[pkg/cmd/gossip-parser/main.go, line 38 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16063#-Kkl25VQx1wIDqyIMjgy:-Kklg3ZwBcm_QM6LcdsK:bnyjr4v) ([raw file](https://github.com/cockroachdb/cockroach/blob/a930a64d39112400e66bcfb64f38b688f684e80f/pkg/cmd/gossip-parser/main.go#L38)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can we make this accept stdin? that'd be quite convenient for piping from curl, I expect.
</blockquote></details>

Still think this is important now that it's a debug command that can talk directly to a server?

---

*[pkg/cmd/gossip-parser/main.go, line 68 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16063#-Kkl2OAzZUQpnUbDVVK9:-Kklhsi9OPV-yyjWVRGf:b-l92gnm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a930a64d39112400e66bcfb64f38b688f684e80f/pkg/cmd/gossip-parser/main.go#L68)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

perhaps a flag?
</blockquote></details>

I added a flag, but I'm not sure whether it's worth keeping around. It does let you see the keys and their timestamps, but the values are pretty worthless.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16063#-:-KkliICwyrO9hMNf4BuQ:bafcmcd)*

**Comment by tamird** [comment]
Looks good to me.

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/cli/flags.go, line 374 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16063#-KkljLQJO-z2ZBbTmoQE:-KkljLQJO-z2ZBbTmoQF:beysgq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d64e0bba702e7ddb9e34f67de05f63bf9732f858/pkg/cli/flags.go#L374)):*
> ```Go
> 	// Debug commands.
> 	{
> 		f := debugKeysCmd.Flags()
> ```

nit: i'd give each of these a scope to avoid overwriting.

---

*[pkg/cmd/gossip-parser/main.go, line 38 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16063#-Kkl25VQx1wIDqyIMjgy:-KkljEwGHDawsdeqeNK0:bb7lgjf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a930a64d39112400e66bcfb64f38b688f684e80f/pkg/cmd/gossip-parser/main.go#L38)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Still think this is important now that it's a debug command that can talk directly to a server?
</blockquote></details>

nope

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16063#-:-KkllHACXsOojrYlh0gX:b9j9n43)*

**Comment by a-robinson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/cli/flags.go, line 374 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16063#-KkljLQJO-z2ZBbTmoQE:-KklmYMK-xsMj34U6GHi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d64e0bba702e7ddb9e34f67de05f63bf9732f858/pkg/cli/flags.go#L374)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: i'd give each of these a scope to avoid overwriting.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16063)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16063)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/cli/cliflags/flags.go, line 462 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16063#-KkltWgFwmWe5kkHJ39W:-KkltWgFwmWe5kkHJ39X:b-y0k4c0) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f1131e291bb75a7a927829c99bb8cc2c91a2f25/pkg/cli/cliflags/flags.go#L462)):*
> ```Go
> 	}
> 
> 	InputFile = FlagInfo{
> ```

This has a generic name but non-generic help text. Either remove the "takes priority over the host/port flags" or rename it to `DebugGossipInputFile`. (we have a similar flag in `cliflags.ZoneConfig`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16063#-:-Kkltn8x4vJ-CmUcZHQM:bnfp4nl)*

**Comment by a-robinson** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/cli/cliflags/flags.go, line 462 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16063#-KkltWgFwmWe5kkHJ39W:-Kkm3sfbqM7VhvQnqsUb:b-v6zrsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f1131e291bb75a7a927829c99bb8cc2c91a2f25/pkg/cli/cliflags/flags.go#L462)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This has a generic name but non-generic help text. Either remove the "takes priority over the host/port flags" or rename it to `DebugGossipInputFile`. (we have a similar flag in `cliflags.ZoneConfig`)
</blockquote></details>

Heh, I had been trying to split the difference. Switched to a gossip-specific flag name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16063)*

**Pull request merged**
