### PR TITLE
opt: prune partial index columns and simplify partial index projections

### LINKED ISSUE #51623: opt: prune columns that are guaranteed not to be needed for partial index mutations
In the example below, `a` does not need to be fetched because the secondary partial index is guaranteed not to change during this mutation—none of its indexed or referenced columns are changing.

Also, the partial index put and del columns can be pruned.

```sql
root@127.0.0.1:54758/defaultdb> create table t (k int primary key, a int, b int, c int, index (a) where b > 1, family (a), family (b), family (c));
CREATE TABLE

Time: 3.244ms

root@127.0.0.1:54758/defaultdb> explain (opt, verbose) update t set c = c + 1 where true;
                                       text
----------------------------------------------------------------------------------
  update t
   ├── columns: <none>
   ├── fetch columns: k:5 a:6 c:8
   ├── update-mapping:
   │    └── c_new:10 => c:4
   ├── partial index put columns: partial_index_del1:9
   ├── partial index del columns: partial_index_del1:9
   ├── cardinality: [0 - 0]
   ├── volatile, mutations
   ├── stats: [rows=0]
   ├── cost: 1190.04
   └── project
        ├── columns: c_new:10 partial_index_del1:9 k:5 a:6 c:8
        ├── immutable
        ├── stats: [rows=1000]
        ├── cost: 1190.03
        ├── key: (5)
        ├── fd: (5)-->(6,8-10), (8)-->(10)
        ├── prune: (5,6,8-10)
        ├── scan t
        │    ├── columns: k:5 a:6 b:7 c:8
        │    ├── partial index predicates
        │    │    └── t_a_idx: filters
        │    │         └── b:7 > 1 [outer=(7), constraints=(/7: [/2 - ]; tight)]
        │    ├── stats: [rows=1000]
        │    ├── cost: 1160.02
        │    ├── key: (5)
        │    ├── fd: (5)-->(6-8)
        │    └── prune: (5-8)
        └── projections
             ├── c:8 + 1 [as=c_new:10, outer=(8), immutable]
             └── b:7 > 1 [as=partial_index_del1:9, outer=(7)]
```

### PR DESCRIPTION
**Pull request by mgartner**
Fixes #51623

#### opt: do not derive prune columns for Upsert, Update, Delete

We no longer derive output prune columns for Upsert, Update, and Delete
ops in `DerivePruneCols`. There are no PruneCols rules for these
operators, so deriving their prune columns was only performing
unnecessary work. There are other rules that prune the fetch and return
columns for these operators. These rules do not rely on
`DerivePruneCols`.

Release note: None

#### sql: remove logic to determine fetch cols in row updater

Previously, the `row.MakeUpdater` function had logic to determine the
fetch columns required for an update operation. This is not necessary
because the cost based optimizer already determines the necessary fetch
columns and plumbs them to `MakeUpdater` as the `requestedCols`
argument.

Release note: None

#### opt: safer access to partial index predicates in TableMeta

Previously, partial index predicate expressions in TableMeta were the
source-of-truth used within the optimizer to determine if an index is a
partial index. However, partial index predicates are not added to
TableMeta for all types of statements in optbuilder. Therefore, it was
not safe to assume this was a source-of-truth.

This commit unexports the map of partial index predicates in TableMeta.
Access to partial index predicates must now be done via
`TableMeta.PartialIndexPredicate`. This function checks the catalog to
determine if an index is a partial index, and panics if there is not a
corresponding predicate expression in the partial index predicate map.
This makes the function an actual a source-of-truth.

Release note: None

#### opt: move addPartialIndexPredicatesForTable to optbuilder/partial_index.go

Release note: None

#### opt: prune update/upsert fetch columns not needed for partial indexes

Indexed columns of partial indexes are now only fetched for UPDATE and
UPSERT operations when needed. They are pruned in cases where it is
guaranteed that they are not needed to build old or new index entries.
For example, consider the table and UPDATE:

    CREATE TABLE t (
      a INT PRIMARY KEY,
      b INT,
      c INT,
      d INT,
      INDEX (b) WHERE c > 0,
      FAMILY (a), FAMILY (b), FAMILY (c), FAMILY (d)
    )

    UPDATE t SET d = d + 1 WHERE a = 1

The partial index is guaranteed not to change with this UPDATE because
neither its indexed columns not the columns referenced in its predicate
are mutating. Therefore, the existing values of b do not need to be
fetched to maintain the state of the partial index. Furthermore, the
primary index does require the existing values of b because no columns
in b's family are mutating. So, b can be pruned from the UPDATE's fetch
columns.

Release note (performance improvement): Previously, indexed columns of
partial indexes were always fetched for UPDATEs and UPSERTs. Now they
are only fetched if they are required for maintaining the state of the
index. If an UPDATE or UPSERT mutates columns that are neither indexed by a
partial index nor referenced in a partial index predicate, they will no
longer be fetched (assuming that they are not needed to maintain the
state of other indexes, including the primary index).

#### opt: normalize partial index PUT/DEL projections to false

The `SimplifyPartialIndexProjections` normalization rule has been added
that normalizes synthesized partial index PUT and DEL columns to False
when it is guaranteed that a mutation will not require changed to the
associated partial index. This normalization can lead to further
normalizations, such as pruning columns that the synthesized projections
relied on.

The motivation for this change is to allow fully disjoint updates to
different columns in the same row, when the columns are split across
different families. By pruning columns not needed to maintain a partial
index, we're not forced to scan all column families. This can ultimately
reduce contention during updates.

Release note (performance improvement): UPDATE and UPSERT operations on
tables with partial indexes no longer evaluate partial index predicate
expressions when it is guaranteed that the operation will not alter the
state of the partial index. In some cases, this can eliminate fetching
the existing value of columns that are referenced in partial index
predicates.

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
Nice work!

[nit] in the commit/PR message: "neither its indexed columns not the columns referenced" -> "neither its indexed columns nor the columns referenced"; "will not require changed to the associated partial index." -> "will not require changes to the associated partial index."

> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 9 of 9 files at r3, 2 of 2 files at r4, 7 of 7 files at r5, 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58358#-:-MPoAFcVEH40Gw_HzsSk:b-pskqbg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @mgartner, and @RaduBerinde)

___
*[pkg/sql/opt/table_meta.go, line 285 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58358#-MPo4xok96ZEegZeSOee:-MPo4xok96ZEegZeSOef:bdoq1qw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e737fbba29e6208cf2da823973006d994d87eda/pkg/sql/opt/table_meta.go#L285)):*
> ```Go
> // partial index expressions that have been built for a table when formatting
> // opt expressions. Use PartialIndexPredicate in all other cases.
> func (tm *TableMeta) PartialIndexPredicatesForFormattingOnly() map[cat.IndexOrdinal]ScalarExpr {
> ```

Nice name!
___
*[pkg/sql/opt/norm/mutation_funcs.go, line 37 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/58358#-MPoBuGT47duUH9EjLBS:-MPoBuGU19yE_fmn9HEM:b6lgrdk) ([raw file](https://github.com/cockroachdb/cockroach/blob/bde9ef1ae22f1b9100a4bbedfd12f226b292a1b3/pkg/sql/opt/norm/mutation_funcs.go#L37)):*
> ```Go
> 			updateCols.Add(tabMeta.MetaID.ColumnID(ord))
> 		}
> 	}
> ```

Isn't there a `ToSet` function on `OptionalColList` that @raduberinde added recently to do this?
___
*[pkg/sql/opt/norm/mutation_funcs.go, line 68 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/58358#-MPoCyLd1Nz7DbeRiiS6:-MPoCyLd1Nz7DbeRiiS7:b-x18wc6) ([raw file](https://github.com/cockroachdb/cockroach/blob/bde9ef1ae22f1b9100a4bbedfd12f226b292a1b3/pkg/sql/opt/norm/mutation_funcs.go#L68)):*
> ```
> update requires may update
> ```

^ garbled sentence
___
*[pkg/sql/opt/norm/mutation_funcs.go, line 95 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/58358#-MPoE3l5AFSAQiogzlNa:-MPoE3l6AUehfDug6jPV:b-2n5k0z) ([raw file](https://github.com/cockroachdb/cockroach/blob/bde9ef1ae22f1b9100a4bbedfd12f226b292a1b3/pkg/sql/opt/norm/mutation_funcs.go#L95)):*
> ```Go
> 		}
> 
> 		ord++
> ```

should this ordinal be incremented for all partial indexes, or only those that are eligible to be simplified? this seems error prone...

would be good to add some test cases with multiple partial indexes, some of which are eligible for simplification and some of which are not
___
*[pkg/sql/opt/norm/prune_cols_funcs.go, line 150 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/58358#-MPo9mIaC9ZG5aZRLd5A:-MPo9mIaC9ZG5aZRLd5B:bbodev0) ([raw file](https://github.com/cockroachdb/cockroach/blob/3610368ad14e95367b04a2d8f974f79730c64bdb/pkg/sql/opt/norm/prune_cols_funcs.go#L150)):*
> ```Go
> 			// update does not require changes to the index. Partial indexes may be
> 			// updated (even when a column in the index is not changing) when the
> 			// predicate reference columns that are being updated. For example, rows
> ```

[nit] reference -> references
___
*[pkg/sql/opt/norm/testdata/rules/mutation, line 62 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/58358#-MPoGGwy-F7bgklm6lvz:-MPoGGwy-F7bgklm6lw-:b-i6ya83) ([raw file](https://github.com/cockroachdb/cockroach/blob/bde9ef1ae22f1b9100a4bbedfd12f226b292a1b3/pkg/sql/opt/norm/testdata/rules/mutation#L62)):*
> ```
> # and columns referenced in predicates are not mutating.
> norm expect=SimplifyPartialIndexProjections
> UPSERT INTO t (k, a, b) VALUES (1, 2, 3)
> ```

can you add an upsert test like this but with one of the columns referenced in a predicate that has a default value that satisfies the predicate? (so therefore it would get added to the index on the insert case.)

**Comment by mgartner** [comment]
___
*[pkg/sql/opt/norm/testdata/rules/mutation, line 62 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/58358#-MPoGGwy-F7bgklm6lvz:-MPq9dqDA_8qPulVnqTx:b-2cr5eb) ([raw file](https://github.com/cockroachdb/cockroach/blob/bde9ef1ae22f1b9100a4bbedfd12f226b292a1b3/pkg/sql/opt/norm/testdata/rules/mutation#L62)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

can you add an upsert test like this but with one of the columns referenced in a predicate that has a default value that satisfies the predicate? (so therefore it would get added to the index on the insert case.)
</blockquote></details>

Hmm, great point. I added this case, but it's broken because the default column is an insert column, not an update column. I think this proves that this normalization isn't possible for Upserts—the Insert columns will always contain all target table columns. I need to think about whether the prune cols changes in the 5th commit are also restricted to Updates...

**Review by mgartner — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58358#-:-MQIt4aT1_4bs38or3VT:b-896fix)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/table_meta.go, line 285 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58358#-MPo4xok96ZEegZeSOee:-MQIt5tr7PAG723UNvuf:b-ve3yvb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e737fbba29e6208cf2da823973006d994d87eda/pkg/sql/opt/table_meta.go#L285)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Nice name!
</blockquote></details>

:smile: 
___
*[pkg/sql/opt/norm/mutation_funcs.go, line 37 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/58358#-MPoBuGT47duUH9EjLBS:-MPq4VSN8rTD1j0mG3Ki:b-lbmm8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/bde9ef1ae22f1b9100a4bbedfd12f226b292a1b3/pkg/sql/opt/norm/mutation_funcs.go#L37)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Isn't there a `ToSet` function on `OptionalColList` that @raduberinde added recently to do this?
</blockquote></details>

We're collect the target table columns here, not the update column IDs. Notice how we are converting the ordinal `ord` to a column id, rather than collecting `col`. This is tricky, so I've expanded the comment to explain a bit more.
___
*[pkg/sql/opt/norm/mutation_funcs.go, line 68 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/58358#-MPoCyLd1Nz7DbeRiiS6:-MPq4zs54vpU6b_3505l:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bde9ef1ae22f1b9100a4bbedfd12f226b292a1b3/pkg/sql/opt/norm/mutation_funcs.go#L68)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

> ```
> update requires may update
> ```

^ garbled sentence
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/mutation_funcs.go, line 95 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/58358#-MPoE3l5AFSAQiogzlNa:-MPq5r-YE8B7KIvi6Hg_:b-starj7) ([raw file](https://github.com/cockroachdb/cockroach/blob/bde9ef1ae22f1b9100a4bbedfd12f226b292a1b3/pkg/sql/opt/norm/mutation_funcs.go#L95)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

should this ordinal be incremented for all partial indexes, or only those that are eligible to be simplified? this seems error prone...

would be good to add some test cases with multiple partial indexes, some of which are eligible for simplification and some of which are not
</blockquote></details>

Great catch! I've expanded the tests to catch this. Added some non-partial indexes into the mix too for the hell of it. I've moved the incrementing of `ord` to directly after the partial index check, which hopefully makes this less error-prone to work with in the future.
___
*[pkg/sql/opt/norm/prune_cols_funcs.go, line 150 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/58358#-MPo9mIaC9ZG5aZRLd5A:-MPq6zAA8FvMGBOJkUs-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3610368ad14e95367b04a2d8f974f79730c64bdb/pkg/sql/opt/norm/prune_cols_funcs.go#L150)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] reference -> references
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/testdata/rules/mutation, line 62 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/58358#-MPoGGwy-F7bgklm6lvz:-MQIu6m1E-lzOthY-iE_:b-4f1t70) ([raw file](https://github.com/cockroachdb/cockroach/blob/bde9ef1ae22f1b9100a4bbedfd12f226b292a1b3/pkg/sql/opt/norm/testdata/rules/mutation#L62)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Hmm, great point. I added this case, but it's broken because the default column is an insert column, not an update column. I think this proves that this normalization isn't possible for Upserts—the Insert columns will always contain all target table columns. I need to think about whether the prune cols changes in the 5th commit are also restricted to Updates...
</blockquote></details>

I've updated this rule so it no longer matches `Upsert`s—these projections cannot be simplified because if the `Upsert` results in an "insert", then the evaluated predicate expressions are required.

The prune cols changes in the 5th commit look to be fine.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58358#-:-MQNTC8zBCX2xIdgk7bW:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @mgartner, and @RaduBerinde)

___
*[pkg/sql/opt/norm/testdata/rules/mutation, line 69 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/58358#-MQNS-PB1TIbKP_3u6JG:-MQNS-PB1TIbKP_3u6JH:bwegupp) ([raw file](https://github.com/cockroachdb/cockroach/blob/952a1b9d818daafa4af4ec0fc1ad383cd38c8c71/pkg/sql/opt/norm/testdata/rules/mutation#L69)):*
> ```
>            └── 2 [as=a_new:21]
> 
> # Simplify UPDATE partial index put/del column to false of second partial index
> ```

of -> for ?

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58358)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/norm/testdata/rules/mutation, line 69 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/58358#-MQNS-PB1TIbKP_3u6JG:-MQNuBr7ExyxNdvWGju-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/952a1b9d818daafa4af4ec0fc1ad383cd38c8c71/pkg/sql/opt/norm/testdata/rules/mutation#L69)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

of -> for ?
</blockquote></details>

Done.

**Comment by mgartner** [comment]
TFTR!

bors r=rytaft

**Comment by mgartner** [comment]
bors r=rytaft

**Comment by mgartner** [comment]
bors r=rytaft

**Review by RaduBerinde — COMMENTED** [review]
Late to the party, but :lgtm:  Nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58358#-:-MQhcTiFEl_zNOwCL4zv:b-i2z3hp)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @mgartner, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/optbuilder/partial_index.go, line 35 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/58358#-MQhbL_93PDZenOQZRAO:-MQhbL_93PDZenOQZRAP:b-ggahfa) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e140b62fbe766ea1bb735700e9e564686baa67b/pkg/sql/opt/optbuilder/partial_index.go#L35)):*
> ```Go
> // normalize the partial index predicates.
> func (b *Builder) addPartialIndexPredicatesForTable(
> 	tabMeta *opt.TableMeta, scan memo.RelExpr, includeDeletable bool,
> ```

Is there any harm to always including any deletable indexes? It would be one less thing to worry about (currently the code that calls this function, and the code that uses index predicates must "match" w.r.t this).

**Comment by mgartner** [comment]
___
*[pkg/sql/opt/optbuilder/partial_index.go, line 35 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/58358#-MQhbL_93PDZenOQZRAO:-MQmblOLExXwOph69jjU:b-qm5krv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e140b62fbe766ea1bb735700e9e564686baa67b/pkg/sql/opt/optbuilder/partial_index.go#L35)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Is there any harm to always including any deletable indexes? It would be one less thing to worry about (currently the code that calls this function, and the code that uses index predicates must "match" w.r.t this).
</blockquote></details>

Good point: https://github.com/cockroachdb/cockroach/pull/58714

**Pull request merged**
