### PR TITLE
changefeedccl: Add pushback duration metric to blocking buffer.

### PR DESCRIPTION
**Pull request by miretskiy**
Add a blocking buffer metric which keeps track of the amount
of time waited for resource aquisition.

Release Notes: None

### CODE REVIEW

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68256)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @miretskiy)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/68256#-MfrjQgs9uq1b5d-hu8I:-MfrjQgs9uq1b5d-hu8J:bsgpdz5) (no related file):*
Seems like a reasonable metric to add to me.  Looks like there are some CI issues but otherwise seems good.

---
___
*[pkg/ccl/changefeedccl/kvevent/blocking_buffer_test.go, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68256#-Mfrf3QTAp4ua0Eq1UhD:-Mfrf3QTAp4ua0Eq1UhE:brq78le) ([raw file](https://github.com/cockroachdb/cockroach/blob/e02444935ff125756c9e2bf41b95830eb93b2548/pkg/ccl/changefeedccl/kvevent/blocking_buffer_test.go#L30)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/util/log"
> 	"github.com/cockroachdb/cockroach/pkg/util/mon"
> 	"github.com/cockroachdb/cockroach/pkg/util/randutil"
> ```

You likely need to `make bazel-generate` after these import changes.
___
*[pkg/ccl/changefeedccl/kvevent/blocking_buffer_test.go, line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68256#-Mfrf8Zt1vc-rTyblajn:-Mfrf8Zt1vc-rTyblajo:b-mww4mq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e02444935ff125756c9e2bf41b95830eb93b2548/pkg/ccl/changefeedccl/kvevent/blocking_buffer_test.go#L93)):*
> ```Go
> 	}
> 
> 	// Keep consuming events until buffer enters pushback.
> ```

thoughts: It looks to me like this test depends on the 10 goroutines started above filling the buffer faster than our one goroutine can cosume the events (seems very likely given the small size of the buffer and the size of the messages).  If we broke the accounting though, I think this would fail by timing out. That's probably OK given how many tests we have that operate that way but perhaps a comment to remind us would be good.

I can't think of a way to _guarantee_ the buffer enters pushback without some testing hooks inside the blocking buffer.  But, we might be able to reduce the (already small) chance of this flaking out by synchronously pre-filling the buffer before starting the async producers (or waiting to start the consumer until some number of messages have been pushed).

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68256)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @stevendanna)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/68256#-MfrjQgs9uq1b5d-hu8I:-MfrmO54EITLDSUnzCrt:bb7cwne) (no related file):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Seems like a reasonable metric to add to me.  Looks like there are some CI issues but otherwise seems good.
</blockquote></details>

ack.

---
___
*[pkg/ccl/changefeedccl/kvevent/blocking_buffer_test.go, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68256#-Mfrf3QTAp4ua0Eq1UhD:-MfrpBHg45fZGB1uBpDQ:br6q0cc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e02444935ff125756c9e2bf41b95830eb93b2548/pkg/ccl/changefeedccl/kvevent/blocking_buffer_test.go#L30)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

You likely need to `make bazel-generate` after these import changes.
</blockquote></details>

One day I'll remember to do that.  But not today.
___
*[pkg/ccl/changefeedccl/kvevent/blocking_buffer_test.go, line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68256#-Mfrf8Zt1vc-rTyblajn:-Mfs0D683IzrAr6RfOQF:b1nl5dp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e02444935ff125756c9e2bf41b95830eb93b2548/pkg/ccl/changefeedccl/kvevent/blocking_buffer_test.go#L93)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

thoughts: It looks to me like this test depends on the 10 goroutines started above filling the buffer faster than our one goroutine can cosume the events (seems very likely given the small size of the buffer and the size of the messages).  If we broke the accounting though, I think this would fail by timing out. That's probably OK given how many tests we have that operate that way but perhaps a comment to remind us would be good.

I can't think of a way to _guarantee_ the buffer enters pushback without some testing hooks inside the blocking buffer.  But, we might be able to reduce the (already small) chance of this flaking out by synchronously pre-filling the buffer before starting the async producers (or waiting to start the consumer until some number of messages have been pushed).
</blockquote></details>

I think you made a good comment, calling out my "laziness".  Turns out there is a perfectly nice way of accomplishing good what this test is trying to accomplish without testing hooks.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68256)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @stevendanna)

___
*[pkg/ccl/changefeedccl/kvevent/blocking_buffer_test.go, line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68256#-Mfrf8Zt1vc-rTyblajn:-Mfs1-Pc2ZR3PLycSyRH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e02444935ff125756c9e2bf41b95830eb93b2548/pkg/ccl/changefeedccl/kvevent/blocking_buffer_test.go#L93)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I think you made a good comment, calling out my "laziness".  Turns out there is a perfectly nice way of accomplishing good what this test is trying to accomplish without testing hooks.
</blockquote></details>

Done.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68256)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @stevendanna)

___
*[pkg/ccl/changefeedccl/kvevent/blocking_buffer_test.go, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68256#-Mfrf3QTAp4ua0Eq1UhD:-Mfs10jMAqpf6oIWQ4WK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e02444935ff125756c9e2bf41b95830eb93b2548/pkg/ccl/changefeedccl/kvevent/blocking_buffer_test.go#L30)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

One day I'll remember to do that.  But not today.
</blockquote></details>

Done.

**Review by stevendanna — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68256)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @miretskiy, and @stevendanna)

___
*[pkg/ccl/changefeedccl/kvevent/blocking_buffer_test.go, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68256#-Mfs2Dvz9y7WrDm4TQBC:-Mfs2Dvz9y7WrDm4TQBD:byjtl22) ([raw file](https://github.com/cockroachdb/cockroach/blob/da9ee6ff7804bf965f4c8532207c7760ba9becc9/pkg/ccl/changefeedccl/kvevent/blocking_buffer_test.go#L76)):*
> ```Go
> 	// Arrange for mem buffer to notify us when it waits for resources.
> 	var waitMu syncutil.Mutex
> 	waited := sync.NewCond(&waitMu)
> ```

up to you: we could use a `chan struct{}` here instead. Not sure which people generally find easier to read.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68256)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @stevendanna)

___
*[pkg/ccl/changefeedccl/kvevent/blocking_buffer_test.go, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68256#-Mfs2Dvz9y7WrDm4TQBC:-Mfs7CNdEA921Bh36QXZ:bf92rce) ([raw file](https://github.com/cockroachdb/cockroach/blob/da9ee6ff7804bf965f4c8532207c7760ba9becc9/pkg/ccl/changefeedccl/kvevent/blocking_buffer_test.go#L76)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

up to you: we could use a `chan struct{}` here instead. Not sure which people generally find easier to read.
</blockquote></details>

I was worried that I would have multiple write attempts; or read attempts; or close attempts...
I think condition here is good.

**Comment by miretskiy** [comment]
tftr
bors r=stevendanna

**Comment by miretskiy** [comment]
@stevendanna @ajwerner I made some changes suggested by Andrew re not keeping track of additional state in the blocking buffer and just making few minor changes in quota pool so that we can leverage existing functionality.
PTAL.

**Review by ajwerner — APPROVED** [review]
LGTM

**Pull request merged**
