### PR TITLE
allocator2: misc building blocks

### PR DESCRIPTION
**Pull request by sumeerbhola**
Lowest layers:
- Interned constraints in constraint.go: optimization to avoid string
  comparisons and cheaper hash computation for an expression.
- Load helpers in load.go
- Constraint matching in constraint_matcher.go

Next higher layer:
- Cluster state in cluster_state.go
- Request-response messages exchanged with each store

Highest layer (missing most functionality):
- Allocator: some core allocator logic in allocator_state.go

Epic: none

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
The first commit is from https://github.com/cockroachdb/cockroach/pull/98877

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99977#-:-NRj2KQ0DMXe9r9Bl-yt:b-kv7a2e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

**Review by kvoli — COMMENTED** [review]
I left some comments, mostly regarding things we talked about previously in person.

I'm happy with merging this in and working through the minimum number of TODOs to get an e2e unit test running on `computeChanges` for rebalancing or allocation.

Moving cache entry population logic out of policy functions would make the core logic of the code easier to follow / distill the algorithm logic.

> Reviewed 2 of 3 files at r1, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99977#-:-NV1LUQh4YfLud3Au-m_:bj2ldob)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/allocator/allocator2/allocator_state.go` line 54 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99977#-NV-x0Mn2YKk6Uce06T4:-NV-x0Mn2YKk6Uce06T5:b-75wclq) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c9c21f7a7189fdf46c630e23e0d518f662a979e/pkg/kv/kvserver/allocator/allocator2/allocator_state.go#L54)):*
> ```Go
> 	// example).
> 	//
> 	// TODO: discuss with Austen.
> ```

We discussed this a while back. We could have a relaxed tolerance for rebalancing across subsets with a lower mean than the cluster average. 
___
*[`pkg/kv/kvserver/allocator/allocator2/allocator_state.go` line 147 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99977#-NV1DclvAZ3q12d1U1C8:-NV1DclvAZ3q12d1U1C9:b-euka4x) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c9c21f7a7189fdf46c630e23e0d518f662a979e/pkg/kv/kvserver/allocator/allocator2/allocator_state.go#L147)):*
> ```Go
> 	disjString := c.toString()
> 	means := a.meansMemo.tryGetMeans(disjString)
> 	if means == nil {
> ```

Discussed in person - moving any cached entry population logic out of decision-like functions would make the policy "meat" easier to grep at a glance.
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 202 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99977#-NV0-qNX5VbqBhGeL6dz:-NV0-qNX5VbqBhGeL6e-:b-2x5t3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c9c21f7a7189fdf46c630e23e0d518f662a979e/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L202)):*
> ```Go
> type failureDetectionSummary uint8
> 
> // TODO(sumeer): should this more similar to node liveness
> ```

For status

unavailable - currently we don't move anything towards the node but we also don't remove to prevent thrashing
drain - move leases off, don't move anything towards the node
suspect - don't move leases off, don't move anything towards the node
dead - upreplicate

Failure likely could be mapped to dead
Shed leases can map to drain

EDIT: With our conversation in person earlier, I agree we could externalize this and just map to overload states, we probably want to be able to specify a few different combinations of eligibility:

A  - valid target for leases, replicas (standard)
B  - won't be target of leases, valid target for recovery replica allocation (used for IO overload atm, may not be necessary since we can be more coherent balancing IO and CPU)
C  - won't be target of replicas (recovery or rebalancing), won't be target of leases (suspect state - a useful state to have, where we don't shed but also don't add anything new)
B  - actively shed leases, superset of A (draining state - required, although at the moment the drain process actually handles calling "shedLease" to trigger transfer leases away)
C  - actively remove replicas, superset of B (dead state)
___
*[`pkg/kv/kvserver/allocator/allocator2/load.go` line 52 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99977#-NV1G9WM7THTjppwcGAK:-NV1G9WM7THTjppwcGAL:bzb94oj) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c9c21f7a7189fdf46c630e23e0d518f662a979e/pkg/kv/kvserver/allocator/allocator2/load.go#L52)):*
> ```Go
> 
> // TODO(sumeer): do we need to move replicas too, in order to do lease
> // rebalancing, or can we assume that constraints and diversity scores have
> ```

If we are concerned with the primary dimensions, then moving leases is much cheaper than replicas. Moving replicas is however necessary when we can't resolve overload/imbalance  or whatever objective just on lease impact.

For a secondary dimension - not the biggest issue to balance lease counts imo, moving them between existing voters seems sufficient. If the lease preference is incoherent with the replica constraints we don't handle it currently and probably wouldn't need to.

This also reminds me, we haven't included anything regarding lease preferences so far. We can add it later but it warrants a TODO imo. See https://github.com/cockroachdb/cockroach/pull/98893, we don't handle synthesizing the preferences to come up with a load mean today.
___
*[`pkg/kv/kvserver/allocator/allocator2/load.go` line 68 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99977#-NV00gWt53Byn4DLlY51:-NV00gWt53Byn4DLlY52:b-cc20rq) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c9c21f7a7189fdf46c630e23e0d518f662a979e/pkg/kv/kvserver/allocator/allocator2/load.go#L68)):*
> ```Go
> type rangeLoad struct {
> 	load loadVector
> 	// Nanos per second. raftCPU <= load[cpu]. Handling this as a special case,
> ```

There's also potential for considering non-uniform follower work e.g. 

consider a range with replicas a,b,c, where the leaseholder is a.

The non-raft CPU could be identical between a and c, where c is serving follower reads (or misrouted requests).

moving the lease from a to c has an impact of doubling c's non-raft traffic.

moving a replica off of c has a known impact (raft) + an unknown(?) impact, but presumably the follower traffic goes to the new replica, say d.

We don't do anything for this at the moment and the split between lease/replica CPU is to differentiate between the impact of moving a lease vs replica atm.

It feels like we can plumb this extra stuff in later if necessary.
___
*[`pkg/kv/kvserver/allocator/allocator2/load.go` line 360 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99977#-NV1FYcY-nAKsxDzZibB:-NV1FYcZ1z7sZJDnUJ85:b-virp2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c9c21f7a7189fdf46c630e23e0d518f662a979e/pkg/kv/kvserver/allocator/allocator2/load.go#L360)):*
> ```Go
> 	}
> 	loadSummary := loadLow
> 	// Heuristics: this is all very rough and subject to revision. There are two
> ```

This approach seems good to build around. If we discover it doesn't handle certain cases well e.g. small nodes, ranges near max range thresholds in some dimensions - then we can handle it later.

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> Moving cache entry population logic out of policy functions would make the core logic of the code easier to follow / distill the algorithm logic.

Done

Rebased on master and marking this as ready for review.

> I'm happy with merging this in and working through the minimum number of TODOs to get an e2e unit test running on `computeChanges` for rebalancing or allocation.

Sounds good. I can merge and then start fleshing out some unit tests for the lower layers (and fixing the TODOs).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99977#-:-NV7c7wiBg8c2RyOje6c:bqjeswg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/allocator/allocator2/allocator_state.go` line 54 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99977#-NV-x0Mn2YKk6Uce06T4:-NV7cCyx3bdawZrO0fUc:b-mh0nrt) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c9c21f7a7189fdf46c630e23e0d518f662a979e/pkg/kv/kvserver/allocator/allocator2/allocator_state.go#L54)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

We discussed this a while back. We could have a relaxed tolerance for rebalancing across subsets with a lower mean than the cluster average. 
</blockquote></details>

Ack. Removed the "discuss" TODO.
___
*[`pkg/kv/kvserver/allocator/allocator2/allocator_state.go` line 147 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99977#-NV1DclvAZ3q12d1U1C8:-NV7cKV_51tKg8hcih1E:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c9c21f7a7189fdf46c630e23e0d518f662a979e/pkg/kv/kvserver/allocator/allocator2/allocator_state.go#L147)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Discussed in person - moving any cached entry population logic out of decision-like functions would make the policy "meat" easier to grep at a glance.
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/allocator/allocator2/allocator_state.go` line 269 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/99977#-NV7eU5U5aMGRIAoRe78:-NV7eU5U5aMGRIAoRe79:bf1pbg1) ([raw file](https://github.com/cockroachdb/cockroach/blob/394cbb8699f234faa4b6dd34da33c9cf113be55e/pkg/kv/kvserver/allocator/allocator2/allocator_state.go#L269)):*
> ```Go
> 
> type diversityScoringMemo struct {
> 	replicasMap *clearableMemoMap[replicasLocalityTiers, *existingReplicaLocalities]
> ```

This is the other use of `clearableMemoMap`.
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 202 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99977#-NV0-qNX5VbqBhGeL6dz:-NV5pF913QgzL8JcbUMA:b6xju2w) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c9c21f7a7189fdf46c630e23e0d518f662a979e/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L202)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

For status

unavailable - currently we don't move anything towards the node but we also don't remove to prevent thrashing
drain - move leases off, don't move anything towards the node
suspect - don't move leases off, don't move anything towards the node
dead - upreplicate

Failure likely could be mapped to dead
Shed leases can map to drain

EDIT: With our conversation in person earlier, I agree we could externalize this and just map to overload states, we probably want to be able to specify a few different combinations of eligibility:

A  - valid target for leases, replicas (standard)
B  - won't be target of leases, valid target for recovery replica allocation (used for IO overload atm, may not be necessary since we can be more coherent balancing IO and CPU)
C  - won't be target of replicas (recovery or rebalancing), won't be target of leases (suspect state - a useful state to have, where we don't shed but also don't add anything new)
B  - actively shed leases, superset of A (draining state - required, although at the moment the drain process actually handles calling "shedLease" to trigger transfer leases away)
C  - actively remove replicas, superset of B (dead state)

</blockquote></details>

I've changed the `failureDetectionSummary` to mirror the states you mentioned. And removed these from the `loadSummary` since I think the combinations are getting a bit complicated. We can first attempt to use the tuple `(loadSummary, loadSummary, failureDetectionSummary)` and see how that works out.
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 490 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/99977#-NV7e6eG9K87zjcJ3ZxJ:-NV7e6eG9K87zjcJ3ZxK:b-8pt0qu) ([raw file](https://github.com/cockroachdb/cockroach/blob/394cbb8699f234faa4b6dd34da33c9cf113be55e/pkg/kv/kvserver/allocator/allocator2/constraint.go#L490)):*
> ```Go
> 
> // FNV-1a hash algorithm.
> func (cd constraintsDisj) hash() uint64 {
> ```

A cheap hash was the initial motivation for `internedConstraint`.
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 1011 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/99977#-NV7dtmv1NI18Tfay51O:-NV7dtmv1NI18Tfay51P:byqh70r) ([raw file](https://github.com/cockroachdb/cockroach/blob/394cbb8699f234faa4b6dd34da33c9cf113be55e/pkg/kv/kvserver/allocator/allocator2/constraint.go#L1011)):*
> ```Go
> // lower memory consumption or to prevent overflow. The empty string is
> // assigned code 0.
> type stringInterner struct {
> ```

Pulled out the `stringInterner` so we can intern the constraints too.
___
*[`pkg/kv/kvserver/allocator/allocator2/load.go` line 52 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99977#-NV1G9WM7THTjppwcGAK:-NV5f4TZ6A79TD2Tw_J5:b-runusy) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c9c21f7a7189fdf46c630e23e0d518f662a979e/pkg/kv/kvserver/allocator/allocator2/load.go#L52)):*
> If we are concerned with the primary dimensions, then moving leases is much cheaper than replicas. Moving replicas is however necessary when we can't resolve overload/imbalance or whatever objective just on lease impact.

Ack. I was imagining that the consideration of first moving leases will be encoded into the rebalancing logic like in the allocator kernel https://github.com/cockroachdb/cockroach/blob/50a4f1705ad14bce86ba4f95e9ed5193e7f2f91a/pkg/kv/kvserver/allocator/aimpl/allocator.go#L418-L420

> For a secondary dimension - not the biggest issue to balance lease counts imo, moving them between existing voters seems sufficient.

Great

> This also reminds me, we haven't included anything regarding lease preferences so far. We can add it later but it warrants a TODO imo. See [#98893](https://github.com/cockroachdb/cockroach/pull/98893), we don't handle synthesizing the preferences to come up with a load mean today.

Added to the todo
___
*[`pkg/kv/kvserver/allocator/allocator2/load.go` line 68 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99977#-NV00gWt53Byn4DLlY51:-NV5gcqX1_44rraVU8Id:b6x38nv) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c9c21f7a7189fdf46c630e23e0d518f662a979e/pkg/kv/kvserver/allocator/allocator2/load.go#L68)):*
> The non-raft CPU could be identical between a and c, where c is serving follower reads (or misrouted requests).

This seems complicated in that if we move the lease from a => c, maybe `a` will start serving follower reads for its region. In general, knowing why someone is serving follower reads (due to its placement, or simply load-balancing), seems to be too complicated to incorporate into the allocator. I am hoping that by having a few pending changes, and no range consuming a large fraction of the store/node resources we can get away with lower fidelity predictions. I have updated this comment to say something about a pessimistic assumption -- that way the lower fidelity does not cause an unexpected overload in the target store.
___
*[`pkg/kv/kvserver/allocator/allocator2/load.go` line 360 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99977#-NV1FYcY-nAKsxDzZibB:-NV7c4KfA-b8CqqJf7gU:b2nhb2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c9c21f7a7189fdf46c630e23e0d518f662a979e/pkg/kv/kvserver/allocator/allocator2/load.go#L360)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

This approach seems good to build around. If we discover it doesn't handle certain cases well e.g. small nodes, ranges near max range thresholds in some dimensions - then we can handle it later. 
</blockquote></details>

Ack
___
*[`pkg/kv/kvserver/allocator/allocator2/load.go` line 263 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/99977#-NV7dDQ74rQlfVhfAvlj:-NV7dDQ74rQlfVhfAvlk:bs2wntq) ([raw file](https://github.com/cockroachdb/cockroach/blob/394cbb8699f234faa4b6dd34da33c9cf113be55e/pkg/kv/kvserver/allocator/allocator2/load.go#L263)):*
> ```Go
> 
> func newMeansMemo(
> 	loadInfoProvider loadInfoProvider, constraintMatcher *constraintMatcher,
> ```

I expanded the interface of `loadInfoProvider` and also passed in `constraintMatcher` to make `meansMemo` self-sufficient in populating the cache. The `loadInfoProvider` is implemented by a higher-layer (`clusterState`), hence hidden behind an interface.

**Review by kvoli — APPROVED** [review]
:lgtm:

> Reviewed 1 of 9 files at r4, 4 of 6 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99977#-:-NVBgxdW9IZpAeSvviuZ:bg7igk9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/allocator/allocator2/allocator_state.go` line 147 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99977#-NV1DclvAZ3q12d1U1C8:-NVBe5mKBW_mqgyCOdbu:byc0je1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c9c21f7a7189fdf46c630e23e0d518f662a979e/pkg/kv/kvserver/allocator/allocator2/allocator_state.go#L147)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Done
</blockquote></details>

Thanks, this is easier to read and understand the key logic.
___
*[`pkg/kv/kvserver/allocator/allocator2/allocator_state.go` line 269 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/99977#-NV7eU5U5aMGRIAoRe78:-NVBeJX8EZX_IoU4YEFY:b2nhb2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/394cbb8699f234faa4b6dd34da33c9cf113be55e/pkg/kv/kvserver/allocator/allocator2/allocator_state.go#L269)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This is the other use of `clearableMemoMap`.
</blockquote></details>

Ack
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 202 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99977#-NV0-qNX5VbqBhGeL6dz:-NVAH2Z25_jXa3PeIvjL:bb73djm) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c9c21f7a7189fdf46c630e23e0d518f662a979e/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L202)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I've changed the `failureDetectionSummary` to mirror the states you mentioned. And removed these from the `loadSummary` since I think the combinations are getting a bit complicated. We can first attempt to use the tuple `(loadSummary, loadSummary, failureDetectionSummary)` and see how that works out.
</blockquote></details>

SGTM
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 104 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/99977#-NVAHJZA9OyW151DUSOJ:-NVAHJZB3LfJrufgKAx9:b-5m3ipm) ([raw file](https://github.com/cockroachdb/cockroach/blob/59edd30b1d99b034829de9737bcce223b37633f2/pkg/kv/kvserver/allocator/allocator2/constraint.go#L104)):*
> ```Go
> 	voterConstraints []internedConstraintsConjunction
> 	// Best-effort. Conjunctions are in order of preference, and it is ok if
> 	// none is satisfied.
> ```

nit: none are
___
*[`pkg/kv/kvserver/allocator/allocator2/load.go` line 68 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99977#-NV00gWt53Byn4DLlY51:-NVAJCCpBJo3X1JIZgRc:b-1lvup9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c9c21f7a7189fdf46c630e23e0d518f662a979e/pkg/kv/kvserver/allocator/allocator2/load.go#L68)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> The non-raft CPU could be identical between a and c, where c is serving follower reads (or misrouted requests).

This seems complicated in that if we move the lease from a => c, maybe `a` will start serving follower reads for its region. In general, knowing why someone is serving follower reads (due to its placement, or simply load-balancing), seems to be too complicated to incorporate into the allocator. I am hoping that by having a few pending changes, and no range consuming a large fraction of the store/node resources we can get away with lower fidelity predictions. I have updated this comment to say something about a pessimistic assumption -- that way the lower fidelity does not cause an unexpected overload in the target store.
</blockquote></details>

I don't think end users would route queries based on leaseholder placement? Is the load balancing you're referring to - SQL load balancing - if so, my assumption was that if there were no replica movements and only lease transfers, that the follower read routing policy wouldn't change. I'm not sure on this though and have only had a light read through some relevant code like https://github.com/cockroachdb/cockroach/blob/f04439ccda905bf003f77dd341b1bd123075a332/pkg/sql/physicalplan/replicaoracle/oracle.go#L174.


I'm in favor of not making plans to incorporate this concept but it may be a (marginal) improvement for estimating impact in the distant future.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99977)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kvoli)

___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 104 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/99977#-NVAHJZA9OyW151DUSOJ:-NVBnocCEtrMGFheCBae:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/59edd30b1d99b034829de9737bcce223b37633f2/pkg/kv/kvserver/allocator/allocator2/constraint.go#L104)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: none are
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/allocator/allocator2/load.go` line 68 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99977#-NV00gWt53Byn4DLlY51:-NVBvTDI9OG0Of75W1wV:bf78dkn) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c9c21f7a7189fdf46c630e23e0d518f662a979e/pkg/kv/kvserver/allocator/allocator2/load.go#L68)):*
> if there were no replica movements and only lease transfers, that the follower read routing policy wouldn't change

I was speculating about future improvements that load-balance across equidistant replicas. Generally speaking, it would be nice if we can avoid knowing too much about the routing policies inside the allocator, but if we have to eventually, so be it.

**Comment by sumeerbhola** [comment]
bors r=kvoli

**Pull request merged**
