### PR TITLE
schemachanger: zone config refactor

### PR DESCRIPTION
**Pull request by annrpom**
This patch refactors some of the zone config logic
in the DSC.

Epic: [CRDB-31473](https://cockroachlabs.atlassian.net/browse/CRDB-31473)
Informs: #129889

Release note: None

### CODE REVIEW

**Comment by annrpom** [comment]
I'm still not entirely satisfied -- trying to think about what i can do to `applyZoneConfig`

**Review by spilchen — COMMENTED** [review]
I like this refactor—it makes the `applyZoneConfig` functions easier to follow. There’s still some code duplication between handling index and table/database objects, but I think that's unavoidable.

> Reviewed 3 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129065#-:-O5s21mG1YHXVuP9QknJ:b8gqsrk)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129065#-O5rt1iE3aeU8mDQDALU:-O5rt1iE3aeU8mDQDALV:b6uf0yo) ([raw file](https://github.com/cockroachdb/cockroach/blob/d96da2a94436d0e6e0fb489fcf818f149d4cc635/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go#L41)):*
> ```Go
> 	// - Partition/row
> 	// - System Ranges
> 	zoneConfigObject := astToZoneConfigObject(b, n)
> ```

I suggest returning the object along with an error. For unsupported modes, we can provide more meaningful error messages. For example, when `n.Discard` is true, we previously returned an error stating "CONFIGURE ZONE DISCARD is not supported in the DSC." Retaining these specific errors would be beneficial, and returning the error will allow you to do that.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/database_zone_config.go` line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129065#-O5rxfLk0v2VVJynM0xu:-O5rxfLk0v2VVJynM0xv:b-hl2fnr) ([raw file](https://github.com/cockroachdb/cockroach/blob/d96da2a94436d0e6e0fb489fcf818f149d4cc635/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/database_zone_config.go#L66)):*
> ```Go
> 	return sqlerrors.NewInsufficientPrivilegeOnDescriptorError(b.CurrentUser(),
> 		reqNonAdminPrivs, string(catalog.Database),
> 		mustRetrieveNamespaceElem(b, dbElem.DatabaseID).Name)
> ```

Will we have a namespace element for a database? I thought those only made sense in the context of table-specific elements.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go` line 1705 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129065#-O5rvQF_0bbmjDnEjPiZ:-O5rvQF_0bbmjDnEjPi_:b-l2e5kp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d96da2a94436d0e6e0fb489fcf818f149d4cc635/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go#L1705)):*
> ```Go
> // mustRetrievePhysicalTableElem will resolve a tableID to a physical table
> // element. A "physical" table element includes tables, views, and sequences.
> func mustRetrievePhysicalTableElem(b BuildCtx, tableID catid.DescID) scpb.Element {
> ```

nit: I suggest renaming `tableID` to `descID` or something similar. It won't always be a table ID; for example, it could represent a view or sequence ID.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/table_zone_config.go` line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129065#-O5rx9Uj0umR69U0P-NU:-O5rx9Uj0umR69U0P-NV:btsu2fa) ([raw file](https://github.com/cockroachdb/cockroach/blob/d96da2a94436d0e6e0fb489fcf818f149d4cc635/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/table_zone_config.go#L71)):*
> ```Go
> 
> 	reqNonAdminPrivs := []privilege.Kind{privilege.ZONECONFIG, privilege.CREATE}
> 	if zs.Database == "system" {
> ```

Will ever be true for table zone configs? I thought `zs.Database` would be an empty string.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go` line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129065#-O5s-CkaBHxUVqNlrmjd:-O5s-CkaBHxUVqNlrmje:br25b51) ([raw file](https://github.com/cockroachdb/cockroach/blob/d96da2a94436d0e6e0fb489fcf818f149d4cc635/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go#L71)):*
> ```Go
> 
> 	// getSeqNum returns the sequence number of the zone config object.
> 	getSeqNum() uint32
> ```

Do we use this function anywhere? I couldn't find any usages of it myself.

**Review by annrpom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129065)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129065#-O5rt1iE3aeU8mDQDALU:-O5sLr1A8X7GTl6L5cIR:b-g7pros) ([raw file](https://github.com/cockroachdb/cockroach/blob/d96da2a94436d0e6e0fb489fcf818f149d4cc635/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go#L41)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

I suggest returning the object along with an error. For unsupported modes, we can provide more meaningful error messages. For example, when `n.Discard` is true, we previously returned an error stating "CONFIGURE ZONE DISCARD is not supported in the DSC." Retaining these specific errors would be beneficial, and returning the error will allow you to do that.
</blockquote></details>

done -- good point
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/database_zone_config.go` line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129065#-O5rxfLk0v2VVJynM0xu:-O5sLuLYAauWVMEG0D8k:bc369vt) ([raw file](https://github.com/cockroachdb/cockroach/blob/d96da2a94436d0e6e0fb489fcf818f149d4cc635/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/database_zone_config.go#L66)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Will we have a namespace element for a database? I thought those only made sense in the context of table-specific elements.
</blockquote></details>

yes; see https://github.com/cockroachdb/cockroach/blob/eef5580639280432275da0f0638dea8bd5091734/pkg/sql/catalog/dbdesc/database_desc.go#L594-L597 and https://github.com/cockroachdb/cockroach/blob/4625d8b32615bf01bf37ce5b833950ab3ac2a0f4/pkg/sql/schemachanger/scdecomp/decomp.go#L91-L98

fwiw, though: the namespace element for a db is just the `DescriptorID` and `Name`
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go` line 1705 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129065#-O5rvQF_0bbmjDnEjPiZ:-O5sQ53oAudq4d5nr8Kv:b-7rl0jq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d96da2a94436d0e6e0fb489fcf818f149d4cc635/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go#L1705)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

nit: I suggest renaming `tableID` to `descID` or something similar. It won't always be a table ID; for example, it could represent a view or sequence ID.
</blockquote></details>

done!
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/table_zone_config.go` line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129065#-O5rx9Uj0umR69U0P-NU:-O5sQtRv1UmbjdjSs2jU:b-n2no8g) ([raw file](https://github.com/cockroachdb/cockroach/blob/d96da2a94436d0e6e0fb489fcf818f149d4cc635/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/table_zone_config.go#L71)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Will ever be true for table zone configs? I thought `zs.Database` would be an empty string.
</blockquote></details>

done -- bad copy & paste
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go` line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129065#-O5s-CkaBHxUVqNlrmjd:-O5sREA33pwy_aLTCjK3:b-73iodd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d96da2a94436d0e6e0fb489fcf818f149d4cc635/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go#L71)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Do we use this function anywhere? I couldn't find any usages of it myself.
</blockquote></details>

done -- removed since no longer used!

**Review by spilchen — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129065#-:-O5syx4_BuQfqh2HZzW0:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @annrpom)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/database_zone_config.go` line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129065#-O5rxfLk0v2VVJynM0xu:-O5syath-fpOmBApKv5I:b-wsvas3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d96da2a94436d0e6e0fb489fcf818f149d4cc635/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/database_zone_config.go#L66)):*
<details><summary><i>Previously, annrpom (annie pompa) wrote…</i></summary><blockquote>

yes; see https://github.com/cockroachdb/cockroach/blob/eef5580639280432275da0f0638dea8bd5091734/pkg/sql/catalog/dbdesc/database_desc.go#L594-L597 and https://github.com/cockroachdb/cockroach/blob/4625d8b32615bf01bf37ce5b833950ab3ac2a0f4/pkg/sql/schemachanger/scdecomp/decomp.go#L91-L98

fwiw, though: the namespace element for a db is just the `DescriptorID` and `Name`
</blockquote></details>

Thanks for the explanation.

**Comment by annrpom** [comment]
Needed to rebase to get a test-flake-fix in! TFTR! ('-')7

**Comment by annrpom** [comment]
bors r=spilchen

**Pull request merged**
