### PR TITLE
sqlccl: construct expressions to match rows in partitions

### PR DESCRIPTION
**Pull request by danhhz**
selectPartitionExprs constructs an expression for selecting all rows in given partitions. This is most of the interesting logic behind the upcoming `SELECT ... FROM ... PARTITION (p0, p1)`.

### CODE REVIEW

**Comment by benesch** [comment]
Nice! Just a few nits below.

---

Reviewed 4 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/sqlccl/partition.go, line 203 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21049#-L1JFX-V9B3vaaXt5-_B:-L1JFX-V9B3vaaXt5-_C:bmte54h) ([raw file](https://github.com/cockroachdb/cockroach/blob/22356279539c7f6ddf0eae76bfe09ea08e38c1b5/pkg/ccl/sqlccl/partition.go#L203)):*
> ```Go
> 	if err != nil {
> 		return nil, err
> 	}
> ```

Normalization should actually happen before simplification. I got this wrong when I wrote the the `CHECK` constraint logic. (If you don't flip the order, then the code simplification I propose below generates ever-so-slightly messier expressions. But once you flip the normalization/simplification order, the generated expressions are identical.)

---

*[pkg/ccl/sqlccl/partition.go, line 256 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21049#-L1J74_MjGN0ELb1geez:-L1J74_MjGN0ELb1gef-:b-eo26n0) ([raw file](https://github.com/cockroachdb/cockroach/blob/22356279539c7f6ddf0eae76bfe09ea08e38c1b5/pkg/ccl/sqlccl/partition.go#L256)):*
> ```Go
> 			colVars[i] = tree.NewTypedOrdinalReference(int(cols[i].ID), cols[i].Type.ToDatumType())
> 		}
> 	}
> ```

Do this all in one loop?

```go
colVars := make(tree.TypedExprs, len(prefixDatums)+int(partDesc.NumColumns))
for i := range colVars {
	col, err := tableDesc.FindActiveColumnByID(idxDesc.ColumnIDs[i])
	if err != nil {
		return err
	}
	colVars[i] = tree.NewTypedOrdinalReference(int(col.ID), col.Type.ToDatumType())
}
```

---

*[pkg/ccl/sqlccl/partition.go, line 306 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21049#-L1JFPOkwWJq1UMppANU:-L1JFPOkwWJq1UMppANV:bko7tly) ([raw file](https://github.com/cockroachdb/cockroach/blob/22356279539c7f6ddf0eae76bfe09ea08e38c1b5/pkg/ccl/sqlccl/partition.go#L306)):*
> ```Go
> 		// b) != (2, 3)`, where the `!= (2, 3)` part is irrelevant. This only
> 		// happens in fairly unrealistic partitionings, so it's unclear if
> 		// anything really needs to be done here.
> ```

Can you add a test case that exercises that? I'm having trouble envisioning what partitioning scheme causes this subpar behavior.

---

*[pkg/ccl/sqlccl/partition.go, line 327 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21049#-L1JD9pqPj91KZB3nZr6:-L1JD9pqPj91KZB3nZr7:b-91peyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/22356279539c7f6ddf0eae76bfe09ea08e38c1b5/pkg/ccl/sqlccl/partition.go#L327)):*
> ```Go
> 					exprsByPartName[partName] = partValueExpr
> 				} else {
> 					exprsByPartName[partName] = tree.NewTypedOrExpr(e, partValueExpr)
> ```

I don't think this branch is ever taken? (And, in fact, I don't understand what it would mean to take this branch.)

---

*[pkg/ccl/sqlccl/partition.go, line 335 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21049#-L1JEu53aRlgOyXMyWpI:-L1JEu54ph2Z41OnM2oF:bihiddy) ([raw file](https://github.com/cockroachdb/cockroach/blob/22356279539c7f6ddf0eae76bfe09ea08e38c1b5/pkg/ccl/sqlccl/partition.go#L335)):*
> ```Go
> 				excludeExpr = nextExcludeExpr
> 			}
> 		}
> ```

In fact, I think this whole stanza can be much simplified!

```go
excludeExpr := tree.TypedExpr(tree.DBoolFalse)
for i := len(partValueExprs) - 1; i >= 0; i-- {
	nextExcludeExpr := tree.TypedExpr(tree.DBoolFalse)
	for _, v := range partValueExprs[i] {
		exprsByPartName[v.name] = tree.NewTypedAndExpr(v.expr, tree.NewTypedNotExpr(excludeExpr))
		nextExcludeExpr = tree.NewTypedOrExpr(nextExcludeExpr, v.expr)
	}
	excludeExpr = tree.NewTypedOrExpr(excludeExpr, nextExcludeExpr)
}
```

---

*[pkg/ccl/sqlccl/partition_test.go, line 976 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21049#-L1JFKLaHmYCxv-IXP4u:-L1JFKLaHmYCxv-IXP4v:b-3jighr) ([raw file](https://github.com/cockroachdb/cockroach/blob/22356279539c7f6ddf0eae76bfe09ea08e38c1b5/pkg/ccl/sqlccl/partition_test.go#L976)):*
> ```Go
> 				PARTITION p7dd VALUES IN ((DEFAULT, DEFAULT))
> 			),
> 			PARTITION pd VALUES IN (DEFAULT)
> ```

Can you add a test case for that TODO above that mentions the irrelevant branch?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21049#-:-L1JGFbl3kgMXD6fvDN7:badlamh)*

**Comment by danhhz** [comment]
Review status: 4 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/ccl/sqlccl/partition.go, line 203 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21049#-L1JFX-V9B3vaaXt5-_B:-L1NS63zbs7qoFbmyJwA:b-ym6mlb) ([raw file](https://github.com/cockroachdb/cockroach/blob/22356279539c7f6ddf0eae76bfe09ea08e38c1b5/pkg/ccl/sqlccl/partition.go#L203)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Normalization should actually happen before simplification. I got this wrong when I wrote the the `CHECK` constraint logic. (If you don't flip the order, then the code simplification I propose below generates ever-so-slightly messier expressions. But once you flip the normalization/simplification order, the generated expressions are identical.)
</blockquote></details>

Aha! That's why I'd done all the nil check craziness below

---

*[pkg/ccl/sqlccl/partition.go, line 256 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21049#-L1J74_MjGN0ELb1geez:-L1NRBkYUs_0tcYevW26:b-5lskcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/22356279539c7f6ddf0eae76bfe09ea08e38c1b5/pkg/ccl/sqlccl/partition.go#L256)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Do this all in one loop?

```go
colVars := make(tree.TypedExprs, len(prefixDatums)+int(partDesc.NumColumns))
for i := range colVars {
	col, err := tableDesc.FindActiveColumnByID(idxDesc.ColumnIDs[i])
	if err != nil {
		return err
	}
	colVars[i] = tree.NewTypedOrdinalReference(int(col.ID), col.Type.ToDatumType())
}
```
</blockquote></details>

Hmm, no idea what I was thinking. Done

---

*[pkg/ccl/sqlccl/partition.go, line 306 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21049#-L1JFPOkwWJq1UMppANU:-L1NcjtB9n01Q1EcxD8F:bzf5zh4) ([raw file](https://github.com/cockroachdb/cockroach/blob/22356279539c7f6ddf0eae76bfe09ea08e38c1b5/pkg/ccl/sqlccl/partition.go#L306)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Can you add a test case that exercises that? I'm having trouble envisioning what partitioning scheme causes this subpar behavior.
</blockquote></details>

Done. I've also (hopefully) improved the comment

---

*[pkg/ccl/sqlccl/partition.go, line 327 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21049#-L1JD9pqPj91KZB3nZr6:-L1NSAFvMNaoUy7Hp8RR:bucfo22) ([raw file](https://github.com/cockroachdb/cockroach/blob/22356279539c7f6ddf0eae76bfe09ea08e38c1b5/pkg/ccl/sqlccl/partition.go#L327)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I don't think this branch is ever taken? (And, in fact, I don't understand what it would mean to take this branch.)
</blockquote></details>

Any partition with multiple values/tuples will hit it (`PARTITION BY LIST (a) (PARTITION b IN ((1), (2))`). Looks like there's no test case for it. Whoops

---

*[pkg/ccl/sqlccl/partition.go, line 335 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21049#-L1JEu53aRlgOyXMyWpI:-L1NSrRFBCnfv96dNMyk:beh70vk) ([raw file](https://github.com/cockroachdb/cockroach/blob/22356279539c7f6ddf0eae76bfe09ea08e38c1b5/pkg/ccl/sqlccl/partition.go#L335)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

In fact, I think this whole stanza can be much simplified!

```go
excludeExpr := tree.TypedExpr(tree.DBoolFalse)
for i := len(partValueExprs) - 1; i >= 0; i-- {
	nextExcludeExpr := tree.TypedExpr(tree.DBoolFalse)
	for _, v := range partValueExprs[i] {
		exprsByPartName[v.name] = tree.NewTypedAndExpr(v.expr, tree.NewTypedNotExpr(excludeExpr))
		nextExcludeExpr = tree.NewTypedOrExpr(nextExcludeExpr, v.expr)
	}
	excludeExpr = tree.NewTypedOrExpr(excludeExpr, nextExcludeExpr)
}
```
</blockquote></details>

I took this mostly as-is, modulo above comment

---

*[pkg/ccl/sqlccl/partition_test.go, line 976 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21049#-L1JFKLaHmYCxv-IXP4u:-L1NcMPjD4Onora3P6RC:b-i6u66v) ([raw file](https://github.com/cockroachdb/cockroach/blob/22356279539c7f6ddf0eae76bfe09ea08e38c1b5/pkg/ccl/sqlccl/partition_test.go#L976)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Can you add a test case for that TODO above that mentions the irrelevant branch?
</blockquote></details>

Done. Adding this and the two tuples in a partition made me step back and rethink the test a bit and it's much more interesting now!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21049)*

**Comment by benesch** [comment]
:lgtm_strong:

Food for thought: I think we could get some mileage by switching to an on-demand constraint generation strategy. Given a spec like `p33p44,p335p445,p33dp44d`, we could toss out `p335p445` and `p33dp44d` by not recursing into the `p33p44` partition—because we know that its subpartitions cannot possibly add to or remove from the parent constraint. Should reduce some of the burden on our underpowered optimizer. Definitely not in this PR though!

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/sqlccl/partition.go, line 306 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21049#-L1JFPOkwWJq1UMppANU:-L1NnqjELv06vX7QgAQk:b-rdxxsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/22356279539c7f6ddf0eae76bfe09ea08e38c1b5/pkg/ccl/sqlccl/partition.go#L306)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Done. I've also (hopefully) improved the comment
</blockquote></details>

Ahh, I get it now. Thanks!

---

*[pkg/ccl/sqlccl/partition.go, line 327 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21049#-L1JD9pqPj91KZB3nZr6:-L1NntKQbbNlWrvCYfk0:brqzya6) ([raw file](https://github.com/cockroachdb/cockroach/blob/22356279539c7f6ddf0eae76bfe09ea08e38c1b5/pkg/ccl/sqlccl/partition.go#L327)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Any partition with multiple values/tuples will hit it (`PARTITION BY LIST (a) (PARTITION b IN ((1), (2))`). Looks like there's no test case for it. Whoops
</blockquote></details>

Oh, of course! That makes perfect sense. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21049#-:-L1Npt0C3JIW3kVx0yAD:b-g5b5nz)*

**Comment by danhhz** [comment]
Oh, that's super smart. I'll do a fast follow. TFTR!

**Comment by danhhz** [comment]
https://github.com/cockroachdb/cockroach/pull/21066

**Pull request merged**
