### PR TITLE
kv/bulk: send ssts with lower admission control priority

### LINKED ISSUE #79264: bulk: AddSSTable should use lower admission priority
https://github.com/cockroachdb/cockroach/pull/79126

Jira issue: CRDB-14663

### PR DESCRIPTION
**Pull request by dt**
small refactor while I'm here since plumbing args to/from the kv.DB "helpers" has been a source of toil and merge conflicts lately.

Jira issue: CRDB-14737
Epic CRDB-2264

### CODE REVIEW

**Comment by dt** [comment]
first two commits are https://github.com/cockroachdb/cockroach/pull/79086, ignore them here.

**Review by erikgrinaker — APPROVED** [review]

**Comment by erikgrinaker** [comment]
>The detour through the kv.DB wrapper was just adding more plumbing, signatures, etc
to update to get an argument or return value through. Perhaps we should remove them
in a follow-up as this is the only non-test caller.

Agreed, I find the non-trivial `DB` helpers to be more of a hassle than they're worth. Should make it easy to construct and send requests instead.

**Comment by dt** [comment]
I'm a little wary about back-porting this so last minute, particularly given how much recent ingestion performance work we've been doing, so hopefully we can get it in asap so it has at least a few betas in which to bake.

**Comment by erikgrinaker** [comment]
>I'm a little wary about back-porting this so last minute, particularly given how much recent ingestion performance work we've been doing, so hopefully we can get it in asap so it has at least a few betas in which to bake.

I'm fine with merging this as-is.

**Comment by dt** [comment]
> I'm fine with merging this as-is.

👍  was just waiting on the open questions in #79086.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: for the admission control bits

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79126#-:-MzowgtqAO_R-8k8B_6s:byl9u6t)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @stevendanna)

**Comment by dt** [comment]
TFTRs!

bors r+

**Comment by irfansharif** [comment]
blathers backport 21.2

**Pull request merged**
