### PR TITLE
sql: add errorIfRows node

### LINKED ISSUE #37053: sql: implement errorIfRows planNode
The `errorIfRows` planNode should return an error if it sees any input rows at all. This helps enable optimizer-driven foreign key checks.

### PR DESCRIPTION
**Pull request by yuzefovich**
Add errorIfRows node that returns an error if it receives a row
from its input. It is needed for foreign keys checks implementation
with joins.

Fixes: #37053.

I'm not sure whether some of these additions are necessary or if something is missing. Also, I'm not sure whether it deserves a unit test.

Release note: None

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37101)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @justinj, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/error_if_rows.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37101#-LdGcwsUBw4Pzxhd8lO9:-LdGcwsUBw4Pzxhd8lOA:b8zk3xo) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7cc4031a6f4e844604efd81245bc45da005815e/pkg/sql/error_if_rows.go#L48)):*
> ```Go
> 	if ok {
> 		// TODO(yuzefovich): what should the error be here?
> 		return false, pgerror.Newf(pgerror.CodeForeignKeyViolationError, "foreign key violation")
> ```

I think you will need to have the node inspect the row to create the error. Look at `fk_existence_batch.go` and see how they do it. You will probably want this node to accept a function that it can use at runtime to turn the row into an error, or something like that.

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37101#-:-LdGhprL6MUSm6sGaS8X:b-g2a5fb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @justinj, and @RaduBerinde)

___
*[pkg/sql/error_if_rows.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37101#-LdGcwsUBw4Pzxhd8lO9:-LdGh-SV1ZdaF0riKxvV:b-2zx5v7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7cc4031a6f4e844604efd81245bc45da005815e/pkg/sql/error_if_rows.go#L48)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think you will need to have the node inspect the row to create the error. Look at `fk_existence_batch.go` and see how they do it. You will probably want this node to accept a function that it can use at runtime to turn the row into an error, or something like that.
</blockquote></details>

Yeah, we will want to parametrize the error message somehow (maybe the optimizer would pass down a string with %s for the values) . Sample messages from the `fk` logictest:

```
foreign key violation: value \[5\] not found in customer reviews@primary \[id\]
foreign key violation: values \[2\] in columns \[id\] referenced in table "review_stats"
```

We could also not worry about it for now and revisit later.

**Comment by yuzefovich** [comment]
@jordanlewis are you ok with merging this as is and modifying later as needed?

**Comment by jordanlewis** [comment]
Yes. LGTM.

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Pull request merged**
