### PR TITLE
sql: skip multiregional tests again

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
Unfortunately, it's still flaky:
https://github.com/cockroachdb/cockroach/pull/105346#issuecomment-1611879332

Informs: https://github.com/cockroachdb/cockroach/issues/98020

Release note: None

### CODE REVIEW

**Review by renatolabs — APPROVED** [review]

**Review by rafiss — COMMENTED** [review]
only the secondary region test is flaky now, right? or both?

**Comment by chengxiong-ruan** [comment]
@rafiss per @renatolabs [comment](https://github.com/cockroachdb/cockroach/pull/105346#issuecomment-1611879332), it's only `secondary_region`. I thought the two tests might be quite relevant so skipping them. But now I think let's skip the `secondary_region` one for now.

**Comment by renatolabs** [comment]
Friendly ping.

**Comment by chengxiong-ruan** [comment]
TFTR!
bors r+

**Pull request merged**
