### PR TITLE
*: bump twpayne/go-geom@1.3.5, geos to include POINT EMPTY fix

### LINKED ISSUE #53631: geo: geos WKT cannot handle POINT EMPTY inside of collections
**Describe the problem**

`st_astext()` is unable to handle empty points in geometry collections.

**To Reproduce**

CockroachDB:

```
> select st_astext('GEOMETRYCOLLECTION (POINT EMPTY)');
ERROR: st_astext(): geos error: IllegalArgumentException: Empty Points cannot be represented in WKB
```

PostGIS:

```
# select st_astext('GEOMETRYCOLLECTION (POINT EMPTY)');
            st_astext            
---------------------------------
 GEOMETRYCOLLECTION(POINT EMPTY)
(1 row)
```

**Environment:**
 - CockroachDB version: `master` at `8b91062f93`
 - Server OS: macOS
 - Client app: `cockroach demo`

CC @otan

### LINKED ISSUE #53632: geo: SpatialObjectToWKT() omits empty shapes in collections
**Describe the problem**

While implementing `ST_ForceCollection`, I have a test case which generates a geometry collection with an empty point. However, calling `geo.SpatialObjectToWKT` omits the empty point from the output.

**To Reproduce**

```go
func TestEmptyPointWKT(t *testing.T) {
	gc := geom.NewGeometryCollection().SetSRID(int(geopb.DefaultGeographySRID))
	gc.MustPush(geom.NewPointEmpty(geom.XY))
	g, err := geo.MakeGeographyFromGeomT(gc)
	require.NoError(t, err)
	wkt, err := geo.SpatialObjectToWKT(g.SpatialObject(), 0)
	require.NoError(t, err)
	require.EqualValues(t, "GEOMETRYCOLLECTION (POINT EMPTY)", wkt)
}
```

This yields a test failure:

```
Not equal: 
expected: string("GEOMETRYCOLLECTION (POINT EMPTY)")
actual  : geopb.WKT("GEOMETRYCOLLECTION EMPTY")
```

PostGIS can represent this just fine:

```
postgis=# select st_astext(st_forcecollection('POINT EMPTY'));
            st_astext            
---------------------------------
 GEOMETRYCOLLECTION(POINT EMPTY)
(1 row)
```

**Environment:**
 - CockroachDB version: `master` at `8b91062f93`
 - Server OS: macOS
 - Client app: `cockroach demo`

CC @otan

### PR DESCRIPTION
**Pull request by otan**
* Bumps twpayne/go-geom to resolve an issue with WKT encoding involving
  empty collection points.
* Bumps GEOS to handles POINT EMPTY correctly.

Resolves #53631.
Resolves #53632.

Release justification: low risk updates to new functionality

Release note: None

### CODE REVIEW

**Comment by otan** [comment]
cc @erikgrinaker thanks for your fixes! once this goes in, #53643 should be good to rebase on top of.

**Review by sumeerbhola — APPROVED** [review]
Can you point me to where the geos fix landed?
Is geos being updated using `go get -u` too?
And what about the other changes here -- are they just a side effect of updating geos and twpayne/go-geom? 

:lgtm: 

> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53647#-:-MG3NbR4Bplza680JEI8:b-4jdx1o)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Comment by otan** [comment]
>Can you point me to where the geos fix landed?
> Is geos being updated using go get -u too?

In here: https://github.com/cockroachdb/geos/
We maintain a submodule commit in c-deps/geos similar to our vendor / `c-deps/rocksdb` that contains currently two custom patches (a windows fix + a wkb fix)

> And what about the other changes here -- are they just a side effect of updating geos and twpayne/go-geom?

yep!

**Comment by otan** [comment]
tftr! 

bors r=sumeerbhola

**Comment by otan** [comment]
bors r=sumeerbhola

**Pull request merged**
