### PR TITLE
ui/next: fix bundling by explicitly listing files in tsconfig

### PR DESCRIPTION
**Pull request by tamird**
cc @maxlang

Closes #7371.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6839)

### CODE REVIEW

**Comment by maxlang** [comment]
I'll let @mrtracy have the final word on tsconfig since he's dealt with it the most.

Created a PR to address the fact that we keep including changes to the generated proto files https://github.com/cockroachdb/cockroach/pull/6843

**Comment by mrtracy** [comment]
This causes problems when writing tests in editors that check for errors.  You won't get automatic errors while writing test files, because they will not be part of the compilation (because the tsconfig has no notion of them).

<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> I'll let @mrtracy have the final word on tsconfig since he's dealt with it the most.
> 
> 
> 
> Created a PR to address the fact that we keep including changes to the generated proto files https://github.com/cockroachdb/cockroach/pull/6843
</details>


---

Review status: 0 of 21 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6839#-:-KIQtERsE86jL59Py0E6:-1649510224)*

**Comment by tamird** [comment]
Are you sure? I'm still getting errors in my editor in test files.

**Comment by mrtracy** [comment]
It breaks both Vim and VSCode. 

<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Are you sure? I'm still getting errors in my editor in test files.
</details>


---

Review status: 0 of 21 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6839#-:-KIUq0ctzgXXjVkZrdFr:1838310414)*

**Comment by mrtracy** [comment]
I believe an alternative fix is to ensure that the `/// <reference>` to typings is present in every file.

**Comment by tamird** [comment]
Yeah, that's true, but sucks :(

**Comment by maxlang** [comment]
What's the status of this PR?

**Comment by maxlang** [comment]
@tamird @mrtracy ?

**Comment by tamird** [comment]
We should sit down and talk about this since it's IDE specific. Some editors support the extra option `filesGlob` that might be useful here, but we should make sure it doesn't break anyone's workflow.

**Comment by mrtracy** [comment]
Apparently this is no longer an issue in vscode.  I have also stopped using vim, so this shouldn't be an issue for our main contributors anymore.

**Comment by maxlang** [comment]
I support getting this in, since bundling is broken for me locally.

**Comment by maxlang** [comment]
LGTM

**Comment by tamird** [comment]
OK, will do in a bit.

**Pull request merged**
