### PR TITLE
WIP on parallelizing locality optimized search

### PR DESCRIPTION
**Pull request by yuzefovich**
Addresses: #68557.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Thanks Yahor, this is very cool! Parallelizing the remote region scans and short-circuiting on a hit will be a big win.

However, I am a little concerned about parallelizing the remote region scans with the local region scan. We're trading off throughput for latency, and we need to be conscious of that and satisfied with the tradeoff. Are we? My concern is that even if we short-circuit, we still aren't saving remote regions from serving the lookup, we just stop waiting for the response. In other words, once we've sent off the Scan, our cancellation isn't going to "catch up to it". So what once was a point lookup in one region is now a point lookup in all regions. At the extreme, this means that all regions are involved in serving all queries, so each region now has to individually have sufficient capacity to serve the aggregate load of the entire cluster. This means that we don't scale horizontally as new regions are added anymore. So that's a large throughput hit, and in exchange, we gain a very minor latency win, because we expect the local lookup to be orders of magnitude faster than the remote lookups.

Of course, this was always the cost of a locality optimized search _local miss_, at least until we address https://github.com/cockroachdb/cockroach/issues/64872, but are we ok with this being the cost of a locality optimized search _hit_? If people are using locality optimizer search, it's because they have some reason to believe that there's locality of access in their workload, so I think it's important that we optimize for that case.

**Comment by yuzefovich** [comment]
Thanks for taking a look Nathan! You bring up a very valid point that I didn't really consider. What you're saying totally makes sense, and I think what we want to have is the following:
```
                     BatchFlowCoordinator
                              |
                           limitOp
                              |
                   serial unordered sync
                      |                 |
              local region scan    parallel unordered sync
                                     |               |
                                    remote regions scans
```
(which should already be the case on master, I need to double-check that).

Just to spell things out as how they are expected to work:
- if we have a local hit, then we don't perform any lookups in the remote regions; this is enforced by having a serial unordered sync with two arms where the first arm is the local region scan;
- if we have a local miss, then we go into the second arm of the serial unordered sync and perform all remote reads in parallel.

So the first commit should probably be removed, and we just want to optimize the draining part of the parallel unordered sync.

**Comment by yuzefovich** [comment]
> Do we need to do anything special to pass the limit down to the parallel unordered sync for the remote region scans so it knows to stop early? Or is that already taken care of?

No, I think the limit part should work without any modification. Once `limitOp` satisfies the limit, it'll return a zero-length batch, and then `BatchFlowCoordinator` will transition into the draining state.

However, I looked into this a bit more, and now I think it'll be a larger change. What I missed (or forgot about) is that currently all remote regions are scanned by a single `TableReader`, so the diagram on master is as follows:
```
                     BatchFlowCoordinator
                              |
                           limitOp
                              |
                     serial unordered sync
                      |                 |
              TableReader            TableReader
         (local region spans)   (remote regions spans)
```
So we would also need to place multiple table readers for each remote region on the same node with a parallel unordered sync. I don't think so far we had a precedent for this kind of ask.

Additionally, my concerns about using the context cancellation to speed up the draining process seem valid - namely, if the parallel unordered sync input is an inbox, cancelling the context will shutdown the remote flow, so it will not work as is in the general case. We might need to have a special case behavior for the case when the plan is fully local.

Now I'm no longer sure that we can get this easily (and cleanly) done for 21.2.

**Comment by rytaft** [comment]
Ah right, I also forgot that this results in a local plan.

> So we would also need to place multiple table readers for each remote region on the same node with a parallel unordered sync. I don't think so far we had a precedent for this kind of ask.

Instead of doing that, out of curiosity, would it possibly make sense to make this change at the kv layer? (cc @nvanbenschoten)

> Now I'm no longer sure that we can get this easily (and cleanly) done for 21.2.

Ok, makes sense. Thanks for investigating! This seems like something we should prioritize for the next release, but I agree it's probably not a good idea to force into 21.2 given the time that remains.

**Comment by rytaft** [comment]
> Instead of doing that, out of curiosity, would it possibly make sense to make this change at the kv layer? (cc @nvanbenschoten)

Or maybe this is a good use case for the new Streamer you're building, @yuzefovich?

**Comment by yuzefovich** [comment]
I just chatted with @michae2, and he pointed out that we could solve the inbox-outbox problem with the existing DrainRequest mechanism with some modifications to the outbox. So I think the remaining main question is to how to plan multiple TableReaders for the remote region scans.

> > Instead of doing that, out of curiosity, would it possibly make sense to make this change at the kv layer? (cc @nvanbenschoten)

> Or maybe this is a good use case for the new Streamer you're building, @yuzefovich?

Yeah, actually the Streamer eventually - hopefully - should be able to help here. However, it is beyond the scope of 21.2 release. I'll spend a bit more time looking into whether we can fit this into 21.2 time frame.

**Comment by rytaft** [comment]
Sounds good - thanks!

**Comment by yuzefovich** [comment]
Something that I didn't fully appreciate right away, just writing it down.

The `TableReader` itself has the capacity to parallelize the scans of its scans, and it is already doing so for the remote regions scans. The blockage will take place at the DistSender level because we will wait for every sub-batch request to be answered in order to assemble the full BatchResponse. Using the Streamer library would alleviate this limitations; similarly, creating separate TableReaders for each span will solve the problem too.

If we were to implement the Streamer and use it for the TableReader, no other changes would be necessary, but that definitely won't happen until 22.1. Placing multiple TableReaders for the remote region spans will require changes to the DistSQL physical planner as well as to the parallel unordered synchronizer to have eager draining. Making the parallel unordered sync as well as the outbox more eager during the draining part seems like a generally good thing to do too.

**Comment by electrum** [comment]
The current plan looks like
```
 • union all
  │ limit: 1
  │
  ├── • scan
  │     spans: local region
  │
  └── • scan
        spans: other regions
```

For our use case of buddy regions, it seems like we could solve this by changing the plan to
```
 • union all
  │ limit: 1
  │
  ├── • scan
  │     spans: local region
  │
  ├── • scan
  │     spans: nearest region
  │
  └── • scan
        spans: other regions
```
I assume the current plan works because `union all` is executed serially?

**Comment by yuzefovich** [comment]
@electrum yeah, that seems reasonable for your use case. However, I think the changes for it would only be in the optimizer land, so I'll let @rytaft consider this idea. To me it seems like we would need to introduce a concept of "buddy regions" and have some special logic around it; not sure how common this ask would be.

**Comment by rytaft** [comment]
Agreed that this would be a reasonable approach, but the optimizer is not currently smart enough to take the latency of remote regions into account when planning locality optimized search. We also don't yet have a concept of "buddy regions". I think these are both things we'd like to do, but they are non-trivial changes and probably not possible in the 21.2 timeframe.

**Comment by yuzefovich** [comment]
I think I figured out all of the rough edges for the general solution in #68679, so closing this PR.

**Pull request closed without merging**
