### PR TITLE
sql: support INSERT ... RETURNING

### LINKED ISSUE #4236: sql: support RETURNING
We need a way to get back the id of an inserted row with a default primary key function. Postgres uses RETURNING, and we should too.

### PR DESCRIPTION
**Pull request by madelynnblue**
Fixes #4236

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4277)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
This is pretty cool! One comment about the select_qvalue changes though.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4277#-:-KA7Er2kxw3X0fVsQo-N:-331681725)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/select_qvalue.go, line 133 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4277#-KA7CSnpdmaeip-j8Sfo:-KA7CSnpdmaeip-j8Sfp:-1016637874) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9a7b4519324c7c4c4d5560e2eae5e838d282b46/sql/select_qvalue.go#L133)):*
The select_qvalue implementation was designed to support multiple tables. That's why the pointer to tableInfo is stored in columnRef..  The plan is that `findColumn` will be able to resolve columns from any table in the "FROM" list.

I realize we need to generalize it but we should not go backward and restrict the entire thing to one table.  

We could separate the tableInfo and qval map fields of selectNode into a new type and have select_qvalues operate on that? (and in the future we can have this type include multiple tableInfos)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4277)*

**Comment by tamird** [comment]
How about `UPDATE ... RETURNING`? Do we want to attempt to have unified handling for the two?

---

Reviewed 5 of 8 files at r1.
Review status: 5 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4277#-:-KA7G7eVdPEDltDEMlRf:-1541385234)*

**Comment by petermattis** [comment]
Nice. We also will want to support `DELETE ... RETURNING` and `UPDATE ... RETURNING`. I'd do those in follow-on PRs.

---

Review status: 5 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/testdata/insert, line 327 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4277#-KA7i9-EQ2TT3sfR-YMJ:-KA7i9-EQ2TT3sfR-YMK:1556993406) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9a7b4519324c7c4c4d5560e2eae5e838d282b46/sql/testdata/insert#L327)):*
Postgres also supports `RETURNING a AS b` in order to name the output column. Would also be good to test returning the `rowid` column for a table without a primary key.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4277#-:-KA7inZhiwze1IGGTeWz:1986866643)*

**Comment by mjibson** [comment]
Review status: 5 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/select_qvalue.go, line 133 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4277#-KA7CSnpdmaeip-j8Sfo:-KABp_wAvw6sZjhA-mL3:65890394) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9a7b4519324c7c4c4d5560e2eae5e838d282b46/sql/select_qvalue.go#L133)):*
Changed to kind of do that. Does that address your concerns?

---

*[sql/testdata/insert, line 327 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4277#-KA7i9-EQ2TT3sfR-YMJ:-KABLMlDCLPa0DhbBOWx:-827283310) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9a7b4519324c7c4c4d5560e2eae5e838d282b46/sql/testdata/insert#L327)):*
Added a test for `RETURNING a AS b` (it already worked), as well as fixing support for when there is no `AS`.

How is it possible to test the rowid's value? It's random. I've added a test to make sure we can specify rowid in returning, but not verifying its value.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4277)*

**Comment by petermattis** [comment]
LGTM, though Radu should give the `qvalTable` stuff a look.

---

Review status: 5 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/testdata/insert, line 327 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4277#-KA7i9-EQ2TT3sfR-YMJ:-KABv9WiM8xvifORZWAa:1866652784) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9a7b4519324c7c4c4d5560e2eae5e838d282b46/sql/testdata/insert#L327)):*
You can test that the `rowid` value exists.  Or you can do something like `rowid != experimental_unique_int()`. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4277#-:-KABvhXj1S-H8UoXK78C:-200605683)*

**Comment by tschottdorf** [comment]
Reviewed 5 of 8 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4277)*

**Comment by RaduBerinde** [comment]
*[sql/select_qvalue.go, line 133 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4277#-KA7CSnpdmaeip-j8Sfo:-KAC0Q_mtyeAcA1hTpRQ:-141769012) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9a7b4519324c7c4c4d5560e2eae5e838d282b46/sql/select_qvalue.go#L133)):*
Yes, thanks a lot! The name won't make sense when it will contain multiple tables, but we can rename later (I don't have a good idea right now, maybe `qvalResolver`?).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4277)*

**Comment by mjibson** [comment]
Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/select_qvalue.go, line 133 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4277#-KA7CSnpdmaeip-j8Sfo:-KACBcml1PgnMm7nRrD_:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9a7b4519324c7c4c4d5560e2eae5e838d282b46/sql/select_qvalue.go#L133)):*
Done.

---

*[sql/testdata/insert, line 327 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4277#-KA7i9-EQ2TT3sfR-YMJ:-KACD2_i7ooC4PsjwQGT:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9a7b4519324c7c4c4d5560e2eae5e838d282b46/sql/testdata/insert#L327)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4277)*

**Comment by JackKrupansky** [comment]
On rowid validation in general, maybe check to see that node ID is correct, and that the shifted time is in the range between when the test started and the current time. And maybe insert multiple rows and assure the rowids are ordered as well as each being valid.

**Pull request merged**
