### PR TITLE
sql: fix db quals in EXPLAIN ANALYZE(DEBUG)

### PR DESCRIPTION
**Pull request by jordanlewis**
Fix two small issues with EXPLAIN ANALYZE (DEBUG):

```

    Remove database qualification from stats sql files so they can be
    injected without modification.

    Release note: None
```

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68016#-:-MfKLpNR483nf-2aGJxd:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/explain_bundle.go, line 675 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68016#-MfKL_d81xYdJzNvf2tP:-MfKL_d90iE-fFHrmy4L:b-zfr4q5) ([raw file](https://github.com/cockroachdb/cockroach/blob/27799cbf2996a9cdc77789019a657acf4c90862a/pkg/sql/explain_bundle.go#L675)):*
> ```Go
> 	tn.ExplicitCatalog = false
> 	fmt.Fprintf(w, "ALTER TABLE %s INJECT STATISTICS '%s';\n", tn.String(), stats)
> 	tn.ExplicitCatalog = true
> ```

Should this always be true? Would it be better to just reset to what it was before?

**Comment by michae2** [comment]
Ha, I think we saw the same thing in env.sql. I'm currently removing all newlines from all setting descriptions 😄

**Comment by jordanlewis** [comment]
Your solution is better, so I've changed this PR to just contain the qualification fixes.

**Pull request merged**
