### PR TITLE
server: Fix race in node.writeSummaries

### LINKED ISSUE #10653: : TestStatusSummaries failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/59693a140f93a4658174054884db891012ac0380

Stress build found a failed test:

```
I161112 07:40:37.209108 4148 gossip/gossip.go:237  [n?] initial resolvers: []
W161112 07:40:37.209136 4148 gossip/gossip.go:1055  [n?] no resolvers found; use --join to specify a connected node
W161112 07:40:37.211158 4148 server/status/runtime.go:116  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I161112 07:40:37.211366 4148 storage/engine/rocksdb.go:340  opening in memory rocksdb instance
I161112 07:40:37.211962 4148 server/config.go:443  1 storage engine initialized
I161112 07:40:37.213633 4148 server/node.go:421  [n?] store [n0,s0] not bootstrapped
I161112 07:40:37.218077 4249 storage/replica_proposal.go:328  [s1,r1/1:/M{in-ax}] new range lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 410815h40m46.217556177s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0s [physicalTime=2016-11-12 07:40:37.218043695 +0000 UTC]
I161112 07:40:37.218694 4148 util/stop/stopper.go:396  stop has been called, stopping or quiescing all running tasks
I161112 07:40:37.218774 4148 server/node.go:350  [n?] **** cluster 7dd3638a-62e3-44c8-9a16-1af396811638 has been created
I161112 07:40:37.218787 4148 server/node.go:351  [n?] **** add additional nodes by specifying --join=127.0.0.1:39897
I161112 07:40:37.219336 4148 base/node_id.go:62  [n1] NodeID set to 1
I161112 07:40:37.219630 4148 storage/store.go:1188  [n1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I161112 07:40:37.219644 4148 server/node.go:434  [n1] initialized store [n1,s1]: {Capacity:536870912 Available:536870912 RangeCount:0 LeaseCount:0}
I161112 07:40:37.219658 4148 server/node.go:319  [n1] node ID 1 initialized
I161112 07:40:37.219683 4148 gossip/gossip.go:280  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:39897" > attrs:<> locality:<> 
I161112 07:40:37.219769 4148 storage/stores.go:296  [n1] read 0 node addresses from persistent storage
I161112 07:40:37.219796 4148 server/node.go:564  [n1] connecting to gossip network to verify cluster ID...
I161112 07:40:37.219995 4148 server/node.go:584  [n1] node connected via gossip and verified as part of cluster "7dd3638a-62e3-44c8-9a16-1af396811638"
I161112 07:40:37.220017 4148 server/node.go:369  [n1] node=1: started with [[]=] engine(s) and attributes []
I161112 07:40:37.220033 4148 server/server.go:630  [n1] starting https server at 127.0.0.1:53845
I161112 07:40:37.220041 4148 server/server.go:631  [n1] starting grpc/postgres server at 127.0.0.1:39897
I161112 07:40:37.220048 4148 server/server.go:632  [n1] advertising CockroachDB node at 127.0.0.1:39897
I161112 07:40:37.226934 4222 storage/split_queue.go:103  [n1,split,s1,r1/1:/M{in-ax}] splitting at keys [/Table/11/0 /Table/12/0 /Table/13/0 /Table/14/0]
I161112 07:40:37.227890 4222 storage/replica_command.go:2361  [n1,split,s1,r1/1:/M{in-ax}] initiating a split of this range at key /Table/11 [r2]
I161112 07:40:37.232739 4222 storage/replica_command.go:2361  [n1,split,s1,r1/1:/{Min-Table/11}] initiating a split of this range at key /Table/12 [r3]
I161112 07:40:37.235927 4222 storage/replica_command.go:2361  [n1,split,s1,r1/1:/{Min-Table/11}] initiating a split of this range at key /Table/13 [r4]
I161112 07:40:37.239259 4222 storage/replica_command.go:2361  [n1,split,s1,r1/1:/{Min-Table/11}] initiating a split of this range at key /Table/14 [r5]
I161112 07:40:37.306773 4148 util/stop/stopper.go:396  stop has been called, stopping or quiescing all running tasks
I161112 07:40:37.306906 4167 http2_server.go:276  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:39897->127.0.0.1:53022: use of closed network connection
	node_test.go:433: 1: replicas does not match expected value.
		Expected 5.000000, Actual 1.000000
	node_test.go:433: 1: replicas.leaseholders does not match expected value.
		Expected 5.000000, Actual 0.000000
```

### PR DESCRIPTION
**Pull request by mrtracy**
Addresses a race condition in node.writeSummaries() which was causing sporadic
test failures in "TestStatusSummaries".

The specific failure occurs when writeSummaries is invoked multiple times
concurrently; this occurs primarily in TestStatusSummaries, which starts a test
server (which calls writeSummaries periodically from a background task) but also
synchronously forces summaries to be written at various points in the test.  The
race occurs because the actual generation of the summary occurs separately from
writing it to the database. If multiple invocations of writeSummaries are
running concurrently, an older status summary may overwrite a newer one.

The proposed fix is a mutex on the node object which will properly serialize
calls to writeSummaries, ensuring that an older summary cannot overwrite a newer
one.

Fixes #10653

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10709)

### CODE REVIEW

**Comment by mrtracy** [comment]
This is a proposed solution, which fixes the problems. A few other proposed solutions:

+ Introduce a test hook which disables the normal recording of StatusSummaries; this would be used by TestStatusSummaries, and would fix the problem.
+ Push the code for writing a summary to the database down into the status recorder object (it currently just returns the summary to the Node, which then writes it to the database). We would then use the recorder's existing mutex instead of this new mutex.
+ (suggested by Tamir) keep responsibility for writing summaries entirely within the "startWriteSummaries" loop, and add an additional condition to its `select` loop which can be signaled to immediately write another summary.

**Comment by petermattis** [comment]
> Introduce a test hook which disables the normal recording of StatusSummaries; this would be used by TestStatusSummaries, and would fix the problem.

This would be my preference. Or the existing patch using a mutex. But the testing knob feels safer.

**Comment by mrtracy** [comment]
After writing out all of the alternatives myself, I'm now convinced that the second option is best - pushing the responsibility for writing the summary down to the MetricsRecorder object. This allows us to use an existing mutex which seems to be a natural fit for this purpose.

I've updated the pull request accordingly.

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/server/status/recorder.go, line 276 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10709#-KWdoGgCKGWZD_96cNSE:-KWdoGgCKGWZD_96cNSF:b-fri0nq) ([raw file](https://github.com/cockroachdb/cockroach/blob/52a5b5a1c3c7ca536a64575b7b0c05f0a7864d24/pkg/server/status/recorder.go#L276)):*
> ```Go
> 		// will generate more versions than will easily fit into a range over
> 		// the course of a day.
> 		if err := db.PutInline(ctx, key, nodeStatus); err != nil {
> ```

You're now holding `mr.mu` for a significant period of time. I'm not familiar enough with this code to know if that is a problem.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10709)*

**Comment by mrtracy** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/server/status/recorder.go, line 276 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10709#-KWdoGgCKGWZD_96cNSE:-KWdq-I8raRpcO6k2Q01:bt38hmn) ([raw file](https://github.com/cockroachdb/cockroach/blob/52a5b5a1c3c7ca536a64575b7b0c05f0a7864d24/pkg/server/status/recorder.go#L276)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> You're now holding `mr.mu` for a significant period of time. I'm not familiar enough with this code to know if that is a problem.
</details>
Hmm, it might affect prometheus logging, which also holds this lock during a scrape.  We could create a mutex specifically for this operation, it only needs to be prevented from racing with itself.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10709)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/server/status/recorder.go, line 276 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10709#-KWdoGgCKGWZD_96cNSE:-KWds5fQ9284IGHHp8a6:b-wjs8l4) ([raw file](https://github.com/cockroachdb/cockroach/blob/52a5b5a1c3c7ca536a64575b7b0c05f0a7864d24/pkg/server/status/recorder.go#L276)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> Hmm, it might affect prometheus logging, which also holds this lock during a scrape.  We could create a mutex specifically for this operation, it only needs to be prevented from racing with itself.
</details>
Isn't that approach the same as what the previous version of this PR was doing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10709)*

**Comment by mrtracy** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/server/status/recorder.go, line 276 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10709#-KWdoGgCKGWZD_96cNSE:-KWdsFEcOo8Yd8n_Uxb0:b-bcg5ju) ([raw file](https://github.com/cockroachdb/cockroach/blob/52a5b5a1c3c7ca536a64575b7b0c05f0a7864d24/pkg/server/status/recorder.go#L276)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Isn't that approach the same as what the previous version of this PR was doing?
</details>
Yes, but that lock was on the Node object. I guess, even though it fixed the problem quickly, having a mutex to serialize access to a single method of Node seemed like a code smell to me. I can't even express why; it seems like the simplest way to allow correct concurrent access to that method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10709)*

**Comment by mrtracy** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/server/status/recorder.go, line 276 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10709#-KWdoGgCKGWZD_96cNSE:-KWdxbFcNzsJ67tyWadq:b-2xco80) ([raw file](https://github.com/cockroachdb/cockroach/blob/52a5b5a1c3c7ca536a64575b7b0c05f0a7864d24/pkg/server/status/recorder.go#L276)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> Yes, but that lock was on the Node object. I guess, even though it fixed the problem quickly, having a mutex to serialize access to a single method of Node seemed like a code smell to me. I can't even express why; it seems like the simplest way to allow correct concurrent access to that method.
</details>
I've given WriteStatusSummary its own mutex, along with an explanation of why (locking during a network round-trip).  It is located inside of the MetricsRecorder object, which has a reduced scope compared to the Node and thus I believe it is much safer to add a mutex here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10709)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/server/status/recorder.go, line 242 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10709#-KWdxau8WcqUtWYbSegK:-KWdxau8WcqUtWYbSegL:b-qec9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/52a5b5a1c3c7ca536a64575b7b0c05f0a7864d24/pkg/server/status/recorder.go#L242)):*
> ```Go
> 	defer mr.mu.Unlock()
> 
> 	if mr.mu.nodeRegistry == nil {
> ```

shouldn't this go away now?

---

*[pkg/server/status/recorder.go, line 259 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10709#-KWdxePHRRD3zbmFvCvh:-KWdxePHRRD3zbmFvCvi:b-987uj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/52a5b5a1c3c7ca536a64575b7b0c05f0a7864d24/pkg/server/status/recorder.go#L259)):*
> ```Go
> 	defer mr.mu.Unlock()
> 
> 	if mr.mu.nodeRegistry == nil {
> ```

this check should be in `generateStatusSummaryLocked`, and then that method can become `generateStatusSummay` and do its own locking, which should address @petermattis' concerns about holding the lock across RPCs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10709)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10709#-:-KWhbN7_xBM_ABJ71mbR:bnfp4nl)*

**Comment by mrtracy** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/server/status/recorder.go, line 242 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10709#-KWdxau8WcqUtWYbSegK:-KWiIj1tZ53hFNy8_wE2:bp0oal1) ([raw file](https://github.com/cockroachdb/cockroach/blob/52a5b5a1c3c7ca536a64575b7b0c05f0a7864d24/pkg/server/status/recorder.go#L242)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> shouldn't this go away now?
</details>
I'm assuming this is addressed with the new revision; I did modify the warning message to stop referring to the specific name of the function, so it makes sense whether called from GetStatusSummary() directly or from WriteStatusSummary().

---

*[pkg/server/status/recorder.go, line 259 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10709#-KWdxePHRRD3zbmFvCvh:-KWiIvGIFdaGfbzYsQBu:b-1si1m2) ([raw file](https://github.com/cockroachdb/cockroach/blob/52a5b5a1c3c7ca536a64575b7b0c05f0a7864d24/pkg/server/status/recorder.go#L259)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this check should be in `generateStatusSummaryLocked`, and then that method can become `generateStatusSummay` and do its own locking, which should address @petermattis' concerns about holding the lock across RPCs.
</details>
I think the current revision is essentially the same as your suggestion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10709)*

**Pull request merged**
