### PR TITLE
*: syncutil.WaitGroupWithError -> x/sync/errgroup

### PR DESCRIPTION
**Pull request by tamird**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14200)

### CODE REVIEW

**Comment by dt** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[glide.lock, line 182 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14200#-KfMy8kJHTOcTZuvv3hS:-KfMy8kJHTOcTZuvv3hT:bqqnkez) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb9d126a8a4b0e17d7d35b8673435baa4755bfb9/glide.lock#L182)):*
> ```
>   - query
> - name: github.com/google/pprof
>   version: a613757740614d4865db70ca9c80bc55cab3ab8f
> ```

this (and others) seem like unrelated changes?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14200)*

**Comment by tamird** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[glide.lock, line 182 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14200#-KfMy8kJHTOcTZuvv3hS:-KfMy_zU0yD2mjGLVJOR:b-mxx6jr) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb9d126a8a4b0e17d7d35b8673435baa4755bfb9/glide.lock#L182)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

this (and others) seem like unrelated changes?
</blockquote></details>

Yes, glide update. They're harmless (I audited).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14200)*

**Comment by dt** [comment]
Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/storageccl/import.go, line 68 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14200#-KfMzZO4xmpYbfgY6uRz:-KfMzZO4xmpYbfgY6uS-:b-na1lc9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7363a328fac76ff072cd61bef9c6dd2f9fc88745/pkg/ccl/storageccl/import.go#L68)):*
> ```Go
> 		go func(start, end roachpb.Key, repr []byte) {
> 			if err := db.WriteBatch(ctx, start, end, repr); err != nil {
> 				log.Errorf(ctx, "writebatch [%s,%s): %+v", start, end, err)
> ```

@danhhz do we want this log-line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14200)*

**Comment by danhhz** [comment]
The ccl stuff lgtm, but @andrei probably wants to look at the distsql ones.

I'm also confused about why these other deps changed. I remember @bdarnell saying in https://reviewable.io/reviews/cockroachdb/cockroach/14130#-Kf9LOEKWFWeiX421jaQ that we should only be changing them for a specific reason. Can you document that reason in the commit message and PR text, please?

---

Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/storageccl/import.go, line 68 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14200#-KfMzZO4xmpYbfgY6uRz:-KfNCjFQZhCpT1zx9n_u:b8uh2c0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7363a328fac76ff072cd61bef9c6dd2f9fc88745/pkg/ccl/storageccl/import.go#L68)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

@danhhz do we want this log-line?
</blockquote></details>

Yeah, @tamird, can we get this back as an error.Wrapf plz?

---

*[pkg/ccl/storageccl/import.go, line 53 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14200#-KfNBq7wzZeqShCswkno:-KfNBq7wzZeqShCswknp:b-qup1ua) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f8f573071cda9c73afa5dd89e8d199bf03c07e9/pkg/ccl/storageccl/import.go#L53)):*
> ```Go
> 	}
> 	b := batchBuilder{}
> 	g, wgCtx := errgroup.WithContext(ctx)
> ```

nit: why wg as the prefix?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14200#-:-KfNHFepUSIWTReN48z4:bu1sysd)*

**Comment by danhhz** [comment]
Whoops, wrong @andreimatei

**Comment by tamird** [comment]
@danhhz I interpreted that as referring to the pinned dependencies. We have a bunch of dependencies that we allow to float on "glide update", and those are the ones that are bumped here. I amended the commit message.

---

Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/ccl/storageccl/import.go, line 68 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14200#-KfMzZO4xmpYbfgY6uRz:-KfNKfUH8uK9BRBvw6GN:b-v2if5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7363a328fac76ff072cd61bef9c6dd2f9fc88745/pkg/ccl/storageccl/import.go#L68)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Yeah, @tamird, can we get this back as an error.Wrapf plz?
</blockquote></details>

You betcha. Done.

---

*[pkg/ccl/storageccl/import.go, line 53 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14200#-KfNBq7wzZeqShCswkno:-KfNJvBd5Jsm0xU7pFMU:b-mctk26) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f8f573071cda9c73afa5dd89e8d199bf03c07e9/pkg/ccl/storageccl/import.go#L53)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: why wg as the prefix?
</blockquote></details>

Wasn't thinking, but changed to `gCtx` throughout.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14200#-:-KfNLu0K8ItaFQXdCZdV:b-y1zafa)*

**Comment by bdarnell** [comment]
My intention in that comment was to freeze *all* dependencies (and I think that's what @petermattis meant in his comment in that thread). Even changes to linters can be harmful to productivity (see the merge skew incident this week). 

---

Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14200#-:-KfNMZUEYp509JhqoXWj:b-pdydxp)*

**Comment by tamird** [comment]
> Even changes to linters can be harmful to productivity (see the merge skew incident this week).

This strikes me as exactly the wrong conclusion; that linter bump caught a legitimate mistake. Are we trading correctness for productivity?

---

Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14200#-:-KfNO-l5_k2FS9sGcM4a:bihcj9m)*

**Comment by andreimatei** [comment]
mmm are we sure we like this package? It goes to one extreme of completely ignoring everything but the first error. I didn't say anything when Dan said he'll use it in one place, but I don't know if we want to encourage it too much and delete our thing. I'd rather change our version to go farther in the opposite direction - store all the inner errors.

I don't feel that strongly, though. If everybody else thinks I'm paranoid, I'll shut up. 

---

Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14200#-:-KfNMvLOCMn7NkPTUlw8:b4q5buv)*

**Comment by tamird** [comment]
If you want all the errors, use a channel?

---

Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14200#-:-KfNOMwWGl3knsVG2Dcw:b-9iamby)*

**Comment by danhhz** [comment]
Reviewed 6 of 13 files at r1, 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14200)*

**Comment by tamird** [comment]
@andreimatei FWIW it makes no sense for this thing to return more than just the first error because of the context interaction; it will cancel the context on the first error, so all the other errors will usually be "context cancelled", which isn't terribly useful.

**Comment by bdarnell** [comment]
> This strikes me as exactly the wrong conclusion; that linter bump caught a legitimate mistake. Are we trading correctness for productivity?

Freezing linter rules for a few months is hardly trading away correctness. And if the linter updates (or other dep updates) are worth it, then give them their own PR and make a case for it. Don't just upgrade every dependency whenever you touch any just because that's easy to do with glide. 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14200#-:-KfNPNGhojVs_ClAatx9:botg6a8)*

**Comment by andreimatei** [comment]
:lgtm: 

Fair enough point about explicitly using a channel for errors.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/internal/client/txn_test.go, line 952 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14200#-KfNSISrSng8qfQEH92E:-KfNSISrSng8qfQEH92F:blrtazq) ([raw file](https://github.com/cockroachdb/cockroach/blob/88e7ce9b5ea7dc84a3ac9a51562713039dbad924/pkg/internal/client/txn_test.go#L952)):*
> ```Go
> 			})
> 		}
> 		return errors.Cause(g.Wait())
> ```

this errors.Cause is no longer needed

---

*[pkg/sql/distsqlrun/outbox_test.go, line 278 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14200#-KfNRDbCeiarU2Fy1KwE:-KfNRDbCeiarU2Fy1KwF:b-n0el2k) ([raw file](https://github.com/cockroachdb/cockroach/blob/88e7ce9b5ea7dc84a3ac9a51562713039dbad924/pkg/sql/distsqlrun/outbox_test.go#L278)):*
> ```Go
> type InboundStreamNotification struct {
> 	stream DistSQL_FlowStreamServer
> 	wg     *sync.WaitGroup
> ```

Here `WaitgroupWithError` was nice; it allowed clients to control the error returned by `FlowStream`, even if not currently used.
You can't do that  with `errgroup.Group`, can you? Replace this with a `chan error` then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14200#-:-KfNT6-nODxtvM2S4tKE:bo0eq9n)*

**Comment by tamird** [comment]
> Freezing linter rules for a few months is hardly trading away correctness.

In the case of the merge skew we saw, that's exactly what it is. Take a look at the fix: https://github.com/cockroachdb/cockroach/pull/14158/files - there's clearly missing error handling code there.

I appreciate that you're taking a hard line on this, but we should also be mindful of the practicalities; static analysis tools have found meaningful bugs for us, so we should be updating them. Updating a single dependency is a serious pain with glide, but updating all not-otherwise-pinned dependencies is convenient, and is the entire reason that we distinguish between dependencies pinned in glide.yaml and dependencies that are not.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14200#-:-KfNTDm0Le6sGyeVBjUO:bebjq2w)*

**Comment by tamird** [comment]
Thanks for the reviews!

---

Review status: 11 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/internal/client/txn_test.go, line 952 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14200#-KfNSISrSng8qfQEH92E:-KfNVqsj1ebjbcnZWMrD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/88e7ce9b5ea7dc84a3ac9a51562713039dbad924/pkg/internal/client/txn_test.go#L952)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

this errors.Cause is no longer needed
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/outbox_test.go, line 278 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14200#-KfNRDbCeiarU2Fy1KwE:-KfNViAMpTlCP08Yt8R6:bx206h2) ([raw file](https://github.com/cockroachdb/cockroach/blob/88e7ce9b5ea7dc84a3ac9a51562713039dbad924/pkg/sql/distsqlrun/outbox_test.go#L278)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Here `WaitgroupWithError` was nice; it allowed clients to control the error returned by `FlowStream`, even if not currently used.
You can't do that  with `errgroup.Group`, can you? Replace this with a `chan error` then.
</blockquote></details>

Yeah, not possible here. Replaced.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14200#-:-KfNWoD6puO8L1Ld89Ft:b-hlc8bm)*

**Pull request merged**
