### PR TITLE
storage: remove re-evaluations of requests after a snapshot is applied

### PR DESCRIPTION
**Pull request by andreimatei**
See individual commits.

### CODE REVIEW

**Comment by andreimatei** [comment]
cc @spencerkimball - #28985 was assigned to you, but I didn't see a PR open and so I've taken it back as a Christmas present to myself. Hope you don't mind.

**Review by bdarnell — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33381)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by tbg — APPROVED** [review]
:lgtm: and thank you

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33381#-:-LUpD3nH4HdXYmdUYYAh:b-8y1qun)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 4823 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33381#-LUpBZbPC5pezcBrnBCz:-LUpBZbPC5pezcBrnBD-:bjqbzxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c9cddf1ca1d351970f54cf97fec31be48257ea1/pkg/storage/replica.go#L4823)):*
> ```Go
> 			// snapshot, so nobody removed p from r.mu.proposals). In this
> 			// ambiguous case, we return an ambiguous error.
> 			// NOTE: We used to perform a re-evaluation here in order to avoid the
> ```

nit: newline above this one
___
*[pkg/storage/replica.go, line 4828 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33381#-LUpBYi4-LYxWZo-tIXd:-LUpBYi527Gb9DFQ2nyy:b-spqjjh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c9cddf1ca1d351970f54cf97fec31be48257ea1/pkg/storage/replica.go#L4828)):*
> ```Go
> 			// error to reflect the ambiguity. This mechanism also proved very hard to
> 			// test and also is of questionable utility since snapshots are only
> 			// applied in the first place if the leaseholder is diverced from the Raft
> ```

divorced
___
*[pkg/storage/replica.go, line 4840 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33381#-LUpBd4cAZ1jwq0nS2gx:-LUpBd4cAZ1jwq0nS2gy:buujzan) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c9cddf1ca1d351970f54cf97fec31be48257ea1/pkg/storage/replica.go#L4840)):*
> ```Go
> 				p.finishApplication(proposalResult{Err: roachpb.NewError(
> 					roachpb.NewAmbiguousResultError(
> 						fmt.Sprintf("unknown status for command; " +
> ```

"unable to determine whether command was applied via snapshot"?
___
*[pkg/storage/replica.go, line 3061 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33381#-LUpCd7e3Rg8twGO_jL1:-LUpCd7e3Rg8twGO_jL2:bsgh1gq) ([raw file](https://github.com/cockroachdb/cockroach/blob/acea9a5e45f8f4f0bbc869f03cefe0119bd7f15c/pkg/storage/replica.go#L3061)):*
> ```Go
> 	for {
> 		br, pErr, retry := r.tryExecuteWriteBatch(ctx, ba)
> 		if retry == proposalIllegalLeaseIndex {
> ```

Not for this PR, but you could drop a TODO in my name to add a metric to the proposal count.
___
*[pkg/storage/replica.go, line 3094 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33381#-LUpCswQ8Re_OWeoiBQ2:-LUpCswQ8Re_OWeoiBQ3:bkqp32r) ([raw file](https://github.com/cockroachdb/cockroach/blob/acea9a5e45f8f4f0bbc869f03cefe0119bd7f15c/pkg/storage/replica.go#L3094)):*
> ```Go
> //   its result (which could be an error) is returned to the client.
> //
> // TODO(tschottdorf): take special care with "special" commands and their
> ```

Mind removing this vague TODO while you're here?

**Review by andreimatei — COMMENTED** [review]
TFTRs. I needed to do another small tweak to `processRaftCommand()`. PTAQuickL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33381#-:-LVK3K7N2ZE7ukJTCGc9:ba8pls3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/replica.go, line 4828 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33381#-LUpBYi4-LYxWZo-tIXd:-LVK2sPSDQ0EdBmyRCuH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c9cddf1ca1d351970f54cf97fec31be48257ea1/pkg/storage/replica.go#L4828)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

divorced
</blockquote></details>

Done.
___
*[pkg/storage/replica.go, line 4840 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33381#-LUpBd4cAZ1jwq0nS2gx:-LVK3CCf98znobNqkhuh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c9cddf1ca1d351970f54cf97fec31be48257ea1/pkg/storage/replica.go#L4840)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

"unable to determine whether command was applied via snapshot"?
</blockquote></details>

Done.
___
*[pkg/storage/replica.go, line 3061 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33381#-LUpCd7e3Rg8twGO_jL1:-LVK2ND63HGnlU_VhzA8:b-e3um3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/acea9a5e45f8f4f0bbc869f03cefe0119bd7f15c/pkg/storage/replica.go#L3061)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Not for this PR, but you could drop a TODO in my name to add a metric to the proposal count.
</blockquote></details>

done, with my name too
___
*[pkg/storage/replica.go, line 3094 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33381#-LUpCswQ8Re_OWeoiBQ2:-LVK2VRf4LFyFXJOySzS:bn1urt5) ([raw file](https://github.com/cockroachdb/cockroach/blob/acea9a5e45f8f4f0bbc869f03cefe0119bd7f15c/pkg/storage/replica.go#L3094)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Mind removing this vague TODO while you're here?
</blockquote></details>

done. This was just FUD, wasn't it? Something is preventing those writes, right?

**Review by tbg — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33381)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/replica.go, line 3094 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33381#-LUpCswQ8Re_OWeoiBQ2:-LVdRzmKBw0ngJ-DWkPz:b-sx0hg) ([raw file](https://github.com/cockroachdb/cockroach/blob/acea9a5e45f8f4f0bbc869f03cefe0119bd7f15c/pkg/storage/replica.go#L3094)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

done. This was just FUD, wasn't it? Something is preventing those writes, right?
</blockquote></details>

The comment might predate sanity that was applied since, but yeah, I don't know of obvious problems here.

Monster nit, but you write `reevaluations` earlier and `re-evaluations` now.

**Review by tbg — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33381)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by tbg — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33381#-:-LVdSYIA2Leg4bbyNeQu:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33381)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/replica.go, line 3094 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33381#-LUpCswQ8Re_OWeoiBQ2:-LW7YHKYCEtZFgbFulHt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/acea9a5e45f8f4f0bbc869f03cefe0119bd7f15c/pkg/storage/replica.go#L3094)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

The comment might predate sanity that was applied since, but yeah, I don't know of obvious problems here.

Monster nit, but you write `reevaluations` earlier and `re-evaluations` now.
</blockquote></details>

Done.

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33381#-:-LW7Z9g4E0JWb1PkSaos:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by andreimatei** [comment]
Build failure was #33683

bors r+

**Pull request merged**
