### PR TITLE
ui: JavaScript updates to address vulnerabilities

### PR DESCRIPTION
**Pull request by nathanstilwell**
Resolving vulnerabilities identified by Synk and npm. Specifically these,

- https://app.snyk.io/vuln/SNYK-JS-LODASH-450202
- https://app.snyk.io/vuln/npm:ua-parser-js:20171012
- https://app.snyk.io/vuln/npm:ua-parser-js:20180227
- https://www.npmjs.com/advisories/535

Release justification: Resolving JavaScript vulnerabilities.

Release note: Upgrading JavaScript dependencies

### CODE REVIEW

**Review by vilterp — APPROVED** [review]

**Comment by vilterp** [comment]
@bdarnell @andy-kimball should we just `bors r+` this?

**Review by bdarnell — APPROVED** [review]
> should we just bors r+ this?

Yes, but I think the CLA check needs to be passing first.

**Comment by nathanstilwell** [comment]
bors retry

**Comment by nathanstilwell** [comment]
bors retry

**Pull request merged**
