### PR TITLE
sql: support BINARY format in COPY

### PR DESCRIPTION
**Pull request by madelynnblue**

### CODE REVIEW

**Comment by mjibson** [comment]
TODO: add memory accounting when creating datums, use pgerrors.

**Review by arulajmani — CHANGES_REQUESTED** [review]
Looks good overall, mostly some minor comments. 

> Reviewed 4 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51890#-:-MDN8rA0Affs9lYNBx31:bt97ut8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @mjibson, and @solongordon)

___
*[pkg/sql/copy.go, line 234 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51890#-MDMwqImDimoaF8lG-mV:-MDMwqImDimoaF8lG-mW:bfv9c3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/25a5f520fc381f8ef1f3abbc10ca92ff6a579857/pkg/sql/copy.go#L234)):*
> ```Go
> // final: If set, buffered data is written even if the buffer is not full.
> func (c *copyMachine) processCopyData(
> 	ctx context.Context, data string, evalCtx *tree.EvalContext, final bool,
> ```

Can we remove evalCtx here as it's no longer used? 
___
*[pkg/sql/copy.go, line 258 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51890#-MDMw8g62q7pkhOyfNfg:-MDMw8g62q7pkhOyfNfh:b-j5t74i) ([raw file](https://github.com/cockroachdb/cockroach/blob/25a5f520fc381f8ef1f3abbc10ca92ff6a579857/pkg/sql/copy.go#L258)):*
> ```Go
> 	for c.buf.Len() > 0 {
> 		switch c.format {
> 		case tree.CopyFormatText:
> ```

Considering we'll have another format copy format (CSV) soon, can we pull the format specific row processing logic into individual functions?  
___
*[pkg/sql/copy.go, line 473 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51890#-MDNF4Uy0l82u5CCqN_4:-MDNF4Uy0l82u5CCqN_5:bea6zx6) ([raw file](https://github.com/cockroachdb/cockroach/blob/25a5f520fc381f8ef1f3abbc10ca92ff6a579857/pkg/sql/copy.go#L473)):*
> ```Go
> }
> 
> func (c *copyMachine) addRow(ctx context.Context, line []byte) error {
> ```

Maybe rename to `readTextTuple` for consistency as this seems the `FormatText` analogous function to `readBinaryTuple`? 
___
*[pkg/sql/copy.go, line 621 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51890#-MDMtQQe914JEF0dbav5:-MDMtQQe914JEF0dbav6:bpro1n0) ([raw file](https://github.com/cockroachdb/cockroach/blob/25a5f520fc381f8ef1f3abbc10ca92ff6a579857/pkg/sql/copy.go#L621)):*
> ```Go
> 
> const (
> 	formatText copyFormat = iota
> ```

I don't think you need this because you're using `tree.CopyFormatBinary` and `tree.CopyFormatText` above. 
___
*[pkg/sql/parser/sql.y, line 2531 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51890#-MDMjcyT1q8kSYjfwRuP:-MDMjcyT1q8kSYjfwRuQ:b2ngckr) ([raw file](https://github.com/cockroachdb/cockroach/blob/25a5f520fc381f8ef1f3abbc10ca92ff6a579857/pkg/sql/parser/sql.y#L2531)):*
> ```Yacc
>     $$.val = &tree.CopyOptions{Destination: $3.expr()}
>   }
> | BINARY
> ```

Should `TEXT` be an acceptable option here even though it is the default? 
___
*[pkg/sql/sem/tree/copy.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51890#-MDMZQaAE2SHC0Y5uo5p:-MDMZQaAE2SHC0Y5uo5q:biq8vxc) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d32eb217275104bc8f23975c3ed7fee15b9b724/pkg/sql/sem/tree/copy.go#L51)):*
> ```Go
> func (o *CopyOptions) Format(ctx *FmtCtx) {
> 	if o.Destination != nil {
> 		ctx.WriteString("destination=")
> ```

nit: Should this be "DESTINATION="? 
___
*[pkg/sql/sem/tree/copy.go, line 77 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51890#-MDMaCfhA939NUYx0f7l:-MDMaCfhA939NUYx0f7m:b-jzv7ns) ([raw file](https://github.com/cockroachdb/cockroach/blob/25a5f520fc381f8ef1f3abbc10ca92ff6a579857/pkg/sql/sem/tree/copy.go#L77)):*
> ```Go
> 
> func (o *CopyOptions) CombineWith(other *CopyOptions) error {
> 	if o.Destination != nil {
> ```

nit: Might be nice to structure this as `other.Destination` in the outer if and `o.Destionation` in the inner if so that we can get rid of the else condition. (here and below)

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51890)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @solongordon)

___
*[pkg/sql/copy.go, line 234 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51890#-MDMwqImDimoaF8lG-mV:-MD_lYRA3pQYLJJDrfYn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/25a5f520fc381f8ef1f3abbc10ca92ff6a579857/pkg/sql/copy.go#L234)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Can we remove evalCtx here as it's no longer used? 
</blockquote></details>

Done.
___
*[pkg/sql/copy.go, line 258 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51890#-MDMw8g62q7pkhOyfNfg:-MD_wAKvBfVtiJ1p3eem:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/25a5f520fc381f8ef1f3abbc10ca92ff6a579857/pkg/sql/copy.go#L258)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Considering we'll have another format copy format (CSV) soon, can we pull the format specific row processing logic into individual functions?  
</blockquote></details>

Done.
___
*[pkg/sql/copy.go, line 473 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51890#-MDNF4Uy0l82u5CCqN_4:-MD_lg1r7AKmn4Eqljgp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/25a5f520fc381f8ef1f3abbc10ca92ff6a579857/pkg/sql/copy.go#L473)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Maybe rename to `readTextTuple` for consistency as this seems the `FormatText` analogous function to `readBinaryTuple`? 
</blockquote></details>

Done.
___
*[pkg/sql/copy.go, line 621 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51890#-MDMtQQe914JEF0dbav5:-MD_loj-CJDml6V31gJw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/25a5f520fc381f8ef1f3abbc10ca92ff6a579857/pkg/sql/copy.go#L621)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I don't think you need this because you're using `tree.CopyFormatBinary` and `tree.CopyFormatText` above. 
</blockquote></details>

Done.
___
*[pkg/sql/parser/sql.y, line 2531 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51890#-MDMjcyT1q8kSYjfwRuP:-MD_m1Os6ZMSLGqHSPZd:bwuyf0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/25a5f520fc381f8ef1f3abbc10ca92ff6a579857/pkg/sql/parser/sql.y#L2531)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should `TEXT` be an acceptable option here even though it is the default? 
</blockquote></details>

TEXT isn't supported in the postgres grammar which is why I didn't include it here. Well, it is, but only in a grammar that we don't support (`WITH (format text)`).
___
*[pkg/sql/sem/tree/copy.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51890#-MDMZQaAE2SHC0Y5uo5p:-MD_r-0IBl6UKCausCB-:b-ol6a13) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d32eb217275104bc8f23975c3ed7fee15b9b724/pkg/sql/sem/tree/copy.go#L51)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: Should this be "DESTINATION="? 
</blockquote></details>

For backward compat needs to be lowercase. Added a comment.
___
*[pkg/sql/sem/tree/copy.go, line 77 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51890#-MDMaCfhA939NUYx0f7l:-MD_qLtHDj6YX4BWHIwn:b3ntoa3) ([raw file](https://github.com/cockroachdb/cockroach/blob/25a5f520fc381f8ef1f3abbc10ca92ff6a579857/pkg/sql/sem/tree/copy.go#L77)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: Might be nice to structure this as `other.Destination` in the outer if and `o.Destionation` in the inner if so that we can get rid of the else condition. (here and below)
</blockquote></details>

Nice! I copied this structure from BackupOptions but yeah this is better.

**Comment by mjibson** [comment]
RFAL

**Review by arulajmani — APPROVED** [review]
Thanks for the new changes, LGTM 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51890#-:-MEKxc1n6a5kd3hXYIjS:bgwnxvx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @solongordon)

**Pull request merged**
