### PR TITLE
sqlbase: remove deprecated fk migration fields

### PR DESCRIPTION
**Pull request by jordanlewis**
We're ready to remove (well, reserve) the legacy fk migration fields.

Release note: None

### CODE REVIEW

**Comment by rohany** [comment]
Do we have a migration that is going to upgrade this representation on all descriptors?

**Review by thoszhang — APPROVED** [review]
@rohany As I understand it, we're not getting rid of `MaybeUpgradeForeignKeyRepresentation` yet (and we can't until we can have long-running migrations with a version gate on completion, but we're slated to have that for 21.1). This PR just removes the legacy fields, which we're only writing, not reading, in 19.2. So we should be fine, right?

(If there is a problem, then we need to figure out how that's going to interact with supporting FKs with no index on the origin columns.)

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48256#-:-M6f_oQP0VSOgymrDN7D:bkcjw8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

**Comment by rohany** [comment]
Yeah I think you're right -- I misunderstood this.

**Comment by otan** [comment]
Are we still ready :o

**Comment by lucy-zhang** [comment]
This was done in #50591.

**Comment by otan** [comment]
I will close this to remove this from my pending reviews then :P

**Pull request closed without merging**
