### PR TITLE
util/log: add configuration option to set log file permissions

### LINKED ISSUE #68799: logging: make the permissions of new log files configurable
Discussed in https://github.com/cockroachdb/cockroach/issues/68736#issuecomment-897727091

We want the permissions of newly created log files to be customizable in the configuration (`file-defaults` + per-sink)

the key would probably be `file-permissions` or something similar

### PR DESCRIPTION
**Pull request by rauchenstein**
Previously, all created log files were created with "644" permissions;
readable by all, writable by the owner. This change adds a new
"file-permissions" key to the file log sink config, defaulting to 644.

Fixes #68799.

Release justification: This change is safe to release because it only
adds new configurability which defaults to the existing behavior.

Release note (cli change): Log file read and write permissions may now
be set via the new "file-permissions" key in the --log flag or
--log-config-file file.

### CODE REVIEW

**Review by knz — APPROVED** [review]
LGTM with nit on the accepted input yaml syntax. See comment below.

cc @catj-cockroach  - you'll want to process this in your other PR.

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69243#-:-Mi1qSpU6GFC9RUyiFct:b-zbe32h)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rauchenstein)

___
*[pkg/cli/log_flags_test.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69243#-Mi1pEHF7aE-yuAkxEhY:-Mi1pEHF7aE-yuAkxEhZ:b-bod3gx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7d8520731fbf4ab22374f05cf77352ce62cdd16/pkg/cli/log_flags_test.go#L89)):*
> ```Go
> 			`format: (?P<format>[^,]+), ` +
> 			`redactable: true\}`)
> 	telemetryFileCfgRe := regexp.MustCompile(
> ```

thanks :100: 
___
*[pkg/util/log/logconfig/config.go, line 756 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69243#-Mi1pZCbE01IURNrwZQ4:-Mi1pZCbE01IURNrwZQ5:b-h8d5ws) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7d8520731fbf4ab22374f05cf77352ce62cdd16/pkg/util/log/logconfig/config.go#L756)):*
> ```Go
> // MarshalYAML implements the yaml.Marshaler interface.
> func (x FilePermissions) MarshalYAML() (r interface{}, err error) {
> 	return fmt.Sprintf("%04o", x), nil
> ```

Maybe avoid emitting the `0` in front, with just `%03o`?
___
*[pkg/util/log/logconfig/config.go, line 772 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69243#-Mi1pVLVDAT6jN1PifeZ:-Mi1pVLVDAT6jN1Pife_:b58qafa) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7d8520731fbf4ab22374f05cf77352ce62cdd16/pkg/util/log/logconfig/config.go#L772)):*
> ```Go
> 	}
> 
> 	in = strings.TrimPrefix(in, "0o")
> ```

Why is this needed? I don't think we want to support the Go syntax.

**Review by rauchenstein — COMMENTED** [review]
The main changes are in config.go and file.go, making necessary connections through flags.go and file_sync_buffer.go and setting the new default in validate.go.  The rest is mostly fixing up tests.  I generalized some tests -- they'll still break when new config is added, but they should be easier to fix than going through each test case individually.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69243#-:-MhzRCW_09O65AVrvyoz:b-ceg6km)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rauchenstein)

___
*[pkg/util/log/logconfig/config.go, line 756 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69243#-Mi1pZCbE01IURNrwZQ4:-Mi2gKTx7RfHEgUwDDCc:b4yrfh1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7d8520731fbf4ab22374f05cf77352ce62cdd16/pkg/util/log/logconfig/config.go#L756)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Maybe avoid emitting the `0` in front, with just `%03o`?
</blockquote></details>

I'm trying to make this look as close to this being an octal YAML number as I can.  As implemented, when unmarshaling we accept "file-permissions: 0o644", "file-permissions: 0644", "file-permissions: 644", as well as each of those with the value in quotes.  The first two options look exactly like octal yaml numbers (0o644 being a deprecated style).  Accepting the third form is part of why we did this whole hack -- we didn't want a configuration of 644 to result in permissions 0420.  But interpreting non-octal as octal was our deviation from normal yaml.  (And the quotes were just because we had to make it really a string field to get this behavior.)

So even if we can't get around outputting it with quotes, and the leading zero is optional because we went out of our way to make it so, I think the leading-zero version is the closest to being standard yaml, so it's the format I preferred.
___
*[pkg/util/log/logconfig/config.go, line 772 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69243#-Mi1pVLVDAT6jN1PifeZ:-Mi2fLg81K55KAlJ605u:b-622ots) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7d8520731fbf4ab22374f05cf77352ce62cdd16/pkg/util/log/logconfig/config.go#L772)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Why is this needed? I don't think we want to support the Go syntax.
</blockquote></details>

Our yaml library accepts 0o644 and 0644 as octal numbers (the "0o" prefix was YAML1.1; leading zero is 1.2 and later).  I wanted to match its behavior with the exception of accepting just 644 as that same value instead interpreting it in decimal.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69243)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rauchenstein)

___
*[pkg/util/log/logconfig/config.go, line 756 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69243#-Mi1pZCbE01IURNrwZQ4:-Mi2muJkB4XZB0x0EKMM:b35vz2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7d8520731fbf4ab22374f05cf77352ce62cdd16/pkg/util/log/logconfig/config.go#L756)):*
<details><summary><i>Previously, rauchenstein wrote…</i></summary><blockquote>

I'm trying to make this look as close to this being an octal YAML number as I can.  As implemented, when unmarshaling we accept "file-permissions: 0o644", "file-permissions: 0644", "file-permissions: 644", as well as each of those with the value in quotes.  The first two options look exactly like octal yaml numbers (0o644 being a deprecated style).  Accepting the third form is part of why we did this whole hack -- we didn't want a configuration of 644 to result in permissions 0420.  But interpreting non-octal as octal was our deviation from normal yaml.  (And the quotes were just because we had to make it really a string field to get this behavior.)

So even if we can't get around outputting it with quotes, and the leading zero is optional because we went out of our way to make it so, I think the leading-zero version is the closest to being standard yaml, so it's the format I preferred.
</blockquote></details>

ok can you point me to the unit tests in this package that illustrate all the supported formats?
___
*[pkg/util/log/logconfig/config.go, line 772 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69243#-Mi1pVLVDAT6jN1PifeZ:-Mi2mzTp1BLYtlsmmPL_:bftg0u0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7d8520731fbf4ab22374f05cf77352ce62cdd16/pkg/util/log/logconfig/config.go#L772)):*
<details><summary><i>Previously, rauchenstein wrote…</i></summary><blockquote>

Our yaml library accepts 0o644 and 0644 as octal numbers (the "0o" prefix was YAML1.1; leading zero is 1.2 and later).  I wanted to match its behavior with the exception of accepting just 644 as that same value instead interpreting it in decimal.
</blockquote></details>

ok now I understand. See my other comment about unit tests. I'll also want to see unit test that demonstrate invalid input and which error is reported.

**Review by rauchenstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69243)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rauchenstein)

___
*[pkg/util/log/logconfig/config.go, line 756 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69243#-Mi1pZCbE01IURNrwZQ4:-Mi34zze0oW9bjgsTUZP:bu3hfdv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7d8520731fbf4ab22374f05cf77352ce62cdd16/pkg/util/log/logconfig/config.go#L756)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ok can you point me to the unit tests in this package that illustrate all the supported formats?
</blockquote></details>

Added in datadriven test "yaml".

**Review by knz — APPROVED** [review]
Nice thanks 💯

**Comment by rauchenstein** [comment]
bors r=knz

**Pull request merged**
