### PR TITLE
storageccl: avoid copying to/from tmpfile for local files

### PR DESCRIPTION
**Pull request by dt**
local files can just be read/written directly in the target location (using tmp suffix+rename to write), avoiding the O(size) copy.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14399)

### CODE REVIEW

**Comment by benesch** [comment]
This special casing is unfortunate, but I imagine it was better than the duplicated code you just refactored! I'm going to hold off and let @danhhz give the LGTM, though, since I don't have quite enough context.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ccl/storageccl/export_storage.go, line 560 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14399#-KgHmt0HrWRoleCqqYTN:-KgHmt0IOt5S8qL-jaOt:b2y0hlw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae639cccc12c265b02c5890b3b165ca29bc85d64/pkg/ccl/storageccl/export_storage.go#L560)):*
> ```Go
> 	if loc, ok := store.(*localFileStorage); ok {
> 		tmpPrefix = loc.base
> 		if err := os.MkdirAll(tmpPrefix, 0755); err != nil {
> ```

I know this behavior already exists elsewhere in the backup code path, but `MkdirAll` seems pretty unusual. I feel like most commands will bail out when the directory doesn't exist; otherwise it's easy to fat finger the first component of the path and end up with a massive garbage directory tree. Is it for consistency with blob storages, where paths aren't really a hierarchy but a flat keyspace?

Anyway, just something that's been on my mind.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14399#-:-KgHlz1sDk3dNqNrumEN:b-ij0n21)*

**Comment by dt** [comment]
We could have a alternate `FileWriter` impl for local files, but I was trying to avoid going back down the road layers of subtyping and (overlapping) implementations.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ccl/storageccl/export_storage.go, line 560 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14399#-KgHmt0HrWRoleCqqYTN:-KgK4XwONBTCNUgW0GF7:b-zbktm7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae639cccc12c265b02c5890b3b165ca29bc85d64/pkg/ccl/storageccl/export_storage.go#L560)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I know this behavior already exists elsewhere in the backup code path, but `MkdirAll` seems pretty unusual. I feel like most commands will bail out when the directory doesn't exist; otherwise it's easy to fat finger the first component of the path and end up with a massive garbage directory tree. Is it for consistency with blob storages, where paths aren't really a hierarchy but a flat keyspace?

Anyway, just something that's been on my mind.
</blockquote></details>

Eh, requiring operators to manually make all ancestors to run "backup .. to /mnt/backups/2017/03/28` or similar in a cron could get annoying, particularly when the cloud stores would be fine with that use case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14399#-:-KgK4Za-KWaXjKj5hjYt:bnrawc7)*

**Comment by danhhz** [comment]
having a second ExportFileWriter implementation and returning either it or tmpWriter from MakeExportFileTmpWriter (which would be renamed MakeExportFileWriter) seems pretty clean to me. can you expand on the downsides you're alluding to?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14399#-:-KgKmbIeUNYFeiaQuPXt:b-zfbb2s)*

**Comment by benesch** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ccl/storageccl/export_storage.go, line 560 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14399#-KgHmt0HrWRoleCqqYTN:-KgK_y3JvGGlAdmGVgnj:b-yfiwsa) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae639cccc12c265b02c5890b3b165ca29bc85d64/pkg/ccl/storageccl/export_storage.go#L560)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Eh, requiring operators to manually make all ancestors to run "backup .. to /mnt/backups/2017/03/28` or similar in a cron could get annoying, particularly when the cloud stores would be fine with that use case.
</blockquote></details>

Yeah, I guess "just run `mkdir -p $BACKUP_DIR`" is a harder argument to support when you might only have a SQL terminal. Fair enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14399)*

**Comment by dt** [comment]
the downside in my mind was that only Finish() has a different impl, so anything other than composition would be very duplicative, and for composition, the constructor needs to be almost entirely duplicated (or have two special-cases -- one to setup the prefix and one to return the wrapped impl).

after discussion in person, convinced that that the duplicated constructor is OK, so switched to that.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14399#-:-KgL24yd0jZTOfq5u4NN:b-1zjvtc)*

**Comment by danhhz** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14399#-:-KgL39fB4eZOxXwNJpKu:bnfp4nl)*

**Pull request merged**
