### PR TITLE
plpgsql: add support for INTO STRICT option

### LINKED ISSUE #115297: plpgsql: support handling NO DATA FOUND exception
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Jira issue: CRDB-33965
Epic: CRDB-34165

### PR DESCRIPTION
**Pull request by DrewKimball**
#### logictest: move plpgsql SELECT/RETURNING INTO tests to new file

This commit is test-only refactor that moves the tests for SELECT
and RETURNING INTO PL/pgSQL syntax to their own file.

Epic: None

Release note: None

#### plpgsql: add support for INTO STRICT syntax

This commit adds support for `SELECT INTO STRICT` and
`RETURNING INTO STRICT` for SQL statements within a PL/pgSQL routine.
This option causes the routine to error when the SQL statement doesn't
return exactly one row. This is handled via a `ScalarGroupBy` to compute
the row count, followed by a call to `crdb_internal.plpgsql_raise` if
necessary to throw the error.

Fixes #115297

Release note (sql change): It is now possible to use the `STRICT` option
with `SELECT ... INTO` and `RETURNING INTO` in order to enforce that the
SQL statement returns exactly one row.

#### sql: add setting to make PL/pgSQL INTO strict by default

This commit adds a new session setting, `plpgsql_use_strict_into`, that
causes PL/pgSQL `SELECT ... INTO` and `RETURNING INTO` syntax to behave
as if the `STRICT` option was specified. This causes the SQL statement
to result in an error if it doesn't return exactly one row. This is
useful for applications migrating from oracle, since it has this "strict"
behavior by default.

Informs #115297

Release note (sql change): Added a setting `plpgsql_use_strict_into`,
which causes PL/pgSQL `SELECT ... INTO` and `RETURNING INTO` to require
exactly one row from the SQL statement, similar to oracle behavior.

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
Nice! :lgtm:

> Reviewed 19 of 19 files at r1, 2 of 2 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120486#-:-Nsy81XKE7mdmTjckiNz:be8rotp)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`-- commits` line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/120486#-Nsy6sm16TREIrQxuqbY):*
For my own edification, how do you opt out of STRICT default behavior in Oracle? Via a similar setting that disables "strict by default"?
___
*[`pkg/sql/vars.go` line 3243 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/120486#-Nsy7CdcAcMN3y7lWYcp:-Nsy7CdcAcMN3y7lWYcq:bnuz274) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bc02a0c6106c8362406fda5aeed0de94a817893/pkg/sql/vars.go#L3243)):*
> ```Go
> 			return nil
> 		},
> 		GlobalDefault: globalFalse,
> ```

nit: should we introduce a cluster setting too?
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 1014 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120486#-Nsy4snYENawZwUAXYoE:-Nsy4snYENawZwUAXYoF:bhh2hgf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c58dd9b01865e3e59ab56e9e7154b118e5f3a22/pkg/sql/opt/optbuilder/plpgsql.go#L1014)):*
> ```Go
> }
> 
> // buildPLpgSQLRaise builds a Project expression which calls the implements the
> ```

nit: "which calls the implements ..."
___
*[`pkg/ccl/logictestccl/testdata/logic_test/plpgsql_into` line 398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120486#-Nsy7hH23-cdFjhwCLnm:-Nsy7hH23-cdFjhwCLnn:bzdm4fu) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c58dd9b01865e3e59ab56e9e7154b118e5f3a22/pkg/ccl/logictestccl/testdata/logic_test/plpgsql_into#L398)):*
> ```
> 
> query II rowsort
> SELECT * FROM xy;
> ```

nit: might be a bit less verbose to use `SELECT count(*) FROM xy;` or `SELECT count(*) == 8 FROM xy;` since we only care whether another row was inserted or not.

**Review by DrewKimball — COMMENTED** [review]
TFYR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120486#-:-NsyRbgX0FoTJAnuocaK:b-814cj3)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[`-- commits` line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/120486#-Nsy6sm16TREIrQxuqbY):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

For my own edification, how do you opt out of STRICT default behavior in Oracle? Via a similar setting that disables "strict by default"?
</blockquote></details>

The docs claim this behavior is "by default", but I haven't been able to find a way to do that. See the "Usage Notes" section in the [docs](https://docs.oracle.com/cd/B13789_01/appdev.101/b10807/13_elems045.htm). I guess maybe you could use `LIMIT 1` plus an exception handler that catches `NO_DATA_FOUND` and sets variables to NULL?
___
*[`pkg/sql/vars.go` line 3243 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/120486#-Nsy7CdcAcMN3y7lWYcp:-NsyQG2f41kYZqLKpDtu:b-4zzlnc) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bc02a0c6106c8362406fda5aeed0de94a817893/pkg/sql/vars.go#L3243)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: should we introduce a cluster setting too?
</blockquote></details>

I think it's probably fine to leave as-is, since the default can be set for a user (right?). I'm open to convincing otherwise, though.
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 1014 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120486#-Nsy4snYENawZwUAXYoE:-NsyQfGH1lmREi12ncpX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c58dd9b01865e3e59ab56e9e7154b118e5f3a22/pkg/sql/opt/optbuilder/plpgsql.go#L1014)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: "which calls the implements ..."
</blockquote></details>

Done.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/plpgsql_into` line 398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120486#-Nsy7hH23-cdFjhwCLnm:-NsyR_r_7qyS0J_To1Ee:b-fznogt) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c58dd9b01865e3e59ab56e9e7154b118e5f3a22/pkg/ccl/logictestccl/testdata/logic_test/plpgsql_into#L398)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: might be a bit less verbose to use `SELECT count(*) FROM xy;` or `SELECT count(*) == 8 FROM xy;` since we only care whether another row was inserted or not.
</blockquote></details>

Good idea, done.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r4, 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120486#-:-NsyWxgf04rtIPMN2sT4:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/vars.go` line 3243 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/120486#-Nsy7CdcAcMN3y7lWYcp:-NsyWanIEG7g_jjUptcs:b-u2jq2z) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bc02a0c6106c8362406fda5aeed0de94a817893/pkg/sql/vars.go#L3243)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I think it's probably fine to leave as-is, since the default can be set for a user (right?). I'm open to convincing otherwise, though.
</blockquote></details>

Yeah, sgtm.

**Review by mgartner — COMMENTED** [review]
Nicely done!!! 
:lgtm:

> Reviewed 1 of 19 files at r1, 27 of 27 files at r7, 2 of 2 files at r8, 10 of 10 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120486#-:-Nt2cw2Q5Ot-qWN0sl2I:b-i6d7wu)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
