### PR TITLE
sql/schemachanger: Enhanced debugging for long-running schema changes

### LINKED ISSUE #124075: schema: Improve visibility into long running schema changes
We lack visibility into long running schema changes. Investigating why a schema change is slow often involves sifting through logs to piece together the clues. To address this, we propose developing new debug tools similar to statement bundles to gather additional details on schema jobs. Leveraging existing job bundle tooling, we can extend its capabilities to output more information specifically for schema jobs, enhancing observability into schema changes.

There is some ambiguity here in terms of what observability will help here. As a starting point, we should look at what information is collected through job bundles and determine how to hook into that to add schema specific information.

Jira issue: CRDB-38686

Epic CRDB-38033

### PR DESCRIPTION
**Pull request by spilchen**
This improves debugging of long-running schema changes by leveraging enhancements in the job infrastructure.

### Retain Trace Events
Trace events are now retained and persisted after the schema change, including lower-level stats from the KV layer. This helps us understand where time is being spent. To achieve this, I implemented the `TraceableJob` interface for `newSchemaChangeResumer`.

### Collect Timing Stats 
We gather statistics on the time spent in `WaitForOneVersion` and `WaitForNoVersion` and include these stats in the retained trace events for review after the schema change. To include these stats in trace spans, I implemented the `tracing.Structured` interface, which happens automatically for protobuf messages. The new stats are added in `lease.proto`.

The stats track the number of retries, elapsed time, the number of leases we are waiting on, the number of distinct nodes we are waiting on, and one node ID that we are waiting on. These last three stats are useful for long waits as we periodically dump the stats.

During a schema change, we may wait multiple times. We do not aggregate the stats, as this proved tricky and is left as a follow-on item if needed.

### Pretty Print Current Plan
We provide a formatted output of the current running phase plan, similar to `EXPLAIN (DDL)`. This can be requested through the job profiler in the DBConsole (under 'Jobs -> Advanced Debugging -> Request Execution Details'). This will clarify the status field (e.g., PostCommitPhase stage 2 of 7 with 1 BackfillType op pending) by showing the stages within the phase.

The file will appear with a name like ‘explain-phase.20240612_135233.70.txt’ in the `job_info` table.

I compute the explain output optimistically, rather than on demand, to avoid the complexity of storing the `scplan.Plan` struct. It seemed easiest to store the explain output and keep the `scplan.Plan` struct local.

Epic: CRDB-38033
Closes: #124075
Release note: None

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
this is looking good! overall my comments are pretty minor.

i think we should try to determine if we can backport these changes without too much risk from messy merge conflicts.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125559#-:-O-IPTcJ6xYX-ONnHJPL:bc7yle0)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/sql/catalog/descpb/lease.proto` line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125559#-O-IJfARDFnII4EownNw:-O-IJfARDFnII4EownNx:bo1z7v3) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc9e727830d66732b433d5bca87e4f99419b35b7/pkg/sql/catalog/descpb/lease.proto#L21)):*
> ```proto
> message WaitStats {
>   // Number of retry attempts made
>   int32 numRetries = 1;
> ```

super nit: the convention for fields in proto files is to use snake case
___
*[`pkg/sql/catalog/lease/count.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125559#-O-IK5d_EWLOgPGfcwqj:-O-IK5d_EWLOgPGfcwqk:bilso4e) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc9e727830d66732b433d5bca87e4f99419b35b7/pkg/sql/catalog/lease/count.go#L38)):*
> ```Go
> 
> type countDetail struct {
> 	// The number of unexpired leases
> ```

nit: a convention with field comments is to start the first sentence with the name of the field, like:
```
// count is the number of unexpired leases
```

(same for the below fields)
___
*[`pkg/sql/catalog/lease/lease.go` line 1871 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125559#-O-ILfIm79Cw6qWShovo:-O-ILfIm79Cw6qWShovp:b-vgo0q5) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc9e727830d66732b433d5bca87e4f99419b35b7/pkg/sql/catalog/lease/lease.go#L1871)):*
> ```Go
> 	ws        descpb.WaitStats
> 	startTime time.Time
> 	recSp     *tracing.Span // Set only if recording events in the span
> ```

super nit: i think `recSp` could use a more descriptive name. perhaps `recSpan` or just `span`?
___
*[`pkg/sql/schemachanger/scdeps/run_deps.go` line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125559#-O-IMttY6E4iYOiLHRyS:-O-IMttY6E4iYOiLHRyT:bbiln5) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc9e727830d66732b433d5bca87e4f99419b35b7/pkg/sql/schemachanger/scdeps/run_deps.go#L99)):*
> ```Go
> 	sessionData  *sessiondata.SessionData
> 
> 	mu struct {
> ```

just curious, do you know if the mutex is needed here? 
___
*[`pkg/sql/schemachanger/scjob/job.go` line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125559#-O-IMVZZ9lGfwXpyV4fp:-O-IMVZZ9lGfwXpyV4fq:baxvcmx) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc9e727830d66732b433d5bca87e4f99419b35b7/pkg/sql/schemachanger/scjob/job.go#L46)):*
> ```Go
> 	rollbackCause error
> }
> ```

nit: to make sure we keep implementing the TraceableJob interface it would be useful to add a line such as:
```
var _ TraceableJob = (*newSchemaChangeResumer)(nil)
```

**Review by spilchen — COMMENTED** [review]
Thanks for taking a look. I addressed your comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125559#-:-O-MBSgHBHu166BY50l-:b-591sb0)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @spilchen)

___
*[`pkg/sql/catalog/descpb/lease.proto` line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125559#-O-IJfARDFnII4EownNw:-O-LvzSVDEvLZ1TXNi4O:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc9e727830d66732b433d5bca87e4f99419b35b7/pkg/sql/catalog/descpb/lease.proto#L21)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

super nit: the convention for fields in proto files is to use snake case
</blockquote></details>

Done.
___
*[`pkg/sql/catalog/lease/count.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125559#-O-IK5d_EWLOgPGfcwqj:-O-Lw0xv1oeRz6gRepWf:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc9e727830d66732b433d5bca87e4f99419b35b7/pkg/sql/catalog/lease/count.go#L38)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: a convention with field comments is to start the first sentence with the name of the field, like:
```
// count is the number of unexpired leases
```

(same for the below fields)
</blockquote></details>

Done
___
*[`pkg/sql/catalog/lease/lease.go` line 1871 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125559#-O-ILfIm79Cw6qWShovo:-O-Lw57Z60pdJRLML2CC:b-whlesr) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc9e727830d66732b433d5bca87e4f99419b35b7/pkg/sql/catalog/lease/lease.go#L1871)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

super nit: i think `recSp` could use a more descriptive name. perhaps `recSpan` or just `span`?
</blockquote></details>

I like `recSpan`.
___
*[`pkg/sql/schemachanger/scdeps/run_deps.go` line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125559#-O-IMttY6E4iYOiLHRyS:-O-LxXdo1buMof72QiNK:brv5rzz) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc9e727830d66732b433d5bca87e4f99419b35b7/pkg/sql/schemachanger/scdeps/run_deps.go#L99)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

just curious, do you know if the mutex is needed here?
</blockquote></details>

I think we need it. The `explainOutput` can be read/write at the same time. Even though the strings themselves are immutable, the assignment doesn't seem to have an atomic guarantee. I found this thread, which seems to confirm assignment isn't atomic: https://groups.google.com/g/golang-nuts/c/UWJlS8mPTlM?pli=1
___
*[`pkg/sql/schemachanger/scjob/job.go` line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125559#-O-IMVZZ9lGfwXpyV4fp:-O-LwQFG10XJiQ1p9BtO:bj8lfod) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc9e727830d66732b433d5bca87e4f99419b35b7/pkg/sql/schemachanger/scjob/job.go#L46)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: to make sure we keep implementing the TraceableJob interface it would be useful to add a line such as:
```
var _ TraceableJob = (*newSchemaChangeResumer)(nil)
```
</blockquote></details>

Ah ok. I was wondering what these variables did. Makes sense now.

**Review by fqazi — COMMENTED** [review]
Just some minor nits from me

> Reviewed 9 of 13 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125559#-:-O-MF57r4D3wz8LouXSH:b6k4qfk)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @spilchen)

___
*[`pkg/sql/catalog/lease/count.go` line 322 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125559#-O-MDUmM4SlD3HzAEk7h:-O-MDUmM4SlD3HzAEk7i:b-a77j5c) ([raw file](https://github.com/cockroachdb/cockroach/blob/fac52238351b64c4d055620e2fad4e24db87db2f/pkg/sql/catalog/lease/count.go#L322)):*
> ```Go
> 	// The system.lease table went through some column renames in past versions.
> 	// Pick the correct version based on the columns used in WHERE clause.
> 	if strings.Contains(whereClause, "desc_id") {
> ```

Nit: I think the other option is to push a boolean down rom the callers, but I'm not sure if that would be cleaner. I'll leave it to you.
___
*[`pkg/sql/schemachanger/scjob/job.go` line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125559#-O-MEf1nA8-sCAc9Yd_s:-O-MEf1nA8-sCAc9Yd_t:b-uaihow) ([raw file](https://github.com/cockroachdb/cockroach/blob/fac52238351b64c4d055620e2fad4e24db87db2f/pkg/sql/schemachanger/scjob/job.go#L83)):*
> ```Go
> 	p := execCtx.(sql.JobExecContext)
> 	return p.ExecCfg().InternalDB.Txn(ctx, func(ctx context.Context, txn isql.Txn) error {
> 		exOp := n.deps.GetExplain()
> ```

Another option is embedding the full scplan, which would give us more flexibility to get the compact / deps explain (assuming we don't get an ugly dependency cycle).
___
*[`pkg/sql/catalog/lease/lease_internal_test.go` line 1641 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125559#-O-MAiMv7lfItKS7HK_W:-O-MAiMw2BGyNsgbSf3h:bow0mtf) ([raw file](https://github.com/cockroachdb/cockroach/blob/fac52238351b64c4d055620e2fad4e24db87db2f/pkg/sql/catalog/lease/lease_internal_test.go#L1641)):*
> ```Go
> 	// Insert using a synthetic descriptor.
> 	err := executor.WithSyntheticDescriptors(catalog.Descriptors{systemschema.LeaseTable_V23_2()}, func() error {
> 		nodeIDs := []string{"2", "2", "8", "3", "2"}
> ```

For session based testing we just need to get the session ID from the SQL liveness provider:

`tc.Servers[0].SQLLivenessProvider().(sqlliveness.Provider).Session()`

**Review by spilchen — COMMENTED** [review]
Thanks for taking a look @fqazi. I applied some of your changes and replied to the other ones.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125559#-:-O-N1czMCjyd3rK3IpB6:bfryjei)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @rafiss)

___
*[`pkg/sql/catalog/lease/count.go` line 322 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125559#-O-MDUmM4SlD3HzAEk7h:-O-N0Y543VR0xwKEoiT1:btq1x7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/fac52238351b64c4d055620e2fad4e24db87db2f/pkg/sql/catalog/lease/count.go#L322)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Nit: I think the other option is to push a boolean down rom the callers, but I'm not sure if that would be cleaner. I'll leave it to you.
</blockquote></details>

Yes, that's probably cheaper than doing a string compare.
___
*[`pkg/sql/schemachanger/scjob/job.go` line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125559#-O-MEf1nA8-sCAc9Yd_s:-O-Mvk2x1WUCa6ZLJzvy:b-xia8io) ([raw file](https://github.com/cockroachdb/cockroach/blob/fac52238351b64c4d055620e2fad4e24db87db2f/pkg/sql/schemachanger/scjob/job.go#L83)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Another option is embedding the full scplan, which would give us more flexibility to get the compact / deps explain (assuming we don't get an ugly dependency cycle).
</blockquote></details>

First, there doesn't appear to be a dependency cycle if we choose to store the plan instead. That part would be okay.

However, this approach introduces unwanted complexity. Consider the following points:

1. What if the explain output is requested before we've had a chance to save the plan? If we're storing a string for the explain output, we can simply return an empty string. But if we're storing the plan, we'd need to save a pointer to the current plan and check if it's nil before returning the output.

2. If we have a pointer to the current plan and someone requests the explain output, is the mutex sufficient? I'm not sure. There are many fields in the plan that could be modified simultaneously while generating the explain output, increasing the risk of errors.

3. The only way to get the explain output is through the DB Console, which isn't easily automated. This means it would receive limited testing. Any issues with generating the explain output from the saved plan would likely occur in real scenarios when we need it most. Generating the explain output at runtime and saving the string would likely reveal issues during our internal testing.
___
*[`pkg/sql/catalog/lease/lease_internal_test.go` line 1641 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125559#-O-MAiMv7lfItKS7HK_W:-O-Msyob2Dlfa4MF8i8U:becbofm) ([raw file](https://github.com/cockroachdb/cockroach/blob/fac52238351b64c4d055620e2fad4e24db87db2f/pkg/sql/catalog/lease/lease_internal_test.go#L1641)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

For session based testing we just need to get the session ID from the SQL liveness provider:

`tc.Servers[0].SQLLivenessProvider().(sqlliveness.Provider).Session()`
</blockquote></details>

I didn't have much luck using a real sessions ID. The lease query wasn't able to find the fake descriptors I added. Does it matter that we use a proper session ID? Populating using the old lease schema seemed to work fine.

**Review by fqazi — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125559)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @spilchen)

___
*[`pkg/sql/schemachanger/scjob/job.go` line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125559#-O-MEf1nA8-sCAc9Yd_s:-O-NVzPb9Wy4vEmQQWUH:b-19t30z) ([raw file](https://github.com/cockroachdb/cockroach/blob/fac52238351b64c4d055620e2fad4e24db87db2f/pkg/sql/schemachanger/scjob/job.go#L83)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

First, there doesn't appear to be a dependency cycle if we choose to store the plan instead. That part would be okay.

However, this approach introduces unwanted complexity. Consider the following points:

1. What if the explain output is requested before we've had a chance to save the plan? If we're storing a string for the explain output, we can simply return an empty string. But if we're storing the plan, we'd need to save a pointer to the current plan and check if it's nil before returning the output.

2. If we have a pointer to the current plan and someone requests the explain output, is the mutex sufficient? I'm not sure. There are many fields in the plan that could be modified simultaneously while generating the explain output, increasing the risk of errors.

3. The only way to get the explain output is through the DB Console, which isn't easily automated. This means it would receive limited testing. Any issues with generating the explain output from the saved plan would likely occur in real scenarios when we need it most. Generating the explain output at runtime and saving the string would likely reveal issues during our internal testing.
</blockquote></details>

I was thinking we could just store a pointer to the plan at:
```
p, err := makePostCommitPlan(ctx, deps, jobID, descriptorIDs, rollbackCause)
	if err != nil {
		if knobs != nil && knobs.OnPostCommitPlanError != nil {
			return knobs.OnPostCommitPlanError(err)
		}
		return err
	}
	deps.SetExplain(p.ExplainCompact())
```

But, both options work. I don't feel strongly about this.
___
*[`pkg/sql/catalog/lease/lease_internal_test.go` line 1641 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125559#-O-MAiMv7lfItKS7HK_W:-O-NVMSE2HUR27g3hujZ:b6v6yxo) ([raw file](https://github.com/cockroachdb/cockroach/blob/fac52238351b64c4d055620e2fad4e24db87db2f/pkg/sql/catalog/lease/lease_internal_test.go#L1641)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

I didn't have much luck using a real sessions ID. The lease query wasn't able to find the fake descriptors I added. Does it matter that we use a proper session ID? Populating using the old lease schema seemed to work fine.
</blockquote></details>

Yeah, the lease query injects: crdb_internal.sql_liveness_is_alive, which validates that the node in question is alive for the session based case.

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125559)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @rafiss)

___
*[`pkg/sql/schemachanger/scjob/job.go` line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125559#-O-MEf1nA8-sCAc9Yd_s:-O-aMGZFACgft1JGQPT4:bn45qqv) ([raw file](https://github.com/cockroachdb/cockroach/blob/fac52238351b64c4d055620e2fad4e24db87db2f/pkg/sql/schemachanger/scjob/job.go#L83)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

I was thinking we could just store a pointer to the plan at:
```
p, err := makePostCommitPlan(ctx, deps, jobID, descriptorIDs, rollbackCause)
	if err != nil {
		if knobs != nil && knobs.OnPostCommitPlanError != nil {
			return knobs.OnPostCommitPlanError(err)
		}
		return err
	}
	deps.SetExplain(p.ExplainCompact())
```

But, both options work. I don't feel strongly about this.
</blockquote></details>

I see. My preference is to stick with the current approach of storing the string. That seems less risky.
___
*[`pkg/sql/catalog/lease/lease_internal_test.go` line 1641 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125559#-O-MAiMv7lfItKS7HK_W:-O-a9lqm7l4HJrqYZ0VO:boknaya) ([raw file](https://github.com/cockroachdb/cockroach/blob/fac52238351b64c4d055620e2fad4e24db87db2f/pkg/sql/catalog/lease/lease_internal_test.go#L1641)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Yeah, the lease query injects: crdb_internal.sql_liveness_is_alive, which validates that the node in question is alive for the session based case.
</blockquote></details>

I like the current version of the test since it easily allows for cross node testing. I see there is a way to do that with session based leasing, but it seems rather complex than what I have. I added another test that does session based leasing tests with a single node.

**Review by fqazi — APPROVED** [review]
Great work Matt!  :lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125559#-:-O-aPNEPEfLNpxUcXr7j:b8k0y5g)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rafiss and @spilchen)

___
*[`pkg/sql/catalog/lease/lease_internal_test.go` line 1641 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125559#-O-MAiMv7lfItKS7HK_W:-O-aPKiv8ajIJBd_z9tv:b-pa926r) ([raw file](https://github.com/cockroachdb/cockroach/blob/fac52238351b64c4d055620e2fad4e24db87db2f/pkg/sql/catalog/lease/lease_internal_test.go#L1641)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

I like the current version of the test since it easily allows for cross node testing. I see there is a way to do that with session based leasing, but it seems rather complex than what I have. I added another test that does session based leasing tests with a single node.
</blockquote></details>

Perfect, thank you
___
*[`pkg/sql/catalog/lease/lease_internal_test.go` line 1709 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/125559#-O-aPUBpDPvcbLw9HIiY:-O-aPUBpDPvcbLw9HIiZ:bs4fmeg) ([raw file](https://github.com/cockroachdb/cockroach/blob/842e638d09423a27a2393fb952ae297553b093eb/pkg/sql/catalog/lease/lease_internal_test.go#L1709)):*
> ```Go
> 		nodeID := "0" // Hard code the node rather than getting it from srv to avoid import cycle
> 		version := 1
> 		region := "E'\\\\x80'" // Single region
> ```

You can use enum.One

**Review by rafiss — APPROVED** [review]
nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125559#-:-O-ahQ9_5o_qw45K834Q:b-j4xmku)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @fqazi and @spilchen)

___
*[`pkg/sql/schemachanger/scdeps/run_deps.go` line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125559#-O-IMttY6E4iYOiLHRyS:-O-agh_dDx1bW8sryXgX:b-6mjj4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc9e727830d66732b433d5bca87e4f99419b35b7/pkg/sql/schemachanger/scdeps/run_deps.go#L99)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

I think we need it. The `explainOutput` can be read/write at the same time. Even though the strings themselves are immutable, the assignment doesn't seem to have an atomic guarantee. I found this thread, which seems to confirm assignment isn't atomic: https://groups.google.com/g/golang-nuts/c/UWJlS8mPTlM?pli=1
</blockquote></details>

i see, thanks for looking into it! another option is to use `atomic.Value` (https://pkg.go.dev/sync/atomic#Value), but i think keeping the mutex might be better in case we add more things here in the future.

**Pull request merged**
