### PR TITLE
kvcoord: Replace rangefeed catchup semaphore with rate limiter

### LINKED ISSUE #110439: rangefeed: tune catchup scan semaphores
We have both client-side and server-side catchup scan semaphores. It isn't clear that these are tuned optimally, or even that we want them both on the client and server side. We should reconsider these.

Jira issue: CRDB-31428

Epic CRDB-26372

### PR DESCRIPTION
**Pull request by miretskiy**
The catchup scan limit was added in #77725 in order to attempt
to restrict a single rangefeed from consuming all catchup
scan slots on the KV side.  This client side limit has
been largely ineffective.

More recently, this semaphore has been coopted in #109346 in order
to pace goroutine creation rate on the client. This functionality
is important, but the implementation is not very good.

Namely, we are interested in controling the rate of new catchup scans
being started by the client (and thus, control the rate of goroutine
creation).  This implementation replaces the old implementation
with rate limit based approach.  The rate limits are configured using
`kv.rangefeed.client.stream_startup_rate` setting which sets
the rate on the number of newly established rangefeed
streams (default 100).

Closes #110439
Epic: CRDB-26372

Release note: None

### CODE REVIEW

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110919)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @erikgrinaker, and @rachitgsrivastava)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go` line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110919#gh-1331274477:-Nemq-2X9VnlMrAUt25U:b-855g7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c389838e3957549bc9fe77e923cdb46e8596995/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L69)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Instead of framing this in terms of a catchup scan estimate, I'd just frame it directly as the rangefeed client rate. It's hard to come up with a general catchup scan estimate, because it depends on a lot of factors, and will often vary even between different rangefeeds on the same cluster.
</blockquote></details>

Thoughts on this new name?
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go` line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110919#gh-1331292109:-NemOpgN2VZL6bWX0WAE:b4aqb6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c389838e3957549bc9fe77e923cdb46e8596995/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L79)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

This isn't really what it means -- this is only true if the catchup scan estimate is equal to or below the actual catchup scan duration, not if it's above.
</blockquote></details>

Naming is darn hard; I wanted to avoid burst; but... you know, I think I'll use that instead.  If it sounds too technical, then that's the goal.
Thoughts on this new name?
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go` line 714 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110919#gh-1331280666:-NemP44E61uHgMjOz_Iy:b-2wcajq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c389838e3957549bc9fe77e923cdb46e8596995/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L714)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Why do we return this? This subverts the rate limiting, since we're saying this request failed and should not count towards the rate limit.
</blockquote></details>

Ahh.. I see; you're right.

**Review by erikgrinaker — COMMENTED** [review]
> Reviewed 3 of 8 files at r1, 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110919)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @miretskiy, and @rachitgsrivastava)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go` line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110919#gh-1331274477:-NerW5hf-UHVabQtrMUe:bw4gdd6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c389838e3957549bc9fe77e923cdb46e8596995/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L69)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Thoughts on this new name?
</blockquote></details>

Well, this isn't really correct either.

The rate limiter is a token bucket. The rate specifies the rate at which tokens are added to the bucket. Burst specifies the size of the bucket.

If we set rate to 1 per second, with 0 burst, then we will spawn 60 per minute (1 each second at a fixed rate). If we set burst to 100 then we'll spawn 100 immediately (without a rate limit), then 1 per second after that (because we never allow the bucket to fill back up, we just immediately consume the tokens as they're added). The rate and burst are independent parameters.

The way it's set up here, we'll spawn 180 immediately, then 60 per second after that.

Do we even need or want burst here, instead of just a smooth rate?
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go` line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110919#gh-1331292109:-NerWxDGAfjwslw3wP2X:bl2wyfn) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c389838e3957549bc9fe77e923cdb46e8596995/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L79)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Naming is darn hard; I wanted to avoid burst; but... you know, I think I'll use that instead.  If it sounds too technical, then that's the goal.
Thoughts on this new name?
</blockquote></details>

Well, this isn't really correct either.

The rate limiter is a token bucket. The rate specifies the rate at which tokens are added to the bucket. Burst specifies the size of the bucket.

If we set rate to 1 per second, with 0 burst, then we will spawn 60 per minute (1 each second at a fixed rate). If we also set burst to 100 then we'll spawn 100 immediately (without a rate limit), then 1 per second after that (because we never allow the bucket to fill back up, we just immediately consume the tokens as they're added). The rate and burst are independent parameters.

The way it's set up here, we'll spawn 180 immediately, then 60 per second after that.

Do we even need or want burst here, instead of just a smooth rate?

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110919)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @miretskiy, and @rachitgsrivastava)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go` line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110919#gh-1331292109:-NerXUQy0BlP2wxbPAJ2:bvv5jj6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c389838e3957549bc9fe77e923cdb46e8596995/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L79)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Well, this isn't really correct either.

The rate limiter is a token bucket. The rate specifies the rate at which tokens are added to the bucket. Burst specifies the size of the bucket.

If we set rate to 1 per second, with 0 burst, then we will spawn 60 per minute (1 each second at a fixed rate). If we also set burst to 100 then we'll spawn 100 immediately (without a rate limit), then 1 per second after that (because we never allow the bucket to fill back up, we just immediately consume the tokens as they're added). The rate and burst are independent parameters.

The way it's set up here, we'll spawn 180 immediately, then 60 per second after that.

Do we even need or want burst here, instead of just a smooth rate?
</blockquote></details>

Whoops, didn't mean to post this twice, was trying to move it to the other thread.

**Comment by miretskiy** [comment]
> > Reviewed 3 of 8 files at r1, 2 of 4 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110919)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @miretskiy, and @rachitgsrivastava)
> 
> _[`pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go` line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110919#gh-1331274477:-NerW5hf-UHVabQtrMUe:bw4gdd6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c389838e3957549bc9fe77e923cdb46e8596995/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L69)):_
> 
> Previously, miretskiy (Yevgeniy Miretskiy) wrote…
> Well, this isn't really correct either.
> 
> The rate limiter is a token bucket. The rate specifies the rate at which tokens are added to the bucket. Burst specifies the size of the bucket.
> 
> If we set rate to 1 per second, with 0 burst, then we will spawn 60 per minute (1 each second at a fixed rate). If we set burst to 100 then we'll spawn 100 immediately (without a rate limit), then 1 per second after that (because we never allow the bucket to fill back up, we just immediately consume the tokens as they're added). The rate and burst are independent parameters.
> 
> The way it's set up here, we'll spawn 180 immediately, then 60 per second after that.
> 
> Do we even need or want burst here, instead of just a smooth rate?
> 
> _[`pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go` line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110919#gh-1331292109:-NerWxDGAfjwslw3wP2X:bl2wyfn) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c389838e3957549bc9fe77e923cdb46e8596995/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L79)):_
> 
> Previously, miretskiy (Yevgeniy Miretskiy) wrote…
> > Naming is darn hard; I wanted to avoid burst; but... you know, I think I'll use that instead.  If it sounds too technical, then that's the goal.
> > Thoughts on this new name?
> 
> Well, this isn't really correct either.
> 
> The rate limiter is a token bucket. The rate specifies the rate at which tokens are added to the bucket. Burst specifies the size of the bucket.
> 
> If we set rate to 1 per second, with 0 burst, then we will spawn 60 per minute (1 each second at a fixed rate). If we also set burst to 100 then we'll spawn 100 immediately (without a rate limit), then 1 per second after that (because we never allow the bucket to fill back up, we just immediately consume the tokens as they're added). The rate and burst are independent parameters.
> 
> The way it's set up here, we'll spawn 180 immediately, then 60 per second after that.
> 

Kinda what I wanted to do... 

> Do we even need or want burst here, instead of just a smooth rate?

I don't know if we need burst; Just going to set 100/sec rate, 0 burst.

**Review by erikgrinaker — APPROVED** [review]
>Kinda what I wanted to do...

Ah ok, I thought there might be a misunderstanding about how the rate limiter worked. Anyway, I don't have a good sense of what the optimal strategy is (might have performance implications), but since we want to reduce Go scheduler tail latencies it seems like we want to avoid bursts -- although I'm not sure it matters until we go past O(1000) goroutines anyway, and I guess the burst doesn't really make much of a difference either way in that case. This is simpler though.

Thanks!

> Reviewed 1 of 8 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110919#-:-NesB_JF2OX4PpIgltef:b3izf20)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @miretskiy, and @rachitgsrivastava)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go` line 70 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110919#-NesCAny24hy6ugISsbg:-NesCAny24hy6ugISsbh:bi96c5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/381ea5cdf5e03530df13fa1cb23cc4ee26c1ecf2/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L70)):*
> ```Go
> 	settings.TenantWritable,
> 	"kv.rangefeed.client.stream_startup_rate",
> 	"controls the rate the client will initiate new rangefeed stream for a single range; 0 implies unlimited",
> ```

nit: per-second rate

**Pull request merged**
