### PR TITLE
roachtest: enable txn heartbeat loops for 1PC txns in kv/contention/nodes=4

### PR DESCRIPTION
**Pull request by nvb**
I noticed when debugging issues in #45482 that unhandled deadlocks occasionally
resolved themselves because txns would eventually time out. This was because
we don't start the txn heartbeat loop for 1PC txns. In this kind of test, we
want any unhandled deadlocks to be as loud as possible, so just like we set
a very long txn expiration, we also enable the txn heartbeat loop for all
txns, even those that we expect will be 1PC.

This commit also drops the kv.lock_table.deadlock_detection_push_delay down
for the test, since it's already touching this code.

### CODE REVIEW

**Review by tbg — APPROVED** [review]

**Review by andreimatei — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45568#-:-M1RZUhLEDI8YlzLhsiN:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/cmd/roachtest/kv.go, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45568#-M1RZNT-2leRz7CTDFLN:-M1RZNT-2leRz7CTDFLO:blhrhap) ([raw file](https://github.com/cockroachdb/cockroach/blob/9122438442f6d35dd2ed748a328c064c69f7fdf7/pkg/cmd/roachtest/kv.go#L225)):*
> ```Go
> 			// Drop the deadlock detection delay because the test creates a
> 			// large number transaction deadlocks.
> 			if _, err := conn.Exec(`
> ```

I think there's a way to check the cluster version instead of swallowing failures

**Review by nvb — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45568#-:-M1Rq_K51g62OC7xEltj:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/cmd/roachtest/kv.go, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45568#-M1RZNT-2leRz7CTDFLN:-M1RqNJM5zVF3VH1x-W2:b-3w0vv2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9122438442f6d35dd2ed748a328c064c69f7fdf7/pkg/cmd/roachtest/kv.go#L225)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think there's a way to check the cluster version instead of swallowing failures
</blockquote></details>

Yeah, that's another option. We already have this pattern all over the place though and I don't want to get into the game of guessing what the right cluster version is, so I'm going to stick with this.

**Comment by yuzefovich** [comment]
Bors crashed because of my PR, so:

bors r+

**Pull request merged**
