### PR TITLE
sql: better errors from parsing bool vars

### PR DESCRIPTION
**Pull request by andreimatei**
Release note: None

### CODE REVIEW

**Review by jordanlewis — CHANGES_REQUESTED** [review]
Thanks! While you're in here, would you mind adding "yes" and "no" to the allowed list of options to increase our compatibility by a bit?

Also, can you change the error message to say that it was a boolean that was required? Here's what Postgres gives, which I rather like (I'd support just copying their message):

```
jordan=# \set VERBOSITY verbose
jordan=# set default_transaction_read_only='on';
SET
jordan=# set default_transaction_read_only='yes';
SET
jordan=# set default_transaction_read_only='true';
SET
jordan=# set default_transaction_read_only='doof';
ERROR:  22023: parameter "default_transaction_read_only" requires a Boolean value
LOCATION:  parse_and_validate_value, guc.c:5998
```

**Review by andreimatei — COMMENTED** [review]
donezo

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47042#-:-M4evduF9TxYUacifCWm:b-rnr8uc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Review by jordanlewis — APPROVED** [review]
Thanks!

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47042#-:-M4osfhN2zYloFsQofFF:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Pull request merged**
