### PR TITLE
sql: support pg_get_indexdef with 3 arguments

### LINKED ISSUE #26629: sql: support pg_get_indexdef with 3 arguments
Needed for  #16971.

Used in this query, already listed in the `srfs` logic test file.

```sql
SELECT NULL AS table_cat,
       n.nspname AS table_schem,
       ct.relname AS TABLE_NAME,
       NOT i.indisunique AS non_unique,
       NULL AS index_qualifier,
       ci.relname AS index_name,
       CASE i.indisclustered
         WHEN TRUE THEN 1
         ELSE CASE am.amname
           WHEN 'hash' THEN 2
           ELSE 3
         END
       END AS TYPE,
       (i.KEYS).n AS ordinal_position,
       trim(BOTH '"' FROM pg_catalog.pg_get_indexdef(ci.oid, (i.KEYS).n, FALSE)) AS COLUMN_NAME,
       CASE am.amcanorder
         WHEN TRUE THEN CASE i.indoption[(i.keys).n - 1] & 1
           WHEN 1 THEN 'D'
           ELSE 'A'
         END
         ELSE NULL
       END AS asc_or_desc,
       ci.reltuples AS CARDINALITY,
       ci.relpages AS pages,
       pg_catalog.pg_get_expr(i.indpred, i.indrelid) AS filter_condition
FROM pg_catalog.pg_class ct
JOIN pg_catalog.pg_namespace n ON (ct.relnamespace = n.oid)
JOIN (
  SELECT i.indexrelid,
         i.indrelid,
         i.indoption,
         i.indisunique,
         i.indisclustered,
         i.indpred,
         i.indexprs,
         information_schema._pg_expandarray(i.indkey) AS KEYS
  FROM pg_catalog.pg_index i
) i
  ON (ct.oid = i.indrelid)
JOIN pg_catalog.pg_class ci ON (ci.oid = i.indexrelid)
JOIN pg_catalog.pg_am am ON (ci.relam = am.oid)
WHERE TRUE
  AND n.nspname = 'public'
  AND ct.relname = 'j'
ORDER BY non_unique,
         TYPE,
         index_name,
         ordinal_position
```

### PR DESCRIPTION
**Pull request by bsnyder788**
Fixes #26629

### CODE REVIEW

**Review by knz — CHANGES_REQUESTED** [review]
Oh nice! Thank you for this contribution!

I have some recommendations below.

Also, a nit, we format release notes with parentheses, like this: `Release note (sql change): ...`

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27161#-:-LGaF4BzCkF-cGFV0HeU:b-ijv0tw)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/builtins/pg_builtins.go, line 564 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27161#-LGaDMI64VJoPQho5avK:-LGaDMI76DGT0wbnmtLC:b-vi1pr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db5e0dcd1c82d970d8bbdd7fcc1d845f9da3640/pkg/sql/sem/builtins/pg_builtins.go#L564)):*
> ```Go
> 		makePGGetIndexDef(tree.ArgTypes{{"index_oid", types.Oid}},
> 			getPGGetIndexDefByOID),
> 		makePGGetIndexDef(tree.ArgTypes{{"index_oid", types.Oid}, {"column_no", types.Int},
> ```

For readability: place all the arguments on a single line, then the `func` on the next.
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 573 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27161#-LGaDSdR7h7UquneX9h3:-LGaDSdR7h7UquneX9h4:b-icriup) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db5e0dcd1c82d970d8bbdd7fcc1d845f9da3640/pkg/sql/sem/builtins/pg_builtins.go#L573)):*
> ```Go
> 				ctx.Ctx(), "pg_get_indexdef",
> 				ctx.Txn,
> 				`SELECT ischema.column_name as pg_get_indexdef FROM information_schema.statistics AS ischema 
> ```

The contents of a \`...\` block can span multiple lines. The following is more readable:

```
`
SELECT ischema.column_name as pg_get_indexdef
  FROM information_schema.statistics AS ischema
       INNER JOIN pg_catalog.pg_indexes AS pgindex
               ON ischema.table_schema = pgindex.schemaname
              AND ischema.table_name = pgindex.tablename
              AND ischema.index_name = pgindex.indexname
              AND pgindex.crdb_oid = $1 AND ischema.seq_in_index = $2`, args[0], args[1])
```

you also do not need a final semicolon.
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 581 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27161#-LGaEhjX90R3VNt1TPBv:-LGaEhjX90R3VNt1TPBw:bnii7co) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db5e0dcd1c82d970d8bbdd7fcc1d845f9da3640/pkg/sql/sem/builtins/pg_builtins.go#L581)):*
> ```Go
> 			}
> 			if len(r) == 0 {
> 				return nil, pgerror.NewErrorf(pgerror.CodeInvalidParameterValueError, "unknown index (OID=%s)", args[0])
> ```

1) I believe this is incorrect: in postgres if the index does not exist the function returns NULL, not an error. 

In that case, you might be able to produce the NULL automatically with the query above using an outer join instead.

2) I'd recommend an assertion that the number of result rows is not greater than 1, just to prevent any future surprise.

**Comment by bsnyder788** [comment]
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 581 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27161#-LGaEhjX90R3VNt1TPBv:-LGkqCbhAKeR4OjiRJRC:bbg0bsb) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db5e0dcd1c82d970d8bbdd7fcc1d845f9da3640/pkg/sql/sem/builtins/pg_builtins.go#L581)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

1) I believe this is incorrect: in postgres if the index does not exist the function returns NULL, not an error. 

In that case, you might be able to produce the NULL automatically with the query above using an outer join instead.

2) I'd recommend an assertion that the number of result rows is not greater than 1, just to prevent any future surprise.
</blockquote></details>

Thanks for the review @knz!

For #1, you are correct, postgres returns NULL if the oid of the index provided does not exist or does not correspond to an index.  

The original CRDB behavior of get_pg_indexdef(oid) (1 argument version) is also throwing the unknown index (OID=XXXX) error vs just returning NULL.  Would you like me to make both of them behave like postgres now?  Or just the 3 arg version and leave the 1 arg one alone?  

I'm not familiar enough with the full codebase to know what kind of unintended consequences going either way could have on existing applications, etc.

For #2, do you have an example of the assertion pattern you are recommending that already exists in the code as far as error message, etc?

**Review by knz — CHANGES_REQUESTED** [review]
Thank you for your updates!

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27161#-:-LGlRbMf0fBCBWA5Eezc:bzdj40h)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/builtins/pg_builtins.go, line 581 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27161#-LGaEhjX90R3VNt1TPBv:-LGlQcG53Lxibm7EE9ew:b6zkqoq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db5e0dcd1c82d970d8bbdd7fcc1d845f9da3640/pkg/sql/sem/builtins/pg_builtins.go#L581)):*
<details><summary><i>Previously, bsnyder788 (Brett Snyder) wrote…</i></summary><blockquote>

Thanks for the review @knz!

For #1, you are correct, postgres returns NULL if the oid of the index provided does not exist or does not correspond to an index.  

The original CRDB behavior of get_pg_indexdef(oid) (1 argument version) is also throwing the unknown index (OID=XXXX) error vs just returning NULL.  Would you like me to make both of them behave like postgres now?  Or just the 3 arg version and leave the 1 arg one alone?  

I'm not familiar enough with the full codebase to know what kind of unintended consequences going either way could have on existing applications, etc.

For #2, do you have an example of the assertion pattern you are recommending that already exists in the code as far as error message, etc? 
</blockquote></details>

1) The value for NULL is `tree.DNull`, not `tree.NewDString("")`

2) yes it would be better to make both implementations work like posgres. Arguably the code we had here was incorrect. This is the kind of fix that will make everything better, I don't see any unintended consequences (in particular I don't see any current uses of this in the code base). You'll just have to add/modify the corresponding test in `pkg/sql/logictest/testdata/logic_test/builtin_function`

3)

```go
if len(r) > 1 {
   return pgerror.Errorf(pgerror.CodeInternalError, "programming error: pg_get_indexdef query has more than 1 result row: %+v", r) 
}
```
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 576 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27161#-LGlRSiW2kY07bu0MTpw:-LGlRSiW2kY07bu0MTpx:b-vm7vkx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad722a39208d0ea8e9f9360a7688c9d1246f0910/pkg/sql/sem/builtins/pg_builtins.go#L576)):*
> ```Go
> 		               FROM information_schema.statistics AS ischema 
> 											INNER JOIN pg_catalog.pg_indexes AS pgindex 
> 													ON ischema.table_schema=pgindex.schemaname 
> ```

nit: "`... = ...`" not "`...=...`" here and below

**Comment by bsnyder788** [comment]
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 581 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27161#-LGaEhjX90R3VNt1TPBv:-LGlXMtN6jPL6mI6FOIX:bmp6t8y) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db5e0dcd1c82d970d8bbdd7fcc1d845f9da3640/pkg/sql/sem/builtins/pg_builtins.go#L581)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

1) The value for NULL is `tree.DNull`, not `tree.NewDString("")`

2) yes it would be better to make both implementations work like posgres. Arguably the code we had here was incorrect. This is the kind of fix that will make everything better, I don't see any unintended consequences (in particular I don't see any current uses of this in the code base). You'll just have to add/modify the corresponding test in `pkg/sql/logictest/testdata/logic_test/builtin_function`

3)

```go
if len(r) > 1 {
   return pgerror.Errorf(pgerror.CodeInternalError, "programming error: pg_get_indexdef query has more than 1 result row: %+v", r) 
}
```

</blockquote></details>

Ok, perfect. I will fix up the 1 argument version as well.  

For #2. The NewDString("") is actually for another edge case I noticed with PG.  If the index exists and the column number specified does not exist in the index (e.g. using -1, or 1000) it returns an empty string instead of NULL. I will be able to make it more obvious when I refactor to handle the NULL for the index itself not existing.

And thanks for the error snippet!

**Comment by bsnyder788** [comment]
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 576 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27161#-LGlRSiW2kY07bu0MTpw:-LGmC32e0wzzZ1akA_aB:bmfxgaw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad722a39208d0ea8e9f9360a7688c9d1246f0910/pkg/sql/sem/builtins/pg_builtins.go#L576)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: "`... = ...`" not "`...=...`" here and below
</blockquote></details>

Done :)

**Comment by bsnyder788** [comment]
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 581 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27161#-LGaEhjX90R3VNt1TPBv:-LGmCQch12KJ1Z9vJHoh:b-f866jc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db5e0dcd1c82d970d8bbdd7fcc1d845f9da3640/pkg/sql/sem/builtins/pg_builtins.go#L581)):*
<details><summary><i>Previously, bsnyder788 (Brett Snyder) wrote…</i></summary><blockquote>

Ok, perfect. I will fix up the 1 argument version as well.  

For #2. The NewDString("") is actually for another edge case I noticed with PG.  If the index exists and the column number specified does not exist in the index (e.g. using -1, or 1000) it returns an empty string instead of NULL. I will be able to make it more obvious when I refactor to handle the NULL for the index itself not existing.

And thanks for the error snippet!
</blockquote></details>

@knz Done.

**Review by knz — APPROVED** [review]
:lgtm:

very good!

Thank you again for all your efforts!

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27161#-:-LGnrTEhAPWhT0V7GLbP:b46yof)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
