### PR TITLE
Clarify/Remove request/response Timestamps

### PR DESCRIPTION
**Pull request by tbg**
There's more upcoming work, but this is a good checkpoint.

---

This change is [Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5028)

### CODE REVIEW

**Comment by bdarnell** [comment]
LGTM

---

Review status: 0 of 18 files reviewed at latest revision, 2 unresolved discussions.

---

*[kv/txn_coord_sender.go, line 715 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5028#-KCS-D9LTdAP_4nVr-NA:-KCS-D9LTdAP_4nVr-NB:-224548519) ([raw file](https://github.com/cockroachdb/cockroach/blob/62c9cda12ee399ff46852da0b5e9e156997c6a6d/kv/txn_coord_sender.go#L715)):*
There's no longer any code in this `case nil`; can it and its comments be removed?

---

*[storage/store.go, line 1457 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5028#-KCS68v2DODTksimzKl6:-KCS68v2DODTksimzKl7:-207708832) ([raw file](https://github.com/cockroachdb/cockroach/blob/62c9cda12ee399ff46852da0b5e9e156997c6a6d/storage/store.go#L1457)):*
Remove this line?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5028#-:-KCS6HxEVSmvCZs-hVmB:676834233)*

**Comment by tamird** [comment]
In `Remove BatchResponse_Header.Timestamp`: can you add rationale to the commit message? I guess the field wasn't being read.

---

Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 7 of 7 files at r3, 1 of 1 files at r4, 4 of 4 files at r5, 10 of 10 files at r6, 1 of 1 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[kv/txn_coord_sender.go, line 715 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5028#-KCS-D9LTdAP_4nVr-NA:-KCS7Fn5gvdqFzyNUfVL:-372550186) ([raw file](https://github.com/cockroachdb/cockroach/blob/62c9cda12ee399ff46852da0b5e9e156997c6a6d/kv/txn_coord_sender.go#L715)):*
Maybe it's avoiding the `default`?

---

*[sql/delete.go, line 46 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5028#-KCS5Z0QF1S95cxbm53_:-KCS5Z0QF1S95cxbm53a:672878549) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bcb9214e9e4d4919fd28f7dfef66baf1415b2a1/sql/delete.go#L46)):*
why didn't CI catch this stuff?

---

*[storage/store.go, line 1400 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5028#-KCS6ot5Bjc6cBGIO9vP:-KCS6ot6n7mtPEauI2Bl:-1082719457) ([raw file](https://github.com/cockroachdb/cockroach/blob/62c9cda12ee399ff46852da0b5e9e156997c6a6d/storage/store.go#L1400)):*
s/a higher timestamp/a higher timestamp than would be deduced/? i'm actually not sure what this is saying - what if i want to read in the past?

---

*[storage/store.go, line 1402 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5028#-KCS6kNG36DL1gEAQCEq:-KCS6kNG36DL1gEAQCEr:-1754913749) ([raw file](https://github.com/cockroachdb/cockroach/blob/62c9cda12ee399ff46852da0b5e9e156997c6a6d/storage/store.go#L1402)):*
s/from//

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5028#-:-KCS5mcZLvG1gfexxT9h:-1087825315)*

**Comment by tschottdorf** [comment]
Done.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[kv/txn_coord_sender.go, line 715 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5028#-KCS-D9LTdAP_4nVr-NA:-KCS9EqP_mUIz3-QKGpX:346646459) ([raw file](https://github.com/cockroachdb/cockroach/blob/62c9cda12ee399ff46852da0b5e9e156997c6a6d/kv/txn_coord_sender.go#L715)):*
Yes, it's avoiding the default. I moved this case down just above and updated the comment.

---

*[sql/delete.go, line 46 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5028#-KCS5Z0QF1S95cxbm53_:-KCS9K65PxPL98KXlZ-w:1822987351) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bcb9214e9e4d4919fd28f7dfef66baf1415b2a1/sql/delete.go#L46)):*
I looked at the logs on CI and was confused as well. There, the stuff runs and I didn't see any error output. Could we possibly have different versions of `vet`?

---

*[storage/store.go, line 1400 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5028#-KCS6ot5Bjc6cBGIO9vP:-KCS9YPr33_OZyNcDQLV:-1829600267) ([raw file](https://github.com/cockroachdb/cockroach/blob/62c9cda12ee399ff46852da0b5e9e156997c6a6d/storage/store.go#L1400)):*
updated:

> Should a transactional operation be forced to a higher
// timestamp (for instance due to the timestamp cache), the response will have
// a transaction set which should be used to update the client transaction from.

---

*[storage/store.go, line 1402 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5028#-KCS6kNG36DL1gEAQCEq:-KCSABchOt-ruCrCmRLs:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/62c9cda12ee399ff46852da0b5e9e156997c6a6d/storage/store.go#L1402)):*
Done.

---

*[storage/store.go, line 1457 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5028#-KCS68v2DODTksimzKl6:-KCSABL9V5Q-Y88HLf7e:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/62c9cda12ee399ff46852da0b5e9e156997c6a6d/storage/store.go#L1457)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5028#-:-KCSAEPD_VSKzqMTHGb1:-499146009)*

**Comment by bdarnell** [comment]
Review status: 16 of 18 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[sql/delete.go, line 46 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5028#-KCS5Z0QF1S95cxbm53_:-KCS8kk5E2fxoRjS8DmJ:-194237882) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bcb9214e9e4d4919fd28f7dfef66baf1415b2a1/sql/delete.go#L46)):*
There appears to be a bug in vet (I've seen it before but haven't tried to track it down) in which it appears to be working from incomplete type information. It interprets a composite literal for a slice type defined in another package as an unkeyed composite struct literal. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5028)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r9, 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[kv/txn_coord_sender.go, line 745 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5028#-KCSHnprA3hyFHE_2LRL:-KCSHnpsCQ6JswYwY3Yk:826876722) ([raw file](https://github.com/cockroachdb/cockroach/blob/35666397574e7b18161baf31dfc55e3d5378787a/kv/txn_coord_sender.go#L745)):*
s/to/to do/

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5028)*

**Comment by tschottdorf** [comment]
Review status: 17 of 18 files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/delete.go, line 46 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5028#-KCS5Z0QF1S95cxbm53_:-KCSJ1DneyKK8f0wZvLh:360001104) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bcb9214e9e4d4919fd28f7dfef66baf1415b2a1/sql/delete.go#L46)):*
I vaguely remember us having issues like that before (and tracking them down to different types observed in the linter) - tests would fail outside of the container, but it would work inside - weird that such differences exist. I think that was an err shadowing lint.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5028)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r11.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/delete.go, line 46 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5028#-KCS5Z0QF1S95cxbm53_:-KCSOA9ujq-dvNpQu0df:108095680) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bcb9214e9e4d4919fd28f7dfef66baf1415b2a1/sql/delete.go#L46)):*
Yeah, @mberhault and I went down that rabbit hole and ended up with an unsatisfying response from rob pike. Likely a related issue. https://github.com/golang/go/issues/11843

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5028)*

**Pull request merged**
