### PR TITLE
ts: convert to gRPC

### LINKED ISSUE #6858: ts.Server: convert to grpc
This is one of the last non-grpc handlers in the codebase - we should use grpc here as we do elsewhere.

Should be straightforward, good starter task.

### PR DESCRIPTION
**Pull request by tamird**
Fixes #6858.

Extracted from other work.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6901)

### CODE REVIEW

**Comment by tschottdorf** [comment]
:lgtm:

<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> #### ts: convert to gRPC
> 
> Fixes #6858.
> 
> 
> 
> Extracted from other work.
> 
> 
> 
</details>


---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[server/server.go, line 473 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6901#-KIdH9ZvxDhyVOXC5tmt:-KIdH9ZwdVgxyJeUsWvp:138868961) ([raw file](https://github.com/cockroachdb/cockroach/blob/30edb5bbde308d022c96ebe1e058608609de4ad4/server/server.go#L473)):*
> ```Go
> 
> 	if err := RegisterTimeSeriesHandlerFromEndpoint(gwCtx, gwMux, s.ctx.Addr, opts); err != nil {
> 		return util.Errorf("error constructing grpc-gateway: %s. are your certificates valid?", err)
> ```

s/are/Are/ or s/\./;/

---

*[util/jsonpb_marshal.go, line 30 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6901#-KIdITjfcNnnQBTtgVJX:-KIdITjgTzyp_oueDcxw:152979441) ([raw file](https://github.com/cockroachdb/cockroach/blob/30edb5bbde308d022c96ebe1e058608609de4ad4/util/jsonpb_marshal.go#L30)):*
> ```Go
> 
> var _ gwruntime.Marshaler = (*JSONPb)(nil)
> ```

is this used?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6901#-:-KIdIjAPQScFrfrkkO6H:1417088721)*

**Comment by tamird** [comment]
Review status: 10 of 15 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[server/server.go, line 473 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6901#-KIdH9ZvxDhyVOXC5tmt:-KIdUWoSB9GWshf1n9hZ:1835081954) ([raw file](https://github.com/cockroachdb/cockroach/blob/30edb5bbde308d022c96ebe1e058608609de4ad4/server/server.go#L473)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> s/are/Are/ or s/\./;/
</details>
This exact error string is repeated in a few places. I have a plan to DRY it up but gonna leave as is for now.

---

*[util/jsonpb_marshal.go, line 30 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6901#-KIdITjfcNnnQBTtgVJX:-KIdUcwqcmZoQ57qwjIU:-1863601792) ([raw file](https://github.com/cockroachdb/cockroach/blob/30edb5bbde308d022c96ebe1e058608609de4ad4/util/jsonpb_marshal.go#L30)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> is this used?
</details>
The above is a type assertion, and `typeProtoMessage` is indeed used in this file and in proto_marshal.go

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6901)*

**Comment by tschottdorf** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6901)*

**Comment by tschottdorf** [comment]
:science_dog: on the UI stuff, but looks like that's to keep us afloat until `next/` hits, right?

<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> :lgtm:
</details>


---

Reviewed 8 of 8 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6901#-:-KIdeFhLdPm4patCnCZS:-1751867113)*

**Comment by tamird** [comment]
Yep

<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> :science_dog: on the UI stuff, but looks like that's to keep us afloat until `next/` hits, right?
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6901#-:-KIdeUnyGZRAHM5Uv7NC:160394143)*

**Comment by d4l3k** [comment]
Reviewed 3 of 4 files at r4.
Review status: 23 of 24 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[server/server.go, line 243 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6901#-KIdlmGted8_Zb8lTanc:-KIdlmGux7i1yG8s_Pwh:764804091) ([raw file](https://github.com/cockroachdb/cockroach/blob/da94f6d0e18a454deafbe25ea76b71b4a45ac170/server/server.go#L243)):*
> ```Go
> 	s.tsServer = ts.MakeServer(s.tsDB)
> 
> 	RegisterTimeSeriesServer(s.grpc, &s.tsServer)
> ```

This should probably be done in the same way admin and status are. See (*statusServer).Register .

---

*[server/server.go, line 441 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6901#-KIdlVlLD_kLwSjqIGee:-KIdlVlMz7k3ZRad6W-D:1819240925) ([raw file](https://github.com/cockroachdb/cockroach/blob/da94f6d0e18a454deafbe25ea76b71b4a45ac170/server/server.go#L441)):*
> ```Go
> 		gwruntime.WithMarshalerOption(gwruntime.MIMEWildcard, jsonpb),
> 		gwruntime.WithMarshalerOption(util.JSONContentType, jsonpb),
> 		gwruntime.WithMarshalerOption(util.AltJSONContentType, jsonpb),
> ```

Is this necessary given the MIMEWildcard?

---

*[server/server.go, line 476 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6901#-KIdm2W9uY3mB_dWGJ4P:-KIdm2W9uY3mB_dWGJ4Q:-730516057) ([raw file](https://github.com/cockroachdb/cockroach/blob/da94f6d0e18a454deafbe25ea76b71b4a45ac170/server/server.go#L476)):*
> ```Go
> 	if err := RegisterTimeSeriesHandlerFromEndpoint(gwCtx, gwMux, s.ctx.Addr, opts); err != nil {
> 		return util.Errorf("error constructing grpc-gateway: %s. are your certificates valid?", err)
> 	}
> ```

Should be done the same way as admin and status

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6901)*

**Comment by d4l3k** [comment]
Reviewed 1 of 4 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6901)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/server.go, line 473 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6901#-KIdH9ZvxDhyVOXC5tmt:-KIdvK3DWn64gA2QCcUj:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/30edb5bbde308d022c96ebe1e058608609de4ad4/server/server.go#L473)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> This exact error string is repeated in a few places. I have a plan to DRY it up but gonna leave as is for now.
</details>
Done.

---

*[server/server.go, line 243 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6901#-KIdlmGted8_Zb8lTanc:-KIdqMJBtXu8rLZiu4YM:-923892155) ([raw file](https://github.com/cockroachdb/cockroach/blob/da94f6d0e18a454deafbe25ea76b71b4a45ac170/server/server.go#L243)):*
<details><summary><i>Previously, d4l3k (Tristan Rice) wrote…</i></summary>
> This should probably be done in the same way admin and status are. See (*statusServer).Register .
</details>
Done. I was fighting with grpc-gateway to generate code in two different packages, but I have it worked out now.

---

*[server/server.go, line 476 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6901#-KIdm2W9uY3mB_dWGJ4P:-KIdvFUdBGJsIOR_OYCQ:2021569897) ([raw file](https://github.com/cockroachdb/cockroach/blob/da94f6d0e18a454deafbe25ea76b71b4a45ac170/server/server.go#L476)):*
<details><summary><i>Previously, d4l3k (Tristan Rice) wrote…</i></summary>
> Should be done the same way as admin and status
</details>
Done. Simplified the interfaces and made them share a connection while I was here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6901)*

**Comment by d4l3k** [comment]
Reviewed 14 of 15 files at r5.
Review status: 26 of 27 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/parser/sql.y, line 283 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6901#-KIdz4wSxZWlivgIMDIR:-KIdz4wTQw0i6Lzz3KMu:910080929) ([raw file](https://github.com/cockroachdb/cockroach/blob/731e4a29e79f9261ee05e954e454387458c7e2cf/sql/parser/sql.y#L283)):*
> ```Yacc
> }
> 
> %type <union> /* <[]Statement> */ stmt_block
> ```

What's up with this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6901)*

**Comment by tamird** [comment]
Review status: 23 of 26 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/parser/sql.y, line 283 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6901#-KIdz4wSxZWlivgIMDIR:-KIe18EOo84NzMx9WPXb:333044403) ([raw file](https://github.com/cockroachdb/cockroach/blob/731e4a29e79f9261ee05e954e454387458c7e2cf/sql/parser/sql.y#L283)):*
<details><summary><i>Previously, d4l3k (Tristan Rice) wrote…</i></summary>
> What's up with this?
</details>
Gah I interrupted `go generate`. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6901)*

**Comment by d4l3k** [comment]
:lgtm:

<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Yep
</details>


---

Review status: 23 of 25 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6901#-:-KIeCT5JudnpPiNBaQMo:1417088721)*

**Comment by d4l3k** [comment]
Reviewed 2 of 4 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6901)*

**Comment by d4l3k** [comment]
Reviewed 14 of 15 files at r1, 5 of 6 files at r2, 8 of 8 files at r3, 1 of 15 files at r5, 2 of 4 files at r6, 9 of 9 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6901)*

**Comment by d4l3k** [comment]
:lgtm:

<details><summary><i>Previously, d4l3k (Tristan Rice) wrote…</i></summary>
> :lgtm:
</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6901#-:-KIeOHm4MQP6QDohaey-:1417088721)*

**Comment by tamird** [comment]
Sigh, acceptance failures seem legit? will take a look with @cuongdo tomorrow.

**Pull request merged**
