### PR TITLE
sql: Make cancel checker more efficient

### PR DESCRIPTION
**Pull request by miretskiy**
Arrange for cancel checker to be notified once context
is done.

```
Old implementation:
BenchmarkCancelChecker-10    	133185742	   8.790 ns/op
New Implementation:
BenchmarkCancelChecker-10    	1000000000	 0.5804 ns/op
```

Epic: None

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Nice! I like it. Curious though what prompted you to look into this?

(Also, not sure if you were planning to address those, but there are a few other places where we have a similar logic - e.g. `colexecutils/cancel_checker.go`.)

> Reviewed 7 of 7 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103866#-:-NWm3swz51FfA6j8RtaT:b7v5rkp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[`pkg/util/cancelchecker/cancel_checker.go` line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103866#-NWm3AnE6bNXkgrCagcg:-NWm3AnFE9AlIqgcDuzG:b-6ags85) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e3f34b56ccb8bf0e95d9529314238580be6ef87/pkg/util/cancelchecker/cancel_checker.go#L50)):*
> ```Go
> 			atomic.StoreUint32(&done, 1)
> 		}); err != nil {
> 			panic(err)
> ```

nit: add a comment here that `err` could only be non-nil if `ctx.Done()` is nil which we know is false.

**Comment by miretskiy** [comment]
> I can add it to this PR if you prefer.

added.

**Review by yuzefovich — APPROVED** [review]
:lgtm: thanks!

> Reviewed 14 of 14 files at r3, 18 of 19 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103866#-:-NWn0j0_4pMAXbxxMu0L:brfqlux)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[`pkg/util/ctxutil/context.go` line 35 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103866#gh-1211848289:-NWn-l_gBxr05VQ1nKCp:b-tz5944) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5d534c59ea6ae9254d951a9c81f4aea4d0094d/pkg/util/ctxutil/context.go#L35)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

@yuzefovich -- do you think I should allow this case -- like: you call whenDone when context is never done -- that's on you :) 
Alternatively, maybe add a method such as `MustInvokeWhenDone` -- which has this check and have regular "WhenDone" work with any context?
</blockquote></details>

Discussed offline, the current approach seems good to me.
___
*[`pkg/util/cancelchecker/cancel_checker_test.go` line 44 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/103866#-NWn0_wX6sCXIA0rt1B7:-NWn0_wX6sCXIA0rt1B8:b-1tby8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e511f7306f167311179742c57d749296237a5eab/pkg/util/cancelchecker/cancel_checker_test.go#L44)):*
> ```Go
> }
> 
> // Old implementation:
> ```

nit: I'd extract this comment from the code into the commit message (I don't think we usually put things like this into the code).

**Comment by miretskiy** [comment]
> nit: I'd extract this comment from the code into the commit message (I don't think we usually put things like this into the code).

done

**Comment by shermanCRL** [comment]
I’d be interested @yuzefovich to know if this would be a visible improvement in SQL performance? Any sort of macro benchmark that may be interesting?

**Comment by miretskiy** [comment]
Yeah; the overall change is not great; colexec calls to CheckEvery might have been more expensive... but still, it's hard to see those if you're talking seconds.  A solid maybe :)

**Comment by shermanCRL** [comment]
If you don’t foresee visible macro improvements, doesn’t sound like a good use of your time @yuzefovich! Just curious. If it were in a hot loop the answer might be different. Thanks.

**Comment by yuzefovich** [comment]
Interestingly, this seems to lead to an increase in allocations which actually increases the latency on the hot path:
```
yuzefovich@gceworker-yuzefovich:~/go/src/github.com/cockroachdb/cockroach$ BENCHTIMEOUT=72h PKG=./pkg/sql/flowinfra BENCHES=BenchmarkFlowSetup ./scripts/bench HEAD~1 HEAD~0
Comparing HEAD~0 (new) with HEAD~1 (old)

Writing to /tmp/tmp.Y7b21cdmu3
Switching to HEAD~1
+ ./dev bench ./pkg/sql/flowinfra --timeout=72h --filter=BenchmarkFlowSetup --count=30 --bench-mem -v --stream-output --ignore-cache
Switching to HEAD~0
+ ./dev bench ./pkg/sql/flowinfra --timeout=72h --filter=BenchmarkFlowSetup --count=30 --bench-mem -v --stream-output --ignore-cache
name                                           old time/op    new time/op    delta
FlowSetup/vectorize=true/distribute=true-24       204µs ± 3%     210µs ± 4%  +2.89%  (p=0.000 n=28+27)
FlowSetup/vectorize=true/distribute=false-24      205µs ± 8%     209µs ± 8%  +2.22%  (p=0.008 n=26+26)
FlowSetup/vectorize=false/distribute=true-24      205µs ± 5%     210µs ± 6%  +2.57%  (p=0.000 n=29+30)
FlowSetup/vectorize=false/distribute=false-24     201µs ± 6%     206µs ± 3%  +2.70%  (p=0.000 n=28+27)

name                                           old alloc/op   new alloc/op   delta
FlowSetup/vectorize=true/distribute=true-24      24.8kB ±13%    25.2kB ±13%  +1.49%  (p=0.005 n=29+29)
FlowSetup/vectorize=true/distribute=false-24     23.6kB ±13%    23.4kB ±11%  -0.56%  (p=0.001 n=27+25)
FlowSetup/vectorize=false/distribute=true-24     28.7kB ±10%    28.9kB ±11%    ~     (p=0.842 n=28+29)
FlowSetup/vectorize=false/distribute=false-24    27.0kB ± 1%    27.0kB ± 1%    ~     (p=0.370 n=24+24)

name                                           old allocs/op  new allocs/op  delta
FlowSetup/vectorize=true/distribute=true-24         265 ±15%       273 ±14%  +2.81%  (p=0.001 n=30+30)
FlowSetup/vectorize=true/distribute=false-24        253 ±17%       253 ± 1%  +0.10%  (p=0.001 n=27+23)
FlowSetup/vectorize=false/distribute=true-24        262 ±10%       267 ±16%  +1.66%  (p=0.001 n=28+30)
FlowSetup/vectorize=false/distribute=false-24       246 ± 1%       247 ± 0%  +0.51%  (p=0.000 n=24+19)
```
(This is on 145bb3b7bfa6508e280421d8ad2a841f41e869df, and I manually modified `scripts/bench` to use 30 iterations instead of 10.)

**Comment by miretskiy** [comment]
Probably due to uint32* allocation. And that's because planner copied
canceler. If it's guaranteed that reset is called, this alloc can be removed

**Comment by knz** [comment]
> Interestingly, this seems to lead to an increase in allocations which actually increases the latency on the hot path:

Have we resolved this latency increase? I don't think this PR is bringing us forward if we keep this latency increase on the hot path.

Should I send a revert for this PR?

**Comment by miretskiy** [comment]
I reverted the change. Cancel checker is about 8x faster. But not 128x (or
1024x) faster

**Pull request merged**
