### PR TITLE
sqlmigrations: bake in old migrations

### PR DESCRIPTION
**Pull request by benesch**
"Bake in" migrations that existed in v1.0 and v1.1 by applying their
effect to the metadata schema. Since we require users to upgrade through
every major release, it is not necessary for v2.0 to include these
migrations; they will have been applied in the upgrade to v1.0 or v1.1.
Fresh v2.0 clusters, meanwhile, will be bootstrapped with a metadata
schema that includes the effect of these migrations.

@knz: can you review the removal of the "RepopulateViewDeps" function? The comment mentioned you might want it later for an "fsck" utility, but it doesn't seem to be used by today's SCRUB, so I removed it.

@bdarnell: are you okay with this?

@nvanbenschoten: this will spare you from needing to check whether the `system.jobs` table exists in https://github.com/cockroachdb/cockroach/pull/22337.

@a-robinson: if no one else reviews this in its entirely, can I toss this your way?

### CODE REVIEW

**Comment by bdarnell** [comment]
I'm generally OK with periodically baking in migrations like this, but I have some doubts about this. We require people to go through 1.1 to get to 2.0, but we don't require them to spend any particular amount of time there. If someone had been on 1.0, and upgrades to 1.1 and 2.0 in rapid succession, is there anything that guarantees that all the 1.1 migrations have run to completion before the upgrade?

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22358#-:-L4Yt49e2WyvgcxQnIFN:b-94ekwu)*

**Comment by benesch** [comment]
A v1.1 node won’t actually serve SQL traffic until all the v1.1 migrations
have completed. So it’s impossible to run `SET CLUSTER SETTING version =
‘v1.1’` unless all the v1.1 migrations have run.

**Comment by bdarnell** [comment]
OK, then I'm OK with this. (I'll leave it to other reviewers to give it a more detailed review and check that the new base schema is equivalent to the old migrations).

**Comment by knz** [comment]
@benesch ok to remove the view dep recomputation. If we need it again we can pull it back from the git history.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22358#-:-L4c5WNrlmogps0A4R4Q:bipfy8f)*

**Comment by nvanbenschoten** [comment]
:lgtm:

A decent amount of knowledge is required to determine which migrations are baked in into each version. We should probably document this information on all existing and new migrations. For example:
```
// Introduced in v2.0.
// Baked into v2.1.
```

---

Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 7 of 7 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22358#-:-L4gBe3B1hkiT66C1yA2:b-uppr67)*

**Comment by a-robinson** [comment]
All changes in the `sqlmigrations` package :lgtm: 

---

Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 3 of 7 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sqlmigrations/migrations.go, line 283 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22358#-L4gQL9NnvfL80GKksN8:-L4gQL9NnvfL80GKksN9:bs9ihzd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e9dd38d49fb8b3841cf3bcce5076c38b7fa8be6/pkg/sqlmigrations/migrations.go#L283)):*
> ```Go
> 	allMigrationsCompleted := true
> 	for _, migration := range backwardCompatibleMigrations {
> 		if migration.workFn == nil {
> ```

Optional, but we could probably verify here whether the cluster has been properly upgraded through all the required versions. In what way will that fail today if we don't add any sort of check here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22358#-:-L4gQfbC2VMr6r0eetqD:bcnqbvi)*

**Comment by benesch** [comment]
Whew, ok, this is ready to go!

@nvanbenschoten I've annotated all the migrations as you suggested.

---

Review status: 2 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sqlmigrations/migrations.go, line 283 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22358#-L4gQL9NnvfL80GKksN8:-L4hF4n0hp6LPpXx7xp8:b-ezwka9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e9dd38d49fb8b3841cf3bcce5076c38b7fa8be6/pkg/sqlmigrations/migrations.go#L283)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Optional, but we could probably verify here whether the cluster has been properly upgraded through all the required versions. In what way will that fail today if we don't add any sort of check here?
</blockquote></details>

It's difficult to write such a check, because it's perfectly valid for certain subsets of the migrations to be unrun at a given version. E.g., new v2.0 clusters won't have run the "create system.jobs table" migration, because they'll have been bootstrapped with it.

You raise a good point, though: we need to bump the `BinaryMinimumSupportedVersion`. This will ensure that you literally can't start a v2.0 node unless you've upgraded through v1.1 first. I've sidecar'd a commit that does exactly that in this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22358#-:-L4louR-BvPGCX0Qjqs8:bebtfon)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 8 files at r5, 1 of 1 files at r6, 7 of 7 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22358#-:-L4m8nhz0UIQpGW2HK5x:bnfp4nl)*

**Pull request merged**
