### PR TITLE
server,storage: add server.consistency_check.{interval.panic_on_failure}

### PR DESCRIPTION
**Pull request by petermattis**
Replace the `CONSISTENCY_CHECK_{INTERVAL,PANIC_ON_FAILURE}` env vars
with `server.consistency_check.{interval.panic_on_failure}` cluster
settings.

See #17531

### CODE REVIEW

**Comment by bdarnell** [comment]
Interval part LGTM.

---

Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/settings/cluster/settings.go, line 595 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17853#-KsF0Xc_uyQwCFlWPwes:-KsF0XcaBJQV74f3sElB:b-rf2poj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0ec39f0d0acf9d1446310511f420502c0aaf19d/pkg/settings/cluster/settings.go#L595)):*
> ```Go
> 		"server.consistency_check.panic_on_failure",
> 		"causes the node to panic when it detects a range consistency check failure",
> 		false,
> ```

I know it's not new to this PR, but why doesn't this default to true? Why would you want to turn it off? (I think originally turning on panic mode would give you worse error messages, but that's changed now). I'd prefer to get rid of the non-panicking mode instead of introducing a setting for it. (there's a separate testing knob that tests can use). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17853#-:-KsF0IDB4cUbLol3a3Dc:bn3d3wj)*

**Comment by petermattis** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/settings/cluster/settings.go, line 595 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17853#-KsF0Xc_uyQwCFlWPwes:-KsF2Tr-ICDkrfwaEZYS:b-nybi9g) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0ec39f0d0acf9d1446310511f420502c0aaf19d/pkg/settings/cluster/settings.go#L595)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I know it's not new to this PR, but why doesn't this default to true? Why would you want to turn it off? (I think originally turning on panic mode would give you worse error messages, but that's changed now). I'd prefer to get rid of the non-panicking mode instead of introducing a setting for it. (there's a separate testing knob that tests can use). 
</blockquote></details>

The historical reason was that we were panicking too often. I'd be fine with always panicking on failure. 

PS I'm not seeing a testing knob for panic-on-failure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17853)*

**Comment by bdarnell** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/settings/cluster/settings.go, line 595 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17853#-KsF0Xc_uyQwCFlWPwes:-KsF37gVEXT-r3X-xOcv:b-hd961x) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0ec39f0d0acf9d1446310511f420502c0aaf19d/pkg/settings/cluster/settings.go#L595)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The historical reason was that we were panicking too often. I'd be fine with always panicking on failure. 

PS I'm not seeing a testing knob for panic-on-failure.
</blockquote></details>

It's StoreTestingKnobs.BadChecksumPanic.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17853)*

**Comment by petermattis** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/settings/cluster/settings.go, line 595 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17853#-KsF0Xc_uyQwCFlWPwes:-KsF3S8g8Fd4YoqKTgOq:brhsi9x) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0ec39f0d0acf9d1446310511f420502c0aaf19d/pkg/settings/cluster/settings.go#L595)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

It's StoreTestingKnobs.BadChecksumPanic.
</blockquote></details>

Ah, different spelling explained why I wasn't finding it.

PTAL

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17853)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/replica_command.go, line 2275 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17853#-KsF8HZQB4RP4akemEar:-KsF8HZQB4RP4akemEas:bmynmw3) ([raw file](https://github.com/cockroachdb/cockroach/blob/efe27582ee1bbd4802d60b373857db32f35105de/pkg/storage/replica_command.go#L2275)):*
> ```Go
> 	wg.Wait()
> 
> 	logFunc := log.Errorf
> ```

You can set `logFunc := log.Fatalf` here and remove the `else` block.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17853#-:-KsF8N3rrhYvFGlKoI6i:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/storage/replica_command.go, line 2275 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17853#-KsF8HZQB4RP4akemEar:-KsFMvtpDuPEe6Nx_0Ts:b-lpcvf9) ([raw file](https://github.com/cockroachdb/cockroach/blob/efe27582ee1bbd4802d60b373857db32f35105de/pkg/storage/replica_command.go#L2275)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

You can set `logFunc := log.Fatalf` here and remove the `else` block.
</blockquote></details>

That's not quite the same as it doesn't allow `BadChecksumPanic` to prevent a fatal error. I've changed this so that we set `logFunc = log.Errorf` in the if-block.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17853)*

**Pull request merged**
