### PR TITLE
catalog/*: rename implementations of descriptors

### PR DESCRIPTION
**Pull request by ajwerner**
This PR implements the renames outlined in https://github.com/cockroachdb/cockroach/pull/52519#issuecomment-678598468 with the additional change of renaming the `dbdesc` package to `databasedesc` for symmetry. 

It's a big change but it's completely mechanical. Take it or leave it.

### CODE REVIEW

**Review by thoszhang — COMMENTED** [review]
Is it bad that the `TestMessageToJSONBRoundTrip` tests are failing? We don't actually rely on those names being stable, right?

I kind of like the abbreviated names (`TableDesc`, etc.) because they look like the new package names, but I don't really care either way. I'll defer to Rohan who probably feels slightly more strongly.

**Comment by ajwerner** [comment]
The change messed up and renamed a protobuf field. I’m going to simply this a bit and not change the interface names and go back to dbdesc

**Comment by ajwerner** [comment]
Okay, I nixed the interface renames and reverted the `dbdesc`->`databasedesc` change. It should be less controversial now. I do worry that if I don't bors it tonight, it will be irritating to do it until at least tomorrow night.

**Review by rohany — APPROVED** [review]

**Review by thoszhang — APPROVED** [review]

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Pull request merged**
