### PR TITLE
kv, kvserver: add query locks command

### LINKED ISSUE #74833: kv: expose interface to query locks
Part of #67589.

In order to populate a virtual table to visualize which transactions are currently holding/waiting on locks in a database, we'll need to implement a new KV API request, `QueryLocksRequest`, to provide this interface.

Jira issue: CRDB-12287

### PR DESCRIPTION
**Pull request by AlexTalks**
This change adds a new KV API, `QueryLocks`, allowing a client to query
the state of a replica's lock table over a provided key span.  This
exposes the in-memory locks currently managed by Concurrency Control,
and is part of the work needed to implement #75541.

Resolves #74833.

Release note: None

Release justification: Low-risk new functionality.

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
It's exciting to see this all falling into place.

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-:-MxCfTdZ8QO16eRvT8FW:bjy6xka)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_read.go, line 373 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-MxCeDZ99EKnpc4ZJVs_:-MxCeDZ99EKnpc4ZJVsa:b-iv0dw3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4fec0e3087aa18bd7907ad6aadd42cc08b4f765/pkg/kv/kvserver/replica_read.go#L373)):*
> ```Go
> 			// and becomes the inclusive start key of what was read.
> 			header.Key = t.ResumeSpan.EndKey
> 		case *roachpb.QueryLocksResponse:
> ```

This function is used for optimistic evaluation of MVCC operations. It shouldn't apply to a metadata operation like `QueryLocksRequest`.
___
*[pkg/kv/kvserver/batcheval/cmd_query_locks.go, line 36 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-MxCewzE0hVj8A9NxsdK:-MxCewzE0hVj8A9NxsdL:b-qujk2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4fec0e3087aa18bd7907ad6aadd42cc08b4f765/pkg/kv/kvserver/batcheval/cmd_query_locks.go#L36)):*
> ```Go
> 	maxOffset time.Duration,
> ) {
> 	DefaultDeclareKeys(rs, header, req, latchSpans, lockSpans, maxOffset)
> ```

Do we want to acquire read latches across the key span being observed? I didn't think we needed to.
___
*[pkg/kv/kvserver/batcheval/cmd_query_locks.go, line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-MxCfMSf8F4vbT4sQ_Xe:-MxCfMSf8F4vbT4sQ_Xf:b2rq5yx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4fec0e3087aa18bd7907ad6aadd42cc08b4f765/pkg/kv/kvserver/batcheval/cmd_query_locks.go#L41)):*
> ```Go
> }
> 
> func QueryLocks(
> ```

We should add some kv-level testing for this request type.
___
*[pkg/roachpb/api.go, line 667 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-MxCeWK90eaVnPrZRr9V:-MxCeWK90eaVnPrZRr9W:b-jdmtyl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4fec0e3087aa18bd7907ad6aadd42cc08b4f765/pkg/roachpb/api.go#L667)):*
> ```Go
> 
> // Method implements the Request interface.
> func (*QueryLocksRequest) Method() Method { return QueryLocks }
> ```

We'll want to implement the `combinable` interface for this type earlier in this file so that requests that are split on range boundaries can have their responses merged back together.

**Review by AlexTalks — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76998)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks and @nvanbenschoten)

___
*[pkg/kv/kvserver/batcheval/cmd_query_locks.go, line 36 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-MxCewzE0hVj8A9NxsdK:-Mxk4peu5lqdyJ8TmJaK:bmdblqc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4fec0e3087aa18bd7907ad6aadd42cc08b4f765/pkg/kv/kvserver/batcheval/cmd_query_locks.go#L36)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we want to acquire read latches across the key span being observed? I didn't think we needed to.
</blockquote></details>

Perhaps not necessary, but is there any reason we might want to?  Perhaps to not race with operations on these keys that may acquire locks?  But let me know if we think this feature shouldn't attempt to block that during evaluation...
___
*[pkg/kv/kvserver/batcheval/cmd_query_locks.go, line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-MxCfMSf8F4vbT4sQ_Xe:-MxkBPAs-NTDKO9NZ-bp:b7faqry) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4fec0e3087aa18bd7907ad6aadd42cc08b4f765/pkg/kv/kvserver/batcheval/cmd_query_locks.go#L41)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We should add some kv-level testing for this request type.
</blockquote></details>

Working - should finish this shortly

**Review by AlexTalks — COMMENTED** [review]
> Reviewed 6 of 23 files at r4, 10 of 17 files at r5, 6 of 10 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76998)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks and @nvanbenschoten)

**Review by AlexTalks — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76998)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks and @nvanbenschoten)

___
*[pkg/kv/kvserver/client_split_test.go, line 403 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-Mxr27mLAAR75rdQZNLO:-Mxr27mM4ec8pHH2nvHK:b-hzpgro) ([raw file](https://github.com/cockroachdb/cockroach/blob/4142cbf0b9faa38583e34f2c6069ba3e8d528164/pkg/kv/kvserver/client_split_test.go#L403)):*
> ```Go
> // create transactions that hold locks on keys across the ranges, and then
> // utilize the QueryLocks API to validate the exposed lock table information.
> func TestStoreRangeSplitAndQueryLocks(t *testing.T) {
> ```

FYI, Still not entirely sure this is the correct place for this test, especially because it feels like it's using different approaches to the KV APIs (I.e. most things in this module use a `Store` / `store.TestSender()`, whereas what we want to test is sending a batch with `QueryLocksRequest` using the `DistSender`).  I think this test does work properly, but please let me know if it should be moved and/or cleaned up at all!

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 4 of 17 files at r5, 3 of 10 files at r6, 1 of 3 files at r7, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-:-My82JNuEZGTPNcXuvFJ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @AlexTalks)

___
*[pkg/kv/kvserver/client_split_test.go, line 403 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-Mxr27mLAAR75rdQZNLO:-My80zDK0rIeM1J0YsYk:b-4ld5ws) ([raw file](https://github.com/cockroachdb/cockroach/blob/4142cbf0b9faa38583e34f2c6069ba3e8d528164/pkg/kv/kvserver/client_split_test.go#L403)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

FYI, Still not entirely sure this is the correct place for this test, especially because it feels like it's using different approaches to the KV APIs (I.e. most things in this module use a `Store` / `store.TestSender()`, whereas what we want to test is sending a batch with `QueryLocksRequest` using the `DistSender`).  I think this test does work properly, but please let me know if it should be moved and/or cleaned up at all!
</blockquote></details>

I think this is a fine place for the test.

But CI is indicating that the test is flaky. We may just need to bump the 10ms up to `testutils.DefaultSucceedsSoonDuration`. Or remove the manual timeout entirely and defer to the test's timeout. That's what you did in the other test.
___
*[pkg/kv/kvserver/replica_test.go, line 11250 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-My81rFOB-BPc3tPNGV7:-My81rFOB-BPc3tPNGV8:b-1hhwv8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4142cbf0b9faa38583e34f2c6069ba3e8d528164/pkg/kv/kvserver/replica_test.go#L11250)):*
> ```Go
> 			require.Equal(t, roachpb.Key("a"), lockInfo.Key)
> 			require.NotNil(t, lockInfo.LockHolder, "expected lock to be held")
> 			if !lockInfo.LockHolder.ID.Equal(txn.ID) || !lockInfo.LockHolder.WriteTimestamp.Equal(txn.WriteTimestamp) {
> ```

minor nit: any reason to not use a pair of `require.Equal` calls here (and below)?

**Review by andreimatei — CHANGES_REQUESTED** [review]
:LGTM: mod the deadlines in one of the tests

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-:-My8DHACCfKnnQXJwc4d:b1cvokd)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @AlexTalks)

___
*[pkg/kv/kvserver/concurrency/concurrency_control.go, line 467 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-My8AXn-0WNpM5NzSCnB:-My8AXn-0WNpM5NzSCnC:b-sirol6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4142cbf0b9faa38583e34f2c6069ba3e8d528164/pkg/kv/kvserver/concurrency/concurrency_control.go#L467)):*
> ```Go
> 	ResumeReason    roachpb.ResumeReason
> 	ResumeNextBytes int64
> 	TotalBytes      int64
> ```

please comment this new field, and also on `ResumeNextBytes`
___
*[pkg/roachpb/api.proto, line 1118 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-My88TJU9JTf7tK6mQGa:-My88TJU9JTf7tK6mQGb:bc1lw3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/4142cbf0b9faa38583e34f2c6069ba3e8d528164/pkg/roachpb/api.proto#L1118)):*
> ```protobuf
> 
> // A QueryLocksRequest is arguments to the QueryLocks() method.  It requests
> // the state of the locks held in the lock table over the given key span,
> ```

consider putting some words here about what locks are in the lock table and what locks aren't
___
*[pkg/roachpb/api.proto, line 1125 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-My88ncC54A2uR8zc--3:-My88ncD7-NKemOuupOJ:b-di2ils) ([raw file](https://github.com/cockroachdb/cockroach/blob/4142cbf0b9faa38583e34f2c6069ba3e8d528164/pkg/roachpb/api.proto#L1125)):*
>   // for example in the case of an unreplicated lock.

I think this "for example" is confusing. If you want to say anything, I think you need to say more to make the connection with replicated vs unreplicated locks; you could say that replicated locks are not part of the lock table if they were never contended. I think you should also say that only locks in the lock table are returned, regardless of this flag (right?).
___
*[pkg/kv/kvserver/client_split_test.go, line 403 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-My8BhCND5OnnE8JFO1O:-My8BhCND5OnnE8JFO1P:b7a4d86) ([raw file](https://github.com/cockroachdb/cockroach/blob/4142cbf0b9faa38583e34f2c6069ba3e8d528164/pkg/kv/kvserver/client_split_test.go#L403)):*
> ```Go
> // create transactions that hold locks on keys across the ranges, and then
> // utilize the QueryLocks API to validate the exposed lock table information.
> func TestStoreRangeSplitAndQueryLocks(t *testing.T) {
> ```

nit: make the name of this test start with `TestQueryLocks`. Maybe `TestQueryLocksAcrossRanges`. The fact that this test "does splits" is not very relevant.
___
*[pkg/kv/kvserver/client_split_test.go, line 403 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-Mxr27mLAAR75rdQZNLO:-My8BilS0M4Uaocypby8:b-q8kw84) ([raw file](https://github.com/cockroachdb/cockroach/blob/4142cbf0b9faa38583e34f2c6069ba3e8d528164/pkg/kv/kvserver/client_split_test.go#L403)):*
> I think this is a fine place for the test.

+1
___
*[pkg/kv/kvserver/client_split_test.go, line 412 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-My8By6fCpbjRw9HCfI5:-My8By6fCpbjRw9HCfI6:bgk4one) ([raw file](https://github.com/cockroachdb/cockroach/blob/4142cbf0b9faa38583e34f2c6069ba3e8d528164/pkg/kv/kvserver/client_split_test.go#L412)):*
> ```Go
> 			Store: &kvserver.StoreTestingKnobs{
> 				DisableMergeQueue: true,
> 				DisableSplitQueue: true,
> ```

how come `DisableSplitQueue` is needed? Consider commenting.
___
*[pkg/kv/kvserver/client_split_test.go, line 480 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-My8ClRQ83Jkxwulwmil:-My8ClRQ83Jkxwulwmim:b3ydgpq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4142cbf0b9faa38583e34f2c6069ba3e8d528164/pkg/kv/kvserver/client_split_test.go#L480)):*
> ```Go
> 	case err := <-scanRes:
> 		t.Fatalf("scan did not wait on locks, returned err %v", err)
> 	case <-time.After(10 * time.Millisecond):
> ```

Is this assuming that the scan will block in 10ms? This seems like a recipe for flakiness. Let's use some sort of a knob to get notified when the scan blocks.
___
*[pkg/kv/kvserver/client_split_test.go, line 529 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-My8D6Ax1SJABF79eUCC:-My8D6Ax1SJABF79eUCD:b9lbj0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4142cbf0b9faa38583e34f2c6069ba3e8d528164/pkg/kv/kvserver/client_split_test.go#L529)):*
> ```Go
> 	case err := <-scanRes:
> 		require.NoError(t, err, "txn3.Scan() should have finished without error after txns unlock")
> 	case <-time.After(10 * time.Millisecond):
> ```

I would make this deadline a lot larger, or remove it completely.

**Review by AlexTalks — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76998)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @AlexTalks, @andreimatei, and @nvanbenschoten)

___
*[pkg/kv/kvserver/concurrency/concurrency_control.go, line 467 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-My8AXn-0WNpM5NzSCnB:-My8F0nN5BpuNbxBnYVK:b6sb4s3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4142cbf0b9faa38583e34f2c6069ba3e8d528164/pkg/kv/kvserver/concurrency/concurrency_control.go#L467)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

please comment this new field, and also on `ResumeNextBytes`
</blockquote></details>

Will do - sg
___
*[pkg/roachpb/api.proto, line 1125 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-My88ncC54A2uR8zc--3:-My8F3Jy7Hp7xeTSw3un:b6sb4s3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4142cbf0b9faa38583e34f2c6069ba3e8d528164/pkg/roachpb/api.proto#L1125)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

>   // for example in the case of an unreplicated lock.

I think this "for example" is confusing. If you want to say anything, I think you need to say more to make the connection with replicated vs unreplicated locks; you could say that replicated locks are not part of the lock table if they were never contended. I think you should also say that only locks in the lock table are returned, regardless of this flag (right?).
</blockquote></details>

Will do - sg
___
*[pkg/kv/kvserver/client_split_test.go, line 403 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-My8BhCND5OnnE8JFO1O:-My8F6WmDHuasVeAChkG:b6sb4s3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4142cbf0b9faa38583e34f2c6069ba3e8d528164/pkg/kv/kvserver/client_split_test.go#L403)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: make the name of this test start with `TestQueryLocks`. Maybe `TestQueryLocksAcrossRanges`. The fact that this test "does splits" is not very relevant.
</blockquote></details>

Will do - sg
___
*[pkg/kv/kvserver/client_split_test.go, line 412 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-My8By6fCpbjRw9HCfI5:-My8EvRYE8QfdMLhm4I5:b-bplhck) ([raw file](https://github.com/cockroachdb/cockroach/blob/4142cbf0b9faa38583e34f2c6069ba3e8d528164/pkg/kv/kvserver/client_split_test.go#L412)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

how come `DisableSplitQueue` is needed? Consider commenting.
</blockquote></details>

This was definitely cargo-culting, heh.  It is likely unnecessary, can remove.
___
*[pkg/kv/kvserver/client_split_test.go, line 480 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-My8ClRQ83Jkxwulwmil:-My8FA6BAsdCjH-c7iKU:b-wybrg3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4142cbf0b9faa38583e34f2c6069ba3e8d528164/pkg/kv/kvserver/client_split_test.go#L480)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Is this assuming that the scan will block in 10ms? This seems like a recipe for flakiness. Let's use some sort of a knob to get notified when the scan blocks.
</blockquote></details>

Do we have a knob that I can use to get a signal?
___
*[pkg/kv/kvserver/client_split_test.go, line 529 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-My8D6Ax1SJABF79eUCC:-My8FKxiBoEIBHXp_kCu:b6sb4s3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4142cbf0b9faa38583e34f2c6069ba3e8d528164/pkg/kv/kvserver/client_split_test.go#L529)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I would make this deadline a lot larger, or remove it completely.
</blockquote></details>

Will do - sg
___
*[pkg/kv/kvserver/replica_test.go, line 11250 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-My81rFOB-BPc3tPNGV7:-My8FS5F28V4hpJbATIM:b-6jyidr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4142cbf0b9faa38583e34f2c6069ba3e8d528164/pkg/kv/kvserver/replica_test.go#L11250)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

minor nit: any reason to not use a pair of `require.Equal` calls here (and below)?
</blockquote></details>

Not really, can change

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76998)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @AlexTalks, @andreimatei, and @nvanbenschoten)

___
*[pkg/kv/kvserver/client_split_test.go, line 480 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-My8ClRQ83Jkxwulwmil:-My8LzLB9wIhWe74mB8v:b-b9wdts) ([raw file](https://github.com/cockroachdb/cockroach/blob/4142cbf0b9faa38583e34f2c6069ba3e8d528164/pkg/kv/kvserver/client_split_test.go#L480)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

Do we have a knob that I can use to get a signal?
</blockquote></details>

I don't see anything in the lock table; I think we should add something.
Alternatively, we could install a `RequestFilter` and watch for a `PushTxn` I guess, although the push is not immediate (but I think there's a knob you can use to make it immediate).
Or, you could record the trace of the respective request and poll it periodically to see if there's some event (or, with #74878, some tag) about the lock. We could also introduce a trace-based notification system for such tests.

Btw, if this patch needs to go in today, feel free to merge as is if you'll clean up later.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76998)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @AlexTalks, @andreimatei, and @nvanbenschoten)

___
*[pkg/kv/kvserver/client_split_test.go, line 480 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-My8ClRQ83Jkxwulwmil:-My98KbhB4SyeTgnBpM5:b-hun1c7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4142cbf0b9faa38583e34f2c6069ba3e8d528164/pkg/kv/kvserver/client_split_test.go#L480)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't see anything in the lock table; I think we should add something.
Alternatively, we could install a `RequestFilter` and watch for a `PushTxn` I guess, although the push is not immediate (but I think there's a knob you can use to make it immediate).
Or, you could record the trace of the respective request and poll it periodically to see if there's some event (or, with #74878, some tag) about the lock. We could also introduce a trace-based notification system for such tests.

Btw, if this patch needs to go in today, feel free to merge as is if you'll clean up later.
</blockquote></details>

actually, there is a `lockTableWaiterImpl.onContentionEvent` that might be useful

**Review by AlexTalks — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76998)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/kvserver/concurrency/concurrency_control.go, line 467 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-My8AXn-0WNpM5NzSCnB:-My95XPh4WU5FAtziI3U:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4142cbf0b9faa38583e34f2c6069ba3e8d528164/pkg/kv/kvserver/concurrency/concurrency_control.go#L467)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

Will do - sg
</blockquote></details>

Done.
___
*[pkg/roachpb/api.proto, line 1118 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-My88TJU9JTf7tK6mQGa:-My98HakBZXkSsvBfNsD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4142cbf0b9faa38583e34f2c6069ba3e8d528164/pkg/roachpb/api.proto#L1118)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

consider putting some words here about what locks are in the lock table and what locks aren't
</blockquote></details>

Done.
___
*[pkg/roachpb/api.proto, line 1125 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-My88ncC54A2uR8zc--3:-My98HzAAYwZ11piWaQc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4142cbf0b9faa38583e34f2c6069ba3e8d528164/pkg/roachpb/api.proto#L1125)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

Will do - sg
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/client_split_test.go, line 412 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-My8By6fCpbjRw9HCfI5:-My9EZT81x_1L6Yx-wyj:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4142cbf0b9faa38583e34f2c6069ba3e8d528164/pkg/kv/kvserver/client_split_test.go#L412)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

This was definitely cargo-culting, heh.  It is likely unnecessary, can remove.
</blockquote></details>

Done
___
*[pkg/kv/kvserver/client_split_test.go, line 480 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-My8ClRQ83Jkxwulwmil:-My9ArUhCU9iHizQOnag:b-l4jjna) ([raw file](https://github.com/cockroachdb/cockroach/blob/4142cbf0b9faa38583e34f2c6069ba3e8d528164/pkg/kv/kvserver/client_split_test.go#L480)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

actually, there is a `lockTableWaiterImpl.onContentionEvent` that might be useful
</blockquote></details>

ok cool - I'll stress it to make sure it's not flaking now but will plan to merge shortly.  Especially since the existing tests in `replica_test.go` seem to wait 5ms for operations to block on locks (though I realize that's a bit different since it's using the replica `Send` directly).
___
*[pkg/kv/kvserver/client_split_test.go, line 529 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-My8D6Ax1SJABF79eUCC:-My9BHMYEJWSi0tLtjCH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4142cbf0b9faa38583e34f2c6069ba3e8d528164/pkg/kv/kvserver/client_split_test.go#L529)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

Will do - sg
</blockquote></details>

Done.

**Review by AlexTalks — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76998)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/kvserver/client_split_test.go, line 480 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76998#-My8ClRQ83Jkxwulwmil:-My9cheECwwlu3lwoLNe:b-1gz2kg) ([raw file](https://github.com/cockroachdb/cockroach/blob/4142cbf0b9faa38583e34f2c6069ba3e8d528164/pkg/kv/kvserver/client_split_test.go#L480)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

ok cool - I'll stress it to make sure it's not flaking now but will plan to merge shortly.  Especially since the existing tests in `replica_test.go` seem to wait 5ms for operations to block on locks (though I realize that's a bit different since it's using the replica `Send` directly).
</blockquote></details>

Unfortunately (of course) `onContentionEvent` only gets called when the contention is resolved, not started.  I think the options are either to increase the wait time here or install a new event...

**Pull request merged**
