### PR TITLE
sql: mark use of Gossip as deprecated

### PR DESCRIPTION
**Pull request by tbg**
This commit wraps Gossip in a wrapper when it is used in SQL. This small
wrapper helpfully keeps track, in code, of work that needs to be done to
enable multi-tenancy, and ensures that any deprecated use of Gossip is
associated with a Github issue. The wrapper also makes sure we're not
introducing new dependencies on Gossip.

Release note: None

### CODE REVIEW

**Review by asubiotto — COMMENTED** [review]
> Reviewed 31 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47972)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[pkg/gossip/gossip.go, line 1621 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47972#-M5bwO8CCOkaozpP0IiV:-M5bwO8CCOkaozpP0IiW:b-b9zesd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0896b5cb7bfc2880c963c8dc6b3e24c536ce039/pkg/gossip/gossip.go#L1621)):*
> ```Go
> // MakeDeprecatedGossip initializes a DeprecatedGossip instance. See
> // MakeTenantSQLDeprecatedWrapper for details.
> func MakeDeprecatedGossip(g *Gossip, tenant bool) DeprecatedGossip {
> ```

What can we do about disallowing new uses of `Gossip`?
___
*[pkg/util/errorutil/tenant_deprecated_wrapper.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47972#-M5btXhq2dHyYGryrw0n:-M5btXhq2dHyYGryrw0o:bt6n65r) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0896b5cb7bfc2880c963c8dc6b3e24c536ce039/pkg/util/errorutil/tenant_deprecated_wrapper.go#L31)):*
> ```Go
> // be available in a SQL tenant server for the time being. Such calls may also
> // point at work items that may obviate the use of the wrapper in the future.
> func MakeTenantSQLDeprecatedWrapper(v interface{}, tenant bool) TenantSQLDeprecatedWrapper {
> ```

After reading this comment I'm still not 100% sure what the `tenant` boolean is specifying. I guess I'm confused by the "indicates whether the object is part of a SQL tenant server". What exactly does that mean? Based on the behavior below I guess it's whether the wrapped object is unavailable in a SQL tenant server? I think it might be clearer if you make the behavior more explicit e.g. `s/tenant/forceUnavailability`.

**Review by nvb — COMMENTED** [review]
> Reviewed 31 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47972)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @tbg)

___
*[pkg/gossip/gossip.go, line 1631 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47972#-M5cnZb56E5uSKJLO1r9:-M5cnZb56E5uSKJLO1rA:by56pk8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0896b5cb7bfc2880c963c8dc6b3e24c536ce039/pkg/gossip/gossip.go#L1631)):*
> ```Go
> //
> // See the comments on TenantSQLDeprecatedWrapper for details.
> type DeprecatedGossip struct {
> ```

nit: is `type DeprecatedGossip errorutil.TenantSQLDeprecatedWrapper` a cleaner pattern to start with these option types?
___
*[pkg/sql/distsql/server.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47972#-M5cnwycEApwi1SNhvPL:-M5cnwyd7EZ0pIdyAu5o:bsf9ozz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0896b5cb7bfc2880c963c8dc6b3e24c536ce039/pkg/sql/distsql/server.go#L51)):*
> ```Go
> const minFlowDrainWait = 1 * time.Second
> 
> const distSQLGossipIssueNo = 47900
> ```

nit: consider commenting with the URL so that it's easier to jump to.
___
*[pkg/util/errorutil/tenant.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47972#-M5ckeWx6EuCMx2Z9IrV:-M5ckeWx6EuCMx2Z9IrW:bl10dac) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0896b5cb7bfc2880c963c8dc6b3e24c536ce039/pkg/util/errorutil/tenant.go#L33)):*
> ```Go
> 		}
> 	}
> 	return errors.New("operation is unsupported in multi-tenancy mode" + buf.String())
> ```

nit: might as well avoid the string concatenation by pulling up a `buf.WriteString("operation is unsupported in multi-tenancy mode")`. That will also make this easier to read.
___
*[pkg/util/errorutil/tenant_deprecated_wrapper.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47972#-M5btXhq2dHyYGryrw0n:-M5clK0b0eYh5F3MXowW:b-fgscta) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0896b5cb7bfc2880c963c8dc6b3e24c536ce039/pkg/util/errorutil/tenant_deprecated_wrapper.go#L31)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

After reading this comment I'm still not 100% sure what the `tenant` boolean is specifying. I guess I'm confused by the "indicates whether the object is part of a SQL tenant server". What exactly does that mean? Based on the behavior below I guess it's whether the wrapped object is unavailable in a SQL tenant server? I think it might be clearer if you make the behavior more explicit e.g. `s/tenant/forceUnavailability`.
</blockquote></details>

I agree. After reading this file, I'm still not sure I understand the difference between `tenant` and `v == nil`. Is there one? Is the idea that we'll still keep providing dependencies even when in a SQL tenant server, but we'll slowly get rid of calls to `Deprecated` which use them and only then will the difference be immaterial?

I'd also consider inverting the condition so that the zero value of this struct can be used to indicate that the optional value is not present.
___
*[pkg/util/errorutil/tenant_deprecated_wrapper.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47972#-M5cleha2bxke6HE9nzQ:-M5clehb147ITnqBR1Il:b-dj6fkd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0896b5cb7bfc2880c963c8dc6b3e24c536ce039/pkg/util/errorutil/tenant_deprecated_wrapper.go#L50)):*
> ```Go
> // A list of related issues can optionally be provided, in case there is a
> // desire to make the functionality available to tenants in the future.
> func (w TenantSQLDeprecatedWrapper) Optional(issueNos ...int) (interface{}, error) {
> ```

Do we want a second form of this that return a boolean instead of an error when the dependency is not provided? I'd hate for us to feel like we can't add conditional logic in hot paths due to the cost of calling this method.

**Comment by tbg** [comment]
The value is always provided for the system tenant (tenant=false) to enable
the optional features like crdb_internal.
In other tenants, it has to be provided for now because there are still
calls to Deprecated() left. When those are gone, we can use a nil Gossip
here. (And can rename DeprecatedGossip to Optional gossip, hiding the
Deprecated method, and remove the bool as well (replace with g==nil).

Does that make sense? Open to suggestions for making that clearer. I can
improve verbiage in the code tomorrow but if there's a different approach
I'm happy to consider it too.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47972)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @nvanbenschoten)

___
*[pkg/gossip/gossip.go, line 1621 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47972#-M5bwO8CCOkaozpP0IiV:-M5f_0SX-zcM8A7dTaeG:bery7ua) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0896b5cb7bfc2880c963c8dc6b3e24c536ce039/pkg/gossip/gossip.go#L1621)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What can we do about disallowing new uses of `Gossip`?
</blockquote></details>

I don't think we need to do more. If you wanted to use Gossip, you would have to get it from the DeprecatedGossip, and it will pretty much force you to realize that you are setting yourself up for failure unless the new use is optional (and even then, it cautions you away from it). Did you have something else in mind or do you think this isn't enough?
___
*[pkg/gossip/gossip.go, line 1631 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47972#-M5cnZb56E5uSKJLO1r9:-M5fdONo2jBJEN_Pz47d:bsc8tgj) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0896b5cb7bfc2880c963c8dc6b3e24c536ce039/pkg/gossip/gossip.go#L1631)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: is `type DeprecatedGossip errorutil.TenantSQLDeprecatedWrapper` a cleaner pattern to start with these option types?
</blockquote></details>

When I first read this suggestion I thought so, but I'm less sure now. It allows you to cast back to the wrapper type, which has the `Deprecated` method which I want to remove from DeprecatedGossip as soon as I can. Theoretical concern, but it's a concern and I don't see anything in the other choice that would outweigh it.
___
*[pkg/util/errorutil/tenant_deprecated_wrapper.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47972#-M5btXhq2dHyYGryrw0n:-M5fe9_M8kaZogkVdzk0:b-if4gfg) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0896b5cb7bfc2880c963c8dc6b3e24c536ce039/pkg/util/errorutil/tenant_deprecated_wrapper.go#L31)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I agree. After reading this file, I'm still not sure I understand the difference between `tenant` and `v == nil`. Is there one? Is the idea that we'll still keep providing dependencies even when in a SQL tenant server, but we'll slowly get rid of calls to `Deprecated` which use them and only then will the difference be immaterial?

I'd also consider inverting the condition so that the zero value of this struct can be used to indicate that the optional value is not present.
</blockquote></details>

I re-worked the commentary to (hopefully) clear this confusion up for all future readers. WDYT?
___
*[pkg/util/errorutil/tenant_deprecated_wrapper.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47972#-M5cleha2bxke6HE9nzQ:-M5fiURC2mxgQyy-3ANS:b-74njhu) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0896b5cb7bfc2880c963c8dc6b3e24c536ce039/pkg/util/errorutil/tenant_deprecated_wrapper.go#L50)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we want a second form of this that return a boolean instead of an error when the dependency is not provided? I'd hate for us to feel like we can't add conditional logic in hot paths due to the cost of calling this method.
</blockquote></details>

I added it but I don't really like it. These are harder to track, and they allow inconsistent errors of the form

```
if g, ok := w.Optional(); !ok {
  return errors.New("thing I wanted is missing")
}
```

That said, you're probably right that we'll see something pop up in the hot path that actually needs to stick around. I'll leave it in and we can revisit. When we give the NodeID a similar treatment (﻿﻿﻿https://github.com/cockroachdb/cockroach/issues/48009) we'll probably need it.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 6 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47972#-:-M5uolME8WGv6gOOuBPU:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @nvanbenschoten, and @tbg)

___
*[pkg/gossip/gossip.go, line 1621 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47972#-M5bwO8CCOkaozpP0IiV:-M5ulDLc5aupBG4l1c1A:bb73djm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0896b5cb7bfc2880c963c8dc6b3e24c536ce039/pkg/gossip/gossip.go#L1621)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I don't think we need to do more. If you wanted to use Gossip, you would have to get it from the DeprecatedGossip, and it will pretty much force you to realize that you are setting yourself up for failure unless the new use is optional (and even then, it cautions you away from it). Did you have something else in mind or do you think this isn't enough?
</blockquote></details>

SGTM

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 10 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47972#-:-M5wDCGm1gLCv4B9i8-A:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @asubiotto, @nvanbenschoten, and @tbg)

**Comment by tbg** [comment]
TFTRs!

bors r=asubiotto,nvanbenschoten

**Pull request merged**
