### PR TITLE
kv: permit ExportRequest evaluation on followers

### LINKED ISSUE #67016: kvserver: no sync between splits and follower reads can cause invalid reads
On leaseholders, latches provide serialization between different classes of operation. On followers, however, latches don't provide the same protection, because requests that are simply applied on a follower don't take latches. Follower reads do take latches, but I think that's by accident and useless given that writes don't take their latches.
At the very least, the following scenario involving a follower read and a split applying concurrently seems possible:

1. follower read across all of range begins, checks range descriptor
2. range split applies
3. RHS range gets removed
4. follower read misses RHS keys

In addition to latches, reads also take read locks on `readOnlyCmdMu`. Some range-level operations also take this lock, so the lock acts as a kind of structural synchronization. For example, I think removing a replica takes this lock (since https://github.com/cockroachdb/cockroach/pull/64324). Applying a split, however, does not. Maybe it should?

Alternatively, I think if step 1) in the scenario instead read "follower read across all of range begins, binds Pebble snapshot, checks range descriptor", then I think the hazard would be avoided because the "checking of the range descriptor" would provide sufficient synchronization with the split. Currently, reads don't bind their Pebble snapshot early (#55461), but I believe they could easily do it now that we have #66845. If we could bind the snapshot early, we could order it before a range descriptor check.

Besides this particular split/follower-read scenario, it seems to me that the topic of latches on followers should be explored. If the latches taken by follower-reads are not useful, we shouldn't take them. The evaluation of requests accesses both MVCC data and also in-memory range state. Access to this state is supposed to be made safe by latches, as asserted by `SpanSetReplicaEvalContext`. On followers, I think `SpanSetReplicaEvalContext` does not provide the guarantees that it thinks it does, which suggests that follower-reads should only have access to a much-reduced `EvalContext` which doesn't allow access to the range's in-memory state. Hopefully this would be sufficient for the limited set of requests that we evaluate on followers.

### LINKED ISSUE #88804: kv: permit Export request evaluation on follower replicas
Now that non-transactional batches of "transactional" read-only requests (get, scan, revscan, refresh) can be served by followers (as of e024445), we have the opportunity to broaden the criteria to other forms of read-only requests. An import type of request that we should allow to evaluate on follower replicas is `ExportRequest`.

This comes with three main benefits:
1. `backupDataProcessor`s won't start performing remote Export RPCs if leaseholders move during execution
2. Backup can plan `backupDataProcessor`s near follower replicas to spread out load if physical planning finds a leaseholder imbalance
3. Backups can more flexibly react to overload by shifting some load away from overloaded leaseholders

We probably don't want to do this until we address https://github.com/cockroachdb/cockroach/issues/67016.

Jira issue: CRDB-20007

### PR DESCRIPTION
**Pull request by arulajmani**
Now that we've fixed #67016, and follower reads correctly synchronize with concurrent splits, it's safe for us to serve ExportRequests from followers. This patch permits that.

Closes #88804

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
Nice!

@dt do you think there are any other backup-level tests that should be updated or added now that this is supported? Are there any tests that you would expect this change to have an impact on? For instance, should we be able to see the impact of this on intra-cluster network transfer in a long-running backup roachtest (where leases may move after the backup is planned)?

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91405#-:-NGIWnv04gNWz1djKZmu:bivepa2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/replica_follower_read.go` line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91405#-NGIUyHC7pnJ2cYi1ukO:-NGIUyHD3CqqHuDx0JiU:b-zczbir) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c460c5b8d83d73c7f38c4f32974cfff3e4a550a/pkg/kv/kvserver/replica_follower_read.go#L46)):*
> ```Go
> 	//    read, then the batch might miss past writes served at higher timestamps
> 	//    on the leaseholder.
> 	// 2. Each request in the batch needs to have clearly defined semantics when
> ```

small nit: If we're going to capitalize this sentence, let's do it for all of these conditions.
___
*[`pkg/kv/kvserver/replica_follower_read.go` line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91405#-NGIV7Dm269Fsw8xjrYO:-NGIV7Dm269Fsw8xjrYP:b1cxj4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c460c5b8d83d73c7f38c4f32974cfff3e4a550a/pkg/kv/kvserver/replica_follower_read.go#L48)):*
> ```Go
> 	// 2. Each request in the batch needs to have clearly defined semantics when
> 	//    served under the closed timestamp. This includes all "transactional"
> 	//    requests and ExportRequests (which are non-transactional).
> ```

"which are non-transactional but which define a start and end timestamp"
___
*[`pkg/roachpb/batch.go` line 195 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91405#-NGIVRx97YHN3OGnBnjJ:-NGIVRx97YHN3OGnBnjK:bgrx8vf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c460c5b8d83d73c7f38c4f32974cfff3e4a550a/pkg/roachpb/batch.go#L195)):*
> ```Go
> }
> 
> // IsAllTransactionalOrExportRequests returns true iff every request in the
> ```

Is this condition applicable more broadly than to just `BatchCanBeEvaluatedOnFollower`? If not, consider inlining it into `BatchCanBeEvaluatedOnFollower`. It might look like:
```go
...
if tsFromServerClock {
	return false
}
for _, ru := range ba.Requests {
	r := ru.GetInner()
	switch {
	case roachpb.IsTransactional(r):
		// TODO: explain
		if !roachpb.IsReadOnly(r) || roachpb.IsLocking(r) {
			return false
		}
	case r.Method() == roachpb.Export:
		// TODO: explain
	default:
		return false
	}
}
return true
```

**Review by arulajmani — COMMENTED** [review]
Sorry for taking so long to get to the review comments; updated, PTAL. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91405#-:-NIelAanACgctcFckM-C:bbg99v5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/replica_follower_read.go` line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91405#-NGIUyHC7pnJ2cYi1ukO:-NIejn2M2R3RtTcCI2uO:b-spgkkh) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c460c5b8d83d73c7f38c4f32974cfff3e4a550a/pkg/kv/kvserver/replica_follower_read.go#L46)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

small nit: If we're going to capitalize this sentence, let's do it for all of these conditions.
</blockquote></details>

No longer applies because I moved the explanation in-line. Let me know if you prefer otherwise. 
___
*[`pkg/roachpb/batch.go` line 195 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91405#-NGIVRx97YHN3OGnBnjJ:-NIejjN_4rEOxg7ZafHI:b-etjaav) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c460c5b8d83d73c7f38c4f32974cfff3e4a550a/pkg/roachpb/batch.go#L195)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this condition applicable more broadly than to just `BatchCanBeEvaluatedOnFollower`? If not, consider inlining it into `BatchCanBeEvaluatedOnFollower`. It might look like:
```go
...
if tsFromServerClock {
	return false
}
for _, ru := range ba.Requests {
	r := ru.GetInner()
	switch {
	case roachpb.IsTransactional(r):
		// TODO: explain
		if !roachpb.IsReadOnly(r) || roachpb.IsLocking(r) {
			return false
		}
	case r.Method() == roachpb.Export:
		// TODO: explain
	default:
		return false
	}
}
return true
```
</blockquote></details>

Good call, this is much cleaner.

**Review by nvb — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91405)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/replica_follower_read.go` line 68 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/91405#-NIepdZ05YzjqED44qHs:-NIepdZ05YzjqED44qHt:bgc8v9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/f41c070d34a6a65066fc2ebc851e7b3b39c4a3a6/pkg/kv/kvserver/replica_follower_read.go#L68)):*
> ```Go
> 			// leaseholder.
> 			// Explanation of conditions required for a batch to be considered for
> 			// follower evaluation are defined inline.
> ```

```
Explanation of conditions required for a batch to be considered for follower evaluation are defined inline.
```
What is this sentence intending to convey? Didn't you just explain these conditions above?
___
*[`pkg/kv/kvserver/replica_follower_read.go` line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/91405#-NIepuQg9s4NVUoXjt-e:-NIepuQg9s4NVUoXjt-f:b-1gzapd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f41c070d34a6a65066fc2ebc851e7b3b39c4a3a6/pkg/kv/kvserver/replica_follower_read.go#L74)):*
> ```Go
> 		case r.Method() == roachpb.Export:
> 		// Export requests also have clear semantics when served under the closed
> 		// timestamp as well, even though they aren't non-transactional, as they
> ```

"are non-transactional" or "aren't transactional"

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91405)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/replica_follower_read.go` line 68 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/91405#-NIepdZ05YzjqED44qHs:-NIer5XPE0b9owXRlAXC:b-htxio1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f41c070d34a6a65066fc2ebc851e7b3b39c4a3a6/pkg/kv/kvserver/replica_follower_read.go#L68)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

```
Explanation of conditions required for a batch to be considered for follower evaluation are defined inline.
```
What is this sentence intending to convey? Didn't you just explain these conditions above?
</blockquote></details>

Lol I think I accidentally pressed `p` here and I had that on my clipboard from before. Fixed. 
___
*[`pkg/kv/kvserver/replica_follower_read.go` line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/91405#-NIepuQg9s4NVUoXjt-e:-NIer52g3ay0NwJ5M8mt:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f41c070d34a6a65066fc2ebc851e7b3b39c4a3a6/pkg/kv/kvserver/replica_follower_read.go#L74)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"are non-transactional" or "aren't transactional"
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91405#-:-NIf28l-8ISwvvy6d3Q-:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by arulajmani** [comment]
TFTR! 

bors r=nvanbenschoten

**Pull request merged**
