### PR TITLE
indexrec: remove the overlap between equalCandidates, rangeCandidates and joinCandidates

### PR DESCRIPTION
**Pull request by qiyanghe1998**
#### indexrec: remove the overlap between equalCandidates, rangeCandidates and joinCandidates

When there is a join expression, the filter expression will be added to the
joinCandidates by the join cases in categorizeIndexCandidates(). Then, when
iterating its child nodes, the categorizeIndexCandidates() will be applied
again on the same filter expression, without join wrap, it will be added to the
equalCandidates or rangeCandidates.

    SELECT t1.i, t1.s
    FROM t1 JOIN t2
    ON t1.k = t2.k
    WHERE t1.i = 2 AND t1.s = 'NG'

Specifically, for the query above, previous implementation will make t1.k,
t1.i, t1.s added to the equalCandidates, and t1.k also added to the
joinCandidates. According to the rule 5 (EQ) introduced in candidate.go, we
will only get the index (i, s, k) after combination since they are from the
same table and appear in equality predicates. However, (i, s) is the index we
should get from combining equality predicates from t1. (i, s, k) should be
added from the rule 5 (EQ + J), (i, s) is from EQ and (k) is from the join
predicate. Therefore, the previous implementation will omit (i, s).

This commits updates the cases for all the joins with left child and right
child so that the filter expressions will not be processed again. For the
tests, I add two test cases for EQ + J under Multi-column combinations with
inner join.

Release note: None

Epic: None

#### indexrec: fix incorrect join attributes in geospatial tests

Release note (bug fix): Join expressions are incorrect (t2.k = t2.k, t2.k !=
t2.k), the first k should com from t1.

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
Great work! I think you need to add a line to the PR message that says "Epic: None" in order to satisfy the linter. Otherwise, I'm not sure why the CLA check is failing... you might want to ask in #dev-inf.

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103782#-:-NWEqNf5AMlsg2vl1DId:b6mp9hd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @qiyanghe1998)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103782#-NWEobR53c4rbYNi8shn):*
nit: categorizeIndeCandidates -> categorizeIndexCandidates
___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103782#-NWEpwEbBctBLrR0RLMW):*
Nice catch! Are there any regression tests you can add that will demonstrate that you've fixed this behavior? Or was that the purpose of changing `!=` to `=` in the tests?

**Comment by qiyanghe1998** [comment]
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103782#-NWEpwEbBctBLrR0RLMW):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Nice catch! Are there any regression tests you can add that will demonstrate that you've fixed this behavior? Or was that the purpose of changing `!=` to `=` in the tests?
</blockquote></details>

I thought that "!=" is not covered by the current implementation (which I will cover in my next PR). Yeah, you are right, I'd better not change any existing tests. I will recover all the existing tests and add some more to cover this fix (that are join involved EQ + J combination indexes).

**Review by mgartner — APPROVED** [review]
:lgtm: Nicely done!

> Reviewed 1 of 2 files at r1, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103782#-:-NWhILGL4AOmwqfFvdPi:b-msncp4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103782#-:-NWiNLbkDoG9XBKfDdq1:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @qiyanghe1998)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103782#-NWEpwEbBctBLrR0RLMW):*
<details><summary><i>Previously, qiyanghe1998 wrote…</i></summary><blockquote>

I thought that "!=" is not covered by the current implementation (which I will cover in my next PR). Yeah, you are right, I'd better not change any existing tests. I will recover all the existing tests and add some more to cover this fix (that are join involved EQ + J combination indexes).
</blockquote></details>

Thanks!

**Pull request merged**
