### PR TITLE
roachtest: add mixed-version restores to backup test

### LINKED ISSUE #96367: backupccl: write a mixed version restore test
We currently allow for mixed version table and database restores but we don't test them. We should by using https://github.com/cockroachdb/cockroach/pull/92431

Jira issue: CRDB-24160

Epic CRDB-20915

### PR DESCRIPTION
**Pull request by renatolabs**
This commit updates the `backup/mixed-version` (now
`backup-restore/mixed-version`) to also perform mixed-version
restores. At a high level, it introduces a new function that runs in
mixed-version state that will randomly attempt to restore a subset of
the backups taken up to that point during the test.

The test will verify that we are able to restore, in mixed version,
backups taken in the previous version _and_ in mixed version.

Resolves: https://github.com/cockroachdb/cockroach/issues/96367.

Epic: [CRDB-19321](https://cockroachlabs.atlassian.net/browse/CRDB-19321)

Release note: None

### CODE REVIEW

**Comment by renatolabs** [comment]
This is a stacked PR, please review them in order (but feel free to review the second or third ones before the first one is merged):

* #100754 
* #100755
* #101730 **(this PR)**

To be reviewed here: **the last commit**.

**Comment by renatolabs** [comment]
Rebased:

* ~#100754~ (merged!)
* ~#100755~ (merged!)
* #101730 **(this PR)**

To be reviewed here: **entire diff**.

**Comment by renatolabs** [comment]
@smg260 @herkolategan @srosenberg Friendly nudge 🙂

**Review by smg260 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101730)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/mixed_version_backup.go` line 986 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101730#-NUwXMRzAR01YhITLp96:-NUwXMRzAR01YhITLp97:b-cjxxq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9e1b90dfbe56ffe5deb8f552444f9f8a4c6349f/pkg/cmd/roachtest/tests/mixed_version_backup.go#L986)):*
> ```Go
> func (mvb *mixedVersionBackup) loadBackupData(
> 	ctx context.Context, l *logger.Logger, rng *rand.Rand, h *mixedversion.Helper,
> ) (err error) {
> ```

what's the point of a named return var if there are no naked returns in the function body?
___
*[`pkg/cmd/roachtest/tests/mixed_version_backup.go` line 1033 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101730#-NUwY9Lm5YZrETbCU-Xa:-NUwY9Lm5YZrETbCU-Xb:b-wgrcrn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9e1b90dfbe56ffe5deb8f552444f9f8a4c6349f/pkg/cmd/roachtest/tests/mixed_version_backup.go#L1033)):*
> ```Go
> 	// concurrently with this step) to store some data in the cluster by
> 	// the time the backup is taken.
> 	wait := 3 * time.Minute
> ```

Is this value based on some observation? It seems arbitrary, and the comment suggests it is dependent on workload init; perhaps more context as to why its run concurrently

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101730)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/mixed_version_backup.go` line 986 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101730#-NUwXMRzAR01YhITLp96:-NV-kwcu2wjrPJbbtHZn:b-m0mqen) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9e1b90dfbe56ffe5deb8f552444f9f8a4c6349f/pkg/cmd/roachtest/tests/mixed_version_backup.go#L986)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

what's the point of a named return var if there are no naked returns in the function body?
</blockquote></details>

This must have been a bad merge conflict resolution. Fixed, thanks.
___
*[`pkg/cmd/roachtest/tests/mixed_version_backup.go` line 1033 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101730#-NUwY9Lm5YZrETbCU-Xa:-NV-l0dH09rr40Erv5KJ:b-z9429e) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9e1b90dfbe56ffe5deb8f552444f9f8a4c6349f/pkg/cmd/roachtest/tests/mixed_version_backup.go#L1033)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

Is this value based on some observation? It seems arbitrary, and the comment suggests it is dependent on workload init; perhaps more context as to why its run concurrently
</blockquote></details>

Yeah, somewhat arbitrary. It's just a point in time when the workloads have loaded some (but likely not all) their initial data. IMO, taking the backup while the data is being inserted is kind of a test "feature" rather than a bug. We could add synchronization so that the backup is only after once all initial data has been loaded, but that adds complexity without an obvious gain.

I added more words to the comment to make the intention clearer, let me know if this helps.

**Review by smg260 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101730#-:-NV14r7y-Sgqb-6E2MMf:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan and @srosenberg)

**Review by herkolategan — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101730)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @srosenberg)

**Comment by renatolabs** [comment]
TFTRs!

bors r=smg260,herkolategan

**Pull request merged**
