### PR TITLE
server: Migrate nodes, {hot-,}ranges, health endpoints to v2 API

### PR DESCRIPTION
**Pull request by itsbilal**
This change adds API v2 compatible versions of the node list, range info
per node, ranges info across nodes, hot ranges, and health endpoints.
These endpoints all support API v2 header-based authentication,
pagination (if applicable), and only return relevant information
in the response payloads.

One part of https://github.com/cockroachdb/cockroach/issues/55947.

Release note (api change): Add these new HTTP API endpoints:
 - `/api/v2/nodes/`: Lists all nodes in the cluster
 - `/api/v2/nodes/<node_id>/ranges`: Lists all ranges on the specified node
 - `/api/v2/ranges/hot/`: Lists hot ranges in the cluster
 - `/api/v2/ranges/<range_id>/`: Describes range in more detail
 - `/api/v2/health/`: Returns an HTTP 200 response if node is healthy.

Release justification: Adds more HTTP API endpoints in parallel
 that do not touch existing code.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Thanks for this code

To ease future review and maintainability, I think it would be worthwhile to split each endpoint implementation into a different file, with the request/response structs at the top and the handler body underneath.

e.g. `api_v2_health.go`, `api_v2_ranges.go`, etc
(you could perhaps combine the two range endpoints inside the same file)

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60952#-:-MUIHP4p6-ioijBLc6Xr:bvkcmbr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal)

___
*[pkg/server/api.go, line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60952#-MUIGmG4AtmtCYjCi8at:-MUIGmG5Dx57omyJPlyo:blkh5bh) ([raw file](https://github.com/cockroachdb/cockroach/blob/8381c64c327326aaf4bb207253bd44b8cf9562b2/pkg/server/api.go#L113)):*
> ```Go
> 		{"nodes/", a.listNodes, true, adminRole, noOption},
> 		{"nodes/{node_id}/ranges/", a.listNodeRanges, true, regularRole, noOption},
> 		{"ranges/hot/", a.listHotRanges, true, regularRole, noOption},
> ```

ranges are admin only because start/end keys are sensitive information

(plz explain this in a comment)
___
*[pkg/server/api.go, line 230 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60952#-MUIGUfH7qGTMQboqSPu:-MUIGUfH7qGTMQboqSPv:bcb8l0h) ([raw file](https://github.com/cockroachdb/cockroach/blob/8381c64c327326aaf4bb207253bd44b8cf9562b2/pkg/server/api.go#L230)):*
> ```Go
> 	resp.Next = next
> 	for _, n := range nodes.Nodes {
> 		var cur nodeStatus
> ```

the go idiomatic way, which also is easier on the eye, would be
```go
resp.Nodes = append(Resp.Nodes, nodeStatus{
   NodeID: n.Desc.NodeID,
   ...
})
```
___
*[pkg/server/pagination.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60952#-MUIH7Yg5pDFJBO6lIWS:-MUIH7Yg5pDFJBO6lIWT:b-su6c82) ([raw file](https://github.com/cockroachdb/cockroach/blob/8381c64c327326aaf4bb207253bd44b8cf9562b2/pkg/server/pagination.go#L35)):*
> ```Go
> 
> // simplePaginate takes in an input slice, and returns a sub-slice of the next
> // `limit` elements starting at `offset`. The second returned value is the
> ```

 might recommend a separate commit for this change with a unit test for the new special case.

**Review by itsbilal — COMMENTED** [review]
TFTR! I've added tests so this is no longer WIP now. Also did the split of the files, and renamed `api.go` to `api_v2.go` for consistency. Ended up keeping `/health` there as that one is pretty simple.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60952#-:-MUUWbQ062Sf1Gd5wBLh:bcjs28u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @knz)

___
*[pkg/server/pagination.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60952#-MUIH7Yg5pDFJBO6lIWS:-MUUYbEs78TcERfKKQbM:bes5jpf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8381c64c327326aaf4bb207253bd44b8cf9562b2/pkg/server/pagination.go#L35)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

 might recommend a separate commit for this change with a unit test for the new special case.
</blockquote></details>

Done. Existing datadriven tests already got updated with the new case so that was easy.
___
*[pkg/server/api.go, line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60952#-MUIGmG4AtmtCYjCi8at:-MUUY_AV9TlHPV5bWwmy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8381c64c327326aaf4bb207253bd44b8cf9562b2/pkg/server/api.go#L113)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ranges are admin only because start/end keys are sensitive information

(plz explain this in a comment)
</blockquote></details>

Done.
___
*[pkg/server/api.go, line 230 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60952#-MUIGUfH7qGTMQboqSPu:-MUUYa-vAm7tw7aDfArN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8381c64c327326aaf4bb207253bd44b8cf9562b2/pkg/server/api.go#L230)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

the go idiomatic way, which also is easier on the eye, would be
```go
resp.Nodes = append(Resp.Nodes, nodeStatus{
   NodeID: n.Desc.NodeID,
   ...
})
```
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
Nice thanks :100: 
Can you also add a proper release note to the commit message and enumerate hte API endpoints with a short description. The doc writer will thank you.

Thanks

> Reviewed 3 of 3 files at r2, 7 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60952#-:-MUUvM2T0v4eZa4sFmLb:bjiww6o)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal)

**Review by itsbilal — COMMENTED** [review]
TFTR! Added

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60952#-:-MUVFozsElrck7NIYxiQ:bomuowc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @knz)

**Comment by itsbilal** [comment]
bors r=knz

**Pull request merged**
