### PR TITLE
server: Tenant pods fan out to cancel SQL sessions

### PR DESCRIPTION
**Pull request by matthewtodd**
Partially addresses #70832.
    
Previously, the tenant `/_status/cancel_session` endpoint was not
available over HTTP and could not cancel a session not running locally.
This change opens it up, so that we can call it from the cloud console,
and makes sure that that we can cancel sessions when a tenant has more
than one SQL pod running.
    
Release note (api change): The tenant `/_status/cancel_session` endpoint
was made available over HTTP and augmented to fan out requests in a
multi-pod world.

### CODE REVIEW

**Review by Azhng — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71174)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @matthewtodd)

___
*[pkg/ccl/serverccl/tenant_status_test.go, line 476 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71174#-MlL5uyA1uZ0oh2705za:-MlL5uyA1uZ0oh2705zb:bpebk2z) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdb81711d76b5c15190bebdd8d5ac461feef2381/pkg/ccl/serverccl/tenant_status_test.go#L476)):*
> ```Go
> func selectClusterSessionIDs(t *testing.T, conn *sqlutils.SQLRunner) []string {
> 	var sessionIDs []string
> 	rows := conn.Query(t, "SELECT session_id FROM crdb_internal.cluster_sessions")
> ```

do you thinking using `conn.QueryStr` will make it less verbose here? 
___
*[pkg/ccl/serverccl/tenant_status_test.go, line 480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71174#-MlL2W-K7RwoiEQuN_AX:-MlL2W-K7RwoiEQuN_AY:b-8t3w3y) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdb81711d76b5c15190bebdd8d5ac461feef2381/pkg/ccl/serverccl/tenant_status_test.go#L480)):*
> ```Go
> 	for rows.Next() {
> 		var sessionID string
> 		rows.Scan(&sessionID)
> ```

nit: unchecked error.
___
*[pkg/ccl/serverccl/tenant_status_test.go, line 491 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71174#-MlL50uu5mnPJImk-l_N:-MlL50uu5mnPJImk-l_O:b-palmja) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdb81711d76b5c15190bebdd8d5ac461feef2381/pkg/ccl/serverccl/tenant_status_test.go#L491)):*
> ```Go
> 
> 	ctx := context.Background()
> 	helper := newTestTenantHelper(t, 3, base.TestingKnobs{})
> ```

this is quite an expensive setup since it sets up a 3-node host cluster + 2x 3-node tenant cluster with different tenant IDs. I remember i was running into timeout issues in the stress tests so I had to skip them. So there's a chance you might need to do that too here as well.

Hmm, perhaps the test helper could have been improved to spin up resource on demand instead of eagerly spinning up so many servers (so we don't have to skip so many tests) :sweat_smile: .
___
*[pkg/ccl/serverccl/tenant_status_test.go, line 494 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71174#-MlL45BbCI2TE34Ix7oG:-MlL45BbCI2TE34Ix7oH:bnjs2qy) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdb81711d76b5c15190bebdd8d5ac461feef2381/pkg/ccl/serverccl/tenant_status_test.go#L494)):*
> ```Go
> 	defer helper.cleanup(ctx, t)
> 
> 	// Open a SQL session on tenant 0.
> ```

super minor nit: `s/tenant 0/tenant SQL Pod 0/`, otherwise this might be slightly misleading since `sql0` and `http1` are both belongs to different SQL pod but running with same tenant ID. `newTestTenantHelper` actually creates a different tenant cluster with a different tenant ID, you can get it via `helper.controlCluster()`

Unrelated note: now typing this out, I think it should have being called `.controlledCluster()` since the terminology is borrowed from vaccine trial, (testing group vs controlled group) 
___
*[pkg/ccl/serverccl/tenant_status_test.go, line 514 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71174#-MlL5nCk7jMXAbZ1qYPA:-MlL5nCk7jMXAbZ1qYPB:b-kygggd) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdb81711d76b5c15190bebdd8d5ac461feef2381/pkg/ccl/serverccl/tenant_status_test.go#L514)):*
> ```Go
> 	cancelSessionReq := serverpb.CancelSessionRequest{NodeId: session.NodeID.String(), SessionID: session.ID}
> 	cancelSessionResp := serverpb.CancelSessionResponse{}
> 	err = http1.PostJSON("/_status/cancel_session/"+session.NodeID.String(), &cancelSessionReq, &cancelSessionResp)
> ```

I'm a bit surprised here, `NodeID` needs to be both embedded in the RPC request as well as the URL ? 
___
*[pkg/server/tenant_status.go, line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71174#-MlL3M4F8mLsY1byp24k:-MlL3M4F8mLsY1byp24l:b-gu2c3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdb81711d76b5c15190bebdd8d5ac461feef2381/pkg/server/tenant_status.go#L191)):*
> ```Go
> 	ctx context.Context, request *serverpb.CancelSessionRequest,
> ) (*serverpb.CancelSessionResponse, error) {
> 	parsedInstanceID, local, err := t.parseInstanceID(request.NodeId)
> ```

Ooof, I thought we override all of the `node_id` to be `NodeID` in the db repo. Hmm how do you feel about making that happen in this PR :sweat_smile:

**Review by matthewtodd — COMMENTED** [review]
> Dismissed @Azhng from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71174)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @dhartunian)

___
*[pkg/ccl/serverccl/tenant_status_test.go, line 476 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71174#-MlL5uyA1uZ0oh2705za:-MlMBI8G4nNeJjlPQA1Z:bf3wa6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdb81711d76b5c15190bebdd8d5ac461feef2381/pkg/ccl/serverccl/tenant_status_test.go#L476)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

do you thinking using `conn.QueryStr` will make it less verbose here? 
</blockquote></details>

Ooh, thanks! Done.
___
*[pkg/ccl/serverccl/tenant_status_test.go, line 491 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71174#-MlL50uu5mnPJImk-l_N:-MlMBRdv3I6ZCdQVAFm0:bk9mp6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdb81711d76b5c15190bebdd8d5ac461feef2381/pkg/ccl/serverccl/tenant_status_test.go#L491)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

this is quite an expensive setup since it sets up a 3-node host cluster + 2x 3-node tenant cluster with different tenant IDs. I remember i was running into timeout issues in the stress tests so I had to skip them. So there's a chance you might need to do that too here as well.

Hmm, perhaps the test helper could have been improved to spin up resource on demand instead of eagerly spinning up so many servers (so we don't have to skip so many tests) :sweat_smile: .
</blockquote></details>

Hmm, interesting. I wonder if there's a way to write a lighter version that's still end-to-end enough to give me confidence, will look around for options.
___
*[pkg/ccl/serverccl/tenant_status_test.go, line 494 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71174#-MlL45BbCI2TE34Ix7oG:-MlMBtYeDCbqccn_tb5u:bconkdt) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdb81711d76b5c15190bebdd8d5ac461feef2381/pkg/ccl/serverccl/tenant_status_test.go#L494)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

super minor nit: `s/tenant 0/tenant SQL Pod 0/`, otherwise this might be slightly misleading since `sql0` and `http1` are both belongs to different SQL pod but running with same tenant ID. `newTestTenantHelper` actually creates a different tenant cluster with a different tenant ID, you can get it via `helper.controlCluster()`

Unrelated note: now typing this out, I think it should have being called `.controlledCluster()` since the terminology is borrowed from vaccine trial, (testing group vs controlled group) 
</blockquote></details>

Good call, changed the comments and the variable names.
___
*[pkg/ccl/serverccl/tenant_status_test.go, line 514 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71174#-MlL5nCk7jMXAbZ1qYPA:-MlMC59U7wRXegtch1cO:b-pthcp8) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdb81711d76b5c15190bebdd8d5ac461feef2381/pkg/ccl/serverccl/tenant_status_test.go#L514)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

I'm a bit surprised here, `NodeID` needs to be both embedded in the RPC request as well as the URL ? 
</blockquote></details>

Good catch, fixed. It just needs to be [in the URL](https://github.com/cockroachdb/cockroach/blob/80ce329b4e02c070611a9e55008349a1176bf297/pkg/server/serverpb/status.proto#L1337-L1343).
___
*[pkg/server/tenant_status.go, line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71174#-MlL3M4F8mLsY1byp24k:-MlMJge2-gtLmfuiwgFg:b6qrgx4) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdb81711d76b5c15190bebdd8d5ac461feef2381/pkg/server/tenant_status.go#L191)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Ooof, I thought we override all of the `node_id` to be `NodeID` in the db repo. Hmm how do you feel about making that happen in this PR :sweat_smile: 
</blockquote></details>

Based on [this comment](https://github.com/cockroachdb/cockroach/blob/80ce329b4e02c070611a9e55008349a1176bf297/pkg/server/serverpb/status.proto#L679-L680), it's probably more than we want to address here.

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71174)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @dhartunian, and @matthewtodd)

___
*[pkg/server/tenant_status.go, line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71174#-MlL3M4F8mLsY1byp24k:-MlQVzNl1wZQ80JF6N_4:bm31s2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdb81711d76b5c15190bebdd8d5ac461feef2381/pkg/server/tenant_status.go#L191)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Based on [this comment](https://github.com/cockroachdb/cockroach/blob/80ce329b4e02c070611a9e55008349a1176bf297/pkg/server/serverpb/status.proto#L679-L680), it's probably more than we want to address here.
</blockquote></details>

Ah I see :+1:

**Review by matthewtodd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71174)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @dhartunian, and @matthewtodd)

___
*[pkg/ccl/serverccl/tenant_status_test.go, line 491 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71174#-MlL50uu5mnPJImk-l_N:-MlkfZUXBO8Nv5BnOjqx:b-bxi480) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdb81711d76b5c15190bebdd8d5ac461feef2381/pkg/ccl/serverccl/tenant_status_test.go#L491)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Hmm, interesting. I wonder if there's a way to write a lighter version that's still end-to-end enough to give me confidence, will look around for options.
</blockquote></details>

I've ended up using `skip.UnderStressRace` like the other tests in this file. 😢

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71174)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @matthewtodd)

___
*[pkg/ccl/serverccl/tenant_status_test.go, line 518 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71174#-MlpqXgV8769hRFOka3q:-MlpqXgV8769hRFOka3r:b-g4gxo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d4c1f4a7127ac43bf2b9a68c02b51b2cd72afad/pkg/ccl/serverccl/tenant_status_test.go#L518)):*
> ```Go
> 		}
> 	}
> 	require.NotNil(t, session, "Session not found.")
> ```

I think this will never be nil, since `session` is a value type instead of a pointer type.

super nit: i think we usually keep the error msg all lower case

**Review by Azhng — APPROVED** [review]
LGTM otherwise

**Pull request merged**
