### PR TITLE
colflow: fix the shutdown for good

### LINKED ISSUE #73425: sql/logictest: TestLogic failed
sql/logictest.TestLogic [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3840190&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3840190&tab=artifacts#/) on master @ [b8f13f26ed9647428ce3130c129adc913c60316c](https://github.com/cockroachdb/cockroach/commits/b8f13f26ed9647428ce3130c129adc913c60316c):

```
=== RUN   TestLogic
    test_log_scope.go:79: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestLogic112937844
    test_log_scope.go:80: use -show-logs to present logs inline
=== CONT  TestLogic
    logic.go:3555: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestLogic112937844
--- FAIL: TestLogic (2438.72s)
=== RUN   TestLogic/5node-disk/distsql_union/Except
    logic.go:2690: 
        
        testdata/logic_test/distsql_union:332: (SELECT y FROM xyz ORDER BY y) EXCEPT ALL (SELECT y FROM xyz ORDER BY y)
        expected success, but found
        (58C01) inbox communication error: rpc error: code = Canceled desc = context canceled
        inbox.go:328: in Next()
    logic.go:2416: 
         pq: inbox communication error: rpc error: code = Canceled desc = context canceled
    logic.go:1962: 
         testdata/logic_test/distsql_union:336: too many errors encountered, skipping the rest of the input
--- done: testdata/logic_test/distsql_union with config 5node-disk: 35 tests, 3 failures
--- total progress: 156339 statements/queries
--- progress: testdata/logic_test/hash_join_dist: 16 statements/queries
--- done: testdata/logic_test/hash_join_dist with config 5node-disk: 18 tests, 0 failures
            --- FAIL: TestLogic/5node-disk/distsql_union/Except (0.02s)
=== RUN   TestLogic/5node-disk/distsql_union
=== PAUSE TestLogic/5node-disk/distsql_union
=== CONT  TestLogic/5node-disk/distsql_union
        --- FAIL: TestLogic/5node-disk/distsql_union (1.44s)
=== RUN   TestLogic/5node-disk
    --- FAIL: TestLogic/5node-disk (0.00s)
```
<details><summary>Help</summary>
<p>
See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)Parameters in this failure:

- GOFLAGS=-parallel=2
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #63262 sql/logictest: TestLogic failed [C-test-failure O-robot branch-release-20.2]
- #61657 sql/logictest: TestLogic failed [C-test-failure O-robot branch-release-21.1]
- #58269 sql/logictest: TestLogic failed [C-test-failure O-robot T-sql-schema branch-release-20.1]
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLogic.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #73962: sql/colflow/colrpc: TestOutboxInbox failed
sql/colflow/colrpc.TestOutboxInbox [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3938232&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3938232&tab=artifacts#/) on master @ [3b4e180a23f5121e0d4106eb3dc5f61ebc314188](https://github.com/cockroachdb/cockroach/commits/3b4e180a23f5121e0d4106eb3dc5f61ebc314188):

```
=== RUN   TestOutboxInbox
--- FAIL: TestOutboxInbox (0.01s)
=== RUN   TestOutboxInbox/cancellationScenario=flowCtxCancel
    colrpc_test.go:426: 
        	Error Trace:	colrpc_test.go:426
        	Error:      	Should be true
        	Test:       	TestOutboxInbox/cancellationScenario=flowCtxCancel
        	Messages:   	query execution canceled
    --- FAIL: TestOutboxInbox/cancellationScenario=flowCtxCancel (0.00s)
```
<details><summary>Help</summary>
<p>
See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)Parameters in this failure:

- TAGS=bazel,gss,deadlock
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestOutboxInbox.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #73966: sql/logictest: TestSqlLiteLogic failed
sql/logictest.TestSqlLiteLogic [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3935418&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3935418&tab=artifacts#/) on master @ [243d90e97789ea0206356b215c0e79aedb4f2e14](https://github.com/cockroachdb/cockroach/commits/243d90e97789ea0206356b215c0e79aedb4f2e14):

```
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/100/slt_good_1.test: 7757 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/100/slt_good_2.test: 7780 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/10/slt_good_5.test: 159 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/100/slt_good_0.test: 6375 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/1000/slt_good_0.test: 7042 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/10/slt_good_7.test: 6369 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/10/slt_good_6.test: 512 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/100/slt_good_1.test: 7848 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/100/slt_good_2.test: 7858 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/10/slt_good_4.test: 21 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/10/slt_good_5.test: 235 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/100/slt_good_0.test: 6449 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/10/slt_good_7.test: 6451 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/10/slt_good_6.test: 619 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/100/slt_good_1.test: 7940 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/100/slt_good_2.test: 7960 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/10/slt_good_4.test: 57 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/10/slt_good_5.test: 358 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/100/slt_good_0.test: 6573 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/10/slt_good_7.test: 6558 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/10/slt_good_6.test: 737 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/100/slt_good_1.test: 8018 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/100/slt_good_2.test: 8010 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/10/slt_good_4.test: 150 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/10/slt_good_5.test: 449 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/100/slt_good_0.test: 6644 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/10/slt_good_7.test: 6644 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/10/slt_good_6.test: 857 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/100/slt_good_1.test: 8099 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/100/slt_good_2.test: 8113 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/10/slt_good_4.test: 300 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/10/slt_good_5.test: 596 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/100/slt_good_0.test: 6757 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/10/slt_good_7.test: 6738 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/1000/slt_good_0.test: 7043 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/10/slt_good_6.test: 944 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/100/slt_good_1.test: 8148 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/100/slt_good_2.test: 8181 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/10/slt_good_4.test: 366 statements/queries
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/10/slt_good_5.test: 666 statements/queries
--- done: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/100/slt_good_1.test with config fakedist-spec-planning: 8172 tests, 0 failures
--- total progress: 13636362 statements/queries
=== CONT  TestSqlLiteLogic/fakedist-spec-planning/slt_good_4.test#10
    logic.go:2438: 
         pq: internal error: unexpected error from the vectorized engine: context canceled
--- done: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/10/slt_good_4.test with config fakedist-spec-planning: 5780 tests, 1 failures
    logic.go:3353: 
        /go/src/github.com/cockroachdb/sqllogictest/test/index/view/10/slt_good_4.test:25851: error while processing
    logic.go:3353: /go/src/github.com/cockroachdb/sqllogictest/test/index/view/10/slt_good_4.test:25851: too many errors encountered, skipping the rest of the input
        --- FAIL: TestSqlLiteLogic/fakedist-spec-planning/slt_good_4.test#10 (119.78s)
```
<details><summary>Help</summary>
<p>
See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestSqlLiteLogic.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #73972: sql: potential flake in TestLogic/5node-spec-planning/distsql_union/Except
Seen in [this build](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/3933198):

```
------- Stdout: -------
=== RUN   TestLogic/5node-spec-planning/distsql_union/Except
    logic.go:2704:
        testdata/logic_test/distsql_union:348: (SELECT x FROM xyz WHERE x < 2) EXCEPT (SELECT x FROM xyz WHERE x >= 2) ORDER BY x
        expected success, but found
        (58C01) inbox communication error: rpc error: code = Canceled desc = context canceled
        inbox.go:361: in Next()
    logic.go:2430:
         pq: inbox communication error: rpc error: code = Canceled desc = context canceled
    logic.go:1976:
         testdata/logic_test/distsql_union:353: too many errors encountered, skipping the rest of the input
--- done: testdata/logic_test/distsql_union with config 5node-spec-planning: 38 tests, 3 failures
--- done: testdata/logic_test/distsql_numtables with config 5node-spec-planning: 27 tests, 0 failures
--- done: testdata/logic_test/distsql_crdb_internal with config 5node-spec-planning: 8 tests, 0 failures
--- progress: testdata/logic_test/distsql_agg: 35 statements/queries
--- progress: testdata/logic_test/hash_join_dist: 16 statements/queries
--- done: testdata/logic_test/hash_join_dist with config 5node-spec-planning: 18 tests, 0 failures
--- total progress: 159492 statements/queries
--- progress: testdata/logic_test/distsql_distinct_on: 8 statements/queries
--- done: testdata/logic_test/distsql_distinct_on with config 5node-spec-planning: 15 tests, 0 failures
--- progress: testdata/logic_test/distsql_agg: 81 statements/queries
--- done: testdata/logic_test/distsql_agg with config 5node-spec-planning: 81 tests, 0 failures
            --- FAIL: TestLogic/5node-spec-planning/distsql_union/Except (0.13s)
```

### PR DESCRIPTION
**Pull request by yuzefovich**
**Revert "Revert "colrpc: propagate the flow cancellation as ungraceful for FlowStream RPC""**

This reverts commit 48dd74c.

**colrpc: deflake TestOutboxInbox**

In `flowCtxCancel` scenario there are two possible errors that might be
returned to the reader depending on the exact sequence of events:
- `QueryCanceledError` is used when the flow ctx cancellation is
observed before the stream arrived
- wrapped `context.Canceled` error is used when the inbox handler
goroutine notices the cancellation first and ungracefully shuts down
the stream.

Previously, we assumed that only the latter could occur, and we allow
for either.

Fixes: #73962.

Release note: None

**colflow: fix the shutdown for good**

This commit fixes a long standing bug in the distributed vectorized
query shutdown where in case of a graceful completion of the flow on one
node, we might get an error on another node resulting in the ungraceful
termination of the query. This was caused by the fact that on remote
nodes the last outbox to exit would cancel the flow context; however,
when instantiating `FlowStream` RPC the outboxes used a child context of
the flow context, so that "graceful" cancellation of the flow context
would cause the inbox to get an ungraceful termination of the gRPC
stream. As a result, the whole query could get "context canceled" error.

I believe this bug was introduced by me over two years ago because
I didn't fully understand how the shutdown should work, and in
particular I was missing that when an inbox observes the flow context
cancellation, it should terminate the `FlowStream` RPC ungracefully in
order to propagate the ungracefullness to the other side of the stream.
This shortcoming was fixed in the previous commit.

Another possible bug was caused by the outbox canceling its own context
in case of a graceful shutdown. As mentioned above, `FlowStream` RPC was
issued using the outbox context, so there was a possibility of a race
between `CloseSend` call being delivered to the inbox (graceful
termination) and the context of the RPC being canceled (ungraceful
termination).

Both of these problems are now fixed, and the shutdown protocol now is as
follows:
- on the gateway node we keep on canceling the flow context at the very
end of the query execution. It doesn't matter whether the query resulted
in an error or not, and doing so allows us to ensure that everything
exits on the gateway node. This behavior is already present.
- due to the fix in a previous commit, that flow context cancellation
terminates ungracefully all still open gRPC streams for `FlowStream` RPC
for which the gateway node is the inbox host.
- the outboxes on the remote nodes get the ungraceful termination and
cancel the flow context of their hosts. This, in turn, would trigger
propagation of the ungraceful termination on other gRPC streams, etc.
- whenever an outbox exits gracefully, it cancels its own context, but
the gRPC stream uses the flow context, so the stream is still alive.
I debated a bit whether we want to keep this outbox context cancellation
in case of a graceful completion and decided to keep it to minimize the
scope of changes.

Fixes: #73425.
Fixes: #73966.
Fixes: #73972.

Release note (bug fix): Previously, CockroachDB could return a spurious
"context canceled" error for a query that actually succeeded in
extremely rare cases, and this has now been fixed.

### CODE REVIEW

**Comment by yuzefovich** [comment]
The first commit is exactly #73887, and I reduced the scope of changes in the third commit (comparing to #74121), so I'm quite pleased with this change overall when thinking about the backport.

**Comment by yuzefovich** [comment]
I've stressed `distsql_union` logic test for a while with no failures:
```
11688 runs so far, 0 failures, over 2h48m45s
```
so I think we're good.

@jordanlewis @cucaroach I'd like to merge this today if possible so that we get a nightly CI run to see whether there is any fallout before the holidays.

**Review by cucaroach — APPROVED** [review]
Its unfortunate that you have to submit to master to get your change run through nightly, maybe we wouldn't have so many test failures if that wasn't the case.   Anyways I reviewed it but only superficially, understanding this stuff better will have to wait till next year!

> Reviewed 3 of 6 files at r1, 2 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74163#-:-MrUCzTR4oY7TQ1Wrggk:b-pdia9q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by yuzefovich** [comment]
I'm relatively confident that this change should not have any fallout, but I'm very interested in the SQLLite logic tests that are run nightly. I think they are pretty expensive, so it would not be really feasible to include it as part of CI for each PR.

I could, however, manually kick off some nightly builds on my current branch without merging it to master, but there is a bit of urgency on merging this - we have a customer on 21.1 that is blocked by this, and I want to have several days worth of nightly runs for more confidence before merging this change to 21.1.

Unless something else comes up, I plan to write the draft of the tech note about the distributed query shutdown tomorrow, and we can chat more after the holidays :)

TFTR!

bors r+

**Pull request merged**
