### PR TITLE
sql: refactor distsql* and exec packages

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, `distsqlrun` was a monstrous package that contained the
logic for planning both vectorized and row based flows as well as
the logic of all processors and many other things. This made
testing some of the parts of the vectorized engine and flows tricky
(if possible). This commit does an overhaul to `distsqlrun` package
as well as renames a few others.

Here are the changes:
- `distsqlplan` is renamed into `physicalplan`
- `exec` is renamed into `colexec`
- `distsqlpb` is renamed into `execinfrapb`
- `distsqlrun` is broken into the following:
  - `colflow` (setting up the vectorized flow)
  - `rowexec` (only the processors that are used exclusively by the
    row engine)
  - `rowflow` (setting up the row based flow)
  - `flowinfra` (the common interface and the shared logic between
    `colflow` and `rowflow`)
  - `execinfra` (the common interfaces for `colexec` and `rowexec`)
  - `distsql` (a "server" package that determines which kind of flow
    to run).

Here is a graph of dependencies between the packages:
```
        ---->  rowflow  ---->  rowexec
        |         |     \         |
        |         ↓      \        ↓
distsql ----> flowinfra ----> execinfra
        |         ↑      /        ↑
        |         |     /         |
        ---->  colflow  ---->  colexec
```
`execinfra` is intended to be similar to `sqlbase` in regard that it can
be used from anywhere.
`flowinfra` is intended to be used only by `distsql`, `colflow`, and `rowflow`.

Release justification: Category 1: Non-production code changes.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
I like the restructuring overall. From my side, I am ok merging it (with whatever names you and Jordan agree on).

I believe there are missing arrows in your diagram from `rowflowsetup` and `colflowsetup` to `execinfra`. This begs the question - why separate `flowbase` and `execinfra`?

> - `rowflowsetup` -> `rowplan` or `rowexecplan`
> - `colflowsetup` -> `colplan` or `colexecplan`

I like the "setup" versions ("plan" is already used heavily for the, well, planning side).

`flowbase` could also be `flowinfra` or `flowsetup`.

**Review by RaduBerinde — APPROVED** [review]

**Review by jordanlewis — APPROVED** [review]
LGTM! 🥂

**Comment by yuzefovich** [comment]
I like Radu's suggestion to rename `flowbase` into `flowinfra` - it has a very nice symmetry with `execinfra`, so I've just renamed that package. I think the graph looks very pretty now :)

**Comment by yuzefovich** [comment]
Thanks for the reviews!

bors r=jordanlewid,raduberinde

**Comment by yuzefovich** [comment]
Hm, a failure I haven't seen before:
```
[01:26:22]Unable to find image 'cockroachdb/builder:20190718-082058' locally
[01:26:26]docker: Error response from daemon: Get https://registry-1.docker.io/v2/cockroachdb/builder/manifests/20190718-082058: EOF.
[01:26:26]See 'docker run --help'.
[01:26:26]Process exited with code 125
```
Assuming it's a flake.

bors r=jordanlewis,raduberinde

**Comment by yuzefovich** [comment]
Was missing "release justification" in the PR description.

bors r=jordanlewis,raduberinde

**Comment by yuzefovich** [comment]
C'mon bors, another flake "TestBackupRestoreWithConcurrentWrites."

bors r=jordanlewis,raduberinde

**Comment by RaduBerinde** [comment]
There are instances of `pkg/sql/exec` left in the Makefile, eg https://github.com/cockroachdb/cockroach/blob/master/Makefile#L824

**Comment by yuzefovich** [comment]
Those two instances were left on purpose (for now) so that files generated into the old directory are deleted. Otherwise, when someone rebases on top of the refactor, the old directory `pkg/sql/exec/` would be full of `*.eg.go` files which is slightly annoying and could case problems with the build.

**Comment by yuzefovich** [comment]
But it looks like I didn't get the commands quite right :/
```
[05:13:11]Compile acceptance tests (29s)
[05:13:11][Compile acceptance tests] + CGO_ENABLED=1
[05:13:11][Compile acceptance tests] + make BUILDTYPE=release XGOOS=linux XGOARCH=amd64 XCMAKE_SYSTEM_NAME=Linux TARGET_TRIPLE=x86_64-unknown-linux-gnu 'LDFLAGS=-static-libgcc -static-libstdc++' SUFFIX=-linux-2.6.32-gnu-amd64 -Otarget testbuild TAGS=acceptance PKG=./pkg/acceptance
[05:13:11][Compile acceptance tests] find: 'pkg/sql/exec': No such file or directory
[05:13:40]Run acceptance tests (11m:17s)
```

**Pull request merged**
