### PR TITLE
*: promote cockroachdb/errors

### LINKED ISSUE #48157: *: replace pkg/errors by cockroachdb/errors
The `cockroachdb/errors` package has gained in maturity. IT's now time to deprecated pkg/errors and migrate.

This should be done by also introducing a linter.

### PR DESCRIPTION
**Pull request by knz**
It is time.

In a nutshell, this:

- changes the imports of `"errors"` and `"github.com/pkg/errors"` to refer to `"github.com/cockroachdb/errors"` instead.
- promotes `errors.If`, `errors.As` and `errors.HasType` instead of error casts.
- promotes `errors.Is`, `errors.IsAny` and `errrors.HasType` instead of manually using `errors.Cause()` and then testing the error.
- promotes `errors.Is` / `errors.IsAny` instead of direct error comparisons.

Fixes #48157

### CODE REVIEW

**Comment by knz** [comment]
The failure are expected - this is missing one more commit. Working on it.

**Comment by knz** [comment]
This is ready :tada:

**Review by tbg — APPROVED** [review]
I'm sorry I let this sit for so long, it somehow slipped my radar. There are some rebase conflicts, I hope they're not dramatic.

I like the lints, though I think they ought to be more actionable - someone not familiar with the errors API might be left clueless as to what they're supposed to do instead. This is as easy as adding an example for each, I think. However, I don't think this should block the merge - once you've rebased this it's time to get it in ASAP.

PS Reviewable really really struggled with this PR. Nice stress test :)

> Reviewed 2 of 2 files at r1, 53 of 53 files at r2, 533 of 533 files at r3, 112 of 112 files at r4, 124 of 124 files at r5, 11 of 11 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48275#-:-M6iEeEn9rzmmeGsa35r:b-mlr1ov)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/cli/debug_merge_logs.go, line 554 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48275#-M6iDWUO8pJ_sDhpl_Hn:-M6iDWUO8pJ_sDhpl_Ho:b-73m6vj) ([raw file](https://github.com/cockroachdb/cockroach/blob/65150577e5769869cb88917e1d11fd8292d093b9/pkg/cli/debug_merge_logs.go#L554)):*
> ```Go
> 				return true
> 			}
> 			panic(err)
> ```

Nice catch.
___
*[pkg/testutils/lint/lint_test.go, line 1647 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/48275#-M6iClze07HR37qIyXQe:-M6iClzhCMZwBBQa_X7k:btbxcsb) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf74a81a12643d2db56ac792e7b8737d1b687f69/pkg/testutils/lint/lint_test.go#L1647)):*
> ```Go
> 			stream.GrepNot(`pkg/roachpb/batch_generated\.go:.*use errors\.HasType, errors\.HasInterface, errors\.As or errors\.If`),
> 			stream.GrepNot(`pkg/roachpb/errors\.go:.*use errors\.HasType, errors\.HasInterface, errors\.As or errors\.If`),
> 			// pgerror also knows what it's doing.
> ```

Can you add some justification on what it means that someone knows what they're doing? Right now it seems that you can just add your code that fails the lint here because.. you know what you're doing. Some more guidance here would be nice.
___
*[pkg/testutils/lint/passes/errcmp/errcmp.go, line 86 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/48275#-M6iA1tq4FVyAPWCdqpC:-M6iA1tr5CH9H1YTRGHj:b9glv7z) ([raw file](https://github.com/cockroachdb/cockroach/blob/15d845178c3f8e4a2ab6ffd6dd212e8998878e7a/pkg/testutils/lint/passes/errcmp/errcmp.go#L86)):*
You could add a comment

> // Instead of, e.g.,
> //   someError == somethingNotNil,
> // enforce
> //   errors.Is(someError, somethingNotNil).
___
*[pkg/testutils/lint/passes/errcmp/errcmp.go, line 88 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/48275#-M6i9maUA4ds3EHPuK_e:-M6i9maUA4ds3EHPuK_f:b-iyrmex) ([raw file](https://github.com/cockroachdb/cockroach/blob/15d845178c3f8e4a2ab6ffd6dd212e8998878e7a/pkg/testutils/lint/passes/errcmp/errcmp.go#L88)):*
> ```Go
> 		if pass.TypesInfo.Types[binaryExpr.X].Type == errorType &&
> 			!pass.TypesInfo.Types[binaryExpr.Y].IsNil() {
> 			// We have a special case: when the RHS is io.EOF.
> ```

Is this just out of courtesy or is there some reason we can't use `errors.Is` in that case?
___
*[pkg/testutils/lint/passes/errcmp/errcmp.go, line 75 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/48275#-M6iD0ZECXWu_nlnJWoM:-M6iD0ZF9zSTw9jgbm66:b2vr4qn) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf74a81a12643d2db56ac792e7b8737d1b687f69/pkg/testutils/lint/passes/errcmp/errcmp.go#L75)):*
> ```Go
> 
> func checkErrCast(pass *analysis.Pass, texpr *ast.TypeAssertExpr) {
> 	if pass.TypesInfo.Types[texpr.X].Type == errorType {
> ```

This pass based linter really is nice.
___
*[pkg/testutils/lint/passes/errcmp/errcmp.go, line 81 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48275#-M6iDr0U5UtVy7gRR6sG:-M6iDr0U5UtVy7gRR6sH:b-hkuxjx) ([raw file](https://github.com/cockroachdb/cockroach/blob/65150577e5769869cb88917e1d11fd8292d093b9/pkg/testutils/lint/passes/errcmp/errcmp.go#L81)):*
> ```Go
> func checkErrSwitch(pass *analysis.Pass, s *ast.SwitchStmt) {
> 	if pass.TypesInfo.Types[s.Tag].Type == errorType {
> 		pass.Reportf(s.Switch, "use errors.Is, errors.IsAny or errors.If")
> ```

I don't think this is actionable enough. Can you add an example here? If someone ended up with this message I don't think they'd know what to do. Something like

Instead of

```
switch err {
  case ErrFoo:
  default:
}
```

consider

```
switch {
  case errors.Is(err, ErrFoo):
  default:
}
```

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48275)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @tbg)

___
*[pkg/testutils/lint/lint_test.go, line 1647 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/48275#-M6iClze07HR37qIyXQe:-M6jhfKuA75SgziMkw4g:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf74a81a12643d2db56ac792e7b8737d1b687f69/pkg/testutils/lint/lint_test.go#L1647)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Can you add some justification on what it means that someone knows what they're doing? Right now it seems that you can just add your code that fails the lint here because.. you know what you're doing. Some more guidance here would be nice.
</blockquote></details>

Done.
___
*[pkg/testutils/lint/passes/errcmp/errcmp.go, line 86 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/48275#-M6iA1tq4FVyAPWCdqpC:-M6jhjMQCVlHillGegW1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/15d845178c3f8e4a2ab6ffd6dd212e8998878e7a/pkg/testutils/lint/passes/errcmp/errcmp.go#L86)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

You could add a comment

> // Instead of, e.g.,
> //   someError == somethingNotNil,
> // enforce
> //   errors.Is(someError, somethingNotNil).
</blockquote></details>

Done.
___
*[pkg/testutils/lint/passes/errcmp/errcmp.go, line 88 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/48275#-M6i9maUA4ds3EHPuK_e:-M6jhjy119Fbr3cJ8BNv:b-c40dqu) ([raw file](https://github.com/cockroachdb/cockroach/blob/15d845178c3f8e4a2ab6ffd6dd212e8998878e7a/pkg/testutils/lint/passes/errcmp/errcmp.go#L88)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Is this just out of courtesy or is there some reason we can't use `errors.Is` in that case?
</blockquote></details>

It was courtesy initially (there are about 200 references to io.EOF and it was doubling the amount of work).

Now that I have a process to do it I can also add those and drop the exception maybe? WDYT?
___
*[pkg/testutils/lint/passes/errcmp/errcmp.go, line 81 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48275#-M6iDr0U5UtVy7gRR6sG:-M6jhgupCg4YGviLeUxi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/65150577e5769869cb88917e1d11fd8292d093b9/pkg/testutils/lint/passes/errcmp/errcmp.go#L81)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I don't think this is actionable enough. Can you add an example here? If someone ended up with this message I don't think they'd know what to do. Something like

Instead of

```
switch err {
  case ErrFoo:
  default:
}
```

consider

```
switch {
  case errors.Is(err, ErrFoo):
  default:
}
```

</blockquote></details>

Done.

**Comment by knz** [comment]
> It was courtesy initially (there are about 200 references to io.EOF and it was doubling the amount of work).

I actually thought about this more: the reason why there's an exception is actually because `io.EOF` is used as a loop terminator for most iteration code (`.Next()`-based APIs).  In that case it makes sense to have it compared exactly; if it is wrapped, that means that the iteration is not complete.

**Comment by knz** [comment]
bors r=tbg

**Pull request merged**
