### PR TITLE
tree: fix incorrect parsing of MM:SS.ff and MINUTE TO SECOND intervals

### LINKED ISSUE #43074: interval duration fields not parsed correctly in interval types
**Describe the problem**

We currently support duration fields in cockroach (e.g. `select '1' interval day to second`), but do not parse it correctly in some cases if interval duration fields are set

**To Reproduce**

In postgres:
```
otan=# select interval '1:03';
 interval
----------
 01:03:00
(1 row)


otan=# select interval '1:03' day to second;
 interval
----------
 01:03:00
(1 row)

otan=# select interval '1:03' minute to second;
 interval
----------
 00:01:03
(1 row)
```

But in cockroach:

```
root@127.0.0.1:59223/movr>  select interval '1:03' minute to second;
  ?column?
+----------+
  01:03:00
(1 row)

Time: 315µs
```

**Expected behavior**
Postgres

**Additional data / screenshots**
I suspect `src/interfaces/ecpg/pgtypeslib/interval.c#L400` in postgres will be helpful and/or src/backend/utils/adt/datetime.c#L2550

**Environment:**
 - CockroachDB version: all

### PR DESCRIPTION
**Pull request by otan**
Resolves https://github.com/cockroachdb/cockroach/issues/43074

This PR fixes two latent bugs in the interval parsing:
* `MINUTE TO SECOND` should be parsed as `MM:SS` instead of `HH:MM`.
* `MM:SS.fff` was getting parsed as `HH:MM + .fff * min` in some cases.

Release note (sql change): This change is two fold:
* When using `INTERVAL 's' MINUTE TO SECOND` syntax, we previously would
parse EVERYTHING as `HH:MM` if provided in this format. However, in the
holy sql bible / postgres, we should actually be parse this as `MM:SS`,
which we do after this PR.
* We had some parsing issues where if you entered interval syntax such
as `interval "01:02.123"`, it would parse incorrectly into a twisted,
non-sensical `HH:MM:SS.fff` format, instead of `MM:SS.fff`. After this
PR, we match postgres behaviour and correctly parse this as 1m, 2.123s.

### CODE REVIEW

**Review by solongordon — CHANGES_REQUESTED** [review]
Looks good in general but I don't understand why the timezone changed in a few logic tests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43292#-:-LwV6xKF20tXZOCCnEtr:bd2w1wg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @solongordon)

___
*[pkg/sql/logictest/testdata/logic_test/datetime, line 1169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43292#-LwV6p0FBI9I3bSHWD2L:-LwV6p0G9iPHnaWKE_I-:bmv7m2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/99e632d6af8ed68c47721adbf26c2816edfd439c/pkg/sql/logictest/testdata/logic_test/datetime#L1169)):*
> ```
> SELECT '2015-08-24 21:45:45.53453'::timestamptz
> ----
> 2015-08-24 21:45:45.53453 -0004 -0004
> ```

Wait, why did this change?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43292)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/sql/logictest/testdata/logic_test/datetime, line 1169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43292#-LwV6p0FBI9I3bSHWD2L:-LwVRol_BgZXTV5N2rFy:bighorm) ([raw file](https://github.com/cockroachdb/cockroach/blob/99e632d6af8ed68c47721adbf26c2816edfd439c/pkg/sql/logictest/testdata/logic_test/datetime#L1169)):*
> ```
> SET TIME ZONE INTERVAL '-04:00' MINUTE TO SECOND
> ```

this means 4 minutes, not 4 hours

**Comment by otan** [comment]
___
*[pkg/sql/logictest/testdata/logic_test/datetime, line 1169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43292#-LwV6p0FBI9I3bSHWD2L:-LwVRwGACLRb5MzUmlHG:bwdkuay) ([raw file](https://github.com/cockroachdb/cockroach/blob/99e632d6af8ed68c47721adbf26c2816edfd439c/pkg/sql/logictest/testdata/logic_test/datetime#L1169)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

> ```
> SET TIME ZONE INTERVAL '-04:00' MINUTE TO SECOND
> ```

this means 4 minutes, not 4 hours
</blockquote></details>

technically, postgres doesn't even allow this:

```
otan=# SET TIME ZONE INTERVAL '-04:00' MINUTE TO SECOND;
ERROR:  time zone interval must be HOUR or HOUR TO MINUTE
LINE 1: SET TIME ZONE INTERVAL '-04:00' MINUTE TO SECOND;
```

we can choose to delete it / restrict this, but I think that's work for a separate PR

**Review by solongordon — APPROVED** [review]
Ah, didn't have enough diff context to see that the timezone was set in minutes.

**Comment by otan** [comment]
bors r=solongordon

no wozzaz, thanks for reviewing :D

**Pull request merged**
