### PR TITLE
opt: reduce histogram filtering allocations

### PR DESCRIPTION
**Pull request by mgartner**
This commit reduces allocations of `[]tree.Datum` used to build
`constraint.Key`s in `(*Histogram).Filter` by reusing slices of
previously built keys. In general, this is unsafe, but it is safe in
this specific context because the `constraint.Key`s are only used
temporarily to perform comparisons with other keys and references to
them do no outlive the function.

Epic: None

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
I had machinations of making this even safer by creating a `reusableSpan` type that wraps a `constraint.Span` and never hands it out to callers, ensuring that the lifetimes of the scratch slices and the span are the same. But it required a lot of boilerplate code, and I'm not convinced it's worth it. So I've added some warning comments that should hopefully deter misuse of the `spanBuilder` in the future.

---

In a real-world workload I saw these allocations accounting for 6.5% of CPU time. That's a lot! The `single-col-histogram-range` benchmark highlights the benefits:

```
name                                                                 old time/op    new time/op    delta
Phases/single-col-histogram-range/Simple/Parse                         8.19µs ± 4%    8.40µs ± 8%     ~     (p=0.310 n=5+5)
Phases/single-col-histogram-range/Simple/OptBuildNoNorm                47.2µs ± 0%    42.3µs ± 1%  -10.40%  (p=0.008 n=5+5)
Phases/single-col-histogram-range/Simple/OptBuildNorm                  76.1µs ± 1%    64.9µs ± 3%  -14.65%  (p=0.008 n=5+5)
Phases/single-col-histogram-range/Simple/Explore                       79.2µs ± 0%    68.7µs ± 5%  -13.22%  (p=0.008 n=5+5)
Phases/single-col-histogram-range/Simple/ExecBuild                     82.2µs ± 0%    72.1µs ± 3%  -12.23%  (p=0.016 n=4+5)
Phases/single-col-histogram-range/Prepared/AssignPlaceholdersNoNorm    31.6µs ± 0%    26.6µs ± 2%  -16.00%  (p=0.016 n=4+5)
Phases/single-col-histogram-range/Prepared/AssignPlaceholdersNorm      31.8µs ± 1%    27.2µs ± 7%  -14.54%  (p=0.008 n=5+5)
Phases/single-col-histogram-range/Prepared/Explore                     34.8µs ± 0%    29.4µs ± 6%  -15.35%  (p=0.008 n=5+5)
Phases/single-col-histogram-range/Prepared/ExecBuild                   37.3µs ± 0%    32.3µs ± 6%  -13.53%  (p=0.008 n=5+5)

name                                                                 old alloc/op   new alloc/op   delta
Phases/single-col-histogram-range/Simple/Parse                         3.40kB ± 0%    3.40kB ± 0%     ~     (all equal)
Phases/single-col-histogram-range/Simple/OptBuildNoNorm                19.0kB ± 0%    15.6kB ± 0%  -18.03%  (p=0.008 n=5+5)
Phases/single-col-histogram-range/Simple/OptBuildNorm                  27.4kB ± 0%    20.6kB ± 0%  -24.97%  (p=0.008 n=5+5)
Phases/single-col-histogram-range/Simple/Explore                       30.4kB ± 0%    23.6kB ± 0%  -22.51%  (p=0.008 n=5+5)
Phases/single-col-histogram-range/Simple/ExecBuild                     32.0kB ± 0%    25.2kB ± 0%  -21.38%  (p=0.008 n=5+5)
Phases/single-col-histogram-range/Prepared/AssignPlaceholdersNoNorm    10.8kB ± 0%     7.4kB ± 0%  -31.73%  (p=0.008 n=5+5)
Phases/single-col-histogram-range/Prepared/AssignPlaceholdersNorm      10.8kB ± 0%     7.4kB ± 0%  -31.73%  (p=0.008 n=5+5)
Phases/single-col-histogram-range/Prepared/Explore                     13.2kB ± 0%     9.8kB ± 0%  -25.92%  (p=0.008 n=5+5)
Phases/single-col-histogram-range/Prepared/ExecBuild                   14.8kB ± 0%    11.4kB ± 0%  -23.09%  (p=0.008 n=5+5)

name                                                                 old allocs/op  new allocs/op  delta
Phases/single-col-histogram-range/Simple/Parse                           21.0 ± 0%      21.0 ± 0%     ~     (all equal)
Phases/single-col-histogram-range/Simple/OptBuildNoNorm                   290 ± 0%        76 ± 0%  -73.79%  (p=0.008 n=5+5)
Phases/single-col-histogram-range/Simple/OptBuildNorm                     509 ± 0%        81 ± 0%  -84.09%  (p=0.008 n=5+5)
Phases/single-col-histogram-range/Simple/Explore                          521 ± 0%        93 ± 0%  -82.15%  (p=0.008 n=5+5)
Phases/single-col-histogram-range/Simple/ExecBuild                        532 ± 0%       104 ± 0%  -80.45%  (p=0.008 n=5+5)
Phases/single-col-histogram-range/Prepared/AssignPlaceholdersNoNorm       240 ± 0%        26 ± 0%  -89.17%  (p=0.008 n=5+5)
Phases/single-col-histogram-range/Prepared/AssignPlaceholdersNorm         240 ± 0%        26 ± 0%  -89.17%  (p=0.008 n=5+5)
Phases/single-col-histogram-range/Prepared/Explore                        251 ± 0%        37 ± 0%  -85.26%  (p=0.008 n=5+5)
Phases/single-col-histogram-range/Prepared/ExecBuild                      262 ± 0%        48 ± 0%  -81.68%  (p=0.008 n=5+5)
```

**Review by michae2 — APPROVED** [review]
:lgtm: Very nice!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131050#-:-O7BDCeiEvlJID90Z2Qm:b-kerl87)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Review by DrewKimball — APPROVED** [review]
:lgtm: Nice improvement!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131050#-:-O7BJbXA69cwmzmMtFMz:b-6f8vr5)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by mgartner** [comment]
TFTR!

bors r+

**Pull request merged**
