### PR TITLE
roachtest: fix multitenant-upgrade

### LINKED ISSUE #104223: roachtest: multitenant-upgrade failed
roachtest.multitenant-upgrade [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10338231?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10338231?buildTab=artifacts#/multitenant-upgrade) on master @ [e2b704df25b012baf7d5fbe26e034f520a70f25c](https://github.com/cockroachdb/cockroach/commits/e2b704df25b012baf7d5fbe26e034f520a70f25c):

```
test artifacts and logs in: /artifacts/multitenant-upgrade/run_1
(assertions.go:333).Fail: 
	Error Trace:	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/multitenant_upgrade.go:391
	            				github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/multitenant_upgrade.go:190
	            				github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/multitenant_upgrade.go:38
	            				main/pkg/cmd/roachtest/test_runner.go:1012
	            				GOROOT/src/runtime/asm_amd64.s:1594
	Error:      	Not equal: 
	            	expected: [][]string{[]string{"23.1"}}
	            	actual  : [][]string{[]string{"22.2"}}
	            	
	            	Diff:
	            	--- Expected
	            	+++ Actual
	            	@@ -2,3 +2,3 @@
	            	  ([]string) (len=1) {
	            	-  (string) (len=4) "23.1"
	            	+  (string) (len=4) "22.2"
	            	  }
	Test:       	multitenant-upgrade
(require.go:165).Equal: FailNow called
(cluster.go:2095).Run: cluster.RunE: context canceled
(cluster.go:2095).Run: cluster.RunE: context canceled
(cluster.go:2095).Run: cluster.RunE: context canceled
(cluster.go:2095).Run: cluster.RunE: context canceled
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/multi-tenant
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*multitenant-upgrade.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-28417

### PR DESCRIPTION
**Pull request by knz**
First commit from #106037.
Epic: CRDB-26691
Fixes #104223.

See individual commits for details.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106416)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @healthy-pod, @herkolategan, @knz, @srosenberg, and @stevendanna)

___
*[`pkg/cmd/roachtest/tests/multitenant_upgrade.go` line 237 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106416#-NZlYoDu5Ie2ebS_rFZv:-NZlYoDu5Ie2ebS_rFZw:b-s615n0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4334dcc8f7e061382f68374acb73b67f2e84a6e/pkg/cmd/roachtest/tests/multitenant_upgrade.go#L237)):*
> ```Go
> 		"SET CLUSTER SETTING version = crdb_internal.node_executable_version()")
> 
> 	// Note that here we'd like to validate that the first tenant 11 server can
> ```

DistSQL version won't ever be bumped, plus we now have retry-as-local fall back mechanism, so it seems like we could do what this comment suggests since we're here anyway.
___
*[`pkg/server/node.go` line 2046 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106416#-NZlVo8j5ugYIFSTvWZy:-NZlVo8j5ugYIFSTvWZz:bu0cmst) ([raw file](https://github.com/cockroachdb/cockroach/blob/8efcd9f7688320cee6d6f61448ae5d1e5f23196c/pkg/server/node.go#L2046)):*
> ```Go
> 
> 	send := func(precedence kvpb.TenantSettingsEvent_Precedence, overrides []kvpb.TenantSetting, incremental bool) error {
> 		log.VInfof(ctx, 1, "sending precedence %d: %v", precedence, overrides)
> ```

nit: should we include value of `incremental` in the log message too?
___
*[`pkg/server/node.go` line 2067 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106416#-NZlVzRcAcnxS7E4uBFs:-NZlVzRcAcnxS7E4uBFt:bjq9yic) ([raw file](https://github.com/cockroachdb/cockroach/blob/8efcd9f7688320cee6d6f61448ae5d1e5f23196c/pkg/server/node.go#L2067)):*
> ```Go
> 	// precedence value, with Incremental set to false. This is important:
> 	// the client waits for at least one non-incremental message
> 	// for each predecende before continuing.
> ```

nit: `s/predecende/precedence/g`.
___
*[`pkg/server/node.go` line 2134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106416#-NZlWy5i6QV-TclEhvQu:-NZlWy5i6QV-TclEhvQv:b-5tco1e) ([raw file](https://github.com/cockroachdb/cockroach/blob/8efcd9f7688320cee6d6f61448ae5d1e5f23196c/pkg/server/node.go#L2134)):*
> ```Go
> 		Name: clusterversion.KeyVersionSetting,
> 		Value: settings.EncodedValue{
> 			Type:  "m",
> ```

nit: it took me a bit to understand where this `"m"` comes from. Do you think it'd be worth to do something like:
```
var dummyVersionSetting settings.VersionSetting // global
...
func (n *Node) getVersionSettingWithUpdateCh(...) {
...
  Value: settings.EncodedValue {
    Type: dummyVersionSetting.Typ(),
     ...
  }
...
}
```

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106416)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @healthy-pod, @herkolategan, @srosenberg, @stevendanna, and @yuzefovich)

___
*[`pkg/cmd/roachtest/tests/multitenant_upgrade.go` line 237 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106416#-NZlYoDu5Ie2ebS_rFZv:-NZllXk-44UXHRZjpz90:bk4hvok) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4334dcc8f7e061382f68374acb73b67f2e84a6e/pkg/cmd/roachtest/tests/multitenant_upgrade.go#L237)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

DistSQL version won't ever be bumped, plus we now have retry-as-local fall back mechanism, so it seems like we could do what this comment suggests since we're here anyway.
</blockquote></details>

@healthy-pod can you see about this one?
___
*[`pkg/server/node.go` line 2046 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106416#-NZlVo8j5ugYIFSTvWZy:-NZlkMS926jUvoU3FKed:b-nmb3nw) ([raw file](https://github.com/cockroachdb/cockroach/blob/8efcd9f7688320cee6d6f61448ae5d1e5f23196c/pkg/server/node.go#L2046)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: should we include value of `incremental` in the log message too?
</blockquote></details>

Good idea, done. (#106037)
___
*[`pkg/server/node.go` line 2067 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106416#-NZlVzRcAcnxS7E4uBFs:-NZlkaDt7P1JfqcFyz7S:ba22pdc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8efcd9f7688320cee6d6f61448ae5d1e5f23196c/pkg/server/node.go#L2067)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `s/predecende/precedence/g`.
</blockquote></details>

Fixed. (#106037)
___
*[`pkg/server/node.go` line 2134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106416#-NZlWy5i6QV-TclEhvQu:-NZlkbxL0QtyhhkD2D5Y:b-nmb3nw) ([raw file](https://github.com/cockroachdb/cockroach/blob/8efcd9f7688320cee6d6f61448ae5d1e5f23196c/pkg/server/node.go#L2134)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: it took me a bit to understand where this `"m"` comes from. Do you think it'd be worth to do something like:
```
var dummyVersionSetting settings.VersionSetting // global
...
func (n *Node) getVersionSettingWithUpdateCh(...) {
...
  Value: settings.EncodedValue {
    Type: dummyVersionSetting.Typ(),
     ...
  }
...
}
```
</blockquote></details>

Good idea, done. (#106037)

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106416)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @healthy-pod, @herkolategan, @srosenberg, @stevendanna, and @yuzefovich)

___
*[`pkg/cmd/roachtest/tests/multitenant_upgrade.go` line 237 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106416#-NZlYoDu5Ie2ebS_rFZv:-NZlvTWg2nVY6yZrlpVP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4334dcc8f7e061382f68374acb73b67f2e84a6e/pkg/cmd/roachtest/tests/multitenant_upgrade.go#L237)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

@healthy-pod can you see about this one?
</blockquote></details>

Done.

**Review by healthy-pod — APPROVED** [review]

**Comment by knz** [comment]
TFYR!

bors r=healthy-pod

**Review by yuzefovich — APPROVED** [review]
> Reviewed 3 of 3 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106416)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @srosenberg, and @stevendanna)

**Pull request merged**
