### PR TITLE
opt: FK fixes and add fk tests to fk_opt

### PR DESCRIPTION
**Pull request by RaduBerinde**
This PR contains a bunch of misc fixes for FKs and adds all the `fk` tests to `fk_opt`, with adjustments as necessary.

Commits:
#### opt: set FK delete action in the catalog

We weren't setting the delete action in the opt catalog. This change
fixes this and makes the catalog table formatter show the actions so
we can test this easily.

Release note: None

#### opt: fix and improve FK check errors

Improved error message when we try to insert NULLs with MATCH FULL.
And fixing a typo when keys have multiple columns.

Release note: None

#### sql: don't execute postqueries if the main query errored out

We weren't checking `res.Err()` and that causes an obscure "txn
already encountered an error".

Release note: None

#### sql: minor cleanup in logic test

Release note: None

#### opt: copy fk tests

Copy the `fk` tests and run them with the new opt-driven FK checks.
This commit only copies the tests; the next commit will fix them up as
needed.

Release note: None

#### opt: update fk_opt tests

The previous commit copied the `fk` tests into `fk_opt`. In this
commit we update them to pass. Mostly error messages fixes, and one
case where the improved semantics allow a statement that previously
failed.

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39462#-:-Lm5HZDd79itSVXSpCDh:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj and @RaduBerinde)

___
*[pkg/sql/logictest/testdata/logic_test/fk_opt, line 727 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39462#-Lm5HKEL1c6m2qk9cS5-:-Lm5HKEL1c6m2qk9cS50:b1gntvy) ([raw file](https://github.com/cockroachdb/cockroach/blob/380baaf9357fb2f498b66f6b75ffef4f4ae677d5/pkg/sql/logictest/testdata/logic_test/fk_opt#L727)):*
> ```
> DELETE FROM pairs WHERE id = 1
> 
> statement error foreign key violation: values \[100 'one'\] in columns \[src dest\] referenced in table "refpairs"
> ```

why did you remove this tracing stuff?
___
*[pkg/sql/logictest/testdata/logic_test/fk_opt, line 10 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39462#-Lm5HOGH9L-k9xQgKE90:-Lm5HOGH9L-k9xQgKE91:bdjiov1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e62b128086d6b09b4c2cf12bf5e0ae7e9b4fc288/pkg/sql/logictest/testdata/logic_test/fk_opt#L10)):*
> ```
> # Disable automatic stats to avoid flakiness.
> statement ok
> SET CLUSTER SETTING sql.stats.automatic_collection.enabled = false
> ```

I think the flakiness was due to printing the trace output
___
*[pkg/sql/opt/exec/execbuilder/mutation.go, line 439 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39462#-Lm5FX1J1J_nHTj0d782:-Lm5FX1J1J_nHTj0d783:b-cy216j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea0b595f2e99004c828698663145aeedc1652fa7/pkg/sql/opt/exec/execbuilder/mutation.go#L439)):*
> ```Go
> 						break
> 					}
> 					details.WriteString(row[query.getColumnOrdinal(col)].String())
> ```

can change this to use `d`

**Review by RaduBerinde — COMMENTED** [review]
Rebased and added a commit (r6) which fixes the on delete action in the opt catalog.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39462#-:-LmfCoki3dCQrkTu9jwD:b-34p7h0)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj and @rytaft)

___
*[pkg/sql/logictest/testdata/logic_test/fk_opt, line 727 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39462#-Lm5HKEL1c6m2qk9cS5-:-LmekPmy6eKYQ-TfnxV_:bn71o61) ([raw file](https://github.com/cockroachdb/cockroach/blob/380baaf9357fb2f498b66f6b75ffef4f4ae677d5/pkg/sql/logictest/testdata/logic_test/fk_opt#L727)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

why did you remove this tracing stuff?
</blockquote></details>

It was checking specific trace events from the old FK execution path. 
___
*[pkg/sql/logictest/testdata/logic_test/fk_opt, line 10 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39462#-Lm5HOGH9L-k9xQgKE90:-LmekpRf5HlY-Kr4Wv-O:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e62b128086d6b09b4c2cf12bf5e0ae7e9b4fc288/pkg/sql/logictest/testdata/logic_test/fk_opt#L10)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think the flakiness was due to printing the trace output
</blockquote></details>

Removed.
___
*[pkg/sql/opt/exec/execbuilder/mutation.go, line 439 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39462#-Lm5FX1J1J_nHTj0d782:-LmelCln1tA_1AWfTdhH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea0b595f2e99004c828698663145aeedc1652fa7/pkg/sql/opt/exec/execbuilder/mutation.go#L439)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

can change this to use `d`
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 4 of 10 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 2 of 2 files at r9, 1 of 2 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39462#-:-LmidVBh-FtMKR_c6-Oh:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj)

**Comment by RaduBerinde** [comment]
@justinj @jordanlewis will need a review on the first commit (it's the problem we discussed yesterday).

**Review by justinj — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39462#-:-Lmp0VzM-3Ckmmrwjwha:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @justinj)

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39462)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/opt_catalog.go, line 585 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39462#-LmqdsHV-AbVJlLVtXsH:-LmqdsHV-AbVJlLVtXsI:biqogbv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d2c2627810bc19216b4c445dc8ee318db1763e8/pkg/sql/opt_catalog.go#L585)):*
> ```Go
> 			validity:          fk.Validity,
> 			match:             fk.Match,
> 			deleteAction:      fk.OnDelete,
> ```

This is fine as long as you're sure that `match` only gets used in the lookup direction, not the delete direction. I'm not sure why I added this TODO in the first place as it seems very specific to the HP.

**Pull request merged**
