### PR TITLE
sql: don't show the "hidden" column flag in EXPLAIN

### PR DESCRIPTION
**Pull request by RaduBerinde**
The ResultColumns.Hidden flag is used internally; it does not carry
useful information for users and should not be visible in EXPLAIN.

Release note (sql change): EXPLAIN no longer shows the "hidden"
annotation for columns.

### CODE REVIEW

**Review by mgartner — COMMENTED** [review]
:lgtm: 

> Reviewed 11 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51837#-:-MCwV2LzCvOZxid6suhq:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @yuzefovich)

___
*[pkg/sql/sqlbase/result_columns.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51837#-MCwUrtu3505A_9j6n6O:-MCwUrtvCG-yoQN3dEA0:bn7k5pj) ([raw file](https://github.com/cockroachdb/cockroach/blob/42e24c4bff991b615d197d646f0f771a8bfbc4a2/pkg/sql/sqlbase/result_columns.go#L108)):*
> ```Go
> // The column types are printed if printTypes is true.
> // The hidden property is printed if showHidden is true.
> func (r ResultColumns) String(printTypes bool, showHidden bool) string {
> ```

You planning on passing `showHidden=true` elsewhere? I only see the one call passing `false`.

**Review by mgartner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51837#-:-MCwV7FX9eEebF5dFwWK:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @yuzefovich)

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/sqlbase/result_columns.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51837#-MCwUrtu3505A_9j6n6O:-MCwY4Ia6LfAOumLituv:bngm8zq) ([raw file](https://github.com/cockroachdb/cockroach/blob/42e24c4bff991b615d197d646f0f771a8bfbc4a2/pkg/sql/sqlbase/result_columns.go#L108)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

You planning on passing `showHidden=true` elsewhere? I only see the one call passing `false`.
</blockquote></details>

No, there's no other caller. Just wanted to keep it general.

**Review by RaduBerinde — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51837#-:-MCwYT0Z6VCp1odkuw1N:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

**Pull request merged**
