### PR TITLE
sql: alias SHOW STATEMENTS to SHOW QUERIES

### LINKED ISSUE #56240: sql: alias SHOW STATEMENTS to SHOW QUERIES
As we seek to make replicate functionality between the db console and the SQL shell we should seek consistency in terminology as well.

In the db console we offer Sessions, Transactions, and Statements pages. 
We mirror this in the SQL shell with `SHOW SESSIONS`, `SHOW TRANSACTIONS`, and `SHOW QUERIES.` (although these only show active sessions, transactions, and queries as opposed to the db consoles historical information). 

SHOW QUERIES and Statements are not consistent. Let's alias `SHOW STATEMENTS` to be the same as `SHOW QUERIES` so that we can demonstrate consistency. We don't need to retire `SHOW QUERIES` since its already in use but we should gradually emphasize it in the docs in favor of the new `SHOW STATEMENTS` for consistency.  

```SQL
root@127.0.0.1:57627/movr> show statements;
ERROR: unrecognized configuration parameter "statements"
SQLSTATE: 42704
```

### PR DESCRIPTION
**Pull request by ivern**
Fixes #56240

This commit makes SHOW STATEMENTS a (preferred) alias of SHOW QUERIES.

Release note (sql change): SHOW STATEMENTS is now an alias of SHOW QUERIES.
The new syntax is preferred by the SQL parser.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
Thanks for working on this! The code change looks good to me.

I just have one request -- could you add a release note to the commit message and PR? (the note is used as a signal to our docs team that a change is required)

```
Release note (sql change): SHOW STATEMENTS is now an alias of SHOW QUERIES.
The new syntax is preferred by the SQL parser.
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58072#-:-MOy7kQaCNVC7zrziFfh:b-h8kezf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Comment by ivern** [comment]
@rafiss thanks for the comments, I've applied your suggested release notes to the commit and PR.

**Review by rafiss — APPROVED** [review]
lgtm! I will merge it on Monday. Leaving it open as a reminder to figure out the question you asked about CANCEL QUERY

**Pull request merged**
