### PR TITLE
sql: refactoring virtualSchemaTable.allTableNames into undefinedTables

### LINKED ISSUE #61801: sql: organize / track better which vtables are implemented
Currently, we have an `allTableNames` field which we try to list all the name of all vtables. This is useful for providing error messages when a user tries to access a vtable that we know is unimplemented and have in the `allTableNames` list. The big issue with this is that it is all manual and does not correspond to our actual vtable definitions. 

```
type virtualSchema struct {
	name           string
	allTableNames  map[string]struct{}
	tableDefs      map[descpb.ID]virtualSchemaDef
	tableValidator func(*descpb.TableDescriptor) error // optional
	// Some virtual tables can be used if there is no current database set; others can't.
	validWithNoDatabaseContext bool
	// Some virtual schemas (like pg_catalog) contain types that we can resolve.
	containsTypes bool
}
```

Adding a name is manual and prone to error. 

Some options we have moving forward with this is to 
1. Remove the field (it is only used for error logging), we have a separate `pg_catalog_expected_diffs.json` file now which we can use to track.
2. Make it correspond to the the actual tables / table ids somehow so it's less manual and we know if we implement it or not. Can also add tests to check the name against if the table desc is created.

In general, I think it would be nice to be able to track the status of vtables and see their implementations all in one place. Using a map that maps the table name to a struct holding it's definition, oid and status could be nice / an option?

We should choose one reliable source of truth on the status of different vtables.

### PR DESCRIPTION
**Pull request by mnovelodou**
Previously, allTableNames have implemented and unimplemented tableNames
This was inadequate because the duplicity makes difficult to maintain
To address this, this patch refactors allTableNames into
undefinedTables to keep only the tables that are not in tableDefs

Release note: None

Fixes #61801

### CODE REVIEW

**Review by RichardJCai — CHANGES_REQUESTED** [review]
One thought I had was instead of referring to these tables as unimplementedTables, maybe we should use undefinedTables since we have tables that are defined but technically not implemented as well.

These tables can strictly be the ones that are undefined. Thoughts?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63144#-:-MXcrAYn7nRksxxBBULu:bvd4lsg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mnovelodou)

___
*[pkg/sql/pg_metadata_test.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63144#-MXcq93f151S4t8g1z98:-MXcq93g4JoNTrc7hqui:bjndos8) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc0c22b6d8332978c56a802e322647167b4e30dc/pkg/sql/pg_metadata_test.go#L82)):*
> ```Go
> 	tableDefsDeclaration               = `tableDefs: map[descpb.ID]virtualSchemaDef{`
> 	tableDefsTerminal                  = `},`
> 	unimplementedTableNamesDeclaration = `unimplementedTableNames: buildStringSet(`
> ```

One thing I just thought of is if we change the code in pg_catalog.go, if we rename this variable again for whatever reason, we might miss updating the corresponding code here.

Is there a test or anything that keeps this in check? I definitely see this getting or some part of this code being updated in the future.
What happens right now if we update the variable name for unimplementedTableNames without changing this code here?
___
*[pkg/sql/pg_metadata_test.go, line 515 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63144#-MXcpZa5AvmOloxbmYIb:-MXcpZa5AvmOloxbmYIc:b-95fvkb) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc0c22b6d8332978c56a802e322647167b4e30dc/pkg/sql/pg_metadata_test.go#L515)):*
> ```Go
> 
> // getTableNameFromCreateTable uses pkg/sql/parser to analize CREATE TABLE
> // statement to retrieve table name
> ```

nit: Missing period
___
*[pkg/sql/virtual_schema_test.go, line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63144#-MXcql7I6M6tuGo_MSvJ:-MXcql7I6M6tuGo_MSvK:b-smu0mz) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc0c22b6d8332978c56a802e322647167b4e30dc/pkg/sql/virtual_schema_test.go#L12)):*
> ```Go
> 
> // VirtualSchemaTest validates virtualSchema that unimplementedTableNames
> // only have tables that do not have a virtualSchemaTable defined.
> ```

nit: only has tables

**Review by mnovelodou — COMMENTED** [review]
Love it, I've been having difficulties to separate what is a unimplemented and undefined. Let me work on that change.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63144#-:-MXcuOroExwUuEx-S66f:b-xsvsjm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[pkg/sql/pg_metadata_test.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63144#-MXcq93f151S4t8g1z98:-MXcsCXd8RfmZO4bFWzu:byaa3e0) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc0c22b6d8332978c56a802e322647167b4e30dc/pkg/sql/pg_metadata_test.go#L82)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

One thing I just thought of is if we change the code in pg_catalog.go, if we rename this variable again for whatever reason, we might miss updating the corresponding code here.

Is there a test or anything that keeps this in check? I definitely see this getting or some part of this code being updated in the future.
What happens right now if we update the variable name for unimplementedTableNames without changing this code here?
</blockquote></details>

If you don't change the code here, it will break the code in charge of modifying the unimplementedTableNames, I mean, no actual production code will break here, What I can do is to create a goTest that validates this unimplementedTableNamesDeclaration is a field of virtualSchema, I think I can do some reflection here.
___
*[pkg/sql/pg_metadata_test.go, line 515 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63144#-MXcpZa5AvmOloxbmYIb:-MXcth0X657es3gb0k-7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc0c22b6d8332978c56a802e322647167b4e30dc/pkg/sql/pg_metadata_test.go#L515)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

nit: Missing period
</blockquote></details>

Done.
___
*[pkg/sql/virtual_schema_test.go, line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63144#-MXcql7I6M6tuGo_MSvJ:-MXcuJIB7qGeLbshevhq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc0c22b6d8332978c56a802e322647167b4e30dc/pkg/sql/virtual_schema_test.go#L12)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

nit: only has tables
</blockquote></details>

Done.

**Review by RichardJCai — COMMENTED** [review]
Looks pretty much good to me, small nits.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63144#-:-MXoHSg_5wJ8aQ6JWeXX:bdz8n4j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mnovelodou and @RichardJCai)

___
*[pkg/sql/pg_metadata_test.go, line 515 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63144#-MXoDmdD-vH47ZNaA8OW:-MXoDmdD-vH47ZNaA8OX:b745ds6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1b165984104b1f800f879cc563a70caaa8fb8ec/pkg/sql/pg_metadata_test.go#L515)):*
> ```Go
> }
> 
> // getTableNameFromCreateTable uses pkg/sql/parser to analize CREATE TABLE
> ```

analize -> analyze
___
*[pkg/sql/pg_metadata_test.go, line 529 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63144#-MXoE1TjD9AqG3JP8svo:-MXoE1TjD9AqG3JP8svp:bml4y4u) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1b165984104b1f800f879cc563a70caaa8fb8ec/pkg/sql/pg_metadata_test.go#L529)):*
> ```Go
> // getUndefinedTablesText retrieves pgCatalog.undefinedTables, then it merges the
> // new table names and formats the replacement text.
> func getUndefinedTablesText(notImplemented PGMetadataTables, vs virtualSchema) (string, error) {
> ```

I think notImplemented should become undefinedTables here
___
*[pkg/sql/pg_metadata_test.go, line 543 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63144#-MXoFcUfB2pS4zxLheb8:-MXoFcUfB2pS4zxLheb9:b3xv6xv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1b165984104b1f800f879cc563a70caaa8fb8ec/pkg/sql/pg_metadata_test.go#L543)):*
> ```Go
> 	removeTables := make(map[string]struct{})
> 	for _, table := range vs.tableDefs {
> 		tableName, err := getTableNameFromCreateTable(table.getSchema())
> ```

I'm surprised we have to do all this work to grab the name of the table, we probably shoulda added a name field and populated it upstream but I don't want to introduce more work here right now since that would be fairly tedious.

**Review by mnovelodou — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63144#-:-MXrPWYmAUIUD8vTbDK7:b-896fix)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[pkg/sql/pg_metadata_test.go, line 515 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63144#-MXoDmdD-vH47ZNaA8OW:-MXrPT6zBTwxRll-VvyH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1b165984104b1f800f879cc563a70caaa8fb8ec/pkg/sql/pg_metadata_test.go#L515)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

analize -> analyze
</blockquote></details>

Done.
___
*[pkg/sql/pg_metadata_test.go, line 529 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63144#-MXoE1TjD9AqG3JP8svo:-MXrH5GHE3ZIp43ODp7y:b-bi4bu0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1b165984104b1f800f879cc563a70caaa8fb8ec/pkg/sql/pg_metadata_test.go#L529)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I think notImplemented should become undefinedTables here
</blockquote></details>

Actually, they are notImplemented that will be defined as tableDefs after this process ran, so here it is correct, but I will rename it as newTables for better readability
___
*[pkg/sql/pg_metadata_test.go, line 543 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63144#-MXoFcUfB2pS4zxLheb8:-MXrHdc05ky6hEPKUA3V:b-kn7go2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1b165984104b1f800f879cc563a70caaa8fb8ec/pkg/sql/pg_metadata_test.go#L543)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I'm surprised we have to do all this work to grab the name of the table, we probably shoulda added a name field and populated it upstream but I don't want to introduce more work here right now since that would be fairly tedious.
</blockquote></details>

I don't feel it like a lot of work, initially in this file I was using a regular expression, here I am just reusing code that parses the CREATE TABLE but I don't feel it is really a big deal. I think this isn't likely to fail due to a refactoring unless you stop using "CREATE TABLE" for this.

By the way adding a name might do this code more prone for human failure as there is CREATE TABLE name and there would be another tableName field.

**Review by RichardJCai — APPROVED** [review]
Thanks for this! Overall looks good to me

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63144#-:-MY7JGaCD6Kx6oVQvPOt:bnf4qcf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mnovelodou and @RichardJCai)

___
*[pkg/sql/pg_metadata_test.go, line 543 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63144#-MXoFcUfB2pS4zxLheb8:-MY7Ih0L9znGqgd7-TqQ:b-rh7jg7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1b165984104b1f800f879cc563a70caaa8fb8ec/pkg/sql/pg_metadata_test.go#L543)):*
<details><summary><i>Previously, mnovelodou (Miguel Novelo) wrote…</i></summary><blockquote>

I don't feel it like a lot of work, initially in this file I was using a regular expression, here I am just reusing code that parses the CREATE TABLE but I don't feel it is really a big deal. I think this isn't likely to fail due to a refactoring unless you stop using "CREATE TABLE" for this.

By the way adding a name might do this code more prone for human failure as there is CREATE TABLE name and there would be another tableName field.
</blockquote></details>

Yeah that's fair
___
*[pkg/sql/pg_metadata_test.go, line 741 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63144#-MY7Izob3Ft1m-k7uMck:-MY7Izob3Ft1m-k7uMcl:bnpi0ru) ([raw file](https://github.com/cockroachdb/cockroach/blob/345f9d77f1fa7c1eae12805dea808bd4e86a3183/pkg/sql/pg_metadata_test.go#L741)):*
> ```Go
> 	propertyIndex := strings.IndexRune(undefinedTablesDeclaration, ':')
> 	property := undefinedTablesDeclaration[:propertyIndex]
> 	// Using pgCatalog but information_schema is a virtualSchema as well
> ```

Reading off your comment here, should we check information_schema as well?

**Review by mnovelodou — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63144)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[pkg/sql/pg_metadata_test.go, line 543 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63144#-MXoFcUfB2pS4zxLheb8:-MY7LLLa7Pyc19EA2uUO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1b165984104b1f800f879cc563a70caaa8fb8ec/pkg/sql/pg_metadata_test.go#L543)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Yeah that's fair
</blockquote></details>

Done.
___
*[pkg/sql/pg_metadata_test.go, line 741 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63144#-MY7Izob3Ft1m-k7uMck:-MY7LN3k3T2dsUos6sZN:b-go97e9) ([raw file](https://github.com/cockroachdb/cockroach/blob/345f9d77f1fa7c1eae12805dea808bd4e86a3183/pkg/sql/pg_metadata_test.go#L741)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Reading off your comment here, should we check information_schema as well?
</blockquote></details>

I don't think so, this is checking the type, not a particular object, I coudn't see how to just use the type for doing this, so I am passing pg_catalog, if you have a suggestion, I can check using another way.

**Comment by RichardJCai** [comment]
Sounds good to me

bors r+

**Pull request merged**
