### PR TITLE
sql/sqlbase: batch single-operation foreign key checks

### PR DESCRIPTION
**Pull request by jordanlewis**
Perform all foreign key checks for a single insert/update/delete row in a single kv batch.

Updates #15157.

### CODE REVIEW

**Comment by jordanlewis** [comment]
I updated the InsertFK benchmark to have 2 foreign keys to check, and got the following benchmark results. The performance improvements would presumably be even more dramatic with more foreign key checks to perform per key.

```
SQL/Cockroach/InsertFK/count=1-8               696µs ± 2%   598µs ± 1%  -14.17%  (p=0.000 n=10+10)
SQL/Cockroach/InsertFK/count=10-8             2.76ms ± 2%  2.04ms ± 5%  -25.89%  (p=0.000 n=10+10)
SQL/Cockroach/InsertFK/count=100-8            23.7ms ± 4%  16.7ms ± 2%  -29.38%  (p=0.000 n=10+10)
SQL/Cockroach/InsertFK/count=1000-8            246ms ± 3%   169ms ± 3%  -31.40%  (p=0.000 n=10+10)
```

**Comment by jordanlewis** [comment]
Updated the benchmarks to do varying number of foreign keys - 1, 5, or 10.

```
SQL/Cockroach/InsertFK/count=1/nFks=1-8       546µs ± 1%   547µs ± 2%     ~     (p=0.963 n=9+8)
SQL/Cockroach/InsertFK/count=1/nFks=5-8      1.05ms ± 3%  0.79ms ± 2%  -25.02%  (p=0.000 n=10+10)
SQL/Cockroach/InsertFK/count=1/nFks=10-8     1.70ms ± 1%  1.10ms ± 5%  -35.15%  (p=0.000 n=10+10)
SQL/Cockroach/InsertFK/count=10/nFks=1-8     1.82ms ± 3%  1.80ms ± 2%     ~     (p=0.853 n=10+10)
SQL/Cockroach/InsertFK/count=10/nFks=5-8     6.19ms ± 2%  3.82ms ± 3%  -38.33%  (p=0.000 n=10+10)
SQL/Cockroach/InsertFK/count=10/nFks=10-8    12.0ms ± 4%   6.3ms ± 4%  -47.76%  (p=0.000 n=10+10)
SQL/Cockroach/InsertFK/count=100/nFks=1-8    13.9ms ± 2%  13.3ms ± 1%   -4.82%  (p=0.000 n=10+10)
SQL/Cockroach/InsertFK/count=100/nFks=5-8    59.8ms ± 1%  32.6ms ± 4%  -45.46%  (p=0.000 n=9+10)
SQL/Cockroach/InsertFK/count=100/nFks=10-8    114ms ± 3%    64ms ±32%  -44.31%  (p=0.000 n=10+10)
SQL/Cockroach/InsertFK/count=1000/nFks=1-8    135ms ± 5%   149ms ± 8%  +10.24%  (p=0.000 n=10+10)
SQL/Cockroach/InsertFK/count=1000/nFks=5-8    686ms ± 8%   406ms ±18%  -40.86%  (p=0.000 n=10+9)
SQL/Cockroach/InsertFK/count=1000/nFks=10-8   1.42s ± 9%   0.70s ±16%  -50.83%  (p=0.000 n=10+10)
```

Not sure why the count=1000, nFks=1 case gets +10% whereas count=100, nFks=1 gets -5%. Doesn't make sense to me. Noise?

**Comment by petermattis** [comment]
I'll leave reviewing the code to @dt, but LGTM regarding the speedup.

> Not sure why the count=1000, nFks=1 case gets +10% whereas count=100, nFks=1 gets -5%. Doesn't make sense to me. Noise?

That's a lot of noise, and notice that you had no outliers that were excluded by `benchstat`. Probably worth figuring out what is going on there.

**Comment by dt** [comment]
@jordanlewis can you include `-benchmem` too ?

that 1k number has me wondering if we might need an upper bound on the batch size, flushing batched checks as we go when handling larger numbers of rows.

---

Reviewed 3 of 3 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18730#-:-KutQTg7lkLBLpuSMadI:b-sy0s4c)*

**Comment by jordanlewis** [comment]
We'll need an upper bound on the batch size eventually, but at the moment the batching is only done *per-op*, meaning the max size of the batch is the number of foreign key checks to perform for that operation.

I'm planning to get to cross-op batching at some point, and that's when I'll add the batch size upper bound.

**Comment by jordanlewis** [comment]
```
name                                         old time/op    new time/op    delta
SQL/Cockroach/InsertFK/count=1/nFks=1-8         452µs ± 2%     479µs ± 9%      ~     (p=0.052 n=10+10)
SQL/Cockroach/InsertFK/count=1/nFks=5-8         853µs ± 4%     635µs ± 5%   -25.58%  (p=0.000 n=10+10)
SQL/Cockroach/InsertFK/count=1/nFks=10-8       1.37ms ± 4%    0.90ms ± 5%   -34.14%  (p=0.000 n=10+10)
SQL/Cockroach/InsertFK/count=10/nFks=1-8       1.43ms ± 5%    1.44ms ± 2%      ~     (p=0.095 n=9+10)
SQL/Cockroach/InsertFK/count=10/nFks=5-8       4.59ms ± 2%    3.00ms ± 2%   -34.59%  (p=0.000 n=10+9)
SQL/Cockroach/InsertFK/count=10/nFks=10-8      9.01ms ± 4%    5.01ms ± 4%   -44.43%  (p=0.000 n=9+10)
SQL/Cockroach/InsertFK/count=100/nFks=1-8      10.3ms ± 3%    10.4ms ± 2%      ~     (p=0.393 n=10+10)
SQL/Cockroach/InsertFK/count=100/nFks=5-8      42.3ms ± 1%    28.2ms ± 3%   -33.50%  (p=0.000 n=9+10)
SQL/Cockroach/InsertFK/count=100/nFks=10-8     82.8ms ± 3%    47.4ms ±10%   -42.73%  (p=0.000 n=10+10)
SQL/Cockroach/InsertFK/count=1000/nFks=1-8      102ms ± 2%     112ms ± 7%    +9.52%  (p=0.000 n=10+10)
SQL/Cockroach/InsertFK/count=1000/nFks=5-8      500ms ±10%     394ms ±24%   -21.21%  (p=0.000 n=10+10)
SQL/Cockroach/InsertFK/count=1000/nFks=10-8     1.04s ±13%     0.62s ±22%   -40.35%  (p=0.000 n=10+10)

name                                         old alloc/op   new alloc/op   delta
SQL/Cockroach/InsertFK/count=1/nFks=1-8        57.5kB ± 1%    57.8kB ± 1%    +0.52%  (p=0.003 n=9+10)
SQL/Cockroach/InsertFK/count=1/nFks=5-8         124kB ± 1%     121kB ± 1%    -2.17%  (p=0.000 n=10+10)
SQL/Cockroach/InsertFK/count=1/nFks=10-8        226kB ± 1%     216kB ± 1%    -4.29%  (p=0.000 n=10+9)
SQL/Cockroach/InsertFK/count=10/nFks=1-8        280kB ± 1%     280kB ± 1%      ~     (p=0.529 n=10+10)
SQL/Cockroach/InsertFK/count=10/nFks=5-8        867kB ± 2%     825kB ± 1%    -4.84%  (p=0.000 n=10+10)
SQL/Cockroach/InsertFK/count=10/nFks=10-8      1.67MB ± 1%    1.58MB ± 2%    -5.24%  (p=0.000 n=10+10)
SQL/Cockroach/InsertFK/count=100/nFks=1-8      2.39MB ± 4%    2.47MB ± 2%    +3.44%  (p=0.000 n=10+10)
SQL/Cockroach/InsertFK/count=100/nFks=5-8      9.72MB ± 1%    9.00MB ± 1%    -7.44%  (p=0.000 n=10+10)
SQL/Cockroach/InsertFK/count=100/nFks=10-8     17.5MB ± 2%    16.4MB ± 2%    -6.70%  (p=0.000 n=10+10)
SQL/Cockroach/InsertFK/count=1000/nFks=1-8     26.8MB ± 1%    54.3MB ±39%  +102.34%  (p=0.000 n=8+10)
SQL/Cockroach/InsertFK/count=1000/nFks=5-8      294MB ±57%     295MB ±32%      ~     (p=0.684 n=10+10)
SQL/Cockroach/InsertFK/count=1000/nFks=10-8     778MB ±54%     383MB ±41%   -50.69%  (p=0.000 n=10+10)

name                                         old allocs/op  new allocs/op  delta
SQL/Cockroach/InsertFK/count=1/nFks=1-8           515 ± 1%       516 ± 1%      ~     (p=0.497 n=8+8)
SQL/Cockroach/InsertFK/count=1/nFks=5-8         1.13k ± 3%     1.03k ± 1%    -8.94%  (p=0.000 n=10+8)
SQL/Cockroach/InsertFK/count=1/nFks=10-8        1.93k ± 4%     1.68k ± 3%   -13.23%  (p=0.000 n=10+10)
SQL/Cockroach/InsertFK/count=10/nFks=1-8        2.12k ± 2%     2.11k ± 1%      ~     (p=0.159 n=8+9)
SQL/Cockroach/InsertFK/count=10/nFks=5-8        7.69k ± 5%     6.56k ± 1%   -14.71%  (p=0.000 n=10+8)
SQL/Cockroach/InsertFK/count=10/nFks=10-8       14.4k ± 2%     12.1k ± 2%   -15.94%  (p=0.000 n=9+10)
SQL/Cockroach/InsertFK/count=100/nFks=1-8       18.4k ± 5%     18.9k ± 2%    +2.97%  (p=0.011 n=9+9)
SQL/Cockroach/InsertFK/count=100/nFks=5-8       77.8k ± 4%     65.0k ± 6%   -16.44%  (p=0.000 n=10+10)
SQL/Cockroach/InsertFK/count=100/nFks=10-8       148k ± 3%      121k ± 2%   -18.37%  (p=0.000 n=9+8)
SQL/Cockroach/InsertFK/count=1000/nFks=1-8       199k ±12%      440k ±43%  +120.97%  (p=0.000 n=10+10)
SQL/Cockroach/InsertFK/count=1000/nFks=5-8      2.44M ±64%     2.35M ±36%      ~     (p=0.739 n=10+10)
SQL/Cockroach/InsertFK/count=1000/nFks=10-8     6.53M ±58%     2.93M ±48%   -55.13%  (p=0.000 n=10+10)
```

There's that count=1000,nFks=1 again. I'll figure out what's up here.

**Comment by jordanlewis** [comment]
```
name                                         old time/op  new time/op  delta
SQL/Cockroach/InsertFK/count=1000/nFks=1-8   95.0ms ± 1%  91.9ms ± 3%   -3.25%  (p=0.000 n=8+10)
SQL/Cockroach/InsertFK/count=1000/nFks=5-8    447ms ± 5%   260ms ± 8%  -41.89%  (p=0.000 n=10+9)
SQL/Cockroach/InsertFK/count=1000/nFks=10-8   908ms ± 1%   467ms ± 3%  -48.53%  (p=0.000 n=9+10)

name                                         old time/op    new time/op    delta
SQL/Cockroach/InsertFK/count=1000/nFks=1-8     92.0ms ± 2%    95.0ms ± 5%   +3.20%  (p=0.017 n=9+10)
SQL/Cockroach/InsertFK/count=1000/nFks=5-8      424ms ± 5%     265ms ± 6%  -37.36%  (p=0.000 n=9+9)
SQL/Cockroach/InsertFK/count=1000/nFks=10-8     882ms ± 3%     485ms ±10%  -44.98%  (p=0.000 n=10+10)

name                                         old alloc/op   new alloc/op   delta
SQL/Cockroach/InsertFK/count=1000/nFks=1-8     23.1MB ± 1%    23.2MB ± 1%     ~     (p=0.089 n=10+10)
SQL/Cockroach/InsertFK/count=1000/nFks=5-8      100MB ± 1%      94MB ± 1%   -5.94%  (p=0.000 n=10+10)
SQL/Cockroach/InsertFK/count=1000/nFks=10-8     201MB ± 1%     187MB ± 1%   -6.89%  (p=0.000 n=10+9)

name                                         old allocs/op  new allocs/op  delta
SQL/Cockroach/InsertFK/count=1000/nFks=1-8       169k ± 6%      168k ± 7%     ~     (p=0.912 n=10+10)
SQL/Cockroach/InsertFK/count=1000/nFks=5-8       739k ±10%      625k ±11%  -15.44%  (p=0.000 n=10+10)
SQL/Cockroach/InsertFK/count=1000/nFks=10-8     1.46M ± 4%     1.21M ± 6%  -17.04%  (p=0.000 n=10+10)
```

Much better. The problem was that I was pointlessly `make`ing a 0-length slice during initialization.

**Review by dt — APPROVED** [review]
Nice!

**Comment by jordanlewis** [comment]
TFTRs!

**Pull request merged**
