### PR TITLE
sql/pgwire: enable automatic kill of idle SQL transactions.

### PR DESCRIPTION
**Pull request by knz**
While an KV transaction is ongoing other KV transactions can be held
up and wait. This can become a problem when a SQL transaction holds a
SQL-level transaction open for a long time and there is a KV
transaction opened for it.

The particular problem is the case of a client disappearing under the
TCP level without a RST (connection closed by peer) while a KV
transaction is ongoing.

The traditional solution to this problem is a "keepalive protocol"
like what SSH and other TCP protocols do. However pgwire does not have
the notion of a keepalive packet; neither does the myriad of extant
pgwire drivers for different languages and frameworks.

Instead, this patch alleviates the problem by introducing a
session-level timeout on inactivity from a client during a KV
transaction. The timeout is only checked in the particular case when a
KV transaction is ongoing, so that a user that interactively enters
COMMIT and a bunch of SELECTs can insert the SELECTs and view their
results without time restriction up to the first statement (INSERT,
CREATE etc) that effectively creates a KV transaction.

The timeout is currently configurable via a new session-flag called
TRANSACTION_IDLE_TIMEOUT, that can be SET and SHOWed from SQL. Its
DEFAULT value is customizable via the environment variable
COCKROACH_TXN_IDLE_TIMEOUT and defaults to 15 seconds. This
implementation could be later extended to take the default timeout
from a user-level configuration variable.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10188)

### CODE REVIEW

**Comment by knz** [comment]
Notes:
- I do not feel strongly about this one and if you think it's a bad idea we can kill the PR.
- this is separate from #10187, but after #10187 is merged we can extend this PR with some kind of background heartbeat from our own SQL shell.

**Comment by knz** [comment]
@andreimatei I think I made a mistake by checking session.TxnState.State. Is that reflecting the existence of a KV transaction appropriately? (Maybe not) Should I check session.txnProto instead?

**Comment by andreimatei** [comment]
Before I review anything, how would you feel about dropping this in favor of a per-transaction deadline (and we can debate if the default is a few seconds or no deadline)?
One concern I have with your approach is how it interacts with txn restarts: if a txn is forced to restart (with a `TxnRestartError`, not a `TxnAbortError`, so there's still a kv txn) and that bubbles up to the client, the client now has a ticking clock until it needs to send the prefix of the txn. On the original attempt, there was no ticking clock for computing this prefix. So we've created a sort of asymmetry between the original attempt and subsequent attempts. This also means that this timeout doesn't just start applying once you've done the first INSERT/UPDATE/DELETE statement.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10188#-:-KUu-wkMcfJy_bTNz-ie:b-mne3hi)*

**Comment by knz** [comment]
So what kind of per-transaction deadline did you have in mind?

As to the timeout applying also after a restart, this is a feature not a bug. This patch wants to actively close KV transactions that have active intents. After a retry error, the KV transaction and its intents is still alive. That's why the timeout still applies.

**Comment by andreimatei** [comment]
Maybe it's a feature, but the point is you can't have it both ways: you can't claim that this timeout only takes effect in more narrow circumstances, like after a txn started doing writes; it's always in effect.

The deadline I'm thinking of would be set inside a transaction with a `SET` stmt, and say that if the current txn doesn't commit in x seconds, the system can roll it back. This would cover automatic retries too, and long-running statements. It would also solve the problem of dropped TCP conns you're so worried about. I'm thinking it's a more consistent mechanism compared to your proposal, and it addresses more problems.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10188#-:-KUwFKwubJ3qIUUvFykA:b-o0lzef)*

**Comment by knz** [comment]
OK and do you foresee to have this deadline opt-in or opt-out?
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bdarnell** [comment]
I think a transaction deadline is a useful feature (mysql doesn't have this feature so people often use [third-party tools](https://www.percona.com/doc/percona-toolkit/2.2/pt-kill.html) or hack up their own solution. However, it's worth noting that these tools generally kill long-running *queries* while leaving long-running transactions open). 

Delaying the start of the timer to the first write is also a good idea since our read-only transactions are cheap (and since read/write transactions are likely to be unpleasant in the shell due to restarts, most interactive transactions will be read-only). It doesn't bother me that the transaction behaves differently on retry. 

Whatever deadline we support should be opt-out instead of opt-in, and it should be possible to set it globally (and persistently), not just per session (this part can come later).

**Comment by andreimatei** [comment]
The way I think about it, the deadline would be more of a user feature than a measure for ensuring smooth operation of the cluster. That's why I'd say that if we have it, the feature should be predictable, consistent, and easy to explain. So I'm worried about measuring different things on the initial run vs a restart. Also I would like this feature to be able to kill long-running selects, or short-running select that are restarted endlessly.
We should think about per-query vs per-transaction deadlines. I was thinking per-transaction is nice because this can be useful for a user - if the whole thing is not done in 5s, then maybe the data that was read in the beginning is all but guaranteed to be stale and so it's not even worth producing a result. But per-query might have other use cases, particularly if we'd have more advanced error recovery mechanism and we didn't automatically toast the transaction (as you say).

I would hate this to happen in the shell, though, so if the feature is on by default, then maybe the shell should opt-out.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10188#-:-KV32LDD8Zch2iH_Y7YY:b-vicovh)*

**Comment by bdarnell** [comment]
I still think we should distinguish between read-only and read-write transactions (which implies that retries are handled differently from the initial run). The problem with a single deadline that affects all transactions equally is that the first time someone encounters the error that their interactive read-only transaction took too long, they'll add whatever they need to add to their `.cockroachrc` to increase their timeout, and then they'll lose the protection of the timeout on read-write transactions where it matters much more. I think this is worth the somewhat more complex model (the fact that transaction retries exist at all is a hard thing for users to understand; the added complexity of timeout behavior is a relatively small factor).

A query-level timeout might be a good idea to keep us from wasting resources on queries that can't be executed efficiently, but I think that's separate from a transaction-level timeout because in cockroachdb long-running read-write transactions can have an impact on the rest of the cluster to a much greater extent.

**Comment by tamird** [comment]
@knz does this need a rebase? It has been dormant for some time. I'm assigning @asubiotto to review post-rebase.

**Comment by bdarnell** [comment]
Do we still need this since we enabled TCP keepalives in #14063? I don't think so.

**Comment by knz** [comment]
@bdarnell indeed the main initial concern is alleviated by server-side TCP keepalives; however what do we want to do about clients that go dormant while holding an open kv txn via a sql txn, while still being active at TCP level?

**Comment by bdarnell** [comment]
Adding some sort of timeout is probably a good idea (if we don't already have one that applies here). I don't think there's an urgent need for it but it's probably worth doing in the 1.1 timeframe.

**Comment by knz** [comment]
I can resurrect this PR; would you be interested?

**Comment by bdarnell** [comment]
Yeah, I think this is worth reviving.

**Comment by dianasaur323** [comment]
@bdarnell is #5924 dependent on this? We have #5924 marked as 1.2, but this issue is marked as 1.3.

**Comment by bdarnell** [comment]
@dianasaur323 I don't see a mention of 1.3 here. This closed PR and #5924 are essentially about the same thing; we should consolidate into that issue.

**Comment by dianasaur323** [comment]
@bdarnell Ah, ok, let's just use #5924 from now on then. 1.3 is mentioned in airtable, but seems like these two are basically the same thing, so I'll just delete that other line item in airtable.

**Comment by knz** [comment]
I made a mistake by closing this PR. I know it is not up-to-date but I was still interested to have a look eventually.

**Comment by knz** [comment]
I forgot all I knew about this and probably the code is much different now. I can't see how I can keep this PR open. Closing.

**Pull request closed without merging**
