### PR TITLE
sql: refactor default privileges for all roles

### PR DESCRIPTION
**Pull request by RichardJCai**
Default privileges for all roles are refactored to be
more in line with regular roles.

Simplifies some code.

Release note: None

### CODE REVIEW

**Comment by RichardJCai** [comment]
@rafiss @arulajmani realized my choice to define DefaultPrivilegesForAllRoles separately on the DefaultPrivilegeDescriptor was probably not the way to go.

Refactored to simplify some things. PTAL before other DefaultPrivilege related prs.

**Review by rafiss — CHANGES_REQUESTED** [review]
seems like a good change! just small comments

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68459#-:-MgMtOVA0Ym-iGGU8Pv9:b3o7jd7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @RichardJCai)

___
*[pkg/sql/crdb_internal.go, line 4869 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68459#-MgMs0JmD8gcQvVwG0kW:-MgMs0JnAkCzJI3vPSXs:b-cvcdj6) ([raw file](https://github.com/cockroachdb/cockroach/blob/db90183774412c8c2e98eec0b4f11d614331ef53/pkg/sql/crdb_internal.go#L4869)):*
> ```Go
> 								if defaultPrivs.GetForAllRoles() {
> 									role = tree.DNull
> 								} else {
> ```

nit: up to you, but what do you think about the pattern
```
role := tree.DNull
if !defaultPrivs.GetForAllRoles() {
  role = tree.NewDString(defaultPrivs.GetUserProto().Decode().Normalized())
}
```
___
*[pkg/sql/pg_catalog.go, line 1184 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68459#-MgMsD4j2smxxqBsFRHo:-MgMsD4j2smxxqBsFRHp:bu8cxg0) ([raw file](https://github.com/cockroachdb/cockroach/blob/db90183774412c8c2e98eec0b4f11d614331ef53/pkg/sql/pg_catalog.go#L1184)):*
> ```Go
> 				if defaultPrivs.GetForAllRoles() {
> 					roleOid = oidZero
> 				} else {
> ```

could use a similar pattern as my earlier comment to avoid the else
___
*[pkg/sql/pg_catalog.go, line 1194 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68459#-MgMrmQUAnxywB8vqXHO:-MgMrmQUAnxywB8vqXHP:b-yiyf4r) ([raw file](https://github.com/cockroachdb/cockroach/blob/db90183774412c8c2e98eec0b4f11d614331ef53/pkg/sql/pg_catalog.go#L1194)):*
> ```Go
> 				)
> 				if err := addRow(
> 					rowOid,             // row identifier oid
> ```

looks like rowOid is never being set now

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68459)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @rafiss)

___
*[pkg/sql/crdb_internal.go, line 4869 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68459#-MgMs0JmD8gcQvVwG0kW:-MgMucJ29IpvD4fsK_be:brgt7q9) ([raw file](https://github.com/cockroachdb/cockroach/blob/db90183774412c8c2e98eec0b4f11d614331ef53/pkg/sql/crdb_internal.go#L4869)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: up to you, but what do you think about the pattern
```
role := tree.DNull
if !defaultPrivs.GetForAllRoles() {
  role = tree.NewDString(defaultPrivs.GetUserProto().Decode().Normalized())
}
```
</blockquote></details>

Yeah looks better to me
___
*[pkg/sql/pg_catalog.go, line 1184 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68459#-MgMsD4j2smxxqBsFRHo:-MgMufTECUF8WR8ZO0j4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/db90183774412c8c2e98eec0b4f11d614331ef53/pkg/sql/pg_catalog.go#L1184)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could use a similar pattern as my earlier comment to avoid the else
</blockquote></details>

Done.
___
*[pkg/sql/pg_catalog.go, line 1194 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68459#-MgMrmQUAnxywB8vqXHO:-MgMuft-1Femzqr8kXAI:b-gahd76) ([raw file](https://github.com/cockroachdb/cockroach/blob/db90183774412c8c2e98eec0b4f11d614331ef53/pkg/sql/pg_catalog.go#L1194)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

looks like rowOid is never being set now
</blockquote></details>

rowOid is set above the addRow line.

**Review by arulajmani — APPROVED** [review]
I dig the change! :lgtm: 

> Reviewed 2 of 6 files at r1, 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68459#-:-MgRj9p_0dff-Hcmbb6f:b-s13c4k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/sql/catalog/descpb/default_privilege.go, line 249 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68459#-MgRaLyl7cqt4BOPRapX:-MgRaLymA40JtjJfZSXv:bsrp4qm) ([raw file](https://github.com/cockroachdb/cockroach/blob/edef81b98bfe0a63688fc164877fea073627a137/pkg/sql/catalog/descpb/default_privilege.go#L249)):*
> ```Go
> 		}
> 		if i+1 < len(p.DefaultPrivilegesPerRole) &&
> 			!defaultPrivilegesForRole.ToDefaultPrivilegesRole().LessThan(p.DefaultPrivilegesPerRole[i+1].ToDefaultPrivilegesRole()) {
> ```

nit: long line

**Comment by RichardJCai** [comment]
TFTR!
bors r=arulajmani

**Pull request merged**
