### PR TITLE
backupccl: stop logging unsanitized backup stmt in schedule executor

### PR DESCRIPTION
**Pull request by msbutler**
Informs #99145

Release note: None

### CODE REVIEW

**Review by stevendanna — APPROVED** [review]
👍 Thanks for fixing this up.

If we wanted to go a bit further, we have some code in this file for creating redacted backup statements. We could print a redacted backup statement rather than just the schedule ID if we saw value in having the whole statement.

But, I personally thing that just the ID is fine.

**Comment by msbutler** [comment]
bors r=stevendanna

**Comment by msbutler** [comment]
bors r=retry

**Comment by msbutler** [comment]
bors r=stevendanna

**Review by dt — APPROVED** [review]

**Pull request merged**
