### PR TITLE
clusterversion: renumber all 21.2 versions

### LINKED ISSUE #69879: clusterversion: upgrades to 21.2 from 21.1.8 unsound
Due to #69874, a master/21.2-prerelease binary that upgrades from 21.1.8 would skip all migrations prior to -124.

### PR DESCRIPTION
**Pull request by knz**
Fixes  #69879

Release justification: fixes for high-priority and high-severity bug

Release note: None

### CODE REVIEW

**Comment by shermanCRL** [comment]
Addresses https://github.com/cockroachdb/cockroach/issues/69874

**Comment by knz** [comment]
@shermanCRL no this PR is for the `master` branch, we'll need another one for that linked issue.

**Comment by dt** [comment]
Could say this addresses _the 21.2 upgrade path correctness concerns_ due to #69874

**Review by RaduBerinde — APPROVED** [review]

**Comment by HonoreDB** [comment]
By request, test failures are TestInterleavedTableMigration and TestOnUpdateVersionGating in pkg/migration/migrations

and logictestccl hangs, probably a flake in TestTenantLogic

**Comment by knz** [comment]
Ok I changed the necessary tests. Thanks for Aaron for helping and Radu for reviewing.
will merge on green.

**Comment by dt** [comment]
@knz I filed #69879 specifically for the 21.1.8->21.2 upgrade, if you want to mark this as fixing it.

**Comment by knz** [comment]
TFYRs

bors r=RaduBerinde

**Pull request merged**
