### PR TITLE
server: support strict MemFS in StickyVFSRegistry

### PR DESCRIPTION
**Pull request by pav-kv**
The strict `MemFS` can be used for emulating crashes, and testing for data durability loss that they may cause if fsync is not used correctly.

Touches #113135, #114411
Epic: none
Release note: none

### CODE REVIEW

**Comment by pavelkalinnikov** [comment]
Factored this out from #114191 (which uses this new option), to make reviews more targeted/speedy.

**Comment by pavelkalinnikov** [comment]
@jbowens Could you PTAL, as you recently refactored this code?

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115595#-:-NkuX_cI9qUtgExNgm6p:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @pavelkalinnikov)

___
*[`pkg/server/sticky_vfs.go` line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115595#-NkuXAea9SUe1A48FsXk:-NkuXAea9SUe1A48FsXl:buo20ym) ([raw file](https://github.com/cockroachdb/cockroach/blob/78a6074b99d6931d532547c3dacb713b3665ab69/pkg/server/sticky_vfs.go#L65)):*
> ```Go
> 
> // Get implements the StickyVFSRegistry interface.
> func (registry *stickyVFSRegistryImpl) Get(stickyVFSID string) vfs.FS {
> ```

Do we need this to be a concrete `*MemFS` so that the caller can call the strict memFS's non `vfs.FS` methods without a type check?

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115595)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

___
*[`pkg/server/sticky_vfs.go` line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115595#-NkuXAea9SUe1A48FsXk:-NkuiISc5Erfl34aWOb7:b-99zmtu) ([raw file](https://github.com/cockroachdb/cockroach/blob/78a6074b99d6931d532547c3dacb713b3665ab69/pkg/server/sticky_vfs.go#L65)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Do we need this to be a concrete `*MemFS` so that the caller can call the strict memFS's non `vfs.FS` methods without a type check?
</blockquote></details>

Yeah, would be nice. It's legal  given that `stickyVFSRegistryImpl` doesn't hold VFS of any other types. Will add a drive-by commit to this PR for simplicity.

**Comment by pavelkalinnikov** [comment]
bors r=jbowens

**Pull request merged**
