### PR TITLE
workload/schemachange: export OTLP traces to disk

### PR DESCRIPTION
**Pull request by chrisseto**
#### aa052138f4399ecd6b7c95cc744385471a0ea36c workload/schemachange: export OTLP traces to disk

Previous commits instrumented the schemachange workload with OTeL but
did not provide a way to access the output spans.

This commit implements a OTLP client that exports to a gzipped JSON+nl
file. As noted in the client's documentation, tooling for this format is
sparse but JSON wrangling tools can provide extremely rich insights. Due
to versioning issues, loading traces into a tool like Jaeger will
require a small amount of post-processing.

Epic: none
Release note (cli change): workload schemachange now writes a
.otlp.ndjson.gz archive containing OTLP trace bundles for debugging
purposes.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
lgtm! just had minor questions

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114770#-:-NkRVmC942RNTzjlyvb6:b-525bpr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chrisseto, @DarrylWong, and @renatolabs)

___
*[`pkg/workload/schemachange/schemachange.go` line 119 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114770#-NkRVcwfA0TRhed8HtfK:-NkRVcwfA0TRhed8HtfL:bk1ddh2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e10e8d2a3b65da7a8aa54eb73aec3cafbcc705f/pkg/workload/schemachange/schemachange.go#L119)):*
> ```Go
> 			`If provided, transactions will be written to this file in JSON form`)
> 		s.flags.StringVar(&s.traceFilePath, `trace-file`, "",
> 			`The file to write OTeL traces to. Defaults to schemachange-workload.{timestamp}.otlp.jsonnl.gz`)
> ```

nit: should we juse use `*.json.gz` or `*.ndjson.gz`? (same for other usages below)
___
*[`pkg/workload/schemachange/tracing.go` line 119 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114770#-NkRVTt17TlE6uFOLVOF:-NkRVTt17TlE6uFOLVOG:bl6ijgx) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e10e8d2a3b65da7a8aa54eb73aec3cafbcc705f/pkg/workload/schemachange/tracing.go#L119)):*
> ```Go
> 
> 	var err error
> 	c.file, err = os.OpenFile(c.Path, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0660)
> ```

does this mean we'll append to the file if it exists already? is it more usable to recreate the file?

**Review by chrisseto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114770)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @rafiss, and @renatolabs)

___
*[`pkg/workload/schemachange/schemachange.go` line 119 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114770#-NkRVcwfA0TRhed8HtfK:-NkRcnIg1rQV-QxIW7s5:bt2vr0y) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e10e8d2a3b65da7a8aa54eb73aec3cafbcc705f/pkg/workload/schemachange/schemachange.go#L119)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: should we juse use `*.json.gz` or `*.ndjson.gz`? (same for other usages below)
</blockquote></details>

Fixed!
___
*[`pkg/workload/schemachange/tracing.go` line 119 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114770#-NkRVTt17TlE6uFOLVOF:-NkRcp5rEbpj4-2e94lv:bua4dzc) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e10e8d2a3b65da7a8aa54eb73aec3cafbcc705f/pkg/workload/schemachange/tracing.go#L119)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

does this mean we'll append to the file if it exists already? is it more usable to recreate the file?
</blockquote></details>

Yes it does and now that you ask not in the slightest. If the file was just `ndjson`, we could append just fine but the addition of gzip means we'll just corrupt the archive :grimacing: 

Fixed to just use `os.Create`. Good catch!

**Review by rafiss — APPROVED** [review]
lgtm! just asked about a pending todo

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114770#-:-NkS3u0_9mQSM02BQKwA:b-m1e0ij)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chrisseto, @DarrylWong, and @renatolabs)

___
*[`pkg/workload/schemachange/schemachange.go` line 822 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114770#-NkS3ogq1xBsjq-F5xGo:-NkS3ogq1xBsjq-F5xGp:bzca68f) ([raw file](https://github.com/cockroachdb/cockroach/blob/caff43287f574f43e048e69aa4dcb64d7b85ca51/pkg/workload/schemachange/schemachange.go#L822)):*
> ```Go
> 	path := s.traceFilePath
> 	if path == "" {
> 		// TODO(chrisseto): Before merge ensure this default output is to a
> ```

were you able to check this?

**Review by chrisseto — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114770#-:-NkWAZz96DWlFivx55bo:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @rafiss, and @renatolabs)

___
*[`pkg/workload/schemachange/schemachange.go` line 822 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114770#-NkS3ogq1xBsjq-F5xGo:-NkWAbfn5O2piWz4boln:bypzxnh) ([raw file](https://github.com/cockroachdb/cockroach/blob/caff43287f574f43e048e69aa4dcb64d7b85ca51/pkg/workload/schemachange/schemachange.go#L822)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

were you able to check this?
</blockquote></details>

Yep! It works as expected though it's not super ergonomic to access as I noted in slack. I might spend some later trying to make the logged directory a clickable URL in TC.

**Pull request merged**
