### PR TITLE
colexecargs: unify creation of memory monitoring components

### LINKED ISSUE #71358: colexec: cleanup management of memory monitors/accounts
We're creating a lot of memory monitoring components when setting up the vectorized flow that need to be properly closed. We should extract a helper struct that would encapsulate the relevant logic. #46022 can serve as an inspiration.

### PR DESCRIPTION
**Pull request by yuzefovich**
**sql: fix benchmark of TableReaders**

We recently merged a change which made the `txnKVFetcher` take ownership
of the passed-in slice of spans. This broke a couple of benchmarks where
the spec would be invalid after the first iteration. This is now fixed.

Release note: None

**colexecargs: unify creation of memory monitoring components**

This commit introduces a utility struct that keeps track of all memory
monitoring components which allows us to remove some duplicated code and
clean up the tests a bit.

Fixes: #71358.

Release note: None

### CODE REVIEW

**Review by rharding6373 — APPROVED** [review]
Nice! :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72542#-:-Mo0a01J90_mQnw03gki:bfd61qr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @yuzefovich)

___
*[pkg/sql/colexec/colbuilder/execplan.go, line 664 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72542#-Mo0YloD8nOSnrGFW9cN:-Mo0YloD8nOSnrGFW9cO:bwfh6g3) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d846cd18391e60e394adeae9d1fcb2c4d4012d5/pkg/sql/colexec/colbuilder/execplan.go#L664)):*
> ```Go
> 	// Make sure that we clean up memory monitoring infrastructure in case of an
> 	// error or a panic.
> 	defer func() {
> ```

Out of curiosity, why do we not have to defer clean up to MonitoringRegistry?

**Review by yuzefovich — COMMENTED** [review]
I added another commit to fix a recent bug with some micro-benchmarks and adjusted the old commit a bit - I noticed that there was an increase in allocations, so I had to dig in a bit - I fixed a regression but also found a small improvement:
```
name                                          old time/op    new time/op    delta
FlowSetup/vectorize=true/distribute=true-24      238µs ± 3%     239µs ± 4%    ~     (p=0.684 n=10+10)
FlowSetup/vectorize=true/distribute=false-24     236µs ± 3%     233µs ± 3%    ~     (p=0.190 n=10+10)

name                                          old alloc/op   new alloc/op   delta
FlowSetup/vectorize=true/distribute=true-24     34.5kB ± 2%    34.4kB ± 1%    ~     (p=0.796 n=9+9)
FlowSetup/vectorize=true/distribute=false-24    32.6kB ± 0%    32.5kB ± 0%    ~     (p=0.382 n=8+8)

name                                          old allocs/op  new allocs/op  delta
FlowSetup/vectorize=true/distribute=true-24        277 ± 0%       273 ± 0%  -1.44%  (p=0.000 n=8+8)
FlowSetup/vectorize=true/distribute=false-24       263 ± 0%       259 ± 0%  -1.44%  (p=0.000 n=9+9)
```
PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72542#-:-Mo1-LOx1kFQpF_SRba3:b-ofoucm)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @rharding6373)

___
*[pkg/sql/colexec/colbuilder/execplan.go, line 664 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72542#-Mo0YloD8nOSnrGFW9cN:-Mo0rhlcDHxEMy35Q2rQ:bovhi49) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d846cd18391e60e394adeae9d1fcb2c4d4012d5/pkg/sql/colexec/colbuilder/execplan.go#L664)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Out of curiosity, why do we not have to defer clean up to MonitoringRegistry?
</blockquote></details>

The code here was introduced long time ago (in #44564) I think because back then if we already created some memory monitoring components and then encountered a panic, we would lose references to those components. I think this PR addresses this problem by having a centralized place that stores all memory monitoring components (and all of them will be closed on `vectorizedFlow.Cleanup`) making the code here redundant.

**Review by cucaroach — APPROVED** [review]
:lgtm:

> Reviewed 18 of 18 files at r2, 17 of 17 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72542#-:-Mo4sbXe6aRKl_ooxuEG:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @rharding6373 and @yuzefovich)

___
*[pkg/sql/colflow/colbatch_scan_test.go, line 155 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72542#-Mo4qxFM7MgJF-zDNljq:-Mo4qxFM7MgJF-zDNljr:bt8rs0i) ([raw file](https://github.com/cockroachdb/cockroach/blob/994adeaaf00b1fa654730ea3ab73dfe63486c479/pkg/sql/colflow/colbatch_scan_test.go#L155)):*
> ```Go
> 				// txnKVFetcher reuses the passed-in slice and destructively
> 				// modifies it.
> 				spec.Core.TableReader.Spans = []roachpb.Span{span}
> ```

Part of me feels like when the bnechmark changes like this we should change the name of the benchmark but I guess this change doesn't materially affect performance?

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72542#-:-Mo4zFts-44ePbXLPE8V:b-tlx7ko)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @rharding6373)

___
*[pkg/sql/colflow/colbatch_scan_test.go, line 155 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72542#-Mo4qxFM7MgJF-zDNljq:-Mo4z7VfAOl4x_Y8wr4p:bw54uly) ([raw file](https://github.com/cockroachdb/cockroach/blob/994adeaaf00b1fa654730ea3ab73dfe63486c479/pkg/sql/colflow/colbatch_scan_test.go#L155)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

Part of me feels like when the bnechmark changes like this we should change the name of the benchmark but I guess this change doesn't materially affect performance?
</blockquote></details>

Yeah, that's a good point, and I did check that there is no change in the numbers (that's how I actually found this bug - by running the benchmark manually).

**Pull request merged**
