### PR TITLE
util/tracing: get rid of "baggage tags"

### PR DESCRIPTION
**Pull request by andreimatei**
Baggage tags are tags that are inherited by all the spans derived from a
parent (as opposed to a regular tag that just affects the span on which
it is set). We were only using this mechanism for propagating
information about verbose recordings across nodes - a verbose span would
get a baggage tag that would be serialized on the wire like all the
other baggage, and recognized on the other side. This baggage mechanism
is too general for this one specific use case; all the code for
generically passing baggage back and forth is not worth it. Also the
propagation mechanism for the verbosity was confusing; there was a
coupling before the baggage state and other state on the span, for no
good reason.

This patch gets rid of all of it, replacing it with specific code for
propagating the verbose recording flag.

Release note: None

### CODE REVIEW

**Review by abarganier — COMMENTED** [review]
The overall idea :lgtm:  - Baggage was the most difficult concept to wrap my head around when first learning about our tracing library. 

My only real question comes from the UX piece of this. Not propagating baggage tags to all descendant spans means that the viewer of a trace will have to know the correct span to look at in order to get information such as `txnID`. For a non-expert, would they know where to look? I don't see this as a deal breaker necessarily, just trying to understand the impact on that side of the equation.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71869#-:-MmsJ5j-BSWN4q1erodJ:b-5l4fsa)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15 and @andreimatei)

___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 490 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71869#-Mms6Yfi19bYwgGN9UwN:-Mms6YfjEzcxfxMTBPKN:boa7nf8) ([raw file](https://github.com/cockroachdb/cockroach/blob/41e49bbc1964c20315245e34314baa8473fc6b66/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L490)):*
> ```
> sp.SetTag("txnID", attribute.StringValue(tc.mu.txn.ID.String()))
> ```
I guess my only question here would be - do you think it will be easy to find this tag when viewing the entire trace of an operation? Or will a non-expert find themselves wondering where the txnID is?

**Review by andreimatei — COMMENTED** [review]
What you say is right, but I'd turn the question back to you - have you ever had a use for that txnID baggage? Note that the setting that baggage was gated by a `sp.IsVerbose()`, so I'm pretty sure it's never been useful. At least as things stand currently, `sp.IsVerbose()` is only true in very specific circumstances, when the tracing is already done at the level of single transaction, and the trace is consumed fully. In these contexts, you have access to all the spans, so we don't need every single one to copy the txn ID. For example, is otel tracing is enabled, `sp.IsVerbose()` does _not_ return `true` - so you don't get these tags in a trace collector. You could argue that we should... but nobody's ever asked for it, exactly. And also the otel interfaces make using baggage quite awkward for us, because baggage is no longer the property of a span, but it lives in the context in a standalone way.

In my thinking about how we'll consume the trace registry, when you're looking at a span in particular, you again should have access to its parents - so you should be able to find the txn id when you need it.

With this said, I don't think baggage is a bad idea in theory. I might re-introduce it if we need it, but I'll re-introduce it with a particular use case in mind. The original use case for it that we had was the "snowball" thing which represented what has come to be known now as verbose recording. For this use case, we can do much better than the baggage feature - which is what this PR does.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71869#-:-MmsMBlx2W0NBRLRsdSG:bu23jvu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15 and @abarganier)

___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 490 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71869#-Mms6Yfi19bYwgGN9UwN:-MmsazGj8u_LxfGjh1Er:b-49fmcm) ([raw file](https://github.com/cockroachdb/cockroach/blob/41e49bbc1964c20315245e34314baa8473fc6b66/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L490)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

> ```
> sp.SetTag("txnID", attribute.StringValue(tc.mu.txn.ID.String()))
> ```
I guess my only question here would be - do you think it will be easy to find this tag when viewing the entire trace of an operation? Or will a non-expert find themselves wondering where the txnID is? 
</blockquote></details>

discussing on the PR-level thread

**Review by abarganier — APPROVED** [review]
Appreciate the explanation, that all SGTM. 

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71869#-:-MmsgBMw4uRcLbpK1Lsd:bkq3i0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15 and @abarganier)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71869#-:-MmtnRwO8V4x5rdPY89l:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15 and @abarganier)

**Pull request merged**
