### PR TITLE
kv: Explain why we don't clean up a txn on internal errors

### PR DESCRIPTION
**Pull request by kkaneda**
We can do this now as `roachpb.Error` carries a txn for `internalError`s.

Change `cleanupTxn()` to close the channel on `txnMeta.txnEnd` only when it is non-nil. The fix was needed to pass `TestTxnCoordSenderAddIntentOnError`.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4586)

### CODE REVIEW

**Comment by bdarnell** [comment]
LGTM

**Comment by tschottdorf** [comment]
This seems like a net loss since now the client can't actively abort the transaction. Your change amounts to abandoning an active transaction. Consider taking a look at #3108; maybe you can marry this PR and that and actively clean up intents in either case?

As an aside, it's not clear that the transaction is over when a non-conflict error is returned. For example, I could want the following transaction:

```go
// pseudocode
func (txn *client.Txn) *roachpb.Error {
  if pErr := txn.CPut("key1", "val1"); pErr == ConditionFailedError {
     // do something else
  } 
}
```

I don't think we necessarily need that, but this is something to think about and document. In general, I don't think much is lost if we leave those retries to the transaction closure - it doesn't cost much to leave a goroutine running for 100us (due to SQL, the kv client is on the same node as TxnCoordSender), and we would need to undo the change in case we ever wanted to get rid of coordinator pinning.

**Comment by kkaneda** [comment]
Thanks for the reviews. I see. So, it looks like it's better to not clean up txn for internal errors (and this PR can just add a comment). Let me take a look at the other PR. I'll probably just update the PR separately if bg451 is fine.

**Comment by bdarnell** [comment]
It's actually pretty common in SQL to handle a unique index violation and continue the transaction (i.e. try an INSERT, and if that fails UPDATE the existing row). This shows up as a ConditionFailedError at our KV layer. (we don't have any tests for this yet because we don't return structured error information in SQL yet, but it's something we do want to support).

**Comment by tschottdorf** [comment]
We already convert that error in SQL. It shows up as a `errUniquenessConstraintViolation` (though it's maybe not correctly error-coded yet).

**Comment by bdarnell** [comment]
Yeah, but at the pgwire level everything turns into "XX000 internal error"

**Comment by kkaneda** [comment]
I see. Changed the PR to just add a comment (and add a panic when a retryable error is returned). Does this look good now? I can also just close the PR.

**Comment by bdarnell** [comment]
LGTM, but it would be good to mention ConditionFailedError as an example of an error that the caller may continue after.

**Comment by kkaneda** [comment]
Agreed. Added the following sentence:

```
For example, a client might continue its transaction after receiving ConditionFailedError, which can come from a unique index violation.
```

**Comment by tamird** [comment]
LGTM

**Pull request merged**
