### PR TITLE
clusterversion: mint 22.1 cluster version

### PR DESCRIPTION
**Pull request by celiala**
This commit will mint a 22.1 cluster version. This will be backported onto both release-22.1/release-22.1.0.

Partial work for https://github.com/cockroachdb/cockroach/issues/80555

### Minting: what is it and when to do it?
Minting a cluster version indicates the end of one release and the beginning of the next. Minting closes the door on any future version gates or migrations being backported to 21.1; i.e. once we mint the version, we cannot add new migrations/version gates under it without requiring a wipe of any clusters that ran a build including the mint. Because of this, we should only merge this onto the 22.1 release branch once we’re sure we won’t need any more cluster versions. In terms of timing, the release team plans for this to be the last commit backported onto 22.1 immediately before choosing the SHA for an rc.1.

Release justification: Non-production code change.
Release note: None

### CODE REVIEW

**Review by irfansharif — APPROVED** [review]
- `dev gen go` I think will generate the file you're after.
- `dev testlogic ccl --files='crdb_internal_tenant' --show-logs --rewrite` will update another test file
- We're going to have to update `TestTenantUpgradeFailure` to work with minted binary versions.

**Comment by celiala** [comment]
@lunevalex - I'm getting a test fail for TestLeasePreferencesDuringOutage, for an unseemingly-related change? any guesses as to why?

github.com/cockroachdb/cockroach/pkg/kv/kvserver/client_lease_test.go:855
```
Failed
=== RUN   TestLeasePreferencesDuringOutage
    test_log_scope.go:79: test logs captured to: /artifacts/tmp/_tmp/6e7bf2e335c4bcac83d466da95afd655/logTestLeasePreferencesDuringOutage3227955927
    test_log_scope.go:80: use -show-logs to present logs inline
    client_lease_test.go:855:
          Error Trace:  client_lease_test.go:855
          Error:        Not equal:
                        expected: "us"
                        actual  : "eu"
                        Diff:
                        --- Expected
                        +++ Actual
                        @@ -1 +1 @@
                        -us
                        +eu
          Test:         TestLeasePreferencesDuringOutage
    panic.go:642: -- test log scope end --
--- FAIL: TestLeasePreferencesDuringOutage (8.14s)
```

**Comment by AlexTalks** [comment]
@irfansharif,
> * We're going to have to update `TestTenantUpgradeFailure` to work with minted binary versions.
Took care of this in #80606.

**Review by jlinder — APPROVED** [review]

**Comment by celiala** [comment]
TFTR!

bors r=irfansharif,jlinder

**Pull request merged**
