### PR TITLE
importccl: parallelize CSV-skipping workload IMPORT

### PR DESCRIPTION
**Pull request by dt**
(only last commit, first two commits are #36042)

This spins up multiple workers, each importing every i'th batch, to do
workload IMPORT.

As noted inline, this execution order, as opposed to assinging large
spans of batches to each worker, should mean that adjacent batches are
processed at roughly the same time and thus end up in the same
sort-batch for SST creation, preserving the non-overlapping SSTs when
the workload's batches are ordered and non-overlapping.

Release note: none.

### CODE REVIEW

**Review by danhhz — COMMENTED** [review]
heh, I have a local PR that does this, which I think has some advantages over what you have here, but your insight about doing them in order is a good one and my impl doesn't do that. Just pushed it to https://github.com/cockroachdb/cockroach/commit/5f728d95da11ac760eb4b4a8a02b9d53015cdc18 for reference. Take a look at some of the cleanups I did

Include the two benchmarks I have in my commit message in your commit message, please.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36060#-:-LapEg9YA19OPkXUa6hC:b-p732uu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz and @dt)

___
*[pkg/ccl/importccl/read_import_workload.go, line 33 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36060#-LapF2dz-OhmgfpJ-AOv:-LapF2dz-OhmgfpJ-AOw:b50b4si) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcdf8d1994ae6e4b0d0ab3bc5b726c49a995fe6e/pkg/ccl/importccl/read_import_workload.go#L33)):*
> ```Go
> 
> type workloadReader struct {
> 	evalCtx *tree.EvalContext
> ```

One of the other impls says we need an evalCtx per worker because it's not threadsafe
___
*[pkg/ccl/importccl/read_import_workload.go, line 146 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36060#-LapFC6E5Ujixg67lxeb:-LapFC6E5Ujixg67lxec:b-h1xtev) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcdf8d1994ae6e4b0d0ab3bc5b726c49a995fe6e/pkg/ccl/importccl/read_import_workload.go#L146)):*
> ```Go
> 		// together and then ingested together in the same SST, minimzing the amount
> 		// of overlapping SSTs.
> 		// TODO(dt): on very long imports, these could drift. We might want to check
> ```

Much simpler than this and guaranteed to work is to have each worker use an atomic int to grab batches to process. I think this is worth doing in the initial PR instead of what you have here.

batchIdxAtomic := int64(conf.BatchBegin-1)
for i := 0; i < workers; i++ {
  g.GoCtx(func(ctx context.Context) error {
    for {
      batch := int(atomic.AddInt64(&batchIdxAtomic, 1)
      if batch >= conf.BatchEnd {
        break
      }
      ...
    }
  }
}
___
*[pkg/ccl/importccl/read_import_workload.go, line 150 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36060#-LapFbHAAoClcHMKr3cb:-LapFbHAAoClcHMKr3cc:b-gj7wq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcdf8d1994ae6e4b0d0ab3bc5b726c49a995fe6e/pkg/ccl/importccl/read_import_workload.go#L150)):*
> ```Go
> 		// that we're significantly above it.
> 		for i := 0; i < workers; i++ {
> 			thread := i
> ```

s/thread/goroutine/ everywhere in this PR
___
*[pkg/ccl/importccl/read_import_workload.go, line 152 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36060#-LapGhg9BbKmVjXtpsQN:-LapGhg9BbKmVjXtpsQO:bi9smsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcdf8d1994ae6e4b0d0ab3bc5b726c49a995fe6e/pkg/ccl/importccl/read_import_workload.go#L152)):*
> ```Go
> 			thread := i
> 			g.GoCtx(func(ctx context.Context) error {
> 				conv, err := newRowConverter(w.table, w.evalCtx, w.kvCh)
> ```

move everything in this body into a method on (*workloadReader)
___
*[pkg/ccl/importccl/read_import_workload.go, line 161 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36060#-LapGq7I065RsVQg8fAj:-LapGq7I065RsVQg8fAk:b46huod) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcdf8d1994ae6e4b0d0ab3bc5b726c49a995fe6e/pkg/ccl/importccl/read_import_workload.go#L161)):*
> ```Go
> 				var rowIdx int64
> 				for b := begin + thread; b < end; b += workers {
> 					// log.Infof(ctx, "%s thread %d of %d importing batch %d", t.Name, thread, workers, b)
> ```

intentional?

**Review by dt — COMMENTED** [review]
Added benchmarks -- they don't look _quite_ the same as yours but are similar in shape and our starting times were pretty different so I'm guessing it is mostly hardware.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36060#-:-LapfmyJDrkb8CUGwRPQ:bcp0hob)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz)

___
*[pkg/ccl/importccl/read_import_workload.go, line 33 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36060#-LapF2dz-OhmgfpJ-AOv:-LapfYv5E31HSAG6e4Do:b-52cbds) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcdf8d1994ae6e4b0d0ab3bc5b726c49a995fe6e/pkg/ccl/importccl/read_import_workload.go#L33)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

One of the other impls says we need an evalCtx per worker because it's not threadsafe
</blockquote></details>

Huh, testrace didn't seem to mind, but we only use a couple fields of the ctx (for now) so maybe it just didn't hit the mutation part. easy enough to make a copy for each and not worry about tit.
___
*[pkg/ccl/importccl/read_import_workload.go, line 146 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36060#-LapFC6E5Ujixg67lxeb:-LapIJZ_5Qe4zjT_sPuD:byh93ph) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcdf8d1994ae6e4b0d0ab3bc5b726c49a995fe6e/pkg/ccl/importccl/read_import_workload.go#L146)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Much simpler than this and guaranteed to work is to have each worker use an atomic int to grab batches to process. I think this is worth doing in the initial PR instead of what you have here.

batchIdxAtomic := int64(conf.BatchBegin-1)
for i := 0; i < workers; i++ {
  g.GoCtx(func(ctx context.Context) error {
    for {
      batch := int(atomic.AddInt64(&batchIdxAtomic, 1)
      if batch >= conf.BatchEnd {
        break
      }
      ...
    }
  }
}
</blockquote></details>

Many of the workloads appear to do one row / batch so I  was trying to avoid having to do any cross-thread coordination for each row, but I guess in the bigger scheme of things, a barrier is probably trivial. It might also be the case that we should be making the Batch func return more than 1 row per call and that would probably have other benefits too (e.g. could bulk-alloc more).

Done.
___
*[pkg/ccl/importccl/read_import_workload.go, line 150 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36060#-LapFbHAAoClcHMKr3cb:-Lap_RW8EevAafzYDiuP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcdf8d1994ae6e4b0d0ab3bc5b726c49a995fe6e/pkg/ccl/importccl/read_import_workload.go#L150)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

s/thread/goroutine/ everywhere in this PR
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/read_import_workload.go, line 152 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36060#-LapGhg9BbKmVjXtpsQN:-Lap_SCt9mcaxef53OD8:big4b23) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcdf8d1994ae6e4b0d0ab3bc5b726c49a995fe6e/pkg/ccl/importccl/read_import_workload.go#L152)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

move everything in this body into a method on (*workloadReader)
</blockquote></details>

Done

well, actually introduced a new struct to hold extra per-file args it needs to close over and then a method on that.
___
*[pkg/ccl/importccl/read_import_workload.go, line 161 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36060#-LapGq7I065RsVQg8fAj:-Lap_f6e2mKjkyWmGcVD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcdf8d1994ae6e4b0d0ab3bc5b726c49a995fe6e/pkg/ccl/importccl/read_import_workload.go#L161)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

intentional?
</blockquote></details>

Done.

**Review by danhhz — COMMENTED** [review]
:lgtm: Sorry if I'm being dense, but I don't see the benchmarks.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36060#-:-LapmhhnCfhEUfN9fRcZ:b-u7kr5m)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz and @dt)

___
*[pkg/ccl/importccl/read_import_workload.go, line 146 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36060#-LapFC6E5Ujixg67lxeb:-LapkhtGD329RwWVhTYZ:b-k6tnxm) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcdf8d1994ae6e4b0d0ab3bc5b726c49a995fe6e/pkg/ccl/importccl/read_import_workload.go#L146)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Many of the workloads appear to do one row / batch so I  was trying to avoid having to do any cross-thread coordination for each row, but I guess in the bigger scheme of things, a barrier is probably trivial. It might also be the case that we should be making the Batch func return more than 1 row per call and that would probably have other benefits too (e.g. could bulk-alloc more).

Done.
</blockquote></details>

Yeah, I had the same thought, but it's easy to later make this grab more than 1 at a time if we have contention issues. (I suspect we won't for a while because the work of converting a row into kvs is much bigger than one atomic add.) Making batch funcs return more than one row is coming.
___
*[pkg/ccl/importccl/read_import_workload.go, line 142 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36060#-Laplprd4rbNUS2MPvmX:-Laplprd4rbNUS2MPvmY:b-5f67kt) ([raw file](https://github.com/cockroachdb/cockroach/blob/489557fdcc8263336208e33f6a20bf74c08bdcb7/pkg/ccl/importccl/read_import_workload.go#L142)):*
> ```Go
> 
> 		workers := workloadReaderWorker{
> 			w:                w,
> ```

let's denormalize whatever this needs from w into fields on this struct
___
*[pkg/ccl/importccl/read_import_workload.go, line 168 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36060#-LapliVg5yRm7dTR_rjw:-LapliVg5yRm7dTR_rjx:b-kqfk7r) ([raw file](https://github.com/cockroachdb/cockroach/blob/489557fdcc8263336208e33f6a20bf74c08bdcb7/pkg/ccl/importccl/read_import_workload.go#L168)):*
> ```Go
> // in the SST builder, minimzing the amount of overlapping SSTs ingested.
> func (w *workloadReaderWorker) run(ctx context.Context) error {
> 	evalCtx := w.w.newEvalCtx()
> ```

move this to where we instantiate the workloadReaderWorker

**Comment by dt** [comment]
ugh, I realized I had accidentally detached HEAD when I was benchmarking and that's why the amend got lost, but apparently when I then pushed, it instead _deleted_ the branch ... and GitHub says it can't be reopened.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36060)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz and @dt)

___
*[pkg/ccl/importccl/read_import_workload.go, line 142 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36060#-Laplprd4rbNUS2MPvmX:-LapuAKo-axI4gNtwzGq:b-1dardd) ([raw file](https://github.com/cockroachdb/cockroach/blob/489557fdcc8263336208e33f6a20bf74c08bdcb7/pkg/ccl/importccl/read_import_workload.go#L142)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

let's denormalize whatever this needs from w into fields on this struct
</blockquote></details>

happy to do so, but it uses all three fields of w

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36060)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz and @dt)

___
*[pkg/ccl/importccl/read_import_workload.go, line 168 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36060#-LapliVg5yRm7dTR_rjw:-LapwGr20lGgvVllAwyB:b-m7re0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/489557fdcc8263336208e33f6a20bf74c08bdcb7/pkg/ccl/importccl/read_import_workload.go#L168)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

move this to where we instantiate the workloadReaderWorker
</blockquote></details>

so the func _is_ the worker -- there is only one struct instantiated. On second though, I'm going back to no helper struct -- it seems like it complicates it more than just having an  anon func inline above to close over all the per-file locals in the readFile loop.

**Pull request closed without merging**
