### PR TITLE
opt, stats: improve statistics with histograms

### PR DESCRIPTION
**Pull request by rytaft**
**stats: make first histogram bucket have empty range**

This commit updates the code for calculating histograms to ensure
that the first bucket has an empty range. This enables the user
of the histogram to know the lower bound of the histogram: it is
equal to the upper bound of the first bucket.

This commit also contains a small bug fix to SHOW STATISTICS USING JSON...,
which was not formatting datums correctly in the histogram output.

**opt: use histogram to update distinct counts**

This commit updates the statistics code to calculate the
distinct count of a column based on its histogram (if available).
This improves on the distinct count estimate based solely on
the constraint.

This commit also updates the statistics code to only copy the
histogram up the query tree when it will be used directly by a
Scan or Select operator.

**opt: refactor TPC-H tests and add histograms**

This commit refactors the opt TPC-H tests by moving all the schema and
stats exec-ddl statements to two shared files. In order to facilitate this
change, I added a new OptTester directive called "import", which allows
test files to import other files (and thus avoid duplication).

This commit also updates the TPC-H stats quality tests to include
histograms. No plans changed as a result of adding histograms, but some of
the stats are more accurate.

### CODE REVIEW

**Comment by rytaft** [comment]
Gentle ping - I have some other work that builds on this so would be nice to get this out the door.

**Review by RaduBerinde — COMMENTED** [review]
Sorry for the delay. I had started to review but got interrupted and then forgot to get back to it.

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38905#-:-Lk6bV7ED9nZB4jwCziY:b-gehesd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 2651 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38905#-Lk6bNzu1jefPiIUp_0Y:-Lk6bNzu1jefPiIUp_0Z:b-bsujqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5e08a027dc5fbb3f2fcfe7d6a36e6402b443b6/pkg/sql/opt/memo/statistics_builder.go#L2651)):*
> ```Go
> 	col, _ := colStat.Cols.Next(0)
> 
> 	// For discrete types (integers and dates), the distinct count estimate from
> ```

Is this true? (given that we treat all values inside a bucket as distinct, when that could be far from the truth)
___
*[pkg/sql/opt/props/histogram.go, line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38905#-Lk6aQoCDFEgh5lPRQZ0:-Lk6aQoD193z4cI4CHn8:b-354ojr) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5e08a027dc5fbb3f2fcfe7d6a36e6402b443b6/pkg/sql/opt/props/histogram.go#L128)):*
> ```Go
> 		b := &h.buckets[i]
> 		var rng float64
> 		ok := true
> ```

[nit] less error-prone if we set `ok=true` in the two cases where we have a range (then `ok = true` is always associated with a `rng = `)
___
*[pkg/sql/opt/props/histogram.go, line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38905#-Lk6auqA4wCLLWVVMo08:-Lk6auqA4wCLLWVVMo09:b-kwm8yg) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5e08a027dc5fbb3f2fcfe7d6a36e6402b443b6/pkg/sql/opt/props/histogram.go#L152)):*
> ```Go
> 			count += rng
> 		} else {
> 			count += b.NumRange
> ```

It seems that there is potential to overestimate by a lot here (to the point where per-column distinct counts might be more useful). I wonder if we can add more information in each bucket to help with this. Unfortunately the histogram works on a sample, so using a sketch inside each bucket won't work very well. (unless we somehow knew the boundaries beforehand)

**Review by justinj — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38905#-:-Lk6gygS2OVORSpAGOOC:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @justinj and @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 2657 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38905#-Lk6fghGA1pxAvQEPrmF:-Lk6fghH7AAxxl-UrjNQ:brxhb4e) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc18334193c09230cbcb7284cb7675e72b850ba3/pkg/sql/opt/memo/statistics_builder.go#L2657)):*
> ```Go
> 	// the histogram estimate serves as an upper bound on the distinct count.
> 	switch sb.md.ColumnMeta(col).Type.Family() {
> 	case types.IntFamily, types.DateFamily:
> ```

should this classification be extracted into a helper somewhere? would be nice to have a guarantee somehow that this will get updated if a new data type is ever added but I can't think of a way to do that that isn't explicitly whitelisting every existing type...
___
*[pkg/sql/opt/testutils/opttester/opt_tester.go, line 256 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38905#-Lk6gVPv4OryYv59_aZa:-Lk6gVPw3RCLYzWf7UU9:b-fxmi5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc18334193c09230cbcb7284cb7675e72b850ba3/pkg/sql/opt/testutils/opttester/opt_tester.go#L256)):*
> ```Go
> //    with the table flag.
> //
> //  - import [flags]
> ```

nice!!

nit: consider specifying what the path is relative to

**Review by rytaft — COMMENTED** [review]
TFTRs!

I made some pretty significant changes to the distinct count estimation code. It's more computationally intensive (it has more math 🤓), but I think it should be much more accurate for cases where the distinct count is relatively small compared to the number of rows. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38905#-:-LkPIPwACq8TmWV6Y8o3:b-rou6pl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @justinj and @RaduBerinde)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 2651 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38905#-Lk6bNzu1jefPiIUp_0Y:-LkPJ6VG-KOn6if77mYL:b-j3jqjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5e08a027dc5fbb3f2fcfe7d6a36e6402b443b6/pkg/sql/opt/memo/statistics_builder.go#L2651)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Is this true? (given that we treat all values inside a bucket as distinct, when that could be far from the truth)
</blockquote></details>

Fixed the distinct count method to be more accurate.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 2657 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38905#-Lk6fghGA1pxAvQEPrmF:-LkPJAXI-Xr1HSMMjFTV:b-7c8zf4) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc18334193c09230cbcb7284cb7675e72b850ba3/pkg/sql/opt/memo/statistics_builder.go#L2657)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

should this classification be extracted into a helper somewhere? would be nice to have a guarantee somehow that this will get updated if a new data type is ever added but I can't think of a way to do that that isn't explicitly whitelisting every existing type...
</blockquote></details>

Removed this condition.
___
*[pkg/sql/opt/props/histogram.go, line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38905#-Lk6aQoCDFEgh5lPRQZ0:-LkPJLPu9SGE2GRVlVX0:b-lsj4iz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5e08a027dc5fbb3f2fcfe7d6a36e6402b443b6/pkg/sql/opt/props/histogram.go#L128)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] less error-prone if we set `ok=true` in the two cases where we have a range (then `ok = true` is always associated with a `rng = `)
</blockquote></details>

This has been changed now.
___
*[pkg/sql/opt/props/histogram.go, line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38905#-Lk6auqA4wCLLWVVMo08:-LkPJRzI-39hWe6b7D53:b8qakuk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5e08a027dc5fbb3f2fcfe7d6a36e6402b443b6/pkg/sql/opt/props/histogram.go#L152)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It seems that there is potential to overestimate by a lot here (to the point where per-column distinct counts might be more useful). I wonder if we can add more information in each bucket to help with this. Unfortunately the histogram works on a sample, so using a sketch inside each bucket won't work very well. (unless we somehow knew the boundaries beforehand)
</blockquote></details>

I changed the algorithm here - let me know what you think.
___
*[pkg/sql/opt/testutils/opttester/opt_tester.go, line 256 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38905#-Lk6gVPv4OryYv59_aZa:-LkP_43LB4TrhMaWmgAI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc18334193c09230cbcb7284cb7675e72b850ba3/pkg/sql/opt/testutils/opttester/opt_tester.go#L256)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

nice!!

nit: consider specifying what the path is relative to
</blockquote></details>

Done.

**Comment by rytaft** [comment]
One thought is that if the new `Histogram.Init` code for estimating distinct counts turns out to be too computationally intensive, it could be moved to the histogram construction code (`stats.EquiDepthHistogram`).

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

Very cool! The way we distribute the distinct counts is pretty sophisticated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38905#-:-LkUFiTk6LVSnxitpQgp:bsgf6dx)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 2669 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38905#-LkUBBmd-quj-GHu0o3w:-LkUBBmd-quj-GHu0o3x:b9mht95) ([raw file](https://github.com/cockroachdb/cockroach/blob/66f7bad59f80780097732d408165eeb1a334e511/pkg/sql/opt/memo/statistics_builder.go#L2669)):*
> ```Go
> // histogram. This should be called after updateDistinctCountsFromConstraint
> // and/or updateDistinctCountFromUnappliedConjuncts.
> func (sb *statisticsBuilder) updateDistinctCountFromHistogram(
> ```

[nit] add a short comment about what `maxDistinctCount` is
___
*[pkg/sql/opt/memo/testdata/stats_quality/tpch, line 325 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/38905#-LkUFNoU7PnZuWKyr6FP:-LkUFNoVDBlAuXYw4njK:b3hi9tn) ([raw file](https://github.com/cockroachdb/cockroach/blob/06c4848965b8e7878fb28a9d693a7f48c714e189/pkg/sql/opt/memo/testdata/stats_quality/tpch#L325)):*
> ```
>       │         │    │    │    │    ├── columns: ps_partkey:29(int!null) ps_suppkey:30(int!null) ps_supplycost:32(float!null)
>       │         │    │    │    │    ├── stats: [rows=800000, distinct(29)=199241, null(29)=0, distinct(30)=9920, null(30)=0, distinct(32)=100379, null(32)=0]
>       │         │    │    │    │    │   histogram(29)=  0 80  3920  80   3920   80   3920   80   3920   80   3920   80   3920   80   3920   80   3920   80   3920   80   3920   80   3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3840   160   3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   160   3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920   80    3920    80    3920    80    3920    80    3920    80    3920   160    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    3920   160    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    3840   160    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    3920    80    4000    80    4000    80    4000    80    4000    80    4000    80    4000    80    4000   160    3920    80    4000    80    4000    80    4000    80    4000    80    4000    80    4000    80    4000    80    4000    80    4000    80    4000    80    4000    80    4000    80    3920   160    4000    80    4000    80    4000    80    4000    80    4000    80    4000    80    4000    80    4000    80    4000    80    4000    80    4000    80    4000   160    3920    80    4000    80    4000    80    4000    80    4000    80    4000    80    4000    80    4000    80    4000    80    4000    80    4000    80    4000    80    4000    80
> ```

An idea to make these more visible would be to do encode them in a URL. It shouldn't be too hard to make a page that actually displays a histogram. A bit of a time sink though, just a thought for the future.
___
*[pkg/sql/opt/props/histogram.go, line 90 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38905#-LkUCwhy36kb5wTI8zo4:-LkUCwhy36kb5wTI8zo5:b-o3lki4) ([raw file](https://github.com/cockroachdb/cockroach/blob/66f7bad59f80780097732d408165eeb1a334e511/pkg/sql/opt/props/histogram.go#L90)):*
> ```Go
> // initDistinctCountDiscreteType estimates the number of distinct values in
> // each bucket. It is used for discrete types such as integer and date.
> func (h *Histogram) initDistinctCountDiscreteType(distinctCount float64) {
> ```

[nit] would be good to include a brief description of how it does it - something like "it distributes the known number of distinct values (distinctCount) among the buckets, in proportion with the amount of rows in each bucket"
___
*[pkg/sql/opt/props/histogram.go, line 133 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38905#-LkUG5im0rdwgNxmbKYk:-LkUG5im0rdwgNxmbKYl:bgdbbn5) ([raw file](https://github.com/cockroachdb/cockroach/blob/66f7bad59f80780097732d408165eeb1a334e511/pkg/sql/opt/props/histogram.go#L133)):*
> ```Go
> // each bucket. It is used for continuous types (i.e. all types other than
> // integer and date).
> func (h *Histogram) initDistinctCountContinuousType(distinctCount float64) {
> ```

If we called `initDistinctCountDiscreteType` on a continuous type, wouldn't it do the exact same thing?

I realize this version might be faster because we're not trying `maxDistinctValuesInRange` each time, but we could have that optimization in a single function (e.g. store `isDiscreteType(h.buckets[0].UpperBound)` in a var).
___
*[pkg/sql/opt/props/histogram.go, line 159 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38905#-LkUDSr62RqpskIwU86_:-LkUDSr62RqpskIwU86a:boi2cw3) ([raw file](https://github.com/cockroachdb/cockroach/blob/66f7bad59f80780097732d408165eeb1a334e511/pkg/sql/opt/props/histogram.go#L159)):*
> ```Go
> }
> 
> // expectedDistinctCount returns the expected number of distinct values in a
> ```

[nit] maybe it's just me, but I find it easier to think of this function in more generic terms (expected number of distinct values among k random numbers between 1 and n)

**Review by rytaft — COMMENTED** [review]
TFTR! Updated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38905#-:-LkV51OV6PLzSTGVCowN:b-p0fj95)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @justinj and @RaduBerinde)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 2669 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38905#-LkUBBmd-quj-GHu0o3w:-LkUv6wSEW01qok2tcXm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/66f7bad59f80780097732d408165eeb1a334e511/pkg/sql/opt/memo/statistics_builder.go#L2669)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] add a short comment about what `maxDistinctCount` is
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/testdata/stats_quality/tpch, line 325 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/38905#-LkUFNoU7PnZuWKyr6FP:-LkUv8WT9YIgYPkzBtTR:bowc9xd) ([raw file](https://github.com/cockroachdb/cockroach/blob/06c4848965b8e7878fb28a9d693a7f48c714e189/pkg/sql/opt/memo/testdata/stats_quality/tpch#L325)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

An idea to make these more visible would be to do encode them in a URL. It shouldn't be too hard to make a page that actually displays a histogram. A bit of a time sink though, just a thought for the future.
</blockquote></details>

Like a graphical display? That could be good, although equi-depth histograms don't usually look as pretty as equi-width histograms. Anyway, agree that it's something we should think about doing at some point.
___
*[pkg/sql/opt/props/histogram.go, line 90 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38905#-LkUCwhy36kb5wTI8zo4:-LkV54gL8xE7SXD7Pwnr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/66f7bad59f80780097732d408165eeb1a334e511/pkg/sql/opt/props/histogram.go#L90)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] would be good to include a brief description of how it does it - something like "it distributes the known number of distinct values (distinctCount) among the buckets, in proportion with the amount of rows in each bucket"
</blockquote></details>

Done.
___
*[pkg/sql/opt/props/histogram.go, line 133 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38905#-LkUG5im0rdwgNxmbKYk:-LkUyIdx4WhVlBo-lXQz:b3jql4b) ([raw file](https://github.com/cockroachdb/cockroach/blob/66f7bad59f80780097732d408165eeb1a334e511/pkg/sql/opt/props/histogram.go#L133)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

If we called `initDistinctCountDiscreteType` on a continuous type, wouldn't it do the exact same thing?

I realize this version might be faster because we're not trying `maxDistinctValuesInRange` each time, but we could have that optimization in a single function (e.g. store `isDiscreteType(h.buckets[0].UpperBound)` in a var).
</blockquote></details>

Good point - done.
___
*[pkg/sql/opt/props/histogram.go, line 159 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38905#-LkUDSr62RqpskIwU86_:-LkV4tfl4lM7LKxLVgpy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/66f7bad59f80780097732d408165eeb1a334e511/pkg/sql/opt/props/histogram.go#L159)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] maybe it's just me, but I find it easier to think of this function in more generic terms (expected number of distinct values among k random numbers between 1 and n)
</blockquote></details>

Done.

**Review by rytaft — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38905#-:-LkVAjdiCWJc_BUAKNUY:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @justinj and @RaduBerinde)

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38905#-:-LkVMHd-9mYYI81sltGH:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/memo/testdata/stats_quality/tpch, line 325 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/38905#-LkUFNoU7PnZuWKyr6FP:-LkVLsjK9m4lueIx2Soo:bfhas61) ([raw file](https://github.com/cockroachdb/cockroach/blob/06c4848965b8e7878fb28a9d693a7f48c714e189/pkg/sql/opt/memo/testdata/stats_quality/tpch#L325)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Like a graphical display? That could be good, although equi-depth histograms don't usually look as pretty as equi-width histograms. Anyway, agree that it's something we should think about doing at some point.
</blockquote></details>

Yeah, it would help even if it's just text, maybe with some coloring or whatnot.

**Pull request merged**
