### PR TITLE
ui: Dropdown redesign

### LINKED ISSUE #45516: ui: Update style for all dropdown buttons (ie. filters)
Update all dropdown buttons (ie. filters, datepicker) to [Secondary button style in the design system ](https://www.figma.com/file/B5AtEGdRbW3VxiBdg62TB8Xw/CRDB-Design-System_V2?node-id=22%3A4)

- [x] [Metrics](https://www.figma.com/file/WK4FG2dFxTpqt96K1FZhSw/obsrv_admin-ui-metrics?node-id=1229%3A6334):  `graph` `dashboard` selectors, `datepicker` selector, `timespan arrows` and `now` button

Screen Shot 2020-02-27 at 4 33 28 PM

- [x] [Jobs](https://www.figma.com/file/c6BNEn0mY6iHG1t5NhoH3E/obsrv_admin-ui-jobs?node-id=1204%3A206): `status` `type` filters 

Screen Shot 2020-02-27 at 4 07 07 PM

- [x] [Statements](https://www.figma.com/file/C85d0mrz8dkNs7Nw5mcTmf/obsrv_admin-ui-statements?node-id=1139%3A1715): `app` filter

Screen Shot 2020-02-27 at 4 03 32 PM

- [x] [Network Latency](https://www.figma.com/file/7ibbkObA1alv7Q3htOcG4l/obsrv_admin-ui-network-latency?node-id=1098%3A5577): `Sort by` and `filter`

 Screen Shot 2020-02-27 at 4 29 34 PM

### PR DESCRIPTION
**Pull request by vladlos**
Restyled select component

Resolves: #45516

Release justification: bug fixes and low-risk updates to new functionality

Release note (ui): none

### CODE REVIEW

**Comment by nathanstilwell** [comment]
Besides the test failure, I'm seeing an inordinate amount of space between the dropdown button and the dropdown menu,

Screen Shot 2020-03-06 at 13 03 20
 (Screenshot taken from the Statements page using Chrome latest)

**Review by dhartunian — CHANGES_REQUESTED** [review]
The Network Latency "Filter" dropdown has not been restyled. Am I missing something?

Please add a release justification as well to the commit + PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45802#-:-M3SC4TC-a-2jk8fDYdz:b-gcgywd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @elkmaster and @nathanstilwell)

___
*[pkg/ui/src/components/icon/caretDown.tsx, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45802#-M3So9yzAo4UOVPYHQVL:-M3So9yzAo4UOVPYHQVM:b-uilvef) ([raw file](https://github.com/cockroachdb/cockroach/blob/7152ef94395042a71701f63f54b9058a6aedaa75/pkg/ui/src/components/icon/caretDown.tsx#L1)):*
> ```XML
> // Copyright 2019 The Cockroach Authors.
> ```

`2020`
___
*[pkg/ui/src/views/cluster/components/range/index.tsx, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45802#-M3SnYc23PewBlDLQXi5:-M3SnYc23PewBlDLQXi6:b-z01497) ([raw file](https://github.com/cockroachdb/cockroach/blob/7152ef94395042a71701f63f54b9058a6aedaa75/pkg/ui/src/views/cluster/components/range/index.tsx#L16)):*
> ```XML
> import React from "react";
> import "./range.styl";
> import { arrowRenderer } from "oss/src/views/shared/components/dropdown";
> ```

remove `oss` from import
___
*[pkg/ui/src/views/cluster/components/range/index.tsx, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45802#-M3Sp14p2yk21JsUbPHb:-M3Sp14p2yk21JsUbPHc:buz8o1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/7152ef94395042a71701f63f54b9058a6aedaa75/pkg/ui/src/views/cluster/components/range/index.tsx#L132)):*
> ```XML
> 
>   toggleDropDown = () => this.setState({ opened: !this.state.opened }, () => {
>     this.toggleCustomPicker(this.state.opened)();
> ```

Can you explain the reason for `()` here? This looks like it returns void.
___
*[pkg/ui/src/views/cluster/components/range/index.tsx, line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45802#-M3Sndy5D_PrAnNd6n44:-M3Sndy5D_PrAnNd6n45:b-akgo67) ([raw file](https://github.com/cockroachdb/cockroach/blob/7152ef94395042a71701f63f54b9058a6aedaa75/pkg/ui/src/views/cluster/components/range/index.tsx#L134)):*
> ```XML
>     this.toggleCustomPicker(this.state.opened)();
>     if (this.state.opened) {
>       this.props.onFocus();
> ```

Why call these `onFocus` and `onBlur` when they trigger based on the `opened` state? I would call them `onOpened` and `onClosed`. Are they connected to browser focus/blur events?

Even better idea might be to have them match the `onFocus` and `onClose` on the `Select`? Are they supposed to mean the same thing?

**Review by dhartunian — COMMENTED** [review]
:lgtm: Thanks for the changes @elkmaster 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45802#-:-M3fkUME71HCm2ML6kqs:b-yandjl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @elkmaster and @nathanstilwell)

**Review by nathanstilwell — APPROVED** [review]
LGTM!

**Review by dhartunian — APPROVED** [review]
:lgtm: (sorry missed marking as approved last time around)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45802#-:-M3gXBRa3qwNbw904jR8:bay7if8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @elkmaster and @nathanstilwell)

**Review by nathanstilwell — APPROVED** [review]
> Reviewed 7 of 7 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45802)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @elkmaster)

**Pull request merged**
