### PR TITLE
fix: pkg/ui/package.json & pkg/ui/yarn.lock to reduce vulnerabilities

### PR DESCRIPTION
**Pull request by dhartunian**
Release justification: low-risk security vuln updates

The following vulnerabilities are fixed with an upgrade:
- https://snyk.io/vuln/SNYK-JS-LODASH-1018905
- https://snyk.io/vuln/SNYK-JS-LODASH-1040724

Depends on cockroachdb/yarn-vendored#58

Release note: None

### CODE REVIEW

**Comment by dhartunian** [comment]
Replaces: https://github.com/cockroachdb/cockroach/pull/60969

**Review by nathanstilwell — APPROVED** [review]
LGTM

**Comment by knz** [comment]
this was an infra flake. retrying

bors r=nathanstilwell

**Pull request merged**
