### PR TITLE
sqlccl: add a test for concurrent backup/restores

### PR DESCRIPTION
**Pull request by danhhz**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13850)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/sqlccl/backup_test.go, line 502 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13850#-Ke5LzySGMOJc8gNotwf:-Ke5LzySGMOJc8gNotwg:bk7r71e) ([raw file](https://github.com/cockroachdb/cockroach/blob/eced84b995ed6c64b4ba5e10bc61369e112adb62/pkg/ccl/sqlccl/backup_test.go#L502)):*
> ```Go
> 	for i := 0; i < concurrency; i++ {
> 		wg.Add(1)
> 		backupDirs = append(backupDirs, filepath.Join(dir, strconv.Itoa(i)))
> ```

why bother with this slice? you're always passing the head of it into the function below.

---

*[pkg/ccl/sqlccl/backup_test.go, line 504 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13850#-Ke5M5d9wK-Cr8vr2mVp:-Ke5M5d9wK-Cr8vr2mVq:b-wcbmst) ([raw file](https://github.com/cockroachdb/cockroach/blob/eced84b995ed6c64b4ba5e10bc61369e112adb62/pkg/ccl/sqlccl/backup_test.go#L504)):*
> ```Go
> 		backupDirs = append(backupDirs, filepath.Join(dir, strconv.Itoa(i)))
> 		go func(d string) {
> 			_, err := sqlDB.DB.Exec(fmt.Sprintf(`BACKUP DATABASE bench TO '%s'`, d))
> ```

nit: in light of scoping issues, i'd use `if _, err := ...; err != nil {` here, and then `err :=` below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13850)*

**Comment by danhhz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/ccl/sqlccl/backup_test.go, line 502 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13850#-Ke5LzySGMOJc8gNotwf:-Ke5OedzvqvPBH0OEvqC:b7enfyi) ([raw file](https://github.com/cockroachdb/cockroach/blob/eced84b995ed6c64b4ba5e10bc61369e112adb62/pkg/ccl/sqlccl/backup_test.go#L502)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why bother with this slice? you're always passing the head of it into the function below.
</blockquote></details>

Artifact from the first way I implemented this. Done.

---

*[pkg/ccl/sqlccl/backup_test.go, line 504 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13850#-Ke5M5d9wK-Cr8vr2mVp:-Ke5PLwcF9uqXHakI4HY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eced84b995ed6c64b4ba5e10bc61369e112adb62/pkg/ccl/sqlccl/backup_test.go#L504)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: in light of scoping issues, i'd use `if _, err := ...; err != nil {` here, and then `err :=` below
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13850)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13850)*

**Comment by mjibson** [comment]
How will this mix with the policy to only allow restoring to non-existent tables? Seems like once we get that in this test will break and not be too useful. Or am I wrong about that policy?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13850#-:-Ke5d2O9diGLIRBPN082:b-e8pcwp)*

**Comment by danhhz** [comment]
Lol, you're right. Looks like I should archive this for when we support restoring over existing tables. That's really the interesting part that it's checking.

**Pull request closed without merging**
