### PR TITLE
sqlproxyccl: remove unused denylist implementations

### PR DESCRIPTION
**Pull request by jeffswenson**
The viper and mock denylist formats are no longer used as of #66137. I'm refactoring 
the denylist for issue #65694. Removing the unused format simplifies the refactoring.

Release note: None

### CODE REVIEW

**Review by meridional — APPROVED** [review]
Some context: I left those in to test out backward and forward-compatibilities.

**Comment by JeffSwenson** [comment]
The build was failing on the lint step. I ran `make bazel-generate` and updated the commit.

**Comment by JeffSwenson** [comment]
Removed the go generate command from service.go. It caused a CI lint failure.
```
//go:generate mockgen -package=denylist -destination=mocks_generated.go -source=service.go . Service
```

**Review by darinpp — APPROVED** [review]
Looks good.

**Pull request merged**
