### PR TITLE
sql: some fixes around routines and types

### LINKED ISSUE #113186: sql: mismatched column-definition list causes an internal error
When a record-returning UDF is used as a data source, it must be given a column-definition list, which names the columns returned by the UDF and determines their types. When the type of the column-definition list doesn't match the actual type returned by the function, postgres attempts an assignment cast:
```
postgres=# create function f() returns record language sql as $$ select 1.99; $$;
CREATE FUNCTION
postgres=# select * from f() AS foo(x int);
 x
---
 2
(1 row)

postgres=# select * from f() AS foo(x timestamp);
ERROR:  return type mismatch in function declared to return record
```
Currently, CRDB doesn't handle this case at all; instead, it returns an internal error during execution due to an unexpected type:
```
root@localhost:26257/system/defaultdb> select * from f() AS foo(x int);
ERROR: internal error: invalid datum type given: DECIMAL, expected INT8
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/rowenc/encoded_datum.go:195: DatumToEncDatum()
github.com/cockroachdb/cockroach/pkg/sql/rowexec/project_set.go:334: toEncDatum()
github.com/cockroachdb/cockroach/pkg/sql/rowexec/project_set.go:241: nextGeneratorValues()
github.com/cockroachdb/cockroach/pkg/sql/rowexec/project_set.go:313: Next()
github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:239: Next()
github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:118: next()
```

Jira issue: CRDB-32791

### LINKED ISSUE #114846: sql: internal error invalid datum type in udf argument
Repro:
```
create function array_to_set(anyarray) returns setof record as $$       
   select i AS "index", $1[i] AS "value" from generate_subscripts($1, 1) i
$$ language sql strict immutable;
select * from array_to_set(array['one', 'two']) as t(f1 numeric(4,2),f2 text);
```

Stack trace:
```
ERROR: internal error: invalid datum type given: INT8, expected DECIMAL(4,2)
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/rowenc/encoded_datum.go:195: DatumToEncDatum()
github.com/cockroachdb/cockroach/pkg/sql/rowexec/project_set.go:334: toEncDatum()
github.com/cockroachdb/cockroach/pkg/sql/rowexec/project_set.go:241: nextGeneratorValues()
github.com/cockroachdb/cockroach/pkg/sql/rowexec/project_set.go:313: Next()
github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:239: Next()
github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:118: next()
github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92: CatchVectorizedRuntimeError()
github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:126: Next()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:250: nextAdapter()
github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92: CatchVectorizedRuntimeError()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:254: next()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:286: Run()
github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:320: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:910: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1957: PlanAndRun()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1672: func3()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1675: PlanAndRunAll()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2302: execWithDistSQLEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1861: dispatchToExecutionEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1092: execStmtInOpenState()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:145: func1()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:3277: execWithProfiling()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:144: execStmt()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2227: func1()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2232: execCmd()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2149: run()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:952: ServeConn()
github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:247: processCommands()
github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:1001: func3()
src/runtime/asm_amd64.s:1650: goexit()

HINT: You have encountered an unexpected error.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.

If you would rather not post publicly, please contact us directly
using the support form.

We appreciate your feedback.
```

This does not error in postgres.

Found in pg_regress rangefuncs

Jira issue: CRDB-33712

### PR DESCRIPTION
**Pull request by yuzefovich**
See each commit for details.

Fixes: #113186
Fixes: #114846

Release note (bug fix): CockroachDB could previously encounter an internal error of the form `invalid datum type given: ..., expected ...` when executing some UDFs and this is now fixed. The bug has been present since 23.1.0 release.

### CODE REVIEW

**Comment by DrewKimball** [comment]
>I don't think it's expected that types.Any would be provided in the first place though.

Yeah, this definitely shouldn't be allowed. I think it'd be better to assert that this doesn't happen, rather than execute without a valid type supplied by the optimizer.

**Comment by yuzefovich** [comment]
Ok, I'll look into the optimizer land for the fix.

**Comment by DrewKimball** [comment]
Hm, looks like the problem may be that we use the generic parameter type in determining. Probably we should be using the type of the argument that's provided when the function is actually called, somehow. We should have access to those arguments in `buildRoutine` through `FuncExpr.Exprs`. We build the arguments [here](https://github.com/cockroachdb/cockroach/blob/f68f0febe05a1d645699bd56b447ad155961ff83/pkg/sql/opt/optbuilder/routine.go#L194-L196), so I think it's a matter of using those supplied types rather than the static parameter types [here](https://github.com/cockroachdb/cockroach/blob/f68f0febe05a1d645699bd56b447ad155961ff83/pkg/sql/opt/optbuilder/routine.go#L217-L233).

**Comment by yuzefovich** [comment]
Hm, I'm not sure what's the expected behavior in the optbuilder should be. Simply doing
```
--- a/pkg/sql/opt/optbuilder/routine.go
+++ b/pkg/sql/opt/optbuilder/routine.go
@@ -226,7 +226,7 @@ func (b *Builder) buildRoutine(
                for i := range paramTypes {
                        paramType := &paramTypes[i]
                        argColName := funcParamColName(tree.Name(paramType.Name), i)
-                       col := b.synthesizeColumn(bodyScope, argColName, paramType.Typ, nil /* expr */, nil /* scalar */)
+                       col := b.synthesizeColumn(bodyScope, argColName, args[i].DataType(), nil /* expr */, nil /* scalar */)
                        col.setParamOrd(i)
                        params[i] = col.id
                }
```
is insufficient. What happens is that when we're building the only stmt in this `array_to_set` routine, we don't specify `desiredTypes` on `buildStmtAtRootWithScope` call, so eventually when we're type checking the `IndirectionExpr` (which is the "value" part), we use `types.Any` in `analyzeSelectList`.

Did you have something else (different from the diff I posted) in mind that should fix it?

**Comment by DrewKimball** [comment]
Are you sure that diff is insufficient? It seems to work for my local test. It should be changing the type of the column in the `*scope` object that gets passed into `buildStmtAtRootWithScope`, which should ensure we use the concrete array type instead of the wildcard array type when resolving the input to the `IndirectionExpr`.

**Comment by DrewKimball** [comment]
The flow goes like this:
1. Param (should be argument) type determines scope column types
2. Scope column types determine resolved expression types when the statement is built
3. The statement result columns determine the type of the RECORD-returning UDF

The problem is that we used parameter types instead of argument types in step (1), which meant we set `ANYARRAY` as the column type instead of a concrete array type.

**Comment by yuzefovich** [comment]
> Are you sure that diff is insufficient? It seems to work for my local test.

My steps:
- check out current master 63dc83b0215c8e4cdfb9255566af6dc91451b485
- apply only single line diff mentioned above
- use the following logic test file
```
# LogicTest: local

statement ok
CREATE FUNCTION array_to_set(anyarray) RETURNS SETOF RECORD AS $$
   SELECT i AS "index", $1[i] AS "value" FROM generate_subscripts($1, 1) i
$$ LANGUAGE SQL STRICT IMMUTABLE;

query RT colnames,rowsort
SELECT * FROM array_to_set(array['one', 'two']) AS t(f1 numeric(4,2), f2 text);
----
f1    f2
1.00  one
2.00  two
```

I'm hitting
```
        expected success, but found
        (XX000) internal error: cannot use value of type string on a datumVec of type anyelement
        datum_vec.go:210: in assertSameTypeFamily()
        DETAIL: stack trace:
        github.com/cockroachdb/cockroach/pkg/col/coldataext/datum_vec.go:210: assertSameTypeFamily()
        github.com/cockroachdb/cockroach/pkg/col/coldataext/datum_vec.go:201: assertValidDatum()
        github.com/cockroachdb/cockroach/pkg/col/coldataext/datum_vec.go:95: Set()
        github.com/cockroachdb/cockroach/bazel-out/darwin_arm64-fastbuild/bin/pkg/sql/colexec/rowtovec.eg.go:190: EncDatumRowToColVecs()
        github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:252: Next()
        github.com/cockroachdb/cockroach/pkg/sql/colexec/invariants_checker.go:93: Next()
        github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:247: next()
        github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:272: nextAdapter()
        github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92: CatchVectorizedRuntimeError()
        github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:278: Next()
        github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:128: next()
...
```

**Comment by DrewKimball** [comment]
Interesting, I think there may be multiple issues here. For example, I think that diff would fix this test case:
```
SELECT * FROM array_to_set(array['one', 'two']::TEXT[]) AS t(f1 numeric(4,2), f2 text);
```

**Comment by DrewKimball** [comment]
[Array constructors](https://www.postgresql.org/docs/15/sql-expressions.html#SQL-SYNTAX-ARRAY-CONSTRUCTORS) are supposed to use union/case expression rules, which prefer resolving the type as TEXT if none is specified ([docs](https://www.postgresql.org/docs/15/typeconv-union-case.html)). I think our second issue is that we're missing some of that type-checking logic.

**Comment by DrewKimball** [comment]
Ok, I think I tracked it down - `IsWildCardType` isn't recognizing the "desired" type as being `Any`; this diff fixes that:
```
diff --git a/pkg/sql/types/types.go b/pkg/sql/types/types.go
index f8963197a64..7fe6ebe2c7a 100644
--- a/pkg/sql/types/types.go
+++ b/pkg/sql/types/types.go
@@ -2139,6 +2139,10 @@ func (t *T) Equal(other *T) bool {
 // IsWildcardType returns true if the type is only used as a wildcard during
 // static analysis, and cannot be used during execution.
 func (t *T) IsWildcardType() bool {
+       switch t.Family() {
+       case AnyFamily:
+               return true
+       }
        switch t {
        case Any, AnyArray, AnyCollatedString, AnyEnum, AnyEnumArray, AnyTuple, AnyTupleArray:
                return true
```
With that plus your diff, your test case passes.

**Review by yuzefovich — COMMENTED** [review]
Thanks for all the pointers!

I think the current implementation of `IsWildcardType` is incorrect (relying on pointer comparison against global singletons doesn't always work), so I added another commit (now first) that fixes that. I extracted the argument type fix into a separate commit two. The main remaining question in my mind is whether the hidden cast done by `projectSet` is the right approach, or should the optimizer do something different?

PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118799#-:-Nq11FpU9mdaReu8g9CO:b-6jkuky)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

**Comment by DrewKimball** [comment]
>The main remaining question in my mind is whether the hidden cast done by projectSet is the right approach, or should the optimizer do something different?

Yeah, this should be an optimizer fix too. I'm guessing the remaining internal error you're seeing is due to the column definition list `AS t(f1 numeric(4,2), f2 text)` - is that right? [Here](https://github.com/cockroachdb/cockroach/blob/d7d442e4a3c9dca7e01c4c6f4f00e2f28faa4374/pkg/sql/opt/optbuilder/srfs.go#L198) is where the column definition list is used to determine the output columns (the col def list is `lastAlias := inScope.alias`). I think the issue is that we don't check that the definition list matches the actual return types. If they don't match, we should be using an assignment cast, like we do here: https://github.com/cockroachdb/cockroach/blob/d7d442e4a3c9dca7e01c4c6f4f00e2f28faa4374/pkg/sql/opt/optbuilder/routine.go#L403-L408

**Review by DrewKimball — COMMENTED** [review]
The first two commits LGTM.

> Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118799#-:-Nq1beHpAA9i9Fvk0fyS:b-mfx8le)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118799#-Nq1_pNi9E3LMqWnXvbt):*
Great catch! You've inspired me to look for other cases where we do this; I'll put up a fix soon.

**Review by yuzefovich — COMMENTED** [review]
I adjusted the second commit to only use the actual argument type when the static type is a wildcard (there was a CI failure that showed that static type can be more descriptive (like having tuple labels that actual argument type is missing)).

Thanks for the pointer on the casts - I agree that this seems like the right fix. I did try to make the change in `finishBuildGeneratorFunction` but struggled with different expr types (i.e. `opt.ScalarExpr` vs `memo.RelExpr` produced by the project op) and what to do about scopes - do you mind taking over this PR and finalizing it?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118799#-:-Nq9mR7z2ZPBz7CYLCRd:b-sjla0f)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118799#-Nq1_pNi9E3LMqWnXvbt):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Great catch! You've inspired me to look for other cases where we do this; I'll put up a fix soon.
</blockquote></details>

Thanks!

**Comment by DrewKimball** [comment]
>do you mind taking over this PR and finalizing it?

Sure. Thanks for stepping outside your comfort zone with this one!

**Comment by yuzefovich** [comment]
Closing as Drew took over this work.

**Pull request closed without merging**
