### PR TITLE
sql: add batch DELETE syntax

### LINKED ISSUE #104157: sql: add batch DELETE syntax
Add the following `DELETE` syntax in preparation of bulk delete:

- `DELETE BATCH FROM` - To use the the default batch size
- `DELETE BATCH (SIZE expr) FROM` - To use the specified batch size

These will return unimplemented errors for now.

The syntax fulfills the following requirements:
1) `DELETE` keyword comes first because some tools look at the first keyword to determine what type of statement it is.
2) New `BATCH` params can be added in the future in a backward compatible way.
3) `BATCH` params (only `SIZE` for now) are order-independent for usability.
4) `SIZE` value is an expression to allow composing a `DELETE` statement from subqueries.

Jira issue: CRDB-28377

Epic CRDB-456

### PR DESCRIPTION
**Pull request by ecwall**
Fixes #104157

This change adds the following DELETE syntax in preparation of bulk delete:
`DELETE BATCH FROM` - To use the the default batch size
`DELETE BATCH (SIZE expr) FROM` - To use the specified batch size
These will return unimplemented errors for now.

The syntax fulfills the following requirements:
1) DELETE keyword comes first because some tools look at the first keyword to
   determine what type of statement it is.
2) New BATCH params can be added in the future in a backward compatible way.
3) BATCH params (only SIZE for now) are order-independent for usability.
4) SIZE value is an expression to allow composing a DELETE statement from
   subqueries.

Release note: None

### CODE REVIEW

**Review by mgartner — COMMENTED** [review]
Are there any documents I can read that describe the motivation and semantics for batch deletes?

Does support for DELETEs and PL/pgSQL in UDFs that we're targeting for v23.2, make a new BATCH DELETE syntax less pressing? A user can simply write a loop in a UDF to do the same thing. Though I suppose having some syntactic sugar specifically for batch deletes is more user-friendly, if its a very common action.

> Reviewed 1 of 1 files at r1, 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104160#-:-NWmvD1u0u2c-igT0QFT:bnspr32)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @rafiss)

___
*[`pkg/sql/sem/tree/batch.go` line 17 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104160#-NWmu_0W1_225PDVAqPs:-NWmu_0W1_225PDVAqPt:blivgqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/a845213457295422e2cdc9fb1a28b2608b19135f/pkg/sql/sem/tree/batch.go#L17)):*
> ```Go
> // Batch represents a BATCH statement.
> type Batch struct {
> 	Size int64
> ```

Does it make more sense for this to be an unsigned int, because it shouldn't be negative?
___
*[`pkg/sql/logictest/testdata/logic_test/delete` line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104160#-NWmsAR19ewZpddCHMnp:-NWmsAR27WaXaoNOyFpU:b-u3ac2q) ([raw file](https://github.com/cockroachdb/cockroach/blob/29e36f70e076c3e66ef13fbe2909cacae58eb26f/pkg/sql/logictest/testdata/logic_test/delete#L59)):*
> ```
> # delete a non-existent value on the index.
> statement count 0
> DELETE FROM kv WHERE v=5
> ```

Why did you duplicate this statement?
___
*[`pkg/sql/logictest/testdata/logic_test/delete` line 596 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104160#-NWmutcn5LYAKgIdudNh:-NWmutcn5LYAKgIdudNi:b9rwnq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a845213457295422e2cdc9fb1a28b2608b19135f/pkg/sql/logictest/testdata/logic_test/delete#L596)):*
> ```
> 
> statement ok
> CREATE TABLE delete_batch_tbl (id INT PRIMARY KEY);
> ```

Consider putting batch delete tests in a new file like `delete_batch`.

**Review by ecwall — COMMENTED** [review]
Sent the doc offline.

The `BATCH DELETE` will start a job that uses DistSQL similarly to TTL so it should be more efficient for deleting large amounts of data.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104160#-:-NWwe6zL4Rd6BkJ6-Ua8:bwpf4q2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rafiss)

___
*[`pkg/sql/sem/tree/batch.go` line 17 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104160#-NWmu_0W1_225PDVAqPs:-NWweX2t-ovZaHw6BYl-:bfid77q) ([raw file](https://github.com/cockroachdb/cockroach/blob/a845213457295422e2cdc9fb1a28b2608b19135f/pkg/sql/sem/tree/batch.go#L17)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Does it make more sense for this to be an unsigned int, because it shouldn't be negative?
</blockquote></details>

`tree.NumVal` currently only can output an int64 so I thought I would use int64 here for consistency since the values won't be larger than `math.MaxInt64` (we might want to set a limit lower than this though in the code).

I'll add validation preventing input of negative values or 0.
___
*[`pkg/sql/logictest/testdata/logic_test/delete` line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104160#-NWmsAR19ewZpddCHMnp:-NWsBjNV7IQNF6DH-DUF:b-v1kqab) ([raw file](https://github.com/cockroachdb/cockroach/blob/29e36f70e076c3e66ef13fbe2909cacae58eb26f/pkg/sql/logictest/testdata/logic_test/delete#L59)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Why did you duplicate this statement?
</blockquote></details>

I undid changes to this file and added my test cases in `delete_batch`.
___
*[`pkg/sql/logictest/testdata/logic_test/delete` line 596 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104160#-NWmutcn5LYAKgIdudNh:-NWsBsMw0H1B8Jmgogaz:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/a845213457295422e2cdc9fb1a28b2608b19135f/pkg/sql/logictest/testdata/logic_test/delete#L596)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Consider putting batch delete tests in a new file like `delete_batch`.
</blockquote></details>

Done

**Comment by knz** [comment]
I perceive that the SQL syntax was not sufficiently researched. It does not have extension points. Any extension direction will make the grammar ambiguous.

What design process was used to choose the candidate SQL syntax? Which design principles were used?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104160)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall, @knz, and @mgartner)

___
*[`pkg/sql/sem/tree/batch.go` line 29 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/104160#-NY-A_GXDGLAK76wR58p:-NY-A_GYBoRQwLw-4zjG:bxxcswz) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ebacd7d21d11a969a4553ab9d1ac70382940013/pkg/sql/sem/tree/batch.go#L29)):*
> ```Go
> 
> // Normalize converts a Batch to a NormalizedBatch.
> func (b *Batch) Normalize() (normalized NormalizedBatch, _ error) {
> ```

do we use this Normalize pattern in other places?

the convention i'm familiar with is to just use the struct from the sql.y file too. see the RestoreOptions struct for an example:

https://github.com/cockroachdb/cockroach/blob/290f665b4f007279aa72cb1e0295907323986076/pkg/sql/parser/sql.y#L3710-L3715

https://github.com/cockroachdb/cockroach/blob/290f665b4f007279aa72cb1e0295907323986076/pkg/sql/sem/tree/backup.go#LL314-L366

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104160)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall, @knz, and @mgartner)

___
*[`pkg/sql/sem/tree/batch.go` line 29 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/104160#-NY-A_GXDGLAK76wR58p:-NY-B1Qq6GWh8eYPZiRr:bozzfm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ebacd7d21d11a969a4553ab9d1ac70382940013/pkg/sql/sem/tree/batch.go#L29)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

do we use this Normalize pattern in other places?

the convention i'm familiar with is to just use the struct from the sql.y file too. see the RestoreOptions struct for an example:

https://github.com/cockroachdb/cockroach/blob/290f665b4f007279aa72cb1e0295907323986076/pkg/sql/parser/sql.y#L3710-L3715

https://github.com/cockroachdb/cockroach/blob/290f665b4f007279aa72cb1e0295907323986076/pkg/sql/sem/tree/backup.go#LL314-L366


</blockquote></details>

the advantage is that you need less boilerplate code.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104160)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall, @knz, and @mgartner)

___
*[`pkg/sql/parser/testdata/delete` line 186 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/104160#-NY-BAi88IUpyE8BiT66:-NY-BAi88IUpyE8BiT67:b-j6e744) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ebacd7d21d11a969a4553ab9d1ac70382940013/pkg/sql/parser/testdata/delete#L186)):*
> ```
> 
> parse
> DELETE BATCH (SIZE 1) FROM a
> ```

if you do use my suggestion above, then we can add an error test also:
```
error
DELETE BATCH (SIZE 1, SIZE 2) FROM a
```

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104160)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @mgartner)

___
*[`pkg/sql/sem/tree/batch.go` line 29 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/104160#-NY-A_GXDGLAK76wR58p:-NY-H-yY7Sm3bUu4n6mO:beh5fx0) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ebacd7d21d11a969a4553ab9d1ac70382940013/pkg/sql/sem/tree/batch.go#L29)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

the advantage is that you need less boilerplate code.
</blockquote></details>

@knz could I get your input on this? I was under the impression that this should not be done during the parsing, though I do agree it creates less boilerplate code because `.Normalize()` does not need to be called everywhere.

**Review by knz — COMMENTED** [review]
> Reviewed 1 of 10 files at r2, 1 of 17 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104160)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall, @mgartner, and @rafiss)

___
*[`pkg/sql/parser/sql.y` line 5331 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/104160#-NYO0Wl95aDWvGwE3hQS:-NYO0Wl95aDWvGwE3hQT:b8hjt2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ebacd7d21d11a969a4553ab9d1ac70382940013/pkg/sql/parser/sql.y#L5331)):*
> ```Yacc
> 
> batch_param:
> 	SIZE a_expr
> ```

nit: spaces not tabs
___
*[`pkg/sql/sem/tree/batch.go` line 29 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/104160#-NY-A_GXDGLAK76wR58p:-NYO0fDx3xMzRMHacQd6:bdh5fb5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ebacd7d21d11a969a4553ab9d1ac70382940013/pkg/sql/sem/tree/batch.go#L29)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

@knz could I get your input on this? I was under the impression that this should not be done during the parsing, though I do agree it creates less boilerplate code because `.Normalize()` does not need to be called everywhere.
</blockquote></details>

My preferences goes in this order:
1. do as little work during parsing as possible, and do option normalization _only once_ during query planning.  In this vision, it's OK to see duplicate options in the AST. The planning code would _check_ that there are no duplicates (or, alternatively, choose to only consider the last value specified). 
2. follow existing patterns, if there are any.

You'll notice that neither opinions have space for a "normalize" function  that generates a new AST node. I do not believe we need this.

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104160)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rafiss)

___
*[`pkg/sql/parser/sql.y` line 5331 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/104160#-NYO0Wl95aDWvGwE3hQS:-NYO4mwM341GEPnMMjGT:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ebacd7d21d11a969a4553ab9d1ac70382940013/pkg/sql/parser/sql.y#L5331)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: spaces not tabs
</blockquote></details>

Done

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104160)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall, @knz, and @mgartner)

___
*[`pkg/sql/sem/tree/batch.go` line 29 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/104160#-NY-A_GXDGLAK76wR58p:-NYYTV894BJ9R2gREl7D:bndymmg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ebacd7d21d11a969a4553ab9d1ac70382940013/pkg/sql/sem/tree/batch.go#L29)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

My preferences goes in this order:
1. do as little work during parsing as possible, and do option normalization _only once_ during query planning.  In this vision, it's OK to see duplicate options in the AST. The planning code would _check_ that there are no duplicates (or, alternatively, choose to only consider the last value specified). 
2. follow existing patterns, if there are any.

You'll notice that neither opinions have space for a "normalize" function  that generates a new AST node. I do not believe we need this.
</blockquote></details>

the latest way is fine with me, though i do think the `CombineWith` pattern used for the restore options seems the most intuitive to me. no need to change this though.

**Comment by ecwall** [comment]
bors r=rafiss

**Pull request merged**
