### PR TITLE
ui: require Yarn 1.0+

### PR DESCRIPTION
**Pull request by benesch**
99b35b3 accidentally introduced a dependency on Yarn 1.0+ with its usage
of `yarn --cwd`. Since Yarn 1.0 has been available since early
September, it seems reasonable to mandate its usage.

### CODE REVIEW

**Review by couchand — APPROVED** [review]
Seems like a reasonable period has passed, and this qualifies for Ben's criteria of needing an actual reason.

Since we're requiring this, can you remove the `--` on the script invocations that's throwing warnings?

**Review by a-robinson — APPROVED** [review]
Thanks, I just ran into this.

**Comment by benesch** [comment]
@couchand 99b35b3 removed usage of `yarn run` entirely. You're not still seeing that `--` deprecation warning, are you?

**Comment by couchand** [comment]
So you're right.  Nevermind, ignore me.

**Pull request merged**
