### PR TITLE
sql: add benchmark for counting how many roundtrips a ddl statement performs

### PR DESCRIPTION
**Pull request by RichardJCai**
sql: add benchmark for counting how many roundtrips a ddl statement performs

Release note: None

Example output:
```
goos: darwin
goarch: amd64
pkg: github.com/cockroachdb/cockroach/pkg/bench
BenchmarkGrantTables/grant_on_1_table-8         	1000000000	         0.164 ns/op	        10.0 roundtrips
BenchmarkGrantTables/grant_on_10_tables-8       	1000000000	         0.445 ns/op	       160 roundtrips
--- BENCH: BenchmarkGrantTables
    test_log_scope.go:77: test logs captured to: /var/folders/s9/5m7lxn217451rj169w3sh8bh0000gp/T/logBenchmarkGrantTables101520749
    test_log_scope.go:58: use -show-logs to present logs inline
BenchmarkDropTables/drop_1_table-8              	       1	1043545344 ns/op	         7.00 roundtrips
BenchmarkDropTables/drop_2_tables-8             	       1	1032635967 ns/op	        16.0 roundtrips
BenchmarkDropTables/drop_3_tables-8             	       1	1032938773 ns/op	        27.0 roundtrips
--- BENCH: BenchmarkDropTables
    test_log_scope.go:77: test logs captured to: /var/folders/s9/5m7lxn217451rj169w3sh8bh0000gp/T/logBenchmarkDropTables622127676
    test_log_scope.go:58: use -show-logs to present logs inline
PASS
```

### CODE REVIEW

**Comment by rohany** [comment]
I personally like this, and think it will be more useful/maintainable than the logictest version

**Comment by RichardJCai** [comment]
This is ready for review

**Comment by solongordon** [comment]
I think this is headed in a good direction. My main concern is that the actual latency timings are not so meaningful, and that is what our benchmark analysis tools will be looking at. Maybe this is too hacky but could we manipulate those timings to be a constant multiple of the number of roundtrips? For example you could arbitrarily say a round trip is 100ms and force the timings to reflect that. Thoughts?

**Comment by RichardJCai** [comment]
> I think this is headed in a good direction. My main concern is that the actual latency timings are not so meaningful, and that is what our benchmark analysis tools will be looking at. Maybe this is too hacky but could we manipulate those timings to be a constant multiple of the number of roundtrips? For example you could arbitrarily say a round trip is 100ms and force the timings to reflect that. Thoughts?

I feel like manipulating the timings to be a constant multiple of the number of roundtrips would be too hacky, different statements have different overheads so I think this would be pretty inaccurate. I wonder how much work it would take to make our benchmark tools look at the latency timings. 

Another thought is we don't necessarily need the latency timings to be a constant multiple of roundtrips do we? If the timings loosely correlate to the number of roundtrips, wouldn't that help catch regressions as well, having the actual roundtrip count may still be useful in this case.

**Comment by rohany** [comment]
Solon isn't suggesting to not have the roundtrip counts, but to also make the time reflective of that, since scripts we use to track benchmark regressions just look at the time.

**Comment by RichardJCai** [comment]
The benchmarks weren't counting latencies correctly earlier. I wonder if we actually have to manipulate latencies to correspond to # of roundtrips or if raw latencies are okay.
```
goos: darwin
goarch: amd64
pkg: github.com/cockroachdb/cockroach/pkg/bench
BenchmarkGrantTables/grant_on_1_table-8         	       9	 121436032 ns/op	        10.0 roundtrips
BenchmarkGrantTables/grant_on_10_tables-8       	       4	 327183332 ns/op	        46.0 roundtrips
--- BENCH: BenchmarkGrantTables
    test_log_scope.go:77: test logs captured to: /var/folders/s9/5m7lxn217451rj169w3sh8bh0000gp/T/logBenchmarkGrantTables465948119
    test_log_scope.go:58: use -show-logs to present logs inline
BenchmarkDropTables/drop_1_table-8              	      10	 104503215 ns/op	         7.00 roundtrips
BenchmarkDropTables/drop_2_tables-8             	       8	 125835994 ns/op	        14.0 roundtrips
BenchmarkDropTables/drop_3_tables-8             	       8	 137107283 ns/op	        21.0 roundtrips
BenchmarkDropTables/drop_10_tables-8            	       4	 355347926 ns/op	        63.0 roundtrips
--- BENCH: BenchmarkDropTables
```

**Comment by RichardJCai** [comment]
Good news, @nvanbenschoten's benchdiff tool works natively for this.

Heres an example output when running the script.

```
name                                                                                old roundtrips  new roundtrips  delta
GrantTables/grant_on_1_table-8                                                           10.0 ± 0%       10.0 ± 0%   ~     (all equal)
GrantTables/grant_on_10_tables-8                                                         46.0 ± 0%       46.0 ± 0%   ~     (all equal)
DropTables/drop_1_table-8                                                                7.00 ± 0%       7.00 ± 0%   ~     (all equal)
DropTables/drop_2_tables-8                                                               14.0 ± 0%       14.0 ± 0%   ~     (all equal)
DropTables/drop_3_tables-8                                                               21.0 ± 0%       21.0 ± 0%   ~     (all equal)
DropTables/drop_10_tables-8                                                              63.0 ± 0%       63.0 ± 0%   ~     (all equal)
```

Any more feedback for this PR? @solongordon @rohany

**Comment by rohany** [comment]
Nice to see that it works! I think you should remove the `TestDDLAnalysis` test in this PR as well.

**Comment by RichardJCai** [comment]
> Nice to see that it works! I think you should remove the `TestDDLAnalysis` test in this PR as well.

Yeah I'll combine that in here, I think I'll still have adding the remaining cases in a separate PR so we can discuss about potential test cases in a separate PR.

**Comment by rohany** [comment]
Now that they aren't a "test", there is no reason to not have any of the cases that we argued about before -- now there isn't any downside to adding a test here!

**Comment by RichardJCai** [comment]
@solongordon I added some test cases for drop database and configure zone, you also mentioned partition by but it requires enterprise, not sure how to enable it for unit tests.

**Comment by solongordon** [comment]
Ah, I believe enterprise features are enabled in tests via `utilccl.TestingEnableEnterprise()`. The complication is that enterprise feature tests must live under `pkg/ccl`. I'd say let's look at adding PARTITION BY tests in a follow-up PR.

**Comment by RichardJCai** [comment]
Here's the output for the benchmark

```
BenchmarkAlterTableAddColumn/alter_table_add_1_column-8         	       8	 126972356 ns/op	         3.00 roundtrips
BenchmarkAlterTableAddColumn/alter_table_add_2_columns-8        	       8	 141453347 ns/op	         3.00 roundtrips
BenchmarkAlterTableAddColumn/alter_table_add_3_columns-8        	       9	 152906897 ns/op	         3.00 roundtrips
BenchmarkAlterTableAddCheckConstraint/alter_table_add_1_check_constraint-8         	       6	 169827794 ns/op	         3.00 roundtrips
BenchmarkAlterTableAddCheckConstraint/alter_table_add_2_check_constraints-8        	       6	 186823110 ns/op	         3.00 roundtrips
BenchmarkAlterTableAddCheckConstraint/alter_table_add_3_check_constraints-8        	       6	 185760406 ns/op	         3.00 roundtrips
BenchmarkAlterTableAddForeignKey/alter_table_add_1_foreign_key-8                   	       3	 387820287 ns/op	         9.00 roundtrips
BenchmarkAlterTableAddForeignKey/alter_table_add_2_foreign_keys-8                  	       3	 374100509 ns/op	        15.0 roundtrips
BenchmarkAlterTableAddForeignKey/alter_table_add_3_foreign_keys-8                  	       3	 423920572 ns/op	        21.0 roundtrips
BenchmarkAlterTableAddForeignKey/alter_table_add_foreign_key_with_3_columns-8      	       5	 251796091 ns/op	         9.00 roundtrips
BenchmarkAlterTableDropColumn/alter_table_drop_1_column-8                          	       6	 220894552 ns/op	         6.00 roundtrips
BenchmarkAlterTableDropColumn/alter_table_drop_2_columns-8                         	       6	 170794224 ns/op	         9.00 roundtrips
BenchmarkAlterTableDropColumn/alter_table_drop_3_columns-8                         	       6	 214295149 ns/op	        12.0 roundtrips
BenchmarkAlterTableDropConstraint/alter_table_drop_1_check_constraint-8            	       8	 131661118 ns/op	         4.00 roundtrips
BenchmarkAlterTableDropConstraint/alter_table_drop_2_check_constraints-8           	       8	 157199877 ns/op	         5.00 roundtrips
BenchmarkAlterTableDropConstraint/alter_table_drop_3_check_constraints-8           	       8	 155881451 ns/op	         6.00 roundtrips
BenchmarkAlterTableSplit/alter_table_split_at_1_value-8                            	      10	 176790524 ns/op	         6.00 roundtrips
BenchmarkAlterTableSplit/alter_table_split_at_2_values-8                           	      12	 209481158 ns/op	        11.0 roundtrips
BenchmarkAlterTableSplit/alter_table_split_at_3_values-8                           	      10	 129818187 ns/op	        15.0 roundtrips
BenchmarkAlterTableUnsplit/alter_table_unsplit_at_1_value-8                        	      13	 180980115 ns/op	         2.00 roundtrips
BenchmarkAlterTableUnsplit/alter_table_unsplit_at_2_values-8                       	       9	 182613212 ns/op	         4.00 roundtrips
BenchmarkAlterTableUnsplit/alter_table_unsplit_at_3_values-8                       	       9	 126987416 ns/op	         6.00 roundtrips
BenchmarkAlterTableConfigureZone/alter_table_configure_zone_5_replicas-8           	      13	  91285841 ns/op	        20.0 roundtrips
BenchmarkAlterTableConfigureZone/alter_table_configure_zone_7_replicas_-8          	      13	  87272704 ns/op	        20.0 roundtrips
BenchmarkAlterTableConfigureZone/alter_table_configure_zone_ranges-8               	      12	  93800449 ns/op	        20.0 roundtrips
BenchmarkCreateRole/create_role_with_no_options-8                                  	      22	  48413832 ns/op	         6.00 roundtrips
BenchmarkCreateRole/create_role_with_1_option-8                                    	      22	  47622130 ns/op	         6.00 roundtrips
BenchmarkCreateRole/create_role_with_2_options-8                                   	      22	  51441396 ns/op	         8.00 roundtrips
BenchmarkCreateRole/create_role_with_3_options-8                                   	      20	  64530177 ns/op	        10.0 roundtrips
BenchmarkAlterRole/alter_role_with_1_option-8                                      	      22	  49533185 ns/op	         4.00 roundtrips
BenchmarkAlterRole/alter_role_with_2_options-8                                     	      18	  58034536 ns/op	         6.00 roundtrips
BenchmarkAlterRole/alter_role_with_3_options-8                                     	       9	 129600255 ns/op	         8.00 roundtrips
BenchmarkDropRole/drop_1_role-8                                                    	      24	  54379316 ns/op	        36.0 roundtrips
BenchmarkDropRole/drop_2_roles-8                                                   	      16	  65266595 ns/op	        40.0 roundtrips
BenchmarkDropRole/drop_3_roles-8                                                   	      14	  72855087 ns/op	        44.0 roundtrips
BenchmarkDropTable/drop_1_table-8                                                  	       9	 116468918 ns/op	         7.00 roundtrips
BenchmarkDropTable/drop_2_tables-8                                                 	      10	 105755001 ns/op	        14.0 roundtrips
BenchmarkDropTable/drop_3_tables-8                                                 	       9	 133696119 ns/op	        21.0 roundtrips
BenchmarkDropView/drop_1_view-8                                                    	       7	 146123344 ns/op	         7.00 roundtrips
BenchmarkDropView/drop_2_views-8                                                   	       4	 254172100 ns/op	        21.0 roundtrips
BenchmarkDropView/drop_3_views-8                                                   	       4	 286790822 ns/op	        35.0 roundtrips
BenchmarkDropSequence/drop_1_sequence-8                                            	      10	 101458630 ns/op	         5.00 roundtrips
BenchmarkDropSequence/drop_2_sequences-8                                           	      10	 106583570 ns/op	        10.0 roundtrips
BenchmarkDropSequence/drop_3_sequences-8                                           	       9	 146715597 ns/op	        15.0 roundtrips
BenchmarkDropDatabase/drop_database_0_tables-8                                     	      16	  78022207 ns/op	         7.00 roundtrips
BenchmarkDropDatabase/drop_database_1_table-8                                      	       8	 131600202 ns/op	        12.0 roundtrips
BenchmarkDropDatabase/drop_database_2_tables-8                                     	       7	 143721591 ns/op	        17.0 roundtrips
BenchmarkDropDatabase/drop_database_3_tables-8                                     	       7	 148130803 ns/op	        22.0 roundtrips
BenchmarkGrant/grant_all_on_1_table-8                                              	      10	 123606521 ns/op	        10.0 roundtrips
BenchmarkGrant/grant_all_on_2_tables-8                                             	       7	 146730827 ns/op	        14.0 roundtrips
BenchmarkGrant/grant_all_on_3_tables-8                                             	       7	 191027885 ns/op	        18.0 roundtrips
BenchmarkRevoke/revoke_all_on_1_table-8                                            	       8	 155342564 ns/op	        10.0 roundtrips
BenchmarkRevoke/revoke_all_on_2_tables-8                                           	       7	 205825330 ns/op	        14.0 roundtrips
BenchmarkRevoke/revoke_all_on_3_tables-8                                           	       5	 226118483 ns/op	        18.0 roundtrips
BenchmarkGrantRole/grant_1_role-8                                                  	      12	 112076337 ns/op	         3.00 roundtrips
BenchmarkGrantRole/grant_2_roles-8                                                 	      12	 114867456 ns/op	         3.00 roundtrips
BenchmarkRevokeRole/revoke_1_role-8                                                	       8	 150962765 ns/op	         3.00 roundtrips
BenchmarkRevokeRole/revoke_2_roles-8                                               	       7	 160457414 ns/op	         3.00 roundtrips
BenchmarkTruncate/truncate_1_column_0_rows-8                                       	       8	 131233257 ns/op	        16.0 roundtrips
BenchmarkTruncate/truncate_1_column_1_row-8                                        	       8	 135570456 ns/op	        16.0 roundtrips
BenchmarkTruncate/truncate_1_column_2_rows-8                                       	       8	 135951403 ns/op	        15.0 roundtrips
BenchmarkTruncate/truncate_2_column_0_rows-8                                       	       9	 132431664 ns/op	        16.0 roundtrips
BenchmarkTruncate/truncate_2_column_1_rows-8                                       	       8	 128004494 ns/op	        16.0 roundtrips
BenchmarkTruncate/truncate_2_column_2_rows-8                                       	       8	 129929507 ns/op	        15.0 roundtrips
```

**Review by solongordon — CHANGES_REQUESTED** [review]
I like where this ended up! A few minor comments but in general looks good.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50953#-:-MBjGxMm7ZCeMpQ-rHJR:b-s3e5jl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai, @rohany, and @solongordon)

___
*[pkg/bench/ddl_analysis/ddl_analysis_bench.go, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50953#-MBjAvGJ3IPiiUNh8CMD:-MBjAvGM3aeyuV4oOQl4:bac9uru) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d0958533f63c9bad538a505801b511c795b78ae/pkg/bench/ddl_analysis/ddl_analysis_bench.go#L30)):*
> ```Go
> type countWithTrace struct {
> 	count int
> 	trace string
> ```

Is there still value in storing this trace even though it's not read anywhere? I guess maybe for debugging? If so would you please add a comment?
___
*[pkg/bench/ddl_analysis/ddl_analysis_bench.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50953#-MBjG6Ox3sWHpzx3JRAn:-MBjG6Ox3sWHpzx3JRAo:bjdwmym) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d0958533f63c9bad538a505801b511c795b78ae/pkg/bench/ddl_analysis/ddl_analysis_bench.go#L35)):*
> ```Go
> // RoundTripBenchTestCase is a struct that holds the name of a benchmark test
> // case for ddl analysis and the statements to run for the test.
> // Running setup, stmt and reset must be idempotent.
> ```

Is idempotency really a requirement? It looks like hardly any of your statements are idempotent to me. Maybe you mean to say that `reset` should drop any resources which would remain after dropping the current database?
___
*[pkg/bench/ddl_analysis/ddl_analysis_bench.go, line 85 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50953#-MBj9H3hE8GXKVkFozO7:-MBj9H3lBGjs-unHE0VG:b-67htof) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d0958533f63c9bad538a505801b511c795b78ae/pkg/bench/ddl_analysis/ddl_analysis_bench.go#L85)):*
> ```Go
> 				stmtToKvBatchRequests.Store(tc.stmt, countWithTrace{count: -1})
> 
> 				sql.Exec(b, tc.stmt)
> ```

I know we're more interested in the roundtrips count than the timings but it probably makes sense to only time how long it takes to execute `tc.stmt`, not the setup and teardown. Downside is it might cause `go bench` to do more iterations and thus slow down the benchmarks.

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50953)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @solongordon)

___
*[pkg/bench/ddl_analysis/ddl_analysis_bench.go, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50953#-MBjAvGJ3IPiiUNh8CMD:-MBjNoYH7BQmN1_KSbQS:bmsu0ow) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d0958533f63c9bad538a505801b511c795b78ae/pkg/bench/ddl_analysis/ddl_analysis_bench.go#L30)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Is there still value in storing this trace even though it's not read anywhere? I guess maybe for debugging? If so would you please add a comment?
</blockquote></details>

I don't think there is any value actually, removed.
___
*[pkg/bench/ddl_analysis/ddl_analysis_bench.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50953#-MBjG6Ox3sWHpzx3JRAn:-MBjNkA73bjvhKbFL94T:b-impcji) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d0958533f63c9bad538a505801b511c795b78ae/pkg/bench/ddl_analysis/ddl_analysis_bench.go#L35)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Is idempotency really a requirement? It looks like hardly any of your statements are idempotent to me. Maybe you mean to say that `reset` should drop any resources which would remain after dropping the current database?
</blockquote></details>

You're right that makes more sense to me. 
___
*[pkg/bench/ddl_analysis/ddl_analysis_bench.go, line 85 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50953#-MBj9H3hE8GXKVkFozO7:-MBjNs4B64pL8d6n6u_C:by97sgc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d0958533f63c9bad538a505801b511c795b78ae/pkg/bench/ddl_analysis/ddl_analysis_bench.go#L85)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I know we're more interested in the roundtrips count than the timings but it probably makes sense to only time how long it takes to execute `tc.stmt`, not the setup and teardown. Downside is it might cause `go bench` to do more iterations and thus slow down the benchmarks.
</blockquote></details>

Yeah I thought about this too. Putting the b.ResetTimer() and b.StopTimer() inside the for loop causes it to hang. (related issue https://github.com/golang/go/issues/27217)

We can remove the for loop, and wrap the b.ResetTimer() and b.StopTimer() around the statement execution but I'm not entirely sure what the implications of that are. I tried this and ran the benchmarks and it seems to take a lot more time, I believe the function entire function is running b.N times including the setup so the benchmarks are taking a lot more time to run. ~500s vs ~130s.  Not sure if it's worth it to try and only track the timing for the statement unless there's an easier way that I'm missing.

The variance also seems to increase a lot. Here's 3 separate drop sequence runs.
```
BenchmarkDropSequence/drop_1_sequence-8         	1000000000	         0.0608 ns/op	         5.00 roundtrips
BenchmarkDropSequence/drop_2_sequences-8        	1000000000	         0.0759 ns/op	        10.0 roundtrips
BenchmarkDropSequence/drop_3_sequences-8        	1000000000	         0.0874 ns/op	        15.0 roundtrips

BenchmarkDropSequence/drop_1_sequence-8                1000000000	         0.0545 ns/op	         5.00 roundtrips
BenchmarkDropSequence/drop_2_sequences-8              1000000000	         0.0682 ns/op	        10.0 roundtrips
BenchmarkDropSequence/drop_3_sequences-8              1000000000	         0.0687 ns/op	        15.0 roundtrips

BenchmarkDropSequence/drop_1_sequence-8         	1000000000	         0.0527 ns/op	         5.00 roundtrips
BenchmarkDropSequence/drop_2_sequences-8        	1000000000	         0.0714 ns/op	        10.0 roundtrips
BenchmarkDropSequence/drop_3_sequences-8        	1000000000	         0.0718 ns/op	        15.0 roundtrips
```

**Review by solongordon — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50953)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @solongordon)

**Comment by RichardJCai** [comment]
Thanks for the reviews!

**Comment by RichardJCai** [comment]
bors r=solongordon

**Pull request merged**
