### PR TITLE
sql: add labels to Tuples

### PR DESCRIPTION
**Pull request by BramGruneir**
In order to further solving #16971, the ability to access the content of a
tuple based on a label is required. Until now, tuples had no labels and thus
there was no way access a specific element in a tuple. This commit adds labels
to tuples and also the ability to specify them directly in the SQL dialect.
However, it does not go to the next step of adding the ability to choose an
element based on the label. That will be in a follow up commit.

Note that the ability to give tuples labels is an extension on top of Postgres'
SQL grammar. But it should be noted that this functionality is mostly for
internal use and ease of testing.

Specifically, one can now specify the names for a tuple using the following:

```sql
((1,2,3) AS a,b,c)

or

(ROW(1,2,3) AS a,b,c)
```

Similar to unlabeled tuples, the ROW keyword is optional unless there is only
a single element in the tuple.

```sql
(ROW('a') AS name)

```

However, the enclosing parentheses are always required.

Furthermore, when comparing tuples, the labels are ignored and only the types
of the elements must be comparable to each other.

This change started out by adding a `Labels` element to both the Tuple and
TTuple structs. And following the though where all the required changes led.
After this, updates to Tuple's TypeCheck where required and then a lot of
testing to ensure the correct format was applied when printing or typing them.

Release note (sql change): Tuples can now be specified with labels. They can be
specified using the new grammar `((1,2,3) AS a,b,c)`.

### CODE REVIEW

**Comment by BramGruneir** [comment]
@rytaft There are some minor changes to optimizer code here and this introduces a change to our SQL grammar.

**Comment by andy-kimball** [comment]
How does this relate to Postgres composite types? How come we're going off in this direction rather than implementing some subset of composite types? Or is the plan to take an initial step in that direction? Is our `Tuple` type (before this change and after) compatible with Postgres composite types?

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/sem/types/types.go, line 323 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25283#-LBcDYI85dkmCggNZtXL:-LBcDYI85dkmCggNZtXM:b9uow1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18dadb0cbec668f5eb8d14f0dccd683b79c5d5f/pkg/sql/sem/types/types.go#L323)):*
> ```Go
> 
> // TTuple is the type of a DTuple.
> type TTuple struct {
> ```

`TTuple` is embedded in `TTable`. That means `TTable` now has two sets of labels.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25283#-:-LBc4pCk9gkBIVv52Yuk:be8omq0)*

**Comment by knz** [comment]
> How does this relate to Postgres composite types?

It relates well (see below)

> How come we're going off in this direction rather than implementing some subset of composite types?

There's no "off" nor "rather". We are going purposefully in this direction *exactly* in order to implement postgres' composite types.

> Or is the plan to take an initial step in that direction? 

Yes this is one of the steps towards addressing #24866 in turn needed to solve #16971 in turn needed to solve #16491.

> Is our Tuple type (before this change and after) compatible with Postgres composite types?

With a resounding yes: if you look at pg's code they actually use a single data structure _with a field column labels_ to represent _every_ tuple type (with or without label). We just had failed to recognize the usefulness of this earlier. This patch fixes that.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/sql/sem/types/types.go, line 323 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25283#-LBcDYI85dkmCggNZtXL:-LBfy5A36PeIYl2MzfrQ:b-p5l1yv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18dadb0cbec668f5eb8d14f0dccd683b79c5d5f/pkg/sql/sem/types/types.go#L323)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

`TTuple` is embedded in `TTable`. That means `TTable` now has two sets of labels.
</blockquote></details>

Bram and I found out that `TTable` needs to go away. I introduced `TTable` on a hunch that since then proved to be a mistake. There's no need for it -- anything that looks like a table disappears from scalar expressions prior to type checking (with the SRF conversion which we're not yet doing completely, but will be done before 2.1).

---

*[pkg/sql/sem/types/types.go, line 339 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25283#-LBchRjWD8wvxnQamGkH:-LBfySATA2bmzM7xTid_:b3nn9te) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18dadb0cbec668f5eb8d14f0dccd683b79c5d5f/pkg/sql/sem/types/types.go#L339)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I believe this string gets printed out by the `pg_typeof` function? Are we sure it's a good idea to make the labels part of that? I notice that `TTable` is printing something like `set of {int, string}` rather than the labels. Why the inconsistency?
</blockquote></details>

1) What is printed for TTable is purely arbitary and has no precedence in pg. See my comment above.

2) I'd be indeed interested to ensure `pg_typeof` does the right thing for TTuple. However at the same time we must be mindful that pg does _not_ report the detailed type composition of a tuple with `pg_typeof` (neither for labeled nor non-labeled tuples! Our current implementation, regardless of this PR, is wrong) -- instead, if uses the name of the thing that produced the tuple type. For example:

- `select pg_typeof(kv) from kv` -> reported type name is just "kv" even though the implementation of that type is a labeled tuple
- `select pg_typeof(_pg_expandarray(...)) -> reported type name is just "record"
- `select pg_typeof(row(1,2,3)) -> also just "record"

We'll implement this transient type name logic in a later iteration. The logic is simple: any composite type derived from a table name gets the name of the table; everything else gets named "record".

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25283#-:-LBfxLqZ9vw-yhDAv2E9:b-gn6to)*

**Comment by BramGruneir** [comment]
All comments addressed, PTAL.

---

Review status: 8 of 22 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/sql/logictest/testdata/logic_test/tuple, line 689 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25283#-LBb9Apm-1rWusVHlpIY:-LCV6Zix3a8bNh0CpdVF:bnqnqve) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18dadb0cbec668f5eb8d14f0dccd683b79c5d5f/pkg/sql/logictest/testdata/logic_test/tuple#L689)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

wait why is NULL not printed. I'd have expected it to be printed.
</blockquote></details>

Nope.

Here's the result from Postgres:

```sql
SELECT (1, 2, 'hello', NULL, NULL), (true, NULL, (false, 6.6, false));
      row      |       row
---------------+------------------
 (1,2,hello,,) | (t,,"(f,6.6,f)")
(1 row)

```

And from us without the labels:

```sql
SELECT (1, 2, 'hello', NULL, NULL), (true, NULL, (false, 6.6, false));
+-----------------------------+--------------------------------+
| (1, 2, 'hello', NULL, NULL) |   (true, NULL, (false, 6.6,    |
|                             |            false))             |
+-----------------------------+--------------------------------+
| (1,2,'hello',,)             | (true,,(false, 6.6, false))    |
+-----------------------------+--------------------------------+
(1 row)

```

But I will add colnames, because I want us to be explicit about any changes to them.  

-(2.1) 
Actually, went even further and added colnames to all non-explain queries in this file.  I think it's important for us to monitor any changes to them.

---

*[pkg/sql/logictest/testdata/logic_test/tuple, line 694 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25283#-LBb9FjXEwOmDKgcl_Jc:-LCV4LkfDwNKnFh0ZTgy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18dadb0cbec668f5eb8d14f0dccd683b79c5d5f/pkg/sql/logictest/testdata/logic_test/tuple#L694)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

remove tabs here and below
</blockquote></details>

Done.

---

*[pkg/sql/parser/sql.y, line 6749 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25283#-LBb9qNeA3gHEO6lCJVz:-LCZFsVO8ejnc0utUIMQ:b80z7bm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18dadb0cbec668f5eb8d14f0dccd683b79c5d5f/pkg/sql/parser/sql.y#L6749)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This wants some changes in `parse_test.go`.
</blockquote></details>

Indeed.  Added.

---

*[pkg/sql/sem/tree/type_check.go, line 813 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25283#-LBb9fji5g0ZzHLzgzyU:-LCVC5Eh7RrorX2VRocm:bbuvggf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18dadb0cbec668f5eb8d14f0dccd683b79c5d5f/pkg/sql/sem/tree/type_check.go#L813)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Pull this check up above, then share the rest of the code for the two cases.
</blockquote></details>

Done.  Much cleaner.  I didn't like the duplication.

---

*[pkg/sql/sem/types/types.go, line 339 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25283#-LBchRjWD8wvxnQamGkH:-LCZHTzEEiXfa6cc1QBM:b3dzae2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18dadb0cbec668f5eb8d14f0dccd683b79c5d5f/pkg/sql/sem/types/types.go#L339)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

1) What is printed for TTable is purely arbitary and has no precedence in pg. See my comment above.

2) I'd be indeed interested to ensure `pg_typeof` does the right thing for TTuple. However at the same time we must be mindful that pg does _not_ report the detailed type composition of a tuple with `pg_typeof` (neither for labeled nor non-labeled tuples! Our current implementation, regardless of this PR, is wrong) -- instead, if uses the name of the thing that produced the tuple type. For example:

- `select pg_typeof(kv) from kv` -> reported type name is just "kv" even though the implementation of that type is a labeled tuple
- `select pg_typeof(_pg_expandarray(...)) -> reported type name is just "record"
- `select pg_typeof(row(1,2,3)) -> also just "record"

We'll implement this transient type name logic in a later iteration. The logic is simple: any composite type derived from a table name gets the name of the table; everything else gets named "record".


</blockquote></details>

I just added the labels here, but I'm cool with changing how the output looks.  Let me know if we want a different format.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25283#-:-LCZG7tKDw5x0A8VpDS-:b5a0au8)*

**Comment by knz** [comment]
LGTM modulo minor nits and missing links to new follow-up issues.

---

Reviewed 13 of 14 files at r2.
Review status: 21 of 22 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/logictest/testdata/logic_test/tuple, line 689 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25283#-LBb9Apm-1rWusVHlpIY:-LCZKIiu7fQ1GaZce-4E:b-7srnlq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18dadb0cbec668f5eb8d14f0dccd683b79c5d5f/pkg/sql/logictest/testdata/logic_test/tuple#L689)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Nope.

Here's the result from Postgres:

```sql
SELECT (1, 2, 'hello', NULL, NULL), (true, NULL, (false, 6.6, false));
      row      |       row
---------------+------------------
 (1,2,hello,,) | (t,,"(f,6.6,f)")
(1 row)

```

And from us without the labels:

```sql
SELECT (1, 2, 'hello', NULL, NULL), (true, NULL, (false, 6.6, false));
+-----------------------------+--------------------------------+
| (1, 2, 'hello', NULL, NULL) |   (true, NULL, (false, 6.6,    |
|                             |            false))             |
+-----------------------------+--------------------------------+
| (1,2,'hello',,)             | (true,,(false, 6.6, false))    |
+-----------------------------+--------------------------------+
(1 row)

```

But I will add colnames, because I want us to be explicit about any changes to them.  

-(2.1) 
Actually, went even further and added colnames to all non-explain queries in this file.  I think it's important for us to monitor any changes to them.
</blockquote></details>

The pretty-printing of tuples as now implemented is sufficient for a first round but is still incomplete to be compatible with pg's. Please file an issue with your example:

`(true,,(false, 6.6, false))` should really be `(t,,"(f,6.6,f)")`

then add a TODO pointing to the new issue both around here and the corresponding pretty-printing code.

We had to do something similar for arrays before. cc Justin on the new issue.

---

*[pkg/sql/logictest/testdata/logic_test/tuple, line 13 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25283#-LCZK8fQBJkmZK0JsD90:-LCZK8fQBJkmZK0JsD91:b-tnwl3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ec77a5a5122a711b5640657d5465ad0fe49a16/pkg/sql/logictest/testdata/logic_test/tuple#L13)):*
> ```
> query BBBBBBBBB colnames
> SELECT
> 	(2, 2) < (1, 1),
> ```

tabs here and below (I know you didn't introduce the tabs, but since you're at it already....)

---

*[pkg/sql/sem/types/types.go, line 339 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25283#-LBchRjWD8wvxnQamGkH:-LCZKvjn4FsC8audW0pi:b-4btntw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18dadb0cbec668f5eb8d14f0dccd683b79c5d5f/pkg/sql/sem/types/types.go#L339)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

I just added the labels here, but I'm cool with changing how the output looks.  Let me know if we want a different format.
</blockquote></details>

I think this function is OK for troubleshooting/debugging purposes. We need to change the logic of `pg_typeof` separately to do what I explained above. Mind filing an issue specifically about that? Then add a TODO to the `pg_typeof` builtin code that refers to the new issue.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25283#-:-LCZL7G91MnaLYOlwT_p:bdwmrc2)*

**Comment by knz** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25283)*

**Pull request merged**
