### PR TITLE
storage: change Stores.storeMap and Store.mu.replicas to sync.Map

### PR DESCRIPTION
**Pull request by petermattis**

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---

*[pkg/storage/store.go, line 332 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-KoNKhfvLpZLhnfnPG7i:-KoNKhfvLpZLhnfnPG7j:b-b05mva) ([raw file](https://github.com/cockroachdb/cockroach/blob/a89dcdf45efe291f506fc74f6cf6409a19a05f1a/pkg/storage/store.go#L332)):*
> ```Go
> 	// stale) consistent view of all Replicas without holding the Store lock.
> 	// In particular, no locks are acquired during the copy process.
> 	rs.repls = nil
> ```

you could probably still pre-allocate this based on one of the other replicas maps...right? might not be worth it given locking overhead.

---

*[pkg/storage/store.go, line 1604 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-KoNKvDbd1ryF53BGck_:-KoNKvDbd1ryF53BGcka:brspoqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a89dcdf45efe291f506fc74f6cf6409a19a05f1a/pkg/storage/store.go#L1604)):*
> ```Go
> // GetReplica fetches a replica by Range ID. Returns an error if no replica is found.
> func (s *Store) GetReplica(rangeID roachpb.RangeID) (*Replica, error) {
> 	value, ok := s.mu.replicas.Load(rangeID)
> ```

can you make this:
```
if value, ok := ...; ok {
  return value.(*Replica), nil
}
return nil, roachpb.New...()
```

---

*[pkg/storage/store.go, line 2122 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-KoNLEpIA5U1B1h9rsO5:-KoNLEpIA5U1B1h9rsO6:bjm11ac) ([raw file](https://github.com/cockroachdb/cockroach/blob/a89dcdf45efe291f506fc74f6cf6409a19a05f1a/pkg/storage/store.go#L2122)):*
> ```Go
> // addReplicaToRangeMapLocked requires that the store lock is held.
> func (s *Store) addReplicaToRangeMapLocked(repl *Replica) error {
> 	if _, ok := s.mu.replicas.Load(repl.RangeID); ok {
> ```

I think this might be the only use case for `LoadOrStore` !

---

*[pkg/storage/store.go, line 2370 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-KoNL_adsXCzarX7_D28:-KoNL_adsXCzarX7_D29:bel9hk5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a89dcdf45efe291f506fc74f6cf6409a19a05f1a/pkg/storage/store.go#L2370)):*
> ```Go
> // ReplicaCount returns the number of replicas contained by this store. This
> // method is O(n) in the number of replicas and should not be called from
> // performance critical code.
> ```

another case where you might be able to lock and use `len` on one of the other maps

---

*[pkg/storage/store.go, line 3515 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-KoNLmWQ1aqwQ7MK4ssZ:-KoNLmWQ1aqwQ7MK4ss_:b-zaruzq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a89dcdf45efe291f506fc74f6cf6409a19a05f1a/pkg/storage/store.go#L3515)):*
> ```Go
> 	value, ok := s.mu.replicas.Load(rangeID)
> 
> 	var exists bool
> ```

while you're here, can you make this a bit less awkward?

```
value, ok := ...
if !ok {
  return false
}
...
exists, err := ...
if err != nil {
  ...
}
return exists
```

Also probably an easy target for plumbing a context, but feel free to leave that as is

---

*[pkg/storage/store.go, line 3700 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-KoNMCPoPtoYixkHo6-c:-KoNMCPoPtoYixkHo6-d:b-vbbysg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a89dcdf45efe291f506fc74f6cf6409a19a05f1a/pkg/storage/store.go#L3700)):*
> ```Go
> ) (_ *Replica, created bool, _ error) {
> 	// The common case: look up an existing (initialized) replica.
> 	value, ok := s.mu.replicas.Load(rangeID)
> ```

can you narrow the scope of `value`? `if value, ok := ...; ok {`

---

*[pkg/storage/stores.go, line 86 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-KoNMYohURpTX2Cyoq_H:-KoNMYohURpTX2Cyoq_I:b-jxv0zz) ([raw file](https://github.com/cockroachdb/cockroach/blob/836493ff6330c9368a463bab656905bcf4d49815/pkg/storage/stores.go#L86)):*
> ```Go
> // if not found.
> func (ls *Stores) GetStore(storeID roachpb.StoreID) (*Store, error) {
> 	value, ok := ls.mu.storeMap.Load(storeID)
> ```

```
if value, ok := ...; ok {
  return value.(..), nil
}
return nil, ...
```

---

*[pkg/storage/stores.go, line 97 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-KoNMfqNiVTSfJtIjY9Y:-KoNMfqNiVTSfJtIjY9Z:b-n8fi6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/836493ff6330c9368a463bab656905bcf4d49815/pkg/storage/stores.go#L97)):*
> ```Go
> 	ls.mu.Lock()
> 	defer ls.mu.Unlock()
> 	if _, loaded := ls.mu.storeMap.LoadOrStore(s.Ident.StoreID, s); loaded {
> ```

why the departure from `ok` here?

---

*[pkg/storage/stores.go, line 99 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-KoNMjWi5NWhrnBEbTZ7:-KoNMjWi5NWhrnBEbTZ8:bmwwtwd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6502ae7a1c0932d49ea6fe90d7604cf37d2c095/pkg/storage/stores.go#L99)):*
> ```Go
> 		panic(fmt.Sprintf("cannot add store twice: %+v", s.Ident))
> 	}
> 	ls.storeMap[s.Ident.StoreID] = s
> ```

did you forget to actually add the store here? Another use case for LoadOrStore.

---

*[pkg/storage/stores.go, line 129 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-KoNN9P_CbobdHLIeYRw:-KoNN9Pa2D7qAakDT8XA:bd7tz9i) ([raw file](https://github.com/cockroachdb/cockroach/blob/836493ff6330c9368a463bab656905bcf4d49815/pkg/storage/stores.go#L129)):*
> ```Go
> 			return false
> 		}
> 		return true
> ```

nit: a bunch of these can be `return err == nil` - whether that's better is up to you

---

*[pkg/storage/stores.go, line 290 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-KoNMzXKYKAo8lGv3ACQ:-KoNMzXKYKAo8lGv3ACR:b-hpqpun) ([raw file](https://github.com/cockroachdb/cockroach/blob/836493ff6330c9368a463bab656905bcf4d49815/pkg/storage/stores.go#L290)):*
> ```Go
> 	ls.mu.storeMap.Range(func(k, v interface{}) bool {
> 		s := v.(*Store)
> 		var storeBI gossip.BootstrapInfo
> ```

nit: you could hoist this out of the closure and save some allocations

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877)*

**Comment by petermattis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 11 unresolved discussions, some commit checks pending.

---

*[pkg/storage/store.go, line 332 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-KoNKhfvLpZLhnfnPG7i:-KoNOT8gWV-1Ha0yxDUo:bjn0jvb) ([raw file](https://github.com/cockroachdb/cockroach/blob/a89dcdf45efe291f506fc74f6cf6409a19a05f1a/pkg/storage/store.go#L332)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

you could probably still pre-allocate this based on one of the other replicas maps...right? might not be worth it given locking overhead.
</blockquote></details>

We don't have an easy count of the number of replicas any more. This isn't performance critical code so I didn't want to bother with anything fancy.

---

*[pkg/storage/store.go, line 1604 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-KoNKvDbd1ryF53BGck_:-KoNOhzoTeI8TKhnrJPV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a89dcdf45efe291f506fc74f6cf6409a19a05f1a/pkg/storage/store.go#L1604)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can you make this:
```
if value, ok := ...; ok {
  return value.(*Replica), nil
}
return nil, roachpb.New...()
```
</blockquote></details>

Done.

---

*[pkg/storage/store.go, line 2122 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-KoNLEpIA5U1B1h9rsO5:-KoNOnzu1p5kORhjbkqw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a89dcdf45efe291f506fc74f6cf6409a19a05f1a/pkg/storage/store.go#L2122)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I think this might be the only use case for `LoadOrStore` !
</blockquote></details>

Done.

---

*[pkg/storage/store.go, line 2370 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-KoNL_adsXCzarX7_D28:-KoNOqHE_JexwrMaaeyw:b-9gjz1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/a89dcdf45efe291f506fc74f6cf6409a19a05f1a/pkg/storage/store.go#L2370)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

another case where you might be able to lock and use `len` on one of the other maps
</blockquote></details>

None of the other maps have the right length!

---

*[pkg/storage/store.go, line 3515 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-KoNLmWQ1aqwQ7MK4ssZ:-KoNPEW5Afvb5rucaJRf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a89dcdf45efe291f506fc74f6cf6409a19a05f1a/pkg/storage/store.go#L3515)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

while you're here, can you make this a bit less awkward?

```
value, ok := ...
if !ok {
  return false
}
...
exists, err := ...
if err != nil {
  ...
}
return exists
```

Also probably an easy target for plumbing a context, but feel free to leave that as is
</blockquote></details>

Done.

---

*[pkg/storage/store.go, line 3700 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-KoNMCPoPtoYixkHo6-c:-KoNPK8JNW9JU4B2-Tp_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a89dcdf45efe291f506fc74f6cf6409a19a05f1a/pkg/storage/store.go#L3700)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can you narrow the scope of `value`? `if value, ok := ...; ok {`
</blockquote></details>

Done.

---

*[pkg/storage/stores.go, line 86 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-KoNMYohURpTX2Cyoq_H:-KoNRPCDdK8FNQia4OmP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/836493ff6330c9368a463bab656905bcf4d49815/pkg/storage/stores.go#L86)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

```
if value, ok := ...; ok {
  return value.(..), nil
}
return nil, ...
```
</blockquote></details>

Done.

---

*[pkg/storage/stores.go, line 97 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-KoNMfqNiVTSfJtIjY9Y:-KoNPMX7KaFnOVqdXG-n:b-wfaad8) ([raw file](https://github.com/cockroachdb/cockroach/blob/836493ff6330c9368a463bab656905bcf4d49815/pkg/storage/stores.go#L97)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why the departure from `ok` here?
</blockquote></details>

I felt that it was unclear what was `ok`. Was the value loaded ok or stored ok? Naming the var `loaded` makes it clearer why `true` is the error case.

---

*[pkg/storage/stores.go, line 99 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-KoNMjWi5NWhrnBEbTZ7:-KoNPV9-U52SD3QTlhdK:b-itvbd7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6502ae7a1c0932d49ea6fe90d7604cf37d2c095/pkg/storage/stores.go#L99)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

did you forget to actually add the store here? Another use case for LoadOrStore.
</blockquote></details>

We only get here if the value was successfully stored via `LoadOrStore`.

---

*[pkg/storage/stores.go, line 129 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-KoNN9P_CbobdHLIeYRw:-KoNPibIGQqVXofXzQmW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/836493ff6330c9368a463bab656905bcf4d49815/pkg/storage/stores.go#L129)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: a bunch of these can be `return err == nil` - whether that's better is up to you
</blockquote></details>

Done.

---

*[pkg/storage/stores.go, line 290 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-KoNMzXKYKAo8lGv3ACQ:-KoNPkaRend8fRhR3hY-:bilrp50) ([raw file](https://github.com/cockroachdb/cockroach/blob/836493ff6330c9368a463bab656905bcf4d49815/pkg/storage/stores.go#L290)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: you could hoist this out of the closure and save some allocations
</blockquote></details>

This isn't performance critical code. I'd rather leave as-is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/storage/stores.go, line 99 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-KoNMjWi5NWhrnBEbTZ7:-KoNUJEiJrwkQVw67Ybg:bg1lwba) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6502ae7a1c0932d49ea6fe90d7604cf37d2c095/pkg/storage/stores.go#L99)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

We only get here if the value was successfully stored via `LoadOrStore`.
</blockquote></details>

Ah, didn't notice the LoadOrStore above. Carry on.

---

*[pkg/storage/stores.go, line 230 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-KoNUZCv8I6fsq5wJD_A:-KoNUZCv8I6fsq5wJD_B:bagxpxb) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b01649df6643158275984b6aa0fa8cf3e1ebdd1/pkg/storage/stores.go#L230)):*
> ```Go
> 				return true
> 			}
> 			return false
> ```

`return err == nil`

---

*[pkg/storage/stores.go, line 240 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-KoNUqdiYsui1WaDDggy:-KoNUqdiYsui1WaDDggz:b-iqkwrk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b01649df6643158275984b6aa0fa8cf3e1ebdd1/pkg/storage/stores.go#L240)):*
> ```Go
> 
> 		repDescFound = true
> 		return false
> ```

I think this should be `return true`, no? Better yet, I think it should be `return err == nil` and the `remove false` above removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-:-KoNV0cA9t-1mUpnZr5E:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/storage/stores.go, line 230 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-KoNUZCv8I6fsq5wJD_A:-KoNWU-Ejbuwmep0aLCw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b01649df6643158275984b6aa0fa8cf3e1ebdd1/pkg/storage/stores.go#L230)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

`return err == nil`
</blockquote></details>

Done.

---

*[pkg/storage/stores.go, line 240 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-KoNUqdiYsui1WaDDggy:-KoNWb7l3wgTzahbxQJw:b-2s6ii3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b01649df6643158275984b6aa0fa8cf3e1ebdd1/pkg/storage/stores.go#L240)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I think this should be `return true`, no? Better yet, I think it should be `return err == nil` and the `remove false` above removed.
</blockquote></details>

Yep. Yes, we could `return err == nil` here, but I made that change and it seemed too subtle.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r3, 1 of 1 files at r4.
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/storage/store.go, line 330 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-KoNUngcXE4OeudN20p5:-KoNUngcXE4OeudN20p6:btc6b9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b01649df6643158275984b6aa0fa8cf3e1ebdd1/pkg/storage/store.go#L330)):*
> ```Go
> func (rs *storeReplicaVisitor) Visit(visitor func(*Replica) bool) {
> 	// Copy the range IDs to a slice so that we iterate over some (possibly
> 	// stale) consistent view of all Replicas without holding the Store lock.
> ```

`sync.Map.Range` does not guarantee a consistent view. I don't think that matters for the way this method is used, but this comment should be updated. 

---

*[pkg/storage/stores.go, line 49 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-KoNWQf-RxzO9rbaeNL2:-KoNWQf-RxzO9rbaeNL3:b-u9818h) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b01649df6643158275984b6aa0fa8cf3e1ebdd1/pkg/storage/stores.go#L49)):*
> ```Go
> 	mu    struct {
> 		syncutil.RWMutex
> 		storeMap   syncmap.Map           // map[roachpb.StoreID]*Store
> ```

Comment that the map may be read without holding the mutex, but writes should still hold it. (Does that matter? Can we move this out of `mu` completely?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-:-KoNXeBtdABuycx3XfOH:bnfp4nl)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877)*

**Comment by petermattis** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/storage/store.go, line 330 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-KoNUngcXE4OeudN20p5:-KoNYCUtsGRwcoUaVSdR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b01649df6643158275984b6aa0fa8cf3e1ebdd1/pkg/storage/store.go#L330)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

`sync.Map.Range` does not guarantee a consistent view. I don't think that matters for the way this method is used, but this comment should be updated. 
</blockquote></details>

Done.

---

*[pkg/storage/stores.go, line 49 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877#-KoNWQf-RxzO9rbaeNL2:-KoNYGH1_SPcjf6EiW7-:b-1wz0bo) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b01649df6643158275984b6aa0fa8cf3e1ebdd1/pkg/storage/stores.go#L49)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Comment that the map may be read without holding the mutex, but writes should still hold it. (Does that matter? Can we move this out of `mu` completely?)
</blockquote></details>

Done. Yeah, I don't think holding the mutex here is necessary for writes. The mutex is really only protecting `biLatestTS` and `latestBI`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877)*

**Comment by tamird** [comment]
Reviewed 1 of 2 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16877)*

**Pull request merged**
