### PR TITLE
delegate: implement SHOW REGIONS

### PR DESCRIPTION
**Pull request by otan**
Release note (sql change): Implement `SHOW REGIONS`, which shows a list
of regions along with the databases associated with them.

### CODE REVIEW

**Review by ajstorm — COMMENTED** [review]
This change looks reasonable to me, but I'm interested in @nvanbenschoten's and @awoods187's opinions on whether this is the right collection of information to show on SHOW REGIONS.  I personally like it, and could see this being very useful to customers.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57618#-:-MNyW1zl8BTy-NJjNOwe:b-jt3af0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57618#-MNyVhDjDmJKR4sfro63:-MNyVhDjDmJKR4sfro64:b-4r6qsn) ([raw file](https://github.com/cockroachdb/cockroach/blob/0619cb2cd2e8e9f003a5fde8ff82fd939f70c67e/pkg/sql/logictest/testdata/logic_test/multiregion#L115)):*
> ```
> 
> query TTTT colnames
> SHOW REGIONS
> ```

Nit: Might make sense to also add a test before any databases are created (and/or after only one has been created), so we can ensure it works there as well.

**Comment by otan** [comment]
___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57618#-MNyVhDjDmJKR4sfro63:-MNyffx4-ZLWnasfokmj:byz12wt) ([raw file](https://github.com/cockroachdb/cockroach/blob/0619cb2cd2e8e9f003a5fde8ff82fd939f70c67e/pkg/sql/logictest/testdata/logic_test/multiregion#L115)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Nit: Might make sense to also add a test before any databases are created (and/or after only one has been created), so we can ensure it works there as well.
</blockquote></details>

there is! first few lines

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57618)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57618#-MNyVhDjDmJKR4sfro63:-MNysTDP74OFPDW6S11F:b-ft7ctm) ([raw file](https://github.com/cockroachdb/cockroach/blob/0619cb2cd2e8e9f003a5fde8ff82fd939f70c67e/pkg/sql/logictest/testdata/logic_test/multiregion#L115)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

there is! first few lines
</blockquote></details>

gah!  I looked right at it, and it was in green, and I still didn't clue in.  Too much doc reading :-(

**Comment by otan** [comment]
merge now, convince @awoods187 later? :P

**Review by ajstorm — APPROVED** [review]
> merge now, convince @awoods187 later? :P

+1

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57618#-:-MQoFWTS5oXrO9AZsoW8:bt9yqu6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

**Comment by otan** [comment]
bors r=ajstorm

**Comment by otan** [comment]
flake!

bors r=ajstorm

**Pull request merged**
