### PR TITLE
catalog: spin off and adopt back-reference validation level

### LINKED ISSUE #85263: catalog: spin validation of back-references off into distinct phase
Presently, when reading a descriptor, we validate its internal consistency with the `ValidateSelf` phase and its referential consistency with the `ValidateCrossReferences` phase. The problem is that if the descriptor has corrupt back-references, validation will fail and render the table unavailable even when the descriptor is leased just to run a query. Back-references only come into play when dropping things in DDL statements. For this reason we should split `ValidateCrossReferences` into two distinct phases and only validate forward references on reads.

Or, at least, only in reads for leasing for a query, make validation usage aware. Also, perhaps validate back-references, but log errors instead of returning them.

Jira issue: CRDB-18145

### PR DESCRIPTION
**Pull request by postamar**
Previously, forward- and backward-reference-checking was done in one
same validation phase, identified by the
catalog.ValidationLevelCrossReferences constant and a similarly named
method on catalog.Descriptor. This validation phase was exercised both
when reading and when writing descriptors.

The problem with this was that a corrupt back-reference would make
a table unusable until descriptor surgery was performed. While this
might be warranted in the context of schema changes, that's not the case
when it comes to queries, which don't really care about these
back-references. For this reason, we want to bypass back-reference
validation when reading descriptors for the purpose of serving queries.
These reads are characterized by the flag AvoidLeased being unset.

To do this, this commit splits the cross-reference validation level into
two. The back-reference level now exists to check the integrity of
back-references directly, as well as to check that forward references
also have matching back-references in the referenced descriptors.

Fixes #85263.

Release justification: low-risk, high benefit change
Release note: None

---- 

This PR is based on https://github.com/cockroachdb/cockroach/pull/87067 which is the product of what made sense for me to take action on right now regarding https://github.com/cockroachdb/cockroach/pull/86420#issuecomment-1223101292 .

### CODE REVIEW

**Comment by postamar** [comment]
The descriptors collection is way too self-referential for this to work reliably. It calls itself for validation and hydration in ways which are impossible to reason about. I think the way to go here is to tighten the self-referential parts into an inner core object of sorts:
- this object contains the layers (virtual, temporary, synthetic, stored and leased);
- it serves `getByIDs` queries, along with `getByName` and `getAllDescriptors` and other similar endpoints;
- it handles validation and type hydration, along with memory management and caching;
- the lease manager, the kv layer etc. can be dependency-injected so that we can do some kind of tracing, have data-driven tests, etc.

**Comment by postamar** [comment]
This is ready for review now, it's correct enough.

**Review by ajwerner — APPROVED** [review]
:lgtm: nice!

> Reviewed 28 of 28 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86420#-:-NBO_zm_5UcMuhQVtQuh:b-7yytuz)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @postamar)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_primary_key.go` line 397 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86420#-NBO_dQLBzh6T0Khv0cI:-NBO_dQM-9v_4gmik_LJ:b-ro9xcs) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d2dd8d882fb51edf3e9f5388fe8139c9ab6433f/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_primary_key.go#L397)):*
> ```Go
> 	if _, _, inboundFKElem := scpb.FindForeignKeyConstraint(b.BackReferences(tableID)); inboundFKElem != nil {
> 		panic(scerrors.NotImplementedErrorf(t.n,
> 			fmt.Sprintf(`foreign keys to table with TTL %q are not permitted`, ns.Name)))
> ```

why `fmt.Sprintf`? It's already a formatting method, no? This is going to lead to redaction in a bad way
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_primary_key.go` line 400 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86420#-NBO_YhGDnr79OrDep16:-NBO_YhGDnr79OrDep17:b-ro9xcs) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d2dd8d882fb51edf3e9f5388fe8139c9ab6433f/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_primary_key.go#L400)):*
> ```Go
> 	}
> 	if _, _, outboundFKElem := scpb.FindForeignKeyConstraint(b.QueryByID(tableID)); outboundFKElem != nil {
> 		panic(scerrors.NotImplementedErrorf(t.n,
> ```

why `fmt.Sprintf`? It's already a formatting method, no? This is going to lead to redaction in a bad way

**Comment by postamar** [comment]
Thanks for the review! No good reason why `fmt.Sprintf` is being used there. Fixing.

**Pull request merged**
