### PR TITLE
ui: Login page

### LINKED ISSUE #46082: ui: Update Admin UI login page styles
Update Admin UI login page styles to match design system. [Figma link
](https://www.figma.com/file/8Bf4FQHSh2IcevigXlpWah/obsrv_admin-ui-login?node-id=86%3A668)

Here is the [CockroachCloud](https://cockroachlabs.cloud/) login screen for reference

**current**
Screen Shot 2020-03-12 at 3 03 36 PM

**new**
Login_01

# Testing
## Storybook
- Login widget with valid/invalid states
## Manual
- Create a local secure cluster, use login page to login as an admin user. Try entering a bad password to ensure that validation is checked.

### PR DESCRIPTION
**Pull request by vladlos**
Updated Admin UI login page styles to match design system.

login
logjn2
login3
login4

Resolves: #46082

Release note (ui): login page design updates

### CODE REVIEW

**Review by dhartunian — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46783)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @elkmaster)

___
*[pkg/ui/src/components/button/button.tsx, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46783#-M4R1haH0fxXSZCA4Ynr:-M4R1haH0fxXSZCA4Yns:b-k45bad) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1eb38ded273b3a4204f5463e7ed42c91220af41/pkg/ui/src/components/button/button.tsx#L26)):*
> ```XML
>   onClick?: (event: React.MouseEvent<HTMLElement>) => void;
>   className?: string;
>   buttonType?: "button" | "submit" | "reset";
> ```

Instead of this, can we add a standard button HTML element prop type into the interface? Then we can add all the standard props.
___
*[pkg/ui/src/components/textInput/index.tsx, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46783#-M4R2-RFEs7V4Uc2CNzd:-M4R2-RFEs7V4Uc2CNze:b3fxo8s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1eb38ded273b3a4204f5463e7ed42c91220af41/pkg/ui/src/components/textInput/index.tsx#L94)):*
> ```XML
> 
>   togglePassword = () => {
>     this.setState({
> ```

if setState is accessing existing state, should we be passing a lambda as argument?
___
*[pkg/ui/src/components/textInput/index.tsx, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46783#-M4R2B-G8aL4KImFekSn:-M4R2B-G8aL4KImFekSo:bq3jv21) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1eb38ded273b3a4204f5463e7ed42c91220af41/pkg/ui/src/components/textInput/index.tsx#L99)):*
> ```XML
>   }
> 
>   renderPasswordIcon = () => (
> ```

I think you might be overloading the Input component with too much responsibility. What do you think of creating a PasswordInput component?

I think in particular stuff inside `src/components` we should try to keep free of `renderBlah` methods and boolean rendering etc etc.
___
*[pkg/ui/src/views/login/loginPage.tsx, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46783#-M4R2Tlm3wCJqUPpL3ei:-M4R2Tlm3wCJqUPpL3ej:b-9op11i) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1eb38ded273b3a4204f5463e7ed42c91220af41/pkg/ui/src/views/login/loginPage.tsx#L21)):*
> ```XML
> 
> import "./loginPage.styl";
> import { CockroachLabsLockupIcon, Button, TextInput } from "oss/src/components";
> ```

remove `oss`
___
*[pkg/ui/src/views/login/loginPage.tsx, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46783#-M4R5TkPEZoZ5Y8VXxBY:-M4R5TkPEZoZ5Y8VXxBZ:b-vy40ts) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1eb38ded273b3a4204f5463e7ed42c91220af41/pkg/ui/src/views/login/loginPage.tsx#L104)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>     const { username, password } = this.state;
>     const userNameLength = username.length > 0;
>     const passwordLength = password.length > 0;
> 
>     this.setState({
>       canSubmit: userNameLength && passwordLength,
>     });
> ```
</details>


This is not part of the field validation and the code should be somewhere else maybe the render method. Is there a strong need to have this be part of the component state?

**Comment by elkmaster** [comment]
@dhartunian, I agree with your comments about button and input components, but it will lead to changes in a lot of places where this components is used. I would assume that this worth it's own pr\
ticket. What you think?

**Review by dhartunian — CHANGES_REQUESTED** [review]
Can you rebase on master so the release justification requirement goes away?

Also, I think this PR is a good candidate to test out our newly merged Storybook PR.
Can you add some stories for the login components and the login pane? Let me know if the CSS makes it difficult.

> Reviewed 12 of 12 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46783#-:-M4yd3Mk2fA4iIoKy0Bw:b1uy4s9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @elkmaster)

**Review by dhartunian — CHANGES_REQUESTED** [review]
Love the stories! Thanks @elkmaster!

This commit does not currently work for me with a secure cluster running locally.

I followed instructions here: https://www.cockroachlabs.com/docs/stable/secure-a-cluster.html (only 1 node needed) and proxied using `make ui-watch-secure TARGET=https://127.0.0.1:8080`. Correctly logging in returns a 200 in devtools but doesn't take me to the overview page.

> Reviewed 7 of 8 files at r5, 3 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46783#-:-M5U0qWq5zMToFc7WgsO:b-y8merv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @elkmaster)

**Review by dhartunian — CHANGES_REQUESTED** [review]
> Reviewed 2 of 14 files at r7, 7 of 8 files at r9, 4 of 5 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46783)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @elkmaster)

___
*[pkg/ui/.storybook/config.tsx, line 27 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/46783#-M5i2Rn37FFdP1_l9CSo:-M5i2Rn37FFdP1_l9CSp:bu1pjxg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e96b5be01024e7cc9a6b24e5d1b8c9dffd4b2c17/pkg/ui/.storybook/config.tsx#L27)):*
> ```XML
> 
> addDecorator(storyFn => (
>   <div style={{padding: "24px"}}>
> ```

Instead of removing this, can you amend the story to just show the login pane isolated from the entire page?
___
*[pkg/ui/src/components/input/index.ts, line 11 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/46783#-M5i3o2w4LRJxUM_gSdV:-M5i3o2x7vJ_400pKpZI:b-yp2dmh) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b23cdda2076fe94c25af1a22d6d8e7c94f10fdc/pkg/ui/src/components/input/index.ts#L11)):*
> ```XML
> // licenses/APL.txt.
> 
> export * from "./textInput";
> ```

does this need to change to `input`? 
___
*[pkg/ui/src/components/input/passwordInput.tsx, line 48 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/46783#-M5i3w7L8BTGn44B_5PI:-M5i3w7L8BTGn44B_5PJ:b-xxg1zz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b23cdda2076fe94c25af1a22d6d8e7c94f10fdc/pkg/ui/src/components/input/passwordInput.tsx#L48)):*
> ```XML
> 
>   renderPasswordIcon = (showPassword: boolean) => (
>     <Button type="flat" onClick={this.togglePassword} className="crl-button__show-password">
> ```

can we get this button to be skipped in tab order? when I hit `TAB` and then `Enter` in the login after entering my password it shows my password which is unexpected.
___
*[pkg/ui/src/redux/login.ts, line 213 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/46783#-M5i5R7cCKo3V34Ekc-f:-M5i5R7dDAzCn1w-xLYB:b-479ry9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b23cdda2076fe94c25af1a22d6d8e7c94f10fdc/pkg/ui/src/redux/login.ts#L213)):*
> ```XML
>         () => {
>           dispatch(loginSuccess(username));
>           return { status: 200 };
> ```

Can we listen to the redux event in the login component and respond to the dispatch? Feels odd to dispatch an event and return something. This function has a return type of `ThunkAction<Promise<void>,...>` so it should not be returning anything.

**Comment by dhartunian** [comment]
@elkmaster can you add a comment describing the changes you made in the last push?

**Comment by elkmaster** [comment]
- create reusable storybook decorators utils to resolve issue with padding for stories. 
- updated login form to skip "view password" button while navigation with tab.
- removed `return` part from dispatch action, use redux state for redirects instead
- minor updates, rebase

**Review by dhartunian — APPROVED** [review]
@elkmaster looks good. Please rebase and then go ahead with bors when it's green.

**Pull request merged**
