### PR TITLE
colexec: add default aggregate function

### PR DESCRIPTION
**Pull request by yuzefovich**
Depends on #51337.
Depends on #52315.

**colexec: add default aggregate function**

This commit introduces "default" aggregate function which is an adapter
from `tree.AggregateFunc` to `colexec.aggregateFunc`. It works as
follows:
- the aggregator (either hash or ordered) is responsible for converting
all necessary vectors to `tree.Datum` columns before calling `Compute`
(this allows us to share the conversion between multiple functions if
they happened to take in the same columns and between multiple groups in
case of the hash aggregator)
- the default aggregate function populates "arguments" to be passed into
the wrapped `tree.AggregateFunc` and adds them
- when the new group is encountered, the result so far is flushed and
the wrapped `tree.AggregateFunc` is reset.

One detail is that these wrapped `tree.AggregateFunc`s need to be
closed, and currently that responsibility lies with the alloc object
that is creating them. In the future, we might want to shift the
responsibility to the aggregators.

Addresses: #43561.

Release note: None

**colexec: clean up hash aggregate functions**

Hash aggregate function always have non-nil `sel`, and this commit
removes the code generation for nil `sel` case (meaning it removes the
dead code). It also templates out nulls vs no-nulls cases in `bool_and`
and `bool_or` aggregates.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
The comparison against the wrapped rowexec processor is rather positive:
```
BenchmarkAggregatorsAgainstWrappedProcessors/hash/STRING_AGG/groupSize=1/nulls=false/wrapped-16         	      16	  68629312 ns/op	  15.28 MB/s
BenchmarkAggregatorsAgainstWrappedProcessors/hash/STRING_AGG/groupSize=1/nulls=false/vectorized-16      	      25	  40485154 ns/op	  25.90 MB/s
BenchmarkAggregatorsAgainstWrappedProcessors/hash/STRING_AGG/groupSize=4/nulls=false/wrapped-16         	      40	  26597027 ns/op	  39.42 MB/s
BenchmarkAggregatorsAgainstWrappedProcessors/hash/STRING_AGG/groupSize=4/nulls=false/vectorized-16      	      51	  22222534 ns/op	  47.19 MB/s
BenchmarkAggregatorsAgainstWrappedProcessors/hash/STRING_AGG/groupSize=16/nulls=false/wrapped-16        	      52	  21222130 ns/op	  49.41 MB/s
BenchmarkAggregatorsAgainstWrappedProcessors/hash/STRING_AGG/groupSize=16/nulls=false/vectorized-16     	      78	  15627650 ns/op	  67.10 MB/s
BenchmarkAggregatorsAgainstWrappedProcessors/hash/STRING_AGG/groupSize=64/nulls=false/wrapped-16        	      58	  19286233 ns/op	  54.37 MB/s
BenchmarkAggregatorsAgainstWrappedProcessors/hash/STRING_AGG/groupSize=64/nulls=false/vectorized-16     	      88	  13062478 ns/op	  80.27 MB/s
BenchmarkAggregatorsAgainstWrappedProcessors/hash/STRING_AGG/groupSize=1024/nulls=false/wrapped-16      	      70	  17265061 ns/op	  60.73 MB/s
BenchmarkAggregatorsAgainstWrappedProcessors/hash/STRING_AGG/groupSize=1024/nulls=false/vectorized-16   	     132	   9052391 ns/op	 115.83 MB/s
BenchmarkAggregatorsAgainstWrappedProcessors/ordered/STRING_AGG/groupSize=1/nulls=false/wrapped-16      	      39	  31631538 ns/op	  33.15 MB/s
BenchmarkAggregatorsAgainstWrappedProcessors/ordered/STRING_AGG/groupSize=1/nulls=false/vectorized-16   	      90	  12740350 ns/op	  82.30 MB/s
BenchmarkAggregatorsAgainstWrappedProcessors/ordered/STRING_AGG/groupSize=4/nulls=false/wrapped-16      	      66	  17845765 ns/op	  58.76 MB/s
BenchmarkAggregatorsAgainstWrappedProcessors/ordered/STRING_AGG/groupSize=4/nulls=false/vectorized-16   	     142	   8276803 ns/op	 126.69 MB/s
BenchmarkAggregatorsAgainstWrappedProcessors/ordered/STRING_AGG/groupSize=16/nulls=false/wrapped-16     	      82	  15065607 ns/op	  69.60 MB/s
BenchmarkAggregatorsAgainstWrappedProcessors/ordered/STRING_AGG/groupSize=16/nulls=false/vectorized-16  	     163	   7316560 ns/op	 143.32 MB/s
BenchmarkAggregatorsAgainstWrappedProcessors/ordered/STRING_AGG/groupSize=64/nulls=false/wrapped-16     	      86	  14487031 ns/op	  72.38 MB/s
BenchmarkAggregatorsAgainstWrappedProcessors/ordered/STRING_AGG/groupSize=64/nulls=false/vectorized-16  	     157	   7523532 ns/op	 139.37 MB/s
BenchmarkAggregatorsAgainstWrappedProcessors/ordered/STRING_AGG/groupSize=1024/nulls=false/wrapped-16   	      86	  14206792 ns/op	  73.81 MB/s
BenchmarkAggregatorsAgainstWrappedProcessors/ordered/STRING_AGG/groupSize=1024/nulls=false/vectorized-16         	     160	   7407518 ns/op	 141.56 MB/s
```
And the absolute speeds are pretty good as well: [string_agg](https://gist.github.com/yuzefovich/5c484d70e0ac044c0da61691631d9ba7). Note that the numbers are somewhat inflated when comparing against other optimized aggregate functions because `string_agg` takes in two columns as arguments.

**Comment by yuzefovich** [comment]
The benchmarks of the last commit are [here](https://gist.github.com/yuzefovich/8106bd1eb13fad97459e44a0e3121f0e) and [here](https://gist.github.com/yuzefovich/22211d16abc5b0facbc57089d055eddc).

**Comment by yuzefovich** [comment]
Only last two commits belong in this PR.

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r3, 15 of 26 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52174)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/aggregate_funcs.go, line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-ME7J9dV9s16x1s-pdsM:-ME7J9dW8KijiobQUIb7:b-m0zqyt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a175e6898ec5445eddb5291a5c996b2e755b132a/pkg/sql/colexec/aggregate_funcs.go#L25)):*
> ```Go
> )
> 
> // isAggOptimized returns whether aggFn has optimized implementation.
> ```

nit: `s/has/has an/`
___
*[pkg/sql/colexec/aggregate_funcs.go, line 195 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-ME7N1nL5ARrH9pk31rE:-ME7N1nL5ARrH9pk31rF:b-5x97ff) ([raw file](https://github.com/cockroachdb/cockroach/blob/a175e6898ec5445eddb5291a5c996b2e755b132a/pkg/sql/colexec/aggregate_funcs.go#L195)):*
> ```Go
> 	funcAllocs := make([]aggregateFuncAlloc, len(spec.Aggregations))
> 	var toClose Closers
> 	var idxsToConvert util.FastIntSet
> ```

Is this over-optimization? If so, I would just use `[]int`. If not, see if `newVecToDatumConverter` can use `FastIntSet` to avoid having to convert?
___
*[pkg/sql/colexec/aggregate_funcs.go, line 299 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-ME7Nsb43wIZiLUjRFhd:-ME7Nsb43wIZiLUjRFhe:b-ummpt0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a175e6898ec5445eddb5291a5c996b2e755b132a/pkg/sql/colexec/aggregate_funcs.go#L299)):*
> ```Go
> 
> 		if err != nil {
> 			return nil, nil, toClose, err
> ```

Are closers closed on error?
___
*[pkg/sql/colexec/aggregate_funcs.go, line 345 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-ME7OBXuEHSVYxNgA5FB:-ME7OBXuEHSVYxNgA5FC:b-fcw60t) ([raw file](https://github.com/cockroachdb/cockroach/blob/a175e6898ec5445eddb5291a5c996b2e755b132a/pkg/sql/colexec/aggregate_funcs.go#L345)):*
> ```Go
> 	inputTypes []*types.T,
> ) (
> 	constructors []execinfrapb.AggregateConstructor,
> ```

I don't think we need to use named return variables here (you're initializing pretty each one minus error anyway)
___
*[pkg/sql/colexec/count_agg_tmpl.go, line 78 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-ME7oUpJ3ImDQxhAg1ar:-ME7oUpJ3ImDQxhAg1as:b2ka7hl) ([raw file](https://github.com/cockroachdb/cockroach/blob/98c19d00de9d343f981a0bf5cdc6902f43d8b703/pkg/sql/colexec/count_agg_tmpl.go#L78)):*
> ```Go
> ) {
> 	var i int
> 	// Remove unused warning.
> ```

:thinking: what's the cause of this unused warning?
___
*[pkg/sql/colexec/default_agg_tmpl.go, line 118 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-ME7X7Wc9OaDoOOXmEXG:-ME7X7Wc9OaDoOOXmEXH:b-9u07j5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a175e6898ec5445eddb5291a5c996b2e755b132a/pkg/sql/colexec/default_agg_tmpl.go#L118)):*
> ```Go
> // 'convertedTupleIdx'. These indices are the same when there is no selection
> // vector but could be different if there is one.
> func _ADD_TUPLE(
> ```

Any chance we can use @jordanlewis' new templating framework for this and other things in this file?
___
*[pkg/sql/colexec/hash_aggregator.go, line 366 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-ME7QhM4-0sTswV6X2b7:-ME7QhM4-0sTswV6X2b8:bdg52j8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a175e6898ec5445eddb5291a5c996b2e755b132a/pkg/sql/colexec/hash_aggregator.go#L366)):*
> ```Go
> 
> func (op *hashAggregator) Close(ctx context.Context) error {
> 	op.toClose.CloseAndLogOnErr(ctx, "hash-aggregator")
> ```

I think that `CloseAndLogOnErr` should be used when we cannot/don't want to return an error which I think is not the case here. We could maybe decorate the error with the fact that we're closing from the hash aggregator but I don't think we should swallow the error.
___
*[pkg/sql/colexec/utils_test.go, line 1439 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-ME7WSou7IZ3vyMYeuZJ:-ME7WSou7IZ3vyMYeuZK:bys6iw9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a175e6898ec5445eddb5291a5c996b2e755b132a/pkg/sql/colexec/utils_test.go#L1439)):*
> ```Go
> }
> 
> func (c *chunkingBatchSource) reset(context.Context) {
> ```

Add a `var _ resetter` assertion above?
___
*[pkg/sql/colexec/colbuilder/execplan.go, line 698 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-ME7WcHE2XZWK4Y6IF_z:-ME7WcHE2XZWK4Y6IFa-:b-fm7j9x) ([raw file](https://github.com/cockroachdb/cockroach/blob/a175e6898ec5445eddb5291a5c996b2e755b132a/pkg/sql/colexec/colbuilder/execplan.go#L698)):*
> ```Go
> 				)
> 			} else {
> 				evalCtx.SingleDatumAggMemAccount = streamingMemAccount
> ```

Some aggregate functions like `ARRAY_AGG` are not streaming so it is no longer true that hash = buffering, ordered = streaming. We might need to do something different here.
___
*[pkg/sql/distsql/columnar_operators_test.go, line 60 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-ME7XI-zAUcG1dh8TFMk:-ME7XI-zAUcG1dh8TFMl:bweihd7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a175e6898ec5445eddb5291a5c996b2e755b132a/pkg/sql/distsql/columnar_operators_test.go#L60)):*
> ```Go
> 	var da sqlbase.DatumAlloc
> 
> 	// We need +1 because an entry for index=6 was omitted by mistake.
> ```

:thinking: 
___
*[pkg/sql/distsql/columnar_operators_test.go, line 202 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-ME7XWB13xHFqsizjaov:-ME7XWB13xHFqsizjaow:bgz3z8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/a175e6898ec5445eddb5291a5c996b2e755b132a/pkg/sql/distsql/columnar_operators_test.go#L202)):*
> ```Go
> 						// on.
> 						continue
> 						// TODO(yuzefovich): here is a more tight condition,
> ```

Don't think so. Do we check the case where one returns an error but the other doesn't?
___
*[pkg/sql/distsql/columnar_utils_test.go, line 79 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-ME7XeuM4oT7yv_PT-Zg:-ME7XeuM4oT7yv_PT-Zh:bmt15ee) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b6141d5fd335888e42903d477cf1537702accc4/pkg/sql/distsql/columnar_utils_test.go#L79)):*
> ```Go
> 	if rng.Float64() < 0.5 {
> 		randomBatchSize := 1 + rng.Intn(3)
> 		fmt.Printf("coldata.BatchSize() is set to %d\n", randomBatchSize)
> ```

Was this not useful?
___
*[pkg/sql/execinfrapb/processors.go, line 143 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-ME7XlEmB5H2oThRnERe:-ME7XlEmB5H2oThRnERf:bp4us5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/a175e6898ec5445eddb5291a5c996b2e755b132a/pkg/sql/execinfrapb/processors.go#L143)):*
> ```Go
> // AggregateFuncToNumArguments maps aggregate functions to the number of
> // arguments they take.
> var AggregateFuncToNumArguments = map[AggregatorSpec_Func]int{
> ```

How do we keep this up to date? If this is used by only testing code, I would rather keep it close to the tests (i.e. not in `execinfrapb`)

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52174)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/colexec/aggregate_funcs.go, line 195 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-ME7N1nL5ARrH9pk31rE:-MEOFNfkBUvHll1MQ8Wq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a175e6898ec5445eddb5291a5c996b2e755b132a/pkg/sql/colexec/aggregate_funcs.go#L195)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is this over-optimization? If so, I would just use `[]int`. If not, see if `newVecToDatumConverter` can use `FastIntSet` to avoid having to convert?
</blockquote></details>

Done.
___
*[pkg/sql/colexec/aggregate_funcs.go, line 299 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-ME7Nsb43wIZiLUjRFhd:-MEOFmL37_chTxjuYKid:bp8lcdy) ([raw file](https://github.com/cockroachdb/cockroach/blob/a175e6898ec5445eddb5291a5c996b2e755b132a/pkg/sql/colexec/aggregate_funcs.go#L299)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Are closers closed on error?
</blockquote></details>

It's the same behavior as for all other `Closer`s. I've just checked `vectorizedFlowCreator.setupFlow` and no, they won't get closed. But this function will return an error only when we're trying to create an aggregate function on an unsupported type, and AFAIK we now fully support all optimized functions and have this default unoptimized one, so if an error occurs, then something has gone really wrong.
___
*[pkg/sql/colexec/aggregate_funcs.go, line 345 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-ME7OBXuEHSVYxNgA5FB:-MEOG_-oDRlKvGmd56MC:b3sno0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/a175e6898ec5445eddb5291a5c996b2e755b132a/pkg/sql/colexec/aggregate_funcs.go#L345)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I don't think we need to use named return variables here (you're initializing pretty each one minus error anyway)
</blockquote></details>

I added named return variables in order to document the code better and make it easier to use this function. Unless you have a strong objection, I'll keep it this way.
___
*[pkg/sql/colexec/count_agg_tmpl.go, line 78 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-ME7oUpJ3ImDQxhAg1ar:-MEOQAnC6LXroVfvPBko:b-kiw5xx) ([raw file](https://github.com/cockroachdb/cockroach/blob/98c19d00de9d343f981a0bf5cdc6902f43d8b703/pkg/sql/colexec/count_agg_tmpl.go#L78)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

:thinking: what's the cause of this unused warning?
</blockquote></details>

It was a case of hash aggregation when we don't need to pay attention to nulls. I updated the template to generate more efficient code for that case.
___
*[pkg/sql/colexec/default_agg_tmpl.go, line 118 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-ME7X7Wc9OaDoOOXmEXG:-MEOHdQZ0DZpKpozXN4s:b-sas1jw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a175e6898ec5445eddb5291a5c996b2e755b132a/pkg/sql/colexec/default_agg_tmpl.go#L118)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Any chance we can use @jordanlewis' new templating framework for this and other things in this file?
</blockquote></details>

I think updated execgen doesn't support all things needed for all aggregate functions, so I don't think it's worth spending time on figuring out whether we could implement this particular template in that framework (some complications are that we have `if eq "_AGGKIND" "Ordered"` condition that all aggregate functions templates have, and that condition is handled on the "meta" level). I'm pretty sure it'll be easier to update all of the files at once.
___
*[pkg/sql/colexec/hash_aggregator.go, line 366 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-ME7QhM4-0sTswV6X2b7:-MEOIezqAeEZxsvNid1C:bgezatw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a175e6898ec5445eddb5291a5c996b2e755b132a/pkg/sql/colexec/hash_aggregator.go#L366)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think that `CloseAndLogOnErr` should be used when we cannot/don't want to return an error which I think is not the case here. We could maybe decorate the error with the fact that we're closing from the hash aggregator but I don't think we should swallow the error.
</blockquote></details>

Actually, the aggregators will never return an error here because `defaultHashAggAlloc` implements `Closer` interface and in `Close` method it calls `tree.AggregateFunc.Close` method which doesn't return an error.

Left a clarifying comment.
___
*[pkg/sql/colexec/utils_test.go, line 1439 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-ME7WSou7IZ3vyMYeuZJ:-MEOJr6T2OozgiKrPX0k:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a175e6898ec5445eddb5291a5c996b2e755b132a/pkg/sql/colexec/utils_test.go#L1439)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Add a `var _ resetter` assertion above?
</blockquote></details>

Done.
___
*[pkg/sql/colexec/colbuilder/execplan.go, line 698 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-ME7WcHE2XZWK4Y6IF_z:-MEOKQbs7if0U7M4XM9m:b-g392th) ([raw file](https://github.com/cockroachdb/cockroach/blob/a175e6898ec5445eddb5291a5c996b2e755b132a/pkg/sql/colexec/colbuilder/execplan.go#L698)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Some aggregate functions like `ARRAY_AGG` are not streaming so it is no longer true that hash = buffering, ordered = streaming. We might need to do something different here.
</blockquote></details>

Such functions create and manage their own memory accounts.

`SingleDatumAggMemAccount` is shared by all aggregate functions that need to store like a single datum.
___
*[pkg/sql/distsql/columnar_operators_test.go, line 60 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-ME7XI-zAUcG1dh8TFMk:-MEOKjgH4-3OcR4Gs91t:b9hzy15) ([raw file](https://github.com/cockroachdb/cockroach/blob/a175e6898ec5445eddb5291a5c996b2e755b132a/pkg/sql/distsql/columnar_operators_test.go#L60)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

:thinking: 
</blockquote></details>

Yeah, I know. Apparently, that's an artifact that has been present since 1.0.
___
*[pkg/sql/distsql/columnar_operators_test.go, line 202 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-ME7XWB13xHFqsizjaov:-MEOKv565G8EAFGfwiZ-:bf6sdfh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a175e6898ec5445eddb5291a5c996b2e755b132a/pkg/sql/distsql/columnar_operators_test.go#L202)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Don't think so. Do we check the case where one returns an error but the other doesn't?
</blockquote></details>

Removed. Yeah, that case is checked separately and it'll have a different error message ("different number of metas returned").
___
*[pkg/sql/distsql/columnar_utils_test.go, line 79 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-ME7XeuM4oT7yv_PT-Zg:-MEOLB0g0N_reyMe0YHu:bsg2s59) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b6141d5fd335888e42903d477cf1537702accc4/pkg/sql/distsql/columnar_utils_test.go#L79)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Was this not useful?
</blockquote></details>

Yeah, I think it wasn't useful, just clogging up the output.
___
*[pkg/sql/execinfrapb/processors.go, line 143 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-ME7XlEmB5H2oThRnERe:-MEOLh0O0cq0ADy5NaPl:b-www80t) ([raw file](https://github.com/cockroachdb/cockroach/blob/a175e6898ec5445eddb5291a5c996b2e755b132a/pkg/sql/execinfrapb/processors.go#L143)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

How do we keep this up to date? If this is used by only testing code, I would rather keep it close to the tests (i.e. not in `execinfrapb`)
</blockquote></details>

I added a note to `processors_sql.proto` which should help with keeping the map up to date.

I agree, though, the map probably doesn't have to live in `execinfrapb`, moved it next to the tests. I think originally I was thinking of using the map somewhere else as well, but I don't remember what that was for.

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 10 of 15 files at r1, 52 of 52 files at r5, 8 of 8 files at r6, 18 of 18 files at r7, 26 of 26 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52174)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/aggregate_funcs.go, line 299 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-ME7Nsb43wIZiLUjRFhd:-MESl40S26aMeIwUJUOP:bszwrew) ([raw file](https://github.com/cockroachdb/cockroach/blob/a175e6898ec5445eddb5291a5c996b2e755b132a/pkg/sql/colexec/aggregate_funcs.go#L299)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

It's the same behavior as for all other `Closer`s. I've just checked `vectorizedFlowCreator.setupFlow` and no, they won't get closed. But this function will return an error only when we're trying to create an aggregate function on an unsupported type, and AFAIK we now fully support all optimized functions and have this default unoptimized one, so if an error occurs, then something has gone really wrong.
</blockquote></details>

Fair enough, but maybe we shouldn't return `toClose` if we encounter an error.
___
*[pkg/sql/colexec/hash_aggregator.go, line 366 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-ME7QhM4-0sTswV6X2b7:-MESlKdvBOGnkhxL-Snc:bdsrzlr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a175e6898ec5445eddb5291a5c996b2e755b132a/pkg/sql/colexec/hash_aggregator.go#L366)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Actually, the aggregators will never return an error here because `defaultHashAggAlloc` implements `Closer` interface and in `Close` method it calls `tree.AggregateFunc.Close` method which doesn't return an error.

Left a clarifying comment.
</blockquote></details>

Even if the current implementations don't return an error, future ones might, or the code might change to do so. I think it's more sane to propagate whatever error happens up if we can. This is partly why I didn't want to implement `CloseAndLogOnErr`, because it should be pretty rare that you want to swallow the error. I think I'm also guilty of overusing `CloseAndLogOnErr`.
___
*[pkg/sql/colexec/ordered_aggregator.go, line 339 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-MESm26L-DiQDM2Y4AHF:-MESm26L-DiQDM2Y4AHG:b3q7blj) ([raw file](https://github.com/cockroachdb/cockroach/blob/055231ae9247fa5bbe7cab8f5622e18e1b2d781a/pkg/sql/colexec/ordered_aggregator.go#L339)):*
> ```Go
> 	// tree.AggregateFunc.Close doesn't return an error, and that's why it's ok
> 	// to "swallow" errors here because they won't actually occur.
> 	a.toClose.CloseAndLogOnErr(ctx, "ordered-aggregator")
> ```

ditto. Please also add a comment on `CloseAndLogOnErr` that specifies that one should only use it if returning an error doesn't make sense.
___
*[pkg/sql/colexec/colbuilder/execplan.go, line 698 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-ME7WcHE2XZWK4Y6IF_z:-MESnNslEtVhd_RStcsJ:b-haeduu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a175e6898ec5445eddb5291a5c996b2e755b132a/pkg/sql/colexec/colbuilder/execplan.go#L698)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Such functions create and manage their own memory accounts.

`SingleDatumAggMemAccount` is shared by all aggregate functions that need to store like a single datum.
</blockquote></details>

OK. I guess my concern was re `IsStreaming` below but I defer to you

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52174)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/aggregate_funcs.go, line 299 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-ME7Nsb43wIZiLUjRFhd:-MET6BvJ50IW2L-N0zkO:b6sre0q) ([raw file](https://github.com/cockroachdb/cockroach/blob/a175e6898ec5445eddb5291a5c996b2e755b132a/pkg/sql/colexec/aggregate_funcs.go#L299)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Fair enough, but maybe we shouldn't return `toClose` if we encounter an error.
</blockquote></details>

Done. I don't think it's important though.
___
*[pkg/sql/colexec/hash_aggregator.go, line 366 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-ME7QhM4-0sTswV6X2b7:-MET79QK8kvVqjJRHjAB:bj9zl9a) ([raw file](https://github.com/cockroachdb/cockroach/blob/a175e6898ec5445eddb5291a5c996b2e755b132a/pkg/sql/colexec/hash_aggregator.go#L366)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Even if the current implementations don't return an error, future ones might, or the code might change to do so. I think it's more sane to propagate whatever error happens up if we can. This is partly why I didn't want to implement `CloseAndLogOnErr`, because it should be pretty rare that you want to swallow the error. I think I'm also guilty of overusing `CloseAndLogOnErr`.
</blockquote></details>

Ok, fair enough, updated.
___
*[pkg/sql/colexec/ordered_aggregator.go, line 339 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-MESm26L-DiQDM2Y4AHF:-MET7L1bC81M91OYXDOu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/055231ae9247fa5bbe7cab8f5622e18e1b2d781a/pkg/sql/colexec/ordered_aggregator.go#L339)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

ditto. Please also add a comment on `CloseAndLogOnErr` that specifies that one should only use it if returning an error doesn't make sense.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/colbuilder/execplan.go, line 698 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-ME7WcHE2XZWK4Y6IF_z:-MET42xO9vC-gouSvVPt:b-82o1ra) ([raw file](https://github.com/cockroachdb/cockroach/blob/a175e6898ec5445eddb5291a5c996b2e755b132a/pkg/sql/colexec/colbuilder/execplan.go#L698)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

OK. I guess my concern was re `IsStreaming` below but I defer to you
</blockquote></details>

I think still even with functions as `array_agg` ordered aggregator should be considered "streaming".

I agree that it becomes a little confusing, but I also think that it's not very important to be exactly correct here - the aggregate functions like this perform the memory accounting, so if we reach the memory limit, an error will return; however, this will also be the case for `rowexec.orderedAggregator`, so there is not much benefit in prohibiting such aggregate functions with `vectorize=201auto` (which is the only case when `IsStreaming` matters).

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 34 of 34 files at r9, 26 of 26 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52174#-:-MEXr0406GGA_1dr7AX8:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
