### PR TITLE
roachtest: test status improvements

### PR DESCRIPTION
**Pull request by andreimatei**
See individual commits.

### CODE REVIEW

**Review by stevendanna — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62972)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @jlinder, @stevendanna, and @tbg)

___
*[pkg/cmd/roachtest/cluster.go, line 1137 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62972#-MXDX1kt4dBTuWS00-Da:-MXDX1kt4dBTuWS00-Db:b-dt9t1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc2f4ce287adfba7bb463603e3fed3657790e831/pkg/cmd/roachtest/cluster.go#L1137)):*
> ```Go
> // cluster is passed to a test, at which point it's hooked up to test.Status().
> func (c *cluster) status(args ...interface{}) {
> 	if impl, ok := c.t.(*test); ok {
> ```

It almost surely doesn't matter since we know all the calling code, but you might check for `nil` impl here

**Review by stevendanna — APPROVED** [review]
Sorry, I always forget it defaults to "Publish and Block".  My comment was just a idle musing, not something that needs to change.  Thanks for cleaning this up!

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62972#-:-MXDXsCy1hkgzmNBZvc8:bgwqf5f)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @jlinder, and @tbg)

**Review by tbg — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62972)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @jlinder)

**Review by andreimatei — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62972#-:-MYIFHqU3FYD2ptT9wjN:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jlinder and @stevendanna)

___
*[pkg/cmd/roachtest/cluster.go, line 1137 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62972#-MXDX1kt4dBTuWS00-Da:-MYI9uBj5iSWxpncuCE2:bi3v83u) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc2f4ce287adfba7bb463603e3fed3657790e831/pkg/cmd/roachtest/cluster.go#L1137)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

It almost surely doesn't matter since we know all the calling code, but you might check for `nil` impl here
</blockquote></details>

Well if `c.t` is a `*test`, it's definitely not a `nil` one - I think it's more than fair to assume that.
But I took the opportunity to make `Status` part of the `testI` interface. And there's now an explicit `nil` check for `c.t`.

**Comment by tbg** [comment]
bors r+

Flake was in TestLogic, unrelated

**Pull request merged**
