### PR TITLE
Release-22.2: sql: regulate MODIFYCLUSTERSETTING with cluster setting

### PR DESCRIPTION
**Pull request by Santamaura**
This PR introduces the cluster setting
sql.auth.modify_cluster_setting_applies_to_all.enabled which
determines whether users with MODIFYCLUSTERSETTING are able to edit non sql.defaults settings.

Part of: #96172
fixes: https://github.com/cockroachdb/cockroach/issues/98155
refs https://github.com/cockroachdb/cockroach/pull/97521

Release note (sql change): add cluster setting
sql.auth.modify_cluster_setting_applies_to_all.enabled to regulate whether MODIFYCLUSTERSETTING can edit non sql.defaults settings.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
nice, glad this was an easy lift

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98234#-:-NQ1lvlp6zyR07gcjoUa:b-hob7ar)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Santamaura)

___
*[`pkg/sql/set_cluster_setting.go` line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98234#-NQ1lHhg30oN6iqsb7zg:-NQ1lHhg30oN6iqsb7zh:b-3h7td4) ([raw file](https://github.com/cockroachdb/cockroach/blob/812715199ec38cdcd24c57f58efdb7d121f9fe5a/pkg/sql/set_cluster_setting.go#L68)):*
> ```Go
> var fullModifyClusterSettingEnabled = settings.RegisterBoolSetting(
> 	settings.TenantWritable,
> 	"sql.full_modify_cluster_setting.enabled",
> ```

to make it easier to find with other authorization-related settings, can we name it
```
sql.auth.modify_cluster_setting_applies_to_all.enabled
```
___
*[`pkg/sql/set_cluster_setting.go` line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98234#-NQ1lBkp13ra_94X7K8b:-NQ1lBkp13ra_94X7K8c:b-odifvw) ([raw file](https://github.com/cockroachdb/cockroach/blob/812715199ec38cdcd24c57f58efdb7d121f9fe5a/pkg/sql/set_cluster_setting.go#L72)):*
> ```Go
> 		"or only settings with the sql.defaults prefix",
> 	true,
> )
> ```

i think this should have `WithPublic()` so that it appears in docs. (unless the product team decided that it shouldn't be documented)

**Review by Santamaura — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98234)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/set_cluster_setting.go` line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98234#-NQ1lHhg30oN6iqsb7zg:-NQ2Aljd3qDCCFLW-ybb:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/812715199ec38cdcd24c57f58efdb7d121f9fe5a/pkg/sql/set_cluster_setting.go#L68)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

to make it easier to find with other authorization-related settings, can we name it
```
sql.auth.modify_cluster_setting_applies_to_all.enabled
```
</blockquote></details>

Done
___
*[`pkg/sql/set_cluster_setting.go` line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98234#-NQ1lBkp13ra_94X7K8b:-NQ2An3h0shGbpMZlrBn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/812715199ec38cdcd24c57f58efdb7d121f9fe5a/pkg/sql/set_cluster_setting.go#L72)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think this should have `WithPublic()` so that it appears in docs. (unless the product team decided that it shouldn't be documented)
</blockquote></details>

Done.

**Comment by rafiss** [comment]
looks good!  but i think it needs a `./dev generate`

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98234)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Santamaura)

___
*[`-- commits` line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98234#-NQ6vf5zEQ4weIl97VHn):*
nit: make sure the release note has the correct name

**Review by Santamaura — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98234)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`-- commits` line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98234#-NQ6vf5zEQ4weIl97VHn):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: make sure the release note has the correct name
</blockquote></details>

Done

**Review by rafiss — APPROVED** [review]

**Pull request merged**
