### PR TITLE
sql,clusterversion: add a cluster version for partially visible indexes

### LINKED ISSUE #101976: roachtest: schemachange/mixed-versions failed
roachtest.schemachange/mixed-versions [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/9721214?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/9721214?buildTab=artifacts#/schemachange/mixed-versions) on master @ [8124bff03d073f35f4d2b6a2048c7f4417d757d9](https://github.com/cockroachdb/cockroach/commits/8124bff03d073f35f4d2b6a2048c7f4417d757d9):

```
test artifacts and logs in: /artifacts/schemachange/mixed-versions/run_1
(cluster.go:2008).Run: output in run_054205.283148785_n3_workload-run-schemac: ./workload run schemachange --verbose=1 --max-ops 100 --concurrency 5 {pgurl:1-4} returned: COMMAND_PROBLEM: ssh verbose log retained in ssh_054206.083028046_n3_workload-run-schemac.log: exit status 1
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-schema
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*schemachange/mixed-versions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-27195

### PR DESCRIPTION
**Pull request by rytaft**
Fixes #101976

Release note: None

### CODE REVIEW

**Review by fqazi — APPROVED** [review]
:lgtm: Thanks for doing this!

> Reviewed 11 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102200#-:-NTs_WweBWYqF9PBEeck:b-pt8m11)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss)

**Comment by rytaft** [comment]
TFTR! Although as-is I realize that this won't actually fix the issue with the mixed-version test. It seems quite painful to plumb the version through to where it's needed, so to stop the test from flaking I just removed the logic in operation_generator.go that creates partially visible indexes.

Let me know if you have a better idea.

**Comment by rytaft** [comment]
Going to go ahead and merge to stop the test failures, but happy to discuss ways to include this testing in `operation_generator.go` going forward

bors r+

**Comment by fqazi** [comment]
@rytaft We do have a way of getting the cluster version there with: isClusterVersionLessThan in operation_generator.go. It's okay to do that as a follow on

**Comment by rytaft** [comment]
Oh ok great! I'll do that now.

bors r-

**Comment by rytaft** [comment]
Done, PTAL. Thanks!

**Review by rytaft — COMMENTED** [review]
Friendly ping, @fqazi 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102200#-:-NTy_SvO2os5QGCH4aln:b4ncvl1)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @herkolategan, @rafiss, and @smg260)

**Review by fqazi — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 12 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102200#-:-NTy_hcx5UYiSJoUwBD-:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @rafiss, and @smg260)

**Review by rytaft — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102200#-:-NTyaJvh0eynnydQ_QIs:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @rafiss, and @smg260)

**Comment by yuzefovich** [comment]
This needs a rebase.

bors r-

**Comment by rytaft** [comment]
Thank you!

**Pull request merged**
