### PR TITLE
ccl/storageccl/engineccl: properly handle intents which straddle sstables

### LINKED ISSUE #28358: libroach: timebound iterator metadata doesn't consider intents
Note: I haven't confirmed this behavior in practice, it's currently theoretical from reading code. Holding off on the severity label until it's confirmed. The fix will need to be backported into 2.0

When computing which timestamps are present in an sstable for the time bound iterator performance optimization, all keys without a timestamp are ignored, which includes intents. This means that certain (probably unlikely) compactions will result in a situation where a time bounded iterator reading from `[t1,t2]` will miss an intent at t2.

https://github.com/cockroachdb/cockroach/blob/8b684ffc2e063451bd6d0865221989c747ae2f78/c-deps/libroach/timebound.cc#L38-L53

Backup uses timebounded iterators and does a read at a certain timestamp until all intents below that timestamp have been resolved one way or another. This bug means that backup could incorrectly proceed with an unresolved intent. If this intent is later rolled back, the backup would contain a value that was never committed.

CDC will have similar correctness issues.

Several fixes are possible with various performance tradeoffs. An partial list:
- Include intents in the time bound metadata. This requires unmarshalling every mvcc metadata proto in the sst and is probably too expensive, especially for inline values like timeseries.
- Disable time bound metadata for any sstable containing intents. This will cause the time bound iterator to always look in the file, so will be correct but a performance pessimization.
- Some combination of the two based on how many intents are in the file or where in the keyspace it is.

### PR DESCRIPTION
**Pull request by petermattis**
An intent which straddles an sstable can lead an incremental iterator to
incorrectly ignore an sstable. In order to fix this, when an intent
straddles an sstable (i.e. the metadata key is the last key in the
sstable) we need to include the intent's timestamp in the timestamp
bounds. We don't need to do this for interior intents because we'll
already be including the intent's timestamp as it is contained in the
next key following the intent. Add
`TestMVCCIncrementalIteratorIntentStraddlesSStables` which demonstrates
the problem.

Fixes #28358

Release note (bug fix): Fix a rare scenario where a backup could
incorrectly include a key for a transaction which was aborted.

### CODE REVIEW

**Comment by petermattis** [comment]
See #28358. I think this reproduces the scenario described in that bug. No comments yet, but the code is relatively straightforward. Getting this out for review as I'm going to be offline for the rest of the night.

**Review by danhhz — COMMENTED** [review]
test looks good!

**Comment by petermattis** [comment]
Implemented the suggested fix to `TimeBoundTblPropCollector` and the test now passes. I think this PR is good to go. PTAL.

**Review by danhhz — APPROVED** [review]
Thanks!

**Comment by petermattis** [comment]
bors r=danhhz

**Pull request merged**
