### PR TITLE
partitionccl,partitionccltestcases: unskip partitioning tests

### PR DESCRIPTION
**Pull request by postamar**
This commit adds a new partitionccltestcases package in which partitioning test specs are defined and leverages code generation to generate individual test cases based on those specs, to better parallelize the unit tests' execution.

Informs #49909.
Informs #49112.

Release note: None

### CODE REVIEW

**Comment by postamar** [comment]
@aadityasondhi at this point I think that what I'm hitting are errors in code owned by KV, can you take a look please?

**Comment by aadityasondhi** [comment]
I noticed that the failures had to do with timeouts. Since these tests are moving replicas around, they are expected to take a while to complete. Upon adding these additional timeouts, I see tests failing due to zone config issues. I am investigating further here: https://github.com/cockroachdb/cockroach/pull/106532.

**Comment by postamar** [comment]
Right, I traced it down to something to do with `CompareWithLocality`. This part of the code has seen recent changes (cc @wenyihu6 ) but nothing semantically different from before from what I can tell.

**Comment by aadityasondhi** [comment]
I don't think those `CompareWithLocality` error messages have anything to do with this. I added zone configs to the test cluster and those error messages are gone and the test still fails. Here is the attached stack trace:
```
        	            	Wraps: (3) attached stack trace
        	            	  -- stack trace:
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/partitionccl.verifyScansOnNode
        	            	  | 	/Users/aadityasondhi/go/src/github.com/cockroachdb/cockroach/pkg/ccl/partitionccl/partition_test.go:298
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/partitionccl.(*partitioningTest).verifyScansFn.func1
        	            	  | 	/Users/aadityasondhi/go/src/github.com/cockroachdb/cockroach/pkg/ccl/partitionccl/partition_test.go:243
        	            	  | github.com/cockroachdb/cockroach/pkg/testutils.SucceedsWithinError.func1
        	            	  | 	/Users/aadityasondhi/go/src/github.com/cockroachdb/cockroach/pkg/testutils/soon.go:75
        	            	  | github.com/cockroachdb/cockroach/pkg/util/retry.ForDuration
        	            	  | 	/Users/aadityasondhi/go/src/github.com/cockroachdb/cockroach/pkg/util/retry/retry.go:213
        	            	  | github.com/cockroachdb/cockroach/pkg/testutils.SucceedsWithinError
        	            	  | 	/Users/aadityasondhi/go/src/github.com/cockroachdb/cockroach/pkg/testutils/soon.go:81
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/partitionccl.RunRepartitioningTestCase.func1
        	            	  | 	/Users/aadityasondhi/go/src/github.com/cockroachdb/cockroach/pkg/ccl/partitionccl/partition_test.go:404
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/partitionccl.withPartitioningTestCluster
        	            	  | 	/Users/aadityasondhi/go/src/github.com/cockroachdb/cockroach/pkg/ccl/partitionccl/partition_test.go:551
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/partitionccl.RunRepartitioningTestCase
        	            	  | 	/Users/aadityasondhi/go/src/github.com/cockroachdb/cockroach/pkg/ccl/partitionccl/partition_test.go:346
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/partitionccl.RunRepartitioningTest
        	            	  | 	/Users/aadityasondhi/go/src/github.com/cockroachdb/cockroach/pkg/ccl/partitionccl/partition_test.go:411
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/partitionccl.TestRepartitioning_single_col_list_partitioning_to_single_col_range_partitioning
        	            	  | 	/Users/aadityasondhi/go/src/github.com/cockroachdb/cockroach/pkg/ccl/partitionccl/partition_generated_test.go:269
        	            	  | testing.tRunner
        	            	  | 	/opt/homebrew/Cellar/go/1.19/libexec/src/testing/testing.go:1446
        	            	  | runtime.goexit
        	            	  | 	/opt/homebrew/Cellar/go/1.19/libexec/src/runtime/asm_arm64.s:1165
```

**Comment by wenyihu6** [comment]
> Right, I traced it down to something to do with `CompareWithLocality`. This part of the code has seen recent changes (cc @wenyihu6 ) but nothing semantically different from before from what I can tell.

Yeah. This error likely isn't the root cause. `CompareWithLocality` is called for metrics updates. It just calls `log.VEventf` on unexpected cases without throwing any errors. If you add localities to `TestServerArgs`, something like the following:
```
	serverArgs := make(map[int]base.TestServerArgs)
	for i := 0; i < numNodes; i++ {
		serverArgs[i] = base.TestServerArgs{
			Locality: {Tiers: []roachpb.Tier{{Key: "region", Value: "us-east"}, {Key: "az", Value: "us-east-1"}}},,
		}
	}
```
This specific error should disappear, and the underlying issue should be popped up. Happy to hop on a call to discuss if needed.

**Comment by aadityasondhi** [comment]
Dug into the stack trace and it seems that the assertion in `verifyScanOnNode` in the partioning tests fails due to the wrong node being scanned based on the scans defined in the test specs. Not sure if @postamar you have any idea what is happening here. I will continue digging in the meantime.
**https://github.com/aadityasondhi/cockroach/blob/4508245faee16a244d185a86ef797946ebf13711/pkg/ccl/partitionccl/partition_test.go#L290**

**Comment by aadityasondhi** [comment]
I was able to fix it locally with help from @arulajmani using the following config settings:
```
		sqlDB.Exec(t, `SET CLUSTER SETTING kv.rangefeed.enabled = true`)
		sqlDB.Exec(t, `SET CLUSTER SETTING kv.closed_timestamp.target_duration = '100ms'`)
```
The problem was that the partitioning was not completed within the timeout, and it would fail. Still waiting on CI to pass on my branch, but you should be able to cherry-pick my commit to merge this PR.

On a separate note, `spanconfigsqltranslatorccl` seems to be doing a data-driven test that tests similar things (setting partitions and then verifying that they were applied). It might be useful to implement here as well for improved maintainability if it makes sense.

**Comment by arulajmani** [comment]
I'll plus one what @aadityasondhi said. The data-driven tests for the SQLTranslator are pretty much testing the same thing as this test, albeit more directly. They also don't have to depend on the underlying cluster state to conform to the partitioning, which means the tests are quicker to run. 

We already have integration tests that test zone/span configs end to end. Maybe a more direct test for partitioning, by rewriting all these tests as SQL Translator datadriven tests, will help maintainability going forward?

**Comment by postamar** [comment]
Ok this is all wonderful news. Thanks everyone. Data-driven tests are the way to go.

**Pull request closed without merging**
