### PR TITLE
sql: always use a fresh transaction to update create stats job progress

### LINKED ISSUE #90841: CREATE STATISTICS stuck in jobs.(*Registry).LoadJob
roachtest.import-cancellation [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/7182945?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/7182945?buildTab=artifacts#/import-cancellation) on release-22.2 @ [f4fcfbc486a884d52532f1f8eacf8e0ad3d9749c](https://github.com/cockroachdb/cockroach/commits/f4fcfbc486a884d52532f1f8eacf8e0ad3d9749c):

```
test artifacts and logs in: /artifacts/import-cancellation/run_1
	import_cancellation.go:311,import_cancellation.go:138,monitor.go:105,errgroup.go:74: dial tcp 34.148.19.194:26257: connect: connection refused

	import_cancellation.go:151,import_cancellation.go:38,test_runner.go:930: context canceled

	test_runner.go:1061,test_runner.go:960: test timed out (4h0m0s)
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=32</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/storage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*import-cancellation.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-20968

### PR DESCRIPTION
**Pull request by michae2**
A roachtest recently found a deadlock in the create stats job, with a stack like this:

```
...
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).LoadJob
        github.com/cockroachdb/cockroach/pkg/jobs/registry.go:618
github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*sampleAggregator).mainLoop
        github.com/cockroachdb/cockroach/pkg/sql/rowexec/sample_aggregator.go:219
...
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).planAndRunCreateStats
        github.com/cockroachdb/cockroach/pkg/sql/distsql_plan_stats.go:310
github.com/cockroachdb/cockroach/pkg/sql.(*createStatsResumer).Resume.func1
        github.com/cockroachdb/cockroach/pkg/sql/create_stats.go:620
...
github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn
        github.com/cockroachdb/cockroach/pkg/kv/db.go:916
github.com/cockroachdb/cockroach/pkg/sql.(*createStatsResumer).Resume
        github.com/cockroachdb/cockroach/pkg/sql/create_stats.go:602
...
```

`LoadJob` opens a new inner transaction to read a row from system.jobs. But in this case the outer transaction opened by `Resume` had previously updated that row of system.jobs and had not yet committed. The `LoadJob` inner transaction was stuck waiting for the outer transaction to commit.

We believe `FractionProgressed` was where the outer transaction wrote to system.jobs, and then a retry of the closure (without aborting the transaction) called `planAndRunCreateStats` again. (The need for a non-aborting retry makes this deadlock very rare.)

This patch changes the call to `FractionProgressed` to always use a fresh transaction instead of the current transaction. This has three benefits: (1) it eliminates this deadlock, (2) it allows us to update job progress even if the current transaction has been aborted for some reason, (3) it keeps the current transaction read-only.

Fixes: #90841

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: good find!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90883#-:-NFjedVR9w-hPseklnEM:bbxruok)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @yuzefovich)

**Comment by michae2** [comment]
We saw this on release-22.2, and the code is the same in 21.2, so I've added backport labels.

The two failures are https://github.com/cockroachdb/cockroach/issues/90879 and https://github.com/cockroachdb/cockroach/issues/90965 which are unrelated.

TFYR!

bors r=rytaft

**Comment by rytaft** [comment]
should we also backport to 22.1?

**Comment by michae2** [comment]
Oh! Yes. 🤦

blathers backport 22.1

**Pull request merged**
