### PR TITLE
changefeedccl: use ScanRequest instead of ExportRequest during backfills

### PR DESCRIPTION
**Pull request by ajwerner**
This PR is motivated by the desire to get the memory usage of CDC under
control in the presense of much larger ranges. Currently when a changefeed
decides it needs to do a backfill, it breaks the spans up along range
boundaries and then fetches the data (with some parallelism) for the backfill.

The memory overhead was somewhat bounded by the range size. If we want to make
the range size dramatically larger, the memory usage would become a function of
that new, much larger range size.

Fortunately, we don't have much need for these `ExportRequest`s any more.
Another fascinating revelation of late is that the `ScanResponse` does indeed
include MVCC timestamps (not the we necessarily needed them but it's a good
idea to keep them for compatibility).

The `ScanRequest` permits currently a limit on `NumRows` which this commit
utilized. I wanted to get this change typed in anticipation of #44341 which
will provide a limit on `NumBytes`.

I retained the existing parallelism as ScanRequests with limits are not
parallel.

I would like to do some benchmarking but I feel pretty okay about the
testing we have in place already. @danhhz what do you want to see here?

Relates to #39717.

Release note: None.

### CODE REVIEW

**Review by danhhz — COMMENTED** [review]
:lgtm: if the roachtests are happy, i'm happy. cdc/initial-scan is designed to stress exactly this, i'd be curious how long it takes before and after this change

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44663#-:-M-Fj-sWD9HIwJsJfEwO:b-y4uhf5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/ccl/changefeedccl/poller.go, line 453 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44663#-M-FhKk0EFPk87ar2y1B:-M-FhKk0EFPk87ar2y1C:b-qtkx0z) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd5f1c09c07ba834184a671208ec00d27889a80d/pkg/ccl/changefeedccl/poller.go#L453)):*
> ```Go
> 	ctx context.Context, span roachpb.Span, ts hlc.Timestamp, withDiff bool,
> ) error {
> 	txn := p.db.NewTxn(ctx, "poller backfill")
> ```

nit: i'd think "changefeed backfill" would be more evocative
___
*[pkg/ccl/changefeedccl/poller.go, line 478 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44663#-M-FioPy1A0cWMTaBxRg:-M-FioPy1A0cWMTaBxRh:b-z9xrnl) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd5f1c09c07ba834184a671208ec00d27889a80d/pkg/ccl/changefeedccl/poller.go#L478)):*
> ```Go
> 		afterScan := timeutil.Now()
> 		res := b.RawResponse().Responses[0].GetScan()
> 		for _, br := range res.BatchResponses {
> ```

i'd still keep the decode+AddKV part as a separate method for readability but ymmv
___
*[pkg/ccl/changefeedccl/poller.go, line 488 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44663#-M-FiT3r2uHQNwTuKBXv:-M-FiT3r2uHQNwTuKBXw:b-35fxvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd5f1c09c07ba834184a671208ec00d27889a80d/pkg/ccl/changefeedccl/poller.go#L488)):*
> ```Go
> 				var prevVal roachpb.Value
> 				if withDiff {
> 					prevVal = kv.Value
> ```

looks like you lost a (somewhat important) comment here

**Review by ajwerner — COMMENTED** [review]
I ran it with the 8M row limit and got roughly the same as last night. Running it again. I'm 99% sure the sink is the bottleneck. I accidentally for one run ran it where it didn't call slurp and the whole scan took 6s. I think it's all sort of in the noise. It's possible that the scan at `1<<18` rows is a hair slower but it doesn't seem statistically significant. Anyway, I intend to make it use something like 16MB when we get the size limit at which point it should be better. 

I think I'd like to merge this given it doesn't seem egregiously worse. 

export:  8m12.375818885s
export:  9m43.823838146s
export: 9m17.891210167s
export:  8m34.513046008s
8<<20: 8m37.686091157s
1<<20: 9m3.046564286s
1<<18: 8m28.071550859s
1<<18: 9m49.689186991s
1<<18:  11m20.302953236s

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44663#-:-M-GbTi14mAhJPIpZO0h:b2jd1yr)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/ccl/changefeedccl/poller.go, line 453 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44663#-M-FhKk0EFPk87ar2y1B:-M-GW5Ie31GDMkzLxdrM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd5f1c09c07ba834184a671208ec00d27889a80d/pkg/ccl/changefeedccl/poller.go#L453)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: i'd think "changefeed backfill" would be more evocative
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/poller.go, line 478 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44663#-M-FioPy1A0cWMTaBxRg:-M-GWO1y1ZeqrotvRGoK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd5f1c09c07ba834184a671208ec00d27889a80d/pkg/ccl/changefeedccl/poller.go#L478)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

i'd still keep the decode+AddKV part as a separate method for readability but ymmv
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/poller.go, line 488 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44663#-M-FiT3r2uHQNwTuKBXv:-M-GWOkgBWTPtcOoR6fD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd5f1c09c07ba834184a671208ec00d27889a80d/pkg/ccl/changefeedccl/poller.go#L488)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

looks like you lost a (somewhat important) comment here
</blockquote></details>

Done.

**Comment by danhhz** [comment]
As long as the performance is in the same ballpark, it's fine by me. Those numbers look okay, merge away!

**Comment by ajwerner** [comment]
Flaked on https://github.com/cockroachdb/cockroach/issues/41941

**Comment by ajwerner** [comment]
TFTR! 

bors r=danhhz

**Pull request merged**
