### PR TITLE
sql: clean up distsql version history

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change moves the distsql version constants to a separate file, improves
the comments, and moves the version history into a comment in the same file.
Having to change a separate text file is awkward.

Release justification: no code change.

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53770)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/execinfra/version.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53770#-MG9qkTyDamQIWq7pPbE:-MG9qkTyDamQIWq7pPbF:bwz2416) ([raw file](https://github.com/cockroachdb/cockroach/blob/6de9000155e2aac83fdedc4c35f7e192fe2c9b6c/pkg/sql/execinfra/version.go#L49)):*
> ```Go
> /*
> 
> **  VERSION HISTORY **
> ```

Should we now remove `execinfra/version_history.txt` as well?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53770)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/execinfra/version.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53770#-MG9qkTyDamQIWq7pPbE:-MG9z-MGCOq0Qf_tioCw:bdicjq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6de9000155e2aac83fdedc4c35f7e192fe2c9b6c/pkg/sql/execinfra/version.go#L49)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Should we now remove `execinfra/version_history.txt` as well?
</blockquote></details>

Ha, can't believe I forgot to do that. Done.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53770#-:-MGA-6vHDdWw1_wSE6bB:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
