### PR TITLE
sql/*: remove MakeTableName (without schema) function

### PR DESCRIPTION
**Pull request by rafiss**
This made it very easy to forget to account for user-defined schemas.
Removing the function should prevent a big class of bugs.

This is broken up into 2 commits. The first fixes some cases that appeared
to me as if they'd benefit from looking up the schema name, and is intended
for a backport back to 20.2. The second commit is a refactor that removes the
non-schema MakeTableName function and probably doesn't need to be backported.

In addition to the release note below, this also fixes the error message
that would appear when trying to drop a role that owns a table in a
user-defined schema.

Release note (bug fix): Using EXPLAIN (OPT, ENV) on a query that
references a table in a user-defined schema would fail previously. This
is now fixed.

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
`schemaexpr`, `opt_catalog.go`, and `opt` changes :LGTM: (except `execbuilder.Builder.applySaveTable` changes - I'm unfamiliar with what this does and not sure if it is safe to save tables to the `public` schema)

> Reviewed 1 of 7 files at r1, 8 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61752#-:-MVOWk2t86P5lDu0MuNr:buwg1r4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @miretskiy)

**Review by solongordon — APPROVED** [review]
:lgtm: in general, though in the case of the bug fixes I'd love to see updated tests.

> Reviewed 7 of 7 files at r1, 7 of 17 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61752#-:-MVXJEF17fkCGbJqUQiY:b6e22k6)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @miretskiy and @rafiss)

___
*[pkg/sql/drop_role.go, line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61752#-MVXIr8T6DApxRyZFS5l:-MVXIr8T6DApxRyZFS5m:bsjbvtd) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ca11cbc51ff4531a14d531f5d93a7c9e28c8bcb/pkg/sql/drop_role.go#L184)):*
> ```Go
> 				parentName := lCtx.getDatabaseName(table)
> 				schemaName := lCtx.getSchemaName(table)
> 				tn := tree.MakeTableNameWithSchema(tree.Name(parentName), tree.Name(schemaName), tree.Name(table.GetName()))
> ```

Could you add a regression test for this (or alter whatever existing test there is to include user-defined schemas)?
___
*[pkg/sql/opt_catalog.go, line 369 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61752#-MVXJ50h56E7g9cBOP-N:-MVXJ50h56E7g9cBOP-O:b-ka49my) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ca11cbc51ff4531a14d531f5d93a7c9e28c8bcb/pkg/sql/opt_catalog.go#L369)):*
> ```Go
> 			scName,
> 			tree.Name(desc.GetName())),
> 		nil
> ```

Ideally I'd like to know what this change fixes (EXPLAIN plans?) and add a regression test.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61752)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @miretskiy and @solongordon)

___
*[pkg/sql/drop_role.go, line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61752#-MVXIr8T6DApxRyZFS5l:-MVYRDT77TCyH8WU9zGo:bhnwd5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ca11cbc51ff4531a14d531f5d93a7c9e28c8bcb/pkg/sql/drop_role.go#L184)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Could you add a regression test for this (or alter whatever existing test there is to include user-defined schemas)?
</blockquote></details>

added a test
___
*[pkg/sql/opt_catalog.go, line 369 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61752#-MVXJ50h56E7g9cBOP-N:-MVYR9Fj9MfxjqGp0SXB:b8o6qff) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ca11cbc51ff4531a14d531f5d93a7c9e28c8bcb/pkg/sql/opt_catalog.go#L369)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Ideally I'd like to know what this change fixes (EXPLAIN plans?) and add a regression test.
</blockquote></details>

it affected EXPLAIN (OPT, ENV). added a test.

**Comment by rafiss** [comment]
thanks for the reviews!!

bors r=solongordon

**Pull request merged**
