### PR TITLE
ui: fix a graph title and tooltip

### PR DESCRIPTION
**Pull request by BramGruneir**

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ui/src/containers/nodeGraphs.tsx, line 529 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15720#-KjPgCNW2AjHcN_hiwkX:-KjPgCNW2AjHcN_hiwkY:byxc6c3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c759fcecbb293b91d4b9888aab3363ef2555022/pkg/ui/src/containers/nodeGraphs.tsx#L529)):*
> ```XML
>           </LineGraph>
> 
>           <LineGraph title="Lease Holders per Store"
> ```

"holders"? I don't think Holder is a proper noun.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15720#-:-KjPgGBz2u5scSbEmK3D:bnfp4nl)*

**Comment by BramGruneir** [comment]
@jseldess  Any thought on what the correct language would be here?

Perhaps we should do an audit on the full Admin UI soon.

**Comment by jseldess** [comment]
@BramGruneir, should we close this old PR? So much has changed in the meantime...

**Comment by BramGruneir** [comment]
Please do!  Wow this is old.

**Pull request closed without merging**
