### PR TITLE
sql: reuse the spans in the txnKVFetcher

### PR DESCRIPTION
**Pull request by yuzefovich**
**sql: reuse the spans in the txnKVFetcher**

Previously, we would always make a copy of the spans to scan in the
`txnKVFetcher` because we might be modifying them. However, most callers
don't care about that - I think only the table reader and ColBatchScan
do need keep the copy of the original spans for the purposes of the
misplanned ranges. This commit takes advantage of this observation and
removes the copy in several cases (most notably for the lookup and index
joins).

Notable change is that now the `txnKVFetcher` is the only component
responsible for the memory accounting of the spans. This simplifies the
memory story but also seems like a good decision because
- `txnKVFetcher` is the component that might be holding onto the spans
slice for the longest amount of time
- it is also the place where we'd know about any modifications, so it
can update the memory accounting accordingly
- in case of `joinReader` - `StartScan` is called multiple times, we do
not close the fetcher until we're ready to perform the next scan, so the
old fetcher is holding onto and is accounting for the old spans until we
call `StartScan` again. Here `generateSpans` is very quick, so if
consequent scans had much more heavy-weight spans, we'll account for the
update very soon (when initializing the new fetcher).
- in case of the vectorized index joiner - here we're performing the
memory accounting as we are building the spans to scan, one batch at a
time. I think it makes sense to do so. Now, during the span generation
the spanAssembler is responsible for the memory accounting, but once
`GetSpans` is called, the ownership is passed to the `txnKVFetcher`.
Once the `cFetcher` emits the first zero batch for the current set of
spans, it closed the txnKVFetcher, and the vectorized index joiner
notifies the ColSpanAssembler to account for the spans. This makes sure
that we don't double count for the memory of `spans`, yet it is always
accounted for.

Addresses: #64906.

Release note: None

**rowexec: reuse the same spans slice in the inverted joiner**

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
First commit is #70608.

**Comment by yuzefovich** [comment]
Rebased on top of master. RFAL.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70622)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @yuzefovich)

___
*[pkg/sql/colfetcher/index_join.go, line 174 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70622#-MkjV0BDEyyNXG2sKeSp:-MkjV0BDEyyNXG2sKeSq:b-2b100f) ([raw file](https://github.com/cockroachdb/cockroach/blob/74f2ae9da86cf638e878e41758c6661eb98946f1/pkg/sql/colfetcher/index_join.go#L174)):*
> ```Go
> 			// about the modification here, and the double counting of the
> 			// memory seems acceptable given that we tend to not account for all
> 			// things anyway.
> ```

I think this is somewhat sketchy for 2 reasons - 1 is that double counting the span memory itself is kind of sad but I can live with that. 2 is how do we un-account for the spans later? If the spans slice is modified, how do we know how much to subtract from our account in the outer operators? Or do we just zero them? Just seems bug prone, and tracking down the memory account errors is always hard...

Can we not release our accounting on the spans slice from the outer processors and nil our reference?

Also, I guess I'm also confused about how this is saving us in TPCH overload - we're allocating 2x less for lookup join, but we're also accounting for 2x more - what would happen if we just allocated 2x less but kept the accounting accurate? Are we only passing TPCH better because we're lying in the opposite direction about the accounting now?
___
*[pkg/sql/row/kv_batch_fetcher.go, line 329 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70622#-MkjTxdVChN0q--1cya8:-MkjTxdVChN0q--1cya9:bv1x6n0) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb4e180d0bc0f9c8f91de697bac9c70b7ab6410d/pkg/sql/row/kv_batch_fetcher.go#L329)):*
> ```Go
> 	}
> 
> 	f.spans = spans
> ```

I think this deserves a comment to explain the non-deepcopy, it will definitely require some thought later when someone stumbles across this because it's quite far away from the new comment you added about ownership.
___
*[pkg/sql/row/kv_batch_fetcher.go, line 332 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70622#-MkjUJpl8myEORrcM8kM:-MkjUJpl8myEORrcM8kN:bxr59pf) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb4e180d0bc0f9c8f91de697bac9c70b7ab6410d/pkg/sql/row/kv_batch_fetcher.go#L332)):*
> ```Go
> 	if reverse {
> 		// Reverse scans receive the spans in decreasing order.
> 		i, j := 0, len(spans)-1
> ```

I find this more confusing than the original way to phrase it... why the change?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70622)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @mgartner, and @michae2)

___
*[pkg/sql/colfetcher/index_join.go, line 174 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70622#-MkjV0BDEyyNXG2sKeSp:-MkmWAO16NAJJOXBCeS0:b-8wjy20) ([raw file](https://github.com/cockroachdb/cockroach/blob/74f2ae9da86cf638e878e41758c6661eb98946f1/pkg/sql/colfetcher/index_join.go#L174)):*
That's a fair point.

When I originally wrote this, I was looking only at the vectorized index join where after `GetSpans` is called, we would only account for the `spans` slice itself, ignoring the keys, and I thought it was ok to double count the slice itself. Also the `txnKVFetcher` cannot modify the capacity of the spans slice. But I agree with you that the memory accounting of the joinReader would get out of sync if the `txnKVFetcher` modifies the spans.

I rewrote the code to have precise memory accounting. We now rely only on the `txnKVFetcher` to account for the spans slice which simplifies the accounting elsewhere. I think this is a good decision because:
1. `txnKVFetcher` is the component that might be holding onto the spans slice for the longest amount of time
2. it is also the place where we'd know about any modifications, so it can update the memory accounting accordingly
3. -  in case of `joinReader` - `StartScan` is called multiple times, we do not close the fetcher until we're ready to perform the next scan, so the old fetcher is holding onto and is accounting for the old spans until we call `StartScan` again. Here `generateSpans` is very quick, so if consequent scans had much more heavy-weight spans, we'll account for the update very soon (when initializing the new fetcher).
    - in case of the vectorized index joiner - here we're performing the memory accounting as we go, one batch at a time. I think it makes sense to do so. Now during the span generation the spanAssembler is responsible for the memory accounting, but once `GetSpans` is called, the ownership is passed to the `txnKVFetcher`. One detail is that the vectorized index join will now have to eagerly close the old fetcher so that we no longer double count for the memory of `spans` while new spans are being generated/accumulated.

Overall, getting the memory accounting here correct is quite tricky indeed - this PR is inspired by the desire to reduce the memory footprint for stability and performance reasons. To get that we now write into the same `spans` slice in two places - where we generate the spans first, but also in the `txnKVFetcher` in case of the resume spans. I believe the latter is the component that should be responsible for precise memory tracking; however, this forces us to teach the former (`joinReader`, `ColIndexJoin`, etc) about how to cooperate with the `txnKVFetcher` to not double count things.

Curious about your thoughts on this approach.

> Also, I guess I'm also confused about how this is saving us in TPCH overload - we're allocating 2x less for lookup join, but we're also accounting for 2x more - what would happen if we just allocated 2x less but kept the accounting accurate? Are we only passing TPCH better because we're lying in the opposite direction about the accounting now?

I think your concern (that the results I saw could be misleading/incorrect) has merit, but I feel like the final results mostly will end up about the same :crossed_fingers: 
___
*[pkg/sql/row/kv_batch_fetcher.go, line 329 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70622#-MkjTxdVChN0q--1cya8:-MkmVaj57XFVmXNOV9EQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb4e180d0bc0f9c8f91de697bac9c70b7ab6410d/pkg/sql/row/kv_batch_fetcher.go#L329)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think this deserves a comment to explain the non-deepcopy, it will definitely require some thought later when someone stumbles across this because it's quite far away from the new comment you added about ownership.
</blockquote></details>

Done.
___
*[pkg/sql/row/kv_batch_fetcher.go, line 332 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70622#-MkjUJpl8myEORrcM8kM:-MkmVbEW-JRWPeyiDtNR:bg12o5u) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb4e180d0bc0f9c8f91de697bac9c70b7ab6410d/pkg/sql/row/kv_batch_fetcher.go#L332)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I find this more confusing than the original way to phrase it... why the change?
</blockquote></details>

Well, previously we had two separate memory chunks backing `f.spans` and `spans`, so we could iterate over the latter and update the former one position at a time. Now we have to reverse the slice in place, so if we were to keep the original approach, we would corrupt the contents. For example, if we had `spans = {0, 1, 2, 3, 4, 5}`, with the previous code we would get `{0, 1, 2, 2, 1, 0}`.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70622)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @mgartner, and @michae2)

___
*[pkg/sql/row/kv_batch_fetcher.go, line 332 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70622#-MkjUJpl8myEORrcM8kM:-MkmelnwEa0p-DB73k_t:b-4kozwq) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb4e180d0bc0f9c8f91de697bac9c70b7ab6410d/pkg/sql/row/kv_batch_fetcher.go#L332)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Well, previously we had to separate memory chunks backing `f.spans` and `spans`, so we could iterate over the latter and update the former one position at a time. Now we have to reverse the slice in place, so if we were to keep the original approach, we would corrupt the contents. For example, if we had `spans = {0, 1, 2, 3, 4, 5}`, with the previous code we would get `{0, 1, 2, 2, 1, 0}`.
</blockquote></details>

*we had two separate memory ...

**Comment by yuzefovich** [comment]
I have some preliminary results on 21.2 branch indicating that a lot of improvement comes from the already merged #70608 and #70729, even without this PR. However, there appears to be a regression in the concurrency on the master branch, so I'm a bit side-tracked.

**Review by rytaft — COMMENTED** [review]
Tricky stuff! Thanks for thinking through this.

> Reviewed 3 of 7 files at r2, 14 of 14 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70622#-:-MlQMshA6POLISm90zK5:b2qa99x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @mgartner, @michae2, and @yuzefovich)

___
*[pkg/sql/colexec/colexecspan/span_assembler_tmpl.go, line 92 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/70622#-MlQAxRGAYvoiTnqR9MQ:-MlQAxRGAYvoiTnqR9MR:b-5sqskf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b228cb48c1428781d5fe312f27f423ad68520db9/pkg/sql/colexec/colexecspan/span_assembler_tmpl.go#L92)):*
> ```Go
> 	// later be returned by GetSpans. Spans are generated only for rows in the
> 	// range [startIdx, endIdx). If startIdx >= endIdx, ConsumeBatch will perform
> 	// no work. The newly accumulated spans are accounted for.
> ```

nit: The memory of the newly accumulated...
___
*[pkg/sql/colexec/colexecspan/span_assembler_tmpl.go, line 101 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/70622#-MlQAsJO4vbdQicRrGW6:-MlQAsJPAaUbLbtd5vV5:b-mglqn3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b228cb48c1428781d5fe312f27f423ad68520db9/pkg/sql/colexec/colexecspan/span_assembler_tmpl.go#L101)):*
> ```Go
> 	// will return an empty slice if it is called before ConsumeBatch.
> 	//
> 	// The returned object is no longer accounted for by the ColSpanAssembler,
> ```

nit: maybe say "The memory of the returned object..."
___
*[pkg/sql/colexec/colexecspan/span_assembler_tmpl.go, line 201 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/70622#-MlQCi7v0yipGASfN0a_:-MlQBfTR-9L39B7Pp0FM:b-ll2ih0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b228cb48c1428781d5fe312f27f423ad68520db9/pkg/sql/colexec/colexecspan/span_assembler_tmpl.go#L201)):*
> ```Go
> 	b.spansBytes = 0
> 	spans := b.spans
> 	b.spans = b.spans[:0]
> ```

This seems possibly sketchy - how do we know when we can reuse this slice?
___
*[pkg/sql/colfetcher/colbatch_scan.go, line 265 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70622#-MlQKSz_-rujb8hUacvQ:-MlQKSz_-rujb8hUacvR:b-wzp3l8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b811e4edb8c4fda676844098bbf29a9b2f15f1ba/pkg/sql/colfetcher/colbatch_scan.go#L265)):*
> ```Go
> 		// info.
> 		allocator.AdjustMemoryUsage(s.Spans.MemUsage())
> 		s.MakeSpansCopy()
> ```

I think this would be simpler if you performed the copy right before you needed to use the copy (see my comments for `SpansWithCopy`)
___
*[pkg/sql/execinfra/readerbase.go, line 99 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70622#-MlQKhb26b1lc04ClPNs:-MlQKhb26b1lc04ClPNt:bdudkht) ([raw file](https://github.com/cockroachdb/cockroach/blob/b811e4edb8c4fda676844098bbf29a9b2f15f1ba/pkg/sql/execinfra/readerbase.go#L99)):*
> ```Go
> }
> 
> // SpansWithCopy tracks a set of spans (which can be modified) along with the
> ```

Since you're going to the trouble of making a struct for this, I think you could have it do more work for you. You could keep track of whether the spans are already copied with a boolean, and then have a `GetCopy()` function which makes the copy if needed and otherwise just returns the copy directly. You could also have it do the memory accounting for you.
___
*[pkg/sql/execinfra/readerbase.go, line 126 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70622#-MlQI7EP-5VCxYUm279J:-MlQI7EP-5VCxYUm279K:b-gwwgcl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b811e4edb8c4fda676844098bbf29a9b2f15f1ba/pkg/sql/execinfra/readerbase.go#L126)):*
> ```Go
> 	}
> 	s.Spans = s.Spans[:0]
> 	s.Spans = s.SpansCopy[:0]
> ```

I think you meant `s.SpansCopy = s.SpansCopy[:0]` here
___
*[pkg/sql/row/kv_batch_fetcher.go, line 69 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70622#-MlQMOTi0bgWcBl5otoC:-MlQMOTjEsw8PMWt13pO:b4zi2kq) ([raw file](https://github.com/cockroachdb/cockroach/blob/759c9786a39b9384e6464eab185f281d5c76736d/pkg/sql/row/kv_batch_fetcher.go#L69)):*
> ```Go
> 	// spansScratch is the largest allocated slice of roachpb.Spans that we need
> 	// to hold on to since we're slicing off spans in nextBatch(). Any resume
> 	// spans are copied into this slice when processing each response.
> ```

did you intend to remove this comment? Does it need a different comment now?
___
*[pkg/sql/rowexec/inverted_joiner.go, line 508 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70622#-MlQLPEXAROZ7M-1qR5K:-MlQLPEY1pgQfDtJ4MFz:b-g07ujt) ([raw file](https://github.com/cockroachdb/cockroach/blob/b811e4edb8c4fda676844098bbf29a9b2f15f1ba/pkg/sql/rowexec/inverted_joiner.go#L508)):*
> ```Go
> 	}
> 
> 	// Deeply reset the index spans.
> ```

is the fetcher done with the spans by now?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70622)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @mgartner, @michae2, @rytaft, and @yuzefovich)

___
*[pkg/sql/colexec/colexecspan/span_assembler_tmpl.go, line 201 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/70622#-MlQCi7v0yipGASfN0a_:-MlQYb4i-zfjBp4uFLws:b-9mwovg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b228cb48c1428781d5fe312f27f423ad68520db9/pkg/sql/colexec/colexecspan/span_assembler_tmpl.go#L201)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This seems possibly sketchy - how do we know when we can reuse this slice?
</blockquote></details>

I extended the contract of `ConsumeBatch` to spell more things out.

The idea is that we don't intertwine `ConsumeBatch` (where we're accumulating spans), `GetSpans` (where we return them), and fetching the data based on the spans, so it is ok to reuse the same slice.
___
*[pkg/sql/execinfra/readerbase.go, line 99 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70622#-MlQKhb26b1lc04ClPNs:-MlQ_AMJ2DOXVq7xko9u:b-n4j0xl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b811e4edb8c4fda676844098bbf29a9b2f15f1ba/pkg/sql/execinfra/readerbase.go#L99)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Since you're going to the trouble of making a struct for this, I think you could have it do more work for you. You could keep track of whether the spans are already copied with a boolean, and then have a `GetCopy()` function which makes the copy if needed and otherwise just returns the copy directly. You could also have it do the memory accounting for you.
</blockquote></details>

Hm, I'm not sure I fully understand your idea.

Currently, `SpansWithCopy` is used as follows:
- we set `Spans` in the constructor for all operators/processors - this field is passed to the kv fetcher and will be modified internally
- `SpansCopy` is only populated in case of TableReaders/ColBatchScans when they don't ignore misplanned ranges.

A crucial point is that `SpansCopy` is only used during the metadata generation step which is after all the reads have been performed. So if we try to make the copy at that point, `Spans` field will have already been modified, so we have to make the copy before we pass `Spans` to the kv fetcher.
___
*[pkg/sql/execinfra/readerbase.go, line 126 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70622#-MlQI7EP-5VCxYUm279J:-MlQZz0J9M7PCnCAtuVK:b-m16fax) ([raw file](https://github.com/cockroachdb/cockroach/blob/b811e4edb8c4fda676844098bbf29a9b2f15f1ba/pkg/sql/execinfra/readerbase.go#L126)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think you meant `s.SpansCopy = s.SpansCopy[:0]` here
</blockquote></details>

Nice catch, thanks!
___
*[pkg/sql/row/kv_batch_fetcher.go, line 69 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70622#-MlQMOTi0bgWcBl5otoC:-MlQaT3SBoIk1hXmzoPV:b-evo5jr) ([raw file](https://github.com/cockroachdb/cockroach/blob/759c9786a39b9384e6464eab185f281d5c76736d/pkg/sql/row/kv_batch_fetcher.go#L69)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

did you intend to remove this comment? Does it need a different comment now?
</blockquote></details>

Good point, added the adjusted comment back.
___
*[pkg/sql/rowexec/inverted_joiner.go, line 508 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70622#-MlQLPEXAROZ7M-1qR5K:-MlQSrHRCcV1LFTm6GPf:b-ax78jc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b811e4edb8c4fda676844098bbf29a9b2f15f1ba/pkg/sql/rowexec/inverted_joiner.go#L508)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

is the fetcher done with the spans by now?
</blockquote></details>

That's a good catch - no, it's not yet done. The spans might be used in case of GetRequests, and it's possible that we never construct GetRequests based on the inverted spans, still the code wasn't right. I have thought a bit more about this, and we don't actually need to perform the deep reset ourselves since this is done in `txnKVFetcher.nextBatch`.

**Review by yuzefovich — COMMENTED** [review]
Rebased on top of #71321. I also refactored the way `spans` are accounted for in case of the vectorized index joiner so that someone is always accounting for the slice.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70622#-:-MlY0su63C9eewnGrCUO:b-sveaws)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @mgartner, @michae2, @rytaft, and @yuzefovich)

**Comment by yuzefovich** [comment]
@jordanlewis @rytaft friendly ping. I think it's in a good shape now.

**Review by rytaft — APPROVED** [review]
:lgtm: Sorry for the delay!

> Reviewed 2 of 8 files at r8, 3 of 8 files at r11, 7 of 7 files at r15, 4 of 4 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70622#-:-Mm5cbaL3DgerFiOZsYr:b-8yidu2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @mgartner, and @michae2)

___
*[pkg/sql/execinfra/readerbase.go, line 99 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70622#-MlQKhb26b1lc04ClPNs:-Mm5bn7sDLPDjFIq4xxJ:b-yksexc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b811e4edb8c4fda676844098bbf29a9b2f15f1ba/pkg/sql/execinfra/readerbase.go#L99)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Hm, I'm not sure I fully understand your idea.

Currently, `SpansWithCopy` is used as follows:
- we set `Spans` in the constructor for all operators/processors - this field is passed to the kv fetcher and will be modified internally
- `SpansCopy` is only populated in case of TableReaders/ColBatchScans when they don't ignore misplanned ranges.

A crucial point is that `SpansCopy` is only used during the metadata generation step which is after all the reads have been performed. So if we try to make the copy at that point, `Spans` field will have already been modified, so we have to make the copy before we pass `Spans` to the kv fetcher.
</blockquote></details>

Oh ok -- I thought Spans wasn't going to be changed -- I guess I misunderstood

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70622#-:-Mm5d9d0-Pm5pio8mALf:b-tlx7ko)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @mgartner, and @michae2)

**Pull request merged**
