### PR TITLE
opt: show paired joiner continuation column

### PR DESCRIPTION
**Pull request by RaduBerinde**
Release justification: bug fixes and low-risk updates to new
functionality.

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61153#-:-MUQo3uW9PFNNuuw6yNU:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/memo/expr_format.go, line 484 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61153#-MUQnnkKEpmJbXTn1iDh:-MUQnnkKEpmJbXTn1iDi:b-xe5v9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cf18dde90252315157ff2ac9640026eaab2a1b3/pkg/sql/opt/memo/expr_format.go#L484)):*
> ```Go
> 			tp.Childf("prefix key columns: %v = %v", t.PrefixKeyCols, idxCols)
> 		}
> 		if t.IsFirstJoinInPairedJoiner {
> ```

Since you're adding this one, might be worth adding a line for `second join in paired joiner` for the lookup join? Or do you think that's overkill?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61153)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/memo/expr_format.go, line 484 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61153#-MUQnnkKEpmJbXTn1iDh:-MUVI-UF7qboY6bLlLlL:b-fznogt) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cf18dde90252315157ff2ac9640026eaab2a1b3/pkg/sql/opt/memo/expr_format.go#L484)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Since you're adding this one, might be worth adding a line for `second join in paired joiner` for the lookup join? Or do you think that's overkill? 
</blockquote></details>

Good idea, done.

**Review by rytaft — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61153)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61153#-:-MUVJrLc9OeBO3zAGQzR:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
