### PR TITLE
server: clean up node.Batch and fix the snowball recorder

### PR DESCRIPTION
**Pull request by RaduBerinde**
CC @spencerkimball

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10301)

### CODE REVIEW

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10301#-:-KVBqSQ2pV6wAhXBZGeC:bnfp4nl)*

**Comment by spencerkimball** [comment]
I've left off needing this PR in my most recent revision, but it still seems like a good change.

**Comment by RaduBerinde** [comment]
@spencerkimball can you push c85c6c496 in a branch somewhere? (can be in your own fork) I want to check that the test doesn't crash with this change.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10301#-:-KVC4V0Qfu1NdRTzzNTB:b23dq3y)*

**Comment by spencerkimball** [comment]
Uh oh I rebased over my change. Is there a way to get back to it?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10301#-:-KVC7_5FKBfL4kSW49WH:byvc1q3)*

**Comment by RaduBerinde** [comment]
You must still have the commit in your repo..  `git checkout -b temp c85c6c4` and push that

**Comment by spencerkimball** [comment]
> git checkout -b temp c85c6c4
OK, there's a temp branch pushed which fails: `make test PKG=./pkg/sql TESTFLAGS=-v TESTS=TestExplainTrace`

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10301#-:-KVCGaNj9kAnZcXiyzge:b-c599sm)*

**Comment by RaduBerinde** [comment]
Great, I verified that the test crashes before the change and passes with this change. I deleted the branch. Thank you!

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10301#-:-KVF5LETJ2WpXzEPIt6C:b-uqlsqj)*

**Pull request merged**
