### PR TITLE
ui: fix generated `DROP INDEX` statement on table details page

### PR DESCRIPTION
**Pull request by zachlite**
This commit does two things:
1. Fixes the generated `DROP INDEX` statement by considering already quoted fully-qualified names.

2. Adds unit tests for the `QuoteIdentifier` utility to clarify its intended usage and limitations.

Epic: none
Release note (bug fix): Fixed a UI issue where the DROP_UNUSED index recommendations produced by the
table details page produced an invalid `DROP INDEX` statement.

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110429)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @zachlite)

___
*[`pkg/ui/workspaces/cluster-ui/src/databaseTablePage/helperComponents.tsx` line 189 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110429#-Ne8bfk1A-ue-0RNQkRa:-Ne8bfk1A-ue-0RNQkRb:bkrxw2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/b33f9f352d22a73d6c42475319092dca74a21570/pkg/ui/workspaces/cluster-ui/src/databaseTablePage/helperComponents.tsx#L189)):*
> ```XML
>     switch (recommendation.type) {
>       case "DROP_UNUSED":
>         // Here, `tableName` is a fully qualified name whose identifiers have already been quoted.
> ```

do you think it can be confusing to identify what has been quoted or not? Can the QuoteIdentifier do the check instead, and if already quotes does nothing? This way you don't risk calling it on things already quoted and you can always use it

**Review by zachlite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110429)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/databaseTablePage/helperComponents.tsx` line 189 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110429#-Ne8bfk1A-ue-0RNQkRa:-Ne8ibhq9Q6-AiTyg6k0:b-xesw3g) ([raw file](https://github.com/cockroachdb/cockroach/blob/b33f9f352d22a73d6c42475319092dca74a21570/pkg/ui/workspaces/cluster-ui/src/databaseTablePage/helperComponents.tsx#L189)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

do you think it can be confusing to identify what has been quoted or not? Can the QuoteIdentifier do the check instead, and if already quotes does nothing? This way you don't risk calling it on things already quoted and you can always use it
</blockquote></details>

I agree it's confusing.  I did what you're suggesting here initially, thinking that `QuoteIdentifier` should be idempotent.  But the problem is that it becomes difficult (impossible?) to know what to do if the caller doesn't tell us the state of the argument.

For example, consider `"tablename"`.  Without the caller telling us, it's impossible to tell if the argument is already a quoted identifier, or if the argument should treated as a non-quoted identifier and it's chars need escaping. If the former, the result should be `"tablename"`. If the latter, the result should be `"""tablename"""`.

My solution was to document this and write a unit test.. WDYT?

**Review by zachlite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110429)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/databaseTablePage/helperComponents.tsx` line 189 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110429#-Ne8bfk1A-ue-0RNQkRa:-Ne8kp2pBIlng8FknqqF:bukdbhc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b33f9f352d22a73d6c42475319092dca74a21570/pkg/ui/workspaces/cluster-ui/src/databaseTablePage/helperComponents.tsx#L189)):*
<details><summary><i>Previously, zachlite wrote…</i></summary><blockquote>

I agree it's confusing.  I did what you're suggesting here initially, thinking that `QuoteIdentifier` should be idempotent.  But the problem is that it becomes difficult (impossible?) to know what to do if the caller doesn't tell us the state of the argument.

For example, consider `"tablename"`.  Without the caller telling us, it's impossible to tell if the argument is already a quoted identifier, or if the argument should treated as a non-quoted identifier and it's chars need escaping. If the former, the result should be `"tablename"`. If the latter, the result should be `"""tablename"""`.

My solution was to document this and write a unit test.. WDYT?
</blockquote></details>

And `QuoteIdentifier` currently always assumes the latter.

**Review by maryliag — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110429#-:-Ne8mVa01Df-2mXTteli:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @zachlite)

___
*[`pkg/ui/workspaces/cluster-ui/src/databaseTablePage/helperComponents.tsx` line 189 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110429#-Ne8bfk1A-ue-0RNQkRa:-Ne8mSEN6uP9PWb4T57a:bdf2gth) ([raw file](https://github.com/cockroachdb/cockroach/blob/b33f9f352d22a73d6c42475319092dca74a21570/pkg/ui/workspaces/cluster-ui/src/databaseTablePage/helperComponents.tsx#L189)):*
<details><summary><i>Previously, zachlite wrote…</i></summary><blockquote>

And `QuoteIdentifier` currently always assumes the latter.
</blockquote></details>

I see. Thanks for the explanation

**Pull request merged**
