### PR TITLE
storage: include summary of prereq batches in cmdQ logs/traces

### PR DESCRIPTION
**Pull request by nvb**
This change adds a summary of the batch requests that a command is waiting
on in the command queue to the trace event from before and after the command
enters the queue. It turns the following two traces:

```
waiting for 4 overlapping requests
waited 8.634716ms for overlapping requests
```

into

```
waiting for 4 overlapping requests: {write/local: [1 EndTxn], [1 EndTxn], [1 EndTxn], [1 EndTxn]}
waited 983.742µs for overlapping requests: {read/local: [1 CPut, 1 BeginTxn]} {write/local: [1 CPut, 1 BeginTxn]}
```

This should improve our ability to understand command queue contention
from traces or high-verbosity logs (`V(2)`).

Release note: None

### CODE REVIEW

**Review by tbg — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29361)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 2373 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29361#-LL_31x84IpJPaOn1Pv5:-LL_31x84IpJPaOn1Pv6:bhub2hp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fb68ce9251787703cad22d10e6ae99e8f56f16d/pkg/storage/replica.go#L2373)):*
> ```Go
> 		var prereqSummary string
> 		if prereqCount > 0 && log.ExpensiveLogEnabled(ctx, 2) {
> 			var b strings.Builder
> ```

Wanna pull this out? That'll help keep the main flow of this method readable and it also lets you add a simple unit test that makes clear what the output is and gives basic confidence that this code won't just NPE when run.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29361)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 2373 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29361#-LL_31x84IpJPaOn1Pv5:-LNBxpTs3_TaASuCPZXg:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fb68ce9251787703cad22d10e6ae99e8f56f16d/pkg/storage/replica.go#L2373)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Wanna pull this out? That'll help keep the main flow of this method readable and it also lets you add a simple unit test that makes clear what the output is and gives basic confidence that this code won't just NPE when run.
</blockquote></details>

Good idea. Done.

**Review by tbg — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29361#-:-LNF3jhA2QKh14mhP62J:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by nvanbenschoten** [comment]
TFTR!

bors r+

**Pull request merged**
