### PR TITLE
cli/start: make Ctrl-C less frightening by avoiding an error shout

### LINKED ISSUE #16925: cli: interrupt signals should be shouted as INFO not ERROR
REported by @dianasaur323  - the ERROR upon ctrl+c is worrying for users whereas it is mostly innocuous for the database. The severity for this message should be downgraded.

### PR DESCRIPTION
**Pull request by knz**
Fixes #16925.

### CODE REVIEW

**Review by tbg — COMMENTED** [review]
Can you not return a sentinel error instead to avoid the globals magic? Maybe I'm missing the point.

**Comment by knz** [comment]
You're right; done.

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18195#-:-KtCUr5vWFCLiSX7QqnG:bnfp4nl)*

**Comment by knz** [comment]
TFYR! 
And your suggestion :)

**Pull request merged**
