### PR TITLE
ui: bugfixes

### PR DESCRIPTION
**Pull request by maxlang**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9340)

### CODE REVIEW

**Comment by mrtracy** [comment]
Reviewed 3 of 3 files at r1, 9 of 9 files at r2.
Review status: 8 of 15 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[ui/app/components/graphs.tsx, line 134 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9340#-KR_PA59JV_B-CSmeqJ3:-KR_PA59JV_B-CSmeqJ4:bsbt8b4) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d6be75f0b7d79081e80bbba99ecd74cf9967922/ui/app/components/graphs.tsx#L134)):*
> ```XML
> 
>   // timestamps has a key for all the timestamps present across all datasets
>   let timestamps = getTimestamps(metrics, data);
> ```

This is pretty harsh processing; let me think about this, it's a situation where I think "there's got to be a better way!"

---

*[ui/app/components/linegraph.tsx, line 62 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9340#-KR_KT-ID60s9raDknM_:-KR_KT-ID60s9raDknMa:bi307xr) ([raw file](https://github.com/cockroachdb/cockroach/blob/79b47d5e18e68a866d5edec8d640f8cf3cd44293/ui/app/components/linegraph.tsx#L62)):*
> ```XML
>     });
> 
>   drawChartBound: () => void;
> ```

Why not define drawChart as `drawChart = () => {` instead?  Then it's automatically bound.

---

*[ui/app/components/stackedgraph.tsx, line 60 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9340#-KR_KawY8JrCuerfiiUV:-KR_KawY8JrCuerfiiUW:bs4q9op) ([raw file](https://github.com/cockroachdb/cockroach/blob/79b47d5e18e68a866d5edec8d640f8cf3cd44293/ui/app/components/stackedgraph.tsx#L60)):*
> ```XML
>     });
> 
>   drawChartBound: () => void;
> ```

Ditto.

---

*[ui/app/containers/timescale.tsx, line 68 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9340#-KR_LuX8zuUiPatrvnF0:-KR_LuX9lEIm5p5nwwLj:b-sryjge) ([raw file](https://github.com/cockroachdb/cockroach/blob/7663c69849aa4e96203f6477a209df3e3520f043/ui/app/containers/timescale.tsx#L68)):*
> ```XML
> 
>   // Sets the default timescale based on the start time of the oldest node.
>   setDefaultTime(props = this.props) {
> ```

Well, thats a handy default argument.

---

*[ui/app/redux/metrics.ts, line 82 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9340#-KR_L4Vw09CNCO3qXWIF:-KR_L4Vw09CNCO3qXWIG:b-jom8k1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7663c69849aa4e96203f6477a209df3e3520f043/ui/app/redux/metrics.ts#L82)):*
> ```XML
>     case RECEIVE:
>       let { payload: response } = action as PayloadAction<WithID<RequestWithResponse>>;
>       if (response.data.request === state.nextRequest) {
> ```

This was even easier than I thought!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9340)*

**Comment by maxlang** [comment]
Review status: 0 of 15 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[ui/app/components/graphs.tsx, line 134 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9340#-KR_PA59JV_B-CSmeqJ3:-KRbWBfY0OSG4p7qq-4P:bgg827t) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d6be75f0b7d79081e80bbba99ecd74cf9967922/ui/app/components/graphs.tsx#L134)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> This is pretty harsh processing; let me think about this, it's a situation where I think "there's got to be a better way!"
</details>
It's possible you could guess the expected timestamps based on the query request.  That would allow us to fix #7319 as well. That said, this is just two iterations through the datapoints vs one, so it's not _horrible_.

---

*[ui/app/components/linegraph.tsx, line 62 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9340#-KR_KT-ID60s9raDknM_:-KRbSdf7gKHiwbPmHyWM:b-qu6n94) ([raw file](https://github.com/cockroachdb/cockroach/blob/79b47d5e18e68a866d5edec8d640f8cf3cd44293/ui/app/components/linegraph.tsx#L62)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> Why not define drawChart as `drawChart = () => {` instead?  Then it's automatically bound.
</details>
Good point. Done.

---

*[ui/app/components/stackedgraph.tsx, line 60 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9340#-KR_KawY8JrCuerfiiUV:-KRbSfk5UTNa2rIQVSdz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/79b47d5e18e68a866d5edec8d640f8cf3cd44293/ui/app/components/stackedgraph.tsx#L60)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> Ditto.
</details>
Done.

---

*[ui/app/containers/timescale.tsx, line 68 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9340#-KR_LuX8zuUiPatrvnF0:-KRbWoftxr7wHaSeuDDY:b36y9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/7663c69849aa4e96203f6477a209df3e3520f043/ui/app/containers/timescale.tsx#L68)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> Well, thats a handy default argument.
</details>
Haha yup.

---

*[ui/app/redux/metrics.ts, line 82 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9340#-KR_L4Vw09CNCO3qXWIF:-KRbWqKY_y3holq18k1U:byklnv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7663c69849aa4e96203f6477a209df3e3520f043/ui/app/redux/metrics.ts#L82)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> This was even easier than I thought!
</details>
Yeah,  didn't know if the reducer was 100% the right spot, but it's pretty clear this way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9340)*

**Comment by petermattis** [comment]
I think we should consider targeting admin UI bug fixes at master.

**Comment by tamird** [comment]
Unfortunately, the master/develop divergence in UI is substantial, so this
likely requires backports.

**Comment by mrtracy** [comment]
:lgtm:

---

Review status: 0 of 15 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[ui/app/components/graphs.tsx, line 134 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9340#-KR_PA59JV_B-CSmeqJ3:-KRdszL2tlsZD94W7iN1:beu61e2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d6be75f0b7d79081e80bbba99ecd74cf9967922/ui/app/components/graphs.tsx#L134)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> It's possible you could guess the expected timestamps based on the query request.  That would allow us to fix #7319 as well. That said, this is just two iterations through the datapoints vs one, so it's not _horrible_.
</details>
Actually, I just really wish this could be handled at the graph level.  This is fine, I couldn't think of a better way to do it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9340#-:-KRdtGcsI4r-Pe60JZFx:bnfp4nl)*

**Pull request merged**
