### PR TITLE
sqlbase: interleave descriptors and key coding

### PR DESCRIPTION
**Pull request by danhhz**
Implements the encoding described in
https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/sql_interleaved_tables.md

No change in benchmarks for non-interleaved tables.

name                       old time/op    new time/op    delta
Insert1000_Cockroach-8       9.73ms ± 4%    9.71ms ± 3%    ~             (p=0.690 n=5+5)
Update1000_Cockroach-8       28.6ms ± 4%    29.0ms ± 2%    ~             (p=0.310 n=5+5)
Delete1000_Cockroach-8       49.8ms ± 4%    48.2ms ± 5%    ~             (p=0.222 n=5+5)
Scan1000_Cockroach-8         2.28ms ± 2%    2.24ms ± 2%    ~             (p=0.222 n=5+5)
WideTable1000_Cockroach-8     109ms ± 4%     112ms ± 2%    ~             (p=0.151 n=5+5)

name                       old alloc/op   new alloc/op   delta
Insert1000_Cockroach-8       4.18MB ± 0%    4.18MB ± 0%    ~             (p=0.413 n=4+5)
Update1000_Cockroach-8       6.55MB ± 0%    6.54MB ± 0%    ~             (p=0.690 n=5+5)
Delete1000_Cockroach-8       3.19MB ± 0%    3.19MB ± 0%    ~             (p=0.690 n=5+5)
Scan1000_Cockroach-8          317kB ± 0%     317kB ± 0%  +0.04%          (p=0.008 n=5+5)
WideTable1000_Cockroach-8    21.2MB ± 0%    21.2MB ± 0%    ~             (p=0.690 n=5+5)

name                       old allocs/op  new allocs/op  delta
Insert1000_Cockroach-8        20.4k ± 0%     20.4k ± 0%    ~             (p=0.540 n=4+5)
Update1000_Cockroach-8        29.5k ± 0%     29.5k ± 0%    ~             (p=0.056 n=5+5)
Delete1000_Cockroach-8        21.6k ± 0%     21.6k ± 0%    ~             (p=0.810 n=5+5)
Scan1000_Cockroach-8          2.30k ± 0%     2.30k ± 0%    ~     (all samples are equal)
WideTable1000_Cockroach-8      223k ± 0%      223k ± 0%    ~             (p=0.690 n=5+5)

For #2972.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7755)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Review status: 0 of 20 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/sqlbase/structured.proto, line 202 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755#-KMR2zD70_oo9OMP_0AF:-KMR2zD70_oo9OMP_0AG:555969311) ([raw file](https://github.com/cockroachdb/cockroach/blob/376daf80a30445cae91fd9a7c08860b54433b85d/sql/sqlbase/structured.proto#L202)):*
> ```protobuf
> 
> // InterleaveDescriptor represents an index (either primary or secondary) that
> // is interleaved into another table's data.
> ```

I think the example below should be moved up here and should mention how the entire InterleaveDescriptor looks and for which table it is set. (In fact there will be one set for table 3, and another one set for table 2 right?)

---

*[sql/sqlbase/structured.proto, line 206 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755#-KMR398BYA7112SMCwSc:-KMR398BYA7112SMCwSd:2115764884) ([raw file](https://github.com/cockroachdb/cockroach/blob/376daf80a30445cae91fd9a7c08860b54433b85d/sql/sqlbase/structured.proto#L206)):*
> ```protobuf
>   message Component {
>     // ParentID the ID of the table being interleaved into.
>     optional uint32 parent_id = 1 [(gogoproto.nullable) = false,
> ```

`ancestor_table_id` (and `ancestor_index_id`)? can also be just `table_id`/`index_id` if the struct is called Ancestor

---

*[sql/sqlbase/structured.proto, line 231 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755#-KMR2TaICuLE1srF-CHI:-KMR2TaICuLE1srF-CHJ:1562179118) ([raw file](https://github.com/cockroachdb/cockroach/blob/376daf80a30445cae91fd9a7c08860b54433b85d/sql/sqlbase/structured.proto#L231)):*
> ```protobuf
>   // an encoded key. The last element is interleaved into the second to last,
>   // and so on.
>   repeated Component components = 2 [(gogoproto.nullable) = false];
> ```

Maybe it would make more sense for this to be called ancestors instead of components?

The comment should mention that they are always in the far-to-near ancestor order (e.g. grand-grand-parent, grand-parent, parent).

---

*[sql/sqlbase/structured.proto, line 249 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755#-KMR3_8RD6h_vSwFzDdM:-KMR3_8RD6h_vSwFzDdN:-830697968) ([raw file](https://github.com/cockroachdb/cockroach/blob/376daf80a30445cae91fd9a7c08860b54433b85d/sql/sqlbase/structured.proto#L249)):*
> ```protobuf
>   optional uint32 parent_id = 4 [(gogoproto.nullable) = false,
>       (gogoproto.customname) = "ParentID", (gogoproto.casttype) = "ID"];
>   repeated InterleaveDescriptor interleaves = 24 [(gogoproto.nullable) = false,
> ```

Doesn't this belong into IndexDescriptor instead of TableDescriptor?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755)*

**Comment by paperstreet** [comment]
Thanks @raduberinde! RFAL

---

Review status: 0 of 20 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/sqlbase/structured.proto, line 202 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755#-KMR2zD70_oo9OMP_0AF:-KMUdc94x-t-NvV-lfZR:201294969) ([raw file](https://github.com/cockroachdb/cockroach/blob/376daf80a30445cae91fd9a7c08860b54433b85d/sql/sqlbase/structured.proto#L202)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> I think the example below should be moved up here and should mention how the entire InterleaveDescriptor looks and for which table it is set. (In fact there will be one set for table 3, and another one set for table 2 right?)
</details>
Fair point

---

*[sql/sqlbase/structured.proto, line 206 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755#-KMR398BYA7112SMCwSc:-KMUdUoWufOoQa3VCqLP:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/376daf80a30445cae91fd9a7c08860b54433b85d/sql/sqlbase/structured.proto#L206)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> `ancestor_table_id` (and `ancestor_index_id`)? can also be just `table_id`/`index_id` if the struct is called Ancestor
</details>
Done.

---

*[sql/sqlbase/structured.proto, line 231 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755#-KMR2TaICuLE1srF-CHI:-KMUdYFtrOpH-0dKqfBR:1337007447) ([raw file](https://github.com/cockroachdb/cockroach/blob/376daf80a30445cae91fd9a7c08860b54433b85d/sql/sqlbase/structured.proto#L231)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Maybe it would make more sense for this to be called ancestors instead of components?
> 
> The comment should mention that they are always in the far-to-near ancestor order (e.g. grand-grand-parent, grand-parent, parent).
</details>
Sure, I like Ancestor

---

*[sql/sqlbase/structured.proto, line 249 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755#-KMR3_8RD6h_vSwFzDdM:-KMUe2JYF1xOPCt52wUR:-1571609979) ([raw file](https://github.com/cockroachdb/cockroach/blob/376daf80a30445cae91fd9a7c08860b54433b85d/sql/sqlbase/structured.proto#L249)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Doesn't this belong into IndexDescriptor instead of TableDescriptor?
</details>
Ah, that does model the at-most-one interleave per index more correctly. I did it the other way because I was thinking the code would be a little cleaner, but that's likely the wrong tradeoff. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755#-:-KMVMLIMmWZz4D-j3m7A:-1529773659)*

**Comment by RaduBerinde** [comment]
Proto LGTM! Some comments on the rest, nothing major

---

Reviewed 1 of 20 files at r1.
Review status: 0 of 20 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[sql/sqlbase/table.go, line 333 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755#-KMVSIGSpj3dOpEMpa2g:-KMVSIGSpj3dOpEMpa2h:1318741568) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ebd44f317df5faaec3475116afd8888195c8d65/sql/sqlbase/table.go#L333)):*
> ```Go
> //
> // Note that ImplicitColumnIDs are not encoded, so the result isn't always a
> // full index key.
> ```

This function comment should mention how the key looks in the interleaved case.

---

*[sql/sqlbase/table.go, line 353 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755#-KMVSXo-PgWkItG4obR-:-KMVSXo-PgWkItG4obR0:1569693030) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ebd44f317df5faaec3475116afd8888195c8d65/sql/sqlbase/table.go#L353)):*
> ```Go
> 			}
> 
> 			l := int(ancestor.SharedPrefixLen)
> ```

[nit] this is easily confused with 1, maybe use `len` or `num`

---

*[sql/sqlbase/table.go, line 359 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755#-KMVSsf26ZVSuoiLgOHb:-KMVSsf26ZVSuoiLgOHc:-38916961) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ebd44f317df5faaec3475116afd8888195c8d65/sql/sqlbase/table.go#L359)):*
> ```Go
> 				return key, containsNull, err
> 			}
> 			offset += l
> ```

[nit] instead of `offset` we could just initialize a `cols` slice like the `dirs` one and just do `cols, dir = cols[l:], dirs[l:]` every time.

---

*[sql/sqlbase/table.go, line 362 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755#-KMVaPXgX5kyCQv71xEn:-KMVaPXgX5kyCQv71xEo:-178024687) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ebd44f317df5faaec3475116afd8888195c8d65/sql/sqlbase/table.go#L362)):*
> ```Go
> 			containsNull = containsNull || n
> 
> 			key = encoding.EncodeNullDescending(key)
> ```

Maybe add a comment explaining that we are using the same encoding as NULL as a sentinel. (also in the decoding functions where we call DecodeIfNull)

---

*[sql/sqlbase/table.go, line 617 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755#-KMVZ94dEfoV5UJWCRM2:-KMVZ94dEfoV5UJWCRM3:392489760) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ebd44f317df5faaec3475116afd8888195c8d65/sql/sqlbase/table.go#L617)):*
> ```Go
> 	interleaves := append([]IndexDescriptor{desc.PrimaryIndex}, desc.Indexes...)
> 
> 	for component := 0; ; component++ {
> ```

I was going to say this is not something we should need to do in the hot path of a scan, but I see we are no longer using this function in DecodeIndexKey. Great! Do you know in what paths we would need to do this? (In what case are we decoding keys without knowing the index they are for?)

---

*[sql/sqlbase/table.go, line 677 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755#-KMV_Kia3IFNUd7QeAab:-KMV_Kia3IFNUd7QeAac:1773275186) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ebd44f317df5faaec3475116afd8888195c8d65/sql/sqlbase/table.go#L677)):*
> ```Go
> // primary key index, the primary key suffix for non-unique secondary indexes
> // or unique secondary indexes containing NULL or empty.
> func DecodeIndexKey(
> ```

I assume we will need to extend this to allow the caller (e.g. rowfetcher) to ignore keys that are part of the parent tables?

---

*[sql/sqlbase/table.go, line 690 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755#-KMV_bkFkKnY7JO_g8Lo:-KMV_bkFkKnY7JO_g8Lp:1126310593) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ebd44f317df5faaec3475116afd8888195c8d65/sql/sqlbase/table.go#L690)):*
> ```Go
> 		for _, ancestor := range index.Interleave.Ancestors {
> 			var parentTableID uint64
> 			key, parentTableID, err = encoding.DecodeUvarintAscending(key)
> ```

We are repeating this code of decoding the table and the index (it's also in the function above), probably better to separate it into a helper that returns `key, ID, IndexID, err`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755#-:-KMVabdpW1Of0bg5UpaY:1347504830)*

**Comment by paperstreet** [comment]
Review status: 0 of 20 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[sql/sqlbase/table.go, line 333 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755#-KMVSIGSpj3dOpEMpa2g:-KMVvGKme6jPIZGEqNfZ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ebd44f317df5faaec3475116afd8888195c8d65/sql/sqlbase/table.go#L333)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> This function comment should mention how the key looks in the interleaved case.
</details>
Done.

---

*[sql/sqlbase/table.go, line 353 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755#-KMVSXo-PgWkItG4obR-:-KMVjySnr6JgTgeywmfD:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ebd44f317df5faaec3475116afd8888195c8d65/sql/sqlbase/table.go#L353)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> [nit] this is easily confused with 1, maybe use `len` or `num`
</details>
Done.

---

*[sql/sqlbase/table.go, line 359 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755#-KMVSsf26ZVSuoiLgOHb:-KMVjy1jDasII2nFZpTf:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ebd44f317df5faaec3475116afd8888195c8d65/sql/sqlbase/table.go#L359)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> [nit] instead of `offset` we could just initialize a `cols` slice like the `dirs` one and just do `cols, dir = cols[l:], dirs[l:]` every time.
</details>
Done.

---

*[sql/sqlbase/table.go, line 362 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755#-KMVaPXgX5kyCQv71xEn:-KMVkbD2DJvBUh1kw-LN:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ebd44f317df5faaec3475116afd8888195c8d65/sql/sqlbase/table.go#L362)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Maybe add a comment explaining that we are using the same encoding as NULL as a sentinel. (also in the decoding functions where we call DecodeIfNull)
</details>
Done.

---

*[sql/sqlbase/table.go, line 617 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755#-KMVZ94dEfoV5UJWCRM2:-KMVkwKRuF_88DkG0dtY:781146229) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ebd44f317df5faaec3475116afd8888195c8d65/sql/sqlbase/table.go#L617)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> I was going to say this is not something we should need to do in the hot path of a scan, but I see we are no longer using this function in DecodeIndexKey. Great! Do you know in what paths we would need to do this? (In what case are we decoding keys without knowing the index they are for?)
</details>
It's used to compute upsert conflicts and to construct error messages for duplicate violations.

I thought about adding a comment to this effect, but I'm worried that it will rot.

---

*[sql/sqlbase/table.go, line 677 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755#-KMV_Kia3IFNUd7QeAab:-KMVlvusciKQYSi1gSq4:1318507682) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ebd44f317df5faaec3475116afd8888195c8d65/sql/sqlbase/table.go#L677)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> I assume we will need to extend this to allow the caller (e.g. rowfetcher) to ignore keys that are part of the parent tables?
</details>
I think rowfetcher can do something faster than that. All keys for row `/Table/50/a/b` will be before `Table/50/a/b/0xff` (the last being DescendingNull, our interleave sentinel).

---

*[sql/sqlbase/table.go, line 690 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755#-KMV_bkFkKnY7JO_g8Lo:-KMVpbJ1pUlyeSMLU9Cl:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ebd44f317df5faaec3475116afd8888195c8d65/sql/sqlbase/table.go#L690)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> We are repeating this code of decoding the table and the index (it's also in the function above), probably better to separate it into a helper that returns `key, ID, IndexID, err`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755)*

**Comment by paperstreet** [comment]
RFAL

---

Review status: 0 of 20 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755#-:-KM_hPlSQ1hsE8Jb8IPZ:677011428)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Reviewed 14 of 20 files at r1, 4 of 6 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/sqlbase/table.go, line 617 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755#-KMVZ94dEfoV5UJWCRM2:-KM_kH6Z8s5u6FY4yJ4r:1754669718) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ebd44f317df5faaec3475116afd8888195c8d65/sql/sqlbase/table.go#L617)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> It's used to compute upsert conflicts and to construct error messages for duplicate violations.
> 
> I thought about adding a comment to this effect, but I'm worried that it will rot.
</details>
Got it. Maybe just add a function comment that this function is not intended to be used in the "hot path" of a scan.

---

*[sql/sqlbase/table.go, line 335 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755#-KM_jw23y0PuoegebrTA:-KM_jw23y0PuoegebrTB:300496931) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea713179c93e21faead4478f38dc56484c0836ad/sql/sqlbase/table.go#L335)):*
> ```Go
> // /<parent_table_id>/<parent_index_id>/<field_1>/<field_2>/NullDesc/<table_id>/<index_id>/<field_3>/<family>
> //
> // Returns the key and whether any of t he encoded values were NULLs.
> ```

extra space in `the`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755#-:-KM_kRAeNQNLf4WJkrRH:1417088721)*

**Comment by paperstreet** [comment]
Thanks for the review!!!

---

Review status: 19 of 20 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/sqlbase/table.go, line 617 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755#-KMVZ94dEfoV5UJWCRM2:-KM_lpkuBRxQGz6upJ3J:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ebd44f317df5faaec3475116afd8888195c8d65/sql/sqlbase/table.go#L617)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Got it. Maybe just add a function comment that this function is not intended to be used in the "hot path" of a scan.
</details>
Done.

---

*[sql/sqlbase/table.go, line 335 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755#-KM_jw23y0PuoegebrTA:-KM_m6O-s6pDswoHFL5Z:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea713179c93e21faead4478f38dc56484c0836ad/sql/sqlbase/table.go#L335)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> extra space in `the`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7755#-:-KM_m74d8EjsQo3eRGXF:1382864433)*

**Pull request merged**
