### PR TITLE
lint: enable the CODEOWNERS linter on non-clean workdirs

### PR DESCRIPTION
**Pull request by knz**
Prior to this patch, the linter would bark if there were spurious
files in otherwise-empty unowned directories (e.g. pkg/).

This patch fixes it.

Release note: None

### CODE REVIEW

**Review by srosenberg — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81467#-:-N2PEwpCBrnn70DGOhjA:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist and @knz)

___
*[`pkg/internal/codeowners/lint.go` line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81467#-N2PEYsRDuGjpI3sC3O3:-N2PEYsS9CG-50ofUmEN:bnv67yj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1809517d67741ad0c79e45504d889bd595926356/pkg/internal/codeowners/lint.go#L69)):*
> ```Go
> 		"README.md":                         {},
> 	}
> 	skipGlobs := []string{
> ```

Seems odd that these globs are not part of .gitignore; if they were, we could load them from there to avoid bit rot.

**Review by knz — COMMENTED** [review]
Thanks stan!

bors r=srosenberg

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81467#-:-N2RQeLR369loug-ha2T:b8k09hc)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist and @srosenberg)

___
*[`pkg/internal/codeowners/lint.go` line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81467#-N2PEYsRDuGjpI3sC3O3:-N2RQG6L8VpVdqJvfKn1:b-n3zk5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/1809517d67741ad0c79e45504d889bd595926356/pkg/internal/codeowners/lint.go#L69)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Seems odd that these globs are not part of .gitignore; if they were, we could load them from there to avoid bit rot.
</blockquote></details>

1. IIRC they are not because folk have argued in the past that "this type of global ignores belongs to a ~/.gitignore file, not a per-project one".
2. the .gitignore files are strewn across multiple levels of the hierarchy. The cost of loading them, and then applying the rules in the right order and the right way (NB, gitignore has its own matching syntax and order, not simple globs), seems more hassle than is worth here.

**Review by andrewbaptist — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81467)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @srosenberg)

**Review by andrewbaptist — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81467)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @srosenberg)

**Review by andrewbaptist — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81467)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @srosenberg)

**Pull request merged**
