### PR TITLE
c-deps,storage: remove libroach

### PR DESCRIPTION
**Pull request by dt**
See individual commits.

This removes libroach which as down to a single function used to list c threads which was still exposed in a debug endpoint and in debug zips. Since the removal of rocksdb however this is no longer particularly useful. This removes it, and then removes all the build cruft around libroach.

### CODE REVIEW

**Review by rickystewart — APPROVED** [review]
lgtm for the `make`/Bazel bits

**Review by tbg — APPROVED** [review]
🥳

**Review by sumeerbhola — APPROVED** [review]
:lgtm_strong: 

> Reviewed 4 of 4 files at r1, 23 of 24 files at r7, 2 of 2 files at r8, 4 of 4 files at r9, 4 of 7 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67389#-:-MePh-Hi-AHRSMrdQpqe:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens and @sumeerbhola)

**Comment by dt** [comment]
TFTRs!

bors r+

**Comment by dt** [comment]
Let's try this again bors.

bors r+

**Pull request merged**
