### PR TITLE
Adds a footer with helpful links

### PR DESCRIPTION
**Pull request by maxlang**
Sits at the bottom of the page when the page height is larger than the window height:
screen shot 2016-03-29 at 3 09 13 pm
(scrolled down)
screen shot 2016-03-29 at 3 09 20 pm
Doesn't wrap when the width is too small
screen shot 2016-03-29 at 3 09 00 pm
Sits at the bottom when the window height is small
screen shot 2016-03-29 at 3 08 48 pm
Or large
screen shot 2016-03-29 at 3 08 39 pm
Thinner example
screen shot 2016-03-29 at 3 08 29 pm

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5696)

### CODE REVIEW

**Comment by maxlang** [comment]
Bit of a last minute change, but could be helpful.

cc @spencerkimball

**Comment by spencerkimball** [comment]
Yeah I like it.

**Comment by cuongdo** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ui/ts/pages/footer.ts, line 20 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5696#-KE4Bed8kzbbxlN1Sqqv:-KE4Bed8kzbbxlN1Sqqw:-1405936436) ([raw file](https://github.com/cockroachdb/cockroach/blob/55e6737815d5b0a5fc59b4ca85e2d01b8870b977/ui/ts/pages/footer.ts#L20)):*
shouldn't this have `https://` as the prefix?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5696)*

**Comment by cuongdo** [comment]
:lgtm: aside from the one footer link issue

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5696#-:-KE4ClcecPfn9KRTfAa0:1091387920)*

**Comment by maxlang** [comment]
Ok I fixed the link and took the opportunity to fix the google groups links to point the same place as the cockroach labs homepage

**Comment by maxlang** [comment]
Merging, let me know if you want different Google groups links @jess-edwards

**Pull request merged**
