### PR TITLE
pprof: enable Mutex profiling by default

### PR DESCRIPTION
**Pull request by nvb**
This PR enables mutex profiling by default. See the following for a detailed introduction to the profile type: https://rakyll.org/mutexprofile/.

The mutex profile sampling rate is set at `.1%`. This is based off of golang/go#23401 (comment),
which says that Google runs all of their Go servers in production with the sampling rate of `1%`. I figured that it doesn't hurt to be an order of magnitude more conservative than them, but I'm not against following them directly.

I ran a few benchmarks on my laptop. With a mutex profile sample rate of `100%` I observed a drop in throughput of `kv95 --concurrency=64` of just about `1%`. This indicates that a sampling rate of `.1%` will result in a negligible performance change.

The change also adds the new profile type to the debug page and the pprof ui visualizer (it was actually already there, it just had no samples by default).

screenshot_2018-09-14 unknown delay

### CODE REVIEW

**Review by vilterp — APPROVED** [review]
UI stuff LGTM

**Comment by nvanbenschoten** [comment]
On a related note, the Mutex contention in `uuid.NewV4` due to its use of `crypto/rand` is worth investigating. This might already be bearing fruit.

**Comment by nvanbenschoten** [comment]
I'm far from an expert in this area, but I'm skeptical that we actually need a cryptographically secure random byte generator for our transaction IDs. Interestingly, `github.com/google/uuid` allows the random number generator to be [configured](https://github.com/google/uuid/blob/e704694aed0ea004bb7eb1fc2e911d048a54606a/uuid.go#L196). That might be an interesting path to explore, especially with some kind of goroutine-local rng to avoid internal synchronization. We could also think about batching UUID allocation.

**Comment by nvanbenschoten** [comment]
At a minimum, it would be worth mocking out `pkg/util/uuid.MakeV4` and see what kind of perf improvement would could expect to see from making this faster.

**Review by benesch — APPROVED** [review]
LGTM!

**Comment by nvanbenschoten** [comment]
TFTRs!

bors r+

**Comment by bdarnell** [comment]
> On a related note, the Mutex contention in uuid.NewV4 due to its use of crypto/rand is worth investigating.

Beware of platform differences - crypto/rand has a Mutex on darwin (and other unixes) that's not used on linux. (Maybe we still want to explore alternate ways of generating transaction IDs to avoid the syscall, but the mutex blocking will disappear on linux).

**Comment by nvanbenschoten** [comment]
Yeah, @petermattis brought this up in https://github.com/cockroachdb/cockroach/issues/30236. I agree that there's more to explore here in terms of efficiently generating transaction IDs.

**Pull request merged**
