### PR TITLE
roachtest: roachprod: Remove check for Pebble CURRENT file in favour of marker.* file

### LINKED ISSUE #95170: roachtest,roachprod: remove checks for Pebble's CURRENT file
As of https://github.com/cockroachdb/pebble/pull/1227, Pebble no longer creates or maintains a `CURRENT` file. However, `roachtest` [1] and `roachprod` [2] still check for this file.

We should remove such checks or replace them with something appropriate as their existence is wrong and confusing.

[1] https://github.com/cockroachdb/cockroach/blob/241f613f2339c63d7294a3ca10bdd94f33dbbbf2/pkg/cmd/roachtest/tests/versionupgrade.go#L377-L378

[2] https://github.com/cockroachdb/cockroach/blob/241f613f2339c63d7294a3ca10bdd94f33dbbbf2/pkg/roachprod/install/cluster_synced.go#L549-L552

Jira issue: CRDB-23382

### LINKED ISSUE #99684: roachtest: post-validations can sometimes hang indefinitely
When a test finishes, `roachtest` attempts to run some post validation checks to make sure the database is not in an inconsistent state. This involves running SQL statements through _some_ live node, if any.

There's a comment in that logic from a long time ago that alludes to the fact that such calls may sometimes hang:

https://github.com/cockroachdb/cockroach/blob/b4f3ae3346b3a8a478bcf32d6254e641170988b1/pkg/cmd/roachtest/test_runner.go#L1090-L1097

While we haven't seen that happen frequently, it did happen in a recent roachtest failure [1]. The consequences of the check hanging are pretty bad, since it means the failure won't have any artifacts, making debugging impossible.

A couple of things worth noting:

* the comment above says "We avoid trying to do this when t.Failed()"; however, we are currently attempting to perform the validations regardless of test status.

* The logs in [1] indicate that we didn't even attempt to run any validation checks, meaning `ConnectToLiveNode` was stuck for 1h. This might mean that the `db.ExecContext` is not respecting context cancelation. The fix might be similar to what was done in #98851, and we need to set a connection timeout in these calls.

[1] #99586

Jira issue: CRDB-26023

### PR DESCRIPTION
**Pull request by smg260**
roachtest: roachprod: Remove check for Pebble CURRENT file in favour
of marker.* files

roachtest: `set_timeout` for `CheckInvalidDescriptors`. Without the `set_timeout`, a cancellation due to timeout is not respected and can cause the step to hang.

Epic: none
Fixes: #95170
Fixes: #99684

Release note: None

Combined with https://github.com/cockroachdb/cockroach/pull/101222 TC run [here](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/9551260?showRootCauses=true&expandBuildChangesSection=true)

### CODE REVIEW

**Comment by smg260** [comment]
There is also a `LOCK` file created on DB open [1], which could be feasible to check instead.

```
-rw-r----- 1 ubuntu ubuntu 60359944 Apr 11 17:53 000916.log
-rw-r----- 1 ubuntu ubuntu 60433928 Apr 11 17:57 000922.log
-rw-r----- 1 ubuntu ubuntu 60417732 Apr 11 18:01 000928.log
-rw-r----- 1 ubuntu ubuntu  4128012 Apr 11 17:57 000930.sst
-rw-r----- 1 ubuntu ubuntu  4150121 Apr 11 17:57 000931.sst
-rw-r----- 1 ubuntu ubuntu  4172418 Apr 11 17:57 000932.sst
-rw-r----- 1 ubuntu ubuntu  2096265 Apr 11 17:57 000933.sst
-rw-r----- 1 ubuntu ubuntu       16 Apr 11 13:56 CURRENT
-rw-r----- 1 ubuntu ubuntu        0 Apr 11 13:56 LOCK
-rw-r----- 1 ubuntu ubuntu    74104 Apr 11 17:57 MANIFEST-000001
-rw-r----- 1 ubuntu ubuntu     2539 Apr 11 13:56 OPTIONS-000003
-rw-r----- 1 ubuntu ubuntu        8 Apr 11 13:56 STORAGE_MIN_VERSION
drwxr-x--- 3 ubuntu ubuntu     4096 Apr 11 13:56 auxiliary
drwxr-xr-x 3 ubuntu ubuntu     4096 Apr 11 13:56 cockroach-temp2897837119
-rw-r----- 1 ubuntu ubuntu       17 Apr 11 13:56 cockroach.advertise-addr
-rw-r----- 1 ubuntu ubuntu       17 Apr 11 13:56 cockroach.advertise-sql-addr
-rw-r----- 1 ubuntu ubuntu       17 Apr 11 13:56 cockroach.http-addr
-rw-r----- 1 ubuntu ubuntu       10 Apr 11 13:56 cockroach.listen-addr
-rw-r----- 1 ubuntu ubuntu       10 Apr 11 13:56 cockroach.sql-addr
-rw-r----- 1 ubuntu ubuntu        0 Apr 11 13:56 marker.format-version.000012.013
-rw-r----- 1 ubuntu ubuntu        0 Apr 11 13:56 marker.manifest.000001.MANIFEST-000001
-rw-r----- 1 ubuntu ubuntu       46 Apr 11 13:56 temp-dirs-record.txt
```

[1] - https://github.com/cockroachdb/pebble/blob/124486b0f85d75a0c695cb65703c5495eec66c99/open.go#L90

**Review by herkolategan — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101254#-:-NTEkPj08nPEMmy1ZcAc:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @srosenberg)

**Review by renatolabs — CHANGES_REQUESTED** [review]
Is there any way that we can verify the dead node detector ran? I'm looking at the logs for the run you did on this branch and couldn't easily find anything.

IMO, it would be nice to make this step explicit by writing to teardown.log and also writing progress/output of the monitor script to `roachprod.log`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101254#-:-NTFAazvAWTnO7F0j3Xk:b-cvnh84)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @smg260 and @srosenberg)

___
*[`pkg/roachprod/install/cluster_synced.go` line 643 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101254#-NTFASwL7jULZD1_ffNd:-NTFASwL7jULZD1_ffNe:b-fab8tc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce69f9db04dbba6e0fdd24bbf63b8162fd0bdf65/pkg/roachprod/install/cluster_synced.go#L643)):*
> ```Go
> 			snippet := `
> {{ if .IgnoreEmpty }}
> if ls {{.Store}}/marker.* 1> /dev/null 2>&1; then
> ```

Any particular reason we're using `ls` and redirecting output instead of using `[ -f ...]` like before?

**Review by smg260 — COMMENTED** [review]
The `NodeMonitorInfo` for each node can be logged from `assertDeadNode`. It's being ignored at the moment

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101254#-:-NTH8Gpq7SBw4MOAd5wg:brn2eu7)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @herkolategan, @renatolabs, and @srosenberg)

___
*[`pkg/roachprod/install/cluster_synced.go` line 643 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101254#-NTFASwL7jULZD1_ffNd:-NTHBCEgD61BcNiTVc0G:b-aoz458) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce69f9db04dbba6e0fdd24bbf63b8162fd0bdf65/pkg/roachprod/install/cluster_synced.go#L643)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Any particular reason we're using `ls` and redirecting output instead of using `[ -f ...]` like before?
</blockquote></details>

`-f` expects only a single filename and will fail when presented with a glob or prefix like above. 

I was trying to see if there was a single file that could be used; the second comment on this PR shows the other files created by Pebble, but I don't have enough insight into knowing whether they would suffice (e.g. `LOCK`)

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101254)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @herkolategan, @smg260, and @srosenberg)

___
*[`pkg/roachprod/install/cluster_synced.go` line 643 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101254#-NTFASwL7jULZD1_ffNd:-NTJkNAHDm85H6GD3KVy:b-4bw288) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce69f9db04dbba6e0fdd24bbf63b8162fd0bdf65/pkg/roachprod/install/cluster_synced.go#L643)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

`-f` expects only a single filename and will fail when presented with a glob or prefix like above. 

I was trying to see if there was a single file that could be used; the second comment on this PR shows the other files created by Pebble, but I don't have enough insight into knowing whether they would suffice (e.g. `LOCK`)


</blockquote></details>

Ah, got it.

I think it makes sense to use the marker files. I still think we should provide some visibility that this check has run -- is there already some side effect that indicates the check passed that I'm missing?

**Comment by smg260** [comment]
Logging will now show the result of checking whether node(s) are alive in test teardown.

```
teardown: 20:09:33 cluster.go:1342: checking for dead nodes
teardown: 20:09:33 cluster.go:1367: node 1: err=<nil>,msg=dead (exit status unknown)
teardown: 20:09:33 cluster.go:1367: node 3: err=<nil>,msg=3839243
teardown: 20:09:33 cluster.go:1367: node 2: err=<nil>,msg=3839178
teardown: 20:09:33 test_impl.go:344: test failure #1: full stack retained in failure_1.log: (test_runner.go:1087).func1: 1 dead node(s) detected
teardown: 20:09:33 test_runner.go:1101: running validation checks on node 2 (<10m)
teardown: 20:09:33 cluster.go:1412: checking for invalid descriptors
```

**Comment by smg260** [comment]
Note: There is a issue inn the case where a node has died; the post validations will hang (within the `set_timeout`). This is likely the cause of various timeouts resulting in no TC artifacts. This PR does not address that as investigation is ongoing.

**Review by smg260 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101254)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @herkolategan, @renatolabs, and @srosenberg)

___
*[`pkg/roachprod/install/cluster_synced.go` line 643 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101254#-NTFASwL7jULZD1_ffNd:-NTVW38O0Y_DlgPZn13s:be25lrp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce69f9db04dbba6e0fdd24bbf63b8162fd0bdf65/pkg/roachprod/install/cluster_synced.go#L643)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Ah, got it.

I think it makes sense to use the marker files. I still think we should provide some visibility that this check has run -- is there already some side effect that indicates the check passed that I'm missing?
</blockquote></details>

Done.
Logging of node statuses added.

**Review by renatolabs — COMMENTED** [review]
Nice to see the output of the dead node detector!

IMO, we should merge just the first commit in this PR. The post-validation checks hanging is a known issue and it's not introduced by the changes here, so they can be fixed separately.

As a side-comment, as noted in #99684, one thing to try is to set a connection timeout instead of a statement timeout.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101254#-:-NTZ4U4fArNve8dRiNFh:bkqf8mu)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @herkolategan and @srosenberg)

**Review by renatolabs — COMMENTED** [review]
We should also run some roachtests on this branch (in TC) now that we're actually looking for dead nodes, to be sure.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101254#-:-NTZ5yMg9RUGwRQgXGuE:b7y6gae)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @herkolategan and @srosenberg)

**Review by smg260 — COMMENTED** [review]
Yes, it is a known issue, but is also now replicable (I'm not sure it was before). I don't see why this would not be useful, since 
-  `statement_timeout` works in the case of the query hanging, and propagates the cancellation correctly and
-  is also used in the consistency check directly after it
- without it, the code is still prone to hang and we miss out on the artifacts.

Also, the code doesn't hang when trying to connect to a live node, it's directly after when attempting to execute SQL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101254#-:-NTZ5rSy2tV6UtaPaIM8:btc75k2)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @herkolategan and @srosenberg)

**Review by renatolabs — APPROVED** [review]
I'm not saying it wouldn't be useful (it definitely would, the lack of artifacts is very frustrating). I guess I misunderstood your previous message when you said "This PR does not address that as investigation is ongoing"; I thought the `statement_timeout` wasn't enough to fix the hanging, and you were still looking into it. All I was saying was for us to merge this sooner while that investigation happened.

If we're in the clear re: hanging issues, then let's merge this!

Nit: update PR description to close both issues at the same time. (`Fixes A, B` doesn't work, unfortunately. It needs to be `Fixes A, fixes B`).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101254#-:-NTZCfpm6qnuwMtwEJwV:bd9xzs8)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @herkolategan and @srosenberg)

**Review by smg260 — COMMENTED** [review]
Poorly worded on my part. What I meant is the investigation  _to find the root cause_  is ongoing.

Will update description- thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101254#-:-NTZOwW_6bEzPx3CBCxt:b-z1dg6f)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @herkolategan and @srosenberg)

**Comment by smg260** [comment]
[Acceptance roachtests](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/9734871?buildTab=artifacts#%2Facceptance%2Fcluster-init%2Frun_1%2Fartifacts.zip;%2Facceptance%2Fmany-splits%2Frun_1%2Fartifacts.zip;%2Facceptance%2Freset-quorum%2Frun_1%2Fartifacts.zip). Teardown logs show node checks.

**Comment by smg260** [comment]
TFTR

bors r=renatolabs

**Comment by erikgrinaker** [comment]
I think this may have broken a bunch of roachtests. These tests all succeed, but then fail with `dead node(s) detected`. The tests stop nodes on their own, on purpose. See e.g. #102054 and #102057. Haven't dug into these to confirm though, but they all started failing when this merged so it lines up.

**Comment by smg260** [comment]
@erikgrinaker yep thanks. I'm adding an opt out for dead node validation.

**Pull request merged**
