### PR TITLE
sql: add SHOW CREATE TABLE

### PR DESCRIPTION
**Pull request by madelynnblue**
Needed for #6058

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6158)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/show.go, line 124 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6158#-KFkIadGAPiNu3Z7bypZ:-KFkIadGAPiNu3Z7byp_:-1453498381) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebf11f87b2f34fa356a0065a89309c8626192b62/sql/show.go#L124)):*
We also have `col.CheckExpr` now.

---

*[sql/show.go, line 163 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6158#-KFkJMMMw0olKH1s0kBh:-KFkJMMMw0olKH1s0kBi:1827440916) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebf11f87b2f34fa356a0065a89309c8626192b62/sql/show.go#L163)):*
You're quoting all identifiers which is valid but excessive. Any reason you're not doing something like:

```
buf.WriteString(parser.Name(n).String())
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6158)*

**Comment by petermattis** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[sql/show.go, line 157 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6158#-KFkKm1uANB1n7G-qexQ:-KFkKm1vWCkAP8Kj4Iyh:1165308315) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebf11f87b2f34fa356a0065a89309c8626192b62/sql/show.go#L157)):*
I believe this method could be implemented as:

```
  return parser.Names(names).String()
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6158)*

**Comment by mjibson** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[sql/show.go, line 124 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6158#-KFkIadGAPiNu3Z7bypZ:-KFkewUyESPQxQb3_1tg:1610000531) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebf11f87b2f34fa356a0065a89309c8626192b62/sql/show.go#L124)):*
Added.

---

*[sql/show.go, line 157 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6158#-KFkKm1uANB1n7G-qexQ:-KFkZ2OWsuNVdoY12nvD:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebf11f87b2f34fa356a0065a89309c8626192b62/sql/show.go#L157)):*
Done.

---

*[sql/show.go, line 163 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6158#-KFkJMMMw0olKH1s0kBh:-KFkZ48q4HWhdn0ciR-E:-1821468664) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebf11f87b2f34fa356a0065a89309c8626192b62/sql/show.go#L163)):*
Didn't know we had it. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6158)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6158#-:-KFlHuGJM5dNPoXS5weN:1417088721)*

**Comment by jseldess** [comment]
Docs updated with https://github.com/cockroachdb/docs/pull/558

**Pull request merged**
