### PR TITLE
cloudimpl: cache suffix in remote file sst wrapper

### PR DESCRIPTION
**Pull request by dt**
Reading SSTs starts with multiple tiny reads in offsets near the end of the file.
If we can read that whole region once and fulfill those reads from a cached buffer,
we can avoid repeated RPCs.

Release note: none.

### CODE REVIEW

**Review by miretskiy — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59478)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @dt)

___
*[pkg/ccl/storageccl/import.go, line 409 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59478#-MS3WoNN5b9p1wGAVwel:-MS3WoNN5b9p1wGAVwem:b-rcb23d) ([raw file](https://github.com/cockroachdb/cockroach/blob/56ec8f07b57c59bdfe370aa5a32e8f2cdf8e3561/pkg/ccl/storageccl/import.go#L409)):*
> ```Go
> // readAndCacheSuffix caches the `size` suffix of the file (which could the
> // whole file) for use by later ReadAt calls to avoid making additional RPCs.
> func (r *sstReader) readAndCacheSuffix(size int64) error {
> ```

Should we add a test for that?

Could be as simple as wrapping real sstReader w/ testReader which counts number of ReadAt calls, and then try reading a small sstable...

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59478)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @miretskiy)

___
*[pkg/ccl/storageccl/import.go, line 409 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59478#-MS3WoNN5b9p1wGAVwel:-MS9MubsD6yZIzP3UGL9:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/56ec8f07b57c59bdfe370aa5a32e8f2cdf8e3561/pkg/ccl/storageccl/import.go#L409)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Should we add a test for that?

Could be as simple as wrapping real sstReader w/ testReader which counts number of ReadAt calls, and then try reading a small sstable...

</blockquote></details>

done.

**Review by miretskiy — APPROVED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59478)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @miretskiy)

**Comment by dt** [comment]
TFTR!

bors r+

**Pull request merged**
