### PR TITLE
sql: help the user understand unsupported correlation

### LINKED ISSUE #24684: sql: equip cockroachdb to _detect_ attempts to use correlated queries
until CockroachDB supports correlated subqueries ( #3288, #24560  ) we want to tell users what's going on in error messages caused by a lack of support.

Currently a user attempting to run correlated subqueries will see either of the following:

- "column not found" when using a column from the surrounding query
- "no data source matches name" when using a table name as argument to a SRF that defines an implicit lateral join (cf #24560 )

We could teach CockroachDB to report better error messages:

- column not found: we could add some scope tracking during name resolution, which would help provide useful error messages even without supporting correlation outright.
- no data source matches name: mention "FROM" in the error message.

### PR DESCRIPTION
**Pull request by knz**
Fixes #24684.

Prior to this patch, a client trying to use an unsupported correlated
query would encounter an obscure error like "column v does not exist"
or "no data source matches prefix".

Given that the new optimizer code can determine whether a query is
correlated, we can use this information to enhance the error message.

Before:

```
> select * from pg_class a where exists (select * from pg_class b where a.oid = b.oid);
pq: no data source matches prefix: a

> select * from pg_class a where exists (select * from kv where v::oid = oid);
pq: column "oid" does not exist
```

After:

```
> select * from pg_class a where exists (select * from pg_class b where a.oid = b.oid);
pq: no data source matches prefix: a
HINT: some correlated subqueries are not supported yet - see
      #3288

> select * from pg_class a where exists (select * from kv where v::oid = oid);
pq: column "oid" does not exist
HINT: some correlated subqueries are not supported yet - see
      #3288
```

Note: some correlated queries do not benefit from this improvement,
specifically those for which the optimizer code aborts early before it
has detected correlation (e.g. because of some other unrelated
feature).

Release note (sql change): CockroachDB will now report a hint in the
error message if it encounters a correlated query that it does not
support yet.

### CODE REVIEW

**Review by rytaft — CHANGES_REQUESTED** [review]
:lgtm: Thanks for doing this!

> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27396#-:-LH8ZXKI6ZJxKe-E6OiD:b-pt8m11)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/optbuilder/builder.go, line 85 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27396#-LH8Z7XpAF846BWVgvHP:-LH8Z7Xq-twtcyP-Vmjl:b-s34w11) ([raw file](https://github.com/cockroachdb/cockroach/blob/a55d0255a33a5a4f62ca8715f49542f197e11a54/pkg/sql/opt/optbuilder/builder.go#L85)):*
> ```Go
> 	// UsingVirtualTable is set to true during semantic analysis if a
> 	// FROM clause refers to a virtual table.
> 	UsingVirtualTable bool
> ```

Add a TODO to remove this flag once virtual tables are supported

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27396)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/optbuilder/builder.go, line 85 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27396#-LH8Z7XpAF846BWVgvHP:-LH9053rEGhpN1uMKXDM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a55d0255a33a5a4f62ca8715f49542f197e11a54/pkg/sql/opt/optbuilder/builder.go#L85)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Add a TODO to remove this flag once virtual tables are supported
</blockquote></details>

Done.

**Comment by knz** [comment]
Thanks for your review!

bors r+

**Comment by knz** [comment]
@rytaft you'll need to complete the review to make a github "approved" checkmark.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 7 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27396#-:-LH90SePDqKkp4hljvTF:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by knz** [comment]
thank you!

bors r+

**Comment by knz** [comment]
failed because of a lint error. retrying.

bors r+

**Pull request merged**
