### PR TITLE
release-24.1: sql: include KV nodes and KV regions information

### PR DESCRIPTION
**Pull request by yuzefovich**
Backport:
  * 3/3 commits from "sql: add information about which KV nodes served read requests" (#124681)
  * 1/1 commits from "sql: include KV regions information" (#124888)
  * 1/1 commits from "sql: add kv nodes to makeDeterministic method" (#124950)

Please see individual PRs for details.

/cc @cockroachdb/release

Release justification: low-risk high benefit observability change.

### CODE REVIEW

**Comment by yuzefovich** [comment]
This was mostly a clean backport (only `sql/exec_log.go` and `distsql_misc` logic test had conflicts).

**Comment by yuzefovich** [comment]
Friendly ping @mgartner @DrewKimball. I think it'd be quite beneficial to backport this. This PR does touch non-trivial amount of code, so I could see the rationale with going through "full backport review".

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 5 of 7 files at r1, 58 of 58 files at r6, 16 of 16 files at r7, 55 of 55 files at r8, 15 of 15 files at r9, 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125070#-:-O-b8Zb85EqdtTbWEZFo:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by yuzefovich** [comment]
Friendly ping @mgartner

**Comment by yuzefovich** [comment]
Friendly ping @mgartner - this seems like a very beneficial to backport fix / improvement.

**Pull request closed without merging**
