### PR TITLE
sql/parser: Added current_schema keyword support.

### PR DESCRIPTION
**Pull request by CMajeri**
current_schema can be used as an alias for the current_schema() builtin.
It is used by some applications like Keycloak.

### CODE REVIEW

**Comment by jordanlewis** [comment]
Thanks for the contribution! This looks correct to me, but it's missing tests. Please add a test to `sql/parser/parse_test.go` - there should already be a similar one for current_timestamp, for instance.

---

Reviewed 4 of 4 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16921#-:-KoSd6OBKxX-5hp-7QJw:b-2rx6md)*

**Comment by jordanlewis** [comment]
Great - now could you please squash the two commits and rebase them instead of including merge commits? Then I think we'll be good to go.

**Comment by CMajeri** [comment]
Hi, I already squashed them didn't I? I can only see one commit in my PR.

**Comment by jordanlewis** [comment]
Yes, it looks good now. Before it showed several commits, perhaps it was a GitHub ui blip.

**Comment by knz** [comment]
:lgtm: 

---

Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16921#-:-KoTHP9bV7MsMKq0CwgB:bg7igkv)*

**Comment by knz** [comment]
@CMajeri thank you for your contribution!!
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
