### PR TITLE
sql/parser: encodeSQLIdent double quotes partially reserved keywords

### PR DESCRIPTION
**Pull request by eisenstatdavid**
encodeSQLIdent only quotes non-reserved keywords and keywords that cause
lookahead tokens to be generated, which causes statements like
`SELECT "full" FROM t` to be formatted improperly (`FULL` is a column
name keyword).

### CODE REVIEW

**Comment by mjibson** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/reserved_keywords.awk, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15852#-KjnnWFccfbLWQTryZc5:-KjnnWFccfbLWQTryZc6:bknqiiv) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6232d6b2b35ea581dc2b261a5e05d0b538d9fad/pkg/sql/parser/reserved_keywords.awk#L1)):*
> ```Awk
> /^col_name_keyword:/ {
> ```

Why does `unreserved_keyword` not need to be here too?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15852)*

**Comment by eisenstatdavid** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/reserved_keywords.awk, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15852#-KjnnWFccfbLWQTryZc5:-KjnoSSqHllh6EsgE8N4:b-1g2fyt) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6232d6b2b35ea581dc2b261a5e05d0b538d9fad/pkg/sql/parser/reserved_keywords.awk#L1)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Why does `unreserved_keyword` not need to be here too?
</blockquote></details>

If I did that, `SYSTEM` and `DATABASE` would get quotes, which would dramatically increase the footprint of this PR. In theory, unreserved keywords should be allowed everywhere that identifiers are (hence "unreserved"). This is close enough to true in practice; manual inspection of the occurrences of `IDENT` without `unreserved_keyword` in `sql.y` turns up the following exceptions:

1. use as a timezone (should be fine; potentially we could remove this exception)

2. use as the argument of `SHOW` (slightly problematic; `SHOW "DATABASES"`, which is normally yield a runtime error, comes back as `SHOW DATABASES`; there may be other issues)

3. use in `extract_arg` (should be fine)

4. use as a column alias without `AS` (fine since `.Format` always uses `AS`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15852)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/reserved_keywords.awk, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15852#-KjnnWFccfbLWQTryZc5:-KjnsoWUqomWC0cNwCjw:b-amoedy) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6232d6b2b35ea581dc2b261a5e05d0b538d9fad/pkg/sql/parser/reserved_keywords.awk#L1)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

If I did that, `SYSTEM` and `DATABASE` would get quotes, which would dramatically increase the footprint of this PR. In theory, unreserved keywords should be allowed everywhere that identifiers are (hence "unreserved"). This is close enough to true in practice; manual inspection of the occurrences of `IDENT` without `unreserved_keyword` in `sql.y` turns up the following exceptions:

1. use as a timezone (should be fine; potentially we could remove this exception)

2. use as the argument of `SHOW` (slightly problematic; `SHOW "DATABASES"`, which is normally yield a runtime error, comes back as `SHOW DATABASES`; there may be other issues)

3. use in `extract_arg` (should be fine)

4. use as a column alias without `AS` (fine since `.Format` always uses `AS`).
</blockquote></details>

Ok. I guess with the change in RSG to round-trip the formatted expressions, it would find if this ends up being a problem or not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15852#-:-Kjnt31phpS-ltxJtBc9:bnfp4nl)*

**Comment by eisenstatdavid** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/reserved_keywords.awk, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15852#-KjnnWFccfbLWQTryZc5:-KjntpPnqo0Li1WzzcWs:b-fjrw6c) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6232d6b2b35ea581dc2b261a5e05d0b538d9fad/pkg/sql/parser/reserved_keywords.awk#L1)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Ok. I guess with the change in RSG to round-trip the formatted expressions, it would find if this ends up being a problem or not.
</blockquote></details>

FWIW, I patched this change into my RSG fork and it's been smooth sailing as far as reparsing is concerned. I'm not sure that it tries hard enough to generate obnoxious identifiers though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15852)*

**Pull request merged**
