### PR TITLE
Move the time monotonicity checker to the HLC.

### LINKED ISSUE #5476: Move the time monotonicity checker to the HLC
As suggested by @bdarnell, in reaction to @BramGruneir's worries that the locking could influence performance and timing of tests.

"""
anything that cares about monotonicity should be using that anyway, and it’s already using a lock and doing a lot of similar work
"""

### PR DESCRIPTION
**Pull request by knz**
Fixes #5476.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5522)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[util/hlc/hlc.go, line 63 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5522#-KD_WCyE3xJgkHh5yp20:-KD_WCyE3xJgkHh5yp21:112752660) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9e6c2c801b68be29cde0074d20c987df2abaeb7/util/hlc/hlc.go#L63)):*
double space here

---

*[util/hlc/hlc.go, line 166 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5522#-KD_WKLFf3nHWZkk6Fe0:-KD_WKLFf3nHWZkk6Fe1:-324313586) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9e6c2c801b68be29cde0074d20c987df2abaeb7/util/hlc/hlc.go#L166)):*
no point in deferring this - this happens entirely under lock now.

---

*[util/hlc/hlc_test.go, line 178 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5522#-KD_WxEYhgk39-K9cUfi:-KD_WxEZ9dI1mQ9jQSOl:217852480) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9e6c2c801b68be29cde0074d20c987df2abaeb7/util/hlc/hlc_test.go#L178)):*
what's this?

package hlc contains manual clocks. there is no need to mess with timeutil here.

---

*[util/timeutil/time.go, line 29 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5522#-KD_W4Ytak4LHLlKDHkt:-KD_W4Ytak4LHLlKDHku:-1001079091) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9e6c2c801b68be29cde0074d20c987df2abaeb7/util/timeutil/time.go#L29)):*
can this be removed? I don't see why it's needed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5522)*

**Comment by knz** [comment]
Review status: 3 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[util/hlc/hlc.go, line 63 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5522#-KD_WCyE3xJgkHh5yp20:-KD_df8MVHhHr0z9cKuL:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9e6c2c801b68be29cde0074d20c987df2abaeb7/util/hlc/hlc.go#L63)):*
Done.

---

*[util/hlc/hlc.go, line 166 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5522#-KD_WKLFf3nHWZkk6Fe0:-KD_djHVm7rl_ZTCVZji:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9e6c2c801b68be29cde0074d20c987df2abaeb7/util/hlc/hlc.go#L166)):*
Done.

---

*[util/hlc/hlc_test.go, line 178 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5522#-KD_WxEYhgk39-K9cUfi:-KD_eyoAVtf5t5RWbVGK:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9e6c2c801b68be29cde0074d20c987df2abaeb7/util/hlc/hlc_test.go#L178)):*
Done.

---

*[util/timeutil/time.go, line 29 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5522#-KD_W4Ytak4LHLlKDHkt:-KD_e1fA9og9C9OQEVSC:-390937164) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9e6c2c801b68be29cde0074d20c987df2abaeb7/util/timeutil/time.go#L29)):*
That was your code :)
I think the idea was to avoid a closure allocation on the heap for the nowFunc. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5522)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[util/hlc/hlc_test.go, line 178 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5522#-KDdHjwmgGv3gSH5bM1x:-KDdHjwmgGv3gSH5bM1y:-1266845315) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2ca285229de26f149cb0b22170c421dfb7563fb/util/hlc/hlc_test.go#L178)):*
prefer calling `.Nanoseconds()` on the `time.Duration` (or just multiple by time.Nanoseconds directly) to casting to int64.

---

*[util/timeutil/time.go, line 29 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5522#-KD_W4Ytak4LHLlKDHkt:-KDdHxglN4gRPTMmvUoZ:-905720285) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9e6c2c801b68be29cde0074d20c987df2abaeb7/util/timeutil/time.go#L29)):*
I must be missing something, since I don't see any new allocations now that it's removed. Anyway, thanks.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5522#-:-KDdI5YJ0GkU7aDBo2Ap:1417088721)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[util/hlc/hlc_test.go, line 178 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5522#-KDdHjwmgGv3gSH5bM1x:-KDdxzSePF_PeTirXIvW:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2ca285229de26f149cb0b22170c421dfb7563fb/util/hlc/hlc_test.go#L178)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5522)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5522)*

**Comment by tamird** [comment]
Please avoid merging on red in the future.

**Pull request merged**
