### PR TITLE
server: cleanups around a tenant's metrics registry

### PR DESCRIPTION
**Pull request by andreimatei**
Please see individual commits.

Release note: None
Epic: None

### CODE REVIEW

**Comment by andreimatei** [comment]
First two commits are #97884.

**Review by dhartunian — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, 4 of 4 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97889)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @abarganier, and @andreimatei)

___
*[`pkg/server/tenant.go` line 620 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/97889#-NPUfCyM-JYUNNtyfeO5:-NPUfCyN8FqsNup2h8y3:b-id6mo7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ac48dc0c686ea5c5c8086f49df0adf5f0fadf3b/pkg/server/tenant.go#L620)):*
> ```Go
> 	// If there's a higher-level recorder, we link our metrics registry to it.
> 	if s.sqlCfg.NodeMetricsRecorder != nil {
> 		s.sqlCfg.NodeMetricsRecorder.AddTenantRegistry(s.sqlCfg.TenantID, s.registry)
> ```

Do we need to "unregister" the metrics if the tenant is stopped?

**Review by aadityasondhi — APPROVED** [review]
These changes are appreciated. I think you just need to `gen bazel` for CI but LGTM.

> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, 4 of 4 files at r4, 3 of 3 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97889#-:-NPZC29L3-XgPpe5ETg0:bf32mww)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @andreimatei)

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97889)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)

___
*[`pkg/server/tenant.go` line 620 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/97889#-NPUfCyM-JYUNNtyfeO5:-NPZG34S1dh-US8uJCBm:bg6w02v) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ac48dc0c686ea5c5c8086f49df0adf5f0fadf3b/pkg/server/tenant.go#L620)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Do we need to "unregister" the metrics if the tenant is stopped?
</blockquote></details>

Is there such a thing as the tenant being stopped independently from the host node?

**Review by dhartunian — APPROVED** [review]
:lgtm: I'm fine with merging without resolving the unregister discussion since that was a problem prior to the refactors as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97889#-:-NPsDhsODCh5igKoOLRm:b9xph6u)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier and @andreimatei)

___
*[`pkg/server/tenant.go` line 620 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/97889#-NPUfCyM-JYUNNtyfeO5:-NPsCsdl2Ta9sHdxK5Tc:bcspw8x) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ac48dc0c686ea5c5c8086f49df0adf5f0fadf3b/pkg/server/tenant.go#L620)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Is there such a thing as the tenant being stopped independently from the host node?
</blockquote></details>

via `ALTER TENANT x STOP SERVICE`?

**Review by knz — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, 4 of 4 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97889)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)

___
*[`pkg/server/tenant.go` line 620 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/97889#-NPUfCyM-JYUNNtyfeO5:-NPsHbFL1i4K9J5348aQ:bmd93bv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ac48dc0c686ea5c5c8086f49df0adf5f0fadf3b/pkg/server/tenant.go#L620)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

via `ALTER TENANT x STOP SERVICE`?
</blockquote></details>

Yes OK for merging this but we need a follow-up issue to handle this case. Can you file that issue and add a link here? Thanks

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97889)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)

___
*[`pkg/server/tenant.go` line 620 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/97889#-NPUfCyM-JYUNNtyfeO5:-NPsIvku7GVqZtLUuRK5:b-a9351o) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ac48dc0c686ea5c5c8086f49df0adf5f0fadf3b/pkg/server/tenant.go#L620)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Yes OK for merging this but we need a follow-up issue to handle this case. Can you file that issue and add a link here? Thanks
</blockquote></details>

maybe I can address this if it's easy - but I can't seem to find any code that deals with stopping a tenant server. Can someone point me to it or is the whole thing yet to be written?

**Review by aadityasondhi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97889)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)

___
*[`pkg/server/tenant.go` line 620 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/97889#-NPUfCyM-JYUNNtyfeO5:-NPskErEENZU3W-IQ0Ba:bfq6gvy) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ac48dc0c686ea5c5c8086f49df0adf5f0fadf3b/pkg/server/tenant.go#L620)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

maybe I can address this if it's easy - but I can't seem to find any code that deals with stopping a tenant server. Can someone point me to it or is the whole thing yet to be written?
</blockquote></details>

@dhartunian already had it implemented as part of my TSDB PR, which is in draft but I expect to have it ready for review this week. It will require some tweaking after this refactor lands. https://github.com/cockroachdb/cockroach/pull/98077/commits/28577fc3b0cb4c55f0904815becff0e85190439c#diff-8453981e212eb3eee4afbfde1f551dc981960870b369580d9b4f911b9108533cR180. 

I can look into where the stopping code is implemented, though. But I would prefer if this PR doesn't block because of it.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97889)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aadityasondhi, @abarganier, @dhartunian, and @knz)

___
*[`pkg/server/tenant.go` line 620 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/97889#-NPUfCyM-JYUNNtyfeO5:-NPstok52JzN2gGHDCzT:b-54fpmz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ac48dc0c686ea5c5c8086f49df0adf5f0fadf3b/pkg/server/tenant.go#L620)):*
<details><summary><i>Previously, aadityasondhi (Aaditya Sondhi) wrote…</i></summary><blockquote>

@dhartunian already had it implemented as part of my TSDB PR, which is in draft but I expect to have it ready for review this week. It will require some tweaking after this refactor lands. https://github.com/cockroachdb/cockroach/pull/98077/commits/28577fc3b0cb4c55f0904815becff0e85190439c#diff-8453981e212eb3eee4afbfde1f551dc981960870b369580d9b4f911b9108533cR180. 

I can look into where the stopping code is implemented, though. But I would prefer if this PR doesn't block because of it. 
</blockquote></details>

ack.
Opened https://github.com/cockroachdb/cockroach/issues/98100 and added a reference to it.

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97889#-:-NPt7n97EYzlsCLnuyDG:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aadityasondhi, @abarganier, @dhartunian, and @knz)

**Pull request merged**
