### PR TITLE
WIP: storage: add service definitions for CollectChecksum()

### PR DESCRIPTION
**Pull request by eisenstatdavid**
We're changing how consistency checks exchange snaphots, per #7739 and
the updated consistency checker RFC.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8589)

### CODE REVIEW

**Comment by tamird** [comment]
What's the point of merging this before there's any code that uses it?

**Comment by tamird** [comment]
Seems OK at a glance, but -1 on merging this by itself before there's code using it.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/api.proto, line 22 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8589#-KPJohyeiFtYT0gYV8NC:-KPJohyeiFtYT0gYV8ND:b-15e1qv) ([raw file](https://github.com/cockroachdb/cockroach/blob/bffd4dcba32c172ec3d450d3d10b0606708d694e/storage/api.proto#L22)):*
> ```protobuf
> 
> import "cockroach/roachpb/metadata.proto";
> import weak "cockroach/roachpb/internal_raft.proto";
> ```

"weak" is incorrect here. it is used for `gogo.proto` because that proto provides only compile-time annotations and is not needed at runtime.

---

*[storage/api.proto, line 78 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8589#-KPJoqkdQcS1gF_HHDBZ:-KPJoqkdQcS1gF_HHDB_:b-b4uyr5) ([raw file](https://github.com/cockroachdb/cockroach/blob/bffd4dcba32c172ec3d450d3d10b0606708d694e/storage/api.proto#L78)):*
> ```protobuf
> // blocks until the checksum is ready.
> message CollectChecksumRequest {
>   roachpb.ReplicaDescriptor replica = 1 [ (gogoproto.nullable = false) ];
> ```

throughout: spurious spaces after `[` and before `]`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8589#-:-KPJpF3oFqtNo4_FEtsH:b-gwyulu)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[storage/api.proto, line 105 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8589#-KPJrBtfsQLP_s3ExMwK:-KPJrBtfsQLP_s3ExMwL:b-ti34wn) ([raw file](https://github.com/cockroachdb/cockroach/blob/bffd4dcba32c172ec3d450d3d10b0606708d694e/storage/api.proto#L105)):*
> ```protobuf
>   // The respondent's snapshot, so that the requester can log a diff. Set if the
>   // ComputeChecksumRequest had snapshot = true.
>   RaftSnapshotData snapshot = 2;
> ```

Do we need to send everything in both directions? I would expect that at least the snapshot data would flow one way. According to the previous comment, if an inconsistency is found the respondent commits suicide; it's difficult to ensure that the requester gets the response in that case. And it seems redundant to log the diff on both sides. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8589)*

**Comment by RaduBerinde** [comment]
I don't think this builds.. You should run `make protobuf` and include the updated generated files in the commit.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[storage/api.proto, line 78 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8589#-KPL0WSlsiC1055xnA-a:-KPL0WSlsiC1055xnA-b:b-ow5qql) ([raw file](https://github.com/cockroachdb/cockroach/blob/bffd4dcba32c172ec3d450d3d10b0606708d694e/storage/api.proto#L78)):*
> ```protobuf
> // blocks until the checksum is ready.
> message CollectChecksumRequest {
>   roachpb.ReplicaDescriptor replica = 1 [ (gogoproto.nullable = false) ];
> ```

paren seems off here

---

*[storage/api.proto, line 82 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8589#-KPL0wg56Q1Kd6nP0x_w:-KPL0wg56Q1Kd6nP0x_x:bs6vug2) ([raw file](https://github.com/cockroachdb/cockroach/blob/bffd4dcba32c172ec3d450d3d10b0606708d694e/storage/api.proto#L82)):*
> ```protobuf
>   // checksum_id identifies the corresponding ComputeChecksumRequest.
>   bytes checksum_id = 2 [
>     (gogoproto.nullable) = false,
> ```

[nit] in other proto files, we put the first item on the same line, and aligned the rest under that one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8589#-:-KPL0lAHSYemf0yuRZQ2:b-9a8brt)*

**Comment by eisenstatdavid** [comment]
Ran make protobuf.

---

Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[storage/api.proto, line 22 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8589#-KPJohyeiFtYT0gYV8NC:-KQM-miJz1pTgZH6FeKr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d897ca43ad95df50fa1ad79667388e5240e21e8f/storage/api.proto#L22)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> "weak" is incorrect here. it is used for `gogo.proto` because that proto provides only compile-time annotations and is not needed at runtime.
</details>
Done.

---

*[storage/api.proto, line 78 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8589#-KPJoqkdQcS1gF_HHDBZ:-KQM-ndmG1F3uC_bZMym:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d897ca43ad95df50fa1ad79667388e5240e21e8f/storage/api.proto#L78)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> throughout: spurious spaces after `[` and before `]`
</details>
Done.

---

*[storage/api.proto, line 78 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8589#-KPL0WSlsiC1055xnA-a:-KQM-qYsfgjilb0zJM9n:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d897ca43ad95df50fa1ad79667388e5240e21e8f/storage/api.proto#L78)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> paren seems off here
</details>
Done.

---

*[storage/api.proto, line 82 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8589#-KPL0wg56Q1Kd6nP0x_w:-KQM-v8470DCDNTshNxr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d897ca43ad95df50fa1ad79667388e5240e21e8f/storage/api.proto#L82)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> [nit] in other proto files, we put the first item on the same line, and aligned the rest under that one
</details>
Done.

---

*[storage/api.proto, line 105 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8589#-KPJrBtfsQLP_s3ExMwK:-KQM-ygW-rNolVowS91A:b6dzhfi) ([raw file](https://github.com/cockroachdb/cockroach/blob/d897ca43ad95df50fa1ad79667388e5240e21e8f/storage/api.proto#L105)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Do we need to send everything in both directions? I would expect that at least the snapshot data would flow one way. According to the previous comment, if an inconsistency is found the respondent commits suicide; it's difficult to ensure that the requester gets the response in that case. And it seems redundant to log the diff on both sides. 
</details>
Switched from Collect to Report, with only the inconsistent replica being sent the initiator's snapshot and logging the diffs. I'll update the RFC later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8589#-:-KQM0VvJ-cgZ2a3epp6V:b-u370kp)*

**Comment by tamird** [comment]
Is this meant to go on master?

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8589#-:-KQM26am4CDtSIDO5fBT:bvlnfv5)*

**Comment by eisenstatdavid** [comment]
I fail at git. I'll send this out again when I have an implementation ready.

**Pull request closed without merging**
