### PR TITLE
roachtest: Use `rocksdb debug` in `inconsistency` roachtest when possible

### LINKED ISSUE #55931: roachtest: inconsistency failed
[(roachtest).inconsistency failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2390471&tab=buildLog) on [release-20.1@46f58ba521f73422c2524d6bff069ffb33ac9541](https://github.com/cockroachdb/cockroach/commits/46f58ba521f73422c2524d6bff069ffb33ac9541):

```
The test failed on branch=release-20.1, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/inconsistency/run_1
	inconsistency.go:107,test_runner.go:755: expected a node to crash

```

<details><summary>More</summary><p>

Artifacts: [/inconsistency](https://teamcity.cockroachdb.com/viewLog.html?buildId=2390471&tab=artifacts#/inconsistency)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Ainconsistency.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #56173: roachtest: inconsistency failed
[(roachtest).inconsistency failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2408362&tab=buildLog) on [release-20.2@150c5918fb6e28e0ea5bfa4e8e94088986fbbf98](https://github.com/cockroachdb/cockroach/commits/150c5918fb6e28e0ea5bfa4e8e94088986fbbf98):

```
The test failed on branch=release-20.2, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/inconsistency/run_1
	inconsistency.go:107,test_runner.go:755: expected a node to crash

```

<details><summary>More</summary><p>

Artifacts: [/inconsistency](https://teamcity.cockroachdb.com/viewLog.html?buildId=2408362&tab=artifacts#/inconsistency)
Related:
- #56039 roachtest: inconsistency failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-master](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-master) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

- #55931 roachtest: inconsistency failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-release-20.1](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-20.1) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Ainconsistency.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by nvb**
Fixes #55931.
Fixes #56173.

The `cockroach debug pebble db set` command did not exist in earlier releases,
so we use `cockroach debug rocksdb put` instead.

### CODE REVIEW

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56195#-:-ML8cZyJ0BvA0r7RjHCM:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/cmd/roachtest/inconsistency.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56195#-ML8c_O39uOvimBVgJuh:-ML8c_O39uOvimBVgJui:bc2wan1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d7901bd49e94f46c038e263906a46bf69385318/pkg/cmd/roachtest/inconsistency.go#L82)):*
> ```Go
> 	}
> 	c.Run(ctx, c.Node(1), fmt.Sprintf("./cockroach debug %s "+
> 		"hex:016b1202000174786e2d0000000000000000000000000000000000 "+
> ```

You might also need to replace the `hex:` prefix with `0x` for the rocksdb command. At least, that's how it was here: https://github.com/cockroachdb/cockroach/commit/8732d4281a7f913c53a5a069932d9caa222dcd57

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56195)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal)

___
*[pkg/cmd/roachtest/inconsistency.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56195#-ML8c_O39uOvimBVgJuh:-ML8dTin183QNe6DIBZD:b-ovind) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d7901bd49e94f46c038e263906a46bf69385318/pkg/cmd/roachtest/inconsistency.go#L82)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

You might also need to replace the `hex:` prefix with `0x` for the rocksdb command. At least, that's how it was here: https://github.com/cockroachdb/cockroach/commit/8732d4281a7f913c53a5a069932d9caa222dcd57
</blockquote></details>

Great catch. Done.

**Comment by itsbilal** [comment]
This should actually be unnecessary now that #55899 is in. But either way, looks good.

**Comment by nvanbenschoten** [comment]
Nice! Things look good on [`release-20.2`](https://github.com/cockroachdb/cockroach/blob/abeb6a501e00a23477aab67951a9b511b7ce7ee5/pkg/cmd/roachtest/inconsistency.go). Happy to close this.

**Pull request closed without merging**
