### PR TITLE
sql: add crdb_internal.invalid_descriptors

### PR DESCRIPTION
**Pull request by spaskob**
This commit adds a new crdb_internal table that pulls all of the
descriptors for a given db context and validates them all (including
their cross-database references). To use it one can do the following to
validate all of the tables in the current database:

```
SELECT * FROM crdb_internal.invalid_descriptors
```

To validate all descriptors in all databases, one uses the special ""
database context like in all other crdb_internal tables. That looks
like:

```
SELECT * FROM "".crdb_internal.invalid_descriptors
```

Touches #53571.
Touches #53754.

Release justification: low risk, high benefit changes to existing
functionality

Release note (sql change): Added a new virtual table
`crdb_internal.invalid_descriptors` which runs validations on
descriptors in the database context and reports any errors.

### CODE REVIEW

**Review by spaskob — COMMENTED** [review]
PTAL

**Review by ajwerner — COMMENTED** [review]
It would be nice to have some testing. I'd imagine a test that injects some invalid descriptors and then runs the command to ensure that it finds them. 

I also think you're going to need to regenerate some of the logic tests. 

> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54017#-:-MGnHkSSBIgZrG_yJs4y:bekj5hk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/crdb_internal.go, line 3669 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54017#-MGnHEOc6bssHUi1_SlE:-MGnHEOc6bssHUi1_SlF:b-6k0h5g) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f2df0b1838bf7d516b93c06e182b46f03aa5ec0/pkg/sql/crdb_internal.go#L3669)):*
> ```Go
> 		// database. To deal with this, we fall through.
> 		// TODO(spaskob): we can also validate type descriptors. Add a new function
> 		// `forEachTypeDescAllWithTableLookup` and the results to this table.
> ```

It should be trivially easy to extend https://github.com/cockroachdb/cockroach/blob/11d9e0189332d6f5a02938374587ffd96672467b/pkg/sql/information_schema.go#L1645

Also, don't stress about reusing that `internalLookupCtx` as there's already caching of the fetching of descriptors.

**Review by ajwerner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54017)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @spaskob)

___
*[pkg/sql/crdb_internal.go, line 3656 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54017#-MGnI1mEEJ4Q5iONxxmS:-MGnI1mF2N1tUcKgAuLs:b-vxs95k) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f2df0b1838bf7d516b93c06e182b46f03aa5ec0/pkg/sql/crdb_internal.go#L3656)):*
> ```Go
> 	comment: `virtual table to validate descriptors`,
> 	schema: `
> CREATE TABLE crdb_internal.invalid_tables (
> ```

if we're going to end up validating types, let's call this `invalid_objects`
___
*[pkg/sql/crdb_internal.go, line 3661 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54017#-MGnI5nS1Rq_laQzkXC9:-MGnI5nS1Rq_laQzkXCA:b-27e5eu) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f2df0b1838bf7d516b93c06e182b46f03aa5ec0/pkg/sql/crdb_internal.go#L3661)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 
>   database_name STRING,
>   schema_name   STRING,
>   obj_name 	    STRING,
>   error         STRING
> ```
</details>

nit: properly align this

**Review by spaskob — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54017)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @miretskiy)

___
*[pkg/sql/crdb_internal.go, line 3656 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54017#-MGnI1mEEJ4Q5iONxxmS:-MIO3aUCA_RNTr6fPIBU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f2df0b1838bf7d516b93c06e182b46f03aa5ec0/pkg/sql/crdb_internal.go#L3656)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

if we're going to end up validating types, let's call this `invalid_objects`
</blockquote></details>

Done.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54017)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @miretskiy, and @spaskob)

___
*[pkg/ccl/backupccl/restore_planning.go, line 1052 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54017#-MITt13C1S3TONjkNceo:-MITt13C1S3TONjkNcep:b-p6btcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/670f904e93d409449ce78290303649190ac75ef7/pkg/ccl/backupccl/restore_planning.go#L1052)):*
> ```Go
> 	ctx context.Context, txn *kv.Txn, codec keys.SQLCodec,
> ) ([]string, error) {
> 	allDescs, err := catalogkv.GetAllDescriptors(ctx, txn, codec, true)
> ```

nit: per the style guide, please add a comment naming the parameter `/* validate */`
___
*[pkg/ccl/backupccl/targets.go, line 702 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54017#-MITtC0iE0KAs93jJaQD:-MITtC0iE0KAs93jJaQE:b-p6btcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/670f904e93d409449ce78290303649190ac75ef7/pkg/ccl/backupccl/targets.go#L702)):*
> ```Go
> 		func(ctx context.Context, txn *kv.Txn) (err error) {
> 			txn.SetFixedTimestamp(ctx, asOf)
> 			allDescs, err = catalogkv.GetAllDescriptors(ctx, txn, keys.SystemSQLCodec, true)
> ```

nit: per the style guide, please add a comment naming the parameter `/* validate */`
___
*[pkg/sql/crdb_internal.go, line 264 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54017#-MITtEasCqoUEj3GLnXK:-MITtEasCqoUEj3GLnXL:b-p6btcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4986289ecda06a37edfe9f4592f5da628bdd0dd2/pkg/sql/crdb_internal.go#L264)):*
> ```Go
> 		row := make(tree.Datums, 14)
> 		worker := func(pusher rowPusher) error {
> 			descs, err := p.Descriptors().GetAllDescriptors(ctx, p.txn, true)
> ```

nit: per the style guide, please add a comment naming the parameter `/* validate */`
___
*[pkg/sql/crdb_internal.go, line 427 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54017#-MITtFBW066G9AhjZfjR:-MITtFBX6tYMBHTcxBS6:b-p6btcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4986289ecda06a37edfe9f4592f5da628bdd0dd2/pkg/sql/crdb_internal.go#L427)):*
> ```Go
> )`,
> 	populate: func(ctx context.Context, p *planner, _ *dbdesc.Immutable, addRow func(...tree.Datum) error) error {
> 		descs, err := p.Descriptors().GetAllDescriptors(ctx, p.txn, true)
> ```

nit: per the style guide, please add a comment naming the parameter `/* validate */`
___
*[pkg/sql/crdb_internal.go, line 2162 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54017#-MITtFr77kr5QUFoYkMX:-MITtFr77kr5QUFoYkMY:b-p6btcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4986289ecda06a37edfe9f4592f5da628bdd0dd2/pkg/sql/crdb_internal.go#L2162)):*
> ```Go
> 		sequenceDep := tree.NewDString("sequence")
> 		interleaveDep := tree.NewDString("interleave")
> 		return forEachTableDescAllWithTableLookup(ctx, p, dbContext, hideVirtual, true,
> ```

nit: per the style guide, please add a comment naming the parameter `/* validate */`
___
*[pkg/sql/crdb_internal.go, line 2439 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54017#-MITtGPo0vi7E6ZcYyy4:-MITtGPo0vi7E6ZcYyy5:b-p6btcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4986289ecda06a37edfe9f4592f5da628bdd0dd2/pkg/sql/crdb_internal.go#L2439)):*
> ```Go
> 			return nil, nil, err
> 		}
> 		descs, err := p.Descriptors().GetAllDescriptors(ctx, p.txn, true)
> ```

nit: per the style guide, please add a comment naming the parameter `/* validate */`
___
*[pkg/sql/crdb_internal.go, line 3671 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54017#-MITtXPi8jWfzB3TpG1i:-MITtXPi8jWfzB3TpG1j:bnzkj1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/4986289ecda06a37edfe9f4592f5da628bdd0dd2/pkg/sql/crdb_internal.go#L3671)):*
> ```Go
> 		// The internalLookupContext will only have descriptors in the current
> 		// database. To deal with this, we fall through.
> 		// TODO(spaskob): we can also validate type descriptors. Add a new function
> ```

it would also be great to validate the structure of `system.namespace`. I'm not sure whether that belongs here or elsewher.
___
*[pkg/sql/crdb_internal.go, line 3673 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54017#-MITtSLX58hFfN82a2jL:-MITtSLX58hFfN82a2jM:b-p6btcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4986289ecda06a37edfe9f4592f5da628bdd0dd2/pkg/sql/crdb_internal.go#L3673)):*
> ```Go
> 		// TODO(spaskob): we can also validate type descriptors. Add a new function
> 		// `forEachTypeDescAllWithTableLookup` and the results to this table.
> 		return forEachTableDescAllWithTableLookup(ctx, p, dbContext, hideVirtual, false, func(
> ```

nit: per the style guide, please add a comment naming the parameter `/* validate */`
___
*[pkg/sql/drop_role.go, line 149 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54017#-MITtR1s7aRKL4YY3ure:-MITtR1s7aRKL4YY3urf:b-p6btcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/670f904e93d409449ce78290303649190ac75ef7/pkg/sql/drop_role.go#L149)):*
> ```Go
> 	// at all _visible_ descriptors, not just those on which the current
> 	// user has permission.
> 	descs, err := params.p.Descriptors().GetAllDescriptors(params.ctx, params.p.txn, true)
> ```

nit: per the style guide, please add a comment naming the parameter `/* validate */`
___
*[pkg/sql/information_schema.go, line 1608 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54017#-MITtPAzAPk9EgC7SQrU:-MITtPAzAPk9EgC7SQrV:b-p6btcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/670f904e93d409449ce78290303649190ac75ef7/pkg/sql/information_schema.go#L1608)):*
> ```Go
> 	ctx context.Context, p *planner, db *dbdesc.Immutable, fn func(sc catalog.ResolvedSchema) error,
> ) error {
> 	schemaNames, err := getSchemaNames(ctx, p, db, false)
> ```

nit: per the style guide, please add a comment naming the parameter `/* validate */`
___
*[pkg/sql/information_schema.go, line 1687 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54017#-MITtOnz8seJJTAOl9ml:-MITtOnz8seJJTAOl9mm:b-cdim38) ([raw file](https://github.com/cockroachdb/cockroach/blob/670f904e93d409449ce78290303649190ac75ef7/pkg/sql/information_schema.go#L1687)):*
> ```Go
> 	var dbDescs []*dbdesc.Immutable
> 	if dbContext == nil {
> 		allDbDescs, err := p.Descriptors().GetAllDatabaseDescriptors(ctx, p.txn, false)
> ```

nit: per the style guide, please add a comment naming the parameter `/* allowMissingDesc */`
___
*[pkg/sql/information_schema.go, line 1696 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54017#-MITtOQ0-vqtCybVvnK2:-MITtOQ0-vqtCybVvnK3:b-p6btcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/670f904e93d409449ce78290303649190ac75ef7/pkg/sql/information_schema.go#L1696)):*
> ```Go
> 		// with privileges from kv.
> 		fetchedDbDesc, err := catalogkv.GetDatabaseDescriptorsFromIDs(
> 			ctx, p.txn, p.ExecCfg().Codec, []descpb.ID{dbContext.GetID()}, false,
> ```

nit: per the style guide, please add a comment naming the parameter `/* validate */`
___
*[pkg/sql/information_schema.go, line 1728 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54017#-MITtMGy1QUP5iKuLnKi:-MITtMGy1QUP5iKuLnKj:b-p6btcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/670f904e93d409449ce78290303649190ac75ef7/pkg/sql/information_schema.go#L1728)):*
> ```Go
> 	fn func(db *dbdesc.Immutable, sc string, typ *typedesc.Immutable) error,
> ) error {
> 	descs, err := p.Descriptors().GetAllDescriptors(ctx, p.txn, true)
> ```

nit: per the style guide, please add a comment naming the parameter `/* validate */`
___
*[pkg/sql/information_schema.go, line 1732 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54017#-MITtNpR1oRkBspU8SbA:-MITtNpS1AzVDOgPEzZg:b-p6btcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/670f904e93d409449ce78290303649190ac75ef7/pkg/sql/information_schema.go#L1732)):*
> ```Go
> 		return err
> 	}
> 	schemaNames, err := getSchemaNames(ctx, p, dbContext, false)
> ```

nit: per the style guide, please add a comment naming the parameter `/* validate */`
___
*[pkg/sql/information_schema.go, line 1808 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54017#-MITtjCP6XDVy7i0AR7H:-MITtjCP6XDVy7i0AR7I:b-p6btcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/670f904e93d409449ce78290303649190ac75ef7/pkg/sql/information_schema.go#L1808)):*
> ```Go
> ) error {
> 	return forEachTableDescAllWithTableLookup(ctx,
> 		p, dbContext, virtualOpts, true,
> ```

nit: per the style guide, please add a comment naming the parameter `/* validate */`
___
*[pkg/sql/information_schema.go, line 1852 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54017#-MITtkB9906dVAQYt_aM:-MITtkB9906dVAQYt_aN:b-p6btcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/670f904e93d409449ce78290303649190ac75ef7/pkg/sql/information_schema.go#L1852)):*
> ```Go
> ) error {
> 	return forEachTableDescWithTableLookupInternal(
> 		ctx, p, dbContext, virtualOpts, false /* allowAdding */, true, fn,
> ```

nit: per the style guide, please add a comment naming the parameter `/* validate */`
___
*[pkg/sql/catalog/catalogkv/catalogkv.go, line 160 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54017#-MITu4RU1eOHOvz7f_yc:-MITu4RV-ADVicqg0vUT:b-p6btcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/670f904e93d409449ce78290303649190ac75ef7/pkg/sql/catalog/catalogkv/catalogkv.go#L160)):*
> ```Go
> 		desc, err = unwrapDescriptorMutable(ctx, dg, ts, raw)
> 	} else {
> 		desc, err = unwrapDescriptor(ctx, dg, ts, raw, true)
> ```

nit: per the style guide, please add a comment naming the parameter `/* validate */`
___
*[pkg/sql/catalog/catalogkv/catalogkv.go, line 364 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54017#-MITu5b4AdcwRKvk6rE4:-MITu5b4AdcwRKvk6rE5:b-p6btcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/670f904e93d409449ce78290303649190ac75ef7/pkg/sql/catalog/catalogkv/catalogkv.go#L364)):*
> ```Go
> // created by the user (i.e. not present when the cluster started).
> func CountUserDescriptors(ctx context.Context, txn *kv.Txn, codec keys.SQLCodec) (int, error) {
> 	allDescs, err := GetAllDescriptors(ctx, txn, codec, true)
> ```

nit: per the style guide, please add a comment naming the parameter `/* validate */`
___
*[pkg/sql/catalog/catalogkv/catalogkv.go, line 642 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54017#-MITu7My23PhzKAdrOUm:-MITu7My23PhzKAdrOUn:b-p6btcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/670f904e93d409449ce78290303649190ac75ef7/pkg/sql/catalog/catalogkv/catalogkv.go#L642)):*
> ```Go
> 	ctx context.Context, txn *kv.Txn, codec keys.SQLCodec, ids []descpb.ID,
> ) ([]*schemadesc.Immutable, error) {
> 	descs, err := getDescriptorsFromIDs(ctx, txn, codec, ids, false)
> ```

nit: per the style guide, please add a comment naming the parameter `/* validate */`

**Review by spaskob — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54017)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @miretskiy)

___
*[pkg/sql/crdb_internal.go, line 3671 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54017#-MITtXPi8jWfzB3TpG1i:-MIU5jCZ5GU0wYDMgfQ1:b-cjk6f3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4986289ecda06a37edfe9f4592f5da628bdd0dd2/pkg/sql/crdb_internal.go#L3671)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

it would also be great to validate the structure of `system.namespace`. I'm not sure whether that belongs here or elsewher.
</blockquote></details>

I agree - I suggest we do this in a principled way. There are two options:
1. Improve table validation to also check the entries in `system.namespace`.
2. Refactor this function https://github.com/cockroachdb/cockroach/blob/5c2c632aaf930a2c9a092871af949e6bfdb68a80/pkg/sql/doctor/doctor.go#L108 so that it can be used in the context of the virtual table for invalid objects.

Either approach would require some thought and refactoring of the descriptor code.

**Review by ajwerner — APPROVED** [review]
Looks like there's one more zip test to fix, then :lgtm: 

> Reviewed 1 of 14 files at r3, 3 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54017#-:-MIZW-jEEVG581ac8SaA:b1lorej)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @miretskiy, and @spaskob)

___
*[pkg/sql/crdb_internal.go, line 3671 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54017#-MITtXPi8jWfzB3TpG1i:-MIZVaxH1jrKv4qmlx1a:be472j1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4986289ecda06a37edfe9f4592f5da628bdd0dd2/pkg/sql/crdb_internal.go#L3671)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

I agree - I suggest we do this in a principled way. There are two options:
1. Improve table validation to also check the entries in `system.namespace`.
2. Refactor this function https://github.com/cockroachdb/cockroach/blob/5c2c632aaf930a2c9a092871af949e6bfdb68a80/pkg/sql/doctor/doctor.go#L108 so that it can be used in the context of the virtual table for invalid objects.

Either approach would require some thought and refactoring of the descriptor code.
</blockquote></details>

sounds good, we should file an issue to follow up with this work. 
___
*[pkg/sql/crdb_internal.go, line 266 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/54017#-MIZVyF5AQxd_S2MO9Bf:-MIZVyF5AQxd_S2MO9Bg:b9we1dr) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aa1a62392833edca5a7a3b9d0a7bbf777e807ab/pkg/sql/crdb_internal.go#L266)):*
> ```Go
> 		row := make(tree.Datums, 14)
> 		worker := func(pusher rowPusher) error {
> 			descs, err := p.Descriptors().GetAllDescriptors(ctx, p.txn, true)
> ```

nit: annotate the booleans in this file.

**Pull request merged**
