### PR TITLE
sql: remove fake index and statistics collectors pg_catalog tables

### PR DESCRIPTION
**Pull request by RichardJCai**
Release note (sql change): Remove pg_catalog tables that were mistakenly added,
notably all tables that end in _index that are not pg_catalog.pg_classes and all
statistics collector tables that are not pg_stat_activity. 

Removing pg statistics collector tables since they are somewhat different from regular pg_catalog tables and it's unlikely for us to implement them. Accessing them will simply error.

`pg_metadata_test.go` has not yet been updating to reflect that the _index tables should not actually be tables.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
how did you identify the ones to remove?

can we update the diff tool / codegen tool to ignore these unneeded tables?

**Review by mnovelodou — COMMENTED** [review]
I created the following issue and assigned it to myself:
https://github.com/cockroachdb/cockroach/issues/61860

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61794#-:-MVXWPSGEnFYbYOvFalO:b6hasa)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by rafiss — APPROVED** [review]
lgtm after updating logic tests

**Comment by RichardJCai** [comment]
TFTR 
bors r=rafiss

**Pull request merged**
