### PR TITLE
sql/tree: desugar IS/IS NOT to IS {NOT} DISTINCT FROM during parsing

### LINKED ISSUE #20482: sql/tree: desugar IS/IS NOT to IS {NOT} DISTINCT FROM during parsing
See https://github.com/cockroachdb/cockroach/pull/20346#issuecomment-348344217.

After #20346 is merged we'll be normalizing IS/IS NOT to IS NOT DISTINCT FROM/IS DISTINCT FROM. We could then take a step further and remove the `tree.Is` and `tree.IsNot` operators entirely and desugar `IS/IS NOT` expressions directly to `tree.Is{Not}DistinctFrom`. 

While doing that, we may want to maintain some state so that strings can round trip through our AST. An alternative is to that (as suggested in https://github.com/cockroachdb/cockroach/pull/20346#issuecomment-348488933) would be to format these comparisons using `IS/IS NOT` whenever possible (based on the right-hand operand).

cc. @knz @RaduBerinde

### PR DESCRIPTION
**Pull request by yuhit**
Fixes #20482

Desugar IS/IS NOT expressions to tree.Is{Not}DistinctFrom.
Format IS DISTINCT FROM/IS NOT DISTINCT FROM comparisons using IS/IS NOT when the right operand is NULL.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
Very very good work. Thank you very much for your contribution.

Just a little nit below and this will be good to merge.

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/sem/tree/expr.go, line 395 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20982#-L0sisrvF2kJYtFexnJE:-L0sisrvF2kJYtFexnJF:b43nedr) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8071acab69d065ea41408413638610738dacfcb/pkg/sql/sem/tree/expr.go#L395)):*
> ```Go
> func (node *ComparisonExpr) Format(buf *bytes.Buffer, f FmtFlags) {
> 	opStr := node.Operator.String()
> 	if node.Operator == IsDistinctFrom && node.TypedRight() == DNull {
> ```

Use `node.Right == DNull`, it's simpler, valid, and also highlights that the expression can be pretty-printed even before type checking has occurred.

---

*[pkg/sql/sem/tree/expr.go, line 397 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20982#-L0sj1_YXVq7_zXoFbdw:-L0sj1_YXVq7_zXoFbdx:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8071acab69d065ea41408413638610738dacfcb/pkg/sql/sem/tree/expr.go#L397)):*
> ```Go
> 	if node.Operator == IsDistinctFrom && node.TypedRight() == DNull {
> 		opStr = "IS NOT"
> 	} else if node.Operator == IsNotDistinctFrom && node.TypedRight() == DNull {
> ```

ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20982#-:-L0sj6EW5Mqm1XT9eAfI:b-8c3diu)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/sem/tree/expr.go, line 395 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20982#-L0sjL9NIP5YfbmB16w2:-L0sjL9OvJUSUoUZO3wj:b2b4in4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8071acab69d065ea41408413638610738dacfcb/pkg/sql/sem/tree/expr.go#L395)):*
> ```Go
> func (node *ComparisonExpr) Format(buf *bytes.Buffer, f FmtFlags) {
> 	opStr := node.Operator.String()
> 	if node.Operator == IsDistinctFrom && node.TypedRight() == DNull {
> ```

I would also recommend to simplify `IS DISTINCT FROM` to `IS` here for boolean values, not just NULL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20982)*

**Comment by RaduBerinde** [comment]
This is great, thanks!

---

Review status: 11 of 12 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20982#-:-L0uUJxXWmPJyt2wBfkr:b-g1it74)*

**Comment by yuhit** [comment]
@knz @RaduBerinde I have changed the code.

**Comment by knz** [comment]
Yes! Perfect. Thank you!
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20982#-:-L0xP3yqmvDZq9jTL1ml:b-p4a0gw)*

**Pull request merged**
