### PR TITLE
opt: support CANCEL/RESUME/STOP JOBS and CANCEL QUERIES/SESSIONS

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: support CANCEL/RESUME/STOP JOBS

Support these flavors of the `ControlJobs` node as a `ControlJobs`
operator.

Release note: None

#### opt: support CANCEL QUERIES and CANCEL SESSIONS

Release note: None

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
Nicely done. My main question is around testing of physical props.

> Reviewed 17 of 17 files at r1, 15 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38936#-:-Lk3YLZs9D-pBxm01mLX:b-mhctbn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj and @RaduBerinde)

___
*[pkg/sql/opt/exec/execbuilder/statement.go, line 243 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38936#-Lk3VKk55Azk60S2h4AU:-Lk3VKk55Azk60S2h4AV:baho6z1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3e0d5e19c8974a41c0c4a4686467648c0ee4381/pkg/sql/opt/exec/execbuilder/statement.go#L243)):*
> ```Go
> 		return execPlan{}, err
> 	}
> 	// ControlJobs returns no columns.
> ```

update comment
___
*[pkg/sql/opt/exec/execbuilder/statement.go, line 256 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38936#-Lk3VLrD9HCS0j1-_cVh:-Lk3VLrD9HCS0j1-_cVi:baho6z1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3e0d5e19c8974a41c0c4a4686467648c0ee4381/pkg/sql/opt/exec/execbuilder/statement.go#L256)):*
> ```Go
> 		return execPlan{}, err
> 	}
> 	// ControlJobs returns no columns.
> ```

update comment
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 772 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38936#-Lk3V_9lExlvqCCLBX5F:-Lk3V_9lExlvqCCLBX5G:b-d0dm56) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3e0d5e19c8974a41c0c4a4686467648c0ee4381/pkg/sql/opt/memo/logical_props_builder.go#L772)):*
> ```Go
> 
> func (b *logicalPropsBuilder) buildCancelQueriesProps(
> 	ctl *CancelQueriesExpr, rel *props.Relational,
> ```

[nit] maybe use a diff variable name like `cancel`?
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 779 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38936#-Lk3VgtY2esahZfh7bYG:-Lk3VgtY2esahZfh7bYH:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3e0d5e19c8974a41c0c4a4686467648c0ee4381/pkg/sql/opt/memo/logical_props_builder.go#L779)):*
> ```Go
> 
> func (b *logicalPropsBuilder) buildCancelSessionsProps(
> 	ctl *CancelSessionsExpr, rel *props.Relational,
> ```

ditto
___
*[pkg/sql/opt/ops/statement.opt, line 172 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38936#-Lk3UkDL0jfxDEmJzRPB:-Lk3UkDMEtabADPm-GOb:b-ui6yg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3e0d5e19c8974a41c0c4a4686467648c0ee4381/pkg/sql/opt/ops/statement.opt#L172)):*
> ```
>     # Props stores the required physical properties for the input
>     # expression.
>     Props    PhysProps
> ```

Are these physical props being tested at all?
___
*[pkg/sql/opt/optbuilder/misc_statements.go, line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38936#-Lk3XWav-T-wsw78c7nt:-Lk3WU3z1YkNmD7e-lSw:bp7v15o) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3e0d5e19c8974a41c0c4a4686467648c0ee4381/pkg/sql/opt/optbuilder/misc_statements.go#L60)):*
> ```Go
> 		1, /* minPrefix */
> 	)
> 	outScope = inScope.push()
> ```

I'm having a bit of trouble understanding how the scoping works here. Is it ok to use `inScope.push()` when we are passing a blank scope above?

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38936#-:-Lk4SUkJE7lDj0nSE09r:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj and @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/statement.go, line 243 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38936#-Lk3VKk55Azk60S2h4AU:-Lk4S0exDrN2CgkBS3Q6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3e0d5e19c8974a41c0c4a4686467648c0ee4381/pkg/sql/opt/exec/execbuilder/statement.go#L243)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

update comment
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/statement.go, line 256 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38936#-Lk3VLrD9HCS0j1-_cVh:-Lk4S17y1iKzH1YQbMMw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3e0d5e19c8974a41c0c4a4686467648c0ee4381/pkg/sql/opt/exec/execbuilder/statement.go#L256)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

update comment
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 772 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38936#-Lk3V_9lExlvqCCLBX5F:-Lk4S6DlBhC6c0thTI6i:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3e0d5e19c8974a41c0c4a4686467648c0ee4381/pkg/sql/opt/memo/logical_props_builder.go#L772)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] maybe use a diff variable name like `cancel`?
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 779 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38936#-Lk3VgtY2esahZfh7bYG:-Lk4S6TD99xRJVNkoEyL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3e0d5e19c8974a41c0c4a4686467648c0ee4381/pkg/sql/opt/memo/logical_props_builder.go#L779)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/opt/ops/statement.opt, line 172 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38936#-Lk3UkDL0jfxDEmJzRPB:-Lk4NSFNEv4TQNWZekrV:b-7gclag) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3e0d5e19c8974a41c0c4a4686467648c0ee4381/pkg/sql/opt/ops/statement.opt#L172)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Are these physical props being tested at all?
</blockquote></details>

Added a test.
___
*[pkg/sql/opt/optbuilder/misc_statements.go, line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38936#-Lk3XWav-T-wsw78c7nt:-Lk4NYRb8Ly7Rgw8GYX-:b929a22) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3e0d5e19c8974a41c0c4a4686467648c0ee4381/pkg/sql/opt/optbuilder/misc_statements.go#L60)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I'm having a bit of trouble understanding how the scoping works here. Is it ok to use `inScope.push()` when we are passing a blank scope above?
</blockquote></details>

This seemed like the right thing to me.. (and it's what Explain does). The scope we use above only matters for how we build that expression, I don't think it should affect the scope we return. 

Is there an alternative that makes more sense?

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 15 of 15 files at r3, 15 of 15 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38936#-:-Lk4axvt9a8AUJQ3Zzng:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj and @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/misc_statements.go, line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38936#-Lk3XWav-T-wsw78c7nt:-Lk4aTtr9IB9aLPnMkzz:b-xyhkfg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3e0d5e19c8974a41c0c4a4686467648c0ee4381/pkg/sql/opt/optbuilder/misc_statements.go#L60)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This seemed like the right thing to me.. (and it's what Explain does). The scope we use above only matters for how we build that expression, I don't think it should affect the scope we return. 

Is there an alternative that makes more sense?
</blockquote></details>

Nah, this seems good, just a bit hard to think of examples of when the returned scope would be used by a parent expression and what the correct behavior is

**Pull request merged**
