### PR TITLE
sql: Correct error msg when creating UDF under temp or virtual schema

### LINKED ISSUE #102964: schemachanger: CREATE FUNCTION within virtual schemas or temp schemas is buggy
1. Declarative schema changer is buggy when creating a function under a *virtual* schema:
```

set use_declarative_schema_changer = off;
create function crdb_internal.f (input int) returns int stable language sql as $$ select 123213$$;
ERROR: cannot CREATE on schema crdb_internal
SQLSTATE: 42501


set use_declarative_schema_changer = unsafe_always;
create function crdb_internal.f (input int) returns int stable language sql as $$ select 123213$$;
ERROR: internal error: building declarative schema change targets for CREATE FUNCTION: invalid descriptor ID 0
SQLSTATE: XX000
DETAIL: stack trace:
....
```

2. Declarative schema changer and legacy schema changer gives different output when creating a function under a *temporary* schema:
```
set use_declarative_schema_changer = off;
create function pg_temp_1683651626391077000_1.t2 (input int) returns int stable language sql as $$ select 123213$$;
ERROR: descriptorless public schema cannot be modified
SQLSTATE: 42501

set use_declarative_schema_changer = unsafe_always;
create function pg_temp_1683651626391077000_1.t2 (input int) returns int stable language sql as $$ select 123213$$;
ERROR: CREATE permission denied for schema {"" "pg_temp_1683651626391077000_1" %!q(bool=false) %!q(bool=true)}
SQLSTATE: 42501
```

It seems to me the legacy schema changer error msg looks more intuitive in both cases, so the fix will be to change the declarative schema changer to output the same error msg in both cases.

### PR DESCRIPTION
**Pull request by Xiang-Gu**
We Fixed the error message to be more understandable when creating UDFs under a virtual or temporary schema, which requires changes to both legacy and declarative schema changers.

Fixes: #102964
Epic: None

### CODE REVIEW

**Review by rafiss — COMMENTED** [review]
nice work! is there a way that the change to move constants from `tree` to `catconstants` can be a separate commit in this PR? it will make it much easier to review the change to the error handling.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104414#-:-NXH044L75O9XlsKh38z:bhydi4i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2, @msbutler, @renatolabs, and @smg260)

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104414)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2, @msbutler, @renatolabs, @smg260, and @Xiang-Gu)

___
*[`pkg/sql/catalog/errors.go` line 206 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104414#-NXMmjr8-c6ecZr8q45p:-NXMmjr9-EBZC1V6ZOSU:b-t1xzw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/db88d0e287ed512144ce31a7d58d909affa0e78f/pkg/sql/catalog/errors.go#L206)):*
> ```Go
> // Here, a virtual schema includes
> // - descriptorless public schemas (deprecated),
> // - temporary schemas,
> ```

why is a temporary schema considered "virtual"? i thought they actually were represented physically. (i might be mistaken)
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_schema.go` line 146 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104414#-NXMmVXwEALhE7DFsyme:-NXMmVXwEALhE7DFsymf:bjythi3) ([raw file](https://github.com/cockroachdb/cockroach/blob/db88d0e287ed512144ce31a7d58d909affa0e78f/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_schema.go#L146)):*
> ```Go
> }
> 
> func IsVirtualSchemaName(schema string) bool {
> ```

nit: this function doesn't seem needed. the same check is made in other places by using:
```
_, isVirtualSchema := catconstants.VirtualSchemaNames[u.Schema()]
```
___
*[`pkg/sql/sqlerrors/errors.go` line 353 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104414#-NXMnTTv8t9FvSTKqQPG:-NXMnTTv8t9FvSTKqQPH:b-q95phq) ([raw file](https://github.com/cockroachdb/cockroach/blob/db88d0e287ed512144ce31a7d58d909affa0e78f/pkg/sql/sqlerrors/errors.go#L353)):*
> ```Go
> }
> 
> func NewCannotModifyTempOrVirtualSchemaError(schema string, kind string) error {
> ```

nit: why is the type of the second parameter a string? it seems like it would be better if it was a `ResolvedSchemaKind`
___
*[`pkg/sql/sqlerrors/errors.go` line 355 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104414#-NXMmGib7-KB4_m9tNtc:-NXMmGib7-KB4_m9tNtd:b-yc5cjb) ([raw file](https://github.com/cockroachdb/cockroach/blob/db88d0e287ed512144ce31a7d58d909affa0e78f/pkg/sql/sqlerrors/errors.go#L355)):*
> ```Go
> func NewCannotModifyTempOrVirtualSchemaError(schema string, kind string) error {
> 	if kind != "temporary" && kind != "virtual" {
> 		panic(errors.AssertionFailedf(
> ```

there's no need to panic and crash the node here. let's just return the assertion error.
___
*[`pkg/sql/sqlerrors/errors.go` line 359 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104414#-NXMnQK8BCFejSPJ7HbQ:-NXMnQK8BCFejSPJ7HbR:b-cjhrhl) ([raw file](https://github.com/cockroachdb/cockroach/blob/db88d0e287ed512144ce31a7d58d909affa0e78f/pkg/sql/sqlerrors/errors.go#L359)):*
> ```Go
> 	}
> 	return pgerror.Newf(pgcode.InsufficientPrivilege,
> 		"%s is a %s schema and cannot be modified", tree.ErrNameString(schema), kind)
> ```

i found that in postgres it is allowed to create functions in the temporary schema. could you explain a bit why we can't allow it? maybe that should be added as a comment inside of this function

**Review by rafiss — COMMENTED** [review]
thank you for making a separate commit! now it's much easier to review

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104414#-:-NXMncD13reqB8iExLlb:b-ukibby)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2, @msbutler, @renatolabs, @smg260, and @Xiang-Gu)

**Review by Xiang-Gu — COMMENTED** [review]
@rafiss thanks for your feedback. I've addressed all of your feedback and can you take another look at it when you get a chance. Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104414#-:-NXXB9hn7UEwtH4xY-67:bthz4gg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2, @msbutler, @rafiss, @renatolabs, and @smg260)

___
*[`pkg/sql/catalog/errors.go` line 206 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104414#-NXMmjr8-c6ecZr8q45p:-NXWpZys40rFa2TsZLKQ:bsbop3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/db88d0e287ed512144ce31a7d58d909affa0e78f/pkg/sql/catalog/errors.go#L206)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

why is a temporary schema considered "virtual"? i thought they actually were represented physically. (i might be mistaken)
</blockquote></details>

temporary schemas are descriptorless. In fact, I think it's better to rename this function to `NewMutableAccessToDescriptorlessSchemaError` to reflect the fact that input `schema` is a descriptorless schema. I've made this change.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_schema.go` line 146 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104414#-NXMmVXwEALhE7DFsyme:-NXWqOSND20xL6WSjfUU:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/db88d0e287ed512144ce31a7d58d909affa0e78f/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_schema.go#L146)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: this function doesn't seem needed. the same check is made in other places by using:
```
_, isVirtualSchema := catconstants.VirtualSchemaNames[u.Schema()]
```
</blockquote></details>

done
___
*[`pkg/sql/sqlerrors/errors.go` line 353 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104414#-NXMnTTv8t9FvSTKqQPG:-NXWqQXo09E5Q5AMb6dD:b9tqc4m) ([raw file](https://github.com/cockroachdb/cockroach/blob/db88d0e287ed512144ce31a7d58d909affa0e78f/pkg/sql/sqlerrors/errors.go#L353)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: why is the type of the second parameter a string? it seems like it would be better if it was a `ResolvedSchemaKind`
</blockquote></details>

good question, it's because if we did so, then we have the following package dependency
`eval` imports `sqlerrors` imports `catalog`

And in `../eval/BUILD.bazel` we have disallowed import from `eval` to `catalog`. That's why I switched the second input parameter to a `string`.
___
*[`pkg/sql/sqlerrors/errors.go` line 355 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104414#-NXMmGib7-KB4_m9tNtc:-NXWrB_-EIj9FipWeEU2:b-st0dfz) ([raw file](https://github.com/cockroachdb/cockroach/blob/db88d0e287ed512144ce31a7d58d909affa0e78f/pkg/sql/sqlerrors/errors.go#L355)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

there's no need to panic and crash the node here. let's just return the assertion error.
</blockquote></details>

good catch. Done
___
*[`pkg/sql/sqlerrors/errors.go` line 359 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104414#-NXMnQK8BCFejSPJ7HbQ:-NXWteHI2GgDYIz2Hp2f:b-3jwys4) ([raw file](https://github.com/cockroachdb/cockroach/blob/db88d0e287ed512144ce31a7d58d909affa0e78f/pkg/sql/sqlerrors/errors.go#L359)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i found that in postgres it is allowed to create functions in the temporary schema. could you explain a bit why we can't allow it? maybe that should be added as a comment inside of this function
</blockquote></details>

nothing fundamental; I think we just choose to not include that in the scope in our first effort to support UDFs. I have changed the code to return an unimplemented error with a link to issue https://github.com/cockroachdb/cockroach/issues/104687

**Review by rafiss — APPROVED** [review]
this looks great now, thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104414#-:-NXpInvQ2Gu5xhPPM8Vt:bfcr9m2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2, @msbutler, @renatolabs, and @smg260)

**Pull request merged**
