### PR TITLE
distsql: ordered synchronizer implementation

### PR DESCRIPTION
**Pull request by RaduBerinde**
Please ignore the first commit (r1) - it's a separate PR.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7342)

### CODE REVIEW

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 13 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[sql/distsql/input_sync.go, line 29 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7342#-KKkJn6k-OG4uvarMT87:-KKkJn6k-OG4uvarMT88:-726859185) ([raw file](https://github.com/cockroachdb/cockroach/blob/03296fd6e55abdf8f75195dfa802a3294709544b/sql/distsql/input_sync.go#L29)):*
> ```Go
> type srcInfo struct {
> 	src     RowSource
> 	row     sqlbase.EncDatumRow
> ```

Explain the relationship between row and src?
An option for not having both of these is to introduce a `PeekableRowSource` that wraps another row source and buffers one row :)

---

*[sql/distsql/input_sync.go, line 30 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7342#-KKkJZaPskb3W07CnkWn:-KKkJZaPskb3W07CnkWo:469553931) ([raw file](https://github.com/cockroachdb/cockroach/blob/03296fd6e55abdf8f75195dfa802a3294709544b/sql/distsql/input_sync.go#L30)):*
> ```Go
> 	src     RowSource
> 	row     sqlbase.EncDatumRow
> 	heapPos int
> ```

maybe add a comment to this `heapPos` saying who maintains it. We only need it for assertions, right?

---

*[sql/distsql/input_sync.go, line 44 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7342#-KKkIxRIDIa6a3IhuA9H:-KKkIxRIDIa6a3IhuA9I:-1084068066) ([raw file](https://github.com/cockroachdb/cockroach/blob/03296fd6e55abdf8f75195dfa802a3294709544b/sql/distsql/input_sync.go#L44)):*
> ```Go
> 	// heap of source indexes, ordered by the current row. Sources with no more
> 	// rows are not in the heap.
> 	heap        []int
> ```

maybe typedef these indexes to a `SrcIdx`. There's a bit of index chasing in this code.

---

*[sql/distsql/input_sync.go, line 64 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7342#-KKkKkWeSBcZxlwzKKbt:-KKkKkWeSBcZxlwzKKbu:1178207657) ([raw file](https://github.com/cockroachdb/cockroach/blob/03296fd6e55abdf8f75195dfa802a3294709544b/sql/distsql/input_sync.go#L64)):*
> ```Go
> 	si := &s.sources[s.heap[i]]
> 	sj := &s.sources[s.heap[j]]
> 	cmp, err := si.row.Compare(&s.alloc, s.ordering, sj.row)
> ```

`Compare` can error? Don't you wish you had exceptions sometimes...

---

*[sql/distsql/input_sync.go, line 89 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7342#-KKkLVYOMdHfnniG-8JL:-KKkLVYPqDKR48Q6_EE0:-1034404753) ([raw file](https://github.com/cockroachdb/cockroach/blob/03296fd6e55abdf8f75195dfa802a3294709544b/sql/distsql/input_sync.go#L89)):*
> ```Go
> }
> 
> // Push is part of heap.Interface and is only meant to be used internally.
> ```

replace this comment with a mention of `initHeap` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7342#-:-KKkLePpiZq3_lvT3Ax_:1417088721)*

**Comment by RaduBerinde** [comment]
Updated.

---

Review status: 0 of 13 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[sql/distsql/input_sync.go, line 30 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7342#-KKkJZaPskb3W07CnkWn:-KKkhYJnO1wCkDE_H72W:-920259511) ([raw file](https://github.com/cockroachdb/cockroach/blob/03296fd6e55abdf8f75195dfa802a3294709544b/sql/distsql/input_sync.go#L30)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> maybe add a comment to this `heapPos` saying who maintains it. We only need it for assertions, right?
</details>
Hm. I guess we aren't using it.. I think in an earlier iteration of the change it was needed. Removing it.

---

*[sql/distsql/input_sync.go, line 64 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7342#-KKkKkWeSBcZxlwzKKbt:-KKkhwa__GjrcJBGvt-m:1201615020) ([raw file](https://github.com/cockroachdb/cockroach/blob/03296fd6e55abdf8f75195dfa802a3294709544b/sql/distsql/input_sync.go#L64)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> `Compare` can error? Don't you wish you had exceptions sometimes...
</details>
Yeah, it may need to decode a buffer into a Datum. And no, I do not :)

---

*[sql/distsql/input_sync.go, line 89 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7342#-KKkLVYOMdHfnniG-8JL:-KKkisQNBL8pecR6x3ww:1458366670) ([raw file](https://github.com/cockroachdb/cockroach/blob/03296fd6e55abdf8f75195dfa802a3294709544b/sql/distsql/input_sync.go#L89)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> replace this comment with a mention of `initHeap` ?
</details>
Sorry, not getting the suggestion (what would the comment say?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7342#-:-KKkjF66IRbOcJiTVMO8:-719267080)*

**Comment by andreimatei** [comment]
Review status: 0 of 13 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/distsql/input_sync.go, line 30 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7342#-KKkJZaPskb3W07CnkWn:-KKngfUYBtMbQn-eyygl:-364862476) ([raw file](https://github.com/cockroachdb/cockroach/blob/03296fd6e55abdf8f75195dfa802a3294709544b/sql/distsql/input_sync.go#L30)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Hm. I guess we aren't using it.. I think in an earlier iteration of the change it was needed. Removing it.
</details>
I wasn't against those assertions. Whatever you think.

---

*[sql/distsql/input_sync.go, line 89 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7342#-KKkLVYOMdHfnniG-8JL:-KKngQ5eIPQyUthz0fWH:2142065043) ([raw file](https://github.com/cockroachdb/cockroach/blob/03296fd6e55abdf8f75195dfa802a3294709544b/sql/distsql/input_sync.go#L89)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Sorry, not getting the suggestion (what would the comment say?)
</details>
well, the comment says that this is meant to be used internally, but it's also "not implemented".
Say that all the elements are put in the heap from the beginning through `initHeap`. Or don't say anything,

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7342)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 13 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/distsql/input_sync.go, line 89 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7342#-KKkLVYOMdHfnniG-8JL:-KKnjr8gmG3-nQKyswBA:722087242) ([raw file](https://github.com/cockroachdb/cockroach/blob/03296fd6e55abdf8f75195dfa802a3294709544b/sql/distsql/input_sync.go#L89)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> well, the comment says that this is meant to be used internally, but it's also "not implemented".
> Say that all the elements are put in the heap from the beginning through `initHeap`. Or don't say anything,
</details>
Ah, gotcha. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7342)*

**Pull request merged**
