### PR TITLE
ccl/sqlproxyccl: deflake TestProxyAgainstSecureCRDB

### LINKED ISSUE #98653: ccl/sqlproxyccl: TestProxyAgainstSecureCRDB failed
ccl/sqlproxyccl.TestProxyAgainstSecureCRDB [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/9070050?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/9070050?buildTab=artifacts#/) on master @ [9b43dc50d468171bc9919dc684b7274b63e13da2](https://github.com/cockroachdb/cockroach/commits/9b43dc50d468171bc9919dc684b7274b63e13da2):

```
=== RUN   TestProxyAgainstSecureCRDB
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/5d831302e446252f630c56f4e52acade/logTestProxyAgainstSecureCRDB725307684
    test_log_scope.go:79: use -show-logs to present logs inline
    proxy_handler_test.go:276: 
        	Error Trace:	/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/12424/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/ccl/sqlproxyccl/sqlproxyccl_test_/sqlproxyccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/sqlproxyccl/proxy_handler_test.go:276
        	            				/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/12424/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/ccl/sqlproxyccl/sqlproxyccl_test_/sqlproxyccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/sqlproxyccl/proxy_handler_test.go:2306
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 2
        	Test:       	TestProxyAgainstSecureCRDB
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/5d831302e446252f630c56f4e52acade/logTestProxyAgainstSecureCRDB725307684
--- FAIL: TestProxyAgainstSecureCRDB (1.22s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-sessions @cockroachdb/server
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestProxyAgainstSecureCRDB.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by jaylim-crl**
Fixes #98653.

Release note: None

Epic: none

Release justification: Test-only fix.

### CODE REVIEW

**Review by jeffswenson — APPROVED** [review]
LGTM

**Comment by knz** [comment]
subsumed by #100481.

bors r-

**Comment by jaylim-crl** [comment]
backport 22.2 23.1

**Comment by jaylim-crl** [comment]
blathers backport 22.2 23.1

**Pull request closed without merging**
