### PR TITLE
changefeedccl: hook up kafka producer library logs to our logging

### PR DESCRIPTION
**Pull request by danhhz**
I don't entirely love this, given that we don't have much control over
sarama's log volume, but sarama returns the same "kafka: client has run
out of available brokers to talk to (Is your cluster reachable?)" error
for any connection issue. Which means it's basically impossible to debug
kafka connection issues without something like this and I think it's
better than the alternative of nothing. Motivated by #35510 which makes
hard to debug connection issues even more likely.

Logs look something like this:

    I190312 18:56:53.535646 585 vendor/github.com/Shopify/sarama/client.go:123  [kafka-producer] Initializing new client
    I190312 18:56:53.535714 585 vendor/github.com/Shopify/sarama/client.go:724  [kafka-producer] client/metadata fetching metadata for all topics from broker localhost:9092
    I190312 18:56:53.536730 569 vendor/github.com/Shopify/sarama/broker.go:148  [kafka-producer] Connected to broker at localhost:9092 (unregistered)
    I190312 18:56:53.537661 585 vendor/github.com/Shopify/sarama/client.go:500  [kafka-producer] client/brokers registered new broker #0 at 172.16.94.87:9092
    I190312 18:56:53.537686 585 vendor/github.com/Shopify/sarama/client.go:170  [kafka-producer] Successfully initialized new client

Release note (enterprise change): `CHANGEFEED`s using kafka log
information to help debug connection issues

### CODE REVIEW

**Comment by danhhz** [comment]
cc @rolandcrosby

**Comment by danhhz** [comment]
Sample output from a tpcc changefeed start/pause/unpause. Pretty noisy but it does seem to die down in the steady state.

```
I190312 19:08:21.774319 1546 vendor/github.com/Shopify/sarama/client.go:123  [kafka-producer] Initializing new client
I190312 19:08:21.774396 1546 vendor/github.com/Shopify/sarama/client.go:724  [kafka-producer] client/metadata fetching metadata for all topics from broker localhost:9092
I190312 19:08:21.775342 1547 vendor/github.com/Shopify/sarama/broker.go:148  [kafka-producer] Connected to broker at localhost:9092 (unregistered)
I190312 19:08:21.776711 1546 vendor/github.com/Shopify/sarama/client.go:500  [kafka-producer] client/brokers registered new broker #0 at 172.16.94.87:9092
I190312 19:08:21.776753 1546 vendor/github.com/Shopify/sarama/client.go:170  [kafka-producer] Successfully initialized new client
I190312 19:08:21.776815 1623 vendor/github.com/Shopify/sarama/async_producer.go:954  [kafka-producer] Producer shutting down.
I190312 19:08:21.776854 1546 vendor/github.com/Shopify/sarama/client.go:223  [kafka-producer] Closing Client
I190312 19:08:21.776952 1611 vendor/github.com/Shopify/sarama/broker.go:191  [kafka-producer] Closed connection to broker localhost:9092
I190312 19:08:21.783076 1389 vendor/github.com/Shopify/sarama/client.go:123  [kafka-producer] Initializing new client
I190312 19:08:21.783128 1389 vendor/github.com/Shopify/sarama/client.go:724  [kafka-producer] client/metadata fetching metadata for all topics from broker localhost:9092
I190312 19:08:21.784323 1390 vendor/github.com/Shopify/sarama/broker.go:148  [kafka-producer] Connected to broker at localhost:9092 (unregistered)
I190312 19:08:21.785403 1389 vendor/github.com/Shopify/sarama/client.go:500  [kafka-producer] client/brokers registered new broker #0 at 172.16.94.87:9092
I190312 19:08:21.785434 1389 vendor/github.com/Shopify/sarama/client.go:170  [kafka-producer] Successfully initialized new client
I190312 19:08:21.785510 1389 vendor/github.com/Shopify/sarama/client.go:123  [kafka-producer] Initializing new client
I190312 19:08:21.785585 1389 vendor/github.com/Shopify/sarama/client.go:724  [kafka-producer] client/metadata fetching metadata for all topics from broker localhost:9092
I190312 19:08:21.786645 1657 vendor/github.com/Shopify/sarama/broker.go:148  [kafka-producer] Connected to broker at localhost:9092 (unregistered)
I190312 19:08:21.789617 1389 vendor/github.com/Shopify/sarama/client.go:500  [kafka-producer] client/brokers registered new broker #0 at 172.16.94.87:9092
I190312 19:08:21.789682 1389 vendor/github.com/Shopify/sarama/client.go:170  [kafka-producer] Successfully initialized new client
I190312 19:08:22.789018 1658 vendor/github.com/Shopify/sarama/client.go:722  [kafka-producer] client/metadata fetching metadata for [warehouse] from broker localhost:9092
I190312 19:08:22.803192 1658 vendor/github.com/Shopify/sarama/client.go:739  [kafka-producer] client/metadata found some partitions to be leaderless
I190312 19:08:22.803227 1658 vendor/github.com/Shopify/sarama/client.go:713  [kafka-producer] client/metadata retrying after 250ms... (3 attempts remaining)
I190312 19:08:23.056358 1658 vendor/github.com/Shopify/sarama/client.go:722  [kafka-producer] client/metadata fetching metadata for [warehouse] from broker localhost:9092
I190312 19:08:23.057943 1684 vendor/github.com/Shopify/sarama/async_producer.go:669  [kafka-producer] producer/broker/0 starting up
I190312 19:08:23.058002 1684 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on warehouse/0
I190312 19:08:23.058337 1683 vendor/github.com/Shopify/sarama/broker.go:146  [kafka-producer] Connected to broker at 172.16.94.87:9092 (registered as #0)
I190312 19:08:23.065028 1659 vendor/github.com/Shopify/sarama/client.go:722  [kafka-producer] client/metadata fetching metadata for [district] from broker localhost:9092
I190312 19:08:23.065066 1687 vendor/github.com/Shopify/sarama/client.go:722  [kafka-producer] client/metadata fetching metadata for [history] from broker localhost:9092
I190312 19:08:23.065246 1688 vendor/github.com/Shopify/sarama/client.go:722  [kafka-producer] client/metadata fetching metadata for [customer] from broker localhost:9092
I190312 19:08:23.072537 1659 vendor/github.com/Shopify/sarama/client.go:739  [kafka-producer] client/metadata found some partitions to be leaderless
I190312 19:08:23.072563 1659 vendor/github.com/Shopify/sarama/client.go:713  [kafka-producer] client/metadata retrying after 250ms... (3 attempts remaining)
I190312 19:08:23.079731 1687 vendor/github.com/Shopify/sarama/client.go:739  [kafka-producer] client/metadata found some partitions to be leaderless
I190312 19:08:23.079777 1687 vendor/github.com/Shopify/sarama/client.go:713  [kafka-producer] client/metadata retrying after 250ms... (3 attempts remaining)
I190312 19:08:23.088026 1688 vendor/github.com/Shopify/sarama/client.go:739  [kafka-producer] client/metadata found some partitions to be leaderless
I190312 19:08:23.088066 1688 vendor/github.com/Shopify/sarama/client.go:713  [kafka-producer] client/metadata retrying after 250ms... (3 attempts remaining)
I190312 19:08:23.326279 1659 vendor/github.com/Shopify/sarama/client.go:722  [kafka-producer] client/metadata fetching metadata for [district] from broker localhost:9092
I190312 19:08:23.327813 1684 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on district/0
I190312 19:08:23.330059 1687 vendor/github.com/Shopify/sarama/client.go:722  [kafka-producer] client/metadata fetching metadata for [history] from broker localhost:9092
I190312 19:08:23.331887 1684 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on history/0
I190312 19:08:23.342596 1688 vendor/github.com/Shopify/sarama/client.go:722  [kafka-producer] client/metadata fetching metadata for [customer] from broker localhost:9092
I190312 19:08:23.343599 1684 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on customer/0
I190312 19:08:23.370412 1648 vendor/github.com/Shopify/sarama/client.go:722  [kafka-producer] client/metadata fetching metadata for [order] from broker localhost:9092
I190312 19:08:23.378817 1648 vendor/github.com/Shopify/sarama/client.go:739  [kafka-producer] client/metadata found some partitions to be leaderless
I190312 19:08:23.378839 1648 vendor/github.com/Shopify/sarama/client.go:713  [kafka-producer] client/metadata retrying after 250ms... (3 attempts remaining)
I190312 19:08:23.629607 1648 vendor/github.com/Shopify/sarama/client.go:722  [kafka-producer] client/metadata fetching metadata for [order] from broker localhost:9092
I190312 19:08:23.631218 1684 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on order/0
I190312 19:08:27.482914 1738 vendor/github.com/Shopify/sarama/client.go:722  [kafka-producer] client/metadata fetching metadata for [new_order] from broker localhost:9092
I190312 19:08:27.490619 1738 vendor/github.com/Shopify/sarama/client.go:739  [kafka-producer] client/metadata found some partitions to be leaderless
I190312 19:08:27.490643 1738 vendor/github.com/Shopify/sarama/client.go:713  [kafka-producer] client/metadata retrying after 250ms... (3 attempts remaining)
I190312 19:08:27.740737 1738 vendor/github.com/Shopify/sarama/client.go:722  [kafka-producer] client/metadata fetching metadata for [new_order] from broker localhost:9092
I190312 19:08:27.741549 1684 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on new_order/0
I190312 19:08:27.748302 1770 vendor/github.com/Shopify/sarama/client.go:722  [kafka-producer] client/metadata fetching metadata for [item] from broker localhost:9092
I190312 19:08:27.755440 1770 vendor/github.com/Shopify/sarama/client.go:739  [kafka-producer] client/metadata found some partitions to be leaderless
I190312 19:08:27.755462 1770 vendor/github.com/Shopify/sarama/client.go:713  [kafka-producer] client/metadata retrying after 250ms... (3 attempts remaining)
I190312 19:08:28.006622 1770 vendor/github.com/Shopify/sarama/client.go:722  [kafka-producer] client/metadata fetching metadata for [item] from broker localhost:9092
I190312 19:08:28.007841 1684 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on item/0
I190312 19:08:28.008462 1780 vendor/github.com/Shopify/sarama/client.go:722  [kafka-producer] client/metadata fetching metadata for [stock] from broker localhost:9092
I190312 19:08:28.017118 1780 vendor/github.com/Shopify/sarama/client.go:739  [kafka-producer] client/metadata found some partitions to be leaderless
I190312 19:08:28.017149 1780 vendor/github.com/Shopify/sarama/client.go:713  [kafka-producer] client/metadata retrying after 250ms... (3 attempts remaining)
I190312 19:08:28.268211 1780 vendor/github.com/Shopify/sarama/client.go:722  [kafka-producer] client/metadata fetching metadata for [stock] from broker localhost:9092
I190312 19:08:28.269403 1684 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on stock/0
I190312 19:08:29.617985 1795 vendor/github.com/Shopify/sarama/client.go:722  [kafka-producer] client/metadata fetching metadata for [order_line] from broker localhost:9092
I190312 19:08:29.626214 1795 vendor/github.com/Shopify/sarama/client.go:739  [kafka-producer] client/metadata found some partitions to be leaderless
I190312 19:08:29.626240 1795 vendor/github.com/Shopify/sarama/client.go:713  [kafka-producer] client/metadata retrying after 250ms... (3 attempts remaining)
I190312 19:08:29.881601 1795 vendor/github.com/Shopify/sarama/client.go:722  [kafka-producer] client/metadata fetching metadata for [order_line] from broker localhost:9092
I190312 19:08:29.882655 1684 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on order_line/0
I190312 19:08:33.122555 1684 vendor/github.com/Shopify/sarama/async_producer.go:760  [kafka-producer] producer/broker/0 maximum request accumulated, waiting for space
I190312 19:08:42.385207 1389 vendor/github.com/Shopify/sarama/client.go:722  [kafka-producer] client/metadata fetching metadata for [customer new_order item history stock order_line order warehouse district] from broker localhost:9092
I190312 19:08:42.405107 1948 vendor/github.com/Shopify/sarama/async_producer.go:669  [kafka-producer] producer/broker/0 starting up
I190312 19:08:42.405148 1948 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on new_order/0
I190312 19:08:42.405166 1948 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on customer/0
I190312 19:08:42.405181 1948 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on history/0
I190312 19:08:42.405235 1948 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on item/0
I190312 19:08:42.405359 1948 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on order_line/0
I190312 19:08:42.408426 1947 vendor/github.com/Shopify/sarama/broker.go:146  [kafka-producer] Connected to broker at 172.16.94.87:9092 (registered as #0)
I190312 19:08:42.416833 1948 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on stock/0
I190312 19:08:42.417164 1948 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on warehouse/0
I190312 19:08:42.417210 1948 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on order/0
I190312 19:08:42.417638 1948 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on district/0
I190312 19:09:26.768870 2216 vendor/github.com/Shopify/sarama/async_producer.go:954  [kafka-producer] Producer shutting down.
I190312 19:09:26.769118 1389 vendor/github.com/Shopify/sarama/client.go:223  [kafka-producer] Closing Client
I190312 19:09:26.769177 1684 vendor/github.com/Shopify/sarama/async_producer.go:748  [kafka-producer] producer/broker/0 shut down
I190312 19:09:26.769204 2034 vendor/github.com/Shopify/sarama/async_producer.go:954  [kafka-producer] Producer shutting down.
I190312 19:09:26.769303 2033 vendor/github.com/Shopify/sarama/broker.go:191  [kafka-producer] Closed connection to broker localhost:9092
I190312 19:09:26.769352 1389 vendor/github.com/Shopify/sarama/client.go:223  [kafka-producer] Closing Client
I190312 19:09:26.769408 1948 vendor/github.com/Shopify/sarama/async_producer.go:748  [kafka-producer] producer/broker/0 shut down
I190312 19:09:26.769443 2032 vendor/github.com/Shopify/sarama/broker.go:191  [kafka-producer] Closed connection to broker 172.16.94.87:9092
I190312 19:09:26.769533 2218 vendor/github.com/Shopify/sarama/broker.go:191  [kafka-producer] Closed connection to broker 172.16.94.87:9092
I190312 19:09:26.769604 2219 vendor/github.com/Shopify/sarama/broker.go:191  [kafka-producer] Closed connection to broker localhost:9092
I190312 19:09:46.897028 2251 vendor/github.com/Shopify/sarama/client.go:123  [kafka-producer] Initializing new client
I190312 19:09:46.897095 2251 vendor/github.com/Shopify/sarama/client.go:724  [kafka-producer] client/metadata fetching metadata for all topics from broker localhost:9092
I190312 19:09:46.898252 2254 vendor/github.com/Shopify/sarama/broker.go:148  [kafka-producer] Connected to broker at localhost:9092 (unregistered)
I190312 19:09:46.899830 2251 vendor/github.com/Shopify/sarama/client.go:500  [kafka-producer] client/brokers registered new broker #0 at 172.16.94.87:9092
I190312 19:09:46.899900 2251 vendor/github.com/Shopify/sarama/client.go:170  [kafka-producer] Successfully initialized new client
I190312 19:09:46.900026 2251 vendor/github.com/Shopify/sarama/client.go:123  [kafka-producer] Initializing new client
I190312 19:09:46.900076 2251 vendor/github.com/Shopify/sarama/client.go:724  [kafka-producer] client/metadata fetching metadata for all topics from broker localhost:9092
I190312 19:09:46.902483 2267 vendor/github.com/Shopify/sarama/broker.go:148  [kafka-producer] Connected to broker at localhost:9092 (unregistered)
I190312 19:09:46.918782 2251 vendor/github.com/Shopify/sarama/client.go:500  [kafka-producer] client/brokers registered new broker #0 at 172.16.94.87:9092
I190312 19:09:46.918849 2251 vendor/github.com/Shopify/sarama/client.go:170  [kafka-producer] Successfully initialized new client
I190312 19:09:47.263011 2251 vendor/github.com/Shopify/sarama/client.go:722  [kafka-producer] client/metadata fetching metadata for [customer item order district new_order history order_line stock warehouse] from broker localhost:9092
I190312 19:09:47.264514 2389 vendor/github.com/Shopify/sarama/async_producer.go:669  [kafka-producer] producer/broker/0 starting up
I190312 19:09:47.264711 2389 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on history/0
I190312 19:09:47.264868 2389 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on order_line/0
I190312 19:09:47.264978 2331 vendor/github.com/Shopify/sarama/broker.go:146  [kafka-producer] Connected to broker at 172.16.94.87:9092 (registered as #0)
I190312 19:09:47.265046 2389 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on stock/0
I190312 19:09:47.265090 2389 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on warehouse/0
I190312 19:09:47.265182 2389 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on new_order/0
I190312 19:09:47.265230 2389 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on district/0
I190312 19:09:47.265280 2389 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on item/0
I190312 19:09:47.265323 2389 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on order/0
I190312 19:09:47.265378 2389 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on customer/0
I190312 19:10:06.968721 2630 vendor/github.com/Shopify/sarama/async_producer.go:669  [kafka-producer] producer/broker/0 starting up
I190312 19:10:06.968762 2630 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on order/0
I190312 19:10:06.969266 2629 vendor/github.com/Shopify/sarama/broker.go:146  [kafka-producer] Connected to broker at 172.16.94.87:9092 (registered as #0)
I190312 19:10:06.969591 2630 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on order_line/0
I190312 19:10:06.976468 2630 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on customer/0
I190312 19:10:06.977676 2630 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on new_order/0
I190312 19:10:07.978884 2630 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on warehouse/0
I190312 19:10:07.987292 2630 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on district/0
I190312 19:10:07.987454 2630 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on history/0
I190312 19:10:23.303996 2630 vendor/github.com/Shopify/sarama/async_producer.go:680  [kafka-producer] producer/broker/0 state change to [open] on stock/0
```

**Comment by rolandcrosby** [comment]
Looks pretty spammy in the setup phase, but like you said, it beats not being able to diagnose issues at all. I have no objection to this.

**Review by nvb — APPROVED** [review]
It is a shame that the logger only has "print" methods and doesn't specify the severity of messages.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35661#-:-L_yv-bX9-LDDclEwL8N:b77kn9b)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz, @nvanbenschoten, and @tbg)

___
*[pkg/ccl/changefeedccl/sink.go, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35661#-L_yuPBpEkCZg2z7aCYc:-L_yuPBpEkCZg2z7aCYd:bvboa94) ([raw file](https://github.com/cockroachdb/cockroach/blob/db272698311d14a2d5d78b0d225ac94fe32b9560/pkg/ccl/changefeedccl/sink.go#L148)):*
> ```Go
> 
> func (l *kafkaLogAdapter) Print(v ...interface{}) {
> 	log.InfoDepth(l.ctx, 1, v...)
> ```

Do you think these should be behind verbosity checks? 

If so, I'd move this type to a file named `kafka.go` so that the vmodule stuff works with that key. We do the same thing with the raft logger.

**Review by danhhz — COMMENTED** [review]
> It is a shame that the logger only has "print" methods and doesn't specify the severity of messages.

Agreed. I'd also love to be able to specify a logger per producer instance.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35661#-:-L_ywWLUErvKbyGgFkNa:b309tkf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[pkg/ccl/changefeedccl/sink.go, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35661#-L_yuPBpEkCZg2z7aCYc:-L_ywXwq6DPnNsY0VoMb:b-qope89) ([raw file](https://github.com/cockroachdb/cockroach/blob/db272698311d14a2d5d78b0d225ac94fe32b9560/pkg/ccl/changefeedccl/sink.go#L148)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you think these should be behind verbosity checks? 

If so, I'd move this type to a file named `kafka.go` so that the vmodule stuff works with that key. We do the same thing with the raft logger.
</blockquote></details>

I think I'd like to try it on by default. This is the only real way we have for users to debug connection issues and we're pretty explicit about telling them not to use --vmodule. It's spammy on startup but I've had this cherry-picked into a bunch of my recent roachprod testing/debugging and there isn't anything in the steady state, so it's mostly a bounded badness.

**Comment by danhhz** [comment]
Whoops, thought I already merged this.

bors r=nvanbenschoten

**Comment by danhhz** [comment]
Merge conflict is another PR that got grouped in the same bors batch

**Pull request merged**
