### PR TITLE
backport-2.1: fix the handling of SQL types

### PR DESCRIPTION
**Pull request by knz**
Backport 1/1 commits from #28937.
Backport 1/1 commits from #28942.
Backport 17/17 commits from #28943.
Backport 1/1 commits from #28944.
Backport 1/1 commits from #28945.
Backport 1/1 commits from #28949.
Backport 2/2 commits from #28950.
Backport 1/1 commits from #28951 (#28959).
Backport 1/1 commits from #28952 (#28959).
Backport 1/1 commits from #28955 (#28959).
Backport 1/1 commits from #28959.
Backport 1/1 commits from #28959.
Backport 1/1 commits from #28690.

cc @cockroachdb/release

### CODE REVIEW

**Review by BramGruneir — APPROVED** [review]
This is a ton to backport.  I've reviewed the individual commits, but I have no idea how to review this.  

I think the commits are good, just a question of if anyone else has any objections.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29006#-:-LKcW_InEaNbwrpR5-OI:b-57vlte)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by knz** [comment]
For reference there was zero merge conflict. So if you're good with the base PRs I'd say there's nothing special to see here.

**Review by BramGruneir — COMMENTED** [review]
SGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29006#-:-LKcrp8n04_hfv9eYAPu:bb73djm)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by knz** [comment]
Merge skew with an opt backport, rebased.

bors r+

**Pull request merged**
