### PR TITLE
tracing: support zipkin

### PR DESCRIPTION
**Pull request by RaduBerinde**
To try this out locally:
 - set up a zipkin instance using `docker run -d -p 9411:9411 openzipkin/zipkin`
 - set `trace.zipkin.collector` to `127.0.0.1:9411`

### CODE REVIEW

**Comment by tschottdorf** [comment]
:lgtm:, minor comments

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/util/tracing/shadow.go, line 142 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16903#-KoOMITS_Heml8s6mIUN:-KoOMITS_Heml8s6mIUO:bkk0k5y) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc3f6c53fddc1047b7342da006c3172f46efb066/pkg/util/tracing/shadow.go#L142)):*
> ```Go
> 
> 	// Create our recorder.
> 	recorder := zipkin.NewRecorder(collector, false /* debug */, "0.0.0.0:0", "cockroach")
> ```

nit: `!debug`, but don't worry about it if that what makes you eat CI.

---

*[pkg/util/tracing/shadow.go, line 160 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16903#-KoON3haO3lS6tiDn4ww:-KoON3haO3lS6tiDn4wx:bsux9dk) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc3f6c53fddc1047b7342da006c3172f46efb066/pkg/util/tracing/shadow.go#L160)):*
> ```Go
> 			}
> 			buf.WriteString("\n")
> 			_, _ = buf.WriteTo(os.Stderr)
> ```

Are you sure?

---

*[pkg/util/tracing/shadow.go, line 179 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16903#-KoONAVxLV8ucojKNIJK:-KoONAVy_f0dZSkPmql_:b-21ecr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc3f6c53fddc1047b7342da006c3172f46efb066/pkg/util/tracing/shadow.go#L179)):*
> ```Go
> 		t.setShadowTracer(createLightStepTracer(lsToken))
> 	} else if zipkinAddr := zipkinCollector.Get(); zipkinAddr != "" {
> 		t.setShadowTracer(createZipkinTracer(zipkinAddr))
> ```

Should add somewhere in the cluster vars that the options are exclusive.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16903#-:-KoONEtXAgnXml77nSDT:b-kl4b7g)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/util/tracing/shadow.go, line 160 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16903#-KoON3haO3lS6tiDn4ww:-KoONTuTOF89L1di9cm0:b-ceylwt) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc3f6c53fddc1047b7342da006c3172f46efb066/pkg/util/tracing/shadow.go#L160)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Are you sure?
</blockquote></details>

No.. But we can't `log` from this package. We can also just drop them, but I'm thinking they could be helpful if something isn't working

---

*[pkg/util/tracing/shadow.go, line 179 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16903#-KoONAVxLV8ucojKNIJK:-KoOP2_K1YILQUToos0r:b-d7bhn0) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc3f6c53fddc1047b7342da006c3172f46efb066/pkg/util/tracing/shadow.go#L179)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Should add somewhere in the cluster vars that the options are exclusive.
</blockquote></details>

will do

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16903)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/util/tracing/shadow.go, line 160 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16903#-KoON3haO3lS6tiDn4ww:-KoOPMCQ3b5Q3ttlIAuX:bcu40sl) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc3f6c53fddc1047b7342da006c3172f46efb066/pkg/util/tracing/shadow.go#L160)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

No.. But we can't `log` from this package. We can also just drop them, but I'm thinking they could be helpful if something isn't working
</blockquote></details>

Maybe I don't completely understand what this is doing, but my understanding is that it would spam all the traces to the logs basically, right? If that's what that's doing, I don't think I'm in favor of it, at least not until it turns out that's what we need. Otherwise, perhaps add a comment on why this is reasonable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16903)*

**Comment by RaduBerinde** [comment]
Review status: 2 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/util/tracing/shadow.go, line 160 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16903#-KoON3haO3lS6tiDn4ww:-KoOQ-noCquJ0YGhBIGm:bz01ieu) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc3f6c53fddc1047b7342da006c3172f46efb066/pkg/util/tracing/shadow.go#L160)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Maybe I don't completely understand what this is doing, but my understanding is that it would spam all the traces to the logs basically, right? If that's what that's doing, I don't think I'm in favor of it, at least not until it turns out that's what we need. Otherwise, perhaps add a comment on why this is reasonable.
</blockquote></details>

No, these are the logs from the zipkin tracer itself. Though it looks like I should be setting this on the collector not on the tracer, the collector logs things like errors sending data.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16903)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/util/tracing/shadow.go, line 160 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16903#-KoON3haO3lS6tiDn4ww:-KoOUWp5WIDS3QCfKM8W:b-l1h7pv) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc3f6c53fddc1047b7342da006c3172f46efb066/pkg/util/tracing/shadow.go#L160)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Ok. I think once these show up someone will be very confused, but I'm ok with this for now, though a comment here still wouldn't hurt (along with a prefix for the logged message explaining its origin).
</blockquote></details>

Added comment and prefix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16903)*

**Comment by tschottdorf** [comment]
:lgtm:, thanks for getting this in! Looking forward to trying it out.

---

Reviewed 4 of 4 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16903#-:-KoOUtspv0t55WmfvdNU:b-234auw)*

**Pull request merged**
