### PR TITLE
Delete the empty post-checkout hook.

### PR DESCRIPTION
**Pull request by petermattis**

### CODE REVIEW

**Comment by petermattis** [comment]
Hmm, the `hub` command line tool auto-filled the pull-request message incorrectly. Not sure what happened.

**Comment by bdarnell** [comment]
Simply removing the file will leave people with a dangling symlink in .git/hooks. How does git like that? We may need to leave the file as a symlink target and just stop clobbering it in bootstrap.sh.

**Comment by petermattis** [comment]
Hmm, perhaps we should just put the "glock" hooks in here so that folks don't have to run `glock install`.

**Comment by bdarnell** [comment]
Yeah, that works too.

**Pull request merged**
