### PR TITLE
roachtest: clean up randomized encryption-at-rest

### PR DESCRIPTION
**Pull request by tbg**
- roachtest: remove extraneous EncryptDefault(false)
- roachtest: avoid Encrypt{Default,AtRandom} in tpccbench
- roachtest: simplify randomized encryption.

### CODE REVIEW

**Comment by tbg** [comment]
I will actually run these tests before merge to make sure things still work. Probably with the `--encrypt` flag, too.

**Review by srosenberg — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76669)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @tbg)

___
*[pkg/cmd/roachtest/cluster.go, line 645 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76669#-Mw9zsCq7wFt9NIZq62o:-Mw9zsCq7wFt9NIZq62p:b6nca3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8b3171a1f0aca9b9f5ea63ae706bc67ab829eb2/pkg/cmd/roachtest/cluster.go#L645)):*
> ```Go
> 	// 1: on
> 	// 2: roll the dice on c.Start
> 	encryption int
> ```

`encryptionMode` might be less ambiguous; otherwise, the name implies it selects a type of encryption algo.
___
*[pkg/cmd/roachtest/cluster.go, line 1817 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76669#-MwA-mYeCZ1UCeW1LWyc:-MwA-mYeCZ1UCeW1LWyd:b-deb2qr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8b3171a1f0aca9b9f5ea63ae706bc67ab829eb2/pkg/cmd/roachtest/cluster.go#L1817)):*
> ```Go
> 	defer c.clearStatusForClusterOpt(startOpts.RoachtestOpts.Worker)
> 
> 	if startOpts.RoachtestOpts.DontEncrypt || c.encryption == 0 {
> ```

This seems weird. Say `c.encryptionMode == 1` (or even `c.encryptionMode == 2`), and the caller sets `DontEncrypt`; should that even be allowed? I can see how this could handle cluster re-use where previous test wants "encryption" and current doesn't. But, it seems error-prone because `c.encryptionMode` is no longer treated as an _invariant_ for the duration of that cluster. Wouldn't be cleaner to move `encryptionMode` compatibility logic into `selectTestForCluster` which already determines compatibility with `TestSpec.Cluster`.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76669)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan, @srosenberg, and @tbg)

___
*[pkg/cmd/roachtest/cluster.go, line 1817 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76669#-MwA-mYeCZ1UCeW1LWyc:-MwAQM30AyWcDCcuKpal:b-xupqpm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8b3171a1f0aca9b9f5ea63ae706bc67ab829eb2/pkg/cmd/roachtest/cluster.go#L1817)):*
I touched on this in the commit message:

> There is still a bit of "weird stuff" which I attempted to clean up.
Encryption can be enabled in one of two ways.

> You can either run `roachtest run --encrypt` which enables encryption
for all clusters, so the randomization doesn't matter. Without the
encrypt flag, randomization only applies to tests that *opt in*, via
`EncryptAtRandom`. The question is what tests like `tpccbench` want to
do; they currently hard-code encryption to off (i.e. they'll ignore the
`--encrypt` flag by setting `DontEncrypt` on their start opts) which
doesn't seem quite right; if I want to run tpccbench with `--encrypt`
that's what I should be getting. I therefore removed these workarounds
for all tests that employed them; if we run tests in nightlies with
`--encrypt` (which we don't anyway) then the right solution would
be for tests to detect that and to skip themselves. We can do that
when the need arises.

I then actually didn't remove the workarounds (thanks for indirectly pointing this out) and once there isn't a workaround there is also no need for this code. I can then change `c.StartE` to return an error if `DontEncrypt && encryption != 0`. Does that sound good?

> Wouldn't be cleaner to move encryptionMode compatibility logic into selectTestForCluster which already determines compatibility with TestSpec.Cluster.

That is likely true, let me take a stab at that as well. Will ping when it's ready.

**Review by srosenberg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76669)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @tbg)

___
*[pkg/cmd/roachtest/cluster.go, line 1817 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76669#-MwA-mYeCZ1UCeW1LWyc:-MwARyRDAN7SM3L71HoM:bge5mm6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8b3171a1f0aca9b9f5ea63ae706bc67ab829eb2/pkg/cmd/roachtest/cluster.go#L1817)):*
> I can then change c.StartE to return an error if DontEncrypt && encryption != 0. Does that sound good?

Yep, that works!

>That is likely true, let me take a stab at that as well. Will ping when it's ready.

:+1:

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76669)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @tbg)

___
*[pkg/cmd/roachtest/cluster.go, line 644 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76669#-MwBMHhE-B_XAzTNyU3_:-MwBMHhE-B_XAzTNyU3a:b-lxogbs) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8b3171a1f0aca9b9f5ea63ae706bc67ab829eb2/pkg/cmd/roachtest/cluster.go#L644)):*
> ```Go
> 	// 0: off
> 	// 1: on
> 	// 2: roll the dice on c.Start
> ```

Might be nice to define some constants for these values so that at the callsites we can reference them by name?

```golang
const (
	noEncrypt        = 0
	alwaysEncrypt    = 1
	encryptAtRandom  = 2
)
```

**Comment by tbg** [comment]
Added more commits to this. The TestSpec is now the place where you opt into random encryption. There are no more methods relating to this on the `Cluster` interface. The encryption randomization is propagated on `clusterImpl` before handing the cluster to the test, in just one place.

**Review by srosenberg — APPROVED** [review]
:lgtm:

> Reviewed 20 of 20 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76669#-:-MyPkkwC8k_IscskMS3Q:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

**Comment by tbg** [comment]
Added one more commit, PTAL

**Review by srosenberg — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76669#-:-MySOjLA-6pffO1YrTWz:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

**Comment by tbg** [comment]
bors r=srosenberg
TFTR!

**Pull request merged**
