### PR TITLE
ctxutil: introduce fast values

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### go.mod: update logtag dependency

See https://github.com/cockroachdb/logtags/pull/4

Epic: none
Release note: None

#### serverident: unexport ServerIdentificationContextKey

Epic: none
Release note: None

#### ctxutil: introduce fast values

This commit introduces a custom context type that can be used to more
efficiently associate values to contexts.

Instead of using arbitrary objects as keys, the keys are a small set
of integers. Any key must be globally registered first, and there is a
limited number that can be registered.

The `fastValuesCtx` stores *all* values for these keys, so traversing
the context hierarchy is not necessary. We also provide a way to add
multiple values at the same time, which saves on allocations.

I looked at before and after profiles in sysbench. Before:
 - CPU usage:
  context.value 0.6%
  context.WithValue 0.3%
  total 0.9%
 - Allocs:
  context.WithValue: 3.5%

After:
 - CPU usage:
  context.value + ctxutil.FastValue 0.5%
  context.WithValue 0.1%
  ctxutil.WithFastValue(s) 0.1%
  total 0.7%
 - Allocs:
  context.WithValue: 0.2%
  context.WithFastValue: 0.6%
  ctxutil.FastValuesBuilder.Finish: 1.4%
  total 2.2%

I will investigate improving on this, perhaps with providing a
pre-allocated context in codepaths where this is possible.

Informs: #136581
Informs: #135904
Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
Very cool!

> Reviewed 4 of 4 files at r1, 5 of 5 files at r2, 18 of 18 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137344#-:-ODxLxoZC_GP_Q-kneua:b-jdo7t9)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aa-joshi, @arjunmahishi, @kyle-a-wong, @RaduBerinde, @sambhav-jain-16, @shailendra-patel, and @tbg)

___
*[`pkg/util/log/ambient_context.go` line 132 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137344#-ODxJDIc13YwqcxoMR0k:-ODxJDIc13YwqcxoMR0l:b-p6396l) ([raw file](https://github.com/cockroachdb/cockroach/blob/b268391f80dfa7a50fa4f28009338849ffa85d6f/pkg/util/log/ambient_context.go#L132)):*
> ```Go
> 			existing := v.(*logtags.Buffer)
> 			newTags := existing.Merge(ac.tags)
> 			if newTags != existing {
> ```

Is it worth adding this kind of check to the exported interface of the `logtags` package? `logtags.NeedsTags`, or something like that?
___
*[`pkg/util/ctxutil/fast_value.go` line 49 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137344#-ODxKiRrEsAhnkKL1qjA:-ODxKiRrEsAhnkKL1qjB:bvqq5t6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b268391f80dfa7a50fa4f28009338849ffa85d6f/pkg/util/ctxutil/fast_value.go#L49)):*
> ```Go
> 	c := &fastValuesCtx{Context: parent}
> 	if p, ok := parent.(*fastValuesCtx); ok {
> 		// Connect to the grandparent context, since the parent won't do anything.
> ```

Checking my understanding: this might be more than the grandparent if we have multiple `fastValuesCtx` stacked up, right? It's just the first non-fastValuesCtx in the ctx stack?
___
*[`pkg/util/ctxutil/fast_value.go` line 51 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137344#-ODxL-3q86q_hU-kPbDa:-ODxL-3q86q_hU-kPbDb:b3iinwf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b268391f80dfa7a50fa4f28009338849ffa85d6f/pkg/util/ctxutil/fast_value.go#L51)):*
> ```Go
> 		// Connect to the grandparent context, since the parent won't do anything.
> 		c.Context = p.Context
> 		c.values = p.values
> ```

Probably worth giving this copy a comment explaining why we need to do it.
___
*[`pkg/util/ctxutil/fast_value.go` line 69 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137344#-ODxLC87E3YbxG5rs6fX:-ODxLC87E3YbxG5rs6fY:b5c5723) ([raw file](https://github.com/cockroachdb/cockroach/blob/b268391f80dfa7a50fa4f28009338849ffa85d6f/pkg/util/ctxutil/fast_value.go#L69)):*
> ```Go
> //	  b.Set(key1, val1)
> //	  b.Set(key2, val2)
> //		ctx = b.Finish()
> ```

nit : indentation is off on this line.
___
*[`pkg/util/ctxutil/fast_value.go` line 72 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137344#-ODxLIAk0i_XEq70KqdJ:-ODxLIAk0i_XEq70KqdK:b-ybf4rk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b268391f80dfa7a50fa4f28009338849ffa85d6f/pkg/util/ctxutil/fast_value.go#L72)):*
> ```Go
> func WithFastValues(parent context.Context) FastValuesBuilder {
> 	var bld FastValuesBuilder
> 	bld.parent = parent
> ```

Worth extracting this repeated logic into a helper?
___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowcontrol.go` line 440 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137344#-ODxIV8o-Fcy9kxCNL6Y:-ODxIV8o-Fcy9kxCNL6Z:b-kzz3wu) ([raw file](https://github.com/cockroachdb/cockroach/blob/b268391f80dfa7a50fa4f28009338849ffa85d6f/pkg/kv/kvserver/kvflowcontrol/kvflowcontrol.go#L440)):*
> ```Go
> }
> 
> var RaftAdmissionMetaKey = ctxutil.RegisterFastValueKey()
> ```

Why export this?

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137344#-:-ODxdhzY5Cp2lC18Ha6B:b-814g8k)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aa-joshi, @arjunmahishi, @kyle-a-wong, @nvanbenschoten, @sambhav-jain-16, @shailendra-patel, and @tbg)

___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowcontrol.go` line 440 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137344#-ODxIV8o-Fcy9kxCNL6Y:-ODxbrix3UYWDaiUG_HN:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/b268391f80dfa7a50fa4f28009338849ffa85d6f/pkg/kv/kvserver/kvflowcontrol/kvflowcontrol.go#L440)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why export this?
</blockquote></details>

Fixed.
___
*[`pkg/util/ctxutil/fast_value.go` line 49 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137344#-ODxKiRrEsAhnkKL1qjA:-ODxc49iEd-QzxiWJd1G:b2zp0b4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b268391f80dfa7a50fa4f28009338849ffa85d6f/pkg/util/ctxutil/fast_value.go#L49)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Checking my understanding: this might be more than the grandparent if we have multiple `fastValuesCtx` stacked up, right? It's just the first non-fastValuesCtx in the ctx stack?
</blockquote></details>

Right, the same code when we created the parent would have ensured that its parent is not `fastValuesCtx`
___
*[`pkg/util/ctxutil/fast_value.go` line 72 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137344#-ODxLIAk0i_XEq70KqdJ:-ODxcwA979QptJHNxF6C:bl4nnsh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b268391f80dfa7a50fa4f28009338849ffa85d6f/pkg/util/ctxutil/fast_value.go#L72)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Worth extracting this repeated logic into a helper?
</blockquote></details>

I wanted to avoid yet another stack trace showing up in profiles :)
___
*[`pkg/util/log/ambient_context.go` line 132 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137344#-ODxJDIc13YwqcxoMR0k:-ODxe87Q4CQPCx8qbxbb:be1txj2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b268391f80dfa7a50fa4f28009338849ffa85d6f/pkg/util/log/ambient_context.go#L132)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is it worth adding this kind of check to the exported interface of the `logtags` package? `logtags.NeedsTags`, or something like that?
</blockquote></details>

Not sure how it would work here. Note that we're reading the existing value "for free" because it's already inside `bld`

**Review by tbg — APPROVED** [review]
:lgtm: nice!

I ran `./pkg/sql/tests -b -r 'BenchmarkSysbench/SQL/3node/oltp_read_only' -d 1000x -c 10` and saw a ~0.97% reduction in allocs.

```
name                                  old time/op    new time/op    delta
Sysbench/SQL/3node/oltp_read_only-10    2.70ms ± 5%    2.71ms ± 6%    ~     (p=0.605 n=9+9)

name                                  old alloc/op   new alloc/op   delta
Sysbench/SQL/3node/oltp_read_only-10    1.17MB ± 0%    1.17MB ± 1%    ~     (p=0.156 n=9+10)

name                                  old allocs/op  new allocs/op  delta
Sysbench/SQL/3node/oltp_read_only-10     4.85k ± 0%     4.80k ± 1%  -0.97%  (p=0.000 n=9+10)
```

> Reviewed 4 of 4 files at r1, 5 of 5 files at r2, 18 of 18 files at r4, 18 of 18 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137344#-:-ODzlEr6-QkFZv1BFp95:bgj60u1)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aa-joshi, @arjunmahishi, @kyle-a-wong, @nvanbenschoten, @RaduBerinde, @sambhav-jain-16, and @shailendra-patel)

___
*[`pkg/base/serverident/server_ident.go` line 21 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/137344#-ODzhmEh9FNEi5iBkBbE:-ODzhmEh9FNEi5iBkBbF:b-lsuihb) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c0ce843343c44037f3c620d57bc2cb376e8a7bb/pkg/base/serverident/server_ident.go#L21)):*
> ```Go
> // ServerIdentificationContextKey is the fast value key used to annotate a
> // context with a ServerIdentificationPayload.
> var ServerIdentificationContextKey = ctxutil.RegisterFastValueKey()
> ```

huh, didn't you just unexport this in a previous commit?

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137344#-:-OE-gZxJBr4hd63K0yP1:b-814g8k)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aa-joshi, @arjunmahishi, @kyle-a-wong, @nvanbenschoten, @sambhav-jain-16, @shailendra-patel, and @tbg)

___
*[`pkg/base/serverident/server_ident.go` line 21 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/137344#-ODzhmEh9FNEi5iBkBbE:-OE-gP7JBGqt-1UsDLOW:b-z5ndio) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c0ce843343c44037f3c620d57bc2cb376e8a7bb/pkg/base/serverident/server_ident.go#L21)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

huh, didn't you just unexport this in a previous commit?
</blockquote></details>

I did, but then I had to export it so I can set it together with another value. Still, clearing out all the test code that used it directly was worthwhile.

**Review by RaduBerinde — COMMENTED** [review]
I made two fixes (that together were masking a bug): `ResetAndAnnotateCtx` now sets the keys unconditionally (since we want to override any previous values); and I removed the `WithFastValues` optimization if no values are set (we were incorrectly returning the grandparent context if the parent was a `fastValuesCtx`). I don't think the optimization was of consequence in practice.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137344#-:-OE10Dey8xF9PqsSlDz3:bpo51na)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aa-joshi, @arjunmahishi, @kyle-a-wong, @nvanbenschoten, @sambhav-jain-16, @shailendra-patel, and @tbg)

**Pull request merged**
