### PR TITLE
Document two invariants on the table descriptor version.

### PR DESCRIPTION
**Pull request by vivekmenezes**
Prepare the code to maintain those invariants.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3329)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/schema_changer.go, line 61 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329#-K4ibate_1MieqNbhgiJ:-K4ibate_1MieqNbhgiK:-935785682) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d19594dfcabbe7d13b398d13a66962b94698a1b/sql/schema_changer.go#L61)):*
Perhaps this is a work in progress, but I don't see what this gives you over just incrementing the `Version` in the caller. You're not even checking that `tableDesc.UpVersion` is true here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/schema_changer.go, line 61 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329#-K4ibate_1MieqNbhgiJ:-K4ih8bdCOhVkHljSFSe:-297969959) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d19594dfcabbe7d13b398d13a66962b94698a1b/sql/schema_changer.go#L61)):*
Yeah it's really for another future change where this code gets put into Publish(). I thought it was nice to have it in here so that the TODO commment in the proto file makes sense. I've changed it to up the version only if UpVersion is set.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329)*

**Comment by vivekmenezes** [comment]
I changed the documentation and the semantics a bit. I think it's much more consistent and as a result better. It took me quite some time to settle on something as small as this.

**Comment by petermattis** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/grant.go, line 47 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329#-K4tZ7uQwkA-VVw0b-0W:-K4tZ7uQwkA-VVw0b-0X:-1912903587) ([raw file](https://github.com/cockroachdb/cockroach/blob/06e0d4fe8855f1bd7f252f96725d25e554cc4c60/sql/grant.go#L47)):*
I still am not understanding the point of this. I thought the invariants were that the up version was only applied by publishing. This just seems to obfuscate how the version is incremented. If this is a work in progress, add a TODO comment here and elsewhere you are calling `applyUpVersion`.

---

*[sql/structured.proto, line 212 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329#-K4tYvz979O3ZdePKJrw:-K4tYvz979O3ZdePKJrx:-1747188314) ([raw file](https://github.com/cockroachdb/cockroach/blob/06e0d4fe8855f1bd7f252f96725d25e554cc4c60/sql/structured.proto#L212)):*
`s/version/up_version/g`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/grant.go, line 47 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329#-K4tZ7uQwkA-VVw0b-0W:-K4uc4LjrimQ2bH_Q4_o:-600704540) ([raw file](https://github.com/cockroachdb/cockroach/blob/06e0d4fe8855f1bd7f252f96725d25e554cc4c60/sql/grant.go#L47)):*
The TODO comment is in structured.proto. I'm going to keep
tableDesc.UpVersion = true and 
remove
p.applyUpVersion(tableDesc) from here in a future change.

---

*[sql/structured.proto, line 212 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329#-K4tYvz979O3ZdePKJrw:-K4ucpA495bgWb43ctL_:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/06e0d4fe8855f1bd7f252f96725d25e554cc4c60/sql/structured.proto#L212)):*
done

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329)*

**Comment by vivekmenezes** [comment]
is this ok to merge?

---

Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329#-:-K4xTkZJNV9ioECZNCSq:-981481383)*

**Comment by tamird** [comment]
Reviewed 7 of 8 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[sql/structured.proto, line 212 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329#-K4tYvz979O3ZdePKJrw:-K4tm8Pkh7EtHZHzR4zn:-1398177206) ([raw file](https://github.com/cockroachdb/cockroach/blob/06e0d4fe8855f1bd7f252f96725d25e554cc4c60/sql/structured.proto#L212)):*
Huh? this was correct before. The comment above is for `version`, not `up_version`.

---

*[sql/structured.proto, line 190 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329#-K4xcBgKtk5uSLsISmWX:-K4xcBgKtk5uSLsISmWY:983525710) ([raw file](https://github.com/cockroachdb/cockroach/blob/a50db72fcf9b6cc2a5a098afa341f280cb563453/sql/structured.proto#L190)):*
s/mark/set/

---

*[sql/structured.proto, line 192 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329#-K4xcEDcriXdHJi9eZDe:-K4xcEDcriXdHJi9eZDf:-1586476745) ([raw file](https://github.com/cockroachdb/cockroach/blob/a50db72fcf9b6cc2a5a098afa341f280cb563453/sql/structured.proto#L192)):*
remove the comma. s/ups/increments/

---

*[sql/structured.proto, line 193 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329#-K4xcN_0dD_tk1xYgO9N:-K4xcN_0dD_tk1xYgO9O:506011116) ([raw file](https://github.com/cockroachdb/cockroach/blob/a50db72fcf9b6cc2a5a098afa341f280cb563453/sql/structured.proto#L193)):*
instead of "maintaining", can you be explicit and explain that it waits for all leases for `v - 1` to expire?

---

*[sql/structured.proto, line 194 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329#-K4xcKzxrNTOJhCopy1s:-K4xcKzxrNTOJhCopy1t:1050109523) ([raw file](https://github.com/cockroachdb/cockroach/blob/a50db72fcf9b6cc2a5a098afa341f280cb563453/sql/structured.proto#L194)):*
s/up/increment/

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329)*

**Comment by vivekmenezes** [comment]
Review status: 6 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[sql/structured.proto, line 212 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329#-K4tYvz979O3ZdePKJrw:-K4xeXeMglOkYZhzIMay:-652518513) ([raw file](https://github.com/cockroachdb/cockroach/blob/06e0d4fe8855f1bd7f252f96725d25e554cc4c60/sql/structured.proto#L212)):*
The comment above is for both version and up_version

---

*[sql/structured.proto, line 190 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329#-K4xcBgKtk5uSLsISmWX:-K4xf0i67Z2gMwjRD8iT:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/a50db72fcf9b6cc2a5a098afa341f280cb563453/sql/structured.proto#L190)):*
done

---

*[sql/structured.proto, line 192 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329#-K4xcEDcriXdHJi9eZDe:-K4xfX8UnvKXuc8CNMqu:-130177653) ([raw file](https://github.com/cockroachdb/cockroach/blob/a50db72fcf9b6cc2a5a098afa341f280cb563453/sql/structured.proto#L192)):*
done. reworded a bit.

---

*[sql/structured.proto, line 193 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329#-K4xcN_0dD_tk1xYgO9N:-K4xh1_kbDDjOInMEPx_:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/a50db72fcf9b6cc2a5a098afa341f280cb563453/sql/structured.proto#L193)):*
done

---

*[sql/structured.proto, line 194 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329#-K4xcKzxrNTOJhCopy1s:-K4xfj6Njm9UqAcKkbxy:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/a50db72fcf9b6cc2a5a098afa341f280cb563453/sql/structured.proto#L194)):*
done

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/structured.proto, line 212 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329#-K4tYvz979O3ZdePKJrw:-K4xiCNPATIO1Bjq6fe7:-2107682984) ([raw file](https://github.com/cockroachdb/cockroach/blob/06e0d4fe8855f1bd7f252f96725d25e554cc4c60/sql/structured.proto#L212)):*
That's true, but its placement suggests that it is for `version`, while this comment suggests that it is for `up_version`. This should be "See comment [for version] above."

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329)*

**Comment by vivekmenezes** [comment]
Review status: 6 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/structured.proto, line 212 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329#-K4tYvz979O3ZdePKJrw:-K4xn7hlqoQTO3u8bke1:-2029906648) ([raw file](https://github.com/cockroachdb/cockroach/blob/06e0d4fe8855f1bd7f252f96725d25e554cc4c60/sql/structured.proto#L212)):*
changed to: See comment for [version] above.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/structured.proto, line 212 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329#-K4tYvz979O3ZdePKJrw:-K4xoI0L4ORUMOm2pl0Y:928363288) ([raw file](https://github.com/cockroachdb/cockroach/blob/06e0d4fe8855f1bd7f252f96725d25e554cc4c60/sql/structured.proto#L212)):*
Sorry, I wasn't clear but I meant the square brackets to mean "this part is optional". I wouldn't include them as literals here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329)*

**Comment by vivekmenezes** [comment]
Review status: 6 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/structured.proto, line 212 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329#-K4tYvz979O3ZdePKJrw:-K4yGCILtDbIXT0fy5S-:-321354618) ([raw file](https://github.com/cockroachdb/cockroach/blob/06e0d4fe8855f1bd7f252f96725d25e554cc4c60/sql/structured.proto#L212)):*
"See comment above."

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329)*

**Comment by vivekmenezes** [comment]
@petermattis can I merge this?

**Comment by petermattis** [comment]
LGTM

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3329#-:-K51k25BziYKep6v2a57:676834233)*

**Pull request merged**
