### PR TITLE
builtins: implement ST_CombineBBox

### LINKED ISSUE #52899: geo/geomfn: implement ST_CombineBbox({box2d,geometry})
Implement `ST_CombineBbox` on arguments {box2d,geometry}, which should adopt [PostGIS behaviour](https://postgis.net/docs/ST_CombineBbox.html).

_Observers: Please react to this issue if you need this functionality._

For Geometry builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geomfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geomfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
  * When using GEOS, you can reference the [C API](https://github.com/libgeos/geos/blob/master/capi/geos_c.h.in) for which functions are available. Unfortunately, Windows is not currently supported when using GEOS.
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go). Note that we currently do not support optional arguments, so we define functions that have optional arguments once without the optional argument (using the default value in the optional position), and once with the optional argument.
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output. Tests here should just ensure the builtin is linked end to end (your exhaustive unit tests go the above mentioned packages!).
* Ensure the documentation is regenerated by calling `make buildshort`. You can also play with it by calling `./cockroach demo --empty` afterwards.
* Submit your PR - make sure to follow the guidelines from [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

You can follow #48552 for an example PR.

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-08-17T14:47:50Z. Changes to titles, body and labels may be overwritten.</sub>

### PR DESCRIPTION
**Pull request by otan**
Resolves #52899.

Release note (sql change): Implement the ST_CombineBBox builtin.

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52903)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/geo/bbox.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52903#-MEy7juDEofuk7Wx2XRi:-MEy7juDEofuk7Wx2XRj:bk6410m) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72ad86cb5628f6ee9d806867bb27344f2ff86bd/pkg/geo/bbox.go#L106)):*
> ```Go
> 		}
> 	}
> 	return &CartesianBoundingBox{
> ```

Does this mean a heap allocation of a new `CartesianBoundingBox`? There are existing callers that don't need the immutability and call this in a loop.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52903)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/geo/bbox.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52903#-MEy7juDEofuk7Wx2XRi:-MEyPKaz8iKlktzd4PL7:b-36l2wh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72ad86cb5628f6ee9d806867bb27344f2ff86bd/pkg/geo/bbox.go#L106)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Does this mean a heap allocation of a new `CartesianBoundingBox`? There are existing callers that don't need the immutability and call this in a loop.
</blockquote></details>

made a non-copy version!

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52903#-:-MEyv1Lr1LxapqD1ZOqp:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Comment by otan** [comment]
bors r=sumeerbhola

**Pull request merged**
