### PR TITLE
sql: require an enterprise license to use generic query plans

### PR DESCRIPTION
**Pull request by mgartner**
Epic: CRDB-37712

Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

nit: it might be nice to mark `gqpccl` package as owned by SQL Queries team in CODEOWNERS.

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127214#-:-O1telEn0uwnhaQWd8xc:binf38h)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

**Review by mgartner — COMMENTED** [review]
> nit: it might be nice to mark `gqpccl` package as owned by SQL Queries team in CODEOWNERS.

Good catch. Looks like the linter requires it. :+1: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127214#-:-O1w6MAE--PnqbUYSmMG:biyls3g)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 16 of 16 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127214#-:-O1wGUew-Owq5Y7kD4mN:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
