### PR TITLE
geo/geomfn: implement ST_Relate and ST_ContainsProperly

### PR DESCRIPTION
**Pull request by otan**
Commit on top of https://github.com/cockroachdb/cockroach/pull/48522.

Added ST_ContainsProperly to the optimizer as well that calls it to use
Covers.

Also update the RFC to claim ST_ContainsProperly as indexed backed.

Release note (sql change): Implemented the geometry based builtins
`ST_Relate` and `ST_ContainsProperly`.

### CODE REVIEW

**Comment by mjibson** [comment]
opt parts lgtm

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
only minor comments -- looks good overall

> Reviewed 13 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48552#-:-M6oaha64Muw2Wq2x8v9:bikdmdg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[docs/RFCS/20200421_geospatial.md, line 1043 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48552#-M6oUiJM3YNdw824kQi6:-M6oUiJM3YNdw824kQi7:bpdcba9) ([raw file](https://github.com/cockroachdb/cockroach/blob/12b5e70961cbd73ef67a0f7d2c0c0e88aa626c07/docs/RFCS/20200421_geospatial.md#L1043)):*
> ```Markdown
> * ST_Contains(g, x), ST_Contains(x, g): use contains(g, x) or
>   contained-by(g, x)
> * ST_ContainsProperly(g, x), ST_ContainsProperly(x, g): see above.
> ```

nit: please repeat the text from the previous bullet
___
*[pkg/geo/geomfn/binary_predicates.go, line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48552#-M6oZ2v37SL36aPSIcZr:-M6oZ2v41IfIxWxlvCZc:b-bu80sq) ([raw file](https://github.com/cockroachdb/cockroach/blob/12b5e70961cbd73ef67a0f7d2c0c0e88aa626c07/pkg/geo/geomfn/binary_predicates.go#L49)):*
> ```
> T**FF*FF*
> ```

There is some redundancy in DE-9IM -- when I tried to construct I came up with `TF*FF*FF*`, but I think it is equivalent to what you wrote above.
___
*[pkg/geo/geomfn/de9im.go, line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48552#-M6oWN-35so7juMxY7De:-M6oWN-35so7juMxY7Df:bt28aew) ([raw file](https://github.com/cockroachdb/cockroach/blob/12b5e70961cbd73ef67a0f7d2c0c0e88aa626c07/pkg/geo/geomfn/de9im.go#L31)):*
> ```Go
> // MatchesDE9IM checks whether the given DE-9IM relation matches the DE-91M pattern.
> // See: https://en.wikipedia.org/wiki/DE-9IM.
> func MatchesDE9IM(str string, pattern string) (bool, error) {
> ```

I am assuming `str` cannot have * since it represents the actual computed relation.
If yes, can you add that to this function comment.
___
*[pkg/geo/geomfn/de9im.go, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48552#-M6oZfBA7yrxhOI9a2YL:-M6oZfBA7yrxhOI9a2YM:bi0bbvn) ([raw file](https://github.com/cockroachdb/cockroach/blob/12b5e70961cbd73ef67a0f7d2c0c0e88aa626c07/pkg/geo/geomfn/de9im.go#L43)):*
> ```Go
> 			continue
> 		case 't':
> 			if str[i] < '0' || str[i] > '2' {
> ```

when do we expect `< 0`?
Can you add a comment that `f` represents false and that `0`, `1`, `2` are true?
I think it would be easier to read if we added a conversion function to a bool.
___
*[pkg/geo/geos/geos.cc, line 430 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48552#-M6o_qp78XEOGxu9z5bc:-M6o_qp8EnE_-UYgR1Gw:b-q9cgda) ([raw file](https://github.com/cockroachdb/cockroach/blob/12b5e70961cbd73ef67a0f7d2c0c0e88aa626c07/pkg/geo/geos/geos.cc#L430)):*
> ```cpp
> 
> //
> // DE-9IM related
> ```

Please add the wikipedia link

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48552)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/geo/geomfn/binary_predicates.go, line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48552#-M6oZ2v37SL36aPSIcZr:-M6olQqX-N9qqy3Z-68a:b-i2ikg9) ([raw file](https://github.com/cockroachdb/cockroach/blob/12b5e70961cbd73ef67a0f7d2c0c0e88aa626c07/pkg/geo/geomfn/binary_predicates.go#L49)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> ```
> T**FF*FF*
> ```

There is some redundancy in DE-9IM -- when I tried to construct I came up with `TF*FF*FF*`, but I think it is equivalent to what you wrote above.
</blockquote></details>

I cheated and used what was on https://postgis.net/docs/ST_ContainsProperly.html.
___
*[pkg/geo/geomfn/de9im.go, line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48552#-M6oWN-35so7juMxY7De:-M6p-HTUDemKpOOcBahG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/12b5e70961cbd73ef67a0f7d2c0c0e88aa626c07/pkg/geo/geomfn/de9im.go#L31)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I am assuming `str` cannot have * since it represents the actual computed relation.
If yes, can you add that to this function comment.
</blockquote></details>

Done.
___
*[pkg/geo/geomfn/de9im.go, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48552#-M6oZfBA7yrxhOI9a2YL:-M6p-bDE9LkwG5exOMLG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/12b5e70961cbd73ef67a0f7d2c0c0e88aa626c07/pkg/geo/geomfn/de9im.go#L43)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

when do we expect `< 0`?
Can you add a comment that `f` represents false and that `0`, `1`, `2` are true?
I think it would be easier to read if we added a conversion function to a bool.
</blockquote></details>

Done.
___
*[pkg/geo/geos/geos.cc, line 430 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48552#-M6o_qp78XEOGxu9z5bc:-M6p-ndWBxyVItpx_y8M:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/12b5e70961cbd73ef67a0f7d2c0c0e88aa626c07/pkg/geo/geos/geos.cc#L430)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Please add the wikipedia link
</blockquote></details>

Done.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48552)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/geo/geomfn/de9im.go, line 29 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48552#-M6pXQhN9KBtQqKOU3Rw:-M6pXQhN9KBtQqKOU3Rx:bn57uuz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d74dd019d353f969b3ebd5fd59cceba138219220/pkg/geo/geomfn/de9im.go#L29)):*
> ```Go
> 
> // MatchesDE9IM checks whether the given DE-9IM relation matches the DE-91M pattern.
> // Assumes the relation has been computed, and such has no 'T' characters.
> ```

did you mean '`*`'?
___
*[pkg/geo/geomfn/de9im.go, line 54 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48552#-M6pYkppC0Lbc6fH_q2P:-M6pYkppC0Lbc6fH_q2Q:bybwnew) ([raw file](https://github.com/cockroachdb/cockroach/blob/d74dd019d353f969b3ebd5fd59cceba138219220/pkg/geo/geomfn/de9im.go#L54)):*
> ```Go
> // Pattern matches are as follows:
> // * '*': allow anything.
> // * 'T': allow only if the relation is '0' (point), '1' (line) or '2' (polygon).
> ```

'T' or 't': allow if the relation is true, which is represented by any of the characters '0' (point), '1' (line) or '2' (area) (representing the dimensionality of the intersection).
___
*[pkg/geo/geomfn/de9im.go, line 55 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48552#-M6pXdzp4cD6o-i2RbxV:-M6pXdzp4cD6o-i2RbxW:b-iucuwp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d74dd019d353f969b3ebd5fd59cceba138219220/pkg/geo/geomfn/de9im.go#L55)):*
> ```Go
> // * '*': allow anything.
> // * 'T': allow only if the relation is '0' (point), '1' (line) or '2' (polygon).
> // * 'f': allow only if relation is also false.
> ```

'F' or 'f': allow only if the relation is false, which is represented by the characters 'f' or 'F'.
___
*[pkg/geo/geomfn/de9im.go, line 62 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48552#-M6pYCqW9E1gpSuBsEWc:-M6pYCqW9E1gpSuBsEWd:b-pr1ccy) ([raw file](https://github.com/cockroachdb/cockroach/blob/d74dd019d353f969b3ebd5fd59cceba138219220/pkg/geo/geomfn/de9im.go#L62)):*
> ```Go
> 	case 't':
> 		// True should only match characters 0-2. 'T' should never exist
> 		// in a relation.
> ```

I think one can drop this last sentence "'T' should never exist ..."

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48552)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/geo/geomfn/de9im.go, line 29 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48552#-M6pXQhN9KBtQqKOU3Rw:-M6pqTsv9NtDKJdFAUWp:bb15jjt) ([raw file](https://github.com/cockroachdb/cockroach/blob/d74dd019d353f969b3ebd5fd59cceba138219220/pkg/geo/geomfn/de9im.go#L29)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

did you mean '`*`'?
</blockquote></details>

both, actually.
___
*[pkg/geo/geomfn/de9im.go, line 54 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48552#-M6pYkppC0Lbc6fH_q2P:-M6pqyDV1NiTKjlsq12x:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d74dd019d353f969b3ebd5fd59cceba138219220/pkg/geo/geomfn/de9im.go#L54)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

'T' or 't': allow if the relation is true, which is represented by any of the characters '0' (point), '1' (line) or '2' (area) (representing the dimensionality of the intersection).
</blockquote></details>

Done.
___
*[pkg/geo/geomfn/de9im.go, line 55 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48552#-M6pXdzp4cD6o-i2RbxV:-M6pqyc64b0Q9bJKF_eZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d74dd019d353f969b3ebd5fd59cceba138219220/pkg/geo/geomfn/de9im.go#L55)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

'F' or 'f': allow only if the relation is false, which is represented by the characters 'f' or 'F'.
</blockquote></details>

Done.
___
*[pkg/geo/geomfn/de9im.go, line 62 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48552#-M6pYCqW9E1gpSuBsEWc:-M6pr0XrAAQ6rNU8PMas:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d74dd019d353f969b3ebd5fd59cceba138219220/pkg/geo/geomfn/de9im.go#L62)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think one can drop this last sentence "'T' should never exist ..."
</blockquote></details>

Done.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 13 of 16 files at r1, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48552)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/geo/geomfn/de9im.go, line 54 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/48552#-M6q7xq46J9ZbXPVDwpM:-M6q7xq46J9ZbXPVDwpN:b-gt8h7r) ([raw file](https://github.com/cockroachdb/cockroach/blob/060cf58b2f3b3a4e0a8d3129442ec949bb875320/pkg/geo/geomfn/de9im.go#L54)):*
> ```Go
> // Pattern matches are as follows:
> // * '*': allow anything.
> // * 't'/'T': allow only if the relation is tryem which is represented any of
> ```

s/tryem/true/

... is represented by any of ...
___
*[pkg/geo/geomfn/de9im.go, line 55 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/48552#-M6q8CoP8OBaWz64WSVr:-M6q8CoP8OBaWz64WSVs:b-6ta7vs) ([raw file](https://github.com/cockroachdb/cockroach/blob/060cf58b2f3b3a4e0a8d3129442ec949bb875320/pkg/geo/geomfn/de9im.go#L55)):*
> ```Go
> // * '*': allow anything.
> // * 't'/'T': allow only if the relation is tryem which is represented any of
> //   '0' (point), '1' (line) or '2' (polygon) which are the dimensionality of the
> ```

s/polygon/area

... which is the dimensionality ...

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48552)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/geo/geomfn/de9im.go, line 54 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/48552#-M6q7xq46J9ZbXPVDwpM:-M6qmFUv8m_ufvVUUOLm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/060cf58b2f3b3a4e0a8d3129442ec949bb875320/pkg/geo/geomfn/de9im.go#L54)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

s/tryem/true/

... is represented by any of ...
</blockquote></details>

Done.
___
*[pkg/geo/geomfn/de9im.go, line 55 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/48552#-M6q8CoP8OBaWz64WSVr:-M6qmFttCyYKjAFwrQ1N:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/060cf58b2f3b3a4e0a8d3129442ec949bb875320/pkg/geo/geomfn/de9im.go#L55)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

s/polygon/area

... which is the dimensionality ...
</blockquote></details>

Done.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48552#-:-M78iwAR1pnDpnYISuJ8:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Comment by otan** [comment]
bors r=sumeerbhola

**Comment by otan** [comment]
flakes galore!

bors r=sumeerbhola

**Comment by otan** [comment]
bors r=sumeerbhola

**Pull request merged**
