### PR TITLE
sql: fix memory accounting of prepared statements and portals in error cases

### PR DESCRIPTION
**Pull request by yuzefovich**
**sql: make sure to close mem acc of prepared stmt in case of an error**

Previously, it was possible that we would not close the memory account
created for a prepared statement when an error is encountered. This was
the case because we would not include the prepared stmt into the prep
stmts namespace, so it would just get lost. However, up until recently
this was not an issue since we mistakenly cleared that memory account
when creating the prepared statement.

Release note: None

**sql: only increment ref count of prep stmt in non-error case of portals**

Previously, it was possible to "leak" a reference to a prepared
statement if we made a portal from it (i.e. took a reference to the
prepared statement) and the memory reservation was denied. This could
lead to "leftover bytes" errors when stopping the "session" monitors.
However, the impact is minor because on release builds we'd still return
those "leftover bytes" and would just file a sentry issue. This is now
fixed.

Fixes: #83935

Release note: None

### CODE REVIEW

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84049)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @yuzefovich)

___
*[`pkg/sql/conn_executor_prepare.go` line 103 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84049#-N6iBVdP90L_Ofiw-kZZ:-N6iBVdQ75vd06fM-xGQ:bcrs4gj) ([raw file](https://github.com/cockroachdb/cockroach/blob/27330ca0155f67a3d938c736f4c6ba6d50592e71/pkg/sql/conn_executor_prepare.go#L103)):*
> ```Go
> 	// Prepare the query. This completes the typing of placeholders.
> 	prepared, err := ex.prepare(ctx, stmt, placeholderHints, rawTypeHints, origin)
> 	if err != nil {
> ```

[nit] Are there cases where error is non-nil but we don't want to close the account? If not, we might be nice to close the account here instead of in `prepare` for symmetry with the other two cases. Up to you though, it doesn't really matter.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84049)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @DrewKimball, and @mgartner)

___
*[`pkg/sql/conn_executor_prepare.go` line 103 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84049#-N6iBVdP90L_Ofiw-kZZ:-N6iWhl74YB58BOFfKc0:b-hj971f) ([raw file](https://github.com/cockroachdb/cockroach/blob/27330ca0155f67a3d938c736f4c6ba6d50592e71/pkg/sql/conn_executor_prepare.go#L103)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Are there cases where error is non-nil but we don't want to close the account? If not, we might be nice to close the account here instead of in `prepare` for symmetry with the other two cases. Up to you though, it doesn't really matter.
</blockquote></details>

I think we want to close the account in all cases when the reference to the prepared statement is lost (i.e. not assigned into `ex.extraTxnState.prepStmtsNamespace.prepStmts` map). If an error is returned by `ex.prepare`, then `prepared` seems to be `nil` in all cases, so I think it's better to keep closing the account inside of the function there.

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84049#-:-N6i_PTK-akk5T4sdVPX:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @yuzefovich)

___
*[`pkg/sql/conn_executor_prepare.go` line 103 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84049#-N6iBVdP90L_Ofiw-kZZ:-N6i_RH98_eJxPtBYNXS:b-lt0lyy) ([raw file](https://github.com/cockroachdb/cockroach/blob/27330ca0155f67a3d938c736f4c6ba6d50592e71/pkg/sql/conn_executor_prepare.go#L103)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I think we want to close the account in all cases when the reference to the prepared statement is lost (i.e. not assigned into `ex.extraTxnState.prepStmtsNamespace.prepStmts` map). If an error is returned by `ex.prepare`, then `prepared` seems to be `nil` in all cases, so I think it's better to keep closing the account inside of the function there.
</blockquote></details>

I see, makes sense.

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
