### PR TITLE
kvserver: QueryResolvedTimestamp should declare lock table keys

### PR DESCRIPTION
**Pull request by shralex**
Release note: None

### CODE REVIEW

**Comment by shralex** [comment]
The following consistently fails without this PR, and passes (10 times in a row) with the PR: make testrace PKG=./pkg/kv/kvserver TESTS=TestServerSideBoundedStalenessNegotiation TESTFLAGS="-v --show-logs"

**Comment by erikgrinaker** [comment]
I don't think this is the right way to address this. Whenever we declare access for a key span, we implicitly declare access for the corresponding lock table span: any reader of key `A` _must_ also read any intents (locks) of `A`, and similarly any writer of `A` _must_ also write an intent (lock) for `A`. So I think these accesses should be declared automagically by e.g. `DefaultDeclareKeys` or some other mechanism.

We addressed a similar issue in #65124, with discussion in #64088, where we automatically declare these accesses for certain code paths. Can't remember the details, but it's worth looking into precisely what is causing this to fail and why that PR was insufficient.

**Comment by erikgrinaker** [comment]
Had another look at this. What #65124 did is basically, when spanset assertions are enabled (during race builds), to modify the declared spans before passing them to the spanset asserter -- but only on the write path:

https://github.com/cockroachdb/cockroach/blob/fcaed2e1a3cd6712b43936b54c446e89588b9abf/pkg/kv/kvserver/replica_write.go#L750-L763

In this case, we're only doing reads, so we would have to do something similar on the read path:

https://github.com/cockroachdb/cockroach/blob/a5708ab8dae9bf4d3ff951ca3fac8312c4db01df/pkg/kv/kvserver/replica_read.go#L65-L67

However, this doesn't seem right to me, and I see that @sumeerbhola has been having similar misgivings about this approach:

https://github.com/cockroachdb/cockroach/blob/fcaed2e1a3cd6712b43936b54c446e89588b9abf/pkg/kv/kvserver/replica_write.go#L768-L769

The problem is basically with direct access to the lock table via low-level `Engine` methods. Normally, we only interact with the lock table _internally_ in the MVCC APIs, with callers only accessing the main (non-lock) keys that are already correctly declared and asserted -- so this works fine. But we need to somehow handle access to the lock table directly.

Short-term, I think modifying the asserted spans on the read path is sort of ok -- it's no worse than what we're already doing on the write path. So let's do that for now just to fix the test failures. Something like this seems to work:

```diff
diff --git a/pkg/kv/kvserver/replica_read.go b/pkg/kv/kvserver/replica_read.go
index 2ec932fb1a..64265b72fb 100644
--- a/pkg/kv/kvserver/replica_read.go
+++ b/pkg/kv/kvserver/replica_read.go
@@ -14,6 +14,7 @@ import (
        "context"
        "sync"
 
+       "github.com/cockroachdb/cockroach/pkg/keys"
        "github.com/cockroachdb/cockroach/pkg/kv/kvserver/batcheval"
        "github.com/cockroachdb/cockroach/pkg/kv/kvserver/batcheval/result"
        "github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency"
@@ -63,7 +64,16 @@ func (r *Replica) executeReadOnlyBatch(
                panic("expected consistent iterators")
        }
        if util.RaceEnabled {
-               rw = spanset.NewReadWriterAt(rw, spans, ba.Timestamp)
+               assertSpans := spans.Copy()
+               spans.Iterate(func(sa spanset.SpanAccess, _ spanset.SpanScope, span spanset.Span) {
+                       ltKey, _ := keys.LockTableSingleKey(span.Key, nil)
+                       var ltEndKey roachpb.Key
+                       if span.EndKey != nil {
+                               ltEndKey, _ = keys.LockTableSingleKey(span.EndKey, nil)
+                       }
+                       assertSpans.AddNonMVCC(sa, roachpb.Span{Key: ltKey, EndKey: ltEndKey})
+               })
+               rw = spanset.NewReadWriterAt(rw, assertSpans, ba.Timestamp)
        }
        defer rw.Close()
```

Medium-term, let's consider how the lock table should interact with span declarations. We have a few options:

1. Make the spanset asserter itself automatically add on corresponding lock table spans, and only rely on the main key spans for locking/latching access to lock table keys. This is safe, because we assume a direct relationship between a key and its lock, where readers/writers need the same access to both, so relying on the main key alone is fine. However, we probably want to explicitly disallow declaring lock table spans, to enforce the invariant that locks/latches are always taken out on the main key.

2. Make commands that directly access the lock table declare this in their key spans. Commands that only interact with the lock table via MVCC commands do not need to declare this. In this case, we must be careful with sequencing/locking of commands where e.g. one command declares `A`, and another command declares `Intent(A)`. We'll probably need to disallow access to the lock table spans without also declaring access to the main key span.

3. Make `DefaultDeclare(Isolated)Keys` automatically add explicit lock table spans. This would require commands that add their own keys to the spans to also add the corresponding lock spans. This is an extension of 2, and has the same challenges.

I'm leaning towards 1 personally, since I think it's easier for command authors to reason about the main key spans rather than the combination/interactions of key spans and lock table spans.

@sumeerbhola @nvanbenschoten I'm not sure what the thinking has been around this, have any thoughts?

**Comment by sumeerbhola** [comment]
I'm ok with a quick change to get the build fixed, and I agree about making the change in `executeReadOnlyBatch`. @shralex please merge once @erikgrinaker is satisfied -- I probably won't have time to review this.

Ideally, we should be declaring and checking the spans on a per-command basis, and not for the whole batch, but perhaps what we have currently is sufficient -- I don't know how often we have caught bugs using the current scheme.

I'd be happy with a longer term scheme that does not require changes in `newBatchedEngine`, `executeReadOnlyBatch`. Solution #1 is appealing in that way.

Though there are also cases like ranged intent resolution which are special, which has its own special case in `newBatchedEngine`.

**Comment by nvanbenschoten** [comment]
I agree with both things @sumeerbhola said. Let's de-flake master today with a patch like the one @erikgrinaker proposed above. Longer-term, let's push this complexity into the spanset package (option 1 above). The rest of the system should not be burdened with this.

> Though there are also cases like ranged intent resolution which are special, which has its own special case in newBatchedEngine.

Is this its own special case? Wouldn't it also go away if we pushed this into the spanset package? Ranged intent resolution declares write spans over each of the key spans that it will touch, so a mapping from global key span to lock table key span would be sufficient to capture the special case in `newBatchedEngine`.

**Review by nvb — APPROVED** [review]

**Review by erikgrinaker — APPROVED** [review]
:lgtm: Nice, thank you!

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71053#-:-MlAxAhC2yMwlH4qhIU_:b-xkcb0o)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @shralex)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71053#-MlAwV2Z5y4wycn4JYfJ):*
Please update the commit message to reflect the new change.

nit: use the imperative form, see https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages
___
*[pkg/kv/kvserver/replica_read.go, line 67 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71053#-MlAwux83uVidvPxxo8r:-MlAwux83uVidvPxxo8s:b-q2n7ti) ([raw file](https://github.com/cockroachdb/cockroach/blob/e651db710a923018d0663cb18e092ead53f07ea1/pkg/kv/kvserver/replica_read.go#L67)):*
> ```Go
> 	}
> 	if util.RaceEnabled {
> 		assertSpans := spans.Copy()
> ```

We should add a comment explaining this, something like "To account for direct access to separated intents in the lock table, add on corresponding lock table spans for all latches."

**Comment by erikgrinaker** [comment]
Opened #71077 to implement option 1.

**Pull request merged**
