### PR TITLE
sql/parser: Merge Datum.Compare and CmpOps functions

### LINKED ISSUE #13692: sql: CockroachDB panics on a date vs timestamptz comparison.
Running the following query causes CockroachDB to panic(!) and die:

```
select
	n_name,
	sum(l_extendedprice * (1 - l_discount)) as revenue
from
	customer,
	orders,
	lineitem,
	supplier,
	nation,
	region
where
	c_custkey = o_custkey
	and l_orderkey = o_orderkey
	and l_suppkey = s_suppkey
	and c_nationkey = s_nationkey
	and s_nationkey = n_nationkey
	and n_regionkey = r_regionkey
	and r_name = 'AFRICA'
	and o_orderdate >= date '1997-01-01'
	and o_orderdate < date '1997-01-01' + interval '1' year
group by
	n_name
order by
	revenue desc;
```

on a TPC-H dataset (PR incoming) causes the following panic:

```
./cockroach start
CockroachDB node starting at 2017-02-21 14:02:13.581244892 -0500 EST
build:      CCL f3c82c667 @ 2017/02/21 16:21:47 (go1.7.3)
admin:      http://localhost:8080
sql:        postgresql://root@localhost:26257?sslmode=disable
logs:       cockroach-data/logs
store[0]:   path=cockroach-data
status:     restarted pre-existing node
clusterID:  efbc7704-1c75-4857-b407-e4b4a3dd373f
nodeID:     1
panic: unsupported comparison: date to timestamptz [recovered]
	panic: select
	n_name,
	sum(l_extendedprice * (1 - l_discount)) as revenue
from
	customer,
	orders,
	lineitem,
	supplier,
	nation,
	region
where
	c_custkey = o_custkey
	and l_orderkey = o_orderkey
	and l_suppkey = s_suppkey
	and c_nationkey = s_nationkey
	and s_nationkey = n_nationkey
	and n_regionkey = r_regionkey
	and r_name = 'AFRICA'
	and o_orderdate >= date '1997-01-01'
	and o_orderdate < date '1997-01-01' + interval '1' year
group by
	n_name
order by
	revenue desc;
: unsupported comparison: date to timestamptz [recovered]
	panic: select
	n_name,
	sum(l_extendedprice * (1 - l_discount)) as revenue
from
	customer,
	orders,
	lineitem,
	supplier,
	nation,
	region
where
	c_custkey = o_custkey
	and l_orderkey = o_orderkey
	and l_suppkey = s_suppkey
	and c_nationkey = s_nationkey
	and s_nationkey = n_nationkey
	and n_regionkey = r_regionkey
	and r_name = 'AFRICA'
	and o_orderdate >= date '1997-01-01'
	and o_orderdate < date '1997-01-01' + interval '1' year
group by
	n_name
order by
	revenue desc;
: unsupported comparison: date to timestamptz [recovered]
	panic: select
	n_name,
	sum(l_extendedprice * (1 - l_discount)) as revenue
from
	customer,
	orders,
	lineitem,
	supplier,
	nation,
	region
where
	c_custkey = o_custkey
	and l_orderkey = o_orderkey
	and l_suppkey = s_suppkey
	and c_nationkey = s_nationkey
	and s_nationkey = n_nationkey
	and n_regionkey = r_regionkey
	and r_name = 'AFRICA'
	and o_orderdate >= date '1997-01-01'
	and o_orderdate < date '1997-01-01' + interval '1' year
group by
	n_name
order by
	revenue desc;
: unsupported comparison: date to timestamptz

goroutine 837 [running]:
panic(0x538f1c0, 0xc420df4bb0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc42038e090)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:198 +0x6e
panic(0x538f1c0, 0xc420df4bb0)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve.func1(0xc42016c400, 0xa0b1f40, 0xc421098180)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:340 +0x74
panic(0x538f1c0, 0xc420df4bb0)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements.func1(0xc421159000, 0x1d5)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:473 +0x149
panic(0x5340ea0, 0xc420df4b90)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/sql/parser.(*DDate).Compare(0xc421139e50, 0x5f07560, 0xc420a704c0, 0xc4210a6b60)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/parser/datum.go:914 +0x120
github.com/cockroachdb/cockroach/pkg/sql.simplifyOneAndExpr(0x5f00e00, 0xc420e20d80, 0x5f00e00, 0xc420e20e00, 0x1, 0xc420a70f40, 0x2, 0x2, 0x5f02300)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/analyze.go:382 +0xb11
github.com/cockroachdb/cockroach/pkg/sql.simplifyAndExpr(0xc42122e6f0, 0x5f07740, 0x64294d0, 0x5f02300)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/analyze.go:273 +0x2d9
github.com/cockroachdb/cockroach/pkg/sql.simplifyExpr(0x5f00aa0, 0xc42122e6f0, 0xc420351800, 0x46a57bf, 0xc4212861f0)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/analyze.go:145 +0x264
github.com/cockroachdb/cockroach/pkg/sql.analyzeExpr(0x5f00aa0, 0xc42122e6f0, 0x4, 0xc420a70ee0, 0x0, 0x4)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/analyze.go:49 +0x42
github.com/cockroachdb/cockroach/pkg/sql.(*planner).selectIndex(0xc421042160, 0xc420cb4000, 0x0, 0x6429400, 0x0, 0x38, 0xc42025fc20, 0xc421282008)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/index_selection.go:125 +0x10d1
github.com/cockroachdb/cockroach/pkg/sql.expandScanNode(0xc421042160, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0xc420cb4000, 0x5f035c0, 0x18, 0x20, 0xc420a70ea0)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:279 +0xea
github.com/cockroachdb/cockroach/pkg/sql.doExpandPlan(0xc421042160, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0x5f05060, 0xc420cb4000, 0xc421282000, 0x0, 0x0, ...)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:230 +0x665
github.com/cockroachdb/cockroach/pkg/sql.doExpandPlan(0xc421042160, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0x5f04ee0, 0xc420970460, 0x5f05060, 0xc421282000, 0x0, ...)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:119 +0x188c
github.com/cockroachdb/cockroach/pkg/sql.doExpandPlan(0xc421042160, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0x5f04ee0, 0xc420970620, 0xc42122da10, 0xc420e71440, 0xc4210a7910, ...)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:123 +0x1927
github.com/cockroachdb/cockroach/pkg/sql.expandRenderNode(0xc421042160, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0xc420ca78c0, 0xc420e71530, 0x34, 0x0, 0xc42122ddda)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:290 +0xbd
github.com/cockroachdb/cockroach/pkg/sql.doExpandPlan(0xc421042160, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0x5f05000, 0xc420ca78c0, 0x5ee230a, 0x5f05000, 0xc420ca78c0, ...)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:233 +0x29b4
github.com/cockroachdb/cockroach/pkg/sql.doExpandPlan(0xc421042160, 0x7fffffffffffffff, 0xc421139f20, 0x1, 0x1, 0x5f04d60, 0xc420e31080, 0x16, 0xc4210a7d68, 0x4413dcf, ...)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:181 +0x243c
github.com/cockroachdb/cockroach/pkg/sql.doExpandPlan(0xc421042160, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0x5f050c0, 0xc420a58fd0, 0xa000000, 0x0, 0x0, ...)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:200 +0x1d13
github.com/cockroachdb/cockroach/pkg/sql.(*planner).expandPlan(0xc421042160, 0x5f050c0, 0xc420a58fd0, 0x5f050c0, 0xc420a58fd0, 0x0, 0x0)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:34 +0x73
github.com/cockroachdb/cockroach/pkg/sql.(*planner).optimizePlan(0xc421042160, 0x5f050c0, 0xc420a58fd0, 0xc420df4020, 0x2, 0x2, 0x1, 0x5f050c0, 0xc420a58fd0, 0x0)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/optimize.go:38 +0xd7
github.com/cockroachdb/cockroach/pkg/sql.(*planner).makePlan(0xc421042160, 0x5efd180, 0xc4210986c0, 0xc41b12b601, 0x63f2160, 0xc4210a8110, 0x4379402, 0xed03e85fa)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:204 +0x12b
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmt(0xc420142300, 0x5efd180, 0xc4210986c0, 0xc421042160, 0xc4210a0001, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1363 +0xa3
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtInOpenTxn(0xc420142300, 0x5efd180, 0xc4210986c0, 0xc421042160, 0x101, 0xc421042068, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1153 +0x2a5
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtsInCurrentTxn(0xc420142300, 0xc421017ad0, 0x1, 0x1, 0xc421042160, 0xc421042068, 0x101, 0x6, 0x6, 0x0, ...)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:891 +0x7cb
github.com/cockroachdb/cockroach/pkg/sql.runTxnAttempt(0xc420142300, 0xc421042160, 0x1, 0xc421042068, 0xc421017b20, 0xc421017ad0, 0x1, 0x1, 0x0, 0x0, ...)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:805 +0xf8
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest.func2(0xc420ab8780, 0xc421017b20, 0x0, 0x0)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:644 +0x2b7
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Exec(0xc420ab8780, 0xc420f20101, 0xc420222240, 0xc420f228c0, 0xc400000000, 0x0)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:511 +0x1c4
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc420142300, 0xc421042000, 0xc421159000, 0x1d5, 0x0, 0x0, 0x0, 0x0, 0xc4213f1300)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:666 +0x5e3
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc420142300, 0xc421042000, 0xc421159000, 0x1d5, 0x0, 0x0, 0x0, 0x0, 0xc421159000)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:479 +0x11f
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).executeStatements(0xc42016c400, 0xa0b1f40, 0xc421098180, 0xc421159000, 0x1d5, 0x0, 0x0, 0x0, 0x0, 0x4566601, ...)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:813 +0x94
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc42016c400, 0xa0b1f40, 0xc421098180, 0xc42016c428, 0x1da, 0x0)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:491 +0xb3
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc42016c400, 0xa0b1f40, 0xc421098180, 0xc4210172a0, 0x5400, 0xc42017c150, 0xa0b2100, 0xc420d35a80, 0x0, 0x0)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:419 +0x8de
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc42017c000, 0xa0b2100, 0xc420d35a80, 0x5f05780, 0xc420fa8d10, 0x0, 0x0)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:415 +0xa2c
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func8.1(0x5f05780, 0xc420fa8d10)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/server/server.go:536 +0x106
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc42038e090, 0xc42002c108, 0x5f05780, 0xc420fa8d10, 0xc420b8d3a0)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:136 +0x95
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:138 +0x277
```

I am unable to construct a more minimal example. Doing things like
```
SELECT now()::date < now()::timestamptz;
+--------------------------------+
| now()::DATE < now()::TIMESTAMP WITH TIME ZONE |
+--------------------------------+
| true                           |
+--------------------------------+
```
seems to work fine. cc @cuongdo, but I'm investigating this myself for a bit.

### PR DESCRIPTION
**Pull request by nvb**
Fixes #13692.

In the past, we have had both `CmpOp` implementations and `Datum.Compare` methods,
which both compare two `Datum` values. These comparisons have always been very similar
and differed only in special cases where encoded key comparisons diverged from SQL
datum value comparisons. This duplicated logic and was error prone. For instance,
when mixed-type comparisons were added for date types, the mixed type logic was
understandably not added to the corresponding `Datum.Compare` methods. This change
adjusts the `CmpOp` implementations to be small wrappers around `Datum.Compare` methods,
which avoids a lot of the code duplication, and will help prevent similar bugs from
being introduced in the future.

This requires a significant propagation of `*parser.EvalContext`s, because this is
now a required parameter of `Datum.Compare`. In most cases, this is actually a good
thing, because it gives us more flexibility in using caches and session variables in
these comparison methods.

The change also switches `CmpOp` from returning a `*DBool` to returning a `Datum`.
This means that we can avoid our previous error hack to return NULL values from
these comparison methods.

cc. @arjunravinarayan

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14048)

### CODE REVIEW

**Comment by tamird** [comment]
Awesome. :lgtm_strong: 

---

Reviewed 30 of 30 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/datum.go, line 114 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14048#-Kep8ZdD7Z-cCxzC9-IW:-Kep8ZdD7Z-cCxzC9-IX:b-ta8kvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fe597038d1e7ac2e5867137072d4697519430b3/pkg/sql/parser/datum.go#L114)):*
> ```Go
> 
> // Len returns the number of Datum values.
> func (d *Datums) Len() int { return len(*d) }
> ```

remove this, too? unless you keep the implementation of sort.Interface, which i think you should.

---

*[pkg/sql/parser/datum.go, line 309 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14048#-KepL9rUOx8Ah86Ke-KE:-KepL9rVcs7NpnTi25Sh:b-yrwbv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fe597038d1e7ac2e5867137072d4697519430b3/pkg/sql/parser/datum.go#L309)):*
> ```Go
> 	case *DInt:
> 		v = *t
> 	case *DFloat:
> ```

merge the two?

---

*[pkg/sql/parser/datum.go, line 1083 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14048#-KepLFjjcV4NvoMmdqor:-KepLFjjcV4NvoMmdqos:bsfr8vx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fe597038d1e7ac2e5867137072d4697519430b3/pkg/sql/parser/datum.go#L1083)):*
> ```Go
> 	case *DDate:
> 		return MakeDTimestampTZFromDate(ctx.GetLocation(), t).Time, true
> 	case *DTimestampTZ:
> ```

merge 'em?

---

*[pkg/sql/parser/datum.go, line 1697 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14048#-KepLMMLCPv7sP32mMKE:-KepLMMLCPv7sP32mMKF:b-3nspg9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fe597038d1e7ac2e5867137072d4697519430b3/pkg/sql/parser/datum.go#L1697)):*
> ```Go
> func (d *DTuple) sort(ctx *EvalContext) {
> 	if !d.Sorted {
> 		sort.Slice(d.D, func(i, j int) bool {
> ```

this is slower; why move to this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14048#-:-KepLhDsCyVGDyk4PWuP:b-kb0mma)*

**Comment by knz** [comment]
Very nice work.

Same question as tamir for sorting tuples. Also could you clarify in the commit message how the new handling of nulls interacts with sorting nulls for sql orderings.

Also I wonder how much of this alleviates #13217.

---

Reviewed 14 of 14 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/datum.go, line 310 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14048#-Ket5moW0SEePnXcR4f1:-Ket5moYqmZzPojZRhBX:b-lnqhyg) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b438c82d41b59ed9f45cb19879314433c5330a8/pkg/sql/parser/datum.go#L310)):*
> ```Go
> 		v = *t
> 	case *DFloat:
> 		return -1 * t.Compare(ctx, d)
> ```

Why `-1 * x` instead of just `-x`?

---

*[pkg/sql/parser/eval_test.go, line 748 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14048#-Ket6tRCvd5SxpXnIq6-:-Ket6tRDUrofj6QWdae3:b-l91o1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b438c82d41b59ed9f45cb19879314433c5330a8/pkg/sql/parser/eval_test.go#L748)):*
> ```Go
> 		{`'-Inf'::real`, `-Inf`},
> 		{`'+Infinity'::double precision`, `+Inf`},
> 		{`'+Inf'::float < 1.0`, `false`},
> ```

I don't remember seeing tests that exercise null/non-null comparisons. Can you check your code paths for that here? (probably things like `x::float < null::float` etc)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14048#-:-Ket5GA3ceQ88tqzUbCn:b-5oegcr)*

**Comment by nvanbenschoten** [comment]
Thanks for the reviews.

---

Review status: 28 of 30 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/sql/parser/datum.go, line 114 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14048#-Kep8ZdD7Z-cCxzC9-IW:-Kev2DzqLRUi5unglhn8:bvu5dzi) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fe597038d1e7ac2e5867137072d4697519430b3/pkg/sql/parser/datum.go#L114)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

remove this, too? unless you keep the implementation of sort.Interface, which i think you should.
</blockquote></details>

We use this `Len` method elsewhere.

---

*[pkg/sql/parser/datum.go, line 309 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14048#-KepL9rUOx8Ah86Ke-KE:-Kev00Pz9MXNNpXDSQzH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fe597038d1e7ac2e5867137072d4697519430b3/pkg/sql/parser/datum.go#L309)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

merge the two?
</blockquote></details>

Done.

---

*[pkg/sql/parser/datum.go, line 1083 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14048#-KepLFjjcV4NvoMmdqor:-Kev0FEXCYyQjynyfAnG:b4t3tq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fe597038d1e7ac2e5867137072d4697519430b3/pkg/sql/parser/datum.go#L1083)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

merge 'em?
</blockquote></details>

Unfortunately, we can't since they're different types and we're referencing type-specific fields.

---

*[pkg/sql/parser/datum.go, line 1697 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14048#-KepLMMLCPv7sP32mMKE:-Kev0Ssm83uP0ILChF6E:b-izpj3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fe597038d1e7ac2e5867137072d4697519430b3/pkg/sql/parser/datum.go#L1697)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this is slower; why move to this?
</blockquote></details>

We now need to have access to an `*EvalContext` when sorting so `Datums` itself can no longer implement `sort.Interface`. The other option would be to create a `DatumSorter struct { Datums, *EvalContext }` type, but since we only need it for this single use case, it doesn't seem worth it. This is also a lot clearer.

---

*[pkg/sql/parser/datum.go, line 310 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14048#-Ket5moW0SEePnXcR4f1:-Kev-Un8zwW4PEGgDq82:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b438c82d41b59ed9f45cb19879314433c5330a8/pkg/sql/parser/datum.go#L310)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Why `-1 * x` instead of just `-x`?
</blockquote></details>

Done.

---

*[pkg/sql/parser/eval_test.go, line 748 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14048#-Ket6tRCvd5SxpXnIq6-:-Kev51EPtDh4v80YWTnu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b438c82d41b59ed9f45cb19879314433c5330a8/pkg/sql/parser/eval_test.go#L748)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I don't remember seeing tests that exercise null/non-null comparisons. Can you check your code paths for that here? (probably things like `x::float < null::float` etc)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14048#-:-Kev52KF9H4kcirPNcsK:b-hlc8b9)*

**Comment by nvanbenschoten** [comment]
Also, this doesn't change the sorting of nulls at all, and it's not handling null values any differently.

---

Review status: 28 of 30 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14048#-:-Kev5yPidqlomwF2q3iI:b-z6nig7)*

**Pull request merged**
