### PR TITLE
dep: Bump grpc-go version

### PR DESCRIPTION
**Pull request by a-robinson**
And pull in new packages -- in particular, the encoding/proto package
isn't needed for compilation but is needed at runtime.

Release note: None

---------------------

We should wait to merge this until they've cut the 1.12 release tag so that we aren't just at an arbitrary commit in their git history but I'm sending out the PR now so that I (or whoever would have done this) don't have to deal with debugging the missing encoding/proto package when it comes time to merge this.

As tested in https://github.com/cockroachdb/cockroach/issues/17370#issuecomment-382082667, this gives a 5-10% boost in whole-cluster throughput and improved tail latencies when run with a highly concurrent workload. It appears to have little performance effect for lower-concurrency workloads.

### CODE REVIEW

**Comment by a-robinson** [comment]
I'll also have to update https://github.com/cockroachdb/vendored when the time comes -- I just didn't bother in this case since I think we should wait until grpc-go creates the release tag.

**Comment by a-robinson** [comment]
grpc-go was released early last week. This is now ready for review/merge, using vendored commit https://github.com/cockroachdb/vendored/commit/5ee55ebb38a0de3de4e1370e77ce98490f29b1a6

**Comment by tschottdorf** [comment]
Your `vendor` seems to conflict. LGTM otherwise and perhaps @bdarnell wants to sign off as well.

**Comment by bdarnell** [comment]
:lgtm:

Any noteworthy changes?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24883#-:-LCVNqbt468tEAqFldB6:b9a5anu)*

**Comment by a-robinson** [comment]
Yeah sorry, fixed now.

**Comment by bdarnell** [comment]
We have some specific ignore rules in our invocation of staticcheck: https://github.com/cockroachdb/cockroach/blob/a6c4ffa9df66c624e0690e59ec3cf4303697af56/pkg/testutils/lint/lint_test.go#L818

We should feel free to ignore lint issues in generated files.

**Comment by a-robinson** [comment]
Perfect, thanks for the pointer!

**Pull request merged**
