### PR TITLE
server: use new diagnostics package in Server

### PR DESCRIPTION
**Pull request by andy-kimball**
SQL-only tenant instances. This commit changes Server to use the new package
and removes the old side-by-side code in updates.go. In addition, this commit
moves the update checker code into the diagnostics package so that it's all
consolidated in one place.

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
I was confused by the commit title and message. It kind of looks like the title and the first part of the message form a sentence, but it doesn't make much sense. Did something get garbled? A description as I understand it could be:

server: use new diagnostics package in Server

This change follows up on #58399, which ported our diagnostics code to a separate package and used it only for tenants. This change did not touch the "legacy" diagnostics code for single-tenant deployments to facilitate backporting. In this commit, we close the loop and phase out the legacy code for single tenants as well.

> Reviewed 32 of 32 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59073#-:-MRK6FSE-ORpDnIO5ZB6:b-x0u8g4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @dt)

___
*[pkg/server/diagnostics/update_checker.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59073#-MRK57ju6S4WyelfI1JQ:-MRK57ju6S4WyelfI1JR:bqjisvv) ([raw file](https://github.com/cockroachdb/cockroach/blob/dca43fb1d2c768d80763fa6e76698177b972d884/pkg/server/diagnostics/update_checker.go#L1)):*
> ```Go
> // Copyright 2016 The Cockroach Authors.
> ```

is this 2021 now?
___
*[pkg/server/diagnostics/update_checker.go, line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59073#-MRK5Ork2H32G64NGun4:-MRK5Ork2H32G64NGun5:bah8bcq) ([raw file](https://github.com/cockroachdb/cockroach/blob/dca43fb1d2c768d80763fa6e76698177b972d884/pkg/server/diagnostics/update_checker.go#L121)):*
> ```Go
> 	if res.StatusCode != http.StatusOK {
> 		b, err := ioutil.ReadAll(res.Body)
> 		log.Warningf(ctx, "failed to check for updates: status: %s, body: %s, error: %v",
> ```

Is this really a warning? We don't want to log warnings on a customer cluster just because our phone home infra is having issues. IMO this is an `Info` if even that.

**Review by andy-kimball — COMMENTED** [review]
Yeah, I'm not sure what happened to the commit message. I fixed it up to incorporate your suggestion.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59073#-:-MRQJjdeCdQ4WZ4A86fi:b-3d5b81)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @tbg)

___
*[pkg/server/diagnostics/update_checker.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59073#-MRK57ju6S4WyelfI1JQ:-MRQKCKHC0mu6B_wYEUp:bkacm5) ([raw file](https://github.com/cockroachdb/cockroach/blob/dca43fb1d2c768d80763fa6e76698177b972d884/pkg/server/diagnostics/update_checker.go#L1)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

is this 2021 now?
</blockquote></details>

That's what I'm told. Updated.
___
*[pkg/server/diagnostics/update_checker.go, line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59073#-MRK5Ork2H32G64NGun4:-MRQJpIGD5Q2OlHNu3Q9:bjaky6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/dca43fb1d2c768d80763fa6e76698177b972d884/pkg/server/diagnostics/update_checker.go#L121)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Is this really a warning? We don't want to log warnings on a customer cluster just because our phone home infra is having issues. IMO this is an `Info` if even that.
</blockquote></details>

I just ported this code over and don't have a particularly informed opinion. I switched to use Infof.

**Review by tbg — APPROVED** [review]
> Reviewed 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59073)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

**Pull request merged**
