### PR TITLE
roachtest: set PredecessorVersion(20.2)=20.1.0

### PR DESCRIPTION
**Pull request by tbg**
Unbreaks CI.

Release note: None

### CODE REVIEW

**Review by bobvawter — APPROVED** [review]
LGTM

**Comment by tbg** [comment]
TFTR!

bors r=bobvawter

**Comment by knz** [comment]
how is this working? a comment in the test code specifically mentions that a fixture should be uploaded.

**Comment by tbg** [comment]
Good point, let me regenerate that fixture, too.

**Review by knz — APPROVED** [review]

**Comment by tbg** [comment]
Ok, now it should work. I'll wait until it goes green on TC though (master is unborked, right @knz?)

**Comment by knz** [comment]
> master is unborked, right

yes, I deleted the tag

**Comment by tbg** [comment]
Closing for #48789, which also has this commit.

**Pull request closed without merging**
