### PR TITLE
kvserver: misc rac2 logging and fixes

### PR DESCRIPTION
**Pull request by kvoli**
Logging and fixes picked up along the way to get v1 compatibility integration testing working for #130187.

---

rac2: introduce misc verbose logging

Previously, there was limited within the range controller and
sub-components. Introduce several V(Event|Info) logging statements:

```
rac2/range_controller.go:260  [T1,Vsystem,n1,s1,r70/1:/{Table/Max-Max},raft] r70 creating range controller
rac2/range_controller.go:376  [T1,Vsystem,n1] r70/1 admitted request (pri=normal-pri wait-duration=709ns wait-for-all=false)
rac2/range_controller.go:458  [T1,Vsystem,n1,s1,r70/1:/{Table/Max-Max},raft] r70 closing range controller
rac2/range_controller.go:646  [T1,Vsystem,n1,s1,r70/1:/{Table/Max-Max},raft] r70:(n1,s1):1 stream t1/s1 admit term:6, admitted:[LowPri:10,NormalPri:10,AboveNormalPri:10,HighPri:10]
rac2/range_controller.go:655  [T1,Vsystem,n1,s1,r70/1:/{Table/Max-Max},raft] creating send stream t1/s1 for replica (n1,s1):1
rac2/range_controller.go:772  [T1,Vsystem,n1,s1,r70/1:/{Table/Max-Max},raft] closing send stream t1/s1 for replica (n1,s1):1
rac2/token_counter.go:491     [T1,Vsystem,n1,s1,r70/1:/{Table/Max-Max},raft] adjusted flow tokens (wc=regular stream=t1/s1 delta=-1.0 MiB): regular=+15 MiB elastic=+7.0 MiB
rac2/token_tracker.go:76      [T1,Vsystem,n1,s1,r70/1:/{Table/Max-Max},raft] tracking +1.0 MiB flow control tokens for pri=NormalPri stream=t1/s2 log-position=6/22
````

Part of: https://github.com/cockroachdb/cockroach/issues/130187
Release note: None

---
replica_rac2: vlog when decoding raft admission meta

V(1) log the raft admission meta information when decoding an entry
below raft, as part of `AdmitRaftEntriesRaftMuLocked`.

Part of: https://github.com/cockroachdb/cockroach/issues/130187
Release note: None

---

kvserver: fix rac v2 replication handle lookup

When calling `LookupReplicationAdmissionHandle`, `storesForFlowControl`
would previously then call `Lookup`, which could only return a v1 replication
admission control handle.

Iterate over the stores calling the same method instead.

Part of: https://github.com/cockroachdb/cockroach/issues/130187
Release note: None

---

kvserver: pass settings when constructing rac2 processor

To avoid a nil ptr deref when using them in
`replica_rac2.processorImpl`.

Part of: https://github.com/cockroachdb/cockroach/issues/130187
Release note: None

---

kvadmission: add todo to handle raft admission meta prio

Part of: cockroachdb#130187
Release note: None

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
flushing a comment. I am still reading.

> Reviewed 7 of 7 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130833#-:-O6wgb2P74CN8qn2_uWZ:b-i4vpdq)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 904 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130833#-O6w_TIH2eqQnw3FJayo:-O6w_TIH2eqQnw3FJayp:bhmx0oo) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a2c543811e58e05253e9539f1ec97121d0ac9bf/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L904)):*
> ```Go
> 		if log.V(1) {
> 			log.Infof(ctx, "decoded raft admission meta below-raft: pri=%s create-time=%d proposer=n%s receiver=[n%d,s%s] tenant=t%d tokens≈%d sideloaded=%t raft-entry=%d/%d",
> 				admissionpb.WorkPriority(meta.AdmissionPriority),
> ```

I don't think we should log the `AdmissionPriority`. For v2 encoding we cast it to `raftpb.Priority` below, since it is not a `admissionpb.WorkPriority`. I think we should move this log statement below the blocks below that compute the `raftPri` and log that, and additionally whether it was v1 or v2 encoding.

**Review by kvoli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130833)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 904 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130833#-O6w_TIH2eqQnw3FJayo:-O6wh9wOECzoQq0lj3Gk:bmu0uf2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a2c543811e58e05253e9539f1ec97121d0ac9bf/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L904)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I don't think we should log the `AdmissionPriority`. For v2 encoding we cast it to `raftpb.Priority` below, since it is not a `admissionpb.WorkPriority`. I think we should move this log statement below the blocks below that compute the `raftPri` and log that, and additionally whether it was v1 or v2 encoding.
</blockquote></details>

I pushed pretty much this change a couple minutes ago when I realized (should have left it as a draft for a bit longer). Take a look and see if it matches what you were thinking.

**Review by sumeerbhola — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130833)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 904 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130833#-O6w_TIH2eqQnw3FJayo:-O6wh8hR7vuMEI8de2Ec:b-xk5nwu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a2c543811e58e05253e9539f1ec97121d0ac9bf/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L904)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I don't think we should log the `AdmissionPriority`. For v2 encoding we cast it to `raftpb.Priority` below, since it is not a `admissionpb.WorkPriority`. I think we should move this log statement below the blocks below that compute the `raftPri` and log that, and additionally whether it was v1 or v2 encoding.
</blockquote></details>

the change you made here looks fine too.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130833#-:-O6wkEM83BD8Z_FAr3J2:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/kvadmission/kvadmission.go` line 359 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/130833#-O6wiyVU2nZ00gMmhKDw:-O6wiyVU2nZ00gMmhKDx:b-kn7k4) ([raw file](https://github.com/cockroachdb/cockroach/blob/19d34b5c9e0a482cec1106a8467a328a2d4e24f7/pkg/kv/kvserver/kvadmission/kvadmission.go#L359)):*
> ```Go
> 					// raftpb.Priority when v2 encoding is enabled. e.g.,
> 					// rac2.AdmissionToRaftPriority().
> 					AdmissionPriority:   int32(admissionInfo.Priority),
> ```

Nice catch. I think we can't fix it here, though it is a slight pity, in that we will need to add a comment saying that `AdmissionPriority` is `admissionpb.Priority` for both v1 and v2 encoding until we actually get to the code that encodes the command. And in replica_raft.go where we do
```
	data, err := raftlog.EncodeCommand(ctx, p.command, p.idKey,
		raftlog.EncodeOptions{
			RaftAdmissionMeta: raftAdmissionMeta,
			EncodePriority:    r.encodePriorityForRACv2(),
		})

```
we would, if the return value of `r.encodePriorityForRACv2()` is true, change `raftAdmissionMeta.Priority` to the `raftpb.Priority` before calling `EncodeCommand`.

Ideally we could make that decision here itself, and propagate it, but we only propagate `raftAdmissionMeta` via `ContextWithMeta`, which already incurs an allocation, and it would be nice to avoid adding another allocation.

**Review by kvoli — COMMENTED** [review]
TYFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130833#-:-O6wxCdT9JDiUhusRAnK:bzftgo7)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/kvadmission/kvadmission.go` line 359 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/130833#-O6wiyVU2nZ00gMmhKDw:-O6wwn6k9jEXwLyPwq-g:b-risg9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/19d34b5c9e0a482cec1106a8467a328a2d4e24f7/pkg/kv/kvserver/kvadmission/kvadmission.go#L359)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Nice catch. I think we can't fix it here, though it is a slight pity, in that we will need to add a comment saying that `AdmissionPriority` is `admissionpb.Priority` for both v1 and v2 encoding until we actually get to the code that encodes the command. And in replica_raft.go where we do
```
	data, err := raftlog.EncodeCommand(ctx, p.command, p.idKey,
		raftlog.EncodeOptions{
			RaftAdmissionMeta: raftAdmissionMeta,
			EncodePriority:    r.encodePriorityForRACv2(),
		})

```
we would, if the return value of `r.encodePriorityForRACv2()` is true, change `raftAdmissionMeta.Priority` to the `raftpb.Priority` before calling `EncodeCommand`.

Ideally we could make that decision here itself, and propagate it, but we only propagate `raftAdmissionMeta` via `ContextWithMeta`, which already incurs an allocation, and it would be nice to avoid adding another allocation.
</blockquote></details>

Ah I see. I'll leave this TODO here since we will update the comment mentioning the priority is the same for v1/v2 and handled in replica_raft.go. I'll open another PR tomorrow for it.
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 904 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130833#-O6w_TIH2eqQnw3FJayo:-O6wxAgQ1SEVIlBPJFRx:b32wwp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a2c543811e58e05253e9539f1ec97121d0ac9bf/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L904)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

the change you made here looks fine too.
</blockquote></details>

sg

**Comment by kvoli** [comment]
bors r=sumeerbhola

**Pull request merged**
