### PR TITLE
builtins: implement ST_Expand

### PR DESCRIPTION
**Pull request by otan**
Release note (sql change): implement ST_Expand for box2d.

### CODE REVIEW

**Comment by rmloveland** [comment]
Hey @otan I think this is called `ST_Extend` in the PR but your description says "ST_Expand" ?

**Comment by otan** [comment]
I should have corrected both!

**Comment by otan** [comment]
oh i didn't let me fix it.
don't work at night

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52957#-:-MF1CxsRBkJd5lYeSJTM:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Comment by otan** [comment]
bors r=summerbhola

**Comment by otan** [comment]
bors r=sumeerbhola

**Pull request merged**
