### PR TITLE
serverccl: Add unit test for unique row id in MT.

### PR DESCRIPTION
**Pull request by rimadeodhar**
This PR adds a unit test to confirm unique row id generates
unique identifiers based on the SQL instance ID in the
multi-tenant environment.

Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
:lgtm:, except for the y.output file that looks like it mistakenly got added to the PR.

**Review by dhartunian — COMMENTED** [review]
> This PR adds a unit test to confirm unique row id works
> as expected in a tenant cluster.

Can you add a few words on what this expectation is? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70215#-:-MjdmkOm1ZbYcijrJ3Er:b907y0r)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @andy-kimball)

**Review by rimadeodhar — COMMENTED** [review]
Updated the message.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70215#-:-Mk32v9tBrGA66PWiFYe:b-ygegqo)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @andy-kimball)

**Review by abarganier — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70215#-:-MkJUY8NBAHs246A0qrd:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @andy-kimball)

**Comment by rimadeodhar** [comment]
TFTR!
bors r=abarganier

**Pull request merged**
