### PR TITLE
sql, distql: reuse renders for GROUP BY columns

### PR DESCRIPTION
**Pull request by RaduBerinde**
Addressing a TODO in `groupNode` for reusing renders when adding `GROUP BY`
columns to the pre-renders. The duplication of renders is especially bad for
distsql where it causes more data to be streamed between nodes, and more data to
be stored inside local aggregation stages (this should help a bit with memory
usage: #15194).

### CODE REVIEW

**Comment by knz** [comment]
group.go changes LGTM
more eyes needed for distsql changes.

**Comment by arjunravinarayan** [comment]
:lgtm: DistSQL changes. @knz you good with the added testcases in r2? Those are the only ones that are confusing me a little, but otherwise this is great!

---

Reviewed 6 of 7 files at r1.
Review status: 5 of 7 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15220#-:-KiF_kagyyRqno6iggWy:b-rw5yp5)*

**Comment by arjunravinarayan** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 881 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15220#-KiFaJTW1bXDMgklu3Gn:-KiFaJTW1bXDMgklu3Go:b1ontn9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5b8a9133f3fc4fd340cc8c9694b030da85b0c84/pkg/sql/distsql_physical_planner.go#L881)):*
> ```Go
> 		}
> 
> 		localAgg := make([]distsqlrun.AggregatorSpec_Aggregation, numAgg, numAgg+len(groupCols))
> ```

How much do we care about optimizations like this, in general? Because we are somewhat inconsistent in taking advantage of known allocation lengths. Just curious because I want to know how much attention I should be paying to this sort of pre-allocation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15220)*

**Comment by RaduBerinde** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 881 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15220#-KiFaJTW1bXDMgklu3Gn:-KiFh8Z5IxPwBy7id3-o:bc4kcl7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5b8a9133f3fc4fd340cc8c9694b030da85b0c84/pkg/sql/distsql_physical_planner.go#L881)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

How much do we care about optimizations like this, in general? Because we are somewhat inconsistent in taking advantage of known allocation lengths. Just curious because I want to know how much attention I should be paying to this sort of pre-allocation.
</blockquote></details>

Hidden allocations tend to add up, it's generally good practice to avoid them when we can easily pre-size slices. When it's not easy to do, I wouldn't go to extra trouble unless it's in a hotter path (e.g. per row).
I'm sure any one allocation here is a drop in the bucket - but that's kind of the point, that there *is* a bucket :) I'm sure there are dozens or hundreds of allocations involved in making an average plan..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15220)*

**Comment by knz** [comment]
Yes the test cases are good too.

---

Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15220#-:-KiFkutTFEYGJIBsQudo:b-o2yxvx)*

**Pull request merged**
