### PR TITLE
build: clean up after verify-archive

### PR DESCRIPTION
**Pull request by dt**

### CODE REVIEW

**Comment by bdarnell** [comment]
If we removed the `--privileged` flag from `build/builder.sh`, would that stop it from writing files as root? It was added in #13414 in order to make it possible to run `gdb` inside the container; it seems like it might be a good idea to only do that when specifically requested.

**Comment by dt** [comment]
with the new assertion that we're leaving the workspace clean, this will still fail if we don't clean it up, owned by root or otherwise.

If we didn't write as root, we might not need the workspace-clean assertion, but it is still probably a good idea -- similar checks have caught tempfile leaks in the past.

**Comment by bdarnell** [comment]
Yeah, this seems like a good change regardless, but the problem wouldn't have had nearly as big an impact on developer productivity if the files weren't owned by root and the next build could clean up automatically.

**Comment by benesch** [comment]
The `--privileged` flag isn't the problem, actually. `build/builder.sh` goes to [great lengths to run as a non-privileged user](https://github.com/cockroachdb/cockroach/blob/master/build/builder.sh#L62-L76), behavior which is ultimately controlled by passing the `-u/--user` flag, not the `--privileged` flag.

The problem, as @dt has discovered, is that we _don't_ pass that flag in [`teamcity-verify-archive`'s `docker` invocation.](https://github.com/cockroachdb/cockroach/blob/master/build/teamcity-verify-archive.sh#L18-L22) Creating an appropriate `/etc/passwd` is real annoying, though.

**Comment by dt** [comment]
Er, what did I discover?

I guess what I was seeing was we call `make archive` to produce an archive but we don't clean it up when we're done.

AFAIK, that  `docker run ... verify-archive` is working working fine and cleans up its workdir, so it is just the archive we need to worry about here? (the rocks tempdir bug notwithstanding)

**Comment by benesch** [comment]
Ok, this is green and LGTM! Let's merge this since it gets us one step closer to fixing verify-archive?

**Pull request merged**
