### PR TITLE
changefeedccl: partition cloud storage sink files by date

### LINKED ISSUE #34473: changefeedccl: enable time based partitioning for cloud storage sink
Currently, the cloud storage sink writes all data inside a single prefix, on the assumption that users will monitor this prefix for new data and remove/archive old files as they are ingested into downstream systems. However, in some circumstances, long-term archival may be desirable, and unbounded growth within a single prefix may be problematic.

We should add a new option to the cloud storage sink that allows users to temporally partition their changefeeds. This doesn't need to have a lot of configuration options - we can start by just enabling partitioning by day. With this option enabled, files written to a cloud storage bucket would be partitioned with a date prefix (after the prefix in the URL, if provided) as follows:

```
/2019-01-31/20190131235900123456789-table-whatever.json
/2019-01-31/20190131235930123456789.RESOLVED
/2019-02-01/20190201000000987654321-table-whatever.json
/2019-02-01/20190201000000987654321.RESOLVED
```

### PR DESCRIPTION
**Pull request by danhhz**
Previously, the cloud storage sink put every file in a single directory,
but this can quickly get out of hand. Partitoning by date is pretty
standard, so start with that and if someone needs more control, we can
plumb down an option.

Closes #34473

Release note (enterprise change): `CHANGEFEED`s targeting cloud sinks
now partition files into date folders.

### CODE REVIEW

**Comment by danhhz** [comment]
Hey @rolandcrosby I went to do #34473 and realized that 1) date partitions are probably standard enough that we don't need to plumb down an option yet and 2) partitioning is a reasonable default. Thoughts on doing the simple thing I have here and just always partitioning by date?

**Comment by rolandcrosby** [comment]
Eminently reasonable; a good safe default. Ship it!

**Review by tbg — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34813)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34813)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/helpers_test.go, line 704 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34813#-LYY0NYDE3EBGQ6rb90U:-LYY0NYE3MvYFgexyWNb:bcj5xna) ([raw file](https://github.com/cockroachdb/cockroach/blob/6acc2d40156b62d74a4a31ceace9c9e2278408e5/pkg/ccl/changefeedccl/helpers_test.go#L704)):*
> ```Go
> }
> 
> func (c *cloudFeed) walkDir(path string, info os.FileInfo, err error) error {
> ```

Forgot to account for the new path structure in r1 of this PR. Switched to using filepath.Walk, which is much cleaner. Dunno what I was thinking before, I literally had copied parts of the filepath.Walk impl.

**Comment by danhhz** [comment]
Haven't repro'd the other test failure yet. Trying now inside build/builder.sh

**Comment by danhhz** [comment]
Thanks for the reviews!

bors r=tbg

**Comment by danhhz** [comment]
For real this time

bors r=tbg

**Pull request merged**
