### PR TITLE
storage: truncate log only between first index and truncate index

### PR DESCRIPTION
**Pull request by nvb**
### Question

Raft log truncations currently perform two steps (there may be
others, but for the sake of this discussion, let's consider only
these two):
1. above raft, they compute the stats of all raft log entries up
   to the truncation entry.
2. beneath raft, they use ClearIterRange to clear all raft log
   entries up to the truncation entry.

In both steps, operations are performed on all entries up to the
truncation entry, and in both steps these operations start from
entry 0. A comment added in #16993 gives some idea as to why:

> // We start at index zero because it's always possible that a previous
> // truncation did not clean up entries made obsolete by the previous
> // truncation.

My current understanding is that this case where a Raft log has
been truncated but its entries not cleaned up is only possible if
a node crashes between `applyRaftCommand` and `handleEvalResultRaftMuLocked`.
This brings up the question: why don't we truncate raft entries
downstream of raft in `applyRaftCommand`? That way, the entries
could be deleted atomically with the update to the `RaftTruncatedStateKey`
and we wouldn't have to worry about them ever diverging or Raft entries
being leaked. That seems like a trivial change, and if that was the
case, would the approach here be safe? I don't see a reason why
not.

### Motivation

For motivation on why we should explore this, I've found that when
running `sysbench oltp_insert` on a fresh cluster without pre-splits to
measure single range write through, raft log truncation accounts for
about **20%** of CPU utilization.

truncate

If we switch the ClearIterRange to a ClearRange downstream of raft,
we improve throughput by **13%** and reduce the amount of CPU that raft
log truncation uses to about **5%**. It's obvious why this speeds up the
actual truncation itself downstream of raft. The reason why it speeds
up the stats computation is less clear, but it may be allowing a RocksDB
iterator to more easily skip over the deleted entry keys.

If we make the change proposed here, we improve throughput by **28%** and
reduce the amount of CPU that raft log truncation uses to a negligible
amount (**< 1%**, hard to tell exactly). The reason this speeds both the
truncation and the stats computation is because it avoids iterating
over RocksDB tombstones for all Raft entries that have ever existed
on the range.

The throughput improvements are of course exaggerated because we are
isolating the throughput of a single range, but they're significant
enough to warrant exploration about whether we can make this approach
work.

### Extension

Finally, the outsized impact of this small change naturally justifies
further exploration. If we could make the change here safe (i.e. if we
could depend on replica.FirstIndex() to always be a lower bound on raft
log entry keys), could we make similar changes elsewhere? Are there
other places where we iterate over an entire raft log keyspace and
inadvertently run into all of the deletion tombstones when we could
simply skip to the `replica.FirstIndex()`? At a minimum, I believe
that `clearRangeData` fits this description, so there may be room to
speed up snapshots and replica GC.

cc. @tschottdorf @petermattis @benesch

### CODE REVIEW

**Comment by bdarnell** [comment]
> This brings up the question: why don't we truncate raft entries
downstream of raft in applyRaftCommand?

I think it's just the way the code is organized. In the propEvalKV project we moved everything but applying the pre-evaluated batch to replica_proposal.go. This was supposed to be memory-only side effects so we didn't have any facility for hooking a side effect like this into the main batch.

If range tombstones were cheap, we wouldn't have to do anything special here and could just truncate the log in evalTruncateLog itself. But we're trying to minimize the size of the batch that gets passed through raft without creating too many range tombstones, so we (effectively) have invented a new kind of range tombstone that we put in the raft command and apply ourselves.

Making this atomic with the batch commit and using FirstIndex instead of zero sounds like a good idea. I don't think there are any other places where we read the log starting from zero; raft itself is careful to always use FirstIndex.

**Comment by benesch** [comment]
> it may be allowing a RocksDB iterator to more easily skip over the deleted entry keys.

Oops, yes, I forgot Peter landed a change to our RocksDB fork (and maybe upstream too? I forget) that does literally exactly this.

**Comment by nvanbenschoten** [comment]
On a similar note, applying log truncations atomically with the rest of its raft entry will fix an issue where SysBytes can go negative because the deletion of a log entry will be double counted.

**Comment by nvanbenschoten** [comment]
I just brought this into a mergeable state. In doing so, I found and fixed a bug where we ignored the last entry in a raft log truncation interval above Raft.

I confirmed that the change still has the same performance impact on sysbench. I also found that this has an almost identical effect on `kv0` _with no pre-splits_. On my laptop it increased throughput by **18%**, reduced average operational latency by **16.2%**, and reduced 99th-percentile latency by **55%**! Even better, it seemed to dramatically reduce the amount of throughput dropoff the workload observes over time. This makes sense because without this change the cost of a raft log truncation would incrementally increase over time as the number of entry tombstones that each log truncation had to skip over continued to grow.

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28126)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/batcheval/cmd_truncate_log.go, line 84 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28126#-LJz1FhoE_fKLDlrZFF_:-LJz1FhoE_fKLDlrZFFa:bzdewhd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b60a6ce831a7555b99c58e58d3b8f71b3159ce3b/pkg/storage/batcheval/cmd_truncate_log.go#L84)):*
> ```Go
> 	}
> 
> 	start := engine.MakeMVCCMetadataKey(keys.RaftLogKey(rangeID, firstIndex))
> ```

I think this needs to be conditional on a new cluster version. Otherwise, clusters with non-finalized upgrades could leak log entries (and, surprisingly, this could leave gaps)

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28126)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/batcheval/cmd_truncate_log.go, line 84 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28126#-LJz1FhoE_fKLDlrZFF_:-LJz2pgkEqpWXsgOQvm-:b-twpqzb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b60a6ce831a7555b99c58e58d3b8f71b3159ce3b/pkg/storage/batcheval/cmd_truncate_log.go#L84)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I think this needs to be conditional on a new cluster version. Otherwise, clusters with non-finalized upgrades could leak log entries (and, surprisingly, this could leave gaps)
</blockquote></details>

Yeah sorry, I meant to make it explicit that the migration to this approach introduces a small window of opportunity to leak entries that will never be cleaned up. Specifically, a replica who was killed in between the `applyRaftCommand` and `handleReplicatedEvalResult` routines of its last log truncation before upgrading to this binary will temporarily leak those entries (but its stats will still be correct). However, these entries will eventually be cleaned up if the replica is ever rebalanced. You may feel differently, but my thought was that this is such a low-risk problem (because it sounds very rare and because the leaked entries are fairly harmless) that it didn't warrant the extra complication of making each replica guarantee an atomic log truncation starting from 0 before migrating to the new approach of truncating the log starting from `lastTruncatedIndex`.

Also, the change upstream of Raft is strictly a correctness fix and doesn't need a cluster version. Starting from 0 when computing the stats was double counting the stats delta for entries that we not cleaned up during a previous log truncation.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28126)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/batcheval/cmd_truncate_log.go, line 84 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28126#-LJz1FhoE_fKLDlrZFF_:-LJz5woV180sGU61oqXG:bqqxb2k) ([raw file](https://github.com/cockroachdb/cockroach/blob/b60a6ce831a7555b99c58e58d3b8f71b3159ce3b/pkg/storage/batcheval/cmd_truncate_log.go#L84)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah sorry, I meant to make it explicit that the migration to this approach introduces a small window of opportunity to leak entries that will never be cleaned up. Specifically, a replica who was killed in between the `applyRaftCommand` and `handleReplicatedEvalResult` routines of its last log truncation before upgrading to this binary will temporarily leak those entries (but its stats will still be correct). However, these entries will eventually be cleaned up if the replica is ever rebalanced. You may feel differently, but my thought was that this is such a low-risk problem (because it sounds very rare and because the leaked entries are fairly harmless) that it didn't warrant the extra complication of making each replica guarantee an atomic log truncation starting from 0 before migrating to the new approach of truncating the log starting from `lastTruncatedIndex`.

Also, the change upstream of Raft is strictly a correctness fix and doesn't need a cluster version. Starting from 0 when computing the stats was double counting the stats delta for entries that we not cleaned up during a previous log truncation.
</blockquote></details>

s/`never be cleaned up`/`not be cleaned up until a replica is destroyed`/

**Review by bdarnell — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28126)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/batcheval/cmd_truncate_log.go, line 84 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28126#-LJz1FhoE_fKLDlrZFF_:-LJz7i692zDsk_Vq9YR2:b-viokus) ([raw file](https://github.com/cockroachdb/cockroach/blob/b60a6ce831a7555b99c58e58d3b8f71b3159ce3b/pkg/storage/batcheval/cmd_truncate_log.go#L84)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

s/`never be cleaned up`/`not be cleaned up until a replica is destroyed`/
</blockquote></details>

The problem is that in a 3-node cluster, rebalancing is impossible, so they'll stick around forever. And the fact that the log becomes non-contiguous seems like it might be a problem (although we store the truncation index so nothing is ever supposed to look at these lost entries).

But good point that we can't just solve it here, we'd have to do something that would ensure a single run of the truncation from zero (which implies extra state). If it's going to be that difficult to address, I think it's rare enough (and probably-harmless enough) not to bother.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28126)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 5707 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28126#-LJz811O6YodbUcwZGKN:-LJz811O6YodbUcwZGKO:b2qqrdw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b60a6ce831a7555b99c58e58d3b8f71b3159ce3b/pkg/storage/replica.go#L5707)):*
> ```Go
> 				log.Errorf(ctx, "unable to clear truncated Raft entries for %+v: %s", rResult.State.TruncatedState, err)
> 			}
> 			iter.Close()
> ```

One oddity about performing the truncation above-Raft is that the Raft log truncation op contains the keys of the Raft log entries being deleted. I suppose this is necessary to ensure that the update of the `TruncatedState` and the clearing of the keys happens atomically.

An alternative idea which wouldn't involve a new cluster version, would be to leave the truncation below Raft but use an unreplicated local key to store the first entry in the Raft log. This would only need to be read when replica state is loaded, but would be written on every truncation. Might not have the same benefit as the approach here. I haven't thought through the pros and cons of this approach.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28126)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 5707 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28126#-LJz811O6YodbUcwZGKN:-LJzAm4zBkZu20Ajq2hV:b-966174) ([raw file](https://github.com/cockroachdb/cockroach/blob/b60a6ce831a7555b99c58e58d3b8f71b3159ce3b/pkg/storage/replica.go#L5707)):*
> would be to leave the truncation below Raft

Just to be clear, this change isn't moving the log truncation back above Raft, it's just making its application atomic with the rest of the write batch.

I think I'm probably misunderstanding your point. Are you saying that the extra unreplicated state could be used to solve the leaked entries problem Ben and I are discussing below? That's kind of what I had in mind for the migration, if we decided one was necessary.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28126)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 5707 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28126#-LJz811O6YodbUcwZGKN:-LJzCKex4U_Oxiu_wZW8:b-6yroe7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b60a6ce831a7555b99c58e58d3b8f71b3159ce3b/pkg/storage/replica.go#L5707)):*
Ah, I think I mistook `applyRaftCommand` for `processRaftCommand`. You're right this is still happening below Raft. 

> Are you saying that the extra unreplicated state could be used to solve the leaked entries problem Ben and I are discussing below? 

Yes.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28126)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/batcheval/cmd_truncate_log.go, line 84 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28126#-LJz1FhoE_fKLDlrZFF_:-LJzD7EQ0NmIrrC-aCQe:b34yiqm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b60a6ce831a7555b99c58e58d3b8f71b3159ce3b/pkg/storage/batcheval/cmd_truncate_log.go#L84)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

The problem is that in a 3-node cluster, rebalancing is impossible, so they'll stick around forever. And the fact that the log becomes non-contiguous seems like it might be a problem (although we store the truncation index so nothing is ever supposed to look at these lost entries).

But good point that we can't just solve it here, we'd have to do something that would ensure a single run of the truncation from zero (which implies extra state). If it's going to be that difficult to address, I think it's rare enough (and probably-harmless enough) not to bother. 
</blockquote></details>

Perhaps we truncate the Raft log from 0 to firstIndex when a Replica is loaded or some other infrequent time.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28126)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/batcheval/cmd_truncate_log.go, line 84 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28126#-LJz1FhoE_fKLDlrZFF_:-LJzNA5w1Sb0G2QJ2GC7:biio5kd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b60a6ce831a7555b99c58e58d3b8f71b3159ce3b/pkg/storage/batcheval/cmd_truncate_log.go#L84)):*
> Perhaps we truncate the Raft log from 0 to firstIndex when a Replica is loaded or some other infrequent time.

I'd hate to have to perform writes for every replica when loading them, especially in light of @spencerkimball's work to speed up startup.

We could do this write during consistency checks, although if we did that we'd never have any guarantee that all ranges were touched before upgrading to future versions, so we wouldn't be able to ever remove the code with 100% confidence that it cleared out all leaked entries.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28126)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/batcheval/cmd_truncate_log.go, line 84 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28126#-LJz1FhoE_fKLDlrZFF_:-LK-WMX1CT21tJ8Nz1YA:b-swb9xf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b60a6ce831a7555b99c58e58d3b8f71b3159ce3b/pkg/storage/batcheval/cmd_truncate_log.go#L84)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> Perhaps we truncate the Raft log from 0 to firstIndex when a Replica is loaded or some other infrequent time.

I'd hate to have to perform writes for every replica when loading them, especially in light of @spencerkimball's work to speed up startup.

We could do this write during consistency checks, although if we did that we'd never have any guarantee that all ranges were touched before upgrading to future versions, so we wouldn't be able to ever remove the code with 100% confidence that it cleared out all leaked entries.
</blockquote></details>

Ack. Don't let me comments hold up this PR. You and Ben have thought about this more deeply than I have. I'm just driving by.

**Review by tbg — APPROVED** [review]
Pretty exciting stuff.

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28126#-:-LK15TQXCsKuDLeLL30_:buecl4e)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/batcheval/cmd_truncate_log.go, line 84 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28126#-LJz1FhoE_fKLDlrZFF_:-LK15eQ21VwCqKl4gjOA:bxfulwf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b60a6ce831a7555b99c58e58d3b8f71b3159ce3b/pkg/storage/batcheval/cmd_truncate_log.go#L84)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ack. Don't let me comments hold up this PR. You and Ben have thought about this more deeply than I have. I'm just driving by.
</blockquote></details>

We could make the writes conditional on there being something to delete, so it would be a single seek (two if you count loading the truncated state, but that needs to happen anyway). Not sure if that would still be too slow (the seek hits a tombstone minefield) to be done, for instance, at server boot time. If it still is, we can write some migration checkpoint key once it's been done once (with the new cluster version active).

I agree that leftover entries hopefully wouldn't ever be a problem, but I don't think we should risk it.

**Comment by nvanbenschoten** [comment]
A follow-on thought I'm now having is that we shouldn't even need to use `ClearIterRange` to clear Raft entries during log truncations. All Raft entries are at discrete keys and we know the start and end bounds ahead of time, so we should be able to lay down a series of blind deletes without the need for iteration at all. We also already computed the stats upstream of Raft so there's really nothing to look at in the truncation interval. I'm not going to make that change here, but I'm curious if anyone sees any holes in that approach.

**Comment by nvanbenschoten** [comment]
> I'm not going to make that change here

Never mind, I just did because it was a trivial change that made the code cleaner. Over a series of 4 trials before and after, the approach improved throughput of single-range sysbench oltp_insert by **5.94%** (p=0.029).

**Review by petermattis — APPROVED** [review]
I didn't review the migration code. Hopefully someone else can scrutinize that.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28126#-:-LK9ZyIi9IQrsW6YDlWi:b-jbamd0)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/keys/keys.go, line 349 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28126#-LK9YqX0CqzaH3BcAgE4:-LK9YqX0CqzaH3BcAgE5:b-x8129n) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d09a325aa8b194976665ba36d1ba1335c973874/pkg/keys/keys.go#L349)):*
> ```Go
> // AppendRaftLogIndexToRaftLogPrefix returns a system-local key
> // for a Raft log entry using the provided Raft log prefix.
> func AppendRaftLogIndexToRaftLogPrefix(prefix roachpb.Key, logIndex uint64) roachpb.Key {
> ```

Holy-long-function-name, Batman!
___
*[pkg/storage/replica.go, line 5729 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28126#-LK9ZW8z27z_dTajYW0E:-LK9ZW8z27z_dTajYW0F:bwfe48y) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d09a325aa8b194976665ba36d1ba1335c973874/pkg/storage/replica.go#L5729)):*
> ```Go
> 				keyPrefixBuf = make([]byte, len(keyPrefix), len(keyPrefix)+extraCap)
> 				copy(keyPrefixBuf, keyPrefix)
> 			}
> ```

This seems overly complicated. I'm wondering if you can do something like:

```
prefixBuf := &r.raftMu.stateLoader.RangeIDPrefixBuf
for idx := oldTruncatedState.Index + 1; idx <= newTruncatedState.Index; idx++ {
  unsafeKey := prefixBuf.RaftLogKey(idx)
  ...
}
```

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28126)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/keys/keys.go, line 349 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28126#-LK9YqX0CqzaH3BcAgE4:-LKDLTXtBwGnDGLyD-_n:b7ge6ca) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d09a325aa8b194976665ba36d1ba1335c973874/pkg/keys/keys.go#L349)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Holy-long-function-name, Batman!
</blockquote></details>

Renamed to `AppendRaftLogIndexToPrefix`.
___
*[pkg/storage/replica.go, line 5707 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28126#-LJz811O6YodbUcwZGKN:-LKDLW5L3Xp5WhexjThK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b60a6ce831a7555b99c58e58d3b8f71b3159ce3b/pkg/storage/replica.go#L5707)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ah, I think I mistook `applyRaftCommand` for `processRaftCommand`. You're right this is still happening below Raft. 

> Are you saying that the extra unreplicated state could be used to solve the leaked entries problem Ben and I are discussing below? 

Yes.
</blockquote></details>

Done.
___
*[pkg/storage/replica.go, line 5729 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28126#-LK9ZW8z27z_dTajYW0E:-LKDLY10Dv5eBzAYWzjy:b-f1pyca) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d09a325aa8b194976665ba36d1ba1335c973874/pkg/storage/replica.go#L5729)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This seems overly complicated. I'm wondering if you can do something like:

```
prefixBuf := &r.raftMu.stateLoader.RangeIDPrefixBuf
for idx := oldTruncatedState.Index + 1; idx <= newTruncatedState.Index; idx++ {
  unsafeKey := prefixBuf.RaftLogKey(idx)
  ...
}
```
</blockquote></details>

The risk I'm trying to avoid here is `RangeIDPrefixBuf` not having sufficient capacity and every call to `RaftLogKey` forcing an allocation. Do you see a cleaner way to accomplish this?
___
*[pkg/storage/batcheval/cmd_truncate_log.go, line 84 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28126#-LJz1FhoE_fKLDlrZFF_:-LKDLXKD1JtYs9oRdFGo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b60a6ce831a7555b99c58e58d3b8f71b3159ce3b/pkg/storage/batcheval/cmd_truncate_log.go#L84)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

We could make the writes conditional on there being something to delete, so it would be a single seek (two if you count loading the truncated state, but that needs to happen anyway). Not sure if that would still be too slow (the seek hits a tombstone minefield) to be done, for instance, at server boot time. If it still is, we can write some migration checkpoint key once it's been done once (with the new cluster version active).

I agree that leftover entries hopefully wouldn't ever be a problem, but I don't think we should risk it.
</blockquote></details>

Done.

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28126)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/keys/keys.go, line 349 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28126#-LK9YqX0CqzaH3BcAgE4:-LKDPpKu5SxrzeKzU9KT:b-a5ntql) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d09a325aa8b194976665ba36d1ba1335c973874/pkg/keys/keys.go#L349)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Renamed to `AppendRaftLogIndexToPrefix`.
</blockquote></details>

Ack, though I think this can go away with my other comment.
___
*[pkg/storage/replica.go, line 5729 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28126#-LK9ZW8z27z_dTajYW0E:-LKDP3_21t4MD_s_sI9N:b-jihao) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d09a325aa8b194976665ba36d1ba1335c973874/pkg/storage/replica.go#L5729)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The risk I'm trying to avoid here is `RangeIDPrefixBuf` not having sufficient capacity and every call to `RaftLogKey` forcing an allocation. Do you see a cleaner way to accomplish this?
</blockquote></details>

Sure. `RangeIDPrefixBuf` is simply `type RangeIDPrefixBuf roachpb.Key`. So just make a larger one:

```
  prefixBuf := make(keys.RangeIDPrefixBuf, 0, 128)
  prefixBuf = append(prefixBuf, r.raftMu.stateLoader.RangeIDPrefixBuf...)  
```

I thought I had calculated that the default `RangeIDPrefixBuf` size (32) was sufficient for Raft log entries, though.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28126)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/keys/keys.go, line 349 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28126#-LK9YqX0CqzaH3BcAgE4:-LKDe_ww1OTVMxSR0wYL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d09a325aa8b194976665ba36d1ba1335c973874/pkg/keys/keys.go#L349)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ack, though I think this can go away with my other comment.
</blockquote></details>

Done.
___
*[pkg/storage/replica.go, line 5729 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28126#-LK9ZW8z27z_dTajYW0E:-LKDeack0mvswLBtQcyG:b-bnltm9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d09a325aa8b194976665ba36d1ba1335c973874/pkg/storage/replica.go#L5729)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Sure. `RangeIDPrefixBuf` is simply `type RangeIDPrefixBuf roachpb.Key`. So just make a larger one:

```
  prefixBuf := make(keys.RangeIDPrefixBuf, 0, 128)
  prefixBuf = append(prefixBuf, r.raftMu.stateLoader.RangeIDPrefixBuf...)  
```

I thought I had calculated that the default `RangeIDPrefixBuf` size (32) was sufficient for Raft log entries, though.
</blockquote></details>

Oh nice, TIL! Raft log keys are only 16 bytes long, so your first suggestion was spot on. Done.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28126#-:-LKEDT6v4ettbajNcdlm:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
