### PR TITLE
c-deps: bump rocksdb for intra-L0+ingest corruption fix

### PR DESCRIPTION
**Pull request by ajkr**
Picks up https://github.com/cockroachdb/rocksdb/pull/70.

Release note (bug fix): Prevent rare corruption when files are ingested
that do not overlap with the in-memory buffer and compaction has fallen
behind.

### CODE REVIEW

**Comment by ajkr** [comment]
Do we need this backported to pre-19.2? I forget why we thought it was specific to 19.2. Weren't we using file ingestion to some extent even earlier?

**Review by petermattis — APPROVED** [review]
LGTM

> Do we need this backported to pre-19.2? I forget why we thought it was specific to 19.2. Weren't we using file ingestion to some extent even earlier?

Yes, we should backport to 19.1 as well. We think the problem is exacerbated by increased usage of sstable ingestion (for rebalancing) in 19.2, but I don't see a reason this couldn't happen with schema changes in 19.1.

**Comment by petermattis** [comment]
> Release note (bug fix): Prevent rare corruption when files are ingested
and flush/compaction are both behind.

I don't quite understand this explanation, though I'm struggling to come up with a succinct explanation of the bug conditions. What do you mean by "are both behind"?

**Comment by ajkr** [comment]
L0 has to fill up while L0->Lbase is taking place to trigger intra-L0. Immutable memtable has to be not flushed even when files newer than it are ingested. Let me think if there's a better summary than behind as it seems not so accurate for the flush case.

**Comment by ajkr** [comment]
How about "Prevent rare corruption when files are ingested that do not overlap with the in-memory buffer and compaction has fallen behind"?

**Comment by petermattis** [comment]
> L0 has to fill up while L0->Lbase is taking place to trigger intra-L0. Immutable memtable has to be not flushed even when files newer than it are ingested. Let me think if there's a better summary than behind as it seems not so accurate for the flush case.

Yeah, it seems difficulty to describe this concisely. Perhaps something like "Fixes a rare corruption bug involving concurrent intra-L0 compactions, ingestions, and mutations".

**Comment by petermattis** [comment]
> How about "Prevent rare corruption when files are ingested that do not overlap with the in-memory buffer and compaction has fallen behind"?

That works for me.

**Comment by ajkr** [comment]
TFTR.

bors r+

**Pull request merged**
