### PR TITLE
storage: Fix the DisableReplicaRebalancing testing knob

### PR DESCRIPTION
**Pull request by a-robinson**
Also prioritize replica rebalancing over lease rebalancing, although I'm not too attached to that change if you're opposed.

### CODE REVIEW

**Comment by a-robinson** [comment]
To be clear, I found the issue with `DisableReplicaRebalancing` by looking at the code, not by tracking down any specific test failures. It's possible that it wasn't actually hurting anything, I don't know.

**Comment by petermattis** [comment]
I'm mildly anxious about the second commit, mainly because it is late in the cycle and it might have an effect. Perhaps we should hold off on that change until 1.2. 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17584#-:-KrCmAV3edQl5Y9STzhP:b-d20biq)*

**Comment by a-robinson** [comment]
Alright, I've removed the second commit and opened up a separate PR (#17595) that we can merge after the 1.1 branch has been cut.

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17584#-:-KrHZN3PAwcWnwHCGNxb:bnfp4nl)*

**Comment by BramGruneir** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17584#-:-KrHehX6zbQIIYjgwv24:bnfp4nl)*

**Pull request merged**
