### PR TITLE
ccl/storageccl: use file registry for atomic data registry rotations

### PR DESCRIPTION
**Pull request by jbowens**
Previously, we overwrote the `COCKROACHDB_DATA_KEYS` file each time.
However, because the DataKeyManager reads and writes to the encryptedFS,
Renames are not atomic, and `SafeWriteToFile` is not safe.

To work around this, when using the new records-based
incrementally-updated file registry, this change:

* Writes the updated data keys registry to a new file path.
* Writes an updated enginepbccl.RegistryMetadata protocol buffer to the
  file registry, including the new data keys registry filename. At this
  point the new registry is active.
* Removes the old registry file.

If we're still using the old, monolithic file registry because the
upgrade to 21.2 has not been finalized yet, we continue replacing the
file at `COCKROACHDB_DATA_KEYS`, hoping there's no crash in the middle
of the Rename.

Release justification: Fix for high-severity bug in existing
functionality
Release note (bug fix): Fixes rare bug whereby an crash during
encryption-at-rest data key rotation would corrupt the store, preventing
future CockroachDB starts.

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
This still needs tests (plus adjusting existing tests), but I wanted to put it up to solicit some discussion on the approach.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69390#-:-MhzDXG09e3Z9Rj5wbq-:bueo6m0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @shermanCRL and @sumeerbhola)

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69390)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens)

___
*[pkg/storage/enginepb/file_registry.proto, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69390#-Mi6wymg0k7eOYSdwOGv:-Mi6wymg0k7eOYSdwOGw:b2xb0np) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff7473ca6ecf1cd04f3f9193882635df66777a9f/pkg/storage/enginepb/file_registry.proto#L78)):*
> ```protobuf
>   // Updates to env-specific, global settings. These are known by CCL
>   // code only.
>   google.protobuf.Any global_settings = 2;
> ```

Do we need this if we didn't need to record the data keys filename?

I realize there is also the use case of allowing incompatible file format changes, but I'd prefer if we could handle those by the file contents itself being self-describing wrt version. Protos allow for that. Except when the incompatibility is outside the scope of the proto itself, like when we shift from writing the raw proto to using `record.Writer`. Given that we already have a way to distinguish the current switch based on the filename (no suffix vs suffix), how about we trivially use `record.Writer` now itself to write a single proto. That will set us up to introduce future versions that change from single proto to multiple incremental protos, where we can record the version in the first `DataKeysRegistry` record in the file.

That will eliminate all the file registry changes from this PR, and be less coupling between different sub-components. And the file registry can remain as purely a registry of individual files instead of also having some global info.

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69390)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/storage/enginepb/file_registry.proto, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69390#-Mi6wymg0k7eOYSdwOGv:-Mi89Tj4EX2Fu6BNljqn:bihqj54) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff7473ca6ecf1cd04f3f9193882635df66777a9f/pkg/storage/enginepb/file_registry.proto#L78)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Do we need this if we didn't need to record the data keys filename?

I realize there is also the use case of allowing incompatible file format changes, but I'd prefer if we could handle those by the file contents itself being self-describing wrt version. Protos allow for that. Except when the incompatibility is outside the scope of the proto itself, like when we shift from writing the raw proto to using `record.Writer`. Given that we already have a way to distinguish the current switch based on the filename (no suffix vs suffix), how about we trivially use `record.Writer` now itself to write a single proto. That will set us up to introduce future versions that change from single proto to multiple incremental protos, where we can record the version in the first `DataKeysRegistry` record in the file.

That will eliminate all the file registry changes from this PR, and be less coupling between different sub-components. And the file registry can remain as purely a registry of individual files instead of also having some global info.
</blockquote></details>

No, we don't need it if we decide not to record the data keys filename.

I originally started down the monotonically increasing file number scheme (see https://github.com/cockroachdb/cockroach/commit/4e0fb087664309ae63519f70eb544718fc958834) but I concluded that it was more complex and less explicit than recording to the file registry. Curious your thoughts after looking at the above commit.

**Comment by sumeerbhola** [comment]
> I originally started down the monotonically increasing file number scheme (see 4e0fb08) but I concluded that it was more complex and less explicit than recording to the file registry. Curious your thoughts after looking at the above commit.

IMO that commit is simpler. It introduces a clean abstraction and hides all the complexity in the implementation of that abstraction, rather than each use case invent its own solution. We'd need to tweak that interface of course, for using in all 3 use cases (manifest, file registry, data keys registry), and should move it to Pebble, so can be used by both Pebble and CockroachDB. Of course this is only relevant if we don't add functionality to do atomic renames in encryptedFS.

**Comment by jbowens** [comment]
Closing in favor of #70156.

**Pull request closed without merging**
