### PR TITLE
sql/parser: Switch default numeric type to DECIMAL

### LINKED ISSUE #6369: sql: Investigate float overflows and when decimal should be the natural constant type
In the initial implementation of Summer, all non-int numeric constants had a natural type of FLOAT. We should adjust this based on if the FLOAT datatype would lose information. For instance, `9223372036854775808` should probably have a natural type of DECIMAL so that it doesnt lose information without a desired type.

### PR DESCRIPTION
**Pull request by nvb**
Resolves #6369.

This change switches the default non-inst constant value to DECIMAL.
This prevents any information loss for constant literals.

The test changes focused on explicitly casting old constants to FLOAT
to prevent code coverage regressions.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6752)

### CODE REVIEW

**Comment by knz** [comment]
I guess you want to write "the default non-int constant type" in this commit message, right?

Also I'd suggest a performance benchmark alongside this PR to illustrate the perf change for common operations involving a simple BinOp on heterogeneous arguments one of which being a literal decimal.

<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> #### sql/parser: Switch default numeric value to DECIMAL
> 
> Resolves #6369.
> 
> 
> 
> This change switches the default non-inst constant value to DECIMAL.
> 
> This prevents any information loss for constant literals.
> 
> 
> 
> The test changes focused on explicitly casting old constants to FLOAT
> 
> to prevent code coverage regressions.
> 
> 
> </details>


---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/set.go, line 153 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6752#-KHzffdTijJXpUfFr1Ep:-KHzffdUT713g29jT3my:-1973894816) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6351f23aa833e02f4d5fcfcb8752a107f7cd0f8/sql/set.go#L153)):*
> ```Go
> 			return nil, err
> 		}
> 		offset = int64(f * 60.0 * 60.0)
> ```

Wait what is the rationale for this change? It does not feel like it belongs to this PR.

---

*[sql/parser/constant.go, line 155 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6752#-KHzg1i5I3ZA1MDama2j:-KHzg1i5I3ZA1MDama2k:530397566) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6351f23aa833e02f4d5fcfcb8752a107f7cd0f8/sql/parser/constant.go#L155)):*
> ```Go
> 		return 0, fmt.Errorf("integer value out of range: %v", intVal)
> 	}
> 	expr.resInt = DInt(i)
> ```

Please update the comment of this function to explain that it modifies the NumVal and why this is so.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6752#-:-KHzfKkmweyGRc02gQxG:-320542215)*

**Comment by nvanbenschoten** [comment]
Thanks for the review! I'm not exactly sure I understand what you want to benchmark. If you are looking for constant arithmetic evaluation, this will all take place during normalization with exact arithmetic, so this change doesn't change anything. Which operations are you referring to?

<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> I guess you want to write "the default non-int constant type" in this commit message, right?
> 
> Also I'd suggest a performance benchmark alongside this PR to illustrate the perf change for common operations involving a simple BinOp on heterogeneous arguments one of which being a literal decimal.</details>


---

Review status: 13 of 15 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/set.go, line 153 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6752#-KHzffdTijJXpUfFr1Ep:-KHzz2lptXSuSmqdsP2L:597855997) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6351f23aa833e02f4d5fcfcb8752a107f7cd0f8/sql/set.go#L153)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Wait what is the rationale for this change? It does not feel like it belongs to this PR.</details>
`sixty.Unscaled()` was having issues, and I meant to add a TODO to look into it. It turns out we needed to Truncate before calling the method. This is inline with how we handle floats.

---

*[sql/parser/constant.go, line 155 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6752#-KHzg1i5I3ZA1MDama2j:-KHzzfBAchYzJczdzVcv:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6351f23aa833e02f4d5fcfcb8752a107f7cd0f8/sql/parser/constant.go#L155)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Please update the comment of this function to explain that it modifies the NumVal and why this is so.</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6752#-:-KHzzoP-j1FvP3JkeZfk:233240408)*

**Comment by knz** [comment]
I mean the fact that in many cases placeholders now are inferred to decimal instead of float. It might not make a lot of difference for query throughput but we may want to quantify that.

<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Thanks for the review! I'm not exactly sure I understand what you want to benchmark. If you are looking for constant arithmetic evaluation, this will all take place during normalization with exact arithmetic, so this change doesn't change anything. Which operations are you referring to?</details>


---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6752#-:-KI-TcA5AyKDQ7o6LuMG:2138851909)*

**Comment by nvanbenschoten** [comment]
I'm a little curious which cases you're referring to. Operations that work on rows will have a defined schema with concrete types, so this change shouldn't affect them.

<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> I mean the fact that in many cases placeholders now are inferred to decimal instead of float. It might not make a lot of difference for query throughput but we may want to quantify that.</details>


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6752#-:-KI-bDEJC3OmGlZ-onGY:-1020612891)*

**Comment by knz** [comment]
The case I'm thinking of is `column < ($1 + 3.5)`

I'm not sure we type $1 in the same way then. Or do we?

LGTM otherwise.

**Comment by nvanbenschoten** [comment]
I added a new benchmark that specifically stresses INT to NUMERIC comparisons. The results demonstrate why a follow on PR that adds a temporary `inf.Dec` to the `EvalContext` so that we can avoid allocations on these comparisons is so important.

```
name                 old time/op    new time/op    delta
Select3_Cockroach-4    1.17ms ± 2%    1.31ms ± 3%  +11.87%  (p=0.000 n=9+10)

name                 old alloc/op   new alloc/op   delta
Select3_Cockroach-4     147kB ± 0%     182kB ± 0%  +23.92%   (p=0.000 n=9+9)

name                 old allocs/op  new allocs/op  delta
Select3_Cockroach-4     2.37k ± 0%     3.19k ± 0%  +34.63%  (p=0.000 n=9+10)
```

<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> The case I'm thinking of is `column < ($1 + 3.5)`
> 
> 
> 
> I'm not sure we type $1 in the same way then. Or do we?
> 
> 
> 
> LGTM otherwise.
</details>


---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6752#-:-KI4OBkFWegGakuRQrfY:174004710)*

**Comment by nvanbenschoten** [comment]
I have a trio of follow-up commits that focus on this regression. It looks like those will actually make this change all in all a performance win!

Benchmark: before perf commits vs. after
```
name                 old time/op    new time/op    delta
Select3_Cockroach-4    1.33ms ± 4%    1.08ms ± 3%  -18.41%  (p=0.000 n=20+19)

name                 old alloc/op   new alloc/op   delta
Select3_Cockroach-4     182kB ± 0%     139kB ± 0%  -23.70%  (p=0.000 n=18+20)

name                 old allocs/op  new allocs/op  delta
Select3_Cockroach-4     3.19k ± 0%     2.26k ± 0%  -28.90%  (p=0.000 n=17+20)
```

Benchmark: before this commit and perf commits vs. after
```
name                 old time/op    new time/op    delta
Select3_Cockroach-4    1.22ms ± 9%    1.10ms ± 4%  -9.37%  (p=0.000 n=20+20)

name                 old alloc/op   new alloc/op   delta
Select3_Cockroach-4     147kB ± 0%     139kB ± 0%  -5.47%  (p=0.000 n=18+19)

name                 old allocs/op  new allocs/op  delta
Select3_Cockroach-4     2.37k ± 0%     2.26k ± 0%  -4.29%  (p=0.000 n=18+20)
```

<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> I added a new benchmark that specifically stresses INT to NUMERIC comparisons. The results demonstrate why a follow on PR that adds a temporary `inf.Dec` to the `EvalContext` so that we can avoid allocations on these comparisons is so important.
> 
> ```
> name                 old time/op    new time/op    delta
> Select3_Cockroach-4    1.17ms ± 2%    1.31ms ± 3%  +11.87%  (p=0.000 n=9+10)
> 
> name                 old alloc/op   new alloc/op   delta
> Select3_Cockroach-4     147kB ± 0%     182kB ± 0%  +23.92%   (p=0.000 n=9+9)
> 
> name                 old allocs/op  new allocs/op  delta
> Select3_Cockroach-4     2.37k ± 0%     3.19k ± 0%  +34.63%  (p=0.000 n=9+10)
> ```
</details>


---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6752#-:-KI4uGZ7k-1xEtzewQZR:-1730610994)*

**Comment by jseldess** [comment]
Talked with Nathan about impact on docs. From user perspective, this seems to only affect `int / int`, which outputs decimal now instead of float.

**Pull request merged**
