### PR TITLE
sql: use Datums for offsets of window frames

### PR DESCRIPTION
**Pull request by yuzefovich**
Adds support for storing non-integer offsets
of window frames necessary for RANGE mode.
Also checks that there is ordering on a single
column that window function is computed over
if in RANGE mode.

Incremental change towards: #27100.

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
As I mentioned in #27100, Postgres plans to fully support all frame specifications in SQL:2011 standard in Release 11. However, I installed today Release 11 Beta 2, and, unfortunately, `RANGE` mode with `value PRECEDING/FOLLOWING` is not there yet, so I don't have an example to follow. This code's behavior is based off their docs https://www.postgresql.org/docs/11/static/sql-expressions.html#SYNTAX-WINDOW-FUNCTIONS.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-:-LIh0zpr3tshllraBZy9:b-c7uem8)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by nvb — CHANGES_REQUESTED** [review]
Nice! Although this certainly needs a lot of tests to go along with it.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-:-LIibc0_7EtW9N-E6VMQ:b-5b29yc)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/window.go, line 721 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIiaXRU6L-2qLA0-tKD:-LIiaXRU6L-2qLA0-tKE:ba82xnc) ([raw file](https://github.com/cockroachdb/cockroach/blob/85ab8bc5959edd4bc31aa97a5d7877edd482ceae/pkg/sql/window.go#L721)):*
> ```Go
> 						return pgerror.NewErrorf(pgerror.CodeWindowingError, "RANGE mode requires that the ORDER BY clause specify exactly one column")
> 					}
> 					// Assumption: renderNode is a parent of windowNode, and it's renders
> ```

`s/it's/its/`
___
*[pkg/sql/window.go, line 722 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIiaanv-QqF2gbvQ7oQ:-LIiaanv-QqF2gbvQ7oR:b-vanuge) ([raw file](https://github.com/cockroachdb/cockroach/blob/85ab8bc5959edd4bc31aa97a5d7877edd482ceae/pkg/sql/window.go#L722)):*
> ```Go
> 					}
> 					// Assumption: renderNode is a parent of windowNode, and it's renders
> 					// contain IndexedVar's representing the input columns. To make sure
> ```

`s/IndexedVar's/IndexedVars/`
___
*[pkg/sql/window.go, line 735 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIialW7ELkdk1o72ZFI:-LIialW7ELkdk1o72ZFJ:bh6fb3j) ([raw file](https://github.com/cockroachdb/cockroach/blob/85ab8bc5959edd4bc31aa97a5d7877edd482ceae/pkg/sql/window.go#L735)):*
> ```Go
> 							panic("unexpected: render of the ordering column is not an IndexedVar")
> 						}
> 						// TODO(yuzefovich): maybe we can simply compare two renders directly?
> ```

@knz how should we be performing this comparison?
___
*[pkg/sql/window.go, line 941 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIiazNaAbbkkQEeiJ7N:-LIiazNaAbbkkQEeiJ7O:bogt43r) ([raw file](https://github.com/cockroachdb/cockroach/blob/85ab8bc5959edd4bc31aa97a5d7877edd482ceae/pkg/sql/window.go#L941)):*
> ```Go
> 		return *o < 0
> 	case *tree.DInterval:
> 		// TODO(yuzefovich): what would be "negative" interval offset?
> ```

Intervals can't be negative?
___
*[pkg/sql/sem/tree/type_check.go, line 824 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIibBJ551fiH9XSb9MW:-LIibBJ6EyLPVacIFi6V:b6q52we) ([raw file](https://github.com/cockroachdb/cockroach/blob/85ab8bc5959edd4bc31aa97a5d7877edd482ceae/pkg/sql/sem/tree/type_check.go#L824)):*
> ```Go
> 			bounds := expr.WindowDef.Frame.Bounds
> 			startBound, endBound := bounds.StartBound, bounds.EndBound
> 			var requiredType types.T
> ```

It's very suspicious that this code is duplicated. That's almost certainly indicative of a programmer error.

**Review by knz — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28067)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/window.go, line 374 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIjhI36-LU8GocVuMMj:-LIjhI36-LU8GocVuMMk:b1aucqw) ([raw file](https://github.com/cockroachdb/cockroach/blob/85ab8bc5959edd4bc31aa97a5d7877edd482ceae/pkg/sql/window.go#L374)):*
> ```Go
> 			if startBound.OffsetExpr != nil {
> 				if startBound.OffsetExpr == tree.DNull {
> 					return pgerror.NewErrorf(pgerror.CodeWindowingError, "frame starting offset must be non-null")
> ```

you can't reliably test for NULL prior to type checking. The test for NULL should happen after you evaluate the expression at runtime.
___
*[pkg/sql/window.go, line 383 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIjhO-M68NeRjd0sPcQ:-LIjhO-M68NeRjd0sPcR:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/85ab8bc5959edd4bc31aa97a5d7877edd482ceae/pkg/sql/window.go#L383)):*
> ```Go
> 			}
> 			if endBound != nil && endBound.OffsetExpr != nil {
> 				if endBound.OffsetExpr == tree.DNull {
> ```

ditto
___
*[pkg/sql/window.go, line 735 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIialW7ELkdk1o72ZFI:-LIjhYgl8slIhA1iGtFo:b-4f6vjo) ([raw file](https://github.com/cockroachdb/cockroach/blob/85ab8bc5959edd4bc31aa97a5d7877edd482ceae/pkg/sql/window.go#L735)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

@knz how should we be performing this comparison?
</blockquote></details>

I think this is correct
___
*[pkg/sql/window.go, line 758 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIjhdS930wVvbW9YcBv:-LIjhdSA-WvXXRxjSV13:b2xrw90) ([raw file](https://github.com/cockroachdb/cockroach/blob/85ab8bc5959edd4bc31aa97a5d7877edd482ceae/pkg/sql/window.go#L758)):*
> ```Go
> 					return err
> 				}
> 				if isNegative(dStartOffset) {
> ```

ditto you can't check negativity during semantic analysis, you need to do this after you evaluate the expression.

**Review by yuzefovich — COMMENTED** [review]
I'm not sure how to test these changes: logic tests are not an option right now since `RANGE` mode is not fully supported. I guess I could introduce some kind of unit tests to make sure that offsets are of correct type, any suggestions where I could look as an example?

I also believe that the behavior of the already supported features should not change at all, so maybe we don't need tests right now, and I'll add them together with `RANGE` PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-:-LIk_KZ08yciT1D1i6KP:btw3eh5)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/window.go, line 374 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIjhI36-LU8GocVuMMj:-LIkQLTTE2Ayz2Lx4vF_:b1n96jj) ([raw file](https://github.com/cockroachdb/cockroach/blob/85ab8bc5959edd4bc31aa97a5d7877edd482ceae/pkg/sql/window.go#L374)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

you can't reliably test for NULL prior to type checking. The test for NULL should happen after you evaluate the expression at runtime.
</blockquote></details>

I see your point, but I'm slightly confused - is it safe to check for NULL after `typeCheckAndRequire` or only after `Eval`uating?
___
*[pkg/sql/window.go, line 383 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIjhO-M68NeRjd0sPcQ:-LIkSM3WD3WUf5UCMaAH:b2nreh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/85ab8bc5959edd4bc31aa97a5d7877edd482ceae/pkg/sql/window.go#L383)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Same as above.
___
*[pkg/sql/window.go, line 721 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIiaXRU6L-2qLA0-tKD:-LIkOX6i1H63gy742Qn0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/85ab8bc5959edd4bc31aa97a5d7877edd482ceae/pkg/sql/window.go#L721)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/it's/its/`
</blockquote></details>

Done.
___
*[pkg/sql/window.go, line 722 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIiaanv-QqF2gbvQ7oQ:-LIkOXVSAV1GsY1B_acM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/85ab8bc5959edd4bc31aa97a5d7877edd482ceae/pkg/sql/window.go#L722)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/IndexedVar's/IndexedVars/`
</blockquote></details>

Done.
___
*[pkg/sql/window.go, line 758 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIjhdS930wVvbW9YcBv:-LIkQfy2A7H30ahtkWIF:bjtnfmr) ([raw file](https://github.com/cockroachdb/cockroach/blob/85ab8bc5959edd4bc31aa97a5d7877edd482ceae/pkg/sql/window.go#L758)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto you can't check negativity during semantic analysis, you need to do this after you evaluate the expression.
</blockquote></details>

Yes, I'm calling `Eval` a few lines above, am I doing it wrong?
___
*[pkg/sql/window.go, line 941 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIiazNaAbbkkQEeiJ7N:-LIkRmwtAtMVp0kPbtJY:b-vapnk3) ([raw file](https://github.com/cockroachdb/cockroach/blob/85ab8bc5959edd4bc31aa97a5d7877edd482ceae/pkg/sql/window.go#L941)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Intervals can't be negative?
</blockquote></details>

I think they can, but I wasn't sure how I would specify negative intervals (I guess something like `-1 days`) and I just haven't had any experience with this type before. Please let me know if the comparison I added is not the way to go.
___
*[pkg/sql/sem/tree/type_check.go, line 824 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIibBJ551fiH9XSb9MW:-LIkOk6_CE4Pze0EoXCo:b81asqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/85ab8bc5959edd4bc31aa97a5d7877edd482ceae/pkg/sql/sem/tree/type_check.go#L824)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It's very suspicious that this code is duplicated. That's almost certainly indicative of a programmer error. 
</blockquote></details>

I extracted this check into a method to avoid to duplication.

I don't think, however, that we can avoid performing this check in two places - we need the check in `type_check.go` for window definitions that follow window functions directly (i.e. `f() OVER (window definition)`), and we need the check in `window.go` for window definitions from `WINDOW` clause.

**Review by knz — CHANGES_REQUESTED** [review]
Good progress. It was a good idea to factor the type checking of the window definitions.

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-:-LIm3Hcg7NIhDBc5in4b:bscizhx)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/window.go, line 374 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIjhI36-LU8GocVuMMj:-LIm3G-Y7_iftOimQQ-U:b-u6w6s9) ([raw file](https://github.com/cockroachdb/cockroach/blob/85ab8bc5959edd4bc31aa97a5d7877edd482ceae/pkg/sql/window.go#L374)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I see your point, but I'm slightly confused - is it safe to check for NULL after `typeCheckAndRequire` or only after `Eval`uating?
</blockquote></details>

See my comments below.
___
*[pkg/sql/window.go, line 758 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIjhdS930wVvbW9YcBv:-LIm2_ToEOj0F1DwcY0u:bfza8mv) ([raw file](https://github.com/cockroachdb/cockroach/blob/85ab8bc5959edd4bc31aa97a5d7877edd482ceae/pkg/sql/window.go#L758)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Yes, I'm calling `Eval` a few lines above, am I doing it wrong?
</blockquote></details>

no it's fine, I misread. 

However to reply to your other question, this is the place where the NULL value should be checked too.
___
*[pkg/sql/window.go, line 941 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIiazNaAbbkkQEeiJ7N:-LIm2kE69ZaA53RZT-NS:b7cjtog) ([raw file](https://github.com/cockroachdb/cockroach/blob/85ab8bc5959edd4bc31aa97a5d7877edd482ceae/pkg/sql/window.go#L941)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think they can, but I wasn't sure how I would specify negative intervals (I guess something like `-1 days`) and I just haven't had any experience with this type before. Please let me know if the comparison I added is not the way to go.
</blockquote></details>

the syntax is e.g. ` '-1day' ` (or `interval '-1day'` or `-interval '1 day'`)
___
*[pkg/sql/sem/tree/type_check.go, line 2124 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIm3-oh1LP5_A68P0oc:-LIm3-oh1LP5_A68P0od:b-amdwqt) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f93fec1b280b26d8a42d47805c3a5a7e3ca3549/pkg/sql/sem/tree/type_check.go#L2124)):*
> ```Go
> 		}
> 		startBound.OffsetExpr = typedStartOffsetExpr
> 		if startBound.OffsetExpr == DNull {
> ```

Again this is not correct. You can only check for DNull *after* `Eval` has been called (on the result of `Eval`).

**Review by knz — COMMENTED** [review]
> I guess I could introduce some kind of unit tests to make sure that offsets are of correct type, any suggestions where I could look as an example?

You can make logic tests that do just the planning but do not test the execution: `EXPLAIN(TYPES) SELECT....` should do the trick.

> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-:-LIm3bkd76Af4svsMsNL:b-1y01to)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by yuzefovich — COMMENTED** [review]
Good idea. I added a single test for `ROWS` mode, but I still cannot test all other types of offsets because parser doesn't support `RANGE 1.5 PRECEDING` and similar. Please let me know if there is another way to test other types as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-:-LImQsMqA385Kv6cIeeC:b-fuu2fp)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/window.go, line 374 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIjhI36-LU8GocVuMMj:-LIm5_RhAS5z13T0D-Fi:b-9755fa) ([raw file](https://github.com/cockroachdb/cockroach/blob/85ab8bc5959edd4bc31aa97a5d7877edd482ceae/pkg/sql/window.go#L374)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

See my comments below.
</blockquote></details>

Thank you.
___
*[pkg/sql/window.go, line 758 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIjhdS930wVvbW9YcBv:-LIm5eeyBxEjx4Lq7Hv3:b-kufkx2) ([raw file](https://github.com/cockroachdb/cockroach/blob/85ab8bc5959edd4bc31aa97a5d7877edd482ceae/pkg/sql/window.go#L758)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

no it's fine, I misread. 

However to reply to your other question, this is the place where the NULL value should be checked too.
</blockquote></details>

I see, thanks.
___
*[pkg/sql/window.go, line 941 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIiazNaAbbkkQEeiJ7N:-LImEs2k0yuVWNvt80Rj:bgzdldr) ([raw file](https://github.com/cockroachdb/cockroach/blob/85ab8bc5959edd4bc31aa97a5d7877edd482ceae/pkg/sql/window.go#L941)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

the syntax is e.g. ` '-1day' ` (or `interval '-1day'` or `-interval '1 day'`)
</blockquote></details>

Good to know, thanks.
___
*[pkg/sql/sem/tree/type_check.go, line 2102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIm7bW-5Ltko5_i6LPJ:-LIm7bW-5Ltko5_i6LPK:bcp8tt6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f93fec1b280b26d8a42d47805c3a5a7e3ca3549/pkg/sql/sem/tree/type_check.go#L2102)):*
> ```Go
> 			// to a window function that has this window frame. If the ordering is
> 			// on the different column, we'll catch it later.
> 			// TODO(yuzefovich): this behavior, however, might produce different error:
> ```

Is producing a different error OK? How should I handle this case? I guess I could "catch" this error and produce the appropriate.
___
*[pkg/sql/sem/tree/type_check.go, line 2124 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIm3-oh1LP5_A68P0oc:-LIm7Ke25LvytPfywD9R:bcr5s31) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f93fec1b280b26d8a42d47805c3a5a7e3ca3549/pkg/sql/sem/tree/type_check.go#L2124)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Again this is not correct. You can only check for DNull *after* `Eval` has been called (on the result of `Eval`).
</blockquote></details>

Got it, thanks.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28067)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/tree/type_check.go, line 2102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIm7bW-5Ltko5_i6LPJ:-LIqH25w0h5N_CkURLXu:bfxjn02) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f93fec1b280b26d8a42d47805c3a5a7e3ca3549/pkg/sql/sem/tree/type_check.go#L2102)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Is producing a different error OK? How should I handle this case? I guess I could "catch" this error and produce the appropriate.
</blockquote></details>

I realized that ordering doesn't have to be on the column that is the first argument to the window function (as I thought earlier). For example, it makes sense to order rows by date to compute sum of prices. In that case, offset should be an `Interval` (type dependent on the ordering column's type) and not `int` (type dependent on the type of "price" column).

**Comment by yuzefovich** [comment]
@knz @nvanbenschoten I have a couple of PRs dependent on this one, so if you could take another look when you get a chance, I'd really appreciate it.

**Review by knz — APPROVED** [review]
The code looks good but I find the tests a bit "thin". Nathan do you have suggestions?

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-:-LIupDcw5CP-wwUQ8Z0e:bmwyeoc)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by yuzefovich — COMMENTED** [review]
I agree with you about lacking of appropriate test coverage; however, I intend to address it very soon with follow-up PRs.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-:-LIug2gU6HyRWi2yvQQI:b-4wq6fi)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by nvb — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28067)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/window.go, line 681 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIv3JeDDM5nFuASJQaw:-LIv3JeDDM5nFuASJQax:bwqwfoa) ([raw file](https://github.com/cockroachdb/cockroach/blob/7deffdd89b45fe9e3687e4222f371cbaa719a536/pkg/sql/window.go#L681)):*
> ```Go
> 						if types.IsDateTimeType(requiredType) {
> 							// Spec: for datetime ordering columns, the required type is an 'interval'.
> 							requiredType = types.Interval
> ```

I must be missing something. Is `requiredType` used anymore? Do we need this switch-case block at all?
___
*[pkg/sql/sem/tree/type_check.go, line 824 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIibBJ551fiH9XSb9MW:-LIv3chj7jiYf_eIng2O:bth474k) ([raw file](https://github.com/cockroachdb/cockroach/blob/85ab8bc5959edd4bc31aa97a5d7877edd482ceae/pkg/sql/sem/tree/type_check.go#L824)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I extracted this check into a method to avoid to duplication.

I don't think, however, that we can avoid performing this check in two places - we need the check in `type_check.go` for window definitions that follow window functions directly (i.e. `f() OVER (window definition)`), and we need the check in `window.go` for window definitions from `WINDOW` clause.
</blockquote></details>

SGTM. Pulling it into a new method is the right approach then.
___
*[pkg/sql/sem/tree/type_check.go, line 2102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIm7bW-5Ltko5_i6LPJ:-LIv4bfd8GpHPVFD7u7S:b-3556xk) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f93fec1b280b26d8a42d47805c3a5a7e3ca3549/pkg/sql/sem/tree/type_check.go#L2102)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I realized that ordering doesn't have to be on the column that is the first argument to the window function (as I thought earlier). It makes sense to order rows by date to compute sum of prices. In that case, offset should be an `Interval` (type dependent on the ordering column's type) and not `int` (type dependent on the type of "price" column).
</blockquote></details>

What do you mean by a "different error"?
___
*[pkg/sql/sem/tree/type_check.go, line 2083 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIv3k4qEoU30c_xu9gl:-LIv3k4qEoU30c_xu9gm:b-5cpezd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7deffdd89b45fe9e3687e4222f371cbaa719a536/pkg/sql/sem/tree/type_check.go#L2083)):*
> ```Go
> func (stripFuncsVisitor) VisitPost(expr Expr) Expr { return expr }
> 
> // TypeCheck checks that offsets of the window frame (if present) are of the
> ```

nit: move this right below `FuncExpr.TypeCheck`

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28067)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/window.go, line 681 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIv3JeDDM5nFuASJQaw:-LIv8Qzk1BPbxJMBTz1G:b-1sp19i) ([raw file](https://github.com/cockroachdb/cockroach/blob/7deffdd89b45fe9e3687e4222f371cbaa719a536/pkg/sql/window.go#L681)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I must be missing something. Is `requiredType` used anymore? Do we need this switch-case block at all?
</blockquote></details>

Nice catch, thanks! Indeed, we don't need this switch-block at all - all the necessary type checking is done in `type_check.go`.
___
*[pkg/sql/sem/tree/type_check.go, line 2102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIm7bW-5Ltko5_i6LPJ:-LIv6x55AFPXan98HwhU:b-5bcfc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f93fec1b280b26d8a42d47805c3a5a7e3ca3549/pkg/sql/sem/tree/type_check.go#L2102)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What do you mean by a "different error"?
</blockquote></details>

Please ignore this discussion I had with myself.

At first I thought that we need to require offsets to be of the same type as the first argument to window function, and with such interpretation if the ordering was on a column with a different type from first argument's type, we would get an error about incompatible types whereas the appropriate error would be saying that the ordering is on the wrong column. However, as I mentioned in the second comment, my thoughts were wrong at first - we can have ordering on column `a` and perform the window computation over column `b`, and we correctly do type check of offset with column `a`.
___
*[pkg/sql/sem/tree/type_check.go, line 2083 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-LIv3k4qEoU30c_xu9gl:-LIv6uvD9nXIB_N0J25a:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7deffdd89b45fe9e3687e4222f371cbaa719a536/pkg/sql/sem/tree/type_check.go#L2083)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: move this right below `FuncExpr.TypeCheck`
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28067#-:-LIwYCzS5SFREdgQMH4n:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by yuzefovich** [comment]
Thanks for the reviews!

bors r+

**Pull request merged**
