### PR TITLE
obsservice: support embedding in CRDB nodes

### LINKED ISSUE #88194: obsservice: embed in CRDB
For 23.1, we'll optionally embed the Obs Service into CRDB. This is so that other teams have more confidence that the new service will ship in one form or another.

Jira issue: CRDB-19741

Epic CRDB-16791

### PR DESCRIPTION
**Pull request by andreimatei**
This patch adds a special value to the --obsservice-addr CRDB flag:
--obsservice-addr=embed means that an the respective node will run the
Obs Service RPC service internally and the events exporter will be
configured to connect to this internal service.

Release note: None
Fixes #88194 
Epic: CRDB-16791

### CODE REVIEW

**Comment by andreimatei** [comment]
Everything but the last commit is #95702 and #95632.

There's some things to discuss still, like for example the name of the database created for the embedded obs service (or more generally the location of the needed schema). But I think it's ready for a review.

**Review by knz — COMMENTED** [review]
Regarding the 1st commit: you've decided to create 1 different loopback listener per tenant. Is that what you wanted? Why not mirror what is done for the TCP service and use just 1 listener, with tenant routing instead?

(I'll review the other commits in later review rounds)

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-:-NMZbgHR3SIjPnzG9e4V:bhisj74)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @abarganier, @andreimatei, and @dhartunian)

___
*[`-- commits` line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NMZaVED8zkDEd1uYgMT):*
:sparkling_heart: :sparkling_heart: :sparkling_heart: 
___
*[`pkg/server/server.go` line 1904 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NMZakJDDn5p0byX0Npv:-NMZakJDDn5p0byX0Npw:b-ualecg) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf81f46542456fab1200855f3956c4ab90fbfeb7/pkg/server/server.go#L1904)):*
> ```Go
> // internal loopback interface.
> func (s *Server) AcceptInternalClients(ctx context.Context) error {
> 	return s.stopper.RunAsyncTaskEx(ctx,
> ```

I recommend use `netutil.MakeTCPServer` and `ServeWith` here like in `startServeSQL()`.

You might want to rename this to `MakeStreamServer` (since it's not good for just TCP and works for any stream socket) but the logic therein is appropriate as-is for the loopback listener too.
___
*[`pkg/server/tenant.go` line 763 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NMZbTgeAmEBRC15Wo5W:-NMZbTgeAmEBRC15Wo5X:b-eajox2) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf81f46542456fab1200855f3956c4ab90fbfeb7/pkg/server/tenant.go#L763)):*
> ```Go
> 	}
> 
> 	return s.stopper.RunAsyncTaskEx(ctx,
> ```

ditto conn manager.
___
*[`pkg/sql/pgwire/hba_conf.go` line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NMZbZYZ0YVqY-eFil2L:-NMZbZYZ0YVqY-eFil2M:bryeao3) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf81f46542456fab1200855f3956c4ab90fbfeb7/pkg/sql/pgwire/hba_conf.go#L303)):*
> ```Go
> host  all all  all cert-password # built-in CockroachDB default
> local all all      password      # built-in CockroachDB default
> loopback all all all trust       # built-in CockroachDB default
> ```

nit: align these columns.

**Review by knz — COMMENTED** [review]
2nd commit LGTM

3rd commit - no architectural concerns, only a couple of minor points.

> Reviewed 1 of 11 files at r1, 2 of 2 files at r2, 23 of 23 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-:-NMZdoXk8baoZ9wYufcm:b7hx1l8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @abarganier, @andreimatei, and @dhartunian)

___
*[`-- commits` line 48 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NMZcFUrAQp227rncdPH):*
This is incorrect. The epic is CRDB-16791. 
You mean this commit fixes (jira) issue CRDB-23641. You can write "Fixes: CRDB-23641" and "Epic: CRDB-16791".
___
*[`pkg/cli/flags.go` line 545 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NMZcblR7uP8kgfecPdu:-NMZcblR7uP8kgfecPdv:br8ibcs) ([raw file](https://github.com/cockroachdb/cockroach/blob/90a24db04a4361a29b6fd99f95e88ffaec3d102c/pkg/cli/flags.go#L545)):*
> ```Go
> 	for _, cmd := range telemetryEnabledCmds {
> 		f := cmd.Flags()
> 		cliflagcfg.StringFlag(f, &serverCfg.ObsServiceAddr, cliflags.ObsServiceAddr)
> ```

maybe `MarkHidden` here until we know where we're going.
___
*[`pkg/obs/event_exporter.go` line 173 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NMZcu087z_A8bQXvSQ8:-NMZcu087z_A8bQXvSQ9:bovw1op) ([raw file](https://github.com/cockroachdb/cockroach/blob/90a24db04a4361a29b6fd99f95e88ffaec3d102c/pkg/obs/event_exporter.go#L173)):*
> ```Go
> 
> 	// Note that Dial is non-blocking.
> 	conn, err := grpc.Dial(targetAddr, grpc.WithTransportCredentials(insecure.NewCredentials()))
> ```

Please add a TODO here and refer to a (new) issue to implement proper configuration of credentials. 
___
*[`pkg/obs/event_exporter.go` line 228 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NMZd0Lr2hXG9e4oMHIK:-NMZd0Lr2hXG9e4oMHIL:b-u133ba) ([raw file](https://github.com/cockroachdb/cockroach/blob/90a24db04a4361a29b6fd99f95e88ffaec3d102c/pkg/obs/event_exporter.go#L228)):*
> ```Go
> 	}))
> 	ctx, sp := s.tr.StartSpanCtx(ctx, "obsservice flusher", tracing.WithSterile())
> 	go func() {
> ```

Why no stopper.RunAsyncTask here?

**Review by knz — COMMENTED** [review]
last commit: I'd like to revisit the configuration ergonomics, see my comments below.

And then I'd like to raise a higher-level point. This code as-is uses an `obs` database in the system tenant. Is that the best we can do? I'm thinking here this would be a very good use case for using a separate secondary tenant to host just the observability data. WDYT?

> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-:-NMZesME8XTMrg2LVWk1:b8yh1k2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @abarganier, @andreimatei, and @dhartunian)

___
*[`-- commits` line 54 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NMZe0QY5p1Saz-Ws2dm):*
Let's make it a separate boolean flag. You can add a check that the two flags are mutually exclusive for now. This will ensure we're not precluded from having _both_ an embedded service and an exporter running side-by-side in the future.
___
*[`pkg/base/constants.go` line 58 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NMZeAwy9X51pbr-483U:-NMZeAwy9X51pbr-483V:b-q64pkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/304c0f8c02746d40811e1bb757e8a76e2ffadaad/pkg/base/constants.go#L58)):*
> ```Go
> 	// ObsServiceEmbedFlagValue is the special value of the --obsservice-addr flag
> 	// configuring the CRDB node to run the Obs Service internally.
> 	ObsServiceEmbedFlagValue = "embed"
> ```

See above.
___
*[`pkg/cli/cliflags/flags.go` line 1709 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NMZeCdX0lePE8y6etgu:-NMZeCdX0lePE8y6etgv:b-q64pkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/304c0f8c02746d40811e1bb757e8a76e2ffadaad/pkg/cli/cliflags/flags.go#L1709)):*
> ```Go
> 		Description: `Address of an OpenTelemetry OTLP sink such as the
> Observability Service or the OpenTelemetry Collector. If set, telemetry
> events are exported to this address. The special value "embed" causes
> ```

See above.
___
*[`pkg/obs/event_exporter.go` line 130 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NMZeLiz1PjKrJ9acfuO:-NMZeLiz1PjKrJ9acfuP:bmndivh) ([raw file](https://github.com/cockroachdb/cockroach/blob/304c0f8c02746d40811e1bb757e8a76e2ffadaad/pkg/obs/event_exporter.go#L130)):*
> ```Go
> // missing port with the default.
> func ValidateOTLPTargetAddr(targetAddr string) (string, error) {
> 	otlpHost, otlpPort, err := net.SplitHostPort(targetAddr)
> ```

Here and in previous commits: use `addrutil.SplitHostPort`. The go version is broken for ipv6.
___
*[`pkg/server/initial_sql.go` line 40 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NMZeZN83FyFNUMUQQ92:-NMZeZN83FyFNUMUQQ93:bj8kn03) ([raw file](https://github.com/cockroachdb/cockroach/blob/304c0f8c02746d40811e1bb757e8a76e2ffadaad/pkg/server/initial_sql.go#L40)):*
> ```Go
> 	ctx context.Context, startSingleNode bool, adminUser, adminPassword string,
> ) error {
> 	if s.cfg.ObsServiceAddr == base.ObsServiceEmbedFlagValue {
> ```

See comment at top.
___
*[`pkg/server/server.go` line 874 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NMZel-31NN2S65CQc18:-NMZel-409OTvr80yn8I:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/304c0f8c02746d40811e1bb757e8a76e2ffadaad/pkg/server/server.go#L874)):*
> ```Go
> 	var eventsExporter obs.EventsExporterInterface
> 	if cfg.ObsServiceAddr != "" {
> 		if cfg.ObsServiceAddr == base.ObsServiceEmbedFlagValue {
> ```

ditto
___
*[`pkg/server/server.go` line 1831 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NMZem5KB1EtiWCBNUXo:-NMZem5KB1EtiWCBNUXp:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/304c0f8c02746d40811e1bb757e8a76e2ffadaad/pkg/server/server.go#L1831)):*
> ```Go
> 		BinaryVersion: build.BinaryVersion(),
> 	})
> 	if s.cfg.ObsServiceAddr != base.ObsServiceEmbedFlagValue {
> ```

ditto
___
*[`pkg/server/tenant.go` line 1020 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NMZeo6K7I479ikD10p6:-NMZeo6K7I479ikD10p7:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/304c0f8c02746d40811e1bb757e8a76e2ffadaad/pkg/server/tenant.go#L1020)):*
> ```Go
> 	var eventsExporter obs.EventsExporterInterface
> 	if baseCfg.ObsServiceAddr != "" {
> 		if baseCfg.ObsServiceAddr == base.ObsServiceEmbedFlagValue {
> ```

ditto

**Review by andreimatei — COMMENTED** [review]
> Everything but the last commit is #95702 and #95632.

Let's please continue on these PRs.

> And then I'd like to raise a higher-level point. This code as-is uses an obs database in the system tenant. Is that the best we can do? I'm thinking here this would be a very good use case for using a separate secondary tenant to host just the observability data. WDYT?

Seems complicated to deal with creating a tenant, particularly in a cluster that otherwise doesn't have tenants. What would be the benefit?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-:-NN9RpKvCPoNgDG_D4sK:b-fgepxg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @abarganier, @dhartunian, and @knz)

___
*[`-- commits` line 48 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NMZcFUrAQp227rncdPH):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

This is incorrect. The epic is CRDB-16791. 
You mean this commit fixes (jira) issue CRDB-23641. You can write "Fixes: CRDB-23641" and "Epic: CRDB-16791".
</blockquote></details>

done in #95632
___
*[`-- commits` line 54 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NMZe0QY5p1Saz-Ws2dm):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Let's make it a separate boolean flag. You can add a check that the two flags are mutually exclusive for now. This will ensure we're not precluded from having _both_ an embedded service and an exporter running side-by-side in the future.
</blockquote></details>

I'd rather keep a single flag. If we'll want to support both an embedded one and an external one (or, at that point, any number of targets), we can make the flag accept a list of addresses.
No?
___
*[`pkg/cli/flags.go` line 545 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NMZcblR7uP8kgfecPdu:-NN8oB4x7yNcDSTpjXmC:b3p6c7m) ([raw file](https://github.com/cockroachdb/cockroach/blob/90a24db04a4361a29b6fd99f95e88ffaec3d102c/pkg/cli/flags.go#L545)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

maybe `MarkHidden` here until we know where we're going.
</blockquote></details>

done in #95632
___
*[`pkg/obs/event_exporter.go` line 173 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NMZcu087z_A8bQXvSQ8:-NN8zkq5-FLOlnxVW8Ko:bkqolvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/90a24db04a4361a29b6fd99f95e88ffaec3d102c/pkg/obs/event_exporter.go#L173)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Please add a TODO here and refer to a (new) issue to implement proper configuration of credentials. 
</blockquote></details>

done in #95632
___
*[`pkg/obs/event_exporter.go` line 228 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NMZd0Lr2hXG9e4oMHIK:-NN8vFjwA3rmzzEKpHLc:b-gt9hl4) ([raw file](https://github.com/cockroachdb/cockroach/blob/90a24db04a4361a29b6fd99f95e88ffaec3d102c/pkg/obs/event_exporter.go#L228)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Why no stopper.RunAsyncTask here?
</blockquote></details>

because I want this to run as long as possible (or at least as long as can be done easily), to flush shutdown events too. That's why I hook it up as a closer, above.
___
*[`pkg/obs/event_exporter.go` line 130 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NMZeLiz1PjKrJ9acfuO:-NN9LtE81Mk1nVenCYLl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/304c0f8c02746d40811e1bb757e8a76e2ffadaad/pkg/obs/event_exporter.go#L130)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Here and in previous commits: use `addrutil.SplitHostPort`. The go version is broken for ipv6.
</blockquote></details>

Done.
___
*[`pkg/server/initial_sql.go` line 40 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NMZeZN83FyFNUMUQQ92:-NN9LvMd2lTvu3xztxc7:bmtch0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/304c0f8c02746d40811e1bb757e8a76e2ffadaad/pkg/server/initial_sql.go#L40)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

See comment at top.
</blockquote></details>

if there's a suggestion which would cause 5 other things to necessarily change, I don't think you need to comment on all of them :P
___
*[`pkg/server/server.go` line 1904 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NMZakJDDn5p0byX0Npv:-NN9MOcF0o7x9OJGK7o8:b-ga3d6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf81f46542456fab1200855f3956c4ab90fbfeb7/pkg/server/server.go#L1904)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I recommend use `netutil.MakeTCPServer` and `ServeWith` here like in `startServeSQL()`.

You might want to rename this to `MakeStreamServer` (since it's not good for just TCP and works for any stream socket) but the logic therein is appropriate as-is for the loopback listener too.
</blockquote></details>

I had looked at those, but they have extraneous code that I don't want. `MakeTCPServer` integrates with the stopper and does something on quiescence which I don't want (*). `ServeWith` deals with some temporary errors from `Accept` that I don't understand (that code was introduced at the same time with `cmux` so maybe it has something to do with that?), but doesn't apply here and I'd rather not have it.
So I don't see what those provide that I want.

(*) In fact I'm not all that sure that what it does is kosher - it closes the active connections when the stopper quiesces, but that close races with the goroutine that deals with that connection. I don't see what makes racing closers OK.
___
*[`pkg/sql/pgwire/hba_conf.go` line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NMZbZYZ0YVqY-eFil2L:-NN9RLsg8FTgV3WHnAv-:bx9ft6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf81f46542456fab1200855f3956c4ab90fbfeb7/pkg/sql/pgwire/hba_conf.go#L303)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: align these columns.
</blockquote></details>

let's take this to #95702 - but I've been meaning to ask you if you think that adding this rule here and then also validating that such a rule exists is the right thing to do, as opposed to not surfacing rules that talk about `loopback` to users, and adding the rule by fiat to whatever config the user provides (or otherwise exempt `loopback` conns from hba through dedicated code).

**Review by knz — COMMENTED** [review]
> Let's please continue on these PRs.

That works :+1: 

> >  And then I'd like to raise a higher-level point. This code as-is uses an obs database in the system tenant. Is that the best we can do? I'm thinking here this would be a very good use case for using a separate secondary tenant to host just the observability data. WDYT?
> 
> Seems complicated to deal with creating a tenant, particularly in a cluster that otherwise doesn't have tenants. What would be the benefit?

The benefit is twofold.
- to not pollute the database namespace.
  1. the name you've chosen is generic and likely to conflict with other legit db names.
  2. users will ask questions. With a separate tenant, they would not see it at all unless they learn to care about it.
- using a different tenant will also enable the obs service to evolve its system schema separately from the main customer's application (each tenant runs its version upgrades independently from others)

> Reviewed 4 of 23 files at r7, 2 of 9 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-:-NNCgPICBVtgF2HukKSD:bvwffxg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @abarganier, @andreimatei, and @dhartunian)

___
*[`-- commits` line 54 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NMZe0QY5p1Saz-Ws2dm):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'd rather keep a single flag. If we'll want to support both an embedded one and an external one (or, at that point, any number of targets), we can make the flag accept a list of addresses.
No?
</blockquote></details>

"embed" is a valid address. So would pretty much any string. Please, don't don't confuse _types_ with  _values_ in the UX.
___
*[`pkg/obs/event_exporter.go` line 228 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NMZd0Lr2hXG9e4oMHIK:-NNChlkxDKIuhmiz1a9F:b965bk8) ([raw file](https://github.com/cockroachdb/cockroach/blob/90a24db04a4361a29b6fd99f95e88ffaec3d102c/pkg/obs/event_exporter.go#L228)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

because I want this to run as long as possible (or at least as long as can be done easily), to flush shutdown events too. That's why I hook it up as a closer, above.
</blockquote></details>

Discussion moved to the other PR.
___
*[`pkg/server/initial_sql.go` line 40 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NMZeZN83FyFNUMUQQ92:-NNChpR46UTKqp8xfG0T:b-8ujlda) ([raw file](https://github.com/cockroachdb/cockroach/blob/304c0f8c02746d40811e1bb757e8a76e2ffadaad/pkg/server/initial_sql.go#L40)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

if there's a suggestion which would cause 5 other things to necessarily change, I don't think you need to comment on all of them :P
</blockquote></details>

I do this as a reviewer so I can quickly seek back to my comments later to see how they have been addressed. Feel free to ignore the duplicates on your side.
___
*[`pkg/server/server.go` line 1904 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NMZakJDDn5p0byX0Npv:-NNChxNA8pWQnQpz9_go:b965bk8) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf81f46542456fab1200855f3956c4ab90fbfeb7/pkg/server/server.go#L1904)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I had looked at those, but they have extraneous code that I don't want. `MakeTCPServer` integrates with the stopper and does something on quiescence which I don't want (*). `ServeWith` deals with some temporary errors from `Accept` that I don't understand (that code was introduced at the same time with `cmux` so maybe it has something to do with that?), but doesn't apply here and I'd rather not have it.
So I don't see what those provide that I want.

(*) In fact I'm not all that sure that what it does is kosher - it closes the active connections when the stopper quiesces, but that close races with the goroutine that deals with that connection. I don't see what makes racing closers OK.
</blockquote></details>

Discussion moved to the other PR.
___
*[`pkg/sql/pgwire/hba_conf.go` line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NMZbZYZ0YVqY-eFil2L:-NNCi-J86N4j24it1PKE:b-pa019u) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf81f46542456fab1200855f3956c4ab90fbfeb7/pkg/sql/pgwire/hba_conf.go#L303)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

let's take this to #95702 - but I've been meaning to ask you if you think that adding this rule here and then also validating that such a rule exists is the right thing to do, as opposed to not surfacing rules that talk about `loopback` to users, and adding the rule by fiat to whatever config the user provides (or otherwise exempt `loopback` conns from hba through dedicated code).
</blockquote></details>

I am friendly to the idea. But discussion moved to the other PR.

**Review by andreimatei — COMMENTED** [review]
> to not pollute the database namespace.
> users will ask questions. With a separate tenant, they would not see it at all unless they learn to care about it.

I think it's the other way around - a tenant is more invasive and more presumably visible in the cluster than one more database - particularly when going from 1 tenant to 2. As far as questions are concerned, I think a new tenant move would probably generate a lot more.

> the name you've chosen is generic and likely to conflict with other legit db names.

Yeah, sorry, I didn't actually mean for `obs` to stay as the name. Replaced by `crdb_observability`.
I've also considered making it a schema in the `system` database, but I was dissuaded from that.

> using a different tenant will also enable the obs service to evolve its system schema separately from the main customer's application (each tenant runs its version upgrades independently from others)

When the obs service is embedded in crdb, we want to evolve its schema on crdb upgrades. So the schema will evolve independently of the application, tenant or no tenant. So I don't see this point very clearly; perhaps you can say more.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-:-NNch11sDdXplV8DfKhR:b-u2hkhh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @abarganier, @dhartunian, and @knz)

___
*[`-- commits` line 54 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NMZe0QY5p1Saz-Ws2dm):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

"embed" is a valid address. So would pretty much any string. Please, don't don't confuse _types_ with  _values_ in the UX.
</blockquote></details>

If someone really has a machine called `embed`, they can reference it with the port number, as `embed:4318`.
I think corner cases like this are worth it in order to keep the number of flags down.

**Review by dhartunian — COMMENTED** [review]
I don't have a strong feeling about the tenancy question. I do think if the customer can see and manipulate the `crdb_observability` database, then we should perhaps be resilient against its truncation/dropping.

> Reviewed 4 of 12 files at r12, 35 of 35 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-:-NNiUeIg0cVPuS34AqGW:bes67q8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @abarganier, @andreimatei, and @knz)

___
*[`pkg/server/initial_sql.go` line 42 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NNiPwtT3135mOeEgQfi:-NNiPwtT3135mOeEgQfj:b-vyr732) ([raw file](https://github.com/cockroachdb/cockroach/blob/07471b0c917a85c22ab21bbe1c573823cbaccf86/pkg/server/initial_sql.go#L42)):*
> ```Go
> ) error {
> 	if s.cfg.ObsServiceAddr == base.ObsServiceEmbedFlagValue {
> 		if err := s.startEmbeddedObsService(ctx); err != nil {
> ```

why is this included in `RunInitialSQL` and in `server.Start`? can we just put it in one place?
___
*[`pkg/server/initial_sql.go` line 77 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NNiS1O--CjyAgWo0IYy:-NNiS1O--CjyAgWo0IYz:bd81ljr) ([raw file](https://github.com/cockroachdb/cockroach/blob/07471b0c917a85c22ab21bbe1c573823cbaccf86/pkg/server/initial_sql.go#L77)):*
> ```Go
> // it doesn't exist already), starts the internal RPC service for event
> // ingestion and hooks up the event exporter to talk to the local service.
> func (s *Server) startEmbeddedObsService(ctx context.Context) error {
> ```

regardless of comment above, can we keep obsservice stuff in its own files? I know this has to stay in `server` package, but I think mixing with internal CRDB stuff like this gets confusing especially since it has lines like `migrations.RunDBMigrations` which could confuse ppl.

**Review by andreimatei — COMMENTED** [review]
> I do think if the customer can see and manipulate the crdb_observability database, then we should perhaps be resilient against its truncation/dropping.

If someone messes with this database, event exporting might not work any more, but otherwise I think the effects are pretty contained - creating new events won't crash or anyhing.
If the database is dropped, restarting a node will recreate it. Beyond that, we could perhaps provide a command of some sort to recreate it at runtime; I'll ruminate but I think it can come later.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-:-NNiY10R88vQDTJtSXL9:b6abcix)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @abarganier, @dhartunian, and @knz)

___
*[`pkg/server/initial_sql.go` line 42 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NNiPwtT3135mOeEgQfi:-NNiWYkq0-6XOH--7dME:b-mov722) ([raw file](https://github.com/cockroachdb/cockroach/blob/07471b0c917a85c22ab21bbe1c573823cbaccf86/pkg/server/initial_sql.go#L42)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

why is this included in `RunInitialSQL` and in `server.Start`? can we just put it in one place?
</blockquote></details>

yeah...
It's because `server.Start` only runs for `TestServer`; the CLI doesn't run it.
I got rid of this `Start` cause it was confusing, and inlined it in `TestServer`, and have that call `RunInitialSQL`.
___
*[`pkg/server/initial_sql.go` line 77 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NNiS1O--CjyAgWo0IYy:-NNiXujaBK-d-fW0mr85:bnam5c0) ([raw file](https://github.com/cockroachdb/cockroach/blob/07471b0c917a85c22ab21bbe1c573823cbaccf86/pkg/server/initial_sql.go#L77)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

regardless of comment above, can we keep obsservice stuff in its own files? I know this has to stay in `server` package, but I think mixing with internal CRDB stuff like this gets confusing especially since it has lines like `migrations.RunDBMigrations` which could confuse ppl.
</blockquote></details>

moved to dedicated file

**Review by dhartunian — APPROVED** [review]
> If the database is dropped, restarting a node will recreate it. Beyond that, we could perhaps provide a command of some sort to recreate it at runtime; I'll ruminate but I think it can come later.

agreed.


:lgtm:

> Reviewed 1 of 12 files at r12, 4 of 5 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-:-NNiiUx5EG9XDQwrlSVI:b-lqm5qd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi, @abarganier, @andreimatei, and @knz)

___
*[`pkg/server/initial_sql.go` line 42 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-NNiPwtT3135mOeEgQfi:-NNmUVBe6NfYVjvQLC61:b-83sjo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/07471b0c917a85c22ab21bbe1c573823cbaccf86/pkg/server/initial_sql.go#L42)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

yeah...
It's because `server.Start` only runs for `TestServer`; the CLI doesn't run it.
I got rid of this `Start` cause it was confusing, and inlined it in `TestServer`, and have that call `RunInitialSQL`.

</blockquote></details>

Nice.

**Comment by andreimatei** [comment]
Rafa, I'm merging to have a foot in the door, but we can continue our discussions at length in the snow.
TFTR!

bors r+

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95703#-:-NOu4f5D3Ak6_PpmbHo9:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aadityasondhi, @abarganier, @dhartunian, and @knz)

**Pull request merged**
