### PR TITLE
sql: avoid running lint tests under race/deadlock/stress

### PR DESCRIPTION
**Pull request by knz**
Release justification: changes to test-only code

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
@erikgrinaker  sorry for getting you as reviewer. I had wanted someone from test engineering, but apparently the github "cockroachdb/test-eng" team assignment is stale.

cc @srosenberg

**Review by erikgrinaker — APPROVED** [review]
No worries, happy to stamp this.

**Comment by knz** [comment]
thx!

bors r=erikgrinaker

**Review by srosenberg — APPROVED** [review]

**Comment by srosenberg** [comment]
> I had wanted someone from test engineering, but apparently the github "cockroachdb/test-eng" team assignment is stale.
> 

Thanks for the head-up; looks like someone else already updated the team members, so it's now up to date.

**Pull request merged**
