### PR TITLE
roachtest: make roachtest aware of 20.1 and the 20.2 tag

### PR DESCRIPTION
**Pull request by knz**
First commit from #48788

### CODE REVIEW

**Review by tbg — APPROVED** [review]
:lgtm: just merge this whole PR without waiting for mine (which we'll just close).

> Reviewed 7 of 7 files at r1, 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48789#-:-M7D9NPE0V9ATFfyP9Y5:b4rw234)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by knz** [comment]
i'll wait for CI first though

**Comment by knz** [comment]
rebased

**Comment by knz** [comment]
ok that passed

bors r=tbg

**Pull request merged**
