### PR TITLE
storage: don't repropose RequestLeaseRequests

### LINKED ISSUE #12446: storage: replica {3 3 3} not lease holder; current lease is repl={3 3 3}
The above error was seen while debugging flakiness in `TestRefreshPendingCommands`:

```
~ make stress PKG=./storage TESTS=TestRefreshPendingCommands STRESSFLAGS="-maxfails 1 -stderr -p 100" TESTTIMEOUT=1m TESTFLAGS='--vmodule=replica=4'
...
    --- FAIL: TestRefreshPendingCommands/#00 (1.56s)
    	client_raft_test.go:1001: range 1: replica {3 3 3} not lease holder; current lease is repl={3 3 3} start=0.900000123,17 exp=4.500000127,29 pro=3.600000127,30
FAIL


ERROR: exit status 1

841 runs completed, 1 failures, over 11s
FAIL
```

The logs show:

`I161216 15:27:02.500412 433 storage/replica.go:3305  [s1,r1/1:/M{in-ax},@c42038a480] command RequestLease [/Min,/Min) proposed from replica {NodeID:3 StoreID:3 ReplicaID:3}: leases repl={1 1 1} start=0.000000000,0 exp=4.500000127,29 and repl={3 3 3} start=0.900000123,17 exp=4.500000127,29 are not equivalent`

I'm not terribly familiar with this lease invariant code but something funky seems to be going on. Here is the [full output](https://github.com/cockroachdb/cockroach/files/657589/out.txt) from the test.

### LINKED ISSUE #12449: storage: fix confusing not lease holder error
Forked from #12446. From the code:

```
	} else if err := verifyLease(); err != nil {
		log.VEventf(
			ctx, 1,
			"command %s proposed from replica %+v: %s",
			raftCmd.BatchRequest, raftCmd.OriginReplica, err,
		)
		// TODO(spencer,andrei): This error is confusing if r.mu.state.Lease is
		// held by raftCmd.OriginReplica.StoreID, but verifyLease failed because
		// raftCmd.OriginLease was not equivalent. In that scenario you get an
		// error which makes you question your sanity:
		//
		//   replica {3 3 3} not lease holder; current lease is repl={3 3 3} ...
		forcedErr = roachpb.NewError(newNotLeaseHolderError(
			r.mu.state.Lease, raftCmd.OriginReplica.StoreID, r.mu.state.Desc))
	} else if isLeaseRequest {
```

### PR DESCRIPTION
**Pull request by andreimatei**
As detailed in #12446, a reproposed RequestLease request is rejected at
processing time because the lease under which it was proposed is no
longer the current lease (the current lease is the lease the request is
trying to institute, and it succeeded in doing so).
The patch makes redirectOnOrAcquire() aware of this possibility.

Fixes #12446
Fixes #12449 

cc @petermattis

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12542)

### CODE REVIEW

**Comment by andreimatei** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/kv/dist_sender.go, line 1279 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542#-KZYobHTx-LXsV4S5UvN:-KZYobHUuEhzajkRcWIi:bod05ex) ([raw file](https://github.com/cockroachdb/cockroach/blob/24fb0d119ac048e63daa15c4bab9e0081fe31f30/pkg/kv/dist_sender.go#L1279)):*
> ```Go
> 		}
> 		return true
> 	case *roachpb.StaleProposalError:
> ```

I've added this handling of `StaleProposalError` here to keep the spirit of the existing code (which was handling `NotLeastHolderError`), but I'm not entirely confident in it.
First question I have is whether it's true that one `BatchRequest` sent by the `DistSender` to a single replica will be turned into a single raft command. If that doesn't hold, I don't think can't blindly retry on these errors.

Then the other question is whether this code is necessary at all. I'm not entirely sure what commands can fail the `originLease` check in `processRaftCommand()`. I guess I don't understand how reproposals work well enough; I'm confused about whether `redirectOnOrAcquireLease` should have received an `AmbiguousCommitError` for the reproposal scenario from https://github.com/cockroachdb/cockroach/issues/12446#issuecomment-267680420.

And finally, if these retries are needed and OK, the final question is whether we should be doing them at a different level - for example in `replica.Send()` or `replica.addWriteCmd()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542)*

**Comment by tamird** [comment]
Reviewed 10 of 11 files at r1.
Review status: 10 of 11 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/kv/dist_sender.go, line 1279 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542#-KZYobHTx-LXsV4S5UvN:-KZZEkgXa_4nLDts4LqH:b6p6jm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/24fb0d119ac048e63daa15c4bab9e0081fe31f30/pkg/kv/dist_sender.go#L1279)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I've added this handling of `StaleProposalError` here to keep the spirit of the existing code (which was handling `NotLeastHolderError`), but I'm not entirely confident in it.
First question I have is whether it's true that one `BatchRequest` sent by the `DistSender` to a single replica will be turned into a single raft command. If that doesn't hold, I don't think can't blindly retry on these errors.

Then the other question is whether this code is necessary at all. I'm not entirely sure what commands can fail the `originLease` check in `processRaftCommand()`. I guess I don't understand how reproposals work well enough; I'm confused about whether `redirectOnOrAcquireLease` should have received an `AmbiguousCommitError` for the reproposal scenario from https://github.com/cockroachdb/cockroach/issues/12446#issuecomment-267680420.

And finally, if these retries are needed and OK, the final question is whether we should be doing them at a different level - for example in `replica.Send()` or `replica.addWriteCmd()`.
</blockquote></details>

This solution seems particularly unsatisfying - can't it lead to infinite reproposal loops? I was imagining that the solution here would make lease requests idempotent.

---

*[pkg/roachpb/errors.go, line 277 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542#-KZZCyXOktFC9NHm64IS:-KZZCyXOktFC9NHm64IT:b-o0soua) ([raw file](https://github.com/cockroachdb/cockroach/blob/24fb0d119ac048e63daa15c4bab9e0081fe31f30/pkg/roachpb/errors.go#L277)):*
> ```Go
> func (e *StaleProposalError) message(_ *Error) string {
> 	return fmt.Sprintf("cannot process command because the current lease is different "+
> 		"than the lease under which it was proposed. OriginLease: %s. current lease: %s",
> ```

same comment as the one i left on the proto - it's not that it's a different lease, it's the lease under which the command was proposed is not in effect during its application

---

*[pkg/roachpb/errors.proto, line 48 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542#-KZZCA3ZGt19enaA0nb6:-KZZCA3ZGt19enaA0nb7:buxf8hm) ([raw file](https://github.com/cockroachdb/cockroach/blob/24fb0d119ac048e63daa15c4bab9e0081fe31f30/pkg/roachpb/errors.proto#L48)):*
> ```protobuf
> }
> 
> // A StaleProposalError indicated that a Raft command cannot be applied because
> ```

s/indicated/indicates/

---

*[pkg/roachpb/errors.proto, line 49 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542#-KZZCBP34s1d8rmc9o_j:-KZZCBP34s1d8rmc9o_k:b-krtrde) ([raw file](https://github.com/cockroachdb/cockroach/blob/24fb0d119ac048e63daa15c4bab9e0081fe31f30/pkg/roachpb/errors.proto#L49)):*
> ```protobuf
> 
> // A StaleProposalError indicated that a Raft command cannot be applied because
> // the lease under which it was proposed is different than the current lease at
> ```

s/is different than the current lease at command application time/is not in effect during the command's application/

---

*[pkg/roachpb/errors.proto, line 51 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542#-KZZCJaq_F_7xJfUtS_8:-KZZCJaq_F_7xJfUtS_9:b-qd0bff) ([raw file](https://github.com/cockroachdb/cockroach/blob/24fb0d119ac048e63daa15c4bab9e0081fe31f30/pkg/roachpb/errors.proto#L51)):*
> ```protobuf
> // the lease under which it was proposed is different than the current lease at
> // command application time. See comments on RaftCommand.origin_lease.
> // These errors are generally retried at the DistSender level; it's OK to
> ```

s/ level//

---

*[pkg/storage/client_test.go, line 430 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542#-KZZCjeyfwJKpNHBwloj:-KZZCjeyfwJKpNHBwlok:bkj9b3l) ([raw file](https://github.com/cockroachdb/cockroach/blob/24fb0d119ac048e63daa15c4bab9e0081fe31f30/pkg/storage/client_test.go#L430)):*
> ```Go
> 
> func (t *multiTestContextKVTransport) String() string {
> 	return fmt.Sprintf("multiTestContextKVTransport: replicas: %v. Next index: %d",
> ```

unusual formatting =/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542)*

**Comment by bdarnell** [comment]
Reviewed 9 of 11 files at r1.
Review status: 10 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/kv/dist_sender.go, line 1279 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542#-KZYobHTx-LXsV4S5UvN:-KZZx5CXLCzGH8ziA5TB:bcunp5q) ([raw file](https://github.com/cockroachdb/cockroach/blob/24fb0d119ac048e63daa15c4bab9e0081fe31f30/pkg/kv/dist_sender.go#L1279)):*
> First question I have is whether it's true that one BatchRequest sent by the DistSender to a single replica will be turned into a single raft command. If that doesn't hold, I don't think can't blindly retry on these errors.

At this level, yes. 

> I'm not entirely sure what commands can fail the originLease check in processRaftCommand().

All commands go through this check and could fail there.

> Then the other question is whether this code is necessary at all. 

If the replicas in the two leases are different, then the retry must occur in the DistSender (and I'd prefer to do that with the existing NotLeaseHolderError instead of introducing a new error type). Retrying at the Replica (or Store) could be an optimization for cases where there is a new incarnation of the same lease, but I don't think that's a common enough case to be worth bothering with.

Note that RequestLease proposals don't go through DistSender at all, so they will have to be retried (or not) on a completely separate code path anyway). 

> I'm confused about whether redirectOnOrAcquireLease should have received an AmbiguousCommitError for the reproposal scenario from #12446 (comment).

Yes, I think so. There is probably some sort of gap in the ambiguousResult detection that comes from the fact that RequestLease is the only thing that can be proposed without holding the lease.  As an alternative to finding and fixing this gap we could probably remove reproposals entirely for RequestLease.

> can't it lead to infinite reproposal loops?

I don't see why this would be any more prone to looping than what we already have. 

---

*[pkg/storage/replica.go, line 3353 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542#-KZ_2vlY0Mi3R7E_IOeZ:-KZ_2vlY0Mi3R7E_IOe_:b6hn356) ([raw file](https://github.com/cockroachdb/cockroach/blob/24fb0d119ac048e63daa15c4bab9e0081fe31f30/pkg/storage/replica.go#L3353)):*
> ```Go
> 			raftCmd.BatchRequest, raftCmd.OriginReplica, err,
> 		)
> 		forcedErr = roachpb.NewError(roachpb.NewStaleProposalError(
> ```

I think what I'd like to do here is make the error type conditional on `isLeaseRequest`: for normal requests, return NotLeaseHolderError and the DistSender will do the right thing (but we need to clean up `NotLeaseHolderError` to return a sensible description of the situation). For lease requests (which don't go through the DistSender and don't know about NotLeaseHolderError), we return LeaseRejectedError (which they do know how to handle)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542)*

**Comment by andreimatei** [comment]
Review status: 10 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/kv/dist_sender.go, line 1279 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542#-KZYobHTx-LXsV4S5UvN:-KZbpD9JDNuzV_hyJFVJ:bx3we3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/24fb0d119ac048e63daa15c4bab9e0081fe31f30/pkg/kv/dist_sender.go#L1279)):*
> > I'm not entirely sure what commands can fail the originLease check in processRaftCommand().
> 
> All commands go through this check and could fail there.

Sure, they go through that check, but can they fail it in the absence of a reproposal? In the reproposal case, we want an `AmbiguousCommitError` to be propagated to the command proposer and then to the `DistSender`, don't we?

`RequestLease`, as you say, is special, and the code for handling its `StaleProposalError` is in `redirectOnOrAcquire`.

> > I'm confused about whether redirectOnOrAcquireLease should have received an AmbiguousCommitError for the reproposal scenario from #12446 (comment).
>
> Yes, I think so. There is probably some sort of gap in the ambiguousResult detection that comes from the fact that RequestLease is the only thing that can be proposed without holding the lease. As an alternative to finding and fixing this gap we could probably remove reproposals entirely for RequestLease.

I guess the gap is that we don't assign a `MaxLeaseIndex` to `RequestLease` commands, so they're always "reproposed" by `refreshProposalLocked()`, not "retried". Which means that the proposer get the raw error, not `AmbiguousCommitError`.
I'm fine with not reproposing `RequestLease`. Do you suppose that `refreshPendingCommandsLocked()` should directly return an `AmbiguousResultError` to `addWriteCommand()`, and have `redirectOnOrAcquireLease()` loop on this error?

---

*[pkg/storage/replica.go, line 3353 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542#-KZ_2vlY0Mi3R7E_IOeZ:-KZboQTwYaLX2_CwWkHv:b-mg5xoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/24fb0d119ac048e63daa15c4bab9e0081fe31f30/pkg/storage/replica.go#L3353)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I think what I'd like to do here is make the error type conditional on `isLeaseRequest`: for normal requests, return NotLeaseHolderError and the DistSender will do the right thing (but we need to clean up `NotLeaseHolderError` to return a sensible description of the situation). For lease requests (which don't go through the DistSender and don't know about NotLeaseHolderError), we return LeaseRejectedError (which they do know how to handle)
</blockquote></details>

I'd rather we not use `NotLeaseHolderError` in this case, and keep that to be used only as a routing error. This case is quite different from a `replica.Send()` wanting to redirect a command. Even though at the `DistSender` level we want to handle them the same (which I'm actually not sure of, see discussion there). 
Also `LeaseRejectedError` is currently different - it's an evaluation error.
No?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542)*

**Comment by bdarnell** [comment]
Reviewed 1 of 11 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/kv/dist_sender.go, line 1279 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542#-KZYobHTx-LXsV4S5UvN:-KZeEae88BKP3DHdEtMR:bbjs4ev) ([raw file](https://github.com/cockroachdb/cockroach/blob/24fb0d119ac048e63daa15c4bab9e0081fe31f30/pkg/kv/dist_sender.go#L1279)):*
> Sure, they go through that check, but can they fail it in the absence of a reproposal?

Yes, this is where NotLeaseHolderErrors come from if the node lost its lease in between proposing the command and it getting applied. 

> In the reproposal case, we want an AmbiguousCommitError to be propagated to the command proposer and then to the DistSender, don't we?

If it was just reproposed and not reevaluated, then it's not ambiguous and we can return the original NotLeaseHolderError.

> I guess the gap is that we don't assign a MaxLeaseIndex to RequestLease commands, so they're always "reproposed" by refreshProposalLocked(), not "retried". Which means that the proposer get the raw error, not AmbiguousCommitError.

Ah, right. Reproposals cannot be ambiguous for a command with a MaxLeaseIndex, but they are here. So yes, I think refreshProposalsLocked should probably return an AmbiguousResultError for commands without a MaxLeaseIndex. 

---

*[pkg/storage/replica.go, line 3353 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542#-KZ_2vlY0Mi3R7E_IOeZ:-KZeKplC8uGJtGcjY6pa:bmucshd) ([raw file](https://github.com/cockroachdb/cockroach/blob/24fb0d119ac048e63daa15c4bab9e0081fe31f30/pkg/storage/replica.go#L3353)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'd rather we not use `NotLeaseHolderError` in this case, and keep that to be used only as a routing error. This case is quite different from a `replica.Send()` wanting to redirect a command. Even though at the `DistSender` level we want to handle them the same (which I'm actually not sure of, see discussion there). 
Also `LeaseRejectedError` is currently different - it's an evaluation error.
No?
</blockquote></details>

If this error makes it to DistSender (without being transformed into an AmbiguousResultError in addWriteCmd), then I think we do want to handle it the same as NotLeaseHolderError. 

And LeaseRejectedError is currently generated at evaluation time, but I don't see why that matters - again, the handling for it would be the same, and we don't generally distinguish between evaluation time and application time. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542)*

**Comment by tamird** [comment]
Reviewed 6 of 7 files at r2.
Review status: 8 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/roachpb/errors.proto, line 48 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542#-K_1PcRzHC2tzeenNo1p:-K_1PcRzHC2tzeenNo1q:b-q8hhs0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1c2b48c41f7834379b112835f4b1ed19fb5edbe/pkg/roachpb/errors.proto#L48)):*
> ```protobuf
>   // If set, the Error() method will return this instead of composing its
>   // regular spiel. Useful because we reuse this error when rejecting a command
>   // because the lease under which it applies is different than the lease under
> ```

"applies", "was proposed" these are different tenses. "under which its application was attempted", perhaps?

---

*[pkg/storage/client_test.go, line 430 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542#-KZZCjeyfwJKpNHBwloj:-K_1PwslSFl2RjeV18jp:bm9xqym) ([raw file](https://github.com/cockroachdb/cockroach/blob/24fb0d119ac048e63daa15c4bab9e0081fe31f30/pkg/storage/client_test.go#L430)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

how would you improve it?
</blockquote></details>

`return fmt.Sprintf("%T: replicas=%v, idx=%d", t, t.replicas, t.idx)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542)*

**Comment by petermattis** [comment]
Review status: 8 of 9 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica.go, line 3304 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542#-K_UhBytMlYTMQ8SUm2z:-K_UhBytMlYTMQ8SUm3-:bfu3q80) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1c2b48c41f7834379b112835f4b1ed19fb5edbe/pkg/storage/replica.go#L3304)):*
> ```Go
> 		if isLeaseRequest {
> 			if raftCmd.ReplicatedEvalResult.State.Lease == nil {
> 				panic("isLeaseRequest but no lease")
> ```

`panic` unwinds the stack which can cause odd failures. Better to `log.Fatal` here and below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/roachpb/errors.go, line 262 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542#-K_c5H0Y62kYTzezR1l1:-K_c5H0Y62kYTzezR1l2:b-cu48u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1c2b48c41f7834379b112835f4b1ed19fb5edbe/pkg/roachpb/errors.go#L262)):*
> ```Go
> func (e *NotLeaseHolderError) message(_ *Error) string {
> 	if e.CustomMsg != "" {
> 		return e.CustomMsg
> ```

It bothers me that some NotLeaseHolder errors will look totally different from others in the logs, when the internal handling is identical because it's based on type switches. I'd like to see a prefix or something injected here so that no matter what the CustomMsg says you can still tell it's a NotLeaseHolder error. (I kind of wish all our error messages started with their type name)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542#-:-K_cEI0YTo2yM9g0bOOi:bnfp4nl)*

**Comment by tamird** [comment]
Reviewed 1 of 7 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica.go, line 3304 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542#-K_UhBytMlYTMQ8SUm2z:-K_eJ7L6Zv-SDnqpB4NZ:bhec913) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1c2b48c41f7834379b112835f4b1ed19fb5edbe/pkg/storage/replica.go#L3304)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`panic` unwinds the stack which can cause odd failures. Better to `log.Fatal` here and below.
</blockquote></details>

also generally a good idea to include some additional information in the message.

---

*[pkg/storage/replica.go, line 3385 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542#-K_eJMGSVL0H8JAwNa6k:-K_eJMGSVL0H8JAwNa6l:b3q91gq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1c2b48c41f7834379b112835f4b1ed19fb5edbe/pkg/storage/replica.go#L3385)):*
> ```Go
> 			err := newNotLeaseHolderError(
> 				r.mu.state.Lease, raftCmd.OriginReplica.StoreID, r.mu.state.Desc)
> 			nlhe := err.(*roachpb.NotLeaseHolderError)
> ```

perhaps you could change `newNotLeaseHolderError` to return a `*roachpb.NotLeaseHolderError` instead of writing this line.

---

*[pkg/storage/replica.go, line 3387 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542#-K_eJUlb60pcS9M_wXAH:-K_eJUlb60pcS9M_wXAI:b4thdqt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1c2b48c41f7834379b112835f4b1ed19fb5edbe/pkg/storage/replica.go#L3387)):*
> ```Go
> 			nlhe := err.(*roachpb.NotLeaseHolderError)
> 			nlhe.CustomMsg = fmt.Sprintf(
> 				"stale proposal: command was proposed under %s but is being applied "+
> ```

s/under/under lease/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542)*

**Comment by andreimatei** [comment]
Review status: 3 of 9 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/roachpb/errors.go, line 262 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542#-K_c5H0Y62kYTzezR1l1:-K_juKpvzuJZscP0Nfwl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1c2b48c41f7834379b112835f4b1ed19fb5edbe/pkg/roachpb/errors.go#L262)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

It bothers me that some NotLeaseHolder errors will look totally different from others in the logs, when the internal handling is identical because it's based on type switches. I'd like to see a prefix or something injected here so that no matter what the CustomMsg says you can still tell it's a NotLeaseHolder error. (I kind of wish all our error messages started with their type name)
</blockquote></details>

Done.

---

*[pkg/roachpb/errors.proto, line 48 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542#-K_1PcRzHC2tzeenNo1p:-K_jukA_djnuVWIWvTW7:b-gb6emb) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1c2b48c41f7834379b112835f4b1ed19fb5edbe/pkg/roachpb/errors.proto#L48)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

"applies", "was proposed" these are different tenses. "under which its application was attempted", perhaps?
</blockquote></details>

done, but still kept two tenses - that's the point, there were two different times in question. But I've changed one of them to "it had been proposed". I think that's correct?

---

*[pkg/storage/client_test.go, line 430 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542#-KZZCjeyfwJKpNHBwloj:-K_jwlgF1wypDZeLZZhk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/24fb0d119ac048e63daa15c4bab9e0081fe31f30/pkg/storage/client_test.go#L430)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

`return fmt.Sprintf("%T: replicas=%v, idx=%d", t, t.replicas, t.idx)`
</blockquote></details>

Done.

---

*[pkg/storage/replica.go, line 3304 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542#-K_UhBytMlYTMQ8SUm2z:-K_jxKSaDsjdahex4ghC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1c2b48c41f7834379b112835f4b1ed19fb5edbe/pkg/storage/replica.go#L3304)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

also generally a good idea to include some additional information in the message.
</blockquote></details>

Done.

---

*[pkg/storage/replica.go, line 3385 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542#-K_eJMGSVL0H8JAwNa6k:-K_k5SDmY-CVq2cv7CI2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1c2b48c41f7834379b112835f4b1ed19fb5edbe/pkg/storage/replica.go#L3385)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

perhaps you could change `newNotLeaseHolderError` to return a `*roachpb.NotLeaseHolderError` instead of writing this line.
</blockquote></details>

Done.

---

*[pkg/storage/replica.go, line 3387 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542#-K_eJUlb60pcS9M_wXAH:-K_k5X2EkyYlg-sSNnNN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1c2b48c41f7834379b112835f4b1ed19fb5edbe/pkg/storage/replica.go#L3387)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

s/under/under lease/
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542)*

**Comment by tamird** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/roachpb/errors.proto, line 48 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542#-K_1PcRzHC2tzeenNo1p:-K_kTHy3q7cMc2JYqgWR:b-jrdngo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1c2b48c41f7834379b112835f4b1ed19fb5edbe/pkg/roachpb/errors.proto#L48)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

done, but still kept two tenses - that's the point, there were two different times in question. But I've changed one of them to "it had been proposed". I think that's correct?
</blockquote></details>

Sure, that's fine.

Pedantically, not all past tenses refer to the same time in the past, so "there were two different times in question" does not justify using different tenses.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12542)*

**Pull request merged**
