### PR TITLE
sql: use type bytes for virtual inverted columns

### LINKED ISSUE #50695: opt: change the key column of inverted indexes to use a new column id and type
Currently, the inverted key column of an inverted index uses the same column ID and type as the original table column it indexes. This is a problem if the column needs to be passed between several operators, because the execution engine expects a column with a certain type (e.g., Geometry), but receives a different type (e.g., int). It also makes several things awkward in the optimizer, and requires special handling of the inverted key column.

The solution is to create a new column for the inverted key column, with a new column ID and type corresponding to the real type stored in the inverted index. This issue tracks the work to make that change in the optimizer.

### PR DESCRIPTION
**Pull request by rytaft**
This commit changes the column type for virtual inverted columns when
constructing `scanNodes` and `TableReaderSpecs` so that the type matches the data
type actually stored in the index. Prior to this commit, the type corresponded
to the column being indexed (e.g., `geometry`), rather than the actual type of
the key column (e.g., `bytes`). This is needed in order to enable vectorized
execution with the `invertedFilterer` processor.

Additionally, the column fetecher now treats virtual inverted columns
differently and dumps the data directly into a `DBytes` rather than attempting
to decode it.

Fixes #50695

Release note (performance improvement): Queries that use a geospatial inverted
index can now take advantage of vectorized execution for some parts of the
query plan, resulting in improved performance.

### CODE REVIEW

**Comment by rytaft** [comment]
This PR is the result of rebasing #53202 and making a few tweaks:

- Now the type of all inverted virtual columns is `Bytes`.
- The `cFetcher` and index decoding functions are now aware of virtual inverted columns, and will dump the output directly into a `DBytes` instead of trying to decode it.

In order to get this working quickly, I added a hack for zig zag joins (it's called out in `distsql_physical_planner.go`). We'll need to do a bigger refactor of zig zag joins to get this to work without the hack, although I think we were going to need to do that anyway to support multi-column inverted indexes and integrate with the other work we've been doing in the optimizer to improve inverted index support. If this PR looks like the right approach, then I'll do the zig zag join refactor as a second commit in this PR.

**Review by yuzefovich — COMMENTED** [review]
Looks good to me, thanks for working on this!

> Reviewed 26 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58241#-:-MPFgJYu44Tt80P00GOe:bc0jf8g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @RaduBerinde, and @rytaft)

___
*[pkg/sql/distsql_spec_exec_factory.go, line 240 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58241#-MPFdEz34wZc_f3RmApx:-MPFdEz34wZc_f3RmApy:b-t4htfz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2592330a17cf681a86176eeb0f211ce5e498256a/pkg/sql/distsql_spec_exec_factory.go#L240)):*
> ```Go
> 		NeededColumns:    colCfg.wantedColumnsOrdinals,
> 	}
> 	if colCfg.virtualColumns != nil {
> ```

nit: this code is duplicated with `distsql_physical_planner`.
___
*[pkg/sql/catalog/colinfo/col_type_info.go, line 172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58241#-MPFdrtG5lKfQ2q73k-K:-MPFdrtG5lKfQ2q73k-L:bn6x5gn) ([raw file](https://github.com/cockroachdb/cockroach/blob/2592330a17cf681a86176eeb0f211ce5e498256a/pkg/sql/catalog/colinfo/col_type_info.go#L172)):*
> ```Go
> func GetColumnTypesFromColDescs(
> 	cols []descpb.ColumnDescriptor, columnIDs []descpb.ColumnID, outTypes []*types.T,
> ) ([]*types.T, error) {
> ```

nit: seems like `err` is always `nil`.
___
*[pkg/sql/rowexec/inverted_filterer.go, line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58241#-MPFfh4P0cbrxXftFplz:-MPFfh4P0cbrxXftFpm-:b-cm2acd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2592330a17cf681a86176eeb0f211ce5e498256a/pkg/sql/rowexec/inverted_filterer.go#L228)):*
> ```Go
> 		// If the input is from the vectorized engine, the encoded bytes may be
> 		// empty.
> 		if row[ifr.invertedColIdx].Datum == nil {
> ```

Can we ever have a `DNull` value here?
___
*[pkg/sql/rowexec/rowfetcher.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58241#-MPFg95WEyuZUVS5MVSS:-MPFg95XCVJizkPWQ2au:b-vqccjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/2592330a17cf681a86176eeb0f211ce5e498256a/pkg/sql/rowexec/rowfetcher.go#L89)):*
> ```Go
> 	}
> 	if virtualColumns != nil {
> 		tempCols := make([]descpb.ColumnDescriptor, len(cols), len(cols)+len(systemColumns))
> ```

nit: duplicated with `colbatch_scan.go`.

**Review by rytaft — COMMENTED** [review]
TFTR, @yuzefovich! I'll work on adding the zig zag join commit now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58241#-:-MPfkfE447ox6Gbf0e7F:b5rfror)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/distsql_spec_exec_factory.go, line 240 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58241#-MPFdEz34wZc_f3RmApx:-MPfhf89AbQi5vrHVUEM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2592330a17cf681a86176eeb0f211ce5e498256a/pkg/sql/distsql_spec_exec_factory.go#L240)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: this code is duplicated with `distsql_physical_planner`.
</blockquote></details>

Done.
___
*[pkg/sql/catalog/colinfo/col_type_info.go, line 172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58241#-MPFdrtG5lKfQ2q73k-K:-MPfbK1iA5MRoxCluRVj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2592330a17cf681a86176eeb0f211ce5e498256a/pkg/sql/catalog/colinfo/col_type_info.go#L172)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: seems like `err` is always `nil`.
</blockquote></details>

Done.
___
*[pkg/sql/rowexec/inverted_filterer.go, line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58241#-MPFfh4P0cbrxXftFplz:-MPfaee85csxL9erGdyH:bav40xr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2592330a17cf681a86176eeb0f211ce5e498256a/pkg/sql/rowexec/inverted_filterer.go#L228)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Can we ever have a `DNull` value here?
</blockquote></details>

Shouldn't ever be `DNull` since nulls aren't stored in inverted indexes.
___
*[pkg/sql/rowexec/rowfetcher.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58241#-MPFg95WEyuZUVS5MVSS:-MPfkcvd2m1n15MJR_T7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2592330a17cf681a86176eeb0f211ce5e498256a/pkg/sql/rowexec/rowfetcher.go#L89)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: duplicated with `colbatch_scan.go`.
</blockquote></details>

Done.

**Review by rytaft — COMMENTED** [review]
I've realized that the zigzag join refactor should be in a separate PR. I've found a way to remove the hack I added without needing to do the refactor. This is ready for review.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58241#-:-MPowHKx-g4pM5arL-TF:b-h0itr7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @RaduBerinde, and @yuzefovich)

**Review by sumeerbhola — COMMENTED** [review]
> Reviewed 7 of 26 files at r1, 7 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58241)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/sql/scan.go, line 119 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58241#-MQE3f-EAi3T3Lc1G4uq:-MQE3f-EAi3T3Lc1G4ur:b-kga750) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bea5bd2aee6c92a269472283958b1700f71428d/pkg/sql/scan.go#L119)):*
> ```Go
> 
> 	// virtualColumns maps a subset of wantedColumns that are virtual to the
> 	// column type actually stored in the index. For example, the key column
> ```

nit: how about "inverted column" instead of "key column" since we now have multi-column inverted indexes?
___
*[pkg/sql/execinfrapb/processors_sql.proto, line 150 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58241#-MQE5C8HCop8n4d_d6Dx:-MQE5C8HCop8n4d_d6Dy:b-xu1bej) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bea5bd2aee6c92a269472283958b1700f71428d/pkg/sql/execinfrapb/processors_sql.proto#L150)):*
> ```protobuf
>   // stored in the table descriptor. For example, the key column in an inverted
>   // index has a different type than the column it indexes in the base table.
>   repeated sqlbase.ColumnDescriptor virtual_columns = 16;
> ```

wondering why this is a repeated field instead of being optional.
___
*[pkg/sql/rowexec/inverted_filterer.go, line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58241#-MPFfh4P0cbrxXftFplz:-MQE6-PL3SJ473q_HZBR:b9srk7u) ([raw file](https://github.com/cockroachdb/cockroach/blob/2592330a17cf681a86176eeb0f211ce5e498256a/pkg/sql/rowexec/inverted_filterer.go#L228)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Shouldn't ever be `DNull` since nulls aren't stored in inverted indexes.
</blockquote></details>

Could you add a code comment that states this.
___
*[pkg/sql/rowexec/inverted_filterer.go, line 236 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58241#-MQE6GdOEX4BJW7fDsAF:-MQE6GdOEX4BJW7fDsAG:b-ksiibm) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bea5bd2aee6c92a269472283958b1700f71428d/pkg/sql/rowexec/inverted_filterer.go#L236)):*
> ```Go
> 			return ifrStateUnknown, ifr.DrainHelper()
> 		}
> 		enc = []byte(*row[ifr.invertedColIdx].Datum.(*tree.DBytes))
> ```

This is a peculiar hack and I think deserves a longer comment above the if-block. Something like:
// NB: Inverted columns are custom encoded in a manner that does not correspond to Datum encoding, and in the code here we only want the encoded bytes.  We have two possibilities with what the provider of this row has done:
// - not decoded the row: This is the `len(enc) > 0` case.
// - decoded the row, but special-cased the inverted column by stuffing the encoded bytes into a "decoded" DBytes: This is the `len(enc) == 0` case.
___
*[pkg/sql/rowexec/inverted_joiner.go, line 463 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58241#-MQE9JVC3eZJxqXmwwLP:-MQE9JVC3eZJxqXmwwLQ:bhgld0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bea5bd2aee6c92a269472283958b1700f71428d/pkg/sql/rowexec/inverted_joiner.go#L463)):*
> ```Go
> 		}
> 		idx := ij.colIdxMap.GetDefault(ij.invertedColID)
> 		encInvertedVal := scannedRow[idx].EncodedBytes()
> ```

If the `rowFetcher` used by `invertedJoiner` had a columnar implementation, we would need to make a similar change here, yes?

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 20 of 26 files at r1, 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58241#-:-MQEuqoH1fRFkvyMugpm:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @RaduBerinde, @rytaft, and @yuzefovich)

**Review by jordanlewis — COMMENTED** [review]
:lgtm: mod comments, thanks so much for taking care of this!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58241#-:-MQHuaSSAFKUmCPH0u8h:b-6ojgq3)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/sql/catalog/tabledesc/structured.go, line 4019 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58241#-MQHtz977u0q4pGxdpo0:-MQHtz977u0q4pGxdpo1:b-qtpq5p) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bea5bd2aee6c92a269472283958b1700f71428d/pkg/sql/catalog/tabledesc/structured.go#L4019)):*
> ```Go
> // bool is true. If virtualCols is non-nil, substitutes the type of the virtual
> // column instead of the table column with the same ID.
> func (desc *Immutable) ColumnTypesWithMutationsAndVirtualCols(
> ```

cc @ajwerner @postamar do we need to be adding stuff like this to interfaces now too?

**Review by rytaft — COMMENTED** [review]
TFTRs!

Based on @sumeerbhola's observation below, I think there is some unnecessary complexity in this implementation. I'm going to try a quick experiment to see if I can remove some of the complexity.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58241#-:-MQI1Ly7B2eUzVtUhSV_:bsyf7j9)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner, @RaduBerinde, @rytaft, @sumeerbhola, and @yuzefovich)

___
*[pkg/sql/scan.go, line 119 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58241#-MQE3f-EAi3T3Lc1G4uq:-MQELCvn6tiLGDnsRz7h:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bea5bd2aee6c92a269472283958b1700f71428d/pkg/sql/scan.go#L119)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: how about "inverted column" instead of "key column" since we now have multi-column inverted indexes?
</blockquote></details>

Done.
___
*[pkg/sql/execinfrapb/processors_sql.proto, line 150 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58241#-MQE5C8HCop8n4d_d6Dx:-MQELEfF4ljAmtr-gfzY:boxgq0n) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bea5bd2aee6c92a269472283958b1700f71428d/pkg/sql/execinfrapb/processors_sql.proto#L150)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

wondering why this is a repeated field instead of being optional.
</blockquote></details>

In theory there could be multiple virtual columns. We have other virtual column types (e.g., virtual computed), but I don't think there is a use case for them to be added here, so this is probably unnecessary.

I'm going to do a quick experiment to see if I can simplify this using the knowledge that (1) there will be at most one virtual inverted column, and (2) it always has type bytes.
___
*[pkg/sql/rowexec/inverted_filterer.go, line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58241#-MPFfh4P0cbrxXftFplz:-MQHyaR_EsBYcv2DSZWx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2592330a17cf681a86176eeb0f211ce5e498256a/pkg/sql/rowexec/inverted_filterer.go#L228)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Could you add a code comment that states this.
</blockquote></details>

Done.
___
*[pkg/sql/rowexec/inverted_filterer.go, line 236 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58241#-MQE6GdOEX4BJW7fDsAF:-MQHzkqz8NOXpYF_y5OI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bea5bd2aee6c92a269472283958b1700f71428d/pkg/sql/rowexec/inverted_filterer.go#L236)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This is a peculiar hack and I think deserves a longer comment above the if-block. Something like:
// NB: Inverted columns are custom encoded in a manner that does not correspond to Datum encoding, and in the code here we only want the encoded bytes.  We have two possibilities with what the provider of this row has done:
// - not decoded the row: This is the `len(enc) > 0` case.
// - decoded the row, but special-cased the inverted column by stuffing the encoded bytes into a "decoded" DBytes: This is the `len(enc) == 0` case.
</blockquote></details>

Done.
___
*[pkg/sql/rowexec/inverted_joiner.go, line 463 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58241#-MQE9JVC3eZJxqXmwwLP:-MQI18Hw8JbHf_XLBQm_:b9tasdl) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bea5bd2aee6c92a269472283958b1700f71428d/pkg/sql/rowexec/inverted_joiner.go#L463)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

If the `rowFetcher` used by `invertedJoiner` had a columnar implementation, we would need to make a similar change here, yes?
</blockquote></details>

Yep, added a comment.

**Comment by postamar** [comment]
> 
> > ```go
> > func (desc *Immutable) ColumnTypesWithMutationsAndVirtualCols(
> > ```
> 
> cc @ajwerner @postamar do we need to be adding stuff like this to interfaces now too?

I believe so.

**Review by rytaft — COMMENTED** [review]
I changed the virtual columns slice to be a pointer to a single column descriptor instead. I think it's improved things slightly. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58241#-:-MQInxryAB-ND0154zFe:b-rrf70s)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner, @mgartner, @postamar, @RaduBerinde, @sumeerbhola, and @yuzefovich)

___
*[pkg/sql/catalog/tabledesc/structured.go, line 4019 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58241#-MQHtz977u0q4pGxdpo0:-MQInYPW9E6dPPRb9ivM:b-bddov0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bea5bd2aee6c92a269472283958b1700f71428d/pkg/sql/catalog/tabledesc/structured.go#L4019)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

cc @ajwerner @postamar do we need to be adding stuff like this to interfaces now too?
</blockquote></details>

I changed this to use `wrapper` instead of `Immutable`.
___
*[pkg/sql/execinfrapb/processors_sql.proto, line 150 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58241#-MQE5C8HCop8n4d_d6Dx:-MQInidxCDR5NAv04Kj1:b-9ycp8s) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bea5bd2aee6c92a269472283958b1700f71428d/pkg/sql/execinfrapb/processors_sql.proto#L150)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

In theory there could be multiple virtual columns. We have other virtual column types (e.g., virtual computed), but I don't think there is a use case for them to be added here, so this is probably unnecessary.

I'm going to do a quick experiment to see if I can simplify this using the knowledge that (1) there will be at most one virtual inverted column, and (2) it always has type bytes.
</blockquote></details>

Changed it to use optional.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

I didn't carefully read the side-effects of this change on the sql package, since I am not very familiar with that code.

> Reviewed 3 of 26 files at r1, 3 of 5 files at r3, 14 of 15 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58241#-:-MQItje0DLT18YzdTKTU:bkwtovw)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner, @postamar, @RaduBerinde, @sumeerbhola, and @yuzefovich)

**Review by rytaft — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58241#-:-MQN5PZZ7jKTmFBKOy_P:b-tlx7ko)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner, @postamar, @RaduBerinde, @sumeerbhola, and @yuzefovich)

**Comment by RaduBerinde** [comment]
Congrats on figuring this out!

**Pull request merged**
