### PR TITLE
kvserver, batcheval: pin Engine state during read-only command evaluation

### LINKED ISSUE #55461: kv: batch evaluation should operate on a consistent storage snapshot
Neither `Engine.NewReadOnly` nor `Engine.NewBatch` actually grabs a stable storage snapshot. Instead, they wait until iterator creation to do so, and then cache the iterator across multiple uses. This leads to two issues.

First, it is unclear when the storage snapshot is captured, making it difficult to coordinate with other state changes without more aggressive serialization using latches or the `readOnlyCmdMu`. Ideally, users would be able to grab a read-only/batch, check a few conditions, and then decide whether evaluation should proceed using the storage snapshot. This comes up in the context of [replica destruction](https://github.com/cockroachdb/cockroach/issues/46329) and in the context of [MVCC GC](https://github.com/cockroachdb/cockroach/issues/55293). 

Second, both of these objects cache multiple types of iterators, including a prefix iterator and a non-prefix iterator. This means that neither reader actually provides a stable storage snapshot at any point. Users have to be ready for inconsistencies to arise between different iterators pulled from the same read-only/batch. This leads to bugs like https://github.com/cockroachdb/cockroach/issues/47219, where state read from one iterator may not agree with state read from another.

Related Slack thread: https://cockroachlabs.slack.com/archives/CAC6K3SLU/p1602087652111000.

Jira issue: CRDB-3659

### LINKED ISSUE #70974: kv: QueryResolvedTimestamp iterator snapshot may be captured before closed timestamp
In `QueryResolvedTimestampRequest`'s evaluation function, we have the following logic:

https://github.com/cockroachdb/cockroach/blob/5f53feb1ce7070453e9ce52d99013934718cc9d7/pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp.go#L51-L57

@sumeerbhola noticed in https://github.com/cockroachdb/cockroach/pull/70852 that:

> unrelated to this PR, I'm worried by this comment @nvanbenschoten
> * We have discussed that we would like a Reader that returns true for ConsistentIterators to contain a version of the engine from when the Reader was created. I think that would not be acceptable in this latchless situation where we want to see the engine state after the closed timestamp has been retrieved. Is my understanding correct?
> * Even with the current lazy creation of the first cloneable iterator, we could have multiple requests in a batch, and a request in the batch that preceded this QueryResolvedTimestampRequest could have created that iterator that we will subsequently clone. So the iterator we create in createMinIntentTimestamp could reflect the engine state prior to this closed timestamp. Is there something preventing this?

@nvanbenschoten responded:

> This is a very good catch. You are correct that this is improperly relying on the Reader's LSM snapshot being lazily captured at the time of the iterator creation. This will be completely broken when we begin capturing Reader snapshots eagerly and is broken today in cases where we have multiple QueryResolvedTimestampRequests in the same batch.
>
> What's even more interesting is that this isn't actually causing issues today, for a very subtle reason. We do issue multiple QueryResolvedTimestampRequest in the same batch to the same range here, so we should hit the second problem. This means that for all but the first request in the batch, we could observe a closed timestamp that was carried in a later log entry than the last entry applied to the observed version of the state machine in computeMinIntentTimestamp. However, because of the way that these QueryResolvedTimestamp responses are combined, we happen to avoid any problems. Each response carries min(closed_ts, min_intent_ts), and we combine the responses by taking the min of all responses (min(min(closed_ts_1, min_intent_ts_1), min(closed_ts_2, min_intent_ts_2), ...)). So because the closed timestamp increases monotonically, we effectively ignore all closed timestamps except the first one and we end up with the correct resolved timestamp.
>
> But regardless, we should fix this. My thinking about how to do that in a way that composes with #55461 is a little hazy. We've discussed the need to snapshot additional replica state for read-only operations that may evaluate after dropping latches. We could capture the pre-snapshot closed timestamp in this bundle to ensure that it is properly sequenced with the engine snapshot. But the closed timestamp isn't negligibly cheap to grab, so we probably wouldn't want to grab it if none of the requests needed it.
>
> Since this isn't causing issues, I'm tempted to say that we should try to solve this as part of #55461, but if you have thoughts, I'd be happy to dive deeper into this now. I opened #70974 to continue the discussion.

Jira issue: CRDB-10315

### PR DESCRIPTION
**Pull request by aayushshah15**
This commit makes it such that we eagerly pin the engine state of the `Reader`
created during the evaluation of read-only requests.

Generally, reads will hold latches throughout the course of their evaluation
(particularly, while they do their `MVCCScan`). Mainly, this commit paves the
way for us to move to a world where we avoid holding latches during the
MVCCScan. Additionally, it also lets us make MVCC garbage collection latchless
as described in #55293.

There are a few notable changes in this patch:

1. Pinning the engine state eagerly runs into #70974. To resolve this, the
closed timestamp of the `Replica` is now captured at the time the `EvalContext`
is created, and not during the command evaluation of
`QueryResolvedTimestampRequest`.

2. `EvalContext` now has a `ImmutableEvalContext` embedded into it. The
`ImmutableEvalContext` is supposed to encapsulate state that must not change
after the `EvalContext` is created. The closed timestamp of the replica is part
of the `ImmutableEvalContext`.

3. `Replica` no longer fully implements the `EvalContext` interface. Instead,
it implements everything but `GetClosedTimestamp()` (which is implemented by
`ImmutableEvalContext` instead).

Relates to https://github.com/cockroachdb/cockroach/issues/55293
Resolves https://github.com/cockroachdb/cockroach/issues/55461
Resolves https://github.com/cockroachdb/cockroach/issues/70974

Release note: None

### CODE REVIEW

**Comment by aayushshah15** [comment]
Hey @nvanbenschoten, does this match your expectation of what we had discussed in the last few weeks? 

This may need a few tests but I wanted to confirm that the approach is close to what you had in mind. I confirmed that pinning the engine state eagerly (and doing nothing else) fails `TestNonBlockingReadsAtResolvedTimestamp` under stress and then confirmed that capturing the closed timestamp eagerly when we create the `EvalContext` avoids running into https://github.com/cockroachdb/cockroach/issues/70974.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Looks like the pinning alone has a pretty significant cost 

Which benchmark is this? 
The difference is that before we were creating a `pebble.Iterator` when creating the first `pebbleIterator` and then cloning it for future `pebbleIterators`. So 1 create + (n-1) clonings
While now we are dong 1 create + n clonings. Most of the time n=1. An optimization would be to store a bool in `pebbleReadOnly` and `pebbleBatch` about whether the `{pebbleReadOnly,pebbleBatch}.iter` has been used before and if not, don't bother cloning it.
There is also an existing bug where we may not close the iter:
```
	// Setting iter to nil is sufficient since it will be closed by one of the
	// subsequent destroy calls.
	p.iter = nil
```
This is not true, if no one has created an MVCCIterator or EngineIterator. The bool will also help for fixing this.

> Reviewed 4 of 14 files at r1, 4 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76312#-:-Mvto-kX4plf9shq_zpJ:b-gh8ida)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @sumeerbhola)

___
*[pkg/kv/kvserver/replica_eval_context.go, line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76312#-MvtmzGKALJEQxlvc2NT:-MvtmzGKALJEQxlvc2NU:b85ily3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e68cf0a1fd970c8da8f83a1bc0a3aad724f64f0/pkg/kv/kvserver/replica_eval_context.go#L55)):*
> ```Go
> 
> // GetClosedTimestamp implements the EvalContext interface.
> func (ec *evalContextImpl) GetClosedTimestamp(_ context.Context) hlc.Timestamp {
> ```

this is implementing `ImmutatbleEvalContext`, yes?
Odd that it is named immutable, but the `closedTS` field is protected by a mutex. Who modifies it?

**Review by aayushshah15 — COMMENTED** [review]
> Which benchmark is this?

I should've mentioned it before, but it was just kv95 running for 5 mins.
```
./cockroach workload run kv --init --tolerate-errors --concurrency=192 --splits=1000 --ramp=1m --duration=5m --read-percent=95 --min-block-bytes=4096 --max-block-bytes=4096 {pgurl:1-5}
```

I added the bookkeeping you mentioned to avoid redundantly cloning the iterator an extra time. Here are the numbers with that change (I'm not sure if they're directly comparable to the numbers I posted above, since I don't remember what cluster size I ran the previous numbers on):
```
name \ ops/sec  master.txt  pin-with-closedts.txt  pin-wo-closedts.txt
.                108k ± 2%              112k ± 1%            114k ± 0%

name \ p50      master.txt  pin-with-closedts.txt  pin-wo-closedts.txt
.                1.17 ± 6%              1.10 ± 0%            1.10 ± 0%

name \ p95      master.txt  pin-with-closedts.txt  pin-wo-closedts.txt
.                5.93 ± 2%              5.58 ± 4%            5.50 ± 0%

name \ p99      master.txt  pin-with-closedts.txt  pin-wo-closedts.txt
.                11.7 ± 3%              11.0 ± 0%            11.0 ± 0%

```

Surprisingly, it doesn't seem like the any of the locking inside `Replica.GetCurrentClosedTimestamp()` has much of an effect on the workload, cc @nvanbenschoten.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76312#-:-Mvy3Bi84zwfWNZ6EP93:b81qk40)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/kv/kvserver/replica_eval_context.go, line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76312#-MvtmzGKALJEQxlvc2NT:-Mvy34hXDt8aNcPh6VVB:b6dhanu) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e68cf0a1fd970c8da8f83a1bc0a3aad724f64f0/pkg/kv/kvserver/replica_eval_context.go#L55)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this is implementing `ImmutatbleEvalContext`, yes?
Odd that it is named immutable, but the `closedTS` field is protected by a mutex. Who modifies it?
</blockquote></details>

You're right, we didn't need the mutex here.

**Comment by aayushshah15** [comment]
@nvanbenschoten mentioned that we should run the numbers for with/without the call into `Replica.GetCurrentClosedTimestamp` again for more iterations.

I ran them again for 10 iterations this time, and here they are. `old` is with the call to `GetCurrentClosedTimestamp` and `new` is without:
```
name  old ops/sec  new ops/sec  delta
.       109k ± 3%    115k ± 1%  +5.23%  (p=0.000 n=10+9)

name  old p50      new p50      delta
.       1.14 ± 5%    1.10 ± 0%    ~     (p=0.087 n=10+10)

name  old p95      new p95      delta
.       5.80 ± 0%    5.50 ± 0%  -5.17%  (p=0.002 n=8+10)

name  old p99      new p99      delta
.       11.4 ± 7%    11.0 ± 0%  -3.17%  (p=0.003 n=10+8)

```

**Comment by nvanbenschoten** [comment]
Thanks for gathering those extra numbers. Is the only difference between `old` and `new` the call to `GetCurrentClosedTimestamp `? Put differently, is `new` still pinning iterators? If so, that indicates that calling `GetCurrentClosedTimestamp` indiscriminately is too expensive, right?

**Comment by aayushshah15** [comment]
>If so, that indicates that calling GetCurrentClosedTimestamp indiscriminately is too expensive, right?

Yes, I've added a commit to this PR that makes it such that most requests won't call into `GetCurrentClosedTimestamp()` anymore. PTAL. For the sake of completion, here are the numbers comparing the first commit of this PR (i.e. with pinning and with the call into `GetCurrentClosedTimestamp()` on every request) against the last commit of this PR.
```
> benchstat ../benchlogs/pin-with-closedts.txt ../benchlogs/pin-elide-closedts.txt
name  old ops/sec  new ops/sec  delta
.       109k ± 3%    117k ± 2%  +7.54%  (p=0.000 n=10+10)

name  old p50      new p50      delta
.       1.14 ± 5%    1.10 ± 0%    ~     (p=0.065 n=10+9)

name  old p95      new p95      delta
.       5.80 ± 0%    5.41 ± 4%  -6.72%  (p=0.000 n=8+10)

name  old p99      new p99      delta
.       11.4 ± 7%    10.5 ± 0%  -7.57%  (p=0.000 n=10+8)
```

**Comment by nvanbenschoten** [comment]
For even more completeness, do you have this direct comparison between master and the last commit of this PR?

**Comment by aayushshah15** [comment]
> For even more completeness, do you have this direct comparison between master and the last commit of this PR?

Here is `master` against the last commit in this PR, not sure what to make of the slight perf improvement:
```
benchstat  ../benchlogs/master.txt ../benchlogs/pin-elide-closedts.txt
name  old ops/sec  new ops/sec  delta
.       114k ± 3%    117k ± 2%  +3.31%  (p=0.001 n=10+10)

name  old p50      new p50      delta
.       1.10 ± 0%    1.10 ± 0%    ~     (all equal)

name  old p95      new p95      delta
.       5.50 ± 0%    5.41 ± 4%    ~     (p=0.071 n=6+10)

name  old p99      new p99      delta
.       11.0 ± 0%    10.5 ± 0%  -4.55%  (p=0.000 n=8+8)
```

**Review by nvb — CHANGES_REQUESTED** [review]
> Reviewed 2 of 14 files at r1, 1 of 6 files at r2, 11 of 15 files at r3, 4 of 4 files at r4, 4 of 4 files at r5, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76312)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @sumeerbhola)

___
*[pkg/kv/kvserver/replica_eval_context.go, line 39 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76312#-MzHMBvX2VE1mOzvhnRc:-MzHMBvX2VE1mOzvhnRd:bjaqufp) ([raw file](https://github.com/cockroachdb/cockroach/blob/96b16ffadf966e6a937f4784818b74640db1d528/pkg/kv/kvserver/replica_eval_context.go#L39)):*
> ```Go
> 
> func newEvalContextImpl(r *Replica) *evalContextImpl {
> 	return &evalContextImpl{
> ```

Should we pool these objects to avoid the new heap allocation? Their lifetime should be pretty well defined.
___
*[pkg/kv/kvserver/replica_eval_context.go, line 41 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76312#-MzHMOFN9Tg_nJOKU1E2:-MzHMOFN9Tg_nJOKU1E3:bb7milr) ([raw file](https://github.com/cockroachdb/cockroach/blob/96b16ffadf966e6a937f4784818b74640db1d528/pkg/kv/kvserver/replica_eval_context.go#L41)):*
> ```Go
> 	return &evalContextImpl{
> 		Replica:  r,
> 		closedTS: r.GetCurrentClosedTimestamp(context.TODO()),
> ```

Let's plumb a `ctx` to here.
___
*[pkg/kv/kvserver/batcheval/eval_context.go, line 142 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76312#-MzHMuQe12szWb4ITJu8:-MzHMuQe12szWb4ITJu9:b-a4t1y2) ([raw file](https://github.com/cockroachdb/cockroach/blob/96b16ffadf966e6a937f4784818b74640db1d528/pkg/kv/kvserver/batcheval/eval_context.go#L142)):*
> ```Go
> }
> 
> // ImmutableEvalContext is like EvalContext, but it encapsulates state that
> ```

The idea was to pass only this interface to read-only command evaluation functions, right? To do that, we may need to pull the `EvalContext` out of `CommandArgs`. Even if that is the plan, we can do it in a separate PR.
___
*[pkg/kv/kvserver/batcheval/eval_context.go, line 147 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76312#-MzHNWF9A_UD3Y0v0nqf:-MzHNWF9A_UD3Y0v0nqg:b-p1ejcq) ([raw file](https://github.com/cockroachdb/cockroach/blob/96b16ffadf966e6a937f4784818b74640db1d528/pkg/kv/kvserver/batcheval/eval_context.go#L147)):*
> ```Go
> 	// GetClosedTimestamp returns the current closed timestamp on the range.
> 	// It is expected that a caller will have performed some action (either
> 	// calling RevokeLease or WatchForMerge) to freeze further progression of
> ```

This comment reminds me that `GetClosedTimestamp` is also used in during range subsumption and lease transfers. In those cases, we want the latest closed timestamp, not the closed timestamp at the time of the storage snapshot. The ordering is very important for those cases, as they need the closed timestamp to be computed _after_ their call to `WaitForMerge` or `RevokeLease`. Do you have thoughts on what we should do here? Maybe expose two methods?
___
*[pkg/storage/pebble.go, line 1681 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76312#-MzHVhDMEdQ9YVkjLE8e:-MzHVhDNBbc9oaOwOSeB:b6e8hxv) ([raw file](https://github.com/cockroachdb/cockroach/blob/96b16ffadf966e6a937f4784818b74640db1d528/pkg/storage/pebble.go#L1681)):*
> ```Go
> 
> 	iter       cloneableIter
> 	unused     bool
> ```

nit: should this be called `iterUnused`? Is it clear what it's referring to? Same question below in `pebbleBatch`.

**Review by sumeerbhola — COMMENTED** [review]
> Reviewed 5 of 15 files at r3, 3 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76312)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/storage/pebble.go, line 1681 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76312#-MzHVhDMEdQ9YVkjLE8e:-MzM5AhnCT6VI9_FY8rE:b-bk65dq) ([raw file](https://github.com/cockroachdb/cockroach/blob/96b16ffadf966e6a937f4784818b74640db1d528/pkg/storage/pebble.go#L1681)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: should this be called `iterUnused`? Is it clear what it's referring to? Same question below in `pebbleBatch`.
</blockquote></details>

+1 to `iterUnused`

**Comment by aayushshah15** [comment]
___
*[pkg/kv/kvserver/replica_eval_context.go, line 39 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76312#-MzHMBvX2VE1mOzvhnRc:-MzMdPhM7bN232IVwLib:b3zdj7t) ([raw file](https://github.com/cockroachdb/cockroach/blob/96b16ffadf966e6a937f4784818b74640db1d528/pkg/kv/kvserver/replica_eval_context.go#L39)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we pool these objects to avoid the new heap allocation? Their lifetime should be pretty well defined.
</blockquote></details>

am I doing something wrong in the last commit? I just ran the same kv95 workload I've been running for this PR on the last commit and I'm seeing a pretty big regression. I haven't dug in yet but wondering if it's clear to you already. 

`pin-elide-closedts` is the second-last commit from this PR and `pin-with-pooling` is the last commit from this PR.

```
benchstat ../benchlogs/pin-elide-closedts.txt ../benchlogs/pin-with-pooling.txt
name  old ops/sec  new ops/sec  delta
.       117k ± 2%    105k ± 1%  -10.22%  (p=0.000 n=10+10)

name  old p50      new p50      delta
.       1.10 ± 0%    1.20 ± 0%   +9.09%  (p=0.000 n=9+10)

name  old p95      new p95      delta
.       5.41 ± 4%    6.30 ± 0%  +16.45%  (p=0.000 n=10+8)

name  old p99      new p99      delta
.       10.5 ± 0%    12.1 ± 0%  +15.24%  (p=0.000 n=8+10)
```

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76312)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/kv/kvserver/replica_eval_context.go, line 41 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76312#-MzHMOFN9Tg_nJOKU1E2:-MzM9RMX4gBWK-ddISJO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/96b16ffadf966e6a937f4784818b74640db1d528/pkg/kv/kvserver/replica_eval_context.go#L41)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's plumb a `ctx` to here.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/batcheval/eval_context.go, line 147 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76312#-MzHNWF9A_UD3Y0v0nqf:-MzM9wBn93GhfT782ZXr:b-ajp3gs) ([raw file](https://github.com/cockroachdb/cockroach/blob/96b16ffadf966e6a937f4784818b74640db1d528/pkg/kv/kvserver/batcheval/eval_context.go#L147)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This comment reminds me that `GetClosedTimestamp` is also used in during range subsumption and lease transfers. In those cases, we want the latest closed timestamp, not the closed timestamp at the time of the storage snapshot. The ordering is very important for those cases, as they need the closed timestamp to be computed _after_ their call to `WaitForMerge` or `RevokeLease`. Do you have thoughts on what we should do here? Maybe expose two methods?
</blockquote></details>

Yeah, makes sense to expose two methods. Done. 
___
*[pkg/storage/pebble.go, line 1681 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76312#-MzHVhDMEdQ9YVkjLE8e:-MzMB96vCriasyN13sWD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/96b16ffadf966e6a937f4784818b74640db1d528/pkg/storage/pebble.go#L1681)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

+1 to `iterUnused`
</blockquote></details>

Done.

**Review by nvb — COMMENTED** [review]
> Reviewed 2 of 13 files at r7, 4 of 5 files at r8, 7 of 7 files at r9, 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76312)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @sumeerbhola)

___
*[pkg/kv/kvserver/replica_eval_context.go, line 65 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/76312#-MzS7jP032PRXoecxACO:-MzS7jP032PRXoecxACP:bbyhax2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7b2a3462f04e1b78cdb930b95cde890ca54cd41/pkg/kv/kvserver/replica_eval_context.go#L65)):*
> ```Go
> 		closedTS:       closedTS,
> 	}
> 	return ec, func() {
> ```

Does this closure allocate? Maybe EvalContext should have a `Release` method on it instead.
___
*[pkg/kv/kvserver/batcheval/eval_context.go, line 147 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76312#-MzHNWF9A_UD3Y0v0nqf:-MzS6ehDEiz3H5LyMPw3:b-u0qt1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/96b16ffadf966e6a937f4784818b74640db1d528/pkg/kv/kvserver/batcheval/eval_context.go#L147)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Yeah, makes sense to expose two methods. Done. 
</blockquote></details>

Can we name these more clearly so that callers won't confuse them? Maybe `GetClosedTimestampBeforeStorageSnapshot` and `GetCurrentClosedTimestamp`?
___
*[pkg/roachpb/api.go, line 98 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76312#-MzS7RCQ4GLMjOFDDvSJ:-MzS7RCQ4GLMjOFDDvSK:bka188d) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a6db3199565d5727fbba6921d8f5c53fd31b5cf/pkg/roachpb/api.go#L98)):*
> ```Go
> 	canBackpressure                                // commands which deserve backpressure when a Range grows too large
> 	bypassesReplicaCircuitBreaker                  // commands which bypass the replica circuit breaker, i.e. opt out of fail-fast
> 	requiresClosedTimestamp                        // commands which read a replica's closed timestamp
> ```

Should we rename this and tighten up the comment now that it only applies to a subset of requests which need the closed timestamp?
___
*[pkg/roachpb/api.go, line 1409 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76312#-MzS7IQO3dxVLjrMpWJI:-MzS7IQO3dxVLjrMpWJJ:bfp7fwq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a6db3199565d5727fbba6921d8f5c53fd31b5cf/pkg/roachpb/api.go#L1409)):*
> ```Go
> 
> func (*SubsumeRequest) flags() flag {
> 	return isRead | isAlone | updatesTSCache | requiresClosedTimestamp
> ```

Does Subsume request still need this flag?

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76312)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/kv/kvserver/replica_eval_context.go, line 65 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/76312#-MzS7jP032PRXoecxACO:-MzWDdq56uJNb5QdITvg:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7b2a3462f04e1b78cdb930b95cde890ca54cd41/pkg/kv/kvserver/replica_eval_context.go#L65)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does this closure allocate? Maybe EvalContext should have a `Release` method on it instead.
</blockquote></details>

Done. 
___
*[pkg/kv/kvserver/batcheval/eval_context.go, line 147 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76312#-MzHNWF9A_UD3Y0v0nqf:-MzWDgVY2VYf_A04w7by:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/96b16ffadf966e6a937f4784818b74640db1d528/pkg/kv/kvserver/batcheval/eval_context.go#L147)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we name these more clearly so that callers won't confuse them? Maybe `GetClosedTimestampBeforeStorageSnapshot` and `GetCurrentClosedTimestamp`?
</blockquote></details>

Done.
___
*[pkg/roachpb/api.go, line 98 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76312#-MzS7RCQ4GLMjOFDDvSJ:-MzW57GZAYCXZ85vnoVS:b-lx4fj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a6db3199565d5727fbba6921d8f5c53fd31b5cf/pkg/roachpb/api.go#L98)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we rename this and tighten up the comment now that it only applies to a subset of requests which need the closed timestamp?
</blockquote></details>

Fixed. 
___
*[pkg/roachpb/api.go, line 1409 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76312#-MzS7IQO3dxVLjrMpWJI:-MzW56P88-KMNJJmIbrg:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a6db3199565d5727fbba6921d8f5c53fd31b5cf/pkg/roachpb/api.go#L1409)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does Subsume request still need this flag?
</blockquote></details>

Fixed.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 4 of 13 files at r11, 4 of 13 files at r14, 2 of 7 files at r15, 7 of 7 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76312#-:-Mzq8_jG5RrFXFssqUJP:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15 and @sumeerbhola)

___
*[pkg/kv/kvserver/replica_eval_context.go, line 79 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/76312#-Mzq8--8CgrymI2RRotJ:-Mzq8--8CgrymI2RRotK:b-yj8izc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a0933b7129bce1ae9272ef1f47d29d0e4f1e707/pkg/kv/kvserver/replica_eval_context.go#L79)):*
> ```Go
> 
> // Release implements the EvalContext interface.
> func (ec *evalContextImpl) Release() {
> ```

Should we `*ev = evalContextImpl{}` before placing it in the pool?
___
*[pkg/kv/kvserver/replica_eval_context_span.go, line 278 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/76312#-Mzq8I-7DrB13C9YpmcF:-Mzq8I-7DrB13C9YpmcG:bcu9rw6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a0933b7129bce1ae9272ef1f47d29d0e4f1e707/pkg/kv/kvserver/replica_eval_context_span.go#L278)):*
> ```Go
> 
> // Release implements the batcheval.EvalContext interface.
> func (rec *SpanSetReplicaEvalContext) Release() {}
> ```

`rec.i.Release()`

**Review by nvb — APPROVED** [review]
> Reviewed 2 of 2 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76312)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15 and @sumeerbhola)

**Review by aayushshah15 — COMMENTED** [review]
TFTR!

I'll wait until tomorrow to merge in case @sumeerbhola wants to take another look. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76312#-:-MzqeLrZ47w-rbgsri5I:b6ek9wq)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15 and @sumeerbhola)

___
*[pkg/kv/kvserver/replica_eval_context.go, line 79 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/76312#-Mzq8--8CgrymI2RRotJ:-MzqekxQ5UdldScpiZmP:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a0933b7129bce1ae9272ef1f47d29d0e4f1e707/pkg/kv/kvserver/replica_eval_context.go#L79)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we `*ev = evalContextImpl{}` before placing it in the pool?
</blockquote></details>

Done. 
___
*[pkg/kv/kvserver/replica_eval_context_span.go, line 278 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/76312#-Mzq8I-7DrB13C9YpmcF:-MzqemeF2VIq-PBEuFAf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a0933b7129bce1ae9272ef1f47d29d0e4f1e707/pkg/kv/kvserver/replica_eval_context_span.go#L278)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`rec.i.Release()`
</blockquote></details>

Done.

**Comment by aayushshah15** [comment]
TFTR!

bors r+

**Pull request merged**
