### PR TITLE
sql: SHOW CREATE now uses two-part names for enum types

### LINKED ISSUE #125827: Running `SHOW CREATE ALL TABLES` will generate unsupported DDL
**Describe the problem**

We're implementing some logic that "squashes" all our migrations into a single .sql file. We use Go with Goose if it matters. To do this I run `SHOW CREATE ALL TABLES`. On a schema that has a members table like this:

```sql
-- what roles a user can take in an organization.
CREATE TYPE organization_member_role AS ENUM ('member','owner');

-- allow users to be part of an organization, with a certain role.
CREATE TABLE organization_members (
    organization_id UUID NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role organization_member_role NOT NULL,
    PRIMARY KEY (organization_id, user_id),
    INDEX (user_id) STORING (role)
);
```

When run with `SHOW CREATE ALL TABLES` it will generate the following statements:
```sql
CREATE TYPE public.organization_member_role AS ENUM ('member', 'owner');
CREATE TABLE public.organization_members (
	organization_id UUID NOT NULL,
	user_id UUID NOT NULL,
	"role" defaultdb.public.organization_member_role NOT NULL,
	CONSTRAINT organization_members_pkey PRIMARY KEY (organization_id ASC, user_id ASC),
	INDEX organization_members_user_id_idx (user_id ASC) STORING ("role")
);
```

When this generated sql is executed it will yield an error like this: 
```
      failed to run goose: partial migration error (type:sql,version:1): ERROR: cross database type references are not supported: defaultdb.public.organization_member_role (SQLSTATE 0A000)
      {
          msg: "failed to run goose: partial migration error (type:sql,version:1): ERROR: cross database type references are not supported: defaultdb.public.organization_member_role (SQLSTATE 0A000)",
          err: <*goose.PartialError | 0x140003e2120>{
              Applied: nil,
              Failed: {
                  Source: {
                      Type: "sql",
                      Path: "001_snapshot.sql",
                      Version: 1,
                  },
                  Duration: 40272125,
                  Direction: "up",
                  Empty: false,
                  Error: <*pgconn.PgError | 0x14000384b40>{
                      Severity: "ERROR",
                      Code: "0A000",
                      Message: "cross database type references are not supported: defaultdb.public.organization_member_role",
                      Detail: "",
                      Hint: "",
                      Position: 0,
                      InternalPosition: 0,
                      InternalQuery: "",
                      Where: "",
                      SchemaName: "",
                      TableName: "",
                      ColumnName: "",
                      DataTypeName: "",
                      ConstraintName: "",
                      File: "schema_resolver.go",
                      Line: 337,
                      Routine: "ResolveType",
                  },
              },
              Err: <*pgconn.PgError | 0x14000384b40>{
                  Severity: "ERROR",
                  Code: "0A000",
                  Message: "cross database type references are not supported: defaultdb.public.organization_member_role",
                  Detail: "",
                  Hint: "",
                  Position: 0,
                  InternalPosition: 0,
                  InternalQuery: "",
                  Where: "",
                  SchemaName: "",
                  TableName: "",
                  ColumnName: "",
                  DataTypeName: "",
                  ConstraintName: "",
                  File: "schema_resolver.go",
                  Line: 337,
                  Routine: "ResolveType",
              },
          },
      }
```

**To Reproduce**

- Setup a database with the above schema
- Run SHOW CREATE ALL TABLES
- Copy and run create statement 

**Expected behavior**
It should not generate DDL that it doesn't support itself

**Additional data / screenshots**
<see above>

**Environment:**
 - CockroachDB  v23.2.5
 - MacOS
 - Golang, Goose

**Additional context**
This makes me worry about whether this command can actually be trusted on. 

Jira issue: CRDB-39623

Epic CRDB-37763

### PR DESCRIPTION
**Pull request by spilchen**
Previously, when viewing DDL through `SHOW CREATE`, enum types were displayed with a three-part name: `database.schema.type`. This limited the usefulness of the DDL output because it could only be applied to a database with the same name.

Now, the `SHOW CREATE` output uses a two-part name (`schema.type`), matching the style used by postgres in the `pg_dump` command.

There are many test changes due to the numerous uses of the `SHOW CREATE` command. Most changes involve removing the database name from the type name.

Additionally, I added an option to `tree/format.go` to allow using a three-part name for types. This is necessary to continually detect cross-database type access in views.

Epic: none
Closes: #125827
Release note (bug fix): When showing enum types in `SHOW CREATE` output, we now format the name as a two-part name instead of a three-part name. This change makes it easier to apply the output with enum types, to other databases.

### CODE REVIEW

**Comment by michae2** [comment]
Nice change!! Sorry for the drive-by comment, but I was wondering: since the commit message mentions enum types, does this also affect composite types?

**Comment by spilchen** [comment]
> Nice change!! Sorry for the drive-by comment, but I was wondering: since the commit message mentions enum types, does this also affect composite types?

Thanks... No, this doesn't affect composite types. I wanted to keep the scope narrow. I have a separate issue for that: #125934. When composite types are included in `SHOW CREATE` commands, they are displayed with a one-part name, without including the schema.

**Review by michae2 — COMMENTED** [review]
> Reviewed 3 of 35 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125996)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @dt, @spilchen, and @wenyihu6)

___
*[`pkg/sql/sem/tree/format.go` line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125996#-O-wwGq45LN2w1oVQbdW:-O-wwGq45LN2w1oVQbdX:b-1zyc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f813b85af524b0b60e2c2df96180b4af920be321/pkg/sql/sem/tree/format.go#L191)):*
> ```Go
> 	// FmtFullyQualifyUserDefinedTypeNames instructs the pretty-printer to include
> 	// the name of user-defined types as a three-part name.
> 	FmtFullyQualifyUserDefinedTypeNames
> ```

I wonder if this flag should generalize to all objects, rather than being specific to types. (I think that would mean combining this with `FmtAlwaysQualifyTableNames`?)

My rationale is: it seems like the all the scenarios that require fully-qualified type names will also require fully-qualified table names and function names and view names and sequence names, etc.
___
*[`pkg/sql/sem/tree/format.go` line 645 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125996#-O-wxqxj10UB2-3N1FWV:-O-wxqxkEf3I53DgE5KE:bhjia3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/f813b85af524b0b60e2c2df96180b4af920be321/pkg/sql/sem/tree/format.go#L645)):*
> ```Go
> // FmtAlwaysQualifyTableNames flag (which requires annotations).
> func AsStringWithFQNames(n NodeFormatter, ann *Annotations) string {
> 	ctx := NewFmtCtx(FmtAlwaysQualifyTableNames, FmtAnnotations(ann))
> ```

Should this also use the new flag?
___
*[`pkg/sql/types/types.go` line 2003 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125996#-O-x3nO35LrcDdXYrA_k:-O-x3nO35LrcDdXYrA_l:b-t41t1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f813b85af524b0b60e2c2df96180b4af920be321/pkg/sql/types/types.go#L2003)):*
> ```Go
> // type name to be a fully-qualified 3-part name.
> func (t *T) SQLStringFullyQualified() string {
> 	if t.TypeMeta.Name != nil && t.Family() == EnumFamily {
> ```

If fixing https://github.com/cockroachdb/cockroach/issues/125934 isn't as simple as removing the `== EnumFamily` condition here, could you add a `// TODO(125934)` comment somewhere explaining that composite types are not yet formatted correctly?

**Review by spilchen — COMMENTED** [review]
tftr! I responded to your comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125996#-:-O09abmUDO86fZjHS3aX:b-t0fqmd)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt, @michae2, and @wenyihu6)

___
*[`pkg/sql/sem/tree/format.go` line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125996#-O-wwGq45LN2w1oVQbdW:-O09aPWQ2f4RChWKhcu0:bygeh7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f813b85af524b0b60e2c2df96180b4af920be321/pkg/sql/sem/tree/format.go#L191)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

I wonder if this flag should generalize to all objects, rather than being specific to types. (I think that would mean combining this with `FmtAlwaysQualifyTableNames`?)

My rationale is: it seems like the all the scenarios that require fully-qualified type names will also require fully-qualified table names and function names and view names and sequence names, etc.
</blockquote></details>

It seems these flags are needed in different scenarios. To use `FmtAlwaysQualifyTableNames`, annotations are required. However, for the case where I need a 3-part type name (in `buildCreateView`), annotations aren't available. In fact, `tree.AsStringWithFlags` specifies that flags should be used without requiring annotations. I introduced a helper flag that combines both bits and used it where it's safe. However, I'm not sure if it can be generalized further.
___
*[`pkg/sql/sem/tree/format.go` line 645 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125996#-O-wxqxj10UB2-3N1FWV:-O09aT1W4kzVv3A8uaLT:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f813b85af524b0b60e2c2df96180b4af920be321/pkg/sql/sem/tree/format.go#L645)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Should this also use the new flag?
</blockquote></details>

Done
___
*[`pkg/sql/types/types.go` line 2003 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125996#-O-x3nO35LrcDdXYrA_k:-O09aX6mBTIbGvVhoWzf:b-nhtq8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/f813b85af524b0b60e2c2df96180b4af920be321/pkg/sql/types/types.go#L2003)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

If fixing https://github.com/cockroachdb/cockroach/issues/125934 isn't as simple as removing the `== EnumFamily` condition here, could you add a `// TODO(125934)` comment somewhere explaining that composite types are not yet formatted correctly?
</blockquote></details>

I added the TODO.

**Review by michae2 — APPROVED** [review]
:lgtm: Nice work! This is a great change!

Assuming the testcase below passes, this LGTM. (If it doesn't pass I can help figure out what is going on.)

> Reviewed 30 of 35 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125996#-:-O0ATbBv5gqzEb1g81Xk:b-mzi7m)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dt, @spilchen, and @wenyihu6)

___
*[`pkg/sql/sem/tree/format.go` line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125996#-O-wwGq45LN2w1oVQbdW:-O0ADbNG6h5qzW0S3azM:bozywh3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f813b85af524b0b60e2c2df96180b4af920be321/pkg/sql/sem/tree/format.go#L191)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

It seems these flags are needed in different scenarios. To use `FmtAlwaysQualifyTableNames`, annotations are required. However, for the case where I need a 3-part type name (in `buildCreateView`), annotations aren't available. In fact, `tree.AsStringWithFlags` specifies that flags should be used without requiring annotations. I introduced a helper flag that combines both bits and used it where it's safe. However, I'm not sure if it can be generalized further.
</blockquote></details>

Thanks for investigating! Good point about `tree.AsStringWithFlags`. The helper flag makes sense to me.
___
*[`pkg/sql/sem/tree/format.go` line 270 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125996#-O0AMLKe7YEQPYp4UecW:-O0AMLKe7YEQPYp4UecX:b-btqcv7) ([raw file](https://github.com/cockroachdb/cockroach/blob/7423003c04791527e44f238b4a6f48a2d1a5b2b1/pkg/sql/sem/tree/format.go#L270)):*
> ```Go
> const (
> 	flagsRequiringAnnotations = FmtAlwaysQualifyTableNames
> 	alwaysQualifyNames        = FmtAlwaysQualifyTableNames | FmtAlwaysQualifyUserDefinedTypeNames
> ```

nit: this works fine, but I think this would fit in a little better as one of the derived flags in the block above, similar to `FmtArrayToString`,`FmtExport`, etc.
___
*[`pkg/sql/logictest/testdata/logic_test/distsql_stats` line 1713 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125996#-O0AOqqUCCkoL0KKghRJ:-O0AOqqUCCkoL0KKghRK:b-rop3tr) ([raw file](https://github.com/cockroachdb/cockroach/blob/7423003c04791527e44f238b4a6f48a2d1a5b2b1/pkg/sql/logictest/testdata/logic_test/distsql_stats#L1713)):*
> ```
>             }
>         ],
>         "histo_col_type": "public.greeting",
> ```

Interesting, I didn't realize this would affect table statistics. This makes sense to me, but just to confirm that type resolution during ALTER TABLE INJECT STATISTICS still works correctly, could you add a testcase like the following to this same file:

```
diff --git a/pkg/sql/logictest/testdata/logic_test/distsql_stats b/pkg/sql/logictest/testdata/logic_test/distsql_stats
index ea5e4aac7ad..b40034cbffe 100644
--- a/pkg/sql/logictest/testdata/logic_test/distsql_stats
+++ b/pkg/sql/logictest/testdata/logic_test/distsql_stats
@@ -1740,6 +1740,24 @@ job.schema_change.successful
 job.create_stats.successful
 job.auto_create_stats.successful

+# Check that we can inject the statistics back into the table from a different
+# database.
+
+let $db
+SHOW DATABASE
+
+statement ok
+CREATE DATABASE another_db
+
+statement ok
+USE another_db
+
+statement ok
+ALTER TABLE $db.public.greeting_stats INJECT STATISTICS '$stats'
+
+statement ok
+USE $db
+
 # Regression test for #63387. Stats collection should succeed when partial index
 # predicates reference inverted-type columns.
 statement ok
```

**Review by spilchen — COMMENTED** [review]
I had to make another change to get your test case to pass. If you don't mind taking another look, I would appreciate it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125996#-:-O0Eqrtl3ETWeGfJCjCN:b-s07wqs)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dt, @michae2, and @wenyihu6)

___
*[`pkg/sql/sem/tree/format.go` line 270 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125996#-O0AMLKe7YEQPYp4UecW:-O0Eq7RC2mUCXhJU5DK9:b87jtcs) ([raw file](https://github.com/cockroachdb/cockroach/blob/7423003c04791527e44f238b4a6f48a2d1a5b2b1/pkg/sql/sem/tree/format.go#L270)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: this works fine, but I think this would fit in a little better as one of the derived flags in the block above, similar to `FmtArrayToString`,`FmtExport`, etc.
</blockquote></details>

Yes, make sense.
___
*[`pkg/sql/logictest/testdata/logic_test/distsql_stats` line 1713 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125996#-O0AOqqUCCkoL0KKghRJ:-O0EpuN38SEiXaQx2YGk:bumetrx) ([raw file](https://github.com/cockroachdb/cockroach/blob/7423003c04791527e44f238b4a6f48a2d1a5b2b1/pkg/sql/logictest/testdata/logic_test/distsql_stats#L1713)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Interesting, I didn't realize this would affect table statistics. This makes sense to me, but just to confirm that type resolution during ALTER TABLE INJECT STATISTICS still works correctly, could you add a testcase like the following to this same file:

```
diff --git a/pkg/sql/logictest/testdata/logic_test/distsql_stats b/pkg/sql/logictest/testdata/logic_test/distsql_stats
index ea5e4aac7ad..b40034cbffe 100644
--- a/pkg/sql/logictest/testdata/logic_test/distsql_stats
+++ b/pkg/sql/logictest/testdata/logic_test/distsql_stats
@@ -1740,6 +1740,24 @@ job.schema_change.successful
 job.create_stats.successful
 job.auto_create_stats.successful

+# Check that we can inject the statistics back into the table from a different
+# database.
+
+let $db
+SHOW DATABASE
+
+statement ok
+CREATE DATABASE another_db
+
+statement ok
+USE another_db
+
+statement ok
+ALTER TABLE $db.public.greeting_stats INJECT STATISTICS '$stats'
+
+statement ok
+USE $db
+
 # Regression test for #63387. Stats collection should succeed when partial index
 # predicates reference inverted-type columns.
 statement ok
```
</blockquote></details>

Good test. It did uncover a problem. I changed the code that generated the JSON to go back to referencing the histogram type as a 3-part name.

**Review by michae2 — APPROVED** [review]
:lgtm: Nice work on this!

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125996#-:-O0FLzHo9VKqlC-jab6D:b-wrpl1f)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dt and @wenyihu6)

___
*[`pkg/sql/logictest/testdata/logic_test/distsql_stats` line 1713 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125996#-O0AOqqUCCkoL0KKghRJ:-O0FLaXG0-1ae0ctTmft:btgfc3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/7423003c04791527e44f238b4a6f48a2d1a5b2b1/pkg/sql/logictest/testdata/logic_test/distsql_stats#L1713)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Good test. It did uncover a problem. I changed the code that generated the JSON to go back to referencing the histogram type as a 3-part name.
</blockquote></details>

Ah, ok, SGTM. (I think we probably have to change the semactx or something used by ALTER TABLE INJECT STATISTICS to use the same database as the table name in the ALTER statement but that can be done in the future.)

**Review by fqazi — APPROVED** [review]
Nice work!

:lgtm_strong: 

> Reviewed 30 of 35 files at r1, 3 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125996#-:-O0GQMPa4sHzsoZlut2j:bv2pu2y)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @wenyihu6)

**Comment by spilchen** [comment]
tftr!

bors r+

**Review by rafiss — COMMENTED** [review]
nice work! is it feasible to backport this fix?

**Comment by spilchen** [comment]
> nice work! is it feasible to backport this fix?

Backporting to 24.1 is straightforward. There are conflicts in earlier versions. Resolving conflicts in 23.2 seems manageable, but 23.1 is too complex. Therefore, I will backport to 24.1 and 23.2. I'm about to go on PTO, so I'll open them when I return.

**Pull request merged**
