### PR TITLE
serverutils: don't use tenant mode under bench

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit makes sure that we don't use the multi-tenant test harness
when running the benchmarks by default. This is intended as a
temporary fix until we ensure that using the multi-tenant setup
doesn't introduce any non-determinism.

Additionally, this commit disables logging the INFO message about
starting a default tenant when running the benchmarks since those
messages break the `benchstat` utility.

Informs: #83461.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Friendly ping @cockroachdb/multi-tenant - my reasoning for this change is that it pollutes the output of the benchmarks breaking `benchstat` as well as possibly introduces non-determinism which we want to avoid.

**Review by rharding6373 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83254)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @yuzefovich)

___
*[`pkg/testutils/serverutils/test_server_shim.go` line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83254#-N5aMhkL68Xn-w3Opgm4:-N5aMhkL68Xn-w3Opgm5:b-pe0z4t) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5e58857028b714276fd52abbb660aeac9d3d0a/pkg/testutils/serverutils/test_server_shim.go#L100)):*
> ```Go
> 	}
> 
> 	if rand.Float64() > probabilityOfStartingDefaultTestTenant || skip.UnderBench() {
> ```

Will we want to benchmark multi-tenant separately from non-multi-tenant in the near future? Ideally I think that benchmarks would set the env variable to force tenant or force no tenant.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83254)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @rharding6373)

___
*[`pkg/testutils/serverutils/test_server_shim.go` line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83254#-N5aMhkL68Xn-w3Opgm4:-N5aQXZL7e8P7Bpz37Qc:by68oie) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5e58857028b714276fd52abbb660aeac9d3d0a/pkg/testutils/serverutils/test_server_shim.go#L100)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Will we want to benchmark multi-tenant separately from non-multi-tenant in the near future? Ideally I think that benchmarks would set the env variable to force tenant or force no tenant.
</blockquote></details>

Quite possibly, I dunno. The current setup is definitely broken for benchmarks, and this is the quick fix. Apart from introducing a way to run benchmarks either via single-tenant or multi-tenant config, we'll also need to suppress the INFO messages about the multi-tenant setup being used (this is what's breaking the `benchstat`). We also will want to somehow preserve the ability of comparison against 22.1 branches so that 22.2 branch runs the single-tenant for fair comparison.

Thus, addressing this proper will require more thinking and more work, but in the meantime this seems like a reasonable quick fix.

**Comment by yuzefovich** [comment]
Thanks for the write up.

To be clear, I'm not suggesting that we merge this fix and call it a day - I'm suggesting restoring the status quo ASAP (for two reasons below) and then discuss how to fix it proper:
1. in order to unblock ongoing work that is using the comparison between different SHAs on microbenchmarks as a guide (e.g. I often use `./scripts/bench` (which under the hood uses `benchstat`) to see what perf impact my change has, and this is currently broken)
2. in order to ease the bisect of perf regressions on microbenchmarks in the future, when 22.2 release is about to be shipped. Currently, if we were to run a bisect, again, `benchstat` would not work, making the bisect burdensome.

Thus, I strongly believe it is worth merging the quick fix ASAP, and then we can discuss how to address the issue proper. My guess is that we will want to run benchmarks in both modes in 22.2 timeframe so that we have comparison against 22.1 (while keeping the names of benchmarks under single-tenant config unchanged) and so that we transition to running only multi-tenant configs in 23.1 time frame.

**Comment by knz** [comment]
no objection to merging a quick fix ASAP. I'd just like to ensure we also file the followup work and keep it on the adequate radar in the same action.

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83254)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @rharding6373)

___
*[`pkg/testutils/serverutils/test_server_shim.go` line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83254#-N5aMhkL68Xn-w3Opgm4:-N5avoeZCedd1rdlcw2d:b-3dbxz2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5e58857028b714276fd52abbb660aeac9d3d0a/pkg/testutils/serverutils/test_server_shim.go#L100)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Quite possibly, I dunno. The current setup is definitely broken for benchmarks, and this is the quick fix. Apart from introducing a way to run benchmarks either via single-tenant or multi-tenant config, we'll also need to suppress the INFO messages about the multi-tenant setup being used (this is what's breaking the `benchstat`). We also will want to somehow preserve the ability of comparison against 22.1 branches so that 22.2 branch runs the single-tenant for fair comparison.

Thus, address this proper will require more thinking and more work, but in the meantime this seems like a reasonable quick fix.
</blockquote></details>

Could we change this so that `skip.UnderBench()` changes the `defaultProbabilityOfStartingTestTenant` to `0.0`.  That way, we could still override it using one of the flags.  You might also want to unconditionally skip the `INFO` message in cases where we're running bench, so that we don't impact `benchstat` (along with an accompanying comment).

Note also that my review of this caught a problem with my original PR.  The default probability above is incorrectly set to 1.0 (it should be 0.5).  I did one last run before I merged where I wanted to ensure that I tested everything inside tenants.  Unfortunately, I then merged the 1.0 probability instead of reverting it to 0.5.  I've got a PR out now to correct that initial bad merge.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83254)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @rharding6373)

___
*[`pkg/testutils/serverutils/test_server_shim.go` line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83254#-N5aMhkL68Xn-w3Opgm4:-N5b-bos3hE2z_jriZ91:b-xvo87d) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5e58857028b714276fd52abbb660aeac9d3d0a/pkg/testutils/serverutils/test_server_shim.go#L100)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Could we change this so that `skip.UnderBench()` changes the `defaultProbabilityOfStartingTestTenant` to `0.0`.  That way, we could still override it using one of the flags.  You might also want to unconditionally skip the `INFO` message in cases where we're running bench, so that we don't impact `benchstat` (along with an accompanying comment).

Note also that my review of this caught a problem with my original PR.  The default probability above is incorrectly set to 1.0 (it should be 0.5).  I did one last run before I merged where I wanted to ensure that I tested everything inside tenants.  Unfortunately, I then merged the 1.0 probability instead of reverting it to 0.5.  I've got a PR out now to correct that initial bad merge.
</blockquote></details>

Good points, done.

**Review by rharding6373 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83254#-:-N5b59ek7maUuBZMCgxj:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[`pkg/testutils/serverutils/test_server_shim.go` line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83254#-N5aMhkL68Xn-w3Opgm4:-N5b5NCF6v24nqUVAmNY:b-vs1pr4) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5e58857028b714276fd52abbb660aeac9d3d0a/pkg/testutils/serverutils/test_server_shim.go#L100)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Good points, done.
</blockquote></details>

Looks good.

**Review by ajstorm — APPROVED** [review]
:lgtm: too

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83254#-:-N5bPU57D1bAakx6lXzP:b4xzfr9)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @ajstorm and @rharding6373)

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83254#-:-N5cBEP48xv6sQhFLegN:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajstorm and @rharding6373)

**Pull request merged**
