### PR TITLE
deps: bump `errors` 

### PR DESCRIPTION
**Pull request by knz**

### CODE REVIEW

**Comment by knz** [comment]
I messed up the version bump on both errors and redact :facepalm: 
let's do this once more

**Comment by knz** [comment]
ok hopefully this works now

**Review by erikgrinaker — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66880#-:-Md2PlJz-FJPh1VXEJoo:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

**Comment by knz** [comment]
The PR is currently blocked on `make bazel-generate` being unable to proceed:

```
ERROR: /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/io_bazel_rules_nogo/BUILD.bazel:3:6: in alias rule @io_bazel_rules_nogo//:nogo: cycle in dependency graph:
    //pkg/cmd/generate-test-suites:generate-test-suites
    @io_bazel_rules_go//:go_context_data
.-> @io_bazel_rules_nogo//:nogo
|   @io_bazel_rules_go//:default_nogo
|   @io_bazel_rules_go//go/tools/builders:nogo_srcs
|   @org_golang_x_tools//go/analysis:go_tool_library
|   @org_golang_x_tools//internal/analysisinternal:go_tool_library
|   @org_golang_x_tools//go/ast/astutil:go_tool_library
|   @org_golang_x_tools//internal/typeparams:typeparams
|   @io_bazel_rules_go//:go_context_data
`-- @io_bazel_rules_nogo//:nogo
ERROR: Analysis of target '//pkg/cmd/generate-test-suites:generate-test-suites' failed; build aborted
```

or

```
ERROR: /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/io_bazel_rules_go/BUILD.bazel:73:16: in go_context_data rule @io_bazel_rules_go//:go_context_data: cycle in dependency graph:
    //:gazelle
    //:gazelle-runner
    @bazel_gazelle//cmd/gazelle:gazelle
    @bazel_gazelle//language/go:go_default_library
    @bazel_gazelle//language/go:go
    @bazel_gazelle//rule:rule
    @com_github_bazelbuild_buildtools//tables:go_default_library
.-> @io_bazel_rules_go//:go_context_data
|   @io_bazel_rules_nogo//:nogo
|   @io_bazel_rules_go//:default_nogo
|   @io_bazel_rules_go//go/tools/builders:nogo_srcs
|   @org_golang_x_tools//go/analysis:go_tool_library
|   @org_golang_x_tools//internal/analysisinternal:go_tool_library
|   @org_golang_x_tools//go/ast/astutil:go_tool_library
|   @org_golang_x_tools//internal/typeparams:typeparams
`-- @io_bazel_rules_go//:go_context_data
ERROR: Analysis of target '//:gazelle' failed; build aborted
```

This looks like this may be due to the dependency upgrade of `golang.org/x/tools`?

@rickystewart: would welcome your help here.

**Comment by rickystewart** [comment]
The bug is https://github.com/bazelbuild/rules_go/issues/2479. I've bumped that thread with what I've found in my investigation here -- I don't have a workaround yet, hopefully we find one though.

**Comment by knz** [comment]
I'm going to extract the most important update into a separate PR #67064

this decreases the priority somewhat but this issue is still a ticking bomb

**Comment by knz** [comment]
another occurrence: #67221

**Comment by knz** [comment]
thanks

bors r=erikgrinaker

**Pull request merged**
