### PR TITLE
[WIP] roachtest: add web ui tests with selenium

### PR DESCRIPTION
**Pull request by couchand**
This begins the odyssey of writing end-to-end tests for the Web UI.  A basic Page Object pattern represents the site abstractly, and a smoke test demonstrates the usage.  See pkg/cmd/roachtest/webui/README.markdown for more information.

The first commit was reviewed separately at #25479.

### CODE REVIEW

**Comment by benesch** [comment]
Cool! Drive by comment: do you prefer writing these tests in Go? Seems like it'd be straightforward to keep everything in JS (using something like WebdriverIO). Also doesn't seem like roachtest is buying you much here?

**Comment by benesch** [comment]
> Also doesn't seem like roachtest is buying you much here?

(Specifically, we could just pay for a Sauce Labs subscription. Then we could easily test on the browsers/platforms we claim to support, too.)

**Comment by tschottdorf** [comment]
@benesch I'm not familiar with what exactly Sauce Labs offers but we'll want to test the UI under chaos or with unavailable clusters. All things being equal I also have a mild preference for being able to do this in Go, though I'd defer to whatever the frontend-minded people decide for because it's their gig after all and they'll have to support it.

**Comment by tschottdorf** [comment]
I suppose the way this would work is that we'd start a roachtest and then run a test on sauce labs that runs against that specific cluster. SL feels suited for "does this look and work right for a normal cluster and work in all supported browsers" whereas roachtests can exercise more obscure features like debug functionality with specifically timed events that would seem awkward to orchestrate against SL.

**Comment by petermattis** [comment]
I don't have strong feelings about whether using `roachtest` is appropriate here. We definitely want to avoid the manual setup instructions in `roachtest/webui/README.markdown`.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/cmd/roachtest/cluster.go, line 749 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25483#-LC_Trfs7CSRHkBwkBXu:-LC_Trfs7CSRHkBwkBXv:bhw6y85) ([raw file](https://github.com/cockroachdb/cockroach/blob/91b2d3eefedf9a7a8c3c8a9230a93b5f4f77ef57/pkg/cmd/roachtest/cluster.go#L749)):*
> ```Go
> }
> 
> // WebURL returns the Web UI endpoint for the specified node.
> ```

`s/endpoint/endpoints/g`
`s/node/nodes/g`

---

*[pkg/cmd/roachtest/webui.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25483#-LC_hRTY0_DKrCsl1eqt:-LC_hRTY0_DKrCsl1equ:bjsi3h8) ([raw file](https://github.com/cockroachdb/cockroach/blob/91b2d3eefedf9a7a8c3c8a9230a93b5f4f77ef57/pkg/cmd/roachtest/webui.go#L106)):*
> ```Go
> 	}
> 
> 	for _, testCase := range tests {
> ```

We might want to use subtests here. Especially true if all of the test cases use the same number of nodes.

---

*[pkg/cmd/roachtest/webui/README.markdown, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25483#-LC_hxCQC5VeO5cv8-Bz:-LC_hxCQC5VeO5cv8-C-:b-fdn6qc) ([raw file](https://github.com/cockroachdb/cockroach/blob/91b2d3eefedf9a7a8c3c8a9230a93b5f4f77ef57/pkg/cmd/roachtest/webui/README.markdown#L19)):*
> ```Markdown
> 
> ```
> > java -jar vendor/seleniumhq.org/selenium-server-stanlone-3.12.0.jar
> ```

Isn't this something the `webui` roachtest should be doing internally?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25483#-:-LC_idfH-g1R-WAC-jOP:bduytu9)*

**Pull request closed without merging**
