### PR TITLE
opt: support if and nullif

### PR DESCRIPTION
**Pull request by madelynnblue**
Implement with case, which is a superset of this functionality.

Release note: None

### CODE REVIEW

**Review by justinj — COMMENTED** [review]
:lgtm:, if you plan to backport, hop in #optimizer for the 2.1 backport process (which is slightly different for opt).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29065#-:-LKnZycaA2z8xX8DP1DD:b-5zhxie)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/optbuilder/scalar.go, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29065#-LKneFdXAwI3f9RfX7HV:-LKneFdXAwI3f9RfX7HW:b-rj6up4) ([raw file](https://github.com/cockroachdb/cockroach/blob/00a1f5a9e8f58a7ec93d629e2d7599846b046f6c/pkg/sql/opt/optbuilder/scalar.go#L289)):*
> ```Go
> 		els := b.buildScalarHelper(t.Else.(tree.TypedExpr), "", inScope, nil)
> 		whens := []memo.GroupID{
> 			b.factory.ConstructWhen(b.buildDatum(tree.DBoolTrue), tru),
> ```

`b.buildDatum(tree.DBoolTrue)` -> `b.factory.ConstructTrue()`

**Review by madelynnblue — COMMENTED** [review]
What is the backport policy for opt? This doesn't meet the "bugfix" bar.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29065#-:-LKoz_k60ep3LGMFGzED:b-jjstz9)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/optbuilder/scalar.go, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29065#-LKneFdXAwI3f9RfX7HV:-LKoz_3R7-vhetnscP9V:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/00a1f5a9e8f58a7ec93d629e2d7599846b046f6c/pkg/sql/opt/optbuilder/scalar.go#L289)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

`b.buildDatum(tree.DBoolTrue)` -> `b.factory.ConstructTrue()`
</blockquote></details>

Done.

**Comment by justinj** [comment]
It matters a bit if you have a commit that changes a bunch of tests due to the testing strategy used in opt, but it probably doesn't matter too much for this change since it just adds some tests. Probably doesn't need a backport.

**Comment by knz** [comment]
can you backport this?

**Comment by mjibson** [comment]
yes will backport this

**Pull request merged**
