### PR TITLE
kvserver: fix flake in TestReportUnreachableRemoveRace

### LINKED ISSUE #59209: kv/kvserver: TestReportUnreachableRemoveRace failed
[(kv/kvserver).TestReportUnreachableRemoveRace failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2599972&tab=buildLog) on [master@dd1976daa787371fc61d7fb382c3c0744141ac4b](https://github.com/cockroachdb/cockroach/commits/dd1976daa787371fc61d7fb382c3c0744141ac4b):

```
          | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).ChangeReplicas
          | 	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_command.go:964
          | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeAdminBatch
          | 	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_send.go:584
          | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).sendWithRangeID
          | 	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_send.go:100
          | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).Send
          | 	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_send.go:36
          | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).Send
          | 	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/store_send.go:195
          | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).Send
          | 	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/stores.go:177
          | github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal.func1
          | 	/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:874
          | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr
          | 	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:326
          | github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal
          | 	/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:862
          | github.com/cockroachdb/cockroach/pkg/server.(*Node).Batch
          | 	/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:900
          | github.com/cockroachdb/cockroach/pkg/roachpb._Internal_Batch_Handler.func1
          | 	/go/src/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go:9083
          | github.com/cockroachdb/cockroach/pkg/util/tracing.ServerInterceptor.func1
          | 	/go/src/github.com/cockroachdb/cockroach/pkg/util/tracing/grpc_interceptor.go:124
          | google.golang.org/grpc.getChainUnaryHandler.func1
          | 	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:921
          | github.com/cockroachdb/cockroach/pkg/rpc.NewServer.func1
          | 	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:176
          | google.golang.org/grpc.getChainUnaryHandler.func1
          | 	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:921
          | github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor
          | 	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/auth.go:60
          | google.golang.org/grpc.chainUnaryServerInterceptors.func1
          | 	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:907
          | github.com/cockroachdb/cockroach/pkg/roachpb._Internal_Batch_Handler
          | 	/go/src/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go:9085
          | google.golang.org/grpc.(*Server).processUnaryRPC
          | 	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1082
          | google.golang.org/grpc.(*Server).handleStream
          | 	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1405
          | google.golang.org/grpc.(*Server).serveStreams.func1.1
          | 	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:746
          | runtime.goexit
          | 	/usr/local/go/src/runtime/asm_amd64.s:1374
        Wraps: (5) (n1,s1):6LEARNER: remote couldn't accept LEARNER_INITIAL snapshot 996e7fed at applied index 57 with error: [n1,s1],r36: cannot apply snapshot: [n1,s1]: canApplySnapshotLocked: cannot add placeholder, have an existing placeholder range=36 [/Table/Max-/Max) (placeholder) (n2,s2):5
        Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *markers.withMark (4) *errbase.opaqueWrapper (5) *errutil.leafError
E210120 19:30:15.134091 373380 sql/stats/automatic_stats.go:343  failed to get tables for automatic stats: get-tables: failed to send RPC: sending to all replicas failed; last error: rpc error: code = Canceled desc = grpc: the client connection is closing
    panic.go:617: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestReportUnreachableRemoveRace142428455
--- FAIL: TestReportUnreachableRemoveRace (1.87s)

```

<details><summary>More</summary><p>
Parameters:

- GOFLAGS=-json

```
make stressrace TESTS=TestReportUnreachableRemoveRace PKG=./pkg/kv/kvserver TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestReportUnreachableRemoveRace.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by lunevalex**
Fixes #59209

This cyles through adding/removing replicas, we need to wait for
the removal and addition to go through, before trying the next round
otherwise the cluster could be still taking out a replica when we try to
add it back, or it could still be adding it when we try to remove it.
Additionally the circuit breaker was triggered on the wrong node, we need
to trigger it on all the nodes but the new leader instead of the otherway around.

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60935#-:-MUA4bLPCXYlJva9OqgL:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

**Comment by lunevalex** [comment]
TFTR!

bors r+

**Pull request merged**
