### PR TITLE
rowexec: remove unnecessary joiner member

### PR DESCRIPTION
**Pull request by andreimatei**
The joiner had a field tracking a confusing lookup row index. Besides
being confusing, this member obscured the fact that it was equal to the
ordinal returned by inserting rows into a disk container - and thus that
the respective ordinal is used.

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67326#-:-Me21DTu3Q8GdoFUpqnw:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/sql/rowexec/joinreader_strategies.go, line 429 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67326#-Me20yd_5RmsmBvxeQWR:-Me20yd_5RmsmBvxeQWS:b-wo6pwk) ([raw file](https://github.com/cockroachdb/cockroach/blob/64700a75d4f8f7cffe9146a9944e8421bc61e33a/pkg/sql/rowexec/joinreader_strategies.go#L429)):*
> ```Go
> 		}
> 		var err error
> 		containerIdx, err = s.lookedUpRows.AddRow(ctx, row)
> ```

nit: why not call this `lookedUpRowIdx`?

**Comment by sumeerbhola** [comment]
Thanks for doing this. I should have removed this when switching `joinReader` to use `DiskBackedNumberedRowContainer` (it used to use `DiskBackedIndexedRowContainer` which does not return the ordinal, which was why this field originally existed).

**Review by sumeerbhola — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67326#-:-Me2CpFy7QZs8G3q8Sk2:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67326#-:-MeWkknC8ktiZzOnsdRr:b-ydi9ay)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @nvanbenschoten and @rytaft)

___
*[pkg/sql/rowexec/joinreader_strategies.go, line 429 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67326#-Me20yd_5RmsmBvxeQWR:-Me23Dez6IQnZ8lAb4-y:byhqdhp) ([raw file](https://github.com/cockroachdb/cockroach/blob/64700a75d4f8f7cffe9146a9944e8421bc61e33a/pkg/sql/rowexec/joinreader_strategies.go#L429)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: why not call this `lookedUpRowIdx`?
</blockquote></details>

I went back and forth, but ultimately I left it; I think it's good here to emphasize strongly the link to the cointainer. Since this method deals with a single thing - a looked-up row - emphasizing that the id identifies it is less interesting.

**Pull request merged**
