### PR TITLE
import,backup: show redacted secrets in job UI

### PR DESCRIPTION
**Pull request by dt**
Previously the IMPORT and BACKUP jobs would hide all query parameters.
This gave some users / engineers the false sense that those secrets were
gone or irrecoverable from the job record, but any super-user with read
access to the system tables can extract the raw URLs, including the params
that include things like AWS_SECRET_ACCESS_KEY, from the raw job data.

This change replaces the blanket hiding of all params with targetted
redacting of just the values for sensitive params, replacing their value
with the word 'redacted'. This is hoped to make is clearer what is going
on -- that the params are still there and we're just not showing the value.

Release note (general change): Jobs show the parameters used for connecting to external storage in SHOW JOBS and the Jobs UI page, with only the values of parameters classified as secrets redacted.

While I'm here: remove duplicate filename prefix in some IMPORT error messages (see first commit for details).

### CODE REVIEW

**Review by miretskiy — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44737)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl and @miretskiy)

**Review by aaron-crl — APPROVED** [review]
LGTM

**Comment by dt** [comment]
Added changefeeds, which also include some secret params in their URIs that _are not_ cloud URIs (and this the `cloud` package doesn't know about them) so added an extra-params-to-scrub argument to the helper as well. RFAL (and cc'ed @ajwerner for the changefeed side)

**Review by ajwerner — COMMENTED** [review]
CDC stuff :lgtm: 

> Reviewed 3 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44737#-:-M-Lk6h2Dp8QTNm76ENH:brdapd1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aaron-crl, @ajwerner, and @miretskiy)

**Pull request merged**
