### PR TITLE
workload: jitter the teardown of connections to prevent thundering herd

### PR DESCRIPTION
**Pull request by sean-**
This change upgrades workload's use of pgx from v4 to v5 in order to allow jittering the teardown of connections.  This change sets a max connection age of 5min and jitters the teardown by 30s.  Upgrading to pgx v5 also adds non-blocking pgxpool connection acquisition.

workload: add flags to manage the age and lifecycle of connection pool

Add flags to all workload types to specify:

* the max connection age: `--max-conn-lifetime duration`
* the max connection age jitter: `--max-conn-lifetime-jitter duration`
* the max connection idle time: `--max-conn-idle-time duration`
* the connection health check interval: `--conn-healthcheck-period duration`
* the min number of connections in the pool: `--min-conns int`

workload: add support for remaining pgx query modes

Add support for pgx.QueryExecModeCacheDescribe and pgx.QueryExecModeDescribeExec.  Previously, only three of the five query modes were available.

workload: fix race condition when recording histogram data

Release note (cli change): workload jitters teardown of connections to prevent thundering herd impacting P99 latency results.

Release note (cli change): workload utility now has flags to tune the connection pool used for testing.  See `--conn-healthcheck-period`, `--min-conns`, and the `--max-conn-*` flags for details.

Release note (cli change): workload now supports every [PostgreSQL query mode](https://github.com/jackc/pgx/blob/fa5fbed497bc75acee05c1667a8760ce0d634cba/conn.go#L167-L182) available via the underlying pgx driver.

### CODE REVIEW

**Review by sean- — COMMENTED** [review]
Reworking https://github.com/cockroachdb/cockroach/pull/98689 plus fixes for broken nightlies in this PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100533#-:-NS8Cw1v7KQlDEgK92cb:b-co4ew2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sean-)

___
*[`pkg/workload/tpcc/tpcc.go` line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100533#-NS8CdXDDA_2VzMFobAb:-NS8CdXDDA_2VzMFobAc:bldoxx2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b199ae5f0b94b358b2eb845b4095d413989e904d/pkg/workload/tpcc/tpcc.go#L174)):*
> ```Go
> 			`idle-conns`:               {RuntimeOnly: true},
> 			`local-warehouses`:         {RuntimeOnly: true},
> 			`max-conn-idle-time`:       {RuntimeOnly: true},
> ```

Registering meta flags was the required fix for https://github.com/cockroachdb/cockroach/issues/100018, FYI.

**Comment by srosenberg** [comment]
Full GCE nightly run: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/9507011?buildTab=tests

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100533)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs, @sean-, and @srosenberg)

___
*[`pkg/workload/pgx_helpers.go` line 332 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100533#-NSgcZpC19IoQFy2zKTg:-NSgcZpC19IoQFy2zKTh:b-wbbhrv) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb7a0cc6dbf50e83f7141551c590e51af03843c4/pkg/workload/pgx_helpers.go#L332)):*
> ```Go
> 
> 	warmupConns := make(chan *pgxpool.Conn, numWarmupConns)
> 	connsPerURL := distribute(numWarmupConns, len(m.Pools))
> ```

With the latest fix, this logic feels like it's taking an extra step by:
1. computing `numWarmupConns` from p.MaxConns
2. distributing numWarmupConns across pools
3. allocating up to min of (p.MaxConns, distribute(numWarmupConns))

Can we invert the logic and skip a step while also making this logic more understandable. I'm thinking something like:
```go
var warmupConnsPerPool []int
if numConns == 0 {
	warmupConnsPerPool = make([]int, len(m.Pools))
	for i, p := range m.Pools {
		warmupConnsPerPool[i] = int(p.Config().MaxConns)
	}
} else {
        // TODO: what if numConns is > p.Config().MaxConns?
	warmupConnsPerPool = distribute(numConns, len(m.Pools)
}

var numWarmupConns int
for _, n := range warmupConnsPerPool {
	numWarmupConns += n
}
warmupConns := make(chan *pgxpool.Conn, numWarmupConns)

for i, p := range m.Pools {
	p := p
	for k := 0; k < warmupConnsPerPool[i]; k++ {
		g.Go(func() error {
			conn, err := p.Acquire(warmupCtx)
			if err != nil {
				return err
			}
			warmupConns <- conn
			return nil
		})
	}
}
```

**Review by sean- — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100533)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten, @renatolabs, and @srosenberg)

___
*[`pkg/workload/pgx_helpers.go` line 332 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100533#-NSgcZpC19IoQFy2zKTg:-NSgr8Z8-d8P2Az_v5gM:bspek7z) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb7a0cc6dbf50e83f7141551c590e51af03843c4/pkg/workload/pgx_helpers.go#L332)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

With the latest fix, this logic feels like it's taking an extra step by:
1. computing `numWarmupConns` from p.MaxConns
2. distributing numWarmupConns across pools
3. allocating up to min of (p.MaxConns, distribute(numWarmupConns))

Can we invert the logic and skip a step while also making this logic more understandable. I'm thinking something like:
```go
var warmupConnsPerPool []int
if numConns == 0 {
	warmupConnsPerPool = make([]int, len(m.Pools))
	for i, p := range m.Pools {
		warmupConnsPerPool[i] = int(p.Config().MaxConns)
	}
} else {
        // TODO: what if numConns is > p.Config().MaxConns?
	warmupConnsPerPool = distribute(numConns, len(m.Pools)
}

var numWarmupConns int
for _, n := range warmupConnsPerPool {
	numWarmupConns += n
}
warmupConns := make(chan *pgxpool.Conn, numWarmupConns)

for i, p := range m.Pools {
	p := p
	for k := 0; k < warmupConnsPerPool[i]; k++ {
		g.Go(func() error {
			conn, err := p.Acquire(warmupCtx)
			if err != nil {
				return err
			}
			warmupConns <- conn
			return nil
		})
	}
}
```
</blockquote></details>

Good suggestion.  Updated.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100533#-:-NSgs-814CJk-mVR5V4b:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @renatolabs and @srosenberg)

**Pull request merged**
