### PR TITLE
sql/parser: Add array_{length, lower, upper} builtin functions

### PR DESCRIPTION
**Pull request by nvb**
Part of #10519.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10565)

### CODE REVIEW

**Comment by cuongdo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/builtins.go, line 1157 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10565#-KW9KCPAyp7FzfbM0Laz:-KW9KCPAyp7FzfbM0Lb-:b-fxshdc) ([raw file](https://github.com/cockroachdb/cockroach/blob/39a290f2ddf579e1a28d4470c2d2ac52b4d290d0/pkg/sql/parser/builtins.go#L1157)):*
> ```Go
> 				dimen := *args[1].(*DInt)
> 				// We do not currently support multi-dimensional arrays.
> 				if dimen != 1 || len(arr) == 0 {
> ```

Is this the right strategy to handle these cases? If `dimen != 1`. would it make more sense to return an error instead of failing silently? Also, if `len(arr) ==0`, should we just return `0`?

---

*[pkg/sql/parser/builtins.go, line 1175 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10565#-KW9KUQPWl58Pz3d_FMR:-KW9KUQPWl58Pz3d_FMS:bnj7hl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/39a290f2ddf579e1a28d4470c2d2ac52b4d290d0/pkg/sql/parser/builtins.go#L1175)):*
> ```Go
> 				// We do not currently support multi-dimensional arrays.
> 				if dimen != 1 || len(arr) == 0 {
> 					return DNull, nil
> ```

same as above

---

*[pkg/sql/parser/builtins.go, line 1192 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10565#-KW9KVJ9wlOvfV7V_S3-:-KW9KVJ9wlOvfV7V_S30:bnj7hl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/39a290f2ddf579e1a28d4470c2d2ac52b4d290d0/pkg/sql/parser/builtins.go#L1192)):*
> ```Go
> 				// We do not currently support multi-dimensional arrays.
> 				if dimen != 1 || len(arr) == 0 {
> 					return DNull, nil
> ```

same as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10565)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/builtins.go, line 1157 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10565#-KW9KCPAyp7FzfbM0Laz:-KW9O9Her0MG6gt66Pzk:b87z0op) ([raw file](https://github.com/cockroachdb/cockroach/blob/39a290f2ddf579e1a28d4470c2d2ac52b4d290d0/pkg/sql/parser/builtins.go#L1157)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary>
> Is this the right strategy to handle these cases? If `dimen != 1`. would it make more sense to return an error instead of failing silently? Also, if `len(arr) ==0`, should we just return `0`?
</details>
This behavior is identical to Postgres'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10565)*

**Comment by cuongdo** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10565#-:-KW9OtKfa0NzekqICxNN:bnfp4nl)*

**Comment by nvanbenschoten** [comment]
TFTR!

**Comment by jseldess** [comment]
Regenerated the functions docs to pick these up, but still need to add descriptions.

**Pull request merged**
