### PR TITLE
engineccl/mvcc: work around time-bound iterator bug

### LINKED ISSUE #32104: changefeedccl: occasional inconsistent performance on long-running tpcc-1000
If the cdc/w=1000/nodes=3/init=false roachtest is altered to run indefinitely instead of 2h, it will eventually see inconsistent performance.

Usually the latency between the latest changefeed-level resolved timestamp is 1-2s. Occasionally it will hit some badness and spike up to single-digit minutes. This can go on for several hours. I keep accidentally cutting the test short, so it's unclear if it ever recovers on it's own.

My first guess is that some range activity is happening (splits, rebalances) and this is causing the ExpertRequests to get slower.

### LINKED ISSUE #32799: changefeedccl: time-bound iterator and CDC in 2.1
There is an unresolved bug in time-bound iterator. It manifests as incorrectly seeing an unresolved intent (the bug is that deletion of the intent key is missed). All current ideas for fixing this are too scary to backport to 2.1, but changefeeds use them (via ExportRequest). See much more detail on the bug in #28358. We have a customer commitment for changefeeds in 2.1 so something has to be done here. Some possible options:

- (1) TBIs are a performance optimization, we could disable them. This is what we did in almost every use of them in crdb. Changefeeds and incremental backup (the two uses of ExportRequest) are the only remaining TBI uses in 2.1.
- (2) When an ExportRequest hits what appears to be an unresolved intent, double check with a normal (non-TBI) iterator.

### PR DESCRIPTION
**Pull request by danhhz**
For reasons described in #28358, a time-bound iterator will sometimes
see an unresolved intent where there is none. A normal iterator doesn't
have this problem, so we work around it in MVCCIncrementalIterator by
double checking all non-value keys. If the normal iterator has a
different value for the key, it's used instead. If the normal iterator
doesn't have that key, it's skipped.

This fixes both changefeeds and incremental backup.

Closes #32104
Closes #32799

Release note (bug fix): `CHANGEFEED`s and incremental `BACKUP`s no
longer indefinitely hang under an infrequent condition.

### CODE REVIEW

**Comment by danhhz** [comment]
@benesch still figuring out how to write tests for this. first wanted to check that this is even fixing it at the right level. thoughts?

**Comment by benesch** [comment]
Yeah, this looks like the right level! Are you planning to backport this to 2.1?

**Comment by danhhz** [comment]
Yup!

**Comment by benesch** [comment]
👍 sounds good. And then we can hopefully rip this out if we come up with a more clever solution within RocksDB.

**Comment by danhhz** [comment]
Cleaned it up a bit and added some tests. Should be ready to go. Give this one an extra thorough look if you can.

**Review by benesch — COMMENTED** [review]
:lgtm_strong:

I reviewed this closely, but if you want extra scrutiny perhaps @bdarnell should take a look too?

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32909#-:-LTU32JH9h0qsBi4-ty-:b-epi22a)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/ccl/storageccl/engineccl/mvcc.go, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32909#-LTU2P5QDHbSJjBP9Gqz:-LTU2P5QDHbSJjBP9Gr-:bxiu4z5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2de146d7c8f655f2c4236615f25b8c2f366d0e58/pkg/ccl/storageccl/engineccl/mvcc.go#L54)):*
> ```Go
> 	iter engine.Iterator
> 
> 	// fields used for a workaround for a bug in the time-bound iterator
> ```

// ... time-bound iterator (#28358)
___
*[pkg/ccl/storageccl/engineccl/mvcc_test.go, line 543 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32909#-LTU5o0a23lNqbmqkTuL:-LTU5o0a23lNqbmqkTuM:bpkbb4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/2de146d7c8f655f2c4236615f25b8c2f366d0e58/pkg/ccl/storageccl/engineccl/mvcc_test.go#L543)):*
> ```Go
> 	// kA -> (intent) [NB this overwrites the intent deletion]
> 	// kA:3 -> vA3
> 	// kA _> vA2
> ```

Should this be `kA:2 -> vA2`?
___
*[pkg/ccl/storageccl/engineccl/mvcc_test.go, line 554 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32909#-LTU3ZKn1Rr4azgXtjpf:-LTU3ZKn1Rr4azgXtjpg:b-i2q2wd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2de146d7c8f655f2c4236615f25b8c2f366d0e58/pkg/ccl/storageccl/engineccl/mvcc_test.go#L554)):*
> ```Go
> 	require.NoError(t, engine.MVCCPut(ctx, db, nil, kA, ts2, vA2, nil))
> 	require.NoError(t, engine.MVCCPut(ctx, db, nil, kA, txnA3.Timestamp, vA3, txnA3))
> 	require.NoError(t, db.Flush())
> ```

:heart: testify
___
*[pkg/ccl/storageccl/engineccl/mvcc_test.go, line 593 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32909#-LTU7b_o9geCDIIeWaqp:-LTU7b_o9geCDIIeWaqq:b-66hnt2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2de146d7c8f655f2c4236615f25b8c2f366d0e58/pkg/ccl/storageccl/engineccl/mvcc_test.go#L593)):*
> ```Go
> 	// Sanity check that we see the still unresolved intent for kC ts1.
> 	_, err = slurpKVs(db, kC, ts0, ts1)
> 	require.EqualError(t, err, `conflicting intents on "kC"`)
> ```

Can you also sanity check that you see the unresolved intent if you `slurpKVs(db, kC, ts2, ts3)` (i.e., scanning at a higher timestamp than the intent is written)? Just to lock in the behavior until #32421 goes back in.

**Comment by danhhz** [comment]
Good idea. @bdarnell would you mind taking a look at this as well?

**Review by bdarnell — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32909)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by benesch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32909)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/ccl/storageccl/engineccl/mvcc_test.go, line 593 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32909#-LTU7b_o9geCDIIeWaqp:-LTcygHr9HDUnz6vkiE7:bwx8bbm) ([raw file](https://github.com/cockroachdb/cockroach/blob/2de146d7c8f655f2c4236615f25b8c2f366d0e58/pkg/ccl/storageccl/engineccl/mvcc_test.go#L593)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Can you also sanity check that you see the unresolved intent if you `slurpKVs(db, kC, ts2, ts3)` (i.e., scanning at a higher timestamp than the intent is written)? Just to lock in the behavior until #32421 goes back in.
</blockquote></details>

Never mind. I'm totally mistaken on this point. Ignore this suggesiton.

**Review by danhhz — COMMENTED** [review]
Thanks for the reviews!

bors r=bdarnell,benesch

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32909#-:-LTd4kU42SQFBIzHofxk:bqn5l7f)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/ccl/storageccl/engineccl/mvcc.go, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32909#-LTU2P5QDHbSJjBP9Gqz:-LTZry6LA8ymqn_aPKY2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2de146d7c8f655f2c4236615f25b8c2f366d0e58/pkg/ccl/storageccl/engineccl/mvcc.go#L54)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

// ... time-bound iterator (#28358)
</blockquote></details>

Done.
___
*[pkg/ccl/storageccl/engineccl/mvcc_test.go, line 543 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32909#-LTU5o0a23lNqbmqkTuL:-LTZs3m4C92qhTKt-OPz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2de146d7c8f655f2c4236615f25b8c2f366d0e58/pkg/ccl/storageccl/engineccl/mvcc_test.go#L543)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Should this be `kA:2 -> vA2`?
</blockquote></details>

Done.
___
*[pkg/ccl/storageccl/engineccl/mvcc_test.go, line 554 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32909#-LTU3ZKn1Rr4azgXtjpf:-LTZs967BVJnfo85LVL1:b-j1we20) ([raw file](https://github.com/cockroachdb/cockroach/blob/2de146d7c8f655f2c4236615f25b8c2f366d0e58/pkg/ccl/storageccl/engineccl/mvcc_test.go#L554)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

:heart: testify
</blockquote></details>

:raised_hands:

**Pull request merged**
