### PR TITLE
cmd/smithcmp: add vectorized test

### PR DESCRIPTION
**Pull request by madelynnblue**
Test vectorized on vs off.

Also many quality of life improvements for smithcmp.

Release note: None

### CODE REVIEW

**Review by solongordon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39126)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @mjibson, and @solongordon)

___
*[pkg/cmd/smithcmp/vec.toml, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39126#-Ll208lO3G82vrLjeCum:-Ll208lO3G82vrLjeCun:byxfjnh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b5a93cf632b6917e0e7e41f84b53936d6a6e73e/pkg/cmd/smithcmp/vec.toml#L20)):*
> ```TOML
>         substring('00000000-0000-0000-0000-' || g::TEXT || '00000000000', 1, 36)::UUID AS _uuid,
>         '0.0.0.0'::INET + g AS _inet,
>         g::TEXT::JSONB AS _jsonb
> ```

Should we comment out the types that vectorized can't handle yet to increase the chances of queries actually going through the vec engine? (timestamp, timestamptz, interval, uuid, inet, jsonb)

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39126)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @solongordon)

___
*[pkg/cmd/smithcmp/vec.toml, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39126#-Ll208lO3G82vrLjeCum:-LlVXyXn92xIyuIrrr6P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b5a93cf632b6917e0e7e41f84b53936d6a6e73e/pkg/cmd/smithcmp/vec.toml#L20)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Should we comment out the types that vectorized can't handle yet to increase the chances of queries actually going through the vec engine? (timestamp, timestamptz, interval, uuid, inet, jsonb)
</blockquote></details>

Done.

**Review by solongordon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39126)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @mjibson)

___
*[pkg/cmd/smithcmp/vec.toml, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39126#-Ll208lO3G82vrLjeCum:-LlYNNpCCFTrUu-F1yIX:b-lfhwwm) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b5a93cf632b6917e0e7e41f84b53936d6a6e73e/pkg/cmd/smithcmp/vec.toml#L20)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Cool. Whitespace/indentation looks a little weird though.

**Pull request merged**
