### PR TITLE
distsql: eagerly cancel remote flows on a query error

### LINKED ISSUE #64916: sql: remote flows do not cancel promptly upon query cancellation
Setup:

1. create 4-node roachprod cluster
2. import tpch (`workload init tpch --data-loader=import`)
3. run querybench with a simple distsql query (`select count(*) from tpch.lineitem`) at concurrency 1024 (`workload run querybench --query-file=queries --tolerate-errors --verbose`)
4. cancel workload

Observe custom chart of queued and active flows:

image
image

In this chart, the load was cancelled between 14:53 and 14:54, but it took over 5 minutes for the cluster to stop processing remote flows.

I would expect that when the load is cancelled, the remote nodes should be able to drop their flows on the floor very quickly.

### PR DESCRIPTION
**Pull request by yuzefovich**
**flowinfra: clarify Flow interface a bit**

The comments around the interface usage are now in line with the code
(this is a follow up to removal of RunSyncFlow RPC a few weeks back).

Release note: None

**distsql: eagerly cancel remote flows on a query error**

This commit introduce another RPC to the DistSQLServer interface to
cancel scheduled flows (i.e. those setup via SetupFlow RPC) when the
relevant queries error out on the gateway. Previously, in such cases the
dead flows would be started on the remote nodes only to realize that the
consumer is gone and shut themselves down. However, this required
performing FlowStream RPC from the remote nodes. This commit fixes the
issue by eagerly canceling such abandoned flows.

This behavior is especially useful if the cluster is overwhelmed with
DistSQL flows and is hitting the limit (500 by default per node) on the
number active flows at once. If the load keeps on hammering the cluster,
and more and more flows will be queued up on the remote nodes, yet the
local (from the perspective of the gateway) flow errors out (e.g.
because it timed out waiting for the remote flows to connect), all those
queued up flows will be dead before they start.

Fixes: #64916.

Release note (sql change): The remote DistSQL flows are now eagerly
canceled if they were queued up and the query was canceled.

### CODE REVIEW

**Comment by yuzefovich** [comment]
I think this is RFAL.

I added a couple of unit tests for some components involved but can't wrap my head around on how to add an "end-to-end" test. I manually verified that it behaves as expected on an actual cluster [link](https://github.com/cockroachdb/cockroach/issues/64916#issuecomment-840918381) though, and the change seems simple enough, so it might be not needed to spend too much time on coming up with that test. Curious whether you have suggestions/thoughts.

**Comment by yuzefovich** [comment]
Friendly ping @RaduBerinde @jordanlewis

**Review by mgartner — APPROVED** [review]
:lgtm: But definitely deserves a look from someone more familiar.

> Reviewed 7 of 7 files at r1, 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65073#-:-MaV-RG85PnWi8gnmh7G:byzedpi)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

**Review by jordanlewis — COMMENTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65073)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @yuzefovich)

___
*[pkg/sql/distsql_running.go, line 141 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65073#-MaUsmtz411MFidLpNMx:-MaUsmtz411MFidLpNMy:bebpdi5) ([raw file](https://github.com/cockroachdb/cockroach/blob/afce04fa3825889894691d3b2c4bbfcbd37128e1/pkg/sql/distsql_running.go#L141)):*
> ```Go
> 						// There are no flows to cancel at the moment.
> 						select {
> 						case <-stopChan:
> ```

the duplicate case seems odd. I think it would be more elegant to use a ticker (https://golang.org/pkg/time/#NewTicker) and listen on either that or stopChan in the main select.

actually I am also wondering whether we should be using a condition variable or channel for signaling here, instead of polling at all.
___
*[pkg/sql/distsql_running.go, line 201 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65073#-MaV48V34F5-y46Jtwfv:-MaV48V34F5-y46Jtwfw:bq3di28) ([raw file](https://github.com/cockroachdb/cockroach/blob/afce04fa3825889894691d3b2c4bbfcbd37128e1/pkg/sql/distsql_running.go#L201)):*
> ```Go
> 	}
> 	nodeID := c.mu.deadFlows[0].nodeID
> 	c.mu.deadFlows = c.mu.deadFlows[1:]
> ```

clear [0] before slicing.
___
*[pkg/sql/execinfrapb/api.proto, line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65073#-MaV4RHDEtDcLFkZSqwY:-MaV4RHDEtDcLFkZSqwZ:be25vk1) ([raw file](https://github.com/cockroachdb/cockroach/blob/afce04fa3825889894691d3b2c4bbfcbd37128e1/pkg/sql/execinfrapb/api.proto#L126)):*
> ```protobuf
> }
> 
> message CancelDeadFlowsRequest {
> ```

add documentation for the contract of the message.

**Review by yuzefovich — COMMENTED** [review]
I still haven't added an integration test, will take a stab at it tomorrow.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65073#-:-MaWbk5d169y283J8k_w:berwnqp)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @mgartner, and @RaduBerinde)

___
*[pkg/sql/distsql_running.go, line 141 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65073#-MaUsmtz411MFidLpNMx:-MaW_AmY84ll92FYg9QR:b-adlmlk) ([raw file](https://github.com/cockroachdb/cockroach/blob/afce04fa3825889894691d3b2c4bbfcbd37128e1/pkg/sql/distsql_running.go#L141)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

the duplicate case seems odd. I think it would be more elegant to use a ticker (https://golang.org/pkg/time/#NewTicker) and listen on either that or stopChan in the main select.

actually I am also wondering whether we should be using a condition variable or channel for signaling here, instead of polling at all.
</blockquote></details>

Good point, refactored using a buffered channel.
___
*[pkg/sql/distsql_running.go, line 201 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65073#-MaV48V34F5-y46Jtwfv:-MaWRJlB1raLGG1XJv_v:bauz41y) ([raw file](https://github.com/cockroachdb/cockroach/blob/afce04fa3825889894691d3b2c4bbfcbd37128e1/pkg/sql/distsql_running.go#L201)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

clear [0] before slicing.
</blockquote></details>

Good point. I refactored to use `ring.Buffer` instead which does clear the element properly when it is removed.
___
*[pkg/sql/execinfrapb/api.proto, line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65073#-MaV4RHDEtDcLFkZSqwY:-MaWUCOI7cmnAcrWprzJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/afce04fa3825889894691d3b2c4bbfcbd37128e1/pkg/sql/execinfrapb/api.proto#L126)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

add documentation for the contract of the message.
</blockquote></details>

Done.

**Review by yuzefovich — COMMENTED** [review]
Added an integration test. I think we now we have good test coverage. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65073#-:-Ma_nusr6JPfvLmt5mOY:bnn7owr)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @mgartner, and @RaduBerinde)

**Comment by yuzefovich** [comment]
@jordanlewis @RaduBerinde friendly ping on this.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65073)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/distsql_running.go, line 141 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65073#-MaqEl1k4ir7mC7yF37M:-MaqEl1k4ir7mC7yF37N:bq0gvnw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee281642d7c0662f2f4a724cd6c2327c54c46aa7/pkg/sql/distsql_running.go#L141)):*
> ```Go
> 					if req == nil {
> 						// There are no flows to cancel at the moment. This
> 						// shouldn't really happen.
> ```

seems like it could happen since we always schedule at least `numCancellingWorkers` worth of pushes to this channel, no? even if there's just 1 remote node with flows.
___
*[pkg/sql/distsql_running.go, line 180 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65073#-MaqDz4g4olMi-DblnLP:-MaqDz4g4olMi-DblnLQ:be1ghhl) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee281642d7c0662f2f4a724cd6c2327c54c46aa7/pkg/sql/distsql_running.go#L180)):*
> ```Go
> 		syncutil.Mutex
> 		// deadFlows is a ring of pointers to deadFlowsOnNode objects.
> 		deadFlows ring.Buffer
> ```

nit: should we call this `deadFlowsByNode` perhaps? it sounds more like a big buffer of flow ids, until you read more deeply.
___
*[pkg/sql/distsql_running.go, line 476 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65073#-MaqDbe23QG-JMk7LJNM:-MaqDbe36Z7DdWmrevR0:b-z1vlti) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee281642d7c0662f2f4a724cd6c2327c54c46aa7/pkg/sql/distsql_running.go#L476)):*
> ```Go
> 				// but it'll slowdown the happy case - by introducing additional
> 				// tracking.
> 				dsp.cancelFlowsCoordinator.addFlowsToCancel(flows)
> ```

shouldn't we also be calling this in the case of an ordinary query cancellation? or does this path get hit for ordinary query cancellations? I'm thinking of the case where a query is cancelled but its remote flows haven't gotten picked up by workers yet.
___
*[pkg/sql/flowinfra/flow_scheduler.go, line 197 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65073#-MaqGVFP9ar1tqzV-ZNq:-MaqGVFP9ar1tqzV-ZNr:bq40l0z) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee281642d7c0662f2f4a724cd6c2327c54c46aa7/pkg/sql/flowinfra/flow_scheduler.go#L197)):*
> ```Go
> 			break
> 		}
> 		fs.mu.queue.Remove(e)
> ```

I think this "queue" has a slightly more efficient method for doing what you are doing, since it's doubly linked. Use the `e.Next()` method to iterate through the list, and use `queue.Remove()` once you find entries. I guess it's still O(n) but the constants are better since you only have to edit the list when you find matches, not for all entries.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65073)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @mgartner, and @RaduBerinde)

___
*[pkg/sql/distsql_running.go, line 141 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65073#-MaqEl1k4ir7mC7yF37M:-MaqcO7v-WQNNF-wUNgd:bpeialv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee281642d7c0662f2f4a724cd6c2327c54c46aa7/pkg/sql/distsql_running.go#L141)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

seems like it could happen since we always schedule at least `numCancellingWorkers` worth of pushes to this channel, no? even if there's just 1 remote node with flows.
</blockquote></details>

No, we push `min(numCancellingWorkers, len(deadFlowsByNode))` number of times, so this scenario is not what the comment is about.

The comment is concerned about the following extremely unlikely scenario:
- there is currently one flow to cancel
- worker 1 receives from `workerWait` channel and goes to sleep, before calling `getFlowsToCancel`
- another query errors out, and it wants to cancel a flow on the same node that we have in the CancelFlowsCoordinator, thus the queue still has only one item
- however, we send another notification on `workerWait` channel
- worker 2 receives from the channel and picks up that single item from the queue
- worker 1 now wakes up to find no flows to cancel.

It's like an extreme starvation of worker 1 goroutine.

However, I think that this should be quite rare and that in general the current solution should work well because we're doing reasonable number of non-blocking sends on the buffering channel. Non-blocking aspect allows us to make `addFlowsToCancel` non-blocking as a whole (modulo the lock acquisition which we cannot go around); the buffer in the channel allows us to keep the workers as busy as they can be. The fact that we don't send more than the length of `deadFlowsByNode` times makes sure that when workers wake up, they also have work. Occasional times when workers wake up to find no work should be rare and shouldn't have much influence on the performance as a whole.
___
*[pkg/sql/distsql_running.go, line 180 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65073#-MaqDz4g4olMi-DblnLP:-MaqY3hT78U-TbxqVkPm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee281642d7c0662f2f4a724cd6c2327c54c46aa7/pkg/sql/distsql_running.go#L180)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: should we call this `deadFlowsByNode` perhaps? it sounds more like a big buffer of flow ids, until you read more deeply.
</blockquote></details>

Done.
___
*[pkg/sql/distsql_running.go, line 476 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65073#-MaqDbe23QG-JMk7LJNM:-MaqYXZZBenFuYsjiXna:birofln) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee281642d7c0662f2f4a724cd6c2327c54c46aa7/pkg/sql/distsql_running.go#L476)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

shouldn't we also be calling this in the case of an ordinary query cancellation? or does this path get hit for ordinary query cancellations? I'm thinking of the case where a query is cancelled but its remote flows haven't gotten picked up by workers yet.
</blockquote></details>

I believe this path will get hit in all cases when we have performed `SetupFlow` RPCs (they happen in `dsp.setupFlows` call below) and when any error occurs on the gateway.

In particular, if the query is canceled (say via `CANCEL QUERY query_id`), the cancellation is handled by canceling the context of the flow on the gateway; the context cancellation error will eventually be propagated to the `DistSQLReceiver` (which is `recv` in this context) via the metadata path, and the receiver will set the error on the result writer. This is exactly the object we're checking here.
___
*[pkg/sql/flowinfra/flow_scheduler.go, line 197 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65073#-MaqGVFP9ar1tqzV-ZNq:-MaqcF5OBlovZRF7PeVN:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee281642d7c0662f2f4a724cd6c2327c54c46aa7/pkg/sql/flowinfra/flow_scheduler.go#L197)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think this "queue" has a slightly more efficient method for doing what you are doing, since it's doubly linked. Use the `e.Next()` method to iterate through the list, and use `queue.Remove()` once you find entries. I guess it's still O(n) but the constants are better since you only have to edit the list when you find matches, not for all entries.
</blockquote></details>

Good point, done.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65073)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @mgartner, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/distsql_running.go, line 141 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65073#-MaqEl1k4ir7mC7yF37M:-MasfXYw69OfK3-obJx4:bx90guj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee281642d7c0662f2f4a724cd6c2327c54c46aa7/pkg/sql/distsql_running.go#L141)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

No, we push `min(numCancellingWorkers, len(deadFlowsByNode))` number of times, so this scenario is not what the comment is about.

The comment is concerned about the following extremely unlikely scenario:
- there is currently one flow to cancel
- worker 1 receives from `workerWait` channel and goes to sleep, before calling `getFlowsToCancel`
- another query errors out, and it wants to cancel a flow on the same node that we have in the CancelFlowsCoordinator, thus the queue still has only one item
- however, we send another notification on `workerWait` channel
- worker 2 receives from the channel and picks up that single item from the queue
- worker 1 now wakes up to find no flows to cancel.

It's like an extreme starvation of worker 1 goroutine.

However, I think that this should be quite rare and that in general the current solution should work well because we're doing reasonable number of non-blocking sends on the buffering channel. Non-blocking aspect allows us to make `addFlowsToCancel` non-blocking as a whole (modulo the lock acquisition which we cannot go around); the buffer in the channel allows us to keep the workers as busy as they can be. The fact that we don't send more than the length of `deadFlowsByNode` times makes sure that when workers wake up, they also have work. Occasional times when workers wake up to find no work should be rare and shouldn't have much influence on the performance as a whole.
</blockquote></details>

I see. Made another comment below about the # of pushes.
___
*[pkg/sql/distsql_running.go, line 241 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65073#-MasfeRCAGQtRjsH7mcg:-MasfeRCAGQtRjsH7mch:bklyc84) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee281642d7c0662f2f4a724cd6c2327c54c46aa7/pkg/sql/distsql_running.go#L241)):*
> ```Go
> 	numWorkersToWakeUp := numCancelingWorkers
> 	if numWorkersToWakeUp < c.mu.deadFlows.Len() {
> 		numWorkersToWakeUp = c.mu.deadFlows.Len()
> ```

Above you said you intended to do min(len(flows), numWorkers), but if len(flows) is less than numWorkers, we always pick numWorkers, right? This is why I was confused.
___
*[pkg/sql/distsql_running.go, line 476 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65073#-MaqDbe23QG-JMk7LJNM:-MasgHpq6I-pL1j732qK:btmyujz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee281642d7c0662f2f4a724cd6c2327c54c46aa7/pkg/sql/distsql_running.go#L476)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I believe this path will get hit in all cases when we have performed `SetupFlow` RPCs (they happen in `dsp.setupFlows` call below) and when any error occurs on the gateway.

In particular, if the query is canceled (say via `CANCEL QUERY query_id`), the cancellation is handled by canceling the context of the flow on the gateway; the context cancellation error will eventually be propagated to the `DistSQLReceiver` (which is `recv` in this context) via the metadata path, and the receiver will set the error on the result writer. This is exactly the object we're checking here.
</blockquote></details>

Right, but don't we have the same problem here where we'll only notice this once we start pushing to the receiver?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65073)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @mgartner, and @RaduBerinde)

___
*[pkg/sql/distsql_running.go, line 141 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65073#-MaqEl1k4ir7mC7yF37M:-Mb4Ttz8-2ZfzMs99f49:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee281642d7c0662f2f4a724cd6c2327c54c46aa7/pkg/sql/distsql_running.go#L141)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I see. Made another comment below about the # of pushes.
</blockquote></details>

Done.
___
*[pkg/sql/distsql_running.go, line 241 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65073#-MasfeRCAGQtRjsH7mcg:-Mb4UHFpBuhxh4IRl-3_:bvv4zsr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee281642d7c0662f2f4a724cd6c2327c54c46aa7/pkg/sql/distsql_running.go#L241)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Above you said you intended to do min(len(flows), numWorkers), but if len(flows) is less than numWorkers, we always pick numWorkers, right? This is why I was confused.
</blockquote></details>

D'oh, good catch, fixed.
___
*[pkg/sql/distsql_running.go, line 476 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65073#-MaqDbe23QG-JMk7LJNM:-Mb4VYQP-wKrgRsKqvn8:bp8uvue) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee281642d7c0662f2f4a724cd6c2327c54c46aa7/pkg/sql/distsql_running.go#L476)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Right, but don't we have the same problem here where we'll only notice this once we start pushing to the receiver?
</blockquote></details>

I agree with you partially that this is not the absolutely perfect place to perform this dead flows cancellation (the ideal place would be calling this function as part of query cancellation - which is cancelling the context), but this place comes very close to that.

In a reasonable scenario the context cancellation should be detected fairly quickly by the flow on the gateway node, so the metadata object containing an error should be propagated very quickly too which should shutdown the whole physical plan; at that point, we will perform the cleanup of the dead flows.

I added a third WIP commit that makes this dead flows cleanup as early as possible, but I don't like it. I don't think it gives us much benefit, but does introduce the breakage of abstractions and seems to introduce unnecessary complications. Do you have a particular example in mind that would justify merging something like that?

**Review by jordanlewis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65073)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @mgartner, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/distsql_running.go, line 476 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65073#-MaqDbe23QG-JMk7LJNM:-Mb9c2780hAQwED8dZLv:b-v4ncwm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee281642d7c0662f2f4a724cd6c2327c54c46aa7/pkg/sql/distsql_running.go#L476)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I agree with you partially that this is not the absolutely perfect place to perform this dead flows cancellation (the ideal place would be calling this function as part of query cancellation - which is cancelling the context), but this place comes very close to that.

In a reasonable scenario the context cancellation should be detected fairly quickly by the flow on the gateway node, so the metadata object containing an error should be propagated very quickly too which should shutdown the whole physical plan; at that point, we will perform the cleanup of the dead flows.

I added a third WIP commit that makes this dead flows cleanup as early as possible, but I don't like it. I don't think it gives us much benefit, but does introduce the breakage of abstractions and seems to introduce unnecessary complications. Do you have a particular example in mind that would justify merging something like that?
</blockquote></details>

I think I was confused - `CANCEL QUERY` will also cause all of the gateway's contexts to be cancelled, including things like random contexts deep in the tree. And those errors will still propagate to this spot "quickly", right? Without having to wait for a moment at which we've got rows ready to write to the receiver.

**Review by jordanlewis — COMMENTED** [review]
:lgtm: (probably WIP is unnecessary, see comment)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65073#-:-Mb9cSac6tGw1Uzk30fy:b-fmei9b)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @mgartner, @RaduBerinde, and @yuzefovich)

**Review by yuzefovich — COMMENTED** [review]
Removed the WIP commit. Also rebased to fix merge conflicts.

TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65073#-:-Mb9qnN05Ty4HRNYuLqn:b6o7puq)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @jordanlewis, @mgartner, and @RaduBerinde)

___
*[pkg/sql/distsql_running.go, line 476 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65073#-MaqDbe23QG-JMk7LJNM:-Mb9q7DZC3KE5ev63W6I:b-iixdqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee281642d7c0662f2f4a724cd6c2327c54c46aa7/pkg/sql/distsql_running.go#L476)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think I was confused - `CANCEL QUERY` will also cause all of the gateway's contexts to be cancelled, including things like random contexts deep in the tree. And those errors will still propagate to this spot "quickly", right? Without having to wait for a moment at which we've got rows ready to write to the receiver.
</blockquote></details>

Yeah, exactly. `CANCEL QUERY` cancels the context which is a parent of the flow context of the local flow on the gateway. This should result in an interrupt of whatever is happening in the gateway flow and will be propagated as a meta object containing a context cancellation error. That error will be set on the `DistSQLReceiver`, but there is no need to wait for any actual rows pushed into it because the `DistSQLReceiver` will have `ConsumerClosed` state once it receives the error. As long as all components are properly listening for context cancelation, this spot in the code should be reached pretty quickly.

**Comment by yuzefovich** [comment]
A note to myself to include #66301 when backporting this.

**Pull request merged**
