### PR TITLE
distsql: add support for zeroNode

### PR DESCRIPTION
**Pull request by yuzefovich**
Adds support for zeroNode in DistSQL
by planning an empty values processor
on the gateway node.

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
I think this change should not affect this logic:
https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/exec_util.go#L470
Am I correct?

Also, I'm not sure what is the best way to test this change.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27653#-:-LHdV-3N3XUHT-NxWDOR:b-a4r3cv)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by RaduBerinde — COMMENTED** [review]
Correct, that check looks fine.

You can add a test or two to `sql/logictest/testdata/planner_test/distsql_auto_mode` which would verify that the node is supported (otherwise `EXPLAIN (DISTSQL)` errors out).

:lgtm: modulo some minor comments

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27653#-:-LHdWTVwDXursXzntM1R:bx29n8e)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsql_physical_planner.go, line 423 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27653#-LHdVF2uDVZ7xoEIJDfI:-LHdVF2uDVZ7xoEIJDfJ:b-gfzmri) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc5c2c60c27d8e5a2271fe765c9b4b16c360a169/pkg/sql/distsql_physical_planner.go#L423)):*
> ```Go
> 
> 	case *zeroNode:
> 		return shouldDistribute, nil
> ```

I would make this `canDistribute`, and same for `valuesNode`. No idea why it was `shouldDistribute`.
___
*[pkg/sql/distsql_physical_planner.go, line 2656 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27653#-LHdVrlB9EnsuIzD9EsD:-LHdVrlB9EnsuIzD9EsE:bjoe1gl) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc5c2c60c27d8e5a2271fe765c9b4b16c360a169/pkg/sql/distsql_physical_planner.go#L2656)):*
> ```Go
> 	columns := len(n.columns)
> 
> 	s := distsqlrun.ValuesCoreSpec{
> ```

[nit] Instead of copying this code, I would extract a function from createPlanForValues, something like `createValuesPlan` which takes `NumRows, RawBytes` as arguments (along with `ResultColumns` and whatever else is needed)
___
*[pkg/sql/distsql_physical_planner.go, line 2676 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27653#-LHdVeq29JrzWZ84QQnB:-LHdVeq29JrzWZ84QQnC:b-saagu8) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc5c2c60c27d8e5a2271fe765c9b4b16c360a169/pkg/sql/distsql_physical_planner.go#L2676)):*
> ```Go
> 			Spec: distsqlrun.ProcessorSpec{
> 				Core:   distsqlrun.ProcessorCoreUnion{Values: &s},
> 				Output: []distsqlrun.OutputRouterSpec{{Type: 0}},
> ```

[nit] use `distsqlrun.OutputRouterSpec_PASS_THROUGH` instead of 0 (same for the original code for values)

**Review by yuzefovich — COMMENTED** [review]
Thanks for a quick review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27653#-:-LHdniiL9sHRI9tRPIIj:bsvb26m)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsql_physical_planner.go, line 423 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27653#-LHdVF2uDVZ7xoEIJDfI:-LHdYsLeD60-zggFZ_zv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc5c2c60c27d8e5a2271fe765c9b4b16c360a169/pkg/sql/distsql_physical_planner.go#L423)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I would make this `canDistribute`, and same for `valuesNode`. No idea why it was `shouldDistribute`.
</blockquote></details>

Done.
___
*[pkg/sql/distsql_physical_planner.go, line 2656 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27653#-LHdVrlB9EnsuIzD9EsD:-LHdnd2t3ZKRUwXg2iZI:beeenuw) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc5c2c60c27d8e5a2271fe765c9b4b16c360a169/pkg/sql/distsql_physical_planner.go#L2656)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Instead of copying this code, I would extract a function from createPlanForValues, something like `createValuesPlan` which takes `NumRows, RawBytes` as arguments (along with `ResultColumns` and whatever else is needed)
</blockquote></details>

Done. Please take a quick look to confirm that I've done as you suggested.
___
*[pkg/sql/distsql_physical_planner.go, line 2676 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27653#-LHdVeq29JrzWZ84QQnB:-LHddQio8iK_hw0-_9ax:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc5c2c60c27d8e5a2271fe765c9b4b16c360a169/pkg/sql/distsql_physical_planner.go#L2676)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] use `distsqlrun.OutputRouterSpec_PASS_THROUGH` instead of 0 (same for the original code for values)
</blockquote></details>

Done.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27653)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsql_physical_planner.go, line 2166 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27653#-LHdpH5f7AvIcxOIb3Vz:-LHdpH5f7AvIcxOIb3W-:b-w4npyo) ([raw file](https://github.com/cockroachdb/cockroach/blob/791e87a404057b6389929c6d22beb7cdf49c43d6/pkg/sql/distsql_physical_planner.go#L2166)):*
> ```Go
> }
> 
> func (dsp *DistSQLPlanner) createValuesPlan(
> ```

[nit] function needs a comment, especially explaining how `n` is used
___
*[pkg/sql/distsql_physical_planner.go, line 2167 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27653#-LHdp3lQ9c7xO1Md7UpH:-LHdp3lQ9c7xO1Md7UpI:b-47xo96) ([raw file](https://github.com/cockroachdb/cockroach/blob/791e87a404057b6389929c6d22beb7cdf49c43d6/pkg/sql/distsql_physical_planner.go#L2167)):*
> ```Go
> 
> func (dsp *DistSQLPlanner) createValuesPlan(
> 	planCtx *planningCtx, n planNode, resultColumns sqlbase.ResultColumns, numRows int,
> ```

My suggestion was to compute `RawBytes` outside this function (just for the values case) and pass it as an argument. We should either do that, or loop until `Next` returns false and count the rows ourselves.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27653)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsql_physical_planner.go, line 2166 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27653#-LHdpH5f7AvIcxOIb3Vz:-LHe-XbzDF7zhyoxxnf7:bfpf6k0) ([raw file](https://github.com/cockroachdb/cockroach/blob/791e87a404057b6389929c6d22beb7cdf49c43d6/pkg/sql/distsql_physical_planner.go#L2166)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] function needs a comment, especially explaining how `n` is used
</blockquote></details>

Not sure what to say about `n` in the comment except that is being closed.
___
*[pkg/sql/distsql_physical_planner.go, line 2167 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27653#-LHdp3lQ9c7xO1Md7UpH:-LHe-U91-iOMTzOaw3PD:bzhouye) ([raw file](https://github.com/cockroachdb/cockroach/blob/791e87a404057b6389929c6d22beb7cdf49c43d6/pkg/sql/distsql_physical_planner.go#L2167)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

My suggestion was to compute `RawBytes` outside this function (just for the values case) and pass it as an argument. We should either do that, or loop until `Next` returns false and count the rows ourselves.
</blockquote></details>

Got it. Hope this version looks better.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27653)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsql_physical_planner.go, line 2166 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27653#-LHdpH5f7AvIcxOIb3Vz:-LHe41lt07KX5nTOMR_R:b-ibrhyt) ([raw file](https://github.com/cockroachdb/cockroach/blob/791e87a404057b6389929c6d22beb7cdf49c43d6/pkg/sql/distsql_physical_planner.go#L2166)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Not sure what to say about `n` in the comment except that is being closed.
</blockquote></details>

You can remove it now. It shouldn't be the responsibility of this function to `Close` the node (or even know about it). The Close is not needed for zeroNode case at all, it's only related to the piece of code that calls `Next`. We should pass `types` to the function (we are calling `getTypesForPlanResult` in the values case).

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27653)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsql_physical_planner.go, line 2166 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27653#-LHdpH5f7AvIcxOIb3Vz:-LHeF8uL3dxYRQCEdOOc:bxpixfw) ([raw file](https://github.com/cockroachdb/cockroach/blob/791e87a404057b6389929c6d22beb7cdf49c43d6/pkg/sql/distsql_physical_planner.go#L2166)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

You can remove it now. It shouldn't be the responsibility of this function to `Close` the node (or even know about it). The Close is not needed for zeroNode case at all, it's only related to the piece of code that calls `Next`. We should pass `types` to the function (we are calling `getTypesForPlanResult` in the values case).
</blockquote></details>

I agree. I think now it should be good to merge.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27653)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsql_physical_planner.go, line 2189 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27653#-LHeLPWeCIOsp3n_zGqD:-LHeLPWeCIOsp3n_zGqE:b-2whtrr) ([raw file](https://github.com/cockroachdb/cockroach/blob/62e4f8e42af915ba73e05c303ad275a2a04c7f9f/pkg/sql/distsql_physical_planner.go#L2189)):*
> ```Go
> 		return physicalPlan{}, err
> 	}
> 	defer n.Close(planCtx.ctx)
> ```

You need to add this back

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27653)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsql_physical_planner.go, line 2189 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27653#-LHeLPWeCIOsp3n_zGqD:-LHeVIz71WU40NTE-PJI:b8w38uc) ([raw file](https://github.com/cockroachdb/cockroach/blob/62e4f8e42af915ba73e05c303ad275a2a04c7f9f/pkg/sql/distsql_physical_planner.go#L2189)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

You need to add this back
</blockquote></details>

Oops, my bad. Thanks for the catch!

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, 1 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27653#-:-LHedPVGCV08dPE2Ha9G:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by yuzefovich — COMMENTED** [review]
bors r+

Thanks for your reviews!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27653#-:-LHhSr8B3HSeDm840j-I:bwvqeyz)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
