### PR TITLE
storage,server: enable separated intents

### PR DESCRIPTION
**Pull request by sumeerbhola**
Separated intents are enabled by default, and the setting
is randomized on the testing path for testserver.go.

The intent resolution performance, which caused these
to be disabled, has been improved due to
https://github.com/cockroachdb/cockroach/pull/60622 and
https://github.com/cockroachdb/cockroach/pull/60698

TestLogic/aggregate is tweaked to reduce the number of
intents created, as explained in the TODO added where
the change was made.

Informs #41720

Release note (ops change): The default value of the
storage.transaction.separated_intents.enabled cluster
setting is changed to true.

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60731#-:-MTq_ng00epEQa6QLwqY:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/sql/logictest/testdata/logic_test/aggregate, line 903 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60731#-MTq_HidBjPzasfmhYHx:-MTq_HidBjPzasfmhYHy:b-bx7pv9) ([raw file](https://github.com/cockroachdb/cockroach/blob/40b65fff964a488ade3a6818b330c18d14331984/pkg/sql/logictest/testdata/logic_test/aggregate#L903)):*
> ```
> statement ok
> INSERT INTO mnop (m, n) SELECT i, (1e9 + i/2e4)::float FROM
>   generate_series(1, 5e3) AS i(i)
> ```

How much faster is this test with this change? I'm a little surprised that dropping from 20k to 5k would make that much of a difference. Does it prevent us from hitting `kv.transaction.max_intents_bytes` and condensing lock spans for the INSERT and then UPDATE statements? If that is the reason, you could confirm by bumping that cluster setting up to 1MB in this test.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60731)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal, @nvanbenschoten, and @petermattis)

___
*[pkg/sql/logictest/testdata/logic_test/aggregate, line 903 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60731#-MTq_HidBjPzasfmhYHx:-MTrASqr8rx-2C0u64RQ:b-9j7fiw) ([raw file](https://github.com/cockroachdb/cockroach/blob/40b65fff964a488ade3a6818b330c18d14331984/pkg/sql/logictest/testdata/logic_test/aggregate#L903)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

How much faster is this test with this change? I'm a little surprised that dropping from 20k to 5k would make that much of a difference. Does it prevent us from hitting `kv.transaction.max_intents_bytes` and condensing lock spans for the INSERT and then UPDATE statements? If that is the reason, you could confirm by bumping that cluster setting up to 1MB in this test.
</blockquote></details>

For some runs it did not do any ranged intent resolution and was many times faster. But now I've seen some timeouts even with this. So I've also adjusted the cluster setting as you indicated. I would have expected 4x faster with this change by reducing the number of deleted intent versions.

I plan to work on https://github.com/sumeerbhola/cockroach/commit/c116da0fe7a8fc21b913d25790bc49a49bd59789 tomorrow.

**Comment by sumeerbhola** [comment]
I am now stuck with these frequent `TestLogic` timeouts after 30min, like https://teamcity.cockroachdb.com/viewLog.html?buildId=2698668&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_Test
- I cannot reproduce them locally with parallel test running turned off. Both with and without separated intents, non-parallel TestLogic on my local machine finished in ~40min (parallel tests should be much faster). And profiling the full run does not suggest anything -- see attached profile which excludes anything beginning with `runtime` (the purple parts are Pebble).
- I can't run with parallel on my machine since it consumes > 27GB and starts swapping and liveness heartbeats starts failing.
- If I increase the `TESTTIMEOUT` to 60m in the Makefile, the test completes, but the tests tab shows `TestLogic` completing in 15min.

I'm looking for any suggestions on how to debug this.

Screen Shot 2021-02-20 at 10 17 51 AM

**Comment by knz** [comment]
> I can't run with parallel on my machine since it consumes > 27GB and starts swapping and liveness heartbeats starts failing.

Maybe you can run with `GOMAXPROCS=4` which should limit the amount of concurrency and reduce RAM usage.

**Review by sumeerbhola — COMMENTED** [review]
> Maybe you can run with GOMAXPROCS=4 which should limit the amount of concurrency and reduce RAM usage.

@knz Thanks for the suggestion
- I ran that way with separated intents enabled and disabled for 20 times each and all runs completed in ~1600s. The profiles for both settings were similar in terms of Pebble being a small fraction of the time.
- Looking at bors failures and bleeding edge build failures for the latter half of last week, I see many timeouts in `TestCCLLogic`, and `acceptance/bank/cluster-recovery` failures. That happens on this PR too, and I am wondering whether the root cause of the `TestLogic` timeout is similar. The `TestCCLLogic` behavior is reproducible locally -- it either completes in 1min or goes on forever until I killed it after 2h (it didn't seem to be doing any work), so maybe it is a different cause.
- The bors and bleeding edge failures precede the Pebble optimization I merged on friday, so at least that is eliminated as a root cause.
- I bumped up the test timeout to 1h and one of the CI runs had `TestLogic` completing in 40min, with most of the slow ones being the `upsert` test https://teamcity.cockroachdb.com/viewLog.html?buildTypeId=Cockroach_UnitTests&buildId=2700653&tab=testsInfo&pager.currentPage=1 Again, trying this locally, I had 100 runs of the upsert file (across all logic configurations) with each completing in < 1min (with GOMAXPROCS=4).

Even though the `TestLogic` timeout is not consistently happening, I'm not going to try to merge this now since master seems quite unstable and I don't want to further muddy the situation. But I'm at a loss on how to proceed -- what would help is the ability to get a cpu profile of the slow `TestLogic` runs that happen on CI. Or hope that fixes to the master instability also fix this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60731#-:-MU5jJwMBUjYfiN4VRV1:b-80oou6)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal, @nvanbenschoten, and @petermattis)

**Comment by sumeerbhola** [comment]
> what would help is the ability to get a cpu profile of the slow TestLogic runs that happen on CI

I managed to grab a cpu profile. I should have realized this earlier -- the small KV batch size returned by `getKVBatchSize` when the `crdb_test` tag is set is what was needed to reproduce the problem. It is the quadratic effect caused by a batch of 1, when scanning N keys each with M versions: the first request iterates over the N*M deleted intents, the second over (N-1)*M, and so on. So we get O(N^2*M) from iterating over deleted intents, plus O(N) for the actual values. This is because all these deletions are sitting in 64MB sized memtables (nothing is flushed). Reducing the memtable to 1MB speeds up the upsert test by 4x, but we start paying the cost of decompression (because the cache size is 0). I can increase the cache, and that should workaround, but I am going to hold off until after running some tpcc roachtests.

btw, the Pebble SeekGE/SeekLT noop optimizations don't speed up this situation since with a batch of 1 the `pebbleMVCCScanner` is not going to seek to the next key.

**Comment by knz** [comment]
I think we've improved the underlying problem here, right?
Maybe this PR can be resuscitated.

**Comment by sumeerbhola** [comment]
> I think we've improved the underlying problem here, right?
Maybe this PR can be resuscitated.

Indeed, we have fixed the problem here. PR https://github.com/cockroachdb/cockroach/pull/64831 was merged yesterday.
I'm closing this.

**Pull request closed without merging**
