### PR TITLE
sql: scanner downcases unquoted identifiers

### PR DESCRIPTION
**Pull request by eisenstatdavid**
For context, see #8862. The tl;dr is that the Postgres JDBC driver assumes that SQL identifiers are downcased unless double quoted, whereas Cockroach stores non-downcased names as is but downcases just before making comparisons. This causes issues when JDBC reads non-downcased names from metadata tables without itself downcasing them.

The solution agreed on in #8862 was to downcase identifiers in the scanner and to make table, index, column, etc. names case sensitive. This PR does the former only, which addresses the problem but leaves the wart that (e.g.) CREATE TABLE "Foo" (...) followed by SELECT * FROM "FOO" is valid. We can document this as a known limitation for 1.0 and roll out case sensitivity later.

### CODE REVIEW

**Comment by knz** [comment]
Very nice work! 
Just one thing remaining about the system tables.

@bdarnell @asubiotto, how do you feel about case sensitivity on user names? Prior to this patch, we would store the name case as-entered, but compare them case-insensitive during auth. With this patch, we store the name normalized (and the comparison is still case-insensitive) so `SHOW USERS` returns something different from what was entered with `CREATE USER`. 

This preserves compatibility with the previous behavior, but I would suggest that we make usernames case-sensitive throughout. Was there a reason why we did not?

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 34 of 34 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/sql/parser/encode.go, line 120 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15434#-KilbDk2G8vPN9mUdcRi:-KilbDk2G8vPN9mUdcRj:b-1755c6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8388707049c6a5261f6dd539371f2f794eedca2f/pkg/sql/parser/encode.go#L120)):*
> ```Go
> func encodeSQLIdent(buf *bytes.Buffer, s string) {
> 	// The string needs quoting if it does not match the ident format.
> 	if isIdent(s) && Name(s).Normalize() == s {
> ```

Extend the comment to explain what is going on here.

---

*[pkg/sql/parser/scan.go, line 471 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15434#-KilbRKZv0m0ozFGx58D:-KilbRK_HuN9oATy3UxT:bksk3v9) ([raw file](https://github.com/cockroachdb/cockroach/blob/8388707049c6a5261f6dd539371f2f794eedca2f/pkg/sql/parser/scan.go#L471)):*
> ```Go
> 	for ; isIdentMiddle(s.peek()); s.pos++ {
> 	}
> 	lval.str = Name(s.in[start:s.pos]).Normalize()
> ```

Perhaps `ReNormalizeName` here? I think this will be reworked later.

---

*[pkg/sql/parser/show.go, line 41 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15434#-KilbalMHch5qJfoylIi:-KilbalMHch5qJfoylIj:b3fvn9y) ([raw file](https://github.com/cockroachdb/cockroach/blob/8388707049c6a5261f6dd539371f2f794eedca2f/pkg/sql/parser/show.go#L41)):*
> ```Go
> 		buf.WriteString(node.Name)
> 	} else {
> 		buf.WriteString(strings.ToUpper(node.Name))
> ```

This is a matter of style, but I'd be comfortable with SET pretty-print the vars lowercase. Would make the code simpler.

---

*[pkg/sql/pgwire/pgwire_test.go, line 639 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15434#-Kilc3iatB1AsFuGPkIP:-Kilc3iatB1AsFuGPkIQ:b-slpwrb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8388707049c6a5261f6dd539371f2f794eedca2f/pkg/sql/pgwire/pgwire_test.go#L639)):*
> ```Go
> 			baseTest.
> 				Results("username", "STRING", false, gosql.NullBool{}, "{primary}").
> 				Results("hashedpassword", "BYTES", true, gosql.NullBool{}, "{}"),
> ```

See my comments on system.go. This should go the other way.

---

*[pkg/sql/sqlbase/system.go, line 220 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15434#-KilcXU6SSC-nVKGYJlA:-KilcXU6SSC-nVKGYJlB:b-zca0xw) ([raw file](https://github.com/cockroachdb/cockroach/blob/8388707049c6a5261f6dd539371f2f794eedca2f/pkg/sql/sqlbase/system.go#L220)):*
> ```Go
> 		Version:  1,
> 		Columns: []ColumnDescriptor{
> 			{Name: "parentid", ID: 1, Type: colTypeInt},
> ```

These names here (and everything below) should stay cased like they were. 
If needed later we can add double quoting on all the SQL code that queries these tables.
The problem is that if you do not, if later we deploy the case-sensitivity fix on top of clusters that have been initialized prior to this change, the queries would not work.

(Unless you had planned to implement a migration that would rename all these columns on previously-created clusters to become normalized, in which case that issue disappears, but that would be more work. I am ok with having our system tables use non-normalized names.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15434#-:-KildMEgrk7q-cZ7Yxv_:b-8h6pqg)*

**Comment by bdarnell** [comment]
> I would suggest that we make usernames case-sensitive throughout. Was there a reason why we did not?

I would expect that the case-sensitivity rules for user names to be the same as for table names (although I would only be mildly surprised if they were different). Why would we change usernames to be case-sensitive at the same time that we're relaxing case behavior for table names?

> We can document this as a known limitation for 1.0 and roll out case sensitivity later.

Why would we consider making a disruptive change like introducing case sensitivity post-1.0?

This is a scary change to be making after rc1 has been cut (it may yet get in before rc1 is released, but it missed the official cutoff). I guess it's important because of the JDBC driver but this really should have gotten in earlier.

**Comment by eisenstatdavid** [comment]
> Why would we consider making a disruptive change like introducing case sensitivity post-1.0?

Case sensitivity was the consensus on the issue thread. I tried to implement that but was still chasing test failures, so after consulting @knz , I cut this PR.

> This is a scary change to be making after rc1 has been cut

I agree. Perhaps we should have a post-mortem re issue triage for 1.0.

**Comment by eisenstatdavid** [comment]
This is failing on CI because on a SET TIME ZONE UTC, "utc" is a valid timezone on MacOS but not Linux due to the case sensitivity of the latter's file system. (There's also a known flaky test.) Since we already have special case code to recognize "default" and "local" as synonyms for UTC, I propose that we recognize "utc" as well.

An alternative fix, possibly infeasible, would be to change the scanner/parser not to downcase the argument of SET TIME ZONE.

**Comment by knz** [comment]
- regarding usernames: ack; users can use double quotes in CREATE USER if that's what they want. Authentication should compare case-sensitive using the username entered by the client, though.
- regarding the PR cut-off: Ben the idea why I support getting this PR now is that at least the descriptors get populated with normalized names, which will enable us later to make good use of this fact (i.e. remove re-normalization in the SQL execution) without backward-compatibility headaches.
- regarding the time zone: there are two fixes possible. One is to do what's been done in other places already, introduce a TZVALUE_LA pseudo-token which would be emitted instead of IDENT for an IDENT that immediately follows ZONE (this is a way to sneak an extra lookahead token in the grammar). The other solution is to have the code of SetTimeZone try to uppercase its argument and retry if a first attempt failed due to "tz not found". I think I'd be more comfortable with the 2nd solution: this would create flexibility for users to not care about this too much.

---

Reviewed 2 of 2 files at r7, 34 of 34 files at r8.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15434#-:-KipMdJAAZMojgehSSQw:b-xvqnhb)*

**Comment by bdarnell** [comment]
> regarding the PR cut-off: Ben the idea why I support getting this PR now is that at least the descriptors get populated with normalized names, which will enable us later to make good use of this fact (i.e. remove re-normalization in the SQL execution) without backward-compatibility headaches.

Yeah, we should still try to get this in before 1.0 (before rc1 if possible, now that it's being delayed).

> The other solution is to have the code of SetTimeZone try to uppercase its argument and retry if a first attempt failed due to "tz not found". 

That works for UTC which is canonically uppercase, but other time zones like `America/New York` are normally given in mixed-case. Are those somehow handled differently from UTC?

**Comment by eisenstatdavid** [comment]
> Are those somehow handled differently from UTC?
Slash is not a valid identifier character, so they have to be quoted anyway. I'm not convinced that upcasing and retrying is a good solution.

**Comment by eisenstatdavid** [comment]
I looked at the list of valid time zone names. As far as I can tell, every name either

1. is upper case,
2. is title case, or
3. contains non-identifier characters.

I'm going to implement @knz 's suggestion but also try title case.

**Comment by eisenstatdavid** [comment]
Ready for another look.

---

Review status: 26 of 34 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/sql/parser/encode.go, line 120 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15434#-KilbDk2G8vPN9mUdcRi:-KipOZEYU09IgLdJhA7b:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8388707049c6a5261f6dd539371f2f794eedca2f/pkg/sql/parser/encode.go#L120)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Extend the comment to explain what is going on here.
</blockquote></details>

Done.

---

*[pkg/sql/parser/scan.go, line 471 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15434#-KilbRKZv0m0ozFGx58D:-KipOnBhHXQ_DhEqYML0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8388707049c6a5261f6dd539371f2f794eedca2f/pkg/sql/parser/scan.go#L471)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Perhaps `ReNormalizeName` here? I think this will be reworked later.
</blockquote></details>

Done.

---

*[pkg/sql/sqlbase/system.go, line 220 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15434#-KilcXU6SSC-nVKGYJlA:-KipYQK1l2xnQO_YCnq_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8388707049c6a5261f6dd539371f2f794eedca2f/pkg/sql/sqlbase/system.go#L220)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

These names here (and everything below) should stay cased like they were. 
If needed later we can add double quoting on all the SQL code that queries these tables.
The problem is that if you do not, if later we deploy the case-sensitivity fix on top of clusters that have been initialized prior to this change, the queries would not work.

(Unless you had planned to implement a migration that would rename all these columns on previously-created clusters to become normalized, in which case that issue disappears, but that would be more work. I am ok with having our system tables use non-normalized names.)
</blockquote></details>

Done.

---

*[pkg/sql/parser/show.go, line 41 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15434#-KilbalMHch5qJfoylIi:-KipOvHhzGj19GWeNYh_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8388707049c6a5261f6dd539371f2f794eedca2f/pkg/sql/parser/show.go#L41)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This is a matter of style, but I'd be comfortable with SET pretty-print the vars lowercase. Would make the code simpler.
</blockquote></details>

Done.

---

*[pkg/sql/pgwire/pgwire_test.go, line 639 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15434#-Kilc3iatB1AsFuGPkIP:-KipYZNoxacGzWHXRU12:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8388707049c6a5261f6dd539371f2f794eedca2f/pkg/sql/pgwire/pgwire_test.go#L639)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

See my comments on system.go. This should go the other way.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15434#-:-KipuxGdAseqFauOfWAX:b467oqh)*

**Comment by knz** [comment]
It looks good to me!

---

Reviewed 11 of 11 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/sqlbase/system.go, line 220 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15434#-KilcXU6SSC-nVKGYJlA:-Kipw8pL_5Tbutmnx9aT:b-hay2ix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8388707049c6a5261f6dd539371f2f794eedca2f/pkg/sql/sqlbase/system.go#L220)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15434#-:-KipwuM1Bsn_3aeYmMWV:bw77for)*

**Comment by knz** [comment]
Reviewed 2 of 2 files at r12, 24 of 34 files at r13, 11 of 11 files at r14.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15434)*

**Comment by knz** [comment]
I think this now just needs a rebase and is then good to go.

**Pull request merged**
