### PR TITLE
insights: identify statements with high retry counts

### PR DESCRIPTION
**Pull request by matthewtodd**
Addresses #85827.

This change undoes the previous "concerns" concept from #85345 and
replaces it with a "problems" field.[^1][^2] We then mark slow statements
retried more than 5 times as having a "HighRetryCount" problem.[^3] Slow
statements without any specifically identified problems will have
"Unknown" in their list of problems. We will add support for further
problem detection in future commits.

[^1]: Every execution insight we offer happens because a statement was
  slow, so the "SlowExecution" concern was the only one we'd ever have.

[^2]: The protocol buffer changes are safe because we haven't deployed
  this code anywhere yet.

[^3]: This threshold may be configured via the
  `sql.insights.high_retry_count.threshold` cluster setting.

Release justification: Category 2: Bug fixes and low-risk updates to new
functionality

Release note (ops change): The new
`sql.insights.high_retry_count.threshold` cluster setting may be used to
configure how many times a slow statement (as identified by the
execution insights system) must have been retried to be marked as having
a high retry count.

### CODE REVIEW

**Review by matthewtodd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86415)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[`pkg/sql/sqlstats/insights/insights.proto` line 25 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86415#-N9mb2hy6zihNPC5z_x9:-N9mb2hy6zihNPC5z_xA:b-ykf8o4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdb9b0883874cd40ccc51d3a085d8ea9b09c657/pkg/sql/sqlstats/insights/insights.proto#L25)):*
> ```protobuf
>   HighWaitTime = 3;
>   HighRetryCount = 4;
>   FailedExecution = 5;
> ```

I'm working through documentation for these values now.

**Review by maryliag — COMMENTED** [review]
> Reviewed 13 of 13 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86415)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @matthewtodd)

___
*[`pkg/sql/sqlstats/insights/detector.go` line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86415#-N9mYtAo2s6PLIc8-KLC:-N9mYtAo2s6PLIc8-KLD:bwvjh3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/40772247663b2d3946b8676adb0ed69826085cdf/pkg/sql/sqlstats/insights/detector.go#L48)):*
> ```Go
> 	result := false
> 	for _, d := range a.detectors {
> 		result = d.isSlow(statement) || result
> ```

can you do a check if the value is already true, break for loop, so you don't need to continue checking
___
*[`pkg/sql/sqlstats/insights/insights.go` line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86415#-N9miqYP7Cjq7z2m3TQT:-N9miqYP7Cjq7z2m3TQU:b8kkkg1) ([raw file](https://github.com/cockroachdb/cockroach/blob/40772247663b2d3946b8676adb0ed69826085cdf/pkg/sql/sqlstats/insights/insights.go#L86)):*
> ```Go
> 	settings.TenantWritable,
> 	"sql.insights.high_retry_count.threshold",
> 	"slow statements retried more than this number of times will be marked as having a high retry count",
> ```

should you add something like "... marked as an insight with high..." ? Just want to clarify that this will be marked on the insights, in case they want to check

**Review by matthewtodd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86415)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/sql/sqlstats/insights/detector.go` line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86415#-N9mYtAo2s6PLIc8-KLC:-N9mvAmxAQvUNhMQTnnE:bx830y3) ([raw file](https://github.com/cockroachdb/cockroach/blob/40772247663b2d3946b8676adb0ed69826085cdf/pkg/sql/sqlstats/insights/detector.go#L48)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

can you do a check if the value is already true, break for loop, so you don't need to continue checking
</blockquote></details>

That's what the comment is about -- we don't short-circuit the for loop so that all the detectors have the chance to observe the statement. This is important for the (fancy) anomaly detector, so that it gets to build up its sense of normal.
___
*[`pkg/sql/sqlstats/insights/insights.go` line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86415#-N9miqYP7Cjq7z2m3TQT:-N9mvaeL83WulnGiQzUS:b-oh2x6e) ([raw file](https://github.com/cockroachdb/cockroach/blob/40772247663b2d3946b8676adb0ed69826085cdf/pkg/sql/sqlstats/insights/insights.go#L86)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

should you add something like "... marked as an insight with high..." ? Just want to clarify that this will be marked on the insights, in case they want to check
</blockquote></details>

Yeah, I'm playing with how to use the names. Our insight is that this statement was slow because of being retried a bunch. I nodded toward that with the phrase "slow statements" here, leaning on the `insights` namespace in the cluster setting to provide the context. But I think we can do more to make this clear, especially calling out that we won't be identifying _all_ highly-retried statements, just the _slow_ ones.

I've just updated to "the number of retries a slow statement must have undergone for its high retry count to be highlighted as a potential problem," leaning on the word "problem" from the insights proto / table. WDYT?

**Review by maryliag — APPROVED** [review]
Just one question, otherwise :lgtm: 
Great to see the room for all other problems we can just add in :smile: 

> Reviewed 5 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86415#-:-N9nAPNGEC5fEatUtSau:b-metzm4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag and @matthewtodd)

___
*[`pkg/sql/sqlstats/insights/detector.go` line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86415#-N9mYtAo2s6PLIc8-KLC:-N9n9XFjD8HGAjY5j3GD:b-2902f3) ([raw file](https://github.com/cockroachdb/cockroach/blob/40772247663b2d3946b8676adb0ed69826085cdf/pkg/sql/sqlstats/insights/detector.go#L48)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

That's what the comment is about -- we don't short-circuit the for loop so that all the detectors have the chance to observe the statement. This is important for the (fancy) anomaly detector, so that it gets to build up its sense of normal.
</blockquote></details>

ahhh I see what you mean now!
___
*[`pkg/sql/sqlstats/insights/insights.go` line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86415#-N9miqYP7Cjq7z2m3TQT:-N9n9l-L3YGky9BwwGhw:b-nw97pr) ([raw file](https://github.com/cockroachdb/cockroach/blob/40772247663b2d3946b8676adb0ed69826085cdf/pkg/sql/sqlstats/insights/insights.go#L86)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Yeah, I'm playing with how to use the names. Our insight is that this statement was slow because of being retried a bunch. I nodded toward that with the phrase "slow statements" here, leaning on the `insights` namespace in the cluster setting to provide the context. But I think we can do more to make this clear, especially calling out that we won't be identifying _all_ highly-retried statements, just the _slow_ ones.

I've just updated to "the number of retries a slow statement must have undergone for its high retry count to be highlighted as a potential problem," leaning on the word "problem" from the insights proto / table. WDYT?
</blockquote></details>

I like this approach! Thank you for updating!
___
*[`pkg/sql/sqlstats/insights/insights.proto` line 36 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86415#-N9n9yASEzpAoCdnrOWG:-N9n9yASEzpAoCdnrOWH:biywukq) ([raw file](https://github.com/cockroachdb/cockroach/blob/493a43ba0738282bc9568bec3d014c1a79dfc664/pkg/sql/sqlstats/insights/insights.proto#L36)):*
> ```protobuf
> 
>   // This statement was slow because of being retried multiple times, again due
>   // to contention. The "high" threshold may be configured by the
> ```

is a retry always because of contention?

**Review by matthewtodd — COMMENTED** [review]
TFTR, @maryliag!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86415#-:-N9nS2u_5EVUkSLp6Q8C:byqop8s)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag and @matthewtodd)

___
*[`pkg/sql/sqlstats/insights/insights.proto` line 36 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86415#-N9n9yASEzpAoCdnrOWG:-N9nRp-e9KHlB7iLhyCF:bq40y4b) ([raw file](https://github.com/cockroachdb/cockroach/blob/493a43ba0738282bc9568bec3d014c1a79dfc664/pkg/sql/sqlstats/insights/insights.proto#L36)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

is a retry always because of contention?
</blockquote></details>

AFAIK? I threw these together quickly from [the Problems table](https://cockroachlabs.atlassian.net/wiki/spaces/SQLOBS/pages/2176549228/Workload+insights+and+recommendations+90#Problems) in the doc.

**Pull request merged**
