### PR TITLE
roachtest: fix roachtest --cluster

### PR DESCRIPTION
**Pull request by andreimatei**
A recent commit delayed the setting of c.t, but some functions used by
attachToExistingCluster() were not prepated to work without c.t set.
This test introduces c.StartE/WipeE flavors that can be run on a cluster
that hasn't a test set yet.

Release note: None

### CODE REVIEW

**Comment by andreimatei** [comment]
not ready yet, sorry

**Comment by BramGruneir** [comment]
Perhaps we should revert the change that broke it and then you can take your time fixing this.

**Comment by andreimatei** [comment]
ready for review now

**Review by BramGruneir — APPROVED** [review]
:lgtm: With one comment.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31401#-:-LOtVJg6DhOwLnUYbaZP:b-97wbcc)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/cluster.go, line 747 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31401#-LOtUoid1ZdTd8sVDNq2:-LOtUoid1ZdTd8sVDNq3:b-wrzuyl) ([raw file](https://github.com/cockroachdb/cockroach/blob/784fdbbae0e968567562bcceb779f8862aefcffb/pkg/cmd/roachtest/cluster.go#L747)):*
> ```Go
> 	if !opt.skipStop {
> 		c.status("stopping cluster")
> 		c.All()
> ```

Why do you need to call all() here?

**Review by benesch — APPROVED** [review]
:lgtm: as well

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31401#-:-LOtVZnfAVzVTjY6TRyh:b-y4jscz)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/cluster.go, line 747 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31401#-LOtUoid1ZdTd8sVDNq2:-LOtVQblADq25e2MPIOt:bptdydq) ([raw file](https://github.com/cockroachdb/cockroach/blob/784fdbbae0e968567562bcceb779f8862aefcffb/pkg/cmd/roachtest/cluster.go#L747)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why do you need to call all() here?
</blockquote></details>

Yeah, this looks spurious.

**Review by andreimatei — COMMENTED** [review]
TFTRs

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31401#-:-LOtVq4y6BgHQhF4i8_6:b-6rbzir)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/cmd/roachtest/cluster.go, line 747 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31401#-LOtUoid1ZdTd8sVDNq2:-LOtVndeDhJsKHYkwzzU:b-6g3wn8) ([raw file](https://github.com/cockroachdb/cockroach/blob/784fdbbae0e968567562bcceb779f8862aefcffb/pkg/cmd/roachtest/cluster.go#L747)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Yeah, this looks spurious.
</blockquote></details>

debug leftover, sorry

**Comment by andreimatei** [comment]
flake pinged to Nikhil.

One more spin:
bors r+

**Pull request merged**
