### PR TITLE
pgwire: deflake TestParseClientProvidedSessionParameters

### LINKED ISSUE #93469: pgwire: flake in TestParseClientProvidedSessionParameters
Easily fails under stress on 8d7903574b94d654aec9d1e4e65bd3325fe21375:
```
./dev test pkg/sql/pgwire -f=TestParseClientProvidedSessionParameters --cpus=4 --stress -v
...
--- FAIL: TestParseClientProvidedSessionParameters (0.02s)
    --- PASS: TestParseClientProvidedSessionParameters/user_is_set_from_query (0.00s)
    --- PASS: TestParseClientProvidedSessionParameters/user_is_ignored_in_options (0.00s)
    --- PASS: TestParseClientProvidedSessionParameters/results_buffer_size_is_not_configurable_from_options (0.00s)
    --- PASS: TestParseClientProvidedSessionParameters/crdb:remote_addr_is_ignored_in_options (0.00s)
    --- PASS: TestParseClientProvidedSessionParameters/more_keys_than_values_in_options_error (0.00s)
    --- PASS: TestParseClientProvidedSessionParameters/more_values_than_keys_in_options_error (0.00s)
    --- PASS: TestParseClientProvidedSessionParameters/success_parsing_encoded_options (0.00s)
    --- PASS: TestParseClientProvidedSessionParameters/success_parsing_options_with_no_space_after_'-c' (0.00s)
    --- PASS: TestParseClientProvidedSessionParameters/success_parsing_options_with_a_tab_(%09)_separating_the_options (0.00s)
    --- PASS: TestParseClientProvidedSessionParameters/error_when_no_leading_'-c' (0.00s)
    --- FAIL: TestParseClientProvidedSessionParameters/'-c'_with_no_leading_space_belongs_to_prev_value (0.00s)
    --- FAIL: TestParseClientProvidedSessionParameters/fail_to_parse_'-c'_with_no_leading_space (0.00s)
    --- FAIL: TestParseClientProvidedSessionParameters/parse_multiple_options_successfully (0.00s)
    --- FAIL: TestParseClientProvidedSessionParameters/success_parsing_option_with_space_in_value (0.00s)
    --- FAIL: TestParseClientProvidedSessionParameters/success_parsing_crdb:jwt_auth_enabled_from_true_option (0.00s)
    --- FAIL: TestParseClientProvidedSessionParameters/success_parsing_crdb:jwt_auth_enabled_from_false_option (0.00s)
    --- PASS: TestParseClientProvidedSessionParameters/success_parsing_crdb:jwt_auth_enabled_when_there_is_some_capitalization (0.00s)
    --- FAIL: TestParseClientProvidedSessionParameters/default_crdb:jwt_auth_enabled_value_is_false_if_not_provided (0.00s)
    --- FAIL: TestParseClientProvidedSessionParameters/crdb:jwt_auth_enabled_must_be_a_boolean_if_provided (0.00s)
    --- FAIL: TestParseClientProvidedSessionParameters/remote_addr_missing_port (0.00s)
    --- FAIL: TestParseClientProvidedSessionParameters/remote_addr_port_must_be_numeric (0.00s)
    --- FAIL: TestParseClientProvidedSessionParameters/remote_addr_host_must_be_numeric (0.00s)
    --- FAIL: TestParseClientProvidedSessionParameters/success_setting_remote_address_from_query (0.00s)
    --- FAIL: TestParseClientProvidedSessionParameters/normalize_to_lower_case_in_options_parameter (0.00s)
    --- FAIL: TestParseClientProvidedSessionParameters/normalize_to_lower_case_in_query_parameters (0.00s)
FAIL
I221212 22:37:53.344612 1 (gostd) testmain.go:264  [-] 1  Test //pkg/sql/pgwire:pgwire_test exited with error code 1


ERROR: exit status 1

21 runs completed, 1 failures, over 3s
```

Jira issue: CRDB-22350

### PR DESCRIPTION
**Pull request by rafiss**
fixes #93469

Release note: None

### CODE REVIEW

**Review by knz — APPROVED** [review]

**Review by andreimatei — COMMENTED** [review]
please explain in the commit message why reusing the server wasn't good

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93538#-:-NJC1kz47TaE0umE4s76:b5sh23a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs)

**Comment by rafiss** [comment]
bors r=knz

**Review by andreimatei — COMMENTED** [review]
Hold up, I don't really understand what's going on here. You sure this is the right fix? Looking superficially, it seems to me that these tests ought to be able to share a server.
Is the goroutine doing `pgx.Connect(ctx, url)` outliving the subtest? If that has something to do with the issue, let's fix that.

Do you mind spelling out to me what's up with these out of order messages? Doesn't each subtest operate on a different session?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93538#-:-NJC7BBH1drj6m7xke9E:bugaeyj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs)

**Review by andreimatei — COMMENTED** [review]
bors r-
while we chat

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93538#-:-NJCJfKCBRdybs-l9sNT:b-gfd2w7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs)

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93538)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @renatolabs)

___
*[`pkg/sql/pgwire/conn_test.go` line 1554 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93538#-NJGp3MR29wWUDmJD3iX:-NJGp3MR29wWUDmJD3iY:b9c5rs7) ([raw file](https://github.com/cockroachdb/cockroach/blob/01d85f19ca09decc3adad715d38122604241b670/pkg/sql/pgwire/conn_test.go#L1554)):*
> ```Go
> 
> 	for _, tc := range testCases {
> 		t.Run(tc.desc, func(t *testing.T) {
> ```

Resuming from where we left offline:
I had misunderstood what is now being done in every subtest: it's opening a listener, not a crdb node, so I no longer care about doing it repeatedly - in fact I think that's the right move.
But, have we actually solved the problem exposed by the failures in a robust way. If the problem is that pgx opens a connection async (in order to cancel the original connection), then isn't it still possible for that async connection to happen after the next subtest started and trip it up if the listen for the next subtest is assigned the same port?
I think we need to either find a way to drain each subtest, or to make the listener ignore these connections done by pgx. I think you've noticed that the async cancel is related to us putting  a connection timeout. Is that timeout necessary?
Alternatively, could we use lib/pq instead?

**Comment by rafiss** [comment]
>  If the problem is that pgx opens a connection async (in order to cancel the original connection), then isn't it still possible for that async connection to happen after the next subtest started and trip it up if the listen for the next subtest is assigned the same port?

my read of https://github.com/jackc/pgconn/blob/96b31c42141f1ab3145ad5f72e17c810ea682801/pgconn.go#L535-L540 is that the async cancel is only sent for non-timeout errors. in this case, it's the context deadline exceeded error that's causing this. so let me just try removing the context deadline.

maybe we could also change things so the listener is not closed until after all the subtests are done.

> I think we need to either find a way to drain each subtest, or to make the listener ignore these connections done by pgx. 

i don't think we can make the listener ignore those connections. it can only identify a cancel request after reading the first few bytes of the request, and by then isn't it already too late?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93538)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @renatolabs)

___
*[`pkg/sql/pgwire/conn_test.go` line 1554 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93538#-NJGp3MR29wWUDmJD3iX:-NJGwtVqAgqdg0LgEC_H:b3ljo5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/01d85f19ca09decc3adad715d38122604241b670/pkg/sql/pgwire/conn_test.go#L1554)):*
Moving your answer back to the right thread.

>> If the problem is that pgx opens a connection async (in order to cancel the original connection), then isn't it still possible for that async connection to happen after the next subtest started and trip it up if the listen for the next subtest is assigned the same port?

> my read of https://github.com/jackc/pgconn/blob/96b31c42141f1ab3145ad5f72e17c810ea682801/pgconn.go#L535-L540 is that the async cancel is only sent for non-timeout errors. in this case, it's the context deadline exceeded error that's causing this. so let me just try removing the context deadline.

:thumbsup: 

> maybe we could also change things so the listener is not closed until after all the subtests are done.

Yeah, that's one way to ensure that the port is not reused.


>> I think we need to either find a way to drain each subtest, or to make the listener ignore these connections done by pgx.

> i don't think we can make the listener ignore those connections. it can only identify a cancel request after reading the first few bytes of the request, and by then isn't it already too late?

Too late how? I was thinking the listener would recognize these packets and not hand the connection to `getSessionArgs`.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93538)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @renatolabs)

___
*[`pkg/sql/pgwire/conn_test.go` line 1554 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93538#-NJGp3MR29wWUDmJD3iX:-NJH3ZKN13W-ECAXUQCw:b7gk63a) ([raw file](https://github.com/cockroachdb/cockroach/blob/01d85f19ca09decc3adad715d38122604241b670/pkg/sql/pgwire/conn_test.go#L1554)):*
> Too late how? I was thinking the listener would recognize these packets and not hand the connection to getSessionArgs.

ah i understand now. i did that and it seems to have done it. and the fake server can still be shared.

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93538#-:-NJLPhHQ3KeKpdf29bEF:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @renatolabs)

**Comment by rafiss** [comment]
tftr!

bors r=knz,andreimatei

**Pull request merged**
