### PR TITLE
util/log: add buffer sink decorator

### PR DESCRIPTION
**Pull request by rauchenstein**
Previously, only the file sink had buffering, and in that case it is
built into the sink.  It's important to add buffering to network sinks
for various reasons -- reducing network chatter, and making the
networking call itself asynchronous so the log call returns with very
low latency.

This change adds a buffering decorator so that buffering can be added to
any log sink with little or no development effort, and allowing
buffering to be configured in a uniform way.

Release note (cli change): Add buffering to log sinks. This can be
configured with the new "buffering" field on any log sink provided via
the "--log" or "--log-config-file" flags.

Release justification: This change is safe because it is a no-op without
a configuration change specifically enabling it.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
General recommendation: be careful with channel writes, which could block. Also select on read on `ctx.Done` during channel writes.

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-:-Mk8X23B7KTyuJx8_zJj:b-9h2mz7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rauchenstein)

___
*[pkg/util/log/buffer_sink.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-Mk8XAr4CsjxkZP6uiVG:-Mk8XAr4CsjxkZP6uiVH:b-ptpo8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3785106a5f1489afc663a28d08bf9b69f440c3/pkg/util/log/buffer_sink.go#L20)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/cli/exit"
> )
> ```

It'd be useful to have a top level comment here which outlines the overall architecture.
___
*[pkg/util/log/buffer_sink.go, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-Mk8VHqt8JfZGfHNj8oK:-Mk8VHqt8JfZGfHNj8oL:bynyonc) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3785106a5f1489afc663a28d08bf9b69f440c3/pkg/util/log/buffer_sink.go#L21)):*
> ```Go
> )
> 
> type bufferSinkMessage struct {
> ```

would appreciate some explanatory comments for each struct and the fields therein. Will make the review easier.
___
*[pkg/util/log/buffer_sink.go, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-Mk8XG1_DG09hTRx_PL0:-Mk8XG1_DG09hTRx_PL1:b-y3nacx) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3785106a5f1489afc663a28d08bf9b69f440c3/pkg/util/log/buffer_sink.go#L63)):*
> ```Go
> 	}
> 
> 	messageCh := make(chan bufferSinkMessage)      // sends messages to the accumulator
> ```

place these things in a struct (perhaps the `bufferSink`)
___
*[pkg/util/log/buffer_sink.go, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-Mk8Wb4h0X6Ia2t-UK0N:-Mk8Wb4h0X6Ia2t-UK0O:bsxjx1i) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3785106a5f1489afc663a28d08bf9b69f440c3/pkg/util/log/buffer_sink.go#L74)):*
> ```Go
> 
> 	// Accumulator
> 	go func() {
> ```

please extract these two anonymous functions into separate top-level named functions (or perhaps method on `bufferSink`).
___
*[pkg/util/log/buffer_sink.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-Mk8WSJR5b3HNF-TbSwE:-Mk8WSJR5b3HNF-TbSwF:b67swcm) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3785106a5f1489afc663a28d08bf9b69f440c3/pkg/util/log/buffer_sink.go#L112)):*
> ```Go
> 					flushCh <- b
> 					atomic.AddInt32(&nQueuedFlushes, 1)
> 					reset()
> ```

something needs to be done about resetting the timer here.
___
*[pkg/util/log/buffer_sink.go, line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-Mk8WkdXDtYmmLHM-XeE:-Mk8WkdXDtYmmLHM-XeF:b-v71e2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3785106a5f1489afc663a28d08bf9b69f440c3/pkg/util/log/buffer_sink.go#L131)):*
> ```Go
> 			case b := <-flushCh:
> 				// Calculate size of all-but-first buffer.
> 				tailSize := 0
> ```

make the size computation a  method on `b`.
___
*[pkg/util/log/buffer_sink.go, line 197 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-Mk8VkrYDc2ITDgv7cKf:-Mk8VkrYDc2ITDgv7cKg:bg3xyue) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3785106a5f1489afc663a28d08bf9b69f440c3/pkg/util/log/buffer_sink.go#L197)):*
> ```Go
> func (s *bufferSink) output(b []byte, opts sinkOutputOptions) error {
> 	// Make a copy to live in the async buffer.
> 	// We can't take ownership of the slice we're passed --
> ```

suggestion: we can swap the byte slice inside the buffer with an empty one, to take the ownership.

**Review by rauchenstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70330)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/util/log/buffer_sink.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-Mk8XAr4CsjxkZP6uiVG:-MliCxu966I-FseRUVa_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3785106a5f1489afc663a28d08bf9b69f440c3/pkg/util/log/buffer_sink.go#L20)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

It'd be useful to have a top level comment here which outlines the overall architecture.
</blockquote></details>

Done.
___
*[pkg/util/log/buffer_sink.go, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-Mk8VHqt8JfZGfHNj8oK:-MliCzH9BRAGNDu6oknK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3785106a5f1489afc663a28d08bf9b69f440c3/pkg/util/log/buffer_sink.go#L21)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

would appreciate some explanatory comments for each struct and the fields therein. Will make the review easier.
</blockquote></details>

Done.
___
*[pkg/util/log/buffer_sink.go, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-Mk8XG1_DG09hTRx_PL0:-MlhH2DC9963JLHhRFDi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3785106a5f1489afc663a28d08bf9b69f440c3/pkg/util/log/buffer_sink.go#L63)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

place these things in a struct (perhaps the `bufferSink`)
</blockquote></details>

Done.
___
*[pkg/util/log/buffer_sink.go, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-Mk8Wb4h0X6Ia2t-UK0N:-MlhH-0iC6cl1uMCky3j:bjpaoqw) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3785106a5f1489afc663a28d08bf9b69f440c3/pkg/util/log/buffer_sink.go#L74)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

please extract these two anonymous functions into separate top-level named functions (or perhaps method on `bufferSink`).
</blockquote></details>

Done (methods).
___
*[pkg/util/log/buffer_sink.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-Mk8WSJR5b3HNF-TbSwE:-MlQl2ZH39ETX-ORWWoh:b-crkrb5) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3785106a5f1489afc663a28d08bf9b69f440c3/pkg/util/log/buffer_sink.go#L112)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

something needs to be done about resetting the timer here.
</blockquote></details>

reset() resets the timer.
___
*[pkg/util/log/buffer_sink.go, line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-Mk8WkdXDtYmmLHM-XeE:-MlQmrLkE4JKjOKLCw0u:b-mtgflf) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3785106a5f1489afc663a28d08bf9b69f440c3/pkg/util/log/buffer_sink.go#L131)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

make the size computation a  method on `b`.
</blockquote></details>

Similar is done.  I moved the accumulator's byte count to be maintained within the bundle, so it's available as a data field.
___
*[pkg/util/log/buffer_sink.go, line 197 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-Mk8VkrYDc2ITDgv7cKf:-MlQqlJn6q5AiXgBau1R:bgm2air) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3785106a5f1489afc663a28d08bf9b69f440c3/pkg/util/log/buffer_sink.go#L197)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

suggestion: we can swap the byte slice inside the buffer with an empty one, to take the ownership.
</blockquote></details>

I don't think that's possible, since log.buffer is backed by bytes.Buffer (not a pointer), and I don't see a way for that to relinquish ownership of its backing data (perhaps so it can do some small-value optimization).
Even if it was possible, we'd be draining the buffer pool of buffers with useful capacity (so those buffers have to allocate new backing data on first use), and leaving the backing arrays for the slices we take ownership of to be GC'ed, which is part of what the whole buffer-pooling scheme was trying to avoid.

I think we'd get similar downsides in a more understandable form by just allocating new byte slices here and not using log.buffers.

**Review by knz — COMMENTED** [review]
Two suggestions:

- run this under stressrace
- run this with the new deadlock detector that Erik enabled (ask test eng for the test flags)

> Reviewed 6 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-:-MlkVc2QB2K5FyRrrujv:b-jh1tnt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @rauchenstein, and @rimadeodhar)

___
*[pkg/util/log/buffer_sink.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-Mk8XAr4CsjxkZP6uiVG:-MlkUGwd7Qe0YTXVUfRn:b-lt5xcx) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3785106a5f1489afc663a28d08bf9b69f440c3/pkg/util/log/buffer_sink.go#L20)):*
<details><summary><i>Previously, rauchenstein wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Maybe some more prose would be useful:

- what is the initial condition
- what happens (outline) when the first log event comes in, and the buffer is not yet full
- what happens (outline) when the buffer is full and a log event comes in
- what happens in the error case
___
*[pkg/util/log/buffer_sink.go, line 26 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-MlkUJA36nfHYyVY4akJ:-MlkUJA36nfHYyVY4akK:b-munhzy) ([raw file](https://github.com/cockroachdb/cockroach/blob/431de7a1fb8f40d6c5fad7dbf307e8569ab87c49/pkg/util/log/buffer_sink.go#L26)):*
> ```Go
> // by the forceSync option).
> type bufferSink struct {
> 	// child is the wrapped logSink
> ```

nit: here and below: periods at the end of sentences
___
*[pkg/util/log/buffer_sink.go, line 83 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-MlkUgTiDlWGi3XeYpNC:-MlkUgTiDlWGi3XeYpND:b-p3jf19) ([raw file](https://github.com/cockroachdb/cockroach/blob/431de7a1fb8f40d6c5fad7dbf307e8569ab87c49/pkg/util/log/buffer_sink.go#L83)):*
> ```Go
> 	var (
> 		b     bufferSinkBundle
> 		timer <-chan time.Time // staleness timer
> ```

Add some explanation for this that explains when the timer is created, when it is reset etc.
___
*[pkg/util/log/buffer_sink.go, line 168 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-MlkUsgd21Y_ssqUxHzr:-MlkUsgd21Y_ssqUxHzs:b-9sku4r) ([raw file](https://github.com/cockroachdb/cockroach/blob/431de7a1fb8f40d6c5fad7dbf307e8569ab87c49/pkg/util/log/buffer_sink.go#L168)):*
> ```Go
> }
> 
> // bufferSinkMessage holds an individual log message sent from output to accumulate
> ```

nit: here and below, periods at the end of comments (comments are sentences).
___
*[pkg/util/log/buffer_sink.go, line 173 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-MlkUwrA-TqwitVlwQ6-:-MlkUwrA-TqwitVlwQ60:b8z3ud6) ([raw file](https://github.com/cockroachdb/cockroach/blob/431de7a1fb8f40d6c5fad7dbf307e8569ab87c49/pkg/util/log/buffer_sink.go#L173)):*
> ```Go
> 	// flush is set if the call explicitly requests to trigger an flush
> 	flush bool
> 	// errorCh is set iff the message is forceSync
> ```

separate sentences with periods and capitals.
___
*[pkg/util/log/buffer_sink_test.go, line 39 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-MlkVFt97TwjOVfrbB-G:-MlkVFt97TwjOVfrbB-H:b-q97liv) ([raw file](https://github.com/cockroachdb/cockroach/blob/431de7a1fb8f40d6c5fad7dbf307e8569ab87c49/pkg/util/log/buffer_sink_test.go#L39)):*
> ```Go
> }
> 
> func TestBufferOneLine(t *testing.T) {
> ```

for all tests here, use `defer leaktest.AfterTest(t)` to verify there are no stray goroutines after the test ends.
___
*[pkg/util/log/buffer_sink_test.go, line 47 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-MlkVKZmB-N5kHzUfv0O:-MlkVKZmB-N5kHzUfv0P:b-h7vojr) ([raw file](https://github.com/cockroachdb/cockroach/blob/431de7a1fb8f40d6c5fad7dbf307e8569ab87c49/pkg/util/log/buffer_sink_test.go#L47)):*
> ```Go
> 
> 	require.NoError(t, sink.output(message, sinkOutputOptions{extraFlush: true}))
> 	<-time.After(time.Second)
> ```

this is not needed if cleanup works.

ditto below.
___
*[pkg/util/log/flags.go, line 403 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-MlkSQ5M81i_hLZFu5dl:-MlkSQ5M81i_hLZFu5dm:b95pgr) ([raw file](https://github.com/cockroachdb/cockroach/blob/431de7a1fb8f40d6c5fad7dbf307e8569ab87c49/pkg/util/log/flags.go#L403)):*
> ```Go
> 
> func attachBufferWrapper(ctx context.Context, s *sinkInfo, c logconfig.CommonSinkConfig) {
> 	b := c.Buffering
> ```

From a UX perspective, it's not so easy / clear how to *disable buffering* entirely with the current mechanism. Should I write:

```
http-servers:
   foo:
     buffering: nil
```
? 

or something else entirely?

This looks cumbersome. Can I instead write:

```
http-servers:
   foo:
     buffered: false
```
    

(NB network sinks should be buffered by default unless buffering disabled by `auditable: true`. )

(we also *probably* don't want `buffering: {enabled: false}` which is a tad too verbose)
___
*[pkg/util/log/logconfig/config.go, line 187 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-MlkRprc8CvA1SRAVfWz:-MlkRprdE_baBOvOaw8d:b-nstzi5) ([raw file](https://github.com/cockroachdb/cockroach/blob/431de7a1fb8f40d6c5fad7dbf307e8569ab87c49/pkg/util/log/logconfig/config.go#L187)):*
> ```Go
> 
> 	// Buffering configures buffering for this log sink.
> 	Buffering *BufferSinkConfig `yaml:",omitempty"`
> ```

ok but please add tests that check that defaults are propagated

(will need to update the recursive default propagation logic to handle pointers to structs. Beware of the nil case.)

**Review by knz — COMMENTED** [review]
Also extend the commit message / PR description to explain that this change is not replacing the file buffering just yet, we want to exercise this code with the new sink types before we use it also for files. However, mention that we do aim to reuse the same buffering code for files too, and so that next cleanup/improvement should be planned ASAP.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-:-MlkVx930YzW8mZCMje9:bl14vvi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @rauchenstein, and @rimadeodhar)

**Review by rimadeodhar — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70330)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @rauchenstein, and @rimadeodhar)

___
*[pkg/util/log/buffer_sink.go, line 134 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-MlzerqSB93VsNVKeVUB:-MlzerqSB93VsNVKeVUC:b-eng1f1) ([raw file](https://github.com/cockroachdb/cockroach/blob/431de7a1fb8f40d6c5fad7dbf307e8569ab87c49/pkg/util/log/buffer_sink.go#L134)):*
> ```Go
> 		case b := <-bs.flushCh:
> 			// Append all the messages in the first buffer.
> 			buf := b.messages[0].b
> ```

Would it be better to have a safety check here to confirm that `len(b.messages) > 0`?
___
*[pkg/util/log/buffer_sink.go, line 152 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-MlzibBL7eHhGOqHcx1P:-MlzibBL7eHhGOqHcx1Q:b-41kar) ([raw file](https://github.com/cockroachdb/cockroach/blob/431de7a1fb8f40d6c5fad7dbf307e8569ab87c49/pkg/util/log/buffer_sink.go#L152)):*
> ```Go
> 			if forceSync {
> 				b.errorCh <- err
> 			} else if err != nil && bs.errCallback != nil {
> ```

So the err will not be forwarded to the errCallback when forceSync is true i.e when b.errorCh is non nil? Why do we need these two mechanisms for forwarding the error?
___
*[pkg/util/log/buffer_sink.go, line 156 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-MlzismC2NdYvD21zpCG:-MlzismC2NdYvD21zpCH:b-olzp2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/431de7a1fb8f40d6c5fad7dbf307e8569ab87c49/pkg/util/log/buffer_sink.go#L156)):*
> ```Go
> 				// Temporarily disable this sink so it's skipped by
> 				// any logging in the callback.
> 				bs.inErrorState = true
> ```

I suspect we'll need a mutex around `inErrorState`?
___
*[pkg/util/log/exit_override.go, line 101 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-Mlva8jH4Xs0UmL_eJWo:-Mlva8jH4Xs0UmL_eJWp:b-9ehctl) ([raw file](https://github.com/cockroachdb/cockroach/blob/431de7a1fb8f40d6c5fad7dbf307e8569ab87c49/pkg/util/log/exit_override.go#L101)):*
> ```Go
> 		if logpb.Severity_ERROR >= s.threshold.get(entry.ch) && sink.active() {
> 			buf := s.formatter.formatEntry(entry)
> 			_ = sink.output(buf.Bytes(), sinkOutputOptions{ignoreErrors: true})
> ```

Nit, if we don't need the return value, we can just skip the assignment i.e. remove the `_ = `?
```
sink.output(buf.Bytes(), sinkOutputOptions{ignoreErrors: true})
```
___
*[pkg/util/log/sinks.go, line 24 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-MlvjMu_CLFWyt_hXo6E:-MlvjMua1rFF_SfX-KJ1:bjn83nq) ([raw file](https://github.com/cockroachdb/cockroach/blob/431de7a1fb8f40d6c5fad7dbf307e8569ab87c49/pkg/util/log/sinks.go#L24)):*
> ```Go
> 	ignoreErrors bool
> 	// forceSync forces synchronous operation of this output operation.
> 	// This is, it will block until the output has been handled.
> ```

Nit: Typo -  Should be`That is`, I'm guessing.

**Review by rauchenstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70330)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rimadeodhar)

___
*[pkg/util/log/buffer_sink.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-Mk8XAr4CsjxkZP6uiVG:-Mm0cQdj1w880OqlYjO5:b38sljp) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3785106a5f1489afc663a28d08bf9b69f440c3/pkg/util/log/buffer_sink.go#L20)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Maybe some more prose would be useful:

- what is the initial condition
- what happens (outline) when the first log event comes in, and the buffer is not yet full
- what happens (outline) when the buffer is full and a log event comes in
- what happens in the error case


</blockquote></details>

I elaborated.
___
*[pkg/util/log/buffer_sink.go, line 83 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-MlkUgTiDlWGi3XeYpNC:-MlvAXKc5gACQpmOK8Xn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/431de7a1fb8f40d6c5fad7dbf307e8569ab87c49/pkg/util/log/buffer_sink.go#L83)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Add some explanation for this that explains when the timer is created, when it is reset etc.
</blockquote></details>

Done.
___
*[pkg/util/log/buffer_sink.go, line 134 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-MlzerqSB93VsNVKeVUB:-Mm0XktZEE6pUvdy6kPW:bd5bmwg) ([raw file](https://github.com/cockroachdb/cockroach/blob/431de7a1fb8f40d6c5fad7dbf307e8569ab87c49/pkg/util/log/buffer_sink.go#L134)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Would it be better to have a safety check here to confirm that `len(b.messages) > 0`?
</blockquote></details>

Indeed it would be, and in fact that's a case that could happen in the latest refactor.
___
*[pkg/util/log/buffer_sink.go, line 152 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-MlzibBL7eHhGOqHcx1P:-Mm0VJkPDsTg-DTv5WHE:b-2xvbom) ([raw file](https://github.com/cockroachdb/cockroach/blob/431de7a1fb8f40d6c5fad7dbf307e8569ab87c49/pkg/util/log/buffer_sink.go#L152)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

So the err will not be forwarded to the errCallback when forceSync is true i.e when b.errorCh is non nil? Why do we need these two mechanisms for forwarding the error?
</blockquote></details>

As relevant an error as possible should be returned by `output`.  In the async case, an error in the child sink cannot be returned because `output` simply queued up the message to be flushed by the child sink later, so we use a callback mechanism.  In the synchronous case, we have to wait for the child sink anyways, so we should return its error.
___
*[pkg/util/log/buffer_sink.go, line 156 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-MlzismC2NdYvD21zpCG:-Mm0UQc04NDtutNtWMI8:b6ra63s) ([raw file](https://github.com/cockroachdb/cockroach/blob/431de7a1fb8f40d6c5fad7dbf307e8569ab87c49/pkg/util/log/buffer_sink.go#L156)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

I suspect we'll need a mutex around `inErrorState`?
</blockquote></details>

No, this is the only thread that modifies that value.
___
*[pkg/util/log/buffer_sink.go, line 173 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-MlkUwrA-TqwitVlwQ6-:-MlvAeNyAh-ZHvCtj7t4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/431de7a1fb8f40d6c5fad7dbf307e8569ab87c49/pkg/util/log/buffer_sink.go#L173)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

separate sentences with periods and capitals.
</blockquote></details>

Done.
___
*[pkg/util/log/buffer_sink_test.go, line 39 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-MlkVFt97TwjOVfrbB-G:-MlvAnd2512txy8_xpNb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/431de7a1fb8f40d6c5fad7dbf307e8569ab87c49/pkg/util/log/buffer_sink_test.go#L39)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

for all tests here, use `defer leaktest.AfterTest(t)` to verify there are no stray goroutines after the test ends.
</blockquote></details>

Done.
___
*[pkg/util/log/buffer_sink_test.go, line 47 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-MlkVKZmB-N5kHzUfv0O:-MlvAphc42SW5DK5LYl_:bdaa4rd) ([raw file](https://github.com/cockroachdb/cockroach/blob/431de7a1fb8f40d6c5fad7dbf307e8569ab87c49/pkg/util/log/buffer_sink_test.go#L47)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

this is not needed if cleanup works.

ditto below.
</blockquote></details>

It was actually, because after getting the signal from ctx.Done(), triggering a final flush then shutdown from bufferSync, the calls from that final flush may not have occurred before the call to `ctrl.Finish()` in the main thread (which is where gomock checks the received calls against its expectations).  (This was the case even when the calls in `cleanup()` were swapped to be ordered properly.)

I found a better way to do this using waitgroups (or just a channel for synchronization) to make the synchronization explicit instead of just "waiting long enough."
___
*[pkg/util/log/exit_override.go, line 101 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-Mlva8jH4Xs0UmL_eJWo:-Mm0S0LECjXEUqms4391:b-wlqgv) ([raw file](https://github.com/cockroachdb/cockroach/blob/431de7a1fb8f40d6c5fad7dbf307e8569ab87c49/pkg/util/log/exit_override.go#L101)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Nit, if we don't need the return value, we can just skip the assignment i.e. remove the `_ = `?
```
sink.output(buf.Bytes(), sinkOutputOptions{ignoreErrors: true})
```
</blockquote></details>

There are linter errors for ignoring the returned error.  This lets the linter know that we're discarding the error on purpose.
___
*[pkg/util/log/flags.go, line 403 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-MlkSQ5M81i_hLZFu5dl:-Mm0SS44BeRS0YtCU5oZ:byfuwgm) ([raw file](https://github.com/cockroachdb/cockroach/blob/431de7a1fb8f40d6c5fad7dbf307e8569ab87c49/pkg/util/log/flags.go#L403)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

From a UX perspective, it's not so easy / clear how to *disable buffering* entirely with the current mechanism. Should I write:

```
http-servers:
   foo:
     buffering: nil
```
? 

or something else entirely?

This looks cumbersome. Can I instead write:

```
http-servers:
   foo:
     buffered: false
```
    

(NB network sinks should be buffered by default unless buffering disabled by `auditable: true`. )

(we also *probably* don't want `buffering: {enabled: false}` which is a tad too verbose)


</blockquote></details>

Discussed with Ryan Kuo.  Created new type for "buffering" that supports the existing structure or "NONE" (case insensitive).  (Actually took a second pass at it too after I realized it could be simplified.)
___
*[pkg/util/log/sinks.go, line 24 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-MlvjMu_CLFWyt_hXo6E:-Mm0T6c05iXNw5BsBy0T:bkrulyk) ([raw file](https://github.com/cockroachdb/cockroach/blob/431de7a1fb8f40d6c5fad7dbf307e8569ab87c49/pkg/util/log/sinks.go#L24)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Nit: Typo -  Should be`That is`, I'm guessing.
</blockquote></details>

Good eye! Fixed.
___
*[pkg/util/log/logconfig/config.go, line 187 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70330#-MlkRprc8CvA1SRAVfWz:-Mm0TP3vDmcFd6n6QrRi:bein9wg) ([raw file](https://github.com/cockroachdb/cockroach/blob/431de7a1fb8f40d6c5fad7dbf307e8569ab87c49/pkg/util/log/logconfig/config.go#L187)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ok but please add tests that check that defaults are propagated

(will need to update the recursive default propagation logic to handle pointers to structs. Beware of the nil case.)
</blockquote></details>

Didn't end up needing to update propagation; it ended up being cleaner to specify the struct by value.  Still need to add the tests -- had to finalize the disabling logic first, since that interacts interestingly with propagation.

**Comment by knz** [comment]
Some findings while trying this on my local computer:

1) For further reference - with fluent output, we get the following bench difference:
```
name              old time/op    new time/op    delta
LogFileOutput-32    13.3µs ± 6%     9.6µs ± 5%   -27.67%  (p=0.008 n=5+5)

name              old alloc/op   new alloc/op   delta
LogFileOutput-32      233B ± 0%      660B ± 0%  +183.43%  (p=0.008 n=5+5)

name              old allocs/op  new allocs/op  delta
LogFileOutput-32      8.00 ± 0%      9.00 ± 0%   +12.50%  (p=0.008 n=5+5)
```
(no further action required on this)

2) the configuration fails with a file error when trying to add buffering to file sinks. I will try to add a guardrail about this.

**Comment by knz** [comment]
Ok so I have dug down into this a bit more. I have added several comments inline (as an additional commit on the branch) which I will want to investigate further a bit later.

There are three high level questions that popped up during this review.  no action needs to be taken on them at this time; I want to mull over them a bit before we make a step forward.

- is there a way to reduce the current bundle in the flusher goroutine when a write to the target sink fails *partially*, instead of retrying the entire bundle?

  I am especially wary of situations where either the network config or log collector refuse to process "large writes" in one go, and always chunk them up in smaller units, say 512 bytes at a time. In that case, we're bound to always observe a partial write and the flush would never make progress.
- how is this code meant to interact with the log flush goroutine that already exists in the logging package?
- what would be a good way to reconcile the previous log config option `buffered-writes` and the new `buffering` option?

**Comment by knz** [comment]
Filed the following follow-up issues, and added links where appropriate:

-  log: merge the implementation for file buffering and network buffering #72452 
-  log: unify the async flush goroutine and the buffer sink flusher #72458 
-  log: indicate which sink is the cause of an error when a logging error is reporte #72461 
-  log: simplify the buffering count for flusherCh in bufferSink #72460 
-  log: ensure that the buffer sink flushes do not hog up a server shutdown #72459 
-  log: report the count of dropped message when messages get dropped during buffering #72453 
-  log: drain all buffered log messages during the final flush by the buffered sink #72455 
-  log: prevent deadlock on error when multiple critical errors go to the same buffered sink #72454 

Now that these follow-up issues are filed and linked, we can merge the PR (assuming CI is satisfied)

**Comment by rauchenstein** [comment]
bors r=knz

**Comment by knz** [comment]
@rauchenstein next time please don't forget to link the related github issue (with "Fixes ...")

**Pull request merged**
