### PR TITLE
rowexec: improve join reader memory usage and fix memory accounting in some cases

### PR DESCRIPTION
**Pull request by yuzefovich**
**rowexec: report memory and disk usage of join reader for EXPLAIN ANALYZE**

Release note (sql change): Memory and disk usage are now reported for
the lookup joins in EXPLAIN ANALYZE.

**rowexec: fix memory accounting for the int slices in join reader**

This commit fixes the memory accounting of the int slices in the join
reader ordering strategy. Previously, we would only account for slices
mentioned in `matchingInputRowIndices` if non-nil, completely ignoring
other slices although the slices not mentioned in
`matchingInputRowIndices` are still live. This is now fixed by properly
tracking all slices that can grow arbitrarily large.

There is no regression test for this because there are two memory usages
in the ordering strategy: the slices mentioned above and the row
container for the looked up rows, and the latter will dominate. So
asserting that some minimum memory usage is reported (e.g. via EXPLAIN
ANALYZE) is meaningless because the row container would get up to the
limit, completely hiding how much memory usage for the slices is
reported. I guess we could have a low level test where we'd force the
row container to spill to disk, but it doesn't seem worth it.

This commit also improves the usage of the old slices when a new
two-dimensional slice needs to be allocated. Previously, we would
discard all old slices, so we'd incur more garbage than necessary.

This commit additionally adds a hint if a memory limit error is returned
to the client suggesting to increase the workmem cluster setting or
session variable.

I decided to not add a release note for this commit since my hope is
that not accounting for these int slices should be relatively minor in
comparison to the looked up rows, so this commit probably provides only
a modest protection from OOM scenarios.

Release note: None

**rowexec: improve join reader memory budget usage in some cases**

This commit improves the behavior of join reader ordering strategy when
it encounters a memory error. That strategy has two large memory users:
the disk-backed row container for the looked up rows, and the
two-dimensional int array that stores a mapping from an input row to
positions of all looked up rows corresponding to the input row in the
row container. Previously, it was possible to run into a scenario when
the row container uses most of the memory budget (but doesn't spill to
disk because it doesn't go above the limit), and then we'd get a memory
error when accounting for the int array. This is case is now fixed by
asking the row container to spill to disk if it hasn't already.

It still is possible for the query to error out eventually when the int
array on its own exceeds the memory limit.

Release note (bug fix): Previously, CockroachDB could run into "memory
budget exceeded" errors when performing lookup joins. This is now fixed
in some cases.

Jira issue: CRDB-14736

### CODE REVIEW

**Review by rharding6373 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79250)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @yuzefovich)

___
*[pkg/sql/rowexec/joinreader_strategies.go, line 763 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79250#-MzbB6lx3Td63NeM2m7f:-MzbB6ly8nhCdLzgsThz:b-et21e1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ee17248d052422577e3054d23322faaaf279e35/pkg/sql/rowexec/joinreader_strategies.go#L763)):*
> ```Go
> 		spilled, spillErr := s.lookedUpRows.SpillToDisk(s.Ctx)
> 		if !spilled || spillErr != nil {
> 			return err
> ```

If I understand this correctly, this may return nil for the error if it couldn't spill to disk because all the containers are already spilling to disk. Could this still result in an error, OOM, or panic upstream?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79250)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @rharding6373)

___
*[pkg/sql/rowexec/joinreader_strategies.go, line 763 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79250#-MzbB6lx3Td63NeM2m7f:-MzbhQjy207ct1_06Ph7:bauiw8u) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ee17248d052422577e3054d23322faaaf279e35/pkg/sql/rowexec/joinreader_strategies.go#L763)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

If I understand this correctly, this may return nil for the error if it couldn't spill to disk because all the containers are already spilling to disk. Could this still result in an error, OOM, or panic upstream?
</blockquote></details>

Hm, we return `err` which is the original error we got when calling `ResizeTo`, so it is definitely non-nil in this branch. The logic here if all containers are already using disk or `spillErr` occurred when during spilling, then we return original `err`. I guess we could have done something like `errors.CombineErrors(err, spillErr)` so that we get the spilling error too.

**Review by rharding6373 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79250#-:-MzbzGaI87UeqLM_vxLu:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @mgartner)

___
*[pkg/sql/rowexec/joinreader_strategies.go, line 763 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79250#-MzbB6lx3Td63NeM2m7f:-MzbyFkM27dZup3mnThN:b-lcftz8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ee17248d052422577e3054d23322faaaf279e35/pkg/sql/rowexec/joinreader_strategies.go#L763)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Hm, we return `err` which is the original error we got when calling `ResizeTo`, so it is definitely non-nil in this branch. The logic here if all containers are already using disk or `spillErr` occurred when during spilling, then we return original `err`. I guess we could have done something like `errors.CombineErrors(err, spillErr)` so that we get the spilling error too.
</blockquote></details>

Seems I misread this as spillErr, but that just means that spillErr could have had an error, so the edit with combined errors is welcome. The hint is nice, too :+1:

**Comment by yuzefovich** [comment]
Hold off for now, I want to add some more commits into this PR - I want to have a regression test for this commit, but there is another bug that I need to address first :)

**Review by rharding6373 — COMMENTED** [review]
Whoops, I hadn't seen your comment on #79255 yet...but wouldn't the improvements to `EXPLAIN ANALYZE` also benefit from a backport to 21.1?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79250#-:-Mzc0NwL4uQHJ5X2JrY5:bw0w1q3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @mgartner)

**Review by yuzefovich — COMMENTED** [review]
Okay, I think it's RFAL.

In my opinion, the first commit (EXPLAIN ANALYZE fix) is the least important in this PR. I thought I would use it to add a regression test for the second commit, but that turned out to be quite tricky. There is low risk in backporting the first commit, so we might as well do it.

The second commit has some risk when backporting - since we now will account for more stuff, "budget exceeded" errors might become more likely. However, I think it is still worth it to backport the second commit too. My reasons are:
- not accounting for something is never great, it was our intention to account for thing properly
- the user will now see a hint in the error, so they will have a way forward
- also, the third commit reduces the likelihood of these errors some, so maybe taking all commits together the amount of these errors should remain the same.

The third commit seems definitely worth backporting.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79250#-:-Mzc7opXBsWISesxrbQ9:bd3dp31)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @mgartner)

___
*[pkg/sql/rowexec/joinreader_strategies.go, line 763 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79250#-MzbB6lx3Td63NeM2m7f:-MzblYxg3gFel2IU7P66:b-k6rpab) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ee17248d052422577e3054d23322faaaf279e35/pkg/sql/rowexec/joinreader_strategies.go#L763)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Seems I misread this as spillErr, but that just means that spillErr could have had an error, so the edit with combined errors is welcome. The hint is nice, too :+1: 
</blockquote></details>

Sounds good, thanks.

**Review by mgartner — APPROVED** [review]
Great finds! :lgtm: 

> Reviewed 7 of 7 files at r3, 2 of 2 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79250#-:-MzouJa09xiyJCJS3JIE:b2bx34j)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @yuzefovich)

___
*[pkg/sql/rowexec/joinreader_strategies.go, line 572 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/79250#-MzosoMmAMDmbmEGvA6V:-MzosoMn38xJhH_3EIBq:b-kdyhnj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c60ea85eebd50918817c22016c21663cf2781fb0/pkg/sql/rowexec/joinreader_strategies.go#L572)):*
> ```Go
> 		// Make sure to reuse the old slices.
> 		oldSlices := s.inputRowIdxToLookedUpRowIndices
> 		s.inputRowIdxToLookedUpRowIndices = make([][]int, len(rows))
> ```

Should we reuse `s.inputRowIdxToLookedUpRowIndices` if `len(rows) <= cap(s.inputRowIdxToLookedUpRowIndices)`?
___
*[pkg/sql/rowexec/joinreader_strategies.go, line 577 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/79250#-Mzot0dUATOrHKGh-Vmk:-Mzot0dUATOrHKGh-Vml:b-jhrd66) ([raw file](https://github.com/cockroachdb/cockroach/blob/c60ea85eebd50918817c22016c21663cf2781fb0/pkg/sql/rowexec/joinreader_strategies.go#L577)):*
> ```Go
> 		}
> 		oldAccountedFor := s.accountedFor.inputRowIdxToLookedUpRowIndices
> 		s.accountedFor.inputRowIdxToLookedUpRowIndices = make([]int64, len(rows))
> ```

Ditto, should we reuse this slice if it's capacity is large enough for `rows`?
___
*[pkg/sql/rowexec/joinreader_strategies.go, line 584 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/79250#-MzotV0a5fR7SHJ7arv2:-MzotV0a5fR7SHJ7arv3:bb885n3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c60ea85eebd50918817c22016c21663cf2781fb0/pkg/sql/rowexec/joinreader_strategies.go#L584)):*
> ```Go
> 		sliceOverhead := memsize.IntSliceOverhead*int64(cap(s.inputRowIdxToLookedUpRowIndices)) +
> 			memsize.Int64*int64(cap(s.accountedFor.inputRowIdxToLookedUpRowIndices))
> 		if err := s.memAcc.Grow(s.Ctx, sliceOverhead-s.accountedFor.sliceOverhead); err != nil {
> ```

`Grow` is safe to use with negative values, correct?
___
*[pkg/sql/logictest/testdata/logic_test/lookup_join_local, line 3 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/79250#-MzovKvh9I1O1uMu2HSd:-MzovKvh9I1O1uMu2HSe:b-cp419z) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4ba3f695a5f5f9ff040035815956e4e029b13d5/pkg/sql/logictest/testdata/logic_test/lookup_join_local#L3)):*
> ```
> # LogicTest: local !metamorphic
> 
> # Lower the workmem limit so that less data needs to be inserted. The join
> ```

nit: explain at a high level that you are testing that the row container spills to disk to make room for the the non-spillable internal state of the join reader .

**Review by cucaroach — APPROVED** [review]
:lgtm:

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79250#-:-MzpIxJG-_O1jVrg8cxY:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale) (waiting on @mgartner)

___
*[pkg/sql/rowexec/joinreader_strategies.go, line 572 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/79250#-MzosoMmAMDmbmEGvA6V:-Mzp8i5A9vX5B0xQHocU:b-r8f6xd) ([raw file](https://github.com/cockroachdb/cockroach/blob/c60ea85eebd50918817c22016c21663cf2781fb0/pkg/sql/rowexec/joinreader_strategies.go#L572)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Should we reuse `s.inputRowIdxToLookedUpRowIndices` if `len(rows) <= cap(s.inputRowIdxToLookedUpRowIndices)`?
</blockquote></details>

Yeah, and we do that already - here, we're in the `else` of this condition.
___
*[pkg/sql/rowexec/joinreader_strategies.go, line 577 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/79250#-Mzot0dUATOrHKGh-Vmk:-Mzp9HE-64npimhRpwhI:brhxzla) ([raw file](https://github.com/cockroachdb/cockroach/blob/c60ea85eebd50918817c22016c21663cf2781fb0/pkg/sql/rowexec/joinreader_strategies.go#L577)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Ditto, should we reuse this slice if it's capacity is large enough for `rows`?
</blockquote></details>

It was reused implicitly. I guess it is possible that the capacities of both slices will grow at different rate, so I made a change to reflect that and made the reuse explicit.
___
*[pkg/sql/rowexec/joinreader_strategies.go, line 584 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/79250#-MzotV0a5fR7SHJ7arv2:-MzpArQYCvhUUqFrO5g7:bgm9tym) ([raw file](https://github.com/cockroachdb/cockroach/blob/c60ea85eebd50918817c22016c21663cf2781fb0/pkg/sql/rowexec/joinreader_strategies.go#L584)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

`Grow` is safe to use with negative values, correct?
</blockquote></details>

Correct (however, it's not the most efficient way since it will never release budget back to the monitor), but we should never get a negative value here anyway.

**Comment by yuzefovich** [comment]
Okay, so things aren't so bad - I introduced the bug with memory accounting that is fixed by the second commit in 5b6456bda3cf6bd928668bc610fa24d1350eb093 during 22.1 release cycle, and previously the code seems to have been working correctly. Thus, I think we're safe to backport all commits to 21.2 (but the second commit will only contain the error hint), and we won't increase the likelihood of "budget exceeded" errors in a point release.

**Pull request merged**
