### PR TITLE
sql: rename JSON operators and comparisons

### PR DESCRIPTION
**Pull request by justinj**
Also deleted the unused RemovePath operator in the process.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Great, much better this way! :lgtm:
CC @andy-kimball this will need incorporating in 22319

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22332#-:-L4N42M88Rzkvgh8Bf5-:bewoeu5)*

**Comment by andy-kimball** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[pkg/sql/opt/operator.go, line 85 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22332#-L4N5tqTR29icabGgZM1:-L4N5tqTR29icabGgZM2:bpdtbj2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6bcaab4a2f429dfa8bd0e873e0befa362d67c00/pkg/sql/opt/operator.go#L85)):*
> ```Go
> 	containsOp
> 	// containedByOp is the <@ JSON operator.
> 	containedByOp
> ```

Does this need to be jsonContainedByOp?

---

*[pkg/sql/opt/operator.go, line 86 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22332#-L4N5zfyTCwGI1YjC2Pn:-L4N5zfyTCwGI1YjC2Po:b-4psrqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6bcaab4a2f429dfa8bd0e873e0befa362d67c00/pkg/sql/opt/operator.go#L86)):*
> ```Go
> 	// containedByOp is the <@ JSON operator.
> 	containedByOp
> 	// existenceOp is the ? JSON operator.
> ```

Comments need updating.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22332)*

**Comment by justinj** [comment]
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/operator.go, line 85 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22332#-L4N5tqTR29icabGgZM1:-L4N6n6eDpIL8asQfUGn:b-ufx9dz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6bcaab4a2f429dfa8bd0e873e0befa362d67c00/pkg/sql/opt/operator.go#L85)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Does this need to be jsonContainedByOp?
</blockquote></details>

This one actually does have a slightly more common usage in Postgres as the array contains/containment operator. We don't implement that right now (mostly because we haven't seen much demand yet) but I think it is "known" as that at least as much as it's known as the JSON one as far as Postgres goes.

---

*[pkg/sql/opt/operator.go, line 86 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22332#-L4N5zfyTCwGI1YjC2Pn:-L4N6xsxI5kbLr5hldCs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6bcaab4a2f429dfa8bd0e873e0befa362d67c00/pkg/sql/opt/operator.go#L86)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Comments need updating.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22332)*

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22332#-:-L4N80FgXXiGFW3or-a-:bnfp4nl)*

**Comment by justinj** [comment]
TFTRs!

**Pull request merged**
