### PR TITLE
kvserver,storage: keep timestamps in sync for intents

### LINKED ISSUE #47337: kv: txn recovery false positive
When running kvnemesis on `master` (22d0bb819d42097082b6964c5982d6c381accbdc), I'm able to trigger the `uncommitted txn had writes` invariant in kvnemesis. Looking up in the logs, we always see that these correspond to transactions that have hit `TransactionStatusError: already committed` errors:
```
db0.Txn(ctx, func(ctx context.Context, txn *kv.Txn) error {
    txn.Get(ctx, /Table/50/"8563ef6a") // ("v-3", nil)
    {
      b := &Batch{}
      b.Get(ctx, /Table/50/"c231bad9") // ("v-7", nil)
      txn.Run(ctx, b) // nil
    }
    {
      b := &Batch{}
      b.Put(ctx, /Table/50/"2c797c74", v-8) // nil
      b.Get(ctx, /Table/50/"2c797c74") // ("v-8", nil)
      txn.Run(ctx, b) // nil
    }
    b := &Batch{}
    b.Put(ctx, /Table/50/"ef0bf622", v-9) // TransactionStatusError: already committed (REASON_TXN_COMMITTED)
    txn.CommitInBatch(ctx, b) // TransactionStatusError: already committed (REASON_TXN_COMMITTED)
    return nil
  }) // TransactionStatusError: already committed (REASON_TXN_COMMITTED)
  return nil
})
```
This error is confusing kvnemesis. The transaction actually was committed, but it also returned an error.

Earlier in the logs, we typically see something like:
```
W200410 15:34:02.677376 1176 roachpb/data.go:1059  updating txn "unnamed" meta={id=382643ec key=/Table/50/"2c797c74" pri=0.06695627 epo=2 ts=1586532842.640559886,3 min=1586532842.618701419,0 seq=1} lock=true stat=PENDING rts=1586532842.640559886,3 wto=false max=1586532843.118701419,0 with COMMITTED txn at earlier epoch meta={id=382643ec key=/Table/50/"2c797c74" pri=0.01335293 epo=0 ts=1586532842.618701419,0 min=1586532842.618701419,0 seq=3} lock=true stat=COMMITTED rts=0,0 wto=false max=0,0 int=2
E200410 15:34:02.677447 1176 kv/kvclient/kvcoord/txn_coord_sender.go:793  [n1,txn=382643ec] programming error: ABORTED txn in error: TransactionStatusError: already committed (REASON_TXN_COMMITTED): meta={id=382643ec key=/Table/50/"2c797c74" pri=0.01335293 epo=0 ts=1586532842.618701419,0 min=1586532842.618701419,0 seq=3} lock=true stat=COMMITTED rts=0,0 wto=false max=0,0 int=2. txn: meta={id=382643ec key=/Table/50/"2c797c74" pri=0.01335293 epo=0 ts=1586532842.618701419,0 min=1586532842.618701419,0 seq=3} lock=true stat=COMMITTED rts=0,0 wto=false max=0,0 int=2
W200410 15:34:02.677678 1176 roachpb/data.go:1059  updating txn "unnamed" meta={id=382643ec key=/Table/50/"2c797c74" pri=0.06695627 epo=2 ts=1586532842.640559886,3 min=1586532842.618701419,0 seq=1} lock=true stat=PENDING rts=1586532842.640559886,3 wto=false max=1586532843.118701419,0 with COMMITTED txn at earlier epoch meta={id=382643ec key=/Table/50/"2c797c74" pri=0.01335293 epo=0 ts=1586532842.618701419,0 min=1586532842.618701419,0 seq=3} lock=true stat=COMMITTED rts=0,0 wto=false max=0,0 int=2
E200410 15:34:02.677721 1176 kv/kvclient/kvcoord/txn_coord_sender.go:793  [n1,txn=382643ec] programming error: ABORTED txn in error: TransactionStatusError: already committed (REASON_TXN_COMMITTED): meta={id=382643ec key=/Table/50/"2c797c74" pri=0.01335293 epo=0 ts=1586532842.618701419,0 min=1586532842.618701419,0 seq=3} lock=true stat=COMMITTED rts=0,0 wto=false max=0,0 int=2. txn: meta={id=382643ec key=/Table/50/"2c797c74" pri=0.01335293 epo=0 ts=1586532842.618701419,0 min=1586532842.618701419,0 seq=3} lock=true stat=COMMITTED rts=0,0 wto=false max=0,0 int=2
```
This might give an indication of what's going wrong. Are we retrying when a transaction has already committed?

#### Reproduction steps
```
roachprod create $USER-stress -n 30 --gce-machine-type=n1-standard-8 --local-ssd=false
git checkout master
make roachprod-stress PKG=./pkg/kv/kvnemesis TESTS=TestKVNemesisSingleNode TESTTIMEOUT=4m TESTFLAGS='-v -show-logs' CLUSTER=$USER-stress
```
This is the same error that was supposed to be fixed by https://github.com/cockroachdb/cockroach/pull/46596. Maybe there's something else going on. @andreimatei said he would take a look.

### PR DESCRIPTION
**Pull request by andreimatei**
An intent's timestamp is recorded in 3 places:
1) MVCCMetadata.Timestamp
2) MVCCMetadata.Txn.WriteTimestamp
3) MVCCKey.Timestamp for the key containing the intent's value

Before this patch, a mvccPut that encountered write too old condition
would bump 1) and 3), but not 2). This was bad, as QueryIntent uses 2)
to determine whether or not an intent was pushed above the staging
timestamp. Before this patch, a txn could be erroneously considered
implicitly committed, even though some of its intents had been pushed.

Similarly, a ResolveIntent that's pushing an intent was updating 1) and
3) and not 2).

This patch makes the 3 timestamps be kept in sync - by making mvccPut
and ResolveIntent update all 3.

Fixes: #47337

Release note: None

### CODE REVIEW

**Comment by andreimatei** [comment]
Working on a test

**Review by nvb — COMMENTED** [review]
So far so good, but there's still some testing to add. You'll also want to run `make test PKG=./pkg/storage TESTS=TestMVCCHistories TESTFLAGS=-rewrite` to update those tests.

> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47491#-:-M4un8snE7Pj4xO9QTAX:b-stwxbh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @petermattis)

___
*[pkg/kv/kvnemesis/operations.proto, line 107 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47491#-M4uipKR6oZfg3jwtSQi:-M4uipKR6oZfg3jwtSQj:b-hl0vwb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8a7bc0729ceb035b91390cad1420869798b75ef/pkg/kv/kvnemesis/operations.proto#L107)):*
> ```protobuf
>   util.hlc.Timestamp after = 3 [(gogoproto.nullable) = false];
>   int32 db_id = 4 [(gogoproto.customname) = 'DBID'];
>   string recording = 5;
> ```

nit: Either add a comment or rename to `trace_recording`.
___
*[pkg/kv/kvserver/store_test.go, line 1769 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47491#-M4uihbS4n49SP0nMUaf:-M4uihbS4n49SP0nMUag:b-hbvzq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8b8c57f65c294ff6a33459fd13f639b669a4c28/pkg/kv/kvserver/store_test.go#L1769)):*
> ```Go
> 
> 			// Now, try to read value using the pusher's txn.
> 			ctx, collect, cancel := tracing.ContextWithRecordingSpan(ctx, "reader")
> ```

Do you still need this?
___
*[pkg/kv/kvserver/batcheval/cmd_push_txn.go, line 185 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/47491#-M4ukcnn3WsBLDRrbALF:-M4ukcnn3WsBLDRrbALG:b-w0jaq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/abf75a95888e3df41c39bc5c89cf9e535daecf03/pkg/kv/kvserver/batcheval/cmd_push_txn.go#L185)):*
> ```Go
> 		// the timestamp of the intent. This is another indication of
> 		// client activity.
> 		reply.PusheeTxn.LastHeartbeat.Forward(args.PusheeTxn.WriteTimestamp)
> ```

I think we also need to remove similar logic from `SynthesizeTxnFromMeta`. `LastActive` doesn't seem to consider the `MinTimestamp` at all though, so I think we need to set `LastHeartbeat` to `MinTimestamp` in that function instead. Do you mind pulling all of this into a separate commit (`kv: don't use intent WriteTimestamp to indicate client activity`) so that it's clear what testing changes fell out of it?
___
*[pkg/storage/mvcc.go, line 2810 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/47491#-M4umcdgERyfHjOWhbOd:-M4umcdgERyfHjOWhbOe:b-6gcz12) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8999ae2220b756e3dacc6befa2caad7c49dea3a/pkg/storage/mvcc.go#L2810)):*
> ```Go
> 	// The intent might be committing at a higher timestamp, or it might be
> 	// getting pushed.
> 	newTimestamp := intent.Txn.WriteTimestamp
> ```

This belongs in the branch where it's used. Outside the branch is the "abort" case, which doesn't need this.
___
*[pkg/storage/mvcc.go, line 2830 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/47491#-M4umn940aZFVOaBvn6W:-M4umn940aZFVOaBvn6X:b-xcq4vh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8999ae2220b756e3dacc6befa2caad7c49dea3a/pkg/storage/mvcc.go#L2830)):*
> ```Go
> 		var metaKeySize, metaValSize int64
> 		if !commit {
> 			// Keep existing intent if we're updating it. We keep the
> ```

This comment needs an update.
___
*[pkg/storage/mvcc.go, line 2835 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/47491#-M4umowUCZX9irkhn7IO:-M4umowUCZX9irkhn7IP:bwl1bd1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8999ae2220b756e3dacc6befa2caad7c49dea3a/pkg/storage/mvcc.go#L2835)):*
> ```Go
> 			// pusher's job isn't to do anything to update the intent but
> 			// to move the timestamp forward, even if it can.
> 			metaKeySize, metaValSize, err = buf.putMeta(rw, metaKey, &buf.newMeta)
> ```

How about adding an assertion inside `putMeta` that `meta.Timestamp == meta.Txn.WriteTimestamp`? That would make me more confident that we're handling this correctly in all cases. Is that the only place where we write these `MVCCMetadata` values?

**Review by andreimatei — COMMENTED** [review]
PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47491#-:-M4v98CA9gHqUKTwHAEg:bb71pro)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @nvanbenschoten, and @petermattis)

___
*[pkg/kv/kvnemesis/operations.proto, line 107 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47491#-M4uipKR6oZfg3jwtSQi:-M4v7OyO2FrmphEVcX36:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8a7bc0729ceb035b91390cad1420869798b75ef/pkg/kv/kvnemesis/operations.proto#L107)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: Either add a comment or rename to `trace_recording`.
</blockquote></details>

done
___
*[pkg/kv/kvserver/store_test.go, line 1769 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47491#-M4uihbS4n49SP0nMUaf:-M4usOPP6niGoUu6vlcP:b-hfpv0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8b8c57f65c294ff6a33459fd13f639b669a4c28/pkg/kv/kvserver/store_test.go#L1769)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you still need this?
</blockquote></details>

removed
___
*[pkg/kv/kvserver/batcheval/cmd_push_txn.go, line 185 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/47491#-M4ukcnn3WsBLDRrbALF:-M4uybM03tJe5UO583Qc:b-hvtmw4) ([raw file](https://github.com/cockroachdb/cockroach/blob/abf75a95888e3df41c39bc5c89cf9e535daecf03/pkg/kv/kvserver/batcheval/cmd_push_txn.go#L185)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think we also need to remove similar logic from `SynthesizeTxnFromMeta`. `LastActive` doesn't seem to consider the `MinTimestamp` at all though, so I think we need to set `LastHeartbeat` to `MinTimestamp` in that function instead. Do you mind pulling all of this into a separate commit (`kv: don't use intent WriteTimestamp to indicate client activity`) so that it's clear what testing changes fell out of it?
</blockquote></details>

Done everything. Good catch with the `SynthesizeTxnFromMeta`.
___
*[pkg/storage/mvcc.go, line 2810 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/47491#-M4umcdgERyfHjOWhbOd:-M4v1wkPDeC0j7o_cM2X:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8999ae2220b756e3dacc6befa2caad7c49dea3a/pkg/storage/mvcc.go#L2810)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This belongs in the branch where it's used. Outside the branch is the "abort" case, which doesn't need this.
</blockquote></details>

done
___
*[pkg/storage/mvcc.go, line 2825 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/47491#-M4v1s3c1miVirzrbGDf:-M4v1s3c1miVirzrbGDg:b-o2pndk) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8999ae2220b756e3dacc6befa2caad7c49dea3a/pkg/storage/mvcc.go#L2825)):*
> ```Go
> 		// Set the timestamp for upcoming write (or at least the stats update).
> 		buf.newMeta.Timestamp = hlc.LegacyTimestamp(newTimestamp)
> 		buf.newMeta.Txn.WriteTimestamp = newTimestamp
> ```

you don't think `newMeta` needs to be a deeper copy, do you?
___
*[pkg/storage/mvcc.go, line 2830 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/47491#-M4umn940aZFVOaBvn6W:-M4v2zqgC3sAZ2sWuz-K:b-26r7j7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8999ae2220b756e3dacc6befa2caad7c49dea3a/pkg/storage/mvcc.go#L2830)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This comment needs an update.
</blockquote></details>

How about I take 
// We keep the
// existing metadata instead of using the supplied intent meta
// to avoid overwriting a newer epoch (see comments above)

and move it above, around the setting of `buf.NewMeta`. And delete the rest of this comment?

Or, what do you think I should do. These comments don't make perfect sense to me, tbh.

**Review by nvb — COMMENTED** [review]
This all mostly looks good to me once you address the MinTimestamp comment and make CI happy, but I think we should get a few more eyes on this. Perhaps from @petermattis and @tbg since both of them were around when the scripture was written (is that the idiom I'm looking for? is a tablet involved?).

Also, this change is pretty scary this close to the release. Even if it doesn't have any bugs itself, it's the kind of thing that has a huge blast radius to tickle other bugs. For instance, it changes the timestamp we're storing in `lockTable` for discovered locks. Of course, it's changing it to be more correct, which is why Sumeer and I were interested in this, but it's still shifting the foundation below most of our contention handling. Either before or after we merge it, I think we should proactively kick off a round of roachtests and continue stressing kvnemesis to see if anything falls out.

> Reviewed 10 of 10 files at r6, 3 of 3 files at r7, 1 of 1 files at r8, 2 of 2 files at r9, 6 of 6 files at r10, 8 of 8 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47491#-:-M4vnq013WGxGT4eGe57:b-c942sp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @petermattis)

___
*[pkg/kv/kvserver/batcheval/transaction.go, line 163 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/47491#-M4vjxBS-MK4AxAFjXA_:-M4vjxBS-MK4AxAFjXAa:bxtqgg5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cbed6fc27fee9704543fb37d99df3fe70b34099/pkg/kv/kvserver/batcheval/transaction.go#L163)):*
> ```Go
> 		TxnMeta: txn,
> 		Status:  roachpb.PENDING,
> 		// Set the LastHeartbeat timestamp to the transactions's MinTimestamp. We
> ```

This patch didn't actually do it though.

You'll probably want to use `txnMinTS` for now just to be safe. We could address the TODO below, but now's not the right time to do that.
___
*[pkg/storage/mvcc.go, line 2825 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/47491#-M4v1s3c1miVirzrbGDf:-M4vlbhHCYlMWvZnrqz-:b-svpw26) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8999ae2220b756e3dacc6befa2caad7c49dea3a/pkg/storage/mvcc.go#L2825)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

you don't think `newMeta` needs to be a deeper copy, do you?
</blockquote></details>

Good question. I don't think so because we unmarshal the meta earlier up in this function (in `mvccGetMetadata`), but you should make sure you're convinced of that as well.
___
*[pkg/storage/mvcc.go, line 2830 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/47491#-M4umn940aZFVOaBvn6W:-M4vmWfYDBSfzpaSIeTE:bc8wo6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8999ae2220b756e3dacc6befa2caad7c49dea3a/pkg/storage/mvcc.go#L2830)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

How about I take 
// We keep the
// existing metadata instead of using the supplied intent meta
// to avoid overwriting a newer epoch (see comments above)

and move it above, around the setting of `buf.NewMeta`. And delete the rest of this comment?

Or, what do you think I should do. These comments don't make perfect sense to me, tbh.
</blockquote></details>

I would just qualify the "existing metadata" sentence with something along the lines of "update the existing metadata's timestamp instead of using ..."
___
*[pkg/storage/mvcc.go, line 2835 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/47491#-M4umowUCZX9irkhn7IO:-M4vmxTK8uccdZKlvLE2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8999ae2220b756e3dacc6befa2caad7c49dea3a/pkg/storage/mvcc.go#L2835)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

How about adding an assertion inside `putMeta` that `meta.Timestamp == meta.Txn.WriteTimestamp`? That would make me more confident that we're handling this correctly in all cases. Is that the only place where we write these `MVCCMetadata` values?
</blockquote></details>

Done.

**Review by andreimatei — COMMENTED** [review]
I've been stressing kvnemesis a bunch. Didn't find anything, although I still run into timeouts even if I... what was it... " jitter my range merging attempts". But in between the timeouts its gotten some good mileage.
I've kicked of a round of the various TPCC flavors. Maybe I'll do more roachtests tomorrow.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47491#-:-M4wDHb67kiQEptUDmAM:b-vcuf2z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @nvanbenschoten, and @petermattis)

___
*[pkg/kv/kvserver/batcheval/transaction.go, line 163 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/47491#-M4vjxBS-MK4AxAFjXA_:-M4w4HtCEs5YGYapXCWx:b845d3y) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cbed6fc27fee9704543fb37d99df3fe70b34099/pkg/kv/kvserver/batcheval/transaction.go#L163)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This patch didn't actually do it though.

You'll probably want to use `txnMinTS` for now just to be safe. We could address the TODO below, but now's not the right time to do that.
</blockquote></details>

oops, it got lost in the shuffle
___
*[pkg/storage/mvcc.go, line 2830 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/47491#-M4umn940aZFVOaBvn6W:-M4w4p3fCbrc2-uWEQ-h:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8999ae2220b756e3dacc6befa2caad7c49dea3a/pkg/storage/mvcc.go#L2830)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I would just qualify the "existing metadata" sentence with something along the lines of "update the existing metadata's timestamp instead of using ..."
</blockquote></details>

done

**Review by andreimatei — COMMENTED** [review]
I've started a run of all the roachtests. We're half-way through and so far so good.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47491#-:-M4yh9S6DtWLSQu1JpU5:b-etqlq9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @nvanbenschoten, and @petermattis)

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47491)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @petermattis)

___
*[pkg/storage/mvcc.go, line 2825 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/47491#-M4v1s3c1miVirzrbGDf:-M4yjo3HCmxSBOZCLtUW:b-q71t35) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8999ae2220b756e3dacc6befa2caad7c49dea3a/pkg/storage/mvcc.go#L2825)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Good question. I don't think so because we unmarshal the meta earlier up in this function (in `mvccGetMetadata`), but you should make sure you're convinced of that as well.
</blockquote></details>

I'm convinced as well.

**Review by nvb — APPROVED** [review]
:lgtm: but I still think someone else should take a look at this.

> Reviewed 1 of 9 files at r12, 8 of 8 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47491#-:-M4yklYL6sS5mTPtqG4g:b-m384ol)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @petermattis)

___
*[pkg/kv/kvserver/batcheval/transaction.go, line 163 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/47491#-M4vjxBS-MK4AxAFjXA_:-M4ykYIY1iZ3j_cWhpVx:b-n64aws) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cbed6fc27fee9704543fb37d99df3fe70b34099/pkg/kv/kvserver/batcheval/transaction.go#L163)):*
> You'll probably want to use txnMinTS for now just to be safe.

This part was missed. It still shouldn't matter, but I think it's better to be safe here.

**Comment by tbg** [comment]
I can take a look tomorrow, unless someone else beats me to it.

**Review by andreimatei — COMMENTED** [review]
roachtests looking ok. I'm gonna merge this since we're in a hurry. Will welcome reviews after the fact too..

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47491#-:-M4zA7IIDaEFp_75ySrF:b-r6yj3i)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @nvanbenschoten, and @petermattis)

___
*[pkg/kv/kvserver/batcheval/transaction.go, line 163 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/47491#-M4vjxBS-MK4AxAFjXA_:-M4zA5qKBAotqcTRknYd:bb71pro) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cbed6fc27fee9704543fb37d99df3fe70b34099/pkg/kv/kvserver/batcheval/transaction.go#L163)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> You'll probably want to use txnMinTS for now just to be safe.

This part was missed. It still shouldn't matter, but I think it's better to be safe here.
</blockquote></details>

PTAL

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47491#-:-M4zR2ytAOSVK0lQKbyV:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @petermattis)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47491#-:-M4zXfEv05OZfJZ9WA3S:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @petermattis)

**Pull request merged**
