### PR TITLE
opt: disable index recommendations for system tables

### LINKED ISSUE #80910: sql: do not show EXPLAIN index recommendation for system tables
We should not show index recommendations for system tables because the user cannot create indexes on these tables.

```
defaultdb> explain select * from system.table_statistics where name = 'hello';
                                                                             info
---------------------------------------------------------------------------------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • filter
  │ filter: name = 'hello'
  │
  └── • scan
        missing stats
        table: table_statistics@primary
        spans: FULL SCAN

  index recommendations: 1
  1. type: index creation
     SQL command: CREATE INDEX ON table_statistics (name) STORING ("columnIDs", "createdAt", "rowCount", "distinctCount", "nullCount", histogram, "avgSize");
(14 rows)
```

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: add system tables to testcat

Release note: None

#### opt: disable index recommendations for system tables

Fixes #80910

Release note (bug fix): Index recommendations are no longer presented
for system tables in the output of `EXPLAIN` statements.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80923#-:-N1AR2Mn53MFXMEighVL:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @msirek)

___
*[`pkg/sql/opt/indexrec/testdata/index-candidates-recommendations` line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80923#-N1AQtypArAae-auzrd4:-N1AQtypArAae-auzrd5:b-ud90s1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3625729ae64c7554e41f53f6771dfea58742b18/pkg/sql/opt/indexrec/testdata/index-candidates-recommendations#L34)):*
> ```
>  (k)
> 
> # Ensure that index candidates are not created for virtual tables.
> ```

nit: virtual -> system

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80923)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @msirek and @rytaft)

___
*[`pkg/sql/opt/indexrec/testdata/index-candidates-recommendations` line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80923#-N1AQtypArAae-auzrd4:-N1Ag8Vz-zzOfSDleCbn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3625729ae64c7554e41f53f6771dfea58742b18/pkg/sql/opt/indexrec/testdata/index-candidates-recommendations#L34)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: virtual -> system
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80923)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @msirek)

**Review by msirek — APPROVED** [review]
Very nice!
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80923#-:-N1Aqaz317jId-J35sxQ:b-z5m9g7)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
