### PR TITLE
vendor: bump panicparse to v2.2.2

### PR DESCRIPTION
**Pull request by tbg**
This is a reincarnation of #81089, which was reverted in #81126.
This time around, we pick up upstream PR [78] which renames the
unicode file that prompted #81126.

[78]: https://github.com/maruel/panicparse/pull/78

Release note: None

### CODE REVIEW

**Review by rickystewart — CHANGES_REQUESTED** [review]
Did you `dev generate bazel --mirror`? I would expect to see changes to `DEPS.bzl` for this change.

**Comment by tbg** [comment]
Good point, fixed.

**Review by rickystewart — APPROVED** [review]

**Review by HonoreDB — APPROVED** [review]
Oh cool, you fixed it upstream!

> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81240#-:-N1yI1Om6yZMAY7ojO9Y:b-c70odf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB)

**Comment by rickystewart** [comment]
Looks like you need to do `go mod tidy` as well?

**Comment by tbg** [comment]
> 
Looks like you need to do go mod tidy as well?

Ugh, yeah. I thought `make -k vendor_rebuild` did that for me. Third time's the charm...

**Comment by tbg** [comment]
bors r=HonoreDB,rickystewart
TFTRs!

**Pull request merged**
