### PR TITLE
hlc: handle synthetic bit in timestamp.{Forward,Backward}

### PR DESCRIPTION
**Pull request by nvb**
See `Timestamp.Forward` section in #52745.

This commit updates the `Timestamp.Forward` and `Timestamp.Backward`
methods to properly propagate the synthetic bit to their output. The
general rule here is that:
1. if the larger input is not synthetic, the output input is not either
2. if the timestamps are equal and either is non-synthetic, the output
   is not either.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Friendly ping.

**Review by aayushshah15 — APPROVED** [review]
:lgtm_strong: apologies for procrastinating on this.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57387#-:-MO9rJiACKYPcFm3kXb4:bd9s682)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by nvanbenschoten** [comment]
TFTR!

bors r+

**Comment by nvanbenschoten** [comment]
Flake was another instance of https://github.com/cockroachdb/cockroach/issues/57785.

bors r+

**Pull request merged**
