### PR TITLE
kv: add server-side metrics for {successful,failed} 1PC evaluation

### PR DESCRIPTION
**Pull request by arulajmani**
This patch adds metrics for successful and failed 1PC evaluations, which together give us the number of attempted 1PC evaluations by a store. We then modify an existing test to use these metrics to verify that it was able to successfully commit using 1PC.

Epic: None
Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113897)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/metrics.go` line 484 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113897#-NifoPfY2H0BZIJB-NjF:-NifoPfY2H0BZIJB-NjG:b17n3ih) ([raw file](https://github.com/cockroachdb/cockroach/blob/93b55ca5217b898b10028568538583a757730008/pkg/kv/kvserver/metrics.go#L484)):*
> ```Go
> 	}
> 	metaFailed1PC = metric.Metadata{
> 		Name:        "txn.server_side.1PC.success",
> ```

"failure"

(note: not using "failed" to match `metaReadWithinUncertaintyIntervalErrorServerSideRetryFailure`)
___
*[`pkg/kv/kvserver/metrics.go` line 485 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113897#-NifoaCuEkOj2yAicBLY:-NifoaCuEkOj2yAicBLZ:b-rapruu) ([raw file](https://github.com/cockroachdb/cockroach/blob/93b55ca5217b898b10028568538583a757730008/pkg/kv/kvserver/metrics.go#L485)):*
> ```Go
> 	metaFailed1PC = metric.Metadata{
> 		Name:        "txn.server_side.1PC.success",
> 		Help:        "Number of batches that attempted to commit using 1PC",
> ```

"and failed"

Otherwise, this should also include successes.
___
*[`pkg/kv/kvserver/metrics.go` line 2372 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113897#-Nifogv95E-mFNxc3U2B:-Nifogv95E-mFNxc3U2C:b-rjqln6) ([raw file](https://github.com/cockroachdb/cockroach/blob/93b55ca5217b898b10028568538583a757730008/pkg/kv/kvserver/metrics.go#L2372)):*
> ```Go
> 	ReadWithinUncertaintyIntervalErrorServerSideRetrySuccess *metric.Counter
> 	ReadWithinUncertaintyIntervalErrorServerSideRetryFailure *metric.Counter
> 	Successful1PC                                            *metric.Counter
> ```

We should invert these names so that the qualifier (successful, failed) is scoped below the subject (one-phase commit). Maybe `OnePhaseCommitSuccess` and `OnePhaseCommitFailure`.

I guess this should extend to the `meta...` variables as well.

**Review by arulajmani — COMMENTED** [review]
RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113897#-:-NijMvbbCnbO9xAepl1a:bb72pd0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/metrics.go` line 485 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113897#-NifoaCuEkOj2yAicBLY:-NijMIkIBx5wAprhQZp2:bj85twx) ([raw file](https://github.com/cockroachdb/cockroach/blob/93b55ca5217b898b10028568538583a757730008/pkg/kv/kvserver/metrics.go#L485)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"and failed"

Otherwise, this should also include successes.
</blockquote></details>

My bad -- I copy pasted these, got dragged away, and didn't realize I hadn't updated them. 
___
*[`pkg/kv/kvserver/metrics.go` line 2372 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113897#-Nifogv95E-mFNxc3U2B:-NijMTri6OBEF1fMGvAY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/93b55ca5217b898b10028568538583a757730008/pkg/kv/kvserver/metrics.go#L2372)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We should invert these names so that the qualifier (successful, failed) is scoped below the subject (one-phase commit). Maybe `OnePhaseCommitSuccess` and `OnePhaseCommitFailure`.

I guess this should extend to the `meta...` variables as well.
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm: once you run `dev gen` to get CI green.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113897#-:-Nijzugb1WdSrZJUzclm:b-hr08qn)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Review by arulajmani — COMMENTED** [review]
> run `dev gen` to get CI green.

Done. TFTR!

bors r=nvanbenschoten

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113897#-:-Nik8KLd4HdCuIWNB6by:b-qdnnx5)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

**Pull request merged**
