### PR TITLE
sql: Fix broken view logic test

### PR DESCRIPTION
**Pull request by a-robinson**
I have no idea how this passed the PR builder on #9988

http://stream1.gifsoup.com/view3/2323130/shame-cube-o.gif

@jordanlewis

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10086)

### CODE REVIEW

**Review by dt — APPROVED** [review]

**Review by petermattis — APPROVED** [review]
LGTM

**Comment by tschottdorf** [comment]
> I have no idea how this passed the PR builder on #9988

Will you take a look?

**Comment by a-robinson** [comment]
Looking

**Comment by a-robinson** [comment]
Looks like it's because change #9988 hadn't been rebased on top of #10009, which added the test statement that needed to be updated. And I presume teamcity just tests the branch as is rather than trying to run the tests with the commits on top of the master branch.

Is that working as intended, @jordanlewis?

**Comment by jordanlewis** [comment]
Yes, that's the expected behavior - that's why we re-run the tests on the merge commit that GitHub creates.

GitHub does expose a ref for each pull request that is the result of merging the pull request, but for some reason this ref is updated each time someone so much as looks at the pull request in a web browser. The result is CI building pull requests over and over again for no reason, so we don't use this option.

**Pull request merged**
