### PR TITLE
deps: bump go.etcd.io/etcd

### PR DESCRIPTION
**Pull request by danhhz**
To pick up https://github.com/etcd-io/etcd/pull/10864.

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]

**Review by danhhz — COMMENTED** [review]
Updated a bunch of stuff to the new naming, but I'm still seeing a couple tests fail with unexpected snapshots

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38913#-:-LjwsJCvE1MHVfMlnucW:b-5h10p9)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/split_delay_helper_test.go, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38913#-Ljws62AD--a3STYnSyJ:-Ljws62B6ndeHDY477ao:b-r7avxs) ([raw file](https://github.com/cockroachdb/cockroach/blob/80c8cc7cb06a6131c9a3cb2f999b3a05f773b138/pkg/storage/split_delay_helper_test.go#L111)):*
> ```Go
> 							RecentActive: true,
> 							ProbeSent:    true, // Unifies string output below.
> 							Inflights:    &tracker.Inflights{},
> ```

This was panic'ing in `(tracker.Progress).String` if Inflights was nil. Do we care?

**Review by tbg — COMMENTED** [review]
I'm going to take a look at this branch. The upstream changes were invasive, I wouldn't be 100% surprised if there were some fallout.

> Reviewed 2 of 2 files at r1, 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38913#-:-LjzO1ULBkxxWUNw6ktE:b-adtnsw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz)

___
*[pkg/storage/split_delay_helper_test.go, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38913#-Ljws62AD--a3STYnSyJ:-LjzNZUuCrcRUETNhcXp:b-j2tffu) ([raw file](https://github.com/cockroachdb/cockroach/blob/80c8cc7cb06a6131c9a3cb2f999b3a05f773b138/pkg/storage/split_delay_helper_test.go#L111)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

This was panic'ing in `(tracker.Progress).String` if Inflights was nil. Do we care?
</blockquote></details>

That's OK, Inflights is never nil inside of Raft. BTW there is `tracker.NewInflights`.

**Review by tbg — COMMENTED** [review]
> Reviewed 18 of 18 files at r3, 2 of 2 files at r4, 3 of 3 files at r5, 14 of 14 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38913)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz)

**Review by tbg — COMMENTED** [review]
Ok, this wasn't hard to figure out. First of all I was wrong about the `Inflights` field, we nilled that intentionally sometimes, which was a bad idea and I'm fixing it in https://github.com/etcd-io/etcd/pull/10903; updated the vendor PR to pick up this fix (when it merges I have to amend the commit to vendor from the upstream repo, but I want to see if tests turn green).

The denied snapshot thing was actually discarded snapshots because I put more safety checks into raft and of course preemptive snapshots failed them. We need to lie a little more when creating the temporary raft group that applies the snap. See the corresponding commit.

Have some hope that this will now turn green, we'll see.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38913#-:-LjzimKN27plUm7vFpG1:b-s9fuq1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz)

**Comment by tbg** [comment]
Yep, it's green. So we just have to get https://github.com/etcd-io/etcd/pull/10903 merged and update the vendored ref.

**Review by tbg — APPROVED** [review]
:lgtm:

> Reviewed 19 of 19 files at r7, 2 of 2 files at r8, 17 of 17 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38913#-:-Lk5nBZf13x_zhkpSpH6:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz)

**Comment by danhhz** [comment]
TFTR!

bors r=tbg

**Pull request merged**
