### PR TITLE
ui: add static images to asset build step

### LINKED ISSUE #117876: CockroachDB favicon does not render for DB Console running v23.1.13
**Describe the problem**

CockroachDB favicon does not render for DB Console running v23.1.13

image (3)

**To Reproduce**

Upgrade from v22.2.x

**Expected behavior**
Favicon restored

**Additional context**
Operator Inconvenienced 

Jira issue: CRDB-35397

### PR DESCRIPTION
**Pull request by dhartunian**
During the `genassets` build + embed step, we were taking just the output of the `db-console-ccl` or `db-console-oss` step which is just a build.js file. This commit adds references to the image assets we want bundled as well. This includes favicon.ico and everything in `./ assets` relative to the db-console build directory.

We disable content hashing in webpack in order to keep the filenames static, which bazel requires. The impact should be minimal as we rarely change these images so if they're cached forever, it's fine.

This change restores the favicon to the CRDB build and the nice image that shows up in the background of the email signup bar.

The size of the final zipped bundle only differs by around 1MB and is already 10MB in size.

Fixes: #117876
Epic: None

Release note (ui change): the favicon now renders properly for DB Console along with other image files.

### CODE REVIEW

**Review by abarganier — COMMENTED** [review]
LGTM, but I'll let Ricky and Lauren give the approval. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121380#-:-NuZV7eNAca53oplMYOX:bv8e8mw)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @laurenbarker, and @rickystewart)

___
*[`pkg/ui/workspaces/db-console/BUILD.bazel` line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121380#-NuZV-1ED9MHP4gD5-vZ:-NuZV-1ED9MHP4gD5-v_:bpmghrq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f0749171ad1164259d9e2316c12260af3eb47c5/pkg/ui/workspaces/db-console/BUILD.bazel#L62)):*
> ```Starlark
>     outs = [
>         "db-console-ccl/assets/bundle.js",
>         "db-console-ccl/assets/favicon.ico",
> ```

Just curious, is there a reason we can't use wildcard patterns here for the assets dir?

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121380)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @laurenbarker, and @rickystewart)

___
*[`pkg/ui/workspaces/db-console/BUILD.bazel` line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121380#-NuZV-1ED9MHP4gD5-vZ:-NueEBR741kt-n8JCGWW:buc6pz2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f0749171ad1164259d9e2316c12260af3eb47c5/pkg/ui/workspaces/db-console/BUILD.bazel#L62)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Just curious, is there a reason we can't use wildcard patterns here for the assets dir?
</blockquote></details>

your question is the core of why UI builds with bazel are hard: bazel requires explicit definition of all outputs. hence you can't use wildcards, and you can't have webpack tell bazel what the names of the outputs are at runtime (if their names are hashes for instance).

**Review by laurenbarker — APPROVED** [review]
This seems reasonable to me. LGTM

**Comment by dhartunian** [comment]
TFTR!

bors r=laurenbarker

**Comment by yuzefovich** [comment]
CI seems to be red.

bors r-

**Comment by dhartunian** [comment]
thanks @yuzefovich I see the problem. my build config is not OSS-compatible. I will fix.

**Comment by dhartunian** [comment]
bors r=laurenbarker

**Comment by rail** [comment]
bors retry
(it crashed)

**Pull request merged**
