### PR TITLE
metric: Add HTTP endpoint for metric rules.

### LINKED ISSUE #69793: metrics: Create HTTP endpoint and test frameworks for testing alert and aggregation rules.
This issue tracks the implementation of the HTTP endpoint to export the registered rules in YAML format. We should also implement a unit test framework and integration tests which will allow for new alert and aggregation rules and endpoint to be tested.

Epic: [CRDB 2573](https://cockroachlabs.atlassian.net/browse/CRDB-2573#icft=CRDB-2573)

### PR DESCRIPTION
**Pull request by rimadeodhar**
This PR adds an HTTP endpoint api/v2/rules which exports all
alerting and aggregation rules defined for CRDB metrics in a
Prometheus compatible format.

Release note (ui change): The Advanced Debug page on DBConsole
contains an additional link under the metrics header called
Rules. This endpoint exposes Prometheus compatible alerting
and aggregation rules for CRDB metrics.
Release note (ops change): We expose an additional HTTP
endpoint /api/v2/rules/ which exposes Prometheus compatible
alerting and aggregation rules for CRDB metrics.

Resolves https://github.com/cockroachdb/cockroach/issues/69793

### CODE REVIEW

**Review by dhartunian — CHANGES_REQUESTED** [review]
> Reviewed 12 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72677)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @rimadeodhar)

___
*[-- commits, line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72677#-ModgSy8A9MWftRCoIfD):*
nit: consider adding a second release note with `(ops change)` as well since this feature is accessible outside of the UI.
___
*[pkg/kv/kvserver/metric_rules.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72677#-ModiQ6JDg1vcb8QKgcI:-ModiQ6JDg1vcb8QKgcJ:bhyae6j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d51a3a0d65f107eab5d222248f46858cdd22b636/pkg/kv/kvserver/metric_rules.go#L56)):*
> ```Go
> // to the rule registry for tracking. All rules are exported in the
> // YAML format.
> func (mr *MetricRules) CreateAndAddRules(ctx context.Context) {
> ```

Could we create all the rules in an `init()` function and just append them later when the registry is available? The readability of the rules gets a bit muddy when they're all behind a function name. It would be nice if the rules were all in a map literal or something so you can see all them together with their prom expressions.

Maybe we can have all the rule inputs in a big struct array, and iterate through it to add them all to the registry? Then the call to `NewAlertingRule` can be shared in a loop.
___
*[pkg/server/api_v2.go, line 344 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72677#-ModhVwH12-H4oNNH-4k:-ModhVwH12-H4oNNH-4l:b-tfdnh0) ([raw file](https://github.com/cockroachdb/cockroach/blob/d51a3a0d65f107eab5d222248f46858cdd22b636/pkg/server/api_v2.go#L344)):*
> ```Go
> //       "$ref": "#/definitions/PrometheusRuleGroup"
> func (a *apiV2Server) listRules(w http.ResponseWriter, r *http.Request) {
> 	w.Header().Set(httputil.ContentTypeHeader, httputil.PlaintextContentType)
> ```

Do you want to set the header only if `err !=nil`? Otherwise we might return an error with a `text/plain` content type.
___
*[pkg/server/api_v2.go, line 350 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72677#-ModhKzB3rvqDIcnOCr2:-ModhKzB3rvqDIcnOCr3:b-h4kdyw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d51a3a0d65f107eab5d222248f46858cdd22b636/pkg/server/api_v2.go#L350)):*
> ```Go
> 		apiV2InternalError(r.Context(), err, w)
> 	}
> 	w.WriteHeader(http.StatusOK)
> ```

`Write` will write OK status by default I believe, this might be unnecessary.
___
*[pkg/server/server.go, line 412 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72677#-Modi0Yk-mev74a5BXm-:-Modi0Yk-mev74a5BXm0:b-k6tono) ([raw file](https://github.com/cockroachdb/cockroach/blob/d51a3a0d65f107eab5d222248f46858cdd22b636/pkg/server/server.go#L412)):*
> ```Go
> 	// Create and add KV metric rules
> 	kvRules := kvserver.NewMetricRules(ruleRegistry)
> 	kvRules.CreateAndAddRules(ctx)
> ```

Just in terms of the API, why does usage require two separate calls first the `kvserver` and then to `kvRules`? Could we do it in one call? If the second one takes no interesting arguments and returns nothing we care about then I don't see why we need it.

**Review by rimadeodhar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72677)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @rimadeodhar)

___
*[pkg/kv/kvserver/metric_rules.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72677#-ModiQ6JDg1vcb8QKgcI:-MopHAD4-_Ut7VBx0gWt:b-m389xm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d51a3a0d65f107eab5d222248f46858cdd22b636/pkg/kv/kvserver/metric_rules.go#L56)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Could we create all the rules in an `init()` function and just append them later when the registry is available? The readability of the rules gets a bit muddy when they're all behind a function name. It would be nice if the rules were all in a map literal or something so you can see all them together with their prom expressions.

Maybe we can have all the rule inputs in a big struct array, and iterate through it to add them all to the registry? Then the call to `NewAlertingRule` can be shared in a loop.
</blockquote></details>

I considered this initially but ruled it out because the rule structs are not easy to construct them inline as you would in a literal. They have complex fields which would make it fairly unwieldy. Having individual functions for them with a top level function initializing and registering all of them felt like a nice compromise.
___
*[pkg/server/api_v2.go, line 344 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72677#-ModhVwH12-H4oNNH-4k:-MopHUsG96mDo5z8qPl5:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/d51a3a0d65f107eab5d222248f46858cdd22b636/pkg/server/api_v2.go#L344)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Do you want to set the header only if `err !=nil`? Otherwise we might return an error with a `text/plain` content type.
</blockquote></details>

Good point, done.
___
*[pkg/server/api_v2.go, line 350 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72677#-ModhKzB3rvqDIcnOCr2:-MopHWMR0B8-l_26DBKG:b-j1xdbn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d51a3a0d65f107eab5d222248f46858cdd22b636/pkg/server/api_v2.go#L350)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

`Write` will write OK status by default I believe, this might be unnecessary.
</blockquote></details>

Yes, you are right. I have removed it.
___
*[pkg/server/server.go, line 412 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72677#-Modi0Yk-mev74a5BXm-:-MopHZll5CjjcltIZlbp:b-7nbrx5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d51a3a0d65f107eab5d222248f46858cdd22b636/pkg/server/server.go#L412)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Just in terms of the API, why does usage require two separate calls first the `kvserver` and then to `kvRules`? Could we do it in one call? If the second one takes no interesting arguments and returns nothing we care about then I don't see why we need it.
</blockquote></details>

Hmm makes sense. Refactored it as a single call.

**Review by dhartunian — APPROVED** [review]
:lgtm: as far as the code goes. Mostly just questions about the alerts themselves which we can resolve separately or outside the PR if you like.

> Reviewed 1 of 15 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72677#-:-MopNtglAfJCOUhQi_Hx:beealcn)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rimadeodhar)

___
*[-- commits, line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72677#-ModgSy8A9MWftRCoIfD):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: consider adding a second release note with `(ops change)` as well since this feature is accessible outside of the UI.
</blockquote></details>

nit: can you add the PR change to the commit? I believe bors picks up the commits, not the PR messages.
___
*[pkg/kv/kvserver/metric_rules.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72677#-ModiQ6JDg1vcb8QKgcI:-MopNb2F5aXK9aUXqJzg:bsvkegk) ([raw file](https://github.com/cockroachdb/cockroach/blob/d51a3a0d65f107eab5d222248f46858cdd22b636/pkg/kv/kvserver/metric_rules.go#L56)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

I considered this initially but ruled it out because the rule structs are not easy to construct them inline as you would in a literal. They have complex fields which would make it fairly unwieldy. Having individual functions for them with a top level function initializing and registering all of them felt like a nice compromise.
</blockquote></details>

:thumbsup: thx for the context.
___
*[pkg/kv/kvserver/metric_rules.go, line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72677#-MopODk72ey4SMBcMhR0:-MopODk72ey4SMBcMhR1:bvfmpxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/89fbaa059b9add36e4ecb6f84f7c10ba211545a9/pkg/kv/kvserver/metric_rules.go#L63)):*
> ```Go
> 	})
> 	recommendedHoldDuration := 10 * time.Minute
> 	help := "This check detects when the number of ranges with less than quorum replicas live are non-zero for too long"
> ```

In general, I feel like there's a step missing from the help strings which is..."now what?". I'm not sure if customers know what to do when these alerts fire.
___
*[pkg/kv/kvserver/metric_rules.go, line 178 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72677#-MopORAh04ebd0-I5kox:-MopORAh04ebd0-I5koy:b-6yysrp) ([raw file](https://github.com/cockroachdb/cockroach/blob/89fbaa059b9add36e4ecb6f84f7c10ba211545a9/pkg/kv/kvserver/metric_rules.go#L178)):*
> ```Go
> ) {
> 	expr := "sum without(store) (capacity_available)"
> 	help := "Aggregation expression to compute available capacity for a node."
> ```

All the capacity descriptions should have some metadata around what capacity they refer to...disk space? what units? Or is that info somewhere else. We've had to add a lot of detailed tooltips in the past to capacity metrics in the DB console to clarify exactly what they refer to.

**Review by rimadeodhar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72677)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[-- commits, line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72677#-ModgSy8A9MWftRCoIfD):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: can you add the PR change to the commit? I believe bors picks up the commits, not the PR messages.
</blockquote></details>

Oh didn't know that. Will do.
___
*[pkg/kv/kvserver/metric_rules.go, line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72677#-MopODk72ey4SMBcMhR0:-MotX3KaEHLWiX0au-X_:b-8nqnc2) ([raw file](https://github.com/cockroachdb/cockroach/blob/89fbaa059b9add36e4ecb6f84f7c10ba211545a9/pkg/kv/kvserver/metric_rules.go#L63)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

In general, I feel like there's a step missing from the help strings which is..."now what?". I'm not sure if customers know what to do when these alerts fire.
</blockquote></details>

Sounds like you're thinking about providing information along the lines of a runbook which this help string is not well suited for. There are ways by which runbook like information can be provided i.e. what to do when the alert fires etc. The field for that is the `annotations` field which allows engineers to specify any additional information about the metric (the prometheus documentation also recommends putting runbook like information within annotations so that approach aligns with Prometheus compatibility as well https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/). I think I can add some comments within the AlertingRule struct to clarify this.

My initial thought for the help string was to marshal it as comments within the output YAML. But the YAML marshalling library makes it very complicated to add comments to alerts and aggregation rules. So I'm thinking of getting rid of that field altogether in lieu of the annotations field. We can discuss this more offline as well.
___
*[pkg/kv/kvserver/metric_rules.go, line 178 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72677#-MopORAh04ebd0-I5kox:-MotXyg16nwHIpqHTptt:b-tqqp7c) ([raw file](https://github.com/cockroachdb/cockroach/blob/89fbaa059b9add36e4ecb6f84f7c10ba211545a9/pkg/kv/kvserver/metric_rules.go#L178)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

All the capacity descriptions should have some metadata around what capacity they refer to...disk space? what units? Or is that info somewhere else. We've had to add a lot of detailed tooltips in the past to capacity metrics in the DB console to clarify exactly what they refer to.
</blockquote></details>

See comment above. I think a lot of the "help" information can (and probably should) be stored within annotations/labels and we can get rid of `help` field altogether.

**Review by rimadeodhar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72677)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[pkg/kv/kvserver/metric_rules.go, line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72677#-MopODk72ey4SMBcMhR0:-MotZfq14IshaSRIK5K1:bp2ll38) ([raw file](https://github.com/cockroachdb/cockroach/blob/89fbaa059b9add36e4ecb6f84f7c10ba211545a9/pkg/kv/kvserver/metric_rules.go#L63)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Sounds like you're thinking about providing information along the lines of a runbook which this help string is not well suited for. There are ways by which runbook like information can be provided i.e. what to do when the alert fires etc. The field for that is the `annotations` field which allows engineers to specify any additional information about the metric (the prometheus documentation also recommends putting runbook like information within annotations so that approach aligns with Prometheus compatibility as well https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/). I think I can add some comments within the AlertingRule struct to clarify this.

My initial thought for the help string was to marshal it as comments within the output YAML. But the YAML marshalling library makes it very complicated to add comments to alerts and aggregation rules. So I'm thinking of getting rid of that field altogether in lieu of the annotations field. We can discuss this more offline as well.
</blockquote></details>

Also, I think for the alerts that are specifically being added here, let me find out if we have any runbook like information that I can add here to these alerts.

**Review by dhartunian — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72677)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rimadeodhar)

___
*[pkg/kv/kvserver/metric_rules.go, line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72677#-MopODk72ey4SMBcMhR0:-Mp7jP2y2qfruIDS-7Q8:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/89fbaa059b9add36e4ecb6f84f7c10ba211545a9/pkg/kv/kvserver/metric_rules.go#L63)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Also, I think for the alerts that are specifically being added here, let me find out if we have any runbook like information that I can add here to these alerts.
</blockquote></details>

:thumbsup: 
___
*[pkg/kv/kvserver/metric_rules.go, line 178 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72677#-MopORAh04ebd0-I5kox:-Mp7jJy9ApbSlEggefhQ:bdoh087) ([raw file](https://github.com/cockroachdb/cockroach/blob/89fbaa059b9add36e4ecb6f84f7c10ba211545a9/pkg/kv/kvserver/metric_rules.go#L178)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

See comment above. I think a lot of the "help" information can (and probably should) be stored within annotations/labels and we can get rid of `help` field altogether.
</blockquote></details>

Ah thx for clarifying.
___
*[pkg/server/api_v2.go, line 350 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72677#-Mp7j9LZBqJui81nbl9F:-Mp7j9LZBqJui81nbl9G:b-li95vq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e95ce9598d593cb87f352e6e9d25e24a2da9bc8/pkg/server/api_v2.go#L350)):*
> ```Go
> 	}
> 	w.Header().Set(httputil.ContentTypeHeader, httputil.PlaintextContentType)
> 	_, _ = w.Write(response)
> ```

nit: should the error be logged?

**Review by rimadeodhar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72677)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian and @rimadeodhar)

___
*[pkg/server/api_v2.go, line 350 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72677#-Mp7j9LZBqJui81nbl9F:-Mp84DSmCFsPM2KUmNZx:bvqz1r8) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e95ce9598d593cb87f352e6e9d25e24a2da9bc8/pkg/server/api_v2.go#L350)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: should the error be logged?
</blockquote></details>

Not necessary. None of the other api/v2 endpoints output this error while writing the response so kept it consistent with that.

**Review by rimadeodhar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72677)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian and @rimadeodhar)

___
*[pkg/kv/kvserver/metric_rules.go, line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72677#-MopODk72ey4SMBcMhR0:-Mp84Luh7slcEddcNwZS:bkmr87z) ([raw file](https://github.com/cockroachdb/cockroach/blob/89fbaa059b9add36e4ecb6f84f7c10ba211545a9/pkg/kv/kvserver/metric_rules.go#L63)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

:thumbsup: 
</blockquote></details>

There are no runbooks as of today specifically for these alerts. So I'm going to go ahead and merge but when I put out the doc on how to use this framework, I'm going to call out the need to add runbooks.

**Comment by rimadeodhar** [comment]
TFTR!

bors r=dhartunian

**Comment by rimadeodhar** [comment]
TFTR!

bors r=dhartunian

**Comment by rimadeodhar** [comment]
bors cancel

**Comment by rimadeodhar** [comment]
TFTR!

bors r=dhartunian

**Pull request merged**
