### PR TITLE
exec: add support for RIGHT OUTER in merge join

### PR DESCRIPTION
**Pull request by yuzefovich**
First commit adds support for RIGHT OUTER JOIN in vectorized merge join.

Second commits does some housekeeping.

Addresses: #37166.

### CODE REVIEW

**Comment by yuzefovich** [comment]
An interesting observation is that increasing the size of the generated `mergejoiner.eg.go` (roughly from 80k lines to 120k lines) gives a very minor performance hit (note that the benchmarks are for INNER JOIN, and the generated code for that should be exactly the same):
```
name                                       old time/op    new time/op    delta
MergeJoiner/rows=1024-24                     51.5µs ± 2%    51.6µs ± 3%    ~     (p=0.971 n=10+10)
MergeJoiner/rows=4096-24                      177µs ± 1%     179µs ± 2%  +1.39%  (p=0.003 n=10+10)
MergeJoiner/rows=16384-24                     661µs ± 1%     671µs ± 1%  +1.47%  (p=0.000 n=10+9)
MergeJoiner/rows=1048576-24                  41.4ms ± 1%    42.1ms ± 2%  +1.63%  (p=0.000 n=10+10)
MergeJoiner/oneSideRepeat-rows=1024-24       54.0µs ± 1%    54.1µs ± 1%    ~     (p=0.387 n=9+9)
MergeJoiner/oneSideRepeat-rows=4096-24        180µs ± 1%     181µs ± 1%    ~     (p=0.400 n=10+9)
MergeJoiner/oneSideRepeat-rows=16384-24       673µs ± 1%     673µs ± 1%    ~     (p=0.796 n=10+10)
MergeJoiner/oneSideRepeat-rows=1048576-24    41.7ms ± 1%    42.1ms ± 1%  +1.09%  (p=0.000 n=10+10)
MergeJoiner/bothSidesRepeat-rows=1024-24     56.0µs ± 2%    57.1µs ± 1%  +1.90%  (p=0.000 n=10+10)
MergeJoiner/bothSidesRepeat-rows=4096-24      200µs ± 2%     197µs ± 1%  -1.24%  (p=0.005 n=10+10)
MergeJoiner/bothSidesRepeat-rows=16384-24    1.06ms ± 0%    1.07ms ± 0%  +0.43%  (p=0.000 n=10+10)
MergeJoiner/bothSidesRepeat-rows=32768-24    3.11ms ± 0%    3.14ms ± 0%  +0.77%  (p=0.000 n=9+9)

name                                       old speed      new speed      delta
MergeJoiner/rows=1024-24                   1.27GB/s ± 2%  1.27GB/s ± 3%    ~     (p=0.971 n=10+10)
MergeJoiner/rows=4096-24                   1.48GB/s ± 1%  1.46GB/s ± 1%  -1.59%  (p=0.000 n=10+9)
MergeJoiner/rows=16384-24                  1.59GB/s ± 1%  1.56GB/s ± 1%  -1.45%  (p=0.000 n=10+9)
MergeJoiner/rows=1048576-24                1.62GB/s ± 1%  1.59GB/s ± 2%  -1.60%  (p=0.000 n=10+10)
MergeJoiner/oneSideRepeat-rows=1024-24     1.21GB/s ± 1%  1.21GB/s ± 1%    ~     (p=0.387 n=9+9)
MergeJoiner/oneSideRepeat-rows=4096-24     1.45GB/s ± 1%  1.45GB/s ± 1%    ~     (p=0.400 n=10+9)
MergeJoiner/oneSideRepeat-rows=16384-24    1.56GB/s ± 1%  1.56GB/s ± 1%    ~     (p=0.796 n=10+10)
MergeJoiner/oneSideRepeat-rows=1048576-24  1.61GB/s ± 1%  1.59GB/s ± 1%  -1.07%  (p=0.000 n=10+10)
MergeJoiner/bothSidesRepeat-rows=1024-24   1.17GB/s ± 2%  1.15GB/s ± 1%  -1.87%  (p=0.000 n=10+10)
MergeJoiner/bothSidesRepeat-rows=4096-24   1.31GB/s ± 2%  1.33GB/s ± 1%  +1.24%  (p=0.005 n=10+10)
MergeJoiner/bothSidesRepeat-rows=16384-24   987MB/s ± 0%   983MB/s ± 0%  -0.43%  (p=0.000 n=10+10)
MergeJoiner/bothSidesRepeat-rows=32768-24   674MB/s ± 0%   668MB/s ± 0%  -0.76%  (p=0.000 n=9+9)
```

**Comment by yuzefovich** [comment]
I've just added another commit to this PR that cleans up the code a bit (removes the TODOs, runs tests against the processor several time - locally takes 0.4s, can reduce it further if needed, renames a couple of methods). If you think it doesn't belong here, please let me know, and I'll move it into the follow-up PR to this one.

**Comment by yuzefovich** [comment]
Rebased it on top of master, so it is RFAL.

**Review by jordanlewis — COMMENTED** [review]
Do we want some benchmarks for the outer join cases? Also, did you verify that these random tests actually catch problems? It looks like we are checking the results of random join between 10 rows with values between 0 and 5 - does this have sufficient variety to catch issues? I would prefer more testing over less.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38610#-:-LjRaI2JEcY7_uoRq8me:bqhd208)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @solongordon, and @yuzefovich)

___
*[pkg/sql/distsqlrun/columnar_operators_test.go, line 129 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38610#-LjRbqsR1nFPBd761q6C:-LjRbqsR1nFPBd761q6D:b9oeqli) ([raw file](https://github.com/cockroachdb/cockroach/blob/d58bf32df5f46636ca7320489a4cee8cc81476c5/pkg/sql/distsqlrun/columnar_operators_test.go#L129)):*
> ```Go
> 	for nSeed := 1; nSeed < nSeeds; nSeed++ {
> 		seed := rand.Int()
> 		rng := rand.New(rand.NewSource(int64(seed)))
> ```

Is there any point to reseeding this? Can't we just run n times with the same initial seed?
___
*[pkg/sql/exec/mergejoiner_test.go, line 1046 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38610#-LjRZ_yl6yRzH6y9I2o1:-LjRZ_yl6yRzH6y9I2o2:bljek4) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa292303dc6b9d5c05a4eefda3991fd901987815/pkg/sql/exec/mergejoiner_test.go#L1046)):*
> ```Go
> 		},
> 		{
> 			description:     "single column DESC with nulls on the right RIGHT OUTER JOIN",
> ```

Nice job on all of these new tests.
___
*[pkg/sql/exec/mergejoiner_tmpl.go, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38610#-LjRZjrTC03fS_HEIz0P:-LjRZjrTC03fS_HEIz0Q:bgf3ut1) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa292303dc6b9d5c05a4eefda3991fd901987815/pkg/sql/exec/mergejoiner_tmpl.go#L289)):*
> ```Go
> // {{/*
> // This code snippet processes an unmatched group from the right.
> func _RIGHT_UNMATCHED_GROUP_SWITCH(joinType joinTypeInfo) { // */}}
> ```

this is a template argument, right? Please name it _JOIN_TYPE to at least try to document what's going on.
___
*[pkg/sql/exec/mergejoiner_tmpl.go, line 304 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38610#-LjR_Ine8gvscEieOyJ-:-LjR_Ine8gvscEieOyJ0:bgsfhze) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa292303dc6b9d5c05a4eefda3991fd901987815/pkg/sql/exec/mergejoiner_tmpl.go#L304)):*
> ```Go
> 	if rGroup.unmatched {
> 		if curRIdx+1 != curRLength {
> 			panic("unexpectedly length of the right unmatched group is not 1")
> ```

Perhaps you should include the actual values in this message so that if the bug gods frown upon us somebody will have a hope to be able to figure out what's going on.
___
*[pkg/sql/exec/mergejoiner_tmpl.go, line 414 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38610#-LjR_bJr8c7oHicV3Bwz:-LjR_bJr8c7oHicV3Bx-:buspjhy) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa292303dc6b9d5c05a4eefda3991fd901987815/pkg/sql/exec/mergejoiner_tmpl.go#L414)):*
> ```Go
> // to handle an unmatched tuple from the right.
> func _INCREMENT_RIGHT_SWITCH(
> 	joinType joinTypeInfo, sel selPermutation, overload mjOverload, rHasNulls bool,
> ```

These are all template args, right? please name with _CAPS.
___
*[pkg/sql/exec/mergejoiner_tmpl.go, line 429 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38610#-LjRaXru9QJl5tFB5qsx:-LjRaXrv7v8HrwbHwm2r:bh7cdgo) ([raw file](https://github.com/cockroachdb/cockroach/blob/d58bf32df5f46636ca7320489a4cee8cc81476c5/pkg/sql/exec/mergejoiner_tmpl.go#L429)):*
> ```Go
> 	o.groups.addRightOuterGroup(curLIdx, curRIdx-1)
> 	for curRIdx < curRLength {
> 		// {{ if _R_HAS_NULLS }}
> ```

Love this kind of change.
___
*[pkg/sql/exec/mergejoiner_tmpl.go, line 917 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38610#-LjRb1Qx9uUJg9AH93sF:-LjRb1Qx9uUJg9AH93sG:bucu7po) ([raw file](https://github.com/cockroachdb/cockroach/blob/d58bf32df5f46636ca7320489a4cee8cc81476c5/pkg/sql/exec/mergejoiner_tmpl.go#L917)):*
> ```Go
> // exhausted.
> func (o *mergeJoin_JOIN_TYPE_STRINGOp) exhaustLeftSource() {
> 	// {{ if $joinType.IsInner }}
> ```

Yay for templating.

**Review by yuzefovich — COMMENTED** [review]
I have been hesitant on adding benchmarks of other join types since even running only INNER join with `./scripts/bench` takes like 20-30 minutes. I guess we could run all of the join types once just to see what the performance numbers they give us, and we can use INNER join benchmark to check for improvement/regressions.

Yes, all of the bugs found via the randomized test with 100 rows was also found with 10 rows, and with increasing the number of runs, I think, we actually get a better coverage. I feel pretty good about test coverage here.

One thing that was missing is randomized tests with non-ordering columns (i.e. when we have inputs with 2 columns, but only 1 is ordered). George disabled such case because of the non-determinism. I've just run it for several minutes and observed no failures (which means that the processor and the operator returned the same results in the same order), so I enabled it. I think that, in theory, such test cases are not deterministic, but in reality the algorithms we have in the processor and the operator "maintain" the input order of rows, so I'd expect for them to always have the same output. If it does become flaky, we can disable it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38610#-:-LjSl9LV3u9vVds7l2iH:b-43zbyr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @solongordon, and @yuzefovich)

___
*[pkg/sql/distsqlrun/columnar_operators_test.go, line 129 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38610#-LjRbqsR1nFPBd761q6C:-LjSjIsZ9jQe2CjeUU1e:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d58bf32df5f46636ca7320489a4cee8cc81476c5/pkg/sql/distsqlrun/columnar_operators_test.go#L129)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Is there any point to reseeding this? Can't we just run n times with the same initial seed?
</blockquote></details>

Done.
___
*[pkg/sql/exec/mergejoiner_tmpl.go, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38610#-LjRZjrTC03fS_HEIz0P:-LjSjbOF9-VXcioD1gSz:b-u1oxi8) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa292303dc6b9d5c05a4eefda3991fd901987815/pkg/sql/exec/mergejoiner_tmpl.go#L289)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

this is a template argument, right? Please name it _JOIN_TYPE to at least try to document what's going on.
</blockquote></details>

Yes, this is a template argument, but the naming convention is consistent throughout this file. So we should rename all of the arguments to all templated "switches" or none of those. I don't have a preference here, so I'll do what you think is better (possibly in order to reduce merge conflicts we can leave the renaming until after all join types are merged).
___
*[pkg/sql/exec/mergejoiner_tmpl.go, line 304 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38610#-LjR_Ine8gvscEieOyJ-:-LjSkbB06qf02LplG6Gw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa292303dc6b9d5c05a4eefda3991fd901987815/pkg/sql/exec/mergejoiner_tmpl.go#L304)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Perhaps you should include the actual values in this message so that if the bug gods frown upon us somebody will have a hope to be able to figure out what's going on.
</blockquote></details>

Done.

**Review by jordanlewis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38610#-:-LjUIlzo33C73K3U-ao4:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @solongordon, and @yuzefovich)

___
*[pkg/sql/exec/mergejoiner_tmpl.go, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38610#-LjRZjrTC03fS_HEIz0P:-LjUIi-hDtNsM2ZSiOw4:ba5dd48) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa292303dc6b9d5c05a4eefda3991fd901987815/pkg/sql/exec/mergejoiner_tmpl.go#L289)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Yes, this is a template argument, but the naming convention is consistent throughout this file. So we should rename all of the arguments to all templated "switches" or none of those. I don't have a preference here, so I'll do what you think is better (possibly in order to reduce merge conflicts we can leave the renaming until after all join types are merged).
</blockquote></details>

Okay, we can do it all at once later.

**Comment by yuzefovich** [comment]
Thanks for the review!

bors r+

**Pull request merged**
