### PR TITLE
colexecagg: use heuristic to grow alloc size for hash aggregation

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexecagg: use heuristic to grow alloc size for hash aggregation**

This commit changes how we determine the size of allocations for the hash aggregation (used to batch-allocate things for multiple buckets or groups). Previously, we would always use a fixed allocation size of 128 which is quite suboptimal with small number of groups. This commit fixes that by growing the allocation size exponentially, starting at 1, and until it reaches 128. As a result, we should be significantly more efficient in cases when we have few groups and slightly less efficient when we have a lot of groups.

Note that the following commit will use the optimizer-driven estimate for the total number of groups when computing the initial allocation size.

Additionally, this commit makes it so that every time the same agg alloc object is shared between multiple functions we increase its alloc size accordingly. We were already doing that for ordered and window aggregation, but now it makes sense do so for the hash aggregation too. Exponentially growing alloc size is handled similarly.

**sql: use optimizer-driven estimate for allocation size**

This commit plumbs the estimated row count for the number of rows produced by the GroupBy from the optimizer all the way to the execution, and then it uses this estimate to come up with the initial allocation size in the hash aggregator in the vectorized engine (mentioned in the previous commit).

As expected, benchmarks (assuming the perfect optimizer estimation) show noticeable improvement in some cases, both in speed and size of allocations, slightly increasing the number of allocated objects in a few cases: https://gist.github.com/yuzefovich/1546c9d133c6ba52cdda6ecd9297ba7d.

Informs: #117546.
Epic: CRDB-35243

Release note: None

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm: Nice!

> Reviewed 5 of 5 files at r1, 2 of 2 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118556#-:-NpakVq_9MSAxI2EwXW3:b-8gk8uj)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Review by mgartner — COMMENTED** [review]
:lgtm: Very cool! Thanks for doing this!

It's interesting that the benchmark that had be biggest reduction in allocations did not get any speedup:

```
Aggregator/ANY\_NOT\_NULL/hash/int/numSameAggs=4/groupSize=1/numInputRows=1048576-24 494ms ± 5% 512ms ±13% ~ (p=0.123 n=10+10)


Aggregator/ANY\_NOT\_NULL/hash/int/numSameAggs=4/groupSize=1/numInputRows=1048576-24 47.4k ± 0% 31.8k ± 0% -32.77% (p=0.000 n=10+10)
```

> Reviewed 4 of 5 files at r1, 2 of 2 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118556#-:-Npf5F5p0TN3LkSQJwi5:bgm963u)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained

___
*[`pkg/sql/opt/exec/execbuilder/relational.go` line 1646 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118556#-Npf4uQs73Vui2J224dO:-Npf4uQs73Vui2J224dP:b-5dotmv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7d322b3bcb0c6db8684408cefbcc0e13746c5fa/pkg/sql/opt/exec/execbuilder/relational.go#L1646)):*
> ```Go
> 		var rowCount uint64
> 		if relProps := groupBy.Relational(); relProps.Statistics().Available {
> 			rowCount = uint64(relProps.Statistics().RowCount)
> ```

Do you think it's worth taking the ceiling here, instead of truncating? For example if the estimated row count is 9.9, might be better to bump it to 10 rather than 9. Maybe this won't matter in practice since the estimate can be pretty far off anyway?

**Review by yuzefovich — COMMENTED** [review]
For some reason, there was some non-determinism when I ran the benchmarks - like 1 out of 4 runs actually showed latency increases, and the largest speedups didn't always correspond to the largest allocation reductions. Not sure what's the reason for that. Generally, benchmarks did show an improvement when I expected it, so I didn't look further.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118556#-:-NpfcmOxCIr974oaHUSV:b6n4883)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained

___
*[`pkg/sql/opt/exec/execbuilder/relational.go` line 1646 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118556#-Npf4uQs73Vui2J224dO:-Npfd9Og2cydLTiH5hsO:b-akkkus) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7d322b3bcb0c6db8684408cefbcc0e13746c5fa/pkg/sql/opt/exec/execbuilder/relational.go#L1646)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Do you think it's worth taking the ceiling here, instead of truncating? For example if the estimated row count is 9.9, might be better to bump it to 10 rather than 9. Maybe this won't matter in practice since the estimate can be pretty far off anyway?
</blockquote></details>

It probably doesn't matter that much, but I'll make a change. I copied this from the scan params - will adjust those too.

**Pull request merged**
