### PR TITLE
opt: support window function partitions

### PR DESCRIPTION
**Pull request by justinj**
Release note: None

### CODE REVIEW

**Comment by justinj** [comment]
actually, ignore this for the moment, there's a bug I'd rather fix once yahor's other change goes in

**Comment by justinj** [comment]
Ok, ready for a look! First commit fixes up the way arguments are passed around, second one adds partitions. Decided it was easier to just make them one PR.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37074)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/sql/opt_exec_factory.go, line 820 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37074#-LdGQFy6CsSMgDxQk25_:-LdGQFy6CsSMgDxQk25a:bf74qsm) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a372156051bf26b34c4db291ca69d41721d4e9f/pkg/sql/opt_exec_factory.go#L820)):*
> ```Go
> 	}
> 
> 	argsIdxs := make([]uint32, len(wi.ArgIdxs))
> ```

I had a feeling that something wasn't right here with arguments when I was rebasing on top of your previous PR. Great that you've addressed it quickly.
___
*[pkg/sql/window.go, line 229 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37074#-LdGQxqAD57yPUyfhG-d:-LdGQxqAD57yPUyfhG-e:bqhzk3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a372156051bf26b34c4db291ca69d41721d4e9f/pkg/sql/window.go#L229)):*
> ```Go
> 			if funcExpr, ok := partition.(*tree.FuncExpr); ok {
> 				if funcExpr.IsWindowFunctionApplication() {
> 					return pgerror.Newf(pgerror.CodeWindowingError, "window function calls cannot be nested")
> ```

What is the reason for this change? Here is an example of psql output on the appropriate query:
`ERROR:  window functions are not allowed in window definitions`.
___
*[pkg/sql/opt/optbuilder/window.go, line 102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37074#-LdGSIZO-lIATW5rToFH:-LdGSIZO-lIATW5rToFI:b4q5ofh) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a372156051bf26b34c4db291ca69d41721d4e9f/pkg/sql/opt/optbuilder/window.go#L102)):*
> ```Go
> 
> 		for j, t := range w.partition {
> 			// TODO(justin): use findExistingCol once argument fix is in.
> ```

Did you mean the refactoring PR that has been merged? Or was there something else?

**Review by justinj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37074)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/sql/window.go, line 229 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37074#-LdGQxqAD57yPUyfhG-d:-LdJgFCk5sWjMSrF9Tp0:b-2upen4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a372156051bf26b34c4db291ca69d41721d4e9f/pkg/sql/window.go#L229)):*
There's a general framework that the optimizer uses for validating things like this, and it was easiest to just make this error message match the one from there to make the logic test pass. We could make that framework more sophisticated to match the error message here but I'm not sure matching postgres on these error messages is really that important.

Related, I noticed the other day that the HP check for this is insufficient:
```
> select row_number() over (partition by row_number() over ()+1);
E190425 13:29:59.310556 786 sql/conn_executor.go:707  [n1,client=127.0.0.1:57798,user=root] a SQL panic has occurred while executing "SELECT row_number() OVER (PARTITION BY row_number() OVER () + 1)": runtime error: invalid memory address or nil pointer dereference
E190425 13:29:59.310655 786 util/log/crash_reporting.go:204  [n1,client=127.0.0.1:57798,user=root] a panic has occurred!
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: panic while executing 1 statements: SELECT row_number() OVER (PARTITION BY row_number() OVER () + _); caused by runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4aca4a3]
```
I thought about opening an issue, but not sure it's worth it at this point for an obscure error case.
___
*[pkg/sql/opt/optbuilder/window.go, line 102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37074#-LdGSIZO-lIATW5rToFH:-LdJh5EK5UN8wEXGDdF4:b-fnxbko) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a372156051bf26b34c4db291ca69d41721d4e9f/pkg/sql/opt/optbuilder/window.go#L102)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Did you mean the refactoring PR that has been merged? Or was there something else?
</blockquote></details>

oops, yup, meant to change this.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37074#-:-LdKvhsODsD9x04ctPMQ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/sql/opt/ops/relational.opt, line 866 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37074#-LdKus8P7BvfCd5L3bvZ:-LdKus8P7BvfCd5L3bv_:b2kj96g) ([raw file](https://github.com/cockroachdb/cockroach/blob/1019132c0b130af42094fcab8717c1fc259c40f5/pkg/sql/opt/ops/relational.opt#L866)):*
> ```
>     # unchanged. Note the only columns pruned by a Window operator are the
>     # window function's arguments.
>     Passthrough ColSet
> ```

Can't it always pass through all input columns? Seems strange to give it the ability to project.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37074)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/sql/window.go, line 229 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37074#-LdGQxqAD57yPUyfhG-d:-LdKxjCC8PVG8iqvIWIx:b-q8lcxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a372156051bf26b34c4db291ca69d41721d4e9f/pkg/sql/window.go#L229)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

There's a general framework that the optimizer uses for validating things like this, and it was easiest to just make this error message match the one from there to make the logic test pass. We could make that framework more sophisticated to match the error message here but I'm not sure matching postgres on these error messages is really that important.

Related, I noticed the other day that the HP check for this is insufficient:
```
> select row_number() over (partition by row_number() over ()+1);
E190425 13:29:59.310556 786 sql/conn_executor.go:707  [n1,client=127.0.0.1:57798,user=root] a SQL panic has occurred while executing "SELECT row_number() OVER (PARTITION BY row_number() OVER () + 1)": runtime error: invalid memory address or nil pointer dereference
E190425 13:29:59.310655 786 util/log/crash_reporting.go:204  [n1,client=127.0.0.1:57798,user=root] a panic has occurred!
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: panic while executing 1 statements: SELECT row_number() OVER (PARTITION BY row_number() OVER () + _); caused by runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4aca4a3]
```
I thought about opening an issue, but not sure it's worth it at this point for an obscure error case.
</blockquote></details>

Nice find, thanks!
___
*[pkg/sql/opt/ops/relational.opt, line 866 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37074#-LdKus8P7BvfCd5L3bvZ:-LdKxuND4hvNw8qnul6J:br5so5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/1019132c0b130af42094fcab8717c1fc259c40f5/pkg/sql/opt/ops/relational.opt#L866)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Can't it always pass through all input columns? Seems strange to give it the ability to project.
</blockquote></details>

Yes, actually with the recent refactor, all input columns are now passed through.

**Review by justinj — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37074#-:-LdPjME39-EEPJx96Wmg:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj, @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/sql/opt/ops/relational.opt, line 866 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37074#-LdKus8P7BvfCd5L3bvZ:-LdPZBmNCp1TzyX3Qe2N:b-qq0g28) ([raw file](https://github.com/cockroachdb/cockroach/blob/1019132c0b130af42094fcab8717c1fc259c40f5/pkg/sql/opt/ops/relational.opt#L866)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Yes, actually with the recent refactor, all input columns are now passed through.
</blockquote></details>

I guess, it's kind of obnoxious though, since then we need to always put an extra project on top to get rid of the argument columns. What would really be ideal I guess would be if the windowNode could take expressions to render for the arguments itself so that we didn't have to deal with those at all (like how `Select` works, for example). It did simplify the code a bit so I made this change.

**Pull request merged**
