### PR TITLE
sql: Move sqlbase.ColumnType to types package (patch 1/)

### PR DESCRIPTION
**Pull request by knz**
Split from #36598 cc @andy-kimball 

Begin process of consolidating all type-related information into the types
package.

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
:lgtm:

> Reviewed 139 of 139 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36698#-:-Lc5_JcFAG06vv5nGRa4:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by knz** [comment]
(please don't merge this)

**Comment by andy-kimball** [comment]
@knz, I used your script to push a rebased version of this commit, as a test of the process. It seems to have worked well.

**Review by jordanlewis — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36698#-:-Lc9VGZU3nsBMxFe9zZi:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @knz)

**Review by knz — COMMENTED** [review]
> Reviewed 7 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36698)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @knz)

**Pull request merged**
