### PR TITLE
distsql: add memory accounting to mergeJoiner

### PR DESCRIPTION
**Pull request by yuzefovich**
Resolves: #26896.

Adds accounting of memory allocated during computation of
cartesion product of equal rows and adds the max allocated
memory to the visual query plan stats.

Release note: None

### CODE REVIEW

**Comment by asubiotto** [comment]
Thanks for the change!

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/distsqlrun/mergejoiner.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26914#-LFrBwAY2ny92jFSScno:-LFrBwAZEnQLv9mYUqZh:b-7eapyv) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cae56cfcd48e384f5c66f61999de8aba3281bdb/pkg/sql/distsqlrun/mergejoiner.go#L106)):*
> ```Go
> 		convertToColumnOrdering(spec.RightOrdering),
> 		spec.NullEquality,
> 		newMonitor(flowCtx.EvalCtx.Ctx(), flowCtx.EvalCtx.Mon, "stream-merger-mem"),
> ```

I would just call this `mergejoiner-mem` since we name monitors according to the processors in other places. Also, I think it would be better for the `mergeJoiner` to have explicit ownership of this monitor, so the monitor is created as well as closed in the `mergeJoiner` and the `streamMerger` doesn't need to worry about it. You can probably use the `memMonitor` field in `processorBase` to store it.

---

*[pkg/sql/distsqlrun/stream_group_accumulator.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26914#-LFrFAn8B3iQGfeAXD08:-LFrFAn8B3iQGfeAXD09:bib3md9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cae56cfcd48e384f5c66f61999de8aba3281bdb/pkg/sql/distsqlrun/stream_group_accumulator.go#L99)):*
> ```Go
> 		if len(s.curGroup) == 0 {
> 			if s.curGroup == nil {
> 				usage := sizeOfEncDatumRowStruct + sizeOfEncDatum*int64(len(row)*64)
> ```

I'm not sure this size calculation is correct. I think you need to account for the size of an `EncDatumRow` and an `EncDatum` (as you're doing), but you also have to account for the size of the members of the `EncDatum`. Take for example the `encoded` field. A `nil` encoded field's size is taken into account when getting the size of an `EncDatum`, but when it actually points to something, those bytes would be unaccounted for. Similar to the `Datum` field, if `!= nil`, it has a `Size` method that you can use. The `encoding` field is already taken into account by the `Sizeof` call so you don't have to worry about that.

It would be awesome if you could extract this logic into `sqlbase` to live alongside the `EncDatum` code (maybe give it a `Size` method like the `Datum` has) and use this here. There are a bunch of other places this logic could be useful, and it would make it nicer to unit-test. 

---

*[pkg/sql/distsqlrun/stream_merger.go, line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26914#-LFrEbjG-WcncNEJKbcO:-LFrEbjG-WcncNEJKbcP:biemjpo) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cae56cfcd48e384f5c66f61999de8aba3281bdb/pkg/sql/distsqlrun/stream_merger.go#L167)):*
> ```Go
> 
> func (sm *streamMerger) close(ctx context.Context) {
> 	sm.left.memAcc.Close(ctx)
> ```

Sort of related to the above comment on ownership: The stream merger shouldn't worry about creating/managing the memory accounts for the `streamGroupAccumulators`, I would pass in the monitor to `makeStreamGroupAccumulator` below and have them create/manage their account.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26914#-:-LFrHdsTEt3BSbuMgiIF:b-fpbdon)*

**Comment by yuzefovich** [comment]
Thanks for the comments!

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/distsqlrun/mergejoiner.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26914#-LFrBwAY2ny92jFSScno:-LFrTGgn1xC4qFEv6lZv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cae56cfcd48e384f5c66f61999de8aba3281bdb/pkg/sql/distsqlrun/mergejoiner.go#L106)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I would just call this `mergejoiner-mem` since we name monitors according to the processors in other places. Also, I think it would be better for the `mergeJoiner` to have explicit ownership of this monitor, so the monitor is created as well as closed in the `mergeJoiner` and the `streamMerger` doesn't need to worry about it. You can probably use the `memMonitor` field in `processorBase` to store it.
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/stream_group_accumulator.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26914#-LFrFAn8B3iQGfeAXD08:-LG1abxk12y9ipA8PlX8:b-fl29ut) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cae56cfcd48e384f5c66f61999de8aba3281bdb/pkg/sql/distsqlrun/stream_group_accumulator.go#L99)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I'm not sure this size calculation is correct. I think you need to account for the size of an `EncDatumRow` and an `EncDatum` (as you're doing), but you also have to account for the size of the members of the `EncDatum`. Take for example the `encoded` field. A `nil` encoded field's size is taken into account when getting the size of an `EncDatum`, but when it actually points to something, those bytes would be unaccounted for. Similar to the `Datum` field, if `!= nil`, it has a `Size` method that you can use. The `encoding` field is already taken into account by the `Sizeof` call so you don't have to worry about that.

It would be awesome if you could extract this logic into `sqlbase` to live alongside the `EncDatum` code (maybe give it a `Size` method like the `Datum` has) and use this here. There are a bunch of other places this logic could be useful, and it would make it nicer to unit-test. 
</blockquote></details>

Extracting `Size()` methods was a good idea.

Please double check my logic for memory accounting:
- we first allocate a slice of 64 `EncDatumRow` structs
- then, for the first 64 `append`s simply growing by `row.Size()` would double count the size of the struct itself, so we need to subtract it
- for all `append`s after first 64 we simply grow by `row.Size()`

---

*[pkg/sql/distsqlrun/stream_merger.go, line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26914#-LFrEbjG-WcncNEJKbcO:-LFrUxfn9Y_O6ffSZlLI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cae56cfcd48e384f5c66f61999de8aba3281bdb/pkg/sql/distsqlrun/stream_merger.go#L167)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Sort of related to the above comment on ownership: The stream merger shouldn't worry about creating/managing the memory accounts for the `streamGroupAccumulators`, I would pass in the monitor to `makeStreamGroupAccumulator` below and have them create/manage their account.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26914#-:-LG1bqZO73jyYuEeWtgd:b-a09w3v)*

**Comment by asubiotto** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/distsqlrun/stream_group_accumulator.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26914#-LFrFAn8B3iQGfeAXD08:-LGND1X68vF7ulPvVv5X:bs90dl3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cae56cfcd48e384f5c66f61999de8aba3281bdb/pkg/sql/distsqlrun/stream_group_accumulator.go#L99)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Extracting `Size()` methods was a good idea.

Please double check my logic for memory accounting:
- we first allocate a slice of 64 `EncDatumRow` structs
- then, for the first 64 `append`s simply growing by `row.Size()` would double count the size of the struct itself, so we need to subtract it
- for all `append`s after first 64 we simply grow by `row.Size()`
</blockquote></details>

The logic is correct but I think we should simplify the implementation. The issue is that `append` calls potentially double the size of `curGroup` and we would not be accounting for `len()/2` nil `EncDatumRow`s so we shouldn't strive to get **exactly** the amount of memory used. I would prefer if we defer accounting for the slice overhead when we actually add to `curGroup` to simplify things. Since `row.Size()` accounts for this, I think you can just `Grow` by that and get rid of `sizeOfEncDatumRowStruct`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26914)*

**Comment by yuzefovich** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/distsqlrun/stream_group_accumulator.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26914#-LFrFAn8B3iQGfeAXD08:-LGPyMZR4eYf79xPy-tU:bdcv6l8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cae56cfcd48e384f5c66f61999de8aba3281bdb/pkg/sql/distsqlrun/stream_group_accumulator.go#L99)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

The logic is correct but I think we should simplify the implementation. The issue is that `append` calls potentially double the size of `curGroup` and we would not be accounting for `len()/2` nil `EncDatumRow`s so we shouldn't strive to get **exactly** the amount of memory used. I would prefer if we defer accounting for the slice overhead when we actually add to `curGroup` to simplify things. Since `row.Size()` accounts for this, I think you can just `Grow` by that and get rid of `sizeOfEncDatumRowStruct`.
</blockquote></details>

Good point.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26914)*

**Comment by asubiotto** [comment]
:lgtm:

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26914#-:-LGQ9ySx5sCta2LNxxSO:bnfp4nl)*

**Comment by knz** [comment]
This is missing a release note: nodes could crash with OOM errors prior to this patch with specially crafted joins.

**Pull request merged**
