### PR TITLE
sql: don't rewind to BEGIN when retrying txn

### LINKED ISSUE #82392: sql: queries with ON CONFLICT DO UPDATE SET seem to interfere each other when run in parallel
**Describe the problem**

We spinned up 2 threads to run the same `INSERT INTO ... ON CONFLICT DO UPDATE SET ...` query in parallel. To do that we started a connection pool with `maximum pool size == 2 connections`. When running against the latest built from master we encountered the following error:

```
org.postgresql.util.PSQLException: ERROR: there is already a transaction in progress
...
```
This seems to be a regression caused by commit https://github.com/cockroachdb/cockroach/commit/9fdb39b49e. It passed with a built prior to this commit. 

**To Reproduce**

We used HikariCP 5.0.0 as the connection pool, and run the query with the following `insertSameValInParallel.java`.

``` java
package jane.demo.connect;

import com.zaxxer.hikari.HikariDataSource;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;


public class insertSameValInParallel {
    static HikariDataSource hds = new HikariDataSource();

    public static class incrementInsert implements Runnable {
        private final int threadId;
        public incrementInsert(int threadId) {
            this.threadId = threadId;
        }
        public void run() {
            int valToInsert = 0;
            while (true) {
                try {
                    insertVal(valToInsert);
                    valToInsert += 1;
                    System.out.printf("Done inserting %d with thread %d\n", valToInsert, this.threadId);
                } catch (Exception e) {
                    e.printStackTrace();
                    System.exit(1);
                }
            }
        }
    }

    public static void main(String[] args) throws Exception {
        hds.setDriverClassName(org.postgresql.Driver.class.getName());
        hds.setJdbcUrl("jdbc:postgresql://localhost:26257/defaultdb?sslmode=disable");
        hds.setUsername("root");
        // If set maximum pool size to 1, no error.
        hds.setMaximumPoolSize(2);
        hds.setAutoCommit(true);

        initTable();

        // Start 2 thread, each will try to insert incremental values to the same table.
        for (int threadId = 0; threadId < 2; threadId++) {
            Thread t = new Thread(new incrementInsert(threadId));
            t.start();
        }

        while (true) Thread.sleep(1000);
    }

    private static void initTable() throws SQLException {
        try (Connection conn = hds.getConnection()) {
            String dropTableSql = "DROP TABLE IF EXISTS public.t; ";
            String createTableSql = "CREATE TABLE public.t (x int, CONSTRAINT my_pkey PRIMARY KEY (x ASC));";
            PreparedStatement stmt = conn.prepareStatement(dropTableSql + createTableSql);
            stmt.executeUpdate();
        }
    }

    private static Object[] insertVal(int val) throws SQLException {
        try (Connection conn = hds.getConnection()) {
            try {
                conn.setAutoCommit(false);
                String sql = String.format(
                            "INSERT INTO t (x) VALUES (%d) " +
                            "ON CONFLICT (x) DO UPDATE SET x = 1000 + %d",
                        val,
                        val
                );
                PreparedStatement stmt = conn.prepareStatement(sql);
                stmt.executeUpdate();
            } finally {
                conn.setAutoCommit(true);
            }
        }
        return null;
    }
}

```

We spinned up a cockroach server with `./cockroach start-single-node --insecure --store=cockroach-data --advertise-addr=localhost`.  

We tested against the binary built at the 

a) current latest commit in master (https://github.com/cockroachdb/cockroach/commit/2181204e9c) 

b) https://github.com/cockroachdb/cockroach/commit/9fdb39b49e 

c) https://github.com/cockroachdb/cockroach/commit/e852be5ca4 (the newest commit prior to #9fdb39b49e)

a) and b) failed with the `org.postgresql.util.PSQLException: ERROR: there is already a transaction in progress` error and c) passed

Note that **any** of following changes in `insertSameValInParallel.java` will make it pass:
  -  Set the maximum pool size to 1. 
  -  Start only one thread.
  -  Comment out the `conn.setAutoCommit(false);` in `insertVal()`.
  -  Change the query to `ON CONFLICT DO NOTHING`.
  -  Add a sleep between thread starts. For example: (Note that the sleep time has to be longer than 100 milliseconds)
     ``` java
         for (int threadId = 0; threadId < 2; threadId++) {
            Thread t = new Thread(new incrementInsert(threadId));
            if (threadId == 1) {
                Thread.sleep(100);
            }
            t.start();
        }
     ```

**Expected behavior**
The queries should not fail.

**Additional data / screenshots**
The whole error message is
```
org.postgresql.util.PSQLException: ERROR: there is already a transaction in progress
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2674)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2364)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:354)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:484)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:404)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:162)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:130)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at jane.demo.connect.insertSameValInParallel.insertVal(myClass.java:72)
	at jane.demo.connect.insertSameValInParallel$incrementInsert.run(myClass.java:22)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Environment:**
 - Server OS: [MacOS]
 - Client app [JDBC]
 - Cockroach Server: single-node insecure node, initialized with `./cockroach start-single-node --insecure`

**Additional context**
This issue is originally from a support ticket. 

Jira issue: CRDB-16346

gz#12585

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/82392

Release note (bug fix): Fixed a bug where CockroachDB would
sometimes automatically retry the BEGIN statement of an explicit
transaction.

### CODE REVIEW

**Review by ZhouXing19 — APPROVED** [review]
Nice catch, thanks!

**Comment by rafiss** [comment]
cc @ZhouXing19 i added the test and changed the implementation a little. please take a look whenever you have time

**Review by ZhouXing19 — CHANGES_REQUESTED** [review]
I'm not familiar with TestingKnobs (and they look so cool!) so I'm a bit confused: did we simulate retrying a txn? It seems to me that there's only one conn in the test, and `SELECT 1; BEGIN; INSERT INTO foo VALUES(1); COMMIT;` only ran once, and it will always pass without retrying.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82622#-:-N44jpOZCOoTu7kznHRb:b8hw9eo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @ZhouXing19)

___
*[`pkg/sql/conn_executor_test.go` line 767 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82622#-N44kgi1BR8ogQ6x3tJl:-N44kgi1BR8ogQ6x3tJm:b-nqirzy) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ab7292d186a93754f34a630cbd4e4fccf37f66a/pkg/sql/conn_executor_test.go#L767)):*
> ```Go
> 			_, tableID, err := keys.SystemSQLCodec.DecodeTablePrefix(put.Key)
> 			if err != nil || tableID != fooTableId {
> 				err = nil
> ```

nit: we can just `return nil` here, I think
___
*[`pkg/sql/conn_executor_test.go` line 772 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82622#-N44km_V3Ov983OY3pGs:-N44km_V3Ov983OY3pGt:b-816md9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ab7292d186a93754f34a630cbd4e4fccf37f66a/pkg/sql/conn_executor_test.go#L772)):*
> ```Go
> 			if atomic.AddInt64(&failed, 1) <= numToFail {
> 				return roachpb.NewErrorWithTxn(
> 					roachpb.NewTransactionRetryError(roachpb.RETRY_REASON_UNKNOWN, "boom"), ba.Txn,
> ```

Maybe a more informative error message?

**Comment by ZhouXing19** [comment]
*[`pkg/sql/conn_executor_test.go` line 758 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82622#-N44lHUW-dbbvtE94uTe:-N44lHUW-dbbvtE94uTf:bykfj57) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ab7292d186a93754f34a630cbd4e4fccf37f66a/pkg/sql/conn_executor_test.go#L758)):*
> ```Go
> 	testDB.QueryRow(t, "SELECT 'foo'::regclass::oid").Scan(&fooTableId)
> 
> 	// Inject an error that will happen during execution.
> ```

I'm not sure if I understand the logic here: is it counting queries that are doing "conditional put", i.e. set the same value to a key in fooTable?. And when the count > 2, it raise an error?

**Review by rafiss — COMMENTED** [review]
> I'm not familiar with TestingKnobs (and they look so cool!) so I'm a bit confused: did we simulate retrying a txn? It seems to me that there's only one conn in the test, and SELECT 1; BEGIN; INSERT INTO foo VALUES(1); COMMIT; only ran once, and it will always pass without retrying.

good questions!

the way testing knobs work is that it lets you "inject" custom functionality into different parts of the system. you can view the usages of the knob to see where the behavior gets injected.

in this case, the behavior i'm injecting is to add a retryable error, which will cause the conn executor to retry the transaction. look for the `canAutoRetry` and `eventRetriableErr` usages in the conn executor.

but to make sure it retried, i should add one more assertion that the retry count was actually incremented.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82622#-:-N44vATjAT8wZYEcMUti:b560w61)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ZhouXing19)

___
*[`pkg/sql/conn_executor_test.go` line 758 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82622#-N44lHUW-dbbvtE94uTe:-N44wMIT9448LNBMwy_P:bn52c9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ab7292d186a93754f34a630cbd4e4fccf37f66a/pkg/sql/conn_executor_test.go#L758)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

I'm not sure if I understand the logic here: is it counting queries that are doing "conditional put", i.e. set the same value to a key in fooTable?. And when the count > 2, it raise an error?
</blockquote></details>

"conditional put" is the name of the KV request used to implement INSERT statements.

this actually will raise the error when the count is *less than* two
___
*[`pkg/sql/conn_executor_test.go` line 767 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82622#-N44kgi1BR8ogQ6x3tJl:-N44wYEFEPf0HJvZyKWX:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ab7292d186a93754f34a630cbd4e4fccf37f66a/pkg/sql/conn_executor_test.go#L767)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

nit: we can just `return nil` here, I think
</blockquote></details>

fixed
___
*[`pkg/sql/conn_executor_test.go` line 772 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82622#-N44km_V3Ov983OY3pGs:-N44xM0eDdBpUkGQR1zM:b4108sj) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ab7292d186a93754f34a630cbd4e4fccf37f66a/pkg/sql/conn_executor_test.go#L772)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Maybe a more informative error message?
</blockquote></details>

nobody actually will see this error message, but i will make it more readable for people looking at the code

**Review by ZhouXing19 — COMMENTED** [review]
I see, thanks for the explanation!
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82622#-:-N47rsbbEO8wvA1eYsBL:boq2rb2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ZhouXing19)

**Review by ZhouXing19 — APPROVED** [review]

**Pull request merged**
