### PR TITLE
sql,distsql: TestDistSQL on 3 node cluster

### PR DESCRIPTION
**Pull request by RaduBerinde**
Enabling logic test on 3 node cluster with distsql, with various test fixes and workarounds.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13706)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
CC @mjibson for the temporary workarounds for aggregation tests

**Comment by knz** [comment]
So I am both very grateful for you fixing the tests (arguably, they were just plainly wrong previously) and very respectful for all the time you spent into it!

:lgtm: - with request to xref in the open issue

I would suggest also to create a docs issues at the same time, to emphasize in our docs a bit more that SQL does not guarantee result ordering, and that in particular with distsql users *must* expect non-deterministic result ordering unless they use ORDER BY, as per the SQL spec. I do not believe we are explaining this anywhere and I am 98% confident we'll have a lot of questions about this if we don't document it upfront.

---

Reviewed 1 of 1 files at r1, 41 of 41 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/testdata/aggregate, line 760 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13706#-KdajwfNRoH2q1gNy999:-KdajwfOCSqBD9E4-vJx:b-to175l) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fc3ae04961c33aaf1f569e9dfc8f9b0302b43c9/pkg/sql/testdata/aggregate#L760)):*
> ```
> 2                 limit        1
> 
> # Temporarily disabled due to #13689.
> ```

Please add a reference to this test in the issue description of #13689 too.

---

*[pkg/sql/testdata/alter_table, line 477 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/13706#-Kdak5bEXSWxOGO18X3f:-Kdak5bEXSWxOGO18X3g:b-lqqgp6) ([raw file](https://github.com/cockroachdb/cockroach/blob/62811a92829ce17cd4cd0de2f846f9dbfa1f345b/pkg/sql/testdata/alter_table#L477)):*
> ```
> 5 NULL
> 
> # Temporarily disabled due to #13646.
> ```

ditto xref

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13706#-:-KdaiDNwZs7xW8UZhQkS:bxgxhf0)*

**Comment by RaduBerinde** [comment]
TFTR! Done, and filed doc issue #13710.

**Comment by RaduBerinde** [comment]
Ah, oops, I wanted to merge the other PR. @andreimatei would still appreciate your review, I can address any comments in a subsequent PR.

**Pull request merged**
