### PR TITLE
builtins: automatically add builtins for each type cast

### LINKED ISSUE #97067: sql: support postgresql date() function to convert timestamp to date
The DATE() function in PostgreSQL allows you to extract a date value from a timestamp. 

This syntax looks like the following:
```
SELECT DATE(timestamp_column) FROM table_name;
date
----------
2023-02-13
```

Alternative solutions would be to just cast to a date, but this requires a code change for existing applications. 
```
SELECT timestamp_column::DATE FROM table_name;
```

Another solution could be a UDF, but this is scoped by the schema/namespace. 

I think the ideal solution would be to have this function native in Cockroach since it is native to PostgreSQL. One interesting thing I'll point out is that I could not find any documentation of this function in the Postgres docs. 

Jira issue: CRDB-24488

### PR DESCRIPTION
**Pull request by otan**
In PG, casts from one type to another can also be use the function syntax, e.g. `date(now())` = `now()::date`. This is done at type resolution time.

Unfortunately we do not support that in type resolution, and from experience long ago it was tricky to do so (happy to be proven wrong).

This change instead defines a builtin for each castable type, which emulates the same behavior. We already kind of do this for `oid` and `inet`, so this isn't much worse right?

Release note (sql change): Each type cast is now expressable as a function, e.g. `now()::date` can be expressed as `date(now())`.

Resolves #97067

### CODE REVIEW

**Comment by rafiss** [comment]
this is cool! did you also see https://github.com/cockroachdb/cockroach/pull/94859

there's one note about PG though -- if i recall correctly, in postgres each cast _is implemented by_ calling the respective builtin function. this PR is going the other way though: each builtin function that is being added here is implemented by calling into the cast code. i'm not sure how much this distinction matters. one thing that could be related is in the pg_cast table, we should start filling out the `castfunc` column

**Comment by otan** [comment]
> there's one note about PG though -- if i recall correctly, in postgres each cast is implemented by calling the respective builtin function. 

that's true; ideally we make this work in type resolution like [pg does](https://www.postgresql.org/docs/current/typeconv-func.html):

> If no exact match is found, see if the function call appears to be a special type conversion request. This happens if the function call has just one argument and the function name is the same as the (internal) name of some data type. Furthermore, the function argument must be either an unknown-type literal, or a type that is binary-coercible to the named data type, or a type that could be converted to the named data type by applying that type's I/O functions (that is, the conversion is either to or from one of the standard string types). When these conditions are met, the function call is treated as a form of CAST specification. [[11]](https://www.postgresql.org/docs/current/typeconv-func.html#ftn.id-1.5.9.8.4.4.1.2)

i don't really see a way around this unfortunately.

----

this is also annoying as this PR will probably tie us in deeper to the `int8`/`float8` by default instead of `int4/float4`. basically to make this work:
```
query error OID out of range: -2147483649
SELECT oid(-2147483649)
```

**Comment by mgartner** [comment]
> i don't recall it being easy to put this into type resolution (pls prove me wrong :D).

If you define the builtins, I wonder if the function resolution we have will work well enough. It's unlikely to work 100% consistently with Postgres until we rewrite our function/type resolution (see #75101 and #https://github.com/cockroachdb/cockroach/issues/88374#issuecomment-1363233118).

**Comment by otan** [comment]
> If you define the builtins, I wonder if the function resolution we have will work well enough. 

based on my manual tests + my random test for casts it works good enough for now.

> It's unlikely to work 100% consistently with Postgres until we rewrite our function/type resolution 

we'll get there one day. [can't say i didn't try](https://github.com/otan-cockroach/cockroach/blob/34d1d1fdd7c0bbd04d2780abd7f32da90e1eef15/pkg/sql/sem/tree/overload_pg.go) :P

**Review by cucaroach — COMMENTED** [review]
Seems fine to me but this is a a little outside my purview, would like to defer to Rafi or Marcus.

> Reviewed 8 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97093#-:-NOKiekECHzx4_W2qcFF:bp8y6ph)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[`pkg/internal/sqlsmith/schema.go` line 500 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97093#-NOKh8Yb9leAO0mttssh:-NOKh8Yb9leAO0mttssi:b-64pr12) ([raw file](https://github.com/cockroachdb/cockroach/blob/c76485669bd8c5eebcc27402157367f78f0bc2bb/pkg/internal/sqlsmith/schema.go#L500)):*
> ```Go
> 
> 		if n := tree.Name(def.Name); n.String() != def.Name {
> 			// sqlsmith doesn't seem to know how to quote these.
> ```

Whats going on here?

**Review by mgartner — DISMISSED** [review]
> Reviewed 4 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97093)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @otan)

___
*[`pkg/sql/sem/builtins/pg_builtins.go` line 200 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97093#-NOKocP39Ek3qdR6OfKw:-NOKocP498rGTE5AVT7E:b84e2ew) ([raw file](https://github.com/cockroachdb/cockroach/blob/c76485669bd8c5eebcc27402157367f78f0bc2bb/pkg/sql/sem/builtins/pg_builtins.go#L200)):*
> ```Go
> 	}
> 	for toOID, def := range castBuiltins {
> 		n := strings.ToLower(types.OidToType[toOID].SQLString())
> ```

I don't think `SQLString` works here - Postgres's naming of these functions doesn't make the SQLString naming of a type. For example, `varchar`, `bit`, `decimal`, and `char` don't seem to be functions in Postgres. It looks like they might exist, but with different names. For example `bpchar` seems to work for the `char` type:

```
marcus=# select pg_typeof('foo'::CHAR), pg_typeof(bpchar('foo'));
 pg_typeof | pg_typeof
-----------+-----------
 character | character
(1 row)
```
___
*[`pkg/sql/sem/builtins/cast_test.go` line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97093#-NOKpoBo0bCDN7JQG8fe:-NOKpoBo0bCDN7JQG8ff:bjz8n9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/c76485669bd8c5eebcc27402157367f78f0bc2bb/pkg/sql/sem/builtins/cast_test.go#L68)):*
> ```Go
> 	switch typ.Oid() {
> 	case oid.T_char:
> 		return "char"
> ```

`oid.T_char` represents the [`"char"`](https://www.postgresql.org/docs/current/datatype-character.html#DATATYPE-CHARACTER-SPECIAL-TABLE) type, not to be confused with the `CHAR` type:

```
marcus=# SELECT pg_typeof('foo'::CHAR), pg_typeof('foo'::"char"), pg_typeof("char"('foo'));
 pg_typeof | pg_typeof | pg_typeof
-----------+-----------+-----------
 character | "char"    | "char"
(1 row)
```

So you'll want to keep the double quotes in the query, e.g., `SELECT "char"(...)` instead of `SELECT char(...)`. I think `typ.SQLString` already includes the double quotes for this type.

**Comment by otan** [comment]
*[`pkg/sql/sem/builtins/pg_builtins.go` line 200 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97093#-NOKocP39Ek3qdR6OfKw:-NOLYilIBQQi_7g09Wkb:b67tdp8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c76485669bd8c5eebcc27402157367f78f0bc2bb/pkg/sql/sem/builtins/pg_builtins.go#L200)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I don't think `SQLString` works here - Postgres's naming of these functions doesn't make the SQLString naming of a type. For example, `varchar`, `bit`, `decimal`, and `char` don't seem to be functions in Postgres. It looks like they might exist, but with different names. For example `bpchar` seems to work for the `char` type:

```
marcus=# select pg_typeof('foo'::CHAR), pg_typeof(bpchar('foo'));
 pg_typeof | pg_typeof
-----------+-----------
 character | character
(1 row)
```
</blockquote></details>

i think this is still right, you just need to quote the name.

```
otan=# select "varbit"('0100');
 varbit
--------
 0100
(1 row)
```

```
otan=# select "numeric"(1234::int);
 numeric
---------
    1234
(1 row)
```

```
otan=# select "char"(96::int);
 char
------
 `
(1 row)
```

**Comment by otan** [comment]
*[`pkg/sql/sem/builtins/cast_test.go` line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97093#-NOKpoBo0bCDN7JQG8fe:-NOLZB7xECriLK--BWXe:b-65nto5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c76485669bd8c5eebcc27402157367f78f0bc2bb/pkg/sql/sem/builtins/cast_test.go#L68)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

`oid.T_char` represents the [`"char"`](https://www.postgresql.org/docs/current/datatype-character.html#DATATYPE-CHARACTER-SPECIAL-TABLE) type, not to be confused with the `CHAR` type:

```
marcus=# SELECT pg_typeof('foo'::CHAR), pg_typeof('foo'::"char"), pg_typeof("char"('foo'));
 pg_typeof | pg_typeof | pg_typeof
-----------+-----------+-----------
 character | "char"    | "char"
(1 row)
```

So you'll want to keep the double quotes in the query, e.g., `SELECT "char"(...)` instead of `SELECT char(...)`. I think `typ.SQLString` already includes the double quotes for this type.
</blockquote></details>

no this is right, `tree.Name("char").String()` makes it a `"char"`.

**Comment by otan** [comment]
*[`pkg/sql/sem/builtins/cast_test.go` line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97093#-NOKpoBo0bCDN7JQG8fe:-NOLe7Xk5v7whdirLCpg:bahn5g9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c76485669bd8c5eebcc27402157367f78f0bc2bb/pkg/sql/sem/builtins/cast_test.go#L68)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

no this is right, `tree.Name("char").String()` makes it a `"char"`.
</blockquote></details>

ah nah good catch, had to rearrange a few things around.

**Comment by otan** [comment]
*[`pkg/sql/sem/builtins/cast_test.go` line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97093#-NOKpoBo0bCDN7JQG8fe:-NOLeg3P7aMSQnLXYiZZ:b-vb7abw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c76485669bd8c5eebcc27402157367f78f0bc2bb/pkg/sql/sem/builtins/cast_test.go#L68)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

ah nah good catch, had to rearrange a few things around.
</blockquote></details>

(sorry i mean, this is still the same, but bpchar / numeric was a surprise)

**Review by rafiss — CHANGES_REQUESTED** [review]
nit: can you fill in the `castfunc` column of pg_cast?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97093#-:-NOLm-294gJuAr2_sU-A:brn3f2a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @otan)

___
*[`docs/generated/sql/functions.md` line 361 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97093#-NOLlrw_5VRFsvA6XPXO:-NOLlrw_5VRFsvA6XPXP:b9pm2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdb77ecdf2052a6d4b410949dc2381cb02db861f/docs/generated/sql/functions.md#L361)):*
> ```Markdown
> </table>
> 
> ### Cast functions
> ```

i'd actually be in favor of marking all these as hidden. what do you think?

**Review by otan — COMMENTED** [review]
hmm, `castfunc` would be "wrong" though compared to PG. is that ok?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97093#-:-NOLpT5P0gCh_kt6ItYp:bq8qypp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @rafiss)

___
*[`docs/generated/sql/functions.md` line 361 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97093#-NOLlrw_5VRFsvA6XPXO:-NOLpSM09ptwglhAhMua:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdb77ecdf2052a6d4b410949dc2381cb02db861f/docs/generated/sql/functions.md#L361)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i'd actually be in favor of marking all these as hidden. what do you think?
</blockquote></details>

Done.

**Comment by rafiss** [comment]
wrong in which way? you mean it would have different function OIDs? i think that's fine -- the OID would still refer to the correct function in pg_proc.

**Comment by otan** [comment]
hmm not so good for something like `castfunc::regproc` - i think i prefer NULL for now until we rehaul our type overload system to make this point the correct way (i.e. casts call funcs, not funcs being derived from casts)

**Comment by rafiss** [comment]
i still don't follow. what's wrong with `castfunc::regproc`? i think if you shared the error or incorrect result i would understand better

**Comment by otan** [comment]
ah, nvm, i see what you're getting at.

**Comment by otan** [comment]
hmm it's a little tricky because we defined casts on all oids, but the functions derived is based on the family.

**Review by rafiss — APPROVED** [review]
thanks for adding this!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97093#-:-NPQee_d83HnDwTT2tKX:b-n71p2r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @otan)

___
*[`pkg/sql/sem/builtins/fixed_oids.go` line 2048 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/97093#-NPQeVYiAwA9w0ddjHoZ:-NPQeVYiAwA9w0ddjHo_:b-l2o77x) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a265ba4f4b7e9a2772569136d63efd77cb1f2dd/pkg/sql/sem/builtins/fixed_oids.go#L2048)):*
> ```Go
> 	2070: `crdb_internal.num_inverted_index_entries(val: tsvector, version: int) -> int`,
> 	2072: `crdb_internal.upsert_dropped_relation_gc_ttl(desc_id: int, gc_ttl: interval) -> bool`,
> 	2073: `box2d(geometry: geometry) -> box2d`,
> ```

just wanna confirm - so if someone adds a new type later on, they'll get an `init` error telling them they need to add an entry into this fixed OID map?

**Review by otan — COMMENTED** [review]
bors r=rafiss

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97093#-:-NPQhUZd3csx2lNzutNF:bx70i2y)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @rafiss)

___
*[`pkg/sql/sem/builtins/fixed_oids.go` line 2048 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/97093#-NPQeVYiAwA9w0ddjHoZ:-NPQhRxjES2rKuSPelqK:bb7s9xe) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a265ba4f4b7e9a2772569136d63efd77cb1f2dd/pkg/sql/sem/builtins/fixed_oids.go#L2048)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

just wanna confirm - so if someone adds a new type later on, they'll get an `init` error telling them they need to add an entry into this fixed OID map?
</blockquote></details>

yep!

**Comment by otan** [comment]
bors r=rafiss

**Pull request merged**
