### PR TITLE
sql: fix planNode deallocation in TestDistSQLRunningInAbortedTxn

### PR DESCRIPTION
**Pull request by knz**
Needed for #33561.

The planNode needs to be re-generated when the txn is retried.

Release note: None

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
LGTM

**Review by andreimatei — COMMENTED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34009#-:-LWHB-qn-O_xvwyLcPcA:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by knz** [comment]
TFYRs! Will appreciate your review of #33561 as well so I can fold this PR into that one without conflict.

**Pull request merged**
