### PR TITLE
roachprod: fix roachprod gc docker build

### PR DESCRIPTION
**Pull request by rail**
Previously, the roachprod garbage collector docker image build process
was using the `go get` approach to build roachprod.

Currently, this method doesn't work, because it doesn't use any pinning,
so the build ends up with all kind of deprecation warnings and failures.

* Use multi-stage docker build in order to separate build and runtime.
  It also reduces the image size from 1.9G to 700M.
* Build roachprod using the checked out commit SHA.
* Use the Bazel build image we use in CI to build roachprod.
* Use Bazel to build roachprod.
* Added `cloudbuild.yaml` to publish the docker image to GCR and use a
  beefier instance type.
* Modify the entrypoint script to set the default region, required by
  the AWS Go SDK library.
* Add `push.sh` to script deployment.

Release note: None

### CODE REVIEW

**Review by jlinder — APPROVED** [review]
One suggestion. :lgtm: either way.

> Reviewed 1 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71609#-:-MmTOyPb8IzvB5GwlxxQ:bckip0b)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rail and @rickystewart)

___
*[pkg/cmd/roachprod/docker/push.sh, line 10 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71609#-MmTOWCHC5KApU3Gqa1n:-MmTOWCHC5KApU3Gqa1o:b92yxa3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba1b8f136331ca480ee80f1b1a356c59ed81574d/pkg/cmd/roachprod/docker/push.sh#L10)):*
> ```Shell
> SHA=$(git rev-parse --short HEAD)
> gcloud --project cockroach-dev-inf builds submit \
>   --substitutions=_BAZEL_IMAGE=$BAZEL_IMAGE,_SHA=$SHA,_OWNER=cockroachdb,_REPO=cockroach \
> ```

Maybe accept OWNER and REPO as env args to this script so the script doesn't need to be changed for testing?

**Review by rail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71609)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jlinder and @rickystewart)

___
*[pkg/cmd/roachprod/docker/push.sh, line 10 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71609#-MmTOWCHC5KApU3Gqa1n:-MmTZIvO0MMpTdyKCteM:bfbq995) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba1b8f136331ca480ee80f1b1a356c59ed81574d/pkg/cmd/roachprod/docker/push.sh#L10)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

Maybe accept OWNER and REPO as env args to this script so the script doesn't need to be changed for testing?
</blockquote></details>

Good point, done!

**Comment by rail** [comment]
bors r=jlinder

**Comment by rail** [comment]
bors r=jlinder

**Pull request merged**
