### PR TITLE
roachtest: more logging in unoptimized_query_oracle and costfuzz

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit makes it so that we log all statements that are executed as
part of the `unoptimized_query_oracle` run. Previously, we would only
log the statements on the failure, but that seems insufficient to be
able to reproduce some of the failures. Additionally, this commit makes
it so that we catch any panics only from `smither.Generate` to avoid
silenced problems in the test itself.

The same changes are also applied to `costfuzz`.

Informs: #84270.

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85018#-:-N7qfEcT6g7s-pcdpTWw:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2)

**Comment by yuzefovich** [comment]
It seems less important to log the successful statements in `costfuzz` since the "state" doesn't spill across iterations, so maybe let's make the change only to the `unoptimized_query_oracle`? @michae2 thoughts?

**Review by michae2 — APPROVED** [review]
Oh, what state is spilling across iterations? That might be a bug? But regardless this is good, thank you for doing it! :lgtm:

I think the same logging in `costfuzz` would also be a good idea, because even if there is no session state spilling across iterations, there can still be timeouts or OOMs or panics which are hard to debug without a log.

Sorry I didn't add this logging to `costfuzz` in the first place!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85018#-:-N7qk4ZY7ZnlwKkBgO6g:badkphg)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @yuzefovich)

**Review by yuzefovich — COMMENTED** [review]
> Oh, what state is spilling across iterations? That might be a bug?

It's hard to say, maybe. I only have some observations [here](https://github.com/cockroachdb/cockroach/issues/84270#issuecomment-1194442145).

Added the logging to `costfuzz` too.

TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85018#-:-N7qr8h33j6oqh0xx7_u:b-4ogxuu)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @rytaft)

**Comment by yuzefovich** [comment]
I'm not sure what's up with this, but the commit has been merged.

**Pull request closed without merging**
