### PR TITLE
cdc: show all changefeed jobs in `SHOW CHANGEFEED JOBS`

### LINKED ISSUE #97883: cdc: SHOW CHANGEFEED JOBS only shows jobs from the last 12h
I got this [escalation](https://github.com/cockroachlabs/support/issues/2128) where a customer did not notice failed changefeed jobs because they did not show up in the `SHOW CHANGEFEED JOBS` output. The reason is that `SHOW CHANGEFEED JOBS` only shows running jobs and jobs from the last 12h. 

We should make this show all changefeed jobs. If the customer does not care about ALL the jobs they can still filter on the output columns (ex. filter out cancelled jobs or jobs which finished/started some interval of time in the past).

Jira issue: CRDB-24944

Epic CRDB-11783

### PR DESCRIPTION
**Pull request by jayshrivastava**
### cdc: show all changefeed jobs in SHOW CHANGEFEED JOBS

Release note (general change): Previously, the output of `SHOW CHANGEFEED JOBS` was limited to show unfinished jobs and finished jobs from the last 14 days. This change makes the command show all changefeed jobs, regardless of if they finished and when they finished. Note that jobs still obey the cluster setting `jobs.retention_time`. Completed jobs older than that time are deleted.

Fixes: https://github.com/cockroachdb/cockroach/issues/97883

### jobs: add virtual index for job_type in crdb_internal.jobs

This change adds a virtual index on the `job_type` column
of `crdb_internal.jobs`. This change should make queries
on that table which filter on job type (such as `SHOW
CHANGEFEED JOBS`) more efficient.

Release note: None

Epic: None

### CODE REVIEW

**Comment by jayshrivastava** [comment]
There doesn't seem to be a reason for why we limit it to 12h. There is a mention of it in the original PR https://github.com/cockroachdb/cockroach/pull/64956#pullrequestreview-667940334. Perhaps this limit was added due to instability in the jobs system / virtual tables. There's no discussion on Slack which I could find either.

**Review by HonoreDB — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98175)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

**Comment by jayshrivastava** [comment]
The virtual index causes a lot of tests to fail in many different ways, including but not limited to mixed version tests. I'm going to hold off on merging for now.

**Comment by jayshrivastava** [comment]
bors r=HonoreDB

**Pull request merged**
