### PR TITLE
Add and use Store-level PollFrozen endpoint

### PR DESCRIPTION
**Pull request by tbg**
After having dispatched Freeze requests to all Ranges in the cluster, the
ClusterFreeze endpoint now polls all (active) Stores in the cluster (as known
to the store pool) for a duration, requiring them to confirm that all of their
Replicas have been frozen.

There is room for improvement: A Store may house "dead" Replicas (which have
been removed from the Range they believe they are still part of), which would
consequently never freeze. A side effect which prioritizes such Replicas in
the GC queue should be able to remedy that, but this is not included in this
change.

With this change in, we can consider stop-the-world upgrades as our chosen
migration strategy of choice for the time being.

I'm planning to refactor the `server/admin.go` code a little bit to be able to test
the wait logic in isolation, but this should be good for a first review.
There's also the option of instead querying each **Node** instead of each Store
(saving RPCs), but addressing Stores felt more natural.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6598)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 5 of 5 files at r1, 4 of 4 files at r2, 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[kv/send_test.go, line 66 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQJLfffUtDlO_gM9LY:-KHQJLfffUtDlO_gM9LZ:1481758586) ([raw file](https://github.com/cockroachdb/cockroach/blob/831ebe1b6f6c4ac299175ddc50d1ba5443d68741/kv/send_test.go#L66)):*
> ```Go
> 	return &roachpb.BatchResponse{}, nil
> }
> func (n Node) PollFrozen(_ context.Context, _ *roachpb.PollFrozenRequest) (*roachpb.PollFrozenResponse, error) {
> ```

if you make this RPC belong to a new service, you can avoid this stub implementation

---

*[roachpb/api.proto, line 792 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQJUU6v7YR2VtX-d7E:-KHQJUU6v7YR2VtX-d7F:-961220464) ([raw file](https://github.com/cockroachdb/cockroach/blob/831ebe1b6f6c4ac299175ddc50d1ba5443d68741/roachpb/api.proto#L792)):*
> ```protobuf
> // StoreRequestHeader locates a Store on a Node.
> message StoreRequestHeader {
>   // TODO(tschottdorf): NodeID isn't really used for anything as this RPC
> ```

why'd you add it, if it's not used?

---

*[server/admin.go, line 801 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQKSAu202f0Pmza9Ct:-KHQKSAu202f0Pmza9Cu:1264792895) ([raw file](https://github.com/cockroachdb/cockroach/blob/831ebe1b6f6c4ac299175ddc50d1ba5443d68741/server/admin.go#L801)):*
> ```Go
> }
> 
> func (s *adminServer) waitForStoreFrozen() error {
> ```

can you sprinkle some comments?

---

*[server/admin.go, line 941 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQKEKxTuHQKcG08X2h:-KHQKEKxTuHQKcG08X2i:-897317592) ([raw file](https://github.com/cockroachdb/cockroach/blob/831ebe1b6f6c4ac299175ddc50d1ba5443d68741/server/admin.go#L941)):*
> ```Go
> 	var err error
> 	if req.Freeze {
> 		err = s.waitForStoreFrozen()
> ```

this change seems unrelated. is it?

---

*[server/node.go, line 806 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQJwiKoWoUihv8iybN:-KHQJwiKoWoUihv8iybO:-887955943) ([raw file](https://github.com/cockroachdb/cockroach/blob/831ebe1b6f6c4ac299175ddc50d1ba5443d68741/server/node.go#L806)):*
> ```Go
> 	ctx context.Context, args *roachpb.PollFrozenRequest,
> ) (*roachpb.PollFrozenResponse, error) {
> 	resp := &roachpb.PollFrozenResponse{Frozen: true}
> ```

is there any reason to initialize Frozen?

---

*[server/node.go, line 813 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQK5K4qG7sqfCYr0D2:-KHQK5K4qG7sqfCYr0D3:-1955664220) ([raw file](https://github.com/cockroachdb/cockroach/blob/831ebe1b6f6c4ac299175ddc50d1ba5443d68741/server/node.go#L813)):*
> ```Go
> 		})
> 	if err != nil {
> 		resp = nil
> ```

don't think you need this

---

*[storage/store_pool.go, line 334 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQJ3o1zKVLix3UGrfL:-KHQJ3o1zKVLix3UGrfM:-1511855915) ([raw file](https://github.com/cockroachdb/cockroach/blob/366af7d08104cba7e1c0ddb50f0bc5720a240b42/storage/store_pool.go#L334)):*
> ```Go
> // Attr->stores, for efficiency. Ensure that entries in this map still
> // have an opportunity to be garbage collected.
> func (sp *StorePool) GetStoreList(required roachpb.Attributes, deterministic bool) (StoreList, int) {
> ```

can you add rationale in the commit message?

---

*[util/pluralize.go, line 20 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQIwIoeUBntpFvo2C8:-KHQIwIoeUBntpFvo2C9:1530141259) ([raw file](https://github.com/cockroachdb/cockroach/blob/db74645f1ab880e95823d1cd21e7bd69b9e64dac/util/pluralize.go#L20)):*
> ```Go
> 
> // Pluralize returns a single character 's' unless n == 1.
> func Pluralize(n int64) string {
> ```

what, no test?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[kv/send_test.go, line 66 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQJLfffUtDlO_gM9LY:-KHQYZVo1NZpCL-Zo_qU:110133355) ([raw file](https://github.com/cockroachdb/cockroach/blob/831ebe1b6f6c4ac299175ddc50d1ba5443d68741/kv/send_test.go#L66)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> if you make this RPC belong to a new service, you can avoid this stub implementation</details>
Done (we discussed offline that it was fine as is).

---

*[roachpb/api.proto, line 792 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQJUU6v7YR2VtX-d7E:-KHQMVU4O5bk3uu-kq8x:-7331024) ([raw file](https://github.com/cockroachdb/cockroach/blob/831ebe1b6f6c4ac299175ddc50d1ba5443d68741/roachpb/api.proto#L792)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> why'd you add it, if it's not used?</details>
See the question, I wanted to call this to the attention of the reviewers. If we ever need a routing layer based on NodeID, this would probably have to be in there (but can still be added later, albeit with a more complicated migration).

---

*[server/admin.go, line 801 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQKSAu202f0Pmza9Ct:-KHQX4qpDlNTAsTBnkhB:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/831ebe1b6f6c4ac299175ddc50d1ba5443d68741/server/admin.go#L801)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can you sprinkle some comments?</details>
Done.

---

*[server/admin.go, line 941 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQKEKxTuHQKcG08X2h:-KHQXBqUb7xc027-TzpH:1296297606) ([raw file](https://github.com/cockroachdb/cockroach/blob/831ebe1b6f6c4ac299175ddc50d1ba5443d68741/server/admin.go#L941)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this change seems unrelated. is it?</details>
Which change? Everything here seems related.

---

*[server/node.go, line 806 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQJwiKoWoUihv8iybN:-KHQXebuKBxOaMo2kRZv:2146618781) ([raw file](https://github.com/cockroachdb/cockroach/blob/831ebe1b6f6c4ac299175ddc50d1ba5443d68741/server/node.go#L806)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> is there any reason to initialize Frozen?</details>
Nope, removed.

---

*[server/node.go, line 813 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQK5K4qG7sqfCYr0D2:-KHQXkjMi8viiYp9Wkru:2072981889) ([raw file](https://github.com/cockroachdb/cockroach/blob/831ebe1b6f6c4ac299175ddc50d1ba5443d68741/server/node.go#L813)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> don't think you need this</details>
I agree, but it looked "cleaner". Happily removed.

---

*[storage/store_pool.go, line 334 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQJ3o1zKVLix3UGrfL:-KHQYLXVncS60O8C1RWl:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/366af7d08104cba7e1c0ddb50f0bc5720a240b42/storage/store_pool.go#L334)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can you add rationale in the commit message?</details>
Done.

---

*[util/pluralize.go, line 20 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQIwIoeUBntpFvo2C8:-KHQYSMpV2BAJkEzKylb:-244918708) ([raw file](https://github.com/cockroachdb/cockroach/blob/db74645f1ab880e95823d1cd21e7bd69b9e64dac/util/pluralize.go#L20)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> what, no test?</details>
Shocking, isn't it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598)*

**Comment by bdarnell** [comment]
Reviewed 4 of 5 files at r1, 4 of 4 files at r2, 8 of 8 files at r3.
Review status: 4 of 16 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[roachpb/api.proto, line 792 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQJUU6v7YR2VtX-d7E:-KHQ_irdjlr1tOmWEYA0:233179823) ([raw file](https://github.com/cockroachdb/cockroach/blob/831ebe1b6f6c4ac299175ddc50d1ba5443d68741/roachpb/api.proto#L792)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> See the question, I wanted to call this to the attention of the reviewers. If we ever need a routing layer based on NodeID, this would probably have to be in there (but can still be added later, albeit with a more complicated migration).</details>
I'd keep it in, for consistency with our other RPCs  (the node ID in BatchRequest_Header isn't used either, but node IDs in ReplicaDescriptor still matter for coalesced heartbeats). 

I was kind of surprised to learn that StoreDescriptors contain NodeDescriptors so you didn't need to use the node ID even internally; if we're concerned about the size and cost of gossiping store descriptors (see rebalancing RFC) we might want to change that so indirecting through the node ID becomes more important.

---

*[server/admin.go, line 825 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQZE3BZS6pYvUMO-BE:-KHQZE3BZS6pYvUMO-BF:1625937751) ([raw file](https://github.com/cockroachdb/cockroach/blob/831ebe1b6f6c4ac299175ddc50d1ba5443d68741/server/admin.go#L825)):*
> ```Go
> 	var err error
> 	for r := retry.Start(opts); r.Next(); {
> 		storeList, _ := s.server.storePool.GetStoreList(roachpb.Attributes{}, false)
> ```

Using the StorePool for this will silently miss stores that have been down long enough fro their gossiped descriptors to expire. This is a problem unless we can make sure that those stores don't rejoin the cluster after the upgrade (and note that the TTL on store descriptor gossip is shorter than the time for the repair queue to consider a node dead and move ranges away from it). 

As I mentioned in the other PR, we could get a definitive list of stores that need to participate in the freeze by retuning the set in ChangeFrozenResponse.

---

*[server/admin.go, line 841 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQY6gJ91FnhcsFAlg_:-KHQY6gJ91FnhcsFAlga:-590936831) ([raw file](https://github.com/cockroachdb/cockroach/blob/831ebe1b6f6c4ac299175ddc50d1ba5443d68741/server/admin.go#L841)):*
> ```Go
> 						mu.oks[storeID] = resp.Frozen
> 					} else {
> 						delete(mu.oks, storeID)
> ```

Why delete here instead of leaving it false? If we're taking this path we're returning an error anyway, so there's no need (that I see) to handle the same error twice. 

---

*[server/admin.go, line 859 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQWvnIaw2VsYiBRVFO:-KHQWvnJrhuvYT3u3pi3:-1067218142) ([raw file](https://github.com/cockroachdb/cockroach/blob/831ebe1b6f6c4ac299175ddc50d1ba5443d68741/server/admin.go#L859)):*
> ```Go
> 				return err
> 			}
> 			if !s.server.stopper.RunAsyncTask(func() {
> ```

I'd like to see this be a `RunLimitedAsyncTask` (in which case the scope of `mu.Lock` will need to be narrowed)

---

*[server/node.go, line 792 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQYnamLvth_c2Yss1z:-KHQYnamLvth_c2Yss2-:-1350778909) ([raw file](https://github.com/cockroachdb/cockroach/blob/831ebe1b6f6c4ac299175ddc50d1ba5443d68741/server/node.go#L792)):*
> ```Go
> ) error {
> 	if h.NodeID != n.Descriptor.NodeID {
> 		return util.Errorf("request for NodeID %d cannot be served by NodeID %d",
> ```

Do you have a specific concern about store commands being sent to the wrong node or is this just general paranoia?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598)*

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r5, 8 of 8 files at r6.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[roachpb/api.proto, line 792 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQJUU6v7YR2VtX-d7E:-KHQawNVNxK9js5z-RRO:-1226759385) ([raw file](https://github.com/cockroachdb/cockroach/blob/831ebe1b6f6c4ac299175ddc50d1ba5443d68741/roachpb/api.proto#L792)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> See the question, I wanted to call this to the attention of the reviewers. If we ever need a routing layer based on NodeID, this would probably have to be in there (but can still be added later, albeit with a more complicated migration).</details>
Ah, fair point. Let's keep it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598)*

**Comment by tschottdorf** [comment]
Review status: 4 of 19 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[roachpb/api.proto, line 792 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQJUU6v7YR2VtX-d7E:-KHQiDwEf2RVsGdmMJ9e:1225393981) ([raw file](https://github.com/cockroachdb/cockroach/blob/831ebe1b6f6c4ac299175ddc50d1ba5443d68741/roachpb/api.proto#L792)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Ah, fair point. Let's keep it.</details>
I removed the TODO.

---

*[server/admin.go, line 825 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQZE3BZS6pYvUMO-BE:-KHQiy7LexWn2wMSykBP:-1490181913) ([raw file](https://github.com/cockroachdb/cockroach/blob/831ebe1b6f6c4ac299175ddc50d1ba5443d68741/server/admin.go#L825)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Using the StorePool for this will silently miss stores that have been down long enough fro their gossiped descriptors to expire. This is a problem unless we can make sure that those stores don't rejoin the cluster after the upgrade (and note that the TTL on store descriptor gossip is shorter than the time for the repair queue to consider a node dead and move ranges away from it). 
> 
> As I mentioned in the other PR, we could get a definitive list of stores that need to participate in the freeze by retuning the set in ChangeFrozenResponse.</details>
Yep, I remember you mentioning that. I went the simple route first because adding in the stores into the response amounts to a weird mutation of the response above Raft. Happy to consider it, but I'd like to do that as a follow-up if possible.

---

*[server/admin.go, line 841 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQY6gJ91FnhcsFAlg_:-KHQji4VCbWc7NfsKbGi:500918524) ([raw file](https://github.com/cockroachdb/cockroach/blob/831ebe1b6f6c4ac299175ddc50d1ba5443d68741/server/admin.go#L841)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Why delete here instead of leaving it false? If we're taking this path we're returning an error anyway, so there's no need (that I see) to handle the same error twice. </details>
You're right, done.

---

*[server/admin.go, line 859 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQWvnIaw2VsYiBRVFO:-KHQu_NvgM8Uj-IcRSPa:794897783) ([raw file](https://github.com/cockroachdb/cockroach/blob/831ebe1b6f6c4ac299175ddc50d1ba5443d68741/server/admin.go#L859)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> I'd like to see this be a `RunLimitedAsyncTask` (in which case the scope of `mu.Lock` will need to be narrowed)</details>
Done. I made a change (in a separate commit) that allows `RunLimitedAsyncTask` to return false if the semaphore is full as I don't want the retry loop to be throttled.

---

*[server/node.go, line 792 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQYnamLvth_c2Yss1z:-KHQie99xGgMN2b8AR0O:-526382568) ([raw file](https://github.com/cockroachdb/cockroach/blob/831ebe1b6f6c4ac299175ddc50d1ba5443d68741/server/node.go#L792)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Do you have a specific concern about store commands being sent to the wrong node or is this just general paranoia?</details>
Just paranoia (and allowing the casual reader to worry about one less thing).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598)*

**Comment by bdarnell** [comment]
Reviewed 5 of 8 files at r10.
Review status: 9 of 19 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[server/admin.go, line 825 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQZE3BZS6pYvUMO-BE:-KHR3xUcvqHytzfkHPj1:-31855301) ([raw file](https://github.com/cockroachdb/cockroach/blob/831ebe1b6f6c4ac299175ddc50d1ba5443d68741/server/admin.go#L825)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Yep, I remember you mentioning that. I went the simple route first because adding in the stores into the response amounts to a weird mutation of the response above Raft. Happy to consider it, but I'd like to do that as a follow-up if possible.</details>
What's weird about it? The replica command has access to the range descriptor so it knows all the stores, and then we'd compute the set union in `ChangeFrozenResponse.combine`. That's a little more complicated than the current combine implementation but still seems reasonable.

---

*[server/admin.go, line 859 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQWvnIaw2VsYiBRVFO:-KHR8_CxeJfOtFD0eyfg:-1712209463) ([raw file](https://github.com/cockroachdb/cockroach/blob/831ebe1b6f6c4ac299175ddc50d1ba5443d68741/server/admin.go#L859)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Done. I made a change (in a separate commit) that allows `RunLimitedAsyncTask` to return false if the semaphore is full as I don't want the retry loop to be throttled.</details>
Why don't you want to block? As it is, this will busy-loop until the semaphore frees up.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598)*

**Comment by tschottdorf** [comment]
Review status: 9 of 19 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[server/admin.go, line 825 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQZE3BZS6pYvUMO-BE:-KHR99IVqXpl1_UqkoPU:77263293) ([raw file](https://github.com/cockroachdb/cockroach/blob/831ebe1b6f6c4ac299175ddc50d1ba5443d68741/server/admin.go#L825)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> What's weird about it? The replica command has access to the range descriptor so it knows all the stores, and then we'd compute the set union in `ChangeFrozenResponse.combine`. That's a little more complicated than the current combine implementation but still seems reasonable.</details>
Oh, yeah, that sounds reasonable - I thought we had to do something with the store on each replica - now that I think about it, I wasn't really thinking. Will give this a shot and ping this comment.

---

*[server/admin.go, line 859 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQWvnIaw2VsYiBRVFO:-KHRAnzK2OmhrsArioSo:-2119104952) ([raw file](https://github.com/cockroachdb/cockroach/blob/831ebe1b6f6c4ac299175ddc50d1ba5443d68741/server/admin.go#L859)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Why don't you want to block? As it is, this will busy-loop until the semaphore frees up.</details>
It wasn't busy-looping, just running through the remaining stores kind of pointlessly (I added a break).
I think it's weird to have a retry loop and then blocking for possibly long periods of time inside of one iteration of the loop. Don't feel too strongly in this case though, so I can back it out if you prefer that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598)*

**Comment by tschottdorf** [comment]
Review status: 4 of 25 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[server/admin.go, line 825 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQZE3BZS6pYvUMO-BE:-KHRVpN9bCyzqDE3SwC-:899333092) ([raw file](https://github.com/cockroachdb/cockroach/blob/831ebe1b6f6c4ac299175ddc50d1ba5443d68741/server/admin.go#L825)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Oh, yeah, that sounds reasonable - I thought we had to do something with the store on each replica - now that I think about it, I wasn't really thinking. Will give this a shot and ping this comment.</details>
Done, PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598)*

**Comment by bdarnell** [comment]
Reviewed 3 of 4 files at r13, 4 of 4 files at r14, 11 of 11 files at r15, 3 of 3 files at r16.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[server/admin.go, line 859 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQWvnIaw2VsYiBRVFO:-KHVPk6LxZDg9NiQ4fLn:-1848921914) ([raw file](https://github.com/cockroachdb/cockroach/blob/831ebe1b6f6c4ac299175ddc50d1ba5443d68741/server/admin.go#L859)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> It wasn't busy-looping, just running through the remaining stores kind of pointlessly (I added a break).
> I think it's weird to have a retry loop and then blocking for possibly long periods of time inside of one iteration of the loop. Don't feel too strongly in this case though, so I can back it out if you prefer that.</details>
I think that blocking until the semaphore becomes available is better than going back to the exponential backoff of the retry loop (especially since that has a hard `MaxRetries` limit); many of our retry loops can run for a long time in one iteration. I would reverse the change to `Stopper`.

---

*[server/admin.go, line 829 \[r16\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHVQhOFH_lLPKL6qyXL:-KHVQhOFH_lLPKL6qyXM:981050000) ([raw file](https://github.com/cockroachdb/cockroach/blob/36c256951c209e258348044ca895645829fa0691/server/admin.go#L829)):*
> ```Go
> 		}
> 	}
> 	storeList, _ := s.server.storePool.GetStoreList(roachpb.Attributes{}, false)
> ```

This should loop over `required` instead of getting a list from the `StorePool`. Gossip can be used to map stores to addresses.

---

*[storage/store_pool.go, line 308 \[r16\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHVOsM5GOanijDPWz8L:-KHVOsM5GOanijDPWz8M:-1808110473) ([raw file](https://github.com/cockroachdb/cockroach/blob/36c256951c209e258348044ca895645829fa0691/storage/store_pool.go#L308)):*
> ```Go
> // stats for those stores.
> type StoreList struct {
> 	Stores      []*roachpb.StoreDescriptor
> ```

This no longer needs to be exported if you change the poller as I suggested above.

---

*[storage/store_pool.go, line 334 \[r16\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHVOuMAw8jrUo3EIVdh:-KHVOuMAw8jrUo3EIVdi:-499318459) ([raw file](https://github.com/cockroachdb/cockroach/blob/36c256951c209e258348044ca895645829fa0691/storage/store_pool.go#L334)):*
> ```Go
> // Attr->stores, for efficiency. Ensure that entries in this map still
> // have an opportunity to be garbage collected.
> func (sp *StorePool) GetStoreList(required roachpb.Attributes, deterministic bool) (StoreList, int) {
> ```

Ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598)*

**Comment by tschottdorf** [comment]
Updated, PTAL.

<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> #### Add and use Store\-level PollFrozen endpoint
> 
> After having dispatched Freeze requests to all Ranges in the cluster, the
> 
> ClusterFreeze endpoint now polls all (active) Stores in the cluster (as known
> 
> to the store pool) for a duration, requiring them to confirm that all of their
> 
> Replicas have been frozen.
> 
> 
> 
> There is room for improvement: A Store may house "dead" Replicas (which have
> 
> been removed from the Range they believe they are still part of), which would
> 
> consequently never freeze. A side effect which prioritizes such Replicas in
> 
> the GC queue should be able to remedy that, but this is not included in this
> 
> change.
> 
> 
> 
> With this change in, we can consider stop-the-world upgrades as our chosen
> 
> migration strategy of choice for the time being.
> 
> 
> 
> I'm planning to refactor the `server/admin.go` code a little bit to be able to test
> 
> the wait logic in isolation, but this should be good for a first review.
> 
> There's also the option of instead querying each **Node** instead of each Store
> 
> (saving RPCs), but addressing Stores felt more natural.
> 
> 
> </details>


---

Review status: 4 of 20 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[server/admin.go, line 859 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHQWvnIaw2VsYiBRVFO:-KHWTP7aDQ1AXRKbAYEb:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/831ebe1b6f6c4ac299175ddc50d1ba5443d68741/server/admin.go#L859)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> I think that blocking until the semaphore becomes available is better than going back to the exponential backoff of the retry loop (especially since that has a hard `MaxRetries` limit); many of our retry loops can run for a long time in one iteration. I would reverse the change to `Stopper`.</details>
Done.

---

*[server/admin.go, line 829 \[r16\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHVQhOFH_lLPKL6qyXL:-KHWTG8ZxQi8PKGUZyPX:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/36c256951c209e258348044ca895645829fa0691/server/admin.go#L829)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> This should loop over `required` instead of getting a list from the `StorePool`. Gossip can be used to map stores to addresses.</details>
Done.

---

*[storage/store_pool.go, line 308 \[r16\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHVOsM5GOanijDPWz8L:-KHWTZFgGfzx0-XbYAem:1855125178) ([raw file](https://github.com/cockroachdb/cockroach/blob/36c256951c209e258348044ca895645829fa0691/storage/store_pool.go#L308)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> This no longer needs to be exported if you change the poller as I suggested above.</details>
Done (dropped the commit).

---

*[storage/store_pool.go, line 334 \[r16\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHVOuMAw8jrUo3EIVdh:-KHWT_dxW4pGJxcjVGQa:1855125178) ([raw file](https://github.com/cockroachdb/cockroach/blob/36c256951c209e258348044ca895645829fa0691/storage/store_pool.go#L334)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Ditto</details>
Done (dropped the commit).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-:-KHWTeEFlDq9DC2C78Iv:-1677991115)*

**Comment by tamird** [comment]
Reviewed 12 of 12 files at r7, 4 of 8 files at r10, 7 of 21 files at r17, 12 of 12 files at r18, 3 of 3 files at r19.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[roachpb/api.proto, line 246 \[r19\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHWVkqavdBLLp3CFC1I:-KHWVkqcA9iSsLRMbiXV:-1134740572) ([raw file](https://github.com/cockroachdb/cockroach/blob/307836808e0d7591e4b89207065a5776efbc1dbd/roachpb/api.proto#L246)):*
> ```protobuf
>   // a Replica on which the command should execute, even when already
>   // frozen).
>   map<int32, int32> stores = 8 [(gogoproto.nullable) = false,
> ```

why 8?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[roachpb/api.proto, line 246 \[r19\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-KHWVkqavdBLLp3CFC1I:-KHWY-9W8XnhTDgj0yxN:-181068375) ([raw file](https://github.com/cockroachdb/cockroach/blob/307836808e0d7591e4b89207065a5776efbc1dbd/roachpb/api.proto#L246)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> why 8?</details>
Because I'm bad at copy-paste. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598)*

**Comment by bdarnell** [comment]
:lgtm:

<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Updated, PTAL.</details>


---

Reviewed 1 of 21 files at r17, 10 of 12 files at r18, 2 of 5 files at r20, 3 of 3 files at r21.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6598#-:-KHWmYzjktTjVNiM-AAB:1417088721)*

**Pull request merged**
