### PR TITLE
kvserver: add leader lease variant for TestLeaseMetricsOnSplitAndTransfer

### PR DESCRIPTION
**Pull request by arulajmani**
References #133763
Release note: None

### CODE REVIEW

**Review by iskettaneh — CHANGES_REQUESTED** [review]
LGTM pending the comment

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136159#-:-OCdlmRa3MN5_uzmvTHV:bq4bagw)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/store.go` line 3475 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136159#-OCdiqis0f6l9QakyaXu:-OCdiqis0f6l9QakyaXv:b-1y2np6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9917d9af7c00b2866291c0269c58f8ea4feef884/pkg/kv/kvserver/store.go#L3475)):*
> ```Go
> 	s.metrics.LeaseHolderCount.Update(leaseHolderCount)
> 	if leaseExpirationCount != 0 {
> 		log.Infof(ctx, "!!!!! here")
> ```

This was forgotten

**Review by iskettaneh — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136159#-:-OCdlpGX8bluEomR0wg0:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Review by iskettaneh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136159)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/roachpb/data.go` line 1994 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136159#-OCdm0IBESiSB_6eSthA:-OCdm0IBESiSB_6eSthB:bw1thl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9917d9af7c00b2866291c0269c58f8ea4feef884/pkg/roachpb/data.go#L1994)):*
> ```Go
> 
> // EpochAndLeaderLeaseType returns a list of {epcoh, leader} lease types.
> func EpochAndLeaderLeaseType() []LeaseType {
> ```

Curious why we don't test for expiration based leases?

**Review by arulajmani — COMMENTED** [review]
TFTR!

bors r=iskettaneh 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136159#-:-OCemypV3NRQniEshruZ:b9bpn4r)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @iskettaneh)

___
*[`pkg/kv/kvserver/store.go` line 3475 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136159#-OCdiqis0f6l9QakyaXu:-OCelTK906Nen5UGWAnr:bn5yvwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/9917d9af7c00b2866291c0269c58f8ea4feef884/pkg/kv/kvserver/store.go#L3475)):*
<details><summary><i>Previously, iskettaneh wrote…</i></summary><blockquote>

This was forgotten
</blockquote></details>

Thanks for catching. Fixed.
___
*[`pkg/roachpb/data.go` line 1994 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136159#-OCdm0IBESiSB_6eSthA:-OCelV9V6jKP4uxR_Rh4:b8raasx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9917d9af7c00b2866291c0269c58f8ea4feef884/pkg/roachpb/data.go#L1994)):*
<details><summary><i>Previously, iskettaneh wrote…</i></summary><blockquote>

Curious why we don't test for expiration based leases?
</blockquote></details>

The test we were updating was written specifically for epoch based leases and disabled expiration based leases to avoid metamorphism. I could've introduced a expiration based lease variant as well, but it didn't seem necessary, as it was already acquiring an expiration based lease for the node liveness range to begin with, which allows us to test metrics related to expiration based leases.

**Pull request merged**
