### PR TITLE
ttl: add queries to job details

### LINKED ISSUE #81905: sql: Observability improvements meta issue for TTL deletions jobs
- [ ] Include SQL statements in Jobs details page for select and delete queries. See [previous comment](https://github.com/cockroachdb/cockroach/issues/79916#issuecomment-1098542735) but unclear why #79547 impacts what displays for Jobs detail
image

Jira issue: CRDB-16123
Epic CRDB-14592

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/81905

This helps with observability so users can understand what the TTL job
is doing behind the scenes.

The job details in the DB console will show:
```
ttl for defaultdb.public.t
-- for each range, iterate to find rows:
SELECT id FROM [108 AS tbl_name]
AS OF SYSTEM TIME '30s'
WHERE <crdb_internal_expiration OR ttl_expiration_expression> <= $1
AND (id) > (<range start>) AND (id) < (<range end>)
ORDER BY id
LIMIT <ttl_select_batch_size>
-- then delete with:
DELETE FROM [108 AS tbl_name]
WHERE <crdb_internal_expiration OR ttl_expiration_expression> <= $1
AND (id) IN (<rows selected above>)
```

Release note: None

Release justification: low risk change

### CODE REVIEW

**Review by otan — APPROVED** [review]
whoever came up with this idea, i love it

**Comment by rafiss** [comment]
tftr!

bors r=otan

**Comment by yuzefovich** [comment]
I think there are some test failures here.

bors r-

**Comment by rafiss** [comment]
fixed the tests, thanks for pointing that out

bors r=otan

**Pull request merged**
