### PR TITLE
storage: tighten assertion on applied index

### PR DESCRIPTION
**Pull request by tbg**
See #7224.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7323)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/replica.go, line 1985 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7323#-KKfra65Y4EY7w_BqcQA:-KKfra65Y4EY7w_BqcQB:-1648041240) ([raw file](https://github.com/cockroachdb/cockroach/blob/b34a5d94ba4875313eb1f10c1470151d95eb7e39/storage/replica.go#L1985)):*
> ```Go
> 	r.mu.Unlock()
> 
> 	if oldIndex+1 != index {
> ```

nit: yoda condition

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7323#-:-KKfriXHptKUgRC_Giij:1417088721)*

**Comment by bdarnell** [comment]
LGTM

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/replica.go, line 1605 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7323#-KKhIf0jTZvvO1RjB5Mv:-KKhIf0kut1DWoiv_PcG:-1179997813) ([raw file](https://github.com/cockroachdb/cockroach/blob/b34a5d94ba4875313eb1f10c1470151d95eb7e39/storage/replica.go#L1605)):*
> ```Go
> 				// Avoid jumps in the applied index when the next "real"
> 				// command applies.
> 				r.mu.state.RaftAppliedIndex++
> ```

It makes me nervous to increment this without persisting it to disk. I think it will actually work, but only because we'll replay the empty commands on restart before we do anything that relies on RaftAppliedIndex being correct. 

We can give this a shot and see if it catches anything, but if not we may want to undo it so we're not leaving a trap for ourselves in the future by allowing the in-memory state to diverge from the on-disk state.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7323#-:-KKhKR2Uv9Y0NI47KQJd:676834233)*

**Comment by tschottdorf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/replica.go, line 1605 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7323#-KKhIf0jTZvvO1RjB5Mv:-KKoXgE91jtpe9tqqBAx:655101997) ([raw file](https://github.com/cockroachdb/cockroach/blob/b34a5d94ba4875313eb1f10c1470151d95eb7e39/storage/replica.go#L1605)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> It makes me nervous to increment this without persisting it to disk. I think it will actually work, but only because we'll replay the empty commands on restart before we do anything that relies on RaftAppliedIndex being correct. 
> 
> We can give this a shot and see if it catches anything, but if not we may want to undo it so we're not leaving a trap for ourselves in the future by allowing the in-memory state to diverge from the on-disk state.
</details>
Agreed, not sure what I was thinking. PTAL, should look better now (though there might be value in pushing empty commands down to `applyRaftCommand` to remove some of the work here down the road).

---

*[storage/replica.go, line 1985 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7323#-KKfra65Y4EY7w_BqcQA:-KKoXvWgquE-tzSZg9qF:-88057169) ([raw file](https://github.com/cockroachdb/cockroach/blob/b34a5d94ba4875313eb1f10c1470151d95eb7e39/storage/replica.go#L1985)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: yoda condition
</details>
Added (yoda?) comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7323)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[storage/replica.go, line 1985 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7323#-KKfra65Y4EY7w_BqcQA:-KKoswXzyOEN0SOqYnaa:-317053891) ([raw file](https://github.com/cockroachdb/cockroach/blob/b34a5d94ba4875313eb1f10c1470151d95eb7e39/storage/replica.go#L1985)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Added (yoda?) comment.
</details>
not what i meant. just asking for the left and right hand sides of the comparison to be reversed.

---

*[storage/replica.go, line 1440 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7323#-KKovDzPJDf54cv-4oy-:-KKovDzPJDf54cv-4oy0:-57995571) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f14886a88f02a308a2f9a4f75534c5ec362ed5e/storage/replica.go#L1440)):*
> ```Go
> 				// Error handling is intentionally deferred to move it out
> 				// of the lock.
> 				newStats, err := saveState(r.store.Engine(), r.mu.state)
> ```

is this code duplicated somewhere else? it's not clear to me why this is the right stuff to do in this location, perhaps a method can be extracted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7323)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[storage/replica.go, line 1985 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7323#-KKfra65Y4EY7w_BqcQA:-KKowU2ktDvf6c185kpl:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/b34a5d94ba4875313eb1f10c1470151d95eb7e39/storage/replica.go#L1985)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> not what i meant. just asking for the left and right hand sides of the comparison to be reversed.
</details>
Done.

---

*[storage/replica.go, line 1440 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7323#-KKovDzPJDf54cv-4oy-:-KKowOVlvmMZBiNnVy3R:-1120817209) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f14886a88f02a308a2f9a4f75534c5ec362ed5e/storage/replica.go#L1440)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> is this code duplicated somewhere else? it's not clear to me why this is the right stuff to do in this location, perhaps a method can be extracted.
</details>
See my comment above. It's too early for a coherent refactor (since our state updates are all over the place).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7323)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7323)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[storage/replica.go, line 1440 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7323#-KKp8bHOp2-XctCdu9-j:-KKp8bHOp2-XctCdu9-k:-1925160472) ([raw file](https://github.com/cockroachdb/cockroach/blob/da99af2941a964e32389399acd57003ded09e130/storage/replica.go#L1440)):*
> ```Go
> 				// Error handling is intentionally deferred to move it out
> 				// of the lock.
> 				newStats, err := saveState(r.store.Engine(), r.mu.state)
> ```

`saveState` doesn't create a batch. If you give it a raw Engine instead of a batch, it will do a bunch of non-atomic writes. I think that trying to recreate a partial update here is more trouble than it's worth. I'd rather generate a RaftCommand containing a NoopRequest.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7323)*

**Comment by tschottdorf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/replica.go, line 1440 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7323#-KKp8bHOp2-XctCdu9-j:-KKpxLOgye2OFb-aukws:1156309391) ([raw file](https://github.com/cockroachdb/cockroach/blob/da99af2941a964e32389399acd57003ded09e130/storage/replica.go#L1440)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> `saveState` doesn't create a batch. If you give it a raw Engine instead of a batch, it will do a bunch of non-atomic writes. I think that trying to recreate a partial update here is more trouble than it's worth. I'd rather generate a RaftCommand containing a NoopRequest.
</details>
How's that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7323)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7323#-:-KKrAyONvEb0c8CBoYyH:1417088721)*

**Pull request merged**
