### PR TITLE
build: switch to `tinystringer`

### LINKED ISSUE #59855: stringer rules behave poorly in Bazel
There are a few places where we depend on `go_sdk` from within Bazel and I'm not convinced that it's necessary or advantageous for us.

```
pkg/sql/schemachange/BUILD.bazel
54:       env PATH=`dirname $(location @go_sdk//:bin/go)` HOME=$(GENDIR) \
58:        "@go_sdk//:bin/go",

pkg/sql/opt/BUILD.bazel
108:      env PATH=`dirname $(location @go_sdk//:bin/go)` HOME=$(GENDIR) \
113:        "@go_sdk//:bin/go",

pkg/util/encoding/BUILD.bazel
76:#        env PATH=`dirname $(location @go_sdk//:bin/go)` HOME=$(GENDIR) \
81:#         "@go_sdk//:bin/go",

build/STRINGER.bzl
9:         env PATH=`dirname $(location @go_sdk//:bin/go)` HOME=$(GENDIR) \
13:         "@go_sdk//:bin/go",
```

Epic CRDB-8308

Jira issue: CRDB-3221

### PR DESCRIPTION
**Pull request by rickystewart**
Create a new binary called `tinystringer` and use it instead of upstream `stringer`.

`tinystringer` serves much the same purpose as `stringer` but has fewer features. `stringer` uses `packages.Load()` which doesn't work inside the Bazel sandbox. Instead we simply parse the source files, not intending to fully understand the AST, but only knowing enough about Go to infer the correct values for `const`s that we `stringer` in the codebase.

I also removed `stringerutil` and re-implemented the functionality as
extra optional arguments to `tinystringer`, so now you can have it
directly generate a map or slice of the enum elements for you. The
resulting code seems more readable to me.

Closes #59855.

Epic: CRDB-8308
Release note: None

### CODE REVIEW

**Comment by rickystewart** [comment]
There are some apparently legitimate test failures still here which I will address but I think that overall this is more or less ready to review.

**Comment by rickystewart** [comment]
Only one test is still failing: `TestRel/comparetest/yaml`. I can't figure out the failure here. It seems there is some confusion about the `String()` values from `pkg/sql/schemachanger/rel/internal/comparetest/testattr_string.go`, but I have investigated that file and the results seem sensible. Does anyone have any ideas?

```
                       Diff:
                        --- Expected
                        +++ Actual
                        @@ -1,2 +1,2 @@
                        -([]uint8) (len=1013) {
                        +([]uint8) (len=996) {
                          00000000  6e 61 6d 65 3a 20 63 6f  6d 70 61 72 65 74 65 73  |name: comparetes|
                        @@ -11,56 +11,55 @@
                          00000090  74 3a 20 34 7d 0a 61 74  74 72 69 62 75 74 65 73  |t: 4}.attributes|
                        - 000000a0  3a 0a 20 20 20 20 65 31  3a 20 7b 5f 75 69 6e 74  |:.    e1: {_uint|
                        - 000000b0  70 74 72 3a 20 30 2c 20  69 3a 20 30 2c 20 69 31  |ptr: 0, i: 0, i1|
                        - 000000c0  36 3a 20 31 2c 20 69 33  32 3a 20 30 2c 20 69 36  |6: 1, i32: 0, i6|
                        - 000000d0  34 3a 20 30 2c 20 69 38  3a 20 31 2c 20 70 69 38  |4: 0, i8: 1, pi8|
                        - 000000e0  3a 20 31 2c 20 73 74 72  3a 20 22 22 2c 20 75 69  |: 1, str: "", ui|
                        - 000000f0  3a 20 30 2c 20 75 69 31  36 3a 20 30 2c 20 75 69  |: 0, ui16: 0, ui|
                        - 00000100  33 32 3a 20 30 2c 20 75  69 36 34 3a 20 30 2c 20  |32: 0, ui64: 0, |
                        - 00000110  75 69 38 3a 20 30 7d 0a  72 75 6c 65 73 3a 20 5b  |ui8: 0}.rules: [|
                        - 00000120  5d 0a 71 75 65 72 69 65  73 3a 20 5b 5d 0a 63 6f  |].queries: [].co|
                        - 00000130  6d 70 61 72 69 73 6f 6e  73 3a 0a 20 20 20 20 2d  |mparisons:.    -|
                        - 00000140  20 65 6e 74 69 74 69 65  73 3a 20 5b 65 32 2c 20  | entities: [e2, |
                        - 00000150  65 33 2c 20 65 31 5d 0a  20 20 20 20 20 20 74 65  |e3, e1].      te|
                        - 00000160  73 74 73 3a 0a 20 20 20  20 20 20 20 20 2d 20 61  |sts:.        - a|
                        - 00000170  74 74 72 73 3a 20 5b 69  38 5d 0a 20 20 20 20 20  |ttrs: [i8].     |
                        - 00000180  20 20 20 20 20 6f 72 64  65 72 3a 20 5b 5b 65 31  |     order: [[e1|
                        - 00000190  5d 2c 20 5b 65 32 5d 2c  20 5b 65 33 5d 5d 0a 20  |], [e2], [e3]]. |
                        - 000001a0  20 20 20 20 20 20 20 2d  20 61 74 74 72 73 3a 20  |       - attrs: |
                        - 000001b0  5b 70 73 74 72 5d 0a 20  20 20 20 20 20 20 20 20  |[pstr].         |
                        - 000001c0  20 6f 72 64 65 72 3a 20  5b 5b 65 31 2c 20 65 32  | order: [[e1, e2|
                        - 000001d0  2c 20 65 33 5d 5d 0a 20  20 20 20 20 20 20 20 2d  |, e3]].        -|
                        - 000001e0  20 61 74 74 72 73 3a 20  5b 70 69 38 5d 0a 20 20  | attrs: [pi8].  |
                        - 000001f0  20 20 20 20 20 20 20 20  6f 72 64 65 72 3a 20 5b  |        order: [|
                        - 00000200  5b 65 31 5d 2c 20 5b 65  32 2c 20 65 33 5d 5d 0a  |[e1], [e2, e3]].|
                        - 00000210  20 20 20 20 20 20 20 20  2d 20 61 74 74 72 73 3a  |        - attrs:|
                        - 00000220  20 5b 70 69 38 2c 20 70  69 31 36 5d 0a 20 20 20  | [pi8, pi16].   |
                        - 00000230  20 20 20 20 20 20 20 6f  72 64 65 72 3a 20 5b 5b  |       order: [[|
                        - 00000240  65 31 5d 2c 20 5b 65 32  5d 2c 20 5b 65 33 5d 5d  |e1], [e2], [e3]]|
                        - 00000250  0a 20 20 20 20 20 20 20  20 2d 20 61 74 74 72 73  |.        - attrs|
                        - 00000260  3a 20 5b 70 69 31 36 5d  0a 20 20 20 20 20 20 20  |: [pi16].       |
                        - 00000270  20 20 20 6f 72 64 65 72  3a 20 5b 5b 65 32 5d 2c  |   order: [[e2],|
                        - 00000280  20 5b 65 33 5d 2c 20 5b  65 31 5d 5d 0a 20 20 20  | [e3], [e1]].   |
                        - 00000290  20 2d 20 65 6e 74 69 74  69 65 73 3a 20 5b 65 32  | - entities: [e2|
                        - 000002a0  2c 20 65 33 2c 20 65 31  2c 20 65 34 5d 0a 20 20  |, e3, e1, e4].  |
                        - 000002b0  20 20 20 20 74 65 73 74  73 3a 0a 20 20 20 20 20  |    tests:.     |
                        - 000002c0  20 20 20 2d 20 61 74 74  72 73 3a 20 5b 75 69 5d  |   - attrs: [ui]|
                        - 000002d0  0a 20 20 20 20 20 20 20  20 20 20 6f 72 64 65 72  |.          order|
                        - 000002e0  3a 20 5b 5b 65 31 2c 20  65 32 2c 20 65 33 2c 20  |: [[e1, e2, e3, |
                        - 000002f0  65 34 5d 5d 0a 20 20 20  20 20 20 20 20 2d 20 61  |e4]].        - a|
                        - 00000300  74 74 72 73 3a 20 5b 70  73 74 72 5d 0a 20 20 20  |ttrs: [pstr].   |
                        - 00000310  20 20 20 20 20 20 20 6f  72 64 65 72 3a 20 5b 5b  |       order: [[|
                        - 00000320  65 31 2c 20 65 32 2c 20  65 33 2c 20 65 34 5d 5d  |e1, e2, e3, e4]]|
                        - 00000330  0a 20 20 20 20 20 20 20  20 2d 20 61 74 74 72 73  |.        - attrs|
                        - 00000340  3a 20 5b 70 69 38 5d 0a  20 20 20 20 20 20 20 20  |: [pi8].        |
                        - 00000350  20 20 6f 72 64 65 72 3a  20 5b 5b 65 31 5d 2c 20  |  order: [[e1], |
                        - 00000360  5b 65 32 2c 20 65 33 2c  20 65 34 5d 5d 0a 20 20  |[e2, e3, e4]].  |
                        - 00000370  20 20 20 20 20 20 2d 20  61 74 74 72 73 3a 20 5b  |      - attrs: [|
                        - 00000380  70 69 38 2c 20 70 69 31  36 5d 0a 20 20 20 20 20  |pi8, pi16].     |
                        - 00000390  20 20 20 20 20 6f 72 64  65 72 3a 20 5b 5b 65 31  |     order: [[e1|
                        - 000003a0  5d 2c 20 5b 65 32 5d 2c  20 5b 65 33 5d 2c 20 5b  |], [e2], [e3], [|
                        - 000003b0  65 34 5d 5d 0a 20 20 20  20 20 20 20 20 2d 20 61  |e4]].        - a|
                        - 000003c0  74 74 72 73 3a 20 5b 70  69 31 36 5d 0a 20 20 20  |ttrs: [pi16].   |
                        - 000003d0  20 20 20 20 20 20 20 6f  72 64 65 72 3a 20 5b 5b  |       order: [[|
                        - 000003e0  65 32 5d 2c 20 5b 65 33  5d 2c 20 5b 65 31 2c 20  |e2], [e3], [e1, |
                        - 000003f0  65 34 5d 5d 0a                                    |e4]].|
                        + 000000a0  3a 0a 20 20 20 20 65 31  3a 20 7b 69 3a 20 22 22  |:.    e1: {i: ""|
                        + 000000b0  2c 20 69 3a 20 30 2c 20  69 3a 20 30 2c 20 69 3a  |, i: 0, i: 0, i:|
                        + 000000c0  20 30 2c 20 69 31 36 3a  20 31 2c 20 69 33 32 3a  | 0, i16: 1, i32:|
                        + 000000d0  20 30 2c 20 69 36 34 3a  20 30 2c 20 69 38 3a 20  | 0, i64: 0, i8: |
                        + 000000e0  31 2c 20 70 69 38 3a 20  31 2c 20 75 69 31 36 3a  |1, pi8: 1, ui16:|
                        + 000000f0  20 30 2c 20 75 69 33 32  3a 20 30 2c 20 75 69 36  | 0, ui32: 0, ui6|
                        + 00000100  34 3a 20 30 2c 20 75 69  38 3a 20 30 7d 0a 72 75  |4: 0, ui8: 0}.ru|
                        + 00000110  6c 65 73 3a 20 5b 5d 0a  71 75 65 72 69 65 73 3a  |les: [].queries:|
                        + 00000120  20 5b 5d 0a 63 6f 6d 70  61 72 69 73 6f 6e 73 3a  | [].comparisons:|
                        + 00000130  0a 20 20 20 20 2d 20 65  6e 74 69 74 69 65 73 3a  |.    - entities:|
                        + 00000140  20 5b 65 32 2c 20 65 33  2c 20 65 31 5d 0a 20 20  | [e2, e3, e1].  |
                        + 00000150  20 20 20 20 74 65 73 74  73 3a 0a 20 20 20 20 20  |    tests:.     |
                        + 00000160  20 20 20 2d 20 61 74 74  72 73 3a 20 5b 69 38 5d  |   - attrs: [i8]|
                        + 00000170  0a 20 20 20 20 20 20 20  20 20 20 6f 72 64 65 72  |.          order|
                        + 00000180  3a 20 5b 5b 65 31 5d 2c  20 5b 65 32 5d 2c 20 5b  |: [[e1], [e2], [|
                        + 00000190  65 33 5d 5d 0a 20 20 20  20 20 20 20 20 2d 20 61  |e3]].        - a|
                        + 000001a0  74 74 72 73 3a 20 5b 69  5d 0a 20 20 20 20 20 20  |ttrs: [i].      |
                        + 000001b0  20 20 20 20 6f 72 64 65  72 3a 20 5b 5b 65 31 2c  |    order: [[e1,|
                        + 000001c0  20 65 32 2c 20 65 33 5d  5d 0a 20 20 20 20 20 20  | e2, e3]].      |
                        + 000001d0  20 20 2d 20 61 74 74 72  73 3a 20 5b 70 69 38 5d  |  - attrs: [pi8]|
                        + 000001e0  0a 20 20 20 20 20 20 20  20 20 20 6f 72 64 65 72  |.          order|
                        + 000001f0  3a 20 5b 5b 65 31 5d 2c  20 5b 65 32 2c 20 65 33  |: [[e1], [e2, e3|
                        + 00000200  5d 5d 0a 20 20 20 20 20  20 20 20 2d 20 61 74 74  |]].        - att|
                        + 00000210  72 73 3a 20 5b 70 69 38  2c 20 70 69 31 36 5d 0a  |rs: [pi8, pi16].|
                        + 00000220  20 20 20 20 20 20 20 20  20 20 6f 72 64 65 72 3a  |          order:|
                        + 00000230  20 5b 5b 65 31 5d 2c 20  5b 65 32 5d 2c 20 5b 65  | [[e1], [e2], [e|
                        + 00000240  33 5d 5d 0a 20 20 20 20  20 20 20 20 2d 20 61 74  |3]].        - at|
                        + 00000250  74 72 73 3a 20 5b 70 69  31 36 5d 0a 20 20 20 20  |trs: [pi16].    |
                        + 00000260  20 20 20 20 20 20 6f 72  64 65 72 3a 20 5b 5b 65  |      order: [[e|
                        + 00000270  32 5d 2c 20 5b 65 33 5d  2c 20 5b 65 31 5d 5d 0a  |2], [e3], [e1]].|
                        + 00000280  20 20 20 20 2d 20 65 6e  74 69 74 69 65 73 3a 20  |    - entities: |
                        + 00000290  5b 65 32 2c 20 65 33 2c  20 65 31 2c 20 65 34 5d  |[e2, e3, e1, e4]|
                        + 000002a0  0a 20 20 20 20 20 20 74  65 73 74 73 3a 0a 20 20  |.      tests:.  |
                        + 000002b0  20 20 20 20 20 20 2d 20  61 74 74 72 73 3a 20 5b  |      - attrs: [|
                        + 000002c0  69 5d 0a 20 20 20 20 20  20 20 20 20 20 6f 72 64  |i].          ord|
                        + 000002d0  65 72 3a 20 5b 5b 65 31  2c 20 65 32 2c 20 65 33  |er: [[e1, e2, e3|
                        + 000002e0  2c 20 65 34 5d 5d 0a 20  20 20 20 20 20 20 20 2d  |, e4]].        -|
                        + 000002f0  20 61 74 74 72 73 3a 20  5b 69 5d 0a 20 20 20 20  | attrs: [i].    |
                        + 00000300  20 20 20 20 20 20 6f 72  64 65 72 3a 20 5b 5b 65  |      order: [[e|
                        + 00000310  31 2c 20 65 32 2c 20 65  33 2c 20 65 34 5d 5d 0a  |1, e2, e3, e4]].|
                        + 00000320  20 20 20 20 20 20 20 20  2d 20 61 74 74 72 73 3a  |        - attrs:|
                        + 00000330  20 5b 70 69 38 5d 0a 20  20 20 20 20 20 20 20 20  | [pi8].         |
                        + 00000340  20 6f 72 64 65 72 3a 20  5b 5b 65 31 5d 2c 20 5b  | order: [[e1], [|
                        + 00000350  65 32 2c 20 65 33 2c 20  65 34 5d 5d 0a 20 20 20  |e2, e3, e4]].   |
                        + 00000360  20 20 20 20 20 2d 20 61  74 74 72 73 3a 20 5b 70  |     - attrs: [p|
                        + 00000370  69 38 2c 20 70 69 31 36  5d 0a 20 20 20 20 20 20  |i8, pi16].      |
                        + 00000380  20 20 20 20 6f 72 64 65  72 3a 20 5b 5b 65 31 5d  |    order: [[e1]|
                        + 00000390  2c 20 5b 65 32 5d 2c 20  5b 65 33 5d 2c 20 5b 65  |, [e2], [e3], [e|
                        + 000003a0  34 5d 5d 0a 20 20 20 20  20 20 20 20 2d 20 61 74  |4]].        - at|
                        + 000003b0  74 72 73 3a 20 5b 70 69  31 36 5d 0a 20 20 20 20  |trs: [pi16].    |
                        + 000003c0  20 20 20 20 20 20 6f 72  64 65 72 3a 20 5b 5b 65  |      order: [[e|
                        + 000003d0  32 5d 2c 20 5b 65 33 5d  2c 20 5b 65 31 2c 20 65  |2], [e3], [e1, e|
                        + 000003e0  34 5d 5d 0a                                       |4]].|
                         }
          Test:         TestRel/comparetest/yaml
        --- FAIL: TestRel/comparetest/yaml (0.00s)
```

**Comment by rickystewart** [comment]
I think all tests are passing now.

**Review by healthy-pod — APPROVED** [review]

**Comment by knz** [comment]
I have no objection on the general approach on correctness grounds and I appreciate the simplification.
That said, there may be some performance impact. I'm raising this [here](https://cockroachlabs.slack.com/archives/C4X2J0RH6/p1683648218432529) and I hope that folk like @nvanbenschoten  will help us gain confidence this is doing the right thing.

**Review by knz — APPROVED** [review]
@tbg:
> I'd also take my chances with it. If the perf impact is significant, it'll show up in roachperf, and might get resolved by removing the offending callers of .String(). I hope we don't call String() often in the critical path.

works for me too.

**Comment by rickystewart** [comment]
I have nothing to back this up on, but generally speaking `switch` statements can be compiled down to jump tables and the compiled code will probably look similar. I think it's also better to express this stuff at a high-level and let the compiler do its job rather than hard-code the jump table ourselves.

SGTM to check it in and keep an eye out for performance regressions.

**Comment by rickystewart** [comment]
bors r=knz,healthy-pod

**Pull request merged**
