### PR TITLE
sql: prefer order-matching index if there is a limit

### LINKED ISSUE #5246: sql: prefer order-matching index when there is a limit
There is a tradeoff between selecting a non-covering index that has the desired ordering vs using a covering index that doesn't. However, when we have a limit the latter has the potential of reading much more data so we should prefer the order-matching index.

See https://github.com/cockroachdb/cockroach/issues/4925#issuecomment-196513251 for an example.

### PR DESCRIPTION
**Pull request by RaduBerinde**
In #4925, we observed ineffective planning for a query in the photos app. We
prefer to use the primary index and sort rather than use a non-covering index
which makes sense in general (non-covering indices require and expensive
indexJoin) but in this case we also had a limit. In such a case using the index
would require looking only at the first rows instead of getting all matching
rows and sorting.

In this change we tweak the index selection: if we have a reasonable limit, we
give a "boost" to all indices that match the ordering exactly. The boost exactly
offsets the non-covering index penalty.

In addition to the new tests, I also verified the photo app query in #4925 now
uses the index.

Fixes #5246.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5446)

### CODE REVIEW

**Comment by tamird** [comment]
commit message: s/and expensive/an expensive/

---

Reviewed 2 of 2 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[sql/select.go, line 313 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5446#-KDTz5LecQAmPNnY2eqU:-KDTz5LecQAmPNnY2eqV:1217602710) ([raw file](https://github.com/cockroachdb/cockroach/blob/16c80a2280940480afff45f2d39e45f6f7b1adb4/sql/select.go#L313)):*
this comment seems to have lost the code it once referred to.  (that happened in the first commit).

---

*[sql/select.go, line 308 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5446#-KDTxobhO3KEBfssvoPc:-KDTxobhO3KEBfssvoPd:19164728) ([raw file](https://github.com/cockroachdb/cockroach/blob/56b9366bdb95b5217abbf636734e9ee2a18c8e10/sql/select.go#L308)):*
expand this comment to explain why "if not grouping". I guess it's because grouping implies an unbounded number of rows need to be scanned.

---

*[sql/select.go, line 311 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5446#-KDTy6DUcwW179C-nn67:-KDTy6DUcwW179C-nn68:-2046746671) ([raw file](https://github.com/cockroachdb/cockroach/blob/56b9366bdb95b5217abbf636734e9ee2a18c8e10/sql/select.go#L311)):*
this doesn't seem like sufficient overflow protection - limitCount may not be equal to MaxInt64, but the sum of limitCount and limitOffset may still exceed it and wrap around. Perhaps `limitCount+limitOffset >=0 && limitCount+limitOffset <= 1000` instead?

---

*[sql/select.go, line 670 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5446#-KDTyevJYGl-lz5sMwKa:-KDTyevJYGl-lz5sMwKb:-1527812704) ([raw file](https://github.com/cockroachdb/cockroach/blob/56b9366bdb95b5217abbf636734e9ee2a18c8e10/sql/select.go#L670)):*
analyzeOrdering also needs this comment, yes?

---

*[sql/select.go, line 936 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5446#-KDTymbjoagNzc8qOij8:-KDTymbjoagNzc8qOij9:-1320746895) ([raw file](https://github.com/cockroachdb/cockroach/blob/56b9366bdb95b5217abbf636734e9ee2a18c8e10/sql/select.go#L936)):*
the commit message says this directly offsets some other cost - can you use a constant so that the relationship is obvious? also a comment right on this block would be good.

---

*[sql/testdata/select_non_covering_index, line 89 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5446#-KDTxawUWT08OHzqlkss:-KDTxawUWT08OHzqlkst:-1126889797) ([raw file](https://github.com/cockroachdb/cockroach/blob/56b9366bdb95b5217abbf636734e9ee2a18c8e10/sql/testdata/select_non_covering_index#L89)):*
expand this comment to explain that the primary index is still consulted because the order-matching index is non-covering.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5446#-:-KDTxMYMWAAei5244I0B:1239758149)*

**Comment by RaduBerinde** [comment]
TFTR! Updated.

---

Review status: 3 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[sql/testdata/select_non_covering_index, line 89 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5446#-KDTxawUWT08OHzqlkss:-KDU3jGfpVpmLIHg-mcy:-282323082) ([raw file](https://github.com/cockroachdb/cockroach/blob/56b9366bdb95b5217abbf636734e9ee2a18c8e10/sql/testdata/select_non_covering_index#L89)):*
This is the theme of the entire file (`select_non_covering_index`)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5446#-:-KDU3tCRHyMtPFcxXOtF:-1512379193)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/limit.go, line 69 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5446#-KDU55UW5QjLy-ozBFaw:-KDU55UXEHjMBf2Nq68x:1614713111) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ece68131d035e23d9ed59cccdcdfda52ef54372/sql/limit.go#L69)):*
what's this about? is there a test that induces this case?

---

*[sql/testdata/select_non_covering_index, line 89 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5446#-KDTxawUWT08OHzqlkss:-KDU5hLIZrwx3Lo8EzGp:1593181440) ([raw file](https://github.com/cockroachdb/cockroach/blob/56b9366bdb95b5217abbf636734e9ee2a18c8e10/sql/testdata/select_non_covering_index#L89)):*
Ah, and the other test cases all touch the primary as well. Fair enough.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5446)*

**Comment by RaduBerinde** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/limit.go, line 69 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5446#-KDU55UW5QjLy-ozBFaw:-KDU6n7EFJ55vtetpi1J:1840047858) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ece68131d035e23d9ed59cccdcdfda52ef54372/sql/limit.go#L69)):*
Added tests.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5446)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5446#-:-KDUKjqrjR-QIHqc5c8Q:1417088721)*

**Pull request merged**
