### PR TITLE
sql,ccl: new tenant info field ServiceMode

### PR DESCRIPTION
**Pull request by knz**
Previous PRs:
- [x] sql: rename TenantInfo.State to DataState, "ACTIVE" to "READY" #95574 

Summary of changes:
- the new TenantInfo.ServiceMode field indicates how to run servers.
- new syntax: `ALTER TENANT ... START SERVICE EXTERNAL/SHARED`,
  `ALTER TENANT ... STOP SERVICE`.
- tenants created via `create_tenant(<id>)`
  (via CC serverless control plane) start in service mode EXTERNAL.
- other tenants start in service mode NONE.
- need ALTER TENANT STOP SERVICE before dropping a tenant.
  - except in the case of `crdb_internal.destroy_tenant`
    for compat with CC serverless control plane.

This commit does not contain the logic to start/stop
servers yet.

Release note: None
Epic: CRDB-21836

### CODE REVIEW

**Comment by dt** [comment]
Part of me wishes we stored things like this in their own columns of the tenant table instead of one giant opaque proto since we are a sql database after all e.g. for easier "WHERE service_mode = x` or whatever, but I suppose pb_to_json works too.

**Comment by knz** [comment]
I can make it a virtual computed column like i did for name.

**Comment by knz** [comment]
TODO for self: only allow service mode SHARED if the name is non-empty.

**Comment by knz** [comment]
Discussed with @ajwerner @dt : I will modify this PR to reify the data state, service mode and name into proper SQL columns.

**Comment by knz** [comment]
replaced by #95691.

**Pull request closed without merging**
