### PR TITLE
explain: include plan of cascades in the output

### LINKED ISSUE #69124: sql: show EXPLAIN for FK cascades or checks in EXPLAIN ANALYZE
Currently the plan for FK cascades or checks is not visible in EXPLAIN ANALYZE or in the bundle for EXPLAIN ANALYZE (DEBUG). This makes any issues related to cascades very hard to debug.

We would have to modify `PlanAndRunCascadesAndChecks` to build against an `explain.Factory`.

Jira issue: CRDB-9450

Epic CRDB-14510

### LINKED ISSUE #97343: sql: show index selection under fk-cascade in EXPLAIN output
We don't currently include any information about the indexes that will be used to execute foreign key cascade actions. This is an observability blind spot.

For example, consider the following `DELETE` statement. It's not possible to determine from EXPLAIN how expensive the fk cascades on t2 and t3 will be. Do they require full table scans? Or are they well-constrained?

```sql
explain delete from t1 where id = '123';
                                                      info
----------------------------------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • root
  │
  ├── • delete
  │   │ from: t1
  │   │
  │   └── • buffer
  │       │ label: buffer 1
  │       │
  │       └── • render
  │           │
  │           └── • scan
  │                 estimated row count: 1 (100% of the table; stats collected 14 minutes ago)
  │                 table: t1@t1_pkey
  │                 spans: [/'123' - /'123']
  │
  ├── • fk-cascade
  │     fk: t2_t1_id_fkey
  │     input: buffer 1
  │
  └── • fk-cascade
        fk: t3_t1_id_fkey
        input: buffer 1
```

This can play out in (at least) two negative ways:
- the fk cascades unexpectedly require large, expensive scans on the child tables that slow down the query
- the fk cascades unexpectedly create read-write contention on the child tables that cause txn retries and prevent the DELETE from serializing with unrelated writes to the child table

Jira issue: CRDB-24648

Epic CRDB-34181

gz#18371

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit extends the EXPLAIN output to also include the plan for each cascade. Previously, we would only show the name of the FK constraint that triggered the cascade as well as the input buffer's label (when applicable). Now, the explain factory is adjusted to provide the cascade plan to the output builder. Depending on the context that plan can be captured in two ways:
- in EXPLAIN ANALYZE context `PlanFn` function is augmented so that the actual execution plan is captured at the execution time. This allows us to easily make execution statistics work.
- in "vanilla" EXPLAIN context the cascade plan is generated on request.

Note that this commit makes three existing functions recursive, and each has a separate context to keep in mind.
- `annotateExplain` is used to annotate plans that have already been created during the execution phase, so we don't need to create any new plans. Here we cache the plans when they are created by `PlanFn`.
- `emitInternal` now powers `explain.Emit`. Here is where we now create plans for the "vanilla" EXPLAIN and care had to be taken to prevent infinite recursion in the case when foreign keys form a cycle (either due to a self-referencing cascade or a FK loop between multiple tables) - the infinite recursion is prevented by tracking a set of table IDs that have already been visited. The created plans are cached for the next call to `GetExplainPlan`.
- `closeExplainPlan` closes the tree of plans created for "vanilla" EXPLAIN. Here we only need to close plans that have already been created, so we don't need to concern ourselves with base case for recursion - it was already handled above.

Fixes: #69124.
Fixes: #97343.

Release note (sql change): EXPLAIN output now contains detailed information about the plans for CASCADE actions.

### CODE REVIEW

**Comment by yuzefovich** [comment]
Ah, this doesn't work when we have multi-table loops :/ I guess we'll need to replace `selfReferencing` boolean with a set of `StableID`s for the tables that were on the "path" for a particular cascade. Any other ideas?

**Comment by DrewKimball** [comment]
>Ah, this doesn't work when we have multi-table loops :/ I guess we'll need to replace selfReferencing boolean with a set of StableIDs for the tables that were on the "path" for a particular cascade. Any other ideas?

Yeah, I'd just try a map. We do something similar for formatting recursive routines in `ExprFmtCtx`.

**Comment by yuzefovich** [comment]
Thanks, I'll work on that later today - please hold off on reviewing for now, I'll ping when it's RFAL.

**Comment by yuzefovich** [comment]
Ok, this is RFAL @DrewKimball @mgartner

**Review by DrewKimball — COMMENTED** [review]
I notice that all implementations of `CascadeBuilder` store the mutated table and FK ordinal. Could we augment that interface to have ways to retrieve those? Then, we could directly store the table's stable ID and the FK ordinal on `exec.Cascade`. Would that work?

> Reviewed 2 of 2 files at r1, 37 of 37 files at r4, 6 of 6 files at r5, 5 of 34 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117093#-:-NnjZQHY-ikD8Gt9aB6c:bjh7tzc)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

**Review by yuzefovich — COMMENTED** [review]
That's a good point - I think we can just store the FK constraint explicitly in the metadata struct, done. I also extracted an extra plumbing commit to make the review of the main change easier.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117093#-:-NnjxRXR1fWXv6RciMZJ:b-idzdqz)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

**Comment by yuzefovich** [comment]
Also, thoughts about backporting this to 23.2.1? It seems like a pretty safe change with decent benefit from backporting.

**Review by DrewKimball — COMMENTED** [review]
> Reviewed 37 of 37 files at r9, 37 of 37 files at r10, 9 of 9 files at r11, 28 of 28 files at r12, 3 of 11 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117093)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[`pkg/sql/explain_plan.go` line 257 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/117093#-Nnl2rCuCfO4gZMFGBbP:-Nnl2rCuCfO4gZMFGBbQ:b-cc0zb) ([raw file](https://github.com/cockroachdb/cockroach/blob/562fb77cb6cb7305396318582a0b6448851568f2/pkg/sql/explain_plan.go#L257)):*
> ```Go
> // plan. Can be nil if the plan doesn't have any cascades.
> func closeExplainPlan(
> 	ctx context.Context, ep *explain.Plan, visitedTablesByCascades *intsets.Fast,
> ```

Is it enough to store the table IDs only? Could this miss FKs from the same table that reference different columns? That might be fine for the explain code paths, but seems problematic for the close path.
___
*[`pkg/sql/explain_plan.go` line 264 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/117093#-Nnl3LKr0pqNXmXy3Kh4:-NnkmObVB1Mg8w7ll4b6:bmnogve) ([raw file](https://github.com/cockroachdb/cockroach/blob/562fb77cb6cb7305396318582a0b6448851568f2/pkg/sql/explain_plan.go#L264)):*
> ```Go
> 	}
> 	for _, cascade := range ep.Cascades {
> 		if cp, err := cascade.GetExplainPlan(ctx); err == nil {
> ```

I have some ideas to further simplify things, but I'm happy to finish reviewing the current version if you think it's best to keep this approach.

`GetExplainPlan` creates a new plan if there wasn't one before, right? Could we add a way to get the cached explain plan if it exists, and then just check if the plan is nil? I think that would let us avoid checking for recursion here - we'd only go as deep as the already-open plans go. Most of the refactoring in this file would be unnecessary.

Maybe we could do the same thing for the explain annotation code as well - just follow the path of whatever plans were created during execution, and emit stats/output for those. If necessary, we could add a max depth to truncate if we're worried about very large cascade series.

If we did this for both the closing and explain annotation code paths, only the vanilla EXPLAIN path would need to worry about recursion.
___
*[`pkg/sql/opt/exec/explain/explain_factory.go` line 182 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/117093#-Nnl5SWeEa2lrYrynMgO:-Nnl5SWeEa2lrYrynMgP:b4fec6p) ([raw file](https://github.com/cockroachdb/cockroach/blob/562fb77cb6cb7305396318582a0b6448851568f2/pkg/sql/opt/exec/explain/explain_factory.go#L182)):*
> ```Go
> 		// during the execution or when GetExplainPlan is invoked during the
> 		// explain output population.
> 		var cascadePlan exec.Plan
> ```

How would you feel about instead wrapping the `exec.Cascade` structs used in `explain.Plan` with a helper struct that caches the plan when `PlanFn` is called? Similar to what is done for `planComponents`.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117093)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/explain_plan.go` line 257 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/117093#-Nnl2rCuCfO4gZMFGBbP:-NnodXgrCrAx85BPE7Jj:b-i687ti) ([raw file](https://github.com/cockroachdb/cockroach/blob/562fb77cb6cb7305396318582a0b6448851568f2/pkg/sql/explain_plan.go#L257)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Is it enough to store the table IDs only? Could this miss FKs from the same table that reference different columns? That might be fine for the explain code paths, but seems problematic for the close path.
</blockquote></details>

I think it should be enough - the important thing is that we use the same recursion conditions in all places, so if we created a plan for some cascade via `GetExplainPlan` call in `emitInternal` or `annotateExplainInternal` functions, then we will close that same plan in `closeExplainPlan` function too since all 3 functions effectively perform the same traversal. If we missed some FKs from the same table, then we didn't create the plan for it in any of these functions, so there is nothing to close. Does it sound reasonable?
___
*[`pkg/sql/explain_plan.go` line 264 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/117093#-Nnl3LKr0pqNXmXy3Kh4:-Nno_H-7Cv46WnN6S4Mq:bu1n2xo) ([raw file](https://github.com/cockroachdb/cockroach/blob/562fb77cb6cb7305396318582a0b6448851568f2/pkg/sql/explain_plan.go#L264)):*
> `GetExplainPlan` creates a new plan if there wasn't one before, right? Could we add a way to get the cached explain plan if it exists, and then just check if the plan is nil?

`GetExplainPlan` will always reuse the cached explain plan if it's available. This is possible in two scenarios:
- if we're in EXPLAIN ANALYZE context, then `PlanFn` is called to create the plan during the query execution, and we augmented `PlanFn` in `explain_factory.go` to capture the explain plan too (stored in `cascadePlan` local variable). In this case, `GetExplainPlan` will not create a new plan and will always return the one that was used during the query execution. This was necessary to make execution stats work (otherwise we'd annotate different nodes with exec stats than if we were to create a fresh plan on `GetExplainPlan` call).
- if `PlanFn` hasn't been called before the first call to `GetExplainPlan`, then only on the first call do we create a plan and store it in the same local `cascadePlan` variable. If `GetExplainPlan` is called again (which is only possible in `closeExplainPlan` code path), then the cached explain plan is returned. The fact that we use exactly the same recursion structure in all 3 recursive functions guarantees that we will close all plan that have been created.

> I think that would let us avoid checking for recursion here - we'd only go as deep as the already-open plans go.

That was my initial thinking / hopes as well, but creating the plan at most once for each cascade is insufficient to prevent infinite recursion. The thing is that if `cascade2` is triggered by `cascade1`, then the plans for both of these are pretty much independent, i.e. `PlanFn` / `GetExplainPlan` functions for both return totally separate plans, and the fact that we cached the plan for `cascade1` doesn't give us any additional information about the plan for `cascade2`.

The way to think about it is the following: it's not `PlanFn` / `GetExplainPlan` functions that are recursive and lead to infinite recursion; instead, it's three functions `closeExplainPlan`, `annotateExplainInternal`, and `emitInternal` that are recursive. On each level of recursion we call new / independent `GetExplainPlan` which creates a new plan, which itself can have more cascades, which results in further recursion. During the execution we have similar mechanics at play, but there the stopping condition for the recursion is when the "input buffer" doesn't have any more rows (i.e. `numBufferedRows = 0`). However, here in the explain recursion we don't have that information, so we need to find some other condition to stop the recursion - not recursing into the table if it has already been visited on the current recursion stack seems reasonable, regardless of whether we visited this particular table due to the same FK constraint as the one that caused us to recurse from the last level. (We could make this tracking more precise (like track "Foreign Key Constraint" IDs that have been used on the current recursive path), but that seems like overkill. Overall, this loop-like FK structure seems like an edge case and it's important only to not get stack / crash, but otherwise possibly-truncated output (because we stopped recursing too soon) seems reasonable.)

> Maybe we could do the same thing for the explain annotation code as well - just follow the path of whatever plans were created during execution, and emit stats/output for those. If necessary, we could add a max depth to truncate if we're worried about very large cascade series.

> If we did this for both the closing and explain annotation code paths, only the vanilla EXPLAIN path would need to worry about recursion.

I'm not sure I follow your suggestions here, but does my response to previous parts change anything?
___
*[`pkg/sql/opt/exec/explain/explain_factory.go` line 182 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/117093#-Nnl5SWeEa2lrYrynMgO:-NnogWuy9jmAw5psxRNg:b68oh53) ([raw file](https://github.com/cockroachdb/cockroach/blob/562fb77cb6cb7305396318582a0b6448851568f2/pkg/sql/opt/exec/explain/explain_factory.go#L182)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

How would you feel about instead wrapping the `exec.Cascade` structs used in `explain.Plan` with a helper struct that caches the plan when `PlanFn` is called? Similar to what is done for `planComponents`.
</blockquote></details>

Hm, I think I see your idea but am struggling to implement it. I think the difficulty I'm having is that unlike for all other parts of the plan (main query, subqueries, checks) - which are fully constructed _before_ `ConstructPlan` is called - the plans for cascades aren't created yet, so we don't have the plans to wrap / unwrap yet. The plans will only be created on `PlanFn` invocations; thus, the natural to me approach is to wrap the `PlanFn` function itself which is what is currently done. Do you mind sharing the code diff that you have in mind?

**Comment by DrewKimball** [comment]
>>I think that would let us avoid checking for recursion here - we'd only go as deep as the already-open plans go.

>That was my initial thinking / hopes as well, but creating the plan at most once for each cascade is insufficient to prevent infinite recursion. The thing is that if cascade2 is triggered by cascade1, then the plans for both of these are pretty much independent, i.e. PlanFn / GetExplainPlan functions for both return totally separate plans, and the fact that we cached the plan for cascade1 doesn't give us any additional information about the plan for cascade2.

My thinking is, we only have to worry about recursion if we're actively constructing new plans, as `GetExplainPlan` does. In the `emitPlan` code path, this is necessary because there are not existing plans. But for `closeExplainPlan` and `annotateExplainInternal`, the plans should have been constructed and cached during execution already (is that right?). So, why are these latter two code paths building new plans when they could iterate through the actual plans left behind by execution? We could rely on execution to build the plans without infinite recursion for those cases. If we reach a cascade during that traversal with no cached plan, we shouldn't build a new one, we should just stop traversing.

**Review by yuzefovich — COMMENTED** [review]
Yes, you're right, very good points. I refactored the code according to this suggestion which makes it more intuitive. Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117093#-:-NnqCaF06UMmDLgZ_4P4:bl6ilhl)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

**Review by DrewKimball — COMMENTED** [review]
Thanks for the refactoring, and sorry for all the back-and-forth. I've got one last set of suggestions, but if you feel like they aren't feasible, or I overlooked something, I think the current state looks good - I could open up a PR afterward if I want to obsess over it some more.

> Reviewed 1 of 7 files at r17, 2 of 28 files at r18.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117093#-:-NnsLEvF6PupcNuPaLtv:b-7unp9v)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[`pkg/sql/instrumentation.go` line 1031 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/117093#-NnsCIE3AyVhydh7KhOu:-NnsCIE3AyVhydh7KhOv:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/52d7c3ebecfd3f0b7c72f0027b6bc3c19ba2bb60/pkg/sql/instrumentation.go#L1031)):*
> ```Go
> 		// the query.
> 		const createPlanIfMissing = false
> 		if cp, _ := cascade.GetExplainPlan(ctx, createPlanIfMissing); cp != nil {
> ```

Nice!
___
*[`pkg/sql/opt/exec/explain/emit.go` line 133 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/117093#-NnsF_LCDCBxbhwhsfqQ:-NnsCZLHC_N7A_wp2gst:b-tmq25t) ([raw file](https://github.com/cockroachdb/cockroach/blob/52d7c3ebecfd3f0b7c72f0027b6bc3c19ba2bb60/pkg/sql/opt/exec/explain/emit.go#L133)):*
> ```Go
> 		// able to include them into the EXPLAIN output.
> 		const createPlanIfMissing = true
> 		if cascadePlan, err := cascade.GetExplainPlan(ctx, createPlanIfMissing); err != nil {
> ```

Ok, I think I have another set of ideas to simplify things further:
1. Revert the changes in `explain_plan.go` and `explain_factory.go`.
2. Remove `GetExplainPlan`, add a method to get cached execution plan from [here](https://github.com/cockroachdb/cockroach/blob/d9c7307281096f1f1ac8bfe2613d253a2aa35fd6/pkg/sql/plan.go#L433-L434), if it exists.
3. `annotateExplain` can expect the execution plan to exist, so just use the new method from (2).
4. This code path (emit) will do the following in order:
     * If a cached execution plan exists, emit and then continue. Responsibility for closing the plan belongs 
        to execution logic, not explain logic.
     * Else if we've visited this table before, just print the buffer and don't recurse.
     * Else, call `PlanFn` directly to build a new plan, and emit. Since we created the plan here, we also close it here.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117093)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/opt/exec/explain/emit.go` line 133 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/117093#-NnsF_LCDCBxbhwhsfqQ:-NntelHk-602dZ0V1jQ1:bfgfqyi) ([raw file](https://github.com/cockroachdb/cockroach/blob/52d7c3ebecfd3f0b7c72f0027b6bc3c19ba2bb60/pkg/sql/opt/exec/explain/emit.go#L133)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Ok, I think I have another set of ideas to simplify things further:
1. Revert the changes in `explain_plan.go` and `explain_factory.go`.
2. Remove `GetExplainPlan`, add a method to get cached execution plan from [here](https://github.com/cockroachdb/cockroach/blob/d9c7307281096f1f1ac8bfe2613d253a2aa35fd6/pkg/sql/plan.go#L433-L434), if it exists.
3. `annotateExplain` can expect the execution plan to exist, so just use the new method from (2).
4. This code path (emit) will do the following in order:
     * If a cached execution plan exists, emit and then continue. Responsibility for closing the plan belongs 
        to execution logic, not explain logic.
     * Else if we've visited this table before, just print the buffer and don't recurse.
     * Else, call `PlanFn` directly to build a new plan, and emit. Since we created the plan here, we also close it here.
</blockquote></details>

Hm, I feel like this strategy shouldn't work. In particular, it seems wrong to me that we wouldn't make any changes to `explain.Factory` - namely, `PlanFn` constructor is created by the main `exec.Factory`, and it doesn't know anything about the explain. With the current state of this PR we inject the explain factory into `PlanFn` function, so the plan created for the cascade will get the same treatment as the main plan. Without this injection we should get annotated main plan but "vanilla" cascade plan, so the EXPLAIN output will differ between the two. WDYT?

Also, if we did call `PlanFn` in `explain.Emit`, we would need to plumb all the arguments necessary for `PlanFn` into `explain.Emit` too, which also seems wrong.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Thanks for all the refactoring!

> Reviewed 1 of 7 files at r17, 11 of 28 files at r18, 5 of 10 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117093#-:-NntpBGPBe8guuXK_9sg:b-m9d9w2)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[`pkg/sql/opt/exec/explain/emit.go` line 133 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/117093#-NnsF_LCDCBxbhwhsfqQ:-Nntn2KM8HXXeG6syqVg:bo4aarh) ([raw file](https://github.com/cockroachdb/cockroach/blob/52d7c3ebecfd3f0b7c72f0027b6bc3c19ba2bb60/pkg/sql/opt/exec/explain/emit.go#L133)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Hm, I feel like this strategy shouldn't work. In particular, it seems wrong to me that we wouldn't make any changes to `explain.Factory` - namely, `PlanFn` constructor is created by the main `exec.Factory`, and it doesn't know anything about the explain. With the current state of this PR we inject the explain factory into `PlanFn` function, so the plan created for the cascade will get the same treatment as the main plan. Without this injection we should get annotated main plan but "vanilla" cascade plan, so the EXPLAIN output will differ between the two. WDYT?

Also, if we did call `PlanFn` in `explain.Emit`, we would need to plumb all the arguments necessary for `PlanFn` into `explain.Emit` too, which also seems wrong.
</blockquote></details>

That's a good point. Well, I think I'm pretty happy with the current state, anyway, so it's probably not worth worrying about further.
___
*[`pkg/sql/opt/exec/explain/explain_factory.go` line 203 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/117093#-Nnto-Az87ZRMzJN6PLC:-Nnto-Az87ZRMzJN6PLD:b-jb99km) ([raw file](https://github.com/cockroachdb/cockroach/blob/52d7c3ebecfd3f0b7c72f0027b6bc3c19ba2bb60/pkg/sql/opt/exec/explain/explain_factory.go#L203)):*
> ```Go
> 				return nil, errors.AssertionFailedf("expected captured buffer %v to wrap the provided bufferRef %v", buffer, bufferRef)
> 			}
> 			f.wrappedFactory = execFactory
> ```

[nit] It seems a little sketchy to mutate `f` and also not use the supplied evalCtx and semaCtx. (It's probably fine, but seems brittle for future code changes). Could we just build a new explain factory here since it's small?

**Review by yuzefovich — COMMENTED** [review]
Thanks for all the suggestions! I think it ended up being pretty clean in the end. I also think it'll be beneficial to backport it to 23.2.1, so I added such a label, and we can discuss whether the backport should be merged on the backport PR.

TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117093#-:-Nnw4-IdCWBAjflyUgz5:b-srnjvl)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/opt/exec/explain/explain_factory.go` line 203 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/117093#-Nnto-Az87ZRMzJN6PLC:-Nnw3PR8D3INr4Rc71Sx:b-jshy3v) ([raw file](https://github.com/cockroachdb/cockroach/blob/52d7c3ebecfd3f0b7c72f0027b6bc3c19ba2bb60/pkg/sql/opt/exec/explain/explain_factory.go#L203)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] It seems a little sketchy to mutate `f` and also not use the supplied evalCtx and semaCtx. (It's probably fine, but seems brittle for future code changes). Could we just build a new explain factory here since it's small?
</blockquote></details>

Yes, good point, done.

**Pull request merged**
