### PR TITLE
sql: properly report events for ownership changes

### LINKED ISSUE #57958: sql: event logging missing for REASSIGN OWNER ... TO
All the ownership changes performed as an effect of a REASSIGN OWNER statement are currently not in the (notable) event log.

This is needed for a full security log.

cc @thtruo 
cc @rafiss for triage. I'm going to _try_ fixing this but I'm really not confident. Would appreciate some help.

### PR DESCRIPTION
**Pull request by knz**
Fixes #57958. 

Release note (sql change): Both ALTER TABLE OWNER and REASSIGN OWNED
BY now report structured notable events about the ownership
changes. Note that REASSIGN OWNED BY currently also reports an
`alter_table_owner` for views and sequences that were implicitly
reassigned, even though CockroachDB does not yet support the ALTER
VIEW OWNER / ALTER SEQUENCE OWNER statements yet.

### CODE REVIEW

**Comment by angelapwen** [comment]
:lgtm_strong: thanks Raphael!

**Review by angelapwen — APPROVED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57969)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by knz** [comment]
thanks!

bors r=angelapwen

**Comment by knz** [comment]
bors r=angelapwen

**Comment by knz** [comment]
bors r=angelapwen

**Comment by knz** [comment]
i got a merge skew. Retrying

bors r=angelapwen

**Comment by knz** [comment]
that was an infra flake

bors r=angelapwen

**Pull request merged**
