### PR TITLE
opt: add fittin.gs external stats and example queries

### PR DESCRIPTION
**Pull request by madelynnblue**
Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Very cool - thanks for adding!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51244#-:-MBu95QBCLjxlfQQErPU:b86c0wx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mjibson and @RaduBerinde)

___
*[pkg/sql/opt/xform/testdata/external/fittings, line 8750 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51244#-MBu8xfT9OZmug7AJqez:-MBu8xfT9OZmug7AJqf-:b-gta86u) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4767885387b7b996797d3b11fc3feead0d2145b/pkg/sql/opt/xform/testdata/external/fittings#L8750)):*
> ```
> opt format=show-stats
> SELECT
> 	killmail, ship, cost, hi AS hiraw, med AS medraw, low AS lowraw
> ```

[nit] we avoid tabs in these files

**Review by rytaft — APPROVED** [review]
:lgtm: cool!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51244#-:-MBuPqdYERWRTDzeRtEh:b-84whef)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/sql/opt/xform/testdata/external/fittings, line 1269 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51244#-MBuOuiS1RF1fRYQ7qM6:-MBuOuiS1RF1fRYQ7qM7:bekavbu) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4767885387b7b996797d3b11fc3feead0d2145b/pkg/sql/opt/xform/testdata/external/fittings#L1269)):*
> ```
>   },
>   {
>     "columns": ["solarsystem"],
> ```

to reduce the size of this file, probably worth eliminating duplicate entries for the same column.

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51244)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/opt/xform/testdata/external/fittings, line 1269 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51244#-MBuOuiS1RF1fRYQ7qM6:-MC7zTQK4sNw8XMqQRpZ:boj1qgt) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4767885387b7b996797d3b11fc3feead0d2145b/pkg/sql/opt/xform/testdata/external/fittings#L1269)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

to reduce the size of this file, probably worth eliminating duplicate entries for the same column.
</blockquote></details>

Good catch. Done.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51244#-:-MC875UM7FyAcktH5jth:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
