### PR TITLE
kv: redirect follower reads to leaseholder on contention

### LINKED ISSUE #57686: kv: improve handling of write-read contention on follower reads
Needed for non-blocking transactions: #52745. Also needed for follower reads in general.

Currently, a follower read that hits write-read contention immediately pushes the contending writer. This is because it doesn't have an enabled lockTable in which it can wait for the lock to be released. This is suboptimal in a few ways. First, it means that the push may need to perform a full WAN hop, even if the lock's resolution is imminent. Second, it means that even once the writer is committed/aborted and the lock is resolved on the leaseholder, there's no guarantee that it will be resolved on the follower when the reader returns.

Either of the following options would be an improvement over the current situation:
1. redirect to the leaseholder if a follower read hits contention. In some systems, follower reads aren't even allowed if they would conflict with a lock (i.e. the closed timestamp waits on locks), so this is still a better situation.
2. wait in the lockTable on the follower, just as we do on the leaseholder. This would require listening to lock state transitions on followers, which seems tricky, but may be more realistically possible with a persistent lock table.

### PR DESCRIPTION
**Pull request by nvb**
Fixes #57686.

This commit adjusts the handling of follower reads to redirect to the leaseholder immediately if a conflicting intent is observed while reading. This replaces the previous behavior of attempting to resolve the intents from the follower using an inefficient method (i.e. without batching and with multiple follower<->leaseholder hops) and then re-evaluating after the resolution had completed.

In general, waiting for conflicting intents on the leaseholder instead of on a follower is preferable because:
- the leaseholder is notified of and reactive to lock-table state transitions.
- the leaseholder is able to more efficiently resolve intents, if necessary, without the risk of multiple follower<->leaseholder round-trips compounding. If the follower was to attempt to resolve multiple intents during a follower read then the `PushTxn` and `ResolveIntent` requests would quickly be more expensive (in terms of latency) than simply redirecting the entire read request to the leaseholder and letting the leaseholder coordinate the intent resolution.
- after the leaseholder has received a response from a `ResolveIntent` request, it has a guarantee that the intent resolution has been applied locally and that no future read will observe the intent. This is not true on follower replicas. Due to the asynchronous nature of Raft, both due to quorum voting and due to async commit acknowledgement from leaders to followers, it is possible for a `ResolveIntent` request to complete and then for a future read on a follower to observe the pre-resolution state of the intent. This effect is transient and will eventually disappear once the follower catches up on its Raft log, but it creates an opportunity for momentary thrashing if a follower read was to resolve an intent and then immediately attempt to read again.

This behavior of redirecting follower read attempts to the leaseholder replica if they encounter conflicting intents on a follower means that follower read eligibility is a function of the "resolved timestamp" over a read's key span, and not just the "closed timestamp" over its key span. Architecturally, this is consistent with Google Spanner, who maintains a concept of "safe time", "paxos safe time", "transaction manager safe time". "safe time" is analogous to the "resolved timestamp" in CockroachDB and "paxos safe time" is analogous to the "closed timestamp" in CockroachDB. In Spanner, it is the "safe time" of a replica that determines follower read eligibility.

There are some downsides to this change which I think are interesting to point out, but I don't think are meaningfully concerning:
1. we don't detect the difference between the resolved timestamp and the closed timestamp until after we have begun evaluating the follower read and scanning MVCC data. This lazy detection of follower read eligibility can lead to wasted work. In the future, we may consider making this detection eager once we address #69717.
2. redirecting follower reads to leaseholders can lead to large response payloads being shipped over wide-area network links. So far, this PR has compared the latency of multiple WAN hops for intent resolution to a single WAN hop for read redirection, but that doesn't recognize the potential asymmetry in cost, at least at the extreme, between control-plane requests like `PushTxn` and `ResolveIntent` and data-plane requests like `Scan` and `Get`. In the future, I'd like to recognize this asymmetry explore ideas around never redirecting the data-plane portion of follower reads to leaseholders and instead only ever sending control-plane requests to proactively close time and relay log positions back to the followers. This is similar to what Spanner does, see https://www.cockroachlabs.com/blog/follower-reads-stale-data/#comparing-cockroachdb-with-spanner. For now, though, I don't think redirecting marginally more often is concerning.

Release note (performance improvement): follower reads that encounter many abandoned intents are now able to efficiently resolve those intents. This resolves an asymmetry where follower reads were previously less efficient at resolving abandoned intents than regular reads evaluated on a leaseholder.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
This deserves an experiment to validate the expected improvement to intent cleanup.

**Comment by nvanbenschoten** [comment]
I ran a series of experiments to demonstrate the impact this has on follower reads that hit abandoned intents. The results were consistent with expectations.

To generate abandoned intents, I ran a version of cockroach with and without this commit and with the following patch applied:
```
--- a/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go
+++ b/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go
@@ -283,7 +283,7 @@ func (h *txnHeartbeater) closeLocked() {

 // startHeartbeatLoopLocked starts a heartbeat loop in a different goroutine.
 func (h *txnHeartbeater) startHeartbeatLoopLocked(ctx context.Context) {
-       if h.loopInterval < 0 {
+       if h.loopInterval < 0 || true {
                log.Infof(ctx, "coordinator heartbeat loop disabled")
                return
        }
```

Without a transaction heartbeat, the intents of a long-running transaction would become eligible for cleanup after 5 seconds.

I then ran the following sequence of queries:
```sql
./cockroach demo --empty --nodes=9 --global

--- in terminal 1: setup db, setup table, abandon 1k intents
alter database defaultdb set primary region "us-east1";
alter database defaultdb add region "us-west1";
alter database defaultdb add region "europe-west1";
alter database defaultdb survive zone|region failure;

create table foo (v int primary key);
show ranges from table foo; -- wait for upreplication
alter table foo split at (select 100*generate_series(1, 10));

begin;
insert into foo select generate_series(1, 1000);
select pg_sleep(6); -- wait for txn abort

--- in terminal 2: cleanup intents with read
select gateway_region(); -- verify region
select * from foo as of system time follower_read_timestamp();
```

This spins up a multi-region cluster with simulated latencies, sets up a multi-region database, creates a table, splits it 10 ways, inserts 1000 intents into the table, then lets them expire. It then runs a follower read over the entire table, which is forced to clean up all intents.

For each version of CRDB, I ran the test 3 times, altering the location of the follower read in each. First, I ran it in `us-east1`, which is the same region as the leaseholders, then in `us-west1`, which is 69ms away from the leaseholder, then in `europe-west1`, which is 70ms away from the leaseholder. I also ran the entire suite twice, once with `zone` survivability and once with `region` survivability. The timing of the follower read was the key metric for the test. Here are the results:

|           | us-east1 / zone | us-east1 / region | us-west1 / zone | us-west1 / region | europe-west1 / zone | europe-west1 / region |
| --------- | --------------- | ----------------- | --------------- | ----------------- | ------------------- | --------------------- |
| Before PR | 530ms           | 1.129s            | 44.727s         | 89.393s           | 44.672s             | 86.528s               |
| After PR  | 530ms           | 1.129s            | 810ms           | 1.592s            | 825ms               | 1.591s                |
| **Δ**     | **0%**          | **0%**            | **-98.2%**      | **-98.2%**        | **-98.2%**          | **-98.2%**            |

The first thing to notice is that all four configs that run the follower read in the non-primary region sped up by exactly **-98.2%**. The reliability of this number is actually pretty wild. So the change is clearly working.

The next thing to notice is that the zone survivability configs drop from just under 1000x their region<->leaseholder RTT to a few 100ms slower than the cleanup in the same region. The 1000x multiplier before this change checks out, because of the intent-at-a-time cleanup noted above. The number isn't exactly 1000x because there is some degree of parallelism between ranges thanks to DistSQL, but it's close enough to demonstrate the point.

The other thing to notice is the impact that survivability has on these numbers. In either case, region survivability leads to more expensive cleanup than zone survivability because consensus during intent resolution is more expensive. But the impact that this has on end-to-end latency differs from before and after this patch. Before, we pay the additional consensus latency once-per-intent because there is no batching. After, intent resolution is batched within a range, so it is only paid 10 times because there are 10 ranges.

**Comment by nvanbenschoten** [comment]
Friendly ping on this review. We have a customer that is waiting for this change.

**Review by irfansharif — APPROVED** [review]
This is somewhat of a 🐶🔎 review for me, but :lgtm:. The code changes make sense, I was mostly how I should be interpreting the datadriven tests below. Is there something written up that I could've read?

Also, all the added commentary here is great! Thanks for taking the time to describe it in these terms and validating the impacts here through your experiments (also why I procrastinated, I had to read carefully 😛). The caveats with redirecting follower reads to the leaseholder if in advance of resolved timestamps make sense, and it makes sense for us to not care about them too much.

> Reviewed 7 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70382#-:-MlvFf2e5kX7KL15DpbQ:b-w48a7p)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/kvserver/concurrency/testdata/concurrency_manager/discovered_lock, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70382#-MlvEEMGD1eYkVkZhUq2:-MlvEEMGD1eYkVkZhUq3:bookk25) ([raw file](https://github.com/cockroachdb/cockroach/blob/eef42a28b4ac462a3b410814cf187801a4025cf3/pkg/kv/kvserver/concurrency/testdata/concurrency_manager/discovered_lock#L66)):*
> ```
> # lock-table is disabled. The lock-table cannot store the lock,
> # so the request retries immediately and redirects when it
> # notices the incorrect lease.
> ```

Can you explain to me what in the test output below are we interpreting as "retries immediately" and "redirects" and "when it notices the incorrect lease"? I'm a bit out of my depth here. Some commentary for me would also help me better understand how to interpret `range_state_listener`. Telling me I should read up on this package is also a fine response, I probably should have by now.

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> we don't detect the difference between the resolved timestamp and the closed timestamp until after we have begun evaluating the follower read and scanning MVCC data. This lazy detection of follower read eligibility can lead to wasted work. In the future, we may consider making this detection eager once we address #69717.

#69717 has been closed. But that issue seems to be about `QueryResolvedTimestamp`. How exactly does it apply here? I guess what we want for a follower read is to scan the (replicated) lock table before scanning the regular keys. But that desire is not specific to follower reads, right? In fact, maybe we already do that?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70382#-:-Mlz2jWCCirYUy9nUwbp:b-b4cptk)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andreimatei, @irfansharif, and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_send.go, line 604 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70382#-Mlz4RcLEb4O_K2TMzE_:-Mlz4RcLEb4O_K2TMzEa:b-4n6z9a) ([raw file](https://github.com/cockroachdb/cockroach/blob/eef42a28b4ac462a3b410814cf187801a4025cf3/pkg/kv/kvserver/replica_send.go#L604)):*
> ```Go
> 		// in CockroachDB. In Spanner, it is the "safe time" of a replica that
> 		// determines follower read eligibility.
> 		if lease.Empty() /* followerRead */ {
> ```

mmm is this `maybeAttachLease` function really the place to do this error switcheroo? Seems kinda random to me. And also the fact that an empty lease means follower read; perhaps that implication is natural in other places, but in this tiny function is seems surprising (particularly since it's not documented).
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 2334 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70382#-Mlz59hJ5rHIOeIjXBD_:-Mlz59hJ5rHIOeIjXBDa:bv6fbp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/eef42a28b4ac462a3b410814cf187801a4025cf3/pkg/kv/kvserver/concurrency/lock_table.go#L2334)):*
> ```Go
> 		// If the lease sequence is too low, this discovered lock may no longer
> 		// be accurate, so we ignore it.
> 		return false, nil
> ```

how come this change?

**Review by nvb — COMMENTED** [review]
TFTRs!

> I was mostly how I should be interpreting the datadriven tests below. Is there something written up that I could've read?

I think the best place to read to learn about this specific datadriven test dialect is the [DSL description](https://github.com/cockroachdb/cockroach/blob/eaeb01699c1672be5dfc29e081c0cc2d7a718c39/pkg/kv/kvserver/concurrency/concurrency_manager_test.go#L51) and the [external interface of the concurrency package](https://github.com/cockroachdb/cockroach/blob/eaeb01699c1672be5dfc29e081c0cc2d7a718c39/pkg/kv/kvserver/concurrency/concurrency_control.go), which maps to the DSL fairly directly.

> How exactly does it apply here? I guess what we want for a follower read is to scan the (replicated) lock table before scanning the regular keys. But that desire is not specific to follower reads, right? In fact, maybe we already do that?

Yes, pretty much exactly what you're saying. We don't eagerly scan the persistent portion of the lock table today for any form of read, but we could. This would allow us to block earlier on the leaseholder and to redirect earlier on followers. Of course, there are trade-offs to doing so, which have been discussed elsewhere.

bors r=irfansharif,andreimatei

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70382#-:-MmdGgqJ4s34jxNJwrXf:bns5l5i)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andreimatei and @irfansharif)

___
*[pkg/kv/kvserver/replica_send.go, line 604 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70382#-Mlz4RcLEb4O_K2TMzE_:-MmdIa6G0UdEtQj2ga7e:begc0po) ([raw file](https://github.com/cockroachdb/cockroach/blob/eef42a28b4ac462a3b410814cf187801a4025cf3/pkg/kv/kvserver/replica_send.go#L604)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

mmm is this `maybeAttachLease` function really the place to do this error switcheroo? Seems kinda random to me. And also the fact that an empty lease means follower read; perhaps that implication is natural in other places, but in this tiny function is seems surprising (particularly since it's not documented).
</blockquote></details>

I think it is the right place, at least given the current code structure. It's where we're already associating a discovered lock with the lease that it was discovered under, so it makes sense to extend it to handle the case where a discovered lock wasn't discovered under a lease at all (i.e. a follower read). I added more commentary.
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 2334 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70382#-Mlz59hJ5rHIOeIjXBD_:-MmdHd1WBLnwFq8nALGo:bovsamd) ([raw file](https://github.com/cockroachdb/cockroach/blob/eef42a28b4ac462a3b410814cf187801a4025cf3/pkg/kv/kvserver/concurrency/lock_table.go#L2334)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

how come this change?
</blockquote></details>

Before this change, we were [using the `added` return value to determine](https://github.com/cockroachdb/cockroach/blob/eaeb01699c1672be5dfc29e081c0cc2d7a718c39/pkg/kv/kvserver/concurrency/concurrency_manager.go#L431) whether to [immediately wait on discovered lock](https://github.com/cockroachdb/cockroach/blob/eaeb01699c1672be5dfc29e081c0cc2d7a718c39/pkg/kv/kvserver/concurrency/concurrency_manager.go#L448) instead of passing back through the `lockTable` to wait on it during the next concurrency retry. As the deleted comment here references, we didn't want to immediately wait in cases where `seq < t.enabledSeq` because the lock may have been stale. So we pretended that we added the lock to the lock table even though we didn't to allow the request to immediately retry. This was all a bit of a hack and we can now remove it.
___
*[pkg/kv/kvserver/concurrency/testdata/concurrency_manager/discovered_lock, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70382#-MlvEEMGD1eYkVkZhUq2:-MmdKeRE8sq11jLa7zxd:b-gq3vwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/eef42a28b4ac462a3b410814cf187801a4025cf3/pkg/kv/kvserver/concurrency/testdata/concurrency_manager/discovered_lock#L66)):*
> Can you explain to me what in the test output below are we interpreting as "retries immediately" and "redirects" and "when it notices the incorrect lease"?

The test demonstrates the immediate retry by releasing latches without blocking during the `handle-write-intent-error` and then allowing the request to re-`sequence`. The idea is that once the request re-sequences, it will check the lease again and will notice the mismatch and redirect. But unlike in the `range_state_listener` tests, we weren't modeling the redirect in this file, which was a little confusing. I've added comments to make it more clear where the redirect comes into play.

**Pull request merged**
