### PR TITLE
bazel,dev: add robust support/validation for checked-in generated code

### LINKED ISSUE #68654: bazel: `pkg/roachpb:bootstrap` and `pkg/sql/opt/optgen/lang:bootstrap` are a disaster
This target depends on `batch_generated.go`, which is wrong since we're depending on a checked-in generated file. But it can't be replaced with `:gen-batch-generated` because it introduces a cyclic dependency error:

```
ERROR: /Users/ricky/go/src/github.com/cockroachdb/cockroach/pkg/roachpb/gen/BUILD.bazel:39:10: in go_binary rule //pkg/roachpb/gen:gen: cycle in dependency graph:
    //pkg/cmd/cockroach-short:cockroach-short
    //pkg/cmd/cockroach-short:cockroach-short_lib
    //pkg/ccl:ccl
    //pkg/ccl/oidcccl:oidcccl
    //pkg/ui:ui
    //pkg/base:base
    //pkg/security:security
    //pkg/settings/cluster:cluster
    //pkg/clusterversion:clusterversion
    //pkg/clusterversion:clusterversion_go_proto
    //pkg/roachpb:with-mocks
    //pkg/roachpb:roachpb
    //pkg/roachpb:gen-batch-generated
.-> //pkg/roachpb/gen:gen
|   //pkg/roachpb/gen:gen_lib
|   //pkg/roachpb:bootstrap
|   //pkg/roachpb:gen-batch-generated
`-- //pkg/roachpb/gen:gen
```

Epic CRDB-8035

### PR DESCRIPTION
**Pull request by rickystewart**
(Only the most recent commit applies for this review.)

While testing #68663, I noticed that there were a few build targets that
didn't look as I expected since they referenced checked-in generated
code in order to generate that same code in the sandbox -- e.g., the
checked-in `batch_generated.go` was used to generate an (identical) file
`batch_generated-gen.go` within the sandbox. I filed the issue #68654 to
investigate this, and gave a college try to stamping out the recursive
structure by refactoring the affected code. I wasn't successful :(

While looking at this I encountered comments by Irfan in
`pkg/{roachpb/gen,sql/opt/optgen/cmd/langgen}/BUILD.bazel` explaining
that this generated code needs to remain checked-in in order to
bootstrap new versions of the code, and that our tooling needs to have
support for extracting this code back into the workspace so devs can
have a sane workflow. Fair enough, so this PR implements all of that.

* Add `dev generate go` to generate the checked-in generated code;
* fix up `dev generate` so that it generates for `bazel`, `docs`, and
  `go` altogether (so `dev generate` is a one-step thing you can do to
  generate everything you'll need to pass CI);
* build the generated Go code via the sandbox in CI and test to make
  sure it matches what's checked in.

Closes #68654.

Release note: None

### CODE REVIEW

**Review by irfansharif — APPROVED** [review]
Good stuff.

**Comment by rickystewart** [comment]
bors r=irfansharif

**Comment by rickystewart** [comment]
bors r=irfansharif

**Comment by rickystewart** [comment]
i stg

bors r=irfansharif

**Pull request merged**
