### PR TITLE
ui: Improve Jobs page status when a high-water timestamp is present

### LINKED ISSUE #80981: ui: The "status" column in the UI seems discrepant from the status in SHOW JOBS when a high-water timestamp is present
Broken out from https://github.com/cockroachdb/cockroach/issues/71563#issuecomment-1116246157 to separate the issues.

Here, these three jobs are either canceled or paused, but the canceled and paused statuses are not shown in the UI. This can be confusing.

image
image

Previous discussion:

@jocrl: Poking around, I still don't have a good understanding of what a highwater timestamp is. But I'm wondering if we maybe want to show a running/cancelled/paused etc. badge in addition to the highwater timestamp?

@Annebirzin: I'm not sure I'm fully understanding the discrepancy but seems like adding the status would make the true status more clear (and assuming this would be consistent with the jobs table in the SQL shell)

@miretskiy, via slack: Highwater makes sense for Running or Paused jobs (perhaps retrying too)...
pause-requested is a transient state... I suppose it does make sense to show it there as well...

Jira issue: CRDB-15410

### PR DESCRIPTION
**Pull request by jocrl**
Todo:
Blocked on resolving the discussion in https://github.com/cockroachdb/cockroach/issues/80981 on whether we should make this change at all.

Fixes #80981

Previously, if a job had a high-water timestamp, the high-water timestamp would
always show, and the job status would be hidden.

This commit modifies the UI such that the high-water timestamp (if available) is
only shown when the job status is "running", "paused", or "pause-requested".
Additionally, these statuses are still shown even if there is a high-water
timestamp.

These are now the only possible statuses that show a high-water timestamp:
image

Before:
image

After:
image

Release note (ui): Previously, if a job had a high-water timestamp, the
high-water timestamp would always show, and the job status would be hidden.
Now, the high-water timestamp is only shown for jobs with the
status "running", "paused", or "pause-requested", and the status is shown in
addition to the high-water timestamp.

### CODE REVIEW

**Comment by jocrl** [comment]
@Annebirzin, requesting your review that the design is cool! For reference, here's a gallery of our many possible job status states 😅:

image

**Comment by Annebirzin** [comment]
@jocrl One minor tweak, can we make the font for the high-water timestamp the same size/color as the fonts for the other status details (ie. `Waiting for GC TTL` or `Duration: 00:00:00`). I think it would be size 12pt. 

Other than that LGTM!

**Comment by jocrl** [comment]
Thanks, Anne!

I'll hold off on that, and converting to a draft in the meantime, until we resolve the discussion in https://github.com/cockroachdb/cockroach/issues/80981 on whether we should make this change at all.

**Comment by jocrl** [comment]
Closing; no longer needed as https://github.com/cockroachdb/cockroach/issues/80981 is being resolved by https://github.com/cockroachdb/cockroach/pull/81213

**Pull request closed without merging**
