### PR TITLE
cmd/reduce: add -tlp option

### PR DESCRIPTION
**Pull request by yuzefovich**
**cmd/reduce: remove stdin option and require -file argument**

We tend to not use the option of passing input SQL via stdin, so this
commit removes it. An additional argument in favor of doing that is that
the follow-up commit will introduce another mode of behavior that
requires `-file` argument to be specified, so it's just cleaner to
always require it now.

Release note: None

**cmd/reduce: add -tlp option**

This commit adds `-tlp` boolean flag that changes the behavior of
`reduce`. It is required that `-file` is specified whenever the `-tlp`
flag is used. The behavior is such that the last two queries (delimited
by empty lines) in the file contain unpartitioned and partitioned queries
that return different results although they are equivalent.

If TLP check is requested, then we remove the last two queries from the
input which we use then to construct a special TLP check query that
results in an error if two removed queries return different results.

We do not just include the TLP check query into the input string because
the reducer would then reduce the check query itself, making the
reduction meaningless.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
The next step is to use the reducer automatically when filing `roachtest/tlp` issues :)

**Review by cucaroach — APPROVED** [review]
Very cool!  :LGTM:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76545#-:-Mvx0o8g8G4gwJvf9Mg2:bm3gq9r)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @michae2)

**Review by mgartner — APPROVED** [review]
Love it! :lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76545#-:-MvxtKLIDc8u8cfrPXIo:be0asap)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[pkg/cmd/reduce/main.go, line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76545#-MvxlmCE247NfWQAJaEQ:-MvxlmCE247NfWQAJaER:brc633g) ([raw file](https://github.com/cockroachdb/cockroach/blob/af1a50ae97a61fd7125c3a3754254494acc991f5/pkg/cmd/reduce/main.go#L85)):*
> ```Go
> 	}
> 	if (*tlp && (*file == "" || *contains != "")) || (!*tlp && *contains == "") {
> 		fmt.Printf("%s: either -contains or -tlp and -file must be provided\n\n", os.Args[0])
> ```

I'd be fine removing the stdin variant of `reduce`. It doesn't seem necessary and adds extra complexity. I'm also happy to do this in a follow-up PR if you'd prefer to just get this merged.

**Review by yuzefovich — COMMENTED** [review]
I had to improve the parsing a bit since the queries might span multiple lines. I tried the updated tool on several `tlp.log` files, and it seems to work well.

TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76545#-:-Mvye-vY8v6BH-_cRvvD:b-x5m2sj)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @cucaroach, @mgartner, and @michae2)

___
*[pkg/cmd/reduce/main.go, line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76545#-MvxlmCE247NfWQAJaEQ:-MvyeaqQ4OfFHu4s8vEB:b-giag4v) ([raw file](https://github.com/cockroachdb/cockroach/blob/af1a50ae97a61fd7125c3a3754254494acc991f5/pkg/cmd/reduce/main.go#L85)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I'd be fine removing the stdin variant of `reduce`. It doesn't seem necessary and adds extra complexity. I'm also happy to do this in a follow-up PR if you'd prefer to just get this merged.
</blockquote></details>

Good point, added another commit to do that.

**Pull request merged**
