### PR TITLE
sql: set default sample_rate to 0.1

### LINKED ISSUE #59379: sql: evaluate sql.txn_stats.sample_rate default
https://github.com/cockroachdb/cockroach/pull/59132 adds the `sql.txn_stats.sample_rate` cluster setting. The default setting is 0, which means never sample stats. However, we're soon going to change the DB Console page to show these sampled execution stats, which means that this setting has to be nonzero to show interesting information.

This issue tracks quantifying the performance effect of turning this setting up to always sample and seeing if it is realistic to remove this setting at all. If not, we might want to have a low but nonzero sample rate to provide some interesting data.

### PR DESCRIPTION
**Pull request by yuzefovich**
**sql: do not reset planner if PREPARE is executed as a stmt**

Previously, when executing a PREPARE command, we would always reset the
planner. This is not necessary when the origin of the command is SQL
because in that case we properly reset the planner before starting the
statement's execution. This change fixes a problem when PREPARE
statements are chosen to be sampled for execution statistics (without
the fix, we would encounter a nil pointer).

Release note: None

**sql: set default sample_rate to 0.1**

Fixes: #59379.

Release note (sql change): Default value for `sql.txn_stats.sample_rate`
cluster setting has been increased from 0 to 0.1. This means that from
now on every statement has 10% probability of being sampled for the
purposes of execution statistics. Note that no other criteria for
sampling (like the query latencies) are currently being utilized to
decide whether to sample a statement or not.

### CODE REVIEW

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61760#-:-MVRb45c4jwgM0L4nYRY:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by yuzefovich** [comment]
There was a problem with `resetPlanner` resetting the instrumentation which could lead to nil pointers, so I had to adjust the commit, so it needs another look. Also @RaduBerinde I'd appreciate if you took a look as well.

Another option to going around the issue that I see is introducing `resetInstrumentation bool` argument to `resetPlanner` signature, and set that to `true` only when calling from `execStmtInOpenState`. Not sure if it would be better. Also curious to hear other ideas.

The problem is that we first set up the instrumentation and decide that it needs to be finished, but then we might call `resetPlanner` pretty much right away which will overwrite whatever needs to be finished.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61760)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[pkg/sql/conn_executor.go, line 2274 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61760#-MVSWUIe44Sr14S3cpV_:-MVSWUIe44Sr14S3cpVa:b-5j7u4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c0233051250a3622dc8b383b7270964ca85c0f0/pkg/sql/conn_executor.go#L2274)):*
> ```Go
> 	p.stmt = Statement{}
> 	// Note that we deliberately do not reset p.instrumentation since we need to
> 	// have more fine-grained control over resetting that field.
> ```

This is surprising.. What field exactly was problematic? I'm worried we may hang on to various things here (e.g. `traceMetadata`, `explainPlan`).

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61760)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

___
*[pkg/sql/conn_executor.go, line 2274 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61760#-MVSWUIe44Sr14S3cpV_:-MVSXIJD0qk-vUftO6Ep:b-iaht61) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c0233051250a3622dc8b383b7270964ca85c0f0/pkg/sql/conn_executor.go#L2274)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is surprising.. What field exactly was problematic? I'm worried we may hang on to various things here (e.g. `traceMetadata`, `explainPlan`).
</blockquote></details>

`instrumentation.sp` - now in `Finish` we have an assumption that `sp` is non-nil. This is always the case after `Setup` is called and returns `needFinish == true`, yet because of the resetting behavior in `resetPlanner` we would overwrite `sp` to `nil`. This was introduced in #61532 as a perf optimization.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61760)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

___
*[pkg/sql/conn_executor.go, line 2274 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61760#-MVSWUIe44Sr14S3cpV_:-MVSXbv11kAJwYWzUCbP:b-nqtp6w) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c0233051250a3622dc8b383b7270964ca85c0f0/pkg/sql/conn_executor.go#L2274)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

`instrumentation.sp` - now in `Finish` we have an assumption that `sp` is non-nil. This is always the case after `Setup` is called and returns `needFinish == true`, yet because of the resetting behavior in `resetPlanner` we would overwrite `sp` to `nil`. This was introduced in #61532 as a perf optimization.
</blockquote></details>

Also because of the current resetting behavior tracing of `PREPARE` is effectively a noop, and I'm not sure it was the intention.

**Comment by yuzefovich** [comment]
Updated the PR based on the conversation with Radu.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61760)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/conn_executor_prepare.go, line 204 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61760#-MVSiJrN5SOfNJjExsGD:-MVSiJrN5SOfNJjExsGE:b-xrgbs5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5cbaf90191487b8ae3e29775456a9667a62876b/pkg/sql/conn_executor_prepare.go#L204)):*
> ```Go
> 		ex.statsCollector.reset(&ex.server.sqlStats, ex.appStats, &ex.phaseTimes)
> 		p := &ex.planner
> 		if origin != PreparedStatementOriginSQL {
> ```

nit: I think this probably deserves a "why" comment

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61760)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @RaduBerinde)

___
*[pkg/sql/conn_executor_prepare.go, line 204 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61760#-MVSiJrN5SOfNJjExsGD:-MVSo7FN5-tFMwccJ1lA:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5cbaf90191487b8ae3e29775456a9667a62876b/pkg/sql/conn_executor_prepare.go#L204)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: I think this probably deserves a "why" comment
</blockquote></details>

Good point, done.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61760#-:-MVSoLtvAysl_CsdZEtz:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @RaduBerinde)

**Comment by yuzefovich** [comment]
The CI seems to be red because of unrelated flakes in KV, so I'll go ahead and merge this.

TFTRs!

bors r+

**Pull request merged**
