### PR TITLE
distsql: Change projections on all columns to no-ops

### PR DESCRIPTION
**Pull request by abhimadan**
To simplify some physical plans that call AddProjection on all columns,
check for the special case where there is no existing rendering, and the
projection is on every column without changing the column order.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm: 

Nice, thanks for doing this!

---

Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsqlplan/physical_plan.go, line 280 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22836#-L5nqYxmxVyDlcG_4Obr:-L5nqYxmxVyDlcG_4Obs:b-hm8h5w) ([raw file](https://github.com/cockroachdb/cockroach/blob/43d0d3fd0eb60229b82c53c1c3bfe3fec5aaf682/pkg/sql/distsqlplan/physical_plan.go#L280)):*
> ```Go
> }
> 
> func isIdentityProjection(columns []uint32) bool {
> ```

[nit] I would move the length check inside this function (and pass the number of expected columns as an arg). As it is, it's returning whether it is a prefix of the identity projection.

---

*[pkg/sql/distsqlplan/physical_plan.go, line 289 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22836#-L5nri9SAOsAplyt32jP:-L5nri9SAOsAplyt32jQ:b-jfs7f1) ([raw file](https://github.com/cockroachdb/cockroach/blob/43d0d3fd0eb60229b82c53c1c3bfe3fec5aaf682/pkg/sql/distsqlplan/physical_plan.go#L289)):*
> ```Go
> }
> 
> func hasPostRender(post distsqlrun.PostProcessSpec) bool {
> ```

[nit] the name is a bit of a misnomer (it's render or projection). I would just use the checks directly without the function, they're more self-documenting.

---

*[pkg/sql/distsqlplan/physical_plan.go, line 307 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22836#-L5nrDzSElRwRJHl3V-o:-L5nrDzSElRwRJHl3V-p:bl5ei97) ([raw file](https://github.com/cockroachdb/cockroach/blob/43d0d3fd0eb60229b82c53c1c3bfe3fec5aaf682/pkg/sql/distsqlplan/physical_plan.go#L307)):*
> ```Go
> 	// If there is no existing post-processing render or projection, and the one
> 	// we are trying to apply projects every column, don't update the spec.
> 	if !hasPostRender(post) && isIdentityProjection(columns) && len(columns) == len(p.ResultTypes) {
> ```

Why the `!hasPostRender` check? Even if there is an existing post-process spec, an identity projection still does nothing. IIRC `p.ResultTypes` takes into account the post-processing.

In this case, the code below should be a no-op.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22836#-:-L5nqwhitWtTNeu_9ZnF:b39f2bw)*

**Comment by abhimadan** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/distsqlplan/physical_plan.go, line 280 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22836#-L5nqYxmxVyDlcG_4Obr:-L5nu9ZgWEbU1LggDlMh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/43d0d3fd0eb60229b82c53c1c3bfe3fec5aaf682/pkg/sql/distsqlplan/physical_plan.go#L280)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I would move the length check inside this function (and pass the number of expected columns as an arg). As it is, it's returning whether it is a prefix of the identity projection.
</blockquote></details>

Done.

---

*[pkg/sql/distsqlplan/physical_plan.go, line 289 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22836#-L5nri9SAOsAplyt32jP:-L5nuBSyak4bz2KFvKJa:b-o692x6) ([raw file](https://github.com/cockroachdb/cockroach/blob/43d0d3fd0eb60229b82c53c1c3bfe3fec5aaf682/pkg/sql/distsqlplan/physical_plan.go#L289)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] the name is a bit of a misnomer (it's render or projection). I would just use the checks directly without the function, they're more self-documenting.
</blockquote></details>

Removed (as per your comment below).

---

*[pkg/sql/distsqlplan/physical_plan.go, line 307 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22836#-L5nrDzSElRwRJHl3V-o:-L5nuDbefoD7olhtubpv:b6poqzv) ([raw file](https://github.com/cockroachdb/cockroach/blob/43d0d3fd0eb60229b82c53c1c3bfe3fec5aaf682/pkg/sql/distsqlplan/physical_plan.go#L307)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Why the `!hasPostRender` check? Even if there is an existing post-process spec, an identity projection still does nothing. IIRC `p.ResultTypes` takes into account the post-processing.

In this case, the code below should be a no-op.
</blockquote></details>

I was focused on the cases that would actually change physical plans to have no post-processing, and I didn't realize that the change also provides this fast path for no-op projections. Thanks for pointing this out! That check has been removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22836)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Reviewed 8 of 9 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsqlplan/physical_plan.go, line 286 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22836#-L5nwujeV67eJK3HRdLW:-L5nwujeV67eJK3HRdLX:b-awcxwe) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a95e1ef6955373b3d5da083b13835e1f67ee4a9/pkg/sql/distsqlplan/physical_plan.go#L286)):*
> ```Go
> 		}
> 	}
> 	return len(columns) == numExistingCols
> ```

[int] I would check this first (no point bothering with the loop if the length doesn't match).

---

*[pkg/sql/distsqlplan/physical_plan.go, line 299 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22836#-L5nwpYzrTm3c0z3zQv7:-L5nwpYzrTm3c0z3zQv8:bsqjbq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a95e1ef6955373b3d5da083b13835e1f67ee4a9/pkg/sql/distsqlplan/physical_plan.go#L299)):*
> ```Go
> // or use it directly in specs.
> func (p *PhysicalPlan) AddProjection(columns []uint32) {
> 	post := p.GetLastStagePost()
> ```

[nit] Not your change, but can you move this down closer to where it's first used?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22836#-:-L5nwzJWyFZRhU2d_gaj:bnfp4nl)*

**Comment by abhimadan** [comment]
Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/distsqlplan/physical_plan.go, line 286 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22836#-L5nwujeV67eJK3HRdLW:-L5nyn60L_lQ1MOZf3_B:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a95e1ef6955373b3d5da083b13835e1f67ee4a9/pkg/sql/distsqlplan/physical_plan.go#L286)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[int] I would check this first (no point bothering with the loop if the length doesn't match).
</blockquote></details>

Done.

---

*[pkg/sql/distsqlplan/physical_plan.go, line 299 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22836#-L5nwpYzrTm3c0z3zQv7:-L5nynkIPeRv2D_tQ877:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a95e1ef6955373b3d5da083b13835e1f67ee4a9/pkg/sql/distsqlplan/physical_plan.go#L299)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Not your change, but can you move this down closer to where it's first used?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22836)*

**Comment by RaduBerinde** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22836)*

**Pull request merged**
