### PR TITLE
opt: add support for ALTER TABLE/INDEX SPLIT AT

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: return index ordinal from ResolveTableIndex

Release note: None

#### optbuilder: add wrapper for building typed scalar

Release note: None

#### opt: add support for ALTER TABLE/INDEX SPLIT AT

Adding optimizer support for `tree.Split`. This statement has a
relational input, so it can't be implemented as an "opaque".

Release note: None

Informs #34848.

### CODE REVIEW

**Review by justinj — COMMENTED** [review]
:lgtm:, feels to me like maybe `cat.Index`s want to know their own ordinal index, which would let `ResolveTableIndex` keep its (imo more natural?) signature. I guess if this is the only case where it matters then it's unclear.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38585#-:-LiiSRFV8mBl_BAYZZfo:brex9gr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj and @rytaft)

**Review by RaduBerinde — COMMENTED** [review]
`Column` also doesn't have a method returning its `Ordinal`, instead we have to store it alongside in `IndexColumn`. I'm not sure if that was because of a high-level principle or it would have just been hard to implement. For `optIndex` it should be easy, we just need to add the ordinal as a member. CC @andy-kimball - do you have any thoughts on Index having an `Ordinal()` method?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38585#-:-LiiXebD8d3c7psoZ1PK:b-y88vsn)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

**Review by andy-kimball — COMMENTED** [review]
It's problematic to store an ordinal in `Column`, because it would force the creation of a new wrapper object. Right now, we implement the `opt.Column` interface directly on `sqlbase.ColumnDescriptor`. I don't see any issue with having an `Index` remember its ordinal, since we already have a wrapper in that case.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38585#-:-LijCOm09TKkcjbc02OI:boed4h6)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

**Comment by RaduBerinde** [comment]
Ok, dropped the first commit and added an `Index.Ordinal` instead.

**Review by justinj — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38585#-:-LijJuXr4IDGUITtEPTR:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

**Pull request merged**
