### PR TITLE
storage: disable log file size limit before consistency fatal

### PR DESCRIPTION
**Pull request by tbg**
This should avoid losing the diff printed to the logs, as observed in:
https://github.com/cockroachdb/cockroach/issues/36861

We don't necessarily care about the large diffs (though they can't hurt
to have around) but about whatever else is in the deleted logs. Without
logs, debugging is typically much more difficult.

Release note: None

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
mmm I think I'd rather write the diff to a dedicated file. This way it also wouldn't go away immediately if the server is restarted. No?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36950#-:-LcrNQJD19moCGt0KYW1:b-crrj8n)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by tbg** [comment]
Since you feel more strongly about this, mind taking this over? Happy to review

**Comment by andreimatei** [comment]
:LGTM: if you're not impressed that this won't help people who autorestart nodes (i.e. everybody but us)

**Comment by tbg** [comment]
> if you're not impressed that this won't help people who autorestart nodes (i.e. everybody but us)

Yeah, not ideal, but I think it'll do, pig, it'll do.

TFTR!

bors r=andreimatei

**Pull request merged**
