### PR TITLE
roachprod{,-stress}: let roachprod-stress use roachprod library

### PR DESCRIPTION
**Pull request by healthy-pod**
This patch migrates roachprod-stress from using the roachprod
binary to using the roachprod library.

Release justification: Non-production code changes
Release note: None

### CODE REVIEW

**Review by srosenberg — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86920#-:-NAMU-D_4e_0xPJH5XBH:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan)

**Comment by healthy-pod** [comment]
TFTR!

**Comment by healthy-pod** [comment]
bors r=srosenberg

**Comment by healthy-pod** [comment]
bors r=srosenberg

**Pull request merged**
