### PR TITLE
opt: introduce placeholder fast path

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### sql: support EXPLAIN ANALYZE EXECUTE

We currently cannot EXPLAIN an EXECUTE statement (the syntax doesn't
even allow it). EXECUTE is handled with special code at the top-level,
so it's tricky to make it work with EXPLAIN. However, EXPLAIN ANALYZE
Is also handled at the top level, before the EXECUTE handling, so that
should just work.

This change allows the parsing of such statements so we can use
EXPLAIN ANALYZE EXECUTE. If EXPLAIN EXECUTE is attempted, we get a
"not supported" error (this is less cryptic than the parsing error
anyway).

Release note: None

#### opt: normalize In with single-element list to Eq

This commit adds a rule that normalizes `a IN (b)` to `a = b` (and
similarly `NOT IN` to `!=`).

This query confirms the equivalency holds even when NULLs are
involved:

```
WITH
  vals (v) AS (VALUES (1), (2), (NULL))
SELECT
  v1.v, v2.v, v1.v NOT IN (v2.v,) AS in, v1.v != v2.v AS eq
FROM
  vals AS v1, vals AS v2

   v   |  v   |  in   |  eq
-------+------+-------+--------
     1 |    1 | false | false
     1 |    2 | true  | true
     1 | NULL | NULL  | NULL
     2 |    1 | true  | true
     2 |    2 | false | false
     2 | NULL | NULL  | NULL
  NULL |    1 | NULL  | NULL
  NULL |    2 | NULL  | NULL
  NULL | NULL | NULL  | NULL
```

Release note: None

#### opt: introduce placeholder fast path

Currently running a query with placeholders happens as follows:
 - at preparation time, we build a memo with the normalized expression
   *with* placeholders.
 - at execution time, we copy the expression into a new memo,
   replacing placeholders with their value (AssignPlaceholders).
 - then we run exploration which performs the actual optimization.

For trivial queries like KV reads, we do too much work during
execution (profiles show it is 10-20% of the runtime for KV workloads
with high read rates).

This commit introduces the concept of a "placeholder fast path". The
idea is that we can make specific checks for simple expressions and
produce (at preparation time) a fully optimized expression (which
still depends on placeholders). For this, we introduce a new operator,
PlaceholderScan which is similar to a Scan except that it always scans
one span with the same start and end key, and the key values are child
scalar expressions (either constants or placeholders).

We use this new operator only for simple SELECTs where the filters
constrain a prefix of an index to constant values; in addition, the
index must be covering and there must be only one such index. With
these conditions, we know the optimal plan upfront.

For now, the placeholder fast path transformation is Go code; if it
gets more complicated, it should be switched to use optgen rules.

A benchmark on my machine shows a kv95 workload going from 34kiops to
38kiops with this change.

Release note: None

Informs #57223.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
CC @andy-kimball @jordanlewis, thought this might put a smile on your face.

**Comment by jordanlewis** [comment]
❤❤❤ amazing!

**Comment by andy-kimball** [comment]
Really happy to see this happen. I know @nvanbenschoten has also been wanting this for a while. 10%+ boost on KV95 is a very nice result.

**Comment by nvanbenschoten** [comment]
This is fantastic! Thanks for the work here @RaduBerinde.

**Review by mgartner — COMMENTED** [review]
Really cool!

I think it'd be nice to have some execbuilder and/or logictests to ensure the new code in `execbuilder/relational.go` works as expected.

> Reviewed 8 of 8 files at r1, 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63807#-:-MYfs_aUBMeGmebzm8TR:bc5n7p6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/bench/bench_test.go, line 470 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63807#-MYfQlZABD7hNnTVfajT:-MYfQlZBD74J8nCPqnGP:b1behik) ([raw file](https://github.com/cockroachdb/cockroach/blob/92ac9e555a0c6dd6e4427833275837418482f805/pkg/sql/opt/bench/bench_test.go#L470)):*
> ```Go
> 	var execMemo *memo.Memo
> 	if h.prepMemo.IsOptimized() {
> 		// No placeholders, we already did the exploration at prepare time.
> ```

nit: No placeholders **or the placeholder fast path succeeded**
___
*[pkg/sql/opt/xform/placeholder_fast_path.go, line 101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63807#-MYfT3VH1ZxoZ6jc7zCz:-MYfT3VH1ZxoZ6jc7zD-:b-g0u06x) ([raw file](https://github.com/cockroachdb/cockroach/blob/92ac9e555a0c6dd6e4427833275837418482f805/pkg/sql/opt/xform/placeholder_fast_path.go#L101)):*
> ```Go
> 
> 	scan, ok := sel.Input.(*memo.ScanExpr)
> 	if !ok {
> ```

nit: Might be faster in a some cases to check that the Select's input is a Scan and return `ok=false` early before looping through the Select filters.
___
*[pkg/sql/opt/xform/placeholder_fast_path.go, line 107 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63807#-MYfTjDrCCeTbE5UXhvn:-MYfTjDrCCeTbE5UXhvo:b3ym85k) ([raw file](https://github.com/cockroachdb/cockroach/blob/92ac9e555a0c6dd6e4427833275837418482f805/pkg/sql/opt/xform/placeholder_fast_path.go#L107)):*
> ```Go
> 	// Check if there is exactly one covering, non-partial index with a prefix
> 	// matching constrainedCols. In that case, using this index is always the
> 	// optimal plan.
> ```

If there are multiple indexes, but at least one is unique, can't we assume that picking any of the UNIQUE indexes is optimal? This might allow for this optimization to apply in quite a few more cases. I suppose it'd be pointless in practice for a user to prefix any non-unique secondary indexes with columns in another unique index, though, so maybe not worth the added complexity...
___
*[pkg/sql/opt/xform/placeholder_fast_path.go, line 133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63807#-MYfm10X6lIYeE8T3-JA:-MYfm10Y7VW96vBdRUwD:bwoj6ak) ([raw file](https://github.com/cockroachdb/cockroach/blob/92ac9e555a0c6dd6e4427833275837418482f805/pkg/sql/opt/xform/placeholder_fast_path.go#L133)):*
> ```Go
> 		if prefixCols.Equals(constrainedCols) {
> 			if foundIndex != nil {
> 				foundMultiple = true
> ```

Perhaps it'd be helpful to have a halting version of`iter.ForEach` that stops iterating based on the callback's return value. Don't worry about it for this PR thought. You can leave a `TODO(mgartner): Stop the iterator early if a second index is found.` if you'd like.
___
*[pkg/sql/opt/xform/testdata/placeholder-fast-path/scan, line 14 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63807#-MYfsMb04rD0GuBIGqjb:-MYfsMb1EF4wewBx_zp8:b-xj7w1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/92ac9e555a0c6dd6e4427833275837418482f805/pkg/sql/opt/xform/testdata/placeholder-fast-path/scan#L14)):*
> ```
>   INDEX (c,b,a) STORING (d),
>   INDEX (d,c,a),
>   INDEX (d,c,b)
> ```

nit: add a partial index and an inverted index and verify the fast path isn't generated.

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

Unfortunately, we can't do much stuff with placeholders in execbuilder/logictests. I will think about it. Maybe we can add some special support for EXPLAIN EXECUTE.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63807#-:-MYfv03ZBckYE7u2rNg8:bf5jfxr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/xform/placeholder_fast_path.go, line 107 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63807#-MYfTjDrCCeTbE5UXhvn:-MYfvPCl-0G-L-RF2PtK:b-bcjiu) ([raw file](https://github.com/cockroachdb/cockroach/blob/92ac9e555a0c6dd6e4427833275837418482f805/pkg/sql/opt/xform/placeholder_fast_path.go#L107)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

If there are multiple indexes, but at least one is unique, can't we assume that picking any of the UNIQUE indexes is optimal? This might allow for this optimization to apply in quite a few more cases. I suppose it'd be pointless in practice for a user to prefix any non-unique secondary indexes with columns in another unique index, though, so maybe not worth the added complexity...
</blockquote></details>

We'd want to scan the index which stores less data (eg fewer columns), which gets into coster territory.
___
*[pkg/sql/opt/xform/placeholder_fast_path.go, line 133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63807#-MYfm10X6lIYeE8T3-JA:-MYfvbcE4l-bRkh59KYo:bmp0q6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/92ac9e555a0c6dd6e4427833275837418482f805/pkg/sql/opt/xform/placeholder_fast_path.go#L133)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Perhaps it'd be helpful to have a halting version of`iter.ForEach` that stops iterating based on the callback's return value. Don't worry about it for this PR thought. You can leave a `TODO(mgartner): Stop the iterator early if a second index is found.` if you'd like.
</blockquote></details>

It might be nice if there are other usecases; I don't think this would be an important one though because this condition should be pretty rare, and all this happens only at prepare time.

**Review by RaduBerinde — COMMENTED** [review]
Added support for EXPLAIN ANALYZE EXECUTE and added a few tests like that. Also updated handling of partial indexes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63807#-:-MYgMU3M7clMiDYRxq9b:b-let4lh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/xform/testdata/placeholder-fast-path/scan, line 14 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63807#-MYfsMb04rD0GuBIGqjb:-MYgD0bYDU5OEMUImHQ3:b-n7og28) ([raw file](https://github.com/cockroachdb/cockroach/blob/92ac9e555a0c6dd6e4427833275837418482f805/pkg/sql/opt/xform/testdata/placeholder-fast-path/scan#L14)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: add a partial index and an inverted index and verify the fast path isn't generated.
</blockquote></details>

Hm.. Good point. This brings up a problem with partial indexes - we can't simply ignore them, or we may miss out on using them.

Updated to fail the fast path if there are any partial indexes that we can't exclude because the filters don't constrain any partial predicate columns. PTAL.

**Review by mgartner — APPROVED** [review]
:lgtm: :100:

> Added support for EXPLAIN ANALYZE EXECUTE and added a few tests like that.

Thanks for doing this! 

> Reviewed 21 of 28 files at r3, 9 of 9 files at r4, 15 of 15 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63807#-:-MYj_jawBkUFTzpKfMHj:bxrqnvl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/xform/placeholder_fast_path.go, line 107 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63807#-MYfTjDrCCeTbE5UXhvn:-MYjXWIV3WcvPrfrhqUa:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/92ac9e555a0c6dd6e4427833275837418482f805/pkg/sql/opt/xform/placeholder_fast_path.go#L107)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We'd want to scan the index which stores less data (eg fewer columns), which gets into coster territory.
</blockquote></details>

:+1: 
___
*[pkg/sql/opt/xform/placeholder_fast_path.go, line 133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63807#-MYfm10X6lIYeE8T3-JA:-MYjXZPA3glNpAjDppLz:b5ugp1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/92ac9e555a0c6dd6e4427833275837418482f805/pkg/sql/opt/xform/placeholder_fast_path.go#L133)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It might be nice if there are other usecases; I don't think this would be an important one though because this condition should be pretty rare, and all this happens only at prepare time.
</blockquote></details>

Ahh... makes sense.
___
*[pkg/sql/opt/xform/placeholder_fast_path.go, line 110 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63807#-MYjZQRr6-JXX9DrKRPB:-MYjZQRr6-JXX9DrKRPC:bik5ib) ([raw file](https://github.com/cockroachdb/cockroach/blob/34d57a027ab2fbadf8b999e195e9596fd2c8adb5/pkg/sql/opt/xform/placeholder_fast_path.go#L110)):*
> ```Go
> 
> 	var iter scanIndexIter
> 	iter.Init(
> ```

nit: you don't need `iter` now 
___
*[pkg/sql/opt/xform/testdata/placeholder-fast-path/scan, line 208 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63807#-MYjZqFH0gccAP0EA3V6:-MYjZqFH0gccAP0EA3V7:bd6uzr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/34d57a027ab2fbadf8b999e195e9596fd2c8adb5/pkg/sql/opt/xform/testdata/placeholder-fast-path/scan#L208)):*
> ```
>   b INT,
>   c INT,
> ```

nit: remove blank line
___
*[pkg/sql/opt/xform/testdata/placeholder-fast-path/scan, line 227 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63807#-MYj_E5e0R81QRe5hekE:-MYj_E5e0R81QRe5hekF:b-swhh6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/34d57a027ab2fbadf8b999e195e9596fd2c8adb5/pkg/sql/opt/xform/testdata/placeholder-fast-path/scan#L227)):*
> ```
> SELECT a, b FROM partial1 WHERE a = 0
> ----
> placeholder-scan partial1@secondary,partial
> ```

nit: if you name the (a, b) partial index it'll be easier for a human to understand/verify the test output.

**Review by rytaft — APPROVED** [review]
:lgtm: Really great to see this!! Should we add a docs-todo for the EXPLAIN EXECUTE v. EXPLAIN ANALYZE EXECUTE?

nit: in the commit/PR message: "at perparation time" -> "at preparation time"

> Reviewed 28 of 28 files at r3, 9 of 9 files at r4, 15 of 15 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63807#-:-MYj0bclCpvem1YPUCAY:b-cdaxwu)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/opt/exec/execbuilder/relational.go, line 475 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63807#-MYj44wgB3aXXYYkUgcp:-MYj44wh5X_AQWT0yb3a:bsw5cig) ([raw file](https://github.com/cockroachdb/cockroach/blob/34d57a027ab2fbadf8b999e195e9596fd2c8adb5/pkg/sql/opt/exec/execbuilder/relational.go#L475)):*
> ```Go
> // if successful (ok=true), the scan is guaranteed never to return more results
> // than maxRows.
> func (b *Builder) indexConstraintMaxResults(
> ```

nit: explain why you need expr in addition to scan

(or you could just use my suggestion of tagging both expression types with `Scan` so you can just pass the expr)
___
*[pkg/sql/opt/exec/execbuilder/testdata/scalar, line 1204 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63807#-MYj1k_pDSd9V6w0zJcK:-MYj1ZkCBDExrPJmvMMj:b-sfg59n) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c6e54e9e645a2873b12446cfaf5bbab538e89ac/pkg/sql/opt/exec/execbuilder/testdata/scalar#L1204)):*
> ```
> │ columns: (c0)
> │ estimated row count: 333 (missing stats)
> │ filter: CASE WHEN (c0 IS DISTINCT FROM CAST(NULL AS DECIMAL)) OR CAST(NULL AS BOOL) THEN ARRAY[NULL] ELSE ARRAY[] END IS NULL
> ```

Any idea why the `OR CAST(NULL AS BOOL)` is just by itself? (not super important... just thought it was weird)
___
*[pkg/sql/opt/ops/relational.opt, line 103 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63807#-MYj4oQh7ML0M7hMc4Qt:-MYj4oQh7ML0M7hMc4Qu:b3iskh7) ([raw file](https://github.com/cockroachdb/cockroach/blob/34d57a027ab2fbadf8b999e195e9596fd2c8adb5/pkg/sql/opt/ops/relational.opt#L103)):*
> ```
> #
> # PlaceholderScan cannot have a Constraint or InvertedConstraint.
> [Relational]
> ```

you could add a `Scan` tag here and in the `Scan` definition -- that would allow you to test `IsScan()` and then cast the private to a `ScanPrivate`
___
*[pkg/sql/opt/testutils/opttester/opt_tester.go, line 1112 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63807#-MYjipLN5zKl7XYp39hf:-MYjipLO1kXF6mhmwHpQ:b-tk772k) ([raw file](https://github.com/cockroachdb/cockroach/blob/34d57a027ab2fbadf8b999e195e9596fd2c8adb5/pkg/sql/opt/testutils/opttester/opt_tester.go#L1112)):*
> ```Go
> 			ot.appliedRules.Add(int(ruleName))
> 		}
> 	})
> ```

These two functions seem like they are probably used in a lot of places. Does it make sense to put this code in a helper function?

**Comment by RaduBerinde** [comment]
Added docs-todo label for documenting that we support EXPLAIN ANALYZE EXECUTE, and we (still) don't support EXPLAIN EXECUTE.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63807)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/relational.go, line 475 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63807#-MYj44wgB3aXXYYkUgcp:-MYk19pC88ku2x0Kl1zz:b-cg0d0p) ([raw file](https://github.com/cockroachdb/cockroach/blob/34d57a027ab2fbadf8b999e195e9596fd2c8adb5/pkg/sql/opt/exec/execbuilder/relational.go#L475)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: explain why you need expr in addition to scan

(or you could just use my suggestion of tagging both expression types with `Scan` so you can just pass the expr)
</blockquote></details>

The problem with passing the expression is that we're not passing the private in the PlaceholderScan, we are passing our manufactured private (with the constraint). I have changed it to pass the relational and required properties separately.
___
*[pkg/sql/opt/exec/execbuilder/testdata/scalar, line 1204 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63807#-MYj1k_pDSd9V6w0zJcK:-MYjzRopDNTLMySAngRM:b-nwud4g) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c6e54e9e645a2873b12446cfaf5bbab538e89ac/pkg/sql/opt/exec/execbuilder/testdata/scalar#L1204)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Any idea why the `OR CAST(NULL AS BOOL)` is just by itself? (not super important... just thought it was weird)
</blockquote></details>

`x=x` gets normalized to `x is not null or null` (`SimplifySameVarEqualities` rule). The `or null` is needed so the result is `null` as opposed to `false` when x is null (of course, the distinction doesn't matter inside WHEN, but the rule runs independently)
___
*[pkg/sql/opt/testutils/opttester/opt_tester.go, line 1112 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63807#-MYjipLN5zKl7XYp39hf:-MYk6YgVDCkmcKP1Co6N:b-5dp6w6) ([raw file](https://github.com/cockroachdb/cockroach/blob/34d57a027ab2fbadf8b999e195e9596fd2c8adb5/pkg/sql/opt/testutils/opttester/opt_tester.go#L1112)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

These two functions seem like they are probably used in a lot of places. Does it make sense to put this code in a helper function?
</blockquote></details>

Done (moved into `makeOptimizer`).

**Review by mgartner — APPROVED** [review]
> Reviewed 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63807)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @rytaft)

**Review by rytaft — APPROVED** [review]
> Reviewed 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63807)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @RaduBerinde)

___
*[pkg/sql/opt/exec/execbuilder/testdata/scalar, line 1204 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63807#-MYj1k_pDSd9V6w0zJcK:-MYkpUL18lX84tEytHMi:bdsvfmk) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c6e54e9e645a2873b12446cfaf5bbab538e89ac/pkg/sql/opt/exec/execbuilder/testdata/scalar#L1204)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`x=x` gets normalized to `x is not null or null` (`SimplifySameVarEqualities` rule). The `or null` is needed so the result is `null` as opposed to `false` when x is null (of course, the distinction doesn't matter inside WHEN, but the rule runs independently)
</blockquote></details>

got it thanks!

**Comment by RaduBerinde** [comment]
🚨 This needs to be backported together with follow-up fix #64225. 🚨

**Pull request merged**
