### PR TITLE
Pass sql user to DB operations: #1830

### PR DESCRIPTION
**Pull request by mberhault**
This test just shows that permissions are not currently enforced for the sql interface. See #1830

### CODE REVIEW

**Comment by bdarnell** [comment]
LGTM, although I'm not sure if it makes sense to check in a test for this at this point.

**Comment by MBerhault** [comment]
Sorry, no. I only wanted to illustrate this and tie it to the issue. Adjusted the title.

**Comment by MBerhault** [comment]
This latest commit sets the requested user in the db request to the incoming sql user.
The db.CopyWithNewUser feels pretty hacky. The reason for it is that we want to keep the heavy-initialization context (the authenticated user does not change anyway, it's still the NodeUser performing the action).

A better solution would be to have a clear distinction between "state" (the current meaning of base.Context) and actual context (requested user, priority, deadline, etc...).
In the case of the sql endpoint, we could do something along the lines of:
- keep a DB and a request context separately.
- for all DB operations, also pass the context (eg: db.Get(context, .....)). This would be used to set Args.Header.User (which currently just calls db.User).

It would be much cleaner, just a bigger refactor. It may or may not be worth it.

**Comment by MBerhault** [comment]
btw, this does not work. Well, it does, but not once I add the tests.
Users can't create databases (which is fine), but they also can't do anything with the tables or their data without access to:
* write access to the table ID key to create tables
* read access to the namespace/table descriptor for everything else

**Pull request closed without merging**
