### PR TITLE
pkg/util/log: introduce new metrics to the logging package

### LINKED ISSUE #72453: log: introduce more metrics into log pkg for network logging
This is follow up work to #70330.

Since https://github.com/cockroachdb/cockroach/pull/106607, we now have the ability to add metrics to the log package.

While the original PR adds a metric to track fluentbit connection errors, we should add additional metrics such as:

1. When the output buffer becomes full, the new buffer sink implementation chooses to drop messages instead of blocking the log call (this is a feature). Count these.
2. Count of log messages flowing through the log package.
3. Error counts
4. ???

Use the new infra to add useful new metrics to `pkg/util/log`, with a focus on improving observability around network logging.

Jira issue: CRDB-11161

### PR DESCRIPTION
**Pull request by abarganier**
See individual commit messages to review.

This PR introduces two new metrics to the logging package:
- `log.messages.count`
- `log.buffered.messages.dropped`

**log.messages.count**: This metric measures the count of messages logged on the node since startup. Note that this does not measure the fan-out of single log messages to the various configured logging sinks. This metric can be helpful in understanding log rates and volumes.

**log.buffered.messages.dropped**: Buffered network logging sinks have a `max-buffer-size` attribute, which determines, in bytes, how many log messages can be buffered. Any `fluent-server` or `http-server` log sink that makes use of a `buffering` attribute in its configuration (enabled by default) qualifies as a buffered network logging sink. If this buffer becomes full, and an additional log message is sent to the buffered log sing, the buffer would exceed this `max-buffer-size`. Therefore, the buffered log sink drops older messages in the buffer to handle, in order to make room for the new.

This PR also renames the metric `fluent.sink.conn.errors` to `log.fluent.sink.conn.errors`, for consistency.

Fixes: https://github.com/cockroachdb/cockroach/issues/72453

----

Release note (ops change): This patch sets the Metric Type
on the metric `log.fluent.sink.conn.errors`. Previously, the
Metric Type was incorrectly left unset.

Note that this is simply an update to the metric's metadata.
The behavior and purpose of the metric remains unchanged.

----

Release note (ops change): This patch introduces the metric,
`log.messages.count`.

This metric measures the count of messages logged on the
node since startup. Note that this does not measure the
fan-out of single log messages to the various configured
logging sinks.

This metric can be helpful in understanding log rates and
volumes.

----

Release note (ops change): This patch introduces a new metric,
`log.buffered.messages.dropped`.

Buffered network logging sinks have a `max-buffer-size` attribute,
which determines, in bytes, how many log messages can be buffered.
Any `fluent-server` or `http-server` log sink that makes use of
a `buffering` attribute in its configuration (enabled by default)
qualifies as a buffered network logging sink.

If this buffer becomes full, and an additional log message is sent
to the buffered log sing, the buffer would exceed this
`max-buffer-size`. Therefore, the buffered log sink drops older
messages in the buffer to handle, in order to make room for the new.

`log.buffered.messages.dropped` counts the number of messages
dropped from the buffer. Note that the count is shared across all
buffered logging sinks.

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111126)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier)

___
*[`-- commits` line 85 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/111126#-NfBjOqb6a7xNsdXClum):*
nit: sink
___
*[`pkg/util/log/buffered_sink.go` line 492 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/111126#-NfBjvB52Ub8grgifu8k:-NfBjvB52Ub8grgifu8l:bd6sclc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fad506f50950f51ae39fce4e894df1a0508dbe2/pkg/util/log/buffered_sink.go#L492)):*
> ```Go
> 	b.messages = b.messages[1:]
> 	b.sizeBytes -= uint64(firstMsg.Len())
> 	logging.metrics.IncrementCounter(BufferedSinkMessagesDropped, 1)
> ```

any chance we can get a unit test for this?
___
*[`pkg/util/log/clog.go` line 271 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111126#-NfBkLtB4QlMVeBO4_1L:-NfBkLtB4QlMVeBO4_1M:b-1tqk0h) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a68e7d655ee83f70d0a8c11dbe1299992cd19ac/pkg/util/log/clog.go#L271)):*
> ```Go
> 	// can be exercised via pkg/util/log's *own* init() function, which is called first.
> 	// Therefore, we need to protect against this case.
> 	if logging.metrics != nil {
> ```

do we need to worry about this conditional being added to a hot path? 
___
*[`pkg/util/log/clog.go` line 272 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111126#-NfBkSTK96o2fd87F_M5:-NfBkSTK96o2fd87F_M6:b-lz731j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a68e7d655ee83f70d0a8c11dbe1299992cd19ac/pkg/util/log/clog.go#L272)):*
> ```Go
> 	// Therefore, we need to protect against this case.
> 	if logging.metrics != nil {
> 		logging.metrics.IncrementCounter(LogMessageCount, 1)
> ```

can we test that the counter gets incremented?

**Review by abarganier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111126)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[`-- commits` line 85 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/111126#-NfBjOqb6a7xNsdXClum):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: sink
</blockquote></details>

Done.
___
*[`pkg/util/log/buffered_sink.go` line 492 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/111126#-NfBjvB52Ub8grgifu8k:-NfC_LhG4cnnlE24qDlH:ba63zec) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fad506f50950f51ae39fce4e894df1a0508dbe2/pkg/util/log/buffered_sink.go#L492)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

any chance we can get a unit test for this?
</blockquote></details>

Similar to the thread where we increment `LogMessageCount`, is the goal to test that this is called? Or is it to test the functionality of `IncrementCounter`? 
___
*[`pkg/util/log/clog.go` line 271 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111126#-NfBkLtB4QlMVeBO4_1L:-NfCZp7gAHrvznebFipe:b-2agwnp) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a68e7d655ee83f70d0a8c11dbe1299992cd19ac/pkg/util/log/clog.go#L271)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

do we need to worry about this conditional being added to a hot path?
</blockquote></details>

Good question - I just threw together a little toy benchmark:

```
func doThing(l *LogMetricsRegistry) {
	work := 0
	for i := 0; i < 100; i++ {
		if l != nil {
			l.IncrementCounter(log.LogMessageCount, 1)
		}
		work++
	}
}

func doThingWithoutConditional(l *LogMetricsRegistry) {
	work := 0
	for i := 0; i < 100; i++ {
		l.IncrementCounter(log.LogMessageCount, 1)
		work++
	}
}

func doThingWithoutConditionalAndCounter() {
	work := 0
	for i := 0; i < 100; i++ {
		work++
	}
}

func BenchmarkCounters(b *testing.B) {
	l := newLogMetricsRegistry()
	b.Run("with conditional and counter increment", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			for i := 0; i < 10; i++ {
				go doThing(l)
			}
		}
	})
	b.Run("without conditional, but with counter increment", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			for i := 0; i < 10; i++ {
				go doThingWithoutConditional(l)
			}
		}
	})
	b.Run("without conditional and no counter increment", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			for i := 0; i < 10; i++ {
				go doThingWithoutConditionalAndCounter()
			}
		}
	})
}
```

Here are the results:
```
BenchmarkCounters
BenchmarkCounters/with_conditional_and_counter_increment
BenchmarkCounters/with_conditional_and_counter_increment-10         	   19623	    159938 ns/op
BenchmarkCounters/without_conditional,_but_with_counter_increment
BenchmarkCounters/without_conditional,_but_with_counter_increment-10         	   10000	    104556 ns/op
BenchmarkCounters/without_conditional_and_no_counter_increment
BenchmarkCounters/without_conditional_and_no_counter_increment-10            	  498702	      2315 ns/op
```

...That's quite a big performance hit :grimacing:. 

This makes me thing we should just drop this metric from the PR... I don't think the performance hit would be as drastic in the actual `outputLogEntry`, since it's doing a lot more than just incrementing a counter, but I don't think the value added here justifies a slower hot path for logging.

What do you think? 
___
*[`pkg/util/log/clog.go` line 272 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111126#-NfBkSTK96o2fd87F_M5:-NfC_Vfi0zwFdTpcYSk9:bnakf1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a68e7d655ee83f70d0a8c11dbe1299992cd19ac/pkg/util/log/clog.go#L272)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

can we test that the counter gets incremented?
</blockquote></details>

To clarify, is the test just to confirm that `IncrementCounter` is called here? Or do you wish to see the functionality within `IncrementCounter` tested?

If the latter, we have unit tests for this here: https://github.com/cockroachdb/cockroach/blob/master/pkg/util/log/logmetrics/metrics_test.go#L22

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111126)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[`pkg/util/log/clog.go` line 271 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111126#-NfBkLtB4QlMVeBO4_1L:-NfG4GrcDlW9vE7AzIMa:bt6azq0) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a68e7d655ee83f70d0a8c11dbe1299992cd19ac/pkg/util/log/clog.go#L271)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Good question - I just threw together a little toy benchmark:

```
func doThing(l *LogMetricsRegistry) {
	work := 0
	for i := 0; i < 100; i++ {
		if l != nil {
			l.IncrementCounter(log.LogMessageCount, 1)
		}
		work++
	}
}

func doThingWithoutConditional(l *LogMetricsRegistry) {
	work := 0
	for i := 0; i < 100; i++ {
		l.IncrementCounter(log.LogMessageCount, 1)
		work++
	}
}

func doThingWithoutConditionalAndCounter() {
	work := 0
	for i := 0; i < 100; i++ {
		work++
	}
}

func BenchmarkCounters(b *testing.B) {
	l := newLogMetricsRegistry()
	b.Run("with conditional and counter increment", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			for i := 0; i < 10; i++ {
				go doThing(l)
			}
		}
	})
	b.Run("without conditional, but with counter increment", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			for i := 0; i < 10; i++ {
				go doThingWithoutConditional(l)
			}
		}
	})
	b.Run("without conditional and no counter increment", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			for i := 0; i < 10; i++ {
				go doThingWithoutConditionalAndCounter()
			}
		}
	})
}
```

Here are the results:
```
BenchmarkCounters
BenchmarkCounters/with_conditional_and_counter_increment
BenchmarkCounters/with_conditional_and_counter_increment-10         	   19623	    159938 ns/op
BenchmarkCounters/without_conditional,_but_with_counter_increment
BenchmarkCounters/without_conditional,_but_with_counter_increment-10         	   10000	    104556 ns/op
BenchmarkCounters/without_conditional_and_no_counter_increment
BenchmarkCounters/without_conditional_and_no_counter_increment-10            	  498702	      2315 ns/op
```

...That's quite a big performance hit :grimacing:. 

This makes me thing we should just drop this metric from the PR... I don't think the performance hit would be as drastic in the actual `outputLogEntry`, since it's doing a lot more than just incrementing a counter, but I don't think the value added here justifies a slower hot path for logging.

What do you think?
</blockquote></details>

Your benchmark is flawed.
1. That `go` statement in there is what is killing your performance. 
2. don't do a `for` loop in your `doXXX` functions. Let the benchmark loops do it. In fact, avoid the 2 nested loops in the benchmarks and stick to the iteration over `1..b.N`. The bench framework will adjust N automatically.

once you have simplified the benchmark, let's see how the results compare. I'm expecting something more reasonable.

**Comment by knz** [comment]
Not quite yet -- as written, there's no guarantee that the same number of goroutines will be running by the time wg.Wait runs. That's because `wg.Add` should not be called from within the goroutine code -- there's no guarantee it runs at all before wg.Wait starts.

Try this:
```go
func BenchmarkCountersWithoutConditionalAndCounter(b *testing.B) {
	doWork := make(chan struct{})
	done := make(chan struct{})
	wg := &sync.WaitGroup{}

	doThingWithoutConditionalAndCounter := func() {
		for {
			select {
			case <-doWork:
				i := 0
				i++
			case <-done:
				return
			}
		}
	}

	for i := 0; i < 10; i++ {
		wg.Add(1)
		go doThingWithoutConditionalAndCounter()
	}

		for i := 0; i < b.N; i++ {
			doWork <- struct{}{}
		}
        close(done)
		wg.Wait()
}
```

(also no need for a sub-test)

**Comment by abarganier** [comment]
Thanks for the tweaks @knz - 3rd time's a charm? 😄 

Here are the results given your suggestions:
```
BenchmarkCounters
BenchmarkCounters-10    	 2972420	       406.7 ns/op
BenchmarkCountersWithoutConditional
BenchmarkCountersWithoutConditional-10    	 3013413	       395.9 ns/op
BenchmarkWithoutConditionalAndCounter
BenchmarkWithoutConditionalAndCounter-10    	 3408507	       350.8 ns/op
```

This demonstrates a **15% hit to performance**. Again, I imagine the actual performance hit will be less significant as the real function's runtime involves a lot more than just incrementing an integer.

So to summarize, if we keep this metric, we get easy observability into log volume (perhaps for the first time ever?). The cost is a bit of a performance hit.

If we're not okay paying this cost, we can reduce the contention around the counters a bit by giving each log channel its own metric. Or, we can ditch the idea altogether.

@knz @dhartunian what do y'all think?

**Comment by knz** [comment]
> This demonstrates a 15% hit to performance. 

More specifically, it corresponds to an extra 0.1µs per log call.

Given the overall density of log calls (less than 100 per second on healthy clusters), this means the overhead is really 100 x 1µs / 1s = 0.00005%. 

We can afford that.

**Review by knz — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, 2 of 5 files at r5, 4 of 4 files at r7, 3 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111126)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)

___
*[`docs/generated/metrics/metrics.html` line 1470 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111126#-NfH_3sz6t0A4h_fA8wF:-NfH_3sz6t0A4h_fA8wG:b804qlj) ([raw file](https://github.com/cockroachdb/cockroach/blob/4988746bee73b8dcf683f1480a3261e9af486b32/docs/generated/metrics/metrics.html#L1470)):*
> ```HTML
> <tr><td>SERVER</td><td>build.timestamp</td><td>Build information</td><td>Build Time</td><td>GAUGE</td><td>TIMESTAMP_SEC</td><td>AVG</td><td>NONE</td></tr>
> <tr><td>SERVER</td><td>go.scheduler_latency</td><td>Go scheduling latency</td><td>Nanoseconds</td><td>HISTOGRAM</td><td>NANOSECONDS</td><td>AVG</td><td>NONE</td></tr>
> <tr><td>SERVER</td><td>log.fluent.sink.conn.errors</td><td>Number of connection errors experienced by fluent-server logging sinks</td><td>fluent-server log sink connection errors</td><td>COUNTER</td><td>COUNT</td><td>AVG</td><td>NON_NEGATIVE_DERIVATIVE</td></tr>
> ```

You might want to double check that you're regenerating this file properly in both r2 and r3. It seems to me that an update here really belongs to the previous commit.

Alternatively, you can also squash them together.
___
*[`pkg/util/log/clog.go` line 269 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/111126#-NfH_gif3mEVzrXxrumn:-NfH_gif3mEVzrXxrumo:bs19f3p) ([raw file](https://github.com/cockroachdb/cockroach/blob/0190f15d22d735e834bd1f787600699fea741a8c/pkg/util/log/clog.go#L269)):*
> ```Go
> 	// NB: Generally, we don't need to make this nil check. However, logging.metrics
> 	// is injected from an external package's init() function, but this code path
> 	// can be exercised via pkg/util/log's *own* init() function, which is called first.
> ```

how so? do you have a stack trace? I'd be more interested in makign this non-nil in all cases to reduce complexity.
___
*[`pkg/util/log/logmetrics/metrics.go` line 114 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/111126#-NfH_puP2beC9Ic5r92H:-NfH_puP2beC9Ic5r92I:b-mbrq3r) ([raw file](https://github.com/cockroachdb/cockroach/blob/0190f15d22d735e834bd1f787600699fea741a8c/pkg/util/log/logmetrics/metrics.go#L114)):*
> ```Go
> 	l.mu.counters[log.MetricName(FluentSinkConnErrors.Name)] = l.mu.metricsStruct.FluentSinkConnErrors
> 	l.mu.counters[log.MetricName(BufferedSinkMessagesDropped.Name)] = l.mu.metricsStruct.BufferedSinkMessagesDropped
> 	l.mu.counters[log.MetricName(LogMessageCount.Name)] = l.mu.metricsStruct.LogMessageCount
> ```

If you fully care about performance, an alternative to the overhead of a by-string map lookup is to:
1. make this a slice
2. create an enum that mirrors the counters
3. use the enum in the increment API
4. look up the metric by a simple slice index operation

**Comment by abarganier** [comment]
Thanks for the feedback. I'll address soon.

Introducing `log.messages.count` created a deadlock with the `LogMetrics` mutex, which I spent time tracking down & fixing. With that fixed, I can address the rest of the feedback.

**Review by abarganier — COMMENTED** [review]
Thanks for the feedback - RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111126#-:-NfNWJOE00gpgsqILSUj:b-d0douj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @knz)

___
*[`docs/generated/metrics/metrics.html` line 1470 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111126#-NfH_3sz6t0A4h_fA8wF:-NfNUTN_9q6iRIFE-E9m:barc8q4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4988746bee73b8dcf683f1480a3261e9af486b32/docs/generated/metrics/metrics.html#L1470)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

You might want to double check that you're regenerating this file properly in both r2 and r3. It seems to me that an update here really belongs to the previous commit.

Alternatively, you can also squash them together.
</blockquote></details>

Thanks for catching - I went ahead and regenerated properly for each commit. 
___
*[`pkg/util/log/clog.go` line 271 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111126#-NfBkLtB4QlMVeBO4_1L:-NfNUYfu-bJl2sCRvgON:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a68e7d655ee83f70d0a8c11dbe1299992cd19ac/pkg/util/log/clog.go#L271)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Your benchmark is flawed.
1. That `go` statement in there is what is killing your performance. 
2. don't do a `for` loop in your `doXXX` functions. Let the benchmark loops do it. In fact, avoid the 2 nested loops in the benchmarks and stick to the iteration over `1..b.N`. The bench framework will adjust N automatically.

once you have simplified the benchmark, let's see how the results compare. I'm expecting something more reasonable.
</blockquote></details>

Done.
___
*[`pkg/util/log/clog.go` line 269 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/111126#-NfH_gif3mEVzrXxrumn:-NfNUZax2WIBoO2ks2bS:bzfkm6g) ([raw file](https://github.com/cockroachdb/cockroach/blob/0190f15d22d735e834bd1f787600699fea741a8c/pkg/util/log/clog.go#L269)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

how so? do you have a stack trace? I'd be more interested in makign this non-nil in all cases to reduce complexity.
</blockquote></details>

I'm not aware of how we can possibly do this, given order of initialization. LMK if I'm overlooking something. I'll explain my thinking below.

The `LogMetricsRegistry` is injected into `pkg/util/log` via `pkg/util/log/logmetrics`. `pkg/util/log` is the one that's imported, so it has to be initialized first. As long as *any* logging call can be made within one of `pkg/util/log`'s own `init()` functions before `pkg/util/log/logmetrics` injects `LogMetricsRegistry`, this nil possibility exists.

For the other metrics (buffered sink msg dropped, fluent conn errors), a way to exercise those code paths during `init()` doesn't exist, since these structures are only initialized *after* the customer's log config file is applied. Of course, if we some day changed our barebones default log config to include one of these, we could end up exercising these code paths within an `init()` logging call and hit this `nil` case.

I'm thinking we should define a package-level function within `pkg/util/log` with the same API that gets used, instead of using `logging.metrics` directly. We can make the nil check there, and then callers never have to think about it. Thoughts? 
___
*[`pkg/util/log/logmetrics/metrics.go` line 114 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/111126#-NfH_puP2beC9Ic5r92H:-NfNUMws0i01Df6Dn_AI:b-hs2p7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/0190f15d22d735e834bd1f787600699fea741a8c/pkg/util/log/logmetrics/metrics.go#L114)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

If you fully care about performance, an alternative to the overhead of a by-string map lookup is to:
1. make this a slice
2. create an enum that mirrors the counters
3. use the enum in the increment API
4. look up the metric by a simple slice index operation
</blockquote></details>

Good idea - added a commit to the end that changes `LogMetricsRegistry` to work this way.

**Review by knz — COMMENTED** [review]
> Reviewed 9 of 9 files at r12, 2 of 2 files at r13, 1 of 1 files at r14, 2 of 2 files at r15, 5 of 5 files at r16, 4 of 4 files at r17, 5 of 5 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111126)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)

___
*[`pkg/util/log/clog.go` line 269 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/111126#-NfH_gif3mEVzrXxrumn:-NfQtzPY5NuguhBhh6au:bxnuphz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0190f15d22d735e834bd1f787600699fea741a8c/pkg/util/log/clog.go#L269)):*
> As long as _any_ logging call can be made within one of `pkg/util/log`'s own `init()` functions

yes I understand the cause effect relationship. I am just wondering why are there logging calls made in init code? I thought we got rid of that?
Have you observed this code failing due to the nil ptr? When it failed, what was the stack trace?
___
*[`pkg/util/log/logmetrics/metrics.go` line 143 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/111126#-NfQuOz6CIR7Y6rj4PeZ:-NfQuOz6CIR7Y6rj4Pe_:b-4cqbud) ([raw file](https://github.com/cockroachdb/cockroach/blob/74bc8392d37acf0d1365314da5859bc4260e452c/pkg/util/log/logmetrics/metrics.go#L143)):*
> ```Go
> 	l.mu.Lock()
> 	defer l.mu.Unlock()
> 	if metric < 0 || len(l.mu.counters) <= int(metric) {
> ```

the go runtime already does this check for you. no need to add extra code.

**Review by abarganier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111126)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @knz)

___
*[`pkg/util/log/clog.go` line 269 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/111126#-NfH_gif3mEVzrXxrumn:-NfQx2QI06J3pE2FizU_:bd81f8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/0190f15d22d735e834bd1f787600699fea741a8c/pkg/util/log/clog.go#L269)):*
> yes I understand the cause effect relationship.

Ack, sorry if that came across as patronizing at all!

> I thought we got rid of that?

I think we did (assuming you're referring to https://github.com/cockroachdb/cockroach/pull/109901), but that doesn't mean some dev in the future can't reintroduce a stray logging call called somehow via `init()`. This nil check was meant to be defensive against such a case. I don't have a stack trace, I just added this check based on what we experienced in https://github.com/cockroachdb/cockroach/issues/109900.

I can see why panicking if `logging.metrics` is `nil` might be better. It would help protect against folks introducing more logging calls into `init()`. 

Would you prefer an explicit panic for such a thing? e.g. `if logging.metrics == nil { panic() }`? Or should we just ditch the nil check and let the nil pointer dereference trigger the panic? 
___
*[`pkg/util/log/logmetrics/metrics.go` line 143 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/111126#-NfQuOz6CIR7Y6rj4PeZ:-NfQzUGcBagfp_7e-xnh:b7wr4pg) ([raw file](https://github.com/cockroachdb/cockroach/blob/74bc8392d37acf0d1365314da5859bc4260e452c/pkg/util/log/logmetrics/metrics.go#L143)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

the go runtime already does this check for you. no need to add extra code.
</blockquote></details>

Oops - removed the `< 0` check.

**Review by knz — COMMENTED** [review]
> Reviewed 2 of 2 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111126)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)

___
*[`pkg/util/log/clog.go` line 269 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/111126#-NfH_gif3mEVzrXxrumn:-Nfl70V49QBvtL449c12:by0q1zw) ([raw file](https://github.com/cockroachdb/cockroach/blob/0190f15d22d735e834bd1f787600699fea741a8c/pkg/util/log/clog.go#L269)):*
> Ack, sorry if that came across as patronizing at all!

it did not! I just wanted to clarify where I was coming from.

> but that doesn't mean some dev in the future can't reintroduce a stray logging call called somehow via `init()`.

This would most definitely be a bug/regression. I wish for these regressions to be caught during CI, before they make it to a release.

> Or should we just ditch the nil check and let the nil pointer dereference trigger the panic?

Since the go runtime already does the panic call for you, adding another one looks like more work.
___
*[`pkg/util/log/logmetrics/metrics.go` line 143 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/111126#-NfQuOz6CIR7Y6rj4PeZ:-Nfl6nr09u0A-SyPDQeA:bw0hbjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/74bc8392d37acf0d1365314da5859bc4260e452c/pkg/util/log/logmetrics/metrics.go#L143)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Oops - removed the `< 0` check.
</blockquote></details>

ditto `metric >= len(l.mu.counters)` - go will panic for you if the value doesn't work.

**Review by abarganier — COMMENTED** [review]
Thanks @knz - ready for another look :thumbsup: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111126#-:-NflDCZzA37FXsFpjuUQ:b-kg8dpq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @knz)

___
*[`pkg/util/log/clog.go` line 269 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/111126#-NfH_gif3mEVzrXxrumn:-NflBoKUEjUJKn7V0nKU:b-9qq3tu) ([raw file](https://github.com/cockroachdb/cockroach/blob/0190f15d22d735e834bd1f787600699fea741a8c/pkg/util/log/clog.go#L269)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

> Ack, sorry if that came across as patronizing at all!

it did not! I just wanted to clarify where I was coming from.

> but that doesn't mean some dev in the future can't reintroduce a stray logging call called somehow via `init()`.

This would most definitely be a bug/regression. I wish for these regressions to be caught during CI, before they make it to a release.

> Or should we just ditch the nil check and let the nil pointer dereference trigger the panic?

Since the go runtime already does the panic call for you, adding another one looks like more work.
</blockquote></details>

Sounds good! Removed the conditional here. 
___
*[`pkg/util/log/logmetrics/metrics.go` line 143 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/111126#-NfQuOz6CIR7Y6rj4PeZ:-NflBmGJE7qERygpjM6Q:bk2szb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/74bc8392d37acf0d1365314da5859bc4260e452c/pkg/util/log/logmetrics/metrics.go#L143)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

ditto `metric >= len(l.mu.counters)` - go will panic for you if the value doesn't work.
</blockquote></details>

Ack - removed the conditional altogether

**Review by knz — APPROVED** [review]
Nice

> Reviewed 1 of 9 files at r20, 2 of 5 files at r25, 2 of 4 files at r26, 5 of 5 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111126#-:-NflFqad2jE4oBEgGNZl:bb70w76)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

**Comment by abarganier** [comment]
TFTR! 

bors r=knz

**Pull request merged**
