### PR TITLE
sql,tree: improve function resolution efficiency

### PR DESCRIPTION
**Pull request by ajwerner**
#### sql: prevent allocations by avoiding some name pointers

We don't need pointers for these names. They generally won't escape.

#### sql,tree: change SearchPath to avoid allocations
The closure-oriented interface was forcing the closures and the variables they
referenced to escape to the heap. This change, while not beautiful, ends up being
much more efficient.

```
name                                         old time/op    new time/op    delta
SQL/MultinodeCockroach/Upsert/count=1000-16    20.4ms ±11%    18.9ms ± 8%   -7.47%  (p=0.000 n=20+19)

name                                         old alloc/op   new alloc/op   delta
SQL/MultinodeCockroach/Upsert/count=1000-16    10.1MB ±29%     9.8MB ±29%     ~     (p=0.231 n=20+20)

name                                         old allocs/op  new allocs/op  delta
SQL/MultinodeCockroach/Upsert/count=1000-16     56.3k ± 7%     50.2k ±10%  -10.81%  (p=0.000 n=19+19)
```

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
See https://github.com/cockroachdb/cockroach/pull/85391#issuecomment-1266319706

**Comment by chengxiong-ruan** [comment]
:lgtm_strong: many thanks!

**Review by chengxiong-ruan — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89317#-:-NDZOEzFCLhaIts6PFd_:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Comment by ajwerner** [comment]
https://github.com/cockroachdb/cockroach/pull/89335

bors r+

**Pull request merged**
