### PR TITLE
sql: add and link Postgres type i/o builtins

### LINKED ISSUE #12526: sql: list the conversion functions in pg_type
Reported in https://github.com/cockroachdb/cockroach/issues/5582#issuecomment-268504183:

Explained further in https://github.com/cockroachdb/cockroach/issues/5582#issuecomment-268516185

The columns "typsend" "typreceive" etc should list the names of conversion functions to/from that data type.

Although we do not support these functions yet it would be useful to fill the columns with the names of these functions nonetheless, so that the client application can do something useful with them (e.g. in the case of Postgrex, run client-side callbacks with the same names).

### PR DESCRIPTION
**Pull request by jordanlewis**
In Postgres, every type has 4 i/o builtins that correspond to it. For `int8`, for instance, there's `int8in`, `int8out`, `int8send`, and `int8recv`. We implement these as no-op builtins for ORM compatibility.

Additionally, we link these builtins to their corresponding fields in `pg_type` for all types.

Also, fix the name in `pg_type` for our `Tuple` type, which is called `record` in Postgres.

Fixes #12526.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14529)

### CODE REVIEW

**Comment by knz** [comment]
Woo, so many thanks for tackling this.
Two nits remaining though.

---

Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/pg_builtins.go, line 36 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14529#-KgdWeeTBphkNtpGRLoI:-KgdWeeV7dqWPZCa-_Ao:b-ba3rni) ([raw file](https://github.com/cockroachdb/cockroach/blob/7be5e84efc7c312331008629aebb7a4e5b6f1f70/pkg/sql/parser/pg_builtins.go#L36)):*
> ```Go
> // programmatically determine whether or not this underscore is present, hence
> // the existence of this map.
> var typeBuiltinsHaveUnderscore = map[oid.Oid]bool{
> ```

`map[oid.Oid]struct{}{ ... }`

---

*[pkg/sql/parser/pg_builtins.go, line 91 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14529#-KgdWuna1sI-jweF_Syr:-KgdWuna1sI-jweF_Sys:b-f3346s) ([raw file](https://github.com/cockroachdb/cockroach/blob/7be5e84efc7c312331008629aebb7a4e5b6f1f70/pkg/sql/parser/pg_builtins.go#L91)):*
> ```Go
> 	return map[string][]Builtin{
> 		builtinPrefix + "send": {
> 			Builtin{
> ```

I'd make a function returning a `Builtin` that takes just the desired return type and argument type as arguments, to construct the four things.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14529#-:-KgdXABALiOxsqzTPvOt:b7upevv)*

**Comment by jordanlewis** [comment]
TFTR!

---

Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/parser/pg_builtins.go, line 36 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14529#-KgdWeeTBphkNtpGRLoI:-KgeNgXW8io5LRPTl98V:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7be5e84efc7c312331008629aebb7a4e5b6f1f70/pkg/sql/parser/pg_builtins.go#L36)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`map[oid.Oid]struct{}{ ... }`
</blockquote></details>

Done.

---

*[pkg/sql/parser/pg_builtins.go, line 91 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14529#-KgdWuna1sI-jweF_Syr:-KgeNhZVWchL5zUimBhM:b-sizqs0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7be5e84efc7c312331008629aebb7a4e5b6f1f70/pkg/sql/parser/pg_builtins.go#L91)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I'd make a function returning a `Builtin` that takes just the desired return type and argument type as arguments, to construct the four things.
</blockquote></details>

good call. done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14529#-:-KgeNfR5W7m_Wovu-s9w:b-814g8k)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r3, 3 of 3 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14529#-:-KgflX9uZUAoO_YLe_z-:bnfp4nl)*

**Comment by nvanbenschoten** [comment]
Late to the game, but this is great! Really nice job.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/pg_catalog.go, line 1462 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14529#-KgnB-7wh51ie3l8jwfD:-KgnB-7wh51ie3l8jwfE:blgnh41) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7900cd9bf5763cac1a1aced4ac05da849a274e3/pkg/sql/pg_catalog.go#L1462)):*
> ```Go
> 				h.RegProc(builtinPrefix+"in"),   // typinput
> 				h.RegProc(builtinPrefix+"out"),  // typoutput
> 				h.RegProc(builtinPrefix+"recv"), // typrecv
> ```

nit: Why did this comment get changes? The column is `typreceive`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14529#-:-KgnASdzjoPzoaPyTd5t:b1qs9pv)*

**Pull request merged**
