### PR TITLE
tenantcapabilities: restructure interfaces

### PR DESCRIPTION
**Pull request by ajwerner**
This commit is mostly just a refactoring of what we have. The previous iteration had some unfortunate coupling between the protobufs and the top-level package. Having the protobuf generated code not be a leaf hurts.

Another pain point was the lack of strong typing when interacting with capabilities. Given this is go, somewhere there's a need to do some type assertion when dealing sets of variant instance types.

The biggest change is that the `TenantCapabilities` concept is no longer wrapped in an interface implemented by the protobuf. Instead, the `Capability` implementations now live inside the `tenantcapabilities` package, and can be looked up with `FromName` and `FromID`, without any access to concrete capabilities. These capabilies then know how to look up values in a strongly typed way from the concrete capabilities.

Epic: none

Release note: None

### CODE REVIEW

**Review by arulajmani — APPROVED** [review]
This is a great simplification, I love where this ended up -- nice parting gift indeed. Thanks for taking the time to refactor this stuff.

> Reviewed 51 of 53 files at r1, 8 of 8 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100217#-:-NRojnzjAuIwCKj-QrXb:b-rxcudf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[`-- commits` line 6 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/100217#-NRojcOA-wCABz5FjA70):*
> Having the protobuf generated code not be a leaf hurts.

Heavy +1. 
___
*[`pkg/multitenant/tenantcapabilities/value.go` line 71 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/100217#-NRocTgd4PNyfTkr7aZt:-NRocTgd4PNyfTkr7aZu:b-d5osqa) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a9174899960d61e8a492830fc4b4d7cb72fe599/pkg/multitenant/tenantcapabilities/value.go#L71)):*
> ```Go
> 
> type spanConfigBoundsValue struct {
> 	b **tenantcapabilitiespb.SpanConfigBounds
> ```

nit: could you add a comment explaining why a pointer to a pointer (as opposed to just a pointer) here?
___
*[`pkg/multitenant/tenantcapabilities/value.go` line 74 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/100217#-NRobxOY4qlbxGhTf2LN:-NRobxOY4qlbxGhTf2LO:b1xur1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a9174899960d61e8a492830fc4b4d7cb72fe599/pkg/multitenant/tenantcapabilities/value.go#L74)):*
> ```Go
> }
> 
> func (s *spanConfigBoundsValue) Get() *spanconfigbounds.Bounds {
> ```

I like the fact that we're returning `spanconfigbounds.Bounds` right here, instead of having to convert it in the `spanconfig` package. I had found myself wrestling with the package structure here initially, so I'm a solid :100: on this (and the reorganization you've done here, in general). 
___
*[`pkg/multitenant/tenantcapabilities/values.go` line 20 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/100217#-NRofgNO8K2DIt-_15OT:-NRofgNO8K2DIt-_15OU:bc9rlfk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0172db8bd5aad2e20d4794f8c1f096cc3d00490a/pkg/multitenant/tenantcapabilities/values.go#L20)):*
> ```Go
> // MustGetValueByID will get the value for the capability corresponding to
> // the requested ID. If the ID is not valid, this function will panic.
> func MustGetValueByID(t *tenantcapabilitiespb.TenantCapabilities, id ID) Value {
> ```

Instead of both this and `GetValueByID`, consider just having the latter and letting that thing panic if need be. Looks like we're only ever using the version that panics in production anyway, so not having two options here will be one less question future visitors will have to ask when they see this code. 
___
*[`pkg/spanconfig/spanconfigbounds/span_config_bounds.go` line 26 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/100217#-NRod6ey-RUJwB-EH4Eb:-NRod6ey-RUJwB-EH4Ec:b-dz6qkr) ([raw file](https://github.com/cockroachdb/cockroach/blob/56bb0027e990b408b629d281089f279b1569cab8/pkg/spanconfig/spanconfigbounds/span_config_bounds.go#L26)):*
> ```Go
> // policy to interact with SpanConfigs.
> type Bounds struct {
> 	b *tenantcapabilitiespb.SpanConfigBounds
> ```

Slightly curious why you had this wrapping before but decided to change it. 
___
*[`pkg/spanconfig/spanconfigstore/bounds_reader.go` line 11 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/100217#-NRodRtL67LPowv871sn:-NRodRtL67LPowv871so:bc663xk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0172db8bd5aad2e20d4794f8c1f096cc3d00490a/pkg/spanconfig/spanconfigstore/bounds_reader.go#L11)):*
> ```Go
> // licenses/APL.txt.
> 
> package spanconfigstore
> ```

Was the package move motivated by not wanting to import `spanconfigbounds` into `KVSubscriber`? Or was there more to it? 
___
*[`pkg/multitenant/tenantcapabilities/values_test.go` line 20 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/100217#-NRohB7O9fpCdescjMz0:-NRohB7O9fpCdescjMz1:b2nbrfr) ([raw file](https://github.com/cockroachdb/cockroach/blob/56bb0027e990b408b629d281089f279b1569cab8/pkg/multitenant/tenantcapabilities/values_test.go#L20)):*
> ```Go
> )
> 
> func TestCapabilityGetSet(t *testing.T) {
> ```

This test wasn't great, but do you think it's worth keeping around a `TestCapabilitiesGetSet` test albeit more useful? 

Mostly in the context of span config bounds -- should we add something that uses Set to alter span config bounds and then makes sure the underlying proto is indeed modified using a `Get`? Your call on whether it's worth having.

**Review by ajwerner — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100217#-:-NRomlfU9R2zMK0fc4GM:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`-- commits` line 6 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/100217#-NRojcOA-wCABz5FjA70):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

> Having the protobuf generated code not be a leaf hurts.

Heavy +1. 
</blockquote></details>

Done.
___
*[`pkg/multitenant/tenantcapabilities/value.go` line 71 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/100217#-NRocTgd4PNyfTkr7aZt:-NRols5o0QMnS5_ejsMG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a9174899960d61e8a492830fc4b4d7cb72fe599/pkg/multitenant/tenantcapabilities/value.go#L71)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: could you add a comment explaining why a pointer to a pointer (as opposed to just a pointer) here?
</blockquote></details>

Done.
___
*[`pkg/multitenant/tenantcapabilities/values.go` line 20 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/100217#-NRofgNO8K2DIt-_15OT:-NRolu6L5oe-q9SHYUOz:b-3komkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/0172db8bd5aad2e20d4794f8c1f096cc3d00490a/pkg/multitenant/tenantcapabilities/values.go#L20)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Instead of both this and `GetValueByID`, consider just having the latter and letting that thing panic if need be. Looks like we're only ever using the version that panics in production anyway, so not having two options here will be one less question future visitors will have to ask when they see this code. 
</blockquote></details>

"in production" :thinking: we haven't shipped this code. I don't love the idea of panics that can happen with a malformed number. I'm inclined to not do that. 
___
*[`pkg/spanconfig/spanconfigbounds/span_config_bounds.go` line 26 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/100217#-NRod6ey-RUJwB-EH4Eb:-NRom3U78uaAfA-j_rWd:b91giow) ([raw file](https://github.com/cockroachdb/cockroach/blob/56bb0027e990b408b629d281089f279b1569cab8/pkg/spanconfig/spanconfigbounds/span_config_bounds.go#L26)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Slightly curious why you had this wrapping before but decided to change it. 
</blockquote></details>

:shrug: I wasn't seeing the value in the wrapping.
___
*[`pkg/spanconfig/spanconfigstore/bounds_reader.go` line 11 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/100217#-NRodRtL67LPowv871sn:-NRom8Ti02fsf4LvnV9I:b2af1yv) ([raw file](https://github.com/cockroachdb/cockroach/blob/0172db8bd5aad2e20d4794f8c1f096cc3d00490a/pkg/spanconfig/spanconfigstore/bounds_reader.go#L11)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Was the package move motivated by not wanting to import `spanconfigbounds` into `KVSubscriber`? Or was there more to it? 
</blockquote></details>

It was to avoid a cycle. This interface depends on `tenantcapabilities` and `tenantcapabilities` now depends on `spanconfigbounds` so this couldn't live in `spanconfigbounds`. 
___
*[`pkg/multitenant/tenantcapabilities/values_test.go` line 20 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/100217#-NRohB7O9fpCdescjMz0:-NRomOZn7lQPzEEd-1d6:b-mwna4k) ([raw file](https://github.com/cockroachdb/cockroach/blob/56bb0027e990b408b629d281089f279b1569cab8/pkg/multitenant/tenantcapabilities/values_test.go#L20)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

This test wasn't great, but do you think it's worth keeping around a `TestCapabilitiesGetSet` test albeit more useful? 

Mostly in the context of span config bounds -- should we add something that uses Set to alter span config bounds and then makes sure the underlying proto is indeed modified using a `Get`? Your call on whether it's worth having. 
</blockquote></details>

I'll do it in the follow-up PR which integrates `SpanConfigBounds`.

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100217)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/multitenant/tenantcapabilities/values_test.go` line 20 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/100217#-NRohB7O9fpCdescjMz0:-NRpvWSO3I68dUtTjmq2:bnpyhts) ([raw file](https://github.com/cockroachdb/cockroach/blob/56bb0027e990b408b629d281089f279b1569cab8/pkg/multitenant/tenantcapabilities/values_test.go#L20)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I'll do it in the follow-up PR which integrates `SpanConfigBounds`.
</blockquote></details>

I added it back

**Review by knz — COMMENTED** [review]
> Reviewed 41 of 53 files at r1, 5 of 8 files at r2, 2 of 2 files at r4, 5 of 6 files at r5, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100217)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiestestutils/testutils.go` line 79 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/100217#-NRrJ_Z52rgryv8TWutH:-NRrJ_Z52rgryv8TWutI:b-q6g676) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e75cfaa098fba1a6b55089d3a7c71f985b270f0/pkg/multitenant/tenantcapabilities/tenantcapabilitiestestutils/testutils.go#L79)):*
> ```Go
> 				return roachpb.TenantID{}, nil, err
> 			}
> 			c.Value(&caps).Set(spanconfigbounds.New(&v))
> ```

I'm missing a `default` case here.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100217)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiestestutils/testutils.go` line 79 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/100217#-NRrJ_Z52rgryv8TWutH:-NRrfhz06Mgh6in7SjCZ:b-wwm31x) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e75cfaa098fba1a6b55089d3a7c71f985b270f0/pkg/multitenant/tenantcapabilities/tenantcapabilitiestestutils/testutils.go#L79)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I'm missing a `default` case here.
</blockquote></details>

https://github.com/cockroachdb/cockroach/pull/100294

**Pull request merged**
