### PR TITLE
distsql external sort API improvements

### PR DESCRIPTION
**Pull request by madelynnblue**
When trying to use this for the upcoming distributed CSV stuff, these were the two biggest improvements I saw that needed to be made. They increase safety and ease external use.

### CODE REVIEW

**Comment by asubiotto** [comment]
Thanks for the changes. I think the tempStorageID work in distsql land still has to be cleaned up (e.g. `tempStorageIDGenerator` on the `flowCtx`). Maybe that just has to be renamed though because having processor IDs will be useful for other things (e.g. debugging). @arjunravinarayan, what do you think?

---

Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/disk_map.go, line 285 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164#-Kpa6CfKOvPcYFJMaJoC:-Kpa6CfKOvPcYFJMaJoD:btuga15) ([raw file](https://github.com/cockroachdb/cockroach/blob/4189b36d0321a4562407fa40a5885585118dd17c/pkg/sql/distsqlrun/disk_map.go#L285)):*
> ```Go
> 	err := b.Flush()
> 	if err != nil {
> 		log.Warning(ctx, errors.Wrapf(err, "batch writer could not be flushed on close"))
> ```

Is the log message worth keeping?

---

*[pkg/sql/distsqlrun/disk_map.go, line 142 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164#-Kpa6jvDD1M_gBzct-Lk:-Kpa6jvDD1M_gBzct-Ll:b-dfazcp) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c09b6de33c2453c7a095f956629a0b76a3d4234/pkg/sql/distsqlrun/disk_map.go#L142)):*
> ```Go
> var _ SortedDiskMap = &RocksDBMap{}
> 
> // tempIDGenerator is the temp ID generator for a node. Although it is possible
> ```

This comment is a bit confusing. I would just explain why this generator is necessary then have the optimization as a TODO.

---

*[pkg/sql/distsqlrun/disk_map.go, line 151 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164#-Kpa6YGSrE6Yu0ESQj7t:-Kpa6YGSrE6Yu0ESQj7u:b-dlhing) ([raw file](https://github.com/cockroachdb/cockroach/blob/1abba2945329b627280c3bcd789d3ac8a96a83de/pkg/sql/distsqlrun/disk_map.go#L151)):*
> ```Go
> 	// []byte{0xff, ..., 0xff} for which there is no end key, thus deleting
> 	// nothing.
> 	if prefix == math.MaxUint64 {
> ```

I think this check still needs to be performed, right?

---

*[pkg/sql/distsqlrun/disk_map_test.go, line 53 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164#-Kpa4b135dcwFUm4tIZf:-Kpa4b135dcwFUm4tIZg:b59pb2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4189b36d0321a4562407fa40a5885585118dd17c/pkg/sql/distsqlrun/disk_map_test.go#L53)):*
> ```Go
> 
> 	batchWriter := diskMap.NewBatchWriterCapacity(64)
> 	defer func() { _ = batchWriter.Close(ctx) }()
> ```

Maybe use a `t.Error` here instead of ignoring the error in all cases.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164#-:-Kpa7IGJKj3QIQnbiIcq:b797h9s)*

**Comment by arjunravinarayan** [comment]
LGTM commit 1, I don't understand the purpose of commit 2. I preferred things when there wasn't a global. Also, if we use the temp-storage outside of DistSQL land, how is it being a global inside DistSQL a good thing? Not clear to me the global pattern is an improvement - can you tell me more?

---

Reviewed 3 of 3 files at r1.
Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164#-:-KpaLd1TamPsPJsCMjlj:b-jiiyc9)*

**Comment by mjibson** [comment]
Here's why I arrived at the decision for commit 2:

I am working on a distributed mapreduce infra for cockroach. At its core mapreduce is a distributed sort, so I was really excited to use this functionality. Looking at the constructor for the rocksdb here, it needed an engine and a prefix. The engine is created in the server package and passed down to distsql, so it was easy to give the correct tempstorage engine to the mapreduce stuff. However getting a good prefix was not easy to pass down to mapreduce, because it was created (and not exported) in the distsql package. But the mapreduce stuff, since it was using the same tempstorage engine, needed to guarantee that it would generate prefixes unique to the engine it was using. So, we have an engine created in server and a tempid generator created in distsql, but they are coupled. Instead of exporting the tempid generator or generating it in the server package, I thought it would be easiest (that is, to users of this new external sort thing) to just be able to hand it an engine, and then bam it works. The prefix being a global means that noone ever has to care about it again.

I do indeed think all of the external sort stuff should live outside of distsql, since it has a wider appeal, and I think when we move it there, then the global ID generator will also go there.

I'm not aware of any arguments FOR being able to specify the prefix in the constructor. It feels like a giant footgun, because if someone decides "oh hey, a nice sorting package, i'll just pass it 0 or make myself a new temp id generator", then that could conflict with the work being done by distsql. I can't see any argument for the usefulness of being able to specify the same prefix twice, and only problems if we do. So why not remove it.

Make sense? Or do we need a hangout?

---

Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/disk_map.go, line 285 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164#-Kpa6CfKOvPcYFJMaJoC:-KpaZTey4QViLELCvrf3:b-2t9odr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4189b36d0321a4562407fa40a5885585118dd17c/pkg/sql/distsqlrun/disk_map.go#L285)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is the log message worth keeping?
</blockquote></details>

I guess if we're returning the error now then no, it's not. Removed.

---

*[pkg/sql/distsqlrun/disk_map.go, line 142 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164#-Kpa6jvDD1M_gBzct-Lk:-KpaZ50mZOy_WhjCVzYs:b-whwqft) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c09b6de33c2453c7a095f956629a0b76a3d4234/pkg/sql/distsqlrun/disk_map.go#L142)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This comment is a bit confusing. I would just explain why this generator is necessary then have the optimization as a TODO.
</blockquote></details>

The comment describes why the optimization is a bad choice: it adds a nearly useless requirement to the API that is difficult to implement, since it must be a unique generator per rocksdb instance.

---

*[pkg/sql/distsqlrun/disk_map.go, line 151 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164#-Kpa6YGSrE6Yu0ESQj7t:-KpaZLeloD--EDS6JtoK:bdpioq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1abba2945329b627280c3bcd789d3ac8a96a83de/pkg/sql/distsqlrun/disk_map.go#L151)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think this check still needs to be performed, right?
</blockquote></details>

Why? At 1000 new prefixes allocated per second it will take over 500 million years to reach this point.

---

*[pkg/sql/distsqlrun/disk_map_test.go, line 53 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164#-Kpa4b135dcwFUm4tIZf:-KpaZyUcC3CI9J2274V5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4189b36d0321a4562407fa40a5885585118dd17c/pkg/sql/distsqlrun/disk_map_test.go#L53)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Maybe use a `t.Error` here instead of ignoring the error in all cases.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164#-:-Kpa_Rsj-KxocUrh14IY:b-jgk0k4)*

**Comment by asubiotto** [comment]
It makes most sense to me to move `disk_map.go` to `engine`. These changes definitely make the temporary storage instance more usable.

---

Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/distsqlrun/disk_map.go, line 142 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164#-Kpa6jvDD1M_gBzct-Lk:-KpaemxLoKNkv0sCSw7-:b-ijkd1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c09b6de33c2453c7a095f956629a0b76a3d4234/pkg/sql/distsqlrun/disk_map.go#L142)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

The comment describes why the optimization is a bad choice: it adds a nearly useless requirement to the API that is difficult to implement, since it must be a unique generator per rocksdb instance.
</blockquote></details>

Got it. I still think it's confusingly worded. It should also have a sentence explaining its use for RocksDBMap keyspace prefixes.

---

*[pkg/sql/distsqlrun/disk_map_test.go, line 53 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164#-Kpa4b135dcwFUm4tIZf:-KpaglSnl5N4opP7ZRas:b-yi0m70) ([raw file](https://github.com/cockroachdb/cockroach/blob/4189b36d0321a4562407fa40a5885585118dd17c/pkg/sql/distsqlrun/disk_map_test.go#L53)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Since we could potentially be executing this block after a `t.Fatal` has already occurred, is there an issue calling `t.Fatal` again here? This is fine if not.

---

*[pkg/sql/distsqlrun/disk_map_test.go, line 253 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164#-Kpagha57dSIXBkhifm1:-Kpagha57dSIXBkhifm2:bs6qvsh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e3bb730927e0851af8c684249a00b6fa4cbf5b/pkg/sql/distsqlrun/disk_map_test.go#L253)):*
> ```Go
> 					batchWriter := diskMap.NewBatchWriter()
> 					// This Close() flushes writes.
> 					defer func() { _ = batchWriter.Close(ctx) }()
> ```

Here as well

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164#-:-KpaeG4zX94pBoOIY0wj:b-8c4w3i)*

**Comment by RaduBerinde** [comment]
I agree that managing the prefix internally instead of passing it down makes sense.

---

Review status: 0 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/server.go, line 113 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164#-KpalH2d6SSEF2yx_Fud:-KpalH2d6SSEF2yx_Fue:bb9s8rl) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e3bb730927e0851af8c684249a00b6fa4cbf5b/pkg/sql/distsqlrun/server.go#L113)):*
> ```Go
> }
> 
> // tempStorageIDGenerator generates unique IDs for each processor to use as a
> ```

We are now using this type in just one place, we could just use a `uint64` and to the `AddUint64` call directly. If you want to keep it, please move it to disk_map.go where it is used (and remove the reference to "processor" in the comment).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164#-:-Kpal5cnlmEtvxzgTOlr:bhl3bki)*

**Comment by arjunravinarayan** [comment]
Thank you for the detailed explanation. It makes a lot of sense. Thanks for explaining it well.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164#-:-Kpan7GwUsd7knAufJTu:bxhdxd6)*

**Comment by arjunravinarayan** [comment]
:lgtm: modulo outstanding comments! Thank you for cleaning this up!

---

Reviewed 2 of 9 files at r3, 9 of 9 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/server.go, line 113 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164#-KpalH2d6SSEF2yx_Fud:-KpapEeV0HmxP09haW74:btd51a6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e3bb730927e0851af8c684249a00b6fa4cbf5b/pkg/sql/distsqlrun/server.go#L113)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We are now using this type in just one place, we could just use a `uint64` and to the `AddUint64` call directly. If you want to keep it, please move it to disk_map.go where it is used (and remove the reference to "processor" in the comment).
</blockquote></details>

I agree.

---

*[pkg/sql/distsqlrun/sorter.go, line 57 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164#-KpaoCZDQ6xpf-AySmyw:-KpaoCZDQ6xpf-AySmyx:b-w76t5r) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e3bb730927e0851af8c684249a00b6fa4cbf5b/pkg/sql/distsqlrun/sorter.go#L57)):*
> ```Go
> 	// tempStorageID is a unique (to this node) ID prefixed before every row, to
> 	// ensure that this processor's rows do not overlap with any other processors.
> 	tempStorageID uint64
> ```

this needs to go.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164#-:-Kpap5KYgMEYWHCq_u6a:b-mnwdrr)*

**Comment by mjibson** [comment]
I've done the requested cleanup and added a new commit to move disk_map.go to storage/engine. Just mechanical changes, but PTAL.

---

Review status: 0 of 9 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsqlrun/server.go, line 113 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164#-KpalH2d6SSEF2yx_Fud:-KpamU8bZp0ZnUtMfRtq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e3bb730927e0851af8c684249a00b6fa4cbf5b/pkg/sql/distsqlrun/server.go#L113)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We are now using this type in just one place, we could just use a `uint64` and to the `AddUint64` call directly. If you want to keep it, please move it to disk_map.go where it is used (and remove the reference to "processor" in the comment).
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/sorter.go, line 57 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164#-KpaoCZDQ6xpf-AySmyw:-Kpaqar9zNg_L0gEoCX4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e3bb730927e0851af8c684249a00b6fa4cbf5b/pkg/sql/distsqlrun/sorter.go#L57)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

this needs to go.
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/disk_map.go, line 142 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164#-Kpa6jvDD1M_gBzct-Lk:-KpamzLXjXwjGhcyjfA6:b-s8xe6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c09b6de33c2453c7a095f956629a0b76a3d4234/pkg/sql/distsqlrun/disk_map.go#L142)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Got it. I still think it's confusingly worded. It should also have a sentence explaining its use for RocksDBMap keyspace prefixes.
</blockquote></details>

I've rewritten this comment.

---

*[pkg/sql/distsqlrun/disk_map_test.go, line 53 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164#-Kpa4b135dcwFUm4tIZf:-KpakLanINFrfzSmkvb2:b-ahysn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4189b36d0321a4562407fa40a5885585118dd17c/pkg/sql/distsqlrun/disk_map_test.go#L53)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Since we could potentially be executing this block after a `t.Fatal` has already occurred, is there an issue calling `t.Fatal` again here? This is fine if not.
</blockquote></details>

I think this is fine. I looked at the code and t.Fatal calls runtime.Goexit(), which is the thing that runs deferred, and it appears to be aware of this situation.

---

*[pkg/sql/distsqlrun/disk_map_test.go, line 253 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164#-Kpagha57dSIXBkhifm1:-KpaltOxWBLIJkAm5zXw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e3bb730927e0851af8c684249a00b6fa4cbf5b/pkg/sql/distsqlrun/disk_map_test.go#L253)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Here as well
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164#-:-Kpaqc7pAFBGsA-9VZKF:b-5otulr)*

**Comment by asubiotto** [comment]
:lgtm: thanks again!

---

Review status: 0 of 9 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/storage/engine/disk_map.go, line 142 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164#-KpbX0Ez5Q0uCJ0Yj5HF:-KpbX0Ez5Q0uCJ0Yj5HG:be8ha0v) ([raw file](https://github.com/cockroachdb/cockroach/blob/4be81e4f0dd4431a1cacdc4b4ec12632e674bf80/pkg/storage/engine/disk_map.go#L142)):*
> ```Go
> var _ SortedDiskMap = &RocksDBMap{}
> 
> // tempIDGenerator is the temp ID generator for a node. Although it is possible
> ```

Just a heads up that this old version wasn't deleted

---

*[pkg/storage/engine/disk_map.go, line 151 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164#-KpbUf63f2NBg6pp4412:-KpbUf63f2NBg6pp4413:b-s7l0xo) ([raw file](https://github.com/cockroachdb/cockroach/blob/4be81e4f0dd4431a1cacdc4b4ec12632e674bf80/pkg/storage/engine/disk_map.go#L151)):*
> ```Go
> // prefixes for NewRocksDBMap. It is a global because NewRocksDBMap needs to
> // prefix its writes uniquely, and using a global prevents users from having to
> // specify the prefex themselves and correctly guarantee that it is unique.
> ```

s/prefex/prefix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164#-:-KpbWfZHLQht4jsXoI_W:b-d62gbb)*

**Comment by mjibson** [comment]
Review status: 0 of 9 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/storage/engine/disk_map.go, line 142 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164#-KpbX0Ez5Q0uCJ0Yj5HF:-KpcGGUwr_ekJaHxBf1e:bjangf5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4be81e4f0dd4431a1cacdc4b4ec12632e674bf80/pkg/storage/engine/disk_map.go#L142)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Just a heads up that this old version wasn't deleted
</blockquote></details>

Merge conflict I think. Deleted.

---

*[pkg/storage/engine/disk_map.go, line 151 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164#-KpbUf63f2NBg6pp4412:-KpcGJlkY_PXJKQgr3Ng:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4be81e4f0dd4431a1cacdc4b4ec12632e674bf80/pkg/storage/engine/disk_map.go#L151)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

s/prefex/prefix.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17164)*

**Pull request merged**
