### PR TITLE
sql, opt: incorporate projection into scanNode

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### sql: consolidate configuration knobs for scanNode columns

We have `scanVisibility` and `wantedColumns` knobs for setting up the
scanNode columns. In addition, we would like to control whether
unwanted columns are also added as hidden. Consolidating all these
knobs in a single structure.

This cleanup also fixes an oversight: mutation columns are now
reported as plan dependencies.

Release note: None

#### sql: fix scanNode issues when we don't include all the PK columns

Fixing a few minor issues with scanNode/rowFetcher for the case where
our schema doesn't contain all PK columns. Also a minor fix to a scrub
error message (it was showing the wrong values).

Release note: None

#### opt/exec: incorporate projection into the scan

We are now able to set up the scanNode to output only the columns we
want (even no columns).

Release note: None

CC @knz, @jordanlewis for the first two commits
CC @andy-kimball for the third commit

### CODE REVIEW

**Comment by knz** [comment]
I think the first commit fixes a definite bug (create view after alter table add column would fail to register the dependency on a newly added column) and is thus a good candidate for a cherry-pick.

Same for the second commit.

Also I think the release note in the first two commits can reflect the bug fixes.

:lgtm: for all nevertheless.

The last commit is very nice -- this is a huge step forward. 

---

Reviewed 10 of 10 files at r1, 2 of 2 files at r2, 8 of 8 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23797#-:-L7WT82UIbKft0rPWgmr:b-g99fkc)*

**Comment by RaduBerinde** [comment]
Added release notes. Can you suggest a testcase I could add with the first commit?

**Comment by knz** [comment]
Here you are:

```
> CREATE TABLE kv(k INT PRIMARY KEY, v INT);
> BEGIN;
   ALTER TABLE kv ADD COLUMN z INT DEFAULT 123;
  CREATE VIEW v AS WITH a AS (UPDATE kv SET v = 444 RETURNING k) SELECT k FROM a;
  COMMIT;
>  EXPLAIN(VERBOSE) SELECT * FROM v;
+----------------+-------+--------+-------------+---------------+------------------+------------------------------+
|      Tree      | Level |  Type  |    Field    |  Description  |     Columns      |           Ordering           |
+----------------+-------+--------+-------------+---------------+------------------+------------------------------+
| update         |     0 | update |             |               | (k)              |                              |
|  │             |     0 |        | table       | kv            |                  |                              |
|  │             |     0 |        | set         | v             |                  |                              |
|  │             |     0 |        | returning 0 | t.public.kv.k |                  |                              |
|  └── render    |     1 | render |             |               | (k, v, z, "444") | "444"=CONST; k!=NULL; key(k) |
|       │        |     1 |        | render 0    | t.public.kv.k |                  |                              |
|       │        |     1 |        | render 1    | t.public.kv.v |                  |                              |
|       │        |     1 |        | render 2    | t.public.kv.z |                  |                              |
|       │        |     1 |        | render 3    | 444           |                  |                              |
|       └── scan |     2 | scan   |             |               | (k, v, z)        | k!=NULL; key(k)              |
|                |     2 |        | table       | kv@primary    |                  |                              |
|                |     2 |        | spans       | ALL           |                  |                              |
+----------------+-------+--------+-------------+---------------+------------------+------------------------------+

(observe, the view `v` uses newly added column `z` at this point.

> SELECT * FROM crdb_internal.forward_dependencies WHERE descriptor_name = 'kv';
+---------------+-----------------+----------+-----------------+-------------------+-----------------------+-------------------+----------------------+
| descriptor_id | descriptor_name | index_id | dependedonby_id | dependedonby_type | dependedonby_index_id | dependedonby_name | dependedonby_details |
+---------------+-----------------+----------+-----------------+-------------------+-----------------------+-------------------+----------------------+
|            51 | kv              |     NULL |              53 | view              |                     0 | NULL              | Columns: [1 2]       |
+---------------+-----------------+----------+-----------------+-------------------+-----------------------+-------------------+----------------------+

(observe: bug: the newly created column z is not depended on properly)
```

Your patch should fix this and the column id 3 (assuming that's the id picked for `z`) will show up in the last column of `crdb_internal.forward_dependencies`.

You can probably turn this into a logic test.

**Comment by RaduBerinde** [comment]
Thanks @knz, added. I confirmed that it showed columns 1 2 before and now it shows 1 2 3.

**Comment by knz** [comment]
Thanks :shipit: 

---

Reviewed 1 of 11 files at r4, 2 of 2 files at r5, 8 of 8 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23797#-:-L7_27p3B5M3zz_64JtH:bemy4r9)*

**Pull request merged**
