### PR TITLE
catalog/lease: address lease query failure during MR conversion

### LINKED ISSUE #122004: ccl/multiregionccl: TestMrSystemDatabase failed
ccl/multiregionccl.TestMrSystemDatabase [failed](https://tanzanite.cluster.engflow.com/invocations/default/3515e9e0-dfb1-4cad-9602-2011ae20e570?testReportRun=1&testReportShard=3&testReportAttempt=1#targets-Ly9wa2cvY2NsL211bHRpcmVnaW9uY2NsOm11bHRpcmVnaW9uY2NsX3Rlc3Q=) on master @ [d45a65e08d45383aade2bcffdcdbe72a0cc279b1](https://github.com/cockroachdb/cockroach/commits/d45a65e08d45383aade2bcffdcdbe72a0cc279b1):

```
=== RUN   TestMrSystemDatabase
    test_log_scope.go:170: test logs captured to: outputs.zip/logTestMrSystemDatabase966567483
    test_log_scope.go:81: use -show-logs to present logs inline

pkg/ccl/multiregionccl/multiregion_system_table_test.go:62: (TestMrSystemDatabase)
	NOTICE: .Locality() called via implicit interface ApplicationLayerInterface;
HINT: consider using .ApplicationLayer().Locality() instead.
TIP: consider replacing the test server initialization from:
    ts, ... := serverutils.StartServer(t, ...)
    defer ts.Stopper().Stop(...)
to:
    srv, ... := serverutils.StartServer(t, ...)
    defer srv.Stopper().Stop(...)
    ts := srv.ApplicationLayer()

See also: https://go.crdb.dev/p/testserver-and-cluster-virtualization
    multiregion_system_table_test.go:370: -- test log scope end --
test logs left over in: outputs.zip/logTestMrSystemDatabase966567483
--- FAIL: TestMrSystemDatabase (121.07s)
=== RUN   TestMrSystemDatabase/Sqlliveness
    multiregion_system_table_test.go:110: error scanning '&{0xc019146d80 <nil>}': pq: unsupported comparison: bytes to crdb_internal_region
    --- FAIL: TestMrSystemDatabase/Sqlliveness (0.19s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=1</code>
 - <code>shard=3</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestMrSystemDatabase.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-37660

### PR DESCRIPTION
**Pull request by fqazi**
Previously, the lease count queries would decide be multi-region aware based on the system database being multi-region. Unfortunately, when this conversion happens we need to also wait for leases to expire, so it was possible to observe a single region system database and a multi-region lease table at the same time. As a result, the count query would fail assuming the region column was bytes instead of the crdb_region type. To address this, this patch address retry logic when this scenario occurs to switch to the multi-region query.

Fixes: #122004

Release note: None

### CODE REVIEW

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122135)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/catalog/lease/count.go` line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122135#-NvDBO8_AN3pFJKIaIQz:-NvDBO8_AN3pFJKIaIR-:b-yq1q22) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff5d40f7af9016fe23beaa6b41a4147b8ce48d7a/pkg/sql/catalog/lease/count.go#L136)):*
> ```Go
> 						count, err = countLeasesNonMultiRegion(ctx, txn, at, whereClause)
> 						// It's possible that our cached database descriptor is stale relative to the
> 						// visible lease table descriptor. Because the lease manager uses changefeeds to
> ```

instead of changefeed, should this say rangefeed?
___
*[`pkg/sql/catalog/lease/count.go` line 139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122135#-NvDBfgEAR6Ohe9JNHXD:-NvDBfgEAR6Ohe9JNHXE:bi5uxnx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff5d40f7af9016fe23beaa6b41a4147b8ce48d7a/pkg/sql/catalog/lease/count.go#L139)):*
> ```Go
> 						// keep track of new descriptor versions, when converting to a multi-region
> 						// system database its possible for the lease table descriptor update to precede
> 						// the system database descriptor update.
> ```

just checking -- this problem is not on the 24.1 branch, right?
___
*[`pkg/sql/catalog/lease/count.go` line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122135#-NvDB0Fl58g1p0d6VEwX:-NvDB0Fl58g1p0d6VEwY:b-13no21) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff5d40f7af9016fe23beaa6b41a4147b8ce48d7a/pkg/sql/catalog/lease/count.go#L144)):*
> ```Go
> 							containsSystemDatabase {
> 							forceMultiRegionQuery = true
> 							return txn.KV().GenerateForcedRetryableErr(ctx, "forcing retry once with MR columns")
> ```

do we need to worry about the synthetic descriptors no longer being correct when the retry happens?

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122135)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/catalog/lease/count.go` line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122135#-NvDBO8_AN3pFJKIaIQz:-NvDOUVr1QdiDDvJaLHF:bcsn85r) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff5d40f7af9016fe23beaa6b41a4147b8ce48d7a/pkg/sql/catalog/lease/count.go#L136)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

instead of changefeed, should this say rangefeed?
</blockquote></details>

Done.

Yes :facepalm: 
___
*[`pkg/sql/catalog/lease/count.go` line 139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122135#-NvDBfgEAR6Ohe9JNHXD:-NvDOXeY0Aw7n_s36U6H:b-7b72dq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff5d40f7af9016fe23beaa6b41a4147b8ce48d7a/pkg/sql/catalog/lease/count.go#L139)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

just checking -- this problem is not on the 24.1 branch, right?
</blockquote></details>

This can happen on the 24.1 branch too. I think this whole scenario though is only limited to serverless if it does happen. The impact there will be that the schema change job will return early before one version exists for the system table descriptors.
___
*[`pkg/sql/catalog/lease/count.go` line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122135#-NvDB0Fl58g1p0d6VEwX:-NvDOuoc4oNTAJfpPM0i:b-qx99l5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff5d40f7af9016fe23beaa6b41a4147b8ce48d7a/pkg/sql/catalog/lease/count.go#L144)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

do we need to worry about the synthetic descriptors no longer being correct when the retry happens?
</blockquote></details>

I think that should be fine, we will adapt the region values as bytes or the region type depending on if a synthetic descriptor was used automatically.

**Review by rafiss — APPROVED** [review]
lgtm!

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122135#-:-NvZiWa93CbyusWXUO4C:b-7nbn20)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

**Comment by fqazi** [comment]
@rafiss TFTR!

bors r+

**Comment by fqazi** [comment]
Retrying one more time, since there were issues on CI infrastructure again

bors r+

**Pull request merged**
