### PR TITLE
sql: add support for executing row-level BEFORE triggers

### LINKED ISSUE #126360: sql: add support for row-level BEFORE triggers
This issue tracks adding support for row-level BEFORE triggers, which execute for each mutated row in an INSERT, UPDATE, UPSERT, or DELETE before the mutation occurs. Example:
```
CREATE TRIGGER t BEFORE INSERT ON table_1 FOR EACH ROW EXECUTE FUNCTION f();
```

Jira issue: CRDB-37296

Jira issue: CRDB-39860

### PR DESCRIPTION
**Pull request by DrewKimball**
#### sql: don't remove renders during exec planning

Previously, exec planning through the `execFactory` could remove a rendered
expression if its result was not needed for the parent operator. This was
the result of an optimization that avoids adding a new `renderNode` if one
already exists. However, there are some cases that rely on renders being
evaluated even if the result is ignored (see #108901).

This commit tightens the restriction on when the optimization is applied,
so that we avoid adding a `renderNode` only when render expressions are
projected exactly once. In addition to avoiding hidden bugs, this
improvement also makes optimization barriers (`BarrierExpr`) easier to
use, since we can rely on it to make sure a given expression is
evaluated.

#### logictest: don't use regexp matching for noticetrace

Previously, the `noticetrace` output for logic tests used regexp matching
for comparing against an expected output. This meant that `noticetrace`
tests were required to work around special characters, which is cumbersome.
This commit adds a new `regexp` option to recover regexp matching behavior,
and reverts the `noticetrace` format to using string matching by default.

#### sql: add basic support for executing row-level BEFORE triggers

This commit adds support for row-level BEFORE triggers, which fire on
each row before the mutation is applied to the row. The triggers are
implemented by projecting each trigger function in the input of the
mutation operator. The location of the trigger function in the query
plan is important, because triggers can observe old and new values of
the row, and even modify it. Each trigger function invocation is
surrounded by optimization barriers for this reason.

#### sql: allow row-level BEFORE triggers to modify the row

This commit adds the logic needed for row-level BEFORE triggers to make
changes to a row that is being inserted or updated. The row is modified
via the return value of the trigger function. For example, to increment
a column, the returned expression may look like this:
```
RETURN ROW((NEW).x, (NEW).y + 10);
```

#### sql: allow row-level BEFORE triggers to filter rows

Row-level BEFORE triggers can prevent rows from being inserted, updated,
or deleted by returning `NULL`. This commit implements this behavior by
adding a filter that checks the result of the trigger function.

#### sql: add support for the WHEN clause in row-level BEFORE triggers

This commit adds support for the trigger WHEN clause, which determines
whether the trigger function should be executed for a given row.

#### opt: add CREATE/DROP TRIGGER to the test catalog

This commit adds support for `CREATE TRIGGER` and `DROP TRIGGER` in the
test catalog. It also changes the ID allocation logic so that user-defined
types and routines get globally unique descriptor IDs, so that code that
relies on unique IDs works with the test catalog. Note that this is
already the case for the non-test catalog.

This commit also adds a few tests showing how row-level BEFORE triggers
are built into the plan of a mutation.

---

Fixes #126360

Release note (sql change): Added support for row-level BEFORE triggers.
A row-level trigger executes the trigger function for each row that is
being mutated. BEFORE triggers fire before the mutation operation.

### CODE REVIEW

**Review by DrewKimball — COMMENTED** [review]
The first 4 commits are #128540.

The first 2 commits (from this PR) are just preparation to make sure tests work correctly. The last 4 are incremental improvements / testing for the "add basic support" commit, which contains the bulk of the changes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131552#-:-O7rfwkn1m8azD3VyWM-:b-r46mqt)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aa-joshi, @arjunmahishi, @mw5h, and @xinhaoz)

___
*[`-- commits` line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131552#-O7rg0es5hVSsZZOYr1L):*
We aren't actually depending on this behavior currently AFAIK, but it's pretty unintuitive that exec planning might remove renders, and might lead to bugs in the current state. Making this change also allows the "basic support" commit to pass tests before the other commits are applied.

**Review by mw5h — COMMENTED** [review]
Does it make sense to break this PR up into more bite-sized chunks?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131552#-:-O82ktR09qS1Qc3YG3Js:b-trnjsq)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`-- commits` line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131552#-O7rg0es5hVSsZZOYr1L):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

We aren't actually depending on this behavior currently AFAIK, but it's pretty unintuitive that exec planning might remove renders, and might lead to bugs in the current state. Making this change also allows the "basic support" commit to pass tests before the other commits are applied.
</blockquote></details>

If this patch doesn't depend on the rest of the PR and provides value outside of this PR, why not pull it out and let's get it in first?

**Comment by DrewKimball** [comment]
>Does it make sense to break this PR up into more bite-sized chunks?

Sure. I'll pull out those first two into separate PRs. Do you think it would be helpful to break out the last four commits as well?

**Comment by DrewKimball** [comment]
Alright, I'm going to rebase on top of master now and hopefully avoid the reviewable tangle.

**Pull request closed without merging**
