### PR TITLE
ui: design updates to the Statements pages

### PR DESCRIPTION
**Pull request by couchand**
Included are a variety of updates to the Statements list and details pages, working to make these pages as immediately useful as possible.

List page, before:
screen shot 2018-08-28 at 3 03 46 pm

List page, after:
screen shot 2018-09-05 at 5 05 15 pm

Details page, before:
screen shot 2018-08-28 at 3 03 35 pm

Details page, after:
screen shot 2018-09-05 at 5 05 32 pm

### CODE REVIEW

**Comment by josueeee** [comment]
Design Polish: 

44744796-f3ce3900-aad3-11e8-819c-8d36e8cbcee2_png__2390x2184__png
44744781-e618b380-aad3-11e8-9c49-db3d8d968115_png__2850x1338_
table

**Comment by vilterp** [comment]
As of #28545, the numerical stats on the node list are right-aligned, since I thought it made them easier to read (sorry I forgot to run this by you @josueeee; was doing a quick fix before code freeze). I think time and retries should be right aligned here too. (@couchand, you can use the css class `sort-table__cell--right-aligned-stats` to get `textAlign: right` if you want. Also just noticed that that should be `right-aligned-stat`).

The bars are tricky to left align because the text can be variable width, but the bars always need to start from the same place...

Also, it's confusing that the "total" and "overall" labels look like links, but aren't — I think we need to either make them bold instead of blue or make them blue and underline all actual links. Prefer just bolding them; underlining everything seems a little drastic. (though it does work pretty well for the GCP console)

**Comment by josueeee** [comment]
@vilterp Thanks for clarifying and @couchand just update the table to match whatever we have in the node list. 

And yes, I think for now we should just use bold type in the dark blue instead of the primary blue as I also think making all links underlined will be too noisy. (However, we do use the primary blue in the overview for non-linked data so we should revisit our link treatment for 2.2)

**Comment by couchand** [comment]
@vilterp @josueeee ready for another pass, thanks!

**Comment by vilterp** [comment]
image

Nit: can you prevent the "time" column from wrapping? (`white-space: no-wrap` or whatever it is) When it wraps, it makes it harder to see the hover tooltips on the other columns, since all the cells get taller but only their top halves (with the actual content) trigger the tooltip.

You could also make the entire cell trigger the tooltip, but I think instead we should try to make the cell contents never wrap so rows always remain the same height.

**Comment by vilterp** [comment]
Another nit:
image

Removing the headings does make this cleaner, but I think this section some more explanation. Maybe just change the column heading to "gateway node" instead of node?

**Comment by vilterp** [comment]
[ ] Layout nit:

image

[ ] Side nav nit: please use that prop in the `<SidebarIcon>` component to highlight the Statements icon when we're on the statement details page.

**Comment by couchand** [comment]
TFTR @vilterp 

> Can you prevent the "time" column from wrapping, as it is above?

Done.

> Maybe just change the column heading to "gateway node" instead of node?

I tried this, but it takes up an inordinate amount of space.  Maybe a tooltip would be appropriate, or perhaps @josueeee has another good idea?

> On our other pages, the side widget sticks close to the content.
> no matter how wide the screen is there's never any right margin on it

Both the same fix.  Done.  (also filed #29640 since I'm really tired of this stuff)

> highlight the Statements icon when we're on the statement details page.

Done.

> Yet another truncated tooltip…

@j-low is already investigating there, and if we don't come up with anything else by a few weeks from now we can look at solving that entire issue by hardcoding the locations of tooltips.  But I'd really rather not introduce a special case here that doesn't solve all the other places this comes up, so I think we should just leave that to #28869.

**Comment by vilterp** [comment]
Nit:
image
image

On the main page, even when the page is wide enough to accommodate the table, there's space off to the right that you can scroll to. This generally happens after displaying a tooltip that goes off the side, but this happens before I've hovered any tooltips.

**Comment by vilterp** [comment]
Otherwise, I think this is ready to go. For explaining the node breakdown, I'd probably just put a tooltip in the column header (or put all the headings back :trollface:)

**Comment by couchand** [comment]
@Amruta-Ranade or @piyush-singh Requesting copy for a new tooltip, proposed to be on the gateway node table on the Statement Details page, to explain the purpose of that table.

**Review by josueeee — APPROVED** [review]
LGTM

**Comment by piyush-singh** [comment]
Strawman for tooltip copy:

>  Statement statistics grouped by which node received the request for the statement.

If it is better to include the term "Gateway", perhaps:

>  Statement statistics grouped by "Gateway" nodes - nodes which received requests for the statements.

**Comment by couchand** [comment]
Using the strawman tooltip text for the time being, we can come back and edit again later.  Also added a little band-aid to help with #29676, but I'm leaving that open since I think there are more significant questions to address there.

**Review by vilterp — APPROVED** [review]
LGTM with a couple quibbles:

- 
image
  there's still a big margin off to the right before any tooltips have been hovered, but it seems to correspond exactly to the width of the furthest-to-the-right tooltip. Let's make sure @j-low's stuff fixes this.
- I'd mention the term "gateway node" in the tooltip, since it seems like a useful term. Maybe "statement statistics grouped by 'gateway node' (the node which received the statement)".

**Comment by couchand** [comment]
@vilterp I agree about waiting on the tooltip layout nit.  Regarding the gateway node tooltip, @Amruta-Ranade mentioned that she'll have a chance to look at that in the next few weeks, so let's revisit it later.

bors r+

**Pull request merged**
