### PR TITLE
rfc: update RangeFeed RFC with ResolvedTS and WriteBatch-decoding discussions

### PR DESCRIPTION
**Pull request by nvb**
This change updates the RangeFeed RFC with detailed discussions on
the semantics and implementation details of the Range-level "resolved
timestamp" that will be broadcast in `Checkpoint()` notifications.
It discusses the `UnresolvedIntentQueue` structure that will be
needed to track this timestamp and a policy we'll need to introduce
to ensure that the timestamp makes forward progress in the presence
of abandoned intents.

The change also updates the RFC with a more detailed discussion on
decoding WriteBatches and the decision making process that will go
into pattern matching RocksDB batch entries to detect higher-level
mvcc operations.

### CODE REVIEW

**Comment by bdarnell** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 282 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LFJuvMOAnCLoQIFNTXo:-LFJuvMOAnCLoQIFNTXp:bybicik) ([raw file](https://github.com/cockroachdb/cockroach/blob/93c16e4d51c2859394d048646b3ec2dd87a40af4/docs/RFCS/20170613_change_feeds_storage_primitive.md#L282)):*
> ```Markdown
> intents on range). This also means that the queue does not need to track the
> specific keys of each intent. This is critical as it should prevent the queue's
> memory footprint from growing large enough to need to spill to disk.
> ```

That should be true in practice, but we still need to guard against the worst case in which there are many single-key transactions in parallel. 

---

*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 284 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LFJvssRAh1UeefPl896:-LFJvssRAh1UeefPl897:bxm9idi) ([raw file](https://github.com/cockroachdb/cockroach/blob/93c16e4d51c2859394d048646b3ec2dd87a40af4/docs/RFCS/20170613_change_feeds_storage_primitive.md#L284)):*
> ```Markdown
> memory footprint from growing large enough to need to spill to disk.
> 
> The queue will be initially built using the RocksDB snapshot captured under lock
> ```

Snapshot or iterator (since we've recently discovered that those have different performance impliciations)?

---

*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 286 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LFJw4q98Mz4LWwI84HY:-LFJw4q98Mz4LWwI84HZ:b6tx35c) ([raw file](https://github.com/cockroachdb/cockroach/blob/93c16e4d51c2859394d048646b3ec2dd87a40af4/docs/RFCS/20170613_change_feeds_storage_primitive.md#L286)):*
> ```Markdown
> The queue will be initially built using the RocksDB snapshot captured under lock
> when the first RangeFeed connected. It will then be incrementally maintained
> (txns added and deleted, refcount adjusted, Timestamp forwarded) as
> ```

One subtlety here: Unless the initial build of the queue blocks everything else, we may see an intent resolution before we see the intent, so the refcount can go negative. I don't think this breaks anything (as long as we're careful to use `refcount == 0` instead of `<= 0`) but it might be worth noting. 

---

*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 309 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LFJwdBDAErUaOOuBUQL:-LFJwdBDAErUaOOuBUQM:bh6froj) ([raw file](https://github.com/cockroachdb/cockroach/blob/93c16e4d51c2859394d048646b3ec2dd87a40af4/docs/RFCS/20170613_change_feeds_storage_primitive.md#L309)):*
> ```Markdown
> 
> On its own, this queue would not be enough to ensure that the resolved timestamp
> continues to make forward progress. This is because transactions may be
> ```

Technically the GC queue guarantees forward progress, but on an unacceptably long timescale. 

---

*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 323 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LFJwyk07_-oJK2kzv8V:-LFJwyk07_-oJK2kzv8W:b-uql1yw) ([raw file](https://github.com/cockroachdb/cockroach/blob/93c16e4d51c2859394d048646b3ec2dd87a40af4/docs/RFCS/20170613_change_feeds_storage_primitive.md#L323)):*
> ```Markdown
> will be introduced to push any transactions that have a sufficiently old
> timestamp in the `UnresolvedIntentQueue` using a high-priority `PushTxnRequest`.
> It is likely that this age threshold will be similar to the follower reads
> ```

This argues that the force-resolution interval should not be *greater* than the closed timestamp interval, but it might make sense for it to be smaller (improved responsiveness in typical cases of short-lived at the expense of additional push attempts when there are long-lived txns). This would add a fourth case: the txn is still pending at its original timestamp, so it remains at the head of the queue and should be pushed again (after a backoff).

---

*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 420 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LFJxycD5O7ES691nyyP:-LFJxycD5O7ES691nyyQ:bmh11j1) ([raw file](https://github.com/cockroachdb/cockroach/blob/93c16e4d51c2859394d048646b3ec2dd87a40af4/docs/RFCS/20170613_change_feeds_storage_primitive.md#L420)):*
> ```Markdown
> to be very careful about making any changes to MVCC once we introduce this
> dependency, and I'm worried about the consequences of this. I think this
> deserves a serious discussion.
> ```

Yeah, this argues for some sort of additional payload in the raft command with higher-level knowledge of intent and other operations. We might be able to get clever and point to the keys that are already in the write batch to avoid the write amplification. 

---

*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 430 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LFJyHkn4kOs1SzczhR7:-LFJyHko5TFRL2Cy6iEN:bktv8b2) ([raw file](https://github.com/cockroachdb/cockroach/blob/93c16e4d51c2859394d048646b3ec2dd87a40af4/docs/RFCS/20170613_change_feeds_storage_primitive.md#L430)):*
> ```Markdown
>     InlineWrite | NonTransactionalWrite => SendValueToMatchingFeeds(key, val, ts),
>     IntentWrite    => {
>         UnresolvedIntentQueue[txnID].refcount++
> ```

Unless we're writing over our own previous intent (which I don't think is detectable from the current WriteBatch alone).

---

*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 438 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LFJyWRqAgi0TA7o9zwy:-LFJyWRrEgE1yFuH9whh:b-x7v13o) ([raw file](https://github.com/cockroachdb/cockroach/blob/93c16e4d51c2859394d048646b3ec2dd87a40af4/docs/RFCS/20170613_change_feeds_storage_primitive.md#L438)):*
> ```Markdown
>         SendValueToMatchingFeeds(key, val, ts)
>     },
>     IntentAbort    => UnresolvedIntentQueue[txnID].refcount--,
> ```

Intent commits and aborts are idempotent and become no-ops if retried. I think that's OK since they'll produce empty WriteBatches, but I'm not 100% sure about this. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26782)*

**Comment by nvanbenschoten** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 282 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LFJuvMOAnCLoQIFNTXo:-LFUpatW4UX6QtidtScG:b-pqga4v) ([raw file](https://github.com/cockroachdb/cockroach/blob/93c16e4d51c2859394d048646b3ec2dd87a40af4/docs/RFCS/20170613_change_feeds_storage_primitive.md#L282)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

That should be true in practice, but we still need to guard against the worst case in which there are many single-key transactions in parallel. 
</blockquote></details>

Added a section discussing this.

---

*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 284 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LFJvssRAh1UeefPl896:-LFUpwKL92iPzMDbb9NV:b-48c5or) ([raw file](https://github.com/cockroachdb/cockroach/blob/93c16e4d51c2859394d048646b3ec2dd87a40af4/docs/RFCS/20170613_change_feeds_storage_primitive.md#L284)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Snapshot or iterator (since we've recently discovered that those have different performance impliciations)?
</blockquote></details>

At its worst, this will have to scan the entire range, so I think we'll want to grab a snapshot like we do with checksum computations.

---

*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 286 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LFJw4q98Mz4LWwI84HY:-LFUrb3n4qd0ckxf-faU:b-3t3jvb) ([raw file](https://github.com/cockroachdb/cockroach/blob/93c16e4d51c2859394d048646b3ec2dd87a40af4/docs/RFCS/20170613_change_feeds_storage_primitive.md#L286)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

One subtlety here: Unless the initial build of the queue blocks everything else, we may see an intent resolution before we see the intent, so the refcount can go negative. I don't think this breaks anything (as long as we're careful to use `refcount == 0` instead of `<= 0`) but it might be worth noting. 
</blockquote></details>

Good point. Added a few sentences.

---

*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 323 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LFJwyk07_-oJK2kzv8V:-LFUs0a88F91j7W_HBUl:b-uaeo9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/93c16e4d51c2859394d048646b3ec2dd87a40af4/docs/RFCS/20170613_change_feeds_storage_primitive.md#L323)):*
> but it might make sense for it to be smaller (improved responsiveness in typical cases of short-lived at the expense of additional push attempts when there are long-lived txns

I don't think we'd get a lot out of the making the force-resolution interval smaller than the closed timestamp interval other than less variation in how far the resolved timestamp lags behind the current time. The resolved timestamp cannot lag less than the closed timestamp interval.

> This would add a fourth case: the txn is still pending at its original timestamp, so it remains at the head of the queue and should be pushed again (after a backoff).

I might be misinterpretting what you're saying, but I think it's that we might have to continuously push the same transaction forward. That's true and it's expected to some degree. I think we'll just want to push it forward enough that we wont run into it for a while. Something like 1 second ahead of the force-resolution interval so that we only push it at most once a second. If we do that then I don't think there's a need for a backoff.

---

*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 420 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LFJxycD5O7ES691nyyP:-LFV78K-7sEZJ4WWqhx0:b-j8v645) ([raw file](https://github.com/cockroachdb/cockroach/blob/93c16e4d51c2859394d048646b3ec2dd87a40af4/docs/RFCS/20170613_change_feeds_storage_primitive.md#L420)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Yeah, this argues for some sort of additional payload in the raft command with higher-level knowledge of intent and other operations. We might be able to get clever and point to the keys that are already in the write batch to avoid the write amplification. 
</blockquote></details>

Yeah, I think this approach provides a much more future-proof approach to replicating these logical mvcc operations. I added a few new paragraphs about this approach. PTAL and let me know what you think.

---

*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 430 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LFJyHkn4kOs1SzczhR7:-LFUtKKj19Io5fDyLGta:b-nne6xt) ([raw file](https://github.com/cockroachdb/cockroach/blob/93c16e4d51c2859394d048646b3ec2dd87a40af4/docs/RFCS/20170613_change_feeds_storage_primitive.md#L430)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Unless we're writing over our own previous intent (which I don't think is detectable from the current WriteBatch alone).
</blockquote></details>

That is what I meant by `IntentUpdate`. Am I missing a case?

---

*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 438 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LFJyWRqAgi0TA7o9zwy:-LFUtgsi5ASgvoEXZ0Au:b-xw6rx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/93c16e4d51c2859394d048646b3ec2dd87a40af4/docs/RFCS/20170613_change_feeds_storage_primitive.md#L438)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Intent commits and aborts are idempotent and become no-ops if retried. I think that's OK since they'll produce empty WriteBatches, but I'm not 100% sure about this. 
</blockquote></details>

We'll have to be aware of this in in the logical operation log we add.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26782)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 323 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LFJwyk07_-oJK2kzv8V:-LFrn__ZDa4HRKxgpOFI:b-br9xe1) ([raw file](https://github.com/cockroachdb/cockroach/blob/93c16e4d51c2859394d048646b3ec2dd87a40af4/docs/RFCS/20170613_change_feeds_storage_primitive.md#L323)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> but it might make sense for it to be smaller (improved responsiveness in typical cases of short-lived at the expense of additional push attempts when there are long-lived txns

I don't think we'd get a lot out of the making the force-resolution interval smaller than the closed timestamp interval other than less variation in how far the resolved timestamp lags behind the current time. The resolved timestamp cannot lag less than the closed timestamp interval.

> This would add a fourth case: the txn is still pending at its original timestamp, so it remains at the head of the queue and should be pushed again (after a backoff).

I might be misinterpretting what you're saying, but I think it's that we might have to continuously push the same transaction forward. That's true and it's expected to some degree. I think we'll just want to push it forward enough that we wont run into it for a while. Something like 1 second ahead of the force-resolution interval so that we only push it at most once a second. If we do that then I don't think there's a need for a backoff.
</blockquote></details>

Right. It doesn't actually make sense to force resolution before the timestamp has been closed, so just ignore this thread. 

---

*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 430 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LFJyHkn4kOs1SzczhR7:-LFrpKI5AHRjx4bk-swM:bi4lf8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/93c16e4d51c2859394d048646b3ec2dd87a40af4/docs/RFCS/20170613_change_feeds_storage_primitive.md#L430)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

That is what I meant by `IntentUpdate`. Am I missing a case?
</blockquote></details>

No, I was just raising the question of how you'd distinguish IntentWrite from IntentUpdate by examining the encoded WriteBatch. 

---

*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 285 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LFrmjjTDPcWs1ZtI1mV:-LFrmjjUALNjjJPox5oo:bpgt6ly) ([raw file](https://github.com/cockroachdb/cockroach/blob/26e61ec9141d259339a363bffd553ea99b058706/docs/RFCS/20170613_change_feeds_storage_primitive.md#L285)):*
> ```Markdown
> 
> Still, it's conceivable that the queue could grow large enough that it needs to
> spill to disk. In this case, we'll use a temp storage engine to house the queue.
> ```

Spilling to disk is dangerous. If we're having trouble keeping up, it'll just get worse when it spills to disk. I think it might be better (and easier) to either break the rangefeed or apply backpressure to incoming writes. 

---

*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 456 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LFrp35s-ZWD-eUKfMsF:-LFrp35t4V5F7gRtiOZN:b-52a7ma) ([raw file](https://github.com/cockroachdb/cockroach/blob/26e61ec9141d259339a363bffd553ea99b058706/docs/RFCS/20170613_change_feeds_storage_primitive.md#L456)):*
> ```Markdown
> The definition of `MVCCOp` will be something like:
> ```
> enum Bytes {
> ```

Use proto syntax (or at least Go) here, not rust. 

---

*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 479 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LFrocT58-5wwcZh7BTK:-LFrocT58-5wwcZh7BTL:bobhdab) ([raw file](https://github.com/cockroachdb/cockroach/blob/26e61ec9141d259339a363bffd553ea99b058706/docs/RFCS/20170613_change_feeds_storage_primitive.md#L479)):*
> ```Markdown
> Notably, all byte slice values will optionally point into the WriteBatch itself,
> which will help limit the write amplification caused by replicating both physical
> and logical operations. This optimization can be introduced gradually.
> ```

SGTM. We should also consider whether this is just reinventing the LZ77 wheel.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-:-LFrpve1Di38Twi-cwD7:bnfp4nl)*

**Review by tbg — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26782)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by tbg — DISMISSED** [review]
This looks pretty good! Tracking the refcount and adding the logical payload is still going to be complex, but I don't see how you could do any better.

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-:-LGZxpe51GYv_xjpq1qy:b-l0n1u3)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LGZuJzz7IXSarxdcJYH:-LGZuK--EfNvyimZqTPX:bew3kyb) ([raw file](https://github.com/cockroachdb/cockroach/blob/396ea7ec606ced46ab06fda0e6e487fc9d246711/docs/RFCS/20170613_change_feeds_storage_primitive.md#L1)):*
> ```Markdown
> - Feature Name: Storage-Level Primitive for Change Feeds
> ```

Might as well rename the file.
___
*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 14 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LGZuPKo88IC_-Clk9Xy:-LGZuPKo88IC_-Clk9Xz:be5zteu) ([raw file](https://github.com/cockroachdb/cockroach/blob/26e61ec9141d259339a363bffd553ea99b058706/docs/RFCS/20170613_change_feeds_storage_primitive.md#L14)):*
> ```Markdown
> 
> It is for use by Cockroach-internal higher-level systems such as distributed
> SQL, change data capture, or a Kafka producer endpoint. ["Change Data Capture
> ```

The kafka part now seems redundant as it's part of CDC.
___
*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 225 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LGZux0127so0kGwG6d3:-LGZux0127so0kGwG6d4:b6ahaht) ([raw file](https://github.com/cockroachdb/cockroach/blob/26e61ec9141d259339a363bffd553ea99b058706/docs/RFCS/20170613_change_feeds_storage_primitive.md#L225)):*
> ```Markdown
> timestamp". As discussed above, the receipt of one of these checkpoints with an
> associated resolved timestamp indicates to a downstream receiver that no
> `Value()` notifications with timestamps less than the resolved timestamp will
> ```

.. that all subsequent `Value()` notifications will have timestamps strictly greater than the resolved timestamp.
___
*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 370 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LGZwoJS4kmZsBdR0ttG:-LGZwoJS4kmZsBdR0ttH:b-lopw79) ([raw file](https://github.com/cockroachdb/cockroach/blob/26e61ec9141d259339a363bffd553ea99b058706/docs/RFCS/20170613_change_feeds_storage_primitive.md#L370)):*
> ```Markdown
> #### Decoding WriteBatches / 
> 
> The heart of this proposal relies on the ability to decode `WriteBatch`es
> ```

This section culminates in "let's not actually do it this way", but that should be made more obvious here.
___
*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 399 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LGZwsg32EbgA1DOWNrg:-LGZwsg32EbgA1DOWNrh:b-w69sr7) ([raw file](https://github.com/cockroachdb/cockroach/blob/26e61ec9141d259339a363bffd553ea99b058706/docs/RFCS/20170613_change_feeds_storage_primitive.md#L399)):*
> ```Markdown
> - MVCCDeleteRange
>     + calls MVCCDelete for each key in range
> - MVCCMerge
> ```

You shouldn't have to care about those, right?

**Review by nvb — COMMENTED** [review]
TFTRs. I addressed all comments so I'm going to go ahead and merge on green. Most of this has already been implemented and I updated the RFC where necessary to reflect this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-:-LTxq3Bi3z_6svbfme0n:bhf2vry)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LGZuJzz7IXSarxdcJYH:-LTxoFiA9y0UXotGDaJS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/396ea7ec606ced46ab06fda0e6e487fc9d246711/docs/RFCS/20170613_change_feeds_storage_primitive.md#L1)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Might as well rename the file.
</blockquote></details>

Done.
___
*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 14 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LGZuPKo88IC_-Clk9Xy:-LTxoG1c3Pdo8sRXl7-j:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26e61ec9141d259339a363bffd553ea99b058706/docs/RFCS/20170613_change_feeds_storage_primitive.md#L14)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

The kafka part now seems redundant as it's part of CDC.
</blockquote></details>

Done.
___
*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 225 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LGZux0127so0kGwG6d3:-LTxoi4sDHK4slHQpeeH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26e61ec9141d259339a363bffd553ea99b058706/docs/RFCS/20170613_change_feeds_storage_primitive.md#L225)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

.. that all subsequent `Value()` notifications will have timestamps strictly greater than the resolved timestamp.
</blockquote></details>

Done.
___
*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 285 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LFrmjjTDPcWs1ZtI1mV:-LTxotGOEQZljt8fhP6O:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26e61ec9141d259339a363bffd553ea99b058706/docs/RFCS/20170613_change_feeds_storage_primitive.md#L285)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Spilling to disk is dangerous. If we're having trouble keeping up, it'll just get worse when it spills to disk. I think it might be better (and easier) to either break the rangefeed or apply backpressure to incoming writes. 
</blockquote></details>

Done.
___
*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 370 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LGZwoJS4kmZsBdR0ttG:-LTxp6prBRItE9fIDgUL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26e61ec9141d259339a363bffd553ea99b058706/docs/RFCS/20170613_change_feeds_storage_primitive.md#L370)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This section culminates in "let's not actually do it this way", but that should be made more obvious here.
</blockquote></details>

Done.
___
*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 399 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LGZwsg32EbgA1DOWNrg:-LTxp7a405Gx8CDIv5NU:b-n5b7nd) ([raw file](https://github.com/cockroachdb/cockroach/blob/26e61ec9141d259339a363bffd553ea99b058706/docs/RFCS/20170613_change_feeds_storage_primitive.md#L399)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

You shouldn't have to care about those, right?
</blockquote></details>

Correct, but I included it for completeness.
___
*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 456 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LFrp35s-ZWD-eUKfMsF:-LTxrO207C1jJdTwEEgj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26e61ec9141d259339a363bffd553ea99b058706/docs/RFCS/20170613_change_feeds_storage_primitive.md#L456)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Use proto syntax (or at least Go) here, not rust. 
</blockquote></details>

Done.
___
*[docs/RFCS/20170613_change_feeds_storage_primitive.md, line 479 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26782#-LFrocT58-5wwcZh7BTK:-LTxq0TX0yDA2OFY-eDA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26e61ec9141d259339a363bffd553ea99b058706/docs/RFCS/20170613_change_feeds_storage_primitive.md#L479)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

SGTM. We should also consider whether this is just reinventing the LZ77 wheel.
</blockquote></details>

Done.

**Pull request merged**
