### PR TITLE
opt: Add doc.go for opt package.

### PR DESCRIPTION
**Pull request by andy-kimball**
This package doc file consolidates information about the optimizer that's
currently scattered across multiple files and documents. Much of it is
pulled from Pete's "query planner" RFC, but it's updated and expanded to
reflect the newest thinking and practice of the opt team. This doc is
intended to be a high-level introduction to the optimizer for new team
members, as well as other interested parties. It is expected to be a
"living doc" that we update from time-to-time as the optimizer evolves.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/doc.go, line 85 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23033#-L67M2lC2gzRDBenW_C_:-L67M2lC2gzRDBenW_Ca:b8vimp2) ([raw file](https://github.com/cockroachdb/cockroach/blob/84e73d9c1b5d909c296c2508dd5c21f32013a7fc/pkg/sql/opt/doc.go#L85)):*
> ```Go
> Parse
> 
> The parse phase is not discussed in this RFC. It transforms the SQL query text
> ```

This isn't an RFC. You might want to search for all occurrences of RFC and adjust the language.

---

*[pkg/sql/opt/doc.go, line 184 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23033#-L67MpdZTftekjeBSS4T:-L67MpdZTftekjeBSS4U:b-jzx0z8) ([raw file](https://github.com/cockroachdb/cockroach/blob/84e73d9c1b5d909c296c2508dd5c21f32013a7fc/pkg/sql/opt/doc.go#L184)):*
> ```Go
> query).
> 
> The collection of table statistics occurs prior to receiving the query. As
> ```

The first sentence here reiterates the parenthetical in the last sentence of the previous paragraph. 

---

*[pkg/sql/opt/doc.go, line 245 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23033#-L67NHVpgtTudlc0JidI:-L67NHVpgtTudlc0JidJ:b-xp98k3) ([raw file](https://github.com/cockroachdb/cockroach/blob/84e73d9c1b5d909c296c2508dd5c21f32013a7fc/pkg/sql/opt/doc.go#L245)):*
> ```Go
> Because memo groups contain logically equivalent expressions, all the memo
> expressions in a group share the same logical properties. However, it's
> possible for two logically equivalent expression to be placed in different memo
> ```

`s/expression/expressions/g`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23033#-:-L67PSjs9IEDbVCV_bT2:bnfp4nl)*

**Comment by andy-kimball** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/doc.go, line 85 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23033#-L67M2lC2gzRDBenW_C_:-L67WHS96dUG8XLLeDEj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/84e73d9c1b5d909c296c2508dd5c21f32013a7fc/pkg/sql/opt/doc.go#L85)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This isn't an RFC. You might want to search for all occurrences of RFC and adjust the language.
</blockquote></details>

Done.

---

*[pkg/sql/opt/doc.go, line 184 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23033#-L67MpdZTftekjeBSS4T:-L67WY5Z0SYlMCmWf_SG:b-dzx1o4) ([raw file](https://github.com/cockroachdb/cockroach/blob/84e73d9c1b5d909c296c2508dd5c21f32013a7fc/pkg/sql/opt/doc.go#L184)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The first sentence here reiterates the parenthetical in the last sentence of the previous paragraph. 
</blockquote></details>

You only have yourself to blame for that : ). Fixed.

---

*[pkg/sql/opt/doc.go, line 245 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23033#-L67NHVpgtTudlc0JidI:-L67WpmDcc7kjoy0XzWT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/84e73d9c1b5d909c296c2508dd5c21f32013a7fc/pkg/sql/opt/doc.go#L245)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/expression/expressions/g`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23033)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23033#-:-L68AebeFpx3gF-L83LP:bnfp4nl)*

**Comment by rytaft** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/sql/opt/doc.go, line 60 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23033#-L6Ho11X765vPZLiYF48:-L6Ho11X765vPZLiYF49:b-n2mwtk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f96529491a2a5b3a772e7b3fb49f470d9f7d6dc/pkg/sql/opt/doc.go#L60)):*
> ```Go
>          +-------+     |   Prep    |    transforms (placeholders present)
>                     +-->-----+-----+  - compute initial properties
>                     |        |        - retrieve and attach stats
> ```

Shouldn't the stats be attached as late as possible? They aren't needed until the search phase.

---

*[pkg/sql/opt/doc.go, line 131 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23033#-L6HpIlA4xPiXIEipnRa:-L6HpIlA4xPiXIEipnRb:be5myr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f96529491a2a5b3a772e7b3fb49f470d9f7d6dc/pkg/sql/opt/doc.go#L131)):*
> ```Go
> "Physical properties" are interesting characteristics of an expression that
> impact its layout, presentation, or location, but not its logical content.
> Examples include row order, column naming, and data distribution. Physical
> ```

What do you mean by data distribution?

---

*[pkg/sql/opt/doc.go, line 256 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23033#-L6HtoUH32MXqAiENfup:-L6HtoUH32MXqAiENfuq:b-mn51i6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f96529491a2a5b3a772e7b3fb49f470d9f7d6dc/pkg/sql/opt/doc.go#L256)):*
> ```Go
> 
> Expressions are inserted into the memo by the factory, which ensure that
> expressions have been fully normalized before insertion (see the Normalize
> ```

There is no Normalize section - maybe you meant Transforms/Prep/Rewrite?

---

*[pkg/sql/opt/doc.go, line 435 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23033#-L6HsY8t5W5_plO-P-UJ:-L6HsY8t5W5_plO-P-UK:b-g8kkt3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f96529491a2a5b3a772e7b3fb49f470d9f7d6dc/pkg/sql/opt/doc.go#L435)):*
> ```Go
> Giving each column a unique index allows the expression nodes mentioned above
> to track input and output columns, or really any set of columns during Prep and
> later phases, using a bitmap. The bitmap representation allows fast
> ```

Maybe change bitmap to FastIntSet?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23033#-:-L6HuKn05F2PNfw_WzaN:bnfp4nl)*

**Comment by andy-kimball** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/doc.go, line 60 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23033#-L6Ho11X765vPZLiYF48:-L6I0-DMDgA6Tu17BnWo:b-cj9acn) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f96529491a2a5b3a772e7b3fb49f470d9f7d6dc/pkg/sql/opt/doc.go#L60)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Shouldn't the stats be attached as late as possible? They aren't needed until the search phase.
</blockquote></details>

I think they can be fairly expensive to fetch/attach/propagate, so it's typically done during PREPARE. However, we can do something different if we find it makes more sense.

---

*[pkg/sql/opt/doc.go, line 131 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23033#-L6HpIlA4xPiXIEipnRa:-L6I0ZT99Sf-FIP_wBXY:b-1337p4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f96529491a2a5b3a772e7b3fb49f470d9f7d6dc/pkg/sql/opt/doc.go#L131)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

What do you mean by data distribution?
</blockquote></details>

Where the data is located. For example, a `ScanOp` might have its data scattered across many ranges, located on different machines. But then we do a `SortOp`, and now the complete set of data is in-memory on the local machine (or spooled to local disk). I added a clarifying parenthetical.

---

*[pkg/sql/opt/doc.go, line 256 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23033#-L6HtoUH32MXqAiENfup:-L6I1A0380A5tymUYvOx:b-pkzycw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f96529491a2a5b3a772e7b3fb49f470d9f7d6dc/pkg/sql/opt/doc.go#L256)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

There is no Normalize section - maybe you meant Transforms/Prep/Rewrite?
</blockquote></details>

Yes, fixed.

---

*[pkg/sql/opt/doc.go, line 435 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23033#-L6HsY8t5W5_plO-P-UJ:-L6I1RrQ0wGrrMW7Kuo7:b-ecdp9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f96529491a2a5b3a772e7b3fb49f470d9f7d6dc/pkg/sql/opt/doc.go#L435)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Maybe change bitmap to FastIntSet?
</blockquote></details>

I added a parenthetical that specifies `FastIntSet`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23033)*

**Pull request merged**
