### PR TITLE
sql: fix SHOW CREATE TABLE for multi-column inverted indexes

### PR DESCRIPTION
**Pull request by mgartner**
#### sql: fix SHOW CREATE TABLE for multi-column inverted indexes

This commit fixes an error when executing `SHOW CREATE TABLE t` when `t`
has a multi-column inverted index. The logic for formatting indexes
assumed that the inverted column was the first and only column in the
index. With the introduction of multi-column inverted indexes, an
inverted index can contain any number of non-inverted columns before the
inverted column.

Release note: None

#### sql: move schemaexpr.FormatIndexForDisplay to catformat package

The `schemaexpr` package's purpose is for dealing with expression
strings defined in a schema, like a partial index predicate or a
computed column expression. `FormatIndexForDisplay` formats an entire
index descriptor into a human readable format. So, this function doesn't
belong in the `schemaexpr` package. It has been moved to a new
`catformat` package. In future commits I plan on other functions that do
not belong in the in `schemaexpr` to the `catformat` package.

Release note: None

#### schemaexpr: move to pkg/sql/catalog

This commit moves the `schemaexpr` package to the `pkg/sql/catalog`
directory. The `schemaexpr` package provides utilities for working with
expression strings defined in schemas. It is more appropriate for it to
live in the `pkg/sql/catalog` directory rather than the more general
`pkg/sql` directory.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56707#-:-MMChnmFAZJE1mPUBxMy:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @RaduBerinde, and @rytaft)

___
*[pkg/sql/schemaexpr/partial_index.go, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56707#-MMChTxZDebBel2YwN_9:-MMChTxZDebBel2YwN_A:bvdxdw0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4879d1c608b71cffa45ef829717465987e3e7fba/pkg/sql/schemaexpr/partial_index.go#L97)):*
> ```Go
> //   INDEX i ON t (a) WHERE b > 0
> //
> func FormatIndexForDisplay(
> ```

[nit] Why is this in `partial_index.go`?

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56707)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @ajwerner, and @rytaft)

___
*[pkg/sql/schemaexpr/partial_index.go, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56707#-MMChTxZDebBel2YwN_9:-MMHJav79lhObxCB6fUb:b-nln94a) ([raw file](https://github.com/cockroachdb/cockroach/blob/4879d1c608b71cffa45ef829717465987e3e7fba/pkg/sql/schemaexpr/partial_index.go#L97)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Why is this in `partial_index.go`?
</blockquote></details>

It doesn't belong here. I've moved it to a new `catformat` package that lives in `pkg/sql/catalog/catformat`. I'll move other functions the don't belong in `schemaexpr` into `catformat` in a follow-up PR. I've also moved `pkg/sql/schemaexpr` to `pkg/sql/catalog/schemaexpr`. 

@ajwerner LMK if you have feedback on the package structure changes I've made in the last 2 commits of this PR.

**Review by rytaft — APPROVED** [review]
Your final commit has an extra release note (also in the PR message). Otherwise, :lgtm: 

> Reviewed 3 of 3 files at r1, 12 of 12 files at r2, 62 of 62 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56707#-:-MMHVfjc5FFth4_ip_-y:b-h0txvw)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru and @ajwerner)

**Review by mgartner — COMMENTED** [review]
> Your final commit has an extra release note (also in the PR message).
 
Fixed!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56707#-:-MMHYNdO0X6kjNlj3b3U:bzhpmej)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @adityamaru and @ajwerner)

**Review by ajwerner — APPROVED** [review]
:lgtm: I’m pleased with the code reorg

> Reviewed 1 of 62 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56707#-:-MMHZQGP4Pzf-29oqyAM:bo0w5nz)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @adityamaru and @ajwerner)

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
