### PR TITLE
outliers: rename to insights

### PR DESCRIPTION
**Pull request by matthewtodd**
The UI design that includes outliers also features other insights about
sql execution. We will expand this outliers subsystem to support making
those insights as well (probably with more detectors, changing the
signature / return type of `isOutlier`). Renaming now is the first step
in that direction.

Release note: None

### CODE REVIEW

**Review by maryliag — APPROVED** [review]
Just had one questions, otherwise :lgtm: 

> Reviewed 40 of 40 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84917#-:-N7phT738PyeKP-PE9GS:b-u1hyxn)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @matthewtodd)

___
*[`pkg/sql/sqlstats/insights/insights.go` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84917#-N7phL2oBiZrnLl6-IQa:-N7phL2oBiZrnLl6-IQb:btzalab) ([raw file](https://github.com/cockroachdb/cockroach/blob/445248ff317c8acc2983cd9b2dcdc8a641874bc0/pkg/sql/sqlstats/insights/insights.go#L32)):*
> ```Go
> var LatencyThreshold = settings.RegisterDurationSetting(
> 	settings.TenantWritable,
> 	"sql.stats.insights.experimental.latency_threshold",
> ```

now that you made more tests, should we maybe remove the `experimental`  ?

**Review by matthewtodd — COMMENTED** [review]
TFTR, @maryliag!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84917#-:-N7pjPt20B59iCu_6h1u:byqop8s)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/sql/sqlstats/insights/insights.go` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84917#-N7phL2oBiZrnLl6-IQa:-N7pjSCP6WcCldFl0pmc:b-nlsmrf) ([raw file](https://github.com/cockroachdb/cockroach/blob/445248ff317c8acc2983cd9b2dcdc8a641874bc0/pkg/sql/sqlstats/insights/insights.go#L32)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

now that you made more tests, should we maybe remove the `experimental`  ?
</blockquote></details>

Yes! I'll be doing that separately (and have more thoughts on naming queued up from Kevin), just wanted to get this mechanical renaming out there.

**Review by j82w — APPROVED** [review]
> Reviewed 40 of 40 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84917)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag)

**Pull request merged**
