### PR TITLE
ui: misc v2 dbs styling fixes

### PR DESCRIPTION
**Pull request by xinhaoz**
- Add tooltip to 'Last updated' text in table details
- Cursor should be a pointer on tooltip hover
- Align Enabled/Disabled tag in db details page  with other
badges by using the existing Badge component

Epic: CRDB-37558
Release note: None

### CODE REVIEW

**Comment by xinhaoz** [comment]
https://www.loom.com/share/a74adc419d38483c8d74073d3db18bce

**Review by angles-n-daemons — CHANGES_REQUESTED** [review]
couple quick questions - looks good overall

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132613#-:-O9GBJTI9tHglvSiMlPD:b1v4v3e)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kyle-a-wong and @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/databaseDetailsV2/tablesView.tsx` line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132613#-O9GBFL2Eh7ocYt7AXQN:-O9GBFL2Eh7ocYt7AXQO:buijviw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a3b57fb09900fd0b1ecee907cfb6b9c2aab6caa/pkg/ui/workspaces/cluster-ui/src/databaseDetailsV2/tablesView.tsx#L140)):*
> ```XML
>         const type = t.autoStatsEnabled ? "success" : "default";
>         const text = t.autoStatsEnabled ? "ENABLED" : "DISABLED";
>         return <Badge status={type} text={text} forceUpperCase />;
> ```

is forceUpperCase necessary?
___
*[`pkg/ui/workspaces/cluster-ui/src/tableDetailsV2/tableOverview.tsx` line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132613#-O9GAqGV2Mr5gSoA5Nm8:-O9GAqGV2Mr5gSoA5Nm9:bk292c5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a3b57fb09900fd0b1ecee907cfb6b9c2aab6caa/pkg/ui/workspaces/cluster-ui/src/tableDetailsV2/tableOverview.tsx#L77)):*
> ```XML
>           <Col>
>             <Tooltip
>               title={formattedErrorText ?? TABLE_METADATA_LAST_UPDATED_HELP}
> ```

seems like `formattedErrorText` can be removed, this can be `metadata.lastUpdateError && TABLE_METADATA_LAST_UPDATED_HELP`
___
*[`pkg/ui/workspaces/cluster-ui/src/components/tooltip/tooltip.module.scss` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132613#-O9GArlp9yKbM6u4u-E1:-O9GArlp9yKbM6u4u-E2:b-8rcjqh) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a3b57fb09900fd0b1ecee907cfb6b9c2aab6caa/pkg/ui/workspaces/cluster-ui/src/components/tooltip/tooltip.module.scss#L12)):*
> ```SCSS
> }
> 
> .container {
> ```

Do we want this to be universal for tooltips?

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132613)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @angles-n-daemons and @kyle-a-wong)

___
*[`pkg/ui/workspaces/cluster-ui/src/databaseDetailsV2/tablesView.tsx` line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132613#-O9GBFL2Eh7ocYt7AXQN:-O9GGpBCDvycgzsD40fm:bdbqdgs) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a3b57fb09900fd0b1ecee907cfb6b9c2aab6caa/pkg/ui/workspaces/cluster-ui/src/databaseDetailsV2/tablesView.tsx#L140)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

is forceUpperCase necessary?
</blockquote></details>

It's not necessary since we're supplying the value directly but I don't think supplying the prop hurts, since it'll just be a noop.
___
*[`pkg/ui/workspaces/cluster-ui/src/tableDetailsV2/tableOverview.tsx` line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132613#-O9GAqGV2Mr5gSoA5Nm8:-O9GGZcjDCM_P0q2npBN:b-grb9pv) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a3b57fb09900fd0b1ecee907cfb6b9c2aab6caa/pkg/ui/workspaces/cluster-ui/src/tableDetailsV2/tableOverview.tsx#L77)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

seems like `formattedErrorText` can be removed, this can be `metadata.lastUpdateError && TABLE_METADATA_LAST_UPDATED_HELP`
</blockquote></details>

I don't quite follow this suggestion - would't that cause the tooltip text to only be shown if there's an error? We want the standard tooltip mesage to be shown if there is no error and the formatted error text when we do have one.
___
*[`pkg/ui/workspaces/cluster-ui/src/components/tooltip/tooltip.module.scss` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132613#-O9GArlp9yKbM6u4u-E1:-O9GGhGk0xTnhDdCna4V:b-7xtei2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a3b57fb09900fd0b1ecee907cfb6b9c2aab6caa/pkg/ui/workspaces/cluster-ui/src/components/tooltip/tooltip.module.scss#L12)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

Do we want this to be universal for tooltips?
</blockquote></details>

Yeah.

**Review by angles-n-daemons — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132613#-:-O9PklaKBkYBvYVn8SKA:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kyle-a-wong and @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/tableDetailsV2/tableOverview.tsx` line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132613#-O9GAqGV2Mr5gSoA5Nm8:-O9PkbN40pfn3wumUAjf:b2svmaa) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a3b57fb09900fd0b1ecee907cfb6b9c2aab6caa/pkg/ui/workspaces/cluster-ui/src/tableDetailsV2/tableOverview.tsx#L77)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

I don't quite follow this suggestion - would't that cause the tooltip text to only be shown if there's an error? We want the standard tooltip mesage to be shown if there is no error and the formatted error text when we do have one.
</blockquote></details>

my eyes didn't work when I wrote this, I read `??` as `&&`, definitely makes more sense now

**Comment by xinhaoz** [comment]
Failures aren't related to the ui pkg.
bors r+

**Pull request merged**
