### PR TITLE
sql: more informative error messages when creating interleaved tables/indexes

### PR DESCRIPTION
**Pull request by richardwu**
Release notes: none

cc: @dianasaur323

### CODE REVIEW

**Comment by jordanlewis** [comment]
:lgtm: except possibly the choice of [] instead of () - I think we use () in other messages but I could be wrong? Could you do a quick search for how columns are normally represented in error messages?

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20165#-:-L-2q5ybDL1Nj9-kzpDg:bb45byl)*

**Comment by dianasaur323** [comment]
:lgtm: gracias!!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20165#-:-L-2rYD2p_wXsE-79w5g:b-o1tl35)*

**Comment by richardwu** [comment]
Ah good point, updated [] to () as well as changed the errors to pgerrors.

(Also fixed some of the FK error messages to use ()).

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20165#-:-L-4BuysndRg-1oyKFQ8:b99lr7p)*

**Comment by jordanlewis** [comment]
Wait, I didn't realize that there were so many other places where we use []. @knz do you think this is an important thing not to change? Do we have a coherent strategy for this? If we're unsure I think you should revert the change to the FK error messages and merge as-is and we can fix the errors in one pass later.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20165#-:-L-7N_4JtOtLEcD2gcNA:brigbl2)*

**Comment by richardwu** [comment]
Alright, I've stashed out the fixes in FK for now.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20165#-:-L-9f62kKWudeFgbkP3A:bu3vojw)*

**Pull request merged**
