### PR TITLE
acceptance: fix spurious docker test failure `unexpected extra event &{0 die} (after [])`

### PR DESCRIPTION
**Pull request by knz**
Needed for #86049.

The root cause of the issue is that the docker container for the DB nodes were crashing, because the test framework **was incorrectly deleting the data/log directory before shutting down the nodes**.

However, this root cause was mostly hidden because of another mistake: the assertion that checks the health of the nodes was not doing its job properly in most cases. So it believed the nodes were healthy when in fact they were not.

This PR fixes both problems.

Informs #58955.
Informs #58951.
Informs #58218.

Release justification: non-production code changes

### CODE REVIEW

**Comment by knz** [comment]
As far as I can see, this problem has existed for a very long time. Throughout most of its existence, it was lucky that 15ms was nearly never enough in Assert to retrieve the docker failure event from the node container. I guess the docker controller has become faster in recent versions.

**Review by rickystewart — APPROVED** [review]

**Comment by rickystewart** [comment]
Awesome, it's great to finally see this fixed.

**Review by renatolabs — APPROVED** [review]
Thanks for fixing this! :tada: Left a few minor comments.

> Reviewed 1 of 1 files at r1, 3 of 3 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, 2 of 2 files at r11, 1 of 1 files at r12, 2 of 2 files at r13, 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86862#-:-NAKcwp57eZDrtKpcs7B:b77bmcy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @tbg)

___
*[`pkg/acceptance/cluster/dockercluster.go` line 591 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/86862#-NAKbPX8AjOm4olkCjoc:-NAKbPX8AjOm4olkCjod:b-tfvted) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcb2c35ce553ce1b7a34ac29347f783631d8e119/pkg/acceptance/cluster/dockercluster.go#L591)):*
> ```Go
> 
> func (l *DockerCluster) monitor(ctx context.Context, monitorDone chan struct{}) {
> 	defer func() { close(monitorDone) }()
> ```

Nit: why not `defer close(monitorDone)`?
___
*[`pkg/acceptance/cluster/dockercluster.go` line 650 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/86862#-NAKbVQJ9HLNBh8PgJyn:-NAKbVQJ9HLNBh8PgJyo:bpw8009) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcb2c35ce553ce1b7a34ac29347f783631d8e119/pkg/acceptance/cluster/dockercluster.go#L650)):*
> ```Go
> 	l.monitorCtx, l.monitorCtxCancelFunc = context.WithCancel(context.Background())
> 	l.monitorDone = make(chan struct{})
> 	go l.monitor(ctx, l.monitorDone)
> ```

Nit: it would make sense if `monitorDone` were always associated with the `monitor()` call. In other words, not passing a channel to the `monitor` function and closing `monitorDone` there instead.
___
*[`pkg/acceptance/cluster/dockercluster.go` line 684 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/86862#-NAKcNYSEXzej-h3dNx4:-NAKcNYTCaOve4tFBgJB:b-un7h42) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca82cb63ab20c44a48536bc494a4828414b35cfb/pkg/acceptance/cluster/dockercluster.go#L684)):*
> ```Go
> 		// The expected event channel is buffered and should contain
> 		// all expected events already.
> 		const almostZero = 15 * time.Millisecond
> ```

Curious: if we expect the channel to contain all expected events at this point, why do we wait 15ms?
___
*[`pkg/acceptance/cluster/dockercluster.go` line 689 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/86862#-NAKcX7nBvskqAr9tG91:-NAKcX7nBvskqAr9tG92:b6yrle2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca82cb63ab20c44a48536bc494a4828414b35cfb/pkg/acceptance/cluster/dockercluster.go#L689)):*
> ```Go
> 			break
> 		}
> 		t.Logf("expecting event: %v", exp)
> ```

Could we change these log messages to use `%#v` instead, for a more readable output?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86862)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @renatolabs, and @tbg)

___
*[`pkg/acceptance/cluster/dockercluster.go` line 591 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/86862#-NAKbPX8AjOm4olkCjoc:-NAKmuMACVTaWQGjWYRH:byjewhh) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcb2c35ce553ce1b7a34ac29347f783631d8e119/pkg/acceptance/cluster/dockercluster.go#L591)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Nit: why not `defer close(monitorDone)`?
</blockquote></details>

sure why not
___
*[`pkg/acceptance/cluster/dockercluster.go` line 684 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/86862#-NAKcNYSEXzej-h3dNx4:-NAKn1Il6At1mwNNOtNt:b3h5xor) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca82cb63ab20c44a48536bc494a4828414b35cfb/pkg/acceptance/cluster/dockercluster.go#L684)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Curious: if we expect the channel to contain all expected events at this point, why do we wait 15ms?
</blockquote></details>

If we specify zero, the timeout branch will be taken and the channel will not be read, resulting in incorrect behavior.
___
*[`pkg/acceptance/cluster/dockercluster.go` line 689 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/86862#-NAKcX7nBvskqAr9tG91:-NAKnEb6CzUPlIzHhmrH:b-3d5991) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca82cb63ab20c44a48536bc494a4828414b35cfb/pkg/acceptance/cluster/dockercluster.go#L689)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Could we change these log messages to use `%#v` instead, for a more readable output?
</blockquote></details>

In general I'd be friendly to this idea, but given how simple the struct is, it's not worth it here.

**Pull request merged**
