### PR TITLE
storage: refactor interfaces for constructing new engines

### PR DESCRIPTION
**Pull request by jbowens**
Refactor several of the various methods for constructing Engines into a
single Open method that supports configuration through the functional
options pattern. This removes some boilerplate configuration.

An eventual goal of this refactor is to tighten the storage package
interface to a narrower, more controlled interface.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
Thanks for doing this!
:lgtm: 

> Reviewed 42 of 42 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67723#-:-MgBCqpMA9XDAlu7OMSQ:bpwuzbv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @jbowens)

___
*[pkg/storage/mvcc_incremental_iterator_test.go, line 914 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67723#-MgBCkSs32wmEJLYzidj:-MgBCkSs32wmEJLYzidk:b-qz1okc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4fad788e508756cb3949dc5c19f9f3fb0e31dcd/pkg/storage/mvcc_incremental_iterator_test.go#L914)):*
> ```Go
> 	// copying into manually created sstables.
> 	ctx := context.Background()
> 	db1 := NewInMemForTesting(ctx, roachpb.Attributes{}, 10<<20)
> ```

same question about storeSize.
___
*[pkg/storage/pebble_test.go, line 433 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67723#-MgBAbkE34M-5ktoZ86k:-MgBAbkFD_hQ2BIh3bGA:b-fh5wmt) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4fad788e508756cb3949dc5c19f9f3fb0e31dcd/pkg/storage/pebble_test.go#L433)):*
> ```Go
> 		roachpb.Attributes{},
> 		1<<20,   /* cacheSize */
> 		512<<20, /* storeSize */
> ```

what happened to the storeSize in the new code (also got dropped in some other tests)? unnecessary?
___
*[pkg/storage/metamorphic/generator.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67723#-MgB9R2FDTiXvFPKCK6y:-MgB9R2FDTiXvFPKCK6z:b7zmrd8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2766b9e77badfda4cd9dc4ab176551b34abdbe87/pkg/storage/metamorphic/generator.go#L44)):*
> ```Go
> 		storage.Filesystem(path),
> 		storage.CacheSize(1<<20 /* 1 MiB */),
> 		storage.Settings(cluster.MakeTestingClusterSettings()))
> ```

looks like we are now randomizing the settings while before we were not, yes?

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67723)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

___
*[pkg/storage/mvcc_incremental_iterator_test.go, line 914 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67723#-MgBCkSs32wmEJLYzidj:-MgBeIXl7Nxmu8zhBpnX:bvd9hzi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4fad788e508756cb3949dc5c19f9f3fb0e31dcd/pkg/storage/mvcc_incremental_iterator_test.go#L914)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

same question about storeSize.
</blockquote></details>

also unnecessary here
___
*[pkg/storage/pebble_test.go, line 433 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67723#-MgBAbkE34M-5ktoZ86k:-MgBcq8BCuvTjR0RzT8P:b-ew2hkv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4fad788e508756cb3949dc5c19f9f3fb0e31dcd/pkg/storage/pebble_test.go#L433)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

what happened to the storeSize in the new code (also got dropped in some other tests)? unnecessary?
</blockquote></details>

Yeah, intentional drop because it's unnecessary here.
___
*[pkg/storage/metamorphic/generator.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67723#-MgB9R2FDTiXvFPKCK6y:-MgBeszC-xWohKrW9gfI:bmin82c) ([raw file](https://github.com/cockroachdb/cockroach/blob/2766b9e77badfda4cd9dc4ab176551b34abdbe87/pkg/storage/metamorphic/generator.go#L44)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

looks like we are now randomizing the settings while before we were not, yes?
</blockquote></details>

`makeStorageConfig` was randomizing them too:
```
func makeStorageConfig(path string) base.StorageConfig {
	return base.StorageConfig{
		Dir:      path,
		Settings: cluster.MakeTestingClusterSettings(),
	}
}
```

**Review by jbowens — COMMENTED** [review]
TFTR!

bors r=sumeerbhola

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67723#-:-MgGHCG18lYA7p7aKYQz:b-6zs9ju)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal, @otan, and @sumeerbhola)

**Comment by jbowens** [comment]
bors r=sumeerbhola

**Comment by jbowens** [comment]
bors r=sumeerbhola

**Pull request merged**
