### PR TITLE
server,rpc: block decommissioned node from interacting with the cluster

### PR DESCRIPTION
**Pull request by tbg**
This PR completes the work started in #54936 by introducing a component that
keeps track of decommissioned nodes and hooks it up to the RPC layer, where it
is used to prevent RPC-layer heartbeats between the cluster and decommissioned
nodes. Since these heartbeats are a prerequisite for opening a connection in
either direction, by failing these heartbeats we are effectively preventing
decommissioned nodes from interacting with the cluster.

First commits from #54936. New here:

- keys: introduce NodeTombstoneKey
- server: introduce node tombstone storage

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
Friendly ping @irfansharif

**Review by irfansharif — APPROVED** [review]
:lgtm:, but while I have you here I had a few questions. Is the following hazard possible? I think it is (though I'm less clear if we care about it, and if so, why.)

- Cluster comprised of n1, n2, n3
- User decommissions n3 through n2
- n2 updates n3's liveness record in KV, marking it as fully decommissioned
- n2 crashes before invoking OnNodeDecommissioned, so it doesn't place the n3 marker on disk
- n2 restarts, and not finding anything on disk to suggest otherwise, connects to n3 (it still hasn't learned through gossip that n3 is decommissioned
- ???

What does this mean for long running migrations? If the orchestrator process (say on n1) is looking to push out feature gates to n2, if n2 still has an open connection to n3 (admittedly the window where this is possible is very short), isn't that _not_ the kind of guarantee want? I'm actually unclear on what happens if the connection to n3 _is_ maintained.

Given the authoritative source of "all decommissioned nodes" is still KV (as opposed to store local keys). If the open connection to n3 is unacceptable (again, unclear on the implications), would we need the orchestrator to inform all live nodes about the current set of decomm'ed nodes? And then wait for each one to guarantee that they've persisted this store local key + disconnected any relevant open connections?

> Reviewed 4 of 4 files at r8, 4 of 5 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55286#-:-MJYZKGO1QuT-p8u-m-4:bd4rg2d)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif and @tbg)

___
*[pkg/keys/printer.go, line 209 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/55286#-MJYQARwD_YRJxrxgdkq:-MJYQARwD_YRJxrxgdkr:b3c7u1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/48bd823d3e686e34a4589bc6293069f9de733b14/pkg/keys/printer.go#L209)):*
> ```Go
> 		return fmt.Sprintf("<invalid: %s>", err)
> 	}
> 	return fmt.Sprint(nodeID)
> ```

I'm not sure what's custom here in pkg/keys, but what about "n<nodeID>"?
___
*[pkg/rpc/context.go, line 1207 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/55286#-MJYUNbI6b60nkyIilpL:-MJYUNbI6b60nkyIilpM:b7f4z1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/168c4904a5cb61f0eb004a7c414d31e8742b4f22/pkg/rpc/context.go#L1207)):*
> ```Go
> 					checkVersion(goCtx, ctx.Settings, response.ServerVersion),
> 					"version compatibility check failed on ping response")
> 				if err != nil {
> ```

This is always true.
___
*[pkg/server/connectivity_test.go, line 363 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/55286#-MJYT3GAA7NN_xHnu252:-MJYT3GAA7NN_xHnu253:bmfakzz) ([raw file](https://github.com/cockroachdb/cockroach/blob/168c4904a5cb61f0eb004a7c414d31e8742b4f22/pkg/server/connectivity_test.go#L363)):*
> ```Go
> 	defer tc.Stopper().Stop(ctx)
> 
> 	//tc.StopServer(2) // stop n3
> ```

Stray line?
___
*[pkg/server/node_tombstone_storage.go, line 118 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/55286#-MJYVuKR1OUbb_xv1IuG:-MJYVuKR1OUbb_xv1IuH:b-dhs4w) ([raw file](https://github.com/cockroachdb/cockroach/blob/168c4904a5cb61f0eb004a7c414d31e8742b4f22/pkg/server/node_tombstone_storage.go#L118)):*
> ```Go
> 
> 	// We've populated the cache, now write through to disk.
> ```

[nit] Remove empty lines here and right below.

**Review by tbg — COMMENTED** [review]
TFTR!

re: your comment, yes, the blocklist is best-effort. We discussed this somewhere on the RFC PR (I believe around [here](https://github.com/cockroachdb/cockroach/pull/48843#pullrequestreview-427775712)), and the outcome was that basically the operator is ultimately still in charge of not bringing back nodes that are not allowed to come back, though we will make it really hard for them to break something in that way (because the decommissioned status usually blocks the nodes). So the question is whether we're "done" after this PR or if we ought to do more. One simple safety hatch is that the orchestrator, upon looking at the liveness table, makes sure any DECOMMISSIONING nodes are not live. We could also push out decommission bits proactively, etc, and actively force a pass through the open connections in the RPC layer, but that seems more trouble than is worth.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55286#-:-MJaOa9_1WxL4qJPyveN:b7cxh3z)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif)

___
*[pkg/keys/printer.go, line 209 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/55286#-MJYQARwD_YRJxrxgdkq:-MJaNBj9BgvDH7Q8p85_:b-qgg5r) ([raw file](https://github.com/cockroachdb/cockroach/blob/48bd823d3e686e34a4589bc6293069f9de733b14/pkg/keys/printer.go#L209)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

I'm not sure what's custom here in pkg/keys, but what about "n<nodeID>"?
</blockquote></details>

I'm not sure what you're suggesting, can you clarify?
___
*[pkg/rpc/context.go, line 1207 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/55286#-MJYUNbI6b60nkyIilpL:-MJaNpXM9fTiwxipf41K:b-opbvbt) ([raw file](https://github.com/cockroachdb/cockroach/blob/168c4904a5cb61f0eb004a7c414d31e8742b4f22/pkg/rpc/context.go#L1207)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

This is always true.
</blockquote></details>

No, `errors.Wrap(nil, _)` is `nil`.
___
*[pkg/server/connectivity_test.go, line 363 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/55286#-MJYT3GAA7NN_xHnu252:-MJaMvJ57St-oFUCj9ev:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/168c4904a5cb61f0eb004a7c414d31e8742b4f22/pkg/server/connectivity_test.go#L363)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Stray line?
</blockquote></details>

Done.
___
*[pkg/server/node_tombstone_storage.go, line 118 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/55286#-MJYVuKR1OUbb_xv1IuG:-MJaN4xW8k4dKE5Cx4p1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/168c4904a5cb61f0eb004a7c414d31e8742b4f22/pkg/server/node_tombstone_storage.go#L118)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

[nit] Remove empty lines here and right below.
</blockquote></details>

Done.

**Comment by tbg** [comment]
bors r=irfansharif

**Comment by irfansharif** [comment]
> I'm not sure what you're suggesting, can you clarify?

Just meant pretty printing the node ID as "n123" instead of just 123. Eh, wtvs.

**Comment by tbg** [comment]
:+1: opened new PR for that.

**Pull request merged**
