### PR TITLE
kv/storage: Track the locality of incoming requests

### PR DESCRIPTION
**Pull request by a-robinson**
The first step of #13232/#13233. This isn't truly being used yet, but sending out to get some feedback and make later reviews less painful. There are a couple TODOs in replica_stats.go where I may find we should tweak things slightly based on how implementing the allocator changes goes.

@BramGruneir

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13426)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1, 3 of 3 files at r2, 3 of 3 files at r3.
Review status: 8 of 12 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/kv/dist_sender.go, line 499 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcJCw2E2XsNdvQ4QBwo:-KcJCw2E2XsNdvQ4QBwp:b-jz1l4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/702e88897d32ba3f80e84adb7f381b14fc656a48/pkg/kv/dist_sender.go#L499)):*
> ```Go
> 	// Attach the local node ID to each request.
> 	if ba.Header.GatewayNodeID == 0 {
> 		if ds.gossip != nil {
> ```

`if ba.Header.GatewayNodeID == 0 && ds.gossip != nil`?

---

*[pkg/storage/replica_stats.go, line 40 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcJE8aKueM_m2wTq8aG:-KcJE8aLCLwwpT3xj4Gb:b-yjuoah) ([raw file](https://github.com/cockroachdb/cockroach/blob/3913b1a521d236187e16343e258e8f927af4a188/pkg/storage/replica_stats.go#L40)):*
> ```Go
> 		syncutil.Mutex
> 		// TODO(a-robinson): Use a form of exponential decay on the counts rather
> 		// than hard resets back to zero?
> ```

I'm sure there is some existing code to leverage for this somewhere. Googling pointed to https://github.com/facebookgo/metrics/blob/master/ewma.go. The TODO is fine for this PR.

---

*[pkg/storage/replica_stats.go, line 78 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcJEgjNXubMEnHfW2CD:-KcJEgjNXubMEnHfW2CE:bxm66er) ([raw file](https://github.com/cockroachdb/cockroach/blob/3913b1a521d236187e16343e258e8f927af4a188/pkg/storage/replica_stats.go#L78)):*
> ```Go
> }
> 
> func (rs *replicaStats) getRequestCounts() (perLocalityCounts, time.Duration) {
> ```

Need a comment document the behavior here. Sort of surprising that this resets the request counts map. 

---

*[pkg/storage/replica_stats_test.go, line 31 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcJFOImmdk_FXjgZH8R:-KcJFOImmdk_FXjgZH8S:bqvantf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3913b1a521d236187e16343e258e8f927af4a188/pkg/storage/replica_stats_test.go#L31)):*
> ```Go
> 				{Key: "region", Value: "us-east1"},
> 				{Key: "zone", Value: "us-east1-a"},
> 			},
> ```

Can you use `Locality.Set("region=us-east1,zone=us-east1-a")`, perhaps via some helper `makeLocality` closure?

---

*[pkg/storage/replica_stats_test.go, line 103 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcJFtQQIZ5JE3FUPbkV:-KcJFtQQIZ5JE3FUPbkW:bmpx0ka) ([raw file](https://github.com/cockroachdb/cockroach/blob/3913b1a521d236187e16343e258e8f927af4a188/pkg/storage/replica_stats_test.go#L103)):*
> ```Go
> 				i, len(actual), len(tc.expected), actual)
> 		}
> 		for k, expV := range tc.expected {
> ```

Can you use `reflect.DeepEqual` and `pretty.Diff` here? The latter is pretty nifty for tests.

---

*[pkg/storage/store_pool.go, line 532 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcJDc2ofngcFTi2Ax3z:-KcJDc2ofngcFTi2Ax4-:b-hvxt77) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eefc568f5f5a7d64f283000da238c695d490984/pkg/storage/store_pool.go#L532)):*
> ```Go
> 		return roachpb.Locality{}
> 	}
> 	return locality
> ```

I think this is equivalent to `return sp.localitiesMu.nodeLocalities[nodeID]`. No harm in using the Go behavior that a non-existent map entry returns the zero value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-:-KcJG0kCsnB8W51hGEh_:bnfp4nl)*

**Comment by BramGruneir** [comment]
Reviewed 4 of 4 files at r1, 3 of 3 files at r2, 3 of 3 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[pkg/storage/replica_stats.go, line 64 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcJIgm7JuCXfUsz79xy:-KcJIgm7JuCXfUsz79xz:b2xeyfg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3913b1a521d236187e16343e258e8f927af4a188/pkg/storage/replica_stats.go#L64)):*
> ```Go
> 	}
> 
> 	// TODO(a-robinson): Consider other ways of tracking this. Should we
> ```

The order of the labels is important.  It's possible to have this setup:
region=us,dc=west,rack=2
region=eur,dc=west,rack=2

So I think this is going to have to be a bit more complicated than simply summing the common tiers.  

It's also possible to have an even crazier system of:
region=us,dc=west,rack=2
region=eur,subregion=scan,dc=west,rack=2

---

*[pkg/storage/replica_stats_test.go, line 119 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcJLM6uQVkyvNTF4FDz:-KcJLM6uQVkyvNTF4FE-:bfbgtsl) ([raw file](https://github.com/cockroachdb/cockroach/blob/3913b1a521d236187e16343e258e8f927af4a188/pkg/storage/replica_stats_test.go#L119)):*
> ```Go
> 			}
> 		}
> 	}
> ```

Can you add some stranger tests cases?  
And some where a node doesn't have a locality?

Maybe use subtests as well to make it easier to parse the output.

---

*[pkg/storage/store_pool.go, line 164 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcJEvTaB3gemmrJ6ESU:-KcJEvTaB3gemmrJ6ESV:b-coul8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/936e62785d0f6a342d2256f749c7d0db477a67d9/pkg/storage/store_pool.go#L164)):*
> ```Go
> 	declinedReservationsTimeout time.Duration
> 	deterministic               bool
> 	detailsMu                   struct {
> ```

So why not just put nodeLocalities in the same mutex as the storeDetails?  The added complexity of having two mutexes worries me a bit.  Any operation that requires both could become disjoint fairly easily.

---

*[pkg/storage/store_pool.go, line 250 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcJFd0cmfV59TBzhnP2:-KcJFd0cmfV59TBzhnP3:bkqcscp) ([raw file](https://github.com/cockroachdb/cockroach/blob/936e62785d0f6a342d2256f749c7d0db477a67d9/pkg/storage/store_pool.go#L250)):*
> ```Go
> 	detail.lastUpdatedTime = sp.clock.PhysicalTime()
> 	sp.detailsMu.Unlock()
> ```

Right here there is the potential to have two different values.  It's minor, but the role of the nodeLocalities is sure to grow.  Having a single mutex would avoid this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426)*

**Comment by a-robinson** [comment]
TFTR!

---

Review status: 3 of 12 files reviewed at latest revision, 10 unresolved discussions.

---

*[pkg/kv/dist_sender.go, line 499 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcJCw2E2XsNdvQ4QBwo:-KcK-pFGyzN6K5tbqcDP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/702e88897d32ba3f80e84adb7f381b14fc656a48/pkg/kv/dist_sender.go#L499)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`if ba.Header.GatewayNodeID == 0 && ds.gossip != nil`?
</blockquote></details>

Done.

---

*[pkg/storage/replica_stats.go, line 40 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcJE8aKueM_m2wTq8aG:-KcK-tPrhKcNHlQYhOvC:b-vjacug) ([raw file](https://github.com/cockroachdb/cockroach/blob/3913b1a521d236187e16343e258e8f927af4a188/pkg/storage/replica_stats.go#L40)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm sure there is some existing code to leverage for this somewhere. Googling pointed to https://github.com/facebookgo/metrics/blob/master/ewma.go. The TODO is fine for this PR.
</blockquote></details>

Ack, thanks. I did some brief googling last week but didn't spend too long on it.

---

*[pkg/storage/replica_stats.go, line 64 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcJIgm7JuCXfUsz79xy:-KcK6NUGeEYS3Ykm54bl:btr7trj) ([raw file](https://github.com/cockroachdb/cockroach/blob/3913b1a521d236187e16343e258e8f927af4a188/pkg/storage/replica_stats.go#L64)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

The order of the labels is important.  It's possible to have this setup:
region=us,dc=west,rack=2
region=eur,dc=west,rack=2

So I think this is going to have to be a bit more complicated than simply summing the common tiers.  

It's also possible to have an even crazier system of:
region=us,dc=west,rack=2
region=eur,subregion=scan,dc=west,rack=2




</blockquote></details>

So I was hoping that we could use the local node's labels to determine the order, but you're right that if other nodes have different sets of keys then doing so won't always work, and this definitely makes data on things like rack numbers completely worthless.

I expect that the allocation decisions will probably want to group by the tiers at which other replicas for the range are located, so maybe we could just record by the first tier at which the other replicas' localities differ from this replica's locality? The big issue with that is that it could change over the life of a replica, but it wouldn't be too frequently and we could reset the map when that happens.

Do you have suggestions on how we should store this? I'm wondering whether it'd be better to just record it per gateway node ID and deal with the localities when making allocation decisions. There was concern on the RFC over whether that'd use too much memory, but we'll also use a lot of memory if we have to store a bunch of long locality strings.

---

*[pkg/storage/replica_stats.go, line 78 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcJEgjNXubMEnHfW2CD:-KcK0EfmLSBpCBjp1SJf:b-n1gs02) ([raw file](https://github.com/cockroachdb/cockroach/blob/3913b1a521d236187e16343e258e8f927af4a188/pkg/storage/replica_stats.go#L78)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Need a comment document the behavior here. Sort of surprising that this resets the request counts map. 
</blockquote></details>

Good point. I've chosen to just split out a reset function instead.

---

*[pkg/storage/replica_stats_test.go, line 31 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcJFOImmdk_FXjgZH8R:-KcKEKj9kZ2tS2rGL99g:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3913b1a521d236187e16343e258e8f927af4a188/pkg/storage/replica_stats_test.go#L31)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Can you use `Locality.Set("region=us-east1,zone=us-east1-a")`, perhaps via some helper `makeLocality` closure?
</blockquote></details>

Done.

---

*[pkg/storage/replica_stats_test.go, line 103 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcJFtQQIZ5JE3FUPbkV:-KcKCK7vTQLoPrRu2_-g:boycyjp) ([raw file](https://github.com/cockroachdb/cockroach/blob/3913b1a521d236187e16343e258e8f927af4a188/pkg/storage/replica_stats_test.go#L103)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Can you use `reflect.DeepEqual` and `pretty.Diff` here? The latter is pretty nifty for tests.
</blockquote></details>

Ah yeah, I should have used those in the first place. `pretty.Diff` is indeed awesome.

---

*[pkg/storage/replica_stats_test.go, line 119 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcJLM6uQVkyvNTF4FDz:-KcKGyE3ijWtSvnrY7Db:b2ueoos) ([raw file](https://github.com/cockroachdb/cockroach/blob/3913b1a521d236187e16343e258e8f927af4a188/pkg/storage/replica_stats_test.go#L119)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Can you add some stranger tests cases?  
And some where a node doesn't have a locality?

Maybe use subtests as well to make it easier to parse the output.
</blockquote></details>

We'll certainly want fancier test cases for the logic that actually makes allocation decisions, but what other sorts of cases do we need here? It may depend on the conversation above about what the perLocalityCounts type should be.

---

*[pkg/storage/store_pool.go, line 164 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcJEvTaB3gemmrJ6ESU:-KcK4ktwExpg1NdztHDH:b-atr8kb) ([raw file](https://github.com/cockroachdb/cockroach/blob/936e62785d0f6a342d2256f749c7d0db477a67d9/pkg/storage/store_pool.go#L164)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

So why not just put nodeLocalities in the same mutex as the storeDetails?  The added complexity of having two mutexes worries me a bit.  Any operation that requires both could become disjoint fairly easily.
</blockquote></details>

As written in the commit message, I'm a little worried about blocking every `(*replica).Send` call on `storeDetails` operations. Normally I'd lean toward code simplicity, but `(*replica).Send` seems like a pretty critical code path. I've added a comment in case you think that helps.

---

*[pkg/storage/store_pool.go, line 250 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcJFd0cmfV59TBzhnP2:-KcK5eYp1mdYWZ6CsS7s:b-jjxz5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/936e62785d0f6a342d2256f749c7d0db477a67d9/pkg/storage/store_pool.go#L250)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Right here there is the potential to have two different values.  It's minor, but the role of the nodeLocalities is sure to grow.  Having a single mutex would avoid this.
</blockquote></details>

Right, but as far as I could tell there isn't any existing code that actually reads both of them at the same time anyway. Would you prefer if I made sure we held both the locks while doing these updates?

---

*[pkg/storage/store_pool.go, line 532 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcJDc2ofngcFTi2Ax3z:-KcK4cJLJbdKuEHdOPAS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eefc568f5f5a7d64f283000da238c695d490984/pkg/storage/store_pool.go#L532)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think this is equivalent to `return sp.localitiesMu.nodeLocalities[nodeID]`. No harm in using the Go behavior that a non-existent map entry returns the zero value.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-:-KcKHVikBIJj3NWVJqgL:b-814g8k)*

**Comment by BramGruneir** [comment]
Reviewed 9 of 9 files at r5, 3 of 3 files at r6, 3 of 3 files at r7, 4 of 4 files at r8.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[pkg/storage/replica_stats.go, line 64 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcJIgm7JuCXfUsz79xy:-KcOPT2zoo0fF-vEM4-m:b-lqg6hz) ([raw file](https://github.com/cockroachdb/cockroach/blob/3913b1a521d236187e16343e258e8f927af4a188/pkg/storage/replica_stats.go#L64)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

So I was hoping that we could use the local node's labels to determine the order, but you're right that if other nodes have different sets of keys then doing so won't always work, and this definitely makes data on things like rack numbers completely worthless.

I expect that the allocation decisions will probably want to group by the tiers at which other replicas for the range are located, so maybe we could just record by the first tier at which the other replicas' localities differ from this replica's locality? The big issue with that is that it could change over the life of a replica, but it wouldn't be too frequently and we could reset the map when that happens.

Do you have suggestions on how we should store this? I'm wondering whether it'd be better to just record it per gateway node ID and deal with the localities when making allocation decisions. There was concern on the RFC over whether that'd use too much memory, but we'll also use a lot of memory if we have to store a bunch of long locality strings.
</blockquote></details>

So as discussed offline, I think it would be best to use the existing `metadata.go DiversityScore` function.  Instead of trying to keep everything in a map of tiers or a trie or something that gets quite messy, simply storing a queue of the last X localities (or maybe a sampling of them from the last N minutes) and calculating the replica with the lowest diversity score against this queue should be quick, clean and precise. 

---

*[pkg/storage/replica_stats_test.go, line 119 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcJLM6uQVkyvNTF4FDz:-KcOgjCi4aj-LS01dACO:b-hbe8jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3913b1a521d236187e16343e258e8f927af4a188/pkg/storage/replica_stats_test.go#L119)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

We'll certainly want fancier test cases for the logic that actually makes allocation decisions, but what other sorts of cases do we need here? It may depend on the conversation above about what the perLocalityCounts type should be.
</blockquote></details>

Some cases I can think of offhand, but of course, only implement ones that makes sense to test the algorithm:
1) Different number of localities tiers  1 and 2
```
region=us-east1,zone=us-east1-a
region=us-east1
region=us-west1,zone=us-east1-a
(no locality)
```

2) Localities with lower tiers that match while higher ones don't.
```
region=a,zone=1
region=b,zone=1
``` 

3) No locality info at all

4) Different lower tiers
```
a1=1,a2=1,a3=1
a1=2,b2=1,b3=1
a1=2,b2=2,c3=1
```

---

*[pkg/storage/store_pool.go, line 164 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcJEvTaB3gemmrJ6ESU:-KcORj5FjvrcwO9Df3ed:b-n3s3p7) ([raw file](https://github.com/cockroachdb/cockroach/blob/936e62785d0f6a342d2256f749c7d0db477a67d9/pkg/storage/store_pool.go#L164)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

As written in the commit message, I'm a little worried about blocking every `(*replica).Send` call on `storeDetails` operations. Normally I'd lean toward code simplicity, but `(*replica).Send` seems like a pretty critical code path. I've added a comment in case you think that helps.
</blockquote></details>

SGTM, if it's a problem, it would be easy to fix.

---

*[pkg/storage/store_pool.go, line 250 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcJFd0cmfV59TBzhnP2:-KcOQZ_348RBC_5nluPH:br04tr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/936e62785d0f6a342d2256f749c7d0db477a67d9/pkg/storage/store_pool.go#L250)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Right, but as far as I could tell there isn't any existing code that actually reads both of them at the same time anyway. Would you prefer if I made sure we held both the locks while doing these updates?
</blockquote></details>

In the allocator, `RebalanceTarget`, `AllocatorTarget` and `RemoveTarget` all use both.  But I don't think it's a concern if there is a minor race here. It wouldn't be harmful if there's a slight difference in the locality values.

Do not require both, ever, that could cause deadlocks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426)*

**Comment by a-robinson** [comment]
Sorry for the delay on this - I've switched the perLocalityCounts map in a pretty meaningful way, so PTAL

---

Review status: 6 of 12 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[pkg/storage/replica_stats.go, line 64 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcJIgm7JuCXfUsz79xy:-KcTqIJg0O0Wqz1Fenn1:b204m84) ([raw file](https://github.com/cockroachdb/cockroach/blob/3913b1a521d236187e16343e258e8f927af4a188/pkg/storage/replica_stats.go#L64)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

So as discussed offline, I think it would be best to use the existing `metadata.go DiversityScore` function.  Instead of trying to keep everything in a map of tiers or a trie or something that gets quite messy, simply storing a queue of the last X localities (or maybe a sampling of them from the last N minutes) and calculating the replica with the lowest diversity score against this queue should be quick, clean and precise. 
</blockquote></details>

So I did a little more thinking and came up with an approach to minimize memory usage without actually having to drop any information. How does this look?

---

*[pkg/storage/replica_stats_test.go, line 119 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcJLM6uQVkyvNTF4FDz:-KcTqaz4w1bOXbnRoqgx:b-a14d9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/3913b1a521d236187e16343e258e8f927af4a188/pkg/storage/replica_stats_test.go#L119)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Some cases I can think of offhand, but of course, only implement ones that makes sense to test the algorithm:
1) Different number of localities tiers  1 and 2
```
region=us-east1,zone=us-east1-a
region=us-east1
region=us-west1,zone=us-east1-a
(no locality)
```

2) Localities with lower tiers that match while higher ones don't.
```
region=a,zone=1
region=b,zone=1
``` 

3) No locality info at all

4) Different lower tiers
```
a1=1,a2=1,a3=1
a1=2,b2=1,b3=1
a1=2,b2=2,c3=1
```


</blockquote></details>

Sure, I've improved the test to make that possible, although they aren't stressing the code much more than before. They'll be much more important when testing the actual allocation algorithm.

---

*[pkg/storage/store_pool.go, line 250 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcJFd0cmfV59TBzhnP2:-KcPCVpISPE_L2Rl2q5u:b-2mhphq) ([raw file](https://github.com/cockroachdb/cockroach/blob/936e62785d0f6a342d2256f749c7d0db477a67d9/pkg/storage/store_pool.go#L250)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

In the allocator, `RebalanceTarget`, `AllocatorTarget` and `RemoveTarget` all use both.  But I don't think it's a concern if there is a minor race here. It wouldn't be harmful if there's a slight difference in the locality values.

Do not require both, ever, that could cause deadlocks.
</blockquote></details>

Only if we weren't disciplined about lock ordering, but we digress.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-:-KcTtSWAy-h4rKrTHRl9:bq8vvg8)*

**Comment by petermattis** [comment]
Still :lgtm:.

---

Review status: 6 of 12 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/storage/replica_stats_test.go, line 26 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcY0gSbSDiTaiAEceE1:-KcY0gSbSDiTaiAEceE2:b-k148ea) ([raw file](https://github.com/cockroachdb/cockroach/blob/427d1435e992cfab1a1001cbca17fb0ece6c7c09/pkg/storage/replica_stats_test.go#L26)):*
> ```Go
> )
> 
> func makeLocality(localitySpec string) roachpb.Locality {
> ```

I usually make helpers like this a closure inside the test until I find the need to reuse them for multiple tests.

```
  makeLocality := func(localitySpec string) roachpb.Locality { ... }
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-:-KcY1IfHCQ41MjKv701c:b-dbkjmj)*

**Comment by BramGruneir** [comment]
Reviewed 6 of 6 files at r9, 4 of 4 files at r10.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/storage/replica_stats.go, line 64 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcJIgm7JuCXfUsz79xy:-KcZy3ue5s7TypHDpKYj:bprkpdn) ([raw file](https://github.com/cockroachdb/cockroach/blob/3913b1a521d236187e16343e258e8f927af4a188/pkg/storage/replica_stats.go#L64)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

So I did a little more thinking and came up with an approach to minimize memory usage without actually having to drop any information. How does this look?
</blockquote></details>

I love the idea of not storing each request and instead just storing counts.  And the optimization of using the full locality string makes sense.  But it does mean that if you have requests coming from 

a=1,b=1   and
a=1,b=2 

and lets say you have replicas at 

1) a=1,b=3
2) a=2,b=1
3) a=3,b=1

Then clearly moving the lease to 1 makes the most sense, but I don't see how you get that information out of this easily.

How about storing counts based on nodeID instead of locality strings?  Then when you're looking to figure out which replica is the closest based on localities, it's a fairly simple weighted calculation and you can just fetch all the localities you need at one time?   This would save a lot more memory and avoid having to deal with storing strings and structs side by side.

Take the top 10 nodes that requested the data, get their localities, compare each replica's localities to those and find the one that has the lowest diversity score (weighted by the number of requests and dealing with decay).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/storage/replica_stats.go, line 64 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcJIgm7JuCXfUsz79xy:-Kc_grLoD7paALPe-e36:b-qc44te) ([raw file](https://github.com/cockroachdb/cockroach/blob/3913b1a521d236187e16343e258e8f927af4a188/pkg/storage/replica_stats.go#L64)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

I love the idea of not storing each request and instead just storing counts.  And the optimization of using the full locality string makes sense.  But it does mean that if you have requests coming from 

a=1,b=1   and
a=1,b=2 

and lets say you have replicas at 

1) a=1,b=3
2) a=2,b=1
3) a=3,b=1

Then clearly moving the lease to 1 makes the most sense, but I don't see how you get that information out of this easily.

How about storing counts based on nodeID instead of locality strings?  Then when you're looking to figure out which replica is the closest based on localities, it's a fairly simple weighted calculation and you can just fetch all the localities you need at one time?   This would save a lot more memory and avoid having to deal with storing strings and structs side by side.

Take the top 10 nodes that requested the data, get their localities, compare each replica's localities to those and find the one that has the lowest diversity score (weighted by the number of requests and dealing with decay).
</blockquote></details>

I'd be willing to bet good money that whatever approach is taken in this PR when it commits will change when we starting experimenting with the heuristics. I suggest we go with what @a-robinson has currently implemented but keep this and other alternatives in mind as experimentation progresses.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426)*

**Comment by a-robinson** [comment]
Review status: 1 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/storage/replica_stats.go, line 64 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcJIgm7JuCXfUsz79xy:-KccdC20xFjkAqwGlQqF:bx0sdyl) ([raw file](https://github.com/cockroachdb/cockroach/blob/3913b1a521d236187e16343e258e8f927af4a188/pkg/storage/replica_stats.go#L64)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'd be willing to bet good money that whatever approach is taken in this PR when it commits will change when we starting experimenting with the heuristics. I suggest we go with what @a-robinson has currently implemented but keep this and other alternatives in mind as experimentation progresses.
</blockquote></details>

It is possible we'll need to switch to just node IDs. If so, changing will be very easy.

---

*[pkg/storage/replica_stats_test.go, line 26 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcY0gSbSDiTaiAEceE1:-KccdAze3E5v9G2bY4o9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/427d1435e992cfab1a1001cbca17fb0ece6c7c09/pkg/storage/replica_stats_test.go#L26)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I usually make helpers like this a closure inside the test until I find the need to reuse them for multiple tests.

```
  makeLocality := func(localitySpec string) roachpb.Locality { ... }
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426)*

**Comment by BramGruneir** [comment]
*[pkg/storage/replica_stats.go, line 64 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426#-KcJIgm7JuCXfUsz79xy:-KcdDCNmZG73HMgq4J_O:bb73djm) ([raw file](https://github.com/cockroachdb/cockroach/blob/3913b1a521d236187e16343e258e8f927af4a188/pkg/storage/replica_stats.go#L64)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

It is possible we'll need to switch to just node IDs. If so, changing will be very easy.
</blockquote></details>

SGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13426)*

**Pull request merged**
