### PR TITLE
log: reimplement log tags

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change rewrites the implementation of log tags. The motivation is
two-fold:

 - copying log tag chains is responsible for 2.5% of object
   allocations during a KV workload. This change removes these
   allocations (unfortunately, I did not see an improvement in the
   throughput).

 - we need the log tags to be exported and outside `log` so they can
   be used by `tracing` (we want log tags to show up as tags in spans).

Instead of linked chains which often need to be copied, we store all
tags in immutable buffers. We no longer use `opentracing/log.Field`
which is wasteful and cannot be tested for value equality; instead we
store all values as `interface{}`. This simplifies the interface. On
the flip side, it can lead to some new allocations, however most tags
are generated once, put in an `AmbientContext`, and then reused many
times.

For efficiency reasons, the implementation takes some leeway with
respect to how to deduplicate tags (it can choose to remove the older
tag, or overwrite it with the new value). This is a minor cosmetic
change.

Release note: None.

### CODE REVIEW

**Review by nvb — CHANGES_REQUESTED** [review]
> Reviewed 37 of 37 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29828)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/util/log/structured.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29828#-LM35N-hBOqvwcKtHjiU:-LM35N-hBOqvwcKtHjiV:b70sk4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e6107d73a2af6ead6d3fbf4dc36843b9d2fe60/pkg/util/log/structured.go#L29)):*
> ```Go
> // formatTags appends the tags to a bytes.Buffer. If there are no tags,
> // returns false.
> func formatTags(ctx context.Context, buf *bytes.Buffer) bool {
> ```

If we're always using this to create strings, consider using a `*strings.Builder` instead.
___
*[pkg/util/log/logtags/buffer.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29828#-LM37Nb9CtwtJVylgCKG:-LM37Nb9CtwtJVylgCKH:b-gas1vi) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e6107d73a2af6ead6d3fbf4dc36843b9d2fe60/pkg/util/log/logtags/buffer.go#L78)):*
> ```Go
> 	// Check for a common case where the "left" tags are a subsequence of the
> 	// "right" tags.
> 	if len(other.tags) >= len(b.tags) {
> ```

You can change this to the following, which will break earlier in certain cases

```
if diff := len(other.tags)-len(b.tags); diff >= 0
    ...
    for i < len(b.tags) && j-i <= diff {
```
___
*[pkg/util/log/logtags/buffer.go, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29828#-LM393f0Cy1mx-a6qZTp:-LM393f0Cy1mx-a6qZTq:b8w4ema) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e6107d73a2af6ead6d3fbf4dc36843b9d2fe60/pkg/util/log/logtags/buffer.go#L110)):*
> ```Go
> 	for ; i < len(other.tags); i++ {
> 		res.addInPlace(other.tags[i].key, other.tags[i].value)
> 	}
> ```

might be worth asserting that `len(res.tags) == len(b.tags)+len(other.tags)-i`
___
*[pkg/util/log/logtags/buffer.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29828#-LM36Mlp-qkLEs78Pbl9:-LM36Mlp-qkLEs78PblA:boa4074) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e6107d73a2af6ead6d3fbf4dc36843b9d2fe60/pkg/util/log/logtags/buffer.go#L129)):*
> ```Go
> 
> func (b *Buffer) init(length, capacity int) {
> 	if length < staticSlots {
> ```

What about if `capacity > staticSlots`? Shouldn't we skip the `prealloc`?
___
*[pkg/util/log/logtags/context.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29828#-LM3EAd1BCbt6WLJQI8V:-LM3EAd1BCbt6WLJQI8W:b-e7cnm5) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e6107d73a2af6ead6d3fbf4dc36843b9d2fe60/pkg/util/log/logtags/context.go#L46)):*
> ```Go
> 	b := FromContext(ctx)
> 	b = b.Add(key, value)
> 	return context.WithValue(ctx, contextLogTagsKey{}, b)
> ```

`return WithTags(ctx, b)`?

And below.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29828)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/util/log/structured.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29828#-LM35N-hBOqvwcKtHjiU:-LM3Fs-p1sTsGNrNEFlj:bkovmaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e6107d73a2af6ead6d3fbf4dc36843b9d2fe60/pkg/util/log/structured.go#L29)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

If we're always using this to create strings, consider using a `*strings.Builder` instead.
</blockquote></details>

Is it just form, or is strings.Builder more efficient?
___
*[pkg/util/log/logtags/buffer.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29828#-LM37Nb9CtwtJVylgCKG:-LM3G8Ch7v27UIBykoVm:bmi8ppe) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e6107d73a2af6ead6d3fbf4dc36843b9d2fe60/pkg/util/log/logtags/buffer.go#L78)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

You can change this to the following, which will break earlier in certain cases

```
if diff := len(other.tags)-len(b.tags); diff >= 0
    ...
    for i < len(b.tags) && j-i <= diff {
```
</blockquote></details>

:100: 
___
*[pkg/util/log/logtags/buffer.go, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29828#-LM393f0Cy1mx-a6qZTp:-LM3GLyV0Nt6ih0kzp1g:bw29lsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e6107d73a2af6ead6d3fbf4dc36843b9d2fe60/pkg/util/log/logtags/buffer.go#L110)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

might be worth asserting that `len(res.tags) == len(b.tags)+len(other.tags)-i`
</blockquote></details>

It's not necessarily true, some of the other.tags can still be deduplicated by `addInPlace`
___
*[pkg/util/log/logtags/buffer.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29828#-LM36Mlp-qkLEs78Pbl9:-LM3GUMi5l5N2cGJFY5r:b-cgy5r5) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e6107d73a2af6ead6d3fbf4dc36843b9d2fe60/pkg/util/log/logtags/buffer.go#L129)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What about if `capacity > staticSlots`? Shouldn't we skip the `prealloc`?
</blockquote></details>

Length is the required capacity; capacity is a hint, an estimate on the maximum length. If we skip the prealloc, we will allocate in cases where it turns out we only need `length`, like tags getting deduplicated (which is actually a common case).
I will maybe rename to `maxLengthHint` and add a comment.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29828)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/util/log/structured.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29828#-LM35N-hBOqvwcKtHjiU:-LM3I3Id9NSgiP5HVfVh:bkk7mx6) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e6107d73a2af6ead6d3fbf4dc36843b9d2fe60/pkg/util/log/structured.go#L29)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Is it just form, or is strings.Builder more efficient?
</blockquote></details>

Looks like it avoids an allocation in `String()`? By the way, it seems insane that it doesn't disallow you from calling `Write` after you called `String` and got a supposedly immutable `string`

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29828)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/util/log/structured.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29828#-LM35N-hBOqvwcKtHjiU:-LM3Im8mDXrsWekzEyAK:bt5hnmh) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e6107d73a2af6ead6d3fbf4dc36843b9d2fe60/pkg/util/log/structured.go#L29)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Looks like it avoids an allocation in `String()`? By the way, it seems insane that it doesn't disallow you from calling `Write` after you called `String` and got a supposedly immutable `string`
</blockquote></details>

Ah, never mind, the length is copied inside the `string` and we only append to the internal buffer.

**Review by nvb — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29828)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/util/log/structured.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29828#-LM35N-hBOqvwcKtHjiU:-LM3JR_g47Q9JqjnN-oS:b-hpuhg2) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e6107d73a2af6ead6d3fbf4dc36843b9d2fe60/pkg/util/log/structured.go#L29)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Ah, never mind, the length is copied inside the `string` and we only append to the internal buffer.
</blockquote></details>

Yeah, exactly.
___
*[pkg/util/log/logtags/buffer.go, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29828#-LM393f0Cy1mx-a6qZTp:-LM3JXZQ6LjzhIdqa9rs:b-njmdwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e6107d73a2af6ead6d3fbf4dc36843b9d2fe60/pkg/util/log/logtags/buffer.go#L110)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It's not necessarily true, some of the other.tags can still be deduplicated by `addInPlace`
</blockquote></details>

Ah ok, never mind.
___
*[pkg/util/log/logtags/buffer.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29828#-LM36Mlp-qkLEs78Pbl9:-LM3J_qL3cQ2nDYKA2fX:b864mot) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e6107d73a2af6ead6d3fbf4dc36843b9d2fe60/pkg/util/log/logtags/buffer.go#L129)):*
> I will maybe rename to maxLengthHint and add a comment.

SGTM

**Review by nvb — APPROVED** [review]
:lgtm: with the proposed changes, but someone who was part of the original implementation (@andreimatei?) should also take a look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29828#-:-LM3JhtA8Q93JWWn3bEU:b-r1vz1p)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by andreimatei — CHANGES_REQUESTED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29828#-:-LM3vj-I6Y32Ry9JDEqT:bb6ywmx)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/util/log/logtags/buffer.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29828#-LM3tkdw6o4muvUYzgH3:-LM3tkdw6o4muvUYzgH4:bblv8gb) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e6107d73a2af6ead6d3fbf4dc36843b9d2fe60/pkg/util/log/logtags/buffer.go#L76)):*
> ```Go
> 	}
> 
> 	// Check for a common case where the "left" tags are a subsequence of the
> ```

I think left/right is confusing; I'd say b/other.
___
*[pkg/util/log/logtags/buffer.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29828#-LM3uJaR3Z746lxUkNBl:-LM3uJaR3Z746lxUkNBm:b8bdeyc) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e6107d73a2af6ead6d3fbf4dc36843b9d2fe60/pkg/util/log/logtags/buffer.go#L76)):*
> ```Go
> 	}
> 
> 	// Check for a common case where the "left" tags are a subsequence of the
> ```

can you give some intuition about why this is a common case?
___
*[pkg/util/log/logtags/buffer.go, line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29828#-LM3t0BU2qx30cFsxftz:-LM3t0BU2qx30cFsxfu-:bxgibai) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e6107d73a2af6ead6d3fbf4dc36843b9d2fe60/pkg/util/log/logtags/buffer.go#L136)):*
> ```Go
> }
> 
> func (b *Buffer) addInPlace(key string, value interface{}) {
> ```

addOrReplace?

**Review by RaduBerinde — COMMENTED** [review]
TFTRs! Updated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29828#-:-LM4ANAp5SrHycGuJYsH:b-u8hs9c)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/util/log/structured.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29828#-LM35N-hBOqvwcKtHjiU:-LM47PKPDqs2ubZPrtGC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e6107d73a2af6ead6d3fbf4dc36843b9d2fe60/pkg/util/log/structured.go#L29)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah, exactly.
</blockquote></details>

Done.
___
*[pkg/util/log/logtags/buffer.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29828#-LM3tkdw6o4muvUYzgH3:-LM47kDH7BXZo7mpzI6p:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e6107d73a2af6ead6d3fbf4dc36843b9d2fe60/pkg/util/log/logtags/buffer.go#L76)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think left/right is confusing; I'd say b/other.
</blockquote></details>

Done.
___
*[pkg/util/log/logtags/buffer.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29828#-LM3uJaR3Z746lxUkNBl:-LM47kX014a_xk_8kw3D:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e6107d73a2af6ead6d3fbf4dc36843b9d2fe60/pkg/util/log/logtags/buffer.go#L76)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

can you give some intuition about why this is a common case?
</blockquote></details>

Done.
___
*[pkg/util/log/logtags/buffer.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29828#-LM37Nb9CtwtJVylgCKG:-LM49BPqAnh7cLmMVVG3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e6107d73a2af6ead6d3fbf4dc36843b9d2fe60/pkg/util/log/logtags/buffer.go#L78)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

:100: 
</blockquote></details>

Done.
___
*[pkg/util/log/logtags/buffer.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29828#-LM36Mlp-qkLEs78Pbl9:-LM49eOl3Q4WzwdKziYD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e6107d73a2af6ead6d3fbf4dc36843b9d2fe60/pkg/util/log/logtags/buffer.go#L129)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> I will maybe rename to maxLengthHint and add a comment.

SGTM
</blockquote></details>

Done.
___
*[pkg/util/log/logtags/buffer.go, line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29828#-LM3t0BU2qx30cFsxftz:-LM49f9J-cKhm55rG5ny:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e6107d73a2af6ead6d3fbf4dc36843b9d2fe60/pkg/util/log/logtags/buffer.go#L136)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

addOrReplace?
</blockquote></details>

Done.
___
*[pkg/util/log/logtags/context.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29828#-LM3EAd1BCbt6WLJQI8V:-LM47bbt9B3cCVGe1xss:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e6107d73a2af6ead6d3fbf4dc36843b9d2fe60/pkg/util/log/logtags/context.go#L46)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`return WithTags(ctx, b)`?

And below.
</blockquote></details>

Done.

**Review by jordanlewis — APPROVED** [review]
Thanks for taking the time to do this! :lgtm:

> Reviewed 32 of 37 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29828#-:-LM4ZsAX0Lbg63gWWvIn:bb3oz3e)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/util/log/logtags/buffer.go, line 121 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29828#-LM4ZbZtAPkTgSWyoqBN:-LM4ZbZuABhWqRUVKTQd:bicibdy) ([raw file](https://github.com/cockroachdb/cockroach/blob/26f18270400d2a5b049ba4994f791040ed90fc75/pkg/util/log/logtags/buffer.go#L121)):*
> ```Go
> // note that this is not exactly the same with the representation that
> // ultimately appears in logs (which is "prettier").
> func (b *Buffer) String() string {
> ```

nit:  you might want to call this DebugString or something (or maybe even `debugString`?) instead of String if you want to make sure this doesn't get called by any real code.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29828)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/util/log/logtags/buffer.go, line 121 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29828#-LM4ZbZtAPkTgSWyoqBN:-LM4yogZ9Wo1bOthVxRO:bmlomb3) ([raw file](https://github.com/cockroachdb/cockroach/blob/26f18270400d2a5b049ba4994f791040ed90fc75/pkg/util/log/logtags/buffer.go#L121)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit:  you might want to call this DebugString or something (or maybe even `debugString`?) instead of String if you want to make sure this doesn't get called by any real code.
</blockquote></details>

The main reason I added it is to be able to print with `%s/%v`.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29828)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/util/log/logtags/buffer.go, line 121 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29828#-LM4ZbZtAPkTgSWyoqBN:-LM5-8Sb1ds8mf-BQMTR:b-ejh8hm) ([raw file](https://github.com/cockroachdb/cockroach/blob/26f18270400d2a5b049ba4994f791040ed90fc75/pkg/util/log/logtags/buffer.go#L121)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The main reason I added it is to be able to print with `%s/%v`.
</blockquote></details>

Is this a use case for https://golang.org/pkg/fmt/#GoStringer? You have to remember to format with `%#v`.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29828)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/util/log/logtags/buffer.go, line 121 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29828#-LM4ZbZtAPkTgSWyoqBN:-LM50O0r7ZsQ9-XFKIz-:b-bm2ba5) ([raw file](https://github.com/cockroachdb/cockroach/blob/26f18270400d2a5b049ba4994f791040ed90fc75/pkg/util/log/logtags/buffer.go#L121)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is this a use case for https://golang.org/pkg/fmt/#GoStringer? You have to remember to format with `%#v`.
</blockquote></details>

Meh.. I really don't see the problem with having `String()` here.

**Pull request merged**
