### PR TITLE
sql: implement DISCARD statement

### PR DESCRIPTION
**Pull request by couchand**
This implements the DISCARD ALL statement (#16587), and parses the other DISCARD flavors but leaves them unimplemented.  It is composed of three commits:

- cdd61fc, a refactor to use `implicitTxn` on `session.TxnState` rather than passing it separately,
- f396dd4, a refactor to change the session var methods to only take the session, not a whole query planner, and
- 2ea7c98, the actual implementation.

### CODE REVIEW

**Comment by arjunravinarayan** [comment]
First commit LGTM.
Second commit looks good, but will wait for the correct PG error fix, and then rope in another reviewer before merging.

---

Reviewed 2 of 2 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/executor.go, line 1398 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16746#-KnfPUkHqBRfoEV6M3nM:-KnfPUkHqBRfoEV6M3nN:b-4anpub) ([raw file](https://github.com/cockroachdb/cockroach/blob/43b8df8626a324499691289de87e1e6f73206690/pkg/sql/executor.go#L1398)):*
> ```Go
> 		case parser.DiscardModeAll:
> 			if !implicitTxn {
> 				// TODO(couchand): Use the actual PostgreSQL error code
> ```

Just leaving this note here that this should be updated before merging, but I'm sure you're on top of it.

---

*[pkg/sql/vars.go, line 42 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16746#-KnfIh9ut7Cq2nYLhcd7:-KnfIh9ut7Cq2nYLhcd8:b8huoc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/54825f3d05f15b36077d6237044a0e5384e25123/pkg/sql/vars.go#L42)):*
> ```Go
> 	// Set performs mutations (usually on p.session) to effect the change
> 	// desired by SET commands.
> 	// TODO(couchand): only pass the session instead of the whole planner
> ```

Is there a wrinkle in doing this TODO in this PR? I understand `Get` is an endless rabbithole, but my understanding was that `Set` could be changed easily. Correct me if I'm wrong.

---

*[pkg/sql/parser/discard.go, line 1 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16746#-KnfPstBPWNh4djr2t17:-KnfPstBPWNh4djr2t18:b-k09zl5) ([raw file](https://github.com/cockroachdb/cockroach/blob/43b8df8626a324499691289de87e1e6f73206690/pkg/sql/parser/discard.go#L1)):*
> ```Go
> // Copyright 2015 The Cockroach Authors.
> ```

Update to 2017.

---

*[pkg/sql/parser/discard.go, line 14 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16746#-KnfPqhG_g40wIIDUoc-:-KnfPqhH7Ht804RiQ1FO:b-7bbyed) ([raw file](https://github.com/cockroachdb/cockroach/blob/43b8df8626a324499691289de87e1e6f73206690/pkg/sql/parser/discard.go#L14)):*
> ```Go
> // implied. See the License for the specific language governing
> // permissions and limitations under the License.
> ```

Add an author tag with your name here!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16746#-:-KnfO-2phWyEbtErW6nY:b-5ot8m3)*

**Comment by jordanlewis** [comment]
Nice! LGTM mod comments

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/sql/executor.go, line 1404 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16746#-KnfdoY-uPo3mD4ZkwPe:-KnfdoY-uPo3mD4ZkwPf:b-uflygj) ([raw file](https://github.com/cockroachdb/cockroach/blob/43b8df8626a324499691289de87e1e6f73206690/pkg/sql/executor.go#L1404)):*
> ```Go
> 
> 			// RESET ALL
> 			for _, v := range varGen {
> ```

Is there any DRY we could perform here? I assume there's a similar loop in the implementation of `RESET`?

---

*[pkg/sql/vars.go, line 42 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16746#-KnfIh9ut7Cq2nYLhcd7:-KnfXQIinQd3qvio8rvo:bwruxji) ([raw file](https://github.com/cockroachdb/cockroach/blob/54825f3d05f15b36077d6237044a0e5384e25123/pkg/sql/vars.go#L42)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Is there a wrinkle in doing this TODO in this PR? I understand `Get` is an endless rabbithole, but my understanding was that `Set` could be changed easily. Correct me if I'm wrong.
</blockquote></details>

+1 on that - I don't think that `Get` will be easily changed. I'd be okay with leaving out both of these TODOs, actually, since it's not entirely clear we *need* to get to them and will serve as some FUD for future code readers :)

---

*[pkg/sql/logictest/testdata/logic_test/discard, line 2 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16746#-KnfdffY0cpfmDzG9Qh0:-KnfdffY0cpfmDzG9Qh1:b-y7jjxl) ([raw file](https://github.com/cockroachdb/cockroach/blob/43b8df8626a324499691289de87e1e6f73206690/pkg/sql/logictest/testdata/logic_test/discard#L2)):*
> ```
> statement ok
> SET SEARCH_PATH = foo
> ```

add a test in here to ensure that you can't run DISCARD ALL when you're inside a transaction, when you're finished with that code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16746#-:-KnfdyXxsc6TI42i8zCs:b-uskv5v)*

**Comment by couchand** [comment]
The latest changes have added another refactor to unify all references to `implicitTxn` to use the flag that already existed on `session.TxnState` rather than passing it alongside the session.  This made the changes to the `Get` variable interface cleaner.

---

Review status: 0 of 12 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/sql/executor.go, line 1398 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16746#-KnfPUkHqBRfoEV6M3nM:-Knjv-Z51tLpffmMoImG:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/43b8df8626a324499691289de87e1e6f73206690/pkg/sql/executor.go#L1398)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Just leaving this note here that this should be updated before merging, but I'm sure you're on top of it.
</blockquote></details>

Fixed.

---

*[pkg/sql/executor.go, line 1404 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16746#-KnfdoY-uPo3mD4ZkwPe:-KnjuqAMnASaX2Zpjquf:bta3963) ([raw file](https://github.com/cockroachdb/cockroach/blob/43b8df8626a324499691289de87e1e6f73206690/pkg/sql/executor.go#L1404)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Is there any DRY we could perform here? I assume there's a similar loop in the implementation of `RESET`?
</blockquote></details>

As far as I can tell there's not currently an implementation of `RESET ALL`.  If there were, that would certainly make an opportunity for DRYing this up.

---

*[pkg/sql/vars.go, line 42 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16746#-KnfIh9ut7Cq2nYLhcd7:-KnfVnAzaCSGkfe068YA:b-q0cpw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/54825f3d05f15b36077d6237044a0e5384e25123/pkg/sql/vars.go#L42)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

+1 on that - I don't think that `Get` will be easily changed. I'd be okay with leaving out both of these TODOs, actually, since it's not entirely clear we *need* to get to them and will serve as some FUD for future code readers :)
</blockquote></details>

I've gone ahead and changed both of them with the latest revisions, since it wasn't too much work.  If anybody thinks that the changes to `Get` are too optimistic, we can roll that back, but it sure does seem nice to keep the interfaces consistent.

---

*[pkg/sql/logictest/testdata/logic_test/discard, line 2 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16746#-KnfdffY0cpfmDzG9Qh0:-Knk32pTyGL8Djue8Gg7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/43b8df8626a324499691289de87e1e6f73206690/pkg/sql/logictest/testdata/logic_test/discard#L2)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

add a test in here to ensure that you can't run DISCARD ALL when you're inside a transaction, when you're finished with that code.
</blockquote></details>

Done.

---

*[pkg/sql/parser/discard.go, line 1 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16746#-KnfPstBPWNh4djr2t17:-Knk2mHSyyIBK1efQjYN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/43b8df8626a324499691289de87e1e6f73206690/pkg/sql/parser/discard.go#L1)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Update to 2017.
</blockquote></details>

Done.

---

*[pkg/sql/parser/discard.go, line 14 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16746#-KnfPqhG_g40wIIDUoc-:-Knk2n9UrKXRg6PVS54v:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/43b8df8626a324499691289de87e1e6f73206690/pkg/sql/parser/discard.go#L14)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Add an author tag with your name here!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16746#-:-Knk3DnfEvO_ERTsfenV:b4nkn32)*

**Comment by jordanlewis** [comment]
Reviewed 10 of 10 files at r3.
Review status: 0 of 12 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/executor.go, line 1006 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16746#-KnkYCVzrtDorY3mALRK:-KnkYCVzrtDorY3mALRL:b-w3yqzv) ([raw file](https://github.com/cockroachdb/cockroach/blob/43b8df8626a324499691289de87e1e6f73206690/pkg/sql/executor.go#L1006)):*
> ```Go
> 	stmts StatementList,
> 	pinfo *parser.PlaceholderInfo,
> 	implicitTxn bool,
> ```

Hmmm... I'm not sure if this is correct! It's encouraging that we still pass the tests with this, and in an ideal world that'd indicate that we're all good to go, but I think this is a pretty deep modification to something that's not too related to what we're trying to do here.

I'd prefer that you back this out and make an issue to unify the `Get` interface in a future PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16746)*

**Comment by jordanlewis** [comment]
:lgtm: besides the `implicitTxn` stuff!

---

Review status: 0 of 12 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16746#-:-Knk_mQ1WA5ivjuNQqTz:b-nj5nbd)*

**Comment by arjunravinarayan** [comment]
Reviewed 3 of 4 files at r4.
Review status: 3 of 12 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/executor.go, line 1006 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16746#-KnkYCVzrtDorY3mALRK:-Knkb6x87tpXBbEyhHWW:b-w6sxc2) ([raw file](https://github.com/cockroachdb/cockroach/blob/43b8df8626a324499691289de87e1e6f73206690/pkg/sql/executor.go#L1006)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Hmmm... I'm not sure if this is correct! It's encouraging that we still pass the tests with this, and in an ideal world that'd indicate that we're all good to go, but I think this is a pretty deep modification to something that's not too related to what we're trying to do here.

I'd prefer that you back this out and make an issue to unify the `Get` interface in a future PR.
</blockquote></details>

I agree with Jordan. Let's keep this PR self-contained.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16746)*

**Comment by jordanlewis** [comment]
Review status: 3 of 12 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/vars.go, line 123 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/16746#-KnkgBj8pFkNUjOLBFhE:-KnkgBj9JyHWAhO8rfuu:b5uz407) ([raw file](https://github.com/cockroachdb/cockroach/blob/f396dd467a8b2401a65feecedb09e2eb4d4088e7/pkg/sql/vars.go#L123)):*
> ```Go
> 			if len(dbName) != 0 {
> 				// Verify database descriptor exists.
> 				// TODO(couchand): determine if we need to lock here (is this the session's main goroutine?)
> ```

This is the session's main goroutine. I think it should be okay to do this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16746)*

**Comment by couchand** [comment]
Review status: 1 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/executor.go, line 1006 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16746#-KnkYCVzrtDorY3mALRK:-KnkfpuBEX88RE8Q-_JO:b-agidd8) ([raw file](https://github.com/cockroachdb/cockroach/blob/43b8df8626a324499691289de87e1e6f73206690/pkg/sql/executor.go#L1006)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

I agree with Jordan. Let's keep this PR self-contained.
</blockquote></details>

Ok sounds good.  I've pulled out the `Get` case, will push that up as a different PR.

---

*[pkg/sql/vars.go, line 123 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/16746#-KnkgBj8pFkNUjOLBFhE:-Knkk3YFnP2MPwEUGY5I:b-et4hpd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f396dd467a8b2401a65feecedb09e2eb4d4088e7/pkg/sql/vars.go#L123)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This is the session's main goroutine. I think it should be okay to do this.
</blockquote></details>

Great, thanks for taking a look, comment has been removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16746)*

**Pull request merged**
