### PR TITLE
sql: make SupportsVectorized check light-weight

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: pool allocations of some objects in the read path**

This commit pools the allocations of some objects that are created on
the simplest read path in the vectorized engine - when we have
a ColBatchScan connected with a Materializer.

Release note: None

**colbuilder: fix casting behavior for actual types mismatch**

We have recently merged a change that enforces that the colbuilder
produces an operator chain that outputs batches with the desired type
schema. This is enforced by planning casts when there is a mismatch.
Previously, we would only try planning a vectorized cast because the
assumption was that only integers of different widths will need to be
cast in some cases, but as it turns out types of string family also
might need to be cast (e.g. `string` and `"char"` aren't identical).
This is now fixed by falling back to row-execution casting when
a vectorized cast isn't supported.

Release note: None

**sql: make SupportsVectorized check light-weight**

Previously, in order to determine whether we supported the vectorization
of a flow, we would run a pretty expensive SupportsVectorized check that
performs a "fake flow setup" by actually creating all of the components
without running them. This has non-negligible performance impact on
KV-like workloads, so it has been optimized away in favor of a more
light-weight check that simply inspects the processor specs for the fact
whether the processor core can be vectorized (either natively or by
wrapping row-execution processor). All processor cores have been
audited to separate out all that we currently cannot wrap (usually
because they don't implement RowSource interface). Note that if a new
processor core is introduced and `canWrap` check is not updated, we
defensively assume that it cannot be wrapped and emit an assertion
failed error that - hopefully - should surface the fact that we need to
update the check.

Addresses: #53893.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Benchmarks of the first commit:
```
name                                           old time/op    new time/op    delta
FlowSetup/vectorize=true/distribute=true-24      21.8µs ± 7%    21.9µs ± 7%    ~     (p=0.739 n=10+10)
FlowSetup/vectorize=true/distribute=false-24     19.4µs ± 3%    19.4µs ± 5%    ~     (p=0.739 n=10+10)

name                                           old alloc/op   new alloc/op   delta
FlowSetup/vectorize=true/distribute=true-24      56.0kB ± 0%    52.0kB ± 0%  -7.15%  (p=0.000 n=9+9)
FlowSetup/vectorize=true/distribute=false-24     52.5kB ± 0%    48.5kB ± 0%  -7.61%  (p=0.000 n=8+8)

name                                           old allocs/op  new allocs/op  delta
FlowSetup/vectorize=true/distribute=true-24         448 ± 0%       441 ± 0%  -1.56%  (p=0.000 n=9+10)
FlowSetup/vectorize=true/distribute=false-24        417 ± 0%       410 ± 0%  -1.68%  (p=0.000 n=10+10)
```
Benchmarks of the second commit:
```
name                                          old time/op    new time/op    delta
FlowSetup/vectorize=true/distribute=true-24     22.1µs ± 8%    18.8µs ± 4%  -14.83%  (p=0.000 n=10+10)
FlowSetup/vectorize=true/distribute=false-24    19.4µs ± 5%    16.6µs ± 3%  -14.21%  (p=0.000 n=10+10)

name                                          old alloc/op   new alloc/op   delta
FlowSetup/vectorize=true/distribute=true-24     52.0kB ± 0%    39.1kB ± 0%  -24.71%  (p=0.000 n=9+9)
FlowSetup/vectorize=true/distribute=false-24    48.5kB ± 0%    35.7kB ± 0%  -26.42%  (p=0.000 n=8+9)

name                                          old allocs/op  new allocs/op  delta
FlowSetup/vectorize=true/distribute=true-24        442 ± 0%       348 ± 0%  -21.27%  (p=0.000 n=9+10)
FlowSetup/vectorize=true/distribute=false-24       411 ± 0%       317 ± 0%  -22.87%  (p=0.000 n=10+10)
```
Benchmarks of the whole PR:
```
name                                           old time/op    new time/op    delta
FlowSetup/vectorize=true/distribute=true-24      21.7µs ± 4%    18.8µs ± 4%  -13.65%  (p=0.000 n=9+10)
FlowSetup/vectorize=true/distribute=false-24     19.6µs ± 3%    16.4µs ± 2%  -16.01%  (p=0.000 n=10+10)
FlowSetup/vectorize=false/distribute=true-24     16.1µs ± 3%    16.1µs ± 4%     ~     (p=0.912 n=10+10)
FlowSetup/vectorize=false/distribute=false-24    14.9µs ± 2%    15.1µs ± 2%     ~     (p=0.052 n=10+10)

name                                           old alloc/op   new alloc/op   delta
FlowSetup/vectorize=true/distribute=true-24      56.0kB ± 0%    39.2kB ± 1%  -30.02%  (p=0.000 n=9+10)
FlowSetup/vectorize=true/distribute=false-24     52.5kB ± 0%    35.7kB ± 0%  -31.99%  (p=0.000 n=8+10)
FlowSetup/vectorize=false/distribute=true-24     33.4kB ± 0%    33.4kB ± 0%     ~     (p=0.870 n=8+9)
FlowSetup/vectorize=false/distribute=false-24    30.0kB ± 0%    30.0kB ± 0%     ~     (p=0.210 n=9+9)

name                                           old allocs/op  new allocs/op  delta
FlowSetup/vectorize=true/distribute=true-24         449 ± 0%       349 ± 0%  -22.27%  (p=0.000 n=9+10)
FlowSetup/vectorize=true/distribute=false-24        418 ± 0%       318 ± 0%  -23.92%  (p=0.000 n=10+9)
FlowSetup/vectorize=false/distribute=true-24        285 ± 0%       285 ± 0%     ~     (all equal)
FlowSetup/vectorize=false/distribute=false-24       255 ± 1%       255 ± 1%     ~     (p=1.000 n=10+10)
```
The flow setup benchmark is a good proxy for KV-like workload, and I'll use it going forward to search for possible optimizations. Note that this PR already fixes most of the performance hit when using the vectorized engine (which was also shown on KV95 numbers), and I'll look into it further.

**Review by asubiotto — CHANGES_REQUESTED** [review]
One thing I was thinking about specifically with the `SupportsVectorized` check is are we doing it with only a single flow? If so, that seems pointless since we don't gain any information and might be good to skip it for performance.

> Reviewed 11 of 11 files at r1, 9 of 9 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56206#-:-MLDPblM6nkgfR_57YZ9:b-8bd6sl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/expr.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56206#-MLDP3-L10ddCP5CT0Z5:-MLDP3-L10ddCP5CT0Z6:b-vg8igj) ([raw file](https://github.com/cockroachdb/cockroach/blob/17602fe0bebd5beda0410111f03c776ef2a3ee7c/pkg/sql/colexec/expr.go#L50)):*
> ```Go
> // NewExprHelper returns a new ExprHelper. forceExprDeserialization determines
> // whether LocalExpr field is ignored by the helper.
> func NewExprHelper(exprDeserialization ExprDeserialization) ExprHelper {
> ```

How come we don't need forced expr deserializations any more?
___
*[pkg/sql/colexec/expr.go, line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56206#-MLDEkS20BaU7VuRfY0w:-MLDEkS20BaU7VuRfY0x:b-co6m8s) ([raw file](https://github.com/cockroachdb/cockroach/blob/17602fe0bebd5beda0410111f03c776ef2a3ee7c/pkg/sql/colexec/expr.go#L128)):*
> ```Go
> 
> func (h *forcedDeserializationExprHelper) Release() {
> 	forcedDeserializationExprHelperPool.Put(h)
> ```

Does it make sense to release the inner expr?
___
*[pkg/sql/colexec/materializer.go, line 310 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56206#-MLDFAzFByoZazs8pk15:-MLDFAzG-X-Ws3UVejiC:bve4dil) ([raw file](https://github.com/cockroachdb/cockroach/blob/17602fe0bebd5beda0410111f03c776ef2a3ee7c/pkg/sql/colexec/materializer.go#L310)):*
> ```Go
> 	m.ProcessorBase.Reset()
> 	*m = Materializer{
> 		ProcessorBase: m.ProcessorBase,
> ```

Comment why you're leaving this field set
___
*[pkg/sql/colexec/colbuilder/execplan.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56206#-MLDFXf_C_ko8RX9TXPc:-MLDFXf_C_ko8RX9TXPd:b-cxoa81) ([raw file](https://github.com/cockroachdb/cockroach/blob/17602fe0bebd5beda0410111f03c776ef2a3ee7c/pkg/sql/colexec/colbuilder/execplan.go#L62)):*
> ```Go
> ) (*colexec.Columnarizer, []execinfra.Releasable, error) {
> 	var toWrapInputs []execinfra.RowSource
> 	var releasable []execinfra.Releasable
> ```

nit: `s/releasable/releasables` here and everywhere
___
*[pkg/sql/colexec/colbuilder/execplan.go, line 269 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56206#-MLDKT-C4BYFTLHFoMmD:-MLDKT-C4BYFTLHFoMmE:b-iowmpp) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d35af8fa98407094e5c0ce2532cd64a8622ea9e/pkg/sql/colexec/colbuilder/execplan.go#L269)):*
> ```Go
> 
> var (
> 	errUnsupportedNativelyCore        = errors.New("unsupported processor core")
> ```

`errCoreUnsupportedNatively` makes more sense to me.
___
*[pkg/sql/colexec/colbuilder/execplan.go, line 660 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56206#-MLDRhnW8Q6dVrvTPPHV:-MLDRhnW8Q6dVrvTPPHW:b-rjzqty) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d35af8fa98407094e5c0ce2532cd64a8622ea9e/pkg/sql/colexec/colbuilder/execplan.go#L660)):*
> ```Go
> 		}
> 		if log.V(1) {
> 			log.Infof(ctx, "planning a wrapped processor because %s", err.Error())
> ```

nit: if you're here already, let's change this to a `log.VInfof`?
___
*[pkg/sql/colexec/colbuilder/execplan.go, line 1218 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56206#-MLDSVeG6cgNoAWQRwnj:-MLDSVeG6cgNoAWQRwnk:b-p7bll) ([raw file](https://github.com/cockroachdb/cockroach/blob/8efceaef07661ede00faeb0d277452748677f89e/pkg/sql/colexec/colbuilder/execplan.go#L1218)):*
> ```Go
> 				post.RenderExprs[castedIdx].Expr = fmt.Sprintf("@%d::%s", i+1, expected.SQLStandardName())
> 				result.Op = input
> 				if err = result.wrapPostProcessSpec(ctx, flowCtx, args, post, resultTypes, factory, err); err != nil {
> ```

It's unfortunate that this is done at this stage. I guess this is something the sql experience team will work on
___
*[pkg/sql/colflow/vectorized_flow.go, line 1273 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56206#-MLDJfAK4Mj4xxy5MUch:-MLDJfAK4Mj4xxy5MUci:b-c1ao1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/17602fe0bebd5beda0410111f03c776ef2a3ee7c/pkg/sql/colflow/vectorized_flow.go#L1273)):*
> ```Go
> // represent is scheduled to be run on a remote node (different from the one
> // performing this check).
> func SupportsVectorized(
> ```

I see a lot of calls to `SupportsVectorized` that don't really care about the return parameters. Should we change the name to something like `GetLeaves` or something similar and then make `SupportsVectorized` a light wrapper that ignores the leaves and immediately cleans up? It'll probably make the callsites cleaner.

edit: not sure this makes sense in light of the second commit.

**Review by yuzefovich — COMMENTED** [review]
> One thing I was thinking about specifically with the `SupportsVectorized` check is are we doing it with only a single flow? If so, that seems pointless since we don't gain any information and might be good to skip it for performance.

I don't think I follow your question and the suggestion. Before this PR, on the gateway node we run `SupportsVectorized` check on each of the flow specs of the physical plan, now we do lighter `IsSupported` check also for each of the flow specs, but in both cases we do the check one at a time.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56206#-:-MLEVZfLANLwMmgQR4D6:b-8kq87i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/expr.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56206#-MLDP3-L10ddCP5CT0Z5:-MLE_gb0ExKgHn3U7xqP:b-9n8pgn) ([raw file](https://github.com/cockroachdb/cockroach/blob/17602fe0bebd5beda0410111f03c776ef2a3ee7c/pkg/sql/colexec/expr.go#L50)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

How come we don't need forced expr deserializations any more?
</blockquote></details>

This was introduced in order to simulate the planning of post processing spec on the remote nodes during `SupportsVectorized` check. The second commit assumes that we can always plan the post-processing spec (either "natively" or by wrapping), so we no longer do the "supports" check for these expressions. If for some reason we cannot deserialize an expression on the remote node, we won't be able to deserialize it in the row-execution engine either, so I think removal of `forcedExprDeserialization` is logical given these two observations.
___
*[pkg/sql/colexec/expr.go, line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56206#-MLDEkS20BaU7VuRfY0w:-MLEWY0UACIGgb0AuGa1:buaoxuj) ([raw file](https://github.com/cockroachdb/cockroach/blob/17602fe0bebd5beda0410111f03c776ef2a3ee7c/pkg/sql/colexec/expr.go#L128)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Does it make sense to release the inner expr?
</blockquote></details>

Hm, I guess why not, done.
___
*[pkg/sql/colexec/materializer.go, line 310 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56206#-MLDFAzFByoZazs8pk15:-MLEXfIz1_56vamu8zuR:b-4x4ep7) ([raw file](https://github.com/cockroachdb/cockroach/blob/17602fe0bebd5beda0410111f03c776ef2a3ee7c/pkg/sql/colexec/materializer.go#L310)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Comment why you're leaving this field set
</blockquote></details>

Done. Your comment actually prompted me to optimize/fix a few things (I think I wasn't reusing `m.ProcessorBase` correctly in the first revision).
___
*[pkg/sql/colexec/colbuilder/execplan.go, line 269 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56206#-MLDKT-C4BYFTLHFoMmD:-MLE_caw6MK34sfyrJ8q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d35af8fa98407094e5c0ce2532cd64a8622ea9e/pkg/sql/colexec/colbuilder/execplan.go#L269)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`errCoreUnsupportedNatively` makes more sense to me.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/colbuilder/execplan.go, line 660 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56206#-MLDRhnW8Q6dVrvTPPHV:-MLEYsdm30GbsGaprdqg:b-9gz2ps) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d35af8fa98407094e5c0ce2532cd64a8622ea9e/pkg/sql/colexec/colbuilder/execplan.go#L660)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: if you're here already, let's change this to a `log.VInfof`?
</blockquote></details>

Do you mean replacing the `if` block with a single line? I recently changed it to the current form in order to avoid computing the info message when the verbosity is not met, does `VInfof` also avoid that? (Looking at the code it looks like yes.)
___
*[pkg/sql/colexec/colbuilder/execplan.go, line 1218 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56206#-MLDSVeG6cgNoAWQRwnj:-MLEZFv80Z1_LRt_VoCW:b-2x9gzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/8efceaef07661ede00faeb0d277452748677f89e/pkg/sql/colexec/colbuilder/execplan.go#L1218)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It's unfortunate that this is done at this stage. I guess this is something the sql experience team will work on
</blockquote></details>

I think it'll be pretty unlikely that we need to plan these casts - it seems to me that the most common cases are integers of different widths (this is a shortcoming of the type system) and strings with differents OIDs (not sure whether something could be improved about these).
___
*[pkg/sql/colflow/vectorized_flow.go, line 1273 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56206#-MLDJfAK4Mj4xxy5MUch:-MLE_4IG-4FEREgf2Xf9:b-6l36rd) ([raw file](https://github.com/cockroachdb/cockroach/blob/17602fe0bebd5beda0410111f03c776ef2a3ee7c/pkg/sql/colflow/vectorized_flow.go#L1273)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I see a lot of calls to `SupportsVectorized` that don't really care about the return parameters. Should we change the name to something like `GetLeaves` or something similar and then make `SupportsVectorized` a light wrapper that ignores the leaves and immediately cleans up? It'll probably make the callsites cleaner.

edit: not sure this makes sense in light of the second commit.
</blockquote></details>

The method has been renamed in the second commit, and I don't think we need to do anything else.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Before this PR, on the gateway node we run SupportsVectorized check on each of the flow specs of the physical plan, now we do lighter IsSupported check also for each of the flow specs, but in both cases we do the check one at a time.

My suggestion is specifically for cases where `len(flows) == 1`. Unless I'm missing something, we do this check for all flows in `setupFlows`. In the case of only one flow, there is no point to doing this check because it will be performed anyway when actually setting up the flow, right? I think this is the most likely case for kv95.

> Reviewed 11 of 11 files at r4, 2 of 2 files at r5, 9 of 9 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56206#-:-MLMtXm90qCgBQvUY2a2:bssgbiv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Review by yuzefovich — COMMENTED** [review]
Yes, we do the check for all flows in `setupFlows`, but that's the only time we do it - i.e. we don't perform it afterwards. The logic is roughly this:
1. in `setupFlows` check every flow whether it is supported
2. depending on whether all flows are supported, we tweak `vectorize` mode value for the sessiondata object of the eval context
3. on every node, when setting up the flows, we only look at `vectorize` mode from the proto.

TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56206#-:-MLOEM6tDS5bcN04rYfi:b-avkxre)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by asubiotto** [comment]
> we don't perform it afterwards

Can you expand on this? For a single flow on the gateway node we call `IsSupported` that calls `supportedNatively` and `canWrap`. If that check is successful we setup the flow, ultimately calling `NewColOperator` that does the same thing (i.e. calls `supportedNatively` and `canWrap` and does certain things depending on it).

We added the `SupportsVectorized` check in order to ensure that these flows can be set up **before** sending the setup RPC to avoid unsupported "hybrid" flows (i.e. the remote flow is rowexec pushing to a colexec flow on this node). In cases where we're only setting up a single flow on the gateway node (which is usually the case in these kv95 benchmarks and single-row workloads in general, my argument is that we can skip it since we do the equivalent when setting up the flow anyway.

**Review by yuzefovich — COMMENTED** [review]
Oh, I see your point about some double calls of `supportedNatively` and `canWrap` methods.

However, we added the `SupportsVectorized` check not only to avoid the hybrid flows but also to remove the fallback logic if the vectorized flow setup fails. Currently if we simply remove `IsSupported` check for a single local flow and it turns out to be unsupported, we will fail the query. We could remove it only if we also add the fall back to setting up a row-based flow if the vectorized one failed. I'll take a look into that.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56206#-:-MLTIcns3avFh5qEjtXn:b-4rvz6h)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Pull request merged**
