### PR TITLE
intentresolver: misc cleanups

### PR DESCRIPTION
**Pull request by andreimatei**
See individual commits.

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
Nice cleanup.

> Reviewed 1 of 1 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, 4 of 4 files at r4, 1 of 1 files at r5, 7 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53105#-:-MF8vKda2jSu2JDr2Sym:b7oy6p4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53105#-MF8qp1844QT2EnVbbAt:-MF8qp19BNZ2u9VtN_Al:b-cuk40f) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcc96bea9d66782c7540dafe26c727a47be7d23/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L128)):*
> ```Go
> 
> 	// ResolveIntent synchronously resolves the provided intent.
> 	ResolveIntent(context.Context, roachpb.LockUpdate, intentresolver.ResolveOptions) *Error
> ```

:thumbsdown: to this second commit. I wouldn't make it unless we need to, and the commit message is not very convincing. The entire `concurrency` package works on `*roachpb.Error` because it's awkward everywhere that we mix them (as you're noticing). I wouldn't make this change unless you're committed to switching the concurrency package and the `txnwait` package over to `error`s as well. Otherwise, we're just shifting ugly code around for no actual benefit.
___
*[pkg/kv/kvserver/intentresolver/intent_resolver.go, line 774 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53105#-MF8t9u8-pNAn4fsSoe5:-MF8t9u8-pNAn4fsSoe6:b59iufn) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3cb25f5b04c1bcc89ecaf57f7e9a2e8e6423b93/pkg/kv/kvserver/intentresolver/intent_resolver.go#L774)):*
> ```Go
> // ResolveOptions is used during intent resolution.
> type ResolveOptions struct {
> 	// If set, the ranges containing the intents are to be poisoned.
> ```

Is there a good explanation of "poisoning a range" anywhere? Is so, could you reference that here? If not, is this a good place for one?
___
*[pkg/kv/kvserver/intentresolver/intent_resolver_test.go, line 925 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/53105#-MF8tok50hSLTbaJyDU7:-MF8tok50hSLTbaJyDU8:b-2t7sce) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebb094d47831dc83b6007ab311bfcbf3339b487c/pkg/kv/kvserver/intentresolver/intent_resolver_test.go#L925)):*
> ```Go
> 
> func respForResolveIntentBatch(
> 	t *testing.T, ba roachpb.BatchRequest, checkTxnStatusOpt checkTxnStatusOpt,
> ```

Would it make more sense to just specify the status that we expect the intents to have? Is that possible?
___
*[pkg/kv/kvserver/intentresolver/intent_resolver_test.go, line 227 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/53105#-MF8uoZDEZsg8l9l8pNy:-MF8uoZDEZsg8l9l8pNz:b-vdww61) ([raw file](https://github.com/cockroachdb/cockroach/blob/e21e32a8167862171f42db77273ac041a74c70ab/pkg/kv/kvserver/intentresolver/intent_resolver_test.go#L227)):*
> ```Go
> 				close(done)
> 			}
> 			txn := c.txn
> ```

Do we want to clone this?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53105)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53105#-MF8qp1844QT2EnVbbAt:-MFBGAYqCFIUd225ivVC:b-pqro8d) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcc96bea9d66782c7540dafe26c727a47be7d23/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L128)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

:thumbsdown: to this second commit. I wouldn't make it unless we need to, and the commit message is not very convincing. The entire `concurrency` package works on `*roachpb.Error` because it's awkward everywhere that we mix them (as you're noticing). I wouldn't make this change unless you're committed to switching the concurrency package and the `txnwait` package over to `error`s as well. Otherwise, we're just shifting ugly code around for no actual benefit.
</blockquote></details>

The reason I've done it is because I'll be adding `ResolveIntent` to the `rangefeed.TxnPusher` iface, to replace `CleanupTxnIntentsAsync`. `CleanupTxnIntentsAsync` already returns error, and I don't want to move the `rangefeed` package backwards.
Does that change your mind?

I wouldn't have gone ahead to do this change if it wasn't for the future plans, but generally, to me, moving from pErr->err when possible is almost always good. Even if a package deals with pErr a lot, it also probably also deals with err a lot anyway. The awkwardness to transforms err->pErr is lower than the other way, at least to me. In this particular case, the commit results in a net -2 calls to `roachpb.NewError()` and -1 `.GoError()`.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53105)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53105#-MF8qp1844QT2EnVbbAt:-MFBJ8d2EFyUM24h5V7j:b-uhkvaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcc96bea9d66782c7540dafe26c727a47be7d23/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L128)):*
> I don't want to move the rangefeed package backwards.

Agreed, this is definitely not something we want to do.

But you're not going to be adding `ResolveIntents` to the interface directly, right? You're going to be calling into the `IntentResolver` from `rangefeedTxnPusher`. So you can perform the `.GoError()` there and not leak anything into the `rangefeed` package.

The way I see it, if you make this change then we now have one more package that's mixing `pErr` and `err`.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53105)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53105#-MF8qp1844QT2EnVbbAt:-MFBNTJADSBy_fht1c3H:b9m0ogo) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcc96bea9d66782c7540dafe26c727a47be7d23/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L128)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> I don't want to move the rangefeed package backwards.

Agreed, this is definitely not something we want to do.

But you're not going to be adding `ResolveIntents` to the interface directly, right? You're going to be calling into the `IntentResolver` from `rangefeedTxnPusher`. So you can perform the `.GoError()` there and not leak anything into the `rangefeed` package.

The way I see it, if you make this change then we now have one more package that's mixing `pErr` and `err`.
</blockquote></details>

removed the commit, under protest
___
*[pkg/kv/kvserver/intentresolver/intent_resolver.go, line 774 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53105#-MF8t9u8-pNAn4fsSoe5:-MFBKB5ABiCzBCPVofTC:b-4mhpgl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3cb25f5b04c1bcc89ecaf57f7e9a2e8e6423b93/pkg/kv/kvserver/intentresolver/intent_resolver.go#L774)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is there a good explanation of "poisoning a range" anywhere? Is so, could you reference that here? If not, is this a good place for one?
</blockquote></details>

added a comment
___
*[pkg/kv/kvserver/intentresolver/intent_resolver_test.go, line 925 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/53105#-MF8tok50hSLTbaJyDU7:-MFBLf466f5x4b5r9uAD:brx5fn2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebb094d47831dc83b6007ab311bfcbf3339b487c/pkg/kv/kvserver/intentresolver/intent_resolver_test.go#L925)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Would it make more sense to just specify the status that we expect the intents to have? Is that possible?
</blockquote></details>

done, see now
___
*[pkg/kv/kvserver/intentresolver/intent_resolver_test.go, line 227 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/53105#-MF8uoZDEZsg8l9l8pNy:-MFBMIa168gePw5EbQQG:b-lrgxyt) ([raw file](https://github.com/cockroachdb/cockroach/blob/e21e32a8167862171f42db77273ac041a74c70ab/pkg/kv/kvserver/intentresolver/intent_resolver_test.go#L227)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we want to clone this?
</blockquote></details>

it wasn't technically generally since we overwrite the LockSpans slice below every time, but yeah I've added a clone.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r8, 2 of 4 files at r9, 7 of 7 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53105#-:-MFBQNRECBFxfgxA6mMy:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvserver/intentresolver/intent_resolver_test.go, line 851 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/53105#-MFBQKYc02ooimEXRDjV:-MFBQKYd0Sa9Z-8by6xK:boadpwr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4172f88fdc4ebe3b6e4a63d5512ceb04e45ebbec/pkg/kv/kvserver/intentresolver/intent_resolver_test.go#L851)):*
> ```Go
> 	checkTxnAborted checkTxnStatusOpt = true
> 
> 	// NOTE: There shouldbe a checkTxnCommitted option, but no test currently uses
> ```

should be

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53105#-:-MFCg76A5gYT18AoSj-Y:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/intentresolver/intent_resolver_test.go, line 851 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/53105#-MFBQKYc02ooimEXRDjV:-MFBSyYr9Jeg0QQAcLam:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4172f88fdc4ebe3b6e4a63d5512ceb04e45ebbec/pkg/kv/kvserver/intentresolver/intent_resolver_test.go#L851)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

should be
</blockquote></details>

done

**Pull request merged**
