### PR TITLE
pkg/server: Add `TenantRanges` to status server, hook into debug.zip

### PR DESCRIPTION
**Pull request by abarganier**
While a system tenant or host cluster has full access to the debug
information provided by the `Ranges` endpoint in the KV status server,
tenants currently have no way to fetch metadata about their own ranges.

We'd like to expose debug information in the form of range metadata to
tenants, so that they can use this information in `debug.zip`, which
is currently in the process of being exposed (albeit a subset of the
full functionality) to tenants.

To provide this, we implement `TenantRanges` and make it accessible
within the tenant status server. The endpoint will reach across the
Tenant/KV boundary via the tenant Connector interface to call the
associated KV status server implementation. From here, we can lean
on the existing `Ranges` endpoint. We can fan out requests to `Ranges`
for all nodes containing replicas of ranges within the tenant's
keyspace. The caller can then transform the metadata into a more
tenant-appropriate format (e.g. avoiding concepts that break the
'tenant boundary', such as node IDs, replication information, etc).

The results from all nodes are then combined, and returned back to the
tenant caller.

This PR does not contain pagination - this functionality will come
in a follow up PR where we offset based on range startKeys.

This PR also modifies the cluster-wide debug zip config to attempt
a `TenantRanges` request, and generate a file from the response.
This file will provide range metadata for all the leaseholder replicas
available in the tenant's keyspace, which can be used by tenants
for debug purposes, such as identifying hot ranges.

Release note (api change): The status api will now have a newly exposed
`_status/tenant_ranges` endpoint available to tenants, although it's not
currently used except for debug.zip (see following commit).

### CODE REVIEW

**Comment by abarganier** [comment]
NB: First 2 commits are being reviewed separately @ https://github.com/cockroachdb/cockroach/pull/76892

Please only mind the final 2 commits.

**Comment by abarganier** [comment]
NB: Still working on wrapping up unit tests for `TenantRanges`, but figured I would upload in the meantime for faster feedback.

**Comment by tbg** [comment]
Drive-by, why only lease holders? Followers serve requests too (follower reads).

**Comment by abarganier** [comment]
> Drive-by, why only lease holders? Followers serve requests too (follower reads).

Do you think it makes most sense to include *all* replicas in the response, but instead of providing information on the node_id/replica_id/etc, we instead just provide the locality information associated with the replica to differentiate? I don't feel too strongly about the leaseholder only decision that I made, so I'm happy to change to something more appropriate.

**Review by rimadeodhar — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, 3 of 3 files at r2, 12 of 12 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76743)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @knz)

___
*[pkg/ccl/kvccl/kvtenantccl/connector.go, line 123 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-Mwgey_M3ncWLYSYqNIu:-Mwgey_M3ncWLYSYqNIv:b-6j7h97) ([raw file](https://github.com/cockroachdb/cockroach/blob/63b13e035a68d94b8f5a5cb029cd83bc6430ab10/pkg/ccl/kvccl/kvtenantccl/connector.go#L123)):*
> ```Go
> var _ serverpb.RegionsServer = (*Connector)(nil)
> 
> // Connector is capable of find the debug information about the current
> ```

Nit: 'finding' debug information :)
___
*[pkg/rpc/auth_tenant.go, line 250 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-MwgfPiu0u5yeLv1vLoZ:-MwgfPiu0u5yeLv1vLo_:b-ta8lz1) ([raw file](https://github.com/cockroachdb/cockroach/blob/63b13e035a68d94b8f5a5cb029cd83bc6430ab10/pkg/rpc/auth_tenant.go#L250)):*
> ```Go
> func (a tenantAuthorizer) authTenantRanges(tenID roachpb.TenantID) error {
> 	if !tenID.IsSet() || tenID == roachpb.SystemTenantID {
> 		return authErrorf("tenant ranges with unspecified or system tenant not permitted.")
> ```

I'm wondering if we should make the error for the system tenant more descriptive? Like if the `tenID` is the system tenant, then return an error clarifying to use the `Ranges` endpoint?

Also, thinking about this more, I'm wondering whether there is any value in not allowing the system tenant to use TenantRanges? I realize that the `Ranges` endpoint makes more sense to call but there is no reason to actively disallow system tenant to call into `TenantRanges` is there?
___
*[pkg/server/status.go, line 1920 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-MwgfmRJ13LxIHSFii58:-MwgfmRJ13LxIHSFii59:b3rr0fe) ([raw file](https://github.com/cockroachdb/cockroach/blob/63b13e035a68d94b8f5a5cb029cd83bc6430ab10/pkg/server/status.go#L1920)):*
> ```Go
> 	ctx context.Context, req *serverpb.RangesRequest,
> ) (*serverpb.RangesResponse, error) {
> ```

Nit: superfluous line?
___
*[pkg/server/status.go, line 2148 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-MwggHaxDSs3ld0Ob1D_:-MwggHaxDSs3ld0Ob1Da:b-1wk6tz) ([raw file](https://github.com/cockroachdb/cockroach/blob/63b13e035a68d94b8f5a5cb029cd83bc6430ab10/pkg/server/status.go#L2148)):*
> ```Go
> 
> 	rangeIDs := make([]roachpb.RangeID, 0)
> 	replicaNodeIDs := make(map[roachpb.NodeID]struct{})
> ```

Please can you add some comments clarifying on what these two fields are used for? This will help make the code more readable.



_Code quote:_
```Go
	rangeIDs := make([]roachpb.RangeID, 0)
	replicaNodeIDs := make(map[roachpb.NodeID]struct{})
```
___
*[pkg/server/tenant_status.go, line 1051 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-Mwglxvo1DP9uEQu4c_8:-Mwglxvo1DP9uEQu4c_9:bc68qw7) ([raw file](https://github.com/cockroachdb/cockroach/blob/95ac8804eaffe8150cf06bbc5259bafacb9e6de5/pkg/server/tenant_status.go#L1051)):*
> ```Go
> 	ctx = t.AnnotateCtx(propagateGatewayMetadata(ctx))
> 	if _, err := t.privilegeChecker.requireAdminUser(ctx); err != nil {
> 		return nil, err
> ```

Was removing this intentional?



_Code quote:_
```Go
	if _, err := t.privilegeChecker.requireAdminUser(ctx); err != nil {
		return nil, err
	}
```

**Review by abarganier — COMMENTED** [review]
I've thought some more about the leaseholder-only issue. I propose that instead, we include metadata for all replicas. 

For each replica, instead of NodeID/ReplicaID, we distinguish them by their locality information.

We can also note which is the current leaseholder, and whether or not the lease is valid.  

Thoughts?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-:-MwhUazP6ycbpDXx__hM:b600bzj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @rimadeodhar, and @tbg)

___
*[pkg/ccl/kvccl/kvtenantccl/connector.go, line 123 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-Mwgey_M3ncWLYSYqNIu:-MwhGddaCivJsgn2KbCU:bljchi3) ([raw file](https://github.com/cockroachdb/cockroach/blob/63b13e035a68d94b8f5a5cb029cd83bc6430ab10/pkg/ccl/kvccl/kvtenantccl/connector.go#L123)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Nit: 'finding' debug information :)
</blockquote></details>

Haha, copypasta - done!
___
*[pkg/rpc/auth_tenant.go, line 250 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-MwgfPiu0u5yeLv1vLoZ:-MwhGhTP3BV_TDBMwEzv:b-ftwnwr) ([raw file](https://github.com/cockroachdb/cockroach/blob/63b13e035a68d94b8f5a5cb029cd83bc6430ab10/pkg/rpc/auth_tenant.go#L250)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

I'm wondering if we should make the error for the system tenant more descriptive? Like if the `tenID` is the system tenant, then return an error clarifying to use the `Ranges` endpoint?

Also, thinking about this more, I'm wondering whether there is any value in not allowing the system tenant to use TenantRanges? I realize that the `Ranges` endpoint makes more sense to call but there is no reason to actively disallow system tenant to call into `TenantRanges` is there?
</blockquote></details>

I think you're right - we can allow the system tenant here - as long as the tenantID is set in the context the operation should be able to proceed.

Removed the `SystemTenantID` check :thumbsup: 
___
*[pkg/server/status.go, line 1920 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-MwgfmRJ13LxIHSFii58:-MwhIsKC0_LhhDghT5lb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/63b13e035a68d94b8f5a5cb029cd83bc6430ab10/pkg/server/status.go#L1920)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Nit: superfluous line?
</blockquote></details>

Done.
___
*[pkg/server/status.go, line 2148 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-MwggHaxDSs3ld0Ob1D_:-MwhIvQ25vitIJ_QhYad:b-la7je5) ([raw file](https://github.com/cockroachdb/cockroach/blob/63b13e035a68d94b8f5a5cb029cd83bc6430ab10/pkg/server/status.go#L2148)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Please can you add some comments clarifying on what these two fields are used for? This will help make the code more readable.
</blockquote></details>

Sure! Done.
___
*[pkg/server/tenant_status.go, line 1051 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-Mwglxvo1DP9uEQu4c_8:-MwhKK-a3X9_EDGZFbB6:b7k7yht) ([raw file](https://github.com/cockroachdb/cockroach/blob/95ac8804eaffe8150cf06bbc5259bafacb9e6de5/pkg/server/tenant_status.go#L1051)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Was removing this intentional?
</blockquote></details>

:sweat_smile:  No, Fixed.

**Comment by abarganier** [comment]
Unit tests have been updated, PTAL

**Review by rimadeodhar — COMMENTED** [review]
LG overall. Mainly, had a question regarding the E2E test for tenant, seems like it shouldn't fail for tenant ranges but it is? Might need to modify the CLITest framework.

As for the open question regarding including all replicas, I think your proposal to distinguish by locality sounds reasonable. 

> Reviewed 10 of 10 files at r5, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-:-Mwi1AKY9iQcFBy3x23K:b6548um)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @knz, and @tbg)

___
*[pkg/server/testserver.go, line 480 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-Mwi-4R88ESX6C13G5dj:-Mwi-4R88ESX6C13G5dk:b-ne0w5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/00667d4086203554a711fec9114da46494798b56/pkg/server/testserver.go#L480)):*
> ```Go
> }
> 
> // TestingKnobs returns the TestingKnobs used by the TestServer.
> ```

Please update comment :).
___
*[pkg/cli/testdata/zip/testzip_tenant, line 22 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-Mwi0yl63WEFveFFZu7J:-Mwi0yl63WEFveFFZu7K:bxoiqlx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff2c98f1fcc335d3cd79202c9095f436955d0ccc/pkg/cli/testdata/zip/testzip_tenant#L22)):*
> ```
> [cluster] requesting data for debug/tenant_ranges... received response...
> [cluster] requesting data for debug/tenant_ranges: last request failed: rpc error: ...
> [cluster] requesting data for debug/tenant_ranges: creating error output: debug/tenant_ranges.json.err.txt... done
> ```

Shouldn't the testzip_tenant test be able to capture tenant ranges?



_Code quote:_
```
[cluster] requesting data for debug/tenant_ranges... received response...
[cluster] requesting data for debug/tenant_ranges: last request failed: rpc error: ...
[cluster] requesting data for debug/tenant_ranges: creating error output: debug/tenant_ranges.json.err.txt... done
```

**Review by abarganier — COMMENTED** [review]
Thanks for the feedback! 

I've gone ahead and updated `TenantRanges` to return range info segmented by locality information. Specifically, we use the availability zone (locality key `az`) as a key and default to `locality_unset`if `az` is unset. Note that this is the default locality key used in multi-tenant cluster configs. The range metadata will also include `is_leaseholder` and `valid_lease` info. 

The E2E test for the tenant is failing because the tenant ID is not being set within the context. I am going to continue working to find a proper fix for this.

Finally, this new format of segmenting ranges in `tenant-ranges.json` dramatically complicates the `hot-ranges-tenant.sh` script. Dealing with JSON was already difficult prior to things being broken down by availability zone.

In the interest of incremental progress/iteration, I'm going to drop the `hot-ranges-tenant.sh` from the scope of this PR and include it in a follow up PR.

The follow up PR can follow the range report dump format used by KV host debug zip's, where each node has a directory, and within each, a separate JSON file for each individual range metadata object. In the follow up PR I will change `tenant-ranges.json` to instead build directories, one per-AZ, and then have separate files for each range metadata object. This should dramatically simplify the `hot-ranges-tenant.sh` script, as well as be easier to navigate for the user.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-:-MwmXkMm3CpcD1I4j55x:b4osdms)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @rimadeodhar, and @tbg)

___
*[pkg/server/testserver.go, line 480 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-Mwi-4R88ESX6C13G5dj:-Mwm_bbFBBlQLKsV5ws7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/00667d4086203554a711fec9114da46494798b56/pkg/server/testserver.go#L480)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Please update comment :).
</blockquote></details>

Done.
___
*[pkg/cli/testdata/zip/testzip_tenant, line 22 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-Mwi0yl63WEFveFFZu7J:-Mwm_cQ74pJqqo7HWRLe:b61w2ol) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff2c98f1fcc335d3cd79202c9095f436955d0ccc/pkg/cli/testdata/zip/testzip_tenant#L22)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Shouldn't the testzip_tenant test be able to capture tenant ranges?
</blockquote></details>

Ah, thanks for catching this. It looks like the `TenantID` is not set in the context. Working on finding a fix for this now.

**Comment by abarganier** [comment]
> Trying to run the test in secure mode brought to light some issues. 

For now, we are going to leave these tests running in `--insecure` mode, as fixing the underlying test infra is out of scope for this PR. We will instead track those efforts in https://github.com/cockroachdb/cockroach/issues/77173

Since the underlying endpoint has been tested within `tenant_status_test.go`, and the `TestZipTenant` only provides a marginal additional level of test coverage, we have decided to proceed without this additional piece of coverage. We will update `TestZipTenant` once https://github.com/cockroachdb/cockroach/issues/77173 has been resolved.

Therefore, this PR is ready for another look 🙂

**Review by dhartunian — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, 3 of 3 files at r2, 8 of 16 files at r9, 22 of 22 files at r11, 2 of 10 files at r12, 5 of 5 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76743)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, @knz, @rimadeodhar, and @tbg)

___
*[pkg/rpc/auth_tenant.go, line 247 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-Mx0XDsIBVUP4wmcx7F6:-Mx0XDsIBVUP4wmcx7F7:b-p7b6t6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f11283c30a92550bd4caeacdcfb889fd412fa16/pkg/rpc/auth_tenant.go#L247)):*
> ```Go
> // tenantID has been set.
> func (a tenantAuthorizer) authTenantRanges(tenID roachpb.TenantID) error {
> 	if !tenID.IsSet() {
> ```

should we check that `a.tenantID` matches here? that's what `authTenant(tenID)` does.
___
*[pkg/server/status.go, line 2109 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-MxAVyhyDOM6j2yM7GDx:-MxAVyhyDOM6j2yM7GDy:b-z7vt9) ([raw file](https://github.com/cockroachdb/cockroach/blob/494baecebfee2c8b414ff29af0e46d26db95ef28/pkg/server/status.go#L2109)):*
> ```Go
> 
> 	nodeResults := make([][]serverpb.RangeInfo, 0, len(replicaNodeIDs))
> 	for nodeID := range replicaNodeIDs {
> ```

is there no facility for fan-out that can do this concurrently?
___
*[pkg/server/serverpb/status.go, line 79 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-Mx0WUccASgtdcdtbO79:-Mx0WUccASgtdcdtbO7A:bux1caa) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f11283c30a92550bd4caeacdcfb889fd412fa16/pkg/server/serverpb/status.go#L79)):*
> ```Go
> //
> // It is available for all tenants, except for the system tenant who should use `Ranges()`.
> type DebugStatusServer interface {
> ```

Is there a reason this interface name does not include `Tenant` or `SQL` in its name?
___
*[pkg/server/serverpb/status.proto, line 414 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-Mx0Z13E9zKjJ4xTqZep:-Mx0Z13E9zKjJ4xTqZeq:b-sn5wup) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f11283c30a92550bd4caeacdcfb889fd412fa16/pkg/server/serverpb/status.proto#L414)):*
> ```protobuf
> }
> 
> message TenantRangeInfo {
> ```

nit: docstring
___
*[pkg/cli/testdata/zip/testzip_tenant, line 22 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-Mwi0yl63WEFveFFZu7J:-MxAWpbe441Hcwz8NlKy:b1hortz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff2c98f1fcc335d3cd79202c9095f436955d0ccc/pkg/cli/testdata/zip/testzip_tenant#L22)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Ah, thanks for catching this. It looks like the `TenantID` is not set in the context. Working on finding a fix for this now.
</blockquote></details>

Does this still need updating?
___
*[pkg/server/status_test.go, line 1158 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-Mx0Zcax9bniEKiAx3hG:-Mx0ZGKo4dj5fyjGGXKn:b-cetvoq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f11283c30a92550bd4caeacdcfb889fd412fa16/pkg/server/status_test.go#L1158)):*
> ```Go
> 		rpcStopper := stop.NewStopper()
> 		defer rpcStopper.Stop(ctx)
> 		rpcContext := newRPCTestContext(ctx, ts, ts.RPCContext().Config)
> ```

any reason you can't use `ts.rpcContext` instead?

**Review by rimadeodhar — COMMENTED** [review]
+1 to David's comments. Other than that, :lgtm:

> Reviewed 1 of 10 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-:-MxAkidRBVPDd2MdbChU:b50avwg)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, @knz, and @rimadeodhar)

___
*[pkg/cli/zip.go, line 279 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-MxAjfYZ2iGgI9XfIhRV:-MxAjfYZ2iGgI9XfIhRW:b-ujl0nt) ([raw file](https://github.com/cockroachdb/cockroach/blob/3da015449a9a51d0f69e60d210c3e70e545ad5d9/pkg/cli/zip.go#L279)):*
> ```Go
> 	}
> 
> 	// A script to summarize the hottest ranges for host cluster range reports.
> ```

Nit: `storage server range reports` is probably better than `host cluster range reports`. Host cluster logic is specific to the serverless architecture.
___
*[pkg/server/serverpb/status.go, line 80 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-MxAk8Bx-eKTevbN-nKS:-MxAk8Bx-eKTevbN-nKT:bq799ck) ([raw file](https://github.com/cockroachdb/cockroach/blob/3da015449a9a51d0f69e60d210c3e70e545ad5d9/pkg/server/serverpb/status.go#L80)):*
> ```Go
> // range reports.
> //
> // It is available for all tenants, except for the system tenant who should use `Ranges()`.
> ```

Nit: I believe this comment is now stale since we allow calling this method even for system tenants.

**Review by abarganier — COMMENTED** [review]
Great feedback all, I appreciate it!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-:-MxBIJ244xeLdG9zR2Yr:b-e6lgkp)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian, @knz, and @rimadeodhar)

___
*[pkg/rpc/auth_tenant.go, line 247 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-Mx0XDsIBVUP4wmcx7F6:-MxAi3nN8YfQtJTmMIdj:bph7slf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f11283c30a92550bd4caeacdcfb889fd412fa16/pkg/rpc/auth_tenant.go#L247)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

should we check that `a.tenantID` matches here? that's what `authTenant(tenID)` does.
</blockquote></details>

`a.tenantID` is the tenant ID for the current node, which is set to SystemTenantID when running on a storage node. Because of this, checking that `a.tenantID == tenID` would never pass for this use case, since the `tenID` argument will be the tenantID of the caller, IIUC.

`authTenant(tenID)` is used for endpoints that should remain within a single tenant's pods, which is what `a,tenantID == tenID` enforces. In our case, the expectation is that the call crosses the Tenant/KV boundary via the tenant connector. 

I think this is sufficient, because checking is `tenID.IsSet()` means we're essentially leaning on the TLS auth step that happens just prior to calling into `auth_tenant`, which is where the `tenID` argument gets set. 
___
*[pkg/server/status.go, line 2109 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-MxAVyhyDOM6j2yM7GDx:-MxB8vmM6L2Fo8vV_uZN:bes3b3b) ([raw file](https://github.com/cockroachdb/cockroach/blob/494baecebfee2c8b414ff29af0e46d26db95ef28/pkg/server/status.go#L2109)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

is there no facility for fan-out that can do this concurrently?
</blockquote></details>

[`iterateNodes`](https://github.com/cockroachdb/cockroach/blob/master/pkg/server/status.go#L2382) exists and would be perfect, but it iterates *all* nodes. We just want to iterate a select few nodes here, so it's a bit overkill.

What we can do is create something like `iterateNodesInIDs(nodeIDs)` that allows us to filter down to just the nodeIDs we care about, but I'd like to avoid pulling that into the scope of this PR. How would you feel about including it in the scope of the upcoming PR for adding pagination to this endpoint? 
___
*[pkg/server/serverpb/status.go, line 79 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-Mx0WUccASgtdcdtbO79:-MxAj0snAOEbp2sF0nwF:bahpbn7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f11283c30a92550bd4caeacdcfb889fd412fa16/pkg/server/serverpb/status.go#L79)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Is there a reason this interface name does not include `Tenant` or `SQL` in its name?
</blockquote></details>

A `SQLStatusServer` already exists and is a smaller version of the serverpb.StatusInterface which includes only the methods used by the SQL subsystem.

`TenantStatusServer` sounds good to me, though. Changed it over.
___
*[pkg/server/serverpb/status.go, line 80 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-MxAk8Bx-eKTevbN-nKS:-MxAlm2i9OdfLeGK6_jM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3da015449a9a51d0f69e60d210c3e70e545ad5d9/pkg/server/serverpb/status.go#L80)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Nit: I believe this comment is now stale since we allow calling this method even for system tenants.
</blockquote></details>

Done.
___
*[pkg/server/serverpb/status.proto, line 414 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-Mx0Z13E9zKjJ4xTqZep:-MxBCypt0_YKXrZpJ1Hc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f11283c30a92550bd4caeacdcfb889fd412fa16/pkg/server/serverpb/status.proto#L414)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: docstring
</blockquote></details>

Done.
___
*[pkg/cli/testdata/zip/testzip_tenant, line 22 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-Mwi0yl63WEFveFFZu7J:-MxAhHUn84FJ3bJnwKkC:b-lrvw3m) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff2c98f1fcc335d3cd79202c9095f436955d0ccc/pkg/cli/testdata/zip/testzip_tenant#L22)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Does this still need updating?
</blockquote></details>

[We are leaving this be](https://github.com/cockroachdb/cockroach/pull/76743#issuecomment-1057076336) until https://github.com/cockroachdb/cockroach/issues/77173 is resolved. I've added a `TODO` to the test to update it once we get these tests working in secure mode. In the meantime we will lean on `TestTenantStatusAPI` for coverage.
___
*[pkg/server/status_test.go, line 1158 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-Mx0Zcax9bniEKiAx3hG:-MxAlc_9DC3s3C_WOyaS:b156cll) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f11283c30a92550bd4caeacdcfb889fd412fa16/pkg/server/status_test.go#L1158)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

any reason you can't use `ts.rpcContext` instead?
</blockquote></details>

Nope, didn't think of that one :D - fixed!
___
*[pkg/cli/zip.go, line 279 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/76743#-MxAjfYZ2iGgI9XfIhRV:-MxBGxDS6RyMOgeqNrDJ:b7i317h) ([raw file](https://github.com/cockroachdb/cockroach/blob/3da015449a9a51d0f69e60d210c3e70e545ad5d9/pkg/cli/zip.go#L279)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Nit: `storage server range reports` is probably better than `host cluster range reports`. Host cluster logic is specific to the serverless architecture.
</blockquote></details>

Thanks for catching this - it was a mistake to update this comment. I'll be sure to update it accordingly in https://github.com/cockroachdb/cockroach/pull/77225

**Review by rimadeodhar — APPROVED** [review]
> Reviewed 13 of 22 files at r14, 10 of 10 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76743)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian, @knz, and @rimadeodhar)

**Pull request merged**
