### PR TITLE
cli/start: use the same format for server details in multi-tenant

### PR DESCRIPTION
**Pull request by knz**
cc @tbg who wanted this.

This ensures that the server details are printed using the same format
as regular nodes for multi-tenant SQL servers.

Before:

```
SQL server for tenant 123 listening at 127.0.0.1:26258, http at 127.0.0.1:8081
```

After:
```
CockroachDB SQL server starting at 2021-12-10 12:11:57.684183707 +0000 UTC (took 0.1s)
build:               CCL v21.2.0-alpha.00000000-6604-g6f243c67e2-dirty @  (go1.17.4)
webui:               http://kenax:8081
sql:                 postgresql://root@kenax:26258/defaultdb?sslmode=disable
sql (JDBC):          jdbc:postgresql://kenax:26258/defaultdb?sslmode=disable&user=root
RPC client flags:    ./cockroach <client cmd> --host=kenax:26258 --insecure
temp dir:            /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/mt-data/cockroach-temp981776782
external I/O path:   <disabled>
store[0]:            path=/data/home/kena/src/go/src/github.com/cockroachdb/cockroach/mt-data
storage engine:      pebble
clusterID:           6622219f-89b7-4d0d-919f-22db8fa83dfd
tenantID:            123
instanceID:          3
```

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
NB: there were no tests to assert the output of server details in the multi-tenant case. I'm not adding them in this PR; they will be in #73306 which will be rebased on top.

**Review by stevendanna — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73676)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @stevendanna)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/73676#-MqZZ9Ln4OP1aT3Znfoi:-MqZZ9Ln4OP1aT3Znfoj:bg7igkv) (no related file):*
:lgtm: 

---
___
*[pkg/cli/start.go, line 909 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73676#-MqZYM0PD2SDIEDt1aOj:-MqZYM0PD2SDIEDt1aOk:bgsn659) ([raw file](https://github.com/cockroachdb/cockroach/blob/c631d86409d7c6e8e1545db600d63908c0c3a8eb/pkg/cli/start.go#L909)):*
> ```Go
> 	// earlier (e.g. above, in the runStart function) because
> 	// at this time the address and port have not been resolved yet.
> 	sCtx := rpc.MakeSecurityContext(serverCfg.Config, security.ClusterTLSSettings(serverCfg.Settings), roachpb.SystemTenantID)
> ```

note to self: It looks like the passed roachpb.SystemTenantID is irrelevant to the PGRUL function that we need this context for, so this is fine for both callers.
___
*[pkg/cli/start.go, line 950 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73676#-MqZYtTQ23t__T7hbXTq:-MqZYtTQ23t__T7hbXTr:brrna9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/c631d86409d7c6e8e1545db600d63908c0c3a8eb/pkg/cli/start.go#L950)):*
> ```Go
> 		buf.Printf("store[%d]:\t%s\n", i, spec)
> 	}
> 	buf.Printf("storage engine: \t%s\n", &serverCfg.StorageEngine)
> ```

Is this relevant for SQL servers? No harm in including it either way I suppose.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73676)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @stevendanna)

___
*[pkg/cli/start.go, line 909 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73676#-MqZYM0PD2SDIEDt1aOj:-MqZchRO0U-sDrYrt8ag:b-c3ylwu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c631d86409d7c6e8e1545db600d63908c0c3a8eb/pkg/cli/start.go#L909)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

note to self: It looks like the passed roachpb.SystemTenantID is irrelevant to the PGRUL function that we need this context for, so this is fine for both callers.
</blockquote></details>

Yes, correct - this function creates a client context, which doesn't care about the tenant ID.
___
*[pkg/cli/start.go, line 950 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73676#-MqZYtTQ23t__T7hbXTq:-MqZclbr-IRa9WLAWOnw:bmbbcvv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c631d86409d7c6e8e1545db600d63908c0c3a8eb/pkg/cli/start.go#L950)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Is this relevant for SQL servers? No harm in including it either way I suppose.
</blockquote></details>

Yep it is - SQL servers use the storage package for spilling SQL data to disk.

**Comment by knz** [comment]
TFYR!

bors r=stevendanna

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73676)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz and @stevendanna)

___
*[pkg/cli/start.go, line 950 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73676#-MqZYtTQ23t__T7hbXTq:-MqZfwVY2FwyVKIDn36f:b46f787) ([raw file](https://github.com/cockroachdb/cockroach/blob/c631d86409d7c6e8e1545db600d63908c0c3a8eb/pkg/cli/start.go#L950)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Yep it is - SQL servers use the storage package for spilling SQL data to disk.
</blockquote></details>

Ah, right. Thanks.

**Comment by knz** [comment]
lint failure
bors r-

**Comment by knz** [comment]
bors r=stevendanna

**Comment by tbg** [comment]
I don't remember wanting this, but looks nice nevertheless!

**Pull request merged**
