### PR TITLE
opt: add rules to push negation through And/Or; build RangeCond

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: add rules to push negation through And/Or

Normalization rules to convert:
```
NOT (a AND b) -> (NOT a) OR (NOT b)
NOT (a OR b)  -> (NOT a) AND (NOT b)
```

Release note: None

#### opt: build RangeCond

Support for `BETWEEN` syntax. We don't add an operator, but directly
construct the equivalent expression.

Note that the current planner does the same normalization.
Unfortunately this normalization is problematic if the expressions
have side-effects. Leaving that as a TODO for now.

Release note: None

### CODE REVIEW

**Comment by rytaft** [comment]
Reviewed 5 of 5 files at r1, 2 of 4 files at r2.
Review status: 6 of 8 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/exec/execbuilder/testdata/scalar, line 445 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23567#-L71QcD50DpTUFYPYyhU:-L71QcD50DpTUFYPYyhV:b-2s0t28) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef42c98f0dc4ca3afa02b476cd0923890bd1e9ff/pkg/sql/opt/exec/execbuilder/testdata/scalar#L445)):*
> ```
> ----
> render     0  render  ·         ·                                                   (column8)                          ·
>  │         0  ·       render 0  ((a >= b) AND (a <= d)) OR ((a >= b) AND (a <= d))  ·                                  ·
> ```

This doesn't seem right.... you've got `cond1 OR cond1`. Why not just `cond1`?

---

*[pkg/sql/opt/exec/execbuilder/testdata/scalar, line 454 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23567#-L71QuJtJyDIxxscl7u6:-L71QuJtJyDIxxscl7u7:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef42c98f0dc4ca3afa02b476cd0923890bd1e9ff/pkg/sql/opt/exec/execbuilder/testdata/scalar#L454)):*
> ```
> ----
> render     0  render  ·         ·                                              (column8)                          ·
>  │         0  ·       render 0  ((a < b) OR (a > d)) AND ((a < b) OR (a > d))  ·                                  ·
> ```

ditto

---

*[pkg/sql/opt/optbuilder/scalar.go, line 342 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23567#-L71RPOXeO2NjGzG2vvX:-L71RPOXeO2NjGzG2vvY:b-f116mb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef42c98f0dc4ca3afa02b476cd0923890bd1e9ff/pkg/sql/opt/optbuilder/scalar.go#L342)):*
> ```Go
> 		rhs := b.factory.ConstructAnd(
> 			b.factory.InternList([]opt.GroupID{
> 				b.factory.ConstructGe(input, from),
> ```

I think this is the culprit. from->to and to->from

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23567)*

**Comment by RaduBerinde** [comment]
Review status: 6 of 8 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/optbuilder/scalar.go, line 342 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23567#-L71RPOXeO2NjGzG2vvX:-L71YhaUZF7pK4-KCUBs:b-dkd6u8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef42c98f0dc4ca3afa02b476cd0923890bd1e9ff/pkg/sql/opt/optbuilder/scalar.go#L342)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I think this is the culprit. from->to and to->from
</blockquote></details>

Oops, good catch. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23567)*

**Comment by andy-kimball** [comment]
Review status: 5 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/opt/xform/rules/bool.opt, line 88 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23567#-L71Z6aJIuxMDahD-RGB:-L71Z6aKJuKC9KW4cb7T:b-skq0ay) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef42c98f0dc4ca3afa02b476cd0923890bd1e9ff/pkg/sql/opt/xform/rules/bool.opt#L88)):*
> ```
> (Not (And $conditions:*))
> =>
> (NegateAnd $conditions)
> ```

I'd write the replace pattern something like this:
```
(Or (NegateConditions $conditions))
```
That way, you can reuse the `NegateConditions` function below, and not have to duplicate it in `factory.go`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23567)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23567#-:-L71_elou8-Wm1zrrq2q:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 5 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/opt/xform/rules/bool.opt, line 88 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23567#-L71Z6aJIuxMDahD-RGB:-L71dBRVRUIZkdXkUs6f:b-vy8sd7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef42c98f0dc4ca3afa02b476cd0923890bd1e9ff/pkg/sql/opt/xform/rules/bool.opt#L88)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I'd write the replace pattern something like this:
```
(Or (NegateConditions $conditions))
```
That way, you can reuse the `NegateConditions` function below, and not have to duplicate it in `factory.go`.
</blockquote></details>

Very nice, not sure why i didn't think of that. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23567)*

**Comment by andy-kimball** [comment]
:lgtm:
I'd add a bit more testing, but other than that, looks good.

---

Review status: 5 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/xform/testdata/rules/bool, line 420 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/23567#-L71eeL4QCYgWf6F1UpN:-L71eeL4QCYgWf6F1UpO:b-snc79t) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0e657e36e1525555eec8c036619adbaf764fb28/pkg/sql/opt/xform/testdata/rules/bool#L420)):*
> ```
> # --------------------------------------------------
> opt
> SELECT * FROM a WHERE NOT (k >= i AND i < f)
> ```

I'd strengthen these tests by adding another level of AND's:

`SELECT * FROM a WHERE NOT (k >= i AND i < f AND (i > 5 AND i < 10 AND))`

Same goes for OR's below.

I'd also add a test case that combines AND and OR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23567#-:-L71fIvDGk83Qn4wk38j:bivserb)*

**Comment by RaduBerinde** [comment]
Had to add a shadowing warning exception for `.og.go` files in `TestVet`.

**Comment by rytaft** [comment]
Reviewed 1 of 3 files at r4, 1 of 8 files at r5.
Review status: 2 of 9 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/xform/factory.go, line 361 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/23567#-L751zbYtO5W7hdzo3K4:-L751zbYtO5W7hdzo3K5:by91za1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0131879145c3563e957b6a306fcce227c7ed8bcb/pkg/sql/opt/xform/factory.go#L361)):*
> ```Go
> }
> 
> // negateAnd negates the given conditions and puts them in a new list.
> ```

negateAnd -> negateConditions

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23567)*

**Comment by RaduBerinde** [comment]
Review status: 1 of 9 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/xform/factory.go, line 361 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/23567#-L751zbYtO5W7hdzo3K4:-L75cKoz24mVDhtfDNqu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0131879145c3563e957b6a306fcce227c7ed8bcb/pkg/sql/opt/xform/factory.go#L361)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

negateAnd -> negateConditions
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23567)*

**Pull request merged**
