### PR TITLE
clusterversion: remove NamespaceTableWithSchemas*

### PR DESCRIPTION
**Pull request by postamar**
clusterversion: remove NamespaceTableWithSchemas*
    
    This commit removes the NamespaceTableWithSchemas and
    NamespaceTableWithSchemasMigration cluster version keys
    and all the version-gated code pertaining to them.
    
    Notably, this removes all references to system.namespace2 as well as the
    deprecated namespace table at descriptor ID 2.
    
    Partially addresses #65200.
    
    Release note: None

    clusterversion: add DeleteDeprecatedNamespaceTableDescriptorMigration
    
    This commit adds a migration which removes all traces of the deprecated
    namespace table descriptor as well as the system.namespace2 table name.
    
    Release note (sql change): Namespace entries may no longer be queried
    via `system.namespace2`.

### CODE REVIEW

**Comment by postamar** [comment]
OK, this should be ready for review now. Until now there were quite a few issues with the migration, which seem to have all disappeared after replacing the SQL queries to change `system.descriptor` and `system.namespace` with catalogkv calls.

**Comment by postamar** [comment]
Rebased to fix merge conflict.

**Review by ajwerner — APPROVED** [review]
:lgtm: sorry for the late review

> Reviewed 63 of 75 files at r1, 13 of 13 files at r2, 5 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65340#-:-Mb6dLJB3KtF_A96KtN6:b-b1ivye)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/ccl/backupccl/restore_job.go, line 421 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65340#-Mae7jcm2sMun2Uo8UbE:-Mae7jcm2sMun2Uo8UbF:b-vopfmm) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b019a166e4a182da0bd7d042e7551303d148c7f/pkg/ccl/backupccl/restore_job.go#L421)):*
> ```Go
> 			// namespace table to write the descriptor into. This may cause wrong
> 			// behavior if the cluster version is bumped DURING a restore.
> 			tkey := catalogkv.MakeObjectNameKey(table.GetParentID(), table.GetParentSchemaID(), table.GetName())
> ```

should this move to catalogkeys?
___
*[pkg/keys/constants.go, line 351 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65340#-Mae8YZq-yT3nBjsxu9F:-Mae8YZq-yT3nBjsxu9G:b-t9sv0j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b019a166e4a182da0bd7d042e7551303d148c7f/pkg/keys/constants.go#L351)):*
> ```Go
> 	// DeprecatedNamespaceTableID was the tableID for the system.namespace table
> 	// for pre-20.1 clusters.
> 	DeprecatedNamespaceTableID = 2 // pseudo
> ```

Unfortunately `pseudo` has a rather specific (and somewhat broken) meaning. See the array below this block. 
___
*[pkg/migration/migrations/delete_deprecated_namespace_tabledesc.go, line 38 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65340#-Mb6cSX5BHXZNpwfjpW9:-Mb6cSX5BHXZNpwfjpWA:bn9p9q0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5d0de7fd5717015b66c2ea49b0c02033c697ea6/pkg/migration/migrations/delete_deprecated_namespace_tabledesc.go#L38)):*
> ```Go
> 	return d.DB.Txn(ctx, func(ctx context.Context, txn *kv.Txn) error {
> 		b := txn.NewBatch()
> 		b.DelRange(deprecatedTablePrefix, deprecatedTablePrefix.PrefixEnd(), false /* returnKeys */)
> ```

I'm pretty certain we don't ever expect to find any keys here. We've had several fancy migrations to ensure that we copy everything over. In principle there really shouldn't be anything in this span. Would it be crazy to fail here if this returns a non-empty set?
___
*[pkg/migration/migrations/delete_deprecated_namespace_tabledesc_external_test.go, line 55 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65340#-Mb6cFjz0rCAEizgvJfA:-Mb6cFjz0rCAEizgvJfB:bisv1a3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5d0de7fd5717015b66c2ea49b0c02033c697ea6/pkg/migration/migrations/delete_deprecated_namespace_tabledesc_external_test.go#L55)):*
> ```
> 		b.Put(catalogkeys.NewPublicTableKey(keys.SystemDatabaseID, `namespace`).Key(codec), keys.DeprecatedNamespaceTableID)
> 		b.Put(catalogkeys.NewPublicTableKey(keys.SystemDatabaseID, `namespace2`).Key(codec), keys.NamespaceTableID)
> ```
This is going to format the key with the schema of the new namespace table, right? That doesn't matter because the code doesn't decode the keys, but it is probably worth noting.

**Review by postamar — COMMENTED** [review]
Thanks for the review, nothing to apologize for, this wasn't pressing.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65340#-:-MbIrDj7Ck-Bm1afVbo9:bc2dguc)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

___
*[pkg/ccl/backupccl/restore_job.go, line 421 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65340#-Mae7jcm2sMun2Uo8UbE:-MbIrIe60zKxjhDlQUlL:b-im7540) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b019a166e4a182da0bd7d042e7551303d148c7f/pkg/ccl/backupccl/restore_job.go#L421)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

should this move to catalogkeys?
</blockquote></details>

Yes! I'll do so in a follow-up PR. I did this and then more, got slightly carried away in fact, but the end result is beyond the scope of this here PR.
___
*[pkg/keys/constants.go, line 351 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65340#-Mae8YZq-yT3nBjsxu9F:-MbIrTy6D11Xg8R-CNuu:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b019a166e4a182da0bd7d042e7551303d148c7f/pkg/keys/constants.go#L351)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Unfortunately `pseudo` has a rather specific (and somewhat broken) meaning. See the array below this block. 
</blockquote></details>

Fixed.
___
*[pkg/migration/migrations/delete_deprecated_namespace_tabledesc.go, line 38 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65340#-Mb6cSX5BHXZNpwfjpW9:-MbIrZYn-cA1pJb627Q3:b-in4z5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5d0de7fd5717015b66c2ea49b0c02033c697ea6/pkg/migration/migrations/delete_deprecated_namespace_tabledesc.go#L38)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I'm pretty certain we don't ever expect to find any keys here. We've had several fancy migrations to ensure that we copy everything over. In principle there really shouldn't be anything in this span. Would it be crazy to fail here if this returns a non-empty set?
</blockquote></details>

Right! I added a panic just to be extra sure this never happens.
___
*[pkg/migration/migrations/delete_deprecated_namespace_tabledesc_external_test.go, line 55 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65340#-Mb6cFjz0rCAEizgvJfA:-MbIreVm0NPGXpqZb2CC:b-ogtsnt) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5d0de7fd5717015b66c2ea49b0c02033c697ea6/pkg/migration/migrations/delete_deprecated_namespace_tabledesc_external_test.go#L55)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 		b.Put(catalogkeys.NewPublicTableKey(keys.SystemDatabaseID, `namespace`).Key(codec), keys.DeprecatedNamespaceTableID)
> 		b.Put(catalogkeys.NewPublicTableKey(keys.SystemDatabaseID, `namespace2`).Key(codec), keys.NamespaceTableID)
> ```
This is going to format the key with the schema of the new namespace table, right? That doesn't matter because the code doesn't decode the keys, but it is probably worth noting. 
</blockquote></details>

Yes, and since my latest changes if it weren't then the migration would panic. I seem to remember that this key actually shows up sometimes, hence why I test for it. I can't remember the exact details but I do remember being quite careful about what I tested here so I'm hoping you'll trust my nebulous memories on this one :)

**Review by ajwerner — COMMENTED** [review]
:lgtm_strong: 

> Reviewed 15 of 29 files at r4, 8 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65340#-:-MbIu14zAPjryr8l2aam:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by postamar** [comment]
CI was failing for good reason. As it turns out, the old namespace table can in fact legitimately still have rows in it. This is the case for rows created prior to the new namespace table even becoming a thing. These will have corresponding entries in the new namespace table. We've made it so deleting an entry in the new namespace table also deletes its equivalent in the old namespace table, so the latter doesn't grow it only shrinks.

This is why, now, instead of panicking when rows are found in the old namespace table, I panic only when there's no matching row in the new namespace table.

**Comment by postamar** [comment]
Rebased to fix merge conflicts.

**Comment by ajwerner** [comment]
> This is the case for rows created prior to the new namespace table even becoming a thing. 

What does this mean? Do you mean that we write to both and have been writing to both since, well, forever?

**Comment by postamar** [comment]
Here's how it works, by example:
1. I have a super old cluster, say 19.1. `CREATE DATABASE foo` adds an entry to the deprecated namespace table.
2. I upgrade that cluster all the way to 21.1. The migrations ensure that `foo` now also has an entry in the new namespace table. The migration doesn't touch the deprecated namespace table. 
3. `CREATE DATABASE bar` adds an entry to the new namespace table and doesn't touch the deprecated namespace table either. 
4. However `DROP DATABASE foo` removes entries from both the deprecated and the new namespace tables.

**Review by ajwerner — COMMENTED** [review]
> The migration doesn't touch the deprecated namespace table.

Ah, I thought we deleted from the old table, but I guess not. 

:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65340#-:-MbbcLth-ERnSUeQBQso:b-ocl3p0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Pull request merged**
