### PR TITLE
pkg/server/debug: add tenant ID filtering to debug/logspy

### PR DESCRIPTION
**Pull request by abarganier**
**NB: The first commit updates crdb_v1 to always tag log entries with the tenant ID. See commit description for details.**

We need to ensure that any log-related debug endpoints that
can be used by tenants (especially those available in DB
Console) filter to the specific tenant that made the request.
This is important to respect tenant boundaries when it comes
to logging data.

This patch updates the `debug/logspy` endpoint to filter logs
to only include those belonging to the tenant handling the
request.

For the system tenant, we apply no such filtering. The system
tenant has sufficient privilege to view logs across tenants,
so we avoid filtering in this case.

Another thing of note is that previously, the `log.Interceptor`
had no chance of error generation. Instead, any errors would
be created after consuming off the channel that the interceptor
produced into. Specifically, if we ever failed to unmarshall
the raw JSON bytes into a `logpb.Entry`, which was not a
tolerated error.

Now that the interceptor filters on tenant ID, it needs to
unmarshall the raw JSON bytes for each log entry into a
`logpb.Entry` so that it can filter against the tenant ID.
This creates an opportunity for error within the interceptor
that didn't exist before, and as before, we do not want to
tolerate such errors in the logSpy system. However, the
interceptor's interface does not allow us to return an error.

As a solution, the logSpyInterceptor now has an error channel
that the Interceptor can produce into if any errors occur
when unmarshalling JSON. The logSpy's run routine will
exit upon receiving an error on this channel. The behavior
should effectively be the same: we didn't tolerate parse
errors before, and we don't with these updates either.

Release note: none

Epic: CRDB-14486

Addresses https://github.com/cockroachdb/cockroach/issues/94779

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 2 of 31 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94777)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @abarganier, and @knz)

___
*[`-- commits` line 104 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/94777#-NLMIq2nCZtalCsxuNdK):*
two questions here:

1. Why even write errors to a channel? Can't we just log them and continue?
2. Why should an error cause an exit in logspy? Can we just continue with the rest of the logs?
___
*[`pkg/server/debug/logspy.go` line 293 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/94777#-NLMJDMCCGkD57XA2p3W:-NLMJDMCCGkD57XA2p3X:bwp5214) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a0680859063d58046377152cb5aedba7a6d027b/pkg/server/debug/logspy.go#L293)):*
> ```Go
> 	var entry logpb.Entry
> 	if err := json.Unmarshal(jsonEntry, &entry); err != nil {
> 		i.errCh <- errors.NewAssertionErrorWithWrappedErrf(err, "could not unmarshal entry: %s", jsonEntry)
> ```

this channel is initialized unbuffered, which means this call may block. is that the behavior we want? I'm not entirely sure how `Intercept` works but if it's in the path of logging, would that block logging?
___
*[`pkg/server/debug/server.go` line 147 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/94777#-NLMGX0oCRuRqMscpg0F:-NLMGX0oCRuRqMscpg0G:b-auq0jn) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a0680859063d58046377152cb5aedba7a6d027b/pkg/server/debug/server.go#L147)):*
> ```Go
> 		panic("programmer error: failed parsing ambientCtx tenantID during debug.Server initialization")
> 	}
> 	tID, err := roachpb.MakeTenantID(parsed)
> ```

you can use `MustMakeTenantID` here if you want.
___
*[`pkg/util/log/format_crdb_v1.go` line 438 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94777#-NLMAn4j0tenHDclMs_-:-NLMAn4j0tenHDclMs_0:biv74dd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d3226e5b5101994dda2bbb336fa7b4f0057660d/pkg/util/log/format_crdb_v1.go#L438)):*
> ```Go
> 		}
> 		// Process the remaining tags.
> 		tagsWithoutTenantID := v2TenantIdTagSelect.ReplaceAllString(string(m[7]), "")
> ```

can you perhaps rename `v2TenantIdTagSelect` since it's now used for v1 as well?

**Review by abarganier — COMMENTED** [review]
Thanks for the feedback, PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94777#-:-NLRP4F85UZLm_nhoncJ:bppiuow)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @dhartunian, and @knz)

___
*[`-- commits` line 104 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/94777#-NLMIq2nCZtalCsxuNdK):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

two questions here:

1. Why even write errors to a channel? Can't we just log them and continue?
2. Why should an error cause an exit in logspy? Can we just continue with the rest of the logs?
</blockquote></details>

1. It changes the behavior a bit (before, we didn't tolerate unmarshal errors), but I don't see it as a big deal to change this... especially considering the introduction of the error channel comes with complexity & risk! Updated to just log, count the entry as dropped, and continue.
2. It was the old behavior (not tolerating unmarshal errors) that I was trying to maintain for no good reason, but now we will just log & record that the message was dropped and continue.
___
*[`pkg/server/debug/logspy.go` line 293 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/94777#-NLMJDMCCGkD57XA2p3W:-NLRGNkhCyhm4KORJpMH:b-d257dm) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a0680859063d58046377152cb5aedba7a6d027b/pkg/server/debug/logspy.go#L293)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

this channel is initialized unbuffered, which means this call may block. is that the behavior we want? I'm not entirely sure how `Intercept` works but if it's in the path of logging, would that block logging?
</blockquote></details>

Removed the errCh entirely.
___
*[`pkg/server/debug/server.go` line 147 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/94777#-NLMGX0oCRuRqMscpg0F:-NLRJBjI24dMDidWa4Io:b-voo9gk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a0680859063d58046377152cb5aedba7a6d027b/pkg/server/debug/server.go#L147)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

you can use `MustMakeTenantID` here if you want.
</blockquote></details>

Done - thank you! 
___
*[`pkg/util/log/format_crdb_v1.go` line 438 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94777#-NLMAn4j0tenHDclMs_-:-NLROrx4BBkVlep_1HYi:br6bb41) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d3226e5b5101994dda2bbb336fa7b4f0057660d/pkg/util/log/format_crdb_v1.go#L438)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

can you perhaps rename `v2TenantIdTagSelect` since it's now used for v1 as well?
</blockquote></details>

Good idea - done!

**Review by knz — COMMENTED** [review]
Good work on the architecture. No comment there.
I've noticed two small things that I believe are important.

> Reviewed 2 of 3 files at r1, 34 of 34 files at r4, 2 of 2 files at r5, 31 of 31 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94777#-:-NLReoml53ycpB4WCtq9:b-wa300n)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @abarganier, and @dhartunian)

___
*[`pkg/server/debug/logspy.go` line 288 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/94777#-NLReRQn6zd8m6uktUSi:-NLReRQn6zd8m6uktUSj:bm8gtqy) ([raw file](https://github.com/cockroachdb/cockroach/blob/01170741510a53df23cd3c72491c846ab9753f0c/pkg/server/debug/logspy.go#L288)):*
> ```Go
> 	if err := json.Unmarshal(jsonEntry, &entry); err != nil {
> 		// Failed to unmarshal, so just log & mark the entry as dropped and continue.
> 		log.Errorf(i.ctx, "logspy failed to unmarshal entry: %v - err: %v", entry, err)
> ```

that will cause a circular re-entry into logging and the interceptor, resulting in an infinite call stack (and a crash).
IMHO if you encounter an error here you should just inject it into `i.jsonEntry` too.
___
*[`pkg/util/log/format_crdb_v1.go` line 438 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94777#-NLRdfUYEwvsJ4cmQQFK:-NLRdfUYEwvsJ4cmQQFL:b-kwic8o) ([raw file](https://github.com/cockroachdb/cockroach/blob/7de36ac5fc5083c16e363190f052f2c39fe06281/pkg/util/log/format_crdb_v1.go#L438)):*
> ```Go
> 		}
> 		// Process the remaining tags.
> 		tagsWithoutTenantID := crdbFmtTenantIdTagSelect.ReplaceAllString(string(m[7]), "")
> ```

since you guarangee the tag is at the beginning, could you perhaps do a slice truncation (up to first `,`) instead of applying a regex? the regex is an expensive solution and it results in a heap allocation, which i believe is not warranted here.

**Review by abarganier — COMMENTED** [review]
TFTR everyone, RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94777#-:-NLX8TA09qaRx6Qbdtga:b-4nkpkn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @dhartunian, and @knz)

___
*[`pkg/server/debug/logspy.go` line 288 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/94777#-NLReRQn6zd8m6uktUSi:-NLX85ie71em-yIlNxKq:b7mq3nc) ([raw file](https://github.com/cockroachdb/cockroach/blob/01170741510a53df23cd3c72491c846ab9753f0c/pkg/server/debug/logspy.go#L288)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

that will cause a circular re-entry into logging and the interceptor, resulting in an infinite call stack (and a crash).
IMHO if you encounter an error here you should just inject it into `i.jsonEntry` too.
</blockquote></details>

Thanks for catching this! If an error occurs here we now pass it along in the payload to `i.jsonEntry`, and the consumer will return the error once consumed. Let me know if I misunderstood your suggestion.
___
*[`pkg/util/log/format_crdb_v1.go` line 438 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94777#-NLRdfUYEwvsJ4cmQQFK:-NLX8H_44R_mUxk4ZZo3:b-e5av0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/7de36ac5fc5083c16e363190f052f2c39fe06281/pkg/util/log/format_crdb_v1.go#L438)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

since you guarangee the tag is at the beginning, could you perhaps do a slice truncation (up to first `,`) instead of applying a regex? the regex is an expensive solution and it results in a heap allocation, which i believe is not warranted here.
</blockquote></details>

Thanks for the advice - removed the TenantID tag regex for both the `crdb_v1` and `crdb_v2` formats.

**Review by knz — COMMENTED** [review]
> Reviewed 2 of 35 files at r7, 2 of 2 files at r8, 31 of 31 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94777)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @abarganier, and @dhartunian)

___
*[`pkg/util/log/format_crdb_v1.go` line 431 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/94777#-NLX8zl1D2iyx5R99kJC:-NLX8zl1D2iyx5R99kJD:b8osfv) ([raw file](https://github.com/cockroachdb/cockroach/blob/784fd3a9389364def2b5489204196edd1a788b10/pkg/util/log/format_crdb_v1.go#L431)):*
> ```Go
> 		// Look for a tenant ID tag. Default to system otherwise.
> 		entry.TenantID = systemTenantID
> 		tagsToProcess := string(m[7])
> ```

Please avoid the conversion to `string` which forces a heap allocation.
Instead, keep `[]byte` and use `bytes.HasPrefix` and `bytes.IndexByte` to search for the comma.
___
*[`pkg/util/log/format_crdb_v2.go` line 700 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/94777#-NLX9EIH--fn82wJHDJG:-NLX9EIH--fn82wJHDJH:b-483ac3) ([raw file](https://github.com/cockroachdb/cockroach/blob/784fd3a9389364def2b5489204196edd1a788b10/pkg/util/log/format_crdb_v2.go#L700)):*
> ```Go
> 	// Strip out the tenant ID tag. We handle it separately in getTenantID().
> 	if strings.HasPrefix(tagsStr, TenantIDLogTagKey) {
> 		tenantIDSplit := strings.SplitN(tagsStr, ",", 2)
> ```

`strings.IndexByte`

**Review by abarganier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94777)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @dhartunian, and @knz)

___
*[`pkg/util/log/format_crdb_v1.go` line 431 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/94777#-NLX8zl1D2iyx5R99kJC:-NLXYAnz5DOEXwsstWkp:bjomwfl) ([raw file](https://github.com/cockroachdb/cockroach/blob/784fd3a9389364def2b5489204196edd1a788b10/pkg/util/log/format_crdb_v1.go#L431)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Please avoid the conversion to `string` which forces a heap allocation.
Instead, keep `[]byte` and use `bytes.HasPrefix` and `bytes.IndexByte` to search for the comma.
</blockquote></details>

Thanks for being vigilant here! Done. Let me know if you think there's any more efficiency to be gained.
___
*[`pkg/util/log/format_crdb_v2.go` line 700 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/94777#-NLX9EIH--fn82wJHDJG:-NLXYIBCBn6pV8jj9qst:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/784fd3a9389364def2b5489204196edd1a788b10/pkg/util/log/format_crdb_v2.go#L700)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

`strings.IndexByte`
</blockquote></details>

Done.

**Review by knz — COMMENTED** [review]
> Reviewed 2 of 36 files at r10, 1 of 2 files at r11, 2 of 2 files at r12, 31 of 31 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94777)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @abarganier, and @dhartunian)

___
*[`pkg/util/log/format_crdb_v1.go` line 437 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/94777#-NLXdz2qBv-gjbcRqw88:-NLXdz2qBv-gjbcRqw89:bnsod9z) ([raw file](https://github.com/cockroachdb/cockroach/blob/52f8d7a9c3ec02da6116593a947442d279dd7ac2/pkg/util/log/format_crdb_v1.go#L437)):*
> ```Go
> 			if commaIndex >= 0 {
> 				// More tags exist than just the tenant ID tag.
> 				entry.TenantID = string(tagsToProcess[1:commaIndex])
> ```

I wonder if we can also get rid of this conversion. The tenant ID is a number. Can we maybe extract the number from the string and have an int instead of string in `entry`?

**Review by abarganier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94777)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @dhartunian, and @knz)

___
*[`pkg/util/log/format_crdb_v1.go` line 437 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/94777#-NLXdz2qBv-gjbcRqw88:-NLXfzlA3rden8pbspUi:b-hb3t7n) ([raw file](https://github.com/cockroachdb/cockroach/blob/52f8d7a9c3ec02da6116593a947442d279dd7ac2/pkg/util/log/format_crdb_v1.go#L437)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I wonder if we can also get rid of this conversion. The tenant ID is a number. Can we maybe extract the number from the string and have an int instead of string in `entry`?
</blockquote></details>

I'm open to the idea! I think I chose to use a string because the ID is served as a string from the `idPayload` in the context when encoding, but the decode side doesn't *need* to be influenced by the encode side of things. It would require some broader changes that fall outside the scope of this PR, so I'd like to handle that in its own thread.

I already got a couple good pieces of feedback from Andrei on the tenant ID log tagging stuff that I'm going to address (kind of like a "various QoL improvements" PR). I think this suggestion would fit nicely alongside it if you're okay with that.

**Review by knz — APPROVED** [review]
yes that's good. I'm pulling on this thread because we know that log parsing has historically been a perf bottleneck so it's a worthy area to be careful about.

**Comment by abarganier** [comment]
> I'm pulling on this thread because we know that log parsing has historically been a perf bottleneck so it's a worthy area to be careful about.

It's very much appreciated 🙏 thanks for the review!

**Review by dhartunian — APPROVED** [review]
:lgtm: I think the last commit msg needs revising.

> Reviewed 35 of 35 files at r7, 2 of 2 files at r8, 1 of 31 files at r9, 2 of 36 files at r10, 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94777#-:-NLaPaq_3WKvtJH5QSpv:bgawcb9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi, @abarganier, and @knz)

___
*[`-- commits` line 99 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/94777#-NLaPg1o1XVhAof7wW7v):*
nit: This is no longer true, right?

**Review by abarganier — COMMENTED** [review]
TFTR :purple_heart: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94777#-:-NLawh9D8-4bSFIjZRJ0:b-rzxmo8)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aadityasondhi, @dhartunian, and @knz)

___
*[`-- commits` line 99 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/94777#-NLaPg1o1XVhAof7wW7v):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: This is no longer true, right?
</blockquote></details>

Thanks for catching! Fixed

**Pull request merged**
