### PR TITLE
kvserver: remove above-raft throttling of AddSST

### PR DESCRIPTION
**Pull request by tbg**
We now rely on admission control to protect the nodes.[^1]

[^1]: https://github.com/cockroachdb/cockroach/pull/98762#discussion_r1164701947

Epic: none
Release note (ops change): The following cluster settings were retired and no longer have any effect:
- kv.bulk_io_write.concurrent_addsstable_requests
- kv.bulk_io_write.concurrent_addsstable_as_writes_requests
- rocksdb.ingest_backpressure.l0_file_count_threshold
- rocksdb.ingest_backpressure.max_delay

### CODE REVIEW

**Comment by tbg** [comment]
@irfansharif could you give me an explanation on why we're now fine removing this? Because we have sufficient integration with admission control? Or because we just don't think this will do more harm than good?

**Comment by tbg** [comment]
Friendly ping.

**Comment by irfansharif** [comment]
I miscommunicated the sequencing, I don't think we should get rid of these for at least a few weeks. Not until https://github.com/cockroachdb/cockroach/pull/98308 has landed and has had chance to bake on master as enabled. This is just out of an abundance of caution and not inviting more CI fallout than necessary. What I can do instead is assign myself this PR, mark it as draft, and take it over the finish line when ready.

**Comment by irfansharif** [comment]
> Because we have sufficient integration with admission control? Or because we just don't think this will do more harm than good?

Yes to both, after the kvflowcontrol machinery is used by default, we should have sufficient protection using just AC machinery and I don't think these limiters would really be meaningful.

**Comment by tbg** [comment]
👍🏽 Would you mind re-opening under your name? That way it doesn't dangle around in my workflows. Thanks!

**Pull request closed without merging**
