### PR TITLE
bulk: add flush metrics

### PR DESCRIPTION
**Pull request by pbardea**
This commit adds the following metrics:
- bulk.written_bytes
- bulk.sst_flush.range
- bulk.sst_flush.size
- bulk.sst_flush.manual

Release note (ops change): Add metrics around bulk operations flushing
and bulk operations write rate.

Release justification: low risk observability changes.

### CODE REVIEW

**Comment by pbardea** [comment]
cc @dt 

I wanted to grab your thoughts on whether these metrics seem worthwhile. The motivation was that it was fairly difficult to see the progress that bulk jobs were making (especially when there was ongoing traffic). I was also curious if any other metrics stood out as potentially useful.

**Review by dt — APPROVED** [review]
I'm a little skeptical of cluster-wide metric vs something per-job, but i think it is better than nothing so LGTM

**Review by irfansharif — COMMENTED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67659#-:-MiRxc137kEHrb5aQkO3:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru)

**Review by itsbilal — APPROVED** [review]
:lgtm_strong: 

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67659#-:-MiRxgrB2ri15Yq4rqUk:b-uwkowd)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @adityamaru)

**Review by adityamaru — APPROVED** [review]

**Review by alyshanjahani-crl — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67659#-:-MiRy0TK9GmGT1ln-zbM:bnfp4nl)* status: :shipit: complete! 3 of 0 LGTMs obtained (waiting on @pbardea)

**Review by adityamaru — APPROVED** [review]
:lgtm:

**Review by arulajmani — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67659#-:-MiRzW8f3RQ21pHDOcKo:bg7igkv)* status: :shipit: complete! 5 of 0 LGTMs obtained (waiting on @pbardea)

**Review by abhimadan — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67659#-:-MiS-WaZ2KMeRUJ7bahH:bg7igkv)* status: :shipit: complete! 6 of 0 LGTMs obtained (waiting on @pbardea)

**Review by gautamgupta — APPROVED** [review]
:shipit:

**Review by bananabrick — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67659)* status: :shipit: complete! 6 of 0 LGTMs obtained (waiting on @pbardea)

**Review by otan — APPROVED** [review]

**Comment by pbardea** [comment]
TFTRs!
bors r+

**Pull request closed without merging**
