### PR TITLE
exec: support index/lookup joins

### PR DESCRIPTION
**Pull request by asubiotto**
First two commits are #33376 #33384

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
Great work - it's satisfyingly simple.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33428#-:-LVEnJ0F2v8iO_ntsoVs:b-hr3lfd)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 59 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/33428#-LVEnewk73akRmPYn_18:-LVEnewk73akRmPYn_19:b-r9nibr) ([raw file](https://github.com/cockroachdb/cockroach/blob/61645651512e43deae538ffed449864fd2c5dc60/pkg/sql/distsqlrun/column_exec_setup.go#L59)):*
> ```Go
> 		toWrapInput = c.input
> 	} else {
> 		// TODO(asubiotto): What should be happening here?
> ```

This is just a final projection that lets you exclude some columns from the final output. I don't think it's necessary anymore now that we have the SimpleProject operators and stuff. I think you could delete the argument from newMaterializer completely, if you felt like it.
___
*[pkg/sql/distsqlrun/columnarizer.go, line 79 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/33428#-LVEmoQdA4lui006xDm9:-LVEmoQe6JooXCxH6PI1:b-47f2fj) ([raw file](https://github.com/cockroachdb/cockroach/blob/61645651512e43deae538ffed449864fd2c5dc60/pkg/sql/distsqlrun/columnarizer.go#L79)):*
> ```Go
> 			// panic("TODO(jordan): columnarizer needs to forward metadata.")
> 			// TODO(asubiotto): Is this dangerous? We're not forwarding metadata from
> 			// tableReader reads so I don't think dropping metadata like this is worse
> ```

What do you mean we're not forwarding metadata from tableReader reads?

I think you're right that it's probably fine. but don't we sometimes need to return metadata? We do need to think of a better story around that eventually.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33428)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 59 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/33428#-LVEnewk73akRmPYn_18:-LVYHrUOCYvPq7kPCVfg:bnqw2qr) ([raw file](https://github.com/cockroachdb/cockroach/blob/61645651512e43deae538ffed449864fd2c5dc60/pkg/sql/distsqlrun/column_exec_setup.go#L59)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This is just a final projection that lets you exclude some columns from the final output. I don't think it's necessary anymore now that we have the SimpleProject operators and stuff. I think you could delete the argument from newMaterializer completely, if you felt like it.
</blockquote></details>

Great. I'm going to merge this with the argument but will remove it in a following PR
___
*[pkg/sql/distsqlrun/columnarizer.go, line 79 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/33428#-LVEmoQdA4lui006xDm9:-LVYI9JC7H5CAOD38AyX:b88vix7) ([raw file](https://github.com/cockroachdb/cockroach/blob/61645651512e43deae538ffed449864fd2c5dc60/pkg/sql/distsqlrun/columnarizer.go#L79)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

What do you mean we're not forwarding metadata from tableReader reads?

I think you're right that it's probably fine. but don't we sometimes need to return metadata? We do need to think of a better story around that eventually.
</blockquote></details>

The use of `tableReader` was a mistake. Just meant that we aren't currently forwarding any metadata (e.g. misplanned ranges). Maybe something to look into when I get back. I'm thinking of ProcessorGroup, another option would be forwading metadata as we do with wrapped plan node subtrees.

**Comment by asubiotto** [comment]
Added a fix to decode decimal keys into ColVecs and extracted this and other fixes into their own commit, all tests should pass now

**Pull request merged**
