### PR TITLE
plpgsql: add support for integer-range FOR loops

### PR DESCRIPTION
**Pull request by DrewKimball**
#### plpgsql: add parser support for integer FOR loops

This commit adds support in the PL/pgSQL parser for integer FOR loops,
which iterate a counter over a user-defined integer range.

Informs #105246

Release note: None

#### plpgsql: support integer range FOR loops

This commit adds support for integer FOR loops in PL/pgSQL. This allows
users to iterate over a range of integer values using the following syntax:
```
FOR target IN [ REVERSE ] expr .. expr [ BY expr ] LOOP ...
```

Informs #105246

Release note (sql change): Added support for PL/pgSQL integer FOR loops,
which iterate over a range of integer values.

### CODE REVIEW

**Comment by mgartner** [comment]
Sorry for the delay! I'll review soon. cc @michae2

**Review by michae2 — APPROVED** [review]
:lgtm: Sorry for the delay, it took me a while to get into it. This is excellent, I just have nits.

Do we have a way to print the routines constructed for PL/pgSQL?

Also would be nice to have a way to print the "stacktrace" of routine calls during execution.

> Reviewed 6 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130211#-:-O7oxnHm9Kr9UCRsChY-:b-t6cpox)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 313 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130211#-O7oa06iEKswQ67Bdpw_:-O7oa06iEKswQ67Bdpwa:b-hxj00q) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab5b1165645a4a17461de103e84a64683ac3cbb0/pkg/sql/opt/optbuilder/plpgsql.go#L313)):*
> ```Go
> // should use popBlock() to remove the block from the stack once it is out of
> // scope.
> func (b *plpgsqlBuilder) newBlock(astBlock *ast.Block) *plBlock {
> ```

nit: might be good to put "push" in the name, since this has the side-effect of pushing the block onto the stack.
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 1117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130211#-O7oxZXC3WOsyXNlxi-M:-O7oxZXC3WOsyXNlxi-N:b-5xx750) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab5b1165645a4a17461de103e84a64683ac3cbb0/pkg/sql/opt/optbuilder/plpgsql.go#L1117)):*
> ```Go
> 	upperRef := tree.NewUnresolvedName(upperVar.String())
> 	stepRef := tree.NewUnresolvedName(stepVar.String())
> 	counterVar := addDecl(b.makeIdentifier("_loop_counter"), types.Int, lowerRef, false /* constant */)
> ```

Is there a way to protect the counterVar from being referenced by user-written PL/pgSQL?
___
*[`pkg/sql/plpgsql/parser/lexer.go` line 460 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130211#-O7kXN5kEL9yOFIwmiIS:-O7kXN5lDBJOJXW4htNa:b-4hdke0) ([raw file](https://github.com/cockroachdb/cockroach/blob/85498b19104492def4deb8de6e75680dc1dd7d8d/pkg/sql/plpgsql/parser/lexer.go#L460)):*
> ```Go
> 	}
> 	if parenLevel != 0 {
> 		return 0, 0, 0, errors.New("mismatched parentheses")
> ```

Why does this function do parentheses matching? Seems like the calls to `parser.ParseOne` and `parser.ParseExprs` should be handling parentheses matching?
___
*[`pkg/sql/sem/plpgsqltree/statements.go` line 668 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130211#-O6XF25Y0_9keqcJKzDC:-O6XEkjs0UX1Moils2eR:b-ofi6zn) ([raw file](https://github.com/cockroachdb/cockroach/blob/85498b19104492def4deb8de6e75680dc1dd7d8d/pkg/sql/sem/plpgsqltree/statements.go#L668)):*
> ```Go
> 	ctx.WriteString(" LOOP\n")
> 	for _, stmt := range s.Body {
> 		ctx.FormatNode(stmt)
> ```

Does this need whitespace between statements? Or indentation?
___
*[`pkg/sql/sem/plpgsqltree/utils/plpg_visitor.go` line 217 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130211#-O7fTz9K-6CH0tiCaRwa:-O7fTz9K-6CH0tiCaRwb:b2wn1tl) ([raw file](https://github.com/cockroachdb/cockroach/blob/85498b19104492def4deb8de6e75680dc1dd7d8d/pkg/sql/sem/plpgsqltree/utils/plpg_visitor.go#L217)):*
> ```Go
> 			newStmt = cpy
> 		}
> 		e, v.Err = simpleVisit(t.Condition, v.Fn)
> ```

unrelated to this PR, but why does While visit the condition twice?
___
*[`pkg/ccl/logictestccl/testdata/logic_test/udf_plpgsql` line 2848 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130211#-O7oTy6hCl2Y9Jhbv2O8:-O7oTy6hCl2Y9Jhbv2O9:bmz5gcw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab5b1165645a4a17461de103e84a64683ac3cbb0/pkg/ccl/logictestccl/testdata/logic_test/udf_plpgsql#L2848)):*
> ```
> NOTICE: DONE
> 
> # BY syntax allows changing the step size.
> ```

What happens if the step is bigger than upper - lower?
___
*[`pkg/ccl/logictestccl/testdata/logic_test/udf_plpgsql` line 2930 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130211#-O7oSkj-DWB1w_8PJ_ix:-O7oSkj-DWB1w_8PJ_iy:bwrdnpj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab5b1165645a4a17461de103e84a64683ac3cbb0/pkg/ccl/logictestccl/testdata/logic_test/udf_plpgsql#L2930)):*
> ```
> NOTICE: DONE
> 
> # REVERSE syntax allows changing the direction of the loop.
> ```

Might also be nice to see REVERSE with (a) BY, (b) negative numbers, (c) reversed bounds.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/udf_plpgsql` line 3112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130211#-O7oTako2tOYqMIu0yp3:-O7oTako2tOYqMIu0yp4:b-rkkl9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab5b1165645a4a17461de103e84a64683ac3cbb0/pkg/ccl/logictestccl/testdata/logic_test/udf_plpgsql#L3112)):*
> ```
> 
> statement error pgcode 22004 pq: lower bound of FOR loop cannot be null
> SELECT f(NULL);
> ```

Does this work if x is not null?

It might also be nice to see the lower and upper bounds as parameters.

**Review by mgartner — APPROVED** [review]
:lgtm: Once you address Michael's comments.

> Reviewed 6 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130211#-:-O9Ai7tX1g5rXJ2Pvkr3:b-7gwik0)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 337 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130211#-O9Aelet46oB8DIg0V3r:-O9Aelet46oB8DIg0V3s:bi12313) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab5b1165645a4a17461de103e84a64683ac3cbb0/pkg/sql/opt/optbuilder/plpgsql.go#L337)):*
> ```Go
> }
> 
> // addDeclarations adds the given variable declarations to the current block.
> ```

nit: "current" => "given"
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 634 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130211#-O9AhrcrEK59neE3lEa4:-O9AhrcrEK59neE3lEa5:b-jio9dp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab5b1165645a4a17461de103e84a64683ac3cbb0/pkg/sql/opt/optbuilder/plpgsql.go#L634)):*
> ```Go
> 			case *ast.IntForLoopControl:
> 				// FOR target IN [ REVERSE ] expr .. expr [ BY expr ] LOOP ...
> 				return b.handleIntForLoop(s, t, c)
> ```

It seems like it should be possible to implement FOR IN with an AST rewrite, like WHILE, but more complicated. I'm curious if that is something you considered?
___
*[`pkg/sql/plpgsql/parser/testdata/stmt_for` line 216 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130211#-O9Ad4lFAom5L5fcyhu-:-O9Ad4lFAom5L5fcyhu0:bxcovmn) ([raw file](https://github.com/cockroachdb/cockroach/blob/85498b19104492def4deb8de6e75680dc1dd7d8d/pkg/sql/plpgsql/parser/testdata/stmt_for#L216)):*
> ```
> HINT: try \h SET SESSION
> 
> # Invalid syntax in second expression.
> ```

nit: add test for an invalid `BY` expression

**Review by DrewKimball — COMMENTED** [review]
TFTRs!

I ended up changing the logic a bit to introduce the concept of "hidden variables", which can be manipulated by the PL/pgSQL builder directly, but cannot be referenced by the user. This is implemented as anonymous columns resolved using the metadata name. I'm open to other suggestions for how to approach this :)

>Do we have a way to print the routines constructed for PL/pgSQL?

We can see the call structure through an opt test - I added one for a simple FOR loop.

>Also would be nice to have a way to print the "stacktrace" of routine calls during execution.

Do you mean raise notices indicating which sub-routine is executing?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130211#-:-O9Oh8Z86wX8Kns1Lqa3:b-rmc3c)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @mgartner and @michae2)

___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 313 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130211#-O7oa06iEKswQ67Bdpw_:-O8IGzZK28HLSh2A4qUp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab5b1165645a4a17461de103e84a64683ac3cbb0/pkg/sql/opt/optbuilder/plpgsql.go#L313)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: might be good to put "push" in the name, since this has the side-effect of pushing the block onto the stack.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 337 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130211#-O9Aelet46oB8DIg0V3r:-O9Ob-kT8hQHjq9EkuHm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab5b1165645a4a17461de103e84a64683ac3cbb0/pkg/sql/opt/optbuilder/plpgsql.go#L337)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: "current" => "given"
</blockquote></details>

Done.
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 634 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130211#-O9AhrcrEK59neE3lEa4:-O9Ob1S5AM0tyfc_niwK:b-jyw48c) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab5b1165645a4a17461de103e84a64683ac3cbb0/pkg/sql/opt/optbuilder/plpgsql.go#L634)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It seems like it should be possible to implement FOR IN with an AST rewrite, like WHILE, but more complicated. I'm curious if that is something you considered?
</blockquote></details>

I did consider it, but thought it would be more straightforward to just directly implement it. I think it's a moot point now though - since we need to support "hidden" variables. I guess we could potentially add support for those to the AST as well...
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 1117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130211#-O7oxZXC3WOsyXNlxi-M:-O8IHU3U3J9KGZEKX1Td:b-a65ex6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab5b1165645a4a17461de103e84a64683ac3cbb0/pkg/sql/opt/optbuilder/plpgsql.go#L1117)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Is there a way to protect the counterVar from being referenced by user-written PL/pgSQL?
</blockquote></details>

Great point.
___
*[`pkg/sql/plpgsql/parser/lexer.go` line 460 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130211#-O7kXN5kEL9yOFIwmiIS:-O9OblQo0jkicFgWZKGY:bcu48eu) ([raw file](https://github.com/cockroachdb/cockroach/blob/85498b19104492def4deb8de6e75680dc1dd7d8d/pkg/sql/plpgsql/parser/lexer.go#L460)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Why does this function do parentheses matching? Seems like the calls to `parser.ParseOne` and `parser.ParseExprs` should be handling parentheses matching?
</blockquote></details>

Good question. Postgres does it, but I don't see why the SQL parser couldn't handle it. I'd rather not change it here, though.
___
*[`pkg/sql/sem/plpgsqltree/statements.go` line 668 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130211#-O6XF25Y0_9keqcJKzDC:-O9Oc-ThCLgEhXV96jCi:b-z2wt2h) ([raw file](https://github.com/cockroachdb/cockroach/blob/85498b19104492def4deb8de6e75680dc1dd7d8d/pkg/sql/sem/plpgsqltree/statements.go#L668)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Does this need whitespace between statements? Or indentation?
</blockquote></details>

Each statement will write itself on a new line, with a terminating semicolon. Indentation would be nice, but it's difficult to get right - for example, if you have multiple indenting statements. [Here's a tracking issue](https://github.com/cockroachdb/cockroach/issues/112136) for improving the formatting.
___
*[`pkg/sql/sem/plpgsqltree/utils/plpg_visitor.go` line 217 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130211#-O7fTz9K-6CH0tiCaRwa:-O9OcVF3AEOxW8ZKLavB:bme764b) ([raw file](https://github.com/cockroachdb/cockroach/blob/85498b19104492def4deb8de6e75680dc1dd7d8d/pkg/sql/sem/plpgsqltree/utils/plpg_visitor.go#L217)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

unrelated to this PR, but why does While visit the condition twice?
</blockquote></details>

Just an accidental copy. Removed it :)
___
*[`pkg/ccl/logictestccl/testdata/logic_test/udf_plpgsql` line 2848 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130211#-O7oTy6hCl2Y9Jhbv2O8:-O9OcmHW-NaLCv27tzjm:b-32g917) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab5b1165645a4a17461de103e84a64683ac3cbb0/pkg/ccl/logictestccl/testdata/logic_test/udf_plpgsql#L2848)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

What happens if the step is bigger than upper - lower?
</blockquote></details>

We should terminate after just one iteration. I added a test for this.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/udf_plpgsql` line 2930 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130211#-O7oSkj-DWB1w_8PJ_ix:-O9OdRn--WSsJIMnjlkZ:b-aqox6u) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab5b1165645a4a17461de103e84a64683ac3cbb0/pkg/ccl/logictestccl/testdata/logic_test/udf_plpgsql#L2930)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Might also be nice to see REVERSE with (a) BY, (b) negative numbers, (c) reversed bounds.
</blockquote></details>

Good ideas, Done.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/udf_plpgsql` line 3112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130211#-O7oTako2tOYqMIu0yp3:-O9OfO-2AzdAbJFO6GGF:b-rinxpa) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab5b1165645a4a17461de103e84a64683ac3cbb0/pkg/ccl/logictestccl/testdata/logic_test/udf_plpgsql#L3112)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Does this work if x is not null?

It might also be nice to see the lower and upper bounds as parameters.
</blockquote></details>

I've replaced this with a test case that has parameterized bounds and step size.
___
*[`pkg/sql/plpgsql/parser/testdata/stmt_for` line 216 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130211#-O9Ad4lFAom5L5fcyhu-:-O9Ofum29DgES-UGIOu_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/85498b19104492def4deb8de6e75680dc1dd7d8d/pkg/sql/plpgsql/parser/testdata/stmt_for#L216)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: add test for an invalid `BY` expression
</blockquote></details>

Done.

**Review by michae2 — APPROVED** [review]
:lgtm: Nice work!! This is very impressive!

> We can see the call structure through an opt test - I added one for a simple FOR loop.

This is cool!

> Do you mean raise notices indicating which sub-routine is executing?

This is a wishlist item, but it would be nice if an error in a sub-routine also came with the stack of routines that had called this sub-routine. And maybe also a line number. :slightly_smiling_face:

> Reviewed 7 of 7 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130211#-:-O9Rz5ouD5t6EmcfzJDy:b-eljnb0)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 1117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130211#-O7oxZXC3WOsyXNlxi-M:-O9RxglFCvm05XwxNhY1:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab5b1165645a4a17461de103e84a64683ac3cbb0/pkg/sql/opt/optbuilder/plpgsql.go#L1117)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Great point.
</blockquote></details>

Nice!
___
*[`pkg/sql/plpgsql/parser/lexer.go` line 460 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130211#-O7kXN5kEL9yOFIwmiIS:-O9Rvs_K2gEFsp7V0Dx8:b-81nlyc) ([raw file](https://github.com/cockroachdb/cockroach/blob/85498b19104492def4deb8de6e75680dc1dd7d8d/pkg/sql/plpgsql/parser/lexer.go#L460)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Good question. Postgres does it, but I don't see why the SQL parser couldn't handle it. I'd rather not change it here, though.
</blockquote></details>

SGTM.
___
*[`pkg/sql/sem/plpgsqltree/statements.go` line 668 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130211#-O6XF25Y0_9keqcJKzDC:-O9RwMNCAe82IXDQGAax:bg2j5h2) ([raw file](https://github.com/cockroachdb/cockroach/blob/85498b19104492def4deb8de6e75680dc1dd7d8d/pkg/sql/sem/plpgsqltree/statements.go#L668)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Each statement will write itself on a new line, with a terminating semicolon. Indentation would be nice, but it's difficult to get right - for example, if you have multiple indenting statements. [Here's a tracking issue](https://github.com/cockroachdb/cockroach/issues/112136) for improving the formatting.
</blockquote></details>

Makes sense, thanks!

**Comment by DrewKimball** [comment]
TFTR!
>This is a wishlist item, but it would be nice if an error in a sub-routine also came with the stack of routines that had called this sub-routine. And maybe also a line number. 🙂

Here's a tracking issue for improving error context in PL/pgSQL: https://github.com/cockroachdb/cockroach/issues/132906

**Pull request merged**
