### PR TITLE
ttljob: mark errors as retryable when possible

### LINKED ISSUE #110823: ttljob: investigate "could not register flowID because the registry is draining" error
A cluster encountered this error:
```
ROW LEVEL TTL job 899375493495848962: stepping through state failed with unexpected error: could not register flowID because the registry is draining
(1)
```

https://cockroachlabsgcp.splunkcloud.com/en-US/app/search/search?earliest=1694444400&latest=1695052327&q=search%20index%3Dcc-app-crdb*%20severity%3DERROR%20%22row%20level%20ttl%22%20%22stepping%20through%20state%20failed%22%20%7C%20timechart%20span%3D1h%20count%20by%20friendly_id&display.page.search.mode=verbose&dispatch.sample_ratio=1&display.general.type=statistics&display.page.search.tab=events&workload_pool=standard_perf&sid=1695052417.480201

We may be missing a check for how the job should behave when a node is shutting down, or there may be an underlying issue with the flow registry. Investigate the error and check if the SQL Queries team can help. If this is expected, then let's not log it as an error.

Jira issue: CRDB-31638

### LINKED ISSUE #117985: ttl: job failure due to "no inbound connection stream"
Seeing a TTL job issue on the DRT cluster (`cct-232`) for job 935605994824925191.  The job starts up and makes some progress but then stumbles due to a rolling upgrade (failing on several nodes before being restarted on node 10).  Finally, it fails with the error seen below.

```
E240118 21:26:04.729236 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68975  ROW LEVEL TTL job 935605994824925191: stepping through state reverting with unexpected error: no inbound stream connection
E240118 21:26:04.729236 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68975 +(1) attached stack trace
E240118 21:26:04.729236 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68975 +  -- stack trace:
E240118 21:26:04.729236 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68975 +  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.init
E240118 21:26:04.729236 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68975 +  |         github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow_registry.go:32
E240118 21:26:04.729236 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68975 +  | runtime.doInit1
E240118 21:26:04.729236 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68975 +  |         GOROOT/src/runtime/proc.go:6757
E240118 21:26:04.729236 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68975 +  | runtime.doInit
E240118 21:26:04.729236 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68975 +  |         GOROOT/src/runtime/proc.go:6724
E240118 21:26:04.729236 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68975 +  | runtime.main
E240118 21:26:04.729236 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68975 +  |         GOROOT/src/runtime/proc.go:249
E240118 21:26:04.729236 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68975 +  | runtime.goexit
E240118 21:26:04.729236 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68975 +  |         src/runtime/asm_amd64.s:1650
E240118 21:26:04.729236 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68975 +Wraps: (2) no inbound stream connection
E240118 21:26:04.729236 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68975 +Error types: (1) *withstack.withStack (2) *errutil.leafError
E240118 21:26:04.880779 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68976  ROW LEVEL TTL job 935605994824925191: stepping through state failed with unexpected error: no inbound stream connection
E240118 21:26:04.880779 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68976 +(1) attached stack trace
E240118 21:26:04.880779 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68976 +  -- stack trace:
E240118 21:26:04.880779 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68976 +  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.init
E240118 21:26:04.880779 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68976 +  |         github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow_registry.go:32
E240118 21:26:04.880779 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68976 +  | runtime.doInit1
E240118 21:26:04.880779 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68976 +  |         GOROOT/src/runtime/proc.go:6757
E240118 21:26:04.880779 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68976 +  | runtime.doInit
E240118 21:26:04.880779 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68976 +  |         GOROOT/src/runtime/proc.go:6724
E240118 21:26:04.880779 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68976 +  | runtime.main
E240118 21:26:04.880779 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68976 +  |         GOROOT/src/runtime/proc.go:249
E240118 21:26:04.880779 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68976 +  | runtime.goexit
E240118 21:26:04.880779 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68976 +  |         src/runtime/asm_amd64.s:1650
E240118 21:26:04.880779 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68976 +Wraps: (2) no inbound stream connection
E240118 21:26:04.880779 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68976 +Error types: (1) *withstack.withStack (2) *errutil.leafError
E240118 21:26:05.127384 771020 jobs/adopt.go:461 ⋮ [T3,Vapplication,n10] 68977  job 935605994824925191: adoption completed with error no inbound stream connection
```

Not sure if this is an code issue or not, so opening this issue for tracking purposes.  Sending to Queries for a first crack.  Please reassign as necessary.

Jira issue: CRDB-35444

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/110823
fixes https://github.com/cockroachdb/cockroach/issues/117985
Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm: although it might be good to get an approval from Jobs knowledgeable person too, like @dt or @stevendanna 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118298#-:-NoyO4OQCMiRNv2UPsWz:bop7od6)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @annrpom and @rafiss)

___
*[`pkg/sql/ttl/ttljob/ttljob.go` line 295 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118298#-NoyNjJQ4_sao-aNYySF:-NoyNjJQ4_sao-aNYySG:b-nlz492) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d4e887238a23c584cf7a03be927f0fd9e894ed5/pkg/sql/ttl/ttljob/ttljob.go#L295)):*
> ```Go
> 	}
> 
> 	return group.Wait()
> ```

nit: it might be good to also wrap the error returned by `group.Wait()` (IIUC it's only the stats fetching error when `ReturnStatsError` testing knob is set) for completeness.

**Review by stevendanna — COMMENTED** [review]
I think this change makes sense for this job type.

The main worry when using the job system's built-in retry mechanism is that it currently does exponential backoff that can eventually push your job's next adoption time up to 24 hours into the future.  That is mostly a problem for long-running jobs that might hit many errors in the lifetime of the job.  If you think this might be problematic for the TTL job (I'm not too familiar with its internals), the other pattern we use is to have a retry loop inside the resumer itself so that you can control the policy to be more appropriate to the job and to reset the job system's run stats for your job once you make some forward progress.

**Review by stevendanna — APPROVED** [review]

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118298)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @annrpom)

___
*[`pkg/sql/ttl/ttljob/ttljob.go` line 295 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118298#-NoyNjJQ4_sao-aNYySF:-Np_pw2h7xgQcnO1uYEk:b-ia4mfl) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d4e887238a23c584cf7a03be927f0fd9e894ed5/pkg/sql/ttl/ttljob/ttljob.go#L295)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: it might be good to also wrap the error returned by `group.Wait()` (IIUC it's only the stats fetching error when `ReturnStatsError` testing knob is set) for completeness.
</blockquote></details>

done; moved the wrapping into a defer

**Review by rafiss — COMMENTED** [review]
tftr! 

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118298#-:-Np_q40L7Wg2DU-KcVKY:bcmaa2f)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @annrpom and @yuzefovich)

**Pull request merged**
