### PR TITLE
release-23.1: CRDB-28040 : JWKS fetch from jwks_uri

### PR DESCRIPTION
**Pull request by dhartunian**
Backport 1/1 commits from #117054.

/cc @cockroachdb/release

---

Fixes CRDB-28040 ( JWKS fetch from jwks_uri )
This commit adds capability to fetch remote JWKS from issuer's jwks_uri endpoint. This will satisfy the requirement to have an ability to automatically fetch the new JWK when the existing JWK is rotated - without human intervention or custom scripts.

Changes include

1. The existing order of token signature verification first and rest of claims next is modified to get issuer first and then the token signature verification. This change is requied to determine the issuer for which the jwks has to be fetched remotely.

2. Introduction of a new cluster setting called `server.jwt_authentication.jwks_auto_fetch.enabled`

3. Depending on the value of `server.jwt_authentication.jwks_auto_fetch.enabled` use JWKS configured through cluster setting or remotely fetch JWKS from jwks_uri of the issuer

4. Modification to exiting test cases to match the new order of verification steps.

The change is backward compatible and not changes required in existing deployments and JWT Auth usage.

----

Release justification: high-priority need for functionality in 23.1

### CODE REVIEW

**Comment by BabuSrithar** [comment]
Have built 23.1 locally with this branch and tested following scenarios. 
1. JWT Authentication with and without `server.jwt_authentication.jwks_auto_fetch.enabled`, switching back and forth.
2. OIDC Login through UI.

**Comment by BabuSrithar** [comment]
Thanks for creating the backport and resolving the conflicts @dhartunian !

**Review by rafiss — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119969)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @BabuSrithar)

**Comment by dikshant** [comment]
@dhartunian It seems the 23.1.17-rc branch was already cut and we also need to backport into that branch. Any chance you can help do it?

**Comment by BabuSrithar** [comment]
blathers backport release-23.1.17-rc

**Pull request merged**
