### PR TITLE
opt: Add next batch of scalar rules to optimizer

### PR DESCRIPTION
**Pull request by andy-kimball**
This PR has two commits to make it easier to review. One adds the OuterCols property to the scalar logical properties (which was small change, but causes big test diffs), and the other adds a number of new scalar rewrite rules.

### CODE REVIEW

**Comment by andy-kimball** [comment]
As I mention in the PR comment, I'd recommend reviewing this one commit at a time, since 1st commit is small but has a lot of noise.

**Comment by RaduBerinde** [comment]
:lgtm:

This must have been pretty tedious, but still much better than implementing each rule in go.

---

Review status: 0 of 62 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/xform/factory.go, line 137 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-L6vpmIYTAfmQ1gk9fux:-L6vpmIYTAfmQ1gk9fuy:b-dyt556) ([raw file](https://github.com/cockroachdb/cockroach/blob/263c6f976582d6e4c6afad4fb771b1741ac3b370/pkg/sql/opt/xform/factory.go#L137)):*
> ```Go
> }
> 
> // constructSortedSet sorts the given list and removes duplicates, and returns
> ```

The name doesn't suggest that duplicates are removed, I'm worried someone might see it in a rule and create a new rule that uses it without realizing this. Maybe `constructSortedDedupedSet`

---

*[pkg/sql/opt/xform/factory.go, line 415 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-L6vkbFkJ4HLyYPGB6GJ:-L6vkbFkJ4HLyYPGB6GK:b-7qa4p9) ([raw file](https://github.com/cockroachdb/cockroach/blob/263c6f976582d6e4c6afad4fb771b1741ac3b370/pkg/sql/opt/xform/factory.go#L415)):*
> ```Go
> }
> 
> // commuteInequality swaps the operands of a inequality comparison expression,
> ```

[nit] an

---

*[pkg/sql/opt/xform/logical_props.go, line 74 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-L6vkH0SMIDwajgUb54b:-L6vkH0SMIDwajgUb54c:bb7p50t) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b9a1a1025ba9e2ea2f7ce6d47fe25696b2e8754/pkg/sql/opt/xform/logical_props.go#L74)):*
> ```Go
> 	// "outer"). Note that what constitutes an "outer column" is dependent on
> 	// an expression's lcoation in the query. For example, while the b.x and
> 	// b.y columns are not outer columns on the EXISTS expression, the *are*
> ```

they

---

*[pkg/sql/opt/xform/typing.go, line 232 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-L6vn1MpCIGdSWilq06J:-L6vn1MpCIGdSWilq06K:bs27es3) ([raw file](https://github.com/cockroachdb/cockroach/blob/263c6f976582d6e4c6afad4fb771b1741ac3b370/pkg/sql/opt/xform/typing.go#L232)):*
> ```Go
> 	// right children.
> 	for _, binOverloads := range tree.BinOps[binOp] {
> 		o := binOverloads.(tree.BinOp)
> ```

Is it possible to have multiple overloads match?

---

*[pkg/sql/opt/xform/rules/numeric.opt, line 59 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-L6vn_hwqjLmZIA0pRgx:-L6vn_hwqjLmZIA0pRgy:b-lywno6) ([raw file](https://github.com/cockroachdb/cockroach/blob/263c6f976582d6e4c6afad4fb771b1741ac3b370/pkg/sql/opt/xform/rules/numeric.opt#L59)):*
> ```
> $left
> 
> # FoldUnaryMinusZero folds -0 for numeric types (except for float which has
> ```

Doesn't decimal also have -0 ?
```
root@:26257/radu> SELECT * from b;
+---+
| k |
+---+
| 1 |
| 2 |
| 3 |
| 4 |
+---+
(4 rows)

Time: 2.376354ms

root@:26257/radu> SELECT -((k-1)/2) FROM b;
+----------------+
| -((k - 1) / 2) |
+----------------+
|             -0 |
|           -0.5 |
|             -1 |
|           -1.5 |
+----------------+
(4 rows)
```

---

*[pkg/sql/opt/xform/rules/scalar.opt, line 121 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-L6vqZaezSI1M7f56L0D:-L6vqZaezSI1M7f56L0E:bneyxxs) ([raw file](https://github.com/cockroachdb/cockroach/blob/263c6f976582d6e4c6afad4fb771b1741ac3b370/pkg/sql/opt/xform/rules/scalar.opt#L121)):*
> ```
> (True)
> 
> # FoldInNull replaces the In/Not operator with Null when the tuple only
> ```

[nit] maybe move the rule below NormalizeInConst which is referenced

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-:-L6vqvjw985TL4hYDDap:b644u6h)*

**Comment by rytaft** [comment]
:lgtm: 

I'm not sure we really need to print outer cols in all of our test output... maybe it would be worth adding a flag to include it in the output or not?

---

Reviewed 31 of 31 files at r1, 40 of 40 files at r2.
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt_index_selection.go, line 147 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-L6voYf3xcj0QUooKiq3:-L6voYf3xcj0QUooKiq4:bda4iog) ([raw file](https://github.com/cockroachdb/cockroach/blob/263c6f976582d6e4c6afad4fb771b1741ac3b370/pkg/sql/opt_index_selection.go#L147)):*
> ```Go
> 			&p.semaCtx,
> 			p.EvalContext(),
> 			nil, // catalog should never be used
> ```

Why? Can we take the catalog argument out of `NewScalar`?

---

*[pkg/sql/opt/xform/expr.go, line 203 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-L6vljdlYCABsvqm43CF:-L6vljdlYCABsvqm43CG:b9aah9z) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b9a1a1025ba9e2ea2f7ce6d47fe25696b2e8754/pkg/sql/opt/xform/expr.go#L203)):*
> ```Go
> 		buf.WriteString(" [type=undefined]")
> 	} else {
> 		hasType := true
> ```

[nit] `showType` seems like it would be a more accurate name here

---

*[pkg/sql/opt/xform/factory.go, line 152 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-L6vrg_L3yXPmo4VwAob:-L6vrg_MwJSjbw-BYtaz:b-gvcn2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/263c6f976582d6e4c6afad4fb771b1741ac3b370/pkg/sql/opt/xform/factory.go#L152)):*
> ```Go
> 	n := 0
> 	for i := 0; i < int(list.Length); i++ {
> 		if n == 0 || ls.compare(i-1, i) < 0 {
> ```

[nit] I think this would be clearer if the condition was `if i==0 || ....`. Right now it looks like you could potentially do an array lookup with index -1.

---

*[pkg/sql/opt/xform/rules_test.go, line 69 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-L6vujGyLa1YRjNDejeM:-L6vujGyLa1YRjNDejeN:bq88dbw) ([raw file](https://github.com/cockroachdb/cockroach/blob/263c6f976582d6e4c6afad4fb771b1741ac3b370/pkg/sql/opt/xform/rules_test.go#L69)):*
> ```Go
> 		}
> 	}
> 	fn(opt.PlusOp)
> ```

Shouldn't you run this test with all binary operators? This list is obviously not exhaustive...

---

*[pkg/sql/opt/xform/rules/comp.opt, line 6 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-L6vvw-5P5GvxG3dsv46:-L6vvw-5P5GvxG3dsv47:bqhfwlw) ([raw file](https://github.com/cockroachdb/cockroach/blob/263c6f976582d6e4c6afad4fb771b1741ac3b370/pkg/sql/opt/xform/rules/comp.opt#L6)):*
> ```
> 
> 
> # CommuteVarInequality is similar to CommuteVar, except it handles inequality
> ```

Where is `CommuteVar`?

---

*[pkg/sql/opt/xform/rules/comp.opt, line 16 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-L6vwAhljSTHWXOwMTbZ:-L6vwAhljSTHWXOwMTb_:byczgcw) ([raw file](https://github.com/cockroachdb/cockroach/blob/263c6f976582d6e4c6afad4fb771b1741ac3b370/pkg/sql/opt/xform/rules/comp.opt#L16)):*
> ```
> (CommuteInequality (OpName) $left $right)
> 
> # CommuteConstInequality is similar to CommuteConst, except that it handles
> ```

Where is `CommuteConst`?

---

*[pkg/sql/opt/xform/rules/comp.opt, line 39 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-L6vwn3LGIvJIddKVGir:-L6vwn3LGIvJIddKVGis:bl7h508) ([raw file](https://github.com/cockroachdb/cockroach/blob/263c6f976582d6e4c6afad4fb771b1741ac3b370/pkg/sql/opt/xform/rules/comp.opt#L39)):*
> ```
> # necessary. Other patterns will fold new constant expressions further.
> [NormalizeCmpPlusConst]
> (Eq | Ge | Gt | Le | Lt
> ```

I think `Ne` works here too (and below)

---

*[pkg/sql/opt/xform/testdata/rules/comp, line 130 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-L6vzqcam599Z2QHmfgS:-L6vzqcam599Z2QHmfgT:bnqzpep) ([raw file](https://github.com/cockroachdb/cockroach/blob/263c6f976582d6e4c6afad4fb771b1741ac3b370/pkg/sql/opt/xform/testdata/rules/comp#L130)):*
> ```
>                 └── const: '01:00:00' [type=time]
> 
> # Try case that should not match pattern because Plus overload is not defined.
> ```

This is a duplicate of below. Did you mean to test `s::json + 1 = '[1]'::json` because `Minus` overload not defined?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-:-L6vqDyvI-eJYR61qU_H:b-q9kt5y)*

**Comment by andy-kimball** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/xform/factory.go, line 137 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-L6vpmIYTAfmQ1gk9fux:-L6w4A3vLlKKy4j7g7PP:b-4thh1e) ([raw file](https://github.com/cockroachdb/cockroach/blob/263c6f976582d6e4c6afad4fb771b1741ac3b370/pkg/sql/opt/xform/factory.go#L137)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The name doesn't suggest that duplicates are removed, I'm worried someone might see it in a rule and create a new rule that uses it without realizing this. Maybe `constructSortedDedupedSet`
</blockquote></details>

I thought `Set` would be enough, since sets have dups removed (as opposed to `constructSortedList`). But I'll rename to `constructSortedUniqueList` to be more explicit.

---

*[pkg/sql/opt/xform/factory.go, line 152 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-L6vrg_L3yXPmo4VwAob:-L6w4f4Gg3ZXgwzmiJ54:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/263c6f976582d6e4c6afad4fb771b1741ac3b370/pkg/sql/opt/xform/factory.go#L152)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] I think this would be clearer if the condition was `if i==0 || ....`. Right now it looks like you could potentially do an array lookup with index -1.
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/factory.go, line 415 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-L6vkbFkJ4HLyYPGB6GJ:-L6w4mGvjqe_WKXGZwE4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/263c6f976582d6e4c6afad4fb771b1741ac3b370/pkg/sql/opt/xform/factory.go#L415)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] an
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/logical_props.go, line 74 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-L6vkH0SMIDwajgUb54b:-L6w4rYcMXC4q2gDjG8x:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b9a1a1025ba9e2ea2f7ce6d47fe25696b2e8754/pkg/sql/opt/xform/logical_props.go#L74)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

they
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/rules_test.go, line 69 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-L6vujGyLa1YRjNDejeM:-L6w4t1UzYtVBZpN_jj5:b-l1pat5) ([raw file](https://github.com/cockroachdb/cockroach/blob/263c6f976582d6e4c6afad4fb771b1741ac3b370/pkg/sql/opt/xform/rules_test.go#L69)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Shouldn't you run this test with all binary operators? This list is obviously not exhaustive...
</blockquote></details>

Only for the commutative operators (e.g. Minus operands can't be switched). I'll add comment to that effect.

---

*[pkg/sql/opt/xform/typing.go, line 232 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-L6vn1MpCIGdSWilq06J:-L6w5RleonifJyMzpWhw:bdssw6c) ([raw file](https://github.com/cockroachdb/cockroach/blob/263c6f976582d6e4c6afad4fb771b1741ac3b370/pkg/sql/opt/xform/typing.go#L232)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Is it possible to have multiple overloads match?
</blockquote></details>

No. That assumption is tested in `TestTypingBinaryAssumptions`. I'll add comment here referring to that test.

---

*[pkg/sql/opt/xform/rules/comp.opt, line 6 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-L6vvw-5P5GvxG3dsv46:-L6w5qZR8ETYCuJ_8GHv:b-7u3w48) ([raw file](https://github.com/cockroachdb/cockroach/blob/263c6f976582d6e4c6afad4fb771b1741ac3b370/pkg/sql/opt/xform/rules/comp.opt#L6)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Where is `CommuteVar`?
</blockquote></details>

Added comment giving location (in scalar.opt).

---

*[pkg/sql/opt/xform/rules/comp.opt, line 16 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-L6vwAhljSTHWXOwMTbZ:-L6w5wXjCZwd2MRPVQAe:b-tu0hpa) ([raw file](https://github.com/cockroachdb/cockroach/blob/263c6f976582d6e4c6afad4fb771b1741ac3b370/pkg/sql/opt/xform/rules/comp.opt#L16)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Where is `CommuteConst`?
</blockquote></details>

Added comment giving location (in scalar.opt).

---

*[pkg/sql/opt/xform/rules/comp.opt, line 39 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-L6vwn3LGIvJIddKVGir:-L6w6G5lRyNc1YH5denz:b-7shgbz) ([raw file](https://github.com/cockroachdb/cockroach/blob/263c6f976582d6e4c6afad4fb771b1741ac3b370/pkg/sql/opt/xform/rules/comp.opt#L39)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I think `Ne` works here too (and below)
</blockquote></details>

I just ported over rules in `normalize.go`, which didn't include `Ne` (not sure why). We'd have to think deeply about it before we add new case. For example, what about Float special values (NaN, INF, -INF)? What about nulls? It probably all works, but I just want to make sure we've considered all the edge cases first.

---

*[pkg/sql/opt/xform/rules/numeric.opt, line 59 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-L6vn_hwqjLmZIA0pRgx:-L6w7DpSiGo-3rKxLIQ_:bzf90gw) ([raw file](https://github.com/cockroachdb/cockroach/blob/263c6f976582d6e4c6afad4fb771b1741ac3b370/pkg/sql/opt/xform/rules/numeric.opt#L59)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Doesn't decimal also have -0 ?
```
root@:26257/radu> SELECT * from b;
+---+
| k |
+---+
| 1 |
| 2 |
| 3 |
| 4 |
+---+
(4 rows)

Time: 2.376354ms

root@:26257/radu> SELECT -((k-1)/2) FROM b;
+----------------+
| -((k - 1) / 2) |
+----------------+
|             -0 |
|           -0.5 |
|             -1 |
|           -1.5 |
+----------------+
(4 rows)
```
</blockquote></details>

I'm following logic in `normalize.go`, which only excepts `Float`. But upon further reflection, I'm going to get rid of this rule altogether, and just let constant folding push the `-` down into the `Datum`. This rule is redundant with that logic (which is yet to be added to new optimizer).

---

*[pkg/sql/opt/xform/rules/scalar.opt, line 121 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-L6vqZaezSI1M7f56L0D:-L6wDGlqzqu_vTOkHkQx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/263c6f976582d6e4c6afad4fb771b1741ac3b370/pkg/sql/opt/xform/rules/scalar.opt#L121)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] maybe move the rule below NormalizeInConst which is referenced
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/testdata/rules/comp, line 130 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-L6vzqcam599Z2QHmfgS:-L6wIgq3h2CUCMVujyKZ:b4m6b7p) ([raw file](https://github.com/cockroachdb/cockroach/blob/263c6f976582d6e4c6afad4fb771b1741ac3b370/pkg/sql/opt/xform/testdata/rules/comp#L130)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This is a duplicate of below. Did you mean to test `s::json + 1 = '[1]'::json` because `Minus` overload not defined?
</blockquote></details>

Yes, was mistake. I switched it for case that tests right thing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439)*

**Comment by andy-kimball** [comment]
Perhaps not, though I think it should be the default to show everything we've got. Maybe we add flags to selectively remove props from output, which various tests could use if they wanted sparser output?

---

Review status: 52 of 62 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-:-L6wLSMix-NBQqOgOWpT:bwdcc2v)*

**Comment by andy-kimball** [comment]
Review status: 52 of 62 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt_index_selection.go, line 147 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-L6voYf3xcj0QUooKiq3:-L6wLmsndSc1laFcpg-C:b-ajjtj) ([raw file](https://github.com/cockroachdb/cockroach/blob/263c6f976582d6e4c6afad4fb771b1741ac3b370/pkg/sql/opt_index_selection.go#L147)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why? Can we take the catalog argument out of `NewScalar`?
</blockquote></details>

Yeah, I tested and found that we don't ever use it in this case, so I removed it.

---

*[pkg/sql/opt/xform/expr.go, line 203 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-L6vljdlYCABsvqm43CF:-L6wMpSnOfOrin_ftO26:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b9a1a1025ba9e2ea2f7ce6d47fe25696b2e8754/pkg/sql/opt/xform/expr.go#L203)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] `showType` seems like it would be a more accurate name here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439)*

**Comment by rytaft** [comment]
> Maybe we add flags to selectively remove props from output, which various tests could use if they wanted sparser output?

Sounds good to me.

---

Reviewed 16 of 16 files at r3, 41 of 41 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/xform/rules/comp.opt, line 39 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-L6vwn3LGIvJIddKVGir:-L6wa5UaEgsgQQvHDD27:b-6qtkiy) ([raw file](https://github.com/cockroachdb/cockroach/blob/263c6f976582d6e4c6afad4fb771b1741ac3b370/pkg/sql/opt/xform/rules/comp.opt#L39)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I just ported over rules in `normalize.go`, which didn't include `Ne` (not sure why). We'd have to think deeply about it before we add new case. For example, what about Float special values (NaN, INF, -INF)? What about nulls? It probably all works, but I just want to make sure we've considered all the edge cases first.
</blockquote></details>

Sounds good. Maybe add a comment to that effect so we don't forget?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-:-L6waoo9OrAO4z060BQU:b-qlbn0h)*

**Comment by andy-kimball** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/xform/rules/comp.opt, line 39 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439#-L6vwn3LGIvJIddKVGir:-L6wdcPzf6v5e4f8KRnI:b-of5zdz) ([raw file](https://github.com/cockroachdb/cockroach/blob/263c6f976582d6e4c6afad4fb771b1741ac3b370/pkg/sql/opt/xform/rules/comp.opt#L39)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Sounds good. Maybe add a comment to that effect so we don't forget?
</blockquote></details>

Yeah, I'll add that in my next PR, since I just got green build and want to merge this before there's another conflict. : )

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23439)*

**Pull request merged**
