### PR TITLE
sql: eliminate data race in test

### LINKED ISSUE #100774: kv: data race in sql/TestAmbiguousCommit
Likely on an unrelated PR (#100773) in this [run](https://teamcity.cockroachdb.com/viewLog.html?buildId=9460876&buildTypeId=Cockroach_BazelExtendedCi):
```
=== RUN   TestAmbiguousCommit/ambiguousSuccess=true
==================
WARNING: DATA RACE
Write at 0x00c000fd6008 by goroutine 60385:
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).SendWithWriteBytes.func1()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_send.go:130 +0x11b
  runtime.deferreturn()
      GOROOT/src/runtime/panic.go:476 +0x32
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).SendWithWriteBytes()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:203 +0x172
  github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal()
      github.com/cockroachdb/cockroach/pkg/server/node.go:1188 +0x712
  github.com/cockroachdb/cockroach/pkg/server.(*Node).Batch()
      github.com/cockroachdb/cockroach/pkg/server/node.go:1262 +0x275
  github.com/cockroachdb/cockroach/pkg/rpc.makeInternalClientAdapter.func1()
      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:835 +0x7c
  github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor.ServerInterceptor.func1()
      github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:96 +0x1d4
  github.com/cockroachdb/cockroach/pkg/rpc.bindUnaryServerInterceptorToHandler.func1()
      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:946 +0x8e
  github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func3()
      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:276 +0xf8
  github.com/cockroachdb/cockroach/pkg/rpc.bindUnaryServerInterceptorToHandler.func1()
      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:946 +0x8e
  github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor()
      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/auth.go:105 +0x322
  github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor-fm()
      <autogenerated>:1 +0xe6
  github.com/cockroachdb/cockroach/pkg/rpc.bindUnaryServerInterceptorToHandler.func1()
      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:946 +0x8e
  github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func1.1()
      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:243 +0x70
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:322 +0x147
  github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func1()
      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:241 +0x137
  github.com/cockroachdb/cockroach/pkg/rpc.bindUnaryServerInterceptorToHandler.func1()
      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:946 +0x8e
  github.com/cockroachdb/cockroach/pkg/rpc.makeInternalClientAdapter.func2()
      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:845 +0x81
  github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor.ClientInterceptor.func2()
      github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:227 +0x163
  github.com/cockroachdb/cockroach/pkg/rpc.getChainUnaryInvoker.func1()
      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:1030 +0x19c
  github.com/cockroachdb/cockroach/pkg/rpc.makeInternalClientAdapter.func3()
      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:915 +0x50d
  github.com/cockroachdb/cockroach/pkg/rpc.internalClientAdapter.Batch()
      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:1038 +0xf9
  github.com/cockroachdb/cockroach/pkg/rpc.(*internalClientAdapter).Batch()
      <autogenerated>:1 +0x33
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*grpcTransport).sendBatch()
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/transport.go:210 +0x1e6
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*grpcTransport).SendNext()
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/transport.go:189 +0x151
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.raceTransport.SendNext()
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/transport_race.go:76 +0x1a8
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*raceTransport).SendNext()
      <autogenerated>:1 +0x75
  github.com/cockroachdb/cockroach/pkg/sql_test.TestAmbiguousCommit.func1.2.1()
      github.com/cockroachdb/cockroach/pkg/sql_test/pkg/sql/ambiguous_commit_test.go:106 +0xac
  github.com/cockroachdb/cockroach/pkg/sql_test.(*interceptingTransport).SendNext()
      github.com/cockroachdb/cockroach/pkg/sql_test/pkg/sql/ambiguous_commit_test.go:50 +0x6a
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).sendToReplicas()
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:2153 +0x1ac6
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).sendPartialBatch()
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1679 +0xa44
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).divideAndSendBatchToRanges()
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1250 +0x592
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).divideAndSendParallelCommit()
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:976 +0x1178
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).Send()
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:869 +0xa3e
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnLockGatekeeper).SendLocked()
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_lock_gatekeeper.go:82 +0x229
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnMetricRecorder).SendLocked()
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_metric_recorder.go:47 +0x1ce
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnCommitter).SendLocked()
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go:203 +0x573
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).sendLockedWithRefreshAttempts()
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go:226 +0x335
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).SendLocked()
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go:154 +0x1e6
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnPipeliner).SendLocked()
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go:291 +0x245
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSeqNumAllocator).SendLocked()
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_seq_num_allocator.go:105 +0xd4
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnHeartbeater).SendLocked()
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go:246 +0x7cc
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*TxnCoordSender).Send()
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_coord_sender.go:529 +0x9b2
  github.com/cockroachdb/cockroach/pkg/kv.(*DB).sendUsingSender()
      github.com/cockroachdb/cockroach/pkg/kv/db.go:1001 +0x190
  github.com/cockroachdb/cockroach/pkg/kv.(*Txn).Send()
      github.com/cockroachdb/cockroach/pkg/kv/txn.go:1057 +0x334
  github.com/cockroachdb/cockroach/pkg/kv.(*Txn).Send-fm()
      <autogenerated>:1 +0x64
  github.com/cockroachdb/cockroach/pkg/kv.sendAndFill()
      github.com/cockroachdb/cockroach/pkg/kv/db.go:831 +0x252
  github.com/cockroachdb/cockroach/pkg/kv.(*Txn).Run()
      github.com/cockroachdb/cockroach/pkg/kv/txn.go:670 +0xa4
  github.com/cockroachdb/cockroach/pkg/kv.(*Txn).CommitInBatch()
      github.com/cockroachdb/cockroach/pkg/kv/txn.go:718 +0x469
  github.com/cockroachdb/cockroach/pkg/sql.(*tableWriterBase).finalize()
      github.com/cockroachdb/cockroach/pkg/sql/tablewriter.go:230 +0x22a
  github.com/cockroachdb/cockroach/pkg/sql.(*insertFastPathNode).BatchedNext()
      github.com/cockroachdb/cockroach/pkg/sql/insert_fast_path.go:314 +0x285
  github.com/cockroachdb/cockroach/pkg/sql.(*rowCountNode).startExec()
      github.com/cockroachdb/cockroach/pkg/sql/plan_batch.go:173 +0x199
  github.com/cockroachdb/cockroach/pkg/sql.startExec.func2()
      github.com/cockroachdb/cockroach/pkg/sql/plan.go:518 +0x186
  github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1()
      github.com/cockroachdb/cockroach/pkg/sql/walk.go:112 +0xa9
  runtime.deferreturn()
      GOROOT/src/runtime/panic.go:476 +0x32
  github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit()
      github.com/cockroachdb/cockroach/pkg/sql/walk.go:79 +0x135
  github.com/cockroachdb/cockroach/pkg/sql.walkPlan()
      github.com/cockroachdb/cockroach/pkg/sql/walk.go:43 +0x165
  github.com/cockroachdb/cockroach/pkg/sql.startExec()
      github.com/cockroachdb/cockroach/pkg/sql/plan.go:521 +0x180
  github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start()
      github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:174 +0x1e9
  github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Init()
      github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:183 +0x1c2
  github.com/cockroachdb/cockroach/pkg/sql/colexec.(*invariantsChecker).Init()
      github.com/cockroachdb/cockroach/pkg/sql/colexec/invariants_checker.go:67 +0xa3
  github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).init()
      github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:94 +0x72
  github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).init-fm()
      <autogenerated>:1 +0x39
  github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError()
      github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92 +0x75
  github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Init()
      github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:103 +0xd3
  github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedStatsCollectorImpl).Init()
      <autogenerated>:1 +0x4b
  github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).init.func1()
      github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:245 +0x6b
  github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError()
      github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92 +0x75
  github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).init()
      github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:244 +0x70
  github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run()
      github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:278 +0x158
  github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run()
      github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:317 +0x349
  github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run()
      github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:900 +0x1516
  github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun()
      github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1884 +0x2e7
  github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func2()
      github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1635 +0x144
  github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll()
      github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1638 +0x293
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1771 +0xe17
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1351 +0x1624
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:770 +0x3ebd
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:137 +0x18e
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2660 +0x50f
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:136 +0x6ed
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2118 +0x7e4
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2123 +0x1d64
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2039 +0x424
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2039 +0x424
  github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:867 +0x1be
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:738 +0x577

Previous read at 0x00c000fd6008 by goroutine 61251:
  reflect.Value.Int()
      GOROOT/src/reflect/value.go:1455 +0x7a9
  reflect.deepValueEqual()
      GOROOT/src/reflect/deepequal.go:160 +0x5ab
  reflect.deepValueEqual()
      GOROOT/src/reflect/deepequal.go:130 +0x1e9b
  reflect.deepValueEqual()
      GOROOT/src/reflect/deepequal.go:127 +0x1712
  reflect.DeepEqual()
      GOROOT/src/reflect/deepequal.go:237 +0x479
  github.com/cockroachdb/cockroach/pkg/sql_test.TestAmbiguousCommit.func1.2.1()
      github.com/cockroachdb/cockroach/pkg/sql_test/pkg/sql/ambiguous_commit_test.go:113 +0xe7
  github.com/cockroachdb/cockroach/pkg/sql_test.(*interceptingTransport).SendNext()
      github.com/cockroachdb/cockroach/pkg/sql_test/pkg/sql/ambiguous_commit_test.go:50 +0x6a
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).sendToReplicas()
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:2153 +0x1ac6
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).sendPartialBatch()
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1679 +0xa44
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).divideAndSendBatchToRanges()
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1250 +0x592
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).Send()
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:871 +0xa99
  github.com/cockroachdb/cockroach/pkg/kv.(*CrossRangeTxnWrapperSender).Send()
      github.com/cockroachdb/cockroach/pkg/kv/db.go:223 +0xfb
  github.com/cockroachdb/cockroach/pkg/internal/client/requestbatcher.(*RequestBatcher).sendBatch.func1.1()
      github.com/cockroachdb/cockroach/pkg/internal/client/requestbatcher/batcher.go:293 +0xfb
  github.com/cockroachdb/cockroach/pkg/util/contextutil.RunWithTimeout()
      github.com/cockroachdb/cockroach/pkg/util/contextutil/context.go:91 +0x142
  github.com/cockroachdb/cockroach/pkg/internal/client/requestbatcher.(*RequestBatcher).sendBatch.func1.2()
      github.com/cockroachdb/cockroach/pkg/internal/client/requestbatcher/batcher.go:310 +0xd3
  github.com/cockroachdb/cockroach/pkg/internal/client/requestbatcher.(*RequestBatcher).sendBatch.func1()
      github.com/cockroachdb/cockroach/pkg/internal/client/requestbatcher/batcher.go:332 +0x647
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470 +0x1f6

Goroutine 60385 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:651 +0x3c4
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:368 +0xd15
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveConn()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:177 +0x48c
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:782 +0xc0a
  github.com/cockroachdb/cockroach/pkg/server.(*systemServerWrapper).serveConn()
      github.com/cockroachdb/cockroach/pkg/server/server_controller_sql.go:93 +0x1fa
  github.com/cockroachdb/cockroach/pkg/server.(*serverController).sqlMux()
      github.com/cockroachdb/cockroach/pkg/server/server_controller_sql.go:73 +0x4fc
  github.com/cockroachdb/cockroach/pkg/server.(*serverController).sqlMux-fm()
      <autogenerated>:1 +0xc7
  github.com/cockroachdb/cockroach/pkg/server.startServeSQL.func1.1()
      github.com/cockroachdb/cockroach/pkg/server/server_sql.go:1745 +0x2eb
  github.com/cockroachdb/cockroach/pkg/util/netutil.(*TCPServer).ServeWith.func1()
      github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:188 +0x111
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470 +0x1f6

Goroutine 61251 (running) created at:
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:461 +0x619
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:332 +0x189
  github.com/cockroachdb/cockroach/pkg/internal/client/requestbatcher.(*RequestBatcher).sendBatch()
      github.com/cockroachdb/cockroach/pkg/internal/client/requestbatcher/batcher.go:286 +0x53
  github.com/cockroachdb/cockroach/pkg/internal/client/requestbatcher.(*RequestBatcher).run.func2()
      github.com/cockroachdb/cockroach/pkg/internal/client/requestbatcher/batcher.go:448 +0x5ea
  github.com/cockroachdb/cockroach/pkg/internal/client/requestbatcher.(*RequestBatcher).run()
      github.com/cockroachdb/cockroach/pkg/internal/client/requestbatcher/batcher.go:504 +0x560
  github.com/cockroachdb/cockroach/pkg/internal/client/requestbatcher.(*RequestBatcher).run-fm()
      <autogenerated>:1 +0x4d
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470 +0x1f6
==================
```
Tenantively marking as GA-blocker

Jira issue: CRDB-26613

### PR DESCRIPTION
**Pull request by andreimatei**
This test was injecting an error into requests, and then reading that error again. The store mutates the error slightly, so this was a data race. Instead, we now no longer share the error with the test harness.

Fixes #100774
Epic: None
Release note: test only

### CODE REVIEW

**Review by irfansharif — APPROVED** [review]
👋🏽

**Comment by alyshanjahani-crl** [comment]
👋

**Review by arulajmani — APPROVED** [review]
👋

**Review by nvb — APPROVED** [review]
LGTM

bors r+

**Pull request merged**
