### PR TITLE
release-21.2: sql: use soft and hard limits in lookup and index joins

### PR DESCRIPTION
**Pull request by yuzefovich**
Backport 1/1 commits from #78224.

/cc @cockroachdb/release

---

Previously, during the execution of lookup and index joins we completely
ignored the soft and hard limits and, instead, always fetched up to the
memory-based limit (which depends on the type of the join). This could
lead to having to read many more rows from the input and then looking up
many more rows from the KV layer than necessary.

This is now fixed by plumbing the soft and hard limits from the
optimizer and using them when sizing the batches of input rows to
perform lookup for. For index joins we know for sure that every input
row will get a looked up row; however, for lookup joins an input row
might result in a miss. To work around this we use a simple heuristic
for determining the limit-hint-based size of input batches: for the
first batch we use the limit hint as is, for the second batch we use 10x
of the original hint, and for the third and all consequent batches we
disable the limiting behavior altogether.

Fixes: #77715.

Release note (bug fix): CockroachDB might now fetch less rows when
performing lookup and index joins on the queries with LIMIT clause.

Release justification: low risk bug fix.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Note that it wasn't a clean backport, but the conflict were minor.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78474#-:-Myz8lfW6uhV8uRNg1GR:b-mhntl9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @rharding6373)

___
*[pkg/sql/colfetcher/index_join.go, line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78474#-Myz8rZi9FUntCJ6p4Ps:-Myz8rZi9FUntCJ6p4Pt:bqilk4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/5dfafd4545e5ab87fb81ea0c2d24be7c24d4e101/pkg/sql/colfetcher/index_join.go#L147)):*
> ```Go
> 				// reference to input tuples after span generation. So, we can discard
> 				// the input batch reference on each iteration.
> 				endIdx := s.findEndIndex(rowCount > 0)
> ```

Note that the change in this line is picking up the fix from d4840b32dfffb1233e551060b12e5295e37c3561 (backporting of which wasn't justified on its own).

**Review by cucaroach — APPROVED** [review]
:LGTM:

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78474#-:-Mz0C1Z86AZDiShbhge8:bmxilld)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rharding6373 and @yuzefovich)

___
*[pkg/sql/colfetcher/index_join.go, line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78474#-Myz8rZi9FUntCJ6p4Ps:-Mz0B0FP0aspb0fV7l9h:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5dfafd4545e5ab87fb81ea0c2d24be7c24d4e101/pkg/sql/colfetcher/index_join.go#L147)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Note that the change in this line is picking up the fix from d4840b32dfffb1233e551060b12e5295e37c3561 (backporting of which wasn't justified on its own).
</blockquote></details>

:+1: 
___
*[pkg/sql/execinfrapb/processors_sql.proto, line 426 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78474#-Mz0BTTA9zCJBu_CqopD:-Mz0BTTA9zCJBu_CqopE:bope1ls) ([raw file](https://github.com/cockroachdb/cockroach/blob/5dfafd4545e5ab87fb81ea0c2d24be7c24d4e101/pkg/sql/execinfrapb/processors_sql.proto#L426)):*
> ```protobuf
>   // Not used if there is a limit set in the PostProcessSpec of this processor
>   // (that value will be used for sizing batches instead).
>   optional int64 limit_hint = 21 [(gogoproto.nullable) = false];
> ```

Explain to me how this is upgrade safe again?   Since we're appending to the structure protobuf of new version binaries will always marshal this field but old version binaries in mixed version scenario will just unmarshal what they can and discard extra bytes at the end?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78474)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @rharding6373)

___
*[pkg/sql/execinfrapb/processors_sql.proto, line 426 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78474#-Mz0BTTA9zCJBu_CqopD:-Mz101hb-blULrCb_Mbn:bnn1xm3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5dfafd4545e5ab87fb81ea0c2d24be7c24d4e101/pkg/sql/execinfrapb/processors_sql.proto#L426)):*
> Since we're appending to the structure protobuf of new version binaries will always marshal this field but old version binaries in mixed version scenario will just unmarshal what they can and discard extra bytes at the end?

Yes, exactly. We cannot change the type of existing fields (so e.g. changing `lookup_batch_bytes_limit` to be `float64` is not backwards-compatible) nor can we reuse the existing "position" within the message (18 for `lookup_batch_bytes_limit`) for some other new meaning, but appending is backwards-compatible.

The usage of this limit hint is an optimization, and if the newer node creates the JoinReader spec with limit hint set, the older node upon receiving it will ignore the limit hint field, and the join reader on the older node will behave exactly as before (buffer up to memory-based limit in all cases). Thus, we didn't need to bump the DistSQL version.

**Review by rharding6373 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78474#-:-Mz1LVge7IzRi7kYNWqm:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @cucaroach)

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78474#-:-Mz1jjdmCv-Ksg4XCsSy:bnfp4nl)* status: :shipit: complete! 3 of 0 LGTMs obtained (waiting on @cucaroach)

**Pull request merged**
