### PR TITLE
sqlbase: correct keys per row calculation in RowFetcher

### LINKED ISSUE #13346: sql: RowFetcher batch limit calculation does not take into account column families
While investigating read performance on the `blocks` schema, I noticed that `ScanRequests` had an incorrectly set `MaxSpanRequestKeys` field. Given the table def:

```
	CREATE TABLE IF NOT EXISTS blocks (
	  block_id BIGINT NOT NULL,
	  writer_id STRING NOT NULL,
	  block_num BIGINT NOT NULL,
	  raw_bytes BYTES NOT NULL,
	  PRIMARY KEY (block_id, writer_id, block_num)
```

And the query:

```
SELECT writer_id, raw_bytes FROM blocks WHERE block_id >= $1 LIMIT 1
```

The `blocks` table has a single column family meaning there is a single key per row for the primary index. I would expect for this query that `MaxSpanRequestKeys` would be 1, but debug logs show it is set to 5. The code causing this is https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sqlbase/rowfetcher.go#L165-L178:

```
	firstBatchLimit := limitHint
	if firstBatchLimit != 0 {
		// For a secondary index, we have one key per row.
		if !rf.isSecondaryIndex {
			// We have a sentinel key per row plus at most one key per non-PK column. Of course, we
			// may have other keys due to a schema change, but this is only a hint.
			firstBatchLimit *= int64(1 + len(rf.cols) - len(rf.index.ColumnIDs))
		}
		// We need an extra key to make sure we form the last row.
		firstBatchLimit++
	}
```

For this query, `limitHint` is 2 (I'm not sure why it isn't one, but whatever). This is not a secondary index and there are 4 columns and 3 columns that are part of the index key. The math translates `(limitHint * (1 + 4 - 3)) + 1 == 5`. Seems like this math is not taking column families into account.

### PR DESCRIPTION
**Pull request by danhhz**
Looks like this got missed in the column families work.

Closes #13346.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13458)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm: thanks for fixing this!

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/sqlbase/structured.go, line 302 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13458#-KcOqoZHHzxev_GaC4i3:-KcOqoZHHzxev_GaC4i4:beg7e63) ([raw file](https://github.com/cockroachdb/cockroach/blob/95024a56a3b4419b867a0fd9d6ff8d62a1259d10/pkg/sql/sqlbase/structured.go#L302)):*
> ```Go
> func (desc *TableDescriptor) KeysPerRow(indexID IndexID) int {
> 	if desc.PrimaryIndex.ID == indexID {
> 		return len(desc.Families)
> ```

This doesn't work for old-school tables with no families right? (which have `#columns` + the sentinel key)
Just asking for my understanding, I think that's fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13458#-:-KcOrASd5m4Iwn4VPunh:b-3fkp1t)*

**Comment by danhhz** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/sqlbase/structured.go, line 302 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13458#-KcOqoZHHzxev_GaC4i3:-KcOr_g05yZaFgPmiXnm:b-eoaabg) ([raw file](https://github.com/cockroachdb/cockroach/blob/95024a56a3b4419b867a0fd9d6ff8d62a1259d10/pkg/sql/sqlbase/structured.go#L302)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This doesn't work for old-school tables with no families right? (which have `#columns` + the sentinel key)
Just asking for my understanding, I think that's fine.
</blockquote></details>

MaybeUpgradeFormatVersion is called on every TableDescriptor as soon as it's received from anywhere (kv, gossip, etc). For old tables, this backfills the families on the descriptor in such a way that they get encoded in the same way as before.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13458)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/sqlbase/structured.go, line 302 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13458#-KcOqoZHHzxev_GaC4i3:-KcP9ZZ8Yx1N82YIbwT1:b-83rsev) ([raw file](https://github.com/cockroachdb/cockroach/blob/95024a56a3b4419b867a0fd9d6ff8d62a1259d10/pkg/sql/sqlbase/structured.go#L302)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

MaybeUpgradeFormatVersion is called on every TableDescriptor as soon as it's received from anywhere (kv, gossip, etc). For old tables, this backfills the families on the descriptor in such a way that they get encoded in the same way as before.
</blockquote></details>

But how is the sentinel key accounted for? Is that a fake empty family?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13458)*

**Comment by danhhz** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/sqlbase/structured.go, line 302 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13458#-KcOqoZHHzxev_GaC4i3:-KcPA5HpIDAHk_Zgr4Dx:b2xxipv) ([raw file](https://github.com/cockroachdb/cockroach/blob/95024a56a3b4419b867a0fd9d6ff8d62a1259d10/pkg/sql/sqlbase/structured.go#L302)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

But how is the sentinel key accounted for? Is that a fake empty family?
</blockquote></details>

Yup. https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sqlbase/structured.go#L395-L397

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13458)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/sqlbase/structured.go, line 302 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13458#-KcOqoZHHzxev_GaC4i3:-KcPE5liFTc-x2fbuxzP:b-v6rzhl) ([raw file](https://github.com/cockroachdb/cockroach/blob/95024a56a3b4419b867a0fd9d6ff8d62a1259d10/pkg/sql/sqlbase/structured.go#L302)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Yup. https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sqlbase/structured.go#L395-L397
</blockquote></details>

Nice! Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13458)*

**Pull request merged**
