### PR TITLE
roachtest: check cluster version after resetting cluster

### LINKED ISSUE #112189: roachtest: backup-restore/mixed-version failed
roachtest.backup-restore/mixed-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12137026?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12137026?buildTab=artifacts#/backup-restore/mixed-version) on master @ [5af56c0ecd701d452c19fb89908012294b5336aa](https://github.com/cockroachdb/cockroach/commits/5af56c0ecd701d452c19fb89908012294b5336aa):

```
(test_runner.go:1108).runTest: test timed out (8h0m0s)
(mixedversion.go:545).Run: unexpected node event: n4: cockroach process for system interface died (exit code 137)
test artifacts and logs in: /artifacts/backup-restore/mixed-version/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-12137026/backup-restore-mixed-version/1697017169969/1697046119045)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #109976 roachtest: backup-restore/mixed-version failed [descriptor version conflict when RESTORE and 22.2 upgrade overlaps] [C-test-failure O-roachtest O-robot T-sql-foundations branch-release-22.2]
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backup-restore/mixed-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-32285

### PR DESCRIPTION
**Pull request by renatolabs**
This fixes the `backup-restore/mixed-version` test to perform cluster version checks _after_ the cluster has been potentially reset while verifying cluster backups. Previously, we were checking the version before, which could lead to wrongly using features that were not available yet.

Fixes: #112189.

Release note: None

### CODE REVIEW

**Comment by renatolabs** [comment]
Ran the test with the seed that caused the failure 3 times, and the test passed:

https://teamcity.cockroachdb.com/viewLog.html?buildId=12146061&buildTypeId=Cockroach_Nightlies_RoachtestNightlyGceBazel&tab=buildResultsDiv&branch_Cockroach_Nightlies=112193

**Review by DarrylWong — APPROVED** [review]
Just for my own understanding of what the bug is, was this only now an issue because of the recent switch from checking cluster versions instead of binary versions?

**Comment by renatolabs** [comment]
Good question! I'll try to provide a better picture of the situation:

Two PRs are relevant here: #111912 and #108372. In the former, there was a change in some of the mixedversion helpers to check cluster version instead of binary version, as you mention. In the former, the backup-restore/mixed-version roachtest was rearranged in order to reuse parts of its logic in a new test.

#108372 merged first, so I had to rebase #111912 and in the process of doing that, I had to change parts of the backup-restore/mixed-version test. Specifically, I had to change parts of the code that checked if certain features were available (such as the existence of the `crdb_internal.system_jobs` vtable, introduced in 23.1). While rebasing, I mistakenly added the cluster version check _before_ the cluster was reset with a (potentially older) version[^1]. This means that the cluster version could be "23.1", for example, by the time we made the check; but when the cluster is reset and started with an older version, that value will no longer correspond to the active cluster version. So the test would think the system_jobs vtable should exist, but it doesn't. The test keeps trying to query it until it times out, leading to the failure observed in #112189.

Hope that helps a little! Happy to talk more about this if you like to learn more, just ping me.


[^1]: A bit of context: the backup-restore/mixed-version test takes multiple backups in mixed-version state (when clusters are running a mix of V1 and V2), and will try to verify that these backups are restorable in a cluster running exclusively V1 or V2.

**Comment by renatolabs** [comment]
I'll wait for #112230 to be approved and merged before merging this, so that the backport of this PR goes through.

**Comment by DarrylWong** [comment]
Thank you! That makes perfect sense to me, I was just a little confused on why this wouldn't have been an issue before, but that clears it up wrt the rebase.

**Comment by renatolabs** [comment]
TFTR!

bors r=DarrylWong

**Pull request merged**
