### PR TITLE
sql: disallow AS OF SYSTEM TIME 0, add more AS OF tests

### LINKED ISSUE #17637: sql: lookup by DB prefix is broken
panic while executing "SHOW EXPERIMENTAL_FINGERPRINTS FROM TABLE ident AS OF SYSTEM TIME 0": interface conversion: interface {} is nil, not *log.ReportingSettings

https://teamcity.cockroachdb.com/viewLog.html?buildId=322791&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests

Assigning for triage.

Found with RSG.

### PR DESCRIPTION
**Pull request by knz**
Fixes #17637.

### CODE REVIEW

**Comment by mjibson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/as_of_test.go, line 159 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17680#-KrgP5NxsvD6K9HaklzJ:-KrgP5NxsvD6K9HaklzK:bv7og0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/9096600f877cf206bfb72199e3afce4217fe3677/pkg/sql/as_of_test.go#L159)):*
> ```Go
> 	// Ditto, as string.
> 	if _, err := db.Query("SELECT a FROM d.t AS OF SYSTEM TIME '1.12345678901'"); err == nil {
> 		t.Fatal("expected error")
> ```

testutils.IsError already tests for this, so these first if blocks are redundant.

---

*[pkg/sql/executor.go, line 2101 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17680#-KrgONlNsnEkewFyG4wQ:-KrgONlNsnEkewFyG4wR:b-13tp4s) ([raw file](https://github.com/cockroachdb/cockroach/blob/9096600f877cf206bfb72199e3afce4217fe3677/pkg/sql/executor.go#L2101)):*
> ```Go
> 		// Attempt to parse as a decimal.
> 		if dec, _, err := apd.NewFromString(s); err != nil {
> 			convErr = errors.Wrap(err, "AS OF SYSTEM TIME: value is not decimal")
> ```

This error could be misleading if a user was attempting to use a timestamp string. I think this final error during the string parsing should be something like "AS OF SYSTEM TIME: could not parse as timestamp or decimal".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17680)*

**Comment by knz** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/as_of_test.go, line 159 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17680#-KrgP5NxsvD6K9HaklzJ:-KrkAescCmuDCt3aWBNF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9096600f877cf206bfb72199e3afce4217fe3677/pkg/sql/as_of_test.go#L159)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

testutils.IsError already tests for this, so these first if blocks are redundant.
</blockquote></details>

Done.

---

*[pkg/sql/executor.go, line 2101 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17680#-KrgONlNsnEkewFyG4wQ:-KrkC8Wvq4q3ypZiPa4S:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9096600f877cf206bfb72199e3afce4217fe3677/pkg/sql/executor.go#L2101)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

This error could be misleading if a user was attempting to use a timestamp string. I think this final error during the string parsing should be something like "AS OF SYSTEM TIME: could not parse as timestamp or decimal".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17680)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/executor.go, line 2104 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17680#-KrlMmaQRwUUq9pcL0s_:-KrlMmaQRwUUq9pcL0sa:b-zbu1m8) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa3ad4091139c3f67d8b2d99455de64770fb21f4/pkg/sql/executor.go#L2104)):*
> ```Go
> 			// DECIMAL conversion error if a user was attempting to use a
> 			// timestamp string and the conversion above failed.
> 			convErr = errors.Errorf("AS OF SYSTEM TIME: value is neither interval nor decimal")
> ```

The word interval here isn't clear to me. Can we use "timestamp" instead? Or is there a better argument for interval?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17680#-:-KrlMy_yvNXYIeTOXXoc:bnfp4nl)*

**Comment by knz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/executor.go, line 2104 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17680#-KrlMmaQRwUUq9pcL0s_:-KsEjCd-WjkPsGuUQRmb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa3ad4091139c3f67d8b2d99455de64770fb21f4/pkg/sql/executor.go#L2104)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

The word interval here isn't clear to me. Can we use "timestamp" instead? Or is there a better argument for interval?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17680)*

**Comment by knz** [comment]
TFYR!

**Pull request merged**
