### PR TITLE
colexec: miscellaneous cleanups

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit:
- wraps some comments at 80 characters
- removes some unnecessary assignments to
`UseStreamingMemAccountForBuffering` test knob
- moves the decision which cache mode of the disk queue to use by the
external sorter into its constructor.

Release note: None

### CODE REVIEW

**Comment by asubiotto** [comment]
@cathymw leaving this review to you

**Comment by yuzefovich** [comment]
@cathymw friendly ping

**Review by cathymw — APPROVED** [review]
Oops, sorry I missed this earlier! 
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57833#-:-MP5XpQODruSvOx0v9Eb:b-i42oi2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @cathymw)

**Comment by yuzefovich** [comment]
No worries, TFTR!

bors r+

**Pull request merged**
