### PR TITLE
dev: don't hang after offline builds

### PR DESCRIPTION
**Pull request by dt**
Epic: none.

### CODE REVIEW

**Review by rickystewart — APPROVED** [review]
WFM

**Comment by dt** [comment]
Did a few informal tests from a two different ISPs and looks like we generally take >100ms to successfully upload, so bumping the limit to 400ms for now. That said, >100ms means it is within the realm of perceived-as-slow-by-human, so perhaps we should make a separate `dev upload-bep` command that calls this function, and then have these post-build calls instead exec `$0 upload-bep &` to fork a proc that can do the upload async after returning the prompt to the user, and then we can take as long as we want to do it since we're out of the user's way.

**Comment by dt** [comment]
For now I'll just bump the timeout here to 400ms and leave a TODO to fork.

**Review by rickystewart — APPROVED** [review]

**Comment by dt** [comment]
TFTR!

bors r+

**Pull request merged**
