### PR TITLE
Support parsing pgwire timestamps as they are sent by lib/pq

### LINKED ISSUE #5612: sql: pgwire timestamp parsing
[`cockroachdb/pq.formatTs`](https://github.com/cockroachdb/pq/blob/master/encode.go#L436) formats timestamps for the wire using `time.RFC3339Nano`. But [`cockroachdb/pq.ParseTimestamp`](https://github.com/cockroachdb/pq/blob/master/encode.go#L339) cannot parse such timestamps. We need to figure out why the discrepancy. Does postgres send back non-RFC3339 timestamps on the wire?

### PR DESCRIPTION
**Pull request by danhhz**
Closes #5612.

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5877)

### CODE REVIEW

**Comment by paperstreet** [comment]
After this lands, I'm going to revert https://github.com/cockroachdb/pq/commit/a7769c728fd100536f2f6c7c4661212250c78480 as it was the wrong fix and is unnecessary (sorry, I should have gotten the entire context before committing anything).

**Comment by dt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/pgwire/types.go, line 255 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5877#-KEbxSP1TUKxI99TR8U5:-KEbxSP1TUKxI99TR8U6:-2064408560) ([raw file](https://github.com/cockroachdb/cockroach/blob/4213440ac47d357f8c539e1ebe786754adc45c76/sql/pgwire/types.go#L255)):*
Is this exercised by any tests currently?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5877)*

**Comment by paperstreet** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/pgwire/types.go, line 255 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5877#-KEbxSP1TUKxI99TR8U5:-KEbyoe_RasH3ZeAFBCq:1759777494) ([raw file](https://github.com/cockroachdb/cockroach/blob/4213440ac47d357f8c539e1ebe786754adc45c76/sql/pgwire/types.go#L255)):*
Nope, could be dead code for all I know. I was just keeping it because it allows roundtripping the timestamp bytes that CockroachDB sends back. I could add a test for the round trip though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5877)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/pgwire/types_test.go, line 26 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5877#-KEc2nC0imLCulVc_SgQ:-KEc2nC0imLCulVc_SgR:-1672672956) ([raw file](https://github.com/cockroachdb/cockroach/blob/4213440ac47d357f8c539e1ebe786754adc45c76/sql/pgwire/types_test.go#L26)):*
You can define this variable inside of `TestParseTs`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5877)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/pgwire/types_test.go, line 31 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5877#-KEc2vpBBmbNbxVe-dl7:-KEc2vpBBmbNbxVe-dl8:-1526184681) ([raw file](https://github.com/cockroachdb/cockroach/blob/4213440ac47d357f8c539e1ebe786754adc45c76/sql/pgwire/types_test.go#L31)):*
Add a test for the format accepted by `pq.ParseTimestamp`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5877)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5877#-:-KEc5ikT2rOTS2YtPjI1:1417088721)*

**Comment by paperstreet** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[sql/pgwire/types_test.go, line 26 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5877#-KEc2nC0imLCulVc_SgQ:-KEc8VaBGD2594U6DDa0:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4213440ac47d357f8c539e1ebe786754adc45c76/sql/pgwire/types_test.go#L26)):*
Done.

---

*[sql/pgwire/types_test.go, line 31 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5877#-KEc2vpBBmbNbxVe-dl7:-KEc8W0-YCGOjNKrHMtQ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4213440ac47d357f8c539e1ebe786754adc45c76/sql/pgwire/types_test.go#L31)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5877)*

**Pull request merged**
