### PR TITLE
go.mod: bump Pebble to d228f9df98d5

### PR DESCRIPTION
**Pull request by jbowens**
```
d228f9df db: add CanDeterministicallySingleDelete
407f8606 db: enforce no split user keys in CheckOrdering
56834cba db: more invariant checking for InternalKeyKind in compactionIter
2a2be74d db: remove compaction iter seqnum optimization, replace with assert
b9be64b8 db: fix newly-introduced SINGLEDEL+DELSIZED bug
717d49c2 db: extend compaction iterator comments, tests
bfb2e6a9 objstorage/objstorageprovider: save custom object name to catalog
292562ca skip size check for External files
dee1494f tool/lsm: note virtualness in text description
fc7802da compaction: return correct error if copy/move compaction is cancelled
ec76d8bf tool/lsm: init provider backing for decoded version edits
038559ea scan_internal: Sort keys by kind before calling visitor
d785f14c ingest: don't call checkVirtualBounds() in ingestion
c87a2a7c *: set hideObsoletePoints=true for shared foreign sstables
3131a57a tool/lsm: color virtual files differently
```

Epic: none
Release note: none

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114838#-:-NjnRE-a7dYOyOKz8VvO:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Comment by jbowens** [comment]
TFTR!

bors r=sumeerbhola

**Comment by jbowens** [comment]
Brutal. The unit tests CI job didn't start until 40m in and then got canceled?

> Canceled:
> Build agent shutdown

**Comment by jbowens** [comment]
bors retry

**Pull request merged**
