### PR TITLE
kvserver: don't return lease when failing to acquire

### LINKED ISSUE #81787: kvserver: don't return lease when failing to acquire
kvserver should not return the previous, expired lease when a replica fails to acquire it for itself. In particular, this would prevent the calling DistSender from continually retrying the old leaseholder if it fails to reacquire the lease (e.g. due to a stalled disk).

### PR DESCRIPTION
**Pull request by erikgrinaker**
**kvserver: improve lease acquisition in `Store.ManuallyEnqueue()`**

Manually enqueuing a range through a queue may sometimes require
acquiring the lease first, since it can only be run on the leaseholder.
Previously this was done through `getLeaseForGossip`, which was meant
for acquiring the gossip lease and would hide certain errors from the
queue.

This patch instead uses `redirectOnOrAcquireLease` to acquire the lease,
and returns an error if the local replica failed to acquire the lease
(even if there is a valid leaseholder elsewhere).

Release note: None

**kvserver: don't return lease when failing to acquire**

This patch does not return the previous, expired lease when a replica
fails to acquire it for itself. In particular, this prevents the calling
DistSender from continually retrying the old leaseholder if it fails to
reacquire the lease (e.g. due to a stalled disk).

Touches #81100.

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
Nice find!

It looks like `TestLeasesDontThrashWhenNodeBecomesSuspect` is now failing. Is that expected/desired? Is there another test we could write to demonstrate the effect this will have on DistSender (i.e., that it won't retry the old leaseholder).

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81134#-:-N1dS7jx5eVs-9tKBB_l:bsebmo4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

**Review by tbg — APPROVED** [review]

**Review by erikgrinaker — COMMENTED** [review]
>It looks like `TestLeasesDontThrashWhenNodeBecomesSuspect` is now failing. Is that expected/desired?

This was a combination of `Store.ManuallyEnqueue` masking lease acquisition errors, and the test attempting (and failing) to enqueue non-leaseholder replicas. Added a commit to fix this, but it could break a few tests that rely on these errors being dropped, so let's see what CI says.

Also, this will likely make gossip lease acquisition failures a bit more noisy -- in particular with `ErrEpochAlreadyIncremented`. But I think that's probably ok.

>Is there another test we could write to demonstrate the effect this will have on DistSender (i.e., that it won't retry the old leaseholder).

I was thinking we'd add a roachtest for disk stalls, which would test this by extension. However, it doesn't seem likely that we can make that reliable in the short term, so I'll have a look at a something more targeted.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81134#-:-N1stHxA3t5F6wRP37-C:b-3g7pzt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

**Review by erikgrinaker — COMMENTED** [review]
Added a DistSender test that ensures it does not retry the same replica with backoff if the NLHE has no lease information.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81134#-:-N1tIoVV69h8HI6iLuP1:b-enofxb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @nvanbenschoten)

**Comment by erikgrinaker** [comment]
Verified that the DB Console enqueue range functionality still worked as expected here. TFTRs!

bors r=nvanbenschoten,tbg

**Comment by erikgrinaker** [comment]
bors retry

**Pull request merged**
