### PR TITLE
stats: invalidate table statistic caches through gossip

### LINKED ISSUE #24585: stats: cache invalidation mechanism
The stats cache needs an invalidation mechanism. We can use gosip for this - we can gossip a special key whenever a new statistic is available.

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change makes the TableStatisticsCache stay up-to-date
automatically: whenever we compute a stat, we gossip a "table stat
added" key for that table, which triggers an invalidation in the
cache.

In the current form, this will add a key per table when we enable
statistics automatically. A possible improvement would be to set a TTL
on these keys and change the cache to always invalidate very old
entries automatically.

Fixes #24585.

Release note: None

### CODE REVIEW

**Comment by rytaft** [comment]
:lgtm: Nice!

---

Reviewed 8 of 8 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/sql/distsqlrun/sample_aggregator.go, line 271 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24605#-L9gJV0D41EsJ8dIQEyB:-L9gJV0D41EsJ8dIQEyC:b-l2hviu) ([raw file](https://github.com/cockroachdb/cockroach/blob/533eb17a3afb6671dee0013ed09cc3539c4f80db/pkg/sql/distsqlrun/sample_aggregator.go#L271)):*
> ```Go
> 	}
> 
> 	// TODO(radu): perhaps use a TTL here to avoid having a key per table floating
> ```

This comment is a little cryptic - can you give a little more context? (e.g., what's a TTL and why would the stat cache need to evict old entries automatically?)

---

*[pkg/sql/stats/stats_cache.go, line 137 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24605#-L9gKqsm5EnL5jMzHglb:-L9gKqsm5EnL5jMzHglc:b-a7n9u3) ([raw file](https://github.com/cockroachdb/cockroach/blob/533eb17a3afb6671dee0013ed09cc3539c4f80db/pkg/sql/stats/stats_cache.go#L137)):*
> ```Go
> 	trimmedKey, err := gossip.RemovePrefixFromKey(key, gossip.KeyTableStatAddedPrefix)
> 	if err == nil {
> 		tableID, err = strconv.ParseInt(trimmedKey, 10, 64)
> ```

what are 10 and 64? Can you add a comment?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24605#-:-L9gLlKhB3FD4cmx10F0:b-8gk8uj)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/sample_aggregator.go, line 271 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24605#-L9gJV0D41EsJ8dIQEyB:-L9gQ-FfAlL254W-8zqb:b-yhj979) ([raw file](https://github.com/cockroachdb/cockroach/blob/533eb17a3afb6671dee0013ed09cc3539c4f80db/pkg/sql/distsqlrun/sample_aggregator.go#L271)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This comment is a little cryptic - can you give a little more context? (e.g., what's a TTL and why would the stat cache need to evict old entries automatically?)
</blockquote></details>

TTL = time to live (last argument to AddInfo). It makes gossip keys expire. We would need to evict old entries because we could be isolated from the cluster for an arbitrary period of time, and keys would have expired by the time we come back so we won't notice them.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24605)*

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Reviewed 7 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/stats/gossip_invalidation_test.go, line 72 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24605#-L9gOxDi6CazCwaN2jTR:-L9gOxDi6CazCwaN2jTS:b38eb0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/533eb17a3afb6671dee0013ed09cc3539c4f80db/pkg/sql/stats/gossip_invalidation_test.go#L72)):*
> ```Go
> 	}
> 	sr1 := sqlutils.MakeSQLRunner(tc.ServerConn(1))
> 	sr1.Exec(t, "CREATE STATISTICS k ON k FROM test.t")
> ```

Not related to this review, but can you have multiple statistics on a single table?

---

*[pkg/sql/stats/stats_cache.go, line 137 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24605#-L9gKqsm5EnL5jMzHglb:-L9gPELSESqsccxbbdKc:b7foflp) ([raw file](https://github.com/cockroachdb/cockroach/blob/533eb17a3afb6671dee0013ed09cc3539c4f80db/pkg/sql/stats/stats_cache.go#L137)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

what are 10 and 64? Can you add a comment?
</blockquote></details>

They're the desired base and bitSize. This is from the [stdlib](https://golang.org/pkg/strconv/#ParseInt) so I'm fine either way with respect to adding a comment.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24605#-:-L9gQGWG6rJdI9QbfOWZ:bnfp4nl)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/stats/gossip_invalidation_test.go, line 72 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24605#-L9gOxDi6CazCwaN2jTR:-L9gXbiw0dMe_grrk7IX:b-zatl4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/533eb17a3afb6671dee0013ed09cc3539c4f80db/pkg/sql/stats/gossip_invalidation_test.go#L72)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Yep - each statistic is on a subset of columns.
</blockquote></details>

Ah ok, that's neat!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24605)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/gossip/keys.go, line 168 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24605#-L9jnhio1cWFQl2IvkjH:-L9jnhio1cWFQl2IvkjI:b-n42z6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/533eb17a3afb6671dee0013ed09cc3539c4f80db/pkg/gossip/keys.go#L168)):*
> ```Go
> // MakeKeyTableStatAddedKey returns the gossip key used to notify that a new
> // statistic is available for the given table.
> func MakeKeyTableStatAddedKey(tableID string) string {
> ```

I realize that we can't use the `TableID` typedef here, but for consistency with the `keys` package, I'd pass `tableID uint32`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24605#-:-L9jnzk94-ssl_osOftO:bnfp4nl)*

**Comment by RaduBerinde** [comment]
I added a commit that moves the code to insert a new stat and do the gossip notification into `stats`.

---

Review status: 5 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/gossip/keys.go, line 168 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24605#-L9jnhio1cWFQl2IvkjH:-L9jxQffEh7qRy52dxwE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/533eb17a3afb6671dee0013ed09cc3539c4f80db/pkg/gossip/keys.go#L168)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I realize that we can't use the `TableID` typedef here, but for consistency with the `keys` package, I'd pass `tableID uint32`.
</blockquote></details>

Done.

---

*[pkg/sql/stats/stats_cache.go, line 137 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24605#-L9gKqsm5EnL5jMzHglb:-L9jxRen3FeiR0vpDSDH:b-kg163c) ([raw file](https://github.com/cockroachdb/cockroach/blob/533eb17a3afb6671dee0013ed09cc3539c4f80db/pkg/sql/stats/stats_cache.go#L137)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

They're the desired base and bitSize. This is from the [stdlib](https://golang.org/pkg/strconv/#ParseInt) so I'm fine either way with respect to adding a comment.
</blockquote></details>

Done (code is now in gossip/keys.go)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24605#-:-L9k2HqeEzx-geWTdAkB:bfvt6vy)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24605#-:-L9kTOkD6fvwj7wnES7p:bnfp4nl)*

**Comment by RaduBerinde** [comment]
bors r+

:pray: :pray: :prayer_beads:

**Pull request merged**
