### PR TITLE
opt: index constraints for LIKE and SIMILAR TO

### LINKED ISSUE #21831: sql: index constraints no longer working for LIKE 'string%'
v2.0-alpha.20180116-650-gaf29319fc:

```
> create table d.t (s string primary key);
CREATE TABLE

Time: 29.1546ms

root@:26257/> explain select * from d.t where s like 'test%';
+------+-------+-------------+
| Tree | Field | Description |
+------+-------+-------------+
| scan |       |             |
|      | table | t@primary   |
|      | spans | ALL         |
+------+-------+-------------+
```

v2.0-alpha.20171218:

```
>  create table d.t (s string primary key);
CREATE TABLE

Time: 53.351523ms

root@:26257/>  explain select * from d.t where s like 'test%';
+-------+------+-------+-----------------+
| Level | Type | Field |   Description   |
+-------+------+-------+-----------------+
|     0 | scan |       |                 |
|     0 |      | table | t@primary       |
|     0 |      | spans | /"test"-/"tesu" |
+-------+------+-------+-----------------+
```

This broke a query I was running (time went from ~ms to +30s).

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: index constraints for LIKE and SIMILAR TO

The old index constraints code supported these; implementing them was
an omission.

Fixes #21831.

Release note: None

#### opt: fall back to not-NULL constraints

Improving the index selection code to at least generate a not-NULL
constraint when we can't create any other constraints on a column.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/logictest/testdata/logic_test/select_index, line 954 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21842#-L3sRWV6ruXUBw4DhGiC:-L3sRWV6ruXUBw4DhGiD:bi63gzc) ([raw file](https://github.com/cockroachdb/cockroach/blob/665731964d575d68e5ddacfa9cf624fd12ebf6ec/pkg/sql/logictest/testdata/logic_test/select_index#L954)):*
> ```
> 
> query IT rowsort
> SELECT k, v FROM str WHERE v SIMILAR TO 'ABC%'
> ```

Was this supposed to e `ABC.*`? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21842#-:-L3sSN-jYBABpRrH45iU:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/logictest/testdata/logic_test/select_index, line 954 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21842#-L3sRWV6ruXUBw4DhGiC:-L3slFJnHQD2XoCkJRwn:b-5l531s) ([raw file](https://github.com/cockroachdb/cockroach/blob/665731964d575d68e5ddacfa9cf624fd12ebf6ec/pkg/sql/logictest/testdata/logic_test/select_index#L954)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Was this supposed to e `ABC.*`? 
</blockquote></details>

Haha yes, but apparently that's wrong. `.` is not a special character for `SIMILAR TO`. Changed to `_*`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21842)*

**Comment by petermattis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/opt/testdata/index-constraints, line 1213 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21842#-L3stBaxzkUwXtxjE5hq:-L3stBaxzkUwXtxjE5hr:b-gpy6e2) ([raw file](https://github.com/cockroachdb/cockroach/blob/018846c18faed722c4c26e04ed0ba68943c7c2f6/pkg/sql/opt/testdata/index-constraints#L1213)):*
> ```
> @1 SIMILAR TO 'ABC'
> ----
> [/'ABC' - /'ABC']
> ```

Can you also add a test case for `@1 SIMILAR TO '(ABC|ABCDEF)%'? This is really testing the literal prefix code, but it is also verifying that we're calling that code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21842)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/testdata/index-constraints, line 1213 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21842#-L3stBaxzkUwXtxjE5hq:-L3sutUy4Zyxzzqtq8Mj:b-fznogt) ([raw file](https://github.com/cockroachdb/cockroach/blob/018846c18faed722c4c26e04ed0ba68943c7c2f6/pkg/sql/opt/testdata/index-constraints#L1213)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Can you also add a test case for `@1 SIMILAR TO '(ABC|ABCDEF)%'? This is really testing the literal prefix code, but it is also verifying that we're calling that code.
</blockquote></details>

Good idea, done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21842)*

**Pull request merged**
