### PR TITLE
Revert "kv,migration: rm code handling legacy raft truncated state"

### LINKED ISSUE #70244: roachtest: import/mixed-versions failed [should stop after beta1 out]
roachtest.import/mixed-versions [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3445998&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3445998&tab=artifacts#/import/mixed-versions) on master @ [2baefd353239ddc4e7f4299b8930001675b99aa9](https://github.com/cockroachdb/cockroach/commits/2baefd353239ddc4e7f4299b8930001675b99aa9):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/import/mixed-versions/run_1
	cluster.go:1253,context.go:89,cluster.go:1241,test_runner.go:866: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-3445998-1631686180-11-n4cpu4 --oneshot --ignore-empty-nodes: exit status 1 1: 13426
		4: dead (exit status 7)
		2: 13255
		3: 12469
		Error: UNCLASSIFIED_PROBLEM: 4: dead (exit status 7)
		(1) UNCLASSIFIED_PROBLEM
		Wraps: (2) attached stack trace
		  -- stack trace:
		  | main.glob..func14
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1173
		  | main.wrap.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:281
		  | github.com/spf13/cobra.(*Command).execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:856
		  | github.com/spf13/cobra.(*Command).ExecuteC
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:960
		  | github.com/spf13/cobra.(*Command).Execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:897
		  | main.main
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:2107
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:225
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1371
		Wraps: (3) 4: dead (exit status 7)
		Error types: (1) errors.Unclassified (2) *withstack.withStack (3) *errutil.leafError
```
<details><summary>Reproduce</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

</p>
</details>
/cc @cockroachdb/bulk-io
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*import/mixed-versions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #70252: roachtest: version/mixed/nodes=5 failed [should stop after beta1]
roachtest.version/mixed/nodes=5 [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3445998&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3445998&tab=artifacts#/version/mixed/nodes=5) on master @ [2baefd353239ddc4e7f4299b8930001675b99aa9](https://github.com/cockroachdb/cockroach/commits/2baefd353239ddc4e7f4299b8930001675b99aa9):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/version/mixed/nodes=5/run_1
	monitor.go:128,version.go:211,version.go:224,test_runner.go:777: monitor failure: unexpected node event: 3: dead (exit status 7)
		(1) attached stack trace
		  -- stack trace:
		  | main.(*monitorImpl).WaitE
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/monitor.go:116
		  | main.(*monitorImpl).Wait
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/monitor.go:124
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerVersion.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/version.go:211
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerVersion.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/version.go:224
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:777
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1371
		Wraps: (2) monitor failure
		Wraps: (3) unexpected node event: 3: dead (exit status 7)
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *errors.errorString

	cluster.go:1253,context.go:89,cluster.go:1241,test_runner.go:866: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-3445998-1631686180-39-n6cpu4 --oneshot --ignore-empty-nodes: exit status 1 1: 25637
		3: dead (exit status 7)
		2: 24163
		6: skipped
		4: 21358
		5: 21692
		Error: UNCLASSIFIED_PROBLEM: 3: dead (exit status 7)
		(1) UNCLASSIFIED_PROBLEM
		Wraps: (2) attached stack trace
		  -- stack trace:
		  | main.glob..func14
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1173
		  | main.wrap.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:281
		  | github.com/spf13/cobra.(*Command).execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:856
		  | github.com/spf13/cobra.(*Command).ExecuteC
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:960
		  | github.com/spf13/cobra.(*Command).Execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:897
		  | main.main
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:2107
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:225
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1371
		Wraps: (3) 3: dead (exit status 7)
		Error types: (1) errors.Unclassified (2) *withstack.withStack (3) *errutil.leafError
```
<details><summary>Reproduce</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*version/mixed/nodes=5.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #70253: roachtest: schemachange/secondary-index-multi-version failed [should stop after beta1]
roachtest.schemachange/secondary-index-multi-version [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3445998&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3445998&tab=artifacts#/schemachange/secondary-index-multi-version) on master @ [2baefd353239ddc4e7f4299b8930001675b99aa9](https://github.com/cockroachdb/cockroach/commits/2baefd353239ddc4e7f4299b8930001675b99aa9):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/schemachange/secondary-index-multi-version/run_1
	secondary_indexes.go:123,versionupgrade.go:213,secondary_indexes.go:87,secondary_indexes.go:147,test_runner.go:777: dial tcp 34.139.60.15:26257: connect: connection refused

	cluster.go:1253,context.go:89,cluster.go:1241,test_runner.go:866: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-3445998-1631686180-75-n3cpu4 --oneshot --ignore-empty-nodes: exit status 1 1: 11978
		2: dead (exit status 7)
		3: 11149
		Error: UNCLASSIFIED_PROBLEM: 2: dead (exit status 7)
		(1) UNCLASSIFIED_PROBLEM
		Wraps: (2) attached stack trace
		  -- stack trace:
		  | main.glob..func14
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1173
		  | main.wrap.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:281
		  | github.com/spf13/cobra.(*Command).execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:856
		  | github.com/spf13/cobra.(*Command).ExecuteC
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:960
		  | github.com/spf13/cobra.(*Command).Execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:897
		  | main.main
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:2107
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:225
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1371
		Wraps: (3) 2: dead (exit status 7)
		Error types: (1) errors.Unclassified (2) *withstack.withStack (3) *errutil.leafError
```
<details><summary>Reproduce</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #63954 roachtest: schemachange/secondary-index-multi-version failed [C-test-failure O-roachtest O-robot T-sql-schema branch-release-20.2]
</p>
</details>
/cc @cockroachdb/sql-schema
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*schemachange/secondary-index-multi-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #70283: roachtest: schemachange/database-version-upgrade failed [should stop after beta1]
roachtest.schemachange/database-version-upgrade [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3445998&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3445998&tab=artifacts#/schemachange/database-version-upgrade) on master @ [2baefd353239ddc4e7f4299b8930001675b99aa9](https://github.com/cockroachdb/cockroach/commits/2baefd353239ddc4e7f4299b8930001675b99aa9):

```
The test failed on branch=master, cloud=gce:
test timed out (see artifacts for details)
```
<details><summary>Reproduce</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

</p>
</details>
/cc @cockroachdb/sql-schema
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*schemachange/database-version-upgrade.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #70350: roachtest: follower-reads/mixed-version/single-region failed [should stop after beta1]
roachtest.follower-reads/mixed-version/single-region [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3457472&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3457472&tab=artifacts#/follower-reads/mixed-version/single-region) on master @ [1f0dfa35126af18c678226a77e1848ca489a1bb2](https://github.com/cockroachdb/cockroach/commits/1f0dfa35126af18c678226a77e1848ca489a1bb2):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/follower-reads/mixed-version/single-region/run_1
	follower_reads.go:244,follower_reads.go:778,follower_reads.go:81,test_runner.go:777: failed to get follower read counts: Get "http://34.75.225.57:26258/_status/vars": dial tcp 34.75.225.57:26258: connect: connection refused

	cluster.go:1253,context.go:89,cluster.go:1241,test_runner.go:866: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-3457472-1631859726-44-n3cpu2 --oneshot --ignore-empty-nodes: exit status 1 3: 11882
		2: dead (exit status 7)
		1: 12545
		Error: UNCLASSIFIED_PROBLEM: 2: dead (exit status 7)
		(1) UNCLASSIFIED_PROBLEM
		Wraps: (2) attached stack trace
		  -- stack trace:
		  | main.glob..func14
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1173
		  | main.wrap.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:281
		  | github.com/spf13/cobra.(*Command).execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:856
		  | github.com/spf13/cobra.(*Command).ExecuteC
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:960
		  | github.com/spf13/cobra.(*Command).Execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:897
		  | main.main
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:2107
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:225
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1371
		Wraps: (3) 2: dead (exit status 7)
		Error types: (1) errors.Unclassified (2) *withstack.withStack (3) *errutil.leafError
```
<details><summary>Reproduce</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*follower-reads/mixed-version/single-region.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #70390: roachtest: decommission/mixed-versions failed [should stop after beta1]
roachtest.decommission/mixed-versions [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3462983&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3462983&tab=artifacts#/decommission/mixed-versions) on master @ [78c6771c7e9f7ba6431f44b067f27e0857341374](https://github.com/cockroachdb/cockroach/commits/78c6771c7e9f7ba6431f44b067f27e0857341374):

```
The test failed on branch=master, cloud=gce:
test timed out (see artifacts for details)
```
<details><summary>Reproduce</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*decommission/mixed-versions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by irfansharif**
This reverts commit 6464de2569efeee6c9d0bbbe7bb5be476da0cf03. That PR
broke few of our roachtests since we haven't release the 21.2 beta yet.
For our roachtests that exercised the upgrade path, we were effectively
upgrading from 21.1 to 22.1 code (as of that PR) that asserted on the
completion of the long running migration removing the legacy raft
truncated state -- something that would only happen when going through
21.2. Given that, we temporarily revert #69887 while our beta gets
prepared. #69887 (or rather, the revert of _this_ commit) will be
re-introduced to master once #69826 lands.

Fixes #70244.
Fixes #70252.
Fixes #70253.
Fixes #70283.
Fixes #70350.
Fixes #70390.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
LGTM

Clean revert? I didn't look much at the diff under that assumption. If anything required manual changes please let me know and I'll give those parts a closer look.

Also, looking forward to reverting the revert. :-)

**Comment by irfansharif** [comment]
Yup, save for some code movements around cockroach_versions.go. Can I get a green stamp pls?

**Review by ajwerner — APPROVED** [review]
Stamped on green assuming it's just mechanical.

**Comment by irfansharif** [comment]
Thanks! My stringer for the version keys hadn't gone through correctly -- will wait for green CI.

**Comment by irfansharif** [comment]
Flaked on https://github.com/cockroachdb/cockroach/issues/69281.

bors r+

**Pull request merged**
