### PR TITLE
kvstreamer: remove temporary allocations for []Result

### PR DESCRIPTION
**Pull request by yuzefovich**
**kvstreamer: refactor the loop of processing the batch response**

This commit refactors the code which processes the batch response in
order to separate out two different concerns:
- processing non-empty responses in order to create `Result`s
- processing incomplete responses to populate the resume request.

Now each of these "concerns" is handled in a separate loop making it
easier to reason about, especially so in the following commit.

This commit also extracts out multiple return arguments of a function
into a struct as well as updates some of the comments and moves some of
the error-checking to an earlier stage.

Release note: None

**kvstreamer: remove temporary allocations for []Result**

Previously, the worker goroutine would accumulate all `Result`s it
can create based on the KV response into a slice, and then the
slice would be passed into the results buffer. At that point, the
slice would be discarded since the results buffer would copy all
`Result`s into its internal state.

This commit refactors the streamer as well as the results buffer to
avoid this temporary allocation of `[]Result`. The main idea is that
`Result`s are now passed one-by-one into the results buffer. The worker
goroutine now acquires the results buffer's mutex, processes the KV
responses one at a time, and whenever a `Result` is created, it is added
into the results buffer right away. However, in order to prevent the
results buffer from eagerly returning a single `Result` on `GetResults`
call, the streamer's user goroutine won't be woken up, until a newly
introduced `doneAddingLocked` method is called by the worker goroutine.

Some care needs to be taken to prevent deadlocks with all of the
mutexes. Now, since we're finalizing the results one at a time, we might
need to hold the streamer's mutex (so that we can set `scanComplete`
correctly), and that mutex must be acquired before the results buffer's
one.

This change shows a modest improvement on the microbenchmarks but is
a lot more important on analytical, TPCH-like queries, where this
`[]Result` is one of the largest sources of garbage.

```
name                                                    old time/op    new time/op    delta
IndexJoin/Cockroach-24                                    5.98ms ± 1%    5.95ms ± 1%    ~     (p=0.079 n=9+10)
IndexJoin/MultinodeCockroach-24                           7.55ms ± 1%    7.59ms ± 1%  +0.47%  (p=0.015 n=8+9)
IndexJoinColumnFamilies/Cockroach-24                      8.68ms ± 3%    8.56ms ± 2%    ~     (p=0.133 n=9+10)
IndexJoinColumnFamilies/MultinodeCockroach-24             11.8ms ± 5%    11.7ms ± 3%    ~     (p=0.315 n=10+10)
LookupJoinEqColsAreKeyNoOrdering/Cockroach-24             6.67ms ± 1%    6.69ms ± 1%    ~     (p=0.315 n=10+9)
LookupJoinEqColsAreKeyNoOrdering/MultinodeCockroach-24    7.87ms ± 1%    7.92ms ± 1%  +0.73%  (p=0.015 n=10+10)
LookupJoinEqColsAreKeyOrdering/Cockroach-24               9.30ms ± 2%    9.31ms ± 4%    ~     (p=0.796 n=10+10)
LookupJoinEqColsAreKeyOrdering/MultinodeCockroach-24      10.9ms ± 4%    10.9ms ± 2%    ~     (p=0.971 n=10+10)
LookupJoinNoOrdering/Cockroach-24                         8.99ms ± 1%    9.03ms ± 4%    ~     (p=0.549 n=9+10)
LookupJoinNoOrdering/MultinodeCockroach-24                12.1ms ± 4%    11.9ms ± 6%    ~     (p=0.143 n=10+10)
LookupJoinOrdering/Cockroach-24                           10.9ms ± 3%    10.8ms ± 3%    ~     (p=0.243 n=10+9)
LookupJoinOrdering/MultinodeCockroach-24                  14.2ms ± 5%    13.9ms ± 3%    ~     (p=0.113 n=10+9)

name                                                    old alloc/op   new alloc/op   delta
IndexJoin/Cockroach-24                                    1.36MB ± 1%    1.31MB ± 0%  -3.61%  (p=0.000 n=10+9)
IndexJoin/MultinodeCockroach-24                           2.07MB ± 2%    2.04MB ± 3%    ~     (p=0.063 n=10+10)
IndexJoinColumnFamilies/Cockroach-24                      1.43MB ± 1%    1.38MB ± 0%  -3.56%  (p=0.000 n=9+9)
IndexJoinColumnFamilies/MultinodeCockroach-24             2.27MB ± 1%    2.22MB ± 2%  -2.09%  (p=0.000 n=8+10)
LookupJoinEqColsAreKeyNoOrdering/Cockroach-24             1.71MB ± 0%    1.67MB ± 0%  -2.70%  (p=0.000 n=9+10)
LookupJoinEqColsAreKeyNoOrdering/MultinodeCockroach-24    2.43MB ± 5%    2.35MB ± 1%  -3.31%  (p=0.000 n=10+10)
LookupJoinEqColsAreKeyOrdering/Cockroach-24               1.72MB ± 1%    1.62MB ± 1%  -6.20%  (p=0.000 n=10+10)
LookupJoinEqColsAreKeyOrdering/MultinodeCockroach-24      2.39MB ± 2%    2.30MB ± 3%  -3.53%  (p=0.000 n=10+10)
LookupJoinNoOrdering/Cockroach-24                         1.79MB ± 1%    1.74MB ± 1%  -2.80%  (p=0.000 n=10+9)
LookupJoinNoOrdering/MultinodeCockroach-24                2.35MB ± 3%    2.32MB ± 2%    ~     (p=0.079 n=10+9)
LookupJoinOrdering/Cockroach-24                           1.63MB ± 1%    1.53MB ± 1%  -5.77%  (p=0.000 n=10+10)
LookupJoinOrdering/MultinodeCockroach-24                  2.30MB ± 4%    2.23MB ± 2%  -3.41%  (p=0.002 n=9+8)

name                                                    old allocs/op  new allocs/op  delta
IndexJoin/Cockroach-24                                     7.15k ± 1%     7.16k ± 1%    ~     (p=0.888 n=10+9)
IndexJoin/MultinodeCockroach-24                            11.9k ± 2%     11.9k ± 2%    ~     (p=0.968 n=10+9)
IndexJoinColumnFamilies/Cockroach-24                       11.9k ± 0%     11.9k ± 0%    ~     (p=0.075 n=9+10)
IndexJoinColumnFamilies/MultinodeCockroach-24              17.6k ± 1%     17.5k ± 1%    ~     (p=0.566 n=10+10)
LookupJoinEqColsAreKeyNoOrdering/Cockroach-24              9.86k ± 1%     9.88k ± 1%    ~     (p=0.150 n=9+10)
LookupJoinEqColsAreKeyNoOrdering/MultinodeCockroach-24     14.1k ± 0%     14.1k ± 1%    ~     (p=0.055 n=8+10)
LookupJoinEqColsAreKeyOrdering/Cockroach-24                12.6k ± 1%     12.5k ± 1%  -0.77%  (p=0.005 n=10+10)
LookupJoinEqColsAreKeyOrdering/MultinodeCockroach-24       17.2k ± 1%     17.0k ± 0%  -0.88%  (p=0.000 n=10+8)
LookupJoinNoOrdering/Cockroach-24                          12.3k ± 1%     12.3k ± 1%    ~     (p=0.929 n=10+10)
LookupJoinNoOrdering/MultinodeCockroach-24                 16.8k ± 1%     16.8k ± 1%    ~     (p=0.968 n=9+10)
LookupJoinOrdering/Cockroach-24                            14.5k ± 1%     14.5k ± 1%    ~     (p=0.271 n=10+10)
LookupJoinOrdering/MultinodeCockroach-24                   19.4k ± 1%     19.3k ± 1%    ~     (p=0.056 n=9+8)
```

Addresses: #82160.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
On this PR, we get the following comparison of the streamer `off` (the first column) and the streamer `on` (the second column):
```
Q1: 4.17s	3.44s	-17.41%
Q2: 0.21s	0.19s	-9.95%
Q3: 1.67s	1.45s	-12.99%
Q4: 1.57s	1.20s	-23.76%
Q5: 2.38s	2.51s	5.50%
Q6: 6.86s	7.13s	3.89%
Q7: 5.90s	6.62s	12.29%
Q8: 1.15s	0.86s	-24.67%
Q9: 6.61s	5.58s	-15.55%
Q10: 2.08s	1.37s	-34.01%
Q11: 0.54s	0.47s	-13.60%
Q12: 7.70s	6.62s	-14.09%
Q13: 0.95s	0.92s	-3.48%
Q14: 0.58s	0.55s	-5.68%
Q15: 5.30s	4.30s	-18.82%
Q16: 0.84s	0.71s	-15.73%
Q17: 0.50s	0.62s	25.40%
Q18: 6.05s	5.14s	-15.01%
Q19: 4.33s	3.21s	-25.77%
Q20: 12.96s	12.27s	-5.28%
Q21: 9.63s	6.19s	-35.71%
Q22: 0.59s	0.48s	-18.24%
```

**Comment by yuzefovich** [comment]
Quick comparison between "streamer off" and "streamer on":
```
Q1: 3.80s	3.59s	-5.61%
Q2: 0.20s	0.20s	-0.50%
Q3: 1.90s	1.46s	-23.08%
Q4: 1.55s	1.15s	-25.99%
Q5: 2.46s	2.48s	0.69%
Q6: 6.67s	6.99s	4.84%
Q7: 6.68s	6.11s	-8.55%
Q8: 1.09s	1.10s	0.55%
Q9: 7.22s	6.22s	-13.87%
Q10: 1.99s	1.70s	-14.81%
Q11: 0.54s	0.51s	-6.08%
Q12: 7.24s	7.21s	-0.46%
Q13: 1.17s	1.11s	-5.47%
Q14: 0.59s	0.62s	5.08%
Q15: 5.12s	4.95s	-3.32%
Q16: 0.84s	0.76s	-9.37%
Q17: 0.49s	0.69s	39.51%
Q18: 5.98s	5.68s	-5.00%
Q19: 3.88s	3.66s	-5.64%
Q20: 12.84s	12.81s	-0.17%
Q21: 9.54s	6.87s	-27.94%
Q22: 0.58s	0.51s	-11.72%
```
Note that Q1, Q13, Q18, Q19 don't have index / lookup joins, so there should be no difference, but it shows up - meaning that the numbers have quite a bit of variance.

**Comment by yuzefovich** [comment]
First three commits are in separate PRs.

**Review by rharding6373 — DISMISSED** [review]
Did a first pass. The optimizations look like they're paying off! Nice work.

> Reviewed 2 of 3 files at r12, 3 of 3 files at r14, 1 of 2 files at r15, 1 of 4 files at r16.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82387#-:-N4ZJkFN7FaJ5b50bXi5:b-zai4sn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2, @rharding6373, and @yuzefovich)

___
*[`-- commits` line 163 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/82387#-N4YTgmU5PEmTnrGzQCV):*
Can we avoid the code duplication from reimplementing two sets of heap methods by making a helper that can implement a min heap that works for both?
___
*[`-- commits` line 201 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/82387#-N4YUw3CD_o6eLffpsoK):*
Turning this into a LIFO queue is a neat optimization.
___
*[`pkg/kv/kvclient/kvstreamer/results_buffer.go` line 271 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/82387#-N4YKoL_BPloC6m2VG5V:-N4YKoL_BPloC6m2VG5W:b-l3x47e) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef750e0c5fb7f9d5612b30f565c63ed7599bdca/pkg/kv/kvclient/kvstreamer/results_buffer.go#L271)):*
> ```Go
> func (b *outOfOrderResultsBuffer) doneAddingLocked() {
> 	b.Mutex.AssertHeld()
> 	b.signal()
> ```

How much of a performance hit is it to signal at the end of addLocked every time it's called and remove `doneAddingLocked` for reduced complexity?

Edit: I see in a later commit `doneAddingLocked` is also used for budgeting purposes, so getting rid of it may not be optimal anyway.
___
*[`pkg/kv/kvclient/kvstreamer/results_buffer.go` line 271 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/82387#-N4ZCluR0GQtugHDO2N_:-N4ZCluSAjUhdAahBojm:b6xhxxr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac225a12c6149017812c5244260ae8cf0ef43381/pkg/kv/kvclient/kvstreamer/results_buffer.go#L271)):*
> ```Go
> 
> func (b *outOfOrderResultsBuffer) doneAddingLocked() {
> 	b.Mutex.AssertHeld()
> ```

Isn't it still advisable to hold the lock while signaling on the channel?
___
*[`pkg/kv/kvclient/kvstreamer/results_buffer.go` line 297 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/82387#-N4ZE4E_5NFmJOPn-IVK:-N4ZE4E_5NFmJOPn-IVL:b-630f80) ([raw file](https://github.com/cockroachdb/cockroach/blob/0da495263fa2578011a2a3d228965acb591a6006/pkg/kv/kvclient/kvstreamer/results_buffer.go#L297)):*
> ```Go
> 
> func (b *outOfOrderResultsBuffer) doneAddingLocked(ctx context.Context) {
> 	b.accountForOverheadLocked(ctx, int64(cap(b.results))*resultSize)
> ```

If I understand this correctly, we can go into memory debt doing this. But in the previous commit we reuse `results`, right? So we also never reduce the capacity of results, which may cause us to stay in debt?
___
*[`pkg/kv/kvclient/kvstreamer/streamer.go` line 1372 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/82387#-N4YRVZJ7kb4WQCw_OX5:-N4YRVZJ7kb4WQCw_OX6:b-4quwjy) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef750e0c5fb7f9d5612b30f565c63ed7599bdca/pkg/kv/kvclient/kvstreamer/streamer.go#L1372)):*
> ```Go
> 				result.memoryTok.toRelease = getResponseSize(get)
> 				memoryTokensBytes += result.memoryTok.toRelease
> 				s.results.addLocked(result)
> ```

I'm a bit concerned about having calls to `addLocked` deep in here when the lock is acquired in a conditional above, and that the conditions being the same aren't immediately obvious. The assertion that the lock is held in `addLocked` helps, but this seems complicated. Will think about this more, nothing actionable atm.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82387)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @rharding6373)

___
*[`-- commits` line 163 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/82387#-N4YTgmU5PEmTnrGzQCV):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Can we avoid the code duplication from reimplementing two sets of heap methods by making a helper that can implement a min heap that works for both?
</blockquote></details>

I don't think we can do this without sacrificing the performance (or, more specifically, without increase in allocations). We could get around this by using generics and then having a single helper, but without the generics, the helper would have to operate on `interface{}` which escapes to the heap (leading to allocations), and the current code operates on concrete structs `singleRangeBatch` and `inOrderBufferedResult`. Another way for having a single helper would be to unify these two structs into one, but that seems extremely dirty.

Thus, I think we should either proceed with the duplicated approach or get rid off the commit altogether. Given the perf wins and reduction in allocations I think the code duplication is worth it.
___
*[`pkg/kv/kvclient/kvstreamer/results_buffer.go` line 271 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/82387#-N4YKoL_BPloC6m2VG5V:-N5CbGLp7yLp4USHgg60:bqwhcbf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef750e0c5fb7f9d5612b30f565c63ed7599bdca/pkg/kv/kvclient/kvstreamer/results_buffer.go#L271)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

How much of a performance hit is it to signal at the end of addLocked every time it's called and remove `doneAddingLocked` for reduced complexity?

Edit: I see in a later commit `doneAddingLocked` is also used for budgeting purposes, so getting rid of it may not be optimal anyway.
</blockquote></details>

I actually had the same thought initially - whether it is worth introducing this `doneAddingLocked` method to be able to "batch" the results returned on `get` call (if we signaled on the channel every time in `addLocked`, in theory `get` could be returning one result at a time) - and wanted to prototype the approach without `doneAddingLocked`. But then I added the memory accounting and this method is very convenient place to do that, so I decided it's probably worth keeping it.

The semantics of `addLocked` and `doneAddingLocked` seem pretty clean, so I ended up not prototyping what the performance implications / mutex contention would be if we did the memory accounting as well as the signaling on the channel on every `addLocked` call.
___
*[`pkg/kv/kvclient/kvstreamer/results_buffer.go` line 271 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/82387#-N4ZCluR0GQtugHDO2N_:-N5CXft_7SpigOGEOKkt:b-wzwiky) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac225a12c6149017812c5244260ae8cf0ef43381/pkg/kv/kvclient/kvstreamer/results_buffer.go#L271)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Isn't it still advisable to hold the lock while signaling on the channel?
</blockquote></details>

Yeah, we're still holding the lock, and it is checked in `accountForOverheadLocked`. I removed it here to avoid the duplication but can bring it back if you think it makes things more clear - there should be no performance impact whatsoever for asserting the mutex is held in regular builds.
___
*[`pkg/kv/kvclient/kvstreamer/results_buffer.go` line 297 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/82387#-N4ZE4E_5NFmJOPn-IVK:-N5CYLs7-wio-qpLPjxm:b-fpl8za) ([raw file](https://github.com/cockroachdb/cockroach/blob/0da495263fa2578011a2a3d228965acb591a6006/pkg/kv/kvclient/kvstreamer/results_buffer.go#L297)):*
You're right that the budget can go into debt (since the results buffer doesn't have a push back mechanism, and it would be sad - and more difficult - to drop already completed results). The idea is that the worker coordinator will see that the budget in debt, so it won't issue any more requests, eventually the caller will consume results by `GetResults` call, and the budget should get out of debt once those results are `Release`d. Note that here we account only for the overhead of the results (i.e. the shallow size of `Result` object which is a constant) and not the KV response (which can be arbitrarily large), so it should be relatively unlikely that we get into debt when accounting for the overhead.

> But in the previous commit we reuse `results`, right?

The previous commit reuses the results only in the InOrder mode and only for the return value of `get` call. In the InOrder mode we need two slices - one is for the buffered results (all results we have received but not returned yet) and another to return on `get` call (all the results that we can return according to the ordering). The first slice is reused implicitly since we're maintaining a heap over it (meaning that we're removing from the tail and adding to the tail - and then pushing elements down if needed), the second slice is reused explicitly. Initially I forgot to account for the second slice, fixed.

> So we also never reduce the capacity of results, which may cause us to stay in debt?

In theory, I guess it's possible, but in reality this should never happen. This could happen if we're using the InOrder mode, the overhead of `buffered` and `resultsScratch` is large in comparison to the total budget so that even when we spill results to disk, the overhead (which is always kept in memory) still keeps the budget in debt. I could only see this happen if the budget's limit is too small.

In the OutOfOrder mode the capacity of `results` can reduce since we are not reusing the slice after `get` call. (I have thought about trying to reuse it but it's quite complex given that we don't know when results get `Release`d - we might have concurrent `addLocked` call to add a new result into the reused slice before the corresponding result has been processed by the caller.)
___
*[`pkg/kv/kvclient/kvstreamer/streamer.go` line 1372 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/82387#-N4YRVZJ7kb4WQCw_OX5:-N5CdQjd0W9iXBWyLYGh:b-xeaixg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef750e0c5fb7f9d5612b30f565c63ed7599bdca/pkg/kv/kvclient/kvstreamer/streamer.go#L1372)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I'm a bit concerned about having calls to `addLocked` deep in here when the lock is acquired in a conditional above, and that the conditions being the same aren't immediately obvious. The assertion that the lock is held in `addLocked` helps, but this seems complicated. Will think about this more, nothing actionable atm.
</blockquote></details>

I agree that the structure of the code doesn't make it clear that the right locks are held, but I'm not sure how to improve it - any suggestions are very welcome. I did add some test assertions though.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82387)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @rharding6373)

___
*[`pkg/kv/kvclient/kvstreamer/streamer.go` line 1372 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/82387#-N4YRVZJ7kb4WQCw_OX5:-N5MRk7N3IIO4jfEaXkw:b4b79d) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef750e0c5fb7f9d5612b30f565c63ed7599bdca/pkg/kv/kvclient/kvstreamer/streamer.go#L1372)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I agree that the structure of the code doesn't make it clear that the right locks are held, but I'm not sure how to improve it - any suggestions are very welcome. I did add some test assertions though.
</blockquote></details>

Drive-by waiting for some code to compile. You've effectively got the same conditional inside this function twice, once at the top, once at the bottom, and then you've got an assumption about its value in the middle. This makes me think one way to make it cleaner is to split it into two different functions, perhaps `processEmptySingleRangeResults` and what you've got where you check the condition at the top and call down to the special case and then the logic in the body of the current function can assume you need to lock and make that clear etc. Maybe there will be a touch of duplication, but it seems worth it.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82387)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @rharding6373)

___
*[`pkg/kv/kvclient/kvstreamer/streamer.go` line 1372 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/82387#-N4YRVZJ7kb4WQCw_OX5:-N5MhlZT597RTyVF9E06:b7sqbab) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef750e0c5fb7f9d5612b30f565c63ed7599bdca/pkg/kv/kvclient/kvstreamer/streamer.go#L1372)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Drive-by waiting for some code to compile. You've effectively got the same conditional inside this function twice, once at the top, once at the bottom, and then you've got an assumption about its value in the middle. This makes me think one way to make it cleaner is to split it into two different functions, perhaps `processEmptySingleRangeResults` and what you've got where you check the condition at the top and call down to the special case and then the logic in the body of the current function can assume you need to lock and make that clear etc. Maybe there will be a touch of duplication, but it seems worth it. 
</blockquote></details>

Drive-bys are always welcome!

I read over your suggestion several times, but I'm not sure I follow. Are you suggesting splitting out a single loop over `br.Responses` into two loops, each in a separate function (one would process responses for which we create results, and another would process responses with the resume spans which we add into the resume request)?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82387)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @rharding6373)

___
*[`pkg/kv/kvclient/kvstreamer/streamer.go` line 1372 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/82387#-N4YRVZJ7kb4WQCw_OX5:-N5Xihl999cqFxWASYh4:bb0bb2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef750e0c5fb7f9d5612b30f565c63ed7599bdca/pkg/kv/kvclient/kvstreamer/streamer.go#L1372)):*

> Are you suggesting splitting out a single loop over br.Responses into two loops, each in a separate function (one would process responses for which we create results, and another would process responses with the resume spans which we add into the resume request)?

Yep. See how these two commits make you feel: https://github.com/yuzefovich/cockroach/compare/streamer-optimizations...ajwerner:streamer-optimizations?expand=1

**Review by yuzefovich — COMMENTED** [review]
I took up Andrew's suggestion and included into a new commit. I also removed most of the commits from this PR for ease of reviewing. The first commit is still part of another PR and should be ignored here. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82387#-:-N5aL74I9e5ZFgm8MGkD:b-s29l8o)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @rharding6373)

___
*[`pkg/kv/kvclient/kvstreamer/streamer.go` line 1372 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/82387#-N4YRVZJ7kb4WQCw_OX5:-N5_mI5I0LnbTiLUMXeO:brteucc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef750e0c5fb7f9d5612b30f565c63ed7599bdca/pkg/kv/kvclient/kvstreamer/streamer.go#L1372)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>


> Are you suggesting splitting out a single loop over br.Responses into two loops, each in a separate function (one would process responses for which we create results, and another would process responses with the resume spans which we add into the resume request)?

Yep. See how these two commits make you feel: https://github.com/yuzefovich/cockroach/compare/streamer-optimizations...ajwerner:streamer-optimizations?expand=1
</blockquote></details>

Makes sense, thanks for typing this out. I was a bit concerned about the performance impact of having an additional loop (since on each request we perform pretty expensive type switches and interface dispatching), but the microbenchmarks don't reveal any perf hit, so I think the cleanup offered by this change is worth it.

**Review by michae2 — APPROVED** [review]
:lgtm:

I left a few thoughts below but they're not important.

> Reviewed 1 of 1 files at r26, 9 of 9 files at r28, 1 of 9 files at r29, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82387#-:-N5lqW02BJrJAlDRJ1_N:b-dit9z1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @michae2, @rharding6373, and @yuzefovich)

___
*[`pkg/kv/kvclient/kvstreamer/results_buffer.go` line 271 at r29](https://reviewable.io/reviews/cockroachdb/cockroach/82387#-N5lqBzD-EYO27rGPhAX:-N5lqBzD-EYO27rGPhAY:bmnpup4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ded11a454b73a4c33e697b5739f686137a3ebc7e/pkg/kv/kvclient/kvstreamer/results_buffer.go#L271)):*
> ```Go
> func (b *outOfOrderResultsBuffer) doneAddingLocked() {
> 	b.Mutex.AssertHeld()
> 	b.signal()
> ```

nit: Now that these are separate methods, you might consider guarding this signal with `if len(b.results) > 0`.
___
*[`pkg/kv/kvclient/kvstreamer/streamer.go` line 1312 at r29](https://reviewable.io/reviews/cockroachdb/cockroach/82387#-N5liH0b5QLaurT8Rm78:-N5liH0b5QLaurT8Rm79:b3zvs3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/ded11a454b73a4c33e697b5739f686137a3ebc7e/pkg/kv/kvclient/kvstreamer/streamer.go#L1312)):*
> ```Go
> 	s.mu.avgResponseEstimator.update(
> 		fp.memoryFootprintBytes, int64(fp.numGetResults+fp.numScanResults),
> 	)
> ```

suggestion: How about doing this at the end of this function, with `int64(fp.numGetResults + someOtherCounter)` where `someOtherCounter` is incremented whenever `result.scanComplete` is true?

Oh, you're trying to avoid holding the streamer mutex for the whole function. :thinking: Well, never mind.

Oh, this value is already in `resultsBufferBase.numCompleteResponses`. Maybe the `avgResponseEstimator` should be part of `resultsBufferBase`?

Anyway, not super important.



_Code quote:_
```Go
	// TODO(yuzefovich): some of the responses might be partial, yet the
	// estimator doesn't distinguish the footprint of the full response vs
	// the partial one. Think more about this.
	s.mu.avgResponseEstimator.update(
		fp.memoryFootprintBytes, int64(fp.numGetResults+fp.numScanResults),
	)
```

**Review by michae2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82387)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @michae2, @rharding6373, and @yuzefovich)

___
*[`pkg/kv/kvclient/kvstreamer/results_buffer.go` line 48 at r29](https://reviewable.io/reviews/cockroachdb/cockroach/82387#-N5lupeb3B9Oe8HQI6Du:-N5lupec1Tr4G_vrf-JF:b-rkji8r) ([raw file](https://github.com/cockroachdb/cockroach/blob/ded11a454b73a4c33e697b5739f686137a3ebc7e/pkg/kv/kvclient/kvstreamer/results_buffer.go#L48)):*
> ```Go
> 	// moment. The boolean indicates whether all expected Results have been
> 	// returned. Must be called without holding the budget's mutex.
> 	get(context.Context) (_ []Result, allComplete bool, _ error)
> ```

Random thought: if you want to optimize further (and make the streamer even more like io_uring) you could change `get` to return a pointer to a single `Result` rather than returning `[]Result` (or turn it into some kind of result-by-result iterator).

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82387#-:-N5n6YMlCkkgRdQQWc_h:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @michae2, and @rharding6373)

___
*[`pkg/kv/kvclient/kvstreamer/results_buffer.go` line 48 at r29](https://reviewable.io/reviews/cockroachdb/cockroach/82387#-N5lupeb3B9Oe8HQI6Du:-N5n2Pox2cENVXMS5ujg:b-6190pw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ded11a454b73a4c33e697b5739f686137a3ebc7e/pkg/kv/kvclient/kvstreamer/results_buffer.go#L48)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Random thought: if you want to optimize further (and make the streamer even more like io_uring) you could change `get` to return a pointer to a single `Result` rather than returning `[]Result` (or turn it into some kind of result-by-result iterator).
</blockquote></details>

I think I did prototype such an idea at some point (hoping to remove the allocation needed for `[]Result` in the InOrder mode as well as to reuse the `results` slice in the OutOfOrder mode), but it showed a regression in performance. Added a TODO to try that again.
___
*[`pkg/kv/kvclient/kvstreamer/results_buffer.go` line 271 at r29](https://reviewable.io/reviews/cockroachdb/cockroach/82387#-N5lqBzD-EYO27rGPhAX:-N5n34lYAjzDtWMkm3td:b-aa59em) ([raw file](https://github.com/cockroachdb/cockroach/blob/ded11a454b73a4c33e697b5739f686137a3ebc7e/pkg/kv/kvclient/kvstreamer/results_buffer.go#L271)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: Now that these are separate methods, you might consider guarding this signal with `if len(b.results) > 0`.
</blockquote></details>

Hm, I think I'll keep it the way it is - the only downside of signaling when there are no results (which shouldn't really happen) is that the streamer's user gorouting will wake up in `Streamer.GetResults` only to go back to sleep, meaning there is little harm.
___
*[`pkg/kv/kvclient/kvstreamer/streamer.go` line 1312 at r29](https://reviewable.io/reviews/cockroachdb/cockroach/82387#-N5liH0b5QLaurT8Rm78:-N5n44uHC8HVAzFj9WXu:b-kqvx78) ([raw file](https://github.com/cockroachdb/cockroach/blob/ded11a454b73a4c33e697b5739f686137a3ebc7e/pkg/kv/kvclient/kvstreamer/streamer.go#L1312)):*
> you're trying to avoid holding the streamer mutex for the whole function. 

Yeah, I tried to optimize the locking pattern so that we don't hold locks for longer than needed and don't acquire the same lock multiple times inside of the same function.

> this value is already in `resultsBufferBase.numCompleteResponses`.

Not exactly - `fp.numGetResults+fp.numScanResults` is the number of `Result` objects created based on a single BatchRequest that targeted a single range whereas `resultsBufferBase.numCompleteResponses` tracks the number of "complete" requests (which could be spanning multiple ranges) for the current Enqueue batch of requests. `numCompleteResponses` is reset across `Streamer.Enqueue` calls whereas the avg response size estimator is updated throughout the lifetime of the Streamer. So `avgResponseEstimator.numResponses` does equal `resultsBufferBase.numCompleteResponses`, but only before the second call to `Enqueue`.

> Maybe the `avgResponseEstimator` should be part of `resultsBufferBase`?

Hm, it's an interesting question. I do see some similarities in these components (e.g. that they handle the results from the BatchResponses), but I think it's cleaner to keep them apart. I think in the future (e.g. when we hook up the Streamer to power regular scans - i.e. TableReaders / cFetchers) the avg response estimator will need to be more sophisticated and it'll probably be better if that complicated logic doesn't make the code around the results buffer more complicated too.

**Comment by yuzefovich** [comment]
Seems like acceptance flake.

bors r+

**Pull request merged**
