### PR TITLE
sql: add role_id and member_id columns to system.role_members table

### PR DESCRIPTION
**Pull request by andyyang890**
This patch adds user ID columns to the system.role_members table.
The new `role_id` column corresponds to the existing `role` column
and the new `member_id` column corresponds to the existing `member`
column. Migrations are also added to alter and backfill the table
in older clusters.

Part of #87079

Release note: None

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
this is looking good! i just had small comments

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91517#-:-NH1OUqyB--zo-rBBd0R:b-erhekz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890)

___
*[`pkg/upgrade/upgrades/role_members_ids_migration.go` line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91517#-NH1NDIV75i_-B83L9D0:-NH1NDIXD0FuOp1AF4LY:bx2h4dx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3a163817f86e2f1161b6825ffe499e0a768e486/pkg/upgrade/upgrades/role_members_ids_migration.go#L87)):*
> ```Go
> 
> const backfillIDColumnsRoleMembersStmt = `
> UPDATE system.role_members
> ```

I'm mildly worried about the cross join on system.users, since that could potentially lead to a lot of memory usage while executing the query. i wonder if it would be easier to reason about if we did with two separate queries:
```
UPDATE system.role_members
SET role_id = u.user_id
FROM system.users u
WHERE role_id IS NULL and role = u.username
LIMIT 1;

UPDATE system.role_members
SET member_id = u.user_id
FROM system.users u
WHERE member_id IS NULL and member = u.username
```
___
*[`pkg/upgrade/upgrades/role_members_ids_migration.go` line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91517#-NH1OEZw5PkUovYOKK8Z:-NH1OEZx6LwemWNHxdmi:b-y7905w) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3a163817f86e2f1161b6825ffe499e0a768e486/pkg/upgrade/upgrades/role_members_ids_migration.go#L97)):*
> ```Go
> 	ctx context.Context, _ clusterversion.ClusterVersion, d upgrade.TenantDeps, _ *jobs.Job,
> ) error {
> 	row, err := d.InternalExecutor.QueryRowEx(ctx, `get-num-null-role-ids-system-role-members`, nil,
> ```

nit: we don't need this query - we can just keep running the update query until it returns a "rows affected" of 0

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91517)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/upgrade/upgrades/role_members_ids_migration.go` line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91517#-NH1NDIV75i_-B83L9D0:-NH6A3lsEP9NsWhAEfJo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3a163817f86e2f1161b6825ffe499e0a768e486/pkg/upgrade/upgrades/role_members_ids_migration.go#L87)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

I'm mildly worried about the cross join on system.users, since that could potentially lead to a lot of memory usage while executing the query. i wonder if it would be easier to reason about if we did with two separate queries:
```
UPDATE system.role_members
SET role_id = u.user_id
FROM system.users u
WHERE role_id IS NULL and role = u.username
LIMIT 1;

UPDATE system.role_members
SET member_id = u.user_id
FROM system.users u
WHERE member_id IS NULL and member = u.username
```


</blockquote></details>

Done.

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91517)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/upgrade/upgrades/role_members_ids_migration.go` line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91517#-NH1OEZw5PkUovYOKK8Z:-NH6DS1k9Ihc3QRLTkfV:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3a163817f86e2f1161b6825ffe499e0a768e486/pkg/upgrade/upgrades/role_members_ids_migration.go#L97)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: we don't need this query - we can just keep running the update query until it returns a "rows affected" of 0
</blockquote></details>

Fixed.

**Review by ZhouXing19 — CHANGES_REQUESTED** [review]
~Left some comments for usages of internal executor~ somehow my comments are gone! Leaving them again

**Review by ZhouXing19 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91517)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890 and @rafiss)

___
*[`pkg/sql/grant_role.go` line 170 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91517#-NH6LF42-27Gukn8ylAa:-NH6LF42-27Gukn8ylAb:b-mlljic) ([raw file](https://github.com/cockroachdb/cockroach/blob/80f78167566b9bb52899aa627cd54c8d6ba0635b/pkg/sql/grant_role.go#L170)):*
> ```Go
> 
> func (n *GrantRoleNode) startExec(params runParams) error {
> 	opName := "grant-role"
> ```

Could you wrap all contents in this function with 
`params.p.WithInternalExecutor(params.ctx, func(ctx context.Context, txn *kv.Txn, ie sqlutil.InternalExecutor) error{<content>}`, and change the `params.p.ExecCfg().InternalExecutor` or `params.extendedEvalCtx.ExecCfg.InternalExecutor` to `ie`? Thank you!
___
*[`pkg/upgrade/upgrades/role_members_ids_migration.go` line 99 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91517#-NH6L_Ah7UWPon18Aqp9:-NH6L_Ah7UWPon18AqpA:b7ca6qc) ([raw file](https://github.com/cockroachdb/cockroach/blob/80f78167566b9bb52899aa627cd54c8d6ba0635b/pkg/upgrade/upgrades/role_members_ids_migration.go#L99)):*
> ```Go
> 	for _, colName := range []string{"role_id", "member_id"} {
> 		for {
> 			rowsAffected, err := d.InternalExecutor.ExecEx(ctx, "backfill-id-columns-system-role-members", nil,
> ```

Could you change it to 
```
ie := d.InternalExecutorFactory.MakeInternalExecutorWithoutTxn()
for. ... {
  for ... {
    rowsAffected, err := ie.ExecEx(ctx, "backfill-id-columns-system-role-members", nil /* txn */, 
        sessiondata.NodeUserSessionDataOverride,
	fmt.Sprintf(backfillIDColumnsRoleMembersStmt, colName),
    )

  }
}
```
We'd like to advocate using `MakeInternalExecutorWithoutTxn` for internal executor that run queries with `nil` txn.

**Comment by ZhouXing19** [comment]
*[`pkg/upgrade/upgrades/role_members_ids_migration.go` line 99 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91517#-NH6L_Ah7UWPon18Aqp9:-NH6MTEO9VifMreoLF6S:b-3zgk9a) ([raw file](https://github.com/cockroachdb/cockroach/blob/80f78167566b9bb52899aa627cd54c8d6ba0635b/pkg/upgrade/upgrades/role_members_ids_migration.go#L99)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Could you change it to 
```
ie := d.InternalExecutorFactory.MakeInternalExecutorWithoutTxn()
for. ... {
  for ... {
    rowsAffected, err := d.InternalExecutor.ExecEx(ctx, "backfill-id-columns-system-role-members", nil /* txn */, 
        sessiondata.NodeUserSessionDataOverride,
	fmt.Sprintf(backfillIDColumnsRoleMembersStmt, colName),
    )

  }
}
```
We'd like to advocate using `MakeInternalExecutorWithoutTxn` for internal executor that run queries with `nil` txn. 
</blockquote></details>

Sorry, `d.InternalExecutor.ExecEx` should be `ie.ExecEx` in the comment above.

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91517)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @ZhouXing19)

___
*[`pkg/sql/grant_role.go` line 170 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91517#-NH6LF42-27Gukn8ylAa:-NH_vTWlApdZrJdfEEJj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/80f78167566b9bb52899aa627cd54c8d6ba0635b/pkg/sql/grant_role.go#L170)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Could you wrap all contents in this function with 
`params.p.WithInternalExecutor(params.ctx, func(ctx context.Context, txn *kv.Txn, ie sqlutil.InternalExecutor) error{<content>}`, and change the `params.p.ExecCfg().InternalExecutor` or `params.extendedEvalCtx.ExecCfg.InternalExecutor` to `ie`? Thank you!
</blockquote></details>

Done.
___
*[`pkg/upgrade/upgrades/role_members_ids_migration.go` line 99 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91517#-NH6L_Ah7UWPon18Aqp9:-NH_vRa3EYNQ39YsPTHp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/80f78167566b9bb52899aa627cd54c8d6ba0635b/pkg/upgrade/upgrades/role_members_ids_migration.go#L99)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Sorry, `d.InternalExecutor.ExecEx` should be `ie.ExecEx` in the comment above.
</blockquote></details>

Done.

**Review by ZhouXing19 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91517)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890, @benbardin, and @rafiss)

___
*[`pkg/sql/grant_role.go` line 196 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91517#-NI57vLsDd2ylhuX_5Pl:-NI57vLsDd2ylhuX_5Pm:b8zcw5a) ([raw file](https://github.com/cockroachdb/cockroach/blob/45e40b612c3e9cb6c40e9d30d27a512875e90e74/pkg/sql/grant_role.go#L196)):*
> ```Go
> 	}
> 	qargs[2] = n.adminOption
> 	for _, r := range n.roles {
> ```

We just need one `params.p.WithInternalExecutor()` wrapping these outer `for` loops here. `params.p.WithInternalExecutor()` will always create a new internal executor for the closure passed to it, but here the internal executor can be reused since it's always bound to the same txn from the planner.
___
*[`pkg/upgrade/upgrades/permanent_upgrades.go` line 57 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91517#-NI59m9I1sRziRItgoRK:-NI59m9I1sRziRItgoRL:b-xre785) ([raw file](https://github.com/cockroachdb/cockroach/blob/45e40b612c3e9cb6c40e9d30d27a512875e90e74/pkg/upgrade/upgrades/permanent_upgrades.go#L57)):*
> ```Go
> 	const upsertMembership = `
>           UPSERT INTO system.role_members ("role", "member", "isAdmin", role_id, member_id) VALUES ($1, $2, true, $3, $4)
>           `
> ```

Could you also do 
```
ieNotBoundToTxn := deps.InternalExecutorFactory.MakeInternalExecutorWithoutTxn()
_, err = ieNotBoundToTxn.Exec(...)
```
here? Thanks!
___
*[`pkg/upgrade/upgrades/role_members_ids_migration.go` line 99 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91517#-NH6L_Ah7UWPon18Aqp9:-NI58WrM9gZ0Oarl8sGC:bjtmqa2) ([raw file](https://github.com/cockroachdb/cockroach/blob/80f78167566b9bb52899aa627cd54c8d6ba0635b/pkg/upgrade/upgrades/role_members_ids_migration.go#L99)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Ditto, the internal executor can be reused, so we can create it outside these 2 for loops.

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91517)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @benbardin, @rafiss, and @ZhouXing19)

___
*[`pkg/sql/grant_role.go` line 196 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91517#-NI57vLsDd2ylhuX_5Pl:-NI6A4pZ-eZpHd4BU973:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/45e40b612c3e9cb6c40e9d30d27a512875e90e74/pkg/sql/grant_role.go#L196)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

We just need one `params.p.WithInternalExecutor()` wrapping these outer `for` loops here. `params.p.WithInternalExecutor()` will always create a new internal executor for the closure passed to it, but here the internal executor can be reused since it's always bound to the same txn from the planner.
</blockquote></details>

Done.
___
*[`pkg/upgrade/upgrades/permanent_upgrades.go` line 57 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91517#-NI59m9I1sRziRItgoRK:-NI6A5x63hpFPKR6WNbh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/45e40b612c3e9cb6c40e9d30d27a512875e90e74/pkg/upgrade/upgrades/permanent_upgrades.go#L57)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Could you also do 
```
ieNotBoundToTxn := deps.InternalExecutorFactory.MakeInternalExecutorWithoutTxn()
_, err = ieNotBoundToTxn.Exec(...)
```
here? Thanks!
</blockquote></details>

Done.
___
*[`pkg/upgrade/upgrades/role_members_ids_migration.go` line 99 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91517#-NH6L_Ah7UWPon18Aqp9:-NI6A6Yo3G67wnwFASei:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/80f78167566b9bb52899aa627cd54c8d6ba0635b/pkg/upgrade/upgrades/role_members_ids_migration.go#L99)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Ditto, the internal executor can be reused, so we can create it outside these 2 for loops.
</blockquote></details>

Done.

**Review by ZhouXing19 — COMMENTED** [review]
The usages of internal executor looks good to me, thanks for making the changes! 
I'll let Rafi finalize the review.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91517#-:-NI8AiGI7Z-w4Y2XUeyl:b-h9fbur)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @benbardin and @rafiss)

**Review by rafiss — APPROVED** [review]
nice, lgtm! thanks for all the testing you've included here

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91517#-:-NIEVJrE-6K3wUx6Yoev:b-8s8h1u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @benbardin and @ZhouXing19)

**Comment by andyyang890** [comment]
TFTR!

bors r=rafiss

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91517)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890, @benbardin, @rafiss, and @ZhouXing19)

___
*[`pkg/clusterversion/cockroach_versions.go` line 610 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/91517#-NIIoUTuBpEsuQ56E0YE:-NIIoUTuBpEsuQ56E0YF:b-sl1rhz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8629d41699da1654ee4771f424c5bb5667c8df90/pkg/clusterversion/cockroach_versions.go#L610)):*
> ```Go
> 	},
> 	{
> 		Key:     V23_1RoleMembersTableHasIDColumns,
> ```

is there a reason to have 3 distinct versions and 3 upgrades instead of a single one?
___
*[`pkg/upgrade/upgrades/permanent_upgrades.go` line 36 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/91517#-NIIowI4Dw0blS8P01HV:-NIIowI4Dw0blS8P01HW:b-scqhof) ([raw file](https://github.com/cockroachdb/cockroach/blob/8629d41699da1654ee4771f424c5bb5667c8df90/pkg/upgrade/upgrades/permanent_upgrades.go#L36)):*
> ```Go
> 	ctx context.Context, _ clusterversion.ClusterVersion, deps upgrade.TenantDeps,
> ) error {
> 	ieNotBoundToTxn := deps.InternalExecutorFactory.MakeInternalExecutorWithoutTxn()
> ```

pls make this change in a different commit, if it's needed.
Is it need? I see other uses of `TenantDeps.InternalExecutor`. If that's no good, consider getting rid of all of them at once.
___
*[`pkg/upgrade/upgrades/permanent_upgrades.go` line 62 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/91517#-NIIoodQ8aBhDrXn1McP:-NIIoodQ8aBhDrXn1McQ:b-36sllk) ([raw file](https://github.com/cockroachdb/cockroach/blob/8629d41699da1654ee4771f424c5bb5667c8df90/pkg/upgrade/upgrades/permanent_upgrades.go#L62)):*
> ```Go
> 	_, err = ieNotBoundToTxn.Exec(
> 		ctx, "addRootToAdminRole", nil /* txn */, upsertMembership, username.AdminRole, username.RootUser, username.AdminRoleID, username.RootUserID)
> 	if err != nil {
> ```

either a blind return, as it was before, or `return nil` at the end if you're handling the error

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91517)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @benbardin, @knz, @rafiss, and @ZhouXing19)

___
*[`pkg/clusterversion/cockroach_versions.go` line 610 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/91517#-NIIoUTuBpEsuQ56E0YE:-NIIzkQQ6Yt2hOa0ZaSo:b-2ozti7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8629d41699da1654ee4771f424c5bb5667c8df90/pkg/clusterversion/cockroach_versions.go#L610)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

is there a reason to have 3 distinct versions and 3 upgrades instead of a single one?
</blockquote></details>

I based this PR off of https://github.com/cockroachdb/cockroach/pull/81457 and I believe @knz left a comment saying this should be done in three versions here https://github.com/cockroachdb/cockroach/pull/81457#pullrequestreview-1041184202.
___
*[`pkg/upgrade/upgrades/permanent_upgrades.go` line 36 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/91517#-NIIowI4Dw0blS8P01HV:-NIJ0X-TEtBaQXtKx43T:bail9eo) ([raw file](https://github.com/cockroachdb/cockroach/blob/8629d41699da1654ee4771f424c5bb5667c8df90/pkg/upgrade/upgrades/permanent_upgrades.go#L36)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls make this change in a different commit, if it's needed.
Is it need? I see other uses of `TenantDeps.InternalExecutor`. If that's no good, consider getting rid of all of them at once.
</blockquote></details>

Ok I moved it out. I'll defer to @zhouxing19 to comment on why it's needed.
___
*[`pkg/upgrade/upgrades/permanent_upgrades.go` line 62 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/91517#-NIIoodQ8aBhDrXn1McP:-NIJ0iSf58MV9d8sSfRZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8629d41699da1654ee4771f424c5bb5667c8df90/pkg/upgrade/upgrades/permanent_upgrades.go#L62)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

either a blind return, as it was before, or `return nil` at the end if you're handling the error
</blockquote></details>

Done.

**Comment by ZhouXing19** [comment]
*[`pkg/upgrade/upgrades/permanent_upgrades.go` line 36 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/91517#-NIIowI4Dw0blS8P01HV:-NIJ2ReM7A8q-vWW8dIM:b4vz3uq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8629d41699da1654ee4771f424c5bb5667c8df90/pkg/upgrade/upgrades/permanent_upgrades.go#L36)):*
> Is it need? I see other uses of TenantDeps.InternalExecutor. If that's no good, consider getting rid of all of them at once.

We ultimately want to get rid of `TenantDeps.InternalExecutor`, as stated in https://github.com/cockroachdb/cockroach/issues/91004.
I don't think we need to get rid of them all in this PR -- there are 27 direct usages of `TenantDeps.InternalExecutor` and some of them can involve more complicated changes. I've made https://github.com/cockroachdb/cockroach/issues/92938 to track it and will work on it shortly.

**Comment by andyyang890** [comment]
Interestingly, removing the addition of `ieNotBoundToTxn` in `pkg/upgrade/upgrades/permanent_upgrades.go` seems to have fixed the issue of the `acceptance/version-upgrade` roachtest hanging. Will try merging again now!

bors r=rafiss

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91517)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @benbardin, @knz, @rafiss, and @ZhouXing19)

___
*[`pkg/clusterversion/cockroach_versions.go` line 610 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/91517#-NIIoUTuBpEsuQ56E0YE:-NIJHKfGAsy5cFRlqHhq:bvyuvcr) ([raw file](https://github.com/cockroachdb/cockroach/blob/8629d41699da1654ee4771f424c5bb5667c8df90/pkg/clusterversion/cockroach_versions.go#L610)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

I based this PR off of https://github.com/cockroachdb/cockroach/pull/81457 and I believe @knz left a comment saying this should be done in three versions here https://github.com/cockroachdb/cockroach/pull/81457#pullrequestreview-1041184202.
</blockquote></details>

I believe Raphael said two versions, not 3 ("version 1" in that list is pre-existing). Like, why do the indexes need to be added in a separate upgrade?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91517)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890, @benbardin, @knz, @rafiss, and @ZhouXing19)

___
*[`pkg/upgrade/upgrades/permanent_upgrades.go` line 56 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/91517#-NIJIeD3ACI3Q29xcnvi:-NIJIeD3ACI3Q29xcnvj:bxuqbv9) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd25722b412251ed4d46b425d4d28fe2cca574ab/pkg/upgrade/upgrades/permanent_upgrades.go#L56)):*
> ```Go
> 	// Upsert the role membership into the table. We intentionally override any existing entry.
> 	const upsertMembership = `
>           UPSERT INTO system.role_members ("role", "member", "isAdmin", role_id, member_id) VALUES ($1, $2, true, $3, $4)
> ```

Wait, is this right? This can run in a 22.2 cluster, before the columns have been added.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91517)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890, @benbardin, @knz, @rafiss, and @ZhouXing19)

___
*[`pkg/upgrade/upgrades/role_members_ids_migration.go` line 42 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/91517#-NIJKx-YACPhZQ1DzXBs:-NIJKx-YACPhZQ1DzXBt:blncygz) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd25722b412251ed4d46b425d4d28fe2cca574ab/pkg/upgrade/upgrades/role_members_ids_migration.go#L42)):*
> ```Go
> 
> const addIndexOnRoleIDToRoleMembersStmt = `
> CREATE INDEX role_members_role_id_idx ON system.role_members (role_id ASC)
> ```

I think these all need `if not exists`, right? Upgrades need to be idempotent.

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91517)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @benbardin, @knz, @rafiss, and @ZhouXing19)

___
*[`pkg/upgrade/upgrades/role_members_ids_migration.go` line 42 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/91517#-NIJKx-YACPhZQ1DzXBs:-NIJOkx55RmDSx5FmPcK:b-f4dsn9) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd25722b412251ed4d46b425d4d28fe2cca574ab/pkg/upgrade/upgrades/role_members_ids_migration.go#L42)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think these all need `if not exists`, right? Upgrades need to be idempotent.
</blockquote></details>

Idempotence is already provided by `hasIndex`,  which is the `schemaExistsFn` in the `operation` structs defined below. None of the other upgrades seem to use `IF NOT EXISTS` with `CREATE INDEX`, but I can add it anyway to be extra safe.

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91517)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @benbardin, @knz, @rafiss, and @ZhouXing19)

___
*[`pkg/clusterversion/cockroach_versions.go` line 610 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/91517#-NIIoUTuBpEsuQ56E0YE:-NIJUOQjBHUTjaZCnDaO:b-7vkund) ([raw file](https://github.com/cockroachdb/cockroach/blob/8629d41699da1654ee4771f424c5bb5667c8df90/pkg/clusterversion/cockroach_versions.go#L610)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I believe Raphael said two versions, not 3 ("version 1" in that list is pre-existing). Like, why do the indexes need to be added in a separate upgrade?
</blockquote></details>

Ok I've moved the adding of the new indexes into the same upgrade as the columns being added.
___
*[`pkg/upgrade/upgrades/role_members_ids_migration.go` line 42 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/91517#-NIJKx-YACPhZQ1DzXBs:-NIJUqrcDJEckG2CSDiW:b-iw5bkz) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd25722b412251ed4d46b425d4d28fe2cca574ab/pkg/upgrade/upgrades/role_members_ids_migration.go#L42)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Idempotence is already provided by `hasIndex`,  which is the `schemaExistsFn` in the `operation` structs defined below. None of the other upgrades seem to use `IF NOT EXISTS` with `CREATE INDEX`, but I can add it anyway to be extra safe.
</blockquote></details>

Added now.

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91517)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @benbardin, @knz, @rafiss, and @ZhouXing19)

___
*[`pkg/upgrade/upgrades/permanent_upgrades.go` line 56 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/91517#-NIJIeD3ACI3Q29xcnvi:-NIYnCnFEuB0nkkUGc6e:b-nkz9jr) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd25722b412251ed4d46b425d4d28fe2cca574ab/pkg/upgrade/upgrades/permanent_upgrades.go#L56)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Wait, is this right? This can run in a 22.2 cluster, before the columns have been added.
</blockquote></details>

Discussed offline and this should be fixed by https://github.com/cockroachdb/cockroach/pull/93071. Will wait for that PR to be merged and then rebase before attempting to merge this PR.

**Comment by andyyang890** [comment]
bors r=rafiss

**Pull request merged**
