### PR TITLE
pkg/util/log: enable bufferedSink usage with fileSink as experimental

### PR DESCRIPTION
**Pull request by abarganier**
Informs: https://github.com/cockroachdb/cockroach/issues/72452

Epic: CRDB-35401

For some time, two buffering mechanisms have existed within the log
package. One is controlled by `buffered-writes`, which is only used by
the file sink. `buffered-writes` buffers writes until a buffer is full,
after which it flushes the buffer to an underlying file. This is not an
asynchronous operation.

Separately, the `bufferedSink` was introduced to provide an async
buffering mechanism. This was originally intended for network log sinks
such as the `fluentSink` and `httpSink`. Originally, the `bufferedSink`
was not allowed for use with the `fileSink` as we already had a
buffering mechanism available.

Today, we find ourselves in a situation where we aim to make CRDB even
more resilient in the face of disk failures. However, some of these
efforts like WAL failover are unable to achieve their goals if the
logging subsystem isn't resilient to disk unavailability as well.

Today, if a file sink is configured to write to an unavailable disk, any
goroutine making a logging call to one of those sinks will hang as the
underlying i/o operations used are unable to interact with the disk.
This can have a severe negative impact on cluster performance and
throughput, even when using `buffered-writes: true`.

As a way to alleviate this pain, this patch experimentally enables the
usage of the `bufferedSink` with the `fileSink`. The `bufferedSink` is
used to "wrap" an underlying sink (such as a `fileSink`), and
asynchronously outputs buffered data to said sink. It is especially good
at shielding writers from any problems with the underlying sink, which
makes it a great candidate to help us accomplish our resiliency goals
when it comes to disk outage scenarios.

Users can leverage the `bufferedSink` by using the `buffering` config option. 
For example:

```
file-defaults:
  buffered-writes: false
  buffering:
    max-staleness: 5s
    flush-trigger-size: 1.0MiB
    max-buffer-size: 50MiB
```

Note that we don't allow both `buffered-writes` and `buffering` to be
used together. This patch adds a validation step to ensure this.

Release note (ops change): Users have the ability to update their log
configuration to enable asynchronous buffering of `file-group` log
sinks via the `buffering` [configuration
options](https://www.cockroachlabs.com/docs/stable/configure-logs#log-buffering-for-network-sinks).

The `buffering` configuration can be applied to `file-defaults` or
individual `file-groups` as needed.

Note however that `buffering` and `buffered-writes` are incompatible for
the time being. If you'd like to try the `buffering` option on a file
log sink, it's necessary to explicitly set `buffered-writes: false`. For
example:
```
file-defaults:
  buffered-writes: false
  buffering:
    max-staleness: 1s
    flush-trigger-size: 256KiB
    max-buffer-size: 50MiB
```
We recommend a `max-staleness: 1s` and `flush-trigger-size: 256KiB` when
using this feature with file log sinks.

### CODE REVIEW

**Review by jbowens — APPROVED** [review]
:lgtm: assuming it looks good to @xinhaoz !

> Reviewed 5 of 5 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120428#-:-Nt2_TA2AsjPweGWp3Gv:b-gvoeg3)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @abarganier and @xinhaoz)

___
*[`-- commits` line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120428#-Nt2YyQO4j3C33ljAKvz):*
Since it's already opt-in, would we be able to avoid the additional environment variable requirement? It seems like something we could document for the `buffering` option.

Or, even more aggressively, could we not mark it as experimental but perhaps not document very loudly. Our WAL failover option will _not_ be considered experimental, so it's a bit unfortunate if we have to force them into using experimental options at the same time.

**Review by abarganier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120428)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @jbowens and @xinhaoz)

___
*[`-- commits` line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120428#-Nt2YyQO4j3C33ljAKvz):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Since it's already opt-in, would we be able to avoid the additional environment variable requirement? It seems like something we could document for the `buffering` option.

Or, even more aggressively, could we not mark it as experimental but perhaps not document very loudly. Our WAL failover option will _not_ be considered experimental, so it's a bit unfortunate if we have to force them into using experimental options at the same time.
</blockquote></details>

Let me discuss with the team, I'm open to ditching the env var and perhaps not advertising the feature quite yet.

**Review by abarganier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120428)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens and @xinhaoz)

___
*[`-- commits` line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120428#-Nt2YyQO4j3C33ljAKvz):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Let me discuss with the team, I'm open to ditching the env var and perhaps not advertising the feature quite yet.
</blockquote></details>

@jbowens envvar removed! We like the idea of not documenting this loudly. 

PTAL, and let us know how your testing goes.

**Review by jbowens — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120428#-:-NtMsce52rzjJVbfOaIn:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @abarganier and @xinhaoz)

___
*[`-- commits` line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120428#-Nt2YyQO4j3C33ljAKvz):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

@jbowens envvar removed! We like the idea of not documenting this loudly. 

PTAL, and let us know how your testing goes.
</blockquote></details>

Nice!

**Review by dhartunian — APPROVED** [review]
:lgtm: thank you for the detailed commit messages :100:. just a few wording nits.

> Reviewed 1 of 7 files at r3, 5 of 5 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120428#-:-NtNqhab4RxfiMD5PFLf:bi8j447)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @abarganier, @jbowens, and @xinhaoz)

___
*[`-- commits` line 82 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/120428#-NtNq0mB6amskHRtMP5c):*
nit: grammar
___
*[`pkg/util/log/logconfig/testdata/validate` line 797 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/120428#-NtNpuP0BTzJ1V3bbhip:-NtNpuP1-wficCLQLpKp:b-x1attm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0831494eaa84dc4a489f666c050b765c4320e81/pkg/util/log/logconfig/testdata/validate#L797)):*
> ```
>   max-group-size: 100MiB
> 
> # Check that buffering works with file sinks when the correct env var is set.
> ```

nit: remove reference to env var

**Review by abarganier — COMMENTED** [review]
TFTRs!

I've created https://github.com/cockroachdb/cockroach/issues/120759 to track follow up work to enable this feature in roachtests, to help put the new config option through its paces.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120428#-:-NtRNmEdCguKj_T5PeVK:bbz39w9)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @dhartunian, @jbowens, and @xinhaoz)

___
*[`-- commits` line 82 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/120428#-NtNq0mB6amskHRtMP5c):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: grammar
</blockquote></details>

Done.

**Review by abarganier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120428)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @dhartunian, @jbowens, and @xinhaoz)

___
*[`pkg/util/log/logconfig/testdata/validate` line 797 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/120428#-NtNpuP0BTzJ1V3bbhip:-NtRP5_q2sfQr9ZwbdJc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0831494eaa84dc4a489f666c050b765c4320e81/pkg/util/log/logconfig/testdata/validate#L797)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: remove reference to env var
</blockquote></details>

Done.

**Comment by abarganier** [comment]
bors r=dhartunian,jbowens

**Pull request merged**
