### PR TITLE
sql/parser: grammar refactorings

### PR DESCRIPTION
**Pull request by knz**
This patchset is yet a smaller subset of #16295, which is itself a subset of #13540.

Most of the changes are neutral except for the following:

- tracing syntax changes (see commit message below for details):
  - `SHOW SESSION TRACE` -> `SHOW TRACE FOR SESSION`
  - `SET/SHOW TRACE` -> `SET/SHOW TRACING`
- tiny bug fix in the syntax for CREATE USER

### CODE REVIEW

**Comment by jordanlewis** [comment]
:lgtm: assuming you have general approval for the tracing syntax change from the proper stakeholders. Nice job on this and thank you for making the commits so nice and atomic. 

One minor concern I have is `goyacc` - I wonder if introducing all of these new productions will have an effect on parsing latency or more importantly edge us closer to some kind of catastrophic `goyacc` max limit on the number of production rules :)

---

Reviewed 15 of 15 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, 3 of 3 files at r6, 2 of 2 files at r7, 2 of 2 files at r8, 2 of 2 files at r9, 2 of 2 files at r10, 2 of 2 files at r11, 2 of 2 files at r12, 1 of 1 files at r13, 2 of 2 files at r14.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/sql.y, line 1368 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/17033#-Kp7X_WBMEXtMSwqjjpo:-Kp7X_WBMEXtMSwqjjpp:bgkwqgz) ([raw file](https://github.com/cockroachdb/cockroach/blob/db58d7b615698ea4637d72f3d07b202359f0bec1/pkg/sql/parser/sql.y#L1368)):*
> ```Yacc
> | show_stmt
> | explain_stmt { /* SKIP DOC */ }
> ```

this one isn't alphabetized :) but maybe on purpose because of the skip doc

---

*[pkg/sql/parser/sql.y, line 3045 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/17033#-Kp7ZPX46rGzDKC8OKgc:-Kp7ZPX5jYcL0OCNyENI:bnelgbv) ([raw file](https://github.com/cockroachdb/cockroach/blob/859a139d19745a77b5ae43ab9a37e8c3854cf8cf/pkg/sql/parser/sql.y#L3045)):*
> ```Yacc
>   }
> | values_clause
> | table_clause
> ```

Why split `table_clause` out? Seems fine but I'm just curious since no one else seems to use it yet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17033#-:-Kp7Zf7wPx4BqzCdQMxg:b8m3h7d)*

**Comment by knz** [comment]
Thanks for your feedback. Indeed the additional productions introduce more states, but because the token lengths of the productions is the same there will not be any more latency (merely a different path through the state machine). 
I do not know what the limits are on the number of productions, but this rearrangement is very much necessary if we want #16295 and #13540 to eventually land. 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/sql.y, line 1368 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/17033#-Kp7X_WBMEXtMSwqjjpo:-Kp89HxYQu8hAqim7pTj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/db58d7b615698ea4637d72f3d07b202359f0bec1/pkg/sql/parser/sql.y#L1368)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

this one isn't alphabetized :) but maybe on purpose because of the skip doc
</blockquote></details>

Done.

---

*[pkg/sql/parser/sql.y, line 3045 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/17033#-Kp7ZPX46rGzDKC8OKgc:-Kp89MhE4uBh_raPkpDh:b8s91cc) ([raw file](https://github.com/cockroachdb/cockroach/blob/859a139d19745a77b5ae43ab9a37e8c3854cf8cf/pkg/sql/parser/sql.y#L3045)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Why split `table_clause` out? Seems fine but I'm just curious since no one else seems to use it yet.
</blockquote></details>

It's used in #16295.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17033#-:-Kp89QGg6tfILqRYmWV2:bgpmj4i)*

**Comment by RaduBerinde** [comment]
LGTM
CC @andreimatei so he's aware of https://github.com/cockroachdb/cockroach/pull/17033/commits/d0aec2d5b0766a59d545c77c38c06095421f90b2

**Comment by knz** [comment]
TFYR!

**Pull request merged**
