### PR TITLE
server: add diagnostics support for tenants

### PR DESCRIPTION
**Pull request by andy-kimball**
Previously, SQL-only tenants did not report feature usage to the registration
server. This commit adds that support via the creation of a new diagnostics
package that encapsulates the usage report code in updates.go.

However, since this commit needs to be backported to 20.2, the new code is
*only* used with tenants, and is side-by-side with the existing code, which
will continue to operate as before. A follow-on commit (that will not be
backported) will fully replace the old implementation with the new.

Release note (sql change): Multi-tenant clusters will now send anonymous usage
information to the central CRDB registration server.

### CODE REVIEW

**Review by miretskiy — COMMENTED** [review]
:lgtm: for bulkio files

> Reviewed 3 of 20 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58399#-:-MPzzMgu5G_B_wqcdM6o:b-9xeikr)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by andy-kimball** [comment]
Note that I've got a follow-on PR in progress to begin using this new code in the existing Server use case as well. This PR is meant to contain the minimal changes needed for tenants, so that it can be back-ported.

**Review by tbg — APPROVED** [review]
> Reviewed 1 of 20 files at r3, 23 of 23 files at r4, 25 of 25 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58399)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @dt, and @knz)

___
*[pkg/server/server_sql.go, line 859 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/58399#-MQHaHoG9tOlRMA4fuxG:-MQHaHoG9tOlRMA4fuxH:b-ucuk5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/47cf595a91c8fc09fe7c8cc6eab07b162d3873c8/pkg/server/server_sql.go#L859)):*
> ```Go
> 
> // StartDiagnostics starts periodic diagnostics reporting.
> // NOTE: This is not called in preStart so that it's disable by default for
> ```

disabled
___
*[pkg/server/diagnostics/reporter.go, line 206 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/58399#-MQHasH_6-QCEkngPWA1:-MQHasH_6-QCEkngPWA2:b-o2bu0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/47cf595a91c8fc09fe7c8cc6eab07b162d3873c8/pkg/server/diagnostics/reporter.go#L206)):*
> ```Go
> 		}
> 	} else {
> 		info.SQL = r.collectSQLInfo(ctx)
> ```

There's no value in reporting this also for the system tenants, right? Mind adding a comment why not? I think the protobuf also doesn't tell us that this will be left blank by non-tenants (though it does mention that node info is left blank by tenants).
___
*[pkg/server/diagnostics/reporter_test.go, line 97 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/58399#-MQHbbQ949DY332jawO6:-MQHbbQ949DY332jawO7:b-t2x1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/47cf595a91c8fc09fe7c8cc6eab07b162d3873c8/pkg/server/diagnostics/reporter_test.go#L97)):*
> ```Go
> }
> 
> // TestServer checks nodes, stores, localities, and zone configs. Telemetry
> ```

TestServerReport

**Comment by andy-kimball** [comment]
___
*[pkg/server/diagnostics/reporter.go, line 206 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/58399#-MQHasH_6-QCEkngPWA1:-MQI4HfH6cA8Lq0vgLPS:bhg1bj7) ([raw file](https://github.com/cockroachdb/cockroach/blob/47cf595a91c8fc09fe7c8cc6eab07b162d3873c8/pkg/server/diagnostics/reporter.go#L206)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

There's no value in reporting this also for the system tenants, right? Mind adding a comment why not? I think the protobuf also doesn't tell us that this will be left blank by non-tenants (though it does mention that node info is left blank by tenants).
</blockquote></details>

I went back and forth on this, and wanted to have a discussion on the best way forward here. I could see other fields in `NodeInfo` also being useful in `SQLInstanceInfo` (e.g. `OSInfo`, `HardwareInfo`, `Locality`, etc.). I could even see `SQLInstanceID` being useful for system tenants, if we ever make it different from `NodeID`. However, I also don't like idea of including environment related fields twice in the same report, once in `NodeInfo` and again in `SQLInstanceInfo`. Probably if I were starting from scratch, I'd have a separate `Environment` field where we put `OSInfo`, `BuildInfo`, `Locality`, etc. And then `NodeInfo` and `SQLInstanceInfo` would just contain fields specific to CRDB nodes and SQL-only instances, respectively. It's just painful to do that now, and I'm not sure it's worth the effort. So I thought I'd just duplicate the fields and then we could factor out a separate `Environment` field if we later see that to be compelling.

Do you or others on this PR have an opinion?

**Comment by andy-kimball** [comment]
___
*[pkg/server/diagnostics/reporter_test.go, line 97 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/58399#-MQHbbQ949DY332jawO6:-MQI8qiJELuA0TphK_M9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/47cf595a91c8fc09fe7c8cc6eab07b162d3873c8/pkg/server/diagnostics/reporter_test.go#L97)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

TestServerReport
</blockquote></details>

Done.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58399)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dt, @knz, and @tbg)

___
*[pkg/server/server_sql.go, line 859 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/58399#-MQHaHoG9tOlRMA4fuxG:-MQI4D9t-4cBD4-jj15N:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/47cf595a91c8fc09fe7c8cc6eab07b162d3873c8/pkg/server/server_sql.go#L859)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

disabled
</blockquote></details>

Done.
___
*[pkg/server/diagnostics/reporter.go, line 206 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/58399#-MQHasH_6-QCEkngPWA1:-MQJidflAV2maGqqOXzB:b-ohyd5h) ([raw file](https://github.com/cockroachdb/cockroach/blob/47cf595a91c8fc09fe7c8cc6eab07b162d3873c8/pkg/server/diagnostics/reporter.go#L206)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I went back and forth on this, and wanted to have a discussion on the best way forward here. I could see other fields in `NodeInfo` also being useful in `SQLInstanceInfo` (e.g. `OSInfo`, `HardwareInfo`, `Locality`, etc.). I could even see `SQLInstanceID` being useful for system tenants, if we ever make it different from `NodeID`. However, I also don't like idea of including environment related fields twice in the same report, once in `NodeInfo` and again in `SQLInstanceInfo`. Probably if I were starting from scratch, I'd have a separate `Environment` field where we put `OSInfo`, `BuildInfo`, `Locality`, etc. And then `NodeInfo` and `SQLInstanceInfo` would just contain fields specific to CRDB nodes and SQL-only instances, respectively. It's just painful to do that now, and I'm not sure it's worth the effort. So I thought I'd just duplicate the fields and then we could factor out a separate `Environment` field if we later see that to be compelling.

Do you or others on this PR have an opinion?
</blockquote></details>

I thought about this more, and decided to just bite the bullet and separate out those fields into a new `Env` field. This will mean more complex changes to the Registration service, but it will probably save time in the long-term, b/c PM's will probably eventually want all those environment-related fields anyway.

PTAL at the new changes I made.

**Review by tbg — APPROVED** [review]
:lgtm:

> Reviewed 29 of 29 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58399#-:-MQMvvnhCpo1deY0z2gJ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @dt, @knz, and @tbg)

___
*[pkg/server/diagnostics/reporter.go, line 295 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/58399#-MQMujZc661KN6DjQ2EA:-MQMujZc661KN6DjQ2EB:b2nhz65) ([raw file](https://github.com/cockroachdb/cockroach/blob/6eb1ce6991bad8d126d173a0749a38640d90e40b/pkg/server/diagnostics/reporter.go#L295)):*
> ```Go
> 	// TODO(andyk): Remove this code once the registration server gets this
> 	// information from the other fields.
> 	info.Node.Locality = info.Env.Locality
> ```

asd

**Pull request merged**
