### PR TITLE
rowexec: use streamer for lookup joins with no ordering

### PR DESCRIPTION
**Pull request by yuzefovich**
**row: fix the usage of Get requests with the streamer in some cases**

Previously, `TxnKVStreamer` processed the Get responses under the
assumption that `nil` `enqueueKeys` argument was provided. In such
a scenario, `EnqueueKeysSatisfied` contained an ordinal into the
original spans slice that is needed to process the Get response
correctly. We will shortly expand the usage of the Streamer to use
non-nil `enqueueKeys` argument which breaks that assumption. We go
around it by exporting `Result.Position` value which tracks exactly the
information we need.

Release note: None

**rowexec: use streamer for lookup joins with no ordering**

This commit expands the usage of the Streamer to lookup joins when
ordering doesn't have to be maintained. We can do so easily since the
join reader span generators de-duplicate spans, so the Streamer will
only be asked to process unique requests.

In theory, we should be able to do the same for the cases when ordering
needs to be maintained, but `InOrder` mode of the Streamer currently has
known bugs / limitations when a single request can result in multiple
rows - this wasn't an issue for the index joins since those are
guaranteed to get a single row for each request.

Also, we want to push the de-duplication logic from the join reader into
the Streamer (in order to inform the behavior of the yet-to-be-added
cache in the Streamer), but that will come after addressing the known
`InOrder` bugs mentioned above.

Some adjustments were needed:
- In order to improve the behavior with low `workmem` limit (in
particular, `regional_by_row` CCL logic test file was erroring out) of
the join reader we now make the batch size hint at most 1/12 of the
limit while giving the streamer the same three quarters - this allows
for other in-memory state of the join reader itself to have some space.
- One lookup join unit test is designed with the non-streamer code path
in mind, so we disable the usage of the streamer there.
- `lookup_join_trace` execbuilder file needed to filter out messages
produced by the range cache.

Out of curiosity, I decided to do a quick comparison of TPCH numbers
with the Streamer `off` (first column) and `on` (second column)
(negative numbers indicate the latency reduction, positive - latency
increase):
```
Q1:   3.78s  3.28s -13.36%
Q2:   0.19s  0.19s  2.11%
Q3:   1.72s  1.48s -13.89%
Q4:   1.57s  1.25s -20.54%
Q5:   2.74s  2.49s -9.06%
Q6:   6.36s  8.19s  28.74%
Q7:   6.97s  7.35s  5.42%
Q8:   1.00s  1.09s  8.68%
Q9:   6.52s  6.93s  6.32%
Q10:  1.93s  1.63s -15.60%
Q11:  0.52s  0.57s  9.06%
Q12:  7.16s  8.89s  24.17%
Q13:  1.17s  1.13s -3.43%
Q14:  0.57s  0.66s  13.91%
Q15:  4.83s  5.53s  14.34%
Q16:  0.81s  0.78s -4.08%
Q17:  0.48s  0.48s  0.84%
Q18:  5.61s  5.33s -4.96%
Q19:  3.86s  3.41s -11.83%
Q20: 12.00s 14.37s  19.79%
Q21:  9.33s  7.24s -22.38%
Q22:  0.57s  0.55s -4.03%
```
This mostly confirms our expectations - lookup joins should get faster
since we now parallelize the lookups. Index joins already get parallel
lookups in the old code path, so we have some regressions. Notably, Q6
and Q12 spend most of the time performing index joins and Q20 is
dominated by an index join and a parallelizable (when lookup columns
form a key) lookup joins.

Addresses: #54680

Release note: None

**sql: don't sort spans redundantly when using the streamer**

This commit makes it so that the lookup and index joins don't sort the
spans when the ordering doesn't have to be maintained and the Streamer
API is used - the Streamer itself performs the sort of spans within
single-range batches, so the caller's sort is redundant.

Release note: None

### CODE REVIEW

**Review by rharding6373 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80141)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft and @yuzefovich)

___
*[`-- commits` line 19 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80141#-N0l4Oz7BoVKwU7UCrg2):*
Are there tests for the new functionality?
___
*[`pkg/sql/rowexec/joinreader.go` line 460 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80141#-N0l36uS-LgHvnQuPzqI:-N0l36uS-LgHvnQuPzqJ:b-c517h7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2872e89f3b45eadb3a3c9ae3d37d9eb549e6917e/pkg/sql/rowexec/joinreader.go#L460)):*
> ```Go
> 		// - the input batch (i.e. buffered input rows) which is limited by the
> 		//   batch size hint;
> 		// - some in-memory state of the join reader strategy;
> ```

Do these only use extra memory in certain modes? Should we be more fine-grained about how to allocate the memory so that we can have a larger memory limit for batchSizeBytes where possible?

I'm not sure if it's a good idea, but it may be worth some discussion.

**Review by yuzefovich — COMMENTED** [review]
Added another commit with some cleanup.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80141#-:-N0lwRi91QILYhGToBEn:bb30n8j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373 and @rytaft)

___
*[`-- commits` line 19 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80141#-N0l4Oz7BoVKwU7UCrg2):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Are there tests for the new functionality?
</blockquote></details>

Yes, lookup joins are ubiquitous in our CI, and since the streamer is on by default on master, it gets exercised plenty. I did add a test for the case of large keys which seems useful.
___
*[`pkg/sql/rowexec/joinreader.go` line 460 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80141#-N0l36uS-LgHvnQuPzqI:-N0l60ay3E_YqPIJZTTz:b-sjgevm) ([raw file](https://github.com/cockroachdb/cockroach/blob/2872e89f3b45eadb3a3c9ae3d37d9eb549e6917e/pkg/sql/rowexec/joinreader.go#L460)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Do these only use extra memory in certain modes? Should we be more fine-grained about how to allocate the memory so that we can have a larger memory limit for batchSizeBytes where possible?

I'm not sure if it's a good idea, but it may be worth some discussion.
</blockquote></details>

See the second smaller comment I added below. This whole discussion occurs only for a scenario of low workmem limit and should never be really applicable to the production setting. Added an explicit callout in the beginning.

I think that we don't have to think too much about the case of a low workmem limit, and my goal with minor adjustments like this is to make the tests non flaky.

**Review by rharding6373 — APPROVED** [review]
:lgtm: Nice work!

> Reviewed 5 of 5 files at r3, 5 of 5 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80141#-:-N0qFYU06fDKOmsOEkdr:bcmw7ss)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft and @yuzefovich)

___
*[`-- commits` line 19 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80141#-N0l4Oz7BoVKwU7UCrg2):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Yes, lookup joins are ubiquitous in our CI, and since the streamer is on by default on master, it gets exercised plenty. I did add a test for the case of large keys which seems useful.
</blockquote></details>

:thumbsup: 
___
*[`pkg/sql/distsql_running.go` line 466 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/80141#-N0qDpnk4xfpK58mQr-L:-N0qDpnlCJR5S3XbMPTY:b-14d8en) ([raw file](https://github.com/cockroachdb/cockroach/blob/9911ed28f566df57d446ba0fc5eb918499d6778c/pkg/sql/distsql_running.go#L466)):*
> ```Go
> 			if jr := proc.Spec.Core.JoinReader; jr != nil {
> 				if jr.IsIndexJoin() || !jr.MaintainOrdering {
> 					// Index joins w/ and w/o order as well as lookup joins w/o
> ```

nit: spell out "with" and "without"

**Review by yuzefovich — COMMENTED** [review]
Made some adjustments to the large keys test.

TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80141#-:-N0qNfytAmZkmiwJxVUO:b-80fuyl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rharding6373, @rytaft, and @yuzefovich)

**Pull request merged**
