### PR TITLE
sql: add the string_agg aggregation function

### LINKED ISSUE #10495: sql: support aggregate functions with secondary arguments
We need aggregates with secondary arguments, 
needed to implement the more general function STRING_AGG (
https://www.postgresql.org/docs/9.2/static/functions-aggregate.html ) - #26737

Implementation-wise we could assume as a startin point that aggregation occurs always on the first argument; and use the values after the first as initializer arguments for the aggregate function object.

### PR DESCRIPTION
**Pull request by BramGruneir**
This function is similar to concat_agg but it takes a delimiter as a secondary
argument. Previously, we were not able to handle aggregations with more than
one argument before. To allow for this, without getting into the messy world of
multi-column aggregators, all arguments after the first one in an aggregator
must be constant expressions.

This in turn required updating the aggregator functions to now also take
argument datums as an new argument.

For distsql, the arguments are stored as expressions that have already been
checked to ensure that they are constants.

It looks like concat_agg (and now string_agg) are not run in distsql yet, so
this will be added next.

This work is primarily motivated by the need for greater ORM compatibility.

Closes #10495, #26737

Release note (sql change): Added the new aggregation function string_agg that
concats a collection of strings into a single string and seperates them with the
passed in delimiter.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
I think it's best to not support it in the optimizer for now (as long as it falls back to the heuristic planner), and we can work on the opt support separately. It will require a new operator and some changes on the execution side.

**Review by knz — CHANGES_REQUESTED** [review]
Thank you for this. 

@asubiotto can you check the distsql execution changes? thanks

Bram please also:
1) file a followup issue that says "for now aggregate functions that take secondary arguments only accept constant expresssions in the 2nd argument and furter". mark it as bug, pgcompat, milestone 2.2, and known-limitation + docs-todo with cc to Jesse to call this out in the release notes / known limitation bug.
2) link to that follow-up issue as indicated in my comment below

> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-:-LJSNiXS01btlvYTZ72K:b-rp21i1)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/group.go, line 455 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-LJSKw7kEFAZ92r5mizU:-LJSKw7l7p17fPw_W79X:bb96q4r) ([raw file](https://github.com/cockroachdb/cockroach/blob/83f08d5fdc1c0a597afe8be2d653f87351f6fef1/pkg/sql/group.go#L455)):*
> ```Go
> 			// In most cases the result is NULL but there are exceptions
> 			// (like COUNT).
> 			aggregateFunc = f.create(params.EvalContext(), nil)
> ```

here and below add a comment inside the argument list to indicate which argument is receiving the `nil` reference.
___
*[pkg/sql/group.go, line 653 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-LJSLGTR366LAk2nrWn9:-LJSLGTR366LAk2nrWnA:b76ur1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/83f08d5fdc1c0a597afe8be2d653f87351f6fef1/pkg/sql/group.go#L653)):*
> ```Go
> 					evalContext := v.planner.EvalContext()
> 					for i := 1; i < len(t.Exprs); i++ {
> 						if _, ok := t.Exprs[i].(tree.VariableExpr); ok {
> ```

This check of VariableExpr is not doing what you think it does. An expression of the form e.g. `(x + 3)` is a BinaryExpr, and is not a VariableExpr. I think you need to use `tree.IsConst`.
___
*[pkg/sql/group.go, line 654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-LJSOHFa-xRktyUYW4pu:-LJSOHFa-xRktyUYW4pv:b7yvlmw) ([raw file](https://github.com/cockroachdb/cockroach/blob/83f08d5fdc1c0a597afe8be2d653f87351f6fef1/pkg/sql/group.go#L654)):*
> ```Go
> 					for i := 1; i < len(t.Exprs); i++ {
> 						if _, ok := t.Exprs[i].(tree.VariableExpr); ok {
> 							v.err = pgerror.UnimplementedWithIssueError(10495, "aggregate functions with multiple non-constant expressions are not supported")
> ```

Update the issue number with the new issue number as indicated at the top.
___
*[pkg/sql/group.go, line 661 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-LJSL85g0FxkDLQW4OsU:-LJSL85g0FxkDLQW4OsV:b-oe02m0) ([raw file](https://github.com/cockroachdb/cockroach/blob/83f08d5fdc1c0a597afe8be2d653f87351f6fef1/pkg/sql/group.go#L661)):*
> ```Go
> 						if err != nil {
> 							v.err = pgerror.NewErrorf(pgerror.CodeInternalError,
> 								"Can't evaluate %s", t.Exprs[i].String())
> ```

1) lowercase error message + prefix with "programming error: "

2) don't drop the `err` you received from `Eval` on the floor, instead format it inside the pg error with `%v`
___
*[pkg/sql/opt_exec_factory.go, line 350 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-LJSLm-E5qHbtNNw1w3K:-LJSLm-E5qHbtNNw1w3L:b-leta2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/83f08d5fdc1c0a597afe8be2d653f87351f6fef1/pkg/sql/opt_exec_factory.go#L350)):*
> ```Go
> 			int(idx),
> 			builtins.NewAnyNotNullAggregate,
> 			nil,
> ```

comment to explain which argument receives `nil`
___
*[pkg/sql/opt_exec_factory.go, line 377 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-LJSLqGa8sfuTPb_WQGk:-LJSLqGa8sfuTPb_WQGl:bxd8qr1) ([raw file](https://github.com/cockroachdb/cockroach/blob/83f08d5fdc1c0a597afe8be2d653f87351f6fef1/pkg/sql/opt_exec_factory.go#L377)):*
> ```Go
> 
> 		default:
> 			// *****************  All the rest here...
> ```

Add a TODO here instead of all the asterisks.
___
*[pkg/sql/opt_exec_factory.go, line 386 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-LJSLpU5EJvUWza7rbu1:-LJSLpU65SHsWAFgLxtw:bdmkv7n) ([raw file](https://github.com/cockroachdb/cockroach/blob/83f08d5fdc1c0a597afe8be2d653f87351f6fef1/pkg/sql/opt_exec_factory.go#L386)):*
> ```Go
> 			renderIdx,
> 			aggFn,
> 			nil,
> ```

ditto comment for arg

**Review by rytaft — COMMENTED** [review]
I agree with @RaduBerinde regarding holding off on optimizer support.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-:-LJToRnC8LYyMuo683n-:b-scvp6p)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by yuzefovich — CHANGES_REQUESTED** [review]
Very nice work!

Currently, `string_agg` will not behave correctly when used as a window function, but it's very easy to fix, I believe (please see my comments below).

Also, it would be great to include a couple of tests for this case when `string_agg` is used as a window function. Here is an example query:
`SELECT company_id, string_agg(employee, ',') OVER (PARTITION BY company_id) FROM string_agg_test ORDER BY company_id;`. Feel free to ask me about window functions.

> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-:-LJU3EHZDSjeNgNZ73RS:b-oeh1uz)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 330 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-LJU0lP2BvfHmnIl7Sxp:-LJU0lP2BvfHmnIl7Sxq:b-ttmd8x) ([raw file](https://github.com/cockroachdb/cockroach/blob/83f08d5fdc1c0a597afe8be2d653f87351f6fef1/pkg/sql/sem/builtins/aggregate_builtins.go#L330)):*
> ```Go
> 		AggregateFunc: f,
> 		WindowFunc: func(params []types.T, evalCtx *tree.EvalContext) tree.WindowFunc {
> 			aggWindowFunc := f(params, evalCtx, nil)
> ```

This should be `arguments` not `nil`.
___
*[pkg/sql/sem/builtins/window_builtins.go, line 182 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-LJU2WwJ7BaBG0RFg75c:-LJU2WwJ7BaBG0RFg75d:b-rl736m) ([raw file](https://github.com/cockroachdb/cockroach/blob/83f08d5fdc1c0a597afe8be2d653f87351f6fef1/pkg/sql/sem/builtins/window_builtins.go#L182)):*
> ```Go
> // NewAggregateWindowFunc creates a constructor of aggregateWindowFunc
> // with agg initialized by provided aggConstructor.
> func NewAggregateWindowFunc(
> ```

nit: currently this function is used only once to create a constructor for an aggregate that takes no arguments. It might be worth adding a comment here saying that if this function is to be used for creating a constructor for aggregates that do take arguments, `nil` below will need to be replaced by those arguments.
___
*[pkg/sql/sem/builtins/window_builtins.go, line 260 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-LJU1Y099L938rxnBccR:-LJU1Y099L938rxnBccS:bi7tu2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/83f08d5fdc1c0a597afe8be2d653f87351f6fef1/pkg/sql/sem/builtins/window_builtins.go#L260)):*
> ```Go
> 	// and construct a new one for the computation.
> 	w.agg.Close(ctx, evalCtx)
> 	*w.agg = aggregateWindowFunc{w.aggConstructor(evalCtx, nil), tree.DNull}
> ```

This should not be `nil` in all cases. For `string_agg` we need to store the arguments and invoke the constructor using those stored arguments. Consider adding a field for that in `framableAggregateWindowFunc`.

**Review by asubiotto — COMMENTED** [review]
Sorry for the late review, this slipped through the cracks. The sql execution side of things look good to me but I'd like @jordanlewis to take a look in case I've missed something.

The biggest thing that stands out to me is the addition of the arguments parameter to all aggregation functions regardless of whether or not they need it. Off the top of my head we could have a separate interface `initAggFuncArgs` implemented only by the aggregation functions which could be checked and used at construction time. This might not be the best way but it might be worth thinking about. On the other hand, I see we have some other unused parameters so it might not be a big deal.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-:-LJoSWqk6SOdywMtoyVx:b9t9mit)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 543 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-LJoRdnt2VA4ndPDVLDb:-LJoRdnt2VA4ndPDVLDc:bl216az) ([raw file](https://github.com/cockroachdb/cockroach/blob/29029d22f8b6e91cf1f5851fa8bda826f046e527/pkg/sql/sem/builtins/aggregate_builtins.go#L543)):*
> ```Go
> 		acc:      evalCtx.Mon.MakeBoundAccount(),
> 	}
> 	if len(arguments) == 1 {
> ```

Not sure whether it would be better to panic here if you get an unexpected number of arguments

**Review by BramGruneir — COMMENTED** [review]
PTAL, string_agg now works as a window function.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-:-LJollxM3w9qjz24TLKJ:b-acebq2)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/group.go, line 455 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-LJSKw7kEFAZ92r5mizU:-LJVRI8hAHx6jqNg4w4K:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83f08d5fdc1c0a597afe8be2d653f87351f6fef1/pkg/sql/group.go#L455)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

here and below add a comment inside the argument list to indicate which argument is receiving the `nil` reference.
</blockquote></details>

Done.
___
*[pkg/sql/group.go, line 653 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-LJSLGTR366LAk2nrWn9:-LJVRt1wAMlvWUWvDF9A:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83f08d5fdc1c0a597afe8be2d653f87351f6fef1/pkg/sql/group.go#L653)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This check of VariableExpr is not doing what you think it does. An expression of the form e.g. `(x + 3)` is a BinaryExpr, and is not a VariableExpr. I think you need to use `tree.IsConst`.
</blockquote></details>

Done.
___
*[pkg/sql/group.go, line 654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-LJSOHFa-xRktyUYW4pu:-LJVRvf93ATYokHxAwjC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83f08d5fdc1c0a597afe8be2d653f87351f6fef1/pkg/sql/group.go#L654)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Update the issue number with the new issue number as indicated at the top.
</blockquote></details>

Done.
___
*[pkg/sql/group.go, line 661 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-LJSL85g0FxkDLQW4OsU:-LJVS5VvDbpGpO2sHob-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83f08d5fdc1c0a597afe8be2d653f87351f6fef1/pkg/sql/group.go#L661)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

1) lowercase error message + prefix with "programming error: "

2) don't drop the `err` you received from `Eval` on the floor, instead format it inside the pg error with `%v`

</blockquote></details>

Done.
___
*[pkg/sql/opt_exec_factory.go, line 350 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-LJSLm-E5qHbtNNw1w3K:-LJVSG0i508_zED5isSO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83f08d5fdc1c0a597afe8be2d653f87351f6fef1/pkg/sql/opt_exec_factory.go#L350)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

comment to explain which argument receives `nil`
</blockquote></details>

Done.
___
*[pkg/sql/opt_exec_factory.go, line 377 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-LJSLqGa8sfuTPb_WQGk:-LJVSGzD1-jOtpsH5eMO:b-yz3ggx) ([raw file](https://github.com/cockroachdb/cockroach/blob/83f08d5fdc1c0a597afe8be2d653f87351f6fef1/pkg/sql/opt_exec_factory.go#L377)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Add a TODO here instead of all the asterisks.
</blockquote></details>

was just a leftover note to myself, removed.
___
*[pkg/sql/opt_exec_factory.go, line 386 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-LJSLpU5EJvUWza7rbu1:-LJVSSfN6fQl5DEP6N_q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83f08d5fdc1c0a597afe8be2d653f87351f6fef1/pkg/sql/opt_exec_factory.go#L386)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto comment for arg
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 330 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-LJU0lP2BvfHmnIl7Sxp:-LJVbSlU6leHIDSDa0fS:b9hpp9o) ([raw file](https://github.com/cockroachdb/cockroach/blob/83f08d5fdc1c0a597afe8be2d653f87351f6fef1/pkg/sql/sem/builtins/aggregate_builtins.go#L330)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

This should be `arguments` not `nil`.
</blockquote></details>

Window functions now work correctly.
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 543 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-LJoRdnt2VA4ndPDVLDb:-LJolUw3ALFMNtgTARx_:bytk164) ([raw file](https://github.com/cockroachdb/cockroach/blob/29029d22f8b6e91cf1f5851fa8bda826f046e527/pkg/sql/sem/builtins/aggregate_builtins.go#L543)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Not sure whether it would be better to panic here if you get an unexpected number of arguments
</blockquote></details>

Hmm... I can add that.
___
*[pkg/sql/sem/builtins/window_builtins.go, line 182 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-LJU2WwJ7BaBG0RFg75c:-LJVcGKE8382DivdpVAU:bx3s3jb) ([raw file](https://github.com/cockroachdb/cockroach/blob/83f08d5fdc1c0a597afe8be2d653f87351f6fef1/pkg/sql/sem/builtins/window_builtins.go#L182)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: currently this function is used only once to create a constructor for an aggregate that takes no arguments. It might be worth adding a comment here saying that if this function is to be used for creating a constructor for aggregates that do take arguments, `nil` below will need to be replaced by those arguments.
</blockquote></details>

This now works but there was no need to edit this function.
___
*[pkg/sql/sem/builtins/window_builtins.go, line 260 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-LJU1Y099L938rxnBccR:-LJolgEJ2i6QrF_IljTd:bx3s3jb) ([raw file](https://github.com/cockroachdb/cockroach/blob/83f08d5fdc1c0a597afe8be2d653f87351f6fef1/pkg/sql/sem/builtins/window_builtins.go#L260)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

This should not be `nil` in all cases. For `string_agg` we need to store the arguments and invoke the constructor using those stored arguments. Consider adding a field for that in `framableAggregateWindowFunc`.
</blockquote></details>

This now works but there was no need to edit this function.

**Review by yuzefovich — APPROVED** [review]
:lgtm: with a nit

> Reviewed 2 of 2 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-:-LJovgOI5X-Q50LENtO_:b-d5ftqp)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/sem/builtins/window_builtins.go, line 260 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-LJU1Y099L938rxnBccR:-LJor1yO0AhYKhPCz69M:bo8xtvp) ([raw file](https://github.com/cockroachdb/cockroach/blob/83f08d5fdc1c0a597afe8be2d653f87351f6fef1/pkg/sql/sem/builtins/window_builtins.go#L260)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

This now works but there was no need to edit this function.
</blockquote></details>

Great!

This should actually be `nil` now.
___
*[pkg/sql/sem/builtins/window_builtins.go, line 240 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-LJovLeM7Gwb8vuOl5Es:-LJovLeM7Gwb8vuOl5Et:b-4drorp) ([raw file](https://github.com/cockroachdb/cockroach/blob/599dc1928163b46516eeb4f788f844efd06e1beb/pkg/sql/sem/builtins/window_builtins.go#L240)):*
> ```Go
> 	aggConstructor func(*tree.EvalContext, tree.Datums) tree.AggregateFunc
> 	shouldReset    bool
> 	arguments      tree.Datums
> ```

I think we don't need `arguments` field anymore.

**Review by BramGruneir — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28392)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 543 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-LJoRdnt2VA4ndPDVLDb:-LJsxWLh8URAyKL3N4vu:b5mavvy) ([raw file](https://github.com/cockroachdb/cockroach/blob/29029d22f8b6e91cf1f5851fa8bda826f046e527/pkg/sql/sem/builtins/aggregate_builtins.go#L543)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Hmm... I can add that.
</blockquote></details>

Added a panic everywhere were argument counts could be wrong.
___
*[pkg/sql/sem/builtins/window_builtins.go, line 260 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-LJU1Y099L938rxnBccR:-LJsvXhA9eBZJqhsN8Y2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83f08d5fdc1c0a597afe8be2d653f87351f6fef1/pkg/sql/sem/builtins/window_builtins.go#L260)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Great!

This should actually be `nil` now.
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/window_builtins.go, line 240 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-LJovLeM7Gwb8vuOl5Es:-LJstXXE2mnln-ke51F-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/599dc1928163b46516eeb4f788f844efd06e1beb/pkg/sql/sem/builtins/window_builtins.go#L240)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think we don't need `arguments` field anymore.
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
:lgtm: modulo a missing unimplemented issue link

> Reviewed 1 of 2 files at r2, 1 of 3 files at r3, 10 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-:-LJt-MM722QaShxHovQV:bhiawy4)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt_exec_factory.go, line 377 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-LJszMeI0RaQWP9atuP5:-LJszMeJ7M0X7I0uuhaw:b-trhrvp) ([raw file](https://github.com/cockroachdb/cockroach/blob/71982277997daad5a7800d9001a8d59fed0e381f/pkg/sql/opt_exec_factory.go#L377)):*
> ```Go
> 
> 		default:
> 			return nil, errors.Errorf("multi-argument aggregation functions not implemented")
> ```

pgerror + unimplemented with issue link

**Review by knz — COMMENTED** [review]
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28392)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Review by BramGruneir — COMMENTED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28392#-:-LJt0A97DpsWg4_fqDl9:b-hay2ix)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Review by knz — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28392)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Pull request merged**
