### PR TITLE
server: document point-in-time nature of tenant_ranges status endpoint

### LINKED ISSUE #99048: Document point-in-time nature of `/_status/tenant_ranges` endpoint results
**Is your feature request related to a problem? Please describe.**
The `/_status/tenant_ranges` endpoint provides metadata about ranges for a tenant that exist *at the time the request was processed*. 

The initial tenant creation process involves the creation of initial ranges, followed by an asynchronous process that splits ranges. If a user were to make a `/_status/tenant_ranges` immediately after tenant creation, it's possible that the client would receive a response containing a fewer number of ranges than they would receive if they made another request a short time after. This would be due to the asynchronous nature of this range splitting process.

Ranges are forever in a state of flux. Splitting, compaction, etc. are common operations that happen to ranges, and so this behavior should be intuitively expected by those who understand this. However, we should make this limitation clear in the documentation, to avoid potential confusion in scenarios such as the example one I gave above. 

**Describe the solution you'd like**
Update documentation to note this characteristic of the `/_status/tenant_ranges` endpoint.

**Additional context**
Informs https://github.com/cockroachdb/cockroach/pull/97386

Jira issue: CRDB-25678

Informs: https://github.com/cockroachdb/cockroach/issues/92979

### PR DESCRIPTION
**Pull request by mdlinville**
Fixes #99048 

Relates to [DOC-7271]

### CODE REVIEW

**Review by michae2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116514#-:-Nm7N_dp5_m85P8STB8p:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @abarganier)

**Review by abarganier — APPROVED** [review]
Apologies for the review lag, :lgtm:  - thank you @mdlinville! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116514#-:-Nmgj0-P56pUYl2iTCpV:b-vb9uhh)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2)

**Review by abarganier — COMMENTED** [review]
Hm, looking at the CI failures, we might need to run `dev gen` one more time?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116514#-:-NmgjFeR8PPYQHNmcH7l:bfc9w9n)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2)

**Comment by mdlinville** [comment]
> Hm, looking at the CI failures, we might need to run `dev gen` one more time?
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116514#-:-NmgjFeR8PPYQHNmcH7l:bfc9w9n)_ status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2)

Thanks for your patience with the churn. I think I've got it now!

**Comment by mdlinville** [comment]
@abarganier I do not have access to view the failed Bazel test logs.

**Comment by dt** [comment]
nit: Can you amend the commit message title line and PR title to be `server: document point-in-time nature of tenant_ranges status endpoint` to match  https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages#GitCommitMessages-Committitle
?

**Comment by mdlinville** [comment]
> nit: Can you amend the commit message title line and PR title to be `server: document point-in-time nature of tenant_ranges status endpoint` to match https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages#GitCommitMessages-Committitle ?

Done.

**Pull request merged**
