### PR TITLE
ui: fix folder ui files are served from in UI development mode

### PR DESCRIPTION
**Pull request by maxlang**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10037)

### CODE REVIEW

**Comment by mrtracy** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10037#-:-KUJWMEVgdMcZX3pLX4n:bnfp4nl)*

**Comment by tamird** [comment]
Hmm, perhaps we should use go/build to load the UI package and make this fail loudly in case of future breakage.

**Comment by tamird** [comment]
File an issue and assign me, if you don't mind.

**Comment by maxlang** [comment]
Created #10038 to track the issue.

**Pull request merged**
