### PR TITLE
acceptance: add basic test of on-disk compat with reference version

### PR DESCRIPTION
**Pull request by dt**
This verifies that the tested binary can read data written to disk by a
reference binary and that after it is allowed to modify that data, the
reference binary can still read it.

Note: Comparing the output of 'select *' is used to determine if the data was
read correctly for now, but we'll need to revisit that if/when we change the
default string format of the types used here.

Also changed the default cluster spun up for the `testDocker{Success,Failure}` helpers, that are used exclusively in the per-language tests, to an explicit single node config. The per-language tests are mostly about verifying pgwire behavior so the extra nodes don't really add coverage there and were just slowing things down.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6054)

### CODE REVIEW

**Comment by mjibson** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[acceptance/reference_test.go, line 21 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6054#-KFIZSzg4hILsh_3syb0:-KFIZSzhAhj7CS7J4Xwx:-2107776879) ([raw file](https://github.com/cockroachdb/cockroach/blob/e81243c2aef5a27a7fe150d2c6d02b6f32389835/acceptance/reference_test.go#L21)):*
Add a comment that diff exits with non-zero status if there's a diff, which triggers `set -e` to exit and fail the test.

---

*[acceptance/reference_test.go, line 40 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6054#-KFI_dCvsqTQTenKbecW:-KFI_dCwO31amdOttlaW:205360031) ([raw file](https://github.com/cockroachdb/cockroach/blob/e81243c2aef5a27a7fe150d2c6d02b6f32389835/acceptance/reference_test.go#L40)):*
I can't find how the `/cockroach` binary gets put there. It doesn't appear in the Dockerfile or (that I can see) in the docker invocation.

---

*[acceptance/cluster/localcluster.go, line 208 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6054#-KFIYSLoA0cuHXUMDcKA:-KFIYSLpXJrOoFRdSAtf:-1000286211) ([raw file](https://github.com/cockroachdb/cockroach/blob/e81243c2aef5a27a7fe150d2c6d02b6f32389835/acceptance/cluster/localcluster.go#L208)):*
What's this do?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6054)*

**Comment by tschottdorf** [comment]
:lgtm: (with @mjibson's comments). Unfortunately it only scratches the surface of things that could go wrong.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[acceptance/reference_test.go, line 51 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6054#-KFJ4KCF162nrozwcP4L:-KFJ4KCF162nrozwcP4M:160388434) ([raw file](https://github.com/cockroachdb/cockroach/blob/e81243c2aef5a27a7fe150d2c6d02b6f32389835/acceptance/reference_test.go#L51)):*
TIL

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6054#-:-KFJ4tHaroup5YnSmLPb:-820116486)*

**Comment by dt** [comment]
Yeah, I wanted to start somewhere though and I was hoping once some of the moving parts were in place, it'd be easier for others to add more granular tests.

I was thinking of adding a multi-node test, to check on-the-wire compat with the reference binary, but there it seems even less likely we can hope to exercise all the possible RPCs and combinations of flags.

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[acceptance/reference_test.go, line 21 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6054#-KFIZSzg4hILsh_3syb0:-KFJvuqHkBdd16i75hzk:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/e81243c2aef5a27a7fe150d2c6d02b6f32389835/acceptance/reference_test.go#L21)):*
Done.

---

*[acceptance/reference_test.go, line 40 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6054#-KFI_dCvsqTQTenKbecW:-KFJeywO1T2YANwpt_v0:-384142216) ([raw file](https://github.com/cockroachdb/cockroach/blob/e81243c2aef5a27a7fe150d2c6d02b6f32389835/acceptance/reference_test.go#L40)):*
See comment on `VolumesFrom` line below.

---

*[acceptance/reference_test.go, line 51 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6054#-KFJ4KCF162nrozwcP4L:-KFJgAYFGM1oih1NkVzL:750285081) ([raw file](https://github.com/cockroachdb/cockroach/blob/e81243c2aef5a27a7fe150d2c6d02b6f32389835/acceptance/reference_test.go#L51)):*
Same -- I started with `fg %1 || true` but this does exactly what I wanted. Added comment.

---

*[acceptance/cluster/localcluster.go, line 208 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6054#-KFIYSLoA0cuHXUMDcKA:-KFJge6VyOF3i_GvT6QN:1141068696) ([raw file](https://github.com/cockroachdb/cockroach/blob/e81243c2aef5a27a7fe150d2c6d02b6f32389835/acceptance/cluster/localcluster.go#L208)):*
In localcluster we setup a Container with binds for the binary, certs, etc:
https://github.com/cockroachdb/cockroach/blob/fd0f1cbdca513522e2e4f7cf0d72887d38e3af33/acceptance/cluster/localcluster.go#L316

And then when we spin up each node we use `VolumesFrom` to copy that container's binds. This just means we do the same for the oneshot container, so it has the same binds too (and that's how we have the `/cockroach` binary above).

Added note to the doc comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6054#-:-KFJhYXfA82rCGoshrNO:226599782)*

**Comment by dt** [comment]
rebased with latest beta as reference binary now (to pick up latest decimal change).

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6054#-:-KFL5DuF1yRIFNGFsQPv:1417088721)*

**Comment by bdarnell** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[acceptance/reference_test.go, line 25 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6054#-KFMbNrcdc1of7kjyXji:-KFMbNrcdc1of7kjyXjj:-358958690) ([raw file](https://github.com/cockroachdb/cockroach/blob/080cb26c3d617e7006dd38ef677465b1e70e2c50/acceptance/reference_test.go#L25)):*
Are these used? (they're not by `cockroach sql`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6054)*

**Pull request merged**
