### PR TITLE
kvserver/batcheval: ignore UseRangeTombstonesForPointDeletes knob sometimes

### LINKED ISSUE #87479: pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-no-los/multiregion-9node-3region-3azs-no-los_test: TestCCLLogic_regional_by_row_hash_sharded_index failed
pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-no-los/multiregion-9node-3region-3azs-no-los_test.TestCCLLogic_regional_by_row_hash_sharded_index [failed](https://teamcity.cockroachdb.com/buildConfiguration/BUILDTYPE_ID-not-found-in-env/6369522?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/BUILDTYPE_ID-not-found-in-env/6369522?buildTab=artifacts#/) on master @ [2372698da1dfacb90f60c6a63f2c1298d1db16b8](https://github.com/cockroachdb/cockroach/commits/2372698da1dfacb90f60c6a63f2c1298d1db16b8):

```
=== RUN   TestCCLLogic_regional_by_row_hash_sharded_index
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/231e1c2b82a8c60573009e2061c3fb3c/logTestCCLLogic_regional_by_row_hash_sharded_index2383282262
    test_log_scope.go:79: use -show-logs to present logs inline
[05:18:47] setting distsql_workmem='76905B';
[05:18:47] rng seed: -416924996751357404

[05:40:58] --- progress: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/3884/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-no-los/multiregion-9node-3region-3azs-no-los_test_/multiregion-9node-3region-3azs-no-los_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_hash_sharded_index: 11 statements
[06:03:31] --- progress: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/3884/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-no-los/multiregion-9node-3region-3azs-no-los_test_/multiregion-9node-3region-3azs-no-los_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_hash_sharded_index: 13 statements
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestCCLLogic_regional_by_row_hash_sharded_index.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-19362

### LINKED ISSUE #87575: pkg/ccl/logictestccl/tests/3node-tenant/3node-tenant_test: TestTenantLogic_create_index failed
pkg/ccl/logictestccl/tests/3node-tenant/3node-tenant_test.TestTenantLogic_create_index [failed](https://teamcity.cockroachdb.com/buildConfiguration/BUILDTYPE_ID-not-found-in-env/6383290?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/BUILDTYPE_ID-not-found-in-env/6383290?buildTab=artifacts#/) on release-22.2 @ [f8e04f32b84a9727c9e813d0096bde2de64d5675](https://github.com/cockroachdb/cockroach/commits/f8e04f32b84a9727c9e813d0096bde2de64d5675):

```
=== RUN   TestTenantLogic_create_index/test_old_bucket_count_syntax
    logic.go:3058: 
        
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/3949/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/logictestccl/tests/3node-tenant/3node-tenant_test_/3node-tenant_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/create_index:379: 
        expected success, but found
        (XXUUU) job 794770461987438593 was paused before it completed with reason: pause point "indexbackfill.before_flow" hit
        wait.go:173: in waitForJobs()
    logic.go:2014: 
         pq: job 794770461987438593 was paused before it completed with reason: pause point "indexbackfill.before_flow" hit
[05:31:37] --- done: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/3949/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/logictestccl/tests/3node-tenant/3node-tenant_test_/3node-tenant_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/create_index with config 3node-tenant: 60 tests, 2 failures
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestTenantLogic_create_index.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-19419

### PR DESCRIPTION
**Pull request by ajwerner**
We want to ignore the point deletion knob for cases where we're deleting data from system tables watched by rangefeeds. Not doing so can lead to missed updates. This is particularly critical for cluster settings.

Fixes #87575
Fixes #87479
Fixes #88202

Release note: None

### CODE REVIEW

**Comment by erikgrinaker** [comment]
I'd move this to somewhere around here: https://github.com/cockroachdb/cockroach/blob/e9d3258d8720d357cf9db8613ee42eb38d4e8f43/pkg/storage/mvcc.go#L6272-L6276

**Comment by ajwerner** [comment]
Done. `mvcc.go` is too big.

**Review by erikgrinaker — APPROVED** [review]
Thanks!

**Comment by ajwerner** [comment]
TFTR!
 
bors r+

**Pull request merged**
