### PR TITLE
kv: introduce txnCommitter interceptor to TxnCoordSender

### PR DESCRIPTION
**Pull request by nvb**
First 7 commits from #34850.

This commit introduces a new `txnInterceptor`, the `txnCommitter`. This interceptor concerns itself with committing and rolling back transactions. It intercepts EndTransaction requests and coordinates their execution. This is either accomplished by issuing them directly with proper addressing, eliding them when they are not needed, or (eventually) coordinating the execution of committing EndTransaction requests in parallel with the rest of their batch.

The primary justification for introducing this interceptor is that it will house all of the coordinator-side logic for parallel commits. The change is a net-win without this though. It consolidates logic about commits and rollbacks scattered between the `txnHeartbeater` and `txnIntentCollector` and puts in all in one place. This allows those interceptors to become more targeted (`txn_interceptor_heartbeater.go` is almost readable now!) and allows the disparate logic to be more easily unit tested.

### CODE REVIEW

**Review by tbg — APPROVED** [review]
:lgtm: very nice

> Reviewed 2 of 3 files at r1, 1 of 2 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, 3 of 3 files at r7, 6 of 6 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34852#-:-LYawhsrEswfuyeWNubB:b-k1vyq0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/txn_interceptor_committer.go, line 32 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/34852#-LYav0QC7SyUi9BI2BF-:-LYav0QC7SyUi9BI2BF0:b-ru59ks) ([raw file](https://github.com/cockroachdb/cockroach/blob/56207d441837c805f402522b1dbe864903c64fad/pkg/kv/txn_interceptor_committer.go#L32)):*
> ```Go
> // NOTE: the primary justification for introducing this interceptor is that it
> // will house all of the coordinator-side logic for parallel commits. Once
> // complete, there will be a nice description of parallel commits here.
> ```

can't wait!
___
*[pkg/kv/txn_interceptor_committer.go, line 82 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/34852#-LYavq6aDU13VhesUMbJ:-LYavq6aDU13VhesUMbK:b601rzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/56207d441837c805f402522b1dbe864903c64fad/pkg/kv/txn_interceptor_committer.go#L82)):*
> ```Go
> 		}
> 	} else {
> 		br = ba.CreateReply()
> ```

Wouldn't it be better to create a reply for the original `ba.Requests` so that you get the slot for the EndTransactionResponse allocated?
Probably not worth the complexity. This code reads nicely as is.
___
*[pkg/kv/txn_interceptor_committer_test.go, line 1 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/34852#-LYaw7xe-Kfa6X2drwLA:-LYaw7xe-Kfa6X2drwLB:b32val) ([raw file](https://github.com/cockroachdb/cockroach/blob/56207d441837c805f402522b1dbe864903c64fad/pkg/kv/txn_interceptor_committer_test.go#L1)):*
> ```Go
> // Copyright 2018 The Cockroach Authors.
> ```

19
___
*[pkg/kv/txn_interceptor_committer_test.go, line 123 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/34852#-LYawR0y87nA6GbuVOdj:-LYawR0y87nA6GbuVOdk:b3tig88) ([raw file](https://github.com/cockroachdb/cockroach/blob/56207d441837c805f402522b1dbe864903c64fad/pkg/kv/txn_interceptor_committer_test.go#L123)):*
> ```Go
> 			br := ba.CreateReply()
> 			br.Txn = ba.Txn
> 			br.Txn.Status = roachpb.PENDING // the Sender does NOT change the transaction status
> ```

Could you add a bit more commentary on this line?

**Review by andreimatei — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34852#-:-LYc01lN00mWGBMFu6ic:bb6ywmx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/txn_interceptor_committer.go, line 127 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/34852#-LYby6LnBV4bHUKYCKej:-LYby6LnBV4bHUKYCKek:bm6tsy1) ([raw file](https://github.com/cockroachdb/cockroach/blob/56207d441837c805f402522b1dbe864903c64fad/pkg/kv/txn_interceptor_committer.go#L127)):*
> ```Go
> func (tc *txnCommitter) closeLocked() {}
> 
> func cloneWithStatus(txn *roachpb.Transaction, s roachpb.TransactionStatus) *roachpb.Transaction {
> ```

just inline this in the caller. It's way to arbitrary to deserve a dedicated function

**Review by nvb — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34852#-:-LYipHL91PDKWHmfZ4XU:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @tbg)

___
*[pkg/kv/txn_interceptor_committer.go, line 82 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/34852#-LYavq6aDU13VhesUMbJ:-LYioO4u3exsPZzn17_K:bbsshhg) ([raw file](https://github.com/cockroachdb/cockroach/blob/56207d441837c805f402522b1dbe864903c64fad/pkg/kv/txn_interceptor_committer.go#L82)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Wouldn't it be better to create a reply for the original `ba.Requests` so that you get the slot for the EndTransactionResponse allocated?
Probably not worth the complexity. This code reads nicely as is.
</blockquote></details>

I just got rid of the call to `CreateReply` entirely, so there are no extra allocations now.
___
*[pkg/kv/txn_interceptor_committer.go, line 127 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/34852#-LYby6LnBV4bHUKYCKej:-LYior842O_32shwf-Vu:b-uraukq) ([raw file](https://github.com/cockroachdb/cockroach/blob/56207d441837c805f402522b1dbe864903c64fad/pkg/kv/txn_interceptor_committer.go#L127)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

just inline this in the caller. It's way to arbitrary to deserve a dedicated function
</blockquote></details>

If this was the end of this chain of commits then I would, but the parallel commits prototype uses this in a few other places.
___
*[pkg/kv/txn_interceptor_committer_test.go, line 1 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/34852#-LYaw7xe-Kfa6X2drwLA:-LYip0hc-_DGJ2PALvVp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/56207d441837c805f402522b1dbe864903c64fad/pkg/kv/txn_interceptor_committer_test.go#L1)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

19
</blockquote></details>

Done.
___
*[pkg/kv/txn_interceptor_committer_test.go, line 123 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/34852#-LYawR0y87nA6GbuVOdj:-LYipG5DAhyZ_nqc1WoE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/56207d441837c805f402522b1dbe864903c64fad/pkg/kv/txn_interceptor_committer_test.go#L123)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Could you add a bit more commentary on this line?
</blockquote></details>

Done.

**Comment by nvanbenschoten** [comment]
```
[TestParse/ParseModeMDY/epoch_infinity/04:05:06/ParseTimestamp] Test ended in panic.
```

But I don't see the panic or any related issue. Flake?

bors r+

**Comment by nvanbenschoten** [comment]
Oh, that's interesting.

```
[03:47:53] :                     [TestListFailures] /timeout-culprit-found.json
[03:47:53] :                             [/timeout-culprit-found.json] [Test Output]
2019/02/14 22:42:56 failed parent test "TestTxnCoordSenderPipelining"
2019/02/14 22:42:56 failed to create slow tests report: open artifacts/slow-tests-report.txt: no such file or directory
2019/02/14 22:42:56 unable to determine test author email: couldn't find test TestCommitTurnedToRollback in pkg/kv: exit status 1
2019/02/14 22:42:56 timeout culprit found: TestCommitTurnedToRollback
        main_test.go:229: expected author andrei@cockroachlabs.com, but got
```

bors r-

**Comment by nvanbenschoten** [comment]
Ok, the test just didn't like that we removed `TestCommitTurnedToRollback`. Fixed.

bors r+

**Pull request merged**
