### PR TITLE
client: make internals accessible on Batch

### PR DESCRIPTION
**Pull request by tbg**
`*client.Batch` is a good candidate to hold on to a `BatchResponse` and `Error`, and the resulting refactors remove a large amount of questionable code, including #6519.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6562)

### CODE REVIEW

**Comment by andreimatei** [comment]
:lgtm: nice

---

Review status: 0 of 27 files reviewed at latest revision, 12 unresolved discussions, some commit checks pending.

---

*[client/batch.go, line 112 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH68CCDkRV7ft6NZzjF:-KH68CCDkRV7ft6NZzjG:1109855964) ([raw file](https://github.com/cockroachdb/cockroach/blob/61d7f1bc6859b3821f8903eb18902be5f92a01d2/client/batch.go#L112)):*
fill free to ignore, but if you happened to get more understanding of this code, maybe it'd be a good moment to either document the semantics of this function better, or change it to a more intuitive api.
What is it supposed to do when `pErr` is `nil` vs when it's not? And when can `br` be nil?

---

*[client/batch.go, line 137 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6CCPmd9RQBDvzKMJ5:-KH6CCPmd9RQBDvzKMJ6:1616101887) ([raw file](https://github.com/cockroachdb/cockroach/blob/69f2b8de810b5a3defe0626763ad5b8a205fb15f/client/batch.go#L137)):*
can we move this assertion into its own function and call it in the beginning? So.much.indent.

---

*[client/batch.go, line 54 \[r16\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6DJteeRq4D7G1HBV5:-KH6DJtf8gsmng8mmfL7:-1834276188) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f1fed1d97a8a58a03d67c9485a4a8161f3b1d10/client/batch.go#L54)):*
please add a comment, mentioning how `response` is empty if `pErr` is coming from `send()`(?) 

---

*[client/batch.go, line 71 \[r16\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6DWJLeQadOJ3CWFLm:-KH6DWJLeQadOJ3CWFLn:-1814553692) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f1fed1d97a8a58a03d67c9485a4a8161f3b1d10/client/batch.go#L71)):*
nit: I prefer google-style `PErrOrDie()`. Keeps the prefix relevant. Also keeps you on your toes.

---

*[client/batch.go, line 97 \[r17\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6F5rWboonFSbg_cAJ:-KH6F5rWboonFSbg_cAK:-368363030) ([raw file](https://github.com/cockroachdb/cockroach/blob/0318996ef557aa985bdc4617d07ddb88b81290c9/client/batch.go#L97)):*
how about panicing instead?

---

*[client/batch.go, line 285 \[r17\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6El_L6C_0SN_sixtl:-KH6El_M6_fhihkkkJr8:1238192338) ([raw file](https://github.com/cockroachdb/cockroach/blob/0318996ef557aa985bdc4617d07ddb88b81290c9/client/batch.go#L285)):*
so why do we need this "raw" flavor? What's special about requests added through this? Why no response?

---

*[client/batch.go, line 555 \[r17\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6FGjlTNPNsqpZw-FV:-KH6FGjlTNPNsqpZw-FW:67481348) ([raw file](https://github.com/cockroachdb/cockroach/blob/0318996ef557aa985bdc4617d07ddb88b81290c9/client/batch.go#L555)):*
mind elaborating a bit why they need to be killed? Or why the exist.

---

*[client/db.go, line 419 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH65ktVnzzY7PgeWEgf:-KH65ktVnzzY7PgeWEgg:725907663) ([raw file](https://github.com/cockroachdb/cockroach/blob/509f77a533da8d6a78d49f5b2460fcb41d532cd8/client/db.go#L419)):*
could we abstract this func in an interface? In fact, don't we have a suitable interface already?

---

*[client/db.go, line 427 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH65QZvlIA3y8s7uLWw:-KH65QZvlIA3y8s7uLWx:945874107) ([raw file](https://github.com/cockroachdb/cockroach/blob/509f77a533da8d6a78d49f5b2460fcb41d532cd8/client/db.go#L427)):*
what's with the TODO?

---

*[client/db.go, line 492 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH68kO_IILkJDo7W9i0:-KH68kO_IILkJDo7W9i1:-101527679) ([raw file](https://github.com/cockroachdb/cockroach/blob/61d7f1bc6859b3821f8903eb18902be5f92a01d2/client/db.go#L492)):*
what's stopping you?

---

*[client/db.go, line 124 \[r16\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6Dr5AjuZE6vfCneBx:-KH6Dr5AjuZE6vfCneBy:-1010876378) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f1fed1d97a8a58a03d67c9485a4a8161f3b1d10/client/db.go#L124)):*
one less wrong thing on the Internet. #RefactoringForGod

---

*[ts/query.go, line 435 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH69biB5qE7lKzFubDe:-KH69biB5qE7lKzFubDf:1101356945) ([raw file](https://github.com/cockroachdb/cockroach/blob/593af94a9344e0244d2b67f14f2d4b8269b5c055/ts/query.go#L435)):*
wasn't there a reason why the scan used to be inconsistent?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-:-KH6G3EH-S6bjJ6jGI8O:677188428)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1, 4 of 4 files at r2, 3 of 3 files at r3, 7 of 7 files at r4, 5 of 5 files at r5, 11 of 11 files at r6, 8 of 8 files at r7, 15 of 15 files at r8, 4 of 4 files at r9, 26 of 26 files at r10, 4 of 4 files at r11, 3 of 3 files at r12, 7 of 7 files at r13, 5 of 5 files at r14, 11 of 11 files at r15, 8 of 8 files at r16, 15 of 15 files at r17, 5 of 5 files at r18.
Review status: all files reviewed at latest revision, 22 unresolved discussions, all commit checks successful.

---

*[client/batch.go, line 245 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6Hbrah2lIXbwRky46:-KH6HbrbSY5sOZxio3Y8:1955936982) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ad3d5f6c2dbece621c46bd975612b9a4028fd4c/client/batch.go#L245)):*
nit, but this function is used pretty heavily so:
```
rus := make([]roachpb.RequestUnion, len(args))
for i := range args {
  rus[i].MustSetInner(arg)
}
b.reqs = append(b.reqs, rus...)
```

This only matters because `append` is slow, as we learned not long ago.

---

*[client/batch.go, line 137 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6CCPmd9RQBDvzKMJ5:-KH6IkIaF4l5886CxnqV:1599624653) ([raw file](https://github.com/cockroachdb/cockroach/blob/69f2b8de810b5a3defe0626763ad5b8a205fb15f/client/batch.go#L137)):*
I'd leave it here because of the TODO.

---

*[client/batch.go, line 73 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6L9Jr5PeExjg_KzZU:-KH6L9Jr5PeExjg_KzZV:71280145) ([raw file](https://github.com/cockroachdb/cockroach/blob/3292752d3b268a939dfd2236e83a179cae91d689/client/batch.go#L73)):*
maybe log the batch as well?

---

*[client/batch.go, line 71 \[r16\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6DWJLeQadOJ3CWFLm:-KH6L4Vj6hop23P8Kfvu:-1575502319) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f1fed1d97a8a58a03d67c9485a4a8161f3b1d10/client/batch.go#L71)):*
We have a ton of MustFoo methods.

---

*[client/batch.go, line 285 \[r17\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6El_L6C_0SN_sixtl:-KH6NVTq_yED0GNZanBr:-1004716920) ([raw file](https://github.com/cockroachdb/cockroach/blob/0318996ef557aa985bdc4617d07ddb88b81290c9/client/batch.go#L285)):*
+1 - could we statically have the separation between internal and non-internal batches?

---

*[client/batch.go, line 555 \[r17\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6FGjlTNPNsqpZw-FV:-KH6NIT7XUcUIaJa_IAk:1808102736) ([raw file](https://github.com/cockroachdb/cockroach/blob/0318996ef557aa985bdc4617d07ddb88b81290c9/client/batch.go#L555)):*
this was removed at some rev

---

*[client/client_test.go, line 745 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6Jh7beaIX0R4HSVM3:-KH6Jh7beaIX0R4HSVM4:-2045275613) ([raw file](https://github.com/cockroachdb/cockroach/blob/593af94a9344e0244d2b67f14f2d4b8269b5c055/client/client_test.go#L745)):*
nit: return a value?

---

*[client/db.go, line 427 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH65QZvlIA3y8s7uLWw:-KH6JN7N0sn_0bwtC2zl:940469901) ([raw file](https://github.com/cockroachdb/cockroach/blob/509f77a533da8d6a78d49f5b2460fcb41d532cd8/client/db.go#L427)):*
random removed in r4 =/

---

*[client/db.go, line 492 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH68kO_IILkJDo7W9i0:-KH6IrSXvDMV9BVpdsCN:-16978403) ([raw file](https://github.com/cockroachdb/cockroach/blob/61d7f1bc6859b3821f8903eb18902be5f92a01d2/client/db.go#L492)):*
probably avoiding an alloc

---

*[client/txn.go, line 651 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6IFa-YYMDtjzv80qj:-KH6IFa-YYMDtjzv80qk:-859665715) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ad3d5f6c2dbece621c46bd975612b9a4028fd4c/client/txn.go#L651)):*
seems like this name should stay `bt` and the RequestUnion should be `ru`

---

*[client/txn.go, line 600 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6IUHvpoouAboAnpFY:-KH6IUHwFjB0HBLdDsyl:1874283534) ([raw file](https://github.com/cockroachdb/cockroach/blob/61d7f1bc6859b3821f8903eb18902be5f92a01d2/client/txn.go#L600)):*
time to move this up a line

---

*[server/status.go, line 530 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6JsJqg1JpqdHfIByF:-KH6JsJrE3JMsRanIDd0:-1326888719) ([raw file](https://github.com/cockroachdb/cockroach/blob/593af94a9344e0244d2b67f14f2d4b8269b5c055/server/status.go#L530)):*
bring that same convenience method here, too?

---

*[server/status.go, line 573 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6K0V3jISvY3u8SBaP:-KH6K0V3jISvY3u8SBaQ:-180323239) ([raw file](https://github.com/cockroachdb/cockroach/blob/593af94a9344e0244d2b67f14f2d4b8269b5c055/server/status.go#L573)):*
did you actually hit this? how?

---

*[storage/gc_queue.go, line 585 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6K9TqHx8hkqfo7e7d:-KH6K9TqHx8hkqfo7e7e:-369178008) ([raw file](https://github.com/cockroachdb/cockroach/blob/69f2b8de810b5a3defe0626763ad5b8a205fb15f/storage/gc_queue.go#L585)):*
can scope this more narrowly now

---

*[storage/replica_gc_queue.go, line 109 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6KFbRqVuLgQynC4UG:-KH6KFbRqVuLgQynC4UH:530991522) ([raw file](https://github.com/cockroachdb/cockroach/blob/69f2b8de810b5a3defe0626763ad5b8a205fb15f/storage/replica_gc_queue.go#L109)):*
scope more narrowly

---

*[storage/store.go, line 1886 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6KIVqsEM8MdxoJu2w:-KH6KIVqsEM8MdxoJu2x:530991522) ([raw file](https://github.com/cockroachdb/cockroach/blob/69f2b8de810b5a3defe0626763ad5b8a205fb15f/storage/store.go#L1886)):*
scope more narrowly

---

*[ts/query.go, line 435 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH69biB5qE7lKzFubDe:-KH6JZcOnjCu1qrUNzhB:-38368647) ([raw file](https://github.com/cockroachdb/cockroach/blob/593af94a9344e0244d2b67f14f2d4b8269b5c055/ts/query.go#L435)):*
+1, should probably stay inconsistent to avoid perf regression

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562)*

**Comment by petermattis** [comment]
Reviewed 2 of 2 files at r1, 4 of 4 files at r2, 3 of 3 files at r3, 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 26 unresolved discussions, all commit checks successful.

---

*[client/batch.go, line 248 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6YeMny3QkdJKhHtp_:-KH6YeMny3QkdJKhHtpa:635135888) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ad3d5f6c2dbece621c46bd975612b9a4028fd4c/client/batch.go#L248)):*
See @tamird's suggestion above. Calling `MustSetInner` on the stack variable forces it to the heap which is unfortunate.

---

*[client/db.go, line 402 \[r18\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6bHJ44kuZ6hBBCQ4L:-KH6bHJ44kuZ6hBBCQ4M:517334359) ([raw file](https://github.com/cockroachdb/cockroach/blob/3141f33945ab56f31a437ab1657dace2cbc85c4f/client/db.go#L402)):*
`s/failures/failures)/g`

---

*[client/txn.go, line 608 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6YGoK_iLnhmG8DWU-:-KH6YGoK_iLnhmG8DWU0:1898803648) ([raw file](https://github.com/cockroachdb/cockroach/blob/509f77a533da8d6a78d49f5b2460fcb41d532cd8/client/txn.go#L608)):*
I think `s/%d/%s/g` will improve the error message.

---

*[client/txn.go, line 647 \[r18\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6bjWjq6cEasXAJb-U:-KH6bjWjq6cEasXAJb-V:590160424) ([raw file](https://github.com/cockroachdb/cockroach/blob/3141f33945ab56f31a437ab1657dace2cbc85c4f/client/txn.go#L647)):*
The `MustSetInner` call will force `bt` to the heap. Better to do something like:

```
  oldRequests := ba.Requests
  ba.Requests = make([]roachpb.RequestUnion, len(ba.Requests) + 1)
  copy(ba.Requests, oldRequests[:firstWriteIndex])
  ba.Requests[firstWriteIndex].MustSetInner(req)
  copy(ba.Requests[firstWriteIndex+1:], oldRequests[firstWriteIndex:])
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562)*

**Comment by tschottdorf** [comment]
TFTR! Comments addressed.

<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> :lgtm: nice</details>


---

Review status: all files reviewed at latest revision, 26 unresolved discussions, all commit checks successful.

---

*[client/batch.go, line 245 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6Hbrah2lIXbwRky46:-KHFcEUScu804CbYet5B:1516997565) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ad3d5f6c2dbece621c46bd975612b9a4028fd4c/client/batch.go#L245)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit, but this function is used pretty heavily so:
> ```
> rus := make([]roachpb.RequestUnion, len(args))
> for i := range args {
>   rus[i].MustSetInner(arg)
> }
> b.reqs = append(b.reqs, rus...)
> ```
> 
> This only matters because `append` is slow, as we learned not long ago.</details>
Done, though I'd be very surprised if this showed.

---

*[client/batch.go, line 248 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6YeMny3QkdJKhHtp_:-KHFcmOxpWw1Pa7LBM-k:1905363446) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ad3d5f6c2dbece621c46bd975612b9a4028fd4c/client/batch.go#L248)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> See @tamird's suggestion above. Calling `MustSetInner` on the stack variable forces it to the heap which is unfortunate.</details>
Done (and verified that nothing's on the heap, at least not here).

---

*[client/batch.go, line 112 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH68CCDkRV7ft6NZzjF:-KHFbDFQfSbm-nLbX0HE:-1068080162) ([raw file](https://github.com/cockroachdb/cockroach/blob/61d7f1bc6859b3821f8903eb18902be5f92a01d2/client/batch.go#L112)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> fill free to ignore, but if you happened to get more understanding of this code, maybe it'd be a good moment to either document the semantics of this function better, or change it to a more intuitive api.
> What is it supposed to do when `pErr` is `nil` vs when it's not? And when can `br` be nil?</details>
I hope I clarified the last two questions on the field comments - `br != nil` iff `pErr == nil`. I updated the comment here and sprinkled some throughout the method. Let me know if that makes sense.

---

*[client/batch.go, line 73 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6L9Jr5PeExjg_KzZU:-KHFaEe5M2U2gntJgG_Y:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3292752d3b268a939dfd2236e83a179cae91d689/client/batch.go#L73)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> maybe log the batch as well?</details>
Done.

---

*[client/batch.go, line 54 \[r16\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6DJteeRq4D7G1HBV5:-KHF_tF4rnJKgSP02SYq:1835118550) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f1fed1d97a8a58a03d67c9485a4a8161f3b1d10/client/batch.go#L54)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> please add a comment, mentioning how `response` is empty if `pErr` is coming from `send()`(?) </details>
Done (I think?)

---

*[client/batch.go, line 71 \[r16\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6DWJLeQadOJ3CWFLm:-KHFa0MDHwC9Grf1mkMq:-396204874) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f1fed1d97a8a58a03d67c9485a4a8161f3b1d10/client/batch.go#L71)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> We have a ton of MustFoo methods.</details>
Yeah, I'm gonna stick to our guns here.

---

*[client/batch.go, line 97 \[r17\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6F5rWboonFSbg_cAJ:-KHFaIPWINchpD1BSW6R:570673396) ([raw file](https://github.com/cockroachdb/cockroach/blob/0318996ef557aa985bdc4617d07ddb88b81290c9/client/batch.go#L97)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> how about panicing instead?</details>
I'm not fond of panicking when I have a perfectly good method to return an error and the running system isn't at stake. The only reason to do that is when I'm scared that test coverage is lacking, and I'm not for this change.

---

*[client/batch.go, line 285 \[r17\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6El_L6C_0SN_sixtl:-KHFctG3oB_YJ2CVTLIR:710884851) ([raw file](https://github.com/cockroachdb/cockroach/blob/0318996ef557aa985bdc4617d07ddb88b81290c9/client/batch.go#L285)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> +1 - could we statically have the separation between internal and non-internal batches?</details>
We could (and I was tempted), but I don't consider it a priority at the moment (the whole API here is still somewhat wedged between the public API it once was and the internal workhorse it is now, and I expect DistSQL to give more ideas on what a future restructuring should look like).
There's no response because, well, I simply don't want to make this a full-fledged thing. If you push random requests in here, don't expect it to try to figure out what you're doing and parse your responses. You're likely going to reach into `b.RawResponse()` anyway.

---

*[client/client_test.go, line 745 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6Jh7beaIX0R4HSVM3:-KHFdmfvHREwUyFJpUMN:1933769018) ([raw file](https://github.com/cockroachdb/cockroach/blob/593af94a9344e0244d2b67f14f2d4b8269b5c055/client/client_test.go#L745)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: return a value?</details>
No, because Batch should be handled as pointer (contains state) and https://play.golang.org/p/vUdxrIUec7

---

*[client/db.go, line 419 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH65ktVnzzY7PgeWEgf:-KHFdxTn-MJEO1idOelm:585026740) ([raw file](https://github.com/cockroachdb/cockroach/blob/509f77a533da8d6a78d49f5b2460fcb41d532cd8/client/db.go#L419)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> could we abstract this func in an interface? In fact, don't we have a suitable interface already?</details>
yes, we could, but it's pointless. We have client.Sender but it's slightly different and not everything that satisfies the same interface works the same (that's an issue with our current usage of client.Sender).

---

*[client/db.go, line 492 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH68kO_IILkJDo7W9i0:-KHFjzrj8vYk8NpdY_vJ:1416408194) ([raw file](https://github.com/cockroachdb/cockroach/blob/61d7f1bc6859b3821f8903eb18902be5f92a01d2/client/db.go#L492)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> probably avoiding an alloc</details>
Just took a look and the reason that we even have this case is essentially because a) we want some convenient place to make sure empty batches don't explode and b) `(*Txn).send` calls in here and may create empty requests because of eliding EndTransaction on a read-only txn. I think it's best to keep returning `nil` here and to point it out in the comment.

---

*[client/db.go, line 402 \[r18\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6bHJ44kuZ6hBBCQ4L:-KHFeTQuICokwDjN2Aih:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3141f33945ab56f31a437ab1657dace2cbc85c4f/client/db.go#L402)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `s/failures/failures)/g`</details>
Done.

---

*[client/txn.go, line 608 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6YGoK_iLnhmG8DWU-:-KHFlYU5KHEW7rWRlDkd:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/509f77a533da8d6a78d49f5b2460fcb41d532cd8/client/txn.go#L608)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I think `s/%d/%s/g` will improve the error message.</details>
Done.

---

*[client/txn.go, line 651 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6IFa-YYMDtjzv80qj:-KHFlfu-5YrGYda_MqeN:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ad3d5f6c2dbece621c46bd975612b9a4028fd4c/client/txn.go#L651)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> seems like this name should stay `bt` and the RequestUnion should be `ru`</details>
Done.

---

*[client/txn.go, line 600 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6IUHvpoouAboAnpFY:-KHFlSjD_V3P7pQWAKW8:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/61d7f1bc6859b3821f8903eb18902be5f92a01d2/client/txn.go#L600)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> time to move this up a line</details>
Done.

---

*[client/txn.go, line 647 \[r18\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6bjWjq6cEasXAJb-U:-KHFmpNtX6KnRuQJX9NO:-850572099) ([raw file](https://github.com/cockroachdb/cockroach/blob/3141f33945ab56f31a437ab1657dace2cbc85c4f/client/txn.go#L647)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> The `MustSetInner` call will force `bt` to the heap. Better to do something like:
> 
> ```
>   oldRequests := ba.Requests
>   ba.Requests = make([]roachpb.RequestUnion, len(ba.Requests) + 1)
>   copy(ba.Requests, oldRequests[:firstWriteIndex])
>   ba.Requests[firstWriteIndex].MustSetInner(req)
>   copy(ba.Requests[firstWriteIndex+1:], oldRequests[firstWriteIndex:])
> ```</details>
Good point, done. More legible, too.

---

*[server/status.go, line 530 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6JsJqg1JpqdHfIByF:-KHFnbIF4SAgC7czvT5P:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/593af94a9344e0244d2b67f14f2d4b8269b5c055/server/status.go#L530)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> bring that same convenience method here, too?</details>
Done.

---

*[server/status.go, line 573 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6K0V3jISvY3u8SBaP:-KHFnkBnukbHdrDu6k5K:547959740) ([raw file](https://github.com/cockroachdb/cockroach/blob/593af94a9344e0244d2b67f14f2d4b8269b5c055/server/status.go#L573)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> did you actually hit this? how?</details>
No, just being thorough (that check was previously done by `GetProtoInconsistent`).

---

*[storage/gc_queue.go, line 585 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6K9TqHx8hkqfo7e7d:-KHFnxzUVb5HJxGqarV9:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/69f2b8de810b5a3defe0626763ad5b8a205fb15f/storage/gc_queue.go#L585)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can scope this more narrowly now</details>
Done.

---

*[storage/replica_gc_queue.go, line 109 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6KFbRqVuLgQynC4UG:-KHFo4Becr2wPxOgRjNF:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/69f2b8de810b5a3defe0626763ad5b8a205fb15f/storage/replica_gc_queue.go#L109)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> scope more narrowly</details>
Done.

---

*[storage/store.go, line 1886 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6KIVqsEM8MdxoJu2w:-KHFoAaqSXPBOaf65pzQ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/69f2b8de810b5a3defe0626763ad5b8a205fb15f/storage/store.go#L1886)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> scope more narrowly</details>
Done.

---

*[ts/query.go, line 435 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH69biB5qE7lKzFubDe:-KHFoFJ1Z7SxHUoPnA_y:-2030036460) ([raw file](https://github.com/cockroachdb/cockroach/blob/593af94a9344e0244d2b67f14f2d4b8269b5c055/ts/query.go#L435)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> +1, should probably stay inconsistent to avoid perf regression</details>
Oops, this was an unintentional change. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-:-KHFom2cO79JSvjsdmO0:-1875133901)*

**Comment by tamird** [comment]
Reviewed 27 of 27 files at r19, 4 of 4 files at r20, 3 of 3 files at r21, 7 of 7 files at r22, 1 of 5 files at r23, 4 of 8 files at r25, 9 of 15 files at r26, 3 of 5 files at r27, 7 of 7 files at r28.
Review status: all files reviewed at latest revision, 18 unresolved discussions, all commit checks successful.

---

*[client/client_test.go, line 745 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KH6Jh7beaIX0R4HSVM3:-KHGDIrCt-GgdFHHHOrU:-1977876449) ([raw file](https://github.com/cockroachdb/cockroach/blob/593af94a9344e0244d2b67f14f2d4b8269b5c055/client/client_test.go#L745)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> No, because Batch should be handled as pointer (contains state) and https://play.golang.org/p/vUdxrIUec7</details>
that anything that contains state "should be handled as a pointer" is somewhat dubious, but OK.

---

*[server/status.go, line 577 \[r28\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KHGEoeUiBYEqa3oLyq1:-KHGEoeWh-XZnRjMulZm:-1231210456) ([raw file](https://github.com/cockroachdb/cockroach/blob/82a484c92e5eee99e0c1f7f9187684568d9f3982/server/status.go#L577)):*
> ```Go
> 	var nodeStatus status.NodeStatus
> 	if err := b.Results[0].Rows[0].ValueProto(&nodeStatus); err != nil {
> 		err = util.Errorf("value returned from %s is not a NodeStatus: %s", key, err)
> ```

nit: this doesn't necessarily mean it's not a NodeStatus

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562)*

**Comment by tschottdorf** [comment]
Review status: 0 of 27 files reviewed at latest revision, 17 unresolved discussions, some commit checks pending.

---

*[server/status.go, line 577 \[r28\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562#-KHGEoeUiBYEqa3oLyq1:-KHIBkgM3-5CjxAUlmg8:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/82a484c92e5eee99e0c1f7f9187684568d9f3982/server/status.go#L577)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: this doesn't necessarily mean it's not a NodeStatus</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6562)*

**Pull request merged**
