### PR TITLE
sql: add validation for partitions matching REGIONAL BY ROW

### PR DESCRIPTION
**Pull request by otan**
See individual commits for details.

### CODE REVIEW

**Comment by otan** [comment]
@ajwerner curious if you had thoughts on alternatives for the first commit, which resolves a chicken and egg problem

**Review by ajwerner — COMMENTED** [review]
What you're doing makes sense. How'd you catch this problem? If I were to step back a bit on the problem, it feels like we should be validating newly read descriptors using the cluster version as opposed to the mutated version of the type descriptor. I don't think we have the abstractions in place to pull that off. cc @postamar 

I only read the commit message

**Comment by otan** [comment]
It was found by writing the validator first, and watching it fail on our tests, hehe!

**Review by arulajmani — CHANGES_REQUESTED** [review]
> , it feels like we should be validating newly read descriptors using the cluster version as opposed to the mutated version of the type descriptor.

I think this particular case is made slightly more complicated by the fact that we're batch fetching all descriptors when running into this validations problem. I think the batch fetching APIs validate using other fetched descriptors, without considering the desc collection, so they probably wouldn't even have the correct cluster version on them. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63898#-:-MYkIf_H7jTWWlVP7Ouf:b-x9kfop)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/database_region_change_finalizer.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63898#-MYkEcxx15pnDTcP5Vge:-MYkEcxx15pnDTcP5Vgf:b-4yn7qj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f786423768e4a6342abb3ae377a0615cdc066757/pkg/sql/database_region_change_finalizer.go#L38)):*
> ```Go
> 	dbID   descpb.ID
> 	typeID descpb.ID
> 	txn    *kv.Txn
> ```

How do you feel about passing in the txn explicitly instead of storing it here? I say because the lifecycle of this struct outlives the txn (in particular, the `waitToUpdateLeases` is called outside of the callback that is passed in the txn object). 
___
*[pkg/sql/database_region_change_finalizer.go, line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63898#-MYkEUyICA7sp6MB_0sA:-MYkEUyICA7sp6MB_0sB:beu22xx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f786423768e4a6342abb3ae377a0615cdc066757/pkg/sql/database_region_change_finalizer.go#L43)):*
> ```Go
> 	cleanupFunc         func()
> 	regionalByRowTables []*tabledesc.Mutable
> 	waitForLeaseIDs     []descpb.ID
> ```

nit: you probably don't need two lists here, the IDs on descriptors stored inside`regionalByRowTables` should suffice. 
___
*[pkg/sql/database_region_change_finalizer.go, line 160 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63898#-MYkGEni6FWbaYY8BWd9:-MYkGEni6FWbaYY8BWdA:b-i56xl6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f786423768e4a6342abb3ae377a0615cdc066757/pkg/sql/database_region_change_finalizer.go#L160)):*
> ```Go
> 	for _, tableDesc := range r.regionalByRowTables {
> 		// Since we hydrated the columns with the old enum, and now that the enum moved
> 		// all transitioned, we have to re-hydrate all the enums.
> ```

nit: could you reword the part which says "and now that the enum moved ...", I find it confusing.

Also, did you mean to say "we have to re-hydrate all table descriptors"?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63898)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[pkg/sql/database_region_change_finalizer.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63898#-MYkEcxx15pnDTcP5Vge:-MYl16g1073ngINgin7n:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f786423768e4a6342abb3ae377a0615cdc066757/pkg/sql/database_region_change_finalizer.go#L38)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

How do you feel about passing in the txn explicitly instead of storing it here? I say because the lifecycle of this struct outlives the txn (in particular, the `waitToUpdateLeases` is called outside of the callback that is passed in the txn object). 
</blockquote></details>

Done.
___
*[pkg/sql/database_region_change_finalizer.go, line 160 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63898#-MYkGEni6FWbaYY8BWd9:-MYl1aL57TQxPkGTa_Gv:b-hr1jyj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f786423768e4a6342abb3ae377a0615cdc066757/pkg/sql/database_region_change_finalizer.go#L160)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: could you reword the part which says "and now that the enum moved ...", I find it confusing.

Also, did you mean to say "we have to re-hydrate all table descriptors"?
</blockquote></details>

technically you're rehydrating the type, but i've reworded it to something to that effect

**Review by arulajmani — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63898#-:-MYlK6Uz57D2Y3mEU6wH:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @otan)

___
*[pkg/sql/database_region_change_finalizer.go, line 160 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63898#-MYkGEni6FWbaYY8BWd9:-MYlJkAw7KEAXMkONSf1:b-rhjj9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/f786423768e4a6342abb3ae377a0615cdc066757/pkg/sql/database_region_change_finalizer.go#L160)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

technically you're rehydrating the type, but i've reworded it to something to that effect
</blockquote></details>

nit: s/we have re-hydrate/we have to re-hydrate/g

**Comment by otan** [comment]
bors r=arulajmani

**Pull request merged**
