### PR TITLE
release-20.1: fix 19.2 - 20.1 closedts incompatibility

### PR DESCRIPTION
**Pull request by andreimatei**
In 20.1 we've inadvertently changed the name of an RPC service by
switching a package name. This was causing 20.1 nodes to not be able to
connect to 19.2 nodes in order to receive closedts updates. This patch
introduces a fallback for the old service name.
19.2 nodes also can't connect to 20.1 nodes; that'll be fixed in the
next commit.

Release note: A bug causing 20.1 nodes to not be able to serve follower
reads in mixed-version 19.2/20.1 cluster has been fixed.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55089)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @andreimatei)

___
*[pkg/kv/kvserver/closedts/transport/clients.go, line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55089#-MI_IMx11u1ITNoLgI_1:-MI_IMx27VzfNUUjoi3u:b-af7j45) ([raw file](https://github.com/cockroachdb/cockroach/blob/4195742a629481266a6612993c05676961eebd72/pkg/kv/kvserver/closedts/transport/clients.go#L188)):*
> ```Go
> 		// connect to 19.2 nodes they don't know what we're talking about. Fallback
> 		// to the old name.
> 		if err != nil && strings.Contains(err.Error(), "unknown service") {
> ```

any chance we can get a more structured error here?

**Review by ajwerner — APPROVED** [review]
Anyway, more structured error would be nice but it's a bit pedantic. :lgtm: 

If I had one piece of feedback it'd be that I'd love to see something to test this compatibility. My sense is that a mixed version roachtest would be great. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55089#-:-MI_a07u5JBDTffr3Q5t:b-k6e5my)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @andreimatei)

**Review by andreimatei — COMMENTED** [review]
> My sense is that a mixed version roachtest would be great.


Yeah absolutely. I was going to see if I can kindly pass that yo @aayushshah15 who's looking at follower read tests in general. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55089#-:-MI_bx_z5_Lb_C9UDea1:bd7ddkb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/kv/kvserver/closedts/transport/clients.go, line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55089#-MI_IMx11u1ITNoLgI_1:-MI__zU5DX9kxHqDzYNe:bhgaryk) ([raw file](https://github.com/cockroachdb/cockroach/blob/4195742a629481266a6612993c05676961eebd72/pkg/kv/kvserver/closedts/transport/clients.go#L188)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

any chance we can get a more structured error here?
</blockquote></details>

not much, I don't think. The error is this, perhaps wrapped
https://github.com/grpc/grpc-go/blob/master/internal/status/status.go#L42

At most I can get an HTTP code - which is "Unimplemented" in this case. You think it's worth it?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55089)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/kv/kvserver/closedts/transport/clients.go, line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55089#-MI_IMx11u1ITNoLgI_1:-MI_c_IM9mZ6HWQwK5Cc:b37wsi1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4195742a629481266a6612993c05676961eebd72/pkg/kv/kvserver/closedts/transport/clients.go#L188)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

not much, I don't think. The error is this, perhaps wrapped
https://github.com/grpc/grpc-go/blob/master/internal/status/status.go#L42

At most I can get an HTTP code - which is "Unimplemented" in this case. You think it's worth it?
</blockquote></details>

I'll merge as is without mucking with this error detection more. This is zombie code anyway.

**Pull request merged**
