### PR TITLE
sql/logictest: add metamorphic param for global MVCC range tombstone

### PR DESCRIPTION
**Pull request by erikgrinaker**
**kvserver: add `GlobalMVCCRangeTombstone` testing knob**

This patch adds a set of testing knobs to enable writing an MVCC range
tombstone at the bottom of the keyspace during cluster bootstrapping.
This also subsumes the previous mechanism to trigger this from the
envvar `COCKROACH_GLOBAL_MVCC_RANGE_TOMBSTONE`, for e.g. roachtests and
roachperf benchmarks.

Release justification: non-production code changes

Release note: None
  
**sql/logictest: add metamorphic param for global MVCC range tombstone**

This patch adds a metamorphic parameter for the SQL logic tests that
will randomly write a global MVCC range tombstone across the entire user
keyspace during cluster bootstrapping. This should not semantically
affect the test data written above it, but will activate MVCC range
tombstone code paths in the storage layer for testing.

Touches #84042.

Release justification: non-production code changes

Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
@rytaft could you please find an reviewer here?

**Review by yuzefovich — COMMENTED** [review]
> Looks like this won't generate the config for `3node-tenant-range-tombstone` for some reason.

My guess is that because you didn't explicitly specify this new config in any of the logic test files, there is no target that would trigger this generation. You might want to include this new config into `ThreeNodeTenantDefaultConfigNames` in `logictestbase.go` so that the new config would run against most logic test files. It's possible that you also need to make some adjustments to `pkg/cmd/generate-logictest/main.go` to include into `ConfigOverrides` - not sure about that one.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86866#-:-NALWI2x3jp0ZS-FTZ-V:b-jnk1cd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @jordanlewis, and @tbg)

___
*[`pkg/kv/kvserver/client_raft_test.go` line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86866#-NALV4rD0OocnPms-ReE:-NALV4rD0OocnPms-ReF:b-u9ew1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea3c48b18bbb6a86906a94115ac7b2952085a0b4/pkg/kv/kvserver/client_raft_test.go#L83)):*
> ```Go
> }
> 
> func TestXXX(t *testing.T) {
> ```

nit: this test seems out of place.

**Review by erikgrinaker — COMMENTED** [review]
> It's possible that you also need to make some adjustments to pkg/cmd/generate-logictest/main.go to include into ConfigOverrides

This did the trick, thanks!

I think this should be good to go now, but I mostly cargo-culted this so let me know if there are any other configs that would be more appropriate or anything.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86866#-:-NAOwzN-BskQiqqrZSDN:b-81gazy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[`pkg/kv/kvserver/client_raft_test.go` line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86866#-NALV4rD0OocnPms-ReE:-NAOxBElAsgrGWGaXN43:b-hkimy) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea3c48b18bbb6a86906a94115ac7b2952085a0b4/pkg/kv/kvserver/client_raft_test.go#L83)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: this test seems out of place.
</blockquote></details>

Whoops, yeah, this was accidentally committed.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

Although it might be worth considering a somewhat different approach - rather than introducing some new configs that explicitly use the range tombstones, why not do that randomly on all existing configs? I.e. with 50% chance for each logic test run put the global range tombstone. This seems like it would give us better coverage (e.g. local and 5node configs would be used too) while also keeping the number of tests smaller.

> Reviewed 7 of 9 files at r1, 31 of 31 files at r3, 32 of 32 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86866#-:-NAPxzBi6gjJ9MmTE37C:bf0e4rx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

**Review by erikgrinaker — COMMENTED** [review]
Yeah, I think you're right -- done!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86866#-:-NAd-u9B3WqEwrpAFmZF:bv0v3jr)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tbg and @yuzefovich)

**Review by tbg — APPROVED** [review]
[Pinged #flaky-test-fighter](https://cockroachlabs.slack.com/archives/C016CAD2HQ8/p1661766488183789) about version-upgrade failure on this PR.

I'll defer to @yuzefovich on the randomization. It seems to make sense - we don't expect any individual test to choke on these (ok maybe some will find a way to accidentally detect the tombstone), and an opt-out pattern would be preferable.

Ah, you just pushed that. :shipit: 

> Reviewed 7 of 9 files at r1, 31 of 31 files at r3, 31 of 31 files at r5, 31 of 31 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86866#-:-NAd-BjBALkPkfMYAuIK:b-yhon8r)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @erikgrinaker)

___
*[`pkg/server/config.go` line 240 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86866#-NAd-iJA6PxF-AmU0oc_:-NAd-iJA6PxF-AmU0oca:b-pl119p) ([raw file](https://github.com/cockroachdb/cockroach/blob/909219cf4075459cbf20ce61a448de16c487ab54/pkg/server/config.go#L240)):*
> ```Go
> 	// key-specific code paths in the storage layer. We'll also have to tweak
> 	// rangefeeds and batcheval to not choke on it.
> 	if envutil.EnvOrDefaultBool("COCKROACH_GLOBAL_MVCC_RANGE_TOMBSTONE", false) {
> ```

I thought we had some (linted) convention to put this in `var` declarations in the global scope, but I am evidently wrong since CI doesn't have a failed lint. Carry on, I guess?

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86866)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tbg)

___
*[`pkg/server/config.go` line 240 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86866#-NAd-iJA6PxF-AmU0oc_:-NAdOhEL9oGqYZ8wSOpD:b1t89re) ([raw file](https://github.com/cockroachdb/cockroach/blob/909219cf4075459cbf20ce61a448de16c487ab54/pkg/server/config.go#L240)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I thought we had some (linted) convention to put this in `var` declarations in the global scope, but I am evidently wrong since CI doesn't have a failed lint. Carry on, I guess?
</blockquote></details>

We do the same thing elsewhere, e.g. earlier in this file, so I figured it was fine -- especially since this is called once during server startup. I'd be more inclined to use a global var if we read it multiple times.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 31 of 31 files at r5, 30 of 31 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86866#-:-NAeICdNEFCnWiM7lx_g:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

**Comment by erikgrinaker** [comment]
TFTRs! CI failures are known flakes.

bors r=tbg,yuzefovich

**Pull request merged**
