### PR TITLE
roachtest/django: miscellaneous changes

### PR DESCRIPTION
**Pull request by otan**
We do this for /mnt/data1/django, so do django-cockroach too, just in
case. Not sure if it'll do anything, but just in case.

Refs: #80614

Release note: None

### CODE REVIEW

**Comment by timgraham** [comment]
I'm not sure if there's a reason why the repo needs to be cloned in the first place. I would advocate to replace the clone and install with `pip install django-cockroachdb 4.0.x` to always get the latest version from PyPI.

There are a couple of other obsolete things in this file that I noticed, namely `RUNNING_COCKROACH_BACKEND_TESTS=1` and `--parallel 1` are no longer needed.

**Comment by otan** [comment]
does `pip install django-cockroachdb 4.0.x` also bring the tests in?

i can remove the extraneous flags though.

**Comment by timgraham** [comment]
The test suite is in the Django repo, not in django-cockroachdb.

**Comment by otan** [comment]
> pip install django-cockroachdb 4.0.x

doesn't seem to work:

```
		Wraps: (5) pip3 install django-cockroachdb 4.0.x returned
		  | stderr:
		  | ERROR: Could not find a version that satisfies the requirement 4.0.x (from versions: none)
		  | ERROR: No matching distribution found for 4.0.x
		  |
		  | stdout:
		  | Defaulting to user installation because normal site-packages is not writeable
		  | Collecting django-cockroachdb
		  |   Using cached django_cockroachdb-4.0.1-py3-none-any.whl (25 kB)
```

**Comment by timgraham** [comment]
Sorry, that should be: `pip install django-cockroachdb==4.0.*`

**Review by timgraham — APPROVED** [review]

**Review by ZhouXing19 — APPROVED** [review]
Thanks!

**Pull request merged**
