### PR TITLE
roachtest: add basic AWS DMS roachtest

### PR DESCRIPTION
**Pull request by otan**
This commit adds a basic AWS DMS roachtest which creates an Amazon RDS
instance and a AWS DMS instance and replicates it to the roachtest's
CockroachDB instance.

It will attempt to destroy any created AWS resources on startup and on
shutdown, re-using the same names throughout so only one can ever exist.

Release note: None

### CODE REVIEW

**Review by ajstorm — CHANGES_REQUESTED** [review]
Did an initial pass and lefts some comments.  Will take a more detailed pass after you have a look at the comments.

> Reviewed 4 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-:-Mzp1y562Cu8n6Vx2YOt:b-9nkkhw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @stevendanna)

___
*[DEPS.bzl, line 357 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-MzonimR9IMkWVOLj2B_:-MzonimR9IMkWVOLj2Ba:b-2t7nvl) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae6595c03415b5a3380dd7bcb9bc8cdd249687b/DEPS.bzl#L357)):*
> ```Starlark
>         build_file_proto_mode = "disable_global",
>         importpath = "github.com/aws/aws-sdk-go-v2",
>         # TODO: mirror this repo (to fix, run `./dev generate bazel --mirror`)
> ```

I know very little about DEPS, but why are we left with these `TODO`s here?
___
*[pkg/cmd/roachtest/tests/awsdms.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-MzosDSU9fppIgNUWFjt:-MzosDSU9fppIgNUWFju:b-twgrf4) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae6595c03415b5a3380dd7bcb9bc8cdd249687b/pkg/cmd/roachtest/tests/awsdms.go#L47)):*
> ```Go
> 
> 	awsdmsWaitTimeLimit  = 30 * time.Minute
> 	awsdmsUser           = "cockroachdbtest"
> ```

Rather than hardcode the username and password, I'm wondering if we want to have them generated in this test and the reference the generated values.  Especially since this is in the public repo, I'm worried that having these credentials publicly available could expose us to bad actors trying to mess around with this database while it's in use for the test.
___
*[pkg/cmd/roachtest/tests/awsdms.go, line 155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-Mzp-hSu4esb01zPbMCt:-Mzp-hSu4esb01zPbMCu:b-9p8gfn) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae6595c03415b5a3380dd7bcb9bc8cdd249687b/pkg/cmd/roachtest/tests/awsdms.go#L155)):*
> ```Go
> 			t.L().Printf("found %d rows when expecting %d, retrying", numRows, awsdmsNumInitialRows)
> 		}
> 		return errors.Newf("failed to wait for target to be in sync")
> ```

Nit: Failed to _find_ target in sync?  Seems like we've done the waiting as requested.
___
*[pkg/cmd/roachtest/tests/awsdms.go, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-Mzou-BMEJJ9mvSd7XUZ:-Mzou-BMEJJ9mvSd7XU_:b-c9ks3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae6595c03415b5a3380dd7bcb9bc8cdd249687b/pkg/cmd/roachtest/tests/awsdms.go#L225)):*
> ```Go
> }
> 
> func setupDMSReplication(
> ```

Nit: This function is quite long.  I'm wondering if it makes sense to split it into separate functions for its various stages (setting up RDS cluster, creating table, setting up CRDB cluster, setting up Migration task, etc).   
___
*[pkg/cmd/roachtest/tests/awsdms.go, line 251 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-MzowFxU-zaEZDQN5kat:-MzowFxU-zaEZDQN5kau:b-emgdpr) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae6595c03415b5a3380dd7bcb9bc8cdd249687b/pkg/cmd/roachtest/tests/awsdms.go#L251)):*
> ```Go
> 				Parameters: []rdstypes.Parameter{
> 					{
> 						ParameterName:  proto.String("rds.logical_replication"),
> ```

Do we also need to do anything about `max_worker_processes` as outlined here: https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Source.PostgreSQL.html?
___
*[pkg/cmd/roachtest/tests/awsdms.go, line 253 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-MzowTpM1b3B9OEiWcXq:-MzowTpM1b3B9OEiWcXr:bogmv38) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae6595c03415b5a3380dd7bcb9bc8cdd249687b/pkg/cmd/roachtest/tests/awsdms.go#L253)):*
> ```Go
> 						ParameterName:  proto.String("rds.logical_replication"),
> 						ParameterValue: proto.String("1"),
> 						ApplyMethod:    rdstypes.ApplyMethodPendingReboot,
> ```

Nit: Does this imply that we need to reboot the cluster for it to take affect?  Or is the fact that we're applying this before we create the cluster sufficient?  In my tests using the console, I couldn't get it to take affect without rebooting the database, even when I applied it on database creation.
___
*[pkg/cmd/roachtest/tests/awsdms.go, line 338 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-MzoxQ9f33_PCGE6kkIH:-MzoxQ9f33_PCGE6kkII:b2mp3j) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae6595c03415b5a3380dd7bcb9bc8cdd249687b/pkg/cmd/roachtest/tests/awsdms.go#L338)):*
> ```Go
> 			fmt.Sprintf("CREATE USER %s", awsdmsCRDBUser),
> 			fmt.Sprintf("GRANT admin TO %s", awsdmsCRDBUser),
> 			"ALTER USER dms SET expect_and_ignore_not_visible_columns_in_copy = true",
> ```

Nit: Should you be using `awsdmsCRDBUser` here?
___
*[pkg/cmd/roachtest/tests/awsdms.go, line 363 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-MzoyAyCBi19mH3mICS8:-MzoyAyCBi19mH3mICS9:be1yp92) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae6595c03415b5a3380dd7bcb9bc8cdd249687b/pkg/cmd/roachtest/tests/awsdms.go#L363)):*
> ```Go
> 		replicationARN = *createReplOut.ReplicationInstance.ReplicationInstanceArn
> 		// Wait for replication instance to become available
> 		t.L().Printf("waiting for all replication instances to be available")
> ```

Nit: I think that there's only one replication instance we're setting up here.  To avoid confusion, can we remove the plural references in this statement?
___
*[pkg/cmd/roachtest/tests/awsdms.go, line 408 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-Mzoyhjn2X13fgFYatOo:-Mzoyhjn2X13fgFYatOp:b-c0x3iq) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae6595c03415b5a3380dd7bcb9bc8cdd249687b/pkg/cmd/roachtest/tests/awsdms.go#L408)):*
> ```Go
> 					DatabaseName: proto.String(awsdmsCRDBDatabase),
> 					Username:     proto.String(awsdmsCRDBUser),
> 					Password:     proto.String("garbage"),
> ```

Nit: Why don't we need a password here?  You might want a comment here explaining why.
___
*[pkg/cmd/roachtest/tests/awsdms.go, line 441 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-Mzoz3s17U06kq_KZRez:-Mzoz3s17U06kq_KZRf-:b-ewdcrs) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae6595c03415b5a3380dd7bcb9bc8cdd249687b/pkg/cmd/roachtest/tests/awsdms.go#L441)):*
> ```Go
>             "rule-name": "1",
>             "object-locator": {
>                 "schema-name": "%",
> ```

Nit: Should this be `public` only?
___
*[pkg/cmd/roachtest/tests/awsdms.go, line 533 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-Mzp1eDW4k7Y8QC8KCre:-Mzp1eDW4k7Y8QC8KCrf:b-nzwhlg) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae6595c03415b5a3380dd7bcb9bc8cdd249687b/pkg/cmd/roachtest/tests/awsdms.go#L533)):*
> ```Go
> 				l.Printf("deleting DMS endpoint %s (arn: %s)", *dmsEndpoint.EndpointIdentifier, *dmsEndpoint.EndpointArn)
> 				if _, err := dmsCli.DeleteEndpoint(ctx, &dms.DeleteEndpointInput{EndpointArn: dmsEndpoint.EndpointArn}); err != nil {
> 					return err
> ```

Nit: Does it make sense here to wrap all of the errors here with "Some resources were not cleaned up"?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79297)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @otan, and @stevendanna)

___
*[DEPS.bzl, line 357 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-MzonimR9IMkWVOLj2B_:-MzqHzJp0pc0u6NHXrNf:b-hglm1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae6595c03415b5a3380dd7bcb9bc8cdd249687b/DEPS.bzl#L357)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

I know very little about DEPS, but why are we left with these `TODO`s here?
</blockquote></details>

yeah [i couldn't get it to work](https://cockroachlabs.slack.com/archives/C019A8NANH0/p1649020206206439), fixed now though.
___
*[pkg/cmd/roachtest/tests/awsdms.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-MzosDSU9fppIgNUWFjt:-Mzq_pAH--QsbPp0B4U6:b-4fb8kz) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae6595c03415b5a3380dd7bcb9bc8cdd249687b/pkg/cmd/roachtest/tests/awsdms.go#L47)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Rather than hardcode the username and password, I'm wondering if we want to have them generated in this test and the reference the generated values.  Especially since this is in the public repo, I'm worried that having these credentials publicly available could expose us to bad actors trying to mess around with this database while it's in use for the test.
</blockquote></details>

it's a bit annoying to debug; but ok.
___
*[pkg/cmd/roachtest/tests/awsdms.go, line 251 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-MzowFxU-zaEZDQN5kat:-MzqaHOD63dsZHdZYByH:b-733a7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae6595c03415b5a3380dd7bcb9bc8cdd249687b/pkg/cmd/roachtest/tests/awsdms.go#L251)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Do we also need to do anything about `max_worker_processes` as outlined here: https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Source.PostgreSQL.html?
</blockquote></details>

not if we're using the default values
___
*[pkg/cmd/roachtest/tests/awsdms.go, line 253 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-MzowTpM1b3B9OEiWcXq:-MzqaJ8O8VAcADJyEscu:bz699lt) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae6595c03415b5a3380dd7bcb9bc8cdd249687b/pkg/cmd/roachtest/tests/awsdms.go#L253)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Does this imply that we need to reboot the cluster for it to take affect?  Or is the fact that we're applying this before we create the cluster sufficient?  In my tests using the console, I couldn't get it to take affect without rebooting the database, even when I applied it on database creation.
</blockquote></details>

yes, but we haven't started it yet.
also, immediate errors from AWS saying this option is pendingreboot only. adding a comment.
___
*[pkg/cmd/roachtest/tests/awsdms.go, line 363 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-MzoyAyCBi19mH3mICS8:-Mzqad8y4LR-zMDFgZhw:blu3zqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae6595c03415b5a3380dd7bcb9bc8cdd249687b/pkg/cmd/roachtest/tests/awsdms.go#L363)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: I think that there's only one replication instance we're setting up here.  To avoid confusion, can we remove the plural references in this statement?
</blockquote></details>

you never know, we may have plural in future!
___
*[pkg/cmd/roachtest/tests/awsdms.go, line 441 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-Mzoz3s17U06kq_KZRez:-MzqaqT45dmJR5Rxr4Cw:b-d8d4wz) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae6595c03415b5a3380dd7bcb9bc8cdd249687b/pkg/cmd/roachtest/tests/awsdms.go#L441)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Should this be `public` only?
</blockquote></details>

i'd rather replicate everything, in case, in the future

**Review by ajstorm — CHANGES_REQUESTED** [review]
> Reviewed 3 of 11 files at r1, 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79297)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @otan, and @stevendanna)

___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-MzubBWJ2yFUBIlpU-mC):*
Nit: ...and replicates _from the RDS instance_ to the roachtest's CockroachDB instance.
___
*[pkg/cmd/roachtest/tests/awsdms.go, line 251 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-MzowFxU-zaEZDQN5kat:-N-TgTxP4AHrFkg74XP4:b-2mt9t9) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae6595c03415b5a3380dd7bcb9bc8cdd249687b/pkg/cmd/roachtest/tests/awsdms.go#L251)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

not if we're using the default values
</blockquote></details>

I thought that when I ran my tests the default values were less than the recommendations in that link.  This test is small though, so maybe it doesn't matter.
___
*[pkg/cmd/roachtest/tests/awsdms.go, line 253 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-MzowTpM1b3B9OEiWcXq:-N-Th-yI1lgMd54XYn7O:bnmkctp) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae6595c03415b5a3380dd7bcb9bc8cdd249687b/pkg/cmd/roachtest/tests/awsdms.go#L253)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

yes, but we haven't started it yet.
also, immediate errors from AWS saying this option is pendingreboot only. adding a comment.
</blockquote></details>

Am I missing the comment?  Or has it not yet been added?
___
*[pkg/cmd/roachtest/tests/awsdms.go, line 363 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-MzoyAyCBi19mH3mICS8:-N-ThUxj95h5fGfavyW2:bprt14w) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae6595c03415b5a3380dd7bcb9bc8cdd249687b/pkg/cmd/roachtest/tests/awsdms.go#L363)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

you never know, we may have plural in future!
</blockquote></details>

Fair, but until we do?
___
*[pkg/cmd/roachtest/tests/awsdms.go, line 481 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-N-TkeSo28e9zkWQstbp:-N-TkeSo28e9zkWQstbq:b6w3ptt) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae6595c03415b5a3380dd7bcb9bc8cdd249687b/pkg/cmd/roachtest/tests/awsdms.go#L481)):*
> ```Go
> 	ctx context.Context, l *logger.Logger, rdsCli *rds.Client, dmsCli *dms.Client,
> ) error {
> 	// Delete DMS tasks, endpoints and replication instances that may be created.
> ```

Nit: This comment should go above the function, and we should have a comment here which states that we're tearing down the replication tasks.
___
*[pkg/cmd/roachtest/tests/awsdms.go, line 626 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-N-Tnlmq4FUIyjzdB-t8:-N-Tnlmq4FUIyjzdB-t9:bfn9ewd) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae6595c03415b5a3380dd7bcb9bc8cdd249687b/pkg/cmd/roachtest/tests/awsdms.go#L626)):*
> ```Go
> 				l.Printf("attempting to delete param group %s", *rdsGroup.DBClusterParameterGroupName)
> 
> 				// This can sometimes fail as the cluster still relies on the param
> ```

Why try to do this in parallel?  Shouldn't the param group delete be fast?  This code is complex, and making it occur serially after the RDS delete will simplify things.
___
*[pkg/cmd/roachtest/tests/awsdms.go, line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-N-T8J4J8WE7lJzP4e-z:-N-T8J4J8WE7lJzP4e0-:b-cgu8ek) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3a89bf7d18eb1f47c74aa2b42a229a26e99ef97/pkg/cmd/roachtest/tests/awsdms.go#L48)):*
> ```Go
> 	awsdmsWaitTimeLimit  = 30 * time.Minute
> 	awsdmsUser           = "cockroachdbtest"
> 	awsdmsDatabase       = "testdb"
> ```

Nit: "rdsdb"?
___
*[pkg/cmd/roachtest/tests/awsdms.go, line 100 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-N-TAqP86CttcIYZYDlS:-N-TAqP86CttcIYZYDlT:b4pkgux) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3a89bf7d18eb1f47c74aa2b42a229a26e99ef97/pkg/cmd/roachtest/tests/awsdms.go#L100)):*
> ```Go
> func runAWSDMS(ctx context.Context, t test.Test, c cluster.Cluster) {
> 	if c.IsLocal() {
> 		t.Fatal("cannot be run in local mode")
> ```

Nit: worth a comment here?  I'm assuming this is because the cluster has to be publicly accessible to AWS DMS?
___
*[pkg/cmd/roachtest/tests/awsdms.go, line 110 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-N-TC-O0DOzvJ1-qKdH6:-N-TC-O0DOzvJ1-qKdH7:b73eq9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3a89bf7d18eb1f47c74aa2b42a229a26e99ef97/pkg/cmd/roachtest/tests/awsdms.go#L110)):*
> ```Go
> 	dmsCli := dms.NewFromConfig(awsCfg)
> 
> 	// Attempt a clean-up of new instances on startup.
> ```

Nit: "old instances"?
___
*[pkg/cmd/roachtest/tests/awsdms.go, line 205 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-N-TDso-BwISZKrIbdKr:-N-TDso-BwISZKrIbdKs:b-2fwgo2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3a89bf7d18eb1f47c74aa2b42a229a26e99ef97/pkg/cmd/roachtest/tests/awsdms.go#L205)):*
> ```Go
> 					return err
> 				}
> 				expectedRows := awsdmsNumInitialRows + numExtraRows - 1
> ```

Nit: Instead of the `-1` here, should we have a "numDeletedRows" const?
___
*[pkg/cmd/roachtest/tests/awsdms.go, line 224 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-N-TMJ2cBVPSypxtB97O:-N-TMJ2cBVPSypxtB97P:bnt8j9n) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3a89bf7d18eb1f47c74aa2b42a229a26e99ef97/pkg/cmd/roachtest/tests/awsdms.go#L224)):*
> ```Go
> }
> 
> func setupAWSDMS(
> ```

Nit: Could use a comment here as to what we're doing in this function.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79297)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @otan, and @stevendanna)

___
*[pkg/cmd/roachtest/tests/awsdms.go, line 253 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-MzowTpM1b3B9OEiWcXq:-N-V0-kv7J6sOiMK4ie0:b823b7p) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae6595c03415b5a3380dd7bcb9bc8cdd249687b/pkg/cmd/roachtest/tests/awsdms.go#L253)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Am I missing the comment?  Or has it not yet been added?
</blockquote></details>

appending `, so using `ApplyMethodPendingReboot` instead` to make ti clear this is what it addresses, but it was added.
___
*[pkg/cmd/roachtest/tests/awsdms.go, line 626 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-N-Tnlmq4FUIyjzdB-t8:-N-V0K0yED1IPLw9dXpM:b-oms9sj) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae6595c03415b5a3380dd7bcb9bc8cdd249687b/pkg/cmd/roachtest/tests/awsdms.go#L626)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Why try to do this in parallel?  Shouldn't the param group delete be fast?  This code is complex, and making it occur serially after the RDS delete will simplify things.
</blockquote></details>

the param group delete can only happen when the cluster is deleted. the cluster can take a while to be deleted, but as mentioned in the comment, there was no waiter method on the cluster being deleted with the SDK.

we aren't doing this in parallel; just with retries?

**Review by ajstorm — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-:-N02zGQJBijG9wtoUjfl:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @otan, and @stevendanna)

___
*[pkg/cmd/roachtest/tests/awsdms.go, line 626 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79297#-N-Tnlmq4FUIyjzdB-t8:-N02zCSZ6r27HpktHDEH:b3dwuyb) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae6595c03415b5a3380dd7bcb9bc8cdd249687b/pkg/cmd/roachtest/tests/awsdms.go#L626)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

the param group delete can only happen when the cluster is deleted. the cluster can take a while to be deleted, but as mentioned in the comment, there was no waiter method on the cluster being deleted with the SDK.

we aren't doing this in parallel; just with retries?
</blockquote></details>

ah, makes sense

**Comment by otan** [comment]
bors r=ajstorm

**Pull request merged**
