### PR TITLE
opt: Enable additional logic tests for opt configs

### PR DESCRIPTION
**Pull request by andy-kimball**
Enable more logic tests (spool -> with).
Fix various bugs and issues that were failing tests.

### CODE REVIEW

**Comment by rytaft** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/sql/logictest/testdata/logic_test/suboperators, line 270 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26177#-LDhSmEn30e7Otr_S6Rm:-LDhSmEn30e7Otr_S6Rn:b-megf8j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2bb5424684a376bf404af660fed22466570ac9b/pkg/sql/logictest/testdata/logic_test/suboperators#L270)):*
> ```
> false
> 
> query III rowsort
> ```

why do we need rowsort if there is an order by clause?

---

*[pkg/sql/logictest/testdata/logic_test/suboperators, line 331 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26177#-LDhSqE1CL2R6gefgy4D:-LDhSqE1CL2R6gefgy4E:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2bb5424684a376bf404af660fed22466570ac9b/pkg/sql/logictest/testdata/logic_test/suboperators#L331)):*
> ```
> NULL
> 
> query III rowsort
> ```

ditto

---

*[pkg/sql/logictest/testdata/logic_test/union, line 87 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26177#-LDhWVOs4hQ6gtV2bcYl:-LDhWVOs4hQ6gtV2bcYm:b-iz3z9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/e63241a85e7b56c54e82e44ef63c388ad0e76284/pkg/sql/logictest/testdata/logic_test/union#L87)):*
> ```
> 
> query IT
> SELECT x, pg_typeof(y) FROM (SELECT 1, 3 UNION ALL SELECT 2, NULL) AS t(x, y)
> ```

This is a duplicate with the test below

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26177#-:-LDhY02S9ZcZRIiCOpXq:bnfp4nl)*

**Comment by andy-kimball** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/logictest/testdata/logic_test/suboperators, line 270 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26177#-LDhSmEn30e7Otr_S6Rm:-LDhcbgg8eTnoazvEFu4:b-47inzu) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2bb5424684a376bf404af660fed22466570ac9b/pkg/sql/logictest/testdata/logic_test/suboperators#L270)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

why do we need rowsort if there is an order by clause?
</blockquote></details>

Was my mistake. Removed.

---

*[pkg/sql/logictest/testdata/logic_test/suboperators, line 331 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26177#-LDhSqE1CL2R6gefgy4D:-LDhcex4-LzO1cN2XeDn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2bb5424684a376bf404af660fed22466570ac9b/pkg/sql/logictest/testdata/logic_test/suboperators#L331)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

---

*[pkg/sql/logictest/testdata/logic_test/union, line 87 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26177#-LDhWVOs4hQ6gtV2bcYl:-LDhcqLSAHc2p5juNPgF:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e63241a85e7b56c54e82e44ef63c388ad0e76284/pkg/sql/logictest/testdata/logic_test/union#L87)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This is a duplicate with the test below
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26177)*

**Comment by rytaft** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26177)*

**Comment by RaduBerinde** [comment]
LGTM

**Comment by RaduBerinde** [comment]
Shouldn't `opt` be enabled for `tuple`?

**Comment by RaduBerinde** [comment]
And `union`

**Comment by andy-kimball** [comment]
Regarding `tuple`, and `union`, I'll enable them as part of the "straggler" pass I'm doing right now. I caught a couple more that hadn't been enabled.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26177#-:-LDhtwaq0z4QZcuZ4V5l:b-amnbf)*

**Pull request merged**
