### PR TITLE
rfc: computed column change to information_schema

### PR DESCRIPTION
**Pull request by justinj**
This can be bikeshedded, I just wanted to put this up for some level of
discussion (and I wasn't sure if we had any prior art on how to handle changes like this).

Release note: None

### CODE REVIEW

**Comment by danhhz** [comment]
:lgtm: but we should probably get someone that's spent more time dealing with compatibility with orms etc to sign off, too

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[docs/RFCS/20171214_computed_columns.md, line 134 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21677#-L3UkcdgjKbCrDjivM5l:-L3UkcdgjKbCrDjivM5m:b5kztn7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b16571013f909459b88d50005b1b05d14631a11/docs/RFCS/20171214_computed_columns.md#L134)):*
> ```Markdown
> feature, we will match [MySQL's extension] to `information_schema`, which is to
> add an extra `TEXT` column `generation_expression` to the
> `information_schema.columns` table which is empty for non-computed columns and
> ```

empty or NULL?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21677#-:-L3UkgxwEiEoBE6i5UZa:b-bfrtkz)*

**Comment by justinj** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[docs/RFCS/20171214_computed_columns.md, line 134 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21677#-L3UkcdgjKbCrDjivM5l:-L3UlbJgZBvfr1MjKv8V:b-grklw0) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b16571013f909459b88d50005b1b05d14631a11/docs/RFCS/20171214_computed_columns.md#L134)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

empty or NULL?
</blockquote></details>

empty, surprisingly:
```
mysql> select generation_expression = '', generation_expression is null from information_schema.columns limit 1;
+----------------------------+-------------------------------+
| generation_expression = '' | generation_expression is null |
+----------------------------+-------------------------------+
|                          1 |                             0 |
+----------------------------+-------------------------------+
1 row in set (0.03 sec)
```
I would be open to making it NULL (which to me seems like it would make more sense) given that this is already a Postgres divergence, but I don't feel particularly strongly either way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21677)*

**Comment by jordanlewis** [comment]
I believe `information_schema` is more than just a MySQL feature - parts of it are available in the SQL standard. I don't think we should deviate from what MySQL is doing here, both for compatibility with MySQL and potentially for compatibility with the standard.

Also, check out GitHub code search - lots of hits for `generation_expression`, with snippets like `GENERATION_EXPRESSION  <> ''`.

https://github.com/search?p=4&q=generation_expression&type=Code&utf8=%E2%9C%93

**Comment by justinj** [comment]
`information_schema` itself is standard, but `generation_expression` is listed as a MySQL extension on their page: https://dev.mysql.com/doc/refman/5.7/en/columns-table.html

Given people's apparent widespread familiarity with it though, I guess we should probably match MySQL.

**Comment by nvanbenschoten** [comment]
LGTM. I agree on matching MySQL's extension with the extra column. Every database I've looked at extends `information_schema` with extra columns. I've never seen this be a problem because nothing even remotely portable would ever perform a `SELECT *` on an `information_schema` table. 

In general, we've taken a somewhat middle ground between Postgres and MySQL, adding columns that make sense from both. I think we actually follow MySQL more closely because Postgres' `information_schema` is arguably incomplete, presumably because they already have `pg_catalog`. With that in mind, following MySQL's lead here with the `generation_expression` column is well precedented.

**Comment by justinj** [comment]
TFTRs y'all

**Pull request merged**
