### PR TITLE
release-22.2: sql: add crdb_internal.stmt_stats_persisted_v22_1

### PR DESCRIPTION
**Pull request by xinhaoz**
## Commit 1
New view crdb_internal.stmt_stats_persisted_v22_1, which is exactly the 
same as crdb_internal.statement_statistics_persisted but without the 
index_recommendations column, is added for mixed 22.1 and 22.2 clusters. 
This ensures the sql activity pages can continue to work during upgrade as 
requested need to be serviced from this table.
This table is needed in addition to the existing crdb_internal v22_1
statement_statistics table as that table is used to read in-memory
stats data.

Epic: none

Release note: None

## Commit 2
server: properly version all queries in combinedstmts

The index_recommendations column was added to the statement_statistics
internal table as of 22.2. Since we read the statement stats table
using an internal view, we created a v22_1 table without the
index_recommendations for use during 22.1 -> .2 upgrades. A newly
added query that gets stmt and txn total runtime was not properly reading
from this table when the cluster was in a mixed version state causing
the query to fail and for the stmts page to error during upgrades.
This commit properly introduces the check to read from the correct
tables during upgrade.

Epic: none

Release note (bug fix): SQL activity page should load data during 22.1 to 22.2 ugprades.

## Commit 3
sqlstats: check if index_recs should be updated in flush

The `index_recommendations` column should only be included
in the sql stats update stmt if the column has been added
on all nodes.

Epic: none

Release note (bug fix): Previously flushing sql stats that
would result in an update stmt during mixed version 22.1/22.2
clusters would fail due to attempting to update the
index_recommendations column, which is new in 22.2.

Fixes: https://github.com/cockroachdb/cockroach/issues/105761

Release justification: bug fix to prevent page from being unresponsive during upgrades

https://www.loom.com/share/ef6cf167b72d430ab9ed91ac3e9223f2

### CODE REVIEW

**Comment by rytaft** [comment]
Thanks for fixing this, @xinhaoz! Just a drive by comment: Can you please open a public GitHub issue (to be fixed by this PR) to document this bug in case others run into it?

**Comment by xinhaoz** [comment]
@rytaft Yup! Already done, just forgot to add it to the description after updating the commits - updated now!

**Comment by rytaft** [comment]
> @rytaft Yup! Already done, just forgot to add it to the description after updating the commits - updated now!

Thanks!

**Review by maryliag — CHANGES_REQUESTED** [review]
I'm a little confused about this PR, isn't this exactly what this [commit](https://github.com/cockroachdb/cockroach/commit/c31fdb01ce0f3b4c74720b0278383b8db03e6a63) was created for?
the view created on that PR was a stats view without the idx recommendation, and you're creating another on this PR, why isn't that one the one used and a new one had to be created? With this change, seems like that view is not longer used.
Also, seems like you're using the new 22_1 view in some places here without checking the version, meaning it will always ignore the idx recommendation on 22.2, and we don't want that.

> Reviewed 10 of 10 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105664#-:-NZX5mrv2TG7Pvs4m7M7:b-q4i6no)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`pkg/server/combined_statement_stats.go` line 233 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105664#-NZX6LVpAUMpuw11cQ_A:-NZX35T54KtLlR8fgKZY:ba0vp46) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1a2ee807c0de1f48e9965122fa12f0a4f05ea0c/pkg/server/combined_statement_stats.go#L233)):*
> ```Go
> 	if req.FetchMode == nil || req.FetchMode.StatsType != serverpb.CombinedStatementsStatsRequest_TxnStatsOnly {
> 		stmtsRuntime, err = getRuntime(
> 			"crdb_internal.stmt_stats_persisted_v22_1", "crdb_internal.statement_statistics_v22_1")
> ```

this is not right, because now on 22.2 you're always using the 22_1 view. You should be checking the cluster version and adding the right suffix per case
___
*[`pkg/sql/sqlstats/persistedsqlstats/flush.go` line 501 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/105664#-NZX6ZBL0I1Mb1vQHRQP:-NZX6ZBL0I1Mb1vQHRQQ:b-e6d4hj) ([raw file](https://github.com/cockroachdb/cockroach/blob/647d47ace8920c1ba44eed51fc2f0f302d9016d0/pkg/sql/sqlstats/persistedsqlstats/flush.go#L501)):*
> ```Go
> WHERE fingerprint_id = $2
>   AND transaction_fingerprint_id = $3
> 	AND aggregated_ts = $4
> ```

nit: alignment

**Review by xinhaoz — COMMENTED** [review]
@maryliag I did consider using the previous table created for v22_1, but that's the combined in-memory one. I wasn't sure if we wanted to lose the performance improvements from reading only the system table in mixed-version, which is why I created a new view. If it's fine to just do in-memory for mixed versions I can remove this new view for the system table without index_recs!  The old one is still used when we fallback to in-memory for mixed versions. As for the places where I'm using only the v22_1 table, those are only for the queries that don't need index_recs, so I thought i'd skip the extra check since the view is from the same source tables. LMK what you think!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105664#-:-NZagf0GA079OYLMi6EN:bgwzmjv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/server/combined_statement_stats.go` line 233 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105664#-NZX6LVpAUMpuw11cQ_A:-NZagDCkARka0Gpjw7H2:b2eon00) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1a2ee807c0de1f48e9965122fa12f0a4f05ea0c/pkg/server/combined_statement_stats.go#L233)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

this is not right, because now on 22.2 you're always using the 22_1 view. You should be checking the cluster version and adding the right suffix per case
</blockquote></details>

For this query, we don't read the index_recommendations column. So I didn't think it was necessary to do those checks, unless I'm missing something that would be different between the two tables for this query.

**Review by maryliag — APPROVED** [review]
I see. Makes sense!
Can you add that explanation to the commit message, so we have more details in case someone looks into this in the future?

otherwise :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105664#-:-NZapfcZCCcU3Qs6teQu:bcrxosd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

**Pull request merged**
