### PR TITLE
gossip: block until client disconnects

### LINKED ISSUE #7791: stress: failed test in cockroach/gossip/gossip.test: TestGossipCullNetwork
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/ee73b1d854981df7e7841466492f52252f2dacaf

Stress build found a failed test:

```
=== RUN   TestGossipCullNetwork
W160713 05:31:50.808749 gossip/gossip.go:934  not connected to cluster; use --join to specify a connected node
W160713 05:31:50.810334 gossip/gossip.go:934  not connected to cluster; use --join to specify a connected node
I160713 05:31:50.812738 gossip/gossip.go:960  starting client to 127.0.0.1:36985
W160713 05:31:50.812833 gossip/gossip.go:934  not connected to cluster; use --join to specify a connected node
I160713 05:31:50.817952 gossip/gossip.go:960  starting client to 127.0.0.1:33525
W160713 05:31:50.818053 gossip/gossip.go:934  not connected to cluster; use --join to specify a connected node
I160713 05:31:50.819533 gossip/gossip.go:960  starting client to 127.0.0.1:43814
W160713 05:31:50.837268 gossip/gossip.go:938  partition in gossip network; attempting new connection
W160713 05:31:50.837295 gossip/gossip.go:938  partition in gossip network; attempting new connection
--- FAIL: TestGossipCullNetwork (15.11s)
	testing.go:113: condition failed to evaluate within 15s: no network culling occurred
```

Run Details:

```
83 runs so far, 0 failures, over 5s
182 runs so far, 0 failures, over 10s
276 runs so far, 0 failures, over 15s
371 runs so far, 0 failures, over 20s
461 runs so far, 0 failures, over 25s
549 runs so far, 0 failures, over 30s
598 runs completed, 1 failures, over 33s
FAIL
```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by tamird**
Fixes #7791.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7810)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 1 of 1 files at r4.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[gossip/gossip.go, line 969 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7810#-KM_G5MR9-cf9AYHDbnU:-KM_G5MR9-cf9AYHDbnV:-195412561) ([raw file](https://github.com/cockroachdb/cockroach/blob/82369cc3d4e3ebdfbff088462536895e28b499c4/gossip/gossip.go#L969)):*
> ```Go
> 	if c := g.findClient(func(c *client) bool { return c.peerID == nodeID }); c != nil {
> 		c.close()
> 		g.doDisconnected(<-g.disconnected) // block until the client has disconnected
> ```

Feels awkward to to `<-g.disconnected` here as `Gossip.manage` is the normal place that channel is accessed. I wonder if it would be better for `closeClient()` and `cullNetwork()` to return a boolean to indicate a client was closed and then `Gossip.manage` could block on `<-g.disconnected` before continuing. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7810#-:-KM_GVs2fOMMtrEACMZq:1417088721)*

**Comment by tamird** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[gossip/gossip.go, line 969 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7810#-KM_G5MR9-cf9AYHDbnU:-KM_TBQAFk_k0EiHql2g:-68253086) ([raw file](https://github.com/cockroachdb/cockroach/blob/82369cc3d4e3ebdfbff088462536895e28b499c4/gossip/gossip.go#L969)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Feels awkward to to `<-g.disconnected` here as `Gossip.manage` is the normal place that channel is accessed. I wonder if it would be better for `closeClient()` and `cullNetwork()` to return a boolean to indicate a client was closed and then `Gossip.manage` could block on `<-g.disconnected` before continuing. 
</details>
Yeah, that's a bit awkward, and yet I find it surprising that `closeClient` doesn't block until the client is gone. I'd rather leave it like this. WDYT?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7810)*

**Comment by petermattis** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[gossip/gossip.go, line 969 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7810#-KM_G5MR9-cf9AYHDbnU:-KM_WGnZOIZwzFy-aShe:-1710062266) ([raw file](https://github.com/cockroachdb/cockroach/blob/82369cc3d4e3ebdfbff088462536895e28b499c4/gossip/gossip.go#L969)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Yeah, that's a bit awkward, and yet I find it surprising that `closeClient` doesn't block until the client is gone. I'd rather leave it like this. WDYT?
</details>
Ok, but probably worthwhile to add a comment to `closeClient` and `cullNetwork` that they should only be called from `manage`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7810)*

**Comment by tamird** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[gossip/gossip.go, line 969 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7810#-KM_G5MR9-cf9AYHDbnU:-KM_d9vhb5BOhR1DDK96:-1401200481) ([raw file](https://github.com/cockroachdb/cockroach/blob/82369cc3d4e3ebdfbff088462536895e28b499c4/gossip/gossip.go#L969)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Ok, but probably worthwhile to add a comment to `closeClient` and `cullNetwork` that they should only be called from `manage`.
</details>
Why is it required that they're only called from `manage`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7810)*

**Comment by petermattis** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[gossip/gossip.go, line 969 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7810#-KM_G5MR9-cf9AYHDbnU:-KM_drrwjoTcrEExoygg:325645884) ([raw file](https://github.com/cockroachdb/cockroach/blob/82369cc3d4e3ebdfbff088462536895e28b499c4/gossip/gossip.go#L969)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Why is it required that they're only called from `manage`?
</details>
`Gossip.manage` is also reading from `g.disconnected`. Seems fragile for other code to be doing so concurrently, unless that is by design in which it should be called out. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7810)*

**Comment by tschottdorf** [comment]
Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7810)*

**Comment by tamird** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[gossip/gossip.go, line 969 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7810#-KM_G5MR9-cf9AYHDbnU:-KM_ejbNvtRJrzUAMedR:1272438858) ([raw file](https://github.com/cockroachdb/cockroach/blob/82369cc3d4e3ebdfbff088462536895e28b499c4/gossip/gossip.go#L969)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `Gossip.manage` is also reading from `g.disconnected`. Seems fragile for other code to be doing so concurrently, unless that is by design in which it should be called out. 
</details>
Oh, I see what you're saying. Indeed, this is racy if called from anything other than `manage()`. Added a commit that removes the pretense of reusability of these methods.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7810)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[gossip/gossip.go, line 848 \[r11\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7810#-KMaqxfFQvJXd-nV0dIZ:-KMaqxfFQvJXd-nV0dI_:-336422902) ([raw file](https://github.com/cockroachdb/cockroach/blob/ade1f91ba1143067315cb87ef9ad579f39583e92/gossip/gossip.go#L848)):*
> ```Go
> 				if leastUsefulID == 0 {
> 					if log.V(1) {
> 						log.Infof("couldn't find least useful client to close")
> ```

Perhaps output `g.outgoing` in this log message.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7810#-:-KMar3OlOm_o0wnZ6r44:1417088721)*

**Comment by tamird** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[gossip/gossip.go, line 848 \[r11\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7810#-KMaqxfFQvJXd-nV0dIZ:-KMaxldeJpRJuYGpsa0s:2104878115) ([raw file](https://github.com/cockroachdb/cockroach/blob/ade1f91ba1143067315cb87ef9ad579f39583e92/gossip/gossip.go#L848)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Perhaps output `g.outgoing` in this log message.
</details>
Had to rejigger the locking in this function to achieve that, PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7810)*

**Comment by petermattis** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[gossip/gossip.go, line 848 \[r11\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7810#-KMaqxfFQvJXd-nV0dIZ:-KMaz9NOuwNwtVPTI5dJ:477551211) ([raw file](https://github.com/cockroachdb/cockroach/blob/ade1f91ba1143067315cb87ef9ad579f39583e92/gossip/gossip.go#L848)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Had to rejigger the locking in this function to achieve that, PTAL.
</details>
It would have been easier to move the logging of `leaseUsefulID` into your old `leaseUsefulID` function. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7810)*

**Comment by tamird** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[gossip/gossip.go, line 848 \[r11\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7810#-KMaqxfFQvJXd-nV0dIZ:-KMb0MpWAz_IkBnuWsd4:1408883134) ([raw file](https://github.com/cockroachdb/cockroach/blob/ade1f91ba1143067315cb87ef9ad579f39583e92/gossip/gossip.go#L848)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> It would have been easier to move the logging of `leaseUsefulID` into your old `leaseUsefulID` function. 
</details>
You mean the logging of g.clients/g.outgoing? Maybe, but this avoids zero-as-sentinel as well, which I like.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7810)*

**Pull request merged**
