### PR TITLE
demo: Add option to automatically apply the Geo-Partitioned Replicas topology to Movr

### PR DESCRIPTION
**Pull request by rohany**
Work for #39945.

This PR adds a Partition function to the workload.Hooks struct so that
workloads that have a partitioning step can just implement that function
within the workload package.

Release note (cli change): Add an option for cockroach demo to
automatically apply the geo-partitioned replicas topology to the movr
dataset using the --geo-partitioned-replicas flag.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40355)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @jordanlewis, and @rohany)

___
*[pkg/cli/demo.go, line 446 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-LnW5spbEuSWCihxre0m:-LnW5spbEuSWCihxre0n:b6u0k8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ad176f2234c1040013f22d2985dba2e9aede9c3/pkg/cli/demo.go#L446)):*
> ```Go
> 	// Make sure that the user didn't request to have a topology and an empty database.
> 	if demoCtx.geoPartitionedReplicas && demoCtx.useEmptyDatabase {
> 		return errors.New("cannot setup geo-partitioned replicas topology on an empty database")
> ```

This is guaranteed to fail if an enterprise license could not be acquired. 

I would recommend to make a test in a a way that guarantees the enterprise license is not available, and verify that `demo` still work.
___
*[pkg/workload/movr/movr.go, line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-LnW6A0K5NnYrAQwnaU4:-LnW6A0K5NnYrAQwnaU5:b7mxzhq) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ad176f2234c1040013f22d2985dba2e9aede9c3/pkg/workload/movr/movr.go#L116)):*
> ```Go
> 	{city: "los angeles", locality: "us_west"},
> 	// The demo setup we have is a 9 node, 3 region cluster.
> 	//{city: "chicago", locality: "us_central"},
> ```

Don't comment out things - simply delete them. We have version control so if we want them again we can restore them.

(Also I think this change is not desirable - are you sure about it?)

**Comment by rohany** [comment]
Sorrry, I should have marked this WIP — I’ll update the pr based on your comments.

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40355)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @jordanlewis, and @rohany)

___
*[pkg/cli/cliflags/flags.go, line 924 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-LnXsatLEdyE3cYglVUu:-LnXsatLEdyE3cYglVUv:b-dgc2ug) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ad176f2234c1040013f22d2985dba2e9aede9c3/pkg/cli/cliflags/flags.go#L924)):*
> ```Go
> 		Name: "geo-partitioned-replicas",
> 		Description: `
> Create a 9 node cluster preloaded with the Movr dataset, and automatically apply
> ```

This should probably say something about "when used with the movr dataset (which is the default)" and then error if another dataset is used

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40355)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @jordanlewis, and @knz)

___
*[pkg/cli/demo.go, line 446 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-LnW5spbEuSWCihxre0m:-Lnj9ERI24eHT4O84d6Y:b-ryaw65) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ad176f2234c1040013f22d2985dba2e9aede9c3/pkg/cli/demo.go#L446)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This is guaranteed to fail if an enterprise license could not be acquired. 

I would recommend to make a test in a a way that guarantees the enterprise license is not available, and verify that `demo` still work.
</blockquote></details>

The test I added to the demo (disabling telemetry and expecting success) should test this. However, if there is an error with partitioning, I think that demo should error out.
___
*[pkg/workload/movr/movr.go, line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-LnW6A0K5NnYrAQwnaU4:-LnjAOQC6ZmgmbLiD_yD:b4irodh) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ad176f2234c1040013f22d2985dba2e9aede9c3/pkg/workload/movr/movr.go#L116)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Don't comment out things - simply delete them. We have version control so if we want them again we can restore them.

(Also I think this change is not desirable - are you sure about it?)
</blockquote></details>

I'm not sure what to do here then -- we could increase the number of nodes in this setup to 12 to have a 4 region cluster using all of the movr cities, or just delete the us-central region from the demo dataset. I'm open to either, but I'm leaning towards just removing some cities?

**Comment by rohany** [comment]
Friendly ping

**Comment by danhhz** [comment]
Oh, sorry! I would guess people have been staying away from this because it still has "wip" in the title. For the future, our emergent convention here seems to be removing the "wip" and leaving a comment to the effect of "this should be good to go" or "this is ready for review" : - )

I took a look again and the approach seems fine to me, but there were a bunch of conversations about how the license stuff should work that I wasn't in, so I'll leave the review to someone that was.

**Comment by rohany** [comment]
Sorry -- thats my bad.

**Review by knz — COMMENTED** [review]
> Reviewed 7 of 7 files at r3, 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40355)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @jordanlewis, and @rohany)

___
*[pkg/cli/demo.go, line 446 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-LnW5spbEuSWCihxre0m:-Lo0t9xq0kwbP0tcW6q1:buoj6kn) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ad176f2234c1040013f22d2985dba2e9aede9c3/pkg/cli/demo.go#L446)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

The test I added to the demo (disabling telemetry and expecting success) should test this. However, if there is an error with partitioning, I think that demo should error out.
</blockquote></details>

I suppose that can be asserted in a test too, can't it?
___
*[pkg/cli/demo.go, line 129 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-Lo0tRjUBDDhwviT4Uk0:-Lo0tRjV1sKpireg-a-f:b-br0alm) ([raw file](https://github.com/cockroachdb/cockroach/blob/31b91324b7c05c9e42dcd5e515224cdfdfc20c55/pkg/cli/demo.go#L129)):*
> ```Go
> 	// This demo only works on a 9 node cluster, so set the node count as such.
> 	// Ignore input user localities.
> 	if demoCtx.geoPartitionedReplicas {
> ```

I think it's important to inform the user when they use contradictory settings. Otherwise they will be under the mistaken assumption that, if no error is produced, their desired number of nodes was respected.

You can test whether a flag was set using `pflag.Lookup(...).Changed`.
___
*[pkg/cli/demo.go, line 274 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-Lo0u-Mr6014tGQv7h5L:-Lo0u-Ms0Co2YuEvC3ve:b3trxni) ([raw file](https://github.com/cockroachdb/cockroach/blob/31b91324b7c05c9e42dcd5e515224cdfdfc20c55/pkg/cli/demo.go#L274)):*
> ```Go
> 		// If we are requested to prepartition our data, and the
> 		// specified dataset is Movr, spawn a goroutine to do the partitioning.
> 		if demoCtx.geoPartitionedReplicas && gen.Meta().Name == "movr" {
> ```

Also please reject a combination of flags when a user specifies another dataset and also geo-partitioned replicas, as we are unable to honor their request  in that case.
___
*[pkg/cli/demo.go, line 294 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-Lo0tgzi2mhytV2X77r8:-Lo0tgzi2mhytV2X77r9:bjzmvx4) ([raw file](https://github.com/cockroachdb/cockroach/blob/31b91324b7c05c9e42dcd5e515224cdfdfc20c55/pkg/cli/demo.go#L294)):*
> ```Go
> 		}
> 
> 		// TODO (rohany): Should we wait until partitioning is done
> ```

yes that seems like a good plan.

Also: is the workload meant to be ran synchronously like this? As-is it will prevent the interactive session from startinig. Isn't it better to have the workload run in the background (in a goroutine) while the user has access to the itneractive shell?
___
*[pkg/cli/demo.go, line 306 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-Lo0uAzHDQSOcBIVOa1a:-Lo0uAzHDQSOcBIVOa1b:bqivnr4) ([raw file](https://github.com/cockroachdb/cockroach/blob/31b91324b7c05c9e42dcd5e515224cdfdfc20c55/pkg/cli/demo.go#L306)):*
> ```Go
> }
> 
> func setupGeoPartitionedReplicas(db *gosql.DB) error {
> ```

This looks like a possible API extension to the workload generator interface. 
It seems weird to me to have code specific to the `movr` workload hanging in the `cli` package. Instead I'd say this code should be in the `movr` workload (in a place where folk who later change the workload will think about!), and reachable via a new method on the interface, perhaps `PreparePartitioning()`. That method would (presumably) be a no-op for the other workloads, until/unless we find interest into partitioning other workloads.

(Actually tpc-c has partitioning code defined already, but I'd recommend against you trying to look into this in the same PR, so presumably you'd leave a TODO in the tpc-implemenation of `PreparePartitioning()`)
___
*[pkg/cli/cliflags/flags.go, line 925 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-Lo0umTwAhao2JjxCmRj:-Lo0umTwAhao2JjxCmRk:byb6kmq) ([raw file](https://github.com/cockroachdb/cockroach/blob/31b91324b7c05c9e42dcd5e515224cdfdfc20c55/pkg/cli/cliflags/flags.go#L925)):*
> ```Go
> 		Description: `
> When used with the Movr dataset, reate a 9 node cluster and automatically apply
> the geo-partitioned replicas topology across the regions us-east1, us-west1, and
> ```

"across 3 virtual regions named ..."

(otherwise you may misguide users into thinking that `demo` deploys to GCE)

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40355)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @jordanlewis, @knz, and @rohany)

___
*[pkg/cli/demo.go, line 274 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-Lo0u-Mr6014tGQv7h5L:-Lo18EIa6uo9kYGtnT0o:b-pccsjm) ([raw file](https://github.com/cockroachdb/cockroach/blob/31b91324b7c05c9e42dcd5e515224cdfdfc20c55/pkg/cli/demo.go#L274)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Also please reject a combination of flags when a user specifies another dataset and also geo-partitioned replicas, as we are unable to honor their request  in that case.
</blockquote></details>

This is done in runDemo already.
___
*[pkg/cli/demo.go, line 294 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-Lo0tgzi2mhytV2X77r8:-Lo18Mv10q4Mw96cxT0B:bz6z0j9) ([raw file](https://github.com/cockroachdb/cockroach/blob/31b91324b7c05c9e42dcd5e515224cdfdfc20c55/pkg/cli/demo.go#L294)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

yes that seems like a good plan.

Also: is the workload meant to be ran synchronously like this? As-is it will prevent the interactive session from startinig. Isn't it better to have the workload run in the background (in a goroutine) while the user has access to the itneractive shell?
</blockquote></details>

The workload is run in the background -- this function just launches the goroutines.
___
*[pkg/cli/demo.go, line 306 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-Lo0uAzHDQSOcBIVOa1a:-Lo1GZac55l-zp5o-tGF:b-94fg1d) ([raw file](https://github.com/cockroachdb/cockroach/blob/31b91324b7c05c9e42dcd5e515224cdfdfc20c55/pkg/cli/demo.go#L306)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This looks like a possible API extension to the workload generator interface. 
It seems weird to me to have code specific to the `movr` workload hanging in the `cli` package. Instead I'd say this code should be in the `movr` workload (in a place where folk who later change the workload will think about!), and reachable via a new method on the interface, perhaps `PreparePartitioning()`. That method would (presumably) be a no-op for the other workloads, until/unless we find interest into partitioning other workloads.

(Actually tpc-c has partitioning code defined already, but I'd recommend against you trying to look into this in the same PR, so presumably you'd leave a TODO in the tpc-implemenation of `PreparePartitioning()`)
</blockquote></details>

Just to clarify, I should look into adding an interface method to workload in a future PR? I can drop a comment on the TPCC partitioning and here, and open an issue as well.
___
*[pkg/cli/cliflags/flags.go, line 925 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-Lo0umTwAhao2JjxCmRj:-Lo18okk94iQbTjxItkl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/31b91324b7c05c9e42dcd5e515224cdfdfc20c55/pkg/cli/cliflags/flags.go#L925)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

"across 3 virtual regions named ..."

(otherwise you may misguide users into thinking that `demo` deploys to GCE)
</blockquote></details>

Done.

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40355)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @jordanlewis, and @knz)

___
*[pkg/cli/demo.go, line 129 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-Lo0tRjUBDDhwviT4Uk0:-Lo1uRqTE6OsqavVwrr1:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/31b91324b7c05c9e42dcd5e515224cdfdfc20c55/pkg/cli/demo.go#L129)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think it's important to inform the user when they use contradictory settings. Otherwise they will be under the mistaken assumption that, if no error is produced, their desired number of nodes was respected.

You can test whether a flag was set using `pflag.Lookup(...).Changed`.
</blockquote></details>

done

**Comment by rohany** [comment]
RFAL

**Review by knz — COMMENTED** [review]
Ok I am starting to like this. Thanks for all the good work.

> Reviewed 2 of 6 files at r5, 7 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-:-LoUYkk-Ecjh2Wh3tzaR:bdbusg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @jordanlewis, @knz, and @rohany)

___
*[pkg/cli/demo.go, line 306 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-Lo0uAzHDQSOcBIVOa1a:-LoUXdwr8ZnV5qYfR-BS:b-xl4v97) ([raw file](https://github.com/cockroachdb/cockroach/blob/31b91324b7c05c9e42dcd5e515224cdfdfc20c55/pkg/cli/demo.go#L306)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Just to clarify, I should look into adding an interface method to workload in a future PR? I can drop a comment on the TPCC partitioning and here, and open an issue as well.
</blockquote></details>

I am saying that your PR as is is creating technical debt and therefore I am not exactly happy about it.

The bare minimum would be to move this particular function to the same package where `movr` is defined (so that folk who work on future changes to movr are forced to also think about updating this function), then inject it as a dependency into `cli` upon initialization (so that you don't depend on a CCL package from here)

Then a step beyond the bare minimum would be to extend the workload interface, to give _any_ workload (not just movr) a chance to set up partitioning. For that extra step you can either do it here or file an issue and leave a TODO with the issue number.
___
*[pkg/cli/demo.go, line 128 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-LoUYAq44t-lMDo-heIP:-LoUYAq59AbsIdmhTkjh:b-qacqp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/54b530a3d25de49347aa5aa38fcb90d2f3461dde/pkg/cli/demo.go#L128)):*
> ```Go
> 
> 	// This demo only works on a 9 node cluster, so set the node count as such.
> 	// Ignore input user localities.
> ```

Move this override below in `runDemo` so that it is clearly linked to the command line parsing.
___
*[pkg/cli/demo.go, line 489 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-LoUYIVl0vsVu5apW01k:-LoUYIVl0vsVu5apW01l:b-c62up4) ([raw file](https://github.com/cockroachdb/cockroach/blob/54b530a3d25de49347aa5aa38fcb90d2f3461dde/pkg/cli/demo.go#L489)):*
> ```Go
> 		return errors.New("--nodes cannot be used with --geo-partitioned-replicas")
> 	}
> ```

Also add either:
- "if --geo-partitioned-replicas is set and --nodes is Changed and set to a different value than 9, print an error" (we don't want to silently dismiss a setting that was purposefully entered by the user)
- "if --geo-partitioned-replicas is set and --nodes is _not_ Changed, then override it to 9 _and_ print an info message to the user (on stdout) to inform them that the demo cluster size is grown from the default" (we don't want to let a difference from the standard behavior remain silent)

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40355)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @jordanlewis, and @knz)

___
*[pkg/cli/demo.go, line 306 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-Lo0uAzHDQSOcBIVOa1a:-LoVZ908C0XiYENuhdnh:b-yq2j5u) ([raw file](https://github.com/cockroachdb/cockroach/blob/31b91324b7c05c9e42dcd5e515224cdfdfc20c55/pkg/cli/demo.go#L306)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I am saying that your PR as is is creating technical debt and therefore I am not exactly happy about it.

The bare minimum would be to move this particular function to the same package where `movr` is defined (so that folk who work on future changes to movr are forced to also think about updating this function), then inject it as a dependency into `cli` upon initialization (so that you don't depend on a CCL package from here)

Then a step beyond the bare minimum would be to extend the workload interface, to give _any_ workload (not just movr) a chance to set up partitioning. For that extra step you can either do it here or file an issue and leave a TODO with the issue number.
</blockquote></details>

Done. This was actually an easy change to add a partition step to the Hooks interface.
___
*[pkg/cli/demo.go, line 128 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-LoUYAq44t-lMDo-heIP:-LoVWTER25W30DXJ85kl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/54b530a3d25de49347aa5aa38fcb90d2f3461dde/pkg/cli/demo.go#L128)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Move this override below in `runDemo` so that it is clearly linked to the command line parsing.
</blockquote></details>

Done.
___
*[pkg/cli/demo.go, line 489 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-LoUYIVl0vsVu5apW01k:-LoVZekw3mqOyACd8DOJ:b-jdz9xx) ([raw file](https://github.com/cockroachdb/cockroach/blob/54b530a3d25de49347aa5aa38fcb90d2f3461dde/pkg/cli/demo.go#L489)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Also add either:
- "if --geo-partitioned-replicas is set and --nodes is Changed and set to a different value than 9, print an error" (we don't want to silently dismiss a setting that was purposefully entered by the user)
- "if --geo-partitioned-replicas is set and --nodes is _not_ Changed, then override it to 9 _and_ print an info message to the user (on stdout) to inform them that the demo cluster size is grown from the default" (we don't want to let a difference from the standard behavior remain silent)
</blockquote></details>

The first should already be handled by the above -- if geoPartitionedReplicas && nodes is changed we throw an error. I'll add the second.

**Review by knz — COMMENTED** [review]
LGTM modulo adding a test for the new feature.
(and a nit)
You also have a linter error to address.

> Reviewed 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-:-LoW19uI5IzateeBNfNo:bxp2xyx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @jordanlewis, and @rohany)

___
*[pkg/cli/demo.go, line 284 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-LoW0_oTBIqxg7kD4n4p:-LoW0_oTBIqxg7kD4n4q:b-8rqrwz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c17b91b5bf2adbfedaedaef91f385bae212b0ed/pkg/cli/demo.go#L284)):*
> ```Go
> 					}
> 					partitionFunc := hookser.Hooks().Partition
> 					if partitionFunc == nil {
> ```

I think you need this instead:

```go
if partitionFunc != nil {
  if err := partitionFunc(db); err != nil {
    ...
  }
}
```

otherwise the other workloads could break.
___
*[pkg/cli/interactive_tests/test_demo_partitioning.tcl, line 11 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-LoW12j70-PWPcq9qHGb:-LoW12j88RCVgXaGgDeC:bmil5k5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c17b91b5bf2adbfedaedaef91f385bae212b0ed/pkg/cli/interactive_tests/test_demo_partitioning.tcl#L11)):*
> ```Tcl
> spawn $argv demo --geo-partitioned-replicas
> # expect a failure
> eexpect "Error: license acquisition was unsuccessful. Enterprise features are needed to partition data"
> ```

You probably need another test that asserts that partitioning is successful when the env var is not set.

(I did not find a test for the new feature elsewhere)

**Comment by rohany** [comment]
Yeah, I'll add an .tcl test for this. However the testing kind of relates to my questions in https://github.com/cockroachdb/cockroach/pull/40613 -- The partitioning is happening asynchronously, so we want to repeatedly send a `SHOW PARTITIONS` command to the demo until we get all the results we want. I don't know how to do this in tcl/expect

**Comment by knz** [comment]
it's very crude but you could do something like this:
```tcl
report "waiting for partitioning to become available..."
system "for i in `seq 1 5`; do
   $argv sql -e 'select ...' >result.txt
   if grep ... result.txt; then 
      found=1
      break
   fi
   sleep 1
done
if test x$found = x; then
   exit 1
fi"
report "done"
```

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40355)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @jordanlewis, @knz, and @rohany)

___
*[pkg/cli/demo.go, line 284 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-LoW0_oTBIqxg7kD4n4p:-LoWDtFZ--PQhFEXSQGs:b-p0amzy) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c17b91b5bf2adbfedaedaef91f385bae212b0ed/pkg/cli/demo.go#L284)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think you need this instead:

```go
if partitionFunc != nil {
  if err := partitionFunc(db); err != nil {
    ...
  }
}
```

otherwise the other workloads could break.
</blockquote></details>

I dont see the difference is here -- if partitionFunc is nil when we requested geo-partitioned-replicas on a dataset, then we should throw an error if it is not defined.

**Comment by rohany** [comment]
Tests added.

**Review by knz — COMMENTED** [review]
Nice tests :)

> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-:-LoZ_GzF-DP6rSBytaWo:b-obrv9w)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @jordanlewis, and @rohany)

___
*[pkg/cli/demo.go, line 278 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-LoZZel8DRpD4Jh4J82M:-LoZZel8DRpD4Jh4J82N:b27wld8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1098cff7fb629534583bcb3bbb06dbaf2b0ab40/pkg/cli/demo.go#L278)):*
> ```Go
> 					}
> 					defer db.Close()
> 					configErr := errors.New(fmt.Sprintf("workload %s is not configured to have a partitioning step", gen.Meta().Name))
> ```

I have thought about this more and I am going to change my advice:
These are config checks. Having these checks so late in the initialization process, moreso in an async goroutine, is a design mistake.
When the code arrives at this point the error path should be limited to unexpected errors unrelated to user input.

I think the checks should be present alongside the command line parsing. It would also clarify the relationship between the command-line arguments and the prerequisites on the generators.
___
*[pkg/cli/interactive_tests/test_demo_partitioning.tcl, line 20 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-LoZ_2ohBg5KvA0-Mr2t:-LoZ_2ohBg5KvA0-Mr2u:b-vyor2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1098cff7fb629534583bcb3bbb06dbaf2b0ab40/pkg/cli/interactive_tests/test_demo_partitioning.tcl#L20)):*
> ```Tcl
> start_test "Expect partitioning succeeds"
> # test that partitioning works if a license could be acquired
> unset env(COCKROACH_SKIP_ENABLING_DIAGNOSTIC_REPORTING)
> ```

Move the "positive" tests to the beginning, this way you don't need to tweak the env var twice.
(Also it would be the more "natural" order for reading/understanding tests: first positive tests, then negative)

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40355)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @jordanlewis, and @knz)

___
*[pkg/cli/demo.go, line 278 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-LoZZel8DRpD4Jh4J82M:-Loa-P772v_2s05aow28:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1098cff7fb629534583bcb3bbb06dbaf2b0ab40/pkg/cli/demo.go#L278)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I have thought about this more and I am going to change my advice:
These are config checks. Having these checks so late in the initialization process, moreso in an async goroutine, is a design mistake.
When the code arrives at this point the error path should be limited to unexpected errors unrelated to user input.

I think the checks should be present alongside the command line parsing. It would also clarify the relationship between the command-line arguments and the prerequisites on the generators.
</blockquote></details>

Done.
___
*[pkg/cli/interactive_tests/test_demo_partitioning.tcl, line 20 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-LoZ_2ohBg5KvA0-Mr2t:-Loa-Syu7GrExTwjNU7N:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1098cff7fb629534583bcb3bbb06dbaf2b0ab40/pkg/cli/interactive_tests/test_demo_partitioning.tcl#L20)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Move the "positive" tests to the beginning, this way you don't need to tweak the env var twice.
(Also it would be the more "natural" order for reading/understanding tests: first positive tests, then negative)
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
:lgtm: with a small suggestion for improvement

> Reviewed 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-:-Loa099mDXlubmInPSf5:b19bxl2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @awoods187, @jordanlewis, and @rohany)

___
*[pkg/cli/demo.go, line 383 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-Loa-yglC4kwPQrGkX3-:-Loa-yglC4kwPQrGkX30:bnbaa2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e193b6c7639f646f62a531747804eed5616f321/pkg/cli/demo.go#L383)):*
> ```Go
> 	// If geo-partition-replicas is requested, make sure the workload is MovR and has a Partitioning step.
> 	if demoCtx.geoPartitionedReplicas {
> 		if gen.Meta().Name != "movr" {
> ```

If you would remove this specific check, this would enable additional workloads to "opt in" the flag smoothly by just implementing the `Partition` hook, without having to modify `demo.go`.

**Review by knz — COMMENTED** [review]
Can you also spell out the name of the flag in the release note? thx

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40355#-:-Loa0BkOCR2FCPhmdZfp:b686zfn)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @awoods187, @jordanlewis, and @rohany)

**Pull request merged**
