### PR TITLE
ui: a variety of minor fixes

### PR DESCRIPTION
**Pull request by couchand**
- remove back links (#23682)
- node list top bar styling (#23802)
- align jobs content to top (#23889)
- rename custom graph to custom chart (#23419)
- highlight table create statement on reload (#23903)
- fixes a rare issue with hover on time series charts (#23011)

### CODE REVIEW

**Comment by vilterp** [comment]
Thank you for getting to all this stuff!

**Comment by vilterp** [comment]
re: removing the backlinks: would be nice to highlight the sidebar icon you're under so you know "where you are" in the UI. It would effectively become your backlink. Note that the icons are currently highlighted when you're on the top-level page itself; maybe we can use the same style. Kind of disorienting otherwise.

re: "custom graph" => "custom chart", may collide with #23771 (race condition!)

---

Reviewed 5 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 8 of 8 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/ui/src/views/databases/containers/tableDetails/index.tsx, line 81 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/23904#-L7eS_fvHm6X-B4sKGxG:-L7eS_fvHm6X-B4sKGxH:b4jn2r1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad69163fcfa2f42c33c4641f88e280c0b33bb469/pkg/ui/src/views/databases/containers/tableDetails/index.tsx#L81)):*
> ```XML
> 
>   componentDidUpdate() {
>     hljs.highlightBlock(this.createStmtNode);
> ```

huh. Verified the fix but don't understand why `componentDidMount` isn't enough. Oh… tables not loaded yet so the <pre> is empty? Gah.

---

*[pkg/ui/src/views/shared/util/table.styl, line 43 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23904#-L7eRkxjkHcztzGfR7WY:-L7eRkxjkHcztzGfR7WZ:b-1au6nl) ([raw file](https://github.com/cockroachdb/cockroach/blob/d493daabd868c045537bc96dd45d96a57d165b87/pkg/ui/src/views/shared/util/table.styl#L43)):*
> ```Stylus
>     border-right $table-cell-border
>     font-weight inherit
>     vertical-align top
> ```

nice. also makes it jitter a little less when you expand… just adds content at the bottom; doesn't move up to the top of the cell since it's already there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23904#-:-L7eRFBAaVoGF5OTLKZO:bchrp4w)*

**Comment by couchand** [comment]
rebased, ready to go, PTAL

The only one that naturally has a "where you are" is the table details page.  I've opened #24069 to track updating the highlight logic for that, but since it looks like it will be nontrivial I'm not going to try to address it here.

---

Review status: 4 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/ui/src/views/databases/containers/tableDetails/index.tsx, line 81 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/23904#-L7eS_fvHm6X-B4sKGxG:-L82ygCefSZg72JnZTvz:blstzi0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad69163fcfa2f42c33c4641f88e280c0b33bb469/pkg/ui/src/views/databases/containers/tableDetails/index.tsx#L81)):*
<details><summary><i>Previously, vilterp (Pete Vilter) wrote…</i></summary><blockquote>

huh. Verified the fix but don't understand why `componentDidMount` isn't enough. Oh… tables not loaded yet so the <pre> is empty? Gah.
</blockquote></details>

yeah..............

---

*[pkg/ui/src/views/shared/util/table.styl, line 43 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23904#-L7eRkxjkHcztzGfR7WY:-L82yjVQy655W33LP_2l:bb7s76d) ([raw file](https://github.com/cockroachdb/cockroach/blob/d493daabd868c045537bc96dd45d96a57d165b87/pkg/ui/src/views/shared/util/table.styl#L43)):*
<details><summary><i>Previously, vilterp (Pete Vilter) wrote…</i></summary><blockquote>

nice. also makes it jitter a little less when you expand… just adds content at the bottom; doesn't move up to the top of the cell since it's already there.
</blockquote></details>

yay!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23904#-:-L82ySM88wW1L4P_NPn8:bm8wz69)*

**Comment by vilterp** [comment]
:lgtm: on everything but removing backlinks everywhere. Mind splitting that commit out into its own PR?

The case of the cluster overview page and the node details page is tricky, since cluster overview can be in so many states (list vs map; zoomed into a locality). I think I'd be ok with removing the "back to node list" link there. But removing it from tables seems like a usability regression.

---

Reviewed 11 of 14 files at r6.
Review status: 4 of 16 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23904#-:-L83UK4tDtgNjyePco0C:b-eejt5n)*

**Comment by couchand** [comment]
I think we need to do something to clean up the nodes links for this release, and it seems like removing the link is the best option we have right now.  I've updated the back links commit to leave the database table back link, even though I don't like having inconsistency, so that it's less contentious here.

**Comment by couchand** [comment]
I'm planning on cherry-picking this into 2.0.1, unless @bdarnell thinks it's worth bringing over now.  Perhaps just c5527d0, since that's small and relatively obvious/annoying?

**Comment by bdarnell** [comment]
I think the rename customgraph to customchart is worth getting in to 2.0 so we don't immediately break any bookmarks people may create. I'm OK with cherry-picking this whole batch of changes as long as you're confident in them.

**Comment by vilterp** [comment]
I've tried out these changes locally and am pretty confident they're fine to go into 2.0.

**Pull request merged**
