### PR TITLE
storage: Remove TestRangeDescriptorSnapshotRace

### PR DESCRIPTION
**Pull request by bdarnell**
With the move to streaming snapshots, this test just starts and abandons
the snapshot process in a tight loop, without consuming them (resulting
in a ton of log spam). Even if it were updated to consume the snapshots
it generates, I don't think it's a very useful or interesting test, so
I'm just deleting it.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10697)

### CODE REVIEW

**Comment by bdarnell** [comment]
This test alone was responsible for about 15% of the logging output of a test run.

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10697#-:-KWcYugy0KfS4SZA07e-:bnfp4nl)*

**Comment by tamird** [comment]
Why remove the timing information on snapshot application?

**Comment by bdarnell** [comment]
The timing information being logged here doesn't cover the entire snapshot generation any more, just creating the rocksdb iterator (which is O(1) and always fast), so the timing isn't interesting and could be misleading. I considered downgrading this to a V(1) and/or moving it to the end of the process, but this log line has been useful in figuring out the sequence of events in recent bugs so I left it in for now.

**Pull request merged**
