### PR TITLE
sql: add enums to statement bundles

### LINKED ISSUE #100377: Include SHOW ENUMS output in statement bundle
**Describe the problem**
Statement bundles don't currently show enum types created via [CREATE TYPE](https://www.cockroachlabs.com/docs/stable/create-type.html), making it difficult or impossible to recreate the DDL in-house.

[SHOW ENUMS](https://www.cockroachlabs.com/docs/stable/show-enums.html) output, or ideally the CREATE TYPE statements needed by the table DDL should be included in the statement bundle.

Jira issue: CRDB-26394

### PR DESCRIPTION
**Pull request by rharding6373**
Statement bundles now include the `CREATE` statements for enums in `schema.sql`.

Epic: None
Fixes: #100377

Release note: None

### CODE REVIEW

**Comment by rharding6373** [comment]
Waiting for input from compliance about whether we need to redact any information from the `CREATE TYPE` statements in the statement bundle before merging.

**Review by michae2 — CHANGES_REQUESTED** [review]
Thank you for doing this!

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101953#-:-NTVkVnu1mSX9cXr2eRp:bff479j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373)

___
*[`pkg/sql/explain_bundle.go` line 812 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101953#-NTVk41u13VokNbU8AsH:-NTVk41u13VokNbU8AsI:billzk3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b05f7cf30f9047b39e4ca6e8730015fc96f0c38/pkg/sql/explain_bundle.go#L812)):*
> ```Go
> 	}
> 	for _, cs := range createStatement {
> 		fmt.Fprintf(w, "%s\n", cs)
> ```

I think this needs a semicolon after `%s` for `schema.sql` to be executable.
___
*[`pkg/cli/testdata/explain-bundle/bundle/schema.sql` line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101953#-NTVkOwC18bhPZAOhl0O:-NTVkOwC18bhPZAOhl0P:bsz00f6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b05f7cf30f9047b39e4ca6e8730015fc96f0c38/pkg/cli/testdata/explain-bundle/bundle/schema.sql#L14)):*
> ```TSQL
> );
> 
> CREATE TYPE public.d AS ENUM {'Monday', 'Tuesday'}
> ```

I think the curly braces need to be parentheses.



_Code quote:_
```TSQL
CREATE TYPE public.d AS ENUM {'Monday', 'Tuesday'}
```

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101953)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2)

___
*[`pkg/sql/explain_bundle.go` line 812 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101953#-NTVk41u13VokNbU8AsH:-NTVsoJO4vTE91riMSjJ:by0j6m) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b05f7cf30f9047b39e4ca6e8730015fc96f0c38/pkg/sql/explain_bundle.go#L812)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

I think this needs a semicolon after `%s` for `schema.sql` to be executable.
</blockquote></details>

Interestingly, `SHOW CREATE ALL TYPES` already includes a semicolon in its `create_statement` output, whereas commands like `SHOW CREATE TABLE t` do not. I tested this manually on a database with multiple UDTs and the statement bundle's schema.sql was executable.
___
*[`pkg/cli/testdata/explain-bundle/bundle/schema.sql` line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101953#-NTVkOwC18bhPZAOhl0O:-NTVtMZ4DJMQXLHEACpr:b-563j3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b05f7cf30f9047b39e4ca6e8730015fc96f0c38/pkg/cli/testdata/explain-bundle/bundle/schema.sql#L14)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

I think the curly braces need to be parentheses.
</blockquote></details>

Thanks! It turns out this is only used in one test, `TestRunExplainCombinations`, and I don't think it was particularly useful there, so I've reverted these changes.

**Review by rharding6373 — COMMENTED** [review]
Revised based on compliance team feedback. PTAL!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101953#-:-NTu8PAt249K8jRPI49T:b-w5s54u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2)

___
*[`pkg/sql/explain_bundle.go` line 814 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/101953#-NTu8vG_EJgi2V9q3WP1:-NTu8vGa2PO7nOw2EABp:bc8xnt8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7d7475a9ae7bd5801227a3bf49006519dceadd0/pkg/sql/explain_bundle.go#L814)):*
> ```Go
> 
> 		if redactValues {
> 			cs, _, _ = strings.Cut(cs, " AS ENUM (")
> ```

I opted to create empty enums when redaction is called. E.g., `CREATE TYPE mytyp AS ENUM ('hello', 'world');` -> `CREATE TYPE mytyp AS ENUM();`. However, there is one case in which this may result in a bad enum in the bundle, which are cases in which the type name contains this string, e.g., `CREATE TYPE "bad AS ENUM (" AS ENUM ('hello', 'world');`. Let me know if you think this is concerning. We could just omit enums entirely when redaction is enabled.

**Review by michae2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101953)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373)

___
*[`pkg/sql/explain_bundle.go` line 814 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/101953#-NTu8vG_EJgi2V9q3WP1:-NTzRf82CEm1ZYTKGIx2:bpmogin) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7d7475a9ae7bd5801227a3bf49006519dceadd0/pkg/sql/explain_bundle.go#L814)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I opted to create empty enums when redaction is called. E.g., `CREATE TYPE mytyp AS ENUM ('hello', 'world');` -> `CREATE TYPE mytyp AS ENUM();`. However, there is one case in which this may result in a bad enum in the bundle, which are cases in which the type name contains this string, e.g., `CREATE TYPE "bad AS ENUM (" AS ENUM ('hello', 'world');`. Let me know if you think this is concerning. We could just omit enums entirely when redaction is enabled.
</blockquote></details>

I think a more robust way to do this would be to pass the statement through `crdb_internal.redactable_sql_constants`, i.e. something like:

```sql
SELECT crdb_internal.redact(crdb_internal.redactable_sql_constants(create_statement)) FROM [SHOW CREATE ALL TYPES];
```

Then we just need to make the `CREATE TYPE` statement redactable, which I think means adding an `if f.HasFlags(FmtMarkRedactionNode)` case to this function: https://github.com/cockroachdb/cockroach/blob/a10740b3cd716580c12d7e3c399d67389018e836/pkg/sql/sem/tree/create.go#L330-L338

which would be similar to this one: https://github.com/cockroachdb/cockroach/blob/a10740b3cd716580c12d7e3c399d67389018e836/pkg/sql/sem/tree/format.go#L690-L695

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101953)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2)

___
*[`pkg/sql/explain_bundle.go` line 814 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/101953#-NTu8vG_EJgi2V9q3WP1:-NU3kNKG-Ag84eRDF0SE:b-s5eex1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7d7475a9ae7bd5801227a3bf49006519dceadd0/pkg/sql/explain_bundle.go#L814)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

I think a more robust way to do this would be to pass the statement through `crdb_internal.redactable_sql_constants`, i.e. something like:

```sql
SELECT crdb_internal.redact(crdb_internal.redactable_sql_constants(create_statement)) FROM [SHOW CREATE ALL TYPES];
```

Then we just need to make the `CREATE TYPE` statement redactable, which I think means adding an `if f.HasFlags(FmtMarkRedactionNode)` case to this function: https://github.com/cockroachdb/cockroach/blob/a10740b3cd716580c12d7e3c399d67389018e836/pkg/sql/sem/tree/create.go#L330-L338

which would be similar to this one: https://github.com/cockroachdb/cockroach/blob/a10740b3cd716580c12d7e3c399d67389018e836/pkg/sql/sem/tree/format.go#L690-L695
</blockquote></details>

That was easier than having to add a `WITH REDACT` option to `SHOW TYPES`. Thanks for the tips.

**Review by michae2 — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101953)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373)

___
*[`pkg/sql/explain_bundle.go` line 814 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/101953#-NTu8vG_EJgi2V9q3WP1:-NU3u6rKANJttTjJ0wPD:b-j5itq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7d7475a9ae7bd5801227a3bf49006519dceadd0/pkg/sql/explain_bundle.go#L814)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

That was easier than having to add a `WITH REDACT` option to `SHOW TYPES`. Thanks for the tips.
</blockquote></details>

Yay! :)

Do we still need `strings.Cut` now? Maybe I wasn't clear before, I was trying to suggest totally replacing the usage of `strings.Cut` for redaction with some logic like: `if redactValues { /* use crdb_internal.redactable_sql_constants in the query */ } else { /* don't use crdb_internal.redactable_sql_constants in the query */ }`.

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101953)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2)

___
*[`pkg/sql/explain_bundle.go` line 814 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/101953#-NTu8vG_EJgi2V9q3WP1:-NU3xTrB1dikYMSYXloL:bfmcxz7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7d7475a9ae7bd5801227a3bf49006519dceadd0/pkg/sql/explain_bundle.go#L814)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Yay! :)

Do we still need `strings.Cut` now? Maybe I wasn't clear before, I was trying to suggest totally replacing the usage of `strings.Cut` for redaction with some logic like: `if redactValues { /* use crdb_internal.redactable_sql_constants in the query */ } else { /* don't use crdb_internal.redactable_sql_constants in the query */ }`.
</blockquote></details>

Gah, sorry, didn't push with the right changes. Should be fixed now?

**Review by michae2 — APPROVED** [review]
:lgtm: Nice. Thank you!

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101953#-:-NU41gNr0LjYLWF48ghN:b3o7y1i)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rharding6373)

___
*[`pkg/sql/explain_bundle.go` line 814 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/101953#-NTu8vG_EJgi2V9q3WP1:-NU41ieV2orZp87NqqII:byp6p7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7d7475a9ae7bd5801227a3bf49006519dceadd0/pkg/sql/explain_bundle.go#L814)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Gah, sorry, didn't push with the right changes. Should be fixed now?
</blockquote></details>

No worries, looks great.

**Comment by rharding6373** [comment]
TFTR!

bors r=michae2

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101953)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[`pkg/sql/explain_bundle.go` line 462 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/101953#-NU7aVOu-01v7lgOzHKN:-NU7aVOvAHhiBIBALdkG:b-ejx015) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f5f04306dc125f9cca2dd0c16f74f9351b4dbea/pkg/sql/explain_bundle.go#L462)):*
> ```Go
> 		}
> 	}
> 	// Get all user-defined types. If redaction is a
> ```

nit: the comment is unfinished.

**Comment by yuzefovich** [comment]
blathers backport 23.1

**Pull request merged**
