### PR TITLE
server: implement unified admin server 

### LINKED ISSUE #92616: server: unify admin server between system and tenant
Remove `tenantAdminServer` in favor of a modified `adminServer` that can handle requests in tenant context.

Epic: CRDB-17356

Jira issue: CRDB-21886

### PR DESCRIPTION
**Pull request by dhartunian**
Previously, we had a separate tenant admin server that implemented a subset of
admin server RPC handlers for SQL tenants to use. This commit modifies the
existing admin sever to create a single implementation that can be shared
between app and system tenants.

The primary changes here are to embed fields from the `Server` struct directly
into the `adminServer` thereby reducing reliance on having a pointer to
`Server` around at runtime for most endpoints. This results in just 4 endpoints
that retain access to `s.server` in their implementation. They contain short
circuit logic at the top of the handler that will throw an Unimplemented error
for non-system tenants. These are the Decommission, DecommissionStatus,
SendKVBatch, and EnqueueRange endpoints which naturally have no counterpart in
a non-system tenant.

Resolves #92616 

Epic: [CRDB-17356](https://cockroachlabs.atlassian.net/browse/CRDB-17356)

Release note: None

### CODE REVIEW

**Review by knz — APPROVED** [review]
This was _so_ satisfying to review. 
Thank you for the big lift, but it's also such a relief to this this code resolve.

:lgtm_strong:  - modulo resolution of the review on #91324 first.

> Reviewed 14 of 14 files at r1, 16 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92686#-:-NI8UMdE-SKoWmnOwXW7:b-c7qujo)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian)

**Review by abarganier — APPROVED** [review]
:lgtm: as well, I think a lot of this follows from the previous PR where a lot of little things have already been worked out, so not too much feedback on this one! 

I agree with @knz - the amount of finesse here is very satisfying to see!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92686#-:-NIIq9mnBP9g7p04PPVp:b-ltu2yt)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @dhartunian and @knz)

___
*[`pkg/server/admin.go` line 138 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92686#-NIIne9Q5AASThG2kSo3:-NIIne9Q5AASThG2kSo4:bh7cln) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd996afe58c2d1ffac52a665500ff639325fcabb/pkg/server/admin.go#L138)):*
> ```Go
> }
> 
> type systemAdminServer struct {
> ```

nit: comments to help explain the difference between `adminServer` and `systemAdminServer`



_Code quote:_
```Go
type systemAdminServer struct {
```
___
*[`pkg/server/admin.go` line 175 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92686#-NIInSua8On7yHjUc226:-NIInSub0yiutxa22T6W:bmqz7ox) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd996afe58c2d1ffac52a665500ff639325fcabb/pkg/server/admin.go#L175)):*
> ```Go
> 	s *Server,
> ) *systemAdminServer {
> 	adminServer := newAdminServer(sqlServer, cs, adminAuthzCheck, ie, ambient, metricsRecorder, db, rpcCtx, serverIterator, clock, distSender, grpc, drainServer)
> ```

nit: can we multi-line this?



_Code quote:_
```Go
	adminServer := newAdminServer(sqlServer, cs, adminAuthzCheck, ie, ambient, metricsRecorder, db, rpcCtx, serverIterator, clock, distSender, grpc, drainServer)
```

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92686)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @knz)

___
*[`pkg/server/admin.go` line 138 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92686#-NIIne9Q5AASThG2kSo3:-NIcGu577igOFfa0nybC:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd996afe58c2d1ffac52a665500ff639325fcabb/pkg/server/admin.go#L138)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: comments to help explain the difference between `adminServer` and `systemAdminServer`
</blockquote></details>

done.
___
*[`pkg/server/admin.go` line 175 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92686#-NIInSua8On7yHjUc226:-NIcH49-5dGNoOxPL3S9:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd996afe58c2d1ffac52a665500ff639325fcabb/pkg/server/admin.go#L175)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: can we multi-line this?
</blockquote></details>

done.

**Comment by dhartunian** [comment]
TFTRs!

bors r=knz,abarganier

**Pull request merged**
