### PR TITLE
importer: use new parquet writer for EXPORT INTO PARQUET

### LINKED ISSUE #103317: export: parquet causes node to OOM
It looks like we are not performing sufficient memory accounting when using `EXPORT INTO` with parquet.

See 
- https://github.com/cockroachlabs/support/issues/2303
- https://github.com/cockroachlabs/support/issues/2247

Jira issue: CRDB-27942

### PR DESCRIPTION
**Pull request by jayshrivastava**
### roachtest: add test for EXPORT INTO PARQUET
This change adds a rochtest which sets up a 3-node CRDB cluster
on 8vCPU machines initialized with the TPC-C database containing
250 warehouses. Then, it executes 30 `EXPORT INTO PARQUET` statements
concurrently, repeatedly for 10 minutes. The main purpose of this
test is to use it for benchmarking. It sets up grafana as well
so metrics can be observed during the test.

This change also adds a daily roachtest which runs exports
on a 100 warehouse TPCC database, without setting up grafana.

Informs: https://github.com/cockroachdb/cockroach/issues/103317
Release note: None

---

### importer: use new parquet writer for EXPORT INTO PARQUET

Previously, `EXPORT INTO PARQUET` used a library which had
very poor memory usage. This change updates this command to
use the new parquet writer in `util/parquet`, which is newer
and does not use excessive memory.

To ensure backwards compatability, as much testing code as
possible is left untouched to ensure the old `EXPORT INTO PARQUET`
behavior is the same when using the new library. Some of the the
old production code and dependencies are also left untouched
because they are used in the test code.

This commit leaves some TODOs to clean up the tests and production
code once we have confidence in the new library.

Informs: https://github.com/cockroachdb/cockroach/issues/104329
Informs: https://github.com/cockroachdb/cockroach/issues/104278
Informs: https://github.com/cockroachdb/cockroach/issues/104279
Closes: https://github.com/cockroachdb/cockroach/issues/103317

Release note (general change): `EXPORT INTO PARQUET` will now
use a new internal implementation for writing parquet files
using parquet spec version 2.6. There should be no significant
impact to the structure of files being written. There is one
minor change:
- all columns written to parquet files will be nullable
  (ie. the parquet repetition type is `OPTIONAL`)

### CODE REVIEW

**Review by jayshrivastava — COMMENTED** [review]
I posted the memstats here: https://drive.google.com/drive/folders/1xIevGiHsC95jnsQQF3Y1N5kSzltKMo1w?usp=share_link

In summary, I ran the roachtest and found that EXPORT with the new library uses
- 42% less memory (1703707920B / 2948454120B). This is a difference 1.24 GB when running concurrent exports on a 14GB database.
- 72% fewer allocs (2598922890 / 9259896304) 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104234#-:-NWx_JQq3TxHxyR5CpuK:bjcf1jz)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[`pkg/sql/importer/exportparquet_test.go` line 140 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104234#-NWxa1oY67CC-i_l7h3Q:-NWxa1oY67CC-i_l7h3R:b-jkvgtz) ([raw file](https://github.com/cockroachdb/cockroach/blob/826809ec0741d9361a5912f661cc5f5c1537cd65/pkg/sql/importer/exportparquet_test.go#L140)):*
> ```Go
> 		require.Equal(t, expected.(*tree.DJSON).JSON.String(),
> 			actual.(*tree.DJSON).JSON.String())
> 	case types.EnumFamily:
> ```

Before I added these changes, we would not write the additional metadata (ex. collation) to parquet files. The metadata was a part of the encoders and decoders here: https://github.com/cockroachdb/cockroach/blob/826809ec0741d9361a5912f661cc5f5c1537cd65/pkg/sql/importer/exportparquet.go#L163

IMO if we aren't writing such things to files, then there is no point in testing them.

**Review by miretskiy — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 5 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104234)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @herkolategan, @jayshrivastava, and @smg260)

___
*[`go.mod` line 216 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104234#-NX0Pvi26qJy-piYQzqJ:-NX0Pvi26qJy-piYQzqK:b-twn8xf) ([raw file](https://github.com/cockroachdb/cockroach/blob/593d98d75a81fbe2662d154cd5dddb0314b47363/go.mod#L216)):*
> ```XML
> 	github.com/stretchr/testify v1.8.3
> 	github.com/twpayne/go-geom v1.4.2
> 	github.com/uber-go/atomic v1.4.0
> ```

maybe we shouldn't add this dependency? What does uber-go/atomic has that atomic does not?
___
*[`pkg/cmd/roachtest/tests/export_parquet.go` line 35 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104234#-NX0Q73L-ptKqJNeYmHK:-NX0Q73L-ptKqJNeYmHL:b-den2lp) ([raw file](https://github.com/cockroachdb/cockroach/blob/593d98d75a81fbe2662d154cd5dddb0314b47363/pkg/cmd/roachtest/tests/export_parquet.go#L35)):*
> ```Go
> 		Name:            "export/parquet",
> 		Owner:           registry.OwnerCDC,
> 		Tags:            registry.Tags("manual"),
> ```

do we want to have smaller non-manual test? Or does it exist?
___
*[`pkg/sql/importer/exportparquet.go` line 37 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104234#-NX0SL_D2MyNIuGoYWDN:-NX0SL_D2MyNIuGoYWDO:b-1sd30r) ([raw file](https://github.com/cockroachdb/cockroach/blob/593d98d75a81fbe2662d154cd5dddb0314b47363/pkg/sql/importer/exportparquet.go#L37)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/util/bitarray"
> 	"github.com/cockroachdb/cockroach/pkg/util/duration"
> 	crlparquet "github.com/cockroachdb/cockroach/pkg/util/parquet"
> ```

add todo or just do it here -- we need memory monitor for this stuff.
___
*[`pkg/sql/importer/exportparquet.go` line 643 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104234#-NX0REWu459Bxb-vRgVR:-NX0REWu459Bxb-vRgVS:bwgm0eb) ([raw file](https://github.com/cockroachdb/cockroach/blob/593d98d75a81fbe2662d154cd5dddb0314b47363/pkg/sql/importer/exportparquet.go#L643)):*
> ```Go
> 			compression = crlparquet.CompressionGZIP
> 		case roachpb.IOFileFormat_Auto, roachpb.IOFileFormat_None:
> 			compression = crlparquet.CompressionNone
> ```

crlparquet supports other compression formats, right?
Perhaps add an issue/todo to make export support those too.
Also, todo to refactor string -> codec parsing.
___
*[`pkg/sql/importer/exportparquet_test.go` line 145 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104234#-NX0T4cY2kNYX3b--zzp:-NX0T4cY2kNYX3b--zzq:b-gagjcv) ([raw file](https://github.com/cockroachdb/cockroach/blob/593d98d75a81fbe2662d154cd5dddb0314b47363/pkg/sql/importer/exportparquet_test.go#L145)):*
> ```Go
> 			actual.(*tree.DEnum).LogicalRep)
> 	case types.CollatedStringFamily:
> 		// Only the value of the collated string matters, not that additional properties
> ```

and it does appear that parquet does not have notion of collation... am I correct?

**Review by jayshrivastava — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104234)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @herkolategan, @miretskiy, and @smg260)

___
*[`go.mod` line 216 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104234#-NX0Pvi26qJy-piYQzqJ:-NXAt_vKDZtdCiClEMWT:bw73ya0) ([raw file](https://github.com/cockroachdb/cockroach/blob/593d98d75a81fbe2662d154cd5dddb0314b47363/go.mod#L216)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

maybe we shouldn't add this dependency? What does uber-go/atomic has that atomic does not?
</blockquote></details>

Done. Accidentally used the wrong "atomic" pkg.
___
*[`pkg/cmd/roachtest/tests/export_parquet.go` line 35 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104234#-NX0Q73L-ptKqJNeYmHK:-NXAtdjx3pGQ84qAYy8I:bs4liv3) ([raw file](https://github.com/cockroachdb/cockroach/blob/593d98d75a81fbe2662d154cd5dddb0314b47363/pkg/cmd/roachtest/tests/export_parquet.go#L35)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

do we want to have smaller non-manual test? Or does it exist?
</blockquote></details>

I added one for TPCC-100. 
___
*[`pkg/sql/importer/exportparquet.go` line 37 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104234#-NX0SL_D2MyNIuGoYWDN:-NXAtgIj3xFJkl_r0Gpz:b-4hupt) ([raw file](https://github.com/cockroachdb/cockroach/blob/593d98d75a81fbe2662d154cd5dddb0314b47363/pkg/sql/importer/exportparquet.go#L37)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

add todo or just do it here -- we need memory monitor for this stuff.
</blockquote></details>

Done. Added an TODO and an issue.
___
*[`pkg/sql/importer/exportparquet.go` line 643 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104234#-NX0REWu459Bxb-vRgVR:-NXAtk1UAopFHwFqgq-h:b-s1jas1) ([raw file](https://github.com/cockroachdb/cockroach/blob/593d98d75a81fbe2662d154cd5dddb0314b47363/pkg/sql/importer/exportparquet.go#L643)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

crlparquet supports other compression formats, right?
Perhaps add an issue/todo to make export support those too.
Also, todo to refactor string -> codec parsing.
</blockquote></details>

Done. Added TODO.
___
*[`pkg/sql/importer/exportparquet_test.go` line 145 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104234#-NX0T4cY2kNYX3b--zzp:-NXAtmfI30QP1-nkoWxe:b-2uv1uy) ([raw file](https://github.com/cockroachdb/cockroach/blob/593d98d75a81fbe2662d154cd5dddb0314b47363/pkg/sql/importer/exportparquet_test.go#L145)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

and it does appear that parquet does not have notion of collation... am I correct?
</blockquote></details>

You are correct.

**Comment by RaduBerinde** [comment]
*[`pkg/cmd/roachtest/tests/export_parquet.go` line 125 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/104234#-NeJuRkk9jqxVtfpjirH:-NeJuDPv5rM856WXTMkP:b-d2vjy3) ([raw file](https://github.com/cockroachdb/cockroach/blob/500cb439722a401a56b46caa55505a9a863ee7b3/pkg/cmd/roachtest/tests/export_parquet.go#L125)):*
> ```Go
> 		Name:            "export/parquet/tpcc-100",
> 		Owner:           registry.OwnerCDC,
> 		Tags:            registry.Tags("daily"),
> ```

"daily" is not a tag used by anything. AFAICT this means that this test will not run as part of any suite, just like "manual" above. Was the intention for this to be part of the nightly suite?

**Comment by jayshrivastava** [comment]
@RaduBerinde Yeah this should be nightly.

**Pull request merged**
