### PR TITLE
distsql: add disk usage accounting for external storage

### PR DESCRIPTION
**Pull request by asubiotto**
Add an additional monitor to the distsql server which is plumbed down to the diskRowContainer to track and limit disk usage.

This is basically what's needed to limit the disk usage of processors spilling over to disk. I'm uncomfortable with `pkg/sql/mon` being so memory specific in name. Should that be changed before this PR goes in?

cc @petermattis

### CODE REVIEW

**Comment by RaduBerinde** [comment]
CC @knz

**Comment by knz** [comment]
You can rename `MemoryMonitor` to `StorageMonitor` perhaps?

**Comment by RaduBerinde** [comment]
I suggest `s/Memory/Resource` in `mon`

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/disk_row_container.go, line 76 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-Kq4mgVbNwI89CHL4kW2:-Kq4mgVbNwI89CHL4kW3:b-6waee5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b739d338ee4442c0970f202499e2357990ee189/pkg/sql/distsqlrun/disk_row_container.go#L76)):*
> ```Go
> // 	  is created with.
> // 	- e is the underlying store that rows are stored on.
> func makeDiskRowContainer(
> ```

This comment needs to describe what mon is used for (especially given the current confusing name).

---

*[pkg/sql/distsqlrun/disk_row_container_test.go, line 118 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-Kq4mwgM-pHXFKy_hEKx:-Kq4mwgM-pHXFKy_hEKy:bb02pw7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b739d338ee4442c0970f202499e2357990ee189/pkg/sql/distsqlrun/disk_row_container_test.go#L118)):*
> ```Go
> 				func() {
> 					d, err := makeDiskRowContainer(
> 						ctx, evalCtx.Mon, types, ordering, memRowContainer{}, tempEngine,
> ```

I don't understand what we're doing here. Isn't Mon for memory? We're using the same monitor for memroy and disk?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-:-Kq4n15s-3jJHUg7P7kp:b-vm2b2n)*

**Comment by arjunravinarayan** [comment]
`ResourceMonitor` works for me.

---

Reviewed 3 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/disk_row_container_test.go, line 118 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-Kq4mwgM-pHXFKy_hEKx:-KqOHRwN8oPv1hG92Kq-:bnq7sa3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b739d338ee4442c0970f202499e2357990ee189/pkg/sql/distsqlrun/disk_row_container_test.go#L118)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I don't understand what we're doing here. Isn't Mon for memory? We're using the same monitor for memroy and disk?
</blockquote></details>

Agreed. I think the mixed nomenclature conflating memory and disk accounting is showing a clear first victim here, so we should clear that up.

---

*[pkg/sql/distsqlrun/server.go, line 123 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-KqOFxSGcj08V7Qwpmoi:-KqOFxSGcj08V7Qwpmoj:b-tsz5qu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b739d338ee4442c0970f202499e2357990ee189/pkg/sql/distsqlrun/server.go#L123)):*
> ```Go
> 	// gracefully OOM if the working set gets too large.
> 	tempStorage engine.Engine
> 	// diskMonitor is used to monitor temporary storage disk usage.
> ```

Add a comment that the actual disk space will be a small multiple (~1.1) of the monitored disk, due to RocksDB space amplification.

---

*[pkg/sql/distsqlrun/server.go, line 149 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-KqOGEXaPL9JIPLx2sNv:-KqOGEXaPL9JIPLx2sNw:bqu81t6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b739d338ee4442c0970f202499e2357990ee189/pkg/sql/distsqlrun/server.go#L149)):*
> ```Go
> 			nil,
> 			-1,            /* increment: use default block size */
> 			math.MaxInt64, // TODO(asubiotto): Choose noteworthy. Maybe fraction?
> ```

We might want to set this directly when creating the RocksDB engine for `tempEngine`, and then copy it here. Not sure what the right move is there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-:-KqOFN3pkq75yEmRsY5c:b-jqbycw)*

**Comment by andreimatei** [comment]
A test showing a query fail with the out-of-disk-space would be sick. Perhaps it has to wait until the rig is hooked up to queries.

---

Review status: 3 of 5 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/disk_row_container.go, line 76 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-Kq4mgVbNwI89CHL4kW2:-KqP33nVj4k6xdVa29IN:b-8zgh64) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b739d338ee4442c0970f202499e2357990ee189/pkg/sql/distsqlrun/disk_row_container.go#L76)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This comment needs to describe what mon is used for (especially given the current confusing name).
</blockquote></details>

I think it'd be better if this function would take in an account, not a monitor. For example, if these accounts were named, it'd be better if the caller was assigning the name.

---

*[pkg/sql/distsqlrun/disk_row_container.go, line 167 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-KqP3pVnZwMxxJG_2dSv:-KqP3pVnZwMxxJG_2dSw:b5fln8v) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b739d338ee4442c0970f202499e2357990ee189/pkg/sql/distsqlrun/disk_row_container.go#L167)):*
> ```Go
> 	d.scratchKey = encoding.EncodeUvarintAscending(d.scratchKey, d.rowID)
> 	if err := d.diskAcc.Grow(ctx, int64(len(d.scratchKey)+len(d.scratchVal))); err != nil {
> 		if pgErr, ok := err.(*pgerror.Error); ok && pgErr.Code == pgerror.CodeOutOfMemoryError {
> ```

If we use accounts for disks (and other resources in general), this error needs to change or be configurable.

---

*[pkg/sql/distsqlrun/server.go, line 146 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-KqP4Ue16Qf-iUCsouHX:-KqP4Ue16Qf-iUCsouHY:bfwt3t8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b739d338ee4442c0970f202499e2357990ee189/pkg/sql/distsqlrun/server.go#L146)):*
> ```Go
> 		diskMonitor: mon.MakeMonitor(
> 			"distsql-tempstorage",
> 			nil,
> ```

nit: comment the nils

---

*[pkg/sql/distsqlrun/server.go, line 148 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-KqP5VItQp9SMqKGEPvT:-KqP5VItQp9SMqKGEPvU:b-c22gi3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b739d338ee4442c0970f202499e2357990ee189/pkg/sql/distsqlrun/server.go#L148)):*
> ```Go
> 			nil,
> 			nil,
> 			-1,            /* increment: use default block size */
> ```

the default is 10k. Much too low for disk, I think. 

---

*[pkg/sql/distsqlrun/server.go, line 159 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-KqP4lQNvSwJoaV5uruA:-KqP4lQNvSwJoaV5uruB:b3szrz5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b739d338ee4442c0970f202499e2357990ee189/pkg/sql/distsqlrun/server.go#L159)):*
> ```Go
> 	if capacity, err := ds.tempStorage.Capacity(); err != nil {
> 		// TODO(asubiotto): Fatalf? Return error?
> 		log.Warning(
> ```

Fatalf is my vote

---

*[pkg/sql/distsqlrun/server.go, line 164 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-KqP5lsJxOZ0XZeFlQFw:-KqP5lsJxOZ0XZeFlQFx:b-4ilc1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b739d338ee4442c0970f202499e2357990ee189/pkg/sql/distsqlrun/server.go#L164)):*
> ```Go
> 		)
> 	} else {
> 		ds.diskMonitor.Start(ctx, nil, mon.MakeStandaloneBudget(capacity.Capacity/4))
> ```

lift the 4 to a constant with some name

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-:-KqP6N0WmZ7SAP0ji1x9:be3sh5r)*

**Comment by asubiotto** [comment]
Thanks for the reviews!

Added a commit that generalizes memory accounting (this includes `s/MemoryMonitor/BytesMonitor`).

@andreimatei: Note that there's a test `TestDiskRowContainerDiskFull` in `disk_row_container_test.go` (although it has less coverage than I think you're suggesting).

---

Review status: 0 of 20 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/disk_row_container.go, line 76 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-Kq4mgVbNwI89CHL4kW2:-KqPG8KakGDn2eT-Jgr4:b-j0cf9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b739d338ee4442c0970f202499e2357990ee189/pkg/sql/distsqlrun/disk_row_container.go#L76)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think it'd be better if this function would take in an account, not a monitor. For example, if these accounts were named, it'd be better if the caller was assigning the name.
</blockquote></details>

Changed the name and added an explanation to the comment. The pattern used to track allocations is to have components maintain one or more instances of `BytesAccount` so it makes more sense to pass a `BytesMonitor` to a component in general and I don't think there's a good reason not to here so leaving it as it is.

---

*[pkg/sql/distsqlrun/disk_row_container.go, line 167 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-KqP3pVnZwMxxJG_2dSv:-KqPH14YLm8XUmXZHUJm:blpby2t) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b739d338ee4442c0970f202499e2357990ee189/pkg/sql/distsqlrun/disk_row_container.go#L167)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

If we use accounts for disks (and other resources in general), this error needs to change or be configurable.
</blockquote></details>

Done. The resource used is now specified when creating a monitor which now returns a suitable error (see `pkg/sql/mon/bytes_resource.go`.

---

*[pkg/sql/distsqlrun/disk_row_container_test.go, line 118 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-Kq4mwgM-pHXFKy_hEKx:-KqPHau2bCcMtd0eBZ6h:b-t05lqq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b739d338ee4442c0970f202499e2357990ee189/pkg/sql/distsqlrun/disk_row_container_test.go#L118)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Agreed. I think the mixed nomenclature conflating memory and disk accounting is showing a clear first victim here, so we should clear that up.
</blockquote></details>

Yes, I thought it wouldn't matter since it's an unlimited monitor used in a test. Changed to be clearer.

---

*[pkg/sql/distsqlrun/server.go, line 123 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-KqOFxSGcj08V7Qwpmoi:-KqPVbe_9VbI1ii24vfD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b739d338ee4442c0970f202499e2357990ee189/pkg/sql/distsqlrun/server.go#L123)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Add a comment that the actual disk space will be a small multiple (~1.1) of the monitored disk, due to RocksDB space amplification.
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/server.go, line 146 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-KqP4Ue16Qf-iUCsouHX:-KqPLDDV7XQXUNTzgmbv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b739d338ee4442c0970f202499e2357990ee189/pkg/sql/distsqlrun/server.go#L146)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: comment the nils
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/server.go, line 148 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-KqP5VItQp9SMqKGEPvT:-KqPUQUM5v-xriVl2Su9:bm3xe3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b739d338ee4442c0970f202499e2357990ee189/pkg/sql/distsqlrun/server.go#L148)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

the default is 10k. Much too low for disk, I think. 
</blockquote></details>

What would you recommend?

---

*[pkg/sql/distsqlrun/server.go, line 149 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-KqOGEXaPL9JIPLx2sNv:-KqPLF4xrmGQ2KNLh0Bu:boeqsqo) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b739d338ee4442c0970f202499e2357990ee189/pkg/sql/distsqlrun/server.go#L149)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

We might want to set this directly when creating the RocksDB engine for `tempEngine`, and then copy it here. Not sure what the right move is there.
</blockquote></details>

I think it's fine as it is until there are non-distsql uses of `tempStorage`. In this case the server would create a root disk monitor for `tempStorage`. We would still create one here with the only difference being passing in the root monitor as `pool` in `Start`.

---

*[pkg/sql/distsqlrun/server.go, line 159 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-KqP4lQNvSwJoaV5uruA:-KqPMkd8U-K-RAmgf8Wm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b739d338ee4442c0970f202499e2357990ee189/pkg/sql/distsqlrun/server.go#L159)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Fatalf is my vote
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/server.go, line 164 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-KqP5lsJxOZ0XZeFlQFw:-KqPTK2dPuovoYp5N1bs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b739d338ee4442c0970f202499e2357990ee189/pkg/sql/distsqlrun/server.go#L164)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

lift the 4 to a constant with some name
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-:-KqPCdeFFVzKS22de3pQ:br6he38)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 20 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/server.go, line 148 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-KqP5VItQp9SMqKGEPvT:-KqYUt2XVANdmC01sNLP:b-jn3rsp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b739d338ee4442c0970f202499e2357990ee189/pkg/sql/distsqlrun/server.go#L148)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What would you recommend?
</blockquote></details>

Something on the order of a query's memory budget. What is that now, btw? Tens of megabytes?

---

*[pkg/sql/mon/bytes_resource.go, line 21 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-KqYVqpNrF0PReOylTiQ:-KqYVqpNrF0PReOylTiR:b-hyff7m) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b8c92f6991de3dae0b6d61afb74b1faa22c72e/pkg/sql/mon/bytes_resource.go#L21)):*
> ```Go
> import "github.com/cockroachdb/cockroach/pkg/sql/pgwire/pgerror"
> 
> // BytesResource is an interface used to abstract the specifics of tracking
> ```

Why talk about "bytes" in this interface?

---

*[pkg/sql/mon/bytes_resource.go, line 33 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-KqYVYvS1wdKAk0nmqg3:-KqYVYvS1wdKAk0nmqg4:btcfxrt) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b8c92f6991de3dae0b6d61afb74b1faa22c72e/pkg/sql/mon/bytes_resource.go#L33)):*
> ```Go
> 
> // NewBudgetExceededError implements the BytesResource interface.
> func (m MemoryResource) NewBudgetExceededError(requested int64, budget int64) error {
> ```

please put the units in the name of args

---

*[pkg/sql/mon/bytes_usage.go, line 259 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-KqYWkPfx7l134cTbxyr:-KqYWkPfx7l134cTbxys:bkw5m3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/58023b964a2e9507709dd4f05df0a412a7f01156/pkg/sql/mon/bytes_usage.go#L259)):*
> ```Go
> func MakeMonitor(
> 	name string,
> 	resource BytesResource,
> ```

I'd suggest having `MakeMonitor` take an enum about the type of resource (and create the BytesResource implementation internally) rather than having the caller have to create some struct that won't make much sense.
Also the implementations of the resources should be singletons, I think. If you make them singletons, than the previous suggestion can go away - the caller can pass the singletons.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-:-KqYXewdrCqXj3vZFPlg:bnfp4nl)*

**Comment by asubiotto** [comment]
Review status: 0 of 20 files reviewed at latest revision, 11 unresolved discussions.

---

*[pkg/sql/distsqlrun/server.go, line 148 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-KqP5VItQp9SMqKGEPvT:-KqYaVWaLEOnUSsXKp_C:bsm34rq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b739d338ee4442c0970f202499e2357990ee189/pkg/sql/distsqlrun/server.go#L148)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Something on the order of a query's memory budget. What is that now, btw? Tens of megabytes?
</blockquote></details>

Done. `64MB`

---

*[pkg/sql/mon/bytes_usage.go, line 259 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-KqYWkPfx7l134cTbxyr:-KqYyaN4vSpSDOUW3bWX:b-aakl02) ([raw file](https://github.com/cockroachdb/cockroach/blob/58023b964a2e9507709dd4f05df0a412a7f01156/pkg/sql/mon/bytes_usage.go#L259)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'd suggest having `MakeMonitor` take an enum about the type of resource (and create the BytesResource implementation internally) rather than having the caller have to create some struct that won't make much sense.
Also the implementations of the resources should be singletons, I think. If you make them singletons, than the previous suggestion can go away - the caller can pass the singletons.
</blockquote></details>

Done. Made them singletons, thanks for the suggestion!

---

*[pkg/sql/mon/bytes_resource.go, line 21 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-KqYVqpNrF0PReOylTiQ:-KqYacxsVTWEBi6J_7JF:b-rs57li) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b8c92f6991de3dae0b6d61afb74b1faa22c72e/pkg/sql/mon/bytes_resource.go#L21)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Why talk about "bytes" in this interface?
</blockquote></details>

Specificity but it's unnecessary so removed it.

---

*[pkg/sql/mon/bytes_resource.go, line 33 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265#-KqYVYvS1wdKAk0nmqg3:-KqYcRxgQFkRqw18CvkU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b8c92f6991de3dae0b6d61afb74b1faa22c72e/pkg/sql/mon/bytes_resource.go#L33)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

please put the units in the name of args
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17265)*

**Comment by RaduBerinde** [comment]
LGTM

**Pull request merged**
