### PR TITLE
sql/catalog: break descpb->parser dep

### PR DESCRIPTION
**Pull request by ajwerner**
There was no need for this. Saw it as I was looking at something else.

Epic: None

Release note: None

### CODE REVIEW

**Review by postamar — APPROVED** [review]
¡LGTM!

**Comment by ajwerner** [comment]
TFTR

bors r+

**Comment by ajwerner** [comment]
Intentionally?

**Comment by rafiss** [comment]
I didn't look into it. I presume @healthy-pod found a build issue with this change while fixing the bug that caused `bazci` to ignore some errors.

**Comment by ajwerner** [comment]
It was broken. Bad copy-pasta:

```python
diff --git a/pkg/BUILD.bazel b/pkg/BUILD.bazel
index e493abfd0b3..bfc9dab23d5 100644
Binary files a/pkg/BUILD.bazel and b/pkg/BUILD.bazel differ
diff --git a/pkg/sql/catalog/descpb/BUILD.bazel b/pkg/sql/catalog/descpb/BUILD.bazel
index 3aedf988c23..6664e3657a5 100644
--- a/pkg/sql/catalog/descpb/BUILD.bazel
+++ b/pkg/sql/catalog/descpb/BUILD.bazel
@@ -96,7 +96,7 @@ stringer(
 )
 
 disallowed_imports_test(
-    "catalog",
+    "descpb",
     disallowed_list = ["//pkg/sql/parser"],
 )
```

**Comment by healthy-pod** [comment]
> I didn't look into it. I presume @healthy-pod found a build issue with this change while fixing the bug that caused bazci to ignore some errors.

True, just didn't want to ping @ajwerner at midnight 😄

**Pull request merged**
