### PR TITLE
sql: Add statement_timeout session variable

### LINKED ISSUE #20789: sql: support statement_timeout
`SET statement_timeout` sets the statement timeout. From the docs:

> Abort any statement that takes more than the specified number of milliseconds, starting from the time the command arrives at the server from the client. If log_min_error_statement is set to ERROR or lower, the statement that timed out will also be logged. A value of zero (the default) turns this off.

This should be doable if we hook into query cancellation.

https://www.postgresql.org/docs/10/static/runtime-config-client.html

Required by the admin tool PSequel.

### PR DESCRIPTION
**Pull request by abhimadan**
This new session variable is similar to the `statement_timeout` variable
in Postgres, but instead of starting the timer when the query reaches
the server, as documented [in the Postgres docs](https://www.postgresql.org/docs/9.4/static/runtime-config-client.html), the timer starts
when the query is registered as active. In practice, this should make
little to no difference on usage.

Fixes #20789.

Release note (sql change): Add `statement_timeout` session variable.

### CODE REVIEW

**Comment by abhimadan** [comment]
As-is, the error returned to the client is the usual "query execution canceled" error. We might want to return a special "query canceled due to timeout" error instead.

**Comment by jordanlewis** [comment]
Great work. To make this complete, you should fix that error message you mentioned and add a logic test.

Here's what Postgres does:

```
tpcc=# set statement_timeout=500;
SET
tpcc=# select generate_series(1,100000000);
ERROR:  canceling statement due to statement timeout
Time: 574.169 ms
```

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/conn_executor_exec.go, line 152 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23399#-L6s7751xMeJzSi5f7Ug:-L6s7751xMeJzSi5f7Uh:bamqs4v) ([raw file](https://github.com/cockroachdb/cockroach/blob/b67edf8009ed6884ef1284f451076926ce9758b8/pkg/sql/conn_executor_exec.go#L152)):*
> ```Go
> 	}()
> 
> 	if _, ok := stmt.AST.(tree.HiddenFromShowQueries); !ok && ex.sessionData.StmtTimeout > 0 {
> ```

nit: minor, but I would put the `ex.sessionData.StmtTimeout` check first. Most commonly that will already be false, so we won't have to do the slightly more expensive cast in that case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23399#-:-L6s7l-UntH4STysAzQk:b-r21335)*

**Comment by dianasaur323** [comment]
quick question - is this at the query or transaction level?

**Comment by abhimadan** [comment]
@dianasaur323 It's query-level cancellation.

**Comment by dianasaur323** [comment]
Got it, thanks!

**Comment by abhimadan** [comment]
Added a new query timeout error and added a logic test.

---

Review status: 8 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/conn_executor_exec.go, line 152 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23399#-L6s7751xMeJzSi5f7Ug:-L6vxCy0gHJZgbU3pK3d:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b67edf8009ed6884ef1284f451076926ce9758b8/pkg/sql/conn_executor_exec.go#L152)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: minor, but I would put the `ex.sessionData.StmtTimeout` check first. Most commonly that will already be false, so we won't have to do the slightly more expensive cast in that case.
</blockquote></details>

Done.

---

*[pkg/sql/conn_executor_exec.go, line 147 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23399#-L6vwdrsP7u17Sp6okzE:-L6vwdrsP7u17Sp6okzF:bdde159) ([raw file](https://github.com/cockroachdb/cockroach/blob/1074e2420731a6dbc64edf19f0e83fb4b13131a8/pkg/sql/conn_executor_exec.go#L147)):*
> ```Go
> 			// stop the timer before unregistering the query.
> 			if !timeoutTicker.Stop() {
> 				<-doneAfterFunc
> ```

I realized my comment here was incorrect, since the `AfterFunc` callback running does not imply that its goroutine is holding `ex.mu`. Corrected so that it waits for the goroutine to finish if the callback has started.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23399#-:-L6vxGbJXDjsmChz8NQt:bv5h3rz)*

**Comment by andreimatei** [comment]
Please add "Touches #5924"  to the commit message.

A question - why not start measuring from when the command is read from the network? We already plumb a "received at" to the commands in the `StmtBuf` consumed by the `connExecutor`.

---

Review status: 8 of 11 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[pkg/sql/conn_executor_exec.go, line 147 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23399#-L6wWxPAmI98IvUoMQct:-L6wWxPAmI98IvUoMQcu:b-70w9o7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3ef64e1790dce26375cf7d2f8158023d278b2b/pkg/sql/conn_executor_exec.go#L147)):*
> ```Go
> 			// stop the timer before unregistering the query.
> 			if !timeoutTicker.Stop() {
> 				<-doneAfterFunc
> ```

why do we need to wait? Does anything bad happen if we let `unregisterFn` race with `ex.cancelQuery()`? Or is the waiting about avoiding a data race on `queryTimedOut`?

---

*[pkg/sql/conn_executor_exec.go, line 162 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23399#-L6wWhu35_NBGBVXdPQD:-L6wWhu35_NBGBVXdPQE:b-hq4ch8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3ef64e1790dce26375cf7d2f8158023d278b2b/pkg/sql/conn_executor_exec.go#L162)):*
> ```Go
> 
> 	if ex.sessionData.StmtTimeout > 0 {
> 		if _, ok := stmt.AST.(tree.HiddenFromShowQueries); !ok {
> ```

what's the `HiddenFromShowQueries` test above? Why do those queries need special handling?

---

*[pkg/sql/conn_executor_exec.go, line 447 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23399#-L6wUWui_wziD-hq-pjf:-L6wUWui_wziD-hq-pjg:b-ynlhf8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3ef64e1790dce26375cf7d2f8158023d278b2b/pkg/sql/conn_executor_exec.go#L447)):*
> ```Go
> 	planner *planner,
> 	unregisterQuery func(),
> 	overwriteErrWithCancelErr func(RestrictedCommandResult),
> ```

if you keep this argument, it needs a comment.
But it seems to me like a very bizarre argument to pass. Can the overwriting just be part of `unregisterQuery()` - in which case that can be renamed to `queryDone` or smth.
Otherwise, make it a method.

---

*[pkg/sql/vars.go, line 450 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23399#-L6wZE615m7U1hBVZher:-L6wZE615m7U1hBVZhes:bjy6avt) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3ef64e1790dce26375cf7d2f8158023d278b2b/pkg/sql/vars.go#L450)):*
> ```Go
> 	},
> 
> 	`statement_timeout`: {
> ```

let's please also accept `intervals` - shame on Postgres for not not doing so and for not putting units in their names. We should mostly advertise the interval version.
Look at `RegisterDurationSetting()` for how to parse an interval (I think).

---

*[pkg/sql/logictest/testdata/logic_test/distsql_join, line 260 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23399#-L6wZ8FZaQfk6E_6LVDX:-L6wZ8FZaQfk6E_6LVDY:b-n0utg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6bdf5dad976074d73e234d104a0745c1d566de5/pkg/sql/logictest/testdata/logic_test/distsql_join#L260)):*
> ```
> ----
> https://cockroachdb.github.io/distsqlplan/decode.html?eJzEkkFr4zAQhe_7K5Y57RIVIifOwVDwNYUmJe2thOBaU1fF8bijMbSE_Pdi65DE1EpzKL1Jo_nemydmBxUZXGRbdJA8ggYFMawV1Ew5Okfcln3T3LxDMlZgq7qRtrxWkBMjJDsQKyVCAgu6ohoUGJTMll3TXgE1ckCcZAVCMturI1kdln3InkpcYWaQT8ShZrvN-CM11ol7Kzfb142gE1CwbCT5m2oY8teX-N8TS9861aNB8eiXw01-Mtx0UPyg2VTEBhlNfxfOt3wx4S1ygTdkq_6YJT7Lv1SP_l-zLV788fA9Ko0GQ8QnIc5s9QpdTZXDby32uE2ApkD_I44azvGOKe9s_HXZcV3BoBP_OvOXeeWf2gGPYR2EozAcBeH4BNZ9eBKEp2Hn6QXOUR-Og_C457ze__kMAAD__4m9mGY=
> ```

what's with this change?

---

*[pkg/sql/logictest/testdata/logic_test/set, line 257 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23399#-L6wYz77fz0nQt61EzR2:-L6wYz77fz0nQt61EzR3:brepfg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3ef64e1790dce26375cf7d2f8158023d278b2b/pkg/sql/logictest/testdata/logic_test/set#L257)):*
> ```
> # Test statement_timeout on a long-running query.
> statement ok
> SET statement_timeout = 100
> ```

why wait 100 milliseconds? 1 should do it.

---

*[pkg/sql/sessiondata/session_data.go, line 57 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23399#-L6wXyLAnK_tWedWG3kz:-L6wXyLAnK_tWedWG3l-:bisj3kd) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3ef64e1790dce26375cf7d2f8158023d278b2b/pkg/sql/sessiondata/session_data.go#L57)):*
> ```Go
> 	// StmtTimeout is the duration a query is permitted to run (in milliseconds)
> 	// before it is canceled by the session. If set to 0, there is no timeout.
> 	StmtTimeout int
> ```

If this stays an int, the unit should be in the name - `StmtTimeoutMillis`. But let's use go's Duration and not lose any Mars orbiters.

---

*[pkg/sql/sqlbase/errors.go, line 238 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23399#-L6wYjH_gxK_9qgLVAOj:-L6wYjH_gxK_9qgLVAOk:b1wt6q5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3ef64e1790dce26375cf7d2f8158023d278b2b/pkg/sql/sqlbase/errors.go#L238)):*
> ```Go
> 
> // NewQueryTimeoutError creates a query timeout error.
> func NewQueryTimeoutError() error {
> ```

not your code, but both this and the method above lie - they don't `new` anything. Let's remove the functions and export the singleton vars.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23399#-:-L6wTtksOLi7LUgU_38J:b-vcol3t)*

**Comment by andreimatei** [comment]
Review status: 8 of 11 files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---

*[pkg/sql/conn_executor_exec.go, line 116 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23399#-L6wai55A8-pHQKYTlJV:-L6wai55A8-pHQKYTlJW:b5w4nen) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3ef64e1790dce26375cf7d2f8158023d278b2b/pkg/sql/conn_executor_exec.go#L116)):*
> ```Go
> 
> 	queryTimedOut := false
> 	overwriteErrWithCancelErr := func(res RestrictedCommandResult) {
> ```

I know it was the same way before, but this should only conditionally call `OverwriteError()` is `res.Err() != nil`. Not because I particularly care about queries where cancelation races with finishing succeeding, but because if a query ignores cancelation,  I'd rather we don't hide that fact by returning a cancelation error anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23399)*

**Comment by abhimadan** [comment]
I thought that we shouldn't start the timer until the query can be cancelled (i.e. when it's added to `ActiveQueries`), but I didn't know at first that passing a negative `Duration` makes it tick immediately. I've changed it to measure from `sessionQueryReceived`.

---

Review status: 0 of 15 files reviewed at latest revision, 11 unresolved discussions.

---

*[pkg/sql/conn_executor_exec.go, line 116 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23399#-L6wai55A8-pHQKYTlJV:-L6xJ9UGHqZoCxbmVJHS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3ef64e1790dce26375cf7d2f8158023d278b2b/pkg/sql/conn_executor_exec.go#L116)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I know it was the same way before, but this should only conditionally call `OverwriteError()` is `res.Err() != nil`. Not because I particularly care about queries where cancelation races with finishing succeeding, but because if a query ignores cancelation,  I'd rather we don't hide that fact by returning a cancelation error anyway.
</blockquote></details>

Done.

---

*[pkg/sql/conn_executor_exec.go, line 147 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23399#-L6wWxPAmI98IvUoMQct:-L6xXUtGDrjtH6QB02nl:b-q33o0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3ef64e1790dce26375cf7d2f8158023d278b2b/pkg/sql/conn_executor_exec.go#L147)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

why do we need to wait? Does anything bad happen if we let `unregisterFn` race with `ex.cancelQuery()`? Or is the waiting about avoiding a data race on `queryTimedOut`?
</blockquote></details>

`unregisterFn` and `cancelQuery` do race, but it doesn't really matter, because access to `ActiveQueries` is serialized, and `cancelQuery` is safe to call if the map entry no longer exists. But as you've said, the race does matter for `queryTimedOut`, since we want to report the correct error message. For example, if a user doesn't issue a `CANCEL QUERY` but the query times out, giving only a generic `query execution canceled` error would be confusing. Since receiving from `doneAfterFunc` depends on whether or not the timer was successfully stopped, it's easier to receive as soon as we attempt to stop the timer.

---

*[pkg/sql/conn_executor_exec.go, line 162 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23399#-L6wWhu35_NBGBVXdPQD:-L704MQrTn8SdYy2-s9B:b-cqu0x5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3ef64e1790dce26375cf7d2f8158023d278b2b/pkg/sql/conn_executor_exec.go#L162)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what's the `HiddenFromShowQueries` test above? Why do those queries need special handling?
</blockquote></details>

Statements that implement `HiddenFromShowQueries` typically do so because they don't want to expose their query ID and be cancelled; some examples of these statements are `ALTER INDEX` and `ALTER TABLE`. I didn't want to mess with that promise by allowing them to be timed out.

---

*[pkg/sql/conn_executor_exec.go, line 447 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23399#-L6wUWui_wziD-hq-pjf:-L704kVyyq8uu-i1wuDx:b-gb7ozs) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3ef64e1790dce26375cf7d2f8158023d278b2b/pkg/sql/conn_executor_exec.go#L447)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

if you keep this argument, it needs a comment.
But it seems to me like a very bizarre argument to pass. Can the overwriting just be part of `unregisterQuery()` - in which case that can be renamed to `queryDone` or smth.
Otherwise, make it a method.
</blockquote></details>

I like the idea of making a single `queryDone`.

---

*[pkg/sql/vars.go, line 450 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23399#-L6wZE615m7U1hBVZher:-L704wxt70FBMacJPGep:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3ef64e1790dce26375cf7d2f8158023d278b2b/pkg/sql/vars.go#L450)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

let's please also accept `intervals` - shame on Postgres for not not doing so and for not putting units in their names. We should mostly advertise the interval version.
Look at `RegisterDurationSetting()` for how to parse an interval (I think).
</blockquote></details>

Done.

---

*[pkg/sql/logictest/testdata/logic_test/distsql_join, line 260 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23399#-L6wZ8FZaQfk6E_6LVDX:-L705F3naTpyDKORPVJt:b-5omso7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6bdf5dad976074d73e234d104a0745c1d566de5/pkg/sql/logictest/testdata/logic_test/distsql_join#L260)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what's with this change?
</blockquote></details>

I ran `-rewrite-results-in-testfiles` on all the logic tests, and it removed a trailing newline in this file. I thought this change would be swallowed up in a future PR anyway, but I don't feel strongly about keeping it here.

---

*[pkg/sql/logictest/testdata/logic_test/set, line 257 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23399#-L6wYz77fz0nQt61EzR2:-L705kqar2fhY7OAPbFP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3ef64e1790dce26375cf7d2f8158023d278b2b/pkg/sql/logictest/testdata/logic_test/set#L257)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

why wait 100 milliseconds? 1 should do it.
</blockquote></details>

Done.

---

*[pkg/sql/sessiondata/session_data.go, line 57 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23399#-L6wXyLAnK_tWedWG3kz:-L705nDu-M3FJdUXAGK7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3ef64e1790dce26375cf7d2f8158023d278b2b/pkg/sql/sessiondata/session_data.go#L57)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

If this stays an int, the unit should be in the name - `StmtTimeoutMillis`. But let's use go's Duration and not lose any Mars orbiters.
</blockquote></details>

Done.

---

*[pkg/sql/sqlbase/errors.go, line 238 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23399#-L6wYjH_gxK_9qgLVAOj:-L705ommcv3xlHxHyvL5:b-me64wj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3ef64e1790dce26375cf7d2f8158023d278b2b/pkg/sql/sqlbase/errors.go#L238)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

not your code, but both this and the method above lie - they don't `new` anything. Let's remove the functions and export the singleton vars.
</blockquote></details>

Done. Made a separate commit before the main one to address this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23399#-:-L703EJEAOVM7fZKMhqb:b-23v7bn)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 15 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[pkg/sql/conn_executor_exec.go, line 162 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23399#-L6wWhu35_NBGBVXdPQD:-L70NM1MnlKL6Hx8Or3t:b-jddua6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3ef64e1790dce26375cf7d2f8158023d278b2b/pkg/sql/conn_executor_exec.go#L162)):*
<details><summary><i>Previously, abhimadan (Abhishek Madan) wrote…</i></summary><blockquote>

Statements that implement `HiddenFromShowQueries` typically do so because they don't want to expose their query ID and be cancelled; some examples of these statements are `ALTER INDEX` and `ALTER TABLE`. I didn't want to mess with that promise by allowing them to be timed out.
</blockquote></details>

mmm I dunno... `HiddenFromShowQueries` suggests that it refers strictly to the output of the `SHOW QUERIES` command. The fact that, as a consequence, that means that one also can't cancel those queries I don't know if it is intended or not. Whether or not hiding anything from that report is a good idea is questionable, but I don't particularly care. I guess you can make some arguments for schema changes, cause those are reported elsewhere.
Regardless, unless you have good reason to do so, I wouldn't conflate `HFSQ` with cancelation more than it is already. If some operation doesn't like being canceled, it should make sure it doesn't check for cancelation. Generally that's not feasible cause our contexts get canceled when the connection drops anyway, for example.
I'd remove this test. 

---

*[pkg/sql/conn_executor_exec.go, line 124 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/23399#-L70LSdw09j8-l310DtA:-L70LSdw09j8-l310DtB:b4vdhng) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3583fe78345154e27831db66c7e8e0192e1507c/pkg/sql/conn_executor_exec.go#L124)):*
> ```Go
> 	queryDone := func(ctx context.Context, res RestrictedCommandResult) {
> 		if timeoutTicker != nil {
> 			// We don't need cancelQuery to run before unregisterFn, but we do want
> ```

nit: I think this comment will leave readers with a blank stare. One thing that would help I think would be moving it a line down to make it clear that it applies to the channel read. (stopping the timer would be a good idea regardless of whatever race considerations).

As the code is written, the reading has a simpler explanation - it avoids a data race on `queryTimedOut`, which is in itself inadmissible regardless of further considerations about other consequences.  I would replace the comment with `// Block for the timer callback to avoid a data race on queryTimedOut`. That would be sufficient for putting people that want to change this code en garde to reason through the consequences of races.

---

*[pkg/sql/set_var.go, line 215 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/23399#-L70PNJJX1ZRUykLbhrr:-L70PNJJX1ZRUykLbhrs:bxv9gu6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3583fe78345154e27831db66c7e8e0192e1507c/pkg/sql/set_var.go#L215)):*
> ```Go
> 	var timeout time.Duration
> 	switch v := tree.UnwrapDatum(&evalCtx.EvalContext, d).(type) {
> 	case *tree.DInterval:
> ```

Well, I think we should also accept a string that can be parsed as a `DInterval` (see tree.ParseDInterval()`). Otherwise, how is one supposed to actually pass a `DInterval` from a query - you'd have to use an explicit cast?
Please add a test for the string version.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23399#-:-L70Q-cXLFTnzzyLjHFZ:bnfp4nl)*

**Comment by abhimadan** [comment]
Review status: 0 of 15 files reviewed at latest revision, 11 unresolved discussions, some commit checks pending.

---

*[pkg/sql/conn_executor_exec.go, line 162 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23399#-L6wWhu35_NBGBVXdPQD:-L70n18pDe1gbReorN6O:b-91uifg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3ef64e1790dce26375cf7d2f8158023d278b2b/pkg/sql/conn_executor_exec.go#L162)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

mmm I dunno... `HiddenFromShowQueries` suggests that it refers strictly to the output of the `SHOW QUERIES` command. The fact that, as a consequence, that means that one also can't cancel those queries I don't know if it is intended or not. Whether or not hiding anything from that report is a good idea is questionable, but I don't particularly care. I guess you can make some arguments for schema changes, cause those are reported elsewhere.
Regardless, unless you have good reason to do so, I wouldn't conflate `HFSQ` with cancelation more than it is already. If some operation doesn't like being canceled, it should make sure it doesn't check for cancelation. Generally that's not feasible cause our contexts get canceled when the connection drops anyway, for example.
I'd remove this test. 
</blockquote></details>

Ah, good point. Removed the check.

---

*[pkg/sql/conn_executor_exec.go, line 124 at r5](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23399#-L70LSdw09j8-l310DtA:-L70n-OE13rryUlODAMm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3583fe78345154e27831db66c7e8e0192e1507c/pkg/sql/conn_executor_exec.go#L124)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: I think this comment will leave readers with a blank stare. One thing that would help I think would be moving it a line down to make it clear that it applies to the channel read. (stopping the timer would be a good idea regardless of whatever race considerations).

As the code is written, the reading has a simpler explanation - it avoids a data race on `queryTimedOut`, which is in itself inadmissible regardless of further considerations about other consequences.  I would replace the comment with `// Block for the timer callback to avoid a data race on queryTimedOut`. That would be sufficient for putting people that want to change this code en garde to reason through the consequences of races.
</blockquote></details>

Done.

---

*[pkg/sql/set_var.go, line 215 at r5](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23399#-L70PNJJX1ZRUykLbhrr:-L70n8LDCRYS-6oT0aHk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3583fe78345154e27831db66c7e8e0192e1507c/pkg/sql/set_var.go#L215)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Well, I think we should also accept a string that can be parsed as a `DInterval` (see tree.ParseDInterval()`). Otherwise, how is one supposed to actually pass a `DInterval` from a query - you'd have to use an explicit cast?
Please add a test for the string version.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23399)*

**Pull request merged**
