### PR TITLE
roachtest: use backup cloud to set CompatibleClouds

### PR DESCRIPTION
**Pull request by dt**
Release note: none.
Epic: none.

### CODE REVIEW

**Review by srosenberg — APPROVED** [review]
Thanks, this should finally fix cluster_creation errors of the form [1].

:lgtm:

[1] https://github.com/cockroachdb/cockroach/issues/112176#issuecomment-1849088912

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115997#-:-NlKeT2_4HgaL59G5tnJ:b-7cl7at)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @msbutler, and @renatolabs)

**Review by msbutler — APPROVED** [review]
Thanks for doing this!

**Review by herkolategan — APPROVED** [review]

**Comment by dt** [comment]
TFTRs!

bors r+

**Comment by RaduBerinde** [comment]
blathers backport 23.2

**Comment by RaduBerinde** [comment]
blathers backport 23.1

**Pull request merged**
