### PR TITLE
sql: grant CONNECT to PUBLIC by default on DATABASE creation 

### PR DESCRIPTION
**Pull request by otan**
Will handle migration in a following PR.

Refs #70098

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
the change looks good overall! i just have one question about where the "defaults" are set

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72595#-:-Mo9f88Z-wfngkNtCpdd:bi8v2z7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @otan, and @RichardJCai)

___
*[pkg/server/admin_test.go, line 330 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72595#-Mo9e8I3APXGGSvY_vom:-Mo9e8I473P4QosFYYPw:bxzx5jh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f148c11553df976d507da8e39c7a2ad5dd944a51/pkg/server/admin_test.go#L330)):*
> ```Go
> 	}
> 	// Test needs to revoke CONNECT on the public database to be meaningful.
> 	if _, err := db.Exec(fmt.Sprintf("REVOKE CONNECT ON DATABASE %s FROM public", testdb)); err != nil {
> ```

just for my understanding, what happens to the test if we don't REVOKE this here?
___
*[pkg/sql/catalog/descpb/privilege.go, line 167 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72595#-Mo9eEJI8nCB0WSR9rtg:-Mo9eEJI8nCB0WSR9rth:bnvckmb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f148c11553df976d507da8e39c7a2ad5dd944a51/pkg/sql/catalog/descpb/privilege.go#L167)):*
how does this part interact with the new `alter default privileges` work? specifically, it seems like it doesn't implement the last sentence from this

> PostgreSQL grants privileges on some types of objects to PUBLIC by default when the objects are created. ... the default privileges granted to PUBLIC are as follows: CONNECT and TEMPORARY (create temporary tables) privileges for databases ... Also, these default privilege settings can be overridden using the ALTER DEFAULT PRIVILEGES command.

https://www.postgresql.org/docs/13/ddl-priv.html

do we instead need to adjust the "default" default privs, as was done here: https://github.com/cockroachdb/cockroach/pull/68500 cc @richardjcai can probably answer this.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72595)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @rafiss, and @RichardJCai)

___
*[pkg/server/admin_test.go, line 330 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72595#-Mo9e8I3APXGGSvY_vom:-MoAPuLD84uXdzXeWgLL:bnzosde) ([raw file](https://github.com/cockroachdb/cockroach/blob/f148c11553df976d507da8e39c7a2ad5dd944a51/pkg/server/admin_test.go#L330)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

just for my understanding, what happens to the test if we don't REVOKE this here?
</blockquote></details>

the test relies on giving specific users `CONNECT` privilleges. not useful if it's on PUBLIC.
___
*[pkg/sql/catalog/descpb/privilege.go, line 167 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72595#-Mo9eEJI8nCB0WSR9rtg:-MoAQ3yH8Hp-xnd_Aqa2:b-xpkcnt) ([raw file](https://github.com/cockroachdb/cockroach/blob/f148c11553df976d507da8e39c7a2ad5dd944a51/pkg/sql/catalog/descpb/privilege.go#L167)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

how does this part interact with the new `alter default privileges` work? specifically, it seems like it doesn't implement the last sentence from this

> PostgreSQL grants privileges on some types of objects to PUBLIC by default when the objects are created. ... the default privileges granted to PUBLIC are as follows: CONNECT and TEMPORARY (create temporary tables) privileges for databases ... Also, these default privilege settings can be overridden using the ALTER DEFAULT PRIVILEGES command.

https://www.postgresql.org/docs/13/ddl-priv.html

do we instead need to adjust the "default" default privs, as was done here: https://github.com/cockroachdb/cockroach/pull/68500 cc @richardjcai can probably answer this.
</blockquote></details>

ALTER DEFAULT PRIVILEGES doesn't really work for connect as well.

**Comment by otan** [comment]
___
*[pkg/sql/catalog/descpb/privilege.go, line 167 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72595#-Mo9eEJI8nCB0WSR9rtg:-MoAQO1X8yei9PpCTYrP:b-gflc8w) ([raw file](https://github.com/cockroachdb/cockroach/blob/f148c11553df976d507da8e39c7a2ad5dd944a51/pkg/sql/catalog/descpb/privilege.go#L167)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

ALTER DEFAULT PRIVILEGES doesn't really work for connect as well.
</blockquote></details>

(i don't think there's an interaction here)

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72595)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @rafiss)

___
*[pkg/sql/catalog/descpb/privilege.go, line 167 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72595#-Mo9eEJI8nCB0WSR9rtg:-MoAYDmmAN54781-AEnu:bh9gjgb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f148c11553df976d507da8e39c7a2ad5dd944a51/pkg/sql/catalog/descpb/privilege.go#L167)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

(i don't think there's an interaction here)
</blockquote></details>

The function name for the previous one became quite misleading after Default Privileges were introduced.
NewDefaultPrivilegeDescriptor doesn't actually relate to "default privileges" but rather it is the default for regular privileges  :sweat: 

Can anyone think of a better name for it? NewBasePrivilegeDescriptor?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72595)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @rafiss)

___
*[pkg/sql/catalog/descpb/privilege.go, line 167 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72595#-Mo9eEJI8nCB0WSR9rtg:-MoAZR682sZEsvD7aST6:b-vam0g0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f148c11553df976d507da8e39c7a2ad5dd944a51/pkg/sql/catalog/descpb/privilege.go#L167)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

The function name for the previous one became quite misleading after Default Privileges were introduced.
NewDefaultPrivilegeDescriptor doesn't actually relate to "default privileges" but rather it is the default for regular privileges  :sweat: 

Can anyone think of a better name for it? NewBasePrivilegeDescriptor? 
</blockquote></details>

`NewInitialPrivilegeDescriptor`?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72595)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @rafiss)

___
*[pkg/sql/catalog/descpb/privilege.go, line 167 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72595#-Mo9eEJI8nCB0WSR9rtg:-MoAZcmq75sx5tPSKd-G:bpc0rfr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f148c11553df976d507da8e39c7a2ad5dd944a51/pkg/sql/catalog/descpb/privilege.go#L167)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

`NewInitialPrivilegeDescriptor`?
</blockquote></details>

Wait ... `NewPrivilegeDescriptor`?

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72595)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @otan, @rafiss, and @RichardJCai)

___
*[pkg/sql/catalog/descpb/privilege.go, line 167 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72595#-Mo9eEJI8nCB0WSR9rtg:-MoAbKUt1BaFeSYBnjIa:b-yfpdv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f148c11553df976d507da8e39c7a2ad5dd944a51/pkg/sql/catalog/descpb/privilege.go#L167)):*
> ALTER DEFAULT PRIVILEGES doesn't really work for connect as well.

ah OK, didn't realize that.

> Can anyone think of a better name for it?

yeah `NewPrivilegeDescriptor` seems like it'd be the go-conventional way to name a constructor function


anyway, the PR lgtm but renaming now sounds like a good idea!

**Comment by rafiss** [comment]
oh one thing i noticed in all the tests is that it seems that postgres doesn't really have a way of showing which privileges `PUBLIC` has. does PG just hide that when doing `\d` and `\l` and such?

**Comment by otan** [comment]
i guess postgres only shows the "explicit" privileges for a user/role?

**Comment by rafiss** [comment]
https://dba.stackexchange.com/questions/194335/in-postgresql-how-do-i-show-the-database-privileges-granted-to-public-in-postgr

very strange! seems like you can't see this using those `\` commands. but they are in `information_schema.role_table_grants` and `information_schema.usage_privileges` and such.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72595)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @rafiss)

___
*[pkg/sql/catalog/descpb/privilege.go, line 167 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72595#-Mo9eEJI8nCB0WSR9rtg:-MoAZkrZ33bq1l8WoUQk:boobsqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f148c11553df976d507da8e39c7a2ad5dd944a51/pkg/sql/catalog/descpb/privilege.go#L167)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

> ALTER DEFAULT PRIVILEGES doesn't really work for connect as well.
ah OK, didn't realize that.

> Can anyone think of a better name for it?
yeah `NewPrivilegeDescriptor` seems like it'd be the go-conventional way to name a constructor function


anyway, the PR lgtm but renaming now sounds like a good idea!
</blockquote></details>

NewPrivilegeDescriptor is already a thing. These constructor names could use some reworking.

**Comment by otan** [comment]
i've named it `NewBasePrivilegeDescriptor` for now.

bors r=rafiss

**Comment by otan** [comment]
not me

bors r=rafiss

**Pull request merged**
