### PR TITLE
vecindex: implement C-SPANN search

### PR DESCRIPTION
**Pull request by andy-kimball**
Add the VectorIndex class, which will implement the C-SPANN algorithm, which adapts Microsoft’s SPANN and SPFresh algorithms to work well with CockroachDB’s unique distributed architecture. This PR implements K-means tree search with a test implementation of bottom-up tree construction. Later PR's will include code to incrementally build the tree.

Epic: CRDB-42943

Release note: None

### CODE REVIEW

**Review by DrewKimball — COMMENTED** [review]
> Reviewed 10 of 12 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135004)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @mw5h)

___
*[`pkg/sql/vecindex/vector_index.go` line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBXV_ve-Gu4jhaCR7PI:-OBXV-Hn7tm1PI785tJ3:byxatsq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eba21b4ba067da763f5a0c840e485db2e51c2d1/pkg/sql/vecindex/vector_index.go#L58)):*
> ```Go
> 
> // SearchOptions specifies options for searching the vector index.
> type SearchOptions struct {
> ```

Can you explain more about the difference between `SearchOptions` and `VectorIndexOptions`? It's not obvious to me when to use one over the other for searching, since they both claim to be for that purpose. Does one override the other?
___
*[`pkg/sql/vecindex/vector_index.go` line 68 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBXUmckAsumV5QUibQv:-OBXUmcl9ZyK9z8j81W0:b90l7lk) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eba21b4ba067da763f5a0c840e485db2e51c2d1/pkg/sql/vecindex/vector_index.go#L68)):*
> ```Go
> 	SkipRerank bool
> 	// ReturnVectors specifies whether to return the original full-size vectors
> 	// are returned in search results.
> ```

[nit] This comment is off.
___
*[`pkg/sql/vecindex/vector_index.go` line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBXb5ZiC4Z4hcNS2hl_:-OBXb5ZiC4Z4hcNS2hla:blrlbf3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eba21b4ba067da763f5a0c840e485db2e51c2d1/pkg/sql/vecindex/vector_index.go#L152)):*
> ```Go
> func (vi *VectorIndex) CreateRoot(ctx context.Context, txn vecstore.Txn) error {
> 	// Use the UnQuantizer because vectors in the root are not quantized.
> 	dims := vi.quantizer.GetRandomDims()
> ```

Shouldn't this be using `vi.rootQuantizer`?
___
*[`pkg/sql/vecindex/vector_index.go` line 243 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBXs0sg1moo_b-CVT7e:-OBXs0shC47aeJvK9o09:balmv2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eba21b4ba067da763f5a0c840e485db2e51c2d1/pkg/sql/vecindex/vector_index.go#L243)):*
> ```Go
> 			// Compute the z-score of the candidate list.
> 			// TODO(andyk): Track z-score stats.
> 			zscore = 0
> ```

This will be the z-score of the query vector WRT the current list of candidates, is that right?
___
*[`pkg/sql/vecindex/vector_index.go` line 258 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBXl9yR8bgcIkz9_2W1:-OBXl9yR8bgcIkz9_2W2:b-tesmi6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eba21b4ba067da763f5a0c840e485db2e51c2d1/pkg/sql/vecindex/vector_index.go#L258)):*
> ```Go
> 
> 			results = vi.pruneDuplicates(results)
> 			if !searchCtx.Options.SkipRerank || searchCtx.Options.ReturnVectors {
> ```

This is only valid for the leaf level, right? Should we assert that we're actually at that level?
___
*[`pkg/sql/vecindex/vector_index.go` line 288 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBXt4AS3XWTfonT9qLD:-OBXt4AS3XWTfonT9qLE:b-lpfgaj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eba21b4ba067da763f5a0c840e485db2e51c2d1/pkg/sql/vecindex/vector_index.go#L288)):*
> ```Go
> 				// Use progressively smaller beam size for higher levels, since
> 				// each contains exponentially fewer partitions.
> 				tempBeamSize /= math.Pow(2, float64(searchLevel-(vecstore.LeafLevel+1)))
> ```

Should we impose the min and max beam size after this adjustment?
___
*[`pkg/sql/vecindex/vector_index.go` line 320 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBYXj7Q26E_t29Sqgs-:-OBYXj7Q26E_t29Sqgs0:b-7rgl6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eba21b4ba067da763f5a0c840e485db2e51c2d1/pkg/sql/vecindex/vector_index.go#L320)):*
> ```Go
> 
> 		_, err = vi.searchChildPartitions(searchCtx, &subSearchSet, searchCtx.tempKeys)
> 		if errors.Is(err, vecstore.ErrPartitionNotFound) {
> ```

I'm now questioning the reason for having a "partition not found error" at all. Since the fact that the root level is cached seems to be (mostly) a detail of the store implementation, should we also make retrying an internal implementation detail? Find if it's not addressed here.
___
*[`pkg/sql/vecindex/vector_index.go` line 410 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBYYtfq5N5O1GOeH67X:-OBYYtfq5N5O1GOeH67Y:bw526rn) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eba21b4ba067da763f5a0c840e485db2e51c2d1/pkg/sql/vecindex/vector_index.go#L410)):*
> ```Go
> 	if searchCtx.Level == vecstore.LeafLevel {
> 		// Leaf vectors haven't been randomized, so compare with the original query
> 		// vector if available, or un-randomize the randomized vector.
> ```

Under what circumstances would the original vector not be available?
___
*[`pkg/util/vector/vector_set.go` line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBY_sBh-e_PxxJ_YiOD:-OBY_sBi8QgVgHGTFwoO:b-7r79tb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eba21b4ba067da763f5a0c840e485db2e51c2d1/pkg/util/vector/vector_set.go#L53)):*
> ```Go
> //
> //gcassert:inline
> func (vs *Set) At(offset int) T {
> ```

[nit] It might be worth making a note that the vector returned here can be invalidated if the `Set` is mutated.
___
*[`pkg/util/vector/vector_set.go` line 114 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBYee665JhzvYo2fImm:-OBYee665JhzvYo2fImn:b-mkf0or) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eba21b4ba067da763f5a0c840e485db2e51c2d1/pkg/util/vector/vector_set.go#L114)):*
> ```Go
> func (vs *Set) Clear() {
> 	vs.Data = vs.Data[:0]
> 	vs.Count = 0
> ```

Can we trash the slice for test builds?
___
*[`pkg/sql/vecindex/testdata/search.ddt` line 105 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBYcBDMEfyw_OZcLgTy:-OBYcBDMEfyw_OZcLgTz:b-59sog7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eba21b4ba067da763f5a0c840e485db2e51c2d1/pkg/sql/vecindex/testdata/search.ddt#L105)):*
> ```
> # ----------
> # Construct new index with duplicate vectors. This can happen when a vector is
> # updated in the primary index, but it cannot be found in the secondary index.
> ```

I might have missed where it's done, but could we have a test with two different primary keys that have the same vector? If I search for that vector requesting 2 results, then I'd expect to get back both primary keys.
___
*[`pkg/sql/vecindex/vector_index_test.go` line 283 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBYdgJl2tQokgh384GN:-OBYdgJl2tQokgh384GO:b-x4lrr3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eba21b4ba067da763f5a0c840e485db2e51c2d1/pkg/sql/vecindex/vector_index_test.go#L283)):*
> ```Go
> // TODO(andyk): Use the incremental algorithm instead, once it's ready. This
> // alternate implementation is useful for testing and benchmarking. How much
> // more accurate is it than the incremental version?
> ```

How hard do you think it would be to make this work for a bulk index creation in production?

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135004)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mw5h)

___
*[`pkg/sql/vecindex/vector_index.go` line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBXV_ve-Gu4jhaCR7PI:-OB_oLUa3WMHK2_Cn1ja:b-gh7ywo) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eba21b4ba067da763f5a0c840e485db2e51c2d1/pkg/sql/vecindex/vector_index.go#L58)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Can you explain more about the difference between `SearchOptions` and `VectorIndexOptions`? It's not obvious to me when to use one over the other for searching, since they both claim to be for that purpose. Does one override the other?
</blockquote></details>

`VectorIndexOptions` applies to the index as a whole, whereas `SearchOptions` applies to an individual search. Any `SearchOptions` that are specified will override those in `VectorIndexOptions` (right now only BaseBeamSize is in both). I've updated the comments to make this more clear.
___
*[`pkg/sql/vecindex/vector_index.go` line 68 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBXUmckAsumV5QUibQv:-OB_rQKd9RU321JK37ih:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eba21b4ba067da763f5a0c840e485db2e51c2d1/pkg/sql/vecindex/vector_index.go#L68)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] This comment is off.
</blockquote></details>

Done.
___
*[`pkg/sql/vecindex/vector_index.go` line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBXb5ZiC4Z4hcNS2hl_:-OB_riPR3PVJGGkN85q1:b-xdjloz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eba21b4ba067da763f5a0c840e485db2e51c2d1/pkg/sql/vecindex/vector_index.go#L152)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Shouldn't this be using `vi.rootQuantizer`?
</blockquote></details>

The root quantizer should always be set up with the same number of randomized dims as the quantizer used to initialize the vector index, so it shouldn't matter. But I agree that it's clearer if we use rootQuantizer here. Fixed.
___
*[`pkg/sql/vecindex/vector_index.go` line 243 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBXs0sg1moo_b-CVT7e:-OB_tzNJ3Wl8SpeJtFYq:b-kkqykb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eba21b4ba067da763f5a0c840e485db2e51c2d1/pkg/sql/vecindex/vector_index.go#L243)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

This will be the z-score of the query vector WRT the current list of candidates, is that right?
</blockquote></details>

It's the Z-score of the list of candidate results contained in `results`. The Z-score compares the "spread" of the list with the average spread from past search operations at the same level. The Z-score is only indirectly about the query vector, since it's what we used to generate the candidate results.
___
*[`pkg/sql/vecindex/vector_index.go` line 258 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBXl9yR8bgcIkz9_2W1:-OB_ugHJCqhSvDnD-My3:bxc2npu) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eba21b4ba067da763f5a0c840e485db2e51c2d1/pkg/sql/vecindex/vector_index.go#L258)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

This is only valid for the leaf level, right? Should we assert that we're actually at that level?
</blockquote></details>

It can be other levels as well, in the case of Insert operations. We need to be able to insert centroid vectors into intermediate levels.
___
*[`pkg/sql/vecindex/vector_index.go` line 288 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBXt4AS3XWTfonT9qLD:-OB_uuJL8W5hTPmepRu5:b8qx0eg) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eba21b4ba067da763f5a0c840e485db2e51c2d1/pkg/sql/vecindex/vector_index.go#L288)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Should we impose the min and max beam size after this adjustment?
</blockquote></details>

My intent was to have the min/max beam sizes be increasingly smaller the closer to the root we are in the search. Perhaps further testing will show that it's better to use the same min/max across all levels, but I'd want to see those results before changing something like this.
___
*[`pkg/sql/vecindex/vector_index.go` line 320 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBYXj7Q26E_t29Sqgs-:-OB_vb-f5G6ZI92nuIl-:b-7l811m) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eba21b4ba067da763f5a0c840e485db2e51c2d1/pkg/sql/vecindex/vector_index.go#L320)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I'm now questioning the reason for having a "partition not found error" at all. Since the fact that the root level is cached seems to be (mostly) a detail of the store implementation, should we also make retrying an internal implementation detail? Find if it's not addressed here.
</blockquote></details>

The problem is that the Store doesn't have enough context to restart the search. The "partition not found" error might happen multiple levels below the root, deep down in a search. The entire search needs to be restarted from the "fresh" root.
___
*[`pkg/sql/vecindex/vector_index.go` line 410 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBYYtfq5N5O1GOeH67X:-OB_vylyEtUc6ixMvn94:bjxcsed) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eba21b4ba067da763f5a0c840e485db2e51c2d1/pkg/sql/vecindex/vector_index.go#L410)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Under what circumstances would the original vector not be available?
</blockquote></details>

In cases where we need to move vectors from one partition to another during split/merge. In those cases, all we have is the randomized vector.
___
*[`pkg/util/vector/vector_set.go` line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBY_sBh-e_PxxJ_YiOD:-OB_zGIw2tDd6jRRUpx8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eba21b4ba067da763f5a0c840e485db2e51c2d1/pkg/util/vector/vector_set.go#L53)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] It might be worth making a note that the vector returned here can be invalidated if the `Set` is mutated.
</blockquote></details>

Done.
___
*[`pkg/util/vector/vector_set.go` line 114 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBYee665JhzvYo2fImm:-OB_zlF49uh27mjYYOqU:b-g0k9qz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eba21b4ba067da763f5a0c840e485db2e51c2d1/pkg/util/vector/vector_set.go#L114)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Can we trash the slice for test builds?
</blockquote></details>

Done, I also added trashing to other relevant operations.
___
*[`pkg/sql/vecindex/testdata/search.ddt` line 105 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBYcBDMEfyw_OZcLgTy:-OBa36vj4RXLkTfwpOnd:b-fznogt) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eba21b4ba067da763f5a0c840e485db2e51c2d1/pkg/sql/vecindex/testdata/search.ddt#L105)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I might have missed where it's done, but could we have a test with two different primary keys that have the same vector? If I search for that vector requesting 2 results, then I'd expect to get back both primary keys.
</blockquote></details>

Good idea, done.
___
*[`pkg/sql/vecindex/vector_index_test.go` line 283 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBYdgJl2tQokgh384GN:-OBa-hGOEcxY-I84MDhA:bwopfl) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eba21b4ba067da763f5a0c840e485db2e51c2d1/pkg/sql/vecindex/vector_index_test.go#L283)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

How hard do you think it would be to make this work for a bulk index creation in production?
</blockquote></details>

I suspect the biggest issue will be performance. K-means is O(Nkid), where N=# vectors, k=# partitions, i=# iterations, d=# dimensions. My testing shows that this `buildTree` implementation is markedly slower than the incremental K-means algorithm (where k=2). It's also not yet clear whether the resulting tree is actually more accurate. So I think we'd need to do more testing, analysis, and perf work before we'd want to use it for bulk index creation.

**Review by mw5h — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, 4 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135004)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @DrewKimball)

___
*[`pkg/sql/vecindex/vector_index.go` line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBazMttAoOGyK06_hVQ:-OBazMttAoOGyK06_hVR:bta2aod) ([raw file](https://github.com/cockroachdb/cockroach/blob/545b4d7019a171ffef53b88ba1fb180a06d76671/pkg/sql/vecindex/vector_index.go#L79)):*
> ```Go
> 	Workspace internal.Workspace
> 	Txn       vecstore.Txn
> 	Level     vecstore.Level
> ```

I found this confusing in the context of this patch. You set it to vecstore.LeafLevel and then don't touch it again, but you also make direct references to LeafLevel, suggesting that this is supposed to have different semantics. It might be clearer to specify what those semantics are.
___
*[`pkg/sql/vecindex/vector_index.go` line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBat2ZU-FGDBjTWPpoD:-OBat2ZU-FGDBjTWPpoE:b-7arr6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/545b4d7019a171ffef53b88ba1fb180a06d76671/pkg/sql/vecindex/vector_index.go#L88)):*
> ```Go
> 	// Randomized is the original vector after being processed by the quantizer's
> 	// RandomizeVector method. It can have a different number of dimensions than
> 	// Original and different values in those dimensions.
> ```

It might be worth noting that RabbitQ and Unquantizer don't actually randomize to a different number of dimensions.
___
*[`pkg/sql/vecindex/vector_index.go` line 439 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBb1_LjDmBP8QogJeRN:-OBb1_LjDmBP8QogJeRO:bxo413h) ([raw file](https://github.com/cockroachdb/cockroach/blob/545b4d7019a171ffef53b88ba1fb180a06d76671/pkg/sql/vecindex/vector_index.go#L439)):*
> ```Go
> // the primary index, that candidate is removed from the list of candidates
> // that's returned.
> func (vi *VectorIndex) getRerankVectors(
> ```

How do we feel about pushing this join logic into the index? Is there precedent for that in CRDB? A few weeks ago, Drew and I talked briefly about using the TopK operator to do the rerank. You could imagine a dumber operator that just returns the PKs and leaves it to the optimizer / execution engine to do the join on PK, compute a virtual error column and sort on that.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135004)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mw5h)

___
*[`pkg/sql/vecindex/vector_index.go` line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBazMttAoOGyK06_hVQ:-OBbPuHl-UbDBHfmOf7O:b-o8cj3j) ([raw file](https://github.com/cockroachdb/cockroach/blob/545b4d7019a171ffef53b88ba1fb180a06d76671/pkg/sql/vecindex/vector_index.go#L79)):*
<details><summary><i>Previously, mw5h (Matt White) wrote…</i></summary><blockquote>

I found this confusing in the context of this patch. You set it to vecstore.LeafLevel and then don't touch it again, but you also make direct references to LeafLevel, suggesting that this is supposed to have different semantics. It might be clearer to specify what those semantics are.
</blockquote></details>

This can be set to a non-leaf level during insert and during splits/merges. I added this information to a comment.
___
*[`pkg/sql/vecindex/vector_index.go` line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBat2ZU-FGDBjTWPpoD:-OBbQf_e9A1pSJeZL95H:b-wq9rht) ([raw file](https://github.com/cockroachdb/cockroach/blob/545b4d7019a171ffef53b88ba1fb180a06d76671/pkg/sql/vecindex/vector_index.go#L88)):*
<details><summary><i>Previously, mw5h (Matt White) wrote…</i></summary><blockquote>

It might be worth noting that RabbitQ and Unquantizer don't actually randomize to a different number of dimensions.
</blockquote></details>

Actually, I expect our RaBitQ implementation to use a different number of dimensions. By using a [fast Hadamard transform](https://en.wikipedia.org/wiki/Fast_Walsh%E2%80%93Hadamard_transform), we can perform a random orthogonal transform in O(NlogN) time, rather than the O(N**2) time that general matrix multiplication requires. The matrix multiplication has already shown up as a problem on profiles, in particular during index builds. The downside to a FHT is that it requires us to expand dimensions to the next higher power of 2.
___
*[`pkg/sql/vecindex/vector_index.go` line 439 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBb1_LjDmBP8QogJeRN:-OBbSSP-0U7eShnZFlpI:b-hcn0x8) ([raw file](https://github.com/cockroachdb/cockroach/blob/545b4d7019a171ffef53b88ba1fb180a06d76671/pkg/sql/vecindex/vector_index.go#L439)):*
<details><summary><i>Previously, mw5h (Matt White) wrote…</i></summary><blockquote>

How do we feel about pushing this join logic into the index? Is there precedent for that in CRDB? A few weeks ago, Drew and I talked briefly about using the TopK operator to do the rerank. You could imagine a dumber operator that just returns the PKs and leaves it to the optimizer / execution engine to do the join on PK, compute a virtual error column and sort on that.
</blockquote></details>

I think it's a good optimization to explore for user queries. However, even if we did that, I think we'd still want this code for internal searches that we need to do for index inserts/splits/merges.

**Review by mw5h — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-:-OBbe_voCj_kfWQBKgfE:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135004)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained

___
*[`pkg/sql/vecindex/vector_index.go` line 258 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBXl9yR8bgcIkz9_2W1:-OBd0WMHARTdfcLiyojX:b4hrbir) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eba21b4ba067da763f5a0c840e485db2e51c2d1/pkg/sql/vecindex/vector_index.go#L258)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

It can be other levels as well, in the case of Insert operations. We need to be able to insert centroid vectors into intermediate levels.
</blockquote></details>

In that case, what happens during this re-ranking step for intermediate levels? There aren't any full vectors to fetch for the centroids.
___
*[`pkg/sql/vecindex/vector_index.go` line 320 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBYXj7Q26E_t29Sqgs-:-OBd0MUuASze5OWM3kZf:b-ot6kml) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eba21b4ba067da763f5a0c840e485db2e51c2d1/pkg/sql/vecindex/vector_index.go#L320)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

The problem is that the Store doesn't have enough context to restart the search. The "partition not found" error might happen multiple levels below the root, deep down in a search. The entire search needs to be restarted from the "fresh" root.
</blockquote></details>

I had thought that "partition not found" only happens in response to a stale root cache. When does that happen for other partitions?

**Comment by andy-kimball** [comment]
*[`pkg/sql/vecindex/vector_index.go` line 320 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBYXj7Q26E_t29Sqgs-:-OBd821s7VmwzZIxzDoW:b-60doaw) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eba21b4ba067da763f5a0c840e485db2e51c2d1/pkg/sql/vecindex/vector_index.go#L320)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I had thought that "partition not found" only happens in response to a stale root cache. When does that happen for other partitions?
</blockquote></details>

If the root is stale, then we don't know about it until we attempt to fetch one of its child partitions, which the Store wouldn't have enough context to detect. Above I said it could be multiple levels below the root, but thinking about it more, I think it should only happen in the level just below the root.

**Comment by andy-kimball** [comment]
*[`pkg/sql/vecindex/vector_index.go` line 258 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBXl9yR8bgcIkz9_2W1:-OBd7rcXDzNmvTA0q_Pa:b-1zkcrh) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eba21b4ba067da763f5a0c840e485db2e51c2d1/pkg/sql/vecindex/vector_index.go#L258)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

In that case, what happens during this re-ranking step for intermediate levels? There aren't any full vectors to fetch for the centroids.
</blockquote></details>

Yes, there are full vectors - we store them in the partition metadata record.

**Comment by andy-kimball** [comment]
*[`pkg/sql/vecindex/vector_index.go` line 320 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135004#-OBYXj7Q26E_t29Sqgs-:-OBdHWe67eHZ91s6YIlT:b-knzpe5) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eba21b4ba067da763f5a0c840e485db2e51c2d1/pkg/sql/vecindex/vector_index.go#L320)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

If the root is stale, then we don't know about it until we attempt to fetch one of its child partitions, which the Store wouldn't have enough context to detect. Above I said it could be multiple levels below the root, but thinking about it more, I think it should only happen in the level just below the root.
</blockquote></details>

One other point: I *do* expect the Store to automatically refresh the root cache when it comes across a "partition not found" error. The vector index will retry and this time expect to not get an error.

**Pull request merged**
