### PR TITLE
storage,kv: make transaction deadline exceeded errors retriable

### PR DESCRIPTION
**Pull request by andreimatei**
Before this patch, they were opaque TransactionStatusErrors.
The belief is that we should only be seeing such errors when a
transaction is pushed by minutes. Shockingly, this seems to hapen enough
in our tests, for example as described here: #18684 (comment)

This patch marks the error as retriable, since it technically is.

This patch also changes the semantics of the
EndTransactionRequest.Deadline field to make it exclusive so that it
matches the nature of SQL leases. No migration needed.

Touches #18684

Release note (sql change): "transaction deadline exceeded" errors are
now returned to the client with a retriable code.

### CODE REVIEW

**Comment by andreimatei** [comment]
cc @vivekmenezes

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 20 of 20 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35284)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/roachpb/errors.proto, line 215 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35284#-LZqIZmYCo1V633USl2R:-LZqIZmYCo1V633USl2S:bvtpdmz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b9807199b9da55f6513b0483016b789490ba20a/pkg/roachpb/errors.proto#L215)):*
> ```protobuf
>   // An asynchronous write was observed to have failed.
>   RETRY_ASYNC_WRITE_FAILURE = 5;
> 	// The transaction exceeded its deadline.
> ```

tab instead of space
___
*[pkg/storage/batcheval/cmd_end_transaction.go, line 278 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35284#-LZqJBW-05At7e4MfL0H:-LZqJBW-05At7e4MfL0I:b-f0gevz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b9807199b9da55f6513b0483016b789490ba20a/pkg/storage/batcheval/cmd_end_transaction.go#L278)):*
> ```Go
> 		}
> 
> 		if IsEndTransactionExceedingDeadline(reply.Txn.Timestamp, *args) {
> ```

Shouldn't we delete this?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35284)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/roachpb/errors.proto, line 215 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35284#-LZqIZmYCo1V633USl2R:-LZqTGpXB9lzYhrYImqH:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b9807199b9da55f6513b0483016b789490ba20a/pkg/roachpb/errors.proto#L215)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

tab instead of space
</blockquote></details>

done
___
*[pkg/storage/batcheval/cmd_end_transaction.go, line 278 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35284#-LZqJBW-05At7e4MfL0H:-LZqTPUtE0VtkHrYR3gY:b-ozuwb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b9807199b9da55f6513b0483016b789490ba20a/pkg/storage/batcheval/cmd_end_transaction.go#L278)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Shouldn't we delete this?
</blockquote></details>

yes, it was unreachable, thanks.

**Comment by jordanlewis** [comment]
Heroes!

**Review by vivekmenezes — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35284)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/txn_coord_sender.go, line 617 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35284#-L_JVPPK0UINcLBv0y8l:-L_JVPPK0UINcLBv0y8m:b-kdy4t) ([raw file](https://github.com/cockroachdb/cockroach/blob/3612e003951f8177d65c27a4fca2ade0225e6940/pkg/kv/txn_coord_sender.go#L617)):*
> ```Go
> 	deadline := ba.Requests[0].GetEndTransaction().Deadline
> 	txn := tc.mu.txn
> 	if deadline != nil && deadline.Less(txn.Timestamp) {
> ```

This should be !txn.Timestamp.Less(deadline). The deadline is not included as a valid timestamp.
___
*[pkg/kv/txn_interceptor_committer.go, line 96 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35284#-L_JVoMn5Dh01iXyhtVZ:-L_JVoMn5Dh01iXyhtV_:bb7od0r) ([raw file](https://github.com/cockroachdb/cockroach/blob/3612e003951f8177d65c27a4fca2ade0225e6940/pkg/kv/txn_interceptor_committer.go#L96)):*
> ```Go
> 	// Check if the (read-only) txn was pushed above its deadline.
> 	deadline := et.Deadline
> 	if deadline != nil && deadline.Less(br.Txn.Timestamp) {
> ```

same
___
*[pkg/kv/txn_interceptor_committer.go, line 106 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35284#-L_JVpWY44J0fTzHMBZb:-L_JVpWY44J0fTzHMBZc:buh3fmo) ([raw file](https://github.com/cockroachdb/cockroach/blob/3612e003951f8177d65c27a4fca2ade0225e6940/pkg/kv/txn_interceptor_committer.go#L106)):*
> ```Go
> 		txnCpy := txn.Clone()
> 		return nil, roachpb.NewErrorWithTxn(
> 			roachpb.NewTransactionRetryError(roachpb.RETRY_COMMIT_DEADLINE_EXCEEDED, extraMsg), &txnCpy)
> ```

probably makes sense to abstract this out as a function. It's repeated here.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35284)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @nvanbenschoten, and @vivekmenezes)

___
*[pkg/kv/txn_coord_sender.go, line 617 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35284#-L_JVPPK0UINcLBv0y8l:-L_Ul_oc39Rs1gSY2T7a:b-gaxh7u) ([raw file](https://github.com/cockroachdb/cockroach/blob/3612e003951f8177d65c27a4fca2ade0225e6940/pkg/kv/txn_coord_sender.go#L617)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

This should be !txn.Timestamp.Less(deadline). The deadline is not included as a valid timestamp.
</blockquote></details>

well that's not how `EndTransactionRequest` is documented and not what the server enforces:
https://github.com/cockroachdb/cockroach/blob/38bb1e7905b89f911bd74be4f5830217ffb7b343/pkg/storage/batcheval/cmd_end_transaction.go#L378

But indeed the leasing code documents to be returning exclusive deadlines.
https://github.com/cockroachdb/cockroach/blob/38bb1e7905b89f911bd74be4f5830217ffb7b343/pkg/sql/lease.go#L1362

So... which one should it be? I'm happy to change the server-side enforcement too.

**Review by vivekmenezes — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35284)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/txn_coord_sender.go, line 617 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35284#-L_JVPPK0UINcLBv0y8l:-L_hQKU3E5clJ2etnPNq:b1e3ld0) ([raw file](https://github.com/cockroachdb/cockroach/blob/3612e003951f8177d65c27a4fca2ade0225e6940/pkg/kv/txn_coord_sender.go#L617)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

well that's not how `EndTransactionRequest` is documented and not what the server enforces:
https://github.com/cockroachdb/cockroach/blob/38bb1e7905b89f911bd74be4f5830217ffb7b343/pkg/storage/batcheval/cmd_end_transaction.go#L378

But indeed the leasing code documents to be returning exclusive deadlines.
https://github.com/cockroachdb/cockroach/blob/38bb1e7905b89f911bd74be4f5830217ffb7b343/pkg/sql/lease.go#L1362

So... which one should it be? I'm happy to change the server-side enforcement too.
</blockquote></details>

The deadline is not an acceptable timestamp. Let's fix it to accommodate that concept. Thanks!

**Comment by vivekmenezes** [comment]
@andreimatei wanna update this PR and get it into a mergeable state. Would love to see it get into 19.1

**Comment by andreimatei** [comment]
Don't know if I can do that today or tomorrow.
Feel free to take it over if you have the time.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35284)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @vivekmenezes)

___
*[pkg/kv/txn_coord_sender.go, line 617 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35284#-L_JVPPK0UINcLBv0y8l:-LaBoWicCgpOYsrdwKrz:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3612e003951f8177d65c27a4fca2ade0225e6940/pkg/kv/txn_coord_sender.go#L617)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

The deadline is not an acceptable timestamp. Let's fix it to accommodate that concept. Thanks!
</blockquote></details>

done
___
*[pkg/kv/txn_interceptor_committer.go, line 96 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35284#-L_JVoMn5Dh01iXyhtVZ:-LaBof7X5YG66txZGGCF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3612e003951f8177d65c27a4fca2ade0225e6940/pkg/kv/txn_interceptor_committer.go#L96)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[pkg/kv/txn_interceptor_committer.go, line 106 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35284#-L_JVpWY44J0fTzHMBZb:-LaBq84a8HwIhRklBXZb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3612e003951f8177d65c27a4fca2ade0225e6940/pkg/kv/txn_interceptor_committer.go#L106)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

probably makes sense to abstract this out as a function. It's repeated here.
</blockquote></details>

Done.

**Review by vivekmenezes — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35284)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @nvanbenschoten, and @vivekmenezes)

___
*[pkg/kv/txn_coord_sender.go, line 705 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35284#-LaDbUjc-onxK6BGOTya:-LaDbUjc-onxK6BGOTyb:b-al4k5a) ([raw file](https://github.com/cockroachdb/cockroach/blob/0762f0dbbdfa3630a2abc7f4fd34b21dc9a74353/pkg/kv/txn_coord_sender.go#L705)):*
> ```Go
> 		// txnCpy := txn.Clone()
> 		// pErr := roachpb.NewErrorWithTxn(
> 		//   roachpb.NewTransactionRetryError(roachpb.RETRY_COMMIT_DEADLINE_EXCEEDED, extraMsg), &txnCpy)
> ```

Nit: remove comments here and below
___
*[pkg/storage/batcheval/cmd_end_transaction.go, line 399 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35284#-LaDbN3QE5ESj4VMb-oh:-LaDbN3QE5ESj4VMb-oi:bxn3fw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/0762f0dbbdfa3630a2abc7f4fd34b21dc9a74353/pkg/storage/batcheval/cmd_end_transaction.go#L399)):*
> ```Go
> 			retry, reason = true, roachpb.RETRY_COMMIT_DEADLINE_EXCEEDED
> 		}
> 	}
> ```

I suppose you could use the common function here too.

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35284#-:-LaGTAyL47lGUnCQ6lVd:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @vivekmenezes)

___
*[pkg/kv/txn_coord_sender.go, line 705 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35284#-LaDbUjc-onxK6BGOTya:-LaGQ3rgB9MeVZqhkYyC:b40u0fl) ([raw file](https://github.com/cockroachdb/cockroach/blob/0762f0dbbdfa3630a2abc7f4fd34b21dc9a74353/pkg/kv/txn_coord_sender.go#L705)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Nit: remove comments here and below
</blockquote></details>

done. not a nit, thanks
___
*[pkg/storage/batcheval/cmd_end_transaction.go, line 399 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35284#-LaDbN3QE5ESj4VMb-oh:-LaGSw808TtYUWDc_8Vx:b6xe6jh) ([raw file](https://github.com/cockroachdb/cockroach/blob/0762f0dbbdfa3630a2abc7f4fd34b21dc9a74353/pkg/storage/batcheval/cmd_end_transaction.go#L399)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I suppose you could use the common function here too.
</blockquote></details>

not easily. Unfortunately on the server side most code (like here) deals with `errors`, and the transaction is attached to the error later.

**Pull request merged**
