### PR TITLE
kvserver: fix write below closedts bug 

### PR DESCRIPTION
**Pull request by andreimatei**
This patch fixes a bug in our closed timestamp management. This bug was
making it possible for a command to close a timestamp even though other
requests writing at lower timestamps are currently evaluating. The
problem was that we were assuming that, if a replica is proposing a new
lease, there can't be any requests in flight and every future write
evaluated on the range will wait for the new lease and the evaluate
above the lease start time. Based on that reasoning, the proposal buffer
was recording the lease start time as its assignedClosedTimestamp. This
was matching what it does for every write, where assignedClosedTimestamp
corresponds to the the closed timestamp carried by the command.

It turns out that the replica's reasoning was wrong. It is, in fact,
possible for writes to be evaluating on the range when the lease
acquisition is proposed. And these evaluations might be done at
timestamps below the would-be lease's start time. This happens when the
replica has already received a lease through a lease transfer. The
transfer must have applied after the previous lease expired and the
replica decided to start acquiring a new one.

This fixes one of the assertion failures seen in #62655.

Release note (bug fix): A bug leading to crashes with the message
"writing below closed ts" has been fixed.

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 5 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63672)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvserver/replica_closedts_test.go, line 417 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIj1_T5ZqH_j02UtR1:-MYIj1_T5ZqH_j02UtR2:b-asmxwn) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e94e1524d5424a514050d4653e298cbbcda9c/pkg/kv/kvserver/replica_closedts_test.go#L417)):*
> ```Go
> }
> 
> // Test that a lease proposal that gets rejected doesn't erroneously dictate the
> ```

Nice test! It's complex, but the way you wrote this makes it easy to follow.
___
*[pkg/kv/kvserver/replica_closedts_test.go, line 422 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIhbxT334aSZoVpSwz:-MYIhbxT334aSZoVpSx-:bxs5bac) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e94e1524d5424a514050d4653e298cbbcda9c/pkg/kv/kvserver/replica_closedts_test.go#L422)):*
> ```Go
> //
> // 1. A lease held by rep1 is getting close to its expiration.
> // 2. Rep1 begins the process of transferring its lease to rep2 with a start time of 100.
> ```

nit: wrap
___
*[pkg/kv/kvserver/replica_closedts_test.go, line 427 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIh_i26lq6VY6js5A0:-MYIh_i26lq6VY6js5A1:b-esf782) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e94e1524d5424a514050d4653e298cbbcda9c/pkg/kv/kvserver/replica_closedts_test.go#L427)):*
> ```Go
> //    lease acquisition is slow to propose.
> // 4. The lease transfer finally applies. Rep2 is the new leaseholder and bumps
> // 	  its tscache to 100.
> ```

nit: spacing is off here.
___
*[pkg/kv/kvserver/replica_closedts_test.go, line 429 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIhiTm8Cvxraq3yXHX:-MYIhiTnCjAtZm2o-YWd:bt4to6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e94e1524d5424a514050d4653e298cbbcda9c/pkg/kv/kvserver/replica_closedts_test.go#L429)):*
> ```Go
> // 	  its tscache to 100.
> // 5. Two writes start evaluating on rep2 under the new lease. They bump their
> //    write timestamp to 100.
> ```

101, right? Or 100,1 if we want to concern ourselves with logical ticks.
___
*[pkg/kv/kvserver/replica_closedts_test.go, line 448 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIhwusA_3XiR4N_ieV:-MYIhwusA_3XiR4N_ieW:b-kk2mwx) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e94e1524d5424a514050d4653e298cbbcda9c/pkg/kv/kvserver/replica_closedts_test.go#L448)):*
> ```Go
> // The test simulates the scenario and verifies that we don't crash with a
> // closed timestamp violation assertion. We avoid the violation because, in step
> // 6, the lease proposal doesn't bump the assignedClosedTimestamp.
> ```

Consider referencing the issue as well, to provide more context for those who seek it.
___
*[pkg/kv/kvserver/replica_closedts_test.go, line 472 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIi9kQ8EpbY8JyfS7H:-MYIi9kQ8EpbY8JyfS7I:bb690fd) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e94e1524d5424a514050d4653e298cbbcda9c/pkg/kv/kvserver/replica_closedts_test.go#L472)):*
> ```Go
> 	unblockWritesCh := make(chan struct{})
> 	var writeKey1, writeKey2 atomic.Value
> 	// Initialize the atomics do they get bound to a specific type.
> ```

"so"
___
*[pkg/kv/kvserver/replica_closedts_test.go, line 472 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIiDcD1eXOsH4oZo9U:-MYIiDcD1eXOsH4oZo9V:bv7jfxk) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e94e1524d5424a514050d4653e298cbbcda9c/pkg/kv/kvserver/replica_closedts_test.go#L472)):*
> ```Go
> 	unblockWritesCh := make(chan struct{})
> 	var writeKey1, writeKey2 atomic.Value
> 	// Initialize the atomics do they get bound to a specific type.
> ```

That's a neat idea.
___
*[pkg/kv/kvserver/replica_closedts_test.go, line 483 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIiQkMAIYL-s_AbuP3:-MYIiQkMAIYL-s_AbuP4:bhyysyj) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e94e1524d5424a514050d4653e298cbbcda9c/pkg/kv/kvserver/replica_closedts_test.go#L483)):*
> ```Go
> 			return
> 		}
> 		if atomic.LoadInt64(&trappedLeaseAcquisition) == 1 {
> ```

Make this an atomic compare and swap to avoid a race between two lease acquisitions. Or use a `sync.Once`.
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 736 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIf0R8-4-gYNB0cbAH:-MYIf0R8-4-gYNB0cbAI:b3vephg) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b20bef1da09475f349743886e2bcf80c97023c6/pkg/kv/kvserver/replica_proposal_buf.go#L736)):*
> ```Go
> 		// timestamps); in other words, assignedClosedTimestamp was not supposed to
> 		// have been incremented while requests with lower timestamps were
> 		// evaluating.
> ```

" and should have been used to bump the timestamp of any requests that began evaluating after it was bumped".
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 737 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIfDCC26UCfNC56wpp:-MYIfDCC26UCfNC56wpq:b-lbned4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b20bef1da09475f349743886e2bcf80c97023c6/pkg/kv/kvserver/replica_proposal_buf.go#L737)):*
> ```Go
> 		// have been incremented while requests with lower timestamps were
> 		// evaluating.
> 		if !b.assignedClosedTimestamp.LessEq(p.Request.WriteTimestamp()) &&
> ```

Aren't these first two conditions equal to `p.Request.WriteTimestamp().Less(b.assignedClosedTimestamp)`?
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 739 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIfOmF4ryKm55a29A4:-MYIfOmF4ryKm55a29A5:b-e2bxv6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b20bef1da09475f349743886e2bcf80c97023c6/pkg/kv/kvserver/replica_proposal_buf.go#L739)):*
> ```Go
> 		if !b.assignedClosedTimestamp.LessEq(p.Request.WriteTimestamp()) &&
> 			!b.assignedClosedTimestamp.IsEmpty() && p.Request.IsIntentWrite() {
> 			wts := p.Request.WriteTimestamp()
> ```

nit: pull this out before if you're going to assign it to a variable so that we can use it in the check.
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 633 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIgK8O21j_cQ6CHc8A:-MYIgK8O21j_cQ6CHc8B:b-ezed7o) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e94e1524d5424a514050d4653e298cbbcda9c/pkg/kv/kvserver/replica_proposal_buf.go#L633)):*
> ```Go
> 			}
> 		}
> 		if fn := b.p.testingFlushFilter(); fn != nil {
> ```

Do we need this? Don't we have the `submitProposalFilter` right above?
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 752 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIgZzI01Cjr4lhl3MB:-MYIgZzI01Cjr4lhl3MC:b34xhdn) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e94e1524d5424a514050d4653e298cbbcda9c/pkg/kv/kvserver/replica_proposal_buf.go#L752)):*
> ```Go
> 		// calling forwardClosedTimestampLocked). Bumping it to the lease start time
> 		// would (surprisingly?) be illegal: just because we're proposing a lease
> 		// starting at timestamp 100, doesn't mean we're sure to not evaluate
> ```

"to not be evaluating"?
___
*[pkg/kv/kvserver/replica_proposal_buf_test.go, line 204 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIfhfw30fUrx982ffU:-MYIfhfw30fUrx982ffV:b-1s84e) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b20bef1da09475f349743886e2bcf80c97023c6/pkg/kv/kvserver/replica_proposal_buf_test.go#L204)):*
> ```Go
> }
> 
> func (pc proposalCreator) newPutProposal(ts hlc.Timestamp) (*ProposalData, []byte) {
> ```

Do we need this change? We you planning on testing the new assertion?
___
*[pkg/kv/kvserver/replica_proposal_buf_test.go, line 768 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIh-We5a63losssytk:-MYIh-We5a63losssytl:b30esc2) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e94e1524d5424a514050d4653e298cbbcda9c/pkg/kv/kvserver/replica_proposal_buf_test.go#L768)):*
> ```Go
> 
> 		expClosed hlc.Timestamp
> 		// If not nil, b.assignedClosedTimestamp is checked against this.
> ```

Is it possible to make this mandatory and check it for each subtest?
___
*[pkg/kv/kvserver/replica_range_lease.go, line 1056 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIh9oJ8G4W0BrWQ8J8:-MYIh9oJ8G4W0BrWQ8J9:bl7kpul) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e94e1524d5424a514050d4653e298cbbcda9c/pkg/kv/kvserver/replica_range_lease.go#L1056)):*
> ```Go
> }
> 
> // TestingAcquireLease is redirectOnOrAcquireLease exposed for tests.
> ```

Can this live in `helpers_test.go`?
___
*[pkg/kv/kvserver/replica_range_lease.go, line 1281 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIh4xp-ndhoZwtHUfg:-MYIh4xp-ndhoZwtHUfh:b9hh00e) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e94e1524d5424a514050d4653e298cbbcda9c/pkg/kv/kvserver/replica_range_lease.go#L1281)):*
> ```Go
> 	if log.ExpensiveLogEnabled(ctx, 2) {
> 		log.Infof(ctx, "extending lease %s at %s", st.Lease, st.Now)
> 		debug.PrintStack()
> ```

I don't think you meant to keep this.
___
*[pkg/kv/kvserver/testing_knobs.go, line 26 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIg1JRDI64jgdxqE_T:-MYIg1JRDI64jgdxqE_U:bp0mmz) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e94e1524d5424a514050d4653e298cbbcda9c/pkg/kv/kvserver/testing_knobs.go#L26)):*
> ```Go
> )
> 
> // ProposalFLushFilter is the type of the TestingFlushFilter callback.
> ```

"FLush"

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63672)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_closedts_test.go, line 422 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIhbxT334aSZoVpSwz:-MYL5T5O-PrhZEU5yFQK:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e94e1524d5424a514050d4653e298cbbcda9c/pkg/kv/kvserver/replica_closedts_test.go#L422)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: wrap
</blockquote></details>

done
___
*[pkg/kv/kvserver/replica_closedts_test.go, line 427 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIh_i26lq6VY6js5A0:-MYL5Trc7EuSgb8G5G1C:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e94e1524d5424a514050d4653e298cbbcda9c/pkg/kv/kvserver/replica_closedts_test.go#L427)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: spacing is off here.
</blockquote></details>

done
___
*[pkg/kv/kvserver/replica_closedts_test.go, line 429 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIhiTm8Cvxraq3yXHX:-MYL5XffE8v5-xXw6Ekh:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e94e1524d5424a514050d4653e298cbbcda9c/pkg/kv/kvserver/replica_closedts_test.go#L429)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

101, right? Or 100,1 if we want to concern ourselves with logical ticks.
</blockquote></details>

done
___
*[pkg/kv/kvserver/replica_closedts_test.go, line 448 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIhwusA_3XiR4N_ieV:-MYL5egdCzvVwVDsAzP4:b-nkig9p) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e94e1524d5424a514050d4653e298cbbcda9c/pkg/kv/kvserver/replica_closedts_test.go#L448)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Consider referencing the issue as well, to provide more context for those who seek it.
</blockquote></details>

I think the issue is easily discoverable from the commit message. 
___
*[pkg/kv/kvserver/replica_closedts_test.go, line 472 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIi9kQ8EpbY8JyfS7H:-MYL621HDxPUS8Bey0kh:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e94e1524d5424a514050d4653e298cbbcda9c/pkg/kv/kvserver/replica_closedts_test.go#L472)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"so"
</blockquote></details>

done
___
*[pkg/kv/kvserver/replica_closedts_test.go, line 483 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIiQkMAIYL-s_AbuP3:-MYL6Ia0DEXBCkO2OAj_:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e94e1524d5424a514050d4653e298cbbcda9c/pkg/kv/kvserver/replica_closedts_test.go#L483)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Make this an atomic compare and swap to avoid a race between two lease acquisitions. Or use a `sync.Once`.
</blockquote></details>

done
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 736 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIf0R8-4-gYNB0cbAH:-MYLPtMw4Dwg-U6XQypw:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b20bef1da09475f349743886e2bcf80c97023c6/pkg/kv/kvserver/replica_proposal_buf.go#L736)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

" and should have been used to bump the timestamp of any requests that began evaluating after it was bumped".
</blockquote></details>

done
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 737 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIfDCC26UCfNC56wpp:-MYLQckW3D1AU9Q_R6dC:b-n6uked) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b20bef1da09475f349743886e2bcf80c97023c6/pkg/kv/kvserver/replica_proposal_buf.go#L737)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Aren't these first two conditions equal to `p.Request.WriteTimestamp().Less(b.assignedClosedTimestamp)`?
</blockquote></details>

yes. I don't know what I was thinking when I wrote it like that.
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 739 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIfOmF4ryKm55a29A4:-MYLQhsNBmn-XXsoGjQl:b19b8xx) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b20bef1da09475f349743886e2bcf80c97023c6/pkg/kv/kvserver/replica_proposal_buf.go#L739)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: pull this out before if you're going to assign it to a variable so that we can use it in the check.
</blockquote></details>

well `wts` escapes, that's why I put it inside the `if` (right?)
But I've gotten rid of it, it wasn't worth a variable.
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 633 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIgK8O21j_cQ6CHc8A:-MYL6VtB0Vnws2EZa4M4:b7butrk) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e94e1524d5424a514050d4653e298cbbcda9c/pkg/kv/kvserver/replica_proposal_buf.go#L633)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need this? Don't we have the `submitProposalFilter` right above?
</blockquote></details>

`submitProposalFilter` as it stood wasn't good because it ran before a closed ts had been assigned to the command. But I've prepended a commit to make it run after, and switched to use it.
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 752 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIgZzI01Cjr4lhl3MB:-MYLIYZX5dz7JlBltemL:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e94e1524d5424a514050d4653e298cbbcda9c/pkg/kv/kvserver/replica_proposal_buf.go#L752)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"to not be evaluating"?
</blockquote></details>

done
___
*[pkg/kv/kvserver/replica_proposal_buf_test.go, line 204 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIfhfw30fUrx982ffU:-MYLR4xpBMkidzOy5Lst:b-2th62g) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b20bef1da09475f349743886e2bcf80c97023c6/pkg/kv/kvserver/replica_proposal_buf_test.go#L204)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need this change? We you planning on testing the new assertion?
</blockquote></details>

well it's not that I particularly wanted to test the assertion, but that without this change the assertion fires for the test that now passes a timestamp (`TestProposalBufferClosedTimestamp`). That's a unit test where proposals don't go through a tracker.
___
*[pkg/kv/kvserver/replica_proposal_buf_test.go, line 768 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIh-We5a63losssytk:-MYLNAnf-MjjhiJWfSzx:b-2x4j6k) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e94e1524d5424a514050d4653e298cbbcda9c/pkg/kv/kvserver/replica_proposal_buf_test.go#L768)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is it possible to make this mandatory and check it for each subtest?
</blockquote></details>

see now
___
*[pkg/kv/kvserver/replica_range_lease.go, line 1056 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIh9oJ8G4W0BrWQ8J8:-MYLK_FaEvjFaaAbEcs8:b-s52snc) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e94e1524d5424a514050d4653e298cbbcda9c/pkg/kv/kvserver/replica_range_lease.go#L1056)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can this live in `helpers_test.go`?
</blockquote></details>

not exactly, because I was calling it from `TestServer`, which is in a different package. But I've removed the `TestServer` utility in favor of having the test reach down directly for the replica, and I've moved this to `helpers_test.go`. I've got mixed feelings.
___
*[pkg/kv/kvserver/replica_range_lease.go, line 1281 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIh4xp-ndhoZwtHUfg:-MYLInQZ-1ZzJtV7aFWO:b-hfpv0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e94e1524d5424a514050d4653e298cbbcda9c/pkg/kv/kvserver/replica_range_lease.go#L1281)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I don't think you meant to keep this.
</blockquote></details>

removed
___
*[pkg/kv/kvserver/testing_knobs.go, line 26 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIg1JRDI64jgdxqE_T:-MYLIjsqCBz7M0opsLIj:b-hfpv0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e94e1524d5424a514050d4653e298cbbcda9c/pkg/kv/kvserver/testing_knobs.go#L26)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"FLush"
</blockquote></details>

removed

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-:-MYLgSif8GHpuqhfbwDm:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvserver/replica_closedts_test.go, line 448 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIhwusA_3XiR4N_ieV:-MYLexCX5RYHmGw3Sm6Q:bhek3dw) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e94e1524d5424a514050d4653e298cbbcda9c/pkg/kv/kvserver/replica_closedts_test.go#L448)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think the issue is easily discoverable from the commit message. 
</blockquote></details>

Until the test gets moved a few times and the git blame requires a few hops to find the commit message. But I don't feel strongly.
___
*[pkg/kv/kvserver/replica_proposal_buf_test.go, line 204 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIfhfw30fUrx982ffU:-MYLgfP_0IUn5CHjy1Iq:byunugd) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b20bef1da09475f349743886e2bcf80c97023c6/pkg/kv/kvserver/replica_proposal_buf_test.go#L204)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

well it's not that I particularly wanted to test the assertion, but that without this change the assertion fires for the test that now passes a timestamp (`TestProposalBufferClosedTimestamp`). That's a unit test where proposals don't go through a tracker.
</blockquote></details>

Oh, I was missing: `pc.newPutProposal(now.ToTimestamp())`. Carry on.

**Review by andreimatei — COMMENTED** [review]
had to do some crap to make the test stable. Please look at the new commit called "improve test utilities for lease info".

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-:-MYN8PlQ7jj7_-8oZ3xY:bx0n5rx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvserver/replica_closedts_test.go, line 448 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-MYIhwusA_3XiR4N_ieV:-MYN86qH4NmdJGIUsDau:b-4c142u) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e94e1524d5424a514050d4653e298cbbcda9c/pkg/kv/kvserver/replica_closedts_test.go#L448)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Until the test gets moved a few times and the git blame requires a few hops to find the commit message. But I don't feel strongly.
</blockquote></details>

the thing is that I don't believe that issue to be useful to anyone. It's up to the comments on the test and, to a lesser degree, this commit message.

**Review by andreimatei — COMMENTED** [review]
Please look at the new commits called "wait when adding voters" and "improve test utilities for lease info".

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-:-MYNeMsT-ls7YU6EQI0q:bvorpea)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r14, 6 of 6 files at r15, 6 of 6 files at r20, 6 of 6 files at r21.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-:-MYf2bHp9KlnHydPih-6:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by andreimatei — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63672#-:-MYf2vN_8Hjvs-RBDW7R:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Pull request merged**
