### PR TITLE
sql: postgresql dollar-quoted string support

### LINKED ISSUE #41777: sql: support dollar-quotes
Postgres supports the following:

> While the standard syntax for specifying string constants is usually convenient, it can be difficult to understand when the desired string contains many single quotes or backslashes, since each of those must be doubled. To allow more readable queries in such situations, PostgreSQL provides another way, called "dollar quoting", to write string constants. A dollar-quoted string constant consists of a dollar sign ($), an optional "tag" of zero or more characters, another dollar sign, an arbitrary sequence of characters that makes up the string content, a dollar sign, the same tag that began this dollar quote, and a dollar sign.

https://www.postgresql.org/docs/9.1/sql-syntax-lexical.html

### PR DESCRIPTION
**Pull request by damienhollis**
Added support for postgresql dollar-quoted strings in the scanner. A
dollar-quoted string constant consists of a dollar sign ($), an
optional "tag" of zero or more characters, another dollar sign, an
arbitrary sequence of characters that makes up the string content, a
dollar sign, the same tag that began this dollar quote, and a final
dollar sign.

The scanner uses the existing token type of SCONST for dollar-quoted
strings. As a result, when the AST is formatted as a string, there is
no knowledge that the original input was dollar-quoted and it is
therefore formatted as either a plain string or an escaped
string (depending on the content).

Fixes #41777.

Release Note (sql change): CockroachDB now supports string and byte
array literals using the dollar-quoted notation, as documented here:
https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING

### CODE REVIEW

**Comment by knz** [comment]
Thanks for this change. I will let others in the team review the code change; can you add a link to the pg doc that explain this syntax in the release note? thx

**Comment by damienhollis** [comment]
Sure - done.

**Comment by knz** [comment]
Damien I'm really grateful you're trying to help!
Our git commit message guidelines are here: https://wiki.crdb.io/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages

as you'll surely establish yourself, there is some way to go here. Feel free to peruse this yourself; otherwise one of us will polish the result before the PR merges.

**Comment by damienhollis** [comment]
Updated the commit message - hopefully closer to what is expected.

**Comment by knz** [comment]
nice thanks :+1:

**Comment by rohany** [comment]
@knz can you review this? It seems like you have the most context on how the lexer works.

**Comment by knz** [comment]
i can but is there a deadline? I likely won't have time until later this week.

**Comment by rohany** [comment]
> is there a deadline

Don't believe so

**Comment by knz** [comment]
Hi Damien,
I just came around to reviewing this. It is very good. Thank you for your contribution.
I took the liberty to rebase your patch over the most recent `master` branch, as well as replacing a call to `s.next()` by `s.peek()` and a minor wording change to the release note. Other than that we can accept your contribution as is.

Thank you again!

bors r+

**Comment by SWDevAngel** [comment]
@damienhollis Hi Damien. Thank you for contributing to CockroachDB this year. As a token of our appreciation we would like to send you a gift. Please DM me on our [community Slack](https://cockroa.ch/slack) `@lisa` so I can send you a link. (If you don’t want a gift, we also have a charitable contribution choice.) All orders need to be in by December 13, so please send this asap. :)

**Pull request merged**
