### PR TITLE
release-21.1: kv,changefeedccl: Mark timeout when nudging a range as retryable

### PR DESCRIPTION
**Pull request by HonoreDB**
Backport 1/1 commits from #68347.

/cc @cockroachdb/release

---

Fixing a possible cause for #67973 -- an attempt to establish a
rangefeed that encounters no lease and times out trying to create
one seems like it may be bubbling up to cdc under chaos, when it's
likely to succeed if it retries.

I haven't been able to find a path in testing that actually hits
this, since the async nudging effectively retries forever anyway
so this only matters if somehow the rangefeed creation happens right
as we're getting into a bad state.

Release note: None

Release justification: Patches a newly-introduced bug.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Will this backport or https://github.com/cockroachdb/cockroach/pull/68347 in general be safe in a mixed version cluster? What will happen if a newer node returns a `RangeFeedRetryError` with the new `REASON_NO_LEASEHOLDER` reason to an older node? Do we risk hitting this fatal:
https://github.com/cockroachdb/cockroach/blob/d0f2981b131700bcf378d7ace28ee0783e60918b/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L196

Also, do we have mixed version tests that run CDC?

**Comment by nvanbenschoten** [comment]
Oh never mind, @HonoreDB is way ahead of me with https://github.com/cockroachdb/cockroach/pull/68495 and https://github.com/cockroachdb/cockroach/pull/68502.

**Comment by HonoreDB** [comment]
This needs to wait two more days so the follow-up PRs can also be backported.

**Comment by HonoreDB** [comment]
Closing in favor of https://github.com/cockroachdb/cockroach/pull/69157, no point in being non-atomic.

**Pull request closed without merging**
