### PR TITLE
sql: add pgcode to `ALTER COLUMN SET DEFAULT` type error

### LINKED ISSUE #56449: sql: unclassified error for `ALTER COLUMN SET DEFAULT` with the wrong type
The following error should be classified as a DatatypeMismatch(42804)
```
create table t(i int);
ok

alter table t alter column i set default 'i'::string;
ERROR: expected DEFAULT expression to have type int, but ''i'::STRING' has type string
```

### LINKED ISSUE #56465: sql: uncategorized error for `ALTER INDEX ... RENAME TO ...` index does not exist
The following error needs use pgcode.UndefinedObject
```
root@:26257/defaultdb> alter index foo@does_not_exist rename to "index";
ERROR: index "does_not_exist" does not exist
```

### PR DESCRIPTION
**Pull request by jayshrivastava**
sql: add pgcode to `ALTER COLUMN SET DEFAULT` type error 

Previously, adding a default value of the wrong type to a
column would return an unclassifed error to the user. This change
resolves the issue by returning a pgcode.DatatypeMismatch (42804)
in the specified situation.

Closes: https://github.com/cockroachdb/cockroach/issues/56449

Release note (sql change): Added a pgcode (42804, DatatypeMismatch)
when adding a default value of the wrong type to a column.

---
sql: add pgcode to `ALTER INDEX ... RENAME TO` undefined index error

Previously, executing a statement to rename an undefined
index would result in an uncategorized error. This change fixes
this behaviour by returning a pgcode.UndefinedObject (42704)
error in the same situation.

Closes: #56465

Release note (sql change): Attempting to rename undefined index
will return a pgcode.UndefinedObject (42704) error intead of
an uncategorized error.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
First commit :lgtm:, second let's lift the wrapping up a layer. 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56455#-:-MLnWfu41Kex3p7wwoe1:bbbfsz4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @jayshrivastava)

___
*[pkg/sql/catalog/tabledesc/structured.go, line 2729 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56455#-MLnWVkd24d2okfSMSjH:-MLnWVkd24d2okfSMSjI:b-iaexa7) ([raw file](https://github.com/cockroachdb/cockroach/blob/745ab59db7c7ec81ef2c5c3b6c989383c6de90f9/pkg/sql/catalog/tabledesc/structured.go#L2729)):*
> ```Go
> 	}
> 	return nil, false, pgerror.Newf(pgcode.UndefinedObject, "index %q does not exist", name)
> }
> ```

This one seems like not what we want. The callers above this should detect the error and wrap it appropriately.

**Review by jayshrivastava — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56455)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

___
*[pkg/sql/catalog/tabledesc/structured.go, line 2729 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56455#-MLnWVkd24d2okfSMSjH:-MLnYZARCvzxy1kRSc-D:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/745ab59db7c7ec81ef2c5c3b6c989383c6de90f9/pkg/sql/catalog/tabledesc/structured.go#L2729)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This one seems like not what we want. The callers above this should detect the error and wrap it appropriately. 
</blockquote></details>

Done.

**Review by ajwerner — APPROVED** [review]
:lgtm_strong: 

> Reviewed 1 of 2 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56455#-:-MLnyC75E_UYgYXc_ig2:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by jayshrivastava** [comment]
bors r=ajwerner

**Pull request merged**
