### PR TITLE
c-deps: update to rocksdb v5.5.1

### PR DESCRIPTION
**Pull request by danhhz**
Also remove the DisableSnapshotClearRange hack that was working around a bug that was fixed in v5.5.1.

### CODE REVIEW

**Review by benesch — APPROVED** [review]
LGTM!

**Comment by danhhz** [comment]
TFTR!

**Comment by tschottdorf** [comment]
That was fast, thanks!

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 17 of 17 files at r1, 6 of 6 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16808#-:-KntBPoihjU0p8fWOiqY:bnfp4nl)*

**Comment by mberhault** [comment]
Oops: this seems to have reverted some portable build flags, resulting in the use of avx2 instructions which craps out on older VMs (quite a few of those in Azure). see #16843

**Comment by benesch** [comment]
I can fix this; I landed the change to RocksDB that caused this to break.
We just need to tweak the CMake flags that we build RocksDB with.

**Pull request merged**
