### PR TITLE
cli/sql: support Kerberos auth

### LINKED ISSUE #42488: cli: crdb client commands should support GSSAPI based authentication
Currently, we require SQL users to use PSQL to connect to a cockroachdb cluster using GSSAPI authentication against Kerberos.  This makes troubleshooting very difficult so Cockroach SQL should be enhanced to work properly in this context.

### PR DESCRIPTION
**Pull request by madelynnblue**
Informs #42488
Informs #51454

Release note: add Kerberos (GSS) support to `cockroach sql` and other CLI commands that only use the SQL protocol (such as `node ls`, or `node status`). Other `cockroach` CLI commands that also use the RPC protocol still cannot use Kerberos (such as `node decommission`, `debug zip`, etc).

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Thanks for this. The code LGTM.

I have updated the PR description on Github, please forward this text to your commit message to ensure the updated Release note gets picked up by our automatic script.

It would also help if you could include an example of how to connect into the commit message, to aid the documentation writer.

(I also checked that all the new deps have acceptable licenses. It's all APL and BSD, so that's ok)

I'll have a final look at the PR once you figure out what's wrong in CI.

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51570#-:-MCXXnsV8HurH6NLwFg1:btpmnf0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/acceptance/compose/gss/psql/gss_test.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51570#-MCXX1O0B_4L9k3I3t9M:-MCXX1O1DuMV6xS4Ts_u:b-lcue25) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67c8bc1046b307cee61bb8e46a102bc1e7fa422/pkg/acceptance/compose/gss/psql/gss_test.go#L114)):*
> ```Go
> 				userDB := gosql.OpenDB(userConnector)
> 				defer userDB.Close()
> 				_, err = userDB.Exec("SELEeCT 1")
> ```

did you intend the typo in the SQL query?
___
*[pkg/acceptance/compose/gss/psql/gss_test.go, line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51570#-MCXY8hm9c_a0dQnZpWa:-MCXY8hm9c_a0dQnZpWb:b-k7q28n) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67c8bc1046b307cee61bb8e46a102bc1e7fa422/pkg/acceptance/compose/gss/psql/gss_test.go#L130)):*
> ```Go
> 					"-e", "SELECT 1",
> 					"--certs-dir", "/certs",
> 					// TODO(mjibson): Teach the CLI to not ask for passwords during kerberos.
> ```

Please file an issue for this thanks. Assign the issue to the "Server/CLI" project too.

**Comment by knz** [comment]
(note how this PR does not "fix" #42488, because fully fixing that issue needs to also solve #51454. So please update the commit message so that GH does not auto-close the issue when you will eventually merge this)

**Review by madelynnblue — COMMENTED** [review]
Fixed commit message.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51570#-:-MCcbEcX-04nZl3n3l7h:btbi3hb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/acceptance/compose/gss/psql/gss_test.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51570#-MCXX1O0B_4L9k3I3t9M:-MCcbMhV6p5ZgGvCiRhG:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67c8bc1046b307cee61bb8e46a102bc1e7fa422/pkg/acceptance/compose/gss/psql/gss_test.go#L114)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

did you intend the typo in the SQL query?
</blockquote></details>

fixed
___
*[pkg/acceptance/compose/gss/psql/gss_test.go, line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51570#-MCXY8hm9c_a0dQnZpWa:-MCcbqDG1dQGcENFXCxs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67c8bc1046b307cee61bb8e46a102bc1e7fa422/pkg/acceptance/compose/gss/psql/gss_test.go#L130)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please file an issue for this thanks. Assign the issue to the "Server/CLI" project too.
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
:lgtm: but there's something odd in CI

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51570#-:-MCf5G99-8Df_QpJuhob:b-npsf84)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by knz** [comment]
cc @thtruo @aaron-crl @BramGruneir  for tracking

**Comment by mjibson** [comment]
CI link is https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_CompileBuilds/2101009?showLog=2101009_21046_5401.21046 which has `Makefile:981: recipe for target 'cockroach.windows-6.2-amd64.exe' failed`

**Comment by mjibson** [comment]
Oh I think that build failure is indeed caused by this PR. I guess I'll try to figure it out? Blergh.

**Comment by mjibson** [comment]
```[18:04:54]W:	 [Step 3/4] vendor/github.com/lib/pq/auth/kerberos/krb_windows.go:17:17: undefined: GSS
[18:04:54]W:	 [Step 3/4] vendor/github.com/lib/pq/auth/kerberos/krb_windows.go:18:8: undefined: GSS
[18:04:54]W:	 [Step 3/4] vendor/github.com/lib/pq/auth/kerberos/krb_windows.go:28:10: undefined: GSS
[18:04:54]W:	 [Step 3/4] vendor/github.com/lib/pq/auth/kerberos/krb_windows.go:39:10: undefined: GSS
[18:04:54]W:	 [Step 3/4] vendor/github.com/lib/pq/auth/kerberos/krb_windows.go:52:10: undefined: GSS
[18:04:54]W:	 [Step 3/4] vendor/github.com/lib/pq/auth/kerberos/krb_windows.go:64:10: undefined: GSS
```

**Comment by mjibson** [comment]
Haha! lib/pq write access pays off again. Small bug in its windows build. Will merge if this passes.

**Comment by BramGruneir** [comment]
This is great!  Thanks for working on it!

**Pull request merged**
