### PR TITLE
roachtest: add test that aggregates orm blacklist failures

### PR DESCRIPTION
**Pull request by jordanlewis**
The spreadsheet we discussed is unwieldy - hard to edit and impossible to keep
up to date. If we write down blacklists in code, then we can use an approach
like this to always have an up to date aggregation.

So far it seems like there's just a lot of unknowns to categorize still.

The output today:

```
=== RUN   TestBlacklists
 648: unknown                                                (unknown)
 493: https://github.com/cockroachdb/cockroach/issues/5807   (sql: Add support for TEMP tables)
 151: https://github.com/cockroachdb/cockroach/issues/17511  (sql: support stored procedures)
  86: https://github.com/cockroachdb/cockroach/issues/26097  (sql: make TIMETZ more pg-compatible)
  56: https://github.com/cockroachdb/cockroach/issues/10735  (sql: support SQL savepoints)
  55: https://github.com/cockroachdb/cockroach/issues/32552  (multi-dim arrays)
  55: https://github.com/cockroachdb/cockroach/issues/26508  (sql: restricted DDL / DML inside transactions)
  52: https://github.com/cockroachdb/cockroach/issues/32565  (sql: support optional TIME precision)
  39: https://github.com/cockroachdb/cockroach/issues/243    (roadmap: Blob storage)
  33: https://github.com/cockroachdb/cockroach/issues/26725  (sql: support postgres' API to handle blob storage (incl lo_creat, lo_from_bytea))
  31: https://github.com/cockroachdb/cockroach/issues/27793  (sql: support custom/user-defined base scalar (primitive) types)
  24: https://github.com/cockroachdb/cockroach/issues/12123  (sql: Can't drop and replace a table within a transaction)
  24: https://github.com/cockroachdb/cockroach/issues/26443  (sql: support user-defined schemas between database and table)
  20: https://github.com/cockroachdb/cockroach/issues/21286  (sql: Add support for geometric types)
  18: https://github.com/cockroachdb/cockroach/issues/6583   (sql: explicit lock syntax (SELECT FOR {SHARE,UPDATE} {skip locked,nowait}))
  17: https://github.com/cockroachdb/cockroach/issues/22329  (Support XA distributed transactions in CockroachDB)
  16: https://github.com/cockroachdb/cockroach/issues/24062  (sql: 32 bit SERIAL type)
  16: https://github.com/cockroachdb/cockroach/issues/30352  (roadmap:when CockroachDB  will support cursor?)
  12: https://github.com/cockroachdb/cockroach/issues/27791  (sql: support RANGE types)
   8: https://github.com/cockroachdb/cockroach/issues/40195  (pgwire: multiple active result sets (portals) not supported)
   8: https://github.com/cockroachdb/cockroach/issues/6130   (sql: add support for key watches with notifications of changes)
   5: Expected Failure                                       (unknown)
   5: https://github.com/cockroachdb/cockroach/issues/23468  (sql: support sql arrays of JSONB)
   5: https://github.com/cockroachdb/cockroach/issues/40854  (sql: set application_name from connection string)
   4: https://github.com/cockroachdb/cockroach/issues/35879  (sql: `default_transaction_read_only` should also accept 'on' and 'off')
   4: https://github.com/cockroachdb/cockroach/issues/32610  (sql: can't insert self reference)
   4: https://github.com/cockroachdb/cockroach/issues/40205  (sql: add non-trivial implementations of FOR UPDATE, FOR NO KEY UPDATE, FOR SHARE, FOR NO KEY SHARE)
   4: https://github.com/cockroachdb/cockroach/issues/35897  (sql: unknown function: pg_terminate_backend())
   4: https://github.com/cockroachdb/cockroach/issues/4035   (sql/pgwire: missing support for row count limits in pgwire)
   3: https://github.com/cockroachdb/cockroach/issues/27796  (sql: support user-defined DOMAIN types)
   3: https://github.com/cockroachdb/cockroach/issues/3781   (sql: Add Data Type Formatting Functions)
   3: https://github.com/cockroachdb/cockroach/issues/40476  (sql: support `FOR {UPDATE,SHARE} {SKIP LOCKED,NOWAIT}`)
   3: https://github.com/cockroachdb/cockroach/issues/35882  (sql: support other character sets)
   2: https://github.com/cockroachdb/cockroach/issues/10028  (sql: Support view queries with star expansions)
   2: https://github.com/cockroachdb/cockroach/issues/35807  (sql: INTERVAL output doesn't match PG)
   2: https://github.com/cockroachdb/cockroach/issues/35902  (sql: large object support)
   2: https://github.com/cockroachdb/cockroach/issues/40474  (sql: support `SELECT ... FOR UPDATE OF` syntax)
   1: https://github.com/cockroachdb/cockroach/issues/18846  (sql: Support CIDR column type)
   1: https://github.com/cockroachdb/cockroach/issues/9682   (sql: implement computed indexes)
   1: https://github.com/cockroachdb/cockroach/issues/31632  (sql: FK options (deferrable, etc))
   1: https://github.com/cockroachdb/cockroach/issues/24897  (sql: CREATE OR REPLACE VIEW)
   1: pass?                                                  (unknown)
   1: https://github.com/cockroachdb/cockroach/issues/36215  (sql: enable setting standard_conforming_strings to off)
   1: https://github.com/cockroachdb/cockroach/issues/32562  (sql: support SET LOCAL and txn-scoped session variable changes)
   1: https://github.com/cockroachdb/cockroach/issues/36116  (sql: psychopg: investigate how `'infinity'::timestamp` is presented)
   1: https://github.com/cockroachdb/cockroach/issues/26732  (sql: support the binary operator: <int> / <float>)
   1: https://github.com/cockroachdb/cockroach/issues/23299  (sql: support coercing string literals to arrays)
   1: https://github.com/cockroachdb/cockroach/issues/36115  (sql: psychopg: investigate if datetimetz is being returned instead of datetime)
   1: https://github.com/cockroachdb/cockroach/issues/26925  (sql: make the CockroachDB integer types more compatible with postgres)
   1: https://github.com/cockroachdb/cockroach/issues/21085  (sql: WITH RECURSIVE (recursive common table expressions))
   1: https://github.com/cockroachdb/cockroach/issues/36179  (sql: implicity convert date to timestamp)
   1: https://github.com/cockroachdb/cockroach/issues/36118  (sql: Cannot parse '24:00' as type time)
   1: https://github.com/cockroachdb/cockroach/issues/31708  (sql: support current_time)
```

Release justification: non-production change
Release note: None

### CODE REVIEW

**Comment by awoods187** [comment]
nice job!

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41252)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rafiss)

___
*[pkg/cmd/roachtest/blacklist_test.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41252#-LqbAyEX2_FDsHo5lnES:-LqbAyEZ1JLc1Tpw7XHJ:bjsr4iz) ([raw file](https://github.com/cockroachdb/cockroach/blob/cebc8113a5af49f52c71b99d7bc8cc37e82a0731/pkg/cmd/roachtest/blacklist_test.go#L99)):*
> ```Go
> 
> 	ctx := context.Background()
> 	// If you run out of non-authed requests, set ts to your personal access token.
> ```

what is the non-auth rate limit? does the test running on CI affect some sort of global rate limit somehow?
___
*[pkg/cmd/roachtest/blacklist_test.go, line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41252#-LqbBMOhDIHzOxSeeWXD:-LqbBMOhDIHzOxSeeWXE:b-q51d20) ([raw file](https://github.com/cockroachdb/cockroach/blob/cebc8113a5af49f52c71b99d7bc8cc37e82a0731/pkg/cmd/roachtest/blacklist_test.go#L128)):*
> ```Go
> 			issueTitle = issueTitleMap[issueNum]
> 		}
> 		fmt.Printf("%4d: %-54s (%s)\n", counts[i].count, reason, issueTitle)
> ```

is there any different between using `fmt.Printf` vs `t.Log` that means we should prefer one or the other?
___
*[pkg/cmd/roachtest/blacklist_test.go, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41252#-LqbBDTm2OjsGMpQJ2MR:-LqbBDTm2OjsGMpQJ2MS:b-id71ht) ([raw file](https://github.com/cockroachdb/cockroach/blob/cebc8113a5af49f52c71b99d7bc8cc37e82a0731/pkg/cmd/roachtest/blacklist_test.go#L132)):*
> ```Go
> 
> 	if editedIssueTitleMap {
> 		// Print out a new issueTitleMap so the user can edit the one in this file.
> ```

the information in this comment would also be useful to be in the log messages

**Review by rafiss — COMMENTED** [review]
excellent! def a good idea, just had minor questions

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41252#-:-LqbB_wJ0QIDwG0RSDJm:b-2sro8z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rafiss)

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41252)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/cmd/roachtest/blacklist_test.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41252#-LqbAyEX2_FDsHo5lnES:-Lt2p3nC6rDLFeePdH4T:b-335fen) ([raw file](https://github.com/cockroachdb/cockroach/blob/cebc8113a5af49f52c71b99d7bc8cc37e82a0731/pkg/cmd/roachtest/blacklist_test.go#L99)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

what is the non-auth rate limit? does the test running on CI affect some sort of global rate limit somehow?
</blockquote></details>

I'm not sure. I think it's a per IP limit. If this starts breaking we'll just turn it off.
___
*[pkg/cmd/roachtest/blacklist_test.go, line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41252#-LqbBMOhDIHzOxSeeWXD:-Lt2pCU_C50Lim6yvhwo:b-h4if2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/cebc8113a5af49f52c71b99d7bc8cc37e82a0731/pkg/cmd/roachtest/blacklist_test.go#L128)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

is there any different between using `fmt.Printf` vs `t.Log` that means we should prefer one or the other?
</blockquote></details>

t.Log only gets printed with test.v.
___
*[pkg/cmd/roachtest/blacklist_test.go, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41252#-LqbBDTm2OjsGMpQJ2MR:-Lt2pFPf0N86XcPWI7Zt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cebc8113a5af49f52c71b99d7bc8cc37e82a0731/pkg/cmd/roachtest/blacklist_test.go#L132)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

the information in this comment would also be useful to be in the log messages
</blockquote></details>

Done.

**Review by jordanlewis — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41252#-:-Lt2pQdL0DCzAF1aQY5y:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Pull request merged**
