### PR TITLE
keys: Malformed keys no longer crash keys.Addr

### LINKED ISSUE #5500: stability: query of death: "local key ... malformed"
sha: 66fc410

Was trying to list some keys through the `cockroach debug range scan` command.
I ran a bunch of queries, but I think the one that caused the crashes was:
`$ cockroach debug kv scan --host=beta.cockroachdb.com <cert flags> 0 ~`

All 4 nodes died within 0.4s with:
```
F160323 14:02:17.845573 keys/keys.go:345  local key /Local/"" malformed; should contain prefix /Local/Range

To see all goroutines, visit https://github.com/maruel/panicparse#GOTRACEBACK

1: running [Created by grpc.(*Server).serveStreams.func1 @ server.go:324]
    log     clog.go:868             getStacks(0xece849800, 0, 0, 0)
    log     clog.go:732             (*loggingT).outputLogEntry(0x26237a0, 0x3, 0x202ce02, 0xc, 0x159, 0xc824a5f180, 0x41)
    log     structured.go:57        addStructured(0, 0, 0x6f6c622e00000003, 0x2, #1, 0x30, #7, 0x2, 0x2)
    log     log.go:73               logDepth(0, 0, 0x1, 0xc800000003, #1, 0x30, #7, 0x2, 0x2)
    log     log.go:179              Fatalf(#1, 0x30, #7, 0x2, 0x2)
    keys    keys.go:345             Addr(0xc820cda420, 0x1, 0x8, 0, 0, 0)
    keys    keys.go:541             Range(0, 0, 0, 0, 0, 0, 0, 0, 0xc82114ede0, 0, ...)
    kv      dist_sender.go:574      (*DistSender).sendChunk(#2, #11, #9, 0, 0, 0, 0, 0, 0, 0, ...)
    kv      dist_sender.go:525      (*DistSender).Send(#2, #11, #9, 0, 0, 0, 0, 0, 0, 0, ...)
    kv      txn_coord_sender.go:415 (*TxnCoordSender).Send(0xc820353800, #11, #9, 0, 0, 0, 0, 0, 0, 0, ...)
    kv      db.go:92                (*DBServer).Batch.func1()
    stop    stopper.go:166          (*Stopper).RunTask(0xc8202c3340, 0xc8242098a0, 0x1876700)
    kv      db.go:102               (*DBServer).Batch(#4, #11, #8, 0xc821f49960, 0, 0, 0)
    roachpb api.pb.go:1329          _External_Batch_Handler(0x1682ba0, #4, #11, #8, 0xc827b1d7c0, 0, 0, 0, 0)
    grpc    server.go:497           (*Server).processUnaryRPC(#3, #10, #5, #6, 0xc82035bb20, 0x233e260, 0, 0, 0)
    grpc    server.go:646           (*Server).handleStream(#3, #10, #5, #6, 0) 
    grpc    server.go:323           (*Server).serveStreams.func1.1(0xc821493ef0, #3, #10, #5, #6)
```

### PR DESCRIPTION
**Pull request by nvb**
Fixes #5500.
- `keys.Addr` (and related functions) now return an error on
  unaddressable keys
- `keys.Addr` now properly handles doubly-encoded range-locally
  addressed keys

The following no longer crashes a node.

```
for i in $(seq 0 255); do echo $i; ./cockroach debug kv scan --insecure '' $(printf "\x$(printf %x ${i})"); done
```

The majority of this is error plumbing, but there are a few changes in the `keys` and `kv` package that are important.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5604)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 25 of 25 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[keys/keys.go, line 343 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604#-KDp2aqlMv_p-V03bNAv:-KDp2aqmVcQVaDet92OI:2127160479) ([raw file](https://github.com/cockroachdb/cockroach/blob/73e3ab2f72f6057beb4879f69cc29d6019ba54d6/keys/keys.go#L343)):*
why not util.Errorf?

---

*[keys/keys_test.go, line 95 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604#-KDp2CCThbk16HRJ4Ai1:-KDp2CCThbk16HRJ4Ai2:-2109865008) ([raw file](https://github.com/cockroachdb/cockroach/blob/73e3ab2f72f6057beb4879f69cc29d6019ba54d6/keys/keys_test.go#L95)):*
```
if ..; err != nil {
} else if !keyAddr.. {
}
```

This code currently double reports errors

---

*[keys/keys_test.go, line 124 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604#-KDp2PQ0agcsRl0jnflx:-KDp2PQ0agcsRl0jnfly:1472736555) ([raw file](https://github.com/cockroachdb/cockroach/blob/73e3ab2f72f6057beb4879f69cc29d6019ba54d6/keys/keys_test.go#L124)):*
always assert on the specific error testutils.IsError

---

*[keys/keys_test.go, line 395 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604#-KDp2gnZb6AwXZolVEmi:-KDp2gn_AH6yxURphmE3:-1166438894) ([raw file](https://github.com/cockroachdb/cockroach/blob/73e3ab2f72f6057beb4879f69cc29d6019ba54d6/keys/keys_test.go#L395)):*
ditto re else if

---

*[kv/dist_sender_test.go, line 572 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604#-KDp44v2j1tt4AOP77pk:-KDp44v3VDlNjEYtplQb:-1166438894) ([raw file](https://github.com/cockroachdb/cockroach/blob/3046e01815a06ad405ea2c2755dbe2f93f2aaa10/kv/dist_sender_test.go#L572)):*
ditto re else if

---

*[kv/range_cache_test.go, line 141 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604#-KDp2yC51fyhhGYtUL97:-KDp2yC51fyhhGYtUL98:-1585703716) ([raw file](https://github.com/cockroachdb/cockroach/blob/73e3ab2f72f6057beb4879f69cc29d6019ba54d6/kv/range_cache_test.go#L141)):*
heh, maybe remove while you're here

---

*[storage/replica_command.go, line 791 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604#-KDp3n7c3ldp1V8nELc_:-KDp3n7c3ldp1V8nELca:63815646) ([raw file](https://github.com/cockroachdb/cockroach/blob/73e3ab2f72f6057beb4879f69cc29d6019ba54d6/storage/replica_command.go#L791)):*
compute this just once?

---

*[storage/engine/mvcc.go, line 1874 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604#-KDp3Z2kgITic7zQ9WKn:-KDp3Z2kgITic7zQ9WKo:-646118508) ([raw file](https://github.com/cockroachdb/cockroach/blob/73e3ab2f72f6057beb4879f69cc29d6019ba54d6/storage/engine/mvcc.go#L1874)):*
seems like you can do this just once.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604)*

**Comment by nvanbenschoten** [comment]
Thanks for the review. Sorry that was so ugly.

---

Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[keys/keys.go, line 343 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604#-KDp2aqlMv_p-V03bNAv:-KDpAQBfUCq2zDILBaaL:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/73e3ab2f72f6057beb4879f69cc29d6019ba54d6/keys/keys.go#L343)):*
Done.

---

*[keys/keys_test.go, line 95 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604#-KDp2CCThbk16HRJ4Ai1:-KDpAcGMajQbQDVPkuzz:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/73e3ab2f72f6057beb4879f69cc29d6019ba54d6/keys/keys_test.go#L95)):*
Done.

---

*[keys/keys_test.go, line 124 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604#-KDp2PQ0agcsRl0jnflx:-KDpB1C9VrqCHTom9Wfw:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/73e3ab2f72f6057beb4879f69cc29d6019ba54d6/keys/keys_test.go#L124)):*
Done.

---

*[keys/keys_test.go, line 395 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604#-KDp2gnZb6AwXZolVEmi:-KDpBj1OujfwwUD3gBLK:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/73e3ab2f72f6057beb4879f69cc29d6019ba54d6/keys/keys_test.go#L395)):*
Done.

---

*[kv/dist_sender_test.go, line 572 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604#-KDp44v2j1tt4AOP77pk:-KDpBrw1z2CKrHwbl1ES:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3046e01815a06ad405ea2c2755dbe2f93f2aaa10/kv/dist_sender_test.go#L572)):*
Done.

---

*[kv/range_cache_test.go, line 141 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604#-KDp2yC51fyhhGYtUL97:-KDpC3P1lkzQrxAXj2Sq:550721939) ([raw file](https://github.com/cockroachdb/cockroach/blob/73e3ab2f72f6057beb4879f69cc29d6019ba54d6/kv/range_cache_test.go#L141)):*
Done. And above.

---

*[storage/replica_command.go, line 791 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604#-KDp3n7c3ldp1V8nELc_:-KDpCrG4WVghztECSNU3:-1836455173) ([raw file](https://github.com/cockroachdb/cockroach/blob/73e3ab2f72f6057beb4879f69cc29d6019ba54d6/storage/replica_command.go#L791)):*
It looks like they just needed the constant to be an RKey. It's safe to cast directly because `keys.Meta2KeyMax` isn't local.

---

*[storage/engine/mvcc.go, line 1874 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604#-KDp3Z2kgITic7zQ9WKn:-KDpDKCECKZMPLxqqaGp:904029538) ([raw file](https://github.com/cockroachdb/cockroach/blob/73e3ab2f72f6057beb4879f69cc29d6019ba54d6/storage/engine/mvcc.go#L1874)):*
Yep, but another instance where it's safe to cast (like we do in the comparison actually)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604#-:-KDpDeRI064zlGhkBQXb:-1185630218)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604#-:-KDpI0zO8rxnhGyol10p:1417088721)*

**Comment by nvanbenschoten** [comment]
Just want to wait for @tschottdorf to double check that this is the expected behavior with doubly-encoded local keys in `keys.Addr`.

**Comment by tschottdorf** [comment]
Reviewed 17 of 25 files at r1, 4 of 9 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[keys/keys.go, line 327 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604#-KDp_le1pFiruft-3gef:-KDp_le3Dw91KW8-NPA_:-1718668297) ([raw file](https://github.com/cockroachdb/cockroach/blob/35296b0b00348b136a5b7b78fa78ccf0af0cbf4e/keys/keys.go#L327)):*
Comment is a bit stale.

---

*[keys/keys.go, line 341 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604#-KDp_wPpC2PJUj2MrvdE:-KDp_wPpC2PJUj2MrvdF:563289321) ([raw file](https://github.com/cockroachdb/cockroach/blob/35296b0b00348b136a5b7b78fa78ccf0af0cbf4e/keys/keys.go#L341)):*
This can't be the correct behavior - if I feed `/Local/A/(/Local/B))` in here, don't I want `A` as the address? It would appear that now I get `B`, which is wrong.

`Addr` should only resolve one level. But what should probably happen is that `AsRawAddr()` returns an error when the key to be raw'ed isn't range-global.

Hope I'm missing something there because I know how much you'd love to undo all of this error handling...

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[keys/keys.go, line 341 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604#-KDp_wPpC2PJUj2MrvdE:-KDpdJ-8LWCgzzuXFqLN:-852176496) ([raw file](https://github.com/cockroachdb/cockroach/blob/35296b0b00348b136a5b7b78fa78ccf0af0cbf4e/keys/keys.go#L341)):*
Right, if you encode `/Local/A/(/Local/B))` you want `A` as the address. But if you encode `/Local/(/Local/B))` you want `B` as the address. This isn't touching the suffix at all here, it's just unwrapping the addressed key. See [this test case](https://github.com/cockroachdb/cockroach/pull/5604/files#diff-3b7f4fc6d374f6ad1fa35192de02daf6R91) for a working example.

With regards to only resolving one level, I'm not sure I agree with that. The reason is that if we only unwrap one level of a doubly-local key, we haven't resolved the keys address, so we can't actually return an `RKey`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604)*

**Comment by nvanbenschoten** [comment]
Review status: 20 of 26 files reviewed at latest revision, 2 unresolved discussions.

---

*[keys/keys.go, line 341 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604#-KDp_wPpC2PJUj2MrvdE:-KDpfnENRwgBF7_CsPH-:-1140643041) ([raw file](https://github.com/cockroachdb/cockroach/blob/35296b0b00348b136a5b7b78fa78ccf0af0cbf4e/keys/keys.go#L341)):*
Looking at the test case again, it doesnt actually show what it's supposed to show because we dont easily allow the creation of doubly-local keys. I changed it to work now.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604)*

**Comment by tschottdorf** [comment]
Review status: 20 of 26 files reviewed at latest revision, 3 unresolved discussions.

---

*[keys/keys.go, line 341 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604#-KDp_wPpC2PJUj2MrvdE:-KDpfm5cK2M-DJLutoQo:1210023163) ([raw file](https://github.com/cockroachdb/cockroach/blob/35296b0b00348b136a5b7b78fa78ccf0af0cbf4e/keys/keys.go#L341)):*
Ah, makes sense.

---

*[keys/keys.go, line 348 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604#-KDpgK2oeJgchYg5g95L:-KDpgK2oeJgchYg5g95M:-1516802498) ([raw file](https://github.com/cockroachdb/cockroach/blob/35296b0b00348b136a5b7b78fa78ccf0af0cbf4e/keys/keys.go#L348)):*
what it is that we actually decode and throw away here?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604)*

**Comment by tschottdorf** [comment]
:lgtm: (didn't review the whole thing though, only `keys.Addr`)

---

Reviewed 6 of 6 files at r5, 5 of 5 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604#-:-KDpgT_3BmeMh0Ofo-QZ:-1192895182)*

**Comment by nvanbenschoten** [comment]
Thanks for the review.

---

Review status: 20 of 26 files reviewed at latest revision, 2 unresolved discussions.

---

*[keys/keys.go, line 327 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604#-KDp_le1pFiruft-3gef:-KDphLR_3ZKPhPxzoErt:1403182485) ([raw file](https://github.com/cockroachdb/cockroach/blob/35296b0b00348b136a5b7b78fa78ccf0af0cbf4e/keys/keys.go#L327)):*
Yep, that was straight up incorrect and probably lead to a lot of confusion. Fixed.

---

*[keys/keys.go, line 348 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604#-KDpgK2oeJgchYg5g95L:-KDpgkei8MYEk-Az2hL1:-1497556020) ([raw file](https://github.com/cockroachdb/cockroach/blob/35296b0b00348b136a5b7b78fa78ccf0af0cbf4e/keys/keys.go#L348)):*
You'd think we're decoding the suffix and throwing away the suffix based on the order of return args, but it's actually an `encoding` package convention to have the first return value be the remaining byte slice, and the second be the decoded value. I'll add a comment to avoid future confusion.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604#-:-KDpiXvmkLfWjqeuYu_A:-588504482)*

**Comment by nvanbenschoten** [comment]
Review status: 20 of 26 files reviewed at latest revision, 2 unresolved discussions.

---

*[keys/keys.go, line 348 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604#-KDpgK2oeJgchYg5g95L:-KDpicXpAhyuIlZJI_qp:709608354) ([raw file](https://github.com/cockroachdb/cockroach/blob/35296b0b00348b136a5b7b78fa78ccf0af0cbf4e/keys/keys.go#L348)):*
s/throwing away the suffix/throwing away the key

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604)*

**Comment by tschottdorf** [comment]
Reviewed 6 of 6 files at r7, 5 of 5 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5604)*

**Pull request merged**
