### PR TITLE
opt: add costs for join filters

### PR DESCRIPTION
**Pull request by madelynnblue**
Add costing for join filters and do initial costing for geo lookup joins.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

[nit] the PR message is blank
[nit] in the first commit message "where costed" should be "were costed"

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48741#-:-M7DUJPG5pMAwLLydXY0:b-cwygn3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/sql/opt/xform/coster.go, line 375 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48741#-M7DW5Q94EUpSym26fzP:-M7DW5QA7fw7N81L1oqW:bouqg65) ([raw file](https://github.com/cockroachdb/cockroach/blob/128b5f2f1a3b3dcfb233c14177c09a27f8b2e465/pkg/sql/opt/xform/coster.go#L375)):*
> ```Go
> 	// columns. We add in both directions because we don't know which way
> 	// the equality filters will be defined.
> 	eqMap := make(map[opt.ColumnID]opt.ColumnID, len(leftEq)*2)
> ```

[nit] I'd use a `util.FastIntMap` here

**Comment by mjibson** [comment]
Switched to util.FastIntMap.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48741#-:-M7EDGXY2yy_MOfR79Er:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
