### PR TITLE
util/uuid: use default math/rand Source to eliminate race

### PR DESCRIPTION
**Pull request by ajwerner**
The previous commit created a new Source. Unfortunately, math/rand Sources are not safe for concurrent use. From math/rand:

```
The default Source is safe for concurrent use by multiple goroutines, but Sources created by NewSource are not.
```

Release note: None

### CODE REVIEW

**Review by benesch — APPROVED** [review]
:lgtm: to fix the immediate race, but as discussed in person I'm worried this will wipe out the performance gains of this change. If it does we might need thread-local RNGs.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32356#-:-LRIoLvgDCL9gt6RDyC2:bujgalm)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by tbg** [comment]
> to fix the immediate race, but as discussed in person I'm worried this will wipe out the performance gains of this change. If it does we might need thread-local RNGs.

What would that look like? Putting rands in a `sync.Pool` as in https://github.com/golang/go/issues/18590#issuecomment-271629446 (`syscall.Gettid()` exists but that's probably a slow route to take in the first place).

**Comment by nvanbenschoten** [comment]
> I'm worried this will wipe out the performance gains of this change. If it does we might need thread-local RNGs.

At a minimum, we could create a separate synchronized rand source for this purpose and give it its own lock. This would be better than using the default `math/rand` source. I don't think this will fully wipe out the perf gains because we're still avoiding a syscall on each txn ID.

**Pull request merged**
