### PR TITLE
roachtest: wait for rebalancing to each region in follower-reads test

### LINKED ISSUE #62855: roachtest: follower-reads/survival=region/locality=regional failed
[(roachtest).follower-reads/survival=region/locality=regional failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2831942&tab=buildLog) on [master@d145e9fc02064a8b6b4179b5af7da5238b192f74](https://github.com/cockroachdb/cockroach/commits/d145e9fc02064a8b6b4179b5af7da5238b192f74):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/follower-reads/survival=region/locality=regional/run_1
	follower_reads.go:407,follower_reads.go:341,follower_reads.go:55,test_runner.go:768: 5 latency values ([95.207418ms 96.255994ms 97.402874ms 98.04185ms 93.831162ms]) are above target latency 20ms, 3 permitted

```

<details><summary>More</summary><p>

Artifacts: [/follower-reads/survival=region/locality=regional](https://teamcity.cockroachdb.com/viewLog.html?buildId=2831942&tab=artifacts#/follower-reads/survival=region/locality=regional)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Afollower-reads%2Fsurvival%3Dregion%2Flocality%3Dregional.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by nvb**
Fixes #62855.

This commit adds a stage to the follower-reads suite of tests to wait
for replicas to be in the correct regions before starting to apply and
measure load. Previously, the test was waiting for the correct count and
type of replicas to be present, but not for them to be in the correct
locations.

This also replaces the slow query logging added in #63319 with slow
query tracing, which was the original intention.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Without this, the test was failing about once every 20 runs. With it, I haven't seen a failure in over 200.

**Review by aayushshah15 — APPROVED** [review]
:lgtm_strong:  

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63353#-:-MXo4MXb3xMfEHsnXRvU:b-yncq5v)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/cmd/roachtest/follower_reads.go, line 192 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63353#-MXo4FSC946L8MLBiDEp:-MXo4FSC946L8MLBiDEq:b-1ruk28) ([raw file](https://github.com/cockroachdb/cockroach/blob/5317139e0d18227a1d4d2c50be66f2b17e6b115b/pkg/cmd/roachtest/follower_reads.go#L192)):*
> ```Go
> 		}
> 		if !ok {
> 			return errors.Newf("rebalancing not complete, found %d voters and %d non_voters", voters, nonVoters)
> ```

`s/rebalancing/upreplication`?
___
*[pkg/cmd/roachtest/follower_reads.go, line 200 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63353#-MXo4aX88NKytj3b1ubb:-MXo4aX88NKytj3b1ubc:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5317139e0d18227a1d4d2c50be66f2b17e6b115b/pkg/cmd/roachtest/follower_reads.go#L200)):*
> ```Go
> 		const q2 = `
> 			SELECT
> 				count(distinct substring(unnest(replica_localities), 'region=([^,]*)'))
> ```

:+1:

**Review by nvb — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63353#-:-MXoz2SX7jh7aL5dK8iT:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15)

___
*[pkg/cmd/roachtest/follower_reads.go, line 192 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63353#-MXo4FSC946L8MLBiDEp:-MXoz-hz1nS5dqZMzguz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5317139e0d18227a1d4d2c50be66f2b17e6b115b/pkg/cmd/roachtest/follower_reads.go#L192)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

`s/rebalancing/upreplication`?
</blockquote></details>

Done.

**Comment by nvanbenschoten** [comment]
Flaked on https://github.com/cockroachdb/cockroach/issues/60682.

bors r+

**Pull request merged**
