### PR TITLE
roachprod: change geo flag to group nodes in a region better

### PR DESCRIPTION
**Pull request by m-schneider**
Currently when using the --geo flag with --clouds=aws, we round robin
regions and availibility zones for AWS. This results in a cluster where
we have nodes in a giving region scattered.

This PR clusters zones in a regions so now giving 3 regions. The first x
nodes will all be in region 1 the next x in region 2 and the remainder
in region 3.

Release note: None

### CODE REVIEW

**Comment by m-schneider** [comment]
___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 221 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32491#-LRi5J4L4B3ael5tYx25:-LRi5J4L4B3ael5tYx26:bbx567j) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3fdc7bf039ca7e609ce97f24bbe05f7c919db30/pkg/cmd/roachprod/vm/aws/aws.go#L221)):*
> ```Go
> 			}
> 			capName := names[j+firstNode]
> 			placement := zones[j%len(zones)]
> ```

This is still preserving the multiple availability zone per region logic.

**Review by nvb — COMMENTED** [review]
It looks like we have almost identical logic in `gce.Provider.Create`. Can we just copy that? Or better yet, can it be abstracted into some utility function?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32491#-:-LRn1S9A5lX1uEFlpGHX:b-xtz2a1)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by m-schneider — COMMENTED** [review]
This is the same as that except cleaner and takes the extra variable of availability zones into account. I looked at the GCE function and it's very GCE specific, it wouldn't be very straightforward to pull out a utility function.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32491#-:-LRqx6xr7idRi9XXWB6d:b-8kgfbf)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 219 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32491#-LRr0jj-ByPUY-0kyMPC:-LRr0jj-ByPUY-0kyMPD:bmhpyp4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae74852d64ea29c9f3c9d299be73a49b3a13f0a1/pkg/cmd/roachprod/vm/aws/aws.go#L219)):*
> ```Go
> 		}
> 		nodesPerRegion = int(math.Ceil(float64(nodeCount-node) / float64(len(regions)-i)))
> 		availabilityZone := rand.Int31n(int32(len(zones)))
> ```

We're choosing a random availability zone now, but it will be consistent for a given region.

**Review by nvb — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32491#-:-LSCGEKqAjf-8bpXJyR3:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 219 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32491#-LRr0jj-ByPUY-0kyMPC:-LSCGG576JMo9bwxzR_n:b-eu34es) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae74852d64ea29c9f3c9d299be73a49b3a13f0a1/pkg/cmd/roachprod/vm/aws/aws.go#L219)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

We're choosing a random availability zone now, but it will be consistent for a given region.
</blockquote></details>

Add this to the comment right above.

**Comment by nvanbenschoten** [comment]
Thanks for finding and fixing this!

**Review by m-schneider — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32491)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 219 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32491#-LRr0jj-ByPUY-0kyMPC:-LSFe9543f3Eh_nQM1Rl:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae74852d64ea29c9f3c9d299be73a49b3a13f0a1/pkg/cmd/roachprod/vm/aws/aws.go#L219)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Add this to the comment right above.
</blockquote></details>

Done!

**Comment by m-schneider** [comment]
Yep, I got it.

**Comment by benesch** [comment]
Bors got stuck on this.

bors r+

**Comment by m-schneider** [comment]
Thanks!

**Pull request merged**
