### PR TITLE
Backport20.1 47728 49234

### PR DESCRIPTION
**Pull request by rohany**
Backport 1/2 commits from #47728.
Backport 1/1 commits from #49234.

/cc @cockroachdb/release

### CODE REVIEW

**Comment by rohany** [comment]
the backport script wasn't cooperating, so I did it by hand.

**Review by jordanlewis — APPROVED** [review]
Weird, ok. Thanks for the very quick fix! :lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49238#-:-M7eRuZn-4JYITrGKUV5:boquiwm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49238#-:-M7eS3l70rOjSjcHUn0V:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by rohany** [comment]
tftrs!

**Pull request merged**
