### PR TITLE
config,storage: remove system config checksum

### PR DESCRIPTION
**Pull request by tamird**
This construction seems nonsensical; the entire structure is available
in gossip; we can just compare it directly.

Extracted from #13011.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13125)

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm: 

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13125#-:-KbH9jYsJs_kKB8QnUSm:bg7igkv)*

**Comment by mberhault** [comment]
LGTM.

Yeah, not sure why we were using a hash, I only moved that around when I poked at that code a while back.

**Comment by a-robinson** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/config/config.go, line 191 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13125#-KbHBwffCvwkcLwk5uPU:-KbHBwffCvwkcLwk5uPV:b2sw6d9) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80c1ecee6652aa68f07e02d07f608e196bd82c8/pkg/config/config.go#L191)):*
> ```Go
> }
> 
> // Equal checks for equality.
> ```

Is there any sort of guarantee that these values are sorted? If not, I'd at least comment the requirement here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13125#-:-KbHCval-xqZM8lt-UP2:bnfp4nl)*

**Comment by tamird** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/config/config.go, line 191 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13125#-KbHBwffCvwkcLwk5uPU:-KbHJMehalMFv6XW-IEr:b-jah6ri) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80c1ecee6652aa68f07e02d07f608e196bd82c8/pkg/config/config.go#L191)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Is there any sort of guarantee that these values are sorted? If not, I'd at least comment the requirement here.
</blockquote></details>

Done.

They should always be sorted since they come out of kv scan operations.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13125)*

**Comment by tamird** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/config/config.go, line 191 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13125#-KbHBwffCvwkcLwk5uPU:-KbHLtvyu-qIj7w96Uzy:b-jgt8ln) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80c1ecee6652aa68f07e02d07f608e196bd82c8/pkg/config/config.go#L191)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Done.

They should always be sorted since they come out of kv scan operations.
</blockquote></details>

Note that the old `Hash()` code also assumed sortedness.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13125)*

**Pull request merged**
