### PR TITLE
testutils/testcluster: automatically wait-for-full-replication

### PR DESCRIPTION
**Pull request by petermattis**
Closes #9624

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10237)

### CODE REVIEW

**Comment by tschottdorf** [comment]
How long does `WaitForFullReplication` take (remember it being slow) and why is it a good idea to always wait for full replication? I think that lets us miss out on a lot of edge case goodness in tests.

**Comment by tamird** [comment]
:lgtm_strong: 

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/testutils/testcluster/testcluster.go, line 182 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10237#-KV1CylasdpUWw2WzAng:-KV1CylbRN0OagYRnev0:bw55niz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b83b0fb0395905363c5e0ebeac19b87f0b5ffe6/pkg/testutils/testcluster/testcluster.go#L182)):*
> ```Go
> 	tc.waitForStores(t)
> 
> 	if args.ReplicationMode == base.ReplicationAuto && nodes >= 3 {
> ```

why does this need to check the number of nodes? I think `Metrics().ReplicaAllocatorAddCount` is zero if there are no suitable candidates.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10237#-:-KV1DAP1ZbD4pIgQRjrh:b-uwkowd)*

**Comment by tschottdorf** [comment]
According to @tamird the original PR was motivated by the TODO in https://github.com/cockroachdb/cockroach/pull/9624/files#diff-b0f627df831bb9b0d791d4ecefc808b7R181:

> // TODO(tamird): consider removing this when #8081 is addressed.

This PR certainly doesn't do that, it goes full-on all the way and is likely to let us forget about whatever is left of that issue (or future ones like it).

**Comment by petermattis** [comment]
I ran `go test -count 1000 -v -run TestBasicAutoReplication` and here are the timings:

```
   2 0.18s
   1 0.19s
   2 0.20s
   7 0.21s
  22 0.22s
  19 0.23s
  39 0.24s
 148 0.25s
 317 0.26s
 298 0.27s
 124 0.28s
  20 0.29s
   1 0.30s
```

I'm not sure what the issue is in #8081. `TestCluster.waitForFullReplication` seems reliable and fast for me. (Currently running stress, so perhaps I'll eat my words in a few minutes).

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/testutils/testcluster/testcluster.go, line 182 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10237#-KV1CylasdpUWw2WzAng:-KV1OpsRTElf0kHYa5ZW:bj5d8nf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b83b0fb0395905363c5e0ebeac19b87f0b5ffe6/pkg/testutils/testcluster/testcluster.go#L182)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> why does this need to check the number of nodes? I think `Metrics().ReplicaAllocatorAddCount` is zero if there are no suitable candidates.
</details>
`ReplicaAllocatorAddCount` reflects necessary replication work to be done, even if there are no suitable candidates. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10237#-:-KV1NUFmguMoRz1b2sx9:bs4bw9r)*

**Comment by petermattis** [comment]
I audited the uses of `StartTestCluster`. Unless I missed something, there was exactly one use (`TestBackupRestoreOnce`) that created a test cluster with `ReplicationAuto` that didn't call `WaitForFullReplication`. And I'm pretty sure that one case was an oversight (or, at least, unintentional).

I also ran`make stress PKG=./testutils/testcluster/ TESTS=TestBasicAutoReplication` for 7.5m without any errors.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10237#-:-KV1R76zmkbrq-PMwC1O:b91n7xm)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/testutils/testcluster/testcluster.go, line 182 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10237#-KV1CylasdpUWw2WzAng:-KV1_ORHGVGnPkERCnm0:bm3gif3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b83b0fb0395905363c5e0ebeac19b87f0b5ffe6/pkg/testutils/testcluster/testcluster.go#L182)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `ReplicaAllocatorAddCount` reflects necessary replication work to be done, even if there are no suitable candidates. 
</details>
I see. Still, having this set to `3` seems fragile. A comment that this hardcoded value may be incorrect would put my mind at ease.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10237)*

**Comment by petermattis** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/testutils/testcluster/testcluster.go, line 182 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10237#-KV1CylasdpUWw2WzAng:-KV1cqPhVsDed9iImvRD:b-7dmbhs) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b83b0fb0395905363c5e0ebeac19b87f0b5ffe6/pkg/testutils/testcluster/testcluster.go#L182)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I see. Still, having this set to `3` seems fragile. A comment that this hardcoded value may be incorrect would put my mind at ease.
</details>
Added a `TODO`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10237)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10237)*

**Pull request merged**
