### PR TITLE
all: rename "leader lease" to "range lease"

### PR DESCRIPTION
**Pull request by tbg**
A somewhat massive undertaking. I'm sure a few slipped out from under me but most `git grep` variations of `lease` and `leader` look promising and since such a patch set goes stale quickly, the weekend might be a good time to get it in.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7718)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

I think this is a definite improvement to clarity. 

---

Reviewed 61 of 63 files at r1, 4 of 4 files at r2.
Review status: 54 of 63 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[docs/RFCS/raft_consistency_checker.md, line 22 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHCL3d1M0hT87ohlyJ:-KMHCL3d1M0hT87ohlyK:1701849917) ([raw file](https://github.com/cockroachdb/cockroach/blob/13f0b2a925c11a57f9093c54be50cbbaadc6f1c7/docs/RFCS/raft_consistency_checker.md#L22)):*
> ```Markdown
> # Detailed design
> 
> The proposal is for each range replica lease holder to periodically collect a SHA of
> ```

`s/replica lease/lease/g`?

---

*[keys/keys.go, line 185 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHCpk-XOR1ZVJwsLcj:-KMHCpk0E62FiXl1YzMU:-36080675) ([raw file](https://github.com/cockroachdb/cockroach/blob/13f0b2a925c11a57f9093c54be50cbbaadc6f1c7/keys/keys.go#L185)):*
> ```Go
> }
> 
> // RangeLeaseKey returns a system-local key for a range range lease.
> ```

`s/range lease/lease/g`

---

*[kv/leader_cache.go, line 27 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHExlTuZfdt-5k-iwR:-KMHExlTuZfdt-5k-iwS:-1775059518) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed7e869e261588a529d54c82abd17f763e40dc15/kv/leader_cache.go#L27)):*
> ```Go
> 
> // A leaseholderCache is a cache of replica descriptors keyed by range ID.
> type leaseholderCache struct {
> ```

Should the file be renamed `leaseholder_cache.go`?

---

*[roachpb/errors.proto, line 34 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHD_4KgP3ThTEQzcvG:-KMHD_4LfsNSvVer67lj:-355505054) ([raw file](https://github.com/cockroachdb/cockroach/blob/13f0b2a925c11a57f9093c54be50cbbaadc6f1c7/roachpb/errors.proto#L34)):*
> ```protobuf
> // A NotLeaseholderError indicates that the current range is not the lease
> // holder. If the lease holder is known, its Replica is set in the error.
> message NotLeaseholderError {
> ```

`s/Leaseholder/LeaseHolder/g`

---

*[roachpb/errors.proto, line 36 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHDcrvMkFkY0YXSv5o:-KMHDcrvMkFkY0YXSv5p:-1779524809) ([raw file](https://github.com/cockroachdb/cockroach/blob/13f0b2a925c11a57f9093c54be50cbbaadc6f1c7/roachpb/errors.proto#L36)):*
> ```protobuf
> message NotLeaseholderError {
>   optional ReplicaDescriptor replica = 1;
>   optional ReplicaDescriptor leaseholder = 2;
> ```

`s/leaseholder/lease_holder/g`

---

*[roachpb/errors.proto, line 199 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHDii63XGJn09IltxR:-KMHDii63XGJn09IltxS:-1779524809) ([raw file](https://github.com/cockroachdb/cockroach/blob/13f0b2a925c11a57f9093c54be50cbbaadc6f1c7/roachpb/errors.proto#L199)):*
> ```protobuf
>   option (gogoproto.onlyone) = true;
> 
>   optional NotLeaseholderError not_leaseholder = 1;
> ```

`s/leaseholder/lease_holder/g`

---

*[storage/queue.go, line 441 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHE7jYVBRKQNQOPYkY:-KMHE7jZnNzj_WJ7xX9X:-33602898) ([raw file](https://github.com/cockroachdb/cockroach/blob/13f0b2a925c11a57f9093c54be50cbbaadc6f1c7/storage/queue.go#L441)):*
> ```Go
> 	defer sp.Finish()
> 
> 	// If the queue requires a replica to have the range range lease in
> ```

`s/range range/range/` (you should do a search for `range range` to catch other instances)

---

*[docs/RFCS/leader_evaluated_raft.md, line 1 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMH8diisETRwMwHz6Sk:-KMH8diisETRwMwHz6Sl:-970026955) ([raw file](https://github.com/cockroachdb/cockroach/blob/13f0b2a925c11a57f9093c54be50cbbaadc6f1c7/docs/RFCS/leader_evaluated_raft.md#L1)):*
> ```Markdown
> - Feature Name: leader_evaluated_raft
> ```

`s/leader/leaseholder/g`

The name still feels confusing. The range lease holder isn't evaluating raft, it's evaluating the operations in a `BatchRequest`. Perhaps `leaserholder_evaluated_kv`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-:-KMHF2DZUv_m5et1W1Hn:-1706471374)*

**Comment by bdarnell** [comment]
:lgtm:

Changing "leader lease" to "range lease" is a definite improvement. I'm less sure about the changes from "leader" to "lease holder", but I guess it's still better than before. 

---

Review status: 54 of 63 files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

*[docs/RFCS/leaseholder_evaluated_raft.md, line 1 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMH8diisETRwMwHz6Sk:-KMHguuA-blXuZ4saTED:-842158757) ([raw file](https://github.com/cockroachdb/cockroach/blob/13f0b2a925c11a57f9093c54be50cbbaadc6f1c7/docs/RFCS/leaseholder_evaluated_raft.md#L1)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `s/leader/leaseholder/g`
> 
> The name still feels confusing. The range lease holder isn't evaluating raft, it's evaluating the operations in a `BatchRequest`. Perhaps `leaserholder_evaluated_kv`?
</details>
`lease_holder` is two words. `+1` to  making the suffix `kv` instead of `raft`, although `lease_holder_evaluated_kv` is a mouthful. `proposer_evaluated_kv`? 

---

*[docs/RFCS/range_leases.md, line 11 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHhtU0-i2AH5sL1eCO:-KMHhtU0-i2AH5sL1eCP:-664506875) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed7e869e261588a529d54c82abd17f763e40dc15/docs/RFCS/range_leases.md#L11)):*
> ```Markdown
> # Summary
> 
> This is a proposal to replace the current per-range range lease
> ```

s/range//? Not sure whether this is redundant or not.

---

*[docs/RFCS/range_leases.md, line 51 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHhxm_5EX72UDLlZI9:-KMHhxm_5EX72UDLlZIA:-499318459) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed7e869e261588a529d54c82abd17f763e40dc15/docs/RFCS/range_leases.md#L51)):*
> ```Markdown
> APIs). This table is special in several respects: it is gossipped, and
> leases within its keyspace (and all ranges that precede it, including
> meta1 and meta2) use the current, per-range range lease mechanism to
> ```

Ditto

---

*[docs/RFCS/rebalancing_v2.md, line 25 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHi8hSVymqN-2Jyt4o:-KMHi8hSVymqN-2Jyt4p:-343137197) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed7e869e261588a529d54c82abd17f763e40dc15/docs/RFCS/rebalancing_v2.md#L25)):*
> ```Markdown
>   - [Other enhancements to distributed allocation](#other-enhancements-to-distributed-allocation)
>   - [Centralized allocation strategy](#centralized-allocation-strategy)
>     - [Leader lease acquisition](#lease holder-lease-acquisition)
> ```

This file is tricky. Many (but not all) of the uses of "leader lease" in this file refer to a proposed allocator lease, not the range lease. 

---

*[kv/dist_sender.go, line 56 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHis8sQRx_-eHl4Cxu:-KMHis8t1wZWfO4W2UWg:-1243493362) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed7e869e261588a529d54c82abd17f763e40dc15/kv/dist_sender.go#L56)):*
> ```Go
> 	defaultRangeLookupMaxRanges = 8
> 	// The default size of the lease holder cache.
> 	defaultLeaderCacheSize = 1 << 16
> ```

s/Leader/LeaseHolder/

---

*[kv/dist_sender.go, line 102 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHiuTqn-niWGCQyXNJ:-KMHiuTrCh6osR-aUaRb:148610228) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed7e869e261588a529d54c82abd17f763e40dc15/kv/dist_sender.go#L102)):*
> ```Go
> 	rangeCache           *rangeDescriptorCache
> 	rangeLookupMaxRanges int32
> 	// leaseholderCache caches range lease holders by range ID.
> ```

s/leaseholder/leaseHolder/g

---

*[roachpb/api.proto, line 820 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHjqpdsj8sxEo4Fddw:-KMHjqpdsj8sxEo4Fddx:458397992) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed7e869e261588a529d54c82abd17f763e40dc15/roachpb/api.proto#L820)):*
> ```protobuf
>   // applied index, which is fraught with complexity due to the need to predict
>   // exactly the log position at which a command will apply, even when the Raft
>   // lease holder is not colocated with the lease holder (which usually proposes all
> ```

This one really meant "leader".

---

*[server/serverpb/admin.proto, line 266 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHkGCyblZumZBR0BM1:-KMHkGCyblZumZBR0BM2:-1129488307) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed7e869e261588a529d54c82abd17f763e40dc15/server/serverpb/admin.proto#L266)):*
> ```protobuf
>     // LEADERSHIP instructs the server to gracefully let all its Replicas'
>     // range leases expire.
>     LEADERSHIP = 1;
> ```

s/LEADERSHIP/LEASES/

---

*[storage/replica_command.go, line 1994 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHkwlO63qcHz5C9pQJ:-KMHkwlPUD-LbGUZRg_8:-1243493362) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed7e869e261588a529d54c82abd17f763e40dc15/storage/replica_command.go#L1994)):*
> ```Go
> type ReplicaSnapshotDiff struct {
> 	// Leader is set to true of this k:v pair is only present on the lease holder.
> 	Leader    bool
> ```

s/Leader/LeaseHolder/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-:-KMHlgPuJ4y6VMvzXMRD:730360888)*

**Comment by tschottdorf** [comment]
Review status: 38 of 69 files reviewed at latest revision, 16 unresolved discussions, some commit checks pending.

---

*[docs/RFCS/raft_consistency_checker.md, line 22 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHCL3d1M0hT87ohlyJ:-KMJijAC0h6ekY9xgHvP:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/13f0b2a925c11a57f9093c54be50cbbaadc6f1c7/docs/RFCS/raft_consistency_checker.md#L22)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `s/replica lease/lease/g`?
</details>
Done.

---

*[docs/RFCS/range_leases.md, line 11 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHhtU0-i2AH5sL1eCO:-KMJipz-beGCeSohiPvd:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed7e869e261588a529d54c82abd17f763e40dc15/docs/RFCS/range_leases.md#L11)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> s/range//? Not sure whether this is redundant or not.
</details>
Done.

---

*[docs/RFCS/range_leases.md, line 51 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHhxm_5EX72UDLlZI9:-KMJiuZoemviEro7Fgj0:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed7e869e261588a529d54c82abd17f763e40dc15/docs/RFCS/range_leases.md#L51)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Ditto
</details>
Done.

---

*[docs/RFCS/rebalancing_v2.md, line 25 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHi8hSVymqN-2Jyt4o:-KMK1A3qHxnpz_cKDX5h:649358584) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed7e869e261588a529d54c82abd17f763e40dc15/docs/RFCS/rebalancing_v2.md#L25)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> This file is tricky. Many (but not all) of the uses of "leader lease" in this file refer to a proposed allocator lease, not the range lease. 
</details>
Done (introduced "allocator lease").

---

*[keys/keys.go, line 185 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHCpk-XOR1ZVJwsLcj:-KMK1-Qh5dYItD3adM18:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/13f0b2a925c11a57f9093c54be50cbbaadc6f1c7/keys/keys.go#L185)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `s/range lease/lease/g`
</details>
Done.

---

*[kv/dist_sender.go, line 56 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHis8sQRx_-eHl4Cxu:-KMK10-AVNdSUUghCX8W:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed7e869e261588a529d54c82abd17f763e40dc15/kv/dist_sender.go#L56)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> s/Leader/LeaseHolder/
</details>
Done.

---

*[kv/dist_sender.go, line 102 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHiuTqn-niWGCQyXNJ:-KMK10TB2uPGwZgLo8Rb:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed7e869e261588a529d54c82abd17f763e40dc15/kv/dist_sender.go#L102)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> s/leaseholder/leaseHolder/g
</details>
Done.

---

*[kv/leaseholder_cache.go, line 27 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHExlTuZfdt-5k-iwR:-KMK119IS9VKOaZGYivo:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed7e869e261588a529d54c82abd17f763e40dc15/kv/leaseholder_cache.go#L27)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Should the file be renamed `leaseholder_cache.go`?
</details>
Done.

---

*[roachpb/api.proto, line 820 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHjqpdsj8sxEo4Fddw:-KMK124OMSTougMKdTB5:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed7e869e261588a529d54c82abd17f763e40dc15/roachpb/api.proto#L820)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> This one really meant "leader".
</details>
Done.

---

*[roachpb/errors.proto, line 34 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHD_4KgP3ThTEQzcvG:-KMK12Xtld29we72zhCd:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/13f0b2a925c11a57f9093c54be50cbbaadc6f1c7/roachpb/errors.proto#L34)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `s/Leaseholder/LeaseHolder/g`
</details>
Done.

---

*[roachpb/errors.proto, line 36 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHDcrvMkFkY0YXSv5o:-KMK140foNUIrJNSDLl_:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/13f0b2a925c11a57f9093c54be50cbbaadc6f1c7/roachpb/errors.proto#L36)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `s/leaseholder/lease_holder/g`
</details>
Done.

---

*[roachpb/errors.proto, line 199 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHDii63XGJn09IltxR:-KMK158zg56158v2tHAG:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/13f0b2a925c11a57f9093c54be50cbbaadc6f1c7/roachpb/errors.proto#L199)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `s/leaseholder/lease_holder/g`
</details>
Done.

---

*[server/serverpb/admin.proto, line 266 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHkGCyblZumZBR0BM1:-KMK16uxcPbgZYSZAlhN:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed7e869e261588a529d54c82abd17f763e40dc15/server/serverpb/admin.proto#L266)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> s/LEADERSHIP/LEASES/
</details>
Done.

---

*[storage/queue.go, line 441 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHE7jYVBRKQNQOPYkY:-KMK17TRBGqfoDWEXW-v:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/13f0b2a925c11a57f9093c54be50cbbaadc6f1c7/storage/queue.go#L441)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `s/range range/range/` (you should do a search for `range range` to catch other instances)
</details>
Done.

---

*[storage/replica_command.go, line 1994 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHkwlO63qcHz5C9pQJ:-KMK181z04MQwZ-_9jVB:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed7e869e261588a529d54c82abd17f763e40dc15/storage/replica_command.go#L1994)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> s/Leader/LeaseHolder/
</details>
Done.

---

*[docs/RFCS/leaseholder_evaluated_raft.md, line 1 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMH8diisETRwMwHz6Sk:-KMJibQ5lKEXzOuJR-Xq:-762507048) ([raw file](https://github.com/cockroachdb/cockroach/blob/13f0b2a925c11a57f9093c54be50cbbaadc6f1c7/docs/RFCS/leaseholder_evaluated_raft.md#L1)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> `lease_holder` is two words. `+1` to  making the suffix `kv` instead of `raft`, although `lease_holder_evaluated_kv` is a mouthful. `proposer_evaluated_kv`? 
</details>
Good idea, change to `proposer evaluated kv`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718)*

**Comment by tschottdorf** [comment]
Thanks for the (what must have been horrible) reviews. Addressed the
comments. Will merge in +12h unless anything substantial is brought up.

On Sat, Jul 9, 2016 at 11:09 PM Ben Darnell <notifications@github.com>
wrote:

> [image: :lgtm:]
> <https://camo.githubusercontent.com/41b3ec3419116e3b3f84507ad965646ce4ce1f0c/68747470733a2f2f72657669657761626c652e696f2f6c67746d2e706e67>
>
> Changing "leader lease" to "range lease" is a definite improvement. I'm
> less sure about the changes from "leader" to "lease holder", but I guess
> it's still better than before.
> ------------------------------
>
> Review status: 54 of 63 files reviewed at latest revision, 16 unresolved
> discussions, some commit checks failed.
> ------------------------------
>
> *docs/RFCS/leaseholder_evaluated_raft.md, line 1 [r1]
> <https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMH8diisETRwMwHz6Sk:-KMHguuA-blXuZ4saTED:-842158757>
> (raw file
> <https://github.com/cockroachdb/cockroach/blob/13f0b2a925c11a57f9093c54be50cbbaadc6f1c7/docs/RFCS/leaseholder_evaluated_raft.md#L1>):*
> *Previously, petermattis (Peter Mattis) wrote…*
>
> s/leader/leaseholder/g
>
> The name still feels confusing. The range lease holder isn't evaluating
> raft, it's evaluating the operations in a BatchRequest. Perhaps
> leaserholder_evaluated_kv?
>
>
> lease_holder is two words. +1 to making the suffix kv instead of raft,
> although lease_holder_evaluated_kv is a mouthful. proposer_evaluated_kv?
>
> ------------------------------
>
> *docs/RFCS/range_leases.md, line 11 [r3]
> <https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHhtU0-i2AH5sL1eCO:-KMHhtU0-i2AH5sL1eCP:-664506875>
> (raw file
> <https://github.com/cockroachdb/cockroach/blob/ed7e869e261588a529d54c82abd17f763e40dc15/docs/RFCS/range_leases.md#L11>):*
>
> # Summary
>
> This is a proposal to replace the current per-range range lease
>
> s/range//? Not sure whether this is redundant or not.
> ------------------------------
>
> *docs/RFCS/range_leases.md, line 51 [r3]
> <https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHhxm_5EX72UDLlZI9:-KMHhxm_5EX72UDLlZIA:-499318459>
> (raw file
> <https://github.com/cockroachdb/cockroach/blob/ed7e869e261588a529d54c82abd17f763e40dc15/docs/RFCS/range_leases.md#L51>):*
>
> APIs). This table is special in several respects: it is gossipped, and
> leases within its keyspace (and all ranges that precede it, including
> meta1 and meta2) use the current, per-range range lease mechanism to
>
> Ditto
> ------------------------------
>
> *docs/RFCS/rebalancing_v2.md, line 25 [r3]
> <https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHi8hSVymqN-2Jyt4o:-KMHi8hSVymqN-2Jyt4p:-343137197>
> (raw file
> <https://github.com/cockroachdb/cockroach/blob/ed7e869e261588a529d54c82abd17f763e40dc15/docs/RFCS/rebalancing_v2.md#L25>):*
>
>   - [Other enhancements to distributed allocation](#other-enhancements-to-distributed-allocation)
>   - [Centralized allocation strategy](#centralized-allocation-strategy)
>     - [Leader lease acquisition](#lease holder-lease-acquisition)
>
> This file is tricky. Many (but not all) of the uses of "leader lease" in
> this file refer to a proposed allocator lease, not the range lease.
> ------------------------------
>
> *kv/dist_sender.go, line 56 [r3]
> <https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHis8sQRx_-eHl4Cxu:-KMHis8t1wZWfO4W2UWg:-1243493362>
> (raw file
> <https://github.com/cockroachdb/cockroach/blob/ed7e869e261588a529d54c82abd17f763e40dc15/kv/dist_sender.go#L56>):*
>
>   defaultRangeLookupMaxRanges = 8
>   // The default size of the lease holder cache.
>   defaultLeaderCacheSize = 1 << 16
>
> s/Leader/LeaseHolder/
> ------------------------------
>
> *kv/dist_sender.go, line 102 [r3]
> <https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHiuTqn-niWGCQyXNJ:-KMHiuTrCh6osR-aUaRb:148610228>
> (raw file
> <https://github.com/cockroachdb/cockroach/blob/ed7e869e261588a529d54c82abd17f763e40dc15/kv/dist_sender.go#L102>):*
>
>   rangeCache           *rangeDescriptorCache
>   rangeLookupMaxRanges int32
>   // leaseholderCache caches range lease holders by range ID.
>
> s/leaseholder/leaseHolder/g
> ------------------------------
>
> *roachpb/api.proto, line 820 [r3]
> <https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHjqpdsj8sxEo4Fddw:-KMHjqpdsj8sxEo4Fddx:458397992>
> (raw file
> <https://github.com/cockroachdb/cockroach/blob/ed7e869e261588a529d54c82abd17f763e40dc15/roachpb/api.proto#L820>):*
>
>   // applied index, which is fraught with complexity due to the need to predict
>   // exactly the log position at which a command will apply, even when the Raft
>   // lease holder is not colocated with the lease holder (which usually proposes all
>
> This one really meant "leader".
> ------------------------------
>
> *server/serverpb/admin.proto, line 266 [r3]
> <https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHkGCyblZumZBR0BM1:-KMHkGCyblZumZBR0BM2:-1129488307>
> (raw file
> <https://github.com/cockroachdb/cockroach/blob/ed7e869e261588a529d54c82abd17f763e40dc15/server/serverpb/admin.proto#L266>):*
>
>     // LEADERSHIP instructs the server to gracefully let all its Replicas'
>     // range leases expire.
>     LEADERSHIP = 1;
>
> s/LEADERSHIP/LEASES/
> ------------------------------
>
> *storage/replica_command.go, line 1994 [r3]
> <https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-KMHkwlO63qcHz5C9pQJ:-KMHkwlPUD-LbGUZRg_8:-1243493362>
> (raw file
> <https://github.com/cockroachdb/cockroach/blob/ed7e869e261588a529d54c82abd17f763e40dc15/storage/replica_command.go#L1994>):*
>
> type ReplicaSnapshotDiff struct {
>   // Leader is set to true of this k:v pair is only present on the lease holder.
>   Leader    bool
>
> s/Leader/LeaseHolder/
> ------------------------------
>
> *Comments from Reviewable
> <https://reviewable.io:443/reviews/cockroachdb/cockroach/7718#-:-KMHlgPuJ4y6VMvzXMRD:730360888>*
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/7718#issuecomment-231568174>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE135OzaAyuztSvMQod1-qxKsvhsbqebks5qUGJ3gaJpZM4JIuN->
> .
>
-- 

-- Tobias

**Comment by petermattis** [comment]
Reviewed 1 of 5 files at r2, 8 of 11 files at r3.
Review status: 38 of 71 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7718)*

**Pull request merged**
