### PR TITLE
exec: add date and decimal types

### PR DESCRIPTION
**Pull request by jordanlewis**
Date is just an Int64, so no work to do there.

Decimal maps to `apd.Decimal`. It's a bit unfortunate as I don't think the columnar representation will help `apd.Decimal` operations as much as they would native datatypes, but not sure what else we can do.

### CODE REVIEW

**Review by solongordon — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31940)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by jordanlewis** [comment]
I was thinking I'd merge this after #31892, to prevent that PR from having to get rebased too many times.

**Comment by solongordon** [comment]
Sounds good. I'm rebasing that and addressing review comments imminently.

**Comment by jordanlewis** [comment]
PTAL, I added some new functions to facilitate decoding a Decimal into a pre-existing `*apd.Decimal`, besides that it's the same.

**Review by madelynnblue — APPROVED** [review]

**Review by solongordon — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31940#-:-LQ5_6vyAhj7TlNPkCmk:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by jordanlewis** [comment]
TFTRs!

bors r+

**Pull request merged**
