### PR TITLE
kvserver: make mergeQueue and rebalancing related cluster settings `SystemOnly`

### PR DESCRIPTION
**Pull request by aayushshah15**
Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]

**Comment by tbg** [comment]
This wouldn't have any effect anyway right? Funny that tenants even get to see this setting.

**Comment by RaduBerinde** [comment]
Does tenant code ever need to look at this value? If not, it should be SystemOnly

**Comment by RaduBerinde** [comment]
We should audit all kv server side settings, most of them should be SystemOnly (meaning they are invisible to tenants and not usable from tenant code).

**Review by aayushshah15 — COMMENTED** [review]
Makes sense, changed them to `SystemOnly`. I also audited (and fixed) at least the rebalancing related cluster settings.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76119#-:-MvFKXh32UG6hUZwlKd5:bec03q7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76119#-:-MvFbRIn72hbVL-qaUG5:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15)

**Comment by aayushshah15** [comment]
TFTRs!

bors r+

**Pull request merged**
