### PR TITLE
sql: add column_comment to information_schema.columns

### LINKED ISSUE #44484: sql: add column_comment to information_schema.columns
**Is your feature request related to a problem? Please describe.**
When querying columns from `information_schema.columns` the comment applied to a column does not show. If I want to be able to perform queries against column comments I have to use `SHOW COLUMNS FROM <table> WITH COMMENT;` which does not support sub-querying. For example, `SELECT comment FROM (SHOW COLUMNS FROM <table> WITH COMMENT)` results in an error

**Describe the solution you'd like**
When I run `SELECT * FROM information_schema.columns WHERE table_name = $1`, I can see a `column_comment` field.

**Additional context**
An example where we might use this is for GDPR compliance. An idea I had was to label columns as personally identifiable information. When I receive a "right of erasure" GDPR request, I can generically obfuscate fields labelled as PII based on a primary key without having to just hard delete rows and break relationships.

This can be useful as in large instances with many databases PII can be distributed across many tables

### PR DESCRIPTION
**Pull request by mosquito2333**
When run SELECT * FROM information_schema.columns WHERE table_name = $1,
you can see a column_comment field.
We can also use SHOW COLUMNS FROM tb WITH COMMENT;
For example,SELECT comment FROM [SHOW COLUMNS FROM tb WITH COMMENT]

Closes #44484

Release note: None

### CODE REVIEW

**Comment by mosquito2333** [comment]
> Thank you for updating your pull request.
> 
> My owl senses detect your PR is good for review. Please keep an eye out for any test failures in CI.
> 
> 🦉 Hoot! I am a [Blathers](https://github.com/apps/blathers-crl), a bot for [CockroachDB](https://github.com/cockroachdb). My owner is [otan](https://github.com/otan).

Thanks!

**Comment by mosquito2333** [comment]
Thanks!

**Comment by mosquito2333** [comment]
> Thank you for updating your pull request.
> 
> My owl senses detect your PR is good for review. Please keep an eye out for any test failures in CI.
> 
> 🦉 Hoot! I am a [Blathers](https://github.com/apps/blathers-crl), a bot for [CockroachDB](https://github.com/cockroachdb). My owner is [otan](https://github.com/otan).

Thanks!

**Review by arulajmani — CHANGES_REQUESTED** [review]
Thanks for your contribution @mosquito2333! I left some minor comments, but otherwise things look good! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58695#-:-MQwVORk46J3w57BfMy3:b-t4k8fn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mosquito2333)

___
*[pkg/sql/information_schema.go, line 444 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58695#-MQwWdht6GCEkZnAXZtt:-MQwWdht6GCEkZnAXZtu:b-cv0j42) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a7e1d0016596c061a6866b840f17d88f3125731/pkg/sql/information_schema.go#L444)):*
> ```Go
> 				//Search the comment belonging to current column from collations,using table id and column id
> 				var description string
> 				for _, comment := range comments {
> ```

Iterating over all the tables which have comments here seems rather inefficient. Could we use a map here instead, keyed by the table ID? 
___
*[pkg/sql/information_schema.go, line 2218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58695#-MQwWAKN8vB_iRuS0QXx:-MQwWAKN8vB_iRuS0QXy:b3tzvu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a7e1d0016596c061a6866b840f17d88f3125731/pkg/sql/information_schema.go#L2218)):*
> ```Go
> // A comment is represented as a datum row, containing object id (table id),
> // sub id (column id), comment text.
> func getColumnComments(ctx context.Context, p *planner) ([]tree.Datums, error) {
> ```

I found this function https://github.com/cockroachdb/cockroach/blob/4e6e7450afa88c877ad28ffe18e96e5c685f1065/pkg/sql/pg_catalog.go#L1194 that seems to do something very similar. Is it possible to get rid of this and use that function in your code above?
___
*[pkg/sql/logictest/testdata/logic_test/information_schema, line 1650 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58695#-MQwVFqR2ToyfN8s8Wws:-MQwVFqR2ToyfN8s8Wwt:b-ibh7jj) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a7e1d0016596c061a6866b840f17d88f3125731/pkg/sql/logictest/testdata/logic_test/information_schema#L1650)):*
> ```
> CREATE TABLE t1 (
>   id INT8 NULL,
>   name STRING NULL,
> ```

We should probably test for the scenario where there is no comment on the column as well. Maybe a third column here?
___
*[pkg/sql/vtable/information_schema.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58695#-MQwQfGD9NZbging8_Cv:-MQwQfGD9NZbging8_Cw:b-r7b1px) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a7e1d0016596c061a6866b840f17d88f3125731/pkg/sql/vtable/information_schema.go#L38)):*
> ```Go
> 	TABLE_NAME               STRING NOT NULL,
> 	COLUMN_NAME              STRING NOT NULL,
>   COLUMN_COMMENT           STRING,
> ```

nit: the indentation on this seems a bit off

**Comment by mosquito2333** [comment]
> Thanks for your contribution @mosquito2333! I left some minor comments, but otherwise things look good!
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58695#-:-MQwVORk46J3w57BfMy3:b-t4k8fn)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mosquito2333)
> 
> _[pkg/sql/information_schema.go, line 444 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58695#-MQwWdht6GCEkZnAXZtt:-MQwWdht6GCEkZnAXZtu:b-cv0j42) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a7e1d0016596c061a6866b840f17d88f3125731/pkg/sql/information_schema.go#L444)):_
> 
> > ```go
> > 				//Search the comment belonging to current column from collations,using table id and column id
> > 				var description string
> > 				for _, comment := range comments {
> > ```
> 
> Iterating over all the tables which have comments here seems rather inefficient. Could we use a map here instead, keyed by the table ID?
> 
> _[pkg/sql/information_schema.go, line 2218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58695#-MQwWAKN8vB_iRuS0QXx:-MQwWAKN8vB_iRuS0QXy:b3tzvu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a7e1d0016596c061a6866b840f17d88f3125731/pkg/sql/information_schema.go#L2218)):_
> 
> > ```go
> > // A comment is represented as a datum row, containing object id (table id),
> > // sub id (column id), comment text.
> > func getColumnComments(ctx context.Context, p *planner) ([]tree.Datums, error) {
> > ```
> 
> I found this function
> 
> https://github.com/cockroachdb/cockroach/blob/4e6e7450afa88c877ad28ffe18e96e5c685f1065/pkg/sql/pg_catalog.go#L1194
> 
> that seems to do something very similar. Is it possible to get rid of this and use that function in your code above?
> _[pkg/sql/logictest/testdata/logic_test/information_schema, line 1650 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58695#-MQwVFqR2ToyfN8s8Wws:-MQwVFqR2ToyfN8s8Wwt:b-ibh7jj) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a7e1d0016596c061a6866b840f17d88f3125731/pkg/sql/logictest/testdata/logic_test/information_schema#L1650)):_
> 
> > ```
> > CREATE TABLE t1 (
> >   id INT8 NULL,
> >   name STRING NULL,
> > ```
> 
> We should probably test for the scenario where there is no comment on the column as well. Maybe a third column here?
> 
> _[pkg/sql/vtable/information_schema.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58695#-MQwQfGD9NZbging8_Cv:-MQwQfGD9NZbging8_Cw:b-r7b1px) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a7e1d0016596c061a6866b840f17d88f3125731/pkg/sql/vtable/information_schema.go#L38)):_
> 
> > ```go
> > 	TABLE_NAME               STRING NOT NULL,
> > 	COLUMN_NAME              STRING NOT NULL,
> >   COLUMN_COMMENT           STRING,
> > ```
> 
> nit: the indentation on this seems a bit off
Thank you for your patience, and your guidance is very helpful to me.
I have modified the code, welcome to continue to guide

**Comment by mosquito2333** [comment]
@arulajmani .Thank you for your patience, and your guidance is very helpful to me.
I have modified the code, welcome to continue to guide

**Review by arulajmani — CHANGES_REQUESTED** [review]
@mosquito2333 thanks for making the changes, this PR should be ready to merge once you remove the clarifying comment from the code and address the nits! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58695#-:-MR6w252CCgRgVc4_H_m:bnfh609)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @mosquito2333)

___
*[pkg/sql/information_schema.go, line 406 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58695#-MR6wATM7TbIeAe5lbYL:-MR6wATM7TbIeAe5lbYM:biz0qvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddbdedfc5d5921d6082212c9fcf8ba5618222c8c/pkg/sql/information_schema.go#L406)):*
> ```Go
> 	schema: vtable.InformationSchemaColumns,
> 	populate: func(ctx context.Context, p *planner, dbContext *dbdesc.Immutable, addRow func(...tree.Datum) error) error {
> 		//Get the collations for all comments of current database.
> ```

nit: space after // 
___
*[pkg/sql/information_schema.go, line 414 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58695#-MR6vjeS62nCdmwxmCnT:-MR6vjeS62nCdmwxmCnU:bei88tl) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddbdedfc5d5921d6082212c9fcf8ba5618222c8c/pkg/sql/information_schema.go#L414)):*
> ```Go
> 		commentMap := make(map[tree.DInt]map[tree.DInt]string)
> 		for _, comment := range comments {
> 			//I don't know, int64 or string, which is more appropriate for objID/objSubID
> ```

I think what you have here, DInt, is fine. Could you remove this comment before I accept the suggestion please?
___
*[pkg/sql/information_schema.go, line 459 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58695#-MR6wDNpCVk6rRrEFGKf:-MR6wDNpCVk6rRrEFGKg:bjxlzyw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddbdedfc5d5921d6082212c9fcf8ba5618222c8c/pkg/sql/information_schema.go#L459)):*
> ```Go
> 				}
> 
> 				//Match the comment belonging to current column from map,using table id and column id
> ```

nit: space after `//`

**Review by arulajmani — APPROVED** [review]
:lgtm: 

Thanks for making the changes and for the contribution @mosquito2333! 

bors r=arulajmani

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58695#-:-MRLGN_-5DDnfImAZyCu:b-go24nn)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @mosquito2333)

**Comment by mosquito2333** [comment]
> :lgtm:
> 
> Thanks for making the changes and for the contribution @mosquito2333!
> 
> bors r=arulajmani
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58695#-:-MRLGN_-5DDnfImAZyCu:b-go24nn)_ status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @mosquito2333)

thank you,but can you help me merge it agen,or what should I do?

> :lgtm:
> 
> Thanks for making the changes and for the contribution @mosquito2333!
> 
> bors r=arulajmani
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58695#-:-MRLGN_-5DDnfImAZyCu:b-go24nn)_ status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @mosquito2333)

Thank you very much, but what should I do now. Can you help me merge it agen ？

**Comment by mosquito2333** [comment]
> :lgtm:
> 
> Thanks for making the changes and for the contribution @mosquito2333!
> 
> bors r=arulajmani
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58695#-:-MRLGN_-5DDnfImAZyCu:b-go24nn)_ status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @mosquito2333)

Thank you very much, but what should I do now. Can you help me merge it agen ？

**Comment by arulajmani** [comment]
hmm looks like this fell prey to a flaky test. 

bors r=arulajmani

**Comment by mosquito2333** [comment]
> hmm looks like this fell prey to a flaky test.
> 
> bors r=arulajmani
Thank you, it was a great experience for me.

**Pull request merged**
