### PR TITLE
ccl: allow partitioned inverted indexes

### LINKED ISSUE #43643: sql: Partitioning for Inverted Indexes
**Is your feature request related to a problem? Please describe.**
For users that have locality requirements (i.e. GDPR), some of their customer data is stored in JSONB columns which must also adhere to locality rules.  Currently, inverted indexes on these columns can not be partitioned, so the table data can be partitioned but the index can not, which breaks the data locality rules.  There is a current workaround to solve this but would be nicer to have as a supported feature to make usability simple.

**Describe the solution you'd like**

Be able to partition an inverted index just like a regular table or index. 

create inverted index custom_jsonb2 on users (city, custom) partition by list (city)
( 
PARTITION us_west VALUES IN (('seattle'), ('san francisco'), ('los angeles')), 
PARTITION us_east VALUES IN (('new york'), ('boston'), ('washington dc')), 
PARTITION europe_west VALUES IN (('amsterdam'), ('paris'), ('rome'))
)
;

**Describe alternatives you've considered**

The alternatives aren't terrible but it's more leg work that has to be done by administrators / users.  The main alternative is to create partial compute columns for a JSONB column.  The new columns have case logic to populate based on data locality or have null otherwise.  You can then create separate inverted indexes for each compute column.  

**Additional context**

There is a workaround blog post here for more context: https://chriscasano.blogspot.com/2019/12/part-pin-for-inverted-index-win.html

### PR DESCRIPTION
**Pull request by mgartner**
Now that multi-column inverted indexes are supported, partitioned
inverted indexes are possible.

Fixes #43643

Release note (sql change): Partitioned inverted indexes are now
supported.

### CODE REVIEW

**Comment by mgartner** [comment]
I ran into an optimizer bug when adding tests for `REGION BY ROW` (#59859), so I'll put those up in a follow-up PR.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59858#-:-MSoL2jcDtFpmAEAFRUx:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @mgartner, and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/partitioning_index, line 189 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59858#-MSoKpNJ93akYvKvCG0Z:-MSoKYFd2nosZr-qWfaf:b6rx1y4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0caa50e84961a0c905106c32b51ca66d7f59601/pkg/ccl/logictestccl/testdata/logic_test/partitioning_index#L189)):*
> ```
> 
> # Verify that inverted indexes with a partition for NULLs can actually store
> # NULLs.
> ```

Was this prohibited somewhere? Seems a bit random. (The test case is fine, just curious...)

**Comment by mgartner** [comment]
___
*[pkg/ccl/logictestccl/testdata/logic_test/partitioning_index, line 189 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59858#-MSoKpNJ93akYvKvCG0Z:-MSoaC5NCKJysM95jeeL:bxgitsr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0caa50e84961a0c905106c32b51ca66d7f59601/pkg/ccl/logictestccl/testdata/logic_test/partitioning_index#L189)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Was this prohibited somewhere? Seems a bit random. (The test case is fine, just curious...)
</blockquote></details>

No nothing was preventing it. I removed it because it doesn't seem necessary.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59858)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm and @otan)

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59858)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm and @mgartner)

___
*[pkg/ccl/logictestccl/testdata/logic_test/partitioning_index, line 158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59858#-MSykVe8DT_BRlfDE5Bs:-MSykVe99yAKjnCXk33B:burwm01) ([raw file](https://github.com/cockroachdb/cockroach/blob/3988d63efdfc7e9737da5f1f6cb64820b9deea9a/pkg/ccl/logictestccl/testdata/logic_test/partitioning_index#L158)):*
> ```
>     a INT PRIMARY KEY, b INT, j JSON,
>     INVERTED INDEX (b, j) PARTITION BY LIST (b) (
>         PARTITION p1 VALUES IN (1),
> ```

do you mind adding tests / an extra line for some variation of inverted indexes for
* implicit column partitioning (https://github.com/cockroachdb/cockroach/blob/0e98670c8fcec566937e899fdf77d2a68c702d62/pkg/ccl/logictestccl/testdata/logic_test/partitioning_implicit#L68)
* PARTITION ALL BY (https://github.com/cockroachdb/cockroach/blob/0e98670c8fcec566937e899fdf77d2a68c702d62/pkg/ccl/logictestccl/testdata/logic_test/partitioning_implicit#L327)
* ALTER PRIMARY KEY with inverted indexes (https://github.com/cockroachdb/cockroach/blob/0e98670c8fcec566937e899fdf77d2a68c702d62/pkg/ccl/logictestccl/testdata/logic_test/partitioning_implicit#L399)
* REGIONAL BY ROW tables (https://github.com/cockroachdb/cockroach/blob/0e98670c8fcec566937e899fdf77d2a68c702d62/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L81)

if it turns out to be work out of the box, i'm happy for a separate commit to handle these

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59858)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/partitioning_index, line 158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59858#-MSykVe8DT_BRlfDE5Bs:-MT1sH30AV-zCwhhirFG:bylbvoa) ([raw file](https://github.com/cockroachdb/cockroach/blob/3988d63efdfc7e9737da5f1f6cb64820b9deea9a/pkg/ccl/logictestccl/testdata/logic_test/partitioning_index#L158)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

do you mind adding tests / an extra line for some variation of inverted indexes for
* implicit column partitioning (https://github.com/cockroachdb/cockroach/blob/0e98670c8fcec566937e899fdf77d2a68c702d62/pkg/ccl/logictestccl/testdata/logic_test/partitioning_implicit#L68)
* PARTITION ALL BY (https://github.com/cockroachdb/cockroach/blob/0e98670c8fcec566937e899fdf77d2a68c702d62/pkg/ccl/logictestccl/testdata/logic_test/partitioning_implicit#L327)
* ALTER PRIMARY KEY with inverted indexes (https://github.com/cockroachdb/cockroach/blob/0e98670c8fcec566937e899fdf77d2a68c702d62/pkg/ccl/logictestccl/testdata/logic_test/partitioning_implicit#L399)
* REGIONAL BY ROW tables (https://github.com/cockroachdb/cockroach/blob/0e98670c8fcec566937e899fdf77d2a68c702d62/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L81)

if it turns out to be work out of the box, i'm happy for a separate commit to handle these
</blockquote></details>

I added inverted indexes to all the `partitioning_implicit` tests you pointed to. I'll add `REGIONAL BY ROW` tests in a follow-up PR because they are dependent on this fix to the optimizer: #59859.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59858)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm and @otan)

**Review by otan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59858)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm and @mgartner)

___
*[pkg/ccl/logictestccl/testdata/logic_test/partitioning_index, line 158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59858#-MSykVe8DT_BRlfDE5Bs:-MT2G6Jl0r6OX3jHPjP6:b2nhpa7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3988d63efdfc7e9737da5f1f6cb64820b9deea9a/pkg/ccl/logictestccl/testdata/logic_test/partitioning_index#L158)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I added inverted indexes to all the `partitioning_implicit` tests you pointed to. I'll add `REGIONAL BY ROW` tests in a follow-up PR because they are dependent on this fix to the optimizer: #59859.
</blockquote></details>

Thx

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
