### PR TITLE
sql/sem/builtins: make hash functions fully compatible with postgres

### LINKED ISSUE #41709: sql: sha funcs slightly different than postgres
```
root@:26257/postgres> select sha256('');
                               sha256                               
+------------------------------------------------------------------+
  e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

```
postgres=# select sha256('');
                               sha256                               
--------------------------------------------------------------------
 \xe3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

Might be a type difference, or a conversion from byte -> string problem? Needs investigation.

Jira issue: CRDB-5417

### PR DESCRIPTION
**Pull request by madelynnblue**
Their return type should be bytes, and they should be prefixed with \x.

Fixes #41709

Release note(sql change): the various hash functions now return bytes
prefixed with \x, identical to Postgres.

### CODE REVIEW

**Comment by mjibson** [comment]
ping @solongordon

**Review by solongordon — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41939#-:-Lt0FK5N-iOIHUN4XRhp:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @solongordon)

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41939)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mjibson)

___
*[pkg/sql/sem/builtins/builtins.go, line 4108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41939#-Lt0YJPs6FKvhayB5bDC:-Lt0YJPt1j1_Rwbokj-n:b-viyhrn) ([raw file](https://github.com/cockroachdb/cockroach/blob/a78c1fdb61ecd80281924ce799f1f270fce2b18e/pkg/sql/sem/builtins/builtins.go#L4108)):*
> ```Go
> 		return tree.DNull, err
> 	}
> 	return tree.NewDBytes(tree.DBytes(fmt.Sprintf("\\x%x", h.Sum(nil)))), nil
> ```

Are you sure it's appending a `\x` here? That's extremely surprising to me (and even if it's true and this is a necessary change, it's a big backwards-incompatibility with our own past versions and shouldn't be made lightly)

This appears to show that the `\x` is a type-conversion artifact:

```
postgres=# select encode(sha256(''), 'hex');
                              encode                              
------------------------------------------------------------------
 e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
(1 row)

```

In cockroach with this change, we're now very different on this query:

```
root@127.0.0.1:52614/movr> select encode(sha256(''), 'hex');;
                                                                 encode                                                                 
+--------------------------------------------------------------------------------------------------------------------------------------+
  5c7865336230633434323938666331633134396166626634633839393666623932343237616534316534363439623933346361343935393931623738353262383535  
(1 row)

Time: 407µs

```

**Comment by mjibson** [comment]
Yup you're right. I'm reverting this for now until we decide changing this matters. See my discussion in #sql-execution-team if you have an opinion.

**Pull request merged**
