### PR TITLE
ui: search criteria ux improvements

### PR DESCRIPTION
**Pull request by maryliag**
Some of the names of sort on search criteria were
not a match for the column name on the tables, which could cause confusion. This commit updates the values of "P99" to "P99 Latency" and "Service Latency" to "Statement time" and "Transaction time".

Release note (ui change): Update sort label
on Search Criteria to match the name on the table columns.

Epic: CRDB-25476

### CODE REVIEW

**Review by gtr — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100893)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx` line 609 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100893#-NSRtqLxAFIq5C79lFgC:-NSRtqLxAFIq5C79lFgD:b-5nil47) ([raw file](https://github.com/cockroachdb/cockroach/blob/20916b4fe1de9f70b50d69e24ce0389069c7d713/pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx#L609)):*
> ```XML
>             <InlineAlert
>               intent="warning"
>               title={getSubsetWarning(
> ```

Missing the new `updateSortValue` argument.
___
*[`pkg/ui/workspaces/cluster-ui/src/util/sqlActivityConstants.ts` line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100893#-NSRqZYG4ZNKukKAYAmX:-NSRqZYG4ZNKukKAYAmY:b-l8gi5p) ([raw file](https://github.com/cockroachdb/cockroach/blob/20916b4fe1de9f70b50d69e24ce0389069c7d713/pkg/ui/workspaces/cluster-ui/src/util/sqlActivityConstants.ts#L97)):*
> ```XML
> export const STATS_LONG_LOADING_DURATION = duration(2, "s");
> 
> export function getSubsetWarning(
> ```

nit: you might have to rename this file to `sqlActivityConstants.tsx` since you're using JSX syntax in this function. This will also get rid of the failing lint tests.
___
*[`pkg/ui/workspaces/cluster-ui/src/util/sqlActivityConstants.ts` line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100893#-NSRqb0g4CKnl7iqvdQ7:-NSRmtXH-MZMcCYNMtK4:btqunld) ([raw file](https://github.com/cockroachdb/cockroach/blob/20916b4fe1de9f70b50d69e24ce0389069c7d713/pkg/ui/workspaces/cluster-ui/src/util/sqlActivityConstants.ts#L105)):*
> ```XML
>   updateSortValue: (sort: SqlStatsSortType) => void,
> ): string {
>   const link = (
> ```

I don't see this link component being used anywhere.
___
*[`pkg/ui/workspaces/cluster-ui/src/util/sqlActivityConstants.ts` line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100893#-NSRt5fN-sMMcvockiCf:-NSRt5fOC4yFtAkFy8ET:bppvkeg) ([raw file](https://github.com/cockroachdb/cockroach/blob/20916b4fe1de9f70b50d69e24ce0389069c7d713/pkg/ui/workspaces/cluster-ui/src/util/sqlActivityConstants.ts#L108)):*
> ```XML
>     <a
>       className={"action"}
>       onClick={() => updateSortValue(getLabel(columnTitle, type))}
> ```

I'm a little confused about calling this `getLabel` function. Did you mean to call `getSortLabel`?

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100893)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr)

___
*[`pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx` line 609 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100893#-NSRtqLxAFIq5C79lFgC:-NSWH1qN9h4FOxe66W7j:bas0vs7) ([raw file](https://github.com/cockroachdb/cockroach/blob/20916b4fe1de9f70b50d69e24ce0389069c7d713/pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx#L609)):*
<details><summary><i>Previously, gtr (Gerardo Torres Castro) wrote…</i></summary><blockquote>

Missing the new `updateSortValue` argument.
</blockquote></details>

That was not part of this commit, removed
___
*[`pkg/ui/workspaces/cluster-ui/src/util/sqlActivityConstants.ts` line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100893#-NSRt5fN-sMMcvockiCf:-NSWHAMzCtP_YjaFbtQ3:b-1puwuk) ([raw file](https://github.com/cockroachdb/cockroach/blob/20916b4fe1de9f70b50d69e24ce0389069c7d713/pkg/ui/workspaces/cluster-ui/src/util/sqlActivityConstants.ts#L108)):*
<details><summary><i>Previously, gtr (Gerardo Torres Castro) wrote…</i></summary><blockquote>

I'm a little confused about calling this `getLabel` function. Did you mean to call `getSortLabel`?
</blockquote></details>

Ooops... All the 3 changes that you commented on was something I was working on another commit that was not suppose to be in this one!
Removed all of these things, please take another look

**Review by gtr — APPROVED** [review]
:lgtm: thanks!

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100893#-:-NSfj-u7E92n2zcnaytH:brfqlux)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag)

**Comment by maryliag** [comment]
TFTR!
bors r+

**Pull request merged**
