### PR TITLE
sql/stats: don't use linear regression with NaN for stats forecasting

### LINKED ISSUE #113645: sql/stats: stats forecasting can't handle NaN values
It is possible for the calculations involved with stats forecasting to result in `NaN` values, whether because histogram bounds are `NaN` or because of extreme values like the max float64 value. Currently, the quantile logic is unable to handle this. It is possible to trigger the error added in #109461 using the following test:
```
diff --git a/pkg/sql/stats/quantile_test.go b/pkg/sql/stats/quantile_test.go
index a7727384085..6f88999d497 100644
--- a/pkg/sql/stats/quantile_test.go
+++ b/pkg/sql/stats/quantile_test.go
@@ -1290,6 +1290,15 @@ func TestQuantileOps(t *testing.T) {
                        intSq: 25416.666666666664,
                        fixed: quantile{{0, 0}, {0.125, 0}, {0.25, 100}, {0.5, 100}, {0.7916666666666666, 200}, {0.9583333333333334, 300}, {1, 400}},
                },
+               {
+                       q:     quantile{{0, 100}, {0.125, 100}, {0.25, 200}, {0.375, 300}, {0.375, 200}, {0.5, 100}, {0.625, 100}, {0.75, 0}, {0.875, 0}, {0.875, 100}, {0.875, 400}, {1, math.NaN()}},
+                       addR:  quantile{{0, 102}, {0.125, 102.25}, {0.25, 202.5}, {0.375, 302.75}, {0.375, 202.75}, {0.5, 103}, {0.625, 103.25}, {0.75, 3.5}, {0.875, 3.75}, {0.875, 103.75}, {0.875, 403.75}, {1, 104}},
+                       addS:  quantile{{0, 111}, {0.125, 111}, {0.125, 113}, {0.25, 213}, {0.25, 215}, {0.375, 316}, {0.375, 216}, {0.5, 117}, {0.625, 118}, {0.75, 19}, {0.875, 20}, {0.875, 120}, {0.875, 420}, {1, 121}},
+                       subR:  quantile{{0, 98}, {0.125, 97.75}, {0.25, 197.5}, {0.375, 297.25}, {0.375, 197.25}, {0.5, 97}, {0.625, 96.75}, {0.75, -3.5}, {0.875, -3.75}, {0.875, 96.25}, {0.875, 396.25}, {1, 96}},
+                       subS:  quantile{{0, 89}, {0.125, 89}, {0.125, 87}, {0.25, 187}, {0.25, 185}, {0.375, 284}, {0.375, 184}, {0.5, 83}, {0.625, 82}, {0.75, -19}, {0.875, -20}, {0.875, 80}, {0.875, 380}, {1, 79}},
+                       intSq: 25416.666666666664,
+                       fixed: quantile{{0, 0}, {0.125, 0}, {0.25, 100}, {0.5, 100}, {0.7916666666666666, 200}, {0.9583333333333334, 300}, {1, 400}},
+               },
        }
```
as well as a related out-of-bounds error on a separate line with a slightly different test:
```
diff --git a/pkg/sql/stats/quantile_test.go b/pkg/sql/stats/quantile_test.go
index a7727384085..8e130590040 100644
--- a/pkg/sql/stats/quantile_test.go
+++ b/pkg/sql/stats/quantile_test.go
@@ -1290,6 +1290,15 @@ func TestQuantileOps(t *testing.T) {
                        intSq: 25416.666666666664,
                        fixed: quantile{{0, 0}, {0.125, 0}, {0.25, 100}, {0.5, 100}, {0.7916666666666666, 200}, {0.9583333333333334, 300}, {1, 400}},
                },
+               {
+                       q:     quantile{{0, 100}, {0.125, 100}, {0.25, 200}, {0.375, 300}, {0.375, 200}, {0.5, 100}, {0.625, 100}, {0.75, 0}, {0.875, 0}, {0.875, 100}, {0.875, math.NaN()}, {1, math.NaN()}},
+                       addR:  quantile{{0, 102}, {0.125, 102.25}, {0.25, 202.5}, {0.375, 302.75}, {0.375, 202.75}, {0.5, 103}, {0.625, 103.25}, {0.75, 3.5}, {0.875, 3.75}, {0.875, 103.75}, {0.875, 403.75}, {1, 104}},
+                       addS:  quantile{{0, 111}, {0.125, 111}, {0.125, 113}, {0.25, 213}, {0.25, 215}, {0.375, 316}, {0.375, 216}, {0.5, 117}, {0.625, 118}, {0.75, 19}, {0.875, 20}, {0.875, 120}, {0.875, 420}, {1, 121}},
+                       subR:  quantile{{0, 98}, {0.125, 97.75}, {0.25, 197.5}, {0.375, 297.25}, {0.375, 197.25}, {0.5, 97}, {0.625, 96.75}, {0.75, -3.5}, {0.875, -3.75}, {0.875, 96.25}, {0.875, 396.25}, {1, 96}},
+                       subS:  quantile{{0, 89}, {0.125, 89}, {0.125, 87}, {0.25, 187}, {0.25, 185}, {0.375, 284}, {0.375, 184}, {0.5, 83}, {0.625, 82}, {0.75, -19}, {0.875, -20}, {0.875, 80}, {0.875, 380}, {1, 79}},
+                       intSq: 25416.666666666664,
+                       fixed: quantile{{0, 0}, {0.125, 0}, {0.25, 100}, {0.5, 100}, {0.7916666666666666, 200}, {0.9583333333333334, 300}, {1, 400}},
+               },
        }
```

Jira issue: CRDB-33086

### LINKED ISSUE #113680: sql: v23.1.11: index out of range in quantile.fixMalformed
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4596060865/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4596060865/?referrer=webhooks_plugin)

Panic Message:

```
panic.go:884: runtime error: index out of range [2] with length 2
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | runtime.goPanicIndex
  | 	GOROOT/src/runtime/panic.go:113
  | github.com/cockroachdb/cockroach/pkg/sql/stats.quantile.fixMalformed
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/quantile.go:811
  | github.com/cockroachdb/cockroach/pkg/sql/stats.predictHistogram
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/forecast.go:416
  | github.com/cockroachdb/cockroach/pkg/sql/stats.forecastColumnStatistics
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/forecast.go:276
  | github.com/cockroachdb/cockroach/pkg/sql/stats.ForecastTableStatistics
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/forecast.go:116
  | github.com/cockroachdb/cockroach/pkg/sql/stats.(*TableStatisticsCache).getTableStatsFromDB
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/stats_cache.go:826
  | github.com/cockroachdb/cockroach/pkg/sql/stats.(*TableStatisticsCache).addCacheEntryLocked.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/stats_cache.go:386
  | github.com/cockroachdb/cockroach/pkg/sql/stats.(*TableStatisticsCache).addCacheEntryLocked
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/stats_cache.go:388
  | github.com/cockroachdb/cockroach/pkg/sql/stats.(*TableStatisticsCache).getTableStatsFromCache
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/stats_cache.go:318
  | github.com/cockroachdb/cockroach/pkg/sql/stats.(*TableStatisticsCache).GetTableStats
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/stats_cache.go:222
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createStatsPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_plan_stats.go:464
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForCreateStats
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_plan_stats.go:513
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).planAndRunCreateStats
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_plan_stats.go:527
  | github.com/cockroachdb/cockroach/pkg/sql.(*createStatsResumer).Resume.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/create_stats.go:610
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).Txn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1620
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).txn.func4
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1698
  | github.com/cockroachdb/cockroach/pkg/kv.runTxn.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:970
  | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).exec
  | 	github.com/cockroachdb/cockroach/pkg/kv/txn.go:928
  | github.com/cockroachdb/cockroach/pkg/kv.runTxn
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:969
  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).TxnWithAdmissionControl
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:932
  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:907
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).txn
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1686
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).Txn
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1621
  | github.com/cockroachdb/cockroach/pkg/sql.(*createStatsResumer).Resume
  | 	github.com/cockroachdb/cockroach/pkg/sql/create_stats.go:592
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func2
  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1630
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine
  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1631
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob
  | 	github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:474
  | github.com/cockroachdb/cockroach/pkg/jobs.(*StartableJob).Start.func2
  | 	github.com/cockroachdb/cockroach/pkg/jobs/jobs.go:978
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) runtime error: index out of range [2] with length 2
Error types: (1) *withstack.withStack (2) runtime.boundsError
-- report composition:
runtime.boundsError
panic.go:884: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/util/stop/stopper.go#L469-L471](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/util/stop/stopper.go#L469-L471)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/jobs/jobs.go#L977-L979](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/jobs/jobs.go#L977-L979)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/jobs/adopt.go#L473-L475](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/jobs/adopt.go#L473-L475)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/jobs/registry.go#L1630-L1632](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/jobs/registry.go#L1630-L1632)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/jobs/registry.go#L1629-L1631](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/jobs/registry.go#L1629-L1631)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/create_stats.go#L591-L593](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/create_stats.go#L591-L593)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/internal.go#L1620-L1622](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/internal.go#L1620-L1622)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/internal.go#L1685-L1687](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/internal.go#L1685-L1687)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/kv/db.go#L906-L908](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/kv/db.go#L906-L908)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/kv/db.go#L931-L933](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/kv/db.go#L931-L933)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/kv/db.go#L968-L970](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/kv/db.go#L968-L970)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/kv/txn.go#L927-L929](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/kv/txn.go#L927-L929)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/kv/db.go#L969-L971](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/kv/db.go#L969-L971)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/internal.go#L1697-L1699](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/internal.go#L1697-L1699)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/internal.go#L1619-L1621](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/internal.go#L1619-L1621)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/create_stats.go#L609-L611](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/create_stats.go#L609-L611)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/distsql_plan_stats.go#L526-L528](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/distsql_plan_stats.go#L526-L528)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/distsql_plan_stats.go#L512-L514](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/distsql_plan_stats.go#L512-L514)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/distsql_plan_stats.go#L463-L465](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/distsql_plan_stats.go#L463-L465)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L221-L223](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L221-L223)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L317-L319](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L317-L319)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L387-L389](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L387-L389)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L385-L387](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L385-L387)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L825-L827](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L825-L827)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/stats/pkg/sql/stats/forecast.go#L115-L117](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/stats/pkg/sql/stats/forecast.go#L115-L117)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/stats/pkg/sql/stats/forecast.go#L275-L277](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/stats/pkg/sql/stats/forecast.go#L275-L277)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/stats/pkg/sql/stats/forecast.go#L415-L417](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/stats/pkg/sql/stats/forecast.go#L415-L417)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/stats/pkg/sql/stats/quantile.go#L810-L812](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/stats/pkg/sql/stats/quantile.go#L810-L812)
[GOROOT/src/runtime/panic.go#L112-L114](GOROOT/src/runtime/panic.go#L112-L114)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 470
pkg/jobs/jobs.go in pkg/jobs.(*StartableJob).Start.func2 at line 978
pkg/jobs/adopt.go in pkg/jobs.(*Registry).runJob at line 474
pkg/jobs/registry.go in pkg/jobs.(*Registry).stepThroughStateMachine at line 1631
pkg/jobs/registry.go in pkg/jobs.(*Registry).stepThroughStateMachine.func2 at line 1630
pkg/sql/create_stats.go in pkg/sql.(*createStatsResumer).Resume at line 592
pkg/sql/internal.go in pkg/sql.(*InternalDB).Txn at line 1621
pkg/sql/internal.go in pkg/sql.(*InternalDB).txn at line 1686
pkg/kv/db.go in pkg/kv.(*DB).Txn at line 907
pkg/kv/db.go in pkg/kv.(*DB).TxnWithAdmissionControl at line 932
pkg/kv/db.go in pkg/kv.runTxn at line 969
pkg/kv/txn.go in pkg/kv.(*Txn).exec at line 928
pkg/kv/db.go in pkg/kv.runTxn.func1 at line 970
pkg/sql/internal.go in pkg/sql.(*InternalDB).txn.func4 at line 1698
pkg/sql/internal.go in pkg/sql.(*InternalDB).Txn.func1 at line 1620
pkg/sql/create_stats.go in pkg/sql.(*createStatsResumer).Resume.func1 at line 610
pkg/sql/distsql_plan_stats.go in pkg/sql.(*DistSQLPlanner).planAndRunCreateStats at line 527
pkg/sql/distsql_plan_stats.go in pkg/sql.(*DistSQLPlanner).createPlanForCreateStats at line 513
pkg/sql/distsql_plan_stats.go in pkg/sql.(*DistSQLPlanner).createStatsPlan at line 464
pkg/sql/stats/pkg/sql/stats/stats_cache.go in pkg/sql/stats.(*TableStatisticsCache).GetTableStats at line 222
pkg/sql/stats/pkg/sql/stats/stats_cache.go in pkg/sql/stats.(*TableStatisticsCache).getTableStatsFromCache at line 318
pkg/sql/stats/pkg/sql/stats/stats_cache.go in pkg/sql/stats.(*TableStatisticsCache).addCacheEntryLocked at line 388
pkg/sql/stats/pkg/sql/stats/stats_cache.go in pkg/sql/stats.(*TableStatisticsCache).addCacheEntryLocked.func1 at line 386
pkg/sql/stats/pkg/sql/stats/stats_cache.go in pkg/sql/stats.(*TableStatisticsCache).getTableStatsFromDB at line 826
pkg/sql/stats/pkg/sql/stats/forecast.go in pkg/sql/stats.ForecastTableStatistics at line 116
pkg/sql/stats/pkg/sql/stats/forecast.go in pkg/sql/stats.forecastColumnStatistics at line 276
pkg/sql/stats/pkg/sql/stats/forecast.go in pkg/sql/stats.predictHistogram at line 416
pkg/sql/stats/pkg/sql/stats/quantile.go in pkg/sql/stats.quantile.fixMalformed at line 811
GOROOT/src/runtime/panic.go in runtime.goPanicIndex at line 113
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
```

### Tags

| Tag | Value |
| --- | --- |
| Command | mt start-sql |
| Environment | v23.1.12 |
| Go Version | go1.19.13 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.11-596-gfb1ed73d9d8 |
| Cockroach SHA | fb1ed73d9d88f459c3cda5866fae29831cce06b4 |
| # of CPUs | 16 |
| # of Goroutines | 280 |

Jira issue: CRDB-33107

### PR DESCRIPTION
**Pull request by DrewKimball**
This patch adds a method to the quantile function, `invalid`, which checks for `NaN` values within the function. These indicate a failure to derive a linear regression model for the observed histograms, and can lead to internal errors and panics if not caught. Stats forecasting now checks this method before attempting to use a quantile function to derive a histogram prediction.

Fixes #113645
Fixes #113680

Release note (bug fix): Fixed a bug that could cause internal errors or panics while attempting to forecast statistics on a numeric column.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
I'll let Michael review this, but I wonder whether we want to revert 120132e47c781ee8947d4753435c82758b964eae given that we now have a proper fix?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113712#-:-NiGsobk5N3adRuQ-V9T:b-4ocx5h)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2)

**Review by yuzefovich — COMMENTED** [review]
Nice job finding this btw!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113712#-:-NiGsxEA52X6QxJZZsm2:b-1rmdtm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2)

**Review by DrewKimball — COMMENTED** [review]
Thanks!

>I wonder whether we want to revert [120132e](https://github.com/cockroachdb/cockroach/commit/120132e47c781ee8947d4753435c82758b964eae) given that we now have a proper fix?

Good point. I've reverted it, since `fixMalformed` shouldn't return an error now.

I also expanded the `invalid` check to include `+/-Inf` values.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113712#-:-NiH2PiV9rbIRKp-kYiw:bv55bpk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2)

**Review by michae2 — APPROVED** [review]
Gah, I was checking for these in `toQuantileValue` and `fromQuantileValue` but it never occurred to me to check in between! Great catch! :lgtm:

It's possible this fixes https://github.com/cockroachdb/cockroach/issues/93892 as well, if we have an invalid quantile that makes it through fixMalformed without panicking. I'll think about that more.

@DrewKimball WDYT about adding another commit that adds panic-catching to `GetTableStats`? https://github.com/cockroachdb/cockroach/blob/722f90212398bfe67137019dde6334da7ff3e12b/pkg/sql/stats/stats_cache.go#L215-L223

If we panic while getting stats, I think we should try to plan the query without stats, rather than cause the query (all queries touching that table) to fail.

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113712#-:-NiH7WX14QO9Qa6B7mbP:bkncm9m)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/stats/quantile.go` line 658 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113712#-NiHC0hM8vuDN16V_l6g:-NiHC0hM8vuDN16V_l6h:b-tomwqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbd74be285ad898137eae348fef23cd655ac6ec1/pkg/sql/stats/quantile.go#L658)):*
> ```Go
> // This function fixes the negative slope pieces by "moving" p from the
> // overlapping places to where it should be. No p is lost in the making of these
> // calculations.
> ```

If you wouldn't mind, could you add a sentence to this comment mentioning that `isInvalid` must be checked first?

**Review by DrewKimball — COMMENTED** [review]
>If we panic while getting stats, I think we should try to plan the query without stats, rather than cause the query (all queries touching that table) to fail.

I think that makes sense, done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113712#-:-NiHv6IB71tcRn1vKWLA:bnng3bn)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2)

___
*[`pkg/sql/stats/quantile.go` line 658 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113712#-NiHC0hM8vuDN16V_l6g:-NiHGWwX4I_SYzAF_-Gg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbd74be285ad898137eae348fef23cd655ac6ec1/pkg/sql/stats/quantile.go#L658)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

If you wouldn't mind, could you add a sentence to this comment mentioning that `isInvalid` must be checked first?
</blockquote></details>

Done.

**Review by michae2 — APPROVED** [review]
:lgtm: Thank you!

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113712#-:-NiLHB2M9DhOKnNRjq4-:b-ae66e1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

**Comment by DrewKimball** [comment]
TFTR!

bors r+

**Comment by michae2** [comment]
I think we should also backport this to release-22.2.17-rc

**Comment by DrewKimball** [comment]
blathers backport 23.1.12-rc

**Comment by DrewKimball** [comment]
blathers backport 23.1.12-rc.Frozen

**Pull request merged**
