### PR TITLE
server: use absolute paths to the {cert,key,ca} files

### PR DESCRIPTION
**Pull request by petermattis**
This makes it easier to utilize the URL from a different directory than
the one the cockroach server started in.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4490)

### CODE REVIEW

**Comment by petermattis** [comment]
`sql:    postgresql://root@peters-imac.local:15432?sslcert=%2FUsers%2Fpmattis%2FDevelopment%2Fgo%2Fsrc%2Fgithub.com%2Fcockroachdb%2Fcockroach%2Fresource%2Ftest_certs%2Froot.client.crt&sslkey=%2FUsers%2Fpmattis%2FDevelopment%2Fgo%2Fsrc%2Fgithub.com%2Fcockroachdb%2Fcockroach%2Fresource%2Ftest_certs%2Froot.client.key&sslmode=verify-full&sslrootcert=%2FUsers%2Fpmattis%2FDevelopment%2Fgo%2Fsrc%2Fgithub.com%2Fcockroachdb%2Fcockroach%2Fresource%2Ftest_certs%2Fca.crt`

**Comment by spencerkimball** [comment]
LGTM

**Comment by tamird** [comment]
filepath.Abs returns an error if the working directory can't be determined
- we should avoid that call if filepath.IsAbs returns true, and emit the
error if it's non-nil.

**Comment by mberhault** [comment]
eep. I'm not sure that's needed. If you just copy paste from a different directory, you'll see something along the lines of "can't load ...crt". Wouldn't that be enough of a hint?
I'd prefer clarify in this case.

**Comment by bdarnell** [comment]
@mberhault That's a clear hint, but if you're running cockroach and your client in two different directories (which I think will be the common case for people who are not developing cockroachdb itself), it's tedious to hand-edit the url to adjust the three different paths, so I think it's better to present a URL that we're confident will work instead of one that is pretty.

I also don't think it matters very much since in most cases in which people have a terminal attached to cockroachdb's stdout they'll be running in insecure mode.

LGTM

**Comment by petermattis** [comment]
@tamird `filepath.Abs` only tries to determine the working directory if `filepath.IsAbs` returns false. And `os.Getwd` is the only error that `filepath.Abs` returns. I don't think there is anything to be done to get the behavior you desire. See https://golang.org/src/path/filepath/path.go?s=6774:6811#L224.

**Pull request merged**
