### PR TITLE
server: expose more/all of Raft's status

### PR DESCRIPTION
**Pull request by tbg**
screen shot 2016-08-30 at 10 54 19 pm
See #8111 for an instance of this being helpful. This exposes all the available
detail to the endpoint (and excerpts of it to the ui) and, together with freely
changing the logging verbosity, should leave little of Raft's internal state in
the dark.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8960)

### CODE REVIEW

**Comment by tamird** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[server/serverpb/status.proto, line 55 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8960#-KQSBNnOgOt7L2JeSwrF:-KQSBNnPuPBrD751gY8K:b-qax730) ([raw file](https://github.com/cockroachdb/cockroach/blob/794633e142d40c18cc77d07f184ea5ae8ea39ef1/server/serverpb/status.proto#L55)):*
> ```protobuf
> }
> 
> // RaftState gives internal details about a Raft group's state.
> ```

can't you use theirs?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8960)*

**Comment by tschottdorf** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[server/serverpb/status.proto, line 55 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8960#-KQSBNnOgOt7L2JeSwrF:-KQSDaz6w0KAtOq9krz2:b1f008o) ([raw file](https://github.com/cockroachdb/cockroach/blob/794633e142d40c18cc77d07f184ea5ae8ea39ef1/server/serverpb/status.proto#L55)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can't you use theirs?
</details>
I wasn't able to import this from here (no relative paths are allowed and etcd is outside of the root), but if you have some wisdom I'm willing to listen.

In any case we'll have stuff remain in our protos, as not all of this state is actually in the Raft protos.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8960)*

**Comment by tamird** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[server/serverpb/status.proto, line 55 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8960#-KQSBNnOgOt7L2JeSwrF:-KQSFsQEDueOZJGiCVn_:b-m9vt7a) ([raw file](https://github.com/cockroachdb/cockroach/blob/794633e142d40c18cc77d07f184ea5ae8ea39ef1/server/serverpb/status.proto#L55)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> I wasn't able to import this from here (no relative paths are allowed and etcd is outside of the root), but if you have some wisdom I'm willing to listen.
> 
> In any case we'll have stuff remain in our protos, as not all of this state is actually in the Raft protos.
</details>
Should be able to use theirs - let's discuss when you have time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8960)*

**Comment by tschottdorf** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[server/serverpb/status.proto, line 55 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8960#-KQSBNnOgOt7L2JeSwrF:-KQSUGha4eiem1g8wrBm:b-oq3912) ([raw file](https://github.com/cockroachdb/cockroach/blob/794633e142d40c18cc77d07f184ea5ae8ea39ef1/server/serverpb/status.proto#L55)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Should be able to use theirs - let's discuss when you have time.
</details>
Done, PTAL

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8960)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 4 of 10 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[server/status.go, line 658 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8960#-KQUAEMR69e2tV5jFj5h:-KQUAEMR69e2tV5jFj5i:b3srbew) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b257c7931a51a90aa1adcc3da57edd318d85b25/server/status.go#L658)):*
> ```Go
> 		state.ID = raftStatus.ID
> 
> 		state.HardState.Term = raftStatus.HardState.Term
> ```

Can't these be `state.HardState = raftStatus.HardState`?

---

*[server/serverpb/status.proto, line 69 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8960#-KQU9g39TunGE2PUD7Zm:-KQU9g39TunGE2PUD7Zn:b-3u4h6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b257c7931a51a90aa1adcc3da57edd318d85b25/server/serverpb/status.proto#L69)):*
> ```protobuf
>   }
> 
>   uint64 id = 1 [(gogoproto.customname) = "ID"];
> ```

What is this ID? The raft node ID (== cockroach replica ID)? Let's use replica_id here for clarity. 

---

*[ui/app/containers/raftRanges.tsx, line 175 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8960#-KQU9teAjys9VlyD_69B:-KQU9teBW868MgUnQL3U:bwp53yw) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b257c7931a51a90aa1adcc3da57edd318d85b25/ui/app/containers/raftRanges.tsx#L175)):*
> ```XML
>             {(this.state.showState) ? <div>State: {nodeRange.raft_state.state} ID={nodeRange.raft_state.getId().toString()} Term={nodeRange.raft_state.getHardState().getTerm().toString()} Lead={nodeRange.raft_state.getLead().toString()}</div> : ""}
>             {(this.state.showReplicas) ? <div>
>               <div>Replica On: {replicaNodeIDs.join(", ")}</div>
> ```

Now that we're showing replica IDs more, this should include the full (node, store, replica) tuple instead of just node IDs. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8960#-:-KQUAwxfUQX2-2CblKIU:bnfp4nl)*

**Comment by tschottdorf** [comment]
Review status: 3 of 11 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[server/status.go, line 658 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8960#-KQUAEMR69e2tV5jFj5h:-KQWB_WD4kv9EX2ScYnA:b-kr6qq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b257c7931a51a90aa1adcc3da57edd318d85b25/server/status.go#L658)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Can't these be `state.HardState = raftStatus.HardState`?
</details>
I had to back out HardState for now and duplicate the message due to a string of ui refactors that would need to happen first.

---

*[server/serverpb/status.proto, line 69 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8960#-KQU9g39TunGE2PUD7Zm:-KQWDeCgw4csT8p5wIpu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b257c7931a51a90aa1adcc3da57edd318d85b25/server/serverpb/status.proto#L69)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> What is this ID? The raft node ID (== cockroach replica ID)? Let's use replica_id here for clarity. 
</details>
Done.

---

*[ui/app/containers/raftRanges.tsx, line 175 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8960#-KQU9teAjys9VlyD_69B:-KQWHqSS1ExA3mp-94m5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b257c7931a51a90aa1adcc3da57edd318d85b25/ui/app/containers/raftRanges.tsx#L175)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Now that we're showing replica IDs more, this should include the full (node, store, replica) tuple instead of just node IDs. 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8960)*

**Comment by tamird** [comment]
:lgtm: modulo waiting for https://github.com/cockroachdb/cockroach/pull/8984 to save me some future work.

---

Reviewed 2 of 10 files at r1, 1 of 7 files at r2, 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[server/status.go, line 658 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8960#-KQUAEMR69e2tV5jFj5h:-KQWWOyeoNjpBgF3525_:bg0b4uk) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b257c7931a51a90aa1adcc3da57edd318d85b25/server/status.go#L658)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> I had to back out HardState for now and duplicate the message due to a string of ui refactors that would need to happen first.
</details>
https://github.com/cockroachdb/cockroach/pull/8984

---

*[server/status.go, line 691 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8960#-KQWWVcE04eXwJcvmfii:-KQWWVcE04eXwJcvmfij:btt6kny) ([raw file](https://github.com/cockroachdb/cockroach/blob/328b8bbea4a8c77ab21955a25f6b1f9163704bea/server/status.go#L691)):*
> ```Go
> 					return true, err
> 				}
> 				raftState := convertRaftStatus(rep.RaftStatus())
> ```

this can go inline below, right? ditto with `state` below.

---

*[ui/app/containers/raftRanges.tsx, line 177 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8960#-KQWUlGkheIzJ_ukiJPi:-KQWUlGkheIzJ_ukiJPj:b4k1fa0) ([raw file](https://github.com/cockroachdb/cockroach/blob/328b8bbea4a8c77ab21955a25f6b1f9163704bea/ui/app/containers/raftRanges.tsx#L177)):*
> ```XML
>           let index = nodeIDIndex[node.node_id];
>           let cell = <td key={index}>
>             {(this.state.showState) ? <div>State: {nodeRange.raft_state.state} ReplicaID={nodeRange.raft_state.getReplicaId().toString()} Term={nodeRange.raft_state.getHardState().getTerm().toString()} Lead={nodeRange.raft_state.getLead().toString()}</div> : ""}
> ```

nit: avoid the getters since surrounding code doesn't use them

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8960#-:-KQWWdnqGBTgy6We7MZQ:byndxme)*

**Comment by tschottdorf** [comment]
Review status: 1 of 11 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[server/status.go, line 658 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8960#-KQUAEMR69e2tV5jFj5h:-KQWYyMpaT6PAyxpigcz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b257c7931a51a90aa1adcc3da57edd318d85b25/server/status.go#L658)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> https://github.com/cockroachdb/cockroach/pull/8984
</details>
Done.

---

*[server/status.go, line 691 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8960#-KQWWVcE04eXwJcvmfii:-KQWYxXvIY-_zKZLcP1O:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/328b8bbea4a8c77ab21955a25f6b1f9163704bea/server/status.go#L691)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this can go inline below, right? ditto with `state` below.
</details>
Done.

---

*[ui/app/containers/raftRanges.tsx, line 177 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8960#-KQWUlGkheIzJ_ukiJPi:-KQWaUTn-8c7djPTZMEi:bufbjsm) ([raw file](https://github.com/cockroachdb/cockroach/blob/328b8bbea4a8c77ab21955a25f6b1f9163704bea/ui/app/containers/raftRanges.tsx#L177)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: avoid the getters since surrounding code doesn't use them
</details>
If I don't use the getters, I call `toString()` on undefined objects (confirmed with @mrtracy).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8960)*

**Comment by tamird** [comment]
Reviewed 10 of 10 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[server/serverpb/status.proto, line 59 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8960#-KQWcJQsN_pm3U55sOGK:-KQWcJQsN_pm3U55sOGL:b-vtqjze) ([raw file](https://github.com/cockroachdb/cockroach/blob/779806fd070c16796069b9d5d88989bb57e096e5/server/serverpb/status.proto#L59)):*
> ```protobuf
> // RaftState gives internal details about a Raft group's state.
> // Closely mirrors the upstream definitions in
> // github.com/coreos/etcd/raft/raftpb/raft.proto.
> ```

did you mean to remove this?

---

*[ui/app/containers/raftRanges.tsx, line 177 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8960#-KQWUlGkheIzJ_ukiJPi:-KQWcLZYGwGG-jgLZ7qJ:b-42ylz8) ([raw file](https://github.com/cockroachdb/cockroach/blob/328b8bbea4a8c77ab21955a25f6b1f9163704bea/ui/app/containers/raftRanges.tsx#L177)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> If I don't use the getters, I call `toString()` on undefined objects (confirmed with @mrtracy).
</details>
Bummer!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8960)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[server/serverpb/status.proto, line 59 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8960#-KQWcJQsN_pm3U55sOGK:-KQWdgmyNR0e1FuwUn5V:b-3ew6g5) ([raw file](https://github.com/cockroachdb/cockroach/blob/779806fd070c16796069b9d5d88989bb57e096e5/server/serverpb/status.proto#L59)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> did you mean to remove this?
</details>
Not remove, but should have updated it (most of this here mirrors etcd/raft). Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8960)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8960)*

**Pull request merged**
