### PR TITLE
rowexec: remove settings for disabling temp storage in sorts and joins

### PR DESCRIPTION
**Pull request by yuzefovich**
Release note (sql change): Two public cluster settings
`sql.distsql.temp_storage.joins` and `sql.distsql.temp_storage.sorts`
that can disable usage of temporary on disk storage of intermediate
results of query execution have been removed.

### CODE REVIEW

**Review by asubiotto — COMMENTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47357)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/rowexec/hashjoiner_test.go, line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47357#-M4oCVvP7kzTDxNDPFjm:-M4oCVvP7kzTDxNDPFjn:b-gtvrd9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e03de3ec3837d2634ed773544252904f1ca0b5f3/pkg/sql/rowexec/hashjoiner_test.go#L342)):*
> ```Go
> 
> 	post := execinfrapb.PostProcessSpec{Projection: true, OutputColumns: outCols}
> 	// Since the use of external storage overrides h.initialBufferSize, disable
> ```

Why does this test need to override `initialBufferSize`? The buffer phase is probably something else we can remove from the hashjoiner to remove this variable and `disableTempStorage` from the constructor, since I'm pretty sure the optimizer takes care of planning the smallest estimated side as the right side.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47357)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/rowexec/hashjoiner_test.go, line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47357#-M4oCVvP7kzTDxNDPFjm:-M4z1OBT4sydVNjl1wUV:basonci) ([raw file](https://github.com/cockroachdb/cockroach/blob/e03de3ec3837d2634ed773544252904f1ca0b5f3/pkg/sql/rowexec/hashjoiner_test.go#L342)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why does this test need to override `initialBufferSize`? The buffer phase is probably something else we can remove from the hashjoiner to remove this variable and `disableTempStorage` from the constructor, since I'm pretty sure the optimizer takes care of planning the smallest estimated side as the right side.
</blockquote></details>

I don't know the answer to the first question - this behavior was already present. Probably because we want to force that the right side is used as the building side.

Anecdotally, I think I saw a query in which building using the left side and probing on the right was more efficient, and this buffering phase in `rowexec.hashJoiner` allowed us to do that (which was not the case in the vectorized engine). I feel like we should keep the buffering phase since the code already exists, and it can give performance boost in the cases when the optimizer is wrong.

**Comment by asubiotto** [comment]
>  I feel like we should keep the buffering phase since the code already exists, and it can give performance boost in the cases when the optimizer is wrong.

I don't agree. I think we should remove this code because in general we want to move optimization decisions outside the execution engine. If the optimizer is wrong, that's something we want to know about and fix in the optimizer.

**Comment by yuzefovich** [comment]
Ok, fair point, but I'd argue that it's beyond the scope of this PR - I wanted to address the TODO that I left a while back.

Added another TODO to remove the buffering stage :)

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47357#-:-M5M7F9m2PV0GuyXji37:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
