### PR TITLE
opt: fix a bug related to extending LogicalKeys, improve handling of contradictions

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: fix a bug related to extending LogicalKeys

We have a few places (in calcOffset) where we don't clone the keys
before extending them. Fixing this by making extend safe and removing
the clone function altogether.

Release note: None

#### opt: improve handling of contradictions

If any call to calcOffset returns no spans, then there is a
contradiction. We were ignoring such cases when extending spans.

For example: for `(@1 = 1) AND (@2 > 5) AND (@2 < 1)` we now
get no spans. We used to get `[/1 - /1]` with remaining filter
`(@2 > 5) AND (@2 < 1)`.

Release note: None

### CODE REVIEW

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/opt/testdata/index-constraints, line 851 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21099#-L1Tf6bkkQAickE3VVFk:-L1Tf6bkkQAickE3VVFl:b4uh0na) ([raw file](https://github.com/cockroachdb/cockroach/blob/b374285a682508b4a9874dc3d28bfc3275f31c13/pkg/sql/opt/testdata/index-constraints#L851)):*
> ```
> Remaining filter: @2 = CASE WHEN @3 = 2 THEN 1 ELSE 2 END
> 
> build-scalar,normalize,index-constraints vars=(string, string, string, string, string, string, string, string, string, string) index=(@2, @4, @6, @7, @10, @3, @1)
> ```

Is it possible to format this test and the next one so they are a bit easier to read? Maybe also add a comment to explain what they are testing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21099#-:-L1TfdXOqJK_VgkHYmI_:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/opt/testdata/index-constraints, line 851 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21099#-L1Tf6bkkQAickE3VVFk:-L1TgY3Wt18uWM3tUhW_:b-t1uabx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b374285a682508b4a9874dc3d28bfc3275f31c13/pkg/sql/opt/testdata/index-constraints#L851)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Is it possible to format this test and the next one so they are a bit easier to read? Maybe also add a comment to explain what they are testing?
</blockquote></details>

It's a case from some logictests where I saw a crash. I'll try to come up with a simpler testcase.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21099)*

**Comment by RaduBerinde** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/opt/testdata/index-constraints, line 851 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21099#-L1Tf6bkkQAickE3VVFk:-L1TnOw71oeK2-hbDX8z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b374285a682508b4a9874dc3d28bfc3275f31c13/pkg/sql/opt/testdata/index-constraints#L851)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It's a case from some logictests where I saw a crash. I'll try to come up with a simpler testcase.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21099)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/index_constraints.go, line 501 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/21099#-L1ToB8eNpMzRuLwkfCR:-L1ToB8eNpMzRuLwkfCS:bvtamvl) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad415284c02148b12a60becee1666ffca9f6de0e/pkg/sql/opt/index_constraints.go#L501)):*
> ```Go
> 			case 0:
> 				// We found a contradiction.
> 				newSpans = LogicalSpans{}
> ```

Subtle that `newSpans` is empty, but non-nil. Also, I'm not clear on why this isn't returning here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21099#-:-L1TogfXRwfHPMoBsSjN:bnfp4nl)*

**Comment by rytaft** [comment]
Reviewed 1 of 2 files at r4.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/testdata/index-constraints, line 851 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21099#-L1Tf6bkkQAickE3VVFk:-L1Tp61KcQhvXg73GcEd:b-vs1prh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b374285a682508b4a9874dc3d28bfc3275f31c13/pkg/sql/opt/testdata/index-constraints#L851)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks good!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21099)*

**Comment by RaduBerinde** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/opt/index_constraints.go, line 501 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/21099#-L1ToB8eNpMzRuLwkfCR:-L1TqOQwUcfQ5cE7mqTv:bhjys7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad415284c02148b12a60becee1666ffca9f6de0e/pkg/sql/opt/index_constraints.go#L501)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Subtle that `newSpans` is empty, but non-nil. Also, I'm not clear on why this isn't returning here.
</blockquote></details>

I don't think we ever distinguish between nil and empty slices anywhere (I chose to add the `ok` flag instead of having `nil` as a special value), so this could have been nil just as well; this just seems more explicit that we want 0 spans.

We don't return because we still want to memoize the result. I added a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21099)*

**Comment by petermattis** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/opt/index_constraints.go, line 501 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/21099#-L1ToB8eNpMzRuLwkfCR:-L1TroygHYrGSQJ3oZkA:bxqc73p) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad415284c02148b12a60becee1666ffca9f6de0e/pkg/sql/opt/index_constraints.go#L501)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I don't think we ever distinguish between nil and empty slices anywhere (I chose to add the `ok` flag instead of having `nil` as a special value), so this could have been nil just as well; this just seems more explicit that we want 0 spans.

We don't return because we still want to memoize the result. I added a comment.
</blockquote></details>

There are tests below for `newSpans == nil` and `newSpans != nil`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21099)*

**Comment by RaduBerinde** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/opt/index_constraints.go, line 501 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/21099#-L1ToB8eNpMzRuLwkfCR:-L1Ts7_8cqn1fdLOqrcO:b3a6wz1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad415284c02148b12a60becee1666ffca9f6de0e/pkg/sql/opt/index_constraints.go#L501)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

There are tests below for `newSpans == nil` and `newSpans != nil`.
</blockquote></details>

Oh, you're right. I changed to just store the result here and return.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21099)*

**Pull request merged**
