### PR TITLE
tree: fix bug in type resolution involving anyenum

### LINKED ISSUE #83496: roachtest/sqlsmith: cannot resolve types in DistSQL by name with fakedist config
```
# LogicTest: 5node

statement ok
CREATE TABLE t (c STRING);
INSERT INTO t VALUES ('v');
ALTER TABLE t EXPERIMENTAL_RELOCATE VALUES (ARRAY[2], 1);
CREATE TYPE typ AS ENUM ('foo', 'bar');

statement ok
SELECT * FROM t
WHERE (
  (SELECT 'bar':::typ FROM t WHERE false)
  IS NOT DISTINCT FROM CASE WHEN NULL THEN NULL ELSE NULL END
)
```

Jira issue: CRDB-17103

### PR DESCRIPTION
**Pull request by postamar**
In exceptional cases it's possible for some special pre-constructed types such as `anyenum` to appear at execution time despite the assurances to the contrary that may be found in the commentary accompanying their definition.

For instance `CASE WHEN NULL THEN NULL ELSE NULL END` can get serialized as `CAST(NULL AS anyenum)`. Despite being valid, this would result in an error in a distributed setting where a TypeReferenceResolver isn't available.

This commit fixes this by prefacing the TypeReferenceResolver method usages with looking in a predefined list of special types that, for the time being, includes types.AnyEnum only.

Fixes #83496

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
I want queries to look at this one. I feel like while this might work, it might reveal some deeper problem I can't see.

> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90461#-:-NEwGZbbBqUi7MTdwyw3:b-7cp7bs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

**Review by rafiss — COMMENTED** [review]
curious if you can cause something similar with either of:
- `CASE WHEN NULL THEN () ELSE () END` for anytuple
- `CASE WHEN NULL THEN ARRAY[] ELSE ARRAY[] END` for anyarray

**Comment by postamar** [comment]
The anyarray case yields
```(42P18) incompatible value type: cannot determine type of empty array. Consider casting to the desired type, for example ARRAY[]::int[]``` while the anytuple case just works.

**Comment by postamar** [comment]
cc @cockroachdb/sql-queries

**Review by yuzefovich — APPROVED** [review]
The fix :lgtm:

However, I don't know whether we are tapering over some other issue as Andrew is hinting at. Perhaps @rafiss or @mgartner have some ideas. Also, from my earlier investigation I still don't know the answer to
> should `anyenum` type be considered a user-defined type? It has a fixed oid.T_anyenum == 3500, so we treat it as not a UDT. Not sure whether this was by design.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90461#-:-NFQfGko4wpjQ9c7NP56:b-pqoecw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @postamar)

___
*[`pkg/sql/sem/tree/type_name.go` line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90461#-NFQeqoc4UbOmGU7nAhH:-NFQeqodAEyaOUVGCAAl:b-ro76yo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5ff9ce92d519314cc69f8de5fc185ce033f74e4/pkg/sql/sem/tree/type_name.go#L156)):*
> ```Go
> var specialResolutionTypes = []*types.T{
> 	types.AnyEnum,
> 	// TODO(?): add more special pre-constructed types
> ```

nit: all TODOs should have github usernames attached to them.

**Comment by postamar** [comment]
Thanks for the review. I wonder as well. Could we do something akin to what we do with `anyarray` and just throw an error saying we can't determine the type of the enum? That would sit better with me, for what that's worth (I'm very naive here).

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90461)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @postamar, and @yuzefovich)

___
*[`pkg/sql/logictest/testdata/logic_test/distsql_enum` line 104 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90461#-NFUgFIwEXqNNcLWC4Gj:-NFUgFIwEXqNNcLWC4Gk:b-a0ughm) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3fcb2e4038322d8b985f47047da06b046b2dd0/pkg/sql/logictest/testdata/logic_test/distsql_enum#L104)):*
> ```
> SELECT * FROM t83496 WHERE (
>   (SELECT 'bar':::typ83496 FROM t83496 WHERE false)
>   IS NOT DISTINCT FROM CASE WHEN NULL THEN NULL ELSE NULL END
> ```

There's a few things going on here that prevent this type of expression in Postgres.

1. Postgres will type a `CASE` expressions as `TEXT` when all branches are of type `UNKNOWN`. https://www.postgresql.org/docs/8.1/typeconv-union-case.html
2. There is no `IS DISTINCT FROM` operator between enums and `TEXT`.

```
marcus=# SELECT pg_typeof(CASE WHEN NULL THEN NULL ELSE NULL END);
 pg_typeof
-----------
 text
(1 row)


marcus=# CREATE TYPE my_type AS ENUM ('foo', 'bar');
CREATE TYPE

marcus=# SELECT 'foo'::my_type IS DISTINCT FROM (CASE WHEN NULL THEN NULL ELSE NULL END);
ERROR:  42883: operator does not exist: my_type = text
LINE 1: SELECT 'foo'::my_type IS DISTINCT FROM (CASE WHEN NULL THEN ...
                              ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
```

I think (1) could be a breaking change, but it'd probably affect very few real-world use cases. I think we currently have behavior similar to (2), so I don't think any further change would be necessary.

The question is: are there other cases beside `CASE` that can cause `anyenum`s to leak into execution?

**Comment by mgartner** [comment]
*[`pkg/sql/logictest/testdata/logic_test/distsql_enum` line 104 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90461#-NFUgFIwEXqNNcLWC4Gj:-NFV5NeLBDXMgwSiui3b:bgw5w9) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3fcb2e4038322d8b985f47047da06b046b2dd0/pkg/sql/logictest/testdata/logic_test/distsql_enum#L104)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

There's a few things going on here that prevent this type of expression in Postgres.

1. Postgres will type a `CASE` expressions as `TEXT` when all branches are of type `UNKNOWN`. https://www.postgresql.org/docs/8.1/typeconv-union-case.html
2. There is no `IS DISTINCT FROM` operator between enums and `TEXT`.

```
marcus=# SELECT pg_typeof(CASE WHEN NULL THEN NULL ELSE NULL END);
 pg_typeof
-----------
 text
(1 row)


marcus=# CREATE TYPE my_type AS ENUM ('foo', 'bar');
CREATE TYPE

marcus=# SELECT 'foo'::my_type IS DISTINCT FROM (CASE WHEN NULL THEN NULL ELSE NULL END);
ERROR:  42883: operator does not exist: my_type = text
LINE 1: SELECT 'foo'::my_type IS DISTINCT FROM (CASE WHEN NULL THEN ...
                              ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
```

I think (1) could be a breaking change, but it'd probably affect very few real-world use cases. I think we currently have behavior similar to (2), so I don't think any further change would be necessary.

The question is: are there other cases beside `CASE` that can cause `anyenum`s to leak into execution?
</blockquote></details>

I experimented with improving our type checking of CASE expressions: https://github.com/cockroachdb/cockroach/pull/90867

It's certainly looking like a deep rabbit hole. Maybe there's a natural stopping point soon I can find after I return from PTO.

**Comment by postamar** [comment]
👍 
I'm going to hold off merging this. We can reopen this PR if needed.

**Pull request closed without merging**
