### PR TITLE
cli: ensure that `debug zip` captures the cluster settings.

### PR DESCRIPTION
**Pull request by knz**
cc @tamird for the admin endpoint changes.

### CODE REVIEW

**Comment by tamird** [comment]
first commit needs to regenerate pkg/ui/embedded.go.

---

Reviewed 7 of 8 files at r1.
Review status: 7 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/server/admin_test.go, line 847 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15207#-KiB94ov3senb-niG8Em:-KiB94ov3senb-niG8En:b-skcy3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/36fe303adcc14a205bd319fa05420f37f4faf852/pkg/server/admin_test.go#L847)):*
> ```Go
> 			if v.Value != "true" {
> 				t.Errorf("%s: expected true, got %s", k, v.Value)
> 			}
> ```

break?

---

*[pkg/server/admin_test.go, line 852 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15207#-KiB973xY6RKzPQkvxa5:-KiB973xY6RKzPQkvxa6:b-ndry6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/36fe303adcc14a205bd319fa05420f37f4faf852/pkg/server/admin_test.go#L852)):*
> ```Go
> 
> 	if !seenRef {
> 		t.Fatalf("failed to observe test setting %s", settingKey)
> ```

how about logging `resp.KeyValues`, too? this error message is not useful currently.

---

*[pkg/server/admin_test.go, line 870 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15207#-KiB9KxrXT4UxlxX0rbg:-KiB9KxrXT4UxlxX0rbh:bukkrjc) ([raw file](https://github.com/cockroachdb/cockroach/blob/36fe303adcc14a205bd319fa05420f37f4faf852/pkg/server/admin_test.go#L870)):*
> ```Go
> 	seenRef = false
> 
> 	// All the settings keys must be retrievable, and their
> ```

this test could be structured better. In my understanding, you want to test:
- get all keys
- get individual keys

You're also testing changing a key and returning it, but I don't think that's necessary. The other cases above should be subtests.

---

*[pkg/server/serverpb/admin.proto, line 331 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15207#-KiB8o_g7Nc_kEm-N3Ox:-KiB8o_g7Nc_kEm-N3Oy:b1af8jy) ([raw file](https://github.com/cockroachdb/cockroach/blob/36fe303adcc14a205bd319fa05420f37f4faf852/pkg/server/serverpb/admin.proto#L331)):*
> ```protobuf
> // SettingsRequest inquires what are the current settings in the cluster.
> message SettingsRequest {
>   repeated string keys = 1;
> ```

explain that empty means all?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15207#-:-KiB8ej-7K5dT1dalC4n:bvuidsg)*

**Comment by knz** [comment]
embedded.go is regenerated. Thanks

---

Review status: 7 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/server/admin_test.go, line 847 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15207#-KiB94ov3senb-niG8Em:-KiBABA0YvGwiFBt9mEc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/36fe303adcc14a205bd319fa05420f37f4faf852/pkg/server/admin_test.go#L847)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

break?
</blockquote></details>

Done.

---

*[pkg/server/admin_test.go, line 852 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15207#-KiB973xY6RKzPQkvxa5:-KiBAKWGP1TemnjbA2jc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/36fe303adcc14a205bd319fa05420f37f4faf852/pkg/server/admin_test.go#L852)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

how about logging `resp.KeyValues`, too? this error message is not useful currently.
</blockquote></details>

Done.

---

*[pkg/server/admin_test.go, line 870 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15207#-KiB9KxrXT4UxlxX0rbg:-KiBBtIx7rvq5CU9o88F:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/36fe303adcc14a205bd319fa05420f37f4faf852/pkg/server/admin_test.go#L870)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this test could be structured better. In my understanding, you want to test:
- get all keys
- get individual keys

You're also testing changing a key and returning it, but I don't think that's necessary. The other cases above should be subtests.
</blockquote></details>

Done.

---

*[pkg/server/serverpb/admin.proto, line 331 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15207#-KiB8o_g7Nc_kEm-N3Ox:-KiBD4YpKeeWwYWMqXza:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/36fe303adcc14a205bd319fa05420f37f4faf852/pkg/server/serverpb/admin.proto#L331)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

explain that empty means all?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15207#-:-KiBA3Vki2TNB78bhYHJ:b-twwn0m)*

**Comment by tamird** [comment]
Reviewed 5 of 5 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/server/admin_test.go, line 863 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15207#-KiBFiLClbOpdL18cfW-:-KiBFiLClbOpdL18cfW0:b-dtba8d) ([raw file](https://github.com/cockroachdb/cockroach/blob/b386e39db4af2706a9d774cc97010b0d0c2a65b0/pkg/server/admin_test.go#L863)):*
> ```Go
> 
> 		// All the settings keys must be retrievable, and their
> 		// type and description must match.
> ```

you don't check types and descriptions in the "all" case?

---

*[pkg/server/admin_test.go, line 879 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15207#-KiBFUfaG52S3iuzecih:-KiBFUfbJKZB_Rzrzwam:b-6u6w9q) ([raw file](https://github.com/cockroachdb/cockroach/blob/b386e39db4af2706a9d774cc97010b0d0c2a65b0/pkg/server/admin_test.go#L879)):*
> ```Go
> 			}
> 
> 			ref, desc, _ := settings.Show(k)
> ```

what are you ignoring here?

---

*[pkg/server/admin_test.go, line 902 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15207#-KiBFXL6pvzV0RS8zJc5:-KiBFXL6pvzV0RS8zJc6:bnufwwm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b386e39db4af2706a9d774cc97010b0d0c2a65b0/pkg/server/admin_test.go#L902)):*
> ```Go
> 
> 		if !seenRef {
> 			t.Fatalf("failed to observe test setting %s", settingKey)
> ```

same unhelpful error

---

*[pkg/server/serverpb/admin.proto, line 330 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15207#-KiBFAhGlDJyEpVGs5OG:-KiBFAhGlDJyEpVGs5OH:bb2uoxi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b386e39db4af2706a9d774cc97010b0d0c2a65b0/pkg/server/serverpb/admin.proto#L330)):*
> ```protobuf
> 
> // SettingsRequest inquires what are the current settings in the cluster.
> // An empty keys array means "all".
> ```

more appropriate on the field, not here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15207)*

**Comment by knz** [comment]
Review status: 6 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/server/admin_test.go, line 863 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15207#-KiBFiLClbOpdL18cfW-:-KiBcUSDfzAo1U4DRh87:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b386e39db4af2706a9d774cc97010b0d0c2a65b0/pkg/server/admin_test.go#L863)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

you don't check types and descriptions in the "all" case?
</blockquote></details>

Done.

---

*[pkg/server/admin_test.go, line 879 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15207#-KiBFUfaG52S3iuzecih:-KiBbq3rwjCmwANhRG8k:b-mlbybb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b386e39db4af2706a9d774cc97010b0d0c2a65b0/pkg/server/admin_test.go#L879)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

what are you ignoring here?
</blockquote></details>

Added clarification in comment.

---

*[pkg/server/admin_test.go, line 902 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15207#-KiBFXL6pvzV0RS8zJc5:-KiBcUtg4Lrd7GdsgeI8:b-pesxb8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b386e39db4af2706a9d774cc97010b0d0c2a65b0/pkg/server/admin_test.go#L902)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

same unhelpful error
</blockquote></details>

This one is already checked, so I removed it.

---

*[pkg/server/serverpb/admin.proto, line 330 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15207#-KiBFAhGlDJyEpVGs5OG:-KiBdwqnCreFDQDKyEbr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b386e39db4af2706a9d774cc97010b0d0c2a65b0/pkg/server/serverpb/admin.proto#L330)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

more appropriate on the field, not here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15207)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/server/admin_test.go, line 825 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15207#-KiBeRLugjEn0FNFSP5S:-KiBeRLugjEn0FNFSP5T:bg1tx3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/711f60403d5c68ea4c923b9889543a5da035fcd3/pkg/server/admin_test.go#L825)):*
> ```Go
> 
> 	checkSetting := func(t *testing.T, k string, v serverpb.SettingsResponse_Value) {
> 		// We do not need to check the 3rd return value because the key
> ```

seems simpler to just check it, but ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15207#-:-KiBeXPS-Q769QkwIgoi:bnfp4nl)*

**Comment by knz** [comment]
Review status: 6 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/server/admin_test.go, line 825 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15207#-KiBeRLugjEn0FNFSP5S:-KiBoFk3cVTy1BkGenz-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/711f60403d5c68ea4c923b9889543a5da035fcd3/pkg/server/admin_test.go#L825)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

seems simpler to just check it, but ok
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15207)*

**Comment by tamird** [comment]
Reviewed 5 of 5 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15207)*

**Pull request merged**
