### PR TITLE
Makefile: improve readability

### PR DESCRIPTION
**Pull request by benesch**

### CODE REVIEW

**Comment by tschottdorf** [comment]
:lgtm:. Rob Pike would be proud.

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26160#-:-LDfickv2nCT1rzXW_jX:b-9rewyz)*

**Review by knz — APPROVED** [review]
I'm not sure it's indeed more readable, but whatever, it's correct.

**Comment by benesch** [comment]
bors r=tschottdorf,knz

**Comment by benesch** [comment]
bors r=tschottdorf,knz

**Pull request merged**
