### PR TITLE
roachtest: retry failed node liveness queries in disk-full test

### PR DESCRIPTION
**Pull request by nicktrav**
Currently, when querying for node liveness in `disk-full`, a query may
hang indefinitely, failing the test only after it has timed out
(currently after 10 hours).

Add retry logic for the node liveness query. The query is cancelled
after a second, and exponentially retries for up to (approximately) one
minute.

Release note: None.

Touches #78337, #78349.

### CODE REVIEW

**Comment by nicktrav** [comment]
Did a [stress run](https://teamcity.cockroachdb.com/viewLog.html?buildId=4656317&tab=buildLog#_state=), just to validate this wasn't breaking anything else (it doesn't really test the retry logic, as for the most part the query succeeds first time).

**Review by jbowens — COMMENTED** [review]
do we know why the query hangs?

shouldn't querying this gossip virtual table always complete?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78380#-:-Myx4CAb-Z-tho6C-JX5:bw03art)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal)

**Review by nicktrav — COMMENTED** [review]
> shouldn't querying this gossip virtual table always complete?

I don't know the answer to this.

> do we know why the query hangs?

I think something might be happening below the query (i.e. in the networking stack). The query requires a network round trip (it opens a connection to node 2): Here's the stack for the hung goroutine, which shows that it's waiting on a response on the socket: https://github.com/cockroachdb/cockroach/issues/78337#issuecomment-1076705811

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78380#-:-Myx6-lP8EqqIbD4xD-k:bsmprht)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal)

**Review by jbowens — APPROVED** [review]
the retry logic :lgtm:

is this a reproducible failure? If we can get a reproduction, it might help to inspect the queried node to ensure the node isn't stalled in servicing the request due to a deadlock or something else.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78380#-:-MyxRRSJDaNFplmJnA42:bkfhb1m)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal)

**Comment by nicktrav** [comment]
Closing in favor of #78456, which fixes the underlying race condition in the test.

**Pull request closed without merging**
