### PR TITLE
concurrency: non-locking reads of RC txns ignore exclusive locks

### LINKED ISSUE #94729: kv: non-locking reads ignore exclusive locks
See https://github.com/cockroachdb/cockroach/issues/49684 for context. If we differentiate between exclusive locks and intents, then we don't need non-locking reads to wait on exclusive locks. See also [this document](https://docs.google.com/document/d/1ji6C0aDI6n61sVKPjf5-YUucbtgBlwfpsrNdcidW5a0/edit).

Before we do this, we'll likely want something like https://github.com/cockroachdb/cockroach/issues/91417. This was also described in https://github.com/cockroachdb/cockroach/issues/49684#issuecomment-848400422.

Jira issue: CRDB-23103

Epic CRDB-26544

### PR DESCRIPTION
**Pull request by arulajmani**
Non-locking reads issued by transactions that can tolerate write-skew
do not block on exclusive locks after this patch.

Resolves https://github.com/cockroachdb/cockroach/issues/94729

Release note: None

### CODE REVIEW

**Comment by arulajmani** [comment]
@nvanbenschoten feel free to hold off on the review until we've landed the other PRs; I just wanted to get this out before addressing comments on those ones.

**Comment by arulajmani** [comment]
@nvanbenschoten this should be good for a look now!

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106316#-:-N_uPS9TCwzxrfrEHIt7:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/concurrency/testdata/lock_table/read_committed` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106316#-N_uOv2o6ZmclNunAAil:-N_uOv2o6ZmclNunAAim:bbqjkgi) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a174e27ca85eb3cfe662681a8875d7b37536697/pkg/kv/kvserver/concurrency/testdata/lock_table/read_committed#L7)):*
> ```
> ----
> 
> new-txn txn=txn2 ts=10,1 epoch=0 iso=read-committed
> ```

Want to call this file `isolation_level` and make this txn `snapshot` iso?
___
*[`pkg/kv/kvserver/concurrency/testdata/lock_table/read_committed` line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106316#-N_uOW4D4ZqHWVpQ0iuK:-N_uOW4D4ZqHWVpQ0iuL:b-2ajut9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a174e27ca85eb3cfe662681a8875d7b37536697/pkg/kv/kvserver/concurrency/testdata/lock_table/read_committed#L15)):*
> ```
> # ------------------------------------------------------------------------------
> # Test that non-locking reads from RC transactions do not block on exclusive
> # exclusive locks held by other RC/Serializable transactions.
> ```

"exclusive exclusive"
___
*[`pkg/kv/kvserver/concurrency/testdata/lock_table/read_committed` line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106316#-N_uOlYV4wFaflX_kBm6:-N_uOlYV4wFaflX_kBm7:bbuo6xn) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a174e27ca85eb3cfe662681a8875d7b37536697/pkg/kv/kvserver/concurrency/testdata/lock_table/read_committed#L88)):*
> ```
> num=1
>  lock: "a"
>   holder: txn: 00000000-0000-0000-0000-000000000002 epoch: 0, ts: 10.000000000,1, info: repl
> ```

Should we include the isolation level in this output? Maybe at least for non-SSI lock holders?
___
*[`pkg/kv/kvserver/concurrency/lock_table_test.go` line 731 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106316#-N_uOFJ38pfEvxz_Qqyc:-N_uOFJ44ZLZYxq0cwIp:b-bh5gxy) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a174e27ca85eb3cfe662681a8875d7b37536697/pkg/kv/kvserver/concurrency/lock_table_test.go#L731)):*
> ```Go
> }
> 
> func ScanIsoLevel(t *testing.T, d *datadriven.TestData) isolation.Level {
> ```

nit: don't split `ScanLockStrength` from `scanLockStrength`.

**Review by arulajmani — COMMENTED** [review]
TFTR! 

bors r=nvanbenschoten 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106316#-:-Na8YwUz30yz8XP_W9X3:b-2fjird)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/concurrency/lock_table_test.go` line 731 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106316#-N_uOFJ38pfEvxz_Qqyc:-Na8S5e_1wNB_fk6H1V9:b-amiicx) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a174e27ca85eb3cfe662681a8875d7b37536697/pkg/kv/kvserver/concurrency/lock_table_test.go#L731)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: don't split `ScanLockStrength` from `scanLockStrength`.
</blockquote></details>

Did you mean `getStrength`? If so, done.
___
*[`pkg/kv/kvserver/concurrency/testdata/lock_table/read_committed` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106316#-N_uOv2o6ZmclNunAAil:-Na8X2CW4W3YFSRWgK3L:bsdh07x) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a174e27ca85eb3cfe662681a8875d7b37536697/pkg/kv/kvserver/concurrency/testdata/lock_table/read_committed#L7)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Want to call this file `isolation_level` and make this txn `snapshot` iso?
</blockquote></details>

Good call. I changed the file name and extended these tests to cover snapshot transactions as well. It was a bit more involved than changing the isolation level of this transaction, but the test coverage is much better now.
___
*[`pkg/kv/kvserver/concurrency/testdata/lock_table/read_committed` line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106316#-N_uOlYV4wFaflX_kBm6:-Na8Yai53_koL0FEtG5-:b-u0gal9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a174e27ca85eb3cfe662681a8875d7b37536697/pkg/kv/kvserver/concurrency/testdata/lock_table/read_committed#L88)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we include the isolation level in this output? Maybe at least for non-SSI lock holders?
</blockquote></details>

That's a good call. I ended up including isolation level information for all transactions, not just SI and RC; there's quite some test churn, but IMO it's trivial, so no point special casing. It's the second commit that I tacked on this PR.

**Pull request merged**
