### PR TITLE
kv: check transaction status before recording refresh spans

### LINKED ISSUE #29253: sql: transaction is too large error during batch insert with background read requests
- Which version of CockroachDB are you using?

CCL v2.0.5 @ 2018/08/13 17:59:42 (go1.10)

- What did you do?

1. Create a table with 3 columns (primary key, foreign key, secondary index).
2. Create a background routine which selects from the table.
3. Try to batch insert 1000 rows.

I've made a complete reproduction:
https://gist.github.com/chessman/739424c341b4d7821661d4468be7ae2f

The behavior may be worse or better if you change select intensity or add more columns to the table.

- What did you expect to see?

Insert successfully completed.

- What did you see instead?

`pq: transaction is too large to complete; try splitting into pieces`

But the data is actually inserted into the table.

- What was the impact?

It is hard to choose a batch size because it depends not only on data size but on read requests. I can't be sure that my batch size is not too large in production during heavy read.

### PR DESCRIPTION
**Pull request by nvb**
Fixes #29253.

We previously accounted for refresh spans before checking the
transaction's status. This meant that we would attempt to add new
refresh spans even if the txn had already been committed. If this
attempt failed because the `max_refresh_spans_bytes` threshold was
exceeded, we would erroneously return an error to the client even
though their transaction had already been committed. The simple
fix for this is to only record refresh spans for transactions that
are still PENDING. The new test case would have failed with the
error observed in #29253 without this fix.

This raises an auxiliary question about whether we should be asserting
that a transaction's status is not COMMITTED if we ever return an
error to the client. cc. @andreimatei.

On the positive side, this should be a minor perf win, as we'll
avoid recording refresh spans on the final batch of every txn.

A similar fix will need to be backported to 2.0. The backport
won't be clean though because of the new txnInterceptor structure.
However, the test shouldn't need to change.

Release note (bug fix): Don't return transaction size limit errors
for transactions that have already committed.

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
The patch looks good, but I'm a bit confused - how exactly was a client getting this error (can you spell out the test pls)? Like, it seems to me that we only generate the error if the txn has been pushed - but how does it commit if it has been pushed (without attempting a refresh)? Is this because of the server-side optimization around the "doesn't have any refresh spans yet to check" flag on the commit?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29685#-:-LLojE-w2YYGVaRcb76R:b1uov7d)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by nvanbenschoten** [comment]
> Is this because of the server-side optimization around the "doesn't have any refresh spans yet to check" flag on the commit?

Yes, that's exactly what's happening in the first test case. I also added a second test case because it's actually possible that the final batch causes a refresh and still commits. This doesn't hit the refresh span limit because the transaction commits before the limit needs to be checked. This too should succeed without error.

PTAL

**Comment by nvanbenschoten** [comment]
> This doesn't hit the refresh span limit because the transaction commits before the limit needs to be checked. 

FWIW, I gave this some thought and convinced myself that this is the desired behavior. The purpose of the refresh span limit is to prevent the `TxnCoordSender` from consuming too much memory between statements when the txn could live on for an unbounded period of time. If the `TxnCoordSender` needs to consume extra memory while it's attempting to commit, it should be allowed to. After all, this memory is proportional to the size of the `BatchRequest` anyway.

**Comment by andreimatei** [comment]
LGTM

**Pull request merged**
