### PR TITLE
ui: hide node, regions, diagnostics on serverless

### PR DESCRIPTION
**Pull request by maryliag**
Hiding information about nodes, regions and diagnostics
on Statements, Statements Details, Transactions, Sessions
and Session details.

Also stop the refresh of info for node and diagnostics on
these pages.

Release justification: Category 4 - Low risk, high benefit changes
Release note: None

### CODE REVIEW

**Review by matthewtodd — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69803#-:-Mj-mkKfCc4WvD99r2R6:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag)

**Review by Azhng — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69803#-:-Mj-n8s254cgMcA7_I9b:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @maryliag)

**Pull request merged**
