### PR TITLE
colexec: change the behavior of vectorize=experimental_always

### PR DESCRIPTION
**Pull request by yuzefovich**
Depends on #50895.

**tree: minor clean up of explain**

NoNormalize explain option is not used anymore, so this commit removes
it. Additionally, we now treat `DEBUG` as a proper explain option.

Release note: None

**colexec: change the behavior of vectorize=experimental_always**

This commit changes the behavior of the planning when `vectorize` is set
to `experimental_always` - it now prohibits wrapping any processor cores
into the vectorized plan (with the only exception being
`core.JoinReader` for now since lookup and index joins are very popular
and have been the first ones to be wrapped).

There is no release note because the change is visible for the private
session variable value that we have mostly for internal purposes.

Release note: None

### CODE REVIEW

**Review by asubiotto — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50801)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/op_creation.go, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50801#-MB3fxxr5G9NdnVTGP7c:-MB3fxxs6dYPy9vqHARf:b-wvjmjf) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc3c47f6ecf03ded45fe41ecf8a96ac462696f4b/pkg/sql/colexec/op_creation.go#L43)):*
> ```Go
> 	// DisableProcessorWrapping indicates whether wrapping of row-execution
> 	// processors into the vectorized flow is prohibited (the only processor
> 	// core that ignores this flag is JoinReader).
> ```

Explain why `JoinReader` is ignored. We might want to create a columnarized join reader at some point though to avoid a conversion step so maybe we shouldn't ignore this flag in the join reader case?

**Review by andreimatei — COMMENTED** [review]
Consider including this information in what gets collected by a statement bundle.

Am I right to read that`EXPLAIN(VEC,DEBUG)` returns an error if the plan is not vectorized? This seems very surprising to me; that's not how I'd expect an `EXPLAIN` to behave. At the very lease call it out in the  commit message. I'd consider including this info into the trace instead of introducing this statement.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50801#-:-MB4Y6xd7vqAGc_TEAb0:bk7ii3m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colflow/vectorized_flow.go, line 475 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50801#-MB4XPcV-hy04DEO6tKD:-MB4XPcV-hy04DEO6tKE:b-y1coq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc3c47f6ecf03ded45fe41ecf8a96ac462696f4b/pkg/sql/colflow/vectorized_flow.go#L475)):*
> ```Go
> 	fdSemaphore semaphore.Semaphore,
> 	forceExprDeserialization bool,
> 	disableProcessorWrapping bool,
> ```

So many bools in this signature... Consider turning them all to enums.

**Review by yuzefovich — COMMENTED** [review]
Andrei, thanks for driving by!

> Consider including this information in what gets collected by a statement bundle.

I thought about this before I opened the PR, and it didn't seem trivial, so I'll leave a TODO for this.

> Am I right to read that `EXPLAIN(VEC,DEBUG)` returns an error if the plan is not vectorized?

Yes, it's exactly the intended behavior.

> I'd consider including this info into the trace instead of introducing this statement.

The goal of this feature is to provide an easy way to see the support for which part of the query is missing from the vectorized engine. The intended workflow is something like: a savvy user runs `EXPLAIN (VEC)` on the query and sees `rowexec.<some processor>`, so they think it's weird, why isn't everything vectorized, so they run `EXPLAIN (VEC, DEBUG)` which returns the first error of a feature that is not supported. To be honest, I don't think that many external users will actually take advantage of this feature, but if they do, `DEBUG` option naming sounds to me like a reasonable warning of possibly unexpected behavior.

Updated the commit message.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50801#-:-MB5JKuH-czXeoF36LPl:b-kgqqgx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @asubiotto)

___
*[pkg/sql/colexec/op_creation.go, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50801#-MB3fxxr5G9NdnVTGP7c:-MB4qC98CrKgb9bvc_aK:bhoq2px) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc3c47f6ecf03ded45fe41ecf8a96ac462696f4b/pkg/sql/colexec/op_creation.go#L43)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Explain why `JoinReader` is ignored. We might want to create a columnarized join reader at some point though to avoid a conversion step so maybe we shouldn't ignore this flag in the join reader case?
</blockquote></details>

My reasoning is that so far `core.JoinReader` has been treated differently - it was the first core that we were wrapping, it is the only core that is allowed to be wrapped with `vectorize=201auto`, and I think we don't have any immediate plans of writing a vectorized operator for this core. Another thing is that lookup and index joins are quite popular, so for queries with them I would be interested in why other things might be getting wrapped. My goal for this feature is to show the first error that we get during vectorized planning, and if in `EXPLAIN (VEC)` I see that there is a lookup or index join, I will know that it must be wrapped because we don't have an equivalent operator, I'm queries about other things.

That said, if we do make an equivalent operator, then we could adjust the behavior of the feature accordingly.
___
*[pkg/sql/colflow/vectorized_flow.go, line 475 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50801#-MB4XPcV-hy04DEO6tKD:-MB5HKBU4IkvSwvYaUcv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc3c47f6ecf03ded45fe41ecf8a96ac462696f4b/pkg/sql/colflow/vectorized_flow.go#L475)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

So many bools in this signature... Consider turning them all to enums.
</blockquote></details>

Done.

**Comment by andreimatei** [comment]
Can we really not make the output of `EXPLAIN (VEC)` include this info?

**Review by yuzefovich — COMMENTED** [review]
> Can we really not make the output of `EXPLAIN (VEC)` include this info?

I think "vanilla" `EXPLAIN (VEC)` serves a different purpose - of showing the tree of vectorized operators and should not show these errors that were "causes to wrap", so I definitely think this feature should be exposed with some special option.

However, I'm open to ideas on how to display it best: should the query return an error? Maybe, instead, we should accumulate all "causes to wrap" and display them altogether, after (or before) we print out the tree with wrapped processors? We have `EXPLAIN (VEC, VERBOSE)`, should we include this feature as part of that explain-vec variant? @asubiotto @jordanlewis curious to hear your thoughts.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50801#-:-MB5r2wR7RMVJH7t-DaE:b-2xz479)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @asubiotto)

**Review by andreimatei — COMMENTED** [review]
> I think "vanilla" EXPLAIN (VEC) serves a different purpose - of showing the tree of vectorized operators and should not show these errors that were "causes to wrap", so I definitely think this feature should be exposed with some special option.

What exactly shows up now in `EXPLAIN (VEC)` for these wrappers? Would it not be perfectly reasonable to include the reason for the wrapper right next to the wrapper's name in that output? Perhaps only under `EXPLAIN(VEC,DEBUG)` or `EXPLAIN(VEC,VERBOSE)`, although I wouldn't bother.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50801#-:-MB620Tl8zx8N6tvqXgv:b-5vhmty)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @asubiotto)

**Review by yuzefovich — COMMENTED** [review]
For example, this is the current plan for TPCH Query 22 on a single node cluster:
```
│
└ Node 1
  └ *colexec.sortOp
    └ *rowexec.hashAggregator
      └ *colexec.hashJoiner
        ├ *colexec.mergeJoinLeftAntiOp
        │ ├ *colfetcher.colBatchScan
        │ └ *colexec.selRegexpBytesBytesConstOp
        │   └ *colfetcher.colBatchScan
        └ *colexec.selectInOpInt64
          └ *colexec.selNotPrefixBytesBytesConstOp
            └ *colexec.selNEBytesBytesConstOp
              └ *colfetcher.colBatchScan
```
Note that there is a `rowexec.hashAggregator` "wrapped" into the plan. This output is populated by traversing `execinfra.OpNode` tree.

I think it'll be pretty hard (at least harder than the current approach) to add a "tag" to such wrapped processors with the reason they were wrapped. It's an interesting idea though, we probably will discuss it during standup tomorrow.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50801#-:-MB62gAV5FlOH7aa2agg:b-pismbn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @asubiotto)

**Comment by asubiotto** [comment]
> Am I right to read thatEXPLAIN(VEC,DEBUG) returns an error if the plan is not vectorized? This seems very surprising to me; that's not how I'd expect an EXPLAIN to behave

I think @andreimatei has a point. What was the reason to discard `experimental_always`? I think that that's exactly why the setting exist.

**Review by yuzefovich — COMMENTED** [review]
`experimental_always` so far has meant that only the vectorized engine is allowed to be used to run the queries (the only exception is SET statements), meaning that if the vectorized flow is not supported (note that "wrapping" a processor into the vectorized flow is considered as "supported" in this scenario), then the query errors out instead of planning row-based flow.

That said, we're now supporting wrapping of most processor cores, so it should be unlikely that we have to fallback to row-based flow on any given query (the biggest exception currently is "LocalProcessors" which are wrapped planNodes). So do you guys think about changing the meaning of `experimental_always`? I think that setting is somewhat orthogonal to the feature that I want to have, but I'm open to ideas.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50801#-:-MB9nDX4BkQlVYsTAzUa:b-krzg8t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @asubiotto)

**Comment by awoods187** [comment]
I'm not a fan of adding yet another EXPLAIN variant. I think we need to be collapsing the number of EXPLAINs not adding to it. I can't see many users understanding the output of EXPLAIN(VEC) well enough to trigger EXPLAIN(VEC DEBUG) and then understanding that well enough to what, report to us we haven't built the feature needed? Or to re-write their query to not use it, if they can even figure out how to do it? This seems like an internal tool that helps us understand what else is practically needing to be built and I think we shouldn't expose this, or if we think its necessary, fold it into EXPLAIN (VEC).

**Review by yuzefovich — COMMENTED** [review]
Thanks everyone for the input! We agreed that the best way forward is adjusting the behavior of `experimental_always` setting so that the wrapping is prohibited instead of introducing a new explain variant. This PR now depends on #50895, but last two commits are RFAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50801#-:-MBBgo674XGFT2HrP6WH:b-u1dl1v)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @asubiotto)

**Comment by asubiotto** [comment]
Can you ping once you rebase?

**Comment by yuzefovich** [comment]
Rebased

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 15 of 15 files at r3, 24 of 24 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50801#-:-MBc_33V9z4cIj-IRvMA:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Pull request merged**
