### PR TITLE
jobsccl: remove some uses of TODOTestTenantDisabled, simplify test code

### PR DESCRIPTION
**Pull request by knz**
First commits from #107135.

Epic: CRDB-18499
Informs #76378.

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, 6 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106928#-:-N__KzQRC99-HVKZQnkM:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling, @herkolategan, @knz, @rhu713, @srosenberg, and @stevendanna)

___
*[`pkg/server/systemconfigwatcher/systemconfigwatchertest/test_system_config_watcher.go` line 43 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/106928#-N__Jz2s0rXwBrR3EPNH:-N__Jz2t4yPZnCuMV7td:bz0jx6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/47d6732b44b14e95aed9f6856af93006a26d2203/pkg/server/systemconfigwatcher/systemconfigwatchertest/test_system_config_watcher.go#L43)):*
> ```Go
> // TestSystemConfigWatcher is a test which exercises the end-to-end integration
> // of the systemconfigwatcher. It exists in this subpackage so that it can be
> // run to exercise secondary tenants, which are ccl-only.
> ```

Should we refactor this testing helper to be a proper test itself, which enables the ccl features and runs both system and secondary tenants?
___
*[`pkg/testutils/serverutils/test_tenant_shim.go` line 117 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/106928#-N__KZ6tC1p9FjgfLCP4:-N__KZ6tC1p9FjgfLCP5:beplqsw) ([raw file](https://github.com/cockroachdb/cockroach/blob/abf94056d983de023b05d96bab8d0ec40e461380/pkg/testutils/serverutils/test_tenant_shim.go#L117)):*
> ```Go
> 
> 	// InternalExecutor returns a *sql.InternalExecutor as an interface{} (which
> 	// also implements insql.InternalExecutor if the test cannot depend on sql).
> ```

nit: `s/insql/isql/`.
___
*[`pkg/server/admin_test.go` line 145 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/106928#-N__KpYD3esHrx7aWz0S:-N__KpYD3esHrx7aWz0T:b-vh5yak) ([raw file](https://github.com/cockroachdb/cockroach/blob/abf94056d983de023b05d96bab8d0ec40e461380/pkg/server/admin_test.go#L145)):*
> ```Go
> 	s, _, _ := serverutils.StartServer(t, base.TestServerArgs{
> 		// Disable the default test tenant for now as this tests fails with
> 		// it enabled. Tracked with #81590.
> ```

Seems like the last commit closes #81590.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106928)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling, @herkolategan, @rhu713, @srosenberg, @stevendanna, and @yuzefovich)

___
*[`pkg/server/systemconfigwatcher/systemconfigwatchertest/test_system_config_watcher.go` line 43 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/106928#-N__Jz2s0rXwBrR3EPNH:-N_cITvV9R9uzej4Y2N0:b-e95wnt) ([raw file](https://github.com/cockroachdb/cockroach/blob/47d6732b44b14e95aed9f6856af93006a26d2203/pkg/server/systemconfigwatcher/systemconfigwatchertest/test_system_config_watcher.go#L43)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Should we refactor this testing helper to be a proper test itself, which enables the ccl features and runs both system and secondary tenants?
</blockquote></details>

Good idea, filed  #107058 to track.
___
*[`pkg/testutils/serverutils/test_tenant_shim.go` line 117 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/106928#-N__KZ6tC1p9FjgfLCP4:-N_cIe8A3XnYEASQF-Aq:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/abf94056d983de023b05d96bab8d0ec40e461380/pkg/testutils/serverutils/test_tenant_shim.go#L117)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `s/insql/isql/`.
</blockquote></details>

Fixed.
___
*[`pkg/server/admin_test.go` line 145 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/106928#-N__KpYD3esHrx7aWz0S:-N_cIfIy5NDvDKAPXiwp:bt09b5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/abf94056d983de023b05d96bab8d0ec40e461380/pkg/server/admin_test.go#L145)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Seems like the last commit closes #81590.
</blockquote></details>

Sadly it does not -- this only covers the debug interface, but all the SQL introspection APIs (get db details etc) are not done yet.

**Comment by knz** [comment]
TFYR

bors r=yuzefovich

**Comment by knz** [comment]
bors r=yuzefovich

**Comment by knz** [comment]
bors r=yuzefovich

**Comment by knz** [comment]
bors r=yuzefovich

**Pull request merged**
