### PR TITLE
go.mod: bump Pebble to 16bf77ee4012

### PR DESCRIPTION
**Pull request by RaduBerinde**
16bf77ee shared: add IsNotExistError method to shared.Storage
93eff0a7 manifest: remove struct Atomic from FileBacking
6bf568d8 manifest: use atomic types in FileMetadata
67895e1d manifest: don't copy FileMetadata by value
7d5a3b7c db: use atomic types in Db
a664f69f replay: use atomic types
9de87a35 vfs: use atomic.Uint32 for disk full generation
75b78212 pebble: use atomic.Int32 for memTable.writerRefs
44af3316 cmd/pebble: use atomic types
5e9ccb46 pebble: use atomic type in commitQueue
41fce88e *: use atomic types in tests
e0a52f16 pebble: add TODO for FilterMetrics
18af1e35 pebble: use atomic types in table cache
49137e40 pebble: use atomic.Uint64 for sequence numbers
e808d80d pebble: use atomic.Int32 for iterCount in tableCacheOpts
37f6c795 pebble: use atomic.Bool for Batch.applied
c865bc3c pebble: use atomic.Int64 for TableCache refs

Release note: none
Epic: none

### CODE REVIEW

**Review by nicktrav — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100739#-:-NSIAila1wuKx7j7OpvC:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal)

**Comment by RaduBerinde** [comment]
TFTR!

bors r+

**Pull request merged**
