### PR TITLE
nightly: create package for nightly tests, incl. partitioning

### PR DESCRIPTION
**Pull request by benesch**
@danhhz this is as far as I'll probably get before next week. It mostly works but still needs some cleanup.

---

Move new-style nightly tests--i.e., those that use roachperf--into a
dedicated nightly package, and add partitioning tests to the suite.

Release note: None

### CODE REVIEW

**Comment by benesch** [comment]
Ugh, don't review this yet. Some unrelated changes slipped in. I'll clean those up later tonight.

**Comment by petermattis** [comment]
@benesch I ignored your advice and left some comments. Hopefully not on the parts that will be cleaned up. The direction looks good. I'm excited for this to go in as there are pieces I want to hack on.

---

Review status: 0 of 7 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/nightly/nightly_test.go, line 35 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4DxuU1S2BFkBRwX0Ux:-L4DxuU1S2BFkBRwX0Uy:b9ap5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/485df2e13f74647ae6b1732ec59494299325ed6d/pkg/nightly/nightly_test.go#L35)):*
> ```Go
> var skipTests = true
> 
> func maybeSkip(t testing.TB) {
> ```

Did you intend to call this?

---

*[pkg/nightly/nightly_test.go, line 42 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4Dy3CSdY2KA012F0PX:-L4Dy3CSdY2KA012F0PY:b60sv9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/485df2e13f74647ae6b1732ec59494299325ed6d/pkg/nightly/nightly_test.go#L42)):*
> ```Go
> 
> func init() {
> 	os.Chdir("../../")
> ```

I imagine this is necessary to locate the cockroach and workload binaries. Seems like it could be a bit surprising. 

---

*[pkg/nightly/nightly_test.go, line 48 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4DyAuvYDlc7qyO8wQz:-L4DyAuvYDlc7qyO8wR-:b46lbml) ([raw file](https://github.com/cockroachdb/cockroach/blob/485df2e13f74647ae6b1732ec59494299325ed6d/pkg/nightly/nightly_test.go#L48)):*
> ```Go
> // clusters (# of machines in each locality) are going to generalize. For now,
> // just hardcode what we had before.
> var singleDCTests = map[string]string{
> ```

I think we can move this into `TestNightlySingleDC`.

---

*[pkg/nightly/nightly_test.go, line 100 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4DyIwd2qKgmeB2-BCh:-L4DyIwd2qKgmeB2-BCi:bhmdzqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/485df2e13f74647ae6b1732ec59494299325ed6d/pkg/nightly/nightly_test.go#L100)):*
> ```Go
> }
> 
> func TestNightlySingleDC(t *testing.T) {
> ```

`s/TestNightly/Test/g` to reduce stuttering.

---

*[pkg/nightly/nightly_test.go, line 107 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4DzXL4QlRDLXT_9-_T:-L4DzXL4QlRDLXT_9-_U:b-nzwjvp) ([raw file](https://github.com/cockroachdb/cockroach/blob/485df2e13f74647ae6b1732ec59494299325ed6d/pkg/nightly/nightly_test.go#L107)):*
> ```Go
> 			t.Parallel()
> 
> 			l, err := newLogger(t.Name())
> ```

How well does this work in practice? I can imagine logging the output of `workload-test` to a shared  file might be confusing even with the prefixes. 

---

*[pkg/nightly/nightly_test.go, line 117 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4DyODCArdPYBbHGykn:-L4DyODCArdPYBbHGyko:bbxf0h0) ([raw file](https://github.com/cockroachdb/cockroach/blob/485df2e13f74647ae6b1732ec59494299325ed6d/pkg/nightly/nightly_test.go#L117)):*
> ```Go
> 			err = runCmds(l, [][]string{
> 				[]string{"roachprod", "create", clusterName},
> 				[]string{"sleep", "30"},
> ```

Is this done to allow the machines to come up? We might want to add a more direct method for testing whether the machines are available. For example, `roachprod run <cluster> true` (I'm not sure if that works). Or perhaps `create` should internally wait. Not necessary to solve in this PR, but certainly worth a TODO.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-:-L4Dzop9YzynnuAkmdta:b-ldy12d)*

**Comment by benesch** [comment]
Pushed up an entirely untested rev to address review feedback. I won't be able to look at this again until tomorrow night, so please feel free to take it over in the meantime! Remaining problems:

* Probably some stupid compilation errors I just introduced.
* Fixing/testing the logger in the single DC test. Probably we want to move the log aggregation into this package instead of running `roachprod test workload-test`.

---

Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/nightly/nightly_test.go, line 35 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4DxuU1S2BFkBRwX0Ux:-L4Eo7hv4uObR3Z08wSQ:b-5utw99) ([raw file](https://github.com/cockroachdb/cockroach/blob/485df2e13f74647ae6b1732ec59494299325ed6d/pkg/nightly/nightly_test.go#L35)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Did you intend to call this?
</blockquote></details>

Oops, yes. Thanks. Done. I decided using a flag was cleaner than using a build tag. Let me know if you have a better name for the flag than "really."

---

*[pkg/nightly/nightly_test.go, line 42 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4Dy3CSdY2KA012F0PX:-L4Es2ISg8M02mFXbqVY:b-7snv9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/485df2e13f74647ae6b1732ec59494299325ed6d/pkg/nightly/nightly_test.go#L42)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I imagine this is necessary to locate the cockroach and workload binaries. Seems like it could be a bit surprising. 
</blockquote></details>

Switched to using flags.

---

*[pkg/nightly/nightly_test.go, line 48 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4DyAuvYDlc7qyO8wQz:-L4Es433_BAc9aQJ8NHg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/485df2e13f74647ae6b1732ec59494299325ed6d/pkg/nightly/nightly_test.go#L48)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think we can move this into `TestNightlySingleDC`.
</blockquote></details>

Done.

---

*[pkg/nightly/nightly_test.go, line 100 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4DyIwd2qKgmeB2-BCh:-L4Es4PJGkxU9SaaXG6H:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/485df2e13f74647ae6b1732ec59494299325ed6d/pkg/nightly/nightly_test.go#L100)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/TestNightly/Test/g` to reduce stuttering.
</blockquote></details>

Done.

---

*[pkg/nightly/nightly_test.go, line 107 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4DzXL4QlRDLXT_9-_T:-L4EoQ06fQ7pUynajbEp:bcwq0fv) ([raw file](https://github.com/cockroachdb/cockroach/blob/485df2e13f74647ae6b1732ec59494299325ed6d/pkg/nightly/nightly_test.go#L107)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

How well does this work in practice? I can imagine logging the output of `workload-test` to a shared  file might be confusing even with the prefixes. 
</blockquote></details>

No idea. I haven't actually tried running the single DC version yet.

---

*[pkg/nightly/nightly_test.go, line 117 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4DyODCArdPYBbHGykn:-L4EoSJWh-p59xgQVEJL:b-j3hxw0) ([raw file](https://github.com/cockroachdb/cockroach/blob/485df2e13f74647ae6b1732ec59494299325ed6d/pkg/nightly/nightly_test.go#L117)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is this done to allow the machines to come up? We might want to add a more direct method for testing whether the machines are available. For example, `roachprod run <cluster> true` (I'm not sure if that works). Or perhaps `create` should internally wait. Not necessary to solve in this PR, but certainly worth a TODO.
</blockquote></details>

Exactly right. I think `create` should internally wait; this bugs me when using roachprod manually from the CLI too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-:-L4Es6TFXknoTnQ2QBg2:b-czz12k)*

**Comment by petermattis** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[build/nightly-workload.sh, line 22 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4G_ggkrcuUpmQHbWg1:-L4G_gglB8KF7BsqOx-M:b-nhlnzw) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a655be5061b1dc66321e7591e25fee4e176b0a/build/nightly-workload.sh#L22)):*
> ```Shell
> make bin/workload
> 
> go test -v -really -clusterid "${TC_BUILD_ID}" -cockroach "$PWD/cockroach" -workload "$PWD/workload" ./pkg/nightly
> ```

Should this be `$PWD/cockroach-linux-2.6.32-gnu-amd64` and `$PWD/bin/workload`?

---

*[pkg/nightly/nightly_test.go, line 35 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4DxuU1S2BFkBRwX0Ux:-L4GZamVic6eJHnONyao:bp62axa) ([raw file](https://github.com/cockroachdb/cockroach/blob/485df2e13f74647ae6b1732ec59494299325ed6d/pkg/nightly/nightly_test.go#L35)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Oops, yes. Thanks. Done. I decided using a flag was cleaner than using a build tag. Let me know if you have a better name for the flag than "really."
</blockquote></details>

Let me think about that. `--really` is a bit awkward. 

---

*[pkg/nightly/nightly_test.go, line 117 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4DyODCArdPYBbHGykn:-L4GZmmdEY54QvHu0er8:b-8k8peg) ([raw file](https://github.com/cockroachdb/cockroach/blob/485df2e13f74647ae6b1732ec59494299325ed6d/pkg/nightly/nightly_test.go#L117)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Exactly right. I think `create` should internally wait; this bugs me when using roachprod manually from the CLI too.
</blockquote></details>

Ack. We should fix `roachprod create`. I'll take on that task.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282)*

**Comment by danhhz** [comment]
this direction is great

---

Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/nightly/log.go, line 31 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4NllGVCgngYDav95hS:-L4NllGVCgngYDav95hT:b-v633xw) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a655be5061b1dc66321e7591e25fee4e176b0a/pkg/nightly/log.go#L31)):*
> ```Go
> // TeamCity build log, if running in CI), while creating a non-interleaved
> // record in the build artifacts.
> type logger struct {
> ```

i tried running these tests locally and this doesn't play well with the roachprod ascii art. we should add a flag to roachprod to disable the prettyness

---

*[pkg/nightly/nightly_test.go, line 35 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4DxuU1S2BFkBRwX0Ux:-L4NkhRIEMfglvwyyoQl:b-7548tu) ([raw file](https://github.com/cockroachdb/cockroach/blob/485df2e13f74647ae6b1732ec59494299325ed6d/pkg/nightly/nightly_test.go#L35)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Let me think about that. `--really` is a bit awkward. 
</blockquote></details>

strawman: a variadic function that accepts a set of string tags. if none of them match a tag specified at runtime, it skipped

```
func skipIfNotTag(t, tags ...string) {
    for _, t := range tags {
        if *tag == tag { return }
    }
    t.Skip(fmt.Sprintf(`tag %s was not one of %s`, *tag, strings.Join(tags, `,`)))
}

TestPartition(t *testing.T) {
    skipIfNotTag(t, `nightly`, `partition`, `release`)
    ....
}
```

---

*[pkg/nightly/nightly_test.go, line 117 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4DyODCArdPYBbHGykn:-L4Nlz470VRJdOmZOw87:b-bwnp5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/485df2e13f74647ae6b1732ec59494299325ed6d/pkg/nightly/nightly_test.go#L117)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ack. We should fix `roachprod create`. I'll take on that task.
</blockquote></details>

peter merged this, so no need for the sleeps anymore

---

*[pkg/nightly/nightly_test.go, line 83 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4Nm_XNhWV9PLnG1HXZ:-L4Nm_XNhWV9PLnG1HX_:b-7zr2cq) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a655be5061b1dc66321e7591e25fee4e176b0a/pkg/nightly/nightly_test.go#L83)):*
> ```Go
> 
> var clusterID = func() string {
> 	id := os.Getenv("COCKROACH_NIGHTLY_CLUSTER_ID")
> ```

i think you want a clusterid flag (or update the nightly-workload.sh script)

---

*[pkg/nightly/nightly_test.go, line 139 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4Nm7Dmu0UaRWf0X9-w:-L4Nm7Dmu0UaRWf0X9-x:bhj70ud) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a655be5061b1dc66321e7591e25fee4e176b0a/pkg/nightly/nightly_test.go#L139)):*
> ```Go
> }
> 
> func TestRoachmart(t *testing.T) {
> ```

i wonder if it's possible to sniff out the go test timeout and refuse to run if it's too short. that was always a huge annoyance with ./pkg/acceptance (and i just got burned by it playing with this PR locally)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-:-L4NmjH4vznnX8fyHpeZ:bilc14l)*

**Comment by petermattis** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/nightly/log.go, line 31 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4NllGVCgngYDav95hS:-L4OB5ZRIx_2zaq2Ku63:b-jo7sp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a655be5061b1dc66321e7591e25fee4e176b0a/pkg/nightly/log.go#L31)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

i tried running these tests locally and this doesn't play well with the roachprod ascii art. we should add a flag to roachprod to disable the prettyness
</blockquote></details>

https://github.com/cockroachdb/roachprod/pull/45

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282)*

**Comment by petermattis** [comment]
@benesch What's the ETA on this change? I'd like to start enhancing the nightly performance tests using this change as a basis. I think it would be good to get this in sooner, even if that is a more limited form.

**Comment by benesch** [comment]
ETA is as soon as TC is happy. I'm happy with how it works locally. Iteration is slow, though.

**Comment by benesch** [comment]
Ready for review, pending three caveats that I don't have the stamina to fix tonight:

  * roachprod needs one last change: https://github.com/cockroachdb/roachprod/pull/49
  * I accidentally dropped the `gsutil` upload command that Dan added
  * I _still_ haven't gotten a successful TC run. Queued yet another here: https://teamcity.cockroachdb.com/viewQueued.html?itemId=507788&tab=queuedBuildOverviewTab

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[build/nightly-workload.sh, line 18 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4f_ECn418QOnjR3JMP:-L4f_ECn418QOnjR3JMQ:bqccmjs) ([raw file](https://github.com/cockroachdb/cockroach/blob/18b0ef82e06d160d5804d1c3e9082542ee368e48/build/nightly-workload.sh#L18)):*
> ```Shell
> set -x
> 
> go get -u -v github.com/benesch/roachprod
> ```

I imagine you want to switch this back to `cockroachdb/roachprod` before merging. 

---

*[build/nightly-workload.sh, line 29 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4f_fJfB4NWR5zIRhrH:-L4f_fJfB4NWR5zIRhrI:b-mtrgqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/886f1f34c0c07dc1e9ee205ae6a90d4a80a611f9/build/nightly-workload.sh#L29)):*
> ```Shell
> mkdir -p artifacts
> cp -R workload-test*/* artifacts/
> gsutil -h "Content-Type:text/plain" cp \
> ```

Per your comment above, do you want to re-add this?

---

*[build/nightly-workload.sh, line 37 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4f_3Ez0_ou1MF0c2kX:-L4f_3Ez0_ou1MF0c2kY:b8iu95l) ([raw file](https://github.com/cockroachdb/cockroach/blob/18b0ef82e06d160d5804d1c3e9082542ee368e48/build/nightly-workload.sh#L37)):*
> ```Shell
> make test \
>   PKG=./pkg/nightly \
>   TESTFLAGS="$(printf "%q " "${testflags[@]}")" \
> ```

Whoa. Does that really deal with all of the quoting correctly?

---

*[build/nightly-workload.sh, line 39 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4f_rUso0ayx1D1JxXE:-L4f_rUso0ayx1D1JxXF:bsunyt8) ([raw file](https://github.com/cockroachdb/cockroach/blob/18b0ef82e06d160d5804d1c3e9082542ee368e48/build/nightly-workload.sh#L39)):*
> ```Shell
>   TESTFLAGS="$(printf "%q " "${testflags[@]}")" \
>   TESTS="${TESTS:-.}" \
>   TESTTIMEOUT=1h
> ```

We'll need to bump this at some point. Any reason not to bump it now? Perhaps to 6h or 12h.

---

*[pkg/nightly/nightly_test.go, line 139 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4Nm7Dmu0UaRWf0X9-w:-L4fZJ8_ofRsA2C87hUA:bip4y3a) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a655be5061b1dc66321e7591e25fee4e176b0a/pkg/nightly/nightly_test.go#L139)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

i wonder if it's possible to sniff out the go test timeout and refuse to run if it's too short. that was always a huge annoyance with ./pkg/acceptance (and i just got burned by it playing with this PR locally)
</blockquote></details>

Yes, it is possible, though a bit irritating. Probably worthwhile, though. @benesch Can you add a `TODO(peter)`?

---

*[pkg/nightly/nightly_test.go, line 43 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4fZ2_QTXmI_2sfDUgg:-L4fZ2_QTXmI_2sfDUgh:b-aqhawv) ([raw file](https://github.com/cockroachdb/cockroach/blob/18b0ef82e06d160d5804d1c3e9082542ee368e48/pkg/nightly/nightly_test.go#L43)):*
> ```Go
> 
> func init() {
> 	flag.Parse()
> ```

Is this `flag.Parse` necessary? I thought the `testing` package automatically parsed the flags.

---

*[pkg/nightly/nightly_test.go, line 133 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4fZknnzgAEoep61wiL:-L4fZknnzgAEoep61wiM:ba3dfmt) ([raw file](https://github.com/cockroachdb/cockroach/blob/18b0ef82e06d160d5804d1c3e9082542ee368e48/pkg/nightly/nightly_test.go#L133)):*
> ```Go
> 				{"roachprod", "start", clusterName},
> 				{"roachprod", "ssh", clusterName + ":1", "--",
> 					"-o", "StrictHostKeyChecking=no", // TODO(benesch): Make roachprod pass these SSH args.
> ```

Remove.

---

*[pkg/nightly/nightly_test.go, line 184 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4fZ_pf58IOfs1duuo8:-L4fZ_pf58IOfs1duuo9:bv1b8p3) ([raw file](https://github.com/cockroachdb/cockroach/blob/18b0ef82e06d160d5804d1c3e9082542ee368e48/pkg/nightly/nightly_test.go#L184)):*
> ```Go
> 		err = runCmd(l, append([]string{
> 			"roachprod", "ssh", fmt.Sprintf("%s:%d", clusterName, nodes[0].i), "--",
> 			"-o", "StrictHostKeyChecking=no", // TODO(benesch): Make roachprod pass these SSH args.
> ```

This shouldn't be necessary now as I've added this to `roachprod`. 

---

*[pkg/nightly/nightly_test.go, line 204 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4fZdt5xBez_Bqh8YOr:-L4fZdt5xBez_Bqh8YOs:ba3dfmt) ([raw file](https://github.com/cockroachdb/cockroach/blob/18b0ef82e06d160d5804d1c3e9082542ee368e48/pkg/nightly/nightly_test.go#L204)):*
> ```Go
> 				err = runCmd(cl, append([]string{
> 					"roachprod", "ssh", fmt.Sprintf("%s:%d", clusterName, node.i), "--",
> 					"-o", "StrictHostKeyChecking=no", // TODO(benesch): Make roachprod pass these SSH args.
> ```

Remove.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-:-L4f_c7NoAElY5_dpyjP:bnfp4nl)*

**Comment by benesch** [comment]
Ok, think I've addressed everything. TC run: https://teamcity.cockroachdb.com/viewQueued.html?itemId=508504

---

Review status: 0 of 6 files reviewed at latest revision, 14 unresolved discussions.

---

*[build/nightly-workload.sh, line 22 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4G_ggkrcuUpmQHbWg1:-L4foKqca-bQ250BScjA:b-9f087b) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a655be5061b1dc66321e7591e25fee4e176b0a/build/nightly-workload.sh#L22)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Should this be `$PWD/cockroach-linux-2.6.32-gnu-amd64` and `$PWD/bin/workload`?
</blockquote></details>

Yep, done.

---

*[build/nightly-workload.sh, line 18 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4f_ECn418QOnjR3JMP:-L4foLqJFxMUd8BzxLRP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/18b0ef82e06d160d5804d1c3e9082542ee368e48/build/nightly-workload.sh#L18)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I imagine you want to switch this back to `cockroachdb/roachprod` before merging. 
</blockquote></details>

Done.

---

*[build/nightly-workload.sh, line 29 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4f_fJfB4NWR5zIRhrH:-L4fnvEDWgA1fb8F4Prh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/886f1f34c0c07dc1e9ee205ae6a90d4a80a611f9/build/nightly-workload.sh#L29)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Per your comment above, do you want to re-add this?
</blockquote></details>

Done.

---

*[build/nightly-workload.sh, line 37 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4f_3Ez0_ou1MF0c2kX:-L4fnz3-bqhSKWSZm3_d:b-mlfno3) ([raw file](https://github.com/cockroachdb/cockroach/blob/18b0ef82e06d160d5804d1c3e9082542ee368e48/build/nightly-workload.sh#L37)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Whoa. Does that really deal with all of the quoting correctly?
</blockquote></details>

As far as the shell is concerned, yes. Make can muck it up (e.g. if it tries to do its own quoting, or if there's a dollar sign), but it handles empty arguments properly which is a real timesaver.

---

*[build/nightly-workload.sh, line 39 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4f_rUso0ayx1D1JxXE:-L4fnxvI3AKoyjXG6gV8:b-3gpwjx) ([raw file](https://github.com/cockroachdb/cockroach/blob/18b0ef82e06d160d5804d1c3e9082542ee368e48/build/nightly-workload.sh#L39)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

We'll need to bump this at some point. Any reason not to bump it now? Perhaps to 6h or 12h.
</blockquote></details>

Nope. Changed to 12h.

---

*[pkg/nightly/nightly_test.go, line 35 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4DxuU1S2BFkBRwX0Ux:-L4c488NfU59g41BPugz:b-6cacjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/485df2e13f74647ae6b1732ec59494299325ed6d/pkg/nightly/nightly_test.go#L35)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

strawman: a variadic function that accepts a set of string tags. if none of them match a tag specified at runtime, it skipped

```
func skipIfNotTag(t, tags ...string) {
    for _, t := range tags {
        if *tag == tag { return }
    }
    t.Skip(fmt.Sprintf(`tag %s was not one of %s`, *tag, strings.Join(tags, `,`)))
}

TestPartition(t *testing.T) {
    skipIfNotTag(t, `nightly`, `partition`, `release`)
    ....
}
```
</blockquote></details>

Oh, that's interesting. Ideally we'd come up with a name other than "tag" so it's not confused with build tags. For now I'm sticking with the simple approach (a flag), but I've renamed it to "-slow", which is, I think, less awkward than "really".

---

*[pkg/nightly/nightly_test.go, line 117 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4DyODCArdPYBbHGykn:-L4fnhd70wwgEw0us0rA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/485df2e13f74647ae6b1732ec59494299325ed6d/pkg/nightly/nightly_test.go#L117)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

peter merged this, so no need for the sleeps anymore
</blockquote></details>

Done.

---

*[pkg/nightly/nightly_test.go, line 83 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4Nm_XNhWV9PLnG1HXZ:-L4fniDuaN5ms5-0zhNe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a655be5061b1dc66321e7591e25fee4e176b0a/pkg/nightly/nightly_test.go#L83)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

i think you want a clusterid flag (or update the nightly-workload.sh script)
</blockquote></details>

Done.

---

*[pkg/nightly/nightly_test.go, line 139 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4Nm7Dmu0UaRWf0X9-w:-L4fngWWucZY2ARwA2Ug:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a655be5061b1dc66321e7591e25fee4e176b0a/pkg/nightly/nightly_test.go#L139)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Yes, it is possible, though a bit irritating. Probably worthwhile, though. @benesch Can you add a `TODO(peter)`?
</blockquote></details>

Done.

---

*[pkg/nightly/nightly_test.go, line 43 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4fZ2_QTXmI_2sfDUgg:-L4fnjqpCvzSur5nkqmP:bj8koem) ([raw file](https://github.com/cockroachdb/cockroach/blob/18b0ef82e06d160d5804d1c3e9082542ee368e48/pkg/nightly/nightly_test.go#L43)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is this `flag.Parse` necessary? I thought the `testing` package automatically parsed the flags.
</blockquote></details>

Guess not. Thanks.

---

*[pkg/nightly/nightly_test.go, line 133 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4fZknnzgAEoep61wiL:-L4fngzscHWGOnsDcy_P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/18b0ef82e06d160d5804d1c3e9082542ee368e48/pkg/nightly/nightly_test.go#L133)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Remove.
</blockquote></details>

Done.

---

*[pkg/nightly/nightly_test.go, line 184 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4fZ_pf58IOfs1duuo8:-L4fnfmJ8vBJIpooKccR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/18b0ef82e06d160d5804d1c3e9082542ee368e48/pkg/nightly/nightly_test.go#L184)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This shouldn't be necessary now as I've added this to `roachprod`. 
</blockquote></details>

Done.

---

*[pkg/nightly/nightly_test.go, line 204 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-L4fZdt5xBez_Bqh8YOr:-L4fng5Q3TymRW5Hdxuc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/18b0ef82e06d160d5804d1c3e9082542ee368e48/pkg/nightly/nightly_test.go#L204)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Remove.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-:-L4foUkyBmfDNjA32aw2:b-nynrf5)*

**Comment by danhhz** [comment]
:lgtm: though looks like you didn't push some of the updates

---

Review status: 0 of 7 files reviewed at latest revision, 14 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22282#-:-L4fx47reNZeBRsnYbRI:bma5jxw)*

**Pull request merged**
