### PR TITLE
scripts: use branch URIs in bump-pebble.sh

### PR DESCRIPTION
**Pull request by dt**
People name their remotes different things and/or use HTTP.

Release note: none.

### CODE REVIEW

**Review by nicktrav — APPROVED** [review]
Thanks! :lgtm:

If you're feeling charitable, we have the same script on `release-21.1` and `release-21.2` that could probably benefit from the same change (if you're going to get stung bumping those in the future too). Feel free to palm that off to us if you'd like.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75991#-:-Mv0v48a65RR_lseKoJa:b-vdq6pd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @jbowens)

___
*[scripts/bump-pebble.sh, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75991#-Mv0uVEd2pMkjgKs2Pyb:-Mv0uVEd2pMkjgKs2Pyc:biz2dlh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8d8ba32ece616a5ee6ba50c472db0ca938e075b/scripts/bump-pebble.sh#L46)):*
> ```Shell
> COCKROACH_UPSTREAM_URL="https://github.com/cockroachdb/cockroach.git"
> PEBBLE_UPSTREAM_URL="https://github.com/cockroachdb/pebble.git"
> VENDORED_UPSTREAM_URL="git@github.com:cockroachdb/vendored.git"
> ```

Is this `git@` as it needs to be authenticated? Or can it be https like the other two remotes?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75991)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens and @nicktrav)

___
*[scripts/bump-pebble.sh, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75991#-Mv0uVEd2pMkjgKs2Pyb:-Mv0vtyp5Eg1_6328SmE:b6bbpx1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8d8ba32ece616a5ee6ba50c472db0ca938e075b/scripts/bump-pebble.sh#L46)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Is this `git@` as it needs to be authenticated? Or can it be https like the other two remotes?
</blockquote></details>

correct, we're pushing to it below, so needs auth, so using ssh. other two are just fetching, so http.

**Comment by dt** [comment]
btw, you can just apply the `backport-x` label to a PR to cause it to be automatically backported when it merges.

**Comment by dt** [comment]
TFTR!

bors r+

**Pull request merged**
