### PR TITLE
rfc: opt-driven FK cascades

### PR DESCRIPTION
**Pull request by RaduBerinde**
RFC for optimizer-driven foreign key cascades.

See accompanying prototype PR #48054.

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48053)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @jordanlewis, @RaduBerinde, @rytaft, and @yuzefovich)

___
*[docs/RFCS/20200424_opt_driven_fk_cascades.md, line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48053#-M5sP5F23_DIer2OO9Pu:-M5sP5F23_DIer2OO9Pv:b-fzb0m4) ([raw file](https://github.com/cockroachdb/cockroach/blob/39be2f7a2b4eca300147706a7af704ddedf289e1/docs/RFCS/20200424_opt_driven_fk_cascades.md#L128)):*
> ```Markdown
> // CascadeBuilder is an interface used to construct a cascading query for a
> // specific FK relation. For example: if we are deleting rows from a child
> // table, after deleting the rows from the child table this interface will be
> ```

I'm confused here: in this example shouldn't "child" be switched with "parent" and vice versa?
___
*[docs/RFCS/20200424_opt_driven_fk_cascades.md, line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48053#-M5sQ83k7GnKjDu9UMKs:-M5sQ83k7GnKjDu9UMKt:bl4i87u) ([raw file](https://github.com/cockroachdb/cockroach/blob/39be2f7a2b4eca300147706a7af704ddedf289e1/docs/RFCS/20200424_opt_driven_fk_cascades.md#L131)):*
> ```Markdown
> // used to build the corresponding deletion in the parent table.
> type CascadeBuilder interface {
> 	// Build constructs a cascading query in the parent table. The input is
> ```

nit: to me "a query in the table" sounds unusual, maybe "constructs a query cascading from the parent table"? (But maybe it's just "remnants" of Russian grammar in my mind.)
___
*[docs/RFCS/20200424_opt_driven_fk_cascades.md, line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48053#-M5sR8uWC1DaKYAjiGBM:-M5sR8uWC1DaKYAjiGBN:b-gwwz4g) ([raw file](https://github.com/cockroachdb/cockroach/blob/39be2f7a2b4eca300147706a7af704ddedf289e1/docs/RFCS/20200424_opt_driven_fk_cascades.md#L201)):*
> ```Markdown
> reworked in [#47681](https://github.com/cockroachdb/cockroach/pull/47681)).
> Internally, it uses a new Optimizer/Memo instance to plan the query and
> execbuilds it against the same exec.Factory as the original execbuilder.
> ```

nit: highlighting - `exec.Factory`.
___
*[docs/RFCS/20200424_opt_driven_fk_cascades.md, line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48053#-M5sRfL50uCRAXmo8UaU:-M5sRfL50uCRAXmo8UaV:b-3jgx28) ([raw file](https://github.com/cockroachdb/cockroach/blob/39be2f7a2b4eca300147706a7af704ddedf289e1/docs/RFCS/20200424_opt_driven_fk_cascades.md#L211)):*
> ```Markdown
> ```
>  - While cascades list is not empty:
>    - txn.Step() // create sequencing point in the transaction
> ```

What does it do / why do we need it?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48053)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @jordanlewis, @rytaft, and @yuzefovich)

___
*[docs/RFCS/20200424_opt_driven_fk_cascades.md, line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48053#-M5sP5F23_DIer2OO9Pu:-M5w7vFU3nJSHxwg-7_J:b20m8gj) ([raw file](https://github.com/cockroachdb/cockroach/blob/39be2f7a2b4eca300147706a7af704ddedf289e1/docs/RFCS/20200424_opt_driven_fk_cascades.md#L128)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I'm confused here: in this example shouldn't "child" be switched with "parent" and vice versa?
</blockquote></details>

Correct, fixed.
___
*[docs/RFCS/20200424_opt_driven_fk_cascades.md, line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48053#-M5sQ83k7GnKjDu9UMKs:-M5w84nz5DPFbup7RuEG:b57q31p) ([raw file](https://github.com/cockroachdb/cockroach/blob/39be2f7a2b4eca300147706a7af704ddedf289e1/docs/RFCS/20200424_opt_driven_fk_cascades.md#L131)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: to me "a query in the table" sounds unusual, maybe "constructs a query cascading from the parent table"? (But maybe it's just "remnants" of Russian grammar in my mind.)
</blockquote></details>

Changed to "Build constructs a cascading query that mutates the child table."
___
*[docs/RFCS/20200424_opt_driven_fk_cascades.md, line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48053#-M5sRfL50uCRAXmo8UaU:-M5w89lD0K8DYYsF5igF:bw5st2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/39be2f7a2b4eca300147706a7af704ddedf289e1/docs/RFCS/20200424_opt_driven_fk_cascades.md#L211)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

What does it do / why do we need it?
</blockquote></details>

This is from the recent work on sequence points. It's necessary so that each cascade "sees" the results of the main query and any previous cascades (in case of circular/self references). We currently do this before each postquery: https://github.com/cockroachdb/cockroach/blob/e3a23df63c3ed60b8842a30edf1f3de4c449ffd7/pkg/sql/distsql_running.go#L1035

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48053)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @jordanlewis, @RaduBerinde, and @rytaft)

___
*[docs/RFCS/20200424_opt_driven_fk_cascades.md, line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48053#-M5sRfL50uCRAXmo8UaU:-M5xZs5c45K6ATMEZLjv:b-kufkx2) ([raw file](https://github.com/cockroachdb/cockroach/blob/39be2f7a2b4eca300147706a7af704ddedf289e1/docs/RFCS/20200424_opt_driven_fk_cascades.md#L211)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is from the recent work on sequence points. It's necessary so that each cascade "sees" the results of the main query and any previous cascades (in case of circular/self references). We currently do this before each postquery: https://github.com/cockroachdb/cockroach/blob/e3a23df63c3ed60b8842a30edf1f3de4c449ffd7/pkg/sql/distsql_running.go#L1035
</blockquote></details>

I see, thanks.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48053)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @jordanlewis, and @RaduBerinde)

___
*[docs/RFCS/20200424_opt_driven_fk_cascades.md, line 10 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48053#-M5x9_bz5nAM8X7DS8_N:-M5x9_bz5nAM8X7DS8_O:bk8bzx8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d08f5398a36c14d860e972802a1c8b309d988ac1/docs/RFCS/20200424_opt_driven_fk_cascades.md#L10)):*
> ```Markdown
> # Summary and motivation
> 
> A foreign key constraint establishes a relationship between two columns (or sets
> ```

[nit] I'd say "A foreign key (FK) constraint..." so it's clear what the abbreviation means below
___
*[docs/RFCS/20200424_opt_driven_fk_cascades.md, line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48053#-M5x9sAw7CL4ylBnwy_i:-M5x9sAx8Iam5OJ5-VX8:brt5jmb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d08f5398a36c14d860e972802a1c8b309d988ac1/docs/RFCS/20200424_opt_driven_fk_cascades.md#L12)):*
> ```Markdown
> A foreign key constraint establishes a relationship between two columns (or sets
> of columns) between two tables. There is a "child" side and a "parent" side for
> each relationship; any value in the FK column in the child table must have a
> ```

[nit] FK column(s)

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48053)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @jordanlewis, @rytaft, and @yuzefovich)

___
*[docs/RFCS/20200424_opt_driven_fk_cascades.md, line 10 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48053#-M5x9_bz5nAM8X7DS8_N:-M5y4dnV7bOdDHbBk3eF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d08f5398a36c14d860e972802a1c8b309d988ac1/docs/RFCS/20200424_opt_driven_fk_cascades.md#L10)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] I'd say "A foreign key (FK) constraint..." so it's clear what the abbreviation means below
</blockquote></details>

Done.
___
*[docs/RFCS/20200424_opt_driven_fk_cascades.md, line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48053#-M5x9sAw7CL4ylBnwy_i:-M5y4fPJ8Li2N2saEEkf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d08f5398a36c14d860e972802a1c8b309d988ac1/docs/RFCS/20200424_opt_driven_fk_cascades.md#L12)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] FK column(s)
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48053#-:-M5yWuaI3x3oWEFUsmyV:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @jordanlewis, and @yuzefovich)

**Pull request merged**
