### PR TITLE
distsql: add external storage to other sort strategies

### LINKED ISSUE #26244: distsqlrun: other sort strategies should be able to fallback to disk
The `sortAllProcessor` can fall back to disk if it starts using too much memory. The same should be true for the top K and chunks processors.

This should be trivial after #26107 is solved.

### PR DESCRIPTION
**Pull request by asubiotto**
Closes #26244

The last commit also includes refactoring since the addition of external storage removed some differences from the sort implementations, so the similarities have been extracted into sorterBase.

I still need to add tests.

### CODE REVIEW

**Comment by solongordon** [comment]
Reviewed 5 of 5 files at r1, 4 of 4 files at r2.
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/distsqlrun/disk_row_container.go, line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27083#-LGQTYnI9M86EK5xsdsX:-LGQTYnI9M86EK5xsdsY:brbhovv) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5ce048d5f809aa458fd20ba9f4b8d80e18dc398/pkg/sql/distsqlrun/disk_row_container.go#L70)):*
> ```Go
> }
> 
> var _ sortableRowContainer = &diskRowContainer{}
> ```

Might as well add
```
var _ topKRowContainer = &diskRowContainer{}
```

---

*[pkg/sql/distsqlrun/row_container.go, line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27083#-LGQVsFg-dsg2Yny3p2y:-LGQVsFg-dsg2Yny3p2z:b-sugqb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5ce048d5f809aa458fd20ba9f4b8d80e18dc398/pkg/sql/distsqlrun/row_container.go#L58)):*
> ```Go
> // callers should not call AddRow. Iterators created after calling InitTopK are
> // guaranteed to read the top k rows only.
> type topKRowContainer interface {
> ```

It seems like the `sortableRowContainer` interface isn't used anywhere now, aside from being extended here. Could you just add your new methods to that interface instead of making a new one?

---

*[pkg/sql/distsqlrun/row_container.go, line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27083#-LGQW7nV3QL1ePmIRhVk:-LGQW7nV3QL1ePmIRhVl:bb5mg25) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5ce048d5f809aa458fd20ba9f4b8d80e18dc398/pkg/sql/distsqlrun/row_container.go#L63)):*
> ```Go
> 	// MaybeReplaceMax checks whether the given row belongs in the top k rows,
> 	// potentially evicting a row in favor of the given row.
> 	MaybeReplaceMax(context.Context, sqlbase.EncDatumRow) error
> ```

Is there value in having a separate function for this? Why not just have `AddRow` switch to the `MaybeReplaceMax` behavior after `InitTopK` is called? Then the caller doesn't need to worry about properly switching from `AddRow` to `MaybeReplaceMax`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27083)*

**Review by asubiotto — COMMENTED** [review]
Tests added (just piggy-backed of the existing sorter tests). This PR is now ready for a full review.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27083#-:-LH43KtKBbEH3wcWQXKH:b-e4at5l)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/disk_row_container.go, line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27083#-LGQTYnI9M86EK5xsdsX:-LGzW8RL5FpSyLaHX2-Q:b-2wfnqc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5ce048d5f809aa458fd20ba9f4b8d80e18dc398/pkg/sql/distsqlrun/disk_row_container.go#L70)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Might as well add
```
var _ topKRowContainer = &diskRowContainer{}
```
</blockquote></details>

Moved the `topKRowContainer` methods to `sortableRowContainer`
___
*[pkg/sql/distsqlrun/row_container.go, line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27083#-LGQVsFg-dsg2Yny3p2y:-LGzXDGT4zw9l3gIWsNY:b-gieacv) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5ce048d5f809aa458fd20ba9f4b8d80e18dc398/pkg/sql/distsqlrun/row_container.go#L58)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

It seems like the `sortableRowContainer` interface isn't used anywhere now, aside from being extended here. Could you just add your new methods to that interface instead of making a new one?
</blockquote></details>

Great suggestion, thanks! I was thinking it would be nice to make this `topK` functionality optional for any future `sortableRowContainer` implementations but we can always separate it then.
___
*[pkg/sql/distsqlrun/row_container.go, line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27083#-LGQW7nV3QL1ePmIRhVk:-LGzYCGc56CapC8X-VTs:boiv8r4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5ce048d5f809aa458fd20ba9f4b8d80e18dc398/pkg/sql/distsqlrun/row_container.go#L63)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Is there value in having a separate function for this? Why not just have `AddRow` switch to the `MaybeReplaceMax` behavior after `InitTopK` is called? Then the caller doesn't need to worry about properly switching from `AddRow` to `MaybeReplaceMax`.
</blockquote></details>

Hmm, it's an interesting suggestion but I'm not sure I want to have `AddRow` change its behavior depending on some conditions. I feel like it's more difficult to reason about code in these cases. In my opinion, the burden on the caller is not high enough to justify this change but it might be worth coming back to this in the future.

**Review by solongordon — CHANGES_REQUESTED** [review]
:lgtm:

I didn't look carefully at the code that was moved to the sorter base since presumably nothing really changed there. One question about a test case that was removed.

> Reviewed 1 of 5 files at r3, 3 of 4 files at r4, 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27083#-:-LH8l1Yj5jI1mfwvxJjC:bt5onmq)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsqlrun/sorter_test.go, line 283 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/27083#-LH8jbzP40P6adsz64mS:-LH8jbzQ9HcMfe-WCRGN:be900jj) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2545b7d0f13bc87a9cc1235caf637de93b4e431/pkg/sql/distsqlrun/sorter_test.go#L283)):*
> ```Go
> 		// memory. Tests the transfer of rows from memory to disk on
> 		// initialization.
> 		{bytes: 1150, expSpill: true},
> ```

Why did this test case go away?

**Review by asubiotto — COMMENTED** [review]
Fixed the lint failure, updated a stale commit message and added a release note.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27083#-:-LH8pKXB8y1HX899Sk3O:by4hi4l)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsqlrun/sorter_test.go, line 283 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/27083#-LH8jbzP40P6adsz64mS:-LH8li2C4mbfVKmDlRtp:b-7iviu) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2545b7d0f13bc87a9cc1235caf637de93b4e431/pkg/sql/distsqlrun/sorter_test.go#L283)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Why did this test case go away?
</blockquote></details>

It was a brittle test case that didn't add any test coverage. Initially this was here to test the case in which we fall back to disk after storing a couple of rows in memory. This testing is now done when testing the `diskBackedRowContainer`.

**Review by solongordon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27083)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsqlrun/sorter_test.go, line 283 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/27083#-LH8jbzP40P6adsz64mS:-LH8pmHnDpJowg0ywN2j:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2545b7d0f13bc87a9cc1235caf637de93b4e431/pkg/sql/distsqlrun/sorter_test.go#L283)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It was a brittle test case that didn't add any test coverage. Initially this was here to test the case in which we fall back to disk after storing a couple of rows in memory. This testing is now done when testing the `diskBackedRowContainer`.
</blockquote></details>

:+1:

**Pull request merged**
