### PR TITLE
opt: switch execbuilder tests to use logictest

### PR DESCRIPTION
**Pull request by RaduBerinde**
We no longer need a special execution path for the execbuilder tests;
this path doesn't support SHOW TRACE statements which would make
adding some tests harder.

This will also make it easier to move pieces of the top-level
logictests to the execbuilder tests.

The TestEngine infrastructure will be removed in a separate PR.

Release note: None

### CODE REVIEW

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 18 of 18 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/opt/exec/execbuilder/testdata/select, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26041#-LDHnkCyA0qsEN8e2isU:-LDI2PWv1YtanygFNK-6:b-o9dtie) ([raw file](https://github.com/cockroachdb/cockroach/blob/2304858f445ffc2812235d1f174259b1e86b4b33/pkg/sql/opt/exec/execbuilder/testdata/select#L100)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I tried but don't quite know how. We fallback on unsupported statements. We can verify that it works with `opt`, but we have a lot of those logic tests already (once we convert them)
</blockquote></details>

what about using the "always on" option for the optimizer?

---

*[pkg/sql/opt/exec/execbuilder/testdata/union, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26041#-LDI2nQy-7w_U6eYYZ4B:-LDI2nQy-7w_U6eYYZ4C:b-gq9qad) ([raw file](https://github.com/cockroachdb/cockroach/blob/28e29dbd01cc04ffd8bf8122752aa8f0cb574642/pkg/sql/opt/exec/execbuilder/testdata/union#L50)):*
> ```
> ----
> 1  2
> 1  1
> ```

Why is this row sorted after the previous if rowsort is enabled?

---

*[pkg/sql/opt/exec/execbuilder/testdata/union, line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26041#-LDI2yan7aBQCzSlpAEG:-LDI2yan7aBQCzSlpAEH:b-kw0fyo) ([raw file](https://github.com/cockroachdb/cockroach/blob/28e29dbd01cc04ffd8bf8122752aa8f0cb574642/pkg/sql/opt/exec/execbuilder/testdata/union#L126)):*
> ```
> 2
> 2
> 1
> ```

another rowsort issue?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26041#-:-LDI3XDX8JWWxcDnkrkq:bnfp4nl)*

**Comment by andy-kimball** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/exec/execbuilder/testdata/select, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26041#-LDHnkCyA0qsEN8e2isU:-LDI3k2t3UPfpNX9bhSD:b8vpvgc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2304858f445ffc2812235d1f174259b1e86b4b33/pkg/sql/opt/exec/execbuilder/testdata/select#L100)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

what about using the "always on" option for the optimizer?
</blockquote></details>

yeah, you could "always on" to get the right behavior

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26041)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/exec/execbuilder/testdata/select, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26041#-LDHnkCyA0qsEN8e2isU:-LDI4KXwBidJGOEU4Hbh:b2v9gc0) ([raw file](https://github.com/cockroachdb/cockroach/blob/2304858f445ffc2812235d1f174259b1e86b4b33/pkg/sql/opt/exec/execbuilder/testdata/select#L100)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

yeah, you could "always on" to get the right behavior
</blockquote></details>

I added it as `SET EXPERIMENTAL_OPT=ALWAYS; SELECT * FROM crdb_internal.jobs`.

I don't want to have a test config with optimizer always on because it wouldn't be very useful - you wouldn't be able to create a table. That said, we can make more use of `SET EXPERIMENTAL_OPT=ALWAYS` inside the tests, after we set up the tables

---

*[pkg/sql/opt/exec/execbuilder/testdata/union, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26041#-LDI2nQy-7w_U6eYYZ4B:-LDI4iM46F6FaJQitFVM:b-fcyz0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/28e29dbd01cc04ffd8bf8122752aa8f0cb574642/pkg/sql/opt/exec/execbuilder/testdata/union#L50)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why is this row sorted after the previous if rowsort is enabled?
</blockquote></details>

The logictest works a bit differently - it accepts any ordering in the test file (it sorts both the results and the expected input). I think I used the distsql mode when I generated it. I sorted it though.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26041)*

**Comment by rytaft** [comment]
Reviewed 2 of 2 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/exec/execbuilder/testdata/union, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26041#-LDI2nQy-7w_U6eYYZ4B:-LDICaTt4E0H6aGe2mwF:bslhqoi) ([raw file](https://github.com/cockroachdb/cockroach/blob/28e29dbd01cc04ffd8bf8122752aa8f0cb574642/pkg/sql/opt/exec/execbuilder/testdata/union#L50)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The logictest works a bit differently - it accepts any ordering in the test file (it sorts both the results and the expected input). I think I used the distsql mode when I generated it. I sorted it though.
</blockquote></details>

It's still not totally sorted (1, 1 should come before 1, 2), but if it's not a problem then no worries.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26041)*

**Comment by RaduBerinde** [comment]
Review status: 19 of 20 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/exec/execbuilder/testdata/union, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26041#-LDI2nQy-7w_U6eYYZ4B:-LDIE1gZ7F3TDgpZ_HJ5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/28e29dbd01cc04ffd8bf8122752aa8f0cb574642/pkg/sql/opt/exec/execbuilder/testdata/union#L50)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

It's still not totally sorted (1, 1 should come before 1, 2), but if it's not a problem then no worries.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26041)*

**Comment by rytaft** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26041)*

**Pull request merged**
