### PR TITLE
sql: implement SQL Stats flush logic

### PR DESCRIPTION
**Pull request by Azhng**
Previous PR: https://github.com/cockroachdb/cockroach/pull/67805
Next Chained PR: https://github.com/cockroachdb/cockroach/pull/67090

## First Commit

sql: remove `count` from stmt/txn stats system table

Previously, system.statement_statistics and
system.transaction_statistics table includes a `count` column
that corresponds to `roachpb.StatementStatistics.Count` and
`roachpb.TransactionStatistics.Count` fields respectively.
The objective for that column is to make
`INSERT ON CONFLICT DO UPDATE` style query easy. However,
since early prototyping have shown that
`INSERT ON CONFLICT DO UPDATE` style statement is quite inefficient,
the SQL Stats flush mechanism will be implemented using
separate queries INSERT and UPDATE statements.
This column is no longer userful and it would require special handling.
Removing this column simplifies the flush logic and removes the
need for special handlings.

Release note (sql change): count column is removed from
 system.statement_statistics and system.transaction_statistics
 tables.

## Second Commit

sql: implement persistedsqlstats flush logic

This commit implements the initial flush logic of the
persisted sql stats subsystem.

Release note: None

### CODE REVIEW

**Comment by Azhng** [comment]
CI Failure seems to be due to some unrelated changeccl tests.

**Review by jordanlewis — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67866)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @jordanlewis)

___
*[pkg/sql/exec_util.go, line 843 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67866#-MffIP838OkOeqMyiuGb:-MffIP838OkOeqMyiuGc:b-ee3wsz) ([raw file](https://github.com/cockroachdb/cockroach/blob/19859e2d54c37c6dfe22e7d1cf710ddbef53fa3a/pkg/sql/exec_util.go#L843)):*
> ```Go
> 		Unit:        metric.Unit_COUNT,
> 	}
> 	MetaSQLStatsFlushStarted = metric.Metadata{
> ```

note for later: let's consider adding this to a db console dashboard. cc @kevin-v-ngo 
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67866#-MffJ3t99PEx41rVffdh:-MffJ3t99PEx41rVffdi:b-cmged0) ([raw file](https://github.com/cockroachdb/cockroach/blob/19859e2d54c37c6dfe22e7d1cf710ddbef53fa3a/pkg/sql/sqlstats/persistedsqlstats/flush.go#L32)):*
> ```Go
> // during the flush will be logged as warning.
> func (s *PersistedSQLStats) Flush(ctx context.Context) {
> 	log.Infof(ctx, "flushing %d sql stats after %s", s.SQLStats.GetTotalFingerprintCount(), timeutil.Since(s.lastFlushStarted))
> ```

It would be nice to also include the number of bytes in the sql stats, since that's a condition for flushing as well.
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67866#-MffIwOQ-cb405EwMb-q:-MffIwOQ-cb405EwMb-r:b-ycm7ie) ([raw file](https://github.com/cockroachdb/cockroach/blob/19859e2d54c37c6dfe22e7d1cf710ddbef53fa3a/pkg/sql/sqlstats/persistedsqlstats/flush.go#L52)):*
> ```Go
> 
> 	err := s.SQLStats.Reset(ctx)
> 	if err != nil {
> ```

minor nit: could collapse these 2 lines (if err := stats.reset(); err != nil { 
log...
}
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 305 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67866#-MffIdqw5b9BApDLye6c:-MffIdqw5b9BApDLye6d:b-v08xw8) ([raw file](https://github.com/cockroachdb/cockroach/blob/19859e2d54c37c6dfe22e7d1cf710ddbef53fa3a/pkg/sql/sqlstats/persistedsqlstats/flush.go#L305)):*
> ```Go
> 
> 	if rowsAffected == 0 {
> 		return errors.New("failed to update transaction statistics")
> ```

Should this be an assertion error? What does this mean? I guess that no rows were selected, which should not be possible since we did the read and found a row in the same txn.
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 355 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67866#-MffIqK43x__JH5O7kmM:-MffIqK43x__JH5O7kmN:b-z3p5ge) ([raw file](https://github.com/cockroachdb/cockroach/blob/19859e2d54c37c6dfe22e7d1cf710ddbef53fa3a/pkg/sql/sqlstats/persistedsqlstats/flush.go#L355)):*
> ```Go
> 
> 	if rowsAffected == 0 {
> 		return errors.New("failed to update statement statistics")
> ```

ditto above
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 430 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67866#-MffH-tG4EV2BvErJQNZ:-MffH-tG4EV2BvErJQN_:b-fq1y1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/19859e2d54c37c6dfe22e7d1cf710ddbef53fa3a/pkg/sql/sqlstats/persistedsqlstats/flush.go#L430)):*
> ```Go
> 	  AND aggregated_ts = $3
>     AND node_id = $4
> FOR UPDATE
> ```

Technically I think this is not necessary since you've already tried to insert into it before... but I guess it doesn't matter either way. Maybe add a comment as to why the `FOR UPDATE`.
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 452 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67866#-MffHdIlCLTjUhnUS8pV:-MffHdIlCLTjUhnUS8pW:b-6fmlq) ([raw file](https://github.com/cockroachdb/cockroach/blob/19859e2d54c37c6dfe22e7d1cf710ddbef53fa3a/pkg/sql/sqlstats/persistedsqlstats/flush.go#L452)):*
> ```Go
> 
> 	if row == nil {
> 		return errors.New("transaction statistics not found")
> ```

include fingerprint id like you did below
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 456 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67866#-MffHeks3yh9GWZVg0IS:-MffHeks3yh9GWZVg0IT:bue500j) ([raw file](https://github.com/cockroachdb/cockroach/blob/19859e2d54c37c6dfe22e7d1cf710ddbef53fa3a/pkg/sql/sqlstats/persistedsqlstats/flush.go#L456)):*
> ```Go
> 
> 	if len(row) != 1 {
> 		return errors.AssertionFailedf("unexpected number of returning columns")
> ```

include unexpected number (yes, it seems impossible :))
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 509 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67866#-MffHhm3AlIReYi1sAIz:-MffHhm3AlIReYi1sAJ-:b-z3p5ge) ([raw file](https://github.com/cockroachdb/cockroach/blob/19859e2d54c37c6dfe22e7d1cf710ddbef53fa3a/pkg/sql/sqlstats/persistedsqlstats/flush.go#L509)):*
> ```Go
> 
> 	if len(row) != 1 {
> 		return errors.AssertionFailedf("unexpected number of returning columns")
> ```

ditto above
___
*[pkg/sql/sqlstats/persistedsqlstats/provider.go, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67866#-MffHtYK45wb3tMQdeZJ:-MffHtYK45wb3tMQdeZK:b3x4j0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/19859e2d54c37c6dfe22e7d1cf710ddbef53fa3a/pkg/sql/sqlstats/persistedsqlstats/provider.go#L34)):*
> ```Go
> //  Once we are able get consistent hash value from a query plan, we should
> //  update this.
> const dummyPlanHash = int64(0)
> ```

cc @cucaroach - please talk with @azhng about your ideas for that reconstructable serialized plan vs an integer hash to discuss tradeoffs / requirements. thanks!

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67866)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @jordanlewis)

___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67866#-MffJ3t99PEx41rVffdh:-MgBjZnuCJ4Wu_fg-ozr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/19859e2d54c37c6dfe22e7d1cf710ddbef53fa3a/pkg/sql/sqlstats/persistedsqlstats/flush.go#L32)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

It would be nice to also include the number of bytes in the sql stats, since that's a condition for flushing as well.
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 305 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67866#-MffIdqw5b9BApDLye6c:-MgBl42c9CgGgOrd07Mp:b4fpetq) ([raw file](https://github.com/cockroachdb/cockroach/blob/19859e2d54c37c6dfe22e7d1cf710ddbef53fa3a/pkg/sql/sqlstats/persistedsqlstats/flush.go#L305)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Should this be an assertion error? What does this mean? I guess that no rows were selected, which should not be possible since we did the read and found a row in the same txn.
</blockquote></details>

Yeah it should be impossible because the otherwise the `INSERT` statement before should succeed. Changed to `errors.AssertionFailf`
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 355 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67866#-MffIqK43x__JH5O7kmM:-MgBleeM9syaEif9DEhz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/19859e2d54c37c6dfe22e7d1cf710ddbef53fa3a/pkg/sql/sqlstats/persistedsqlstats/flush.go#L355)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

ditto above
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 430 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67866#-MffH-tG4EV2BvErJQNZ:-MgBlybf2wz9-j5LZITo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/19859e2d54c37c6dfe22e7d1cf710ddbef53fa3a/pkg/sql/sqlstats/persistedsqlstats/flush.go#L430)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Technically I think this is not necessary since you've already tried to insert into it before... but I guess it doesn't matter either way. Maybe add a comment as to why the `FOR UPDATE`.
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 452 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67866#-MffHdIlCLTjUhnUS8pV:-MgBmZvh2M3SJXdfAunL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/19859e2d54c37c6dfe22e7d1cf710ddbef53fa3a/pkg/sql/sqlstats/persistedsqlstats/flush.go#L452)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

include fingerprint id like you did below
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 456 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67866#-MffHeks3yh9GWZVg0IS:-MgBm_jb8m9MALMWgfa-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/19859e2d54c37c6dfe22e7d1cf710ddbef53fa3a/pkg/sql/sqlstats/persistedsqlstats/flush.go#L456)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

include unexpected number (yes, it seems impossible :))
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 509 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67866#-MffHhm3AlIReYi1sAIz:-MgBmk7n4hunnjHmPK65:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/19859e2d54c37c6dfe22e7d1cf710ddbef53fa3a/pkg/sql/sqlstats/persistedsqlstats/flush.go#L509)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

ditto above
</blockquote></details>

Done.

**Review by jordanlewis — COMMENTED** [review]
> Reviewed 27 of 27 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67866)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @jordanlewis)

___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 305 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67866#-MffIdqw5b9BApDLye6c:-MgC-Ftz2TbGoW0ujhzO:bmlwns4) ([raw file](https://github.com/cockroachdb/cockroach/blob/19859e2d54c37c6dfe22e7d1cf710ddbef53fa3a/pkg/sql/sqlstats/persistedsqlstats/flush.go#L305)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Yeah it should be impossible because the otherwise the `INSERT` statement before should succeed. Changed to `errors.AssertionFailf`
</blockquote></details>

nit: there's a mismatch between number of args and number of fmt strings
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 355 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67866#-MffIqK43x__JH5O7kmM:-MgC-PIF0_9-ofCah09x:bmlwns4) ([raw file](https://github.com/cockroachdb/cockroach/blob/19859e2d54c37c6dfe22e7d1cf710ddbef53fa3a/pkg/sql/sqlstats/persistedsqlstats/flush.go#L355)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: there's a mismatch between number of args and number of fmt strings
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 452 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67866#-MffHdIlCLTjUhnUS8pV:-MgC-fq7AtIuP66sjAMs:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/19859e2d54c37c6dfe22e7d1cf710ddbef53fa3a/pkg/sql/sqlstats/persistedsqlstats/flush.go#L452)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ditto
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 456 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67866#-MffHeks3yh9GWZVg0IS:-MgC-gGJ1X0DJ1O-4b7G:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/19859e2d54c37c6dfe22e7d1cf710ddbef53fa3a/pkg/sql/sqlstats/persistedsqlstats/flush.go#L456)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ditto
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 509 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67866#-MffHhm3AlIReYi1sAIz:-MgC-i4BDf2Nw5FYZmTW:b-z3m97f) ([raw file](https://github.com/cockroachdb/cockroach/blob/19859e2d54c37c6dfe22e7d1cf710ddbef53fa3a/pkg/sql/sqlstats/persistedsqlstats/flush.go#L509)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ditto again

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67866)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @jordanlewis)

___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 305 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67866#-MffIdqw5b9BApDLye6c:-MgCCUbW-EguC-4fXyU-:bgj659b) ([raw file](https://github.com/cockroachdb/cockroach/blob/19859e2d54c37c6dfe22e7d1cf710ddbef53fa3a/pkg/sql/sqlstats/persistedsqlstats/flush.go#L305)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: there's a mismatch between number of args and number of fmt strings
</blockquote></details>

:facepalm: , oof. Thought Goland would have caught this. Fixed 
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 355 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67866#-MffIqK43x__JH5O7kmM:-MgCCZe95ysbtuUajXtr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/19859e2d54c37c6dfe22e7d1cf710ddbef53fa3a/pkg/sql/sqlstats/persistedsqlstats/flush.go#L355)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: there's a mismatch between number of args and number of fmt strings
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 452 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67866#-MffHdIlCLTjUhnUS8pV:-MgCCT9Z0vAxpn6E03-M:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/19859e2d54c37c6dfe22e7d1cf710ddbef53fa3a/pkg/sql/sqlstats/persistedsqlstats/flush.go#L452)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 456 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67866#-MffHeks3yh9GWZVg0IS:-MgCCTk9Acq1hZmjieeW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/19859e2d54c37c6dfe22e7d1cf710ddbef53fa3a/pkg/sql/sqlstats/persistedsqlstats/flush.go#L456)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 509 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67866#-MffHhm3AlIReYi1sAIz:-MgCCU2AAkaK6eiFhjYU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/19859e2d54c37c6dfe22e7d1cf710ddbef53fa3a/pkg/sql/sqlstats/persistedsqlstats/flush.go#L509)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

ditto again
</blockquote></details>

Done.

**Review by jordanlewis — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67866#-:-MgLPq633h5zo3swSbSV:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng and @jordanlewis)

___
*[pkg/sql/catalog/systemschema/system.go, line 380 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/67866#-MgLPSZr6QI_4n3_7Ysb:-MgLPSZr6QI_4n3_7Ysc:b2ap15s) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fa5321ec1c0e1fb1c8c25bd57027e3fb25a6536/pkg/sql/catalog/systemschema/system.go#L380)):*
> ```Go
>     aggregated_ts  TIMESTAMPTZ NOT NULL,
>     fingerprint_id BYTES NOT NULL,
>     plan_hash      INT NOT NULL,
> ```

Let's change all of the `INT` to `INT8` to make sure we don't run into problems later if defaults change.

**Comment by Azhng** [comment]
TFTR! 

bors r+

**Pull request merged**
