### PR TITLE
distsql: Implement INTERSECT/EXCEPT ALL plans

### PR DESCRIPTION
**Pull request by abhimadan**
Part of #10432, #21661, and #21706.

Release note (performance improvement): Support distributed execution of
INTERSECT ALL and EXCEPT ALL queries.

### CODE REVIEW

**Comment by abhimadan** [comment]
I forgot to write EXCEPT ALL logic tests. Adding those now.

**Comment by abhimadan** [comment]
Added the tests. Although, after staring at the resulting plans for a bit, I think I can make improve them more so that the planner tries harder to distribute the join whenever possible.

**Comment by abhimadan** [comment]
Should be better now. PTAL!

**Comment by arjunravinarayan** [comment]
Great work! The code looks outstanding to me as is. And the new test cases are great and comprehensive.

One tip: a majority of the code change here is code movement, and separating code movement changes into its own commit would greatly expedite reviewing.

The plans in the logic tests are currently hard to understand - the hash joiner and merge joiners do a lot more work now, but their `Summary()`s don't indicate all the extra information that we've added. They need updating (and the logic tests will thus change). I would appreciate it if you put that change in a separate commit _before_ this commit so that all the changes to the existing tests that exercise join code don't get combined with the changes already here.

---

Reviewed 4 of 5 files at r1, 2 of 2 files at r2.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/distsqlplan/physical_plan.go, line 788 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21896#-L47uykIjgmbKF9LmeKX:-L47uykJvdSbrih8pQ3b:b6lnp26) ([raw file](https://github.com/cockroachdb/cockroach/blob/85fa8f03eaa98bcba28861b60689f542e40de585/pkg/sql/distsqlplan/physical_plan.go#L788)):*
> ```Go
> 	stageID := p.NewStageID()
> 
> 	// Each node has a join processor.
> ```

tiny nit: obvious comment can be elided.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21896#-:-L47yY3OkV07C0eqQm8_:bgcsh3m)*

**Comment by abhimadan** [comment]
Split up the commit into two. Still need to improve the `Summary()`s, but I might address that in a separate PR and get that merged first, since I think that joins in general don't have much information and I want to improve those as well (for example, the diagrams don't tell you the join type).

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/distsql_physical_planner.go, line 1960 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21896#-L48VVQ3mJtgnJbOAKYo:-L48VVQ453jTk4_yAgwP:b-4paguu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4826072aa29b40d81cd51609e8d6a615597d0ab7/pkg/sql/distsql_physical_planner.go#L1960)):*
> ```Go
> 		var newMergeOrdering distsqlrun.Ordering
> 		newMergeOrdering.Columns = make([]distsqlrun.Ordering_Column, 0, len(mergeOrdering.Columns))
> 		for _, ord := range mergeOrdering.Columns {
> ```

I'm starting to think that this logic isn't entirely correct. The `mergeJoinOrdering` from `physicalProps` seems to stop once it finds an ordering mismatch. This makes sense since because the other minor orderings aren't meaningful once the major ordering diverges. Similarly, we have to recognize when we strip out a major ordering here, which would force us to use the hash joiner. Using the merge joiner has the potential to produce incorrect results if we base our decision on minor orderings.

An example query of what I'm thinking of is `(SELECT y FROM xyz ORDER BY z,y) EXCEPT ALL (SELECT x FROM xyz ORDER BY z,x)`. It's difficult to produce a test case that has incorrect rows returned, but the query plan for this is [here](https://cockroachdb.github.io/distsqlplan/decode.html?eJzUl0Fv2kAQhe_9FdGcWrGVsmuTNJYq-ZpKTaq0t4qDg6fEEmHR2kihEf-9Mj44mHgeq0W43Ar485t9nufXvNLC5nyXPXNJyW_SpMiQoogUxaRoTBNFS2enXJbW1Zc0wG3-QsmlomKxXFX11xNFU-uYkleqimrOlNCv7HHOD5zl7EhRzlVWzLciS1c8Z26dvqz_kqL7VZVcpFqlEU02iuyqam9ZVtmMKdEbdbjsT-uqrmJqRirVo1atI9XSj-uLp6x86uD19e04xmccLxeM5EL0f7kQ947T3se6nB3n3fuMauGDrnrnZN_ZzfibLRbd4835T_Ux1aNPX10xe2r-2XvW9hzjsHO8M-Gd_WyXO9f2aV_taOth8gRkT52nY7rgkafBXYh7xznnPJlhdhrInnqnj-mCx04P7kLcO84573Q0zE4D2VPv9DFd8NjpwV2Ie8c5552Oh9lpIHvqnT6mCx47PbgLce8457zT4E-kBy6XdlHyQf9Tv6zH53zGjSmlXbkp_3B2upVpPt5vue0XOZdV86tuPtwump_qAd_Cugvrt3C8A2s_WF8G0eMQ2gRpG6BtRMcj2fHIw3HjB3cc96XHIbQJ0jZAOxYdB49rLMLmSn5eVyJ9LcPXIfGSYRQvQAPPZBrFC9BA-4vo-I3s-E1IvGQYxQvQYMVlGsUL0EBbyx2CXsV7b9PdBjKggvZep14dJNOwhACOji7jsIYAjtT3Xqq7xsfA-L23qk9WAI3CgnC0sTKO4oJwpC5XCnpscqVo0Ck6qFQADfMSVisAh3kJKxYtN4sG1aKDugXQMC9h7QJwmJewfjFB_WLkfjGgX0xQvwAa5QXh6Ohh_YJwpC73iwH9YoL6BdAoLwhHGxvWLwhH6n79Mtl8-BcAAP__gR4_3Q==). We don't want to use the mergejoiner for this query.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21896#-:-L48VCuf4m9lP6A1hR_a:b-qi0r6k)*

**Comment by abhimadan** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/distsqlplan/physical_plan.go, line 788 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21896#-L47uykIjgmbKF9LmeKX:-L48W4ibFZctFmDm0zOE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/85fa8f03eaa98bcba28861b60689f542e40de585/pkg/sql/distsqlplan/physical_plan.go#L788)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

tiny nit: obvious comment can be elided.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21896)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/distsql_physical_planner.go, line 1960 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21896#-L48VVQ3mJtgnJbOAKYo:-L49G1XnlKOBkO6w3uh9:b-s5kuiq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4826072aa29b40d81cd51609e8d6a615597d0ab7/pkg/sql/distsql_physical_planner.go#L1960)):*
<details><summary><i>Previously, abhimadan (Abhishek Madan) wrote…</i></summary><blockquote>

I'm starting to think that this logic isn't entirely correct. The `mergeJoinOrdering` from `physicalProps` seems to stop once it finds an ordering mismatch. This makes sense since because the other minor orderings aren't meaningful once the major ordering diverges. Similarly, we have to recognize when we strip out a major ordering here, which would force us to use the hash joiner. Using the merge joiner has the potential to produce incorrect results if we base our decision on minor orderings.

An example query of what I'm thinking of is `(SELECT y FROM xyz ORDER BY z,y) EXCEPT ALL (SELECT x FROM xyz ORDER BY z,x)`. It's difficult to produce a test case that has incorrect rows returned, but the query plan for this is [here](https://cockroachdb.github.io/distsqlplan/decode.html?eJzUl0Fv2kAQhe_9FdGcWrGVsmuTNJYq-ZpKTaq0t4qDg6fEEmHR2kihEf-9Mj44mHgeq0W43Ar485t9nufXvNLC5nyXPXNJyW_SpMiQoogUxaRoTBNFS2enXJbW1Zc0wG3-QsmlomKxXFX11xNFU-uYkleqimrOlNCv7HHOD5zl7EhRzlVWzLciS1c8Z26dvqz_kqL7VZVcpFqlEU02iuyqam9ZVtmMKdEbdbjsT-uqrmJqRirVo1atI9XSj-uLp6x86uD19e04xmccLxeM5EL0f7kQ947T3se6nB3n3fuMauGDrnrnZN_ZzfibLRbd4835T_Ux1aNPX10xe2r-2XvW9hzjsHO8M-Gd_WyXO9f2aV_taOth8gRkT52nY7rgkafBXYh7xznnPJlhdhrInnqnj-mCx04P7kLcO84573Q0zE4D2VPv9DFd8NjpwV2Ie8c5552Oh9lpIHvqnT6mCx47PbgLce8457zT4E-kBy6XdlHyQf9Tv6zH53zGjSmlXbkp_3B2upVpPt5vue0XOZdV86tuPtwump_qAd_Cugvrt3C8A2s_WF8G0eMQ2gRpG6BtRMcj2fHIw3HjB3cc96XHIbQJ0jZAOxYdB49rLMLmSn5eVyJ9LcPXIfGSYRQvQAPPZBrFC9BA-4vo-I3s-E1IvGQYxQvQYMVlGsUL0EBbyx2CXsV7b9PdBjKggvZep14dJNOwhACOji7jsIYAjtT3Xqq7xsfA-L23qk9WAI3CgnC0sTKO4oJwpC5XCnpscqVo0Ck6qFQADfMSVisAh3kJKxYtN4sG1aKDugXQMC9h7QJwmJewfjFB_WLkfjGgX0xQvwAa5QXh6Ohh_YJwpC73iwH9YoL6BdAoLwhHGxvWLwhH6n79Mtl8-BcAAP__gR4_3Q==). We don't want to use the mergejoiner for this query.
</blockquote></details>

It is not ok to just remove columns from merge ordering; that will result in an `ORDER BY` no longer being respected. In the plan you linked above, notice how we sort by @2 but then that ordering is lost because we no longer take @2 into account in the final ordered synchronizer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21896)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 1960 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21896#-L48VVQ3mJtgnJbOAKYo:-L49U761X9oF2WQXb2-I:b-982rd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4826072aa29b40d81cd51609e8d6a615597d0ab7/pkg/sql/distsql_physical_planner.go#L1960)):*
<details><summary><i>Previously, abhimadan (Abhishek Madan) wrote…</i></summary><blockquote>

Right. In my earlier comment, I was saying that the plan I linked is incorrect, since that ordering isn't actually respected by the input streams (though I think dropping the @2 would be fine if the ordering was @1+,@2+ instead of @2+,@1+). I think the correct thing to do here is to use `computeMergeJoinOrdering` instead of just dropping things from the ordering, since that contains many more special cases that I haven't considered here, and guarantees that the new ordering will be consistent with the old one.

I think we're on the same page here, but let me know if I'm misunderstanding something.
</blockquote></details>

Yes, it's also incorrect in that (more serious) aspect. But my point is that it's never correct to just drop something from the merge ordering (even if it's at the end). It would still be incorrect even if we had `@1+, @2+`. If we drop `@2` along the way, we won't be able to maintain that ordering when we merge streams. As an example (not related to set ops), say you are doing `SELECT a, c FROM t ORDER BY a, b`. You might have two table readers, one outputting rows `(1, 1, 10), (1, 2, 20)`  and another one `(1, 5, 50)`.  If we drop `b` along the way, we won't be able to guarantee that `1, 50` will come after `1, 10` and `1, 20` when we finally merge the two streams.

I think that if we need to drop anything from the ordering, we should just fall back to the `else` case below where we bring everything on one node.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21896)*

**Comment by abhimadan** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 1960 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21896#-L48VVQ3mJtgnJbOAKYo:-L4BkRxaO5RaZWaDs6Ew:bvq986a) ([raw file](https://github.com/cockroachdb/cockroach/blob/4826072aa29b40d81cd51609e8d6a615597d0ab7/pkg/sql/distsql_physical_planner.go#L1960)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yes, it's also incorrect in that (more serious) aspect. But my point is that it's never correct to just drop something from the merge ordering (even if it's at the end). It would still be incorrect even if we had `@1+, @2+`. If we drop `@2` along the way, we won't be able to maintain that ordering when we merge streams. As an example (not related to set ops), say you are doing `SELECT a, c FROM t ORDER BY a, b`. You might have two table readers, one outputting rows `(1, 1, 10), (1, 2, 20)`  and another one `(1, 5, 50)`.  If we drop `b` along the way, we won't be able to guarantee that `1, 50` will come after `1, 10` and `1, 20` when we finally merge the two streams.

I think that if we need to drop anything from the ordering, we should just fall back to the `else` case below where we bring everything on one node.
</blockquote></details>

Looks like [this `EXPLAIN` diagram](https://cockroachdb.github.io/distsqlplan/decode.html?eJzcl09r20AUxO_9FOadWrKF7EpOGkFB1xSalLS34oNibW2BozWrNTQEf_di6-BYdt94eTIC3_xHP83u6M0OeqPalfaheLENZb9JkyJDihJSlJKiMU0ULb2b2qZxfnNJC9yXfym7VlTVy1XY_DxRNHXeUvZGoQoLSxn9Kp4X9skWpfWkqLShqBZbkaWvXgr_mpdFKEjR4ypko1yrPKHJWpFbhd09m1DMLGV6rU7X_el86Erm-krl5ooUvRRhOh8tbJ2N9Htx0xHf3e_5dTQvmnn3hjRZ7xZoYhYYZ4zhjEn6M6YnJ9L_rmh3H-dL6215sJKN8ElXHdncd-tn9pur6u4OF_ZP-Jjrq09ffTWbtx9Pm7rxCVtZ1ceWeXSFD-6zW3YuOy58syesB4oZ0B0-Zr0aExEzkTFniZm-nJiZgaYd6A4_7b0aEzHtImPOMu3mcqY9GWjage7w096rMRHTLjLmLNOeXM60pwNNO9Adftp7NSZi2kXGnGXa08uZdvA29mSbpasbe9IbwfVmB7ac2daXxq381P7wbrqVab8-brntD6VtQvuvbr_c1-1fmwW-h3UX1u_hdA_WcbC-FtFjCW1E2gZoG9bxhHc8iXDcxMEdx2PpsYQ2Im0DtFPWcfC4xixsbvjndcPStzx8K4kXD6N4ARp4xtMoXoAG2l9Yx-94x-8k8eJhFC9AgxHnaRQvQANtzXcIOooPTtP9BjKggg6O06gO4mlYQgBHW-dxWEMAR-oHh-q-8Skw_uBUjckKoFFYEI4mlsdRXBCO1PlKQY-NrxQNOkWLSgXQMC-yWgE4zIusWDTfLBpUixZ1C6BhXmTtAnCYF1m_GFG_GL5fDOgXI-oXQKO8IBxtXdYvCEfqfL8Y0C9G1C-ARnlBOJpYWb8gHKnH9ctk_eFfAAAA__8HZGEA) for `SELECT l.a, r.b FROM (SELECT a FROM data ORDER BY a,c) l INNER JOIN (SELECT b FROM data ORDER BY b,c) r ON l.a = r.b` does drop the `@2` from the end of the ordering. This is very similar to the case I'm thinking of for set ops. And looking in `joinOrdering()`, it looks like a join propagates the ordering guaranteed by the merge joiner.

That said, I think that dropping the ordering upstream is probably not the right way to go, since as you've said, that could cause problems if the child plan is also merging multiple streams. In a previous PR, I added a check in `joinerbase.go` which compared the number of left and right-side result types with the number of equality columns, but after this discussion, I think that is too strong of an assertion to make. This issue can probably be resolved if I modify that check so that it allows cases where not all result streams appear in the set op columns. With this done, the projection on the child plans should no longer be necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21896)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 1960 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21896#-L48VVQ3mJtgnJbOAKYo:-L4CeKsTm9fBAuh3m52X:b-178uka) ([raw file](https://github.com/cockroachdb/cockroach/blob/4826072aa29b40d81cd51609e8d6a615597d0ab7/pkg/sql/distsql_physical_planner.go#L1960)):*
<details><summary><i>Previously, abhimadan (Abhishek Madan) wrote…</i></summary><blockquote>

Looks like [this `EXPLAIN` diagram](https://cockroachdb.github.io/distsqlplan/decode.html?eJzcl09r20AUxO_9FOadWrKF7EpOGkFB1xSalLS34oNibW2BozWrNTQEf_di6-BYdt94eTIC3_xHP83u6M0OeqPalfaheLENZb9JkyJDihJSlJKiMU0ULb2b2qZxfnNJC9yXfym7VlTVy1XY_DxRNHXeUvZGoQoLSxn9Kp4X9skWpfWkqLShqBZbkaWvXgr_mpdFKEjR4ypko1yrPKHJWpFbhd09m1DMLGV6rU7X_el86Erm-krl5ooUvRRhOh8tbJ2N9Htx0xHf3e_5dTQvmnn3hjRZ7xZoYhYYZ4zhjEn6M6YnJ9L_rmh3H-dL6215sJKN8ElXHdncd-tn9pur6u4OF_ZP-Jjrq09ffTWbtx9Pm7rxCVtZ1ceWeXSFD-6zW3YuOy58syesB4oZ0B0-Zr0aExEzkTFniZm-nJiZgaYd6A4_7b0aEzHtImPOMu3mcqY9GWjage7w096rMRHTLjLmLNOeXM60pwNNO9Adftp7NSZi2kXGnGXa08uZdvA29mSbpasbe9IbwfVmB7ac2daXxq381P7wbrqVab8-brntD6VtQvuvbr_c1-1fmwW-h3UX1u_hdA_WcbC-FtFjCW1E2gZoG9bxhHc8iXDcxMEdx2PpsYQ2Im0DtFPWcfC4xixsbvjndcPStzx8K4kXD6N4ARp4xtMoXoAG2l9Yx-94x-8k8eJhFC9AgxHnaRQvQANtzXcIOooPTtP9BjKggg6O06gO4mlYQgBHW-dxWEMAR-oHh-q-8Skw_uBUjckKoFFYEI4mlsdRXBCO1PlKQY-NrxQNOkWLSgXQMC-yWgE4zIusWDTfLBpUixZ1C6BhXmTtAnCYF1m_GFG_GL5fDOgXI-oXQKO8IBxtXdYvCEfqfL8Y0C9G1C-ARnlBOJpYWb8gHKnH9ctk_eFfAAAA__8HZGEA) for `SELECT l.a, r.b FROM (SELECT a FROM data ORDER BY a,c) l INNER JOIN (SELECT b FROM data ORDER BY b,c) r ON l.a = r.b` does drop the `@2` from the end of the ordering. This is very similar to the case I'm thinking of for set ops. And looking in `joinOrdering()`, it looks like a join propagates the ordering guaranteed by the merge joiner.

That said, I think that dropping the ordering upstream is probably not the right way to go, since as you've said, that could cause problems if the child plan is also merging multiple streams. In a previous PR, I added a check in `joinerbase.go` which compared the number of left and right-side result types with the number of equality columns, but after this discussion, I think that is too strong of an assertion to make. This issue can probably be resolved if I modify that check so that it allows cases where not all result streams appear in the set op columns. With this done, the projection on the child plans should no longer be necessary.
</blockquote></details>

So in that case the inner join doesn't guarantee any ordering and there is no top-level order by. I believe this corresponds to the semantics in the SQL standards.

In the case `(SELECT y FROM xyz ORDER BY z,y) EXCEPT ALL (SELECT x FROM xyz ORDER BY z,x)` I'm not sure if we need to guarantee any ordering, unless there's a "top level" ORDER BY. If we do, we will need to plumb `z` all the way to the end..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21896)*

**Comment by abhimadan** [comment]
Thanks your the comments so far @arjunravinarayan and @RaduBerinde! Made some significant changes to how ordering-only input streams are handled. Now, rather than adding a projection at the input level, the projection is now at the joiner level.

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsql_physical_planner.go, line 1960 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21896#-L48VVQ3mJtgnJbOAKYo:-L4Ct3T_H2G4JGQGOfpO:bw4d7rr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4826072aa29b40d81cd51609e8d6a615597d0ab7/pkg/sql/distsql_physical_planner.go#L1960)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

So in that case the inner join doesn't guarantee any ordering and there is no top-level order by. I believe this corresponds to the semantics in the SQL standards.

In the case `(SELECT y FROM xyz ORDER BY z,y) EXCEPT ALL (SELECT x FROM xyz ORDER BY z,x)` I'm not sure if we need to guarantee any ordering, unless there's a "top level" ORDER BY. If we do, we will need to plumb `z` all the way to the end..
</blockquote></details>

Seems like the SQL 1999 standard doesn't specify any ordering requirements for set operations without a top-level `ORDER BY` (which IMO makes sense -- the `z` isn't accessible at the top level, so an ordering based on it at the top level would appear to be arbitrary).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21896#-:-L4Crzg_WWVSaSMwBudF:bxf6wmt)*

**Comment by abhimadan** [comment]
Rebased to get the improved EXPLAIN diagrams. PTAL!

**Comment by asubiotto** [comment]
This looks good to me, great work! Left a few minor comments. I would wait for @RaduBerinde to give you the green light though

---

Reviewed 5 of 6 files at r4, 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 2040 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21896#-L4gTsbNcb4Qq-_uSqGN:-L4gTsbNcb4Qq-_uSqGO:bxi9ebh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4bd6ca2dd1023df30abf5af253afff33d6beea5/pkg/sql/distsql_physical_planner.go#L2040)):*
> ```Go
> 		// Set up the equality columns.
> 		eqCols := make([]uint32, len(streamCols))
> 		copy(eqCols, streamCols)
> ```

I'm curious: is there a need to make a copy here?

---

*[pkg/sql/distsqlplan/physical_plan.go, line 843 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21896#-L4gUmE7OJhGGFiCSlk4:-L4gUmE7OJhGGFiCSlk5:b-elayq0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4bd6ca2dd1023df30abf5af253afff33d6beea5/pkg/sql/distsqlplan/physical_plan.go#L843)):*
> ```Go
> // AddSetOpStage creates a join stage to implement INTERSECT ALL and EXCEPT ALL
> // plans.
> func (p *PhysicalPlan) AddSetOpStage(
> ```

Not sure this method is necessary, don't have strong feelings about it though

---

*[pkg/sql/logictest/testdata/logic_test/distsql_union, line 77 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21896#-L4gVaM8Pr-SeFm6BkX1:-L4gVaM8Pr-SeFm6BkX2:bz9psxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4bd6ca2dd1023df30abf5af253afff33d6beea5/pkg/sql/logictest/testdata/logic_test/distsql_union#L77)):*
> ```
> SELECT "URL" FROM [EXPLAIN (DISTSQL) SELECT x FROM xyz WHERE x < 3 UNION SELECT x FROM xyz WHERE x >= 3 ORDER BY x]
> ----
> https://cockroachdb.github.io/distsqlplan/decode.html?eJzMlkFr3DAQhe_9Fctcq8OO7E0aQWEPpbCXpKS5tT641hAMjmUkGZIG__di-5B6yY7qygYfLe2bN2_fd9Ar1EbTbf5EDtQPQBAgQUACAlIQcIBMQGNNQc4Z2_9kFJz0M6i9gLJuWt8fZwIKYwnUK_jSVwQKHvJfFd1TrsmCAE0-L6vBpLHlU25fjs8vv0HA17LyZNXuiLuf7X6fFLtEKXW6fQABd63vLyDrBJjWv3k5nz8SKOzEv-_zpXS-rAs_XYaZLudM_8-09HlG3GTVuOnF6W9D29pYTZb0ZGrWLeF_mJPuu7H-_J8-4seLw68mw3Fj5Ab2iSR3nbQR5C4dd0qu3Fi5gX0iy10nbUS5S8edlptsrNzAPpHlrpM2otyl407LTTdWbmCfyHLXSRtR7tJxLz8o3pl-T64xtaOzh8X7k_f9g4P0I42vE2daW9A3a4rBZvy8G3TDgSbnx1scP071eNUv-LcYWXE6EeO5WLLihHdOYpxTVnzgnQ-sWEpefcWqr3nxdUzoT6z4hne-iXHGAGMhyKIoQx4zDHCGUaAhTxoGUEOetZA5zxoGYMMo2pDHDQO8YRRwkgdOBoCT84DLug9_AgAA___KeT5X
> ```

Stupid question: Why has this changed? I also don't notice any obvious difference between the two plans.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21896#-:-L4g_hI_j9FXeeUD6sMs:bjofgwu)*

**Comment by abhimadan** [comment]
Review status: 4 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsql_physical_planner.go, line 2040 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21896#-L4gTsbNcb4Qq-_uSqGN:-L4gfPhc9U5UepNzH6Mw:b2nfggu) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4bd6ca2dd1023df30abf5af253afff33d6beea5/pkg/sql/distsql_physical_planner.go#L2040)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I'm curious: is there a need to make a copy here?
</blockquote></details>

I made it a shallow copy and it still seems to work. Thanks for pointing this out!

---

*[pkg/sql/distsqlplan/physical_plan.go, line 843 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21896#-L4gUmE7OJhGGFiCSlk4:-L4gf_bCD4pU6IWQ18TP:b-d751dk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4bd6ca2dd1023df30abf5af253afff33d6beea5/pkg/sql/distsqlplan/physical_plan.go#L843)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Not sure this method is necessary, don't have strong feelings about it though
</blockquote></details>

This had more value before I moved down the projection to the join stage, because some pairs of parameters like `{left,right}Types` were identical. Though I agree with you that it's not very helpful now, so I've removed it.

---

*[pkg/sql/logictest/testdata/logic_test/distsql_union, line 77 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21896#-L4gVaM8Pr-SeFm6BkX1:-L4gfpd5mjlhcfIX4M99:bsgjgy) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4bd6ca2dd1023df30abf5af253afff33d6beea5/pkg/sql/logictest/testdata/logic_test/distsql_union#L77)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Stupid question: Why has this changed? I also don't notice any obvious difference between the two plans.
</blockquote></details>

The plans are functionally identical, with the only difference being the order of inputs being merged together (I'm honestly not even sure if they look visually different, might just be in the query string).

The reason this happened is that UNION plans previously didn't take into account the `inverted` flag on the `unionNode`. This PR takes it into account because it's important for correctness of EXCEPT ALL queries, but the change flipped the input orderings for UNION queries.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21896)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 4 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/sql/logictest/testdata/logic_test/distsql_union, line 77 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21896#-L4gVaM8Pr-SeFm6BkX1:-L4ghB5Yog3IsSc5Tpon:b8sqr0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4bd6ca2dd1023df30abf5af253afff33d6beea5/pkg/sql/logictest/testdata/logic_test/distsql_union#L77)):*
<details><summary><i>Previously, abhimadan (Abhishek Madan) wrote…</i></summary><blockquote>

The plans are functionally identical, with the only difference being the order of inputs being merged together (I'm honestly not even sure if they look visually different, might just be in the query string).

The reason this happened is that UNION plans previously didn't take into account the `inverted` flag on the `unionNode`. This PR takes it into account because it's important for correctness of EXCEPT ALL queries, but the change flipped the input orderings for UNION queries.
</blockquote></details>

Yeah it's possible to have two different plans that look the same (depends on the order of the processors in the plan, the order of streams etc)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21896#-:-L4ghaL1cSbHaQ_orLh4:bnfp4nl)*

**Pull request merged**
