### PR TITLE
hlc: fix HybridManualClock.Pause

### LINKED ISSUE #60914: kv/kvserver: TestLeaseholdersRejectClockUpdateWithJump failed
[(kv/kvserver).TestLeaseholdersRejectClockUpdateWithJump failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2702602&tab=buildLog) on [master@bf9744bad5a416a4b06907f0f3dd42896f7342f3](https://github.com/cockroachdb/cockroach/commits/bf9744bad5a416a4b06907f0f3dd42896f7342f3):

```
=== RUN   TestLeaseholdersRejectClockUpdateWithJump
    test_log_scope.go:73: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestLeaseholdersRejectClockUpdateWithJump291996701
    test_log_scope.go:74: use -show-logs to present logs inline
    client_replica_test.go:266: remote wall time is too far ahead (500.00652ms) to be trustworthy
    panic.go:636: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestLeaseholdersRejectClockUpdateWithJump291996701
--- FAIL: TestLeaseholdersRejectClockUpdateWithJump (1.57s)

```

<details><summary>More</summary><p>
Parameters:

- TAGS=
- GOFLAGS=-race -parallel=4

```
make stressrace TESTS=TestLeaseholdersRejectClockUpdateWithJump PKG=./pkg/kv/kvserver TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestLeaseholdersRejectClockUpdateWithJump.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by andreimatei**
Pause() reads the clock and saved the reading to be
returned from now on. The bgu was that the reading and the saving were
not atomic - it was possible to read, then the still-not-paused clock to
hand out higher timestamps to others, then to write. This created a
backwards clock jump, which is unexpected. In particular, such a jump
broke the logic in TestLeaseholdersRejectClockUpdateWithJump.

Fixes #60914

Release note: None

### CODE REVIEW

**Comment by stevendanna** [comment]
The BazelCI failure here is likely my fault, you should be able to ignore it. (https://github.com/cockroachdb/cockroach/pull/64270)

**Comment by lunevalex** [comment]
Nice find, thanks for fixing.

**Review by lunevalex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64242#-:-MZISe3hDGz6C4dtZQXZ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64242#-:-MZJ3sqU6cwtIs5tOWrI:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
