### PR TITLE
sql: use micro instead of nano seconds for timestamps

### LINKED ISSUE #6597: sql: python psycopg2 errors on `now()`
The following:

```
import psycopg2
conn = psycopg2.connect('')
cur = conn.cursor()
cur.execute("SELECT now()")
v = cur.fetchall()
print v
```

produces an error:

`ValueError: microsecond must be in 0..999999`.

Invoked with:

`docker run --rm --net=host -e PGHOST=127.0.0.1 -e PGPORT=26257 -v $(PWD):/data cockroachdb/postgres-test python /data/test.py`

### PR DESCRIPTION
**Pull request by madelynnblue**
Matches Postgres.

Fixes #6597

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6604)

### CODE REVIEW

**Comment by dt** [comment]
:lgtm:

<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> #### sql: use micro instead of nano seconds for timestamps
> 
> Matches Postgres.
> 
> 
> 
> Fixes #6597
> 
> 
> </details>


---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[acceptance/python_test.go, line 38 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6604#-KHNhnfyf06kIibQh1oA:-KHNhnfyf06kIibQh1oB:-185561222) ([raw file](https://github.com/cockroachdb/cockroach/blob/69ea08ef5d97c21552aca63379998b875e9e2e83/acceptance/python_test.go#L38)):*
> ```Go
> # verify we can parse a timestamp
> cur = conn.cursor()
> cur.execute("SELECT now()")
> ```

Could probably just throw this in the select above, and then slice it for the assertion?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6604#-:-KHNi0jKrl3OfBzR25NV:1417088721)*

**Comment by mjibson** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[acceptance/python_test.go, line 38 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6604#-KHNhnfyf06kIibQh1oA:-KHNim9zz27W7eODNgZk:620525726) ([raw file](https://github.com/cockroachdb/cockroach/blob/69ea08ef5d97c21552aca63379998b875e9e2e83/acceptance/python_test.go#L38)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> Could probably just throw this in the select above, and then slice it for the assertion?</details>
I'm inclined to leave it like this because it's clear that the comment is referring specifically to that statement and I think the slicing reduces the code clarity since it merges two logical tests into one statement.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6604)*

**Comment by dt** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[acceptance/python_test.go, line 38 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6604#-KHNhnfyf06kIibQh1oA:-KHNjVBML6JFAS5vd3Zi:262468467) ([raw file](https://github.com/cockroachdb/cockroach/blob/69ea08ef5d97c21552aca63379998b875e9e2e83/acceptance/python_test.go#L38)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> I'm inclined to leave it like this because it's clear that the comment is referring specifically to that statement and I think the slicing reduces the code clarity since it merges two logical tests into one statement.</details>
:thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6604)*

**Comment by mjibson** [comment]
@dt hints about how to fix the current test failure? It's due to that old-vs-new-binary testing thing. The format changed, so...

**Comment by dt** [comment]
@mjibson maybe change the `SELECT` in the acceptance test to just get unix time or something?

**Comment by mjibson** [comment]
**DO NOT MERGE**

There is a pending design decision about whether or not we want to do this. See the discussion at https://gitter.im/cockroachdb/cockroach?at=57322aef12fa465406ebb182

**Comment by knz** [comment]
Reviewed 3 of 3 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/pgwire/types.go, line 211 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6604#-KHUaNA3vABpdv_Yfrgt:-KHUaNA4WrIT-huM0XwK:1761867081) ([raw file](https://github.com/cockroachdb/cockroach/blob/69ea08ef5d97c21552aca63379998b875e9e2e83/sql/pgwire/types.go#L211)):*
> ```Go
> 
> const pgTimeStampFormatNoOffset = "2006-01-02 15:04:05.999999"
> const pgTimeStampFormat = pgTimeStampFormatNoOffset + "-07:00"
> ```

Out of curiosity, is there a reason to fix the timezone to New York time? This feels wrong to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6604)*

**Comment by dt** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/pgwire/types.go, line 211 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6604#-KHUaNA3vABpdv_Yfrgt:-KHUaq9AeMi8Muy_x14u:257453410) ([raw file](https://github.com/cockroachdb/cockroach/blob/69ea08ef5d97c21552aca63379998b875e9e2e83/sql/pgwire/types.go#L211)):*
> ```Go
> 
> const pgTimeStampFormatNoOffset = "2006-01-02 15:04:05.999999"
> const pgTimeStampFormat = pgTimeStampFormatNoOffset + "-07:00"
> ```

That isn't New York (-5) -- it's the reference time from Go.
 
>  The layout defines the format by showing how the reference time, defined to be
> `Mon Jan 2 15:04:05 -0700 MST 2006` would be interpreted if it were the value.

https://golang.org/pkg/time/#Parse

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6604)*

**Comment by dt** [comment]
:lgtm:

<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> **DO NOT MERGE**
> 
> 
> 
> There is a pending design decision about whether or not we want to do this. See the discussion at https://gitter.im/cockroachdb/cockroach?at=57322aef12fa465406ebb182</details>


---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 8 of 8 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6604#-:-KHed2x4mpVc6MLg76yz:1417088721)*

**Comment by bdarnell** [comment]
:lgtm:

This is a nice solution (better than the others in the doc). We'll have to put a big "here be dragons" warning on the `_ns` functions. 

Should we advise people to strip the nanoseconds from their existing timestamp data?  System.lease has existing nanosecond data that is difficult to strip; going forward should we round all lease expirations to microseconds?

<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> :lgtm:</details>


---

Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 8 of 8 files at r5.
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[acceptance/python_test.go, line 36 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6604#-KHfFwQDF6wgv1Qeq7XB:-KHfFwQEQBeChefUj73V:126787445) ([raw file](https://github.com/cockroachdb/cockroach/blob/2285a66f8a317946a47d967c57f6af418a2433f9/acceptance/python_test.go#L36)):*
> ```Go
> v = cur.fetchall()
> assert v == [(1, 5)]
> # verify we can parse a timestamp
> ```

Not just any timestamp: inserting a hand-constructed timestamp and reading it back wouldn't trigger the bug. I'm not sure how to say that in a comment, though. We can't just say "a timestamp with non-zero nanoseconds" since that's no longer true. Maybe just a link back to the bug.

---

*[sql/parser/builtins.go, line 639 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6604#-KHfLcV-DZQDBsTViE-p:-KHfLcV-DZQDBsTViE-q:-778226611) ([raw file](https://github.com/cockroachdb/cockroach/blob/2285a66f8a317946a47d967c57f6af418a2433f9/sql/parser/builtins.go#L639)):*
> ```Go
> 	},
> 
> 	"format_timestamp_ns": {
> ```

This appears to be untested.

---

*[sql/parser/datum.go, line 826 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6604#-KHfMdn4TuWIiZP5Dv4O:-KHfMdn4TuWIiZP5Dv4P:-937903251) ([raw file](https://github.com/cockroachdb/cockroach/blob/2285a66f8a317946a47d967c57f6af418a2433f9/sql/parser/datum.go#L826)):*
> ```Go
> // Format implements the NodeFormatter interface.
> func (d *DTimestampTZ) Format(buf *bytes.Buffer, f FmtFlags) {
> 	buf.WriteString(d.UTC().Format(timestampNodeFormat))
> ```

Not new in this change, but are DTimestamp.Format and DTimestampTZ supposed to be identical? 

---

*[sql/parser/eval.go, line 1998 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6604#-KHfQrsihSpacQ2kdg8H:-KHfQrsihSpacQ2kdg8I:1806771503) ([raw file](https://github.com/cockroachdb/cockroach/blob/2285a66f8a317946a47d967c57f6af418a2433f9/sql/parser/eval.go#L1998)):*
> ```Go
> const (
> 	dateFormat                            = "2006-01-02"
> 	timestampFormat                       = "2006-01-02 15:04:05"
> ```

Where do we use these second-resolution formats?

---

*[sql/testdata/datetime, line 375 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6604#-KHfK_MVuIifIPLWtqV7:-KHfK_MVuIifIPLWtqV8:282202559) ([raw file](https://github.com/cockroachdb/cockroach/blob/2285a66f8a317946a47d967c57f6af418a2433f9/sql/testdata/datetime#L375)):*
> ```
> # nanoseconds are truncated to microseconds
> query I
> SELECT extract(nanosecond from timestamp '2001-04-10 12:04:59.34565423')
> ```

Test/document the way this interacts with unique indexes: Inserting two timestamps that differ only in nanoseconds will fail with this syntax, while it works if parse_timestamp_ns is used.

---

*[sql/testdata/datetime, line 387 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6604#-KHfHSSPoFMyrXU5dKuG:-KHfHSSPoFMyrXU5dKuH:-1482976485) ([raw file](https://github.com/cockroachdb/cockroach/blob/2285a66f8a317946a47d967c57f6af418a2433f9/sql/testdata/datetime#L387)):*
> ```
> # current_timestamp_ns has nanoseconds
> query B
> SELECT extract(nanosecond from current_timestamp_ns()) % 1000 != 0
> ```

These tests will fail about 1 in 1000 times (or more often if the underlying clock is just padding out a less-precise timer to give a value in nanoseconds). The nightly stress runs go for at least 300 iterations on this package, so this will have an annoyingly high false positive rate. We need to generate multiple timestamps and verify that at least some of them have non-zero nanoseconds. (here and in the system.lease test below)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6604#-:-KHfRi6ORpwCGxwZkt5z:988998356)*

**Comment by mjibson** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[acceptance/python_test.go, line 36 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6604#-KHfFwQDF6wgv1Qeq7XB:-KHfVLT-pkX5MiI6_mzI:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/2285a66f8a317946a47d967c57f6af418a2433f9/acceptance/python_test.go#L36)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Not just any timestamp: inserting a hand-constructed timestamp and reading it back wouldn't trigger the bug. I'm not sure how to say that in a comment, though. We can't just say "a timestamp with non-zero nanoseconds" since that's no longer true. Maybe just a link back to the bug.</details>
Done.

---

*[sql/parser/builtins.go, line 639 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6604#-KHfLcV-DZQDBsTViE-p:-KHfWakjAO_t00ZZt8B-:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/2285a66f8a317946a47d967c57f6af418a2433f9/sql/parser/builtins.go#L639)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> This appears to be untested.</details>
Done.

---

*[sql/parser/datum.go, line 826 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6604#-KHfMdn4TuWIiZP5Dv4O:-KHfYp0hMHG-AGC_Ri0D:-1810111083) ([raw file](https://github.com/cockroachdb/cockroach/blob/2285a66f8a317946a47d967c57f6af418a2433f9/sql/parser/datum.go#L826)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Not new in this change, but are DTimestamp.Format and DTimestampTZ supposed to be identical? </details>
That behavior is unspecified. However I agree with you and will propose a fix to this in a followup PR.

---

*[sql/parser/eval.go, line 1998 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6604#-KHfQrsihSpacQ2kdg8H:-KHfZjJ9_-FYR8iSYy7I:956776072) ([raw file](https://github.com/cockroachdb/cockroach/blob/2285a66f8a317946a47d967c57f6af418a2433f9/sql/parser/eval.go#L1998)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Where do we use these second-resolution formats?</details>
The subsecond precision part is only required for output, not parsing. See: https://play.golang.org/p/2yTGWPoEt4

---

*[sql/testdata/datetime, line 387 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6604#-KHfHSSPoFMyrXU5dKuG:-KHgurRHY1pzuwapdf-3:-1776910492) ([raw file](https://github.com/cockroachdb/cockroach/blob/2285a66f8a317946a47d967c57f6af418a2433f9/sql/testdata/datetime#L387)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> These tests will fail about 1 in 1000 times (or more often if the underlying clock is just padding out a less-precise timer to give a value in nanoseconds). The nightly stress runs go for at least 300 iterations on this package, so this will have an annoyingly high false positive rate. We need to generate multiple timestamps and verify that at least some of them have non-zero nanoseconds. (here and in the system.lease test below)</details>
I'm not sure we can do this in the testdata tests. The timestamp data gets set at the beginning of each statement. Thus, we'd have to have multiple statements and OR the results between them. I think these would have to be moved to a _test.go file to properly test them. Do you know another way?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6604)*

**Comment by mjibson** [comment]
Review status: 8 of 10 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[sql/testdata/datetime, line 375 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6604#-KHfK_MVuIifIPLWtqV7:-KHgzEeYYTuP6rugl8kE:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/2285a66f8a317946a47d967c57f6af418a2433f9/sql/testdata/datetime#L375)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Test/document the way this interacts with unique indexes: Inserting two timestamps that differ only in nanoseconds will fail with this syntax, while it works if parse_timestamp_ns is used.</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6604)*

**Comment by bdarnell** [comment]
Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/testdata/datetime, line 387 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6604#-KHfHSSPoFMyrXU5dKuG:-KHrN_E5NRgZw-O-ycZI:-1466510512) ([raw file](https://github.com/cockroachdb/cockroach/blob/2285a66f8a317946a47d967c57f6af418a2433f9/sql/testdata/datetime#L387)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> I'm not sure we can do this in the testdata tests. The timestamp data gets set at the beginning of each statement. Thus, we'd have to have multiple statements and OR the results between them. I think these would have to be moved to a _test.go file to properly test them. Do you know another way?</details>
You could do it in a testdata file with a table: `INSERT INTO t VALUES (now())`, repeated a few times, then `SELECT 1 FROM t WHERE extract(nanosecond from value) % 1000 != 0 LIMIT 1`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6604)*

**Comment by mjibson** [comment]
Review status: 6 of 10 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/testdata/datetime, line 387 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6604#-KHfHSSPoFMyrXU5dKuG:-KHgzHcvjONCW3_Gg7TY:2101406442) ([raw file](https://github.com/cockroachdb/cockroach/blob/2285a66f8a317946a47d967c57f6af418a2433f9/sql/testdata/datetime#L387)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> You could do it in a testdata file with a table: `INSERT INTO t VALUES (now())`, repeated a few times, then `SELECT 1 FROM t WHERE extract(nanosecond from value) % 1000 != 0 LIMIT 1`</details>
Right!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6604)*

**Comment by jseldess** [comment]
Docs updated with https://github.com/cockroachdb/docs/pull/305

**Pull request merged**
