### PR TITLE
sql/parser: fix serialization for DInterval

### PR DESCRIPTION
**Pull request by RaduBerinde**
An interval is represented in SQL with syntax like `INTERVAL '5m'`. But when we
serialize `DInterval`s, they print out as just `5m`, which results in
invalid expressions.

This change fixes the serialization and provides a new function `ValueAsString`
which is used when casting to string (in that case we do want just the value as
a string).

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10712)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
@knz - I didn't change the representation, it's a bigger change (in terms of fixing tests) and I wasn't sure if there is consensus on which representation to use.  This serialization fix is needed in any case.

**Comment by RaduBerinde** [comment]
Hm, I think that when encoding to string in pgwire (`writeTextDatum`) we should use `ValueAsString`. Fixing.

**Comment by RaduBerinde** [comment]
Merged with @nvanbenschoten's change.

**Comment by knz** [comment]
Check this:
```
root@:26257> select '11 day'::interval;
+--------------------+
| '11 day'::INTERVAL |
+--------------------+
| 0m11d0ns           |
+--------------------+
(1 row)
root@:26257> select interval '0m11d0ns';
pq: could not parse '0m11d0ns' as type interval: time: unknown unit d in duration 0m11d0ns
```

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10712#-:-KWh_5N_xJ0ZM30WQlPE:bz7ghnb)*

**Comment by RaduBerinde** [comment]
This is an existing problem, right? My change shouldn't have affected that output

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10712#-:-KWha2E6AYlkoJwl34-w:bm3hqa5)*

**Comment by knz** [comment]
On 16-11-16 15:45, RaduBerinde wrote:
> This is an existing problem, right? My change shouldn't have affected
> that output
> 

Ok this is true. Then your change LGTM.

I'll fix the issue as part of  #10475.

-- 
Raphael 'kena' Poss

**Comment by RaduBerinde** [comment]
TFTR!

**Pull request merged**
