### PR TITLE
sql: compatibility blitz for pgadmin

### LINKED ISSUE #23299: sql: support coercing string literals to arrays
In PostgreSQL, the following statement works fine:

```
#  select '["a", {"b":1}]'::jsonb #- '{1,b}';
 ?column?  
-----------
 ["a", {}]
```

CockroachDB complains

```
> select '["a", {"b":1}]'::jsonb #- '{1,b}';
pq: unknown signature: json_remove_path(jsonb, string)
```

unless you specifically make the RHS an array:

```
> select '["a", {"b":1}]'::jsonb #- array['1', 'b'];
+------------------+
| json_remove_path |
+------------------+
| ["a", {}]        |
+------------------+
> select '["a", {"b":1}]'::jsonb #- '{1,b}'::text[];
+------------------+
| json_remove_path |
+------------------+
| ["a", {}]        |
+------------------+
```

We should support automatically coercing string literals to arrays. According to @justinj this isn't trivial.

/cc @knz

### LINKED ISSUE #24747: sql: support pg_matviews virtual table
An error pops up in Navicat when clicking materialized views:

```SELECT c.oid AS oid, v.matviewname AS mviewname, c.relacl AS acl, c.reloptions AS param, 
v.ispopulated AS ispopulated, v.matviewowner AS mviewowner, v.definition AS definition, obj_description(c.oid) AS comment, t.spcname AS tablespace, v.schemaname AS schemaname 
FROM pg_matviews AS v 
INNER JOIN pg_class AS c ON v.matviewname = c.relname 
LEFT JOIN pg_tablespace AS t ON v.tablespace = t.spcname 
WHERE v.schemaname = 'public' 
ORDER BY v.matviewname ASC```

I180409 21:51:12.531915 380 sql/conn_executor.go:1805  [n1,client=[::1]:56172,user=root] execution error: relation "pg_matviews" does not exist

We don’t support materialized views at this time.

### LINKED ISSUE #26378: sql: add pg_catalog.pg_default_acl
Note: this vtable is empty on pg by default.

PGAdmin issues the following query:

```sql
SELECT db.oid AS did,
       db.datname AS name,
       db.dattablespace AS spcoid,
       spcname,
       datallowconn,
       pg_encoding_to_char(encoding) AS encoding,
       pg_get_userbyid(datdba) AS datowner,
       datcollate,
       datctype,
       datconnlimit,
       has_database_privilege(db.oid, 'CREATE') AS cancreate,
       current_setting('default_tablespace') AS default_tablespace,
       descr.description AS comments,
       db.datistemplate AS is_template,
       (
         SELECT array_to_string(ARRAY (
          SELECT array_to_string(defaclacl::TEXT[], ', ')
          FROM pg_default_acl
          WHERE (defaclobjtype = 'r')
            AND (defaclnamespace = 0::OID)
         ), ', ')
        ) AS tblacl,
        (
          SELECT array_to_string(ARRAY (
            SELECT array_to_string(defaclacl::TEXT[], ', ')
            FROM pg_default_acl
            WHERE (defaclobjtype = 'S')
              AND (defaclnamespace = 0::OID)
          ), ', ')
        ) AS seqacl,
        (
          SELECT array_to_string(ARRAY (
            SELECT array_to_string(defaclacl::TEXT[], ', ')
            FROM pg_default_acl
            WHERE (defaclobjtype = 'f')
              AND (defaclnamespace = 0::OID)
          ), ', ')
        ) AS funcacl,
        (
          SELECT array_to_string(ARRAY (
            SELECT array_to_string(defaclacl::TEXT[], ', ')
            FROM pg_default_acl
            WHERE (defaclobjtype = 'T')
              AND (defaclnamespace = 0::OID)
          ), ', ')
        ) AS typeacl,
        (
          SELECT array_agg((provider || '=') || label)
          FROM pg_shseclabel AS sl1
          WHERE sl1.objoid = db.oid
        ) AS seclabels,
        array_to_string(datacl::TEXT[], ', ') AS acl
FROM pg_database AS db
LEFT JOIN pg_tablespace AS ta
  ON db.dattablespace = ta.oid
LEFT JOIN pg_shdescription AS descr
  ON ((db.oid = descr.objoid) AND (descr.classoid = 'pg_database'::REGCLASS))
WHERE db.oid > NULL::OID
ORDER BY datname
```

Details can be found here: https://www.postgresql.org/docs/current/static/catalog-pg-default-acl.html

### LINKED ISSUE #26389: sql: add pg_catalog.pg_shdepend
PGAdmin issues the following query:

```sql
  SELECT cl.relkind, 
         COALESCE(cin.nspname, cln.nspname) AS nspname, 
         COALESCE(ci.relname, cl.relname) AS relname, 
         cl.relname AS indname 
  FROM pg_class AS cl 
  JOIN pg_namespace AS cln 
    ON cl.relnamespace = cln.oid 
  LEFT JOIN pg_index AS ind 
    ON ind.indexrelid = cl.oid 
  LEFT JOIN pg_class AS ci 
    ON ind.indrelid = ci.oid 
  LEFT JOIN pg_namespace AS cin 
    ON ci.relnamespace = cin.oid 
  WHERE (cl.oid IN (
    SELECT objid 
    FROM pg_shdepend 
    WHERE refobjid = 2901009604::OID
  )) 
  AND (cl.oid > none::OID) 
UNION ALL 
  SELECT 'n', 
         NULL, 
         nspname, 
         NULL 
  FROM pg_namespace AS nsp 
  WHERE (nsp.oid IN (
    SELECT objid 
    FROM pg_shdepend 
    WHERE refobjid = 2901009604::OID
  )) 
  AND (nsp.oid > none::OID) 
UNION ALL 
  SELECT CASE WHEN typtype = 'd' 
           THEN 'd' 
           ELSE 'y' 
        END, 
        NULL, 
        typname, 
        NULL 
  FROM pg_type AS ty 
  WHERE (ty.oid IN (
    SELECT objid 
    FROM pg_shdepend 
    WHERE refobjid = 2901009604::OID
  )) 
  AND (ty.oid > none::OID) 
UNION ALL
  SELECT 'C', 
         NULL, 
         conname, 
         NULL 
  FROM pg_conversion AS co 
  WHERE (co.oid IN (
    SELECT objid 
    FROM pg_shdepend 
    WHERE refobjid = 2901009604::OID
  )) 
  AND (co.oid > none::OID) 
UNION ALL 
  SELECT CASE WHEN prorettype = 2279 
           THEN 'T' 
           ELSE 'p' 
        END, 
        NULL, 
        proname, 
        NULL 
  FROM pg_proc AS pr 
  WHERE (pr.oid IN (
    SELECT objid 
    FROM pg_shdepend 
    WHERE refobjid = 2901009604::OID
  )) 
  AND (pr.oid > none::OID) 
UNION ALL 
  SELECT 'o', 
         NULL, 
         (
           (
             (
               (oprname || '('::TEXT) 
                 || COALESCE(tl.typname, ''::TEXT)
             ) || CASE WHEN (tl.oid IS NOT NULL) AND (tr.oid IS NOT NULL) 
               THEN ','::TEXT END
           ) || COALESCE(tr.typname, ''::TEXT)
          ) || ')'::TEXT, 
          NULL 
  FROM pg_operator AS op 
  LEFT JOIN pg_type AS tl 
    ON tl.oid = op.oprleft 
  LEFT JOIN pg_type AS tr 
    ON tr.oid = op.oprright 
  WHERE (op.oid IN (
    SELECT objid 
    FROM pg_shdepend 
    WHERE refobjid = 2901009604::OID
  )) 
  AND (op.oid > none::OID) 
  ORDER BY 1, 2, 3
```

See https://www.postgresql.org/docs/current/static/catalog-pg-shdepend.html for details.

### LINKED ISSUE #26390: sql: add pg_conversion
PGAdmin issues the following query:

```sql
  SELECT cl.relkind, 
         COALESCE(cin.nspname, cln.nspname) AS nspname, 
         COALESCE(ci.relname, cl.relname) AS relname, 
         cl.relname AS indname 
  FROM pg_class AS cl 
  JOIN pg_namespace AS cln 
    ON cl.relnamespace = cln.oid 
  LEFT JOIN pg_index AS ind 
    ON ind.indexrelid = cl.oid 
  LEFT JOIN pg_class AS ci 
    ON ind.indrelid = ci.oid 
  LEFT JOIN pg_namespace AS cin 
    ON ci.relnamespace = cin.oid 
  WHERE (cl.oid IN (
    SELECT objid 
    FROM pg_shdepend 
    WHERE refobjid = 2901009604::OID
  )) 
  AND (cl.oid > none::OID) 
UNION ALL 
  SELECT 'n', 
         NULL, 
         nspname, 
         NULL 
  FROM pg_namespace AS nsp 
  WHERE (nsp.oid IN (
    SELECT objid 
    FROM pg_shdepend 
    WHERE refobjid = 2901009604::OID
  )) 
  AND (nsp.oid > none::OID) 
UNION ALL 
  SELECT CASE WHEN typtype = 'd' 
           THEN 'd' 
           ELSE 'y' 
        END, 
        NULL, 
        typname, 
        NULL 
  FROM pg_type AS ty 
  WHERE (ty.oid IN (
    SELECT objid 
    FROM pg_shdepend 
    WHERE refobjid = 2901009604::OID
  )) 
  AND (ty.oid > none::OID) 
UNION ALL
  SELECT 'C', 
         NULL, 
         conname, 
         NULL 
  FROM pg_conversion AS co 
  WHERE (co.oid IN (
    SELECT objid 
    FROM pg_shdepend 
    WHERE refobjid = 2901009604::OID
  )) 
  AND (co.oid > none::OID) 
UNION ALL 
  SELECT CASE WHEN prorettype = 2279 
           THEN 'T' 
           ELSE 'p' 
        END, 
        NULL, 
        proname, 
        NULL 
  FROM pg_proc AS pr 
  WHERE (pr.oid IN (
    SELECT objid 
    FROM pg_shdepend 
    WHERE refobjid = 2901009604::OID
  )) 
  AND (pr.oid > none::OID) 
UNION ALL 
  SELECT 'o', 
         NULL, 
         (
           (
             (
               (oprname || '('::TEXT) 
                 || COALESCE(tl.typname, ''::TEXT)
             ) || CASE WHEN (tl.oid IS NOT NULL) AND (tr.oid IS NOT NULL) 
               THEN ','::TEXT END
           ) || COALESCE(tr.typname, ''::TEXT)
          ) || ')'::TEXT, 
          NULL 
  FROM pg_operator AS op 
  LEFT JOIN pg_type AS tl 
    ON tl.oid = op.oprleft 
  LEFT JOIN pg_type AS tr 
    ON tr.oid = op.oprright 
  WHERE (op.oid IN (
    SELECT objid 
    FROM pg_shdepend 
    WHERE refobjid = 2901009604::OID
  )) 
  AND (op.oid > none::OID) 
  ORDER BY 1, 2, 3
```

See https://www.postgresql.org/docs/current/static/catalog-pg-conversion.html for details.

### LINKED ISSUE #33341: sql: auto array type cast from '{}' in column default definition for better pg compatibility
**Is your feature request related to a problem? Please describe.**
I'm using scala backend and https://github.com/slick/slick and https://github.com/tminglei/slick-pg, and I'm trying to use cockroach with them.

slick-pg generates sql like below with array column defaults.

```sql
create table test {
  foo text[] default '{}'
}
```

In postgres, that SQL works.

But in cockroach, `Error: pq: expected DEFAULT expression to have type string[], but ''{}'' has type string` occurs and sql should be fixed as below.

```sql
create table test {
  foo text[] default '{}'::text[]
}
```

**Describe the solution you'd like**
Automatically cast `'{}'` to its own column type.

**Describe alternatives you've considered**
Modify https://github.com/tminglei/slick-pg to generate sql with type cast like `::text[]`, but I think fixing in cockroach would be better in pg-compatibility.

**Additional context**

### LINKED ISSUE #37124: sql: support row_to_json
PGAdmin uses row_to_json underneath the hood (as obtained via vmodule=conn_executor=2 --logtostderr):

```
I190425 14:25:50.706016 2640 sql/conn_executor.go:1347  [n1,client=172.23.0.5:38720,user=root] execution error: unknown function: row_to_json()
```

https://www.postgresql.org/docs/9.5/functions-json.html

### PR DESCRIPTION
**Pull request by jordanlewis**
A bunch of small improvements to the catalog, new builtins, and a couple of typing improvements all in the name of making pgadmin work.

And it works okay now! Definitely still some flaws and unsupported things, but at least the default experience isn't completely broken anymore.

Closes #33341.
Closes #23299.
Closes #26389.
Closes #26378.
Closes #26390.
Closes #24747.
Closes #37124.
Updates #25213.

image

### CODE REVIEW

**Comment by awoods187** [comment]
Awesome! This is really great stuff!

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38869#-:-LjpiFwi-rufhShpzYZI:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/opt/optbuilder/union.go, line 34 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/38869#-Ljpi3XU0CdBFXs6d3Ye:-Ljpi3XU0CdBFXs6d3Yf:b-gaa1zo) ([raw file](https://github.com/cockroachdb/cockroach/blob/edaa7b85bdc6c4ed68316660ece9f40d639853f5/pkg/sql/opt/optbuilder/union.go#L34)):*
> ```Go
> 	// Try to propagate types left-to-right, if we didn't already have desired
> 	// types.
> 	if len(desiredTypes) == 0 {
> ```

Please add a new test for this in  `optbuilder/testdata/union`
___
*[pkg/sql/sem/builtins/builtins.go, line 2246 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/38869#-Ljphn0--0TxDvIA1Zs4:-Ljphn0--0TxDvIA1Zs5:b9lyk2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f89ff624f6dc71034cc7cdfbadedb0731b8a32d/pkg/sql/sem/builtins/builtins.go#L2246)):*
> ```Go
> 	),
> 
> 	"row_to_json": makeBuiltin(defProps(),
> ```

Can you add a logic test for this function?

**Review by andy-kimball — COMMENTED** [review]
Amazing work, Jordan. This gives further evidence that there's a lot of low-hanging compatibility fruit across various drivers/tools that dedicated engineer(s) could pluck.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38869#-:-Ljq5H8N4AimZvrQgcg6:bv7xatr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Review by jordanlewis — COMMENTED** [review]
Main questionable thing about this is that our type system is a little bit different than Postgres, so when we added the constant upcast path from string to string array, it causes a bad error message to be created for something like

`SELECT array['foo'] || bar`. Postgres also errors on this if you don't specify `bar::text`. But we produce something like `no valid overload from string[] || string`, which is a lie. The reason it produces this is that our typing rules apply in a particular order - we end up filtering out the string[]||string overload early in the case of not knowing the second string's type (it's a constant) because of this rule where we try to type constants homogeneously with resolved types, and throw away the ones that didn't match that. Then, we reject string[]||string[] because the second string can't resolve to a string[] as it doesn't parse to one.

I think the solution would be to change the homogeneous rule to prefer homogeneous but not rule out non-homogeneous, but I think that would be pretty invasive. I'm tempted to leave this bad error message for now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38869#-:-Ljv99dpCxJuad_-1KUS:b7kw6q7)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/optbuilder/union.go, line 34 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/38869#-Ljpi3XU0CdBFXs6d3Ye:-Ljv95am6t6xE03V3SG9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/edaa7b85bdc6c4ed68316660ece9f40d639853f5/pkg/sql/opt/optbuilder/union.go#L34)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Please add a new test for this in  `optbuilder/testdata/union`
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/builtins.go, line 2246 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/38869#-Ljphn0--0TxDvIA1Zs4:-Ljv96ZNBC2hLTiLEk77:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f89ff624f6dc71034cc7cdfbadedb0731b8a32d/pkg/sql/sem/builtins/builtins.go#L2246)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Can you add a logic test for this function?
</blockquote></details>

Done.

**Comment by jordanlewis** [comment]
@RaduBerinde feeling good about your stamp here? I'm ready to merge this.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38869#-:-Lk9fpPD-UkoAdfceyTH:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by jordanlewis** [comment]
Thanks a lot for reviewing this!

bors r+

**Pull request merged**
