### PR TITLE
lint: delete previously skipped Misspell

### PR DESCRIPTION
**Pull request by tbg**
As requested by @andreimatei and supported by @nvanbenschoten (and
myself too):

https://github.com/cockroachdb/cockroach/pull/73638#issuecomment-991331443

Release note: None

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
:lgtm: but please say in the commit messages that this deletes a linter that was already skipped

I think deleting is better than skipping, but I'm slightly against not running this linter. It does find stuff for me on occasion. A lot the time it has to do with the number of 'l' in variations of "marshal"/"cancel". But every now and then it's something better. You seem to want to delete it because it causes extra CI runs. How about instead of not running it, we elevate it to `make listshort` instead, so more people get the errors earlier?
I've been however training myself to not correct spelling errors when I see them in other's committed code, so I guess I should also care less about my own spelling... so I don't have strong feelings either way.

There's also a matter of deciding how a change like this gets made. I think a thumbs up/down vote on the slack eng channel would be good, so that it's not two people alone acting unilaterally on eng-wide things.
One thing that's fresh in my mind is the people, with @jordanlewis among them, did not seem willing to discourage typo fixes PR in the recent typocalipyse mega-PR. So perhaps he'll have something to say here too.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73733#-:-MqoHtX48Z3RTspKZVZ-:b-ek372b)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker)

**Review by rickystewart — CHANGES_REQUESTED** [review]
Can you make the corresponding change for Bazel, too?

```
diff --git a/build/bazelutil/lint.bzl b/build/bazelutil/lint.bzl
index f43ef7c211..549f485b9c 100644
--- a/build/bazelutil/lint.bzl
+++ b/build/bazelutil/lint.bzl
@@ -48,7 +48,6 @@ def lint_binary(name, test):
         data = [
             test,
             "//pkg/sql/opt/optgen/cmd/optfmt",
-            "@com_github_client9_misspell//cmd/misspell:misspell",
             "@com_github_cockroachdb_crlfmt//:crlfmt",
             "@go_sdk//:bin/go",
             "@org_golang_x_lint//golint:golint",
diff --git a/build/bazelutil/lint.sh.in b/build/bazelutil/lint.sh.in
index 6708eeb588..3e2c723a94 100644
--- a/build/bazelutil/lint.sh.in
+++ b/build/bazelutil/lint.sh.in
@@ -29,7 +29,6 @@ test_bin="$(rlocation_ck cockroach/$PACKAGE/${NAME}_/$NAME)"
 go_bin="$(rlocation_ck go_sdk/bin/go)"
 crlfmt_bin="$(rlocation_ck com_github_cockroachdb_crlfmt/crlfmt_/crlfmt)"
 golint_bin="$(rlocation_ck org_golang_x_lint/golint/golint_/golint)"
-misspell_bin="$(rlocation_ck com_github_client9_misspell/cmd/misspell/misspell_/misspell)"
 optfmt_bin="$(rlocation_ck cockroach/pkg/sql/opt/optgen/cmd/optfmt/optfmt_/optfmt)"
 
 # Need to run this so that Go can find the runfiles.
@@ -43,6 +42,6 @@ fi
 cd "$BUILD_WORKSPACE_DIRECTORY/$PACKAGE"
 
 TEST_WORKSPACE=cockroach \
-    PATH="$(dirname $go_bin):$(dirname $crlfmt_bin):$(dirname $misspell_bin):$(dirname $golint_bin):$(dirname $optfmt_bin):$PATH" \
+    PATH="$(dirname $go_bin):$(dirname $crlfmt_bin):$(dirname $golint_bin):$(dirname $optfmt_bin):$PATH" \
     GOROOT="$(dirname $(dirname $go_bin))" \
     "$test_bin" "$@"

```

**Comment by tbg** [comment]
TFTRs, made both changes and will merge on green.

> There's also a matter of deciding how a change like this gets made.

That's an interesting question, but asking for too many opinions is asking for death by committee. If to make any trivial change one has to go through a time consuming process, we have a problem. In my opinion some combination of dev-inf and test-eng owns the lints and they are supposed to represent what is good for the Eng org as a whole. This may not always work but I would still expect that, on average, it is more efficient to have to walk back the occasional contentious change rather than getting bogged down 100% of the time.

I am a bit of a typo fanatic myself but if I take a step back from my mild OCD I think it is rather pointless unless the cost for fixing a typo is marginally zero. That is emphatically not true today.

**Comment by andreimatei** [comment]
>  How about instead of not running it, we elevate it to make listshort instead, so more people get the errors earlier?

You haven't expressed an opinion on this. I think this is a good option, particularly if we also take the opportunity to add a few more exempt words to the linter.

> That's an interesting question, but asking for too many opinions is asking for death by committee. If to make any trivial change one has to go through a time consuming process, we have a problem. In my opinion some combination of dev-inf and test-eng owns the lints and they are supposed to represent what is good for the Eng org as a whole. This may not always work but I would still expect that, on average, it is more efficient to have to walk back the occasional contentious change rather than getting bogged down 100% of the time.

This linter is an example of a thing that doesn't require any particular expertise. Everybody can have an equally informed opinion on it. So I don't know if dev-inf or test-eng should necessarily decide here more than anyone else. As I was saying, I personally still am marginally against removing this linter; it has been useful for me (*). Why does your opinion matter more than mine? One reason would be if you have a strong preference. Still, taking the temperature more I think is fair.
There are degrees of involving the community between zero and "death by committee". I think a survey with two or three options is a good one (lintshort vs delete would be the two rational options). Have people vote, and then act accordingly. If people put new options in the chat, you can consider them  and discard them if you want. It would still be better than not asking any question at all.

(*) Before you re-raise the point that I can enable it for myself only in some way, I don't think that works because the linter is not smart enough to only check a diff. Either the code-base is 100% clean, or it's unusable (I think).

**Review by irfansharif — APPROVED** [review]
Your [commonwealth friends](https://cockroachlabs.slack.com/archives/C0185G7QN14/p1611255757011800) thank you. I also prefer the outright deletion to just lifting it to lintshort (which this author is too impatient to ever use). I'd be surprised if anyone will miss needing an extra 50m CI run cause they spelled "behaviour".

**Review by rickystewart — APPROVED** [review]

**Comment by tbg** [comment]
> You haven't expressed an opinion on this. I think this is a good option, particularly if we also take the opportunity to add a few more exempt words to the linter.

I think this linter is a clear case of something that provides negative benefit, so personally the more rid of it we get the better and I would set my bar at "I don't ever have to think of this linter again". I'm okay with anything we do that clears that bar but not personally invested into it, for obvious reasons.

> Why does your opinion matter more than mine?

I hope that's not how this is coming across. My argument is that while this linter may be providing a modest benefit to you, it is also an externality on the engineering org as a whole and I am proposing we remove it on those grounds. I'd be surprised 
I'm not trying to take the linter away from you personally and won't stand in the way of someone returning the linter to the codebase in a way that is strictly opt-in. However, this is not something I will be spending my time on.

bors r=irfansharif,rickystewart

**Pull request merged**
