### PR TITLE
storage: Use single timer in replicaScanner between waitAndProcess calls

### PR DESCRIPTION
**Pull request by nvb**
Before this change, about a third (**32.54%**) of our total allocations
were spent on the `time.After` call in `replicaScanner.waitAndProcess`.
This change uses our custom properly resettable timer to store a single
timer on the replicaScanner struct, and use this timer for all pacing. Now,
a single timer for the replicaScanner is allocated per Store.

web

---

This change is [Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5091)

### CODE REVIEW

**Comment by vivekmenezes** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/scanner.go, line 240 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5091#-KCWM26SLuKpt8fLoIYV:-KCWM26T0FEMoNP1mBuT:470460476) ([raw file](https://github.com/cockroachdb/cockroach/blob/fed3fdd4eadad222c337ac758a7b79eee4210a2d/storage/scanner.go#L240)):*
any reason not to use defer 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5091)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/scanner.go, line 240 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5091#-KCWM26SLuKpt8fLoIYV:-KCWNEkZzMDQOzQhRKPV:1499490856) ([raw file](https://github.com/cockroachdb/cockroach/blob/fed3fdd4eadad222c337ac758a7b79eee4210a2d/storage/scanner.go#L240)):*
Nope, good call. Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5091)*

**Comment by vivekmenezes** [comment]
LGTM

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5091#-:-KCWOgG0jepgeAYM5bGl:676834233)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5091#-:-KCWucnPGAtVZMLi9wfr:1417088721)*

**Pull request merged**
