### PR TITLE
ui: include SERIALIZATION_CONFLICT events in txn contention details

### LINKED ISSUE #111650: ui: link insights with 40001 error and conflicting txn id to the conflicting txn fingerprint
Follow up to https://github.com/cockroachdb/cockroach/issues/111649.

Once the above is addressed we can query the transaction_contention_events table in the UI to correlate any insights with 40001 failure codes with conflicting txn id to the conflicting txn fingerprint. 

Jira issue: CRDB-32006

### PR DESCRIPTION
**Pull request by xinhaoz**
### Note that only the last commit is part of this review.

This commit introduces `SERIALIZATION_CONFLICT` contention event details to
the txn insights details page. If a transaction insight failed with a
40001 error code, we will query `crdb_internal.transaction_contention_events`
to see if there is any serialization conflict event containing the blocking
txn exec id, fingerprint id and conflict location information.

A section called `Failed Execution` will appear when this information is
available with the following info:
- blocking txn execution id
- blocking txn finggerprint id
- conflict location - db, table and index names

Epic: none
Closes: https://github.com/cockroachdb/cockroach/issues/111650

Release note (ui change): Txn insight details will show the following details
when we have information on a txn execution with a 40001 error code and we
have captured the conflicting txn meta (only available if the txn had not yet
committed at the time of execution).
A section called `Failed Execution` will appear when this information is
available with the following info:
- blocking txn execution id
- blocking txn finggerprint id
- conflict location - db, table and index names

https://www.loom.com/share/0958b52282404049862a26fc9d84416c

### CODE REVIEW

**Comment by xinhaoz** [comment]
The build will fail for now because these changes rely on - https://github.com/cockroachdb/cockroach/pull/111685

**Review by maryliag — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111873)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/failedInsightDetailsPanel.tsx` line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111873#-Ng0sfYc4ulXRBGSV-lG:-Ng0sfYc4ulXRBGSV-lH:b-i5iy0p) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd72725caac9094dde0fb73bedd5f5a4d4e145d9/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/failedInsightDetailsPanel.tsx#L32)):*
> ```XML
> };
> 
> const FailedInsightDetailsPanelLabels = {
> ```

curious: why the need of this variables if you only use in one place? We don't do that for any of the other label on summary cards
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/transactionInsightDetailsOverviewTab.tsx` line 120 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111873#-Ng0svfj4d1pifyWtkjF:-Ng0svfj4d1pifyWtkjG:b-dslncb) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd72725caac9094dde0fb73bedd5f5a4d4e145d9/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/transactionInsightDetailsOverviewTab.tsx#L120)):*
> ```XML
>     });
> 
>   // We only expect up to 1 serialization conflict.
> ```

is that because only one can happen or because we only store info up to one?

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111873)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/failedInsightDetailsPanel.tsx` line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111873#-Ng0sfYc4ulXRBGSV-lG:-Ng4NeHD1BuP-si4Dx0i:b7kwmbg) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd72725caac9094dde0fb73bedd5f5a4d4e145d9/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/failedInsightDetailsPanel.tsx#L32)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

curious: why the need of this variables if you only use in one place? We don't do that for any of the other label on summary cards
</blockquote></details>

Just for organization and colocation of the text on the page.  Personally I'm not a big fan of writing the strings directly inline with a component since it can get broken up and etc. and makes it harder to test / validate all the text in a component.
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/transactionInsightDetailsOverviewTab.tsx` line 120 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111873#-Ng0svfj4d1pifyWtkjF:-Ng4NbJYBVMCnTzG0b0r:b-4ub9au) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd72725caac9094dde0fb73bedd5f5a4d4e145d9/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/transactionInsightDetailsOverviewTab.tsx#L120)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

is that because only one can happen or because we only store info up to one?
</blockquote></details>

Yes that's right, I updated the comment to include that!

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111873#-:-Ng5HLY5B-yqLl8hon4j:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

**Pull request merged**
