### PR TITLE
sql: Fix bug preventing usage of hard/soft limits

### PR DESCRIPTION
**Pull request by a-robinson**
It looks like this got broken by 31fc76d6a4c4de92542a37f4e67ee18e5d361135

@andreimatei @knz @RaduBerinde 

Fixes https://github.com/cockroachdb/cockroach/issues/13935, although there's still a factor of two difference between the forward and reverse scans. The ledger example gets 30-40 transactions/sec when using reverse scans, and 80-90 when using forward scans (as in https://github.com/cockroachdb/examples-go/pull/99).

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14182)

### CODE REVIEW

**Comment by knz** [comment]
LGTM, but please 1) add a test 2) check if that also fixes #13892

**Comment by RaduBerinde** [comment]
Oops, sorry about that, LGTM. I agree we should have a test, though I don't have any immediate ideas on how to write one..

**Comment by a-robinson** [comment]
I'll see what I can do about a test, but no promises before looking at it a little more closely.

@knz, how would you suggest I verify whether this fixes #13892? It doesn't have very concrete repro steps about what data to load into the table.

**Comment by knz** [comment]
Please drop the reference to #13892: I was confusing it with some other earlier issue which has been fixed since.

**Comment by a-robinson** [comment]
Added a simple test, PTAL.

**Comment by knz** [comment]
Nice, thanks. LGTM

**Pull request merged**
