### PR TITLE
ui: rename "active" execution types and functions to "recent"

### PR DESCRIPTION
**Pull request by amyyq2**
This change renames the active execution types and functions to "recent" types and functions. This is in preparation for the addition of recent executions to the current active executions table.

The file names will be changed in a later PR.

Release note: None

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
Thank you for doing this refactor!
you should also rename the files, to align with their new names

> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91860#-:-NGrlVGM4HKAUISz4x8I:bugqlu8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @amyyq2)

___
*[`pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPageRoot.tsx` line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91860#-NGrlH3xD6mPTtN486lt:-NGrlH3xD6mPTtN486lu:b-i4g98z) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24b197c5c7955ff6be3d8d92976b4ce851693c9/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPageRoot.tsx#L56)):*
> ```XML
>         <span>
>           Recent executions represent individual statement executions in
>           progress or recently completed, timed out, or canceled.
> ```

nit: only add this part on your commit, because this is not yet the case

**Review by amyyq2 — COMMENTED** [review]
Sounds good!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91860#-:-NGrzSuE0sDHj-Y71OXY:brxp9sd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPageRoot.tsx` line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91860#-NGrlH3xD6mPTtN486lt:-NGrzWvwARZYd4gGE3oL:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24b197c5c7955ff6be3d8d92976b4ce851693c9/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPageRoot.tsx#L56)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: only add this part on your commit, because this is not yet the case
</blockquote></details>

Done

**Review by xinhaoz — APPROVED** [review]
Nice! Clean rename 👍

**Review by amyyq2 — COMMENTED** [review]
TFTR! Added another commit for refactoring in db-console, so would appreciate another look :smiley: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91860#-:-NH0Vq7E96vuYuuhso-p:b-80r85u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 34 of 37 files at r2, 4 of 4 files at r3, 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91860#-:-NH1R_sc0w-OaTiR-1CW:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @amyyq2)

**Pull request merged**
