### PR TITLE
cherrypick: parser: parse collation locales properly

### PR DESCRIPTION
**Pull request by mberhault**
Previously, the parser introduced unwanted quotes for locales that are
not normalized identifiers. BCP 47 locales do not contain dots (`.`), so
the switch from `any_name` to `unrestricted_name` will not affect any
valid SQL statements.

### CODE REVIEW

**Comment by eisenstatdavid** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15917#-:-KkBNwClj9F5oVswqPXV:bnfp4nl)*

**Comment by mberhault** [comment]
CC: @cockroachdb/release

**Comment by bdarnell** [comment]
What problem does this solve? It seems low-risk enough but there's no issue linked in the original PR and the commit message doesn't seem to describe anything too serious.

**Comment by eisenstatdavid** [comment]
Locales with uppercase letters did not work because our parser would quote them on the way in, and then language.Tag parser would barf on the quotes. I can make a retroactive issue if you wish.

**Comment by bdarnell** [comment]
OK. No need for a retroactive issue.

**Comment by mberhault** [comment]
This is failing with:
```
parse_test.go:686: expected CREATE TABLE a (b STRING COLLATE "DE"), but found CREATE TABLE a (b STRING COLLATE DE)
parse_test.go:686: expected SELECT 'Deutsch' COLLATE "DE", but found SELECT 'Deutsch' COLLATE DE
```

**Comment by eisenstatdavid** [comment]
We need 18b308837101b4fec82d2e8bb717c730d6cd8c53 too then.

**Comment by mberhault** [comment]
oh great. That commit is part of a 4-commit PR covering 23 files: https://github.com/cockroachdb/cockroach/pull/15817/commits

**Comment by eisenstatdavid** [comment]
That one commit is standalone. Don't take the others.

**Comment by mberhault** [comment]
Sure, but there's a broader question about individual commits. It's generally preferable to grab an entire PR, or things may get odd later (and definitely harder to track).
@bdarnell: thoughts?

**Comment by bdarnell** [comment]
In general I prefer to take a PR at a time because we don't have as much testing of the individual commits under a PR. But in this case when it's a choice between a 2-line change and a bunch of PRs covering 23 files I think it makes more sense to just take the commit.

**Comment by mberhault** [comment]
Done. Rebased and running again.

**Review by bdarnell — APPROVED** [review]

**Comment by jseldess** [comment]
@eisenstatdavid, @bdarnell, should this be listed as a known limitation in the docs, pre 1.0.1?

**Comment by eisenstatdavid** [comment]
Borderline? It only causes problems if you quote a non-lowercase locale name, which seems like an edge case to me.

**Comment by jseldess** [comment]
Hmm, given that there are some prominent locals with uppercase letters [here]https://godoc.org/golang.org/x/text/language#Tag), seems harmless to me to list it as a limitation pre-1.0.1, especially since we've fixed it. You ok with that?

**Comment by eisenstatdavid** [comment]
Sure.

**Pull request merged**
