### PR TITLE
log: replace ErrEventf family with VErrEventf family

### PR DESCRIPTION
**Pull request by nvb**
This change replaces the ErrEventf family of functions with a new
VErrEventf family of functions. The functions all take a verbosity
level which, if exceeded, causes the function to log the provided
message in addition to adding it as a trace event. This mirrors the
exiting VEventf family of functions.

The reasoning behind getting rid of ErrEvent entirely is that errors
are often the most interesting logs when debugging, so at a high enough
verbosity level they should always be available. Unfortunately, the
ErrEvent functions made it look like errors were more accessible than
they actually were, which resulted in almost no errors ever being logged
across our system, even at the highest verbosity levels. This has proven
to be a major inconvenience when debugging issues that involve exotic
error behavior. Because of this, the ErrEvent functions don't make sense
to have.

### CODE REVIEW

**Comment by knz** [comment]
This is brilliant work.
You're sneaking a bug fix in here, and that needs more attention / more verbosity in the commit message.

Also I think the last commit deserves a release note, to inform the user that your change may cause more error messages to become visible in log files, but that is not to be a cause of concern ("the errors were happening already, but at least now we know they were" or something like that).

---

Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 12 of 12 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/kv/dist_sender.go, line 465 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22919#-L5xOVIg47oUHbim5YTe:-L5xOVIg47oUHbim5YTf:b-jh56jy) ([raw file](https://github.com/cockroachdb/cockroach/blob/a942dd8d2963909a2ad1f86c583b83d14b2a6c2c/pkg/kv/dist_sender.go#L465)):*
> ```Go
> 	br, err := ds.sendRPC(ctx, desc.RangeID, replicas, ba)
> 	if err != nil {
> 		log.VErrEvent(ctx, 2, err.Error())
> ```

How have you chosen the levels here and below? Was there any logic to picking 2 vs 1? If so, mention it briefly in the commit message.

---

*[pkg/kv/range_cache.go, line 418 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22919#-L5xN3LTcIOVbZ1TRczV:-L5xN3LUZZ7jyTcAGi-z:b-f8s7s8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a977bdf527d3ff13c58dd6de0540819c524d9794/pkg/kv/range_cache.go#L418)):*
> ```Go
> ) ([]roachpb.RangeDescriptor, []roachpb.RangeDescriptor, error) {
> 	// Tag inner operations.
> 	ctx = log.WithLogTagStr(ctx, "range-lookup", key.String())
> ```

Oy, here and elsewhere (and everywhere, really), this is paying the cost of stringification upfront even when logging is not enabled. Is that desirable?
I would recommend a log tag binding that keeps the given object/reference as-is and only stringifies when the tag is stringified in a log message (perhaps with some memoization).

---

*[pkg/storage/consistency_queue.go, line 78 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22919#-L5xOFHkmicZ42C9xdbv:-L5xOFHkmicZ42C9xdbw:b9rom2u) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b1572d2142f09f6ed3cc0dcf66aab5cd4966374/pkg/storage/consistency_queue.go#L78)):*
> ```Go
> 		lpTS, err := repl.getQueueLastProcessed(ctx, q.name)
> 		if err != nil {
> 			return false, 0
> ```

Wow is that a bug fix? Looks like one. In that case, can you extend the commit message to explain the problems caused by not fixing this?
May want a cherry-pick into 2.0 too.

---

*[pkg/storage/ts_maintenance_queue.go, line 112 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22919#-L5xOOQVEN58ECPe-jVU:-L5xOOQWDMaSDH2QOfCr:b-eyl074) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b1572d2142f09f6ed3cc0dcf66aab5cd4966374/pkg/storage/ts_maintenance_queue.go#L112)):*
> ```Go
> 		lpTS, err := repl.getQueueLastProcessed(ctx, q.name)
> 		if err != nil {
> 			return false, 0
> ```

ditto commit msg & cherry-pick.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22919#-:-L5xOgrXGU4sFatnMkoQ:b8lcxoa)*

**Comment by nvanbenschoten** [comment]
Thanks for the good critiques about the release notes! I do plan to cherry-pick this entire change into 2.0.

---

Review status: 0 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/kv/dist_sender.go, line 465 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22919#-L5xOVIg47oUHbim5YTe:-L6IZyKzJEf2d7ZLZaba:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a942dd8d2963909a2ad1f86c583b83d14b2a6c2c/pkg/kv/dist_sender.go#L465)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

How have you chosen the levels here and below? Was there any logic to picking 2 vs 1? If so, mention it briefly in the commit message.
</blockquote></details>

Done.

---

*[pkg/kv/range_cache.go, line 418 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22919#-L5xN3LTcIOVbZ1TRczV:-L6IX_b9SH448uj5Cq0O:b3elndo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a977bdf527d3ff13c58dd6de0540819c524d9794/pkg/kv/range_cache.go#L418)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Oy, here and elsewhere (and everywhere, really), this is paying the cost of stringification upfront even when logging is not enabled. Is that desirable?
I would recommend a log tag binding that keeps the given object/reference as-is and only stringifies when the tag is stringified in a log message (perhaps with some memoization).
</blockquote></details>

Good point, replaced with `WithLogTag` to avoid the eager stringification. Do note though that this code is far from the hot path.

---

*[pkg/storage/consistency_queue.go, line 78 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22919#-L5xOFHkmicZ42C9xdbv:-L6IZ2z-4JCCdDsp1eEJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b1572d2142f09f6ed3cc0dcf66aab5cd4966374/pkg/storage/consistency_queue.go#L78)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Wow is that a bug fix? Looks like one. In that case, can you extend the commit message to explain the problems caused by not fixing this?
May want a cherry-pick into 2.0 too.
</blockquote></details>

Done.

---

*[pkg/storage/ts_maintenance_queue.go, line 112 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22919#-L5xOOQVEN58ECPe-jVU:-L6IYIDh4zUj5GEEeKsz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b1572d2142f09f6ed3cc0dcf66aab5cd4966374/pkg/storage/ts_maintenance_queue.go#L112)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto commit msg & cherry-pick.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22919#-:-L6I_ItqiP_Ztz090kbH:bdx407n)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 1 of 13 files at r4, 12 of 12 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22919#-:-L6J974oyC78pEs8IN7n:bnfp4nl)*

**Comment by nvanbenschoten** [comment]
TFTR!

**Pull request merged**
