### PR TITLE
schemachanger: prettier EXPLAIN (DDL) output

### LINKED ISSUE #104043: schemachanger: names in EXPLAIN (DDL) output instead of IDs
The output of EXPLAIN (DDL) and its variants is human-readable but its target audience is, admittedly, CRDB contributors, rather than cluster operators. As it is, there's no hope of the latter making much sense of it because it's peppered with table, index and column IDs. Relying on IDs is also not very useful for contributors (whose use-case is testing) because as soon as a schema change involves two tables it quickly becomes very confusing.

Let's decorate the output with names instead.

Epic: CRDB-27601

Jira issue: CRDB-28332

### PR DESCRIPTION
**Pull request by postamar**
This commit adds ID -> name mappings to the scpb.TargetState which lies at the heart of the declarative schema changer, these mappings are then used (when present) to decorate the output of EXPLAIN (DDL) in an effort to make it more understandable.

This commit also adds support for the SHAPE flag in conjunction with EXPLAIN (DDL). The generated output informs on expensive operations such as backfills or validations.

Fixes #104043.

Release note (sql change): EXPLAIN (DDL) statements now have descriptor, index, column, constraint and other ID values decorated with names when available. There is now also a new EXPLAIN (DDL, SHAPE) statement which provides information on costly operations planned by the declarative schema changer, like which index backfills and validations will get performed.

### CODE REVIEW

**Review by Xiang-Gu — COMMENTED** [review]
Thanks for doing this; this is super valuable! I don't have any opposition of the technical solution. I have some questions on the wordings of the explain output and a few minor questions/comments.

1. Why do you want to call this new flag "SHAPE"? I didn't immediately see the meaning.
2. Do we want to make "explain_shape" directory work similarly to "explain" and "explain_verbose"? That is, for every tested statement in an end-to-end test, we have one file for it under the "explain_shape" directory. Furthermore, when we run the TestEndToEnd_xxx test with a "rewrite" flag, the corresponding file under "explain_shape" gets rewritten (just as the file under "explain" and "explain_verbose")

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103930#-:-NWNHq7X58UQzU5L2n-i:b-3fjwca)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

___
*[`pkg/sql/schemachanger/scbuild/build.go` line 324 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103930#-NWNQ9Wx8iiE5vgDzYQc:-NWNQ9Wx8iiE5vgDzYQd:buavjkh) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef449b9df7b35acdd18249901ef420e2794af40/pkg/sql/schemachanger/scbuild/build.go#L324)):*
> ```Go
> 	scpb.ForEachNamespace(b, func(_ scpb.Status, ts scpb.TargetStatus, e *scpb.Namespace) {
> 		dnm, isNew := getOrCreate(e.DescriptorID)
> 		if isNew || ts == scpb.InvalidTarget || ts == scpb.ToPublic {
> ```

why do we want the `ts==scpb.InvalidTarget` filter?
___
*[`pkg/sql/schemachanger/scpb/name_mappings.go` line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103930#-NWNSEYM2bv0ZZUih7Ti:-NWNRCVyEvUgwTm2_h7Q:b7l24dy) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef449b9df7b35acdd18249901ef420e2794af40/pkg/sql/schemachanger/scpb/name_mappings.go#L132)):*
> ```Go
> 		return name
> 	}
> 	return NameMappings(ts.NameMappings).ConstraintName(relationID, constraintID)
> ```

Did I understand this correctly: the purpose of the last return clause is for cases where certain name-related elements are needed but not involved in the plan (ts.Target); For example, altering a table won't touch the parent database but we probably want to know its parent database name, which will be stored in the builder state as an element with InvalidTargetStatus by the decomp logic.
___
*[`pkg/sql/schemachanger/scplan/plan_explain.go` line 205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103930#-NWNJKyYAp05kAit1UN7:-NWNJKyYAp05kAit1UN8:bk1vhfe) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef449b9df7b35acdd18249901ef420e2794af40/pkg/sql/schemachanger/scplan/plan_explain.go#L205)):*
> ```Go
> 			var en treeprinter.Node
> 			var estimatedMemAlloc int
> 			accountFor := func(label string) string {
> ```

I saw this `accountFor` helper is defined multiple times. Will it be better to make it a function `func accountFor(label string, memAcc *int) string` and define it once?
___
*[`pkg/sql/schemachanger/scplan/plan_explain.go` line 377 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103930#-NWNJhw1-1uIsFT1eE35:-NWNJhw1-1uIsFT1eE36:bd07nwg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef449b9df7b35acdd18249901ef420e2794af40/pkg/sql/schemachanger/scplan/plan_explain.go#L377)):*
> ```Go
> 
> // ExplainShape returns a human-readable plan rendering for
> // EXPLAIN (DDL, SHAPE) statements.
> ```

Can you add a bit more comments here about the main purpose of this new EXPLAIN flag? something like "it gives a condensed summary of the operations involved in the schema change with highlights on expensive operations (backfill, validation, etc.), which helps users understand where most of the time will be spent if the schema change is to be executed."
___
*[`pkg/sql/schemachanger/scplan/plan_explain.go` line 446 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103930#-NWNLaen1RH6_mnw4OQW:-NWNLaen1RH6_mnw4OQX:b8hbcym) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef449b9df7b35acdd18249901ef420e2794af40/pkg/sql/schemachanger/scplan/plan_explain.go#L446)):*
> ```Go
> 
> func (p Plan) explainBackfillsAndMerges(root treeprinter.Node, ops []scop.Op) error {
> 	gbs, gms := groupBackfillsAndMerges(ops)
> ```

Are we respecting the real ordering of the backfill and merges if the plan involves >1 backfills and merges?

IIUC, backfill and merge always appears in pairs. If we have a plan where the real ordering of the operations are
1. backfill_1
2. merge_1
3. backfill_2
4. merge_2

Will the logic print out operations in that order? Or, will it be all backfills first and then all merges (i.e. backfill_1 followed by backfill_2 followed by merge_1 followed by merge_2)?
___
*[`pkg/sql/schemachanger/scplan/plan_explain.go` line 596 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103930#-NWNMfsu4QrB4_DhbYe3:-NWNMfsu4QrB4_DhbYe4:b-eoh88p) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef449b9df7b35acdd18249901ef420e2794af40/pkg/sql/schemachanger/scplan/plan_explain.go#L596)):*
> ```Go
> 	sort.Slice(gbs, func(i, j int) bool {
> 		if gbs[i].relationID == gbs[j].relationID {
> 			return gbs[i].srcIndexID < gbs[j].srcIndexID
> ```

I have a gut feeling that this might not work properly, because it's possible that we have three backfill/merge groups:
```index_a <-- index_b <-- index_c <-- index_d```
where we backfill `index_b` from `index_a`, backfill `index_c` from `index_b`, and so on.

It's possible, depending on the implementation, that `index_b.GetID()` is bigger than `index_c.GetID()` (do you remember in my support-add-drop-column-alterPK PR we inflate this chain, de-duplicate, and re-inflate again for the next ALTER TABLE stmt, and so on. I think this makes what I described here possible)

In my PR, I need to do similar things to order the primary indexes and I had logic there to sort by the _location_ of srcIndex (i.e. if 'B.srcIdx = A', then A comes before B in the ordering)
___
*[`pkg/ccl/schemachangerccl/testdata/explain/create_index` line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103930#-NWNEeiI79qJ-TODQ1n3:-NWNEeiI79qJ-TODQ1n4:b6wfolv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef449b9df7b35acdd18249901ef420e2794af40/pkg/ccl/schemachangerccl/testdata/explain/create_index#L14)):*
> ```
>  │    └── Stage 1 of 1 in StatementPhase
>  │         ├── 7 elements transitioning toward PUBLIC
>  │         │    ├── ABSENT → BACKFILL_ONLY    SecondaryIndex:{DescID 104 "t1", IndexID 2 "+id1", TemporaryIndexID 3, SourceIndexID 1 "t1_pkey"}
> ```

what is this "+id1" name for IndexID 2? Saw a bunch of them
___
*[`pkg/ccl/schemachangerccl/testdata/explain_shape/create_index` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103930#-NWNFPBPDVRXSSZrQRh8:-NWNFPBPDVRXSSZrQRh9:b55c6tm) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef449b9df7b35acdd18249901ef420e2794af40/pkg/ccl/schemachangerccl/testdata/explain_shape/create_index#L13)):*
> ```
>  ├── execute 2 system table mutations transactions
>  ├── backfill using primary index t1_pkey in relation t1
>  │     ⇒ +id1: id↗, name↗, money
> ```

How to understand/interpret this line?  Can we pretty print this step with something like `backfill primary index (4) "idx4(i, j, k)" from primary index (2) "idx2(i,j)" in relation "t1"`, or, if we want to use symbols/shapes, maybe something like "idx2(i,j) <-- idx4(i,j,k)`. 
___
*[`pkg/ccl/schemachangerccl/testdata/explain_shape/create_index` line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103930#-NWNGieo9zWYi3Cgh_Fz:-NWNGiep6aauEkJGJE7e:b-yfl4lr) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef449b9df7b35acdd18249901ef420e2794af40/pkg/ccl/schemachangerccl/testdata/explain_shape/create_index#L16)):*
> ```
>  ├── execute 2 system table mutations transactions
>  ├── merge temporary indexes into backfilled indexes in relation t1
>  │     ~t1@[3] ⇒ +id1
> ```

Similarly, can we format merging step with something easier to read/understand?

**Review by postamar — COMMENTED** [review]
Thanks very much for having taken a look! This helps.

1. This flag already exists for DML plans and is used to synthetise them somewhat.
2. Indeed, yes, already done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103930#-:-NWc6_LB6iC3Ov2i4H01:b-bigy1t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Xiang-Gu)

___
*[`pkg/sql/schemachanger/scbuild/build.go` line 324 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103930#-NWNQ9Wx8iiE5vgDzYQc:-NWc6t9476x1T9spJzMB:bzhbog8) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef449b9df7b35acdd18249901ef420e2794af40/pkg/sql/schemachanger/scbuild/build.go#L324)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

why do we want the `ts==scpb.InvalidTarget` filter?
</blockquote></details>

The builder state includes elements which don't have targets set, that will be their target value. I rewrote this clause into `isNotDropping` which is closer to what I really want to express here.
___
*[`pkg/sql/schemachanger/scpb/name_mappings.go` line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103930#-NWNSEYM2bv0ZZUih7Ti:-NWc7IKg6f4zavL1MsZI:b-3fhsss) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef449b9df7b35acdd18249901ef420e2794af40/pkg/sql/schemachanger/scpb/name_mappings.go#L132)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

Did I understand this correctly: the purpose of the last return clause is for cases where certain name-related elements are needed but not involved in the plan (ts.Target); For example, altering a table won't touch the parent database but we probably want to know its parent database name, which will be stored in the builder state as an element with InvalidTargetStatus by the decomp logic.
</blockquote></details>

Yes basically. I added more commentary to clarify.
___
*[`pkg/sql/schemachanger/scplan/plan_explain.go` line 205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103930#-NWNJKyYAp05kAit1UN7:-NWc7OCB5oI9QE8t4rWQ:b4qlk0i) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef449b9df7b35acdd18249901ef420e2794af40/pkg/sql/schemachanger/scplan/plan_explain.go#L205)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

I saw this `accountFor` helper is defined multiple times. Will it be better to make it a function `func accountFor(label string, memAcc *int) string` and define it once?
</blockquote></details>

I don't feel strongly about this but I don't think so, to me it's basically the same as this, and I have a slight preference for capturing the variable to update in a closure rather than dealing with pointers.
___
*[`pkg/sql/schemachanger/scplan/plan_explain.go` line 377 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103930#-NWNJhw1-1uIsFT1eE35:-NWc8QQD2dBKjlUBMcbu:b-cmt49t) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef449b9df7b35acdd18249901ef420e2794af40/pkg/sql/schemachanger/scplan/plan_explain.go#L377)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

Can you add a bit more comments here about the main purpose of this new EXPLAIN flag? something like "it gives a condensed summary of the operations involved in the schema change with highlights on expensive operations (backfill, validation, etc.), which helps users understand where most of the time will be spent if the schema change is to be executed."
</blockquote></details>

Done! Thanks.
___
*[`pkg/sql/schemachanger/scplan/plan_explain.go` line 446 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103930#-NWNLaen1RH6_mnw4OQW:-NWc8Uln3hb5ntlXWAUE:btbxpdg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef449b9df7b35acdd18249901ef420e2794af40/pkg/sql/schemachanger/scplan/plan_explain.go#L446)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

Are we respecting the real ordering of the backfill and merges if the plan involves >1 backfills and merges?

IIUC, backfill and merge always appears in pairs. If we have a plan where the real ordering of the operations are
1. backfill_1
2. merge_1
3. backfill_2
4. merge_2

Will the logic print out operations in that order? Or, will it be all backfills first and then all merges (i.e. backfill_1 followed by backfill_2 followed by merge_1 followed by merge_2)?
</blockquote></details>

There is no ordering during execution, these operations are performed concurrently. The ordering here is only to ensure that the explain output remains stable.
___
*[`pkg/sql/schemachanger/scplan/plan_explain.go` line 596 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103930#-NWNMfsu4QrB4_DhbYe3:-NWc8evp5ARyVAQv67Wm:bxzpzgk) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef449b9df7b35acdd18249901ef420e2794af40/pkg/sql/schemachanger/scplan/plan_explain.go#L596)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

I have a gut feeling that this might not work properly, because it's possible that we have three backfill/merge groups:
```index_a <-- index_b <-- index_c <-- index_d```
where we backfill `index_b` from `index_a`, backfill `index_c` from `index_b`, and so on.

It's possible, depending on the implementation, that `index_b.GetID()` is bigger than `index_c.GetID()` (do you remember in my support-add-drop-column-alterPK PR we inflate this chain, de-duplicate, and re-inflate again for the next ALTER TABLE stmt, and so on. I think this makes what I described here possible)

In my PR, I need to do similar things to order the primary indexes and I had logic there to sort by the _location_ of srcIndex (i.e. if 'B.srcIdx = A', then A comes before B in the ordering)


</blockquote></details>

I don't understand any of this, sorry. I'm assuming this relates to the previous comment.
___
*[`pkg/ccl/schemachangerccl/testdata/explain/create_index` line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103930#-NWNEeiI79qJ-TODQ1n3:-NWc9702CsO6Tg9aO4xA:b4i07v0) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef449b9df7b35acdd18249901ef420e2794af40/pkg/ccl/schemachangerccl/testdata/explain/create_index#L14)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

what is this "+id1" name for IndexID 2? Saw a bunch of them
</blockquote></details>

I put a plus before elements that are added in the schema change. I changed this to a suffix. These little symbols make the most sense when looking at the EXPLAIN outputs of PK changes, because the new primary index is named the same as the old one (and the intermediate one too for that matter). We might have to revisit this syntax with your PR. I'd be fine with that, I don't expect this to be definitive.
___
*[`pkg/ccl/schemachangerccl/testdata/explain_shape/create_index` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103930#-NWNFPBPDVRXSSZrQRh8:-NWc9dspEPmyVifGZHSv:bva0he4) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef449b9df7b35acdd18249901ef420e2794af40/pkg/ccl/schemachangerccl/testdata/explain_shape/create_index#L13)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

How to understand/interpret this line?  Can we pretty print this step with something like `backfill primary index (4) "idx4(i, j, k)" from primary index (2) "idx2(i,j)" in relation "t1"`, or, if we want to use symbols/shapes, maybe something like "idx2(i,j) <-- idx4(i,j,k)`. 
</blockquote></details>

You're right it's incomprehensible. Fixed.
___
*[`pkg/ccl/schemachangerccl/testdata/explain_shape/create_index` line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103930#-NWNGieo9zWYi3Cgh_Fz:-NWc9mPWE4iOaZJv5w9b:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef449b9df7b35acdd18249901ef420e2794af40/pkg/ccl/schemachangerccl/testdata/explain_shape/create_index#L16)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

Similarly, can we format merging step with something easier to read/understand?
</blockquote></details>

Fixed

**Review by Xiang-Gu — APPROVED** [review]
Thanks for explaining and addressing my feedback. LGTM!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103930#-:-NWgrlLz5uCgNK5oOsJw:bptsobj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

___
*[`pkg/sql/schemachanger/scplan/plan_explain.go` line 446 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103930#-NWNLaen1RH6_mnw4OQW:-NWgmI2u3BOwRzALifmO:byi6j63) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef449b9df7b35acdd18249901ef420e2794af40/pkg/sql/schemachanger/scplan/plan_explain.go#L446)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

There is no ordering during execution, these operations are performed concurrently. The ordering here is only to ensure that the explain output remains stable.
</blockquote></details>

I see now. Input of this function `explainBackfillAndMerges` are all operations within the same stage!
___
*[`pkg/sql/schemachanger/scplan/plan_explain.go` line 596 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103930#-NWNMfsu4QrB4_DhbYe3:-NWgn64eB8EDURekWC0v:b2wjiqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef449b9df7b35acdd18249901ef420e2794af40/pkg/sql/schemachanger/scplan/plan_explain.go#L596)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I don't understand any of this, sorry. I'm assuming this relates to the previous comment.
</blockquote></details>

Correct, I was confused by something else. The sorting here simply ensures a stable output ordering.

**Comment by postamar** [comment]
Thanks for the review!

Rebasing to get rid of flaky test.

**Pull request merged**
