### PR TITLE
sql: fix connExecutor extraTxnState autoRetryCounter race condition

### LINKED ISSUE #75752: sql: connExectuor extraTxnState race condition
**Describe the problem**

`connExecutor` has a field named [`extraTxnState`](https://github.com/cockroachdb/cockroach/blob/f44c694773c7f3d643108e91594f9484a669d058/pkg/sql/conn_executor.go#L1172). This field stores information related to a transaction in addition to the [`txnState`](https://github.com/cockroachdb/cockroach/blob/f44c694773c7f3d643108e91594f9484a669d058/pkg/sql/conn_executor.go#L1159). However, unlike `state` field, `extraTxnState` is not protected by a mutex. 

This can cause the data race conditions when a transaction state transition happens while `crdb_internal.node_sessions` virtual table is queried. 

[Write Operation](https://github.com/cockroachdb/cockroach/blob/f44c694773c7f3d643108e91594f9484a669d058/pkg/sql/conn_executor.go#L2724)

[Read Operation](https://github.com/cockroachdb/cockroach/blob/f44c694773c7f3d643108e91594f9484a669d058/pkg/sql/conn_executor.go#L2892)

[Failed CI Run](https://teamcity.cockroachdb.com/viewLog.html?buildId=4258408&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_Testrace)

```
=== RUN   TestDropColumnAfterMutations
    test_log_scope.go:79: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestDropColumnAfterMutations3101956907
    test_log_scope.go:80: use -show-logs to present logs inline
=== RUN   TestDropColumnAfterMutations/basic-concurrent-drop-mutations
=== RUN   TestDropColumnAfterMutations/failed-concurrent-drop-mutations
==================
WARNING: DATA RACE
Read at 0x00c00513e3f0 by goroutine 607:
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).serialize()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2892 +0x507
  github.com/cockroachdb/cockroach/pkg/sql.(*SessionRegistry).SerializeAll()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/exec_util.go:1950 +0x244
  github.com/cockroachdb/cockroach/pkg/server.(*baseStatusServer).getLocalSessions()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/status.go:187 +0x34d
  github.com/cockroachdb/cockroach/pkg/server.(*statusServer).ListLocalSessions()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/status.go:2118 +0x84
  github.com/cockroachdb/cockroach/pkg/server/serverpb._Status_ListLocalSessions_Handler.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/serverpb/status.pb.go:6939 +0x8b
  github.com/cockroachdb/cockroach/pkg/util/tracing.ServerInterceptor.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/tracing/grpc_interceptor.go:150 +0x5c2
  google.golang.org/grpc.chainUnaryInterceptors.func1.1()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1116 +0x125
  github.com/cockroachdb/cockroach/pkg/rpc.NewServer.func3()
      /go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:236 +0xf5
  google.golang.org/grpc.chainUnaryInterceptors.func1.1()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1119 +0x226
  github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor()
      /go/src/github.com/cockroachdb/cockroach/pkg/rpc/auth.go:71 +0x1c1
  github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor-fm()
      /go/src/github.com/cockroachdb/cockroach/pkg/rpc/auth.go:47 +0x99
  google.golang.org/grpc.chainUnaryInterceptors.func1.1()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1119 +0x226
  github.com/cockroachdb/cockroach/pkg/rpc.NewServer.func1.1()
      /go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:205 +0x70
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:344 +0x161
  github.com/cockroachdb/cockroach/pkg/rpc.NewServer.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:203 +0x135
  google.golang.org/grpc.chainUnaryInterceptors.func1.1()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1119 +0x226
  google.golang.org/grpc.chainUnaryInterceptors.func1()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1121 +0x285
  github.com/cockroachdb/cockroach/pkg/server/serverpb._Status_ListLocalSessions_Handler()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/serverpb/status.pb.go:6941 +0x1da
  google.golang.org/grpc.(*Server).processUnaryRPC()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1282 +0x1514
  google.golang.org/grpc.(*Server).handleStream()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1616 +0xfd3
  google.golang.org/grpc.(*Server).serveStreams.func1.2()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:921 +0xfd

Previous write at 0x00c00513e3f0 by goroutine 1665:
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).txnStateTransitionsApplyWrapper()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2724 +0x7d0
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1955 +0x1ca8
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1703 +0x5fe
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).initConnEx.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:205 +0xc4
```

**Expected behavior**

Race condition should not happen.

### PR DESCRIPTION
**Pull request by RichardJCai**
Release note: None

Fixes https://github.com/cockroachdb/cockroach/issues/75752

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75827)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75827#-MuyTfT70EuxCg8AW1Ol):*
is there a test that can be added, or can the commit say when this was likely to happen?
___
*[pkg/sql/conn_executor.go, line 1172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75827#-MuyTk707N6rzroGdmxf:-MuyTk707N6rzroGdmxg:b-1n9dl6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2f88bf438964b8696c4421b7d529fb113a1069/pkg/sql/conn_executor.go#L1172)):*
> ```Go
> 		// autoRetryCounter may be read concurrently by serialize(), thus we must
> 		// update the counter using atomic operations.
> 		autoRetryCounter int32
> ```

nit: if this was changed to an `*int32`, i think it would be easier to remember that it needs to be accessed atomically.

(we'd also have to change the initialization of extraTxnState so that it sets `autoRetryCounter: new(int32)`)

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75827)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/sql/conn_executor.go, line 1172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75827#-MuyTk707N6rzroGdmxf:-Mv-LjoR5dSyOPu_asr9:btgahzs) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2f88bf438964b8696c4421b7d529fb113a1069/pkg/sql/conn_executor.go#L1172)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: if this was changed to an `*int32`, i think it would be easier to remember that it needs to be accessed atomically.

(we'd also have to change the initialization of extraTxnState so that it sets `autoRetryCounter: new(int32)`)
</blockquote></details>

also maybe rename it to `atomicAutoRetryCounter` (or something...)

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75827)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75827#-MuyTfT70EuxCg8AW1Ol):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

is there a test that can be added, or can the commit say when this was likely to happen?
</blockquote></details>

Not obvious to me about how we can test this or if a test would be worth it. 

I'll update the commit with some info.
___
*[pkg/sql/conn_executor.go, line 1172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75827#-MuyTk707N6rzroGdmxf:-Mv05hiFAcV5_cmqYM4O:b-9qn4sb) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2f88bf438964b8696c4421b7d529fb113a1069/pkg/sql/conn_executor.go#L1172)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

also maybe rename it to `atomicAutoRetryCounter` (or something...)
</blockquote></details>

Going to use atomic.Value instead and added a new function to avoid nil pointer error.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75827)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/sql/conn_executor.go, line 1172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75827#-MuyTk707N6rzroGdmxf:-Mv0NYhG8sk2Qo71oTEX:b-3c3oda) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2f88bf438964b8696c4421b7d529fb113a1069/pkg/sql/conn_executor.go#L1172)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Going to use atomic.Value instead and added a new function to avoid nil pointer error.
</blockquote></details>

you could avoid the nil pointer if you init `autoRetryCounter: new(int32)` somewhere in `newConnExecutor`

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75827)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/conn_executor.go, line 1172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75827#-MuyTk707N6rzroGdmxf:-Mv0i9d49QUSvdwUztEq:b-e9muj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2f88bf438964b8696c4421b7d529fb113a1069/pkg/sql/conn_executor.go#L1172)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

you could avoid the nil pointer if you init `autoRetryCounter: new(int32)` somewhere in `newConnExecutor`
</blockquote></details>

Yeah that seems more reasonable

**Review by rafiss — APPROVED** [review]
thanks!!

**Comment by RichardJCai** [comment]
TFTR!
bors r=rafiss

**Pull request merged**
