### PR TITLE
kvclient: allow DistSender to consider non-voters when routing requests

### PR DESCRIPTION
**Pull request by aayushshah15**
Before this patch, the DistSender would only route BatchRequests to
replicas of types `VOTER_FULL` and `VOTER_INCOMING`. This patch changes
that to let the DistSender route requests (for instance, follower read
requests) to `NON_VOTER` replicas as well.

Release note: None

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
> for instance, follower read requests

I think we want *only* "follower read requests" to be sent to `NON_VOTERs`. Can you confirm that that's what the patch does?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-:-MQweeDCDke75kW7v3-M:bhtnf4y)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @nvanbenschoten)

___
*[pkg/kv/kvclient/kvcoord/replica_slice.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MQwe9CKD-thK7P871Up:-MQwe9CKD-thK7P871Uq:bkk2pzg) ([raw file](https://github.com/cockroachdb/cockroach/blob/426bc7a7722668a6ec859145aab041021f099dc8/pkg/kv/kvclient/kvcoord/replica_slice.go#L46)):*
> ```Go
> // that are not gossiped are omitted from the result.
> //
> // Generally, only voting and non-voting replicas are returned. However, if a
> ```

nit: s/only voting and non-voting replicas are returned/learners are not returned.

**Review by nvb — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58772)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15)

___
*[pkg/kv/kvserver/replica_follower_read.go, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MQx8m_uE3oXYh8RgqJ9:-MQx8m_uE3oXYh8RgqJA:b-xo8clg) ([raw file](https://github.com/cockroachdb/cockroach/blob/426bc7a7722668a6ec859145aab041021f099dc8/pkg/kv/kvserver/replica_follower_read.go#L65)):*
> ```Go
> 	}
> 	// TODO DURING REVIEW: Is there a reason we shouldn't be allowing
> 	// VOTER_INCOMINGs here? Since we use LEARNERs to upreplicate, VOTER_INCOMINGs
> ```

I thought either @andreimatei or @ajwerner had made that change. Maybe there's a PR sitting around to do so?

This is also related to @andreimatei's plans to allow VOTER_INCOMING replicas to acquire leases, in which case we'll certainly need to issue both read and write requests to them.

**Review by aayushshah15 — COMMENTED** [review]
> Can you confirm that that's what the patch does?

Just to make sure I understood you, we don't want to include `NON_VOTER`s in the `ReplicaSlice` in order to avoid a possible network hop in the case we have a request that cannot be served by a follower replica and we have a stale view of the leaseholder, right? 

PTAL at what I've done there.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-:-MQy174GCfL-eTXSGr_Q:b-wpsdgg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, and @nvanbenschoten)

___
*[pkg/kv/kvclient/kvcoord/replica_slice.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MQwe9CKD-thK7P871Up:-MQy63mV8mZC7tnl1bRZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/426bc7a7722668a6ec859145aab041021f099dc8/pkg/kv/kvclient/kvcoord/replica_slice.go#L46)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: s/only voting and non-voting replicas are returned/learners are not returned.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_follower_read.go, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MQx8m_uE3oXYh8RgqJ9:-MR-8vPd7fz9hTbhPaqN:b-p6m2eh) ([raw file](https://github.com/cockroachdb/cockroach/blob/426bc7a7722668a6ec859145aab041021f099dc8/pkg/kv/kvserver/replica_follower_read.go#L65)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I thought either @andreimatei or @ajwerner had made that change. Maybe there's a PR sitting around to do so?

This is also related to @andreimatei's plans to allow VOTER_INCOMING replicas to acquire leases, in which case we'll certainly need to issue both read and write requests to them.
</blockquote></details>

I added a commit to this PR that let's `VOTER_INCOMING`s serve follower reads as well.

**Review by andreimatei — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-:-MR27kIm590tpwhuFpqL:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @andreimatei, and @nvanbenschoten)

___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 1786 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MR273Q03R19TVs5Hw4i:-MR273Q03R19TVs5Hw4j:b5249zq) ([raw file](https://github.com/cockroachdb/cockroach/blob/16eb23125ca413526f241b94bbefcadcf0ce6b77/pkg/kv/kvclient/kvcoord/dist_sender.go#L1786)):*
> ```Go
> 	ba.RangeID = desc.RangeID
> 	leaseholder := routing.Leaseholder()
> 	canFollowerRead := (ds.clusterID != nil) && CanSendToFollower(ds.clusterID.Get(), ds.st, ba)
> ```

ugh this is not your mess, but do you mind checking if it's easy to have the cluster id be bound inside the `CanSendToFollower()` (i.e. in the ccl package)? Like, make the cluster id be provided to that package once and for all when a cluster id is known, instead of burdening callers like this with it.
___
*[pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go, line 234 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MR27XtE-xtr4Jn8L5g7:-MR27XtE-xtr4Jn8L5g8:b-hbhqsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/16eb23125ca413526f241b94bbefcadcf0ce6b77/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L234)):*
> ```Go
> 	// TODO(aayush): We should be able create RangeFeeds on non-voting replicas.
> 	// Do this in a focussed patch.
> 	replicas, err := NewReplicaSlice(ctx, ds.nodeDescs, desc, nil, false)
> ```

nit: "Do this in a focussed patch." is a weird TODO to merge.
___
*[pkg/kv/kvclient/kvcoord/replica_slice.go, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MR22uW982_9GBWLm4KD:-MR22uW982_9GBWLm4KE:b-49i9ur) ([raw file](https://github.com/cockroachdb/cockroach/blob/16eb23125ca413526f241b94bbefcadcf0ce6b77/pkg/kv/kvclient/kvcoord/replica_slice.go#L66)):*
> ```Go
> 	desc *roachpb.RangeDescriptor,
> 	leaseholder *roachpb.ReplicaDescriptor,
> 	canUseFollowerRead bool,
> ```

Make it an enum pls.
And if you call the options, for example, `Voters` and `VotersAndNonVoters`, then there's no reason to say anything about leases in any comments. Let the caller figure out what it wants and way and be prescriptive.

Since I hate the `ReplicaSlice` anyway, I'd prefer to keep it as dumb as possible.
___
*[pkg/kv/kvclient/kvcoord/replica_slice.go, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MR23Nt-DUp-z-q42jbV:-MR23Nt-DUp-z-q42jbW:b-z1gysd) ([raw file](https://github.com/cockroachdb/cockroach/blob/16eb23125ca413526f241b94bbefcadcf0ce6b77/pkg/kv/kvclient/kvcoord/replica_slice.go#L78)):*
> ```Go
> 	// hop, everything would still work if we had `All` here.
> 	var replicas []roachpb.ReplicaDescriptor
> 	if canUseFollowerRead {
> ```

let's tie the condition to `checkCanReceiveLease()`. If you rebase on top of #58722, that  function gets a usable interface. It might be time to move it out of `batcheval` into a more accessible package.
___
*[pkg/roachpb/api.go, line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MR248OoBKLbyeuGraAF:-MR248OoBKLbyeuGraAG:b-fq3nfj) ([raw file](https://github.com/cockroachdb/cockroach/blob/16eb23125ca413526f241b94bbefcadcf0ce6b77/pkg/roachpb/api.go#L56)):*
> ```Go
> // RequiresReadLease returns whether the ReadConsistencyType requires
> // that a read-only request be performed on an active valid leaseholder.
> // TODO DURING REVIEW: Not entirely related to the PR, but this confused me for
> ```

yeah; i'd probably just call it `Inconistent`
___
*[pkg/roachpb/metadata_replicas.go, line 266 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MR26Pn1CPqp8IobfTSz:-MR26Pn1CPqp8IobfTT-:b-u95vxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/35a767519982f1cdfb44fcdc9df818247df5d636/pkg/roachpb/metadata_replicas.go#L266)):*
> ```Go
> // replication change, incoming or outgoing voters. Notably, this set must
> // encapsulate all replicas of a range for a range merge to proceed.
> func (d ReplicaSet) VoterFullAndNonVoterDescriptors() []ReplicaDescriptor {
> ```

what's going on here? The implementation is the same as below. Two things with seemingly different name for the same effect?
If you wanna make one about merges, then put that in the name. But I'd still stick to one.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58772)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @andreimatei, and @nvanbenschoten)

___
*[pkg/roachpb/metadata_replicas.go, line 266 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MR26Pn1CPqp8IobfTSz:-MR28EKU49o40SdwtJS0:bfgn2a3) ([raw file](https://github.com/cockroachdb/cockroach/blob/35a767519982f1cdfb44fcdc9df818247df5d636/pkg/roachpb/metadata_replicas.go#L266)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what's going on here? The implementation is the same as below. Two things with seemingly different name for the same effect?
If you wanna make one about merges, then put that in the name. But I'd still stick to one.
</blockquote></details>

Like, either name them for what they return (my preference given where they live) or name them for what they're used for. If we name them but what they return, there should be only one.

**Review by nvb — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58772)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @andreimatei)

___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 1786 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MR273Q03R19TVs5Hw4i:-MR2ZEwSDwyQ4xvlbGkB:b-o33qqr) ([raw file](https://github.com/cockroachdb/cockroach/blob/16eb23125ca413526f241b94bbefcadcf0ce6b77/pkg/kv/kvclient/kvcoord/dist_sender.go#L1786)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

ugh this is not your mess, but do you mind checking if it's easy to have the cluster id be bound inside the `CanSendToFollower()` (i.e. in the ccl package)? Like, make the cluster id be provided to that package once and for all when a cluster id is known, instead of burdening callers like this with it.
</blockquote></details>

Mind opening an issue for this? Seems pretty unrelated to this PR.
___
*[pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go, line 232 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MR2ZLzO0zTu7xWuRVRD:-MR2ZLzO0zTu7xWuRVRE:b-2m8jvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/16eb23125ca413526f241b94bbefcadcf0ce6b77/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L232)):*
> ```Go
> 		latencyFn = ds.rpcContext.RemoteClocks.Latency
> 	}
> 	// TODO(aayush): We should be able create RangeFeeds on non-voting replicas.
> ```

Yes, this will be a major reason to create non-voting replicas. We should support it. Doing so in a separate patch so we can include a good test sounds like the right approach to me.
___
*[pkg/kv/kvclient/kvcoord/replica_slice.go, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MR22uW982_9GBWLm4KD:-MR2ZlSU6SHD37YZYSNT:b-l4vxga) ([raw file](https://github.com/cockroachdb/cockroach/blob/16eb23125ca413526f241b94bbefcadcf0ce6b77/pkg/kv/kvclient/kvcoord/replica_slice.go#L66)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Make it an enum pls.
And if you call the options, for example, `Voters` and `VotersAndNonVoters`, then there's no reason to say anything about leases in any comments. Let the caller figure out what it wants and way and be prescriptive.

Since I hate the `ReplicaSlice` anyway, I'd prefer to keep it as dumb as possible.
</blockquote></details>

Either that or invert this to be `onlyPossibleLeaseholders bool`. I fear the inclusion of the `leaseholder` arg here already did away with keeping this dumb.
___
*[pkg/kv/kvclient/kvcoord/replica_slice.go, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MR23Nt-DUp-z-q42jbV:-MR2_3nW4pfAlCTAgjor:b-gmy12m) ([raw file](https://github.com/cockroachdb/cockroach/blob/16eb23125ca413526f241b94bbefcadcf0ce6b77/pkg/kv/kvclient/kvcoord/replica_slice.go#L78)):*
> It might be time to move it out of batcheval into a more accessible package.

Agreed. Let's move it to `roachpb`. And make it return a bool instead of an error so it's cheap to call.
___
*[pkg/kv/kvserver/replica_learner_test.go, line 775 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MR2aBWZ1qRh_g8tICPx:-MR2aBWZ1qRh_g8tICPy:b-ygk2pk) ([raw file](https://github.com/cockroachdb/cockroach/blob/35a767519982f1cdfb44fcdc9df818247df5d636/pkg/kv/kvserver/replica_learner_test.go#L775)):*
> ```Go
> }
> 
> func TestLearnerAndJointConfigFollowerRead(t *testing.T) {
> ```

Should this test have been expanded in the first commit to include non-voting replicas? Or should we otherwise introduce a new test for follower reads off non-voting replicas? Actually, it doesn't look like we're actually testing that `VOTER_INCOMING` replicas can server follower reads now, just that they can't not serve them. So I think we need a test in each of these commits. Maybe there's an existing test that we can generalize?
___
*[pkg/roachpb/metadata_replicas.go, line 266 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MR26Pn1CPqp8IobfTSz:-MR2_xII-4faYR6ABtAt:b-xfl5s2) ([raw file](https://github.com/cockroachdb/cockroach/blob/35a767519982f1cdfb44fcdc9df818247df5d636/pkg/roachpb/metadata_replicas.go#L266)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Like, either name them for what they return (my preference given where they live) or name them for what they're used for. If we name them but what they return, there should be only one.
</blockquote></details>

+1 to these points.

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58772)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 1786 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MR273Q03R19TVs5Hw4i:-MR2bimV1wEXWn9iCmVn:bpm97cu) ([raw file](https://github.com/cockroachdb/cockroach/blob/16eb23125ca413526f241b94bbefcadcf0ce6b77/pkg/kv/kvclient/kvcoord/dist_sender.go#L1786)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Mind opening an issue for this? Seems pretty unrelated to this PR.
</blockquote></details>

It seems like we generate it inside `bootstrapCluster()` and then plumb it through to where we create the `DistSender`. I can't immediately think of a way to do what you want Andrei, I'm adding a TODO for now. 
___
*[pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go, line 232 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MR2ZLzO0zTu7xWuRVRD:-MR2cdge6bPu3Dg1lFwE:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/16eb23125ca413526f241b94bbefcadcf0ce6b77/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L232)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yes, this will be a major reason to create non-voting replicas. We should support it. Doing so in a separate patch so we can include a good test sounds like the right approach to me.
</blockquote></details>

:+1: 
___
*[pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go, line 234 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MR27XtE-xtr4Jn8L5g7:-MR2TbRd4KO0Jaq7c6OZ:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/16eb23125ca413526f241b94bbefcadcf0ce6b77/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L234)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: "Do this in a focussed patch." is a weird TODO to merge.
</blockquote></details>

Fixed.
___
*[pkg/kv/kvclient/kvcoord/replica_slice.go, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MR22uW982_9GBWLm4KD:-MR2cwXn1FV7VV0j-8Rd:b-8wd8f0) ([raw file](https://github.com/cockroachdb/cockroach/blob/16eb23125ca413526f241b94bbefcadcf0ce6b77/pkg/kv/kvclient/kvcoord/replica_slice.go#L66)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Either that or invert this to be `onlyPossibleLeaseholders bool`. I fear the inclusion of the `leaseholder` arg here already did away with keeping this dumb.
</blockquote></details>

Turned it into an enum.
___
*[pkg/kv/kvclient/kvcoord/replica_slice.go, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MR23Nt-DUp-z-q42jbV:-MRIC7a7-GGxLz1vj4a9:b-pthidn) ([raw file](https://github.com/cockroachdb/cockroach/blob/16eb23125ca413526f241b94bbefcadcf0ce6b77/pkg/kv/kvclient/kvcoord/replica_slice.go#L78)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> It might be time to move it out of batcheval into a more accessible package.

Agreed. Let's move it to `roachpb`. And make it return a bool instead of an error so it's cheap to call.
</blockquote></details>

Done except for changing the return type of that method since it seems like a bunch of its callers might care about the kind of error being returned (i.e. if the `ReplicaID` being passed in does not exist). In case this is about avoiding potential allocations, would it make it cheap enough if the errors were `const`s at the top of the file?
___
*[pkg/kv/kvserver/replica_learner_test.go, line 775 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MR2aBWZ1qRh_g8tICPx:-MR4qBtq9Fe40n5lMTCx:bei6qez) ([raw file](https://github.com/cockroachdb/cockroach/blob/35a767519982f1cdfb44fcdc9df818247df5d636/pkg/kv/kvserver/replica_learner_test.go#L775)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should this test have been expanded in the first commit to include non-voting replicas? Or should we otherwise introduce a new test for follower reads off non-voting replicas? Actually, it doesn't look like we're actually testing that `VOTER_INCOMING` replicas can server follower reads now, just that they can't not serve them. So I think we need a test in each of these commits. Maybe there's an existing test that we can generalize?
</blockquote></details>

I extended an existing test for the first commit, and added a new one testing follower reads on `VOTER_INCOMING`.
___
*[pkg/roachpb/api.go, line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MR248OoBKLbyeuGraAF:-MR2czAMDPqcU-f4Iw5B:bguiv2u) ([raw file](https://github.com/cockroachdb/cockroach/blob/16eb23125ca413526f241b94bbefcadcf0ce6b77/pkg/roachpb/api.go#L56)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

yeah; i'd probably just call it `Inconistent`
</blockquote></details>

Added a TODO for it.
___
*[pkg/roachpb/metadata_replicas.go, line 266 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MR26Pn1CPqp8IobfTSz:-MR2TfHp0-ctlzfs6T8S:ba5b1p6) ([raw file](https://github.com/cockroachdb/cockroach/blob/35a767519982f1cdfb44fcdc9df818247df5d636/pkg/roachpb/metadata_replicas.go#L266)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

+1 to these points.
</blockquote></details>

I had messed up, I had intended to have it such that a `predVoterFullOrNonVoter()` filters for usage in range merges (doesn't include `VOTER_INCOMING`) and a `predVoterOrNonVoter()` filters for the `DistSender` to route follower read requests to (which does include `VOTER_INCOMING`). All fixed now.

**Review by andreimatei — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-:-MRQjW6u6Lm1Ey02t6K9:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @andreimatei, and @nvanbenschoten)

___
*[pkg/roachpb/metadata_replicas.go, line 497 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MRQjSsO1pvINbcVgvu9:-MRQjDQeC_Sqrt1dkIXg:b1t93up) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd12430c6c214cb4b70bcc144cc1ac17453fb52d/pkg/roachpb/metadata_replicas.go#L497)):*
> ```Go
> }
> 
> // CheckCanReceiveLease checks whether `wouldbeLeaseholder` can receive a lease. Returns an error
> ```

wrapping

**Review by nvb — COMMENTED** [review]
:lgtm: mod a few comments.

> Reviewed 6 of 7 files at r7, 6 of 11 files at r8, 6 of 6 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-:-MRR8mAU3v4MEeHotMQX:blrad3a)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15 and @andreimatei)

___
*[pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go, line 232 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MR2ZLzO0zTu7xWuRVRD:-MRR6WrS0AN6hk93GVYW:b-54tquq) ([raw file](https://github.com/cockroachdb/cockroach/blob/16eb23125ca413526f241b94bbefcadcf0ce6b77/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L232)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

Mind opening an issue for this? Issues are better for tracking anything that has user-visible impact.
___
*[pkg/kv/kvclient/kvcoord/replica_slice.go, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MR23Nt-DUp-z-q42jbV:-MRR6oGaAb7m719qvzxF:btqhbwn) ([raw file](https://github.com/cockroachdb/cockroach/blob/16eb23125ca413526f241b94bbefcadcf0ce6b77/pkg/kv/kvclient/kvcoord/replica_slice.go#L78)):*
> In case this is about avoiding potential allocations, would it make it cheap enough if the errors were consts at the top of the file?

Yes, that would make things cheap enough. We'll need to make that change in this commit if we want to keep this as an `error`. We don't want to introduce new allocations into this hot path if they can be easily avoided.
___
*[pkg/kv/kvclient/kvcoord/replica_slice.go, line 42 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MRR6fCvBg6umU7fhv2b:-MRR6fCvBg6umU7fhv2c:b-awit8x) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd12430c6c214cb4b70bcc144cc1ac17453fb52d/pkg/kv/kvclient/kvcoord/replica_slice.go#L42)):*
> ```Go
> type ReplicaSlice []ReplicaInfo
> 
> type ReplicaSliceFilter int
> ```

The linter will likely tell you this, but this will need a comment, as will each value.
___
*[pkg/kv/kvserver/replica_learner_test.go, line 791 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MRR7es736u_arvGj2Pj:-MRR7es736u_arvGj2Pk:bfkg96i) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd12430c6c214cb4b70bcc144cc1ac17453fb52d/pkg/kv/kvserver/replica_learner_test.go#L791)):*
> ```Go
> 	defer tc.Stopper().Stop(ctx)
> 	db := sqlutils.MakeSQLRunner(tc.ServerConn(0))
> 	db.Exec(t, fmt.Sprintf(`SET CLUSTER SETTING kv.closed_timestamp.target_duration = '%s'`,
> ```

Out of curiosity, why was this needed?
___
*[pkg/sql/physicalplan/replicaoracle/oracle.go, line 228 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MRR8TZd7n7W9PYVVmR9:-MRR8TZd7n7W9PYVVmRA:b-3gyq8o) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd12430c6c214cb4b70bcc144cc1ac17453fb52d/pkg/sql/physicalplan/replicaoracle/oracle.go#L228)):*
> ```Go
> 	}
> 
> 	replicas, err := replicaSliceOrErr(ctx, o.nodeDescs, desc, kvcoord.OnlyPotentialLeaseholders)
> ```

How did you decide on these choices. It's not clear to me why some should use `OnlyPotentialLeaseholders` and others should use `AllExtantReplicas`.

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58772)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/kvclient/kvcoord/replica_slice.go, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MR23Nt-DUp-z-q42jbV:-MS3k848CKE5GfD18a-T:b-3h2gwg) ([raw file](https://github.com/cockroachdb/cockroach/blob/16eb23125ca413526f241b94bbefcadcf0ce6b77/pkg/kv/kvclient/kvcoord/replica_slice.go#L78)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> In case this is about avoiding potential allocations, would it make it cheap enough if the errors were consts at the top of the file?

Yes, that would make things cheap enough. We'll need to make that change in this commit if we want to keep this as an `error`. We don't want to introduce new allocations into this hot path if they can be easily avoided.
</blockquote></details>

Done, but these pre-allocated errors cannot be parametrized right? LMK if you're not ok with what I've done here.
___
*[pkg/kv/kvclient/kvcoord/replica_slice.go, line 42 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MRR6fCvBg6umU7fhv2b:-MS3fPSz56uYjHXidlc4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd12430c6c214cb4b70bcc144cc1ac17453fb52d/pkg/kv/kvclient/kvcoord/replica_slice.go#L42)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The linter will likely tell you this, but this will need a comment, as will each value.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_learner_test.go, line 791 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MRR7es736u_arvGj2Pj:-MS3fQlV-ZVj_8BI2Bby:bvx2le2) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd12430c6c214cb4b70bcc144cc1ac17453fb52d/pkg/kv/kvserver/replica_learner_test.go#L791)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Out of curiosity, why was this needed?
</blockquote></details>

Previous incantation was getting parsed as ~`8333 hours` by CRDB. Before I wrote a separate test for follower reads on `VOTER_INCOMING`, I tried to quickly check it by modifying this test & noticed the funkiness.
___
*[pkg/roachpb/metadata_replicas.go, line 497 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MRQjSsO1pvINbcVgvu9:-MS3g3pu9TBDiDrUdjg8:bhu9kdm) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd12430c6c214cb4b70bcc144cc1ac17453fb52d/pkg/roachpb/metadata_replicas.go#L497)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

wrapping
</blockquote></details>

Looks like you fixed it in your PR.
___
*[pkg/sql/physicalplan/replicaoracle/oracle.go, line 228 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-MRR8TZd7n7W9PYVVmR9:-MS3g6uw03M_uaahcim3:b-egyvif) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd12430c6c214cb4b70bcc144cc1ac17453fb52d/pkg/sql/physicalplan/replicaoracle/oracle.go#L228)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

How did you decide on these choices. It's not clear to me why some should use `OnlyPotentialLeaseholders` and others should use `AllExtantReplicas`. 
</blockquote></details>

We only use the `closestOracle` for follower-read queries see: https://github.com/cockroachdb/cockroach/blob/b44a0a0f184ad8437ee56b133dc6ecc7227e4393/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go#L137, and `binPackingOracle` for the rest. We don't use the `randomChoiceOracle` for anything besides testing AFAICT.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 5 of 17 files at r10, 6 of 11 files at r11, 6 of 6 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58772#-:-MS9IzvC7bMAnoRznUar:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

**Comment by aayushshah15** [comment]
TFTRs!

bors r+

**Pull request merged**
