### PR TITLE
sql,server: change indexusagestats subsystem to issue cluster RPC fanout

### PR DESCRIPTION
**Pull request by Azhng**
sql: introduce crdb_internal.index_usage_stats virtual table

This commit introduce crdb_internal.index_usage_stats virtual
table that is backed by new clusterindexusagestats package. This
new package implements a variant of the indexusagestats interface
and serves the data by issuing cluster RPC fanout.

Addresses #64740

Followup to #66451

Release note (sql change): introduce crdb_internal.index_usage_statistics
virtual table to surface index usage statistics.
sql.metrics.index_usage_stats.enabled cluster setting can be used to
turn on/off the subsystem. It is default to true.

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
your "follow up"on the PR description is pointing to itself :)  

> Reviewed 2 of 21 files at r3, 31 of 31 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66639#-:-MeeLPCK3OBgc7TsRH8i:bu6w04v)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @mgartner)

___
*[pkg/server/index_usage_stats_test.go, line 215 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66639#-MeeM5Re9DtwHgqV37Di:-MeeM5Re9DtwHgqV37Dj:b-vcrb5s) ([raw file](https://github.com/cockroachdb/cockroach/blob/5692451cb51665e50d50f546531a847691e02f9b/pkg/server/index_usage_stats_test.go#L215)):*
> ```Go
> 	// When being stressed, there's possibility that it might takes a while for
> 	// the stats payload to be ingested.
> 	// time.Sleep(3 * time.Second)
> ```

nit: remove unnecessary comments
___
*[pkg/server/index_usage_stats_test.go, line 218 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66639#-MeeMC1h6ntVpF6gv5wR:-MeeMC1h6ntVpF6gv5wS:b-8so11) ([raw file](https://github.com/cockroachdb/cockroach/blob/5692451cb51665e50d50f546531a847691e02f9b/pkg/server/index_usage_stats_test.go#L218)):*
> ```Go
> 
> 	// Check local node stats.
> 	// Fetch stats reader from each individual
> ```

nit: period
___
*[pkg/sql/idxusage/cluster_idx_usage_stats.go, line 18 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66639#-MeeMkFw4u8FRFAHIu5H:-MeeMkFw4u8FRFAHIu5I:bpc3pm) ([raw file](https://github.com/cockroachdb/cockroach/blob/5692451cb51665e50d50f546531a847691e02f9b/pkg/sql/idxusage/cluster_idx_usage_stats.go#L18)):*
> ```Go
> )
> 
> // ClusterIndexUsageStats implements the Reader interface and is able to returns
> ```

nit: return

**Review by Azhng — COMMENTED** [review]
Fixed! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66639#-:-Mf-0xh676vm7rw4h1V0:b-lx4fua)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @mgartner)

**Comment by Azhng** [comment]
Friendly ping @mgartner

**Review by mgartner — CHANGES_REQUESTED** [review]
> Reviewed 2 of 21 files at r3, 9 of 31 files at r4, 4 of 9 files at r5, 4 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66639)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @maryliag)

___
*[pkg/server/index_usage_stats.go, line 55 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66639#-Mf-qz8e0NJFhOhCqWfb:-Mf-qz8f7cxqvDiPlIdq:b-hs40od) ([raw file](https://github.com/cockroachdb/cockroach/blob/897bc9311a25bc17e517a9b2dc5601c54a3a5e18/pkg/server/index_usage_stats.go#L55)):*
> ```Go
> 			statsReader :=
> 				s.sqlServer.pgServer.SQLServer.GetLocalIndexStatisticsReader()
> 			return serializeIndexUsageStats(req, statsReader)
> ```

Should `req` be `localReq` here?
___
*[pkg/server/index_usage_stats.go, line 58 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66639#-Mf-sKxl8zDK98nP6VxR:-Mf-sKxl8zDK98nP6VxS:b-mj4noy) ([raw file](https://github.com/cockroachdb/cockroach/blob/897bc9311a25bc17e517a9b2dc5601c54a3a5e18/pkg/server/index_usage_stats.go#L58)):*
> ```Go
> 		}
> 
> 		statusServer, err := s.dialNode(ctx, requestedNodeID)
> ```

nit: maybe name `statusServer` to `statusClient` or `client` to make it clear its not of type `statusServer` and that it's a client to a remote status server
___
*[pkg/server/index_usage_stats.go, line 63 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66639#-Mf-r6hu8s2XZX_sEQ5-:-Mf-r6hu8s2XZX_sEQ50:b-bep6s5) ([raw file](https://github.com/cockroachdb/cockroach/blob/897bc9311a25bc17e517a9b2dc5601c54a3a5e18/pkg/server/index_usage_stats.go#L63)):*
> ```Go
> 		}
> 
> 		return statusServer.IndexUsageStatistics(ctx, localReq)
> ```

Should `localReq` be `req` here?
___
*[pkg/server/index_usage_stats.go, line 87 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66639#-Mf-tILS67brhi9x0ql_:-Mf-tILS67brhi9x0qla:buuxw4y) ([raw file](https://github.com/cockroachdb/cockroach/blob/897bc9311a25bc17e517a9b2dc5601c54a3a5e18/pkg/server/index_usage_stats.go#L87)):*
> ```Go
> 	var combinedError error
> 	errFn := func(_ roachpb.NodeID, nodeFnError error) {
> 		if nodeFnError != nil {
> ```

nit: iterateNodes should not call this function with a `nil` error, so you can remove this check.
___
*[pkg/server/index_usage_stats.go, line 115 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66639#-Mf0-HIBESU6eQ3hvD0E:-Mf0-HIBESU6eQ3hvD0F:b-74q6te) ([raw file](https://github.com/cockroachdb/cockroach/blob/897bc9311a25bc17e517a9b2dc5601c54a3a5e18/pkg/server/index_usage_stats.go#L115)):*
> ```Go
> 	}
> 
> 	err := reader.ForEach(idxusage.IteratorOptions{
> ```

Creating a reader interface and implementing a local and cluster implementation of the interface only for the purpose of using either here seems over-engineered for what needs to be accomplished: aggregating index usage stats response from multiple nodes. Also, the cluster implementation just uses a local implementation which has all the complexity and overhead of dealing with concurrent reads and write. Would it be simpler to remove the interface, implement a single struct for local index usage stats, and perform aggregation of the results here?
___
*[pkg/server/index_usage_stats.go, line 118 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66639#-Mf-zpMi-BizjkCCW4Z4:-Mf-zpMi-BizjkCCW4Z5:b-7j1s6p) ([raw file](https://github.com/cockroachdb/cockroach/blob/897bc9311a25bc17e517a9b2dc5601c54a3a5e18/pkg/server/index_usage_stats.go#L118)):*
> ```Go
> 		SortedTableID: req.OrderedTableID,
> 		SortedIndexID: req.OrderedIndexID,
> 		Max:           max,
> ```

It'd be nice to not fetch more than `max` usage stats from remote nodes in the first place, if possible. Or at least to fetch only up to `max` from each node because we'll never need more than that. If that's a lot more effort, maybe leave a TODO somewhere?
___
*[pkg/server/serverpb/status.proto, line 1126 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66639#-Mf-xgwkBH5gQNxt8wjT:-Mf-xgwkBH5gQNxt8wjU:b-jdlccx) ([raw file](https://github.com/cockroachdb/cockroach/blob/897bc9311a25bc17e517a9b2dc5601c54a3a5e18/pkg/server/serverpb/status.proto#L1126)):*
> ```protobuf
>   // by the RPC. If this field is left unset, then all stats data will be
>   // returned at once.
>   oneof max {
> ```

Did you try using `optional` here instead of `oneof`?
___
*[pkg/sql/idxusage/cluster_idx_usage_stats.go, line 26 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66639#-Mf01Mpk53xRSWjdL6ku:-Mf01Mpk53xRSWjdL6kv:b-zbknt3) ([raw file](https://github.com/cockroachdb/cockroach/blob/897bc9311a25bc17e517a9b2dc5601c54a3a5e18/pkg/sql/idxusage/cluster_idx_usage_stats.go#L26)):*
> ```Go
> 	// usage stats, therefore, we do not call LocalIndexUsageStats.Start() method.
> 	storage      *LocalIndexUsageStats
> 	statusServer serverpb.SQLStatusServer
> ```

nit: this field is never used

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66639)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, and @mgartner)

___
*[pkg/server/index_usage_stats.go, line 87 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66639#-Mf-tILS67brhi9x0ql_:-Mf9lPXkCY97TNImBD5W:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/897bc9311a25bc17e517a9b2dc5601c54a3a5e18/pkg/server/index_usage_stats.go#L87)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: iterateNodes should not call this function with a `nil` error, so you can remove this check.
</blockquote></details>

done.
___
*[pkg/server/index_usage_stats.go, line 115 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66639#-Mf0-HIBESU6eQ3hvD0E:-Mf9JJ2h1QCDB29-7eNc:b-lmk8r9) ([raw file](https://github.com/cockroachdb/cockroach/blob/897bc9311a25bc17e517a9b2dc5601c54a3a5e18/pkg/server/index_usage_stats.go#L115)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Creating a reader interface and implementing a local and cluster implementation of the interface only for the purpose of using either here seems over-engineered for what needs to be accomplished: aggregating index usage stats response from multiple nodes. Also, the cluster implementation just uses a local implementation which has all the complexity and overhead of dealing with concurrent reads and write. Would it be simpler to remove the interface, implement a single struct for local index usage stats, and perform aggregation of the results here?
</blockquote></details>

I agree this is a bit awkward. I think the root cause here is that this RPC endpoint is consumed by two different clients:

1. The code that populates `crdb_internal` virtual table. This client needs an aggregated reader so it can populate the virtual table.
2. The DB Console. This client needs the serialized data returning from the RPC endpoint. Preferably aggregated. If not, the DB Console will aggregated in the frontend.

The `max` param was introduced here to distinguish between those two type of use case. But this does introduce quite a bit of awkwardness.

I think a better approach would be: this endpoint does not perform aggregation at all. It returns all the statistics directly to the caller without aggregation. Then the code responsible for `crdb_internal` virtual table would be the one performing aggregation.

Then, the DB Console will be calling to a different endpoint, (possibly the v2 status API that's being built right now) and that API will be responsible to fetching data from the `crdb_internal` virtual table.

I updated the code to reflect this.
___
*[pkg/server/index_usage_stats.go, line 118 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66639#-Mf-zpMi-BizjkCCW4Z4:-Mf9l-WQBxKPirK8Y5og:b-iuuo85) ([raw file](https://github.com/cockroachdb/cockroach/blob/897bc9311a25bc17e517a9b2dc5601c54a3a5e18/pkg/server/index_usage_stats.go#L118)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It'd be nice to not fetch more than `max` usage stats from remote nodes in the first place, if possible. Or at least to fetch only up to `max` from each node because we'll never need more than that. If that's a lot more effort, maybe leave a TODO somewhere?
</blockquote></details>

Removed `max` from the request protobuf now since this API will be primary used for populating the `crdb_internal` virtual table as mentioned in above comment. There's not quite necessary to limit number of rows returning from this endpoint. 
___
*[pkg/server/serverpb/status.proto, line 1126 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66639#-Mf-xgwkBH5gQNxt8wjT:-Mf9ldFY6hBg-Nrwbe3C:b-hui1g4) ([raw file](https://github.com/cockroachdb/cockroach/blob/897bc9311a25bc17e517a9b2dc5601c54a3a5e18/pkg/server/serverpb/status.proto#L1126)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Did you try using `optional` here instead of `oneof`?
</blockquote></details>

Removed `max` param here. See the comment above.
___
*[pkg/sql/idxusage/cluster_idx_usage_stats.go, line 26 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66639#-Mf01Mpk53xRSWjdL6ku:-Mf9lHLKBzWLCVr2Nq45:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/897bc9311a25bc17e517a9b2dc5601c54a3a5e18/pkg/sql/idxusage/cluster_idx_usage_stats.go#L26)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: this field is never used
</blockquote></details>

Done.

**Review by mgartner — CHANGES_REQUESTED** [review]
> Reviewed 15 of 16 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66639)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, and @mgartner)

___
*[pkg/server/index_usage_stats.go, line 63 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66639#-Mf-r6hu8s2XZX_sEQ5-:-MfE7hZA55lfDncu9Tlu:b-gg7us7) ([raw file](https://github.com/cockroachdb/cockroach/blob/897bc9311a25bc17e517a9b2dc5601c54a3a5e18/pkg/server/index_usage_stats.go#L63)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Should `localReq` be `req` here?
</blockquote></details>

Looking at this again, and I think `localReq` is correct. This is basically telling another node "give me _your_ local stats", is that correct? Might be worth a comment for clarity.
___
*[pkg/server/index_usage_stats.go, line 115 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66639#-Mf0-HIBESU6eQ3hvD0E:-MfE9cYM7lODmc6Ld5Yd:b-hswquq) ([raw file](https://github.com/cockroachdb/cockroach/blob/897bc9311a25bc17e517a9b2dc5601c54a3a5e18/pkg/server/index_usage_stats.go#L115)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

I agree this is a bit awkward. I think the root cause here is that this RPC endpoint is consumed by two different clients:

1. The code that populates `crdb_internal` virtual table. This client needs an aggregated reader so it can populate the virtual table.
2. The DB Console. This client needs the serialized data returning from the RPC endpoint. Preferably aggregated. If not, the DB Console will aggregated in the frontend.

The `max` param was introduced here to distinguish between those two type of use case. But this does introduce quite a bit of awkwardness.

I think a better approach would be: this endpoint does not perform aggregation at all. It returns all the statistics directly to the caller without aggregation. Then the code responsible for `crdb_internal` virtual table would be the one performing aggregation.

Then, the DB Console will be calling to a different endpoint, (possibly the v2 status API that's being built right now) and that API will be responsible to fetching data from the `crdb_internal` virtual table.

I updated the code to reflect this.
</blockquote></details>

Sounds simpler to me. :+1: 
___
*[pkg/server/index_usage_stats_test.go, line 195 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66639#-MfE9KUUDdRqq68N1fkz:-MfE9KUUDdRqq68N1fl-:bixujwb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3437ee36fa1a5e57a058a66dc15b8a90d1717e9a/pkg/server/index_usage_stats_test.go#L195)):*
> ```Go
> 	}()
> 
> 	// Records a non-full scan.
> ```

nit add: "over t_a_idx".
___
*[pkg/server/index_usage_stats_test.go, line 199 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66639#-MfE9Sqy9sOFfYAJPkEo:-MfE9Sqy9sOFfYAJPkEp:b-a0lem3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3437ee36fa1a5e57a058a66dc15b8a90d1717e9a/pkg/server/index_usage_stats_test.go#L199)):*
> ```Go
> 	require.NoError(t, err)
> 
> 	// Records an zigzag join.
> ```

nit add: "that scans both t_a_idx and t_b_idx"
___
*[pkg/server/index_usage_stats_test.go, line 203 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66639#-MfE9XCQB_WA7cScKAeD:-MfE9XCQB_WA7cScKAeE:b-jjci6m) ([raw file](https://github.com/cockroachdb/cockroach/blob/3437ee36fa1a5e57a058a66dc15b8a90d1717e9a/pkg/server/index_usage_stats_test.go#L203)):*
> ```Go
> 	require.NoError(t, err)
> 
> 	// Record a full scan.
> ```

nit add: "over t_b_idx"
___
*[pkg/server/index_usage_stats_test.go, line 213 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66639#-MfE89jI1T4mMSWIqs5k:-MfE89jI1T4mMSWIqs5l:b-skr5ot) ([raw file](https://github.com/cockroachdb/cockroach/blob/3437ee36fa1a5e57a058a66dc15b8a90d1717e9a/pkg/server/index_usage_stats_test.go#L213)):*
> ```Go
> 	// When being stressed, there's possibility that it might takes a while for
> 	// the stats payload to be ingested.
> 	// time.Sleep(3 * time.Second)
> ```

Is this leftover?
___
*[pkg/server/index_usage_stats_test.go, line 260 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66639#-MfE8gGmCGD3bOIVqops:-MfE8gGmCGD3bOIVqopt:b-ay6hlg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3437ee36fa1a5e57a058a66dc15b8a90d1717e9a/pkg/server/index_usage_stats_test.go#L260)):*
> ```Go
> 		statsEntries++
> 		switch stats.Key.IndexID {
> 		case 2: // t@t_a_idx
> ```

nit: could this instead be `case indexKeyA.IndexID`?
___
*[pkg/sql/conn_executor.go, line 272 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66639#-MfE6hKz65dmJDSAdHNx:-MfE6hKz65dmJDSAdHNy:b-nn7fg2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3437ee36fa1a5e57a058a66dc15b8a90d1717e9a/pkg/sql/conn_executor.go#L272)):*
> ```Go
> 	pool *mon.BytesMonitor
> 
> 	// indexUsageStats tracks the index usage statistics.
> ```

nit: Make it clear in this comment that it only tracks usage for the gateway node of a query, not the entire cluster.

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66639)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @mgartner)

___
*[pkg/server/index_usage_stats.go, line 63 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66639#-Mf-r6hu8s2XZX_sEQ5-:-MfEET_868mDZJRqEEbr:b-9camez) ([raw file](https://github.com/cockroachdb/cockroach/blob/897bc9311a25bc17e517a9b2dc5601c54a3a5e18/pkg/server/index_usage_stats.go#L63)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Looking at this again, and I think `localReq` is correct. This is basically telling another node "give me _your_ local stats", is that correct? Might be worth a comment for clarity.
</blockquote></details>

Yes. I'll add a comment. 
___
*[pkg/server/index_usage_stats.go, line 115 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66639#-Mf0-HIBESU6eQ3hvD0E:-MfEEtIp6ZrOX2dsx4Vc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/897bc9311a25bc17e517a9b2dc5601c54a3a5e18/pkg/server/index_usage_stats.go#L115)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Sounds simpler to me. :+1: 
</blockquote></details>

Done.
___
*[pkg/server/index_usage_stats_test.go, line 213 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66639#-MfE89jI1T4mMSWIqs5k:-MfEFAeT0lbkc4zBPKDz:bd4qe07) ([raw file](https://github.com/cockroachdb/cockroach/blob/3437ee36fa1a5e57a058a66dc15b8a90d1717e9a/pkg/server/index_usage_stats_test.go#L213)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Is this leftover?
</blockquote></details>

Ah yes. I cleaned this up earlier but probably messed up the rebase and it sneaked back. :facepalm:

**Review by mgartner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 16 files at r7, 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66639#-:-MfZ3kaV5mbKDh6STiOC:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag and @mgartner)

___
*[pkg/server/index_usage_stats.go, line 63 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66639#-Mf-r6hu8s2XZX_sEQ5-:-MfZ3ZBl6Qa5-9Ql0vQ2:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/897bc9311a25bc17e517a9b2dc5601c54a3a5e18/pkg/server/index_usage_stats.go#L63)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Yes. I'll add a comment. 
</blockquote></details>

Thanks!

**Comment by Azhng** [comment]
TFTR!

bors r+

**Pull request merged**
