### PR TITLE
kvserver: fix constraint analysis on replica replacement

### LINKED ISSUE #94809: kvserver: allocating replacement replicas needs to consider fully satisfying constraints
In a recent investigation, it was discovered that when we have constraints applying to some but not all the replicas needed for a range, it is possible for a replacement operation (such as during decommission) to not consider that all constraints are no longer satisfied. This occurs when we have configurations such as `num_replicas = 3, constraints = '{<some constraint>: 1}'`, and thus would expect to have 2 replicas that do not need to satisfy any constraints, known as "unconstrained replicas"; however replacement of the one replica that satisfies the constraint should not be possible.

This can be reproduced simply with the following:
```
roachprod create local -n4
roachprod stage local release v22.1.12
roachprod start local --racks=4
roachprod ssh local:1 -- './cockroach workload init kv --splits=100'
roachprod sql local:1 -- -e "alter database kv configure zone using num_replicas=3, constraints='{+rack=3: 1}';"
# wait for rebalancing
roachprod ssh local:1 -- './cockroach node decommission 4 --insecure'
# this should not succeed, but it does
```

Jira issue: CRDB-23152

### PR DESCRIPTION
**Pull request by AlexTalks**
This changes the allocator to be fully aware of the replica that is
beingn replaced when allocating new target replicas due to a dead or
decommissioning node. This ensures that if constraints were respected
before the dead or decommissioning node left the cluster, they will
still be respected afterwards, particularly in the case at issue, which
is when partial constraints are set on a range (e.g. `num_replicas = 3,
<some_constraint>: 1`). This is achieved by rejecting candidate
stores to allocate the replacement on when they do not satisfy a
constraint that was satisfied by the existing store. In doing so, this
means that some node decommissions that would previously be able to
execute will now not allow the user to decommission the node and violate
the configured constraints.

Fixes #94809.

Depends on #94024.

Release note (bug fix): Decommissions that would violate constraints set
on a subset of replicas for a range (e.g. `num_replicas = 3,
<constraint>: 1`) will no longer be able to execute, respecting
constraints during and after the decommission.

### CODE REVIEW

**Review by kvoli — COMMENTED** [review]
Few comments/questions.  The linter is making noise in a few areas.

> Reviewed 4 of 4 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94810#-:-NNdYA4pCicrC-BZlfQj:b-yq6uul)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks)

___
*[`-- commits` line 22 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94810#-NNdUqxi85P893QJX9J_):*
nit: beingn
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator.go` line 1326 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94810#-NNdVgXT9cc96FTeWay7:-NNdVgXT9cc96FTeWay8:b-yuifob) ([raw file](https://github.com/cockroachdb/cockroach/blob/80d6a105ed12d4d39fd6def62be14310c5c7455e/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L1326)):*
> ```Go
> 	conf roachpb.SpanConfig,
> 	existingVoters, existingNonVoters []roachpb.ReplicaDescriptor,
> 	replacing *roachpb.ReplicaDescriptor,
> ```

I'm not a huge fan of passing in a reference that could be mutated. I understand we discussed before that a list wasn't great either since it implied you could be replacing more than 1 replica at a time. Is there an alternative?
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go` line 1907 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94810#-NNdX8E-477xawkWl9uh:-NNdX8E-477xawkWl9ui:b-ch7n4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/80d6a105ed12d4d39fd6def62be14310c5c7455e/pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go#L1907)):*
> ```Go
> 		// If so, then only replacing it with a satisfying store is valid to ensure
> 		// that the constraint stays fully satisfied.
> 		if necessary && satisfiedByExistingStore && !satisfiedByCandidateStore {
> ```

Nice stuff here - this is clear to understand.
___
*[`pkg/kv/kvserver/allocator_impl_test.go` line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94810#-NNdXwIf7Jasqd6eAWGW:-NNdXwIf7Jasqd6eAWGX:b-zddnfi) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4b0a9f4a83f527dd6b4202efcbf8d54a940c9c8/pkg/kv/kvserver/allocator_impl_test.go#L112)):*
> ```Go
> 			Locality: roachpb.Locality{
> 				Tiers: []roachpb.Tier{
> 					{
> ```

It looks like these are added in the 1st commit then edited in the 2nd commit to remove some flags. Is this necessary?

**Review by AlexTalks — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94810)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator.go` line 1326 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94810#-NNdVgXT9cc96FTeWay7:-NNnPvbJDYHkQ4f6DZ-3:b-b81a0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/80d6a105ed12d4d39fd6def62be14310c5c7455e/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L1326)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

I'm not a huge fan of passing in a reference that could be mutated. I understand we discussed before that a list wasn't great either since it implied you could be replacing more than 1 replica at a time. Is there an alternative?
</blockquote></details>

I can pass in a concrete `roachpb.ReplicaDescriptor` and use `Validate` (or some new `IsValid` function) to check if it has a value of course.  I prefer using `nil` to indicate that we don't have a replica being replaced, but I understand the concern here. Let me know if you definitely think this should be changed.
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go` line 1907 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94810#-NNdX8E-477xawkWl9uh:-NNnQRJr6ZguFjpQm7gc:b-lyc0i) ([raw file](https://github.com/cockroachdb/cockroach/blob/80d6a105ed12d4d39fd6def62be14310c5c7455e/pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go#L1907)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Nice stuff here - this is clear to understand.
</blockquote></details>

Thanks - I was worried we might need additional cases here but hopefully this makes sense.  This is also the only case where we can return `valid = false, necessary = true`, but that is primarily done so we can log it in the ranking process.
___
*[`pkg/kv/kvserver/allocator_impl_test.go` line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94810#-NNdXwIf7Jasqd6eAWGW:-NNnQdDm0NNq42ndFUJj:b-gsg86z) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4b0a9f4a83f527dd6b4202efcbf8d54a940c9c8/pkg/kv/kvserver/allocator_impl_test.go#L112)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

It looks like these are added in the 1st commit then edited in the 2nd commit to remove some flags. Is this necessary?
</blockquote></details>

Not necessary, should be fixed now.

**Review by kvoli — APPROVED** [review]
> Reviewed 8 of 8 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94810)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks)

___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator.go` line 1326 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94810#-NNdVgXT9cc96FTeWay7:-NNnXJeoEG4dX9LfgqCv:b-pm542o) ([raw file](https://github.com/cockroachdb/cockroach/blob/80d6a105ed12d4d39fd6def62be14310c5c7455e/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L1326)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

I can pass in a concrete `roachpb.ReplicaDescriptor` and use `Validate` (or some new `IsValid` function) to check if it has a value of course.  I prefer using `nil` to indicate that we don't have a replica being replaced, but I understand the concern here. Let me know if you definitely think this should be changed.
</blockquote></details>

It doesn't seem worth changing over it.
___
*[`pkg/kv/kvserver/allocator_impl_test.go` line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94810#-NNdXwIf7Jasqd6eAWGW:-NNnYLS3C0b6shqSBYNj:b7xtsyh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4b0a9f4a83f527dd6b4202efcbf8d54a940c9c8/pkg/kv/kvserver/allocator_impl_test.go#L112)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

Not necessary, should be fixed now.
</blockquote></details>

Did this update push? I can still see them being removed in c2.

https://github.com/cockroachdb/cockroach/pull/94810/commits/b856e5d08d39d939452507bfb1f62b34bb8dcb49#diff-a380886513365b4c5d0612c9bb1f2ee62a11571d189141fcb56d4c41182f4dbfL112
___
*[`pkg/kv/kvserver/store_test.go` line 3595 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94810#-NNnZO1CDvY90iOUyoSu:-NNnZO1CDvY90iOUyoSv:b-2ne23) ([raw file](https://github.com/cockroachdb/cockroach/blob/b856e5d08d39d939452507bfb1f62b34bb8dcb49/pkg/kv/kvserver/store_test.go#L3595)):*
> ```Go
> 				{NodeID: 5, StoreID: 5, ReplicaID: 5},
> 			},
> 			zoneConfig: zonepb.DefaultSystemZoneConfigRef(),
> ```

`s/zoneConfig/spanConfig/` here and few other spots.

**Review by AlexTalks — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94810)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator.go` line 1326 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94810#-NNdVgXT9cc96FTeWay7:-NNrZC-z5psxQKzMuE2O:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/80d6a105ed12d4d39fd6def62be14310c5c7455e/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L1326)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

It doesn't seem worth changing over it.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/allocator_impl_test.go` line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94810#-NNdXwIf7Jasqd6eAWGW:-NNrbAyW9zo6RCckDq8p:bt2vr0y) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4b0a9f4a83f527dd6b4202efcbf8d54a940c9c8/pkg/kv/kvserver/allocator_impl_test.go#L112)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Did this update push? I can still see them being removed in c2.

https://github.com/cockroachdb/cockroach/pull/94810/commits/b856e5d08d39d939452507bfb1f62b34bb8dcb49#diff-a380886513365b4c5d0612c9bb1f2ee62a11571d189141fcb56d4c41182f4dbfL112
</blockquote></details>

Fixed!
___
*[`pkg/kv/kvserver/store_test.go` line 3595 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94810#-NNnZO1CDvY90iOUyoSu:-NNrbCH154doPLe37t9p:b8af9a4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b856e5d08d39d939452507bfb1f62b34bb8dcb49/pkg/kv/kvserver/store_test.go#L3595)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

`s/zoneConfig/spanConfig/` here and few other spots.
</blockquote></details>

Bad rebase, sorry!

**Review by AlexTalks — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94810)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator.go` line 1216 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/94810#-NOHe4AP5AF2Y81iYyIP:-NOHe4AP5AF2Y81iYyIQ:b-y40rnl) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7db7e348f6c596da6e497b847ddf77f399c5182/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L1216)):*
> ```Go
> 	// should be considered of otherwise equal validity, with candidate ranking
> 	// chosing the best of the available options.
> 	var decommissioningReplica *roachpb.ReplicaDescriptor
> ```

FYI @kvoli I added this after some thought and reviewing a failing multiregion test.  I think it makes sense, but if you don't like this logic being in the allocator (and would rather have it in the replicate queue), let me know. Given that I think our goal is to consolidate more logic into the allocator, it made sense to me to live here.

(The issue is, briefly, if we have a multi-region cluster configured to survive region failure, and all nodes in a region die, we want to ensure that replacement of their replicas proceeds despite their replacement effectively breaking constraints).

**Pull request merged**
