### PR TITLE
sql/parser: Treat StrVal and NumVal the same during overload resolution

### LINKED ISSUE #14527: sql: literal values sometimes don't get implicitly converted
There appear to be situations in SQL queries where values will not get implicitly converted to match the column type they're being compared (or assigned) to.

CockroachDB (as of `0499d0d51f0bfb332fd4d69e943812845e9eae99`):
```
root@:26257/> CREATE TABLE d.t (b TIMESTAMP);
CREATE TABLE
root@:26257/> INSERT INTO d.t VALUES ('2015-09-18 00:00:00');
INSERT 1
root@:26257/> SELECT * FROM d.t WHERE b = '2015-09-18 00:00:00';
pq: unsupported comparison operator: <timestamp> = <string>
```

Postgres:
```
template1=# CREATE TABLE t (b TIMESTAMP);
CREATE TABLE
template1=# INSERT INTO t VALUES ('2015-09-18 00:00:00');
INSERT 0 1
template1=# SELECT * FROM t WHERE b = '2015-09-18 00:00:00';
          b
---------------------
 2015-09-18 00:00:00
(1 row)
```

### PR DESCRIPTION
**Pull request by nvb**
Fixes #14527.

Previously, our untyped literal handling was inconsistent for string
literals. We made the decision a while ago to treat string literals as
resolved string types during overload resolution. This decision was made
because it simplified certain logic, avoided ambiguities in a few cases,
and allowed a certain class of errors to be more specific. However, this
approach led to inconsistencies in untyped string constant resolution (see
the linked issue).

This change changes overload resolution and homogeneous type checking to
give `StrVal` constants the same treatment as `NumVal` constants. The
change addresses inconsistencies like the related issue. The cost of
this is that it introduces a limitation that we already had for numeric
constants, which materializes in ambiguities in constant coercion between
parent expressions (see change to `pgwire_test.go`).

This change makes a few errors worse, like the error reported for `'a' + 0`.
Previously we would return and `unsupported binary operator` error. Instead, we
will now return a `could not parse 'a' as type date` error, because type
checking will try to use our `<date> + <int>` overload. An unexpected
effect is that it also improves some errors, like the one for
`COALESCE(1, 2, 3, 4, '5')`. Now, instead of throwing an error that 
`1 is not a string`, we'll read left to right and throw an error that 
`'5' is not an int`.

cc. @justinj

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14593)

### CODE REVIEW

**Comment by jordanlewis** [comment]
:lgtm: Nice! I was wondering where there were no cases for string constants in typeCheckOverloadedExprs. I think this change makes a lot of sense and is a strict improvement, despite the issues that it adds. 

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/parser/type_check_test.go, line 166 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14593#-KgtXm28wrN53AN31uJh:-KgtXm28wrN53AN31uJi:b3lr4eu) ([raw file](https://github.com/cockroachdb/cockroach/blob/da5bbf5ad23e2d990b3df8067005e1c9df116e47/pkg/sql/parser/type_check_test.go#L166)):*
> ```Go
> 	}{
> 		{`'1' + '2'`, `unsupported binary operator:`},
> 		{`'a' + 0`, `could not parse 'a' as type date`},
> ```

This is a pretty hilarious error. FWIW, Postgres complains that 'a' cannot be parsed into an integer, but happily accepts '20170101' + 0. It would be nice to fix this, but I don't think it's a big deal. Perhaps you could write a TODO here and explain what would need to be changed to fix this, if you already know?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14593#-:-KgtZ-gyPzT_vgD5-l7r:b-vsw9e4)*

**Comment by knz** [comment]
I like the simplification too. LGTM modulo longer comments in two places.

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/pgwire/pgwire_test.go, line 751 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14593#-Kh-DYVQCQJlLY-JM6FM:-Kh-DYVRm6mEzpTXC1JP:bxpnniy) ([raw file](https://github.com/cockroachdb/cockroach/blob/da5bbf5ad23e2d990b3df8067005e1c9df116e47/pkg/sql/pgwire/pgwire_test.go#L751)):*
> ```Go
> 		//},
> 
> 		// TODO(nvanbenschoten) Same class of limitation as that in logic_test/typing.
> ```

Please extend the comment with a reminder of what the limitation is.

---

*[pkg/sql/testdata/logic_test/typing, line 127 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14593#-Kh-DTYE1qogJiatk88I:-Kh-DTYGnDm6agSfkjVy:bluagyi) ([raw file](https://github.com/cockroachdb/cockroach/blob/da5bbf5ad23e2d990b3df8067005e1c9df116e47/pkg/sql/testdata/logic_test/typing#L127)):*
> ```
> false   2010-09-28 00:00:00 +0000 +0000   2010-09-28 12:00:00.1 +0000 +0000   2010-09-29 12:00:00.1 +0000 +0000   12h2m0s
> 
> ## 14527
> ```

Can you extend this comment with a one-line summary of what this issue is about.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14593#-:-Kh-DiNxmfyGWs05x3e2:butqq8j)*

**Comment by nvanbenschoten** [comment]
TFTRs!

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/type_check_test.go, line 166 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14593#-KgtXm28wrN53AN31uJh:-KhRJ38HyvfBtgsEA8j4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da5bbf5ad23e2d990b3df8067005e1c9df116e47/pkg/sql/parser/type_check_test.go#L166)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This is a pretty hilarious error. FWIW, Postgres complains that 'a' cannot be parsed into an integer, but happily accepts '20170101' + 0. It would be nice to fix this, but I don't think it's a big deal. Perhaps you could write a TODO here and explain what would need to be changed to fix this, if you already know?
</blockquote></details>

Done.

---

*[pkg/sql/pgwire/pgwire_test.go, line 751 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14593#-Kh-DYVQCQJlLY-JM6FM:-KhRJjsdS79We9MUU8M0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da5bbf5ad23e2d990b3df8067005e1c9df116e47/pkg/sql/pgwire/pgwire_test.go#L751)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please extend the comment with a reminder of what the limitation is.
</blockquote></details>

Done.

---

*[pkg/sql/testdata/logic_test/typing, line 127 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14593#-Kh-DTYE1qogJiatk88I:-KhRKfVtrKXMxz1LJnNE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da5bbf5ad23e2d990b3df8067005e1c9df116e47/pkg/sql/testdata/logic_test/typing#L127)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can you extend this comment with a one-line summary of what this issue is about.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14593#-:-KhRKgFe2ebjkXgI1Zvk:bz5mair)*

**Comment by knz** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14593)*

**Pull request merged**
