### PR TITLE
dev: for `dev bench`, forego sharding and run benchmarks with 1 CPU

### PR DESCRIPTION
**Pull request by rickystewart**
Epic: CRDB-17171
Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Thanks for the change!

What does `-cpu` do exactly? It definitely runs a single instance of the benchmark instead of N, but is the go process itself restricted to 1 cpu, i.e. is GOMAXPROCS also set to 1?

A few suggestions:
 - we could mention in `dev bench --help` that by default we run a single instance of each benchmark, and mention that `--test-arg -cpus=X` can be used to change that.
 - is the `--cpus` flag useful with `bench`? If not, we should remove it because it's confusing.
 - in general, the description of `--cpus` is too generic -  "cap the number of cpu cores used". Used for what? For building? For running tests? (does it override GOMAXPROCS?)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115734#-:-Nl0_jnr8dv0Fe5zJS7b:b-fu3tu3)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by rickystewart** [comment]
> What does -cpu do exactly? It definitely runs a single instance of the benchmark instead of N, but is the go process itself restricted to 1 cpu, i.e. is GOMAXPROCS also set to 1?

Check out the [documentation](https://pkg.go.dev/cmd/go/internal/test) for `go test`:

```
-cpu 1,2,4
	    Specify a list of GOMAXPROCS values for which the tests, benchmarks or
	    fuzz tests should be executed. The default is the current value
	    of GOMAXPROCS. -cpu does not apply to fuzz tests matched by -fuzz.
```

So yes, `GOMAXPROCS` is set to 1 in this case.

> we could mention in dev bench --help that by default we run a single instance of each benchmark, and mention that --test-arg -cpus=X can be used to change that.

Done.

> is the --cpus flag useful with bench? If not, we should remove it because it's confusing.

It serves the same purpose as it does with `dev`: restricting the number of cores used for building and testing at the Bazel level. Whatever the test actually does once building is done and the test is triggered is no longer controlled by `--cpus`.

> in general, the description of --cpus is too generic - "cap the number of cpu cores used". Used for what? For building? For running tests? (does it override GOMAXPROCS?)

This complaint has been made before. I'll improve the description.

**Review by RaduBerinde — APPROVED** [review]
:lgtm_strong: 

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115734#-:-Nl5Z96B8ci-MoXdFBbA:b-uwkowd)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rickystewart)

___
*[`pkg/cmd/dev/bench.go` line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115734#-Nl5Yw6k2CtUD8_8vNxF:-Nl5Yw6k2CtUD8_8vNxG:b-8c0v98) ([raw file](https://github.com/cockroachdb/cockroach/blob/59b9b0dbc2b13621d24afbf37333551cad0c486a/pkg/cmd/dev/bench.go#L35)):*
> ```Go
> 		Long:  `Run the specified benchmarks.
> 
> Note that by default we explicitly restrict the benchmark to running on a single core.
> ```

[nit] add `on a single core (i.e. GOMAXPROCS=1)`
___
*[`pkg/cmd/dev/util.go` line 170 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115734#-Nl5Z49mDGndkI7B7x3T:-Nl5Z49mDGndkI7B7x3U:b-ac66ec) ([raw file](https://github.com/cockroachdb/cockroach/blob/59b9b0dbc2b13621d24afbf37333551cad0c486a/pkg/cmd/dev/util.go#L170)):*
> ```Go
> 
> func addCommonBuildFlags(cmd *cobra.Command) {
> 	cmd.Flags().IntVar(&numCPUs, "cpus", 0, "cap the number of CPU cores used for building and testing at the Bazel level (note that this has no impact on GOMAXPROCS or the functionality of any build or test action under the Bazel level.)")
> ```

Awesome, super helpful!

**Comment by RaduBerinde** [comment]
One thing - does the weekly workload that runs the microbenchmarks use dev? We compare results across commits and across branches, they would need to pass --cpu 16 ot whatever to keep things the same.

**Comment by rickystewart** [comment]
> One thing - does the weekly workload that runs the microbenchmarks use dev?

Not to my knowledge. I reviewed the script `build/teamcity/cockroach/nightlies/microbenchmark_weekly.sh` and the corresponding binary `pkg/cmd/roachprod-microbench`. However, I didn't write this code or review it and am not really familiar with it.

**Comment by rickystewart** [comment]
bors r=RaduBerinde

**Pull request merged**
