### PR TITLE
storage: stop modifying requests and returning responses from TxnWaitQueue

### PR DESCRIPTION
**Pull request by nvb**
This PR contains three pieces of cleanup that pave the way for pulling the TxnWaitQueue underneath the upcoming `pkg/storage/concurrency` package. It removes all cases where the queue mandates an update to the PushTxnRequest that entered it. It also removes all cases where the queue could field requests directly and return results for them. This restricts the TxnWaitQueue's interface and allows it to be pushed into the concurrency manager abstraction without bloating this new abstraction.

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm_strong: I quite like this change. It simplifies the role of the txnwait queue nicely. 

>  I ran YCSB A at a few concurrency levels and saw no difference in performance.

That's encouraging enough for me. 

> Reviewed 4 of 4 files at r1, 4 of 4 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43383#-:-LwYU5YL8I_cZu7oBsag:by2r6yv)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/storage/batcheval/cmd_push_txn.go, line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43383#-LwWw8uTAOjKE-K9iO35:-LwWw8uTAOjKE-K9iO36:b-js07t6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6b75ff81ee2cc48f95193863ff79350661804c8/pkg/storage/batcheval/cmd_push_txn.go#L128)):*
> ```Go
> 	now := cArgs.EvalCtx.Clock().Now()
> 	if now.Less(h.Timestamp) {
> 		// The batch's timestamp should have been used to udpate the clock.
> ```

udpate
___
*[pkg/storage/txnwait/queue.go, line 653 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43383#-LwYTwwb8bfTZYRwTvlo:-LwWwfZZ8mB3jvRgS5Ir:b-gs0nf6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e50605d8e5249849c4e6ad472e3db9139342363e/pkg/storage/txnwait/queue.go#L653)):*
> ```Go
> 					)
> 					metrics.DeadlocksTotal.Inc(1)
> 					// TODO(nvanbenschoten): As it, it would make sense to return
> ```

If for whatever reason you back off of the last commit: s/As it/As is/

**Review by nvb — COMMENTED** [review]
TFTR! I actually decided to peel the entire final commit off for now. I don't think it's too much of an issue for the `concurrency` package to have the ability to field requests directly with responses where possible, as long as it's never mutating requests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43383#-:-Lx9W_Fe8FgN1oqrpuyh:b261zbm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/storage/batcheval/cmd_push_txn.go, line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43383#-LwWw8uTAOjKE-K9iO35:-Lx8kwQWByaoJbI25Pt0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6b75ff81ee2cc48f95193863ff79350661804c8/pkg/storage/batcheval/cmd_push_txn.go#L128)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

udpate
</blockquote></details>

Done.
___
*[pkg/storage/txnwait/queue.go, line 653 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43383#-LwYTwwb8bfTZYRwTvlo:-Lx8kx5qAmCJVRDbX8lq:b-a9qft0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e50605d8e5249849c4e6ad472e3db9139342363e/pkg/storage/txnwait/queue.go#L653)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

If for whatever reason you back off of the last commit: s/As it/As is/
</blockquote></details>

Removed the entire commit.

**Review by ajwerner — APPROVED** [review]
> Reviewed 4 of 8 files at r4, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43383)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/storage/txnwait/queue_test.go, line 31 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43383#-LxNPf9u1rLVmkjw5c2B:-LxNPf9u1rLVmkjw5c2C:b-1huxrr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c601328a620faf9d8f198613ec7c86256722ebef/pkg/storage/txnwait/queue_test.go#L31)):*
> ```Go
> 
> func TestShouldPushImmediately(t *testing.T) {
> 	// TODO WIP
> ```

did you want to do anything about this?

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43383)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/storage/txnwait/queue_test.go, line 31 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43383#-LxNPf9u1rLVmkjw5c2B:-LxbU_IR-_ulkUMIKi4g:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c601328a620faf9d8f198613ec7c86256722ebef/pkg/storage/txnwait/queue_test.go#L31)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

did you want to do anything about this?
</blockquote></details>

Done.

**Comment by nvanbenschoten** [comment]
```
F200102 20:05:04.162081 1531172 sqlmigrations/migrations.go:531  [n1] not enough time left on migration lease, terminating for safety
```

Huh, looks like a resurfacing of https://github.com/cockroachdb/cockroach/issues/21444, which we never tracked down but were able to correlate with slow TeamCity workers. We do see some serious slowdown in the logs of this test, like `handle raft ready: 16.5s`.

I'm not able to reproduce with `stress` or `stressrace`, so I'm going to chalk this up to a flake for now.

bors r+

**Comment by nvanbenschoten** [comment]
https://github.com/cockroachdb/cockroach/pull/41482#issuecomment-570344581 just hit the same issue, so something's up, but it's not due to this PR.

**Pull request merged**
