### PR TITLE
exec: support comparisons between all numeric types

### PR DESCRIPTION
**Pull request by rafiss**
The vectorized engine now supports comparisons between floats, ints, and
decimals.

touches #39189

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Very nice work! I think we should address the TODO about reusing the same `tmpDec` to avoid an allocation on each comparison before this merges, but if you push back, I'll be ok with that as well.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39778#-:-Lml8Xv18wBxL8laCvLk:b-2m3g75)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @solongordon)

___
*[pkg/sql/exec/execgen/cmd/execgen/overloads.go, line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39778#-Lml9KUi1Cxknz2Q5PDZ:-Lml9KUi1Cxknz2Q5PD_:bfkvgap) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b3056a262add010b20a1ce30d7db904f4dae959/pkg/sql/exec/execgen/cmd/execgen/overloads.go#L271)):*
> ```Go
> // registerTypeCustomizer registers a particular type customizer to a type, for
> // usage by templates.
> func registerTypeCustomizer(pair coltypePair, customizer typeCustomizer) {
> ```

[nit]: the comment needs an adjustment.
___
*[pkg/sql/exec/execgen/cmd/execgen/overloads.go, line 321 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39778#-Lml9N2i8x6-86wFq3iB:-Lml9N2i8x6-86wFq3iC:bp7nx00) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b3056a262add010b20a1ce30d7db904f4dae959/pkg/sql/exec/execgen/cmd/execgen/overloads.go#L321)):*
> ```Go
> // decimalFloatCustomizer supports mixed type expressions with a float left-hand
> // side and a decimal right-hand side.
> type floatDecimalCustomizer struct{}
> ```

[nit]: `s/decimalFloat/floatDecimal/` (in the comment).
___
*[pkg/sql/exec/execgen/cmd/execgen/overloads.go, line 325 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39778#-Lml9QDzD66mEMeo3wo5:-Lml9QDzD66mEMeo3wo6:b-jzs8u1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b3056a262add010b20a1ce30d7db904f4dae959/pkg/sql/exec/execgen/cmd/execgen/overloads.go#L325)):*
> ```Go
> // decimalIntCustomizer supports mixed type expressions with an int left-hand
> // side and a decimal right-hand side.
> type intDecimalCustomizer struct{}
> ```

ditto (in the comment).
___
*[pkg/sql/exec/execgen/cmd/execgen/overloads.go, line 602 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39778#-Lml9UJrEsK_3PRB5h7O:-Lml9UJrEsK_3PRB5h7P:b3h13wc) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b3056a262add010b20a1ce30d7db904f4dae959/pkg/sql/exec/execgen/cmd/execgen/overloads.go#L602)):*
> ```Go
> 		buf := strings.Builder{}
> 		// todo(rafi): is there a way to avoid an allocating on each comparison?
> 		t := template.Must(template.New("").Parse(`
> ```

Maybe we could use a global variable here that would live in the template that is using the comparison functions? This doesn't sound good though.

Another thing is that maybe we would be ok with defining a global scratch struct that is shared among all templates and is populated into every generated file?
___
*[pkg/sql/exec/execgen/cmd/execgen/overloads.go, line 710 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39778#-Lml8Ltb3OAj05McOPo1:-Lml8Ltb3OAj05McOPo2:b-3cbimr) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b3056a262add010b20a1ce30d7db904f4dae959/pkg/sql/exec/execgen/cmd/execgen/overloads.go#L710)):*
> ```Go
> 
> 	// Use an intCustomizer of appropriate width when widths are the same.
> 	registerTypeCustomizer(coltypePair{coltypes.Int8, coltypes.Int8}, intCustomizer{width: 8})
> ```

[question]: a comparison between ints with different widths is unsupported right now, right?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39778)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon and @yuzefovich)

___
*[pkg/sql/exec/execgen/cmd/execgen/overloads.go, line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39778#-Lml9KUi1Cxknz2Q5PDZ:-LmpSMkpEaB5apVQP7wf:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b3056a262add010b20a1ce30d7db904f4dae959/pkg/sql/exec/execgen/cmd/execgen/overloads.go#L271)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: the comment needs an adjustment.
</blockquote></details>

done
___
*[pkg/sql/exec/execgen/cmd/execgen/overloads.go, line 321 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39778#-Lml9N2i8x6-86wFq3iB:-LmpRjYS1CKFCpcLyzJ6:bwbakze) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b3056a262add010b20a1ce30d7db904f4dae959/pkg/sql/exec/execgen/cmd/execgen/overloads.go#L321)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: `s/decimalFloat/floatDecimal/` (in the comment).
</blockquote></details>

thanks, nice catch
___
*[pkg/sql/exec/execgen/cmd/execgen/overloads.go, line 325 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39778#-Lml9QDzD66mEMeo3wo5:-LmpRkhT0tMSFo1mhI9h:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b3056a262add010b20a1ce30d7db904f4dae959/pkg/sql/exec/execgen/cmd/execgen/overloads.go#L325)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

ditto (in the comment).
</blockquote></details>

done
___
*[pkg/sql/exec/execgen/cmd/execgen/overloads.go, line 602 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39778#-Lml9UJrEsK_3PRB5h7O:-LmpRr4Z-d06YeDla19n:b-lf3wwu) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b3056a262add010b20a1ce30d7db904f4dae959/pkg/sql/exec/execgen/cmd/execgen/overloads.go#L602)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Maybe we could use a global variable here that would live in the template that is using the comparison functions? This doesn't sound good though.

Another thing is that maybe we would be ok with defining a global scratch struct that is shared among all templates and is populated into every generated file?
</blockquote></details>

i was wondering about the global variable approach. i'm not sure if there are any concurrency concerns. i'll think of how we could use a templated scratch struct. even one allocation per batch would be way better than how it is in this revision.
___
*[pkg/sql/exec/execgen/cmd/execgen/overloads.go, line 710 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39778#-Lml8Ltb3OAj05McOPo1:-LmpSnACDZLwz4H53BUW:bbv87lh) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b3056a262add010b20a1ce30d7db904f4dae959/pkg/sql/exec/execgen/cmd/execgen/overloads.go#L710)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[question]: a comparison between ints with different widths is unsupported right now, right?
</blockquote></details>

it is supported -- the loop right above this one handles that. for int comparisons, everything is just casted to int64. i included the same-width customizers for the binary operator overloads and doing overflow checks appropriately.

**Review by jordanlewis — COMMENTED** [review]
Great work. Thanks for doing this. I'd like to see some basic regression tests as well (maybe that's just enabling more logic test configs?).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39778#-:-LmqWMOf9FxjYJmCBCfc:b-hlbk00)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss, @solongordon, and @yuzefovich)

___
*[pkg/sql/exec/execgen/cmd/execgen/overloads.go, line 602 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39778#-Lml9UJrEsK_3PRB5h7O:-LmqRoaK7MSo7TTQHYQ_:b-2rhovv) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b3056a262add010b20a1ce30d7db904f4dae959/pkg/sql/exec/execgen/cmd/execgen/overloads.go#L602)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i was wondering about the global variable approach. i'm not sure if there are any concurrency concerns. i'll think of how we could use a templated scratch struct. even one allocation per batch would be way better than how it is in this revision.
</blockquote></details>

There would definitely be concurrency concerns with that idea. Ideally, we could figure out a way to do as you say and make an allocation per batch. If that was too slow (which I doubt) we could pool the temp decimals into a `sync.Pool` and acquire and release one once per batch. However, I don't see an easy way to make this work - it's challenging to make assumptions about the outer scope of templates in our hacky language. I like the idea about a global scratch struct, I think.

I wouldn't object to seeing the first version of this go in with the poor allocation behavior, though. I think for the rest of this release we'd be wise to focus on breadth rather than performance - as I saw with the hash joiner, even adding a pointless allocation on every single call to the hash function on both probe and build side left the hash joiner in a state that was 10x faster than pre-vectorized.
___
*[pkg/sql/exec/execgen/cmd/execgen/selection_ops_gen.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39778#-LmqSltL-NsxLdPXS3la:-LmqSltL-NsxLdPXS3lb:b-o98h7a) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b3056a262add010b20a1ce30d7db904f4dae959/pkg/sql/exec/execgen/cmd/execgen/selection_ops_gen.go#L31)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/col/coldata"
> 	"github.com/cockroachdb/cockroach/pkg/col/coltypes"
> 	"github.com/cockroachdb/cockroach/pkg/sql/exec/execerror"
> ```

nit: this seems somewhat out of place in this commit? probably doesn't matter though or else the compiler would have complained.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39778)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @rafiss, @solongordon, and @yuzefovich)

___
*[pkg/sql/exec/execgen/cmd/execgen/overloads.go, line 602 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39778#-Lml9UJrEsK_3PRB5h7O:-LmqX9I94oeFvFXH_BfT:brs73zl) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b3056a262add010b20a1ce30d7db904f4dae959/pkg/sql/exec/execgen/cmd/execgen/overloads.go#L602)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

There would definitely be concurrency concerns with that idea. Ideally, we could figure out a way to do as you say and make an allocation per batch. If that was too slow (which I doubt) we could pool the temp decimals into a `sync.Pool` and acquire and release one once per batch. However, I don't see an easy way to make this work - it's challenging to make assumptions about the outer scope of templates in our hacky language. I like the idea about a global scratch struct, I think.

I wouldn't object to seeing the first version of this go in with the poor allocation behavior, though. I think for the rest of this release we'd be wise to focus on breadth rather than performance - as I saw with the hash joiner, even adding a pointless allocation on every single call to the hash function on both probe and build side left the hash joiner in a state that was 10x faster than pre-vectorized.
</blockquote></details>

Yeah, this makes sense.
___
*[pkg/sql/exec/execgen/cmd/execgen/overloads.go, line 710 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39778#-Lml8Ltb3OAj05McOPo1:-LmqXMZo9I7fWSfV_yaW:bo6oaan) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b3056a262add010b20a1ce30d7db904f4dae959/pkg/sql/exec/execgen/cmd/execgen/overloads.go#L710)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it is supported -- the loop right above this one handles that. for int comparisons, everything is just casted to int64. i included the same-width customizers for the binary operator overloads and doing overflow checks appropriately.
</blockquote></details>

Oh yeah, thanks, I missed that.
___
*[pkg/sql/exec/execgen/cmd/execgen/selection_ops_gen.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39778#-LmqSltL-NsxLdPXS3la:-LmqXTpR9I_bnwwxs7V-:b-7fluow) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b3056a262add010b20a1ce30d7db904f4dae959/pkg/sql/exec/execgen/cmd/execgen/selection_ops_gen.go#L31)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: this seems somewhat out of place in this commit? probably doesn't matter though or else the compiler would have complained. 
</blockquote></details>

I think this is needed because we're calling `execerror.NonVectorizedPanic` in the template for some of the customizers.

**Review by rafiss — COMMENTED** [review]
ah yes, i meant to note in the PR comments that i was still working on testing it all.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39778#-:-LmuLPAz35xk4Tmng-1K:b-2yoy2p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @rafiss, @solongordon, and @yuzefovich)

___
*[pkg/sql/exec/execgen/cmd/execgen/selection_ops_gen.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39778#-LmqSltL-NsxLdPXS3la:-LmuLEwv8oLoXwVJytYb:bkvi4xp) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b3056a262add010b20a1ce30d7db904f4dae959/pkg/sql/exec/execgen/cmd/execgen/selection_ops_gen.go#L31)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think this is needed because we're calling `execerror.NonVectorizedPanic` in the template for some of the customizers.
</blockquote></details>

yeah, the import is required for the reason Yahor said.

**Comment by rafiss** [comment]
This is ready for another review.

**Review by jordanlewis — APPROVED** [review]
:lgtm:

I think we could probably manage to accomplish more and better testing with some kind of randomized strategy akin to what @mjibson was mentioning in Slack today, but that can wait until later I think.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39778#-:-Ln-auQhDon_3GgJI_sJ:b2r6ysd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @rafiss, @solongordon, and @yuzefovich)

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39778)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @rafiss, @solongordon, and @yuzefovich)

___
*[pkg/sql/exec/execgen/cmd/execgen/overloads.go, line 602 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39778#-Lml9UJrEsK_3PRB5h7O:-LnDXb-s7ht4W8m27UZc:b-us8qr3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b3056a262add010b20a1ce30d7db904f4dae959/pkg/sql/exec/execgen/cmd/execgen/overloads.go#L602)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Yeah, this makes sense.
</blockquote></details>

is assuming things about the outer scope of templates much different than what we currently do, where templates assume that the correct packages are imported by the outer scope.

it doesn't seem so to me, so maybe the approach i'll take later on is to just assume that the global "decimal pool" struct/package is in scope in this templated code.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39778#-:-LnDcUXp31WaJ0XG9BHr:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @rafiss, @solongordon, and @yuzefovich)

___
*[pkg/sql/exec/overloads_test.go, line 155 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39778#-LnDbYuyDaesg00iNL62:-LnDbYuyDaesg00iNL63:bj5qucl) ([raw file](https://github.com/cockroachdb/cockroach/blob/6da62eac5a369003901eb836520783d7f9d48c64/pkg/sql/exec/overloads_test.go#L155)):*
> ```Go
> }
> 
> func TestFloatComparison(t *testing.T) {
> ```

[nit]: it seems like `TestIntComparison` is missing (or at least a comment is about why the test is missing).
___
*[pkg/sql/exec/execgen/cmd/execgen/overloads_test_utils_gen.go, line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39778#-LnDbxcSDcznzOZFP7Du:-LnDbxcSDcznzOZFP7Dv:b30lpo0) ([raw file](https://github.com/cockroachdb/cockroach/blob/6da62eac5a369003901eb836520783d7f9d48c64/pkg/sql/exec/execgen/cmd/execgen/overloads_test_utils_gen.go#L23)):*
> ```Go
> import (
> 	"bytes"
>   "math"
> ```

[super nit]: seems like `math` package is misaligned.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39778)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @rafiss, @solongordon, and @yuzefovich)

___
*[pkg/sql/exec/overloads_test.go, line 155 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39778#-LnDbYuyDaesg00iNL62:-LnDd2MKETbYw0zKtZ6U:b-3bccbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/6da62eac5a369003901eb836520783d7f9d48c64/pkg/sql/exec/overloads_test.go#L155)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: it seems like `TestIntComparison` is missing (or at least a comment is about why the test is missing).
</blockquote></details>

initially i had intentionally omitted it since int comparison is tested by the other tests. but now that i think about it, we have different code for int left-hand-side versus right, so i should have that test as well.
___
*[pkg/sql/exec/execgen/cmd/execgen/overloads_test_utils_gen.go, line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39778#-LnDbxcSDcznzOZFP7Du:-LnDcs5a6frVx-6rTeDM:b-jvudc9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6da62eac5a369003901eb836520783d7f9d48c64/pkg/sql/exec/execgen/cmd/execgen/overloads_test_utils_gen.go#L23)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[super nit]: seems like `math` package is misaligned.
</blockquote></details>

done, it was a tab vs space issue

**Pull request merged**
