### PR TITLE
sql: reuse cluster for all TestTrace sub-tests

### LINKED ISSUE #17798: sql: TestTrace takes >30s
This is likely because we're creating a lot of clusters and that's somehow slow. There's no good reason for this, it's probably because we're waiting for full replication or something like that. Seems good to speed this up a bit.

```
$make test PKG=./pkg/sql TESTS=TestTrace TESTFLAGS=-v
...
--- PASS: TestTrace (34.55s)
	test_log_scope.go:78: test logs captured to: /var/folders/yy/4q8rrssd27vdgbr59w9qbffr0000gn/T/logTestTrace100207672
	test_log_scope.go:61: use -show-logs to present logs inline
    --- PASS: TestTrace/Session (8.75s)
        --- PASS: TestTrace/Session/TracingOff (3.73s)
            --- PASS: TestTrace/Session/TracingOff/node-0 (0.01s)
            --- PASS: TestTrace/Session/TracingOff/node-1 (0.02s)
            --- PASS: TestTrace/Session/TracingOff/node-2 (0.05s)
        --- PASS: TestTrace/Session/TracingOn (5.02s)
            --- PASS: TestTrace/Session/TracingOn/node-0 (0.02s)
            --- PASS: TestTrace/Session/TracingOn/node-1 (0.03s)
            --- PASS: TestTrace/Session/TracingOn/node-2 (0.10s)
    --- PASS: TestTrace/SessionDistSQL (8.14s)
        --- PASS: TestTrace/SessionDistSQL/TracingOff (4.04s)
            --- PASS: TestTrace/SessionDistSQL/TracingOff/node-0 (0.07s)
            --- PASS: TestTrace/SessionDistSQL/TracingOff/node-1 (0.08s)
            --- PASS: TestTrace/SessionDistSQL/TracingOff/node-2 (0.02s)
        --- PASS: TestTrace/SessionDistSQL/TracingOn (4.10s)
            --- PASS: TestTrace/SessionDistSQL/TracingOn/node-0 (0.01s)
            --- PASS: TestTrace/SessionDistSQL/TracingOn/node-1 (0.02s)
            --- PASS: TestTrace/SessionDistSQL/TracingOn/node-2 (0.04s)
    --- PASS: TestTrace/ShowTraceFor (9.24s)
        --- PASS: TestTrace/ShowTraceFor/TracingOff (4.37s)
            --- PASS: TestTrace/ShowTraceFor/TracingOff/node-0 (0.01s)
            --- PASS: TestTrace/ShowTraceFor/TracingOff/node-1 (0.02s)
            --- PASS: TestTrace/ShowTraceFor/TracingOff/node-2 (0.04s)
        --- PASS: TestTrace/ShowTraceFor/TracingOn (4.87s)
            --- PASS: TestTrace/ShowTraceFor/TracingOn/node-0 (0.07s)
            --- PASS: TestTrace/ShowTraceFor/TracingOn/node-1 (0.08s)
            --- PASS: TestTrace/ShowTraceFor/TracingOn/node-2 (0.09s)
    --- PASS: TestTrace/ShowTraceForSplitBatch (8.42s)
        --- PASS: TestTrace/ShowTraceForSplitBatch/TracingOff (3.67s)
            --- PASS: TestTrace/ShowTraceForSplitBatch/TracingOff/node-0 (0.03s)
            --- PASS: TestTrace/ShowTraceForSplitBatch/TracingOff/node-1 (0.06s)
            --- PASS: TestTrace/ShowTraceForSplitBatch/TracingOff/node-2 (0.04s)
        --- PASS: TestTrace/ShowTraceForSplitBatch/TracingOn (4.75s)
            --- PASS: TestTrace/ShowTraceForSplitBatch/TracingOn/node-0 (0.03s)
            --- PASS: TestTrace/ShowTraceForSplitBatch/TracingOn/node-1 (0.05s)
            --- PASS: TestTrace/ShowTraceForSplitBatch/TracingOn/node-2 (0.04s)
PASS
ok  	github.com/cockroachdb/cockroach/pkg/sql	34.668s
```

### PR DESCRIPTION
**Pull request by petermattis**
Cluster setup is taking 3-4s per sub-test. Creating a new cluster on
each sub-test was causing TestTrace overall to take ~30s. Switch to
sharing the same cluster amongst all the sub-tests by ensuring the each
sub-test gets a new "session".

Fixes #17798

### CODE REVIEW

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18238#-:-KtK-KwSDNefcSKnQdFQ:bnfp4nl)*

**Comment by andreimatei** [comment]
Thanks for doing this Peter. I have also noticed that this test is slow and it bothered me.
But is #17798 really fixed? The biggest problem discussed in that issue is that the table split takes seconds. Did you ever figure out why that is? If not, I think the issue should stay open for that investigation.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/trace_test.go, line 206 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18238#-KtK5owSq1cf6NJwKg99:-KtK5owSq1cf6NJwKg9A:b-o7t691) ([raw file](https://github.com/cockroachdb/cockroach/blob/483629f855c6d7bb8035681eed80f08cda6242ef/pkg/sql/trace_test.go#L206)):*
> ```Go
> 							// cluster.ServerConn() so that per-session state has a known
> 							// value.
> 							pgURL, cleanup := sqlutils.PGUrl(
> ```

I don't understand this comment. Which "per-session state" is important for this test? What's wrong with `cluster.ServerConn()` exactly?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18238#-:-KtK60laW8F6KrSih1kR:b-skozw4)*

**Comment by petermattis** [comment]
Well, in my opinion the biggest problem in #17798 is the total test run time which I think this fixes. I'll file another issue about the slow split and investigate today.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/trace_test.go, line 206 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18238#-KtK5owSq1cf6NJwKg99:-KtMZUxBW3SaMyy-3wSj:b1i70r9) ([raw file](https://github.com/cockroachdb/cockroach/blob/483629f855c6d7bb8035681eed80f08cda6242ef/pkg/sql/trace_test.go#L206)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't understand this comment. Which "per-session state" is important for this test? What's wrong with `cluster.ServerConn()` exactly?
</blockquote></details>

The only bit is the `SELECT COUNT(1) FROM crdb_internal.session_trace` check that the trace is empty. Pulling that out of the sub-test seems reasonable, but I'll leave that to you as my initial attempt to do so resulted in other breakage. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18238#-:-KtM_rHI0IjoxwVoiWO4:bt7herz)*

**Comment by andreimatei** [comment]
LGTM

>  I'll file another issue about the slow split and investigate today.

respect

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/trace_test.go, line 206 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18238#-KtK5owSq1cf6NJwKg99:-KtMgnHVlXdOwJPo6mel:b3lanfr) ([raw file](https://github.com/cockroachdb/cockroach/blob/483629f855c6d7bb8035681eed80f08cda6242ef/pkg/sql/trace_test.go#L206)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The only bit is the `SELECT COUNT(1) FROM crdb_internal.session_trace` check that the trace is empty. Pulling that out of the sub-test seems reasonable, but I'll leave that to you as my initial attempt to do so resulted in other breakage. 
</blockquote></details>

OK, but put that in the TODO too: 
```
// TODO(andrei): Pull the check for an empty session_trace out of
// the sub-tests so we can use cluster.ServerConn(i) here.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18238#-:-KtMhBfXHQQ4yxQVDFx_:ba7q1iv)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/trace_test.go, line 206 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18238#-KtK5owSq1cf6NJwKg99:-KtMhYpQsqkq4USPtU7E:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/483629f855c6d7bb8035681eed80f08cda6242ef/pkg/sql/trace_test.go#L206)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

OK, but put that in the TODO too: 
```
// TODO(andrei): Pull the check for an empty session_trace out of
// the sub-tests so we can use cluster.ServerConn(i) here.
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18238)*

**Pull request merged**
