### PR TITLE
sql: implement SHOW DEFAULT PRIVILEGES

### LINKED ISSUE #67381: sql: implement show default privileges
See: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20210527_default_privileges.md#show-default-privileges

This goes hand in hand with implementing `pg_default_acl`

Epic CRDB-2586

### PR DESCRIPTION
**Pull request by RichardJCai**
Release note (sql change):
Support SHOW DEFAULT PRIVILEGES
and SHOW DEFAULT PRIVILEGES FOR ROLE ...

If a role(s) is not specified, default privileges
are shown for the current role.

SHOW DEFAULT PRIVILEGES returns the following columns
schema_name | role | object_type | grantee | privilege_type

Release note (sql change):
Add crdb_internal.default_privileges table

Resolves https://github.com/cockroachdb/cockroach/issues/67381

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67997#-:-MfJg8aX3vkeLTWHtiul:b-7nbn20)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @RichardJCai)

___
*[pkg/sql/sem/tree/alter_default_privileges.go, line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67997#-MfJfRaD8iQGGX_NRG43:-MfJfRaE8UKzdzTFy6qP:bw0jfmt) ([raw file](https://github.com/cockroachdb/cockroach/blob/f095b2552fc2acb8dcb24841096ae01a4d6f74f4/pkg/sql/sem/tree/alter_default_privileges.go#L152)):*
> ```Go
> // NameListToUsernames converts a NameList containing SQL input of usernames,
> // normalizes the names and returns them as a list of SQLUsernames.
> func NameListToUsernames(roles NameList) ([]security.SQLUsername, error) {
> ```

ah, nice this function is definitely good

nit: i think this would fit better in name_part.go (maybe make the `NameList` the receiver)

also, let's do a cleanup PR after this that makes the other conversions like this use this function (the ones i added in GRANT/REVOKE). let met know if you can do the PR, but if not, i don't mind doing it after this merges.

**Review by arulajmani — CHANGES_REQUESTED** [review]
If I were a user, I'd find the `NULLS` in `SHOW DEFAULT PRIVILEGES` output confusing. Should we instead offer:

`SHOW DEFAULT PRIVILEGES [FOR DATABASE|SCHEMA name] [FOR ROLE ....]` instead? If the `FOR DATABASE/SCHEMA` is omitted, we can default to the current database's default privileges.

> Reviewed 4 of 4 files at r1, 12 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67997#-:-MfJjn0J4TiKGCEu9z5r:bm8is5v)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[pkg/sql/crdb_internal.go, line 4868 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67997#-MfJdVDS1PdDH6QFcGtA:-MfJdVDS1PdDH6QFcGtB:b2118v3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c488f4daccd4aa1be34ddc23abeb173997f45265/pkg/sql/crdb_internal.go#L4868)):*
> ```Go
> 								if err := addRow(
> 									tree.NewDString(descriptor.GetName()),
> 									tree.DNull, /* schema is currently always nil. See: #67376 */
> ```

Might be worth adding a comment in code and the release note saying that `NULL` has an explicit meaning here for database level default privileges. 
___
*[pkg/sql/crdb_internal.go, line 4879 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67997#-MfJezYN5jkxfF2kREWq:-MfJezYN5jkxfF2kREWr:b-tarxx8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c488f4daccd4aa1be34ddc23abeb173997f45265/pkg/sql/crdb_internal.go#L4879)):*
> ```Go
> 						}
> 					}
> 				}
> ```

So this whole `PUBLIC` role having `USAGE` on `TYPES` by default is not going to be 
___
*[pkg/sql/logictest/testdata/logic_test/crdb_internal_default_privileges, line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67997#-MfJfHD3E3YYkOckQSqC:-MfJfHD3E3YYkOckQSqD:b-l0rtfk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c488f4daccd4aa1be34ddc23abeb173997f45265/pkg/sql/logictest/testdata/logic_test/crdb_internal_default_privileges#L3)):*
> ```
> statement ok
> ALTER DEFAULT PRIVILEGES GRANT SELECT ON TABLES TO PUBLIC;
> ALTER DEFAULT PRIVILEGES GRANT USAGE ON TYPES TO PUBLIC;
> ```

Might be worth adding a `select * from crdb_internal.default_privileges` before granting `USAGE` to public on types as well to codify our handling of that case. 
___
*[pkg/sql/logictest/testdata/logic_test/crdb_internal_default_privileges, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67997#-MfJh0nu5DcVp-dSxJ-H:-MfJh0nu5DcVp-dSxJ-I:bfbr7lc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c488f4daccd4aa1be34ddc23abeb173997f45265/pkg/sql/logictest/testdata/logic_test/crdb_internal_default_privileges#L29)):*
> ```
> 
> query TTTTTT colnames,rowsort
> SELECT * FROM crdb_internal.default_privileges
> ```

nit: Can we put a filter on `grantee=foo OR grantee=bar` here?
___
*[pkg/sql/logictest/testdata/logic_test/crdb_internal_default_privileges, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67997#-MfJhF0O3vJFEI7nCVML:-MfJhF0O3vJFEI7nCVMM:bv7srsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c488f4daccd4aa1be34ddc23abeb173997f45265/pkg/sql/logictest/testdata/logic_test/crdb_internal_default_privileges#L55)):*
> ```
> 
> query TTTTTT colnames,rowsort
> SELECT * FROM crdb_internal.default_privileges
> ```

nit: Same as above, let's put a filter on `role == bar || role == foo` here as well? I think it'll make the test a bit more readable (here, and maybe even a couple places below)
___
*[pkg/sql/sem/tree/alter_default_privileges.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67997#-MfJZuNv2sP3JCIJlvAu:-MfJZuNv2sP3JCIJlvAv:blhu4fc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c488f4daccd4aa1be34ddc23abeb173997f45265/pkg/sql/sem/tree/alter_default_privileges.go#L83)):*
> ```Go
> 		return "schemas"
> 	default:
> 		panic(fmt.Sprintf("unknown AlterDefaultPrivilegesTargetObject value: %d", t))
> ```

We should return an assertion failure instead of panicking here.

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67997)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[pkg/sql/crdb_internal.go, line 4879 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67997#-MfJezYN5jkxfF2kREWq:-MfJkURODKSWNhSI23B4:bv52zb4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c488f4daccd4aa1be34ddc23abeb173997f45265/pkg/sql/crdb_internal.go#L4879)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

So this whole `PUBLIC` role having `USAGE` on `TYPES` by default is not going to be 
</blockquote></details>

Oops unfinished thought -- meant to write "is not going to be introspect-able"

**Review by RichardJCai — COMMENTED** [review]
I think removing the null schema is a good idea when we don't specify the database.

> we can default to the current database's default privileges. 
Agreed, this is what the current behaviour is, I want the SHOW command to be as similar as possible to the ALTER DEFAULT PRIVILEGES command

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67997#-:-MfYV2wCAiRF8ZuGhiTb:b-eu69zl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @rafiss)

___
*[pkg/sql/crdb_internal.go, line 4868 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67997#-MfJdVDS1PdDH6QFcGtA:-MfYVbLWEQh1OKJACzX3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c488f4daccd4aa1be34ddc23abeb173997f45265/pkg/sql/crdb_internal.go#L4868)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Might be worth adding a comment in code and the release note saying that `NULL` has an explicit meaning here for database level default privileges. 
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 4879 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67997#-MfJezYN5jkxfF2kREWq:-MfYVblN1QFUL0GtYoni:b-x4q1fw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c488f4daccd4aa1be34ddc23abeb173997f45265/pkg/sql/crdb_internal.go#L4879)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Oops unfinished thought -- meant to write "is not going to be introspect-able"
</blockquote></details>

We still need to iron out this behaviour. `USAGE` on `TYPES` isn't introspectable in PG even after explicitly granting it.
___
*[pkg/sql/logictest/testdata/logic_test/crdb_internal_default_privileges, line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67997#-MfJfHD3E3YYkOckQSqC:-MfYW7mK7um7QYZxvGj7:b-jffgmw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c488f4daccd4aa1be34ddc23abeb173997f45265/pkg/sql/logictest/testdata/logic_test/crdb_internal_default_privileges#L3)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Might be worth adding a `select * from crdb_internal.default_privileges` before granting `USAGE` to public on types as well to codify our handling of that case. 
</blockquote></details>

This case still isn't correctly handled in CRDB. In PG, this privilege wouldn't show up - explicitly granting `USAGE` on `TYPES` does not create an entry in the `pg_default_acl` table, signifying the absence of the privilege / entry is important rather than having the entry show. 

I think us allowing it to be specifically granted and adding an entry is likely not the way we want to move forward. Sucks but I think we'll have to add logic to handle this case.

I'll handle it in https://github.com/cockroachdb/cockroach/issues/67377
___
*[pkg/sql/logictest/testdata/logic_test/crdb_internal_default_privileges, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67997#-MfJh0nu5DcVp-dSxJ-H:-MfYWoO7BhDHyOU9x-AB:bf6x2s5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c488f4daccd4aa1be34ddc23abeb173997f45265/pkg/sql/logictest/testdata/logic_test/crdb_internal_default_privileges#L29)):*
> grantee=foo OR grantee=bar
Done
___
*[pkg/sql/logictest/testdata/logic_test/crdb_internal_default_privileges, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67997#-MfJhF0O3vJFEI7nCVML:-MfYWqbCCLYS90VE1Vq3:b-aoqij2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c488f4daccd4aa1be34ddc23abeb173997f45265/pkg/sql/logictest/testdata/logic_test/crdb_internal_default_privileges#L55)):*
> role == bar || role == foo
Done
___
*[pkg/sql/sem/tree/alter_default_privileges.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67997#-MfJZuNv2sP3JCIJlvAu:-MfYY-rE4lLUsOt61VPC:b-40l3oi) ([raw file](https://github.com/cockroachdb/cockroach/blob/c488f4daccd4aa1be34ddc23abeb173997f45265/pkg/sql/sem/tree/alter_default_privileges.go#L83)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

We should return an assertion failure instead of panicking here. 
</blockquote></details>

I've changed it to panic an assertion error instead. 
I don't think it's clean to make this `.String()` function to return an error but also it's a regular pattern in our codebase already to panic assertion errors in switch statements like this.
___
*[pkg/sql/sem/tree/alter_default_privileges.go, line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67997#-MfJfRaD8iQGGX_NRG43:-MfYXKUDBxk0PqBLy9Ka:bgq0sm0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f095b2552fc2acb8dcb24841096ae01a4d6f74f4/pkg/sql/sem/tree/alter_default_privileges.go#L152)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ah, nice this function is definitely good

nit: i think this would fit better in name_part.go (maybe make the `NameList` the receiver)

also, let's do a cleanup PR after this that makes the other conversions like this use this function (the ones i added in GRANT/REVOKE). let met know if you can do the PR, but if not, i don't mind doing it after this merges.
</blockquote></details>

Sounds good to me I can do the cleanup.

**Review by arulajmani — APPROVED** [review]
:lgtm: 

I think the release note on your second commit needs an update now. 

> Reviewed 10 of 15 files at r3, 17 of 17 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67997#-:-MfnvEBSACaGoBxAR3SQ:b-6dr40q)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/sql/crdb_internal.go, line 4879 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67997#-MfJezYN5jkxfF2kREWq:-Mfnr82c5ZFbMBNg4unh:baq2aet) ([raw file](https://github.com/cockroachdb/cockroach/blob/c488f4daccd4aa1be34ddc23abeb173997f45265/pkg/sql/crdb_internal.go#L4879)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

We still need to iron out this behaviour. `USAGE` on `TYPES` isn't introspectable in PG even after explicitly granting it.
</blockquote></details>

Yeah, I think we've had a few more conversations about this offline so let's make sure to come back and tackle it hear once we resolve how we're tackling these "default" cases. 
___
*[pkg/sql/logictest/testdata/logic_test/crdb_internal_default_privileges, line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67997#-MfJfHD3E3YYkOckQSqC:-MfnsO4mALIcQ6gj7eOS:bnf96vx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c488f4daccd4aa1be34ddc23abeb173997f45265/pkg/sql/logictest/testdata/logic_test/crdb_internal_default_privileges#L3)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

This case still isn't correctly handled in CRDB. In PG, this privilege wouldn't show up - explicitly granting `USAGE` on `TYPES` does not create an entry in the `pg_default_acl` table, signifying the absence of the privilege / entry is important rather than having the entry show. 

I think us allowing it to be specifically granted and adding an entry is likely not the way we want to move forward. Sucks but I think we'll have to add logic to handle this case.

I'll handle it in https://github.com/cockroachdb/cockroach/issues/67377
</blockquote></details>

Yeah, I wasn't suggesting we have to handle it in this PR, I was just wondering if it's worth adding a test here which codifies the current behavior with a comment. Your call.

**Review by RichardJCai — COMMENTED** [review]
Fixed commit message

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67997#-:-MgBy-o19Az90efDISo8:b-csvk0h)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rafiss and @RichardJCai)

**Comment by RichardJCai** [comment]
TFTRs!
bors r+

**Comment by RichardJCai** [comment]
Looks like it flaked
bors r+

**Pull request merged**
