### PR TITLE
ci,lint: update to latest `honnef.co/go/tools`

### LINKED ISSUE #103048: build,lint: upgrade to latest honnef.co/go/tools
[v0.4.0](https://github.com/dominikh/go-tools/releases/tag/2023.1) contains a completely new implementation of the unused check that is supposed to fix false positives including generics-related fixes. We should jump right to v.0.4.3.

The unused lint functionality we patched into `rules_go` probably needs to be updated as well given U1000 was rewritten from the ground up.

When making this change we must ensure that it works cleanly under remote execution.

Jira issue: CRDB-27812

Epic CRDB-8308

### PR DESCRIPTION
**Pull request by rickystewart**
Also use the upstream `unused` binary rather than our hacked-in support
for the `Unused lint`. This will run as part of the `lint` step.

Closes https://github.com/cockroachdb/cockroach/issues/103048.

Epic: CRDB-8308
Releae note: None

### CODE REVIEW

**Comment by rickystewart** [comment]
(First commit from #104892)

**Review by rail — APPROVED** [review]

**Comment by rickystewart** [comment]
Follow-up: #105053

**Comment by rickystewart** [comment]
bors r=rail

**Comment by rickystewart** [comment]
bors r=rail

**Pull request merged**
