### PR TITLE
sql/rowexec: delete indexSkipTableReader

### PR DESCRIPTION
**Pull request by andreimatei**
This processor is not used. It was implemented for #24584, but the PR to
start planning it stalled since Ridwan left, a year ago (#39668).
This guy is marginally in my way, and, worse, it's dead code. Unless
someone promises to finish that PR imminently :).

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
It is something we want to implement at some point, but I guess we can get it from the git history.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51178#-:-MBkbDDHEV6WsGm5I6do:b5jhd4o)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rohany)

**Review by andreimatei — COMMENTED** [review]
Right. The code needed to be updated in the past, and now I need to update it some more. I think at this point the burden should shift to the future implementor of the respective feature.
This processor is one of the few that interacts directly with KV, which makes it more likely to need maintenance.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51178#-:-MBkcICsEjYC34-aIj0P:beow1xf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany)

**Comment by rohany** [comment]
LGTM

F for the index skip table reader

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51178#-:-MBpMqOl3QldKTF5LaCV:b-616sc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany)

**Pull request merged**
