### PR TITLE
rangefeed: updates to rangefeed test helpers 

### PR DESCRIPTION
**Pull request by rharding6373**
This PR moves some rangefeed test helpers into a separate file so some
can be exported.

Epic: None

Release note: None

### CODE REVIEW

**Review by wenyihu6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129507)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rharding6373)

___
*[`pkg/kv/kvserver/rangefeed/event_size_test.go` line 283 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129507#-O4x9l_wEuUDZnveT86C:-O4x9l_wEuUDZnveT86D:bjcnk3k) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2528b19b9d66bca44c9787f74599fa81972428b/pkg/kv/kvserver/rangefeed/event_size_test.go#L283)):*
> ```Go
> 
> func generateRandomizedSpan(rand *rand.Rand) roachpb.RSpan {
> 	startKey, endKey, _ := generateStartAndEndKey(rand, 0)
> ```

nit: It looks like this function `generateStartAndEndKey` at this commit does not take in the k int as a parameter yet. We could merge the two commits together. Or if you don't mind the extra work, we can make sure the first commit only moves the functions but does not change this. 
___
*[`pkg/kv/kvserver/rangefeed/event_size_test.go` line 291 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129507#-O4xADPM4CxeZ17EM9Uf:-O4xADPM4CxeZ17EM9Ug:b-nl86rb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2528b19b9d66bca44c9787f74599fa81972428b/pkg/kv/kvserver/rangefeed/event_size_test.go#L291)):*
> ```Go
> 
> func generateRandomTestData(rand *rand.Rand) testData {
> 	startKey, endkey, _ := generateStartAndEndKey(rand, 0)
> ```

nit: I would prefer if we can have another helper function that does not take in the extra 0 and also does not return the third return values since the additional argument doesn't seem to be used in this package. Something like 

```
func generateStartAndEndKeyAboveK(rand *rand.Rand, k int) (roachpb.Key, roachpb.Key, int) {}

func generateStartAndEndKey(rand *rand.Rand) (roachpb.Key, roachpb.Key) {
startKey, endkey, _ := generateStartAndEndKey(rand, 0)
return startKey, endKey 
}
```
___
*[`pkg/kv/kvserver/rangefeed/event_size_test.go` line 297 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129507#-O4xAyWG4h9XzWCylXtS:-O4xAyWG4h9XzWCylXtT:bqmxnc9) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2528b19b9d66bca44c9787f74599fa81972428b/pkg/kv/kvserver/rangefeed/event_size_test.go#L297)):*
> ```Go
> 		span:             generateRandomizedSpan(rand).AsRawSpanWithNoLocals(),
> 		key:              generateRandomizedBytes(rand),
> 		timestamp:        GenerateRandomizedTs(rand, 100),
> ```

nit: could we rename this parameter to something like maxTs and add /*maxTs*/ here?

**Review by rharding6373 — COMMENTED** [review]
TFTR! PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129507#-:-O4xKmwMBRPUx5JUFWG5:b-qozhfh)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @wenyihu6)

___
*[`pkg/kv/kvserver/rangefeed/event_size_test.go` line 283 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129507#-O4x9l_wEuUDZnveT86C:-O4xItds1jAyByXJarW6:b8kd2as) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2528b19b9d66bca44c9787f74599fa81972428b/pkg/kv/kvserver/rangefeed/event_size_test.go#L283)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

nit: It looks like this function `generateStartAndEndKey` at this commit does not take in the k int as a parameter yet. We could merge the two commits together. Or if you don't mind the extra work, we can make sure the first commit only moves the functions but does not change this.
</blockquote></details>

Whoops, missed these when I moved these functions back. They're in their own commit now.
___
*[`pkg/kv/kvserver/rangefeed/event_size_test.go` line 291 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129507#-O4xADPM4CxeZ17EM9Uf:-O4xKF1t892unNGaJ22P:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2528b19b9d66bca44c9787f74599fa81972428b/pkg/kv/kvserver/rangefeed/event_size_test.go#L291)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

nit: I would prefer if we can have another helper function that does not take in the extra 0 and also does not return the third return values since the additional argument doesn't seem to be used in this package. Something like 

```
func generateStartAndEndKeyAboveK(rand *rand.Rand, k int) (roachpb.Key, roachpb.Key, int) {}

func generateStartAndEndKey(rand *rand.Rand) (roachpb.Key, roachpb.Key) {
startKey, endkey, _ := generateStartAndEndKey(rand, 0)
return startKey, endKey 
}
```
</blockquote></details>

Good idea. Done.
___
*[`pkg/kv/kvserver/rangefeed/event_size_test.go` line 297 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129507#-O4xAyWG4h9XzWCylXtS:-O4xKkii2xnpCcBlQjnM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2528b19b9d66bca44c9787f74599fa81972428b/pkg/kv/kvserver/rangefeed/event_size_test.go#L297)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

nit: could we rename this parameter to something like maxTs and add /*maxTs*/ here?
</blockquote></details>

Done.

**Review by wenyihu6 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129507#-:-O4xPmz6-sAi5ICapqdJ:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained

**Review by wenyihu6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129507)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rharding6373)

___
*[`-- commits` line 17 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/129507#-O4xQ1u49G-1v5RZKlBu):*
nit: looks like this commit doesn't have epic and release notes: none.

**Review by rharding6373 — COMMENTED** [review]
TFTR!

bors r=wenyihu6

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129507#-:-O4xT4eT89U--XxZGbIZ:b-4zg106)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @wenyihu6)

___
*[`-- commits` line 17 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/129507#-O4xQ1u49G-1v5RZKlBu):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

nit: looks like this commit doesn't have epic and release notes: none.
</blockquote></details>

Done

**Pull request merged**
