### PR TITLE
sql: support crdb_internal.ranges{_no_leases} for secondary tenants

### PR DESCRIPTION
**Pull request by aayushshah15**
This PR makes `crdb_internal.ranges{_no_leases}` and `SHOW RANGES`
work for secondary tenants. It achieves this by leveraging the
`DistSender` on the secondary tenant to perform privileged meta2
lookups over the tenant `Connector` boundary.

Release note (sql change): `crdb_internal.ranges{_no_leases}` and 
`SHOW RANGES` statements now work on secondary tenants.

Epic: https://cockroachlabs.atlassian.net/browse/CRDB-14522

### CODE REVIEW

**Review by knz — COMMENTED** [review]
This is good.
LGTM with nits.

> Reviewed 2 of 2 files at r1, 11 of 11 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92029#-:-NH4R8yW4ezLU8JBdBec:bqp3g9g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92029#-NH4Pwmw669PiEqvPILf):*
No objection to this fix, but does it belong to this PR?
___
*[`pkg/sql/crdb_internal.go` line 3668 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92029#-NH4Qc_zE3riXip7VBmh:-NH4Qc_zE3riXip7VBmi:bks5k1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4eb5fcabe181d9214a9390b3f53ba5108d91b173/pkg/sql/crdb_internal.go#L3668)):*
> ```Go
> 				return nil, nil
> 			}
> 			defer ri.Next(ctx)
> ```

This is elegant but it feels like magic. Please add a comment above the function definition that explains how the iteration works.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/crdb_internal_tenant` line 307 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92029#-NH4QrMN4rJHney0ifno:-NH4QrMN4rJHney0ifnp:bjork14) ([raw file](https://github.com/cockroachdb/cockroach/blob/4eb5fcabe181d9214a9390b3f53ba5108d91b173/pkg/ccl/logictestccl/testdata/logic_test/crdb_internal_tenant#L307)):*
> ```
> SELECT range_id, start_pretty, end_pretty, lease_holder FROM crdb_internal.ranges
> 
> 53  /Tenant/10  /Max  1
> ```

I appreciate this is not directly a result of your change, but having `/Max` as end key is problematic. 

What would it take for this to be `/Tenant/10/<endprefix>` or something similar? If it's a simple change in your PR I'll take it, otherwise please file an issue so we can track this.

**Comment by knz** [comment]
@ecwall would you like to review this PR as well? I believe there are a few things in there you'll find interesting to learn.

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92029)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @knz, and @smg260)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92029#-NH4Pwmw669PiEqvPILf):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

No objection to this fix, but does it belong to this PR?
</blockquote></details>

`cockroach demo` stalls without this fix since it relies on this logic during startup.
___
*[`pkg/sql/crdb_internal.go` line 3668 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92029#-NH4Qc_zE3riXip7VBmh:-NH5bFF7E1G6CdNugPIs:b-1nlsx0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4eb5fcabe181d9214a9390b3f53ba5108d91b173/pkg/sql/crdb_internal.go#L3668)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

This is elegant but it feels like magic. Please add a comment above the function definition that explains how the iteration works.
</blockquote></details>

Let me know if that comment doesn't quite cover it. 
___
*[`pkg/ccl/logictestccl/testdata/logic_test/crdb_internal_tenant` line 307 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92029#-NH4QrMN4rJHney0ifno:-NH5Ab5PC7UPJLPoasDO:b7koi8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/4eb5fcabe181d9214a9390b3f53ba5108d91b173/pkg/ccl/logictestccl/testdata/logic_test/crdb_internal_tenant#L307)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I appreciate this is not directly a result of your change, but having `/Max` as end key is problematic. 

What would it take for this to be `/Tenant/10/<endprefix>` or something similar? If it's a simple change in your PR I'll take it, otherwise please file an issue so we can track this.
</blockquote></details>

Filed: https://github.com/cockroachdb/cockroach/issues/92072

**Comment by ecwall** [comment]
Moving work to https://github.com/cockroachdb/cockroach/pull/92131

**Pull request closed without merging**
