### PR TITLE
sql: add support for executing simple UDFs

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: fix outdated comment in execbuilder

Release note: None

#### sql: add helpful eval_gen instructions

Release note: None

#### sql: add support for executing simple UDFs

This commit adds basic support for executing single-statement,
zero-argument, scalar user-defined functions. It sets up some basic
components that are needed. There's quite a few TODOs scattered
throughout the commit that will be addressed in future commits.

Evaluation of a UDF is performed similarly to the execution of
apply-joins. During the execbuilder phase, a `tree.RoutineExpr` is
created to represent the invocation of a UDF. This expression contains a
closure that can generate an optimized plan for each statement in the
UDF body. During evaluation, a plan is generated and executed for each
statement sequentially (however, only a single-statement is currently
supported). The results of the last statement are returned as the
result.

Release note: None

#### opt: fully optimize statements in UDFs

The optimizer now creates required properties that are used when
optimizing each statement in a body UDF during evaluation of the UDF.
These props must be used to ensure that properties such as ordering and
presentation are maintained during optimization.

Release note: None

#### sql: execute all statements in a UDF during evaluation

All statements in a UDF body are now executed when a UDF is evaluated.

Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
Nice work! No comments :)

> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 19 of 19 files at r3, 6 of 6 files at r4, 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85674#-:-N8jujze4LCYd04755lR:b-4hscra)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @msirek, and @rytaft)

___
*[`pkg/sql/sem/tree/routine.go` line 45 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85674#-N8jtYWEES3tWcecodes:-N8jtYWF8gwR8IS53h5y:btgpl7b) ([raw file](https://github.com/cockroachdb/cockroach/blob/921c7fceb8c574754bc653e79141a3ab98b055fa/pkg/sql/sem/tree/routine.go#L45)):*
> ```Go
> }
> 
> // NewTypedRoutineExpr returns a new RoutineExpr the is well-typed.
> ```

nit: probably `s/the is/that is/`.

**Review by DrewKimball — APPROVED** [review]
Cool! :LGTM:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85674#-:-N8w_iLa6RXZ2VGvQNTa:b-a41a5j)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @msirek, and @rytaft)

___
*[`pkg/sql/logictest/testdata/logic_test/udf` line 293 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85674#-N8wZZDlBVrTV5F3QMqt:-N8wZZDlBVrTV5F3QMqu:bisix8s) ([raw file](https://github.com/cockroachdb/cockroach/blob/475988055dff9512f43a5f19315498acf4f6e72f/pkg/sql/logictest/testdata/logic_test/udf#L293)):*
> ```
> 
> query III colnames
> SELECT *, one() FROM ab WHERE a = one()
> ```

[nit] Is it possible to use a udf as a table source right now? If so, that case could use a test.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85674)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @msirek, and @rytaft)

___
*[`pkg/sql/logictest/testdata/logic_test/udf` line 293 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85674#-N8wZZDlBVrTV5F3QMqt:-N8xp-H41_j2W21yOj1V:b-o7vuhc) ([raw file](https://github.com/cockroachdb/cockroach/blob/475988055dff9512f43a5f19315498acf4f6e72f/pkg/sql/logictest/testdata/logic_test/udf#L293)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Is it possible to use a udf as a table source right now? If so, that case could use a test.
</blockquote></details>

Good catch! Done.
___
*[`pkg/sql/sem/tree/routine.go` line 45 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85674#-N8jtYWEES3tWcecodes:-N8xonBuBAMxFgT5HKgF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/921c7fceb8c574754bc653e79141a3ab98b055fa/pkg/sql/sem/tree/routine.go#L45)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: probably `s/the is/that is/`.
</blockquote></details>

Done.

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
