### PR TITLE
storage: move protos to storagepb

### PR DESCRIPTION
**Pull request by jordanlewis**
This is a mechanical change that moves the protobufs that used to live
in storage to a new package, storagepb. The purpose of this change is to
permit packages (such as sql) that need just protobuf definitions in
storage to not have to depend on the whole storage package.

First 2 commits are #31309.

Updates #30001.

Release note: None

### CODE REVIEW

**Review by a-robinson — DISMISSED** [review]
:lgtm: 

> Reviewed 17 of 17 files at r1, 1 of 1 files at r2, 41 of 41 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31322#-:-LOdk8qH3S7mtIph70ni:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/client_raft_test.go, line 261 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31322#-LOdjBRA-nVnJ1wj9XMV:-LOdjBRB5C0IiEsKohKn:bfgj2ka) ([raw file](https://github.com/cockroachdb/cockroach/blob/484cfbb392f84ade1d512bfdc3e8ef63d575ec13/pkg/storage/client_raft_test.go#L261)):*
> ```Go
> 		},
> 		repl.Desc(),
> 		storagepb.reasonrangeUnderReplicated,
> ```

I think your renamer got overzealous with this? `reasonrangeUnderReplicated` is both an unexported name and the `r` in `Range` should be capitalized regardless.

**Review by tbg — APPROVED** [review]
:lgtm:

> Reviewed 3 of 17 files at r1, 11 of 54 files at r4, 2 of 2 files at r5, 36 of 43 files at r6, 36 of 36 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31322#-:-LOe41XHDRtEJXKpxRtF:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/storage/replica_proposal.go, line 26 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/31322#-LOe3oOc6ErIl1I_-fI0:-LOe3oOc6ErIl1I_-fI1:b-i1w13j) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe919bbd598e06284efcb8e3fa401f09618f3c49/pkg/storage/replica_proposal.go#L26)):*
> ```Go
> 	"unsafe"
> 
> 	"github.com/cockroachdb/cockroach/pkg/storage/storagepb"
> ```

We agreed we weren't  gonna worry about this, right?

**Comment by jordanlewis** [comment]
> We agreed we weren't gonna worry about this, right?

Yes. But now that Nikhil's merged https://github.com/cockroachdb/crlfmt/pull/22, I'll run that :)

**Comment by jordanlewis** [comment]
TFTRs!

bors r+

**Pull request merged**
