### PR TITLE
sql/opt/optbuilder: return pgcode on undefined index

### LINKED ISSUE #67099: sql: selecting from non-existing index does not return pgcode
**Describe the problem**

It should return `42704`/`pgcode.UndefinedObject`. The code that produces this is https://github.com/cockroachdb/cockroach/blob/cea4a80a82676db34f9b743469e75b87b1e75a06/pkg/sql/opt/optbuilder/select.go#L524-L528

### PR DESCRIPTION
**Pull request by ajwerner**
Fixes #67099

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67101#-:-MdXaqgZDCBIykFYn6P1:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by ajwerner** [comment]
TFTR!

bors r=RaduBerinde

**Pull request merged**
