### PR TITLE
rac2: delete TokenWaitingHandle interface

### PR DESCRIPTION
**Pull request by sumeerbhola**
There is only one implementation, so there is no need to pay for the heap allocation.

Epic: CRDB-37515

Release note: None

### CODE REVIEW

**Comment by sumeerbhola** [comment]
`BenchmarkTimeBoundIterate` CI failure is a flake

**Review by pav-kv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132912)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go` line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132912#-O9V1VioElMqbHPY5w-m:-O9V1VioElMqbHPY5w-n:b-g41t0r) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c85d3a4f98ef20f24dc5d7a134ef26c7540e516/pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go#L36)):*
> ```Go
> 	// available recently. A typical usage pattern is:
> 	//
> 	//   for {
> ```

Should this comment migrate to the impl type? Looks useful.

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132912#-:-O9V28Y5835rCa3Y_RBU:b-814g8k)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go` line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132912#-O9V1VioElMqbHPY5w-m:-O9V2028BLlS7_PHVx5h:b-w3r6nj) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c85d3a4f98ef20f24dc5d7a134ef26c7540e516/pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go#L36)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Should this comment migrate to the impl type? Looks useful.
</blockquote></details>

All the impl functions already had a copy of these comments.

**Comment by sumeerbhola** [comment]
bors r=pav-kv

**Review by kvoli — APPROVED** [review]

**Pull request merged**
