### PR TITLE
sql: allow CONNECTION LIMIT syntax for CREATE DATABASE

### LINKED ISSUE #54116: sql: make CONNECTION LIMIT = -1 a no-op
At table creation, Postgres supports a notion of infinite connection limits via CONNECTION LIMIT = -1. We should make this a no-op as it isn't relevant with CockroachDB.

### PR DESCRIPTION
**Pull request by otan**
Resolves #54116.

Release note (sql change): Added the ability to parse the `CONNECTION
LIMIT [=] iconst32` syntax for `CREATE DATABASE`. This is currently a
no-op for -1 (default, unlimited connections), and errors for any
other value.

### CODE REVIEW

**Comment by knz** [comment]
I think treating the -1 case as no-op is good, but I'm not comfortable about ignoring every other value.

The issue here is that we want to support it later. If we ignore it today, we're telling users they can stuff arbitrary values there **with the guarantee crdb will ignore it**. So if we ever want to do something with the value we'll need first one deprecation cycle for the current behavior and then only change it.

That's a general principle btw - ignoring values is the dual of guaranteeing it doesn't matter and offering "this is a placeholder for arbitrary values" as a long-term supported feature. 

-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by otan** [comment]
ah i misread the ticket. can make this error for != -1.

**Review by arulajmani — APPROVED** [review]
Looks good 

> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54219#-:-MHIXSgHCZA94-o80Vfa:b-vs1pri)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @solongordon)

**Comment by otan** [comment]
bors r=arulajmani

**Pull request merged**
