### PR TITLE
acceptance: add a django GSS test

### PR DESCRIPTION
**Pull request by madelynnblue**
This verifies that the pip psycopg2 and django-cockroachdb modules can
connect to a GSS-enabled cockroach server in django 3.

Release note: None

### CODE REVIEW

**Comment by vy-ton** [comment]
@cockroachdb/appdev Sharing for awareness

**Review by rafiss — COMMENTED** [review]
The Django parts look good to me, but I'm less familiar with GSS.

Also, having trouble understanding why the test is failing.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50405#-:-MAbZ0h9EC3aCCmIcAKU:bmpxicf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @BramGruneir and @rafiss)

**Comment by mjibson** [comment]
Thanks. Don't worry about the GSS stuff, it's copied from the existing GSS test. I'll figure out the failure.

**Review by rafiss — APPROVED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50405)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @BramGruneir)

**Comment by mjibson** [comment]
This failure is happening because acceptance/cluster.GenerateCerts is called at the package test start, but then cluster/DockerCluster.createNodeCerts is called when docker clusters are created. If the DockerPython test (or any of the DockerX tests) run before TestComposeGSSPython, then `node.crt` will be overwritten with a new cert. These two node certs have different key lengths. The ones created by the DockerX tests have a length of 1024, which is too short for modern ssl stuff, which produces the key too small error here. Changing that to 2048 (the same as the GenerateCerts call) fixes the error. Even though a new cert is being generated, both use the hardcoded CA, which is why the generated node cert is still valid.

**Comment by mjibson** [comment]
Followup: we shouldn't "just" bump the keysize to 2048 and allow the node certs to be overwritten because the valid hosts are different for each.

**Comment by mjibson** [comment]
@rafiss could you review the new commit here about cert stuff? Wow this was annoying to find.

**Review by rafiss — APPROVED** [review]
lgtm, and thank you for this test!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50405#-:-MAcRI157V52zV543GRa:b-oj9b67)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @BramGruneir and @rafiss)

**Comment by rafiss** [comment]
@brianc as we mentioned in our call today, here's a test that uses Kerberos in a Django environment.

**Pull request merged**
