### PR TITLE
roachtest: improve the filename of stmtbundles

### PR DESCRIPTION
**Pull request by andrewbaptist**
The perturbation/* tests download statement bundles at the end of the test. Previously these only included the timestamp that the profile was taken at. However this meant searching through the profiles to find a relevant one. This commit adds both the operation type as well as the duration of the trace. It required unzipping the trace and examining the contents.

Epic: none

Release note: None

### CODE REVIEW

**Review by arulajmani — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133443#-:-OA39dG--Xrw7SFZ__tJ:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist, @herkolategan, @kvoli, and @nameisbhaskar)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133443#-OA38xp814IyoeoqQy0x):*
Should we include an example of the new file name with your changes, either in the commit message or in a comment? 
___
*[`pkg/cmd/roachtest/tests/util.go` line 294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133443#-OA39WUf4ouFkeKOvagx:-OA39WUf4ouFkeKOvagy:baezucp) ([raw file](https://github.com/cockroachdb/cockroach/blob/63bcdfefbfdf1c9984a0cacf988f2b3d1303b62e/pkg/cmd/roachtest/tests/util.go#L294)):*
> ```Go
> 	// Use the second to last line because the last line is empty.
> 	duration := strings.Split(strings.TrimSpace(lines[len(lines)-2]), " ")[0]
> 	return fmt.Sprintf("%s-%s-%s.zip", collectedAt.Format("2006-01-02T15_04_05Z07:00"), operation, duration), nil
> ```

I'm assuming you got this logic correct, but an example (like I mentioned above) would help.

**Review by kvoli — CHANGES_REQUESTED** [review]
Had a pass, structure :lgtm: -- consider adopting the suggestions between nits and non-nits.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133443#-:-OA3CwPr-hHZxOjQNNAO:bfdoywr)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @andrewbaptist, @arulajmani, @herkolategan, and @nameisbhaskar)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133443#-OA3BPhY2mQYXT4-aETy):*
Include perturbation in the commit header as well, otherwise it could apply to any roachtest at a glance.
___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133443#-OA38xp814IyoeoqQy0x):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should we include an example of the new file name with your changes, either in the commit message or in a comment?
</blockquote></details>

+1
___
*[`pkg/cmd/roachtest/tests/util.go` line 263 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133443#-OA3BgrB3jbOX4C4BGji:-OA3BgrB3jbOX4C4BGjj:b-3xmuz0) ([raw file](https://github.com/cockroachdb/cockroach/blob/63bcdfefbfdf1c9984a0cacf988f2b3d1303b62e/pkg/cmd/roachtest/tests/util.go#L263)):*
> ```Go
> 			return err
> 		}
> 		logger.Printf("downloading profile %s", filename)
> ```

Should this be `"downloaded profile %s"`, as the profile is downloaded above:

```go
resp, err := client.Get(context.Background(), url)
```
___
*[`pkg/cmd/roachtest/tests/util.go` line 268 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133443#-OA3C6QqDuqJWW-il3I5:-OA3C6QqDuqJWW-il3I6:b-kqua9s) ([raw file](https://github.com/cockroachdb/cockroach/blob/63bcdfefbfdf1c9984a0cacf988f2b3d1303b62e/pkg/cmd/roachtest/tests/util.go#L268)):*
> ```Go
> }
> 
> // getFilename creates a reasonable file name for the profile based on the trace
> ```

nit: reasonable is subjective, prefer being specific for how the filename is constructed, either on the function comment, or below with an example as @arulajmani suggests.
___
*[`pkg/cmd/roachtest/tests/util.go` line 268 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133443#-OA3COqz0E-fayWzTSgV:-OA3COqz0E-fayWzTSgW:b-kg0laz) ([raw file](https://github.com/cockroachdb/cockroach/blob/63bcdfefbfdf1c9984a0cacf988f2b3d1303b62e/pkg/cmd/roachtest/tests/util.go#L268)):*
> ```Go
> }
> 
> // getFilename creates a reasonable file name for the profile based on the trace
> ```

nit: traced, it occurred in the past.
___
*[`pkg/cmd/roachtest/tests/util.go` line 276 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133443#-OA3CS0Z2rDEnUTK1rEg:-OA3CS0Z2rDEnUTK1rEh:bwyyjwv) ([raw file](https://github.com/cockroachdb/cockroach/blob/63bcdfefbfdf1c9984a0cacf988f2b3d1303b62e/pkg/cmd/roachtest/tests/util.go#L276)):*
> ```Go
> 		return "", err
> 	}
> 	// As an alternative we could use the trace.json file to get the duration.
> ```

nit: consider refocussing this comment, or rephrasing. What is the relevance of the alternative here, unless also discussing why this method was preferred over the alternative.
___
*[`pkg/cmd/roachtest/tests/util.go` line 291 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133443#-OA3Cm4ZDx53JRrHq1bi:-OA3Cm4ZDx53JRrHq1bj:bobw5bq) ([raw file](https://github.com/cockroachdb/cockroach/blob/63bcdfefbfdf1c9984a0cacf988f2b3d1303b62e/pkg/cmd/roachtest/tests/util.go#L291)):*
> ```Go
> 	// An alternative if this isn't differentiated enough is to use the entire
> 	// fingerprint text.
> 	operation := strings.Split(strings.TrimSpace(lines[0]), " ")[0]
> ```

An example, or explaining what is in `lines[0]` would help the reader be convinced this is correct, as there are no tests.
___
*[`pkg/cmd/roachtest/tests/util.go` line 294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133443#-OA39WUf4ouFkeKOvagx:-OA3CvAI38dpAR53k53_:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/63bcdfefbfdf1c9984a0cacf988f2b3d1303b62e/pkg/cmd/roachtest/tests/util.go#L294)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I'm assuming you got this logic correct, but an example (like I mentioned above) would help.
</blockquote></details>

+1

**Review by andrewbaptist — COMMENTED** [review]
TFTR!

bors r=kvoli, arulajmani

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133443#-:-OAJByzPBlJVORNXmJea:bm44nvo)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @arulajmani, @herkolategan, @kvoli, and @nameisbhaskar)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133443#-OA3BPhY2mQYXT4-aETy):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Include perturbation in the commit header as well, otherwise it could apply to any roachtest at a glance.
</blockquote></details>

Done
___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133443#-OA38xp814IyoeoqQy0x):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done! Added in the commit and a comment. For reference a file now looks something like `2024-10-24T18_23_57Z-UPSERT-101.490ms.zip`
___
*[`pkg/cmd/roachtest/tests/util.go` line 263 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133443#-OA3BgrB3jbOX4C4BGji:-OAJAPHw3x9lWjYGnFaP:b-a2ujfl) ([raw file](https://github.com/cockroachdb/cockroach/blob/63bcdfefbfdf1c9984a0cacf988f2b3d1303b62e/pkg/cmd/roachtest/tests/util.go#L263)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Should this be `"downloaded profile %s"`, as the profile is downloaded above:

```go
resp, err := client.Get(context.Background(), url)
```
</blockquote></details>

Changed.
___
*[`pkg/cmd/roachtest/tests/util.go` line 268 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133443#-OA3C6QqDuqJWW-il3I5:-OAJATw77YGSeyh3ZuWZ:bwyfac3) ([raw file](https://github.com/cockroachdb/cockroach/blob/63bcdfefbfdf1c9984a0cacf988f2b3d1303b62e/pkg/cmd/roachtest/tests/util.go#L268)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: reasonable is subjective, prefer being specific for how the filename is constructed, either on the function comment, or below with an example as @arulajmani suggests.
</blockquote></details>

I removed the word reasonable and added the example.
___
*[`pkg/cmd/roachtest/tests/util.go` line 268 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133443#-OA3COqz0E-fayWzTSgV:-OAJAclP35BxegJkuyOg:b-a2ujfl) ([raw file](https://github.com/cockroachdb/cockroach/blob/63bcdfefbfdf1c9984a0cacf988f2b3d1303b62e/pkg/cmd/roachtest/tests/util.go#L268)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: traced, it occurred in the past.
</blockquote></details>

Changed.
___
*[`pkg/cmd/roachtest/tests/util.go` line 276 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133443#-OA3CS0Z2rDEnUTK1rEg:-OAJAz3KCIOpPPsbMsM0:b28afxy) ([raw file](https://github.com/cockroachdb/cockroach/blob/63bcdfefbfdf1c9984a0cacf988f2b3d1303b62e/pkg/cmd/roachtest/tests/util.go#L276)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: consider refocussing this comment, or rephrasing. What is the relevance of the alternative here, unless also discussing why this method was preferred over the alternative.
</blockquote></details>

Cleaned up.
___
*[`pkg/cmd/roachtest/tests/util.go` line 291 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133443#-OA3Cm4ZDx53JRrHq1bi:-OAJBmzU9JDRu-t2WVg6:b-8xyeld) ([raw file](https://github.com/cockroachdb/cockroach/blob/63bcdfefbfdf1c9984a0cacf988f2b3d1303b62e/pkg/cmd/roachtest/tests/util.go#L291)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

An example, or explaining what is in `lines[0]` would help the reader be convinced this is correct, as there are no tests.
</blockquote></details>

I added an example and cleaned up the text. We can revist this once we have additional workload (like TPCC). Then we might want to include more of the query text. It is hard to balance readability and conciseness.
___
*[`pkg/cmd/roachtest/tests/util.go` line 294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133443#-OA39WUf4ouFkeKOvagx:-OAJBlYkDqaybRhsYoXn:bz1xei1) ([raw file](https://github.com/cockroachdb/cockroach/blob/63bcdfefbfdf1c9984a0cacf988f2b3d1303b62e/pkg/cmd/roachtest/tests/util.go#L294)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Thanks - example added.

**Review by kvoli — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133443#-:-OAJJzfY9Tvugz47Hcbi:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani, @herkolategan, and @nameisbhaskar)

**Comment by andrewbaptist** [comment]
TFTR!

bors r=kvoli, arulajmani

**Pull request merged**
