### PR TITLE
sql: improve comments for protos related to interleaving

### PR DESCRIPTION
**Pull request by RaduBerinde**
Release note: None

### CODE REVIEW

**Review by thoszhang — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49132)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/sql/sqlbase/structured.proto, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49132#-M7OjRELCllxpfOKofWt:-M7OjRELCllxpfOKofWu:bz373sg) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ebcbeebc3da04e266bb6c71b822f3dc89cb5afd/pkg/sql/sqlbase/structured.proto#L35)):*
> ```protobuf
> }
> 
> // ForeignKeyReference is deprecated, replaced by ForeignKeyConstraint in v19.2.
> ```

I'd add a sentence about how it's still possible for table descriptors on disk to have `ForeignKeyReference`s.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49132)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @lucy-zhang)

___
*[pkg/sql/sqlbase/structured.proto, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49132#-M7OjRELCllxpfOKofWt:-M7OqboZDzWjNQh4Uk3Q:b-dtkds3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ebcbeebc3da04e266bb6c71b822f3dc89cb5afd/pkg/sql/sqlbase/structured.proto#L35)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

I'd add a sentence about how it's still possible for table descriptors on disk to have `ForeignKeyReference`s.
</blockquote></details>

Done, thanks!

**Pull request merged**
