### PR TITLE
sql,backupccl: stop using StartableJobs when not needed

### PR DESCRIPTION
**Pull request by thoszhang**
We were using `StartableJob`s in the schema change job and the restore
job to start more jobs. This was unnecessary because we didn't need the
ability to get results from the job resumer that `StartableJob`
provide. It also incurred problems because creating a `StartableJob`
creates state that can't be cleaned up if the transaction was restarted.

This commit switches those jobs to normal jobs that are claimed and
started by the registry. To recover the behavior where jobs are started
"immediately," we notify the job registry adoption loop.

Some schema change tests had to be skipped because they relied on the
ability of the schema change job to manually start jobs.

Related to #60671.

Release note: None

### CODE REVIEW

**Comment by lucy-zhang** [comment]
I seem to be consistently hitting a timeout in `TestCCLLogic/multiregion-9node-3region-3azs` here: https://github.com/cockroachdb/cockroach/blob/b5d9848a02cc796bf833685041e16a0f09100993/pkg/ccl/logictestccl/testdata/logic_test/multi_region_backup#L681

So this is going to take some further investigation.

**Comment by lucy-zhang** [comment]
Never mind, apparently this is #60773. I should have just checked the existing issues.

**Review by ajwerner — COMMENTED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60804)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @pbardea)

___
*[pkg/sql/alter_column_type_test.go, line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60804#-MU9RtH66u5VCHNtIoHw:-MU9RtH7ASoGzgb7yoga:b-psbywm) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5bed9bfd3da8dbe867009fd466ad27b7f565d5/pkg/sql/alter_column_type_test.go#L103)):*
> ```Go
> 	defer log.Scope(t).Close(t)
> 	skip.WithIssue(t, 60801, "needs to be rewritten to not use RunBeforeChildJobs")
> ```

How about reworking this to just detect the resumption of the job to do the alter type with `RunBeforeResume`. Both here and the other one and then delete this knob.

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60804)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @pbardea)

___
*[pkg/sql/alter_column_type_test.go, line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60804#-MU9RtH66u5VCHNtIoHw:-MU9XTdt9B7Nxj2DhWWU:b-ifvnfq) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5bed9bfd3da8dbe867009fd466ad27b7f565d5/pkg/sql/alter_column_type_test.go#L103)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

How about reworking this to just detect the resumption of the job to do the alter type with `RunBeforeResume`. Both here and the other one and then delete this knob. 
</blockquote></details>

Done. That was not as annoying as I originally expected.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60804#-:-MUAAIJO8C1VlqvIeiWP:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @pbardea)

**Comment by lucy-zhang** [comment]
TFTR

bors r+

**Pull request merged**
