### PR TITLE
workload: add follower read support

### PR DESCRIPTION
**Pull request by andrewbaptist**
The performance of the system can be different if there are reads as of a system time. This PR adds the ability to issue follower reads.

Epic: none

Release note (cli change): Add --follower-read-percent to the workload kv run.

### CODE REVIEW

**Comment by andrewbaptist** [comment]
This is part of the testing effort for #112351. It allows running follower reads for KV workloads.

**Comment by andrewbaptist** [comment]
@austin This can't merge yet as this depends on the fix for follower reads (otherwise this test will fail). However, I wanted to have you review these changes as they are in a test you have been mostly involved in.

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113094)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @herkolategan, @kvoli, @msbutler, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/kv.go` line 542 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113094#-NhgjW0x6L-AupsQItef:-NhgjW0x6L-AupsQIteg:b-toilqc) ([raw file](https://github.com/cockroachdb/cockroach/blob/0901a7465f5395bbc57c53d42b2b6111982fa733/pkg/cmd/roachtest/tests/kv.go#L542)):*
> ```Go
> 			// Don't connect to the node we are going to shut down.
> 			dbs := make([]*gosql.DB, nodes-1)
> 			for i := 0; i < nodes-1; i++ {
> ```

nit: `for i := range dbs {`
___
*[`pkg/cmd/roachtest/tests/kv.go` line 615 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113094#-Nhgjx4B11opIsWoM2Al:-Nhgjx4B11opIsWoM2Am:bwvi6it) ([raw file](https://github.com/cockroachdb/cockroach/blob/0901a7465f5395bbc57c53d42b2b6111982fa733/pkg/cmd/roachtest/tests/kv.go#L615)):*
> ```Go
> 			t.Status("gracefully draining and restarting nodes")
> 			// Gracefully shut down the third node, let the cluster run for a
> 			// while, then restart it. Then repeat for good measure.
> ```

s/Then repeat/Repeat for a total of 3 times/

To make it more clear where the 3 is coming from below.
___
*[`pkg/cmd/roachtest/tests/kv.go` line 637 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113094#-Nhgk4GP0spXEQFmopIf:-Nhgk4GP0spXEQFmopIg:bdm0tq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0901a7465f5395bbc57c53d42b2b6111982fa733/pkg/cmd/roachtest/tests/kv.go#L637)):*
> ```Go
> 				// drop all packets in both directions.
> 				if !c.IsLocal() {
> 					c.Run(ctx, c.Node(nodes), `sudo iptables -A INPUT -p tcp --dport 26257 -j DROP`)
> ```

Nice idea.
___
*[`pkg/workload/kv/kv.go` line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113094#-NhghckA0VYPq_KTA7HY:-NhghckA0VYPq_KTA7HZ:btmfrkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/07af6ec1d1fd643e0cdf035a0adfb73dee0e49c6/pkg/workload/kv/kv.go#L99)):*
> ```Go
> 	insertCount                          int
> 	useBackgroundTxnQoS                  bool
> 	followerReadPercent                  int
> ```

nit: move this right below `readPercent`.
___
*[`pkg/workload/kv/kv.go` line 185 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113094#-Nhghkje36dHk6XoRUvb:-Nhghkje36dHk6XoRUvc:bwph0su) ([raw file](https://github.com/cockroachdb/cockroach/blob/07af6ec1d1fd643e0cdf035a0adfb73dee0e49c6/pkg/workload/kv/kv.go#L185)):*
> ```Go
> 		g.flags.BoolVar(&g.useBackgroundTxnQoS, `background-qos`, false,
> 			`Set default_transaction_quality_of_service session variable to "background".`)
> 		g.flags.IntVar(&g.followerReadPercent, `follower-read-percent`, 0,
> ```

nit: move this below `g.flags.IntVar(&g.readPercent`...
___
*[`pkg/workload/kv/kv.go` line 185 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113094#-Nhgi5Ui4mkyDMvIhREk:-Nhgi5Ui4mkyDMvIhREl:bt4ws3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/07af6ec1d1fd643e0cdf035a0adfb73dee0e49c6/pkg/workload/kv/kv.go#L185)):*
> ```Go
> 		g.flags.BoolVar(&g.useBackgroundTxnQoS, `background-qos`, false,
> 			`Set default_transaction_quality_of_service session variable to "background".`)
> 		g.flags.IntVar(&g.followerReadPercent, `follower-read-percent`, 0,
> ```

It was previously possible to accomplish this by adding the `default_transaction_use_follower_reads` session variable to the db URL that you pass to KV, but this is much nicer and also allows for a fraction of the read to be from followers.
___
*[`pkg/workload/kv/kv.go` line 601 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113094#-Nhgi0qw7uPUbZXBH2Lw:-Nhgi0qw7uPUbZXBH2Lx:bnjinn8) ([raw file](https://github.com/cockroachdb/cockroach/blob/07af6ec1d1fd643e0cdf035a0adfb73dee0e49c6/pkg/workload/kv/kv.go#L601)):*
> ```Go
> 		readStmt := o.readStmt
> 
> 		if o.config.followerReadPercent > 0 &&
> ```

nit: do we need the `o.config.followerReadPercent > 0` condition?

**Review by andrewbaptist — COMMENTED** [review]
TFTR - I updated the code, but am only going to merge the first commit (change workload to support follower reads) here once approved, and then move the other commit to the branch which has the fix for follower read stopping.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113094#-:-Ni61rCJCixFcM6dmslY:brladty)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @kvoli, @msbutler, @nvanbenschoten, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/kv.go` line 542 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113094#-NhgjW0x6L-AupsQItef:-Ni60CCpBjTFaRew0m12:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0901a7465f5395bbc57c53d42b2b6111982fa733/pkg/cmd/roachtest/tests/kv.go#L542)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: `for i := range dbs {`
</blockquote></details>

Done
___
*[`pkg/cmd/roachtest/tests/kv.go` line 615 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113094#-Nhgjx4B11opIsWoM2Al:-Ni60LoP5iyz3vjOABm6:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0901a7465f5395bbc57c53d42b2b6111982fa733/pkg/cmd/roachtest/tests/kv.go#L615)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

s/Then repeat/Repeat for a total of 3 times/

To make it more clear where the 3 is coming from below.
</blockquote></details>

Done
___
*[`pkg/cmd/roachtest/tests/kv.go` line 637 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113094#-Nhgk4GP0spXEQFmopIf:-Ni60OigB3uglnC_8QHJ:b-1w221i) ([raw file](https://github.com/cockroachdb/cockroach/blob/0901a7465f5395bbc57c53d42b2b6111982fa733/pkg/cmd/roachtest/tests/kv.go#L637)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Nice idea.
</blockquote></details>

Thanks - I realized it wasn't reproducing reliably with "clean" shutdown. 
___
*[`pkg/workload/kv/kv.go` line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113094#-NhghckA0VYPq_KTA7HY:-Ni60_QJ0f9l-HOV_M9Z:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/07af6ec1d1fd643e0cdf035a0adfb73dee0e49c6/pkg/workload/kv/kv.go#L99)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: move this right below `readPercent`.
</blockquote></details>

Done
___
*[`pkg/workload/kv/kv.go` line 185 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113094#-Nhghkje36dHk6XoRUvb:-Ni60aTh6eG_AYqei52n:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/07af6ec1d1fd643e0cdf035a0adfb73dee0e49c6/pkg/workload/kv/kv.go#L185)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: move this below `g.flags.IntVar(&g.readPercent`...
</blockquote></details>

Done
___
*[`pkg/workload/kv/kv.go` line 185 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113094#-Nhgi5Ui4mkyDMvIhREk:-Ni60had22iSUgGoHzxJ:b-nhge8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/07af6ec1d1fd643e0cdf035a0adfb73dee0e49c6/pkg/workload/kv/kv.go#L185)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It was previously possible to accomplish this by adding the `default_transaction_use_follower_reads` session variable to the db URL that you pass to KV, but this is much nicer and also allows for a fraction of the read to be from followers.
</blockquote></details>

Right - I had considered that previously, but I wanted to make sure that the test at least covered both types of reads since the cause for slowdowns might have been different for each.
___
*[`pkg/workload/kv/kv.go` line 601 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113094#-Nhgi0qw7uPUbZXBH2Lw:-Ni60qc44auy6gfsg3E9:b-3ozpkf) ([raw file](https://github.com/cockroachdb/cockroach/blob/07af6ec1d1fd643e0cdf035a0adfb73dee0e49c6/pkg/workload/kv/kv.go#L601)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: do we need the `o.config.followerReadPercent > 0` condition?
</blockquote></details>

No - removed to make it more clear.

**Review by kvoli — APPROVED** [review]
First commit :lgtm: 

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113094#-:-NiAD5VdDV-p0PrpzQbw:bg60rpc)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist, @herkolategan, @msbutler, @nvanbenschoten, and @srosenberg)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113094#-NhhXO7P0wDBzAXhNOUh):*
nit: could you mention adding follower read support for the `kv` workload specifically.

**Comment by andrewbaptist** [comment]
bors r=kvoli

TFTR!
I pulled off the second commit so I can add the changes to the workload tool first prior to the follower read changes being made. I moved the second commit to: #112926.

**Pull request merged**
