### PR TITLE
roachtest: remove tpchbench/tpchVec config

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit removes tpchVec config of tpchbench roachtest because that
config contains only a small subset of TPCH queries and
skipping/unskipping them causes the roachperf dashboard to be
misleading. tpchvec roachtest is more "powerful" because it also checks
the correctness of the results and prints out the comparison with vec
off. Ideally, we would hook up tpchvec test to roachperf.

Addresses: #41108.

Release note: None

### CODE REVIEW

**Comment by asubiotto** [comment]
If the issue is the dashboard, I think we should change the roachperf code not to display results from this particular roachtest. Unless I'm missing something, I think we still want to keep this roachtest in place and run it nightly, right?

**Comment by yuzefovich** [comment]
I don't see a value in this test no more - `roachtest/tpchvec` gives us more - it checks the correctness of the results. The only part that is missing from that test is putting the data on the dashboard to see the performance changes in the vectorized engine over time, but I would argue that it wasn't meaningful (in the current setup) anyway - long-running query 9 messes up the scale so that other queries are not readable.

Why do you want to keep it?

**Review by asubiotto — APPROVED** [review]
Ah, got it. Didn't realize they were separate :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42885#-:-LvKVr67D-gmV41JqWVX:b-qxc5qd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
