### PR TITLE
roachtest: improve sqlsmith

### LINKED ISSUE #58235: roachtest: sqlsmith/setup=tpcc/setting=ddl-nodrop failed
[(roachtest).sqlsmith/setup=tpcc/setting=ddl-nodrop failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2538659&tab=buildLog) on [master@cd62a02833eeb02d14944668d09ee54806927a2b](https://github.com/cockroachdb/cockroach/commits/cd62a02833eeb02d14944668d09ee54806927a2b):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/sqlsmith/setup=tpcc/setting=ddl-nodrop/run_1
	sqlsmith.go:142,sqlsmith.go:223,test_runner.go:760: pq: injected panic in Next

```

<details><summary>More</summary><p>

Artifacts: [/sqlsmith/setup=tpcc/setting=ddl-nodrop](https://teamcity.cockroachdb.com/viewLog.html?buildId=2538659&tab=artifacts#/sqlsmith/setup=tpcc/setting=ddl-nodrop)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Asqlsmith%2Fsetup%3Dtpcc%2Fsetting%3Dddl-nodrop.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by yuzefovich**
**roachtest: delay panic injection in sqlsmith**

We need to delay the panic injection until after the smither is created
because some queries are run during its instantiation.

Fixes: #58235.

Release note: None

**roachtest: ignore a known issue in sqlsmith**

This commit temporarily skips failing `sqlsmith` roachtest on `internal
error: invalid index` errors which are due to issues with subqueries
(#39433) in order to reduce the noise.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Friendly ping @jordanlewis

**Review by jordanlewis — APPROVED** [review]
Sorry, I thought I approved this already

**Comment by yuzefovich** [comment]
No worries - in the first cut I didn't move it enough. I also just added another commit to remove the noise. PTAL.

**Review by jordanlewis — APPROVED** [review]

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by yuzefovich** [comment]
Unrelated flake.

bors r+

**Pull request merged**
