### PR TITLE
sql: support json - text

### PR DESCRIPTION
**Pull request by yuzefovich**
Added support for JSONArray minus string. The code used to quietly
do nothing on the operation; now, instead, it loops over all elements
of the array, converts it to string and compares to the key to be removed.

Resolves: #25665.

Release note: None

### CODE REVIEW

**Comment by arjunravinarayan** [comment]
This looks good to me, roping in @justinj to confirm that this is the expected semantics of the JSON minus operator, and that the added tests are sufficient.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-:-LDD8zyqDqcY3gA9q3Zf:b-6kealw)*

**Comment by arjunravinarayan** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[pkg/sql/logictest/testdata/logic_test/json, line 527 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-LDDBE7r3-MvzZMHauiH:-LDDBE7r3-MvzZMHauiI:byhclt7) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e3b4b750fbda0302d0a14cbcca314f8450d940/pkg/sql/logictest/testdata/logic_test/json#L527)):*
> ```
> SELECT '["1", "2", "3"]'::JSONB - '4'
> ----
> ["1", "2", "3"]
> ```

Add a few more test cases: empty array, empty string.

---

*[pkg/util/json/json.go, line 1149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-LDDAoIX0sEMetK1NFyK:-LDDAoIX0sEMetK1NFyL:b-bbvtz7) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e3b4b750fbda0302d0a14cbcca314f8450d940/pkg/util/json/json.go#L1149)):*
> ```Go
> 	removed := false
> 	for _, el := range j {
> 		s, _ := el.AsText()
> ```

You should check the err here, and if its `!= nil` return the error.

---

*[pkg/util/json/json.go, line 1150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-LDDBlQH2gp0h_i8u4q-:-LDDBlQH2gp0h_i8u4q0:b27sb5a) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e3b4b750fbda0302d0a14cbcca314f8450d940/pkg/util/json/json.go#L1150)):*
> ```Go
> 	for _, el := range j {
> 		s, _ := el.AsText()
> 		if strings.Compare(*s, key) != 0 {
> ```

you can just use `==` here instead of `strings.Compare` since you don't care about differentiating the inequality cases.

---

*[pkg/util/json/json.go, line 1156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-LDDBZd7AbRHiklJ_LyA:-LDDBZd7AbRHiklJ_LyB:bg5lfzj) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e3b4b750fbda0302d0a14cbcca314f8450d940/pkg/util/json/json.go#L1156)):*
> ```Go
> 		}
> 	}
> 	return b.Build(), removed, nil
> ```

One small optimization that's possible here is if `removed = false`, you don't need to build, and can just return `j`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25861)*

**Comment by justinj** [comment]
This looks really good! A couple semantics things I'm unsure about. Feel free to ask me if you have any questions about anything.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/logictest/testdata/logic_test/json, line 527 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-LDDBE7r3-MvzZMHauiH:-LDDD7Ec2HlKaFZCGtHG:bycixky) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e3b4b750fbda0302d0a14cbcca314f8450d940/pkg/sql/logictest/testdata/logic_test/json#L527)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Add a few more test cases: empty array, empty string.
</blockquote></details>

also deleting from arrays which contain values which are not just strings would be good, in particular values whose stringified form might match the right hand side, like `"[1]"::jsonb - '1'::string`.

---

*[pkg/util/json/json.go, line 1145 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-LDDDoXZ7lVRWx9rbKN4:-LDDAED8E-7WdOunB7D-:b-7q2vs5) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e3b4b750fbda0302d0a14cbcca314f8450d940/pkg/util/json/json.go#L1145)):*
> ```Go
> var errCannotDeleteFromObject = pgerror.NewError(pgerror.CodeInvalidParameterValueError, "cannot delete from object using integer index")
> 
> func (j jsonArray) RemoveKey(key string) (JSON, bool, error) {
> ```

I think we should rename `RemoveKey` now that it's clear it's not just removing a key, it's more like `RemoveString` or `MinusString` something I guess? It's just some weird postgres-y semantics so I don't know if there's even really a good name for it.

In addition, `RemoveKey` is used by path deletion as well (see `RemovePath` and the `#-` operator). I think by changing the semantics of this you might also be subtly changing the semantics of that (though my memory of that is a little foggy). You should take a look into that to see if that's the case, and if it's desirable or not. You might have to split up this method into two (`RemoveKey` and `MinusString`, or something).

---

*[pkg/util/json/json.go, line 1149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-LDDA1Vz9WpJ2jRonNmw:-LDDA1W-7qVvxRgqKNKo:bdalptp) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e3b4b750fbda0302d0a14cbcca314f8450d940/pkg/util/json/json.go#L1149)):*
> ```Go
> 	removed := false
> 	for _, el := range j {
> 		s, _ := el.AsText()
> ```

so I think this is not quite right, the result of `"[true]"::jsonb - 'true'` should be `[true]`. `-` should only remove values in the left hand side which were *strings*. I think you need to test if `el.Type() == StringJSONType` in addition. A gotcha here to keep in mind is that if `el.Type() == StringJSONType`, `el` might *not* be a `jsonString` - it could also be a `jsonEncoded`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-:-LDDF-RI6xPopnMDoD-u:b-uv5ybp)*

**Comment by yuzefovich** [comment]
I addressed all the comments, so please leave so more :) I guess I should update the commit message to elaborate more on additional changes, right?

---

Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/sql/logictest/testdata/logic_test/json, line 527 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-LDDBE7r3-MvzZMHauiH:-LDDEBK7Abf49Zrr3Rpi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e3b4b750fbda0302d0a14cbcca314f8450d940/pkg/sql/logictest/testdata/logic_test/json#L527)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Add a few more test cases: empty array, empty string.
</blockquote></details>

Done.

---

*[pkg/util/json/json.go, line 1145 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-LDDDoXZ7lVRWx9rbKN4:-LDHRycY5Cj0dCHK66yJ:b4cepbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e3b4b750fbda0302d0a14cbcca314f8450d940/pkg/util/json/json.go#L1145)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I think we should rename `RemoveKey` now that it's clear it's not just removing a key, it's more like `RemoveString` or `MinusString` something I guess? It's just some weird postgres-y semantics so I don't know if there's even really a good name for it.

In addition, `RemoveKey` is used by path deletion as well (see `RemovePath` and the `#-` operator). I think by changing the semantics of this you might also be subtly changing the semantics of that (though my memory of that is a little foggy). You should take a look into that to see if that's the case, and if it's desirable or not. You might have to split up this method into two (`RemoveKey` and `MinusString`, or something).
</blockquote></details>

I agree with method renaming.

I looked over <code>RemovePath</code>, and to the best of my understanding, it should work exactly like it used to. I added several test cases that I could think of.

---

*[pkg/util/json/json.go, line 1149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-LDDAoIX0sEMetK1NFyK:-LDDEX308CQGBC2KLfLh:b74g9ip) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e3b4b750fbda0302d0a14cbcca314f8450d940/pkg/util/json/json.go#L1149)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

You should check the err here, and if its `!= nil` return the error.
</blockquote></details>

I looked over all AsText methods, and none actually return an error (always nil). Should I still check whether the error is nil, and if so, what's the appropriate return statement, something like  <code> return j, false, err </code> ?

---

*[pkg/util/json/json.go, line 1149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-LDDA1Vz9WpJ2jRonNmw:-LDDcSlO1BeXscTtQz7m:b-osll8l) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e3b4b750fbda0302d0a14cbcca314f8450d940/pkg/util/json/json.go#L1149)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

so I think this is not quite right, the result of `"[true]"::jsonb - 'true'` should be `[true]`. `-` should only remove values in the left hand side which were *strings*. I think you need to test if `el.Type() == StringJSONType` in addition. A gotcha here to keep in mind is that if `el.Type() == StringJSONType`, `el` might *not* be a `jsonString` - it could also be a `jsonEncoded`.
</blockquote></details>

You're right. I had this check but then, for some reason, decided it wasn't necessary. I'm slightly puzzled by the type system, please take a look at revised version.

---

*[pkg/util/json/json.go, line 1150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-LDDBlQH2gp0h_i8u4q-:-LDDXWwS3_q0vyp7tWdW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e3b4b750fbda0302d0a14cbcca314f8450d940/pkg/util/json/json.go#L1150)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

you can just use `==` here instead of `strings.Compare` since you don't care about differentiating the inequality cases.
</blockquote></details>

Done.

---

*[pkg/util/json/json.go, line 1156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-LDDBZd7AbRHiklJ_LyA:-LDDXR_86LIqyU8JukyT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e3b4b750fbda0302d0a14cbcca314f8450d940/pkg/util/json/json.go#L1156)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

One small optimization that's possible here is if `removed = false`, you don't need to build, and can just return `j`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-:-LDHTJQSCpLl2bNM_ai-:boqbcs3)*

**Comment by justinj** [comment]
Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/util/json/json.go, line 1145 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-LDDDoXZ7lVRWx9rbKN4:-LDHUM7F2LQ4LzE5F1aA:b-kqb336) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e3b4b750fbda0302d0a14cbcca314f8450d940/pkg/util/json/json.go#L1145)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I agree with method renaming.

I looked over <code>RemovePath</code>, and to the best of my understanding, it should work exactly like it used to. I added several test cases that I could think of.
</blockquote></details>

What about `'["foo"]'::jsonb #- array['foo']`? this should return an error, I can't immediately tell if it still does here? maybe I'm wrong and we actually don't use this in the presence of arrays 🤔

---

*[pkg/util/json/json.go, line 1149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-LDDAoIX0sEMetK1NFyK:-LDHUSxZ34cgC9KzVE2p:b-5046bj) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e3b4b750fbda0302d0a14cbcca314f8450d940/pkg/util/json/json.go#L1149)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I looked over all AsText methods, and none actually return an error (always nil). Should I still check whether the error is nil, and if so, what's the appropriate return statement, something like  <code> return j, false, err </code> ?
</blockquote></details>

There's one more implementor of the `JSON` interface which isn't in this file, it's `jsonEncoded`, which represents a JSON value that might not (yet) have been decoded from its on-disk encoding, in `pkg/util/json/encoded.go`. It can error on most methods in the presence of invalid encoded data, which theoretically should never occur, but it is an error case.

The reason `jsonEncoded` exists is that for many operations it would be wasteful to decode the entire JSON object, so `jsonEncoded` allows us to not decode the entire thing in the case of say, we only want to grab one field out of it.

Usually we just use the zero value for each thing we're returning, so `return nil, false, err`.

---

*[pkg/util/json/json.go, line 1149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-LDDA1Vz9WpJ2jRonNmw:-LDHUrdiAAKgY2hAC49K:b-f6fcrz) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e3b4b750fbda0302d0a14cbcca314f8450d940/pkg/util/json/json.go#L1149)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

You're right. I had this check but then, for some reason, decided it wasn't necessary. I'm slightly puzzled by the type system, please take a look at revised version.
</blockquote></details>

[this document](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20171005_jsonb_encoding.md) might be helpful for understanding (but I can also answer any specific questions).

---

*[pkg/util/json/json.go, line 1151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-LDHYaKnDzy3nvU7CtZk:-LDHYaKnDzy3nvU7CtZl:blm5u8r) ([raw file](https://github.com/cockroachdb/cockroach/blob/a149945cdd008e2423915e7a13eefe6019e673d6/pkg/util/json/json.go#L1151)):*
> ```Go
> 		// We want to remove only elements of string type.
> 		if el.Type() == StringJSONType {
> 			decoded, err := el.tryDecode()
> ```

is this necessary? I think a `jsonEncoded` should support `AsText` without being `tryDecode`d (though I might be misremembering)

---

*[pkg/util/json/json.go, line 1170 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-LDHXsHe4qZrLLZEJEpV:-LDHXsHe4qZrLLZEJEpW:bi1o4v6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a149945cdd008e2423915e7a13eefe6019e673d6/pkg/util/json/json.go#L1170)):*
> ```Go
> 	if removed {
> 		return b.Build(), removed, nil
> 	} else {
> ```

for whatever reason it's more idiomatic in Go to omit this `else` block and just `return ...` below

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25861)*

**Comment by arjunravinarayan** [comment]
I think the commit message is sufficiently descriptive as-is.

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/util/json/json.go, line 1170 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-LDHXsHe4qZrLLZEJEpV:-LDHaw81BGT-rFmIPHkH:bxzpaal) ([raw file](https://github.com/cockroachdb/cockroach/blob/a149945cdd008e2423915e7a13eefe6019e673d6/pkg/util/json/json.go#L1170)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

for whatever reason it's more idiomatic in Go to omit this `else` block and just `return ...` below
</blockquote></details>

(I believe its something about 'avoid indentation where possible', although I personally don't like this style, its been beaten into me).

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-:-LDHaaIz5iU_vai7Aiub:bfqw2h1)*

**Comment by arjunravinarayan** [comment]
(You also have to change some other callers in test files which use the old `RemoveKey` name)

---







*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-:-LDHcR27BQXzCH3ELXLs:blweot)*

**Comment by yuzefovich** [comment]
Thanks for pointing out that I needed to update the tests as well. All comments have been addressed.

---

Review status: 2 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/sql/logictest/testdata/logic_test/json, line 527 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-LDDBE7r3-MvzZMHauiH:-LDI5ulr78z1K_Omq4G2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e3b4b750fbda0302d0a14cbcca314f8450d940/pkg/sql/logictest/testdata/logic_test/json#L527)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[pkg/util/json/json.go, line 1145 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-LDDDoXZ7lVRWx9rbKN4:-LDICJ1b2sdn09ZXR87E:bgbgwxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e3b4b750fbda0302d0a14cbcca314f8450d940/pkg/util/json/json.go#L1145)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

What about `'["foo"]'::jsonb #- array['foo']`? this should return an error, I can't immediately tell if it still does here? maybe I'm wrong and we actually don't use this in the presence of arrays 🤔
</blockquote></details>

There was a minor bug for this particular case, I fixed it by returning an error although there was an explicit comment saying that "we don't propagate the error" when trying to parse path element in position 1 as an integer. I think the assumption of never getting into this case was incorrect.

---

*[pkg/util/json/json.go, line 1149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-LDDA1Vz9WpJ2jRonNmw:-LDHc2fsAe8MRgi8zTNX:b-j3gxi) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e3b4b750fbda0302d0a14cbcca314f8450d940/pkg/util/json/json.go#L1149)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

[this document](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20171005_jsonb_encoding.md) might be helpful for understanding (but I can also answer any specific questions).
</blockquote></details>

Thanks, I'll read through the doc.

---

*[pkg/util/json/json.go, line 1149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-LDDAoIX0sEMetK1NFyK:-LDHbrrlDjqwEDGDVgvA:bxk0097) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e3b4b750fbda0302d0a14cbcca314f8450d940/pkg/util/json/json.go#L1149)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

There's one more implementor of the `JSON` interface which isn't in this file, it's `jsonEncoded`, which represents a JSON value that might not (yet) have been decoded from its on-disk encoding, in `pkg/util/json/encoded.go`. It can error on most methods in the presence of invalid encoded data, which theoretically should never occur, but it is an error case.

The reason `jsonEncoded` exists is that for many operations it would be wasteful to decode the entire JSON object, so `jsonEncoded` allows us to not decode the entire thing in the case of say, we only want to grab one field out of it.

Usually we just use the zero value for each thing we're returning, so `return nil, false, err`.
</blockquote></details>

I see, thanks for clarifying.

---

*[pkg/util/json/json.go, line 1151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-LDHYaKnDzy3nvU7CtZk:-LDIEi0e4DP6EDL_WAvs:b-m4h1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/a149945cdd008e2423915e7a13eefe6019e673d6/pkg/util/json/json.go#L1151)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

is this necessary? I think a `jsonEncoded` should support `AsText` without being `tryDecode`d (though I might be misremembering)
</blockquote></details>

You're right. For some reason, when I first used <code>AsText</code> for all types, I ran into some error which I then fixed by decoding. Now it works without that, so, probably, the error was of a different cause.

---

*[pkg/util/json/json.go, line 1170 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-LDHXsHe4qZrLLZEJEpV:-LDHcESr4_bQgT_vE9H5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a149945cdd008e2423915e7a13eefe6019e673d6/pkg/util/json/json.go#L1170)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

for whatever reason it's more idiomatic in Go to omit this `else` block and just `return ...` below
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-:-LDIYMc66qLli5ghjnhY:b-3c576g)*

**Comment by arjunravinarayan** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/sql/logictest/testdata/logic_test/json, line 572 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-LDIZS4y8P4nt4k-Bb86:-LDIZS4y8P4nt4k-Bb87:b-103yqq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffa150d749268f8a30becd6b435db867116b3edd/pkg/sql/logictest/testdata/logic_test/json#L572)):*
> ```
> SELECT '[1, 2, 3]'::JSONB #- ARRAY['0']
> ----
> [2, 3]
> ```

This doesn't look right? cc @Justinj 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25861)*

**Comment by yuzefovich** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[pkg/sql/logictest/testdata/logic_test/json, line 572 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-LDIZS4y8P4nt4k-Bb86:-LDIaA6262bARuBkoNQZ:bmvgh9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffa150d749268f8a30becd6b435db867116b3edd/pkg/sql/logictest/testdata/logic_test/json#L572)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

This doesn't look right? cc @Justinj 
</blockquote></details>

It removes an element at index 0 from the array. The result is confirmed with psql.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25861)*

**Comment by arjunravinarayan** [comment]
*[pkg/sql/logictest/testdata/logic_test/json, line 572 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-LDIZS4y8P4nt4k-Bb86:-LDIaYrxAfIGI5fr0EtH:b-cvyqa6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffa150d749268f8a30becd6b435db867116b3edd/pkg/sql/logictest/testdata/logic_test/json#L572)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

It removes an element at index 0 from the array. The result is confirmed with psql.
</blockquote></details>

Ah gotcha, thanks. Looks correct, then.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25861)*

**Comment by yuzefovich** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/util/json/json.go, line 1145 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-LDDDoXZ7lVRWx9rbKN4:-LDIoimKBKMl6fu4N8Vi:bebiyiv) ([raw file](https://github.com/cockroachdb/cockroach/blob/49e3b4b750fbda0302d0a14cbcca314f8450d940/pkg/util/json/json.go#L1145)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Actually I just did a test, I think this still might not be right - this shouldn't error:
```
> select '{"a": ["foo"]}'::jsonb #- array['a', 'a'];
```
some more tests might be necessary?

This case might have been the origin of that error-handling, I'm surprised there wasn't a test for it, but could you add one?
</blockquote></details>

PostgreSQL produces an error in this case, so does CRDB now. I added a few additional tests to cover it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25861)*

**Comment by arjunravinarayan** [comment]
:lgtm: !

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/util/json/json.go, line 1555 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-LDJ-D1R8VLbM9nxVlmW:-LDJ-D1R8VLbM9nxVlmX:b-lkfpgp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b95365a274d47d20e955c811c4eee80807dfe319/pkg/util/json/json.go#L1555)):*
> ```Go
> 	idx, err := strconv.Atoi(path[0])
> 	if err != nil {
> 		// TODO: give the position of the path element to match psql.
> ```

Please put your name in this TODO.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-:-LDJ-A_n616e_WHOofi8:b593w5u)*

**Comment by yuzefovich** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/util/json/json.go, line 1555 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/25861#-LDJ-D1R8VLbM9nxVlmW:-LDJ-VrWCB-K8VCwO_cn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b95365a274d47d20e955c811c4eee80807dfe319/pkg/util/json/json.go#L1555)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Please put your name in this TODO.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25861)*

**Comment by arjunravinarayan** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25861)*

**Comment by knz** [comment]
Folk I'm sorry I am seeing this only now, but this PR would have benefited from a release note.

**Pull request merged**
