### PR TITLE
distsql: proto specs for join processors

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10054)

### CODE REVIEW

**Comment by paperstreet** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql/processors.proto, line 167 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10054#-KUNCCvaUMZx-mNrirQW:-KUNCCvaUMZx-mNrirQX:b-2oab1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfaaf4966b8a235dec76afb626ec70dc281ea1a3/pkg/sql/distsql/processors.proto#L167)):*
> ```protobuf
>   optional JoinType type = 4 [(gogoproto.nullable) = false];
> 
>   // Columns for the output stream. If the left stream has N columns and the
> ```

very small nit: I had to read this a couple times to understand it, I kept waiting for the "else" counterpart to the "if". Maybe s/If the left/Assuming the left/?

---

*[pkg/sql/distsql/processors.proto, line 173 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10054#-KUNC3GQsQhoMfFLlb_8:-KUNC3GQsQhoMfFLlb_9:b5aa7ti) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfaaf4966b8a235dec76afb626ec70dc281ea1a3/pkg/sql/distsql/processors.proto#L173)):*
> ```protobuf
> }
> 
> // HashJoinerSpec is the specification for a merge join processor. The processor
> ```

hash join processor?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10054)*

**Comment by irfansharif** [comment]
Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql/processors.proto, line 139 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10054#-KUNG_cheJ3fvz1QqdVE:-KUNG_cheJ3fvz1QqdVF:b-x14t50) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfaaf4966b8a235dec76afb626ec70dc281ea1a3/pkg/sql/distsql/processors.proto#L139)):*
> ```protobuf
> 
> // MergeJoinerSpec is the specification for a merge join processor. The processor
> // has two inputs and one output. The inputs have the same ordering on the
> ```

'The inputs **must** have' for more clarity.

---

*[pkg/sql/distsql/processors.proto, line 141 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10054#-KUNIuOFIRfEsgrNWisu:-KUNIuOGa2kg7eOPkiam:b-oifihb) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfaaf4966b8a235dec76afb626ec70dc281ea1a3/pkg/sql/distsql/processors.proto#L141)):*
> ```protobuf
> // has two inputs and one output. The inputs have the same ordering on the
> // columns that have equality constraints. For example:
> //   SELECT FROM T1 INNER JOIN T2 ON T1.C1 = T2.C5 AND T1.C2 = T2.C4
> ```

`SELECT *` or some target list.

---

*[pkg/sql/distsql/processors.proto, line 144 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10054#-KUNGIuC-IuCUbL4TMtW:-KUNGIuD-nPBFFMHhR2V:brawema) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfaaf4966b8a235dec76afb626ec70dc281ea1a3/pkg/sql/distsql/processors.proto#L144)):*
> ```protobuf
> //
> // To perform a merge join, the streams corresponding to T1 and T2 must have the
> // same ordering on coluns C1, C2 and C5, C4 respectively. For example: C1+,C2-
> ```

'columns'.

---

*[pkg/sql/distsql/processors.proto, line 161 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10054#-KUNHwQCdmm6wWBX1KP6:-KUNHwQCdmm6wWBX1KP7:bpas8lm) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfaaf4966b8a235dec76afb626ec70dc281ea1a3/pkg/sql/distsql/processors.proto#L161)):*
> ```protobuf
>   // orderings). If the left stream has N columns and the right stream has M
>   // columns, in this expression variables $0 to $(N-1) refer to columns of the
>   // left stream and variables $N to $(N+M-1) refer to columns in the right
> ```

how are we determining what `N` and `M` are?

---

*[pkg/sql/distsql/processors.proto, line 179 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10054#-KUNL2noY-tPTtb-bKYc:-KUNL2noY-tPTtb-bKYd:b6p4a7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfaaf4966b8a235dec76afb626ec70dc281ea1a3/pkg/sql/distsql/processors.proto#L179)):*
> ```protobuf
> // table. Thus, there is no guarantee on the ordering of results that stem only
> // from the left input (in the case of LEFT_OUTER, FULL_OUTER). However, it is
> // guaranteed that results that involve the right stream preserve the ordering;
> ```

what would this look like for `LEFT JOIN` (or `FULL JOIN`) when there are no corresponding matches on the right stream?

---

*[pkg/sql/distsql/processors.proto, line 191 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10054#-KUNKHb9aDX25k5Nb1uI:-KUNKHb9aDX25k5Nb1uJ:bqxxx2) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfaaf4966b8a235dec76afb626ec70dc281ea1a3/pkg/sql/distsql/processors.proto#L191)):*
> ```protobuf
>   // orderings). If the left stream has N columns and the right stream has M
>   // columns, in this expression variables $0 to $(N-1) refer to columns of the
>   // left stream and variables $N to $(N+M-1) refer to columns in the right
> ```

see above, how are we going to determine what `N` and `M` are?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10054)*

**Comment by RaduBerinde** [comment]
TFTRs, updated

---

Review status: 2 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/sql/distsql/processors.proto, line 139 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10054#-KUNG_cheJ3fvz1QqdVE:-KUNMQM6DuGkjLaSNPzv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfaaf4966b8a235dec76afb626ec70dc281ea1a3/pkg/sql/distsql/processors.proto#L139)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary>
> 'The inputs **must** have' for more clarity.
</details>
Done.

---

*[pkg/sql/distsql/processors.proto, line 141 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10054#-KUNIuOFIRfEsgrNWisu:-KUNMQbma9s-yFT2rHgz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfaaf4966b8a235dec76afb626ec70dc281ea1a3/pkg/sql/distsql/processors.proto#L141)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary>
> `SELECT *` or some target list.
</details>
Done.

---

*[pkg/sql/distsql/processors.proto, line 144 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10054#-KUNGIuC-IuCUbL4TMtW:-KUNMTcZO2OkDrf3RDIq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfaaf4966b8a235dec76afb626ec70dc281ea1a3/pkg/sql/distsql/processors.proto#L144)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary>
> 'columns'.
</details>
Done.

---

*[pkg/sql/distsql/processors.proto, line 161 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10054#-KUNHwQCdmm6wWBX1KP6:-KUNMVsYKlxwIO58zXWZ:b-hvc5we) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfaaf4966b8a235dec76afb626ec70dc281ea1a3/pkg/sql/distsql/processors.proto#L161)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary>
> how are we determining what `N` and `M` are?
</details>
We will know once we receive the first row from each input. If that makes the code harder we can add them to the spec at that time.

---

*[pkg/sql/distsql/processors.proto, line 167 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10054#-KUNCCvaUMZx-mNrirQW:-KUNMV4K-oTizT2Leszh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfaaf4966b8a235dec76afb626ec70dc281ea1a3/pkg/sql/distsql/processors.proto#L167)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> very small nit: I had to read this a couple times to understand it, I kept waiting for the "else" counterpart to the "if". Maybe s/If the left/Assuming the left/?
</details>
Done.

---

*[pkg/sql/distsql/processors.proto, line 173 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10054#-KUNC3GQsQhoMfFLlb_8:-KUNMVUCyfEXMxrJyEgr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfaaf4966b8a235dec76afb626ec70dc281ea1a3/pkg/sql/distsql/processors.proto#L173)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> hash join processor?
</details>
Done.

---

*[pkg/sql/distsql/processors.proto, line 179 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10054#-KUNL2noY-tPTtb-bKYc:-KUNMwE67jdpIRqog3jr:b-vgwyye) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfaaf4966b8a235dec76afb626ec70dc281ea1a3/pkg/sql/distsql/processors.proto#L179)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary>
> what would this look like for `LEFT JOIN` (or `FULL JOIN`) when there are no corresponding matches on the right stream?
</details>
the previous sentence says that there is no ordering guarantee for those results 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10054#-:-KUNNMNrZZQv82yixPpC:bw7fxih)*

**Comment by irfansharif** [comment]
:lgtm:

---

Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql/processors.proto, line 179 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10054#-KUNL2noY-tPTtb-bKYc:-KUNPkzb3D1M_1nKY_RW:bz59nr9) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfaaf4966b8a235dec76afb626ec70dc281ea1a3/pkg/sql/distsql/processors.proto#L179)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> the previous sentence says that there is no ordering guarantee for those results 
</details>
*hangs head in shame*

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10054#-:-KUNPzt0h-UCAEczTcLz:bnfp4nl)*

**Comment by irfansharif** [comment]
Reviewed 1 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10054)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql/processors.proto, line 179 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10054#-KUNL2noY-tPTtb-bKYc:-KUNXW590Zht1ODPke_F:b-qkjo56) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfaaf4966b8a235dec76afb626ec70dc281ea1a3/pkg/sql/distsql/processors.proto#L179)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary>
> *hangs head in shame*
</details>
Haha, no, it's pretty hard to explain and I don't think I did a particularly good job :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10054)*

**Pull request merged**
