### PR TITLE
ui: ensure tooltips have spaces before all inline elements

### PR DESCRIPTION
**Pull request by couchand**
Wrapping up something noticed on #21517

### CODE REVIEW

**Comment by kuanluo** [comment]
Screenshot please? :)

**Review by vilterp — APPROVED** [review]
Thanks!

**Comment by couchand** [comment]
@kuanluo I knew you'd ask for that.  see if you can catch this:

old:
screen shot 2018-01-17 at 4 38 05 pm

new:
screen shot 2018-01-17 at 4 39 55 pm

**Comment by couchand** [comment]
@kuanluo I knew you'd ask for that.  See if you can catch this:

old:
screen shot 2018-01-17 at 4 38 05 pm

new:
screen shot 2018-01-17 at 4 39 55 pm

**Comment by kuanluo** [comment]
So much better! 👍

**Pull request merged**
