### PR TITLE
kvserver: misc bug rac2 bug fixes and integration testing setup

### PR DESCRIPTION
**Pull request by kvoli**
The `UsingRac2Protocol` in a `RaftMessageRequest` is used to notify
followers about the flow control protocol the range leader is using.
Populate the field so followers are informed and correctly admit work to
store queues.

---

Previously, we were not using the `raftpb.Priority` but
`admissionpb.WorkPriority` to encode commands. These priorities map to
different integers.

When the rac2 enablement level is
`replica_rac2.EnabledWhenLeaderV2Encoding`, convert the work priority to
a raft priority before encoding.

---

We wish to re-use some generally applicable testing knobs between v1 and
v2. Move the flow control v1 specific settings into
`kvflowcontrol.TestingKnobsV1`.

--- 

Thread `kvflowcontrol.TestingKnobs` through the `rac2` `Processor` and
`RangeController`. The two knobs supported allow only running
meaningful rac2 machinery against the scratch range and overwriting
token deduction amounts.

---

Part of: https://github.com/cockroachdb/cockroach/issues/130187
Release note: None

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 6 of 6 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130937#-:-O74nRysCwkm9FyVJpV5:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/replica_raft.go` line 1931 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130937#-O74lLfz217tnJcbHFEe:-O74lLfz217tnJcbHFEf:b5hm7p4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c38ca84dedcda6c4142177705d75faf4689893d7/pkg/kv/kvserver/replica_raft.go#L1931)):*
> ```Go
> 		Message:           msg,
> 		RangeStartKey:     startKey, // usually nil
> 		UsingRac2Protocol: r.flowControlV2.GetEnabledWhenLeader() == replica_rac2.EnabledWhenLeaderV2Encoding,
> ```

this needs to be `EnabledWhenLeaderV1Encoding`. The protocol is v2, but it is still using v1 entry encodings.

**Review by kvoli — COMMENTED** [review]
TYFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130937#-:-O74sXqd-TV6etF7n2MY:bzftgo7)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/replica_raft.go` line 1931 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130937#-O74lLfz217tnJcbHFEe:-O74sM7LAlYriU-Zt40n:ba2y9hd) ([raw file](https://github.com/cockroachdb/cockroach/blob/c38ca84dedcda6c4142177705d75faf4689893d7/pkg/kv/kvserver/replica_raft.go#L1931)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this needs to be `EnabledWhenLeaderV1Encoding`. The protocol is v2, but it is still using v1 entry encodings.
</blockquote></details>

Do you mean `UsingRac2Protocol: r.flowControlV2.GetEnabledWhenLeader() >= replica_rac2.EnabledWhenLeaderV1Encoding`?

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130937#-:-O756gaW77UjwwQIvI-r:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/replica_raft.go` line 1931 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130937#-O74lLfz217tnJcbHFEe:-O756Xp07Y3kJP4aFMdy:b-zh19vi) ([raw file](https://github.com/cockroachdb/cockroach/blob/c38ca84dedcda6c4142177705d75faf4689893d7/pkg/kv/kvserver/replica_raft.go#L1931)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Do you mean `UsingRac2Protocol: r.flowControlV2.GetEnabledWhenLeader() >= replica_rac2.EnabledWhenLeaderV1Encoding`?
</blockquote></details>

yep, that's what I should have said :)

**Comment by kvoli** [comment]
I haven't been able to reproduce the extended CI failure on `TestFlowControlRaftSnapshot` w/ stressrace over 30 minutes locally. 

The reason it likely fails is due to the truncate being mis-routed and then ignored.

```
I240918 16:19:36.165294 4793 kv/kvserver/batcheval/cmd_truncate_log.go:59 â‹® [T1,Vsystem,n1,s1,r1/1:â€¹/{Min-System/NodeLâ€¦}â€º] 467  attempting to truncate raft logs for another range: r70. Normally this is due to a merge and can be ignored.
```

I'm going to merge as is and track any subsequent failure in rac2. I somehow doubt this is related to the changes here, as they are mechanical non-behavior changes (I've looked back over a few times).



bors r=sumeerbhola

**Pull request merged**
