### PR TITLE
storage_test: match on range start and end keys

### LINKED ISSUE #3806: Failed tests (11265): TestStoreZoneUpdateAndRangeSplit
The following test appears to have failed:

[#11265](https://circleci.com/gh/cockroachdb/cockroach/11265):

```
1      storage/queue.go:333
1      kv/txn_coord_sender.go:754
I0113 18:44:10.649528 956 stopper.go:264  draining; tasks left:
1      storage/queue.go:333
I0113 18:44:10.650399 956 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- FAIL: TestStoreZoneUpdateAndRangeSplit (0.03s)
	client_split_test.go:546: range max bytes mismatch, got: 67108864, expected: 65536
=== RUN   TestStoreRangeSplitWithMaxBytesUpdate
I0113 18:44:10.651809 956 gossip/gossip.go:218  setting node descriptor node_id:1 address:<network_field:"localhost" address_field:"1" > attrs:<> 
W0113 18:44:10.653106 956 gossip/gossip.go:445  bad address from gossip node {1 1 }: gossip/resolver/resolver.go:96: unknown address network "localhost" for 1
I0113 18:44:10.655354 956 raft/raft.go:446  [group 1] 1 became follower at term 5
I0113 18:44:10.655610 956 raft/raft.go:234  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0113 18:44:10.655766 956 raft/raft.go:526  [group 1] 1 is starting a new election at term 5
I0113 18:44:10.655882 956 raft/raft.go:459  [group 1] 1 became candidate at term 6
I0113 18:44:10.656011 956 raft/raft.go:508  [group 1] 1 received vote from 1 at term 6
I0113 18:44:10.656143 956 raft/raft.go:487  [group 1] 1 became leader at term 6
--
I0113 18:44:16.125046 956 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestLogSplits (1.02s)
	<autogenerated>:28: prior leak detected, leaktest disabled
=== RUN   Example_rebalancing
--- PASS: Example_rebalancing (0.90s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	28.539s
=== RUN   TestBatchBasics
I0113 18:44:21.076334 1027 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.01s)
=== RUN   TestBatchGet
I0113 18:44:21.080807 1027 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN   TestBatchMerge
I0113 18:44:21.091995 1027 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by tamird**
Fixes #3806.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3894)

### CODE REVIEW

**Comment by andreimatei** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/gc_queue.go, line 104 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3894#-K868Np1suSJSeu6kguL:-K868Np1suSJSeu6kguM:1546661569) ([raw file](https://github.com/cockroachdb/cockroach/blob/818b4f2ae815d148eaa6f43696e57f66dcf4da7e/storage/gc_queue.go#L104)):*
@mberhault do you know if this .GC should be nullable?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3894)*

**Comment by tamird** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[storage/gc_queue.go, line 104 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3894#-K868Np1suSJSeu6kguL:-K869Qr3TvEHBv58--vV:-128371027) ([raw file](https://github.com/cockroachdb/cockroach/blob/818b4f2ae815d148eaa6f43696e57f66dcf4da7e/storage/gc_queue.go#L104)):*
FYI looks like this thing has been nullable since it came into existence in https://github.com/cockroachdb/cockroach/commit/566bbd5a6938bbc655f18ee89acad057e2c0fce1#diff-20152aa58aec6712444019753e883c14R102

@spencerkimball any insight you can provide here?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3894)*

**Comment by vivekmenezes** [comment]
LGTM

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/client_split_test.go, line 539 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3894#-K86AI9AtE5uZkW0E0ek:-K86AI9AtE5uZkW0E0el:-223541546) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e9099a74e7956e4eae5207b8a7e6fadfb57ffc4/storage/client_split_test.go#L539)):*
How has this changed? I'm assuming this is the fix. Ah I see that.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3894#-:-K86AaoQ79y4lsDnNpPg:676834233)*

**Comment by bdarnell** [comment]
LGTM

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[storage/client_split_test.go, line 539 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3894#-K86Bo4QsUoV5663JBC-:-K86Bo4QsUoV5663JBC0:923208230) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e9099a74e7956e4eae5207b8a7e6fadfb57ffc4/storage/client_split_test.go#L539)):*
We might want to check both start and end keys for future-proofing. Currently the zone config mechanisms only look at start keys, but we might want to change that .

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3894#-:-K86C5sqJ9JAdA1GB6Cp:676834233)*

**Comment by spencerkimball** [comment]
GC was allowed to be nil in order to indicate that a higher level GC policy should be utilized. Some of that context is no longer appropriate. Nothing would break to change it.

**Comment by tamird** [comment]
OK, I've changed the first commit to one that makes ZoneConfig.GC non-nullable.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/client_split_test.go, line 539 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3894#-K86Bo4QsUoV5663JBC-:-K86j9M9QzGetvoXI3XJ:98335593) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e9099a74e7956e4eae5207b8a7e6fadfb57ffc4/storage/client_split_test.go#L539)):*
That is actually asserted a little lower down in this test.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3894#-:-K86lK1uMCVb4FTpZajD:1324007220)*

**Comment by bdarnell** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/client_split_test.go, line 539 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3894#-K86Bo4QsUoV5663JBC-:-K86m-5whf4ODqD89eD1:304393129) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e9099a74e7956e4eae5207b8a7e6fadfb57ffc4/storage/client_split_test.go#L539)):*
I think the EndKey check needs to be inside the SucceedsWithin call. We don't guarantee the order in which splits happen. The zone config is applied as soon as the StartKey matches but if we're explicitly checking the end key then we could catch the range while there is still another split to do on the right side.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3894)*

**Comment by tamird** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/client_split_test.go, line 539 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3894#-K86Bo4QsUoV5663JBC-:-K86nOOykBnRLMSByU3v:-202500724) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e9099a74e7956e4eae5207b8a7e6fadfb57ffc4/storage/client_split_test.go#L539)):*
Good point. Done, and I've applied a similar treatment to the next code block.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3894)*

**Pull request merged**
