### PR TITLE
roachpb: change InitChecksum to panic when checksum is already initialized

### PR DESCRIPTION
**Pull request by vivekmenezes**
---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5307)

### CODE REVIEW

**Comment by BramGruneir** [comment]
LGTM

**Comment by tamird** [comment]
The commit message is vague. perhaps "roachpb: change InitChecksum to panic when checksum is already initialized"

:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[kv/dist_sender_test.go, line 951 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5307#-KD-_c5QMmJCJJfP0jcR:-KD-_c5QMmJCJJfP0jcS:1593137839) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d7a590b1008878a835a0a3bb07fca3798eaeabd/kv/dist_sender_test.go#L951)):*
throughout: This is not the way this method was intended to be used, I guess. Could you make copies of `val` instead?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5307#-:-KD-_JD5RYv0cbtM8tu-:-787113396)*

**Comment by vivekmenezes** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[kv/dist_sender_test.go, line 951 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5307#-KD-_c5QMmJCJJfP0jcR:-KD-aq1pOg1u_wXFFMSr:-582167910) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d7a590b1008878a835a0a3bb07fca3798eaeabd/kv/dist_sender_test.go#L951)):*
That's how I had originally done it until I discovered ClearChecksum.  One advantage of leaving it this way is that it also tests an InitChecksum following a ClearChecksum 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5307)*

**Comment by vivekmenezes** [comment]
Done

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5307#-:-KD-bVpDlftavKcr3F7g:676635175)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[kv/dist_sender_test.go, line 951 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5307#-KD-_c5QMmJCJJfP0jcR:-KD-bPVos_v5siwo8S4D:1996161295) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d7a590b1008878a835a0a3bb07fca3798eaeabd/kv/dist_sender_test.go#L951)):*
Testing that in dist_sender_test, which is in another package is not an advantage. I'd be in favour of adding a test for that scenario in roachpb, though.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5307)*

**Comment by tamird** [comment]
What's done?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5307#-:-KD-bm9RMdUL2tO6zlDf:339772786)*

**Comment by vivekmenezes** [comment]
I've renamed the PR and the commit message

---

Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[kv/dist_sender_test.go, line 951 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5307#-KD-_c5QMmJCJJfP0jcR:-KD-gOkyqfWHs0MtZcZH:-1144176818) ([raw file](https://github.com/cockroachdb/cockroach/blob/073a382a4c82a1e57365602006128289f34c61cb/kv/dist_sender_test.go#L951)):*
Added a test to roachpb.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5307#-:-KD-gIwX1t4voR2MyVhN:-449008931)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5307#-:-KD-gqhdsifF5P1qlNvV:1417088721)*

**Pull request merged**
