### PR TITLE
opt: generate constraints for var IN tuple, tuple inequalities

### PR DESCRIPTION
**Pull request by RaduBerinde**
With these changes, the constraints we have so far should go a long way when we start pushing them across joins.

#### opt: generate constraints for var IN tuple

Release note: None

#### opt: generate constraints from tuple inequalities

Release note: None

### CODE REVIEW

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/sql/opt/memo/expr_view.go, line 417 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24410#-L95qBs-0zcb2To75BkJ:-L95qBs-0zcb2To75BkK:b-cvcm79) ([raw file](https://github.com/cockroachdb/cockroach/blob/f413b6587422b9ecde1955c6bb4ca74926abfa5f/pkg/sql/opt/memo/expr_view.go#L417)):*
> ```Go
> // MatchesTupleOfConstants returns true if the expression is a TupleOp with
> // ConstValue children.
> func MatchesTupleOfConstants(ev ExprView) bool {
> ```

[nit] why not call it `IsTupleOfConstants`?

---

*[pkg/sql/opt/memo/testdata/logprops/constraints, line 381 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24410#-L95rcgP-T3jwpgLtVZ1:-L95rcgP-T3jwpgLtVZ2:b-v1wwz1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f413b6587422b9ecde1955c6bb4ca74926abfa5f/pkg/sql/opt/memo/testdata/logprops/constraints#L381)):*
> ```
> 
> opt
> SELECT * FROM a WHERE (x, y) >= (1, 2.5)
> ```

Can you add comments about what this and the next two tests are testing?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24410#-:-L95rv5u7mTafUmt2A7l:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 3 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/memo/expr_view.go, line 417 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24410#-L95qBs-0zcb2To75BkJ:-L95scif7MjK1BQWY7k1:b-acldoy) ([raw file](https://github.com/cockroachdb/cockroach/blob/f413b6587422b9ecde1955c6bb4ca74926abfa5f/pkg/sql/opt/memo/expr_view.go#L417)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] why not call it `IsTupleOfConstants`?
</blockquote></details>

Hmm, this was moved from `norm` (it used to be in `xform` and that part of the change disappeared in the rebase). Fixed.

It was named like this because it was meant to be part of a set of functions used for matching rules.. I like `IsTupleOfConstants` more too, @andy-kimball is that ok? Or would you want this in a separate `match.go` file?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24410)*

**Comment by RaduBerinde** [comment]
Review status: 3 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/opt/memo/testdata/logprops/constraints, line 381 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24410#-L95rcgP-T3jwpgLtVZ1:-L95wqa77nbzAX5rUMGr:bwwpvbh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f413b6587422b9ecde1955c6bb4ca74926abfa5f/pkg/sql/opt/memo/testdata/logprops/constraints#L381)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Can you add comments about what this and the next two tests are testing?
</blockquote></details>

Done (for all added tests)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24410)*

**Comment by rytaft** [comment]
Reviewed 3 of 5 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24410)*

**Pull request merged**
