### PR TITLE
ui: allow stmts page to search across explain plan page

### LINKED ISSUE #71615: ui: allow stmts page search across logical plan text
**Is your feature request related to a problem? Please describe.**
I'd like to identify queries using a specific index, today the search is going against stmt text only, and unless stmt uses an index hint, my search query is not possible.

**Describe the solution you'd like**
index the logical plan text so that search by index name is possible.

**Describe alternatives you've considered**
no solution today

image
image

### PR DESCRIPTION
**Pull request by gtr**
Closes #71615.
    
Previously, the search functionality for the stmts page only allowed a search
through the statement query. This change adds the statement's Plan as part of
that search.

Release note (ui change): logical plan text included in searchable text for
stmts page.

Demo video: shows that the search feature works for statements' plan

https://user-images.githubusercontent.com/35943354/150594026-ba6325b1-90f1-4830-9b88-c021d4781596.mov

### CODE REVIEW

**Comment by gtr** [comment]
Closes PR [#74820](https://github.com/cockroachdb/cockroach/pull/74820). I had to switch to this PR since I had the fork on the main cockroach repository, not my fork. Thanks for the feedback on the other PR! 😄

**Review by jocrl — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75097)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75097#-Mtj5GTM0Liqi3w3Vjnk:-Mtj5GTM0Liqi3w3Vjnl:bp43mhj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e62728ec2edd23eb251f5c332301edbb6adddff5/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx#L64)):*
> ```XML
> }
> 
> // planNodeAttributesToString recursively converts a FlatPlanNode into a string.
> ```

Yay functions!

nit: s/planNodeAttributesToString/planNodeToString
___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx, line 430 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75097#-MtjEK965NzUrGZp1JWj:-MtjEK965NzUrGZp1JWk:br2k6cj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e62728ec2edd23eb251f5c332301edbb6adddff5/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L430)):*
> ```XML
>       .filter(statement => (filters.fullScan ? statement.fullScan : true))
>       .filter(statement =>
>         search ? filterBySearchQuery(statement, search) : true,
> ```

Archer brought up in the prior PR that he's concerned about the performance implications of running all this every time the filter is changed (and actually, on every render).

What kind of data did you use when you were building this? I think it would be helpful to test out your filter feature with a larger table to see if you indeed run into performance issues. You can do via the following, and happy to pair if you're confused/stuck
- go to the statements table for a [cluster on staging](https://management-staging.crdb.io/cluster/d34e1413-9b31-4a6f-90e1-c194f871845f/sql-activity?tab=Statements), turn on `App: $internal` in the filters, and change the start time to like a year back to get more statements. You should get ~700 rows
- Right click -> inspect -> Network tab -> refresh and get the return response for the statements endpoint
- [Run storybook](https://github.com/cockroachdb/cockroach/blob/825d63326866711b950ba600eed6b91059d61862/pkg/ui/workspaces/cluster-ui/README.md#storybook)
- Feed the statement response into the [storybook fixtures for the statements page](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.fixture.ts#L287), and view the story for the statements page
- Test if you have performance issues when filtering 🙂. If you do, now you have an environment where you can test whether you successfully fix them. And if you don't, maybe quadruple the number of rows for good measure and see if you do. @xinhaoz's been dealing with issues from having too much data in the statements page, and I'm not sure what the order of magnitude of rows for that is.
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.spec.tsx, line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75097#-MtjJicMCQpFwitOInm2:-MtjJicMCQpFwitOInm3:bq2kybg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e62728ec2edd23eb251f5c332301edbb6adddff5/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.spec.tsx#L284)):*
> ```XML
>         "Into users(id, city, name, address, credit_card) Size 5 columns, 3 rows";
> 
>       assert.deepEqual(planNodeAttrsToString(testNodeAttrs), expectedString);
> ```

nit: I don't think you need to deep equal a string? `assert.equal` should do here, and same for the others.
docs for assert: https://www.chaijs.com/api/assert/#method_equal
shallow vs deep equality: https://stackoverflow.com/questions/5703609/what-is-the-difference-between-being-shallowly-and-deeply-equal-how-is-this-app

**Review by jocrl — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75097)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx, line 430 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75097#-MtjEK965NzUrGZp1JWj:-MtjLz4nANe2hMs8VpdD:b9gmiyw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e62728ec2edd23eb251f5c332301edbb6adddff5/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L430)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

Archer brought up in the prior PR that he's concerned about the performance implications of running all this every time the filter is changed (and actually, on every render).

What kind of data did you use when you were building this? I think it would be helpful to test out your filter feature with a larger table to see if you indeed run into performance issues. You can do via the following, and happy to pair if you're confused/stuck
- go to the statements table for a [cluster on staging](https://management-staging.crdb.io/cluster/d34e1413-9b31-4a6f-90e1-c194f871845f/sql-activity?tab=Statements), turn on `App: $internal` in the filters, and change the start time to like a year back to get more statements. You should get ~700 rows
- Right click -> inspect -> Network tab -> refresh and get the return response for the statements endpoint
- [Run storybook](https://github.com/cockroachdb/cockroach/blob/825d63326866711b950ba600eed6b91059d61862/pkg/ui/workspaces/cluster-ui/README.md#storybook)
- Feed the statement response into the [storybook fixtures for the statements page](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.fixture.ts#L287), and view the story for the statements page
- Test if you have performance issues when filtering 🙂. If you do, now you have an environment where you can test whether you successfully fix them. And if you don't, maybe quadruple the number of rows for good measure and see if you do. @xinhaoz's been dealing with issues from having too much data in the statements page, and I'm not sure what the order of magnitude of rows for that is.
</blockquote></details>

*Actually*, now that we have the ability to point local frontends to staging backends, you can instead [run that](https://github.com/cockroachlabs/managed-service#ui-only-development) and see if the filter has performance issues on a staging cluster.

**Review by Azhng — COMMENTED** [review]
Nice! Glad to see it's starting to come together! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75097#-:-MtnUIp45Jt4bWGnpAX5:b-vi05ha)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx, line 70 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75097#-MtnRSzw01zqnV20uVf7:-MtnRSzw01zqnV20uVf8:bz5pfm7) ([raw file](https://github.com/cockroachdb/cockroach/blob/fba0e2e30f8853c1a73cd949f740e726e0a09dda/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx#L70)):*
> ```XML
>   if (plan.children.length > 0) {
>     return plan.children
>       .map(child => `${str} ${planNodeToString(child)}`)
> ```

Hmm, are we duplicating the `${str}` for each child of the plan here? 
___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx, line 430 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75097#-MtjEK965NzUrGZp1JWj:-MtnVFNO7cLSFfEWA9gx:be4qk62) ([raw file](https://github.com/cockroachdb/cockroach/blob/e62728ec2edd23eb251f5c332301edbb6adddff5/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L430)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

*Actually*, now that we have the ability to point local frontends to staging backends, you can instead [run that](https://github.com/cockroachlabs/managed-service#ui-only-development) and see if the filter has performance issues on a staging cluster.
</blockquote></details>

Just some thoughts here. Since the full text match search is likely the most expensive part of the filtering, it might be better if we move this filtering to the bottom of the chain of `filters`, where most of the statements has been filtered out using other relatively cheap filters (e.g. latency threshold, sql type etc.) 
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.spec.tsx, line 352 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75097#-MtnUTyy-hpN9hUbLkPu:-MtnUTyy-hpN9hUbLkPv:b-juaoaj) ([raw file](https://github.com/cockroachdb/cockroach/blob/fba0e2e30f8853c1a73cd949f740e726e0a09dda/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.spec.tsx#L352)):*
> ```XML
>       const expectedString =
>         "render  group (scalar)  filter filter variable = _ virtual table table cluster_settings@primary";
>       assert.deepEqual(planNodeToString(testPlanNode), expectedString);
> ```

Let's also test the top-level `filteryByQueryString` too as well

**Comment by gtr** [comment]
Thanks for the feedback @jocrl @Azhng @xinhaoz! I made the requested changes and tested the performance of my filter function by populating the statements page with 915 statements and the filter function works just fine.

**Review by jocrl — COMMENTED** [review]
Yay! A question for everyone else - what're our general guidelines for when the PR description should include a before/after screenshot or video? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75097#-:-MttOViR6UkoptATz758:bu9mtd6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr and @xinhaoz)

**Review by maryliag — COMMENTED** [review]
@jocrl  For UI changes, the PR must include the before/after images. For behaviour changes, videos are not required, but are welcomed.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75097#-:-MttXlv24kGxPOSl_gqT:b9z0uey)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr and @xinhaoz)

**Review by jocrl — COMMENTED** [review]
🎉 lgtm! Whenever you get the TeamCity build fixed 😉

For that, you want to go to the "build log" tab and find the error


It looks like eslint errors, which you can set up to auto-format on save in your editor. I know I'm saying that it's eslint, but make sure you know how to go to TeamCity and find the error 😛

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75097#-:-MtxoUgj07Rx7OrMebM1:b-vw6opk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr and @xinhaoz)

**Review by xinhaoz — APPROVED** [review]
Nice work! Changes look good granted CI passes. Thanks for testing it!

> Reviewed 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75097#-:-MtyLk1U1WDislXWDd3c:b-hrw79r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @gtr, @jocrl, @maryliag, and @xinhaoz)

**Review by maryliag — APPROVED** [review]
Great job on this issue! :lgtm: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75097#-:-MuD2dQWCnHEJAQscsRk:baup4u0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng, @gtr, @jocrl, @maryliag, and @xinhaoz)

**Pull request merged**
