### PR TITLE
raft: periodically broadcast MsgDeFortifyLeader 

### PR DESCRIPTION
**Pull request by arulajmani**
See individual commits.

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132580)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`-- commits` line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/132580#-O9Ax7mdAY3uz7Sg1maJ):*
`s/prevented from another/prevented another/`
___
*[`pkg/raft/raft.go` line 1080 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132580#-O9AwGoy0wLde5VurUeA:-O9AwGoy0wLde5VurUeB:b-wj912i) ([raw file](https://github.com/cockroachdb/cockroach/blob/606b82acc1d8d7edef710e55c415bab0e3aa512e/pkg/raft/raft.go#L1080)):*
> ```Go
> 
> 	if r.pastElectionTimeout() {
> 		if r.shouldBcastDeFortify() {
> ```

Does this logic mean that once `r.pastElectionTimeout()` starts returning true, we will defortify on every tick until we decide to call an election? So for cases like demoted non-voters, we'll defortify on every tick.

Tying this all to `electionElapsed` gets pretty tricky to think about. Maybe we should just introduce a new `defortifyElapsed` counter.

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132580)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/raft/raft.go` line 1080 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132580#-O9AwGoy0wLde5VurUeA:-O9AyQlYAK7FJ5ElNhba:b-lwopb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/606b82acc1d8d7edef710e55c415bab0e3aa512e/pkg/raft/raft.go#L1080)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does this logic mean that once `r.pastElectionTimeout()` starts returning true, we will defortify on every tick until we decide to call an election? So for cases like demoted non-voters, we'll defortify on every tick.

Tying this all to `electionElapsed` gets pretty tricky to think about. Maybe we should just introduce a new `defortifyElapsed` counter.
</blockquote></details>

Nice catch. How do you feel about re-setting `r.electionElapsed` independent of the `r.promotable` condition? Something like:

```golang
	if r.pastElectionTimeout() {
		r.electionElapsed = 0
		if r.promotable() {
			if err := r.Step(pb.Message{From: r.id, Type: pb.MsgHup}); err != nil {
				r.logger.Debugf("error occurred during election: %v", err)
			}
		}
	}
```

The behaviour that changes as a result of this is for peer's that are in the process of receiving a snapshot (`hasNextOrInProgressSnapshot` from `promotable`). With this change, a peer which is waiting to apply a snapshot will not immediately call an election once it finishes doing so -- instead, it may have to wait for a few ticks before calling an election. This doesn't seem too meaningful in practice. 

----

I initially thought about adding a new counter as well, but I decided against it. The reasons weren't strong though -- mostly because without a new counter, we continue to have a 1:1 mapping between counters and `tick{election,heartbeat}` and I can skip the boiler plate to introduce a new counter.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132580)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/raft/raft.go` line 1080 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132580#-O9AwGoy0wLde5VurUeA:-O9B4Egv4eU95F5k2DgZ:b-py3ng7) ([raw file](https://github.com/cockroachdb/cockroach/blob/606b82acc1d8d7edef710e55c415bab0e3aa512e/pkg/raft/raft.go#L1080)):*
> How do you feel about re-setting `r.electionElapsed` independent of the `r.promotable` condition?

Seems reasonable to me, but that's independent from this issue, isn't it? Either way, we still have the early return so we can't depend on `r.pastElectionTimeout()` implying `r.electionElapsed = 0`.

> I initially thought about adding a new counter as well, but I decided against it. The reasons weren't strong though -- mostly because without a new counter, we continue to have a 1:1 mapping between counters and `tick{election,heartbeat}` and I can skip the boiler plate to introduce a new counter.

We could re-use `heartbeatElapsed`. That's not as crazy as it sounds, given that `deFortify` is a form of an "anti-heartbeat".

We could also just add a new counter. There's not much boilerplate that goes along with it.

If anything, I'd suggest we try to get rid of `wasSupportingFortifiedLeaderLastTick`, which feels like more complexity than an extra counter.

**Review by arulajmani — COMMENTED** [review]
RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132580#-:-O9BYhB69kPtlg0ycxat:bb72pd0)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/raft/raft.go` line 1080 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132580#-O9AwGoy0wLde5VurUeA:-O9BXq8cB4uY0obaYcmG:b-ez35zb) ([raw file](https://github.com/cockroachdb/cockroach/blob/606b82acc1d8d7edef710e55c415bab0e3aa512e/pkg/raft/raft.go#L1080)):*
I like the idea of re-using `heartbeatElapsed` here. I left a TODO in the code to rename this to `fortificationElapsed`, which I think we should do as fortification continues to become the hot trend in the package and heartbeats take a back seat. Viewing this as `fortificationElapsed` instead of `heartbeatElapsed`, de-fortifying at this quanta doesn't seem crazy at all.

One other downside of my initial approach, of using `electionElapsed` and `pastElectionTimeout` is that it would've made de-fortification quanta random, which begs a few questions on why. 

> If anything, I'd suggest we try to get rid of `wasSupportingFortifiedLeaderLastTick`, which feels like more complexity than an extra counter.

I dropped the first commit.

**Review by nvb — COMMENTED** [review]
> Reviewed 11 of 11 files at r4, 10 of 10 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132580)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/raft/raft.go` line 878 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/132580#-O9Cx1A0DJ-1vFZA24Cj:-O9Cx1A16SO5bVasRagZ:bj9pq9p) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ebf733431151f5fb62eb20f5308ace3b0ea9c2b/pkg/raft/raft.go#L878)):*
> ```Go
> // to be dropped.
> func (r *raft) maybeUnpauseAndBcastAppend() {
> 	assertTrue(r.fortificationTracker.FortificationEnabled(), "should only be called when fortification is enabled")
> ```

I fear these layers of `FortificationEnabled()` checks are not only unaesthetic, but they're actually buggy. `FortificationEnabled()` can change at any time in response to cluster settings changes. To handle that, we'll want to check it in only the places where it's actually needed.
___
*[`pkg/raft/raft.go` line 883 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/132580#-O9CyzAb-6KuutPPai7E:-O9CyzAb-6KuutPPai7F:bpu2j1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bd1a12f6b0b7db0975c1dd0db129e4de09a31e3/pkg/raft/raft.go#L883)):*
> only leaders can fortify

I don't think this is what you meant to say.
- "leaders should not be de-fortifying without stepping down"?
- "leaders can only fortify"?
___
*[`pkg/raft/raft.go` line 897 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/132580#-O9CyMM67Pj4Bg6byClu:-O9CyMM67Pj4Bg6byClv:butb3xw) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bd1a12f6b0b7db0975c1dd0db129e4de09a31e3/pkg/raft/raft.go#L897)):*
> r.fortificationTracker.FortificationEnabled()

The intention of this check is correct, but we don't want to check `FortificationEnabled()`, as we can fortify some followers and then have `FortificationEnabled()` start returning false. We either want to send these unconditionally or want to use some other signal about whether the leader ever sent fortification messages during its term.
___
*[`pkg/raft/raft.go` line 2305 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/132580#-O9CzPkx-tNWJcU9mPAD:-O9CzPkx-tNWJcU9mPAE:bblm79m) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bd1a12f6b0b7db0975c1dd0db129e4de09a31e3/pkg/raft/raft.go#L2305)):*
> ```Go
> func (r *raft) handleDeFortify(m pb.Message) {
> 	assertTrue(r.state != pb.StateLeader, "leaders should locally de-fortify without sending a message")
> 	assertTrue(r.lead == 0 || r.lead == m.From, "only the leader should send de-fortification requests")
> ```

nit: `s/0/None/`

**Review by arulajmani — COMMENTED** [review]
Pulled https://github.com/cockroachdb/cockroach/pull/132715 out to iterate over an open question, so that just leaves the last 2 commits for review on this one. Sorry if pulling out the PR complicated things needlessly. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132580#-:-O9HmTpL9qK5pWiLUebP:b2fs0xa)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/raft/raft.go` line 878 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/132580#-O9Cx1A0DJ-1vFZA24Cj:-O9HkHDs1hoEApgu0wRr:bwvd9qp) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ebf733431151f5fb62eb20f5308ace3b0ea9c2b/pkg/raft/raft.go#L878)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I fear these layers of `FortificationEnabled()` checks are not only unaesthetic, but they're actually buggy. `FortificationEnabled()` can change at any time in response to cluster settings changes. To handle that, we'll want to check it in only the places where it's actually needed.
</blockquote></details>

I'll close this thread out now that we have https://github.com/cockroachdb/cockroach/pull/132715. 
___
*[`pkg/raft/raft.go` line 883 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/132580#-O9CyzAb-6KuutPPai7E:-O9Hkuot87yiN3rk-b3C:b-llwjtn) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bd1a12f6b0b7db0975c1dd0db129e4de09a31e3/pkg/raft/raft.go#L883)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> only leaders can fortify

I don't think this is what you meant to say.
- "leaders should not be de-fortifying without stepping down"?
- "leaders can only fortify"?
</blockquote></details>

My bad, should've double checked auto complete.
___
*[`pkg/raft/raft.go` line 897 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/132580#-O9CyMM67Pj4Bg6byClu:-O9Hk1TwEH5GcU8YduTP:b3bximn) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bd1a12f6b0b7db0975c1dd0db129e4de09a31e3/pkg/raft/raft.go#L897)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> r.fortificationTracker.FortificationEnabled()

The intention of this check is correct, but we don't want to check `FortificationEnabled()`, as we can fortify some followers and then have `FortificationEnabled()` start returning false. We either want to send these unconditionally or want to use some other signal about whether the leader ever sent fortification messages during its term.
</blockquote></details>

Discussed this offline, and. as a result, pulled out https://github.com/cockroachdb/cockroach/pull/132715.

**Review by nvb — COMMENTED** [review]
I _think_ this will be good once https://github.com/cockroachdb/cockroach/pull/132715 lands and this gets rebased, but I'll take one more quick pass after that point. Just ping me when this is ready.

> Reviewed 7 of 7 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132580#-:-O9IVnYwDdDTKB6dXSTF:b-eoj9av)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by arulajmani** [comment]
Rebased, and should be good for a look @nvanbenschoten.

**Review by nvb — APPROVED** [review]
LGTM!

**Comment by arulajmani** [comment]
Thanks! Rebased to fix a merge conflict. 

bors r=nvanbenschoten

**Pull request merged**
