### PR TITLE
roachtest: update version map and test fixtures for 23.1

### PR DESCRIPTION
**Pull request by e-mbrown**
This PR generates v22.2 fixtures for `acceptance/mixed-version`, so the test can run on v23.1

Release note: None
Epic: RE-242

### CODE REVIEW

**Review by celiala — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91010)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachtest/fixtures/1/checkpoint-v22.1-76.tgz` line 0 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91010#-NFjVV-59S9sgQAGAAWo:-NFjVV-6-vCHGae6Tt7M:b-qtb46m) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1501d26d94c12159ee1d846fabe037f8ada4918/pkg/cmd/roachtest/fixtures/1/checkpoint-v22.1-76.tgz#L0)):*
:thinking: I'm pretty sure these 22.2 fixture files should be named `v22.2.tgz` instead of `v22.1-76.tgz`

wondering if we missed a step here? maybe one of @tbg @dt or someone on TestEng could advise?

FYI this is the runbook that the release team is following:

https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/2713911496/Regenerate+fixtures+in+pkg+cmd+roachtest

**Review by celiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91010)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachtest/fixtures/1/checkpoint-v22.1-76.tgz` line  at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91010#-NFjVV-59S9sgQAGAAWo:-NFk7GYd9YPOxuc_BQJ_:bt2qv23) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1501d26d94c12159ee1d846fabe037f8ada4918/pkg/cmd/roachtest/fixtures/1/checkpoint-v22.1-76.tgz#L)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

:thinking: I'm pretty sure these 22.2 fixture files should be named `v22.2.tgz` instead of `v22.1-76.tgz`

wondering if we missed a step here? maybe one of @tbg @dt or someone on TestEng could advise?


</blockquote></details>

This is my bad: I think the runbook was missing some steps. Investigating / retrying now.

**Review by srosenberg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91010)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @smg260, and @tbg)

___
*[`pkg/cmd/roachtest/fixtures/1/checkpoint-v22.1-76.tgz` line  at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91010#-NFjVV-59S9sgQAGAAWo:-NFk9LSR-Ulq14AE5pgZ:b-nerwwx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1501d26d94c12159ee1d846fabe037f8ada4918/pkg/cmd/roachtest/fixtures/1/checkpoint-v22.1-76.tgz#L)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

This is my bad: I think the runbook was missing some steps. Investigating / retrying now.
</blockquote></details>

The problem seems to be with the `binaryVersion` embedded into the published`v22.2.0-beta.4` binary,

```
./cockroach version |grep "Build Tag"
Build Tag:        v22.2.0-beta.4
```

```
gdb cockroach
watch 'github.com/cockroachdb/cockroach/pkg/clusterversion.binaryVersion'
run start-single-node --insecure --listen-addr localhost:9090 --http-addr localhost:9091

Thread 1 "cockroach" hit Hardware watchpoint 1: 'github.com/cockroachdb/cockroach/pkg/clusterversion.binaryVersion'

Old value = {Major = 22, Minor = 1, Patch = 0, Internal = 0}
New value = {Major = 22, Minor = 1, Patch = 0, Internal = 76}
```

**Comment by dt** [comment]
It'll be 22.2 once we merge the 22.2 version mint PRs and cut rc.1

**Comment by srosenberg** [comment]
> It'll be 22.2 once we merge the 22.2 version mint PRs and cut rc.1

I didn't realize that `22.2` beta's binary version was intentionally derived from the last version of `22.1`. That definitely confused me and probably others. Why didn't we opt for a dummy offset (relative to `22.2`)?

**Comment by dt** [comment]
It isn't the last 22.1 version. "22.1-76" means "76 versions *after* 22.1", ie those are 38 2-part gates/migrations we step through _in 22.2_ to get to "22.2"  -- the end point, where we're on the final 22.2 version.

**Comment by srosenberg** [comment]
> It isn't the last 22.1 version. "22.1-76" means "76 versions _after_ 22.1", ie those are 38 2-part gates/migrations we step through _in 22.2_ to get to "22.2" -- the end point, where we're on the final 22.2 version.

I get that it's an _internal_ version which denotes a migration. The surprising part is that beta has `22.1` prefix whereas rc is `22.2`. To the end user, the internal version is virtually meaningless; seeing `22.1-76` show up as your node binary while you've just upgraded to `22.2` beta is rather unconventional.

**Comment by dt** [comment]
> seeing 22.1-76 show up as your node binary while you've just upgraded to 22.2 beta

The thing is though that you haven't upgraded to 22.2 cluster version yet, if you're on a 22.2 beta -- you've upgraded to something after 22.1, but before 22.2. We call that something 22.1+76 steps. If you'd upgraded to an earlier beta, you might have only had the first 72 steps or 74, so we need a numbering system to number these migrations from 22.1 to 22.2 -- right now it is counting up many things we've added to 22.2.

You could argue that 22.2-100 should sort as less than 22.2 rather than as greater, and further more that 22.2-4 should sort greater than 22.2-2, and then the numbering would be 22.1 -> 22.2-2 -> 22.2-4 -> ... 22.2-76 -> 22.2, but given existing nodes sort the opposite this would be a slightly tricky change to pull off for not practical difference in behavior.

**Comment by celiala** [comment]
Correct me if I'm misunderstanding but:

* `pkg/cmd/roachtest/fixtures/{n}/checkpoint-v22.1-76.tgz` is expected since we haven't yet merged the minting PR (version gate for v22.2).
* but what we want for roachtest (for this PR) is simply to rename s/checkpoint-v22.1-76.tgz/checkpoint-v22.2.tgz/ . (i.e. if we haven't yet minted the previous release, then the release team should add a step in our fixture-generation runbook to do this rename step.

**Comment by celiala** [comment]
I just manually renamed `v22.1-76.tgz` to `v22.2.tgz`. Adding @dt @tbg as reviewers to confirm that this is all that needs to be done.

**Review by celiala — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91010#-:-NFpP2mf3giBYGu16u2J:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @smg260, and @tbg)

**Review by srosenberg — APPROVED** [review]
:lgtm:

I think it's safe to merge. I double-checked that the previous version's fixtures followed the same pattern. That is, `checkpoint-v22.1.tgz` has the binaryVersion of `21.2-112` which coincides with the last migration step before `22.1` rc was cut.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91010#-:-NFq3MB74nLH2Zq4Z3XC:bsf5ak1)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @dt, @smg260, and @tbg)

**Comment by renatolabs** [comment]
bors r=celiala,srosenberg

Build timed out for unrelated reasons, I believe. Retrying.

**Comment by celiala** [comment]
I see "Build failed". retrying:

bors r+

**Comment by celiala** [comment]
acceptance test dependency failed, but I didn't see anything obvious (maybe a flake).

trying once more 

bors r+

**Comment by celiala** [comment]
bors cancel

**Pull request merged**
