### PR TITLE
opt/constraint: ConsolidateSpans, ExactPrefix

### PR DESCRIPTION
**Pull request by RaduBerinde**
ConsolidateSpans is used to coalesce spans that have consecutive
boundaries, e.g. `[/1 - /3] [/4 - /6] -> [/1 - /6]`.

ExactPrefix figures out the prefix of columns which are constrained to
a single value.

We also bring in some testing machinery from `idxconstraint`, which
allows specifying spans in string form.

Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/constraint/constraint.go, line 299 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24152#-L8DWu6LdpJYt2Pu-NHg:-L8DWu6LdpJYt2Pu-NHh:b79yx3k) ([raw file](https://github.com/cockroachdb/cockroach/blob/15102997010a990b937bb3f2b78778849f7214be/pkg/sql/opt/constraint/constraint.go#L299)):*
> ```Go
> // ConsolidateSpans merges spans that have consecutive boundaries. For example:
> //   [/1 - /2] [/3 - /4] becomes [/1 - /4].
> func (c *Constraint) ConsolidateSpans(evalCtx *tree.EvalContext) {
> ```

Would this be something that could/should be integrated into `Spans.SortAndMerge`? Would you want to do this every time you sort and merge so that constraints have a guarantee they're as simplified as possible?

---

*[pkg/sql/opt/constraint/key.go, line 309 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24152#-L8DXzP_F79nRyTWxPTX:-L8DXzP_F79nRyTWxPTY:bbm8esv) ([raw file](https://github.com/cockroachdb/cockroach/blob/15102997010a990b937bb3f2b78778849f7214be/pkg/sql/opt/constraint/key.go#L309)):*
> ```Go
> //  - all but the last datums match between a and b,
> //  - the last datum of b is the next datum after a (for types that support it).
> func (c *KeyContext) AreKeysConsecutive(a, b Key) bool {
> ```

I'd expect this to be a method on `Key` that uses the `Compare` and `Next` methods on `KeyContext`, maybe like this:
```
`func (k Key) IsConsecutiveWith(other Key) bool {
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24152)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/constraint/constraint.go, line 299 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24152#-L8DWu6LdpJYt2Pu-NHg:-L8DZWF_D3x7F1-nrrCZ:b-imbv6m) ([raw file](https://github.com/cockroachdb/cockroach/blob/15102997010a990b937bb3f2b78778849f7214be/pkg/sql/opt/constraint/constraint.go#L299)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Would this be something that could/should be integrated into `Spans.SortAndMerge`? Would you want to do this every time you sort and merge so that constraints have a guarantee they're as simplified as possible?
</blockquote></details>

The problem is that the index constraints code doesn't do as good of a job if we consolidate "eagerly". For example `a IN (1,2) AND b=3`. If we start with `[/1 - /1] [/2 - /2]` we can refine that to `[/1/3 - /1/3] [/2/3 - /2/3]` but if we merge them early we end up with `[/1/3 - /2/3]`. Granted, this is because of limitations in that code - it should try to break up spans like `[/1 - /2]` in cases like this but there are various difficulties there.

---

*[pkg/sql/opt/constraint/key.go, line 309 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24152#-L8DXzP_F79nRyTWxPTX:-L8D_NzGAZ5eKRA1YEwb:bcgvmiy) ([raw file](https://github.com/cockroachdb/cockroach/blob/15102997010a990b937bb3f2b78778849f7214be/pkg/sql/opt/constraint/key.go#L309)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I'd expect this to be a method on `Key` that uses the `Compare` and `Next` methods on `KeyContext`, maybe like this:
```
`func (k Key) IsConsecutiveWith(other Key) bool {
```
</blockquote></details>

I figured `AreKeysConsecutive` is more clear. `IsConsecutiveWith` doesn't say which needs to come first. An alternative is a global `AreKeysConsecutive(keyCtx *KeyContext, a, b Key)` (though I don't see much difference between that and a method on KeyContext)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24152)*

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/constraint/constraint.go, line 299 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24152#-L8DWu6LdpJYt2Pu-NHg:-L8DamZu8066xaISua6k:bv56fo0) ([raw file](https://github.com/cockroachdb/cockroach/blob/15102997010a990b937bb3f2b78778849f7214be/pkg/sql/opt/constraint/constraint.go#L299)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The problem is that the index constraints code doesn't do as good of a job if we consolidate "eagerly". For example `a IN (1,2) AND b=3`. If we start with `[/1 - /1] [/2 - /2]` we can refine that to `[/1/3 - /1/3] [/2/3 - /2/3]` but if we merge them early we end up with `[/1/3 - /2/3]`. Granted, this is because of limitations in that code - it should try to break up spans like `[/1 - /2]` in cases like this but there are various difficulties there.
</blockquote></details>

OK, makes sense.

---

*[pkg/sql/opt/constraint/key.go, line 309 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24152#-L8DXzP_F79nRyTWxPTX:-L8Dat5mB4mr67rM6Ug8:b-98wdbg) ([raw file](https://github.com/cockroachdb/cockroach/blob/15102997010a990b937bb3f2b78778849f7214be/pkg/sql/opt/constraint/key.go#L309)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I figured `AreKeysConsecutive` is more clear. `IsConsecutiveWith` doesn't say which needs to come first. An alternative is a global `AreKeysConsecutive(keyCtx *KeyContext, a, b Key)` (though I don't see much difference between that and a method on KeyContext)
</blockquote></details>

Could be `IsPreviousKey`, maybe?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24152#-:-L8DaqMa1re3-64kFBCf:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/opt/constraint/key.go, line 309 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24152#-L8DXzP_F79nRyTWxPTX:-L8DhDpsAyNjSlIhCFRN:b-wlbupz) ([raw file](https://github.com/cockroachdb/cockroach/blob/15102997010a990b937bb3f2b78778849f7214be/pkg/sql/opt/constraint/key.go#L309)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Could be `IsPreviousKey`, maybe?
</blockquote></details>

Done, flipped it to `IsNextKey`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24152)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/constraint/constraint.go, line 300 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/24152#-L8Dx-d6H0plDjGvssHN:-L8DwG81gyN5NrlCXf9v:b-es2uys) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff10d20269bd778b056688f493e1dd5009f74ed7/pkg/sql/opt/constraint/constraint.go#L300)):*
> ```Go
> //   [/1 - /2] [/3 - /4] becomes [/1 - /4].
> func (c *Constraint) ConsolidateSpans(evalCtx *tree.EvalContext) {
> 	if c.IsContradiction() {
> ```

What about `IsUnconstrained`? Shouldn't that also cause an early exit? 

---

*[pkg/sql/opt/constraint/constraint_test.go, line 354 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/24152#-L8E-0pCYeDGSyl9CFuM:-L8E-0pCYeDGSyl9CFuN:b4v36cf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff10d20269bd778b056688f493e1dd5009f74ed7/pkg/sql/opt/constraint/constraint_test.go#L354)):*
> ```Go
> 		},
> 		{
> 			s: "[/1 - /2]",
> ```

this is a duplicate test

---

*[pkg/sql/opt/constraint/constraint_test.go, line 473 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/24152#-L8E-o4pm4sSOa-q13le:-L8E-o4pm4sSOa-q13lf:bym58np) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff10d20269bd778b056688f493e1dd5009f74ed7/pkg/sql/opt/constraint/constraint_test.go#L473)):*
> ```Go
> 
> // parseSpans parses a list of spans with integer values like:
> //   "[/1 - /2], [/5 - /6]
> ```

`"[/1 - /2], [/5 - /6]` -> `[/1 - /2] [/5 - /6]`

(The comma is confusing - the actual test cases don't have a comma. Also you have a stray quotation mark)

Alternatively, you could separate the spans with a comma and just split on ", ". Then you could avoid rejoining the 3 pieces together below....

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24152#-:-L8E1B0hO31MhhsW81Z8:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/constraint/constraint.go, line 300 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24152#-L8Dx-d6H0plDjGvssHN:-L8E5OM_5txhJV5BZkhH:b589z8i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff10d20269bd778b056688f493e1dd5009f74ed7/pkg/sql/opt/constraint/constraint.go#L300)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

What about `IsUnconstrained`? Shouldn't that also cause an early exit? 
</blockquote></details>

The regular path is fine, it won't do anything. I had this check because I was doing somethiing with the first span in an earlier iteration. I'm removing this `if` altogether.

---

*[pkg/sql/opt/constraint/constraint_test.go, line 354 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24152#-L8E-0pCYeDGSyl9CFuM:-L8E54H49qlnXh9C7c6Y:b3b65vv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff10d20269bd778b056688f493e1dd5009f74ed7/pkg/sql/opt/constraint/constraint_test.go#L354)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

this is a duplicate test
</blockquote></details>

Fixed in the other PR

---

*[pkg/sql/opt/constraint/constraint_test.go, line 473 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24152#-L8E-o4pm4sSOa-q13le:-L8E57elAcLEY72gkwlD:b-q020jk) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff10d20269bd778b056688f493e1dd5009f74ed7/pkg/sql/opt/constraint/constraint_test.go#L473)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

`"[/1 - /2], [/5 - /6]` -> `[/1 - /2] [/5 - /6]`

(The comma is confusing - the actual test cases don't have a comma. Also you have a stray quotation mark)

Alternatively, you could separate the spans with a comma and just split on ", ". Then you could avoid rejoining the 3 pieces together below....
</blockquote></details>

That's why there was a comma in the original code, but I switched to space for consistency with String() which is used for "expected" values. Corrected the comment in the other PR.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24152)*

**Pull request merged**
