### PR TITLE
kv: use LockSpanSets to declare lock spans 

### PR DESCRIPTION
**Pull request by arulajmani**
Prior to this patch, requests would use the same mechanism
(`spanset.SpanSets`) to declare both latch and lock spans.
This patch changes the latter to use `lockspanset.LockSpanSets`
instead. This allows us to declare lock spans for a request with its
intended lock strengths in the future. This will in-turn enable us to
support multiple locking strengths in the concurrency package.

This patch does not change any functionality. To that end, requests
that would have previously declared access for `spanset.SpanReadOnly`
use `lock.None`; requests that would have previously declared
`spanset.SpanReadWrite` use `lock.Intent`. The `concurrency` package
validates lock spans with no other lock strength are supplied to it.
It does so both in the lock table waiter and when scanning the lock
table. We will relax these assertions as we build towards shared locks.

One thing to note is that I decided not to change the lock table tests
in this patch, to reduce test churn. We do so by translating lock
strength back to SpanAccess when printing out the guard state. This
will get fixed in a followup, along with the datadriven input.

Informs https://github.com/cockroachdb/cockroach/issues/102008

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 49 of 49 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102647)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/concurrency/concurrency_control.go` line 423 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102647#-NUAPUbyAJup3fB8_O_8:-NUAPUbyAJup3fB8_O_9:b-am21p0) ([raw file](https://github.com/cockroachdb/cockroach/blob/77fa2c56951b92b6b95aa8b10b67c97cfe894822/pkg/kv/kvserver/concurrency/concurrency_control.go#L423)):*
> ```Go
> 
> 	// The maximal set of spans within which the request expects to have
> 	// isolation from conflicting transactions. Conflicting locks within
> ```

We should mention strength somewhere in this comment.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1288 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102647#-NUF251W6W_nHdUpfCk0:-NUF251W6W_nHdUpfCk1:b-r8pf4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/77fa2c56951b92b6b95aa8b10b67c97cfe894822/pkg/kv/kvserver/concurrency/lock_table.go#L1288)):*
> ```Go
> 			findDistinguished = false
> 		}
> 		state.guardStrength = g.str
> ```

Does it make sense to move the assignment of `guardStregth` into `lockTableGuardImpl.updateStateLocked`?
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1631 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102647#-NUF2wZX-62xNP86ltu6:-NUF2wZX-62xNP86ltu7:b-j1g3m1) ([raw file](https://github.com/cockroachdb/cockroach/blob/77fa2c56951b92b6b95aa8b10b67c97cfe894822/pkg/kv/kvserver/concurrency/lock_table.go#L1631)):*
> ```Go
> 		// NB: If we were not defer to the stronger lock strength and start waiting
> 		// here, we would end up doing so in the wrong wait queue (queuedReaders vs.
> 		// queuedWriters.
> ```

nit: missing closing parenthesis.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1641 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102647#-NUF36n29ppSxDx7yiFg:-NUF36n29ppSxDx7yiFh:bmbdis9) ([raw file](https://github.com/cockroachdb/cockroach/blob/77fa2c56951b92b6b95aa8b10b67c97cfe894822/pkg/kv/kvserver/concurrency/lock_table.go#L1641)):*
> ```Go
> 		// reservations, we can not detect a key is being accessed with both None
> 		// and Intent locking strengths, like we can for transactional requests. In
> 		// some rare cases, the is now held at a timestamp that is not compatible
> ```

"the is now held"
___
*[`pkg/kv/kvserver/concurrency/lock/locking.go` line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102647#-NUAO-EF81EirZjDhxms:-NUAO-EF81EirZjDhxmt:b-2ajbb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1baec4dfb9b2319367edd19289be3cc67b69fa6/pkg/kv/kvserver/concurrency/lock/locking.go#L57)):*
> ```Go
> 
> // NumLockStrength is the total number of lock strengths in the Strength enum.
> const NumLockStrength = MaxStrength + 1
> ```

Consider adding an init-time validation for this constant. E.g. that `NumLockStrength == len(Strength_name)`.
___
*[`pkg/kv/kvserver/lockspanset/lockspanset.go` line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102647#-NUAOYhD76yYnLWjACl2:-NUAOYhD76yYnLWjACl3:bj2lwwi) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1baec4dfb9b2319367edd19289be3cc67b69fa6/pkg/kv/kvserver/lockspanset/lockspanset.go#L79)):*
> ```Go
> func (l *LockSpanSet) String() string {
> 	var buf strings.Builder
> 	for st := range l.spans {
> ```

```go
for st, spans := range l.spans {
    for _, span := range spans {
```
___
*[`pkg/kv/kvserver/lockspanset/lockspanset.go` line 113 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102647#-NUAPlrv2jPbxRy47sBv:-NUAPlrv2jPbxRy47sBw:b-ftupmz) ([raw file](https://github.com/cockroachdb/cockroach/blob/77fa2c56951b92b6b95aa8b10b67c97cfe894822/pkg/kv/kvserver/lockspanset/lockspanset.go#L113)):*
> ```Go
> 		return
> 	}
> 	copy(l.spans[str], existing)
> ```

Are we missing the `l.spans[str] = make([]roachpb.Span, len(existing), n+len(existing))` here?
___
*[`pkg/kv/kvserver/lockspanset/lockspanset.go` line 119 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102647#-NUAPwaj2pIweKItwj4T:-NUAPwaj2pIweKItwj4U:b-bn28pu) ([raw file](https://github.com/cockroachdb/cockroach/blob/77fa2c56951b92b6b95aa8b10b67c97cfe894822/pkg/kv/kvserver/lockspanset/lockspanset.go#L119)):*
> ```Go
> // invalid.
> func (l *LockSpanSet) Validate() error {
> 	for st := range l.spans {
> ```

Same comment about `for st, spans := range l.spans`  that was mentioned in the prior patch.
___
*[`pkg/kv/kvserver/lockspanset/lockspanset.go` line 120 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102647#-NUAQ9hy-Nc40jehcm__:-NUAQ9hy-Nc40jehcm_a:b6b3evs) ([raw file](https://github.com/cockroachdb/cockroach/blob/77fa2c56951b92b6b95aa8b10b67c97cfe894822/pkg/kv/kvserver/lockspanset/lockspanset.go#L120)):*
> ```Go
> func (l *LockSpanSet) Validate() error {
> 	for st := range l.spans {
> 		for _, sp := range l.spans[st] {
> ```

nit: `s/sp/span/`, for consistency with the rest of this file.

**Review by arulajmani — COMMENTED** [review]
Addressed everything except for the comment about `updateStateLocked`. Let me know how you feel about the proposal there. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102647#-:-NUNSq31D2qG4monTi7B:b-1335fd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1288 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102647#-NUF251W6W_nHdUpfCk0:-NUNPXfuAiiwnAwiKyk9:bvown9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/77fa2c56951b92b6b95aa8b10b67c97cfe894822/pkg/kv/kvserver/concurrency/lock_table.go#L1288)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does it make sense to move the assignment of `guardStregth` into `lockTableGuardImpl.updateStateLocked`?
</blockquote></details>

I thought about this a bit, and I don't think it makes sense in the current structure because of this call:

https://github.com/cockroachdb/cockroach/blob/2924cc5197bb5eb5756f91667aeb5174bef34506/pkg/kv/kvserver/concurrency/lock_table.go#L719

It's not a incorrect to do so, but it feels slightly weird that we're setting `guardStrength` to the value of the last lock we scanned if no conflicts were found. 

How do you feel about pulling that call and the following piece of code:
https://github.com/cockroachdb/cockroach/blob/2924cc5197bb5eb5756f91667aeb5174bef34506/pkg/kv/kvserver/concurrency/lock_table.go#L728-L733

into it's own function (say: `updateStateToDoneWaiting`). This is fine, because `startWait=true` does not need to be conditional on the value of `notify`. 

If we do that, then we could move `guardStrength` into `updateStateLocked`. Maybe even rename that function to `updateStateToWaiting` and ensure it's never called with wait kind of `doneWaiting`.

How do you feel about all this?     
___
*[`pkg/kv/kvserver/concurrency/lock/locking.go` line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102647#-NUAO-EF81EirZjDhxms:-NUNGSIUEvN91EFdpUkW:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1baec4dfb9b2319367edd19289be3cc67b69fa6/pkg/kv/kvserver/concurrency/lock/locking.go#L57)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Consider adding an init-time validation for this constant. E.g. that `NumLockStrength == len(Strength_name)`.
</blockquote></details>

Done. 
___
*[`pkg/kv/kvserver/lockspanset/lockspanset.go` line 113 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102647#-NUAPlrv2jPbxRy47sBv:-NUNHfgABXLfyquqyOG4:bpgl2zf) ([raw file](https://github.com/cockroachdb/cockroach/blob/77fa2c56951b92b6b95aa8b10b67c97cfe894822/pkg/kv/kvserver/lockspanset/lockspanset.go#L113)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Are we missing the `l.spans[str] = make([]roachpb.Span, len(existing), n+len(existing))` here?
</blockquote></details>

Yeah, thanks for catching.

**Review by nvb — COMMENTED** [review]
> Reviewed 50 of 50 files at r3, 48 of 49 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102647)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1288 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102647#-NUF251W6W_nHdUpfCk0:-NUNzhZmByYl2Uh-bgV9:b-3hjxmm) ([raw file](https://github.com/cockroachdb/cockroach/blob/77fa2c56951b92b6b95aa8b10b67c97cfe894822/pkg/kv/kvserver/concurrency/lock_table.go#L1288)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I thought about this a bit, and I don't think it makes sense in the current structure because of this call:

https://github.com/cockroachdb/cockroach/blob/2924cc5197bb5eb5756f91667aeb5174bef34506/pkg/kv/kvserver/concurrency/lock_table.go#L719

It's not a incorrect to do so, but it feels slightly weird that we're setting `guardStrength` to the value of the last lock we scanned if no conflicts were found. 

How do you feel about pulling that call and the following piece of code:
https://github.com/cockroachdb/cockroach/blob/2924cc5197bb5eb5756f91667aeb5174bef34506/pkg/kv/kvserver/concurrency/lock_table.go#L728-L733

into it's own function (say: `updateStateToDoneWaiting`). This is fine, because `startWait=true` does not need to be conditional on the value of `notify`. 

If we do that, then we could move `guardStrength` into `updateStateLocked`. Maybe even rename that function to `updateStateToWaiting` and ensure it's never called with wait kind of `doneWaiting`.

How do you feel about all this?     
</blockquote></details>

All of what you said makes sense to me. It feels wrong to set the `guardStrength` for `kind: doneWaiting`.

However, splitting the`updateStateLocked` may prove to be difficult for callers like `tryClearLock`. We could try it. If it does not work well, we could set `guardStrength` conditionally in `updateStateLocked`, based on `waitingState.kind`.

**Review by arulajmani — COMMENTED** [review]
RFAL. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102647#-:-NUOmgCX4fwwHwcDXSw6:by76qvq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1288 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102647#-NUF251W6W_nHdUpfCk0:-NUOlpj1DEBYlDMv2OvY:b-74w25c) ([raw file](https://github.com/cockroachdb/cockroach/blob/77fa2c56951b92b6b95aa8b10b67c97cfe894822/pkg/kv/kvserver/concurrency/lock_table.go#L1288)):*
Let me know how you feel about the changes to `tryClearLock`. I like where we ended up, but in case you're not a fan, the change is in its own commit so should be easy enough to reverse. 

> This is fine, because startWait=true does not need to be conditional on the value of notify.

After coming back to this, I ended up preferring a different approach. See the last commit.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 49 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102647#-:-NUXPmc51o9lTTHTcdiw:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 548 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/102647#-NUP6Wxt97XRleGoR05Y:-NUP6Wxt97XRleGoR05Z:buybg22) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6d3eff312d464c12eb83585ba33f0967e569d71/pkg/kv/kvserver/concurrency/lock_table.go#L548)):*
> ```Go
> 		panic(errors.AssertionFailedf("unexpected waiting state kind: %d", newState.kind))
> 	}
> 	newState.guardStrength = g.str // copy over the strength which cased the conflict
> ```

"caused"
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2117 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/102647#-NUXNYmQ4ivWJvRkRyfr:-NUXNYmQ4ivWJvRkRyfs:b-vyfroa) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6d3eff312d464c12eb83585ba33f0967e569d71/pkg/kv/kvserver/concurrency/lock_table.go#L2117)):*
> ```Go
> 	lockHolderTxn, _ := l.getLockHolder() // only needed if this is a replicated lock
> 	replicatedHeld := l.holder.locked && l.holder.holder[lock.Replicated].txn != nil
> 	transitionWaiter := func(g *lockTableGuardImpl) {
> ```

Does this closure introduce any new heap allocations?

**Review by arulajmani — COMMENTED** [review]
TFTR! 

bors r=nvanbenschoten 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102647#-:-NUXyxde0I4FQt6HgYUa:b-2fjird)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2117 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/102647#-NUXNYmQ4ivWJvRkRyfr:-NUXuu3YEWiJX_S4mGRC:bowjm60) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6d3eff312d464c12eb83585ba33f0967e569d71/pkg/kv/kvserver/concurrency/lock_table.go#L2117)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does this closure introduce any new heap allocations?
</blockquote></details>

I tested by wrapping a call to `tryClearLocks` in a testing.AllocsPerRun and it confirmed that this function doesn't perform any allocations, so we should be good. Ideally, we would have been able to test using `TestGCAssert`, but that seems broken from a bit of slack searching.

**Pull request merged**
