### PR TITLE
storage: remove confusing code in StorePool

### LINKED ISSUE #12204: storage: clean up handling of StorePool's concept of "dead"
In `StorePool`, `storeDetail` objects have a confused notion of liveness. When calling `storeDetail.status`, a store is not considered live unless at least one gossip has been received. When calling `storeDetail.isDead`, this notion doesn't apply. I suspect the reason to be related to unittests.

Clean this up so that `storeDetail.status` simply invokes `storeDetail.isDead`.

### PR DESCRIPTION
**Pull request by spencerkimball**
Previously, `storeDetail.status()` had a different definition of
"dead" than `storeDetail.isDead()`. This was presumably done to
avoid adding stores to the list of available stores if we didn't
have a gossiped store descriptor. This is just a slight change
for clarity and to remove a TODO.

Fixes #12204

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12206)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/store_pool.go, line 438 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12206#-KYWJ9fzXXRbSYQzopiv:-KYWJ9fzXXRbSYQzopiw:b-z8jtvm) ([raw file](https://github.com/cockroachdb/cockroach/blob/604f707a8a02403c85dd19a60f7f59063ba7d7a4/pkg/storage/store_pool.go#L438)):*
> ```Go
> 		case storeStatusAvailable:
> 			if detail.desc != nil {
> 				aliveStoreCount++
> ```

should this line be outside the nil guard?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12206)*

**Comment by spencerkimball** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/store_pool.go, line 438 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12206#-KYWJ9fzXXRbSYQzopiv:-KYWSJurY-AvX-bjFGWq:bb9zbah) ([raw file](https://github.com/cockroachdb/cockroach/blob/604f707a8a02403c85dd19a60f7f59063ba7d7a4/pkg/storage/store_pool.go#L438)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

should this line be outside the nil guard?
</blockquote></details>

Good point; still confusing. I've clarified further.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12206)*

**Comment by tamird** [comment]
What does `storeStatusUnavailable` mean? Nothing looks for it, so it's not clear what the semantics of it are. The only line that `switch`es on `detail.status` doesn't have a default clause, so it seems to be treated the same as `storeStatusDead`.

Sadly this remains confusing.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12206#-:-KYYZHnvuvypPHtazVBs:b-p9xnx7)*

**Comment by spencerkimball** [comment]
I've added more comments. Yes, for the purposes of getting a list of available stores, both `storeStatusUnavailable` and `storeStatusDead` are treated the same. I've added both to the switch with a comment. It is somewhat confusing in essence because we're taking two signals to determine various states of liveness.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12206#-:-KYZfjJ_EkYeD85sIfLB:b-j2t7kz)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/store_pool.go, line 219 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12206#-KYZi3wy4TWwAU1BYLfP:-KYZhheG9b1w53RTqdv_:bgbjsg8) ([raw file](https://github.com/cockroachdb/cockroach/blob/56feaa0987b130a0ecde28d5116a4204e683547e/pkg/storage/store_pool.go#L219)):*
> ```Go
> 		detail := sp.mu.storeDetails[id]
> 		fmt.Fprintf(&buf, "%d", id)
> 		if detail.isDead(now, sp.timeUntilStoreDead, sp.nodeLivenessFn) {
> ```

not clear that this is doing the right thing - perhaps something to consider

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12206#-:-KYZi8CKQKlKX_TATmD8:bnfp4nl)*

**Comment by spencerkimball** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/store_pool.go, line 219 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12206#-KYZi3wy4TWwAU1BYLfP:-KYZwObeqsmqez84xEIy:bs5v5pf) ([raw file](https://github.com/cockroachdb/cockroach/blob/56feaa0987b130a0ecde28d5116a4204e683547e/pkg/storage/store_pool.go#L219)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

not clear that this is doing the right thing - perhaps something to consider
</blockquote></details>

This is just for debugging. I don't think we need to make it more complicated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12206)*

**Pull request merged**
