### PR TITLE
sql: add support for scalars on the right of @> in index selection

### PR DESCRIPTION
**Pull request by m-schneider**
Closes: #21783

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[pkg/sql/opt/index_constraints.go, line 806 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22503#-L4qG2xlP43Il6Rtn_Xr:-L4qG2xlP43Il6Rtn_Xs:b-x9oxqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b967ddf25e9af3c37f73b0cb0b93c89bed2395d6/pkg/sql/opt/index_constraints.go#L806)):*
> ```Go
> // makeInvertedIndexSpansForExpr is analogous to makeSpansForExpr, but it is
> // used for inverted indexes.
> func (c *indexConstraintCtx) makeInvertedIndexSpansForExpr(offset int,
> ```

why do we need offset? it's always 0 for an inverted index 

---

*[pkg/sql/opt/index_constraints.go, line 824 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22503#-L4qI4Jl6O3GGN8XA-IQ:-L4qGGBtHOIqYp_0APc2:b4n3vgp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b967ddf25e9af3c37f73b0cb0b93c89bed2395d6/pkg/sql/opt/index_constraints.go#L824)):*
> ```Go
> 		switch rd.Type() {
> 		case json.ArrayJSONType, json.ObjectJSONType:
> 			break
> ```

[nit] move the`return` at the end here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22503)*

**Comment by rytaft** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[pkg/sql/opt_index_selection.go, line 537 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22503#-L4qqra_5xJaamcICgdB:-L4qqra_5xJaamcICgdC:bq9z6ys) ([raw file](https://github.com/cockroachdb/cockroach/blob/b967ddf25e9af3c37f73b0cb0b93c89bed2395d6/pkg/sql/opt_index_selection.go#L537)):*
> ```Go
> func (ss *spanSorter) Less(i, j int) bool {
> 	// Compare start keys.
> 	return ss.spans[i].Key.Compare(ss.spans[j].EndKey) < 0
> ```

The comment says compare start keys, but it looks like you're comparing `Key` to `EndKey`...

---

*[pkg/sql/opt/index_constraints.go, line 827 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22503#-L4qtcnF6LxciiH9sxXg:-L4qtcnF6LxciiH9sxXh:b5t6kbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/b967ddf25e9af3c37f73b0cb0b93c89bed2395d6/pkg/sql/opt/index_constraints.go#L827)):*
> ```Go
> 		default:
> 			spans := make(LogicalSpans, 2)
> 			datum := rhs.private.(tree.Datum)
> ```

Isn't this the same as `rightDatum` above?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22503)*

**Comment by m-schneider** [comment]
Please ignore the encoding change commit. This change needs to be on top of that commit in order to sort correctly.

---

Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/opt/index_constraints.go, line 806 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22503#-L4qG2xlP43Il6Rtn_Xr:-L5AE_bFqMyS2TTkZV4q:bwqrvd2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b967ddf25e9af3c37f73b0cb0b93c89bed2395d6/pkg/sql/opt/index_constraints.go#L806)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

why do we need offset? it's always 0 for an inverted index 
</blockquote></details>

Got rid of it.

---

*[pkg/sql/opt/index_constraints.go, line 824 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22503#-L4qI4Jl6O3GGN8XA-IQ:-L5AKBsWoTPF1BPPM-J9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b967ddf25e9af3c37f73b0cb0b93c89bed2395d6/pkg/sql/opt/index_constraints.go#L824)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] move the`return` at the end here
</blockquote></details>

Done.

---

*[pkg/sql/opt/index_constraints.go, line 827 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22503#-L4qtcnF6LxciiH9sxXg:-L5AFlL_s8KjNpK6hNlc:bdcv6kv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b967ddf25e9af3c37f73b0cb0b93c89bed2395d6/pkg/sql/opt/index_constraints.go#L827)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Isn't this the same as `rightDatum` above?
</blockquote></details>

Good point!

---

*[pkg/sql/opt_index_selection.go, line 537 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22503#-L4qqra_5xJaamcICgdB:-L5AEILWL-2WLf4KK9TS:bmh0yqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/b967ddf25e9af3c37f73b0cb0b93c89bed2395d6/pkg/sql/opt_index_selection.go#L537)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

The comment says compare start keys, but it looks like you're comparing `Key` to `EndKey`...
</blockquote></details>

I got rid of the whole thing. After changing the inverted key encoding, everything sorts correctly on the logical span level!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22503#-:-L5AK1BUu2fhtL94fsiu:b-msd2wd)*

**Comment by rytaft** [comment]
Reviewed 7 of 9 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/util/encoding/encoding.go, line 504 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22503#-L5A_ZgrutdzwjxAEGHB:-L5A_ZgrutdzwjxAEGHC:b5wz1dw) ([raw file](https://github.com/cockroachdb/cockroach/blob/6560c8d56a687d522611ca52de3fdaf89eee20ed/pkg/util/encoding/encoding.go#L504)):*
> ```Go
> }
> 
> // encodeBytesAscendingWithTerminator encodes the []byte value using an escape-based
> ```

Fix comment to match function name

---

*[pkg/util/encoding/encoding.go, line 637 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22503#-L5AcVUMJ7YipzunIWuu:-L5AcVUMJ7YipzunIWuv:b-uwvc8i) ([raw file](https://github.com/cockroachdb/cockroach/blob/6560c8d56a687d522611ca52de3fdaf89eee20ed/pkg/util/encoding/encoding.go#L637)):*
> ```Go
> func prettyPrintInvertedIndexKey(b []byte) (string, []byte, error) {
> 	outBytes := ""
> 	tempB := b[1:]
> ```

Can you add a comment about why you're skipping the first byte?

---

*[pkg/util/encoding/encoding.go, line 788 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22503#-L5AbagV-uia1xvYsjUU:-L5AbagV-uia1xvYsjUV:bib2a13) ([raw file](https://github.com/cockroachdb/cockroach/blob/6560c8d56a687d522611ca52de3fdaf89eee20ed/pkg/util/encoding/encoding.go#L788)):*
> ```Go
> }
> 
> // EncodeJSONAscending encodes a JSON Type. The encodes bytes are appended to the
> ```

encodes -> encoded

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22503)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/index_constraints.go, line 822 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22503#-L5Afi7llNkncg4bLfMp:-L5Afi7llNkncg4bLfMq:b78l3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/6560c8d56a687d522611ca52de3fdaf89eee20ed/pkg/sql/opt/index_constraints.go#L822)):*
> ```Go
> 			return LogicalSpans{c.makeEqSpan(0 /* offset */, rhs.private.(tree.Datum))}, true, true
> 		default:
> 			// If we find a scalar on the right side of the  @> operator it means that we need to find
> ```

[nit] extra space before `@>`

---

*[pkg/sql/opt/index_constraints.go, line 826 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22503#-L5AfrBDqxxOSn0llJG0:-L5AfrBDqxxOSn0llJG1:b5rqthg) ([raw file](https://github.com/cockroachdb/cockroach/blob/6560c8d56a687d522611ca52de3fdaf89eee20ed/pkg/sql/opt/index_constraints.go#L826)):*
> ```Go
> 			// two logical spans, one for the original scalar and one for arrays containing the scalar.
> 			// This is valid because in JSON something can either be an array or scalar so the spans are
> 			// guaranteed not to overlap.
> ```

I would explain "overlap" more clearly. The spans themselves clearly don't overlap, but what we're saying here is that there can't be duplicate results (PKs) when we scan both.

---

*[pkg/sql/opt/index_constraints.go, line 828 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22503#-L5AgYooTnxVUg3mspPU:-L5AgYop8le6KhKmoLXe:b-wrzrdh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6560c8d56a687d522611ca52de3fdaf89eee20ed/pkg/sql/opt/index_constraints.go#L828)):*
> ```Go
> 			// guaranteed not to overlap.
> 			spans := make(LogicalSpans, 2)
> 			if !c.verifyType(0, rightDatum.ResolvedType()) {
> ```

This doesn't hurt but I don't think we need this check. We already know rightDatum is DJSON or we would have crashed above. If you keep it, add `/* offset */` after `0`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22503#-:-L5AgCW8QbrCfjWYfgfu:bnfp4nl)*

**Comment by m-schneider** [comment]
Thanks!

---

Review status: 5 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/sql/opt/index_constraints.go, line 822 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22503#-L5Afi7llNkncg4bLfMp:-L5AhE137epLArG-cE5O:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6560c8d56a687d522611ca52de3fdaf89eee20ed/pkg/sql/opt/index_constraints.go#L822)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] extra space before `@>`
</blockquote></details>

Done.

---

*[pkg/sql/opt/index_constraints.go, line 826 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22503#-L5AfrBDqxxOSn0llJG0:-L5AhZDz6fHHqAk3U-JU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6560c8d56a687d522611ca52de3fdaf89eee20ed/pkg/sql/opt/index_constraints.go#L826)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I would explain "overlap" more clearly. The spans themselves clearly don't overlap, but what we're saying here is that there can't be duplicate results (PKs) when we scan both.
</blockquote></details>

Done.

---

*[pkg/sql/opt/index_constraints.go, line 828 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22503#-L5AgYooTnxVUg3mspPU:-L5AhbPMMhMhrH3KAHIm:b9dhs1d) ([raw file](https://github.com/cockroachdb/cockroach/blob/6560c8d56a687d522611ca52de3fdaf89eee20ed/pkg/sql/opt/index_constraints.go#L828)):*
> /* offset */
That makes sense!

---

*[pkg/util/encoding/encoding.go, line 504 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22503#-L5A_ZgrutdzwjxAEGHB:-L5AhlrpHXTggqooSQEB:bqeaz5c) ([raw file](https://github.com/cockroachdb/cockroach/blob/6560c8d56a687d522611ca52de3fdaf89eee20ed/pkg/util/encoding/encoding.go#L504)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Fix comment to match function name
</blockquote></details>

Thanks for the comments, I'll address them on the original PR. It's at https://reviewable.io/reviews/cockroachdb/cockroach/21889 if you want to follow!

---

*[pkg/util/encoding/encoding.go, line 637 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22503#-L5AcVUMJ7YipzunIWuu:-L5AiVCk8N7HZ5SzRBIv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6560c8d56a687d522611ca52de3fdaf89eee20ed/pkg/util/encoding/encoding.go#L637)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Can you add a comment about why you're skipping the first byte?
</blockquote></details>

Done.

---

*[pkg/util/encoding/encoding.go, line 788 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22503#-L5AbagV-uia1xvYsjUU:-L5Aj-mGFmNFK2AyeADg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6560c8d56a687d522611ca52de3fdaf89eee20ed/pkg/util/encoding/encoding.go#L788)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

encodes -> encoded
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22503#-:-L5Aj2NSnRMs9kRq-HMm:b-ucfknh)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22503#-:-L5AlHJ2yvBRlx6X3-zT:bnfp4nl)*

**Pull request merged**
