### PR TITLE
sql/parser: recognize qualified type names

### PR DESCRIPTION
**Pull request by rohany**
This PR allows the parser to recognize qualified typenames
and generic typenames.

To accomplish this, we move some type and typecast related
productions closer to how the postgres grammar operates,
and separate out type names from the unreserved_keyword_list.

Release note: None

### CODE REVIEW

**Comment by rohany** [comment]
Opening up a draft with the ideas i mentioned, please take a look!

**Comment by rohany** [comment]
Nice, the failure don't seen worrying, just slightly different output in some error messages.

**Comment by knz** [comment]
Good start!

Here are some things that postgres supports but your patch doesn't (yet):

- `SELECT 1::notatype`   (custom type name without qualification)
- `CREATE TABLE t(x notatype)`  (ditto)
- `SELECT my.type '1'`  (typed literal)
- `SELECT 1::int4.mytype`  (all the predefined type names are also valid db/schema names)

**Comment by rohany** [comment]
PTAL -- my original commit had support for the first two but I forgot to add a test. 

Adding @jordanlewis here, might have some comments.

I think that we because added type aliases as keywords (something postgres doesn't do) led to a variety of conflicts. I removed the keywords for these and moved some of these aliases to be resolved by a lookup table during parsing (it replaces what we have now, but an argument could be that this should only be done during typechecking).

For these aliases, we can reference them like you mentioned above (`select 1::int4.ty`), but for some reserved types like `select 1::int.ty` both us and postgres can't.

Additionally, it seems like allowing types to be named `FAMILY` with no quotes causes some abiguity that I can't seem to get around, which led me to separate our `type_func_name_keywords` into two sets: with and without our extensions (eg. `FAMILY`).

Does this all make sense, or am i just making this tower of blocks more fragile? I don't have a good intuition for this yet.

**Comment by rohany** [comment]
Additionally I don't see a way of parsing certain type keywords that are used in other places (like JSON, STRING) without quotes as qualified accessors for types -- e.g. I don't see a way to get `SELECT 1::json.mytype` to work due to a conflict related to the `<TYPEname> SCONST` implicit casting syntax. This casting syntax is driving a lot of keyword separation introduced in this PR.

**Comment by knz** [comment]
Well it's odd to me that this is so complex, given that pg supports it with comparatively fewer grammar rules.

**Comment by rohany** [comment]
I think I'm bringing us closer to pg here -- PG doesn't have all of these typenames in unreserved, so it doesn't run into the conflicts I'm trying to fix here (its unclear to me how it avoids conflicts for the few keywords I have left in unreserved_type_keyword). The apparent complexity of this PR is just in separating these unreserved_type_keywords and `"FAMILY"` from valid typenames. The work this PR is doing to dispatch to a known type when seeing an identifier should be removed in future PRs because it seems like type resolution that depends on a search path -- it's incorrect to be doing it at parse time here.

The most confusing this about pg's grammar around this for me is their rule for `GenericType`. it looks like this:
```
type_function_name opt_type_modifiers {
 $$ = makeTypeName($1);
 $$->typmods = $2;
 $$->location = @1;
}
```
and `type_function_name` looks like
```
type_function_name:	IDENT { $$ = $1; }
  | unreserved_keyword		{ $$ = pstrdup($1); }
  | type_func_name_keyword	{ $$ = pstrdup($1); }
```

So I don't know where they get their qualifications from.

**Comment by knz** [comment]
You misread pg's grammar:

```
GenericType:
            type_function_name opt_type_modifiers
            | type_function_name attrs opt_type_modifiers
        ;
```

The magic is in `attrs` (like it was in crdb's original .y file)

**Comment by rohany** [comment]
Alright, I was able to simplify this more. I got rid of the separation between reserved and unreserved type keywords, which don't exist in PG's grammar. Now the only separation is in the type_func_keywords to possibly contain our extensions.

**Review by knz — COMMENTED** [review]
This is very, very good.

> Reviewed 4 of 4 files at r1, 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47216#-:-M4__Oct2ZWyKz_pNLQX:bcbj2ga)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rohany)

___
*[pkg/sql/parser/parse_test.go, line 3287 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47216#-M4__h-40bB3Vf6Qnza4:-M4__h-40bB3Vf6Qnza5:b-up7t4k) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cc9fdbd9d161af7aee6a1a45ca9bd6bb8b1536d/pkg/sql/parser/parse_test.go#L3287)):*
> ```Go
> 		{`SELECT 1::int4.typ`, 0, `qualified types`, ``},
> 		{`SELECT 1::db.schem.typ`, 0, `qualified types`, ``},
> 		{`CREATE TABLE t (x special.type)`, 0, `qualified types`, ``},
> ```

can you add the additional CREATE TABLE tests with composite type names containing keywords here to see which errors are reported.

Also verify:

- `<composite type> ARRAY [ ]`
- `<composite type> ARRAY [ 123 ]`
- `123 IS OF (<composite type>, <composite type>)`

also with mixes of keywords and non-keywords.
___
*[pkg/sql/parser/sql.y, line 8354 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47216#-M4_aFNCAfQdEalmy01v:-M4_aFNCAfQdEalmy01w:b-8793yj) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cc9fdbd9d161af7aee6a1a45ca9bd6bb8b1536d/pkg/sql/parser/sql.y#L8354)):*
> ```Yacc
>   }
> | func_name '(' expr_list opt_sort_clause ')' SCONST { return unimplemented(sqllex, $1.unresolvedName().String() + "(...) SCONST") }
> // The key here is that none of the keywords in the func_name_no_type_reserved
> ```

Would it be possible to pull both this rule and that below (`const_typename SCONST`) into a separate non-terminal called `typed_literal` or something and explain it  as a separate thing. 
This makes it easier visually to connect the two things together.
___
*[pkg/sql/parser/sql.y, line 8357 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47216#-M4_aUaS-YdGRxY7FvAv:-M4_aUaS-YdGRxY7FvAw:bst82d6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cc9fdbd9d161af7aee6a1a45ca9bd6bb8b1536d/pkg/sql/parser/sql.y#L8357)):*
> ```Yacc
> // production can overlap with the type rules in const_typename, otherwise
> // we will have conflicts between this rule and the one below.
> | func_name_no_type_reserved SCONST
> ```

Separate comment: maybe the name `func_name_excluding_const_typenames` would be better? This way it's clearer visually that they don't overlap when quickly glancing through.
___
*[pkg/sql/parser/sql.y, line 9802 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47216#-M4_b9mR99C5xIrbLcFc:-M4_b9mR99C5xIrbLcFd:btm4j0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cc9fdbd9d161af7aee6a1a45ca9bd6bb8b1536d/pkg/sql/parser/sql.y#L9802)):*
> ```Yacc
> 
> // Type/function identifier without CRDB extra reserved keywords.
> type_function_name_no_crdb_extra:
> ```

Keep the naming pattern from `type_func_name_keyword`:

`type_function_name_no_crdb_extra` -> `type_func_name_keyword_no_crdb_extra`

This ensures that both `type_func_name_keyword` AND `type_func_name_keyword_no_crdb_extra` get highlighted in a text editor search when searching for the common prefix.
___
*[pkg/sql/parser/sql.y, line 10158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47216#-M4_arU-6ufeNEFJ3HGC:-M4_arU-6ufeNEFJ3HGD:br0hxai) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cc9fdbd9d161af7aee6a1a45ca9bd6bb8b1536d/pkg/sql/parser/sql.y#L10158)):*
> ```Yacc
> type_func_name_keyword:
>   pg_type_func_name_keyword
> | cockroachdb_extra_type_func_name_keyword
> ```

You already used `_no_crdb_extra` above. I recommend the following renames:

- `pg_type_func_name_keyword` -> `func_name_keyword_no_crdb_extra`
- `cockroachdb_extra_type_func_name_keyword` -> `func_name_keyword_crdb_extra`

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47216)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/sql/parser/parse_test.go, line 3287 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47216#-M4__h-40bB3Vf6Qnza4:-M4_iJKS2Az_ADZtiTVw:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cc9fdbd9d161af7aee6a1a45ca9bd6bb8b1536d/pkg/sql/parser/parse_test.go#L3287)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

can you add the additional CREATE TABLE tests with composite type names containing keywords here to see which errors are reported.

Also verify:

- `<composite type> ARRAY [ ]`
- `<composite type> ARRAY [ 123 ]`
- `123 IS OF (<composite type>, <composite type>)`

also with mixes of keywords and non-keywords.
</blockquote></details>

Done
___
*[pkg/sql/parser/sql.y, line 8354 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47216#-M4_aFNCAfQdEalmy01v:-M4_iKgK7e51x22y85_a:b-l0a9xd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cc9fdbd9d161af7aee6a1a45ca9bd6bb8b1536d/pkg/sql/parser/sql.y#L8354)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Would it be possible to pull both this rule and that below (`const_typename SCONST`) into a separate non-terminal called `typed_literal` or something and explain it  as a separate thing. 
This makes it easier visually to connect the two things together.
</blockquote></details>

Done, that makes thing clearer.
___
*[pkg/sql/parser/sql.y, line 8357 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47216#-M4_aUaS-YdGRxY7FvAv:-M4_jYQbDthT1ZsCDH8G:bcp19xm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cc9fdbd9d161af7aee6a1a45ca9bd6bb8b1536d/pkg/sql/parser/sql.y#L8357)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Separate comment: maybe the name `func_name_excluding_const_typenames` would be better? This way it's clearer visually that they don't overlap when quickly glancing through.
</blockquote></details>

I renamed it -- after I got rid of separate typenames, this should just be named func_name_no_crdb_extra, since that is the only difference now.
___
*[pkg/sql/parser/sql.y, line 9802 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47216#-M4_b9mR99C5xIrbLcFc:-M4_rvPc3-b2KChxjCH3:brkjc3g) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cc9fdbd9d161af7aee6a1a45ca9bd6bb8b1536d/pkg/sql/parser/sql.y#L9802)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Keep the naming pattern from `type_func_name_keyword`:

`type_function_name_no_crdb_extra` -> `type_func_name_keyword_no_crdb_extra`

This ensures that both `type_func_name_keyword` AND `type_func_name_keyword_no_crdb_extra` get highlighted in a text editor search when searching for the common prefix.
</blockquote></details>

I think `type_function_name_no_crdb_extra` follows along with the patterns we have so far -- it mirrors the rule `type_function_name`, so I don't want to change that prefix.
___
*[pkg/sql/parser/sql.y, line 10158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47216#-M4_arU-6ufeNEFJ3HGC:-M4_regn24Ki3Klmm41x:b-mzhch4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cc9fdbd9d161af7aee6a1a45ca9bd6bb8b1536d/pkg/sql/parser/sql.y#L10158)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

You already used `_no_crdb_extra` above. I recommend the following renames:

- `pg_type_func_name_keyword` -> `func_name_keyword_no_crdb_extra`
- `cockroachdb_extra_type_func_name_keyword` -> `func_name_keyword_crdb_extra`
</blockquote></details>

I did something similar. I need to end the production with `keyword` so the keyword generator picks it up, so I can't follow this exactly.

**Review by jordanlewis — APPROVED** [review]
Great simplification! Looks good to me.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47216#-:-M4as7ipDCoHFbj3sCzB:bxqpiyu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rohany)

___
*[pkg/sql/parser/parse_test.go, line 2652 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/47216#-M4arfNK5NwWwOrfmkow:-M4arfNL27O27KHAIgAX:b-5hb1zz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1115e0b2a4fab1ab62efecb66164a6c99b92c0c0/pkg/sql/parser/parse_test.go#L2652)):*
> ```Go
> 		{
> 			`SELECT CAST(1.2+2.3 AS notatype)`,
> 			`at or near ")": syntax error: type does not exist
> ```

Hmm... I'd definitely like to see this error improved somehow. Can it say `type "notatype" does not exist`?
___
*[pkg/sql/parser/sql.y, line 7355 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/47216#-M4asiqr2lpBMJ5UR4jr:-M4asSRl2CO51cEesr1w:b-b4jh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1115e0b2a4fab1ab62efecb66164a6c99b92c0c0/pkg/sql/parser/sql.y#L7355)):*
> ```Yacc
>           case 0:
>             // Note: we can only report an unimplemented error for specific
>             // known type names. Anything else may return PII.
> ```

nit: I'm not sure the phrase "PII" is used much here - how about "sensitive info"?

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47216)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @knz)

___
*[pkg/sql/parser/parse_test.go, line 2652 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/47216#-M4arfNK5NwWwOrfmkow:-M4aycnQDexVfM9qePg3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1115e0b2a4fab1ab62efecb66164a6c99b92c0c0/pkg/sql/parser/parse_test.go#L2652)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Hmm... I'd definitely like to see this error improved somehow. Can it say `type "notatype" does not exist`?
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
:lgtm:   :100: nice

> Reviewed 2 of 7 files at r2, 3 of 5 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47216#-:-M4csDLe2Hl7bAFLtHpN:bn3g695)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by rohany** [comment]
bors r+

TFTR!

**Pull request merged**
