### PR TITLE
storage: reduce commit index on quiescence heartbeat, don't drop them

### PR DESCRIPTION
**Pull request by nvb**
Informs #30064.

53dc851 introduced logic to drop quiescence heartbeats to Replicas that
are not caught up to the leader. This turns out to be an issue in cases
where:
- a Range is quiescent
- a Replica needs a heartbeat to join a Raft group
- that Replica's node is unable to update its liveness record because
doing so depends on the Replica joining the Raft group
- so the Replica never gets any heartbeats and never joins the group

This change adjusts the logic. Instead of dropping these heartbeats, the
leader Replica now sends them, but with a reduced commit index and with
Quiesce equal to false.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
I don't like that this doesn't have a test, but from what I can tell, we don't have any tests around replica quiescence at all and a one-off test for this specific issue is going to be very hard to write. At a minimum, this seems to improve the situation with https://github.com/cockroachdb/cockroach/issues/30064. Any suggestions are welcome.

**Review by bdarnell — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31112)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 4886 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31112#-LOKfKsH8YMqd6mUA_fl:-LOKfKsH8YMqd6mUA_fm:b-ot0klf) ([raw file](https://github.com/cockroachdb/cockroach/blob/be43b2916a600e83c8e2f5a9e3bc68b938b826b1/pkg/storage/replica.go#L4886)):*
> ```Go
> 
> 		if !r.maybeCoalesceHeartbeat(ctx, msg, toReplica, fromReplica, quiesce) {
> 			log.Fatalf(ctx, "failed to coalesce known heartbeat: %v", msg)
> ```

What  does "known" mean here? Why is this now a fatal instead of returning false?

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31112)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 4886 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31112#-LOKfKsH8YMqd6mUA_fl:-LOKolchAYAP9gvQQXK6:b-ez5i14) ([raw file](https://github.com/cockroachdb/cockroach/blob/be43b2916a600e83c8e2f5a9e3bc68b938b826b1/pkg/storage/replica.go#L4886)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

What  does "known" mean here? Why is this now a fatal instead of returning false?
</blockquote></details>

`maybeCoalesceHeartbeat` only returns false if it is given a non-heartbeat request. This is so that it's easy to use in `Replica.sendRaftMessage`. In this case, we know we're giving it a heartbeat request, so it should never return false.

**Review by bdarnell — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31112)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
