### PR TITLE
sql/ui: Create eventlog events for zone config changes

### LINKED ISSUE #23444: ui: changing a zone config doesn't create an event
Not really a UI-issue per-se, but you notice it in the UI. Setting a zone config (either on the command line or via the `EXPERIMENTAL CONFIGURE ZONE` syntax) does not create an event displayed in the `system.event` table. I postulate that it should as changing a zone config is a significant occurrence.

Note that we should also capture implicit zone config deletions that occur due to changing the partitions for a table.

### PR DESCRIPTION
**Pull request by a-robinson**
Fixes #23444

Release note (cli change): Changing or removing a replication zone
config now causes events to be written to the system event log.

-------------------------

The best way to print the names of the modified zones isn't totally clear to me.

1. `config.CLIZoneSpecifier(&n.zoneSpecifier)` (as I've included here) gives statements in the UI Like `Zone Config Changed: User root set the zone config for foo.bar to num_replicas: 7` or `Zone Config Changed: User root set the zone config for demo.users.w to constraints: {"+region=us-west1": 2}`
2. `&n.zoneSpecifier.String()` is a no-go because it doesn't qualify names at all, so you get, e.g. `bar` instead of `foo.bar`
3. `tree.AsStringWithFlags(&n.zoneSpecifier, tree.FmtAlwaysQualifyTableNames)` gives statements like `Zone Config Changed: User root set the zone config for TABLE foo.public.bar to num_replicas: 7` or `Zone Config Changed: User root set the zone config for PARTITION w OF INDEX users@primary to constraints: {"+region=us-west1": 2}`. I don't love the caps-lock or the inclusion of the `public` schema, but this would also be perfectly reasonable.

Option 1 matches the CLI syntax for setting zones. Option 3 matches the SQL syntax. What do you think, @benesch?

### CODE REVIEW

**Comment by benesch** [comment]
Well that was easy! :lgtm: 

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/sql/set_zone_config.go, line 159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25250#-LBXg6B14fN_epnN6GHa:-LBXg6B14fN_epnN6GHb:b-fivsop) ([raw file](https://github.com/cockroachdb/cockroach/blob/85212aba5bfa40d62867009be69e9e7dd6a3a330/pkg/sql/set_zone_config.go#L159)):*
> ```Go
> 	hasNewSubzones := yamlConfig != nil && index != nil
> 	n.run.numAffected, err = writeZoneConfig(params.ctx, params.p.txn,
> 		targetID, table, zone, params.extendedEvalCtx.ExecCfg, hasNewSubzones)
> ```

Are you intentionally not checking for `err != nil` immediately?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25250#-:-LBXgeJd6BatuVxN81OD:b-g3gfps)*

**Comment by mrtracy** [comment]
Looks solid to me. :lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25250#-:-LBXpHa64ZFNJl_oTXcI:b7p29v9)*

**Comment by benesch** [comment]
Oops, missed your question in the PR description. I agree with your choice of option 1. Users aren't even supposed to know about the SQL syntax (yet).

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25250#-:-LBXqj9e17HtZOO8tkUk:b2xxo8c)*

**Comment by a-robinson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/set_zone_config.go, line 159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25250#-LBXg6B14fN_epnN6GHa:-LBZIxx45yiRPtbhSsRS:bljat9o) ([raw file](https://github.com/cockroachdb/cockroach/blob/85212aba5bfa40d62867009be69e9e7dd6a3a330/pkg/sql/set_zone_config.go#L159)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Are you intentionally not checking for `err != nil` immediately?
</blockquote></details>

Not intentional. Changed the code to check immediately.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25250)*

**Comment by a-robinson** [comment]
bors cancel

**Pull request merged**
