### PR TITLE
sql: ensure REGIONAL BY ROW statements roundtrip

### LINKED ISSUE #59362: sql: SHOW CREATE TABLE for multi-region needs to round trip
We have tests that assert zone configs and in some cases crdb_region appear in SHOW CREATE TABLE, but these should disappear.

We should be able to test all these round trip the same.

### PR DESCRIPTION
**Pull request by otan**
Resolves #59362

See individual commits for details.

### CODE REVIEW

**Comment by otan** [comment]
@ajstorm if you could review this one as a priority over the others that'd be great!

**Review by ajstorm — CHANGES_REQUESTED** [review]
For some reason, I lost track of this one.  Feel free to be more aggressive in pinging me if this happens again.  Mostly minor stuff below.

> Reviewed 2 of 2 files at r1, 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60513#-:-MTkJaWQ0YbjNlNSFTQc:b9b98mt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 94 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60513#-MTk1-TW6Qe14RwxcieT:-MTk1-TW6Qe14RwxcieU:br89vly) ([raw file](https://github.com/cockroachdb/cockroach/blob/be21323240d82184b5cb343b86c577eedfbe66b8/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L94)):*
> ```
> ----
> CREATE TABLE public.regional_by_row_table_explicit_crdb_region_column (
>   pk INT8 NULL,
> ```

Nit: It's a bit confusing that you call the first column `pk` but it's not the primary key.  Worth changing?
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60513#-MTk0_yH-IJ0j8hIrMj_:-MTk0_yH-IJ0j8hIrMja:bxkm1bl) ([raw file](https://github.com/cockroachdb/cockroach/blob/be21323240d82184b5cb343b86c577eedfbe66b8/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L96)):*
> ```
>   pk INT8 NULL,
>   a INT8 NULL,
>   crdb_region public.crdb_internal_region NOT NULL,
> ```

I might be missing something, but where did this `NOT NULL` come from?  I don't think we want to be implicitly injecting it here (if that's what we're doing).
___
*[pkg/sql/create_table.go, line 1550 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60513#-MTk56uxDbxObi2XTyeY:-MTk56uxDbxObi2XTyeZ:b3w85qo) ([raw file](https://github.com/cockroachdb/cockroach/blob/be21323240d82184b5cb343b86c577eedfbe66b8/pkg/sql/create_table.go#L1550)):*
> ```Go
> 								err = errors.WithDetailf(
> 									err,
> 									"REGIONAL BY ROW AS must reference a column of type %s.",
> ```

Nit: remove full-stop.
___
*[pkg/sql/create_table.go, line 1554 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60513#-MTk4wjqDl0NlKOfkZHR:-MTk4wjrE7bPiIrq3Q-Z:b-5afinm) ([raw file](https://github.com/cockroachdb/cockroach/blob/be21323240d82184b5cb343b86c577eedfbe66b8/pkg/sql/create_table.go#L1554)):*
> ```Go
> 								)
> 							} else {
> 								err = errors.WithDetailf(
> ```

If I'm following this correctly, isn't this the case where the user hasn't specified a name and we've generated a bad type?  If so, I'd think this should be an assertion.
___
*[pkg/sql/create_table.go, line 1556 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60513#-MTk59VJ9actJeTmOqGo:-MTk59VJ9actJeTmOqGp:b3w85qo) ([raw file](https://github.com/cockroachdb/cockroach/blob/be21323240d82184b5cb343b86c577eedfbe66b8/pkg/sql/create_table.go#L1556)):*
> ```Go
> 								err = errors.WithDetailf(
> 									err,
> 									"Column %s must be of type %s.",
> ```

Nit: remove full-stop.
___
*[pkg/sql/create_table.go, line 1913 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60513#-MTkGDW2AX3gwp6mZx87:-MTkGDW2AX3gwp6mZx88:b36mbcw) ([raw file](https://github.com/cockroachdb/cockroach/blob/be21323240d82184b5cb343b86c577eedfbe66b8/pkg/sql/create_table.go#L1913)):*
> ```Go
> 				return nil, err
> 			}
> 			// This should be forbidden by the syntax, but do a sanity check.
> ```

Nit: Might be good to describe what "this" is, in the comment.
___
*[pkg/sql/sqltestutils/show_create_table.go, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60513#-MTkGfE83yXrRkcmllDX:-MTkGfE83yXrRkcmllDY:b-j94bme) ([raw file](https://github.com/cockroachdb/cockroach/blob/be21323240d82184b5cb343b86c577eedfbe66b8/pkg/sql/sqltestutils/show_create_table.go#L1)):*
> ```Go
> // Copyright 2020 The Cockroach Authors.
> ```

Nit: Happy New Year!
___
*[pkg/sql/sqltestutils/show_create_table.go, line 26 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60513#-MTkH3WlDRv93Lhn5ftv:-MTkH3WlDRv93Lhn5ftw:b-nl6rhp) ([raw file](https://github.com/cockroachdb/cockroach/blob/be21323240d82184b5cb343b86c577eedfbe66b8/pkg/sql/sqltestutils/show_create_table.go#L26)):*
> ```Go
> // ShowCreateTableTestCase is a test case for ShowCreateTableTest.
> type ShowCreateTableTestCase struct {
> 	// Stmt is the table to execute.
> ```

Nit: Is it the table?  Or the create table statement?  
___
*[pkg/sql/sqltestutils/show_create_table.go, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60513#-MTkGo0FEYmRYqy1Z4YJ:-MTkGo0FEYmRYqy1Z4YK:b-x6mce4) ([raw file](https://github.com/cockroachdb/cockroach/blob/be21323240d82184b5cb343b86c577eedfbe66b8/pkg/sql/sqltestutils/show_create_table.go#L27)):*
> ```Go
> type ShowCreateTableTestCase struct {
> 	// Stmt is the table to execute.
> 	Stmt string
> ```

Super Nit: Might want to spell out `Statement` here, as it's the only thing abbreviated.  Or maybe call this Create, as it would match the terminology used below?
___
*[pkg/sql/sqltestutils/show_create_table.go, line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60513#-MTkHEs2E9APokH23vA8:-MTkHEs2E9APokH23vA9:b-icwrjo) ([raw file](https://github.com/cockroachdb/cockroach/blob/be21323240d82184b5cb343b86c577eedfbe66b8/pkg/sql/sqltestutils/show_create_table.go#L37)):*
> ```Go
> // ShowCreateTableTest tests the output for SHOW CREATE TABLE matches
> // the expect values. Furthermore, it round trips SHOW CREATE TABLE
> // statements to ensure it produces an identical SHOW CREATE TABLE.
> ```

Nit: to ensure _they_ produce identical SHOW CREATE TABLEs.
___
*[pkg/sql/sqltestutils/show_create_table.go, line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60513#-MTkI1-i0o390NPZ3vBd:-MTkI1-i0o390NPZ3vBe:b-tovm4j) ([raw file](https://github.com/cockroachdb/cockroach/blob/be21323240d82184b5cb343b86c577eedfbe66b8/pkg/sql/sqltestutils/show_create_table.go#L52)):*
> ```Go
> 		CREATE DATABASE mrdb PRIMARY REGION = "us-west1";
> 		USE d;
> 		CREATE TABLE items (
> ```

Not following why we need this create table.  A comment would help here.
___
*[pkg/sql/sqltestutils/show_create_table.go, line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60513#-MTkIOPX6qFSHeELubhS:-MTkIOPX6qFSHeELubhT:btga1nn) ([raw file](https://github.com/cockroachdb/cockroach/blob/be21323240d82184b5cb343b86c577eedfbe66b8/pkg/sql/sqltestutils/show_create_table.go#L95)):*
> ```Go
> 			}
> 			// Re-insert to make sure it's round-trippable.
> 			name += "_2"
> ```

Instead of "_2", does it make more sense to call this "_round-trip"?
___
*[pkg/sql/sqltestutils/show_create_table.go, line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60513#-MTkJLUD6XNxCnvHoj2w:-MTkJLUD6XNxCnvHoj2x:bthiyr4) ([raw file](https://github.com/cockroachdb/cockroach/blob/be21323240d82184b5cb343b86c577eedfbe66b8/pkg/sql/sqltestutils/show_create_table.go#L112)):*
> ```Go
> 		})
> 	}
> ```

Nit: extra line.

**Review by arulajmani — CHANGES_REQUESTED** [review]
> If PRIMARY KEY is defined as a constraint, it gets CreatePartitioning
> called on twice, which means it may lose it's implicit partitioning.
> This gets fixed in this commit.

I wonder if instead of applying a bandaid here to ensure `CreatePartitioning` is only called once/being careful about things if it is called twice is the way to go. We've seen the need for such tip-toeing come up in a few different contexts now, I wonder if we should take the opportunity to make `CreatePartitioning` more robust to double calls. Is there any scenario in which the current behavior of `CreatePartitioning` is desirable?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60513#-:-MTky_InAFSAwvB8GKC9:b-uvtiv8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/create_table.go, line 1919 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60513#-MTkyJZh4OsV5Ja32Nfe:-MTkyJZi1ReQG-J-Gdtw:b-nd6m8x) ([raw file](https://github.com/cockroachdb/cockroach/blob/be21323240d82184b5cb343b86c577eedfbe66b8/pkg/sql/create_table.go#L1919)):*
> ```Go
> 				)
> 			}
> 			// Leave the partitioning of the primary key to the end.
> ```

nit: Could you add some words around why

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60513)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60513#-MTk0_yH-IJ0j8hIrMj_:-MTm-yW2AyH0jnv09lNp:bgc3wsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/be21323240d82184b5cb343b86c577eedfbe66b8/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L96)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

I might be missing something, but where did this `NOT NULL` come from?  I don't think we want to be implicitly injecting it here (if that's what we're doing).
</blockquote></details>

all PK constraints must be NOT NULL. so we *have* to implicitly inject it.
___
*[pkg/sql/create_table.go, line 1554 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60513#-MTk4wjqDl0NlKOfkZHR:-MTm05guAmz0M8jl839T:b4cqf6p) ([raw file](https://github.com/cockroachdb/cockroach/blob/be21323240d82184b5cb343b86c577eedfbe66b8/pkg/sql/create_table.go#L1554)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

If I'm following this correctly, isn't this the case where the user hasn't specified a name and we've generated a bad type?  If so, I'd think this should be an assertion.
</blockquote></details>

Nah, it's if they do something like

```
CREATE TABLE t (
   crdb_region int
) REGIONAL BY ROW
```

where the crdb_region gets implicitly assumed.
___
*[pkg/sql/sqltestutils/show_create_table.go, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60513#-MTkGo0FEYmRYqy1Z4YJ:-MTmVQIj9l97lXOF8sRJ:b-1vlt6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/be21323240d82184b5cb343b86c577eedfbe66b8/pkg/sql/sqltestutils/show_create_table.go#L27)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Super Nit: Might want to spell out `Statement` here, as it's the only thing abbreviated.  Or maybe call this Create, as it would match the terminology used below?
</blockquote></details>

it's just moved code :') I called it CREATE STATEMENT
___
*[pkg/sql/sqltestutils/show_create_table.go, line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60513#-MTkI1-i0o390NPZ3vBd:-MTmVaDm9p6JbB6Ee2OY:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/be21323240d82184b5cb343b86c577eedfbe66b8/pkg/sql/sqltestutils/show_create_table.go#L52)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Not following why we need this create table.  A comment would help here.
</blockquote></details>

Done
___
*[pkg/sql/sqltestutils/show_create_table.go, line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60513#-MTkIOPX6qFSHeELubhS:-MTmVbOT5Dag4aE2KZtH:bq411sd) ([raw file](https://github.com/cockroachdb/cockroach/blob/be21323240d82184b5cb343b86c577eedfbe66b8/pkg/sql/sqltestutils/show_create_table.go#L95)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Instead of "_2", does it make more sense to call this "_round-trip"?
</blockquote></details>

Hehe, moved code. done.

**Review by ajstorm — APPROVED** [review]
> Reviewed 12 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60513)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60513#-MTk0_yH-IJ0j8hIrMj_:-MTpUq_k-2iM_lYzrHnR:b-2y8vbv) ([raw file](https://github.com/cockroachdb/cockroach/blob/be21323240d82184b5cb343b86c577eedfbe66b8/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L96)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

all PK constraints must be NOT NULL. so we *have* to implicitly inject it.
</blockquote></details>

Interesting.  I would have thought that this would have to be _explicitly_ specified.
___
*[pkg/sql/create_table.go, line 1554 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60513#-MTk4wjqDl0NlKOfkZHR:-MTpVNq4Eqzw8525pLWB:bsk1h5s) ([raw file](https://github.com/cockroachdb/cockroach/blob/be21323240d82184b5cb343b86c577eedfbe66b8/pkg/sql/create_table.go#L1554)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Nah, it's if they do something like

```
CREATE TABLE t (
   crdb_region int
) REGIONAL BY ROW
```

where the crdb_region gets implicitly assumed.
</blockquote></details>

Worth adding a comment here to clarify (for the cases where you're on vaycay and we're trying to understand what this does)?
___
*[pkg/sql/sqltestutils/show_create_table.go, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60513#-MTkGo0FEYmRYqy1Z4YJ:-MTpVbXK7iyGu6saObgo:b-lb0cvq) ([raw file](https://github.com/cockroachdb/cockroach/blob/be21323240d82184b5cb343b86c577eedfbe66b8/pkg/sql/sqltestutils/show_create_table.go#L27)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

it's just moved code :') I called it CREATE STATEMENT
</blockquote></details>

You touch it, you buy it.  Looks much better now!

Nit: "CreateStatement is the statement used to create the table"?

**Comment by otan** [comment]
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60513#-MTk0_yH-IJ0j8hIrMj_:-MTqXuVN3DKTT09lvbtC:b-vadpgm) ([raw file](https://github.com/cockroachdb/cockroach/blob/be21323240d82184b5cb343b86c577eedfbe66b8/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L96)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Interesting.  I would have thought that this would have to be _explicitly_ specified.
</blockquote></details>

oh, this is a SQL behaviour. if you did something like `CREATE TABLE t (a INT PRIMARY KEY)`, the `a` gets implicitly NOT NULL'd as well.

**Comment by otan** [comment]
thanks!

bors r=ajstorm

**Pull request merged**
