### PR TITLE
rac2,kvserverpb: add comments regarding entries not subject to replication AC

### PR DESCRIPTION
**Pull request by sumeerbhola**
Epic: CRDB-37515

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
First commit is from https://github.com/cockroachdb/cockroach/pull/132838

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132846#-:-O9Q30On0T7c6k5a7R8W:bnwcj6z)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

**Comment by sumeerbhola** [comment]
Rebased onto master.

**Review by kvoli — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132846#-:-O9Q7wWN3pLeBVtkknI-:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv)

**Comment by sumeerbhola** [comment]
TFTR!

**Comment by sumeerbhola** [comment]
bors r=kvoli

**Pull request merged**
