### PR TITLE
opt: delete cascade fast path

### PR DESCRIPTION
**Pull request by RaduBerinde**
🚨 If we backport this, we also need to backport the fast-path related fixes in #57100 🚨

#### opt: minor cleanup in optbuilder cascade code

Factoring out a few blocks of duplicated code.

Release note: None

#### opt: delete cascade fast path

Currently, a delete cascade is executed by buffering the input to the
parent deletion and joining that with the child table to find the
child rows to be deleted.

In cases where the DELETE WHERE clause only references FK columns,
instead of buffering the parent rows, we can transfer the filter to
the child table. For example:
```
  CREATE TABLE parent (p INT PRIMARY KEY)
  CREATE TABLE child (p INT REFERENCES parent(p))
  DELETE FROM parent WHERE p=1
```
We can execute the cascade as (effectively):
```
  DELETE FROM child WHERE p=1
```

There are a few subtleties:
 - we must not cascade to rows that have a NULL value on a FK column,
   even if they do satisfy the filter.
 - in special cases, some expressions might evaluate differently for
   corresponding FK values: for example expression `d::string=1.0`
   with the decimal 1.0 in the parent and 1.00 in the child.

The main advantage of this fast path is that it opens up the
possibility of using the much faster delete-range, both in the parent
(because we no longer need the actual rows) and in the child. In
particular, this closes the gap to interleaved tables which allow use
of delete-range across the entire hierarchy.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
CC @yuzefovich - if you have time and want to rerun the tests vs. interleaved with this PR, that would be awesome!

**Review by mgartner — APPROVED** [review]
Cool! :lgtm: 

> Reviewed 2 of 2 files at r1, 20 of 20 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55344#-:-MJ9JJUaBQbIDU916jW7:b-dp13x5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/optbuilder/fk_cascade.go, line 643 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55344#-MJ929EN0qCLLOhlW9ci:-MJ929EO7ZDrv5xHkSOA:boh83ej) ([raw file](https://github.com/cockroachdb/cockroach/blob/9adfd0bfbe931d722a5694e09436360761972bb0/pkg/sql/opt/optbuilder/fk_cascade.go#L643)):*
> ```Go
> 		if r := recover(); r != nil {
> 			if ok, e := errorutil.ShouldCatch(r); ok {
> 				err = e
> ```

Does this work even though the only return statement in `buildCascadeHelper` is `return fn(b), nil`? `err` will still be returned in this case?
___
*[pkg/sql/opt/optbuilder/fk_cascade.go, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55344#-MJ9Bt8hDXsEKRa7ZAiH:-MJ9Bt8hDXsEKRa7ZAiI:b25s8vx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecbfd629e9912e1a8964e15019ad975692900c69/pkg/sql/opt/optbuilder/fk_cascade.go#L111)):*
> ```Go
> // onDeleteCascadeBuilder is a memo.CascadeBuilder implementation for certain
> // cases of ON DELETE CASCADE where we can transfer a filter from the original
> // statement instead of buffering the deleted rows.
> ```

It looks like this also supports cases when there is no filter (the full table scan mentioned at the top of `tryNewOnDeleteFastCascadeBuilder`), correct? If so, maybe mention that case here too?
___
*[pkg/sql/opt/optbuilder/fk_cascade.go, line 196 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55344#-MJ9CWRHCkHt8bRk2CaA:-MJ9CWRHCkHt8bRk2CaB:bhldn0r) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecbfd629e9912e1a8964e15019ad975692900c69/pkg/sql/opt/optbuilder/fk_cascade.go#L196)):*
> ```Go
> 	// Check that the scan is not limited or constrained (this currently shouldn't
> 	// be possible in a normalized expression).
> 	if scan.Constraint != nil || scan.HardLimit != 0 {
> ```

Might be safer to use `!scan.IsUnfiltered(md)` (defined in `memo/expr.go`) because there are now partial index scans and `InvertedConstraints` with can constrained the resulting rows.
___
*[pkg/sql/opt/optbuilder/fk_cascade.go, line 208 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55344#-MJ9Deop4PvW1BU4QT4m:-MJ9Deoq--OkJ9IMb8Uq:b-gdmv52) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecbfd629e9912e1a8964e15019ad975692900c69/pkg/sql/opt/optbuilder/fk_cascade.go#L208)):*
> ```Go
> 	// checkPaths returns false if any tables are reachable from tabID through
> 	// multiple inbound FK paths (or if there are cycles). It uses a recursive
> 	// depth-first search.
> ```

Cycles definitely seem problematic, but why can't we do the fast path when a table is reachable through multiple paths? It seems like it would result in duplicate DelRange operations, which don't seem like an issue (and if they are could we de-duplicate them)?
___
*[pkg/sql/opt/optbuilder/mutation_builder_fk.go, line 516 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55344#-MJ93PNOBCsQKDENad8q:-MJ93PNOBCsQKDENad8r:b-8c11ll) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7312d31357341b4646b176a209df18e1406a0cb/pkg/sql/opt/optbuilder/mutation_builder_fk.go#L516)):*
> ```Go
> 	if err != nil {
> 		if isAdding {
> 			// The other table is in the process of being added; ignore the FK relation.
> ```

[nit] leave this comment to explain why h.otherTab might be `nil` and the early return.
___
*[pkg/sql/opt/optbuilder/mutation_builder_fk.go, line 581 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55344#-MJ93BlJ9qW1NSgjo3ze:-MJ93BlJ9qW1NSgjo3zf:b-6bk6dz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9adfd0bfbe931d722a5694e09436360761972bb0/pkg/sql/opt/optbuilder/mutation_builder_fk.go#L581)):*
> ```Go
> }
> 
> // resolveTable resolves a table StableID. Returns nil if the other table is in
> ```

[nit] Here and below: there is no "other" table in the context of this function.

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55344#-:-MJCodYS0mAclWLsXxl7:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/optbuilder/fk_cascade.go, line 643 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55344#-MJ929EN0qCLLOhlW9ci:-MJCo1hR4ihKWBwqQ6F4:b-y2zhqw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9adfd0bfbe931d722a5694e09436360761972bb0/pkg/sql/opt/optbuilder/fk_cascade.go#L643)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Does this work even though the only return statement in `buildCascadeHelper` is `return fn(b), nil`? `err` will still be returned in this case?
</blockquote></details>

Yeah, its the standard way of modifying a return value from a defer. When this code runs, `err` is set to whatever value was returned and can be modified.
___
*[pkg/sql/opt/optbuilder/fk_cascade.go, line 208 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55344#-MJ9Deop4PvW1BU4QT4m:-MJCnLD82zn-USEo8wI9:b-t8n6eu) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecbfd629e9912e1a8964e15019ad975692900c69/pkg/sql/opt/optbuilder/fk_cascade.go#L208)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Cycles definitely seem problematic, but why can't we do the fast path when a table is reachable through multiple paths? It seems like it would result in duplicate DelRange operations, which don't seem like an issue (and if they are could we de-duplicate them)?
</blockquote></details>

We could, I didn't want to bother with these impractical cases (even if the code is easy, it's a pain to test). I added a TODO.
___
*[pkg/sql/opt/optbuilder/mutation_builder_fk.go, line 516 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55344#-MJ93PNOBCsQKDENad8q:-MJCoYTC6NLeLnp2KBVB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7312d31357341b4646b176a209df18e1406a0cb/pkg/sql/opt/optbuilder/mutation_builder_fk.go#L516)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] leave this comment to explain why h.otherTab might be `nil` and the early return.
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/mutation_builder_fk.go, line 581 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55344#-MJ93BlJ9qW1NSgjo3ze:-MJCo_hVDfIE49NS4Lff:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/9adfd0bfbe931d722a5694e09436360761972bb0/pkg/sql/opt/optbuilder/mutation_builder_fk.go#L581)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] Here and below: there is no "other" table in the context of this function.
</blockquote></details>

Fixed.

**Review by mgartner — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55344)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

___
*[pkg/sql/opt/memo/expr.go, line 640 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/55344#-MJCwx3M-tfnalmivCZX:-MJCwx3M-tfnalmivCZY:bdkgtm2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec480cf6c3f133e3d3f421a362ee0ce3ebeae7cd/pkg/sql/opt/memo/expr.go#L640)):*
> ```Go
> 	if s.Index == cat.PrimaryIndex {
> 		// Primary index is always non-partial; skip making the catalog calls.
> 		return false
> ```

Nice find!
___
*[pkg/sql/opt/optbuilder/fk_cascade.go, line 643 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55344#-MJ929EN0qCLLOhlW9ci:-MJCxUPKEJa_2_fTED_J:b3jswk1) ([raw file](https://github.com/cockroachdb/cockroach/blob/9adfd0bfbe931d722a5694e09436360761972bb0/pkg/sql/opt/optbuilder/fk_cascade.go#L643)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yeah, its the standard way of modifying a return value from a defer. When this code runs, `err` is set to whatever value was returned and can be modified.
</blockquote></details>

Ahh, good to know.
___
*[pkg/sql/opt/optbuilder/fk_cascade.go, line 208 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55344#-MJ9Deop4PvW1BU4QT4m:-MJCx1cG3-TWsBJtUJHT:bb73djm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecbfd629e9912e1a8964e15019ad975692900c69/pkg/sql/opt/optbuilder/fk_cascade.go#L208)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We could, I didn't want to bother with these impractical cases (even if the code is easy, it's a pain to test). I added a TODO.
</blockquote></details>

SGTM

**Comment by yuzefovich** [comment]
I ran a quick test against the fast-path interleaved case, and the results are great (old is interleaved, new is cascade fast path):
```
name                     old ops/s  new ops/s  delta
point-delete-throughput  5.58 ± 7%  5.82 ± 5%  +4.34%  (p=0.009 n=10+9)

name                     old ms/s   new ms/s   delta
point-delete-P50          243 ±10%   227 ± 8%  -6.51%  (p=0.029 n=10+9)
point-delete-Avg          180 ± 7%   174 ± 6%    ~     (p=0.059 n=10+10)
```
```
name                       old ops/s   new ops/s   delta
delete-comcast-throughput   0.60 ± 0%   0.60 ± 0%   ~     (all equal)

name                       old ms/s    new ms/s    delta
delete-comcast-P50         1.93k ±10%  2.01k ±27%   ~     (p=0.688 n=9+9)
delete-comcast-Avg         1.64k ±15%  1.68k ±16%   ~     (p=0.576 n=9+10)
```

**Review by rytaft — APPROVED** [review]
:lgtm:  Nice work!

> Reviewed 2 of 2 files at r1, 16 of 20 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55344#-:-MJDjI_N9iF_28_4_WXe:bo31fz2)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/mutation_builder_fk.go, line 486 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/55344#-MJDhZNk1Kb_my02n640:-MJDhZNk1Kb_my02n641:b-wby4el) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec480cf6c3f133e3d3f421a362ee0ce3ebeae7cd/pkg/sql/opt/optbuilder/mutation_builder_fk.go#L486)):*
> ```Go
> }
> 
> // initWithID ensures that withID is initialized (and thus that the input to the
> ```

[nit] would `ensureWithID` be a better name? (I don't feel too strongly, so feel free to ignore)

**Comment by RaduBerinde** [comment]
Thanks @yuzefovich, that's great. After this has been merged on master for a while, we can consider backporting to 20.2.x so we can advise against interleaved tables for all new deployments.

**Review by RaduBerinde — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55344#-:-MJSiW1q0R_iKhK75Ryf:b-tm3sxm)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/optbuilder/mutation_builder_fk.go, line 486 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/55344#-MJDhZNk1Kb_my02n640:-MJSiVTo0IVtuj58swpU:bexegmu) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec480cf6c3f133e3d3f421a362ee0ce3ebeae7cd/pkg/sql/opt/optbuilder/mutation_builder_fk.go#L486)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] would `ensureWithID` be a better name? (I don't feel too strongly, so feel free to ignore)
</blockquote></details>

Done, TFTR!

**Comment by RaduBerinde** [comment]
🚨 If we backport this, we also need to backport the fast-path related fixes in #57100 🚨

**Pull request merged**
