### PR TITLE
cli: add "skip" option to IMPORT CSV DATA

### PR DESCRIPTION
**Pull request by bobvawter**
Open question:  Where do I update the documentation to show the new skip option?

This change allows the user to skip the first N-many lines of a CSV file when
importing data.  This allows, for example, files with column headers to be
imported directly.

Resolves: #19967

Release note: (cli change): add "skip" option to IMPORT CSV DATA

### CODE REVIEW

**Comment by benesch** [comment]
Woo, nice! I'll leave the review to @mjibson. Documentation lives in a separate repository: github.com/cockroachdb/docs. Updating it is an unfortunately manual process.

The page you want is probably https://github.com/cockroachdb/docs/blob/master/v2.0/import.md, except that's for v2.0. We haven't yet cut a version of the docs for 2.1.

**Comment by mjibson** [comment]
This looks great.

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ccl/importccl/csv.go, line 524 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23466#-L6wiw9Vbbfen4NjcsXI:-L6wiw9WtwdItDNGp1_5:b-8lhrsq) ([raw file](https://github.com/cockroachdb/cockroach/blob/613761a38c17681305419642a58cb21b913b9849/pkg/ccl/importccl/csv.go#L524)):*
> ```Go
> 					return errors.Wrapf(err, "row %d: reading CSV record", i)
> 				}
> 				// Ignore the first N lines
> ```

`.` at EOL. See https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23466#-:-L6wjnQLnv8lPSxwbg51:b-j45s0m)*

**Comment by mjibson** [comment]
@arjunravinarayan this PR changes a proto used in distsql. Do we need to bump a version somewhere? I'm not exactly sure when that needs to happen.

**Comment by arjunravinarayan** [comment]
@mjibson  I don't know how the thing that consumes a `CSVOptions` will behave w.r.t. the newly introduced field (Who reads a `CSVOptions`? The CSV processor?). The thing you have to think about is what happens when someone sends out CSVs with the field set in a mixed version cluster - will consumers of this Proto who have a different version do the right thing (my guess based on looking at the field name is that a job started on an old version can safely run on a new node, but not the other way round? but that's for you to decide based on the semantics). 

If you conclude that this would work badly in a mixed version cluster in either direction, then you need some way to not let the query run on mixes of old and new nodes. The DistSQL versioning system will do that for you, and you can bump the DistSQL version, although in the longer run you might want to maintain your own versioning system in IMPORT-land that doesn't wipe all query processing capabilities during a rolling upgrade, but I believe I've derailed this conversation sufficiently.

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23466#-:-L6wlGRT_K_p9hLnNr8F:b-ihig4s)*

**Comment by bobvawter** [comment]
This would only behave badly if you wanted to skip rows and the node that interprets the import statement is newer than the one that executes CSV file-read operation.

https://github.com/cockroachdb/docs/blob/master/v2.0/import.md#functional-overview

There's no problem with interop if you don't want to skip nodes, the default value of the new proto field would result in the desired no-op case.

@mjibson What's the right path forward here?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23466#-:-L6wrQ5iiB9gcsYwRX_x:b-32ytvp)*

**Comment by dianasaur323** [comment]
cc @Amruta-Ranade for help on docs if necessary

**Comment by danhhz** [comment]
@bobvawter correct. if you had a mixed version cluster and used this feature, any old nodes would incorrectly ignore this field and would try to interpret a header row as data. the cluster version mechanism mentioned lets you prevent this by allowing you to return an error if the user tries to use this feature before the cluster has finished the upgrade

**Comment by arjunravinarayan** [comment]
@bobvawter in that case the right path is to increment the DistSQL version in `distsqlrun/server.go` and copy over the explanation you posted above in `distsqlrun/version_history.txt`. @danhhz it doesn't return an error, it just plans the query on the subset of nodes with the correct version, so you get reduced concurrency while the upgrade is in process.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23466#-:-L6wtJWZkL3ou5jcg_Uv:b3ail9r)*

**Comment by danhhz** [comment]
> @danhhz it doesn't return an error, it just plans the query on the subset of nodes with the correct version, so you get reduced concurrency while the upgrade is in process.

ack. til!

**Comment by mjibson** [comment]
Import does its own planning, and it doesn't care about node versions. It uses all nodes in the cluster, and so I think will indeed end up doing the ignore thing.

**Comment by bobvawter** [comment]
PTAL.  I have added a new cluster version entry based on discussion with @dt in the #backup slack channel.

---

Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/ccl/importccl/csv.go, line 524 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23466#-L6wiw9Vbbfen4NjcsXI:-L7-fkzRUFrE_UOICauU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/613761a38c17681305419642a58cb21b913b9849/pkg/ccl/importccl/csv.go#L524)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

`.` at EOL. See https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23466#-:-L7-fKp_GwMtNvVbVaPO:bf35vng)*

**Comment by bobvawter** [comment]
Argh.  Looks like tweaking the versions breaks a number of tests that are looking for "2.0".  I'm going to split this change into two commits, the first one to introduce the new version tag and fix the tests, then the actual import changes.

**Comment by bdarnell** [comment]
Cluster versions should be introduced in the same commit that starts to use them (which currently means that each such commit must touch a handful of random test files that assert the expected value of the cluster version). Otherwise, there would be a (remote) chance that someone could start a node with exactly that commit and it would claim to have the new feature but would not actually be safe to mix with a newer node.

**Comment by bobvawter** [comment]
Per @bdarnell, leaving this as a single commit.  The tests are now passing.

**Comment by mjibson** [comment]
What happens if the 2.0 branch needs to bump its cluster version for some reason? Won't that collide with the 2.0-1 used here? Do we need to bump to 2.1-1 or something?

Does it really make sense to bump this every time we change the protos of import, backup, or restore? That is, does it make more sense to change it once before release and do a version check there instead? Or can we do something like guarantee that things will only be scheduled on nodes with a version => the coordinator? This whole problem is hard.

**Comment by bdarnell** [comment]
We shouldn't introduce new cluster versions in the 2.0 branch because the general contract is that you can upgrade and downgrade freely within patch releases of the same X.Y branch (I don't know what we'd do if we have a serious bug in 2.0 that can't be fixed without a new cluster version). We don't bump to 2.1-1 because that would be greater than 2.1, which hasn't happened yet.

**Comment by mjibson** [comment]
Does it make sense to bake in some space in case of that? We could start a 2.0-10 or something. I'm fine with 2.0-1, just wanted to think this through. Your call, clearly, just trying to make sure we're ok.

**Comment by bdarnell** [comment]
Leaving a gap is not a bad idea since we're starting a new release series here, but I'm not sure how much it actually helps. If we have to actually use the gap then ordering becomes poorly defined, since 2.0-1 could be introduced chronologically after 2.0-11.

**Comment by bobvawter** [comment]
There is a currently-unused `Patch` field in the cluster-version proto.  Perhaps if the 2.0 branch really, really needed to introduce a new cluster version, it could use 2.0.1 or something and we could fix up the 2.1 branch to DTRT if that case ever arises.  It would be weird that 2.0.1 is before? sibling to? 2.0-X, but there is some maneuvering room in the existing data structures.

**Comment by bdarnell** [comment]
Right, I forgot about the Patch field. That was our escape hatch for this situation, so no reason to start with a gap in the last component of the cluster version.

**Comment by bobvawter** [comment]
I've seen some other software project (e.g. Kotlin) use multiples of 10 for their least-significant version parts, so there's always a gap if you need to insert an emergency fix, just like BASIC.

**Comment by bobvawter** [comment]
Is there any further discussion we need to have about the cluster version, or shall I merge this?

**Comment by mjibson** [comment]
This LGTM assuming Ben ok's the version stuff.

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23466#-:-L76ULgFbV6sQsS8giqY:bnfp4nl)*

**Pull request merged**
