### PR TITLE
settings/cluster: Add a version to denote work on v19.2.

### PR DESCRIPTION
**Pull request by BramGruneir**
Release note: None

### CODE REVIEW

**Comment by BramGruneir** [comment]
I could also bump BinaryMinimumSupportedVersion but it didn't seem required yet.  Let me know.

**Review by bdarnell — APPROVED** [review]
I think we should go ahead and bump BinaryMinimumSupportedVersion to 19.1 now; otherwise we'll forget to do it when real incompatible changes are introduced. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37000#-:-Ld5apIS0UpmEzX3qKbM:b-5tvbql)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell)

**Comment by BramGruneir** [comment]
Done, TFTR

bors r+

**Comment by BramGruneir** [comment]
trying again, bors r+

**Comment by BramGruneir** [comment]
bors r+

I worry that roachtest is going to fail again.

**Comment by BramGruneir** [comment]
I had to shrink the name in the upgrade test for `no-predecessor-found` to `no-pred` so that the roachtest will pass.  The cluster name was too large.

bors r+

**Review by andreimatei — COMMENTED** [review]
Hold up, don't we want negative unstable versions?
Cause if we don't, is `SET CLUSTER SETTING version = 19.2` gonna do the right thing? What version will that update to?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37000#-:-Ld5zEAdCg5FkaNjz4rT:b-3q1q1x)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by bdarnell** [comment]
`SET CLUSTER SETTING version=19.2` won't work until the 19.2 cluster version is defined. During the development cycle, you'll set the setting to `19.1-1`, etc. Negative unstable versions are nice in principle, but they don't work yet.

**Comment by andreimatei** [comment]
Oh I missed that what's being introduced here is a 19.1 version, and not a 19.2 version. But then won't we run into trouble if we need more 19.1 versions, that still need to come below the one introduced here?

**Comment by bdarnell** [comment]
They won't come below this version, they'll come above it. Unstable cluster versions start with the previous stable release and count up (starting with 19.1-1 here); the upcoming version number doesn't appear in the sequence until the end.

We also have the version tags which are used for buildinfo, and those start with the next version's number and an alpha suffix (v19.2-alpha.00000000). These are used in buildinfo. Yes, it's confusing, but those are the systems we have right now.

**Comment by BramGruneir** [comment]
bors r-

Going to merge a PR that includes the tag in a PR that includes the tag from a branch on cockraoch instead of my fork.  

DO NOT MERGE THIS ONE.

**Comment by BramGruneir** [comment]
But I do want to leave this open to see the CI result.

**Pull request closed without merging**
