### PR TITLE
admission: smooth compaction token calculation

### LINKED ISSUE #91519: admission:  ioLoadListener compaction token calculation is too abrupt
`ioLoadListener` calculates multiple types of tokens, one of which is based on compaction bandwidth out of L0. Compaction bandwidth capacity out of L0 is hard to predict.
- Pebble may not be using all the compaction concurrency available. And if Pebble were to use all the compaction concurrency (which itself may be variable in the future), it is hard to know how much more will be given to L0, since there is sophisticated scoring happening in the level compaction decision making. Note, this is unlike flushes where we do have a dedicated concurrency of 1 and do make predictions based on idle time.
- Related to the scoring, the allocation of compaction capacity to L0 can vary.

For these reasons we have used a measurement based approach with exponential smoothing, where the measurements are taken *only* when we know there is some backlog, so all compactions ought to be running. At a high level I think we can continue with this approach. The problem is that we have abrupt behavior:
above an unhealthy threshold (actually a predicate defined by a disjunction sublevel-count > L or file-count > F), we use compaction bandwidth (C), to allocate C/2 tokens. Below the unhealthy threshold, the token count is infinity.

This results in bursty admission behavior where we go over the threshold, restrict tokens for a few intervals (each interval is 15s long), and then go below the threshold and have unlimited tokens and admit everything, which again puts us above the threshold. It is typical to see something like 2-3 intervals about the threshold anfd then 1 interval below. This is bad but the badness is somewhat restricted because (a) the admitted requests have to evaluate which steals time away from the admitting logic, (b) our typical workloads don't have huge concurrency so the waiting requests are limited by this concurrency.
With replication admission control we will make this worse by doing logical admission of all the waiting requests when we switch from above the threshold to below, causing another big fan-in burst (https://docs.google.com/document/d/1iCfSlTO0P6nvoGC6sLGB5YqMOcO047CMpREgG_NSLCw/edit#heading=h.sw7pci2vwkk3).

Instead we should switch to a piece-wise linear function for defining the tokens. Let us define a sub-level count threshold L and a file-count threshold F that we would like to be roughly stable at under overload. Say L=10 and F=500. These are half the current defaults of 20 and 1000 since (a) the current thresholds are higher than what we would like to sustain at, (b) we will keep the current C/2 logic at 2L and 2F. Regardless, L and F are configurable.

Then we define a score = max(sublevel-count/L, file-count/F). The compaction token function is:
- score < 1 : unlimited
- score in [1, 2): tokens = -C/2 x score + 3C/2
  This means C tokens when score=1, and will linearly decrease to C/2 tokens when the score is 2.
- score >= 2: tokens = C/2

Jira issue: CRDB-21299

Epic CRDB-25469

### PR DESCRIPTION
**Pull request by bananabrick**
We change the way we compute the score for compaction token
calculation, and use that score to smoothen the calculation.

The score is calculated as max(sublevels/20, l0files/1000).

Prior to this commit, we were overloaded if score was above 1 and
underloaded if score was below 1. This meant that it was easy to
have an underloaded system with unlimited tokens, and then become
overloaded due to the unlimited tokens. Note that our score calculations
also use the admission control overload threshold of 20, and 1000.

In this pr, we the keep the previous definition of score, but we're only
overloaded if score >= 1. We can consider score < 0.5 as underload, and score
in [0.5, 1) as medium load.

During underload, we still give out unlimited tokens, and during
overload we still give out C = smoothedIntL0CompactedBytes / 2 tokens.

But during medium load we hand out (C/2, C]  tokens. This scheme will
ideally remove the sharp spikes in the granted tokens due to switching
back and forth between overloaded and underloaded systems.

Epic: https://cockroachlabs.atlassian.net/browse/CRDB-25469
Fixes: https://github.com/cockroachdb/cockroach/issues/91519
Release note: None

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
Can you include some graphs from your experimental results in the PR description (and the experiment setup).

:lgtm: 

> Reviewed 5 of 5 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104577#-:-NY4hu9P-YYxq-Az79TI:bdssi7v)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bananabrick)

___
*[`pkg/util/admission/grant_coordinator.go` line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104577#-NY4eXHc2mV_WhRQTrG3:-NY4eXHc2mV_WhRQTrG4:bzfjtp8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e56047491c6c4b19a58b18efb99a343e47e735b/pkg/util/admission/grant_coordinator.go#L54)):*
> ```Go
> 	settings                             *cluster.Settings
> 	makeStoreRequesterFunc               makeStoreRequesterFunc
> 	kvIOTokensExhaustedDuration          *metric.Counter
> ```

we should add a TODO to make all these metrics per store
___
*[`pkg/util/admission/granter.go` line 312 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104577#-NY4f2-900s2NhzxFFMB:-NY4f2-900s2NhzxFFMC:b651q4t) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e56047491c6c4b19a58b18efb99a343e47e735b/pkg/util/admission/granter.go#L312)):*
> ```Go
> 	ioTokensExhaustedDurationMetric *metric.Counter
> 	availableTokensMetrics          *metric.Gauge
> 	tookWithoutPermissionMetric     *metric.Counter
> ```

the total tokens given out (with or without permission) may also be helpful if we are trying to compare whether the without permission rate is significant.
___
*[`pkg/util/admission/granter.go` line 394 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104577#-NY4fXfv-BDrViTPU-WD:-NY4fXfv-BDrViTPU-WE:b-k3o0ej) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e56047491c6c4b19a58b18efb99a343e47e735b/pkg/util/admission/granter.go#L394)):*
> ```Go
> 		if sg.coordMu.availableIOTokens > 0 {
> 			sg.subtractTokensLocked(count, false)
> 			sg.availableTokensMetrics.Update(sg.coordMu.availableIOTokens)
> ```

We should update the metric where we update `availableIOTokens`, i.e., in `subtractTokensLocked` and in `setAvailableTokens`. Otherwise it is easy to forget some caller.
___
*[`pkg/util/admission/io_load_listener.go` line 826 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104577#-NY4gux77WrDttbEVybO:-NY4gux77WrDttbEVybP:b-w3kl3a) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac62629e89d5a836a15e970cb2a8d500fcb9f2d9/pkg/util/admission/io_load_listener.go#L826)):*
> ```Go
> 	// and less smoothed behaviour than multiplying the score by 2, and checking
> 	// if the score is < 1, or >= 2, and performing linear interpolation for the
> 	// range [1, 2).
> ```

I don't quite believe this. There must be a bug if that was the behavior that occurred. I don't mind this current code since it the interval [1, 2) is easy to reason about in the equations below. So maybe just say that.
___
*[`pkg/util/admission/io_load_listener.go` line 847 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104577#-NY4gX_f9dTamRHB5EWd:-NY4gX_f9dTamRHB5EWe:b-8hhe8o) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac62629e89d5a836a15e970cb2a8d500fcb9f2d9/pkg/util/admission/io_load_listener.go#L847)):*
> ```Go
> 			// since we want to get under the thresholds over time. This
> 			// scaling could be adjusted based on how much above the threshold we are,
> 			// but for now we just use a constant.
> ```

the last sentence "... could be adjusted ..." is what this PR is doing, so we should drop the sentence.

**Review by irfansharif — APPROVED** [review]
Could you backport the additional metrics to 22.2 and 23.1? They’re very valuable. +1 to adding a metric for L0 tokens produced and including in backport (feel free to do that separately too, or take advantage of the LGTM here). 

> Reviewed 3 of 5 files at r2, 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104577#-:-NY54Qui5KEzpsfYPYqB:b-qbx0xv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bananabrick and @sumeerbhola)

___
*[`-- commits` line 24 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104577#-NY59c7w-AKe2RhWhe-H):*
s/pr/commit. Nit: "we the keep the previous definition of score, but we're only overloaded if score >= 1" makes it seem that previously we had a different definition of overload, but we didn't. We're instead introducing medium load, and re-defining underload.
___
*[`-- commits` line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104577#-NY5F2L4BPXqVmuK31Cs):*
This could be more specific in mentioning the exact piecewise linear function we're using, or that it's a linear interpolation from X to Y.
___
*[`pkg/util/admission/grant_coordinator.go` line 991 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104577#-NY4nUVODSXEYsf90lJr:-NY4nUVODSXEYsf90lJs:b-ohba94) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e56047491c6c4b19a58b18efb99a343e47e735b/pkg/util/admission/grant_coordinator.go#L991)):*
> ```Go
> 	KVSlotAdjusterDecrements             *metric.Counter
> 	KVIOTokensExhaustedDuration          *metric.Counter
> 	KVIONumIOTokensTookWithoutPermission *metric.Counter
> ```

[Minor nit]: "Num" is unnecessary, here and elsewhere.
___
*[`pkg/util/admission/granter.go` line 394 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104577#-NY4fXfv-BDrViTPU-WD:-NY4mbFjBgHUFPNtYMaN:b-obvlln) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e56047491c6c4b19a58b18efb99a343e47e735b/pkg/util/admission/granter.go#L394)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We should update the metric where we update `availableIOTokens`, i.e., in `subtractTokensLocked` and in `setAvailableTokens`. Otherwise it is easy to forget some caller.
</blockquote></details>

+1. There's one other callsite below where we invoke `subtractTokensLocked` where we're not updating this metric (was that intentional? if so, why?)
___
*[`pkg/util/admission/io_load_listener.go` line 541 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104577#-NY55Hc00aCTapxk-sDi:-NY55Hc00aCTapxk-sDj:b-u0o1if) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac62629e89d5a836a15e970cb2a8d500fcb9f2d9/pkg/util/admission/io_load_listener.go#L541)):*
> ```Go
> 	l0WriteLM, l0IngestLM, ingestLM := io.perWorkTokenEstimator.getModelsAtDone()
> 	io.kvGranter.setLinearModels(l0WriteLM, l0IngestLM, ingestLM)
> 	if score, _ := io.ioThreshold.Score(); score >= 0.5 || io.aux.doLogFlush ||
> ```

This logging is very useful. Could you also add a log.V(1) condition so we can enable it selectively even on unloaded clusters through vmodule?
___
*[`pkg/util/admission/io_load_listener.go` line 829 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104577#-NY5BtUC5__5plw33I25:-NY5BtUD1ltgYBeakKYa:ba0c5ao) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac62629e89d5a836a15e970cb2a8d500fcb9f2d9/pkg/util/admission/io_load_listener.go#L829)):*
> ```Go
> 	score *= 2
> 	if score < 1 {
> 		// Under the threshold. Maintain a smoothedCompactionByteTOkens based on
> ```

Accidental capitalization of "O" in smoothedCompactionByteTOkens.
___
*[`pkg/util/admission/io_load_listener.go` line 836 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104577#-NY5Cfx78gmtsJSvJE6f:-NY5Cfx78gmtsJSvJE6g:bra57xh) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac62629e89d5a836a15e970cb2a8d500fcb9f2d9/pkg/util/admission/io_load_listener.go#L836)):*
> ```Go
> 		numTokens := intL0CompactedBytes
> 		// Smooth it. This may seem peculiar since we are already using
> 		// smoothedIntL0CompactedBytes, but the clauses below uses different
> ```

Nit: "clauses below _use_ different"
___
*[`pkg/util/admission/io_load_listener.go` line 850 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104577#-NY5AYxr40X1oF965m7g:-NY5AYxr40X1oF965m7h:bm2ojxr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac62629e89d5a836a15e970cb2a8d500fcb9f2d9/pkg/util/admission/io_load_listener.go#L850)):*
> ```Go
> 			fTotalNumByteTokens = float64(smoothedIntL0CompactedBytes / 2.0)
> 		} else {
> 			// score in [1, 2).
> ```

This could use a comment block explaining why we're using the piece-wise linear function. You could also annotate this else block with the "medium load" naming convention you used in the commit message. Ditto above for "underload" and "overload".
___
*[`pkg/util/admission/testdata/format_adjust_tokens_stats.txt` line 4 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104577#-NY55pT256pw4oUdgO_Z:-NY55pT256pw4oUdgO__:b3o9im4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac62629e89d5a836a15e970cb2a8d500fcb9f2d9/pkg/util/admission/testdata/format_adjust_tokens_stats.txt#L4)):*
> ```help
> ----
> zero:
> compaction score 0.000 (0 ssts, 0 sub-levels), L0 growth 0 B (write 0 B ingest 0 B ignored 0 B): requests 0 (0 bypassed) with 0 B acc-write (0 B bypassed) + 0 B acc-ingest (0 B bypassed) + write-model 0.00x+0 B (smoothed 0.00x+0 B) + ingested-model 0.00x+0 B (smoothed 0.00x+0 B) + at-admission-tokens 0 B, compacted 0 B [≈0 B], flushed 0 B [≈0 B]; admitting all; elastic tokens 0 B (used 0 B, regular used 0 B): write model 0.00x+0 B ingest model 0.00x+0 B, disk bw read 0 B write 0 B provisioned 0 B; write stalls 12
> ```

Why is this non-zero for the zero state this test wants to print?
___
*[`pkg/util/admission/testdata/io_load_listener` line 575 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104577#-NY5E5uN0qBR-1Kr2z_1:-NY5E5uN0qBR-1Kr2z_2:b-4sayr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac62629e89d5a836a15e970cb2a8d500fcb9f2d9/pkg/util/admission/testdata/io_load_listener#L575)):*
> ```
> setAvailableTokens: io-tokens=unlimited elastic-disk-bw-tokens=1 max-byte-tokens=unlimited max-disk-bw-tokens=105
> 
> # Test scoring and interpolation for compaction token smoothing.
> ```

This is not for this PR, but I continue to find tests in this file difficult to read. There's so much state, the lines are very long (so not very friendly reading it in IDEs, with or without text wrapping), and every `set-state` directive sets all state so it's hard to visually point out exactly which one was changed line by line. Do you have any ideas on for how we could improve it? I just glanced at these diffs.

**Comment by bananabrick** [comment]
Adding some graphs showing the smoothing behaviour(left is with smoothing, right is master):

Screenshot 2023-06-16 at 6 28 26 PM
Screenshot 2023-06-16 at 6 29 14 PM
Screenshot 2023-06-16 at 6 29 04 PM
Screenshot 2023-06-16 at 6 28 55 PM
Screenshot 2023-06-16 at 6 28 50 PM
Screenshot 2023-06-16 at 6 28 35 PM
Screenshot 2023-06-16 at 6 28 30 PM

We can see smoothing even in the CPU utilization as we avoid bursts which were common in the previous scheme.

The tokens taken without permission/exhaustion durations are slightly higher in this pr. This shouldn't be a concern in the single node version of this experiment/with flow control enabled. I'll probably run the single node experiment before I merge this.

The ops vs sec is slightly lower with smoothing, around 6900 ops/sec vs 7200 ops/sec on master. I think this is expected as we're throttling compaction tokens starting from a sublevel count of 10 rather than 20.

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104577)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif and @sumeerbhola)

___
*[`-- commits` line 24 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104577#-NY59c7w-AKe2RhWhe-H):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

s/pr/commit. Nit: "we the keep the previous definition of score, but we're only overloaded if score >= 1" makes it seem that previously we had a different definition of overload, but we didn't. We're instead introducing medium load, and re-defining underload.
</blockquote></details>

Done.
___
*[`-- commits` line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104577#-NY5F2L4BPXqVmuK31Cs):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

This could be more specific in mentioning the exact piecewise linear function we're using, or that it's a linear interpolation from X to Y.
</blockquote></details>

Done.
___
*[`pkg/util/admission/grant_coordinator.go` line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104577#-NY4eXHc2mV_WhRQTrG3:-NY5NhJl4XGLrQCMWPxf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e56047491c6c4b19a58b18efb99a343e47e735b/pkg/util/admission/grant_coordinator.go#L54)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

we should add a TODO to make all these metrics per store
</blockquote></details>

Done.
___
*[`pkg/util/admission/grant_coordinator.go` line 991 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104577#-NY4nUVODSXEYsf90lJr:-NY5Ni3bAmjWl8YY274q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e56047491c6c4b19a58b18efb99a343e47e735b/pkg/util/admission/grant_coordinator.go#L991)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

[Minor nit]: "Num" is unnecessary, here and elsewhere.
</blockquote></details>

Done.
___
*[`pkg/util/admission/granter.go` line 312 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104577#-NY4f2-900s2NhzxFFMB:-NY5OUsIBoFfmhwoG82h:b-bffgf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e56047491c6c4b19a58b18efb99a343e47e735b/pkg/util/admission/granter.go#L312)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

the total tokens given out (with or without permission) may also be helpful if we are trying to compare whether the without permission rate is significant.
</blockquote></details>

Will add in the next pr.
___
*[`pkg/util/admission/granter.go` line 394 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104577#-NY4fXfv-BDrViTPU-WD:-NY5OoR34esp6rd4EgMh:bhk59xh) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e56047491c6c4b19a58b18efb99a343e47e735b/pkg/util/admission/granter.go#L394)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

+1. There's one other callsite below where we invoke `subtractTokensLocked` where we're not updating this metric (was that intentional? if so, why?)
</blockquote></details>

Oversight.

But I didn't put this in `subtractTokensLocked` on purpose. In `setAvailableTokens` we call subtractTokensLocked, and then we might further restrict the available tokens, and I didn't want this to be updated twice.

But I guess updating twice is fine, so I moved this in.
___
*[`pkg/util/admission/io_load_listener.go` line 541 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104577#-NY55Hc00aCTapxk-sDi:-NY5PnRxAaohr13AxrFB:b-hswygw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac62629e89d5a836a15e970cb2a8d500fcb9f2d9/pkg/util/admission/io_load_listener.go#L541)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

This logging is very useful. Could you also add a log.V(1) condition so we can enable it selectively even on unloaded clusters through vmodule?
</blockquote></details>

Nice. This is once every 15 seconds anyway, we just always log this. Added `log.V(1)` for now.
___
*[`pkg/util/admission/io_load_listener.go` line 826 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104577#-NY4gux77WrDttbEVybO:-NY5QaXRB5qFgytKLipp:bnus5g2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac62629e89d5a836a15e970cb2a8d500fcb9f2d9/pkg/util/admission/io_load_listener.go#L826)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I don't quite believe this. There must be a bug if that was the behavior that occurred. I don't mind this current code since it the interval [1, 2) is easy to reason about in the equations below. So maybe just say that.
</blockquote></details>

I ran this multiple times with another pr, where the only diff was that we don't multiply the score by 2, and we divide the thresholds beneath by 0.5. Fairly certain this is what was going on, which is why I think we should keep this.

I'm going to run it once more to verify.
___
*[`pkg/util/admission/io_load_listener.go` line 829 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104577#-NY5BtUC5__5plw33I25:-NY5Qv79C3dGCUZKVMRF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac62629e89d5a836a15e970cb2a8d500fcb9f2d9/pkg/util/admission/io_load_listener.go#L829)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Accidental capitalization of "O" in smoothedCompactionByteTOkens.
</blockquote></details>

Done.
___
*[`pkg/util/admission/io_load_listener.go` line 847 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104577#-NY4gX_f9dTamRHB5EWd:-NY5R3701tDQGFEd1Mx-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac62629e89d5a836a15e970cb2a8d500fcb9f2d9/pkg/util/admission/io_load_listener.go#L847)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

the last sentence "... could be adjusted ..." is what this PR is doing, so we should drop the sentence.
</blockquote></details>

Done.
___
*[`pkg/util/admission/io_load_listener.go` line 850 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104577#-NY5AYxr40X1oF965m7g:-NY5RkeT-2zEJqNhfyID:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac62629e89d5a836a15e970cb2a8d500fcb9f2d9/pkg/util/admission/io_load_listener.go#L850)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

This could use a comment block explaining why we're using the piece-wise linear function. You could also annotate this else block with the "medium load" naming convention you used in the commit message. Ditto above for "underload" and "overload".
</blockquote></details>

Done.
___
*[`pkg/util/admission/testdata/format_adjust_tokens_stats.txt` line 4 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104577#-NY55pT256pw4oUdgO_Z:-NY5RlgE-gTQHDC0a4No:bkxit8f) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac62629e89d5a836a15e970cb2a8d500fcb9f2d9/pkg/util/admission/testdata/format_adjust_tokens_stats.txt#L4)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Why is this non-zero for the zero state this test wants to print?
</blockquote></details>

The test just calls `adjustTokensInner` with a write stall count of 12. The previous for the zero case is 0.
___
*[`pkg/util/admission/testdata/io_load_listener` line 575 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104577#-NY5E5uN0qBR-1Kr2z_1:-NY5S5D15xe42qXpCP4r:bh7ty49) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac62629e89d5a836a15e970cb2a8d500fcb9f2d9/pkg/util/admission/testdata/io_load_listener#L575)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

This is not for this PR, but I continue to find tests in this file difficult to read. There's so much state, the lines are very long (so not very friendly reading it in IDEs, with or without text wrapping), and every `set-state` directive sets all state so it's hard to visually point out exactly which one was changed line by line. Do you have any ideas on for how we could improve it? I just glanced at these diffs.
</blockquote></details>

I think this test prints out a bunch of state, but when I was writing the tests here, I only cared about three variables. We could probably modify this to only selectively print the variables we want.

Not sure if that was true for the other tests here.

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104577)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @irfansharif and @sumeerbhola)

___
*[`pkg/util/admission/io_load_listener.go` line 826 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104577#-NY4gux77WrDttbEVybO:-NY5bouQ-e5ooQQQQ177:b-bnv7jo) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac62629e89d5a836a15e970cb2a8d500fcb9f2d9/pkg/util/admission/io_load_listener.go#L826)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

I ran this multiple times with another pr, where the only diff was that we don't multiply the score by 2, and we divide the thresholds beneath by 0.5. Fairly certain this is what was going on, which is why I think we should keep this.

I'm going to run it once more to verify.
</blockquote></details>

Hmm, rather than reproducing this, which would take forever, I wrote a go script to compare the differences.

```
package main

import "fmt"

func main() {
	diff := 0
	for i := 0; i < 21; i++ {
		var score1 float64
		var score2 float64
		score1 = float64(i) / float64(20)
		score2 = score1 * 2
		fmt.Println(score1, score2)
		if score1 < 0.5 && score2 >= 1 {
			diff++
		} else if score1 >= 0.5 && score1 < 1 && (score2 < 1 || score2 >= 2) {
			diff++
		} else if score1 >= 1 && score2 < 2 {
			diff++
		}
	}
	fmt.Println(diff)
}

```

and it printed out no differences at all. Maybe I did have a bug. Okay, I removed that comment.

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104577)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @irfansharif and @sumeerbhola)

___
*[`pkg/util/admission/io_load_listener.go` line 826 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104577#-NY4gux77WrDttbEVybO:-NY5hI0n5Lhev_Tahuqz:bz3thak) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac62629e89d5a836a15e970cb2a8d500fcb9f2d9/pkg/util/admission/io_load_listener.go#L826)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Hmm, rather than reproducing this, which would take forever, I wrote a go script to compare the differences.

```
package main

import "fmt"

func main() {
	diff := 0
	for i := 0; i < 21; i++ {
		var score1 float64
		var score2 float64
		score1 = float64(i) / float64(20)
		score2 = score1 * 2
		fmt.Println(score1, score2)
		if score1 < 0.5 && score2 >= 1 {
			diff++
		} else if score1 >= 0.5 && score1 < 1 && (score2 < 1 || score2 >= 2) {
			diff++
		} else if score1 >= 1 && score2 < 2 {
			diff++
		}
	}
	fmt.Println(diff)
}

```

and it printed out no differences at all. Maybe I did have a bug. Okay, I removed that comment.
</blockquote></details>

Oh this is silly, but I just realized that I was changing the score range to `[0.5, 1)`, but I didn't recompute the linear function based on that range.

**Comment by bananabrick** [comment]
The github CI lint failures are also happening on commits merged into master, and bazel ci passed. Will merge this now.

**Pull request merged**
