### PR TITLE
sql: add crdb_internal.{node,cluster}_txn_execution_insights

### LINKED ISSUE #93075: insights: split execution insights table into stmts and txns
Related to #90393.

Currently, we show all of our exec insights in `crdb_internal.{cluster,node}_execution_insights`.
As we want to surface more txn-specific information, this table should be split into 2 tables - stmt exec insights and txn exec insights.

Jira issue: CRDB-22144

### PR DESCRIPTION
**Pull request by xinhaoz**
Closes https://github.com/cockroachdb/cockroach/issues/93075

This commit adds 2 new virtual tables displaying execution
insights for transaction.
- crdb_internal.cluster_txn_execution_insights
- crdb_internal.node_txn_execution_insights

Release note (sql change):
2 new virtual tables displaying execution insights for transaction:
- crdb_internal.cluster_txn_execution_insights
- crdb_internal.node_txn_execution_insights

----------------

Only the 2nd commit is relevant here.

### CODE REVIEW

**Review by j82w — COMMENTED** [review]
> Reviewed 6 of 8 files at r1, 2 of 2 files at r2, 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94720)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`-- commits` line 11 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94720#-NL3fWy3E-NAXWPFuTnc):*
Should this have a release note since it's adding a new crdb_internal table?
___
*[`pkg/sql/crdb_internal.go` line 6977 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94720#-NL3fwhfA81H-K3hjkea:-NL3fwhfA81H-K3hjkeb:bfjfy3r) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac6d813538768709ce2e2f9add94496db572073b/pkg/sql/crdb_internal.go#L6977)):*
> ```Go
> 	}
> 	for _, insight := range response.Insights {
> 		for _, s := range insight.Statements {
> ```

nit: can the method name 'populateExecutionInsights' be updated to clarify if this is for statement or transactions to avoid confusion?
___
*[`pkg/sql/crdb_internal.go` line 7036 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94720#-NL3hIbP-4X6FHKrnd8D:-NL3hIbP-4X6FHKrnd8E:bmtvjhf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac6d813538768709ce2e2f9add94496db572073b/pkg/sql/crdb_internal.go#L7036)):*
> ```Go
> 			}
> 
> 			err = errors.CombineErrors(err, addRow(
> ```

Please add a crdb_internal test to verify the new table is popul
___
*[`pkg/sql/crdb_internal.go` line 6975 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/94720#-NL3idWE73j73-D-LOk-:-NL3idWE73j73-D-LOk0:ba24dgo) ([raw file](https://github.com/cockroachdb/cockroach/blob/4caec13a55f1295d7aae5ab6f3224fcd36bdbff5/pkg/sql/crdb_internal.go#L6975)):*
> ```Go
> 	query := ""
> 	// We should truncate the query if it surpasses some absurd limit.
> 	queryMax := 5000
> ```

Would it be better to follow the cluster_transaction_statistics where it only has the stmt fingerprints, and if users need the query string they can get using SQL. If it is necessary please use stringbuilder. String operations are pretty expensive when concatenating them. https://stackoverflow.com/questions/1760757/how-to-efficiently-concatenate-strings-in-go/47798475#47798475
___
*[`pkg/sql/sqlstats/insights/store.go` line 24 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/94720#-NL3gzW90A7L0itFGixy:-NL3gzW90A7L0itFGixz:bhpx1gk) ([raw file](https://github.com/cockroachdb/cockroach/blob/4caec13a55f1295d7aae5ab6f3224fcd36bdbff5/pkg/sql/sqlstats/insights/store.go#L24)):*
> ```Go
> 	mu struct {
> 		syncutil.RWMutex
> 		insights *cache.UnorderedCache
> ```

What's the reason for making this an UnorderedCache?

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94720)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

___
*[`-- commits` line 11 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94720#-NL3fWy3E-NAXWPFuTnc):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Should this have a release note since it's adding a new crdb_internal table?
</blockquote></details>

Added.
___
*[`pkg/sql/crdb_internal.go` line 6977 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94720#-NL3fwhfA81H-K3hjkea:-NLMLLzX3tyoxShDV2jh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac6d813538768709ce2e2f9add94496db572073b/pkg/sql/crdb_internal.go#L6977)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

nit: can the method name 'populateExecutionInsights' be updated to clarify if this is for statement or transactions to avoid confusion?
</blockquote></details>

Done.
___
*[`pkg/sql/crdb_internal.go` line 7036 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94720#-NL3hIbP-4X6FHKrnd8D:-NLMmj5Q38HZJuUgs-29:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac6d813538768709ce2e2f9add94496db572073b/pkg/sql/crdb_internal.go#L7036)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Please add a crdb_internal test to verify the new table is popul
</blockquote></details>

Done.
___
*[`pkg/sql/crdb_internal.go` line 6975 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/94720#-NL3idWE73j73-D-LOk-:-NLML3ps4XSpBnl9QGEm:b-7tv3uu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4caec13a55f1295d7aae5ab6f3224fcd36bdbff5/pkg/sql/crdb_internal.go#L6975)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Would it be better to follow the cluster_transaction_statistics where it only has the stmt fingerprints, and if users need the query string they can get using SQL. If it is necessary please use stringbuilder. String operations are pretty expensive when concatenating them. https://stackoverflow.com/questions/1760757/how-to-efficiently-concatenate-strings-in-go/47798475#47798475
</blockquote></details>

I think it would be better to have it for now since we're trying to avoid 2 RPC fanouts on the txn insights page. Switched to string builder, thanks for the callout!
___
*[`pkg/sql/sqlstats/insights/store.go` line 24 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/94720#-NL3gzW90A7L0itFGixy:-NLMkIyS-7FlKkD9_IzZ:b-p8aatn) ([raw file](https://github.com/cockroachdb/cockroach/blob/4caec13a55f1295d7aae5ab6f3224fcd36bdbff5/pkg/sql/sqlstats/insights/store.go#L24)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

What's the reason for making this an UnorderedCache?
</blockquote></details>

See https://github.com/cockroachdb/cockroach/pull/93284#issuecomment-1358525381

**Review by j82w — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r4, 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94720#-:-NLN37144Q7gWl8kJ0jK:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`pkg/sql/crdb_internal.go` line 7036 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94720#-NL3hIbP-4X6FHKrnd8D:-NLN6BO9-xWXQJLXzFZr:b8y3elr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac6d813538768709ce2e2f9add94496db572073b/pkg/sql/crdb_internal.go#L7036)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please make sure to add e2e tests.

**Review by rharding6373 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94720#-:-NM10vkT1Uw8G1evTrAR:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @j82w and @xinhaoz)

___
*[`pkg/sql/crdb_internal.go` line 6911 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/94720#-NM0of2L2zMWQiPDsg14:-NM0of2L2zMWQiPDsg15:b-936k3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/f94eebaefb4f8affb52a47156c199fd6e758e0dd/pkg/sql/crdb_internal.go#L6911)):*
> ```Go
> 	problems                   STRING[] NOT NULL,
> 	causes                     STRING[] NOT NULL,
>   stmt_execution_ids         STRING[] NOT NULL
> ```

minor nit: indentation

**Comment by xinhaoz** [comment]
TFTR!
bors r+

**Pull request merged**
