### PR TITLE
sql: remove interleaved join

### PR DESCRIPTION
**Pull request by yuzefovich**
**logictest: merge two files**

This commit merges `select_for_update_nowait_interleaved` into
`select_for_update` because the issue with the interleaved joins and
multitenancy has been resolved.

Release note: None

**sql: remove interleaved join**

This commit removes all the code related to interleaved joins (merge
joins will now be planned instead) because the interleaved join is
under-tested and doesn't offer performance improvements against the
merge joiner (especially vectorized one) in most cases.

Release note (sql change): Interleaved joins have been enterily removed,
and merge joins will now be planned in all cases when interleaved joins
would have been planned previously.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
opt part LGTM. Thanks for doing this! Looks like a bunch of logic tests still need to be updated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54163#-:-MGsb6460C6kY8nUbpMf:b-jzcddw)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
I think I fixed all the issues now with the tests. I decided to actually not remove the interleaving from the logic tests and simply renamed the files in order to not lose coverage of the interleaving tables. RFAL.

**Review by jordanlewis — APPROVED** [review]
LGTM, this must have been satisfying!

**Comment by yuzefovich** [comment]
Yes, it was very satisfying :)

TFTRs!

bors r+

**Pull request merged**
