### PR TITLE
schemachanger: remove subzone fallbacks

### LINKED ISSUE #130900: schemachanger: remove subzone fallback cases in the DSC
Once partitions work is done, we should have enough zone configuration changes to unblock the subzone fallback cases in our declarative schema changer.

Jira issue: CRDB-42283

Epic CRDB-31473

### PR DESCRIPTION
**Pull request by annrpom**
See individual commits for details.

Fixes: https://github.com/cockroachdb/cockroach/issues/130900

Release note: None

### CODE REVIEW

**Comment by annrpom** [comment]
I'll add a test for the 4th commit, but opening for any comments. Re: what we discussed in our tech discussion: I realized we needed a RBR fallback in drop index before we can have that test go down the DSC path 

https://github.com/cockroachdb/cockroach/issues/136320

**Review by spilchen — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 14 of 14 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135918)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom and @mgartner)

___
*[`pkg/sql/schemachanger/scplan/internal/opgen/opgen_index_zone_config.go` line 32 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/135918#-OD6yglICzBoRVAPkldH:-OD6yglICzBoRVAPkldI:b6ta9ve) ([raw file](https://github.com/cockroachdb/cockroach/blob/03b73d2418527a0bc6cb90015fda06a1f114eeb0/pkg/sql/schemachanger/scplan/internal/opgen/opgen_index_zone_config.go#L32)):*
> ```Go
> 			to(scpb.Status_ABSENT,
> 				emit(func(this *scpb.IndexZoneConfig, md *opGenContext) *scop.DiscardSubzoneConfig {
> 					if checkIfDescriptorHasGCDependents(md) {
> ```

Do we need to filter based on the table ID?
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/index_zone_config.go` line 414 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/135918#-OD6vOnzCDietj-3B4dO:-OD6vOnzCDietj-3B4dP:bm4rayp) ([raw file](https://github.com/cockroachdb/cockroach/blob/77ccba5f3900bdf7056e941ee69dba3dd2de9fe2/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/index_zone_config.go#L414)):*
> ```Go
> 		indexElems := b.ResolveIndex(tableID, tree.Name(indexName), ResolveParams{})
> 		indexID = indexElems.FilterIndexName().
> 			Filter(func(current scpb.Status, _ scpb.TargetStatus, _ *scpb.IndexName) bool {
> ```

nit: I think you can use `Filter(publicStatusFilter)` here instead. 
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go` line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135918#-OD6rUk90J34vcyMm4GS:-OD6rUk90J34vcyMm4GT:b4lykg4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b59853158b73ab7d758f464d772ab9dab91671ee/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go#L40)):*
> ```Go
> // changer is enabled. Operations marked as non-fully supported can only be
> // with the use_declarative_schema_changer session variable.
> var supportedStatements = map[reflect.Type]supportedStatement{
> ```

I like updating the order here. Should we leave a comment to say that the operations should be ordered to help protect against future changes?
___
*[`pkg/ccl/partitionccl/drop_test.go` line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135918#-OD6qldp0Lm-J-bEc-OP:-OD6qldp0Lm-J-bEc-OQ:b-cbay5u) ([raw file](https://github.com/cockroachdb/cockroach/blob/c48dd422b6faa9c855864f11973744db103cf722/pkg/ccl/partitionccl/drop_test.go#L89)):*
> ```Go
> 	ttl := "gc.ttlseconds = 1"
> 	sqlutils.SetZoneConfig(t, sqlDB, "INDEX t.kv@kv_pkey",
> 		fmt.Sprintf("num_replicas = %d", *s.DefaultZoneConfig().NumReplicas))
> ```

nit: shouldn't this be discarding the old zone config? i.e. `CONFIGURE ZONE DISCARD`
___
*[`pkg/sql/zone_test.go` line 215 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135918#-OD6rB-6-jHmtahwvOS1:-OD6rB-6-jHmtahwvOS2:bywqmqp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c48dd422b6faa9c855864f11973744db103cf722/pkg/sql/zone_test.go#L215)):*
> ```Go
> 	sqlutils.TxnSetZoneConfig(t, sqlDB, txn, "RANGE default", gcOverride)
> 	sqlutils.TxnSetZoneConfig(t, sqlDB, txn, "TABLE d.t",
> 		fmt.Sprintf("num_replicas = %d", *s.DefaultZoneConfig().NumReplicas)) // this should pick up the overridden default config
> ```

nit: the comment doesn't make sense anymore. Unless we switch this to cause a `CONFIGURE ZONE DISCARD` to happen.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go` line 95 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/135918#-OD6ze1P6dPb7XC-npvX:-OD6ze1P6dPb7XC-npvY:b-8s5s9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/03b73d2418527a0bc6cb90015fda06a1f114eeb0/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go#L95)):*
> ```Go
> 		panic(errors.AssertionFailedf("programming error: cannot find secondary index element."))
> 	}
> 	// TODO(136320): If a region is being added or dropped on this database, we
> ```

I'm a bit confused by this comment, particularly the part that states, _"If a region is being added or dropped on this database."_ Don't we already know the operation being performed here—dropping an index? Or does this operation also occur during the addition or removal of a region? 

Also, doesn't this have broader implications now aside from the zone config stuff. i.e. you cannot drop an index for an RBR table using the DSC.

**Review by annrpom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135918)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @spilchen)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go` line 95 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/135918#-OD6ze1P6dPb7XC-npvX:-OD89hNJ9gNUWHcFfyxS:bceddm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/03b73d2418527a0bc6cb90015fda06a1f114eeb0/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go#L95)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

I'm a bit confused by this comment, particularly the part that states, _"If a region is being added or dropped on this database."_ Don't we already know the operation being performed here—dropping an index? Or does this operation also occur during the addition or removal of a region? 

Also, doesn't this have broader implications now aside from the zone config stuff. i.e. you cannot drop an index for an RBR table using the DSC.
</blockquote></details>

this comment is indeed confusing -- i have reworded it to:

```
	// TODO(136320): If a region is being added or dropped on this database
	// concurrently, we have to block dropping an index for RBR tables. The logic
	// for detecting a concurrent ADD/DROP region is not yet in the DSC; falling
	// back for now.
```

but let me know if this is still confusing

re: broader implications -- the fallback that we removed already blocked this ddl if the table had any subzone configs (which rbr tables do out of the box; i believe it's [here](https://github.com/cockroachdb/cockroach/blob/d7ce9f7451da8b6a97bbfe222b7bde62ae2f5654/pkg/sql/create_table.go#L488))

but thinking about your question more: a user could have just removed all subzone configs from their rbr table if they have set `override_multi_region_zone_config = true. i wouldn't expect this to be the use case most of the time, but let me see what we want to do here
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/index_zone_config.go` line 414 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/135918#-OD6vOnzCDietj-3B4dO:-OD8DfW31tMOrO8XJHf6:b-fnrt5p) ([raw file](https://github.com/cockroachdb/cockroach/blob/77ccba5f3900bdf7056e941ee69dba3dd2de9fe2/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/index_zone_config.go#L414)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

nit: I think you can use `Filter(publicStatusFilter)` here instead.
</blockquote></details>

done ty!
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go` line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135918#-OD6rUk90J34vcyMm4GS:-OD8EU5aAHzMEf2tJKtD:b-fnrx58) ([raw file](https://github.com/cockroachdb/cockroach/blob/b59853158b73ab7d758f464d772ab9dab91671ee/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go#L40)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

I like updating the order here. Should we leave a comment to say that the operations should be ordered to help protect against future changes?
</blockquote></details>

done oki
___
*[`pkg/sql/schemachanger/scplan/internal/opgen/opgen_index_zone_config.go` line 32 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/135918#-OD6yglICzBoRVAPkldH:-ODH7JCE2_2hEfJHdDZp:bgdv0z1) ([raw file](https://github.com/cockroachdb/cockroach/blob/03b73d2418527a0bc6cb90015fda06a1f114eeb0/pkg/sql/schemachanger/scplan/internal/opgen/opgen_index_zone_config.go#L32)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Do we need to filter based on the table ID?
</blockquote></details>

done -- i did something similar to `checkIfDescriptorIsWithoutData` where we skip the element if it does not have the correct descriptor id
___
*[`pkg/ccl/partitionccl/drop_test.go` line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135918#-OD6qldp0Lm-J-bEc-OP:-ODHN6Rg2bc57oxvsXCn:b-vhvlix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c48dd422b6faa9c855864f11973744db103cf722/pkg/ccl/partitionccl/drop_test.go#L89)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

nit: shouldn't this be discarding the old zone config? i.e. `CONFIGURE ZONE DISCARD`
</blockquote></details>

ah this syntax is a bit confusing -- so this is essentially a no-op unless this is the first `CONFIGURE ZONE` statement for the object. if it's the first `CONFIGURE ZONE` statement, we end up creating a zone config entry in the system.zones table. the reason to do this is so that we stop inheriting from the parent zone config. so you should be able to do something like to see this demonstrated:

```
-- create table t
select * from system.zones;

alter table t configure zone = '';

select * from system.zones;

-- see new entry here for table t

alter table t configure zone using num_replicas = 11;

alter table t configure zone = '';

select jsonb_pretty(crdb_internal.pb_to_json('cockroach.config.zonepb.ZoneConfg', config))                                                from system.zones where id = 't'::regclass::oid; 

-- note how num_replicas/the entire zone config has not been discarded

```
___
*[`pkg/sql/zone_test.go` line 215 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135918#-OD6rB-6-jHmtahwvOS1:-ODHOEE8BcYVoHPqOxvg:bnj7hl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c48dd422b6faa9c855864f11973744db103cf722/pkg/sql/zone_test.go#L215)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

nit: the comment doesn't make sense anymore. Unless we switch this to cause a `CONFIGURE ZONE DISCARD` to happen.
</blockquote></details>

same as above

**Review by annrpom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135918)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @spilchen)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go` line 95 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/135918#-OD6ze1P6dPb7XC-npvX:-ODIevug9GoMMnFDuifN:b-pi5lni) ([raw file](https://github.com/cockroachdb/cockroach/blob/03b73d2418527a0bc6cb90015fda06a1f114eeb0/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go#L95)):*
<details><summary><i>Previously, annrpom (annie pompa) wrote…</i></summary><blockquote>

this comment is indeed confusing -- i have reworded it to:

```
	// TODO(136320): If a region is being added or dropped on this database
	// concurrently, we have to block dropping an index for RBR tables. The logic
	// for detecting a concurrent ADD/DROP region is not yet in the DSC; falling
	// back for now.
```

but let me know if this is still confusing

re: broader implications -- the fallback that we removed already blocked this ddl if the table had any subzone configs (which rbr tables do out of the box; i believe it's [here](https://github.com/cockroachdb/cockroach/blob/d7ce9f7451da8b6a97bbfe222b7bde62ae2f5654/pkg/sql/create_table.go#L488))

but thinking about your question more: a user could have just removed all subzone configs from their rbr table if they have set `override_multi_region_zone_config = true. i wouldn't expect this to be the use case most of the time, but let me see what we want to do here
</blockquote></details>

https://cockroachlabs.slack.com/archives/GQ5GJ1ELB/p1733346935194059

**Review by spilchen — APPROVED** [review]
:lgtm: I have a few suggestions for optimizing some of the functions, if you're interested.

> Reviewed 1 of 17 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, 12 of 15 files at r10, 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135918#-:-ODLq4ZoCU5ppMQZqF_p:b5rsfvp)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @annrpom and @mgartner)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go` line 95 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/135918#-OD6ze1P6dPb7XC-npvX:-ODLjljh1U7w6JfRkDby:bcdq3nt) ([raw file](https://github.com/cockroachdb/cockroach/blob/03b73d2418527a0bc6cb90015fda06a1f114eeb0/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go#L95)):*
<details><summary><i>Previously, annrpom (annie pompa) wrote…</i></summary><blockquote>

https://cockroachlabs.slack.com/archives/GQ5GJ1ELB/p1733346935194059
</blockquote></details>

Thanks the comment is good. And I understand the context better now.
___
*[`pkg/ccl/partitionccl/drop_test.go` line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135918#-OD6qldp0Lm-J-bEc-OP:-ODLpxe4CZ4674vEau0K:b9zpisr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c48dd422b6faa9c855864f11973744db103cf722/pkg/ccl/partitionccl/drop_test.go#L89)):*
<details><summary><i>Previously, annrpom (annie pompa) wrote…</i></summary><blockquote>

ah this syntax is a bit confusing -- so this is essentially a no-op unless this is the first `CONFIGURE ZONE` statement for the object. if it's the first `CONFIGURE ZONE` statement, we end up creating a zone config entry in the system.zones table. the reason to do this is so that we stop inheriting from the parent zone config. so you should be able to do something like to see this demonstrated:

```
-- create table t
select * from system.zones;

alter table t configure zone = '';

select * from system.zones;

-- see new entry here for table t

alter table t configure zone using num_replicas = 11;

alter table t configure zone = '';

select jsonb_pretty(crdb_internal.pb_to_json('cockroach.config.zonepb.ZoneConfg', config))                                                from system.zones where id = 't'::regclass::oid; 

-- note how num_replicas/the entire zone config has not been discarded

```
</blockquote></details>

Ah ok, got it.
___
*[`pkg/sql/schemachanger/scplan/internal/opgen/op_funcs.go` line 204 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/135918#-ODLp8jTD8_ah7G7n_rL:-ODLp8jTD8_ah7G7n_rM:b2kcey7) ([raw file](https://github.com/cockroachdb/cockroach/blob/148c25a399784501a3def183379c656c3c0ae165/pkg/sql/schemachanger/scplan/internal/opgen/op_funcs.go#L204)):*
> ```Go
> 		case *scpb.TableData:
> 			// Filter out any elements we do not want to consider.
> 			if !pred(t.Element()) {
> ```

nit: since we are always going to be dealing with a `scpb.TableData` struct, could we just pass that in instead? It means we don't have to use any helper to get an attribute. We can just refer to the tableID or databaseID directly from the struct.
___
*[`pkg/sql/schemachanger/scplan/internal/opgen/op_funcs.go` line 227 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/135918#-ODLl2VABscRStZW_lGX:-ODLl2VABscRStZW_lGY:bu5oku1) ([raw file](https://github.com/cockroachdb/cockroach/blob/148c25a399784501a3def183379c656c3c0ae165/pkg/sql/schemachanger/scplan/internal/opgen/op_funcs.go#L227)):*
> ```Go
> 		}
> 		switch t.Element().(type) {
> 		case *scpb.IndexData:
> ```

nit: It would be more optimal to check the `tableID` _after_ confirming the element is an `IndexData`. Since the vast majority of elements won’t be `IndexData`, this avoids unnecessary `GetDescID` calls. Additionally, instead of using the `GetDescID` helper, we can directly access the field from the element, which is likely more efficient.



_Suggestion:_
```Go
		switch e := t.Element().(type) {
		case *scpb.IndexData:
			// Validate this is the table ID we are
			// looking for.
			if e.TableID != tableID {
				continue
			}		
```

**Review by annrpom — COMMENTED** [review]
i am always interested -- ty for the suggestions

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135918#-:-ODNNfyM34Xw7bUoQFl2:b-s6qr74)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/schemachanger/scplan/internal/opgen/op_funcs.go` line 204 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/135918#-ODLp8jTD8_ah7G7n_rL:-ODNP9jK91CHmYFW--Xa:b-8o9muu) ([raw file](https://github.com/cockroachdb/cockroach/blob/148c25a399784501a3def183379c656c3c0ae165/pkg/sql/schemachanger/scplan/internal/opgen/op_funcs.go#L204)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

nit: since we are always going to be dealing with a `scpb.TableData` struct, could we just pass that in instead? It means we don't have to use any helper to get an attribute. We can just refer to the tableID or databaseID directly from the struct.
</blockquote></details>

done it was a bit of logic that i was trying to cover: i wanted there to be a way to avoid having to do some " if it's for a table, only look at table id; if it's for db, only look at db id"

but yeah i think doing all of that to just get the attribute whenever we have it already is unnecessary -- changed!
___
*[`pkg/sql/schemachanger/scplan/internal/opgen/op_funcs.go` line 227 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/135918#-ODLl2VABscRStZW_lGX:-ODNo_Je2eq8DvIOiXNJ:bvbkbuq) ([raw file](https://github.com/cockroachdb/cockroach/blob/148c25a399784501a3def183379c656c3c0ae165/pkg/sql/schemachanger/scplan/internal/opgen/op_funcs.go#L227)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

nit: It would be more optimal to check the `tableID` _after_ confirming the element is an `IndexData`. Since the vast majority of elements won’t be `IndexData`, this avoids unnecessary `GetDescID` calls. Additionally, instead of using the `GetDescID` helper, we can directly access the field from the element, which is likely more efficient.
</blockquote></details>

done -- ty for the catch !

**Comment by annrpom** [comment]
TFTR! ('-')7 

bors r+

**Pull request merged**
