### PR TITLE
release-2.1: cli: add a `cockroach workload` subcommand

### PR DESCRIPTION
**Pull request by danhhz**
Backport 3/3 commits from #28390.

/cc @cockroachdb/release

---

Only a selection of the current workloads are included to allow the
others to mature and prove their usefulness to users.

The following cobra command hierarchy is established under `cockroach
workload`:

    check         a running cluster's data for consistency
        [generator]
    csv-server    serves csv table data through an HTTP interface
    init          set up tables for a workload
        [generator]
    run           run a workload's operations against a cluster
        [generator]
    fixtures      tools for quickly synthesizing and loading large datasets
        list          list all fixtures stored on GCS
        make          regenerate and store a fixture on GCS
            [generator]
        load          load a fixture into a running cluster. An enterprise license is required.
            [generator]
        url           generate the GCS URL for a fixture
            [generator]

bin/workload is unchanged and contains the full list of all workloads.

Release note (cli change): A `cockroach workload` subcommand has been
added which provides various generators for data and query loads and
tools for working with them.

### CODE REVIEW

**Review by benesch — APPROVED** [review]

**Comment by danhhz** [comment]
TFTR!

bors r=benesch

**Comment by jseldess** [comment]
@danhhz, just starting to look at this, but it's awesome. Thank you!

A few quick questions:

- I've already used `cockroach workload init bank` and `cockroach workload run bank`, so I know how those subcommands work. But I don't see how `cockroach workload fixtures` is applicable for external users:

```
~/go/src/github.com/cockroachdb/cockroach$ cockroach workload fixtures
Usage:
  cockroach workload fixtures [flags]
  cockroach workload fixtures [command]

Available Commands:
  list        list all fixtures stored on GCS
  make        regenerate and store a fixture on GCS
  load        load a fixture into a running cluster. An enterprise license is required.
  url         generate the GCS URL for a fixture

Flags:
      --gcs-billing-project string   Google Cloud project to use for storage billing; required to be non-empty if the bucket is requestor pays
  -h, --help                         help for fixtures

Global Flags:
      --log-backtrace-at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log-dir string                   if non-empty, write log files in this directory
      --log-dir-max-size bytes           maximum combined size of all log files (default 100 MiB)
      --log-file-max-size bytes          maximum size of each log file (default 10 MiB)
      --log-file-verbosity Severity      minimum verbosity of messages written to the log file (default INFO)
      --logtostderr Severity[=DEFAULT]   logs at or above this threshold go to stderr (default NONE)
      --no-color                         disable standard error log colorization
      --verbosity level                  log level for V logs (significantly increases log output)
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging (significantly hurts performance)

Use "cockroach workload fixtures [command] --help" for more information about a command.
~/go/src/github.com/cockroachdb/cockroach$ cockroach workload fixtures list
Error: failed to create google cloud client (You may need to setup the GCS application default credentials: 'gcloud auth application-default login --project=cockroach-shared'): dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```

- I also don't know if/when a user would want/need to use `cockroach workload check/csv-server`. Can you clarify?

**Comment by danhhz** [comment]
I've been going back and forth on the fixtures stuff. They are for loading datasets that are too large to do with batched INSERTs in a reasonable time (think tpcc-1000). We store them as backups and use them for our nightly roachtests, but they might also be useful for a user that wants to test a large cluster.

`workload fixtures make` makes a new fixture and stores it to google cloud storage. `workload fixtures list` shows the existing fixtures. `workload fixtures load` restores a fixture into a cluster. All of them require the user to set up google cloud storage credentials.

I think what I'll do is hide them for 2.1.0 and re-enable if/when they're useful. For example, we might want the tpcc-1000 fixture for some performance docs.

`workload csv-server` is used to make fixtures. I'll hide it.

`workload check` is to verify that the internal invariants of a test hold after running it (tpcc for example defines a number of these). They are essentially testing our correctness. Probably also more confusing than helpful to expose to external users.

**Comment by danhhz** [comment]
Okay @jseldess, once https://github.com/cockroachdb/cockroach/pull/29273 merges we'll only have `cockroach workload init` and `cockroach workload run`. While I'm in here, are they any changes to the help text (or other changes) that you want? I'm going to have a limited time to devote to this until changefeeds are further along, so I'd be nice to get everything done in one followup.

**Comment by jseldess** [comment]
Actually, after discussing offline, I think your PR is good to go. I'll open issues for UX-related follow-up work when there's time.

**Pull request merged**
