### PR TITLE
Remove unnecessary method argument to ExecuteCmd and AddCmd.

### PR DESCRIPTION
**Pull request by petermattis**

### CODE REVIEW

**Comment by spencerkimball** [comment]
LGTM

**Comment by tschottdorf** [comment]
LGTM, unless we ever want to log the method executed there.

**Comment by bdarnell** [comment]
LGTM. @tschottdorf The method name can be derived from the argument type, so we don't lose anything by making this change.

**Comment by petermattis** [comment]
@tschottdorf to add to what Ben said, see `proto.Request.Method()` and the implementations in `proto/api.go`.

**Pull request merged**
