### PR TITLE
workload, logictest: fix miscellaneous TODOs related to TPCH

### PR DESCRIPTION
**Pull request by yuzefovich**
Release justification: non-production code changes.

Release note: None

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46034)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/workload/querybench/query_bench.go, line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46034#-M2J1pBZEyfBBGVC8BIT:-M2J1pBZEyfBBGVC8BIU:b-8g8hw1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e88024c28e4f65a42edfd9b5da4ce010dcfa79dd/pkg/workload/querybench/query_bench.go#L134)):*
> ```Go
> 			// Fall back to using the pre-19.2 syntax.
> 			// TODO(asubiotto): Remove this once we stop running this test against
> 			//  19.1.
> ```

How are we sure we don't run this against 19.1 anymore?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46034)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/workload/querybench/query_bench.go, line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46034#-M2J1pBZEyfBBGVC8BIT:-M2J60fzA4-EhMDN_t2Z:b-2dklsj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e88024c28e4f65a42edfd9b5da4ce010dcfa79dd/pkg/workload/querybench/query_bench.go#L134)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

How are we sure we don't run this against 19.1 anymore?
</blockquote></details>

Good point. I think we can now bump the minimum version in `tpchbench` roachtest.

**Comment by yuzefovich** [comment]
Friendly ping.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46034#-:-M3Ave-HBqYS6gmrz-K4:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
