### PR TITLE
release-23.2: status: add network packet dropped and error metrics

### PR DESCRIPTION
**Pull request by nvb**
Backport 2/2 commits from #116005.

/cc @cockroachdb/release

Release justification: improves observability of networking instability. Assists L2 escalations.

---

This commit adds packet drop/error counter on network's sending and receiving end. These metrics are derived from the os and aims for better observability on tail latencies.

The second added chart looks like below for number of packets, packets error, and packets dropped on sending and receiving end.

Screenshot 2023-12-13 at 4 49 11 PM

Fixes: #115458

Release note(ui change): the DB Console metrics dashboard's Networking tab is
enhanced with charts that visualize number of packets received, number of
receiving packets with error, number of receiving packets got dropped, number
of packets sent, number of sending packets with error, and number of sending
packets got dropped.

### CODE REVIEW

**Comment by lyang24** [comment]
Thank you Nathan

**Comment by erikgrinaker** [comment]
Do these metrics cover TCP retransmits, or only packets dropped by the sending OS (e.g. due to full send buffers)? In the vast majority of cases, packet loss happens in transit, not on the sender, and OS networking metrics typically expose these in terms of retransmits not drops.

**Comment by lyang24** [comment]
> Do these metrics cover TCP retransmits, or only packets dropped by the sending OS (e.g. due to full send buffers)? In the vast majority of cases, packet loss happens in transit, not on the sender, and OS networking metrics typically expose these in terms of retransmits not drops.
This commit does not include tcp retransmits, it includes metric and ui graphs on total packets, packets with errors, and drops due to full buffer. Tcp retransmits are a helpful metric we can look into in future iterations i did some research i think it can be collected by netstats -s call, I wonder is there a tested golang library that provides this by api? 
```
eyang@HQ-C02FC4D6MD6T cockroach % netstat -s -t
tcp:
	0 packet sent
		0 data packet (0 byte)
		0 data packet (0 byte) retransmitted
```

**Review by erikgrinaker — APPROVED** [review]
Yeah, makes sense to address that separately. Thanks!

**Review by dhartunian — APPROVED** [review]

**Pull request merged**
