### PR TITLE
sql: add attidentity and attgenerated columns to pg_catalog.pg_attribute

### LINKED ISSUE #48541: sql: add attidentity and attgenerated columns to pg_attribute
The `pg_catalog.pg_attribute` table in CockroachDB currently does not contain `attidentity` or `attgenerated` columns. It seems like these were added in Postgres versions 10 and 12, respectively.

attidentity | char |   | If a zero byte (''), then not an identity column. Otherwise, a = generated always, d = generated by default.
-- | -- | -- | --
attgenerated | char |   | If a zero byte (''), then not a generated column. Otherwise, s = stored. (Other values might be added in the future.)

https://www.postgresql.org/docs/12/catalog-pg-attribute.html

This was initially discovered because class generation functionality in .NET/npgsql/EntityFramework relies on this metadata. [The query it uses is here](https://github.com/npgsql/efcore.pg/blob/95bced395fd5f98359782855c98b48cfd5522edf/src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs#L245).

### PR DESCRIPTION
**Pull request by spiffyy99**
Before: The pg_catalog.pg_attribute table only contained columns
included in up to Postgres 9.5.

Why: Needed because the .NET EntityFramework requires this metadata
for C# class generation functionality.

Now: The pg_catalog.pg_attribute now contains the attidentity (not
implemented) and attgenerated (implemented) columns, which were added in
Postgres 10 and 12, respectively. attgenerated contains 's' for
computed columns (also called generated columns) and the zero byte ('')
otherwise.

Resolves: #48541

Release note (sql change): the pg_catalog.pg_attribute table now
contains the columns attidentity (unimplemented) and attgenerated
(implemented, 's' for computed/generated columns).

### CODE REVIEW

**Comment by r6min** [comment]
Had to recreate due to the PR not picking up my newest commit, #51302 for the old review chain

**Review by RichardJCai — APPROVED** [review]
LGTM!

**Review by otan — APPROVED** [review]

**Comment by r6min** [comment]
bors retry

**Pull request merged**
