### PR TITLE
sql: Add "or-if-not-exists" semantics to `CPut` and use it in index entry writes

### LINKED ISSUE #33260: sql: UPDATE while schema change can result in error
**Describe the problem**

doing UPDATEs can result in errors while a CREATE INDEX is running.

error message & query:
```
ERROR:  value type is not BYTES: UNKNOWN
UPDATE "cache" SET "value" = $1, "updated" = $2, "expires" = $3 WHERE "id" = $4
```
schema:
```
CREATE TABLE cache
(
  id SERIAL PRIMARY KEY
);

ALTER TABLE cache ADD COLUMN method STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_method;
ALTER TABLE cache ADD COLUMN name STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_name;
ALTER TABLE cache ADD COLUMN value STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_value;
ALTER TABLE cache ADD COLUMN locked INT NOT NULL DEFAULT 0 CREATE IF NOT EXISTS FAMILY family_locked;
ALTER TABLE cache ADD COLUMN created INT NOT NULL DEFAULT 0 CREATE IF NOT EXISTS FAMILY family_created;
ALTER TABLE cache ADD COLUMN updated INT NOT NULL DEFAULT 0 CREATE IF NOT EXISTS FAMILY family_updated;
ALTER TABLE cache ADD COLUMN expires INT NOT NULL DEFAULT 0 CREATE IF NOT EXISTS FAMILY family_expires;

CREATE INDEX method_name ON cache (method, name);
```

schema change:
```
CREATE INDEX method_name_storing_value ON cache (method, name) STORING (value);
```

**Environment:**
CockroachDB CCL v2.1.2 (x86_64-unknown-linux-gnu, built 2018/12/10 20:15:47, go1.10.3)

### PR DESCRIPTION
**Pull request by dt**
This switches index updates to use a new `CPut` behavior, to fix the
handling of valid update operations that are processed during the
backfill for indexes that have values -- such as UNIQUE indexes as well
as non-unique indexes that include STORING columns.

We need to use `CPut` for maintaining index entries (at least for UNIQUE
indexes) to avoid clobbering entries for other rows. During the backfill
we cannot assume an entry with the old value actually exists however.
Thus a normal `CPut` on them from the prior value to the new value also
asserts they exist, which isn't always true.

This issue is a little hard to hit: we only emit a `CPut` from the old
value to the new value when a) the key is the same and b) the values are
different. If any indexed values changed, we'd be deleting the old entry
and `CPut`ting a new one which we (correctly) expect not to exist at
all. Only when updating the same key to a new value -- i.e. when handing
an update to only a STORING column or some UNIQUE cases -- do we do this
in-place CPut from old to new and then only when we happen to be
operating on keys not yet reached by the backfiller do we incorrectly
assume it exists with value old.

Since we put many CPuts in the batch at once, we can't easily retry in
SQL with nil vs old values so we need new CPut semantics to fix this.

This adds a flag to `CPut` to optionally allow a put which expects a given existing 
value to succeed if instead that key does not exist.

This is useful in sitations where the client is trying to avoid overwriting an existing 
entry other than the one it thinks should exist, but also wants to allow for it not to exist.
Specifically, when writing secondary index entries, particularly for unique indexes, 
we use `CPut` to ensure that we're not overwriting the index entry for a different 
row -- if we are, we expect the `CPut` to fail.

Fixes #33260.

Release note (bug fix): Fix bug when that would return errors when
handling valid UPDATEs during periods of an index creation schema
change.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
LGTM modulo nit. Again, well found

> Reviewed 7 of 7 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35157#-:-LZLhy6W7NCeAJw6_ok4:b-n1eosk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @dt, @jordanlewis, and @lucy-zhang)

___
*[pkg/sql/row/writer.go, line 755 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35157#-LZLho7_BCiltx-NMW2T:-LZLho7_BCiltx-NMW2U:beum9hl) ([raw file](https://github.com/cockroachdb/cockroach/blob/c91a03d7fc5ed31194883c66cf70c232660d5a91/pkg/sql/row/writer.go#L755)):*
> ```Go
> 
> 		if traceKV {
> 			log.VEventf(ctx, 2, "CPut %s -> %v", keys.PrettyPrint(ru.Helper.secIndexValDirs[i], newSecondaryIndexEntry.Key), newSecondaryIndexEntry.Value.PrettyPrint())
> ```

please update the event text (and the corresponding filter regexps in SHOW KV TRACE FOR SESSION)

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35157)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @jordanlewis, @knz, and @lucy-zhang)

___
*[pkg/sql/row/writer.go, line 755 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35157#-LZLho7_BCiltx-NMW2T:-LZLnP203e6eWp1m9zsZ:b-gwgzne) ([raw file](https://github.com/cockroachdb/cockroach/blob/c91a03d7fc5ed31194883c66cf70c232660d5a91/pkg/sql/row/writer.go#L755)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

please update the event text (and the corresponding filter regexps in SHOW KV TRACE FOR SESSION)
</blockquote></details>

any suggestions on what to call it? `CPutAllowingIfNotExists` seems stupidly verbose.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35157)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @jordanlewis, @knz, and @lucy-zhang)

___
*[pkg/sql/row/writer.go, line 755 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35157#-LZLho7_BCiltx-NMW2T:-LZLoC4h7s-S62BYWdIh:b-p3wbux) ([raw file](https://github.com/cockroachdb/cockroach/blob/c91a03d7fc5ed31194883c66cf70c232660d5a91/pkg/sql/row/writer.go#L755)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

any suggestions on what to call it? `CPutAllowingIfNotExists` seems stupidly verbose.
</blockquote></details>

eh, nvm, I just remembered that in debugging, Jordan and I wanted to see the expected value for the cput in the trace too, so I'll just tack an "(expecting %v if exists) on the end there.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35157)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @jordanlewis, @knz, and @lucy-zhang)

___
*[pkg/sql/row/writer.go, line 755 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35157#-LZLho7_BCiltx-NMW2T:-LZLvObk3m-4lDgMrpYG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c91a03d7fc5ed31194883c66cf70c232660d5a91/pkg/sql/row/writer.go#L755)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

eh, nvm, I just remembered that in debugging, Jordan and I wanted to see the expected value for the cput in the trace too, so I'll just tack an "(expecting %v if exists) on the end there.
</blockquote></details>

Done.

**Comment by dt** [comment]
interesting. This CI failure _feels_ like it should be related to my change since it is inspecting the trace output of UPDATE and I did change that output, but it isn't the CPut line that seems to have changed, but rather, these two extra lines from a txn push:
```
                    dist sender send  querying next range at /Table/SystemConfigSpan/Start
                    dist sender send  r6: sending batch 1 PushTxn to (n1,s1):1
```
in the middle of 
```
                    dist sender send  querying next range at /Table/2/1/53/"kv2"/3/1
                    dist sender send  r6: sending batch 1 Get to (n1,s1):1
                    dist sender send  querying next range at /Table/3/1/55/2/1
                    dist sender send  r6: sending batch 1 Get to (n1,s1):1
                    dist sender send  r7: sending batch 1 EndTxn, 1 QueryIntent to (n1,s1):1
                    table reader      Scan /Table/55/{1-2}
                    dist sender send  querying next range at /Table/55/1
                    dist sender send  r20: sending batch 1 Scan to (n1,s1):1
                    dist sender send  querying next range at /Table/SystemConfigSpan/Start
                    dist sender send  r6: sending batch 1 PushTxn to (n1,s1):1
                    table reader      fetched: /kv2/primary/...PK.../k/v -> /1/2
                    flow              Put /Table/55/1/...PK.../0 -> /TUPLE/1:1:Int/1/1:2:Int/4
                    dist sender send  querying next range at /Table/55/1/...PK.../0
                    dist sender send  r20: sending batch 1 Put, 1 EndTxn to (n1,s1):1
                    flow              fast path completed
                    sql txn           rows affected: 1
```
https://teamcity.cockroachdb.com/viewLog.html?buildId=1148834&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_Test

It passes locally for me.

**Review by bdarnell — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35157)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @jordanlewis, @knz, and @lucy-zhang)

___
*[pkg/roachpb/api.proto, line 172 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35157#-LZM8oZC81pg3UplS7mf:-LZM8oZC81pg3UplS7mg:brs7zqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/30f975d5ac11126ddc804bd046d770c6b6251867/pkg/roachpb/api.proto#L172)):*
> ```protobuf
>   // writing to virgin keyspace and no reads are necessary to
>   // rationalize MVCC.
>   bool blind = 4;
> ```

Does the new flag interact in any interesting ways with the blind flag?
___
*[pkg/roachpb/api.proto, line 173 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35157#-LZM7wHe33_ck9OrNi9g:-LZM7wHe33_ck9OrNi9h:b1je9iy) ([raw file](https://github.com/cockroachdb/cockroach/blob/30f975d5ac11126ddc804bd046d770c6b6251867/pkg/roachpb/api.proto#L173)):*
> ```protobuf
>   // rationalize MVCC.
>   bool blind = 4;
>   // Typcically if a specific, non-empty expected value is supplied, it *must*
> ```

s/Typc/Typ/
___
*[pkg/roachpb/api.proto, line 177 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35157#-LZM8-zO8UybNXLyDPgK:-LZM8-zO8UybNXLyDPgL:b7ge11r) ([raw file](https://github.com/cockroachdb/cockroach/blob/30f975d5ac11126ddc804bd046d770c6b6251867/pkg/roachpb/api.proto#L177)):*
> ```protobuf
>   // does not exist. This is useful when a given value is expected but it is
>   // possible it has not yet been written.
>   bool allow_if_does_not_exist = 5;
> ```

How does this handle tombstones? Do they count as "not exist" or does it fail like InitPut? If they count as not existing, is the difference between CPut and InitPut a problem? If they cause it to fail, could that ever block legitimate writes?
___
*[pkg/storage/batcheval/cmd_conditional_put.go, line 50 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35157#-LZM97czA-zmmm9Pd24s:-LZM97czA-zmmm9Pd24t:b-6i4npr) ([raw file](https://github.com/cockroachdb/cockroach/blob/30f975d5ac11126ddc804bd046d770c6b6251867/pkg/storage/batcheval/cmd_conditional_put.go#L50)):*
> ```Go
> 		return result.Result{}, engine.MVCCBlindConditionalPut(ctx, batch, cArgs.Stats, args.Key, h.Timestamp, args.Value, args.ExpValue, h.Txn)
> 	}
> 	if args.AllowIfDoesNotExist {
> ```

(Partially answering my own question) It should be an error to specify both blind and allow if does not exist if we're just going to ignore one of them. Or maybe it's OK to ignore blind (which is just enabling a performance optimization) but not allow-not-exist (which affects semantics).

Blind is magically set in replica_raft.go. I think we need a guard there that ensures we never set Blind if AllowIfDoesNotExist is set (unless we can support the combination). How important is the blind optimization for cases where allow-not-exist will be set?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35157)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @dt, @jordanlewis, @knz, and @lucy-zhang)

___
*[pkg/storage/batcheval/cmd_conditional_put.go, line 50 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35157#-LZM97czA-zmmm9Pd24s:-LZMF5BqAGHVBTFb_f4-:bksrfak) ([raw file](https://github.com/cockroachdb/cockroach/blob/30f975d5ac11126ddc804bd046d770c6b6251867/pkg/storage/batcheval/cmd_conditional_put.go#L50)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

(Partially answering my own question) It should be an error to specify both blind and allow if does not exist if we're just going to ignore one of them. Or maybe it's OK to ignore blind (which is just enabling a performance optimization) but not allow-not-exist (which affects semantics).

Blind is magically set in replica_raft.go. I think we need a guard there that ensures we never set Blind if AllowIfDoesNotExist is set (unless we can support the combination). How important is the blind optimization for cases where allow-not-exist will be set? 
</blockquote></details>

I think I can make Blind and AllowNotExists work together, though I don't know if understand what Blind actually is / what it means enough to know if that is desired or even matters for index entries.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35157)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @dt, @jordanlewis, @knz, and @lucy-zhang)

___
*[pkg/storage/batcheval/cmd_conditional_put.go, line 50 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35157#-LZM97czA-zmmm9Pd24s:-LZMFzRD6MGibPY2--Db:b-bp0fv0) ([raw file](https://github.com/cockroachdb/cockroach/blob/30f975d5ac11126ddc804bd046d770c6b6251867/pkg/storage/batcheval/cmd_conditional_put.go#L50)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I think I can make Blind and AllowNotExists work together, though I don't know if understand what Blind actually is / what it means enough to know if that is desired or even matters for index entries. 
</blockquote></details>

I initially avoided adding another yet another arg to the existing `MVCCConditionalPut` function, but using separate functions for the two variants, this if/else block gets a bit messy with calls to all 4 combinations... I dunno, maybe it is still clearer what's going on than adding bool args?

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35157)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @jordanlewis, @knz, and @lucy-zhang)

___
*[pkg/storage/batcheval/cmd_conditional_put.go, line 50 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35157#-LZM97czA-zmmm9Pd24s:-LZMJrlt7MStfAfxWDRb:bquxjvy) ([raw file](https://github.com/cockroachdb/cockroach/blob/30f975d5ac11126ddc804bd046d770c6b6251867/pkg/storage/batcheval/cmd_conditional_put.go#L50)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I initially avoided adding another yet another arg to the existing `MVCCConditionalPut` function, but using separate functions for the two variants, this if/else block gets a bit messy with calls to all 4 combinations... I dunno, maybe it is still clearer what's going on than adding bool args?
</blockquote></details>

Yeah, I think we're getting beyond the point that multiple functions make sense, especially if we have to add another flag later to control the treatment of tombstones to absorb InitPut.

The blind optimization does matter at least for index backfills (that's why it's available for InitPut too: #14630). I think it's probably important for index writes from regular statements, but less so. (the original motivation for blind cputs was for batched kv insert workloads without indexes).

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35157)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @jordanlewis, @knz, and @lucy-zhang)

___
*[pkg/roachpb/api.proto, line 172 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35157#-LZM8oZC81pg3UplS7mf:-LZMK0Xn5lfqv27DOhRz:b-8j2p6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/30f975d5ac11126ddc804bd046d770c6b6251867/pkg/roachpb/api.proto#L172)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Does the new flag interact in any interesting ways with the blind flag?
</blockquote></details>

So I'm not too familiar with Blind but after looking though the code and where it is set in replica_eval, I _think_ it should get along with my new flag, but I'd certainly like to have someone with more domain expertise with it confirm that.
___
*[pkg/roachpb/api.proto, line 173 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35157#-LZM7wHe33_ck9OrNi9g:-LZMK-bYBpUlO80idtps:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/30f975d5ac11126ddc804bd046d770c6b6251867/pkg/roachpb/api.proto#L173)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

s/Typc/Typ/
</blockquote></details>

Done.
___
*[pkg/roachpb/api.proto, line 177 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35157#-LZM8-zO8UybNXLyDPgK:-LZML3BP8IfLwpnQ5S0Y:b-ce843d) ([raw file](https://github.com/cockroachdb/cockroach/blob/30f975d5ac11126ddc804bd046d770c6b6251867/pkg/roachpb/api.proto#L177)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

How does this handle tombstones? Do they count as "not exist" or does it fail like InitPut? If they count as not existing, is the difference between CPut and InitPut a problem? If they cause it to fail, could that ever block legitimate writes?
</blockquote></details>

For now I'm pretty sure this handles them the same as `CPut` did before.  I'm not wanting to replace any InitPut usage with this _for now_.

When we do get to that though, I think all callers pass `failOnTombstones = false` except for one of the index backfiller paths. I think by the time we're ready to migrate InitPut calls, that path will phased out anyway due to the SST backfiller.
___
*[pkg/storage/batcheval/cmd_conditional_put.go, line 50 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35157#-LZM97czA-zmmm9Pd24s:-LZMKo8b5tt-IUa2YJKi:b-6o4wj6) ([raw file](https://github.com/cockroachdb/cockroach/blob/30f975d5ac11126ddc804bd046d770c6b6251867/pkg/storage/batcheval/cmd_conditional_put.go#L50)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Yeah, I think we're getting beyond the point that multiple functions make sense, especially if we have to add another flag later to control the treatment of tombstones to absorb InitPut.

The blind optimization does matter at least for index backfills (that's why it's available for InitPut too: #14630). I think it's probably important for index writes from regular statements, but less so. (the original motivation for blind cputs was for batched kv insert workloads without indexes). 
</blockquote></details>

okay, took a quick pass at switching to flag thus combining with blind.

**Review by andy-kimball — COMMENTED** [review]
See https://github.com/cockroachdb/cockroach/pull/35081, which should fix the test flake you encountered. Rebasing to get that fix should solve your CI problems.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35157#-:-LZN5xID0kFZfHh4_ncO:b-ww0y0s)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @jordanlewis, @knz, and @lucy-zhang)

**Review by bdarnell — APPROVED** [review]
> Reviewed 6 of 10 files at r4, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35157)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @dt, @jordanlewis, @knz, and @lucy-zhang)

___
*[pkg/storage/engine/bench_test.go, line 369 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35157#-LZXmBWj9CPnH88eZh7p:-LZXmBWj9CPnH88eZh7q:b4t0h65) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2ff09a17a87a27389af56cd6ebee8387b51b047/pkg/storage/engine/bench_test.go#L369)):*
> ```Go
> 	b.ResetTimer()
> 
> 	const mustExist = false
> ```

This constant is confusing. It looks like it's saying `!mustExist` when it actually means "this value for the allowNotExist argument means the value must exist". As a local name it looks like the `for mustExist := range []bool{false, true}` pattern. I think this is an indication that we need a typed constant instead of bools, and then you can refer to the (global but more verbose) constant value here.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35157)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @jordanlewis, @knz, and @lucy-zhang)

___
*[pkg/storage/engine/bench_test.go, line 369 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35157#-LZXmBWj9CPnH88eZh7p:-LZaIVsE31ODgsgPLyhl:b-c26pl2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2ff09a17a87a27389af56cd6ebee8387b51b047/pkg/storage/engine/bench_test.go#L369)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This constant is confusing. It looks like it's saying `!mustExist` when it actually means "this value for the allowNotExist argument means the value must exist". As a local name it looks like the `for mustExist := range []bool{false, true}` pattern. I think this is an indication that we need a typed constant instead of bools, and then you can refer to the (global but more verbose) constant value here. 
</blockquote></details>

Yeah, can see that. I added better named global consts and switched all these callers to use them (I didn't make them typed though).

**Comment by dt** [comment]
I went ahead and did the typed consts suggested.

bors r=bdarnell r=knz

**Pull request merged**
