### PR TITLE
sql: parse and display NOT VALID constraint label

### PR DESCRIPTION
**Pull request by mgartner**
#### sql: add NOT VALID label to SHOW CREATE output for unvalidated constraints

This commit appends "NOT VALID" to unvalidated constraints in the output
of `SHOW CREATE`, `SHOW CONSTRAINTS`, and pg_catalog builtin functions.
This makes it possible for a user to determine which constraints have
been validated or not. It also better matches Postgres behavior:

    pg=# CREATE TABLE t (a INT, b INT);
    CREATE TABLE

    pg=# ALTER TABLE t ADD CONSTRAINT check_a CHECK (a IN (1, 2, 3));
    ALTER TABLE

    pg=# ALTER TABLE t ADD CONSTRAINT check_b CHECK (b IN (4, 5, 6)) NOT VALID;
    ALTER TABLE

    pg=# \d t
                     Table "public.t"
     Column |  Type   | Collation | Nullable | Default
    --------+---------+-----------+----------+---------
     a      | integer |           |          |
     b      | integer |           |          |
    Check constraints:
        "check_a" CHECK (a = ANY (ARRAY[1, 2, 3]))
        "check_b" CHECK (b = ANY (ARRAY[4, 5, 6])) NOT VALID

Release note (sql change): Constraints that have not been validated are
now marked "NOT VALID" in the output of `SHOW CREATE` and `SHOW
CONSTRAINTS`.

#### sql: parse NOT VALID in table constraints

This commit allows the `NOT VALID` option IN `CREATE TABLE` table
constraints. For example:

    CREATE TABLE (a INT, CHECK (a > 0) NOT VALID)

This option is a no-op; the constraint created does not skip validation.
In addition, the `NOT VALID` options is not allowed for `PRIMARY KEY` or
`UNIQUE` constraints. This behavior matches Postgres's behavior.

Release note (sql change): The NOT VALID option can now be provided for
CHECK and FOREIGN KEY constraints listed as table constraints in CREATE
TABLE statements. This option has no affect on the constraint created.
It will not skip validation.

#### cli: add dump test for check constraints

This commit adds a test to define the behavior of dumping a table with
check constraints. The current behavior may not be desirable for
unvalidated check constraints because rows that were in violation of an
unvalidated check constraint will fail to be inserted when the dump SQL
is run. I've not attempted to change the logic for now, but rather to
make the current behavior explicit.

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
If we want this to go out in 20.2, I'm happy to add a Release Justification.

**Comment by rohany** [comment]
Looks good to me, we should include it in 20.2. Just to double check, is the `NOT VALID` valid syntax to include in a create table statement?

**Comment by lucy-zhang** [comment]
> is the `NOT VALID` valid syntax to include in a create table statement?

Unfortunately not in cockroach. I don't think we should make this change right now, for that reason.

If we wanted to support `NOT VALID` in `CREATE TABLE` that would be another thing. But I don't know if we'd want to do that either. Aside from `CREATE TABLE AS`, it's not clear why you'd want to specify a constraint as `NOT VALID` in a new table; all subsequent writes will be subject to the constraint, so there aren't many meaningful differences in behavior compared to a normal validated constraint.

**Comment by rohany** [comment]
I see. If it's not valid syntax, we can't include it in show create unfortunately. so we might have to move this to the backburner.

**Comment by lucy-zhang** [comment]
Hmmmmm, interesting: In Postgres, `NOT VALID` in a `CREATE TABLE` statement seems to do nothing. The constraint is added normally.

```
lucy=# create table t (a int, check (a > 0) not valid);
CREATE TABLE
lucy=# \d t
                 Table "public.t"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 a      | integer |           |          |
Check constraints:
    "t_a_check" CHECK (a > 0)
```

So I think I'm fine with this change as long as we also add the `NOT VALID` syntax to `CREATE TABLE`.

**Comment by mgartner** [comment]
Makes sense to me. I'm working on supporting `NOT VALID` in `CREATE TABLE`, but it's requiring a lot of tedious tinkering with the yacc file. I'll keep at it, but I'm not confident we'll consider it a low-risk change when it's all said and done. 🤷‍♂️

**Comment by mgartner** [comment]
@lucy-zhang this is ready for another look. I've added support for including `NOT VALID` in a table constraint.

**Review by thoszhang — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53485)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/show_create_clauses.go, line 428 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53485#-MKMhi187hXF3P0UjQeZ:-MKMhi197WAXMWFRDzsL:bsw7f17) ([raw file](https://github.com/cockroachdb/cockroach/blob/55f4293f0cbe40b11f61cb17f5c741151279064d/pkg/sql/show_create_clauses.go#L428)):*
> ```Go
> 		f.WriteString(")")
> 		if e.Validity != descpb.ConstraintValidity_Validated {
> 			f.WriteString(" NOT VALID")
> ```

We also have to do this for foreign keys, right? This is just for check constraints.

**Comment by lucy-zhang** [comment]
Adding @arulajmani as someone on SQL Experience to also take a look. Feel free to reassign to someone else as appropriate.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53485)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @lucy-zhang)

___
*[pkg/sql/show_create_clauses.go, line 428 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53485#-MKMhi187hXF3P0UjQeZ:-MK_jhwT1ivzBdVv3uAm:b-o7vuhc) ([raw file](https://github.com/cockroachdb/cockroach/blob/55f4293f0cbe40b11f61cb17f5c741151279064d/pkg/sql/show_create_clauses.go#L428)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

We also have to do this for foreign keys, right? This is just for check constraints.
</blockquote></details>

Good catch! Done.

**Review by thoszhang — COMMENTED** [review]
Changes LGTM. This doesn't affect `dump` because we add constraints after writes, right?

> Reviewed 11 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53485#-:-MKb31mj4TbOFNpWrIDA:b-31pas1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @arulajmani, and @lucy-zhang)

**Comment by mgartner** [comment]
It did affect some of the import tests. Is that what you mean?

**Review by thoszhang — COMMENTED** [review]
I think those are `PGDUMP` tests. I'm thinking of `cockroach dump` (https://www.cockroachlabs.com/docs/v20.1/cockroach-dump.html) which also gets its `CREATE` statements from `crdb_internal.create_statements`,  but it uses the special columns which are implemented with some special flags in the statement generation code (for example, to omit constraints). I looked at the tests in dump_test.go, and we do omit foreign keys in the `CREATE` statement for `dump` (so that we can handle cyclic references on writes), so we should be fine there. But what happens to check constraints? I just want to make sure we don't do anything unintended.

> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53485#-:-MKb7B5G-AUfEIB--Byh:b35zsnh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @arulajmani)

**Comment by lucy-zhang** [comment]
FWIW I also filed https://github.com/cockroachdb/cockroach/issues/56003, which is at most only slightly related, but in general I'm not entirely sure how `dump` is supposed to work with constraints.

**Comment by mgartner** [comment]
Re: #56003: I'm confused why I had to change this: https://github.com/cockroachdb/cockroach/pull/53485/files#diff-2e4e2ee1646d89c121c9ee6bd5d3791960e1698200d727f446b7f4903566a33aR5181. The constraint should be valid after the import.

**Comment by lucy-zhang** [comment]
> The constraint should be valid after the import.

I don't think it should be (and I assumed from looking at the diff that the constraint would have ended up unvalidated even prior to this change). Maybe @adityamaru can confirm.

**Comment by lucy-zhang** [comment]
Also, just to clarify, `pg_dump` is unrelated to `cockroach dump`.

**Comment by mgartner** [comment]
> I don't think it should be (and I assumed from looking at the diff that the constraint would have ended up unvalidated even prior to this change).

Why does the explicit `ALTER TABLE a VALIDATE CONSTRAINT fk_i_ref_t;` in `pkg/ccl/importccl/testdata/cockroachdump/dump.sql` not validate the constraint?

**Comment by lucy-zhang** [comment]
I think that's a test for `cockroach dump` (which generates SQL and is unrelated to `IMPORT`) and the tests that you had to update are for `pg_dump` (which is a non-SQL file type that `IMPORT` supports).

FWIW, I just learned that `cockroach dump` is being deprecated (not sure when) so maybe the `cockroach dump` considerations don't really matter. But I think you should be fine with the `pg_dump` tests.

**Comment by mgartner** [comment]
@lucy-zhang thanks for the added context. I've added a test that explicitly shows the behavior of `cockroach dump` for check constraints (both validated and unvalidated). The behavior of `cockroach dump` for unvalidated check constraints hasn't really changed in this PR because `NOT VALID` is ignored.

That being said, the behavior may not make the most sense because some of the INSERTs in the dump could fail. A row that was in the table but in violation of an `NOT VALID` check constraint would fail to be inserted to a table with the same check constraint (whether that new check constraint is valid or not). I think changing this behavior is outside the scope of this PR, and if `cockroach dump` is being deprecated, may not be worth our time.

**Review by arulajmani — COMMENTED** [review]
Left one suggestion but otherwise this is :lgtm: 

> Reviewed 2 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53485#-:-MKqjUUd2Jrz-AGJp2gv:be7go2v)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @arulajmani, @lucy-zhang, and @mgartner)

___
*[pkg/cli/testdata/dump/check_constraints, line 29 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/53485#-MKqjJsL9mgA1ckykr5h:-MKqjJsL9mgA1ckykr5i:b4phpa6) ([raw file](https://github.com/cockroachdb/cockroach/blob/db1ab9bc5970acf0d2ea0e425cb9820adb808db2/pkg/cli/testdata/dump/check_constraints#L29)):*
> ```
> 
> INSERT INTO public.t (x, y) VALUES
> 	(1, 1);
> ```

Wouldn't this fail? Am I missing something?
___
*[pkg/sql/logictest/testdata/logic_test/show_create, line 36 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/53485#-MKqgyBM8lTzQRNLyUVQ:-MKqgyBM8lTzQRNLyUVR:b-4rf4bw) ([raw file](https://github.com/cockroachdb/cockroach/blob/db1ab9bc5970acf0d2ea0e425cb9820adb808db2/pkg/sql/logictest/testdata/logic_test/show_create#L36)):*
> ```
> COMMENT ON COLUMN public.c.a IS 'column';
> COMMENT ON INDEX public.c@c_a_b_idx IS 'index'
> ```

Maybe add a test here for NOT VALID used inside a CREATE TABLE as well?

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53485)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @arulajmani, and @lucy-zhang)

___
*[pkg/cli/testdata/dump/check_constraints, line 29 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/53485#-MKqjJsL9mgA1ckykr5h:-MKqmSR183eJDcuiAeM_:bsx2t5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/db1ab9bc5970acf0d2ea0e425cb9820adb808db2/pkg/cli/testdata/dump/check_constraints#L29)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Wouldn't this fail? Am I missing something?
</blockquote></details>

Yes it would. But it would have failed before this commit too, because the `c` constraint would still be in the `CREATE TABLE` statement above, only without the `NOT VALID` (note that the `NOT VALID` in the `CREATE TABLE` is a no-op).

From my previous comment:

```
... I've added a test that explicitly shows the behavior of cockroach dump for check constraints (both validated and unvalidated). The behavior of cockroach dump for unvalidated check constraints hasn't really changed in this PR because NOT VALID is ignored in CREATE TABLE statements.

That being said, the behavior may not make the most sense because some of the INSERTs in the dump could fail. A row that was in the table but in violation of an NOT VALID check constraint would fail to be inserted to a table with the same check constraint (whether that new check constraint is valid or not). I think changing this behavior is outside the scope of this PR, and if cockroach dump is being deprecated, may not be worth our time.
```

Does that make sense? Basically, the `NOT VALID` has been added in this commit, but the result of running the dump SQL generated in this test has not changed.
___
*[pkg/sql/logictest/testdata/logic_test/show_create, line 36 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/53485#-MKqgyBM8lTzQRNLyUVQ:-MKqo5XO0OLxpUK65-_d:b-bn3dsi) ([raw file](https://github.com/cockroachdb/cockroach/blob/db1ab9bc5970acf0d2ea0e425cb9820adb808db2/pkg/sql/logictest/testdata/logic_test/show_create#L36)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Maybe add a test here for NOT VALID used inside a CREATE TABLE as well?
</blockquote></details>

`NOT VALID` in a `CREATE TABLE` is ignored. I think the new tests in `parse_test.go` cover this case well. IMO this wouldn't be the right place to test that `NOT VALID` does not show up in `SHOW CREATE TABLE` when `NOT VALID` was included in a `CREATE TABLE` because it's due to parsing logic, not `SHOW CREATE TABLE` logic. But if you feel strongly, I'm happy to add one.

**Review by arulajmani — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53485)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @arulajmani, @lucy-zhang, and @mgartner)

___
*[pkg/cli/testdata/dump/check_constraints, line 29 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/53485#-MKqjJsL9mgA1ckykr5h:-MKr8WDM1Wiro2u1YR6F:bfjta83) ([raw file](https://github.com/cockroachdb/cockroach/blob/db1ab9bc5970acf0d2ea0e425cb9820adb808db2/pkg/cli/testdata/dump/check_constraints#L29)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Yes it would. But it would have failed before this commit too, because the `c` constraint would still be in the `CREATE TABLE` statement above, only without the `NOT VALID` (note that the `NOT VALID` in the `CREATE TABLE` is a no-op).

From my previous comment:

```
... I've added a test that explicitly shows the behavior of cockroach dump for check constraints (both validated and unvalidated). The behavior of cockroach dump for unvalidated check constraints hasn't really changed in this PR because NOT VALID is ignored in CREATE TABLE statements.

That being said, the behavior may not make the most sense because some of the INSERTs in the dump could fail. A row that was in the table but in violation of an NOT VALID check constraint would fail to be inserted to a table with the same check constraint (whether that new check constraint is valid or not). I think changing this behavior is outside the scope of this PR, and if cockroach dump is being deprecated, may not be worth our time.
```

Does that make sense? Basically, the `NOT VALID` has been added in this commit, but the result of running the dump SQL generated in this test has not changed.
</blockquote></details>

Haha guess I was missing your commit message. 
___
*[pkg/sql/logictest/testdata/logic_test/show_create, line 36 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/53485#-MKqgyBM8lTzQRNLyUVQ:-MKrAH7j9wK8A6qwxW7o:b-4q7b5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/db1ab9bc5970acf0d2ea0e425cb9820adb808db2/pkg/sql/logictest/testdata/logic_test/show_create#L36)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

`NOT VALID` in a `CREATE TABLE` is ignored. I think the new tests in `parse_test.go` cover this case well. IMO this wouldn't be the right place to test that `NOT VALID` does not show up in `SHOW CREATE TABLE` when `NOT VALID` was included in a `CREATE TABLE` because it's due to parsing logic, not `SHOW CREATE TABLE` logic. But if you feel strongly, I'm happy to add one.
</blockquote></details>

Nup, not strongly

**Comment by mgartner** [comment]
Thanks for the feedback everyone!

bors r+

**Pull request merged**
