### PR TITLE
span: Re-initialize iterator when forwarding

### LINKED ISSUE #115411: roachtest: cdc/initial-scan-only failed [NPE in btree-based frontier]
roachtest.cdc/initial-scan-only [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12925674?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12925674?buildTab=artifacts#/cdc/initial-scan-only) on master @ [02e46d54d0b0bf63f43592709d551534edb54be6](https://github.com/cockroachdb/cockroach/commits/02e46d54d0b0bf63f43592709d551534edb54be6):

```
(monitor.go:153).Wait: monitor failure: read tcp 172.17.0.3:51266 -> 34.23.67.255:26257: read: connection reset by peer
test artifacts and logs in: /artifacts/cdc/initial-scan-only/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=16</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_metamorphicBuild=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-12925674/cdc-initial-scan-only/1701429266857/1701429739814)

</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/initial-scan-only.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-34017

### LINKED ISSUE #115483: pkg/ccl/backupccl/backuprand/backuprand_test: TestBackupRestoreRandomDataRoundtrips failed
pkg/ccl/backupccl/backuprand/backuprand_test.TestBackupRestoreRandomDataRoundtrips [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/12942791?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/12942791?buildTab=artifacts#/) on master @ [74ae9a18d82fdc80e5e9b71b3f06b258ae5cb91b](https://github.com/cockroachdb/cockroach/commits/74ae9a18d82fdc80e5e9b71b3f06b258ae5cb91b):

Fatal error:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1edc7bb]

```
Stack: 

```
goroutine 895514 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).recover(0xc1?, {0x79a8420, 0xc00e2db320})
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:230 +0x65
panic({0x58544c0?, 0xb11fbf0?})
	GOROOT/src/runtime/panic.go:914 +0x21f
github.com/cockroachdb/cockroach/pkg/util/span.(*iterator).findNextOverlap(0xc005c5cf58, 0xc0061b9e00?)
	github.com/cockroachdb/cockroach/pkg/util/span/frontierentry_interval_btree.go:1109 +0xdb
github.com/cockroachdb/cockroach/pkg/util/span.(*iterator).FirstOverlap(0xc005c5cf58, 0x2?)
	github.com/cockroachdb/cockroach/pkg/util/span/frontierentry_interval_btree.go:1071 +0xf4
github.com/cockroachdb/cockroach/pkg/util/span.(*btreeFrontier).forward(0xc0055f5f90, {{0xc012c90378, 0x2, 0x8}, {0xc012c90380, 0x2, 0x8}}, {0x179cf0a386531626, 0x0, 0x0})
	github.com/cockroachdb/cockroach/pkg/util/span/frontier.go:467 +0x27b
github.com/cockroachdb/cockroach/pkg/util/span.(*btreeFrontier).Forward(0xc0055f5f90, {{0xc012c90378, 0x2, 0x8}, {0xc012c90380, 0x2, 0x8}}, {0x179cf0a386531626, 0x0, 0x0})
	github.com/cockroachdb/cockroach/pkg/util/span/frontier.go:300 +0x18b
github.com/cockroachdb/cockroach/pkg/ccl/backupccl.checkCoverage({0xc01092e558?, 0x1?}, {0xc0143ed400?, 0xc0025f7009?, 0x1?}, {0xc00f16ae00, 0x1, 0x1?})
	github.com/cockroachdb/cockroach/pkg/ccl/backupccl/backup_span_coverage.go:63 +0x571
github.com/cockroachdb/cockroach/pkg/ccl/backupccl.restore({0x79a8420, 0xc00460f0b0}, {0x7a011e0, 0xc0040020a0}, {0xc00f16ae00, 0x1, 0x1}, {0xc01092e558, 0x1, 0x1}, ...)
	github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_job.go:285 +0x27d
github.com/cockroachdb/cockroach/pkg/ccl/backupccl.restoreWithRetry({0x79a8420, 0xc00460f0b0}, {0x7a011e0, 0xc0040020a0}, {0xc00f16ae00, 0x1, 0x1}, {0xc01092e558, 0x1, 0x1}, ...)
	github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_job.go:172 +0x478
github.com/cockroachdb/cockroach/pkg/ccl/backupccl.(*restoreResumer).doResume(0xc012a92bd0, {0x79a8420, 0xc00460f0b0}, {0x5eace80?, 0xc0040020a0})
	github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_job.go:1801 +0x195c
github.com/cockroachdb/cockroach/pkg/ccl/backupccl.(*restoreResumer).Resume(0xc012a92bd0, {0x79a8420, 0xc00460f0b0}, {0x5eace80?, 0xc0040020a0?})
	github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_job.go:1586 +0x4a
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func2(0xc01481a340?, 0x0?, 0xc005c5f838, {0x7986540?, 0xc012a92bd0?}, {0x79a8420?, 0xc00460f0b0?}, {0x5eace80?, 0xc0040020a0?})
	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1565 +0xc2
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine(0xc000e41400, {0x79a8420, 0xc00e2db710}, {0x5eace80, 0xc0040020a0}, {0x7986540, 0xc012a92bd0}, 0xc01481a340, {0x62807e2, 0x7}, ...)
	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1566 +0xa2d
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob(0xc000e41400, {0x79a8420, 0xc00e2db710}, {0x7986540, 0xc012a92bd0}, 0xc01481a340, {0x62807e2, 0x7}, {0xc012164090, 0x16})
	github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:447 +0x552
github.com/cockroachdb/cockroach/pkg/jobs.(*StartableJob).Start.func2({0xc0056a3800?, 0x0?})
	github.com/cockroachdb/cockroach/pkg/jobs/jobs.go:905 +0xe7
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:484 +0x13a
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx in goroutine 887666
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:475 +0x415
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   TestBackupRestoreRandomDataRoundtrips
    test_log_scope.go:170: test logs captured to: /artifacts/tmp/_tmp/4de3d9455ce580fd52f59602b3ef6e62/logTestBackupRestoreRandomDataRoundtrips1860539140
    test_log_scope.go:81: use -show-logs to present logs inline
*
* ERROR: a panic has occurred!
* runtime error: invalid memory address or nil pointer dereference
* (1) attached stack trace
*   -- stack trace:
*   | runtime.gopanic
*   | 	GOROOT/src/runtime/panic.go:914
*   | runtime.panicmem
*   | 	GOROOT/src/runtime/panic.go:261
*   | runtime.sigpanic
*   | 	GOROOT/src/runtime/signal_unix.go:861
*   | github.com/cockroachdb/cockroach/pkg/util/span.(*iterator).findNextOverlap
*   | 	github.com/cockroachdb/cockroach/pkg/util/span/frontierentry_interval_btree.go:1109
*   | github.com/cockroachdb/cockroach/pkg/util/span.(*iterator).FirstOverlap
*   | 	github.com/cockroachdb/cockroach/pkg/util/span/frontierentry_interval_btree.go:1071
*   | github.com/cockroachdb/cockroach/pkg/util/span.(*btreeFrontier).forward
*   | 	github.com/cockroachdb/cockroach/pkg/util/span/frontier.go:467
*   | github.com/cockroachdb/cockroach/pkg/util/span.(*btreeFrontier).Forward
*   | 	github.com/cockroachdb/cockroach/pkg/util/span/frontier.go:300
*   | github.com/cockroachdb/cockroach/pkg/ccl/backupccl.checkCoverage
*   | 	github.com/cockroachdb/cockroach/pkg/ccl/backupccl/backup_span_coverage.go:63
*   | github.com/cockroachdb/cockroach/pkg/ccl/backupccl.restore
*   | 	github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_job.go:285
*   | github.com/cockroachdb/cockroach/pkg/ccl/backupccl.restoreWithRetry
*   | 	github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_job.go:172
*   | github.com/cockroachdb/cockroach/pkg/ccl/backupccl.(*restoreResumer).doResume
*   | 	github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_job.go:1801
*   | github.com/cockroachdb/cockroach/pkg/ccl/backupccl.(*restoreResumer).Resume
*   | 	github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_job.go:1586
*   | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func2
*   | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1565
*   | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine
*   | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1566
*   | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob
*   | 	github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:447
*   | github.com/cockroachdb/cockroach/pkg/jobs.(*StartableJob).Start.func2
*   | 	github.com/cockroachdb/cockroach/pkg/jobs/jobs.go:905
*   | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
*   | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:484
*   | runtime.goexit
*   | 	src/runtime/asm_amd64.s:1650
* Wraps: (2) runtime error: invalid memory address or nil pointer dereference
* Error types: (1) *withstack.withStack (2) runtime.errorString
*
```
</p>
</details>
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
, <code>stress=true</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestBackupRestoreRandomDataRoundtrips.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #115487: roachtest: c2c/shutdown/src/worker failed
roachtest.c2c/shutdown/src/worker [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12942600?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12942600?buildTab=artifacts#/c2c/shutdown/src/worker) on master @ [74ae9a18d82fdc80e5e9b71b3f06b258ae5cb91b](https://github.com/cockroachdb/cockroach/commits/74ae9a18d82fdc80e5e9b71b3f06b258ae5cb91b):

```
(cluster_to_cluster.go:1612).func1: shutdown execution failed: monitor failure: getting the job status: read tcp 172.17.0.3:41576 -> 34.148.187.204:26257: read: connection reset by peer
test artifacts and logs in: /artifacts/c2c/shutdown/src/worker/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=8</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_metamorphicBuild=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-12942600/c2c-shutdown-src-worker/1701515209222/1701515812118)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*c2c/shutdown/src/worker.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-34054

### LINKED ISSUE #115488: roachtest: c2c/initialscan/kv0 failed
roachtest.c2c/initialscan/kv0 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12942600?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12942600?buildTab=artifacts#/c2c/initialscan/kv0) on master @ [74ae9a18d82fdc80e5e9b71b3f06b258ae5cb91b](https://github.com/cockroachdb/cockroach/commits/74ae9a18d82fdc80e5e9b71b3f06b258ae5cb91b):

```
(monitor.go:153).Wait: monitor failure: context canceled
(monitor.go:153).Wait: monitor failure: monitor user task failed: t.Fatal() was called
test artifacts and logs in: /artifacts/c2c/initialscan/kv0/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=8</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=false</code>
, <code>ROACHTEST_metamorphicBuild=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-12942600/c2c-initialscan-kv0/1701514312129/1701516002742)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*c2c/initialscan/kv0.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-34055

### LINKED ISSUE #115490: roachtest: c2c/tpcc/warehouses=500/duration=10/cutover=0 failed
roachtest.c2c/tpcc/warehouses=500/duration=10/cutover=0 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12942600?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12942600?buildTab=artifacts#/c2c/tpcc/warehouses=500/duration=10/cutover=0) on master @ [74ae9a18d82fdc80e5e9b71b3f06b258ae5cb91b](https://github.com/cockroachdb/cockroach/commits/74ae9a18d82fdc80e5e9b71b3f06b258ae5cb91b):

```
(assertions.go:333).Fail: 
	Error Trace:	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cluster_to_cluster.go:750
	            				github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cluster_to_cluster.go:971
	            				github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cluster_to_cluster.go:1265
	            				main/pkg/cmd/roachtest/monitor.go:119
	            				golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75
	            				src/runtime/asm_amd64.s:1650
	Error:      	Received unexpected error:
	            	context canceled
	Test:       	c2c/tpcc/warehouses=500/duration=10/cutover=0
(require.go:1360).NoError: FailNow called
(monitor.go:153).Wait: monitor failure: monitor user task failed: t.Fatal() was called
test artifacts and logs in: /artifacts/c2c/tpcc/warehouses=500/duration=10/cutover=0/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=8</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=false</code>
, <code>ROACHTEST_metamorphicBuild=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-12942600/c2c-tpcc-warehouses-500-duration-10-cutover-0/1701515610245/1701517020587)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*c2c/tpcc/warehouses=500/duration=10/cutover=0.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-34057

### LINKED ISSUE #115497: roachtest: c2c/weekly/kv50 failed
roachtest.c2c/weekly/kv50 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyAwsBazel/12942670?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyAwsBazel/12942670?buildTab=artifacts#/c2c/weekly/kv50) on master @ [74ae9a18d82fdc80e5e9b71b3f06b258ae5cb91b](https://github.com/cockroachdb/cockroach/commits/74ae9a18d82fdc80e5e9b71b3f06b258ae5cb91b):

```
(soon.go:64).SucceedsWithin: condition failed to evaluate within 6h0m0s: dial tcp 3.12.120.41:26257: connect: connection refused
(monitor.go:153).Wait: monitor failure: monitor user task failed: t.Fatal() was called
test artifacts and logs in: /artifacts/c2c/weekly/kv50/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=aws</code>
, <code>ROACHTEST_cpu=8</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=false</code>
, <code>ROACHTEST_metamorphicBuild=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for aws clusters_</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*c2c/weekly/kv50.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #115512: ccl/streamingccl/streamingest: TestStreamingAutoReplan failed
ccl/streamingccl/streamingest.TestStreamingAutoReplan [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/12953640?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/12953640?buildTab=artifacts#/) on master @ [74ae9a18d82fdc80e5e9b71b3f06b258ae5cb91b](https://github.com/cockroachdb/cockroach/commits/74ae9a18d82fdc80e5e9b71b3f06b258ae5cb91b):

Fatal error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x219a85b]

```
Stack: 

```
goroutine 169810065 [running]:
github.com/cockroachdb/cockroach/pkg/util/span.(*iterator).findNextOverlap(0xc00eac5938, 0xc0176fe980?)
	github.com/cockroachdb/cockroach/pkg/util/span/frontierentry_interval_btree.go:1109 +0xdb
github.com/cockroachdb/cockroach/pkg/util/span.(*iterator).FirstOverlap(0xc00eac5938, 0x7?)
	github.com/cockroachdb/cockroach/pkg/util/span/frontierentry_interval_btree.go:1071 +0xf4
github.com/cockroachdb/cockroach/pkg/util/span.(*btreeFrontier).forward(0xc01487c690, {{0xc00e6de390, 0x7, 0x8}, {0xc00e6de398, 0x7, 0x8}}, {0x179d472582907f5c, 0x0, 0x0})
	github.com/cockroachdb/cockroach/pkg/util/span/frontier.go:467 +0x27b
github.com/cockroachdb/cockroach/pkg/util/span.(*btreeFrontier).Forward(0xc01487c690, {{0xc00e6de390, 0x7, 0x8}, {0xc00e6de398, 0x7, 0x8}}, {0x179d472582907f5c, 0x0, 0x0})
	github.com/cockroachdb/cockroach/pkg/util/span/frontier.go:300 +0x18b
github.com/cockroachdb/cockroach/pkg/ccl/streamingccl/streamingest.(*streamIngestionProcessor).bufferCheckpoint(0xc012cb3400, {{0x7a32490?, 0xc017f3e210?}, {0x6387ba4?, 0xc00eac5e92?}})
	github.com/cockroachdb/cockroach/pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go:871 +0x303
github.com/cockroachdb/cockroach/pkg/ccl/streamingccl/streamingest.(*streamIngestionProcessor).handleEvent(0xc012cb3400, {{0x7a32490?, 0xc017f3e210?}, {0x6387ba4?, 0x96a285?}})
	github.com/cockroachdb/cockroach/pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go:710 +0x2bc
github.com/cockroachdb/cockroach/pkg/ccl/streamingccl/streamingest.(*streamIngestionProcessor).consumeEvents(0xc012cb3400, {0x179d4711e36b69c9?, 0xc019195860?})
	github.com/cockroachdb/cockroach/pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go:655 +0xef
github.com/cockroachdb/cockroach/pkg/ccl/streamingccl/streamingest.(*streamIngestionProcessor).Start.func3({0x7a00da0?, 0xc01ee94d70?})
	github.com/cockroachdb/cockroach/pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go:464 +0x72
github.com/cockroachdb/cockroach/pkg/ccl/streamingccl/streamingest.(*streamIngestionProcessor).Start.Group.GoCtx.func9()
	github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:168 +0x22
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 169804549
	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:72 +0x96
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   TestStreamingAutoReplan
    test_log_scope.go:170: test logs captured to: /artifacts/tmp/_tmp/90c1b75d835f45b8488807abb5b1092d/logTestStreamingAutoReplan1059297502
    test_log_scope.go:81: use -show-logs to present logs inline

pkg/ccl/streamingccl/replicationtestutils/testutils.go:150: ((*TenantStreamingClusters).init)
	NOTICE: .WaitForTenantCapabilities() called via implicit interface TenantControlInterface;
HINT: consider using .TenantController().WaitForTenantCapabilities() instead.
```
</p>
</details>
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
, <code>stress=true</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestStreamingAutoReplan.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-34073

### PR DESCRIPTION
**Pull request by miretskiy**
Re-initialize iterator when forwarding span
frontier timestamp.  The underlying btree may be
mutated (by merge operation) invalidating previously
constructed iterator.

Btree implementation is also hardened against mis-use
when mutating span frontier while iterating.

Fixes #115411
Fixes #115528
Fixes #115512
Fixes #115490
Fixes #115488
Fixes #115487
Fixes #115483

Release notes: None

### CODE REVIEW

**Review by stevendanna — COMMENTED** [review]
I left some questions but I think I'm going to need to read the implementation more completely to understand this bug fix.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115509)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

___
*[`pkg/util/span/frontier.go` line 822 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115509#gh-1413701687:-Nkp49Sz1bfZGlVcSlB8:b-60lqm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/bce833dd46da86ae944c5c4547bb75b2381b0a99/pkg/util/span/frontier.go#L822)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I wonder if we could give this a name that makes it more clear it will mutate the given frontier.
</blockquote></details>

Got better name; and simplified this function and the call sites.
This function, now called spanDifference simply computes a set difference
between the span and the frontier, and returns that diff.
___
*[`pkg/util/span/llrb_frontier.go` line 135 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115509#gh-1413701239:-Nkp0cul0geXvkdHZYV9:b-dh5k9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/bce833dd46da86ae944c5c4547bb75b2381b0a99/pkg/util/span/llrb_frontier.go#L135)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Why do we do this twice?  If required, it could definitely use a comment.

If unintentional, perhaps `collectOverlaps` could construct the SpanGroup and return it rather than taking it as an out param?
</blockquote></details>

Total copy pasta.

**Review by stevendanna — APPROVED** [review]
Thanks for hunting this down!

**Pull request merged**
