### PR TITLE
pgrepl: implement the parser for the PostgreSQL replication protocol

### PR DESCRIPTION
**Pull request by otan**
This commit implements parsing the [PG replication protocol syntax](https://www.postgresql.org/docs/current/protocol-replication.html) which is derived from the `.y` file from PG itself. We had to invent some new lexing protocols as the lexing mechanism is different to standard plpgsql/pgsql.

This is in preparation for supporting pglogical within CRDB.

Epic: https://cockroachlabs.atlassian.net/browse/CRDB-26486
Release note: None

### CODE REVIEW

**Review by ZhouXing19 — CHANGES_REQUESTED** [review]
Nice work! Mostly nit comments and had 2 questions

> Reviewed 2 of 14 files at r3, 38 of 38 files at r5, 38 of 38 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104938#-:-NY65pz12TOn_zh20OOP:b-cnczxe)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan, @renatolabs, and @srosenberg)

___
*[`pkg/sql/pgrepl/pgreplparser/lexer.go` line 84 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/104938#-NY614sM4t3FXbw2T5WF:-NY614sM4t3FXbw2T5WG:b-ofprej) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd28b578b8ea21d31d2eb65a91f30d1e3c502edc/pkg/sql/pgrepl/pgreplparser/lexer.go#L84)):*
> ```Go
> 	case ch == doubleQuote:
> 		l.scanUntilEndQuote(lval, doubleQuote, lexbase.NormalizeString, IDENT)
> 	case unicode.IsDigit(ch):
> ```

nit: This case overlaps a lot with the `isID(ch, true)` case for the LSN check. I wonder if they can share that part of code.
___
*[`pkg/sql/pgrepl/pgreplparser/lexer.go` line 91 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/104938#-NY5zp2g0ksDn0-h5uLl:-NY5zp2g0ksDn0-h5uLm:b-y945lz) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd28b578b8ea21d31d2eb65a91f30d1e3c502edc/pkg/sql/pgrepl/pgreplparser/lexer.go#L91)):*
> ```Go
> 			switch {
> 			case unicode.IsDigit(nextCh):
> 			case isHexDigit(nextCh) || nextCh == '/':
> ```

if `unicode.IsDigit(nextCh) == true`, is `isHexDigit(nextCh)` always `true`? If so, shouldn't we remove the `case unicode.IsDigit(nextCh)`? Otherwise, these digits will never be parsed as an LSN.
___
*[`pkg/sql/pgrepl/pgreplparser/lexer.go` line 150 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/104938#-NY5xacbCIwhsatCXnic:-NY5xacbCIwhsatCXnid:b30rgtt) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd28b578b8ea21d31d2eb65a91f30d1e3c502edc/pkg/sql/pgrepl/pgreplparser/lexer.go#L150)):*
> ```Go
> }
> 
> func isID(ch rune, firstCh bool) bool {
> ```

I had some trouble understanding what `ID` means here. Could you add some comments to this func, and maybe have 200 and 377 as const var? 
___
*[`pkg/sql/pgrepl/pgreplparser/lexer.go` line 161 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/104938#-NY64RHE6HdeaWbxRIGH:-NY64RHE6HdeaWbxRIGI:b-pbt360) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd28b578b8ea21d31d2eb65a91f30d1e3c502edc/pkg/sql/pgrepl/pgreplparser/lexer.go#L161)):*
> ```Go
> }
> 
> func (l *lexer) checkLSN(lval *pgreplSymType, startPos int) bool {
> ```

nit: it would be helpful to have comments explaining the expected format of LSN -- two hexadecimal numbers of up to 8 digits each, separated by a slash.
___
*[`pkg/sql/pgrepl/pgreplparser/pgrepl.y` line 1 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/104938#-NY5l2ftDiN1nOYnKQ63:-NY5l2ftDiN1nOYnKQ64:b-qe1ayg) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd28b578b8ea21d31d2eb65a91f30d1e3c502edc/pkg/sql/pgrepl/pgreplparser/pgrepl.y#L1)):*
> ```Yacc
> %{
> ```

nit: for the whole yacc file formatting, tabs -> spaces
___
*[`pkg/sql/pgrepl/pgreplparser/pgrepl.y` line 218 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/104938#-NY5rFyP7SafX8HZ7p1L:-NY5rFyP7SafX8HZ7p1M:b1ewyas) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd28b578b8ea21d31d2eb65a91f30d1e3c502edc/pkg/sql/pgrepl/pgreplparser/pgrepl.y#L218)):*
> ```Yacc
> /*
>  * SHOW setting
>  * NOTE(otan): we omit K_SHOW as this should be handled by the existing protocol.
> ```

Could you say more about this? Does it mean replication config params can only be queried via the pg protocol? Why? 
___
*[`pkg/sql/pgrepl/pgreplparser/pgrepl.y` line 376 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/104938#-NY62mZ-0UCRPLBGlYcT:-NY62mZ-0UCRPLBGlYcU:b7vnm3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd28b578b8ea21d31d2eb65a91f30d1e3c502edc/pkg/sql/pgrepl/pgreplparser/pgrepl.y#L376)):*
> ```Yacc
> 			K_TIMELINE_HISTORY UCONST
> 				{
> 					$$.val = &pgrepltree.TimelineHistory{Timeline: $2.numVal()}
> ```

nit: pg has [a check for positive argument](https://github.com/postgres/postgres/blob/4327f6c7480fea9348ea6825a9d38a71b2ef8785/src/backend/replication/repl_gram.y#L298-L301) here. Do we want to have one as well?
___
*[`pkg/sql/pgrepl/pgreplparser/pgrepl.y` line 400 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/104938#-NY634aAA9ToP-OtbCQL:-NY634aAA9ToP-OtbCQM:b-i36xtx) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd28b578b8ea21d31d2eb65a91f30d1e3c502edc/pkg/sql/pgrepl/pgreplparser/pgrepl.y#L400)):*
> ```Yacc
> 			K_TIMELINE UCONST
> 				{
> 					$$.val = $2.numVal();
> ```

nit: ditto, positive arg check
___
*[`pkg/sql/pgrepl/pgreplparser/testdata/lexer/lsn.ddt` line 39 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/104938#-NY64uGn6lxHbSjPaWDt:-NY64uGn6lxHbSjPaWDu:b868xsb) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd28b578b8ea21d31d2eb65a91f30d1e3c502edc/pkg/sql/pgrepl/pgreplparser/testdata/lexer/lsn.ddt#L39)):*
> ```
> bA101001010101010/f
> ----
> ERROR: at or near "bA101001010101010/f": syntax error: error decoding LSN: strconv.ParseUint: parsing "bA101001010101010": value out of range
> ```

nit: maybe add a case that ends with '/'?
___
*[`pkg/sql/pgrepl/pgreplparser/testdata/parser/start_replication.ddt` line 57 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/104938#-NY65N_46A8DYm6NqcmV:-NY65N_46A8DYm6NqcmW:bcnjofy) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd28b578b8ea21d31d2eb65a91f30d1e3c502edc/pkg/sql/pgrepl/pgreplparser/testdata/parser/start_replication.ddt#L57)):*
> ```
> ----
> START_REPLICATION SLOT slot_1 LOGICAL A0010/1011 (opt 'opt', "xXx" 'a') -- normalized!
> START_REPLICATION SLOT slot_1 LOGICAL A0010/1011 (opt '_', "xXx" '_') -- literals removed
> ```

nit: maybe adding a case with an invalid LSN?

**Review by ZhouXing19 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104938)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan, @renatolabs, and @srosenberg)

___
*[`pkg/sql/pgrepl/pgreplparser/pgrepl.y` line 220 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/104938#-NYGhxQv7XjvSa6MuuHi:-NYGhxQv7XjvSa6MuuHj:b8lyc2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/628d3360bf3cb61dd65a826ae6988f53fc9d0706/pkg/sql/pgrepl/pgreplparser/pgrepl.y#L220)):*
> ```Yacc
> /*
>  * SHOW setting
>  * NOTE(otan): we omit K_SHOW as the fallback from being being parsed by
> ```

nit: remove one of the "being"
___
*[`pkg/sql/pgrepl/pgreplparser/testdata/lexer/lsn.ddt` line 37 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/104938#-NYGiRDw4xpizp1OcXcW:-NYGiRDw4xpizp1OcXcX:bnympt5) ([raw file](https://github.com/cockroachdb/cockroach/blob/628d3360bf3cb61dd65a826ae6988f53fc9d0706/pkg/sql/pgrepl/pgreplparser/testdata/lexer/lsn.ddt#L37)):*
> ```
> # ends with a /
> lex
> 00ff/
> ```

This doesn't seem to be supported by pg: 
```
postgres=# SELECT '00ff/'::pg_LSN;
ERROR:  22P02: invalid input syntax for type pg_lsn: "00ff/"
LINE 1: SELECT '00ff/'::pg_LSN;
               ^
LOCATION:  pg_lsn_in, pg_lsn.c:74

postgres=# SELECT '00ff/00'::pg_LSN;
 pg_lsn 
--------
 FF/0
(1 row)
```

**Review by ZhouXing19 — APPROVED** [review]
:lgtm_strong: :

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104938#-:-NYGmE8g3LyMWoqxplIo:b-yncq55)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan, @renatolabs, and @srosenberg)

**Comment by otan** [comment]
bors r=ZhouXing19

**Pull request merged**
