### PR TITLE
roachtest: add test to run db-console cypress tests

### PR DESCRIPTION
**Pull request by kyle-a-wong**
Adds two roachtests that run db-console cypress tests:
  - db-console/cypress
  - db-console/mixed-version-cypress

These tests build a docker image, using cypress/included as the base then copying the necessary db-console e2e test files needed to run the cypress tests.

Epic: None
Resolves: CC-30147
Release note: None

### CODE REVIEW

**Review by angles-n-daemons — APPROVED** [review]
Since this is a large net positive for almost no risk, consider this pr approved. I've left a number of comments, but they're all suggestions.

Separately, I tested this on my own to verify the roachtest itself works.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133855#-:-OAwvJyg5cSN44IKhepO:b-8n6nka)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @dhartunian, @herkolategan, @kyle-a-wong, and @xinhaoz)

___
*[`pkg/cmd/roachtest/tests/db_console.go` line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133855#-OAx3Kh30oHy5dmlzI1a:-OAx3Kh30oHy5dmlzI1b:b-lfxfrj) ([raw file](https://github.com/cockroachdb/cockroach/blob/df1e9ce28602fe8a951c53e5fcb0cccde97047c9/pkg/cmd/roachtest/tests/db_console.go#L6)):*
> ```Go
> // included in the /LICENSE file.
> 
> package tests
> ```

If you could paint over this file one more time, and comment each of the functions in more detail it would really improve the comprehensibility of what's going on.
___
*[`pkg/cmd/roachtest/tests/db_console.go` line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133855#-OAx0YUw-zLKWpAqJ6-J:-OAx0YUxDXua8hDg4WPf:b-qcqwka) ([raw file](https://github.com/cockroachdb/cockroach/blob/df1e9ce28602fe8a951c53e5fcb0cccde97047c9/pkg/cmd/roachtest/tests/db_console.go#L162)):*
> ```Go
> 
> // buildDockerImage builds the Docker image which will run db-console cypress tests
> func (d *dbConsoleCypressTest) buildDockerImage(ctx context.Context) {
> ```

Wherever possible, build should be decoupled from run. The docker run command can be here, but docker build should be somewhere in our build pipelines.

I'm not super familiar with our build pipelines, but it seems like there's a lot of stuff related to building and publishing images in this directory: `build/teamcity/internal/cockroach/build/`.

I believe that doing so can reduce the complexity of running a test.
___
*[`pkg/cmd/roachtest/tests/db_console.go` line 200 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133855#-OAwz98z2A8LDZdTT-pa:-OAwz98z2A8LDZdTT-pb:b-do3m5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/df1e9ce28602fe8a951c53e5fcb0cccde97047c9/pkg/cmd/roachtest/tests/db_console.go#L200)):*
> ```Go
> 			d.t.Fatal(mkDirErr)
> 		}
> 		require.NoError(d.t, rtCluster.RunE(ctx, option.WithNodes(workloadNode), "mkdir", "-p", d.artifactPath))
> ```

If the artifacts directory is created on the workload node after the tests are run, will it be empty?
___
*[`pkg/cmd/roachtest/tests/db_console.go` line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133855#-OAwyqsv0m6N_Amq8s4V:-OAwyqsv0m6N_Amq8s4W:bth6hax) ([raw file](https://github.com/cockroachdb/cockroach/blob/df1e9ce28602fe8a951c53e5fcb0cccde97047c9/pkg/cmd/roachtest/tests/db_console.go#L202)):*
> ```Go
> 		require.NoError(d.t, rtCluster.RunE(ctx, option.WithNodes(workloadNode), "mkdir", "-p", d.artifactPath))
> 		require.NoError(d.t, rtCluster.Get(ctx, d.t.L(), d.artifactPath, testArtifactsDir, workloadNode))
> 		require.NoError(d.t, err)
> ```

where is this error created?
___
*[`pkg/cmd/roachtest/tests/db-console/Dockerfile` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133855#-OAx0Hq32nLR-S8NxOSx:-OAx0Hq32nLR-S8NxOSy:bypvcm6) ([raw file](https://github.com/cockroachdb/cockroach/blob/df1e9ce28602fe8a951c53e5fcb0cccde97047c9/pkg/cmd/roachtest/tests/db-console/Dockerfile#L1)):*
> ```Dockerfile
> FROM cypress/included:13.13.2
> ```

Seems like there's a similar dockerfile at: pkg/ui/workspaces/e2e-tests/Dockerfile.cypress.

Did you come across that one in your search? Any thoughts on merging the two, or do you know how that one is used?
___
*[`pkg/cmd/roachtest/tests/db-console/Dockerfile` line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133855#-OAx2EwH5TiUlSeJJMUY:-OAx2EwH5TiUlSeJJMUZ:b-xzm22n) ([raw file](https://github.com/cockroachdb/cockroach/blob/df1e9ce28602fe8a951c53e5fcb0cccde97047c9/pkg/cmd/roachtest/tests/db-console/Dockerfile#L3)):*
> ```Dockerfile
> FROM cypress/included:13.13.2
> 
> RUN apt-get -y update
> ```

Another thing to note, so the image is more compact and easier to move around, two things can be done:

1. A `npm build` step can be added so that everything required to run the tests is packaged in a small directory, this removes the need for a heavyweight `node_modules` directory to run the tests.
2. This dockerfile can be split into [multiple stages](https://docs.docker.com/build/building/multi-stage/). The final stage can include only the build directory so that it's as small as needs be.

**Review by kyle-a-wong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133855)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @angles-n-daemons, @DarrylWong, @dhartunian, @herkolategan, and @xinhaoz)

___
*[`pkg/cmd/roachtest/tests/db_console.go` line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133855#-OAx3Kh30oHy5dmlzI1a:-OB76RIV2FxhBBCGCOl5:b81sgs7) ([raw file](https://github.com/cockroachdb/cockroach/blob/df1e9ce28602fe8a951c53e5fcb0cccde97047c9/pkg/cmd/roachtest/tests/db_console.go#L6)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

If you could paint over this file one more time, and comment each of the functions in more detail it would really improve the comprehensibility of what's going on.
</blockquote></details>

Done. Can you take a second look and lmk what you think
___
*[`pkg/cmd/roachtest/tests/db_console.go` line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133855#-OAx0YUw-zLKWpAqJ6-J:-OB76bsW4dP3Q17HalqF:b-q6ot63) ([raw file](https://github.com/cockroachdb/cockroach/blob/df1e9ce28602fe8a951c53e5fcb0cccde97047c9/pkg/cmd/roachtest/tests/db_console.go#L162)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

Wherever possible, build should be decoupled from run. The docker run command can be here, but docker build should be somewhere in our build pipelines.

I'm not super familiar with our build pipelines, but it seems like there's a lot of stuff related to building and publishing images in this directory: `build/teamcity/internal/cockroach/build/`.

I believe that doing so can reduce the complexity of running a test.
</blockquote></details>

For now I'm leaving this as is.
___
*[`pkg/cmd/roachtest/tests/db_console.go` line 200 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133855#-OAwz98z2A8LDZdTT-pa:-OB76jbg3nmgh2P28Bbz:b-o5dwvu) ([raw file](https://github.com/cockroachdb/cockroach/blob/df1e9ce28602fe8a951c53e5fcb0cccde97047c9/pkg/cmd/roachtest/tests/db_console.go#L200)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

If the artifacts directory is created on the workload node after the tests are run, will it be empty?
</blockquote></details>

Good point. I moved this to be created before the tests run
___
*[`pkg/cmd/roachtest/tests/db_console.go` line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133855#-OAwyqsv0m6N_Amq8s4V:-OB76vjJ6rlPa82j2A5w:bbumi10) ([raw file](https://github.com/cockroachdb/cockroach/blob/df1e9ce28602fe8a951c53e5fcb0cccde97047c9/pkg/cmd/roachtest/tests/db_console.go#L202)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

where is this error created?
</blockquote></details>

This is the error from the if block, i had it here just to fail the test, but I changed the if block to use assert.NoError so that the stack trace is included in the logs, and added a t.fatal in place of this NoError call.
___
*[`pkg/cmd/roachtest/tests/db-console/Dockerfile` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133855#-OAx0Hq32nLR-S8NxOSx:-OB77ECw7CzSZKwtMzM-:bxpyz6k) ([raw file](https://github.com/cockroachdb/cockroach/blob/df1e9ce28602fe8a951c53e5fcb0cccde97047c9/pkg/cmd/roachtest/tests/db-console/Dockerfile#L1)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

Seems like there's a similar dockerfile at: pkg/ui/workspaces/e2e-tests/Dockerfile.cypress.

Did you come across that one in your search? Any thoughts on merging the two, or do you know how that one is used?
</blockquote></details>

I opted not to use or change any of the docker / local run configurations of the existing cypress test. `Dockerfile.cypress` is used in conjunction with `compose.yaml` to run the tests locally

**Review by angles-n-daemons — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133855#-:-OBB82bYEqIATXP2eKlM:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @dhartunian, @herkolategan, @kyle-a-wong, and @xinhaoz)

___
*[`pkg/cmd/roachtest/tests/db_console.go` line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133855#-OAx0YUw-zLKWpAqJ6-J:-OBB7ufU8Gqxp9HDxS3u:b-2zwhok) ([raw file](https://github.com/cockroachdb/cockroach/blob/df1e9ce28602fe8a951c53e5fcb0cccde97047c9/pkg/cmd/roachtest/tests/db_console.go#L162)):*
<details><summary><i>Previously, kyle-a-wong (Kyle Wong) wrote…</i></summary><blockquote>

For now I'm leaving this as is.
</blockquote></details>

Sounds good 👍
___
*[`pkg/cmd/roachtest/tests/db_console.go` line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133855#-OAwyqsv0m6N_Amq8s4V:-OBB7nyk8VDF2XSTw4A5:b-6dzroi) ([raw file](https://github.com/cockroachdb/cockroach/blob/df1e9ce28602fe8a951c53e5fcb0cccde97047c9/pkg/cmd/roachtest/tests/db_console.go#L202)):*
<details><summary><i>Previously, kyle-a-wong (Kyle Wong) wrote…</i></summary><blockquote>

This is the error from the if block, i had it here just to fail the test, but I changed the if block to use assert.NoError so that the stack trace is included in the logs, and added a t.fatal in place of this NoError call.
</blockquote></details>

Ah got it, thanks.

**Comment by kyle-a-wong** [comment]
tftr!

bors r+

**Comment by kyle-a-wong** [comment]
bors retry

**Pull request merged**
