### PR TITLE
sql/schemachanger: enable declarative schema changer to read comments from db

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
This commit adds a metadata fetcher interface to read comments
from db during descriptor elements walking. An implementation
of the interface is also added and plumbed into the descriptor
decomposition.

Release note: None

### CODE REVIEW

**Comment by chengxiong-ruan** [comment]
@postamar I decided to break this out from #78025 which I think it's hard enough to review even it was in a separate commit, I found it's really hard to make sure all test pass at each commit because the commits all kinda touching the same tests....

**Review by postamar — CHANGES_REQUESTED** [review]
Thanks for breaking this out. I think you did the right thing, there's a lot here, and it will make the `COMMENT ON` pull request a lot more straightforward to review.

I have a few objections, nothing too deep so don't wait for me to get back from vacation to merge this after addressing them.

> Reviewed 33 of 40 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80380#-:-N0Gz-YzE2PGvIqQM9vA:bwhs0y3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan)

___
*[pkg/sql/descmetadata/comment_cache.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80380#-N0Gxqq91bmH-PWMB8B9:-N0Gxqq91bmH-PWMB8BA:b-ljqlvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3016208a3747538e4bf7a821f663892dc9f76ca6/pkg/sql/descmetadata/comment_cache.go#L35)):*
> ```Go
> 	ie            sqlutil.InternalExecutor
> 	comments      map[scdecomp.CommentKey]string
> 	objIDsChecked map[catid.DescID]struct{}
> ```

nit: consider using a `catalog.DescriptorIDSet` instead?
___
*[pkg/sql/descmetadata/comment_cache.go, line 110 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80380#-N0GybUz6TgppwpETV3I:-N0GybUz6TgppwpETV3J:bb5jjha) ([raw file](https://github.com/cockroachdb/cockroach/blob/3016208a3747538e4bf7a821f663892dc9f76ca6/pkg/sql/descmetadata/comment_cache.go#L110)):*
> ```Go
> 		"mf-get-table-comments",
> 		mf.txn,
> 		sessiondata.InternalExecutorOverride{User: security.RootUserName()},
> ```

Just curious, why do we need to query this table as root? Is this how it's done in the legacy schema changer? (I haven't checked)
___
*[pkg/sql/schemachanger/scbuild/builder_state.go, line 432 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80380#-N0GwmjKDt0XwngEILkP:-N0GwmjL-qzd4wv9-HOA:b7pr78v) ([raw file](https://github.com/cockroachdb/cockroach/blob/3016208a3747538e4bf7a821f663892dc9f76ca6/pkg/sql/schemachanger/scbuild/builder_state.go#L432)):*
> ```Go
> 			}
> 		case catalog.Schema:
> 			if err := b.commentCache.LoadCommentsForObjects(b.ctx, catalog.Table, c.backrefs.Ordered()); err != nil {
> ```

Schemas also contain types, not just tables. Why does `LoadCommentsForObjects` require a descriptor type anyway? I don't understand the purpose of this filtering. Let's just warm the cache for all the back-referenced things, no?
___
*[pkg/sql/schemachanger/scdecomp/decomp.go, line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80380#-N0GtZ2fD1jQQWbmarKP:-N0GtZ2fD1jQQWbmarKQ:bn7bu8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/3016208a3747538e4bf7a821f663892dc9f76ca6/pkg/sql/schemachanger/scdecomp/decomp.go#L63)):*
> ```Go
> 	desc catalog.Descriptor,
> 	lookupFn func(id catid.DescID) catalog.Descriptor,
> 	ev ElementVisitor,
> ```

Consider moving the `ElementVisitor` definition to this new `dependencies.go` file, it seems like it would belong there.
___
*[pkg/sql/schemachanger/scdecomp/dependencies.go, line 26 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80380#-N0GsiN-Axj5LweiLbLs:-N0GsiN-Axj5LweiLbLt:b-aajk1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/3016208a3747538e4bf7a821f663892dc9f76ca6/pkg/sql/schemachanger/scdecomp/dependencies.go#L26)):*
> ```Go
> type CommentKey struct {
> 	ObjectID    catid.DescID
> 	SubID       descpb.ID
> ```

Shouldn't this also be a `catid.DescID`?
___
*[pkg/sql/schemachanger/scdecomp/dependencies.go, line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80380#-N0GstMs4deGCu239vmc:-N0GstMs4deGCu239vmd:b-5mv6a2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3016208a3747538e4bf7a821f663892dc9f76ca6/pkg/sql/schemachanger/scdecomp/dependencies.go#L28)):*
> ```Go
> 	SubID       descpb.ID
> 	CommentType keys.CommentType
> }
> ```

Why is this type defined here in `scdecomp` at all? 
___
*[pkg/sql/schemachanger/scdecomp/dependencies.go, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80380#-N0Gtrm_-iDbyiwrCriJ:-N0Gtrm_-iDbyiwrCriK:bnvz16e) ([raw file](https://github.com/cockroachdb/cockroach/blob/3016208a3747538e4bf7a821f663892dc9f76ca6/pkg/sql/schemachanger/scdecomp/dependencies.go#L32)):*
> ```Go
> // DescriptorCommentCache represent an interface to fetch metadata like
> // comment for descriptors.
> type DescriptorCommentCache interface {
> ```

The descriptor decomposition logic does not care that this is a cache, as far as it's concerned that's purely an implementation detail. I'm aware that's not the case for `scbuild` though.

What do you think of having an interface here that just does `Get`s and rename it `CommentGetter` or something. Then in the builder define another named `CommentCache` with the `LoadCommentsForObjects` method and which embeds `CommentGetter`?
___
*[pkg/sql/schemachanger/scdecomp/dependencies.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80380#-N0GuYsI6e81mlKfr1u6:-N0GuYsI6e81mlKfr1u7:b6s84i6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3016208a3747538e4bf7a821f663892dc9f76ca6/pkg/sql/schemachanger/scdecomp/dependencies.go#L35)):*
> ```Go
> 	// Get returns comment for a (objID, subID, commentType) tuple if exists. "ok"
> 	// returned indicates if the comment actually exists or not.
> 	Get(ctx context.Context, objID catid.DescID, subID descpb.ID, commentType keys.CommentType) (comment string, ok bool, err error)
> ```

How about replacing this one method with several, one for each comment type?`GetDatabaseComment(ctx, dbID)` etc.

No need to have the `system.comment` table schema leak everywhere.
___
*[pkg/sql/schemachanger/scdeps/sctestdeps/database_state.go, line 200 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80380#-N0GvckT5ob8alSWJCV7:-N0GvckT5ob8alSWJCV8:b4lc1pe) ([raw file](https://github.com/cockroachdb/cockroach/blob/3016208a3747538e4bf7a821f663892dc9f76ca6/pkg/sql/schemachanger/scdeps/sctestdeps/database_state.go#L200)):*
> ```Go
> 	}
> 	return comments
> }
> ```

This is fine but have you considered instead having a comment cache constructor in `descmetadata` which warms the cache by doing a `SELECT * FROM system.comments LIMIT 1000` or something like that?

This way you could re-use it in the test deps (no way we'd ever have more than 1k comments) plus you would amortize a lot of round trips in prod for the common case where there are at most very few comments.
___
*[pkg/sql/schemachanger/scplan/plan_test.go, line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80380#-N0GrjcgDUIcdlF9xZsX:-N0GrjcgDUIcdlF9xZsY:bu5kw71) ([raw file](https://github.com/cockroachdb/cockroach/blob/3016208a3747538e4bf7a821f663892dc9f76ca6/pkg/sql/schemachanger/scplan/plan_test.go#L60)):*
> ```Go
> 		run := func(t *testing.T, d *datadriven.TestData) string {
> 			// TODO (Chengxiong): make this switch block to have only "build" and
> 			// "ops/deps" sections.
> ```

I suggest you either follow up with a PR shortly or file an issue to track this, otherwise we'll forget about it.
___
*[pkg/sql/schemachanger/scplan/plan_test.go, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80380#-N0GryPt9iLdaiXxnk2K:-N0GryPt9iLdaiXxnk2L:b-bdmq1g) ([raw file](https://github.com/cockroachdb/cockroach/blob/3016208a3747538e4bf7a821f663892dc9f76ca6/pkg/sql/schemachanger/scplan/plan_test.go#L106)):*
> ```Go
> 					default:
> 						t.Fatal("not a supported descriptor metadata statement")
> 					}
> ```

Why have a switch block at all? Instead perhaps just `tdb.Exec(t, stmt.SQL)`?

Same comment applies elsewhere in this PR.

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80380)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

___
*[pkg/sql/descmetadata/comment_cache.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80380#-N0Gxqq91bmH-PWMB8B9:-N0HmYjA7abkdsVKTToT:b-5wiz31) ([raw file](https://github.com/cockroachdb/cockroach/blob/3016208a3747538e4bf7a821f663892dc9f76ca6/pkg/sql/descmetadata/comment_cache.go#L35)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

nit: consider using a `catalog.DescriptorIDSet` instead?
</blockquote></details>

nice, How could I forget that!
___
*[pkg/sql/descmetadata/comment_cache.go, line 110 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80380#-N0GybUz6TgppwpETV3I:-N0Hmq2R8RON-HpCsYK_:b-wcqmdq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3016208a3747538e4bf7a821f663892dc9f76ca6/pkg/sql/descmetadata/comment_cache.go#L110)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Just curious, why do we need to query this table as root? Is this how it's done in the legacy schema changer? (I haven't checked)
</blockquote></details>

Yeah, metadata updater and `show create table` also use root user. I remember I tried something else and got permission denied.
___
*[pkg/sql/schemachanger/scbuild/builder_state.go, line 432 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80380#-N0GwmjKDt0XwngEILkP:-N0Hp-d8DhNd56Dl3IQ8:b-b3pm2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/3016208a3747538e4bf7a821f663892dc9f76ca6/pkg/sql/schemachanger/scbuild/builder_state.go#L432)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Schemas also contain types, not just tables. Why does `LoadCommentsForObjects` require a descriptor type anyway? I don't understand the purpose of this filtering. Let's just warm the cache for all the back-referenced things, no?
</blockquote></details>

Good question...my reasoning was that
1. there's not comment on types, so I'm just being lazy here to treat everything as table. I agree it's confusing and I can add comment for that.
2. the comment table is indexed starting with `commentType`.... so I think the better practice is to respect the type first. But this table is probably very small as you said. so type filtering here is not necessary, especially after we add the `select limit 1000` thing you suggested :)
___
*[pkg/sql/schemachanger/scdecomp/decomp.go, line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80380#-N0GtZ2fD1jQQWbmarKP:-N0HqWBE-WMYub9NKa5l:bl7tnra) ([raw file](https://github.com/cockroachdb/cockroach/blob/3016208a3747538e4bf7a821f663892dc9f76ca6/pkg/sql/schemachanger/scdecomp/decomp.go#L63)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Consider moving the `ElementVisitor` definition to this new `dependencies.go` file, it seems like it would belong there.
</blockquote></details>

good point, done.
___
*[pkg/sql/schemachanger/scdecomp/dependencies.go, line 26 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80380#-N0GsiN-Axj5LweiLbLs:-N0HrMua1xBme4i7GiLB:b-gqafs6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3016208a3747538e4bf7a821f663892dc9f76ca6/pkg/sql/schemachanger/scdecomp/dependencies.go#L26)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Shouldn't this also be a `catid.DescID`?
</blockquote></details>

oops, we actually shouldn't use either since `SubID` is not for a descriptor. Using a uint32 instead...
___
*[pkg/sql/schemachanger/scdecomp/dependencies.go, line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80380#-N0GstMs4deGCu239vmc:-N0Hw30WETzt-hFEiaxy:bh9cpcv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3016208a3747538e4bf7a821f663892dc9f76ca6/pkg/sql/schemachanger/scdecomp/dependencies.go#L28)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Why is this type defined here in `scdecomp` at all? 
</blockquote></details>

moved to the implementation in `descmetadata`.
___
*[pkg/sql/schemachanger/scdecomp/dependencies.go, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80380#-N0Gtrm_-iDbyiwrCriJ:-N0HsJqqC_jN9_Eo6s31:bcooi7c) ([raw file](https://github.com/cockroachdb/cockroach/blob/3016208a3747538e4bf7a821f663892dc9f76ca6/pkg/sql/schemachanger/scdecomp/dependencies.go#L32)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

The descriptor decomposition logic does not care that this is a cache, as far as it's concerned that's purely an implementation detail. I'm aware that's not the case for `scbuild` though.

What do you think of having an interface here that just does `Get`s and rename it `CommentGetter` or something. Then in the builder define another named `CommentCache` with the `LoadCommentsForObjects` method and which embeds `CommentGetter`?
</blockquote></details>

yeah, that's brilliant~
___
*[pkg/sql/schemachanger/scdecomp/dependencies.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80380#-N0GuYsI6e81mlKfr1u6:-N0HwhMj5E0l5hb6_RVR:b-ite4k4) ([raw file](https://github.com/cockroachdb/cockroach/blob/3016208a3747538e4bf7a821f663892dc9f76ca6/pkg/sql/schemachanger/scdecomp/dependencies.go#L35)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

How about replacing this one method with several, one for each comment type?`GetDatabaseComment(ctx, dbID)` etc.

No need to have the `system.comment` table schema leak everywhere.
</blockquote></details>

Good idea to have these higher level methods. refactored as suggested.
___
*[pkg/sql/schemachanger/scdeps/sctestdeps/database_state.go, line 200 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80380#-N0GvckT5ob8alSWJCV7:-N0I4sxD-9UgfrSvttAI:bwc1ux1) ([raw file](https://github.com/cockroachdb/cockroach/blob/3016208a3747538e4bf7a821f663892dc9f76ca6/pkg/sql/schemachanger/scdeps/sctestdeps/database_state.go#L200)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

This is fine but have you considered instead having a comment cache constructor in `descmetadata` which warms the cache by doing a `SELECT * FROM system.comments LIMIT 1000` or something like that?

This way you could re-use it in the test deps (no way we'd ever have more than 1k comments) plus you would amortize a lot of round trips in prod for the common case where there are at most very few comments.
</blockquote></details>

good idea actually. but here in the test we use the test db runner instead of internal executor, so probably the only thin in common is the query.
But I do like the idea of warming the cache with a 1000 when it's constructed. added that.
___
*[pkg/sql/schemachanger/scplan/plan_test.go, line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80380#-N0GrjcgDUIcdlF9xZsX:-N0ICp7c8nkGdXwmq3g9:b-4cio3p) ([raw file](https://github.com/cockroachdb/cockroach/blob/3016208a3747538e4bf7a821f663892dc9f76ca6/pkg/sql/schemachanger/scplan/plan_test.go#L60)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I suggest you either follow up with a PR shortly or file an issue to track this, otherwise we'll forget about it.
</blockquote></details>

Yeah... I'm an old school and wrote on my notebook with an actual pen.
___
*[pkg/sql/schemachanger/scplan/plan_test.go, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80380#-N0GryPt9iLdaiXxnk2K:-N0IDFLp2ZE4lkGbOkFb:bva66g6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3016208a3747538e4bf7a821f663892dc9f76ca6/pkg/sql/schemachanger/scplan/plan_test.go#L106)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Why have a switch block at all? Instead perhaps just `tdb.Exec(t, stmt.SQL)`?

Same comment applies elsewhere in this PR.
</blockquote></details>

that's true...removed.

**Review by fqazi — APPROVED** [review]
:lgtm:  only very minor comments nothing blocking

> Reviewed 15 of 17 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80380#-:-N0WCTzq1d3YDbRHDNrB:b-ku4cou)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @chengxiong-ruan and @postamar)

___
*[`pkg/sql/descmetadata/comment_cache.go` line 119 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/80380#-N0WBcuzDVB3TBx1CKSa:-N0WBcuzDVB3TBx1CKSb:b-u7zsyz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b031376b49494baad4d580c66caf52edf17dfb3/pkg/sql/descmetadata/comment_cache.go#L119)):*
> ```Go
> 	}
> 
> 	var uncheckedObjIDs []catid.DescID
> ```

Probably won't be a problem, but you can do uncheckedObjIDs := objIDs[:0], which will keep the same storage length so that you won't have growth if there are more than a 1000 comments.
___
*[`pkg/sql/descmetadata/comment_cache.go` line 199 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/80380#-N0WAS_c0-1amlO07QXy:-N0WAS_c0-1amlO07QXz:b-sqtbmd) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b031376b49494baad4d580c66caf52edf17dfb3/pkg/sql/descmetadata/comment_cache.go#L199)):*
> ```Go
> 	// to avoid boundary cut by `LIMIT 1000`. We might lose 1 object here, but not
> 	// a big deal in most cases.
> 	mf.maxWarmedObjID = maxObjID - 1
> ```

objIDSChecked isn't updated above? Also, I don't get why we have to subtract 1 here? The check can always do >= maxWarmedObjID?

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80380)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi and @postamar)

___
*[`pkg/sql/descmetadata/comment_cache.go` line 119 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/80380#-N0WBcuzDVB3TBx1CKSa:-N0WKwIB8Mc7J9hkJPv8:b-5j8yg1) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b031376b49494baad4d580c66caf52edf17dfb3/pkg/sql/descmetadata/comment_cache.go#L119)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Probably won't be a problem, but you can do uncheckedObjIDs := objIDs[:0], which will keep the same storage length so that you won't have growth if there are more than a 1000 comments.
</blockquote></details>

ah nice trick, changed it to `make([]descid.DescID, 0, len(objIDs))` since looks like `uncheckedObjIDs := objIDs[:0]` would make them share the underlying storage.
___
*[`pkg/sql/descmetadata/comment_cache.go` line 199 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/80380#-N0WAS_c0-1amlO07QXy:-N0WJhSAArYRjLNCmBSv:b-wpvkuz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b031376b49494baad4d580c66caf52edf17dfb3/pkg/sql/descmetadata/comment_cache.go#L199)):*
> objIDSChecked isn't updated above?

oh, we don't need to update `objIDsChecked` here because of this logic:
```
func (mf *metadataCache) shouldLoadFromDB(objID catid.DescID) bool {
	return objID > mf.maxWarmedObjID && !mf.objIDsChecked.Contains(objID)
}
```
I just didn't want to put a 1000 ids by hand in it lol.

> Also, I don't get why we have to subtract 1 here? The check can always do >= maxWarmedObjID?

Yeah, we may do `>= maxWarmedObjID` as well. My brain model just worked that way somehow haha. The reason to subtract 1 here is just my laziness to handle edge cases where a table object_id has say 10 comments on different sub_ids, but because this table is that last obj we read from db, and we only read 5 comments of it, so we can't say this object_id is fully checked. Yes, it's just me lazy ha.

**Comment by chengxiong-ruan** [comment]
TFTR! @fqazi @postamar 
bors r+

**Pull request merged**
