### PR TITLE
sql: allow comparisons of tuples

### LINKED ISSUE #6206: sql: support tuple comparisons
Postgres supports comparing between tuples (semantically it's a lexicographical ordering):

```sql
SELECT * FROM t;
 k | a | b | c 
---+---+---+---
 1 | 1 | 2 | 3
 2 | 1 | 2 | 4
 3 | 1 | 3 | 0
 4 | 2 | 1 | 0
(4 rows)

SELECT * FROM t WHERE (a,b,c) > (1,2,3);
 k | a | b | c 
---+---+---+---
 2 | 1 | 2 | 4
 3 | 1 | 3 | 0
 4 | 2 | 1 | 0
(3 rows)
```

This can be useful for example when reading parts of a multi-column index. We don't support this (`pq: unsupported comparison operator: <tuple> < <tuple>`). To get the same behavior, the expression needs to be tediously rewritten:
```sql
SELECT * FROM t WHERE a > 1 OR (a = 1 AND (b > 2 OR (b = 2 AND c > 3)));
+---+---+---+---+
| k | a | b | c |
+---+---+---+---+
| 2 | 1 | 2 | 4 |
| 3 | 1 | 3 | 0 |
| 4 | 2 | 1 | 0 |
+---+---+---+---+
```

Note that we do support tuple equality/inequality.

### PR DESCRIPTION
**Pull request by madelynnblue**
Fixes #6206

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6217)

### CODE REVIEW

**Comment by andreimatei** [comment]
This is not yet used by index selection, is it? (and in that case I don't think we can say it fixes the bug)

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/parser/eval.go, line 744 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6217#-KFuv26uWbnwQlP3laqE:-KFuv26uWbnwQlP3laqF:-1604997315) ([raw file](https://github.com/cockroachdb/cockroach/blob/f48e76d00787928a79654ec1b352d59696982195/sql/parser/eval.go#L744)):*
isn't there a `DTuple.Compare` directly?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6217#-:-KFuv8_Y9XZ2aHer6kMq:-938644887)*

**Comment by mjibson** [comment]
Changed to "See".

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/parser/eval.go, line 744 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6217#-KFuv26uWbnwQlP3laqE:-KFw2uDh6uZaG7Za7ZIk:487297188) ([raw file](https://github.com/cockroachdb/cockroach/blob/f48e76d00787928a79654ec1b352d59696982195/sql/parser/eval.go#L744)):*
`DTuple.Compare` has different semantics than this. For example it allows comparing tuples of different lengths. However we can handle those and then call it directly, yes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6217#-:-KFw588-FmKZrsXNTj4L:1863377201)*

**Comment by mjibson** [comment]
Updated with tests for varying sizes and types. We now have an unfortunate panic/recover because Datum.Compare's function signature returns just an `int`, no errors, and it panics on type mismatch errors. Calling defer on every row where a tuple is being compared is perhaps a big enough performance problem that we should 1) not use DTuple's Compare method or 2) change the function signature of Datum.Compare to also return an error. Thoughts?

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6217#-:-KFw7csyg4Z9ei4McOSI:-1913900186)*

**Comment by RaduBerinde** [comment]
LGTM, but the issue should stay open until we generate constraints/spans in index selection. Otherwise you could argue it's worse than before, when the user was forced to rewrite the expression but when they did the query didn't scan the entire table..

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6217#-:-KFy0Y4Cd_WEuHzfg5Wn:-1046162623)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[sql/parser/eval.go, line 770 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6217#-KFyI81HMAC9KxhigcOH:-KFyI81HMAC9KxhigcOI:-1290428076) ([raw file](https://github.com/cockroachdb/cockroach/blob/09b56d3ddfa3b0e0c50aac062bcade0133fc9f88/sql/parser/eval.go#L770)):*
This should never happen as type-checking will not allow comparison of tuples with unequal numbers of elements. It's probably fine to leave out this check and rely on type-checking to catch unequal tuple lengths.

---

*[sql/parser/eval.go, line 773 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6217#-KFyII41btecI-d8fbEC:-KFyII41btecI-d8fbED:917934919) ([raw file](https://github.com/cockroachdb/cockroach/blob/09b56d3ddfa3b0e0c50aac062bcade0133fc9f88/sql/parser/eval.go#L773)):*
Is this necessary? Seems like the `panic` in `DTuple.Compare` shouldn't be reachable from here if we've already performed type-checking. If this is possible, can you add a test case?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6217#-:-KFyIyr0Rgjz8A5WgC5q:1417088721)*

**Comment by mjibson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[sql/parser/eval.go, line 770 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6217#-KFyI81HMAC9KxhigcOH:-KFyzsYK7GJmAvQOoIcq:-1551069483) ([raw file](https://github.com/cockroachdb/cockroach/blob/09b56d3ddfa3b0e0c50aac062bcade0133fc9f88/sql/parser/eval.go#L770)):*
What you describe doesn't seem to be the case. See the test case below with this error message. When this length check is removed that statement succeeds instead of errors.

---

*[sql/parser/eval.go, line 773 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6217#-KFyII41btecI-d8fbEC:-KFyzGjI8P2LderCM6rf:-1283881307) ([raw file](https://github.com/cockroachdb/cockroach/blob/09b56d3ddfa3b0e0c50aac062bcade0133fc9f88/sql/parser/eval.go#L773)):*
Yes, it's necessary, in the case of comparing tuples of the same length that have members that are different types. See the test case below for `unsupported comparison`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6217)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[sql/parser/eval.go, line 770 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6217#-KFyI81HMAC9KxhigcOH:-KFz0SrTowH7liF41Ynw:1825657427) ([raw file](https://github.com/cockroachdb/cockroach/blob/09b56d3ddfa3b0e0c50aac062bcade0133fc9f88/sql/parser/eval.go#L770)):*
That's surprising. Why isn't this being caught by `typeCheckTupleEQ`.

---

*[sql/parser/eval.go, line 773 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6217#-KFyII41btecI-d8fbEC:-KFz0chInZK_qkDUwAqB:1130320339) ([raw file](https://github.com/cockroachdb/cockroach/blob/09b56d3ddfa3b0e0c50aac062bcade0133fc9f88/sql/parser/eval.go#L773)):*
See my other comment. I would think this would be caught by `typeCheckTupleEQ`. Do you mind investigating why it isn't? Are we not running type-checking in some cases?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6217)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[sql/parser/eval.go, line 773 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6217#-KFyII41btecI-d8fbEC:-KFz0zGqh2EZIlEZwaOY:98107726) ([raw file](https://github.com/cockroachdb/cockroach/blob/09b56d3ddfa3b0e0c50aac062bcade0133fc9f88/sql/parser/eval.go#L773)):*
Ah, `typeCheckTupleEQ` is only checking tuples during equality. I think this change needs to change `typeCheckComparisonOp` to check other tuple operations.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6217)*

**Comment by mjibson** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[sql/parser/eval.go, line 770 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6217#-KFyI81HMAC9KxhigcOH:-KFzf5qNigKrGWC6ATRw:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/09b56d3ddfa3b0e0c50aac062bcade0133fc9f88/sql/parser/eval.go#L770)):*
Done.

---

*[sql/parser/eval.go, line 773 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6217#-KFyII41btecI-d8fbEC:-KFzf6Oz1x1rYXwJAWsa:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/09b56d3ddfa3b0e0c50aac062bcade0133fc9f88/sql/parser/eval.go#L773)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6217)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[sql/testdata/tuple, line 85 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6217#-KFzfh9QoudUg0t8HTdL:-KFzfh9RtZhWN7lSIspv:331136125) ([raw file](https://github.com/cockroachdb/cockroach/blob/57767282fed3739f5a8658045dd10d2f596daf96/sql/testdata/tuple#L85)):*
See below about the error message. This should be `<int> > <string>`, or even better: `(<int>, <int>) > (<int>, <string>)`. But let's just file an issue and fix it in a separate PR.

---

*[sql/testdata/tuple, line 88 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6217#-KFzfU8nXmlKHdluCQjD:-KFzfU8oNhdVyZgIunuK:-1871240316) ([raw file](https://github.com/cockroachdb/cockroach/blob/57767282fed3739f5a8658045dd10d2f596daf96/sql/testdata/tuple#L88)):*
Shouldn't that be `2, 3`? Let's file a bug about this incorrect error message. I think it is because we don't actually have a `>` operator, but implement it via `<` and swapping the arguments.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6217#-:-KFzg--dSNrLT8_WLy-N:1417088721)*

**Pull request merged**
