### PR TITLE
sql: Add SHOW LOCALITY command.

### LINKED ISSUE #38438: sql/cli: allow users to query for locality
**Problem**
Users need to look back at their initial start commands, look in the logs, or look at the data distribution page to retrieve locality. This can be error-prone and time-consuming.

**Proposed Solution**
In SQL, SHOW LOCALITY 
In the CLI, Cockroach node returns locality

### PR DESCRIPTION
**Pull request by rohany**
Fixes #38438.

`SHOW LOCALITY` returns the locality of the current node.

Release note (sql change): Add a `SHOW LOCALITY` command in sql.

### CODE REVIEW

**Comment by rohany** [comment]
```
./cockroach start --listen-addr=localhost --insecure --locality=region=us-east1
------
➜  cockroach git:(show-locality) ✗ ./cockroach sql --insecure
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
#
# Server version: CockroachDB CCL v19.2.0-alpha.20190606-964-ge9c579a369-dirty (x86_64-apple-darwin18.6.0, built 2019/07/23 19:27:01, go1.12.5) (same version as client)
# Cluster ID: 1be30eaf-3f36-4ae6-a2e7-867e4fce7410
# Organization: Cockroach Labs - Production Testing
#
# Enter \? for a brief introduction.
#
root@:26257/defaultdb> show locality;
     locality
+-----------------+
  region=us-east1
(1 row)

Time: 419µs

root@:26257/defaultdb>

**Review by solongordon — CHANGES_REQUESTED** [review]
- Rather than making this a query, I think it would better if `locality` was just a new variable like `node_id` is. See here: https://github.com/cockroachdb/cockroach/blob/cee171c75f88ccae19834c4320511beffe7d87dc/pkg/sql/vars.go#L520-L525 The implementation should look very similar actually since I think locality is stored on the `evalCtx`.
- What do we want this to show if there is no locality? Right now it's blank, which is maybe fine or maybe we would prefer "none" or something? I guess we can make a note to ask @awoods187 when he gets back.
- For commits like this with user-facing changes, you should fill out the "Release note" part of the commit message. That will be used by the docs team when they generate release notes, like this: https://www.cockroachlabs.com/docs/releases/v19.2.0-alpha.20190701.html

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39058#-:-LkxsZ-o2FJXNyhUdyml:b-uwd7mb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187 and @solongordon)

**Review by solongordon — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39058)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @rohany, and @solongordon)

___
*[pkg/sql/vars.go, line 516 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39058#-LkyQaBW1hBoHNYtaEL8:-LkyQaBX-YyXmk64KGGl:b-cglsz7) ([raw file](https://github.com/cockroachdb/cockroach/blob/9838dab221124ce343d729c8b4a14a4a086bf64d/pkg/sql/vars.go#L516)):*
> ```Go
> 				return evalCtx.Locality.String()
> 			}
> 			return "No locality set."
> ```

I changed my mind, I think this is kind of weird. :)  Let's just stick with the blank value.

**Review by solongordon — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39058#-:-Ll7fbe_0sO7tPRA6Oju:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @awoods187 and @rohany)

**Pull request merged**
