### PR TITLE
rocksdb: pickup patch for windows release builds

### PR DESCRIPTION
**Pull request by mberhault**
This picks up https://github.com/cockroachdb/rocksdb/pull/1 fixing unused errors in windows release builds.

### CODE REVIEW

**Review by benesch — APPROVED** [review]
Nice! Triggered a test release build against this branch: https://teamcity.cockroachdb.com/viewQueued.html?itemId=402637&tab=queuedBuildOverviewTab

**Comment by mberhault** [comment]
oh, I triggered a public bleeding-edge one already: https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_MergeToMaster&branch_Cockroach=19914&tab=buildTypeStatusDiv
I think the `branch != master` will skip the upload

**Comment by benesch** [comment]
Ah, that works too. No wonder I didn't see it.

**Comment by mberhault** [comment]
Looks like the windows build went through fine. Still having trouble with my local `builder.sh build TYPE=release-windows` though.

**Comment by benesch** [comment]
:shipit: 

What's the error you're getting on your local builder?

**Comment by mberhault** [comment]
```
# github.com/cockroachdb/cockroach/pkg/storage/engine
/x-tools/x86_64-w64-mingw32/lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.bfd: cannot find -lroach
/x-tools/x86_64-w64-mingw32/lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.bfd: cannot find -lprotobuf
/x-tools/x86_64-w64-mingw32/lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.bfd: cannot find -lrocksdb
/x-tools/x86_64-w64-mingw32/lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.bfd: cannot find -lsnappy
/x-tools/x86_64-w64-mingw32/lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.bfd: cannot find -ljemalloc
collect2: error: ld returned 1 exit status
github.com/cockroachdb/cockroach/pkg/kv
github.com/cockroachdb/cockroach/pkg/server/diagnosticspb
Makefile:220: recipe for target 'build' failed
make: *** [build] Error 2
```

**Comment by mberhault** [comment]
This is after successful build of the individual libraries.

**Comment by benesch** [comment]
Oh, you've probably got busted zcgo_flags files. Try:

```
find . -name 'zcgo_flags*' -delete
```

**Comment by mberhault** [comment]
That did the trick. Thank you.

**Pull request merged**
