### PR TITLE
pkg/jobs: remove usage of `reflect`

### PR DESCRIPTION
**Pull request by chrisseto**
Based on https://github.com/cockroachdb/cockroach/pull/113008

Previously, `InitFromDatums` utilized `reflect` to hydrate a scheduled job from queried data.

While the implementation was not particularly problematic, it felt a bit arcane and was resistant to easy extension. In particular, adding support for wrapped types proved to be difficult short of special casing fields.

To aid a future commit that aims to wrap ScheduleID in it's own type, this commit replaces the reflect implementation with a simple switch statement.

The `col` struct tags have been left in place as they are a useful reference.

Epic: none
Informs: #110909
Release note: None

### CODE REVIEW

**Review by stevendanna — COMMENTED** [review]
Thanks for working on this. I think making ScheduleID its own type is a great goal.

I'm OK with this more explicit approach and appreciate the unit tests you've added.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113008#-:-NhfKcGJ6cpZdT0HzV83:bmwrhku)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chrisseto and @dt)

___
*[`pkg/jobs/scheduled_job.go` line 296 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113008#-NhfIHc1DJJdv3mBbpv0:-NhfIHc1DJJdv3mBbpv1:b-k7hri7) ([raw file](https://github.com/cockroachdb/cockroach/blob/598a22b055bac7a6d493871a2921bf2f1804bcc2/pkg/jobs/scheduled_job.go#L296)):*
> ```Go
> 	}
> 
> 	nullFields := 0
> ```

[nit] what you have is fine, but I think it might be a _little_ clearer if this was just a `modified` bool.
___
*[`pkg/jobs/scheduled_job.go` line 373 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113008#-NhfIB-r7KqOGwbrNIsi:-NhfIB-r7KqOGwbrNIsj:b-wngbog) ([raw file](https://github.com/cockroachdb/cockroach/blob/598a22b055bac7a6d493871a2921bf2f1804bcc2/pkg/jobs/scheduled_job.go#L373)):*
> ```Go
> 				return err
> 			}
> 		}
> ```

Do we want a default case here that returns an error?

**Review by chrisseto — COMMENTED** [review]
TFTR, PTAL!

For posterity, this change was suggested by @dt https://cockroachlabs.slack.com/archives/CLQ753JGH/p1698173868597269?thread_ts=1698172725.414779&cid=CLQ753JGH

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113008#-:-NhgDU2lBS_quNZygMkt:bdf3b9v)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @stevendanna)

___
*[`pkg/jobs/scheduled_job.go` line 296 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113008#-NhfIHc1DJJdv3mBbpv0:-NhgDNaK1kMjji69moQp:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/598a22b055bac7a6d493871a2921bf2f1804bcc2/pkg/jobs/scheduled_job.go#L296)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

[nit] what you have is fine, but I think it might be a _little_ clearer if this was just a `modified` bool.
</blockquote></details>

Done!
___
*[`pkg/jobs/scheduled_job.go` line 373 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113008#-NhfIB-r7KqOGwbrNIsi:-NhgAAVC3zlkYXI22fOd:b-y7bubz) ([raw file](https://github.com/cockroachdb/cockroach/blob/598a22b055bac7a6d493871a2921bf2f1804bcc2/pkg/jobs/scheduled_job.go#L373)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Do we want a default case here that returns an error?
</blockquote></details>

Surprisingly, no. The original code skipped over any fields that were unused. I defaulted to having an error case and that ended up breaking a lot of tests. Instead of ignoring field implicitly, I've added a default case with a note.

**Review by stevendanna — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113008)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chrisseto and @dt)

___
*[`pkg/jobs/scheduled_job.go` line 373 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113008#-NhfIB-r7KqOGwbrNIsi:-NhgETdzC0fcxyaq0nI6:b8w6pbl) ([raw file](https://github.com/cockroachdb/cockroach/blob/598a22b055bac7a6d493871a2921bf2f1804bcc2/pkg/jobs/scheduled_job.go#L373)):*
<details><summary><i>Previously, chrisseto (Chris Seto) wrote…</i></summary><blockquote>

Surprisingly, no. The original code skipped over any fields that were unused. I defaulted to having an error case and that ended up breaking a lot of tests. Instead of ignoring field implicitly, I've added a default case with a note.
</blockquote></details>

Interesting, thanks!

**Comment by chrisseto** [comment]
TFTR!

bors r=stevendanna

**Pull request merged**
