### PR TITLE
sql: add telemetry for ALTER DATABASE PLACEMENT

### LINKED ISSUE #68597: sql: add telemetry for PLACEMENT operations
In #68433, syntax is being added to remove non-voting replicas from a database zone configuration. We need to add telemetry to track how many ALTER DATABASE SET PLACEMENT commands are run. The pattern for SURVIVE telemetry can likely be lifted as it's tracking the same kind of information on the database.

### PR DESCRIPTION
**Pull request by pawalt**
This PR adds telemetry for ALTER DATABASE PLACEMENT operations.

Release note: None

Resolves #68597

### CODE REVIEW

**Review by arulajmani — CHANGES_REQUESTED** [review]
I don't think this PR adds telemetry, it adds support for event logs. We probably want telemetry too, should we do that in a separate PR? 

Separately, I think you've got a bit more to do before these event logs work correctly. I suspect if you altered a database's placement policy you wouldn't have it show up correctly in the UI. Does it? Here's an example PR to follow for the last step: https://github.com/cockroachdb/cockroach/pull/63141/files#

> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69006#-:-MhFMVKa48rPn9v1uHXW:b4iwa4n)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @pawalt)

___
*[pkg/util/log/eventpb/ddl_events.proto, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69006#-MhFM0jp5BZEGx1MNm8O:-MhFM0jp5BZEGx1MNm8P:bwsa7y) ([raw file](https://github.com/cockroachdb/cockroach/blob/e65b36994c5ff4c4db313ac2c9593cb8504462bd/pkg/util/log/eventpb/ddl_events.proto#L99)):*
> ```protobuf
>   // The name of the database.
>   string database_name = 3 [(gogoproto.jsontag) = ",omitempty"];
>   // The new survival goal
> ```

Did you mean new placement policy?

**Review by pawalt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69006)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @otan)

___
*[pkg/util/log/eventpb/ddl_events.proto, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69006#-MhFM0jp5BZEGx1MNm8O:-MhK5UNP2F-njTeDKv5L:bd910lj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e65b36994c5ff4c4db313ac2c9593cb8504462bd/pkg/util/log/eventpb/ddl_events.proto#L99)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Did you mean new placement policy?
</blockquote></details>

Oops bad copypasta

**Review by arulajmani — CHANGES_REQUESTED** [review]
The telemetry counters are missing test coverage. Check out `pkg/ccl/telemetryccl/testdata/telemetry/multiregion`, that's probably where we want this stuff. 

> Reviewed 3 of 6 files at r1, 3 of 3 files at r2, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69006#-:-MhK6u-rElJcwQDT6t51:brhhvk7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @otan, and @pawalt)

___
*[pkg/sql/alter_database.go, line 1153 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69006#-MhK66AiDUVBdhGwN7gI:-MhK66AiDUVBdhGwN7gJ:b-re5dpy) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4216b99b3037be46d799d18a9ea6ca450db7160/pkg/sql/alter_database.go#L1153)):*
> ```Go
> 
> 	telemetry.Inc(
> 		sqltelemetry.AlterDatabaseSurvivalGoalCounter(
> ```

Did you mean to call `AlterDatabasePlacementCounter` here?

**Review by pawalt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69006)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @otan)

___
*[pkg/sql/alter_database.go, line 1153 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69006#-MhK66AiDUVBdhGwN7gI:-MhKBRF45p3IF1DIqHLo:b-99pbjp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4216b99b3037be46d799d18a9ea6ca450db7160/pkg/sql/alter_database.go#L1153)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Did you mean to call `AlterDatabasePlacementCounter` here? 
</blockquote></details>

Damn could have sworn I changed that. Fixed.

**Review by arulajmani — CHANGES_REQUESTED** [review]
One testing request, but otherwise :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69006#-:-MhLxK5TDfoljeoTIFEd:bkyaf6d)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani, @otan, and @pawalt)

___
*[pkg/ccl/telemetryccl/testdata/telemetry/multiregion, line 35 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69006#-MhLwz3F1vNOZDP9nFJ5:-MhLwz3F1vNOZDP9nFJ6:bz8hhr2) ([raw file](https://github.com/cockroachdb/cockroach/blob/659c72d60bb4415e27a9556f9b0ac0f66e68bdab/pkg/ccl/telemetryccl/testdata/telemetry/multiregion#L35)):*
> ```
> 
> feature-usage
> ALTER DATABASE to_be_restricted SET PLACEMENT RESTRICTED
> ```

Let's add one for `SET PLACEMENT DEFAULT` as well?  both create and alter database. 
___
*[pkg/sql/sem/tree/data_placement.go, line 43 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69006#-MhLxEhpAHM04UbU_rEv:-MhLxEhpAHM04UbU_rEw:bredx1n) ([raw file](https://github.com/cockroachdb/cockroach/blob/659c72d60bb4415e27a9556f9b0ac0f66e68bdab/pkg/sql/sem/tree/data_placement.go#L43)):*
> ```Go
> }
> 
> // TelemetryName returns a representation of DataPlacement suitable for telemetry
> ```

nit: full stop.

**Review by arulajmani — APPROVED** [review]
Sorry, meant to approve. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69006#-:-MhLxNsrDHZL63s57RKc:blludsn)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani, @otan, and @pawalt)

**Review by pawalt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69006)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani and @otan)

___
*[pkg/ccl/telemetryccl/testdata/telemetry/multiregion, line 35 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69006#-MhLwz3F1vNOZDP9nFJ5:-MhOkx__4LiNZmDhUNO3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/659c72d60bb4415e27a9556f9b0ac0f66e68bdab/pkg/ccl/telemetryccl/testdata/telemetry/multiregion#L35)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Let's add one for `SET PLACEMENT DEFAULT` as well?  both create and alter database. 
</blockquote></details>

Done.

**Review by arulajmani — APPROVED** [review]
:lgtm: 

I think you need to update some generated code.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69006#-:-MhPGyUB3lNSX05LK0li:b2clugb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @otan)

**Comment by pawalt** [comment]
bors r=arulajmani

**Pull request merged**
