### PR TITLE
WIP: Not for review

### PR DESCRIPTION
**Pull request by vivekmenezes**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5765)

### CODE REVIEW

**Comment by tamird** [comment]
FWIW you can add your fork of the repo to circleCI and run builds without opening PRs, if that was intention here.

**Comment by vivekmenezes** [comment]
My intention is to get help with this PR. Whats the best way to share a PR privately.

I'm having problems with the second commit.

**Comment by tamird** [comment]
This approach is simply not the right way to go. The problem you're having is that api.proto is used from c++, and importing raft.proto there requires some yak shaving (and actually doing that yak shave will produce a bunch of dead c++ code).

How about you move the CheckConsistency protos into a new file instead?

**Comment by vivekmenezes** [comment]
Thanks. Will give it a try and include that in the other PR

**Pull request closed without merging**
