### PR TITLE
storage: leave intents behind after blind-writes experiencing write-too-old

### PR DESCRIPTION
**Pull request by andreimatei**
Before this patch, any write running into a write-too-old condition
resulted in a WriteTooOldError being returned by the server. Returning
an error implies that no intents are left behind. This is unfortunate;
we'd like to leave intents (or, in the future, other types of locks)
behind so keep away other transactions. We've observed this resulting in
the starvation of a class of transactions in a user's workload.

This patch makes it so that blind writes (i.e. Puts - used by UPDATE,
not CPuts) don't return WriteTooOldErrors any more. Instead, they return
the a txn proto with the WriteTooOld flag set. This is the behavior they
had before #38668. This patch retains the goal of #38668, however: the
client now eagerly refreshes the transactions when it sees a WriteTooOld
flag, and if the refresh succeeds, it returns a WriteTooOldError to the
higher layers (SQL), allowing for automatic retries where applicable.

Unfortunately, CPuts (used by INSERT) continue to return
WriteTooOldErrors without leaving locks behind. Dealing with them
requires more tenderness because they imply a read, and the timestamp of
a read cannot be bumped as easily as that of a write.

Touches #44653

Release note (SQL change): UPDATEs returning a serialization failure error (code
40001) now leave behind a lock, helping the transaction succeed if it
retries. This prevents starvation of transactions whose UPDATEs are
prone to conflicts.

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
everything but the last 3 commits is elsewhere

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-:-M-Bu2JAAO8ZbuwnOMzQ:bnl5k71)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by nvb — COMMENTED** [review]
> Reviewed 2 of 14 files at r4, 1 of 20 files at r6, 1 of 1 files at r10, 4 of 4 files at r11, 14 of 14 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44654)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/dist_sender.go, line 651 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-_xWLLB1eIKdGiwtLs:-M-_xWLLB1eIKdGiwtLt:bozl2pt) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c3c16343fa593d28f1c9c86dea39e618de5e47/pkg/kv/dist_sender.go#L651)):*
> ```Go
> // encountered in the transaction and retry just the EndTxn request to
> // avoid client-side serializable txn retries.
> // TODO(andrei,nvanbenschoten): Get rid of this returning both error and result,
> ```

Didn't you just address this?
___
*[pkg/kv/dist_sender_server_test.go, line 2407 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-_xcT3E5IYOFUOp7C3:-M-_xcT3E5IYOFUOp7C4:bqxqlpm) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c3c16343fa593d28f1c9c86dea39e618de5e47/pkg/kv/dist_sender_server_test.go#L2407)):*
> ```Go
> 				lastAutoRetries = metrics.AutoRetries.Count()
> 
> 				err := tc.retryable(ctx, txn)
> ```

You can undo this.
___
*[pkg/kv/txn_interceptor_span_refresher.go, line 231 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-_zN8815FR6ZVCSEiZ:-M-_zN8815FR6ZVCSEi_:b-jqc8fk) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c3c16343fa593d28f1c9c86dea39e618de5e47/pkg/kv/txn_interceptor_span_refresher.go#L231)):*
> ```Go
> ) (_ *roachpb.BatchResponse, _ *roachpb.Error, largestRefreshTS hlc.Timestamp) {
> 	br, pErr := sr.sendHelper(ctx, ba)
> 	if pErr == nil && br.Txn.WriteTooOld {
> ```

Let's add a few tight tests around this logic in `txn_interceptor_span_refresher_test.go`.
___
*[pkg/kv/txn_interceptor_span_refresher.go, line 231 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-_zfI65yvFDFyqXmYj:-M-_zfI65yvFDFyqXmYk:bag56jg) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c3c16343fa593d28f1c9c86dea39e618de5e47/pkg/kv/txn_interceptor_span_refresher.go#L231)):*
> ```Go
> ) (_ *roachpb.BatchResponse, _ *roachpb.Error, largestRefreshTS hlc.Timestamp) {
> 	br, pErr := sr.sendHelper(ctx, ba)
> 	if pErr == nil && br.Txn.WriteTooOld {
> ```

Should we check whether `ba.Txn.WriteTooOld` was already set? Will that be possible with this new eager refresh-or-error policy?
___
*[pkg/kv/txn_interceptor_span_refresher.go, line 250 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-_zodm2co1YIxGT7Dg:-M-_zodnArgptdxZvpD5:bkbb0py) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c3c16343fa593d28f1c9c86dea39e618de5e47/pkg/kv/txn_interceptor_span_refresher.go#L250)):*
> ```Go
> 		//
> 		// For the refresh, we have two options: either refresh everything read
> 		// *before* this batch, and then retry to batch, or refresh the current
> ```

the batch
___
*[pkg/kv/txn_interceptor_span_refresher.go, line 258 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-a-01EEmuMRS5YI4AH:-M-a-01EEmuMRS5YI4AI:b-darfr1) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c3c16343fa593d28f1c9c86dea39e618de5e47/pkg/kv/txn_interceptor_span_refresher.go#L258)):*
> ```Go
> 		bumpedTxn.ReadTimestamp = bumpedTxn.WriteTimestamp
> 		pErr = roachpb.NewErrorWithTxn(
> 			roachpb.NewTransactionRetryError(roachpb.RETRY_WRITE_TOO_OLD, ""),
> ```

You were the one who wanted the `extraMsg`...
___
*[pkg/kv/txn_interceptor_span_refresher.go, line 266 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-a-GrQ91pqV4DDPhjL:-M-a-GrQ91pqV4DDPhjM:bpvh14e) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c3c16343fa593d28f1c9c86dea39e618de5e47/pkg/kv/txn_interceptor_span_refresher.go#L266)):*
> ```Go
> 	}
> 	if pErr != nil {
> 		// Don't confuse layers above with both a result and an error. This layer is
> ```

I thought we got rid of this?
___
*[pkg/kv/txn_interceptor_span_refresher.go, line 272 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-a-KaP6AwAskSejlDh:-M-a-KaP6AwAskSejlDi:b-jpia0y) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c3c16343fa593d28f1c9c86dea39e618de5e47/pkg/kv/txn_interceptor_span_refresher.go#L272)):*
> ```Go
> 		// Terminate the txn.WriteTooOld flag here. We failed to refresh it away, so
> 		// turn it into a retriable error.
> 		if br.Txn.WriteTooOld {
> ```

We need this again? If so, let's add a test where it's necessary and also pull the logic into a helper.
___
*[pkg/kv/txn_interceptor_span_refresher.go, line 332 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-a-Z6NBaj4CGrg4ZXt:-M-a-Z6NBaj4CGrg4ZXu:btxylbw) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c3c16343fa593d28f1c9c86dea39e618de5e47/pkg/kv/txn_interceptor_span_refresher.go#L332)):*
> ```Go
> 	// Try updating the txn spans so we can retry.
> 	if ok := sr.tryUpdatingTxnSpans(ctx, retryTxn); !ok {
> 		return br, pErr, hlc.Timestamp{}
> ```

Why was this needed?
___
*[pkg/roachpb/api.proto, line 1788 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-_xt048MIvLUl_Q7VT:-M-_xt048MIvLUl_Q7VU:b95xee8) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c3c16343fa593d28f1c9c86dea39e618de5e47/pkg/roachpb/api.proto#L1788)):*
> ```protobuf
>   // idempotent. We could just re-issue requests. See #26915.
>   bool async_consensus = 13;
>   reserved 7,12,14;
> ```

smallest nit possible: we put spaces between these everywhere else.
___
*[pkg/storage/replica_evaluate.go, line 288 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-a0QuFASXhcPcDC8UF:-M-a0QuFASXhcPcDC8UG:b1wp2z7) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c3c16343fa593d28f1c9c86dea39e618de5e47/pkg/storage/replica_evaluate.go#L288)):*
> ```Go
> 				// to be rejected if it were sent again with the same sequence number
> 				// after a refresh.
> 				// TODO(andrei): What we really want to do here is either speculatively
> ```

This is going to be a great change when it happens.
___
*[pkg/storage/replica_test.go, line 4513 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-_wcLKBnYNzo9nu59W:-M-_wcLKBnYNzo9nu59X:b-pr7vzc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f07bd5f7657052a08642ceef90f3562ecf2b2afa/pkg/storage/replica_test.go#L4513)):*
> ```Go
> 	}
> 
> 	// Expect that keyB intent got leaked.
> ```

What does "leaked" mean? Anyone who runs into will notice that they're able to remove it, so it's not really leaked without recourse. I'd add a bit more here.
___
*[pkg/storage/replica_test.go, line 9599 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-_yNHo62DTjgxiT1b8:-M-_yNHo62DTjgxiT1b9:b-d8hff) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c3c16343fa593d28f1c9c86dea39e618de5e47/pkg/storage/replica_test.go#L9599)):*
> ```Go
> 		ba.Add(&put)
> 		return send(ba)
> ```

nit: remove this diff
___
*[pkg/storage/replica_write.go, line 477 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-_zCPA1tqnfKmlbat5:-M-_zCPA1tqnfKmlbat6:b837yjo) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c3c16343fa593d28f1c9c86dea39e618de5e47/pkg/storage/replica_write.go#L477)):*
> ```Go
> 		pErrOrWTO := pErr
> 		if pErr == nil && br.Txn != nil && br.Txn.WriteTooOld {
> 			bumpedTxn := br.Txn.Clone()
> ```

This seems like a lot of wasted allocations. Is there a clean way to pull this into `canDoServersideRetry` and avoid them?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44654)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/dist_sender.go, line 651 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-_xWLLB1eIKdGiwtLs:-M-kAl4O2tVTkQUlPHPd:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c3c16343fa593d28f1c9c86dea39e618de5e47/pkg/kv/dist_sender.go#L651)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Didn't you just address this?
</blockquote></details>

done
___
*[pkg/kv/dist_sender_server_test.go, line 2407 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-_xcT3E5IYOFUOp7C3:-M-kArAq9eadaa_2IMGr:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c3c16343fa593d28f1c9c86dea39e618de5e47/pkg/kv/dist_sender_server_test.go#L2407)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

You can undo this.
</blockquote></details>

done
___
*[pkg/kv/txn_interceptor_span_refresher.go, line 231 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-_zfI65yvFDFyqXmYj:-M-kBZWq9Fqrr7KIQZ9o:b2pmpjt) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c3c16343fa593d28f1c9c86dea39e618de5e47/pkg/kv/txn_interceptor_span_refresher.go#L231)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we check whether `ba.Txn.WriteTooOld` was already set? Will that be possible with this new eager refresh-or-error policy?
</blockquote></details>

It's no longer possible for `ba.Txn.WriteTooOld` to be set.
___
*[pkg/kv/txn_interceptor_span_refresher.go, line 231 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-_zN8815FR6ZVCSEiZ:-M-kyqPL56AkMV0oVoXu:b7z2ife) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c3c16343fa593d28f1c9c86dea39e618de5e47/pkg/kv/txn_interceptor_span_refresher.go#L231)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's add a few tight tests around this logic in `txn_interceptor_span_refresher_test.go`.
</blockquote></details>

added one such tests. Were you thinking of more?
___
*[pkg/kv/txn_interceptor_span_refresher.go, line 250 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-_zodm2co1YIxGT7Dg:-M-kBnLD7osGC396hoFY:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c3c16343fa593d28f1c9c86dea39e618de5e47/pkg/kv/txn_interceptor_span_refresher.go#L250)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

the batch
</blockquote></details>

done
___
*[pkg/kv/txn_interceptor_span_refresher.go, line 258 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-a-01EEmuMRS5YI4AH:-M-kCBap6FYRbLiVVFVu:b5huec9) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c3c16343fa593d28f1c9c86dea39e618de5e47/pkg/kv/txn_interceptor_span_refresher.go#L258)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

You were the one who wanted the `extraMsg`...
</blockquote></details>

well but what would it say in this case?
___
*[pkg/kv/txn_interceptor_span_refresher.go, line 266 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-a-GrQ91pqV4DDPhjL:-M-kDe-b8wztiZeQ4Wif:b6amgh5) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c3c16343fa593d28f1c9c86dea39e618de5e47/pkg/kv/txn_interceptor_span_refresher.go#L266)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I thought we got rid of this?
</blockquote></details>

yes, I've now rebased on the other change
___
*[pkg/kv/txn_interceptor_span_refresher.go, line 272 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-a-KaP6AwAskSejlDh:-M-kDjlQ3eJu0_RomPSw:baja3cs) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c3c16343fa593d28f1c9c86dea39e618de5e47/pkg/kv/txn_interceptor_span_refresher.go#L272)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We need this again? If so, let's add a test where it's necessary and also pull the logic into a helper.
</blockquote></details>

We didn't need this. It was a bad leftover. Done.
___
*[pkg/kv/txn_interceptor_span_refresher.go, line 332 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-a-Z6NBaj4CGrg4ZXt:-M-kDxrAEfpI8h1NcrlZ:b-c55qta) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c3c16343fa593d28f1c9c86dea39e618de5e47/pkg/kv/txn_interceptor_span_refresher.go#L332)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why was this needed?
</blockquote></details>

it wasn't. Good catch.
___
*[pkg/roachpb/api.proto, line 1788 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-_xt048MIvLUl_Q7VT:-M-kEAFIAaJAUn0OP6ue:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c3c16343fa593d28f1c9c86dea39e618de5e47/pkg/roachpb/api.proto#L1788)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

smallest nit possible: we put spaces between these everywhere else.
</blockquote></details>

done
___
*[pkg/storage/replica_evaluate.go, line 288 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-a0QuFASXhcPcDC8UF:-M-kESrZ9xLbCRnj5g9j:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c3c16343fa593d28f1c9c86dea39e618de5e47/pkg/storage/replica_evaluate.go#L288)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is going to be a great change when it happens.
</blockquote></details>

:thumbsup: 
___
*[pkg/storage/replica_test.go, line 4513 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-_wcLKBnYNzo9nu59W:-M-kPJUs3lA2WQn5lVdl:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f07bd5f7657052a08642ceef90f3562ecf2b2afa/pkg/storage/replica_test.go#L4513)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What does "leaked" mean? Anyone who runs into will notice that they're able to remove it, so it's not really leaked without recourse. I'd add a bit more here.
</blockquote></details>

done
___
*[pkg/storage/replica_test.go, line 9599 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-_yNHo62DTjgxiT1b8:-M-kH8uMCjKz7RXMDoYt:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c3c16343fa593d28f1c9c86dea39e618de5e47/pkg/storage/replica_test.go#L9599)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: remove this diff
</blockquote></details>

done
___
*[pkg/storage/replica_write.go, line 477 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-_zCPA1tqnfKmlbat5:-M-kSouN1HindHut6kE6:bm938yc) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c3c16343fa593d28f1c9c86dea39e618de5e47/pkg/storage/replica_write.go#L477)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This seems like a lot of wasted allocations. Is there a clean way to pull this into `canDoServersideRetry` and avoid them?
</blockquote></details>

ok, see now

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 19 files at r13, 4 of 4 files at r14, 14 of 14 files at r15.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44654)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/txn_interceptor_span_refresher.go, line 231 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-_zfI65yvFDFyqXmYj:-M-oqujM6HyVP6crY2B3:bomfb9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c3c16343fa593d28f1c9c86dea39e618de5e47/pkg/kv/txn_interceptor_span_refresher.go#L231)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

It's no longer possible for `ba.Txn.WriteTooOld` to be set.
</blockquote></details>

Should we assert against that then? What about if this is a refresher on a leaf txn coordinator and the root is a 19.2 node?
___
*[pkg/kv/txn_interceptor_span_refresher.go, line 258 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-a-01EEmuMRS5YI4AH:-M-oqkcI8_HVVXYIv5pm:bifl9sv) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c3c16343fa593d28f1c9c86dea39e618de5e47/pkg/kv/txn_interceptor_span_refresher.go#L258)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

well but what would it say in this case?
</blockquote></details>

"WriteTooOld flag converted to WriteTooOldError" or something
___
*[pkg/kv/txn_interceptor_span_refresher_test.go, line 105 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-orBmY1i3hg70aA0Pl:-M-orBmZ-tHVqax6BApi:b8tajhc) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c2269a488b9d775f83960ae8f016f66c2808b3d/pkg/kv/txn_interceptor_span_refresher_test.go#L105)):*
> ```Go
> 		// If name is not set, the test will use pErr.String().
> 		name string
> 		// OnFirstSend, if set, is invoked to evaluate the batch. If not set, pErr()
> ```

Consider constraining this to something like `br func(roachpb.BatchRequest) *roachpb.BatchResponse` and then require that exactly one of `br` and `pErr` are set.

Then you can also keep the assertions in `onFirstSend` below.
___
*[pkg/kv/txn_interceptor_span_refresher_test.go, line 187 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-orzQP6SfvYIU8R_Dz:-M-orzQP6SfvYIU8R_E-:b4o9aow) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c2269a488b9d775f83960ae8f016f66c2808b3d/pkg/kv/txn_interceptor_span_refresher_test.go#L187)):*
> ```Go
> 			// Collect some refresh spans.
> 			var ba roachpb.BatchRequest
> 			clonedTxn := txn.Clone()
> ```

nit, just inline this: `ba.Header = roachpb.Header{Txn: txn.Clone()}`
___
*[pkg/storage/replica_test.go, line 4513 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-_wcLKBnYNzo9nu59W:-M-osDRXDVdfIRtlobCf:bdpqrl2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f07bd5f7657052a08642ceef90f3562ecf2b2afa/pkg/storage/replica_test.go#L4513)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

done
</blockquote></details>

Did you mean to leave both comments?
___
*[pkg/storage/replica_write.go, line 477 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-_zCPA1tqnfKmlbat5:-M-osRBS7IQ3PFxYiwPK:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c3c16343fa593d28f1c9c86dea39e618de5e47/pkg/storage/replica_write.go#L477)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

ok, see now
</blockquote></details>

:thumbsup:

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44654)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/txn_interceptor_span_refresher.go, line 231 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-_zfI65yvFDFyqXmYj:-M-owBtQ2bd1DCdFHPeg:b-9a5hbb) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c3c16343fa593d28f1c9c86dea39e618de5e47/pkg/kv/txn_interceptor_span_refresher.go#L231)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we assert against that then? What about if this is a refresher on a leaf txn coordinator and the root is a 19.2 node?
</blockquote></details>

I had not considered 19.2 roots. I've added code to reset the flag in `newLeafTxnCoordSender()` - I think that's better than handling the flag here.
I've also added an assertion.
___
*[pkg/kv/txn_interceptor_span_refresher.go, line 258 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-a-01EEmuMRS5YI4AH:-M-p-Og77kkqlgIDpuT0:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c3c16343fa593d28f1c9c86dea39e618de5e47/pkg/kv/txn_interceptor_span_refresher.go#L258)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"WriteTooOld flag converted to WriteTooOldError" or something
</blockquote></details>

done
___
*[pkg/kv/txn_interceptor_span_refresher_test.go, line 105 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-orBmY1i3hg70aA0Pl:-M-p0c5iA5n42K7wXOC0:b-ehq5ek) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c2269a488b9d775f83960ae8f016f66c2808b3d/pkg/kv/txn_interceptor_span_refresher_test.go#L105)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Consider constraining this to something like `br func(roachpb.BatchRequest) *roachpb.BatchResponse` and then require that exactly one of `br` and `pErr` are set.

Then you can also keep the assertions in `onFirstSend` below.
</blockquote></details>

I've added an assertion that exactly one of the two is set. And I've re-instituted those assertions. But I've kept the signature.
___
*[pkg/kv/txn_interceptor_span_refresher_test.go, line 187 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-orzQP6SfvYIU8R_Dz:-M-p1Ew200-F4-LTabb-:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c2269a488b9d775f83960ae8f016f66c2808b3d/pkg/kv/txn_interceptor_span_refresher_test.go#L187)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit, just inline this: `ba.Header = roachpb.Header{Txn: txn.Clone()}`
</blockquote></details>

done
___
*[pkg/storage/replica_test.go, line 4513 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-M-_wcLKBnYNzo9nu59W:-M-p1hYw8uPT1BvmDKPH:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/f07bd5f7657052a08642ceef90f3562ecf2b2afa/pkg/storage/replica_test.go#L4513)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did you mean to leave both comments?
</blockquote></details>

fixed

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r17, 15 of 15 files at r18.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-:-M-piSeS2DWb9FM7_gy5:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-:-M-uxIyM0xqb7-GjgqT7:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44654#-:-M-w-d6D3oLfUYX3WHP7:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

**Pull request merged**
