### PR TITLE
storage: stop returning NotLeaseHolderError from (*Store).RangeFeed

### PR DESCRIPTION
**Pull request by danhhz**
(*Store).Send has an optimization for uninitialized replicas to send
back a NotLeaseHolderError with a hint of where an initialized replica
might be found. RangeFeeds can always be served from followers and so
don't otherwise return NotLeaseHolderError. This commit changes the
corresponding codepath in (*Store).Send to return a RangeNotFoundError
instead.

Touches #36077

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm: nice, this looks better.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37099#-:-LdGlNh6DGNBqyIr8VKx:b59gvps)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by danhhz** [comment]
TFTR! master + this PR (+ some error.Wrap and log debugging) has been running cdc/crdb-chaos for 2h34m without a failure, which is longer than it usually goes. there still may be other issues to find, but seems like this fix is doing what we think

bors r=nvanbenschoten

**Comment by danhhz** [comment]
Flake is #37085.

bors r=nvanbenschoten

**Comment by danhhz** [comment]
Ugh, I meant "(*Store).RangeFeed" in that last sentence in both the commit message and PR description.

**Pull request merged**
