### PR TITLE
bazel: don't use different `gotags` for test and non-test scenarios

### LINKED ISSUE #71857: bazel: low cache utilization between builds and tests
**Describe the problem**

I'm observing that the build artifacts from a `{dev,bazel} build` are not being used by `{dev,bazel} test` and vice-versa. When going from building the full cockroach-short binary to running a specific test, the build cache is trampled upon by each command with the results no longer usable by the other or by itself afterwards. This is surprising, is it because of the differing `.bazelrc` configs between the two? Something else?

**To Reproduce**

Some numbers from my machine, I'm seeing each step start the build from scratch(-ish) without achieving much cache utilization.

```sh
$ dev test pkg/spanconfig/spanconfigstore # 116.655s
$ dev build cockroach-short               # 210.004s
$ dev test pkg/spanconfig/spanconfigstore # 97.852s
$ dev build cockroach-short               # 176.392s
```

Here are two profiles (open using chrome://tracing), they show that we're pretty much starting from scratch each time.
- [dev.gz](https://github.com/cockroachdb/cockroach/files/7394095/dev.gz) (for an unexpected long build step)
- [test.gz](https://github.com/cockroachdb/cockroach/files/7394096/test.gz) (ditto, for test)

**Expected behavior**

Build artifacts from a `dev build cockroach-short` should be re-usable for tests and vice-versa.

Epic CRDB-8036

### PR DESCRIPTION
**Pull request by rickystewart**
In a couple different places in-tree we use the build tags `crdb_test`
and `crdb_test_off` to support conditional compilation. Unfortunately,
this results in low cache utilization when swapping between builds and
tests, since recompiling with different `gotags` causes Bazel to
recompile EVERYTHING, including the entire standard library, with these
different tags. This means that you can't build `cockroach` and then run
a quick test using cached build artifacts, for example.

Fix this by adding a new configuration, `//build/toolchains:crdb_test`.
We use `select()` in `pkg/util/buildutil/BUILD.bazel` to choose between
`crdb_test_on.go` and `crdb_test_off.go` accordingly.

Also add logic to `build/bazelutil/check.sh` to detect new uses of these
build constraints and warn people that the logic also needs to be
Bazelfied.

Closes #71857.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Cool! What will be the outcome caching-wise with this change? The files that (directly or indirectly) depend on the `util` package will be recompiled when we switch between builds and tests? It might be worthwhile to separate the code further into a tiny subpackage to reduce that surface.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72838#-:-MoehKJUBjGTXUyDmQY0:b-b71789)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rail and @rickystewart)

___
*[build/bazelutil/check.sh, line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72838#-Moeh-HR-ja5x3p9-gpZ:-Moeh-HR-ja5x3p9-gp_:btoq6x0) ([raw file](https://github.com/cockroachdb/cockroach/blob/d252d9876ae5e9f7f20b4e85dcac4e1a7f86b533/build/bazelutil/check.sh#L103)):*
> ```Shell
> git grep '//go:build' pkg | grep crdb_test | while read LINE; do
>     if [[ "$EXISTING_CRDB_TEST_BUILD_CONSTRAINTS" == *"$LINE"* ]]; then
> 	# Grandfathered.
> ```

[nit] tabs

**Comment by rickystewart** [comment]
> Cool! What will be the outcome caching-wise with this change? The files that (directly or indirectly) depend on the `util` package will be recompiled when we switch between builds and tests? 

No, actually. The nice part about using `x_defs` for this is that nothing is recompiled, and instead it [only requires the binary](https://github.com/bazelbuild/rules_go/blob/master/go/core.rst#defines-and-stamping) to be re-linked:

> This means that changing a value results only in re-linking, not re-compilation and thus does not cause cascading changes.

> [nit] tabs

Fixed.

**Comment by rickystewart** [comment]
Re-compilation would still be required for everything that depends on `pkg/sql/opt/props` or `pkg/sql/opt/memo`, though. But because the list of sources is conditional on the test configuration, we can't avoid that.

**Review by RaduBerinde — COMMENTED** [review]
Ah.. you are changing it from a `const` to a `var`..

The assumption has been that when you do `if util.CrdbTestBuild { ... }` then the code is statically elided altogether in non-test builds. It is meant to be a zero cost assertion.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72838#-:-MoekKCMDkH3C4gLTCyR:bbnwpz0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rail and @rickystewart)

**Comment by rickystewart** [comment]
> The assumption has been that when you do if util.CrdbTestBuild { ... } then the code is statically elided altogether in non-test builds. It is meant to be a zero cost assertion.

Is that static elision guaranteed/validated anywhere? Or is it just an assumption that the compiler is smart enough to do this?

I can do conditional compilation for these files too, you'll just see much worse caching since now everything that depends on `pkg/util` will indeed have to be recompiled when swapping between build and test, as you hypothesized above.

**Comment by petermattis** [comment]
> Is that static elision guaranteed/validated anywhere? Or is it just an assumption that the compiler is smart enough to do this?

Pretty much every reasonable compiler for the last 5-10 years has statically elided unreachable code. The Go compiler definitely does so.

> We could decide to move the CrdbTestBuild constant, conditionally compiled, into its own small package, like Radu suggests. That way, only packages that depend on it would need to be recompiled, rather than everyone who imports util.

To make sure I understand: the bazel caching will cache both versions where the tag is set and where it is unset, right? So if you `dev test; dev build; dev test`, it isn't going to recompile again on the second `dev test`.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72838)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rail and @rickystewart)

___
*[pkg/sql/opt/memo/BUILD.bazel, line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72838#-MoexAuA0QNy5WIqHKRg:-MoexAuA0QNy5WIqHKRh:b-ergu1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/370d1acf0aaf7299289b99bfc06fac7ed0d85fcb/pkg/sql/opt/memo/BUILD.bazel#L6)):*
> ```Starlark
>     name = "memo",
>     srcs = [
>         "check_expr.go",
> ```

The use of tags in these files predate the CrdbTestBuild constant. I think it'd be equivalent to keep just one file with no build tags and do `if !util.CrdbTestBuild { return }` first thing in `CheckExpr()` (and `Verify()` etc).

**Comment by rickystewart** [comment]
OK, I made the requested changes. Unfortunately this still thrashes the cache (when you swap between build and test, everything that depends on `pkg/util/buildutil` has to be recompiled, and Bazel can't cache between the two configurations). It just doesn't thrash the cache as badly as before, when EVERYTHING would have to be recompiled.

I still want to get this merged because it's an objective improvement, but there's still work to be done here. I think what we want to do is go with the original approach (where swapping between build and test only requires re-linking) for dev scenarios, but for release builds make sure `CrdbTestBuild` is set to a `const`. Should still be possible with Bazel, I'll just need to shuffle some stuff around. Would that address the concern?

**Review by RaduBerinde — COMMENTED** [review]
We could also just make all dev builds have it set to true, and only release builds set it to false. IMO that would be preferable actually.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72838#-:-Mogaczf7WCalHpEnycS:bjf8t4l)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rail and @rickystewart)

**Review by petermattis — COMMENTED** [review]
> OK, I made the requested changes. Unfortunately this still thrashes the cache (when you swap between build and test, everything that depends on pkg/util/buildutil has to be recompiled, and Bazel can't cache between the two configurations). It just doesn't thrash the cache as badly as before, when EVERYTHING would have to be recompiled.

@rickystewart how does bazel's cache work with regards to go build tags? With `go build`, if I build source using `go build -tags foo` and `go build -tags bar`, I'll end up recompiling everything, but the cache will be populated with both `foo` and `bar` variants. If I then do `go build -tags foo` nothing will be rebuilt. From experimentation it looks like bazel doesn't behave that way which is bad. It means switching between race (which is a build tag) and non-race builds will recompiling everything. Is there some way to teach bazel to put the build tag in the cache key such that it doesn't evict builds with a different cache key? I'm not sure I'm using the correct language here. I'm also quite surprised if this hasn't affected other Go users of bazel.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72838#-:-Moi6s8KDo7n38J5u3oU:b-v8vbli)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rail and @rickystewart)

**Comment by rickystewart** [comment]
> Is there some way to teach bazel to put the build tag in the cache key such that it doesn't evict builds with a different cache key?

Making that change would probably require patching upstream `rules_go` somehow. Not really sure what change would be required. I'll file an issue upstream and we'll go from there.

**Comment by rickystewart** [comment]
OK, so this latest version of the patch uses `crdb_test_on.go` or `crdb_test_off.go` accordingly for `opt` builds. For `dbg` or `fastbuild` builds, we instead use `crdb_test_dyn.go`, a new file that dynamically sets the value of `CrdbTestBuild` depending on a value passed in at link time. (Context: builds in Bazel can be built in one of [three compilation modes](https://docs.bazel.build/versions/main/user-manual.html#flag--compilation_mode), which are `fastbuild`, `dbg`, and `opt`. `fastbuild` is the default and `opt` is for optimized builds. Since `fastbuild` is the default, devs will default to using it, so they'll get the "fast-path" behavior. For release we'll use `opt`, obviously, which will get `CrdbTestBuild` as an appropriate `const`. You'll still thrash the cache if you swap between build and test while building w/ `opt`, but presumably if you're building an optimized build you should be ready to deal with slightly longer compile times.)

AFAIC this is ready to merge.

**Review by RaduBerinde — COMMENTED** [review]
Very clever! :lgtm_strong:

Not strictly related to this PR - if it doesn't already, it would be nice if the build version (e.g. what you see in the logs or when you do `SELECT version()`) indicated `fastbuild/dbg` for those builds. That will help reduce confusion if we ever use the wrong build type in some context.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72838#-:-MojsXZsA3A5itKDuyBc:b1mmcyn)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rail and @rickystewart)

___
*[pkg/util/buildutil/BUILD.bazel, line 40 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72838#-MojtR085UdMkEKmdidE:-MojtR085UdMkEKmdidF:b-jdo7t9) ([raw file](https://github.com/cockroachdb/cockroach/blob/acd1f61e79ce864ec1e68da450c23e3162a59173/pkg/util/buildutil/BUILD.bazel#L40)):*
> ```Starlark
>     outs = ["gen-crdb_test_off.go"],
>     cmd = REMOVE_GO_BUILD_CONSTRAINTS,
> )
> ```

Very cool!

**Comment by rickystewart** [comment]
> if it doesn't already, it would be nice if the build version (e.g. what you see in the logs or when you do `SELECT version()`) indicated `fastbuild/dbg` for those builds. That will help reduce confusion if we ever use the wrong build type in some context.

Makes sense to me: #72891

**Comment by rickystewart** [comment]
TFTR :) 

bors r=RaduBerinde

**Comment by rickystewart** [comment]
> Making that change would probably require patching upstream `rules_go` somehow. Not really sure what change would be required. I'll file an issue upstream and we'll go from there.

https://github.com/bazelbuild/rules_go/issues/3012

**Pull request merged**
