### PR TITLE
tenantcostclient: pass next live instance ID

### PR DESCRIPTION
**Pull request by RaduBerinde**
This set of changes adds tracking instances on the server side. The main motivator at this stage is to detect duplicate requests and avoid double-charging in some cases. A secondary motivator is that doing this later will cause headaches during upgrade.

Informs #68479.

#### tenantcostclient: plumb SQL instance and session ID

This commit plumbs the SQL Instance ID and corresponding
sqlliveness.SessionID to the tenant cost controller.

Release note: None

Release justification: Necessary fix for the distributed rate limiting
functionality, which is vital for the upcoming Serverless MVP release.
It allows CRDB to throttle clusters that have run out of free or paid
request units (which measure CPU and I/O usage). This functionality is
only enabled in multi-tenant scenarios and should have no impact on
our dedicated customers.

#### tenantcost: implement request sequence number

This commit adds a monotonic request sequence number for the
TokenBucket API. This is used to detect duplicate requests and avoid
double-charging.

Release note: None

Release justification: Necessary fix for the distributed rate limiting
functionality, which is vital for the upcoming Serverless MVP release.
It allows CRDB to throttle clusters that have run out of free or paid
request units (which measure CPU and I/O usage). This functionality is
only enabled in multi-tenant scenarios and should have no impact on
our dedicated customers.

#### tenantcostserver: cleanup stale instances

This commit implements the server-side logic for cleaning up stale
instances from the tenant_usage table, according to the following
scheme:

 - each tenant sends the ID of the next instance in circular order.
   The live instance set is maintained on the tenant side by a
   separate subsystem.

 - the server uses this information as a "hint" that some instances
   might be stale. When the next ID does not match the expected value,
   a cleanup for a specific instance ID range is triggered. The
   cleanup ultimately checks that the last update is stale, so that
   stale information from the tenant-side doesn't cause incorrect
   removals.

Instances are cleaned up one at a time, with a limit of 10 instance
removals per request. This solution avoids queries that scan ranges of
the table which may contain a lot of tombstones.

Release note: None

Release justification: Necessary fix for the distributed rate limiting
functionality, which is vital for the upcoming Serverless MVP release.
It allows CRDB to throttle clusters that have run out of free or paid
request units (which measure CPU and I/O usage). This functionality is
only enabled in multi-tenant scenarios and should have no impact on
our dedicated customers.

#### tenantcostclient: pass next live instance ID

This change adds reporting of the next live instance ID to the tenant
cost controller.

For now we query the sqlinstance.Provider at most once a minute. This
is temporary until the Provider is changed to a range-feed-driven
cache (##69976).

Release note: None

Release justification: Necessary fix for the distributed rate limiting
functionality, which is vital for the upcoming Serverless MVP release.
It allows CRDB to throttle clusters that have run out of free or paid
request units (which measure CPU and I/O usage). This functionality is
only enabled in multi-tenant scenarios and should have no impact on
our dedicated customers.

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
mod getting the next instance ID, this didn't turn out to be so bad

:lgtm: 

> Reviewed 11 of 11 files at r1, 12 of 12 files at r2, 10 of 10 files at r3, 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70520#-:-Mk9ySi28AZ62dwgGwbP:bokwfmr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @andy-kimball, and @RaduBerinde)

___
*[pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go, line 356 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70520#-Mk9rx5RCoAEbgaMfDvR:-Mk9rsmSE2NnWF2HXzBW:b5kdffm) ([raw file](https://github.com/cockroachdb/cockroach/blob/05548ee0f94b522b327c7b6ebee637979e7de7e1/pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go#L356)):*
> ```Go
> 		TenantID:                    c.tenantID.ToUint64(),
> 		InstanceID:                  uint32(c.instanceID),
> 		InstanceLease:               []byte(c.sessionID),
> ```

`UnsafeBytes()` if you want it
___
*[pkg/ccl/multitenantccl/tenantcostserver/server_test.go, line 267 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70520#-MkA-QXS472gPKu3o0Qk:-MkA-QXS472gPKu3o0Ql:b-t8ol12) ([raw file](https://github.com/cockroachdb/cockroach/blob/59c1f476e1f6ef277721e8f3a6d9d14cbb35fbde/pkg/ccl/multitenantccl/tenantcostserver/server_test.go#L267)):*
> ```
> 	//testutils.SucceedsSoon(t, func() error {
> 	testutils.SucceedsWithin(t, func() error {
> ```
detritus?
___
*[pkg/ccl/multitenantccl/tenantcostserver/system_table.go, line 403 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70520#-Mk9zoPk8JS1FHs77S57:-Mk9zoPk8JS1FHs77S58:b7iarku) ([raw file](https://github.com/cockroachdb/cockroach/blob/59c1f476e1f6ef277721e8f3a6d9d14cbb35fbde/pkg/ccl/multitenantccl/tenantcostserver/system_table.go#L403)):*
> ```Go
> func (h *sysTableHelper) maybeCleanupStaleInstance(
> 	cutoff time.Time, instanceID base.SQLInstanceID,
> ) (ok bool, nextInstance base.SQLInstanceID, _ error) {
> ```

uber-nit: more descriptive name than `ok`, maybe `deleted` or `cleanedUp`?
___
*[pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go, line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70520#-Mk9t8HEB8SmMl-vAQIG:-Mk9t8HEB8SmMl-vAQIH:btxcrce) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6ffcec86f8f49b7b2179591198564888aefb5e5/pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go#L74)):*
> ```Go
> 		if string(instance.Lease) != string(in.InstanceLease) {
> 			// This must be a different incarnation of the same ID. Clear the sequence
> 			// number.
> ```

nit: consider noting also that the client is going to issue its first request at sequence 1, making the choice to set this to 0 work well with the below logic. 
___
*[pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70520#-Mk9tWH_97MlUNa37C8f:-Mk9tWH_97MlUNa37C8g:b-a4forg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6ffcec86f8f49b7b2179591198564888aefb5e5/pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go#L83)):*
> ```Go
> 		// will still consume RUs; we rely on a higher level control loop that
> 		// periodically reconfigures the token bucket to correct such errors.
> 		if instance.Seq == 0 || instance.Seq < in.SeqNum {
> ```

do we need the zero check given the choice to start the client at 1?
___
*[pkg/server/server_sql.go, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70520#-Mk9sGqF2DKpRaw--MdR:-Mk9sGqF2DKpRaw--MdS:bii6xon) ([raw file](https://github.com/cockroachdb/cockroach/blob/05548ee0f94b522b327c7b6ebee637979e7de7e1/pkg/server/server_sql.go#L133)):*
> ```Go
> 	sqlMemMetrics           sql.MemoryMetrics
> 	stmtDiagnosticsRegistry *stmtdiagnostics.Registry
> 	sqlLivenessSessionID    sqlliveness.SessionID
> ```

comment that this will only be populated with a non-zero value on secondary tenants?
___
*[pkg/server/tenant.go, line 490 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70520#-Mk9vx5_AeKfEpeOG8lz:-Mk9vx5_AeKfEpeOG8m-:b6afeax) ([raw file](https://github.com/cockroachdb/cockroach/blob/20cf25ca235cf6faaafcc4c0cbc75c0e33c96d5a/pkg/server/tenant.go#L490)):*
> ```Go
> }
> 
> func makeNextLiveInstanceIDFn(
> ```

cc @rimadeodhar for awareness and to highlight the value of the caching work (which I'll review next, sorry). 
___
*[pkg/server/tenant.go, line 515 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70520#-Mk9wUBD5QE0Ftf2YwKp:-Mk9wUBD5QE0Ftf2YwKq:bdpaf8o) ([raw file](https://github.com/cockroachdb/cockroach/blob/20cf25ca235cf6faaafcc4c0cbc75c0e33c96d5a/pkg/server/tenant.go#L515)):*
> ```Go
> 		}
> 
> 		if now := timeutil.Now(); lastRetrieval.Before(now.Add(-interval)) {
> ```

bad things are going to happen if it takes more than interval to run the fetch, but still it seems like we don't want to kick off concurrent retrievals. 
___
*[pkg/server/tenant.go, line 518 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70520#-Mk9xVNo0jUZuw9gZkVu:-Mk9xVNo0jUZuw9gZkVv:bcmmio3) ([raw file](https://github.com/cockroachdb/cockroach/blob/20cf25ca235cf6faaafcc4c0cbc75c0e33c96d5a/pkg/server/tenant.go#L518)):*
> ```Go
> 			lastRetrieval = now
> 
> 			_ = stopper.RunAsyncTask(ctx, "get-next-live-instance-id", func(ctx context.Context) {
> ```

how do you feel about pulling this closure out above the returned closure. I don't think tying the context together is a particularly good thing. If anything, give it the server's outer context.

**Review by andy-kimball — COMMENTED** [review]
> Reviewed 11 of 11 files at r1, 12 of 12 files at r2, 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70520)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @andy-kimball, and @RaduBerinde)

___
*[pkg/ccl/multitenantccl/tenantcostserver/server.go, line 37 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70520#-Mk99YK6CvVKgiLM9h8K:-Mk99YK6CvVKgiLM9h8L:b-3psg93) ([raw file](https://github.com/cockroachdb/cockroach/blob/59c1f476e1f6ef277721e8f3a6d9d14cbb35fbde/pkg/ccl/multitenantccl/tenantcostserver/server.go#L37)):*
> ```Go
> 	"tenant_usage_instance_inactivity",
> 	"instances that have not reported consumption for longer than this value are cleaned up; "+
> 		"should be at least four times higher than the tenant_cost_control_period of any tenant",
> ```

Instead of making this independently settable, should we derive it from `tenant_cost_control_period` (since it sounds like it's very tied to it)? That'd prevent errors where this gets set to a value < 4x that value. It'd also be one less setting that we have to worry about.
___
*[pkg/ccl/multitenantccl/tenantcostserver/system_table.go, line 406 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70520#-MkA12kr0mVH9jf5JLXb:-MkA12kr0mVH9jf5JLXc:b-b3i1hm) ([raw file](https://github.com/cockroachdb/cockroach/blob/59c1f476e1f6ef277721e8f3a6d9d14cbb35fbde/pkg/ccl/multitenantccl/tenantcostserver/system_table.go#L406)):*
> ```Go
> 	ts := tree.MustMakeDTimestamp(cutoff, time.Microsecond)
> 	row, err := h.ex.QueryRowEx(
> 		h.ctx, "tenant-usage-upsert", h.txn,
> ```

Isn't this a delete, not an upsert?
___
*[pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go, line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70520#-Mk989bWEeix0G0ct1yd:-Mk989bX6HDrRv99XGXg:b-l0m4e7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6ffcec86f8f49b7b2179591198564888aefb5e5/pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go#L81)):*
> ```Go
> 		// Only update consumption if we are sure this is not a duplicate request
> 		// that we already counted. Note that if this is a duplicate request, it
> 		// will still consume RUs; we rely on a higher level control loop that
> ```

I'm a bit confused by "if this is a duplicate request, it will still consume RUs", and yet the if statement is not calling `tenant.Consumption.Add`, so how is it consuming RUs?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70520)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @andy-kimball, and @RaduBerinde)

___
*[pkg/ccl/multitenantccl/tenantcostserver/server.go, line 37 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70520#-Mk99YK6CvVKgiLM9h8K:-MkABiDq3XaeYsTOPXA8:bei8kog) ([raw file](https://github.com/cockroachdb/cockroach/blob/59c1f476e1f6ef277721e8f3a6d9d14cbb35fbde/pkg/ccl/multitenantccl/tenantcostserver/server.go#L37)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Instead of making this independently settable, should we derive it from `tenant_cost_control_period` (since it sounds like it's very tied to it)? That'd prevent errors where this gets set to a value < 4x that value. It'd also be one less setting that we have to worry about.
</blockquote></details>

It's tricky - tenant_cost_control_period comes from the tenant side
___
*[pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go, line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70520#-Mk989bWEeix0G0ct1yd:-MkAByfB3dzTxuWfDphS:b-8hps93) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6ffcec86f8f49b7b2179591198564888aefb5e5/pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go#L81)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I'm a bit confused by "if this is a duplicate request, it will still consume RUs", and yet the if statement is not calling `tenant.Consumption.Add`, so how is it consuming RUs?
</blockquote></details>

It won't show up as consumption, but it consumes burst RUs. Nothing that wouldn't be corrected by the higher level closed loop though

**Comment by andy-kimball** [comment]
___
*[pkg/ccl/multitenantccl/tenantcostserver/server.go, line 37 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70520#-Mk99YK6CvVKgiLM9h8K:-MkA_j8S64GxrP4JnuVz:bk0ezuj) ([raw file](https://github.com/cockroachdb/cockroach/blob/59c1f476e1f6ef277721e8f3a6d9d14cbb35fbde/pkg/ccl/multitenantccl/tenantcostserver/server.go#L37)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It's tricky - tenant_cost_control_period comes from the tenant side
</blockquote></details>

Ah, makes sense.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70520)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andy-kimball, and @RaduBerinde)

___
*[pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go, line 356 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70520#-Mk9rx5RCoAEbgaMfDvR:-MkARS2X6rvrU0aAqgGg:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/05548ee0f94b522b327c7b6ebee637979e7de7e1/pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go#L356)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

`UnsafeBytes()` if you want it
</blockquote></details>

Done
___
*[pkg/ccl/multitenantccl/tenantcostserver/system_table.go, line 403 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70520#-Mk9zoPk8JS1FHs77S57:-MkARk8ICdjxwTv8IyNM:b-izae4t) ([raw file](https://github.com/cockroachdb/cockroach/blob/59c1f476e1f6ef277721e8f3a6d9d14cbb35fbde/pkg/ccl/multitenantccl/tenantcostserver/system_table.go#L403)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

uber-nit: more descriptive name than `ok`, maybe `deleted` or `cleanedUp`?
</blockquote></details>

Changed to `deleted`
___
*[pkg/ccl/multitenantccl/tenantcostserver/system_table.go, line 406 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70520#-MkA12kr0mVH9jf5JLXb:-MkARoJ3CjjEqqWMuazQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/59c1f476e1f6ef277721e8f3a6d9d14cbb35fbde/pkg/ccl/multitenantccl/tenantcostserver/system_table.go#L406)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Isn't this a delete, not an upsert?
</blockquote></details>

Done.
___
*[pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70520#-Mk9tWH_97MlUNa37C8f:-MkASNxcDWHdzcQB1KlR:b-toh8k6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6ffcec86f8f49b7b2179591198564888aefb5e5/pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go#L83)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

do we need the zero check given the choice to start the client at 1?
</blockquote></details>

I was thinking of reasonable behavior with tenants before this change, where the sequence number would stay 0 always. Probably doesn't matter but it was easy enough to do.
___
*[pkg/server/server_sql.go, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70520#-Mk9sGqF2DKpRaw--MdR:-MkATO7lEldOcK6MbeIy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/05548ee0f94b522b327c7b6ebee637979e7de7e1/pkg/server/server_sql.go#L133)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

comment that this will only be populated with a non-zero value on secondary tenants?
</blockquote></details>

Done.
___
*[pkg/server/tenant.go, line 515 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70520#-Mk9wUBD5QE0Ftf2YwKp:-MkAVGWp6VRN5_AusrnZ:b8gj3mz) ([raw file](https://github.com/cockroachdb/cockroach/blob/20cf25ca235cf6faaafcc4c0cbc75c0e33c96d5a/pkg/server/tenant.go#L515)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

bad things are going to happen if it takes more than interval to run the fetch, but still it seems like we don't want to kick off concurrent retrievals. 
</blockquote></details>

Good catch, fixed.
___
*[pkg/server/tenant.go, line 518 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70520#-Mk9xVNo0jUZuw9gZkVu:-MkAVRpK5aykpL9g07k_:b-slfsld) ([raw file](https://github.com/cockroachdb/cockroach/blob/20cf25ca235cf6faaafcc4c0cbc75c0e33c96d5a/pkg/server/tenant.go#L518)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

how do you feel about pulling this closure out above the returned closure. I don't think tying the context together is a particularly good thing. If anything, give it the server's outer context.
</blockquote></details>

I extracted most of it. Let me know if this is what you had in mind for the contexts.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 21 files at r5, 2 of 10 files at r7, 3 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70520#-:-MkCIpPABZP6C-6Qre1v:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @andy-kimball, and @RaduBerinde)

___
*[pkg/server/tenant.go, line 518 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70520#-Mk9xVNo0jUZuw9gZkVu:-MkCI8PLEVxnqL_pZkIR:b2f5ofk) ([raw file](https://github.com/cockroachdb/cockroach/blob/20cf25ca235cf6faaafcc4c0cbc75c0e33c96d5a/pkg/server/tenant.go#L518)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I extracted most of it. Let me know if this is what you had in mind for the contexts.
</blockquote></details>

Yeah, if I had one more nit, it would be to annotate that server context with a log tag like `serverCtx = logtags.AddTag(serverCtx, "get-next-live-instance-id", nil)`

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70520)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andy-kimball, and @RaduBerinde)

___
*[pkg/server/tenant.go, line 518 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70520#-Mk9xVNo0jUZuw9gZkVu:-MkDqzP2BtYu3mRA4ylv:b-7au82e) ([raw file](https://github.com/cockroachdb/cockroach/blob/20cf25ca235cf6faaafcc4c0cbc75c0e33c96d5a/pkg/server/tenant.go#L518)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Yeah, if I had one more nit, it would be to annotate that server context with a log tag like `serverCtx = logtags.AddTag(serverCtx, "get-next-live-instance-id", nil)`
</blockquote></details>

Good idea, done. Feels like RunAsyncTask should do that internally..

**Pull request merged**
