### PR TITLE
sql: add REPLICATION roleoption for replication mode

### PR DESCRIPTION
**Pull request by otan**
These commits add the REPLICATION roleoption (as per PG), and then uses it to authenticate whether a user can use the replication protocol.

Informs #105130

----

# sql: add REPLICATION roleoption

Matches PostgreSQL implementation of the REPLICATION roleoption.

Release note (sql change): Added the REPLICATION role option for a user,
which allows a user to use the streaming replication protocol.

# sql: only allow REPLICATION users to login with replication mode

In PG, the REPLICATION roleoption is required to use streaming
replication mode. Enforce the same constraint.

Release note: None

### CODE REVIEW

**Review by rafiss — COMMENTED** [review]
will do a full review in a bit, but one thing to note: in this 23.2 we want to be making sure there is a system privilege for each role option (even the ones that are PG only).

interestingly, in ccdbc76ac0334e6e0f2570a06125ecd1ecacff7d it seems that we already added a REPLICATION system privilege, for a different purpose. i think it's OK to reuse that name, but when we do the role option checks, we should also be checking the system privilege, like how do `privs.CheckPrivilege(user, privilege.NOSQLLOGIN)` further up in user.go

**Comment by otan** [comment]
nice of you to work on a public holiday 😂 

> interestingly, in https://github.com/cockroachdb/cockroach/commit/ccdbc76ac0334e6e0f2570a06125ecd1ecacff7d it seems that we already added a REPLICATION system privilege, for a different purpose.

gotcha, i added it.

**Comment by stevendanna** [comment]
@otan @rafiss The REPLICATION system privilege is still part of a "private preview" feature, so perhaps we should figure out if we should rename that to avoid any confusion.

**Comment by otan** [comment]
i'm ok to re-use it; the replication privilege can mean anything to do with replication

**Review by rafiss — CHANGES_REQUESTED** [review]
looks good! my comments are all minor

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106082#-:-NZl21PH3xySp0nMW2Ki:br9e9z9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nkodali and @otan)

___
*[`-- commits` line 7 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/106082#-NZl0fzh0FQGwVSbTBWD):*
nit: could the release note mention that there is also a corresponding system privilege
___
*[`pkg/sql/user.go` line 349 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/106082#-NZl0yEnCjC11Emwu-dQ:-NZl0yEo4c_5IbV8U6D2:b-rjgnnh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7733efa827adc970eea2ebeac9bb8a486108ab9c/pkg/sql/user.go#L349)):*
> ```Go
> 			aInfo.CanLoginSQLRoleOpt = false
> 		case "REPLICATION":
> 			fmt.Printf(">>> opt replication\n")
> ```

nit: extra print
___
*[`pkg/sql/pgrepl/connect_test.go` line 70 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/106082#-NZl1wDYDXeqarRzYwTd:-NZl1wDYDXeqarRzYwTe:bf7ddvg) ([raw file](https://github.com/cockroachdb/cockroach/blob/7733efa827adc970eea2ebeac9bb8a486108ab9c/pkg/sql/pgrepl/connect_test.go#L70)):*
> ```Go
> 		t.Run(fmt.Sprintf("hasPrivilege=%t/useRoot=%t/replicationMode=%s", tc.hasPrivilege, tc.useRoot, tc.replicationMode), func(t *testing.T) {
> 			if tc.hasPrivilege {
> 				sqlDB.Exec(t, `ALTER USER testuser REPLICATION`)
> ```

can we do something here to test that the system privilege works too?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106082)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nkodali and @rafiss)

___
*[`pkg/sql/pgrepl/connect_test.go` line 70 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/106082#-NZl1wDYDXeqarRzYwTd:-NZxHwmo37QxyanSGynq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7733efa827adc970eea2ebeac9bb8a486108ab9c/pkg/sql/pgrepl/connect_test.go#L70)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

can we do something here to test that the system privilege works too?
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 1 of 9 files at r5, 9 of 9 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106082)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

**Comment by otan** [comment]
bors r=rafiss

thx!

**Comment by otan** [comment]
bors r-

Rebase drift

**Comment by otan** [comment]
bors r=rafiss

**Pull request merged**
