### PR TITLE
importccl: Parallelize avro import

### LINKED ISSUE #45097: importccl: faster Avro imports
Imports can parse Avro files as of https://github.com/cockroachdb/cockroach/issues/30283 but the speed is not yet optimized.

Outcome of this issue would be to increase Avro speed to an acceptable level--ideally comparable to our fastest Import functionality today. Working with partners to determine sufficient speed will be a part of acceptance of this issue.

### PR DESCRIPTION
**Pull request by miretskiy**
Parallelize avro importer to improve its throughput (2.8x improvement).

Touches #40374.
Fixes #45097.

Release notes (performance): Faster avro import

### CODE REVIEW

**Review by spaskob — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45269)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @spaskob)

___
*[pkg/ccl/importccl/read_import_avro.go, line 232 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45269#-M118mrfArbhtnuw1q_R:-M118mrfArbhtnuw1q_S:b-t5tkj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/48053185b1cec45ad349db046b6e7229d26d4984/pkg/ccl/importccl/read_import_avro.go#L232)):*
> ```Go
> 		return false
> 	}
> 	c.rejected <- fmt.Sprintf("%s\n", row)
> ```

I am confused, isn't avro a binary format? What is the meaning of row in this case?
___
*[pkg/ccl/importccl/read_import_base.go, line 356 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45269#-M119RdY3OcBmGzNIAYr:-M119RdY3OcBmGzNIAYs:bccg77o) ([raw file](https://github.com/cockroachdb/cockroach/blob/48053185b1cec45ad349db046b6e7229d26d4984/pkg/ccl/importccl/read_import_base.go#L356)):*
> ```Go
> type namedInput struct {
> 	reader *fileReader
> 	name   string
> ```

could you add comments what name and idx represent?
___
*[pkg/ccl/importccl/read_import_base.go, line 360 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45269#-M119YtsAcQR44GPaQL2:-M119YtsAcQR44GPaQL3:b-gfq643) ([raw file](https://github.com/cockroachdb/cockroach/blob/48053185b1cec45ad349db046b6e7229d26d4984/pkg/ccl/importccl/read_import_base.go#L360)):*
> ```Go
> }
> 
> // A scanner over avro input.
> ```

why is the comment specific to avro?

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45269)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @spaskob)

___
*[pkg/ccl/importccl/read_import_avro.go, line 232 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45269#-M118mrfArbhtnuw1q_R:-M11ZXD9DcoDz-ov09d-:b9vj2qy) ([raw file](https://github.com/cockroachdb/cockroach/blob/48053185b1cec45ad349db046b6e7229d26d4984/pkg/ccl/importccl/read_import_avro.go#L232)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

I am confused, isn't avro a binary format? What is the meaning of row in this case?
</blockquote></details>

You are not confused; avro may or may not be binary.
However, at this stage, we have read avro input file and converted that input into a native go type
(for example: map, or an array, or a byte array, or an int, etc).  So, i'm just printing that representation of the row that we have failed to handle.

I wonder if I should print %v instead though....
___
*[pkg/ccl/importccl/read_import_base.go, line 356 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45269#-M119RdY3OcBmGzNIAYr:-M11_GT-3ox9i080UFX8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/48053185b1cec45ad349db046b6e7229d26d4984/pkg/ccl/importccl/read_import_base.go#L356)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

could you add comments what name and idx represent?
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/read_import_base.go, line 360 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45269#-M119YtsAcQR44GPaQL2:-M11_6QCExxd3tCTDkkG:b-zf7tcn) ([raw file](https://github.com/cockroachdb/cockroach/blob/48053185b1cec45ad349db046b6e7229d26d4984/pkg/ccl/importccl/read_import_base.go#L360)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

why is the comment specific to avro?
</blockquote></details>

Because of copy & paste.

Updated.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45269)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @spaskob)

___
*[pkg/ccl/importccl/read_import_base.go, line 360 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45269#-M119YtsAcQR44GPaQL2:-M11_xVA2oUUqu7r5wTs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/48053185b1cec45ad349db046b6e7229d26d4984/pkg/ccl/importccl/read_import_base.go#L360)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Because of copy & paste.

Updated.
</blockquote></details>

Done.

**Review by spaskob — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45269)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @spaskob)

___
*[pkg/ccl/importccl/read_import_avro.go, line 232 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45269#-M118mrfArbhtnuw1q_R:-M11gJg-EoKHCq5fJIoq:blk0lq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/48053185b1cec45ad349db046b6e7229d26d4984/pkg/ccl/importccl/read_import_avro.go#L232)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

You are not confused; avro may or may not be binary.
However, at this stage, we have read avro input file and converted that input into a native go type
(for example: map, or an array, or a byte array, or an int, etc).  So, i'm just printing that representation of the row that we have failed to handle.

I wonder if I should print %v instead though....
</blockquote></details>

We may need to discuss how rejected file is going to be used. The initial idea is that it is in the same format as the input so that the user can repeat the import but only reading from the rejected file. If this is not feasible for avro we should reconsider this approach.
___
*[pkg/ccl/importccl/read_import_csv.go, line 82 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45269#-M11kRGL1IBZW5kQPp0p:-M11kRGM1z2Zg_7DL13C:b-oqt6e3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c301037b7a91fa62c971d8201c65a07936af8f4/pkg/ccl/importccl/read_import_csv.go#L82)):*
> ```Go
> }
> 
> func (c *csvInputReader) readFile(
> ```

I wonder if this function can be refactored away in the future as well.
___
*[pkg/ccl/importccl/read_import_csv.go, line 192 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45269#-M11jug98jmmmGHGnL0n:-M11jug98jmmmGHGnL0o:bt9ipco) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c301037b7a91fa62c971d8201c65a07936af8f4/pkg/ccl/importccl/read_import_csv.go#L192)):*
> ```Go
> 				col := conv.VisibleCols[i]
> 				err = wrapRowErr(err, s.input.name, rowNum, pgcode.Syntax,
> 					"parse %q as %s", col.Name, col.Type.SQLString())
> ```

I wonder if we should also include the field in the error message.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45269)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @spaskob)

___
*[pkg/ccl/importccl/read_import_avro.go, line 232 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45269#-M118mrfArbhtnuw1q_R:-M11vhF6B7r71ALWSxEY:b-45vdgn) ([raw file](https://github.com/cockroachdb/cockroach/blob/48053185b1cec45ad349db046b6e7229d26d4984/pkg/ccl/importccl/read_import_avro.go#L232)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

We may need to discuss how rejected file is going to be used. The initial idea is that it is in the same format as the input so that the user can repeat the import but only reading from the rejected file. If this is not feasible for avro we should reconsider this approach.
</blockquote></details>

It's not feasible for avro.
___
*[pkg/ccl/importccl/read_import_csv.go, line 82 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45269#-M11kRGL1IBZW5kQPp0p:-M11vvZI7PACYnsxABW4:bcj79pb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c301037b7a91fa62c971d8201c65a07936af8f4/pkg/ccl/importccl/read_import_csv.go#L82)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

I wonder if this function can be refactored away in the future as well.
</blockquote></details>

perhaps... Not sure if it's possible to refactor e.g. mysqldump or pgdump formats,
but perhaps move this to parallelImporter in base and just call that
___
*[pkg/ccl/importccl/read_import_csv.go, line 192 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45269#-M11jug98jmmmGHGnL0n:-M11wGNbBpj8Q5KhXd28:b-8o4w68) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c301037b7a91fa62c971d8201c65a07936af8f4/pkg/ccl/importccl/read_import_csv.go#L192)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

I wonder if we should also include the field in the error message.
</blockquote></details>

Perhaps -- I tried to keep things the same where possible. if you want, I can change this err message.

**Comment by miretskiy** [comment]
@spaskob  @dt 
finally: all ci builds are green. I found some issues (through existing tests), which I have fixed in avro records handling.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45269)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @spaskob)

___
*[pkg/ccl/importccl/read_import_avro.go, line 232 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45269#-M118mrfArbhtnuw1q_R:-M13FOLK4652LdAQvR17:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/48053185b1cec45ad349db046b6e7229d26d4984/pkg/ccl/importccl/read_import_avro.go#L232)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

It's not feasible for avro.
</blockquote></details>

Done.

**Comment by miretskiy** [comment]
@dt @spaskob please review latest revision.  Thanks.

**Review by dt — COMMENTED** [review]
> Reviewed 6 of 10 files at r1, 4 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45269)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @spaskob)

___
*[pkg/ccl/importccl/read_import_base.go, line 431 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45269#-M1OtlmsESPZVudDRdfY:-M1OtlmsESPZVudDRdfZ:bdomkys) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc533158d66ac06e6ddd7cde0783a9936faba8f9/pkg/ccl/importccl/read_import_base.go#L431)):*
> ```Go
> 	Scan() bool
> 
> 	// Err returns an error (if any) encountered when processing avro stream.
> ```

avro mentioned in comment
___
*[pkg/ccl/importccl/read_import_base.go, line 523 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45269#-M1Omr4O8nif9ZZMzLAp:-M1Omr4PBMRZ-liJeAbL:bcyn303) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc533158d66ac06e6ddd7cde0783a9936faba8f9/pkg/ccl/importccl/read_import_base.go#L523)):*
> ```Go
> 			// Scan more data, unless we're done.
> 			select {
> 			case <-ctx.Done():
> ```

I'm surprised this didn't show up in profiling, but `.Done()` in hot loops is usually performance problem -- we usually pull it into local above the loop `done := ctx.Done()` and even then sometimes even avoid checking the ch on every iteration as it is still somewhat expensive (i believe the prior CSV code only checked it on flushes).
___
*[pkg/ccl/importccl/read_import_base.go, line 568 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45269#-M1OoBqG7dTrmCCjvhgR:-M1OoBqG7dTrmCCjvhgS:bem531c) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc533158d66ac06e6ddd7cde0783a9936faba8f9/pkg/ccl/importccl/read_import_base.go#L568)):*
> ```Go
> 	p.b.data = append(p.b.data, data)
> 
> 	if len(p.b.data) == cap(p.b.data) {
> ```

this seems brittle, or at least subtle -- i had to read this a couple times before I'd convinced myself that this would actually behave correctly, i.e. that append or something else would never re-alloc the batch. IMO it'd be clearer just to add `batchSize` as a field on p.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45269)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @spaskob)

___
*[pkg/ccl/importccl/read_import_base.go, line 431 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45269#-M1OtlmsESPZVudDRdfY:-M1R6FQ38rceEAODaunQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc533158d66ac06e6ddd7cde0783a9936faba8f9/pkg/ccl/importccl/read_import_base.go#L431)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

avro mentioned in comment
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/read_import_base.go, line 523 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45269#-M1Omr4O8nif9ZZMzLAp:-M1R6T7yDgPbT8sXxBJl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc533158d66ac06e6ddd7cde0783a9936faba8f9/pkg/ccl/importccl/read_import_base.go#L523)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I'm surprised this didn't show up in profiling, but `.Done()` in hot loops is usually performance problem -- we usually pull it into local above the loop `done := ctx.Done()` and even then sometimes even avoid checking the ch on every iteration as it is still somewhat expensive (i believe the prior CSV code only checked it on flushes).
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/read_import_base.go, line 568 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45269#-M1OoBqG7dTrmCCjvhgR:-M1R6YQXEzn0tURCM6V6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc533158d66ac06e6ddd7cde0783a9936faba8f9/pkg/ccl/importccl/read_import_base.go#L568)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

this seems brittle, or at least subtle -- i had to read this a couple times before I'd convinced myself that this would actually behave correctly, i.e. that append or something else would never re-alloc the batch. IMO it'd be clearer just to add `batchSize` as a field on p. 
</blockquote></details>

Done.

**Review by spaskob — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45269)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @spaskob)

___
*[pkg/ccl/importccl/read_import_csv.go, line 192 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45269#-M11jug98jmmmGHGnL0n:-M1RY748APpJj-gvAFZl:b-q8ycvs) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c301037b7a91fa62c971d8201c65a07936af8f4/pkg/ccl/importccl/read_import_csv.go#L192)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Perhaps -- I tried to keep things the same where possible. if you want, I can change this err message.
</blockquote></details>

You have 4 things to show but only 2 placeholders

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45269)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @spaskob)

___
*[pkg/ccl/importccl/read_import_base.go, line 523 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45269#-M1Omr4O8nif9ZZMzLAp:-M1RB3HJC4HRjCbHAL8o:bhwytbp) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc533158d66ac06e6ddd7cde0783a9936faba8f9/pkg/ccl/importccl/read_import_base.go#L523)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Good point.  Removed, and, as per your suggestion moved to flush.
___
*[pkg/ccl/importccl/read_import_csv.go, line 192 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45269#-M11jug98jmmmGHGnL0n:-M1RczAK-lstsTSaVYXh:byr2gab) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c301037b7a91fa62c971d8201c65a07936af8f4/pkg/ccl/importccl/read_import_csv.go#L192)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

You have 4 things to show but only 2 placeholders
</blockquote></details>

You misread the code a bit; I've changed line wrapping to make it clear that i'm calling a function with 3 arguments (one of which is an error constructed with Wrapf(...))

**Comment by miretskiy** [comment]
I reran and updated before/after benchmark for csv import.  Refactoring and introduction of the interface{} (instead of the string) didn't have a significant impact:
benchstat  ~/before.txt ~/after.txt
name              old time/op    new time/op    delta
ConvertRecord-16    2.27µs ±11%    2.29µs ± 8%    ~     (p=0.494 n=10+10)

name              old speed      new speed      delta
ConvertRecord-16  53.0MB/s ±12%  52.5MB/s ± 9%    ~     (p=0.494 n=10+10)

name              old alloc/op   new alloc/op   delta
ConvertRecord-16    3.63kB ± 0%    3.61kB ± 0%  -0.68%  (p=0.000 n=9+9)

name              old allocs/op  new allocs/op  delta
ConvertRecord-16       100 ± 0%       101 ± 0%  +1.00%  (p=0.000 n=10+10)

**Pull request merged**
