### PR TITLE
sql: change how DistSQL returns info on mistmatched ranges 

### PR DESCRIPTION
**Pull request by andreimatei**
DistSQL returns information to the gateway about ranges that were
expected to be local to a TableReader and friends but weren't. The
gateway is expected to update its range cache with this info.
Before this patch, a TableReader would collect info about the descriptor
and lease of the ranges it read. This was done through the
batch.ReturnRangeInfo flag, which was plumbed through the many layers or
row/kv fetchers. This flag is going away (separately from this PR), and
so this PR switches DistSQL to doing something else. Besides, plumbing
the requirement to get that range information everywhere was very noisy
and hadn't be done very well - a lot of fetchers created by randos that
didn't end up needing said information were also collecting it.

Instead, the TableReader now uses the local range cache to return info
on all the non-local ranges. The local range cache is expected to be up
to date for the respective ranges since they've just been read. DistSQL
using the local cache ends up being a lot cleaner.

Release note: None

### CODE REVIEW

**Comment by andreimatei** [comment]
Only the last commit is to be review here, the rest are https://reviewable.io/reviews/cockroachdb/cockroach/51227

**Review by yuzefovich — COMMENTED** [review]
4th commit LGTM, but it's probably worth for Nathan to take a look as well.

> Reviewed 22 of 22 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51318#-:-MC7yhBZB2NDmeGY0gww:b-5fda3g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @nvanbenschoten, and @yuzefovich)

___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 507 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51318#-MC7wc7bA16Ga8TUEHuk:-MC7w0KE0_Miz9ndO8M5:bs95qnl) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d56103cfeb862c3957e9a74d37da5544c0e3e75/pkg/kv/kvclient/kvcoord/range_cache.go#L507)):*
> ```Go
> 	// We iterate from the range meta key after RangeMetaKey(desc.StartKey) to the
> 	// end of the key space and we stop when we hit a descriptor to the right of
> 	// newEntry. Notice the Next() we use for the start key to avoid clearing the
> ```

nit: what is `newEntry` here?
___
*[pkg/sql/execinfra/readerbase.go, line 90 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51318#-MC7x_iDAdZpCK9nsw4Q:-MC7x_iDAdZpCK9nsw4R:b-xhqv1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d56103cfeb862c3957e9a74d37da5544c0e3e75/pkg/sql/execinfra/readerbase.go#L90)):*
> ```Go
> 
> 	for _, ri := range overlapping {
> 		// Ranges with unknown leases are returned.
> ```

What is "unknown" about leases on this ranges?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51318)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @yuzefovich)

___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 507 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51318#-MC7wc7bA16Ga8TUEHuk:-MC82TUn6T5g6rQG2D1O:b-r4hl4m) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d56103cfeb862c3957e9a74d37da5544c0e3e75/pkg/kv/kvclient/kvcoord/range_cache.go#L507)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: what is `newEntry` here?
</blockquote></details>

fixed, that's now `span`
___
*[pkg/sql/execinfra/readerbase.go, line 90 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51318#-MC7x_iDAdZpCK9nsw4Q:-MC82ZpOCKATKxpxjueb:b23mu5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d56103cfeb862c3957e9a74d37da5544c0e3e75/pkg/sql/execinfra/readerbase.go#L90)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

What is "unknown" about leases on this ranges?
</blockquote></details>

well `ri.Lease` can be empty - the cache can have a descriptor without a lease. I've decided to change this, btw, and don't return these ranges. The local cache not having a lease is not necessarily an indication that the gateway had stale information, so I now think it's better to not send anything back about these guys.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51318)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 512 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/51318#-MC842Od722vEFKCFz0d:-MC842Od722vEFKCFz0e:bxhy9ce) ([raw file](https://github.com/cockroachdb/cockroach/blob/15306def4017442b443e4f892206a4abb4a936f4/pkg/kv/kvclient/kvcoord/range_cache.go#L512)):*
> ```Go
> 		cached := rdc.getValue(e)
> 		// Stop when we hit a descriptor to the right of newEntry. The end key is
> 		// exclusive, so if newEntry is [a,b) and we hit [b,c), we stop.
> ```

ditto for `newEntry`.

**Review by nvb — APPROVED** [review]
:lgtm_strong: nice change! I'm a little surprised this didn't break any tests though. Is there a gap in testing around this logic? Should we be trying to improve it?

> Reviewed 19 of 22 files at r4, 3 of 5 files at r5, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51318#-:-MCEJXQM8VETL9zcZka9:blepasl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 499 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/51318#-MCEIAcH18mEX-tRpLii:-MCEIAcH18mEX-tRpLij:b-946ba8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4961bbd3666e529feaaeb7aeddbf62203dcbe552/pkg/kv/kvclient/kvcoord/range_cache.go#L499)):*
> ```Go
> }
> 
> func (rdc *RangeDescriptorCache) getCachedOverlappingLocked(
> ```

`getCachedOverlappingRLocked`
___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 989 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/51318#-MCEIQwIEaRbY7rYYCPI:-MCEIQwIEaRbY7rYYCPJ:b-au0nzs) ([raw file](https://github.com/cockroachdb/cockroach/blob/4961bbd3666e529feaaeb7aeddbf62203dcbe552/pkg/kv/kvclient/kvcoord/range_cache.go#L989)):*
> ```Go
> 		entry := rdc.getValue(e)
> 		if newEntry.NewerThan(entry) {
> 			entriesToEvict = append(entriesToEvict, e)
> ```

Do we need this slice anymore? Now that we're pulling everything into the `overlapping` slice, I think we can just evict directly in this loop. The problem was evicting while in `DoRangeEntry`.
___
*[pkg/sql/execinfra/readerbase.go, line 75 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/51318#-MCEIyPo6xQ7zSRlS0te:-MCEIyPo6xQ7zSRlS0tf:b-nzvzx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4961bbd3666e529feaaeb7aeddbf62203dcbe552/pkg/sql/execinfra/readerbase.go#L75)):*
> ```Go
> ) (misplannedRanges []roachpb.RangeInfo) {
> 	log.VEvent(ctx, 2, "checking range cache to see if range info updates should be communicated to the gateway")
> 	var overlapping []*kvbase.RangeCacheEntry
> ```

Any reason to build up this larger slice instead of nesting the iterations? Seems wasteful.
___
*[pkg/sql/execinfra/readerbase.go, line 90 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/51318#-MCEJ7qR40dZnyJdYl00:-MCEJ7qR40dZnyJdYl01:b-hrkl65) ([raw file](https://github.com/cockroachdb/cockroach/blob/4961bbd3666e529feaaeb7aeddbf62203dcbe552/pkg/sql/execinfra/readerbase.go#L90)):*
> ```Go
> 
> 	for _, ri := range overlapping {
> 		// Ranges with unknown leases are not returned, as the current node might
> ```

`// Ranges with unknown leases are included in the result.`

`// Ranges with unknown leases are not returned.`

Someone's lying here.

**Review by andreimatei — COMMENTED** [review]
> I'm a little surprised this didn't break any tests though. Is there a gap in testing around this logic? Should we be trying to improve it?

I did actually run into more tests around this than I thought there would be :P. I was satisfied enough.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51318#-:-MCEUhpP30XFutsiy98j:bskd5v7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @yuzefovich)

___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 512 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/51318#-MC842Od722vEFKCFz0d:-MCESg4z2n0ZolE8GsHG:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/15306def4017442b443e4f892206a4abb4a936f4/pkg/kv/kvclient/kvcoord/range_cache.go#L512)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

ditto for `newEntry`.
</blockquote></details>

done
___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 499 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/51318#-MCEIAcH18mEX-tRpLii:-MCESb_50b6RN8dhCLFr:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4961bbd3666e529feaaeb7aeddbf62203dcbe552/pkg/kv/kvclient/kvcoord/range_cache.go#L499)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`getCachedOverlappingRLocked`
</blockquote></details>

done
___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 989 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/51318#-MCEIQwIEaRbY7rYYCPI:-MCETD5O3vbqgjMvSxfc:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4961bbd3666e529feaaeb7aeddbf62203dcbe552/pkg/kv/kvclient/kvcoord/range_cache.go#L989)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need this slice anymore? Now that we're pulling everything into the `overlapping` slice, I think we can just evict directly in this loop. The problem was evicting while in `DoRangeEntry`.
</blockquote></details>

done
___
*[pkg/sql/execinfra/readerbase.go, line 75 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/51318#-MCEIyPo6xQ7zSRlS0te:-MCEUSDtAXHG1cYHcqux:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4961bbd3666e529feaaeb7aeddbf62203dcbe552/pkg/sql/execinfra/readerbase.go#L75)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Any reason to build up this larger slice instead of nesting the iterations? Seems wasteful.
</blockquote></details>

done
___
*[pkg/sql/execinfra/readerbase.go, line 90 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/51318#-MCEJ7qR40dZnyJdYl00:-MCEUSpk5glHGWYbtEcE:b-fq9gfh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4961bbd3666e529feaaeb7aeddbf62203dcbe552/pkg/sql/execinfra/readerbase.go#L90)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`// Ranges with unknown leases are included in the result.`

`// Ranges with unknown leases are not returned.`

Someone's lying here.
</blockquote></details>

I had changed my mind and forgot one of the comments. Fixed. We are *not* returning unknown leases.

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51318#-:-MCEdv1c1LeR9F3NBHnJ:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @yuzefovich)

**Pull request merged**
