### PR TITLE
sqlsmith: stop ignoring a decimal error

### LINKED ISSUE #40929: sql: internal error: (-0E-2019):::DECIMAL: could not evaluate -0E-2019 as Datum type DDecimal from string "0E-2019": could not parse "0E-2019" as type decimal
```
CREATE TABLE IF NOT EXISTS tab_orig AS
	SELECT g FROM generate_series(NULL, NULL) AS g;

SELECT 0 / '-Infinity'::DECIMAL FROM tab_orig;
```

```
stack trace:
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/expr.go:78: processExpression()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/expr.go:161: Init()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:145: Init()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:776: InitWithEvalCtx()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:752: Init()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/tablereader.go:92: newTableReader()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/processors.go:138: NewProcessor()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowflow/row_based_flow.go:165: makeProcessor()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowflow/row_based_flow.go:65: setupProcessors()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowflow/row_based_flow.go:48: Setup()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql/server.go:331: setupFlow()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql/server.go:404: SetupLocalSyncFlow()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:241: setupFlows()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:330: Run()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:966: PlanAndRun()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:826: execWithDistSQLEngine()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:718: dispatchToExecutionEngine()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:417: execStmtInOpenState()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:98: execStmt()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1238: execCmd()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1167: run()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:444: ServeConn()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:584: func1()
runtime/asm_amd64.s:1337: goexit()
```

Jira issue: CRDB-5499

### PR DESCRIPTION
**Pull request by rafiss**
Resolves #40929

The error being referenced no longer occurs.

Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
Huh, I'm curious what fixed this :)

:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71015#-:-MkxPT2b9uZhcz9ILh4v:bviaxl8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss)

**Comment by rafiss** [comment]
i also am curious... but i don't feel like bisecting it now :P 

i realized i should add a test for this case though, so will do that

**Comment by rafiss** [comment]
bors r=yuzefovich

**Comment by rafiss** [comment]
nevermind, the error still happens under fakedist configuration. sorry, i thought i had tested that.

**Pull request closed without merging**
