### PR TITLE
Fix "make install" target

### PR DESCRIPTION
**Pull request by ltworf**
The `make install` target uses DESTDIR to know where to install, so the variable is needed.

Without this change, the `make install` as `dpkg-buildpackage` runs it will fail.

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41799#-:-LrnCC0JDOoe7Ji8on2e:bg7igk9)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by ltworf** [comment]
Unfortunately I can't access the failed test so I got no idea of what is wrong with tis.

**Comment by petermattis** [comment]
Oh, I had forgotten that `variables.mk` is automatically generated. See the `build/variables.mk` target. Rather than editing `variables.mk` directly, I think you want to add a `DESTDIR := ` line to the `Makefile` along with a comment.

**Comment by ltworf** [comment]
Seems both were needed. Fixed.

**Review by petermattis — COMMENTED** [review]
> Seems both were needed. Fixed.

Right. Both are needed, though if you added the variable to `Makefile`, the next time you run `make` it would regenerate `build/variables.mk`. Thanks for the fix!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41799#-:-LrnVh7V74Q7lwh0Zgnd:bod2ka3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
