### PR TITLE
sql,opt: support locality optimized semi, inner, and left lookup joins

### LINKED ISSUE #64870: opt, sql: locality optimized semi, inner, and left lookup joins
A locality optimized lookup join is a lookup join in which each lookup is known to produce a limited number of rows, and it is planned such that local nodes (those in the same region as the gateway) are searched for those rows before remote nodes. If all rows are found locally, there is no need for the execution engine to communicate with remote nodes. This can significantly reduce the latency of queries in a multi-region cluster.

https://github.com/cockroachdb/cockroach/pull/63044 added support for locality optimized anti lookup joins, but we do not yet support locality optimized semi, inner, or left lookup joins. Due to the special semantics of anti joins, it was possible to support locality optimized anti lookup joins simply by adding a transformation rule in the optimizer. No changes to the execution engine were required. 

Supporting the other types of joins will require both optimizer and execution changes, however. On the optimizer side, we'll need to plan a single lookup join that has two types of join predicates: local and remote. On the execution side, we'll need to use the local join predicate to first look up data locally, and if it's not found, use the remote join predicate to look up data remotely.

A previous prototype in https://github.com/cockroachdb/cockroach/pull/62248 explored an alternative approach, which duplicated the entire lookup join operation and used a limited `UNION ALL` (similar to our approach for locality optimized scans) to combine the results. This approach had a problem, though, which was that it needed to buffer the input rows for the lookup join so they would be available to both sides of the `UNION ALL`. This caused problems in mutation queries, where the execution engine tried to run buffered subqueries that use mutation output _before_ the mutation query. Buffering also reduces performance, so it's best avoided if possible.

See the original issue for more context and details: #55185.

### PR DESCRIPTION
**Pull request by rytaft**
This commit updates the optimizer and execution engine to add support for
locality optimized semi, inner, and left lookup joins. On the optimizer side,
this involves a new rule, `GenerateLocalityOptimizedLookupJoin`. On the
execution side, this involves modifications to the `joinReader` processor to
support locality optimized search.

`GenerateLocalityOptimizedLookupJoin` converts a semi, inner, or left lookup
join into a locality optimized lookup join (anti joins are handled by
`GenerateLocalityOptimizedAntiJoin`). A locality optimized lookup join is
designed to avoid communicating with remote nodes (relative to the gateway
region) if at all possible.

A locality optimized lookup join can be planned under the following
conditions:
 - Each lookup is known to produce at most one row.
 - The lookup join scans multiple spans in the lookup index for each input
   row, with some spans targeting partitions on local nodes (relative to the
   gateway region), and some targeting partitions on remote nodes. It is not
   known which span(s) will contain the matching row(s).

The result of `GenerateLocalityOptimizedLookupJoin` will be a lookup join with
two different sets of lookup conditions: one set targeting the local values
from the original join, and the other targeting the remote values. For each
input row, the execution engine will use the local conditions first to perform
the lookup, and if a matching row is found in the index, there is no need to
use the remote conditions. If all input rows have local matches, the execution
engine will never need to communicate with remote nodes.

This is a useful optimization if there is locality of access in the workload,
such that rows tend to be accessed from the region where they are located. If
there is no locality of access, using a locality optimized lookup join could be
a slight pessimization, since rows residing in remote regions will be found
slightly more slowly than they would be otherwise.

For example, suppose we have a multi-region database with regions 'us-east1',
'us-west1' and 'europe-west1', and we have the following tables and query,
issued from 'us-east1':
```
  CREATE TABLE parent (
    p_id INT PRIMARY KEY
  ) LOCALITY REGIONAL BY ROW;

  CREATE TABLE child (
    c_id INT PRIMARY KEY,
    c_p_id INT REFERENCES parent (p_id)
  ) LOCALITY REGIONAL BY ROW;

  SELECT * FROM parent, child WHERE c_id = 10 AND p_id = c_p_id;
```
Normally, this would produce the following plan:
```
  inner-join (lookup parent)
   ├── lookup columns are key
   ├── lookup expr: (p_id = c_p_id) AND (crdb_region IN ('europe-west1', 'us-east1', 'us-west1'))
   ├── scan child
   │    └── constraint: /7/5
   │         ├── [/'europe-west1'/10 - /'europe-west1'/10]
   │         ├── [/'us-east1'/10 - /'us-east1'/10]
   │         └── [/'us-west1'/10 - /'us-west1'/10]
   └── filters (true)
```
but if the session setting `locality_optimized_partitioned_index_scan` is enabled,
the optimizer will produce this plan, using locality optimized search, both for
the scan of child and for the lookup join with parent. See the rule
`GenerateLocalityOptimizedScan` for details about how the optimization is applied
for scans.
```
  inner-join (lookup parent)
   ├── lookup columns are key
   ├── lookup expr: (p_id = c_p_id) AND (crdb_region = 'us-east1')
   ├── remote lookup expr: (p_id = c_p_id) AND (crdb_region IN ('europe-west1', 'us-west1'))
   ├── locality-optimized-search
   │    ├── scan child
   │    │    └── constraint: /13/11: [/'us-east1'/10 - /'us-east1'/10]
   │    └── scan child
   │         └── constraint: /18/16
   │              ├── [/'europe-west1'/10 - /'europe-west1'/10]
   │              └── [/'us-west1'/10 - /'us-west1'/10]
   └── filters (true)
```
As long as `child.c_id = 10` and the matching row in parent are both located in
'us-east1', the second plan will be much faster. But if they are located in
one of the other regions, the first plan would be slightly faster.

Once the execution engine receives this plan, the existence of a remote lookup
expression is a signal to use locality optimized search. To support locality
optimized search, this commit adds a new `joinReaderSpanGenerator`, called
`localityOptimizedSpanGenerator`. The `localityOptimizedSpanGenerator` has two
`multiSpanGenerators`, one for generating spans that target local nodes
(initialized with the `LookupExpr`), and one for generating spans that target
remote nodes (initialized with the `RemoteLookupExpr`).

At the end of processing each batch, if locality optimized search is enabled,
the `joinReader` checks whether all input rows had local matches. If not all rows
had matches, it uses the `localityOptimizedSpanGenerator` to generate remote
spans, and performs another scan using the remote spans to fill in any
remaining matches for the input rows of the batch.

Fixes #64870

Release note (performance improvement): Inner, Left, and Semi joins involving
`REGIONAL BY ROW` tables can now take advantage of locality optimized search.
This optimization allows lookup joins to avoid communicating with remote nodes
if a lookup is known to produce at most one match per input row, and all
matches are found locally. This can reduce query latency.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Nice work!

> Reviewed 17 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65784#-:-Majrvto2fr6IqQ7RBAV:bdtx8r6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, @RaduBerinde, and @rytaft)

___
*[pkg/sql/rowexec/joinreader.go, line 720 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65784#-MajoHG2Eo5Ve1LiRjYh:-MajoHG2Eo5Ve1LiRjYi:b-hhdp2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/5618261132d094e0a76688bf3f7e1af1073fd9cc/pkg/sql/rowexec/joinreader.go#L720)):*
> ```Go
> 	// the remote nodes for the current batch.
> 	if jr.remoteLookupExpr.Expr != nil && !jr.strategy.generatedRemoteSpans() &&
> 		jr.rowsRead != int64(len(jr.strategy.getInputRows())) {
> ```

Hm, I'm a bit concerned about the correctness of the last condition. `jr.rowsRead` tracks the number of rows we have read from the input throughout the operation of the join reader. IIUC the join reader alternates between `jrReadingInput`, `jrPerformingLookup`, and `jrEmittingRows` states (meaning that we read a batch of rows - which updates `jr.scratchInputRows` - perform a lookup for these rows, and emit the output before reading the next input batch). If I'm correct, then `jr.rowsRead` can outgrow the length of the input rows batch.
___
*[pkg/sql/rowexec/joinreader_span_generator.go, line 472 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65784#-MajpYIG0_zSZL5pXN3G:-MajpYIG0_zSZL5pXN3H:beeyqv1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5618261132d094e0a76688bf3f7e1af1073fd9cc/pkg/sql/rowexec/joinreader_span_generator.go#L472)):*
> ```Go
> // maxLookupCols is part of the joinReaderSpanGenerator interface.
> func (g *localityOptimizedSpanGenerator) maxLookupCols() int {
> 	localLookupCols := g.localSpanGen.maxLookupCols()
> ```

I would guess that both lookup expressions would always have the same lookup columns, no? Maybe it's worth adding an assertion for that?
___
*[pkg/sql/rowexec/joinreader_strategies.go, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65784#-Maji_mQBaAtBRtMJlix:-Maji_mR2CYqTK0QzeBH:bwclork) ([raw file](https://github.com/cockroachdb/cockroach/blob/5618261132d094e0a76688bf3f7e1af1073fd9cc/pkg/sql/rowexec/joinreader_strategies.go#L33)):*
> ```Go
> 	getMaxLookupKeyCols() int
> 	// getInputRows returns the input rows for the current batch.
> 	getInputRows() []rowenc.EncDatumRow
> ```

nit: if I'm reading the code correctly, `getInputRows` is only used to get the length (to check whether the local lookup succeeded for all input rows) in the joinReader code itself, and the input rows always come from `jr.scratchInputRows`. I think it'd be ok to just hard-code `len(jr.scratchInputRows)` in that single place where the length is needed and not add this method to the interface.

**Review by mgartner — APPROVED** [review]
Very cool! :lgtm_strong: 

Everything outside of `rowexec` looks good to me (I'll leave that to Yahor). The commit message is very clear and crisp! :100: 

> Reviewed 18 of 24 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65784#-:-Mak-kQtDINs4pl9GXgl:b8hi8yy)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach, @RaduBerinde, and @rytaft)

**Review by RaduBerinde — COMMENTED** [review]
This is really cool, awesome job!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65784#-:-Maq2RcQBYF1vlRRsvvn:b-ukx01y)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @rytaft)

**Review by rytaft — COMMENTED** [review]
Thanks all for the reviews! Updated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65784#-:-Mb1f1pQ4ttB7hOWNM-Q:b-ux8w5m)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @yuzefovich)

___
*[pkg/sql/rowexec/joinreader.go, line 720 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65784#-MajoHG2Eo5Ve1LiRjYh:-Mb1XIlL2IZlnuIwPLaP:bfr5tg9) ([raw file](https://github.com/cockroachdb/cockroach/blob/5618261132d094e0a76688bf3f7e1af1073fd9cc/pkg/sql/rowexec/joinreader.go#L720)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Hm, I'm a bit concerned about the correctness of the last condition. `jr.rowsRead` tracks the number of rows we have read from the input throughout the operation of the join reader. IIUC the join reader alternates between `jrReadingInput`, `jrPerformingLookup`, and `jrEmittingRows` states (meaning that we read a batch of rows - which updates `jr.scratchInputRows` - perform a lookup for these rows, and emit the output before reading the next input batch). If I'm correct, then `jr.rowsRead` can outgrow the length of the input rows batch.
</blockquote></details>

You're totally right - thanks for catching this! I updated my tests in `joinreader_test.go` so they now catch this problem. Fixed to use a new variable called `curBatchRowsRead`.
___
*[pkg/sql/rowexec/joinreader_span_generator.go, line 472 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65784#-MajpYIG0_zSZL5pXN3G:-Mb1YqRq1QYuC8ioSq-q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5618261132d094e0a76688bf3f7e1af1073fd9cc/pkg/sql/rowexec/joinreader_span_generator.go#L472)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I would guess that both lookup expressions would always have the same lookup columns, no? Maybe it's worth adding an assertion for that?
</blockquote></details>

Done.
___
*[pkg/sql/rowexec/joinreader_strategies.go, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65784#-Maji_mQBaAtBRtMJlix:-Mb1Z7MPDP20f5JZ8hhL:b-fqdl0a) ([raw file](https://github.com/cockroachdb/cockroach/blob/5618261132d094e0a76688bf3f7e1af1073fd9cc/pkg/sql/rowexec/joinreader_strategies.go#L33)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: if I'm reading the code correctly, `getInputRows` is only used to get the length (to check whether the local lookup succeeded for all input rows) in the joinReader code itself, and the input rows always come from `jr.scratchInputRows`. I think it'd be ok to just hard-code `len(jr.scratchInputRows)` in that single place where the length is needed and not add this method to the interface.
</blockquote></details>

The problem is that `jr.scratchInputRows` is reset to `jr.scratchInputRows[:0]` right after the call to `processLookupRows`. Moving that seems problematic, so I added a new field to the joinReader, `curBatchInputRowCount`. Let me know if you think this is better...

**Review by cucaroach — APPROVED** [review]
> Reviewed 18 of 24 files at r1, 2 of 2 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65784)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Review by yuzefovich — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65784#-:-Mb4dSi9B1gm7y3-jUni:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/rowexec/joinreader_strategies.go, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65784#-Maji_mQBaAtBRtMJlix:-Mb4cnwZ6xURyJUS1ikg:bygxdtn) ([raw file](https://github.com/cockroachdb/cockroach/blob/5618261132d094e0a76688bf3f7e1af1073fd9cc/pkg/sql/rowexec/joinreader_strategies.go#L33)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

The problem is that `jr.scratchInputRows` is reset to `jr.scratchInputRows[:0]` right after the call to `processLookupRows`. Moving that seems problematic, so I added a new field to the joinReader, `curBatchInputRowCount`. Let me know if you think this is better...
</blockquote></details>

I see, I missed that it was being reset before we want to know the length, but I think I prefer the current approach a bit more. My reasoning is that the `joinReader` is the owner of the slice of input rows for the current batch, so it should be the one responsible for knowing the length.

**Review by rytaft — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65784#-:-Mb6EpId2a_O7UB2f2PC:b-tlx7ko)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/rowexec/joinreader_strategies.go, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65784#-Maji_mQBaAtBRtMJlix:-Mb6El5D1rhjviUefAlu:b-kwpkg7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5618261132d094e0a76688bf3f7e1af1073fd9cc/pkg/sql/rowexec/joinreader_strategies.go#L33)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I see, I missed that it was being reset before we want to know the length, but I think I prefer the current approach a bit more. My reasoning is that the `joinReader` is the owner of the slice of input rows for the current batch, so it should be the one responsible for knowing the length.
</blockquote></details>

Sounds good - thanks!

**Comment by rytaft** [comment]
Looks like a flake

bors r+

**Comment by rytaft** [comment]
trying again...

bors r+

**Comment by rytaft** [comment]
Another flake: #65429

bors r+

**Comment by rytaft** [comment]
bumped the DistSQLVersion

bors r+

**Pull request merged**
