### PR TITLE
sql,*: error handling improvements

### PR DESCRIPTION
**Pull request by knz**
Subsumes #35825.
Subsumes #35820.

This PR replaces uses of `errors.New`, `errors.Errorf` and `errors.Wrap` by their `pgerror` equivalents. It also embeds the subsumed PRs; see those PR's discussion for details.

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
LGTM. This is great, thank you for the patience to go through all these!

**Comment by knz** [comment]
Note to self: before this merges review the CCL code too.

**Comment by knz** [comment]
This ship is sailing :ocean: 

bors r+

**Comment by bdarnell** [comment]
I think this PR was too eager to replace Wrapfs with NewAssertionErrors. Specifically the ones in schema_changer.go occur in the context of a client.Txn where the error (or its cause) is inspected. This replaces potentially-retriable errors with assertion errors which can cause schema changes to fail unnecessarily. 

I'll fix the ones that I'm specifically finding to be problems, but it makes me nervous to see how many Wrapfs were replaced with assertion errors instead of using the new Wrapf.

**Pull request merged**
