### PR TITLE
util/stop: some carryover changes from #7459

### PR DESCRIPTION
**Pull request by vivekmenezes**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7479)

### CODE REVIEW

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7479#-:-KLGkWyllzdqqMdpRvIz:1417088721)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[kv/txn_coord_sender.go, line 878 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7479#-KLH8yJvY38C_SPhjtUM:-KLH8yJvY38C_SPhjtUN:-1689933176) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d77aa6d7667953f55a48f94fb18892fac611877/kv/txn_coord_sender.go#L878)):*
> ```Go
> 					// In principle, we can relax this as needed though.
> 					tc.unregisterTxnLocked(txnID)
> 					return roachpb.NewError(&roachpb.NodeUnavailableError{})
> ```

i think i'd rather pass `err` through here. if `roachpb.NodeUnavailableError` is the way to go, perhaps we should just return that from the stopper?

---

*[storage/replica_command.go, line 1861 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7479#-KLH9B40JwymofKQCToN:-KLH9B40JwymofKQCToO:-587757814) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d77aa6d7667953f55a48f94fb18892fac611877/storage/replica_command.go#L1861)):*
> ```Go
> 				}
> 			}); err != nil {
> 				log.Error(errors.Wrap(err, "could not rerun consistency check"))
> ```

FYI the `errors.Wrap` doesn't buy anything here, but it doesn't hurt.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7479)*

**Comment by vivekmenezes** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[kv/txn_coord_sender.go, line 878 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7479#-KLH8yJvY38C_SPhjtUM:-KLHHqcM4d9vpNmxqrTV:-608799336) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d77aa6d7667953f55a48f94fb18892fac611877/kv/txn_coord_sender.go#L878)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> i think i'd rather pass `err` through here. if `roachpb.NodeUnavailableError` is the way to go, perhaps we should just return that from the stopper?
</details>
We can't add a dependency from util to roachpb because roachpb depends on util. I think it's okay to return a different error from here. The stopper error is node agnostic while an error returned from here can be cockroach specific.

---

*[storage/replica_command.go, line 1861 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7479#-KLH9B40JwymofKQCToN:-KLHIj1swO0GXSw5aH1c:677114931) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d77aa6d7667953f55a48f94fb18892fac611877/storage/replica_command.go#L1861)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> FYI the `errors.Wrap` doesn't buy anything here, but it doesn't hurt.
</details>
True

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7479)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[kv/txn_coord_sender.go, line 878 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7479#-KLH8yJvY38C_SPhjtUM:-KLH9GCo-6hNBEHSYo4E:1521984235) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d77aa6d7667953f55a48f94fb18892fac611877/kv/txn_coord_sender.go#L878)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> We can't add a dependency from util to roachpb because roachpb depends on util. I think it's okay to return a different error from here. The stopper error is node agnostic while an error returned from here can be cockroach specific.
</details>
True, but stopper is in its own package util/stop, not util.

I don't understand why we'd want two errors that means the same thing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7479)*

**Comment by vivekmenezes** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[kv/txn_coord_sender.go, line 878 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7479#-KLH8yJvY38C_SPhjtUM:-KLHKS82lnjm7zy_wpFX:-1511091810) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d77aa6d7667953f55a48f94fb18892fac611877/kv/txn_coord_sender.go#L878)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> True, but stopper is in its own package util/stop, not util.
> 
> I don't understand why we'd want two errors that means the same thing.
</details>
util/net.go depends on util/stopper. perhaps what I need to do is move that out of util. Do you think rpc/ is a good home for it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7479)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[kv/txn_coord_sender.go, line 878 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7479#-KLH8yJvY38C_SPhjtUM:-KLHNE99jcpQzzPI74KR:587950854) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d77aa6d7667953f55a48f94fb18892fac611877/kv/txn_coord_sender.go#L878)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> util/net.go depends on util/stopper. perhaps what I need to do is move that out of util. Do you think rpc/ is a good home for it?
</details>
Hm, nah - let's put it in its own package `util/netutil`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7479)*

**Comment by vivekmenezes** [comment]
Review status: 1 of 15 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[kv/txn_coord_sender.go, line 878 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7479#-KLH8yJvY38C_SPhjtUM:-KLHeDlahNC8oukKyC_Y:-169923651) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d77aa6d7667953f55a48f94fb18892fac611877/kv/txn_coord_sender.go#L878)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Hm, nah - let's put it in its own package `util/netutil`
</details>
All done. Thanks for the review

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7479)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 16 of 16 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[util/stop/stopper_test.go, line 196 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7479#-KLHedHnF3U6vkW2L7_s:-KLHedHnF3U6vkW2L7_t:159086403) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd509606c08b229e6fc437228afd8862e96ff787/util/stop/stopper_test.go#L196)):*
> ```Go
> 			// Wait until Quiesce() is called.
> 			<-qc
> 			if err := thisStopper.RunTask(func() {}); !testutils.IsError(
> ```

nit:
```
err := thisStopper.RunTask(func() {})
if _, ok := err.(*roachpb.NodeUnavailableError); !ok {
  t.Errorf("unexpected error: %v", err)
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7479#-:-KLHf6dHrfUZcHM6Emfq:1417088721)*

**Comment by vivekmenezes** [comment]
Review status: 14 of 15 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[util/stop/stopper_test.go, line 196 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7479#-KLHedHnF3U6vkW2L7_s:-KLHjQNfysCSq7DNqmYe:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd509606c08b229e6fc437228afd8862e96ff787/util/stop/stopper_test.go#L196)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit:
> ```
> err := thisStopper.RunTask(func() {})
> if _, ok := err.(*roachpb.NodeUnavailableError); !ok {
>   t.Errorf("unexpected error: %v", err)
> }
> ```
</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7479)*

**Pull request merged**
