### PR TITLE
util/encoding: add a new encoding for column family values

### PR DESCRIPTION
**Pull request by danhhz**
The prefix uses varints to encode a column id and type, packing them into a
single byte when they're small (colID < 8 and typ < 15). This works by
shifting the colID "left" by 4 and putting any type less than 15 in the low
bytes. The result is uvarint encoded and fits in one byte if the original
column id fit in 3 bits. If it doesn't fit in one byte, the most significant
bits spill to the "left", leaving the type bits always at the very "right".

If the type is > 15, the reserved sentinel of 15 is placed in the type bits
and a uvarint follows with the type value.

Together, this means the everything but the last byte of the colID/typ
uvarint can be dropped if the column id isn't needed.

name                   time/op
EncodeBoolValue-8      28.0ns ± 2%
DecodeBoolValue-8      36.5ns ± 2%
EncodeIntValue-8       49.9ns ± 4%
DecodeIntValue-8       66.8ns ± 3%
EncodeFloatValue-8     31.6ns ± 1%
DecodeFloatValue-8     45.1ns ± 2%
EncodeBytesValue-8     36.9ns ± 2%
DecodeBytesValue-8     45.9ns ± 3%
EncodeTimeValue-8      60.1ns ± 2%
DecodeTimeValue-8      66.5ns ± 1%
EncodeDecimalValue-8    216ns ± 3%
DecodeDecimalValue-8    237ns ± 4%
EncodeDurationValue-8  75.1ns ± 1%
DecodeDurationValue-8  82.0ns ±10%

name                   alloc/op
EncodeBoolValue-8      0.00B ±NaN%
DecodeBoolValue-8      0.00B ±NaN%
EncodeIntValue-8       0.00B ±NaN%
DecodeIntValue-8       0.00B ±NaN%
EncodeFloatValue-8     0.00B ±NaN%
DecodeFloatValue-8     0.00B ±NaN%
EncodeBytesValue-8     0.00B ±NaN%
DecodeBytesValue-8     0.00B ±NaN%
EncodeTimeValue-8      0.00B ±NaN%
DecodeTimeValue-8      0.00B ±NaN%
EncodeDecimalValue-8    7.00B ± 0%
DecodeDecimalValue-8    96.0B ± 0%
EncodeDurationValue-8  0.00B ±NaN%
DecodeDurationValue-8  0.00B ±NaN%

name                   allocs/op
EncodeBoolValue-8       0.00 ±NaN%
DecodeBoolValue-8       0.00 ±NaN%
EncodeIntValue-8        0.00 ±NaN%
DecodeIntValue-8        0.00 ±NaN%
EncodeFloatValue-8      0.00 ±NaN%
DecodeFloatValue-8      0.00 ±NaN%
EncodeBytesValue-8      0.00 ±NaN%
DecodeBytesValue-8      0.00 ±NaN%
EncodeTimeValue-8       0.00 ±NaN%
DecodeTimeValue-8       0.00 ±NaN%
EncodeDecimalValue-8    0.00 ±NaN%
DecodeDecimalValue-8     2.00 ± 0%
EncodeDurationValue-8   0.00 ±NaN%
DecodeDurationValue-8   0.00 ±NaN%

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7356)

### CODE REVIEW

**Comment by paperstreet** [comment]
Review note: I'm going to add one more commit to this PR before merging to switch from using the old value encoding (which is still sitting around in roachpb) to this one. This was ready so I figured I'd get the process started.

Also cc @petermattis

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-:-KKnf-0DDhSgM86lG_Ux:846451887)*

**Comment by paperstreet** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[util/encoding/encoding.go, line 1182 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-KKoSWOPAnuTsvxI40x6:-KKoSWOPAnuTsvxI40x7:578622667) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ebe5b74deffdb35de6f09f9add5b7fe9573078c/util/encoding/encoding.go#L1182)):*
> ```Go
> func EncodeBytesValue(appendTo []byte, colID uint32, data []byte) []byte {
> 	appendTo = encodeValueTag(appendTo, colID, Bytes)
> 	appendTo = EncodeNonsortingUvarint(appendTo, uint64(len(data)))
> ```

After getting this PR out, I realized that the benchmarks for this and the BytesAscending encoding are basically the same. The other one will use 1 fewer byte for any byte array that doesn't need escaping, but could be longer if it needs lots of escaping. The other may also slow down PeekValueLength for large arrays since you have to look at every byte. Who has an opinion on which tradeoffs we like better?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356)*

**Comment by RaduBerinde** [comment]
Great stuff!

The old value encoding code will not be used anymore and will be removed right?

---

Review status: 0 of 8 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[util/encoding/encoding.go, line 854 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-KKnqFaQ8cYT0YzNxo6v:-KKnqFaRKShv_hWKfhvl:1039850299) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dcb84d4c1ff2dd2983caf7f79e98f7e6b3ed05e/util/encoding/encoding.go#L854)):*
> ```Go
> 	False
> 
> 	SentinelType Type = 15 // Used in the Value encoding.
> ```

Make it clear here that we can NOT have any type that equals the sentinel value 15 (the "point at the last byte" thing wouldn't work - as things stand, `DecodeValueTag` would try to decode an extra int).
Maybe we should put explicit values on them instead of `iota`.

---

*[util/encoding/encoding.go, line 1135 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-KKnqYH7ljkrMuKHAQ3x:-KKnqYH7ljkrMuKHAQ3y:1499915701) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dcb84d4c1ff2dd2983caf7f79e98f7e6b3ed05e/util/encoding/encoding.go#L1135)):*
> ```Go
> // uvarint can be dropped if the column id isn't needed.
> func encodeValueTag(appendTo []byte, colID uint32, typ Type) []byte {
> 	if typ >= SentinelType {
> ```

Here we should panic if typ == SentinelType

---

*[util/encoding/encoding.go, line 1137 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-KKnnQv0YV8vZDZbFRIQ:-KKnnQv0YV8vZDZbFRIR:1319080897) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dcb84d4c1ff2dd2983caf7f79e98f7e6b3ed05e/util/encoding/encoding.go#L1137)):*
> ```Go
> 	if typ >= SentinelType {
> 		appendTo = EncodeNonsortingUvarint(appendTo, uint64(colID)<<4|uint64(SentinelType))
> 		appendTo = EncodeNonsortingUvarint(appendTo, uint64(typ))
> ```

return Encode..

---

*[util/encoding/encoding.go, line 1221 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-KKnpco8BB9Ue4abyyul:-KKnpco8BB9Ue4abyyum:-2081980600) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dcb84d4c1ff2dd2983caf7f79e98f7e6b3ed05e/util/encoding/encoding.go#L1221)):*
> ```Go
> // you can drop the first typeOffset bytes and DecodeValueTag and
> // PeekValueLength will still work on the result.
> func DecodeValueTag(b []byte) (typeOffset int, dataOffset int, colID uint32, typ Type, err error) {
> ```

The explanation should be more clear - mention specifically that b can point either at the full tag, or just at the last byte, and in the latter case the colID return value is not valid and should be ignored.

---

*[util/encoding/encoding.go, line 1222 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-KKnqkiJvoCiphytE1PD:-KKnqkiJvoCiphytE1PE:692557236) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dcb84d4c1ff2dd2983caf7f79e98f7e6b3ed05e/util/encoding/encoding.go#L1222)):*
> ```Go
> // PeekValueLength will still work on the result.
> func DecodeValueTag(b []byte) (typeOffset int, dataOffset int, colID uint32, typ Type, err error) {
> 	// TODO(dan): This can be made much faster by special casing the single byte
> ```

I'm not sure about the "much faster" part, we would just be saving a >> and an &

---

*[util/encoding/encoding.go, line 1292 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-KKnp42JHZiuflEfZXnD:-KKnp42Kd48A4PcWmmhN:321303234) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dcb84d4c1ff2dd2983caf7f79e98f7e6b3ed05e/util/encoding/encoding.go#L1292)):*
> ```Go
> 
> // DecodeBytesValue decodes a value encoded by EncodeBytesValue.
> func DecodeBytesValue(b []byte) ([]byte, []byte, error) {
> ```

name or document the results. I guess this goes for all functions but especially here.

---

*[util/encoding/encoding.go, line 1379 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-KKnpT64Gj4NbP7Q5ACJ:-KKnpT64Gj4NbP7Q5ACK:-621649671) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dcb84d4c1ff2dd2983caf7f79e98f7e6b3ed05e/util/encoding/encoding.go#L1379)):*
> ```Go
> // Note: If this function succeeds, it's not a guarantee that decoding the value
> // will succeed.
> func PeekValueLength(b []byte) (typeOffset int, length int, err error) {
> ```

Mention here that the buffer can point at the start of the "full tag" with the column id, or it can point to the last byte at the tag and it works just as well.

Also, explain what typeOffset is and that length includes that as well.

---

*[util/encoding/encoding.go, line 1182 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-KKoSWOPAnuTsvxI40x6:-KKoh1N7WHZOwnYdZ-EO:1241204091) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ebe5b74deffdb35de6f09f9add5b7fe9573078c/util/encoding/encoding.go#L1182)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> After getting this PR out, I realized that the benchmarks for this and the BytesAscending encoding are basically the same. The other one will use 1 fewer byte for any byte array that doesn't need escaping, but could be longer if it needs lots of escaping. The other may also slow down PeekValueLength for large arrays since you have to look at every byte. Who has an opinion on which tradeoffs we like better?
</details>
How does it use 1 fewer byte - doesn't it have a termination escape (2 bytes) vs our length field which will usually be 1 byte?

I would probably go with this as it has a better worst-case behavior and doesn't need post-processing for escapes.

---

*[util/encoding/encoding_test.go, line 1598 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-KKntjfLrKDP0vwTXRM4:-KKntjfLrKDP0vwTXRM5:759194079) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dcb84d4c1ff2dd2983caf7f79e98f7e6b3ed05e/util/encoding/encoding_test.go#L1598)):*
> ```Go
> 			t.Fatalf("seed %d: got %d expected %d: %x", seed, l, length, buf[:length])
> 		}
> ```

Why not decode here as well and verify the length matches, and that the decoding is correct?

Otherwise we need more encode/decode tests that involve appending stuff to the encoding before running decode.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-:-KKnsuR4mMQaBHYivHlL:335964409)*

**Comment by petermattis** [comment]
:lgtm:, though I didn't go over this thoroughly. The high-level looks good.

---

Review status: 0 of 8 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[util/encoding/encoding.go, line 1133 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-KKsLBNmbStVc9rlmVeT:-KKsLBNmbStVc9rlmVeU:-1654101115) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ebe5b74deffdb35de6f09f9add5b7fe9573078c/util/encoding/encoding.go#L1133)):*
> ```Go
> //
> // Together, this means the everything but the last byte of the colID/typ
> // uvarint can be dropped if the column id isn't needed.
> ```

It's worth mentioning that in practice we're not storing the column ID, but the delta from the previous column ID. This is accomplished by sorting the column IDs in a column family before encoding them. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-:-KKsLPbkhioziK5II8ZE:-1689204149)*

**Comment by paperstreet** [comment]
TFTRs! This is ready for another look (r4 is the new encoding, r5 is using it and deleting the old one)

---

Review status: 0 of 8 files reviewed at latest revision, 10 unresolved discussions, some commit checks pending.

---

*[util/encoding/encoding.go, line 854 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-KKnqFaQ8cYT0YzNxo6v:-KKsgwO4GgQpsL73_vEr:-787999013) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dcb84d4c1ff2dd2983caf7f79e98f7e6b3ed05e/util/encoding/encoding.go#L854)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Make it clear here that we can NOT have any type that equals the sentinel value 15 (the "point at the last byte" thing wouldn't work - as things stand, `DecodeValueTag` would try to decode an extra int).
> Maybe we should put explicit values on them instead of `iota`.
</details>
This is an interesting question. Encoding 15 actually works just fine, it's put in the second varint. I can't see why anyone would do it, but it happens to work and I don't have to special case 15 in the tests.

Agreed on iota. That scares me anytime it's persisted, but it seems to be our idiom and we do it all over the place. I've been planning on making these consts into a proto enum (which makes it obvious that it could be persisted), I'll throw in a TODO for that.

---

*[util/encoding/encoding.go, line 1137 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-KKnnQv0YV8vZDZbFRIQ:-KKsjPyiO1rqvzxo1Gm-:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dcb84d4c1ff2dd2983caf7f79e98f7e6b3ed05e/util/encoding/encoding.go#L1137)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> return Encode..
</details>
Done.

---

*[util/encoding/encoding.go, line 1221 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-KKnpco8BB9Ue4abyyul:-KKsqhWWafdc09DtQsLY:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dcb84d4c1ff2dd2983caf7f79e98f7e6b3ed05e/util/encoding/encoding.go#L1221)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> The explanation should be more clear - mention specifically that b can point either at the full tag, or just at the last byte, and in the latter case the colID return value is not valid and should be ignored.
</details>
Done.

---

*[util/encoding/encoding.go, line 1222 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-KKnqkiJvoCiphytE1PD:-KKsl79sqCSOCnH1jM0Q:-1765148484) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dcb84d4c1ff2dd2983caf7f79e98f7e6b3ed05e/util/encoding/encoding.go#L1222)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> I'm not sure about the "much faster" part, we would just be saving a >> and an &
</details>
It saves the function call to DecodeNonsortingUvarint, though maybe that's being inlined. Anyway, I wrote this, saw it didn't make much difference in benchmarks, and forgot to update the comment. Fixed.

---

*[util/encoding/encoding.go, line 1292 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-KKnp42JHZiuflEfZXnD:-KKsmFC_6bql2bFaCTM8:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dcb84d4c1ff2dd2983caf7f79e98f7e6b3ed05e/util/encoding/encoding.go#L1292)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> name or document the results. I guess this goes for all functions but especially here.
</details>
Done.

---

*[util/encoding/encoding.go, line 1379 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-KKnpT64Gj4NbP7Q5ACJ:-KKsrpwvVjy_jKauQH0G:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dcb84d4c1ff2dd2983caf7f79e98f7e6b3ed05e/util/encoding/encoding.go#L1379)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Mention here that the buffer can point at the start of the "full tag" with the column id, or it can point to the last byte at the tag and it works just as well.
> 
> Also, explain what typeOffset is and that length includes that as well.
</details>
Done.

---

*[util/encoding/encoding.go, line 1182 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-KKoSWOPAnuTsvxI40x6:-KKsjU7s8YrC3MD6EgoZ:1647622722) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ebe5b74deffdb35de6f09f9add5b7fe9573078c/util/encoding/encoding.go#L1182)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> How does it use 1 fewer byte - doesn't it have a termination escape (2 bytes) vs our length field which will usually be 1 byte?
> 
> I would probably go with this as it has a better worst-case behavior and doesn't need post-processing for escapes.
</details>
The bytes aren't necessarily terminated. If you encode 0x0304, this encoding does 0x020304 and the key encoding does 0x0304.

Anyway, I wasn't thinking about post-processing for some reason, that definitely tips the scales for me.

---

*[util/encoding/encoding_test.go, line 1598 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-KKntjfLrKDP0vwTXRM4:-KKssoiOsnzQcEkicTJq:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dcb84d4c1ff2dd2983caf7f79e98f7e6b3ed05e/util/encoding/encoding_test.go#L1598)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Why not decode here as well and verify the length matches, and that the decoding is correct?
> 
> Otherwise we need more encode/decode tests that involve appending stuff to the encoding before running decode.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-:-KKt5fMmoSGLR2u40BOu:280765329)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 8 files reviewed at latest revision, 10 unresolved discussions, some commit checks pending.

---

*[util/encoding/encoding.go, line 854 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-KKnqFaQ8cYT0YzNxo6v:-KKt8CvuoOzU3OVCvpHt:1005686783) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dcb84d4c1ff2dd2983caf7f79e98f7e6b3ed05e/util/encoding/encoding.go#L854)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> This is an interesting question. Encoding 15 actually works just fine, it's put in the second varint. I can't see why anyone would do it, but it happens to work and I don't have to special case 15 in the tests.
> 
> Agreed on iota. That scares me anytime it's persisted, but it seems to be our idiom and we do it all over the place. I've been planning on making these consts into a proto enum (which makes it obvious that it could be persisted), I'll throw in a TODO for that.
</details>
If we have type 15, encoding would be something like `<col id> 15 15`. If we call `DecodeValueTag` with a slice starting at the last byte, it will go ahead and read another varint which is not valid.  We have to point at the *first* 15. This goes against the documented behavior: "everything but the last byte of the colID/typ uvarint can be dropped if the column id isn't needed", in this specific case we need everything but the last 2 bytes..

---

*[util/encoding/encoding.go, line 1182 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-KKoSWOPAnuTsvxI40x6:-KKt7r-XmRqH1yjZNa7J:981945075) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ebe5b74deffdb35de6f09f9add5b7fe9573078c/util/encoding/encoding.go#L1182)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> The bytes aren't necessarily terminated. If you encode 0x0304, this encoding does 0x020304 and the key encoding does 0x0304.
> 
> Anyway, I wasn't thinking about post-processing for some reason, that definitely tips the scales for me.
</details>
I really don't know how that would work. What if something follows 0x0304, how would we know it's part of that string or part of a different thing in that key?

`EncodeBytesAscending` ends with `append(b, escape, escapedTerm)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356)*

**Comment by paperstreet** [comment]
Review status: 0 of 8 files reviewed at latest revision, 10 unresolved discussions, some commit checks pending.

---

*[util/encoding/encoding.go, line 854 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-KKnqFaQ8cYT0YzNxo6v:-KKt9YZpuqEVDE1lWnVJ:-1241150393) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dcb84d4c1ff2dd2983caf7f79e98f7e6b3ed05e/util/encoding/encoding.go#L854)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> If we have type 15, encoding would be something like `<col id> 15 15`. If we call `DecodeValueTag` with a slice starting at the last byte, it will go ahead and read another varint which is not valid.  We have to point at the *first* 15. This goes against the documented behavior: "everything but the last byte of the colID/typ uvarint can be dropped if the column id isn't needed", in this specific case we need everything but the last 2 bytes..
</details>
Ah, the docs are just unclear. There is either one or two varints. Everything up to the last byte of the _first_ varint can be dropped. Will take another swing at that comment

---

*[util/encoding/encoding.go, line 1133 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-KKsLBNmbStVc9rlmVeT:-KKt9u916079RIbcd35C:-1448950137) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ebe5b74deffdb35de6f09f9add5b7fe9573078c/util/encoding/encoding.go#L1133)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> It's worth mentioning that in practice we're not storing the column ID, but the delta from the previous column ID. This is accomplished by sorting the column IDs in a column family before encoding them. 
</details>
Oops, missed this. Will update shortly.

---

*[util/encoding/encoding.go, line 1182 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-KKoSWOPAnuTsvxI40x6:-KKt9nDz1ko_aOEXUMQy:1791750038) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ebe5b74deffdb35de6f09f9add5b7fe9573078c/util/encoding/encoding.go#L1182)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> I really don't know how that would work. What if something follows 0x0304, how would we know it's part of that string or part of a different thing in that key?
> 
> `EncodeBytesAscending` ends with `append(b, escape, escapedTerm)`
</details>
welp. brain fart on my part

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[sql/sqlbase/encoded_datum.go, line 89 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-KKtC312S9_x5SXvCY-m:-KKtC312S9_x5SXvCY-n:1773308543) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c8137b5af700907fac476ca3b9c3b4b2732fc24/sql/sqlbase/encoded_datum.go#L89)):*
> ```Go
> 		}
> 		ed.SetEncoded(typ, enc, buf[:encLen])
> 		buf = buf[encLen:]
> ```

might as well just do `returm buf[encLen:], nil` directly instead (same below)

---

*[util/encoding/encoding.go, line 854 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-KKnqFaQ8cYT0YzNxo6v:-KKtAXzAxe8i5pmcPnBf:303533079) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dcb84d4c1ff2dd2983caf7f79e98f7e6b3ed05e/util/encoding/encoding.go#L854)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> Ah, the docs are just unclear. There is either one or two varints. Everything up to the last byte of the _first_ varint can be dropped. Will take another swing at that comment
</details>
Got it. That works. The newer comments for DecodeValueTag in r4 are more accurate.

---

*[util/encoding/encoding_test.go, line 1717 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-KKtBkQt5Qkopzrzw-jR:-KKtBkQt5Qkopzrzw-jS:2094844752) ([raw file](https://github.com/cockroachdb/cockroach/blob/246c572ac856553f9617a14196738fa8870c23fc/util/encoding/encoding_test.go#L1717)):*
> ```Go
> 		}
> 
> 		switch typ {
> ```

do all these types implement `Stringer`? If so just converting to string and comparing would be simpler

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-:-KKtCcFueP9y-tD7BW6T:1417088721)*

**Comment by RaduBerinde** [comment]
Reviewed 1 of 3 files at r1, 1 of 7 files at r4, 1 of 6 files at r6, 5 of 5 files at r7.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356)*

**Comment by paperstreet** [comment]
Review status: 6 of 8 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[sql/sqlbase/encoded_datum.go, line 89 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-KKtC312S9_x5SXvCY-m:-KKtDfkafwtC9lkp_TsY:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c8137b5af700907fac476ca3b9c3b4b2732fc24/sql/sqlbase/encoded_datum.go#L89)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> might as well just do `returm buf[encLen:], nil` directly instead (same below)
</details>
Done.

---

*[util/encoding/encoding_test.go, line 1717 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356#-KKtBkQt5Qkopzrzw-jR:-KKtRb5o16COVmWfIPEy:-366117855) ([raw file](https://github.com/cockroachdb/cockroach/blob/246c572ac856553f9617a14196738fa8870c23fc/util/encoding/encoding_test.go#L1717)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> do all these types implement `Stringer`? If so just converting to string and comparing would be simpler
</details>
looks like the base types don't

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7356)*

**Pull request merged**
