### PR TITLE
sql: allow for dropping indexes in use in outbound fk

### LINKED ISSUE #50592: sql: dropping column with FK relies on FK origin indexes
I was taking a first step toward removing the requirement for origin FK indexes, namely to allow dropping these indexes without error. I tried the simple diff below. With this change, a seemingly unrelated thing fails: dropping a column that has a foreign key. See exeample: https://gist.github.com/RaduBerinde/8eef2aa04627ee18a2ca3a12d9d4d870

My guess is that we are not directly dropping any foreign keys involving the column, instead it happens indirectly through deleting all indexes. Unfortunately I'm not familiar with this code at all, I wouldn't know where to begin to fix this.

```diff
diff --git a/pkg/sql/drop_index.go b/pkg/sql/drop_index.go
index 25bd598b13..30a809e49a 100644
--- a/pkg/sql/drop_index.go
+++ b/pkg/sql/drop_index.go
@@ -356,29 +356,7 @@ func (p *planner) dropIndexByName(
 		return err
 	}
 
-	// Index for updating the FK slices in place when removing FKs.
 	sliceIdx := 0
-	for i := range tableDesc.OutboundFKs {
-		tableDesc.OutboundFKs[sliceIdx] = tableDesc.OutboundFKs[i]
-		sliceIdx++
-		fk := &tableDesc.OutboundFKs[i]
-		canReplace := func(idx *sqlbase.IndexDescriptor) bool {
-			return idx.IsValidOriginIndex(fk.OriginColumnIDs)
-		}
-		// The index being deleted could be used as the origin index for this foreign key.
-		if idx.IsValidOriginIndex(fk.OriginColumnIDs) && !indexHasReplacementCandidate(canReplace) {
-			if behavior != tree.DropCascade && constraintBehavior != ignoreIdxConstraint {
-				return errors.Errorf("index %q is in use as a foreign key constraint", idx.Name)
-			}
-			sliceIdx--
-			if err := p.removeFKBackReference(ctx, tableDesc, fk); err != nil {
-				return err
-			}
-		}
-	}
-	tableDesc.OutboundFKs = tableDesc.OutboundFKs[:sliceIdx]
-
-	sliceIdx = 0
 	for i := range tableDesc.InboundFKs {
 		tableDesc.InboundFKs[sliceIdx] = tableDesc.InboundFKs[i]
 		sliceIdx++
diff --git a/pkg/sql/logictest/testdata/logic_test/drop_index b/pkg/sql/logictest/testdata/logic_test/drop_index
```

### PR DESCRIPTION
**Pull request by rohany**
Fixes #50592.

Release note (sql change): This PR enables the use of dropping indexes
used in outbound foreign key relationships.

### CODE REVIEW

**Comment by awoods187** [comment]
So speedy!

**Comment by RaduBerinde** [comment]
Ha, I tried the same and ran into #50592. Are you fixing that here as well?

**Comment by rohany** [comment]
This is in response to your issue :)

**Review by thoszhang — COMMENTED** [review]
Do we need a version gate for this?

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50769#-:-MB0ejwRD6Dt8PNaAyxq:bg4eudg)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by rohany** [comment]
> Do we need a version gate for this?

Ahh, yes. I'll add one and update the PR.

**Comment by rohany** [comment]
Updated with a version gate.

**Review by RaduBerinde — COMMENTED** [review]
Awesome, I see the fix now! Thanks! :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50769#-:-MB0kd1H5tBgTHp1CytA:bd6feuf)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lucy-zhang and @rohany)

___
*[pkg/sql/alter_table.go, line 460 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50769#-MB0kW_V9nnIVjv3790R:-MB0kW_V9nnIVjv3790S:bq9b7pj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9429356331c36ad2182a7b447ed52ca40a1313bb/pkg/sql/alter_table.go#L460)):*
> ```Go
> 
> 			// Drop check constraints which reference the column.
> 			// Note that foreign key constraints are dropped as part of dropping
> ```

This comment needs updating
___
*[pkg/sql/logictest/testdata/logic_test/alter_table, line 1355 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50769#-MB0l5PYEWJVgNmlGbPn:-MB0l5PYEWJVgNmlGbPo:b-cwtbmz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9429356331c36ad2182a7b447ed52ca40a1313bb/pkg/sql/logictest/testdata/logic_test/alter_table#L1355)):*
> ```
> ALTER TABLE t50069_a ADD COLUMN y INT AS (d.public.t50069_a.x + 1) STORED
> 
> # Dropping a column with a foreign key should delete the column and the FK.
> ```

This case would work just fine even without the fix you added, no? Because the outbound FK index is there when we drop the column. Maybe create the table with an index on `p` and then drop that index before dropping the column?

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50769)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @lucy-zhang and @RaduBerinde)

___
*[pkg/sql/alter_table.go, line 460 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50769#-MB0kW_V9nnIVjv3790R:-MB0nVQJBsXcBmxeSAj9:b-axhojg) ([raw file](https://github.com/cockroachdb/cockroach/blob/9429356331c36ad2182a7b447ed52ca40a1313bb/pkg/sql/alter_table.go#L460)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This comment needs updating
</blockquote></details>

Good catch, updated.
___
*[pkg/sql/logictest/testdata/logic_test/alter_table, line 1355 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50769#-MB0l5PYEWJVgNmlGbPn:-MB0nyJE3BbLbuQEw_2M:b-pk6oro) ([raw file](https://github.com/cockroachdb/cockroach/blob/9429356331c36ad2182a7b447ed52ca40a1313bb/pkg/sql/logictest/testdata/logic_test/alter_table#L1355)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This case would work just fine even without the fix you added, no? Because the outbound FK index is there when we drop the column. Maybe create the table with an index on `p` and then drop that index before dropping the column?
</blockquote></details>

This is the case you posted your gist. Note that we are still creating indexes for FK's in this commit, so there is already an index on `p`. We're dropping it, and then cleaning up the FK in the drop column code.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50769)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @lucy-zhang, @RaduBerinde, and @rohany)

___
*[pkg/sql/logictest/testdata/logic_test/alter_table, line 1355 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50769#-MB0l5PYEWJVgNmlGbPn:-MB0qCnq8v-lxH9LhObZ:bio20pm) ([raw file](https://github.com/cockroachdb/cockroach/blob/9429356331c36ad2182a7b447ed52ca40a1313bb/pkg/sql/logictest/testdata/logic_test/alter_table#L1355)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

This is the case you posted your gist. Note that we are still creating indexes for FK's in this commit, so there is already an index on `p`. We're dropping it, and then cleaning up the FK in the drop column code.
</blockquote></details>

Oh, right, thanks!

**Comment by rohany** [comment]
I'll wait for @lucy-zhang to review as well

**Review by thoszhang — APPROVED** [review]
> Reviewed 4 of 5 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50769)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @rohany)

___
*[pkg/clusterversion/cockroach_versions.go, line 524 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50769#-MBB-BXp5eVz4zq_cQ-s:-MBB-BXp5eVz4zq_cQ-t:b-mdidjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd2964597a04e1ed653a4fb9dd02c6d847569339/pkg/clusterversion/cockroach_versions.go#L524)):*
> ```Go
> 		// VersionDropOriginFKIndexes allows for users to drop indexes that are
> 		// used by the origin side of a foreign key relationship.
> 		Key:     VersionDropOriginFKIndexes,
> ```

Can there just be a single version for the removed restrictions that covers both "can drop indexes" and "can create new FKs without indexes"?
___
*[pkg/sql/alter_table.go, line 487 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50769#-MBB-TbP0wKFPFl-2UX8:-MBB-TbP0wKFPFl-2UX9:b-zensm) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd2964597a04e1ed653a4fb9dd02c6d847569339/pkg/sql/alter_table.go#L487)):*
> ```Go
> 			}
> 
> 			// If we are able to drop indexes used by foreign keys on the origin side,
> ```

nit: I'd say `Since we are able...` for future readers who don't have context on the historical requirements
___
*[pkg/sql/drop_index.go, line 359 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50769#-MBB-e55EqtRRvT-fVOq:-MBB-e55EqtRRvT-fVOr:b-m96mqp) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd2964597a04e1ed653a4fb9dd02c6d847569339/pkg/sql/drop_index.go#L359)):*
> ```Go
> 	}
> 
> 	// If the we aren't high enough version to drop indexes on the origin side
> ```

nit: `at a high enough version`?

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50769)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @lucy-zhang, @RaduBerinde, and @rohany)

___
*[pkg/clusterversion/cockroach_versions.go, line 524 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50769#-MBB-BXp5eVz4zq_cQ-s:-MBB042b-LLxPClaDqi6:b-ns59bs) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd2964597a04e1ed653a4fb9dd02c6d847569339/pkg/clusterversion/cockroach_versions.go#L524)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Can there just be a single version for the removed restrictions that covers both "can drop indexes" and "can create new FKs without indexes"?
</blockquote></details>

That makes sense, I'll update this.
___
*[pkg/sql/alter_table.go, line 487 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50769#-MBB-TbP0wKFPFl-2UX8:-MBB0N1OA9NMaC_pCGdQ:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd2964597a04e1ed653a4fb9dd02c6d847569339/pkg/sql/alter_table.go#L487)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

nit: I'd say `Since we are able...` for future readers who don't have context on the historical requirements
</blockquote></details>

done
___
*[pkg/sql/drop_index.go, line 359 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50769#-MBB-e55EqtRRvT-fVOq:-MBB0U-f1_rNYh8LPWuZ:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd2964597a04e1ed653a4fb9dd02c6d847569339/pkg/sql/drop_index.go#L359)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

nit: `at a high enough version`?
</blockquote></details>

done

**Comment by rohany** [comment]
bors r=lucy-zhang

**Pull request merged**
