### PR TITLE
cli/sql: make the client more forward-compatible

### PR DESCRIPTION
**Pull request by knz**
As described in #19445.

Two changes, one for polish and one that addresses the main feature at hand:
- the client-side command `\?` in `cockroach sql` now prints out a description of each option.
- the syntax check enabled by `check_syntax` now runs server-side.

See the two individual commits for details.

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21119#-:-L1ZBJ21JHg1rQUwbW-x:bnfp4nl)*

**Comment by knz** [comment]
TFYR

**Comment by jseldess** [comment]
@knz, in regards to: 
> the client-side command \? in cockroach sql now prints out a description of each option.

I can't see any difference between 1.1 and 2.0. In both cases, `\?` within the interactive shell prints something like:

```
You are using 'cockroach sql', CockroachDB's lightweight SQL client.
Type:
  \q to exit        (Ctrl+C/Ctrl+D also supported)
  \! CMD            run an external command and print its results on standard output.
  \| CMD            run an external command and run its output as SQL statements.
  \set [NAME]       set a client-side flag or (without argument) print the current settings.
  \unset NAME       unset a flag.
  \show             during a multi-line statement or transaction, show the SQL entered so far.
  \? or "help"      print this help.
  \h [NAME]         help on syntax of SQL commands.
  \hf [NAME]        help on SQL built-in functions.

More documentation about our SQL dialect and the CLI shell is available online:
https://www.cockroachlabs.com/docs/v2.0/sql-statements.html
https://www.cockroachlabs.com/docs/v2.0/use-the-built-in-sql-client.html
```

Can you clarify what changed?

**Comment by knz** [comment]
Yes, sorry the commit message was incorrect. It was meant to say that `\set` now prints a description. For example:

```
root@:26257/> \set
+----------------+--------+--------------------------------------------------------------------------+
|     Option     | Value  |                               Description                                |
+----------------+--------+--------------------------------------------------------------------------+
| check_syntax   | true   | check the SQL syntax before running a query (needs SHOW SYNTAX support   |
|                |        | on the server)                                                           |
| display_format | pretty | the output format for tabular data (pretty, csv, tsv, html, sql,         |
|                |        | records, raw)                                                            |
| echo           | false  | show SQL queries before they are sent to the server                      |
| errexit        | false  | exit the shell upon a query error                                        |
| show_times     | true   | display the execution time after each query                              |
| smart_prompt   | true   | print connection and session metadata in the prompt                      |
+----------------+--------+--------------------------------------------------------------------------+
```

**Comment by jseldess** [comment]
Hmm, we had already mentioned that [in v1.1](https://www.cockroachlabs.com/docs/dev/use-the-built-in-sql-client.html#sql-shell-options-changed-in-v1-1). Perhaps the docs were premature and now just don't need to be updated?

> To see current settings, use \set without any options.

**Comment by knz** [comment]
`\set` in 1.1 would only print the name of the options and the current setting.

In 2.0 there is also a new "description" column.

**Pull request merged**
