### PR TITLE
opt: do not allow references to inaccessible columns with table prefix

### LINKED ISSUE #70879: Inaccessible columns should not be referencable in a query
Inaccessible columns should not be accessible. In some cases they are not:

```
defaultdb> CREATE TABLE t (a INT, INDEX ((a + 1)));
CREATE TABLE

defaultdb> SELECT crdb_internal_idx_expr FROM t;
ERROR: column "crdb_internal_idx_expr" does not exist

defaultdb> SELECT * FROM t WHERE crdb_internal_idx_expr = 1;
ERROR: column "crdb_internal_idx_expr" does not exist
```

But if they are qualified, they are accessible:

```
defaultdb> SELECT t.crdb_internal_idx_expr FROM t;
  crdb_internal_idx_expr
--------------------------
(0 rows)


defaultdb> SELECT * FROM t WHERE t.crdb_internal_idx_expr = 1;
  a
-----
(0 rows)
```

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: mark expression index columns as inaccessible in test catalog

Expression index columns are now marked as inaccessible rather than
hidden in the test catalog, matching the behavior of the opt catalog.

Release note: None

#### opt: do not allow references to inaccessible columns with table prefix

In optbuilder, the logic for resolving column names that don't have
prefixes is separate from the logic for resolving columns names with
prefixes, such as a table name. Prior to this commit, the latter did not
check the visibility of columns during resolution. This allowed
inaccessible columns to be referenced in queries by prefixing the
inaccessible columns with the table name.

Fixes #70879

Release note (bug fix): A bug has been fixed which allowed queries to
reference internal columns created by the system for expression indexes.
These columns, which had names prefixed with "crdb_internal_idx_expr",
can no longer be referenced in queries. This bug was present since
version 21.2 when expression indexes were released.

### CODE REVIEW

**Review by rharding6373 — APPROVED** [review]
:lgtm: But since I don't know much about column visibility you may want to wait for Radu's approval.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74245#-:-MrcQkTf1B4pWfTbnZYw:bo66feg)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/scope.go, line 929 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74245#-MrcPhJe7_XBz-QPgvCL:-MrcPhJe7_XBz-QPgvCM:b-32s5x7) ([raw file](https://github.com/cockroachdb/cockroach/blob/25972fdb55b187ef9887ae89b86095c25ded12a6/pkg/sql/opt/optbuilder/scope.go#L929)):*
> ```Go
> 	for i := range inScope.cols {
> 		col := &inScope.cols[i]
> 		if col.visibility != inaccessible &&
> ```

Does this mean that if a table has hidden columns that we can still match on them? Can you point to a test that uses hidden columns in this way?

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74245)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @rharding6373)

___
*[pkg/sql/opt/optbuilder/scope.go, line 929 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74245#-MrcPhJe7_XBz-QPgvCL:-MrcZWuFCbVPE-jSFH63:b-ouf797) ([raw file](https://github.com/cockroachdb/cockroach/blob/25972fdb55b187ef9887ae89b86095c25ded12a6/pkg/sql/opt/optbuilder/scope.go#L929)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Does this mean that if a table has hidden columns that we can still match on them? Can you point to a test that uses hidden columns in this way?
</blockquote></details>

Right. A good example is the hidden `rowid` column added to tables without explicit primary keys. I added a logic test that shows this, since I couldn't find a great example for you.

There are actually different "levels" of hidden. If you want to really dive into the rabbit hole, see #66380 and:https://github.com/cockroachdb/cockroach/blob/a121be591d3fe5f9db3199cc5c72f9eeac01cfe5/pkg/sql/opt/optbuilder/scope_column.go#L74-L92.

**Review by rharding6373 — APPROVED** [review]
> Reviewed 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74245)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/scope.go, line 929 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74245#-MrcPhJe7_XBz-QPgvCL:-Mrcf4bt406nW4QnSL5v:bkkra11) ([raw file](https://github.com/cockroachdb/cockroach/blob/25972fdb55b187ef9887ae89b86095c25ded12a6/pkg/sql/opt/optbuilder/scope.go#L929)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Right. A good example is the hidden `rowid` column added to tables without explicit primary keys. I added a logic test that shows this, since I couldn't find a great example for you.

There are actually different "levels" of hidden. If you want to really dive into the rabbit hole, see #66380 and:https://github.com/cockroachdb/cockroach/blob/a121be591d3fe5f9db3199cc5c72f9eeac01cfe5/pkg/sql/opt/optbuilder/scope_column.go#L74-L92.  
</blockquote></details>

:thumbsup: Thanks!

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74245#-:-MrcgnuB0WX-W2r_50AS:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
