### PR TITLE
sql/schemachanger: implement ADD COLUMN for serial sequences

### LINKED ISSUE #126900: ALTER TABLE ADD COLUMN add DSC support for SERIAL
**Is your feature request related to a problem? Please describe.**
This is one of the missing pieces to support ALTER TABLE ADD COLUMN fully in the declarative schema changer.

**Describe the solution you'd like**

Jira issue: CRDB-40178

Epic CRDB-31282

### PR DESCRIPTION
**Pull request by fqazi**
Previously, the ADD COLUMN implementation in the declarative schema
changer only supported SERIAL columns with the normalization type of
rowid. This patch adds support for all other serial normalization modes
for serial columns during add column in the declarative schema changer.

Fixes: #126900

Release note: None

### CODE REVIEW

**Review by spilchen — CHANGES_REQUESTED** [review]
This looks good. I just had a couple of minor questions/comments.

> Reviewed 2 of 2 files at r1, 4 of 4 files at r2, 61 of 61 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136413#-:-OD6Z50F4gZjxpVkj8qp:b-9ngnv9)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/schemachanger/testdata/end_to_end/add_column_serial_simple_sequence_cached_node/add_column_serial_simple_sequence_cached_node.definition` line 4 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/136413#-OD6T2ju4f1JZ_Uk3Jum:-OD6T2ju4f1JZ_Uk3Jun:b4dewvb) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c41f3da53bac370f2993a4a60d9672a303a14ea/pkg/sql/schemachanger/testdata/end_to_end/add_column_serial_simple_sequence_cached_node/add_column_serial_simple_sequence_cached_node.definition#L4)):*
> ```
> CREATE DATABASE db;
> CREATE TABLE db.public.tbl (i INT PRIMARY KEY);
> SET serial_normalization='sql_sequence_cached_node';
> ```

This isn’t related to this change, but I noticed that this setting isn’t documented externally. I’m not sure if that was intentional.
___
*[`pkg/sql/schemachanger/testdata/end_to_end/add_column_serial_simple_sequence/add_column_serial_simple_sequence.definition` line 0 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/136413#-OD6IqA26d8jYPm95dRE:-OD6IqA26d8jYPm95dRF:b-iu14pr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c41f3da53bac370f2993a4a60d9672a303a14ea/pkg/sql/schemachanger/testdata/end_to_end/add_column_serial_simple_sequence/add_column_serial_simple_sequence.definition#L0)):*
Can we add test coverage for this to TestAlterTableDMLInjection?
___
*[`pkg/sql/schemachanger/testdata/end_to_end/add_column_serial_simple_sequence/add_column_serial_simple_sequence.definition` line 0 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/136413#-OD6L2gEEeqrXz83xb8f:-OD6L2gEEeqrXz83xb8g:b-li8xyi) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c41f3da53bac370f2993a4a60d9672a303a14ea/pkg/sql/schemachanger/testdata/end_to_end/add_column_serial_simple_sequence/add_column_serial_simple_sequence.definition#L0)):*
We already had an existing add column serial test, which I'm guessing is used to test when `rowid` is used. Would it make sense to rename `add_column_serial` to `add_column_serial_rowid` so that we are clear about what's being tested?
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go` line 224 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/136413#-OD6WTCA4lTLYTUGUFQn:-OD6WTCA4lTLYTUGUFQo:b5dvmkz) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c41f3da53bac370f2993a4a60d9672a303a14ea/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go#L224)):*
> ```Go
> 		} else {
> 			// Otherwise, a sequence was created above and assigned.
> 			b.Add(&scpb.SequenceOwner{
> ```

It doesn't seem intuitive to assume the presence of a sequence just because `colDefaultExpression` is non-nil—I don't see a clear connection there. Also, wouldn’t the `SequenceOwner` typically be added in `doCreateSequence`? If it isn’t, perhaps we should update that function to handle it, as it already sets up the other elements for the new column.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go` line 288 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/136413#-OD6TlQZC5-OSlW4XQ-X:-OD6TlQZC5-OSlW4XQ-Y:bbm1dul) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c41f3da53bac370f2993a4a60d9672a303a14ea/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go#L288)):*
> ```Go
> 		defType.Name(), b.SessionData().SerialNormalizationMode.String()))
> 
> 	serialNormalizationMode := b.SessionData().SerialNormalizationMode
> ```

nit: this code block looks to be duplicated from `CREATE TABLE`. Should we consider making a helper function and use it in both places?
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go` line 318 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/136413#-OD6VFW1C41MVkTYa3UE:-OD6VFW1C41MVkTYa3UF:b-ghp3ah) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c41f3da53bac370f2993a4a60d9672a303a14ea/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go#L318)):*
> ```Go
> 	}
> 
> 	// Start with a fixed sequence number and find the first one
> ```

Does this name resolution logic account for cases where a single `ALTER` statement adds multiple `SERIAL` columns? Additionally, does it handle scenarios where an earlier `ALTER` statement within an explicit transaction added a `SERIAL` column?
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go` line 340 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/136413#-OD6QjfQ2fz_8OubXqVi:-OD6QjfQ2fz_8OubXqVj:bexwzx0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c41f3da53bac370f2993a4a60d9672a303a14ea/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go#L340)):*
> ```Go
> 	}
> 
> 	seqOptions := tree.SequenceOptions{}
> ```

This code block appears to be shared with the `CREATE TABLE` logic in `sql/serial.go`. Could we extract it into a helper function and reuse it for the `CREATE` case to avoid duplicating this logic?
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go` line 341 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/136413#-OD6Pp--2_UIlu9kDSpK:-OD6Pp--2_UIlu9kDSpL:b-bvpxxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c41f3da53bac370f2993a4a60d9672a303a14ea/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go#L341)):*
> ```Go
> 
> 	seqOptions := tree.SequenceOptions{}
> 	switch serialNormalizationMode {
> ```

Can we add an assertion for the default case?
___
*[`pkg/sql/logictest/testdata/logic_test/alter_table` line 3997 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/136413#-OD6Ua9l2IHjCDx5c-Be:-OD6Ua9l2IHjCDx5c-Bf:bt36fn7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c41f3da53bac370f2993a4a60d9672a303a14ea/pkg/sql/logictest/testdata/logic_test/alter_table#L3997)):*
> ```
> SET serial_normalization = sql_sequence
> 
> statement error .*nextval\(\): unimplemented: cannot evaluate scalar expressions containing sequence operations in this context.*
> ```

Should we expand the logic tests? For example, we could verify the schema after adding the column and include tests for other `serial_normalization` options.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136413)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go` line 224 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/136413#-OD6WTCA4lTLYTUGUFQn:-OD7dG3J2BFeOkol3UwQ:b-u49mjh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c41f3da53bac370f2993a4a60d9672a303a14ea/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go#L224)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

It doesn't seem intuitive to assume the presence of a sequence just because `colDefaultExpression` is non-nil—I don't see a clear connection there. Also, wouldn’t the `SequenceOwner` typically be added in `doCreateSequence`? If it isn’t, perhaps we should update that function to handle it, as it already sets up the other elements for the new column.
</blockquote></details>

That is fair I renamed this to: `colSerialDefaultExpression`. 

The other problem is that this suffers from the chicken and the egg problem, where we need the column to exist before the sequence owner can be assigned. I added the following comment:

// Otherwise, a serial column is being created. The sequence was created  
// above, but the owner could not be assigned, since the column does not  
// exist. So manually create the element here, since the CREATE SEQUENCE  
// code path cannot resolve the column.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go` line 318 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/136413#-OD6VFW1C41MVkTYa3UE:-OD7i52Y8QoFmJ6dEut6:b-801c67) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c41f3da53bac370f2993a4a60d9672a303a14ea/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go#L318)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Does this name resolution logic account for cases where a single `ALTER` statement adds multiple `SERIAL` columns? Additionally, does it handle scenarios where an earlier `ALTER` statement within an explicit transaction added a `SERIAL` column?
</blockquote></details>

Let me add logic tests, but this works correctly for both cases. Including the case where the explicit sequence creates the same name.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go` line 341 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/136413#-OD6Pp--2_UIlu9kDSpK:-OD7k01d9O0XbPeCLyH2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c41f3da53bac370f2993a4a60d9672a303a14ea/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go#L341)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Can we add an assertion for the default case?
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/alter_table` line 3997 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/136413#-OD6Ua9l2IHjCDx5c-Be:-OD8NdeD-ltdKDyyjNpb:bh243sd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c41f3da53bac370f2993a4a60d9672a303a14ea/pkg/sql/logictest/testdata/logic_test/alter_table#L3997)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Should we expand the logic tests? For example, we could verify the schema after adding the column and include tests for other `serial_normalization` options.
</blockquote></details>

Done.

Adding more logic tests in add_table to test all serialization modes.
___
*[`pkg/sql/schemachanger/testdata/end_to_end/add_column_serial_simple_sequence/add_column_serial_simple_sequence.definition` line  at r3](https://reviewable.io/reviews/cockroachdb/cockroach/136413#-OD6L2gEEeqrXz83xb8f:-OD8VYHp0-HzlplKLgbM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c41f3da53bac370f2993a4a60d9672a303a14ea/pkg/sql/schemachanger/testdata/end_to_end/add_column_serial_simple_sequence/add_column_serial_simple_sequence.definition#L)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

We already had an existing add column serial test, which I'm guessing is used to test when `rowid` is used. Would it make sense to rename `add_column_serial` to `add_column_serial_rowid` so that we are clear about what's being tested?
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/testdata/end_to_end/add_column_serial_simple_sequence/add_column_serial_simple_sequence.definition` line  at r3](https://reviewable.io/reviews/cockroachdb/cockroach/136413#-OD6IqA26d8jYPm95dRE:-OD8YliND_pY2pRVtSGg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c41f3da53bac370f2993a4a60d9672a303a14ea/pkg/sql/schemachanger/testdata/end_to_end/add_column_serial_simple_sequence/add_column_serial_simple_sequence.definition#L)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Can we add test coverage for this to TestAlterTableDMLInjection?
</blockquote></details>

Done.

**Review by spilchen — APPROVED** [review]
:lgtm: Thanks for addressing the code review comments.

> Reviewed 64 of 64 files at r6, 4 of 4 files at r7, 2 of 3 files at r8, 60 of 62 files at r9, 14 of 14 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136413#-:-ODBZ5QL6eTyeEzr53fD:b74wpb7)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/schemachanger/scbuild/builder_test.go` line 100 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/136413#-ODBT0Az7WG90GIm8Vli:-ODBT0Az7WG90GIm8Vlj:b-wnozoo) ([raw file](https://github.com/cockroachdb/cockroach/blob/9392ee31b248f61187782bc9db508dd5dcb76be0/pkg/sql/schemachanger/scbuild/builder_test.go#L100)):*
> ```Go
> 										sd.ApplicationName = ""
> 										sd.EnableUniqueWithoutIndexConstraints = true
> 										sd.AlterColumnTypeGeneralEnabled = true
> ```

This might be a merge issue, but I recently removed this line. It’s no longer needed since we don’t require the enable setting for altering column types unless operating in a mixed-version environment.
___
*[`pkg/sql/show_create_clauses.go` line 623 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/136413#-ODBWe6J91VBg2vHLZzX:-ODBWe6J91VBg2vHLZzY:b-a9ovyx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e652047da83ba37e17aaadf226acde4556152e34/pkg/sql/show_create_clauses.go#L623)):*
> ```Go
> 		f.Printf(" CACHE %d", opts.CacheSize)
> 	}
> 	if opts.NodeCacheSize > 1 {
> ```

If I'm reading the code correctly in `incrementSequenceUsingCache` (`sql/sequence.go`), a node cache is used if `opts.CacheSize` is 1 and `opts.NodeCacheSize` > 0.



_Suggestion:_
```Go
if opts.CacheSize == 1 && opts.NodeCacheSize > 0
```
___
*[`pkg/sql/schemachanger/sctest/end_to_end.go` line 142 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/136413#-ODBTjAw3d863w9KkgXm:-ODBTjAw3d863w9KkgXn:b-wnozoo) ([raw file](https://github.com/cockroachdb/cockroach/blob/9392ee31b248f61187782bc9db508dd5dcb76be0/pkg/sql/schemachanger/sctest/end_to_end.go#L142)):*
> ```Go
> 						sd.ApplicationName = ""
> 						sd.EnableUniqueWithoutIndexConstraints = true // this allows `ADD UNIQUE WITHOUT INDEX` in the testing suite.
> 						sd.AlterColumnTypeGeneralEnabled = true
> ```

This might be a merge issue, but I recently removed this line. It’s no longer needed since we don’t require the enable setting for altering column types unless operating in a mixed-version environment.
___
*[`pkg/sql/serial.go` line 195 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136413#-ODBUIXWBJfCOiEw17UI:-ODBUIXWBJfCOiEw17UJ:b-ht5ud8) ([raw file](https://github.com/cockroachdb/cockroach/blob/84c161f1b2ee8b0e34d977836a7a20f367bbfc32/pkg/sql/serial.go#L195)):*
> ```Go
> 	if serialNormalizationMode == sessiondatapb.SerialUsesVirtualSequences {
> 		seqType = "virtual "
> 		seqOpts = virtualSequenceOpts
> ```

nit: I think we can remove `virtualSequenceOpts` now. Same with `realSequenceOpts`

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136413)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @spilchen)

___
*[`pkg/sql/show_create_clauses.go` line 623 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/136413#-ODBWe6J91VBg2vHLZzX:-ODC4PXW4h0pDkmi58q_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e652047da83ba37e17aaadf226acde4556152e34/pkg/sql/show_create_clauses.go#L623)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

If I'm reading the code correctly in `incrementSequenceUsingCache` (`sql/sequence.go`), a node cache is used if `opts.CacheSize` is 1 and `opts.NodeCacheSize` > 0.
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/sctest/end_to_end.go` line 142 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/136413#-ODBTjAw3d863w9KkgXm:-ODC57Hg-wmPw1q8F8pj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9392ee31b248f61187782bc9db508dd5dcb76be0/pkg/sql/schemachanger/sctest/end_to_end.go#L142)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

This might be a merge issue, but I recently removed this line. It’s no longer needed since we don’t require the enable setting for altering column types unless operating in a mixed-version environment.
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/testdata/end_to_end/add_column_serial_simple_sequence_cached_node/add_column_serial_simple_sequence_cached_node.definition` line 4 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/136413#-OD6T2ju4f1JZ_Uk3Jum:-ODC5BX392FdY0eeKoTf:bsm5eo2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c41f3da53bac370f2993a4a60d9672a303a14ea/pkg/sql/schemachanger/testdata/end_to_end/add_column_serial_simple_sequence_cached_node/add_column_serial_simple_sequence_cached_node.definition#L4)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

This isn’t related to this change, but I noticed that this setting isn’t documented externally. I’m not sure if that was intentional.
</blockquote></details>

I think there is a doc issue open for it: https://cockroachlabs.atlassian.net/browse/DOC-9830
___
*[`pkg/sql/schemachanger/scbuild/builder_test.go` line 100 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/136413#-ODBT0Az7WG90GIm8Vli:-ODC59U2CKmHZrVS5d7O:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9392ee31b248f61187782bc9db508dd5dcb76be0/pkg/sql/schemachanger/scbuild/builder_test.go#L100)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

This might be a merge issue, but I recently removed this line. It’s no longer needed since we don’t require the enable setting for altering column types unless operating in a mixed-version environment.
</blockquote></details>

Done.

**Review by spilchen — COMMENTED** [review]
> Reviewed 1 of 1 files at r11, 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136413)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi)

___
*[`pkg/sql/show_create_clauses.go` line 623 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/136413#-ODBWe6J91VBg2vHLZzX:-ODCaDla3zjq9t4DGKOd:b-4lxqil) ([raw file](https://github.com/cockroachdb/cockroach/blob/e652047da83ba37e17aaadf226acde4556152e34/pkg/sql/show_create_clauses.go#L623)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Is `opts.NodeCacheSize` checking the correct value? I think it's should be `> 0` not `> 1`.
___
*[`pkg/sql/schemachanger/scbuild/builder_test.go` line 100 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/136413#-ODBT0Az7WG90GIm8Vli:-ODCa_VL8ofhGoe3F-vL:b-afcr0z) ([raw file](https://github.com/cockroachdb/cockroach/blob/9392ee31b248f61187782bc9db508dd5dcb76be0/pkg/sql/schemachanger/scbuild/builder_test.go#L100)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Hmm, I still see the `AlterColumnTypeGeneralEnabled` setting here. It's fixed in the other spot though.

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136413)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi)

___
*[`pkg/sql/schemachanger/testdata/end_to_end/add_column_serial_simple_sequence_cached_node/add_column_serial_simple_sequence_cached_node.definition` line 4 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/136413#-OD6T2ju4f1JZ_Uk3Jum:-ODCb9Mg4V0nBXT681bN:bzbpuo3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c41f3da53bac370f2993a4a60d9672a303a14ea/pkg/sql/schemachanger/testdata/end_to_end/add_column_serial_simple_sequence_cached_node/add_column_serial_simple_sequence_cached_node.definition#L4)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

I think there is a doc issue open for it: https://cockroachlabs.atlassian.net/browse/DOC-9830
</blockquote></details>

Thanks for confirming.

**Comment by fqazi** [comment]
@spilchen TFTR!

bors r+

**Pull request merged**
