### PR TITLE
ccl/sqlproxyccl: allow non-TLS connections, expose Done channel

### PR DESCRIPTION
**Pull request by jbowens**
ccl/sqlproxyccl: expose a connection Done channel 

Expose a per-connection Done channel to package consumers. This will be
used by the CC superuser sql proxy to clean up auxiliary resources when
connections are terminated.

ccl/sqlproxyccl: allow insecure non-TLS connections

Allow sqlproxy to be configured without TLS for either the incoming or
outgoing connections. This is helpful for the Cockroach Cloud local
development environment which by default does not use TLS.

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57037#-:-MMr27bB22aQ5U6CBHGs:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens and @petermattis)

___
*[pkg/ccl/sqlproxyccl/server.go, line 166 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57037#-MMr1QeCBaaS5orKEa41:-MMr1QeCBaaS5orKEa42:bjz390o) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ae1dd0d324c267f186b1d89f1a701ec89d17567/pkg/ccl/sqlproxyccl/server.go#L166)):*
> ```Go
> 	net.Conn
> 
> 	mu       sync.Mutex
> ```

Nit: use the unnamed struct pattern to clearly delineate which members the mutex protects.

```
mu struct {
  sync.Mutex
  closed bool
  closeCh chan struct{}
}
```
___
*[pkg/ccl/sqlproxyccl/server.go, line 186 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57037#-MMr1dV36bwzxa_h3ILo:-MMr1dV36bwzxa_h3ILp:b-xktr3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ae1dd0d324c267f186b1d89f1a701ec89d17567/pkg/ccl/sqlproxyccl/server.go#L186)):*
> ```Go
> 		c.closed = true
> 	}
> 	return c.Conn.Close()
> ```

Is it harmful to call close more than once?

**Review by jbowens — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57037#-:-MMrFy8MALmTtK01xnpP:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @petermattis)

___
*[pkg/ccl/sqlproxyccl/server.go, line 186 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57037#-MMr1dV36bwzxa_h3ILo:-MMrFnWA5PRANd-HyyMl:b7oaeiy) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ae1dd0d324c267f186b1d89f1a701ec89d17567/pkg/ccl/sqlproxyccl/server.go#L186)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is it harmful to call close more than once?
</blockquote></details>

I don't think so, but it seems prudent to avoid the double call just in case. Done.

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57037)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @petermattis)

**Review by jbowens — COMMENTED** [review]
This PR fails the staticcheck linter because:
```
func (*Conn).Done is unused (U1001)
```
but `Done` is a method that we're exposing so that it may be consumed by the managed-service repo. Is there a custom we follow for this? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57037#-:-MMulj5XCh435QewJYFM:bqmiw4j)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @petermattis)

**Review by petermattis — COMMENTED** [review]
```
var _ = (*Conn)(nil).Done // silence unused lint
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57037#-:-MMuoqoDC_tMGdjHm2a3:b8abxad)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @petermattis)

**Pull request merged**
