### PR TITLE
stats: move and extend recently introduced test 

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit moves recently introduced test from one file to another. Initially, this test needed to be in `stats_test` package - in order to avoid import cycle - because it was importing stuff from `sql`, but later revisions removed that import.

Additionally, the test is extended to verify the behavior of the limit on the number of dropped tables processed at once by the stats garbage collector.

Also the buffer of the channel for the interval setting change is increased from 1 to 4 to make it a bit safer.

Epic: None

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105522#-:-NYp2U2W5YqyYx4ygroO:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/sql/stats/delete_stats_test.go` line 708 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105522#-NYp293849ND1eGPI2Jb:-NYp293849ND1eGPI2Jc:bww4l9q) ([raw file](https://github.com/cockroachdb/cockroach/blob/8af5caf7dbcca25d1d1c5bda0ae5cc86b9678631/pkg/sql/stats/delete_stats_test.go#L708)):*
> ```Go
> 	runner.Exec(t, "DROP TABLE t;")
> 	testutils.SucceedsSoon(t, func() error {
> 		runner.QueryRow(t, `SELECT count(*) FROM system.table_statistics WHERE "tableID" = $1;`, tableID).Scan(&count)
> ```

While you're here... I  was thinking it would be good to test that the limit works as expected. So perhaps you could try adjusting the cluster setting to reduce the limit from 1000 to, say, 2 -- and make sure at most 2 tables are deleted?

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105522#-:-NYu-FmS7Dw0fQeFR8Ve:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

___
*[`pkg/sql/stats/delete_stats_test.go` line 708 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105522#-NYp293849ND1eGPI2Jb:-NYtzgjS8UNOASLUC8Yr:bn1g7br) ([raw file](https://github.com/cockroachdb/cockroach/blob/8af5caf7dbcca25d1d1c5bda0ae5cc86b9678631/pkg/sql/stats/delete_stats_test.go#L708)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

While you're here... I  was thinking it would be good to test that the limit works as expected. So perhaps you could try adjusting the cluster setting to reduce the limit from 1000 to, say, 2 -- and make sure at most 2 tables are deleted?
</blockquote></details>

Added another subtest to verify this. It seems to be a bit tricky (without introduction of testing knobs) to control precisely how many tables are deleted in a single sweep, so, instead, this new subtest ensures that for five tables at least two sweeps occur when the limit of 1 is used. This seems to be non-flaky and reasonable enough.

**Comment by yuzefovich** [comment]
I'll increase the channel's buffer to make the change a tad safer.

bors r-

**Pull request merged**
