### PR TITLE
release-20.2: sql: make multi-tenancy errors report to telemetry

### PR DESCRIPTION
**Pull request by knz**
Backport 2/2 commits from #54256.

/cc @cockroachdb/release

---

### CODE REVIEW

**Review by asubiotto — APPROVED** [review]
LGTM pending review in release meeting.

**Comment by knz** [comment]
@asubiotto ok to merge as per latest guidelines?

**Comment by asubiotto** [comment]
Yes 🟢

**Comment by knz** [comment]
Thanks!

**Pull request merged**
