### PR TITLE
changefeedccl: Add metrics scope library for changefeeds.

### PR DESCRIPTION
**Pull request by miretskiy**
Add a utility library that allows creation of fixed number (8) of
custome "metric" scopes.  Each scope is intended to keep track of
a small set of SLI related metrics.
Scopes are named "tier0", "tier1", ... "tier7".

Follow on changes will integrate changefeed code with this library.

CRDB-2422

Release Notes: None

### CODE REVIEW

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71875)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @samiskin)

___
*[pkg/ccl/changefeedccl/cdcutils/metrics_scope.go, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71875#-Mmcwg6pzhjVNUE11Lkd-r1-19:-MmdRJSz-v4tAg83hdBs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8aece3cf16a1590e00cf852e5897433228e42e33/pkg/ccl/changefeedccl/cdcutils/metrics_scope.go#L19)):*
<details><summary><i>Previously, samiskin (Shiranka Miskin) wrote…</i></summary><blockquote>

It could be nice to add some context here on why we have a fixed limit in the first place, mentioning that the limitation is from the metrics registry.
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/cdcutils/metrics_scope.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71875#-Mmcwg6pzhjVNUE11Lkd-r1-47:-MmdQorw0mmpy7PkpcQt:br9e52w) ([raw file](https://github.com/cockroachdb/cockroach/blob/8aece3cf16a1590e00cf852e5897433228e42e33/pkg/ccl/changefeedccl/cdcutils/metrics_scope.go#L47)):*
<details><summary><i>Previously, samiskin (Shiranka Miskin) wrote…</i></summary><blockquote>

What do you think about renaming `SLIScope` to `ScopedSLI` and `NewScopedSLI()`?  Just sounds weird to me to have `SLIScope.Scopes`, while "ScopedSLI" still fits with multiple scopes
</blockquote></details>

Not sure I like: ScopedX to me means that the object X is scoped -- like an object that gets destroyed when it goes out of scope.
These metrics never go out of scope.
But the SLIScope returns sli metrics associated with scope.  Perhaps I could replace scope with `namespace`? Not sure.. scope is kinda nice and short.

**Review by samiskin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71875)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @samiskin)

___
*[pkg/ccl/changefeedccl/cdcutils/metrics_scope.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71875#-Mmcwg6pzhjVNUE11Lkd-r1-47:-MmsFdgeCgPhQAjnydi4:bvhllgc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8aece3cf16a1590e00cf852e5897433228e42e33/pkg/ccl/changefeedccl/cdcutils/metrics_scope.go#L47)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Not sure I like: ScopedX to me means that the object X is scoped -- like an object that gets destroyed when it goes out of scope.
These metrics never go out of scope.
But the SLIScope returns sli metrics associated with scope.  Perhaps I could replace scope with `namespace`? Not sure.. scope is kinda nice and short.
</blockquote></details>

Ah thats true.  What about `SLIScopes` and `CreateSLIScopes()`?  At least then "Scope" solely means "A namespace for metrics", and "SLIScopes" is "A container of SLI scopes", rather than the term "Scope" referring to both the namespace and the container.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71875)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @samiskin)

___
*[pkg/ccl/changefeedccl/cdcutils/metrics_scope.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71875#-Mmcwg6pzhjVNUE11Lkd-r1-47:-Mmsf8Uj5mH8dXorbvKp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8aece3cf16a1590e00cf852e5897433228e42e33/pkg/ccl/changefeedccl/cdcutils/metrics_scope.go#L47)):*
<details><summary><i>Previously, samiskin (Shiranka Miskin) wrote…</i></summary><blockquote>

Ah thats true.  What about `SLIScopes` and `CreateSLIScopes()`?  At least then "Scope" solely means "A namespace for metrics", and "SLIScopes" is "A container of SLI scopes", rather than the term "Scope" referring to both the namespace and the container.
</blockquote></details>

Done.

**Review by samiskin — APPROVED** [review]
✨

**Comment by rafiss** [comment]
@miretskiy @samiskin  friendly ping - does this still need to be backported?

**Comment by miretskiy** [comment]
Nope

**Comment by rafiss** [comment]
Thanks! Then I will remove the backport labels.

**Pull request merged**
