### PR TITLE
sql: open a transaction for BindCmd

### LINKED ISSUE #64140: sql: hazardous use of descriptors in BIND outside of explicit transaction
**Describe the problem**

In SQL you can bind arguments to a prepared statement outside of a transaction. This generally happens in the binary wire protocol if I understand correctly. The client will prepare a statement and then it will bind the arguments to an unnamed portal and then it will execute the portal. The prepare is safe and fine because we'll re-acquire leases inside the implicit transaction when checking if the plan is stale. The bind, however, has a hazardous and unsafe properties. 

When the type of argument to a bind is either a user-defined type or refers to an OID type by name, we resolve the type and value during while doing the `BIND`. This is problematic because it will use the transaction currently sitting on the `connExecutor`. This is generally the previously committed transaction (I suspect there may be cases where this is nil but I don't know). This happens here (with the regclass/regtype resolution happening underneath `tree.ParseDOid`):
https://github.com/cockroachdb/cockroach/blob/d91205fab5a8b943a2d61e2b71bd201f5d477f0d/pkg/sql/conn_executor_prepare.go#L368-L381

At that point we'll attach a deadline due to leasing to an already committed transaction. If we attach the following sane invariant to the deadline code we get failures right and left:

```go
--- a/pkg/kv/txn.go
+++ b/pkg/kv/txn.go
@@ -695,6 +695,9 @@ func (txn *Txn) UpdateDeadlineMaybe(ctx context.Context, deadline hlc.Timestamp)
 
        txn.mu.Lock()
        defer txn.mu.Unlock()
+       if txn.status().IsFinalized() {
+               panic(errors.WithContextTags(errors.AssertionFailedf("UpdateDeadlineMaybe() called on finalized txn"), ctx))
+       }
``` 

Worse yet are cases where we cannot use a cached, leased descriptor, like a number of system tables. For example, the following test fails rather surprisingly with this error:

```go
func TestRegclassBind(t *testing.T) {
	defer leaktest.AfterTest(t)()
	defer log.Scope(t).Close(t)

	ctx := context.Background()
	tc := testcluster.StartTestCluster(t, 1, base.TestClusterArgs{})
	defer tc.Stopper().Stop(ctx)
	_, err := tc.ServerConn(0).Exec("SELECT $1::REGCLASS::INT", "system.descriptor")
	require.NoError(t, err)
}
```
```
    system_table_test.go:48: 
        	Error Trace:	system_table_test.go:48
        	Error:      	Received unexpected error:
        	            	pq: error in argument for $1: TransactionStatusError: client already committed or rolled back the transaction. Trying to execute: 1 Get (REASON_UNKNOWN)
        	Test:       	TestRegclassBind
```

**Possible Solution**

It seems to me like we should move the conn executor into an open state when binding (or when creating a portal?). It feels weird to me to have a bound portal outside of a transaction. I may not know enough to know though. We do this already for example when processing an `ExecCmd`. 

**Additional context**

There are some edge cases where I think we may miss renames or interpret arguments as the wrong type. It's more just a general soundness problem.

Jira issue: CRDB-6916

### PR DESCRIPTION
**Pull request by ajwerner**
Bind needs to evaluate casts for oid types and look up user-defined types.
It needs a transaction to do that. It's a miracle that this ever works. We get
away with it for the most part because we allow calling `UpdateDeadlineMaybe`
on a txn which is finalized (see next commit) and in all of our tests we use
leasable tables.

This is so subtle I'm omitting a release note.

Fixes #64140.

Release note: None

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64162)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @fqazi, and @RaduBerinde)

___
*[pkg/sql/conn_executor_prepare.go, line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64162#-MZ00Mmx6JEdxV8SHyMb:-MZ00Mmx6JEdxV8SHyMc:b-ufs6ru) ([raw file](https://github.com/cockroachdb/cockroach/blob/09d94ca8625bf0169821a6c864905bca1a84c45d/pkg/sql/conn_executor_prepare.go#L308)):*
> ```Go
> // an event to open an implicit transaction. A transaction is needed to bind
> // arguments as binding arguments to a portal may references types and tables.
> func (ex *connExecutor) execBindInNoTxnState(
> ```

This doesn't seem like the right way to me... but I don't want to speak too authoritatively. Generating a `BeginTransaction` event seems quite heavyweight to me. Also I'm not sure how we finish that transaction - I don't see the equivalent event in `execBindInOpenState` (and to be honest I don't really want to know the answer to this :) ). It'd be great, in my opinion, if we keep bind working locally, without interfacing with the state machine if possible. So I'd like to see if it is, indeed, possible.
How does `Prepare` work? I remember being unhappy because `Prepares` create a `client.Txn` (locally, not through the state machine) for pretty bad reasons - just to that the lease machinery can get a timestamp to work with. But as bad as it is, doing things locally is still better than doing them through the state machine in my book. I don't know if that's still current or not. But I'd like to hear whether the needs of a Bind are different from the needs of a Prepare.

**Comment by ajwerner** [comment]
Prepare creates its own transaction to plan. The awkward thing with bind is we'll never know if the interpretation used to convert the arguments to typed expressions or datums is wrong. With prepare, we check again during exec whether the dependencies are still up to date.

Honestly, it's not clear to me that bind makes sense without an exec and therefore without entering the open state. I'm looking to be schooled here.

**Comment by ajwerner** [comment]
Anyway, the crux of the problem is that to do name resolution, you need a timestamp and you need leased descriptor versions; on some level you need a transaction to power that machinery. Then, when going to execute we check staleness by re-leasing the descriptors and making sure all of the versions match. For bind, however, we are throwing away the information we'd need to re-prepare them if the dependencies didn't match. By the time we're doing a bind, we do have a prepared statement, but we've lost the descriptor collection used to prepare it. On some level, the solution is to not attempt to resolve any names during `BIND`. That's almost viable for `regclass` etc but is not at all viable for types. 

We're in a bit of a pickle on this one.

**Comment by ajwerner** [comment]
I'm going to let this sit for a while. We decided we don't care that much about the edge cases here for now. They'll become harder to avoid as the resolution APIs change (which is good) but we're going to kick that can down the road a bit.

**Pull request closed without merging**
