### PR TITLE
sql: add errors to IndexedRow(s) interfaces

### PR DESCRIPTION
**Pull request by yuzefovich**
Adds an option of returning an error for tree.IndexedRow and
tree.IndexedRows methods.

Release note: None

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34465)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/window.go, line 1164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34465#-LXt5Gaw5gfOhTxIl08I:-LXt5Gaw5gfOhTxIl08J:bcfuf87) ([raw file](https://github.com/cockroachdb/cockroach/blob/e28792bd6fba6c67da251cfda0c466c823d311cc/pkg/sql/window.go#L1164)):*
> ```Go
> 	if idx < 0 || idx >= len(ir.rows) {
> 		return nil, errors.Errorf("index out of bounds")
> 	}
> ```

I think we should just leave these ones as panics, unless there's a reason you expect them to return errors now. The panic message has more information than this error, and it's a truly exceptional condition - we don't expect it to ever happen, and if it does, perhaps something is very broken.

Essentially I'd be happy to see the error added to the interfqace but only returned as non-nil in the new scenario you've introduced, unless there's another reason to add this error return that I'm not aware of.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34465)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/window.go, line 1164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34465#-LXt5Gaw5gfOhTxIl08I:-LXtpbD69f09pkQsXoik:b-l5sypc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e28792bd6fba6c67da251cfda0c466c823d311cc/pkg/sql/window.go#L1164)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think we should just leave these ones as panics, unless there's a reason you expect them to return errors now. The panic message has more information than this error, and it's a truly exceptional condition - we don't expect it to ever happen, and if it does, perhaps something is very broken.

Essentially I'd be happy to see the error added to the interfqace but only returned as non-nil in the new scenario you've introduced, unless there's another reason to add this error return that I'm not aware of.
</blockquote></details>

I agree with your point, nothing changed in the logic touched by this PR, so let's keep the panics here.

We want to return an error when we're iterating over the row container on disk if the error occurs, and maybe in some other cases we haven't thought of yet.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34465)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/sem/tree/window_funcs.go, line 127 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34465#-LXu4csZENVNb0WmBdSw:-LXu4csZENVNb0WmBdSx:bp8wy31) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0499847b96f7ec599ce037c0e7afdd54a27c5e6/pkg/sql/sem/tree/window_funcs.go#L127)):*
> ```Go
> 					valueAt, err := wfr.valueAt(i)
> 					if err != nil {
> 						panic(err)
> ```

Hmm... if we have to panic given an error in `valueAt` here, what's the value of adding the error output to `valueAt` in the first place? In your next PR, you're introducing other error cases from `valueAt`, right? So if we hit those here, we'll panic anyway?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34465)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/sem/tree/window_funcs.go, line 127 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34465#-LXu4csZENVNb0WmBdSw:-LXuMSmYBusFqEwvn0Rj:buhr1pe) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0499847b96f7ec599ce037c0e7afdd54a27c5e6/pkg/sql/sem/tree/window_funcs.go#L127)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Hmm... if we have to panic given an error in `valueAt` here, what's the value of adding the error output to `valueAt` in the first place? In your next PR, you're introducing other error cases from `valueAt`, right? So if we hit those here, we'll panic anyway?
</blockquote></details>

Good point, removed the changes. Yes, the error cases are different - I didn't think through it thoroughly, thanks.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34465)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/distsqlrun/windower.go, line 634 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34465#-LXuWURt8E3U1Gc14es0:-LXuWURt8E3U1Gc14es1:b86mi7c) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1ee9fe453fb186bb858ba2235d6c5aa0718dea8/pkg/sql/distsqlrun/windower.go#L634)):*
> ```Go
> 			frameRun.PeerHelper.Init(frameRun, peerGrouper)
> 			frameRun.CurRowPeerGroupNum = 0
> 			if sorter != nil {
> ```

Not sure whether it would be better to modify methods of PeerHelper to return an error as well. I feel probably not.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34465)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/distsqlrun/windower.go, line 634 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34465#-LXuWURt8E3U1Gc14es0:-LXu_grkBo8kCT17X4IL:bwk2grv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1ee9fe453fb186bb858ba2235d6c5aa0718dea8/pkg/sql/distsqlrun/windower.go#L634)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Not sure whether it would be better to modify methods of PeerHelper to return an error as well. I feel probably not.
</blockquote></details>

If this sorter checking is only happening because you know `Init` might touch the sorter, then I'd suggest bubbling up the error through `PeerHelper.Init` and so forth for sure. Otherwise somebody might call `Init` elsewhere and not know to check `sorter.err` since they don't have the foresight you do on this problem right now.
___
*[pkg/sql/distsqlrun/windower.go, line 657 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34465#-LXue93RChps_3rEKIyl:-LXue93RChps_3rEKIym:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1ee9fe453fb186bb858ba2235d6c5aa0718dea8/pkg/sql/distsqlrun/windower.go#L657)):*
> ```Go
> 				frameRun.PeerHelper.Update(frameRun)
> 				frameRun.CurRowPeerGroupNum++
> 				if sorter != nil {
> ```

ditto

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34465)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/distsqlrun/windower.go, line 634 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34465#-LXuWURt8E3U1Gc14es0:-LXuzy1C8y0CZ_9zxG1V:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1ee9fe453fb186bb858ba2235d6c5aa0718dea8/pkg/sql/distsqlrun/windower.go#L634)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

If this sorter checking is only happening because you know `Init` might touch the sorter, then I'd suggest bubbling up the error through `PeerHelper.Init` and so forth for sure. Otherwise somebody might call `Init` elsewhere and not know to check `sorter.err` since they don't have the foresight you do on this problem right now.
</blockquote></details>

Good point, done.
___
*[pkg/sql/distsqlrun/windower.go, line 657 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34465#-LXue93RChps_3rEKIyl:-LXv-1QlAP9itnQBwYyS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1ee9fe453fb186bb858ba2235d6c5aa0718dea8/pkg/sql/distsqlrun/windower.go#L657)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34465)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/sem/tree/window_funcs.go, line 391 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34465#-LXy8xZz0krYTnaHJ17z:-LXy8x_-0SRCzN9dT1qE:b-4by1c1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e6bd0cb58fd866b5c94183a4cbe3ab09e49ad13/pkg/sql/sem/tree/window_funcs.go#L391)):*
> ```Go
> 	row, err := wfr.Rows.GetRow(idx)
> 	if err != nil {
> 		panic(err)
> ```

I'm afraid you'll need to fix these ones too... We don't want an expected error to panic the server. Error plumbing is hard work!

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34465)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/sem/tree/window_funcs.go, line 391 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34465#-LXy8xZz0krYTnaHJ17z:-LXypYOB78JbDhlHZqg1:bfa8i1n) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e6bd0cb58fd866b5c94183a4cbe3ab09e49ad13/pkg/sql/sem/tree/window_funcs.go#L391)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I'm afraid you'll need to fix these ones too... We don't want an expected error to panic the server. Error plumbing is hard work! 
</blockquote></details>

Done. Thanks for patiently pointing out all of these places.

As far as I see, panics are only left in the tests or when a truly exceptional case happens (like a different mode of window framing etc.). I think these should remain as they are.

**Review by jordanlewis — APPROVED** [review]
:lgtm: likewise thanks for patiently fixing all of the cases!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34465#-:-LXz6yWB17pDMaVFrosd:b-21oiba)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

**Review by yuzefovich — COMMENTED** [review]
Thanks for the reviews!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34465#-:-LXz7d4f7g5g7XuNmyLl:bctxt4d)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

**Pull request merged**
