### PR TITLE
roachtest: grant tenant admin split capabilities in tpch

### LINKED ISSUE #96862: roachtest: tenant does not have admin split capability
roachtest.multitenant/tpch [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/8641928?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/8641928?buildTab=artifacts#/multitenant/tpch) on master @ [09188370d82e163ff1d44c62fe611104502c548d](https://github.com/cockroachdb/cockroach/commits/09188370d82e163ff1d44c62fe611104502c548d):

```
test artifacts and logs in: /artifacts/multitenant/tpch/run_1
(multitenant_tpch.go:54).func1: pq: importing 40 ranges: splitting key /Tenant/123/Table/110/1: ba: AdminSplit [/Tenant/123/Table/110/1,/Min) RPC error: grpc: tenant 123 does not have admin split capability [code 16/Unauthenticated]
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*multitenant/tpch.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-24376

### PR DESCRIPTION
**Pull request by rharding6373**
Grants the tenant the `can_admin_split` capability in the tpch roachtest.

Fixes: #96862
Epic: None

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
Thanks for fixing this! 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96902#-:-NNsF8V7DdDPXagpCcJ5:b-d05gmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs, @rharding6373, and @smg260)

___
*[`pkg/cmd/roachtest/tests/multitenant_tpch.go` line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96902#-NNsDxBCB4Mc_TM5EUkl:-NNsDxBCB4Mc_TM5EUkm:b9ixtkl) ([raw file](https://github.com/cockroachdb/cockroach/blob/969aeb5f8ac508f9931563d462201ab2d5888302/pkg/cmd/roachtest/tests/multitenant_tpch.go#L94)):*
> ```Go
> 	}
> 	testutils.SucceedsSoon(t, func() error {
> 		_, err := multiTenantConn.Exec(`ALTER TENANT [$1::INT] GRANT CAPABILITY can_admin_split=true`, tenantID)
> ```

We should use `singleTenantConn` (the system tenant) here to execute grant this capability. 

Separately, I don't think we need the GRANT inside of a `SucceedsSoon` -- instead, we want an `ALTER TABLE ... SPLIT AT` inside a `SucceedsSoon`. Capability state is eventually consistent, so doing so should prevent this test from flaking. 

We could either run a "scratch" `ALTER TABLE ... SPLIT AT`, or we could wrap the usage of `ALTER TABLE ... SPLIT AT` in the roachtest inside of a `SucceedsSoon`.

**Review by rharding6373 — COMMENTED** [review]
TFTR! The most recent revision passes the roachtest, so it's RFAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96902#-:-NNtn6l6AA2digcXxdj8:b-c375zj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @renatolabs, and @smg260)

___
*[`pkg/cmd/roachtest/tests/multitenant_tpch.go` line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96902#-NNsDxBCB4Mc_TM5EUkl:-NNtmNjq-iWP8_RGNWiL:b35khil) ([raw file](https://github.com/cockroachdb/cockroach/blob/969aeb5f8ac508f9931563d462201ab2d5888302/pkg/cmd/roachtest/tests/multitenant_tpch.go#L94)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

We should use `singleTenantConn` (the system tenant) here to execute grant this capability. 

Separately, I don't think we need the GRANT inside of a `SucceedsSoon` -- instead, we want an `ALTER TABLE ... SPLIT AT` inside a `SucceedsSoon`. Capability state is eventually consistent, so doing so should prevent this test from flaking. 

We could either run a "scratch" `ALTER TABLE ... SPLIT AT`, or we could wrap the usage of `ALTER TABLE ... SPLIT AT` in the roachtest inside of a `SucceedsSoon`. 
</blockquote></details>

Thanks for all the tips! I used your suggestion to do a fake split, since the splits in this test happen during import and I'm not sure we're able to wrap them.

**Review by arulajmani — APPROVED** [review]
:lgtm_strong: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96902#-:-NNvl7oY4iyCfYvhP6j5:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @renatolabs and @smg260)

**Comment by rharding6373** [comment]
TFTR!

bors r=arulajmani

**Pull request merged**
