### PR TITLE
server,sql: Refactor distSQLPlanner to only be initialized once

### PR DESCRIPTION
**Pull request by lgo**
This changes DistSQLPlanner to be exported. This will let us initialize a single DistSQLPlanner in pkg/server.

Note that a few methods on DistSQLPlanner were unexported as they don't escape pkg/sql. These exported methods are used outside of the file they're defined, but not out of the packaged.

This also refactors distSQLPlanner to only be initialized once. This moves distSQLPlanner initialization out from the SchemaChangeManager and Executor to instead use a shared instance initialized in Server.Start.

---
The first commit just renames things. @RaduBerinde thoughts on this? I'm not about our export/non-exported conventions as this does unexport a few functions that are called outside the definition file.

### CODE REVIEW

**Comment by tschottdorf** [comment]
I got alarmed by the word "singleton" in the message and scrolled through the diff, but it doesn't actually seem that you're making it a singleton (under which I understand a package-global variable). Unless that's actually what you're trying to do (I hope not), consider re-wording this appropriately.

**Comment by lego** [comment]
Welp didn't mean to set off alarms. Renamed things to "initializing a single instance"

**Comment by RaduBerinde** [comment]
:lgtm_strong:    Thanks!

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19534#-:-KxJbBNMYYW9xKSiYUtr:by1cciz)*

**Comment by vivekmenezes** [comment]
Thanks!

**Pull request merged**
