### PR TITLE
release-19.2: c-deps: bump rocksdb for intra-L0+ingest corruption fix

### PR DESCRIPTION
**Pull request by ajkr**
Backport 1/1 commits from #42008.

/cc @cockroachdb/release

---

Picks up https://github.com/cockroachdb/rocksdb/pull/70.

Release note (bug fix): Prevent rare corruption when files are ingested
that do not overlap with the in-memory buffer and compaction has fallen
behind.

### CODE REVIEW

**Comment by ajkr** [comment]
For 19.2 updating the branch also pulls in https://github.com/cockroachdb/rocksdb/pull/69. While it's not needed, I also prefer not to fork crl-release-6.2.1.

**Review by petermattis — APPROVED** [review]
LGTM

> For 19.2 updating the branch also pulls in cockroachdb/rocksdb#69. While it's not needed, I also prefer not to fork crl-release-6.2.1.

Agreed. That change looks innocuous enough.

**Comment by ajkr** [comment]
TFTR.

bors r+

**Comment by petermattis** [comment]
No need to bors on the release branch. Merge skew is unlikely. We do need CI to pass.

**Comment by ajkr** [comment]
I thought the merge button was greyed last time CI succeeded. Let's see.

**Comment by ajkr** [comment]
Well it timed out after running ~14K race tests, which seems much more than are run against other PRs (how is it determined?). I am rerunning but not sure what'll be different.

**Comment by ajkr** [comment]
I changed the setting for our release branches to not require bors status check to succeed before merging. Not sure if this config change has other implications, but it un-greys the merge button.

**Pull request merged**
