### PR TITLE
stats: improve UI experience

### LINKED ISSUE #35319: v19.1.0-beta.20190225: Unknown Event Types in the Web UI for automatic stats
**Describe the problem**

Automatic stats are creating `unknown event types` in the Web UI event log

image

**To Reproduce**

What did you do? Describe in your own words.
Ran the latest beta and sent some test load using https://github.com/cockroachdb/movr. Checked the WebUI and saw a bunch of unknown events.

**Expected behavior**
I'd expect these events to be labeled clearly

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change makes the following improvements:

 - the job name is now a user-friendly message (instead of the exact SQL
   statement) for automatic table stats. The message includes the
   fully-qualified tale name (the table name was not visible at all).

 - the event description in the UI is fixed (used to be an "unknown
   event error"); the message includes the FQ table name.

 - events are not posted by default (they are too spammy and redundant
   with the jobs); but they can be turned on via a cluster setting
   (could be useful during debugging).

Release note (admin ui change): CREATE STATISTICS jobs no longer
generate events by default; improved descriptions for automatic
statistics jobs.

Fixes #35319.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Sample event message (if enabled via cluster setting):
image

Jobs view (manual vs auto):
image

CC @awoods187

**Comment by RaduBerinde** [comment]
I will post a follow-up PR which populates the `Command` field in the expanded job view with the internal `CREATE STATISTICS` command.

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35425#-:-L_DyRJkENSTDqH0MDLm:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @rytaft)

**Review by rytaft — COMMENTED** [review]
Nice changes!

> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35425#-:-L_ssyZNDZii8T7S62mb:bibb57g)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/create_stats.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35425#-L_sphfE77cLYT_E4PY-:-L_sphfFDcmvK1CDnbjQ:bbsyb1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7edd205dbf9cc8c42f82a4fb4434a8d15949d3e/pkg/sql/create_stats.go#L40)):*
> ```Go
> 
> // createStatsPostEvents controls the cluster setting for enabling
> // automatic table statistics collection.
> ```

This description needs fixing

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/create_stats.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35425#-L_sphfE77cLYT_E4PY-:-L_tYIsZ1sl_hNPwAhYT:b-iui9zz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7edd205dbf9cc8c42f82a4fb4434a8d15949d3e/pkg/sql/create_stats.go#L40)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This description needs fixing
</blockquote></details>

Thanks, added a commit in my adaptive throttle PR:
```
+// createStatsPostEvents controls whether we post an event to the event log when
+// a CREATE STATISTICS job finishes.
```

**Comment by rytaft** [comment]
___
*[pkg/sql/create_stats.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35425#-L_sphfE77cLYT_E4PY-:-L_tZHC3C8ae4_MeGaYV:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7edd205dbf9cc8c42f82a4fb4434a8d15949d3e/pkg/sql/create_stats.go#L40)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Thanks, added a commit in my adaptive throttle PR:
```
+// createStatsPostEvents controls whether we post an event to the event log when
+// a CREATE STATISTICS job finishes.
```
</blockquote></details>

Thanks!

**Pull request merged**
