### PR TITLE
sql: made some planner methods into functions

### PR DESCRIPTION
**Pull request by vivekmenezes**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14394)

### CODE REVIEW

**Comment by vivekmenezes** [comment]
I'm add more stuff to this so hold off on reviewing unless you are opposed to this general direction. I think one of the big problems we have is that there are a number of methods that are primarily using  planner.txn and are thus methods of planner, we should make them pure functions and make the planner a real planner as opposed to being a container for txn.

**Comment by mjibson** [comment]
How are we going to remove the txn from a planner since plans need to be able to fetch table descriptors? Is your idea to have the txn be passed, when it is needed, as an additional argument (that is, instead of it being `p.txn`)?

**Comment by nvanbenschoten** [comment]
I love where this is going! We should avoid methods wherever possible. 

This will almost certainly need a rebase over #14188.

**Comment by vivekmenezes** [comment]
The high level idea here is to disassociate  a bunch of functionality from
the planner and session so that they can be used where the planner and
session are not created.

There is some functionality that depends only on a txn and a virtualtabler,
and some that also cares about the session database name. I'm planning to
move all that in this pr.

Still a work in progress.

**Comment by vivekmenezes** [comment]
After that a subsequent pr will move the table leases into their own type:
leaseCollection? Which will allow functionality to hold table leases
without a planner or a session.

**Comment by nvanbenschoten** [comment]
All of those changes sound like improvements to me. I'd expect that this would be a large step towards addressing #14414.

**Comment by vivekmenezes** [comment]
This is ready for review. It's a pretty straightforward change. I think once this is merged, I could move all these functions into sqlbase, or at least into a single file: descriptor.go?

**Comment by tamird** [comment]
The commit message should include motivation; currently the body just restates the subject, which isn't useful.

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/sql/descriptor.go, line 158 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394#-KgRsQ1BWd4yOMq02hFQ:-KgRsQ1BWd4yOMq02hFR:b-7jq5ms) ([raw file](https://github.com/cockroachdb/cockroach/blob/1239bc648dcda35b80585b2cdd240e85a2e17e9d/pkg/sql/descriptor.go#L158)):*
> ```Go
> 
> // getDescriptor looks up the descriptor for `plainKey`, validates it,
> // and unmarshals it into `descriptor`.
> ```

to preserve this line break, add a blank comment line:
```
// and unmarshals it ...
//
// If plainkey...
```

---

*[pkg/sql/descriptor.go, line 237 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394#-KgRsy1QxG6pdAJ9CErM:-KgRsy1RFo-tTuZeLyzR:b-on28sz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1239bc648dcda35b80585b2cdd240e85a2e17e9d/pkg/sql/descriptor.go#L237)):*
> ```Go
> }
> 
> // getDescriptorsFromTargetList examines a TargetList and fetches the
> ```

"fetches the descriptors for the targets."? unless "examines" is meaningful.

---

*[pkg/sql/table.go, line 128 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394#-KgRtLM8Jc63UNVlJAMy:-KgRtLM8Jc63UNVlJAMz:b-bvz58e) ([raw file](https://github.com/cockroachdb/cockroach/blob/1239bc648dcda35b80585b2cdd240e85a2e17e9d/pkg/sql/table.go#L128)):*
> ```Go
> // getTableDesc returns a table descriptor for a table, or nil if the
> // descriptor is not found. If you want the "not found" condition to
> // return an error, use mustGetTableDesc() instead.
> ```

to preserve this line break, add a blank comment line between the two paragraphs.

---

*[pkg/sql/table.go, line 145 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394#-KgRtNz_bcngUWN48yzu:-KgRtNz_bcngUWN48yzv:b-bvz58e) ([raw file](https://github.com/cockroachdb/cockroach/blob/1239bc648dcda35b80585b2cdd240e85a2e17e9d/pkg/sql/table.go#L145)):*
> ```Go
> 
> // getViewDesc returns a table descriptor for a table, or nil if the
> // descriptor is not found.
> ```

to preserve this line break, add a blank comment line between the two paragraphs.

---

*[pkg/sql/table.go, line 454 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394#-KgRtSTNX1M9_CEEl5G8:-KgRtSTNX1M9_CEEl5G9:b-7qvf97) ([raw file](https://github.com/cockroachdb/cockroach/blob/1239bc648dcda35b80585b2cdd240e85a2e17e9d/pkg/sql/table.go#L454)):*
> ```Go
> }
> 
> // expandTableGlob expands wildcards from the end of `expr` and
> ```

expr?

---

*[pkg/sql/table.go, line 503 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394#-KgRtZwcruZNP5G0SfBN:-KgRtZwcruZNP5G0SfBO:bbnpl9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1239bc648dcda35b80585b2cdd240e85a2e17e9d/pkg/sql/table.go#L503)):*
> ```Go
> 		// has its timestamps set correctly so getTableOrViewDesc will fetch with
> 		// the correct timestamp.
> 		descFunc = func(ctx context.Context, tn *parser.TableName) (*sqlbase.TableDescriptor, error) {
> ```

can you use this style in data_source.go as well, for consistency?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394#-:-KgRrUIsRK0zlzSV2-qS:b-un09wx)*

**Comment by nvanbenschoten** [comment]
Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/sql/data_source.go, line 495 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394#-KgTQHg-dVbtY-f5lRET:-KgTQHg0lNQHcdQJhI73:bpyuxw3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1239bc648dcda35b80585b2cdd240e85a2e17e9d/pkg/sql/data_source.go#L495)):*
> ```Go
> 		desc, err = mustGetTableOrViewDesc(ctx, p.txn, p.getVirtualTabler(), tn)
> 	} else {
> 		desc, err = p.getTableLease(ctx, tn)
> ```

Is this method on the chopping block next?

---

*[pkg/sql/table.go, line 503 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394#-KgRtZwcruZNP5G0SfBN:-KgTRsERKluQklS-pXt5:bf5vv2f) ([raw file](https://github.com/cockroachdb/cockroach/blob/1239bc648dcda35b80585b2cdd240e85a2e17e9d/pkg/sql/table.go#L503)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can you use this style in data_source.go as well, for consistency?
</blockquote></details>

+1, lets keep them consistent, one way or the other

---

*[pkg/sql/virtual_schema.go, line 249 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394#-KgTS1XX215kVdn2QYJ6:-KgTS1XX215kVdn2QYJ7:b-2vo0rv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1239bc648dcda35b80585b2cdd240e85a2e17e9d/pkg/sql/virtual_schema.go#L249)):*
> ```Go
> 	getVirtualTableDesc(tn *parser.TableName) (*sqlbase.TableDescriptor, error)
> 	getVirtualDatabaseDesc(name string) *sqlbase.DatabaseDescriptor
> 	getVirtualSchemaEntry(name string) (virtualSchemaEntry, bool)
> ```

I feel like this is kind of an abuse of the interface, which is meant only to provide access to VirtualSchema descriptors. Why not just pass around `*virtualSchemaHolder`?

@mjibson, what was to reasoning behind this approach over just having `virtualSchemaHolder` handle nil receivers? Did you just not want `virtualSchemaHolder` to be exported?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394)*

**Comment by vivekmenezes** [comment]
Added another comment to the commit message.

---

Review status: 12 of 15 files reviewed at latest revision, 9 unresolved discussions, some commit checks pending.

---

*[a discussion](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394#-KgUX_bXaXftzwyeZ0Lt:-KgUX_bYxzNyyKvOCE7F:bb71pro) (no related file):*
PTAL

---

*[pkg/sql/data_source.go, line 495 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394#-KgTQHg-dVbtY-f5lRET:-KgUO0poDSRTpYvCH16s:b-4fbwdt) ([raw file](https://github.com/cockroachdb/cockroach/blob/1239bc648dcda35b80585b2cdd240e85a2e17e9d/pkg/sql/data_source.go#L495)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this method on the chopping block next?
</blockquote></details>

Yes once this is in, we create another layer that depends on the base functionality provided in this PR and a data structure that holds a list of leases. 

---

*[pkg/sql/descriptor.go, line 158 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394#-KgRsQ1BWd4yOMq02hFQ:-KgUOVpuvuLxcQIuUThm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1239bc648dcda35b80585b2cdd240e85a2e17e9d/pkg/sql/descriptor.go#L158)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

to preserve this line break, add a blank comment line:
```
// and unmarshals it ...
//
// If plainkey...
```
</blockquote></details>

Done.

---

*[pkg/sql/descriptor.go, line 237 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394#-KgRsy1QxG6pdAJ9CErM:-KgULEwbcKlGLAYea855:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1239bc648dcda35b80585b2cdd240e85a2e17e9d/pkg/sql/descriptor.go#L237)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

"fetches the descriptors for the targets."? unless "examines" is meaningful.
</blockquote></details>

Done.

---

*[pkg/sql/table.go, line 128 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394#-KgRtLM8Jc63UNVlJAMy:-KgULXO9SEMST_YbNxbu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1239bc648dcda35b80585b2cdd240e85a2e17e9d/pkg/sql/table.go#L128)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

to preserve this line break, add a blank comment line between the two paragraphs.
</blockquote></details>

Done.

---

*[pkg/sql/table.go, line 145 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394#-KgRtNz_bcngUWN48yzu:-KgULZ15fOvtK0kMP7x5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1239bc648dcda35b80585b2cdd240e85a2e17e9d/pkg/sql/table.go#L145)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

to preserve this line break, add a blank comment line between the two paragraphs.
</blockquote></details>

Done.

---

*[pkg/sql/table.go, line 454 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394#-KgRtSTNX1M9_CEEl5G8:-KgUN-hngkkRQt_O-si5:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/1239bc648dcda35b80585b2cdd240e85a2e17e9d/pkg/sql/table.go#L454)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

expr?
</blockquote></details>

fixed

---

*[pkg/sql/table.go, line 503 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394#-KgRtZwcruZNP5G0SfBN:-KgUNrYdNoiymgfsOelp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1239bc648dcda35b80585b2cdd240e85a2e17e9d/pkg/sql/table.go#L503)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

+1, lets keep them consistent, one way or the other
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394#-:-KgUXJSeOhGgF6WdEdpx:b6trv4v)*

**Comment by tamird** [comment]
Reviewed 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/sql/descriptor.go, line 237 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394#-KgRsy1QxG6pdAJ9CErM:-KgUqcshrT4oNuuGRf9U:b-pfj523) ([raw file](https://github.com/cockroachdb/cockroach/blob/1239bc648dcda35b80585b2cdd240e85a2e17e9d/pkg/sql/descriptor.go#L237)):*
> examines a TargetList and
Remove this bit.

---

*[pkg/sql/table.go, line 457 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394#-KgUqRQzlm6GDjThx_If:-KgUqRQzlm6GDjThx_Ig:b-23sg7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c893f099236a4ca8e89454864c715f0d0083069/pkg/sql/table.go#L457)):*
> ```Go
> }
> 
> // expandTableGlob expands a parser.TablePattern into a list of tables
> ```

s/a parser.TablePattern/pattern/ (the name of the argument)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394)*

**Comment by tamird** [comment]
Reviewed 1 of 4 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394)*

**Comment by vivekmenezes** [comment]
Review status: 13 of 15 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/sql/descriptor.go, line 237 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394#-KgRsy1QxG6pdAJ9CErM:-KgV56OBKFaP1aS8VRDw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1239bc648dcda35b80585b2cdd240e85a2e17e9d/pkg/sql/descriptor.go#L237)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

> examines a TargetList and
Remove this bit.
</blockquote></details>

Done.

---

*[pkg/sql/table.go, line 457 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394#-KgUqRQzlm6GDjThx_If:-KgV5P48Q198NMWc6-Ta:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c893f099236a4ca8e89454864c715f0d0083069/pkg/sql/table.go#L457)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

s/a parser.TablePattern/pattern/ (the name of the argument)
</blockquote></details>

Done.

---

*[pkg/sql/virtual_schema.go, line 249 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394#-KgTS1XX215kVdn2QYJ6:-KgV5f2XP6fDEjz8_fWy:b-wszrky) ([raw file](https://github.com/cockroachdb/cockroach/blob/1239bc648dcda35b80585b2cdd240e85a2e17e9d/pkg/sql/virtual_schema.go#L249)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I feel like this is kind of an abuse of the interface, which is meant only to provide access to VirtualSchema descriptors. Why not just pass around `*virtualSchemaHolder`?

@mjibson, what was to reasoning behind this approach over just having `virtualSchemaHolder` handle nil receivers? Did you just not want `virtualSchemaHolder` to be exported?
</blockquote></details>

Any thoughts here? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394)*

**Comment by nvanbenschoten** [comment]
:lgtm: other than the question for @mjibson about `VirtualTabler`.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394#-:-KgVWvaChv4FT4oPCa_H:bm5trte)*

**Comment by mjibson** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/virtual_schema.go, line 249 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394#-KgTS1XX215kVdn2QYJ6:-KgVaJ-F9QTi6dYDu-Rx:bsnrt99) ([raw file](https://github.com/cockroachdb/cockroach/blob/1239bc648dcda35b80585b2cdd240e85a2e17e9d/pkg/sql/virtual_schema.go#L249)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Any thoughts here? 
</blockquote></details>

I think it was done this way because the enterprise repo was being developed under a private repo and so it was hard to do cross repo stuff, or maybe I made a bad initial choice. But since that problem is gone now please do whatever makes the most sense. It is possible the old way is bad and should change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394)*

**Comment by vivekmenezes** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/virtual_schema.go, line 249 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394#-KgTS1XX215kVdn2QYJ6:-KgVehl4cJt2pf1DWiBA:bxzvpyu) ([raw file](https://github.com/cockroachdb/cockroach/blob/1239bc648dcda35b80585b2cdd240e85a2e17e9d/pkg/sql/virtual_schema.go#L249)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I think it was done this way because the enterprise repo was being developed under a private repo and so it was hard to do cross repo stuff, or maybe I made a bad initial choice. But since that problem is gone now please do whatever makes the most sense. It is possible the old way is bad and should change.
</blockquote></details>

I'm going to leave it as is and postpone any further improvements for later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/virtual_schema.go, line 249 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394#-KgTS1XX215kVdn2QYJ6:-KgVxgQQUKiduuhYx4dv:b-lc3iva) ([raw file](https://github.com/cockroachdb/cockroach/blob/1239bc648dcda35b80585b2cdd240e85a2e17e9d/pkg/sql/virtual_schema.go#L249)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I'm going to leave it as is and postpone any further improvements for later.
</blockquote></details>

SGTM. Thanks for the explanation Matt.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14394)*

**Pull request merged**
