### PR TITLE
Merge release 23.2 v23.2.0 rc.2

### PR DESCRIPTION
**Pull request by andrewbaptist**
Merge the v23.2.0-rc.2 tag back into v23.2

Epic: none.
Release justification: noop

### CODE REVIEW

**Comment by andrewbaptist** [comment]
It looks like this wasn't done for rc.0 or rc.1, so please verify I followed the correct process on this. Thanks!

**Comment by rail** [comment]
Do we actually merge these branches until we are done with the branch? We are going to use this branch for potential RCs and the release builds AFAIK. This operation is harmless, so probably it makes sense to merge everything back to 23.2 in advance and reduce the future merge sizes. Also, by merging now we may catch potential issues on the 23.2 branch, who knows. In other words, I'm fine with this merge, just wanted to make sure we don't break anything in the process. @celiala WDYT?

**Comment by andrewbaptist** [comment]
Agreed it wasn't clear if we should. I was following this:
https://cockroachlabs.atlassian.net/wiki/spaces/RE/pages/2975072322/Phase+3+Publish+23.1#6.-Merge-staging-branch-into-the-main-release-branch-(if-applicable)

And it isn't completely clear if it was applicable in this case (but it
definitely seemed like it was based on the text).

I added a few comments to that page as I went along to help clear up any
confusion so once a decision has been made on this, we should clean this up
as well.

Andrew

**Review by rail — APPROVED** [review]

**Review by celiala — APPROVED** [review]
LGTM!

> On advantage of this merge is that as long as the "files changed" stays at 0 it helps make sure we don't miss any PRs (only merge to the .0 but didn't get merged back to the release-23.2 branch. I don't think there is any harm in merging early periodically (every beta/rc).

Good point (agree)

**Comment by andrewbaptist** [comment]
bors r=rail,celiala 

TFTR!

**Comment by rickystewart** [comment]
@andrewbaptist FYI: Please do not use `bors` for release branches. It applies for `master` only.

**Comment by andrewbaptist** [comment]
Sorry - I had accidentally bors it and then manually merged once I realized my mistake. Was there still something running after I had merged it last week?

**Pull request merged**
