### PR TITLE
roachtest: Test debug zip command works correctly.

### PR DESCRIPTION
**Pull request by ghost**
In this test, we specifically check the `cockroach debug zip` command produces
the expected information from `gossip_nodes` and `gossip_liveness`. It also
checks the command times out even if some nodes in the cluster is intentionally
killed.

Issue: #24473.

Release note: None

### CODE REVIEW

**Comment by windchan7** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/cmd/roachtest/debug.go, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/24946#-LAxrnY82wbZD0-MY-DW:-LB1GV3U1O_gJN-gD1kL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/07b8a1438aa766acc095480ef398a15a11a963d5/pkg/cmd/roachtest/debug.go#L30)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Nit: follow the https://github.com/cockroachdb/cockroach/blob/master/docs/style.md and capitalize. (Comment applies throughout this file).
</blockquote></details>

Done.

---

*[pkg/cmd/roachtest/debug.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/24946#-LAxs-f_6jlPsW584Wj9:-LB1GWLzE-BOtaV75nyx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/07b8a1438aa766acc095480ef398a15a11a963d5/pkg/cmd/roachtest/debug.go#L31)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

In this test you are better off just running `c.Stop` without this helper. You don't need clean shutdown.
</blockquote></details>

Done.

---

*[pkg/cmd/roachtest/debug.go, line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/24946#-LAxsDKW5odcVMtbf1il:-LB1GWvX79WZ5r-vr9-9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/07b8a1438aa766acc095480ef398a15a11a963d5/pkg/cmd/roachtest/debug.go#L53)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

For both, can you grep against the contents? Just do `grep 'something-that-matches-if-it's-not-broken' ./debug/gossip/liveness` instead.
</blockquote></details>

Done.

---

*[pkg/cmd/roachtest/debug.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/24946#-LAxsUnvEQfWf_gj3H-K:-LB1GXRF8S1ln9kHCb9-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/07b8a1438aa766acc095480ef398a15a11a963d5/pkg/cmd/roachtest/debug.go#L61)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

`; time.Sleep(time.Second)`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24946)*

**Comment by tschottdorf** [comment]
:lgtm:, thanks! But looks like there's a merge conflict.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24946#-:-LB235Rr5cywCMrx2VE5:bod92qc)*

**Comment by windchan7** [comment]
@tschottdorf , conflict resolved! Thanks.

**Pull request merged**
