### PR TITLE
sql: CREATE STATISTICS statement and distsql planning for stats

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### distsql: planning for statistics

image

#### update hyperloglog dependency

Updating to include a fix for spurious race detector errors.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
CC @knz for the first commit

**Comment by RaduBerinde** [comment]
Added a commit that switches `statisticID` to use `unique_rowid()`.

**Comment by rytaft** [comment]
Looking good!  Maybe also add `sql/logictest/testdata/logic_test/create_stats` to test the expected output?

---

Reviewed 11 of 12 files at r1, 7 of 7 files at r2, 2 of 2 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/create_stats.go, line 37 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20326#-L-8-OIgLB-WEI_Fb2On:-L-8-OIgLB-WEI_Fb2Oo:bap0r91) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb37d31bf306d77bc3e2cce012f9240328ab899f/pkg/sql/create_stats.go#L37)):*
> ```Go
> 	}
> 
> 	// Is this perhaps a name for a virtual table?
> ```

nit - this comment is a bit confusing - it sounds like you are actually asking a question.  Maybe change to something like:
```
// Check if tn matches the name of an existing virtual table.
```

---

*[pkg/sql/distsql_plan_stats.go, line 87 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20326#-L-85hRA7cSsSoh3O0P2:-L-85hRA7cSsSoh3O0P3:btbxw4x) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb37d31bf306d77bc3e2cce012f9240328ab899f/pkg/sql/distsql_plan_stats.go#L87)):*
> ```Go
> 						colIdx = i
> 					}
> 				}
> ```

What if `colIdx` is not present in `post.OutputColumns`?  Maybe  add a check here that the column was found?

---

*[pkg/sql/distsql_plan_stats.go, line 113 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20326#-L-875wjE_VlrcWe5Prr:-L-875wjE_VlrcWe5Prs:b-rysnof) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb37d31bf306d77bc3e2cce012f9240328ab899f/pkg/sql/distsql_plan_stats.go#L113)):*
> ```Go
> 	// An INT column indicating the number of rows processed.
> 	outTypes = append(outTypes, sqlbase.ColumnType{SemanticType: sqlbase.ColumnType_INT})
> 	// An INT column indicating the number of NULL values on the first column
> ```

I thought this was supposed to be the number of NULL values on any column (that's what it says in the [RFC](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20170908_sql_optimizer_statistics.md#systemtable_statistics))?

---

*[pkg/sql/sem/tree/create.go, line 992 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20326#-L-8CFsk-UX_iznM2hPq:-L-8CFsk-UX_iznM2hPr:b-3whpy) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb37d31bf306d77bc3e2cce012f9240328ab899f/pkg/sql/sem/tree/create.go#L992)):*
> ```Go
> // CreateStats represents a CREATE STATISTICS statement.
> type CreateStats struct {
> 	Name        Name
> ```

Is the name getting inserted correctly into `system.table_statistics`?

I suppose we'll need to add several tests of the full lifecycle anyway, (from `CREATE STATISTICS` to querying the stats cache), but it seems likely that the Name might be getting dropped somewhere...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20326#-:-L-8E0qdn_CBIGOY3nVd:b-7kpmq3)*

**Comment by lego** [comment]
First commit LGTM :). Just left a few nit comments.

---

Reviewed 12 of 12 files at r1, 2 of 7 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/sql/create_stats.go, line 37 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20326#-L-8JSlpIN-qk2fBlN1E:-L-8JSlpIN-qk2fBlN1F:b-tlnuup) ([raw file](https://github.com/cockroachdb/cockroach/blob/04874f33cd067311087c60efbad2890511bf3fbe/pkg/sql/create_stats.go#L37)):*
> ```Go
> 
> 	// Is this perhaps a name for a virtual table?
> 	if _, foundVirtual, err := p.getVirtualDataSource(ctx, tn); err != nil {
> ```

You could also call `tableDesc.IsVirtualTable()` or even `tableDesc.IsPhysicalTable` (although `MustGetTableDesc` already ensures the table is not a view). It might be more self-descriptive of what you're checking and better since that's all you care about, instead of fetching the virtual data source.

---

*[pkg/sql/create_stats.go, line 56 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20326#-L-8MPzrxyXFqoUx_jdm:-L-8MPzrxyXFqoUx_jdn:b-j7pd6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c4fd2527ddd59ef196028e538c5450051cbb15d/pkg/sql/create_stats.go#L56)):*
> ```Go
> 		return nil, errors.Errorf("no columns given for statistics")
> 	}
> 	columns := make([]sqlbase.ColumnID, len(n.ColumnNames))
> ```

You can simplify this with:

```go
columns, err := tableDesc.FindActiveColumnsByNames(n.ColumnNames)
if err != nil {
  return err
}
columnIDs := make([]sqlbase.ColumnID, len(columns)
for i := range columns {
  columnIDs[i] = columns[i].ID
}
```

(sidenote: is it preferable to store ColumnIDs, ColumnDescriptor pointers, or the ColumnDescriptor structs? I have no idea which is most appropriate.)

---

*[pkg/sql/logictest/testdata/logic_test/distsql_stats, line 47 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20326#-L-8O3buHTZtxnhE10qg:-L-8O3buHTZtxnhE10qh:byjq8dh) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c4fd2527ddd59ef196028e538c5450051cbb15d/pkg/sql/logictest/testdata/logic_test/distsql_stats#L47)):*
> ```
> 
> statement ok
> CREATE STATISTICS s1 ON a FROM data
> ```

For good measure, can you pop in`CREATE STATISTICS s1 ON a FROM test.data`.

---

*[pkg/sql/parser/parse_test.go, line 244 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20326#-L-8KPV5nKlwgiWADY32:-L-8KPV5nKlwgiWADY33:bntkami) ([raw file](https://github.com/cockroachdb/cockroach/blob/04874f33cd067311087c60efbad2890511bf3fbe/pkg/sql/parser/parse_test.go#L244)):*
> ```Go
> 		{`CREATE SEQUENCE a INCREMENT 5 NO MAXVALUE MINVALUE 1 START 3 NO CYCLE`},
> 
> 		{`CREATE STATISTICS a ON col1 FROM t`},
> ```

Maybe also add `CREATE STATISTICS a ON col1 FROM a.t`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20326#-:-L-8OHXeT7VVTx2HcgS4:b-7egr3m)*

**Comment by RaduBerinde** [comment]
TFTRs!

---

Review status: 10 of 24 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/sql/create_stats.go, line 37 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20326#-L-8JSlpIN-qk2fBlN1E:-L-8TshDKBM3AyAfFANs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04874f33cd067311087c60efbad2890511bf3fbe/pkg/sql/create_stats.go#L37)):*
<details><summary><i>Previously, lego (Joey Pereira) wrote…</i></summary><blockquote>

You could also call `tableDesc.IsVirtualTable()` or even `tableDesc.IsPhysicalTable` (although `MustGetTableDesc` already ensures the table is not a view). It might be more self-descriptive of what you're checking and better since that's all you care about, instead of fetching the virtual data source.
</blockquote></details>

Done.

---

*[pkg/sql/create_stats.go, line 56 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20326#-L-8MPzrxyXFqoUx_jdm:-L-8UIudV_MYevPLurU_:bjs8fxi) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c4fd2527ddd59ef196028e538c5450051cbb15d/pkg/sql/create_stats.go#L56)):*
<details><summary><i>Previously, lego (Joey Pereira) wrote…</i></summary><blockquote>

You can simplify this with:

```go
columns, err := tableDesc.FindActiveColumnsByNames(n.ColumnNames)
if err != nil {
  return err
}
columnIDs := make([]sqlbase.ColumnID, len(columns)
for i := range columns {
  columnIDs[i] = columns[i].ID
}
```

(sidenote: is it preferable to store ColumnIDs, ColumnDescriptor pointers, or the ColumnDescriptor structs? I have no idea which is most appropriate.)
</blockquote></details>

Done, thanks. Here we only need the IDs. Otherwise I'd store the structs, it seems pretty small.

---

*[pkg/sql/create_stats.go, line 37 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20326#-L-8-OIgLB-WEI_Fb2On:-L-8TQbmlKJRF-cCJiPs:bz4ar5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb37d31bf306d77bc3e2cce012f9240328ab899f/pkg/sql/create_stats.go#L37)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

nit - this comment is a bit confusing - it sounds like you are actually asking a question.  Maybe change to something like:
```
// Check if tn matches the name of an existing virtual table.
```
</blockquote></details>

I removed this code, but it was a copy paste so I fixed the original.

---

*[pkg/sql/distsql_plan_stats.go, line 87 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20326#-L-85hRA7cSsSoh3O0P2:-L-8Udt8aZZKkC_pkddz:bc7t6so) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb37d31bf306d77bc3e2cce012f9240328ab899f/pkg/sql/distsql_plan_stats.go#L87)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

What if `colIdx` is not present in `post.OutputColumns`?  Maybe  add a check here that the column was found?
</blockquote></details>

We would have failed above where we check the same. Added a panic.

---

*[pkg/sql/distsql_plan_stats.go, line 113 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20326#-L-875wjE_VlrcWe5Prr:-L-8VgD7qaDw1J0Z9R5w:b-o6vvrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb37d31bf306d77bc3e2cce012f9240328ab899f/pkg/sql/distsql_plan_stats.go#L113)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I thought this was supposed to be the number of NULL values on any column (that's what it says in the [RFC](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20170908_sql_optimizer_statistics.md#systemtable_statistics))?
</blockquote></details>

Good catch! Fixed

---

*[pkg/sql/logictest/testdata/logic_test/distsql_stats, line 47 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20326#-L-8O3buHTZtxnhE10qg:-L-8YEG2q060y-QwSerg:b-1jn1ck) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c4fd2527ddd59ef196028e538c5450051cbb15d/pkg/sql/logictest/testdata/logic_test/distsql_stats#L47)):*
<details><summary><i>Previously, lego (Joey Pereira) wrote…</i></summary><blockquote>

For good measure, can you pop in`CREATE STATISTICS s1 ON a FROM test.data`.
</blockquote></details>

I tested it manually, I don't think it's necessary to add it here (we will generate two statistics if we call it twice).

---

*[pkg/sql/parser/parse_test.go, line 244 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20326#-L-8KPV5nKlwgiWADY32:-L-8XrOpmJvyQTPco7hD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04874f33cd067311087c60efbad2890511bf3fbe/pkg/sql/parser/parse_test.go#L244)):*
<details><summary><i>Previously, lego (Joey Pereira) wrote…</i></summary><blockquote>

Maybe also add `CREATE STATISTICS a ON col1 FROM a.t`.
</blockquote></details>

Done.

---

*[pkg/sql/sem/tree/create.go, line 992 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20326#-L-8CFsk-UX_iznM2hPq:-L-8XtDcCptdJXrVCIvk:bjf36sa) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb37d31bf306d77bc3e2cce012f9240328ab899f/pkg/sql/sem/tree/create.go#L992)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Is the name getting inserted correctly into `system.table_statistics`?

I suppose we'll need to add several tests of the full lifecycle anyway, (from `CREATE STATISTICS` to querying the stats cache), but it seems likely that the Name might be getting dropped somewhere...
</blockquote></details>

Yeah, we're not, we need to add it to the processor spec, I was planning of doing that in a follow-up change.

We'll be adding tests that verify the outputs, we just need some convenience SHOW STATISTICS statement (I don't want to hardcode the tableID in the test)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20326#-:-L-8_uQQlxYapVky2CVk:bz5mair)*

**Comment by rytaft** [comment]
Changes look good.  So I guess `sql/logictest/testdata/logic_test/create_stats` should be added in a later PR when we're ready to test the output?

---

Reviewed 1 of 12 files at r5, 9 of 9 files at r6, 2 of 2 files at r7, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsql_plan_stats.go, line 87 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20326#-L-85hRA7cSsSoh3O0P2:-L-8bdttwfbU5m8pB9Bm:b-yri5jz) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb37d31bf306d77bc3e2cce012f9240328ab899f/pkg/sql/distsql_plan_stats.go#L87)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We would have failed above where we check the same. Added a panic.
</blockquote></details>

But isn't `post.OuputColumns` a smaller set than `scan.colIdxMap` if there is a projection?  So shouldn't there be an error if `post.Projection` is true, but `colIdx` was not found in `post.OutputColumns`?

---

*[pkg/sql/sem/tree/create.go, line 992 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20326#-L-8CFsk-UX_iznM2hPq:-L-8d73iWI2kU4ii0MHG:brxp9sq) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb37d31bf306d77bc3e2cce012f9240328ab899f/pkg/sql/sem/tree/create.go#L992)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yeah, we're not, we need to add it to the processor spec, I was planning of doing that in a follow-up change.

We'll be adding tests that verify the outputs, we just need some convenience SHOW STATISTICS statement (I don't want to hardcode the tableID in the test)
</blockquote></details>

Sounds good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20326#-:-L-8djhmTDhfzFrU7cr_:b1yug6a)*

**Comment by RaduBerinde** [comment]
Why do we need a file separate from `distsql_stats`? I was planning to add tests there (there's a TODO)

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql_plan_stats.go, line 87 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20326#-L-85hRA7cSsSoh3O0P2:-L-8iFDOrbSBRceff3se:b6secgl) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb37d31bf306d77bc3e2cce012f9240328ab899f/pkg/sql/distsql_plan_stats.go#L87)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

But isn't `post.OuputColumns` a smaller set than `scan.colIdxMap` if there is a projection?  So shouldn't there be an error if `post.Projection` is true, but `colIdx` was not found in `post.OutputColumns`?
</blockquote></details>

Ah, sorry, I looked at the wrong thing. The OutputColumns should be those that are in `scan.valNeededForCol`, which is the same set of columns we are looping over. Added a flag and a panic.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20326#-:-L-8i5CNfhzzfnKBgt4C:b-1rm8v)*

**Comment by rytaft** [comment]
Ah sorry you're right - `distsql_stats` is perfect.

:lgtm:

---

Reviewed 1 of 5 files at r9, 2 of 2 files at r10, 3 of 3 files at r11.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20326#-:-L-8xk_Gnk5ZFH0mYbFO:bq59k7q)*

**Pull request merged**
