### PR TITLE
clusterversion,*: remove pre-22.1 cluster versions

### LINKED ISSUE #80663: clusterversion: bump min-supported version to 22.1
**Describe the problem**

This issue tracks the work necessary to [bump the min supported binary version](https://github.com/cockroachdb/cockroach/blob/6cdd96b38f5b67c655a5697b6bf493b2c59041c1/pkg/clusterversion/cockroach_versions.go#L610-L615) on master:
* ~This needs to be done before we cut any release for 22.2~
* Update: This task blocks us from releasing beta/RC releases for 22.2 (With https://github.com/cockroachdb/cockroach/pull/86345 we were able to unblock the releasing of alpha candidates)

TODOs:

- [x] remove old 22.1 cluster version gates
- [ ] bump the min supported binary version https://github.com/cockroachdb/cockroach/pull/86642

Jira issue: CRDB-18426
Jira issue: CRDB-15560

### PR DESCRIPTION
**Pull request by celiala**
This PR removes any remaining pre-22.1 gates and bumps the minimum-supported version on master, which is required in order for us to cut any release for 22.2

The cleanup for these version gates was fairly straight-forward, using the guidance from https://github.com/cockroachdb/cockroach/pull/74270#issuecomment-1000693734:

> For the most part, if the gates were just simple if !version.IsActive { return x } or something, I just removed the block, and even if it was a little more complicated, like args = [x]; if version { args = append(args, y) }; foo(args) I still tried to mostly inline it such that it looked natural (i.e. remove that append and make it args = [x, y]).

Code removed / adjusted, by team-specific areas:

* `TestRestoreOldVersions`: removed `BinaryVersionOverride` reference to old version (cc @RichardJCai / @cockroachdb/bulk-io )
* Removed `TestVirtualColumnNotAllowedInPkeyBefore22_1` (cc @cockroachdb/sql-schema )
* Adjusted `TestSetMinVersion` to account for deprecated version gates (cc @cockroachdb/storage )

Fixes https://github.com/cockroachdb/cockroach/issues/80663
Release note: None
Release justification: bump minSupportedVersion

### CODE REVIEW

**Comment by celiala** [comment]
`TestRestoreOldVersions` seems to be consistently failing (although not seeing more detailed output):
* https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/6206578?showRootCauses=true&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildDeploymentsSection=true&expandBuildTestsSection=true

**Comment by celiala** [comment]
`TestChangefeedErrors` (`github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl`) is failing at:
```
    changefeed_test.go:3791: expected error 'unknown format: nope', got: pq: feature CHANGEFEED was disabled by the database administrator
```

**Comment by cucaroach** [comment]
> I'm not sure how to fix - maybe @RaduBerinde or @cucaroach can help here?

Beats me, I suspect someone from CDC will know?   Looks like the enabling feature of the didn't take for some reason.

**Comment by knz** [comment]
cc @stevendanna could you provide input on the above?

**Comment by ajwerner** [comment]
> TestRestoreOldVersions

This is a rather important test for BulkIO. I think we need somebody from their team to sign off (@stevendanna being a good choice).

**Comment by ajwerner** [comment]
For the changefeed tests, maybe @miretskiy can help?

**Comment by celiala** [comment]
Re `TestRestoreOldVersions`:

8/30 Update: I've updated the PR to leave the `TestRestoreOldVersions` test as-is, but I could definitely I could use help from someone on how to fix (maybe @stevendanna / BulkIO ) ?

The CI output is a bit vague (Lots of "No pass/skip/fail event found for test"):
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/6296779?buildTab=tests&status=failed

**Comment by celiala** [comment]
Hi all - this is now RFAL - thanks!

All tests now pass for Bazel Essential CI. Here is code that was removed/tweaked, by team-specific areas:

* `TestRestoreOldVersions`: removed `BinaryVersionOverride` reference to old version (cc @RichardJCai / @cockroachdb/bulk-io )
* Removed `TestVirtualColumnNotAllowedInPkeyBefore22_1` (cc @cockroachdb/sql-schema )
* Adjusted `TestSetMinVersion` to account for deprecated version gates (cc @cockroachdb/storage )

Thanks!

**Comment by postamar** [comment]
Schema-related changes LGTM

**Review by ajwerner — APPROVED** [review]
Schema changes :lgtm:, @postamar won the race 

> Reviewed 1 of 11 files at r1, 1 of 5 files at r2, 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86642#-:-NAtzTsEDTFJUgOz5Y5z:b-sttcf8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @cucaroach, and @irfansharif)

**Review by benbardin — APPROVED** [review]
approved for bakcupccl

**Review by jbowens — APPROVED** [review]
storage related changes :lgtm: 

> Reviewed 2 of 11 files at r1, 3 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86642#-:-NAu9WzM4ABq1Ini7YDe:b174sqg)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @adityamaru, @cucaroach, @irfansharif, and @jlinder)

**Review by jlinder — APPROVED** [review]

**Comment by celiala** [comment]
TFTRs!

bors r=jlinder,benbardin,jbowens,ajwerner

**Pull request merged**
