### PR TITLE
backupccl: skip collecting/verifying full-file SHA512 checksums

### PR DESCRIPTION
**Pull request by dt**
BACKUP uses SSTables to store its data. SSTables maintain block-level checksums internally, which
allow verifying the integrity of data _as it is read_. BACKUP previously also checksummed the
entire file, using SHA512. However these full-file checksums, by nature, require reading the whole
file to verify them. RESTORE would prefer to be able to open and read only the subsets of the
files it actually needs, or to only read and process files incrementally.

This change adds a setting which defaults to not collecting full-file checksums and a setting
which also defaults to false for not verifying full-file checksums if they are present.

Release note (sql change): BACKUP and RESTORE default to using block-level checksums embedded in its data files instead of collecting / verifying more expensive file-level SHA512 checksums. Collecting/verifying the full-file file checksums can be re-enabled with 'backup.collect_full_file_checksums.enabled' and 'backup.verify_full_file_checksums.enabled'.

### CODE REVIEW

**Review by miretskiy — APPROVED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58404)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @pbardea)

___
*[pkg/ccl/backupccl/restore_job.go, line 548 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58404#-MQ9YUe8DLD9udyFh5WU:-MQ9YUe8DLD9udyFh5WV:b-ztxym) ([raw file](https://github.com/cockroachdb/cockroach/blob/1896e1ad54566820a96a0afbcf72f2b02752e100/pkg/ccl/backupccl/restore_job.go#L548)):*
> ```Go
> 				importSpans[i].Files[j].Sha512 = nil
> 			}
> 		}
> ```

we should probably log an error if verifyCHecksums, but the file does not have them...

**Review by pbardea — APPROVED** [review]
Not for this PR, but we might also want to augment SHOW BACKUP with an option to inspect if a backup included checksums? Or perhaps it would be useful to promote `SHOW BACKUP FILES` into something that we advertise in our docs?

**Review by dt — COMMENTED** [review]
We could extend `show`, though I'm sort of thinking we should just aim for full-file checksums to go away entirely instead? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58404#-:-MQF7ef51SQZOr2sVEuz:b-z5j16l)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[pkg/ccl/backupccl/restore_job.go, line 548 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58404#-MQ9YUe8DLD9udyFh5WU:-MQ9YoPK9rJEGx4byQhu:b-yq7gic) ([raw file](https://github.com/cockroachdb/cockroach/blob/1896e1ad54566820a96a0afbcf72f2b02752e100/pkg/ccl/backupccl/restore_job.go#L548)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

we should probably log an error if verifyCHecksums, but the file does not have them...
</blockquote></details>

FWIW, it's a silent case today -- we currently verify full-file checksums if they are there, but we don't say anything if they're not.

**Review by miretskiy — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58404)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

___
*[pkg/ccl/backupccl/restore_job.go, line 548 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58404#-MQ9YUe8DLD9udyFh5WU:-MQFDwy72tZHnBRi4N-S:b-yeb205) ([raw file](https://github.com/cockroachdb/cockroach/blob/1896e1ad54566820a96a0afbcf72f2b02752e100/pkg/ccl/backupccl/restore_job.go#L548)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

FWIW, it's a silent case today -- we currently verify full-file checksums if they are there, but we don't say anything if they're not.
</blockquote></details>

Right, but now we have explicit settings.  So, if a user at some point had collectChecksums == false; but then changed their mind and turned on`verifyChecksums`, shouldn't we log a message saying that we're skipping checksum verification even if the setting is true?

UP to you -- but I do think that if we can't honor explicit request (verifyChecksum), then we should log.
Or maybe, rename setting to verify_full_file_checksums_if_available...

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58404)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[pkg/ccl/backupccl/restore_job.go, line 548 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58404#-MQ9YUe8DLD9udyFh5WU:-MQHxAkKC83KSP8Hypq-:bomb1ls) ([raw file](https://github.com/cockroachdb/cockroach/blob/1896e1ad54566820a96a0afbcf72f2b02752e100/pkg/ccl/backupccl/restore_job.go#L548)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Right, but now we have explicit settings.  So, if a user at some point had collectChecksums == false; but then changed their mind and turned on`verifyChecksums`, shouldn't we log a message saying that we're skipping checksum verification even if the setting is true?

UP to you -- but I do think that if we can't honor explicit request (verifyChecksum), then we should log.
Or maybe, rename setting to verify_full_file_checksums_if_available...

</blockquote></details>

Yeah, could rename it -- I included that "if present" in the setting help text but was keeping the name itself concise. 

I'm sort of leaning towards just removing these settings entirely though, and doing this unconditionally. If we trust the block checksums -- which we're saying we do as soon as we allow skipping the file checksums -- then we should just say that they're what we're going to trust, and not confuse users with the extra settings, the above discussion of extending `show backup`, etc.

**Review by miretskiy — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58404)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

___
*[pkg/ccl/backupccl/restore_job.go, line 548 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58404#-MQ9YUe8DLD9udyFh5WU:-MQI7B38DvzyUtulFkCj:b6e7osa) ([raw file](https://github.com/cockroachdb/cockroach/blob/1896e1ad54566820a96a0afbcf72f2b02752e100/pkg/ccl/backupccl/restore_job.go#L548)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Yeah, could rename it -- I included that "if present" in the setting help text but was keeping the name itself concise. 

I'm sort of leaning towards just removing these settings entirely though, and doing this unconditionally. If we trust the block checksums -- which we're saying we do as soon as we allow skipping the file checksums -- then we should just say that they're what we're going to trust, and not confuse users with the extra settings, the above discussion of extending `show backup`, etc.
</blockquote></details>

I would be fine with this.

**Review by miretskiy — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58404#-:-MQI7I4HAgeP73QNxf1t:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58404)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @miretskiy)

___
*[pkg/ccl/backupccl/restore_job.go, line 548 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58404#-MQ9YUe8DLD9udyFh5WU:-MQINU677E1nt-oYLqCq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1896e1ad54566820a96a0afbcf72f2b02752e100/pkg/ccl/backupccl/restore_job.go#L548)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I would be fine with this. 
</blockquote></details>

Done.

**Comment by dt** [comment]
uh, what GitHub? I just pushed a rebase? and now I can't re-open?

**Pull request closed without merging**
