### PR TITLE
sql: pool FlowSpecs and TableReaderSpecs

### PR DESCRIPTION
**Pull request by jordanlewis**
Broken out from #30556.

The first commit is a slightly unrelated but necessary change to refactor
plan diagram creation. The explain analyze output changes slightly as a
result - the stats diagram lines are moved to the end of the box, instead of
always occurring before the post-process lines in the box. I don't think this
is a big deal - if we really care it's possible to fix, but it just takes a little more
bookkeeping.

Previously, plan diagram creation and annotation of plan diagrams with
span stats was done in one step that couldn't be decomposed. This commit
changes the interface of plan diagrams a bit to permit decomposing the
two steps.

Now, plan diagrams are represented with an interface, FlowDiagram, that
exposes a method to generate JSON and a method to augment the diagram
with statistics from tracing spans.

This is necessary to permit more granular resource management of
FlowSpecs in the next commit - the plan diagram needs to be generated
before the flow is cleaned up, but the tracing spans are only available
after the flow is cleaned up.

n.b. this moves the stats lines of each processor in the diagram below
the post processor line.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30607)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsql_physical_planner.go, line 1093 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30607#-LND0zzgAcYUP7OLx_My:-LND0zzgAcYUP7OLx_Mz:b-rs41bj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8dfc7336664719ffb94d7d1f02bbf339c25d4f4/pkg/sql/distsql_physical_planner.go#L1093)):*
> ```Go
> 		var tr *distsqlrun.TableReaderSpec
> 		if i == 0 {
> 			// For the first span, we can just directly use the spec we made above.
> ```

[nit] span partition

Also, can't we put `s` on the stack and avoid special casing i=0?
___
*[pkg/sql/distsqlrun/api.go, line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30607#-LND1GlD6D3_aY9p-kCl:-LND1GlD6D3_aY9p-kCm:b-ll2a7c) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8dfc7336664719ffb94d7d1f02bbf339c25d4f4/pkg/sql/distsqlrun/api.go#L79)):*
> ```Go
> // Release puts this TableReaderSpec back into its sync pool. It may not be used
> // again after Release returns.
> func (s *TableReaderSpec) Release() {
> ```

Where is this called?

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30607)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/api.go, line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30607#-LND1GlD6D3_aY9p-kCl:-LNDGAKzDpXW2jexP5g1:b-9qpbwg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8dfc7336664719ffb94d7d1f02bbf339c25d4f4/pkg/sql/distsqlrun/api.go#L79)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Where is this called?
</blockquote></details>

It'll be called during flow teardown. I tried to pull this out of the larger linked PR but it might be a lost cause to get all the commits independent.

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/distsqlrun/api.go, line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30607#-LND1GlD6D3_aY9p-kCl:-LNFknTVBvHYqcl3JPGb:bvk71lf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8dfc7336664719ffb94d7d1f02bbf339c25d4f4/pkg/sql/distsqlrun/api.go#L79)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

It'll be called during flow teardown. I tried to pull this out of the larger linked PR but it might be a lost cause to get all the commits independent. 
</blockquote></details>

I guess the PR is functional without calling this. I am just worried that we hand these off to grpc and in principle it could hold on to them and retry RPCs

**Comment by jordanlewis** [comment]
I updated it to include the other part of the puzzle, pooled FlowSpecs and the release of both objects.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30607)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsql_physical_planner.go, line 850 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30607#-LNG8Em83PXIL4Ncv7kV:-LNG8Em83PXIL4Ncv7kW:b-wnrrwp) ([raw file](https://github.com/cockroachdb/cockroach/blob/174b607d21d23c83c190a467f22c96d35f9ce44c/pkg/sql/distsql_physical_planner.go#L850)):*
> ```Go
> // corresponds to a scanNode, except for the Spans and OutputColumns.
> // Only needs indexVarMap for a filter expression - if there's no filter
> // expression in the scanNode, it's valid to pass a nil indexVarMap.
> ```

It's always valid to pass a `nil` indexVarMap which means identity.
___
*[pkg/sql/distsqlplan/physical_plan.go, line 827 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30607#-LNGAZMo3tqvjBaw43Th:-LNGAZMo3tqvjBaw43Ti:bunv1dk) ([raw file](https://github.com/cockroachdb/cockroach/blob/174b607d21d23c83c190a467f22c96d35f9ce44c/pkg/sql/distsqlplan/physical_plan.go#L827)):*
> ```Go
> 		if !ok {
> 			flowSpec = distsqlrun.NewFlowSpec()
> 			flows[proc.Node] = flowSpec
> ```

Don't we need to set the FlowID and Gateway here?
___
*[pkg/sql/distsqlrun/api.go, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30607#-LNG9zQT3fgnk-i_Nk6t:-LNG9zQT3fgnk-i_Nk6u:b-z5stiv) ([raw file](https://github.com/cockroachdb/cockroach/blob/174b607d21d23c83c190a467f22c96d35f9ce44c/pkg/sql/distsqlrun/api.go#L66)):*
> ```Go
> }
> 
> var trSpecPool = sync.Pool{
> ```

I don't think this belongs in `distsqlrun`; it's only used in the planning code. I'd put it either in `sql` or in `distsqlplan`. They can be global functions, eg `RelaseTableReaderSpec`

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30607)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsql_physical_planner.go, line 1093 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30607#-LND0zzgAcYUP7OLx_My:-LNGXtJn6gC0eyPKyfvA:bnqc837) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8dfc7336664719ffb94d7d1f02bbf339c25d4f4/pkg/sql/distsql_physical_planner.go#L1093)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] span partition

Also, can't we put `s` on the stack and avoid special casing i=0?
</blockquote></details>

I don't think so because we want to reuse the Spans memory that we get back from the pooled spec. I hadn't added that particular change into this commit, but it's there now.
___
*[pkg/sql/distsqlplan/physical_plan.go, line 827 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30607#-LNGAZMo3tqvjBaw43Th:-LNGCUtu4TSfjxJAHVoI:b-lfc45z) ([raw file](https://github.com/cockroachdb/cockroach/blob/174b607d21d23c83c190a467f22c96d35f9ce44c/pkg/sql/distsqlplan/physical_plan.go#L827)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Don't we need to set the FlowID and Gateway here?
</blockquote></details>

Oops, yeah, done.

**Comment by jordanlewis** [comment]
Ping @asubiotto

**Review by asubiotto — APPROVED** [review]
> Reviewed 4 of 12 files at r3, 6 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30607)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlplan/physical_plan.go, line 827 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/30607#-LNpt5hI20rUwqM0r7BN:-LNpt5hI20rUwqM0r7BO:b-ttllnl) ([raw file](https://github.com/cockroachdb/cockroach/blob/108086a584925465a4424a4d6dc2d6da71ebe77c/pkg/sql/distsqlplan/physical_plan.go#L827)):*
> ```Go
> 		if !ok {
> 			flowSpec = NewFlowSpec()
> 			flowSpec.FlowID = flowID
> ```

What about making these arguments to `NewFlowSpec`? Same with `tableReader`, might avoid programming error.
___
*[pkg/sql/distsqlplan/specs.go, line 58 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/30607#-LNptlsW9qvyoCGmMP8k:-LNptlsW9qvyoCGmMP8l:b1dwdjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/108086a584925465a4424a4d6dc2d6da71ebe77c/pkg/sql/distsqlplan/specs.go#L58)):*
> ```Go
> // may not be used again after Release returns.
> func ReleaseTableReaderSpec(s *distsqlrun.TableReaderSpec) {
> 	s.Reset()
> ```

If you decide to pass in arguments to `NewTableReaderSpec`, you could remove the reset here and do it there/do a partial reset.

**Review by jordanlewis — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30607#-:-LNriTcm34URhdm6kz2N:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlplan/physical_plan.go, line 827 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/30607#-LNpt5hI20rUwqM0r7BN:-LNriN8K84jTxhXCT8t4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/108086a584925465a4424a4d6dc2d6da71ebe77c/pkg/sql/distsqlplan/physical_plan.go#L827)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What about making these arguments to `NewFlowSpec`? Same with `tableReader`, might avoid programming error.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlplan/specs.go, line 58 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/30607#-LNptlsW9qvyoCGmMP8k:-LNriO3H51bkak02nqCB:b-fx4bn2) ([raw file](https://github.com/cockroachdb/cockroach/blob/108086a584925465a4424a4d6dc2d6da71ebe77c/pkg/sql/distsqlplan/specs.go#L58)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

If you decide to pass in arguments to `NewTableReaderSpec`, you could remove the reset here and do it there/do a partial reset.
</blockquote></details>

I think the pattern of resetting before putting into the pool is more standard, so I'm going to keep that.
___
*[pkg/sql/distsqlrun/api.go, line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30607#-LND1GlD6D3_aY9p-kCl:-LNriSGT-MT3ADz658Ep:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8dfc7336664719ffb94d7d1f02bbf339c25d4f4/pkg/sql/distsqlrun/api.go#L79)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I guess the PR is functional without calling this. I am just worried that we hand these off to grpc and in principle it could hold on to them and retry RPCs
</blockquote></details>

Done.

**Pull request merged**
