### PR TITLE
tree: resolve bounded staleness in EvalAsOfTimestamp

### LINKED ISSUE #67555: sql: implement bounded staleness builtin functions
Part of #66020.
Needed for **stage 1**.

See https://github.com/cockroachdb/cockroach/blob/025c53decd8eb00cb70a1d410692026c9f8614dc/docs/RFCS/20210519_bounded_staleness_reads.md#sql-parser.
Prototyped in #62239.

### PR DESCRIPTION
**Pull request by otan**
See individual commits for details.
Resolves #67555

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 17 of 17 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67741)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nihalpednekar and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/as_of, line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67741#-MezkJZY75fO11p5Qqkb:-MezkJZZD4CpwtXHfvgk:b-r8mic4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0405b37d175cddf43c45c3544e25cbf59207b0a/pkg/ccl/logictestccl/testdata/logic_test/as_of#L126)):*
> ```
> does not yet work
> ```

Bounded staleness queries in explicit transactions are not something I imagine we will support because the semantics around which timestamp to use are strange and not particularly useful. Consider being more direct here and saying that this is unsupported.
___
*[pkg/sql/sem/tree/as_of.go, line 84 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67741#-MeziyrD0-PY9iDiu_HB:-MeziyrD0-PY9iDiu_HC:bfd0ga6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0405b37d175cddf43c45c3544e25cbf59207b0a/pkg/sql/sem/tree/as_of.go#L84)):*
> ```Go
> 	// Timestamp is the HLC timestamp evaluated from the AS OF SYSTEM TIME clause.
> 	Timestamp hlc.Timestamp
> 	// BoundedStaleness is true if the AS OF SYSTEM TIME clause allows bounded
> ```

Is "allows" the right word here? That makes it sound like this flag can be ignored. But it can't, right? It changes the semantics of the `Timestamp` field, from the exact timestamp to evaluate the query to a minimum staleness bound used to dynamically determine the timestamp to evaluate the query.
___
*[pkg/sql/sem/tree/as_of.go, line 110 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67741#-MezjVMwB0Bf2wV-Lh4_:-MezjVMwB0Bf2wV-Lh4a:bj6mo49) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0405b37d175cddf43c45c3544e25cbf59207b0a/pkg/sql/sem/tree/as_of.go#L110)):*
> ```Go
> 	opts ...EvalAsOfTimestampOption,
> ) (AsOfSystemTime, error) {
> 	o := evalAsOfTimestampOptions{}
> ```

This options struct is forced to allocate and escape to the heap, right? I'm trying to remember how many heap allocations this options pattern causes. The static allocation of `EvalAsOfTimestampOptionAllowBoundedStaleness` avoids one, and then the varargs shouldn't cause any (but worth confirming, they may if not inlined), so maybe this is the only one.

Consider replacing `type EvalAsOfTimestampOption func(o *evalAsOfTimestampOptions)` with `type EvalAsOfTimestampOption func(o evalAsOfTimestampOptions) evalAsOfTimestampOptions` to avoid the heap allocation.
___
*[pkg/sql/sem/tree/as_of.go, line 119 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67741#-Mezk6K-DaHnYX7KeUzy:-Mezk6K09q8IQ1L7b-q_:bqxxl5q) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0405b37d175cddf43c45c3544e25cbf59207b0a/pkg/sql/sem/tree/as_of.go#L119)):*
> ```Go
> 		if o.allowBoundedStaleness {
> 			optFuncs = fmt.Sprintf(
> 				", %s, %s",
> ```

nit: comma at the end of string

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67741)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nihalpednekar and @nvanbenschoten)

___
*[pkg/sql/sem/tree/as_of.go, line 119 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67741#-Mezk6K-DaHnYX7KeUzy:-Mf-d-cC1WY5siJlqthg:b-yzqjv1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0405b37d175cddf43c45c3544e25cbf59207b0a/pkg/sql/sem/tree/as_of.go#L119)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: comma at the end of string
</blockquote></details>

oh no, a believer of the oxford comma D:

Done

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67741#-:-Mf1OzzY7_EYVswZgOtd:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nihalpednekar)

___
*[pkg/sql/sem/tree/as_of.go, line 84 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67741#-MeziyrD0-PY9iDiu_HB:-Mf1OZzoCFEWtJkAla5S:bsng7gx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0405b37d175cddf43c45c3544e25cbf59207b0a/pkg/sql/sem/tree/as_of.go#L84)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is "allows" the right word here? That makes it sound like this flag can be ignored. But it can't, right? It changes the semantics of the `Timestamp` field, from the exact timestamp to evaluate the query to a minimum staleness bound used to dynamically determine the timestamp to evaluate the query.
</blockquote></details>

This comment or the one above should probably also discuss the difference in the meaning of `Timestamp` when `BoundedStaleness` is set to true versus when it is set to false.

**Comment by otan** [comment]
bors r=nvanbenschoten

**Pull request merged**
