### PR TITLE
sql,tracing: introduce crdb_internal.cluster_inflight_traces

### PR DESCRIPTION
**Pull request by adityamaru**
This change adds a new indexed, virtual table
`crdb_internal.cluster_inflight_traces`. This table surfaces
cluster-wide inflight traces for the trace_id specified via
an index constraint.

Each row in the virtual table corresponds to a
`tracing.Recording` on a particular node for the given
trace ID. A `tracing.Recording` is the trace of a single
operation rooted at a root span on that node. Under the hood,
the virtual table contacts all "live" nodes in the cluster
via the trace collector which streams back a recording at a
time.

The table has 3 additional columns that surface the raw JSON,
string, and JaegarJSON representation of the recording. These
formats are what we dump in a stmt bundle as well, and have
been considered the best way to consume traces. This table
is not meant to be consumed directly via the SQL shell but
will have CLI wrapper built on top of it that will assimilate
and write the traces to files. Similar to how we dump a stmt
bundle.

This change also tweaks some of the recording->string methods
to include StructuredRecords.

Informs: #64992

Release note (sql change): adds a virtual table
`crdb_internal.cluster_inflight_traces` which surfaces
cluster-wide inflight traces for the trace_id specified via
an index constraint. The output of this table is not appropriate
to consume over a SQL connection; follow up changes will add
CLI wrappers to make the interaction more user-friendly.

### CODE REVIEW

**Comment by adityamaru** [comment]
First commit is from https://github.com/cockroachdb/cockroach/pull/66678, will rebase once that is merged!

**Review by abarganier — COMMENTED** [review]
> Reviewed 3 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66679)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @knz)

___
*[pkg/sql/crdb_internal.go, line 1261 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66679#-MctOwmh-MwMiWqbS6AQ:-MctOwmh-MwMiWqbS6AR:b-enf1fw) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e7f7e0ea16085a31516aa733ad1da69a896dae4/pkg/sql/crdb_internal.go#L1261)):*
> ```
> return false, nil
> ```
Should we be returning true if any rows were generated?
___
*[pkg/sql/crdb_internal_test.go, line 897 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66679#-MctaU2NDCZvqlp9MSjS:-MctaU2NDCZvqlp9MSjT:b-eea6qh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e7f7e0ea16085a31516aa733ad1da69a896dae4/pkg/sql/crdb_internal_test.go#L897)):*
> ```
> 			[][]string{{strconv.Itoa(int(traceID)), `1`}, {strconv.Itoa(int(traceID)), `1`},
> 				{strconv.Itoa(int(traceID)), `2`}})
> ```
Is it worth the trouble to make assertions against the recording columns as well? 
___
*[pkg/sql/explain_bundle.go, line 312 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66679#-MctbQz7Ei9LRVPyZsQ5:-MctbQz7Ei9LRVPyZsQ6:b-7wjosr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e7f7e0ea16085a31516aa733ad1da69a896dae4/pkg/sql/explain_bundle.go#L312)):*
> ```
> select JSON File
> ```
nit: "select the JSON file" 
___
*[pkg/util/tracing/recording.go, line 220 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66679#-MctiDrB-Oa5rgxt5SzO:-MctiDrCE_VV6O3tEps4:bfctngr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e7f7e0ea16085a31516aa733ad1da69a896dae4/pkg/util/tracing/recording.go#L220)):*
<details><summary><i alt="summary">Quoted 17 lines of code…</i></summary>

> ```
> 	// If the span was verbose then the Structured events would have been
> 	// stringified and included in the Logs above. If the span was not verbose
> 	// we should add the Structured events now.
> 	if !isVerbose(sp) {
> 		sp.Structured(func(sr *types.Any, t time.Time) {
> 			lr := opentracing.LogRecord{
> 				Timestamp: t,
> 			}
> 			str, err := MessageToJSONString(sr, true /* emitDefaults */)
> 			if err != nil {
> 				return
> 			}
> 			lr.Fields = append(lr.Fields, otlog.String("structured", str))
> 			lastLog := ownLogs[len(ownLogs)-1]
> 			ownLogs = append(ownLogs, conv(lr, lastLog.Timestamp))
> 		})
> 	}
> ```
</details>

I'm surprised we weren't including Structured events to some degree before in this non-verbose case, both here and in `ToJaegerJSON()`. Seems like verbosity doesn't impact the recording of structured events though, so it should be ok? Just checking. 
___
*[pkg/util/tracing/utils.go, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66679#-MctntWyAqjdqyZj-cvA:-MctntWyAqjdqyZj-cvB:bi0u6wx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e7f7e0ea16085a31516aa733ad1da69a896dae4/pkg/util/tracing/utils.go#L1)):*
> ```Go
> // Copyright 2021 The Cockroach Authors.
> ```

nit: rename file to something more explicit, e.g. `json_conv.go`

**Review by knz — COMMENTED** [review]
No objection on the overall idea, but  I'm not seeing any memory monitoring for the trace collector. What mechanism ensures that a node won't explode in RAM usage if there is a lot of trace data to collect?

> Reviewed 14 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66679#-:-Mctp_Tc8_iOm9vQPkS9:bwx6j2t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru)

**Comment by adityamaru** [comment]
> No objection on the overall idea, but I'm not seeing any memory monitoring for the trace collector. What mechanism ensures that a node won't explode in RAM usage if there is a lot of trace data to collect?
> 
> >

@knz the trace collector is an iterator that only buffers a single node's recordings at a time. It serves from these buffered recordings until there are no more, and only then contacts the next node for its recordings. If I understand the vtable infrastructure correctly, it is also lazy in the way it pushes rows. i.e it will only buffer the datums of a single row (in our case a single trace recording at a time), until the consumer consumes the row. So at most we should be buffering the O(inflight trace recordings of a single node) at a time. I agree that memory monitoring even within this buffering is advisable but just wanted to clarify the current behavior.

**Comment by knz** [comment]
Maybe you could sprinkle the code in various places to explain memory consumption.

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66679)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @knz)

___
*[pkg/sql/crdb_internal.go, line 1261 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66679#-MctOwmh-MwMiWqbS6AQ:-McyIoalAMvEybZoEqKq:b-rmsntx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e7f7e0ea16085a31516aa733ad1da69a896dae4/pkg/sql/crdb_internal.go#L1261)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

> ```
> return false, nil
> ```
Should we be returning true if any rows were generated?
</blockquote></details>

nice catch, done.
___
*[pkg/sql/crdb_internal_test.go, line 897 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66679#-MctaU2NDCZvqlp9MSjS:-McyN2Dc8FbnuyUXNm2O:bslh6i9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e7f7e0ea16085a31516aa733ad1da69a896dae4/pkg/sql/crdb_internal_test.go#L897)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

> ```
> 			[][]string{{strconv.Itoa(int(traceID)), `1`}, {strconv.Itoa(int(traceID)), `1`},
> 				{strconv.Itoa(int(traceID)), `2`}})
> ```
Is it worth the trouble to make assertions against the recording columns as well? 
</blockquote></details>

We do have tests at the trace collector level to check that we are fetching the correct spans, so I'm inclined to avoid making assertions to check the json conversion/string conversion. In other words we know with a high degree of confidence that `nodeID, recording` returned on each iteration is correct. Testing the util methods involves a lot of stripping and regexing because of the variable timestamps. Taking a page from `explain_bundle_test.go` we should check that the size of the column is not zero.
___
*[pkg/util/tracing/recording.go, line 220 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66679#-MctiDrB-Oa5rgxt5SzO:-McyJG5A1PsjsKBBY7-z:b-6zl8be) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e7f7e0ea16085a31516aa733ad1da69a896dae4/pkg/util/tracing/recording.go#L220)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

> ```
> 	// If the span was verbose then the Structured events would have been
> 	// stringified and included in the Logs above. If the span was not verbose
> 	// we should add the Structured events now.
> 	if !isVerbose(sp) {
> 		sp.Structured(func(sr *types.Any, t time.Time) {
> 			lr := opentracing.LogRecord{
> 				Timestamp: t,
> 			}
> 			str, err := MessageToJSONString(sr, true /* emitDefaults */)
> 			if err != nil {
> 				return
> 			}
> 			lr.Fields = append(lr.Fields, otlog.String("structured", str))
> 			lastLog := ownLogs[len(ownLogs)-1]
> 			ownLogs = append(ownLogs, conv(lr, lastLog.Timestamp))
> 		})
> 	}
> ```
I'm surprised we weren't including Structured events to some degree before in this non-verbose case, both here and in `ToJaegerJSON()`. Seems like verbosity doesn't impact the recording of structured events though, so it should be ok? Just checking. 
</blockquote></details>

If the span is verbose, which is the only time a statement bundle would be useful, then all structured events are stringified and added to the log records. Now we have a use case where we might want to pull traces from a non-verbose span, that still records structured events, but does not record log events. 
___
*[pkg/util/tracing/utils.go, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66679#-MctntWyAqjdqyZj-cvA:-McyK-DX2_OSIVu0YX2A:b-kfdw66) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e7f7e0ea16085a31516aa733ad1da69a896dae4/pkg/util/tracing/utils.go#L1)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: rename file to something more explicit, e.g. `json_conv.go`
</blockquote></details>

we have several other places in the code where we have `utils` files that seem to become home to general utility methods that don't really have another place to live in the surrounding infrastructure. I don't feel strongly about it either way, but might be good to have a more free-form place for future tracing work? Happy to go either way!

**Comment by adityamaru** [comment]
> Maybe you could sprinkle the code with comments in various places to explain memory consumption.

Yup, added a comment above the virtual table definition! I do think that this might need to be revisited in the future, if we start seeing a lot of unfinished "root spans" on each node during bulk job execution. Off the top of my head though, this should not be an issue.

**Comment by knz** [comment]
no further comments from me

**Review by abarganier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66679)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @adityamaru, and @knz)

___
*[pkg/sql/crdb_internal.go, line 1261 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66679#-MctOwmh-MwMiWqbS6AQ:-Md2dWYT1FTVWqPVfDT8:bo5kvfs) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e7f7e0ea16085a31516aa733ad1da69a896dae4/pkg/sql/crdb_internal.go#L1261)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

nice catch, done.
</blockquote></details>

Since we're adding rows in a loop, what if `addRow` is successful on the 1st iteration, but fails on the 2nd? Is this a transactional operation? If not, then would we still want to return true, since the 1st iteration succeeded?
___
*[pkg/sql/crdb_internal_test.go, line 897 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66679#-MctaU2NDCZvqlp9MSjS:-Md2eCr3ApjeRgSXh1eJ:b-gmh6jr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e7f7e0ea16085a31516aa733ad1da69a896dae4/pkg/sql/crdb_internal_test.go#L897)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

We do have tests at the trace collector level to check that we are fetching the correct spans, so I'm inclined to avoid making assertions to check the json conversion/string conversion. In other words we know with a high degree of confidence that `nodeID, recording` returned on each iteration is correct. Testing the util methods involves a lot of stripping and regexing because of the variable timestamps. Taking a page from `explain_bundle_test.go` we should check that the size of the column is not zero.
</blockquote></details>

`NotEmpty` checks SGTM! Thanks.
___
*[pkg/util/tracing/recording.go, line 220 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66679#-MctiDrB-Oa5rgxt5SzO:-Md2eSc51jGsS0-V4ZVp:b-ce6elh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e7f7e0ea16085a31516aa733ad1da69a896dae4/pkg/util/tracing/recording.go#L220)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

If the span is verbose, which is the only time a statement bundle would be useful, then all structured events are stringified and added to the log records. Now we have a use case where we might want to pull traces from a non-verbose span, that still records structured events, but does not record log events. 
</blockquote></details>

:thumbsup: thanks for clarifying
___
*[pkg/util/tracing/utils.go, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66679#-MctntWyAqjdqyZj-cvA:-Md2eZWD1n-jEYyLEIQN:b-p43adr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e7f7e0ea16085a31516aa733ad1da69a896dae4/pkg/util/tracing/utils.go#L1)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

we have several other places in the code where we have `utils` files that seem to become home to general utility methods that don't really have another place to live in the surrounding infrastructure. I don't feel strongly about it either way, but might be good to have a more free-form place for future tracing work? Happy to go either way!
</blockquote></details>

If there's precedent elsewhere then I don't feel too strongly about it, thanks for clarifying!
___
*[pkg/util/tracing/collector/collector.go, line 40 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66679#-Md2jWEj5zePAQxb5O6N:-Md2jWEj5zePAQxb5O6O:b5moj9x) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a9a5ee34321a6d032a6d31b94993f1c98d1ab57/pkg/util/tracing/collector/collector.go#L40)):*
> ```
> mon          *mon.BytesMonitor
> ```
unused?

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66679)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @adityamaru, and @knz)

___
*[pkg/sql/crdb_internal.go, line 1261 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66679#-MctOwmh-MwMiWqbS6AQ:-MdFwXgs4o_-KlfEYSDb:bo54t3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e7f7e0ea16085a31516aa733ad1da69a896dae4/pkg/sql/crdb_internal.go#L1261)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Since we're adding rows in a loop, what if `addRow` is successful on the 1st iteration, but fails on the 2nd? Is this a transactional operation? If not, then would we still want to return true, since the 1st iteration succeeded?
</blockquote></details>

The vtable generator returns a row as and when a consumer consumes it. There isn't any transactional guarantee, so if the second `addRow` were to return an error, the consumer would see that error being bubbled up and would hopefully deal with it with an appropriate `if err != nil`.
___
*[pkg/sql/crdb_internal_test.go, line 897 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66679#-MctaU2NDCZvqlp9MSjS:-MdFwypo8AxH-hfhMuTz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e7f7e0ea16085a31516aa733ad1da69a896dae4/pkg/sql/crdb_internal_test.go#L897)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

`NotEmpty` checks SGTM! Thanks.
</blockquote></details>

Done.
___
*[pkg/util/tracing/collector/collector.go, line 40 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66679#-Md2jWEj5zePAQxb5O6N:-MdFx0rX-INkWoE-lXzK:b-ksc2nc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a9a5ee34321a6d032a6d31b94993f1c98d1ab57/pkg/util/tracing/collector/collector.go#L40)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

> ```
> mon          *mon.BytesMonitor
> ```
unused?
</blockquote></details>

yup, deleted.

**Review by abarganier — APPROVED** [review]
:lgtm: nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66679#-:-MdIAPxT9afJZ9uZ-IRo:b-kbynj8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier, @adityamaru, and @knz)

___
*[pkg/sql/crdb_internal.go, line 1261 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66679#-MctOwmh-MwMiWqbS6AQ:-MdIAK3sCttU_iX7ju-q:b2nhb2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e7f7e0ea16085a31516aa733ad1da69a896dae4/pkg/sql/crdb_internal.go#L1261)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

The vtable generator returns a row as and when a consumer consumes it. There isn't any transactional guarantee, so if the second `addRow` were to return an error, the consumer would see that error being bubbled up and would hopefully deal with it with an appropriate `if err != nil`.
</blockquote></details>

Ack

**Comment by adityamaru** [comment]
TFTR!

bors r=abarganier

**Pull request merged**
