### PR TITLE
storage: de-flake TestComputeVerifyChecksum

### PR DESCRIPTION
**Pull request by tamird**
Closes #7782.

Same as #7782 but also attempts to make the positive case assertion stronger.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7785)

### CODE REVIEW

**Comment by tschottdorf** [comment]
Could you point out where the positive case is being made stronger? Don't see it (must be hidden in what looks mostly like a refactor). LGTM otherwise.

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7785#-:-KMVxyvv6Q8YqLK8ynLH:-1574070975)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/replica_test.go, line 5412 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7785#-KMVzEXu8npye6JMk37O:-KMVzEXu8npye6JMk37P:-200235479) ([raw file](https://github.com/cockroachdb/cockroach/blob/35b231854a83fe66fdee897d926a9e49a0d42982/storage/replica_test.go#L5412)):*
> ```Go
> 
> 		appliedIndex := getAppliedIndex()
> 		if diff := appliedIndex - oldAppliedIndex; diff != 1 {
> ```

@tschottdorf here - we're asserting that exactly the command we expect has executed in the intervening time

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7785)*

**Comment by tschottdorf** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/replica_test.go, line 5412 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7785#-KMVzEXu8npye6JMk37O:-KMY3BBD5oKhmi5zzJuI:1232472862) ([raw file](https://github.com/cockroachdb/cockroach/blob/35b231854a83fe66fdee897d926a9e49a0d42982/storage/replica_test.go#L5412)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> @tschottdorf here - we're asserting that exactly the command we expect has executed in the intervening time
</details>
Ah, gotcha.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7785)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7785)*

**Pull request merged**
