### PR TITLE
build: run builder as invoking user.

### PR DESCRIPTION
**Pull request by jordanlewis**
This commit adds a small amount of extra machinery to the docker
invocation to make commands run in the container as a user with the same
id as the invoking user. This guarantees that new files and directories
created by the build process (`.npm/*, .jspm/*, pkg/docker_amd64/*,
bin/docker_amd64/*`, other generated files) will be owned by the invoking
user and not as root.

This is useful for TeamCity and also probably nice for users running
this in their local environment.

One potential issue is that users who have let those files named above
be owned by root will encounter permission errors when running the
builder after this patch. The fix is to chown everything to the external
user from outside of the container and try again.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8311)

### CODE REVIEW

**Comment by tamird** [comment]
We already chown things everywhere, so if this does what it says, you should be able to also include this diff:
```diff
diff --git a/build/circle-deps.sh b/build/circle-deps.sh
index 47619cd..8d5fe79 100755
--- a/build/circle-deps.sh
+++ b/build/circle-deps.sh
@@ -144,19 +144,12 @@ if is_shard 2; then
   # parallelism. Avoid deleting our build output in that case.
   if ! is_shard 0; then
     for dir in "${HOME}/.jspm" "${HOME}/.npm"; do
-      # A side-effect of using build/builder.sh is that files created by
-      # the builder are owned by root.root. This isn't normally a
-      # problem, except when trying to rsync onto these directories by a
-      # non-root user which runs into permissions problem. So before
-      # rsyncing, we chown all the files to the current user.
-      time ssh node0 sudo chown -R "${USER}.${USER}" "${dir}"
       time rsync -a --delete "${dir}/" node0:"${dir}"
     done
 
     cmds=$(grep '^cmd ' GLOCKFILE | grep -v glock | awk '{print $2}' | awk -F/ '{print $NF}')
     path="${gopath0}/bin/docker_amd64"
     time ssh node0 mkdir -p "$path"
-    time ssh node0 sudo chown "${USER}.${USER}" "$path"
     (time cd "$path" && rsync ${cmds} node0:"${path}")
   fi
 fi
@@ -166,7 +159,6 @@ if is_shard 1; then
   # parallelism. Avoid deleting our build output in that case.
   if ! is_shard 0; then
     dir="${gopath0}/pkg/docker_amd64_race"
-    time ssh node0 sudo chown -R "${USER}.${USER}" "${dir}"
     time rsync -a --delete "${dir}/" node0:"${dir}"
   fi
 fi
@@ -192,7 +184,6 @@ if is_shard 0; then
   if ! is_shard 2; then
     node=$((2 % $CIRCLE_NODE_TOTAL))
     dir="${gopath0}/pkg/docker_amd64"
-    time sudo chown -R "${USER}.${USER}" "${dir}"
     time rsync -au node${node}:"${dir}/" "${dir}"
   fi
 fi

```

Nice work!

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[build/builder.sh, line 62 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8311#-KOH4VTu4xIm0IZk3c8B:-KOH4VTvxe9ZreCifiGO:-1436413648) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fa676b4371aaafd015e491b687c317b5e16fb39/build/builder.sh#L62)):*
> ```Shell
> cockroach_toplevel="$(dirname $(cd $(dirname $0); pwd))"
> 
> # Make a fake passwd file for our user.
> ```

s/our user/the invoking user/g

---

*[build/builder.sh, line 95 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8311#-KOH57peI2WW9KHPAj2i:-KOH57peI2WW9KHPAj2j:-1117528666) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fa676b4371aaafd015e491b687c317b5e16fb39/build/builder.sh#L95)):*
> ```Shell
> vols="${vols} --volume=${HOME}/.npm:/root/.npm"
> vols="${vols} --volume=${cockroach_toplevel}:/go/src/github.com/cockroachdb/cockroach"
> vols="${vols} --volume=$(mktemp -d):/root"
> ```

nit: extract "/root" as a variable so you can leave a comment on it explaining why it's needed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8311#-:-KOH4EvzCFc_YLGXesnN:854678043)*

**Comment by jordanlewis** [comment]
I deleted these `chown`s as well as the `useradd` we were doing for the jspm user, which is now unnecessary and in fact harmful as the internal docker user no longer has root permissions and can't e.g. create a new user.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[build/builder.sh, line 62 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8311#-KOH4VTu4xIm0IZk3c8B:-KOHBPaDZot5KLE_R2e-:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fa676b4371aaafd015e491b687c317b5e16fb39/build/builder.sh#L62)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> s/our user/the invoking user/g
</details>
Done.

---

*[build/builder.sh, line 95 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8311#-KOH57peI2WW9KHPAj2i:-KOHBPBAcuf12JIJT2VQ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fa676b4371aaafd015e491b687c317b5e16fb39/build/builder.sh#L95)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: extract "/root" as a variable so you can leave a comment on it explaining why it's needed
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8311#-:-KOHBMwyMgyjhotndMhm:-104471479)*

**Comment by tamird** [comment]
Excellent! cc @petermattis 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[build/builder.sh, line 68 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8311#-KOHH8jUgEK81ZYwDqyl:-KOHH8jUgEK81ZYwDqym:337870446) ([raw file](https://github.com/cockroachdb/cockroach/blob/004cb0a71706f78c9f34a1026b8fde58b76f0bc5/build/builder.sh#L68)):*
> ```Shell
> # We'll mount a fresh directory owned by the invoking user as /root inside
> # the container so the container user is able to write there.
> BUILD_HOME="/root"
> ```

heh, can you make this lowercase? inconsistent

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8311#-:-KOHHDe7RdEXXYAawGZ3:2022704678)*

**Comment by jordanlewis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[build/builder.sh, line 68 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8311#-KOHH8jUgEK81ZYwDqyl:-KOHHTv-lntGyyeoFShk:-1201652230) ([raw file](https://github.com/cockroachdb/cockroach/blob/004cb0a71706f78c9f34a1026b8fde58b76f0bc5/build/builder.sh#L68)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> heh, can you make this lowercase? inconsistent
</details>
My reasoning for keeping this UPPER_CASE is that it's a mimic of the $HOME environment variable but I don't really care either way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8311)*

**Comment by tamird** [comment]
I believe this is causing a failure in #8317: https://circleci.com/gh/tamird/cockroach/420. In particular, [`go test -v -i ./...`](https://github.com/cockroachdb/cockroach/blob/6bd2d0a/build/circle-deps.sh#L75) is failing with `go install cmd/cgo: open /usr/local/go/pkg/tool/linux_amd64/cgo: permission denied`.

It seems that `go test -i` is trying to write some stuff in `$GOROOT`, which is unsurprisingly owned by root (because that's who built the container).

Should we replace the old `chown`s with `chown`s of `$GOROOT`? I'm going to try it on my branch.

**Comment by jordanlewis** [comment]
Hmmm this does seem like a problem indeed. I'm not sure why it didn't fail
in my testing. I don't think that the chown should be strictly necessary
unless something is actually modifying files that are only on the image -
installing something should work fine because GOROOT is explicitly mounted
from the host filesystem, I thought. I'll look into this more when I get
home.

**Comment by tamird** [comment]
GOROOT is on the image - GOPATH is what's mounted.

**Comment by jordanlewis** [comment]
This isn't causing all circle builds to fail - see for instance #8322 which does have this as a parent. I'm not sure why this build in particular is trying to write into `$GOROOT`.

**Comment by tamird** [comment]
You mean it is?

**Comment by jordanlewis** [comment]
No, I'm saying that there exist other PRs like the one I linked that have
this commit as an ancestor that are successfully building on Circle.

**Comment by tamird** [comment]
That doesn't mean that this PR didn't break them. The state of cached
artifacts on circle isn't always "ancestral".

**Pull request merged**
