### PR TITLE
build: added coverage uploading to codecov.io, ignore generated files, and optimize

### PR DESCRIPTION
**Pull request by d4l3k**
This added codecov.io as a coverage endpoint.

Ignores files that match
`(acceptance|cmd|ui/embedded|storage/simulation|sql/pgbench|.*\.(pb|pb\.gw)\.go)`
since we don't care about files that are generated or those which are only for
tests.

Only generate coverage profiles for packages that are actually dependencies of
the package we are testing.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7967)

### CODE REVIEW

**Comment by d4l3k** [comment]
The one issue with the later optimization, is that is misses some dependencies since `go list`'s `TestImports` and `XTestImports` isn't recursive and will miss recursive test dependencies.

I should probably remove it as runtime isn't crucial. It's mostly fine if it takes 2 hours to run on CI. Alternatively I could write a small script to recursively fetch test dependencies.

**Comment by jordanlewis** [comment]
I agree that you can remove the later optimization. It's no big deal if it takes a while to run, especially if the run is scheduled for a time when people don't need build agent capacity.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7967#-:-KNDqksQJBI63_1exbtL:-1723723012)*

**Comment by d4l3k** [comment]
Updated to correctly recursively determine test imported packages.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7967#-:-KNE4gpjeGNbTTO3im0q:123963521)*

**Comment by jordanlewis** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7967#-:-KNE7gkhNaE8XZVkPzr4:1417088721)*

**Pull request merged**
