### PR TITLE
sql: fix minor procedure bugs and add UDF/SP mixed tests

### PR DESCRIPTION
**Pull request by mgartner**
#### sql: fix bugs with procedures passing arguments to other procedures

This commit fixes a limitation where a procedure could not pass an
argument through to another procedure, like:

    CREATE PROCEDURE p(n INT) LANGUAGE SQL AS $$
      CALL other_proc(n);
    $$

To lift this restriction, the body of a procedure must be type-checked
with respect to the current scope which contains the procedures named
parameters. This change required a few subsequent changes to prevent
regressions:

  1. Copying some logic that ensures that `CALL` arguments are not
     subqueries to `optbuilder.subquery.TypeCheck`.
  2. Using `FuncExpr.InCall` instead of `CallAncestor` to determine the
     correct verbiage for error messages of procedures. `CallAncestor`
     is no longer used and has been removed.

Epic: None

Release note: None

#### sql/logictest: add tests for UDFs and SPs calling each other

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
The first two commits are from #120674.

**Review by yuzefovich — APPROVED** [review]
Last two commits :lgtm:

> Reviewed 6 of 6 files at r3, 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120718#-:-NtNlB604RvADRM6K3-A:by4jjvt)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/logictest/testdata/logic_test/udf_procedure_mix` line 43 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/120718#-NtNl4Gm32oS2vDBOuyR:-NtNl4Gm32oS2vDBOuyS:b-vkdg9n) ([raw file](https://github.com/cockroachdb/cockroach/blob/98f871e7a11e25ec557f16584cbab1a48ca85a84/pkg/sql/logictest/testdata/logic_test/udf_procedure_mix#L43)):*
> ```
> 
> query I
> SELECT fetch_sum_1_to_n(9)
> ```

nit: should we also check contents of `sums` table to ensure `9 45` row is there?

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 6 of 6 files at r3, 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120718#-:-NtP8oSCAIju0Cy3KyKY:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120718)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/logictest/testdata/logic_test/udf_procedure_mix` line 43 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/120718#-NtNl4Gm32oS2vDBOuyR:-NtSZSZz8Kt2zBLp1tZ_:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/98f871e7a11e25ec557f16584cbab1a48ca85a84/pkg/sql/logictest/testdata/logic_test/udf_procedure_mix#L43)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: should we also check contents of `sums` table to ensure `9 45` row is there?
</blockquote></details>

Good idea. Done.

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Comment by mgartner** [comment]
Flake.

bors r+

**Pull request merged**
