### PR TITLE
sql,workload: port rand to workload

### PR DESCRIPTION
**Pull request by jordanlewis**
Release note: None

### CODE REVIEW

**Review by danhhz — COMMENTED** [review]
Cool! Can you add a test that this generates the exact same table schemas given the same seed? In fact, I'd hope this would pass for all currently registered generators, we could a test that checks all of them in `workloadccl/all_test.go`

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30430#-:-LMnSNmIDyJxTkc6wMlC:b-sdy0sv)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/workload/rand/rand.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30430#-LMnSC0CDREEH41fmsqW:-LMnSC0DDKDJnlmINhjv:b-z2h7pg) ([raw file](https://github.com/cockroachdb/cockroach/blob/6700e2e19d788eaae32e351a41db5078fc4d1e41/pkg/workload/rand/rand.go#L60)):*
> ```Go
> 			`batch`: {RuntimeOnly: true},
> 		}
> 		g.flags.IntVar(&g.tables, `tables`, 1, `Number of tables to create`)
> ```

nit: inconsistent capitalization here in the flag descriptions

**Review by solongordon — APPROVED** [review]
Nice. `datumToGoSQL` is missing a few datum types, but I can add those in a follow-up PR (or add a commit here if you prefer.)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30430#-:-LMsBrwD5IV-UJHa4JFE:b2j7x2t)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by solongordon** [comment]
I finished up the random datum generation and fixed the lint issues. Will look into the test @danhhz suggested.

**Comment by jordanlewis** [comment]
Fixed some last bugs with array encoding - needed to make sure we didn't generate arrays with element types that aren't supported. @justinj or @solongordon can you take a quick look?

**Pull request merged**
