### PR TITLE
roachtest: loq recovery test, handle context timeouts

### LINKED ISSUE #91016: roachtest: loqrecovery/workload=movr/rangeSize=2mb failed
roachtest.loqrecovery/workload=movr/rangeSize=2mb [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/7225397?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/7225397?buildTab=artifacts#/loqrecovery/workload=movr/rangeSize=2mb) on release-22.2.0 @ [207058d86e0b30ee27866cdf7df923791e1adf55](https://github.com/cockroachdb/cockroach/commits/207058d86e0b30ee27866cdf7df923791e1adf55):

```
test artifacts and logs in: /artifacts/loqrecovery/workload=movr/rangeSize=2mb/run_1
	test_runner.go:1061,test_runner.go:960: test timed out (0s)
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #88112 roachtest: loqrecovery/workload=movr/rangeSize=2mb failed [C-test-failure O-roachtest O-robot T-kv branch-master]
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*loqrecovery/workload=movr/rangeSize=2mb.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-21074

### PR DESCRIPTION
**Pull request by aliher1911**
Previously test could hang on sql exec indefinitely if recovery didn't succeed despite having internal timeouts.
This PR changes db.Exec to db.ExecContext to handle test cancellations correctly.

Release note: None

Fixes #91016

### CODE REVIEW

**Comment by erikgrinaker** [comment]
This makes sense, but why does it fix the test failures?

**Comment by aliher1911** [comment]
Currently, if any post recovery processes fail to restart we send it as perf metric but don't fail test.
So in this case panic on node 5 should not cause test to fail but report success < 100%. But what was happening is that db.Exec was handing because it cluster was borked on system ranges after it was left with 2 ranges out of 5.
I will create a separate issue to tighten recovery. Just want to get Tobi's feedback on original issue first.

**Comment by erikgrinaker** [comment]
Got it, thanks.

**Review by erikgrinaker — APPROVED** [review]

**Pull request merged**
