### PR TITLE
opt: teach buildScan how to use inverted histograms

### LINKED ISSUE #48220: opt: use inverted index statistics in the optimizer
We currently do not use statistics on inverted indexes, which results in poor cardinality and cost estimation of inverted index scans and inverted zig zag joins. This issue covers the work needed to use the statistics in the optimizer. Collection of these statistics is covered by #48219.

To estimate the selectivity of a contains predicate (e.g., `x @> 5`), we would use the formula `(1/no. distinct keys) * (no. values in the index/no. of rows)`. If a histogram is available, we can use it to get a more accurate selectivity estimate.

As described in the [Geospatial RFC](#47762), improving statistics on inverted indexes will benefit the work we're doing for geospatial support, as well as for JSON and Array inverted index support.

### PR DESCRIPTION
**Pull request by madelynnblue**
Fixes #48220

Release note: None

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
Awesome! This is looking great. Just a few comments inline.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-:-MCHrrtd9dTQmE-kFwoY:btn0xcj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 761 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCHlr6U-h1qvZXAwItK:-MCHlr6U-h1qvZXAwItL:bcv3cf6) ([raw file](https://github.com/cockroachdb/cockroach/blob/33e96cc168c57247c27535d48ac350e4c3282e22/pkg/sql/opt/memo/statistics_builder.go#L761)):*
> ```Go
> 	// ----------------------------------------------------------------
> 	var constrainedCols, histCols opt.ColSet
> 	constrainedCols = scan.Cols.Copy()
> ```

I think this should only include the first column, since `InvertedConstraint` currently only applies to the inverted column. (probably doesn't affect correctness, but I think it's a bit clearer and it may  slightly affect performance).
___
*[pkg/sql/opt/memo/statistics_builder.go, line 773 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCHlZsd3YUUuE6fl8rW:-MCHlZseDV02e5tt32rm:b40rixa) ([raw file](https://github.com/cockroachdb/cockroach/blob/33e96cc168c57247c27535d48ac350e4c3282e22/pkg/sql/opt/memo/statistics_builder.go#L773)):*
> ```Go
> 
> 			inputStat, _ := sb.colStatFromInput(colSet, scan)
> 			if inputHist := inputStat.Histogram; inputHist != nil {
> ```

I think we should handle the case where we don't have a histogram on the indexed column (or `shouldUseHistogram` returned false). This would be rare, but it's always possible that the user disabled stats or disabled histograms.

To handle that case, you could do what we were doing before with `numUnappliedConjuncts += 2`
___
*[pkg/sql/opt/memo/statistics_builder.go, line 782 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCHnoSs4Kng3fMiT4my:-MCHnoSs4Kng3fMiT4mz:b-veziy1) ([raw file](https://github.com/cockroachdb/cockroach/blob/33e96cc168c57247c27535d48ac350e4c3282e22/pkg/sql/opt/memo/statistics_builder.go#L782)):*
> ```Go
> 		})
> 	}
> ```

I think you'll need to add `sb.updateNullCountsFromNotNullCols` here and `sb.selectivityFromNullsRemoved` below in case the original column had null values. 
___
*[pkg/sql/opt/memo/testdata/stats/inverted-geo, line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCHpERECR7vmGFgASfH:-MCHpERFCNlddBUkK4_5:b-wyk3m8) ([raw file](https://github.com/cockroachdb/cockroach/blob/33e96cc168c57247c27535d48ac350e4c3282e22/pkg/sql/opt/memo/testdata/stats/inverted-geo#L14)):*
> ```
>     "row_count": 7000,
>     "distinct_count": 7,
>     "null_count": 0,
> ```

would be good to add another test where null count is non-zero
___
*[pkg/sql/opt/memo/testdata/stats/inverted-geo, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCHq9Q_3-WKX8iRZfzt:-MCHq9Q_3-WKX8iRZfzu:bxtzfr7) ([raw file](https://github.com/cockroachdb/cockroach/blob/33e96cc168c57247c27535d48ac350e4c3282e22/pkg/sql/opt/memo/testdata/stats/inverted-geo#L88)):*
> ```
>  │         ├── ["\xfd\x10\x00\x00\x00\x00\x00\x00\x01", "\xfd\x12")
>  │         └── ["\xfd\x14\x00\x00\x00\x00\x00\x00\x00", "\xfd\x14\x00\x00\x00\x00\x00\x00\x00"]
>  │    2})
> ```

What is `2})` referring to? It appears again below....
___
*[pkg/sql/opt/memo/testdata/stats/inverted-geo, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCHpg5W5tp-o5g-S0hH:-MCHpg5X85W4hcAGS29C:b-4eqgse) ([raw file](https://github.com/cockroachdb/cockroach/blob/33e96cc168c57247c27535d48ac350e4c3282e22/pkg/sql/opt/memo/testdata/stats/inverted-geo#L104)):*
> ```
>  │         │         └── ["\xfd\x14\x00\x00\x00\x00\x00\x00\x00", "\xfd\x14\x00\x00\x00\x00\x00\x00\x00"]
>  │         │    2})
>  │         └── cost: 3150.02
> ```

This formatting looks a bit weird -- I don't think we should show the spans for the `memo` format.

I would just use the `opt` directive here instead, since it's easier to see which plan is chosen. Also, `opt` prints out the stats while `memo` does not. (You could also fix up the memo formatting to remove the spans and show both the `opt` and `memo` output).

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51439)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 761 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCHlr6U-h1qvZXAwItK:-MCJ_ikkC0Cf7pAB7QQz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/33e96cc168c57247c27535d48ac350e4c3282e22/pkg/sql/opt/memo/statistics_builder.go#L761)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think this should only include the first column, since `InvertedConstraint` currently only applies to the inverted column. (probably doesn't affect correctness, but I think it's a bit clearer and it may  slightly affect performance).
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 773 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCHlZsd3YUUuE6fl8rW:-MCJGNyO81DrCfdTZxxL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/33e96cc168c57247c27535d48ac350e4c3282e22/pkg/sql/opt/memo/statistics_builder.go#L773)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think we should handle the case where we don't have a histogram on the indexed column (or `shouldUseHistogram` returned false). This would be rare, but it's always possible that the user disabled stats or disabled histograms.

To handle that case, you could do what we were doing before with `numUnappliedConjuncts += 2`
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 782 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCHnoSs4Kng3fMiT4my:-MCJ_kTD7L3absrMaGBn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/33e96cc168c57247c27535d48ac350e4c3282e22/pkg/sql/opt/memo/statistics_builder.go#L782)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think you'll need to add `sb.updateNullCountsFromNotNullCols` here and `sb.selectivityFromNullsRemoved` below in case the original column had null values. 
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/testdata/stats/inverted-geo, line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCHpERECR7vmGFgASfH:-MCNgKfo8UDfUqJiKIpr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/33e96cc168c57247c27535d48ac350e4c3282e22/pkg/sql/opt/memo/testdata/stats/inverted-geo#L14)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

would be good to add another test where null count is non-zero
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/testdata/stats/inverted-geo, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCHq9Q_3-WKX8iRZfzt:-MCJq2apBJ0JrNzZJvon:b-o6u9pi) ([raw file](https://github.com/cockroachdb/cockroach/blob/33e96cc168c57247c27535d48ac350e4c3282e22/pkg/sql/opt/memo/testdata/stats/inverted-geo#L88)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

What is `2})` referring to? It appears again below....
</blockquote></details>

Fixed memo formatting
___
*[pkg/sql/opt/memo/testdata/stats/inverted-geo, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCHpg5W5tp-o5g-S0hH:-MCJbKIw4ydIXMahoHB-:bs2vtc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/33e96cc168c57247c27535d48ac350e4c3282e22/pkg/sql/opt/memo/testdata/stats/inverted-geo#L104)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This formatting looks a bit weird -- I don't think we should show the spans for the `memo` format.

I would just use the `opt` directive here instead, since it's easier to see which plan is chosen. Also, `opt` prints out the stats while `memo` does not. (You could also fix up the memo formatting to remove the spans and show both the `opt` and `memo` output).
</blockquote></details>

Now using both opt and memo since memo formatting is improved.

**Review by rytaft — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51439)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson and @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 785 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCSFl9P1nYqsIQns1EK:-MCSFl9P1nYqsIQns1EL:b-ce6gx9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99f3257f6df93c783b2abba0baeb9e48531d485/pkg/sql/opt/memo/statistics_builder.go#L785)):*
> ```Go
> 				}
> 			} else {
> 				numUnappliedConjuncts += 2
> ```

Would be good to include something similar to this comment from before here:
```
// ... just assume a single closed span such as ["\xfd", "\xfe").
// This corresponds to two "conjuncts" as defined in numConjunctsInConstraint.
```
___
*[pkg/sql/opt/memo/statistics_builder.go, line 788 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCSGHTrAcMtkMrQzLca:-MCSGHTrAcMtkMrQzLcb:b-xzys6p) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99f3257f6df93c783b2abba0baeb9e48531d485/pkg/sql/opt/memo/statistics_builder.go#L788)):*
> ```Go
> 			}
> 		})
> 	}
> ```

I'd also add this block here, too:
```
} else {
  numUnappliedConjuncts += 2
}
```
___
*[pkg/sql/opt/memo/testdata/stats/inverted-geo, line 264 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCSHBxwCoAqustzG8si:-MCSHBxwCoAqustzG8sj:bdxckok) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99f3257f6df93c783b2abba0baeb9e48531d485/pkg/sql/opt/memo/testdata/stats/inverted-geo#L264)):*
> ```
> # Inverted indexes don't contain NULL entries, so we expect a full scan.
> memo
> SELECT * FROM t WHERE g IS NULL OR ST_INTERSECTS('LINESTRING(100 100, 150 150)', g)
> ```

Can you add the opt output of this query too so we can see the stats? I think you should also repeat the same tests as above here so we can check that the null counts are correct.
___
*[pkg/sql/opt/xform/memo_format.go, line 285 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCSHhuJ0psaotYZi5ud:-MCSHhuJ0psaotYZi5ue:bkv48to) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99f3257f6df93c783b2abba0baeb9e48531d485/pkg/sql/opt/xform/memo_format.go#L285)):*
> ```Go
> 		}
> 		if t.InvertedConstraint != nil {
> 			fmt.Fprintf(mf.buf, ",invert constrained")
> ```

[nit] maybe "constrained inverted"? Not sure what sounds best...

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51439)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 785 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCSFl9P1nYqsIQns1EK:-MCdaTvLCqXNKTJ3C94S:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99f3257f6df93c783b2abba0baeb9e48531d485/pkg/sql/opt/memo/statistics_builder.go#L785)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Would be good to include something similar to this comment from before here:
```
// ... just assume a single closed span such as ["\xfd", "\xfe").
// This corresponds to two "conjuncts" as defined in numConjunctsInConstraint.
```

</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 788 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCSGHTrAcMtkMrQzLca:-MCdaYEn2_-x4tDB3eCG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99f3257f6df93c783b2abba0baeb9e48531d485/pkg/sql/opt/memo/statistics_builder.go#L788)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I'd also add this block here, too:
```
} else {
  numUnappliedConjuncts += 2
}
```
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/testdata/stats/inverted-geo, line 264 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCSHBxwCoAqustzG8si:-MCgG5NO0lkUsrwddhiL:b-sepiqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99f3257f6df93c783b2abba0baeb9e48531d485/pkg/sql/opt/memo/testdata/stats/inverted-geo#L264)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Can you add the opt output of this query too so we can see the stats? I think you should also repeat the same tests as above here so we can check that the null counts are correct.
</blockquote></details>

Added. They all seem to have a nullcount=0 so there must be something wrong? I added some stats for the PK column but that didn't appear to fix anything. Unsure what's the problem.
___
*[pkg/sql/opt/xform/memo_format.go, line 285 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCSHhuJ0psaotYZi5ud:-MCdav3R8dA78Ts-WITy:b1ss9b0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99f3257f6df93c783b2abba0baeb9e48531d485/pkg/sql/opt/xform/memo_format.go#L285)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] maybe "constrained inverted"? Not sure what sounds best...
</blockquote></details>

no idea either. they are all weird. changed.

**Review by rytaft — COMMENTED** [review]
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51439)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/sql/logictest/testdata/logic_test/inverted_filter_geospatial_explain_local, line 18 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCgbtiNEO9AP_stX--w:-MCgbsGrEwanrKr7Xp-4:be7zb3p) ([raw file](https://github.com/cockroachdb/cockroach/blob/82af5380eb4d3e1646548c1539cb0695d3572f8f/pkg/sql/logictest/testdata/logic_test/inverted_filter_geospatial_explain_local#L18)):*
> ```
> 
> query T
> SELECT url FROM [EXPLAIN (DISTSQL) SELECT k FROM geo_table2 WHERE ST_Intersects('POINT(3.0 3.0)'::geometry, geom)]
> ```

These tests are no longer testing what they intended to... see if you can inject stats to get it back to a plan using the inverted filterer.
___
*[pkg/sql/logictest/testdata/logic_test/inverted_index_geospatial, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCgcGI6E1Hp97PhgdKf:-MCgcGI6E1Hp97PhgdKg:b3kyqqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/82af5380eb4d3e1646548c1539cb0695d3572f8f/pkg/sql/logictest/testdata/logic_test/inverted_index_geospatial#L31)):*
> ```
> # the default index bounds.
> query T
> SELECT url FROM [EXPLAIN ANALYZE SELECT k FROM geo_table WHERE ST_Intersects('SRID=26918;POINT(400003 4000003)'::geometry, geom) ORDER BY k]
> ```

Same here -- see if you can get this plan to use an inverted filterer
___
*[pkg/sql/opt/exec/execbuilder/testdata/inverted_index, line 612 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCgcR-oDdjXnDP-YVFl:-MCgcR-oDdjXnDP-YVFm:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/82af5380eb4d3e1646548c1539cb0695d3572f8f/pkg/sql/opt/exec/execbuilder/testdata/inverted_index#L612)):*
> ```
> 
> query TTTTT
> EXPLAIN (VERBOSE) SELECT k FROM geo_table WHERE ST_Intersects('POINT(3.0 3.0)'::geometry, geom)
> ```

ditto
___
*[pkg/sql/opt/memo/statistics_builder.go, line 792 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCgcc7bAtwFLCN9A1qT:-MCgcc7bAtwFLCN9A1qU:bno254q) ([raw file](https://github.com/cockroachdb/cockroach/blob/82af5380eb4d3e1646548c1539cb0695d3572f8f/pkg/sql/opt/memo/statistics_builder.go#L792)):*
> ```Go
> 		})
> 	} else {
> 		numUnappliedConjuncts += 2
> ```

[nit] this could use a brief comment too
___
*[pkg/sql/opt/memo/testdata/stats/inverted-geo, line 264 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCSHBxwCoAqustzG8si:-MCgdjYm-3NkXdixYpcG:b-xg7kq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99f3257f6df93c783b2abba0baeb9e48531d485/pkg/sql/opt/memo/testdata/stats/inverted-geo#L264)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Added. They all seem to have a nullcount=0 so there must be something wrong? I added some stats for the PK column but that didn't appear to fix anything. Unsure what's the problem.
</blockquote></details>

I think it probably has to do with the fact that `i` is a primary key, so I'm guessing that we're using that fact to set the null count to 0 somewhere. Try removing the primary key designation in the `CREATE TABLE` statement and see if that fixes it.
___
*[pkg/sql/opt/memo/testdata/stats/inverted-geo, line 15 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCgcu8KEGnzjwFupn6O:-MCgcu8KEGnzjwFupn6P:bkhbtg) ([raw file](https://github.com/cockroachdb/cockroach/blob/82af5380eb4d3e1646548c1539cb0695d3572f8f/pkg/sql/opt/memo/testdata/stats/inverted-geo#L15)):*
> ```
>     "created_at": "2018-01-01 1:00:00.00000+00:00",
>     "row_count": 2000,
>     "distinct_count": 1000,
> ```

These stats don't make sense since `i` is the primary key -- distinct count always equals the row count for a key.
___
*[pkg/sql/opt/memo/testdata/stats/inverted-geo, line 239 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCgdC-K-0S2sCCUNCSm:-MCgdC-K-0S2sCCUNCSn:b-g7eesn) ([raw file](https://github.com/cockroachdb/cockroach/blob/82af5380eb4d3e1646548c1539cb0695d3572f8f/pkg/sql/opt/memo/testdata/stats/inverted-geo#L239)):*
> ```
>     "row_count": 2000,
>     "distinct_count": 1000,
>     "null_count": 50
> ```

same here -- a primary key shouldn't have null rows.
___
*[pkg/sql/opt/memo/testdata/stats/inverted-geo, line 277 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCgdLU4EH_mCsrZPbe2:-MCgdLU4EH_mCsrZPbe3:br7ikps) ([raw file](https://github.com/cockroachdb/cockroach/blob/82af5380eb4d3e1646548c1539cb0695d3572f8f/pkg/sql/opt/memo/testdata/stats/inverted-geo#L277)):*
> ```
> 
> # Inverted indexes don't contain NULL entries, so we expect a full scan.
> opt
> ```

Might be helpful to change this directive to `opt colstat=1 colstat=2` so we can see the column stats in the output.
___
*[pkg/sql/opt/memo/testdata/stats/inverted-geo, line 389 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCgeG7X73Z0YpiPalqO:-MCgeG7Y4z8jRZgbbRIp:b-4kei9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/82af5380eb4d3e1646548c1539cb0695d3572f8f/pkg/sql/opt/memo/testdata/stats/inverted-geo#L389)):*
> ```
>  │    │                   ├── inverted constraint: /2/1
>  │    │                   │    └── spans: ["\x87\xff", "\x87\xff"]
>  │    │                   ├── stats: [rows=100, distinct(1)=97.5, null(1)=0, distinct(2)=2, null(2)=100]
> ```

This null count for column 2 (`g`) is wrong -- it should be 0. I think you probably need to explicitly set the null count to 0 inside `invertedConstrainScan`. (This is happening since we've effectively combined the regular and inverted stats for `g` into a single stat. The inverted index doesn't actually have any nulls to begin with.)

I think this might be a problem for `selectivityFromHistograms` too, since it will incorrectly think the input has null values. You might be able to hack around this by waiting to update the null counts until *after* `selectivityFromHistograms` is called.

**Review by madelynnblue — COMMENTED** [review]
null counts fixed. RFAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-:-MChjZ2UCfhlxGrN_KFC:b-guuuzz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson and @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 792 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCgcc7bAtwFLCN9A1qT:-MChDy_R9fiWDPPcuUOe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/82af5380eb4d3e1646548c1539cb0695d3572f8f/pkg/sql/opt/memo/statistics_builder.go#L792)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] this could use a brief comment too
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/testdata/stats/inverted-geo, line 15 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCgcu8KEGnzjwFupn6O:-MChFuen-1hWKSAi7V9I:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/82af5380eb4d3e1646548c1539cb0695d3572f8f/pkg/sql/opt/memo/testdata/stats/inverted-geo#L15)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

These stats don't make sense since `i` is the primary key -- distinct count always equals the row count for a key.
</blockquote></details>

fixed

**Review by rytaft — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51439)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 814 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCiBD0j89AMlst2UrlB:-MCiBD0j89AMlst2UrlC:bems7ye) ([raw file](https://github.com/cockroachdb/cockroach/blob/25bc9fbeaeea4dfeff35fc83356b3dd98ad8c558/pkg/sql/opt/memo/statistics_builder.go#L814)):*
> ```Go
> 	constrainedCols.ForEach(func(col opt.ColumnID) {
> 		colSet := opt.MakeColSet(col)
> 		inputStat, _ := sb.colStatFromInput(colSet, scan)
> ```

I think you want to use `s.ColStats.Lookup(colSet)` here instead to get the `colStat` for the scan. As written, the code is updating the underlying stat for the table, which could lead to some unpredictable results depending on the order of exploration. In general we don't want parent expressions to update the stats for their input.

(If the `colStat` doesn't exist due to `shouldUseHistoram=false`, I wouldn't bother adding it -- I think it's fine if our null counts are off in that case since the row count estimate will already be very rough).

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51439)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson and @rytaft)

___
*[pkg/sql/logictest/testdata/logic_test/inverted_index_geospatial, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCgcGI6E1Hp97PhgdKf:-MCk7cLd8RJPYc2NlClv:b1lfa75) ([raw file](https://github.com/cockroachdb/cockroach/blob/82af5380eb4d3e1646548c1539cb0695d3572f8f/pkg/sql/logictest/testdata/logic_test/inverted_index_geospatial#L31)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Same here -- see if you can get this plan to use an inverted filterer
</blockquote></details>

These changes went away with the current version.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 814 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCiBD0j89AMlst2UrlB:-MCk7gJd7g6VdPNovI3J:b-j7y8l0) ([raw file](https://github.com/cockroachdb/cockroach/blob/25bc9fbeaeea4dfeff35fc83356b3dd98ad8c558/pkg/sql/opt/memo/statistics_builder.go#L814)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think you want to use `s.ColStats.Lookup(colSet)` here instead to get the `colStat` for the scan. As written, the code is updating the underlying stat for the table, which could lead to some unpredictable results depending on the order of exploration. In general we don't want parent expressions to update the stats for their input.

(If the `colStat` doesn't exist due to `shouldUseHistoram=false`, I wouldn't bother adding it -- I think it's fine if our null counts are off in that case since the row count estimate will already be very rough).

</blockquote></details>

Done. This made the scan null counts = 0, but the other null counts are now non-zero. Does that seem correct?

**Review by rytaft — COMMENTED** [review]
> Reviewed 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51439)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 814 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MCiBD0j89AMlst2UrlB:-MCl_MGSDOqi95pP3TtK:b119qba) ([raw file](https://github.com/cockroachdb/cockroach/blob/25bc9fbeaeea4dfeff35fc83356b3dd98ad8c558/pkg/sql/opt/memo/statistics_builder.go#L814)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Done. This made the scan null counts = 0, but the other null counts are now non-zero. Does that seem correct?
</blockquote></details>

Yea, that seems right since we haven't yet taught the logical props builder that `ST_Intersects` and friends are null-rejecting filters. 
___
*[pkg/sql/opt/memo/testdata/stats/inverted-geo, line 405 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/51439#-MClaLCAAFROoMN8zZiW:-MClaLCB2orQY7ULue-F:b38scvi) ([raw file](https://github.com/cockroachdb/cockroach/blob/1efeec61812ce90d5b3df65a808a3b9a8e9cc896/pkg/sql/opt/memo/testdata/stats/inverted-geo#L405)):*
> ```
>       │    │                   ├── inverted constraint: /2/3
>       │    │                   │    └── spans: ["\x87\xff", "\x87\xff"]
>       │    │                   ├── stats: [rows=100, distinct(2)=2, null(2)=0, distinct(3)=100, null(3)=0]
> ```

Hmm the estimated row count is still 100 here. Also, I would expect distinct(2) to be 1, not 2. I think this is happening because when `updateDistinctCountFromHistogram` is called, the null count is still non-zero.

I think having the combined stat is making these calculations overly difficult. Even if we don't want to change the underlying `system.table_statistics` schema yet, I think things would be significantly improved if we split the single combined stat into two when we use it in the `statisticsBuilder`. You could do this by adding an `Inverted` field to `props.ColumnStatistic`, and when we load the stats for a table in `statisticsBuilder.makeTableStatistics`, any stat on an inverted column would become two `colStats`: the non-inverted one would use the `RowCount`, `DistinctCount`, and `NullCount` from the original stat and ignore the histogram, and the inverted one would use the histogram and get the `RowCount` and `DistinctCount` by calling `ValuesCount()` and `DistinctValuesCount()` on the histogram. `NullCount` for the inverted stat would always be 0.

Let me know what you think. You might be able to get it to work without this change, but I think it would require a lot of hacks.

**Pull request closed without merging**
