### PR TITLE
sqlccl: check privileges in BACKUP/RESTORE

### PR DESCRIPTION
**Pull request by dt**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14009)

### CODE REVIEW

**Comment by knz** [comment]
:lgtm: with nits

---

Reviewed 13 of 13 files at r1, 1 of 1 files at r2, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/ccl/sqlccl/backup.go, line 781 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14009#-Kencay9xm3tSz7Dunsd:-KencayAe1lyYNEW7459:bs7e0rl) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a458fdc3adc916ed1c314137d942702ad75584/pkg/ccl/sqlccl/backup.go#L781)):*
> ```Go
> 	// Fail fast if the necessary databases don't exist since the below logic
> 	// leaks table IDs when Restore fails.
> 	if err := p.ExecCfg().DB.Txn(ctx, func(txn *client.Txn) error {
> ```

I'd suggest aliasing `p.ExecCfg().DB` into a local variable.

---

*[pkg/ccl/sqlccl/backup.go, line 891 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14009#-KenckDrBh--Y80MYhD7:-KenckDrBh--Y80MYhD8:b-553mgx) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a458fdc3adc916ed1c314137d942702ad75584/pkg/ccl/sqlccl/backup.go#L891)):*
> ```Go
> 		return nil, nil, err
> 	}
> 	if err := p.RequireSuperUser("BACKUP"); err != nil {
> ```

Design question: why not making backup/restore a separate privilege that can be granted to non-admin users?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14009#-:-KencytDkbCGLo5g1FvS:bfmeux1)*

**Comment by dt** [comment]
Review status: 18 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/ccl/sqlccl/backup.go, line 781 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14009#-Kencay9xm3tSz7Dunsd:-KenlDVzJMg08HwEHzbK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a458fdc3adc916ed1c314137d942702ad75584/pkg/ccl/sqlccl/backup.go#L781)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I'd suggest aliasing `p.ExecCfg().DB` into a local variable.
</blockquote></details>

Done.

---

*[pkg/ccl/sqlccl/backup.go, line 891 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14009#-KenckDrBh--Y80MYhD7:-KenkoHVvzFPIku85TTd:b-l26fjs) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a458fdc3adc916ed1c314137d942702ad75584/pkg/ccl/sqlccl/backup.go#L891)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Design question: why not making backup/restore a separate privilege that can be granted to non-admin users?
</blockquote></details>

backup/restore allows access to the node's local filesystem, thus the root-only requirement.

We could potentially make it more granular: if the backup/restore location is cloud-only, we could require only SELECT/CREATE, but for now this feels like a safe, conservative default.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14009)*

**Comment by knz** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/ccl/sqlccl/backup.go, line 891 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14009#-KenckDrBh--Y80MYhD7:-Kenu2XAoS4es6wojprT:bb6mt9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a458fdc3adc916ed1c314137d942702ad75584/pkg/ccl/sqlccl/backup.go#L891)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

backup/restore allows access to the node's local filesystem, thus the root-only requirement.

We could potentially make it more granular: if the backup/restore location is cloud-only, we could require only SELECT/CREATE, but for now this feels like a safe, conservative default.
</blockquote></details>

:+1:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14009)*

**Comment by dt** [comment]
for the docs: BACKUP and RESTORE both require root user. BACKUP requires SELECT privilege (which root always has) on each table and DB backed up, RESTORE requires CREATE priv on the db into which tables are restored.

**Comment by benesch** [comment]
Only root should be able to `CREATE DATABASE` IIRC, which means there's one more place that can use RequireSuperUser, no?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14009#-:-KenxwrKXRBVrT6luN0L:b-7sz512)*

**Comment by benesch** [comment]
*[pkg/sql/planhook.go, line 41 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14009#-KenxN_seYPiFlz1nABQ:-KenxN_seYPiFlz1nABR:b-qx078t) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c938a4e69dc75d5e204af81a30148d01c4d29f4/pkg/sql/planhook.go#L41)):*
> ```Go
> // PlanHookState exposes the internal planner state needed by plan hooks. This
> // state is passed in this struct, rather than directly to hook functions, to
> // avoid rewiring every hook function when more state needs to be exported.
> ```

Would you mind to update this comment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14009)*

**Comment by tamird** [comment]
Indeed, create.go:

```
	if p.session.User != security.RootUser {
		return nil, fmt.Errorf("only %s is allowed to create databases", security.RootUser)
	}
```

---

Reviewed 13 of 13 files at r1, 1 of 1 files at r2, 4 of 5 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/sqlccl/backup_test.go, line 793 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14009#-Keo-V3Y3TgLrksNVxTh:-Keo-V3Zt5h-0ZMuFdmu:b-uf4w2o) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c938a4e69dc75d5e204af81a30148d01c4d29f4/pkg/ccl/sqlccl/backup_test.go#L793)):*
> ```Go
> 
> 	t.Run("root-only", func(t *testing.T) {
> 		_, err = testuser.Exec(backupStmt)
> ```

throughout: this should be `err :=`

---

*[pkg/ccl/sqlccl/backup_test.go, line 806 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14009#-Keo-skn6ns6mtj9pvll:-Keo-skn6ns6mtj9pvlm:b-t4d2ve) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c938a4e69dc75d5e204af81a30148d01c4d29f4/pkg/ccl/sqlccl/backup_test.go#L806)):*
> ```Go
> 		sqlDB.Exec(backupStmt)
> 		_, err = sqlDB.DB.Exec(
> 			fmt.Sprintf(`RESTORE bench.bank FROM '%s' WITH OPTIONS ('into_db'='system')`, dir),
> ```

does passing the `dir` actually matter here? this permission validation doesn't seem to require a backup to be written.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14009#-:-Kenzx-3VK1Faa3pwlXS:b-uont26)*

**Comment by dt** [comment]
Done
#14028

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/sqlccl/backup_test.go, line 793 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14009#-Keo-V3Y3TgLrksNVxTh:-Keo1hFQU6SGUyaVySkk:bvwemsz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c938a4e69dc75d5e204af81a30148d01c4d29f4/pkg/ccl/sqlccl/backup_test.go#L793)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

throughout: this should be `err :=`
</blockquote></details>

Done.
#14028

---

*[pkg/ccl/sqlccl/backup_test.go, line 806 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14009#-Keo-skn6ns6mtj9pvll:-Keo0ZUC1-99ruf1XXE4:b5r6mfj) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c938a4e69dc75d5e204af81a30148d01c4d29f4/pkg/ccl/sqlccl/backup_test.go#L806)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

does passing the `dir` actually matter here? this permission validation doesn't seem to require a backup to be written.
</blockquote></details>

yes, reading the descriptors from the backup happens before assigning their parents, which happens before checking privs on assigned parents.

---

*[pkg/sql/planhook.go, line 41 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14009#-KenxN_seYPiFlz1nABQ:-Keo99FyLPKtSomMdTU6:bbm9yet) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c938a4e69dc75d5e204af81a30148d01c4d29f4/pkg/sql/planhook.go#L41)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Would you mind to update this comment?
</blockquote></details>

#14028

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14009#-:-Keo95mzgwcfReXHmoiA:bdz9037)*

**Pull request merged**
