### PR TITLE
roachpb: change TxnMeta.ID to a real UUID type

### LINKED ISSUE #4230: util/uuid: consider removing in favor of github.com/satori/go.uuid
Not sure if we need any of the extra functionality.

### PR DESCRIPTION
**Pull request by tamird**
Blocked on gogo/protobuf#146.

Fixes #4230.
Closes #4318.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4327)

### CODE REVIEW

**Comment by tschottdorf** [comment]
Should squash before merge unless the previous commit passes all tests.
LGTM with some qs

---

Reviewed 32 of 32 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[kv/txn_coord_sender.go, line 508 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4327#-KAGbGxrWAtAFlDTiUVt:-KAGbGxrWAtAFlDTiUVu:-1810253720) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc7ef92063c3c8be3291c48ae54df3b3d263e971/kv/txn_coord_sender.go#L508)):*
Good News Everyone! Now that you use a fixed-width slice, I think you should be able to hash the thing directly and avoid string conversions: https://play.golang.org/p/M2B8XDOvi4

---

*[storage/sequence_cache.go, line 69 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4327#-KAGc0z_EEsxepcofz2-:-KAGc0z_EEsxepcofz20:-285352238) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc7ef92063c3c8be3291c48ae54df3b3d263e971/storage/sequence_cache.go#L69)):*
one-liner with some variation of bytes.Repeat() looks preferable. Why this change?

---

*[util/uuid/uuid.go, line 26 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4327#-KAGcRVWcPz_URutNZlB:-KAGcRVWcPz_URutNZlC:-160422152) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc7ef92063c3c8be3291c48ae54df3b3d263e971/util/uuid/uuid.go#L26)):*
Why not `type UUID uuid.UUID`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4327#-:-KAGctG5Jhez9LYA7htJ:1215821302)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[kv/txn_coord_sender.go, line 508 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4327#-KAGbGxrWAtAFlDTiUVt:-KAGiE_nG2u226rel2Ak:-920172155) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc7ef92063c3c8be3291c48ae54df3b3d263e971/kv/txn_coord_sender.go#L508)):*
WIll do (but haven't yet).

---

*[storage/sequence_cache.go, line 69 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4327#-KAGc0z_EEsxepcofz2-:-KAGi6kNRMkR7rwctjKC:1287632182) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc7ef92063c3c8be3291c48ae54df3b3d263e971/storage/sequence_cache.go#L69)):*
Because that variant requires using `FromBytes` which has an error return.

---

*[util/uuid/uuid.go, line 26 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4327#-KAGcRVWcPz_URutNZlB:-KAGiCLI4vsO9lQkPUVx:203916987) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc7ef92063c3c8be3291c48ae54df3b3d263e971/util/uuid/uuid.go#L26)):*
Because methods.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4327)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[util/uuid/uuid.go, line 26 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4327#-KAGcRVWcPz_URutNZlB:-KAGlSZRvFsenDvIeFZa:-278029394) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc7ef92063c3c8be3291c48ae54df3b3d263e971/util/uuid/uuid.go#L26)):*
What's wrong with this: https://play.golang.org/p/7huSsQh_Sq
Btw, how is `type UUID struct { uuid.UUID }` laid out in memory? Just the same as my suggestion or is there overhead?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4327)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[util/uuid/uuid.go, line 26 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4327#-KAGcRVWcPz_URutNZlB:-KAGtn68rf58WZ3LyJl_:977558348) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc7ef92063c3c8be3291c48ae54df3b3d263e971/util/uuid/uuid.go#L26)):*
Nothing's wrong with that, but it requires me to write wrapper methods?

I don't know if there's overhead, @petermattis can probably answer this one better than I can.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4327)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[util/uuid/uuid.go, line 26 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4327#-KAGcRVWcPz_URutNZlB:-KAGuLVDiEa8WLiPhCG9:1425304534) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc7ef92063c3c8be3291c48ae54df3b3d263e971/util/uuid/uuid.go#L26)):*
AFAIK, the memory layout of `type UUID struct { uuid.UUID }` is the same as the memory layout of `util.UUID`. There is no overhead. The reason for using the struct is that you get to "inherit" the methods on `util.UUID` which you lose with `type UUID util.UUID`. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4327)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[util/uuid/uuid.go, line 26 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4327#-KAGcRVWcPz_URutNZlB:-KAGv1ZtwuB2Hwmjyiz2:-1402452590) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc7ef92063c3c8be3291c48ae54df3b3d263e971/util/uuid/uuid.go#L26)):*
Ok, didn't know there was no overhead. TIL and LGTM

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4327)*

**Comment by petermattis** [comment]
LGTM

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[kv/txn_coord_sender.go, line 508 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4327#-KAGbGxrWAtAFlDTiUVt:-KAGzlg37LsU8CblD-Wy:1760615676) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc7ef92063c3c8be3291c48ae54df3b3d263e971/kv/txn_coord_sender.go#L508)):*
`s/a fixed-width slice/an array/g`

---

*[util/uuid/uuid.go, line 53 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4327#-KAH-OCC8LtezcKA114o:-KAH-OCDSamE8RWmRlp-:1066089323) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc7ef92063c3c8be3291c48ae54df3b3d263e971/util/uuid/uuid.go#L53)):*
I'm surprised this is necessary. Can't you just compare the structs/arrays directly.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4327#-:-KAH-WDbILkrO7yp7qdJ:676834233)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[util/uuid/uuid.go, line 53 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4327#-KAH-OCC8LtezcKA114o:-KAH0-5BKKFepfzJ_V48:931302474) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc7ef92063c3c8be3291c48ae54df3b3d263e971/util/uuid/uuid.go#L53)):*
Hey, what do you know. Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4327)*

**Comment by tamird** [comment]
Review status: 16 of 34 files reviewed at latest revision, 3 unresolved discussions.

---

*[kv/txn_coord_sender.go, line 508 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4327#-KAGbGxrWAtAFlDTiUVt:-KAH8Yrs_mLFgiAa1BG5:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc7ef92063c3c8be3291c48ae54df3b3d263e971/kv/txn_coord_sender.go#L508)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4327)*

**Comment by tschottdorf** [comment]
LGTM

---

Reviewed 18 of 18 files at r3, 9 of 9 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[util/uuid/uuid.go, line 50 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4327#-KAHhA4S2GnGBUkEExVP:-KAHhA4TqY8t-IJONSkf:-1376059219) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bcfa42782849331a2b05c7decb44d28e4ed55ba/util/uuid/uuid.go#L50)):*
s/D/d/ and why all the excitement (`!`)?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4327#-:-KAHhMTWkEgt9sHlKtQU:676834233)*

**Comment by tschottdorf** [comment]
LGTM

**Pull request merged**
