### PR TITLE
cli/sql: improve debuggability

### LINKED ISSUE #31565: cli: smart_prompt test has been left over
The `smart_prompt` shell option is no longer a thing, and yet we have a test that appears to exercise it. Don't know how it's passing or whether it should be replaced with something else.
https://github.com/cockroachdb/cockroach/blob/fc6570dadbe71f5d8aed3bb6a14f37e186965213/pkg/cli/interactive_tests/test_multiline_statements.tcl#L78

### LINKED ISSUE #31567: cli: I want a way to tell the shell to not run the extra statements
It used to be that, when the old `smart_prompt` shell option was `\unset`, the shell would not send requests like `SHOW TRANSACTION STATUS` and `SHOW database` (and also `SHOW SYNTAX`, but this one has gotten its own option to disable in the meantime). 
This was quite nice, as any extra statement is a bummer when you're playing with tracing or automatic retries.
The new way to customize the prompt does not seem to have this effect; even if the respective placeholders are taken out of the prompt, the statements are still run.

I'm looking at the statement run with `set cluster setting sql.trace.session_eventlog.enabled=true;` and then the `/debug/events` page.

As an extra, the `SHOW TRANSACTION STATUS` statement seems to be run **twice** per real statement with the default prompt, but only once with `\set prompt1 nada>`.

### PR DESCRIPTION
**Pull request by knz**
Thanks Andrei for putting this on the radar.
Fixes  #31565.
Fixes  #31567.

### CODE REVIEW

**Review by andreimatei — APPROVED** [review]
LGTM thanks for doing this!


One question: why does `--debug-sql-cli` imply `--echo-sql`? `--echo-sql` is about printing the statements that the prompt sends transparently, right? But when `--debug-sql-cli` is enabled, there should be no such statements I think.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31630#-:-LPRf6D7CZsiqFN1FAtO:bx3xhkr)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/sql.go, line 341 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31630#-LPReO6RC8tHVVQrSyQ5:-LPReO6RC8tHVVQrSyQ6:b4btgf9) ([raw file](https://github.com/cockroachdb/cockroach/blob/40a09e77df21271830982eb4a8839bce0bcd3333/pkg/cli/sql.go#L341)):*
> ```Go
> 	},
> 	`smart_prompt`: {
> 		"detect open transactions and propose entering multi-line statements",
> ```

i'd suggest using named fields for these struct initializers (starting with this one, you don't need to boil the ocean)

**Review by andreimatei — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31630)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/cliflags/flags.go, line 269 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31630#-LPRfjXQ5N74eTs3TSRM:-LPRfjXQ5N74eTs3TSRN:b2zrj9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/13a64dcf82db200fc7855758c3a4160a08dea47d/pkg/cli/cliflags/flags.go#L269)):*
> ```Go
> 		Description: `
> Simplify the SQL CLI to ease troubleshooting of CockroachDB
> issues. This echoes sent SQL, disables the db-sensitive prompt, and
> ```

I'm not sure what "disables the db-sensitive prompt" means. Consider rephrasing.

**Review by knz — COMMENTED** [review]
> why does --debug-sql-cli imply --echo-sql?

The shell may change the syntax of the input by the user in subtle ways. Also if an input is spanning multiple lines, it must become clear what exactly is sent to the server. this flag reveals that.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31630#-:-LPVpqdc1BObcDH6PmGx:b780j4y)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/sql.go, line 341 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31630#-LPReO6RC8tHVVQrSyQ5:-LPVpdWE5Ix4dD2wgcF8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/40a09e77df21271830982eb4a8839bce0bcd3333/pkg/cli/sql.go#L341)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

i'd suggest using named fields for these struct initializers (starting with this one, you don't need to boil the ocean)
</blockquote></details>

Done.
___
*[pkg/cli/cliflags/flags.go, line 269 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31630#-LPRfjXQ5N74eTs3TSRM:-LPVpp3h2-O5uD0lb1M6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/13a64dcf82db200fc7855758c3a4160a08dea47d/pkg/cli/cliflags/flags.go#L269)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'm not sure what "disables the db-sensitive prompt" means. Consider rephrasing.
</blockquote></details>

Done.

**Pull request merged**
