### PR TITLE
cli/sql.go: update docs link to more helpful destination

### PR DESCRIPTION
**Pull request by ghost**
I'm totally new to this project and have spent a long time already trying to describe a table. I tried postgres' syntax `\d` and got an error hinting "try `\?`"

The output of `\?` includes this hint:
```
More documentation about our SQL dialect is available online:
http://www.cockroachlabs.com/docs/
```

However, that URL requires two additional drill down clicks to actually get to docs about your sql dialect.

This PR points this hint directly at the overview of Cockroach's sql dialect.

### CODE REVIEW

**Comment by spencerkimball** [comment]
Thanks for the PR @therealplato.

+cc @knz @jseldess: have we considered a mechanism that renders our SQL documentation as a generated `.go` file that could be read and displayed in our shell to provide up-to-date documentation without requiring browsing externally?

**Comment by jseldess** [comment]
That's an interesting idea. Let's explore. In the meantime, though, that in-CLI docs link should definitely be more direct. I'll look into that.

**Review by jseldess — APPROVED** [review]

**Comment by knz** [comment]
@therealplato thank you for your contribution!! Do you want to extend the message further and also add a link to the CLI shell's documentation next to the link you already have? Something like:
```
More documentation about our SQL dialect and the CLI shell is available online:
http://www.cockroachlabs.com/docs/sql-statements.html
https://www.cockroachlabs.com/docs/use-the-built-in-sql-client.html
```

@spencerkimball sounds cool. Note that I had a PR to provide inline help already ( #13540 ) but the bikeshed discussion drowned it. I would absolutely want to do more of this, even possibly rendering our doc HTML as embeddable ASCII, but there are two obstacles:

1. our docs currently contain HTML garbaged mixed with the markup, which makes for polluted ASCII rendering that needs to be manually hand-edited to clean up. The solution for this would be to use a different markup language that cleanly exports to plain ASCII (markdown is not one of them)
2. we have some religious commitment going on for SVG/graphical diagrams for the supported SQL syntax. I would like, like pg docs do, to use plain text grammar summaries instead (this is the approach suggested in #13540 btw) but that was shot down. I'm not sure where to go from here.
```

**Comment by petermattis** [comment]
@knz Providing help in the SQL shell would be nice. My issue with #13540 was that the help was tied to tab-completion which seemed surprising. I wonder if we can rework that PR to use a different mechanism for accessing builtin help.

**Comment by knz** [comment]
Thank you!

**Comment by therealplato** [comment]
I've never seen the SVG command syntax branches before this project and I think they're amazing. It's quite clear that if I add `IF NOT EXISTS` to my `CREATE INDEX` then I must also include an index name.

I see no reason why you can't bake the positioning, arrows and text of the svg's into ascii for manpages and other terminal use

**Comment by knz** [comment]
@therealplato oh so you know how to achieve this already? Can you explain this to us?

**Comment by therealplato** [comment]
i haven't done it, i haven't looked or found a tool to do it, but svg's are just textual entities that contain all the relevant information about positioning and content. it stands to reason that you can programmatically extract that information and render it as ascii art

**Comment by petermattis** [comment]
We generate the svgs. Might be easier to generate ascii versions as well. I
bet something fancy could be done with Unicode characters.

**Pull request merged**
