### PR TITLE
sql/logic: deflake upsert test for `generated as identity` column

### LINKED ISSUE #93297: sql: flake in TestTenantLogic_upsert
Seen on [this](https://teamcity.cockroachdb.com/viewLog.html?buildId=7890825&buildTypeId=Cockroach_UnitTests_BazelUnitTests) bors run
```
Failed
=== RUN   TestTenantLogic_upsert/generated_as_identity
[21:16:09] --- progress: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/6370/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/logictestccl/tests/3node-tenant/3node-tenant_test_/3node-tenant_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/upsert: 275 statements
    logic.go:2867: 
         
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/6370/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/logictestccl/tests/3node-tenant/3node-tenant_test_/3node-tenant_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/upsert:1321: SELECT * FROM generated_as_id_t ORDER BY a
        expected:
            1  1  1
            2  2  2
            3  3  3
            
        but found (query options: "rowsort" -> ignore the following ordering of rows) :
            1  4  4
            2  5  5
            3  6  6
```

Jira issue: CRDB-22261

### PR DESCRIPTION
**Pull request by ZhouXing19**
See [this flake in teamcity.](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/8230155?showRootCauses=true&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true)

fixes #93297

Epic: none

Release note: None

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
nice idea!

**Comment by ZhouXing19** [comment]
TFTR!
bors r=rafiss

**Pull request merged**
