### PR TITLE
sql,kv: add compact_engine_span for internal use

### PR DESCRIPTION
**Pull request by sumeerbhola**
This sql builtin can be used to compact the key span for a
running node, given the (nodeID, storeID, start_key, end_key).

Informs #26068

Release note: None

### CODE REVIEW

**Review by tbg — COMMENTED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57709)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/kv/kvserver/api.proto, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-MO6nE2oCEFC_1gyeEPd:-MO6nE2oCEFC_1gyeEPe:b-vbsfuh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8a211039d754122ec5adcfa8e88b5cab8639c76/pkg/kv/kvserver/api.proto#L83)):*
> ```protobuf
> message CompactEngineSpanRequest {
>   StoreRequestHeader header = 1 [(gogoproto.nullable) = false, (gogoproto.embed) = true];
>   roachpb.Span span = 2 [(gogoproto.nullable) = false, (gogoproto.embed) = true];
> ```

I don't think this should be embedded, as it makes the methods of `Span` available on `CompactEngineSpanRequest`. We typically only embed the headers in these requests.
___
*[pkg/sql/planner.go, line 725 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-MO6oIUn9rWYJE3vSV9I:-MO6oIUn9rWYJE3vSV9J:b-dohw1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8a211039d754122ec5adcfa8e88b5cab8639c76/pkg/sql/planner.go#L725)):*
> ```Go
> 	ctx context.Context, nodeID int32, storeID int32, rangeID int64,
> ) error {
> 	conn, err := p.execCfg.DistSender.NodeDialer().Dial(ctx, roachpb.NodeID(nodeID), rpc.DefaultClass)
> ```

```go
	if !p.ExecCfg().Codec.ForSystemTenant() {
		return errorutil.UnsupportedWithMultiTenancy(errorutil.FeatureNotAvailableToNonSystemTenantsIssue)
	}
```

The RPC would fail, but this returns a better error.
___
*[pkg/sql/planner.go, line 736 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-MO6oeqQ5oIj2RbEWfIN:-MO6oeqQ5oIj2RbEWfIO:b9r6cuf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8a211039d754122ec5adcfa8e88b5cab8639c76/pkg/sql/planner.go#L736)):*
> ```Go
> 		},
> 		Span: roachpb.Span{
> 			// TODO: ask about conversion from RangeID to the span. We need
> ```

I think this is really a question from someone from #sql-execution. You (or something you call) has to perform a meta2 scan to pick out the right range descriptor but this is a builtin; I don't know if it gets to do any of that stuff (we have a distSender so we could do it all manually, but that seems wrong). Ask them about what your options are, but my intuition is that the right thing to do is to take a start and end key in `compact_engine_span` and to call it via

```sql
select crdb_internal.compact_engine_span(1 /* nodeID */, 2 /* storeID */, start_key::string, end_key::string) from crdb_internal.ranges_no_leases where range_id = 37;
```

You could similary target all nodes by deriving the nodeID and storeID from `crdb_internal.kv_store_status.{node_id,store_id}` to, for example, target all stores in the cluster.

It would be nice to wrap the above expression into a short-hand again, but I don't know if we have the facilities for that. Again, a good question for #sql-execution, but even if we don't, the above is good enough to be pasted into a run book.
___
*[pkg/sql/sem/builtins/builtins.go, line 4545 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-MO6roTdDDrcbpSLGDfP:-MO6roTdDDrcbpSLGDfQ:b-izcpss) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8a211039d754122ec5adcfa8e88b5cab8639c76/pkg/sql/sem/builtins/builtins.go#L4545)):*
> ```Go
> 				return tree.DBoolTrue, nil
> 			},
> 			Info:       "This function is used only by CockroachDB's developers for restoring engine health.",
> ```

Still give this a real description. After all, internal users like documentation, too.

**Review by sumeerbhola — COMMENTED** [review]
TFTR!
I've addressed the comments.

Regarding tests:
- I've added sql logictests.
- I've registered the server in `client_test.go`. I couldn't find a test for `CollectChecksum`, so didn't have a pattern to follow. Should I be using `multiTestConfig.nodeDialer`like `TestStoreRangeWaitForApplication` does, or is the logictest sufficient since it exercises the end-to-end path?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-:-MOHPSTS4YbvoAWBQZ7A:b-1gsgoy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @tbg)

___
*[pkg/kv/kvserver/api.proto, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-MO6nE2oCEFC_1gyeEPd:-MOHEE5d0XxgFNCFv57t:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8a211039d754122ec5adcfa8e88b5cab8639c76/pkg/kv/kvserver/api.proto#L83)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I don't think this should be embedded, as it makes the methods of `Span` available on `CompactEngineSpanRequest`. We typically only embed the headers in these requests.
</blockquote></details>

Done
___
*[pkg/sql/planner.go, line 725 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-MO6oIUn9rWYJE3vSV9I:-MOHEkwN-oQWoGHR2L-p:b6zy933) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8a211039d754122ec5adcfa8e88b5cab8639c76/pkg/sql/planner.go#L725)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

```go
	if !p.ExecCfg().Codec.ForSystemTenant() {
		return errorutil.UnsupportedWithMultiTenancy(errorutil.FeatureNotAvailableToNonSystemTenantsIssue)
	}
```

The RPC would fail, but this returns a better error.
</blockquote></details>

Done. I noticed there are two `ExecutorConfig` objects I can get to: `planner.execCfg` and `planner.extendedEvalCtx.ExecCfg` -- the latter is returned by `planner.ExecCfg()`. Do you know the difference?
___
*[pkg/sql/planner.go, line 736 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-MO6oeqQ5oIj2RbEWfIN:-MO9MDJo9PohwcvrvJlJ:bqwmli7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8a211039d754122ec5adcfa8e88b5cab8639c76/pkg/sql/planner.go#L736)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I think this is really a question from someone from #sql-execution. You (or something you call) has to perform a meta2 scan to pick out the right range descriptor but this is a builtin; I don't know if it gets to do any of that stuff (we have a distSender so we could do it all manually, but that seems wrong). Ask them about what your options are, but my intuition is that the right thing to do is to take a start and end key in `compact_engine_span` and to call it via

```sql
select crdb_internal.compact_engine_span(1 /* nodeID */, 2 /* storeID */, start_key::string, end_key::string) from crdb_internal.ranges_no_leases where range_id = 37;
```

You could similary target all nodes by deriving the nodeID and storeID from `crdb_internal.kv_store_status.{node_id,store_id}` to, for example, target all stores in the cluster.

It would be nice to wrap the above expression into a short-hand again, but I don't know if we have the facilities for that. Again, a good question for #sql-execution, but even if we don't, the above is good enough to be pasted into a run book.
</blockquote></details>

Using `crdb_internal.ranges_no_leases` is perfect.
___
*[pkg/sql/sem/builtins/builtins.go, line 4545 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-MO6roTdDDrcbpSLGDfP:-MOHKG9l08egKtpz0CVA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8a211039d754122ec5adcfa8e88b5cab8639c76/pkg/sql/sem/builtins/builtins.go#L4545)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Still give this a real description. After all, internal users like documentation, too.
</blockquote></details>

Done.

**Review by tbg — COMMENTED** [review]
I think the logic tests do a good enough job at verifying that the plumbing works (that's pretty much all they do).
We don't want to write new tests using multiTestContext (it's a relic that's unfortunately proven hard to get rid of). Really the only additional thing that I could see you test is whether calling into the server with a compaction request actually does trigger the compaction. This seems hard to do above the pebble level unless we're fine with a mostly tautological test - you could add a testing knob that intercepts the inputs to `CompactEngineSpan` before calling `CompactEngine` and it could at least check that the key spans don't get mangled (when called from SQL). I don't know if that's worth it, once we get rid of the hex encoding.

> Reviewed 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-:-MOaj9DrEmE9x4V_dZsF:b-n2qum9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @sumeerbhola, and @tbg)

___
*[pkg/sql/planner.go, line 725 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-MO6oIUn9rWYJE3vSV9I:-MOahLbPDYrGGBNTm8XL:biy1ovn) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8a211039d754122ec5adcfa8e88b5cab8639c76/pkg/sql/planner.go#L725)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Done. I noticed there are two `ExecutorConfig` objects I can get to: `planner.execCfg` and `planner.extendedEvalCtx.ExecCfg` -- the latter is returned by `planner.ExecCfg()`. Do you know the difference?
</blockquote></details>

I'm not sure, you'd have to ask someone from SQL. I think using `p.ExecCfg()` is likely to give you the right one but it can't hurt to ask for a clarifying comment on the fields if there aren't any yet.
___
*[pkg/sql/logictest/testdata/logic_test/crdb_internal, line 647 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-MOahpXr2fbU_zp4YRlL:-MOahpXr2fbU_zp4YRlM:b-9fcrda) ([raw file](https://github.com/cockroachdb/cockroach/blob/cca8405d6a65047eded7b97264a287fe64852bf4/pkg/sql/logictest/testdata/logic_test/crdb_internal#L647)):*
> ```
> query TTB colnames
> SELECT start_pretty, end_pretty,
>  crdb_internal.compact_engine_span(1, 1, to_hex(start_key), to_hex(end_key))
> ```

would need to change if the hex stuff went away.
___
*[pkg/sql/sem/builtins/builtins.go, line 4542 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-MOai85Y-srapIpkpWCU:-MOai85Y-srapIpkpWCV:b-5sf1xx) ([raw file](https://github.com/cockroachdb/cockroach/blob/cca8405d6a65047eded7b97264a287fe64852bf4/pkg/sql/sem/builtins/builtins.go#L4542)):*
> ```Go
> 				nodeID := int32(tree.MustBeDInt(args[0]))
> 				storeID := int32(tree.MustBeDInt(args[1]))
> 				startKey, err := hex.DecodeString(string(tree.MustBeDString(args[2])))
> ```

Rather than baking the hex encoding in here, the caller could use the `decode` builtin if they wished to specify the inputs in hex, or even just use the `\x` encoding (https://www.postgresql.org/docs/9.1/datatype-binary.html).
I don't have any particular rule to point to to justify this, but I think the method should take the data in the representation that is most natural to it, and a "string that will be assumed to be hex encoded" doesn't seem to qualify, especially since we assume that the keys are mostly provided by `crdb_internal.ranges_no_leases`.
___
*[pkg/sql/sem/builtins/builtins.go, line 4560 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-MOaiu5wAm5RyI3rZLmD:-MOaiu5wAm5RyI3rZLmE:b4xbtt0) ([raw file](https://github.com/cockroachdb/cockroach/blob/cca8405d6a65047eded7b97264a287fe64852bf4/pkg/sql/sem/builtins/builtins.go#L4560)):*
> ```Go
> 				"end keys are hex encoded. To get the start and end keys for a particular rangeID, one " +
> 				"can do: SELECT to_hex(start_key), to_hex(end_key) FROM crdb_internal.ranges_no_leases " +
> 				"WHERE range_id=<value>. The compaction is run synchronously, so this function may take " +
> ```

Would need an update if hex stuff were to go away.
___
*[pkg/sql/sem/tree/eval.go, line 3070 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-MOaj-as9oGFRTzig3f5:-MOaj-as9oGFRTzig3f6:bzcjvn8) ([raw file](https://github.com/cockroachdb/cockroach/blob/cca8405d6a65047eded7b97264a287fe64852bf4/pkg/sql/sem/tree/eval.go#L3070)):*
> ```Go
> 	// CompactEngineSpan is used to compact an engine key span at the given
> 	// (nodeID, storeID). The parameter list here will be replaced by a struct
> 	// union when we add more overloads to the compact_span builtin.
> ```

Do you think the list will realistically be replaced? I don't think it needs to (but there may be a gap in my understanding).

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57709)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @sumeerbhola, and @tbg)

___
*[pkg/sql/planner.go, line 725 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-MO6oIUn9rWYJE3vSV9I:-MOc6j4GBSw__dA1znmI:b-vgkqqa) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8a211039d754122ec5adcfa8e88b5cab8639c76/pkg/sql/planner.go#L725)):*

> I'm not sure, you'd have to ask someone from SQL.

Yahor confirmed that they are the same.
___
*[pkg/sql/sem/builtins/builtins.go, line 4542 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-MOai85Y-srapIpkpWCU:-MOcAGPJ2upDq9xpsEJt:b-g9axjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/cca8405d6a65047eded7b97264a287fe64852bf4/pkg/sql/sem/builtins/builtins.go#L4542)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Rather than baking the hex encoding in here, the caller could use the `decode` builtin if they wished to specify the inputs in hex, or even just use the `\x` encoding (https://www.postgresql.org/docs/9.1/datatype-binary.html).
I don't have any particular rule to point to to justify this, but I think the method should take the data in the representation that is most natural to it, and a "string that will be assumed to be hex encoded" doesn't seem to qualify, especially since we assume that the keys are mostly provided by `crdb_internal.ranges_no_leases`.
</blockquote></details>

Thanks for the link -- I'd been hunting for a spec for the encoding we emit bytes in, and this clarifies things.

When I run `SELECT start_key, end_key from crdb_internal.ranges_no_leases;` the keys are printed in the `bytea` escape format which is discouraged in https://www.postgresql.org/docs/current/datatype-binary.html#id-1.5.7.12.10.
And doing `encode(start_key, 'hex')` is the same as `to_hex(start_key)` -- I can change the comment here to say the former to be more Postgres compliant, though since this is an internal facing function the conciseness of `to_hex` may be preferable. And `lex.DecodeRawBytesToByteArray` is calling `hex.DecodeString` just as the code here does. If you prefer I can use `lex.DecodeRawBytesToByteArray` so that there is no decoding code divergence over time.
So I am still leaning towards hex. If this function were to take either hex or escape format it would also need to take a format string, which seems unnecessary flexibility.
Thoughts?
___
*[pkg/sql/sem/tree/eval.go, line 3070 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-MOaj-as9oGFRTzig3f5:-MOcCuDc5wc3jpHYhplu:b-h9xyst) ([raw file](https://github.com/cockroachdb/cockroach/blob/cca8405d6a65047eded7b97264a287fe64852bf4/pkg/sql/sem/tree/eval.go#L3070)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Do you think the list will realistically be replaced? I don't think it needs to (but there may be a gap in my understanding).
</blockquote></details>

I assumed we would eventually want something that iterated over all nodes. I've adjusted the comment.
Punching out of the builtin environment in this way is a hack, so all I wanted to state here was that we shouldn't start adding more methods here.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57709)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @sumeerbhola, and @tbg)

___
*[pkg/sql/sem/builtins/builtins.go, line 4542 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-MOai85Y-srapIpkpWCU:-MOeiOK1DzSJWK5pGRqx:bdl4aip) ([raw file](https://github.com/cockroachdb/cockroach/blob/cca8405d6a65047eded7b97264a287fe64852bf4/pkg/sql/sem/builtins/builtins.go#L4542)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Thanks for the link -- I'd been hunting for a spec for the encoding we emit bytes in, and this clarifies things.

When I run `SELECT start_key, end_key from crdb_internal.ranges_no_leases;` the keys are printed in the `bytea` escape format which is discouraged in https://www.postgresql.org/docs/current/datatype-binary.html#id-1.5.7.12.10.
And doing `encode(start_key, 'hex')` is the same as `to_hex(start_key)` -- I can change the comment here to say the former to be more Postgres compliant, though since this is an internal facing function the conciseness of `to_hex` may be preferable. And `lex.DecodeRawBytesToByteArray` is calling `hex.DecodeString` just as the code here does. If you prefer I can use `lex.DecodeRawBytesToByteArray` so that there is no decoding code divergence over time.
So I am still leaning towards hex. If this function were to take either hex or escape format it would also need to take a format string, which seems unnecessary flexibility.
Thoughts?
</blockquote></details>

I'm not sure we're on the same page yet. My point was that it strikes me as unidiomatic to have a builtin that takes hex-encoded strings instead of just raw bytes. If you dropped all of the hex encoding stuff and just used `select crdb_internal.compact_engine_span(1, 1, start_key, end_key) from crdb_internal.ranges_no_leases`, does that not work?

If you had a hex key and wanted to pass that to the method (say you poked at the engine manually and so all you have is a copied hex string) you could use

```
select crdb_internal.compact_engine_span(1, 1, decode('deadbeef', 'hex'), decode('feadbeef', 'hex'))
```

so I don't understand why you want to force the hex encoding into the builtin.

I also don't understand why it matters how the keys are printed when you select from `crdb_internal.ranges_no_leases`. They are raw byte strings, surely they won't pretty-print nicely, but why is that an issue? Feels like I'm missing something.

**Review by sumeerbhola — COMMENTED** [review]
> I don't know if that's worth it, once we get rid of the hex encoding.

I didn't bother adding more tests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-:-MOiGWxx5v9Zb_U_slbb:btnywb2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @tbg)

___
*[pkg/sql/logictest/testdata/logic_test/crdb_internal, line 647 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-MOahpXr2fbU_zp4YRlL:-MOiGSaD1A0ZxPl_GvyG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cca8405d6a65047eded7b97264a287fe64852bf4/pkg/sql/logictest/testdata/logic_test/crdb_internal#L647)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

would need to change if the hex stuff went away.
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/builtins.go, line 4542 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-MOai85Y-srapIpkpWCU:-MOiG_h2CrpJN0e7XHIz:bty4jke) ([raw file](https://github.com/cockroachdb/cockroach/blob/cca8405d6a65047eded7b97264a287fe64852bf4/pkg/sql/sem/builtins/builtins.go#L4542)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I'm not sure we're on the same page yet. My point was that it strikes me as unidiomatic to have a builtin that takes hex-encoded strings instead of just raw bytes. If you dropped all of the hex encoding stuff and just used `select crdb_internal.compact_engine_span(1, 1, start_key, end_key) from crdb_internal.ranges_no_leases`, does that not work?

If you had a hex key and wanted to pass that to the method (say you poked at the engine manually and so all you have is a copied hex string) you could use

```
select crdb_internal.compact_engine_span(1, 1, decode('deadbeef', 'hex'), decode('feadbeef', 'hex'))
```

so I don't understand why you want to force the hex encoding into the builtin.

I also don't understand why it matters how the keys are printed when you select from `crdb_internal.ranges_no_leases`. They are raw byte strings, surely they won't pretty-print nicely, but why is that an issue? Feels like I'm missing something.

</blockquote></details>

My thinking was fuzzy -- I mixed up the printing aspect and jumped to an assumption that a user would need to pass in a string and not bytea. Didn't realize that `decode` bridges that gap.
Done.
___
*[pkg/sql/sem/builtins/builtins.go, line 4560 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-MOaiu5wAm5RyI3rZLmD:-MOiDi658j67Q7Ow9d7W:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cca8405d6a65047eded7b97264a287fe64852bf4/pkg/sql/sem/builtins/builtins.go#L4560)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Would need an update if hex stuff were to go away.
</blockquote></details>

Done.

**Review by tbg — APPROVED** [review]
Looking forward to seeing this solve problems in the wild!

> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-:-MOjzi0JD2V-L5WSRWeT:bd39jdr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @sumeerbhola, and @tbg)

___
*[pkg/sql/logictest/testdata/logic_test/crdb_internal, line 649 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-MOjyrCrD2nZ9NfmE6vx:-MOjyrCrD2nZ9NfmE6vy:b-awx8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dfe1081e99b46d4811d90c63312fa35c89764a6/pkg/sql/logictest/testdata/logic_test/crdb_internal#L649)):*
> ```
> SELECT start_pretty, end_pretty, to_hex(start_key), to_hex(end_key),
>  crdb_internal.compact_engine_span(1, 1, start_key, end_key)
> FROM crdb_internal.ranges_no_leases WHERE table_name = 'foo' LIMIT 1
> ```

This seems unnecessary prone to needing to change when the assigned tableID changes. I like how this test documents the ultimate intended usage (rather than just calling with `\xff` and `\xff\xff` or something like that), but I'd prefer thinning this down so that the ID doesn't leak into the file:

```
SELECT crdb_internal.compact_engine_span(1, 1, start_key, end_key)
FROM crdb_internal.ranges_no_leases WHERE table_name = 'foo' LIMIT 1

```
___
*[pkg/sql/logictest/testdata/logic_test/crdb_internal, line 654 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-MOjyj7r5MRMq65Yb7y_:-MOjyj7r5MRMq65Yb7ya:b1o9q5s) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dfe1081e99b46d4811d90c63312fa35c89764a6/pkg/sql/logictest/testdata/logic_test/crdb_internal#L654)):*
> ```
> /Table/56/1/1  /Table/56/1/2  c08989  c0898a  true
> 
> # Failed compaction due to unknown node.
> ```

How about one with unknown store as well?

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57709)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @tbg)

___
*[pkg/sql/logictest/testdata/logic_test/crdb_internal, line 649 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-MOjyrCrD2nZ9NfmE6vx:-MOlLdx7186U3ZW-IqQF:btvmejc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dfe1081e99b46d4811d90c63312fa35c89764a6/pkg/sql/logictest/testdata/logic_test/crdb_internal#L649)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This seems unnecessary prone to needing to change when the assigned tableID changes. I like how this test documents the ultimate intended usage (rather than just calling with `\xff` and `\xff\xff` or something like that), but I'd prefer thinning this down so that the ID doesn't leak into the file:

```
SELECT crdb_internal.compact_engine_span(1, 1, start_key, end_key)
FROM crdb_internal.ranges_no_leases WHERE table_name = 'foo' LIMIT 1

```
</blockquote></details>

The test uses the same key again in the `decode`-based call below, rather than make up a fictional one, so if we want to keep that consistent with this, we would need to leak the tableID.
___
*[pkg/sql/logictest/testdata/logic_test/crdb_internal, line 654 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-MOjyj7r5MRMq65Yb7y_:-MOlMrHS95NCS0ctrX5X:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dfe1081e99b46d4811d90c63312fa35c89764a6/pkg/sql/logictest/testdata/logic_test/crdb_internal#L654)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

How about one with unknown store as well?
</blockquote></details>

Done

**Review by tbg — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57709)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

___
*[pkg/sql/logictest/testdata/logic_test/crdb_internal, line 649 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-MOjyrCrD2nZ9NfmE6vx:-MOlOsjj4ysUC6Z2ADJY:b-qwbu7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dfe1081e99b46d4811d90c63312fa35c89764a6/pkg/sql/logictest/testdata/logic_test/crdb_internal#L649)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

The test uses the same key again in the `decode`-based call below, rather than make up a fictional one, so if we want to keep that consistent with this, we would need to leak the tableID.
</blockquote></details>

I don't feel strongly either way (the next person shuffling the tableIDs around might) but there's no reason imo why the below example needs to line up with the above. In fact you could just hard-code `a` and `b` because all you care about is getting a nonempty span.

Speaking of which, that might be something to test, what happens if you pass `end <= start`?

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57709)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @tbg)

___
*[pkg/sql/logictest/testdata/logic_test/crdb_internal, line 649 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-MOjyrCrD2nZ9NfmE6vx:-MOlceDK71HRsEwLBypC:b7phr7p) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dfe1081e99b46d4811d90c63312fa35c89764a6/pkg/sql/logictest/testdata/logic_test/crdb_internal#L649)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I don't feel strongly either way (the next person shuffling the tableIDs around might) but there's no reason imo why the below example needs to line up with the above. In fact you could just hard-code `a` and `b` because all you care about is getting a nonempty span.

Speaking of which, that might be something to test, what happens if you pass `end <= start`?
</blockquote></details>

I changed it to not output the keys, and added a test with an invalid range. There was no error being generated by Pebble -- a quick look at the code suggests that it just turning into a trivially empty range. So I added some checking in `CompactEngineSpan`.

**Review by tbg — APPROVED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57709)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

___
*[pkg/sql/planner.go, line 736 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-MOq2LPE5jPJ7HQcL_hz:-MOq2LPF2jHv3I9SEOxq:bh2tw6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/d92373bfd1dfd5b5189e198008e9771ee533dfe2/pkg/sql/planner.go#L736)):*
> ```Go
> 	end := roachpb.Key(endKey)
> 	if start.Compare(end) >= 0 {
> 		return errors.Errorf("start %s is not less than end %s", start, end)
> ```

Wouldn't it be more idiomatic to check this when it's handed to pebble? After all, there can be multiple code paths calling into pebble compactions (in theory, maybe even practice?!) and they all benefit from this check.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57709)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

___
*[pkg/sql/planner.go, line 736 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-MOq2LPE5jPJ7HQcL_hz:-MOq2ZqP2CeQDE74TXBp:bqdp8wn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d92373bfd1dfd5b5189e198008e9771ee533dfe2/pkg/sql/planner.go#L736)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Wouldn't it be more idiomatic to check this when it's handed to pebble? After all, there can be multiple code paths calling into pebble compactions (in theory, maybe even practice?!) and they all benefit from this check.
</blockquote></details>

(i.e. inside of pebble, I mean)

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57709)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @tbg)

___
*[pkg/sql/planner.go, line 736 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/57709#-MOq2LPE5jPJ7HQcL_hz:-MPGQtcNC64vve90Be7N:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d92373bfd1dfd5b5189e198008e9771ee533dfe2/pkg/sql/planner.go#L736)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

(i.e. inside of pebble, I mean)
</blockquote></details>

Done

**Review by tbg — APPROVED** [review]
> Reviewed 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57709)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal)

**Pull request merged**
