### PR TITLE
sql: Add command for manually transferring a lease

### PR DESCRIPTION
**Pull request by a-robinson**
Fixes https://github.com/cockroachdb/cockroach/issues/21420.

Release note (sql change): The new EXPERIMENTAL_RELOCATE LEASE command
for ALTER TABLE and ALTER INDEX allows manually transferring the leases
for specific ranges to specific stores.

I don't like the syntax here (particularly the fact that it can't be used on non-SQL ranges), but did a v1 of it to best match the existing `TESTING_RELOCATE` command from https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20170314_sql_split_syntax.md#3-alter-tableindex-testing_relocate that I had completely forgotten about. I think we ought to change or extend both of them to be more friendly to ranges that aren't currently part of a valid table/index.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
It would be nice if we had a test for this new functionality, although it doesn't look like we have anything targetted for `TESTING_RELOCATE` either.

---

Reviewed 13 of 13 files at r1.
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/expand_plan.go, line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26436#-LFsQjkp291srnTr9Go5:-LFsQjkq8_tUqbWUF5W_:b-pwasdj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9836992a7285074b73f59338fa347cbb763f931/pkg/sql/expand_plan.go#L342)):*
> ```Go
> 
> 	case *testingRelocateLeaseNode:
> 		n.rows, err = doExpandPlan(ctx, p, noParams, n.rows)
> ```

minor nit: new line after this line.

---

*[pkg/sql/testing_relocate.go, line 305 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26436#-LFsQB-l2hx9Kf3QpSkc:-LFsQB-l2hx9Kf3QpSkd:b-f2184p) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9836992a7285074b73f59338fa347cbb763f931/pkg/sql/testing_relocate.go#L305)):*
> ```Go
> 	data := n.rows.Values()
> 
> 	if !data[0].ResolvedType().Equivalent(types.Int) {
> ```

Do we need this with the previous check in `planner.TestingRelocateLease`?

---

*[pkg/sql/testing_relocate.go, line 311 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26436#-LFsQ29hEnGZ0pHE_Uus:-LFsQ29hEnGZ0pHE_Uut:b-eyhz43) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9836992a7285074b73f59338fa347cbb763f931/pkg/sql/testing_relocate.go#L311)):*
> ```Go
> 		)
> 	}
> 	storeID := roachpb.StoreID(*data[0].(*tree.DInt))
> ```

`roachpb.StoreID(tree.MustBeDInt(data[0]))`

---

*[pkg/sql/parser/sql.y, line 1263 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26436#-LFsP4dG3kcF3XoRO17G:-LFsP4dG3kcF3XoRO17H:b-eqt1n3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9836992a7285074b73f59338fa347cbb763f931/pkg/sql/parser/sql.y#L1263)):*
> ```Yacc
>   }
> 
> alter_relocate_lease_stmt:
> ```

Looks like we're missing new cases in `TestParse` for this statement.

---

*[pkg/sql/sem/tree/split.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26436#-LFsOQDd-Iq0xAl9TTqV:-LFsOQDd-Iq0xAl9TTqW:b-2305vl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9836992a7285074b73f59338fa347cbb763f931/pkg/sql/sem/tree/split.go#L72)):*
> ```Go
> 	// Only one of Table and Index can be set.
> 	// TODO(XXX): It's not great that this (and TestingRelocate) can only work on
> 	// ranges that are part of a currently valid table or index.
> ```

This is an unfortunate limitation, but it's one we have with all of the other configuration statements in this file as well, right? In that case, I think it can be left as a general TODO.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26436#-:-LFsR6ty9uMQPIVtvghs:b-wmgfct)*

**Review by a-robinson — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26436#-:-LH-hzb1Ecm84C0aAXuQ:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/testing_relocate.go, line 305 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26436#-LFsQB-l2hx9Kf3QpSkc:-LH-gB6i-n6wsqR6-cnW:b-aq2l89) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9836992a7285074b73f59338fa347cbb763f931/pkg/sql/testing_relocate.go#L305)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need this with the previous check in `planner.TestingRelocateLease`?
</blockquote></details>

I'm not sure,  I just cribbed it from `TestingRelocate`, which does a similar check in the `planner` method. It certainly looks redundant, but I'm not familiar enough with this code to be confident about it. I'll remove it if you believe it's not necessary.
___
*[pkg/sql/testing_relocate.go, line 311 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26436#-LFsQ29hEnGZ0pHE_Uus:-LH-gt6I5NSzb6Fwdwa5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9836992a7285074b73f59338fa347cbb763f931/pkg/sql/testing_relocate.go#L311)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`roachpb.StoreID(tree.MustBeDInt(data[0]))`
</blockquote></details>

Done.
___
*[pkg/sql/parser/sql.y, line 1263 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26436#-LFsP4dG3kcF3XoRO17G:-LH-hhI-BSAdktBAu7ES:bd0jggz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9836992a7285074b73f59338fa347cbb763f931/pkg/sql/parser/sql.y#L1263)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Looks like we're missing new cases in `TestParse` for this statement.
</blockquote></details>

Thanks for catching that. Done.
___
*[pkg/sql/sem/tree/split.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26436#-LFsOQDd-Iq0xAl9TTqV:-LH-XCGhBhHoad9802j4:b-uw4gpi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9836992a7285074b73f59338fa347cbb763f931/pkg/sql/sem/tree/split.go#L72)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is an unfortunate limitation, but it's one we have with all of the other configuration statements in this file as well, right? In that case, I think it can be left as a general TODO.
</blockquote></details>

I was really hoping to do something about this before adding a new statement with the limitation, but also don't know if it's worth the cycles needed to design and agree on an alternative. I've changed to a normal TODO and won't block on it, but am (as always) interested in @knz's input on this.

**Review by nvb — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26436)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/parser/parse_test.go, line 945 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26436#-LH-xP4Y9Ra7Ey_aWMpo:-LH-xP4Z-bcBCGRvxhdE:b-muw25b) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ef376baeacb52b37cce81319abd33af0329d700/pkg/sql/parser/parse_test.go#L945)):*
> ```Go
> 		{`ALTER INDEX d.i EXPERIMENTAL_RELOCATE VALUES (ARRAY[1], 2)`},
> 
> 		{`ALTER TABLE a EXPERIMENTAL_RELOCATE VALUES (1, 1)`},
> ```

This is missing the `LEASE` keyword.
___
*[pkg/sql/testing_relocate.go, line 305 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26436#-LFsQB-l2hx9Kf3QpSkc:-LH-xcoEAH4o8eBVCLIP:bboqpu4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9836992a7285074b73f59338fa347cbb763f931/pkg/sql/testing_relocate.go#L305)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

I'm not sure,  I just cribbed it from `TestingRelocate`, which does a similar check in the `planner` method. It certainly looks redundant, but I'm not familiar enough with this code to be confident about it. I'll remove it if you believe it's not necessary.
</blockquote></details>

Yeah, we should be able to remove it. Double check though. You can try giving it a string that can't be coerced to an int.

**Review by a-robinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26436)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/parser/parse_test.go, line 945 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26436#-LH-xP4Y9Ra7Ey_aWMpo:-LH01Ulf3ZYzgxMig5XF:bw9rzb0) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ef376baeacb52b37cce81319abd33af0329d700/pkg/sql/parser/parse_test.go#L945)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is missing the `LEASE` keyword.
</blockquote></details>

:man_facepalming: 

Fixed, thanks.
___
*[pkg/sql/testing_relocate.go, line 305 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26436#-LFsQB-l2hx9Kf3QpSkc:-LH0A7bR84qrsa6daWnb:bo066k8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9836992a7285074b73f59338fa347cbb763f931/pkg/sql/testing_relocate.go#L305)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah, we should be able to remove it. Double check though. You can try giving it a string that can't be coerced to an int.
</blockquote></details>

Yup, looks good to me.

```
root@:26257/defaultdb> alter table foo experimental_relocate lease values ('2', 1111);
+------+-----------+
| key  |  pretty   |
+------+-----------+
| \xbe | /Table/54 |
+------+-----------+
(1 row)

Time: 3.50094ms
root@:26257/defaultdb> alter table foo experimental_relocate lease values ('foo', 1111);
pq: could not parse "foo" as type int: strconv.ParseInt: parsing "foo": invalid syntax
```

**Review by nvb — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26436#-:-LH1CFwD6N438HkPd4jg:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by knz — APPROVED** [review]
The code is correct and solid, but gosh, so much redundancy!

The code for `relocateNode` and `relocateLeaseNode` is, if I read this correctly, completely identical but for the final call to `AdminTransferLease` or `RelocateRange`. Is that the case?

If so, then please instead add a new boolean field `RelocateLease` in `tree.Relocate` (`split.go`),
then use that field with a simple `if ... { AdminTransferLease } else { ...RelocateRange...}`  in the existing code in `sql/relocate.go`.

> Reviewed 1 of 13 files at r1, 11 of 14 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26436#-:-LH2e6wuEMaJzkr6zy2K:b30cq9b)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by a-robinson — COMMENTED** [review]
Thanks for the quick review! It's a little more than just that call at the end of `Next`, but there was certainly a lot of duplication. I've merged them as you suggested, albeit now the code is a little awkwardly mixed together due to the type differences between the two commands. It's still better this way, but maybe not by as much as you were thinking.

**Review by knz — APPROVED** [review]
I do like it.

:lgtm:

As to your comment: "It's unfortunate this only works on ranges that are parts of tables or indexes". 

Do you have suggestions as to what better handle we could use? I was running into a similar question for zone configs. 

> Reviewed 11 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26436#-:-LH9OlmM6J0uhzJED2th:b-indxlz)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/relocate.go, line 85 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26436#-LH9P6Mo-nlEnUfUQjib:-LH9P6Mo-nlEnUfUQjic:b11iv42) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c61aa169fcf471059393e240d16a70c8d0eea12/pkg/sql/relocate.go#L85)):*
> ```Go
> 	}
> 	if len(cols) < 2 {
> 		return nil, errors.Errorf("less than two columns in %s data", cmdName)
> ```

nit: I'd have skipped the change of this error message. Since ALTER statements cannot be nested, there would not be any ambiguity.
___
*[pkg/sql/relocate.go, line 94 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26436#-LH9PIDK6UU9V8tW01Ll:-LH9PIDK6UU9V8tW01Lm:b-fn6wbc) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c61aa169fcf471059393e240d16a70c8d0eea12/pkg/sql/relocate.go#L94)):*
> ```Go
> 			var colName string
> 			if i == 0 {
> 				if n.RelocateLease {
> ```

nit: Hoist this initialization of colName to the top of the loop.

**Review by a-robinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26436)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/relocate.go, line 94 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26436#-LH9PIDK6UU9V8tW01Ll:-LH9QYAQ6PobOgjDM3-f:b-sagvj1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c61aa169fcf471059393e240d16a70c8d0eea12/pkg/sql/relocate.go#L94)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: Hoist this initialization of colName to the top of the loop.
</blockquote></details>

I'm not totally sure what you mean. You mean before even checking whether the column type matches the desired type? I've switched the code back to being more like it was before.

**Review by knz — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26436)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/relocate.go, line 94 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26436#-LH9PIDK6UU9V8tW01Ll:-LH9TT5B5BclXk9gWIKu:b7v7vs9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c61aa169fcf471059393e240d16a70c8d0eea12/pkg/sql/relocate.go#L94)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

I'm not totally sure what you mean. You mean before even checking whether the column type matches the desired type? I've switched the code back to being more like it was before.
</blockquote></details>

yes I can live with this too. Thanks!

**Pull request merged**
