### PR TITLE
engine: Fix pebble.OpenFile and related functions.

### PR DESCRIPTION
**Pull request by itsbilal**
engine.OpenFile is called with the full path, not just the
filename, despite the variable name. That function is also
expected to create the file if it doesn't exist. This fix makes
changes to bring that function in line with what's in RocksDB.

Other miscellaneous sstable.{Reader,Writer} options changes to get
cockroach to build with the latest pebble.

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41727)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/bulk/sst_writer.go, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41727#-LrYryIE87s7gqZr1a1I:-LrYryIE87s7gqZr1a1J:b-b2skr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ece23ced305aca190a9e19decdc8ea5995fbf7dc/pkg/storage/bulk/sst_writer.go#L97)):*
> ```Go
> 		Comparer:       engine.MVCCComparer,
> 		MergerName:     "nullptr",
> 		BlockSize:      64 * 1024,
> ```

Do we configure the RocksDB-based writer to use 64KB? That's strange as we normally configure both Pebble and RocksDB to use a 32KB block size.
___
*[pkg/storage/bulk/sst_writer.go, line 98 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41727#-LrYs7SrCeKE9dlwI4RR:-LrYs7SrCeKE9dlwI4RS:b-vd943s) ([raw file](https://github.com/cockroachdb/cockroach/blob/ece23ced305aca190a9e19decdc8ea5995fbf7dc/pkg/storage/bulk/sst_writer.go#L98)):*
> ```Go
> 		MergerName:     "nullptr",
> 		BlockSize:      64 * 1024,
> 		IndexBlockSize: math.MaxInt32,
> ```

This shouldn't be necessary as `TableFormatLevelDB` disables two-level indexes.
___
*[pkg/storage/engine/pebble.go, line 438 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41727#-LrYsJ4X5M9i69UtZAjl:-LrYsJ4X5M9i69UtZAjm:b-21c6pj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ece23ced305aca190a9e19decdc8ea5995fbf7dc/pkg/storage/engine/pebble.go#L438)):*
> ```Go
> 	}
> 	if _, err := p.fs.Stat(filename); os.IsNotExist(err) {
> 		return p.fs.Create(filename)
> ```

I'm wondering if all of the complexity is necessary here, or if this method should just be `p.fs.Create(filename)`. AFAICT, the RocksDB version calls down into a single `open(..., O_CREAT)` call.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41727)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/pebble.go, line 438 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41727#-LrYsJ4X5M9i69UtZAjl:-Lridr4eEbprrGc9IfB1:b-ftt7zm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ece23ced305aca190a9e19decdc8ea5995fbf7dc/pkg/storage/engine/pebble.go#L438)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm wondering if all of the complexity is necessary here, or if this method should just be `p.fs.Create(filename)`. AFAICT, the RocksDB version calls down into a single `open(..., O_CREAT)` call. 
</blockquote></details>

It seems that `OpenFile` is supposed to create a file for writing (even thought `Engine.OpenFile` does not have a comment that states the purpose) while `vfs.FS.OpenFile` opens the file for reading. 
And `vfs.FS.Create` does not truncate since we are using that function for also reusing WAL files -- do we need a create with truncate for the use case here?

**Review by itsbilal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41727)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr and @petermattis)

___
*[pkg/storage/bulk/sst_writer.go, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41727#-LrYryIE87s7gqZr1a1I:-LrivsvB9cMb_qla4frG:b9lkixu) ([raw file](https://github.com/cockroachdb/cockroach/blob/ece23ced305aca190a9e19decdc8ea5995fbf7dc/pkg/storage/bulk/sst_writer.go#L97)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Do we configure the RocksDB-based writer to use 64KB? That's strange as we normally configure both Pebble and RocksDB to use a 32KB block size.
</blockquote></details>

We do. It's in `libroach/db.cc` with this comment:
```
  // Larger block size (4kb default) means smaller file at the expense of more
  // scanning during lookups.
  table_options.block_size = 64 * 1024;
```
___
*[pkg/storage/bulk/sst_writer.go, line 98 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41727#-LrYs7SrCeKE9dlwI4RR:-Lrivz4YEbVS1bUYaJqM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ece23ced305aca190a9e19decdc8ea5995fbf7dc/pkg/storage/bulk/sst_writer.go#L98)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This shouldn't be necessary as `TableFormatLevelDB` disables two-level indexes.
</blockquote></details>

Done.
___
*[pkg/storage/engine/pebble.go, line 438 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41727#-LrYsJ4X5M9i69UtZAjl:-Lrj-bM63kGRr6tjUihy:bk8526z) ([raw file](https://github.com/cockroachdb/cockroach/blob/ece23ced305aca190a9e19decdc8ea5995fbf7dc/pkg/storage/engine/pebble.go#L438)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

It seems that `OpenFile` is supposed to create a file for writing (even thought `Engine.OpenFile` does not have a comment that states the purpose) while `vfs.FS.OpenFile` opens the file for reading. 
And `vfs.FS.Create` does not truncate since we are using that function for also reusing WAL files -- do we need a create with truncate for the use case here?
 
</blockquote></details>

`Create` does the job - didn't realize it'll implicitly make the directory as well.

And good catch Sumeer. It doesn't seem like we ever call `OpenFile` on a file that already exists, but anyway it probably makes sense to unify behaviour here with RocksDB (which seems to add `| O_TRUNC`). I've added a TODO here.

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41727)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @sumeerbhola)

___
*[pkg/storage/bulk/sst_writer.go, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41727#-LrYryIE87s7gqZr1a1I:-Lrj5Sd29g_NllHZSmyR:b-pjlzph) ([raw file](https://github.com/cockroachdb/cockroach/blob/ece23ced305aca190a9e19decdc8ea5995fbf7dc/pkg/storage/bulk/sst_writer.go#L97)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

We do. It's in `libroach/db.cc` with this comment:
```
  // Larger block size (4kb default) means smaller file at the expense of more
  // scanning during lookups.
  table_options.block_size = 64 * 1024;
```
</blockquote></details>

Ack, but where did that come from? We use 32 KB blocks elsewhere. Did we just mistype this one time and now we're copying it everywhere?
___
*[pkg/storage/engine/pebble.go, line 438 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41727#-LrYsJ4X5M9i69UtZAjl:-Lrj5gFTBH-PjufBSqSD:bsko1n4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ece23ced305aca190a9e19decdc8ea5995fbf7dc/pkg/storage/engine/pebble.go#L438)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

`Create` does the job - didn't realize it'll implicitly make the directory as well.

And good catch Sumeer. It doesn't seem like we ever call `OpenFile` on a file that already exists, but anyway it probably makes sense to unify behaviour here with RocksDB (which seems to add `| O_TRUNC`). I've added a TODO here.
</blockquote></details>

`Create` will not create the directory. If we need that, then add a call to `p.fs.MkdirAll(p.fs.PathDir(filename))`. I don't think we need that, though, as I don't see mkdir happening on the RocksDB code path.

I'm :thumbsup: on separating out `Create` from `OpenExisting` (though I do not like that name).

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41727)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @petermattis)

___
*[pkg/storage/engine/pebble.go, line 438 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41727#-LrYsJ4X5M9i69UtZAjl:-LrjPw4D4v6TjgKLs54y:b-bwrkg) ([raw file](https://github.com/cockroachdb/cockroach/blob/ece23ced305aca190a9e19decdc8ea5995fbf7dc/pkg/storage/engine/pebble.go#L438)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`Create` will not create the directory. If we need that, then add a call to `p.fs.MkdirAll(p.fs.PathDir(filename))`. I don't think we need that, though, as I don't see mkdir happening on the RocksDB code path.

I'm :thumbsup: on separating out `Create` from `OpenExisting` (though I do not like that name). 
</blockquote></details>

We need to distinguish the WAL reuse case from others for encrypted FS -- so I will be adding something like a `ReuseWAL(oldname, newname string) (vfs.File, error) ` function to `vfs.FS`, at which point we could change `Create` to do a truncate.

**Review by itsbilal — COMMENTED** [review]
Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41727#-:-LrkbWvS8xhcKgpM9OFS:b-9qdoz3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @dt, and @petermattis)

___
*[pkg/storage/bulk/sst_writer.go, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41727#-LrYryIE87s7gqZr1a1I:-LrkT8rCDudI2XQ7Gsx-:b-bjpe4w) ([raw file](https://github.com/cockroachdb/cockroach/blob/ece23ced305aca190a9e19decdc8ea5995fbf7dc/pkg/storage/bulk/sst_writer.go#L97)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ack, but where did that come from? We use 32 KB blocks elsewhere. Did we just mistype this one time and now we're copying it everywhere?
</blockquote></details>

Seems like it. Dan who touched that code last says he can't recall a reason for it being different. Changed it back to 32k.

cc @dt for confirmation

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41727)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr and @petermattis)

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41727)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr and @petermattis)

___
*[pkg/storage/bulk/sst_writer.go, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41727#-LrYryIE87s7gqZr1a1I:-Lrkd6j25elTEaw4udNM:b-yjcntn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ece23ced305aca190a9e19decdc8ea5995fbf7dc/pkg/storage/bulk/sst_writer.go#L97)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Seems like it. Dan who touched that code last says he can't recall a reason for it being different. Changed it back to 32k.

cc @dt for confirmation
</blockquote></details>

I have a vague recollection that at one point we considered using (much) bigger blocks since BACKUP SSTs are only ever iterated from start to finish. We don't really care about Seek performance and bigger blocks could get us superior compression which might be nice for transport and/or storage costs... but I think that discussion was about using 4MB blocks, not just few more kb.

As it stands though, I think we're using the same SST writer (and settings) for backup ssts and ingested SSTs, so we should absolutely be using serving-optimized settings, so no objection here from me.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41727)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr and @petermattis)

___
*[pkg/storage/bulk/sst_writer.go, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41727#-LrYryIE87s7gqZr1a1I:-LrnDlfv-Lvi1q2g48DJ:b-t6vvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ece23ced305aca190a9e19decdc8ea5995fbf7dc/pkg/storage/bulk/sst_writer.go#L97)):*
> As it stands though, I think we're using the same SST writer (and settings) for backup ssts and ingested SSTs, so we should absolutely be using serving-optimized settings, so no objection here from me.

We should fix this. Sstables created for backup use LevelDB format, but sstables created for ingestion should use RocksDB format. @itsbilal can you file an issue?

**Comment by itsbilal** [comment]
Filed https://github.com/cockroachdb/cockroach/issues/41814 under both storage and bulk since I was unsure which side this would land on. `sst_writer.go` is currently under bulk (but will probably move to `engine`, or out into `storage` as part of #41657). Feel free to update issue with more context. Thanks!

**Pull request merged**
