### PR TITLE
raft: add conceptual de-fortification and some assertions 

### PR DESCRIPTION
**Pull request by arulajmani**
See individual commits for details.

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 10 of 10 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129100)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`-- commits` line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129100#-O4etGt74jAdkztwxYej):*
> By adding this explicit de-fortification, we're able to then assert that a peer only ever bumps its term if its no longer supporting a fortified leader.

Is this stale? Is it an assertion that we can make? Aren't the "two ways a peer may de-fortify" both counter-examples to this assertion?
___
*[`pkg/raft/raft.go` line 269 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129100#-O4etX_-2y9-0khU7oBI:-O4etX_-2y9-0khU7oBJ:bplrjm1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0730fb4841d86b641b1ce6a3a7582aa5aab899d/pkg/raft/raft.go#L269)):*
> ```Go
> 	StoreLiveness raftstoreliveness.StoreLiveness
> 
> 	// TestingDisableFortification, if set, disables raft leader fortification.
> ```

Can't we give raft a `StoreLiveness` with a `SupportFromEnabled` implementation that always returns false? Is there a benefit to having both approaches?
___
*[`pkg/raft/raft.go` line 803 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129100#-O4eu-iS5fX2abwwSpt0:-O4eu-iS5fX2abwwSpt1:bibr26n) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0730fb4841d86b641b1ce6a3a7582aa5aab899d/pkg/raft/raft.go#L803)):*
> ```Go
> func (r *raft) reset(term uint64) {
> 	if r.Term != term {
> 		assertTrue(!r.supportingFortifiedLeader(),
> ```

I'm still not sure how it is possible to make this assertion. What if others in the raft group elect a new leader while we still support the old one?

EDIT: or is the idea that in any of those cases, `deFortify` will be called first. If so, we should mention that in a comment here.
___
*[`pkg/raft/raft.go` line 917 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129100#-O4eu7Sh9NuSl6dcfY5C:-O4eu7Sh9NuSl6dcfY5D:br435lm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0730fb4841d86b641b1ce6a3a7582aa5aab899d/pkg/raft/raft.go#L917)):*
> ```Go
> }
> 
> // deFortify (conceptually) revokes previously provided fortification support to
> ```

nit: can we move this near all of the other fortification logic?
___
*[`pkg/raft/raft.go` line 1187 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129100#-O4euR349zHj41x2UGeZ:-O4euR349zHj41x2UGe_:b-g2789p) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0730fb4841d86b641b1ce6a3a7582aa5aab899d/pkg/raft/raft.go#L1187)):*
> ```Go
> 				r.becomeFollower(m.Term, m.From)
> 			} else {
> 				if m.Type == pb.MsgVote {
> ```

Instead of the nested `if`s, can we pull this out into a new branch of the parent conditional? Maybe something like:
```go
switch m.Type {
case pb.MsgApp, pb.MsgHeartbeat, pb.MsgSnap, pb.MsgFortifyLeader:
    r.deFortify(m.From, m.Term)
    r.becomeFollower(m.Term, m.From)
case pb.MsgVote:
    ...
default:
    ...
}
```

**Review by arulajmani — COMMENTED** [review]
RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129100#-:-O4rE6MD8KT0irp7Cj26:bb72pd0)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`-- commits` line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129100#-O4etGt74jAdkztwxYej):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> By adding this explicit de-fortification, we're able to then assert that a peer only ever bumps its term if its no longer supporting a fortified leader.

Is this stale? Is it an assertion that we can make? Aren't the "two ways a peer may de-fortify" both counter-examples to this assertion?
</blockquote></details>

I think this relates to your other comment below, where you had this edit:

```
EDIT: or is the idea that in any of those cases, deFortify will be called first. If so, we should mention that in a comment here.
```
 
Was this comment from before that edit? I'm open to rewording this to make things a bit clearer, but what I was trying to say is that because we call de-fortify on both those paths, we're able to ,add this assertion. 
___
*[`pkg/raft/raft.go` line 269 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129100#-O4etX_-2y9-0khU7oBI:-O4rDUkV9GI6SEUmIVhA:b-1bmdq5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0730fb4841d86b641b1ce6a3a7582aa5aab899d/pkg/raft/raft.go#L269)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can't we give raft a `StoreLiveness` with a `SupportFromEnabled` implementation that always returns false? Is there a benefit to having both approaches?
</blockquote></details>

Hadn't considered it. Switched, your approach is nicer.
___
*[`pkg/raft/raft.go` line 803 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129100#-O4eu-iS5fX2abwwSpt0:-O4rA-j5CG3xR5hnrqrb:b-vzd8og) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0730fb4841d86b641b1ce6a3a7582aa5aab899d/pkg/raft/raft.go#L803)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm still not sure how it is possible to make this assertion. What if others in the raft group elect a new leader while we still support the old one?

EDIT: or is the idea that in any of those cases, `deFortify` will be called first. If so, we should mention that in a comment here.
</blockquote></details>

Yeah exactly. Like we briefly spoke about last week, with an explicit `deFortify`, we're able to make this assertion in reset. I added a comment.
___
*[`pkg/raft/raft.go` line 917 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129100#-O4eu7Sh9NuSl6dcfY5C:-O4rABxR0vyas8kiWmB3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0730fb4841d86b641b1ce6a3a7582aa5aab899d/pkg/raft/raft.go#L917)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: can we move this near all of the other fortification logic?
</blockquote></details>

Done.
___
*[`pkg/raft/raft.go` line 1187 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129100#-O4euR349zHj41x2UGeZ:-O4rAg-oDkD-aQO71Lf3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0730fb4841d86b641b1ce6a3a7582aa5aab899d/pkg/raft/raft.go#L1187)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Instead of the nested `if`s, can we pull this out into a new branch of the parent conditional? Maybe something like:
```go
switch m.Type {
case pb.MsgApp, pb.MsgHeartbeat, pb.MsgSnap, pb.MsgFortifyLeader:
    r.deFortify(m.From, m.Term)
    r.becomeFollower(m.Term, m.From)
case pb.MsgVote:
    ...
default:
    ...
}
```
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r4, 9 of 10 files at r5, 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129100#-:-O4rYZZeBWf-QmQo2psU:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`-- commits` line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129100#-O4etGt74jAdkztwxYej):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I think this relates to your other comment below, where you had this edit:

```
EDIT: or is the idea that in any of those cases, deFortify will be called first. If so, we should mention that in a comment here.
```
 
Was this comment from before that edit? I'm open to rewording this to make things a bit clearer, but what I was trying to say is that because we call de-fortify on both those paths, we're able to ,add this assertion.
</blockquote></details>

Got it, in that case, this seems fine.
___
*[`pkg/raft/raft.go` line 269 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129100#-O4etX_-2y9-0khU7oBI:-O4rXOsV8AZmsTaoeBza:b4txaru) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0730fb4841d86b641b1ce6a3a7582aa5aab899d/pkg/raft/raft.go#L269)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Hadn't considered it. Switched, your approach is nicer.
</blockquote></details>

Can we get rid of this flag now?
___
*[`pkg/raft/raft.go` line 2005 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/129100#-O4rY90UDdSd_ijZBrEX:-O4rY90UDdSd_ijZBrEY:b-o3g1y0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7fd9e5ee184c31c915c8b367f0a139ab8ad014d/pkg/raft/raft.go#L2005)):*
> ```Go
> // a leader.
> func (r *raft) deFortify(from pb.PeerID, term uint64) {
> 	assertTrue(term > r.Term || (from == r.lead && r.Term == term),
> ```

small nit: replace `from == r.lead && r.Term == term` with `term == r.Term && from == r.lead` to read nicer next to the `term > r.Term`.

**Review by arulajmani — COMMENTED** [review]
Thanks!

bors r=nvanbenschoten

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129100#-:-O4rkDab2rp8VajtMHLa:bh7uere)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[`pkg/raft/raft.go` line 269 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129100#-O4etX_-2y9-0khU7oBI:-O4rjmIQ5KSCsgan3SPz:b-mmmq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0730fb4841d86b641b1ce6a3a7582aa5aab899d/pkg/raft/raft.go#L269)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we get rid of this flag now?
</blockquote></details>

Sorry, meant to delete this. Done.
___
*[`pkg/raft/raft.go` line 2005 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/129100#-O4rY90UDdSd_ijZBrEX:-O4rk1O9AecBo36aFil7:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7fd9e5ee184c31c915c8b367f0a139ab8ad014d/pkg/raft/raft.go#L2005)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

small nit: replace `from == r.lead && r.Term == term` with `term == r.Term && from == r.lead` to read nicer next to the `term > r.Term`.
</blockquote></details>

Done.

**Comment by arulajmani** [comment]
Build failed with:
```
ERROR: /home/agent/.cache/bazel/_bazel_agent/5ff96bfab82c7a794450c7f1830ec61e/external/com_google_protobuf/BUILD:280:26: Executing genrule @@com_google_protobuf//:_internal_wkt_protos_genrule failed: (Exit 34): UNAVAILABLE: io exceptionChannel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]Target //pkg/cmd/bazci/bazel-github-helper:bazel-github-helper failed to build
```

That IO exception doesn't seem related to the PR. I'll optimistically try to re-merge. 

bors r=nvanbenschoten

**Review by nvb — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129100)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani)

**Pull request merged**
