### PR TITLE
deps: upgrade redact

### PR DESCRIPTION
**Pull request by knz**
First commit from #104718.

Imports https://github.com/cockroachdb/redact/pull/29
should result in general enhancements to the quality of redactable logs.

Epic: CRDB-27642

### CODE REVIEW

**Review by ericharmeling — APPROVED** [review]
Don't have much context on the first commit, but the second commit LGTM!

> Reviewed 10 of 10 files at r1, 21 of 21 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103857#-:-NXjuV-l5pK3hZDa75FD:b-z5d4iw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft and @sumeerbhola)

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1, 21 of 21 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103857#-:-NXk5PhMEFV_nbb6eX8Z:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Comment by knz** [comment]
TFYRs!

bors r=ericharmeling,rytaft

**Comment by knz** [comment]
bors r=ericharmeling,rytaft

**Comment by knz** [comment]
bors r=ericharmeling,rytaft single on

**Pull request merged**
