### PR TITLE
cluster-ui: add region and nodes label component 

### LINKED ISSUE #130674: cluster-ui: v2 databases - component mock ups
This issue tracks the implementation of the new db overview page.
This step just requires the new page layout with mocked data.

Figma: https://www.figma.com/design/mP7CcVoGUmd1673TMWtsDI/DB-console-%2F-Databases?node-id=102-54&t=il9BTcOArWB55wap-1

Jira issue: CRDB-42176

Epic CRDB-37558

### PR DESCRIPTION
**Pull request by xinhaoz**
Only the latest commit in this PR should be reviewed.
Previous: https://github.com/cockroachdb/cockroach/pull/130693

---------------------------------------------
This commit adds a component displaying a region and
its nodes. The component shows the region code, e.g.
`us-east-1` followed by a count of the number of nodes
in the region. On hover, the component shows the list
of nodes in the region.

Epic: none
Fixes: https://github.com/cockroachdb/cockroach/issues/130674

image
image

### CODE REVIEW

**Review by angles-n-daemons — CHANGES_REQUESTED** [review]
couple of initial questions, looks good overall

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130704#-:-O6vv468AZhG9xIBzVhA:b-ju23yr)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @kyle-a-wong, and @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/databasesV2/databasesTable.tsx` line 29 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130704#-O6vt_F44SCT3c1DH5Vh:-O6vt_F44SCT3c1DH5Vi:b4udwzo) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2ea60357c4ec7c621a39c0f7403b6a38e03497c/pkg/ui/workspaces/cluster-ui/src/databasesV2/databasesTable.tsx#L29)):*
> ```XML
>     render: (_, db: DatabaseRow) => {
>       const encodedDBPath = EncodeDatabaseUri(db.name);
>       // TODO (xzhang: For CC we have to use `${location.pathname}/${db.name}`
> ```

I think if this TODO needs be anywhere, it should be on the `EncodeDatabaseUri` utility function.
___
*[`pkg/ui/workspaces/cluster-ui/src/databasesV2/index.tsx` line 50 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130704#-O6vrhWrDkaax_x0dTgp:-O6vrhWrDkaax_x0dTgq:b-aoyl1y) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2ea60357c4ec7c621a39c0f7403b6a38e03497c/pkg/ui/workspaces/cluster-ui/src/databasesV2/index.tsx#L50)):*
> ```XML
>   const [search, setSearch] = useState<string>("");
>   const [nodeRegions, setNodeRegions] = useState<ReactSelectOption[]>([]);
>   const onNodeRegionsChange = (selected: OptionsType<ReactSelectOption>) => {
> ```

Why not pass `setNodeRegions` directly on the Select Component?
___
*[`pkg/ui/workspaces/cluster-ui/src/databasesV2/utils.ts` line 17 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130704#-O6vqZS2ASgABOQPui9_:-O6vqZS2ASgABOQPui9a:b-j4xduh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2ea60357c4ec7c621a39c0f7403b6a38e03497c/pkg/ui/workspaces/cluster-ui/src/databasesV2/utils.ts#L17)):*
> ```XML
>   filter: DatabaseListFilters,
> ): DatabaseRow[] => {
>   return databases.filter(db => {
> ```

Is it possible to push this filtering down to the API?
___
*[`pkg/ui/workspaces/cluster-ui/src/layouts/pageSection.tsx` line 17 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130704#-O6vu6MS3boiyEoACQbf:-O6vu6MS3boiyEoACQbg:b-gog4hb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2ea60357c4ec7c621a39c0f7403b6a38e03497c/pkg/ui/workspaces/cluster-ui/src/layouts/pageSection.tsx#L17)):*
> ```XML
> const cx = classNames.bind(styles);
> 
> type PageSectionProps = {
> ```

Are we planning on rolling this component out to all the pages?

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130704)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @angles-n-daemons, @dhartunian, and @kyle-a-wong)

___
*[`pkg/ui/workspaces/cluster-ui/src/databasesV2/databasesTable.tsx` line 29 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130704#-O6vt_F44SCT3c1DH5Vh:-O6vwTos9kKS9KZ-xZ32:b-7p159i) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2ea60357c4ec7c621a39c0f7403b6a38e03497c/pkg/ui/workspaces/cluster-ui/src/databasesV2/databasesTable.tsx#L29)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

I think if this TODO needs be anywhere, it should be on the `EncodeDatabaseUri` utility function.
</blockquote></details>

There are other places this function is still being used, so I wanted to keep it to this use case of the function. Also for CC it looks like we weren't using this function in the path. This comment was more to serve as a reminder we haven't handled the CC path yet.
___
*[`pkg/ui/workspaces/cluster-ui/src/databasesV2/index.tsx` line 50 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130704#-O6vrhWrDkaax_x0dTgp:-O6vwu6n8UuR7BIm5ast:b-f61r6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2ea60357c4ec7c621a39c0f7403b6a38e03497c/pkg/ui/workspaces/cluster-ui/src/databasesV2/index.tsx#L50)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

Why not pass `setNodeRegions` directly on the Select Component?
</blockquote></details>

I believe there was a weird typing issue. In any case this part of the code will likely change when we hook it up to live data from the api.
___
*[`pkg/ui/workspaces/cluster-ui/src/databasesV2/utils.ts` line 17 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130704#-O6vqZS2ASgABOQPui9_:-O6vx1HSC2_AHc2-kzV_:b3jweeb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2ea60357c4ec7c621a39c0f7403b6a38e03497c/pkg/ui/workspaces/cluster-ui/src/databasesV2/utils.ts#L17)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

Is it possible to push this filtering down to the API?
</blockquote></details>

Yup, the api will handle this filtering - it's just for the mockup right now. Added tests since it was simple to do and for completion but we didn't really need to.

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130704)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @angles-n-daemons, @dhartunian, and @kyle-a-wong)

___
*[`pkg/ui/workspaces/cluster-ui/src/layouts/pageSection.tsx` line 17 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130704#-O6vu6MS3boiyEoACQbf:-O6vxRmM5_yWmRY0W75E:bn2x238) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2ea60357c4ec7c621a39c0f7403b6a38e03497c/pkg/ui/workspaces/cluster-ui/src/layouts/pageSection.tsx#L17)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

Are we planning on rolling this component out to all the pages?
</blockquote></details>

Oops missed this - yes we're planning on using this in other pages. THey shouldn't need to impor tthe prop types though.

**Review by angles-n-daemons — CHANGES_REQUESTED** [review]
> Reviewed 20 of 20 files at r4, 4 of 4 files at r5, 5 of 5 files at r6, 9 of 9 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130704)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @kyle-a-wong, and @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/databasesV2/databasesTable.tsx` line 56 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/130704#-O6wjmLD8qtFnwQh4OD3:-O6wjmLD8qtFnwQh4OD4:b-paeq98) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f847a20fb92ae5353d6c4cc4be417364284753b/pkg/ui/workspaces/cluster-ui/src/databasesV2/databasesTable.tsx#L56)):*
> ```XML
>     render: (db: DatabaseRow) => (
>       <div>
>         {Object.entries(db.nodesByRegion ?? []).map(([region, nodes]) => (
> ```

one note, for `Object.entries` the default should be an object so the reader knows what type is being handled:

```javascript
Object.entries(possiblyUndefined ?? {}) // note object as the fallback
```

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130704)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @angles-n-daemons, @dhartunian, and @kyle-a-wong)

___
*[`pkg/ui/workspaces/cluster-ui/src/databasesV2/databasesTable.tsx` line 56 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/130704#-O6wjmLD8qtFnwQh4OD3:-O6wkhNt24uBdGmhw33O:bpvtqwo) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f847a20fb92ae5353d6c4cc4be417364284753b/pkg/ui/workspaces/cluster-ui/src/databasesV2/databasesTable.tsx#L56)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

one note, for `Object.entries` the default should be an object so the reader knows what type is being handled:

```javascript
Object.entries(possiblyUndefined ?? {}) // note object as the fallback
```
</blockquote></details>

Ah nice catch Done.

**Review by angles-n-daemons — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130704#-:-O7-hEqC0qgIHU8ZxppD:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dhartunian and @kyle-a-wong)

**Comment by xinhaoz** [comment]
TFTR!
bors r+

**Pull request merged**
