### PR TITLE
opt: add rule expectations to norm rule tests

### PR DESCRIPTION
**Pull request by justinj**
This commit adds assertions that the rules norm tests claim to be
testing actually do test them. There's a couple cases where there was an
easy fix to fix a rule that wasn't actually tested, and some were less
clear and so I added a TODO.

Release note: None.

### CODE REVIEW

**Review by andy-kimball — COMMENTED** [review]
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29658)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 3443 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29658#-LLl8hZs5PgF8XL3Cus7:-LLl8hZs5PgF8XL3Cus8:b8i68pj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e9ad8c448a7ab65ed07cb30e76ccaf9da8dfa37/pkg/sql/opt/norm/testdata/rules/decorrelate#L3443)):*
> ```
> # HoistJoinSubquery
> # --------------------------------------------------
> opt
> ```

I'd rather keep this query in this section by changing `(SELECT k+1) = 0` to `(SELECT k+1) = x`.
___
*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 3542 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29658#-LLl95xB0sAViCeApe4M:-LLl95xB0sAViCeApe4N:bdq8l1e) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e9ad8c448a7ab65ed07cb30e76ccaf9da8dfa37/pkg/sql/opt/norm/testdata/rules/decorrelate#L3542)):*
> ```
> # Any in Join filter disjunction.
> opt
> SELECT j, y FROM a INNER JOIN xy ON x IN (SELECT v FROM uv WHERE u=y) OR x IS NULL
> ```

This one can stay in this section if you update `(SELECT v FROM uv WHERE u=y)` to `(SELECT v FROM uv WHERE u=k)`.
___
*[pkg/sql/opt/norm/testdata/rules/prune_cols, line 1307 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29658#-LLlDB5VDvsCpcerZWEm:-LLlDB5VDvsCpcerZWEn:b-3snink) ([raw file](https://github.com/cockroachdb/cockroach/blob/64bb1d86d31715f5af7ee07bde85a67b39f89856/pkg/sql/opt/norm/testdata/rules/prune_cols#L1307)):*
> ```
> # PruneGroupByCols
> # --------------------------------------------------
> # TODO(justin): none of these tests seem to exercise PruneGroupByCols, figure
> ```

I think these tests stopped exercising the rule when radu re-did groupby compilation in optbuilder.
___
*[pkg/sql/opt/norm/testdata/rules/prune_cols, line 1312 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29658#-LLlEhJq08cY3_476Vsi:-LLlEhJq08cY3_476Vsj:b-tyhzrx) ([raw file](https://github.com/cockroachdb/cockroach/blob/64bb1d86d31715f5af7ee07bde85a67b39f89856/pkg/sql/opt/norm/testdata/rules/prune_cols#L1312)):*
> ```
> # Columns used by grouping or aggregation, but not both should not be pruned.
> opt expect-not=PruneGroupByCols
> SELECT s, sum(i) FROM a GROUP BY s
> ```

Use this:
`SELECT s, sum(i) FROM a GROUP BY s, s||'foo'`
___
*[pkg/sql/opt/norm/testdata/rules/prune_cols, line 1327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29658#-LLlF3qg9MxTrEWUghz6:-LLlF3qg9MxTrEWUghz7:b-8093kf) ([raw file](https://github.com/cockroachdb/cockroach/blob/64bb1d86d31715f5af7ee07bde85a67b39f89856/pkg/sql/opt/norm/testdata/rules/prune_cols#L1327)):*
> ```
> # Columns used by both grouping and aggregation should not be pruned.
> opt expect-not=PruneGroupByCols
> SELECT avg(s::int+i), s, i FROM a GROUP BY s, i
> ```

Use this: `SELECT avg(s::int+i), s, i FROM a GROUP BY s, i, i+1`
___
*[pkg/sql/opt/norm/testdata/rules/prune_cols, line 1347 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29658#-LLlGpMN-2zNKtyU5JUb:-LLlGpMN-2zNKtyU5JUc:b3wgf76) ([raw file](https://github.com/cockroachdb/cockroach/blob/64bb1d86d31715f5af7ee07bde85a67b39f89856/pkg/sql/opt/norm/testdata/rules/prune_cols#L1347)):*
> ```
> # Columns used only by aggregation, no grouping columns.
> opt expect-not=PruneGroupByCols
> SELECT min(i), max(k), max(k) FROM a
> ```

I don't know how to rewrite this test case. However, maybe add this case to the `PruneAggCols` cases instead (and delete this case):
`SELECT min(i), max(k), max(k) FROM a ORDER BY max(f)`
___
*[pkg/sql/opt/norm/testdata/rules/prune_cols, line 1366 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29658#-LLlHLx73O0A4dfunuWw:-LLlHLx73O0A4dfunuWx:buhohsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/64bb1d86d31715f5af7ee07bde85a67b39f89856/pkg/sql/opt/norm/testdata/rules/prune_cols#L1366)):*
> ```
> # Columns used only by groupings, no aggregation columns.
> opt expect-not=PruneGroupByCols
> SELECT s, i+1 AS r FROM a GROUP BY i, s
> ```

`SELECT s, i+1 AS r FROM a GROUP BY i, s, s||'foo'`
___
*[pkg/sql/opt/norm/testdata/rules/prune_cols, line 1381 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29658#-LLlHfS84UgJFX8eMI1N:-LLlHfS84UgJFX8eMI1O:b-d5uuty) ([raw file](https://github.com/cockroachdb/cockroach/blob/64bb1d86d31715f5af7ee07bde85a67b39f89856/pkg/sql/opt/norm/testdata/rules/prune_cols#L1381)):*
> ```
> # Groupby a groupby.
> opt expect-not=PruneGroupByCols
> SELECT min(sm), i FROM (SELECT s, i, sum(k) sm, avg(k) av FROM a GROUP BY i, s) a GROUP BY i
> ```

`SELECT min(sm), i FROM (SELECT s, i, sum(k) sm, avg(k) av FROM a GROUP BY i, s) a GROUP BY i, i+1`
___
*[pkg/sql/opt/norm/testdata/rules/prune_cols, line 1406 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29658#-LLlIQp2E521VARA5zf1:-LLlIQp2E521VARA5zf2:b-ddgn3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/64bb1d86d31715f5af7ee07bde85a67b39f89856/pkg/sql/opt/norm/testdata/rules/prune_cols#L1406)):*
> ```
> # Distinct (GroupBy operator with no aggregates).
> opt expect-not=PruneGroupByCols
> SELECT DISTINCT s, f FROM a
> ```

Maybe switch to this:
`SELECT DISTINCT ON (s, s||'foo') s, f FROM a`

**Review by andy-kimball — COMMENTED** [review]
This has turned out to be very useful. Also gives me comfort that most of our tests are doing what they were originally intended to do.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29658#-:-LLlNguC6Swzi_qFF_xQ:br03uz7)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by rytaft — APPROVED** [review]
> Reviewed 13 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29658)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/testdata/rules/comp, line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29658#-LLoYyUkDqbjqF-PRMij:-LLoYyUkDqbjqF-PRMik:bqhtzne) ([raw file](https://github.com/cockroachdb/cockroach/blob/64bb1d86d31715f5af7ee07bde85a67b39f89856/pkg/sql/opt/norm/testdata/rules/comp#L226)):*
> ```
> 
> # Nested tuples.
> opt expect=NormalizeTupleEquality
> ```

should you add `SimplifyAnd` to this list too?

**Review by rytaft — COMMENTED** [review]
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29658)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by RaduBerinde — APPROVED** [review]
Wow, this is great! Thanks for the tedious work going through all of these, and fixing various cases.

:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29658#-:-LLpyt4s1ZbiCj018VLr:b-ksueyx)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by justinj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29658)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/testdata/rules/comp, line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29658#-LLoYyUkDqbjqF-PRMij:-LM3Z--07MVoINRP0g2H:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64bb1d86d31715f5af7ee07bde85a67b39f89856/pkg/sql/opt/norm/testdata/rules/comp#L226)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

should you add `SimplifyAnd` to this list too?
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 3443 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29658#-LLl8hZs5PgF8XL3Cus7:-LLoY-l20c0j2PiDRH88:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e9ad8c448a7ab65ed07cb30e76ccaf9da8dfa37/pkg/sql/opt/norm/testdata/rules/decorrelate#L3443)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I'd rather keep this query in this section by changing `(SELECT k+1) = 0` to `(SELECT k+1) = x`.
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 3542 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29658#-LLl95xB0sAViCeApe4M:-LLobdyd1gv6KqigS6Ts:bf30w29) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e9ad8c448a7ab65ed07cb30e76ccaf9da8dfa37/pkg/sql/opt/norm/testdata/rules/decorrelate#L3542)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

This one can stay in this section if you update `(SELECT v FROM uv WHERE u=y)` to `(SELECT v FROM uv WHERE u=k)`.
</blockquote></details>

I had to change it a little more, but it works now.
___
*[pkg/sql/opt/norm/testdata/rules/prune_cols, line 1307 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29658#-LLlDB5VDvsCpcerZWEm:-LM3ZNcTDf0b5rh_y2gQ:b-dqlsme) ([raw file](https://github.com/cockroachdb/cockroach/blob/64bb1d86d31715f5af7ee07bde85a67b39f89856/pkg/sql/opt/norm/testdata/rules/prune_cols#L1307)):*
> SELECT s, sum(i) FROM a GROUP BY s, s||'foo'
___
*[pkg/sql/opt/norm/testdata/rules/prune_cols, line 1312 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29658#-LLlEhJq08cY3_476Vsi:-LM3ZOQ12ejAmaebialX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64bb1d86d31715f5af7ee07bde85a67b39f89856/pkg/sql/opt/norm/testdata/rules/prune_cols#L1312)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Use this:
`SELECT s, sum(i) FROM a GROUP BY s, s||'foo'`
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/testdata/rules/prune_cols, line 1327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29658#-LLlF3qg9MxTrEWUghz6:-LM3_9DGBGKdtPAGKVAV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64bb1d86d31715f5af7ee07bde85a67b39f89856/pkg/sql/opt/norm/testdata/rules/prune_cols#L1327)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Use this: `SELECT avg(s::int+i), s, i FROM a GROUP BY s, i, i+1`
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/testdata/rules/prune_cols, line 1347 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29658#-LLlGpMN-2zNKtyU5JUb:-LM3fDxJ5Ds0BOSmzqRk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64bb1d86d31715f5af7ee07bde85a67b39f89856/pkg/sql/opt/norm/testdata/rules/prune_cols#L1347)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I don't know how to rewrite this test case. However, maybe add this case to the `PruneAggCols` cases instead (and delete this case):
`SELECT min(i), max(k), max(k) FROM a ORDER BY max(f)`
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/testdata/rules/prune_cols, line 1366 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29658#-LLlHLx73O0A4dfunuWw:-LM3fZO-99h85NR70A-0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64bb1d86d31715f5af7ee07bde85a67b39f89856/pkg/sql/opt/norm/testdata/rules/prune_cols#L1366)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

`SELECT s, i+1 AS r FROM a GROUP BY i, s, s||'foo'`
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/testdata/rules/prune_cols, line 1381 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29658#-LLlHfS84UgJFX8eMI1N:-LM3fZxwEqbbvei6AvxZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64bb1d86d31715f5af7ee07bde85a67b39f89856/pkg/sql/opt/norm/testdata/rules/prune_cols#L1381)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

`SELECT min(sm), i FROM (SELECT s, i, sum(k) sm, avg(k) av FROM a GROUP BY i, s) a GROUP BY i, i+1`
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/testdata/rules/prune_cols, line 1406 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29658#-LLlIQp2E521VARA5zf1:-LM3frtUC2hY0I4v2rRP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64bb1d86d31715f5af7ee07bde85a67b39f89856/pkg/sql/opt/norm/testdata/rules/prune_cols#L1406)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Maybe switch to this:
`SELECT DISTINCT ON (s, s||'foo') s, f FROM a`
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29658)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29658#-:-LM8L5ut1Llqp6hZ873J:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Comment by justinj** [comment]
TFTRs!

bors r+

**Comment by justinj** [comment]
rebased

bors r+

**Comment by RaduBerinde** [comment]
Backport?

**Pull request merged**
