### PR TITLE
delegate: implement SHOW GRANTS ON SCHEMA

### LINKED ISSUE #53570: sql: support `SHOW GRANTS` on schemas
**Describe the problem**

I expect to be able to `SHOW GRANTS` on schema descriptors.

**To Reproduce**

```sql
SET experimental_enable_user_defined_schemas = true;
CREATE SCHEMA sc;
SHOW GRANTS ON SCHEMA sc;
```

I get:
```
root@127.0.0.1:52942/movr> SHOW GRANTS ON SCHEMA sc;
invalid syntax: statement ignored: at or near "sc": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
 SHOW GRANTS ON SCHEMA sc
```

**Expected behavior**
To show the grants on the schema.

**Environment:**

```
Build Tag:        v20.2.0-alpha.3-650-g3fd6e3b5d3
Build Time:       2020/08/27 18:32:55
Distribution:     CCL
Platform:         darwin amd64 (x86_64-apple-darwin19.5.0)
Go Version:       go1.14.4
C Compiler:       4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.32.62)
Build Commit ID:  3fd6e3b5d3610ee4ed34ab0eca2df932aa6ca8f1
Build Type:       development
```

### PR DESCRIPTION
**Pull request by otan**
Resolves #53570 

Release note (sql change): Implement `SHOW GRANTS ON SCHEMA
<schema_list>`

### CODE REVIEW

**Review by arulajmani — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54420)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @otan)

___
*[pkg/sql/delegate/show_grants.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54420#-MHMhqfCEUmFe0lW_2q1:-MHMhqfCEUmFe0lW_2q2:b-yxzp7e) ([raw file](https://github.com/cockroachdb/cockroach/blob/9efa1de32f19da0432ecce3e24fcb7e4960d5353/pkg/sql/delegate/show_grants.go#L42)):*
> ```Go
>        table_schema AS schema_name,
>        grantee,
>        privilege_type
> ```

nit: Looks like this query is the same as the dbPrivQuery above, can we just construct a single `dbOrSchemaPrivQuery`
___
*[pkg/sql/delegate/show_grants.go, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54420#-MHMlubl4C9T7UvHi015:-MHMlubl4C9T7UvHi016:b1vawo5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9efa1de32f19da0432ecce3e24fcb7e4960d5353/pkg/sql/delegate/show_grants.go#L98)):*
> ```Go
> 				dbName = s.Name().Catalog()
> 			} else if dbName != s.Name().Catalog() {
> 				return nil, errors.AssertionFailedf("schema %q in unexpected database %q", schema, dbName)
> ```

You can fail this assertion by doing the following: 

```

CREATE DATABASE db; CREATE DATABASE test; USE test;

CREATE SCHEMA schema; 

SHOW GRANTS FROM SCHEMA abc, db; 
```

I think the reason for this is https://github.com/cockroachdb/cockroach/blob/2fd9d953c6ae435c20fdb1acce1eb352f37f6234/pkg/sql/sem/tree/name_resolution.go#L448 -- we shouldn't be doing the CRDB 1.1 compat check if the schema is explicit. Might be worth fixing as part of this PR.

**Comment by otan** [comment]
___
*[pkg/sql/delegate/show_grants.go, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54420#-MHMlubl4C9T7UvHi015:-MHMwzvuAkb_kSIar3kt:bgrqcaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9efa1de32f19da0432ecce3e24fcb7e4960d5353/pkg/sql/delegate/show_grants.go#L98)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

You can fail this assertion by doing the following: 

```

CREATE DATABASE db; CREATE DATABASE test; USE test;

CREATE SCHEMA schema; 

SHOW GRANTS FROM SCHEMA abc, db; 
```

I think the reason for this is https://github.com/cockroachdb/cockroach/blob/2fd9d953c6ae435c20fdb1acce1eb352f37f6234/pkg/sql/sem/tree/name_resolution.go#L448 -- we shouldn't be doing the CRDB 1.1 compat check if the schema is explicit. Might be worth fixing as part of this PR. 
</blockquote></details>

I think we still have to do this -- otherwise, some other compatibility is broken.
This is a big change I feel, and one that almost certainly shouldn't be backported.

I'd argue this assertion is still fine given that "SCHEMA" is explicitly specified, adn this works:

```
CREATE DATABASE db; CREATE DATABASE test; USE test;

CREATE SCHEMA schema;  CREATE SCHEMA db;

root@127.0.0.1:63754/test> SHOW GRANTS ON SCHEMA schema, db;
  database_name | schema_name | grantee | privilege_type
----------------+-------------+---------+-----------------
  test          | db          | admin   | ALL
  test          | db          | root    | ALL
  test          | schema      | admin   | ALL
  test          | schema      | root    | ALL
(4 rows)

Server Execution Time: 1.025ms
Network Latency: 187µs
```

**Comment by otan** [comment]
___
*[pkg/sql/delegate/show_grants.go, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54420#-MHMlubl4C9T7UvHi015:-MHNJ3DY4Sq8YTLZZr_u:b-omnhd0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9efa1de32f19da0432ecce3e24fcb7e4960d5353/pkg/sql/delegate/show_grants.go#L98)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

I think we still have to do this -- otherwise, some other compatibility is broken.
This is a big change I feel, and one that almost certainly shouldn't be backported.

I'd argue this assertion is still fine given that "SCHEMA" is explicitly specified, adn this works:

```
CREATE DATABASE db; CREATE DATABASE test; USE test;

CREATE SCHEMA schema;  CREATE SCHEMA db;

root@127.0.0.1:63754/test> SHOW GRANTS ON SCHEMA schema, db;
  database_name | schema_name | grantee | privilege_type
----------------+-------------+---------+-----------------
  test          | db          | admin   | ALL
  test          | db          | root    | ALL
  test          | schema      | admin   | ALL
  test          | schema      | root    | ALL
(4 rows)

Server Execution Time: 1.025ms
Network Latency: 187µs
```
</blockquote></details>

Fixed it a different way!

**Review by arulajmani — APPROVED** [review]
Could you add the test I commented in the logic test now that we've got this working? Otherwise LGTM 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54420#-:-MHO4i3r3LbNNVNF6K2N:b-hj3xyt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/delegate/show_grants.go, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54420#-MHMlubl4C9T7UvHi015:-MHO0_L41kxKGMum5JAr:b-xexmet) ([raw file](https://github.com/cockroachdb/cockroach/blob/9efa1de32f19da0432ecce3e24fcb7e4960d5353/pkg/sql/delegate/show_grants.go#L98)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Fixed it a different way!
</blockquote></details>

Nice! :D 

Didn't realize other compat stuff would break, but doesn't sound too surprising haha

**Comment by otan** [comment]
bors r=arulajmani

**Pull request merged**
