### PR TITLE
util/tracing, sql: surface finished bool in span recordings

### PR DESCRIPTION
**Pull request by angelapwen**
This commit adds a finished boolean value to each span's
recording, as well as a column in the virtual table
`crdb_internal.node_inflight_trace_spans`. There are many
finished spans that are still surfaced in the vtable because they
are part of in-flight traces. This change will allow a user
querying the vtable to filter for unfinished spans.

The finished value is set upon retrieving a span's recording based
off its duration - if the Span's `duration` is -1, the span is
unfinished. (Note that the RecordedSpan's `duration` will not be -1
because it has `duration` set for unfinished spans.)

Release note (sql change): add `finished` column to the virtual
table `crdb_internal.node_inflight_trace_spans` that represents
whether each span has finished or not.

### CODE REVIEW

**Review by irfansharif — COMMENTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59856)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @angelapwen, @knz, and @tbg)

___
*[pkg/sql/crdb_internal.go, line 1146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnm5xL9ogtvTRyHpRC:-MSnm5xL9ogtvTRyHpRD:b1whouo) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/sql/crdb_internal.go#L1146)):*
> ```Go
>   span_id        INT NOT NULL,    -- The span's ID.
>   goroutine_id   INT NOT NULL,    -- The ID of the goroutine on which the span was created.
>   finished       BOOL NOT NULL,   -- True if the span has finished, false otherwise.
> ```

"True if the span has been finished, false otherwise."
___
*[pkg/sql/crdb_internal.go, line 1148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnhh1G83N_T4_7x40l:-MSnhh1G83N_T4_7x40m:btxxorn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/sql/crdb_internal.go#L1148)):*
> ```Go
>   finished       BOOL NOT NULL,   -- True if the span has finished, false otherwise.
>   start_time     TIMESTAMPTZ,     -- The span's start time.
>   duration       INTERVAL,        -- The span's duration, measured by time of 
> ```

From an earlier PR, bit there's something wrong with the phrasing around "measured by time of".
___
*[pkg/sql/logictest/testdata/logic_test/crdb_internal, line 254 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnmbxI3FGTHSvwkdp5:-MSnmbxI3FGTHSvwkdp6:b-so64a7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/sql/logictest/testdata/logic_test/crdb_internal#L254)):*
> ```
> 
> query IIIIBTTT colnames
> SELECT * FROM crdb_internal.node_inflight_trace_spans WHERE span_id < 0
> ```

Feel free to punt it off to a separate commit, or ignore entirely, but is it possible for us to actually test this vtable? I'm not sure if logic tests are the best place for, you're the expert. If this is our only test, all we're testing on is the schema, and not really the underlying machinery.
___
*[pkg/util/tracing/crdbspan.go, line 249 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSni9tbEADXR24UM1q0:-MSni9tbEADXR24UM1q1:bh60g2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/util/tracing/crdbspan.go#L249)):*
> ```Go
> 		StartTime:    s.startTime,
> 		Duration:     s.mu.duration,
> 		Finished:     false,
> ```

We don't need to set anything here, the default value for the unset field is false. If we're wanting to set it for readability (imo we don't need to), I'd prefer setting it in the rs.Duration == -1 block below instead.
___
*[pkg/util/tracing/tracer_test.go, line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnjdg9BiNzmN46HLRH:-MSnjdgA4CBnQa-H8aku:b-4s4g2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/util/tracing/tracer_test.go#L342)):*
> ```Go
> }
> 
> // TestActiveSpanVisitorErrors confirms that the visitor of the Tracer's
> ```

[nit] There's no need to make any changes in this PR, but generally when moving code blocks around (or files), it's a bit better to do "pure movements" in a stand-alone commit, and code-changes in another. The upside of doing so is that it's easy for git to understand what the actual code-changes are, instead of it conflating it with the code movements. That in turn makes the reviewable/github view for PRs easier to read.
___
*[pkg/util/tracing/tracer_test.go, line 371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnjAKW9d5weLXNvtX9:-MSnjAKW9d5weLXNvtXA:b-unvs0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/util/tracing/tracer_test.go#L371)):*
> ```Go
> // representing whether the span is finished; and a sorted list of in-flight
> // span operation names.
> func getSortedActiveSpanOpsWithFinishedFlag(t *testing.T, tr *Tracer) (map[string]bool, []string) {
> ```

In most usages we're using one of the two results. I think it'd be better to simply create _another_ helper instead that returns a map of `operation string -> finished bool` for a given Tracer.
___
*[pkg/util/tracing/tracer_test.go, line 380 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnkmlD0EK6HB-KIKfQ:-MSnkmlD0EK6HB-KIKfR:b-onja1e) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/util/tracing/tracer_test.go#L380)):*
> ```Go
> 		for _, rec := range sp.GetRecording() {
> 			spanOps = append(spanOps, rec.Operation)
> 			activeSpans[rec.Operation] = rec.Finished
> ```

Naming it "activeSpans" where the value for "activeSpan[<span op name] == true" indicates that it's actually inactive, is a bit confusing. This applies for all callers of this helper as well.
___
*[pkg/util/tracing/tracer_test.go, line 433 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnlJ5sD6pwknMPx-yU:-MSnlJ5sD6pwknMPx-yV:bsivjbf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/util/tracing/tracer_test.go#L433)):*
> ```Go
> 
> // TestSpanRecordingFinished verifies that a Span with one or more in-flight
> // child Spans is tracked by the Tracer and that its recording's Fininished
> ```

Typo. Also, how about "TestSpanRecordingFinished verifies that a Finish()ed span's recording indicates that it has, in fact, finished." instead?
___
*[pkg/util/tracing/tracer_test.go, line 435 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnm1jv7ZuuJ3aXrrtz:-MSnm1jwE2a9cxqB9jMv:bds3i29) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/util/tracing/tracer_test.go#L435)):*
> ```Go
> // child Spans is tracked by the Tracer and that its recording's Fininished
> // boolean value is changed when this Span itself finishes.
> func TestSpanRecordingFinished(t *testing.T) {
> ```

Nice test!
___
*[pkg/util/tracing/tracer_test.go, line 450 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnkbdY4c5Rpn5kQg4c:-MSnkbdZ-CYq6_uHBA_W:b-lrhsr4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/util/tracing/tracer_test.go#L450)):*
> ```Go
> 	activeSpanMap, sortedSpanOps := getSortedActiveSpanOpsWithFinishedFlag(t, tr1)
> 	require.Equal(t, []string{"root", "root.child", "root.child.child", "root.child.remotechild"}, sortedSpanOps)
> 	for _, k := range activeSpanMap {
> ```

`for _, finished :=`
___
*[pkg/util/tracing/tracer_test.go, line 457 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnlkBW5JMsJ_bwkYC_:-MSnlkBW5JMsJ_bwkYCa:bfx3j7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/util/tracing/tracer_test.go#L457)):*
> ```Go
> 	activeSpanMap, _ = getSortedActiveSpanOpsWithFinishedFlag(t, tr1)
> 
> 	// Only childChild should have a true boolean flag for finished.
> ```

"Only childChild should appear to have been finished." Ditto for the comments below.
___
*[pkg/util/tracing/tracingpb/recorded_span.proto, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnhIGgAblDnTRM_72F:-MSnhIGgAblDnTRM_72G:b-t7hn2d) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/util/tracing/tracingpb/recorded_span.proto#L60)):*
> ```protobuf
>   // A span whose recording is collected before it's finished will have the
>   // duration set as the "time of collection - start time". Such a span will
>   // have an "unfinished" tag.
> ```

Update this comment to refer to the new proto field below.
___
*[pkg/util/tracing/tracingpb/recorded_span.proto, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnhNaw67FQPCbu5z1D:-MSnhNaw67FQPCbu5z1E:b-luzjl) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/util/tracing/tracingpb/recorded_span.proto#L83)):*
> ```protobuf
>   uint64 goroutine_id = 12 [(gogoproto.customname) = "GoroutineID"];
> 
>   // True if the span has finished, false otherwise.
> ```

"True if the span has been Finish()ed, false otherwise."

**Review by angelapwen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59856)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif, @knz, and @tbg)

___
*[pkg/sql/crdb_internal.go, line 1146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnm5xL9ogtvTRyHpRC:-MSnv3Cf-q9QzuVGKw9j:b-8qzcvd) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/sql/crdb_internal.go#L1146)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

"True if the span has been finished, false otherwise."
</blockquote></details>

Ah okay, going to update it to "True if the span has been Finished()ed, false otherwise." as I think that makes it more clear. 
___
*[pkg/sql/crdb_internal.go, line 1148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnhh1G83N_T4_7x40l:-MSnv8aRASfCHrFoiImh:bufi22t) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/sql/crdb_internal.go#L1148)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

From an earlier PR, bit there's something wrong with the phrasing around "measured by time of".
</blockquote></details>

I think you're right, I meant "calculated by (time of collection - start time)" — will update for this phrasing. 
___
*[pkg/sql/logictest/testdata/logic_test/crdb_internal, line 254 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnmbxI3FGTHSvwkdp5:-MSnzYBG7wQAetdIhCim:bsur6lp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/sql/logictest/testdata/logic_test/crdb_internal#L254)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Feel free to punt it off to a separate commit, or ignore entirely, but is it possible for us to actually test this vtable? I'm not sure if logic tests are the best place for, you're the expert. If this is our only test, all we're testing on is the schema, and not really the underlying machinery.
</blockquote></details>

This is a good question — I had thought that the schema logic tests + the unit tests would cover it but I'll do some digging. 

I think I _could_ write some logic tests but I think they'd be really brittle — the vtable output doesn't feel really stable. I do see a SQL unit test for `crdb_internal.session_trace` that queries the vtable in a unit test [here](https://github.com/cockroachdb/cockroach/blob/8297ccd33a090ca75b1924c8df1d42eae15782d1/pkg/sql/trace_test.go#L76) and later in the same file. I'm not familiar with this pattern and will need to spend some time looking into it. 
___
*[pkg/util/tracing/crdbspan.go, line 249 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSni9tbEADXR24UM1q0:-MSnvQTx3W1OXpoDQ7pD:b-c6fq02) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/util/tracing/crdbspan.go#L249)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

We don't need to set anything here, the default value for the unset field is false. If we're wanting to set it for readability (imo we don't need to), I'd prefer setting it in the rs.Duration == -1 block below instead.
</blockquote></details>

Ah, I actually didn't know the default value for the unset field is false. I prefer setting it for readability but defer to anyone else's opinion here if you feel strongly. 
___
*[pkg/util/tracing/tracer_test.go, line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnjdg9BiNzmN46HLRH:-MSnvcV87rgi-XhEM2K9:b-ccdmiy) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/util/tracing/tracer_test.go#L342)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

[nit] There's no need to make any changes in this PR, but generally when moving code blocks around (or files), it's a bit better to do "pure movements" in a stand-alone commit, and code-changes in another. The upside of doing so is that it's easy for git to understand what the actual code-changes are, instead of it conflating it with the code movements. That in turn makes the reviewable/github view for PRs easier to read.
</blockquote></details>

Ah, okay that makes sense — I noticed the view was difficult to read but didn't realize this was "worth" its own commit. Thanks for letting me know
___
*[pkg/util/tracing/tracer_test.go, line 371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnjAKW9d5weLXNvtX9:-MSnvjnX22bBY37W9qck:b2n6noo) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/util/tracing/tracer_test.go#L371)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

In most usages we're using one of the two results. I think it'd be better to simply create _another_ helper instead that returns a map of `operation string -> finished bool` for a given Tracer.
</blockquote></details>

This makes sense! I like that. Somehow I hadn't even considered that
___
*[pkg/util/tracing/tracer_test.go, line 380 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnkmlD0EK6HB-KIKfQ:-MSnwuzl4xwO8TlVcSNh:beuq0nn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/util/tracing/tracer_test.go#L380)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Naming it "activeSpans" where the value for "activeSpan[<span op name] == true" indicates that it's actually inactive, is a bit confusing. This applies for all callers of this helper as well.
</blockquote></details>

Yeah, you're right. I think the confusion is that they are "spans in active traces" and not necessarily "active spans." I've renamed the helpers to `getSortedSpanOpsInActiveTraces` and `getSpanOpsInActiveTracesWithFinishedFlag` which are kind of mouthfuls but are more precise.
___
*[pkg/util/tracing/tracer_test.go, line 433 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnlJ5sD6pwknMPx-yU:-MSnxsTT0ZWHuDoA_3Ox:b-5jedff) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/util/tracing/tracer_test.go#L433)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Typo. Also, how about "TestSpanRecordingFinished verifies that a Finish()ed span's recording indicates that it has, in fact, finished." instead?
</blockquote></details>

Yep, sounds good! 
___
*[pkg/util/tracing/tracer_test.go, line 435 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnm1jv7ZuuJ3aXrrtz:-MSnyQC8Blfv1kA5KBvG:b75055h) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/util/tracing/tracer_test.go#L435)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Nice test!
</blockquote></details>

Thank you :) 
___
*[pkg/util/tracing/tracer_test.go, line 450 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnkbdY4c5Rpn5kQg4c:-MSnz6En6rb3rLP6BaCv:b-b5jitv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/util/tracing/tracer_test.go#L450)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

`for _, finished :=`
</blockquote></details>

Done! Good call. 
___
*[pkg/util/tracing/tracer_test.go, line 457 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnlkBW5JMsJ_bwkYC_:-MSnzCHT7gAJffcjOxbp:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/util/tracing/tracer_test.go#L457)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

"Only childChild should appear to have been finished." Ditto for the comments below.
</blockquote></details>

Done
___
*[pkg/util/tracing/tracingpb/recorded_span.proto, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnhIGgAblDnTRM_72F:-MSnzKZn4pSuMzxDSpnI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/util/tracing/tracingpb/recorded_span.proto#L60)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Update this comment to refer to the new proto field below.
</blockquote></details>

Done.
___
*[pkg/util/tracing/tracingpb/recorded_span.proto, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnhNaw67FQPCbu5z1D:-MSnzE3--iRO3KITe61z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/util/tracing/tracingpb/recorded_span.proto#L83)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

"True if the span has been Finish()ed, false otherwise."
</blockquote></details>

Done.

**Review by irfansharif — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-:-MSoCWCc3WD28frDwFwv:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @angelapwen, @irfansharif, @knz, and @tbg)

___
*[pkg/sql/crdb_internal.go, line 1148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnhh1G83N_T4_7x40l:-MSo8aAp8a-1XAZwBptE:b-hokfzl) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/sql/crdb_internal.go#L1148)):*
[mega pedantic nit] I like the phrasing we're using in RecordedSpan:

> The span's duration, measured from start to Finish(). A span whose recording is collected before it's finished will have the duration set as the "time of collection - start time".
___
*[pkg/sql/logictest/testdata/logic_test/crdb_internal, line 254 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnmbxI3FGTHSvwkdp5:-MSo9Spf5PEDEcZKZSN2:b39fi7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/sql/logictest/testdata/logic_test/crdb_internal#L254)):*
<details><summary><i>Previously, angelapwen (Angela P Wen) wrote…</i></summary><blockquote>

This is a good question — I had thought that the schema logic tests + the unit tests would cover it but I'll do some digging. 

I think I _could_ write some logic tests but I think they'd be really brittle — the vtable output doesn't feel really stable. I do see a SQL unit test for `crdb_internal.session_trace` that queries the vtable in a unit test [here](https://github.com/cockroachdb/cockroach/blob/8297ccd33a090ca75b1924c8df1d42eae15782d1/pkg/sql/trace_test.go#L76) and later in the same file. I'm not familiar with this pattern and will need to spend some time looking into it. 
</blockquote></details>

Sounds good, feel free to file a placeholder issue so you don't lose track of this thread.
___
*[pkg/util/tracing/tracer_test.go, line 380 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnkmlD0EK6HB-KIKfQ:-MSoBlbe5C7nqGrt4orR:b-5317fx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/util/tracing/tracer_test.go#L380)):*
<details><summary><i>Previously, angelapwen (Angela P Wen) wrote…</i></summary><blockquote>

Yeah, you're right. I think the confusion is that they are "spans in active traces" and not necessarily "active spans." I've renamed the helpers to `getSortedSpanOpsInActiveTraces` and `getSpanOpsInActiveTracesWithFinishedFlag` which are kind of mouthfuls but are more precise.
</blockquote></details>

[nit, more pedanticity] I think we'd be fine if we just dropped "in active traces" from all these signatures and variable names. Saying that we're dealing with "active traces" doesn't really say much (are we comparing it against inactive traces?), and like you said, can make it all a bit of a mouthful. These are all tests anyway, so some brevity seems ok. 

It also begs the question: what's an "active" trace with all "finished" spans, or none at all? Better to just dodge the whole thing by making no mention of "active", if possible (I'm thinking `getSortedSpanOps`, `getSpanOpsWithFinished`)

I kind of feel the same way about "inflight" (vtable name), but that's for some other time. Generally I think reducing the amount of terminology we're using is a Good Thing (TM).
___
*[pkg/util/tracing/tracingpb/recorded_span.proto, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnhIGgAblDnTRM_72F:-MSo8RSV4Xl9PtM_6PkK:b-irf21k) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/util/tracing/tracingpb/recorded_span.proto#L60)):*
<details><summary><i>Previously, angelapwen (Angela P Wen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

(Did you mean to push up a diff here?)

**Review by angelapwen — COMMENTED** [review]
Thanks for the review :small_airplane: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-:-MSoLi793nASGzZspLIl:b-z2bxi)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif, @knz, and @tbg)

___
*[pkg/sql/crdb_internal.go, line 1148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnhh1G83N_T4_7x40l:-MSoFX8J-zNBrpcmmCQI:b-5311na) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/sql/crdb_internal.go#L1148)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

[mega pedantic nit] I like the phrasing we're using in RecordedSpan:

> The span's duration, measured from start to Finish(). A span whose recording is collected before it's finished will have the duration set as the "time of collection - start time".

</blockquote></details>

Actually, that's a really good idea. When I'd originally written this comment I didn't realize that the table surfaced finished spans and the original comment wasn't accurate for finished spans. Updating. 
___
*[pkg/sql/logictest/testdata/logic_test/crdb_internal, line 254 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnmbxI3FGTHSvwkdp5:-MSoFjPDEOcuSvXMhm6R:b-9x13ra) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/sql/logictest/testdata/logic_test/crdb_internal#L254)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Sounds good, feel free to file a placeholder issue so you don't lose track of this thread.
</blockquote></details>

Done, thanks, tracked in #59873
___
*[pkg/util/tracing/tracer_test.go, line 380 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnkmlD0EK6HB-KIKfQ:-MSoFp1s24i5E-VImheM:bdrlac3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/util/tracing/tracer_test.go#L380)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

[nit, more pedanticity] I think we'd be fine if we just dropped "in active traces" from all these signatures and variable names. Saying that we're dealing with "active traces" doesn't really say much (are we comparing it against inactive traces?), and like you said, can make it all a bit of a mouthful. These are all tests anyway, so some brevity seems ok. 

It also begs the question: what's an "active" trace with all "finished" spans, or none at all? Better to just dodge the whole thing by making no mention of "active", if possible (I'm thinking `getSortedSpanOps`, `getSpanOpsWithFinished`)

I kind of feel the same way about "inflight" (vtable name), but that's for some other time. Generally I think reducing the amount of terminology we're using is a Good Thing (TM).
</blockquote></details>

I love these discussions! In this case, an "active" trace with all "finished" spans ...doesn't exist as it would disappear from the list of span operations. I guess this is not quite the spirit of what we would like to define "active" traces as. 

I'll drop the mention of active traces here. 
___
*[pkg/util/tracing/tracingpb/recorded_span.proto, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnhIGgAblDnTRM_72F:-MSoF49z635T4NGILRbU:beczye8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/util/tracing/tracingpb/recorded_span.proto#L60)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

(Did you mean to push up a diff here?)
</blockquote></details>

Ah yes I did!! Thanks.

**Review by irfansharif — COMMENTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59856)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @angelapwen, @irfansharif, @knz, and @tbg)

___
*[pkg/util/tracing/tracer_test.go, line 466 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSoP8QA64_zMNjazRvL:-MSoP8QA64_zMNjazRvM:b-3whi66) ([raw file](https://github.com/cockroachdb/cockroach/blob/35bae524ae506d0c470779b56e8a83088c5e8013/pkg/util/tracing/tracer_test.go#L466)):*
> ```Go
> 
> 	// Only childChild should appear to have finished.
> 	require.False(t, activeSpanMap["root"])
> ```

[nit] spanOpToFinished would read better (and avoid the confusing use of "active" + the double negation + avoid using "Map" in the name)
```
require.True(t, spanOpToFinished["root.child.child"])
```
___
*[pkg/util/tracing/tracingpb/recorded_span.proto, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnhIGgAblDnTRM_72F:-MSoOXtn0qjnJLharMm4:bbq4u1e) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/util/tracing/tracingpb/recorded_span.proto#L60)):*
<details><summary><i>Previously, angelapwen (Angela P Wen) wrote…</i></summary><blockquote>

Ah yes I did!! Thanks. 
</blockquote></details>

I'd drop the "field 13". This comment gets rendered as a go comment in recorded_span.pb.go, and the field tag is meaningless there.

**Review by angelapwen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59856)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @irfansharif, @knz, and @tbg)

___
*[pkg/util/tracing/tracer_test.go, line 466 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSoP8QA64_zMNjazRvL:-MSoSrgu-IhwyYf6pHFq:b-3d3rvr) ([raw file](https://github.com/cockroachdb/cockroach/blob/35bae524ae506d0c470779b56e8a83088c5e8013/pkg/util/tracing/tracer_test.go#L466)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

[nit] spanOpToFinished would read better (and avoid the confusing use of "active" + the double negation + avoid using "Map" in the name)
```
require.True(t, spanOpToFinished["root.child.child"])
```
</blockquote></details>

Yep, that makes sense — I named it `spanOpsWithFinished` to align better with the helper method name but I do agree that `To` describes the map better :thinking: I've more often seen `With` used in CRDB in this case though.
___
*[pkg/util/tracing/tracingpb/recorded_span.proto, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59856#-MSnhIGgAblDnTRM_72F:-MSoT7ssBWzDekJAeOJN:bs7wubq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe50c34aef13b5dbd067acd20844f85bbc81659/pkg/util/tracing/tracingpb/recorded_span.proto#L60)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

I'd drop the "field 13". This comment gets rendered as a go comment in recorded_span.pb.go, and the field tag is meaningless there.
</blockquote></details>

Done!

**Comment by tbg** [comment]
Only skimmed since Irfan's got you covered, but looks good!

**Comment by angelapwen** [comment]
bors=irfansharif,tbg

**Comment by angelapwen** [comment]
bors r=irfansharif,tbg

**Comment by angelapwen** [comment]
bors r=irfansharif,tbg

Flaky test, I believe 🍂

**Pull request merged**
