### PR TITLE
scplan: validate opgen declarations

### PR DESCRIPTION
**Pull request by postamar**
Previously it was all too easy to register an incomplete set of
operation edges for a given element. This commit fixes this by making
the registration more constrained and augmented with validation checks.
This now guarantees that all declared elements have operation edges
defined for them, both in the adding and the dropping directions, and
that these subgraphs have the desired properties of having ABSENT and
PUBLIC as the source and sink, and vice versa.

This required introducing a NotImplemented operation to satisfy these
new requirements with our partial implementation of schema changes.

Release note: None

### CODE REVIEW

**Comment by postamar** [comment]
This is still a work-in-progress, some tests are still failing. This is because we're trying to do stuff like mark _all_ columns from a table as write-only (descriptor validation doesn't like that!). Presumably we can prevent this from happening with a mixture of dep and opt rules?

**Comment by postamar** [comment]
Force-pushed to fix merge conflicts following the borsing of the public schema descriptor PR.

**Review by ajwerner — APPROVED** [review]
:lgtm:

I'm cool with this mod the bugs. Any further tightening can happen later. 

> Reviewed 3 of 54 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73325#-:-MpqkOAw5KAj2LPdS8lW:b-e8nfsm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @fqazi and @postamar)

___
*[pkg/sql/schemachanger/scplan/testdata/drop_table, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73325#-MpqTvgI0ZZ5nUoEFxvD:-MpqTvgI0ZZ5nUoEFxvE:ba46dbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/be8818a71e840dd5e52e15f267c35cee86f70d57/pkg/sql/schemachanger/scplan/testdata/drop_table#L47)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     [Owner:{DescID: 57}, PUBLIC, DROP] -> ABSENT
>     [UserPrivileges:{DescID: 57, Username: admin}, PUBLIC, DROP] -> ABSENT
>     [UserPrivileges:{DescID: 57, Username: public}, PUBLIC, DROP] -> ABSENT
>     [UserPrivileges:{DescID: 57, Username: root}, PUBLIC, DROP] -> ABSENT
> ```
</details>

How do you feel about making all of these depend on the descriptor being already `TXN_DROPPED` if we're dropping the descriptor?  
___
*[pkg/sql/schemachanger/scplan/testdata/drop_table, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73325#-MpqUJGe1l71I0S-EM5h:-MpqUJGe1l71I0S-EM5i:b7zq4fk) ([raw file](https://github.com/cockroachdb/cockroach/blob/be8818a71e840dd5e52e15f267c35cee86f70d57/pkg/sql/schemachanger/scplan/testdata/drop_table#L78)):*
> ```
>     [Column:{DescID: 57, ColumnID: 1}, DELETE_AND_WRITE_ONLY, DROP] -> DELETE_ONLY
>     [DefaultExpression:{DescID: 57, ColumnID: 1}, PUBLIC, DROP] -> ABSENT
>     [Column:{DescID: 57, ColumnID: 2}, DELETE_AND_WRITE_ONLY, DROP] -> DELETE_ONLY
> ```
This is arguably incorrect but it's subtle why. Or, rather, it may not be incorrect in this drop case, but I think it still subtly is. Any changes which happen to a descriptor between the `Statement` phase and the `PreCommit` phase will never be visible to any other node as they will commit as though they happened atomically (they are in the same transaction). The reason we don't do ~everything in just the statement phase is itself almost an optimization. It was the phase constraints which were preventing the column from being moved to `DELETE_ONLY` before the transaction committed.

**Pull request merged**
