### PR TITLE
cherrypick-1.1: build/deploy: install root CAs in docker image

### LINKED ISSUE #18905: build/deploy: missing ca certificates
Attempting to run a BACKUP from the deploy docker image:

```
x509: failed to load system roots and no roots provided
```

I think deploy/Dockerfile just needs `RUN apt-get update && apt-get -y upgrade && apt-get install -y ca-certificates`

But I can't test it because of #18904

### PR DESCRIPTION
**Pull request by madelynnblue**
Fixes #18905 
Cherrypick of #18951

### CODE REVIEW

**Review by a-robinson — APPROVED** [review]

**Comment by bdarnell** [comment]
Since docker caches/reuses intermediate layers, how do we ensure that each release has the latest CA certs at the time it is built?

**Comment by benesch** [comment]
StackOverflow suggests something like this: https://github.com/moby/moby/issues/1996#issuecomment-185872769

**Comment by a-robinson** [comment]
That'd be nice, or just using `docker build --no-cache`. Although is this a problem in practice given that our releases are built on ephemeral teamcity workers?

**Comment by bdarnell** [comment]
If the teamcity workers are sufficiently isolated, we may be fine here, but we should probably add `--no-cache` to be safe on the `docker build` commands for releases.

**Comment by benesch** [comment]
Just for posterity: TeamCity workers are intentionally *not* isolated so that e.g. a build will not need to redownload the builder image if it's running on an agent that's previously run a build with the same builder image version. Less of a concern with releases, since we release once a week and agents rarely survive longer than a day, but still not a guarantee.

**Pull request merged**
