### PR TITLE
jobs: remove deprecated 20.1/20.2 migration code

### LINKED ISSUE #54251: jobs: remove the deprecated mixed 20.1/20.2 code paths
There are "deprecated" functions that refer to this issue (X-anchored-telemetry).

This code should be removed and then this issue closed.

### PR DESCRIPTION
**Pull request by ajwerner**
This set of commits removes the jobs code related to node-liveness epoch based leasing. This has now all been replaced by sqlliveness. This formally frees the jobs package of the node liveness dependency. There's a small commit to remove a bad method, `NewJob`. 

Fixes https://github.com/cockroachdb/cockroach/issues/54251.

Release justification: low risk, high benefit changes to existing functionality

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Looks like the main thing that I added in #62781 but on a quick glance I don't see in this PR is the removal of several unit tests that instantiate CRDB 20.1 cluster. My guess is those could be safely removed or possibly reworked to the new jobs infra.

**Comment by ajwerner** [comment]
@dt my sense is that you're the most familiar with what I'm getting rid of. Also, I did kill some tests with this.

**Review by ajwerner — COMMENTED** [review]
@sajjadrizvi maybe you'd now be interested in giving this a look? It will give you some context on the history and will clean up some code you are currently touching. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61417#-:-MbdWQCeCmurzQQC2_ak:b-2jw13m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

**Comment by ajwerner** [comment]
@dt gentle ping or if you're too busy, I'll look elsewhere. @yuzefovich given you typed one of these up, interested in giving me a stamp?

**Review by yuzefovich — APPROVED** [review]
:lgtm: just some nits from me.

super nit: release justifications aren't needed.

> Reviewed 2 of 2 files at r1, 4 of 4 files at r2, 20 of 20 files at r3, 5 of 5 files at r4, 7 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61417#-:-McAMVe2756mTIZlDD-4:b-e3pp11)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @dt)

___
*[pkg/jobs/deprecated.go, line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61417#-McAO2LDEgzkKgBmk0RN:-McAO2LDEgzkKgBmk0RO:b9w9x69) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a61eb767e9d02a01fbbd3c8fd0ebcb7388c3acd/pkg/jobs/deprecated.go#L41)):*
> ```Go
> 	// reschedule a job.  Visible for testing.
> 	LeniencySetting = settings.RegisterDurationSetting(
> 		"jobs.registry.leniency",
> ```

Deleted cluster settings should be added to `settings/registry.go`.
___
*[pkg/jobs/jobs_test.go, line 1191 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61417#-McANFlnDsM9T0vH-FRZ:-McANFlnDsM9T0vH-FR_:bhjy23y) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bf9d4590764a15ea03bd454ac22a8305409162f/pkg/jobs/jobs_test.go#L1191)):*
> ```Go
> 			}
> 		}()
> 		_, _ = registry.CreateAdoptableJobWithTxn(ctx, jobs.Record{
> ```

nit: why the returned `err` is ignored?
___
*[pkg/jobs/registry.go, line 446 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61417#-McAOSXz-aD7YOqRfamx:-McAOSXz-aD7YOqRfamy:bn5xc9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1ce064636e5490903bd3d794554d6ea27a4128b/pkg/jobs/registry.go#L446)):*
> ```Go
> 			return err
> 		}
> 		// Set createdByType and createdByID to NULL if we don't know them.a
> ```

nit: `s/them.a/them./`.
___
*[pkg/jobs/registry.go, line 453 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61417#-McAPBjT0689lUFstnpT:-McAPBjT0689lUFstnpU:b4ryy3p) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1ce064636e5490903bd3d794554d6ea27a4128b/pkg/jobs/registry.go#L453)):*
> ```Go
> 		}
> 
> 		// If there's no session then we know that the sqlliveness subsystem hasn't
> ```

super nit: as a newcomer to this code, I'm confused by this comment, maybe expand it to make it more explicitly what is the goal of the comment?
___
*[pkg/jobs/registry.go, line 779 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61417#-McAPX3JDSyO5GMDidSH:-McAPX3JDSyO5GMDidSI:b-vb28a0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1ce064636e5490903bd3d794554d6ea27a4128b/pkg/jobs/registry.go#L779)):*
> ```Go
> 	r.mu.Lock()
> 	defer r.mu.Unlock()
> 	// If the cluster is finalized, kill any remaining legacy jobs. They will be
> ```

nit: should this comment be removed too?
___
*[pkg/sql/crdb_internal.go, line 720 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61417#-McAQoAu-KWay1qJb2gb:-McAQoAu-KWay1qJb2gc:b-69zapx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4facd7bc7176709591130d79aa08bc2c34da8d2e/pkg/sql/crdb_internal.go#L720)):*
> ```Go
> 						// Silently swallow the error for checking for liveness.
> 					} else if instanceID, ok := instanceID.(*tree.DInt); ok && isAlive {
> 						leaseNode = instanceID
> ```

nit: maybe rename `leaseNode` to `coordinatorID` to be in line with the column name in the schema?

**Comment by dt** [comment]
@ajwerner sorry I didn't give this a pass before I was OOO last week. I don't actually have any particular expertise or background on the adoption/registry code, so given @yuzefovich has given it a pass, I donno if I have anything really to add

**Review by ajwerner — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61417#-:-McDFe9YCiWunsbe-Tjj:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dt and @yuzefovich)

___
*[pkg/jobs/deprecated.go, line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61417#-McAO2LDEgzkKgBmk0RN:-McDDlkR-plMDpZVfGrK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a61eb767e9d02a01fbbd3c8fd0ebcb7388c3acd/pkg/jobs/deprecated.go#L41)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Deleted cluster settings should be added to `settings/registry.go`.
</blockquote></details>

Done.
___
*[pkg/jobs/jobs_test.go, line 1191 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61417#-McANFlnDsM9T0vH-FRZ:-McDEvANCkM_89WbYV8z:b-f8sf1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bf9d4590764a15ea03bd454ac22a8305409162f/pkg/jobs/jobs_test.go#L1191)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: why the returned `err` is ignored?
</blockquote></details>

Added a comment.
___
*[pkg/jobs/registry.go, line 446 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61417#-McAOSXz-aD7YOqRfamx:-McDE3-32ZWw64OHFi7z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1ce064636e5490903bd3d794554d6ea27a4128b/pkg/jobs/registry.go#L446)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `s/them.a/them./`.
</blockquote></details>

Done.
___
*[pkg/jobs/registry.go, line 453 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61417#-McAPBjT0689lUFstnpT:-McDEDxX-zKFTW8F6OMV:bvzn8fl) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1ce064636e5490903bd3d794554d6ea27a4128b/pkg/jobs/registry.go#L453)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

super nit: as a newcomer to this code, I'm confused by this comment, maybe expand it to make it more explicitly what is the goal of the comment?
</blockquote></details>

That comment was also stale. Updated.
___
*[pkg/sql/crdb_internal.go, line 720 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61417#-McAQoAu-KWay1qJb2gb:-McDFaj02rgyc-6X679k:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4facd7bc7176709591130d79aa08bc2c34da8d2e/pkg/sql/crdb_internal.go#L720)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: maybe rename `leaseNode` to `coordinatorID` to be in line with the column name in the schema?
</blockquote></details>

Done.

**Comment by ajwerner** [comment]
bors r=yuzefovich

**Pull request merged**
