### PR TITLE
workload/tpch: properly enable checks

### PR DESCRIPTION
**Pull request by remysucre**
Commit #64174 renamed disable-checks to enable-checks, but the disableChecks
variable is still handled as before. This commit changes the variable to
enableChecks as well as the code that uses it.

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Nice catch! I think what #64174 missed was to update the default value for `enable-checks` flag (we should have made it `true`) since the logic of using `disableChecks` variable was correct. But overall your change does look cleaner, so thank you!

I only have a nit.

Also the linter fails with:
```
    lint_test.go:1362: 
        /go/src/github.com/cockroachdb/cockroach/pkg/workload/tpch/tpch.go
        diff -u /go/src/github.com/cockroachdb/cockroach/pkg/workload/tpch/tpch.go.orig /go/src/github.com/cockroachdb/cockroach/pkg/workload/tpch/tpch.go
        --- /go/src/github.com/cockroachdb/cockroach/pkg/workload/tpch/tpch.go.orig	2021-10-20 01:55:17.622473558 +0000
        +++ /go/src/github.com/cockroachdb/cockroach/pkg/workload/tpch/tpch.go	2021-10-20 01:55:17.622473558 +0000
        @@ -61,7 +61,7 @@
         	scaleFactor int
         	fks         bool
         
        -	enableChecks              bool
        +	enableChecks               bool
         	vectorize                  string
         	useClusterVectorizeSetting bool
         	verbose                    bool
    --- FAIL: TestLint/TestGofmtSimplify (22.34s)
```

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71741#-:-MmTw5YE6RdNtAhS_MM8:b2tj9js)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @remysucre)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71741#-MmTwyiQ5nu6iUS5a0yU):*
nit: the commit message should have a title with the package name prepended and with no capitalization. We also want to say there is no release note associated with this commit.

How about something like:
```
workload/tpch: properly enable checks

Release note: None
```
You might also want to include a short description in the body describing this change. If you do, please wrap the lines at 80 characters.

Once you've updated the commit message, we usually just use that to fill in the PR description and the title.

**Comment by yuzefovich** [comment]
I adjusted the PR title and description to match the commit.

Thanks for your contribution!

bors r+

**Comment by yuzefovich** [comment]
Seems like a flake.

bors r+

**Comment by yuzefovich** [comment]
A different flake.

bors r=yuzefovich

**Comment by otan** [comment]
courtesy

bors r=yuzefovich

**Pull request merged**
