### PR TITLE
upgrades: flatten permanent upgrades

### PR DESCRIPTION
**Pull request by dt**
This switches the permanent migrations system from allowing
any migration to be considered permanent to having exactly two
'bootstrap' migrations, one for system tenants specifically and
one for all clusters.

This single bootstrap job can be edited in place to add addition bootstrap
steps, such as creating a new singleton job, as needed, _along side_ a
regular migration that performs the same task during upgrades, typically by
calling the same function in both places. This should simplify bootstrap by
having only one or two jobs to run, instead of some unbounded number.

Release note: none.
Epic: none.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
So much simpler, thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119142#-:-NqZ2aTg-Wd7MJ44jMon:b-uu3p0o)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt and @stevendanna)

___
*[`pkg/upgrade/upgrades/upgrades.go` line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119142#-NqZ2BHbAZ76PmsGA8IV:-NqZ2BHbAZ76PmsGA8IW:b-e5mddl) ([raw file](https://github.com/cockroachdb/cockroach/blob/d95ca14594ce8ac8d02e31b1853be28f644cafdb/pkg/upgrade/upgrades/upgrades.go#L70)):*
> ```Go
> 	upgrade.NewPermanentSystemUpgrade(
> 		"populate initial version cluster setting table entry",
> 		clusterversion.VPrimordial3.Version(),
> ```

We should remove all the cluster settings that are no longer used (and remove the commentary around Permanent upgrades in `cockroach_versions.go`).

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119142)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @stevendanna)

___
*[`pkg/upgrade/upgrades/upgrades.go` line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119142#-NqZ2BHbAZ76PmsGA8IV:-NqZKh4K8KDPOBlH3lwU:b-isgn01) ([raw file](https://github.com/cockroachdb/cockroach/blob/d95ca14594ce8ac8d02e31b1853be28f644cafdb/pkg/upgrade/upgrades/upgrades.go#L70)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We should remove all the cluster settings that are no longer used (and remove the commentary around Permanent upgrades in `cockroach_versions.go`).
</blockquote></details>

Which cluster settings are no longer used?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119142)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @stevendanna)

___
*[`pkg/upgrade/upgrades/upgrades.go` line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119142#-NqZ2BHbAZ76PmsGA8IV:-NqbrDjxAYU71mMNeswo:b-adseey) ([raw file](https://github.com/cockroachdb/cockroach/blob/d95ca14594ce8ac8d02e31b1853be28f644cafdb/pkg/upgrade/upgrades/upgrades.go#L70)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Bleh, I meant cluster versions
</blockquote></details>

Ah, makes sense, removed.  Just glad to know there aren't some extra cluster settings relating to upgrade execution.

**Review by stevendanna — COMMENTED** [review]
This looks good. I wonder if we want to add a documentation comment somewhere explaining what you need to do when you think you need to modified the bootstrap migrations.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1, 1 of 1 files at r5, 4 of 6 files at r7, 1 of 3 files at r8, 4 of 5 files at r10, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119142#-:-Nqc17mi2nxb_ZMtTaYm:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dt)

___
*[`pkg/clusterversion/cockroach_versions.go` line 173 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/119142#-Nqc0nXBBSxPnvwI9XrH:-Nqc0nXBBSxPnvwI9XrI:b-s2czb0) ([raw file](https://github.com/cockroachdb/cockroach/blob/80897631ae83ea2429502418843195ee8f861839/pkg/clusterversion/cockroach_versions.go#L173)):*
> ```Go
> 	// VBootstrap versions are associated with bootstrap steps; no new bootstrap
> 	// versions should be added, as the two bootstrap functions are extended as
> 	// needed in-place.
> ```

[nit] maybe add a pointer to where the bootstrap steps are defined
___
*[`pkg/upgrade/upgrades/permanent_upgrades.go` line 36 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119142#-Nqc06_u01Nei_Um-OTk:-Nqc06_u01Nei_Um-OTl:b4m75gj) ([raw file](https://github.com/cockroachdb/cockroach/blob/71fe15f568c9a54f07b1ddbec70539cc6f57d874/pkg/upgrade/upgrades/permanent_upgrades.go#L36)):*
> ```Go
> 	ctx context.Context, cv clusterversion.ClusterVersion, deps upgrade.SystemDeps,
> ) error {
> 	for _, fn := range []upgrade.SystemUpgradeFunc{
> ```

[nit] I would make this a global variable and add a comment explaining when it is appropriate to add something here.
___
*[`pkg/upgrade/upgrades/permanent_upgrades.go` line 57 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119142#-Nqc0FXj2egKlHC1QueO:-Nqc0FXj2egKlHC1QueP:b-fyetn7) ([raw file](https://github.com/cockroachdb/cockroach/blob/71fe15f568c9a54f07b1ddbec70539cc6f57d874/pkg/upgrade/upgrades/permanent_upgrades.go#L57)):*
> ```Go
> ) error {
> 	for _, u := range []bootstrapStep{
> 		{"add users and roles", addRootUser},
> ```

[nit] ditto, and what's with the unused strings?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119142)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

___
*[`pkg/upgrade/upgrades/permanent_upgrades.go` line 36 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119142#-Nqc06_u01Nei_Um-OTk:-NqcL0BB2wM4YztTIKcP:b6ruh2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/71fe15f568c9a54f07b1ddbec70539cc6f57d874/pkg/upgrade/upgrades/permanent_upgrades.go#L36)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I would make this a global variable and add a comment explaining when it is appropriate to add something here.
</blockquote></details>

I tried pulling this into its own var and commenting on it, but the commentary ended up duplicative with the comment on the functions that ran through the list. I think I want comments on the functions, so I went back to inline lists but with the function comments speaking to the lists they contain. WDYT?
___
*[`pkg/upgrade/upgrades/permanent_upgrades.go` line 57 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119142#-Nqc0FXj2egKlHC1QueO:-NqcEcKeAp5RIJ2jJDsj:by5318) ([raw file](https://github.com/cockroachdb/cockroach/blob/71fe15f568c9a54f07b1ddbec70539cc6f57d874/pkg/upgrade/upgrades/permanent_upgrades.go#L57)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] ditto, and what's with the unused strings?
</blockquote></details>

We had these string names before that documented what each step was doing and I didn't want to lose them, just in case we later decide to e.g. update the job status between steps to reflect which step is running at any given time.

I'll log.Info them for now so they're not unused.

**Review by RaduBerinde — APPROVED** [review]
:lgtm_strong:   Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119142#-:-NqdMyXg6YjzvEkZ4PNd:b-rc30b)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dt)

___
*[`pkg/upgrade/upgrades/permanent_upgrades.go` line 36 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119142#-Nqc06_u01Nei_Um-OTk:-NqdMlUfE7P56rOtK3zr:b-qbxl94) ([raw file](https://github.com/cockroachdb/cockroach/blob/71fe15f568c9a54f07b1ddbec70539cc6f57d874/pkg/upgrade/upgrades/permanent_upgrades.go#L36)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I tried pulling this into its own var and commenting on it, but the commentary ended up duplicative with the comment on the functions that ran through the list. I think I want comments on the functions, so I went back to inline lists but with the function comments speaking to the lists they contain. WDYT?
</blockquote></details>

Looks great, thanks!

**Comment by dt** [comment]
TFTR!

bors r+

**Pull request merged**
