### PR TITLE
sql: add support for oid typecasts

### LINKED ISSUE #9990: sql: Fully support Postgres-style Object Identifier Types
See https://www.postgresql.org/docs/9.6/static/datatype-oid.html for context.

Up until now, I've been simply aliasing all object identifier types to `INT`. This works fine for the primary use case of joining on OIDs, but does not work if clients try to use the crazy "cast-as-subquery" functionality. These operations look like casts but actually perform an intelligent subquery on a `pg_catalog` table. For instance:

```
SELECT * FROM pg_attribute WHERE attrelid = 'mytable'::regclass;
```

is actually mapped to something like

```
SELECT * FROM pg_attribute
  WHERE attrelid = (SELECT oid FROM pg_class WHERE relname = 'mytable');
```

We should decide if and how we want to support these "specialized input and output routines".

@knz @cuongdo

### PR DESCRIPTION
**Pull request by jordanlewis**
This pull request adds support for typecasts of the form `table::REGCLASS`. These special REG* types convert string inputs into their corresponding OIDs from the table indicated by the type. See https://www.postgresql.org/docs/9.6/static/datatype-oid.html for more information.

Only review the last 2 commits - the other two are a part of #11694.

Closes #9990

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/11717)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
This came out cleaner than I thought it would, nice job! Do you mind opening an issue about the virtual table cache, which this change necessitates? Also, are there any other concerns you had while writing this? If so, it would be nice to enumerate them here, because I know there we a number discussed offline.

Also, I'm going to merge #10196 later today when I get a chance to give it one last close look over. The change will conflict a bit, so if possible please don't merge before then. Thanks.

---

Reviewed 4 of 4 files at r3, 5 of 8 files at r4.
Review status: 7 of 14 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/col_types.go, line 31 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/11717#-KXzUbBmhPUCq61nd0BV:-KXzUbBnRm7A4LzQAebf:bokha7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada5791ba98445adb8eb45b375fe7db477a4799c/pkg/sql/parser/col_types.go#L31)):*
> ```Go
> 	NodeFormatter
> 	columnType()
> 	castTargetType()
> ```

What do you think about embedding `CastTargetType` here?

---

*[pkg/sql/parser/expr.go, line 1033 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/11717#-KXzVYAF4DLBARIaY3Wu:-KXzVYAF4DLBARIaY3Wv:btpfme6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada5791ba98445adb8eb45b375fe7db477a4799c/pkg/sql/parser/expr.go#L1033)):*
> ```Go
> 		return TypeInterval, intervalCastTypes
> 	case *PGOIDType:
> 		return TypeInt, intCastTypes
> ```

Is `intCastTypes` correct? It looks like we only handle `[]Type{TypeString, TypeInt}` and maybe `TypeNull` (not sure how PG behaves with that.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11717#-:-KXzVtdAtksRgSPsnUHV:b-3c5eux)*

**Comment by jordanlewis** [comment]
TFTR! I'll rebase on top of #10196 when it's merged.

---

Review status: 7 of 14 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/col_types.go, line 31 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/11717#-KXzUbBmhPUCq61nd0BV:-KY-R5e8oYLkHURdEFRf:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada5791ba98445adb8eb45b375fe7db477a4799c/pkg/sql/parser/col_types.go#L31)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What do you think about embedding `CastTargetType` here?
</blockquote></details>

Good point, done.

---

*[pkg/sql/parser/expr.go, line 1033 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/11717#-KXzVYAF4DLBARIaY3Wu:-KY-Scq-nOwlhJ0mh8cv:b78kar8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada5791ba98445adb8eb45b375fe7db477a4799c/pkg/sql/parser/expr.go#L1033)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is `intCastTypes` correct? It looks like we only handle `[]Type{TypeString, TypeInt}` and maybe `TypeNull` (not sure how PG behaves with that.)
</blockquote></details>

You are right - good catch. PG allows `NULL::OID`, just returning `NULL`, so we can keep that behavior as well. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11717#-:-KY-SqilofL7_2VF5-f0:b-qqsm2y)*

**Comment by jordanlewis** [comment]
Rebased - PTAL.

---

Review status: 0 of 15 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11717#-:-KY0bObTua7c4UFoCFUz:bcwpx9j)*

**Comment by nvanbenschoten** [comment]
:lgtm: Nice job with this! And you opened an issue about the cache, right?

---

Review status: 0 of 15 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11717#-:-KYFjiraGQYdHaOphIuN:b7bm03u)*

**Comment by jordanlewis** [comment]
Opened a (very barebones) issue for the cache in #12025.

**Pull request merged**
