### PR TITLE
concurrency: refactors in preparation for lock promotion

### PR DESCRIPTION
**Pull request by arulajmani**
See individual commits for details.

References https://github.com/cockroachdb/cockroach/issues/110435

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118448)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2725 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118448#-NpQd-YtCDofg7Afh3sD:-NpQd-YtCDofg7Afh3sE:bdy4p8u) ([raw file](https://github.com/cockroachdb/cockroach/blob/fce0ac0dfebe05242cd522c210f6cc9cf5e328f2/pkg/kv/kvserver/concurrency/lock_table.go#L2725)):*
> ```Go
> 
> // insertLockingRequest inserts the locking request, trying to access the lock
> // with the supplied strength, at the correct position into the lock's wait
> ```

`s/into/in/`
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2794 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118448#-NpQhGMlCyLmuu2mAd4s:-NpQhGMlCyLmuu2mAd4t:bixcs7e) ([raw file](https://github.com/cockroachdb/cockroach/blob/97b813bf8edaf10ca96492e59a4d2277c508a111/pkg/kv/kvserver/concurrency/lock_table.go#L2794)):*
> ```Go
> // arrival time -- requests that arrive later sort after requests that arrive
> // earlier, and vice-versa.
> func (kl *keyLocks) sortsAfter(g1, g2 *lockTableGuardImpl) bool {
> ```

A `sortsBefore` and `sortsAfter` method which don't reference each other and which don't use some shared logic feels like a recipe for bugs. Do we need both?
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2794 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118448#-NpQlYhxA_VxQVOYyZcs:-NpQlYhxA_VxQVOYyZct:bk4kpt6) ([raw file](https://github.com/cockroachdb/cockroach/blob/97b813bf8edaf10ca96492e59a4d2277c508a111/pkg/kv/kvserver/concurrency/lock_table.go#L2794)):*
> ```Go
> // arrival time -- requests that arrive later sort after requests that arrive
> // earlier, and vice-versa.
> func (kl *keyLocks) sortsAfter(g1, g2 *lockTableGuardImpl) bool {
> ```

Does this need to be a method on `keyLocks`? Are we going to scan through the held locks to detect promotions on each call?

An alternative approach here would be something like the following:
```go
type queueOrder struct {
    reqSeqNum uint64
    lockPromotion bool
}

func (o1 queueOrder) before(o2 queueOrder) bool { ... }
```

We'd then compute and store an immutable `queueOrder` on the `queuedGuard`.

**Review by arulajmani — COMMENTED** [review]
RFAL! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118448#-:-Nq4LEyn9G0rbwJBv8Co:by76qkj)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2794 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118448#-NpQhGMlCyLmuu2mAd4s:-Nq3Bpd11yYYRz8tkGsx:b-31irre) ([raw file](https://github.com/cockroachdb/cockroach/blob/97b813bf8edaf10ca96492e59a4d2277c508a111/pkg/kv/kvserver/concurrency/lock_table.go#L2794)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

A `sortsBefore` and `sortsAfter` method which don't reference each other and which don't use some shared logic feels like a recipe for bugs. Do we need both?
</blockquote></details>

Yeah, I call one from the other in https://github.com/cockroachdb/cockroach/pull/118484. 

I ended up removing the `before` -- the only place that was previously using it was `verify`, which I rewrote to (what I think to) be a bit clearer.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2794 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118448#-NpQlYhxA_VxQVOYyZcs:-Nq4LCr8CLx3to9JXIdz:b-w3ji1d) ([raw file](https://github.com/cockroachdb/cockroach/blob/97b813bf8edaf10ca96492e59a4d2277c508a111/pkg/kv/kvserver/concurrency/lock_table.go#L2794)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does this need to be a method on `keyLocks`? Are we going to scan through the held locks to detect promotions on each call?

An alternative approach here would be something like the following:
```go
type queueOrder struct {
    reqSeqNum uint64
    lockPromotion bool
}

func (o1 queueOrder) before(o2 queueOrder) bool { ... }
```

We'd then compute and store an immutable `queueOrder` on the `queuedGuard`.
</blockquote></details>

Discussed offline. SGTM. Done!

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118448)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2794 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118448#-NpQlYhxA_VxQVOYyZcs:-Nq4MJ-K-g1mg6FqRdeA:b50yguk) ([raw file](https://github.com/cockroachdb/cockroach/blob/97b813bf8edaf10ca96492e59a4d2277c508a111/pkg/kv/kvserver/concurrency/lock_table.go#L2794)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Discussed offline. SGTM. Done!
</blockquote></details>

Are these still needed now that we have `queueOrder`?

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118448)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2794 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118448#-NpQlYhxA_VxQVOYyZcs:-Nq4Mciw9ikl02Qo4Mtg:bqg4lqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/97b813bf8edaf10ca96492e59a4d2277c508a111/pkg/kv/kvserver/concurrency/lock_table.go#L2794)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Are these still needed now that we have `queueOrder`?
</blockquote></details>

Ugh accidentally pressed `u` one too many times and didn't realize :) 

My bad; removed.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118448#-:-Nq4XdU94EaXZdP26tu4:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by arulajmani** [comment]
Thanks! 

bors r=nvanbenschoten

**Pull request merged**
