### PR TITLE
kvnemesis: add support for shared lock

### LINKED ISSUE #100173: kvnemesis: add SHARED locks
We should extend kvnemesis to acquire SHARED locks ([#91545](https://github.com/cockroachdb/cockroach/issues/91545)).

From the Read Committed RFC:
> The framework’s generator will be updated to issue locking reads with a SHARED lock strength.

Jira issue: CRDB-26564

Epic CRDB-26548

### PR DESCRIPTION
**Pull request by arulajmani**
This patch teaches KVNemesis to generate batches that acquire shared locks, using Get, Scan, and ReverseScan requests.

Closes #100173
Release note: None

### CODE REVIEW

**Review by miraradeva — COMMENTED** [review]
Looks great! I'm wondering if it will be useful to add some tests in `validator_test` to try out and document some of the interactions between transactions using for share and for update locks. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110651#-:-NeO3Kh68RyQTNqnlTPf:b-ivd04a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvnemesis/generator.go` line 265 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110651#-NeO1H_qDQHyvu8EkPcb:-NeO1H_qDQHyvu8EkPcc:b-hi1bj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0049c297019da8017a2207359159b11eaa1600cd/pkg/kv/kvnemesis/generator.go#L265)):*
> ```Go
> 		GetMissing:                     1,
> 		GetMissingForUpdate:            1,
> 		GetMissingForShare:             1,
> ```

Also add `GetMissingForShareSkipLocked`?
___
*[`pkg/kv/kvnemesis/generator.go` line 1290 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110651#-NeO2-HN5_vAwuiJhcZH:-NeO2-HN5_vAwuiJhcZI:b8k7as7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0049c297019da8017a2207359159b11eaa1600cd/pkg/kv/kvnemesis/generator.go#L1290)):*
> ```Go
> }
> 
> func getForShare(key string) Operation {
> ```

Do we also want to include the skip locked variants of these here, and in the applier test?
___
*[`pkg/kv/kvnemesis/operations.proto` line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110651#-NeO2JGQ3OlakNAfDWVH:-NeO2JGQ3OlakNAfDWVI:b-69f3ki) ([raw file](https://github.com/cockroachdb/cockroach/blob/0049c297019da8017a2207359159b11eaa1600cd/pkg/kv/kvnemesis/operations.proto#L46)):*
> ```proto
>   bytes key = 1;
>   bool for_update = 2;
>   bool for_share = 3;
> ```

I'm sure this is fine because kvnemesis is not an actual prod system that may run under different versions. But just for my understanding, this sort of proto change is not backwards compatible, right? We are only supposed to add to the end instead? (I'm not suggesting you change this, it looks good in this order)

**Review by arulajmani — COMMENTED** [review]
I added a few test cases to `validator_test` -- I didn't add too many, because KVNemesis doesn't do any special validation for locking reads. RFAL! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110651#-:-NeOe2PnDjE2ID62A6cV:b9j8w1g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miraradeva)

___
*[`pkg/kv/kvnemesis/generator.go` line 265 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110651#-NeO1H_qDQHyvu8EkPcb:-NeOPxxt1JAmM1g-qn7Q:b2nkio0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0049c297019da8017a2207359159b11eaa1600cd/pkg/kv/kvnemesis/generator.go#L265)):*
<details><summary><i>Previously, miraradeva (Mira Radeva) wrote…</i></summary><blockquote>

Also add `GetMissingForShareSkipLocked`?
</blockquote></details>

Nice catch! Turns out, `GetMissingForUpdateSkipLocked` was also missing -- added that as well.
___
*[`pkg/kv/kvnemesis/generator.go` line 1290 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110651#-NeO2-HN5_vAwuiJhcZH:-NeOWFib6p5aJdy0hkDM:bd1flnz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0049c297019da8017a2207359159b11eaa1600cd/pkg/kv/kvnemesis/generator.go#L1290)):*
<details><summary><i>Previously, miraradeva (Mira Radeva) wrote…</i></summary><blockquote>

Do we also want to include the skip locked variants of these here, and in the applier test?
</blockquote></details>

Good catch. It turns out, even here, we were missing `getForUpdateSkipLocked` as well. I've added both.

Ditto for the scan/reverse scan variants.
___
*[`pkg/kv/kvnemesis/operations.proto` line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110651#-NeO2JGQ3OlakNAfDWVH:-NeO_Jd95qF7XlDrEo8_:b-4e6mbj) ([raw file](https://github.com/cockroachdb/cockroach/blob/0049c297019da8017a2207359159b11eaa1600cd/pkg/kv/kvnemesis/operations.proto#L46)):*
<details><summary><i>Previously, miraradeva (Mira Radeva) wrote…</i></summary><blockquote>

I'm sure this is fine because kvnemesis is not an actual prod system that may run under different versions. But just for my understanding, this sort of proto change is not backwards compatible, right? We are only supposed to add to the end instead? (I'm not suggesting you change this, it looks good in this order)
</blockquote></details>

You're right, this sort of protobuf change won't be backwards incompatible if its stored on disk or sent over the network. That would break mixed-version backwards compatibility. 

This change is fine, because it's test only.

**Review by miraradeva — APPROVED** [review]
:lgtm:

> Reviewed 12 of 15 files at r1, 16 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110651#-:-NePLjapBroOKhIKrGoY:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by arulajmani** [comment]
TFTR! 

bors r=miraradeva

**Pull request merged**
