### PR TITLE
partitionccl: remove unused functions

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit removes a couple of functions that are only used in tests.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I think it's owned by @cockroachdb/sql-schema? I didn't do any archaeology for why these functions are unused.

**Comment by ajwerner** [comment]
What lead you here?

**Comment by yuzefovich** [comment]
Thinking about removing `context.Context` from `eval.Context` (what Marylia ran into).

**Review by otan — APPROVED** [review]

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by ajwerner** [comment]
bors r+

One of the flakes will be fixed by https://github.com/cockroachdb/cockroach/pull/86114. The other is https://github.com/cockroachdb/cockroach/issues/85800.

**Pull request merged**
