### PR TITLE
distsqlrun,sql: export everything distsql changefeed flows will need

### PR DESCRIPTION
**Pull request by danhhz**
Existing ccl distsql flows implement the Processor interface and do physical planning in the sql package. Changefeeds are going to implement RowSource and do physical planning in the ccl tree, so we need to export a bunch of stuff to get this to work. I extracted this from my in-progress branch, so I think it's everything but no guarantees.

I was originally going to include this as part of a mega-PR also introducing the changefeed flow, but realized it's probably better to get the reviews started now.

### CODE REVIEW

**Comment by knz** [comment]
Could you perhaps make a list of the public interface that's used here? So we can glance through it and see if there's anything mis-exported (e.g. something that would be best left un-exported and repackaged in another public API).

Thanks

**Comment by knz** [comment]
No comment on the distsql planning changes but extendedEvalContext is not meant to be exported like this I recall. @andreimatei can you provide guidance?
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by danhhz** [comment]
Unfortunately, ExtendedEvalContext is necessary for both `(*DistSQLPlanner).NewPlanningCtx` and `(*DistSQLPlanner).Run` so it's unavoidable in some sense. I tried just now to remove it in favor of passing just the fields that are used by those two methods but it ends up in`runParams` and so we'd have to plumb down all of them, which is definitely worse.

I could do something like a marker interface just to make sure that nothing outside of sql is doing anything with it other than getting it and passing it back in, would that be preferable? Otherwise, is there some alternative you prefer? This PR needs to go in ASAP

**Review by andreimatei — COMMENTED** [review]
Well if the ccl package needs to to do planning, I guess you do need to export `extendedEvalContext`.
But my question would be - if other ccl functionality delegates planning and some of the running to the sql package (AFAICT, through `sql.PlanAndRunExport` and `distsqlrun.NewCSVWriterProcessor`), why not do the same here? Or the other way around. Is there a difference between the two cases?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28466#-:-LJ_9xNM0bPbtns2FwAA:bx3xajx)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by danhhz** [comment]
It turns out that I don't need to export extendedEvalContext. Go will let me take the one already given out by `sql.PlanHookState` and pass it back into `(*DistSQLPlanner).NewPlanningCtx` and `(*DistSQLPlanner).Run` just fine. To be clear, I'm not adding that method to PlanHookState, it's been there for a long time: https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/planhook.go#L71

(This also lets me access the fields and methods of extendedEvalContext, which means you can get around our "don't return unexported types from an exported function" linter with an interface, which should probably be fixed.)

Okay, I think this is ready to go!

**Review by jordanlewis — APPROVED** [review]
LGTM. It makes me sad that we need to export so much internal details to make distsql usable from another package, but fixing that isn't something that can get done before this needs to go in.

**Comment by danhhz** [comment]
Yeah, agreed. Definitely seems like there is something simpler to be done here. The worst part is once the release branch is cut, we should probably hold off on that refactor until the changefeed cherry-picks die down (which might be a while).

I realize no one's going to have time for this, but all the processors could be moved into a separate package. Doing that probably would have forced this issue a while ago. The core team has been picking apart storage and not only is it helping readability, it's also making the interfaces going in to be more public and thoughtful. (I've heard the original prototype of follower reads vs the final impl is a good example).

Thanks for the reviews!

bors r=jordanlewis

**Comment by RaduBerinde** [comment]
I'd also be curious to learn the answer to @andrei's question above:

> But my question would be - if other ccl functionality delegates planning and some of the running to the sql package (AFAICT, through sql.PlanAndRunExport and distsqlrun.NewCSVWriterProcessor), why not do the same here? Or the other way around. Is there a difference between the two cases?

What is the main reason that physical planning has to happen from ccl and can't be delegated to sql? This kind of tight inter-dependency is going to be a nightmare when we inevitably redesign the execution layers..

**Comment by danhhz** [comment]
Ah, sorry, missed this question! PlanAndRunExport is a cargo cult of import, which was added at the last second before a release and we didn't have time to do it in any sort of principled way. Perhaps I'm incorrectly assuming others people's opinions, but I've always found it unfortunate that import's planning (and now export's) live in another package because it makes it harder to understand and maintain the import code. We can't fix import now because we've promised not to move apache2 code into ccl, but I was looking here to avoid re-making that mistake with changefeeds.

That said, I'm absolutely open to alternatives, especially if we redesign the execution layers. It would be nice if we could reuse the current distsql physical planning logic, but it's currently pretty tightly coupled and mocking out the correct input would be unwieldy and even more confusing than import and export are now. I don't particularly see how putting it in distsqlrun right now helps any distsql readability, but it's easy to imagine that being different when the optimizer starts doing planning. Putting it in ccl to start gives us that flexibility.

**Comment by knz** [comment]
The party line currently in the SQL team is that all the logical planning should be directed from the non-CCL code (and include as many bits as necessary to plan CCL statements) and restrict the execution to use CCL code.

**Comment by danhhz** [comment]
Oh, that's the first I'm hearing of it. My position has always been that anything that can reasonably be ccl code should be. I don't see why the current physical planning functions are any structurally better sitting in sql than they would be in ccl. I want to make sure everyone is happy, but I have a billion things to get in before the release branch is cut and I don't have time to resolve this in an asychronous thread. If y'all feel strongly, lets set up a meeting and discuss (preferably tuesday or wednesday please).

**Review by andreimatei — COMMENTED** [review]
> I don't see why the current physical planning functions are any structurally better sitting in sql than they would be in ccl

My impression is that, if the ccl package can do the planning fully for a type of statement, then there's nothing wrong with doing "physical planning" - so, creating a flow spec - in whatever package. But then I'd say ideally the ccl package should do its own thing and not need things like `PlanningCtx` and `EvalCtx`. If the planning somehow needs to combine planning done by the sql package and the planning done by the ccl package, then I'm not sure what's to be done.
And this is strictly about planning; about execution I don't know what I think.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28466#-:-LJnvBg83FNhtK8s0_NU:b51l4gi)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
