### PR TITLE
opt: ON UPDATE cascades for Upsert

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change implements ON UPDATE actions for Upsert operations. The existing
machinery for Update can be used without modification.

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49804#-:-M8wIfi6-oVlFwx-MLXt:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/logictest/testdata/logic_test/cascade, line 3910 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49804#-M8wGMrl-YDGEHF2ZTrz:-M8wGMrm-XV8Ia3f02ip:bxu5bgx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c37035d324bf4b78161133b983c0aca16bc3c7/pkg/sql/logictest/testdata/logic_test/cascade#L3910)):*
> ```
> 
> statement ok
> UPSERT INTO parent VALUES (1, 1)
> ```

Consider adding a comment to explain what this is testing

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49804)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

___
*[pkg/sql/logictest/testdata/logic_test/cascade, line 3910 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49804#-M8wGMrl-YDGEHF2ZTrz:-M8wds9E64RS6yEYcJWP:b-ryrxn9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c37035d324bf4b78161133b983c0aca16bc3c7/pkg/sql/logictest/testdata/logic_test/cascade#L3910)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Consider adding a comment to explain what this is testing
</blockquote></details>

Done. I also added a couple of more tests and added (in a separate commit) some changes that were made only to the `cascade` file.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 8 of 8 files at r2, 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49804#-:-M8wvS_p440WDQAVZLJl:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
