### PR TITLE
Add support for the TRIM builtin function

### PR DESCRIPTION
**Pull request by nvb**
See #2042

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3089)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM


---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[sql/parser/builtins.go, line 252 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3089#-K2modnZd6NMNqHo6IFy)** ([raw file](https://github.com/cockroachdb/cockroach/blob/dcdb0013dd3428173e0c32c973ff5ac0220d65d4/sql/parser/builtins.go#L252)):</sup>
nit: the closing parentheses make this and the similar comments below a bit confusing. How about `TRIM(...) and TRIM(BOTH ...) to BTRIM(...)`?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3089)

**Comment by nvanbenschoten** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[sql/parser/builtins.go, line 252 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3089#-K2modnZd6NMNqHo6IFy)** ([raw file](https://github.com/cockroachdb/cockroach/blob/dcdb0013dd3428173e0c32c973ff5ac0220d65d4/sql/parser/builtins.go#L252)):</sup>
Good point. Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3089)

**Comment by tamird** [comment]
Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[sql/parser/builtins.go, line 252 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3089#-K2modnZd6NMNqHo6IFy)** ([raw file](https://github.com/cockroachdb/cockroach/blob/dcdb0013dd3428173e0c32c973ff5ac0220d65d4/sql/parser/builtins.go#L252)):</sup>
Can you add the parentheses on the end like I suggested in my comment? the ellipsis is intended as a cue, but it's missing from the result of the parser's transformation in this comment.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3089)

**Comment by nvanbenschoten** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[sql/parser/builtins.go, line 252 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3089#-K2modnZd6NMNqHo6IFy)** ([raw file](https://github.com/cockroachdb/cockroach/blob/dcdb0013dd3428173e0c32c973ff5ac0220d65d4/sql/parser/builtins.go#L252)):</sup>
Oh sorry, didn't catch that. You mean like this, right?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3089)

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

<sup>**[sql/parser/builtins.go, line 252 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3089#-K2modnZd6NMNqHo6IFy)** ([raw file](https://github.com/cockroachdb/cockroach/blob/dcdb0013dd3428173e0c32c973ff5ac0220d65d4/sql/parser/builtins.go#L252)):</sup>
Yup!


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3089)

**Pull request merged**
