### PR TITLE
opt: add panic injection to the optimizer for randomized tests

### LINKED ISSUE #98787: opt: add tests with randomly inject optimizer panics to catch missing panic-catchers
To find missing panic-catchers related to optimizer code, we should add a test that randomly injects panics the occur within optimization, similar to how we inject panics in the execution engine.

From the [v23.1 pre-mortem](https://cockroachlabs.atlassian.net/wiki/spaces/SQLQUERIES/pages/edit-v2/29294919690).

### PR DESCRIPTION
**Pull request by DrewKimball**
This patch adds a function `opt.MaybeInjectOptimizerTestingPanic` that is called at various points during query optimization in order to inject panics during testing. This is used to test that panic-catching is in place around calls to optimizer logic that could use a panic for error propagation. This will help to ensure that optimizer error-propagation panics are surfaced as internal errors, rather than node crashes.

Fixes #98787

Release note: None

### CODE REVIEW

**Comment by DrewKimball** [comment]
I verified that enabling the panic injection and running a bunch of sqlsmith queries is enough to catch a missing panic-catcher for `Optimizer.Optimize` (if I remove it).

**Review by michae2 — COMMENTED** [review]
Nice!

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99868#-:-NRiPbQG8M3-phTcFjyZ:b-83sjoh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/vars.go` line 687 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99868#-NRiOjH63w9NMheXIWHF:-NRiOjH63w9NMheXIWHG:b783g8x) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae5fa59027f039101c299f1a51dcc1331c353918/pkg/sql/vars.go#L687)):*
> ```Go
> 
> 	// CockroachDB extension.
> 	`testing_inject_panics`: {
> ```

How would you feel about adding a new setting just for optimizer panics, rather than changing this setting?

My thinking is: the optimizer panic catcher is separate from the vectorized engine panic catcher, so we should be able to test them separately (even if in practice we usually turn on both settings at the same time).

**Review by mgartner — APPROVED** [review]
:lgtm: This is really cool! So we'll turn this on for tests like SQLSmith, correct?

A lot of the panics in the optimizer follow a simple pattern like:

```go
if cond {
  panic(...)
}
```

If we wanted to extend this panic injection further, we could replace all these panics with:

```go
opt.PanicIf(cond, ...)

// ...

func PanicIf(cond bool, ...) {
    if evalCtx.SessionData().TestingInjectPanics {
        if rand.Float64() < panicInjectionProbability {
            log.Info(ctx, "injecting panic in optimizer")
            panic(errors.AssertionFailedf("injected panic in optimizer"))
        }
    }
    if cond {
        panic(...)
    }
}
```

The benefit is that we'd inject panics in all the places that could possibly panic. No need to change this PR though.

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99868#-:-NRsCOdGCXbX3V5y6kEl:bhxkc52)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99868)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2)

___
*[`pkg/sql/vars.go` line 687 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99868#-NRiOjH63w9NMheXIWHF:-NSCY7M3BUNet-TIsFAC:b-8ylue9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae5fa59027f039101c299f1a51dcc1331c353918/pkg/sql/vars.go#L687)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

How would you feel about adding a new setting just for optimizer panics, rather than changing this setting?

My thinking is: the optimizer panic catcher is separate from the vectorized engine panic catcher, so we should be able to test them separately (even if in practice we usually turn on both settings at the same time).
</blockquote></details>

Sure, doesn't hurt. Done.

**Review by michae2 — CHANGES_REQUESTED** [review]
Nice!

> Reviewed 5 of 12 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99868#-:-NSDAWGO79S2tOxfL4vm:b-83sjoh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

___
*[`pkg/sql/sessiondatapb/session_data.proto` line 118 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/99868#-NSDAI0S2msFIykBMqCh:-NSDAI0S2msFIykBMqCi:b-mz5pdd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7923368251c24bbac59ad22956ccdfadf8db9da2/pkg/sql/sessiondatapb/session_data.proto#L118)):*
> ```protobuf
>   // during optimization. The goal of this setting is to flush out cases where
>   // panics used for error-propagation are uncaught.
>   bool testing_optimizer_inject_panics = 27;
> ```

Should this be in `LocalOnlySessionData` rather than here?

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99868)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @michae2)

___
*[`pkg/sql/sessiondatapb/session_data.proto` line 118 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/99868#-NSDAI0S2msFIykBMqCh:-NSDJLnW7BrlRryHKXnN:belo8vk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7923368251c24bbac59ad22956ccdfadf8db9da2/pkg/sql/sessiondatapb/session_data.proto#L118)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Should this be in `LocalOnlySessionData` rather than here?
</blockquote></details>

Good point, moved it.

**Review by michae2 — APPROVED** [review]
:lgtm: Thanks for doing this!

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99868#-:-NSDL0EXAqZ4VtB_si0Q:b-pt8m11)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

**Comment by DrewKimball** [comment]
TFTRs!

bors r+

**Pull request merged**
