### PR TITLE
builtins: implement ST_Disjoint

### LINKED ISSUE #48919: geo/geomfn: implement ST_Disjoint({geometry,geometry})
Implement `ST_Disjoint` on arguments {geometry,geometry}, which should adopt [PostGIS behaviour](https://postgis.net/docs/ST_Disjoint.html).

_Observers: Please react to this issue if you need this functionality._

For Geometry builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geomfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geomfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
  * When using GEOS, you can reference the [C API](https://github.com/libgeos/geos/blob/master/capi/geos_c.h.in) for which functions are available. Unfortunately, Windows is not currently supported when using GEOS.
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go). Note that we currently do not support optional arguments, so we define functions that have optional arguments once without the optional argument (using the default value in the optional position), and once with the optional argument.
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output. Tests here should just ensure the builtin is linked end to end (your exhaustive unit tests go the above mentioned packages!).
* Ensure the documentation is regenerated by calling `make buildshort`. You can also play with it by calling `./cockroach demo --empty` afterwards.
* Submit your PR - make sure to follow the guidelines from [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

You can follow #48552 for an example PR.

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-06-30T05:29:57Z. Changes to titles, body and labels may be overwritten.</sub>

### PR DESCRIPTION
**Pull request by otan**
Resolves #48919.

Release note (sql change): Implements the ST_Disjoint builtin for
geometry types.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51444#-:-MCI82J40kWDx5zA1LNS:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/geo/geomfn/binary_predicates_test.go, line 173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51444#-MCI6cOw3Rbq9qV6rYQO:-MCI6cOx9EzFnxmBxIiB:bezx7jv) ([raw file](https://github.com/cockroachdb/cockroach/blob/572d9aac4f567a912c2ba8b1ab605162d26cfc53/pkg/geo/geomfn/binary_predicates_test.go#L173)):*
> ```Go
> 	for i, tc := range testCases {
> 		t.Run(fmt.Sprintf("tc:%d", i), func(t *testing.T) {
> 			g, err := Disjoint(tc.a, tc.b)
> ```

[nit] `g` is a confusing variable name, given that it's a boolean
___
*[pkg/geo/geomfn/binary_predicates_test.go, line 180 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51444#-MCI6kNI2lyA-QR4Mazl:-MCI6kNI2lyA-QR4Mazm:b-38hsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/572d9aac4f567a912c2ba8b1ab605162d26cfc53/pkg/geo/geomfn/binary_predicates_test.go#L180)):*
> ```Go
> 
> 	t.Run("errors if SRIDs mismatch", func(t *testing.T) {
> 		_, err := Crosses(mismatchingSRIDGeometryA, mismatchingSRIDGeometryB)
> ```

Crosses -> Disjoint
___
*[pkg/sql/sem/builtins/geo_builtins.go, line 2129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51444#-MCI7rJBAICeX9IMQE0h:-MCI7rJC2jji2RUQyZ4a:bowalyv) ([raw file](https://github.com/cockroachdb/cockroach/blob/572d9aac4f567a912c2ba8b1ab605162d26cfc53/pkg/sql/sem/builtins/geo_builtins.go#L2129)):*
> ```Go
> 			geomfn.Disjoint,
> 			infoBuilder{
> 				info:         "Returns true if geometry_a does not overlap, touch or is within geometry_b.",
> ```

[nit] this description feels a bit awkward but I don't have a better suggestion...

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51444)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/geo/geomfn/binary_predicates_test.go, line 173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51444#-MCI6cOw3Rbq9qV6rYQO:-MCITnqs0XNmZaK9PTwr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/572d9aac4f567a912c2ba8b1ab605162d26cfc53/pkg/geo/geomfn/binary_predicates_test.go#L173)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] `g` is a confusing variable name, given that it's a boolean
</blockquote></details>

Done.
___
*[pkg/geo/geomfn/binary_predicates_test.go, line 180 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51444#-MCI6kNI2lyA-QR4Mazl:-MCITsPYExE40qjEI_jQ:b-xtbh1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/572d9aac4f567a912c2ba8b1ab605162d26cfc53/pkg/geo/geomfn/binary_predicates_test.go#L180)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Crosses -> Disjoint
</blockquote></details>

Woops!
___
*[pkg/sql/sem/builtins/geo_builtins.go, line 2129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51444#-MCI7rJBAICeX9IMQE0h:-MCITte51IrDrSaNb2YY:bxqsdiv) ([raw file](https://github.com/cockroachdb/cockroach/blob/572d9aac4f567a912c2ba8b1ab605162d26cfc53/pkg/sql/sem/builtins/geo_builtins.go#L2129)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] this description feels a bit awkward but I don't have a better suggestion...
</blockquote></details>

Hah, it's the same flavour of wording as PostGIS.

**Comment by otan** [comment]
bors r=rytaft

**Comment by otan** [comment]
bors r=rytaft

**Comment by otan** [comment]
bors r=rytaft

**Pull request merged**
