### PR TITLE
sql: new functions `crdb_internal.ranges_in_span` and `crdb_internal.tenant_ranges_per_table`

### PR DESCRIPTION
**Pull request by THardy98**
Part of: https://github.com/cockroachdb/cockroach/issues/94332
Part of: https://github.com/cockroachdb/cockroach/issues/94330

This PR introduces two new SRFs:
`crdb_internal.ranges_in_span(start_key, end_key)` - returns the set of ranges encompassing this span in the form of `(range_id, start_key, end_key)` 

Example response:
```
select * from crdb_internal.ranges_in_span('\xf670', '\xf671');
  range_id | start_key | end_key
-----------+-----------+----------
        91 | \xf66f    | \xffff
```

`crdb_internal.tenant_ranges_per_table()` - returns the tenant's tables, each table row contains the set of ranges encompassing the table, each row takes the form of `(database_name, database_id, table_name, table_id, range_count, range_ids)`

Example response:
```
select * from crdb_internal.tenant_ranges_per_table() where database_name = 'movr';
  database_name | database_id |         table_name         | table_id | range_count |          range_ids
----------------+-------------+----------------------------+----------+-------------+-------------------------------
  movr          |         104 | users                      |      106 |           9 | {76,60,58,56,65,55,59,57,66}
  movr          |         104 | vehicles                   |      107 |           9 | {77,64,63,62,86,61,87,85,75}
  movr          |         104 | rides                      |      108 |           9 | {74,73,72,69,71,67,70,68,88}
  movr          |         104 | vehicle_location_histories |      109 |           1 | {89}
  movr          |         104 | promo_codes                |      110 |           1 | {90}
  movr          |         104 | user_promo_codes           |      111 |           1 | {91}
```

`crdb_internal.ranges_in_span` is a QOL improvement, for convienence.
`crdb_internal.tenant_ranges_per_table` is intended to be used as a method to retrieve a large number of tables' range data quickly, particularly for the database details page (where we surface the range count of each table).

Tested with 100 databases, each with 100 tables, each table having 1 range, `crdb_internal.tenant_ranges_per_table` is able to retrieve the range ids & range count for the ~10,000 tables in ~1.5s.

```
select * from crdb_internal.tenant_ranges_per_table() where database_name = 'movr';
  database_name | database_id |         table_name         | table_id | range_count |          range_ids
----------------+-------------+----------------------------+----------+-------------+-------------------------------
...
  movr"100      |         310 | users17                   |    10411 |           1 | {10101}
(10048 rows)

Time: 1.126s total (execution 1.121s / network 0.005s)
```

Release note(sql change): introduce two SRFs `crdb_internal.ranges_in_span` and `crdb_internal.tenant_ranges_per_table`

### CODE REVIEW

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96011)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @THardy98)

___
*[`pkg/sql/logictest/testdata/logic_test/ranges_in_span` line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96011#-NMk-eRU1ov_7TlqMoBf:-NMk-eRU1ov_7TlqMoBg:b-gpuce) ([raw file](https://github.com/cockroachdb/cockroach/blob/b07abaf87a84df0f0ed53f6454b75d293eac8534/pkg/sql/logictest/testdata/logic_test/ranges_in_span#L1)):*
> ```
> # LogicTest: local
> ```

When new functions are added, we should make sure they are secondary-tenant compatible.

It looks like you are already using `rangedesc.Iterator` which is good, but `# LogicTest: local` will prevent the test from being run under a config that uses a secondary tenant (for example the `3node-tenant` config).

What happens if you remove this and run it under the `3node-tenant` config?

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96011)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall)

___
*[`pkg/sql/logictest/testdata/logic_test/ranges_in_span` line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96011#-NMk-eRU1ov_7TlqMoBf:-NN2SSss6kwAi9jZ0tDI:b-9ixfhe) ([raw file](https://github.com/cockroachdb/cockroach/blob/b07abaf87a84df0f0ed53f6454b75d293eac8534/pkg/sql/logictest/testdata/logic_test/ranges_in_span#L1)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

When new functions are added, we should make sure they are secondary-tenant compatible.

It looks like you are already using `rangedesc.Iterator` which is good, but `# LogicTest: local` will prevent the test from being run under a config that uses a secondary tenant (for example the `3node-tenant` config).

What happens if you remove this and run it under the `3node-tenant` config?
</blockquote></details>

Looks like a test failure:
```
RangeIterator failed to seek to /Meta2/Table/3/NULL: rpc error: code = Unauthenticated desc = requested key /Meta2/Table/3/NULL not fully contained in tenant keyspace /Tenant/1{0-1}
```
Would it be acceptable to swallow this error and continue iterating, effectively skip any iterations we aren't authed for? Or is there a better way to handle this, I'm not familiar with how we handle this.

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96011)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @THardy98)

___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 2941 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/96011#-NN2ZUgM91QLSWexAsHY:-NN2ZUgM91QLSWexAsHZ:bnqp6y0) ([raw file](https://github.com/cockroachdb/cockroach/blob/13074d897af50cae4eb800bccde4588d4f4ed344/pkg/sql/sem/builtins/generator_builtins.go#L2941)):*
> ```Go
> }
> 
> func getRangeIteratorWithinSpan(
> ```

Can you add `GetRangeIterator(context.Context, roachpb.Span)` to `eval.Planner` (see `GetRangeDescByID`)? Then you don't need to pass in the `db` from here
___
*[`pkg/sql/logictest/testdata/logic_test/ranges_in_span` line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96011#-NMk-eRU1ov_7TlqMoBf:-NN2_4pC3Mckiky2CPHL:b-ayh1m9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b07abaf87a84df0f0ed53f6454b75d293eac8534/pkg/sql/logictest/testdata/logic_test/ranges_in_span#L1)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

Looks like a test failure:
```
RangeIterator failed to seek to /Meta2/Table/3/NULL: rpc error: code = Unauthenticated desc = requested key /Meta2/Table/3/NULL not fully contained in tenant keyspace /Tenant/1{0-1}
```
Would it be acceptable to swallow this error and continue iterating, effectively skip any iterations we aren't authed for? Or is there a better way to handle this, I'm not familiar with how we handle this.
</blockquote></details>

That means you are trying to access keys outside of the tenant's keyspace which is `/Tenant/1{0-1}` meaning `[/Tenant/10, /Tenant/11)`. Can you use a span like `'/Tenant/10', '/Tenant/11'`instead (you have to figure out the bytes for this)?

**Review by knz — COMMENTED** [review]
I like the direction this is going but there are two main design questions remaining open:
- how do you intend this to behave when a single large table contains thousands of ranges?
- there's memory accounting missing in this approach

> Reviewed 1 of 6 files at r1, 1 of 5 files at r3, 1 of 1 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96011#-:-NN2fCHw7s3d71bODh7h:b-b1mewj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @THardy98)

___
*[`-- commits` line 9 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/96011#-NN2eJ938hri0TQHvAnr):*
Can you make this more granular, so that it takes as argument which tables to retrieve ranges for. If there's 100 databases and you inspect just 1, you want this SRF to produce only the data for that db.
___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 3032 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/96011#-NN2efXpAuIaXx19GeGF:-NN2efXpAuIaXx19GeGG:b-nly8tp) ([raw file](https://github.com/cockroachdb/cockroach/blob/13074d897af50cae4eb800bccde4588d4f4ed344/pkg/sql/sem/builtins/generator_builtins.go#L3032)):*
> ```Go
> // Start implements the tree.ValueGenerator interface.
> func (trpti *tenantRangesPerTableIterator) Start(ctx context.Context, txn *kv.Txn) error {
> 	rangeIter, err := getRangeIteratorWithinSpan(ctx, txn.DB(), trpti.span)
> ```

This method would be better served by a call into a function implemented in pkg/sql off `(*planner)` that inspects the descriptor collection and retrieves descriptors one by one. As implemented here, it still retrieves all descriptors in RAM (via the vtable) before it starts iterating.
___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 3085 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/96011#-NN2ezEV-BCdkDJ1W8d8:-NN2ezEV-BCdkDJ1W8d9:bshwmvr) ([raw file](https://github.com/cockroachdb/cockroach/blob/13074d897af50cae4eb800bccde4588d4f4ed344/pkg/sql/sem/builtins/generator_builtins.go#L3085)):*
> ```Go
> 		End:   interval.Comparable(tableStartKey.PrefixEnd()),
> 	}
> 	tableOverlappingRanges := trpti.rangeIntervalTree.Get(tableRange)
> ```

Wowzer, what do you intend to do here if there are 10000 ranges in 1 table? E.g. a large table?

I think this code would be better served by a range iterator in the mapping from table -> range, with 1 result row per range.

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96011)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @knz)

___
*[`pkg/sql/logictest/testdata/logic_test/ranges_in_span` line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96011#-NMk-eRU1ov_7TlqMoBf:-NN7Ft0sDrOoN7OAXGJE:bhun438) ([raw file](https://github.com/cockroachdb/cockroach/blob/b07abaf87a84df0f0ed53f6454b75d293eac8534/pkg/sql/logictest/testdata/logic_test/ranges_in_span#L1)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

That means you are trying to access keys outside of the tenant's keyspace which is `/Tenant/1{0-1}` meaning `[/Tenant/10, /Tenant/11)`. Can you use a span like `'/Tenant/10', '/Tenant/11'`instead (you have to figure out the bytes for this)? 
</blockquote></details>

I'm confused as to why this happens though, particularly for `tenant_ranges_per_table` where we explicitly pass in the tenant's span. Why would we be accessing keys outside the tenant's keyspace?

**Review by ecwall — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96011)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @THardy98)

___
*[`pkg/sql/logictest/testdata/logic_test/ranges_in_span` line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96011#-NMk-eRU1ov_7TlqMoBf:-NNHsUeUAqixJHtn6AlP:b-12i650) ([raw file](https://github.com/cockroachdb/cockroach/blob/b07abaf87a84df0f0ed53f6454b75d293eac8534/pkg/sql/logictest/testdata/logic_test/ranges_in_span#L1)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

I'm confused as to why this happens though, particularly for `tenant_ranges_per_table` where we explicitly pass in the tenant's span. Why would we be accessing keys outside the tenant's keyspace?
</blockquote></details>

Yeah `/Meta2` is not inside the tenant's keyspace so I am not sure why that is being read. What is the stack trace when this error happens?

**Comment by THardy98** [comment]
Closing this PR in favour of opening a new PR using the new `SpanStats` RPC implementation (see https://github.com/cockroachdb/cockroach/pull/96223 ).

Also separated the builtins into their own PRs:
- `ranges_in_span`: https://github.com/cockroachdb/cockroach/pull/97537
-  `tenant_span_stats`: https://github.com/cockroachdb/cockroach/pull/97534

**Pull request closed without merging**
