### PR TITLE
storage: Improve coverage of replaced node test without a big slowdown

### PR DESCRIPTION
**Pull request by a-robinson**
It's down from 12 seconds to about 700ms. Still slower than if we killed the second node, but as mentioned in #11780 this gives better coverage.

It was so slow because it had to wait at least 9 seconds for the first
range's lease to expire. Backoff delays also added some time on top of
that. Resolve this by cutting down the raft tick interval and election
timeout to speed things up. This has shown to not be flaky.

@tamird

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12023)

### CODE REVIEW

**Comment by a-robinson** [comment]
It didn't end up being much of a bug (the only real non-test change being passing store config options down through bootstrapNode), but it was a good excuse for me to sit down and read through the many, many layers of our RPC stack.

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 4 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/server/node.go, line 176 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12023#-KYFR3xtdT_WKXuoF1EX:-KYFR3xtdT_WKXuoF1EY:b-ghv9gl) ([raw file](https://github.com/cockroachdb/cockroach/blob/22586f6ca440a77bc78538c996d8b10559a2672a/pkg/server/node.go#L176)):*
> ```Go
> 	defer stopper.Stop()
> 
> 	// Copy over the important configuration parameters to avoid pulling in any
> ```

wouldn't it be more robust to nuke stuff we _dont_ want? Also, since this has a relatively small number of callers, it would be nice to require that the passed-in clock is not nil.

---

*[pkg/server/server.go, line 197 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12023#-KYFRiwzzFHjuDe_BgCQ:-KYFRiwzzFHjuDe_BgCR:b-5ja8i8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aee560cbd36307a78eba71e62167b7e5c7112fe/pkg/server/server.go#L197)):*
> ```Go
> 	// succeed because the only server has been shut down; thus, thus the
> 	// DistSender needs to know that it should not retry in this situation.
> 	retryOpts := base.DefaultRetryOptions()
> ```

optional: flipping this seems cleaner, i.e. try to use the config value and only then call this function

---

*[pkg/server/testserver.go, line 101 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12023#-KYFRusD82SV4P4u0ETn:-KYFRusD82SV4P4u0ETo:b-r5c81g) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aee560cbd36307a78eba71e62167b7e5c7112fe/pkg/server/testserver.go#L101)):*
> ```Go
> 		cfg.MetricsSampleInterval = params.MetricsSampleInterval
> 	}
> 	if params.RaftTickInterval != time.Duration(0) {
> ```

i think this cast is superfluous

---

*[pkg/storage/gossip_test.go, line 155 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12023#-KYFSFIG5KBH7Cf9oBKA:-KYFSFIG5KBH7Cf9oBKB:bypmenx) ([raw file](https://github.com/cockroachdb/cockroach/blob/601de8a3231bf79cd73c9c2350ff9361b48d049d/pkg/storage/gossip_test.go#L155)):*
> ```Go
> 		base.TestClusterArgs{
> 			ReplicationMode: base.ReplicationAuto,
> 			ServerArgs: base.TestServerArgs{
> ```

you could extract this whole struct to avoid duplicating parts of it below, which seems fragile. you could remove some of the constants above as a result.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12023#-:-KYFS8093H2oZgHamxED:bnfp4nl)*

**Comment by a-robinson** [comment]
Review status: 1 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/server/node.go, line 176 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12023#-KYFR3xtdT_WKXuoF1EX:-KYFZdD3_7viRg3iQ5YQ:bksl0oy) ([raw file](https://github.com/cockroachdb/cockroach/blob/22586f6ca440a77bc78538c996d8b10559a2672a/pkg/server/node.go#L176)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

wouldn't it be more robust to nuke stuff we _dont_ want? Also, since this has a relatively small number of callers, it would be nice to require that the passed-in clock is not nil.
</blockquote></details>

It certainly would be, it just seemed like it was going to be a pain to figure out which parameters need to be cleared out because when I tried it that way it led to a flake every few hundred test runs. I've gone back and found that the gossip field was the problem. Thanks for keeping me honest.

There are enough tests that hit this code path with a nil clock indirectly that keeping the check in seems worth it, though.

---

*[pkg/server/server.go, line 197 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12023#-KYFRiwzzFHjuDe_BgCQ:-KYFWI5XB0tOq-2nTt28:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aee560cbd36307a78eba71e62167b7e5c7112fe/pkg/server/server.go#L197)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

optional: flipping this seems cleaner, i.e. try to use the config value and only then call this function
</blockquote></details>

Done.

---

*[pkg/server/testserver.go, line 101 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12023#-KYFRusD82SV4P4u0ETn:-KYFYl1WSdpNeYaQWas5:b-4c5ezp) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aee560cbd36307a78eba71e62167b7e5c7112fe/pkg/server/testserver.go#L101)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

i think this cast is superfluous
</blockquote></details>

Good catch, done.

---

*[pkg/storage/gossip_test.go, line 155 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12023#-KYFSFIG5KBH7Cf9oBKA:-KYFZUkPNKzFobgxNTCO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/601de8a3231bf79cd73c9c2350ff9361b48d049d/pkg/storage/gossip_test.go#L155)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

you could extract this whole struct to avoid duplicating parts of it below, which seems fragile. you could remove some of the constants above as a result.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12023)*

**Comment by tamird** [comment]
Reviewed 1 of 6 files at r4, 4 of 4 files at r5, 1 of 1 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12023)*

**Pull request merged**
