### PR TITLE
Add Stephanie Bodoff to AUTHORS

### PR DESCRIPTION
**Pull request by ghost**
Release note: None

### CODE REVIEW

**Review by arulajmani — APPROVED** [review]

**Review by jlinder — CHANGES_REQUESTED** [review]
Hi Stephanie. Can you merge your commits into a single commit and then force-push to the branch? This will make it so the PR will follow [our philosophy](https://wiki.crdb.io/wiki/spaces/CRDB/pages/1411744698/Decomposing+changes+and+updating+PRs+during+reviews) for how we write commits.

**Comment by stbof** [comment]
> Hi Stephanie. Can you merge your commits into a single commit and then force-push to the branch? This will make it so the PR will follow [our philosophy](https://wiki.crdb.io/wiki/spaces/CRDB/pages/1411744698/Decomposing+changes+and+updating+PRs+during+reviews) for how we write commits.



> Hi Stephanie. Can you merge your commits into a single commit and then force-push to the branch? This will make it so the PR will follow [our philosophy](https://wiki.crdb.io/wiki/spaces/CRDB/pages/1411744698/Decomposing+changes+and+updating+PRs+during+reviews) for how we write commits.

I'm used to squashing multiple commits in the merge itself. I don't know how to do what you are asking.  Could you help me with the procedure.

**Comment by stbof** [comment]
> > Hi Stephanie. Can you merge your commits into a single commit and then force-push to the branch? This will make it so the PR will follow [our philosophy](https://wiki.crdb.io/wiki/spaces/CRDB/pages/1411744698/Decomposing+changes+and+updating+PRs+during+reviews) for how we write commits.
> 
> > Hi Stephanie. Can you merge your commits into a single commit and then force-push to the branch? This will make it so the PR will follow [our philosophy](https://wiki.crdb.io/wiki/spaces/CRDB/pages/1411744698/Decomposing+changes+and+updating+PRs+during+reviews) for how we write commits.
> 
> I'm used to squashing multiple commits into a single commit in the merge itself. I don't know how to do what you are asking. Could you help me with the procedure.

Nevermind. The docs team has instructions for this. I'll apply those.

**Comment by jlinder** [comment]
Apologies for not including info on how to fix this earlier. Here's how to fix it:

1. Get your local branch to have only one commit that contains the subject line, the `Release justification` line and the `Release note` line. If your local branch looks like the branch that is in the PR, then you'll likely need to run `git reset HEAD^` to get the commit 08727eea4f3b0a14434adcc2ae9a11b57cc11281 to be the branch head. Then amend the commit with `git commit --amend` to change the commit message.
2. Push the new branch head to your remote with `git push --force-with-lease FORK_NAME stephaniebodoff_authors`

**Comment by stbof** [comment]
@jlinder I believe this is fixed now.

**Review by jlinder — APPROVED** [review]
Indeed!

:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69881#-:-Mj5uf5HEJPsrFyLbFvP:b4o0hfn)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @stbof)

**Pull request merged**
