### PR TITLE
obsservice: add logs_service proto for OTLP collector

### PR DESCRIPTION
**Pull request by aadityasondhi**
This patch adds the required protos for implementing the logs_service for the OTLP collector. This will allow cockroach to export events to an OTEL collector in the form of OTEL-compatible logs using the `LogsServiceClient`. Additionally, obsservice can ingest these logs as a `LogsServiceServer` when used in place of an OTEL collector.

Epic: CRDB-16791

Release note: None

### CODE REVIEW

**Review by dhartunian — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93733#-:-NKsTvW17afswlu1T1oc:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93733)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi)

___
*[`pkg/obsservice/obspb/update-opentelemetry-proto.sh` line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93733#-NLMRoDu23TDVlUFuTQO:-NLMRoDu23TDVlUFuTQP:b9hff82) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a92b37c14ee338a75c5a0494629716de00200b8/pkg/obsservice/obspb/update-opentelemetry-proto.sh#L83)):*
> ```Shell
> # into:
> # option go_package = "v1";
> find $DEST_DIR -type f -name "*.proto" -exec sed -i '' -e "s/option go_package = \"go.opentelemetry.io\/proto\/otlp\/.*\/v1\"/option go_package = \"v1\"/" {} + ;
> ```

why did this change?
I don't see `-i` taking an argument in the man page.

**Review by aadityasondhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93733)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[`pkg/obsservice/obspb/update-opentelemetry-proto.sh` line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93733#-NLMRoDu23TDVlUFuTQO:-NLMYPy_Aw_K47N3efa-:bwi995l) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a92b37c14ee338a75c5a0494629716de00200b8/pkg/obsservice/obspb/update-opentelemetry-proto.sh#L83)):*
It errored on my local machine with:
```
./update-opentelemetry-proto.sh
Cloning opentelemetry-proto in /var/folders/sy/cstk63m54r992k2zybwh1_p80000gq/T/tmp.UX5yJRME.
Making a backup copy of opentelemetry-proto in /var/folders/sy/cstk63m54r992k2zybwh1_p80000gq/T/tmp.UVc0KC7t.
Copying protos.
Editing protos.
sed: 1: "opentelemetry-proto/com ...": invalid command code o
Deleted temp working directory /var/folders/sy/cstk63m54r992k2zybwh1_p80000gq/T/tmp.UX5yJRME
```

Did some digging and found: https://stackoverflow.com/questions/19456518/error-when-using-sed-with-find-command-on-os-x-invalid-command-code

> "On the OSX version of sed, the -i option expects an extension argument so your command is actually parsed as the extension argument and the file path is interpreted as the command code.
Try adding the -e argument explicitly and giving '' as argument to -i"

I am assuming your machine is running Linux?

**Review by aadityasondhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93733)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[`pkg/obsservice/obspb/update-opentelemetry-proto.sh` line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93733#-NLMRoDu23TDVlUFuTQO:-NLMZKuuBfV_QMYPArgz:byelf57) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a92b37c14ee338a75c5a0494629716de00200b8/pkg/obsservice/obspb/update-opentelemetry-proto.sh#L83)):*
<details><summary><i>Previously, aadityasondhi (Aaditya Sondhi) wrote…</i></summary><blockquote>

It errored on my local machine with:
```
./update-opentelemetry-proto.sh
Cloning opentelemetry-proto in /var/folders/sy/cstk63m54r992k2zybwh1_p80000gq/T/tmp.UX5yJRME.
Making a backup copy of opentelemetry-proto in /var/folders/sy/cstk63m54r992k2zybwh1_p80000gq/T/tmp.UVc0KC7t.
Copying protos.
Editing protos.
sed: 1: "opentelemetry-proto/com ...": invalid command code o
Deleted temp working directory /var/folders/sy/cstk63m54r992k2zybwh1_p80000gq/T/tmp.UX5yJRME
```

Did some digging and found: https://stackoverflow.com/questions/19456518/error-when-using-sed-with-find-command-on-os-x-invalid-command-code

> "On the OSX version of sed, the -i option expects an extension argument so your command is actually parsed as the extension argument and the file path is interpreted as the command code.
Try adding the -e argument explicitly and giving '' as argument to -i"

I am assuming your machine is running Linux? 
</blockquote></details>

I wonder if this breaks the Linux version since `-i` doesn't take an argument. I can add a condition based on the OS in the script to make it work for both.

**Review by aadityasondhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93733)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei)

___
*[`pkg/obsservice/obspb/update-opentelemetry-proto.sh` line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93733#-NLMRoDu23TDVlUFuTQO:-NLMnZhXDTUDn0vCqV8A:bs5jsz6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a92b37c14ee338a75c5a0494629716de00200b8/pkg/obsservice/obspb/update-opentelemetry-proto.sh#L83)):*
<details><summary><i>Previously, aadityasondhi (Aaditya Sondhi) wrote…</i></summary><blockquote>

I wonder if this breaks the Linux version since `-i` doesn't take an argument. I can add a condition based on the OS in the script to make it work for both.
</blockquote></details>

@andreimatei Fixed it to make it work with both OS. Let me know what you think.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93733)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aadityasondhi)

___
*[`pkg/obsservice/obspb/update-opentelemetry-proto.sh` line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93733#-NLMRoDu23TDVlUFuTQO:-NLbc4fN8VAwpu0cMdou:bqz7yfp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a92b37c14ee338a75c5a0494629716de00200b8/pkg/obsservice/obspb/update-opentelemetry-proto.sh#L83)):*
<details><summary><i>Previously, aadityasondhi (Aaditya Sondhi) wrote…</i></summary><blockquote>

@andreimatei Fixed it to make it work with both OS. Let me know what you think.
</blockquote></details>

damn BSDs

Let's find something that works across both of them, otherwise there's too many lines
I think this should work:
```
sed -i.bak -e ...
rm *.bak
```

And please extract this in a separate commit.

**Review by aadityasondhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93733)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei)

___
*[`pkg/obsservice/obspb/update-opentelemetry-proto.sh` line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93733#-NLMRoDu23TDVlUFuTQO:-NM9lUCF3qCv85tpE8CQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a92b37c14ee338a75c5a0494629716de00200b8/pkg/obsservice/obspb/update-opentelemetry-proto.sh#L83)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

damn BSDs

Let's find something that works across both of them, otherwise there's too many lines
I think this should work:
```
sed -i.bak -e ...
rm *.bak
```

And please extract this in a separate commit.
</blockquote></details>

Done.

**Review by andreimatei — APPROVED** [review]
LGTM

**Pull request merged**
