### PR TITLE
multitenant: improve admin function RELOCATE {NON_}VOTING test cases

### LINKED ISSUE #93420: multitenant: improve admin function RELOCATE {NON_}VOTING test cases
Address the TODO comments on these test cases fix the invalid test setup.

```
// TODO(ewall): Set up test to avoid "trying to add a voter to a store that already has a VOTER_FULL" error.
```

```
// TODO(ewall): Set up test to avoid "type of replica being removed (VOTER_FULL) does not match expectation for change" error.
```

```
// TODO(ewall): Set up test to avoid "list of voter targets overlaps with the list of non-voter targets" error.
```

Jira issue: CRDB-22327

Epic CRDB-16746

### PR DESCRIPTION
**Pull request by ecwall**
Fixes #93420
    
Address the TODO comments on these test cases fix the invalid test setup.
    
Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93421)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @ecwall, and @rafiss)

___
*[`pkg/sql/delegate/show_ranges.go` line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93421#-NJ7AVjM1q_NJT0ns9hR:-NJ7AVjM1q_NJT0ns9hS:byzt7n0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f394911abdbffc442689199eff2903767e9d3e28/pkg/sql/delegate/show_ranges.go#L73)):*
> ```Go
> 			replica_localities[array_position(replicas, lease_holder)] as lease_holder_locality,
> 			replicas,
> 			voting_replicas,
> ```

instead of adding these two columns here (a user-facing change)
you could modify your test to query `crdb_internal.ranges` instead of using SHOW RANGES.

If you keep the columns here you need a release note.

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93421)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @knz, and @rafiss)

___
*[`pkg/sql/delegate/show_ranges.go` line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93421#-NJ7AVjM1q_NJT0ns9hR:-NJeh0pp7urmFBPGrMGl:b-5ifdgr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f394911abdbffc442689199eff2903767e9d3e28/pkg/sql/delegate/show_ranges.go#L73)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

instead of adding these two columns here (a user-facing change)
you could modify your test to query `crdb_internal.ranges` instead of using SHOW RANGES.

If you keep the columns here you need a release note.
</blockquote></details>

Separated that change into its own PR.

**Review by knz — COMMENTED** [review]
I have three general questions about the direction of this PR:

1. we have a couple of logic tests in pkg/ccl/logictestccl/testdata/logic_test/tenant_unsupported that seem to also connect to the work you're doing here. How will this file need to change?

2. we have quite a few range-level unit tests in pkg/sql/logictest/testdata/logic_test/ranges including for the "alter range relocate" feature. Currently, this test is limited to run only in single-tenancy ("# LogicTest: 5node" at the top).   Do you have a plan to make this test work also with secondary tenants, e.g via a new logic test config "5node-tenant"?

3. the last two points are making me think about the implementation of the tests. Your PR, like those before it, are exclusively investing into go unit tests. However, I am seeing the above two logic test files and others like them, where the tests are much more compact and easy to follow. How much of the multitenancy testing strategy could we offload to our logic test framework?

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93421#-:-NJel0E54rAmd4gvRSyH:b-5m1i0l)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @ecwall, and @rafiss)

___
*[`pkg/sql/multitenant_admin_function_test.go` line 131 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93421#-NJekT2XEj9Z1Bf-_XrC:-NJekT2XEj9Z1Bf-_XrD:bn1sn52) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ebae323c7d2e21f332cf533e90c0247b4fa5da8/pkg/sql/multitenant_admin_function_test.go#L131)):*
> ```Go
> }
> 
> type replicaState struct {
> ```

I don't understand what this type is for, nor the purpose of the functions introduced below. Can you add docstrings that explains them?
___
*[`pkg/sql/multitenant_admin_function_test.go` line 584 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93421#-NJekeuLAtEE3CcHhx4X:-NJekeuLAtEE3CcHhx4Y:bnjjhl) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ebae323c7d2e21f332cf533e90c0247b4fa5da8/pkg/sql/multitenant_admin_function_test.go#L584)):*
> ```Go
> }
> 
> func TestExperimentalRelocateVoters(t *testing.T) {
> ```

I don't understand what this test is checking. Can you explain?
Ditto for the other tests below.

**Review by ecwall — COMMENTED** [review]
1. I have been updating `pkg/ccl/logictestccl/testdata/logic_test/tenant_unsupported` as I move the capability checks from SQL to KV, but the updates to the tests in this PR don't affect that file.
2. Yeah I think we need to support configuring tenant capabilities first so that tenants can be granted the required capabilities.  Right now those tests would still fail for secondary tenants, but the error message would be different.
3. I think we can move some of these tests into logic tests if after we are able to grant capabilities and after these tests no longer need testing knobs. The ones I am not sure about are the ones that require special zone config setup to complete before the tests are run (how do you run SucceedsSoon in a logic test?).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93421#-:-NJfPPEQBYD10VGWyv4a:b-sxmt3h)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @knz, and @rafiss)

___
*[`pkg/sql/multitenant_admin_function_test.go` line 131 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93421#-NJekT2XEj9Z1Bf-_XrC:-NJfALh3D8UeSAyU_Ac1:bqmjwcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ebae323c7d2e21f332cf533e90c0247b4fa5da8/pkg/sql/multitenant_admin_function_test.go#L131)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I don't understand what this type is for, nor the purpose of the functions introduced below. Can you add docstrings that explains them?
</blockquote></details>

Added.
___
*[`pkg/sql/multitenant_admin_function_test.go` line 584 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93421#-NJekeuLAtEE3CcHhx4X:-NJfANDRCnXwtkfuXlfv:bqmjwcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ebae323c7d2e21f332cf533e90c0247b4fa5da8/pkg/sql/multitenant_admin_function_test.go#L584)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I don't understand what this test is checking. Can you explain?
Ditto for the other tests below.
</blockquote></details>

Added.

**Review by knz — APPROVED** [review]
thanks

> how do you run SucceedsSoon in a logic test?

theres a `retry` directive for that.

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93421#-:-NJkEeD0AweHs77L820I:b-zheden)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @rafiss)

**Comment by ecwall** [comment]
bors r=knz

**Pull request merged**
