### PR TITLE
distsql: set up flows in parallel

### PR DESCRIPTION
**Pull request by RaduBerinde**
Use a pool of workers to send out `SetupFlow` requests in parallel.

The next step is accumulating the processors in the failed attempts and moving them over to the gateway node's flow (this is the reason we are waiting for the requests before running the local flow).

@asubiotto - I am not sure if there is a guarantee that there are no more outstanding sql executions when `stopper.ShouldStop()` is closed. I hope that is the case, since all our workers exit when that happens.. If it's not, what do you suggest in this case? (maybe listening for `ShouldStop()` as well where `Run` does `res := <-resultChan`?)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
I pushed another commit that allows queries happening when `ShouldStop()` is closed.

**Comment by asubiotto** [comment]
It's not guaranteed that there are no more outstanding sql executions when `stopper.ShouldStop()` is closed. Listening for `stopper.ShouldStop()` from where you put it is what I would suggest.

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql_running.go, line 32 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858#-KhYrDMR5owSpuMeRXFH:-KhYrDMR5owSpuMeRXFI:b-4238hw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9183eb12d863815e61f47fc9cfcf733baf3fc92a/pkg/sql/distsql_running.go#L32)):*
> ```Go
> )
> 
> // To allow queries to send out flow RPCs in parallel, we use a pool of workers
> ```

the pool is per DistSQLPlanner, but the planner is a singleton, right? Perhaps it's worth mentioning here that the pool is shared by multiple queries.

---

*[pkg/sql/distsql_running.go, line 46 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858#-KhYp0m-ZtFiTg4VGToV:-KhYp0m0GWhQCrkG3L9I:b-mkbst6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9183eb12d863815e61f47fc9cfcf733baf3fc92a/pkg/sql/distsql_running.go#L46)):*
> ```Go
> }
> 
> // runerResult is returned by a worker (via a channel) for each received
> ```

ru_n_n_er

---

*[pkg/sql/distsql_running.go, line 51 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858#-KhYpjTOZ8vIlq8pJ3kh:-KhYpjTOZ8vIlq8pJ3ki:b-7wfnti) ([raw file](https://github.com/cockroachdb/cockroach/blob/9183eb12d863815e61f47fc9cfcf733baf3fc92a/pkg/sql/distsql_running.go#L51)):*
> ```Go
> 	nodeID   roachpb.NodeID
> 	err      error
> 	response *distsqlrun.SimpleResponse
> ```

I think `SimpleResponse` also contains an error. Add a comment to `err` here explaining the difference.

---

*[pkg/sql/distsql_running.go, line 54 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858#-KhYpI2ZAINGesvR4dL0:-KhYpI2ZAINGesvR4dL1:b-1zokxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9183eb12d863815e61f47fc9cfcf733baf3fc92a/pkg/sql/distsql_running.go#L54)):*
> ```Go
> }
> 
> func (dsp *distSQLPlanner) initRunners(stopper *stop.Stopper) {
> ```

nit: consider creating a new `distSQLRunner` struct for the `distSQLPanner` methods in this new file. 

---

*[pkg/sql/distsql_running.go, line 70 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858#-KhYsRnbxTtkZxjeqGp1:-KhYsRncId01RyixJt9J:b-1oj16e) ([raw file](https://github.com/cockroachdb/cockroach/blob/9183eb12d863815e61f47fc9cfcf733baf3fc92a/pkg/sql/distsql_running.go#L70)):*
> ```Go
> 					} else {
> 						client := distsqlrun.NewDistSQLClient(conn)
> 						res.response, res.err = client.SetupFlow(req.ctx, req.flowReq)
> ```

I'm thinking whether a timeout here (separate from a query's timeout, which doesn't exist :) ) would be a good idea. What do you think?

---

*[pkg/sql/distsql_running.go, line 111 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858#-KhYqg5mcQMhdgeJ2gVw:-KhYqg5mcQMhdgeJ2gVx:bvcylgy) ([raw file](https://github.com/cockroachdb/cockroach/blob/9183eb12d863815e61f47fc9cfcf733baf3fc92a/pkg/sql/distsql_running.go#L111)):*
> ```Go
> 
> 	var resultChan chan runnerResult
> 	if len(flows) > 1 {
> ```

mind explaining how one stream is special?

---

*[pkg/sql/distsql_running.go, line 128 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858#-KhYryF10JQIzsMtjC0j:-KhYryF10JQIzsMtjC0k:b-m9nosf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9183eb12d863815e61f47fc9cfcf733baf3fc92a/pkg/sql/distsql_running.go#L128)):*
> ```Go
> 			return err
> 		}
> 		// Send out a request to the workers.
> ```

consider doing what the DistSender does - fall back to serial sending of RPCs if the pool has no workers. It's less important here, as these RPCs are supposed to be short, I guess, but still, I think that pool can still be subject to funkiness when faced with an unresponsive node.

---

*[pkg/sql/distsql_running.go, line 140 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858#-KhYt94ILoJ7NXtYgaGD:-KhYt94ILoJ7NXtYgaGE:b-3zmf59) ([raw file](https://github.com/cockroachdb/cockroach/blob/9183eb12d863815e61f47fc9cfcf733baf3fc92a/pkg/sql/distsql_running.go#L140)):*
> ```Go
> 
> 	var err error
> 	// Now wait for all RPCs to complete. Note that we are not waiting for the
> ```

nit: since you put this comment, spell it out more for the casual reader - we are waiting for the flows to be scheduled on remote nodes.

---

*[pkg/sql/distsql_running.go, line 152 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858#-KhYsdYgRL5AX6l3P4yS:-KhYsdYh1edaqKCIRbnz:blfba5s) ([raw file](https://github.com/cockroachdb/cockroach/blob/9183eb12d863815e61f47fc9cfcf733baf3fc92a/pkg/sql/distsql_running.go#L152)):*
> ```Go
> 			err = res.response.Error.ErrorDetail()
> 		}
> 		// TODO(radu): accumulate the flows that we couldn't set up and move them
> ```

nit: s/we couldn't/we failed to - to suggest errors, not anything broader

---

*[pkg/sql/distsql_running.go, line 168 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858#-KhYtSf33S4mBYGgPB72:-KhYtSf33S4mBYGgPB73:b1mcufd) ([raw file](https://github.com/cockroachdb/cockroach/blob/9183eb12d863815e61f47fc9cfcf733baf3fc92a/pkg/sql/distsql_running.go#L168)):*
> ```Go
> 		return err
> 	}
> 	ctx, flow, err := dsp.distSQLSrv.SetupSyncFlow(ctx, &localReq, recv)
> ```

I don't know what it entails, but if it's not very hard, I think in the next change we should try to optimistically schedule this sync flow in parallel with the others, and, if need be, create a second flow with the failures. You said something about not being able to run more than one flow per query per node at a time, but I hope we can relax that :)

---

*[pkg/sql/distsql_running.go, line 145 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858#-KhYuAQY1wvjLGKk0RYz:-KhYuAQY1wvjLGKk0RZ-:b5bcxey) ([raw file](https://github.com/cockroachdb/cockroach/blob/c72cc1261f71d155842bcf4b16355bc3231b9f4f/pkg/sql/distsql_running.go#L145)):*
> ```Go
> 		select {
> 		case <-dsp.stopper.ShouldStop():
> 			// The workers may be gone by now; just error out.
> ```

why would the workers be gone, exactly? Cause we closed the `RPCContext`? Shouldn't they return errors there?

I think it'd be a good idea to make sure that the workers always return (or rather, that the return channel is closed), rather than having every query have to listen to the stopper here. Perhaps giving the pool a cancellable context, that's cancelled by another goroutine, and doing something with that cancellation would help. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858#-:-KhYu2xHQ6kYg6lfFgBu:bnfp4nl)*

**Comment by RaduBerinde** [comment]
TFTR!

---

Review status: 0 of 4 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql_running.go, line 32 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858#-KhYrDMR5owSpuMeRXFH:-KhZ3lCozWw-umQLUfM3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9183eb12d863815e61f47fc9cfcf733baf3fc92a/pkg/sql/distsql_running.go#L32)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

the pool is per DistSQLPlanner, but the planner is a singleton, right? Perhaps it's worth mentioning here that the pool is shared by multiple queries.
</blockquote></details>

Done.

---

*[pkg/sql/distsql_running.go, line 46 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858#-KhYp0m-ZtFiTg4VGToV:-KhZ3n1IL8Rc_yXR6Qag:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9183eb12d863815e61f47fc9cfcf733baf3fc92a/pkg/sql/distsql_running.go#L46)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

ru_n_n_er
</blockquote></details>

Done.

---

*[pkg/sql/distsql_running.go, line 51 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858#-KhYpjTOZ8vIlq8pJ3kh:-KhZ4IGZx6ifVES3cZS8:b3texvv) ([raw file](https://github.com/cockroachdb/cockroach/blob/9183eb12d863815e61f47fc9cfcf733baf3fc92a/pkg/sql/distsql_running.go#L51)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think `SimpleResponse` also contains an error. Add a comment to `err` here explaining the difference.
</blockquote></details>

I tried to, but I couldn't come up with anything that makes sense. Changed `SetupFlow` to return nothing.

---

*[pkg/sql/distsql_running.go, line 70 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858#-KhYsRnbxTtkZxjeqGp1:-KhZBGXSBbHapq9fBgUU:bxxsvsw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9183eb12d863815e61f47fc9cfcf733baf3fc92a/pkg/sql/distsql_running.go#L70)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'm thinking whether a timeout here (separate from a query's timeout, which doesn't exist :) ) would be a good idea. What do you think?
</blockquote></details>

Seems reasonable, leaving a TODO for now.

---

*[pkg/sql/distsql_running.go, line 111 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858#-KhYqg5mcQMhdgeJ2gVw:-KhZBdopjrLD3Lf3MdTP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9183eb12d863815e61f47fc9cfcf733baf3fc92a/pkg/sql/distsql_running.go#L111)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

mind explaining how one stream is special?
</blockquote></details>

Done.

---

*[pkg/sql/distsql_running.go, line 128 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858#-KhYryF10JQIzsMtjC0j:-KhZBeKAXqf4mtkGoJWx:b-l1ardd) ([raw file](https://github.com/cockroachdb/cockroach/blob/9183eb12d863815e61f47fc9cfcf733baf3fc92a/pkg/sql/distsql_running.go#L128)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

consider doing what the DistSender does - fall back to serial sending of RPCs if the pool has no workers. It's less important here, as these RPCs are supposed to be short, I guess, but still, I think that pool can still be subject to funkiness when faced with an unresponsive node.
</blockquote></details>

Cool idea, done.

---

*[pkg/sql/distsql_running.go, line 140 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858#-KhYt94ILoJ7NXtYgaGD:-KhZBtbKqCBaw65Akd3B:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9183eb12d863815e61f47fc9cfcf733baf3fc92a/pkg/sql/distsql_running.go#L140)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: since you put this comment, spell it out more for the casual reader - we are waiting for the flows to be scheduled on remote nodes.
</blockquote></details>

Done.

---

*[pkg/sql/distsql_running.go, line 152 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858#-KhYsdYgRL5AX6l3P4yS:-KhZDT-lxKXQoiE9LS55:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9183eb12d863815e61f47fc9cfcf733baf3fc92a/pkg/sql/distsql_running.go#L152)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: s/we couldn't/we failed to - to suggest errors, not anything broader
</blockquote></details>

Done.

---

*[pkg/sql/distsql_running.go, line 168 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858#-KhYtSf33S4mBYGgPB72:-KhZDU13u0xckLT82E0l:bfaz4iz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9183eb12d863815e61f47fc9cfcf733baf3fc92a/pkg/sql/distsql_running.go#L168)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't know what it entails, but if it's not very hard, I think in the next change we should try to optimistically schedule this sync flow in parallel with the others, and, if need be, create a second flow with the failures. You said something about not being able to run more than one flow per query per node at a time, but I hope we can relax that :)
</blockquote></details>

Flows are identified are by <flowID, node> pair. If a query has multiple flows on a node, whatever other flow that tries to connect to one of them wouldn't have enough information to choose among them. We would need to add another identifier to each outbox spec.

Actually, this whole idea can't quite work the way we thought. Other nodes on which we may have already deployed flows would still try to connect to the hosts we intended to set up the flow on initially.. Outboxes would need to have two different hosts and try to connect to both in parallel (bleh). This needs more thought. Of course, we could also only do this for flows that have no incoming streams, which would include a large class of queries.

---

*[pkg/sql/distsql_running.go, line 145 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858#-KhYuAQY1wvjLGKk0RYz:-KhZBxmoA_Bh5PADn8PC:b-t52uab) ([raw file](https://github.com/cockroachdb/cockroach/blob/c72cc1261f71d155842bcf4b16355bc3231b9f4f/pkg/sql/distsql_running.go#L145)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

why would the workers be gone, exactly? Cause we closed the `RPCContext`? Shouldn't they return errors there?

I think it'd be a good idea to make sure that the workers always return (or rather, that the return channel is closed), rather than having every query have to listen to the stopper here. Perhaps giving the pool a cancellable context, that's cancelled by another goroutine, and doing something with that cancellation would help. 
</blockquote></details>

Because the stopper closed `ShouldStop()`, which apparently can happen while there are ongoing queries. To make them always return, the workers would need some other signal for when it's safe to exit; I don't know what that signal would be. That's what the stopper should be for, but apparently we're not using it correctly.

I wonder if using an unbuffered channel for `runnerChan` could collapse this into the "no available runners" case I just added above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858#-:-KhZIEk24ms-YQ0LOTAi:b-814g8k)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 9 files reviewed at latest revision, 11 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsql_running.go, line 145 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858#-KhYuAQY1wvjLGKk0RYz:-KhZKCO0syasumcwj8h_:bhom4yl) ([raw file](https://github.com/cockroachdb/cockroach/blob/c72cc1261f71d155842bcf4b16355bc3231b9f4f/pkg/sql/distsql_running.go#L145)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Because the stopper closed `ShouldStop()`, which apparently can happen while there are ongoing queries. To make them always return, the workers would need some other signal for when it's safe to exit; I don't know what that signal would be. That's what the stopper should be for, but apparently we're not using it correctly.

I wonder if using an unbuffered channel for `runnerChan` could collapse this into the "no available runners" case I just added above.
</blockquote></details>

Yeah, that should work, switched to an unbuffered channel.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql_running.go, line 51 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858#-KhYpjTOZ8vIlq8pJ3kh:-KhZPSu4S2bJeDTm1SEp:b-q74txj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9183eb12d863815e61f47fc9cfcf733baf3fc92a/pkg/sql/distsql_running.go#L51)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I tried to, but I couldn't come up with anything that makes sense. Changed `SetupFlow` to return nothing.
</blockquote></details>

great!

---

*[pkg/sql/distsql_running.go, line 168 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858#-KhYtSf33S4mBYGgPB72:-KhZNzTkQ9SUlUncbG5-:b9wqer7) ([raw file](https://github.com/cockroachdb/cockroach/blob/9183eb12d863815e61f47fc9cfcf733baf3fc92a/pkg/sql/distsql_running.go#L168)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Flows are identified are by <flowID, node> pair. If a query has multiple flows on a node, whatever other flow that tries to connect to one of them wouldn't have enough information to choose among them. We would need to add another identifier to each outbox spec.

Actually, this whole idea can't quite work the way we thought. Other nodes on which we may have already deployed flows would still try to connect to the hosts we intended to set up the flow on initially.. Outboxes would need to have two different hosts and try to connect to both in parallel (bleh). This needs more thought. Of course, we could also only do this for flows that have no incoming streams, which would include a large class of queries.
</blockquote></details>

Having the outboxes fallback to connecting to the gateway (or, generally, a 2nd host) doesn't seem horrible to me... I don't think it would have to be done in parallel; in fact I think it probably shouldn't, as it might succeed in connecting to both.

One thing I'm thinking about is on what errors exactly do we want to retry. We shouldn't retry on server-side errors or on grpc errors where the server might have received the request (I think there's a similar distinction in DistSender somewhere) - you don't want two flows.

---

*[pkg/sql/distsql_running.go, line 145 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858#-KhYuAQY1wvjLGKk0RYz:-KhZP9Tl8_dCygF0iaAe:b-58m4i8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c72cc1261f71d155842bcf4b16355bc3231b9f4f/pkg/sql/distsql_running.go#L145)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yeah, that should work, switched to an unbuffered channel.
</blockquote></details>

ah I misread this; I thought you were saying that the `SetupFlow()` RPCs just block if the stopper is stopped.
Anyway, kewl!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858#-:-KhZRN9NenscdiSeIlzm:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql_running.go, line 168 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858#-KhYtSf33S4mBYGgPB72:-KhZn5p0cuUcy9P9AWc-:b-bdx54t) ([raw file](https://github.com/cockroachdb/cockroach/blob/9183eb12d863815e61f47fc9cfcf733baf3fc92a/pkg/sql/distsql_running.go#L168)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Having the outboxes fallback to connecting to the gateway (or, generally, a 2nd host) doesn't seem horrible to me... I don't think it would have to be done in parallel; in fact I think it probably shouldn't, as it might succeed in connecting to both.

One thing I'm thinking about is on what errors exactly do we want to retry. We shouldn't retry on server-side errors or on grpc errors where the server might have received the request (I think there's a similar distinction in DistSender somewhere) - you don't want two flows.
</blockquote></details>

We can retry on server-side errors (the important one being version mismatch; other errors are failures of distsqlrun infrastructure, it's fine to retry for them also). Yeah, we can't retry if there's a communication error; hopefully if a host is down, we normally see the error on `GRPCDial`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858)*

**Comment by arjunravinarayan** [comment]
Reviewed 6 of 9 files at r4, 2 of 2 files at r5, 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/distsql_running.go, line 51 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858#-KhYpjTOZ8vIlq8pJ3kh:-KhcApxp6cW6JzhNpmFx:b-3qgmpm) ([raw file](https://github.com/cockroachdb/cockroach/blob/9183eb12d863815e61f47fc9cfcf733baf3fc92a/pkg/sql/distsql_running.go#L51)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

great!
</blockquote></details>

Looks like there is a difference - what used to be `could not parse '1-3' as type decimal` now became `rpc error: code = Unknown desc = could not parse '1-3' as type decimal`. Not sure if it matters.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/distsql_running.go, line 51 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858#-KhYpjTOZ8vIlq8pJ3kh:-KhcDl4_Yx0Nf8lejxfT:b-5gk9uf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9183eb12d863815e61f47fc9cfcf733baf3fc92a/pkg/sql/distsql_running.go#L51)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Looks like there is a difference - what used to be `could not parse '1-3' as type decimal` now became `rpc error: code = Unknown desc = could not parse '1-3' as type decimal`. Not sure if it matters.
</blockquote></details>

It does, `IsPermanentSchemaChangeError` cares. It seems that this kind of error should either be detected in the planning stage, or it should be emitted on output streams like other flow errors (as opposed to a "sync" error to SetupFlow).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsql_running.go, line 51 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858#-KhYpjTOZ8vIlq8pJ3kh:-KhcTjcI7MkULXzWHPMM:b4b4ioh) ([raw file](https://github.com/cockroachdb/cockroach/blob/9183eb12d863815e61f47fc9cfcf733baf3fc92a/pkg/sql/distsql_running.go#L51)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It does, `IsPermanentSchemaChangeError` cares. It seems that this kind of error should either be detected in the planning stage, or it should be emitted on output streams like other flow errors (as opposed to a "sync" error to SetupFlow).
</blockquote></details>

I removed the commit that removes Error from the response. I did clean up your original comment, there is now only one error in `runnerResult`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14858)*

**Pull request merged**
