### PR TITLE
builtins: allow *FromWKB methods to also take EWKB

### PR DESCRIPTION
**Pull request by otan**
It appears that PostGIS allows EWKB for all FromWKB methods. As such,
change the builtins code to allow for this to occur.

Refs: https://github.com/cockroachdb/django-cockroachdb/issues/148

Release note: None

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50584#-:-MAc2geD1zHt2uqDpK5O:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by otan** [comment]
bors r=sumeerbhola

TFTR!

**Comment by otan** [comment]
bors r-

oops, needata rebase

**Comment by otan** [comment]
bors r=sumeerbhola

**Pull request merged**
