### PR TITLE
colexec: enable hash aggregator and unordered distinct in vectorize auto

### PR DESCRIPTION
**Pull request by Azhng**
colexec: enable hash aggregator and unordered distinct to run in vecotrize auto

Release note (sql change): hash aggregator and unordered distinct is now
supported in vectorize=auto mode.

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45810)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/sql/colexec/execplan.go, line 627 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45810#-M1l7Yxi8aQXCjpaNatL:-M1l7Yxi8aQXCjpaNatM:bq2jvus) ([raw file](https://github.com/cockroachdb/cockroach/blob/4de7d1eb1be3903f37ae2de6bdac6ac1e1b0c4d7/pkg/sql/colexec/execplan.go#L627)):*
> ```Go
> 					aggSpec.GroupCols, aggCols,
> 				)
> 				result.CanRunInAutoMode = true
> ```

Nice! Could you add a comment to each one why it can be run in vectorize auto? Something along the lines of memory use. Also would be good to note that these operators don't spill to disk in the row execution engine either.

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45810)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/execplan.go, line 627 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45810#-M1l7Yxi8aQXCjpaNatL:-M1lAPYZ5mpMSK3O3MGi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4de7d1eb1be3903f37ae2de6bdac6ac1e1b0c4d7/pkg/sql/colexec/execplan.go#L627)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Nice! Could you add a comment to each one why it can be run in vectorize auto? Something along the lines of memory use. Also would be good to note that these operators don't spill to disk in the row execution engine either.
</blockquote></details>

Done.

**Review by asubiotto — CHANGES_REQUESTED** [review]
The CI failure with the memory limit is fixed in a PR I just merge to master. You can rebase to pick up the change.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45810#-:-M1lYjFu7f6QSPAiPUjY:b-6m7510)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/sql/colexec/execplan.go, line 627 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45810#-M1lXTkTAcMn4lRlz-Rp:-M1lXTkTAcMn4lRlz-Rq:bvgozoo) ([raw file](https://github.com/cockroachdb/cockroach/blob/80271d2ba758b705324f67b477c511fefb3c3adb/pkg/sql/colexec/execplan.go#L627)):*
> ```Go
> 					aggSpec.GroupCols, aggCols,
> 				)
> 				// Auto mode is enable for hashAggregator since it performs online
> ```

nit: `s/enable/enabled/`
___
*[pkg/sql/colexec/execplan.go, line 629 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45810#-M1lXfqv-U5dCtfXFJhV:-M1lXfqw0UoIyxQu-eQo:bxt1bfh) ([raw file](https://github.com/cockroachdb/cockroach/blob/80271d2ba758b705324f67b477c511fefb3c3adb/pkg/sql/colexec/execplan.go#L629)):*
> ```Go
> 				// Auto mode is enable for hashAggregator since it performs online
> 				// aggregation. This limits a large part of memory used by the
> 				// aggregator to a constant amount. However, hashAggregator does not
> ```

I'd probably change this to: `This limits memory growth in the aggregator to be proportional to the number of distinct groups.`. 
___
*[pkg/sql/colexec/execplan.go, line 629 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45810#-M1lYbPs3YryB9rcqOu4:-M1lYbPs3YryB9rcqOu5:b-e8tp70) ([raw file](https://github.com/cockroachdb/cockroach/blob/80271d2ba758b705324f67b477c511fefb3c3adb/pkg/sql/colexec/execplan.go#L629)):*
> ```Go
> 				// Auto mode is enable for hashAggregator since it performs online
> 				// aggregation. This limits a large part of memory used by the
> 				// aggregator to a constant amount. However, hashAggregator does not
> ```

nit: remove "However"
___
*[pkg/sql/colexec/execplan.go, line 630 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45810#-M1lY1hsANJVbMLTkNHc:-M1lY1hsANJVbMLTkNHd:brivryx) ([raw file](https://github.com/cockroachdb/cockroach/blob/80271d2ba758b705324f67b477c511fefb3c3adb/pkg/sql/colexec/execplan.go#L630)):*
> ```Go
> 				// aggregation. This limits a large part of memory used by the
> 				// aggregator to a constant amount. However, hashAggregator does not
> 				// implement disk spilling, but neither is the hashAggregator in the row
> ```

`s/neither is/neither does`
___
*[pkg/sql/colexec/execplan.go, line 672 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45810#-M1lYWJU54MG7f56kJ8J:-M1lYWJU54MG7f56kJ8K:b-b8fkv0) ([raw file](https://github.com/cockroachdb/cockroach/blob/80271d2ba758b705324f67b477c511fefb3c3adb/pkg/sql/colexec/execplan.go#L672)):*
> ```Go
> 				// distinct tuples into memory. This limits the memory consumption
> 				// proportionally to the number of distinct tuples in the table. Disk
> 				// spilling is not implemented for this operator, but neither is the
> ```

nit: I'd use the same phrasing as above: Unordered distinct does not spill to disk, but neither does...

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45810)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/execplan.go, line 629 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45810#-M1lXfqv-U5dCtfXFJhV:-M1lZM5DA3j0vvvKktdL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/80271d2ba758b705324f67b477c511fefb3c3adb/pkg/sql/colexec/execplan.go#L629)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I'd probably change this to: `This limits memory growth in the aggregator to be proportional to the number of distinct groups.`. 
</blockquote></details>

Done.
___
*[pkg/sql/colexec/execplan.go, line 630 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45810#-M1lY1hsANJVbMLTkNHc:-M1lZTVQ0hSRd5WEYOtp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/80271d2ba758b705324f67b477c511fefb3c3adb/pkg/sql/colexec/execplan.go#L630)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`s/neither is/neither does`
</blockquote></details>

Done.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45810#-:-M1lbS4u-TTqgPor4YxY:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by Azhng** [comment]
Close in favor of #45906

**Pull request closed without merging**
