### PR TITLE
kv: add trace events to latch and lock wait-queue state transitions

### PR DESCRIPTION
**Pull request by nvb**
This PR improves tracing around various aspects of contention and conflict resolution. This provides better observability into places where a request/transaction may block on the progress of another request/transaction.

The best way to visualize the impact of these changes is to look at the effect they had on the `pkg/kv/kvserver/concurrency/testdata/concurrency_manager` datadriven files.

#### kv: add trace events to lock wait-queue state transitions

This change adds trace events to each state transition observed by the ockTableWaiter while waiting on a collection of lockWaitQueues. This provides increased observability into the behavior of lock wait-queues on contended keys, including information about queue depth.

#### kv: add trace events to latch manager

This change adds trace events to the latch manager, indicating when a latch acquisition blocks on a currently held latch. This provides increased observability into blocking within the latch manager.

#### roachpb: print millisecond resolution in ContentionEvents

This commit updates ContentionEvent formatting to print with millisecond resolution, instead of truncating the output to 10ms resolution.

/cc @cockroachdb/kv

### CODE REVIEW

**Review by tbg — APPROVED** [review]
> Reviewed 13 of 13 files at r1, 3 of 3 files at r2, 13 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65099)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/concurrency/testdata/concurrency_manager/basic, line 146 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65099#-M_t6bqbB2fU7C2po6RV:-M_t6bqbB2fU7C2po6RW:bka8kpy) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd30130e281d712a52c7cf65988278a354e39250/pkg/kv/kvserver/concurrency/testdata/concurrency_manager/basic#L146)):*
> ```
> [3] sequence req4: sequencing request
> [3] sequence req4: acquiring latches
> [3] sequence req4: waiting to acquire write latch k@10.000000000,1, held by read latch k{-2}@14.000000000,1
> ```

`k{-2}` is `[k, k2)`?

**Review by nvb — COMMENTED** [review]
TFTR! It looks like we have some immediate use for this.

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65099#-:-M_v2znG9rilHPfiIr8j:b-yj1nwc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/kv/kvserver/concurrency/testdata/concurrency_manager/basic, line 146 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65099#-M_t6bqbB2fU7C2po6RV:-M_v2S2g2Aeb6swAtH5X:b-fevij8) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd30130e281d712a52c7cf65988278a354e39250/pkg/kv/kvserver/concurrency/testdata/concurrency_manager/basic#L146)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

`k{-2}` is `[k, k2)`?
</blockquote></details>

Yes, this comes from the implementation of `(roachpb.Span).String`.

**Comment by tbg** [comment]
Had a question looking at https://github.com/cockroachlabs/support/issues/1311#issuecomment-989334775, namely, if we have, say an `Export [a,z)` at the bottom (evaluating) and blocking on it (say) a `Scan [b,f)` and our traced request is doing (say) a `Put c`, will the trace events reveal the span of the `Export`, `[a,z)`? And I assume it will print a zero transaction?

**Comment by nvanbenschoten** [comment]
> will the trace events reveal the span of the Export, [a,z)?

It depends on the structure of the tree. The way the latch manager works is that it captures a btree snapshot and then iterates over all spans that the incoming request cares about. For each overlapping latch in these spans, it checks if there's a conflict and, if so, begins waiting.

If we wanted to guarantee that we waited in an order that reflects dependencies (e.g. always wait on `Export` first) then I think we'd have to do the full scan, collect a list of conflicting latches, sort them by the time that they were inserted (their `id` which is a sequence number, not their `timestamp`), then wait in that sorted order. That doesn't sound very expensive (just build up a slice, then sort it), but it also isn't free. So we'd want to make it worth It, maybe by also including more information about what exactly a request is waiting on.

> And I assume it will print a zero transaction?

Transactions don't really mean anything at the level of the latch manager, because latches are request-scoped and all transaction coordination takes place above them. So it won't print anything about transactions, but that also not really interesting at this level.

**Comment by tbg** [comment]
Thanks, that makes sense. Reason I was asking is that we've seen slow latches a few times and have been completely blind. After this PR, we're less blind but I wonder if we're still unable to swiftly give good answers. The slice idea sounds good. It's still not perfect, right? If our request is `Put(a)` and `Export[b,c)` is evaluating and `Scan[a,c)` is waiting, with what you're describing we would only pick up the `Scan`, not the `Export`? So our debugging will end at "we're waiting on a Scan, no idea why that's taking so long". We want a transitive closure. As a naive algorithm, visit all nodes (not leaves) that overlap our span. If the node extends out of the span, recursively visit that extra span as well before proceeding. The set of all leaves visited during this process are the requests we are (transitively) blocked on. We could report (the N oldest) of that as well as the queue depth (i.e. longest path from our req to a leaf).
I do wonder if this is making perfect the enemy of good, though I tend to think that it isn't - observability should be simple to interpret.

**Pull request merged**
