### PR TITLE
heapprofiler: properly preserve heap dumps, refactor some code

### LINKED ISSUE #50237: server:   heap profiler GC removes the wrong files
So there's logic to "garbage collect" heap profiler files so there's always no more than N files in the directory, configurable via cluster setting `"server.heap_profile.max_profiles"` (default 5)

The code is implemented in `(o *HeapProfiler) gcProfiles()`

This code has two **major** flaws:

- **it does not sort the files** and instead uses the directory order (FS-dependent / OS-dependent) to decide which files to remove

- **it removes files indiscriminately of type**

I can see in my cluster of interest that I have 5 files:

```
memprof.000000001448318504_2020-06-11T10_57_35.202.pprof
memprof.fraction_system_memory.000000019154821120_2020-06-05T13_22_13.241.pprof
memprof.fraction_system_memory.000000019331059712_2020-03-04T16_58_39.54.pprof
memprof.fraction_system_memory.000000019349680128_2020-06-05T13_26_32.349.pprof
memprof.fraction_system_memory.000000020150149120_2020-06-05T09_25_25.637.pprof
```

The 4 "fraction_system_memory" are from v19.1, this format is not used any more in v19.2. However, they count in the determination of which files to remove. The result is (for this cluster) that there is always at most one up to date pprof file remaining.

### PR DESCRIPTION
**Pull request by knz**
Fixes #50237 

See the individual commits for details.

### CODE REVIEW

**Comment by knz** [comment]
@bdarnell ok to backport this despite the change in filename structure?

**Comment by bdarnell** [comment]
Yeah, it's fine to backport with the filename change since the old version was pretty useless.

**Review by tbg — COMMENTED** [review]
Thanks Raphael. A couple of comments/ideas:

1. We also have the `COCKROACH_MEMPROF_INTERVAL` env var which is used here

https://github.com/cockroachdb/cockroach/blob/69fbe79a655a07f76513ab42661f0dfbd9fd5451/pkg/cli/start.go#L1298-L1299

It will also lead to files `${logdir}/memprof.<stuff>` to be written. Can you make sure that the two mechanisms don't clash? Ideally we would want to unify them but that may be too much to ask here. Perhaps the files written via the env var can get a `.COCKROACH_MEMPROF_INTERVAL` suffix.

2. a heap profile is like what, 300kb? It seems very restrictive to default to a max 72h retention. In practice we see that customers take much longer to come to us. I'm also not sure if we're regressing against the intention of the original code (clearly that intention didn't translate into action, but still), which was to keep "interesting" profiles around for a long time (~forever). The hope was that by looking at the profiles, you could get an idea of the largest X heap profiles, even when you were looking a week after things happened. Now, if I understand the commit message correctly, there will be nothing left.
I am also skeptical that the notion of a "ramp up" and the concomitant assumption of monotonicity is useful here. We profile, by default, every 10s (though the profile we get depends on the last GC cycle), which may not be enough to be monotonic across smaller leaks. Even with larger leaks, there can be wild fluctuations that break the ramp (if GC gets to free a giant slab, it may buy itself a short-lived dip that way). A better concept could simply be per process instance  - we chiefly care about profiles when processes crash, so the real ramp-up is always from when the process started until it blew up. Let's say we keep the top X per process instance (which as a nice side-effect, simplifies the code), and we make the retention interval _much_ larger. If the process crashes every 10.00001s (i.e. right after taking the first heap dump) we will rack up around ~100mb per hour in profiles, which of course is a shame. The scenario is contrived, of course. Most processes are long-running and will just keep 5 new profiles around. Perhaps the right thing to do use instead of an age policy is a size policy - we throw out the oldest profiles until we're below X mb (300?)
For all reasonable scenarios this leaves us with tons of interesting profiles over possibly weeks or months.

3. While we're here, I wonder if taking a heap profile is cheap enough to do it more frequently (every second?)

4. Now that we have a grouping of profiles into "runs" (whether we stick with your ramp ups or my per-process run), it would be nice to indicate visually the first one in the run (`memprof.<foo>.<bar>.FIRST`?)

5. It's bothered me in the past that the size in the filename was not human friendly. If you're willing to entertain that, then maybe the thing to do is to move away from the dots to a format that can accommodate 1) and 4) also, straw man:

```
memprof.run=%d,size=%d,hsize=%s,run=%d // or ",first" or ",env"
```

The filename basically unmarshals into a struct and you can do things like not deleting files that have the `env` property set, etc.

6. I realize I'm putting a lot of ideas on your plate, it's totally fine if you want to trim the amount of work you put in here. I would say the things I'm most skeptical about is the concept of ramp-up (per-process feels most useful to me) and the short retention period.

Haven't reviewed the code yet in case it changes based on my comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50446#-:-MAVhmbm1cfgt9DHOmMt:b-3z72b6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @tbg)

**Comment by knz** [comment]
> 1. ... COCKROACH_MEMPROF_INTERVAL ...

Ok I'll check that. Agreed that the filenames need to be distinguished.

> 2a. [...] It seems very restrictive to default to a max 72h retention. In practice we see that customers take much longer to come to us. I'm also not sure if we're regressing against the intention of the original code (clearly that intention didn't translate into action, but still), which was to keep "interesting" profiles around for a long time (~forever). 

- I did not know this was the intention. 
- I know from experience that we kept too many profiles for the registration server at some point, and it filled up the disk (+ the directory listings were kinda broken, ext4 is *not happy* with a single directory containing thousands of files). I believe this was a multi-month problem though.
- Therefore I believe we still should have a retention window. However, we could make it size-based instead of time-based. WDYT?

edit, I read this below

> Perhaps the right thing to do use instead of an age policy is a size policy - we throw out the oldest profiles until we're below X mb (300?)

Size it is then.

> The hope was that by looking at the profiles, you could get an idea of the largest X heap profiles, even when you were looking a week after things happened.

This is still possible given that the sizes are still in the file name.

> I am also skeptical that the notion of a "ramp up" and the concomitant assumption of monotonicity is useful here. [...]

The rest of this paragraph suggests to me that you misunderstood the code.
The logic in the heap profile already restricts profiles to sample only monotonic increases, inside 1-hour windows.

So if, say, over 4 10-second intervals your server has   100, 150, 80, 160 bytes allocated, the heap profiler already only generates files for the points at 100, 150, 160.

That logic is not changed in this PR.

There is a "flush" at 1 hour intervals though, so that the low water mark gets reset at every hour no matter what. So with the existing logic and my new logic, the code will preserve the last 5 profiles for every hour.


(Additionally, I can emit the PID in the filename, which ensures that there's an additional reset across node restarts.)

> For all reasonable scenarios this leaves us with tons of interesting profiles over possibly weeks or months.

The code as written here likely achieves that once we switch to a size limitation instead of duration (see above).

> 3. While we're here, I wonder if taking a heap profile is cheap enough to do it more frequently (every second?)

This seems out of scope and I am not directly interested to investigate this right now.

> Now that we have a grouping of profiles into "runs" (whether we stick with your ramp ups or my per-process run), it would be nice to indicate visually the first one in the run (memprof.<foo>.<bar>.FIRST?)

That sounds gimmicky. Given that the ramp-ups always start with the smallest size chronogically, a simple directory sort will provide you the first one (is the first one in the chrononological sequence)

> It's bothered me in the past that the size in the filename was not human friendly. If you're willing to entertain that, then maybe the thing to do is to move away from the dots to a format that can accommodate 1) and 4) also, straw man [...]

Huh, no to your strawman. Terrible operator experience with special characters in filenames.

What I can do however is this: `memprof.<timestamp>.<full size>.<humanize size>`

the humanize size is redundant but would help with visual identification.

**Comment by tbg** [comment]
Yep, I misunderstood ramps. Now that (I think, will see once I review) I understand, it sounds good.

> What I can do however is this: memprof.<timestamp>.<full size>.<humanize size>

If you can shoehorn 1) into this as well, sure. This is sort of where I started but with 1) and 4) it became too one-offy. Whatever works in the code will work for me.

> Size it is then.

👍 that'll be great to have, thanks!

> That sounds gimmicky.

Fair enough. Just for the record though, with the delay in contacting us often the interesting heap profile will be somewhere in the middle of the directory listing. But with the human readable sizes and a rough idea of when the OOM happened it should be easy enough to find the right dump (or rather, .FIRST wouldn't help much neither).

I'll review when you've updated, thanks again.

**Comment by knz** [comment]
:facepalm:  I forgot about this ....

**Comment by knz** [comment]
> > Size it is then.
> +1 that'll be great to have, thanks!

done.

> We also have the COCKROACH_MEMPROF_INTERVAL env var 
> Can you make sure that the two mechanisms don't clash?

They do ... :facepalm:

**Comment by knz** [comment]
>    We also have the COCKROACH_MEMPROF_INTERVAL env var
>   Can you make sure that the two mechanisms don't clash?

OK This is now fixed. You're going to like the result hopefully!

RFAL. Please take it one commit at a time.

**Comment by knz** [comment]
(Remaining CI failure is infra issue - not relevant to this PR)

**Comment by knz** [comment]
I have been running some servers with this code active on my machine and here are 3 flies in the ointment:

1) long upramps after node (re)start

   - under normal circumstances (eg `cockroach start-single-node` in a blank data directory, or after a restart) the RSS memory usage keeps creeping up, asymptotically for a *long* time - hours
   - this causes the code here to keep dumping memory profiles to disk every 10 seconds under the rule "keep dumping profiles as long as memory usage increases"

     (10s is the default sampling period, which we like when nodes are otherwise running near capacity to catch runaway OOM situations)
   - therefore, the code *appears* as if it never stops collecting data and/or will not GC these "upramps" for these long periods after start-up

   **Q: are we satisfied with this behavior?** 

2) default GC max file size not large enough?

   - a memory profile with my example server provisioned with 32GB RAM is ~100KB (not much load)
   - the GC has now a size-based heuristic, with max size defaulting at 128MB
   - so configuration gives up to ~1300 memory profiles
   - that means about 3-4 hours of continuous sampling with sampling every 10s
   - so a single node restart cycle will (as per the point above) bring the most recent sampling cycle up to the GC limit, and the GC will erase files from a previous node run

   That seems counter-productive **and a new version of the problem this PR is set out to solve**

3) risk of too many files

   - Solution to the above is perhaps to up the GC limit to larger than 128MB
   - Users will start to ask "what is this directory with so many files"
   - my experience and that of others is that ext4 and other command-line utilities like `ls` start to misbehave wrt performance at about 10000 files per directory:

     https://webmasters.stackexchange.com/questions/99539/what-is-a-recommended-maximum-number-of-files-in-a-directory-on-your-webserver
 
     https://adammonsen.com/post/1555/

   - 10000 files is 27 hours if the sampling never stops, e.g. if the initial node ramp-up takes a full day or more
   - after 10 days of frequent ramp-ups over many hours, and assuming the GC limit is upped from its 128MB default, we'd be looking at large directory count
   - this will cause questions to our tech support "why is this directory so slow" and "why can't I seem to be able to remove files" (`rm *` and shells will be very slow to process commands)
   - this suggests that our desire to keep more memory profiles is going to run afoul of directory size limits under this new code.

   **Q: is it perhaps worth extending this PR further with code that groups files together in zip archives?**

**Comment by knz** [comment]
CI fails here during `verify-archive` with this:
```
[14:05:57]W:		 [Test archive] ERROR: cockroach server exited with error: creating goroutine dump dir: mkdir goroutine_dump: read-only file system`
```

I'm going to check whether it's a run script that needs altering or whether the goroutine dump dir is misconfigured.

**Comment by tbg** [comment]
These are good observations, thank you. 1) is probably exacerbated by the fact that you were running an idle server, where we expect resource usage to slowly approach the peak from below, but it might happen in the same way on production systems and ideally we stay away from having to worry about too many files here.

If we're taking a step back, the decision to keep tracking the "peaks" in my recollection resulted from trying to simplify a more complicated heuristic around "crashes": when a crash occurs, we want a series of heap dumps leading up to the crash. Taking a profile whenever there's more in the heap than before (in the current process) seemed to check that box, but now you're finding that it creates the problem of preserving too many (uninteresting) files: a server that runs for two weeks without much happening (but slowly increased memory usage) followed by a harsh spike and then OOM will keep lots of old profiles around. It feels like we do want something similar to what you had in the first commit: we keep only the most recent N (10?) profiles *written by the current process* (and keep the other heuristics the same). In return, we should be able to lower the 128MiB limit quite a bit if we desire to do so, enough to avoid a problematic number of files per directory by default.

**Comment by knz** [comment]
> It feels like we do want something similar to what you had in the first commit: we keep only the most recent N (10?) profiles written by the current process (and keep the other heuristics the same). In return, we should be able to lower the 128MiB limit quite a bit if we desire to do so, enough to avoid a problematic number of files per directory by default.

Ok that works for me. It's easy enough to implement.

**Comment by knz** [comment]
Well actually not so much - we're still not happy about the case where there was an *unexplained memory spike* without a server crash.

However I can still use your suggestion by only keeping the last N files *in the current upramp*.

**Comment by tbg** [comment]
What's an upramp again? In the first commit it says

> - it now understands "ramp ups": a sequence of heap dumps where
  the heap was increasing in size.

but I remember misunderstanding that before. If, inside a process, the heap sizes are

1 10 2 15 99 50

then what's the current upramp? I would avoid anything that tries to reason about monotonicity of this sequence, as heap sizes always jitter due to GC (and I think you explained to me that that wasn't what an upramp was about).

**Comment by knz** [comment]
> If, inside a process, the heap sizes are
> 1 10 2 15 99 50
> then what's the current upramp?

If I was only looking at the Go heap (see below), then the current upramp is just "50".
The one before would be "2 15 99".
Then the proposal in my last comment above would be to keep all 3 upramps in your example (max 10 files per upramp, but here you have max 3 files so it "fits").

> I would avoid anything that tries to reason about monotonicity of this sequence, as heap sizes always jitter due to GC (and I think you explained to me that that wasn't what an upramp was about).

That is why one of the commits in this sequence has extended the concept to include RSS usage. I believe this was a gap in our collective understanding (and goals). Please look at the commit message for details.

**Comment by tbg** [comment]
> That is why one of the commits in this sequence has extended the concept to include RSS usage. I believe this was a gap in our collective understanding (and goals). Please look at the commit message for details.

But doesn't the same problem exist there, except more complicated to understand? Go returns memory to the OS, which may or may not reclaim it based on memory pressure. I feel that basing a heuristic on top of the complex workings of memory allocation in general just isn't something I'm very comfortable with. It may work fine here, it may work poorly there, but definitely nobody can really explain when exactly the numbers go up or down anywhere.
If we want such a heuristic, perhaps we would need to base it on the bytes allocated since the last collection, as indicated by the mem stats. But that seems like a new work avenue, whereas I'm hoping we can converge on a simple heuristic here and call it a day (heap profiles are useful and their sensible collection is important, but in most scenarios we're seeing relatively straightforwardly a recent OOM that is of interest). For example, I'd be ok with "largest N dumps from current process" being retained, even if in principle this could then wipe out a previous spike that didn't lead to an OOM when a later OOM hovers near the limit for long enough.

**Comment by knz** [comment]
>  For example, I'd be ok with "largest N dumps from current process" being retained

that's an interesting proposal (also new, we haven't discussed that before)

We can do a max-N queue per process during GC yes.  I'll investigate that in my next iteration.

**Comment by knz** [comment]
The last discussion above was moot - the code already intended to keep only the N files, but there was a bug in my code which prevented it to do so.

I have reworked the code to simplify collection. We now have 3 different profilers with coherent upramp detection and GC policies:

| Profiler | Trigger | Method | Output file name |
|--|--|--|--|
| Go heapprof | `GoAllocBytes` (same as before) | `pprof` (same as before) | `memprof.XXX.<allocbytes>` (same as before) |
| Jemalloc profiler | `CGoTotalBytes` (**NEW**) | Jemalloc `dump_heap_profile` (same as before) | `jeprof.XXX.<cgototal>` (byte count added to name) |
| (**NEW:**) Memory stats | `RSSBytes` | JSON from `runtime.MemStats` and jemalloc overall bytes | `memstats.XXXX.<rss>` |

For each profiler separately, collection occurs:

- if COCKROACH_MEMPROF_INTERVAL is set and zero, collection is entirely disabled.
- at a minimum, at the interval set by COCKROACH_MEMPROF_INTERVAL:
  - by default (if not set) every 1H
  - if non-zero, at that interval (values lower than 10s are clamped to 10s)
- additionally, at intervals of 10s, as long as usage is increasing since the previous profile was taken (as discussed earlier in this thread)

Meanwhile, the "max N per upramp" and "max N bytes total" retention policies are applied separately for each profiler (i.e. collection by one profiler does not impact which files are retained by other profilers).

**Comment by knz** [comment]
Here's an example output on a server running for 15 minutes:

```
kena@kenax ....com/cockroachdb/cockroach % ls -l cockroach-data/logs/heap_profiler
total 479
-rw-r-----  1 kena  kena  17653 Aug  8 18:16 jeprof.2020-08-08T16_16_32.751.110219264
-rw-r-----  1 kena  kena  17647 Aug  8 18:16 jeprof.2020-08-08T16_16_42.75.110239744
-rw-r-----  1 kena  kena  18083 Aug  8 18:29 jeprof.2020-08-08T16_29_02.836.110342144
-rw-r-----  1 kena  kena  18082 Aug  8 18:29 jeprof.2020-08-08T16_29_12.833.110362624
-rw-r-----  1 kena  kena  18199 Aug  8 18:31 jeprof.2020-08-08T16_31_52.942.110440448
-rw-r-----  1 kena  kena  44804 Aug  8 18:11 memprof.2020-08-08T16_11_22.747.31882520
-rw-r-----  1 kena  kena  46927 Aug  8 18:12 memprof.2020-08-08T16_12_12.743.32254272
-rw-r-----  1 kena  kena  56508 Aug  8 18:18 memprof.2020-08-08T16_18_22.752.32462864
-rw-r-----  1 kena  kena  59085 Aug  8 18:20 memprof.2020-08-08T16_20_12.837.33038512
-rw-r-----  1 kena  kena  60673 Aug  8 18:23 memprof.2020-08-08T16_23_02.781.33190872
-rw-r-----  1 kena  kena  12122 Aug  8 18:32 memstats.2020-08-08T16_32_02.837.249180160
-rw-r-----  1 kena  kena  12144 Aug  8 18:32 memstats.2020-08-08T16_32_12.838.249454592
-rw-r-----  1 kena  kena  12165 Aug  8 18:32 memstats.2020-08-08T16_32_22.838.249720832
-rw-r-----  1 kena  kena  12166 Aug  8 18:32 memstats.2020-08-08T16_32_32.836.249987072
-rw-r-----  1 kena  kena  12190 Aug  8 18:32 memstats.2020-08-08T16_32_42.839.250257408
```

What we see here:

- there was an upramp in Go heap allocations from the beginning to about 18.23. The `memprof` profiles were dumped until Go heap allocs stabilized. Only the last 5 files of the upramp were retained.
- there was an upramp in non-Go total alloc bytes, from the beginning to about 18.31. The `jeprof` profiles were dumped until non-Go allocations stabilized. Only the last 5 files of the upramp are retained.
- there was an upramp in RSS usage from the beginning until the present time 18.32. Memory stats are collected throughout. Only the last 5 files are retained.

**Comment by knz** [comment]
From a UX perspective, there's something super useful that comes from dumping all these files to the same directory. Consider this directory listing, sorted by file creation time:

```
kena@kenax ....com/cockroachdb/cockroach % ls -ltr cockroach-data/logs/heap_profiler
total 519
-rw-r-----  1 kena  kena  46927 Aug  8 18:12 memprof.2020-08-08T16_12_12.743.32254272
-rw-r-----  1 kena  kena  17647 Aug  8 18:16 jeprof.2020-08-08T16_16_42.75.110239744
-rw-r-----  1 kena  kena  56508 Aug  8 18:18 memprof.2020-08-08T16_18_22.752.32462864
-rw-r-----  1 kena  kena  59085 Aug  8 18:20 memprof.2020-08-08T16_20_12.837.33038512
-rw-r-----  1 kena  kena  60673 Aug  8 18:23 memprof.2020-08-08T16_23_02.781.33190872
-rw-r-----  1 kena  kena  18083 Aug  8 18:29 jeprof.2020-08-08T16_29_02.836.110342144
-rw-r-----  1 kena  kena  18082 Aug  8 18:29 jeprof.2020-08-08T16_29_12.833.110362624
-rw-r-----  1 kena  kena  18199 Aug  8 18:31 jeprof.2020-08-08T16_31_52.942.110440448
-rw-r-----  1 kena  kena  67369 Aug  8 18:33 memprof.2020-08-08T16_33_12.84.33578520
-rw-r-----  1 kena  kena  12281 Aug  8 18:33 memstats.2020-08-08T16_33_52.842.252121088
-rw-r-----  1 kena  kena  12281 Aug  8 18:34 memstats.2020-08-08T16_34_02.843.252387328
-rw-r-----  1 kena  kena  12306 Aug  8 18:34 memstats.2020-08-08T16_34_12.843.252657664
-rw-r-----  1 kena  kena  12306 Aug  8 18:34 memstats.2020-08-08T16_34_22.844.252928000
-rw-r-----  1 kena  kena  18324 Aug  8 18:34 jeprof.2020-08-08T16_34_33.307.177549312
-rw-r-----  1 kena  kena  12443 Aug  8 18:34 memstats.2020-08-08T16_34_33.314.253214720
```

What we see here is the sequence of memory increases coming from different types of memory usage over time. Notice for example how Go heap allocation here has its last dump at 18.33, but we see several increases in RSS usage and one increase in non-Go allocations after that. These are insights we did not have before.

**Review by tbg — APPROVED** [review]
:lgtm: not my most in-depth review, but I hope it serves you well enough. Thanks for all of the work you've put in.
How does debug zip handle all of these files now? Will they all be picked up?

Also, just to check my understanding of the ramp-up policy - if a server exhibits a sawtooth pattern, we will basically create new ramp ups all of the time, and in the worst case will never GC any of them until we hit the size limitation, right?

> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, 8 of 8 files at r5, 5 of 5 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, 10 of 10 files at r9, 3 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50446#-:-MEXsPC6-uVWB4vJoBxN:b-spkwlo)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bdarnell and @knz)

___
*[pkg/server/server.go, line 2002 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50446#-MEXkIz--rrMhPERkvVo:-MEXkIz--rrMhPERkvVp:b9t3z83) ([raw file](https://github.com/cockroachdb/cockroach/blob/5336da96e72d92ff03081cd6d1f5e5bddf45f9ea/pkg/server/server.go#L2002)):*
> ```Go
> 			return errors.Wrap(err, "creating goroutine dump dir")
> 		}
> 		goroutineDumper, err = goroutinedumper.NewGoroutineDumper(s.cfg.GoroutineDumpDirName)
> ```

don't you want `var err error` above this line instead of above this whole block? This pattern where you assign to `err` and check it only inside a nested block is unusual.
___
*[pkg/server/server.go, line 2015 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50446#-MEXkQ5k4nAsj748pjpH:-MEXkQ5k4nAsj748pjpI:bji28bi) ([raw file](https://github.com/cockroachdb/cockroach/blob/5336da96e72d92ff03081cd6d1f5e5bddf45f9ea/pkg/server/server.go#L2015)):*
> ```Go
> 			return errors.Wrap(err, "creating heap profiles dir")
> 		}
> 		heapProfiler, err = heapprofiler.NewHeapProfiler(s.cfg.HeapProfileDirName, s.ClusterSettings())
> ```

and here
___
*[pkg/server/dumpstore/dumpstore.go, line 31 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50446#-MEXlF7w8OxGqVy-v9Bk:-MEXlF7w8OxGqVy-v9Bl:b-c2rdoo) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe7a89204d1bbaaad942348c5d0e568f5354b183/pkg/server/dumpstore/dumpstore.go#L31)):*
> ```Go
> // the chronological order of their creation: this code is intended to
> // track file order using file names. This choice was made both to
> // avoid a mandatory sorting step after ioutil.ReadDir() and to
> ```

nit: `ioutil.ReadDir` already sorts.
___
*[pkg/server/dumpstore/dumpstore.go, line 33 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50446#-MEXlM2n3js2fsVxX1NL:-MEXlM2n3js2fsVxX1NM:bna9ev1) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe7a89204d1bbaaad942348c5d0e568f5354b183/pkg/server/dumpstore/dumpstore.go#L33)):*
> ```Go
> // avoid a mandatory sorting step after ioutil.ReadDir() and to
> // present unsurprising behavior if the filesystem doesn't preserve
> // timestamps properly (e.g. if a directory is restored from backup
> ```

not that this would be legal! But agreed that it's wise to be agnostic to the FS here.
___
*[pkg/server/dumpstore/dumpstore.go, line 44 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50446#-MEXmEOtCElxhaBsINhF:-MEXmEOtCElxhaBsINhG:b-5685a9) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe7a89204d1bbaaad942348c5d0e568f5354b183/pkg/server/dumpstore/dumpstore.go#L44)):*
> ```Go
> }
> 
> // Dumper represents a dump file producer.
> ```

isn't this really more of a GC policy? Nothing in `Dumper` is about producing files. It's about going through files and removing some of them, isn't it?
___
*[pkg/server/dumpstore/dumpstore.go, line 51 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50446#-MEXlx8e0DWEI8mhPR2x:-MEXlx8e0DWEI8mhPR2y:b1llhst) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe7a89204d1bbaaad942348c5d0e568f5354b183/pkg/server/dumpstore/dumpstore.go#L51)):*
> ```Go
> 	// The dumper may signal files that it wants to keep even
> 	// beyond the configured max size, by returning a boolean array
> 	// mapping 1-to-1 to the provided files.
> ```

it's a map from (index in files) to (preserved status), right? Why not `map[int]struct{}`?
Unclear from looking at the interface why this would be needed, but I assume it is.
___
*[pkg/server/dumpstore/dumpstore.go, line 52 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50446#-MEXlhEr1oTlqE2H8JzU:-MEXlhEr1oTlqE2H8JzV:b-grm9xt) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe7a89204d1bbaaad942348c5d0e568f5354b183/pkg/server/dumpstore/dumpstore.go#L52)):*
> ```Go
> 	// beyond the configured max size, by returning a boolean array
> 	// mapping 1-to-1 to the provided files.
> 	PreFilter(ctx context.Context, files []os.FileInfo, cleanupFn func(fileName string) error) (preserved map[int]bool, err error)
> ```

Dumper doesn't know about "max size", do you want to remove references to it?
___
*[pkg/server/dumpstore/dumpstore.go, line 102 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50446#-MEXmc7K-BQ3bZE2busC:-MEXmc7K-BQ3bZE2busD:b-icpkm3) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe7a89204d1bbaaad942348c5d0e568f5354b183/pkg/server/dumpstore/dumpstore.go#L102)):*
> ```Go
> 	// Then, remove all the oldest files whose size goes in excess of
> 	// maxS, except for those listed in preserved.
> 	removeOldAndTooBigExcept(ctx, dumper, files, now, maxS, preserved, cleanupFn)
> ```

having reviewed to the end of this file, I *think* `Dumper` is really a customizable GC policy which is applied on top of the size-based one here. Is that about right? Try to make it clear on `Dumper`, please.
___
*[pkg/server/heapprofiler/statsprofiler.go, line 39 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/50446#-MEXs3ahELbDJl7alLf8:-MEXs3ahELbDJl7alLf9:b-u19954) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c00e403c305637b111eb4980effe016a71e9795/pkg/server/heapprofiler/statsprofiler.go#L39)):*
> ```Go
> }
> 
> const statsFileNamePrefix = "memstats"
> ```

the corresponding heap profiles are named `jemalloc.*`, right? So in a sense even though these two dump types are related, this isn't obvious from the name. Should we rename either or both of them? Or maybe `memstats` is fine, if this really tracks *all* memory (i.e. does not exclude Go runtime allocs).
___
*[pkg/server/status/runtime.go, line 386 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/50446#-MEXrnXM35wr3Yz69tgR:-MEXrnXN87Y5mHWHCggE:bqafwsu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c00e403c305637b111eb4980effe016a71e9795/pkg/server/status/runtime.go#L386)):*
> ```Go
> }
> 
> // CGoMemStats reports what has been allocated outside of Go.
> ```

How come they don't include Go? I thought we make jemalloc the allocator for everything in this process, doesn't that make the runtime use it too? My understanding here is hazy.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50446)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bdarnell, @knz, and @tbg)

___
*[pkg/server/server.go, line 2002 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50446#-MEXkIz--rrMhPERkvVo:-MEYm23_8XjWOTAb_Y_6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5336da96e72d92ff03081cd6d1f5e5bddf45f9ea/pkg/server/server.go#L2002)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

don't you want `var err error` above this line instead of above this whole block? This pattern where you assign to `err` and check it only inside a nested block is unusual.
</blockquote></details>

Done.
___
*[pkg/server/server.go, line 2015 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50446#-MEXkQ5k4nAsj748pjpH:-MEYm2Pr6mGMAlTjGOmL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5336da96e72d92ff03081cd6d1f5e5bddf45f9ea/pkg/server/server.go#L2015)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

and here
</blockquote></details>

Done.
___
*[pkg/server/dumpstore/dumpstore.go, line 51 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50446#-MEXlx8e0DWEI8mhPR2x:-MEYmESR4IYRsgLMC62O:b-u8i0r2) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe7a89204d1bbaaad942348c5d0e568f5354b183/pkg/server/dumpstore/dumpstore.go#L51)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

it's a map from (index in files) to (preserved status), right? Why not `map[int]struct{}`?
Unclear from looking at the interface why this would be needed, but I assume it is.
</blockquote></details>

this way I can write `if preserved[x]` instead of `if _, ok := preserved[x]; ok`
___
*[pkg/server/dumpstore/dumpstore.go, line 52 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50446#-MEXlhEr1oTlqE2H8JzU:-MEYmqgk9dhbO-o0MRVH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe7a89204d1bbaaad942348c5d0e568f5354b183/pkg/server/dumpstore/dumpstore.go#L52)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Dumper doesn't know about "max size", do you want to remove references to it?
</blockquote></details>

Done.
___
*[pkg/server/dumpstore/dumpstore.go, line 102 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50446#-MEXmc7K-BQ3bZE2busC:-MEYo27Q7aofN91fBl3d:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe7a89204d1bbaaad942348c5d0e568f5354b183/pkg/server/dumpstore/dumpstore.go#L102)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

having reviewed to the end of this file, I *think* `Dumper` is really a customizable GC policy which is applied on top of the size-based one here. Is that about right? Try to make it clear on `Dumper`, please.
</blockquote></details>

Done.
___
*[pkg/server/heapprofiler/statsprofiler.go, line 39 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/50446#-MEXs3ahELbDJl7alLf8:-MEYo6Ct42a4XH2ZYqQ_:bgdgnib) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c00e403c305637b111eb4980effe016a71e9795/pkg/server/heapprofiler/statsprofiler.go#L39)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

the corresponding heap profiles are named `jemalloc.*`, right? So in a sense even though these two dump types are related, this isn't obvious from the name. Should we rename either or both of them? Or maybe `memstats` is fine, if this really tracks *all* memory (i.e. does not exclude Go runtime allocs).
</blockquote></details>

Yes `memstats.*` tracks everything,
`jeprof.*` only tracks non-go
and `heapprof.*`  only tracks go
___
*[pkg/server/status/runtime.go, line 386 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/50446#-MEXrnXM35wr3Yz69tgR:-MEYoDoZEuPdU4JFEjxF:b-k5e3nz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c00e403c305637b111eb4980effe016a71e9795/pkg/server/status/runtime.go#L386)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

How come they don't include Go? I thought we make jemalloc the allocator for everything in this process, doesn't that make the runtime use it too? My understanding here is hazy.
</blockquote></details>

jemalloc is only used for `malloc()` calls, by C/C++ code or other code using the C standard library.
The go heap allocator does not use `malloc()` and thus does not get profiled by `jemalloc`.

**Comment by knz** [comment]
> How does debug zip handle all of these files now? Will they all be picked up?

Yes - it specifies the pattern `*` and thus grabs all files in the sub-directory. This has been true for a couple of versions already.


> Also, just to check my understanding of the ramp-up policy - if a server exhibits a sawtooth pattern, we will basically create new ramp ups all of the time

true, with a max of 5 files per ramp-up (by default)

> and in the worst case will never GC any of them until we hit the size limitation, right?

Yes

**Comment by knz** [comment]
bors r=tbg

**Comment by knz** [comment]
bors r=tbg

**Comment by knz** [comment]
bors r=tbg

**Pull request merged**
