### PR TITLE
colexec: fix a couple of issues with outer hash joins

### LINKED ISSUE #39303: exec: a bug with RIGHT OUTER and FULL OUTER hash joins
Adopted from a failure on `lookup_join` logic test when ran with `experimental_on`. (As a side note, what is a hash join query doing in a "lookup join" test?)

The following test reliably fails.
```
# LogicTest: 5node-dist-vec

statement ok
CREATE TABLE small (a INT PRIMARY KEY, b INT)

statement ok
CREATE TABLE large (c INT, d INT)

statement ok
INSERT INTO small SELECT x, 3*x FROM
  generate_series(1, 10) AS a(x)

statement ok
INSERT INTO large SELECT 2*x, 4*x FROM
  generate_series(1, 10) AS a(x)

statement ok
ALTER TABLE small SPLIT AT SELECT a FROM small

statement ok
ALTER TABLE small EXPERIMENTAL_RELOCATE SELECT ARRAY[mod(i, 3) + 1], i FROM generate_series(1, 10) AS g(i)

statement ok
ALTER TABLE large SPLIT AT SELECT 2*i FROM generate_series(1, 10) AS g(i)

statement ok
ALTER TABLE large EXPERIMENTAL_RELOCATE SELECT ARRAY[mod(i, 3) + 1], 2*i FROM generate_series(1, 10) as g(i)

query T
SELECT url FROM [EXPLAIN ANALYZE SELECT small.b, large.d FROM large RIGHT HASH JOIN small ON small.b = large.c AND large.d < 30 ORDER BY 1 LIMIT 5]
----
https://cockroachdb.github.io/distsqlplan/decode.html#eJzcVk2PmzoU3b9fYd3Ve3pOwZCvsVQpm7aTUZVUmXTVZsHAbYJEMLJNNdEo_70COkphiIGhE027S2zO9b3nHB_5AWIR4MLbowL-BRhQcICCCxsKiRQ-KiVktlV8OA_ugdsUwjhJdba8oeALicAfQIc6QuCw9u4iXKEXoLSyWgFqL4zy8okM9548zCJPbhEo3CZerDixxgNrSrw4IA4ReodSAYX3YaRRcjJzyNfUtl2fuDbnfL5YT4HCMtWczBidZSfcedrfoSIi1Um2bgMFnSZRZUlhhL4Ov4f6wIn9xs7XtBdFRId75MRWsDlSKCDFzI8z3R3IzlO78jQzBpvjJq-xReDsSJ9HkltPktp7UXQiaWCxnCL3RFFBQh0D7CkD7ssz4Jxl4FQnjYUMUGJQqrTJkE2f1NB47andjQhjlNa03Nr6kCAnq_mH6zVZfl6_W5Gb5XwBFCL8pv-dsf_eynC7y3-V7ERnbg2fbns-8R79VIciPsfpiS-3i2NuhdQoLcYqErj_A4WP4T7UZNTPCR06H7ZQuk7EvN1aJRdiIBKLVQKj0MUtrnmnIUf9hxyVhmTtL7TdKvUG1rB6oXtkXg0FkxoK2EtmXgeKhq0yz2IDy-mVesNLpx67bOqN__TUa_DMz9S7en2h57Q3O2v3ChoOrPFf9grqQNKoXSI4A8utkvS630HOZRNhcuFEOJewz06EBs88voPs3pHwGzo__w6q6XyFKhGxwqritZXtTGYMtljYRolU-vhJCj8_pvi7zHF5hgaodLE7Kf7M42Ira7A9mLE-aMcMZh36drqBK313RDtmsFMF27-C3RLYroJdI3hoZmxoBLOGo0d9fGIGN_nEjG7wybiPT8zgJp-Y0Q0-mRjVmprFmvbxyVUfpc3gJqXN6KZE6BJlTy91pyzrCm8Qmz2JlPLddMxyM3OoVPXeHP_5EQAA__9DQ2TG

query II rowsort
SELECT small.b, large.d FROM large RIGHT HASH JOIN small ON small.b = large.c AND large.d < 30 ORDER BY 1 LIMIT 5
----
3   NULL
6   12
9   NULL
12  24
15  NULL
```
Note that the output of the vectorized engine is not deterministic on the last query, so maybe the problem is with the hash router although I think the hash joiner is more likely culprit with the unordered synchronizer being the cause of the non-determinism. I also played around with some variations of the query (like switching the order of the tables and having `LEFT HASH JOIN`), and it appears that the problem is only with `RIGHT OUTER` hash join.

Here is the plan:
Screen Shot 2019-08-03 at 8 11 21 PM

### LINKED ISSUE #40371: exec: a bug with hash joiner when build table is empty
If we run the following logic test:
```
# LogicTest: local-vec

statement ok
CREATE TABLE empty (x INT)

statement ok
CREATE TABLE onecolumn (x INT); INSERT INTO onecolumn(x) VALUES (44), (NULL), (42)

query II colnames
SELECT * FROM empty AS a(x) FULL OUTER JOIN onecolumn AS b(y) ON a.x = b.y ORDER BY b.y
----
x     y
NULL  NULL
NULL  42
NULL  44
```
we'll get an out of bounds error:
```
                testdata/logic_test/join:228: SELECT * FROM empty AS a(x) FULL OUTER JOIN onecolumn AS b(y) ON a.x = b.y ORDER BY b.y
                expected success, but found
                (XX000) internal error: unexpected error from the vectorized runtime: runtime error: index out of range
                error.go:70: in func1()
                DETAIL: stack trace:
                github.com/cockroachdb/cockroach/pkg/sql/exec/execerror/error.go:70: func1()
                runtime/panic.go:522: gopanic()
                runtime/panic.go:44: panicindex()
                github.com/cockroachdb/cockroach/pkg/col/coldata/vec.eg.go:1002: Copy()
                github.com/cockroachdb/cockroach/pkg/sql/exec/hashjoiner.go:962: congregate()
...
```
What happens is that for the build table, hash joiner creates `Vec`s of zero length and then appends to them in order to accumulate all the tuples from the build side. When the hash table is built, the hash joiner probes it and then congregates the output. To do that we copy the data from the accumulated `Vec`s using `prober.buildIdx` as the selection vector. Here is a problem: in case of outer joins some rows on the left might have a match, some might not, those without a match will have a 0 in the corresponding spot in `prober.buildIdx`. But if the build table was empty, the length of the accumulated `Vec`s is 0, so we get an out of bounds.

This can be fixed by adding a check whether `ht.size > 0` which seems a little like a hack to me because for all unmatched rows from the build table we'll be copying the zeroth row of the hash table (whatever it happens to be) and then setting a null at the corresponding index. It feels like the correct way to put the build table rows into the output is to copy the actual rows only if they were matched and skip those that were unmatched. However, it'll probably have a performance hit.

cc @jordanlewis thoughts?

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: fix a bug with RIGHT OUTER hash join**

Previously, probeRowUnmatched was not updated correctly in case of
non-distinct build table - the values were only set to 'true', but the
slice was never reset between subsequent probe batches nor the values
were set to 'false' when they were, in fact, 'false'. Now this is
fixed.

Fixes: #39303.

**colexec: minor refactor of hash joiner**

**colexec: fix hash joiner when the build table is empty**

Previously, with an outer hash join with an empty build table but non-empty
probe table we would hit index out of bounds error. The root problem is
that we always copy the values vector for the build table regardless
of whether the corresponding rows actually matched. Now before copying
we make sure that the hash table is not empty and also for all unmatched
rows we set buildIdx to 0 so that we can copy the garbage zeroth row
(the setting of NULLs later will take care of the correctness).

Fixes: #40371.
Addresses: #38994.

**colexec: add a unit test with an empty build table for hash joiner**

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
As a nice bonus, this PR combined with #40995 now makes vectorized engine pass `join` logic test fail (on the queries that are supported).

**Comment by yuzefovich** [comment]
Friendly ping.

**Review by asubiotto — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 6 of 6 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41151)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/col/coldata/vec.go, line 58 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41151#-LrATorx8Avoa1Bi855P:-LrATory4SMVMwpJz6Qp:bukv19z) ([raw file](https://github.com/cockroachdb/cockroach/blob/b40b49d407842db6b86576db5933a61e4322bc42/pkg/col/coldata/vec.go#L58)):*
> ```Go
> 	// the tuple Sel64[idx] will be skipped if SkipTuples[idx] is true.
> 	// NOTE: this can only be set when Sel64 is set and SelOnDest is false.
> 	SkipTuples []bool
> ```

My general feeling with adding arguments to `CopySliceArgs` is that we shouldn't, especially if it seems like we could convert the booleans to a selection vector. It adds complexity and specialization to already complex and specialized code. 
___
*[pkg/sql/colexec/hashjoiner_test.go, line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41151#-LrASVCR2n-k1aUNVZ1n:-LrASVCR2n-k1aUNVZ1o:b40w5m4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e748f4a3e39a4c696e5114bb0534a2a7a3a8ad9/pkg/sql/colexec/hashjoiner_test.go#L168)):*
> ```Go
> 
> 			// Test right outer join with non-distinct left build table with an
> 			// unmatched row from the right followed by a matched one.
> ```

Can you slightly expand *why* you're testing this?
___
*[pkg/sql/colexec/utils_test.go, line 319 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41151#-LrAY1drCXshlAG5eqsd:-LrAY1drCXshlAG5eqse:b-p3ujnd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2547066f32188bb3c26bed74dbf080e77356c9b9/pkg/sql/colexec/utils_test.go#L319)):*
> ```Go
> // with t.
> func runTestsWithFn(
> 	t *testing.T, tups []tuples, typs [][]coltypes.T, test func(t *testing.T, inputs []Operator),
> ```

Maybe expand the comment

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41151)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/col/coldata/vec.go, line 58 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41151#-LrATorx8Avoa1Bi855P:-LrBJXHx6dqx8GWj8mZZ:bm98kvn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b40b49d407842db6b86576db5933a61e4322bc42/pkg/col/coldata/vec.go#L58)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

My general feeling with adding arguments to `CopySliceArgs` is that we shouldn't, especially if it seems like we could convert the booleans to a selection vector. It adds complexity and specialization to already complex and specialized code. 
</blockquote></details>

Hm, I looked into this, but it's more complicated than simply converting the booleans to a selection vector. We also need a way to specify the "destination" of those indices that are in the selection vector. For example, if we have `Sel64 = [0, 1, 2]` and `SkipTuples = [1]`, when copying we want 0 to be copied at position 0 and 2 at position 2. However, if we "apply" boolean vector, we'll get `Sel64 = [0, 2]` which will copy 2 at position 1. At the same time, if insert a random index to shift it, we'll get the same problem as the one I'm trying to address - we will be copying unnecessary data. I don't like this solution either, but it seems to be the least evil I can think of.
___
*[pkg/sql/colexec/hashjoiner_test.go, line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41151#-LrASVCR2n-k1aUNVZ1n:-LrBHvHd2UmFarzeUzfD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e748f4a3e39a4c696e5114bb0534a2a7a3a8ad9/pkg/sql/colexec/hashjoiner_test.go#L168)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Can you slightly expand *why* you're testing this?
</blockquote></details>

Done.
___
*[pkg/sql/colexec/utils_test.go, line 319 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41151#-LrAY1drCXshlAG5eqsd:-LrBJT4w8LPHorSpoTif:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2547066f32188bb3c26bed74dbf080e77356c9b9/pkg/sql/colexec/utils_test.go#L319)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Maybe expand the comment
</blockquote></details>

Done.

**Review by asubiotto — COMMENTED** [review]
> Reviewed 11 of 11 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41151)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/col/coldata/vec.go, line 58 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41151#-LrATorx8Avoa1Bi855P:-LroJj1W0lu3Fd4aJ3bO:b5bva7y) ([raw file](https://github.com/cockroachdb/cockroach/blob/b40b49d407842db6b86576db5933a61e4322bc42/pkg/col/coldata/vec.go#L58)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Hm, I looked into this, but it's more complicated that simply converting the booleans to a selection vector. We also need a way to specify the "destination" of those indices that are in the selection vector. For example, if we have `Sel64 = [0, 1, 2]` and `SkipTuples = [1]`, when copying we want 0 to be copied at position 0 and 2 at position 2. However, if we "apply" boolean vector, we'll get `Sel64 = [0, 2]` which will copy 2 at position 1. At the same time, if insert a random index to shift it, we'll get the same problem as the one I'm trying to address - we will be copying unnecessary data. I don't like this solution either, but it seems to be the least evil I can think of.
</blockquote></details>

As discussed, the index out of bounds was coming from calling `Copy` with a source end index past the end of the source slice, which should be invalid. We should change the caller to not copy when this is the case. There are also cases where we will copy garbage values, but that's ok.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41151)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/col/coldata/vec.go, line 58 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41151#-LrATorx8Avoa1Bi855P:-LrohPZNBb2qI3l6NxJf:b5acd38) ([raw file](https://github.com/cockroachdb/cockroach/blob/b40b49d407842db6b86576db5933a61e4322bc42/pkg/col/coldata/vec.go#L58)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

As discussed, the index out of bounds was coming from calling `Copy` with a source end index past the end of the source slice, which should be invalid. We should change the caller to not copy when this is the case. There are also cases where we will copy garbage values, but that's ok.
</blockquote></details>

I removed this `SkipTuples` thing.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r7, 1 of 1 files at r8, 4 of 4 files at r9, 4 of 4 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41151#-:-Lrpknf35mn2OYnmaeMN:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

**Comment by yuzefovich** [comment]
TFTRs!

**Pull request merged**
