### PR TITLE
sql, ui: introduce `sql.crud_query.count` QPS metric

### PR DESCRIPTION
**Pull request by dhartunian**
Previously, customers struggled to get an accurate picture of "QPS" on a cluster, due to a number of factors.

First, our `sql.query.count` metric includes counts of transaction control statements which greatly inflate the "QPS" in a confusing way to a customer.

Second, the Metrics page in DB Console included a "QPS" metric which was a client-side sum of the insert/update/delete/select counters. This metric wasn't available to scrape or view in line graphs which led to confusion.

In this PR we introduce the `sql.crud_query.count` and `sql.crud_query.started.count` metric which is incremented along with the insert/update/delete/select counters.

This metric is added to the SQL chart at the top of the overview dashboard. That chart is renamed to have the title `SQL Queries Per Second` for clarity and the box on the right hand side now uses this metric directly.

Resolves: CRDB-25876
Epic: CRDB-37557

Release note (ops change): Two new metrics are available `sql.crud_query.count` and `sql.crud_query.started.count` which measure the number of insert/update/delete/select queries executed and started respectively.

### CODE REVIEW

**Review by angles-n-daemons — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132922#-:-O9j_pEf6uqPTb0DUV_p:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aa-joshi, @arjunmahishi, and @dhartunian)

___
*[`pkg/sql/conn_executor.go` line 4439 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132922#-O9j_cqDAZI42T7Mpfzo:-O9j_cqDAZI42T7Mpfzp:b-yx44y6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d99190c784ed56ab22a105044a0f0b6e5e91e80/pkg/sql/conn_executor.go#L4439)):*
> ```Go
> 	DeleteCount telemetry.CounterWithMetric
> 	// TotalCRUDCount includes all 4 CRUD statements above.
> 	TotalCRUDCount telemetry.CounterWithMetric
> ```

I feel that something akin to `CRUDQueryCount` will better match the rest of the changeset.

Just a suggestion, non-blocking.
___
*[`pkg/sql/exec_util.go` line 888 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132922#-O9j_L8i6vhzwJBJghw9:-O9j_L8i6vhzwJBJghwA:bjwa7hh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d99190c784ed56ab22a105044a0f0b6e5e91e80/pkg/sql/exec_util.go#L888)):*
> ```Go
> 		Unit:        metric.Unit_COUNT,
> 	}
> 	MetaTotalCRUDStarted = metric.Metadata{
> ```

:tada:

**Comment by dhartunian** [comment]
Tiny demo using
`./cockroach demo movr --multitenant=false --nodes 9 --geo-partitioned-replicas --with-load`

which shows that QPS in graph matches the box, and also that the count is the sum of 23.6 + 13.5.

Screenshot 2024-10-22 at 14 29 20

**Review by dhartunian — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132922#-:-O9pfeD4AAnGB1x4H0pI:b-814g8k)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aa-joshi, @angles-n-daemons, and @arjunmahishi)

___
*[`pkg/sql/conn_executor.go` line 4439 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132922#-O9j_cqDAZI42T7Mpfzo:-O9pRFVX9QO-g3MefmIy:b-ho5wpv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d99190c784ed56ab22a105044a0f0b6e5e91e80/pkg/sql/conn_executor.go#L4439)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

I feel that something akin to `CRUDQueryCount` will better match the rest of the changeset.

Just a suggestion, non-blocking.
</blockquote></details>

Agreed. Done.

**Comment by dhartunian** [comment]
bors r=angles-n-daemons

**Pull request merged**
