### PR TITLE
sql: support SHOW TRACE FOR SELECT ... AS OF SYSTEM TIME 

### PR DESCRIPTION
**Pull request by andreimatei**
Release note: SHOW TRACE FOR SELECT ... AS OF SYSTEM TIME is now
supported.

Before this patch, the Executor wasn't recognizing the AS OF SYSTEM TIME
and so the SELECT was failing with a planning error.

I'm going to cherry-pick the first commit into 1.1 because a client wants it.

### CODE REVIEW

**Comment by knz** [comment]
Ugh. Why do it this way? Does this not work:
`SELECT * FROM [SHOW TRACE FOR SELECT ....] AS OF SYSTEM TIME...`?

would not need extra code.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20162#-:-KzPlHeA1KMWwwGrLk5s:bg48xfw)*

**Comment by andreimatei** [comment]
`SELECT * FROM [SHOW TRACE FOR SELECT ....] AS OF SYSTEM TIME...` "works", but that's not a query I would write (and it's also not the query that @tschottdorf and friends wrote).

**Comment by andreimatei** [comment]
Like, `SHOW TRACE FOR` is special; you should be able to put it in front of anything; I don't think of what comes after it as a subquery (for which we indeed don't support AOST).

**Comment by knz** [comment]
But that's the problem, right, I can't write `SELECT message from [SHOW TRACE FOR SELECT ... AS OF SYSTEM TIME ...` with your change, it wouldn't work.

So if your PR really wants to address the use case "stick SHOW TRACE FOR in front of something and expect it to work", there is more work to do (make the isAsOf function recurse, or perhaps use `walkPlan()`)

**Comment by mjibson** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/logictest/testdata/logic_test/show_trace, line 722 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20162#-KzPsxnNJYMfJ4dGDCnc:-KzPsGLAEpCuZGDZpuMY:bcp6m7r) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7013cab0f05286952df29f4e87dcbaf5b522a29/pkg/sql/logictest/testdata/logic_test/show_trace#L722)):*
> ```
> # not return the error, see #20157).
> statement error pq: database "t" does not exist
> SHOW TRACE FOR SELECT * FROM t.abc AS OF SYSTEM TIME '2017-01-01'
> ```

Can there be a test where it doesn't return an error, to guarantee it works?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20162)*

**Comment by andreimatei** [comment]
Indeed; I think ideally `AS OF SYSTEM TIME` should be allowed in any select, including the ones that our code considers subqueries. But doing that is more involved; we need to make some of, but not all of, the reads in a query non-transactional. Just exploring the tree and fishing out AS OF SYSTEM TIME would be, in my opinion, the wrong way to go; for example if you have a union of two things or a join and one side has it and the other doesn't, it'd be incorrect to just fish it out and set a txn timestamp.
That's why I think what I have here is simple and worth doing; it'll be the last time we hear of this problem because, let's face it, nobody knows the `FROM [...]` syntax.

**Comment by knz** [comment]
Be sure to also test explicit PREPARE/EXECUTE statements here.

**Comment by knz** [comment]
@jordanlewis I'd like you to have a second look as your insight wrt plan caching may influence the evaluation of this approach.

**Comment by andreimatei** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/logictest/testdata/logic_test/show_trace, line 722 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20162#-KzPsxnNJYMfJ4dGDCnc:-KzPt6cSge_e-Vi1PXei:bmlqv6q) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7013cab0f05286952df29f4e87dcbaf5b522a29/pkg/sql/logictest/testdata/logic_test/show_trace#L722)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Can there be a test where it doesn't return an error, to guarantee it works?
</blockquote></details>

well you tell me. As far as I can see, I can't use any expression with AS OF SYSTEM TIME, so I can't run a query at a present time. And so without that I need to write a program to get the current timestamp so I can't do it in a logic test. I think that'd be overkill for testing this.
Also, this test does show that something works - we get to planning the statement and we pretty convincingly read descriptors at an old timestamp.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20162)*

**Comment by knz** [comment]
Regarding the design I still believe it's unfortunate to create a situation we have statements that are valid in one syntactic context (e.g. at the top level) but not at another (e.g. in a subquery). 
The problem here is one of assymmetry -- we're trying very hard in other places to ensure that SQL is algebraic (the same expression has the same meaning in every situation) and here you're just casually breaking the rule simple because you don't want to call `walkPlan` with a suitable plan visitor and instead bake a half-functional predicate that's just a glorified `_, ok := v.(cast); return ok`.

**Comment by mjibson** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/logictest/testdata/logic_test/show_trace, line 722 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20162#-KzPsxnNJYMfJ4dGDCnc:-KzPyMBp5w9cPPCClJtY:b-t7b03v) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7013cab0f05286952df29f4e87dcbaf5b522a29/pkg/sql/logictest/testdata/logic_test/show_trace#L722)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

well you tell me. As far as I can see, I can't use any expression with AS OF SYSTEM TIME, so I can't run a query at a present time. And so without that I need to write a program to get the current timestamp so I can't do it in a logic test. I think that'd be overkill for testing this.
Also, this test does show that something works - we get to planning the statement and we pretty convincingly read descriptors at an old timestamp.
</blockquote></details>

How about adding something in as_of_test.go? It already does all of the work of getting a timestamp at which something is present.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20162)*

**Comment by andreimatei** [comment]
> and here you're just casually breaking the rule simple because you don't want to call walkPlan with a suitable plan visitor 

Please be more generous with what I want and what I don't want; I want everything to be clean and great.
I didn't implement AS OF SYSTEM TIME; I see myself as an innocent bystander. This change makes AOST work in more contexts, not fewer. It's making our language more "symmetric".
I'm trying to address an issue with `SHOW TRACE FOR` that someone is complaining about. You're complaining about issues with AOST; `select * from (SELECT * from t.t AS OF SYSTEM TIME '2017-11-20')` does not work.

Now, what is your suggestion exactly? We write a visitor that recognizes `AOST` - cool; but it needs to reject the general query in which some sources have AOST and others don't. How would we do that exactly?

**Comment by jordanlewis** [comment]
This approach seems fine to me. Agree with @andreimatei that it is an incremental improvement on AOST. A more complete restructuring seems out of scope for this change.

---

Reviewed 7 of 7 files at r1.
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/render.go, line 304 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20162#-KzPzMbByHwvwcvqPjxG:-KzPzMbByHwvwcvqPjxH:byp3qaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/00e508fb381f89639da7285e22e4aa85673f4690/pkg/sql/render.go#L304)):*
> ```Go
> 	// definition), or they should have been handled by the executor.
> 	if parsed.From.AsOf.Expr != nil && !r.planner.avoidCachedDescriptors {
> 		return fmt.Errorf("AS OF SYSTEM TIME not supported")
> ```

Since I was pinged on this review - Do we know the statement context here? I would prefer this message be extended with specifics if possible - for example, something like "AS OF SYSTEM TIME not supported in CREATE TABLE AS". If we don't know the context, or it's hard to find out, I'd prefer it if you appended "in this context" to the error message. Otherwise I believe it will be misleading to users.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20162#-:-KzQ1Jhc4-yN7qDzDUjr:bbw7rso)*

**Comment by knz** [comment]
All right, I'm all for small step improvements. Carry on.

LGTM

**Comment by andreimatei** [comment]
@knz, if you do have an idea about how that visitor should look like, I would like to hear about it because, independently of this change, the way in which the executor has special code for recognizing AOST does bother me. If possible, I think it'd be much nicer to push checking of valid uses to planning and actual handling of to the `ScanNode` or such. That's because the current code doesn't go well with a world in which session handling code is supposed to be different from query execution code. And also because the current implementation is a bit broken: see #20182

---

Review status: 1 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/render.go, line 304 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20162#-KzPzMbByHwvwcvqPjxG:-KzQ9s6afSyKIT4fZdDT:b34pypl) ([raw file](https://github.com/cockroachdb/cockroach/blob/00e508fb381f89639da7285e22e4aa85673f4690/pkg/sql/render.go#L304)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Since I was pinged on this review - Do we know the statement context here? I would prefer this message be extended with specifics if possible - for example, something like "AS OF SYSTEM TIME not supported in CREATE TABLE AS". If we don't know the context, or it's hard to find out, I'd prefer it if you appended "in this context" to the error message. Otherwise I believe it will be misleading to users.
</blockquote></details>

I've added "not supported in this context", good suggestion. The reason why I changed this error in the first place was that before it looked too much like a parse error.
I don't know what kind of "context" is or could be available - like, are you thinking of a part of the statement, or what exactly? I don't quite see what we could add here other than perhaps the whole statement (which would be useful), but if you do, I'm listening.

---

*[pkg/sql/logictest/testdata/logic_test/show_trace, line 722 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20162#-KzPsxnNJYMfJ4dGDCnc:-KzQASf_GnNbjDSh1jjw:bgghkmu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7013cab0f05286952df29f4e87dcbaf5b522a29/pkg/sql/logictest/testdata/logic_test/show_trace#L722)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

How about adding something in as_of_test.go? It already does all of the work of getting a timestamp at which something is present.
</blockquote></details>

I didn't do that originally because deciding on what to test here exactly is not easy. But I added something now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20162#-:-KzQQSq5TR83AczW3Thb:b-xyfhjc)*

**Review by madelynnblue — APPROVED** [review]

**Pull request merged**
