### PR TITLE
crosscluster/physical: update tokens when altering topology

### PR DESCRIPTION
**Pull request by dt**
Release note: none.
Epic: none.

This regressed in #135637 which was assigning all conusmer sub-partitions the whole partition due to sharing the original token.

### CODE REVIEW

**Review by msbutler — APPROVED** [review]
Are you planning to follow up with a change to remove tokens?

**Comment by dt** [comment]
>  planning to follow up with a change to remove tokens?

It isn't currently on my prioritized backlog.

**Comment by dt** [comment]
But it kills me a little that that the DistSQL plan diagram isn't the source of truth as to what the plan will actually do.

**Comment by dt** [comment]
TFTR!

bors r+

**Pull request merged**
