### PR TITLE
sql: fix data race in MemberOfWithAdminOption

### LINKED ISSUE #95642: ccl/sqlproxyccl: TestBackendDialTLS failed due to race condition in catalog nstree
ccl/sqlproxyccl.TestBackendDialTLS [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/8396114?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/8396114?buildTab=artifacts#/) on master @ [2861a4ee05fac1cc13f87bf00f368a65ea8700dc](https://github.com/cockroachdb/cockroach/commits/2861a4ee05fac1cc13f87bf00f368a65ea8700dc):

```
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1964 +0x1cba
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1882 +0x424
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).runWithEx.func1()
      github.com/cockroachdb/cockroach/pkg/sql/internal.go:173 +0x117

Goroutine 5649 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:644 +0x3c4
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:368 +0xd15
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveConn()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:177 +0x48c
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:774 +0xc0a
  github.com/cockroachdb/cockroach/pkg/server.(*SQLServerWrapper).AcceptClients.func1()
      github.com/cockroachdb/cockroach/pkg/server/tenant.go:716 +0x267
  github.com/cockroachdb/cockroach/pkg/server.startServeSQL.func1.1()
      github.com/cockroachdb/cockroach/pkg/server/server_sql.go:1588 +0x2eb
  github.com/cockroachdb/cockroach/pkg/util/netutil.(*TCPServer).ServeWith.func1()
      github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:188 +0x111
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470 +0x1f6

Goroutine 5686 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).runWithEx()
      github.com/cockroachdb/cockroach/pkg/sql/internal.go:172 +0x344
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).execInternal()
      github.com/cockroachdb/cockroach/pkg/sql/internal.go:903 +0xf76
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).QueryIteratorEx()
      github.com/cockroachdb/cockroach/pkg/sql/internal.go:722 +0x2ac
  github.com/cockroachdb/cockroach/pkg/sql.(*internalTxn).QueryIteratorEx()
      <autogenerated>:1 +0x132
  github.com/cockroachdb/cockroach/pkg/sql.forEachRoleMembership()
      github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2760 +0x155
  github.com/cockroachdb/cockroach/pkg/sql.resolveMemberOfWithAdminOption()
      github.com/cockroachdb/cockroach/pkg/sql/authorization.go:613 +0x1e4
  github.com/cockroachdb/cockroach/pkg/sql.MemberOfWithAdminOption.func2()
      github.com/cockroachdb/cockroach/pkg/sql/authorization.go:552 +0x111
  github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).doCall.func1()
      github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:387 +0x51
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTask()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:305 +0x147
  github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).doCall()
      github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:386 +0x2a4
  github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).DoChan.func1()
      github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:356 +0xd0
==================
=== RUN   TestBackendDialTLS/tenant11
=== RUN   TestBackendDialTLS/tenant11To10
```
<p>Parameters: <code>TAGS=bazel,gss,race</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-sessions @cockroachdb/server
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestBackendDialTLS.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-23645

### LINKED ISSUE #96539: ccl/sqlproxyccl: TestBackendDialTLS failed
ccl/sqlproxyccl.TestBackendDialTLS [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/8580435?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/8580435?buildTab=artifacts#/) on master @ [5fbcd8a8deac0205c7df38e340c1eb9692854383](https://github.com/cockroachdb/cockroach/commits/5fbcd8a8deac0205c7df38e340c1eb9692854383):

```
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func2()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2048 +0xad7
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2050 +0xc12
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1892 +0x424
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).runWithEx.func1()
      github.com/cockroachdb/cockroach/pkg/sql/internal.go:171 +0x117

Goroutine 4821 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:644 +0x3c4
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:368 +0xd15
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveConn()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:177 +0x48c
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:777 +0xc0a
  github.com/cockroachdb/cockroach/pkg/server.(*SQLServerWrapper).AcceptClients.func1()
      github.com/cockroachdb/cockroach/pkg/server/tenant.go:729 +0x267
  github.com/cockroachdb/cockroach/pkg/server.startServeSQL.func1.1()
      github.com/cockroachdb/cockroach/pkg/server/server_sql.go:1631 +0x2eb
  github.com/cockroachdb/cockroach/pkg/util/netutil.(*TCPServer).ServeWith.func1()
      github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:188 +0x111
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470 +0x1f6

Goroutine 4847 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).runWithEx()
      github.com/cockroachdb/cockroach/pkg/sql/internal.go:170 +0x344
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).execInternal()
      github.com/cockroachdb/cockroach/pkg/sql/internal.go:900 +0xf76
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).QueryIteratorEx()
      github.com/cockroachdb/cockroach/pkg/sql/internal.go:719 +0x2ac
  github.com/cockroachdb/cockroach/pkg/sql.(*internalTxn).QueryIteratorEx()
      <autogenerated>:1 +0x132
  github.com/cockroachdb/cockroach/pkg/sql.resolveMemberOfWithAdminOption()
      github.com/cockroachdb/cockroach/pkg/sql/authorization.go:652 +0x55b
  github.com/cockroachdb/cockroach/pkg/sql.MemberOfWithAdminOption.func2()
      github.com/cockroachdb/cockroach/pkg/sql/authorization.go:552 +0x111
  github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).doCall.func1()
      github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:387 +0x51
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTask()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:305 +0x147
  github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).doCall()
      github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:386 +0x2a4
  github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).DoChan.func1()
      github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:356 +0xd0
==================
=== RUN   TestBackendDialTLS/tenant11
```
<p>Parameters: <code>TAGS=bazel,gss,race</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-sessions @cockroachdb/server
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestBackendDialTLS.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-24174

### PR DESCRIPTION
**Pull request by andyyang890**
This patch fixes a race condition in MemberOfWithAdminOption
by using a fresh transaction within the singleflight call.

Fixes #95642
Fixes #96539

Release note: None

### CODE REVIEW

**Comment by andyyang890** [comment]
This PR is an implementation of the idea discussed in #98469, but it seems to be hitting an issue where the `system.role_members` table appears to be empty. Is the modification time perhaps not set for the permanent upgrade that creates the initial row for `(admin, root)`?

**Comment by rafiss** [comment]
> table appears to be empty. Is the modification time perhaps not set for the permanent upgrade that creates the initial row for (admin, root)?

that seems likely. if the modification time is not set, then we should be able to safely not change the txn timestamp -- since this means that the `system.role_members` table is in it's default state.

**Comment by andyyang890** [comment]
> or just keep the transaction timestamp?

Would you mind elaborating a bit more about what the advantages of the original suggestion to set a fixed timestamp were? Are those benefits not strictly required for correctness?

**Comment by rafiss** [comment]
If the version is 1, that means there have been no modifications to the table. So using a historical timestamp or the current timestamp would both return the same results.

**Comment by andyyang890** [comment]
> If the version is 1, that means there have been no modifications to the table. So using a historical timestamp or the current timestamp would both return the same results.

I think the problem right now is that the permanent upgrade below inserts rows into the `system.role_members` table without bumping the table descriptor version. I'm guessing it would be unsafe to add code to the permanent upgrade that does the version bumping since it won't have been run on older clusters.
https://github.com/cockroachdb/cockroach/blob/08f2dc4e4e523d97c228bb0665f3859d920084f4/pkg/upgrade/upgrades/permanent_upgrades.go#L59-L87

**Comment by rafiss** [comment]
Right, I'm saying that if the version is 1 then we know:
- the permanent upgrade has run (since the cluster isn't available until permanent upgrades are done)
- no modifications have been made to the table since the permanent upgrade ran

So we can work around this issue of the upgrade not bumping the version by just using the current timestamp for the txn timestamp.

Or to resurrect this thread https://github.com/cockroachdb/cockroach/pull/98469#issuecomment-1466936674
> You don't want ReadTimestamp() I don't think. I think you want to take that descriptor you read for the role_memberships table and take its ModificationTime().

Maybe this is a case where we can use the outer txn's ReadTimestamp?

**Comment by andyyang890** [comment]
Ah I see, thanks for the clarification. I've updated the PR to do that!

**Review by rafiss — COMMENTED** [review]
great! this lgtm, but just wanted to discuss my comment from one of the other PRs:

if possible, could we add a more targeted test that catches this bug? it feels kind of lucky to me that TestBackendDialTLS is the one that caught this. i could imagine that test being refactored in the future, and no longer catching a future regression on this.

We could add a test to pkg/sql/user_test.go that surfaces the bug? It's possible that `TestGetUserTimeout` already would have revealed the bug, but I see that test is skipped under race

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98617#-:-NQb6bf-6lSADqnt3yj2:b-l6cuee)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Review by andyyang890 — COMMENTED** [review]
Looks like `TestGetUserTimeout` does catch the bug so I've unskipped it under race! I also removed the `backport-22.2.x` tag since this issue only started happening after the internal executor refactor, which was merged in 23.1.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98617#-:-NQfpWZm8ni0R6A4l6th:b-3m1070)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @rafiss)

**Review by rafiss — APPROVED** [review]

**Comment by andyyang890** [comment]
TFTR!

bors r=rafiss

**Comment by andyyang890** [comment]
bors retry

**Pull request merged**
