### PR TITLE
sql/sem/normalize: remove ConstantEvalVisitor

### PR DESCRIPTION
**Pull request by mgartner**
#### sql/rowexec: handle re-parsed lookup expressions in join reader

Previously, the join reader relied on the `normalize.ConstantEvalVisitor`
used in `execinfrapb.DeserializeExpr` to convert tuples in serialized
lookup expressions from `*tree.Tuple`s to `*tree.DTuple`s. This commit
break this reliance.

Release note: None

#### sql/sem/normalize: remove ConstantEvalVisitor

The `ConstantEvalVisitor` was introduced in #30216 as a work around for
a poorly performing type of query. It turned an `ARRAY` AST node with
all constant children into a `DArray`. The optimizer now performs this
optimization in the execbuilder phase. To be sure this is no longer
needed, I ran several queries similar to the original motivating
examples and saw no measurable performance difference.

Epic: None

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
A classic 5 year ["temporary fix"](https://github.com/cockroachdb/cockroach/pull/30216#issuecomment-422041328) cc @RaduBerinde.

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119557#-:-NrIJwoJBFA2TL7XjPAu:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by mgartner** [comment]
@DrewKimball I added a new commit to address one assumption in the join reader that broke because of this. PTAL.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 7 of 7 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119557)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[`pkg/sql/rowexec/joinreader_span_generator.go` line 573 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119557#-NrNCSoT7X4y6kY-GhTP:-NrNCSoT7X4y6kY-GhTQ:b-io3nk9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2329ee68a97e1c039460676851241493bd89bbc3/pkg/sql/rowexec/joinreader_span_generator.go#L573)):*
> ```Go
> 						"expected tuple to contain only tree.Datums, found %T", t.Exprs[i],
> 					)
> 				}
> ```

Looks like we have some special logic in case `inequality` is set that I'd expect we need to copy here too.

**Comment by mgartner** [comment]
Hmm I wonder if this could cause a regression in the row-based engine in the case that a filter like `i IN (1 , 3, …)` is pushed to another node.

**Comment by mgartner** [comment]
I re-tested this and it did cause a significant regression when evaluating a distributed filter like in `SELECT * FROM t WHERE a IN (1, 2, 3, 4, ..., 9999);`. Closing.

**Pull request closed without merging**
