### PR TITLE
importccl: support computed columns in IMPORT

### PR DESCRIPTION
**Pull request by madelynnblue**
Computed columns raise a question about what the expected CSV column
format is. To make this obvious, we require that the computed columns
appear at the end of the table schema. Thus, it should be obvious to
users that the only expected CSV columns will be the specified ones,
and that they should appear at the front. Otherwise, it could be
unclear to users if or how they should specify a computed column in
the middle of two others.

Release note (sql change): support computed columns in IMPORT

### CODE REVIEW

**Comment by mjibson** [comment]
Review second commit only please. First is from another PR.

**Comment by justinj** [comment]
LGTM! Definitely less code involved than I would have thought, thanks for doing this!

**Comment by knz** [comment]
do you want to proceed with this PR?

**Comment by mjibson** [comment]
Nope. Keeping the branch around but we decided to not merge this yet.

**Pull request closed without merging**
