### PR TITLE
roachtest: Bump up node/SSD size for clearrange roachtests

### PR DESCRIPTION
**Pull request by itsbilal**
For the clearrange/* roachtests, the instances we spun up on aws
(c5d.xlarge) had 4x less local ssd storage space as the ones we spun
up on gce. This extra headroom made a pretty significant difference,
as the bigbank workload import would easily exceed the ~900gb usable capacity
on a 10x c5d.xlarge node cluster (it was observed to take around 1.9TB on
GCE).

This change bumps up the instance size indirectly, by requiring more CPUs
which is how the instance type is determined.

A related, though less pressing change, is to allow for increased concurrency
in AddSSTable requests to make the import go faster.

Release justification: Roachtest change, doesn't affect cockroach binary
Release note: None.

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53572#-:-MFlgSEi55tFhFuCkA_u:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal, @jbowens, and @petermattis)

___
*[pkg/cmd/roachtest/clearrange.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53572#-MFlgUNh5_aXPrLKI0SG:-MFlgUNi77QLq_66H01Y:b92dyfm) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f7c54e2174eb25922669be68bb480896f0daf8/pkg/cmd/roachtest/clearrange.go#L72)):*
> ```Go
> 
> 	conn := c.Conn(ctx, 1)
> 	if _, err := conn.ExecContext(ctx, `SET CLUSTER SETTING kv.bulk_io_write.concurrent_addsstable_requests = 10`); err != nil {
> ```

Does the cluster setting exist on 19.1.x or do we have to gate setting it on a particular CRDB version?

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53572)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens and @petermattis)

___
*[pkg/cmd/roachtest/clearrange.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53572#-MFlgUNh5_aXPrLKI0SG:-MFlybKG1o8wUhE-91cp:bjy2dol) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f7c54e2174eb25922669be68bb480896f0daf8/pkg/cmd/roachtest/clearrange.go#L72)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Does the cluster setting exist on 19.1.x or do we have to gate setting it on a particular CRDB version?
</blockquote></details>

Might be a good idea to use `c.spec.NodeCount` instead of 10, so that it's consistent with the clusterSpec.

**Review by itsbilal — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53572#-:-MG3xEqo1g8ore4Tayoc:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal and @petermattis)

___
*[pkg/cmd/roachtest/clearrange.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53572#-MFlgUNh5_aXPrLKI0SG:-MG3xFgd6r8OiNwNE_rj:b-1hxibu) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f7c54e2174eb25922669be68bb480896f0daf8/pkg/cmd/roachtest/clearrange.go#L72)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Might be a good idea to use `c.spec.NodeCount` instead of 10, so that it's consistent with the clusterSpec.
</blockquote></details>

Done. Yep, I had to get this on >=19.2. Good catch.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53572#-:-MG4-eWd4P3FzDwVryhZ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal)

**Comment by itsbilal** [comment]
TFTRs!

bors r+

**Pull request merged**
