### PR TITLE
sqlsmith: don't compare voids for joins

### LINKED ISSUE #73777: roachtest: sqlsmith/setup=empty/setting=no-ddl failed: error lookup for ComparisonExpr
roachtest.sqlsmith/setup=empty/setting=no-ddl [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3904068&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3904068&tab=artifacts#/sqlsmith/setup=empty/setting=no-ddl) on master @ [5cd5be83218475ef0cc3c62a856b8d9d22cf142b](https://github.com/cockroachdb/cockroach/commits/5cd5be83218475ef0cc3c62a856b8d9d22cf142b):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/sqlsmith/setup=empty/setting=no-ddl/run_1
	sqlsmith.go:230,sqlsmith.go:257,test_runner.go:779: Failed generating a query Caught error lookup for ComparisonExpr ((((tab_60.col_119)[??? tab_60.col_119]))[void] = (((tab_61.col_121)[??? tab_61.col_121]))[void])[bool]'s CmpOp failed
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=empty/setting=no-ddl.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #73898: roachtest: sqlsmith/setup=empty/setting=no-mutations failed
roachtest.sqlsmith/setup=empty/setting=no-mutations [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3924285&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3924285&tab=artifacts#/sqlsmith/setup=empty/setting=no-mutations) on master @ [dd7fd4e5a371ce4437fce383b9674cba2e212fe6](https://github.com/cockroachdb/cockroach/commits/dd7fd4e5a371ce4437fce383b9674cba2e212fe6):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/sqlsmith/setup=empty/setting=no-mutations/run_1
	sqlsmith.go:230,sqlsmith.go:257,test_runner.go:779: Failed generating a query Caught error lookup for ComparisonExpr ((((tab_4503.col_8060)[??? tab_4503.col_8060]))[void] = (((tab_4504.col_8061)[??? tab_4504.col_8061]))[void])[bool]'s CmpOp failed
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=empty/setting=no-mutations.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #73901: internal/sqlsmith: TestGenerateParse failed
internal/sqlsmith.TestGenerateParse [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3925795&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3925795&tab=artifacts#/) on master @ [dd7fd4e5a371ce4437fce383b9674cba2e212fe6](https://github.com/cockroachdb/cockroach/commits/dd7fd4e5a371ce4437fce383b9674cba2e212fe6):

```
	)
		AS tab_325
ORDER BY
	col_400 NULLS FIRST, col_401 NULLS FIRST;

    panic.go:1047: lookup for ComparisonExpr ((((tab_335.col_416)[??? tab_335.col_416]))[void] = (((tab_336.col_417)[??? tab_336.col_417]))[void])[bool]'s CmpOp failed
        goroutine 9919 [running]:
        runtime/debug.Stack()
        	GOROOT/src/runtime/debug/stack.go:24 +0x72
        github.com/cockroachdb/cockroach/pkg/util/leaktest.AfterTest.func1()
        	github.com/cockroachdb/cockroach/pkg/util/leaktest/leaktest.go:110 +0x94
        panic({0x69ca160, 0xc002a44780})
        	GOROOT/src/runtime/panic.go:1047 +0x266
        github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Stop(0xc00167a2d0, {0xaf34300, 0xc0001c0028})
        	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:551 +0x49a
        panic({0x69ca160, 0xc002a44780})
        	GOROOT/src/runtime/panic.go:1047 +0x266
        github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*ComparisonExpr).memoizeFn(0xc000a734f0)
        	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/expr.go:613 +0x35f
        github.com/cockroachdb/cockroach/pkg/sql/sem/tree.NewTypedComparisonExpr({0x6632ce0, 0x1}, {0xaf6d3a8, 0xc0024e73c8}, {0xaf6d3a8, 0xc0024e73f8})
        	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/expr.go:527 +0x1fb
        github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.makeEquiJoinExpr(0xc002a9a000, {0x0, 0x0, 0x0}, 0x98)
        	github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/relational.go:238 +0x376
        github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.makeTableExpr(0xc002a9a000, {0x0, 0x0, 0x0}, 0x80)
        	github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/relational.go:144 +0x15f
        github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.makeEquiJoinExpr(0xc002a9a000, {0x0, 0x0, 0x0}, 0xa0)
        	github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/relational.go:208 +0xd5
        github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.makeTableExpr(0xc002a9a000, {0x0, 0x0, 0x0}, 0x75)
        	github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/relational.go:144 +0x15f
        github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.makeJoinExpr(0xc002a9a000, {0x0, 0x0, 0x0}, 0x5)
        	github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/relational.go:179 +0x7d
        github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.makeTableExpr(0xc002a9a000, {0x0, 0x0, 0x0}, 0xb8)
        	github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/relational.go:144 +0x15f
        github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.(*Smither).makeSelectClause(0xc002a9a000, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0})
        	github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/relational.go:521 +0x316
        github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.(*Smither).makeSelect(0x7fd177554280, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0})
        	github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/relational.go:726 +0xce
        github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.makeSelect(0xc002a9a000)
        	github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/relational.go:679 +0x5a
        github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.(*Smither).makeStmt(0xc002a9a000)
        	github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/relational.go:20 +0x56
        github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.(*Smither).Generate(0xaead320)
        	github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/sqlsmith.go:158 +0x3d
        github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.TestGenerateParse(0xc000b55ba0)
        	github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/sqlsmith_test.go:184 +0x9db
        testing.tRunner(0xc000b55ba0, 0x74d1958)
        	GOROOT/src/testing/testing.go:1259 +0x230
        created by testing.(*T).Run
        	GOROOT/src/testing/testing.go:1306 +0x727
--- FAIL: TestGenerateParse (2.21s)
```
<details><summary>Help</summary>
<p>
See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)Parameters in this failure:

- TAGS=bazel,gss
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestGenerateParse.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by otan**
No comparison expr is defined on voids, so don't generate comparisons
for them.

Resolves #73901
Resolves #73898
Resolves #73777

Release note: None

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
thanks!

**Comment by otan** [comment]
bors r=rafiss

**Comment by otan** [comment]
bors r=rafiss

**Comment by otan** [comment]
bors r=rafiss

**Pull request merged**
