### PR TITLE
obsservice: insert into Statement Insights

### PR DESCRIPTION
**Pull request by maryliag**
Inserting Statement Insights to the insight table
on obsservice.
Add to the event the general info, such as cluster_id and tenant_id.

This commit will insert each event as soon as they're exported,
a following PR will create batches for the inserts.

Fixes CC-25987
Part Of CC-26215

https://www.loom.com/share/678c0702e66a4eeb95e798875e7156a7

Release note: None

### CODE REVIEW

**Review by abarganier — COMMENTED** [review]
This is awesome! Just a few small nits & a couple questions (mostly out of curiosity). 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115060#-:-NkGTqyA7wLaDhCPk_xU:byfcudm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/obsservice/obslib/migrations/sqlmigrations/0002_stmt_insights.sql` line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115060#-NkGRBYR97MFdBoRa8FV:-NkGR7t2ACux0A76-3s0:b-39scyf) ([raw file](https://github.com/cockroachdb/cockroach/blob/46ccd83d8632da48fe4190176f05674786964d6a/pkg/obsservice/obslib/migrations/sqlmigrations/0002_stmt_insights.sql#L3)):*
> ```TSQL
> -- +goose Up
> CREATE TABLE statement_execution_insights (
>    timestamp                  TIMESTAMPTZ,
> ```

Is the idea behind using `TIMESTAMPTZ` that for the prototype, the client will be sql-over-http, which should have the same TZ as the cluster region? What if the cluster is multi-region? Just trying to understand the `TIMESTAMPTZ` vs. `TIMESTAMP` reasoning. 
___
*[`pkg/obsservice/obslib/migrations/sqlmigrations/0002_stmt_insights.sql` line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115060#-NkGQnYw2IOQhjIutKhA:-NkGQnYw2IOQhjIutKhB:b-o8xain) ([raw file](https://github.com/cockroachdb/cockroach/blob/60719a073152f2f63ef71ebeec39f498b3087526/pkg/obsservice/obslib/migrations/sqlmigrations/0002_stmt_insights.sql#L44)):*
> ```TSQL
>      session_id,
>      transaction_id,
>      transaction_fingerprint_id,
> ```

Just curious, what's the motivation for getting rid of the column family here? 
___
*[`pkg/obsservice/obslib/process/stmt_insights_processor.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115060#-NkGRNPr-9zjchyTFM9D:-NkGRNPs1QS-Us0SXBmZ:b-kuh5z9) ([raw file](https://github.com/cockroachdb/cockroach/blob/46ccd83d8632da48fe4190176f05674786964d6a/pkg/obsservice/obslib/process/stmt_insights_processor.go#L27)):*
> ```Go
> ) error {
> 	db, err := OpenDBSync(ctx, t.SinkPGURL)
> 	if err != nil {
> ```

nit: let's add a TODO here to pool/recycle these connections in a future patch
___
*[`pkg/obsservice/obslib/process/stmt_insights_processor.go` line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115060#-NkGSVZrAeNZ62NcPi_F:-NkGSVZrAeNZ62NcPi_G:b54ruv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/46ccd83d8632da48fe4190176f05674786964d6a/pkg/obsservice/obslib/process/stmt_insights_processor.go#L33)):*
> ```Go
> 
> 	insertStmt := `INSERT INTO obsservice.statement_execution_insights VALUES 
>     ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, 
> ```

nit: it might make things easier to read if we define the column names in this statement, just so we know what each is meant to represent (and protect against schema changes changing what each column index represents). 
___
*[`pkg/obsservice/obslib/process/stmt_insights_processor.go` line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115060#-NkGReQv2fai_8T1rsV-:-NkGReQv2fai_8T1rsV0:bku05mu) ([raw file](https://github.com/cockroachdb/cockroach/blob/46ccd83d8632da48fe4190176f05674786964d6a/pkg/obsservice/obslib/process/stmt_insights_processor.go#L69)):*
> ```Go
> 		stmtInsight.ErrorCode,
> 		stmtInsight.Contention,
> 		tree.DNull, // details
> ```

nit: can we add to the comment a bit of context about why this null for now, and what it will be in the future? 
___
*[`pkg/obsservice/obslib/transform/transformer_utils.go` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115060#-NkGTAvaDgb03fpcS5ch:-NkGTAvaDgb03fpcS5ci:b830dqm) ([raw file](https://github.com/cockroachdb/cockroach/blob/46ccd83d8632da48fe4190176f05674786964d6a/pkg/obsservice/obslib/transform/transformer_utils.go#L1)):*
> ```Go
> // Copyright 2023 The Cockroach Authors.
> ```

nit: can we name this file something other than `transformer_utils`? I find that files with `util` in the name over time end up having random stuff added to them, which can get messy. Maybe something like `event_info`?

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115060)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier)

___
*[`pkg/obsservice/obslib/migrations/sqlmigrations/0002_stmt_insights.sql` line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115060#-NkGRBYR97MFdBoRa8FV:-NkGvrqG8Ph-GDTeHvGi:b-fb099o) ([raw file](https://github.com/cockroachdb/cockroach/blob/46ccd83d8632da48fe4190176f05674786964d6a/pkg/obsservice/obslib/migrations/sqlmigrations/0002_stmt_insights.sql#L3)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Is the idea behind using `TIMESTAMPTZ` that for the prototype, the client will be sql-over-http, which should have the same TZ as the cluster region? What if the cluster is multi-region? Just trying to understand the `TIMESTAMPTZ` vs. `TIMESTAMP` reasoning.
</blockquote></details>

we do have the feature of showing UI on specified timezone, so this is to keep things compatible to how it works today. The TZ is set by a cluster setting, so it will be the same for the entire cluster.
___
*[`pkg/obsservice/obslib/migrations/sqlmigrations/0002_stmt_insights.sql` line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115060#-NkGQnYw2IOQhjIutKhA:-NkGwRDT5J3b6PlW3Iz2:b-8jangn) ([raw file](https://github.com/cockroachdb/cockroach/blob/60719a073152f2f63ef71ebeec39f498b3087526/pkg/obsservice/obslib/migrations/sqlmigrations/0002_stmt_insights.sql#L44)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Just curious, what's the motivation for getting rid of the column family here?
</blockquote></details>

ah, I was testing some stuff and forgot to add it back. Reverted this change
___
*[`pkg/obsservice/obslib/process/stmt_insights_processor.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115060#-NkGRNPr-9zjchyTFM9D:-NkH0ZEyC9QqIxz55Nog:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/46ccd83d8632da48fe4190176f05674786964d6a/pkg/obsservice/obslib/process/stmt_insights_processor.go#L27)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: let's add a TODO here to pool/recycle these connections in a future patch
</blockquote></details>

done
___
*[`pkg/obsservice/obslib/process/stmt_insights_processor.go` line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115060#-NkGSVZrAeNZ62NcPi_F:-NkGydmh5m-VGXu80xzl:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/46ccd83d8632da48fe4190176f05674786964d6a/pkg/obsservice/obslib/process/stmt_insights_processor.go#L33)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: it might make things easier to read if we define the column names in this statement, just so we know what each is meant to represent (and protect against schema changes changing what each column index represents).
</blockquote></details>

done
___
*[`pkg/obsservice/obslib/process/stmt_insights_processor.go` line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115060#-NkGReQv2fai_8T1rsV-:-NkGyxKS4fIweqy_HET8:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/46ccd83d8632da48fe4190176f05674786964d6a/pkg/obsservice/obslib/process/stmt_insights_processor.go#L69)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: can we add to the comment a bit of context about why this null for now, and what it will be in the future?
</blockquote></details>

Done
___
*[`pkg/obsservice/obslib/transform/transformer_utils.go` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115060#-NkGTAvaDgb03fpcS5ch:-NkGzF_c9STUzUvST0rz:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/46ccd83d8632da48fe4190176f05674786964d6a/pkg/obsservice/obslib/transform/transformer_utils.go#L1)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: can we name this file something other than `transformer_utils`? I find that files with `util` in the name over time end up having random stuff added to them, which can get messy. Maybe something like `event_info`?
</blockquote></details>

Done

**Review by abarganier — APPROVED** [review]
:lgtm: - nice work! :rocket: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115060#-:-NkH8zyO4BUV7S3Bpq86:bbaij7n)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/obsservice/obslib/migrations/sqlmigrations/0002_stmt_insights.sql` line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115060#-NkGRBYR97MFdBoRa8FV:-NkH8d9G5rG2TOW-Rmai:bugjiz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/46ccd83d8632da48fe4190176f05674786964d6a/pkg/obsservice/obslib/migrations/sqlmigrations/0002_stmt_insights.sql#L3)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

we do have the feature of showing UI on specified timezone, so this is to keep things compatible to how it works today. The TZ is set by a cluster setting, so it will be the same for the entire cluster.
</blockquote></details>

Ah, I didn't know `TIMESTAMPTZ` took that into account - cool! Thanks for explaining.

**Comment by maryliag** [comment]
TFTRs!

bors r+

**Pull request merged**
