### PR TITLE
storage: clean up usage of `{eng,batch} engine.{Reader,Writer,ReadWriter}`

### PR DESCRIPTION
**Pull request by irfansharif**
We should be using `{reader,writer,readWriter} engine.{Reader,Writer,ReadWriter}` instead. See individual commits for review.

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm_strong: 

> Reviewed 3 of 3 files at r1, 6 of 6 files at r2, 4 of 4 files at r3, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43265#-:-LwL2ZnN6gi5nGluQrfR:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @irfansharif)

___
*[pkg/storage/replica_raft.go, line 1621 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43265#-LwL2P0TEjVUM-Cq4lUq:-LwL2P0TEjVUM-Cq4lUr:bdjybgz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3fa87ad98feed258f9618f8989a8cc6ce12733a/pkg/storage/replica_raft.go#L1621)):*
> ```Go
> 	oldTruncatedState, newTruncatedState *roachpb.RaftTruncatedState,
> 	loader stateloader.StateLoader,
> 	batch engine.Batch,
> ```

Why did you make this a batch?

**Review by irfansharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43265)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/storage/replica_raft.go, line 1621 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43265#-LwL2P0TEjVUM-Cq4lUq:-LwLUVsN6b_PnoiS7tLu:b-c1mvmw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3fa87ad98feed258f9618f8989a8cc6ce12733a/pkg/storage/replica_raft.go#L1621)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why did you make this a batch?
</blockquote></details>

Woops, snuck in from another (incoming) diff. That being said, I think philosophically we should be using engine.Batch when we are, infact, using {rocksdb,pebble} batches. It may be obvious to us now, but all of batcheval/proposer kv never deal with raw engines and the function signatures should reflect as such.

**Review by irfansharif — COMMENTED** [review]
TFTR, will merge on green (lint failures).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43265#-:-LwLV5mtEmteX7g06bCl:b-sdv8ng)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

**Pull request merged**
