### PR TITLE
roachpb: fix nil-pointer conversion error

### LINKED ISSUE #9347: stability: panic on version discrepancy
Upgrading gamma from d8213c2 to d262ae3 using a rolling restart.

Nodes crashed right away with:
```
panic: interface conversion: interface is nil, not roachpb.Request [recovered]
        panic: interface conversion: interface is nil, not roachpb.Request

goroutine 45 [running]:
panic(0x15a5780, 0xc421a466c0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/cli.initBacktrace.func2(0x15a5780, 0xc421a466c0)
        /go/src/github.com/cockroachdb/cockroach/cli/backtrace.go:98 +0xca
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Recover(0xc42040d560)
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:173 +0x56
panic(0x15a5780, 0xc421a466c0)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/roachpb.RequestUnion.GetInner(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/roachpb/api.go:325 +0x6f
github.com/cockroachdb/cockroach/roachpb.(*BatchRequest).GetArg(0xc4217a33b8, 0x16, 0xc421dfe540, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/roachpb/batch.go:139 +0xdd
github.com/cockroachdb/cockroach/roachpb.(*BatchRequest).IsLease(0xc4217a33b8, 0xc4203b9380)
        /go/src/github.com/cockroachdb/cockroach/roachpb/batch.go:78 +0x3e
github.com/cockroachdb/cockroach/storage.(*Replica).processRaftCommand(0xc4203a26c0, 0xc421152970, 0x8, 0x20831, 0x15804, 0x100000001, 0x1, 0x1473ff8ab84d635e, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:2357 +0x92a
github.com/cockroachdb/cockroach/storage.(*Replica).handleRaftReady(0xc4203a26c0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:1894 +0x8b8
github.com/cockroachdb/cockroach/storage.(*Store).processReady(0xc4201c6280, 0x15804)
        /go/src/github.com/cockroachdb/cockroach/storage/store.go:2571 +0xfd
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc42031c620, 0xc42040d560)
        /go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:197 +0x308
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
        /go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc42040d560, 0xc42074aee0)
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66
```

This is most likely due to 5e1ce5a.

After the first node (`104.196.169.188`) started crash-looping, stopped all of them and restarted at the new version. However, other nodes started crashing. Reverted back to d8213c2

### PR DESCRIPTION
**Pull request by petermattis**
Fix a nil-pointer conversion error when a batch contains a nil
request. Such a request can occur when a new server unmarshal a request
containing a request type that is no longer present in RequestUnion.

Fixes #9347.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9349)

### CODE REVIEW

**Comment by petermattis** [comment]
Cc @cockroachdb/stability

**Comment by mberhault** [comment]
LGTM.
Is this liable to become a problem if we transparently ignore something that should really be important? I'm fine with the short-term fix, but this is the kind of thing that needs to be properly identified. "full shutdown" during beta is acceptable, but it won't be for long.

**Comment by tamird** [comment]
Yeah, I'm a little uneasy about this. I'd rather we worked out what's really going on in #9347 given that we expect it not to occur after a stop-the-world upgrade.

**Comment by tamird** [comment]
cc @eisenstatdavid

**Comment by tschottdorf** [comment]
I also think this is a dangerous fix. If you're worried about `gamma` getting back on its feet quickly I'm ok baking this, deploying that, then doing a (more) proper stop-the-world upgrade, but it makes me very uneasy to silently have replicas potentially diverge in this intransparent way.

**Comment by petermattis** [comment]
I suppose it depends on what you mean by a stop-the-world upgrade. If Marc just killed the nodes and restarted then it is very possible that one of the replicas in one of the ranges was behind and needed to be caught up. If the concern is that we're not processing the `VerifyChecksumRequest` on all of the nodes then I'm not as worried. That request only had an effect if the checksums differed which is not something we've seen in a while.

**Comment by tamird** [comment]
I'd prefer if we did this in a more targeted way - unmarshal the old request's tag into a NoopRequest.

**Comment by petermattis** [comment]
Unfortunately, you can't have 2 `NoopRequest` types in `RequestUnion`:

```
stringer: checking package: api.pb.go:5494:7: duplicate case *..NoopRequest in type switch
```

**Comment by tamird** [comment]
Bummer. If the freeze-cluster upgrade doesn't work, you can add a new type (empty, like NoopRequest) to work around that.

**Comment by bdarnell** [comment]
Yeah, checking for nil does too much, since it happens both for `reserved` tags from the past and not-yet-assigned tags from the future. We should probably just bring back VerifyChecksumRequest (with its contents deleted) and document that we can't delete things from these unions (commands other than VerifyChecksum are going to be difficult to remove anyway; the only reason we were able to remove VerifyChecksum is that its documented behavior degrades gracefully into a noop). 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9349#-:-KRaycXktCFhKtA6pWmm:b-ub962v)*

**Comment by petermattis** [comment]
Reworked this PR to add a `{Request,Response}Union.DeprecatedVerifyChecksum` field. PTAL.

**Comment by mberhault** [comment]
LGTM.

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9349#-:-KRcjFHLXmPDqBMSaEsM:bnfp4nl)*

**Comment by tschottdorf** [comment]
This will let the batch error out in `executeCmd`, so none of the other requests in the batch will apply. This is still unnecessarily prone to divergence. But let's basically never remove anything from below Raft until proposed-eval'ed KV is in in the future.

**Comment by petermattis** [comment]
Yep, I hope the warning message in `api.proto` will dissuade anyone from doing this in the future.

**Pull request merged**
