### PR TITLE
sql: add CONTROLJOB role option

### PR DESCRIPTION
**Pull request by RichardJCai**
sql: add CONTROLJOB role option

Pair programmed by @cockroachdb/sql-features 

Release note (sql change): Added CONTROLJOB role option.
When creating/altering roles, CONTROLJOB can be passed as a
role option. For example CREATE USER <user> CONTROLJOB CREATEROLE.

NOCONTROLJOB can be used to remove CONTROLJOB from the role when
altering the role.

CONTROLJOB allows the user to pause/resume and cancel jobs owned
by non-admin users.

CONTROLJOB also allows seeing all jobs owned by non-admin users, ie
when running SHOW JOBS.

### CODE REVIEW

**Review by solongordon — CHANGES_REQUESTED** [review]
> Reviewed 9 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52804)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[pkg/sql/authorization.go, line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52804#-MEhcmQ2-ypKGPMkIcCY:-MEhcmQ2-ypKGPMkIcCZ:b5wugzx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d85e7a12dc33d3e6a323103d4d693cda6c0798b3/pkg/sql/authorization.go#L207)):*
> ```Go
> }
> 
> func (p *planner) IsUserAdminRole(ctx context.Context, user string) (bool, error) {
> ```

Nit: Maybe `UserHasAdminRole` would be clearer. The current name makes it sound like the user is explicitly `admin`.
___
*[pkg/sql/authorization.go, line 436 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52804#-MEhdAi76OtgUPlMwghb:-MEhdAi76OtgUPlMwghc:b-i90g31) ([raw file](https://github.com/cockroachdb/cockroach/blob/d85e7a12dc33d3e6a323103d4d693cda6c0798b3/pkg/sql/authorization.go#L436)):*
> ```Go
> 	}
> 
> 	// User is not a member of a role that has CREATEROLE privilege.
> ```

Not from this PR but this comment is out of date
___
*[pkg/sql/control_jobs.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52804#-MEheXN60CJFgCHS6lKg:-MEheXN60CJFgCHS6lKh:bxryvtf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d85e7a12dc33d3e6a323103d4d693cda6c0798b3/pkg/sql/control_jobs.go#L60)):*
> ```Go
> 			return pgerror.Newf(pgcode.InsufficientPrivilege,
> 				"user %s does not have %s privilege",
> 				params.p.User(), roleoption.CONTROLJOB.String())
> ```

Nit: `.String()` is automatically called for `%s`
___
*[pkg/sql/control_jobs.go, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52804#-MEhenFG9WXo2qKGMbJe:-MEhenFG9WXo2qKGMbJf:b-fj2t1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/d85e7a12dc33d3e6a323103d4d693cda6c0798b3/pkg/sql/control_jobs.go#L84)):*
> ```Go
> 		}
> 
> 		job, err := reg.LoadJob(params.ctx, int64(jobID))
> ```

Needs an `err` check.
___
*[pkg/sql/control_jobs.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52804#-MEhex3wAFXKzM8ew8Jk:-MEhex3wAFXKzM8ew8Jl:b-mq8fc6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d85e7a12dc33d3e6a323103d4d693cda6c0798b3/pkg/sql/control_jobs.go#L95)):*
> ```Go
> 			// Owner is an admin but user executing the statement is not.
> 			if ok {
> 				return errors.New("only admins can control jobs owned by other admins")
> ```

Use `pgcode.InsufficientPrivilege`
___
*[pkg/sql/parser/sql.y, line 6231 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52804#-MEhfhiMEjAKqr-4w4K_:-MEhfhiMEjAKqr-4w4Ka:bkruvwt) ([raw file](https://github.com/cockroachdb/cockroach/blob/d85e7a12dc33d3e6a323103d4d693cda6c0798b3/pkg/sql/parser/sql.y#L6231)):*
> ```Yacc
> 	{
> 		$$.val = tree.KVOption{Key: tree.Name($1), Value: nil}
> 	}
> ```

Tab chars

**Review by solongordon — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52804)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[pkg/sql/roleoption/role_option.go, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52804#-MEiWPBP6qRtKp_DKnmt:-MEiWPBP6qRtKp_DKnmu:bzauzoy) ([raw file](https://github.com/cockroachdb/cockroach/blob/d85e7a12dc33d3e6a323103d4d693cda6c0798b3/pkg/sql/roleoption/role_option.go#L163)):*
> ```Go
> 		roleOptionBits&NOCREATEROLE.Mask() != 0) ||
> 		(roleOptionBits&LOGIN.Mask() != 0 &&
> 			roleOptionBits&NOLOGIN.Mask() != 0) {
> ```

This needs an update.

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52804)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/sql/authorization.go, line 436 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52804#-MEhdAi76OtgUPlMwghb:-MEyCOlDBzc1ntVxCTlR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d85e7a12dc33d3e6a323103d4d693cda6c0798b3/pkg/sql/authorization.go#L436)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Not from this PR but this comment is out of date
</blockquote></details>

Done.
___
*[pkg/sql/control_jobs.go, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52804#-MEhenFG9WXo2qKGMbJe:-MEy9140-w3QVhxgpsz4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d85e7a12dc33d3e6a323103d4d693cda6c0798b3/pkg/sql/control_jobs.go#L84)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Needs an `err` check.
</blockquote></details>

Done.
___
*[pkg/sql/control_jobs.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52804#-MEhex3wAFXKzM8ew8Jk:-MEy97JDDmzjc-sKAnSW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d85e7a12dc33d3e6a323103d4d693cda6c0798b3/pkg/sql/control_jobs.go#L95)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Use `pgcode.InsufficientPrivilege`
</blockquote></details>

Done.
___
*[pkg/sql/parser/sql.y, line 6231 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52804#-MEhfhiMEjAKqr-4w4K_:-MEy9HI79L6DNYshO3J0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d85e7a12dc33d3e6a323103d4d693cda6c0798b3/pkg/sql/parser/sql.y#L6231)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Tab chars
</blockquote></details>

Done.
___
*[pkg/sql/roleoption/role_option.go, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52804#-MEiWPBP6qRtKp_DKnmt:-MEy9UrNB2UAFHUcdX-e:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d85e7a12dc33d3e6a323103d4d693cda6c0798b3/pkg/sql/roleoption/role_option.go#L163)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

This needs an update.
</blockquote></details>

Done.

**Review by solongordon — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52804#-:-MF0jgd009kWVT5r1Jwz:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @solongordon)

**Comment by RichardJCai** [comment]
bors r=solongordon

**Pull request merged**
