### PR TITLE
release-22.1: memo: better selectivity estimates on single-table ORed predicates

### PR DESCRIPTION
**Pull request by mgartner**
Backport:
  * 1/1 commits from "memo: better selectivity estimates on single-table ORed predicates" (#89358)
  * 1/1 commits from "sql: add optimizer_use_improved_disjunction_stats session setting" (#94389)

Please see individual PRs for details.

Note that the setting `optimizer_use_improved_disjunction_stats` defaults to `false` in
this backport (differing from the original commit) so that users must opt into the new
behavior. 

Release justification: This backports improved statistics logic behind a session setting.

/cc @cockroachdb/release

### CODE REVIEW

**Comment by mgartner** [comment]
Do not review yet. I need to figure out why some of the join stats have changed.

**Comment by mgartner** [comment]
Ok, this is ready for review.

**Review by msirek — COMMENTED** [review]
> Reviewed 3 of 20 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94439)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/memo/statistics_builder.go` line 3175 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94439#-NKV6O3X7-hdMVE9QHKN:-NKV6O3X7-hdMVE9QHKO:b-2gqh6i) ([raw file](https://github.com/cockroachdb/cockroach/blob/dca99a39ccf4d79b7fd05c3f7fad10f73c56c916/pkg/sql/opt/memo/statistics_builder.go#L3175)):*
> ```Go
> 			// not an Or, bump the number of unapplied disjuncts.
> 			numUnappliedDisjuncts++
> 			return
> ```

It seems like we want the new flag to control the setting of `unconstrained` and incrementing of `numUnappliedDisjuncts` instead of just removing the old logic.
___
*[`pkg/sql/opt/memo/statistics_builder.go` line 3194 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94439#-NKV6a4s5Ltr5rFvzMui:-NKV6a4s5Ltr5rFvzMuj:b-lfg721) ([raw file](https://github.com/cockroachdb/cockroach/blob/dca99a39ccf4d79b7fd05c3f7fad10f73c56c916/pkg/sql/opt/memo/statistics_builder.go#L3194)):*
> ```Go
> 	collectConstraints(or.Right)
> 
> 	return constraints, numUnappliedDisjuncts
> ```

Same here. It seems like we want to follow the old behavior when the flag is false.  Otherwise we're changing the result, even when the flag is false.



_Code quote:_
```Go
not an Or, bump the number of unapplied disjuncts.
```

**Comment by mgartner** [comment]
*[`pkg/sql/opt/memo/statistics_builder.go` line 3175 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94439#-NKV6O3X7-hdMVE9QHKN:-NKV74710tmk04WP8gwR:b-opqkp3) ([raw file](https://github.com/cockroachdb/cockroach/blob/dca99a39ccf4d79b7fd05c3f7fad10f73c56c916/pkg/sql/opt/memo/statistics_builder.go#L3175)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

It seems like we want the new flag to control the setting of `unconstrained` and incrementing of `numUnappliedDisjuncts` instead of just removing the old logic.
</blockquote></details>

Notice the check I added to gate the old logic above: `if numUnappliedDisjuncts == 0 {`. This matches the old logic which needing to contort the function signature any more. I originally missed this, which is why I created #94442 so these fixes make it back into master and the v22.2 backport.

**Review by msirek — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 13 files at r1, 17 of 20 files at r4, 20 of 20 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94439#-:-NKVS6xsCe4ucCLpXpU6:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`-- commits` line 34 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/94439#-NKVCpQK0HH7LU1mIKgy):*
Should this say "defaults to `false`" ?
___
*[`pkg/sql/opt/memo/statistics_builder.go` line 3175 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94439#-NKV6O3X7-hdMVE9QHKN:-NKVRplu-7adiZj7_N32:bw5ca13) ([raw file](https://github.com/cockroachdb/cockroach/blob/dca99a39ccf4d79b7fd05c3f7fad10f73c56c916/pkg/sql/opt/memo/statistics_builder.go#L3175)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Notice the check I added to gate the old logic above: `if numUnappliedDisjuncts == 0 {`. This matches the old logic which needing to contort the function signature any more. I originally missed this, which is why I created #94442 so these fixes make it back into master and the v22.2 backport.
</blockquote></details>

OK, I see.

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 1 of 13 files at r1, 20 of 20 files at r4, 20 of 20 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94439#-:-NKW-_ZE0J3qla7z0nhI:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

**Comment by mgartner** [comment]
> Should this say "defaults to false" ?

Good catch. I've updated the commit and also made a note in the PR description to highlight that this differs from the original commit.

**Comment by mgartner** [comment]
TFTRs!

**Pull request merged**
