### PR TITLE
sql: remove constant folding visitor

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change removes the visitor for folding operations on constant literals,
called by `tree.TypeCheck`. This was part of our original typing solution which
folds constant operations first and only assigns a type to the result.
Unfortunately doing this folding in a visitor doesn't interact well with writing
out ASTs (e.g. for CREATE TABLE AS, see #50164), as the folded result does not
"hang off" the original AST.

The value of this feature is debatable; in particular, Postgres does not type
constant expressions like this. The changes to the tests in this commit
illustrate some cases; in most of these, the new results are consistent with
Postgres.

Release note (sql change): Typing of expressions involving only operations on
constant literals changed in some cases. Each constant literal is now assigned a
type (whereas before we were calculating the result first and only assigning a
type to the result).

### CODE REVIEW

**Review by rohany — APPROVED** [review]

**Comment by yuzefovich** [comment]
Just a pass-by comment:
nit: `s/DEGIMAL/DECIMAL/` in commit message.

**Comment by RaduBerinde** [comment]
Fixed the commit message. I had to make some more fixes in the `typing` tests. These tests were mostly to show off the typing implementation, and some of the ones that stopped working don't work in Postgres either.

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/logictest/testdata/logic_test/typing, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50254#-M9vXOUk55vlYhRZugOH:-M9vXOUl6FWmIMPjQ7DP:b3fygzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e2a4b828806e9bbfa0421966b87646e5e6c44d8/pkg/sql/logictest/testdata/logic_test/typing#L41)):*
> ```
> SELECT * FROM d
> ----
> 0.99999999999999999999
> ```

This result is consistent with postgres, and with what we would get if we had a non-constant `(a/c)*(b/c)` expression with `(a,b,c)=(9,1,3)`.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50254#-:-M9x0XIU7HuxZHr3oKkz:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by RaduBerinde — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50254#-:-M9xmpSbC69WUocVPNFS:b-tlx7ko)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by andy-kimball** [comment]
As some context, I never removed this back when I did original constant folding because the constant folding is part of CRDB's typing rules, and changing it is a breaking change (and at the time I was trying to keep exact compatibility). Make sure to work with docs team to document this breaking change.

**Comment by RaduBerinde** [comment]
bors r-

I will add a proper release note.

**Comment by mgartner** [comment]
Nice! 🎉 🎁 🍰

**Comment by RaduBerinde** [comment]
I added a better commit message explaining the reasoning for the change.

**Comment by RaduBerinde** [comment]
TestDrainingProcessorSwallowsUncertaintyError flake.

bors r+

**Pull request merged**
