### PR TITLE
opt: add initial support for geospatial lookup joins

### PR DESCRIPTION
**Pull request by rytaft**
This commit contains a prototype for adding some support for
geospatial index acceleration in the optimizer. It adds a new
operator, `GeospatialLookupJoin`, as well as a transformation rule
to generate `GeospatialLookupJoin`s when one of the supported
geospatial functions is used as one of the filter conditions of
a join.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
> Reviewed 7 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47713)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @mjibson, @otan, @RaduBerinde, @rytaft, and @sumeerbhola)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 1627 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-M5Srb2I1_DIA6d_xGgh:-M5Srb2I1_DIA6d_xGgi:bfhqxrl) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dc2ae90ed6842fe6621171b7eead9e773e37903/pkg/sql/opt/xform/custom_funcs.go#L1627)):*
> ```Go
> 	"st_contains":    memo.GeospatialContains,
> 	"st_containedby": memo.GeospatialContainedBy,
> 	"st_intersects":  memo.GeospatialIntersects,
> ```

is this where we will add more function name entries that also map to these three?
For geospatial expressions these 3 relationships are sufficient -- I don't think there is a need to combine these using boolean operator.

But for JSON and Array joins, I think we can have an expression. A made up example: 
`(y @> '{"a":1, "b":2}'::json and y <@ x) or (y @> x and  y @> '{"w":29}'::json)`
where x is the column in the row doing the lookup and y is the indexed element.

I have two questions:
- I am adding an `InvertedJoinerSpec` to processors_sql.proto. How does what the optimizer produce get translated into specs in that file?
- The expression above would need to be represented in the `InvertedJoinerSpec`: I am assuming we already have protos that can represent such expressions -- any suggestion on what I could use?
___
*[pkg/sql/opt/xform/rules/join.opt, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-M5ShIKo92lwQuNlYjGS:-M5ShIKpABCv56ExDDg1:b-sd5gto) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dc2ae90ed6842fe6621171b7eead9e773e37903/pkg/sql/opt/xform/rules/join.opt#L117)):*
> ```
> # indexes). See the GenerateGeospatialLookupJoins custom function for more
> # details.
> # TODO(rytaft): Add support for LeftJoin.
> ```

is LeftJoin a left outer join?
___
*[pkg/sql/opt/xform/rules/join.opt, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-M5ShLAb70F9GFkEpSgl:-M5ShLAb70F9GFkEpSgm:bge0b3p) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dc2ae90ed6842fe6621171b7eead9e773e37903/pkg/sql/opt/xform/rules/join.opt#L117)):*
> ```
> # indexes). See the GenerateGeospatialLookupJoins custom function for more
> # details.
> # TODO(rytaft): Add support for LeftJoin.
> ```

I'm starting to write the inverted index lookup join code and want to make sure I don't miss something.
My assumption is that the row doing the lookup will be used to compute a set expression (this will vary for different functions: contains, intersects, ...) and the inverted index will be one index column (some Datum, not necessarily int, so this code can be used for JSON and array joins too) followed by the PK columns. The sets in the set expression will be represented using spans of EncDatums (corresponding to the first column in the inverted index).
I think there are two categories of cases:
- Inner Join and Semi Join: if there is no match for an input row in the inverted index, nothing needs to be output, since there is no possibility that that input row could match something.
- Left outer join and Anti join: if nothing matches, one does need to output a row with the PK columns set to Null.

In both cases the enclosing index join will decide what finally gets output.
Is this consistent with your thinking?

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/xform/custom_funcs.go, line 1627 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-M5Srb2I1_DIA6d_xGgh:-M5TBFf47MoMdvx1fKzp:b-g5ko7c) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dc2ae90ed6842fe6621171b7eead9e773e37903/pkg/sql/opt/xform/custom_funcs.go#L1627)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is this where we will add more function name entries that also map to these three?
For geospatial expressions these 3 relationships are sufficient -- I don't think there is a need to combine these using boolean operator.

But for JSON and Array joins, I think we can have an expression. A made up example: 
`(y @> '{"a":1, "b":2}'::json and y <@ x) or (y @> x and  y @> '{"w":29}'::json)`
where x is the column in the row doing the lookup and y is the indexed element.

I have two questions:
- I am adding an `InvertedJoinerSpec` to processors_sql.proto. How does what the optimizer produce get translated into specs in that file?
- The expression above would need to be represented in the `InvertedJoinerSpec`: I am assuming we already have protos that can represent such expressions -- any suggestion on what I could use?

</blockquote></details>

The optimizer produces `planNode`s through calls to `optExecFactory`. Then the distsql physical planner (distsql_physical_planner.go) generates specs from `planNode`s.  You can check out `lookupJoinNode` for a relevant example.

Processors get expressions as SQL strings that they parse (the expressions use the `@1, @2, @3..` notation to refer to columns). Existing join processors use expressions for ON conditions.

**Review by RaduBerinde — COMMENTED** [review]
Looks good to me!

I think the operator can be generalized for any inverted index (just need to abstract the mechanics of how we get the spans and how we combine the results). But I don't see a problem with starting out with a Geo-specific operator and generalizing later - we should just keep it in mind so we don't have to rework a lot of things.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-:-M5TKAPb3P_aI5zNRcuV:b-3sviup)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @mjibson, @otan, @RaduBerinde, @rytaft, and @sumeerbhola)

___
*[pkg/sql/opt/memo/expr.go, line 429 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-M5TJksw0U6bH5ZCOIj4:-M5TJksx0cTTw13IoURZ:b73b5us) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dc2ae90ed6842fe6621171b7eead9e773e37903/pkg/sql/opt/memo/expr.go#L429)):*
> ```Go
> 
> const (
> 	// GeospatialContains corresponds to a join in which for each row of the
> ```

Feels like this belongs at a lower layer (whichever one we'll be using to get the index spans)
___
*[pkg/sql/opt/ops/relational.opt, line 310 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-M5TA6fq68Hl7K0galTy:-M5TA6fq68Hl7K0galTz:b-u1g9nr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dc2ae90ed6842fe6621171b7eead9e773e37903/pkg/sql/opt/ops/relational.opt#L310)):*
> ```
> }
> 
> # GeospatialLookupJoin represents a join between an input expression and an index,
> ```

[nit] consider using Geo instead of Geospatial to shorten these names
___
*[pkg/sql/opt/xform/testdata/rules/join, line 1636 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-M5TMQYD2sNWrJOrTU0q:-M5TMQYD2sNWrJOrTU0r:b-s2zywb) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dc2ae90ed6842fe6621171b7eead9e773e37903/pkg/sql/opt/xform/testdata/rules/join#L1636)):*
> ```
> ----
> 
> opt expect=GenerateGeospatialLookupJoins
> ```

[it] Add a comment explaining what the query is doing (looks like it's calculating the densities of two neighborhoods)
___
*[pkg/sql/opt/xform/testdata/rules/join, line 1642 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-M5TMPXO9Rfb5yQ3d-9J:-M5TMPXO9Rfb5yQ3d-9K:bdm4nxs) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dc2ae90ed6842fe6621171b7eead9e773e37903/pkg/sql/opt/xform/testdata/rules/join#L1642)):*
> ```
> FROM nyc_census_blocks AS c
> JOIN nyc_neighborhoods AS n
> ON ST_Intersects(c.geom, n.geom)  AND c.boroname = n.boroname
> ```

[nit] extra space
___
*[pkg/sql/opt/xform/testdata/rules/join, line 1660 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-M5TL06O75bMMZqt8jB_:-M5TL06O75bMMZqt8jBa:bk9w5kd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dc2ae90ed6842fe6621171b7eead9e773e37903/pkg/sql/opt/xform/testdata/rules/join#L1660)):*
> ```
>  │    │    ├── lookup columns are key
>  │    │    ├── fd: (9)==(12), (12)==(9)
>  │    │    ├── geospatial-lookup-join
> ```

This should show the GeospatialRelationship

**Review by rytaft — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-:-M5ci-riCkjzP7EDJ4RL:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @mjibson, @otan, and @sumeerbhola)

___
*[pkg/sql/opt/memo/expr.go, line 429 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-M5TJksw0U6bH5ZCOIj4:-M5cJu_G6-eLmLt2mt_0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dc2ae90ed6842fe6621171b7eead9e773e37903/pkg/sql/opt/memo/expr.go#L429)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Feels like this belongs at a lower layer (whichever one we'll be using to get the index spans)
</blockquote></details>

Done.
___
*[pkg/sql/opt/ops/relational.opt, line 310 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-M5TA6fq68Hl7K0galTy:-M5cLHam9iATLu4qDIqk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dc2ae90ed6842fe6621171b7eead9e773e37903/pkg/sql/opt/ops/relational.opt#L310)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] consider using Geo instead of Geospatial to shorten these names
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 1627 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-M5Srb2I1_DIA6d_xGgh:-M5ci4jCBJfGILkzAlOg:b-vcuprx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dc2ae90ed6842fe6621171b7eead9e773e37903/pkg/sql/opt/xform/custom_funcs.go#L1627)):*
> is this where we will add more function name entries that also map to these three?

Yes, exactly. I'll work on adding the others in.

> But for JSON and Array joins...

Agreed that we'll need to support other types of relationships for those. I think we can add those relationships later when we're ready to support them.

I'll add some boilerplate in `optExecFactory` so you or I can fill it in whenever the new operator is ready.
___
*[pkg/sql/opt/xform/rules/join.opt, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-M5ShIKo92lwQuNlYjGS:-M5cLZa30ySbzxVytFv6:b-9x47hj) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dc2ae90ed6842fe6621171b7eead9e773e37903/pkg/sql/opt/xform/rules/join.opt#L117)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is LeftJoin a left outer join?
</blockquote></details>

Yep, exactly
___
*[pkg/sql/opt/xform/rules/join.opt, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-M5ShLAb70F9GFkEpSgl:-M5cLkPfAKX8R-wWvpA6:bpvkpn5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dc2ae90ed6842fe6621171b7eead9e773e37903/pkg/sql/opt/xform/rules/join.opt#L117)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I'm starting to write the inverted index lookup join code and want to make sure I don't miss something.
My assumption is that the row doing the lookup will be used to compute a set expression (this will vary for different functions: contains, intersects, ...) and the inverted index will be one index column (some Datum, not necessarily int, so this code can be used for JSON and array joins too) followed by the PK columns. The sets in the set expression will be represented using spans of EncDatums (corresponding to the first column in the inverted index).
I think there are two categories of cases:
- Inner Join and Semi Join: if there is no match for an input row in the inverted index, nothing needs to be output, since there is no possibility that that input row could match something.
- Left outer join and Anti join: if nothing matches, one does need to output a row with the PK columns set to Null.

In both cases the enclosing index join will decide what finally gets output.
Is this consistent with your thinking?
</blockquote></details>

That sounds right to me
___
*[pkg/sql/opt/xform/testdata/rules/join, line 1636 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-M5TMQYD2sNWrJOrTU0q:-M5caEEQ87NZuSdmLKpe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dc2ae90ed6842fe6621171b7eead9e773e37903/pkg/sql/opt/xform/testdata/rules/join#L1636)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[it] Add a comment explaining what the query is doing (looks like it's calculating the densities of two neighborhoods)
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/testdata/rules/join, line 1642 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-M5TMPXO9Rfb5yQ3d-9J:-M5caF8X4MUatl_SoEuq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dc2ae90ed6842fe6621171b7eead9e773e37903/pkg/sql/opt/xform/testdata/rules/join#L1642)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] extra space
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/testdata/rules/join, line 1660 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-M5TL06O75bMMZqt8jB_:-M5cbaNJ2ZOIju_CS3nZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dc2ae90ed6842fe6621171b7eead9e773e37903/pkg/sql/opt/xform/testdata/rules/join#L1660)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This should show the GeospatialRelationship
</blockquote></details>

Done.

**Review by rytaft — COMMENTED** [review]
I think I've made all the changes discussed, and I think this should be ok to merge now if it looks ok. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-:-M5d7dJ49sZYtT9J3Vgl:b-lima4e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @mjibson, @otan, and @sumeerbhola)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 1627 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-M5Srb2I1_DIA6d_xGgh:-M5d6oDq-Ie1EBYyIdmb:b-fcqwu8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dc2ae90ed6842fe6621171b7eead9e773e37903/pkg/sql/opt/xform/custom_funcs.go#L1627)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

> is this where we will add more function name entries that also map to these three?

Yes, exactly. I'll work on adding the others in.

> But for JSON and Array joins...

Agreed that we'll need to support other types of relationships for those. I think we can add those relationships later when we're ready to support them.

I'll add some boilerplate in `optExecFactory` so you or I can fill it in whenever the new operator is ready.
</blockquote></details>

Made the changes.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> Reviewed 21 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-:-M5gM84p6DHClZnh6F6r:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @mjibson, @otan, @rytaft, and @sumeerbhola)

___
*[pkg/sql/opt_exec_factory.go, line 682 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-M5gJ41u8sKJmSmKK8pn:-M5gJ41v95qm0oRTR5L8:b-inx7ix) ([raw file](https://github.com/cockroachdb/cockroach/blob/58b820df118a42c91d363909f0933d6e97607b40/pkg/sql/opt_exec_factory.go#L682)):*
> ```Go
> ) (exec.Node, error) {
> 	// TODO(rytaft, sumeerbhola): Fill this in.
> 	return struct{}{}, errors.Errorf("Geospatial joins are not yet supported")
> ```

[nit] return nil
___
*[pkg/sql/opt/ops/relational.opt, line 315 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-M5gJKbj4WwQ5kEpFOYf:-M5gJKbj4WwQ5kEpFOYg:b6cl8lc) ([raw file](https://github.com/cockroachdb/cockroach/blob/58b820df118a42c91d363909f0933d6e97607b40/pkg/sql/opt/ops/relational.opt#L315)):*
> ```
> define GeoLookupJoin {
>     Input RelExpr
>     On    FiltersExpr
> ```

[nit] mention whether this On condition includes the condition from which the GeoRelationshipType is derived.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 1625 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-M5gJyrY9_AHS22D6mn0:-M5gJyrY9_AHS22D6mn1:bjxbyjg) ([raw file](https://github.com/cockroachdb/cockroach/blob/58b820df118a42c91d363909f0933d6e97607b40/pkg/sql/opt/xform/custom_funcs.go#L1625)):*
> ```Go
> }
> 
> // TODO(rytaft): add ST_DFullyWithin (geoindex.Covers) and ST_DWithin
> ```

This mapping needs a comment, especially given that some functions map to the same relationship. IIUC this is an "implies" relation and we still run the function on the lookup join results derived from the relationship.

Is the relationship equivalent for some of them (e.g. Covers)? Would that information help? I'm guessing no - the geo lookup join can still return false positives and we still need to evaluate the function?

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/exec/execbuilder/relational.go, line 1363 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-M5gMM6MAtOJXCHhdHQd:-M5gMM6MAtOJXCHhdHQe:b-r0t75r) ([raw file](https://github.com/cockroachdb/cockroach/blob/58b820df118a42c91d363909f0933d6e97607b40/pkg/sql/opt/exec/execbuilder/relational.go#L1363)):*
> ```Go
> }
> 
> func (b *Builder) buildGeoLookupJoin(join *memo.GeoLookupJoinExpr) (execPlan, error) {
> ```

Saving you a click to open the CI page - this is unused.

**Review by rytaft — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-:-M5hSqVT1PZTuPumfI9N:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @mjibson, @otan, @RaduBerinde, and @sumeerbhola)

___
*[pkg/sql/opt_exec_factory.go, line 682 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-M5gJ41u8sKJmSmKK8pn:-M5h3cpt05JT-OZMQhiG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/58b820df118a42c91d363909f0933d6e97607b40/pkg/sql/opt_exec_factory.go#L682)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] return nil
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/relational.go, line 1363 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-M5gMM6MAtOJXCHhdHQd:-M5h3enA4mE-cKb8ELSu:b-a6taqh) ([raw file](https://github.com/cockroachdb/cockroach/blob/58b820df118a42c91d363909f0933d6e97607b40/pkg/sql/opt/exec/execbuilder/relational.go#L1363)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Saving you a click to open the CI page - this is unused.
</blockquote></details>

Thanks! Fixed.
___
*[pkg/sql/opt/ops/relational.opt, line 315 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-M5gJKbj4WwQ5kEpFOYf:-M5hKJVW8-BdfIrg82d2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/58b820df118a42c91d363909f0933d6e97607b40/pkg/sql/opt/ops/relational.opt#L315)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] mention whether this On condition includes the condition from which the GeoRelationshipType is derived.
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 1625 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-M5gJyrY9_AHS22D6mn0:-M5hQmaGAzxfzXo_d6kf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/58b820df118a42c91d363909f0933d6e97607b40/pkg/sql/opt/xform/custom_funcs.go#L1625)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This mapping needs a comment, especially given that some functions map to the same relationship. IIUC this is an "implies" relation and we still run the function on the lookup join results derived from the relationship.

Is the relationship equivalent for some of them (e.g. Covers)? Would that information help? I'm guessing no - the geo lookup join can still return false positives and we still need to evaluate the function?
</blockquote></details>

Done.

**Review by rytaft — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-:-M5hrVg8DLgTLfDE5kY9:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @mjibson, @otan, @RaduBerinde, and @sumeerbhola)

**Review by rytaft — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47713#-:-M5r8wVxDnA_-YGx4LiM:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @mjibson, @otan, @RaduBerinde, and @sumeerbhola)

**Pull request merged**
