### PR TITLE
concurrency: use of lock.Modes to determine confilcts in tryActiveWait

### PR DESCRIPTION
**Pull request by arulajmani**
This patch refactors tryActiveWait to make use of lock.Modes to determine conflicts. In doing so, it splits out the logic into 3 different methods:

1. To determine a conflict with a lock holder.
2. To determine a conflict with a reservation.
3. To modify datastructures in preparation for active wait.

In doing so, we no longer make the assumption that there will only ever be a single reservation or lock holder on a key. In the future, we'll be able to further extend tryActiveWait to account for multiple locks/reservations on a key.

Informs #102210

Release note: None

### CODE REVIEW

**Comment by arulajmani** [comment]
@nvanbenschoten  still a bit rough, but the overall structure is there. I'll ping when it's ready for a detailed look.

**Comment by arulajmani** [comment]
@nvanbenschoten I reworked this a bit after our pair programming session the other day -- I'm quite happy with how things ended up! I still plan on adding a commit here that threads in cluster settings into the lock table, and using them when constructing lock modes, but that shouldn't preclude you from having a look.

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102973)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102973#-NVAfSlGBkfYbcpw-LUB):*
`s/confilcts/conflicts/`
___
*[`-- commits` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102973#-NVAfaCW4Zjm0RM4E05A):*
Do we need to call out the method to determine a conflict with a waiter? Or were we planning to consider reservations to be a form of waiters? In which case, `s/reservation/waiter/`.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1515 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102973#-NVAgLtj8ggHNuKazglz:-NVAgLtj8ggHNuKazgm-:b-tkwzqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a391952bc7ad6c8b05f2905bbf51f84bf5024b6/pkg/kv/kvserver/concurrency/lock_table.go#L1515)):*
> ```Go
> // tryActiveWait decides whether the request, g, should actively wait at this
> // key or not. It adjusts the data-structures appropriately if the request
> // needs. If the request needs to wait at this key and the supplied notify
> ```

"if the request needs"

Consider giving a hint at what this adjustment might look like. You don't need to be precise or exhaustive, but some indication that this function may add g to the lock's wait-queue would be helpful.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1521 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102973#-NVAgeQxEiIyRI-bMRFU:-NVAgeQxEiIyRI-bMRFV:b-dofrjt) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a391952bc7ad6c8b05f2905bbf51f84bf5024b6/pkg/kv/kvserver/concurrency/lock_table.go#L1521)):*
> ```Go
> // with any locks or reservations that may be present at this key. A request
> // is only allowed to proceed if it is compatible with all locks and
> // reservations.
> ```

"all locks and reservations"

And also all other waiters, right?
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1524 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102973#-NVAgjKd-1v_NHS-Ih_3:-NVAgjKd-1v_NHS-Ih_4:b-gke4of) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a391952bc7ad6c8b05f2905bbf51f84bf5024b6/pkg/kv/kvserver/concurrency/lock_table.go#L1524)):*
> ```Go
> //
> // There is one tricky case with tryActiveWait -- when the key is only locked by
> // finalized transactions. Such cases are determined by consulting the
> ```

"by finalized transactions"

This implies that we always know with confidence whether a transaction is finalized or not. Consider rephrasing to something like "when a key is only locked by transactions that are known to be finalized".
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1528 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102973#-NVAgzsZE98fDcIwviSW:-NVAgzsZE98fDcIwviSX:bpmnww3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a391952bc7ad6c8b05f2905bbf51f84bf5024b6/pkg/kv/kvserver/concurrency/lock_table.go#L1528)):*
> ```Go
> // are a few considerations here:
> //
> // - For unreplicated locks, this method will silently clear the lock. The
> ```

Consider generalizing this sentence to work with multiple lock holders. Something like "the method will remove the finalized transaction(s) from the lock, which may leave it empty".
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1569 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102973#-NVAkERn466QxU6rCfLY:-NVAkERn466QxU6rCfLZ:bcqpmt5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a391952bc7ad6c8b05f2905bbf51f84bf5024b6/pkg/kv/kvserver/concurrency/lock_table.go#L1569)):*
> ```Go
> // traces of them via a round of replication. This is discussed in more detail
> // in #41720. Specifically, see mention of "contention footprint" and
> // COMMITTED_BUT_NOT_REMOVABLE. 	Also, resolving these locks/intents would
> ```

nit: there's a tab in here. In fact, there's a bit of messed up spacing in these lines.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1607 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102973#-NVAoCJ38WNr7jCs7tlM:-NVAoCJ38WNr7jCs7tlN:b-9kclva) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a391952bc7ad6c8b05f2905bbf51f84bf5024b6/pkg/kv/kvserver/concurrency/lock_table.go#L1607)):*
> ```Go
> 	// after nudging the lock, there's no conflict -- this lock can be gc-ed at
> 	// the caller.
> 	if !l.isHeldOrReserved() {
> ```

We only hit this on the `clearLockHolder` path of `conflictsWithLockHolder`, right? If so, we're not doing any nudging here. It's also not clear that this benefits from being separated from that logic. The split raises questions about whether there are other reasons why we'd find a lock that's not held or reserved.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1608 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102973#-NVAltzNAA0Kwwxo-h5c:-NVAltzNAA0Kwwxo-h5d:b-apgt8e) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a391952bc7ad6c8b05f2905bbf51f84bf5024b6/pkg/kv/kvserver/concurrency/lock_table.go#L1608)):*
> ```Go
> 	// the caller.
> 	if !l.isHeldOrReserved() {
> 		// TODO(arul): Should a locking request acquire a reservation instead of
> ```

It probably should. The current behavior is surprising. This would also allow us to simplify the code, right? We could eliminate the `transitionedToFree` logic?
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1666 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102973#-NVAqrhl0xO-JkJnGYXU:-NVAqrhl0xO-JkJnGYXV:b-kd4z96) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a391952bc7ad6c8b05f2905bbf51f84bf5024b6/pkg/kv/kvserver/concurrency/lock_table.go#L1666)):*
> ```Go
> 	var ws waitingState
> 	// TODO(arul): try and improve the structure of this logic.
> 	// TODO(arul): What if the request is already in the queue?
> ```

Do we need to address this TODO now? Would it help to push the `waitQueueMaxLengthExceeded` handling into `adjustWaitQueues`? 
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1765 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102973#-NVArFiX7g-37u6t6oRf:-NVArFiX7g-37u6t6oRg:bi496tb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a391952bc7ad6c8b05f2905bbf51f84bf5024b6/pkg/kv/kvserver/concurrency/lock_table.go#L1765)):*
> ```Go
> 		waitForState.kind = waitSelf
> 	} else if l.distinguishedWaiter == nil {
> 		l.distinguishedWaiter = g
> ```

It's surprising to see that `constructWaitingState` is mutating `lockState`. Is there a better place for this? For instance, should we be setting the `l.distinguishedWaiter` in `adjustWaitQueues` and then just checking whether `g` is the distinguished waiter here?
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1870 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102973#-NVAq6h74zTHFDyt8YY0:-NVAq6h74zTHFDyt8YY1:b83hedq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a391952bc7ad6c8b05f2905bbf51f84bf5024b6/pkg/kv/kvserver/concurrency/lock_table.go#L1870)):*
> While doing so, it should mark all active waiters it doesn't conflict with as inactive (and nudge them to no longer wait at this lock).

Why should it do this? Is that because we know we'd only reach this point if we don't conflict with the lock holder or any reservations? Does that necessarily mean that waiters that we don't conflict with also don't conflict with the lock holder or any reservation?
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1888 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102973#-NVAqdLq0Bso8a38uvvf:-NVAqdLq0Bso8a38uvvg:b-owfvnb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a391952bc7ad6c8b05f2905bbf51f84bf5024b6/pkg/kv/kvserver/concurrency/lock_table.go#L1888)):*
> ```Go
> 		return // non-{locking,transactional} requests cannot acquire reservations.
> 	}
> 	if l.reservation != nil && l.reservation == g {
> ```

Again, didn't we already check this condition?
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1923 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102973#-NVAnhTD5fnyXhOeNts9:-NVAnhTD5fnyXhOeNtsA:b24ito) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a391952bc7ad6c8b05f2905bbf51f84bf5024b6/pkg/kv/kvserver/concurrency/lock_table.go#L1923)):*
> ```Go
> 		return false, nil // the lock isn't held; no conflict to speak of
> 	}
> 	if g.isSameTxn(lockHolderTxn) {
> ```

Didn't we already check this in the call to `alreadyLockedOrReservedByRequest`?
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1937 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102973#-NVAmo3A31Idnd6UfAcc:-NVAmo3A31Idnd6UfAcd:b-u8jjrj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a391952bc7ad6c8b05f2905bbf51f84bf5024b6/pkg/kv/kvserver/concurrency/lock_table.go#L1937)):*
> ```Go
> 	}
> 
> 	if g.str == lock.None {
> ```

It's subtle that `g.str` is mutable over the lifetime of a `lockTableGuardImpl` and yet it looks to the user like it is an immutable attribute of the guard. That's enforced by comments like "if the request, referenced by the supplied lockTableGuardImpl". I think this is why the previous code passed around a SpanAccess alongside the guard. I don't think we need to go that far, but maybe push `g.str` behind a well-named, well-commented accessor method which references the iteration in `stepToNextSpan`.

**Review by arulajmani — COMMENTED** [review]
@nvanbenschoten I've replied in-line to all your comments. Even though a few of them weren't directly applicable in the new structure, I think the spirit still holds -- so thanks for the detailed look on this one! Like we spoke about offline, I opened a fresh slate PR over at https://github.com/cockroachdb/cockroach/pull/104261. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102973#-:-NWwd0fZB6oqFp6RneVi:b-mz2uec)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1515 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102973#-NVAgLtj8ggHNuKazglz:-NWtrbOM6cBwpMikUWUz:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a391952bc7ad6c8b05f2905bbf51f84bf5024b6/pkg/kv/kvserver/concurrency/lock_table.go#L1515)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"if the request needs"

Consider giving a hint at what this adjustment might look like. You don't need to be precise or exhaustive, but some indication that this function may add g to the lock's wait-queue would be helpful.
</blockquote></details>

Done. 
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1521 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102973#-NVAgeQxEiIyRI-bMRFU:-NWu-c-v3VbUx-ZLt-oi:b-lx4fj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a391952bc7ad6c8b05f2905bbf51f84bf5024b6/pkg/kv/kvserver/concurrency/lock_table.go#L1521)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"all locks and reservations"

And also all other waiters, right?
</blockquote></details>

Fixed. 
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1524 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102973#-NVAgjKd-1v_NHS-Ih_3:-NWu-duKCavhHDu9AKKN:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a391952bc7ad6c8b05f2905bbf51f84bf5024b6/pkg/kv/kvserver/concurrency/lock_table.go#L1524)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"by finalized transactions"

This implies that we always know with confidence whether a transaction is finalized or not. Consider rephrasing to something like "when a key is only locked by transactions that are known to be finalized".
</blockquote></details>

Fixed.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1569 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102973#-NVAkERn466QxU6rCfLY:-NWu0GtUEGhuH-h8oBN7:bhtthwa) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a391952bc7ad6c8b05f2905bbf51f84bf5024b6/pkg/kv/kvserver/concurrency/lock_table.go#L1569)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: there's a tab in here. In fact, there's a bit of messed up spacing in these lines.
</blockquote></details>

Ugh I think the line wrapping to 80 chars did this. Lazy question -- is there an easy way to wrap with tabs? 
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1607 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102973#-NVAoCJ38WNr7jCs7tlM:-NWtzy6x3xQyDGntp3XF:b1toeeb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a391952bc7ad6c8b05f2905bbf51f84bf5024b6/pkg/kv/kvserver/concurrency/lock_table.go#L1607)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We only hit this on the `clearLockHolder` path of `conflictsWithLockHolder`, right? If so, we're not doing any nudging here. It's also not clear that this benefits from being separated from that logic. The split raises questions about whether there are other reasons why we'd find a lock that's not held or reserved.
</blockquote></details>

I ended up reworking this considerably. We can iterate on the new PR, but I think the new approach is more in line with what I think you're asking for in this comment. 
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1608 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102973#-NVAltzNAA0Kwwxo-h5c:-NWtzO0Q0e_YQbn51xU_:b-2wy1qa) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a391952bc7ad6c8b05f2905bbf51f84bf5024b6/pkg/kv/kvserver/concurrency/lock_table.go#L1608)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It probably should. The current behavior is surprising. This would also allow us to simplify the code, right? We could eliminate the `transitionedToFree` logic?
</blockquote></details>

I've replaced this with a more opinionated TODO, but I'll probably get to it in a future patch -- mostly because there'll be some test churn as a result. 

As for the `transitionedToFree` logic, I think we might need to keep it unless we do something about non-locking read requests as well. 
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1666 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102973#-NVAqrhl0xO-JkJnGYXU:-NWtz9us0ITf_9cu1FxI:b-94da66) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a391952bc7ad6c8b05f2905bbf51f84bf5024b6/pkg/kv/kvserver/concurrency/lock_table.go#L1666)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need to address this TODO now? Would it help to push the `waitQueueMaxLengthExceeded` handling into `adjustWaitQueues`? 
</blockquote></details>

This is addressed now. 
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1765 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102973#-NVArFiX7g-37u6t6oRf:-NWtxA1A3LUHg1L5m9Z1:bnt7gth) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a391952bc7ad6c8b05f2905bbf51f84bf5024b6/pkg/kv/kvserver/concurrency/lock_table.go#L1765)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It's surprising to see that `constructWaitingState` is mutating `lockState`. Is there a better place for this? For instance, should we be setting the `l.distinguishedWaiter` in `adjustWaitQueues` and then just checking whether `g` is the distinguished waiter here?
</blockquote></details>

I was binge watching Rust videos over the weekend, like one does, so coming back and seeing what I'd written here was jarring. 
The good news is I ended up discovering your suggestion for myself, so I feel a bit better.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1870 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102973#-NVAq6h74zTHFDyt8YY0:-NWtxoco91gp2K1lSpFO:b-wsk4kv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a391952bc7ad6c8b05f2905bbf51f84bf5024b6/pkg/kv/kvserver/concurrency/lock_table.go#L1870)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> While doing so, it should mark all active waiters it doesn't conflict with as inactive (and nudge them to no longer wait at this lock).

Why should it do this? Is that because we know we'd only reach this point if we don't conflict with the lock holder or any reservations? Does that necessarily mean that waiters that we don't conflict with also don't conflict with the lock holder or any reservation?
</blockquote></details>

It's been a while, but I think I wrote this comment without upgrade locks in mind. But you're right, in the general case, where upgrade locks are a thing this won't work. 

This function is getting removed now, and with it, so is the TODO. We'll need something like this for lock transitions though (I think one place is `lockIsFree`). Let's make sure we consider UPGRADE locks when we do implement this. 
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1888 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102973#-NVAqdLq0Bso8a38uvvf:-NWtyOlVC_SljEw20p6E:bp4oyyz) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a391952bc7ad6c8b05f2905bbf51f84bf5024b6/pkg/kv/kvserver/concurrency/lock_table.go#L1888)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Again, didn't we already check this condition?
</blockquote></details>

Not applicable in the new structure, but I've tried to apply the spirit of this comment and be very deliberate about which conditions are possible and which ones are not. 
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1937 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102973#-NVAmo3A31Idnd6UfAcc:-NWu0RRZ7ZQV7S3XJTZs:bcmsshj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a391952bc7ad6c8b05f2905bbf51f84bf5024b6/pkg/kv/kvserver/concurrency/lock_table.go#L1937)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It's subtle that `g.str` is mutable over the lifetime of a `lockTableGuardImpl` and yet it looks to the user like it is an immutable attribute of the guard. That's enforced by comments like "if the request, referenced by the supplied lockTableGuardImpl". I think this is why the previous code passed around a SpanAccess alongside the guard. I don't think we need to go that far, but maybe push `g.str` behind a well-named, well-commented accessor method which references the iteration in `stepToNextSpan`.
</blockquote></details>

Noting that I haven't done this yet, but will do before we merge the new PR.

**Pull request closed without merging**
