### PR TITLE
support: add GoLand language support for datadriven and logic test files

### PR DESCRIPTION
**Pull request by mgartner**
#### support: add GoLand language support for datadriven and logic test files

A textmate language support bundle has been added for data-driven and
logic test files. Support currently includes:

  * Syntax highlighting of comments in data-driven test files.
  * Syntax highlighting of comments, commands, and SQL in logic test files.
  * Auto-commenting of data-driven and logic test files with GoLand's
    `Code > Comment with Line Comment` or any associated hotkey.

In order for language support to apply, data-driven test files must have
the `.ddt` extension.

To install the textmate bundle, enable the TextMate Bundles plugin in
`Preferences > Plugins`, then click the `+` button in the TextMate
Bundles configuration `Preferences > Editor > TextMate Bundles` and add
the `support/textmate/DataDriven.tmbundle`
directory.

Release justification: This change only affects development tooling.

Release note: None

#### sql/logictest: add .ddt extension to all logic test files

This commit adds the `.ddt` extension to all logic test files to enable
syntax highlighting and language support when the DataDriven.tmbundle
bundle has been installed in GoLand.

Release note: None

#### support: add optimizer test syntax highlighting to DataDriven.tmbundle

Syntax highlighting of commands and SQL for data-driven optimizer tests
has been added to `DataDriven.tmbundle`.

Release note: None

#### support: add syntax highlighting for basic datadriven tests

Previously, only commands in logic and optimizer data-driven tests were
syntax highlighted. This commit updates `DataDriven.tmbundle` so that
commands of all data-driven tests are syntax highlighted.

Release note: None

#### opt: add .ddt extension to all optimizer data-driven test files

This commit adds the `.ddt` extension to all data-driven test files in
the optimizer to enable syntax highlighting and language support when
the datadrive.tmLanguage bundle has been installed in GoLand.

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
Here's what the logic test syntax highlighting looks like with my GoLand theme:

Screen Shot 2022-03-17 at 4 21 25 PM

It's very minimal, but we can always extend it if we feel the need.

I'm not sure the bundle should live in `pkg/sql/logictest`, given that it provides support for more generic datadriven tests too, but I couldn't think of a better place. I'm open to suggestions.

**Comment by rafiss** [comment]
> I'm not sure the bundle should live in pkg/sql/logictest, given that it provides support for more generic datadriven tests too, but I couldn't think of a better place. I'm open to suggestions.

would it make sense in https://github.com/cockroachdb/datadriven ?

**Comment by rafiss** [comment]
I wonder how this affects backporting datadriven test changes. I guess this would be safe to backport to supported releases

**Comment by mgartner** [comment]
> would it make sense in https://github.com/cockroachdb/datadriven ?

I thought about this, but I think the syntax highlighting of specific commands like `statement`, `query`, etc. is too specific for the more general `datadriven` library.

> I wonder how this affects backporting datadriven test changes. I guess this would be safe to backport to supported releases

Good point. We should probably backport this to make our lives easier.

**Review by yuzefovich — APPROVED** [review]
Nice! :lgtm:

+1 on backporting this.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78048#-:-MySo3063x2C7V2YyUpG:brvrml2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @mgartner)

___
*[pkg/sql/logictest/support/textmate/datadriven.tmLanguage/Syntaxes/datadriven.tmLanguage, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78048#-MySnRcKAN2DRY-BIXvg:-MySnRcLEo84jlKmT3SE:bdh7waz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ccc78634bba25f936b9c08c7a17b0ef7628c151/pkg/sql/logictest/support/textmate/datadriven.tmLanguage/Syntaxes/datadriven.tmLanguage#L24)):*
> ```
> 					<key>end</key>
> 					<string>\n</string>
>                 <key>name</key>
> ```

nit: there seems to be a mix of tabs and spaces in both `tmLanguage` files.
___
*[pkg/sql/logictest/support/textmate/datadriven.tmLanguage/Syntaxes/logictest.tmLanguage, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78048#-MySnZknB12kjkecgLsL:-MySnZknB12kjkecgLsM:bdelhnp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ccc78634bba25f936b9c08c7a17b0ef7628c151/pkg/sql/logictest/support/textmate/datadriven.tmLanguage/Syntaxes/logictest.tmLanguage#L26)):*
> ```
>                  <key>match</key>
>                  <string>(?x)^(
>                     statement |
> ```

nit: maybe worth ordering the patterns?

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78048)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/logictest/support/textmate/datadriven.tmLanguage/Syntaxes/datadriven.tmLanguage, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78048#-MySnRcKAN2DRY-BIXvg:-MyTSkA88m9d4xKPFdij:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ccc78634bba25f936b9c08c7a17b0ef7628c151/pkg/sql/logictest/support/textmate/datadriven.tmLanguage/Syntaxes/datadriven.tmLanguage#L24)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: there seems to be a mix of tabs and spaces in both `tmLanguage` files.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/support/textmate/datadriven.tmLanguage/Syntaxes/logictest.tmLanguage, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78048#-MySnZknB12kjkecgLsL:-MyTSmlP11h04qMHiTXE:b-xfn8hc) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ccc78634bba25f936b9c08c7a17b0ef7628c151/pkg/sql/logictest/support/textmate/datadriven.tmLanguage/Syntaxes/logictest.tmLanguage#L26)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: maybe worth ordering the patterns?
</blockquote></details>

Do you mean alphabetically?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78048)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @mgartner, and @yuzefovich)

___
*[pkg/sql/logictest/support/textmate/datadriven.tmLanguage/Syntaxes/logictest.tmLanguage, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78048#-MySnZknB12kjkecgLsL:-MyTVJjB8fOBqxM75A0n:b-7xtei2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ccc78634bba25f936b9c08c7a17b0ef7628c151/pkg/sql/logictest/support/textmate/datadriven.tmLanguage/Syntaxes/logictest.tmLanguage#L26)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Do you mean alphabetically?
</blockquote></details>

Yeah.

**Comment by mgartner** [comment]
I've made a number of changes and improvements:

* `DataDriven.tmbundle` now lives in the `support/textmate` directory, since it is not specific to logic tests.
* All the syntax files have been merged, so a single extension, `.ddt`, can be used for all files.
* Logic tests and optimizer tests now support syntax highlighting of SQL within them.
* Commands in data driven tests that are not logic or optimizer tests are now highlighted.

We should also strip the `.ddt` from the test names passed to `t.Run()` so that the test names don't change. Interestingly, the TextMate seems to support file-type recognition by looking at the first line of the file, so in theory we wouldn't need to change the extension. I'm having trouble getting that to work in GoLand, but I'll spend some more time with it before we merge this.

Here's some screenshots.

#### Logictest

image

#### Opttest

image

#### Generic data-driven test

image

**Comment by mgartner** [comment]
___
*[pkg/sql/logictest/support/textmate/datadriven.tmLanguage/Syntaxes/logictest.tmLanguage, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78048#-MySnZknB12kjkecgLsL:-MyTfoLt8sWwp3Vsnv3t:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ccc78634bba25f936b9c08c7a17b0ef7628c151/pkg/sql/logictest/support/textmate/datadriven.tmLanguage/Syntaxes/logictest.tmLanguage#L26)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Yeah.
</blockquote></details>

Done.

**Comment by yuzefovich** [comment]
LGTM.

Reviewable is really struggling with this PR lol.

In the second commit there is a change to `support/textmate/DataDriven.tmbundle/Syntaxes/datadriven.tmLanguage` that should probably go into the first commit.

**Comment by mgartner** [comment]
I'm going to split this PR up into multiple to make it easier to merge.

**Pull request closed without merging**
