### PR TITLE
insights: enable the fixed-threshold detector

### PR DESCRIPTION
**Pull request by matthewtodd**
This commit effectively enables the new "insights" subsystem, wherein we
observe in-flight statement executions and gather information about
statements that ran longer than a fixed threshold, with the intent of
supporting developers and operators tuning their workloads.

We are currently building a UI in DB console to surface these insights;
in the meantime, they are also available in the
`crdb_internal.cluster_execution_insights` table.

A local 5-minute run of the kv95 workload with the
`sql.insights.latency_threshold` cluster setting set to 0ms (disabled)
and 100ms shows an unappreciable impact on execution latencies:

| `latency_threshold` | ops(total) | ops/sec(cum) | avg(ms) | p50(ms) | p95(ms) | p99(ms) | pMax(ms) |
|---------------------|------------|--------------|---------|---------|---------|---------|----------|
| 0ms                 | 825873     | 2752.9       | 11.6    | 0.6     | 96.5    | 268.4   | 939.5    |
| 100ms               | 853175     | 2843.9       | 11.2    | 0.7     | 79.7    | 260.0   | 1208.0   |

Note that we have another, hopefully more useful, heuristic-based "slow"
detector in the works, but it will need more performance tuning before
we can enable it by default.

Release justification: Category 2: Bug fixes and low-risk updates to new
functionality

Release note (sql change): A new subsystem, "insights," has been enabled
by default, gathering slow statement executions in the
`crdb_internal.cluster_execution_insights` table along with possible
reasons for the slowness: full scans / missing indexes, contention, plan
changes, retries, etc. This system may be tuned by a handful of new
cluster settings and monitored with a handful of new metrics, all in the
`sql.insights` namespace.

### CODE REVIEW

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86216#-:-N9b1Uqd5AnQpITW8-ZE:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @matthewtodd)

**Review by j82w — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86216)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @matthewtodd)

___
*[`-- commits` line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86216#-N9bPvdg5UEYVMvYr2TF):*
Did we look at the cluster telemetry to see what percentage of queries this would include? Or what the average latency is for a few of the bigger customers? My concern is this could end up only be logging 1% as part of the benchmark, but could end up being a much higher percentage in real world scenarios which could impact performance.

**Review by j82w — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86216)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @matthewtodd)

**Pull request merged**
