### PR TITLE
sql: move jobs table auth checks out of hot path

### LINKED ISSUE #117416: sql: authorization for system.jobs table is slow
Currently, when the `system.jobs` virtual table is generated, an [authorization check](https://github.com/cockroachdb/cockroach/blob/51c7bc5f9d4480a5581495815ca718d5e11eca12/pkg/sql/crdb_internal.go#L1077) is performed for every row in the table to check whether the row should be visible to the user. This can be very slow when there are many active jobs. One user reported `SHOW JOBS` taking over a minute, with nearly all the execution time being attributable to this privilege check.

@rafiss came up with one idea:
>it looks like a simple refactor would be to change jobsauth.Authorize so that it accepts a bool parameter for the result of HasGlobalPrivilegeOrRoleOption(ctx, privilege.CONTROLJOB)

The trace in the customer issue showed all the time spent performing the lookup for this portion of the check, so this will likely improve things significantly.

Jira issue: CRDB-35163

### PR DESCRIPTION
**Pull request by DrewKimball**
Previously, the `crdb_internal.system_jobs` internal table performed an authorization check for every row, to ensure that it was visible to the current user. This could cause a large slow down when there were many rows for any query that touches `crdb_internal.system_jobs`.

This commit moves part of the authorization check outside the loop. Now, checking that the current user has `CONTROLJOB` and `VIEWJOB` global privileges only happens once per jobs table scan.

Fixes #117416

Release note (performance improvement): Some privilege checks when scanning the `crdb_internal.system_jobs` internal table now happen once before the scan, instead of once for each row. This will improve performance for queries that read from `crdb_internal.system_jobs`.

### CODE REVIEW

**Comment by sean-** [comment]
How far back is this going to be backported?

**Review by rafiss — COMMENTED** [review]
nice, the fix lgtm! i wonder if we could add a benchmark to https://github.com/cockroachdb/cockroach/blob/master/pkg/bench/rttanalysis/virtual_table_bench_test.go that would show the number of KV roundtrips decreasing when querying this table (or using SHOW JOBS)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117438#-:-Nndqr7L659Dp7M7ROwg:b-4fhb42)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava, @michae2, and @miretskiy)

**Review by michae2 — APPROVED** [review]
:lgtm: Very nice!

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117438#-:-NneUqd22HukFCzkKjy4:b-kerl87)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @jayshrivastava and @miretskiy)

**Review by mgartner — CHANGES_REQUESTED** [review]
Nice find!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117438#-:-NnjR-jJ7UrIvryNEJ5Z:bdkgtm2)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @jayshrivastava, and @miretskiy)

___
*[`pkg/jobs/jobsauth/authorization.go` line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117438#-NnjQKet2U2wAvT8Cerp:-NnjQKet2U2wAvT8Cerq:b-inys1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/c62781d39288a22b8eb9d0ad882b0afc9de457e9/pkg/jobs/jobsauth/authorization.go#L97)):*
> ```Go
> 		return false, false, err
> 	}
> 	return hasControlJob, hasViewJob, nil
> ```

Callers don't really care about these booleans, they are simply passed along to `Authorize`. So you can instead return a new struct, like `jobsauth.Privilege` that contains these booleans as private fields. That tightens up the API—it's impossible for callers to pass the wrong booleans or use their own hand-crafted booleans.

**Review by DrewKimball — COMMENTED** [review]
I tried adding a benchmark like this:
```
--- a/pkg/bench/rttanalysis/virtual_table_bench_test.go
+++ b/pkg/bench/rttanalysis/virtual_table_bench_test.go
@@ -62,5 +62,22 @@ SELECT * FROM crdb_internal.tables;
 SELECT * FROM t1;
 SELECT * FROM t2;`,
                },
+               // Check the number of KV requests needed to perform a full scan of the jobs
+               // table, as is done when running SHOW JOBS.
+               {
+                       Name: "jobs table scan",
+                       SetupEx: []string{
+                               `
+INSERT INTO system.jobs (id, status, created)
+SELECT unique_rowid(), 'RUNNING', now() FROM generate_series(1, 100);`,
+                               `
+INSERT INTO system.job_info (job_id, info_key, value)
+SELECT id, 'legacy_payload', '\x0a1e6175746f6d617469632053514c20537461747320636f6d70616374696f6e12046e6f646518d683adf6f4ce830320b892bff6f4ce83039a0210a2dd19fc71cf4efaabac97be05da7c66a2020a08d7843d100218002004f20100'
+FROM system.jobs WHERE job_type IS NULL;`,
+                       },
+                       Stmt: `
+SET ROLE = testuser;
+SELECT * FROM crdb_internal.jobs;`,
+               },
        })
 }
```
but didn't have much luck getting a non-root user, which is required for repro. However, I did manage to verify that the fix works by running these statements manually and collecting statement bundles.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117438#-:-NnwXkmM7VsfOK1YC-9r:b1yah59)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @jayshrivastava, @mgartner, and @miretskiy)

___
*[`pkg/jobs/jobsauth/authorization.go` line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117438#-NnjQKet2U2wAvT8Cerp:-NnwXztVBZRHCs6LUzee:b-fznogt) ([raw file](https://github.com/cockroachdb/cockroach/blob/c62781d39288a22b8eb9d0ad882b0afc9de457e9/pkg/jobs/jobsauth/authorization.go#L97)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Callers don't really care about these booleans, they are simply passed along to `Authorize`. So you can instead return a new struct, like `jobsauth.Privilege` that contains these booleans as private fields. That tightens up the API—it's impossible for callers to pass the wrong booleans or use their own hand-crafted booleans.
</blockquote></details>

Good idea, done.

**Review by rafiss — COMMENTED** [review]
the framework already uses a non-root user: d0b49444ed42608351b30be9911a4a3f5084e1e7

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117438#-:-NnyDp4c1oF_XyAq9xpj:b5ipkgl)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jayshrivastava, @mgartner, @michae2, and @miretskiy)

**Review by rafiss — COMMENTED** [review]
ah, but that testuser is still an admin, so i think they would also bypass the slow code since `a.HasAdminRole` would short-circuit the rest of the function, and the result of that call is cached in the RoleMembershipCache.

maybe instead of `GRANT admin TO testuser` we could change that to just grant the specific privileges needed by the test

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117438#-:-NnyDvoE9RWxOzwiCfyp:bcl6nhf)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jayshrivastava, @mgartner, @michae2, and @miretskiy)

**Comment by DrewKimball** [comment]
>How far back is this going to be backported?

23.2 is probably reasonable...

**Review by mgartner — APPROVED** [review]
Looks great! :lgtm: modulo Rafi's comments.

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117438#-:-NoMqx7mBHUAVmvr-STd:b-i1tjdj)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @jayshrivastava and @miretskiy)

**Comment by stevendanna** [comment]
@DrewKimball Just noticed this was still outstanding. It seems like a really worthwhile improvement to me.  Anything I can do to help move it forward?

**Comment by mgartner** [comment]
Friendly ping @DrewKimball - is this still on your radar?

**Comment by DrewKimball** [comment]
Sorry for the delay. I'll spend some time today trying to get the test working.

**Comment by DrewKimball** [comment]
I've added a commit that adds a method for rttanalysis tests to specify a user without admin privileges, plus benchmarks for `SHOW JOBS` and `SELECT * FROM crdb_internal.system_jobs` with that user. With the changes in this PR, the round trips show a nice reduction from 83 to 4.

**Review by mgartner — APPROVED** [review]
:lgtm: Nicely done!

> Reviewed 12 of 12 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117438#-:-NzcpMvd0U8RZfjDFt3C:b-msncp4)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @jayshrivastava, @miretskiy, and @rafiss)

**Review by rafiss — APPROVED** [review]

**Comment by rafiss** [comment]
noting the great improvement for posterity:
```
goos: darwin
goarch: arm64
                                           │ bench-old.txt  │            bench-new.txt            │
                                           │     sec/op     │   sec/op     vs base                │
Jobs/non_admin_show_jobs-8                   3333.55m ± 12%   77.74m ± 2%  -97.67% (p=0.000 n=10)
Jobs/non_admin_crdb_internal.system_jobs-8   3125.24m ±  2%   73.86m ± 1%  -97.64% (p=0.000 n=10)
geomean                                         3.228         75.78m       -97.65%

                                           │ bench-old.txt │           bench-new.txt            │
                                           │  roundtrips   │ roundtrips  vs base                │
Jobs/non_admin_show_jobs-8                     83.000 ± 0%   4.000 ± 0%  -95.18% (p=0.000 n=10)
Jobs/non_admin_crdb_internal.system_jobs-8     83.000 ± 0%   4.000 ± 0%  -95.18% (p=0.000 n=10)
geomean                                         83.00        4.000       -95.18%

                                           │ bench-old.txt  │            bench-new.txt             │
                                           │      B/op      │     B/op      vs base                │
Jobs/non_admin_show_jobs-8                   1519.96Mi ± 1%   27.75Mi ± 1%  -98.17% (p=0.000 n=10)
Jobs/non_admin_crdb_internal.system_jobs-8   1433.82Mi ± 0%   22.95Mi ± 3%  -98.40% (p=0.000 n=10)
geomean                                        1.442Gi        25.24Mi       -98.29%

                                           │ bench-old.txt │            bench-new.txt            │
                                           │   allocs/op   │  allocs/op   vs base                │
Jobs/non_admin_show_jobs-8                   20250.7k ± 1%   388.2k ± 1%  -98.08% (p=0.000 n=10)
Jobs/non_admin_crdb_internal.system_jobs-8   19385.3k ± 1%   329.4k ± 2%  -98.30% (p=0.000 n=10)
geomean                                        19.81M        357.6k       -98.20%
```

**Comment by DrewKimball** [comment]
TFYRs! And sorry for taking so long!

bors r+

**Comment by msbutler** [comment]
blathers backport 24.1

**Comment by DrewKimball** [comment]
The attempted bors ran into [this](https://github.com/cockroachdb/cockroach/issues/125212) flake.

bors retry

**Comment by mgartner** [comment]
>noting the great improvement for posterity:

Incredible! Great work @DrewKimball!

**Pull request merged**
