### PR TITLE
kvserver: surface MVCC range key stats

### PR DESCRIPTION
**Pull request by erikgrinaker**
**kvserver: use `MVCCStats.Total()` for data sizes**

Queues were computing the size of range data (for GC and timeout
purposes) by manually adding up `KeyBytes` and `ValBytes` from
`MVCCStats`. This patch changes the calculations to instead use
`MVCCStats.Total()`, which in particular also takes MVCC range keys into
account.

Release note: None
  
**kvserver: add MVCC range key metrics**

This patch adds the storage metrics `rangekeycount`, `rangekeybytes`,
`rangevalcount`, and `rangevalbytes` for MVCC range keys (i.e. MVCC
range tombstones). They are analogous to the corresponding point key
metrics (e.g. `keycount`).

Touches #85367.

Release note (ops change): Added the storage metrics `rangekeycount`,
`rangekeybytes`, `rangevalcount`, and `rangevalbytes` for MVCC range
keys (i.e. MVCC range tombstones). These are analogous to the
corresponding point key metrics (e.g. `keycount`).
  
**cli: show MVCC range key stats in `node status`**

This patch adds the columns `range_key_bytes` and `range_value_bytes` to
the output of `node status` when `--stats` or `--all` is specified.

Release note: None
  
**server: include MVCC range keys in size calculations**

This patch includes MVCC range keys in size calculations, specifically
the node diagnostic report and the MVCC garbage info in
`TableDetailsResponse`.

This also removes `intent_bytes` from these calculation, since this is
already included in `key_bytes` and `val_bytes`.

Release note: None

**sql: include MVCC range keys in `crdb_internal.ranges.range_size`**

Release note: None

### CODE REVIEW

**Review by koorosh — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85453)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, and @pavelkalinnikov)

___
*[`pkg/server/diagnostics/reporter.go` line 309 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85453#-N8YcsZ356R2kD30ht52:-N8YcsZ356R2kD30ht53:bh4a7jb) ([raw file](https://github.com/cockroachdb/cockroach/blob/09a65d5546ccbb774d9ae9a35b670a33e9379356/pkg/server/diagnostics/reporter.go#L309)):*
> ```Go
> 		info.Stores[i].RangeCount = int64(r.Metrics["replicas"])
> 		info.Node.RangeCount += info.Stores[i].RangeCount
> 		bytes := int64(r.Metrics["sysbytes"] + r.Metrics["valbytes"] + r.Metrics["keybytes"] +
> ```

@erikgrinaker , sorry if it's obvious question but I'm curious whether it's possible that `valbytes` and `rangevalbytes` metrics can reference to the same key-val in store? For instance, collecting `valbytes` metric for `a=5` key-value pair and then collecting `rangevalbytes` for `[a-c)=5` range. Will it count twice value of `a` key?

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85453)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @koorosh, and @pavelkalinnikov)

___
*[`pkg/server/diagnostics/reporter.go` line 309 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85453#-N8YcsZ356R2kD30ht52:-N8YhLSREZJ3CrdikvG-:bqd1clb) ([raw file](https://github.com/cockroachdb/cockroach/blob/09a65d5546ccbb774d9ae9a35b670a33e9379356/pkg/server/diagnostics/reporter.go#L309)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

@erikgrinaker , sorry if it's obvious question but I'm curious whether it's possible that `valbytes` and `rangevalbytes` metrics can reference to the same key-val in store? For instance, collecting `valbytes` metric for `a=5` key-value pair and then collecting `rangevalbytes` for `[a-c)=5` range. Will it count twice value of `a` key?
</blockquote></details>

Good question, that isn't obvious at all. Point keys and range keys exist separately, so it's possible to have `a=1` and also `[a-c)=789`.  The caller has to interpret their meaning relative to each other. That also means that their stats are separate, and should be added up.

If you're curious, there's a bunch of details in the tech note: https://github.com/cockroachdb/cockroach/blob/master/docs/tech-notes/mvcc-range-tombstones.md

**Review by koorosh — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85453#-:-N8YxFeZ2gP7LbevYRL9:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aliher1911 and @pavelkalinnikov)

**Comment by erikgrinaker** [comment]
TFTR!

bors r=koorosh

**Pull request merged**
