### PR TITLE
opt: add support for aggregate FILTER

### PR DESCRIPTION
**Pull request by justinj**
This commit introduces support for FILTERing individual aggregates in a
group by.

One unintuitive change is that if we have a COUNT(*) with a FILTER, we
need to synthesize an input for the aggregation to be over, because
otherwise we have no input to hang the AggFilter off of.

Thus, we convert
  COUNT(*) FILTER (WHERE foo)
to
  COUNT(true) FILTER (WHERE foo).

This isn't a problem for DISTINCT because COUNT(DISTINCT *) is not valid.

Release note (sql change): FILTER expressions are now supported by the
cost-based optimizer.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34077)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/execbuilder/testdata/aggregate, line 602 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34077#-LWRuD6g1NcCx9iT_UBO:-LWRuD6hExHvjVqaRDk7:bd260qi) ([raw file](https://github.com/cockroachdb/cockroach/blob/548e509e5c0de4c3052238da05eac90ca1a02381/pkg/sql/opt/exec/execbuilder/testdata/aggregate#L602)):*
> ```
> ----
> group           ·            ·
>  │              aggregate 0  count_rows() FILTER (WHERE k > 5)
> ```

How do we get `count_rows` here if we're building it as `count(true)`? I was expecting some special code in execbuilder that converts it back but can't see any.

**Review by justinj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34077)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/execbuilder/testdata/aggregate, line 602 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34077#-LWRuD6g1NcCx9iT_UBO:-LWS4DEO6vdkkxjqVInG:b-kif7tc) ([raw file](https://github.com/cockroachdb/cockroach/blob/548e509e5c0de4c3052238da05eac90ca1a02381/pkg/sql/opt/exec/execbuilder/testdata/aggregate#L602)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

How do we get `count_rows` here if we're building it as `count(true)`? I was expecting some special code in execbuilder that converts it back but can't see any.
</blockquote></details>

Ah, I forgot to regenerate these tests, fixed. Do you think that conversion in execbuilder is important?

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34077#-:-LWS6Q9l6uuroB2uauHN:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/execbuilder/testdata/aggregate, line 602 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34077#-LWRuD6g1NcCx9iT_UBO:-LWS69ed1fN31sm4EU2H:b-c4sc6k) ([raw file](https://github.com/cockroachdb/cockroach/blob/548e509e5c0de4c3052238da05eac90ca1a02381/pkg/sql/opt/exec/execbuilder/testdata/aggregate#L602)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Ah, I forgot to regenerate these tests, fixed. Do you think that conversion in execbuilder is important?
</blockquote></details>

Nah, this is not a very common case. Plus the main benefit would be to not render the `true` column and that would be hard to do in the execbuilder.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 9 of 10 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34077#-:-LWSwwRQ9ud0q94uidYh:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/execbuilder/testdata/aggregate, line 587 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34077#-LWSrh1R8YpsxNycYyqU:-LWSrh1S9iko92iYK86q:b-rteozy) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ac1539fb77a9d5c9e5e9cff9b817ede54dc7890/pkg/sql/opt/exec/execbuilder/testdata/aggregate#L587)):*
> ```
> ·               filter       v > 10          ·             ·
> 
> # TODO(radu): FILTER not yet supported.
> ```

[nit] remove this TODO
___
*[pkg/sql/opt/optbuilder/scope.go, line 956 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34077#-LWSuyB3Dq2XQjEguyEM:-LWSuyB487EJ2b1aCRX3:b-qh1fss) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ac1539fb77a9d5c9e5e9cff9b817ede54dc7890/pkg/sql/opt/optbuilder/scope.go#L956)):*
> ```Go
> 		}
> 
> 		s.builder.semaCtx.Properties.Restore(oldProps)
> ```

should we be concerned about not restoring props in case of the error above?
___
*[pkg/sql/opt/optbuilder/scope.go, line 999 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34077#-LWSvN4Z9JP7DpaHPUnR:-LWSvN4Z9JP7DpaHPUnS:b-dox4y) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ac1539fb77a9d5c9e5e9cff9b817ede54dc7890/pkg/sql/opt/optbuilder/scope.go#L999)):*
> ```Go
> 			if f.Filter != nil {
> 				// If we have a COUNT(*) with a FILTER, we need to synthesize an input for the aggregation
> 				// to be over, because otherwise we have no input to hang the AggFilter off of.
> ```

[nit] comments should be <= 80 columns
___
*[pkg/sql/opt/optbuilder/testdata/aggregate, line 2643 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34077#-LWSvvV22t0-7muwiAD8:-LWSvvV22t0-7muwiAD9:bj4bxf3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ac1539fb77a9d5c9e5e9cff9b817ede54dc7890/pkg/sql/opt/optbuilder/testdata/aggregate#L2643)):*
> ```
>       └── sum [type=decimal]
>            └── agg-filter [type=decimal]
>                 ├── variable: d [type=decimal]
> ```

It's a bit hard to distinguish the input from the filter... maybe it's worth adding labels for input/filter?

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34077)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 642 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34077#-LWT1qYV78HaZIwdYOls:-LWT1qYV78HaZIwdYOlt:b-hhuf6g) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ac1539fb77a9d5c9e5e9cff9b817ede54dc7890/pkg/sql/opt/exec/execbuilder/relational_builder.go#L642)):*
> ```Go
> 			child := item.Agg.Child(0)
> 
> 			if aggFilter, ok := child.(*memo.AggFilterExpr); ok {
> ```

Since it appears we're assuming there's just one `AggFilterExpr`, and it sits above any `AggDistinctExpr`, can you add some checking to the `Memo.checkExpr` function? We already have some checks there for the distinct case.

**Review by justinj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34077)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andy-kimball and @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 642 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34077#-LWT1qYV78HaZIwdYOls:-LWXopIi4OlSqZ17mpPC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ac1539fb77a9d5c9e5e9cff9b817ede54dc7890/pkg/sql/opt/exec/execbuilder/relational_builder.go#L642)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Since it appears we're assuming there's just one `AggFilterExpr`, and it sits above any `AggDistinctExpr`, can you add some checking to the `Memo.checkExpr` function? We already have some checks there for the distinct case.
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/testdata/aggregate, line 587 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34077#-LWSrh1R8YpsxNycYyqU:-LWXp6aS69pGj2hmFJTM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ac1539fb77a9d5c9e5e9cff9b817ede54dc7890/pkg/sql/opt/exec/execbuilder/testdata/aggregate#L587)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] remove this TODO
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/scope.go, line 956 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34077#-LWSuyB3Dq2XQjEguyEM:-LWXpDqM8ZWuZM096Rtn:bgdaamm) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ac1539fb77a9d5c9e5e9cff9b817ede54dc7890/pkg/sql/opt/optbuilder/scope.go#L956)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

should we be concerned about not restoring props in case of the error above?
</blockquote></details>

I wouldn't think so, since we bail if that happens, and throw everything away, right?
___
*[pkg/sql/opt/optbuilder/scope.go, line 999 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34077#-LWSvN4Z9JP7DpaHPUnR:-LWXrtMP9sFnYoODQLqG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ac1539fb77a9d5c9e5e9cff9b817ede54dc7890/pkg/sql/opt/optbuilder/scope.go#L999)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] comments should be <= 80 columns
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/testdata/aggregate, line 2643 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34077#-LWSvvV22t0-7muwiAD8:-LWXvjPz-3vy3bVPU3D7:bbkkln1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ac1539fb77a9d5c9e5e9cff9b817ede54dc7890/pkg/sql/opt/optbuilder/testdata/aggregate#L2643)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

It's a bit hard to distinguish the input from the filter... maybe it's worth adding labels for input/filter?
</blockquote></details>

Good idea—done.

**Review by rytaft — APPROVED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34077)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andy-kimball)

___
*[pkg/sql/opt/optbuilder/scope.go, line 956 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34077#-LWSuyB3Dq2XQjEguyEM:-LWbbLWYCZvXmprcJHVJ:b-ebawe8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ac1539fb77a9d5c9e5e9cff9b817ede54dc7890/pkg/sql/opt/optbuilder/scope.go#L956)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I wouldn't think so, since we bail if that happens, and throw everything away, right?
</blockquote></details>

Yea, I think you're right

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/optbuilder/scope.go, line 956 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34077#-LWSuyB3Dq2XQjEguyEM:-LWbcjzH0-PKHEPGzI1p:bijhf3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ac1539fb77a9d5c9e5e9cff9b817ede54dc7890/pkg/sql/opt/optbuilder/scope.go#L956)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Yea, I think you're right
</blockquote></details>

The semaCtx is passed externally, and it's probably being reused (https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/plan_opt.go#L232). I think we should restore.

**Comment by justinj** [comment]
Ok, fixed the restoring. TFTRs!

bors r+

**Pull request merged**
