### PR TITLE
rac2: add metric counter tracking tokens returned from disconnect

### LINKED ISSUE #131191: rac2: add metric for tracked token return due to state transition
All tracked flow tokens may be untracked and returned to the token counter if the replication stream disconnects, or the replica requires a snapshot.

Add a metric which covers these cases.

Jira issue: CRDB-42438

Epic CRDB-37515

### PR DESCRIPTION
**Pull request by kvoli**
When a replica enters `StateProbe` or has its send stream closed, all tracked token deductions are returned.

Add a new metric counter which is incremented by the amount of tokens returned due to streams disconnecting.

Four variations are added, pertaining to whether the tokens were deducted post-evaluation or prior to sending, and the token work class, regular or elastic. The full metric names are:

```
kvflowcontrol.tokens.eval.elastic.disconnected
kvflowcontrol.tokens.eval.regular.disconnected
kvflowcontrol.tokens.send.elastic.disconnected
kvflowcontrol.tokens.send.regular.disconnected
```

Resolves: #131191
Release note: None

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131194)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/metrics.go` line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131194#-O7ZOAQg3Ptf5xGLncI-:-O7ZOAQg3Ptf5xGLncI0:b-ljwm8w) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b975ce099d3f6ade640081ab375c2784fee1509/pkg/kv/kvserver/kvflowcontrol/rac2/metrics.go#L57)):*
> ```Go
> 	flowTokensDisconnectReturn = metric.Metadata{
> 		Name:        "kvflowcontrol.tokens.%s.%s.disconnected",
> 		Help:        "Flow %s tokens returned early by %s requests due disconnects, across all replication streams",
> ```

nit: due to disconnects ...

This is a subset of `flowTokensReturned`, yes? Worth noting in a code comment.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 917 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131194#-O7ZPjov0J5Lnyi1fxms:-O7ZPjov0J5Lnyi1fxmt:b995jfr) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b975ce099d3f6ade640081ab375c2784fee1509/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L917)):*
> ```Go
> 		}
> 	}
> 	rss.parent.evalTokenCounter.metrics.onDisconnectReturn(perWorkClass)
> ```

Is this reaching into the `tokenCounter.metrics` field because it is simpler than plumbing this information into `tokenCounter.Return` as a parameter? Seems less principled given everything else gets updated inside `tokenCounter`. 
Also, what about `sendTokenCounter`?

**Review by kvoli — COMMENTED** [review]
TYFTR, I've pushed changes addressing the PR comments. I've also extended one of the simulation tests to demonstrate the metric working. Should be good for another look @sumeerbhola.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131194#-:-O7_7Gm51RNjNrevcA3V:b-35qgyt)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/metrics.go` line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131194#-O7ZOAQg3Ptf5xGLncI-:-O7_6NyQ3uSZ9Iss1z4K:bmqreda) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b975ce099d3f6ade640081ab375c2784fee1509/pkg/kv/kvserver/kvflowcontrol/rac2/metrics.go#L57)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: due to disconnects ...

This is a subset of `flowTokensReturned`, yes? Worth noting in a code comment.
</blockquote></details>

Added a comment in the description and updated grammar.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 917 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131194#-O7ZPjov0J5Lnyi1fxms:-O7_6SVQD0VuZC0Hdndq:b-as9jfe) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b975ce099d3f6ade640081ab375c2784fee1509/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L917)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is this reaching into the `tokenCounter.metrics` field because it is simpler than plumbing this information into `tokenCounter.Return` as a parameter? Seems less principled given everything else gets updated inside `tokenCounter`. 
Also, what about `sendTokenCounter`?
</blockquote></details>

Fair enough, I did take some liberty here. I've moved this to stay within the token counter instead.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131194#-:-O7_V6BTBAtmPJF7dkEa:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/simulation/range_controller_stream_disconnection` line 51 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131194#-O7_Uy3CDpMkzTBS4GEX:-O7_Uy3CDpMkzTBS4GEY:bndtsc2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7674c1fcd5c4ccf6ea971eae242f87dda50e02f7/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/simulation/range_controller_stream_disconnection#L51)):*
> ```
> kvflowcontrol.eval_wait.elastic.requests.bypassed           unit=reqs/s rate=true
> kvflowcontrol.eval_wait.regular.requests.{admitted,waiting} unit=reqs/s rate=true
> kvflowcontrol.tokens.eval.regular.disconnected              unit=MiB
> ```

how about also plotting the disconnected send tokens.

**Review by kvoli — COMMENTED** [review]
TYFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131194#-:-O7a2M2GDH0u-ooXG0op:bzftgo7)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/simulation/range_controller_stream_disconnection` line 51 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131194#-O7_Uy3CDpMkzTBS4GEX:-O7a2MpQ-tVRUyd204QL:b4giqjw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7674c1fcd5c4ccf6ea971eae242f87dda50e02f7/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/simulation/range_controller_stream_disconnection#L51)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

how about also plotting the disconnected send tokens.
</blockquote></details>

Good idea, updated to include the send tokens graph.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131194#-:-O7a38ja6zvVAqktCSsy:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

**Comment by kvoli** [comment]
TYFTR!

bors r=sumeerbhola

**Pull request merged**
