### PR TITLE
server: support separate transactions on sql api

### PR DESCRIPTION
**Pull request by THardy98**
Part of: https://github.com/cockroachdb/cockroach/issues/102386

This change introduces a `separate_txns` field to the sql api endpoint.
This field allows callers to run provided statements in separate
transactions. Failures in separate transactions are scoped to their
respective transaction and do not interfere with the execution of
subsequent transactions. The exception to this case is if the max
response size is exceeded. If the response size is exceeded in an
earlier transaction, it will still exceed the limit in subsequent
transactions.  The response-level error using `separate_txns` is a
generic message: `separate transaction payload encountered transaction
error(s)`, indicating that an error has occurred in at least one of the
transactions.

We additionally add a `stop_on_error` field to allow callers to stop
execution of subsequent txns (i.e. in the case where `separate_txns` is
true).

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108447)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @THardy98)

___
*[`pkg/server/api_v2_sql.go` line 377 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108447#-NbR7GafDae0_yKrf3t5:-NbR7GafDae0_yKrf3t6:bre6pzl) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a6eb1a50a80319a4912b5ebbd9bb34abe24a983/pkg/server/api_v2_sql.go#L377)):*
> ```Go
> 	err = timeutil.RunWithTimeout(ctx, "run-sql-via-api", timeout, func(ctx context.Context) error {
> 		if !requestPayload.SeparateTxns {
> 			execRes, _, err := a.runSingleTxn(ctx, 0, 0, username, requestPayload, requestPayload.Statements, options)
> ```

I feel there is a lot of code duplication here.

Can you perhaps simplify the control flow a bit? Something like this:
https://github.com/knz/cockroach/commit/62099b2a446361b0ada673dc95d499fa416e5bae

**Review by j82w — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108447)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @THardy98)

___
*[`pkg/server/api_v2_sql.go` line 209 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108447#-NbUoJWl53zEsqnhfA24:-NbUoJWl53zEsqnhfA25:b2lu883) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a6eb1a50a80319a4912b5ebbd9bb34abe24a983/pkg/server/api_v2_sql.go#L209)):*
> ```Go
> 	Execute         bool        `json:"execute"`
> 	SeparateTxns    bool        `json:"separate_txns"`
> 	Statements      []statement `json:"statements"`
> ```

Would it be better to make an array of transactions and each transaction has an array of stmts? That way it's more flexible and matches the response with multiple txns and each has multiple stmts.

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108447)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @knz)

___
*[`pkg/server/api_v2_sql.go` line 209 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108447#-NbUoJWl53zEsqnhfA24:-NbUu-nh-2Cna6C07zvA:bno6ivx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a6eb1a50a80319a4912b5ebbd9bb34abe24a983/pkg/server/api_v2_sql.go#L209)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Would it be better to make an array of transactions and each transaction has an array of stmts? That way it's more flexible and matches the response with multiple txns and each has multiple stmts. 
</blockquote></details>

I agree, but I chose this approach because its additive, non-breaking and this functionality is currently blocking some other UI work. Changing the request/response format means changing the sql api UI-side and its corresponding usages.
___
*[`pkg/server/api_v2_sql.go` line 377 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108447#-NbR7GafDae0_yKrf3t5:-NbUtodlD_Ns3ywEiPHZ:bdsv0lz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a6eb1a50a80319a4912b5ebbd9bb34abe24a983/pkg/server/api_v2_sql.go#L377)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I feel there is a lot of code duplication here.

Can you perhaps simplify the control flow a bit? Something like this:
https://github.com/knz/cockroach/commit/62099b2a446361b0ada673dc95d499fa416e5bae
</blockquote></details>

Yes that's a much better idea. I've refactored to follow this instead, much smaller code diff.

**Review by knz — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108447)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @THardy98)

___
*[`pkg/server/api_v2_sql.go` line 208 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108447#-NbVTZQNAxA3JCBh_VKx:-NbVTZQODauWtDm8mIjR:b-lw88xe) ([raw file](https://github.com/cockroachdb/cockroach/blob/d116a388ab65e177abda7dc4a786f3ca44473655/pkg/server/api_v2_sql.go#L208)):*
> ```Go
> 		ApplicationName string `json:"application_name"`
> 		Execute         bool   `json:"execute"`
> 		SeparateTxns    bool   `json:"separate_txns"`
> ```

May I recommend you add another bool field `StopOnError` which decides whether or not to stop subsequent txns/stmts from executing when an error is encountered.

From experience, there are valid use cases for both.

**Comment by j82w** [comment]
*[`pkg/server/api_v2_sql.go` line 209 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108447#-NbUoJWl53zEsqnhfA24:-NbV5j268poki9vniRfC:bg8vds) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a6eb1a50a80319a4912b5ebbd9bb34abe24a983/pkg/server/api_v2_sql.go#L209)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

I agree, but I chose this approach because its additive, non-breaking and this functionality is currently blocking some other UI work. Changing the request/response format means changing the sql api UI-side and its corresponding usages.
</blockquote></details>

We could keep the current stmts and just add the txns property. Then in the db just treat the old stmts array as first txn.

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108447)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @knz)

___
*[`pkg/server/api_v2_sql.go` line 209 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108447#-NbUoJWl53zEsqnhfA24:-NbVY1jjBl-iEVeC6nJQ:b-upakrk) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a6eb1a50a80319a4912b5ebbd9bb34abe24a983/pkg/server/api_v2_sql.go#L209)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

We could keep the current stmts and just add the txns property. Then in the db just treat the old stmts array as first txn. 
</blockquote></details>

Yea that could work. I'm still a bit hesitant with this because we'd have to change the `txnResult` shape, or more safely, introduce a new field in `execResult` to hold txns that return multiple statement results, which weirdly would hold 2 fields for transaction results (one for single stmt, one for multi-stmt). WDYT? Is that fine?

**Comment by j82w** [comment]
*[`pkg/server/api_v2_sql.go` line 209 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108447#-NbUoJWl53zEsqnhfA24:-NbVc9ekCkQ1p2_jzQ6M:b-88hef8) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a6eb1a50a80319a4912b5ebbd9bb34abe24a983/pkg/server/api_v2_sql.go#L209)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

Yea that could work. I'm still a bit hesitant with this because we'd have to change the `txnResult` shape, or more safely, introduce a new field in `execResult` to hold txns that return multiple statement results, which weirdly would hold 2 fields for transaction results (one for single stmt, one for multi-stmt). WDYT? Is that fine?
</blockquote></details>

nvm, I thought `txnResults` already had support for multiple statements, but it's just poorly named. It should be labeled stmtResult.

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108447)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @knz)

___
*[`pkg/server/api_v2_sql.go` line 208 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108447#-NbVTZQNAxA3JCBh_VKx:-NbW6GwkAoBs-iqNj-Eu:bqmjwcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d116a388ab65e177abda7dc4a786f3ca44473655/pkg/server/api_v2_sql.go#L208)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

May I recommend you add another bool field `StopOnError` which decides whether or not to stop subsequent txns/stmts from executing when an error is encountered.

From experience, there are valid use cases for both.
</blockquote></details>

Added.

**Comment by j82w** [comment]
*[`pkg/server/api_v2_sql.go` line 400 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/108447#-NbW8yYh2JoOHFa5Izml:-NbW8yYh2JoOHFa5Izmm:bbflj09) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2e4448606b2d489b84866c327fe463aac6c6d2c/pkg/server/api_v2_sql.go#L400)):*
> ```Go
> 				// If StopOnError is specified, return the outerErr and terminate
> 				if requestPayload.StopOnError {
> 					return outerErr, true
> ```

Does the stmtErr need to be combined with the outerErr?

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108447)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @knz)

___
*[`pkg/server/api_v2_sql.go` line 400 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/108447#-NbW8yYh2JoOHFa5Izml:-NbWAmt34-L95YsUfdI5:bkl9idz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2e4448606b2d489b84866c327fe463aac6c6d2c/pkg/server/api_v2_sql.go#L400)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Does the stmtErr need to be combined with the outerErr?
</blockquote></details>

I decided for the `outerErr` to be a generic message when we're running separate txns. `stmtErr` in this case is captured only at the stmt level. My thinking is that separate txns = separate errors, no need to capture it again at the top-level response error. I initially thought about combining `stmtErr` into `outerErr` but thought with an unbounded number of stmts, it can become hard to read and a bit redundant.

**Comment by j82w** [comment]
*[`pkg/server/api_v2_sql.go` line 400 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/108447#-NbW8yYh2JoOHFa5Izml:-NbWCw5C5qcTdQyI3IK-:b38ljlv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2e4448606b2d489b84866c327fe463aac6c6d2c/pkg/server/api_v2_sql.go#L400)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

I decided for the `outerErr` to be a generic message when we're running separate txns. `stmtErr` in this case is captured only at the stmt level. My thinking is that separate txns = separate errors, no need to capture it again at the top-level response error. I initially thought about combining `stmtErr` into `outerErr` but thought with an unbounded number of stmts, it can become hard to read and a bit redundant. 
</blockquote></details>

Does the ui show and/or log the inner stmt error? My concern is it only check if the txn fails and then stops. It doesn't bother checking the inner errors.

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108447)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @knz)

___
*[`pkg/server/api_v2_sql.go` line 400 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/108447#-NbW8yYh2JoOHFa5Izml:-NbWEKff3SurqMXbUaud:b-8n9qrm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2e4448606b2d489b84866c327fe463aac6c6d2c/pkg/server/api_v2_sql.go#L400)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Does the ui show and/or log the inner stmt error? My concern is it only check if the txn fails and then stops. It doesn't bother checking the inner errors.
</blockquote></details>

That's correct. I think this is an easy UI side change though. We can add a small change when we format responses to also log stmt-level errors. I do this in a follow-up PR handling stmt-level errors on the db page.

**Comment by THardy98** [comment]
RFAL / any remaining feedback/thoughts?

**Review by knz — APPROVED** [review]
LGTM but you also need a review approval from your team.

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108447#-:-NbaGt4I7w0qIZ9CDW3w:bgx1atq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @THardy98)

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108447#-:-NboFhLhEoaQAXJcbsSV:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @j82w and @THardy98)

**Comment by THardy98** [comment]
TYFR

**Comment by knz** [comment]
bors r-

The CI failure indicates a real problem.

**Comment by knz** [comment]
image

**Comment by THardy98** [comment]
> You should filter out the `source` part of the JSON error output. The references to the source code change too often.

Done.

**Pull request merged**
