### PR TITLE
workload: add generic initial table validations and generator-specific consistency checks

### PR DESCRIPTION
**Pull request by danhhz**

### CODE REVIEW

**Comment by danhhz** [comment]
@jordanlewis I think @benesch said he's ooo for the rest of the week. Could you look at this, plz?

**Comment by benesch** [comment]
:lgtm: but I didn't look at the actual checks at all

---

Reviewed 1 of 1 files at r1, 4 of 4 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 5 of 5 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24088#-:-L89MKGaGq-PWa21WGoT:b-l5g8jz)*

**Comment by jordanlewis** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r2, 1 of 2 files at r3, 1 of 6 files at r6, 5 of 5 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/cmd/workload/fixtures.go, line 78 at r8](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24088#-L89euG9-y_KBqs_zYEA:-L89euG9-y_KBqs_zYEB:b77x3ou) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9cdd73b12992c6d77fffbe7555b1c62a9701fa8/pkg/cmd/workload/fixtures.go#L78)):*
> ```Go
> 
> var fixturesLoadRunChecks = fixturesLoadCmd.PersistentFlags().Bool(
> 	`checks`, true, `Run validity checks on the loaded fixture`)
> ```

This should probably be set to false. At least for tpcc, running the checks takes over 1 hour on a large dataset.

---

*[pkg/workload/validate.go, line 84 at r8](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24088#-L89f9Eo9ML14nFmq-fM:-L89f9Eo9ML14nFmq-fN:b-yylwdf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9cdd73b12992c6d77fffbe7555b1c62a9701fa8/pkg/workload/validate.go#L84)):*
> ```Go
> 		table.Name, table.Name, rowIdx)
> 	if err := db.QueryRow(query).Scan(actual...); err != nil {
> 		return errors.Wrapf(err, `feching table %s row %d [%s]`, table.Name, rowIdx, query)
> ```

fetching*

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24088#-:-L89fKj70Q3w0oabDVSz:bnfp4nl)*

**Comment by danhhz** [comment]
I had to add a small tpcc special-case hack to the test to get it to pass in a reasonable time. TFTRs!

---

Review status: 2 of 11 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/cmd/workload/fixtures.go, line 78 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/24088#-L89euG9-y_KBqs_zYEA:-L8DN90b9wX2Uoaw0ZxQ:b-bau4co) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9cdd73b12992c6d77fffbe7555b1c62a9701fa8/pkg/cmd/workload/fixtures.go#L78)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This should probably be set to false. At least for tpcc, running the checks takes over 1 hour on a large dataset.
</blockquote></details>

gotcha. that probably defeats the purpose but i'll make it false for now and figure something out after do some testing

---

*[pkg/workload/validate.go, line 84 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/24088#-L89f9Eo9ML14nFmq-fM:-L8DNOnX8Zm4Xqy0boFt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9cdd73b12992c6d77fffbe7555b1c62a9701fa8/pkg/workload/validate.go#L84)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

fetching*
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24088#-:-L8DOrsA-9nrmCbLNtMG:b-pjppnj)*

**Pull request merged**
