### PR TITLE
build: make testlogic caches its test binary

### PR DESCRIPTION
**Pull request by jordanlewis**
Previously, invoking `make testlogic` multiple times in a row with
intervening changes only to files in `pkg/sql/testdata` would take
multiple seconds as Go needlessly recompiles the test binary each time.

Now, `make testlogic` saves the test binary to `bin/sql.test` and reuses
it if no `.go` files have been modified since it was created. This greatly
improves workflows when iterating on files in `pkg/sql/testdata` since
runs of e.g. `make testlogic FILES=tuple` take less than a second each
when the binary is cached.

### CODE REVIEW

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[Makefile, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14912#-Khd5fWqyT23ra4Zq1zH:-Khd5fWqyT23ra4Zq1zI:bu7izqo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a828e00b32e0568c4f3ccfc198fda084685c5418/Makefile#L137)):*
> ```Makefile
> bin/sql.test: PKG := ./pkg/sql
> bin/sql.test: override GOFLAGS += -c -o bin/sql.test
> bin/sql.test: main.go $(shell find pkg -type f -name "*.go")
> ```

is this `go list -f '{{join .GoFiles "\n"}}' ./pkg/...`? You might also want to depend on CGoFiles. IOW, you may be reinventing the Go build system here.

I'll let @benesch sign off on this one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14912)*

**Comment by benesch** [comment]
Ahh, this is amazing. `sql.test` takes SO LONG to link.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[Makefile, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14912#-Khd5j3ldddxLPFdvwQ7:-Khd5j3ldddxLPFdvwQ8:b1h29m2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a828e00b32e0568c4f3ccfc198fda084685c5418/Makefile#L137)):*
> ```Makefile
> bin/sql.test: PKG := ./pkg/sql
> bin/sql.test: override GOFLAGS += -c -o bin/sql.test
> bin/sql.test: main.go $(shell find pkg -type f -name "*.go")
> ```

Would you mind to extract this into a variable called `GO_SOURCES`? It'll make it marginally more obvious if someone adds a `.go` file outside of `PKG`.

---

*[Makefile, line 138 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14912#-Khd5xRhhQeVqt2ydzzR:-Khd5xRhhQeVqt2ydzzS:b-l2jkwb) ([raw file](https://github.com/cockroachdb/cockroach/blob/a828e00b32e0568c4f3ccfc198fda084685c5418/Makefile#L138)):*
> ```Makefile
> bin/sql.test: override GOFLAGS += -c -o bin/sql.test
> bin/sql.test: main.go $(shell find pkg -type f -name "*.go")
> 	$(GO) test $(GOFLAGS) -tags '$(TAGS)' -ldflags '$(LINKFLAGS)' $(PKG)
> ```

You could just inline the variables to save yourself some trouble.

```
$(GO) test $(GOFLAGS) -c -o bin/sql.test -tags '$(TAGS)' -ldflags '$(LINKFLAGS)' ./pkg/sql
```

---

*[Makefile, line 155 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14912#-Khd6LiUesusVn0o_-a9:-Khd6LiUesusVn0o_-aA:b2knnj2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a828e00b32e0568c4f3ccfc198fda084685c5418/Makefile#L155)):*
> ```Makefile
> testlogic:
> 	cd pkg/sql && ../../bin/sql.test -test.run "$(TESTS)" -test.timeout $(TESTTIMEOUT) $(TESTFLAGS)
> ```

I'd inline `$(TESTFLAGS)` here too. I guess `TESTS` is long enough that you might as well leave it. 

```bash
cd pkg/sql && ../../bin/sql.test -test.run "$(TESTS)" -test.timeout $(TESTTIMEOUT) -test.v $(if $(FILES),-show-sql) $(TESTFLAGS)
```

Even if you don't inline $(TESTFLAGS), use `override TESTFLAGS += foo` so that the user can specify additional test flags on the command line. (We're not totally consistent about this elsewhere.)

Also, this'll be on the PATH, so I think you can just run `sql.test` instead of `../../bin/sql.test` :D

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14912#-:-Khd7j6QdKMGs1XUbILp:btol962)*

**Comment by tamird** [comment]
Also just to put it out there: please consider filing an issue upstream
about caching test binaries in the normal go toolchain.

**Comment by benesch** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[Makefile, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14912#-Khd5fWqyT23ra4Zq1zH:-Khd84ndgTUvRbRnjKnv:b-f13ct8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a828e00b32e0568c4f3ccfc198fda084685c5418/Makefile#L137)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

is this `go list -f '{{join .GoFiles "\n"}}' ./pkg/...`? You might also want to depend on CGoFiles. IOW, you may be reinventing the Go build system here.

I'll let @benesch sign off on this one.
</blockquote></details>

@tamird that doesn't print the dir to the file unfortunately. I assume you can write a more complicated template to do so, in which case I'm :thumbsup: on this suggestion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14912)*

**Comment by jordanlewis** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[Makefile, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14912#-Khd5fWqyT23ra4Zq1zH:-Khd8YnvTB6QUV5DyyLq:b-mpqeth) ([raw file](https://github.com/cockroachdb/cockroach/blob/a828e00b32e0568c4f3ccfc198fda084685c5418/Makefile#L137)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

@tamird that doesn't print the dir to the file unfortunately. I assume you can write a more complicated template to do so, in which case I'm :thumbsup: on this suggestion.
</blockquote></details>

It might be the same, except it's like 5x faster. I agree this is kind of reinventing the wheel, but it's better than waiting like 6 seconds every time you run this. Also, the kinds of changes where you need to iterate with `testlogic` are not the kinds of changes where you're changing CGoFiles so I'm feeling like this is sufficient.

---

*[Makefile, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14912#-Khd5j3ldddxLPFdvwQ7:-Khd8tp-eaVeoJkgaC-x:btn26m7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a828e00b32e0568c4f3ccfc198fda084685c5418/Makefile#L137)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Would you mind to extract this into a variable called `GO_SOURCES`? It'll make it marginally more obvious if someone adds a `.go` file outside of `PKG`.
</blockquote></details>

Well... I'd rather not people start using this as it *is* a hack as Tamir points out. Also, this way it doesn't have to run the `find` on every `make` invocation.

---

*[Makefile, line 138 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14912#-Khd5xRhhQeVqt2ydzzR:-Khd8wcP3bTPeAWi7unG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a828e00b32e0568c4f3ccfc198fda084685c5418/Makefile#L138)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

You could just inline the variables to save yourself some trouble.

```
$(GO) test $(GOFLAGS) -c -o bin/sql.test -tags '$(TAGS)' -ldflags '$(LINKFLAGS)' ./pkg/sql
```
</blockquote></details>

Done.

---

*[Makefile, line 155 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14912#-Khd6LiUesusVn0o_-a9:-Khd9KwOmIBQ2upGVjSK:b-837glw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a828e00b32e0568c4f3ccfc198fda084685c5418/Makefile#L155)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I'd inline `$(TESTFLAGS)` here too. I guess `TESTS` is long enough that you might as well leave it. 

```bash
cd pkg/sql && ../../bin/sql.test -test.run "$(TESTS)" -test.timeout $(TESTTIMEOUT) -test.v $(if $(FILES),-show-sql) $(TESTFLAGS)
```

Even if you don't inline $(TESTFLAGS), use `override TESTFLAGS += foo` so that the user can specify additional test flags on the command line. (We're not totally consistent about this elsewhere.)

Also, this'll be on the PATH, so I think you can just run `sql.test` instead of `../../bin/sql.test` :D
</blockquote></details>

I prefer the current solution - I've found myself wanting to override but not append to TESTFLAGS from the command line.

Fixed the ../../ thing though, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14912)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[Makefile, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14912#-Khd5fWqyT23ra4Zq1zH:-KhdCIKmwH8z4q6Qc8ou:buxgmv9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a828e00b32e0568c4f3ccfc198fda084685c5418/Makefile#L137)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

It might be the same, except it's like 5x faster. I agree this is kind of reinventing the wheel, but it's better than waiting like 6 seconds every time you run this. Also, the kinds of changes where you need to iterate with `testlogic` are not the kinds of changes where you're changing CGoFiles so I'm feeling like this is sufficient.
</blockquote></details>

Whoa, really? Alright.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14912)*

**Comment by jordanlewis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[Makefile, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14912#-Khd5fWqyT23ra4Zq1zH:-KhdCd-_G6D-FMqukl1q:bz8icfv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a828e00b32e0568c4f3ccfc198fda084685c5418/Makefile#L137)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Whoa, really? Alright.
</blockquote></details>

`go list -f '{{join .GoFiles "\n"}}' ./pkg/...  0.76s user 0.82s system 82% cpu 1.914 total`
`find ./pkg -type f -name "*.go"  0.03s user 0.51s system 98% cpu 0.555 total`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14912)*

**Comment by jordanlewis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[Makefile, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14912#-Khd5fWqyT23ra4Zq1zH:-KhdDQV-4QTK4DCzIaYx:bdnygaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a828e00b32e0568c4f3ccfc198fda084685c5418/Makefile#L137)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

`go list -f '{{join .GoFiles "\n"}}' ./pkg/...  0.76s user 0.82s system 82% cpu 1.914 total`
`find ./pkg -type f -name "*.go"  0.03s user 0.51s system 98% cpu 0.555 total`

</blockquote></details>

The "6 seconds" comment I made referred to the length of time it takes to link the test binary btw, not the `go list` which is only a few times slower than the `find`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14912)*

**Comment by benesch** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[Makefile, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14912#-Khd5j3ldddxLPFdvwQ7:-KhdC4Pcua-jCGkOn3DG:b8tg36p) ([raw file](https://github.com/cockroachdb/cockroach/blob/a828e00b32e0568c4f3ccfc198fda084685c5418/Makefile#L137)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Well... I'd rather not people start using this as it *is* a hack as Tamir points out. Also, this way it doesn't have to run the `find` on every `make` invocation.
</blockquote></details>

You'd *think* so, right? Unfortunately prerequisites are evaluated on every invocation of Make. There's no way around this; Make needs a complete dependency graph. Just FYI.

---

*[Makefile, line 138 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14912#-Khd5xRhhQeVqt2ydzzR:-KhdDNgqp2Z-iD694A56:b-lnqr8p) ([raw file](https://github.com/cockroachdb/cockroach/blob/a828e00b32e0568c4f3ccfc198fda084685c5418/Makefile#L138)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can you include $(GOFLAGS) here for consistency with the other test commands?

---

*[Makefile, line 155 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14912#-Khd6LiUesusVn0o_-a9:-KhdD6YepAavov9VWZp8:bk4g0cg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a828e00b32e0568c4f3ccfc198fda084685c5418/Makefile#L155)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I prefer the current solution - I've found myself wanting to override but not append to TESTFLAGS from the command line.

Fixed the ../../ thing though, thanks!
</blockquote></details>

Hmk, fair enough. With any other toolchain you'd have `--no-verbose` in addition to `--verbose`, so `--verbose $(TESTFLAGS)` would allow you do undo the prior `--verbose`. Not so with Go. Ugh.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14912)*

**Comment by jordanlewis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[Makefile, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14912#-Khd5j3ldddxLPFdvwQ7:-KhdDzALsUDBDY9Kkwct:b-ihhjm9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a828e00b32e0568c4f3ccfc198fda084685c5418/Makefile#L137)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

You'd *think* so, right? Unfortunately prerequisites are evaluated on every invocation of Make. There's no way around this; Make needs a complete dependency graph. Just FYI.
</blockquote></details>

Ugh :( Well, I'll keep to my first justification then. I don't want a variable called `GO_SOURCES` around to confuse people!

---

*[Makefile, line 138 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14912#-Khd5xRhhQeVqt2ydzzR:-KhdEK9jtbQNx9iQVdbR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a828e00b32e0568c4f3ccfc198fda084685c5418/Makefile#L138)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Can you include $(GOFLAGS) here for consistency with the other test commands?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14912)*

**Comment by benesch** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[Makefile, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14912#-Khd5j3ldddxLPFdvwQ7:-KhdrikAwBnzfuTxctGM:b-bk5ipd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a828e00b32e0568c4f3ccfc198fda084685c5418/Makefile#L137)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Ugh :( Well, I'll keep to my first justification then. I don't want a variable called `GO_SOURCES` around to confuse people!
</blockquote></details>

Works for me!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14912#-:-KhdrhZx4DU-LXQiDB02:bnfp4nl)*

**Comment by benesch** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14912)*

**Comment by dt** [comment]
Looks like this might have added ~7s to `make` startup (when run in the builder)?
```
$ time ./build/builder.sh make bin.docker_amd64/.bootstrap
GOPATH set to /go
make: Nothing to be done for 'bin.docker_amd64/.bootstrap'.

real	0m15.143s
user	0m0.033s
sys	0m0.024s

$ time ./build/builder.sh make bin.docker_amd64/.bootstrap
GOPATH set to /go
make: Nothing to be done for 'bin.docker_amd64/.bootstrap'.

real	0m8.829s
user	0m0.034s
sys	0m0.024s

$ time ./build/builder.sh make bin.docker_amd64/.bootstrap
GOPATH set to /go
make: Nothing to be done for 'bin.docker_amd64/.bootstrap'.

real	0m9.218s
user	0m0.033s
sys	0m0.022s

$ g revert 9d2a7e4e3
[master a91475b49] Revert "build: make testlogic caches its test binary"
 1 file changed, 6 insertions(+), 10 deletions(-)

$ time ./build/builder.sh make bin.docker_amd64/.bootstrap
GOPATH set to /go
make: Nothing to be done for 'bin.docker_amd64/.bootstrap'.

real	0m1.899s
user	0m0.034s
sys	0m0.025s

$ time ./build/builder.sh make bin.docker_amd64/.bootstrap
GOPATH set to /go
make: Nothing to be done for 'bin.docker_amd64/.bootstrap'.

real	0m1.845s
user	0m0.033s
sys	0m0.024s

$ time ./build/builder.sh make bin.docker_amd64/.bootstrap
GOPATH set to /go
make: Nothing to be done for 'bin.docker_amd64/.bootstrap'.

real	0m1.840s
user	0m0.033s
sys	0m0.023s
```

**Comment by benesch** [comment]
Agh, that does seem possible, considering `find` will read the entire
directory tree and Docker for Mac has unusably slow shared folders.

**Comment by dt** [comment]
FWIW, still seems like a win, but serves as yet another nail in the coffin of it being tenable to tell people to "just use the builder".

**Comment by jordanlewis** [comment]
Ugh. I'd hate to see this niche feature slow every make invocation down. Maybe we can fix this by moving it into a different Makefile.

**Comment by dt** [comment]
every make invocation *in docker on OSX* just to clarify -- running on OS X natively, `find` takes no appreciable time at all.

**Comment by knz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14912#-:-Khfb-b_r4vtEQJZiwly:bnfp4nl)*

**Comment by benesch** [comment]
What's really interesting is that

```
build/builder.sh find pkg -name '*.go'
```

produces all the output in the first ~1s... then proceeds to hang for about five seconds doing nothing discernible.

**Comment by tamird** [comment]
Run it under strace!

**Comment by benesch** [comment]
Just did! :)

Is there an easy way to get `strace` in the builder image? I commented out the `-u` flag to `docker run` in builder.sh and `apt-get install`ed it, but that's rather clunky.

**Comment by tamird** [comment]
Nope, that's the only way I know.

**Comment by benesch** [comment]
I think #14936 fixes the perf regression.

**Pull request merged**
