### PR TITLE
sql: add test for builtin that belongs to information_schema

### PR DESCRIPTION
**Pull request by rafiss**
Epic: None

This tests the change in 3f50d81

Release note: None

### CODE REVIEW

**Review by ZhouXing19 — APPROVED** [review]
Seems that it has been fixed by https://github.com/cockroachdb/cockroach/pull/96562/commits/3f50d81d062371d13c5cb56f9daeac6f31ede7d9 but we can still add the test for `logic_test/pg_catalog`

**Comment by rafiss** [comment]
tftr! i didn't see that commit go in earlier

bors r+

**Pull request merged**
