### PR TITLE
acceptanceccl: add 2tb backup test

### PR DESCRIPTION
**Pull request by madelynnblue**
Refactors the terraform join flags a bit since this test already has
store data, and we have a bug that requires the join flag on these
nodes to be all nodes. We can't use this for other tests, though,
because that will prevent the init step from happening.

### CODE REVIEW

**Comment by mjibson** [comment]
@cuongdo can you review just the terraform changes?

**Comment by danhhz** [comment]
ccl stuff lgtm

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/acceptanceccl/backup_test.go, line 64 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15182#-Ki6wyYAcwm6tRlp-wpE:-Ki6wyYAcwm6tRlp-wpF:b-9k66jn) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9486c1121c55ad020123af4de07b547e0392489/pkg/ccl/acceptanceccl/backup_test.go#L64)):*
> ```Go
> 	// node will have the previous node as its join flag. If true, then all
> 	// nodes will have all nodes in their join flags.
> 	joinAll bool
> ```

something like "skipClusterInit" would make it more obvious when you'd want to set this to true

---

*[pkg/ccl/acceptanceccl/backup_test.go, line 307 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15182#-Ki73EDGJen2eZAzu6x3:-Ki73EDGJen2eZAzu6x4:b-tymuvg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9486c1121c55ad020123af4de07b547e0392489/pkg/ccl/acceptanceccl/backup_test.go#L307)):*
> ```Go
> 	}
> 	b.SetBytes(dataSize)
> 	log.Infof(ctx, "backed up %s", humanizeutil.IBytes(dataSize))
> ```

may as well throw an empty incremental backup in here too. each one as a sub benchmark?

I'm also okay leaving this for @benesch to do when he tests the TimeBoundIterator

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15182#-:-Ki73cXgHepZV96ckZK6:bpfat2x)*

**Comment by mjibson** [comment]
@cuongdo can you look at the terraform changes?

**Comment by cuongdo** [comment]
Reviewed 3 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/acceptance/terraform/azure/main.tf, line 185 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15182#-KjdNBZ61rWGgwLJKD2e:-KjdNBZ61rWGgwLJKD2f:b-x7il3b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9486c1121c55ad020123af4de07b547e0392489/pkg/acceptance/terraform/azure/main.tf#L185)):*
> ```HCL
>     # shifted by one (first element is empty), then take the value at index "instance.index".
>     # If join_all is true, --join is instead all nodes.
>     join_address = "${var.join_all == "true" ? join(",", google_compute_instance.cockroach.*.network_interface.0.access_config.0.assigned_nat_ip) : element(concat(split(",", ""), google_compute_instance.cockroach.*.network_interface.0.access_config.0.assigned_nat_ip), count.index == 0 ? 0 : 1)}"
> ```

Why is this file (`azure/main.tf`) referencing `google_compute_instance.*`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15182)*

**Comment by mjibson** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/acceptance/terraform/azure/main.tf, line 185 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15182#-KjdNBZ61rWGgwLJKD2e:-KjdZxcN1nVJf9oKlkXS:b-ku24xn) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9486c1121c55ad020123af4de07b547e0392489/pkg/acceptance/terraform/azure/main.tf#L185)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

Why is this file (`azure/main.tf`) referencing `google_compute_instance.*`?
</blockquote></details>

Copy paste error :(. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15182)*

**Comment by cuongdo** [comment]
LGTM for Terraform

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15182#-:-KjhbV30qyFdpAeEfA-q:bcmb112)*

**Comment by mjibson** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/ccl/acceptanceccl/backup_test.go, line 64 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15182#-Ki6wyYAcwm6tRlp-wpE:-KjiGKupHaOU-gPS1A66:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9486c1121c55ad020123af4de07b547e0392489/pkg/ccl/acceptanceccl/backup_test.go#L64)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

something like "skipClusterInit" would make it more obvious when you'd want to set this to true
</blockquote></details>

Done.

---

*[pkg/ccl/acceptanceccl/backup_test.go, line 307 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15182#-Ki73EDGJen2eZAzu6x3:-KjiGNKxS2952ZlmAgoh:bm48fv2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9486c1121c55ad020123af4de07b547e0392489/pkg/ccl/acceptanceccl/backup_test.go#L307)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

may as well throw an empty incremental backup in here too. each one as a sub benchmark?

I'm also okay leaving this for @benesch to do when he tests the TimeBoundIterator
</blockquote></details>

I'm leaving this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15182)*

**Comment by mjibson** [comment]
For reference, the bug listed in the commit message is #13027.

**Pull request merged**
