### PR TITLE
[WIP]: encryption at rest for Pebble. No tests and no integration cod…

### PR DESCRIPTION
**Pull request by sumeerbhola**
…e yet.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
Just sending to get some initial feedback. I plan to split this up for proper review.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41526#-:-LqsV5hd4Oo8ltdDniWl:bfl3nqo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @petermattis)

**Review by sumeerbhola — COMMENTED** [review]
The place to start reading is the comment in encrypted_fs.go.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41526#-:-LqsVJIO3y3Qf4G1A6wI:b-3xxwld)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @petermattis)

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41526)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @petermattis)

___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41526#-LqsVdyEAH9pcEuHKCgr:-LqsVdyF7F-oqByBRbEh:b-vi0341) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1f79d49cbeafaf111dc1bf6847caca229d9c3b/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L96)):*
> ```Go
> }
> 
> // TODO: should I bother with errorFile or just return nil?
> ```

I am assuming nil would be fine, assuming that callers should not be calling close() on a fs.File returned with an error.
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 208 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41526#-LqsW3K_5BS34VN5Y5yM:-LqsW3K_5BS34VN5Y5yN:b6h6win) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1f79d49cbeafaf111dc1bf6847caca229d9c3b/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L208)):*
> ```Go
> // key rotation settings and how that compares to WAL file recycling). If we change the
> // key and use the same underlying file it does not work due to the possibility of zero
> // readable entries (there is a TODO(ajkr) in env_encryption.cc about this).
> ```

I want to confirm my understanding here.
___
*[pkg/ccl/storageccl/engineccl/key_manager.go, line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41526#-LqsWBs84SFkBhJsWbVp:-LqsWBs84SFkBhJsWbVq:b-ivzbbs) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1f79d49cbeafaf111dc1bf6847caca229d9c3b/pkg/ccl/storageccl/engineccl/key_manager.go#L146)):*
> ```Go
> 	_, err := m.fs.Stat(m.registryFilename)
> 	if err == os.ErrNotExist {
> 		// TODO: can we rely on ErrNotExist being the only not-existence error?
> ```

errors as values, with no standard error codes, is somewhat confusing to me wrt what to expect.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41526)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @petermattis)

___
*[pkg/ccl/storageccl/engineccl/key_manager.go, line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41526#-LqsXdX-ACojLPrxd28_:-LqsXdX-ACojLPrxd28a:bqkg5qr) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1f79d49cbeafaf111dc1bf6847caca229d9c3b/pkg/ccl/storageccl/engineccl/key_manager.go#L10)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/storage/engine"
> 	"github.com/cockroachdb/pebble/vfs"
> 	"github.com/gogo/protobuf/proto"
> ```

hmm, wonder why goland pulled in this instead of `"github.com/golang/protobuf/proto"`

**Review by petermattis — COMMENTED** [review]
The high-level structure matches what I know of the C++ version of this code. And the comment in `encrypted_fs.go` makes sense. I didn't look terribly closely at the implementation. Will definitely want to break this into multiple PRs, building it from the bottom up and testing and benchmarking as you go. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41526#-:-LqsYCiF8GvucbV9UzVZ:b-849kkt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/file_registry.go, line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41526#-LqsXjwo84LeyT3jWtx7:-LqsXjwp7eTy5H9TT9aN:b-ojo337) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1f79d49cbeafaf111dc1bf6847caca229d9c3b/pkg/storage/engine/file_registry.go#L17)):*
> ```Go
> //
> // FileRegistry keeps track of files for the data-FS and store-FS.
> type FileRegistry struct {
> ```

Is there a reason `FileRegistry` is defined here and not in `ccl/storageccl/engineccl`? I believe there is a similar separation in `libroach`, but I'm not sure why it exists there either. Will this ever get used if we aren't also using `EncryptedFS`?

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41526)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @petermattis)

___
*[pkg/storage/engine/file_registry.go, line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41526#-LqsXjwo84LeyT3jWtx7:-LqvagPQ4sZ4mxccXs7D:bn1inuy) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1f79d49cbeafaf111dc1bf6847caca229d9c3b/pkg/storage/engine/file_registry.go#L17)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is there a reason `FileRegistry` is defined here and not in `ccl/storageccl/engineccl`? I believe there is a similar separation in `libroach`, but I'm not sure why it exists there either. Will this ever get used if we aren't also using `EncryptedFS`?
</blockquote></details>

- `db.cc<libroach>` (not `db.cc<ccl>`) always creates a FileRegistry since it minimally wants to check that there is no registry file if the file registry is not enabled, and it used the FileRegistry object to perform that check. We are going to lose information if we had a registry file before and now the registry is disabled. In this case the FileRegistry will not create a file. I've not yet added this check method since it can wait until the integration step.
- if `DBOpts.use_file_registry` is set to true the created `FileRegistry` is loaded and gets passed to the `EnvManager` where it is available to the encrypted environments.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41526)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @sumeerbhola)

___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41526#-LqsVdyEAH9pcEuHKCgr:-Lqw-tit05nEYonEPf5C:bjzc21e) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1f79d49cbeafaf111dc1bf6847caca229d9c3b/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L96)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I am assuming nil would be fine, assuming that callers should not be calling close() on a fs.File returned with an error.
</blockquote></details>

Yep, no need for this. You can just return `nil` from the `EncryptedFS` methods for the file return value if an error is being returned.
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 208 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41526#-LqsW3K_5BS34VN5Y5yM:-Lqw02uR-uFDnu7XeN91:b-18lpx6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1f79d49cbeafaf111dc1bf6847caca229d9c3b/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L208)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I want to confirm my understanding here.
</blockquote></details>

Yes, this is my understanding. I can see providing an "atomic create" method which does something similar to `SafeWriteToFile`.

Alternately, you could inspect the names involved here. Somewhat uglier, but the names are stable and it would avoid changing the `vfs.FS` API.
___
*[pkg/ccl/storageccl/engineccl/key_manager.go, line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41526#-LqsXdX-ACojLPrxd28_:-Lqw0SlH8QFYMECn41Kf:bpxaqkl) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1f79d49cbeafaf111dc1bf6847caca229d9c3b/pkg/ccl/storageccl/engineccl/key_manager.go#L10)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

hmm, wonder why goland pulled in this instead of `"github.com/golang/protobuf/proto"`
</blockquote></details>

`gogo/protobuf/proto` is the protocol buffer library we use in CockroachDB.
___
*[pkg/ccl/storageccl/engineccl/key_manager.go, line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41526#-LqsWBs84SFkBhJsWbVp:-Lqw0Z_QE9fKQ71BvCCL:b-3dxqze) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1f79d49cbeafaf111dc1bf6847caca229d9c3b/pkg/ccl/storageccl/engineccl/key_manager.go#L146)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

errors as values, with no standard error codes, is somewhat confusing to me wrt what to expect. 
</blockquote></details>

This changed in go1.13: https://golang.org/doc/go1.13#error_wrapping (but we can't use that yet). Note that you should probably use `os.IsNotExist(err)` rather than comparing values
___
*[pkg/storage/engine/file_registry.go, line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41526#-LqsXjwo84LeyT3jWtx7:-Lqw1-iO8rYikOJHjCji:bmdn7rw) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1f79d49cbeafaf111dc1bf6847caca229d9c3b/pkg/storage/engine/file_registry.go#L17)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

- `db.cc<libroach>` (not `db.cc<ccl>`) always creates a FileRegistry since it minimally wants to check that there is no registry file if the file registry is not enabled, and it used the FileRegistry object to perform that check. We are going to lose information if we had a registry file before and now the registry is disabled. In this case the FileRegistry will not create a file. I've not yet added this check method since it can wait until the integration step.
- if `DBOpts.use_file_registry` is set to true the created `FileRegistry` is loaded and gets passed to the `EnvManager` where it is available to the encrypted environments.
</blockquote></details>

Ack. Thanks for the explanation.

**Review by sumeerbhola — COMMENTED** [review]
The tests are done. 
But I've screwed up something in rebase so it has pulled in a lot of other changes.
Also, I'm assuming even without that screw up you would want this split into multiple PRs. I can send out file_registry.go first. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41526#-:-Lriq-2qCkGyRY1852b1:b-uu5bp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @sumeerbhola)

___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41526#-LqsVdyEAH9pcEuHKCgr:-Lr9nb8V8sM9tKbUrHiT:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1f79d49cbeafaf111dc1bf6847caca229d9c3b/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L96)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Yep, no need for this. You can just return `nil` from the `EncryptedFS` methods for the file return value if an error is being returned.
</blockquote></details>

done
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 208 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41526#-LqsW3K_5BS34VN5Y5yM:-Lr9n_GY5oDbZciLAosz:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1f79d49cbeafaf111dc1bf6847caca229d9c3b/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L208)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Yes, this is my understanding. I can see providing an "atomic create" method which does something similar to `SafeWriteToFile`.

Alternately, you could inspect the names involved here. Somewhat uglier, but the names are stable and it would avoid changing the `vfs.FS` API.
</blockquote></details>

done
___
*[pkg/ccl/storageccl/engineccl/key_manager.go, line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41526#-LqsXdX-ACojLPrxd28_:-Lr9nTq91hmVbIIGWac9:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1f79d49cbeafaf111dc1bf6847caca229d9c3b/pkg/ccl/storageccl/engineccl/key_manager.go#L10)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`gogo/protobuf/proto` is the protocol buffer library we use in CockroachDB.
</blockquote></details>

done
___
*[pkg/ccl/storageccl/engineccl/key_manager.go, line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41526#-LqsWBs84SFkBhJsWbVp:-Lr9nWNlA8HmFP-8h5nE:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1f79d49cbeafaf111dc1bf6847caca229d9c3b/pkg/ccl/storageccl/engineccl/key_manager.go#L146)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This changed in go1.13: https://golang.org/doc/go1.13#error_wrapping (but we can't use that yet). Note that you should probably use `os.IsNotExist(err)` rather than comparing values
</blockquote></details>

done

**Review by petermattis — COMMENTED** [review]
Yeah, something is wonky with the rebase. Splitting this PR into multiple PRs is definitely nice to the reviewer. Let me know when you want me to take another look. Or feel free to close this PR and open new ones.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41526#-:-LrnZB-VEh76VjUOkU7H:b-ncqxwy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @sumeerbhola)

**Comment by sumeerbhola** [comment]
This work has been committed in other PRs, so closing this.

**Pull request closed without merging**
