### PR TITLE
Refactor readcsv in preparation for dist csv

### PR DESCRIPTION
**Pull request by madelynnblue**

### CODE REVIEW

**Comment by danhhz** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ccl/sqlccl/csv.go, line 86 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17415#-KqcVTvtjiraEw3L8CI4:-KqcVTvunFcOK44gA5VJ:b74fghn) ([raw file](https://github.com/cockroachdb/cockroach/blob/65478fbe6d9da4c0a4242bcb643aa1ecb854012f/pkg/ccl/sqlccl/csv.go#L86)):*
> ```Go
> 		dataFiles[i] = fmt.Sprintf("nodelocal://%s", f)
> 	}
> 	dest = fmt.Sprintf("nodelocal://%s", dest)
> ```

Now that we're using ExportStore for this, I'd prefer that we have the user give us the uri and we use it directly. That's both more consistent with our other tooling (BACKUP/RESTORE) and allows for more flexibility on where the input and output go

Or, if you disagree strongly, I'm happy to leave it as is and revisit the discussion in a TODO

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17415#-:-KqcWymDv2Kriz_tg25t:bnfp4nl)*

**Comment by mjibson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ccl/sqlccl/csv.go, line 86 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17415#-KqcVTvtjiraEw3L8CI4:-Kqd7REnEMnnggTBd6xw:b-ke07m6) ([raw file](https://github.com/cockroachdb/cockroach/blob/65478fbe6d9da4c0a4242bcb643aa1ecb854012f/pkg/ccl/sqlccl/csv.go#L86)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Now that we're using ExportStore for this, I'd prefer that we have the user give us the uri and we use it directly. That's both more consistent with our other tooling (BACKUP/RESTORE) and allows for more flexibility on where the input and output go

Or, if you disagree strongly, I'm happy to leave it as is and revisit the discussion in a TODO
</blockquote></details>

I'm unsure about the best way to proceed here. It's a bit onerous to users to have some files be local and other files use the ES syntax (i.e., have to prepend nodelocal:// to the dest directory). I kind of want to support both: if there's no scheme specified, it assumes nodelocal. Thoughts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17415)*

**Comment by danhhz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ccl/sqlccl/csv.go, line 86 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17415#-KqcVTvtjiraEw3L8CI4:-Kqd80-eRFbT0yWGFc9M:boulzyb) ([raw file](https://github.com/cockroachdb/cockroach/blob/65478fbe6d9da4c0a4242bcb643aa1ecb854012f/pkg/ccl/sqlccl/csv.go#L86)):*
> I kind of want to support both: if there's no scheme specified, it assumes nodelocal.

sgtm

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17415)*

**Comment by danhhz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ccl/sqlccl/csv.go, line 86 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17415#-KqcVTvtjiraEw3L8CI4:-Kqd8Fm0I0FtbxvbwX7s:bc0npwb) ([raw file](https://github.com/cockroachdb/cockroach/blob/65478fbe6d9da4c0a4242bcb643aa1ecb854012f/pkg/ccl/sqlccl/csv.go#L86)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

> I kind of want to support both: if there's no scheme specified, it assumes nodelocal.

sgtm
</blockquote></details>

I should also say, I'm fine leaving it as is and put this plan as a TODO. It's easy to come back to this later in the code freeze

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17415)*

**Comment by mjibson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/ccl/sqlccl/csv.go, line 86 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17415#-KqcVTvtjiraEw3L8CI4:-KqdHhdbIYgbYClyE71V:bvfdjvu) ([raw file](https://github.com/cockroachdb/cockroach/blob/65478fbe6d9da4c0a4242bcb643aa1ecb854012f/pkg/ccl/sqlccl/csv.go#L86)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I should also say, I'm fine leaving it as is and put this plan as a TODO. It's easy to come back to this later in the code freeze
</blockquote></details>

Added todo. Will merge after tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17415)*

**Pull request merged**
