### PR TITLE
bulk: extend BulkAdder/BufferingAdder to support adding keys with timestamp

### PR DESCRIPTION
**Pull request by gh-casper**
bulk: extend BulkAdder/BufferingAdder to support adding
    keys with timestamp

    Previously, BulkAdder and its primary implementation
    BufferingAdder assume all keys share same timestamp.
    But it is not the way ingestion processors use it in the
    tenant stream replication.

    This commit supports encoding key and timestamp into
    single key when adding it into buffering_adder and
    decoding it when flush it.

    Release justification: Cat 4
    Release note: None

Linked issue: https://github.com/cockroachdb/cockroach/issues/59176

### CODE REVIEW

**Comment by dt** [comment]
Hm.
`kvBufEntry` goes to some lengths to golf bytes (packing multiple ints into different bits in the one uint64), since we often have millions of them. I'm a little wary of a 50% increase in its size. I wonder if we can just pre-encode the full key instead?

**Review by gh-casper — COMMENTED** [review]
> kvBufEntry
Currently key's length bits is 28 bits and offset bits is 36, making a limit of 512mb per item, 32gb per buffer. If we make room for the length of a timestamp (a timestamp needs 10 bytes if encoded with protoutil.Marshal), we need 4 bits. Shall we take it from item length as 512 mb is impractical or take from both item length bits and offset bits？Wdyt?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85923#-:-N98WOmDC3r6ThZ7QQoZ:bm3d77e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @stevendanna)

**Comment by dt** [comment]
My suggestion was to not to steal some bits for the timestamp, but rather to not track the timestamp separately at all: we need the timestamp to encode keys to put in the SST, but we can just encode it into the keys now and skip that part later, and then the existing key span bits stay as they are, just describing a slightly longer key (that now has some timestamp on the end of it).

We'd want a flag like "this buffer has timestamped keys in it" so we know whether or not we need to timestamp them when they come out, but we could keep the buffer elements the same -- just a key and value slice per entry.

**Comment by dt** [comment]
How would you feel about putting this one on ice until after the 22.2 branch is cut?

If we realize we need it later, @stevendanna points out that we can make a fork of pkg/kv/bulk just for replication ingest in a backport.

**Pull request closed without merging**
