### PR TITLE
multi-tenant: Small cleanup of tenant testing

### PR DESCRIPTION
**Pull request by ajstorm**
This commit addresses two small problems with tenant testing:

- We were mistakenly not passing along the testing knobs from the server to the
  tenant.
- We were printing out the "this test is using a tenant" message before we were
  guaranteed to be using a tenant.

To resolve these issues we now:

- Pass along the testing knobs from the server to the tenant.
- Print out the tenant message only when we're guranteed to be running the test
  in a tenant.

Release justification: Testing only change
Release note: None

### CODE REVIEW

**Comment by ajstorm** [comment]
Hold off on reviewing for now.  Looks like someone else beat me to nearly the exact same change.

**Comment by ajstorm** [comment]
This should be ready for review now.  Adding @stevendanna to reviewers because I'm proposing we roll back his recent change.

**Review by stevendanna — APPROVED** [review]
LGTM! Only reason I didn't make this the default initially was to avoid any surprises for others, but I think this is better given that it looks like all the tests pass without issue.

**Comment by ajstorm** [comment]
TFTR @stevendanna!

bors r=stevendanna

**Pull request merged**
