### PR TITLE
exec: add support for FULL OUTER in merge join

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit adds support for FULL OUTER. This was quite simple since in order to support FULL OUTER we simply need to generate the code that corresponds to both LEFT OUTER and RIGHT OUTER.

Addresses: #37166.

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
Very nice that the templating work from left and right can be so easily reused here. That's good validation!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38630#-:-LjIK4KiDp4zY_FL0vzs:b-l1l6eu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @solongordon)

**Comment by yuzefovich** [comment]
Rebased it, so it is RFAL.

**Review by jordanlewis — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38630)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon and @yuzefovich)

___
*[pkg/sql/exec/mergejoiner_tmpl.go, line 1059 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38630#-LjWVdpiCqwnPUEO_3ue:-LjWVdpiCqwnPUEO_3uf:bqmy7pv) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d1c25070d3f17b4f9da57fdad60525208979573/pkg/sql/exec/mergejoiner_tmpl.go#L1059)):*
> ```Go
> 	// {{ end }}
> 	// {{ if or $.JoinType.IsLeftOuter $.JoinType.IsRightOuter }}
> 	o.outputReady = outputReady
> ```

Would it be easier just to be setting `o.outputReady` directly?

**Review by jordanlewis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38630#-:-LjWVkbKDay1gn5SGrpr:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @solongordon and @yuzefovich)

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38630)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @solongordon)

___
*[pkg/sql/exec/mergejoiner_tmpl.go, line 1059 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38630#-LjWVdpiCqwnPUEO_3ue:-LjWhdKy97O3uBy6mvQ9:b-lbcc49) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d1c25070d3f17b4f9da57fdad60525208979573/pkg/sql/exec/mergejoiner_tmpl.go#L1059)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Would it be easier just to be setting `o.outputReady` directly?
</blockquote></details>

Initially, when there was an if-else within each joinType switch, it wasn't possible to refactor this to set `o.outputReady` directly in case of FULL OUTER when right source was exhausted (in that case, we would first set to false - which is the desired - to exhaust the left source, but then override it with true since the right source was finished).

Now, I don't see a problem with writing o.outputReady directly (FULL OUTER is the only interesting case worth consideration, and at least one of the input sources is exhausted, so only one of the `if`s will happen). Thanks for pointing this out!

**Comment by yuzefovich** [comment]
Thanks for the review!

bors r+

**Pull request merged**
