### PR TITLE
go.mod: bump Pebble to 8801607debb0

### PR DESCRIPTION
**Pull request by itsbilal**
Second commit does the wholesale addition of error return values to `NewMVCCIterator` and `NewEngineIterator`.

```
8801607d db: Add TestConcurrentExcise
ad242264 *: add error return value to NewIter{,WithContext}
eb4a8571 *: implement EventuallyFileOnlySnapshots
```

Release note: None.
Epic: None.

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, 5 of 69 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108864)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @mgartner, and @rhu713)

___
*[`pkg/kv/kvserver/replica_rangefeed.go` line 408 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108864#-Nc2xSr8EnePDoDTdpPt:-Nc2xSr8EnePDoDTdpPu:b-37ixrs) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a1753d5e85e72ccc9a265982700c24931058e61/pkg/kv/kvserver/replica_rangefeed.go#L408)):*
> ```Go
> 		lowerBound, _ := keys.LockTableSingleKey(desc.StartKey.AsRawKey(), nil)
> 		upperBound, _ := keys.LockTableSingleKey(desc.EndKey.AsRawKey(), nil)
> 		iter, err := r.store.TODOEngine().NewEngineIterator(storage.IterOptions{
> ```

I'm a little worried about all these instances where we can't easily propagate an error return value.  I don't want some refactoring to end up feeding one of these call sites an EFOS snapshot `Reader`, and there's a subtle, very rare panic waiting to  happen.

Maybe we should add another `storage` package interface:
```
type ReaderWithMustIterators interface {
   Reader
   MustEngineIterator(r Reader) EngineIterator
   MustMVCCIterator(r Reader) MVCCIterator
}
```
And `Reader`s for which iterator construction is infallible can implement this interface. Then in situations like this, we have type safety protection against accidentally threading an EFOS snapshot in its stead.

**Comment by itsbilal** [comment]
*[`pkg/kv/kvserver/replica_rangefeed.go` line 408 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108864#-Nc2xSr8EnePDoDTdpPt:-Nc30Xpl0ePLlCTPzRQ9:b-2zgglo) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a1753d5e85e72ccc9a265982700c24931058e61/pkg/kv/kvserver/replica_rangefeed.go#L408)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I'm a little worried about all these instances where we can't easily propagate an error return value.  I don't want some refactoring to end up feeding one of these call sites an EFOS snapshot `Reader`, and there's a subtle, very rare panic waiting to  happen.

Maybe we should add another `storage` package interface:
```
type ReaderWithMustIterators interface {
   Reader
   MustEngineIterator(r Reader) EngineIterator
   MustMVCCIterator(r Reader) MVCCIterator
}
```
And `Reader`s for which iterator construction is infallible can implement this interface. Then in situations like this, we have type safety protection against accidentally threading an EFOS snapshot in its stead.
</blockquote></details>

I'm good with making that change, though the matching Pebble interface has already been updated even for paths that don't currently return errors. So if someone were to make a change to start returning an error in `*DB.NewIter`, and we have a panic in `*Pebble.MustMVCCIterator` in case of an error, we will still end up in the same place where we have a runtime panic and no direct type safety due to a mismatch in expectations between the Pebble struct in Cockroach and the DB struct in Pebble.

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108864)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @mgartner, and @rhu713)

___
*[`pkg/kv/kvserver/replica_rangefeed.go` line 408 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108864#-Nc2xSr8EnePDoDTdpPt:-Nc33n7v2JclSv2Si4hs:b4ks74g) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a1753d5e85e72ccc9a265982700c24931058e61/pkg/kv/kvserver/replica_rangefeed.go#L408)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I'm good with making that change, though the matching Pebble interface has already been updated even for paths that don't currently return errors. So if someone were to make a change to start returning an error in `*DB.NewIter`, and we have a panic in `*Pebble.MustMVCCIterator` in case of an error, we will still end up in the same place where we have a runtime panic and no direct type safety due to a mismatch in expectations between the Pebble struct in Cockroach and the DB struct in Pebble.
</blockquote></details>

Yes, but we're able to (independently of this change) propagate the `Must*` interface down into Pebble too. I also think it's more reasonable of an expectation that we (Storage) can maintain this contract at pkg/storage, than expecting all Cockroach engineers to understand which `Reader`s are safe to ignore errors from and which are not.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108864)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens, @mgartner, and @rhu713)

___
*[`pkg/kv/kvserver/replica_rangefeed.go` line 408 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108864#-Nc2xSr8EnePDoDTdpPt:-Nc3Nf1d2bjkJXq8oNan:bd7huxt) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a1753d5e85e72ccc9a265982700c24931058e61/pkg/kv/kvserver/replica_rangefeed.go#L408)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Yes, but we're able to (independently of this change) propagate the `Must*` interface down into Pebble too. I also think it's more reasonable of an expectation that we (Storage) can maintain this contract at pkg/storage, than expecting all Cockroach engineers to understand which `Reader`s are safe to ignore errors from and which are not.
</blockquote></details>

+1 to separating out these two interfaces.

**Review by itsbilal — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108864#-:-Nc3WyE9948IUlAnfS1P:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens, @mgartner, and @rhu713)

___
*[`pkg/kv/kvserver/replica_rangefeed.go` line 408 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108864#-Nc2xSr8EnePDoDTdpPt:-Nc3Wwro15s7_l35bjqH:b-m539f) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a1753d5e85e72ccc9a265982700c24931058e61/pkg/kv/kvserver/replica_rangefeed.go#L408)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

+1 to separating out these two interfaces.
</blockquote></details>

This is done now.

**Review by jbowens — COMMENTED** [review]
> Reviewed 11 of 69 files at r2, 2 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108864)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @rhu713, and @sumeerbhola)

___
*[`pkg/kv/kvserver/replica_rangefeed.go` line 408 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108864#-Nc2xSr8EnePDoDTdpPt:-Nc4HCYj7AwWQ6sSIx6Y:b-z4zj6g) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a1753d5e85e72ccc9a265982700c24931058e61/pkg/kv/kvserver/replica_rangefeed.go#L408)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

This is done now.
</blockquote></details>

This interface assertion shouldn't be necessary, right? `TODOEngine()` returns an `Engine` which always must implement `storage.ReaderWithMustIterators`?

Now that I'm looking at this again, could we leave `NewEngineIterator` and `NewMVCCIterator`'s `Reader` signatures as-is, and make the fallible `NewIterator` interface the exceptional? A `FallibleReader` or some such? This seems like it would reduce churn and eliminate boilerplate. If this is reasonable to you, sorry I didn't think of it earlier—I know these broad API refactors are annoying.

**Comment by itsbilal** [comment]
*[`pkg/kv/kvserver/replica_rangefeed.go` line 408 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108864#-Nc2xSr8EnePDoDTdpPt:-Nc4NCBr7npQKMlaiGvt:bd5a143) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a1753d5e85e72ccc9a265982700c24931058e61/pkg/kv/kvserver/replica_rangefeed.go#L408)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

This interface assertion shouldn't be necessary, right? `TODOEngine()` returns an `Engine` which always must implement `storage.ReaderWithMustIterators`?

Now that I'm looking at this again, could we leave `NewEngineIterator` and `NewMVCCIterator`'s `Reader` signatures as-is, and make the fallible `NewIterator` interface the exceptional? A `FallibleReader` or some such? This seems like it would reduce churn and eliminate boilerplate. If this is reasonable to you, sorry I didn't think of it earlier—I know these broad API refactors are annoying.
</blockquote></details>

I think we should stick with this and consider `ReaderWithMustIterators` as the exception rather than the norm. If anything we should move towards eliminating it (see point 6 below). Here are all the reasons why:

1) We will end up using EFOS in more cases going forward anyway
2) Future changes can introduce errors to existing iterator creation code paths
3) Most uses of NewMVCCIterator already handle errors or have error return values, this change just closes the gap
4) I've already done the bulk of the work of the refactor, and it'd be a shame to throw it away only to reintroduce it if we ever introduced errors elsewhere down the line
5) We already have too many interfaces (eg. InternalWriter vs Writer), 
6) The only cases where we _really_ need `ReaderWithMustIterators` are the MVCC incremental iterator (easily fixable with a mechanical refactor), and the rangefeed (a little more complex). I can see the rangefeed being the only longer-term user of `MustMVCCIterator`. Meanwhile we have 200+ uses of `NewMVCCIterator` that handle errors correctly.

I've made the TODOEngine change in this line.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, 33 of 69 files at r2, 8 of 12 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108864)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @jbowens, @mgartner, and @rhu713)

___
*[`pkg/kv/kvserver/replica_evaluate.go` line 110 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/108864#-Nc7ce_Z9KrnYDK4XFOm:-Nc7ce_Z9KrnYDK4XFOn:bgwf1v3) ([raw file](https://github.com/cockroachdb/cockroach/blob/630c317d2cab181ff51e6b329152642327cce19e/pkg/kv/kvserver/replica_evaluate.go#L110)):*
> ```Go
> 	})
> 	if err != nil {
> 		log.Fatalf(context.TODO(), "error when creating iterator: %s", err)
> ```

there is a single caller of `optimizePuts` that can handle an error by wrapping it like `pErr := kvpb.NewErrorWithTxn(err)`
___
*[`pkg/kv/kvserver/replica_rangefeed.go` line 408 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108864#-Nc2xSr8EnePDoDTdpPt:-Nc7ctZj4RCDwdcLyCZM:bgwloso) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a1753d5e85e72ccc9a265982700c24931058e61/pkg/kv/kvserver/replica_rangefeed.go#L408)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I think we should stick with this and consider `ReaderWithMustIterators` as the exception rather than the norm. If anything we should move towards eliminating it (see point 6 below). Here are all the reasons why:

1) We will end up using EFOS in more cases going forward anyway
2) Future changes can introduce errors to existing iterator creation code paths
3) Most uses of NewMVCCIterator already handle errors or have error return values, this change just closes the gap
4) I've already done the bulk of the work of the refactor, and it'd be a shame to throw it away only to reintroduce it if we ever introduced errors elsewhere down the line
5) We already have too many interfaces (eg. InternalWriter vs Writer), 
6) The only cases where we _really_ need `ReaderWithMustIterators` are the MVCC incremental iterator (easily fixable with a mechanical refactor), and the rangefeed (a little more complex). I can see the rangefeed being the only longer-term user of `MustMVCCIterator`. Meanwhile we have 200+ uses of `NewMVCCIterator` that handle errors correctly.

I've made the TODOEngine change in this line.
</blockquote></details>

I agree that error return should be the norm.
And now I don't see why we need these Must variants. I wonder whether it would be simpler with the following sequence of PRs:
- Introduce the interface change and change all callers to handle the error, with a few panics where it isn't vanilla refactoring. This touches many files but merges quickly. The PR we are currently reviewing can be changed to be this. There are no actual error returns, so there is no worry about those panics being hit.
- (potentially multiple small PRs) Fix all the panic cases by propagating error -- we can seek expertise of the various teams for these, if needed.
- Bump Pebble and change the storage package to propagate the error from Pebble.
___
*[`pkg/kv/kvserver/replica_rangefeed.go` line 420 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/108864#-Nc7eu4B5IsUtmzdSYuX:-Nc7eu4B5IsUtmzdSYuY:bv8z8sn) ([raw file](https://github.com/cockroachdb/cockroach/blob/630c317d2cab181ff51e6b329152642327cce19e/pkg/kv/kvserver/replica_rangefeed.go#L420)):*
> ```Go
> 	// due to stopping, but before it enters the quiescing state, then the select
> 	// below will fall through to the panic.
> 	if err := p.Start(r.store.Stopper(), rtsIter); err != nil {
> ```

this may be an acceptable way to handle an error in the `NewEngineIterator` case too.
___
*[`pkg/kv/kvserver/rangefeed/catchup_scan.go` line 87 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/108864#-Nc7adqx8TYxBlAKHMY8:-Nc7adqx8TYxBlAKHMY9:b-jrv9x3) ([raw file](https://github.com/cockroachdb/cockroach/blob/630c317d2cab181ff51e6b329152642327cce19e/pkg/kv/kvserver/rangefeed/catchup_scan.go#L87)):*
> ```Go
> ) *CatchUpIterator {
> 	return &CatchUpIterator{
> 		simpleCatchupIter: storage.NewMVCCIncrementalIterator(reader.(storage.ReaderWithMustIterators),
> ```

Can't this type assertion trigger a panic?
The only non-test caller is replica_rangefeed.go, which I think can handle an error using `return future.MakeCompletedErrorFuture(err)`.
___
*[`pkg/storage/mvcc.go` line 2840 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/108864#-Nc7bHH96FmnKGC192vj:-Nc7bHH96FmnKGC192vk:b-xijuf3) ([raw file](https://github.com/cockroachdb/cockroach/blob/630c317d2cab181ff51e6b329152642327cce19e/pkg/storage/mvcc.go#L2840)):*
> ```Go
> 	// _expect_ to hit this since the RevertRange is only intended for non-live
> 	// key spans, but there could be an intent leftover.
> 	iter := NewMVCCIncrementalIterator(rw.(ReaderWithMustIterators), MVCCIncrementalIterOptions{
> ```

same panic question. And this callsite can handle an error, just like all the callers of `NewMVCCIncrementalIterator` in this file.
___
*[`pkg/kv/kvserver/batcheval/cmd_export_test.go` line 533 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/108864#-Nc7bnZY4GDL43XXU-ZU:-Nc7bnZY4GDL43XXU-ZV:buo31h) ([raw file](https://github.com/cockroachdb/cockroach/blob/630c317d2cab181ff51e6b329152642327cce19e/pkg/kv/kvserver/batcheval/cmd_export_test.go#L533)):*
> ```Go
> 	}
> 
> 	iter := storage.NewMVCCIncrementalIterator(reader.(storage.ReaderWithMustIterators), storage.MVCCIncrementalIterOptions{
> ```

can handle error

**Review by itsbilal — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108864#-:-Nc7r9eCDTSR7SN6KOCD:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens, @mgartner, @rhu713, and @sumeerbhola)

___
*[`pkg/kv/kvserver/replica_evaluate.go` line 110 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/108864#-Nc7ce_Z9KrnYDK4XFOm:-Nc7m31c6uwEOxXGIh52:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/630c317d2cab181ff51e6b329152642327cce19e/pkg/kv/kvserver/replica_evaluate.go#L110)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

there is a single caller of `optimizePuts` that can handle an error by wrapping it like `pErr := kvpb.NewErrorWithTxn(err)`
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/replica_rangefeed.go` line 408 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108864#-Nc2xSr8EnePDoDTdpPt:-Nc7nM-E6FGvMSaqiELJ:bauvtnh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a1753d5e85e72ccc9a265982700c24931058e61/pkg/kv/kvserver/replica_rangefeed.go#L408)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I agree that error return should be the norm.
And now I don't see why we need these Must variants. I wonder whether it would be simpler with the following sequence of PRs:
- Introduce the interface change and change all callers to handle the error, with a few panics where it isn't vanilla refactoring. This touches many files but merges quickly. The PR we are currently reviewing can be changed to be this. There are no actual error returns, so there is no worry about those panics being hit.
- (potentially multiple small PRs) Fix all the panic cases by propagating error -- we can seek expertise of the various teams for these, if needed.
- Bump Pebble and change the storage package to propagate the error from Pebble.
</blockquote></details>

This PR was only supposed to be 1+3 anyway, at least with the way it was at the start. I'm down to decouple the Pebble bump if that helps. The only non-vanilla-refactors, like I said, are `NewMVCCIncrementalIterator` and its ~20 callsites, and `replica_{evaluate,rangefeed}.go` (which is actually addressed now that this PR is taking on some of the work from point 2, so it's really only `NewMVCCIncrementalIterator`). I was planning on doing `NewMVCCIncrementalIterator` separately anyway as there are some mild complexities there (eg. CatchUpIterator), which would be the rest of 2.

I've added a TODO to `NewMVCCIncrementalIterator`. If that sounds good, let me know - I can split out the replica_{evaluate,rangefeed} stuff too out of this PR but otherwise I think it already is covering all the mechanical refactors that shouldn't need more attention from other teams.
___
*[`pkg/kv/kvserver/replica_rangefeed.go` line 420 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/108864#-Nc7eu4B5IsUtmzdSYuX:-Nc7m3cM4QGBad9epBqo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/630c317d2cab181ff51e6b329152642327cce19e/pkg/kv/kvserver/replica_rangefeed.go#L420)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this may be an acceptable way to handle an error in the `NewEngineIterator` case too.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/rangefeed/catchup_scan.go` line 87 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/108864#-Nc7adqx8TYxBlAKHMY8:-Nc7m4q10i-usO0IurHi:b-hhf2cj) ([raw file](https://github.com/cockroachdb/cockroach/blob/630c317d2cab181ff51e6b329152642327cce19e/pkg/kv/kvserver/rangefeed/catchup_scan.go#L87)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can't this type assertion trigger a panic?
The only non-test caller is replica_rangefeed.go, which I think can handle an error using `return future.MakeCompletedErrorFuture(err)`.
</blockquote></details>

That's correct, but my understanding was that we'd prefer a type-assertion panic when we send an EFOS down the wrong code path, as opposed to the much rarer "panic on an error in the wild". Given my comment above that explicitly calls out NewMVCCIncrementalIterator as something we should fix to return an error soon, I agree that we should be returning an error here.

I just didn't want to update all ~30 callsites of NewMVCCIncrementalIterator in the same PR with the hope this would land quickly and that can be the follow-up (hence the TODO in NewMVCCIncrementalIterator that I removed with the ReaderWithMustIterator change), but I can do it.
___
*[`pkg/storage/mvcc.go` line 2840 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/108864#-Nc7bHH96FmnKGC192vj:-Nc7mcq24iB9Pr1sMWS3:b3nsgq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/630c317d2cab181ff51e6b329152642327cce19e/pkg/storage/mvcc.go#L2840)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

same panic question. And this callsite can handle an error, just like all the callers of `NewMVCCIncrementalIterator` in this file.
</blockquote></details>

`NewMVCCIncrementalIterator` case as mentioned above
___
*[`pkg/kv/kvserver/batcheval/cmd_export_test.go` line 533 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/108864#-Nc7bnZY4GDL43XXU-ZU:-Nc7mipWCGpv2Xy2JiW_:b-ya81ng) ([raw file](https://github.com/cockroachdb/cockroach/blob/630c317d2cab181ff51e6b329152642327cce19e/pkg/kv/kvserver/batcheval/cmd_export_test.go#L533)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can handle error
</blockquote></details>

Same as above

**Review by sumeerbhola — APPROVED** [review]
Thanks for doing this

:lgtm: 

> Reviewed 4 of 76 files at r5, 42 of 72 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108864#-:-NcNa-bM0Xjt3GDOltJ1:b34axqc)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens, @mgartner, and @rhu713)

**Pull request merged**
