### PR TITLE
opt: increase cost of full scans

### LINKED ISSUE #56661: Retries generated from small tables with constraints
**Describe the problem**

A transaction retry is being fired when two transactions, each with inserts on a table that has a FK reference for tables with a small amount of records.  It seems very similar to this issue:  https://github.com/cockroachdb/cockroach/issues/41701.  I believe the hash join / full scan on the constraint is blocking the other insert transaction.  Below are my steps to reproduce the issue:

**To Reproduce**

### Recreation steps
-- Create two terminal session and alternate between each step of the transaction to recreate
--   The retry occurs in terminal 1 when we insert into ch (2,2).  
--   The first two inserts into p work.  
--   The insert into ch waits in terminal 1
--   The insert into ch completes in terminal 2 which causes the ch insert in terminal 1 to retry.

-- Do this in one terminal
create table p (id int primary key);
create table ch (id int primary key, p_id int not null references p);
create index idx_ch_p_id on ch(p_id);

begin transaction;
insert into p values (1);
insert into ch values (1,1);
commit;

-- Do this in another terminal
begin transaction;
insert into p values (2);
insert into ch values (2,2);
commit;

-- Cleanup
drop table ch;
drop table p;

### Terminal 1

root@:26257/ap> create table p (id int primary key);
create table ch (id int primary key, p_id int not null references p);
create index idx_ch_p_id on ch(p_id);
CREATE TABLE

Time: 122ms total (execution 122ms / network 0ms)

CREATE TABLE

Time: 561ms total (execution 260ms / network 300ms)

CREATE INDEX

Time: 1.071s total (execution 0.092s / network 0.979s)

root@:26257/ap> explain insert into p values (1);
        tree       |    field     |   description
-------------------+--------------+------------------
                   | distribution | local
                   | vectorized   | false
  insert fast path |              |
                   | into         | p(id)
                   | auto commit  |
                   | size         | 1 column, 1 row
(6 rows)

Time: 46ms total (execution 45ms / network 0ms)

root@:26257/ap> begin transaction;
BEGIN

Time: 0ms total (execution 0ms / network 0ms)

root@:26257/ap  OPEN> insert into p values (1);
INSERT 1

Time: 2ms total (execution 2ms / network 0ms)

root@:26257/ap  OPEN> explain insert into ch values (1,1);
               tree               |        field        |   description
----------------------------------+---------------------+-------------------
                                  | distribution        | local
                                  | vectorized          | false
  root                            |                     |
   ├── insert                     |                     |
   │    │                         | into                | ch(id, p_id)
   │    └── buffer                |                     |
   │         │                    | label               | buffer 1
   │         └── values           |                     |
   │                              | size                | 2 columns, 1 row
   └── fk-check                   |                     |
        └── error if rows         |                     |
             └── hash join (anti) |                     |
                  │               | equality            | (column2) = (id)
                  │               | left cols are key   |
                  │               | right cols are key  |
                  ├── scan buffer |                     |
                  │               | label               | buffer 1
                  └── scan        |                     |
                                  | estimated row count | 1
                                  | table               | p@primary
                                  | spans               | FULL SCAN
(21 rows)

Time: 1ms total (execution 1ms / network 0ms)

root@:26257/ap  OPEN> insert into ch values (1,1);
ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_PUSHER_ABORTED): "sql txn" meta={id=4c4921eb key=/Table/185/1/1/0 pri=0.01029214 epo=0 ts=1605217678.414709000,0 min=1605217603.103393000,0 seq=3} lock=true stat=ABORTED rts=1605217661.518035000,2 wto=false max=1605217603.603393000,0
SQLSTATE: 40001

### Terminal 2

root@:26257/ap> begin transaction;
BEGIN

Time: 0ms total (execution 1ms / network 0ms)

root@:26257/ap  OPEN> insert into p values (2);
INSERT 1

Time: 1ms total (execution 1ms / network 0ms)

root@:26257/ap  OPEN> insert into ch values (2,2);
INSERT 1

Time: 98ms total (execution 98ms / network 0ms)

root@:26257/ap  OPEN>

**Expected behavior**

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version 20.2
 - Server OS: Mac OS
 - Client app: cockroach cli

### PR DESCRIPTION
**Pull request by RaduBerinde**
The main motivation for this change is to avoid seemingly bad plans
when the tables are empty or very small, in particular FK checks doing
full scans instead of using an index. This has caused confusion with
customers and users on multiple occasions.

In addition, even if the plans are good for small tables, they are
risky as the tables could get bigger than our stats show. Also, there
are other hidden costs to scanning more than we need (like contention).

This change makes a relatively small cost adjustment - it adds the
cost of 10 rows to full scans. This is enough to discourage full scans
on small tables, and to prefer constrained scans even when the row
count is the same.

Informs #56615.
Fixes #56661.

Release justification: low risk, high benefit changes to existing
functionality.

Release note (performance improvement): fixed cases where the
optimizer was doing unnecessary full table scans when the table was
very small (according to the last collected statistics).

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 36 of 36 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61680#-:-MVNLQBR-yUSVR7GcUs3:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/opt/exec/execbuilder/testdata/fk, line 1193 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61680#-MVNIZqZ-nQucsFVXyCR:-MVNIZqZ-nQucsFVXyCS:b-xgiecv) ([raw file](https://github.com/cockroachdb/cockroach/blob/862ee77af0117bc3875aa98ae4ed8a8d26265a59/pkg/sql/opt/exec/execbuilder/testdata/fk#L1193)):*
> ```
> ]'
> 
> # This query should use lookup join, even if the table is small.
> ```

[nit] "shoud use **a** lookup join"

It's not obvious to me that a lookup join is being used here. Does `insert fast path` imply a lookup join?
___
*[pkg/sql/opt/exec/execbuilder/testdata/fk, line 1416 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61680#-MVNJ_zQCb0nUeeTqQBV:-MVNJ_zQCb0nUeeTqQBW:b-51nfsw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e050d6ad7b6e7551619c37fbc25b8cb2a7701b2e/pkg/sql/opt/exec/execbuilder/testdata/fk#L1416)):*
> ```
> 
> query T
> EXPLAIN UPDATE p SET p=p+1 WHERE p > 0
> ```

did you intend to delete this test and the similar one above? redundant?
___
*[pkg/sql/opt/xform/coster.go, line 604 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61680#-MVNKhbH3Y-Ts77VIieZ:-MVNKhbH3Y-Ts77VIie_:b2wjfgr) ([raw file](https://github.com/cockroachdb/cockroach/blob/862ee77af0117bc3875aa98ae4ed8a8d26265a59/pkg/sql/opt/xform/coster.go#L604)):*
> ```Go
> 	// estimate turns out to be smaller than the actual row count.
> 	if scan.IsUnfiltered(c.mem.Metadata()) {
> 		baseCost += cpuCostFactor
> ```

I wonder, is this small cost addition still necessary now that we're adding 10 rows?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61680)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[pkg/sql/opt/exec/execbuilder/testdata/fk, line 1193 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61680#-MVNIZqZ-nQucsFVXyCR:-MVNSL41CfeNkMYBwZZC:b-okmhrb) ([raw file](https://github.com/cockroachdb/cockroach/blob/862ee77af0117bc3875aa98ae4ed8a8d26265a59/pkg/sql/opt/exec/execbuilder/testdata/fk#L1193)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] "shoud use **a** lookup join"

It's not obvious to me that a lookup join is being used here. Does `insert fast path` imply a lookup join?
</blockquote></details>

Yeah, fast path does lookups.
___
*[pkg/sql/opt/exec/execbuilder/testdata/fk, line 1416 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61680#-MVNJ_zQCb0nUeeTqQBV:-MVNRmTo0MV_HIUGXR5H:b-s62gfb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e050d6ad7b6e7551619c37fbc25b8cb2a7701b2e/pkg/sql/opt/exec/execbuilder/testdata/fk#L1416)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

did you intend to delete this test and the similar one above? redundant?
</blockquote></details>

It's redundant and doesn't work anymore, given that I had to make the child table bigger. By "doesn't work" I mean that it doesn't choose a hash join without `prefer_lookup_joins_for_fks` (previous diff).
___
*[pkg/sql/opt/xform/coster.go, line 604 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61680#-MVNKhbH3Y-Ts77VIieZ:-MVNRhoa-9VMktSsbw0p:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/862ee77af0117bc3875aa98ae4ed8a8d26265a59/pkg/sql/opt/xform/coster.go#L604)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I wonder, is this small cost addition still necessary now that we're adding 10 rows?
</blockquote></details>

Removed.

**Review by mgartner — APPROVED** [review]
Cool! :lgtm: 

> Reviewed 35 of 35 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61680#-:-MVNcz_03t51rikiB-2d:b-dp13x5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/exec/execbuilder/testdata/fk, line 1193 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61680#-MVNIZqZ-nQucsFVXyCR:-MVNcYco3x0IPBl1waRE:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/862ee77af0117bc3875aa98ae4ed8a8d26265a59/pkg/sql/opt/exec/execbuilder/testdata/fk#L1193)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yeah, fast path does lookups.
</blockquote></details>

:+1:

**Review by mgartner — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61680)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

**Pull request merged**
