### PR TITLE
colexec, colrpc: add deserialization time for inbox

### PR DESCRIPTION
**Pull request by cathymw**
This commit updates stream stats on EXPLAIN ANALYZE diagrams to display
the time Inbox spends deserializing batches. The deserialization time
is collected by the Inbox with a StopWatch.

The following screenshot shows the updated stream stats on EXPLAIN ANALYZE:
image

Release note (sql change): EXPLAIN ANALYZE diagrams now show
"deserialization time" on streams instead of "IO time".

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56144)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @cathymw, and @yuzefovich)

___
*[pkg/sql/colflow/colrpc/inbox.go, line 277 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56144#-ML9S67r4kcFTdU7h_Rc:-ML9S67s4DE8ILt0Tqyq:b-jmba3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/f438776549407101fdb339922c822864fa2fb49f/pkg/sql/colflow/colrpc/inbox.go#L277)):*
> ```Go
> 			colexecerror.InternalError(log.PanicAsError(0, err))
> 		}
> 		i.deserializationStopWatch.Stop()
> ```

I'd probably `defer` this right after we `Start`ed the stopwatch - as is, if `i.done` is `true`, we don't stop the stop watch.

**Review by cathymw — COMMENTED** [review]
Rebased after #55705 merged and addressed comment

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56144#-:-MLFO0fk3mOVdNCM2_Dl:bjsu44z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colflow/colrpc/inbox.go, line 277 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56144#-ML9S67r4kcFTdU7h_Rc:-MLFNeO9A_wXr9E64Q0M:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f438776549407101fdb339922c822864fa2fb49f/pkg/sql/colflow/colrpc/inbox.go#L277)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I'd probably `defer` this right after we `Start`ed the stopwatch - as is, if `i.done` is `true`, we don't stop the stop watch.
</blockquote></details>

Done.

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r2, 5 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56144)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @cathymw, and @yuzefovich)

___
*[pkg/sql/colexec/stats.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56144#-MLN0faT2Swm_m-AnSbc:-MLN0faU4lMFbHSgUtFu:b-tj3g51) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6b8a9ce66e41d732eac24be269e71666ce101a0/pkg/sql/colexec/stats.go#L31)):*
> ```Go
> 
> // The NetworkReader interface only exists to avoid an import cycle with
> // with the colrpc file. This interface should only be implemented by the inbox.
> ```

nit: two `with`s
___
*[pkg/sql/colflow/colrpc/inbox.go, line 253 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56144#-MLN1B-DD5fyGYBjZ6gj:-MLN1B-DD5fyGYBjZ6gk:b-b87p29) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6b8a9ce66e41d732eac24be269e71666ce101a0/pkg/sql/colflow/colrpc/inbox.go#L253)):*
> ```Go
> // Next is canceled or when DrainMeta goroutine tells it to do so.
> func (i *Inbox) Next(ctx context.Context) coldata.Batch {
> 	i.deserializationStopWatch.Start()
> ```

Why start the stopwatch here? I would start it before the call to `Deserialize` and defer `Stop` it there.

**Review by cathymw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56144)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/stats.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56144#-MLN0faT2Swm_m-AnSbc:-MLOPQDTEPGx7s4ulodx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6b8a9ce66e41d732eac24be269e71666ce101a0/pkg/sql/colexec/stats.go#L31)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: two `with`s
</blockquote></details>

Done.
___
*[pkg/sql/colflow/colrpc/inbox.go, line 253 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56144#-MLN1B-DD5fyGYBjZ6gj:-MLP-cON4WHr3pa9l-yK:bwdonjq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6b8a9ce66e41d732eac24be269e71666ce101a0/pkg/sql/colflow/colrpc/inbox.go#L253)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why start the stopwatch here? I would start it before the call to `Deserialize` and defer `Stop` it there.
</blockquote></details>

I was trying to record how long the Inbox spends time doing stuff (i.e. not counting the time inbox spends waiting to receive a batch from Outbox). I thought it was maybe more useful to display how long was spent in the inbox, other than network latency, rather than just timing the `Deserialize` call. But maybe `deserialization time` isn't the most accurate name for that?

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56144)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @cathymw, and @yuzefovich)

___
*[pkg/sql/colflow/colrpc/inbox.go, line 253 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56144#-MLN1B-DD5fyGYBjZ6gj:-MLRpIXQBiMkKeyHrWkO:b-gbdjci) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6b8a9ce66e41d732eac24be269e71666ce101a0/pkg/sql/colflow/colrpc/inbox.go#L253)):*
<details><summary><i>Previously, cathymw wrote…</i></summary><blockquote>

I was trying to record how long the Inbox spends time doing stuff (i.e. not counting the time inbox spends waiting to receive a batch from Outbox). I thought it was maybe more useful to display how long was spent in the inbox, other than network latency, rather than just timing the `Deserialize` call. But maybe `deserialization time` isn't the most accurate name for that?
</blockquote></details>

I don't know if this gets us anything though. In general the only "useful" work the inbox will be doing is deserializing these rows, which  is why I think it's sufficient to time the actual deserialization. We're currently including time spent waiting for a stream to be opened, for example (in `maybeInit`).

**Review by cathymw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56144)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colflow/colrpc/inbox.go, line 253 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56144#-MLN1B-DD5fyGYBjZ6gj:-MLUGwCLEH1h5LgBC7ps:b2upsbc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6b8a9ce66e41d732eac24be269e71666ce101a0/pkg/sql/colflow/colrpc/inbox.go#L253)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I don't know if this gets us anything though. In general the only "useful" work the inbox will be doing is deserializing these rows, which  is why I think it's sufficient to time the actual deserialization. We're currently including time spent waiting for a stream to be opened, for example (in `maybeInit`).
</blockquote></details>

Okay yeah, that makes sense. I moved the stopwatch `Start` and `End` to be around the `Deserialize` call. I left the deferred `Stop` outside of the for loop though so that it doesn't get added to the defer call stack multiple times

**Review by asubiotto — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56144)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @cathymw, and @yuzefovich)

___
*[pkg/sql/colflow/colrpc/inbox.go, line 253 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56144#-MLN1B-DD5fyGYBjZ6gj:-MLgPTFz7ur9p5mO5yhE:b-v830tj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6b8a9ce66e41d732eac24be269e71666ce101a0/pkg/sql/colflow/colrpc/inbox.go#L253)):*
<details><summary><i>Previously, cathymw wrote…</i></summary><blockquote>

Okay yeah, that makes sense. I moved the stopwatch `Start` and `End` to be around the `Deserialize` call. I left the deferred `Stop` outside of the for loop though so that it doesn't get added to the defer call stack multiple times
</blockquote></details>

I see the concern with the for loop. I would just:
```
stopWatch.Start()
defer stopWatch.Stop()
for {
     stopWatch.Stop()
     Recv()
     stopWatch.Start()
}
```
And remove all other references to the stopwatch.
___
*[pkg/sql/colflow/colrpc/inbox.go, line 267 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56144#-MLgQ9s47bYg8Idf7RpA:-MLgQ9s47bYg8Idf7RpB:bmdcjf6) ([raw file](https://github.com/cockroachdb/cockroach/blob/563828cd187ed389525d10d1560f843a9ab8b887/pkg/sql/colflow/colrpc/inbox.go#L267)):*
> ```Go
> 			colexecerror.InternalError(log.PanicAsError(0, err))
> 		}
> 		i.deserializationStopWatch.Stop()
> ```

If you follow my suggestion, I would remove this.

**Review by cathymw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56144)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colflow/colrpc/inbox.go, line 253 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56144#-MLN1B-DD5fyGYBjZ6gj:-MLhljJ6BUzYQaPj2-Mn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6b8a9ce66e41d732eac24be269e71666ce101a0/pkg/sql/colflow/colrpc/inbox.go#L253)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I see the concern with the for loop. I would just:
```
stopWatch.Start()
defer stopWatch.Stop()
for {
     stopWatch.Stop()
     Recv()
     stopWatch.Start()
}
```
And remove all other references to the stopwatch.
</blockquote></details>

Done.
___
*[pkg/sql/colflow/colrpc/inbox.go, line 267 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56144#-MLgQ9s47bYg8Idf7RpA:-MLhljyjAEd8PJnumvUd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/563828cd187ed389525d10d1560f843a9ab8b887/pkg/sql/colflow/colrpc/inbox.go#L267)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

If you follow my suggestion, I would remove this.
</blockquote></details>

Done.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56144#-:-MLlaDAL0fQhsWYnlzXl:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

**Comment by cathymw** [comment]
TFTRs! 

bors r=asubiotto

**Pull request merged**
