### PR TITLE
opt: add transformation rule to convert left join to inner join

### PR DESCRIPTION
**Pull request by rytaft**
Release justification: bug fixes and low-risk updates to new functionality

This commit adds an exploration rule `ConvertLeftToInnerJoin`, which converts
a left join to an inner join with the same `ON` condition, and then wraps the
expression in another left join with the original left side. In order to
avoid computing the left side of the join twice, we create a `With` expression
for the left side, and then reference it with two `WithScans`. For example
(assuming `x` is the primary key of `a`):
```
  SELECT a.x, b.y FROM a LEFT JOIN b ON ST_Intersects(a.geom, b.geom);
```
is converted to:
```
  WITH a_buf AS (
    SELECT * FROM a
  )
  SELECT a_buf.x, inr.y FROM a_buf LEFT JOIN (
    SELECT * FROM a_buf JOIN b ON ST_Intersects(a_buf.geom, b.geom)
  ) AS inr
  ON a_buf.x = inr.x;
```
Note that this transformation is not desirable in the general case, but it
is useful if there is a possibility of creating an inverted join (such as in
the above example). For this reason, we only perform this transformation if
it is possible to generate an inverted join.

This transformation allows us to index-accelerate spatial left joins, which
was not possible before.

Informs #53576

Release note (performance improvement): left outer spatial joins can now
be index-accelerated, which can lead to performance improvements in some
cases.

### CODE REVIEW

**Comment by rytaft** [comment]
I need to add more tests, but figured I'd post this now to see if there's any feedback.

**Review by RaduBerinde — COMMENTED** [review]
I have to look at the details a bit more but this should be ok to go in, given that it's conditioned on `CanGenerateInvertedJoin`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53976#-:-MGQUyYOA5uKO-1whgJP:brp7lfq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @RaduBerinde, @rytaft, and @sumeerbhola)

___
*[pkg/sql/opt/xform/rules/join.opt, line 143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53976#-MGQUaWT-FLaDB7GFSYu:-MGQUaWT-FLaDB7GFSYv:b9fxqkp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f709177852513881d95624ce28b577033546918e/pkg/sql/opt/xform/rules/join.opt#L143)):*
> ```
> # the above example). For this reason, we only perform this transformation if
> # CanGenerateInvertedJoin returns true.
> #
> ```

Feels like this isn't the desired end solution, if that's right leave a TODO and the issue number.
___
*[pkg/sql/opt/xform/rules/join.opt, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53976#-MGQT5X97EMREn-ahxXf:-MGQT5X97EMREn-ahxXg:b-qj8cot) ([raw file](https://github.com/cockroachdb/cockroach/blob/f709177852513881d95624ce28b577033546918e/pkg/sql/opt/xform/rules/join.opt#L151)):*
> ```
>     $right:^(InnerJoin)
>     $on:* & (CanGenerateInvertedJoin $left $right $on)
>     $private:* & (NoJoinHints $private) & (AddWithBinding $id:(NextWithID) $newLeft:(EnsureKey $left))
> ```

Hm, we shouldn't be adding anything in the match part of the rule. I think we should make `AddWithBinding` generate and return the WithID and do `$id:(AddWithBinding ..)` in the replace part

**Review by rytaft — COMMENTED** [review]
Fixed some issues and added more test cases. RFAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53976#-:-MGVKRZi8JOON7U4jkyG:bactuwh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @sumeerbhola)

___
*[pkg/sql/opt/xform/rules/join.opt, line 143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53976#-MGQUaWT-FLaDB7GFSYu:-MGVK3zf1uCEydx4wCQg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f709177852513881d95624ce28b577033546918e/pkg/sql/opt/xform/rules/join.opt#L143)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Feels like this isn't the desired end solution, if that's right leave a TODO and the issue number.
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/rules/join.opt, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53976#-MGQT5X97EMREn-ahxXf:-MGVK89bEzY4Hs-DMUjw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f709177852513881d95624ce28b577033546918e/pkg/sql/opt/xform/rules/join.opt#L151)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Hm, we shouldn't be adding anything in the match part of the rule. I think we should make `AddWithBinding` generate and return the WithID and do `$id:(AddWithBinding ..)` in the replace part
</blockquote></details>

Done.

**Review by mgartner — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1, 4 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53976)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @rytaft, and @sumeerbhola)

___
*[pkg/sql/logictest/testdata/logic_test/inverted_join_geospatial, line 186 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53976#-MGj5Bxy2oboqZqCJrNb:-MGj5Bxy2oboqZqCJrNc:b-8vryyz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8330294a1122fbb56d9ab2f09b3d9497a40de371/pkg/sql/logictest/testdata/logic_test/inverted_join_geospatial#L186)):*
> ```
> 16
> 
> # Left join is supported by having the optimizer convert it to an inner join.
> ```

It would be nice if there was a way to ensure that an INNER JOIN was used for these queries, but I don't think there is way to do so...
___
*[pkg/sql/opt/xform/custom_funcs.go, line 2818 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53976#-MGj5kDG9YQj1L3c9NWr:-MGj5kDG9YQj1L3c9NWs:bcljwg7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8330294a1122fbb56d9ab2f09b3d9497a40de371/pkg/sql/opt/xform/custom_funcs.go#L2818)):*
> ```Go
> // used to avoid applying certain rules such as ConvertLeftToInnerJoin in cases
> // where they will not be beneficial.
> func (c *CustomFuncs) CanGenerateInvertedJoin(left, right memo.RelExpr, on memo.FiltersExpr) bool {
> ```

Would this new rule benefit non-geo inverted index cases? If so, you can add a TODO so we can do so in a future release. If not, [nit] Rename this and update the comment to make it clear that this returns true only if there is a geo index.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53976#-:-MGjsshT9QFsbgiAVZ7P:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft and @sumeerbhola)

___
*[pkg/sql/opt/xform/rules/join.opt, line 145 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53976#-MGjrRY58cpG_MJ4l0ty:-MGjrRY58cpG_MJ4l0tz:bli0211) ([raw file](https://github.com/cockroachdb/cockroach/blob/8330294a1122fbb56d9ab2f09b3d9497a40de371/pkg/sql/opt/xform/rules/join.opt#L145)):*
> ```
> #
> # We also don't match if the right hand side is an InnerJoin, to prevent this
> # rule from matching an infinite number of times.
> ```

This sounds fragile (in principle another rule could add an operator in-between the leftjoin and the innerjoin). But looks like `CanGenerateInvertedJoin` would prevent these cases anyway, because the left join we are creating has simple equality and no geo relationship

**Review by rytaft — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53976#-:-MGk9oxC6-KAyfPhK-76:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @RaduBerinde, and @sumeerbhola)

___
*[pkg/sql/logictest/testdata/logic_test/inverted_join_geospatial, line 186 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53976#-MGj5Bxy2oboqZqCJrNb:-MGk2j4g9rVB_cVWyUbB:b-7w9xsp) ([raw file](https://github.com/cockroachdb/cockroach/blob/8330294a1122fbb56d9ab2f09b3d9497a40de371/pkg/sql/logictest/testdata/logic_test/inverted_join_geospatial#L186)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It would be nice if there was a way to ensure that an INNER JOIN was used for these queries, but I don't think there is way to do so...
</blockquote></details>

Like with a join hint? I don't think that works in this case, unfortunately. But the EXPLAIN plans for at least a subset of these are included in `inverted_join_geospatial_dist` and `inverted_join_geospatial_explain`, and those all show an inverted (inner) join.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 2818 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53976#-MGj5kDG9YQj1L3c9NWr:-MGk8YKN1J1p_hYSfoE7:brq66m7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8330294a1122fbb56d9ab2f09b3d9497a40de371/pkg/sql/opt/xform/custom_funcs.go#L2818)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Would this new rule benefit non-geo inverted index cases? If so, you can add a TODO so we can do so in a future release. If not, [nit] Rename this and update the comment to make it clear that this returns true only if there is a geo index.
</blockquote></details>

Done (added a TODO above the rule).
___
*[pkg/sql/opt/xform/rules/join.opt, line 145 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53976#-MGjrRY58cpG_MJ4l0ty:-MGk3VkbBFr0KJee8xCd:b-xxbo7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/8330294a1122fbb56d9ab2f09b3d9497a40de371/pkg/sql/opt/xform/rules/join.opt#L145)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This sounds fragile (in principle another rule could add an operator in-between the leftjoin and the innerjoin). But looks like `CanGenerateInvertedJoin` would prevent these cases anyway, because the left join we are creating has simple equality and no geo relationship
</blockquote></details>

I was able to remove this by only checking whether the right input matches the criteria in `CanGenerateInvertedJoin`. Only the right side matters anyway (since the left input will become a `WithScan`).

**Review by mgartner — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53976#-:-MGkBYy60fuA4mgAbPt7:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @RaduBerinde, and @sumeerbhola)

**Review by sumeerbhola — COMMENTED** [review]
>  In order to
> avoid computing the left side of the join twice, we create a With expression
> for the left side, and then reference it with two WithScans.

What happens when executing this scan to populate `a_buf` -- is it one processor that is feeding two places in the expression? Is `a_buf` buffered somewhere or is is always the build side of the hash join? The EXPLAIN urls have  
"local scan buffer 0/0" and "local scan buffer 1/3" which I don't understand.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53976#-:-MGn7lP05XnmAWF6XBld:b-yfer3w)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner, @RaduBerinde, and @sumeerbhola)

**Comment by rytaft** [comment]
Yep, exactly -- the output of the WITH expression is buffered, and used to feed those two places in the plan.

I think the explain URLs don't include the execution of the subqueries -- that happens prior to execution of the main plan.

**Pull request merged**
