### PR TITLE
pkg/ui: Swap in new Snapshot debug component

### PR DESCRIPTION
**Pull request by benbardin**
The PR focuses on the routes. I'll delete deprecated code in a follow-up diff.

Part of: https://github.com/cockroachdb/cockroach/issues/83679

Release note: None

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94701)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @benbardin)

___
*[`pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx` line 326 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94701#-NLM4VpCBbVjl2TenXWk:-NLM4VpCBbVjl2TenXWl:b-nnwgwm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a030b3b9225be5b6f2171bf30a9a2bb0e98110c8/pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx#L326)):*
> ```XML
>     ],
>     [nodeID, snapshotID, spanID, spanOperation],
>   );
> ```

is `useMemo` necessary here? the operation doesn't look expensive.
___
*[`pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx` line 341 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94701#-NLM4ahm20-4plLlQB2N:-NLM4ahm20-4plLlQB2O:b1jet0p) ([raw file](https://github.com/cockroachdb/cockroach/blob/a030b3b9225be5b6f2171bf30a9a2bb0e98110c8/pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx#L341)):*
> ```XML
>     // eslint-disable-next-line react-hooks/exhaustive-deps
>     [nodeID, snapshotID, spanID, spanOperation],
>   );
> ```

same comment as above.

**Review by benbardin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94701)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @dhartunian)

___
*[`pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx` line 326 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94701#-NLM4VpCBbVjl2TenXWk:-NLWpD9t149AEW4CHV3b:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a030b3b9225be5b6f2171bf30a9a2bb0e98110c8/pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx#L326)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

is `useMemo` necessary here? the operation doesn't look expensive.
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx` line 341 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94701#-NLM4ahm20-4plLlQB2N:-NLWpDZGEFQq67XZ7ThO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a030b3b9225be5b6f2171bf30a9a2bb0e98110c8/pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx#L341)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

same comment as above.
</blockquote></details>

Done.

**Review by dhartunian — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94701#-:-NLWqsrED43LIWzTlPnD:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

**Comment by rail** [comment]
bors r-
We have temporarily disabled bors for merges. Please merge the PR manually when all required checks pass.

**Pull request merged**
