### PR TITLE
distsqlrun: assert there's at least a proc in a flow

### PR DESCRIPTION
**Pull request by andreimatei**
The code was trying to protect against a flow with nothing in
flow.processors, but I don't think that's thing.
Code becomes clearer if we assume at least one processor.

Release note: None

### CODE REVIEW

**Review by jordanlewis — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35314)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @asubiotto, and @jordanlewis)

___
*[pkg/sql/distsqlrun/flow.go, line 609 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35314#-LZvTe_SEPyw4rkuu5wH:-LZvTe_SEPyw4rkuu5wI:bl2rpiv) ([raw file](https://github.com/cockroachdb/cockroach/blob/63b2996e06cfb74687dd1400ebc48e705dd4b8fd/pkg/sql/distsqlrun/flow.go#L609)):*
> ```Go
> 	var headProc Processor
> 	if len(f.processors) == 0 {
> 		return errors.Errorf("programming error: no processors in flow")
> ```

Use pgerror.AssertionErrorf.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35314)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/distsqlrun/flow.go, line 609 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35314#-LZvTe_SEPyw4rkuu5wH:-LZvgcoM8Y5GG24fc4DO:b-ipssjq) ([raw file](https://github.com/cockroachdb/cockroach/blob/63b2996e06cfb74687dd1400ebc48e705dd4b8fd/pkg/sql/distsqlrun/flow.go#L609)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Use pgerror.AssertionErrorf. 
</blockquote></details>

done. But I think it'd be better this error lived in base somewhere and would be recognized by SQL in `convertToErrWithPGCode()`.

**Comment by jordanlewis** [comment]
LGTM

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35314#-:-L_3gv7z6Oxsa_A3qgzF:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

**Pull request merged**
