### PR TITLE
sql: disable primary key changes with other schema changes in same transaction

### PR DESCRIPTION
**Pull request by rohany**
Release note (sql change): This PR disables the use of
primary key changes along with other schema changes
in the same transaction.

### CODE REVIEW

**Comment by rohany** [comment]
I'm not sure if we want to go in this direction, but I've prepared the PR in either case.

**Comment by knz** [comment]
before this PR merges (if it does) please extend the release note, it's too short currently.

**Comment by rohany** [comment]
Can I get a review on this @lucy-zhang? I think we should go down this route for now.

**Comment by rohany** [comment]
Friendly ping.

**Comment by rohany** [comment]
I'm actually going to close this in favor of other PRs.

**Pull request closed without merging**
