### PR TITLE
storage: streaming snapshots improvements

### PR DESCRIPTION
**Pull request by jordanlewis**
This pull request contains several commits that respond to post-merge comments
on #8726.

```
Changes:

   storage: distinct batches for snapshot logs

   This commit re-introduces the use of distinct batches to snapshot
   application for clearing the range.

   rocksDBBatch.ApplyBatchRepr also had a small bug - it didn't flush
   mutations before applying the repr. That's corrected now.

  storage: streaming snap miscellaneous improvements

   - Rename OutgoingSnap.{Snap,Snapshot} to {EngineSnap,RaftSnap} for
    clarity
   - Use uuid.Short() to log Snapshot uuids.

   storage: get snapshot log entries lazily

   When sending a streaming snapshot, delay getting the raft log entries from
   the rocksdb snapshot until we need them.

   storage: streaming snaps chunked by size in bytes

   Previously, snapshots were chunked based on the number of entries in a
   batch. Now they are chunked based on the size in bytes of the batch.

   storage/engine: improve batch.Repr()

   If the batch has never been flushed, we can just return the mutations as a
   Repr without having to flush to C++ and read bytes back.
```

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8958)

### CODE REVIEW

**Comment by petermattis** [comment]
Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 5 of 5 files at r4.
Review status: 5 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[storage/replica_raftstorage.go, line 627 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958#-KQS2JX3QC7F5qfFRFj7:-KQS2JX3QC7F5qfFRFj8:b-rsi20r) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfae67d608e42e0034f237a03ab8e538eecdd1cc/storage/replica_raftstorage.go#L627)):*
> ```Go
> 	defer batch.Close()
> 
> 	// The log entries are all written to distinct keys so we can use a
> ```

This comment is inaccurate. The part about the log entries should be down below next to the distinct batch used for writing the log entries. And let's resurrect the comment about why clearing can be done using a distinct batch.

---

*[storage/replica_raftstorage.go, line 649 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958#-KQS2efG1Un8tQi_NHAQ:-KQS2efG1Un8tQi_NHAR:b-wbidra) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfae67d608e42e0034f237a03ab8e538eecdd1cc/storage/replica_raftstorage.go#L649)):*
> ```Go
> 	// Write the snapshot into the range.
> 	for _, batchRepr := range inSnap.Batches {
> 		if err := batch.ApplyBatchRepr(batchRepr); err != nil {
> ```

It looks like `rocksDBBatch.ApplyBatchRepr` needs to call `flushMutations`. 

---

*[storage/store.go, line 2561 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958#-KQS1DQ_JOuosFYcRnuQ:-KQS1DQa3wg4aZaJfRdl:b-ekgjjj) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ba66987c03d65eb9cfc24c03bb787b24de15683/storage/store.go#L2561)):*
> ```Go
> 	var alloc bufalloc.ByteAllocator
> 	// TODO(jordan) make this configurable. For now, 1MB.
> 	batchSize := 1024 * 1024
> ```

`const batchSize = 10 << 20` (shifting left by 20 multiplies by 1 MB).

---

*[storage/engine/batch.go, line 90 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958#-KQS0vt7MKHiEmjA_1Y_:-KQS0vt8OrPplhIdO2X1:b6bwrvk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5d5f192fdc3314defde8589002002c0bf416460/storage/engine/batch.go#L90)):*
> ```Go
> }
> 
> // repr constructs the batch representation and returns it.
> ```

`s/repr/getRepr/g`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958)*

**Comment by jordanlewis** [comment]
Review status: 1 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[storage/replica_raftstorage.go, line 649 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958#-KQS2efG1Un8tQi_NHAQ:-KQS3D1hJDTUTvsyzL8H:b9k1p80) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfae67d608e42e0034f237a03ab8e538eecdd1cc/storage/replica_raftstorage.go#L649)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> It looks like `rocksDBBatch.ApplyBatchRepr` needs to call `flushMutations`. 
</details>
Done. That fixed the issue.

---

*[storage/store.go, line 2561 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958#-KQS1DQ_JOuosFYcRnuQ:-KQS3MzGQRE6ICGBF9kW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ba66987c03d65eb9cfc24c03bb787b24de15683/storage/store.go#L2561)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `const batchSize = 10 << 20` (shifting left by 20 multiplies by 1 MB).
</details>
Done.

---

*[storage/engine/batch.go, line 90 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958#-KQS0vt7MKHiEmjA_1Y_:-KQS3WBvzvl_n-HieG7n:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5d5f192fdc3314defde8589002002c0bf416460/storage/engine/batch.go#L90)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `s/repr/getRepr/g`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958)*

**Comment by jordanlewis** [comment]
Review status: 1 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[storage/replica_raftstorage.go, line 627 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958#-KQS2JX3QC7F5qfFRFj7:-KQS8MNVD9_S9wUvHSug:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfae67d608e42e0034f237a03ab8e538eecdd1cc/storage/replica_raftstorage.go#L627)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> This comment is inaccurate. The part about the log entries should be down below next to the distinct batch used for writing the log entries. And let's resurrect the comment about why clearing can be done using a distinct batch.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958)*

**Comment by petermattis** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r5.
Review status: 1 of 8 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/replica_raftstorage.go, line 630 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958#-KQSCC83dkKVqToQUQGv:-KQSCC83dkKVqToQUQGw:b-begdbd) ([raw file](https://github.com/cockroachdb/cockroach/blob/97265f177d5d66e67a48c41645840873c98a7fc8/storage/replica_raftstorage.go#L630)):*
> ```Go
> 	// that are potentially overwritten below, which violates the spirit of
> 	// the distinct batch. This is safe because we don't do any reads until
> 	// after the distinct batch is closed.
> ```

I think the second sentence and third sentences are no longer accurate. How about:

```
Clear the range using a distinct batch in order to prevent the iteration from forcing the batch to flush from Go to C++.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958#-:-KQSCSxPV3jkjnv5bYU7:bnfp4nl)*

**Comment by jordanlewis** [comment]
Review status: 1 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/replica_raftstorage.go, line 630 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958#-KQSCC83dkKVqToQUQGv:-KQSDZKSn9x8aAc_tVs-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/97265f177d5d66e67a48c41645840873c98a7fc8/storage/replica_raftstorage.go#L630)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I think the second sentence and third sentences are no longer accurate. How about:
> 
> ```
> Clear the range using a distinct batch in order to prevent the iteration from forcing the batch to flush from Go to C++.
> ```
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958)*

**Comment by tamird** [comment]
:lgtm:

Can you update the PR message?

---

Reviewed 2 of 3 files at r1, 6 of 6 files at r6, 1 of 1 files at r7, 2 of 2 files at r8, 4 of 5 files at r9, 3 of 4 files at r10, 1 of 1 files at r11.
Review status: 7 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[storage/replica_raftstorage.go, line 494 \[r9\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958#-KQSE958EuRx78ASaYiU:-KQSE958EuRx78ASaYiV:b-qojoi5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f14b88629bbbd696f6457189c4a4dd587ba1138a/storage/replica_raftstorage.go#L494)):*
> ```Go
> 		EngineSnap: snap,
> 		Iter:       iter,
> 		LogEntries: snapData.LogEntries,
> ```

this is unrelated to the rest of this commit, right? I think it belongs in 9f7ac9a.

---

*[storage/replica_test.go, line 6466 \[r9\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958#-KQSEJ18FOb5HfQ0204u:-KQSEJ18FOb5HfQ0204v:b-mzd3d7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f14b88629bbbd696f6457189c4a4dd587ba1138a/storage/replica_test.go#L6466)):*
> ```Go
> 		RangeDescriptor: *firstRng.Desc(),
> 		Batches:         [][]byte{b.Repr()},
> 		LogEntries:      snap.LogEntries,
> ```

belongs in 9f7ac9a?

---

*[storage/store.go, line 2561 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958#-KQSD-w_BntFSTThC_rZ:-KQSD-w_BntFSTThC_r_:bq5bewr) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b5363d4a7038cb6e513d8e34e438ea720f413ee/storage/store.go#L2561)):*
> ```Go
> 	var alloc bufalloc.ByteAllocator
> 	// TODO(jordan) make this configurable. For now, 1MB.
> 	const batchSize = 1 << 20
> ```

Consider reverting 1d95a1718d4ee91e7935442578d09873f77d7465 in this commit.

---

*[storage/store.go, line 2589 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958#-KQSDOB42KuKfrcZ_VOm:-KQSDOB53ZnWsEIfmLJ8:blq4dd5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b5363d4a7038cb6e513d8e34e438ea720f413ee/storage/store.go#L2589)):*
> ```Go
> 			}
> 			b = nil
> 			alloc = bufalloc.ByteAllocator{}
> ```

what's this about?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958#-:-KQSE3rW46DWskitTROk:b-iqw31q)*

**Comment by tamird** [comment]
Reviewed 1 of 5 files at r9.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958)*

**Comment by jordanlewis** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[storage/replica_raftstorage.go, line 494 \[r9\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958#-KQSE958EuRx78ASaYiU:-KQSG4ZCfiA5LxU3q1yq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f14b88629bbbd696f6457189c4a4dd587ba1138a/storage/replica_raftstorage.go#L494)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this is unrelated to the rest of this commit, right? I think it belongs in 9f7ac9a.
</details>
Done.

---

*[storage/replica_test.go, line 6466 \[r9\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958#-KQSEJ18FOb5HfQ0204u:-KQSGhO9HXascT5_c8mA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f14b88629bbbd696f6457189c4a4dd587ba1138a/storage/replica_test.go#L6466)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> belongs in 9f7ac9a?
</details>
Done.

---

*[storage/store.go, line 2561 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958#-KQSD-w_BntFSTThC_rZ:-KQSGnM-dvx7HUo7Pxsa:blbxwod) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b5363d4a7038cb6e513d8e34e438ea720f413ee/storage/store.go#L2561)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Consider reverting 1d95a1718d4ee91e7935442578d09873f77d7465 in this commit.
</details>
I'd prefer to do this later, or maybe leave it to someone more familiar with that area - there's a TODO about needing more tests, but I'm not sure about the context.

---

*[storage/store.go, line 2589 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958#-KQSDOB42KuKfrcZ_VOm:-KQSG6hHSjG4jDB3xT-g:b-4xymdp) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b5363d4a7038cb6e513d8e34e438ea720f413ee/storage/store.go#L2589)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> what's this about?
</details>
Resetting `alloc` releases the memory that the chunk used to buffer its changes. See Peter's comments on #8726.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958)*

**Comment by tamird** [comment]
Reviewed 6 of 6 files at r12.
Review status: 2 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/store.go, line 2561 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958#-KQSD-w_BntFSTThC_rZ:-KQSIfGaGBCesgeXtyjM:bpr2pbb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b5363d4a7038cb6e513d8e34e438ea720f413ee/storage/store.go#L2561)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary>
> I'd prefer to do this later, or maybe leave it to someone more familiar with that area - there's a TODO about needing more tests, but I'm not sure about the context.
</details>
Sounds good. Could you just update the TODO, though?

By the way, the log entries are not actually currently streaming, are they? They seem to be sent in one large lump, which can still greatly exceed 1MB. Am I understanding that right?

---

*[storage/store.go, line 2589 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958#-KQSDOB42KuKfrcZ_VOm:-KQSHu3HBBP7Hzd05DCv:b-mlbyg9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b5363d4a7038cb6e513d8e34e438ea720f413ee/storage/store.go#L2589)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary>
> Resetting `alloc` releases the memory that the chunk used to buffer its changes. See Peter's comments on #8726.
</details>
Cool. Might be worth a comment since this pattern doesn't appear anywhere else.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958)*

**Comment by tamird** [comment]
Reviewed 5 of 5 files at r13, 2 of 2 files at r14.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958)*

**Comment by jordanlewis** [comment]
Review status: 2 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/store.go, line 2561 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958#-KQSD-w_BntFSTThC_rZ:-KQSJLHAgvEKbRbVk7s3:b-rf7fbd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b5363d4a7038cb6e513d8e34e438ea720f413ee/storage/store.go#L2561)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Sounds good. Could you just update the TODO, though?
> 
> By the way, the log entries are not actually currently streaming, are they? They seem to be sent in one large lump, which can still greatly exceed 1MB. Am I understanding that right?
</details>
Correct - log entries aren't streaming yet. Updated the TODO.

---

*[storage/store.go, line 2589 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958#-KQSDOB42KuKfrcZ_VOm:-KQSLzuWmSOuTM6ZiP1v:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b5363d4a7038cb6e513d8e34e438ea720f413ee/storage/store.go#L2589)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Cool. Might be worth a comment since this pattern doesn't appear anywhere else.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958)*

**Comment by tamird** [comment]
Reviewed 1 of 7 files at r15, 4 of 5 files at r17, 2 of 2 files at r18.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8958)*

**Pull request merged**
