### PR TITLE
kvcoord: Pace rangefeed client goroutine creation

### LINKED ISSUE #98842: kvcoord: pace DistSender rangefeed goroutines
When the DistSender processes a RangeFeed request across a key span, it spawns goroutines to process each individual range:

https://github.com/cockroachdb/cockroach/blob/736a67e0d36cc545bf74d65db069ee895ff9bea0/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L206-L210

For large spans, this can put a lot of pressure on the Go scheduler. Furthermore, most of these goroutines will immediately block on this semaphore:

https://github.com/cockroachdb/cockroach/blob/736a67e0d36cc545bf74d65db069ee895ff9bea0/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L565-L566

We should instead use this semaphore to pace the spawning of goroutines, significantly reducing the scheduler pressure.

Jira issue: CRDB-25544

Epic CRDB-26372

### PR DESCRIPTION
**Pull request by miretskiy**
Acquire catchup scan quota prior to goroutine creation in order to pace the goroutine creation rate.

This change results in nice and smooth growth in
goroutine count, thus reducing the pressure on goroutine scheduler, which in turn reduces the impact on SQL latency during changefeed startup.

This change also improves observability in rangefeed client by introducing new counters:
 * `distsender.rangefeed.retry.<reason>`: counter keeping track of the number of ranges that ecountered a retryable error of particular type (e.g. slow counsumer, range split, etc).

Observability also enhanced by adding a column to
 `crdb_internal.active_rangefeed` virtual table augment to indicate
if the range is currently in catchup scan mode.

Fixes #98842

Release note (enterprise change): Pace rangefeed goroutine creation
rate to improve scheduler latency.  Improve observability by adding
additional metrics indicating the reason for rangefeed restart
as well as additional column in the `crdb_internal.active_rangefeed`
table to indicate if the range is currently in catchup scan mode.

### CODE REVIEW

**Comment by miretskiy** [comment]
Smooth startup (100k ranges):

Screenshot 2023-08-23 at 12 12 49 PM

**Comment by miretskiy** [comment]
Screenshot 2023-08-23 at 12 18 34 PM

**Review by erikgrinaker — COMMENTED** [review]
I'm flushing some initial comments, but I have to follow up on a high-priority L2 escalation. Will resume the review later.

> Reviewed 6 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109346#-:-NcvsfZk30HFbsoO1vjj:b-t8lmd3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @ericharmeling, and @miretskiy)

___
*[`-- commits` line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109346#-NcvcsWs1PlMhNjagZUV):*
Could use a release note, both for the pacing and observability.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109346#-Ncvd5rp8FVZGFS6sztf:-Ncvd5rp8FVZGFS6sztg:b-de6zms) ([raw file](https://github.com/cockroachdb/cockroach/blob/23b97a1b2e4f0fb5bf4902e51d3ec7789593e6bb/pkg/kv/kvclient/kvcoord/dist_sender.go#L214)):*
> ```Go
> 	}
> 	metaDistSenderRangefeedPostCatchupRanges = metric.Metadata{
> 		Name: "distsender.rangefeed.post_catchup_ranges",
> ```

Why do we need this when we already have distsender.rangefeed.catchup_ranges? Do we expect this to be any different than distsender.rangefeed.total_ranges - distsender.rangefeed.catchup_ranges? If so, why, and maybe we should fix that instead?
___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 370 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109346#-Ncvh_c95J_pmXaYJJUW:-Ncvh_c95J_pmXaYJJUX:b-z69cgb) ([raw file](https://github.com/cockroachdb/cockroach/blob/23b97a1b2e4f0fb5bf4902e51d3ec7789593e6bb/pkg/kv/kvclient/kvcoord/dist_sender.go#L370)):*
> ```Go
> 	var retryCounters [kvpb.NumRangeFeedRetryErrors]*metric.Counter
> 	for idx, name := range kvpb.RangeFeedRetryError_Reason_name {
> 		retryCounters[idx] = metric.NewCounter(metric.Metadata{
> ```

This will break when we remove a reason. Consider using a map instead, which also removes the need for `NumRangeFeedRetryErrors` and associated logic.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109346#-Ncve024BlQS3rfBqgZL:-Ncve024BlQS3rfBqgZM:b-tfebba) ([raw file](https://github.com/cockroachdb/cockroach/blob/23b97a1b2e4f0fb5bf4902e51d3ec7789593e6bb/pkg/kv/kvclient/kvcoord/dist_sender.go#L371)):*
> ```Go
> 	for idx, name := range kvpb.RangeFeedRetryError_Reason_name {
> 		retryCounters[idx] = metric.NewCounter(metric.Metadata{
> 			Name:        fmt.Sprintf("distsender.rangefeed.retry.%s", strings.ToLower(name)),
> ```

Should we strip the reason_ prefix here? Also, we may want to add a note on `RangeFeedRetryError_Reason` that the reason names should be stable because they are exposed via metric names.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 372 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109346#-NcveOc2BvcAOYCpNdJb:-NcveOc2BvcAOYCpNdJc:boncry7) ([raw file](https://github.com/cockroachdb/cockroach/blob/23b97a1b2e4f0fb5bf4902e51d3ec7789593e6bb/pkg/kv/kvclient/kvcoord/dist_sender.go#L372)):*
> ```Go
> 		retryCounters[idx] = metric.NewCounter(metric.Metadata{
> 			Name:        fmt.Sprintf("distsender.rangefeed.retry.%s", strings.ToLower(name)),
> 			Help:        `Number of ranges in retried due to rangefeed retry error`,
> ```

What about retries due to e.g. connection failures and other errors? Should those be included here too? We'd want this to add up to distsender.rangefeed.restart_ranges, right?

Also, nit: "number of rangefeed retries". It's not the number of ranges, it's the number of retried errors.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go` line 372 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109346#-NcvjchT4tnOqsuTIs18:-NcvjchT4tnOqsuTIs19:b1st271) ([raw file](https://github.com/cockroachdb/cockroach/blob/23b97a1b2e4f0fb5bf4902e51d3ec7789593e6bb/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L372)):*
> ```Go
> 	// catchupRes is the catchup scan quota acquired upon the
> 	// start of rangefeed.
> 	// It is released when this stream receives first non-empty checkpoint
> ```

The rangefeed protocol sends an empty checkpoint precisely to signal completion of the catchup scan, so the non-empty bit here seems wrong.

https://github.com/cockroachdb/cockroach/blob/b35afe9031b8acc917551c293bcafac253970634/pkg/kv/kvserver/rangefeed/processor.go#L393-L398

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109346)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @ericharmeling, and @erikgrinaker)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109346#-Ncvd5rp8FVZGFS6sztf:-NcwIpv772wsn-9IJHDn:bgheqi4) ([raw file](https://github.com/cockroachdb/cockroach/blob/23b97a1b2e4f0fb5bf4902e51d3ec7789593e6bb/pkg/kv/kvclient/kvcoord/dist_sender.go#L214)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Why do we need this when we already have distsender.rangefeed.catchup_ranges? Do we expect this to be any different than distsender.rangefeed.total_ranges - distsender.rangefeed.catchup_ranges? If so, why, and maybe we should fix that instead?
</blockquote></details>

You're right... Removed it... I think I had it as a counter at some point; but switching back to gauge made it pretty useless.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 370 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109346#-Ncvh_c95J_pmXaYJJUW:-NcwIwEzDMipgBFn31Sx:b-cjl8b0) ([raw file](https://github.com/cockroachdb/cockroach/blob/23b97a1b2e4f0fb5bf4902e51d3ec7789593e6bb/pkg/kv/kvclient/kvcoord/dist_sender.go#L370)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

This will break when we remove a reason. Consider using a map instead, which also removes the need for `NumRangeFeedRetryErrors` and associated logic.
</blockquote></details>

First, I unfortunately cannot use map -- metrics registry does not support that.  Either each retry
reason has to be spelled out in a struct map... or you have to use array.

Second, you can't (or I should say, you shouldn't) just delete enum value -- just like deleting any other field
you should "reserve" that value.  But you do bring up a good point that when we reserve a value (because of deletion), the map indexes are no longer contiguous.

I've made some changes here.  First, I added another change to modify metrics registry to support slices.
For the life of me, I don't understand why we had this restriction (no slices) in the first place.
This made it much easier to generate slice of counters here (w/out relying on `NumRangeFeedRetryErrors` constant).

Second, I introduced a helper struct along with accessor method to hold these counters.
I added comments to clarify why we need this indirection.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109346#-Ncve024BlQS3rfBqgZL:-NcwxzIJBwBtunpUR_CJ:b-tdhzhe) ([raw file](https://github.com/cockroachdb/cockroach/blob/23b97a1b2e4f0fb5bf4902e51d3ec7789593e6bb/pkg/kv/kvclient/kvcoord/dist_sender.go#L371)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Should we strip the reason_ prefix here? Also, we may want to add a note on `RangeFeedRetryError_Reason` that the reason names should be stable because they are exposed via metric names.
</blockquote></details>

Yes; done.
And done.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 372 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109346#-NcveOc2BvcAOYCpNdJb:-NcwyI7-18fH9M_5XmTX:b-ij52q3) ([raw file](https://github.com/cockroachdb/cockroach/blob/23b97a1b2e4f0fb5bf4902e51d3ec7789593e6bb/pkg/kv/kvclient/kvcoord/dist_sender.go#L372)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

What about retries due to e.g. connection failures and other errors? Should those be included here too? We'd want this to add up to distsender.rangefeed.restart_ranges, right?

Also, nit: "number of rangefeed retries". It's not the number of ranges, it's the number of retried errors.
</blockquote></details>

Rephrased comment -- it was "fat finger" copy pasta.

Initially, I wasn't planning to handle all errors, but okay -- more metrics added.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go` line 372 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109346#-NcvjchT4tnOqsuTIs18:-NcxgP9WCNlrMTVKeIY_:b2nbgc7) ([raw file](https://github.com/cockroachdb/cockroach/blob/23b97a1b2e4f0fb5bf4902e51d3ec7789593e6bb/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L372)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

The rangefeed protocol sends an empty checkpoint precisely to signal completion of the catchup scan, so the non-empty bit here seems wrong.

https://github.com/cockroachdb/cockroach/blob/b35afe9031b8acc917551c293bcafac253970634/pkg/kv/kvserver/rangefeed/processor.go#L393-L398
</blockquote></details>

Perhaps; but we never released catchup scan reservation when receiving empty checkpoint:
```
if !t.ResolvedTS.IsEmpty() && active.catchupRes != nil {  
  active.releaseCatchupScan()  
}
```
That code existed since... forever.

**Review by aliher1911 — CHANGES_REQUESTED** [review]
Overall looks workable with some nits about documenting it.

The part about enabling slices in metrics makes me uneasy as we are removing assertion. Maybe split that out in separate commit in this PR?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109346#-:-NdFMTFwA46bNmP0VHEH:b-c9nsil)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @erikgrinaker, and @miretskiy)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go` line 372 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109346#-NcvjchT4tnOqsuTIs18:-NdBjyB158FkX5CIdDv2:biq1qid) ([raw file](https://github.com/cockroachdb/cockroach/blob/23b97a1b2e4f0fb5bf4902e51d3ec7789593e6bb/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L372)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Perhaps; but we never released catchup scan reservation when receiving empty checkpoint:
```
if !t.ResolvedTS.IsEmpty() && active.catchupRes != nil {  
  active.releaseCatchupScan()  
}
```
That code existed since... forever.
</blockquote></details>

I checked the history and we added catchup scan metric with this condition in 2022 (https://github.com/cockroachdb/cockroach/pull/77711) but there's no justification on why we filter empty checkpoint which is specifically meant to indicate end of catch up as pointed above.

Adding limiter was a subsequent commit. Maybe that's the reason no one payed attention?

This check is deferring throttling to the next emitted checkpoint. It was likely negligible with 200ms interval, but if we want to bump it, then I think we won't see a checkpoint for a bit.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go` line 374 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109346#-NdFBKurBhnEVYN9VHAN:-NdFBKurBhnEVYN9VHAO:b-417w9i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef0e5caa4424468a8107bb6100c38e86e8c7306a/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L374)):*
> ```Go
> 	// It is released when this stream receives first non-empty checkpoint
> 	// (meaning: catchup scan completes).
> 	catchupRes catchupAlloc
> ```

I think this struct is becoming hairy and the comment about thread safe `partialRangeFeed` is making it worse. In fact it now has two parts, one is partial range feed under mutex, and another which is state that is maintained explicitly for `singleRangeFeed`.

Unsafe part is used within a switch on the event type and the other is for `onRangeEvent` which has its own switch on type internally.
It looks like an unfortunate side effect of moving the state from `singleRangeFeed` out to be able to do cleanups. And unsafe part is safe by convention that it is only ever used by creator of the struct or by work loop (also by mux range feed work loop).

If we can't keep them separate at least we should call it out.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go` line 511 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109346#-NdFGfeWBTarW3O_m_iA:-NdFGfeWBTarW3O_m_iB:b-iu93xq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef0e5caa4424468a8107bb6100c38e86e8c7306a/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L511)):*
> ```Go
> }
> 
> // partialRangeFeed establishes a RangeFeed to the range specified by desc. It
> ```

nit: Comment seem out of date as desc is not passed since 2018. We now use token as a destination to establish RangeFeed.
Worth updating since we are changing signature here.
___
*[`pkg/util/metric/registry.go` line 256 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109346#-NdFLMxd573UryOvLIc2:-NdFLMxd573UryOvLIc3:b67d14k) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef0e5caa4424468a8107bb6100c38e86e8c7306a/pkg/util/metric/registry.go#L256)):*
> ```Go
> 
> 	switch fieldType.Kind() {
> 	case reflect.Array, reflect.Slice:
> ```

Is there any rationale why we explicitly forbid slices, did we try to avoid reference types and keep everything by value?

**Review by erikgrinaker — APPROVED** [review]
Catchup scan parts LGTM, but I agree with Oleg, let's split off the metrics changes to a separate PR. The slice stuff needs a bit closer attention, and we may want to backport this in which case we want to keep changes separate and focused.

> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109346#-:-NdVOXFL7WYUSx7yMSUR:b23mju6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @ericharmeling, and @miretskiy)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 386 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109346#-NdVP5DY0U5lu2G_W13S:-NdVP5DZ67hc44BCYISY:bupjs0j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef0e5caa4424468a8107bb6100c38e86e8c7306a/pkg/kv/kvclient/kvcoord/dist_sender.go#L386)):*
> ```Go
> 		RetryErrors:            retryCounters,
> 		Stuck:                  metric.NewCounter(retryMeta("stuck")),
> 		SendErrors:             metric.NewCounter(retryMeta("send error")),
> ```

nit: this will be formatted as "send error error".
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go` line 372 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109346#-NcvjchT4tnOqsuTIs18:-NdVPpIw0maI05q8yx1Q:bgx3eiv) ([raw file](https://github.com/cockroachdb/cockroach/blob/23b97a1b2e4f0fb5bf4902e51d3ec7789593e6bb/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L372)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

I checked the history and we added catchup scan metric with this condition in 2022 (https://github.com/cockroachdb/cockroach/pull/77711) but there's no justification on why we filter empty checkpoint which is specifically meant to indicate end of catch up as pointed above.

Adding limiter was a subsequent commit. Maybe that's the reason no one payed attention?

This check is deferring throttling to the next emitted checkpoint. It was likely negligible with 200ms interval, but if we want to bump it, then I think we won't see a checkpoint for a bit.
</blockquote></details>

On master, this will now be every 3 seconds, which is fairly significant. We should release the catchup scan semaphore as soon as we receive a checkpoint, empty or otherwise. We can either fix that here or in a separate PR, but we should fix it.

**Review by miretskiy — COMMENTED** [review]
Ack re metrics.  I actually meant to do that but accidentally committed together.  Thanks for bringing this up.
I did some archeological digging to determine why we supported arrays vs both arrays and slices.  See newly added commit for explanation.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109346#-:-NdjsVTI9nMoNguSQ-LU:b9e816w)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @ericharmeling, and @erikgrinaker)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go` line 372 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109346#-NcvjchT4tnOqsuTIs18:-NdjuoIKAeWBD5_T-RSe:b-c5nd2z) ([raw file](https://github.com/cockroachdb/cockroach/blob/23b97a1b2e4f0fb5bf4902e51d3ec7789593e6bb/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L372)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

On master, this will now be every 3 seconds, which is fairly significant. We should release the catchup scan semaphore as soon as we receive a checkpoint, empty or otherwise. We can either fix that here or in a separate PR, but we should fix it.
</blockquote></details>

Okay; i'm convinced it's safe to drop this restriction; and I know we handle 0 ts on the changefeed side anyway.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go` line 374 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109346#-NdFBKurBhnEVYN9VHAN:-NdjvKQg0mkISiTO9H_A:b45gnr4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef0e5caa4424468a8107bb6100c38e86e8c7306a/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L374)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

I think this struct is becoming hairy and the comment about thread safe `partialRangeFeed` is making it worse. In fact it now has two parts, one is partial range feed under mutex, and another which is state that is maintained explicitly for `singleRangeFeed`.

Unsafe part is used within a switch on the event type and the other is for `onRangeEvent` which has its own switch on type internally.
It looks like an unfortunate side effect of moving the state from `singleRangeFeed` out to be able to do cleanups. And unsafe part is safe by convention that it is only ever used by creator of the struct or by work loop (also by mux range feed work loop).

If we can't keep them separate at least we should call it out.
</blockquote></details>

I really can't disagree w/ you.  
I tried to do a bit of a cleanup, by introducing mutable/immutable structs, etc.
I also tried to use atomics and avoid mutex altogether.  Turns out, mutex was cheaper.\
So, I understand what you mean; I decided to punt on this for now, but I have updated comments,
including additional comments on the mutex and why it's not that scary.

Let me know if you think that's okay, @aliher1911 and if not, let me know and I'll try to do something else.

```
name                     old time/op    new time/op    delta
ActiveRangeFeedState-10    34.9ns ± 1%    47.8ns ± 4%  +37.01%  (p=0.000 n=9+10)
```
___
*[`pkg/util/metric/registry.go` line 256 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109346#-NdFLMxd573UryOvLIc2:-NdjtVWv7QfvR_z0PRG5:b44j6ra) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef0e5caa4424468a8107bb6100c38e86e8c7306a/pkg/util/metric/registry.go#L256)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Is there any rationale why we explicitly forbid slices, did we try to avoid reference types and keep everything by value?
</blockquote></details>

I've created new commit explaining why.  I don't think that's the rationale because regardless of array vs slice, they are *not* added directly; instead they are expanded to add their values anyway.  So, as far as I can tell this restriction was superfluous.

**Review by aliher1911 — APPROVED** [review]
👍

**Review by erikgrinaker — APPROVED** [review]
>Ack re metrics.

Well, the metrics are still added in the same commit as the pacing, and the metrics need the slice support, so this still sort of hampers targeted backportability -- I'd prefer to separate them out, but your call.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109346#-:-NdoDyD9-GDAL0wCbv7g:bhqm4hi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @ericharmeling)

**Comment by miretskiy** [comment]
> > Ack re metrics.
> 
> Well, the metrics are still added in the same commit as the pacing, and the metrics need the slice support, so this still sort of hampers targeted backportability -- I'd prefer to separate them out, but your call.
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109346#-:-NdoDyD9-GDAL0wCbv7g:bhqm4hi)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @ericharmeling)

Sorry, you're right -- I misunderstood what you meant.  Took a bit of git surgery, but I've split commits.
I'm keeping top level PR description unchanged (because it's a union of all 3 commits), but each commit description
has been updated.

I'm still pretty much 100% sure that the whole thing is safe to backport; but let's hedge anyway.

**Pull request merged**
