### PR TITLE
roachtest: extract logger into a subpackage

### PR DESCRIPTION
**Pull request by tbg**
- roachtest: rename clusterI -> Cluster
- roachtest: extract logger to its own package

Release note: None

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
Fully on board with extracting the roachtest machinery out to a package that tests import. However, I wonder if we might want to have a simple `roachtest` package with `Logger` directly beneath it, for ergonomics, instead of having to import all sorts of subpackages.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66365#-:-MbzUURf3C0KuC1et2Mu:b9ktsbs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

**Review by tbg — COMMENTED** [review]
You mean starting a `roachtest` package that has all of the things we're going to pull out, instead of smaller packages? That could be ok too, but I'm less sure - there is a surprising amount of stuff, none of it really tested, and the logger is enough code for its own package with its own tests. I'm also not sure that ergonomics are much better, as the testing code rarely ever has to spell out the type. Anyway, let's see! This is not chiseled in stone.

TFTR!
bors r=erikgrinaker

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66365#-:-Mc5kL6xAtixyy6n6Z0b:b-2zdavn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

**Comment by tbg** [comment]
Lint failure snuck in under me. I think this next one is good now though

 bors r=erikgrinaker

**Comment by tbg** [comment]
Wake up bors
bors r=erikgrinaker

**Pull request merged**
