### PR TITLE
[dnm] roachtest: add helper to set up jaeger and store data as artifacts

### PR DESCRIPTION
**Pull request by tbg**
image

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
Wondering if this is useful. cc @andreimatei @nvanbenschoten @cockroachdb/test-eng

**Review by nvb — APPROVED** [review]
:lgtm: It looks very useful!

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65844#-:-Map-TRoA1rAKb8Db-bS:b-ubf8p9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/cmd/roachtest/kv.go, line 237 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65844#-Maoz57gCYOuL_KxTO73:-Maoz57gCYOuL_KxTO74:bevvfje) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3d043de2675a650b14406ce12c0e67df8267c5a/pkg/cmd/roachtest/kv.go#L237)):*
> ```
> // The UI can be accessed on n1's port 16686.
> ```
Want to log this fact?
___
*[pkg/cmd/roachtest/kv.go, line 263 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65844#-MaozMhQ9ZLgugw76q-x:-MaozMhQ9ZLgugw76q-y:bbmyjjl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3d043de2675a650b14406ce12c0e67df8267c5a/pkg/cmd/roachtest/kv.go#L263)):*
> ```Go
> 	m.Go(func(ctx context.Context) error {
> 		err := c.RunE(ctx, c.Node(1), `SPAN_STORAGE_TYPE=badger BADGER_EPHEMERAL=false \
> BADGER_DIRECTORY_VALUE=logs/jaeger.badger/data BADGER_DIRECTORY_KEY=logs/jaeger.badger/key \
> ```

Is the logs directory the right thing to use? My concern is that this will be in the root filesystem, which is usually 10GB large on these systems. Meanwhile, the SSD mounted at /mnt/data1 is usually 375GB large. When you tested this out over the course of an hour, did you happen to take a look at how large the directory got?

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65844)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/cmd/roachtest/kv.go, line 263 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65844#-MaozMhQ9ZLgugw76q-x:-Mb0qoEQDlft9uFkzX9Y:b-ykfsy8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3d043de2675a650b14406ce12c0e67df8267c5a/pkg/cmd/roachtest/kv.go#L263)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is the logs directory the right thing to use? My concern is that this will be in the root filesystem, which is usually 10GB large on these systems. Meanwhile, the SSD mounted at /mnt/data1 is usually 375GB large. When you tested this out over the course of an hour, did you happen to take a look at how large the directory got?
</blockquote></details>

I'll take a look. I think it makes sense to decide on a case-by-case basis. When we're debugging a short test that doesn't push many ops/sec, the log dir is practical because then the test harness fetches the data for us even when the cluster is destroyed, without having to add special fetching logic. If we wanted to check this in as always-on for some tests (maybe we want that, right?) I agree that we should steer clear of the boot partition.

**Review by tbg — COMMENTED** [review]
Just ran the contention test again:

```
ubuntu@tobias-1622462130-01-n5cpu4-0001:/mnt/data1/jaeger.badger$ du -sch
37G	.
37G	total
```

Pretty hefty, but I guess we expected that.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65844#-:-Mb1cWIe33PsaCdyHKdg:b-7w1w13)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

**Comment by tbg** [comment]
Posting for later

```go
	// Convenient copy-paste for local jaeger instance.
	const _ = `
docker run -d \
  --name jaeger \
  -v "$(pwd):/dump" \
  -e COLLECTOR_ZIPKIN_HOST_PORT=:9411 \
  -e SPAN_STORAGE_TYPE=badger \
  -e BADGER_EPHEMERAL=false \
  -e BADGER_DIRECTORY_VALUE=/dump/data \
  -e BADGER_DIRECTORY_KEY=/dump/key \
  -p 5775:5775/udp \
  -p 6831:6831/udp \
  -p 6832:6832/udp \
  -p 5778:5778 \
  -p 16686:16686 \
  -p 14268:14268 \
  -p 14250:14250 \
  -p 9411:9411 \
  jaegertracing/all-in-one:1.23`
```

**Pull request closed without merging**
