### PR TITLE
libroach: automatically compact sstables with any range deletions

### PR DESCRIPTION
**Pull request by petermattis**
Add a table property collector which marks any sstable containing a
range tombstone as requiring compaction. This ensures that the disk
space for deleted data is reclaimed promptly.

Change `RocksDBMap.Clear` to force a flush after adding a range
tombstone. Combined with the compaction of any sstable containing a
range tombstone, this ensures that space in the temporary storage
directory is reclaimed quickly.

Release note (bug fix): Ensure that space in the temporary storage
directory is reclaimed more promptly.

### CODE REVIEW

**Comment by petermattis** [comment]
This is based on https://github.com/cockroachdb/cockroach/pull/31975, but without any attempt to remove the compaction queue. I'd like to add a test before this merges.

**Review by benesch — APPROVED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32385)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[c-deps/libroach/include/libroach.h, line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32385#-LRMrRHu9oDKbXd5brwg:-LRMrRHu9oDKbXd5brwh:bz7xt0m) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6aeefc52e3ead00cf3c5c67d1e370f77551b5cc/c-deps/libroach/include/libroach.h#L136)):*
> ```objc
> // Disable/enable automatic compactions. Automatic compactions are
> // enabled by default. Disabling is provided for testing purposes so
> // that automatic compactions do not interfere with test expecations.
> ```

"expecations"
___
*[pkg/storage/engine/disk_map.go, line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32385#-LRMrhho4gFKYi1q3mwk:-LRMrhho4gFKYi1q3mwl:b19wd9s) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6aeefc52e3ead00cf3c5c67d1e370f77551b5cc/pkg/storage/engine/disk_map.go#L188)):*
> ```Go
> 	// range tombstone is pushed to disk which will kick off compactions that
> 	// will eventually free up the deleted space.
> 	return r.store.Flush()
> ```

Why in RocksDBMap.Clear but not elsewhere?

**Review by benesch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32385)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[c-deps/libroach/options.cc, line 198 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32385#-LRMrxtn3hAwIcNgApWH:-LRMrxtn3hAwIcNgApWI:b-aekcef) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6aeefc52e3ead00cf3c5c67d1e370f77551b5cc/c-deps/libroach/options.cc#L198)):*
> ```cpp
>   // deletions.
>   options.table_properties_collector_factories.emplace_back(
>       new DeleteRangeTblPropCollectorFactory());
> ```

nitty nit: this should be consistent with the time bound property collector installation. Maybe these table properties collectors should live in a "tableprops.h" header? But I think giving the time bound one its own file while the delete range one gets stuffed into options.cc is sotra weird.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32385)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[c-deps/libroach/options.cc, line 198 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32385#-LRMrxtn3hAwIcNgApWH:-LRN4vYt3FILsUE5fiQH:b-mchowk) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6aeefc52e3ead00cf3c5c67d1e370f77551b5cc/c-deps/libroach/options.cc#L198)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

nitty nit: this should be consistent with the time bound property collector installation. Maybe these table properties collectors should live in a "tableprops.h" header? But I think giving the time bound one its own file while the delete range one gets stuffed into options.cc is sotra weird.
</blockquote></details>

I've moved `timebound.{cc,h}` to `table_props.{cc,h}` and moved the delete range property collector there. PTAL.
___
*[c-deps/libroach/include/libroach.h, line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32385#-LRMrRHu9oDKbXd5brwg:-LRN4ZkD3QDnA0wW5KpO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6aeefc52e3ead00cf3c5c67d1e370f77551b5cc/c-deps/libroach/include/libroach.h#L136)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

"expecations"
</blockquote></details>

Done.
___
*[pkg/storage/engine/disk_map.go, line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32385#-LRMrhho4gFKYi1q3mwk:-LRNDSO45EIcu_u2052t:bwa3gg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6aeefc52e3ead00cf3c5c67d1e370f77551b5cc/pkg/storage/engine/disk_map.go#L188)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Why in RocksDBMap.Clear but not elsewhere?
</blockquote></details>

Where else are you thinking? I'm intentionally punting on trying to get rid of the compaction queue in this PR.

**Review by benesch — APPROVED** [review]
:lgtm: 

Are you planning to add a test when you remove the compaction queue?

> Reviewed 1 of 1 files at r2, 2 of 5 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32385#-:-LRNHwNk1Ibvbheg6SlQ:bsbiktv)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[c-deps/libroach/db.cc, line 741 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32385#-LRNHqYz8X5l-3D9Z3Yt:-LRNHqYz8X5l-3D9Z3Yu:b-82oqa1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e740d2c9b7fe356db7c2c3f76e0907adfa55a776/c-deps/libroach/db.cc#L741)):*
> ```cpp
>   // by the time bounded iterator optimization.
>   options->table_properties_collector_factories.emplace_back(DBMakeTimeBoundCollector());
>   // TODO(peter): DeleteRangeCollector
> ```

Ping.
___
*[pkg/storage/engine/disk_map.go, line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32385#-LRMrhho4gFKYi1q3mwk:-LRNHaRFEJJMnqZwKbDf:btdxs07) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6aeefc52e3ead00cf3c5c67d1e370f77551b5cc/pkg/storage/engine/disk_map.go#L188)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Where else are you thinking? I'm intentionally punting on trying to get rid of the compaction queue in this PR.
</blockquote></details>

Oh, I see, the idea is that everywhere else the compaction queue will trigger the flush? Makes sense to me.

**Review by petermattis — COMMENTED** [review]
>  Are you planning to add a test when you remove the compaction queue?

I'm still planning to add a test before merging. Shouldn't take long as soon as I have a free hour.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32385#-:-LRNIesHEzBPGNNtnhWR:bnnd4a8)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[c-deps/libroach/db.cc, line 741 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32385#-LRNHqYz8X5l-3D9Z3Yt:-LRNIW4dDiTWW8cK5tOu:b-fi9qgn) ([raw file](https://github.com/cockroachdb/cockroach/blob/e740d2c9b7fe356db7c2c3f76e0907adfa55a776/c-deps/libroach/db.cc#L741)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Ping.
</blockquote></details>

Heh, that's why I added that TODO. Fixed.
___
*[pkg/storage/engine/disk_map.go, line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32385#-LRMrhho4gFKYi1q3mwk:-LRNIYgy8v5EpzC-2uWw:b-9v69e1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6aeefc52e3ead00cf3c5c67d1e370f77551b5cc/pkg/storage/engine/disk_map.go#L188)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Oh, I see, the idea is that everywhere else the compaction queue will trigger the flush? Makes sense to me.
</blockquote></details>

Yes, the compaction queue will trigger the flush elsewhere. And it will do a compaction as well which will be less necessary, but oh well.

**Review by benesch — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32385)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by petermattis** [comment]
@benesch Added the promised test. It fails without the delete-range prop collector, or if I disable the flush in `RocksDBMap.Clear`. PTAL.

**Review by benesch — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32385#-:-LRSHSIh4OFqUJQMInMT:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by petermattis** [comment]
bors r=benesch

**Comment by petermattis** [comment]
Hello, bors. Are you there?

bors r=benesch

**Pull request merged**
