### PR TITLE
colexec: switch tests from using subtests to logging the info

### LINKED ISSUE #50501: colexec: excessive use of sub-tests
The following tests use too many sub-tests:

- TestMergeJoiner
- TestExternalHashJoiner
- TestExternalSort
- TestHashJoiner
- TestWindowFunctions

The problem specifically is an invalid trade-off between "complexity of 1 sub-test" and "number of sub-tests". Each sub-test has initialization, logging and synchronization overheads. These overheads are only OK if EITHER 1) there are only few sub-tests in the tests; OR 2) the complexity of each sub test is large enough to offset the overheads.

(In addition, the large log file makes Teamcity build logs unpleasant to navigate.)

As it stands we see thousands of lines of output in the log and an execution time in excess of 20s for the entire package, where the same execution without sub-tests would be much faster.

Suggestion: instead of
```go
   t.Run(fmt.Sprintf("details", ...), func(t *testing.T) {
      ...
   })
```

do:
```go
   func(t *testing.T) {
      log.Infof("testing: details", ...)
      ...
   }(t)
``` 

(prefer `log.Infof` to `t.Logf`, so that we can use `log.Scope`).

cc @asubiotto @yuzefovich for triage.

### PR DESCRIPTION
**Pull request by yuzefovich**
This change reduces the output size with `-test.v` option from 23k to
500, but there is no visible change in the running time of the whole
package - it still takes about 20s with disabled batch size
randomization.

Fixes: #50501.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I think what we're giving up is an ability to run a particular subtest, with something like `make test PKG=./pkg/sql/colexec TESTS=TestMergeJoiner/inner_join_no_nulls/batchSize=1...`, however, I haven't been using this ability actually - my workload has always been modifying the `runTests` test harness to comment out undesired configs as well as commenting out undesirable unit test cases, but I know that Alfonso seems to have been using this ability. I'm ok with both merging this PR and with keeping the existing state of affairs.

**Comment by knz** [comment]
Thanks for trying the change out. 
Given the performance difference then I wouldn't push further to change the structure of the test (sub-test vs 1 test).

However, what about the logging? Is it possible to shorten the logging without changing the test structure too much?

(A strawman: collapse certain sub-tests together?)

**Comment by yuzefovich** [comment]
> However, what about the logging? Is it possible to shorten the logging without changing the test structure too much?

Hm, I think the biggest problem with amount of logging we have is that we're using `runTests` test harness from `colexec/utils_test.go` which multiplies each of the unit test by a factor of 9 (unless some things are skipped), and collapsing subtests in there into one would basically get reduced to what I have in this PR. Basically, what I'm saying is that I don't see a middle ground where we can reduce the amount of logging and keep the ability to run subtests. Or am I missing something? Maybe @jordanlewis has ideas?

**Comment by jordanlewis** [comment]
What logging is done right now? If you disable the logging, does the test still take so long to run?

As an alternative, could we change `runTests` to not use subtests, but permit selective disabling of configs using an environment variable?

**Comment by yuzefovich** [comment]
> What logging is done right now? If you disable the logging, does the test still take so long to run?

There is no logging per se, simply having a bunch of subtests "logs" the subtest name, so there is no way to disable that "logging" without simply reducing the number of subtests.

> As an alternative, could we change `runTests` to not use subtests, but permit selective disabling of configs using an environment variable?

It is an interesting idea, and I think it could work. Basically we would proceed forward with this PR and then add those env vars. However, I personally don't use the selective disablement myself, so I'd like to leave that task to someone who is actually using those "selectors".

**Comment by jordanlewis** [comment]
> There is no logging per se, simply having a bunch of subtests "logs" the subtest name, so there is no way to disable that "logging" without simply reducing the number of subtests.

Okay - my question still stands, if you delete all of the subtests without re-introducing the logs, do you get any performance improvements?

**Comment by knz** [comment]
For clarity here the primary goal is to make logs smaller so that team city gets an easy time processing them (this improves TC UI response, troubleshooting failing CI runs etc). 

The raw command-line perf of the test may not be relevant nor measurable.
-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by yuzefovich** [comment]
> my question still stands, if you delete all of the subtests without re-introducing the logs, do you get any performance improvements?

Misunderstood your question initially. No, commenting out all `log.Infof` calls I added in this PR in place of subtests doesn't give any performance benefits - it still takes about 20s for the whole package.

So the way I see it, we want:
1. reduce the amount of logging "unconditional" logging done into the stdout, which is what this PR does
2. and it might be nice to preserve the ability to run a subset of unit tests (this can probably be done via environment variables, as Jordan suggested). I think Alfonso mentioned he uses that ability, so I'd leave the implementation to him to tailor to his needs.

**Comment by yuzefovich** [comment]
@jordanlewis friendly ping

**Comment by jordanlewis** [comment]
One last q - would it be possible to just change the "big tests" (merge joiner, hash joiner, etc) that were complained about and not all of them?

**Comment by yuzefovich** [comment]
I don't think so - the main culprit is the `runTests` test harness, if we don't change that, we won't see much benefit. (I'm also not sure how/what you would change only in the big tests to reduce their footprint apart from simply removing some test cases which is a no-no.)

**Comment by yuzefovich** [comment]
@jordanlewis @asubiotto we should decide on how to proceed with this PR. I'm ok with either closing it or merging as-is.

**Comment by asubiotto** [comment]
I think we can go ahead with merging this PR since it solves the unconditional logging problem that slows TC down at the expense of slightly worse testing ergonomics. If the latter becomes a problem, we can revisit ways to make this better.

**Comment by yuzefovich** [comment]
@jordanlewis I'm leaning towards merging this as well since it might help navigate the logs on TeamCity for other teams. WDYT?

**Review by jordanlewis — APPROVED** [review]

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by yuzefovich** [comment]
Seems like a weird infra flake (using 20.1.4 binary for roachtests).

bors r+

**Pull request merged**
