### PR TITLE
sql: miscellaneous SHOW improvements, part 3

### PR DESCRIPTION
**Pull request by knz**
The main changes in this patchset are all geared towards making SHOW CREATE better.
Outline:
- INTERLEAVE now supports interleaving across databases, and SHOW CREATE reports this properly.
- fewer accesses to the descriptors for various SHOW statements (other than SHOW CREATE)
- major refactoring of SHOW CREATE, with more useful (and more correct) behavior for tables with FK or INTERLEAVE dependencies over other databases.
- new vtable `crdb_internal.create_statements` that serves as foundation for SHOW CREATE.

For Docs: the output of SHOW CREATE may have changed slightly, so if there are any examples in docs they need to be updated. In particular the output is now better when there are cross-database FK or INTERLEAVE dependencies.

### CODE REVIEW

**Comment by knz** [comment]
rebased; ptal.

**Comment by mjibson** [comment]
Does it make sense to make the system and any other internal tables all non-quoted, so users can use them as they would expect? Otherwise this behavior feels really surprising.

---

Review status: 0 of 24 files reviewed at latest revision, 12 unresolved discussions.

---

*[pkg/sql/crdb_internal.go, line 793 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938#-KpH3yGGJEgbnNGT1Hvk:-KpH3yGGJEgbnNGT1Hvl:bpyv6j) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbe5a7e139ba498fe4114c4806beafd8ec2e8e4a/pkg/sql/crdb_internal.go#L793)):*
> ```Go
> 		return forEachTableDescAll(ctx, p, prefix,
> 			func(db *sqlbase.DatabaseDescriptor, table *sqlbase.TableDescriptor) error {
> 				typeView := parser.NewDString("view")
> ```

Can these be defined somewhere else? Seems wasteful to make them anew each time, unless there's a reason I don't see to do that.

---

*[pkg/sql/show.go, line 262 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938#-KpH-eooXjY1HaKzaba8:-KpH-eooXjY1HaKzaba9:bv4uxh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/380c2d67072cca7871c3ee577abaa318bc88058d/pkg/sql/show.go#L262)):*
> ```Go
> 		return "", err
> 	}
> 	parentDb, err := sqlbase.GetDatabaseDescFromID(ctx, p.txn, parentTable.ParentID)
> ```

Are permissions correctly checked? Or does that happen some time later based on just the table id, which does any needed database checks too?

---

*[pkg/sql/show.go, line 169 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938#-KpH6Z6AIaunNdstamq2:-KpH6Z6AIaunNdstamq3:bng0jjq) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbe5a7e139ba498fe4114c4806beafd8ec2e8e4a/pkg/sql/show.go#L169)):*
> ```Go
> // showTableDetails extracts information about the given table using
> // the given query patterns in SQL. The query pattern must accept
> // three formatting parameters:
> ```

This says three but four are listed below.

---

*[pkg/sql/show_test.go, line 243 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938#-KpH2h3LimXXa0KspONx:-KpH2h3LimXXa0KspONy:b1txfvr) ([raw file](https://github.com/cockroachdb/cockroach/blob/28cd81b6db509c54b3a3a8d976cb093c8431b408/pkg/sql/show_test.go#L243)):*
> ```Go
> 
> 	tests := []string{
> 		`CREATE VIEW %s (i, s, v, t) AS SELECT i, s, v, t FROM d.t`,
> ```

This stuff is in the wrong commit.

---

*[pkg/sql/show_test.go, line 291 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938#-KpH9t0XAiTgzpJJLH5X:-KpH9t0XAiTgzpJJLH5Y:b-z5kaj4) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbe5a7e139ba498fe4114c4806beafd8ec2e8e4a/pkg/sql/show_test.go#L291)):*
> ```Go
> 		expected string
> 	}{
> 		{`CREATE VIEW %s AS SELECT i, s, v, t FROM t`,
> ```

These would be easier to read like:

{
  `create view ...`,
  `create view ...`,
},

As is it's hard to match them up.

---

*[pkg/sql/logictest/testdata/logic_test/crdb_internal, line 84 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938#-KpH1Jvqrkf9rxZUgOZH:-KpH1Jvqrkf9rxZUgOZI:bpelp84) ([raw file](https://github.com/cockroachdb/cockroach/blob/2774384f28a393e3d71f61a34bf1c06bb7ba87d2/pkg/sql/logictest/testdata/logic_test/crdb_internal#L84)):*
> ```
> 
> query error pq: foo
> SELECT crdb_internal.force_error('', 'foo')
> ```

Could you add a test for the non empty string case for the first argument?

---

*[pkg/sql/parser/eval.go, line 2651 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938#-KpH1P1lsZh-repd-CeN:-KpH1P1lsZh-repd-CeO:ba4dmxo) ([raw file](https://github.com/cockroachdb/cockroach/blob/2774384f28a393e3d71f61a34bf1c06bb7ba87d2/pkg/sql/parser/eval.go#L2651)):*
> ```Go
> 		// If we are facing an explicit error, propagate it unchanged.
> 		fName := expr.Func.String()
> 		if fName == `crdb_internal.force_error` {
> ```

Do we need to worry about normalization here if a user used caps to spell any of this?

---

*[pkg/ccl/sqlccl/load.go, line 76 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938#-KpGpbvZpFLJ3FavsTap:-KpGpbvZpFLJ3FavsTaq:bzg2uye) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2dcf447d811993d247e91b92c729199dee609b2/pkg/ccl/sqlccl/load.go#L76)):*
> ```Go
> 			d.descriptor
> 		FROM system.namespace n INNER JOIN system.descriptor d ON n.id = d.id
> 		WHERE n."parentID" = $1
> ```

Why does this need to be quoted? (This may be related to me not fully understanding the point of this commit.)

---

*[pkg/server/admin.go, line 849 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938#-KpGqXfgWyPLeu7ho-61:-KpGqXfgWyPLeu7ho-62:bcvceun) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2dcf447d811993d247e91b92c729199dee609b2/pkg/server/admin.go#L849)):*
> ```Go
> 	// Query database.
> 	query := makeSQLQuery()
> 	query.Append(`SELECT key, value, "lastUpdated" FROM system.ui WHERE key IN (`)
> ```

It is really weird that only one column with no special characters needs to be quoted. It's clearly because of the upper case, but will users and us engineers need to correctly quote these columns when we query these tables, or is this being done here for clarity, but it's optional? I feel like few people will remember this rule since it's pretty non-obvious.

---

*[pkg/sql/doc.go, line 82 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938#-KpGsnYSrd5iRYPohWkG:-KpGskazm1XAMO3J86cn:b-ugd9mi) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2dcf447d811993d247e91b92c729199dee609b2/pkg/sql/doc.go#L82)):*
> ```Go
> query:
> 
>   SELECT id FROM system.namespace WHERE "parentID" = 0 AND name = <database-name>
> ```

Ugh. We even have to document this silly quoting stuff? This feels real bad :(

---

*[pkg/sql/sqlbase/structured.go, line 869 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938#-KpGnDLwXBF-hduwerfI:-KpGnDLwXBF-hduwerfJ:b-wl6dw4) ([raw file](https://github.com/cockroachdb/cockroach/blob/30aeef3c778ff6e19b9ab683cb131ee3e2eda1f8/pkg/sql/sqlbase/structured.go#L869)):*
> ```Go
> 			}
> 			if !found {
> 				return errors.Errorf("missing fk back reference to %q@%q from %q@%q",
> ```

Thinking about this: %q is a Go thing, not a SQL thing, but I guess it's better than %s so overall an improvement. Are there cases that %q renders incorrectly that a SQL-informed conversion would render better?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938#-:-KpGrB-UcRjp8y9YJnqG:b4jjik0)*

**Comment by knz** [comment]
Thanks matt for the constructive comments. I have a few responses  already below, and I will address the rest in the code later this week.

> Does it make sense to make the system and any other internal tables all non-quoted, so users can use them as they would expect? Otherwise this behavior feels really surprising.

Yes it would make sense. But it's too late - we can't do that and preserve compatibility with all previously created clusters. Also that discussion belonged to #16884 :)

---

Review status: 0 of 24 files reviewed at latest revision, 11 unresolved discussions, some commit checks pending.

---

*[pkg/sql/parser/eval.go, line 2651 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938#-KpH1P1lsZh-repd-CeN:-KpHAxj4NXSxNUokfvRM:btyoat7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2774384f28a393e3d71f61a34bf1c06bb7ba87d2/pkg/sql/parser/eval.go#L2651)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Do we need to worry about normalization here if a user used caps to spell any of this?
</blockquote></details>

Function names, contrary to identifers, are always pre-normalized.

---

*[pkg/ccl/sqlccl/load.go, line 76 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938#-KpGpbvZpFLJ3FavsTap:-KpHB915kr70XebPqHdf:b4othl7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2dcf447d811993d247e91b92c729199dee609b2/pkg/ccl/sqlccl/load.go#L76)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Why does this need to be quoted? (This may be related to me not fully understanding the point of this commit.)
</blockquote></details>

This commit is part of #16884 - a separate concern.

---

*[pkg/sql/doc.go, line 82 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938#-KpGsnYSrd5iRYPohWkG:-KpHBOr7xkj9uOiHtTaX:bq5kfas) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2dcf447d811993d247e91b92c729199dee609b2/pkg/sql/doc.go#L82)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Ugh. We even have to document this silly quoting stuff? This feels real bad :(
</blockquote></details>

The badness was in creating system tables with non-normalized names... not much we can do about this now.

---

*[pkg/sql/sqlbase/structured.go, line 869 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938#-KpGnDLwXBF-hduwerfI:-KpHBZvJzYuYFpv0A501:b-ti50mq) ([raw file](https://github.com/cockroachdb/cockroach/blob/30aeef3c778ff6e19b9ab683cb131ee3e2eda1f8/pkg/sql/sqlbase/structured.go#L869)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Thinking about this: %q is a Go thing, not a SQL thing, but I guess it's better than %s so overall an improvement. Are there cases that %q renders incorrectly that a SQL-informed conversion would render better?
</blockquote></details>

yes - SQL identifiers do not support \xNN escapes, and %q could produce them. But one would need to be very ... dedicated to achieve such a SQL identifier in practice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938#-:-KpHAYmezpxTHksJb6Wr:b-nn1jjr)*

**Comment by knz** [comment]
Rebased and all comments addressed, PTAL

---

Review status: 0 of 24 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[pkg/sql/crdb_internal.go, line 793 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938#-KpH3yGGJEgbnNGT1Hvk:-KpM1mSejRzrU9l5x00g:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbe5a7e139ba498fe4114c4806beafd8ec2e8e4a/pkg/sql/crdb_internal.go#L793)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Can these be defined somewhere else? Seems wasteful to make them anew each time, unless there's a reason I don't see to do that.
</blockquote></details>

Done.

---

*[pkg/sql/show.go, line 262 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938#-KpH-eooXjY1HaKzaba8:-KpM2AOdTI9ZT7xwZCl3:bwuvn1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/380c2d67072cca7871c3ee577abaa318bc88058d/pkg/sql/show.go#L262)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Are permissions correctly checked? Or does that happen some time later based on just the table id, which does any needed database checks too?
</blockquote></details>

`initialCheck` defined above calls `p.anyPrivilege(desc)` for this purpose.

---

*[pkg/sql/show.go, line 169 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938#-KpH6Z6AIaunNdstamq2:-KpM26Rqv4fsrq4mbRIZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbe5a7e139ba498fe4114c4806beafd8ec2e8e4a/pkg/sql/show.go#L169)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

This says three but four are listed below.
</blockquote></details>

Done.

---

*[pkg/sql/show_test.go, line 243 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938#-KpH2h3LimXXa0KspONx:-KpM3ZF7QeoDgPqynKBB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/28cd81b6db509c54b3a3a8d976cb093c8431b408/pkg/sql/show_test.go#L243)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

This stuff is in the wrong commit.
</blockquote></details>

Done.

---

*[pkg/sql/show_test.go, line 291 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938#-KpH9t0XAiTgzpJJLH5X:-KpM3YGdLandCh2r5b-d:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbe5a7e139ba498fe4114c4806beafd8ec2e8e4a/pkg/sql/show_test.go#L291)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

These would be easier to read like:

{
  `create view ...`,
  `create view ...`,
},

As is it's hard to match them up.
</blockquote></details>

Done.

---

*[pkg/sql/logictest/testdata/logic_test/crdb_internal, line 84 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938#-KpH1Jvqrkf9rxZUgOZH:-KpM6GplqfEiPqNKLZ6C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2774384f28a393e3d71f61a34bf1c06bb7ba87d2/pkg/sql/logictest/testdata/logic_test/crdb_internal#L84)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Could you add a test for the non empty string case for the first argument?
</blockquote></details>

Done.

---

*[pkg/server/admin.go, line 849 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938#-KpGqXfgWyPLeu7ho-61:-KpM2R9nfEXHVUIpaMFf:b-hx1bxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2dcf447d811993d247e91b92c729199dee609b2/pkg/server/admin.go#L849)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

It is really weird that only one column with no special characters needs to be quoted. It's clearly because of the upper case, but will users and us engineers need to correctly quote these columns when we query these tables, or is this being done here for clarity, but it's optional? I feel like few people will remember this rule since it's pretty non-obvious.
</blockquote></details>

IT's not optional. However the good thing is, if you get this wrong it fails in a very obvious way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938#-:-KpM6us1yNLKovVcw-6R:bqtkgl3)*

**Comment by mjibson** [comment]
Review status: 0 of 24 files reviewed at latest revision, 14 unresolved discussions, all commit checks successful.

---

*[pkg/sql/crdb_internal.go, line 801 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938#-KpRKBQeZsuPo2HfRNfU:-KpRKBQeZsuPo2HfRNfV:b5twta7) ([raw file](https://github.com/cockroachdb/cockroach/blob/78347a9b9aa46b50ac4e06ad5b654385d2033746/pkg/sql/crdb_internal.go#L801)):*
> ```Go
> 				deps := make(map[parser.TableName]struct{})
> 				if table.IsView() {
> 					descType = &typeView
> ```

Hmm, I think I made a bad suggestion. I like this less than what was here before. What about `descType = parser.NewDString("view")`. That would prevent both from being created each for loop (like they were initially), but also not add them to the package namespace. I'm getting annoyed at my own bike shedding though, so whatever you want.

---

*[pkg/sql/show_test.go, line 342 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938#-KpRLR1aQO59EaoWAN4q:-KpRLR1aQO59EaoWAN4r:bop8s26) ([raw file](https://github.com/cockroachdb/cockroach/blob/78347a9b9aa46b50ac4e06ad5b654385d2033746/pkg/sql/show_test.go#L342)):*
> ```Go
> 			if create != expect {
> 				t.Fatalf("statement: %s\ngot: %s\nexpected: %s", stmt, create, expect)
> 				return
> ```

No need for this since it's in a subtest.

---

*[pkg/sql/show_test.go, line 359 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938#-KpRLMhl_M2rb_OiNjFr:-KpRLMhl_M2rb_OiNjFs:b-uvz98h) ([raw file](https://github.com/cockroachdb/cockroach/blob/78347a9b9aa46b50ac4e06ad5b654385d2033746/pkg/sql/show_test.go#L359)):*
> ```Go
> 			if create != expect {
> 				t.Errorf("round trip statement: %s\ngot: %s", expect, create)
> 				return
> ```

You can remove this and use just t.Fatalf above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938)*

**Comment by knz** [comment]
Review status: 0 of 24 files reviewed at latest revision, 14 unresolved discussions, all commit checks successful.

---

*[pkg/sql/crdb_internal.go, line 801 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938#-KpRKBQeZsuPo2HfRNfU:-KpVgBs1mkunTDqUCa6s:b-b8xd32) ([raw file](https://github.com/cockroachdb/cockroach/blob/78347a9b9aa46b50ac4e06ad5b654385d2033746/pkg/sql/crdb_internal.go#L801)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Hmm, I think I made a bad suggestion. I like this less than what was here before. What about `descType = parser.NewDString("view")`. That would prevent both from being created each for loop (like they were initially), but also not add them to the package namespace. I'm getting annoyed at my own bike shedding though, so whatever you want.
</blockquote></details>

I think I found a good middle ground :)

---

*[pkg/sql/show_test.go, line 342 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938#-KpRLR1aQO59EaoWAN4q:-KpVgkvw16ei6N9_HYyB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78347a9b9aa46b50ac4e06ad5b654385d2033746/pkg/sql/show_test.go#L342)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

No need for this since it's in a subtest.
</blockquote></details>

Done.

---

*[pkg/sql/show_test.go, line 359 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938#-KpRLMhl_M2rb_OiNjFr:-KpVgkT8lmdz-E-qJPeo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78347a9b9aa46b50ac4e06ad5b654385d2033746/pkg/sql/show_test.go#L359)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

You can remove this and use just t.Fatalf above.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16938)*

**Review by madelynnblue — APPROVED** [review]

**Comment by knz** [comment]
TFYR!

**Pull request merged**
