### PR TITLE
storage: add txn debug names for split/merge, unittest for dist txn cleanup

### PR DESCRIPTION
**Pull request by spencerkimball**
Also, moved initial gossip of store capacity to `client_test.go` setup
for `createTestStore` and fixed associated broken tests.

This PR is exploratory work to address #6693 & #9135

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14375)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/roachpb/data.go, line 931 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14375#-KgAZzgI1bxnCjBDCCuc:-KgAZzgI1bxnCjBDCCud:bzg5p29) ([raw file](https://github.com/cockroachdb/cockroach/blob/98f55e4f471d468e39d3706b6e987488f3b24d60/pkg/roachpb/data.go#L931)):*
> ```Go
> 		t.OrigTimestamp, t.MaxTimestamp, t.WriteTooOld, t.RetryOnPush)
> 	if t.Status != PENDING {
> 		fmt.Fprintf(&buf, " (%d intents)", len(t.Intents))
> ```

is this generally useful, or just when iterating over extant transaction records during startup?

---

*[pkg/storage/client_split_test.go, line 1823 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14375#-KgAu000_LSLd5AXKE0p:-KgAu000_LSLd5AXKE0q:bv6ltle) ([raw file](https://github.com/cockroachdb/cockroach/blob/98f55e4f471d468e39d3706b6e987488f3b24d60/pkg/storage/client_split_test.go#L1823)):*
> ```Go
> 			}
> 			lastRangeCount = rangeCount
> 		case <-time.After(10 * time.Millisecond):
> ```

why not keep the old stricter logic?

---

*[pkg/storage/client_split_test.go, line 1860 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14375#-KgAuBbHGuWgQBFuuiJ7:-KgAuBbHGuWgQBFuuiJ8:b-m7jnwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/98f55e4f471d468e39d3706b6e987488f3b24d60/pkg/storage/client_split_test.go#L1860)):*
> ```Go
> 	store := createTestStoreWithConfig(t, stopper, storeCfg)
> 
> 	// Split at "a".
> ```

this comment isn't very helpful

---

*[pkg/storage/client_split_test.go, line 1868 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14375#-KgAuKDmP1DEgSvqvLZQ:-KgAuKDmP1DEgSvqvLZR:bgsto5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/98f55e4f471d468e39d3706b6e987488f3b24d60/pkg/storage/client_split_test.go#L1868)):*
> ```Go
> 	lhs := store.LookupReplica(roachpb.RKey("a"), nil)
> 
> 	// Split at "b".
> ```

ditto

also, why are two splits required? isn't one enough?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14375)*

**Comment by spencerkimball** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/roachpb/data.go, line 931 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14375#-KgAZzgI1bxnCjBDCCuc:-KgF4IVtMO_bcBydkkUp:b-7l03so) ([raw file](https://github.com/cockroachdb/cockroach/blob/98f55e4f471d468e39d3706b6e987488f3b24d60/pkg/roachpb/data.go#L931)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

is this generally useful, or just when iterating over extant transaction records during startup?
</blockquote></details>

I think it is generally useful. I'm going to further change it to print only if the number of intents is >= 1.

---

*[pkg/storage/client_split_test.go, line 1823 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14375#-KgAu000_LSLd5AXKE0p:-KgF4rup3GBAJtv5dCw8:bns74cd) ([raw file](https://github.com/cockroachdb/cockroach/blob/98f55e4f471d468e39d3706b6e987488f3b24d60/pkg/storage/client_split_test.go#L1823)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why not keep the old stricter logic?
</blockquote></details>

Because of the changes to the store test harness to ensure that the store capacity is gossiped. There is some non-determinism in the test which makes it flaky. This change is verifying the correct behavior and is immune now to timing issues.

---

*[pkg/storage/client_split_test.go, line 1860 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14375#-KgAuBbHGuWgQBFuuiJ7:-KgF5B4kAHOdUgZptjuT:b-skx4ec) ([raw file](https://github.com/cockroachdb/cockroach/blob/98f55e4f471d468e39d3706b6e987488f3b24d60/pkg/storage/client_split_test.go#L1860)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this comment isn't very helpful
</blockquote></details>

I disagree. It's serving to visually break up the flow of statements so you can just reference a short description on top of an otherwise hefty block of statements.

---

*[pkg/storage/client_split_test.go, line 1868 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14375#-KgAuKDmP1DEgSvqvLZQ:-KgF5PUshkc4N28RiJu9:b4pys5x) ([raw file](https://github.com/cockroachdb/cockroach/blob/98f55e4f471d468e39d3706b6e987488f3b24d60/pkg/storage/client_split_test.go#L1868)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

ditto

also, why are two splits required? isn't one enough?
</blockquote></details>

I dislike messing with the `/Min-?` range; better to use two unittest-defined ranges.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14375)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/client_split_test.go, line 1823 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14375#-KgAu000_LSLd5AXKE0p:-KgFGp1JSr9bffqQsj96:bln6uyp) ([raw file](https://github.com/cockroachdb/cockroach/blob/98f55e4f471d468e39d3706b6e987488f3b24d60/pkg/storage/client_split_test.go#L1823)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary><blockquote>

Because of the changes to the store test harness to ensure that the store capacity is gossiped. There is some non-determinism in the test which makes it flaky. This change is verifying the correct behavior and is immune now to timing issues.
</blockquote></details>

What timing issues? The old logic looked like it was always waiting for the gossip callback.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14375)*

**Comment by spencerkimball** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/client_split_test.go, line 1823 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14375#-KgAu000_LSLd5AXKE0p:-KgFL2QbSCBwzG4Lb3Ti:besop69) ([raw file](https://github.com/cockroachdb/cockroach/blob/98f55e4f471d468e39d3706b6e987488f3b24d60/pkg/storage/client_split_test.go#L1823)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

What timing issues? The old logic looked like it was always waiting for the gossip callback.
</blockquote></details>

Introducing the gossip capacity in the client test startup sets wheels in motion which are somewhat non-deterministic. We could wait on more than just achieving quorum (we'd need to wait for the lease count, which is a much less readily-available metric), but it just didn't seem worthwhile to spend energy plumbing that through `helpers_test.go` as well only to still have what is essentially a fragile test. This logic is much more resilient.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14375)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica.go, line 82 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14375#-KgFMbOiYyuynd6ljMHX:-KgFMbOjama_2eJ2fOrC:bx972k5) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb7a9b45b3aa261976eb583f1dc295b77cd9f812/pkg/storage/replica.go#L82)):*
> ```Go
> 	replicaChangeTxnName = "change-replica"
> 	splitTxnName         = "split"
> 	mergeTxnName         = "merge"
> ```

Not much point to single use constants such as these, other than to boost line count. I suppose you're following existing convention here, though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14375)*

**Comment by spencerkimball** [comment]
Someone want to approve this, or further comment.

**Comment by bdarnell** [comment]
Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/storage/client_split_test.go, line 1851 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14375#-KgFaqmoHNQqxF3OW5Jx:-KgFaqmoHNQqxF3OW5Jy:b-ys7893) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb7a9b45b3aa261976eb583f1dc295b77cd9f812/pkg/storage/client_split_test.go#L1851)):*
> ```Go
> 
> // TestDistributedTxnCleanup verifies that distributed transactions
> // cleanup their txn records after commit or abort.
> ```

Other useful cases to test are that txn records are cleaned up when the txn is aborted by another (i.e. a deadlock) and this is detected by either the heartbeat loop or the transaction's own commit attempt. That's probably a different test, though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14375)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14375#-:-KgFbSqRDVJZE4RL2rd4:bnfp4nl)*

**Comment by spencerkimball** [comment]
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/storage/client_split_test.go, line 1851 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14375#-KgFaqmoHNQqxF3OW5Jx:-KgFeC-Me4Foc98vUFOb:b76kjqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb7a9b45b3aa261976eb583f1dc295b77cd9f812/pkg/storage/client_split_test.go#L1851)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Other useful cases to test are that txn records are cleaned up when the txn is aborted by another (i.e. a deadlock) and this is detected by either the heartbeat loop or the transaction's own commit attempt. That's probably a different test, though.
</blockquote></details>

I've added the forced abort case here.

---

*[pkg/storage/replica.go, line 82 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14375#-KgFMbOiYyuynd6ljMHX:-KgFlYY3dgYrhdrkTW4p:bkcxq96) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb7a9b45b3aa261976eb583f1dc295b77cd9f812/pkg/storage/replica.go#L82)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Not much point to single use constants such as these, other than to boost line count. I suppose you're following existing convention here, though.
</blockquote></details>

meh...I'm just going to stick to this pattern.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14375)*

**Pull request merged**
