### PR TITLE
Rework the update benchmarks to mirror the insert benchmarks.

### PR DESCRIPTION
**Pull request by petermattis**
Removed the non-transactional update benchmark. An SQL statement that is
not run in an explicit transaction is auto-wrapped with a transaction
which is why the timings between the non-transactional and transactional
update benchmark were identical.

I'm not sure why Update10_Postgres-8 had such variation across 10
runs. Note that Cockroach is performing relatively worse as the number
of rows updated increases. Something to investigate.

name                   time/op
Update1_Cockroach-8    1.35ms ± 1%
Update1_Postgres-8      228µs ± 2%
Update10_Cockroach-8   8.44ms ± 1%
Update10_Postgres-8     820µs ±11%
Update100_Cockroach-8  80.1ms ± 3%
Update100_Postgres-8   5.02ms ± 2%

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3968)

### CODE REVIEW

**Comment by dt** [comment]
LGTM.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3968#-:-K8yUgO47RJ2UaAxbof-:-492975211)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/bench_test.go, line 278 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3968#-K8yWihMBVOI0NzYUUxT:-K8yWihNihWY_8cC00mM:-647948331) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a4ac2df9490af6b7614dcad31dccbf41041e82e/sql/bench_test.go#L278)):*
What is the reasoning behind not using [`sql.Tx`](https://golang.org/pkg/database/sql/#Tx)s through [`db.Begin`](https://golang.org/pkg/database/sql/#DB.Begin) in benchmarks/tests like these?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3968)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/bench_test.go, line 278 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3968#-K8yWihMBVOI0NzYUUxT:-K8yhDTKLuI5om-CX8tx:1975237627) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a4ac2df9490af6b7614dcad31dccbf41041e82e/sql/bench_test.go#L278)):*
I'm not sure what David's initial reasoning was. Using a single request like this minimizes any network overhead, but I imagine it is minimal. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3968)*

**Comment by dt** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/bench_test.go, line 278 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3968#-K8yWihMBVOI0NzYUUxT:-K8ypV7kNgpbupECK5EA:273760358) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a4ac2df9490af6b7614dcad31dccbf41041e82e/sql/bench_test.go#L278)):*
Primarily I just wanted to mirror the pgbench code as closely as possible, since that was what motivated the benchmark, but also keeping it simple and avoiding any noise/issues added by client drivers (some maintain complicated state-machines, pg doesn't like our lack of tags, etc).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3968)*

**Pull request merged**
