### PR TITLE
server,pgwire: use a single SQL listener for multiple tenants

### LINKED ISSUE #84585: server: explore tenant routing in pg interface (also unix socket) [CRDB-14537 followup]
It is important for UX to have a single TCP port open / unix socket for all tenants running in 1 process.

The TLS client cert and/or some option in the conn URL could distinguish which tenant is being connected to.

(Alternatively, we could decide once and for all for separate interfaces. It's worth experimenting a little bit.)

Epic: CRDB-14537

Jira issue: CRDB-17748

### PR DESCRIPTION
**Pull request by knz**
Parent PRs:
- [x] https://github.com/cockroachdb/cockroach/pull/84608
- [x] https://github.com/cockroachdb/cockroach/pull/91739
- [x] https://github.com/cockroachdb/cockroach/pull/91744
- [x] https://github.com/cockroachdb/cockroach/pull/92574
- [x] https://github.com/cockroachdb/cockroach/pull/92575
- [x] https://github.com/cockroachdb/cockroach/pull/92576
- [x] https://github.com/cockroachdb/cockroach/pull/92577
- [x] https://github.com/cockroachdb/cockroach/pull/92578
- [x] https://github.com/cockroachdb/cockroach/pull/92579
- [x] https://github.com/cockroachdb/cockroach/pull/94901

Fixes #84585.
Informs  #94310.
Epic: CRDB-14537

This commit implements tenant routing using a single SQL network listener.

The tenant name can be specified:

- via the client status param `options`, e.g. `options=-ccrdb:tenant=hello`
- via the database name, e.g. `crdb:tenant-hello.defaultdb`.

Release note (backward-incompatible change): If a SQL database is created with a name that starts with `crdb:tenant-` (e.g. `CREATE DATABASE "crdb:tenant-foo"`, clients will no longer be able to connect to it directly.

### CODE REVIEW

**Comment by knz** [comment]
@jaylim-crl I don't understand your question.

The logic implemented here only exists for shared-process multitenancy, which we've estimated will only be used in Self-hosted / Dedicated.  

We may want to have a conversation about whether (and how) sqlproxy will be used with a multitenancy-enabled CC dedicated, but i'm not sure we need to have it now.

**Comment by jaylim-crl** [comment]
> @jaylim-crl I don't understand your question.
> 
> The logic implemented here only exists for shared-process multitenancy, which we've estimated will only be used in Self-hosted / Dedicated.
> 
> We may want to have a conversation about whether (and how) sqlproxy will be used with a multitenancy-enabled CC dedicated, but i'm not sure we need to have it now.

I see. Thanks for the clarification; that explains it.

**Comment by andy-kimball** [comment]
I'm confused about what `crdb:tenant-hello` means. Isn't the name of the tenant `hello` in this case? But if that's the name of the tenant, then where is the name of the database? And if `hello` isn't the name of the tenant, then where is the name of the tenant specified?

**Comment by knz** [comment]
> maybe the defaultdb is implied if there's no DB specified?

That is exactly what's happening.

> what crdb:tenant-hello means. Isn't the name of the tenant hello in this case? 

correct.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92580)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @knz, and @smg260)

___
*[`pkg/server/server_controller.go` line 245 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92580#-NI3jkV21wpmHGwkPflS:-NI3jkV21wpmHGwkPflT:b-3i5pww) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7541852d240effe2a7ce7518f3716329a0b042e/pkg/server/server_controller.go#L245)):*
> ```Go
> 	if status.State == pgwire.PreServeCancel {
> 		// Cancel requests do not contain enough data for routing; we
> 		// simply broadcast them to all servers. One of the servers will
> ```

that has an unfortunate side effect of causing warnings to be logged in all the servers that weren't intended to handle the request. it also is a security concern, since an attacker will have an increased rate of allowed guesses. maybe we just document it and say it's fine?

**Review by andy-kimball — COMMENTED** [review]
But why do something different than what Serverless does? It's confusing to have one syntax in one place a different syntax in another. The only restriction we should have is that you can't create a database that has a database name starting with the tenant name + ".". That seems like a very rare case that will almost certainly break no one. Your idea of using "crdb:tenant-" is probably even less likely to be part of a database name, but who cares? Neither of these will ever be database names, and no customer will be broken by _either of them_. The advantages of sticking with the proxy syntax:

* It avoids confusion in the docs where there are different ways of augmenting the database name - that's much more likely to cause confusion with customers than the rare case where a customer gets confused by an ambiguous name.
* It's aesthetically nicer to use `<tenant-cluster-name>.<db-name>` than `crdb:tenant-<tenant-cluster-name>.<db-name>`.

You explicitly ack'd using the "." syntax in the [original proposal](https://docs.google.com/document/d/1jQiOMMjCxto1KFJ8FGU51tmpd6Yo2VFUHa4d4x5l53c/edit):

> [knz] Yeah this is nice. The dot prefix is OK because periods are valid parts of a pg identifier. 

I don't think we should invent something new here, when the current approach has worked just fine for years now, with zero customer complaints.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92580#-:-NI49TOTBBgRRqQofA6-:b-56da21)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @knz, and @smg260)

**Comment by knz** [comment]
The proposal by Andy is not practical, because it changes which URLs are accepted depending on which tenants are defined.  It also requires inspecting the tenant table on every incoming connection.

Instead, I suggest we advance the discussion on https://github.com/cockroachdb/cockroach/issues/92526#issuecomment-1343259112 and use the outcome.

**Comment by andy-kimball** [comment]
> The proposal by Andy is not practical, because it changes which URLs are accepted depending on which tenants are defined.
You're incorrectly generalizing the proposal. Instead, it should be stated as, "it changes which URLs are accepted depending on whether the cluster is a multi-tenant or single-tenant cluster." That is a _much_ narrower restriction than the way to stated it, and I think perfectly acceptable. I don't think that single-tenant and multi-tenant instances of CRDB need to operate in identical ways.

> It also requires inspecting the tenant table on every incoming connection.
As it is, in a multi-tenant cluster, don't we have to inspect the tenant table on every incoming connection in order to get the tenant ID (i.e. to lookup tenant ID by name)?

**Comment by knz** [comment]
> depending on whether the cluster is a multi-tenant or single-tenant cluster.

This does not work. 
Your suggestion presupposes that whether a cluster is single-tenant or multi-tenant is 1) easy to determine 2) immutable.
Both are untrue today, especially the second part.

Imagine you have a cluster that qualifies as "single-tenant" at time t1. There's workload against it. Including perhaps workload using a composite db name.

Then at t2 because of, say, setting up a c2c replication stream, that same cluster switches to what qualifies at "multi-tenant". Suddently, all the client app connections start failing (because of what you propose).
This is unacceptable.

> I don't think that single-tenant and multi-tenant instances of CRDB need to operate in identical ways.

I wish to kindly but firmly push back against that. Our project currently assumes that *all* clusters are multi-tenant, and we're only considering single-tenancy as a starting point on an upgrade path to multi-tenancy. *eventually* everything is multi-tenant, and our c2c replication story make the number of tenants variable.

So at this time I wish we do not entertain solutions that try to separate "single-tenancy" from "multi-tenancy" in the source code. There's got to be a better way.

**Review by knz — COMMENTED** [review]
I've adapted the routing logic as per [the (new) RFC](https://github.com/cockroachdb/cockroach/pull/93537) and addressed the other comments.

RFAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92580#-:-NJuIdUW2Jv3H7-EIDtb:b-2jndam)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @rafiss, and @smg260)

___
*[`pkg/server/server_controller.go` line 245 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92580#-NI3jkV21wpmHGwkPflS:-NJuGdAzE9y1mOgi1fwk:bs0m1hy) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7541852d240effe2a7ce7518f3716329a0b042e/pkg/server/server_controller.go#L245)):*
> that has an unfortunate side effect of causing warnings to be logged in all the servers that weren't intended to handle the request

Point taken. I've moved the code around a bit to improve that. Do you like it better?

> it also is a security concern, since an attacker will have an increased rate of allowed guesses

I don't see this? As far as I can see, there is no rate limiting on cancel requests currently. So the rate of cancel attempts that would fail is (currently) bounded by the CPU only. IF we have N tenant servers running at the same time, each one will evaluate 1/N of the cancel requests at a time, so the total number of attempts possible does not increase.

I agree we might want to improve this in the future; which we will be able to do via a semaphore _above_ the tenant routing in server/server_controller.go so it's shared across SQL servers. But that looks like a separate project.

**Comment by knz** [comment]
@rafiss when you get a chance could you have another look thx

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92580)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @herkolategan, @knz, and @smg260)

___
*[`pkg/server/server_controller.go` line 245 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92580#-NI3jkV21wpmHGwkPflS:-NKTgORP4RjYkqM8B9sC:b-iwt0ht) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7541852d240effe2a7ce7518f3716329a0b042e/pkg/server/server_controller.go#L245)):*
>>    it also is a security concern, since an attacker will have an increased rate of allowed guesses
>
> I don't see this? 

my thinking was that the rate is higher now, since one cancel request will now fan out to multiple tenants. previously, there was no fan-out. with fan-out, it means that one cancel request "guess" can be used for all N tenants at the same time.

> As far as I can see, there is no rate limiting on cancel requests currently.

there is rate-limiting. an invalid requests hangs onto a semaphore for a second, which limits the amount of bad requests per second. i have now reminded myself that this semaphore is global 

https://github.com/cockroachdb/cockroach/blob/606313d29a93693914568403f60214cdcc15e563/pkg/sql/pgwire/pgwirecancel/cancel_semaphore.go#L26

the good part of that is some sort of rate limit is enforced still.
the bad part is that a malicious party could spam cancel requests, and then starve cancel requests for _all_ other tenants running in this server. maybe this doesn't matter for our threat model? but if that's the case, there should be a comment explaining so

> I agree we might want to improve this in the future; which we will be able to do via a semaphore above the tenant routing in server/server_controller.go so it's shared across SQL servers. But that looks like a separate project.

ok, it could be another project. but since this is the change that is introducing the regression, can you please file a followup issue? to me it seems the right way of doing this is to avoid fan-out, and instead make the pre-server smart enough to route the request correctly to the right tenant, similar to how sqlproxy can do it now
___
*[`pkg/sql/pgwire/server.go` line 817 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92580#-NKTi87j628bp4u_Wm4y:-NKTi87j628bp4u_Wm4z:b-aqqn6g) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1a69457f0526694bdd7968d2f72de9ca4d6961d/pkg/sql/pgwire/server.go#L817)):*
> ```Go
> // in the pgwirecancel package for more information.
> //
> // This function does not return an error, so the caller (and possible
> ```

this comment needs adjusting now

**Review by knz — COMMENTED** [review]
RFAL. Thanks for your suggestion to inspect the cancellation situation more closely. I hope you like the result.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92580#-:-NKYlNBxCewUCGvAtpDb:bb016qd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @herkolategan, @rafiss, and @smg260)

___
*[`pkg/server/server_controller.go` line 245 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92580#-NI3jkV21wpmHGwkPflS:-NKY_G1W4ouUirHgIUnB:b3ykvhj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7541852d240effe2a7ce7518f3716329a0b042e/pkg/server/server_controller.go#L245)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

>>    it also is a security concern, since an attacker will have an increased rate of allowed guesses
>
> I don't see this? 

my thinking was that the rate is higher now, since one cancel request will now fan out to multiple tenants. previously, there was no fan-out. with fan-out, it means that one cancel request "guess" can be used for all N tenants at the same time.

> As far as I can see, there is no rate limiting on cancel requests currently.

there is rate-limiting. an invalid requests hangs onto a semaphore for a second, which limits the amount of bad requests per second. i have now reminded myself that this semaphore is global 

https://github.com/cockroachdb/cockroach/blob/606313d29a93693914568403f60214cdcc15e563/pkg/sql/pgwire/pgwirecancel/cancel_semaphore.go#L26

the good part of that is some sort of rate limit is enforced still.
the bad part is that a malicious party could spam cancel requests, and then starve cancel requests for _all_ other tenants running in this server. maybe this doesn't matter for our threat model? but if that's the case, there should be a comment explaining so

> I agree we might want to improve this in the future; which we will be able to do via a semaphore above the tenant routing in server/server_controller.go so it's shared across SQL servers. But that looks like a separate project.

ok, it could be another project. but since this is the change that is introducing the regression, can you please file a followup issue? to me it seems the right way of doing this is to avoid fan-out, and instead make the pre-server smart enough to route the request correctly to the right tenant, similar to how sqlproxy can do it now
</blockquote></details>

I have investigated this further, and I have found the following.

- Thanks to the existing semaphore mechanism, we actually had suitable DoS protection already.
- Yes, as you've surmised already, a malicious user spamming the _combined_ server would starve the semaphore, which fails to provide us with inter-tenant resource isolation. However at this point, we are not aiming to isolate resource usage between tenants inside the same process (there's many issues to solve before that, like memory usage etc). So this starvation would not be an obstacle. But I agree that if we let things that way we would need some documentation.
- That being said, I found that a single global shared semaphore for the entire process is not desirable; it interferes with stress testing the cancellation code and provides weird waiting behavior to `cockroach demo --nodes N`. So I have amended this commit to make the semaphore per-server. Which obviates the previous point entirely.
- I have looked into doing something similar to sqlproxy, and I found it unpractical: we would need to parse the pgwire protocol in the server controller to detect the backenddata keys and store them in a map/cache. So instead I have opted to dispatch the cancel requests in parallel to all in-memory servers. This is not less secure than in sequence because each of them is protected by a similar semaphore; and it gives us the benefit of keeping the latency low if the cancel succeeds.

I have reworked the comments and added some additional explanation accordingly.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92580)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @herkolategan, @rafiss, and @smg260)

___
*[`pkg/sql/pgwire/server.go` line 817 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92580#-NKTi87j628bp4u_Wm4y:-NKYm8l57pMBoxJs0fpU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1a69457f0526694bdd7968d2f72de9ca4d6961d/pkg/sql/pgwire/server.go#L817)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this comment needs adjusting now
</blockquote></details>

Done.

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92580)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @herkolategan, @knz, and @smg260)

___
*[`pkg/server/server_controller.go` line 468 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92580#-NKsCUTe-sO0obEDJ6vO:-NKsCUTe-sO0obEDJ6vP:bt4budj) ([raw file](https://github.com/cockroachdb/cockroach/blob/139683b690746b1db7062dc02679ff7db8f2c171/pkg/server/server_controller.go#L468)):*
> ```Go
> 			// servers to see and process the cancel at approximately the
> 			// same time as every other.
> 			if err := c.stopper.RunAsyncTask(ctx, "cancel", func(ctx context.Context) {
> ```

any particular reason to use the stopper here versus a `ctxgroup`? i'm asking partially so i can understand when one is preferred over the other.
___
*[`pkg/server/server_controller.go` line 480 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92580#-NKsC6l974QVkgfLrU42:-NKsC6lA6hLWbHVdr6iB:bkfqedt) ([raw file](https://github.com/cockroachdb/cockroach/blob/139683b690746b1db7062dc02679ff7db8f2c171/pkg/server/server_controller.go#L480)):*
> ```Go
> 		// This is achieved here because when the cancellation succeeds
> 		// in at least one server, that server's task above will
> 		// complete quickly and report nil quickly on the error channel.
> ```

nice, i think the direction you're going in will work. but one concern around this logging: this assumes that a "success" will always be reported more quickly than an error. but consider the case where one of the semaphores is already exhausted. when the code calls `TryAcquire` on it, the request will fail quickly, so it's possible that that error would end up being reported here, even if one of the other servers successfully handled the request

i think this might need to wait for all the goroutines to finish. if all errors are non-nil, then it should be logged. and perhaps we should log each unique error type, in case things failed for different reasons

**Review by knz — COMMENTED** [review]
RFAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92580#-:-NL7-quR9coKle-keMvi:b-828fna)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @herkolategan, @rafiss, and @smg260)

___
*[`pkg/server/server_controller.go` line 468 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92580#-NKsCUTe-sO0obEDJ6vO:-NL7-Bw70zFE6AjDu4Wq:brmm3o) ([raw file](https://github.com/cockroachdb/cockroach/blob/139683b690746b1db7062dc02679ff7db8f2c171/pkg/server/server_controller.go#L468)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

any particular reason to use the stopper here versus a `ctxgroup`? i'm asking partially so i can understand when one is preferred over the other.
</blockquote></details>

It's a fair question. A ctxgroup will return a non-nil error if _any_ of the tasks returns a non-nil error. In our case here, we want to learn if at least one of the tasks did return a nil error. ctxgroup does not give us that.
___
*[`pkg/server/server_controller.go` line 480 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92580#-NKsC6l974QVkgfLrU42:-NL7-oNF4rUP9YhIuE4T:b-8ivmbp) ([raw file](https://github.com/cockroachdb/cockroach/blob/139683b690746b1db7062dc02679ff7db8f2c171/pkg/server/server_controller.go#L480)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nice, i think the direction you're going in will work. but one concern around this logging: this assumes that a "success" will always be reported more quickly than an error. but consider the case where one of the semaphores is already exhausted. when the code calls `TryAcquire` on it, the request will fail quickly, so it's possible that that error would end up being reported here, even if one of the other servers successfully handled the request

i think this might need to wait for all the goroutines to finish. if all errors are non-nil, then it should be logged. and perhaps we should log each unique error type, in case things failed for different reasons
</blockquote></details>

Yep, you're right. Fixed it.

**Review by rafiss — APPROVED** [review]
thank you for tracking down all the loose ends!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92580#-:-NL8PQpX-VVGe1_N46LN:b5f54i9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @herkolategan, and @smg260)

**Comment by knz** [comment]
TFYRs!

bors r=rafiss

**Pull request merged**
