### PR TITLE
githook: also produce the commit suggestions with --amend

### PR DESCRIPTION
**Pull request by knz**
Prior to this patch the commit message suggestions and the
default release note ("none") were only produced for new commits.

This patch fixes this to also include the suggestion for amends and
merges, and always adds the release note when not present.

Release note: None

### CODE REVIEW

**Comment by andreimatei** [comment]
LGTM thanks!

**Comment by benesch** [comment]
This is awesome! Thanks @knz!

**Comment by jordanlewis** [comment]
+1 - thanks!

**Pull request merged**
