### PR TITLE
kvserver: deflake TestGossipHandlesReplacedNode

### LINKED ISSUE #74447: kv/kvserver: TestGossipHandlesReplacedNode failed
kv/kvserver.TestGossipHandlesReplacedNode [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4044053&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4044053&tab=artifacts#/) on master @ [260144b9bec2b2da2cf96c7198197a88b97c942c](https://github.com/cockroachdb/cockroach/commits/260144b9bec2b2da2cf96c7198197a88b97c942c):

```
=== RUN   TestGossipHandlesReplacedNode
    test_log_scope.go:79: test logs captured to: /artifacts/tmp/_tmp/751d67000aac5f3394c2369309253f02/logTestGossipHandlesReplacedNode3951923715
    test_log_scope.go:80: use -show-logs to present logs inline
    testcluster.go:412: listen tcp 127.8.243.194:36669: bind: address already in use
    panic.go:642: -- test log scope end --
--- FAIL: TestGossipHandlesReplacedNode (1.81s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
Parameters in this failure:

- TAGS=bazel,gss
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestGossipHandlesReplacedNode.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-12084

### PR DESCRIPTION
**Pull request by tbg**
Fixes #74447.

Release note: None

### CODE REVIEW

**Comment by erikgrinaker** [comment]
I'd prefer either listening on port 0 or on a non-ephemeral port (typically below 32768) -- are those options not viable here?

**Comment by tbg** [comment]
We are intentionally restarting using the same port as the recently stopped server - that is what the test wants to do. So we can't restart with port zero.
We can't use a hard-coded port because then you cannot stress the test.

**Review by erikgrinaker — APPROVED** [review]

**Comment by erikgrinaker** [comment]
Bummer. I suppose this is fine for now.

**Comment by tbg** [comment]
bors r=erikgrinaker

**Comment by irfansharif** [comment]
blathers backport 22.1

**Pull request merged**
