### PR TITLE
sql: auto-generate column names like in PostgreSQL

### LINKED ISSUE #26236: sql: make CockroachDB generate column names for expressions like pg
So PostgreSQL has some rules to generate a simple column name for a projected expression, that extend what the SQL standard has to say on the topic.

Meanwhile CockroachDB does not contain any rule at all (or barely) and simply renders the syntax of the projected expression as name for the new column.

Some example discrepancies:

| input syntax | pg | crdb |
|--|--|--|
| `(a,b)`        | `row` | `(a, b)` |
| `nullif(1,2)` | `nullif` | `nullif(1, 2)` |
| `array[1,2,3]` | `array` | `array[1, 2, 3]` |

The code to do this in pg is found in function `FigureColname` /  `FigureColnameInternal` in `src/backend/parser/parse_target.c`.

The advantage of pg's approach are multiple:

- the name is simpler to use
- it's smaller in memory
- the computation of the name is cheaper

Also clients may care about generated names when introspecting the column names of the results of a query client-side.

### PR DESCRIPTION
**Pull request by knz**
Fixes  #26236.

Prior to this patch, CockroachDB would generate names for results not
explicitly named with AS using a pretty-printing algorithm for the
entire rendered expression.

Example before:

```
> SELECT cos(x + y)::INT FROM xy;
+-----------------+
| cos(x + y)::INT |
+-----------------+
|               0 |
+-----------------+
> SELECT 'abc'::BYTES;
+--------------+
| 'abc'::BYTES |
+--------------+
| abc          |
+--------------+
> SELECT 1 + 2
+-------+
| 1 + 2 |
+-------+
|     3 |
+-------+
```

There were multiple drawbacks from doing so:

- the generated column names were incompatible with PostgreSQL. This
  showed up in edge cases like `select nullif(a,b,c)` where the column
  name is expected to be "`nullif`" not the pretty-printed full
  expression `NULLIF(a, b, c)`.
- the algorithm incurred many mandatory memory allocations (to
  assemble the string) for every single column rendered, in every
  query.
- the tree recursion and string interpolations needed to construct the
  string were using CPU cycles that do not contribute to the query
  results.

Instead, this patch implements PostgreSQL's algorithm, which has the
following properties:

- it only produces pre-existing strings in memory, either from static
  string constants or from the text of the SQL query (parsed
  tokens). No additional memory allocations or string computations are
  needed.
- it traverses fewer nodes from the AST in memory to compute its
  result.

- it produces the same results as PostgreSQL for the same input
  queries.

Example after:

```
> SELECT cos(x + y)::INT FROM xy;
+-----+
| cos |
+-----+
|   0 |
+-----+
> SELECT 'abc'::BYTES;
+-------+
| bytes |
+-------+
| abc   |
+-------+
> SELECT 1 + 2
+----------+
| ?column? |
+----------+
|        3 |
+----------+
```

The algorithm produces a string and a confidence level (0-2) and is
recursively defined as follows:

- things that get constant strings with confidence 2:
  - column reference get named after the unqualified column name.
  - function applications get named after the name of the function,
    e.g. `cos(x)` gets named `cos`.
  - function-like operators get named after the operator. For example
    `coalesce(a,b)` gets named `coalesce`, `row(a,b)` gets named
    `row`, `nullif(a,b)` is `nullif`, `exists(subquery...)` is
    `exists`, etc.
  - `ARRAY(E)` and `ARRAY[...]` gets named `array`.
  - boolean literals (`true`/`false`) get named `bool` because pg
    internally implements them as `'t'::BOOL` and `'f'::BOOL`.
  - `(SELECT E AS x)` gets named just `x`.
  - `(E).x` gets named just `x`.
  - `((E) AS x)` gets named just `x`.
  - `(VALUES (E))` gets named just `column1` (for consistency with
    the standalone `VALUES` clause).
- things that are named recursively:
  - `(E)` gets named after E.
  - `E[N]` gets named after E.
  - `E COLLATE X` gets named after E.
  - `(SELECT E)` (no `AS` in subquery) gets named after E.
  - `E::T` and `E:::T` gets named after E, and if the confidence is <=
    1 then after T with confidence 1.  e.g. `t::INT` is named `t`,
    `123::INT` is named `int`.
  - `CASE A THEN B ELSE C END` gets named after C, and if the
    confidence is <= 1 then just `case` with confidence 1.
  - `CASE A THEN B END` (no ELSE) gets named just `case` with
    confidence 1.
- everything else receives no name with confidence 0.

When the algorithm complete, if there was no name produced the final
name becomes `"?column?"`.
The original code is to be found in pg's source in
`src/backend/parser/parse_target.c`.

Release note (sql change): CockroachDB now computes automatic column
names for SELECT expressions that do not use AS using a simpler and
more efficient algorithm, which also produces names more compatible
with PostgreSQL.

Release note (backward-incompatible change): CockroachDB now uses a
different algorithm to generate column names for complex expressions
in SELECT clauses when AS is not used. The results are more compatible
with PostgreSQL but may appear different to client applications. This
does not impact most uses of SQL, where the rendered expressions are
sufficiently simple (simple function applications, reuses of existing
columns) or when AS is used explicitly.

### CODE REVIEW

**Comment by knz** [comment]
@rytaft can we spend a few minutes together? There is one edge case where I get a different column name in opt-generated plans. I don't know where to look. Would like your help.

**Comment by RaduBerinde** [comment]
Could you give a brief overview of the algorithm in the commit message? (you go over its properties but not the algorithm itself). I realize there are a lot of details to it, but at least the general approach. Would also help mentioning `src/backend/parser/parse_target.c` as a reference.

The corresponding code in `opt` is [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/opt/optbuilder/project.go#L112).

---

Review status: 0 of 39 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26550#-:-LEVgeOh6-ZzTdDFNgXW:b-d82v4p)*

**Comment by knz** [comment]
> Could you give a brief overview of the algorithm in the commit message?

Done.

> Would also help mentioning src/backend/parser/parse_target.c as a reference.

Done.

> The corresponding code in opt is here.

Thanks! I fixed (adapted) it and all the tests. RFAL.

---

Review status: 0 of 87 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26550#-:-LEVzcQI1KvodBFAZWM9:b-5kbxq1)*

**Comment by RaduBerinde** [comment]
Very nice! :lgtm_strong: 

Thanks for that description, it helps a lot!

Just a nit: in the test changes you alternate between using and not using `AS`. I find it more clear to always include it. That said, if it's too much work to go through all these changes again, don't worry about it.

---

Review status: 0 of 87 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26550#-:-LEX4nWC5bx_s2MY-mD3:bjtlm5w)*

**Comment by RaduBerinde** [comment]
No, no, I'm strictly talking about the ones you changed. In some cases you are using the optional keyword `AS`, in some cases you are not. For example, in `opt/memo/testdata/typing` the new query is `SELECT 1 a, TRUE b, FALSE c, NULL d` which is (to me) a bit more confusing to read than `SELECT 1 AS a, TRUE AS b, FALSE AS c, NULL AS d`.

---

Review status: 0 of 87 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26550#-:-LEYvYoI5WF2DjmbdZil:b-izj9y1)*

**Comment by knz** [comment]
>  For example, in opt/memo/testdata/typing the new query is SELECT 1 a, TRUE b, FALSE c, NULL d which is (to me) a bit more confusing to read than SELECT 1 AS a, TRUE AS b, FALSE AS c, NULL AS d.

Oh I see, that makes sense. I have changed all the relevant tests accordingly.

**Comment by knz** [comment]
Thanks for the review :)

bors r+

**Pull request merged**
