### PR TITLE
streamingccl: correctly resume stream from partial initial scan

### LINKED ISSUE #109957: roachtest: c2c/shutdown/src/worker failed
roachtest.c2c/shutdown/src/worker [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11597382?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11597382?buildTab=artifacts#/c2c/shutdown/src/worker) on master @ [b994d025c678f495cb8b93044e35a8c59595bd78](https://github.com/cockroachdb/cockroach/commits/b994d025c678f495cb8b93044e35a8c59595bd78):

```
(assertions.go:333).Fail: 
	Error Trace:	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cluster_to_cluster.go:656
	            				github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cluster_to_cluster.go:795
	            				github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cluster_to_cluster.go:1261
	            				main/pkg/cmd/roachtest/monitor.go:119
	            				golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75
	            				GOROOT/src/runtime/asm_amd64.s:1594
	Error:      	Received unexpected error:
	            	failed stripped fingerprint: failed getting dst fingerprint: could not get database names: pq: service unavailable for target tenant (destination-tenant)
	Test:       	c2c/shutdown/src/worker
(require.go:1360).NoError: FailNow called
(monitor.go:153).Wait: monitor failure: monitor user task failed: t.Fatal() was called
test artifacts and logs in: /artifacts/c2c/shutdown/src/worker/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=8</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/p/roachfana/teamcity-11597382-1693633808-38-n9cpu8/1693650192535/1693651023273)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*c2c/shutdown/src/worker.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-31183

### PR DESCRIPTION
**Pull request by stevendanna**
When starting a subscription, we pass an initial timestamp and a previous replicated timestamp. If the previous replicated timestamp is zero, the produce assumes we've completed the initial scan and streams only incremental changes from the given replicated timestamp.

When resuming a restarted job, we use a persisted frontier checkpoint to find the minimum timestamp replicated time for a set of spans and use that rather than the overall replicated time to attempt to reduce the amount of duplicated work.

Since data is split across many ranges, some portions of our keyspace may complete their initial scan before others. As a result, the persisted frontier checkpoint during the initial scan may have some spans at zero-valued timestamps and others at non-zero timestamps.

Unfortunately, the code to find the minimum timestamp incorrectly handled portions of the frontier that had zero-valued timestamps, returning the lowest non-zero value rather than zero.

As a result, if we resumed during an initial scan but after some portions of the key space have recorded progress, we would use a non-zero previous replicated timestamp to resume a stream even if some of the spans still required their initial scans to complete.

He we fix the bug so that the minimum timestamp for a set of spans is zero if any of the given spans is currently at zero.

Fixes #109957

Release note: None

Epic: none

### CODE REVIEW

**Comment by stevendanna** [comment]
@msbutler @lidorcarmel We should probably try to write an integration-y test that reproduces the actual fingerprint mismatch, but I think this is the core of the problem seen with the fingerprint mismatch.

**Review by msbutler — APPROVED** [review]
Amazing find! I'm fine with the integration test you describe being follow up work.

**Comment by stevendanna** [comment]
bors r=msbutler

**Comment by dt** [comment]
Do we have a testserver-based e2e unit test that pauses and resumes?

**Comment by msbutler** [comment]
we do, but not during an initial scan that would hit this specific failure mode.

**Comment by stevendanna** [comment]
blathers backport 23.1.10-rc

**Pull request merged**
