### PR TITLE
sql: make it possible to refer to tables/indices by ID

### LINKED ISSUE #12715: sql: make it possible to refer to dbs/tables/indices by number
Like we already have ordinal references for data sources we should have ordinal references to dbs/tables/indices.

Like e.g. `SELECT * FROM !1231` to select from table 1231. or `SELECT !1231 FROM foo` for column 1231 or `SELECT * FROM !1231.foo` for a db ref, or `SELECT * FROM foo@!1231` for an index ref.

Will help with IR work and also will simplify the code produced for #12682.

cc @dt

### PR DESCRIPTION
**Pull request by knz**
For example:

``` sql
  SELECT * FROM [123] AS t
  SELECT * FROM [123] AS t(a,b,c)
  SELECT * FROM [123(1,2,3)] AS t(a,b,c)
  SELECT * FROM [123] @ [456] AS t(a,b,c)
  SELECT * FROM [123] @ {FORCE_INDEX=[456]} AS t(a,b,c)
```

Fixes #12715.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13781)

### CODE REVIEW

**Comment by a-robinson** [comment]
Nice work on this, @knz!

**Comment by petermattis** [comment]
I like the functionality!

Can we bikeshed the syntax? Not terribly fond of using `!<id>` for this. What else is possible? How about `[<id>]`? Or does that conflict with array indirection? `{<id>}` or `#<id>` would also be preferable to me.

**Comment by knz** [comment]
`{...}` would be hairy to implement in the grammar. The other two suggestions are fine. I have a slight preference for `#<id>` but I can see it becoming annoying when copy/pasting SQL into Github issues/PRs.

**Comment by knz** [comment]
I'm off for today, I'll look into this further tomorrow.

Feel free to come with more syntax bikeshedding, I have not preference in the matter really.

**Comment by knz** [comment]
I went for `[...]` since we already have crdb-specific syntax with square brackets (`[explain ...]`).

**Comment by petermattis** [comment]
That visually looks good to me.

**Comment by mjibson** [comment]
Review status: 0 of 13 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/sql/data_source.go, line 363 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13781#-KdiFV6-ZCQbtzZZxhp4:-KdiFV6-ZCQbtzZZxhp5:bnp46k2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2343c73b94ec365b4ddfdaf39688faea6e036954/pkg/sql/data_source.go#L363)):*
> ```Go
> 			src, err = p.getTableScanByRef(tref, hints, scanVisibility)
> 		} else {
> 			src, err = p.getDataSource(t.Expr, hints, scanVisibility)
> ```

This is a slight change in behavior. Was not using hints a bug?

---

*[pkg/sql/data_source.go, line 451 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13781#-KdiGKxtJ4vY8kbH8dLa:-KdiGKxu_vOmFssC5ShV:b5foajr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2343c73b94ec365b4ddfdaf39688faea6e036954/pkg/sql/data_source.go#L451)):*
> ```Go
> 	tn := parser.TableName{
> 		TableName:               parser.Name(desc.Name),
> 		DBNameOriginallyOmitted: true,
> ```

Why does this need to be true?

---

*[pkg/sql/scan.go, line 281 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/13781#-Kdm26HaYE3pCEsyM5pO:-Kdm26HaYE3pCEsyM5pP:bqcpk1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d45425419971a60d28a5d367813dada492c30b8/pkg/sql/scan.go#L281)):*
> ```Go
> 				}
> 			}
> 		}
> ```

Why did this `}` need to be added here? Looks like it was fine where it was. (It's obviously not wrong here, just seems like it was correct before.)

---

*[pkg/sql/scan.go, line 297 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/13781#-Kdm2Kv9mBTNko2eAyIQ:-Kdm2Kv9mBTNko2eAyIR:b-bk0wad) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d45425419971a60d28a5d367813dada492c30b8/pkg/sql/scan.go#L297)):*
> ```Go
> 			}
> 		}
> 		if n.specifiedIndex == nil {
> ```

Same question as above. Can this go in the else one line above?

---

*[pkg/sql/parser/sql.y, line 2928 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/13781#-Kdm-9gnywb4eBjF42bj:-Kdm-9gnywb4eBjF42bk:b-opyt2p) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ac18090c458af450545f02f8a7f8f85a24e157b/pkg/sql/parser/sql.y#L2928)):*
> ```Yacc
>        return 1
>     }
>     a.Index = a.Index + b.Index
> ```

I don't understand why we are adding strings here and indexIDs on the next line.

---

*[pkg/sql/parser/sql.y, line 2964 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/13781#-Kdm-c7W7ij59_LewRtb:-Kdm-c7XwS7ppuaPjWEK:bmezs8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ac18090c458af450545f02f8a7f8f85a24e157b/pkg/sql/parser/sql.y#L2964)):*
> ```Yacc
>     }
>     $$.val = &AliasedTableExpr{Expr: &TableRef{TableID: id, Columns: $3.tableRefCols()},
> 			       Hints: $5.indexHints(),
> ```

Tabs here and next line, should be spaces to be consistent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13781)*

**Comment by knz** [comment]
Review status: 0 of 13 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/sql/data_source.go, line 363 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13781#-KdiFV6-ZCQbtzZZxhp4:-KdrEqmFRbbP7uDMts32:bkpc2vs) ([raw file](https://github.com/cockroachdb/cockroach/blob/2343c73b94ec365b4ddfdaf39688faea6e036954/pkg/sql/data_source.go#L363)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

This is a slight change in behavior. Was not using hints a bug?
</blockquote></details>

It wasn't a bug for a subtle reason: hints can currently only be applied in the grammar to a direct table name, so the "child node" of an `AliasedTableExpr` with a hint was *always* a simple table name, thus never an `AliasedTableExpr`, and thus it was not possible for the `hints` parameters to be non-nil for `AliasedTableExpr`.

However I found the protection provided by this grammar constraint rather ... flimsy, and didn't see why we couldn't (conceptually at least) envision hints given for arbitrary data sources. To acknowledge this vision, I changed the code here, which incidentally also makes it less surprising (more maintainable) and more future-proof.

---

*[pkg/sql/data_source.go, line 451 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13781#-KdiGKxtJ4vY8kbH8dLa:-KdrFidDFps4_bsOHCab:byq9z58) ([raw file](https://github.com/cockroachdb/cockroach/blob/2343c73b94ec365b4ddfdaf39688faea6e036954/pkg/sql/data_source.go#L451)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Why does this need to be true?
</blockquote></details>

Added a comment to clarify.

---

*[pkg/sql/scan.go, line 281 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/13781#-Kdm26HaYE3pCEsyM5pO:-KdrG4-WXmupjDhHjI9m:bk0fccw) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d45425419971a60d28a5d367813dada492c30b8/pkg/sql/scan.go#L281)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Why did this `}` need to be added here? Looks like it was fine where it was. (It's obviously not wrong here, just seems like it was correct before.)
</blockquote></details>

Sorry please add some context here, I do not understand your question. Somehow your review comment got misplaced, I do not understand what it refers to.

---

*[pkg/sql/scan.go, line 297 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/13781#-Kdm2Kv9mBTNko2eAyIQ:-KdrG9awBX2gcjjgLnW0:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d45425419971a60d28a5d367813dada492c30b8/pkg/sql/scan.go#L297)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Same question as above. Can this go in the else one line above?
</blockquote></details>

ditto

---

*[pkg/sql/parser/sql.y, line 2928 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/13781#-Kdm-9gnywb4eBjF42bj:-KdrGDFR2UJNzDupQt8f:bwi1tkv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ac18090c458af450545f02f8a7f8f85a24e157b/pkg/sql/parser/sql.y#L2928)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I don't understand why we are adding strings here and indexIDs on the next line.
</blockquote></details>

Because that's the arithmetically correct way to select the one and only non-empty value from both operands when we don't know which one is empty.
(empty + non-empty = non-empty, 0 + non-zero = non-zero)

---

*[pkg/sql/parser/sql.y, line 2964 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/13781#-Kdm-c7W7ij59_LewRtb:-KdrGR4kj44JH1_A64Xz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ac18090c458af450545f02f8a7f8f85a24e157b/pkg/sql/parser/sql.y#L2964)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Tabs here and next line, should be spaces to be consistent.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13781)*

**Comment by mjibson** [comment]
:lgtm:

Although with multiple commits I have no idea how reviewable orders new changesets, so I can't really find some of your more recent changes.

---

Review status: 0 of 13 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/scan.go, line 281 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/13781#-Kdm26HaYE3pCEsyM5pO:-KdsyIUN4nx-W6t1F6BO:b-2guj8r) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d45425419971a60d28a5d367813dada492c30b8/pkg/sql/scan.go#L281)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Sorry please add some context here, I do not understand your question. Somehow your review comment got misplaced, I do not understand what it refers to.
</blockquote></details>

This is about the placement of the `}` before the `if n.specifiedIndex == nil` check. I think it's fine as you changed it, though. Ignore these comments.

---

*[pkg/sql/parser/sql.y, line 2928 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/13781#-Kdm-9gnywb4eBjF42bj:-Kdsyi2_JXHhu1-AeeY-:b-ozy4ee) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ac18090c458af450545f02f8a7f8f85a24e157b/pkg/sql/parser/sql.y#L2928)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Because that's the arithmetically correct way to select the one and only non-empty value from both operands when we don't know which one is empty.
(empty + non-empty = non-empty, 0 + non-zero = non-zero)
</blockquote></details>

Ah, I didn't realize one was checked to be empty.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13781#-:-KdsymJaqi-Dj8L0UiGD:b-rd6i0x)*

**Comment by knz** [comment]
TFYR!

**Pull request merged**
