### PR TITLE
authors: add msirek to authors

### PR DESCRIPTION
**Pull request by msirek**
Release note: None

### CODE REVIEW

**Review by ajstorm — APPROVED** [review]
LGTM.  One minor suggestion which you can take or leave.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74663#-:-Mt8RXVB88ui5d4agSlh:b-13boof)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek)

___
*[AUTHORS, line 280 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74663#-Mt8QHGO27c22dKbfqiz:-Mt8QHGO27c22dKbfqj-:b-g1hktv) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fe8e0f25a82cf1ce79a5d751e01e3b01c123d53/AUTHORS#L280)):*
> ```
> Marius Posta <marius@cockroachlabs.com>
> Marjan Ansar <marjan@cockroachlabs.com>
> Mark Sirek <sirek@cockroachlabs.com> msirek <sirek@cockroachlabs.com>
> ```

Nit: you can take or leave this comment but we do get a fair amount of spam here at CRL.  I have a sneaking suspicion that some of that spam is a result of this authors list.  To test that suspicion, you could change your email address here to something like `sirek+authors@cockroachlabs.com`.  Gmail ignores everything after and including the + in your address, and doing so would tell us if this is how the spammers are uncovering our addresses.  You could even go with something like `sirek+m@cockroachlabs.com` if you wanted to make it look more natural.  Again, your call, but I'd wish I'd done this for mine.

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74663)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[AUTHORS, line 280 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74663#-Mt8QHGO27c22dKbfqiz:-Mt8VdcB04raKd1WjPW1:b-di43iy) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fe8e0f25a82cf1ce79a5d751e01e3b01c123d53/AUTHORS#L280)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: you can take or leave this comment but we do get a fair amount of spam here at CRL.  I have a sneaking suspicion that some of that spam is a result of this authors list.  To test that suspicion, you could change your email address here to something like `sirek+authors@cockroachlabs.com`.  Gmail ignores everything after and including the + in your address, and doing so would tell us if this is how the spammers are uncovering our addresses.  You could even go with something like `sirek+m@cockroachlabs.com` if you wanted to make it look more natural.  Again, your call, but I'd wish I'd done this for mine.
</blockquote></details>

This is a good point. I made the change. I don't know how the AUTHORS file is used at cockroach, if those addresses are used internally for sending us things. For example, would I miss some important e-mails if I made mine a github noreply e-mail address.

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74663)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @msirek)

___
*[AUTHORS, line 280 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74663#-Mt8QHGO27c22dKbfqiz:-Mt8XBeQ3IWyb766tASW:bcp2bh8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fe8e0f25a82cf1ce79a5d751e01e3b01c123d53/AUTHORS#L280)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

This is a good point. I made the change. I don't know how the AUTHORS file is used at cockroach, if those addresses are used internally for sending us things. For example, would I miss some important e-mails if I made mine a github noreply e-mail address.
</blockquote></details>

I actually don't fully know the answer to that question.  I think a no-replay address wouldn't be the best for community building thought, as in theory at least, community members should be able to reach out to us using this list.

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74663)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[AUTHORS, line 280 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74663#-Mt8QHGO27c22dKbfqiz:-Mt8ZCEGDQyUIG01ACAy:b-pta10y) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fe8e0f25a82cf1ce79a5d751e01e3b01c123d53/AUTHORS#L280)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

I actually don't fully know the answer to that question.  I think a no-replay address wouldn't be the best for community building thought, as in theory at least, community members should be able to reach out to us using this list.  
</blockquote></details>

I see.  Thanks.

**Pull request merged**
