### PR TITLE
sql: Add ALTER DATABASE ... PRIMARY REGION

### PR DESCRIPTION
**Pull request by ajstorm**
Databases created without a primary region were previously not able to
add one via ALTER DATABASE.  This PR implements ALTER DATABASE ...
PRIMARY REGION.

Release note (sql change): Adds ALTER DATABASE ... PRIMARY REGION

### CODE REVIEW

**Review by otan — COMMENTED** [review]
> Reviewed 7 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58725)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/alter_database.go, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58725#-MQnJtaiCwjzNjubqQxO:-MQnJtaiCwjzNjubqQxP:bxj72bx) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcc153431e8da63a819a07efc0d1e8bf496eb09f/pkg/sql/alter_database.go#L150)):*
> ```Go
> 	if !n.desc.IsMultiRegion() {
> 		return pgerror.Newf(pgcode.InvalidDatabaseDefinition,
> 			"cannot add region %q to database %q. Please add a primary region first.",
> ```

maybe
```
errors.WithHint(
   pgerror.Newf(pgcode.InvalidDatabaseDefinition, "cannot add region %q to database %q", 			string(n.n.Region),			string(n.n.Name)),
   "You must add a PRIMARY REGION first using ALTER DATABASE %s SET PRIMARY REGION %s", ...
)
```
___
*[pkg/sql/alter_database.go, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58725#-MQnKMFK08fY2_8GXj_F:-MQnKMFK08fY2_8GXj_G:b-z3jov8) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcc153431e8da63a819a07efc0d1e8bf496eb09f/pkg/sql/alter_database.go#L289)):*
> ```Go
> 	// an error, as it must be added before it can be used as a primary region.
> 	found := false
> 	for _, r := range n.desc.RegionConfig.Regions {
> ```

n.desc.RegionConfig.PrimaryRegion != "" should do.
___
*[pkg/sql/alter_database.go, line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58725#-MQnKS0tE4i52IleBvtL:-MQnKS0tE4i52IleBvtM:bhcza3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcc153431e8da63a819a07efc0d1e8bf496eb09f/pkg/sql/alter_database.go#L303)):*
> ```Go
> 				string(n.n.PrimaryRegion),
> 			),
> 			"ALTER DATABASE %q ADD REGION %q", string(n.n.Name), string(n.n.PrimaryRegion),
> ```

i think we use the SQL escape string instead, i.e. n.n.Name.String() (if that escapes items). %q does not escape SQL strings.
___
*[pkg/sql/alter_database.go, line 348 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58725#-MQnKdulE5RsGGQpUIb5:-MQnKdulE5RsGGQpUIb6:bjw2n4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcc153431e8da63a819a07efc0d1e8bf496eb09f/pkg/sql/alter_database.go#L348)):*
> ```Go
> 	if enumPrimaryRegion != databasePrimaryRegion {
> 		return errors.AssertionFailedf(
> 			"Multi-region enum primary region %q does not match database primary region %q",
> ```

nit: errors start with lower case.
do we need this check if we have validators that catch this?
___
*[pkg/sql/alter_database.go, line 359 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58725#-MQnLJJCE-athsJcLSUy:-MQnLJJCE-athsJcLSUz:bscgupi) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcc153431e8da63a819a07efc0d1e8bf496eb09f/pkg/sql/alter_database.go#L359)):*
> ```Go
> 		*n.desc.RegionConfig); err != nil {
> 		return err
> 	}
> ```

we don't (yet) have logic to iterate over every table and set a reasonable MR config for each one (with this change, it will inherit the same as database level).
(neither do we have logic for CREATE TABLE that if the database is multiregion, set a reasonable default)
can you add a TODO with an issue to cover this?
i think `ADD REGION` similarly has this issue.
___
*[pkg/sql/region_util.go, line 280 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58725#-MQnL5KrC0guDdUleet8:-MQnL5KrC0guDdUleet9:bsx9dvb) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcc153431e8da63a819a07efc0d1e8bf496eb09f/pkg/sql/region_util.go#L280)):*
> ```Go
> 	}
> 	// TODO(#multiregion): See github issue:
> 	// https://github.com/cockroachdb/cockroach/issues/56877.
> ```

hmm this issue is closed. @arulajmani ?

**Review by ajstorm — COMMENTED** [review]
TFTR @otan.  Addressed everything I could.  Left questions for the rest.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58725#-:-MQoWEy32E5bdBKm9V6K:buyu3s5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @otan)

___
*[pkg/sql/alter_database.go, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58725#-MQnJtaiCwjzNjubqQxO:-MQoMYKF9wMNGjPpK-fO:bs7wumb) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcc153431e8da63a819a07efc0d1e8bf496eb09f/pkg/sql/alter_database.go#L150)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

maybe
```
errors.WithHint(
   pgerror.Newf(pgcode.InvalidDatabaseDefinition, "cannot add region %q to database %q", 			string(n.n.Region),			string(n.n.Name)),
   "You must add a PRIMARY REGION first using ALTER DATABASE %s SET PRIMARY REGION %s", ...
)
```

</blockquote></details>

Done.
___
*[pkg/sql/alter_database.go, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58725#-MQnKMFK08fY2_8GXj_F:-MQoOYm6AqlTL63pW2ZU:btqak73) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcc153431e8da63a819a07efc0d1e8bf496eb09f/pkg/sql/alter_database.go#L289)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

n.desc.RegionConfig.PrimaryRegion != "" should do.
</blockquote></details>

I'm probably missing something, but not sure how this check helps. Here we're trying to confirm that the proposed primary region is one of the regions already added to the database.  Does checking the descriptor's primary region help?
___
*[pkg/sql/alter_database.go, line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58725#-MQnKS0tE4i52IleBvtL:-MQoP9Nj5qFtPslp2igp:b-ic0ydj) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcc153431e8da63a819a07efc0d1e8bf496eb09f/pkg/sql/alter_database.go#L303)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i think we use the SQL escape string instead, i.e. n.n.Name.String() (if that escapes items). %q does not escape SQL strings.
</blockquote></details>

Right, %s and n.n.Name.String() works.  The string cast also removes the escaped SQL, so I went that route, but what you're suggesting is better.
___
*[pkg/sql/alter_database.go, line 348 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58725#-MQnKdulE5RsGGQpUIb5:-MQoUPMB3j9Uo9jqA9K5:b9n0yre) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcc153431e8da63a819a07efc0d1e8bf496eb09f/pkg/sql/alter_database.go#L348)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: errors start with lower case.
do we need this check if we have validators that catch this?
</blockquote></details>

Good point!  I'd forgotten that our existing validators already check this condition (and much more).  Replaced all of this with a call to the validator.
___
*[pkg/sql/alter_database.go, line 359 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58725#-MQnLJJCE-athsJcLSUy:-MQoRHFR9Nxj46t5xJ5g:bg510id) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcc153431e8da63a819a07efc0d1e8bf496eb09f/pkg/sql/alter_database.go#L359)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

we don't (yet) have logic to iterate over every table and set a reasonable MR config for each one (with this change, it will inherit the same as database level).
(neither do we have logic for CREATE TABLE that if the database is multiregion, set a reasonable default)
can you add a TODO with an issue to cover this?
i think `ADD REGION` similarly has this issue.
</blockquote></details>

What are you worried we'd have to change on each table?  The `PRIMARY REGION` should only impact the leaseholders for `REGIONAL BY TABLE` tables in the `PRIMARY REGION` and `GLOBAL` tables.  All of that should be inherited from the database level zone config.  

On `CREATE TABLE`, (for `REGIONAL BY TABLE IN <region>` and `REGIONAL BY ROW`) I'd expect that we'd handle this under the issue that adds the support.  Were you thinking differently?

We also have #58340 for `ADD REGION`.
___
*[pkg/sql/region_util.go, line 280 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58725#-MQnL5KrC0guDdUleet8:-MQoW56n16f0M4UJx9Z6:b-u2t2wf) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcc153431e8da63a819a07efc0d1e8bf496eb09f/pkg/sql/region_util.go#L280)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

hmm this issue is closed. @arulajmani ?
</blockquote></details>

fwiw, this was just copy pasta'd from the old location to here (unchanged).  If @arulajmani says we don't need it anymore, I'll remove the comment.

**Review by otan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58725)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @otan)

___
*[pkg/sql/alter_database.go, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58725#-MQnKMFK08fY2_8GXj_F:-MQoZZ6kEJXOYCWum63e:b-urbn4k) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcc153431e8da63a819a07efc0d1e8bf496eb09f/pkg/sql/alter_database.go#L289)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

I'm probably missing something, but not sure how this check helps. Here we're trying to confirm that the proposed primary region is one of the regions already added to the database.  Does checking the descriptor's primary region help?
</blockquote></details>

oh i misread this check. forgive me.
___
*[pkg/sql/alter_database.go, line 359 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58725#-MQnLJJCE-athsJcLSUy:-MQo_43j8k7hg8DBbDtg:bot9orh) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcc153431e8da63a819a07efc0d1e8bf496eb09f/pkg/sql/alter_database.go#L359)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

What are you worried we'd have to change on each table?  The `PRIMARY REGION` should only impact the leaseholders for `REGIONAL BY TABLE` tables in the `PRIMARY REGION` and `GLOBAL` tables.  All of that should be inherited from the database level zone config.  

On `CREATE TABLE`, (for `REGIONAL BY TABLE IN <region>` and `REGIONAL BY ROW`) I'd expect that we'd handle this under the issue that adds the support.  Were you thinking differently?

We also have #58340 for `ADD REGION`.
</blockquote></details>

Ah ok forgot REGIONAL BY TABLE IN PRIMARY REGION was the default.
Yeah ok, this makes sense.
___
*[pkg/sql/alter_database.go, line 304 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58725#-MQoZeGr7OvLAYtPMj6n:-MQoZeGr7OvLAYtPMj6o:blb9433) ([raw file](https://github.com/cockroachdb/cockroach/blob/1cfcaa9f8de26f585be18ef1316df8bb177980b8/pkg/sql/alter_database.go#L304)):*
> ```Go
> 			pgerror.Newf(pgcode.InvalidName,
> 				"region %s has not been added to the database. "+
> 					"Please add the region to the database before setting it as primary region.",
> ```

super nit: i think call to actions should be part of the HINT (i.e. the second sentence) -- the error should just be what the issue is "region %s has not been added to the database".
(also Please is not in imperative voice :P it's too polite!)
___
*[pkg/sql/region_util.go, line 280 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58725#-MQnL5KrC0guDdUleet8:-MQo_Up89q3TrCLn1UhO:bv2wn76) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcc153431e8da63a819a07efc0d1e8bf496eb09f/pkg/sql/region_util.go#L280)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

fwiw, this was just copy pasta'd from the old location to here (unchanged).  If @arulajmani says we don't need it anymore, I'll remove the comment.
</blockquote></details>

Yeah I realised, but wanted to bring it to arul's attention :)

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58725)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @otan)

___
*[pkg/sql/alter_database.go, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58725#-MQnKMFK08fY2_8GXj_F:-MQqd46wB4BH9g9uAo3z:b-p5jk17) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcc153431e8da63a819a07efc0d1e8bf496eb09f/pkg/sql/alter_database.go#L289)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

oh i misread this check. forgive me.
</blockquote></details>

Forgiven.
___
*[pkg/sql/alter_database.go, line 304 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58725#-MQoZeGr7OvLAYtPMj6n:-MQqd7GU25NnTGGfsLuE:bdf5uwd) ([raw file](https://github.com/cockroachdb/cockroach/blob/1cfcaa9f8de26f585be18ef1316df8bb177980b8/pkg/sql/alter_database.go#L304)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

super nit: i think call to actions should be part of the HINT (i.e. the second sentence) -- the error should just be what the issue is "region %s has not been added to the database".
(also Please is not in imperative voice :P it's too polite!)
</blockquote></details>

Fixed.  I also dropped the Canadian politeness, as per your request.  Sorry for bring it up in the first place :P 
___
*[pkg/sql/region_util.go, line 280 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58725#-MQnL5KrC0guDdUleet8:-MQqdGPZEEaNRpjCukep:b-4q7u9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcc153431e8da63a819a07efc0d1e8bf496eb09f/pkg/sql/region_util.go#L280)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Yeah I realised, but wanted to bring it to arul's attention :)
</blockquote></details>

@arulajmani I'm going to push.  Let me know what you want me to do with this comment.  I'll be in this code with my next PR anyway.

**Comment by ajstorm** [comment]
TFTR @otan!

bors r=otan

**Comment by ajstorm** [comment]
More linter generated file merge problems.  One more time...

bors r=otan

**Comment by ajstorm** [comment]
And, because the third time was the charm yesterday... 🤞 

bors r=otan

**Comment by ajstorm** [comment]
One more time...

bors r=otan

**Pull request merged**
