### PR TITLE
cherry-pick 2.0: sql: fix CREATE TABLE AS with subqueries, also cure major wart 

### PR DESCRIPTION
**Pull request by knz**
Picks #23017.

### CODE REVIEW

**Comment by jordanlewis** [comment]
Looks like there are some tracing differences. I think this might actually be my fault - I didn't cherrypick several tracing changes that I made on master. I will make that happen.

**Comment by knz** [comment]
ok thanks

**Comment by knz** [comment]
rebased; ptal

**Comment by knz** [comment]
Merging this since this now picks up your earlier changes.

**Pull request merged**
