### PR TITLE
sqlccl: use settings pkg for enterprise flag

### PR DESCRIPTION
**Pull request by dt**

### CODE REVIEW

**Comment by dt** [comment]
let the bikeshed begin: should we still read the env var? should we then persist it to the table? what if nodes have different values?

**Comment by bdarnell** [comment]
:lgtm:

+1 to getting rid of the env var. I don't think we should have something that's controlled by both an env-var or flag and a cluster setting.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14825#-:-KhU9uEmHjP1Nwjex0yp:brgldxb)*

**Comment by dt** [comment]
fwiw, my vote is also to kill the env vars.

**Comment by benesch** [comment]
Also LGTM, and I also vote we kill the env vars! I guess we should write a boot-and-set-enterprise-enabled script and stash it somewhere accessible, too.

**Comment by danhhz** [comment]
lgtm and also +1 on getting rid of env var. i've changed my mind since yesterday

**Comment by dt** [comment]
Did the TODO to switch to `SET`.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14825#-:-KhXisUoys4p6LE1Sh12:b-29j2af)*

**Comment by tamird** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14825)*

**Pull request merged**
