### PR TITLE
changefeedccl: Add query parameter for specifying certificates for schema registries

### LINKED ISSUE #64622: Add query parameter for specifying certificates for schema registries
CRDB does not have a way to specifying which CA to trust for schema registries. This can be a blocking problem for Cockroach Cloud users (see https://github.com/cockroachdb/cockroach/issues/42882).

We should add a param to specify the certificate to trust for schema registries, like the client_cert param that we already have.

registry_client_cert: The base64-encoded Privacy Enhanced Mail (PEM) certificate. This is used with registry_client_key.
Sink type: Kafka
Type: String 

registry_client_key: The base64-encoded private key for the PEM certificate. This is used with registry_client_cert.
Sink type: Kafka
Type: String

### PR DESCRIPTION
**Pull request by spiffyy99**
changefeedccl: Add query parameter for specifying certificates for schema registries

Added query params to schema registry  URL to indicate custom CA
certificates to trust while dialing Confluent schema registries.

Resolves #64622

Release note (enterprise change): Added ca_cert as a query param
to Confluent registry schema URL to trust custom certs on connection.

### CODE REVIEW

**Review by stevendanna — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65431)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @spiffyyeng)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/65431#-Ma9LoNo0Rzn_JaoT9Vu:-Ma9LoNo0Rzn_JaoT9Vv:b-7p7ift) (no related file):*
Thanks for working on this!

I didn't do a line-by-line review yet, but I wanted to get some of my larger concerns to you for consideration.  Happy to discuss any of them further!

---
___
*[pkg/ccl/changefeedccl/encoder.go, line 374 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65431#-Ma9JfcY-u8C53Umym5D:-Ma9JfcY-u8C53Umym5E:b-675tf0) ([raw file](https://github.com/cockroachdb/cockroach/blob/295c680b9f488f64a6031ff715aa765159ec27f5/pkg/ccl/changefeedccl/encoder.go#L374)):*
> ```Go
> 			return errors.Wrapf(err, `param %s must be a bool`, changefeedbase.SinkParamRegistryTLSEnabled)
> 		}
> 	}
> ```

Over in sink_kafka there is a consumeBool helper func, perhaps we can promote that to a method on the sinkURL struct itself?  However, in my other comment I argue for removing this option altogether so perhaps that isn't necessary.
___
*[pkg/ccl/changefeedccl/encoder.go, line 389 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65431#-Ma9I0QI2WjJtb8EjLmz:-Ma9I0QI2WjJtb8EjLn-:b-4pr5p) ([raw file](https://github.com/cockroachdb/cockroach/blob/295c680b9f488f64a6031ff715aa765159ec27f5/pkg/ccl/changefeedccl/encoder.go#L389)):*
> ```Go
> 		}
> 	} else if caCert != nil {
> 		return errors.Errorf(`%s requires %s=true`, changefeedbase.SinkParamRegistryCACert, changefeedbase.SinkParamRegistryTLSEnabled)
> ```

Can we avoid _requiring_ the tls_enabled flag here.  We have that option for kafka because there is know way to know from the schema whether it expects TLS or not.  But for the schema registry, whether or not to use TLS is clear from the schema being used (http vs https). 

If we went the route of not requiring the tls_enabled flag, it might be nice to warn the user if they've specified a ca with an http sink.
___
*[pkg/ccl/changefeedccl/tls.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65431#-Ma9HNUZ0FOc-6RNeN-a:-Ma9HNUZ0FOc-6RNeN-b:bngdw00) ([raw file](https://github.com/cockroachdb/cockroach/blob/295c680b9f488f64a6031ff715aa765159ec27f5/pkg/ccl/changefeedccl/tls.go#L76)):*
> ```Go
> 	}
> 
> 	client := &httputil.Client{
> ```

This is used as an alternative to the DefaultClient.  The default client additionally sets some timeouts and disables keepalives.  It might be good to avoid having different behaviors between the client.  We could do that by calling NewClientWithTimeout here and then mutating the returned struct.
___
*[pkg/ccl/changefeedccl/tls.go, line 139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65431#-Ma9M3VA2ZsQcfftwv7e:-Ma9M3VA2ZsQcfftwv7f:b5drmd8) ([raw file](https://github.com/cockroachdb/cockroach/blob/295c680b9f488f64a6031ff715aa765159ec27f5/pkg/ccl/changefeedccl/tls.go#L139)):*
> ```Go
> 	}
> 	return ret, nil
> }
> ```

We've got some of these TLS-related functions in a few places now.  Perhaps as a follow-up we could work on a nice util package where we could share them.  Not necessary in this PR though.
___
*[pkg/ccl/changefeedccl/changefeedbase/options.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65431#-Ma9LOTy0yOslNrYVBWo:-Ma9LOTy0yOslNrYVBWp:bhgd6lo) ([raw file](https://github.com/cockroachdb/cockroach/blob/295c680b9f488f64a6031ff715aa765159ec27f5/pkg/ccl/changefeedccl/changefeedbase/options.go#L95)):*
> ```Go
> 	SinkParamFileSize           = `file_size`
> 	SinkParamRegistryCACert     = `registry_ca_cert`
> 	SinkParamRegistryTLSEnabled = `registry_tls_enabled`
> ```

I feel like it is a bit odd for these to be URL parameters to the kafka parameters while the registry URL itself is an option.  Perhaps these should be options?

**Review by miretskiy — CHANGES_REQUESTED** [review]
> Reviewed 5 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65431)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @spiffyyeng and @stevendanna)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65431#-Ma9JNWA2V7fPhJ0GrUN:-Ma9JNWA2V7fPhJ0GrUO:b4n0p5g) ([raw file](https://github.com/cockroachdb/cockroach/blob/295c680b9f488f64a6031ff715aa765159ec27f5/pkg/ccl/changefeedccl/changefeed_processors.go#L165)):*
> ```Go
> 	}
> 
> 	if ca.encoder, err = getEncoder(ca.spec.Feed.Opts, ca.spec.Feed.Targets, &sinkURL{URL: parsedSink}); err != nil {
> ```

I'm a bit confused why we need to pass SinkURI to create an encoder.  It appears that the schema registry cert params could have been specified as part of the `confluent_schema_registry` option (which has to be specified anyway)?  Why do we want to add these schema specific params to SinkURI?
___
*[pkg/ccl/changefeedccl/encoder.go, line 374 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65431#-Ma9JfcY-u8C53Umym5D:-Ma9QRz3Ay1BHHOBorxx:blchgy0) ([raw file](https://github.com/cockroachdb/cockroach/blob/295c680b9f488f64a6031ff715aa765159ec27f5/pkg/ccl/changefeedccl/encoder.go#L374)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Over in sink_kafka there is a consumeBool helper func, perhaps we can promote that to a method on the sinkURL struct itself?  However, in my other comment I argue for removing this option altogether so perhaps that isn't necessary.
</blockquote></details>

Also, I'd love to pull out some of the tls option parsing and setup into some helper methods.
___
*[pkg/ccl/changefeedccl/tls.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65431#-Ma9HNUZ0FOc-6RNeN-a:-Ma9RFSd3shC2WQSv-It:b-uys7ae) ([raw file](https://github.com/cockroachdb/cockroach/blob/295c680b9f488f64a6031ff715aa765159ec27f5/pkg/ccl/changefeedccl/tls.go#L76)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

This is used as an alternative to the DefaultClient.  The default client additionally sets some timeouts and disables keepalives.  It might be good to avoid having different behaviors between the client.  We could do that by calling NewClientWithTimeout here and then mutating the returned struct.
</blockquote></details>

Just a note to self: I assume we handle timeouts in http/https talking to registry much the same way we'd handle sink errors -- i.e. by retrying the whole changefeed.
___
*[pkg/ccl/changefeedccl/tls.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65431#-Ma9Qk6x42ySn_QwR9Uj:-Ma9Qk6x42ySn_QwR9Uk:b-2ra9f4) ([raw file](https://github.com/cockroachdb/cockroach/blob/295c680b9f488f64a6031ff715aa765159ec27f5/pkg/ccl/changefeedccl/tls.go#L88)):*
> ```Go
> }
> 
> func generateCACert(priv *rsa.PrivateKey) ([]byte, *x509.Certificate, error) {
> ```

This looks like a test function -- it doesn't belong here, actually, majority of these methods).
You might consider moving them to tls_test.go, or even tls.go under cdctest package.

**Comment by amruss** [comment]
> Can we avoid requiring the tls_enabled flag here. We have that option for kafka because there is no way to know from the schema whether it expects TLS or not. But for the schema registry, whether or not to use TLS is clear from the schema being used (http vs https).
>If we went the route of not requiring the tls_enabled flag, it might be nice to warn the user if they've specified a ca with an http sink.

Both of those things make sense to me - definitely don't think we should add the tls flag if it isn't needed. We'll just have to be careful of how we doc it- warning is also a good idea. 

>I feel like it is a bit odd for these to be URL parameters to the kafka parameters while the registry URL itself is an option. Perhaps these should be options?

Two thoughts for making it a query param: 1) ca_cert is specified as a query param 2) Normally the pattern is sink-specific stuff goes in as a query param, which was kind of the thinking here. Per our discussion earlier, confluent schema registry doesn't _necessarily_ need to be used for kafka, so maybe that's actually a reason to use an option instead.


> I'm a bit confused why we need to pass SinkURI to create an encoder. It appears that the schema registry cert params could have been specified as part of the confluent_schema_registry option (which has to be specified anyway)? Why do we want to add these schema specific params to SinkURI?

What would specifying it this way look like?

**Comment by miretskiy** [comment]
@amruss 
Re: `What would specifying it this way look like`
Something like `WITH confluent_schema_registry='https://......?ca_cert....`

**Comment by spiffyyeng** [comment]
@miretskiy @amruss @stevendanna okay, I've changed it so that the registry schema URL has a query param `ca_cert` that accomplishes this. maybe we should add a new docs section for these separate query params if they increase in count?

**Review by miretskiy — APPROVED** [review]
This :lgtm:, but please wait for @stevendanna to also chime in.

> Reviewed 7 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65431#-:-MaEfjXe6StNkoOhd3NC:b-8wa5mg)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @miretskiy, @spiffyyeng, and @stevendanna)

___
*[pkg/ccl/changefeedccl/encoder_test.go, line 381 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65431#-Ma9S4YvEqjNEVssr5Ly:-Ma9S4YvEqjNEVssr5Lz:bx58znr) ([raw file](https://github.com/cockroachdb/cockroach/blob/295c680b9f488f64a6031ff715aa765159ec27f5/pkg/ccl/changefeedccl/encoder_test.go#L381)):*
> ```Go
> 	}
> 
> 	t.Run("format=experimental_avro,envelope=key_only", func(t *testing.T) {
> ```

if you feel adventurous, you can end and end to end test to changefeed_stmt, where you can try running kafkaFeed (you'd need to rebase on master to get kafkaFeed for tests). Also, you'd probably need to change kafkaFeed implementation a bit to create registry w/ tls.

**Review by stevendanna — COMMENTED** [review]
I left a few more comments.  Overall this is moving in the right direction I think.  Let me know if you want to talk synchronously about any of them.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65431#-:-MaEhX5y6j2LbtBSECsX:btklq29)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @miretskiy, @spiffyyeng, and @stevendanna)

___
*[pkg/ccl/changefeedccl/encoder.go, line 287 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65431#-MaEe8l111a7tf_iukdn:-MaEe8l111a7tf_iukdo:b-ugru2k) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3e1d02434ac2ea2ceae5843b217d6bbdb4fb20e/pkg/ccl/changefeedccl/encoder.go#L287)):*
> ```Go
> 	resolvedCache map[string]confluentRegisteredEnvelopeSchema
> 
> 	httpClient *httputil.Client
> ```

:thinking: [just thinking out loud] In the general case`http.Client` has a CloseIdleConnections method that we might want to call when we no longer need a http.Client that isn't going to live for the lifetime of the program.  However, since our httputil.Client sets DisableKeepalives, I don't think we _have_ to call it since by default our connections will only be used for a single request.
___
*[pkg/ccl/changefeedccl/encoder.go, line 361 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65431#-MaEfCvC4AvQCMrlwUnv:-MaEfCvC4AvQCMrlwUnw:b-tz1xbn) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3e1d02434ac2ea2ceae5843b217d6bbdb4fb20e/pkg/ccl/changefeedccl/encoder.go#L361)):*
> ```Go
> 	regURL, err := url.Parse(e.registryURL)
> 	if err != nil {
> 		return errors.Errorf("failed parsing registry url:%s due to error:%v", e.registryURL, err)
> ```

When wrapping an error like this, there are some functions you can call specifically for wrapping that you might want to prefer:

```go
errors.Wrapf(err, "failed parsing registry url %q", e.registryURL)
```
___
*[pkg/ccl/changefeedccl/encoder.go, line 367 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65431#-MaEiA0n7zU7xl3Bb3jC:-MaEiA0oEf9kDMOkiXP3:biw5eu0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3e1d02434ac2ea2ceae5843b217d6bbdb4fb20e/pkg/ccl/changefeedccl/encoder.go#L367)):*
> ```Go
> 	var caCert []byte
> 
> 	if caCertString := params.Get(changefeedbase.RegistryParamCACert); caCertString != "" {
> ```

I agree that ca_cert as a parameter to the registry URL feels better than as a parameter to the kafka URL, but I think this will pose a problem we need to address:

We are leaving the ca_cert query parameter on the URL.  Are we sure that Confluent's schema registry implementation will allow this?  Our test schema registry is very accepting of all requests, so my guess is if we only tested against the test implementation we won't see a problem.

Conversely, since this is an HTTP API we are talking to, perhaps some other schema registry implementation _requires_ query parameters that have nothing to do with us but conflicts with parameters we think we control?  How do we know if the query parameter we are using is actually safe to remove?

For now, we could punt on the harder version of this question and say that we control the ca_cert parameter and that we don't send it onto the schema registry if it is provided. 
___
*[pkg/ccl/changefeedccl/encoder.go, line 377 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65431#-MaEcBLU8RYdoBGmDVBF:-MaEcBLU8RYdoBGmDVBG:b6m2drr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3e1d02434ac2ea2ceae5843b217d6bbdb4fb20e/pkg/ccl/changefeedccl/encoder.go#L377)):*
> ```Go
> 		var err error
> 		e.httpClient, err = newClientFromTLSKeyPair(caCert)
> 		if strings.HasPrefix(e.registryURL, "http://") {
> ```

The parsed URL you constructed above should have a `Scheme` member that you can compare directly against.
___
*[pkg/ccl/changefeedccl/encoder.go, line 378 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65431#-MaEfaNn9oRIUqleEdtG:-MaEfaNn9oRIUqleEdtH:b-mng8vk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3e1d02434ac2ea2ceae5843b217d6bbdb4fb20e/pkg/ccl/changefeedccl/encoder.go#L378)):*
> ```Go
> 		e.httpClient, err = newClientFromTLSKeyPair(caCert)
> 		if strings.HasPrefix(e.registryURL, "http://") {
> 			log.Warningf(context.Background(), "attempting to use CA cert for schema registry:%s with HTTP scheme", e.registryURL)
> ```

Perhaps

```go
			log.Warningf(context.Background(), "CA certificate provided but schema registry %q uses HTTP", e.registryURL)
```
___
*[pkg/ccl/changefeedccl/encoder_test.go, line 321 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65431#-MaEcfBTEq5i_oE9pqBV:-MaEcfBTEq5i_oE9pqBW:b7xzt2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3e1d02434ac2ea2ceae5843b217d6bbdb4fb20e/pkg/ccl/changefeedccl/encoder_test.go#L321)):*
> ```Go
> }
> 
> func NewCACertBase64Encoded() (*tls.Certificate, string, error) {
> ```

I don't think we need to export this
___
*[pkg/ccl/changefeedccl/tls.go, line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65431#-MaEgow83NGM-aHhloz_:-MaEgow83NGM-aHhloza:b-g870m9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3e1d02434ac2ea2ceae5843b217d6bbdb4fb20e/pkg/ccl/changefeedccl/tls.go#L54)):*
> ```Go
> 	if !rootCAs.AppendCertsFromPEM(caCert) {
> 		return nil, errors.Errorf("failed to parse certificate data:%s", string(caCert))
> 	}
> ```

Not to self, looks like AppedCertsFromPem deals with len(caCerts) == 0 without returning an error, which is likely what we want.
___
*[pkg/ccl/changefeedccl/tls.go, line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65431#-MaE_1pE3STrjfsvXuMJ:-MaE_1pE3STrjfsvXuMK:byueaf4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3e1d02434ac2ea2ceae5843b217d6bbdb4fb20e/pkg/ccl/changefeedccl/tls.go#L65)):*
> ```Go
> 
> 	clientWrapper := httputil.NewClientWithTimeout(httputil.StandardHTTPTimeout)
> 	clientWrapper.Client = client
> ```

I don't think this is quite what you want since it is going to replace the entire client, which will still have the effect of constructing a client with different defaults.
___
*[pkg/util/httputil/client.go, line 25 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65431#-MaEa1yq6FAXkx0X05qj:-MaEa1yq6FAXkx0X05qk:b-q1w8hm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3e1d02434ac2ea2ceae5843b217d6bbdb4fb20e/pkg/util/httputil/client.go#L25)):*
> ```Go
> var DefaultClient = NewClientWithTimeout(StandardHTTPTimeout)
> 
> // StandardHTTPTimeout is the default timeeout to use for HTTP connections.
> ```

s/timeeout/timeout/

**Review by stevendanna — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65431)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @miretskiy and @spiffyyeng)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/65431#-MaSj3846gRgRA_8w2Ou:-MaSj3846gRgRA_8w2Ov:bnbvfwi) (no related file):*
:lgtm: Nice work!

I've left a few comments, but none are blocking, so take them or leave them.

As a follow-up, we might want to add something the the cdc/schemareg roachtest to make sure this is tested against the confluent schema registry occasionally.

Part of me still feels that an options-based way to pass the certs might be slightly cleaner, but this is more consistent.

---
___
*[pkg/ccl/changefeedccl/encoder.go, line 371 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65431#-MaSR0OL8up7YidLYFom:-MaSR0OL8up7YidLYFon:b-or6j3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bb2cc72863c61d414df7aafd996835f2831490e/pkg/ccl/changefeedccl/encoder.go#L371)):*
> ```Go
> 	regURL, err := url.Parse(e.registryURL)
> 	if err != nil {
> 		return errors.Wrapf(err, "failed parsing registry url:%s", e.registryURL)
> ```

[nit] I think in most places we would add a space after the `:`

```go
return errors.Wrapf(err, "failed parsing registry url: %s", e.registryURL)
```
___
*[pkg/ccl/changefeedccl/encoder.go, line 380 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65431#-MaSSDrf1cIkJ0vXsQsD:-MaSSDrf1cIkJ0vXsQsE:byjzv9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bb2cc72863c61d414df7aafd996835f2831490e/pkg/ccl/changefeedccl/encoder.go#L380)):*
> ```Go
> 		err := decodeBase64FromString(caCertString, &caCert)
> 		if err != nil {
> 			return errors.Wrapf(err, `param %s must be base 64 encoded`, changefeedbase.RegistryParamCACert)
> ```

[nit] We use a raw string here (backquotes) but double-quoted strings in the rest of this function.
___
*[pkg/ccl/changefeedccl/tls.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65431#-Ma9HNUZ0FOc-6RNeN-a:-MaSYIKc9b5-ziEZ-JN8:b-f9rk2k) ([raw file](https://github.com/cockroachdb/cockroach/blob/295c680b9f488f64a6031ff715aa765159ec27f5/pkg/ccl/changefeedccl/tls.go#L76)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Just a note to self: I assume we handle timeouts in http/https talking to registry much the same way we'd handle sink errors -- i.e. by retrying the whole changefeed.
</blockquote></details>

Yes, we mark the errors from the schema registry POST as Retryable.  We have 3 retries around that POST so it won't _immediately_ retry the whole changefeed.  It is worth noting that we should only be contacting the registry at startup and on schema changes.
___
*[pkg/ccl/changefeedccl/tls.go, line 61 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65431#-MaSa-WL6Ag78F4UbrBA:-MaSa-WL6Ag78F4UbrBB:b4sgglg) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bb2cc72863c61d414df7aafd996835f2831490e/pkg/ccl/changefeedccl/tls.go#L61)):*
> ```Go
> 
> 	client := httputil.NewClientWithTimeout(httputil.StandardHTTPTimeout)
> 	transport := client.Client.Transport.(*http.Transport)
> ```

If we wanted to be paranoid about NewClientWithTimeout changing such that this would panic, I suppose we could do something like:

```go
	if transport, ok := client.Client.Transport.(*http.Transport); ok {
		transport.TLSClientConfig = tlsConfig
		client.Client.Transport = transport
	} else {
		client.Client.Transport = &http.Transport{
			TLSClientConfig: tlsConfig,
		}
	}
```

But, we also have tests that will blow up if the type ever changes, so I'm cool with it as-is.

Interestingly, it looks like there aren't many callers of NewClientWithTimeout. I feel like in the long run, that httputil API isn't quite right as what you usually want to get is a Transport with all the default configuration and not a Client directly.  But, let's tackle that some other day.
___
*[pkg/ccl/changefeedccl/tls.go, line 63 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65431#-MaShihZAACngBAkTLVY:-MaShihZAACngBAkTLVZ:blifiew) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bb2cc72863c61d414df7aafd996835f2831490e/pkg/ccl/changefeedccl/tls.go#L63)):*
> ```Go
> 	transport := client.Client.Transport.(*http.Transport)
> 	transport.TLSClientConfig = tlsConfig
> 	client.Client.Transport = transport
> ```

Just as an FYI, I don't think you need to write this back because you are modifying it through the reference above.  But, it doesn't hurt anything and is perhaps a bit more clear.

**Pull request merged**
