### PR TITLE
build: upgrade to golang v1.21.3

### LINKED ISSUE #112088: *: upgrade to go 1.21
We want go 1.21 to support crdb 23.2.

Jira issue: CRDB-32231

### PR DESCRIPTION
**Pull request by rickystewart**
Fixes #112088.

* [x] Adjust the Pebble tests to run in new version.
* [x] Adjust version in the TeamCity agent image ([setup script](./packer/teamcity-agent.sh))
* [x] Update `build/teamcity/internal/release/build-and-publish-patched-go/impl.sh` with the new version and adjust SHA256 sums as necessary.
* [x] Adjust `GO_VERSION` and `GO_FIPS_COMMIT` for the FIPS Go toolchain ([source](./teamcity/internal/release/build-and-publish-patched-go/impl-fips.sh)).
* [ ] Run the `Internal / Cockroach / Build / Toolchains / Publish Patched Go for Mac` build configuration in TeamCity with your latest version of the script above. Note the job depends on another job `Build and Publish Patched Go`. That job prints out the SHA256 of all tarballs, which you will need to copy-paste into `WORKSPACE` (see below). `Publish Patched Go for Mac` is an extra step that publishes the *signed* `go` binaries for macOS. That job also prints out the SHA256 of the Mac tarballs in particular.
* [ ] Adjust `--@io_bazel_rules_go//go/toolchain:sdk_version` in [.bazelrc](../.bazelrc).
* [ ] Bump the version in `WORKSPACE` under `go_download_sdk`. You may need to bump [rules_go](https://github.com/bazelbuild/rules_go/releases). Also edit the filenames listed in `sdks` and update all the hashes to match what you built in the step above.
* [ ] Bump the version in `WORKSPACE` under `go_download_sdk` for the FIPS version of Go (`go_sdk_fips`).
* [ ] Run `./dev generate bazel` to refresh `distdir_files.bzl`, then `bazel fetch @distdir//:archives` to ensure you've updated all hashes to the correct value.
* [ ] Bump the go version in `go.mod`.
* [ ] Bump the default installed version of Go in `bootstrap-debian.sh` ([source](./bootstrap/bootstrap-debian.sh)).
* [ ] Replace other mentions of the older version of go (grep for `golang:<old_version>` and `go<old_version>`).
* [ ] Ask the Developer Infrastructure team to deploy new TeamCity agent images according to [packer/README.md](./packer/README.md)

Epic: none
Release note (general change): Updated Go version to 1.21.1

### CODE REVIEW

**Comment by rickystewart** [comment]
Blocked on many test failures related to the `context` patching, @miretskiy will investigate

**Comment by knz** [comment]
@miretskiy in go 1.21 `propagateCancel` is a method of context.Context, not a standalone function any more.

**Review by knz — COMMENTED** [review]
I have investigated more. Two results:

### Regarding the context stuff

I see that yevgueny tried to "prepare" things earlier in `pkg/util/ctxutil/link_1_21_bazel.go`; sadly that implementation seems incorrect. The `propagateCancel` _method_ in go 1.21 only exists over `context.cancelCtx`, and so the use of it inside (our own custom) `WhenDone()` is incorrect.

What we need to do is this:

1) add the following to `build/teamcity/internal/release/build-and-publish-patched-go/diff.patch`

```diff
diff --git a/src/context/context.go b/src/context/context.go
index ee66b43c85..5c451cf97f 100644
--- a/src/context/context.go
+++ b/src/context/context.go
@@ -423,6 +423,12 @@ type cancelCtx struct {
        cause    error                 // set to non-nil by the first cancel call
 }

+type ExportedCancelCtx = cancelCtx
+
+func (c *cancelCtx) ExportedPropagateCancel(parent Context, child canceler) {
+       c.propagateCancel(parent, child)
+}
+
 func (c *cancelCtx) Value(key any) any {
        if key == &cancelCtxKey {
                return c
```

2) review and incorporate the following PR here: #112089.


### Regarding the go scheduler stats

@rickystewart we also need to update `pkg/util/goschedstats/runtime_go1.20.go` to include when building with 1.21. (and modify `runtime_go1.19.go` to exclude when building 1.21.)

I have checked the definitions therein and they are valid for the 1.21 runtime.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111928#-:-NgNs13c2X3E-XZXorAe:by6rxoo)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by knz** [comment]
@rickystewart if we feel uncomfortable with the changes in #112088 I propose to move forward with your PR with a diff that makes `pkg/util/ctxutil/link_shared.go` prevail (i.e. use slow but safe path until we fix the problem).

**Comment by miretskiy** [comment]
> The `propagateCancel` _method_ in go 1.21 only exists over `context.cancelCtx`, and so the use of it inside (our own custom) `WhenDone()` is incorrect.

This is not correct -- I provided runtime patch that added exported function to context package to propagate cance.

**Comment by jbowens** [comment]
My understanding is we're no longer pursuing an upgrade to 1.21 for the 23.2 release, but we will still upgrade to 1.21 early within the 24.1 development cycle, right?

**Pull request closed without merging**
