### PR TITLE
sql, server: add skeleton TokenBucket connector and tenant resource limits configuration APIs

### PR DESCRIPTION
**Pull request by RaduBerinde**
This PR is a scaled back version of #67508 where we don't use the system table at all. It's meant to put some of the infrastructure pieces in place and provide a stub API for reconfiguration.

The plan is to add consumption metrics on top of this soon so that CC can develop in parallel.

---

#### server: add TokenBucket connector API

This change adds the TokenBucket API proposed in the RFC (#66436), a
stub implementation and client for it, and the corresponding KV
connector interface.

The client and server-side code lives in
ccl/multitenantccl/tenantcostclient and tenantcostserver.

Release note: None

#### sql: tenant resource limits configuration API

This commit adds a `crdb_internal.update_tenant_resource_limits`
internal SQL function (to be used by the system tenant) which updates
the token bucket configuration for a specific tenant.

Release note: None

### CODE REVIEW

**Comment by kernfeld-cockroach** [comment]
Thanks for the heads-up. I am good with the current proposed function signature.

Since we're planning to call this function every 10 seconds, I don't think it matters that much to be able to reject out-of-date or duplicate requests. But if we wanted to leave forwards compatibility for that functionality, I would suggest that we include a monotonically increasing 64-bit integer nonce value. CRDB would ignore it for the MVP. But also, if there's not going to be a reasonable place to store the value anyways then there's likely no point adding it.

**Review by ajwerner — COMMENTED** [review]
> But if we wanted to leave forwards compatibility for that functionality, I would suggest that we include a monotonically increasing 64-bit integer nonce value. CRDB would ignore it for the MVP. But also, if there's not going to be a reasonable place to store the value anyways then there's likely no point adding it.

I assumed that the implementation of the client library would be tracking such a nonce inside the implementation of `TenantSideCostController`. Such a thing will need to exist. The SQL pod shouldn't be calling the gRPC method directly IIUC. 

> Reviewed 32 of 32 files at r1, 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67768#-:-Mf4ifZH5PLk09fwyGRY:btzgfs4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/ccl/kvccl/kvtenantccl/connector.go, line 396 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67768#-Mf4fS4O6l0zLdxIQmaS:-Mf4fS4O6l0zLdxIQmaT:b5f0qye) ([raw file](https://github.com/cockroachdb/cockroach/blob/2850092c53e44267ae3bd137bff6b59e35f31d3b/pkg/ccl/kvccl/kvtenantccl/connector.go#L396)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 	for ctx.Err() == nil {
> 		client, err := c.getClient(ctx)
> 		if err != nil {
> 			continue
> 		}
> ```
</details>

No logging or backoff?
___
*[pkg/ccl/kvccl/kvtenantccl/connector.go, line 399 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67768#-Mf4fj3l8jvrX3Sni_a0:-Mf4fj3l8jvrX3Sni_a1:bpyz11m) ([raw file](https://github.com/cockroachdb/cockroach/blob/2850092c53e44267ae3bd137bff6b59e35f31d3b/pkg/ccl/kvccl/kvtenantccl/connector.go#L399)):*
> ```Go
> 		resp, err := client.TokenBucket(ctx, in)
> 		if err != nil {
> 			log.Warningf(ctx, "error issuing RangeLookup RPC: %v", err)
> ```

I see now that this is copy-pasta. Should we refactor out a helper?
___
*[pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67768#-Mf4gd-OCSR4aBki4pqI:-Mf4gd-PExgtcrIrvcXc:b-c6isks) ([raw file](https://github.com/cockroachdb/cockroach/blob/2850092c53e44267ae3bd137bff6b59e35f31d3b/pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go#L41)):*
> ```
> 	if err := stopper.RunAsyncTask(context.Background(), "refresher", func(ctx context.Context) {
> 		c.mainLoop(ctx)
> 	}); err != nil {
> ```
Thoughts on a start method? I generally dislike goroutines running under a stopper before calls to `Start`. I know they exist but I don't like them. 
___
*[pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67768#-Mf4hDU_6AKksUTnxaRH:-Mf4hDU_6AKksUTnxaRI:b-2p17sx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2850092c53e44267ae3bd137bff6b59e35f31d3b/pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go#L55)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 		if err := updateTenantUsageState(ctx, s.executor, txn, tenantID, state); err != nil {
> 			return err
> 		}
> 		return nil
> ```
</details>

nit: `return updateTenantUsageState(ctx, s.executor, txn, tenantID, state)`
___
*[pkg/multitenant/tenant_usage.go, line 11 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67768#-Mf4iNJg6U_jQ0m-8-21:-Mf4iNJg6U_jQ0m-8-22:b2go4xt) ([raw file](https://github.com/cockroachdb/cockroach/blob/489c40bc4773416f4add48db72415dd0de023ca6/pkg/multitenant/tenant_usage.go#L11)):*
> ```Go
> // licenses/APL.txt.
> 
> package multitenant
> ```

nit: add a `doc.go` or a package comment here
___
*[pkg/server/tenant.go, line 392 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67768#-Mf4gG4p9_OwSWMczaM3:-Mf4gG4p9_OwSWMczaM4:b-c2hjzw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2850092c53e44267ae3bd137bff6b59e35f31d3b/pkg/server/tenant.go#L392)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> // TenantSideCostController is an interface through which tenants report and
> // throttle resource usage.
> type TenantSideCostController interface {
> 	// TODO(radu)
> }
> ```
</details>


Why define this here and not in the `multitenant` package I was going to suggest you create but you already did in the second commit?

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67768)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67768#-Mf4mDPL4tHdtb1KS6eK:-Mf4mDPL4tHdtb1KS6eL:b-z7ixhq) ([raw file](https://github.com/cockroachdb/cockroach/blob/489c40bc4773416f4add48db72415dd0de023ca6/pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go#L34)):*
> ```Go
> 
> 	result := &roachpb.TokenBucketResponse{}
> 	if err := s.db.Txn(ctx, func(ctx context.Context, txn *kv.Txn) error {
> ```

How come it isn't possible to make this a single SQL statement that selects the current state and then updates it?
___
*[pkg/ccl/multitenantccl/tenantcostserver/tenanttokenbucket/tenant_token_bucket.go, line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67768#-Mf4mTwm2ezK_Hhjv-2Y:-Mf4mTwm2ezK_Hhjv-2Z:bv1761m) ([raw file](https://github.com/cockroachdb/cockroach/blob/489c40bc4773416f4add48db72415dd0de023ca6/pkg/ccl/multitenantccl/tenantcostserver/tenanttokenbucket/tenant_token_bucket.go#L23)):*
> ```Go
> type State struct {
> 	// Burst limit in RUs.
> 	RUBurstLimit float64
> ```

super nit: idiomatic Go would use field names as the first word in each comment.

**Review by RaduBerinde — COMMENTED** [review]
TFTRs!

> I assumed that the implementation of the client library would be tracking such a nonce inside the implementation of TenantSideCostController

Correct, the above is referring to the host-side reconfiguration API (for changing the refill rate etc)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67768#-:-Mf4kuEz8m2ZgdxKYD_v:bl989xd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @andy-kimball)

___
*[pkg/ccl/kvccl/kvtenantccl/connector.go, line 399 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67768#-Mf4fj3l8jvrX3Sni_a0:-Mf4qVRwAjZTjzmagFoh:b-d6y3h2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2850092c53e44267ae3bd137bff6b59e35f31d3b/pkg/ccl/kvccl/kvtenantccl/connector.go#L399)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I see now that this is copy-pasta. Should we refactor out a helper?
</blockquote></details>

I tried but couldn't find a clean way to do it; other functions have some "hard error" return paths that are hard to incorporate in a `func`. I agree it should be done but it will require some back and forth so I'll leave that out of this PR.

Fixed the RPC name.
___
*[pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67768#-Mf4gd-OCSR4aBki4pqI:-Mf4uPizCX4m6U9eZD58:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/2850092c53e44267ae3bd137bff6b59e35f31d3b/pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go#L41)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	if err := stopper.RunAsyncTask(context.Background(), "refresher", func(ctx context.Context) {
> 		c.mainLoop(ctx)
> 	}); err != nil {
> ```
Thoughts on a start method? I generally dislike goroutines running under a stopper before calls to `Start`. I know they exist but I don't like them. 
</blockquote></details>

Good point, done.
___
*[pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67768#-Mf4mDPL4tHdtb1KS6eK:-Mf4oUyuEzzx4YJ_3zHU:b-yif2mv) ([raw file](https://github.com/cockroachdb/cockroach/blob/489c40bc4773416f4add48db72415dd0de023ca6/pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go#L34)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

How come it isn't possible to make this a single SQL statement that selects the current state and then updates it?
</blockquote></details>

How? By having some internal SQL function?

I don't know how we could make that work with the new proposal, where we have to interact with two rows.

In any case, I will start with a simple implementation and take it from there.
___
*[pkg/ccl/multitenantccl/tenantcostserver/tenanttokenbucket/tenant_token_bucket.go, line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67768#-Mf4mTwm2ezK_Hhjv-2Y:-Mf4v27p1xxOIfJaPq31:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/489c40bc4773416f4add48db72415dd0de023ca6/pkg/ccl/multitenantccl/tenantcostserver/tenanttokenbucket/tenant_token_bucket.go#L23)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

super nit: idiomatic Go would use field names as the first word in each comment.
</blockquote></details>

Done.
___
*[pkg/server/tenant.go, line 392 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67768#-Mf4gG4p9_OwSWMczaM3:-Mf4vc-_32BuB_zFvZYG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2850092c53e44267ae3bd137bff6b59e35f31d3b/pkg/server/tenant.go#L392)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> // TenantSideCostController is an interface through which tenants report and
> // throttle resource usage.
> type TenantSideCostController interface {
> 	// TODO(radu)
> }
> ```

Why define this here and not in the `multitenant` package I was going to suggest you create but you already did in the second commit?
</blockquote></details>

Done.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67768)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andy-kimball, and @RaduBerinde)

___
*[pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67768#-Mf4mDPL4tHdtb1KS6eK:-Mf5CswC57G42oW34bkl:b-na81hz) ([raw file](https://github.com/cockroachdb/cockroach/blob/489c40bc4773416f4add48db72415dd0de023ca6/pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go#L34)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

How? By having some internal SQL function?

I don't know how we could make that work with the new proposal, where we have to interact with two rows.

In any case, I will start with a simple implementation and take it from there.
</blockquote></details>

I just mean an `INSERT INTO foo SELECT ... FROM foo` kind of thing. Doesn't the code you have here run into serializability conflicts when multiple SQL pods call at the same time? If it were a single INSERT/SELECT statement that used FOR UPDATE locking, we'd never hit conflicts (I suppose we could use `FOR UPDATE` in `readTenantUsage` as well). But maybe I'm not understanding exactly what `readTenantUsageState` and `updateTenantUsageState` will be doing - my assumption is that we read 1 row, then use the values in that row to create another (new) row.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67768)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @andy-kimball)

___
*[pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67768#-Mf4mDPL4tHdtb1KS6eK:-Mf5S5fL4IF7OFUA3OIw:b-cp5c6r) ([raw file](https://github.com/cockroachdb/cockroach/blob/489c40bc4773416f4add48db72415dd0de023ca6/pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go#L34)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I just mean an `INSERT INTO foo SELECT ... FROM foo` kind of thing. Doesn't the code you have here run into serializability conflicts when multiple SQL pods call at the same time? If it were a single INSERT/SELECT statement that used FOR UPDATE locking, we'd never hit conflicts (I suppose we could use `FOR UPDATE` in `readTenantUsage` as well). But maybe I'm not understanding exactly what `readTenantUsageState` and `updateTenantUsageState` will be doing - my assumption is that we read 1 row, then use the values in that row to create another (new) row.
</blockquote></details>

I will write up the new approach in the RFC when I get a chance (Andrew has a nice writeup in there, though we improved it a bit offline). We will be reading and updating two rows (but with no secondary index). We will use SELECT FOR UPDATE.

**Review by andy-kimball — APPROVED** [review]
I'm not too familiar with the surrounding code, but it :lgtm: with some small comments/questions. I'm approving now because I don't want you to get blocked too much longer, but hope that someone else in SQL can approve soon as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67768#-:-MfAG8xGER_iIlk8rLsr:bkh4xv7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @andy-kimball, and @RaduBerinde)

___
*[pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67768#-Mf4mDPL4tHdtb1KS6eK:-MfABb6N3XCdBRcTTaZJ:b53mm7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/489c40bc4773416f4add48db72415dd0de023ca6/pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go#L34)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I will write up the new approach in the RFC when I get a chance (Andrew has a nice writeup in there, though we improved it a bit offline). We will be reading and updating two rows (but with no secondary index). We will use SELECT FOR UPDATE.
</blockquote></details>

OK, I just want to confirm we're understanding each other: I'm suggesting that all this code could just be a single SQL statement that round-trips just once to the DB rather than twice, thus reducing how long we hold locks:
```
INSERT INTO the_tenant_usage_table
SELECT u.Seq+1, u.RU+$1, u.ReadRequests+$2, u.ReadBytes+$3, ...
FROM the_tenant_usage_table u
WHERE its_the_existing_last_row()
```
And you're saying that this approach won't work for some reason, or maybe that it's too complex, right? It's fine if that's the case, I just want to make sure we're not mis-communicating.
___
*[pkg/server/server.go, line 639 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/67768#-MfAFIH8AnjQ7EOrpmn9:-MfAFIH8AnjQ7EOrpmnA:b-900bf1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cc783c06e01ed914e1b8d44244233b103ea74e2/pkg/server/server.go#L639)):*
> ```Go
> 		tenantUsage,
> 	)
> 	node.admissionQ = gcoord.GetWorkQueue(admission.KVWork)
> ```

Looks like `admissionQ` is getting set twice here, once in the constructor, once after.

Also, is it possible to not need to create a TenantUsageServer if this is not a multi-tenant cluster? Or will it be cheap enough that it doesn't matter?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67768)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @andy-kimball, and @RaduBerinde)

___
*[pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67768#-Mf4mDPL4tHdtb1KS6eK:-MfAGxJ28ssVWraetZxc:b-8teu4m) ([raw file](https://github.com/cockroachdb/cockroach/blob/489c40bc4773416f4add48db72415dd0de023ca6/pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go#L34)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> INSERT INTO the_tenant_usage_table
> SELECT u.Seq+1, u.RU+$1, u.ReadRequests+$2, u.ReadBytes+$3, ...
> FROM the_tenant_usage_table u
> WHERE its_the_existing_last_row()
> ```
</details>


Whether you do it in a single statement and write it with the logic in SQL or do it in two statements, one which reads and the other which writes, it's roughly the same number of round-trips to the store. The advantage of the single-statement formulation is that I *think* we'll tell KV to commit in batch and thus hit the pure 1PC path with no intents.

**Comment by andy-kimball** [comment]
___
*[pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67768#-Mf4mDPL4tHdtb1KS6eK:-MfAIEt7AqQldPNtcb0y:b-nn8a1d) ([raw file](https://github.com/cockroachdb/cockroach/blob/489c40bc4773416f4add48db72415dd0de023ca6/pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go#L34)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> INSERT INTO the_tenant_usage_table
> SELECT u.Seq+1, u.RU+$1, u.ReadRequests+$2, u.ReadBytes+$3, ...
> FROM the_tenant_usage_table u
> WHERE its_the_existing_last_row()
> ```

Whether you do it in a single statement and write it with the logic in SQL or do it in two statements, one which reads and the other which writes, it's roughly the same number of round-trips to the store. The advantage of the single-statement formulation is that I *think* we'll tell KV to commit in batch and thus hit the pure 1PC path with no intents. 
</blockquote></details>

Yes, I was thinking of round-trips from an app tier to SQL, which doesn't apply here, since this would all be running in a built-in function on a SQL node. However, I think there's actually 3 round-trips instead of 2, since committing the explicit transaction requires one extra round-trip.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67768)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @andy-kimball)

___
*[pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67768#-Mf4mDPL4tHdtb1KS6eK:-MfBUV2O5UUBvW5Gbv_E:bxn0k7z) ([raw file](https://github.com/cockroachdb/cockroach/blob/489c40bc4773416f4add48db72415dd0de023ca6/pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go#L34)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Yes, I was thinking of round-trips from an app tier to SQL, which doesn't apply here, since this would all be running in a built-in function on a SQL node. However, I think there's actually 3 round-trips instead of 2, since committing the explicit transaction requires one extra round-trip.
</blockquote></details>

Yeah I understand, I'll keep it in mind and see if we can do something like that once we're further in the implementation.

It would be nice if we had a way to set up the transaction to autocommit on the UPDATE statement.
___
*[pkg/server/server.go, line 639 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/67768#-MfAFIH8AnjQ7EOrpmn9:-MfBWpOJAMEgrSFziPua:b4i8rb7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cc783c06e01ed914e1b8d44244233b103ea74e2/pkg/server/server.go#L639)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Looks like `admissionQ` is getting set twice here, once in the constructor, once after.

Also, is it possible to not need to create a TenantUsageServer if this is not a multi-tenant cluster? Or will it be cheap enough that it doesn't matter?
</blockquote></details>

Fixed the admissionQ.

Is there an easy way to tell if this is a multi-tenant cluster?

I don't think this server will do any background work if there are no tenant requests coming through, so it shouldn't be a problem.

**Pull request merged**
