### PR TITLE
sql: support tuples in index selection

### LINKED ISSUE #6206: sql: support tuple comparisons
Postgres supports comparing between tuples (semantically it's a lexicographical ordering):

```sql
SELECT * FROM t;
 k | a | b | c 
---+---+---+---
 1 | 1 | 2 | 3
 2 | 1 | 2 | 4
 3 | 1 | 3 | 0
 4 | 2 | 1 | 0
(4 rows)

SELECT * FROM t WHERE (a,b,c) > (1,2,3);
 k | a | b | c 
---+---+---+---
 2 | 1 | 2 | 4
 3 | 1 | 3 | 0
 4 | 2 | 1 | 0
(3 rows)
```

This can be useful for example when reading parts of a multi-column index. We don't support this (`pq: unsupported comparison operator: <tuple> < <tuple>`). To get the same behavior, the expression needs to be tediously rewritten:
```sql
SELECT * FROM t WHERE a > 1 OR (a = 1 AND (b > 2 OR (b = 2 AND c > 3)));
+---+---+---+---+
| k | a | b | c |
+---+---+---+---+
| 2 | 1 | 2 | 4 |
| 3 | 1 | 3 | 0 |
| 4 | 2 | 1 | 0 |
+---+---+---+---+
```

Note that we do support tuple equality/inequality.

### PR DESCRIPTION
**Pull request by madelynnblue**
Fixes #6206

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6332)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[sql/index_selection.go, line 571 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6332#-KGJG8FRHt3w7x8oOE_4:-KGJG8FSmgVElN_4Pa6j:-1657956657) ([raw file](https://github.com/cockroachdb/cockroach/blob/21ac6ea2462cd239cee78cc6ae6a28a18c141324/sql/index_selection.go#L571)):*
isn't this simply `if c.Operator != parser.In { .. }`?

---

*[sql/index_selection.go, line 575 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6332#-KGJGZD-as8nni7MKCs9:-KGJGZD-as8nni7MKCsA:-1378038648) ([raw file](https://github.com/cockroachdb/cockroach/blob/21ac6ea2462cd239cee78cc6ae6a28a18c141324/sql/index_selection.go#L575)):*
We should be able to use a prefix here, e.g. `(a,b,c) > (1,2,3)`  implies `(a, b) >= (1,2)`. Doesn't have to be in this change, but please add a TODO

---

*[sql/index_selection.go, line 1188 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6332#-KGJJVp-Kqjq1yGKjLo4:-KGJJVp-Kqjq1yGKjLo5:-1816736679) ([raw file](https://github.com/cockroachdb/cockroach/blob/21ac6ea2462cd239cee78cc6ae6a28a18c141324/sql/index_selection.go#L1188)):*
Comment needs some tweaking

---

*[sql/index_selection.go, line 1193 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6332#-KGJIIp1oTsVDBQBBxbu:-KGJIIp2gSXv8N9gTps1:-1475660399) ([raw file](https://github.com/cockroachdb/cockroach/blob/21ac6ea2462cd239cee78cc6ae6a28a18c141324/sql/index_selection.go#L1193)):*
I am not understanding how this works.. We are making this code support multiple columns but we are only looking at the direction of one of them? Where are we actually checking that each column in the index is in the direction we want?

---

*[sql/index_selection_test.go, line 528 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6332#-KGJIspF0fS7gsInfxiN:-KGJIspF0fS7gsInfxiO:500762097) ([raw file](https://github.com/cockroachdb/cockroach/blob/21ac6ea2462cd239cee78cc6ae6a28a18c141324/sql/index_selection_test.go#L528)):*
Please add tests with mixed directions, e.g. `a,b-`, `a-,b-`, `a-,b`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6332)*

**Comment by mjibson** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[sql/index_selection.go, line 571 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6332#-KGJG8FRHt3w7x8oOE_4:-KGJNVjUFB_WAG3uNV7R:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/21ac6ea2462cd239cee78cc6ae6a28a18c141324/sql/index_selection.go#L571)):*
Done.

---

*[sql/index_selection.go, line 575 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6332#-KGJGZD-as8nni7MKCs9:-KGJNtefR_rgMaDW1p4_:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/21ac6ea2462cd239cee78cc6ae6a28a18c141324/sql/index_selection.go#L575)):*
Done.

---

*[sql/index_selection.go, line 1188 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6332#-KGJJVp-Kqjq1yGKjLo4:-KGJQoE5BxjXQEsh5Frh:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/21ac6ea2462cd239cee78cc6ae6a28a18c141324/sql/index_selection.go#L1188)):*
Done.

---

*[sql/index_selection.go, line 1193 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6332#-KGJIIp1oTsVDBQBBxbu:-KGLMz_n4lMTjEhmivrj:2063088180) ([raw file](https://github.com/cockroachdb/cockroach/blob/21ac6ea2462cd239cee78cc6ae6a28a18c141324/sql/index_selection.go#L1193)):*
Ah. Good catch. I wanted to reuse the encodeStartConstraintAscending function (and its variants) so as to not rewrite a bunch of code.

I'm inclined to not support indexes with multiple directions, but mark that as a TODO. This would satisfy the purpose of this PR, which is to get index selection working with primary keys of multiple columns. Support arbitrary indexes could reasonably come at a later time.

Implementing the full solution here will be difficult. You can't just loop through each datum in the tuple and send them off to encode[Start|End]Constraint[As|De]scending because those functions are too smart and do things like run .PrefixEnd() on **each** datum. This makes the descending index tests decrement both the a and b keys instead of just the b key. That is, for (a, b ) => (1, 4), it spits out a span of -/0/3 instead of the expected -/1/3. This is all complicated enough that I think we should just not support mixed indexes for tuple comparison.

Thoughts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6332)*

**Comment by mjibson** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[sql/index_selection_test.go, line 528 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6332#-KGJIspF0fS7gsInfxiN:-KGLqChLK3L5pdzfTuO2:-655462736) ([raw file](https://github.com/cockroachdb/cockroach/blob/21ac6ea2462cd239cee78cc6ae6a28a18c141324/sql/index_selection_test.go#L528)):*
Tests added but not yet correct. PR is currently in flux.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6332)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[sql/index_selection.go, line 1193 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6332#-KGJIIp1oTsVDBQBBxbu:-KGMldgac0G5vDqit-YU:-1177103587) ([raw file](https://github.com/cockroachdb/cockroach/blob/21ac6ea2462cd239cee78cc6ae6a28a18c141324/sql/index_selection.go#L1193)):*
I'm ok with not supporting it for now (as long as we check for it correctly). IMO this code needs a rewrite (it shouldn't be so intertwined with how we map tables to KVs). I have some ideas; it will probably be easier to fully implement this when (or after) that is done.

But we should leave a issue open describing what is missing (in the long term we don't want holes like this).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6332)*

**Comment by RaduBerinde** [comment]
*[sql/index_selection.go, line 1193 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6332#-KGJIIp1oTsVDBQBBxbu:-KGMtvFPj4DJH7N2m3NE:-1693723491) ([raw file](https://github.com/cockroachdb/cockroach/blob/21ac6ea2462cd239cee78cc6ae6a28a18c141324/sql/index_selection.go#L1193)):*
I filed #6346 to track rewriting this stuff.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6332)*

**Comment by tamird** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/index_selection.go, line 528 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6332#-KGNjiRA2-uMe_ZiHQqA:-KGNjiRA2-uMe_ZiHQqB:-1203870697) ([raw file](https://github.com/cockroachdb/cockroach/blob/34c16b403f2465253ac98e0dc2067ed0a3cffdf6/sql/index_selection.go#L528)):*
maybe a more descriptive name? exprLoop?

---

*[sql/table.go, line 524 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6332#-KGNjQgvp6q2wEZyniiC:-KGNjQgwz9zsRub_4dne:1107980584) ([raw file](https://github.com/cockroachdb/cockroach/blob/34c16b403f2465253ac98e0dc2067ed0a3cffdf6/sql/table.go#L524)):*
nit: scope this more narrowly?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6332)*

**Comment by mjibson** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/index_selection.go, line 528 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6332#-KGNjiRA2-uMe_ZiHQqA:-KGNl1DATs7nrxIAZ6w-:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/34c16b403f2465253ac98e0dc2067ed0a3cffdf6/sql/index_selection.go#L528)):*
Done.

---

*[sql/table.go, line 524 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6332#-KGNjQgvp6q2wEZyniiC:-KGNky1ewCXYzK9c5x2P:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/34c16b403f2465253ac98e0dc2067ed0a3cffdf6/sql/table.go#L524)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6332)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6332#-:-KGOSlnEAePoAq58LCvj:1417088721)*

**Pull request merged**
