### PR TITLE
ui: split opt-in data from rest of helpus data

### PR DESCRIPTION
**Pull request by cuongdo**
This makes the helpus flow store the `optin` field separately from the
rest of the `OptInAttributes`, so that the server can query it cleanly.

Also modified the usage reporting code to read the optin status by
calling the `(*adminServer).GetUIData()` method directly, removing an
ugly hack from `SetUIData()`.

To make this happen cleanly, I changed the GET /uidata API to retrieve
multiple keys.

Combined with my other change to set multiple keys at once, this change
allows the admin UI to more easily break up its gets/sets of uidata into 
multiple keys. This is important when the server needs to query the uidata,
since we don't want to be manipulating JSON too much in the server.

cc @tamird (since we discussed this), @maxlang, @dt (for the cluster info reporting changes)

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5564)

### CODE REVIEW

**Comment by mrtracy** [comment]
I don't see the 

---

Reviewed 4 of 10 files at r1.
Review status: 4 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[ui/ts/models/helpus.ts, line 49 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDgGjeFgC2lxB4yDIHF:-KDgGjeFgC2lxB4yDIHG:1367823219) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/ui/ts/models/helpus.ts#L49)):*
I do not understand the motivation for this change.  Now it's ugly code here instead of on the server, and that's better?  Why is it necessary for this "optin" attribute to be stored separately?  I simply don't understand the motivation. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-:-KDgGOGfBVf_gpIIU91v:609236392)*

**Comment by mrtracy** [comment]
Review status: 4 of 10 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/updates.go, line 206 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDgI9hU7m5WrphtegEm:-KDgI9hVHbrhu1zrVmCN:1014541984) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/server/updates.go#L206)):*
(sorry for the disjointed commentary, reviewable was hiding files from me)

It appears to me that this was the only change necessary here.  I don't understand why this method can't just query the previously existing "helpus" key, and read the opt-in value from it.

---

*[ui/ts/models/helpus.ts, line 49 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDgGjeFgC2lxB4yDIHF:-KDgHch0G9rJ34Y3tDBs:917576433) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/ui/ts/models/helpus.ts#L49)):*
Alright, so the key here is that there may be multiple admin ui users that

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564)*

**Comment by maxlang** [comment]
Review status: 4 of 10 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[ui/ts/models/api.ts, line 97 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDhBmFZ6yIfTyNOiS5z:-KDhBmF_EvzZCUN_O2F7:1695221196) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/ui/ts/models/api.ts#L97)):*
I'd add a comment with an example URL.

---

*[ui/ts/models/api.ts, line 100 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDh8WZ_5LbjRLJUpBCh:-KDh8WZ_5LbjRLJUpBCi:217477707) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/ui/ts/models/api.ts#L100)):*
We weren't doing this before, but now that this is getting more general we should probably use ```encodeURIComponent(key)``` so that we support keys with special characters.

---

*[ui/ts/models/api.ts, line 102 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDhA1_edO2eMH-whXXy:-KDhA1_edO2eMH-whXXz:753974167) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/ui/ts/models/api.ts#L102)):*
You can just use double-quotes if you aren't using any of the features the template literal syntax.

---

*[ui/ts/models/helpus.ts, line 49 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDhF9hwFvclzNohYqVR:-KDhCDympGL5csqJx_kJ:-1545039133) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/ui/ts/models/helpus.ts#L49)):*
As mentioned below, if you just store off optin as a convenience for the backend, but keep the "helpus" data intact, you could leave this code untouched.

---

*[ui/ts/models/helpus.ts, line 64 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDhD8KVl7WfsXhNT1j4:-KDhD8KVl7WfsXhNT1j5:-13580069) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/ui/ts/models/helpus.ts#L64)):*
Why bother omitting? What if we always read from the "helpus" key and just stored the extra optin value when saving as a convenience?

---

*[ui/ts/models/helpus.ts, line 67 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDhE2EuZ6TzJ3Qchwbv:-KDhE2EvqpjE51nu1MyN:-1919860211) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/ui/ts/models/helpus.ts#L67)):*
This can be simplified with newer syntax which allows you to use special characters/variables/etc as keys:

```javascript
let keyValues: {[key: string]: string} = {
  [KEY_HELPUS]: btoa(JSON.stringify(helpus)),
  [KEY_OPTIN]: btoa(JSON.stringify(optin)),
}
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564)*

**Comment by tamird** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[server/admin.proto, line 293 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDhSopxcGRbz-iIOP9J:-KDhSopywTiGeUqa58Wr:1795344796) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/server/admin.proto#L293)):*
it does? seems like the proto field is called "keys" too.

---

*[server/admin_test.go, line 526 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDhT0j9jz3-vfbfIR8x:-KDhT0j9jz3-vfbfIR8y:-394567523) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/server/admin_test.go#L526)):*
well it's more because we don't have expected timestamps, right?

---

*[server/updates.go, line 206 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDgI9hU7m5WrphtegEm:-KDhTNkWpTNwC0AYOW0x:-1282445100) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/server/updates.go#L206)):*
Yeah, this is the only required change, but beta's coming up and having these RPCs handle multiple keys is an obvious improvement.

---

*[server/updates.go, line 220 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDhTXR_w7Kim5nzkDNj:-KDhTXR_w7Kim5nzkDNk:-360229587) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/server/updates.go#L220)):*
needs to be Warningf, but also you should log the error

---

*[ui/ts/models/helpus.ts, line 49 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDhF9hwFvclzNohYqVR:-KDhTxGwIWFdY1appweW:151115499) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/ui/ts/models/helpus.ts#L49)):*
New code seems strictly better than the old, though.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564)*

**Comment by cuongdo** [comment]
Review status: 4 of 10 files reviewed at latest revision, 11 unresolved discussions.

---

*[server/admin.proto, line 293 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDhSopxcGRbz-iIOP9J:-KDi9GpBLL8nvO0KcidV:210430542) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/server/admin.proto#L293)):*
Yes, but from an API point of view, if you're retrieving a single key, the URL looks like this:

`/_admin/v1/uidata?keys=MYKEY`

A little awkward to me.

---

*[server/admin_test.go, line 526 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDhT0j9jz3-vfbfIR8x:-KDi9lLtgf7XPk7xYko8:-439823591) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/server/admin_test.go#L526)):*
Yeah, clarified the comment.

---

*[server/updates.go, line 206 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDgI9hU7m5WrphtegEm:-KDi9rRLk5wLE9XWWs-I:480671405) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/server/updates.go#L206)):*
JSON has a tendency of growing in weird, unexpected ways. Having a separate key that the server can trivially parse is better. Also, if the UI somehow puts corrupt JSON into `uidata`, that shouldn't stop us from reading `optin`. It might seem like a remote possibility, but this paranoia has been bred from bad experiences dealing with server-side JSON.

---

*[server/updates.go, line 220 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDhTXR_w7Kim5nzkDNj:-KDiAmIuWYhr8x04MsVI:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/server/updates.go#L220)):*
Done.

---

*[ui/ts/models/api.ts, line 97 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDhBmFZ6yIfTyNOiS5z:-KDiBC8Wn8sek3r3MEXX:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/ui/ts/models/api.ts#L97)):*
Done.

---

*[ui/ts/models/api.ts, line 100 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDh8WZ_5LbjRLJUpBCh:-KDiBLxwMzSJ3SJlZ_pa:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/ui/ts/models/api.ts#L100)):*
Done.

---

*[ui/ts/models/api.ts, line 102 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDhA1_edO2eMH-whXXy:-KDiBRbGPpNhygr9UHc6:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/ui/ts/models/api.ts#L102)):*
Done.

---

*[ui/ts/models/helpus.ts, line 49 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDgGjeFgC2lxB4yDIHF:-KDiBihhzmZj6DczGKGt:-2058015502) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/ui/ts/models/helpus.ts#L49)):*
Following @maxlang's suggestion, I'm cloning the `optin` attribute to reduce the complexity of this code.

---

*[ui/ts/models/helpus.ts, line 49 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDhF9hwFvclzNohYqVR:-KDiDLia6Vq02Hd6P9us:-2013756444) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/ui/ts/models/helpus.ts#L49)):*
@maxlang: I've followed your suggestion, but I still strongly prefer to extract the `optin` and `helpus` strings.

---

*[ui/ts/models/helpus.ts, line 64 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDhD8KVl7WfsXhNT1j4:-KDiBxEca54jvm3fMGcL:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/ui/ts/models/helpus.ts#L64)):*
Done.

---

*[ui/ts/models/helpus.ts, line 67 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDhE2EuZ6TzJ3Qchwbv:-KDiDILCbZ7Q2WxlTaCK:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/ui/ts/models/helpus.ts#L67)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564)*

**Comment by tamird** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[server/admin.proto, line 293 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDhSopxcGRbz-iIOP9J:-KDiMBAfe16cjjHWpO5D:-1287659254) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/server/admin.proto#L293)):*
Sure, fine. What I meant was that

> That has to do with the automatic way that query parameters are mapped to protobuf fields.

is not accurate.

---

*[server/updates.go, line 220 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDhTXR_w7Kim5nzkDNj:-KDiKJypjKRATNeR6fcV:-975589764) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/server/updates.go#L220)):*
I think %v for val.Value will log it as `[1 2 3 4]` - you want `%q` I think.

---

*[ui/ts/models/helpus.ts, line 64 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDhD8KVl7WfsXhNT1j4:-KDiLCgcJHlBCaJC3War:1348170601) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/ui/ts/models/helpus.ts#L64)):*
I must be missing something - why can't `keyValues` be `attrs` exactly? in other words, why do we still have JSON (right?) in KEY_HELPUS?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564)*

**Comment by cuongdo** [comment]
Review status: 7 of 10 files reviewed at latest revision, 10 unresolved discussions.

---

*[server/admin.proto, line 293 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDhSopxcGRbz-iIOP9J:-KDiNl8Z-LF_-zctUu7G:-888365374) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/server/admin.proto#L293)):*
Clarified.

---

*[server/updates.go, line 220 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDhTXR_w7Kim5nzkDNj:-KDiO2TxlOLNyfsySQL0:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/server/updates.go#L220)):*
Done.

---

*[ui/ts/models/helpus.ts, line 64 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDhD8KVl7WfsXhNT1j4:-KDiOCVCfZlWkEExne6M:-187106804) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/ui/ts/models/helpus.ts#L64)):*
`keyValues` contains both the `optin` key and the `helpus` key, so that requires having a `keyValues`that's distinct from `attrs`. `attrs` can't simply be the value of `KEY_HELPUS`, because the JSON->gRPC mapping requires that `bytes` fields (which `uidata` values are) be base64-encoded. To base64-encode (`btoa`)`attrs`, we must first convert to a JSON string.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[ui/ts/models/helpus.ts, line 64 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDhD8KVl7WfsXhNT1j4:-KDiTdZuxko8YqfAbH8o:-1355379400) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/ui/ts/models/helpus.ts#L64)):*
> `keyValues` contains both the `optin` key and the `helpus` key

Right, I understand - that's the part I'm suggesting we change.

> `attrs` can't simply be the value of `KEY_HELPUS`, 

To clarify, I wasn't suggesting that `attrs` be the value of `KEY_HELPUS` - I was suggesting that `attrs` be `keyValues` itself.

> because the JSON->gRPC mapping requires that `bytes` fields (which `uidata` values are) be base64-encoded. To base64-encode `(btoa)` `attrs`, we must first convert to a JSON string.

Can't you construct a new object then, with each value in `attrs` having been `btoa`'d, and use that as `keyValues`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564)*

**Comment by cuongdo** [comment]
Review status: 8 of 10 files reviewed at latest revision, 8 unresolved discussions.

---

*[ui/ts/models/helpus.ts, line 64 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-KDhD8KVl7WfsXhNT1j4:-KDj0ahpBNASI9DCh7ZA:-1081459950) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a35570e6f5e2dc1a4759e9ccadb8a1a0ffab42/ui/ts/models/helpus.ts#L64)):*
I've pushed a new commit that does this. Feedback from @mrtracy or @maxlang?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564)*

**Comment by mrtracy** [comment]
:lgtm: - it appears that all of the individual "help us" attributes are being stored in individual keys, which seems much better than the earlier situation (where only "optin" was treated specially in the front end code).

---

Review status: 8 of 10 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-:-KDj2voW2PGI1VM7jEm5:-1434391754)*

**Comment by cuongdo** [comment]
There have been several useful but diverging opinions of how to handle these two requirements:

1. Sharing cluster reporting opt-in status, saved in the admin UI, with the server cluster reporting reporting code.
2. The original intent to have `SetUIData` and `GetUIData` be an opaque cookie jar for the admin UI.

I've kept the `optin` info separate but have renamed it to `server.optin-reporting` to make its sharing and meaning more apparent. We've had sufficient debate on how to structure `UIData` keys, and barring any functional issues here, I'd like to merge this PR.

**Comment by mrtracy** [comment]
I will just say that I really liked the previous solution better (where all attributes were separate), but the only thing I really do _not_ like here is the duplication of the opt in field. If it needs to be separate, fine, but I don't see why it should also be present in the helpus structure.

---

Review status: 2 of 10 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-:-KDjOpmfilV4EjN-X9dT:-1701021374)*

**Comment by mrtracy** [comment]
If you just want to merge this to get the multiple-key functionality in, that's fine; we can argue about what keys need to be stored later.

---

Review status: 2 of 10 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-:-KDjQSA93-t70iLMI0Mq:1563813134)*

**Comment by cuongdo** [comment]
There was no duplication in an earlier revision, but there was disagreement with that as well. The solution space that makes everyone happy here contains exactly 0 elements.

---

Review status: 2 of 10 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-:-KDjRTLNDowENZ6ZrqIa:-1549723508)*

**Comment by maxlang** [comment]
:lgtm:

I agree with Matt that the core functionality here is solid and we can always fiddle with what we're storing later.

---

Review status: 2 of 10 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5564#-:-KDjXKKEKpHOSZi_uc53:-308865681)*

**Pull request merged**
