### PR TITLE
sql,jobs: implement a type schema changer and `RENAME TYPE`

### LINKED ISSUE #48672: sql: support the ALTER TYPE RENAME TO command
See https://www.postgresql.org/docs/9.1/sql-altertype.html.

### PR DESCRIPTION
**Pull request by rohany**
Fixes #48672.

This PR adds a "type schema changer" that has similar logic to the table
schema changer, but is much simpler. It mostly will just drain names and
wait for leases, but will have important work to do in the `ALTER TYPE
ADD VALUE` case. Using this type schema changer, we implement the
`RENAME TYPE` command.

Release note: None

### CODE REVIEW

**Comment by rohany** [comment]
There are still a couple TODO's in here that need resolving, but I'd like to get a look now, since the type schema changer is mostly stood up here. I'm interested in feedback on
* testing: what are interesting things to test for this? Is there testing that we can do without implementing more type change commands?
* on failure: I don't think anything needs to be done right now on type change job failure -- is that wrong?
* job mutex: how do we ensure that multiple type change jobs don't conflict with each other? Or is that even a problem?

**Review by ajwerner — CHANGES_REQUESTED** [review]
> Reviewed 10 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50936)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, and @rohany)

___
*[pkg/sql/alter_type.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MBZq1NA6G2CrEZ4DBqE:-MBZq1NB8vCDM1BV5o2s:b-f78bxk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c8e10c73592b6f243a6e965bd002853d933c9b6/pkg/sql/alter_type.go#L83)):*
> ```Go
> 		desc, err := catalogkv.GetDescriptorByID(params.ctx, p.txn, p.ExecCfg().Codec, id)
> 		if err != nil {
> 			return err
> ```

I suspect this is a case where we want to return an `ObjectAlreadyExistsError` but we want to provide information that we failed to look up what the object was rather than returning this error directly. 
___
*[pkg/sql/type_change.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MBZqg0w1pxdp8Fsv67V:-MBZqg0w1pxdp8Fsv67W:bhlkkdp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c8e10c73592b6f243a6e965bd002853d933c9b6/pkg/sql/type_change.go#L39)):*
> ```Go
> 	var job *jobs.Job
> 	if cachedJob, ok := p.extendedEvalCtx.SchemaChangeJobCache[typeDesc.ID]; ok {
> 		job = cachedJob
> ```

Why not just:

```
job, jobExists := p.extendedEvalCtx.SchemaChangeJobCache[typeDesc.ID]
```
___
*[pkg/sql/type_change.go, line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MBZqoKR2YbE8Wzrdm1x:-MBZqoKSBi6aWIPza1J6:br19hw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c8e10c73592b6f243a6e965bd002853d933c9b6/pkg/sql/type_change.go#L43)):*
> ```
> 		// Update it.
> 		if jobDesc != "" {
> ```
When does this happen?
___
*[pkg/sql/type_change.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MBZqyMJC0zvwiLfxJnL:-MBZqyMJC0zvwiLfxJnM:b1yf5fe) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c8e10c73592b6f243a6e965bd002853d933c9b6/pkg/sql/type_change.go#L76)):*
> ```
> 	// Maybe increment the type's version.
> 	typeDesc.MaybeIncrementVersion()
> ```
It sort of surprises me that we do this here but alas.
___
*[pkg/sql/type_change.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MBZrKOfAvUq6XkQrq4H:-MBZrKOfAvUq6XkQrq4I:blqlrd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c8e10c73592b6f243a6e965bd002853d933c9b6/pkg/sql/type_change.go#L171)):*
> ```
> 	// TODO (rohany): I don't think that there is any thing that needs to be
> 	//  done if a type job fails.
> ```
What about dealing with draining names? Do we want to clean them up?

It's not clear what this would happen other than a user explicitly performing cancelation. Perhaps there are other errors we'll erroneously not classify as retriable. 

Orthogonally, should we disallow cancellation?
___
*[pkg/sql/sqlbase/descriptor.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MBZrjI84395YmHr9N9a:-MBZrjI84395YmHr9N9b:b-gte8wl) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c8e10c73592b6f243a6e965bd002853d933c9b6/pkg/sql/sqlbase/descriptor.go#L59)):*
> ```Go
> 	GetModificationTime() hlc.Timestamp
> 	GetDrainingNames() []NameInfo
> 	SetDrainingNames([]NameInfo)
> ```

I was really hoping to keep this as a read-only interface. I'm pretty :thumbsdown: on adding this method here.

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50936)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @lucy-zhang)

___
*[pkg/sql/alter_type.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MBZq1NA6G2CrEZ4DBqE:-MBZt6kI53pYGupyeuJh:bkv9m53) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c8e10c73592b6f243a6e965bd002853d933c9b6/pkg/sql/alter_type.go#L83)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I suspect this is a case where we want to return an `ObjectAlreadyExistsError` but we want to provide information that we failed to look up what the object was rather than returning this error directly. 
</blockquote></details>

I can look into that as a separate issue -- we do this in a few places already so it would be good to tackle them at once (created #51010).
___
*[pkg/sql/type_change.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MBZqg0w1pxdp8Fsv67V:-MBZtPf05eN_rkJAdCh2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c8e10c73592b6f243a6e965bd002853d933c9b6/pkg/sql/type_change.go#L39)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Why not just:

```
job, jobExists := p.extendedEvalCtx.SchemaChangeJobCache[typeDesc.ID]
```
</blockquote></details>

Done.
___
*[pkg/sql/type_change.go, line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MBZqoKR2YbE8Wzrdm1x:-MBZtSAf15aCpagjrmdr:bi88i1y) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c8e10c73592b6f243a6e965bd002853d933c9b6/pkg/sql/type_change.go#L43)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 		// Update it.
> 		if jobDesc != "" {
> ```
When does this happen?
</blockquote></details>

I can see it being useful in places where we update backreferences, or just want to bump a version on a type without updating the job description. A bunch of this code is adapted from the similar flow for table changes, so I've kept some of the choices made there.
___
*[pkg/sql/type_change.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MBZqyMJC0zvwiLfxJnL:-MBZtiisAWpbIe2M-t3W:b54cr8r) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c8e10c73592b6f243a6e965bd002853d933c9b6/pkg/sql/type_change.go#L76)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	// Maybe increment the type's version.
> 	typeDesc.MaybeIncrementVersion()
> ```
It sort of surprises me that we do this here but alas.
</blockquote></details>

Where would you rather see it? I don't want standard users of the type to have to do it every time they modify one in an alter type node.
___
*[pkg/sql/type_change.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MBZrKOfAvUq6XkQrq4H:-MBZvHAN0DqF0AOnJVnS:b-1shezt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c8e10c73592b6f243a6e965bd002853d933c9b6/pkg/sql/type_change.go#L171)):*
I'm on board with disallowing cancellation of these jobs.

> What about dealing with draining names? Do we want to clean them up?

I would think so, but it doesn't look like the table schema changer does this. Maybe @lucy-zhang knows.
___
*[pkg/sql/sqlbase/descriptor.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MBZrjI84395YmHr9N9a:-MBZudH59PYaL0pEidvD:bkrcra5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c8e10c73592b6f243a6e965bd002853d933c9b6/pkg/sql/sqlbase/descriptor.go#L59)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I was really hoping to keep this as a read-only interface. I'm pretty :thumbsdown: on adding this method here. 
</blockquote></details>

Woops, I meant to put this on the `MutableDescriptor` interface.

**Review by thoszhang — COMMENTED** [review]
> Reviewed 10 of 20 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50936)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @rohany)

___
*[pkg/sql/type_change.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MBZqyMJC0zvwiLfxJnL:-MBdewdr-Lt4DTeiPDT3:by6v8rv) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c8e10c73592b6f243a6e965bd002853d933c9b6/pkg/sql/type_change.go#L76)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Where would you rather see it? I don't want standard users of the type to have to do it every time they modify one in an alter type node.
</blockquote></details>

I'm with Andrew (I think) in that having any schema change call `MaybeIncrementVersion()` manually makes for a bad interface, but I think this is as good of a place as any other.
___
*[pkg/sql/type_change.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MBZrKOfAvUq6XkQrq4H:-MBdfcju1KmW6T3frw0z:bhdaua6) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c8e10c73592b6f243a6e965bd002853d933c9b6/pkg/sql/type_change.go#L171)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

I'm on board with disallowing cancellation of these jobs.

> What about dealing with draining names? Do we want to clean them up?

I would think so, but it doesn't look like the table schema changer does this. Maybe @lucy-zhang knows.
</blockquote></details>

Yeah, we don't clean up draining names in the table schema changer, but maybe we should start doing that here. Though what would it mean to clean them up besides just doing what `Resume()` is already doing?
___
*[pkg/sql/logictest/testdata/logic_test/type_change, line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MBdgzMN3SGn-pV4H4en:-MBdgzMN3SGn-pV4H4eo:br92p4r) ([raw file](https://github.com/cockroachdb/cockroach/blob/57dbcfffad1507d8f29a2252bf2279363b7c2614/pkg/sql/logictest/testdata/logic_test/type_change#L21)):*
> ```
> {hi}
> 
> # Test that we can use the new name within a transaction.
> ```

Can we also have a test for renaming a table twice within the same transaction?

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50936)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @lucy-zhang)

___
*[pkg/sql/type_change.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MBZqyMJC0zvwiLfxJnL:-MBdiLAB6HpG_c835EP4:b5ldtgd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c8e10c73592b6f243a6e965bd002853d933c9b6/pkg/sql/type_change.go#L76)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

I'm with Andrew (I think) in that having any schema change call `MaybeIncrementVersion()` manually makes for a bad interface, but I think this is as good of a place as any other.
</blockquote></details>

We do the same thing in the table schema change path -- another reason to maybe do this on mutable descriptor creation
___
*[pkg/sql/type_change.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MBZrKOfAvUq6XkQrq4H:-MBdiUNB-GHRkqPnqf_a:bs46grg) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c8e10c73592b6f243a6e965bd002853d933c9b6/pkg/sql/type_change.go#L171)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Yeah, we don't clean up draining names in the table schema changer, but maybe we should start doing that here. Though what would it mean to clean them up besides just doing what `Resume()` is already doing?
</blockquote></details>

Yeah, I'm not sure what it would mean. It seems like the draining in the table schema changer occurs "before the job can fail", so I could see the rationale in not doing it. AFAICT, the `OnFailOrCancel` hook would look exactly like the `Resume` hook.
___
*[pkg/sql/logictest/testdata/logic_test/type_change, line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MBdgzMN3SGn-pV4H4en:-MBdioIC6Mi5bbaNLdQZ:b-k3nmtt) ([raw file](https://github.com/cockroachdb/cockroach/blob/57dbcfffad1507d8f29a2252bf2279363b7c2614/pkg/sql/logictest/testdata/logic_test/type_change#L21)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Can we also have a test for renaming a table twice within the same transaction?
</blockquote></details>

Those already exist in `rename_test.go`

**Review by thoszhang — COMMENTED** [review]
Very minor bikeshedding: the name `TypeChange` seems to imply that the `SchemaChange` job is for schemas (also, what are we going to name the actual job for schemas?). Is it even possible to rename `SchemaChange` to `TableChange` or something?

`SchemaChange` (the original) / `TableSchemaChange`, `TypeSchemaChange`, and `SchemaSchemaChange` would also be sort of fine with me.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-:-MBdkcFN-SfpL6QkpnON:b-a8iui4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @rohany)

___
*[pkg/sql/type_change.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MBZqyMJC0zvwiLfxJnL:-MBdjMIqDT3fZ2-erIsZ:bvgeomi) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c8e10c73592b6f243a6e965bd002853d933c9b6/pkg/sql/type_change.go#L76)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

We do the same thing in the table schema change path -- another reason to maybe do this on mutable descriptor creation
</blockquote></details>

Yeah, agreed.
___
*[pkg/sql/type_change.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MBZrKOfAvUq6XkQrq4H:-MBdjP5b5ia6HJ5xdl1k:bedz3b4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c8e10c73592b6f243a6e965bd002853d933c9b6/pkg/sql/type_change.go#L171)):*
> AFAICT, the OnFailOrCancel hook would look exactly like the Resume hook.

Yeah, I'm not sure there's really a point if the hooks are just identical. I guess misclassified errors that are actually retriable are where we'd care about this, like Andrew said, but even then we wouldn't guarantee success if we get the error again. I think we should just leave it. Maybe this will change for some reason once more schema changes are implemented.
___
*[pkg/sql/logictest/testdata/logic_test/type_change, line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MBdgzMN3SGn-pV4H4en:-MBdjZU0DUJ9JE2szv43:b4700l6) ([raw file](https://github.com/cockroachdb/cockroach/blob/57dbcfffad1507d8f29a2252bf2279363b7c2614/pkg/sql/logictest/testdata/logic_test/type_change#L21)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Those already exist in `rename_test.go`
</blockquote></details>

Sorry, I meant "type" and not "table"

**Review by ajwerner — COMMENTED** [review]
> Is it even possible to rename SchemaChange to TableChange or something?

It should be. Protobuf message names aren't really used as strings IIUC. Should it be `TableOrDatabaseChange`?

> Reviewed 1 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-:-MBe0CGa2ytkzLnazJR9:b-oxy1ps)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, and @rohany)

___
*[pkg/sql/type_change.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MBZrKOfAvUq6XkQrq4H:-MBZx09SDeyM_YnYf2B4:bjvj5j3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c8e10c73592b6f243a6e965bd002853d933c9b6/pkg/sql/type_change.go#L171)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

I'm on board with disallowing cancellation of these jobs.

> What about dealing with draining names? Do we want to clean them up?

I would think so, but it doesn't look like the table schema changer does this. Maybe @lucy-zhang knows.
</blockquote></details>

I don't think that means that the table schema changer's behavior is good.

**Review by rohany — COMMENTED** [review]
Its unfortunate that `Schema` is overloaded for table schemas and namespace schemas. I wouldn't mind `{DescriptorType}SchemaChanger`. I can rename this to `TypeSchemaChange` here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-:-MBdxPXG5LqDwVXz1tKB:b36zzps)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @lucy-zhang)

___
*[pkg/sql/type_change.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MBZrKOfAvUq6XkQrq4H:-MBdxAbg-dD0Im0OLXgl:bynh0lo) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c8e10c73592b6f243a6e965bd002853d933c9b6/pkg/sql/type_change.go#L171)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

> AFAICT, the OnFailOrCancel hook would look exactly like the Resume hook.

Yeah, I'm not sure there's really a point if the hooks are just identical. I guess misclassified errors that are actually retriable are where we'd care about this, like Andrew said, but even then we wouldn't guarantee success if we get the error again. I think we should just leave it. Maybe this will change for some reason once more schema changes are implemented.
</blockquote></details>

Alright, I'll leave it empty for now.
___
*[pkg/sql/logictest/testdata/logic_test/type_change, line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MBdgzMN3SGn-pV4H4en:-MBdwZdIEqS02YTQAYV0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/57dbcfffad1507d8f29a2252bf2279363b7c2614/pkg/sql/logictest/testdata/logic_test/type_change#L21)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Sorry, I meant "type" and not "table"
</blockquote></details>

Done.

**Comment by rohany** [comment]
I think I'm fuzzy on the conclusion of whether to include the draining names in the failure job or not -- I think that it would be unnecessary, based on my understanding of the jobs framework

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50936)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @lucy-zhang)

___
*[pkg/sql/type_change.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MBZrKOfAvUq6XkQrq4H:-MBom7j-2-g4SkZaANWA:b4hylgi) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c8e10c73592b6f243a6e965bd002853d933c9b6/pkg/sql/type_change.go#L171)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Alright, I'll leave it empty for now.
</blockquote></details>

Oh, I see now that we're not actually trying to detect retriable errors. I'm not sure most of the allowed retriable errors in `isPermanentSchemaChangeError()` apply here, but should we just use that? (Separately, a lot of them aren't errors we even use anymore.)

That's sort of separate from the question of whether we should try again to clean up the draining names. I've come around to thinking we should do it (minus the final waiting for leases at the end), since the extra retry couldn't hurt.

**Comment by rohany** [comment]
> Oh, I see now that we're not actually trying to detect retriable errors. I'm not sure most of the allowed retriable errors in isPermanentSchemaChangeError() apply here, but should we just use that? (Separately, a lot of them aren't errors we even use anymore.)

Done, updated to add a retry loop like the schema changer. I took a quick look and some at least are applicable. It makes sense to keep a set of schema changer errors in the same place.

> That's sort of separate from the question of whether we should try again to clean up the draining names. I've come around to thinking we should do it (minus the final waiting for leases at the end), since the extra retry couldn't hurt.

Done

**Review by ajwerner — CHANGES_REQUESTED** [review]
I'd love to see more testing of the failure scenarios. 

> Reviewed 3 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-:-MC7aTwZ8zh7Ni6E4iVM:b-r9liu9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, and @rohany)

___
*[pkg/sql/alter_type.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MBZq1NA6G2CrEZ4DBqE:-MC7ZnXX3dMF25Sp2h5A:b8j9ipu) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c8e10c73592b6f243a6e965bd002853d933c9b6/pkg/sql/alter_type.go#L83)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

I can look into that as a separate issue -- we do this in a few places already so it would be good to tackle them at once.
</blockquote></details>

nit: TODO then?
___
*[pkg/sql/type_change.go, line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MBZqoKR2YbE8Wzrdm1x:-MC7_JW_Dy80u27UYmnx:b-ir0jnv) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c8e10c73592b6f243a6e965bd002853d933c9b6/pkg/sql/type_change.go#L43)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

I can see it being useful in places where we update backreferences, or just want to bump a version on a type without updating the job description. A bunch of this code is adapted from the similar flow for table changes, so I've kept some of the choices made there.
</blockquote></details>

It smells. I think we need commentary here about why we'd have the job existing but with no description and some reasoning for why we want to keep it with no description. I thought that we recently went through and got rid of the no description cases. 
___
*[pkg/sql/type_change.go, line 200 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MC7_jfJ6fH6CJ3b_CKT:-MC7_jfJ6fH6CJ3b_CKU:bboy3l1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccaba10bc06b516942c6d7f00d2a8471517f5cd5/pkg/sql/type_change.go#L200)):*
> ```Go
> 		}
> 	}
> 	return nil
> ```

You're not guaranteed to run at least once unfortunately. I think this should return `ctx.Err()`

Furthermore, I don't get why you're defining `tcErr` above the loop if you're not using it outside of the loop.

**Review by rohany — COMMENTED** [review]
Added some tests with deleted descriptors and errors injected into the job

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-:-MC83rtdDP3eGXIw6iVh:b-yyqeyf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @lucy-zhang)

___
*[pkg/sql/alter_type.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MBZq1NA6G2CrEZ4DBqE:-MC7h7CDEBPHOMQC2enV:bt8kxr3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c8e10c73592b6f243a6e965bd002853d933c9b6/pkg/sql/alter_type.go#L83)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: TODO then?
</blockquote></details>

I landed the change in the meantime. Rebased to include it here.
___
*[pkg/sql/type_change.go, line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MBZqoKR2YbE8Wzrdm1x:-MC7hRNiD20iolP_Hnga:b-9xbgas) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c8e10c73592b6f243a6e965bd002853d933c9b6/pkg/sql/type_change.go#L43)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

It smells. I think we need commentary here about why we'd have the job existing but with no description and some reasoning for why we want to keep it with no description. I thought that we recently went through and got rid of the no description cases. 
</blockquote></details>

I agree -- this isn't a hill I'm going to die on. Updated so that all callers should provide descriptions.
___
*[pkg/sql/type_change.go, line 200 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MC7_jfJ6fH6CJ3b_CKT:-MC7hepgAMeJDT2z4Wo2:bjl9wcj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccaba10bc06b516942c6d7f00d2a8471517f5cd5/pkg/sql/type_change.go#L200)):*
> You're not guaranteed to run at least once unfortunately. I think this should return ctx.Err()

we are now :)

> Furthermore, I don't get why you're defining tcErr above the loop if you're not using it outside of the loop.

too much cargo culting :(

**Review by ajwerner — COMMENTED** [review]
Just the lingering nits from me

> Reviewed 6 of 12 files at r3, 13 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-:-MCHqkcg-hy3WHhaF7ay:b46l5c7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, and @rohany)

___
*[pkg/sql/type_change.go, line 43 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MCHq0PTAegPg3xgxrE2:-MCHq0PUDEP0rDLct-00:b-4yyugn) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3484e3ed838326ea8c377f32bcb3303fa3b3a28/pkg/sql/type_change.go#L43)):*
> ```Go
> 		if err := job.WithTxn(p.txn).SetDescription(ctx,
> 			func(ctx context.Context, description string) (string, error) {
> 				return strings.Join([]string{description, jobDesc}, ";" /* sep */), nil
> ```

nit: probably you want a space between them. Also could just be `description + "; " + jobDesc`
___
*[pkg/sql/type_change.go, line 205 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-MCHqNZM9xq0S_5mOuD8:-MCHqNZM9xq0S_5mOuD9:bv8d9fm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3484e3ed838326ea8c377f32bcb3303fa3b3a28/pkg/sql/type_change.go#L205)):*
> ```Go
> 			)
> 			return nil
> 		case !isPermanentSchemaChangeError(tcErr):
> ```

Don't we want some visibility into this? Logging at the very least. I thought dt added something to report running status.

**Comment by rohany** [comment]
Updated with nit fixes.

> Don't we want some visibility into this? Logging at the very least. I thought dt added something to report running status.

I used a log. Note sure if a transient retry here warrants a running status change.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50936#-:-MCI3SkN3hlNmZ57I7zC:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, and @rohany)

**Comment by rohany** [comment]
I'll wait for @lucy-zhang to look as well.

**Review by thoszhang — APPROVED** [review]
> Reviewed 3 of 20 files at r1, 9 of 12 files at r3, 9 of 13 files at r4, 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50936)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, and @rohany)

**Pull request merged**
