### PR TITLE
docs: Clean up the RFCs directory

### PR DESCRIPTION
**Pull request by a-robinson**
Update the `Status` and `RFC PR` fields of a bunch of the RFCs to try to more accurately reflect reality. Also move images into the images directory while I'm here.

@petermattis sorry to throw a PR at you that isn't related to stability, but I assume you have the best idea of whether my status updates are correct. There's certainly no rush to get this in.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9004)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm: Thanks for doing this.

---

Reviewed 21 of 21 files at r1.
Review status: 10 of 25 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/sql_interleaved_tables.md, line 2 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9004#-KQYEt7zWxVCzzbQMF-V:-KQYEt7zWxVCzzbQMF-W:bu4i0am) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2e3e570e878b7bc345ed8b14911886f2c54648c/docs/RFCS/sql_interleaved_tables.md#L2)):*
> ```Markdown
> - Feature Name: sql_interleaved_tables
> - Status: in-progress
> ```

I think this is done. @paperstreet?

---

*[docs/RFCS/stateless_replica_relocation.md, line 2 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9004#-KQYF2q8f73GNdRt5zOx:-KQYF2q8f73GNdRt5zOy:bz023b0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2e3e570e878b7bc345ed8b14911886f2c54648c/docs/RFCS/stateless_replica_relocation.md#L2)):*
> ```Markdown
> - Feature Name: Stateless Replica Relocation
> - Status: complete
> ```

`s/complete/completed/g`

---

*[docs/RFCS/store_pool.md, line 2 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9004#-KQYExSyWIiM7cXuuzoP:-KQYExSyWIiM7cXuuzoQ:bodhprc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2e3e570e878b7bc345ed8b14911886f2c54648c/docs/RFCS/store_pool.md#L2)):*
> ```Markdown
> - Feature Name: Store Pool
> - Status: Completed
> ```

`s/Completed/completed/g` (for consistency)

---

*[docs/RFCS/store_pool.md, line 4 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9004#-KQYF9TyNKKPTmri9aOE:-KQYF9TzBocAKFy4HXmy:b9dp5yj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2e3e570e878b7bc345ed8b14911886f2c54648c/docs/RFCS/store_pool.md#L4)):*
> ```Markdown
> - Status: Completed
> - Start Date: 2015-08-20
> - RFC PR: #2286, #2336
> ```

Should all of these PR references be links like you do for `time_travel.md`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9004#-:-KQYFFXGjvmpWfKkyc_j:b-pt8m0o)*

**Comment by bdarnell** [comment]
Review status: 10 of 25 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/store_pool.md, line 4 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9004#-KQYF9TyNKKPTmri9aOE:-KQZoOetn332x42GWwCM:b-zfzbil) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2e3e570e878b7bc345ed8b14911886f2c54648c/docs/RFCS/store_pool.md#L4)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Should all of these PR references be links like you do for `time_travel.md`?
</details>
Github linkifies these automatically when it renders the file; no need to manually link. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9004)*

**Comment by a-robinson** [comment]
Review status: 10 of 45 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[docs/RFCS/sql_interleaved_tables.md, line 2 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9004#-KQYEt7zWxVCzzbQMF-V:-KQa0GAxrjUSc4J7DBEt:brwnt72) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2e3e570e878b7bc345ed8b14911886f2c54648c/docs/RFCS/sql_interleaved_tables.md#L2)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I think this is done. @paperstreet?
</details>
I was going based on the fact that https://github.com/cockroachdb/cockroach/issues/2972 is still open, presumably because https://github.com/cockroachdb/cockroach/pull/7985 hasn't merged yet

---

*[docs/RFCS/stateless_replica_relocation.md, line 2 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9004#-KQYF2q8f73GNdRt5zOx:-KQa0QsXVBWQe0iHlpav:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2e3e570e878b7bc345ed8b14911886f2c54648c/docs/RFCS/stateless_replica_relocation.md#L2)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `s/complete/completed/g`
</details>
Done.

---

*[docs/RFCS/store_pool.md, line 2 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9004#-KQYExSyWIiM7cXuuzoP:-KQa0TMZWiqOltKqgmA7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2e3e570e878b7bc345ed8b14911886f2c54648c/docs/RFCS/store_pool.md#L2)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `s/Completed/completed/g` (for consistency)
</details>
Done.

---

*[docs/RFCS/store_pool.md, line 4 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9004#-KQYF9TyNKKPTmri9aOE:-KQa0UK80eBiBjZgUoD2:b-983ktl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2e3e570e878b7bc345ed8b14911886f2c54648c/docs/RFCS/store_pool.md#L4)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Github linkifies these automatically when it renders the file; no need to manually link. 
</details>
Github actually doesn't seem to linkify them, unfortunately. It's definitely more convenient for the reader if we manually linkify them, it's just less likely that such a pattern will actually be kept up over time due to the extra manual work involved. I've gone through and done it for all the existing files, though. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9004)*

**Comment by bdarnell** [comment]
Review status: 10 of 45 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[docs/RFCS/store_pool.md, line 4 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9004#-KQYF9TyNKKPTmri9aOE:-KQaDj_Daq9hm13TMC_V:bqkd8hj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2e3e570e878b7bc345ed8b14911886f2c54648c/docs/RFCS/store_pool.md#L4)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> Github actually doesn't seem to linkify them, unfortunately. It's definitely more convenient for the reader if we manually linkify them, it's just less likely that such a pattern will actually be kept up over time due to the extra manual work involved. I've gone through and done it for all the existing files, though. 
</details>
Hmm, I stand corrected. I thought it used to, though. I should make a place to publish this helper I use for the release notes:

```
(defun expand-pr-reference ()
  (interactive)
  (save-excursion
    (goto-char 0)
    (while (re-search-forward "\\([^\\[]\\)#\\([0-9]+\\)" nil t)
      (replace-match "\\1[#\\2](https://github.com/cockroachdb/cockroach/pull/\\2)" t nil))))
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9004)*

**Comment by paperstreet** [comment]
Review status: 10 of 45 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[docs/RFCS/sql_interleaved_tables.md, line 2 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9004#-KQYEt7zWxVCzzbQMF-V:-KQaUMVPR_-sPApJCqDu:bs1qpaw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2e3e570e878b7bc345ed8b14911886f2c54648c/docs/RFCS/sql_interleaved_tables.md#L2)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> I was going based on the fact that https://github.com/cockroachdb/cockroach/issues/2972 is still open, presumably because https://github.com/cockroachdb/cockroach/pull/7985 hasn't merged yet
</details>
in-progress is correct, unfortunately. I was blocked until this week on a getting a new beta so I could update the reference test. Should be done soon, I'll make sure to update this rfc when it is

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9004)*

**Pull request merged**
