### PR TITLE
sql,server: Add CANCEL SESSION statement

### PR DESCRIPTION
**Pull request by abhimadan**
See individual commits for details.

### CODE REVIEW

**Comment by abhimadan** [comment]
This currently has no tests.

**Comment by abhimadan** [comment]
The test doesn't seem to be flaky anymore.

**Comment by knz** [comment]
Are you ok waiting a few days for a review?

**Comment by jordanlewis** [comment]
@knz you should be on vacation! I'm going to review this, then I'd like you to take a look when you return. :)

**Comment by jordanlewis** [comment]
Nice!

I think there's a missing test for `SHOW CLUSTER SESSIONS` unless I just didn't see it for some reason.

---

Reviewed 10 of 10 files at r1, 13 of 13 files at r2, 10 of 10 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/server/status.go, line 1375 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23861#-L8XzCYTmABJMtEU5HWd:-L8XzCYTmABJMtEU5HWe:boaw6ne) ([raw file](https://github.com/cockroachdb/cockroach/blob/48941027aa1ab769d3183498ee9ff8a4801df7d9/pkg/server/status.go#L1375)):*
> ```Go
> }
> 
> func (s *statusServer) CancelSession(
> ```

This needs a docstring

---

*[pkg/server/serverpb/status.proto, line 400 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23861#-L8XxWT6Dk__wsd5zauy:-L8XxWT6Dk__wsd5zauz:bdt0nk6) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e09ad68375b7deacadfc723123f99b0da0fb89b/pkg/server/serverpb/status.proto#L400)):*
> ```protobuf
>   string last_active_query = 8;
>   // ID of the session (uint128 represented as a hexadecimal string).
>   string id = 9 [(gogoproto.customname) = "ID"];
> ```

Why don't we just use the UUID bytes here? I see that it was also done this way for query id... it's a bit unfortunate because this is 36 bytes instead of the 16 that it could be if it was sent over the wire as its raw bytes.

---

*[pkg/server/serverpb/status.proto, line 451 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23861#-L8XzGzsTY4XXVuqrgei:-L8XzGzsTY4XXVuqrgej:b-k5qb1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/48941027aa1ab769d3183498ee9ff8a4801df7d9/pkg/server/serverpb/status.proto#L451)):*
> ```protobuf
>   // forwarding is necessary.
>   string node_id = 1;
>   string session_id = 2 [(gogoproto.customname) = "SessionID"];
> ```

Again should this be `bytes` instead of a `string`? Unfortunate that it was already done this way for cancel query. I guess might as well go with what we have already.

---

*[pkg/sql/cancel_session.go, line 35 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23861#-L8XyskzqPHt3usluaxe:-L8XyskzqPHt3usluaxf:bu0vfux) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff687e1c4df6dfe1b38f12aa60df02271356a089/pkg/sql/cancel_session.go#L35)):*
> ```Go
> 		tree.IndexedVarHelper{},
> 		types.String,
> 		true, /* requireType */
> ```

Do you think we should change the output of `SHOW SESSIONS` and the input to this to actually be a UUID type (since we do support those) instead of a string?

---

*[pkg/sql/conn_executor.go, line 1741 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23861#-L8XzTbGPgey8yc0I_ve:-L8XzTbGPgey8yc0I_vf:b-ybkzit) ([raw file](https://github.com/cockroachdb/cockroach/blob/48941027aa1ab769d3183498ee9ff8a4801df7d9/pkg/sql/conn_executor.go#L1741)):*
> ```Go
> // cancelSession is part of the registrySession interface.
> func (ex *connExecutor) cancelSession() {
> 	// TODO: figure out how to send a nice error message to the client.
> ```

TODO(abhimadan)

---

*[pkg/sql/crdb_internal.go, line 758 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23861#-L8XxpTXXO-Tl8EeGdi6:-L8XxpTXXO-Tl8EeGdi7:bzcdxjg) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e09ad68375b7deacadfc723123f99b0da0fb89b/pkg/sql/crdb_internal.go#L758)):*
> ```Go
> CREATE TABLE crdb_internal.%s (
>   node_id            INT NOT NULL,   -- the node on which the query is running
> 	session_id         STRING,         -- the ID of the session
> ```

this indentation should match the other lines

---

*[pkg/sql/run_control_test.go, line 287 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23861#-L8XzYNUb-qeCqDOH54w:-L8XzYNUb-qeCqDOH54x:bdm1nv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/48941027aa1ab769d3183498ee9ff8a4801df7d9/pkg/sql/run_control_test.go#L287)):*
> ```Go
> 			ReplicationMode: base.ReplicationManual,
> 		})
> 	defer tc.Stopper().Stop(context.TODO())
> ```

nit: do `ctx := context.TODO()` at the top and pass `ctx` instead of writing TODO over and over, unless you really need separate contexts for some reason.

---

*[pkg/sql/run_control_test.go, line 328 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23861#-L8XzmFeOXFNxA4UPzdJ:-L8XzmFeOXFNxA4UPzdK:b-ob45w7) ([raw file](https://github.com/cockroachdb/cockroach/blob/48941027aa1ab769d3183498ee9ff8a4801df7d9/pkg/sql/run_control_test.go#L328)):*
> ```Go
> 	// Verify that the connection is closed.
> 	if _, err = conn1.ExecContext(context.TODO(), "SELECT 1"); err != gosqldriver.ErrBadConn {
> 		t.Fatal("session not canceled")
> ```

Might want to also include a test that includes an active query, to assert that `CANCEL SESSION` also kills running queries.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23861#-:-L8Y-SjiFkp2EILcy1zY:bkfm5qe)*

**Comment by knz** [comment]
Overall the approach is sound and the technical aspects of the change are very good.

I am very happy to use the same ID generation as for queries. Despite dissenting opinions favoring the use of UUIDs, there are distinct benefits to avoid considering the ID as an opaque blob, and instead let it carry locality information.

We have had a similar discussion about query IDs before. You can trace that in the PR discussion around query listing/cancellation last year. The current choice for query IDs, which I am happy to see is adopted for session IDs too, has all sorts of benefits down the line, including the ability to track down the originator of a session when a session ID is embedded in distributed queries, or the ability to discover this information from SQL clients using SHOW SESSIONS.

Also beyond this enabling some code sharing, _it also enables sharing docs and concepts_ with SHOW QUERIES, reducing the cognitive overhead overall.

---

Reviewed 10 of 10 files at r1, 13 of 13 files at r2, 10 of 10 files at r3.
Review status: all files reviewed at latest revision, 17 unresolved discussions, all commit checks successful.

---

*[pkg/server/serverpb/status.proto, line 400 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23861#-L8XxWT6Dk__wsd5zauy:-L8YExPoAyPuOH5ECxQ1:b4vg45g) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e09ad68375b7deacadfc723123f99b0da0fb89b/pkg/server/serverpb/status.proto#L400)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Why don't we just use the UUID bytes here? I see that it was also done this way for query id... it's a bit unfortunate because this is 36 bytes instead of the 16 that it could be if it was sent over the wire as its raw bytes.
</blockquote></details>

It's not a UUID.

However, why use hex encoding? Why not the raw bytes directly in the string?

---

*[pkg/sql/cancel_session.go, line 35 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23861#-L8XyskzqPHt3usluaxe:-L8YFiVRzevvSu7_w6Nh:b-k8es0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff687e1c4df6dfe1b38f12aa60df02271356a089/pkg/sql/cancel_session.go#L35)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Do you think we should change the output of `SHOW SESSIONS` and the input to this to actually be a UUID type (since we do support those) instead of a string?
</blockquote></details>

They are not UUIDs (and for good reason - see my top-level comments).

---

*[pkg/sql/cancel_session.go, line 47 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23861#-L8YFnHNxBJ_4d6AKr-W:-L8YFnHNxBJ_4d6AKr-X:be41bb3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff687e1c4df6dfe1b38f12aa60df02271356a089/pkg/sql/cancel_session.go#L47)):*
> ```Go
> }
> 
> func (n *cancelSessionNode) startExec(params runParams) error {
> ```

Remove this definition from the 2nd commit -- `startExec` is optional and yours doesn't do anything in this commit. Add it only in the 3rd commit.

---

*[pkg/sql/cancel_session.go, line 60 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23861#-L8YG7yNwGcM7I2Wgqns:-L8YG7yNwGcM7I2Wgqnt:b-ctlp7u) ([raw file](https://github.com/cockroachdb/cockroach/blob/48941027aa1ab769d3183498ee9ff8a4801df7d9/pkg/sql/cancel_session.go#L60)):*
> ```Go
> 
> 	sessionIDString := tree.AsStringWithFlags(sessionIDDatum, tree.FmtBareStrings)
> 	sessionID, err := uint128.FromString(sessionIDString)
> ```

Make a method on the new type you'd have typedef'd at this point.

---

*[pkg/sql/cancel_session.go, line 66 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23861#-L8YG4U1HWwiPdZibv38:-L8YG4U1HWwiPdZibv39:b-bc8nf5) ([raw file](https://github.com/cockroachdb/cockroach/blob/48941027aa1ab769d3183498ee9ff8a4801df7d9/pkg/sql/cancel_session.go#L66)):*
> ```Go
> 
> 	// Get the lowest 32 bits of the session ID.
> 	nodeID := 0xFFFFFFFF & sessionID.Lo
> ```

Make a method. (Ditto for the query ID while you're at it).

---

*[pkg/sql/cancel_session.go, line 79 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23861#-L8YGi5Dzw4nOf9gYdjQ:-L8YGi5Dzw4nOf9gYdjR:bv5wfjq) ([raw file](https://github.com/cockroachdb/cockroach/blob/48941027aa1ab769d3183498ee9ff8a4801df7d9/pkg/sql/cancel_session.go#L79)):*
> ```Go
> 	}
> 
> 	if !response.Canceled {
> ```

nit: for consistency with every other SQL statement that's not idempotent by default (CREATE, DROP etc), please add a IF EXISTS variant to make it idempotent. 

(Also for CANCEL QUERY while you're at it).

---

*[pkg/sql/run_control_test.go, line 301 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23861#-L8YHFlo1F44T54Yd9YB:-L8YHFlo1F44T54Yd9YC:bs8kln7) ([raw file](https://github.com/cockroachdb/cockroach/blob/48941027aa1ab769d3183498ee9ff8a4801df7d9/pkg/sql/run_control_test.go#L301)):*
> ```Go
> 	}
> 
> 	// Wait for node 2 to know about both sessions.
> ```

This needs a timeout.

Also I think we have a RetryUntil method that abstracts what this loop does and does the timeout. 

---

*[pkg/sql/session.go, line 275 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23861#-L8YFI0V71CER37ld8hx:-L8YFI0V71CER37ld8hy:b5u2c72) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e09ad68375b7deacadfc723123f99b0da0fb89b/pkg/sql/session.go#L275)):*
> ```Go
> 	noCopy util.NoCopy
> 
> 	sessionID uint128.Uint128
> ```

I would recommend a typedef for this (and the query ID, while you're at it) to ease the reading of this definition.

---

*[pkg/sql/session.go, line 353 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23861#-L8YHXtPomezzkP10jwG:-L8YHXtPomezzkP10jwH:btp7nv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/48941027aa1ab769d3183498ee9ff8a4801df7d9/pkg/sql/session.go#L353)):*
> ```Go
> // CancelSession looks up the specified session in the session registry and cancels it.
> func (r *SessionRegistry) CancelSession(sessionIDStr string, username string) (bool, error) {
> 	sessionID, err := uint128.FromString(sessionIDStr)
> ```

make a method on the type you'd have typedef'd.

---

*[pkg/sql/session.go, line 373 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23861#-L8YHaWNUcVElQnz_S-V:-L8YHaWNUcVElQnz_S-W:b-jqaqdx) ([raw file](https://github.com/cockroachdb/cockroach/blob/48941027aa1ab769d3183498ee9ff8a4801df7d9/pkg/sql/session.go#L373)):*
> ```Go
> 	}
> 
> 	return false, fmt.Errorf("session ID %s not found", sessionID)
> ```

see my nit about IF EXISTS.

---

*[pkg/sql/sem/tree/stmt.go, line 225 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23861#-L8YGONoj6xf073tSWLH:-L8YGONoj6xf073tSWLI:b-2fvxbj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff687e1c4df6dfe1b38f12aa60df02271356a089/pkg/sql/sem/tree/stmt.go#L225)):*
> ```Go
> 
> // StatementTag returns a short string identifying the type of statement.
> func (*CancelSession) StatementTag() string { return "CANCEL SESSION" }
> ```

I believe that both this and CancelQuery above can implement `IndependentFromParallelizedPriors` defined at the beginning. Please check. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23861#-:-L8YDG23cPRQ4G0aiWAE:b5ahsyz)*

**Comment by abhimadan** [comment]
Review status: 3 of 32 files reviewed at latest revision, 17 unresolved discussions, some commit checks pending.

---

*[pkg/server/status.go, line 1375 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23861#-L8XzCYTmABJMtEU5HWd:-L8YW8Uk2ZmLAiRTmy47:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/48941027aa1ab769d3183498ee9ff8a4801df7d9/pkg/server/status.go#L1375)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This needs a docstring
</blockquote></details>

Done.

---

*[pkg/server/serverpb/status.proto, line 400 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23861#-L8XxWT6Dk__wsd5zauy:-L8bsKSR4kOL6hfVOZLm:b-jwdyhc) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e09ad68375b7deacadfc723123f99b0da0fb89b/pkg/server/serverpb/status.proto#L400)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

It's not a UUID.

However, why use hex encoding? Why not the raw bytes directly in the string?
</blockquote></details>

Changed to use bytes.

---

*[pkg/server/serverpb/status.proto, line 451 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23861#-L8XzGzsTY4XXVuqrgei:-L8bsO_g3RZFzUHhlVW3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/48941027aa1ab769d3183498ee9ff8a4801df7d9/pkg/server/serverpb/status.proto#L451)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Again should this be `bytes` instead of a `string`? Unfortunate that it was already done this way for cancel query. I guess might as well go with what we have already.
</blockquote></details>

Done.

---

*[pkg/sql/cancel_session.go, line 35 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23861#-L8XyskzqPHt3usluaxe:-L8bsW7w33u7JA1HpSqb:bhflfvl) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff687e1c4df6dfe1b38f12aa60df02271356a089/pkg/sql/cancel_session.go#L35)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

They are not UUIDs (and for good reason - see my top-level comments).
</blockquote></details>

Leaving as a string.

---

*[pkg/sql/cancel_session.go, line 47 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23861#-L8YFnHNxBJ_4d6AKr-W:-L8Z51FH9SvJDqEaTmJC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff687e1c4df6dfe1b38f12aa60df02271356a089/pkg/sql/cancel_session.go#L47)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Remove this definition from the 2nd commit -- `startExec` is optional and yours doesn't do anything in this commit. Add it only in the 3rd commit.
</blockquote></details>

Done.

---

*[pkg/sql/cancel_session.go, line 60 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23861#-L8YG7yNwGcM7I2Wgqns:-L8Ye_zk312YqwmMcGY9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/48941027aa1ab769d3183498ee9ff8a4801df7d9/pkg/sql/cancel_session.go#L60)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Make a method on the new type you'd have typedef'd at this point.
</blockquote></details>

Done.

---

*[pkg/sql/cancel_session.go, line 66 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23861#-L8YG4U1HWwiPdZibv38:-L8YWGRJ7NwnWs1Z4rSg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/48941027aa1ab769d3183498ee9ff8a4801df7d9/pkg/sql/cancel_session.go#L66)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Make a method. (Ditto for the query ID while you're at it).
</blockquote></details>

Done.

---

*[pkg/sql/cancel_session.go, line 79 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23861#-L8YGi5Dzw4nOf9gYdjQ:-L8Z4CD7-XH_fjRfPpu8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/48941027aa1ab769d3183498ee9ff8a4801df7d9/pkg/sql/cancel_session.go#L79)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: for consistency with every other SQL statement that's not idempotent by default (CREATE, DROP etc), please add a IF EXISTS variant to make it idempotent. 

(Also for CANCEL QUERY while you're at it).
</blockquote></details>

Done.

---

*[pkg/sql/conn_executor.go, line 1741 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23861#-L8XzTbGPgey8yc0I_ve:-L8YegUc5__0ijMGEbZC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/48941027aa1ab769d3183498ee9ff8a4801df7d9/pkg/sql/conn_executor.go#L1741)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

TODO(abhimadan)
</blockquote></details>

Done.

---

*[pkg/sql/crdb_internal.go, line 758 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23861#-L8XxpTXXO-Tl8EeGdi6:-L8YehM3421UMMY3jlS5:b4kyvs4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e09ad68375b7deacadfc723123f99b0da0fb89b/pkg/sql/crdb_internal.go#L758)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

this indentation should match the other lines
</blockquote></details>

I stared at this in my editor for a while until I realized I used a tab instead of two spaces. Fixed.

---

*[pkg/sql/run_control_test.go, line 287 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23861#-L8XzYNUb-qeCqDOH54w:-L8YeqRe2JDGvYKcyGoT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/48941027aa1ab769d3183498ee9ff8a4801df7d9/pkg/sql/run_control_test.go#L287)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: do `ctx := context.TODO()` at the top and pass `ctx` instead of writing TODO over and over, unless you really need separate contexts for some reason.
</blockquote></details>

Done.

---

*[pkg/sql/run_control_test.go, line 301 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23861#-L8YHFlo1F44T54Yd9YB:-L8Ykp2-6BRMJ5xtMmNi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/48941027aa1ab769d3183498ee9ff8a4801df7d9/pkg/sql/run_control_test.go#L301)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This needs a timeout.

Also I think we have a RetryUntil method that abstracts what this loop does and does the timeout. 
</blockquote></details>

Done.

---

*[pkg/sql/run_control_test.go, line 328 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23861#-L8XzmFeOXFNxA4UPzdJ:-L8bshZc3luf1XH5Day-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/48941027aa1ab769d3183498ee9ff8a4801df7d9/pkg/sql/run_control_test.go#L328)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Might want to also include a test that includes an active query, to assert that `CANCEL SESSION` also kills running queries.
</blockquote></details>

Done.

---

*[pkg/sql/session.go, line 275 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23861#-L8YFI0V71CER37ld8hx:-L8YetGB7uLT4Wv8A_-f:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e09ad68375b7deacadfc723123f99b0da0fb89b/pkg/sql/session.go#L275)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I would recommend a typedef for this (and the query ID, while you're at it) to ease the reading of this definition.
</blockquote></details>

Done.

---

*[pkg/sql/session.go, line 353 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23861#-L8YHXtPomezzkP10jwG:-L8Z0UAe9BgRFbnQyaMu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/48941027aa1ab769d3183498ee9ff8a4801df7d9/pkg/sql/session.go#L353)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

make a method on the type you'd have typedef'd.
</blockquote></details>

Done.

---

*[pkg/sql/session.go, line 373 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23861#-L8YHaWNUcVElQnz_S-V:-L8Z7XXN7Af25CKMBHbN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/48941027aa1ab769d3183498ee9ff8a4801df7d9/pkg/sql/session.go#L373)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

see my nit about IF EXISTS.
</blockquote></details>

Done.

---

*[pkg/sql/sem/tree/stmt.go, line 225 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23861#-L8YGONoj6xf073tSWLH:-L8bssR75fpP_7dp0dBs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff687e1c4df6dfe1b38f12aa60df02271356a089/pkg/sql/sem/tree/stmt.go#L225)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I believe that both this and CancelQuery above can implement `IndependentFromParallelizedPriors` defined at the beginning. Please check. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23861)*

**Comment by knz** [comment]
:lgtm: but maybe one of the changes needs a separate commit, see below.

---

Reviewed 4 of 28 files at r4, 13 of 14 files at r5, 12 of 12 files at r6.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/sql/conn_executor_exec.go, line 469 at r6](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23861#-L8gE0hS7G3Af8Sxdjy8:-L8gE0hS7G3Af8Sxdjy9:b3x8krh) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dc3ab52bd238da937087caf245be44991b0da10/pkg/sql/conn_executor_exec.go#L469)):*
> ```Go
> 	// TODO(abhimadan): remove the locking once the name resolution done in
> 	// makePlan no longer mutates stmt.
> 	ex.mu.Lock()
> ```

These two locking changes (here and below) deserve a separate commit I think, with an explanation in the commit message.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23861#-:-L8gEgAMA9AS4k0WN8cL:b-56styd)*

**Comment by abhimadan** [comment]
I'm putting this PR on hold temporarily. The locking here creates a deadlock for queries that use `SHOW SESSIONS` or `SHOW QUERIES` as subqueries (e.g., `SELECT query_id FROM [SHOW QUERIES]`). I get the feeling now that there's no simple band-aid solution to the name resolution race that motivated the locks around `makePlan`, so I'm going to look into fixing the root of the problem, if possible.

**Comment by abhimadan** [comment]
The underlying race is between query serialization (from `SHOW SESSIONS` and `SHOW QUERIES`) and type-checking and name resolution that occur during planning. Due to placeholders, type-checking must be in the planning phase. Name resolution may be possible to move before planning, but I haven't investigated too deeply.

Instead of fixing those races, I opted to restructure the tests to avoid encountering the races. They're only encountered when introspection queries are run just as another query starts and is still in its planning phase, which I think is fairly unlikely outside of a unit test (though it could be common if ORMs started to use `SHOW SESSIONS` and `SHOW QUERIES`). Also, we would expect a race like this on the `phase` column of the `crdb_internal.*queries` tables even if the races mentioned above are fixed.

**Comment by knz** [comment]
Thanks for the explanation! :shipit:

**Comment by abhimadan** [comment]
Sorry about not looping you in on this PR in the first place; it definitely would have been good to get your feedback on it as well. Those are very good points, though I'm not sure if I'll have time to do this in the last week of my internship, since I have a bit of remaining DistSQL work to finish up as well. I'll try to do this at the beginning of next week, and I'll let you know if I don't end up getting time for it.

---

Review status: 6 of 32 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23861#-:-LAUaw6q9orJuh7BYeip:b-1d258d)*

**Comment by andreimatei** [comment]
I'm addressing my previous comment partially in #30813

**Pull request merged**
