### PR TITLE
storage/engine: reproduce RocksDB DeleteRange bug

### PR DESCRIPTION
**Pull request by petermattis**
See #18371

### CODE REVIEW

**Review by bdarnell — APPROVED** [review]

**Comment by benesch** [comment]
```
[TestStyle/TestMissingLeakTest] style_test.go:93: storage/engine/rocksdb_test.go: TestRocksDBDeleteRangeBug: missing defer leaktest.AfterTest
```

**Review by benesch — APPROVED** [review]

**Comment by tamird** [comment]
Looking at this a bit late; how come the patch applied to our fork (https://github.com/cockroachdb/rocksdb/commit/e46ec6c430ef58fe531175aecc2cae5a8980c8ba?w=1) is different from the patch applied upstream (https://github.com/facebook/rocksdb/commit/0980dc6c9abe263531cb313af56c5018b8f4b331?w=1#diff-8c969f9ca48ea9f8ab6a82ce9da4d292)?

**Comment by petermattis** [comment]
That's interesting. I applied the patch in https://github.com/facebook/rocksdb/pull/2799/commits/4c05a1b38137c320c026dbd2d8b800ce1fa04dda (I believe I appended `.patch` to the URL). That commit doesn't seem to exist in the repo.

Both patches seem to fix the bug. Probably worthwhile to use the one in the RocksDB repo. Let me see if my wifi allows me to send out a PR.

**Comment by tamird** [comment]
Ah, I guess it was just an optimization? https://github.com/facebook/rocksdb/pull/2799#discussion_r135913719

**Pull request merged**
