### PR TITLE
insights: execution_insights_capacity cluster setting

### LINKED ISSUE #79450: insights: configurable memory storage / eviction policy
Here we expand on the walking skeleton by keeping more than 10 outliers in memory, developing a retention / eviction strategy.

Epic: CRDB-13544

Jira issue: CRDB-14869

### PR DESCRIPTION
**Pull request by matthewtodd**
Fixes #79450.

Whereas we previously retained only the 10 most recent insights, we now
let the user choose how many they'd like to hang onto.

It may make sense to be more sophisticated than a simple LRU cache here:
perhaps we won't want a single fingerprint to dominate the list. That
work is captured in https://github.com/cockroachdb/cockroach/issues/86271.

Release justification: Category 2: Bug fixes and low-risk updates to new
functionality.

Release note (ops change): The
`sql.insights.execution_insights_capacity` cluster setting was
introduced, limiting the number of SQL execution insights retained in
memory per node.

### CODE REVIEW

**Comment by matthewtodd** [comment]
@kevin-v-ngo could you review the naming here?

**Comment by kevin-v-ngo** [comment]
> max_per_nod

Thoughts on `sql.insights.node_execution_insights_rows.max` ?

- Appended '.max' to be consistent in our other settings (e.g., sql.stats.persisted_rows.max, sql.stats.response.max): https://www.cockroachlabs.com/docs/stable/cluster-settings.html
- Node prefix consistent with 'node_throttle_config'

- Specified '**execution**_insights' in case we introduce other insights in the future with new crdb_internal tables where this cluster setting would not apply and we may introduce a new one for those insights. Thoughts?

**Review by maryliag — APPROVED** [review]
Besides the name change :lgtm: 

> Reviewed 2 of 5 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86272#-:-N9fvk1--r6NDFbaMz5r:b-a9cote)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag and @matthewtodd)

___
*[`pkg/sql/sqlstats/insights/insights.go` line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86272#-N9fvcPJ9FZIIOEiinsH:-N9fvcPJ9FZIIOEiinsI:b3n98c5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b3e2772bc64259af424901eab269c6716398f7a/pkg/sql/sqlstats/insights/insights.go#L27)):*
> ```Go
> // MaxPerNode limits the number of insights retained in memory. As further
> // insights are had, the oldest ones are evicted.
> var MaxPerNode = settings.RegisterIntSetting(
> ```

I like Kevin's suggestion for the name, and when you update here don't forget to also update the parameter name to align.

**Comment by matthewtodd** [comment]
bors r-

I forgot to update the commit message after the rename.

**Pull request merged**
