### PR TITLE
storage: remove TODOs in cmd_push_txn

### PR DESCRIPTION
**Pull request by nvb**
This was discussed in https://github.com/cockroachdb/cockroach/pull/33523#pullrequestreview-191150177 but I missed digging into it at the time. I still don't think I have my head fully wrapped around it, but I do enough to know that it's not something I want to start pulling on right now.

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35162)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by nvanbenschoten** [comment]
`TestSQLAlchemy/SecondRun` flake. One more try.

bors r+

**Comment by nvanbenschoten** [comment]
Rebased to pick up the fix.

bors r+

**Comment by nvanbenschoten** [comment]
Never mind, this still hasn't been fixed yet.

bors r-

**Pull request merged**
