### PR TITLE
opt: add GeneratePartialIndexScans rule

### LINKED ISSUE #50232: opt: generate unconstrained scans over partial indexes
We should be able to generate unconstrained scans over partial indexes when the query filter implies the predicate.

### PR DESCRIPTION
**Pull request by mgartner**
This commit introduces a new exploration rule,
GeneratePartialIndexScans. This rule generates unconstrained Scans over
partial indexes when a Select filter implies the partial index
predicate.

For example, consider the table and query:

    CREATE TABLE t (
      i INT,
      s STRING,
      INDEX pidx (i) STORING (s) WHERE s = 'foo'
    )

    SELECT i FROM t WHERE s = 'foo'

GeneratePartialIndexScans will generate a scan over the partial index:

    project
     ├── columns: i:1
     └── scan t@pidx
          └── columns: i:1 s:3!null

It is capable of handling cases where the index does not cover the
selected columns, and where additional filtering is required after the
partial index scan. For example:

    CREATE TABLE t (
      i INT,
      s STRING,
      f FLOAT,
      INDEX pidx (i) WHERE s = 'foo'
    )

    SELECT i FROM t WHERE s = 'foo' AND f = 2.5

In this case, GeneratePartialIndexScans will generate the following
expression with an added Select and IndexJoin:

    project
     ├── columns: i:1
     └── index-join t
          ├── columns: i:1 s:2!null f:3!null
          └── select
               ├── columns: i:1 rowid:4!null
               ├── scan t@pidx
               │    └── columns: i:1 rowid:4!null
               └── filters
                    └── f:3 = 2.5

Fixes #50232 

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50070#-:-M9ZfuZG3tT6Z0j0clJL:bcmw7ss)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 134 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50070#-M9ZdNyw3L0NHt3Ls0s2:-M9ZdNyw3L0NHt3Ls0s3:b-jn6t1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a8ca76bc15ca30584d75769df0d9338d1cf63c5/pkg/sql/opt/xform/custom_funcs.go#L134)):*
> ```Go
> // GeneratePartialIndexScans generates unconstrained index scans over all
> // partial indexes with predicates that are implied by the filters. Partial
> // indexes with predicates cannot be proven to be implied by the filters are
> ```

[nit] which cannot
___
*[pkg/sql/opt/xform/custom_funcs.go, line 138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50070#-M9ZdRhU2RHGitT1X4Pd:-M9ZdRhU2RHGitT1X4Pe:bjdqao8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a8ca76bc15ca30584d75769df0d9338d1cf63c5/pkg/sql/opt/xform/custom_funcs.go#L138)):*
> ```Go
> //
> // When a filter completely matches the predicate, the remaining filters are
> // simplified so that they do not include the filter. A redundnat filter is
> ```

redundant
___
*[pkg/sql/opt/xform/custom_funcs.go, line 193 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50070#-M9Zds8wDFLvtKDvlh3a:-M9Zds8wDFLvtKDvlh3b:b-n3lnav) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a8ca76bc15ca30584d75769df0d9338d1cf63c5/pkg/sql/opt/xform/custom_funcs.go#L193)):*
> ```Go
> 		// If index is covering and there are no remaining filters, construct a
> 		// new Scan in the same group as the original Select.
> 		if remainingFilters.ChildCount() == 0 && covering {
> ```

[nit] `len(remainingFilters)`
___
*[pkg/sql/opt/xform/custom_funcs.go, line 196 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50070#-M9ZfRqa6ltMiQUiSBcG:-M9ZfRqa6ltMiQUiSBcH:bq6o65m) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a8ca76bc15ca30584d75769df0d9338d1cf63c5/pkg/sql/opt/xform/custom_funcs.go#L196)):*
> ```Go
> 			scan := memo.ScanExpr{ScanPrivate: *scanPrivate}
> 			scan.Index = iter.IndexOrdinal()
> 			c.e.mem.AddScanToGroup(&scan, grp)
> ```

[nit] Doesn't `indexScanBuilder` cover this case too?
___
*[pkg/sql/opt/xform/custom_funcs.go, line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50070#-M9ZfD98DYU9KqPGxzDL:-M9Zf5tdD1vF4scBjZQI:b80b2bt) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a8ca76bc15ca30584d75769df0d9338d1cf63c5/pkg/sql/opt/xform/custom_funcs.go#L226)):*
> ```Go
> 
> 		// If there are remaining filters, construct a Select with them.
> 		if remainingFilters.ChildCount() != 0 {
> ```

We don't need this check (`addSelect` already checks it)
___
*[pkg/sql/opt/xform/partial_index.go, line 20 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50070#-M9ZeC3k9DSN93fpHBCp:-M9ZeC3k9DSN93fpHBCq:b-npoer2) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a8ca76bc15ca30584d75769df0d9338d1cf63c5/pkg/sql/opt/xform/partial_index.go#L20)):*
> ```Go
> )
> 
> // predicateImpliedByFilters attempts to prove that a partial index predicate is
> ```

I think this is accidentally left over
___
*[pkg/sql/opt/xform/testdata/rules/select, line 223 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50070#-M9ZfpT99WVxI6fl6Mau:-M9ZfpT99WVxI6fl6Mav:b2c0w3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a8ca76bc15ca30584d75769df0d9338d1cf63c5/pkg/sql/opt/xform/testdata/rules/select#L223)):*
> ```
>       └── filters
>            └── NOT b:4 [outer=(4), constraints=(/4: [/false - /false]; tight), fd=()-->(4)]
> ```

Maybe add a test where the table has multiple partial indexes (as well as some non-partial indexes).

**Review by rytaft — APPROVED** [review]
Nice! :lgtm: once you address Radu's comments.

> Reviewed 5 of 5 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50070#-:-M9_UHOn3ProWJPtWL3z:b-a8kf9d)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/testutils/opttester/opt_tester.go, line 830 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50070#-M9_QgKG66RnR4bCHuOS:-M9_QgKG66RnR4bCHuOT:b-kmlkdq) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a8ca76bc15ca30584d75769df0d9338d1cf63c5/pkg/sql/opt/testutils/opttester/opt_tester.go#L830)):*
> ```Go
> 			return false
> 		}
> 		return true
> ```

While you're making changes here, probably worth adding the ruleName to `ot.seenRules` like we do in `Optimize` above
___
*[pkg/sql/opt/xform/custom_funcs.go, line 144 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50070#-M9_RHxZ-NHEsZH541gL:-M9_RHxZ-NHEsZH541gM:b-uhh223) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a8ca76bc15ca30584d75769df0d9338d1cf63c5/pkg/sql/opt/xform/custom_funcs.go#L144)):*
> ```Go
> // For each partial index, there are two conditions to consider: whether or not
> // the index "covers" the columns needed and whether or not the remaining filter
> // is empty. There two conditions combine to create four possible cases:
> ```

There two -> These two
___
*[pkg/sql/opt/xform/custom_funcs.go, line 148 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50070#-M9_RgKO21LMAFxGxvrl:-M9_RgKO21LMAFxGxvrm:bhdrqzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a8ca76bc15ca30584d75769df0d9338d1cf63c5/pkg/sql/opt/xform/custom_funcs.go#L148)):*
> ```Go
> //   - The index is covering and the remaining filter is empty. In this case, A
> //     single unconstrained Scan operator is added to the same group as the
> //     original Select operator).
> ```

[nit] extra ")"
___
*[pkg/sql/opt/xform/custom_funcs.go, line 191 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50070#-M9_S4Qs8UnOeE2TzDDJ:-M9_S4Qt3ZfOuDhpVj_7:b5x2rz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a8ca76bc15ca30584d75769df0d9338d1cf63c5/pkg/sql/opt/xform/custom_funcs.go#L191)):*
> ```Go
> 		covering := iter.IsCovering()
> 
> 		// If index is covering and there are no remaining filters, construct a
> ```

[nit] It would help to number the 4 cases above and refer to the case numbers in the comments here.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50070)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/testutils/opttester/opt_tester.go, line 830 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50070#-M9_QgKG66RnR4bCHuOS:-M9_lSdO6YR1fUfFasBT:b9a00ci) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a8ca76bc15ca30584d75769df0d9338d1cf63c5/pkg/sql/opt/testutils/opttester/opt_tester.go#L830)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

While you're making changes here, probably worth adding the ruleName to `ot.seenRules` like we do in `Optimize` above
</blockquote></details>

I've undid these changes for now, because I no longer need them.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 134 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50070#-M9ZdNyw3L0NHt3Ls0s2:-M9_7koy9uxHt3sMuyv0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a8ca76bc15ca30584d75769df0d9338d1cf63c5/pkg/sql/opt/xform/custom_funcs.go#L134)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] which cannot
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 191 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50070#-M9_S4Qs8UnOeE2TzDDJ:-M9_lWO3EhtzNsihO7ch:b-q2m8mk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a8ca76bc15ca30584d75769df0d9338d1cf63c5/pkg/sql/opt/xform/custom_funcs.go#L191)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] It would help to number the 4 cases above and refer to the case numbers in the comments here.
</blockquote></details>

Turns out there's actually 6 cases. I've rewritten this comment to be more clear, and I've rewritten the code to be _correct_ and also less verbose. LMK what you think!
___
*[pkg/sql/opt/xform/custom_funcs.go, line 196 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50070#-M9ZfRqa6ltMiQUiSBcG:-M9_NjT2EYQeL41ZnlfG:bxuvksn) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a8ca76bc15ca30584d75769df0d9338d1cf63c5/pkg/sql/opt/xform/custom_funcs.go#L196)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Doesn't `indexScanBuilder` cover this case too?
</blockquote></details>

Thanks for the pointers. I've simplified this code, and fixed a bug—it wasn't splitting the filters into 2 Selects when part of the filters must be applied before the IndexJoin and the remaining filters must be applied after.
___
*[pkg/sql/opt/xform/partial_index.go, line 20 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50070#-M9ZeC3k9DSN93fpHBCp:-M9_OJl1ExSAnqxjsxa8:b-834n6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a8ca76bc15ca30584d75769df0d9338d1cf63c5/pkg/sql/opt/xform/partial_index.go#L20)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I think this is accidentally left over
</blockquote></details>

Oops!
___
*[pkg/sql/opt/xform/testdata/rules/select, line 223 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50070#-M9ZfpT99WVxI6fl6Mau:-M9_a5Zl-YsjdhVtQPpB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a8ca76bc15ca30584d75769df0d9338d1cf63c5/pkg/sql/opt/xform/testdata/rules/select#L223)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Maybe add a test where the table has multiple partial indexes (as well as some non-partial indexes).
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50070)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 191 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50070#-M9_S4Qs8UnOeE2TzDDJ:-M9_tEt290FHctwxjkPF:b-vs1prh) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a8ca76bc15ca30584d75769df0d9338d1cf63c5/pkg/sql/opt/xform/custom_funcs.go#L191)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Turns out there's actually 6 cases. I've rewritten this comment to be more clear, and I've rewritten the code to be _correct_ and also less verbose. LMK what you think!
</blockquote></details>

Looks good!

**Pull request merged**
