### PR TITLE
exec: defend against setupVectorized panics

### PR DESCRIPTION
**Pull request by asubiotto**
There are cases in which setupVectorized may panic for benign reasons.
For example, an operator might unconditionally create a NewMemBatch with
an unsupported type (e.g. timestamp). We want to catch these kinds of
panics and treat them as setup errors.

Release note: None

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38556)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/distsqlrun/flow.go, line 502 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38556#-LifeTTm6q9F2neTw74J:-LifeTTm6q9F2neTw74K:bvw8wog) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1debd437f05f5c0adf3cdab5820629c62fd856b/pkg/sql/distsqlrun/flow.go#L502)):*
> ```Go
> 	if f.EvalCtx.SessionData.Vectorize != sessiondata.VectorizeOff {
> 		var err error
> 		panicErr := exec.CatchVectorizedRuntimeError(func() { err = f.setupVectorized(ctx) })
> ```

It kind of feels like `setupVectorized` should be the one to catch the panic, rather than this thing.https://github.com/golang/go/wiki/PanicAndRecover#usage-in-a-package says you should not panic across package boundaries by convention, although I suppose we already do that in the materializer. Maybe this is an excuse to move the catching of panics into a helper, so we don't have to repeat ourselves in the routers, unordered sync, and materializer.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38556)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/distsqlrun/flow.go, line 502 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38556#-LifeTTm6q9F2neTw74J:-LirsjPqD6mq4PZBwZiC:b-g5e4xz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1debd437f05f5c0adf3cdab5820629c62fd856b/pkg/sql/distsqlrun/flow.go#L502)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

It kind of feels like `setupVectorized` should be the one to catch the panic, rather than this thing.https://github.com/golang/go/wiki/PanicAndRecover#usage-in-a-package says you should not panic across package boundaries by convention, although I suppose we already do that in the materializer. Maybe this is an excuse to move the catching of panics into a helper, so we don't have to repeat ourselves in the routers, unordered sync, and materializer.
</blockquote></details>

My understanding is that `exec.CatchVectorizedRuntimeError` is already a helper in the `exec` package catching panics from that package, it just happens to be used in `distsqlrun` because of planning. Could you expand on what an ideal world would look like?

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38556)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/distsqlrun/flow.go, line 502 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38556#-LifeTTm6q9F2neTw74J:-LjaXYoF5oUjw0abt1wx:bj8yf4d) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1debd437f05f5c0adf3cdab5820629c62fd856b/pkg/sql/distsqlrun/flow.go#L502)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

My understanding is that `exec.CatchVectorizedRuntimeError` is already a helper in the `exec` package catching panics from that package, it just happens to be used in `distsqlrun` because of planning. Could you expand on what an ideal world would look like?
</blockquote></details>

whoops, sorry I forgot to respond to this. What I mean to say is that in the ideal world, we'd have just a couple of main entry points into exec, one of which would be `newColOperator` (not currently possible because that lives in distsqlrun, not `exec`. I would say all of the main entry points into exec should be responsible for never letting a panic escape - and instead always returning an error.

**Comment by asubiotto** [comment]
Is this still an issue? @yuzefovich who might know more about the current state of vectorized setup and panic handling. I'm especially concerned about unsupported types (i.e. components creating a mem batch with an unsupported type e.g. timestamp).

**Comment by asubiotto** [comment]
Talked to @yuzefovich offline. Looks like our pre-check handles this now.

**Pull request closed without merging**
