### PR TITLE
protectedts: add reconciliation loop and adopt

### PR DESCRIPTION
**Pull request by ajwerner**
See individual commits.

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, 6 of 6 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45176#-:-M0V54Y6B2BdtJ1SPDM8:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/jobs/jobs.go, line 553 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45176#-M0V3l5eCEo9a30ubh9m:-M0V3l5fDgfi1mf5vBVS:bgz4l74) ([raw file](https://github.com/cockroachdb/cockroach/blob/18a79762000750ed2c384338f5121f5da0a76aa9/pkg/jobs/jobs.go#L553)):*
> ```Go
> }
> 
> // Error makes JobNotFoundError and error.
> ```

"an error"
___
*[pkg/jobs/jobsprotectedts/jobs_protected_ts.go, line 29 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/45176#-M0V4Bd9BA2habq0FgrV:-M0V4Bd9BA2habq0FgrW:b9ors9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/b646780e77ba6aef19069151f0b54c88eae85945/pkg/jobs/jobsprotectedts/jobs_protected_ts.go#L29)):*
> ```Go
> // MetaType is the value used in the ptpb.Record.MetaType field for records
> // associated with jobs.
> const MetaType = "jobs"
> ```

Add a note that this value cannot change.
___
*[pkg/jobs/jobsprotectedts/jobs_protected_ts.go, line 35 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/45176#-M0V4koZ4aX765X5TuAo:-M0V4koZ4aX765X5TuAp:b-dst21) ([raw file](https://github.com/cockroachdb/cockroach/blob/b646780e77ba6aef19069151f0b54c88eae85945/pkg/jobs/jobsprotectedts/jobs_protected_ts.go#L35)):*
> ```Go
> func MakeStatusFunc(jr *jobs.Registry) ptreconcile.StatusFunc {
> 	return func(ctx context.Context, txn *client.Txn, meta []byte) (shouldRemove bool, _ error) {
> 		jobID, err := strconv.ParseInt(string(meta), 10, 64)
> ```

Consider pulling the encoding and decoding of this meta field into separate functions so that its easier to search for and understand without that logic being hidden in here.
___
*[pkg/storage/protectedts/ptreconcile/reconciler.go, line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45176#-M0V0ZQB5Ye598zZoini:-M0V0ZQB5Ye598zZoinj:b-mr9iy4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5eccbcd241aa627acf468fed1af391c196b357f/pkg/storage/protectedts/ptreconcile/reconciler.go#L39)):*
> ```Go
> 	"kv.protectedts.reconciliation.interval",
> 	"the frequency for reconciling jobs with protected timestamp records",
> 	time.Minute,
> ```

Should this be 5 minutes? That's what the commit message says.
___
*[pkg/storage/protectedts/ptreconcile/reconciler.go, line 163 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45176#-M0V28as89mLsAsUIDl8:-M0V28at8-W90vQ24eAj:b-uyu6ry) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5eccbcd241aa627acf468fed1af391c196b357f/pkg/storage/protectedts/ptreconcile/reconciler.go#L163)):*
> ```Go
> 		task, ok := r.statusFuncs[rec.MetaType]
> 		if !ok {
> 			return true
> ```

Is this considered an error case or is it ok for certain meta types to not have reconciliation functions?
___
*[pkg/storage/protectedts/ptreconcile/reconciler.go, line 189 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45176#-M0V2Nt5CbVpzb3Ino_b:-M0V2Nt5CbVpzb3Ino_c:b-tmzg9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5eccbcd241aa627acf468fed1af391c196b357f/pkg/storage/protectedts/ptreconcile/reconciler.go#L189)):*
> ```Go
> 			r.metrics.RecordsProcessed.Inc(1)
> 		} else {
> 			r.metrics.ReconciliationErrors.Inc(1)
> ```

Why isn't it enough to put this in the `err != nil` case?

**Review by ajwerner — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45176#-:-M0Z4gcl-3RpNs86xesZ:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/jobs/jobs.go, line 553 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45176#-M0V3l5eCEo9a30ubh9m:-M0Z19UwAQd4TQ62ENOU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/18a79762000750ed2c384338f5121f5da0a76aa9/pkg/jobs/jobs.go#L553)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"an error"
</blockquote></details>

Done.
___
*[pkg/jobs/jobsprotectedts/jobs_protected_ts.go, line 29 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/45176#-M0V4Bd9BA2habq0FgrV:-M0Z4S4a2M1ZqsaQET7P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b646780e77ba6aef19069151f0b54c88eae85945/pkg/jobs/jobsprotectedts/jobs_protected_ts.go#L29)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Add a note that this value cannot change.
</blockquote></details>

Done.
___
*[pkg/jobs/jobsprotectedts/jobs_protected_ts.go, line 35 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/45176#-M0V4koZ4aX765X5TuAo:-M0Z4Sih4KHqqq7v5a3q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b646780e77ba6aef19069151f0b54c88eae85945/pkg/jobs/jobsprotectedts/jobs_protected_ts.go#L35)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Consider pulling the encoding and decoding of this meta field into separate functions so that its easier to search for and understand without that logic being hidden in here.
</blockquote></details>

Done.
___
*[pkg/storage/protectedts/ptreconcile/reconciler.go, line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45176#-M0V0ZQB5Ye598zZoini:-M0Z-IX3DHJ9BmgtobbL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5eccbcd241aa627acf468fed1af391c196b357f/pkg/storage/protectedts/ptreconcile/reconciler.go#L39)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should this be 5 minutes? That's what the commit message says.
</blockquote></details>

Done.
___
*[pkg/storage/protectedts/ptreconcile/reconciler.go, line 163 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45176#-M0V28as89mLsAsUIDl8:-M0Yzrxx6gPT4ai9gbkS:b-cils36) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5eccbcd241aa627acf468fed1af391c196b357f/pkg/storage/protectedts/ptreconcile/reconciler.go#L163)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this considered an error case or is it ok for certain meta types to not have reconciliation functions?
</blockquote></details>

It's a good question. It's only envisioned in testing. I added a `log.Infof`and an `NB`
___
*[pkg/storage/protectedts/ptreconcile/reconciler.go, line 189 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45176#-M0V2Nt5CbVpzb3Ino_b:-M0Z-BVSDs1Qw5x-rI5H:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5eccbcd241aa627acf468fed1af391c196b357f/pkg/storage/protectedts/ptreconcile/reconciler.go#L189)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why isn't it enough to put this in the `err != nil` case?
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 15 of 15 files at r8, 6 of 6 files at r9, 2 of 2 files at r10, 2 of 2 files at r11, 2 of 2 files at r12, 1 of 1 files at r13, 4 of 4 files at r14.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45176#-:-M0Z5morEXL2LNxONQ-G:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/storage/protectedts/ptreconcile/reconciler.go, line 163 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45176#-M0V28as89mLsAsUIDl8:-M0Z5NSO2h37WGU5vpCS:b-5nac6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5eccbcd241aa627acf468fed1af391c196b357f/pkg/storage/protectedts/ptreconcile/reconciler.go#L163)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

It's a good question. It's only envisioned in testing. I added a `log.Infof`and an `NB`
</blockquote></details>

Is the `NB` supposed to be here or above? Just double checking.

**Review by ajwerner — COMMENTED** [review]
bors r=nvanbenschoten

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45176#-:-M0ZrP9p04B-q2egBGfL:b-nvg7rs)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[pkg/storage/protectedts/ptreconcile/reconciler.go, line 163 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45176#-M0V28as89mLsAsUIDl8:-M0ZrNHA1ct4SBZ3rZP6:b-39v3cp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5eccbcd241aa627acf468fed1af391c196b357f/pkg/storage/protectedts/ptreconcile/reconciler.go#L163)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is the `NB` supposed to be here or above? Just double checking.
</blockquote></details>

Whoops, fixed.

**Pull request merged**
