### PR TITLE
backupccl: modify file stitching semantics to reduce ooo flushes

### PR DESCRIPTION
**Pull request by adityamaru**
This change tweaks the file stitching semantics to reduce the
number of out-of-order flushes of SST files we see during a backup.

Previously, we would buffer the SSTs returned by the ExportResponse,
and after hitting a certain max size we would sort and drain the queue.
Experimentation showed that we still incurred a high number of out of
order flushes that were preventing SST files written to ExternalStorage from
hitting their target sizes. Furthermore, we were seeing very few "spanGrows"
which refers to the SST returned by ExportResponse growing the previous span
in the underlying SST, and thereby not creating a `BackupManifest_File` entry
in the manifest.

Our goal is to minimize ooo flushes, and maximise span grows.
This change, at the cost of being computationally more expensive, tries to do
just this. Every time we see a `returnedSST` from an ExportResponse we add it
to the underlying btree, which is sorted on Span.Key. We then Ascend the tree
starting at the Span of the last flushed file, and check for all those `returnedSST`s
that have a `Span.Key >= LastSpan.EndKey` and write it to the underlying SST file.
This is correct, because the SST files need to be in-order. In this way we
"greedily" fill up the underlying SST until we can no more given our buffered
elements.

Preliminary experimentation has shown that this greatly reduces the number
of ooo flushes. It also increases the `spanGrows` but this is proportional
to how much the max buffer size is set to. The more one can buffer, the more
the `spanGrows`, and the less we store in the manifest.

I'll be running a few more experiments, results of which I'll post below.

Informs: #73815

### CODE REVIEW

**Comment by adityamaru** [comment]
@dt I want to run this by you before I clean it up:

There's a decrease in OOO flushes, and an increase in span grows, but maybe there is something more we can do here.
The first is using the changes in this PR, the second is the logic on master. Each line represents a "node" with its own sink with max buffer size set to 64MiB. The CSVs were generated from a TPCC 5k cluster.

The more we bump up the buffered SST max size, the more span grows we get. I'm still trying to wrap my head around this correlation.

```
[-] 55  ****NODE****
[-] 56  sink stats: {files:4915 flushes:0 oooFlushes:130 sizeFlushes:0 spanGrows:127}
[-] 57  ****NODE****
[-] 58  sink stats: {files:5066 flushes:0 oooFlushes:131 sizeFlushes:0 spanGrows:85}
[-] 59  ****NODE****
[-] 60  sink stats: {files:4777 flushes:0 oooFlushes:117 sizeFlushes:0 spanGrows:93}
[-] 61  ****NODE****
[-] 62  sink stats: {files:4990 flushes:0 oooFlushes:126 sizeFlushes:0 spanGrows:186}
[-] 63  ****NODE****
[-] 64  sink stats: {files:5892 flushes:0 oooFlushes:174 sizeFlushes:0 spanGrows:89}
[-] 65  ****NODE****
[-] 66  sink stats: {files:4961 flushes:0 oooFlushes:106 sizeFlushes:0 spanGrows:122}
```


```
[-] 55  ****NODE****
[-] 56  sink stats: {files:4915 flushes:0 oooFlushes:231 sizeFlushes:0 spanGrows:39}
[-] 57  ****NODE****
[-] 58  sink stats: {files:5066 flushes:0 oooFlushes:250 sizeFlushes:0 spanGrows:27}
[-] 59  ****NODE****
[-] 60  sink stats: {files:4777 flushes:0 oooFlushes:211 sizeFlushes:0 spanGrows:35}
[-] 61  ****NODE****
[-] 62  sink stats: {files:4990 flushes:0 oooFlushes:214 sizeFlushes:0 spanGrows:101}
[-] 63  ****NODE****
[-] 64  sink stats: {files:5892 flushes:0 oooFlushes:230 sizeFlushes:0 spanGrows:47}
[-] 65  ****NODE****
[-] 66  sink stats: {files:4961 flushes:0 oooFlushes:228 sizeFlushes:0 spanGrows:50}
```

**Comment by adityamaru** [comment]
For incremental backups:

```
[-] 52  ****NODE****
[-] 53  sink stats: {files:481 flushes:0 oooFlushes:1 sizeFlushes:0 spanGrows:64}
 [-] 54  ****NODE****
[-] 55  sink stats: {files:515 flushes:0 oooFlushes:1 sizeFlushes:0 spanGrows:75}
[-] 56  ****NODE****
[-] 57  sink stats: {files:470 flushes:0 oooFlushes:1 sizeFlushes:0 spanGrows:45}
[-] 58  ****NODE****
[-] 59  sink stats: {files:506 flushes:0 oooFlushes:1 sizeFlushes:0 spanGrows:81}
[-] 60  ****NODE****
[-] 61  sink stats: {files:588 flushes:0 oooFlushes:1 sizeFlushes:0 spanGrows:78}
[-] 62  ****NODE****
[-] 63  sink stats: {files:477 flushes:0 oooFlushes:1 sizeFlushes:0 spanGrows:56}
```

```
   [-] 83  ****NODE****
   [-] 84  sink stats: {files:481 flushes:0 oooFlushes:3 sizeFlushes:0 spanGrows:89 }
   [-] 85  ****NODE****
   [-] 86  sink stats: {files:515 flushes:0 oooFlushes:14 sizeFlushes:0 spanGrows:66}
   [-] 87  ****NODE****
   [-] 88  sink stats: {files:470 flushes:0 oooFlushes:45 sizeFlushes:0 spanGrows:1}
   [-] 89  ****NODE****
   [-] 90  sink stats: {files:506 flushes:0 oooFlushes:11 sizeFlushes:0 spanGrows:67}
   [-] 91  ****NODE****
   [-] 92  sink stats: {files:588 flushes:0 oooFlushes:40 sizeFlushes:0 spanGrows:5 }
   [-] 93  ****NODE****
   [-] 94  sink stats: {files:477 flushes:0 oooFlushes:45 sizeFlushes:0 spanGrows:1}
```

**Comment by dt** [comment]
huh, yeah, I'm surprised we have so few spanGrows given how few ooo flushes there are maybe the input spans just have holes in them based on leaseholders so that's the best we can do?

**Comment by adityamaru** [comment]
Ran some experiments on a 5K TPCC 6 node cluster with buffer size = 16MiB. 

Vanilla: ExportRequestsLimit * 2
Without multiplier: ExportRequestsLimit
Plus 1: ExportRequestLimit + 1

Backup times are not too far apart. Span grows are _marginally_ better when there is no multiplier. Maybe I need to run backups on a larger data set to confirm these findings. The b-tree approach above does significantly reduce the ooo flushes and increases span grows so I think there is value in it. 

```
Code on master:

Vanilla:  12:11

n5] 13608 backup sst sink recv'd 4084 files, wrote 581 (19 due to size, 561 due to re-ordering), 5 recv files extended prior span
n6,job=721051154762465281] 16056 backup sst sink recv'd 4723 files, wrote 811 (16 due to size, 794 due to re-ordering), 1 recv files extended prior span
n3] 14984 backup sst sink recv'd 4134 files, wrote 641 (30 due to size, 610 due to re-ordering), 3 recv files extended prior span
n4] 15417 backup sst sink recv'd 4351 files, wrote 663 (25 due to size, 637 due to re-ordering), 2 recv files extended prior span
n1] 16004 backup sst sink recv'd 4137 files, wrote 579 (20 due to size, 558 due to re-ordering), 6 recv files extended prior span
n2] 16149 backup sst sink recv'd 4224 files, wrote 677 (24 due to size, 652 due to re-ordering), 5 recv files extended prior span


Without multiplier:   12:39


n5] 4264 backup sst sink recv'd 3459 files, wrote 606 (12 due to size, 593 due to re-ordering), 24 recv files extended prior span
n6] 6090 backup sst sink recv'd 4319 files, wrote 824 (18 due to size, 805 due to re-ordering), 4 recv files extended prior span
n3] 6082 backup sst sink recv'd 3964 files, wrote 569 (35 due to size, 533 due to re-ordering), 4 recv files extended prior span
n4] 6276 backup sst sink recv'd 3992 files, wrote 606 (24 due to size, 581 due to re-ordering), 31 recv files extended prior span
n1,job=721064703401852929] 7115 backup sst sink recv'd 4142 files, wrote 811 (17 due to size, 793 due to re-ordering), 6 recv files extended prior span
n2] 7114 backup sst sink recv'd 4157 files, wrote 821 (25 due to size, 795 due to re-ordering), 8 recv files extended prior span


With +1:  14:12

n5] 8110 backup sst sink recv'd 3594 files, wrote 627 (11 due to size, 615 due to re-ordering), 10 recv files extended prior span
n6] 9832 backup sst sink recv'd 4292 files, wrote 962 (13 due to size, 948 due to re-ordering), 11 recv files extended prior span
n4] 9046 backup sst sink recv'd 3910 files, wrote 770 (18 due to size, 751 due to re-ordering), 1 recv files extended prior span
n3] 9443 backup sst sink recv'd 4129 files, wrote 798 (34 due to size, 763 due to re-ordering), 6 recv files extended prior span
n1,job=721071259827142657] 9459 backup sst sink recv'd 4177 files, wrote 718 (15 due to size, 702 due to re-ordering), 6 recv files extended prior span
n2] 8677 backup sst sink recv'd 3720 files, wrote 697 (17 due to size, 679 due to re-ordering), 1 recv files extended prior span





With btree:

Vanilla:  14:25

n5] 8383 backup sst sink recv'd 3529 files, wrote 234 (16 due to size, 217 due to re-ordering), 34 recv files extended prior span
n3] 8437 backup sst sink recv'd 3440 files, wrote 258 (14 due to size, 243 due to re-ordering), 17 recv files extended prior span
n4] 8387 backup sst sink recv'd 3551 files, wrote 266 (13 due to size, 252 due to re-ordering), 36 recv files extended prior span
n1] 9129 backup sst sink recv'd 3496 files, wrote 262 (12 due to size, 249 due to re-ordering), 39 recv files extended prior span
n6,job=721090238458101761] 12281 backup sst sink recv'd 5316 files, wrote 477 (8 due to size, 468 due to re-ordering), 48 recv files extended prior span
n2] 10757 backup sst sink recv'd 4392 files, wrote 408 (11 due to size, 396 due to re-ordering), 60 recv files extended prior span


Without multiplier: 15:19

n5] 7272 backup sst sink recv'd 3429 files, wrote 216 (8 due to size, 207 due to re-ordering), 40 recv files extended prior span
n6] 9407 backup sst sink recv'd 4442 files, wrote 308 (15 due to size, 292 due to re-ordering), 51 recv files extended prior span
n1] 8221 backup sst sink recv'd 3758 files, wrote 273 (20 due to size, 252 due to re-ordering), 11 recv files extended prior span
n4,job=721110435278782465] 8731 backup sst sink recv'd 4130 files, wrote 325 (19 due to size, 305 due to re-ordering), 5 recv files extended prior span
n2] 6807 backup sst sink recv'd 3124 files, wrote 210 (19 due to size, 190 due to re-ordering), 15 recv files extended prior span
n3] 10546 backup sst sink recv'd 4924 files, wrote 410 (19 due to size, 390 due to re-ordering), 19 recv files extended prior span
```

**Comment by adityamaru** [comment]
Closing for now, can revisit if deemed necessary.

**Pull request closed without merging**
