### PR TITLE
pkg/sql: export AggregatedStatementStatistics

### PR DESCRIPTION
**Pull request by abarganier**
This patch hooks into the Flush functionality used
by PersistedSQLStats, causing the statement statistics
being flushed to be transformed & given to the
EventsExporter, which prepares them to be sent
to external o11y systems.

If CRDB is not configured at node startup to target
an external o11y system (right now determined by the
presence of the `--obsservice-addr`), then we skip
this transformation & export step entirely within
the flush logic.

By default, Flush happens every 10 minutes, where
statement statistics being aggregated in-memory are
flushed to disk (and now, to the address configured
by the `--obsservice-addr` flag). This means that
the data received by the external system will have
a granularity of 10 minutes. However, the 10 minute
intervals are unlikely to be aligned against a clock
yet (e.g. 10:00, 10:10, 10:20, etc). This is because
the 10 minute flush happens on a *timer*, which is
started at node initialization. Alignment of the
flushes to the clock is planned work. For now,
getting the data exported is a good first start.

Lastly, it's acknowledged that the transformation
required here is likely going to be heavy on
allocations. During the prototyping phase however,
we leave the optimization and/or restructuring of
the exported type for the future.

Release note: none

Epic: CRDB-28191

### CODE REVIEW

**Review by knz — APPROVED** [review]
thanks

> Reviewed 2 of 2 files at r1, 9 of 9 files at r2, 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111875#-:-Ng4V_yvBl2nMQHrrq_C:b-k73z76)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @j82w)

___
*[`-- commits` line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111875#-Ng4UK6KBSgl8xNm0PxB):*
nit: this commit message would be more readable if you could wrap at 70+ columns instead of 55.

**Review by j82w — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111875)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @knz)

___
*[`pkg/sql/pgwire/server.go` line 319 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111875#-NgKi-3u4X0bHttxjWcB:-NgKi-3u4X0bHttxjWcC:b-7oso64) ([raw file](https://github.com/cockroachdb/cockroach/blob/7813cfa094d31255016516e1c612d8d04295ef64/pkg/sql/pgwire/server.go#L319)):*
> ```Go
> 	parentMemoryMonitor *mon.BytesMonitor,
> 	histogramWindow time.Duration,
> 	eventsExporter obs.EventsExporterInterface,
> ```

should this be a pointer?
___
*[`pkg/sql/sqlstats/persistedsqlstats/flush.go` line 163 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111875#-NgKeFkk82omruGT_nRq:-NgKeFkk82omruGT_nRr:b-1rt431) ([raw file](https://github.com/cockroachdb/cockroach/blob/7813cfa094d31255016516e1c612d8d04295ef64/pkg/sql/sqlstats/persistedsqlstats/flush.go#L163)):*
> ```Go
> func (s *PersistedSQLStats) flushStmtStats(ctx context.Context, aggregatedTs time.Time) {
> 	// If we are dealing with a NoopEventsExporter, skip all the work involved to provide it with data.
> 	_, skipEventsExporterFlush := s.eventsExporter.(obs.NoopEventsExporter)
> ```

I think a cluster setting should be added to be on the safe side. 
___
*[`pkg/sql/sqlstats/persistedsqlstats/flush.go` line 168 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111875#-NgKiEN_0Ax6hFX-uiSm:-NgKiEN_0Ax6hFX-uiSn:b-fxwpf6) ([raw file](https://github.com/cockroachdb/cockroach/blob/7813cfa094d31255016516e1c612d8d04295ef64/pkg/sql/sqlstats/persistedsqlstats/flush.go#L168)):*
> ```Go
> 	_ = s.SQLStats.IterateStatementStats(ctx, sqlstats.IteratorOptions{},
> 		func(ctx context.Context, statistics *appstatspb.CollectedStatementStatistics) error {
> 			if !skipEventsExporterFlush {
> ```

Should the exporter maybe have a flag `enabled` that can be checked to avoid the type casting?
___
*[`pkg/sql/sqlstats/persistedsqlstats/flush.go` line 170 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111875#-NgKiZy67w3FHOMuwSZh:-NgKiZy67w3FHOMuwSZi:b-6sbh8g) ([raw file](https://github.com/cockroachdb/cockroach/blob/7813cfa094d31255016516e1c612d8d04295ef64/pkg/sql/sqlstats/persistedsqlstats/flush.go#L170)):*
> ```Go
> 			if !skipEventsExporterFlush {
> 				now := s.getTimeNow()
> 				toExport, err := toExportedStmtStats(now, statistics)
> ```

Would it be possible to pre-allocate and possibly cache all the `obspb.StatementStatEvent` to optimize memory?
___
*[`pkg/sql/sqlstats/persistedsqlstats/flush.go` line 174 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111875#-NgKj_1U37VUoB3OBT8M:-NgKj_1U37VUoB3OBT8N:b-cl87xy) ([raw file](https://github.com/cockroachdb/cockroach/blob/7813cfa094d31255016516e1c612d8d04295ef64/pkg/sql/sqlstats/persistedsqlstats/flush.go#L174)):*
> ```Go
> 					log.Errorf(ctx, "marshalling stmt stat: %v", err)
> 				}
> 				s.eventsExporter.SendEvent(ctx, obspb.StatementStatEvent, *toExport)
> ```

Is it better to pass by ref with the size of the obj?
___
*[`pkg/sql/sqlstats/persistedsqlstats/flush.go` line 196 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111875#-NgKl8Qa9x57eIl-bk4w:-NgKl8Qa9x57eIl-bk4x:b4v1ce9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7813cfa094d31255016516e1c612d8d04295ef64/pkg/sql/sqlstats/persistedsqlstats/flush.go#L196)):*
> ```Go
> 		return nil, err
> 	}
> 	return &otel_logs_pb.LogRecord{
> ```

What is the reason needing to export it for otel? Trying to understand why pass down the event exporter and log to otel.

**Review by abarganier — COMMENTED** [review]
thanks for the review @j82w - PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111875#-:-NgQUMC5BvvazmQd-TO7:b-rmzt41)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @knz)

___
*[`-- commits` line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111875#-Ng4UK6KBSgl8xNm0PxB):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: this commit message would be more readable if you could wrap at 70+ columns instead of 55.
</blockquote></details>

Ack, added a vim setting that does this moving forward.
___
*[`pkg/sql/pgwire/server.go` line 319 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111875#-NgKi-3u4X0bHttxjWcB:-NgLGprLEN1LYK0BzMaQ:b-8fexoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7813cfa094d31255016516e1c612d8d04295ef64/pkg/sql/pgwire/server.go#L319)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

should this be a pointer?
</blockquote></details>

In this case, we're saying that the argument is an interface, so we shouldn't use a pointer (pointers to interfaces don't make much sense in Golang, IIUC). 
___
*[`pkg/sql/sqlstats/persistedsqlstats/flush.go` line 163 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111875#-NgKeFkk82omruGT_nRq:-NgQTk0H1KTgFk1wVDVG:btwwnp9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7813cfa094d31255016516e1c612d8d04295ef64/pkg/sql/sqlstats/persistedsqlstats/flush.go#L163)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

I think a cluster setting should be added to be on the safe side.
</blockquote></details>

Done! LMK what you think.
___
*[`pkg/sql/sqlstats/persistedsqlstats/flush.go` line 168 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111875#-NgKiEN_0Ax6hFX-uiSm:-NgQTlX159NXfCM8d7bd:bwbkt6r) ([raw file](https://github.com/cockroachdb/cockroach/blob/7813cfa094d31255016516e1c612d8d04295ef64/pkg/sql/sqlstats/persistedsqlstats/flush.go#L168)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Should the exporter maybe have a flag `enabled` that can be checked to avoid the type casting?
</blockquote></details>

With the cluster setting, we no longer do the casting. The NoopExporter `SendEvent` is a noop anyway.
___
*[`pkg/sql/sqlstats/persistedsqlstats/flush.go` line 170 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111875#-NgKiZy67w3FHOMuwSZh:-NgQTs5F7sbHMCgecY4x:bgiqor0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7813cfa094d31255016516e1c612d8d04295ef64/pkg/sql/sqlstats/persistedsqlstats/flush.go#L170)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Would it be possible to pre-allocate and possibly cache all the `obspb.StatementStatEvent` to optimize memory?
</blockquote></details>

Done. Added a `sync.Pool` for object reuse and changed the transformation function to instead copy over values.
___
*[`pkg/sql/sqlstats/persistedsqlstats/flush.go` line 174 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111875#-NgKj_1U37VUoB3OBT8M:-NgQTx4_8KcpmFyTJq7r:bnct29z) ([raw file](https://github.com/cockroachdb/cockroach/blob/7813cfa094d31255016516e1c612d8d04295ef64/pkg/sql/sqlstats/persistedsqlstats/flush.go#L174)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Is it better to pass by ref with the size of the obj?
</blockquote></details>

Good call! I've been meaning to do this. Added a commit that changes the interface & protos to use pointers instead of values.
___
*[`pkg/sql/sqlstats/persistedsqlstats/flush.go` line 196 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111875#-NgKl8Qa9x57eIl-bk4w:-NgQU0gr21xtnDL4wagh:b-so8fn5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7813cfa094d31255016516e1c612d8d04295ef64/pkg/sql/sqlstats/persistedsqlstats/flush.go#L196)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

What is the reason needing to export it for otel? Trying to understand why pass down the event exporter and log to otel.
</blockquote></details>

We plan to use the OTLP log record format for all exported data, to keep things compatible with the OpenTelemetry Collector. This was a decision made back at a time when our plans were different, but I still see potential value in keeping this around. If the serialization/deserialization becomes an issue someday, I'm open to changing it, but I figure we'll cross that bridge if we come to it.

**Comment by abarganier** [comment]
Closing this as it's no longer relevant to our prototype plans

**Pull request closed without merging**
