### PR TITLE
sql: add missing back-reference in region enum type

### LINKED ISSUE #84144: `REGIONAL BY ROW` data inconsistent after changing node's locality
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

1. I had a few tables which were `REGIONAL BY ROW`.
2. I restarted a few nodes, changing the `--locality=` parameter.
3. Ran `ALTER TABLE {table} SET LOCALITY REGIONAL BY TABLE IN PRIMARY REGION;`
4. The database appeared to be corrupt.
5. See the following error:
```
ERROR: failed to construct index entries during backfill: error decoding 4 bytes: could not find [96] in enum "crdb_internal_region" representation PhysicalReps: [[80]]; LogicalReps: [eu] goroutine 54102 [running]:
runtime/debug.Stack()
        GOROOT/src/runtime/debug/stack.go:24 +0x65
github.com/cockroachdb/cockroach/pkg/sql/types.(*T).EnumGetIdxOfPhysical(0xc00a506780, {0xc00adac593, 0x45dde60, 0xd})
        github.com/cockroachdb/cockroach/pkg/sql/types/pkg/sql/types/types.go:2520 +0x234
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.GetEnumComponentsFromPhysicalRep(0xc00a506780, {0xc00adac593, 0x0, 0xc00282be0e})
        github.com/cockroachdb/cockroach/pkg/sql/sem/tree/datum.go:4529 +0x27
github.com/cockroachdb/cockroach/pkg/sql/rowenc/keyside.Decode(0xc000a00d88, 0xc00a506780, {0xc00adac592, 0xa, 0xa}, 0x0)
        github.com/cockroachdb/cockroach/pkg/sql/rowenc/keyside/decode.go:267 +0x2417
github.com/cockroachdb/cockroach/pkg/sql/rowenc.(*EncDatum).EnsureDecoded(0xc0042fef38, 0x631e378, 0xc002bfd290)
        github.com/cockroachdb/cockroach/pkg/sql/rowenc/encoded_datum.go:251 +0x194
github.com/cockroachdb/cockroach/pkg/sql/row.(*Fetcher).NextRowDecodedInto(0xc0042ff2f0, {0x631e378, 0xc002bfd290}, {0xc00066bb20, 0x7, 0x0}, {{{0x76543210, 0x0}, 0x0}, {0x0, ...}, ...})
        github.com/cockroachdb/cockroach/pkg/sql/row/fetcher.go:1044 +0x1f7
github.com/cockroachdb/cockroach/pkg/sql/backfill.(*IndexBackfiller).BuildIndexEntriesChunk(0xc000a00c80, {0x631e378, 0xc002bfd290}, 0x203001, {0x644a8d8, 0xc000d3cf00}, {{0xc00adac190, 0x6, 0x8}, {0xc00adac198, ...}}, ...)
        github.com/cockroachdb/cockroach/pkg/sql/backfill/backfill.go:856 +0xb1c
github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*indexBackfiller).buildIndexEntryBatch.func1({0x631e378, 0xc002bfd290}, 0xc004b39200)
        github.com/cockroachdb/cockroach/pkg/sql/rowexec/indexbackfiller.go:435 +0xf2
github.com/cockroachdb/cockroach/pkg/kv.runTxn.func1({0x631e378, 0xc002bfd290}, 0xc0042ff678)
        github.com/cockroachdb/cockroach/pkg/kv/db.go:949 +0x27
github.com/cockroachdb/cockroach/pkg/kv.(*Txn).exec(0xc004bfe2c0, {0x631e378, 0xc002bfd290}, 0xc0042ff980)
        github.com/cockroachdb/cockroach/pkg/kv/txn.go:993 +0xae
github.com/cockroachdb/cockroach/pkg/kv.runTxn({0x631e378, 0xc002bfd290}, 0xc0021a8750, 0x9121d9)
        github.com/cockroachdb/cockroach/pkg/kv/db.go:948 +0x5a
github.com/cockroachdb/cockroach/pkg/kv.(*DB).TxnWithAdmissionControl(0x631e378, {0x631e378, 0xc002bfd290}, 0xa, 0x0, 0x48d820)
        github.com/cockroachdb/cockroach/pkg/kv/db.go:911 +0x89
github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn(...)
        github.com/cockroachdb/cockroach/pkg/kv/db.go:890
github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*indexBackfiller).buildIndexEntryBatch(0xc000a00c80, {0x631e378, 0xc004b39200}, {{0xc00adac190, 0x6, 0x8}, {0xc00adac198, 0x2, 0x8}}, {0x17003d6871733671, ...})
        github.com/cockroachdb/cockroach/pkg/sql/rowexec/indexbackfiller.go:428 +0x2fc
github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*indexBackfiller).constructIndexEntries(0xc000a00c80, {0x631e378, 0xc004b39200}, 0xc0119bea20)
        github.com/cockroachdb/cockroach/pkg/sql/rowexec/indexbackfiller.go:134 +0x305
github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*indexBackfiller).runBackfill.func1({0x631e2d0, 0xc00bd5ae80})
        github.com/cockroachdb/cockroach/pkg/sql/rowexec/indexbackfiller.go:319 +0xcb
github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx.func1()
        github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:169 +0x25
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:54 +0x92
```

**Expected behavior**
The database to work as expected.

**Additional data / screenshots**
I can provide any information requested.

**Environment:**
 - CockroachDB version: 22.1
 - Server OS: Linux

**Additional context**
The database's data was inconsistent, backups didn't work, any `REGIONAL BY ROW` table was affected.

Jira issue: CRDB-17489

### PR DESCRIPTION
**Pull request by postamar**
This commit fixes a long-standing bug in which making an existing
multi-region table REGIONAL BY ROW would omit adding a back-reference to
the table in the region enum type. This puts the table at risk for
corruption in the face of schema changes to the region enum, which is
unaware of this dependency.

Fixes #84144.

Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84305#-:-N6oAKdPBWl6dB9zEs8P:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by postamar** [comment]
Thanks for the review!

bors r+

**Comment by rafiss** [comment]
would we want a release note on this?

**Comment by ajwerner** [comment]
We'll certainly want them on the backports. I think there will also be a TA

**Pull request merged**
