### PR TITLE
storageccl: improve UX of AWS secrets with + chars

### PR DESCRIPTION
**Pull request by benesch**
`+` characters are not URL safe, but users often include them unescaped in
export storage URIs when providing AWS secret keys. This previously
would cause BACKUP and RESTORE to fail with cryptic "signature does
not match" errors.

Because an AWS secret will never contain a space, in this specific case
we can undo the effects of the URI encoding to recover the original
secret.

Release note (enterprise change): BACKUP and RESTORE are more resilient
to non-URL-safe characters in query string authentication parameters.

### CODE REVIEW

**Review by dt — APPROVED** [review]

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24300#-:-L8juDBq5mSxH1Ak0S2V:bnfp4nl)*

**Review by madelynnblue — APPROVED** [review]

**Comment by dianasaur323** [comment]
:lgtm: thank you! @jseldess - we might want to revisit how we tell people to manage encoding / decoding secrets in docs.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24300#-:-L92m9sv8riHoDlv0bY-:b-28pe7r)*

**Review by dianasaur323 — APPROVED** [review]

**Comment by benesch** [comment]
Ok, I verified that this works with my `+`-laden AWS creds.

bors r=dt,bdarnell,dianasaur323

**Comment by benesch** [comment]
bors r=dt,bdarnell,dianasaur323

**Pull request merged**
