### PR TITLE
sql: Adding DROP USER command

### PR DESCRIPTION
**Pull request by mpoornima**
* Takes in a list of usernames and deletes them (all or none) 
* User needs to have `DELETE` privileges on `system.users`
* Drops the `username` entry from `system.users` table
* Currently the permissions given to the user are left intact as is the case with the cli `user rm` command

Notes to reviewers:
* I've only added logical sql tests for the functionality as I've felt unit tests will be just duplicating the same logic.
* The drop of an user being an SQL `DELETE` statement, happens in the current existing transaction. I wasn't sure how to change this behaviour to start a new transaction for each `DELETE` so that each drop of user can be independent of the other (as is the case with mysql). Do let me know if this functionality is required.

### CODE REVIEW

**Comment by benesch** [comment]
This is an awesome first PR, @mpoornima! Thanks so much!

Someone else (perhaps @knz?) will be along shortly to give you a full review, but here's some style feedback for now!

---

Review status: 0 of 13 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/sql/drop.go, line 1117 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmNAC_n9yKvHvrlqp9y:-KmNAC_n9yKvHvrlqp9z:budp85l) ([raw file](https://github.com/cockroachdb/cockroach/blob/090ab8d9acafd768594c3183bda3fa8e954423bd/pkg/sql/drop.go#L1117)):*
> ```Go
> 
> // All the deletes happen in single transaction
> //   notes: Should we run each drop user in an individual transaction, returning errors concatenated like in mysql?
> ```

No, I think the way you've implemented it is better. It's also consistent with Postgres's convention.

---

*[pkg/sql/drop.go, line 1127 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmNBB-yx_v_4k_LDFrD:-KmNBB-yx_v_4k_LDFrE:bbkbkm7) ([raw file](https://github.com/cockroachdb/cockroach/blob/090ab8d9acafd768594c3183bda3fa8e954423bd/pkg/sql/drop.go#L1127)):*
> ```Go
> 		// Disable deleting root user
> 		if normalizedUsername == security.RootUser {
> 			return errors.Errorf("username %q cannot be deleted", security.RootUser)
> ```

We probably should use `%q`, but we use `%s` when printing similar messages in `CREATE USER`, and you use `%s` in an error message below, so I'd make this one `%s` too for consistency.

Actually, on second thought, this entire check is probably unnecessary. For better or worse, the `root` user isn't included in `system.users`. Perhaps leave a comment like "protected users, like security.RootUser, aren't included in the `system.users` table, so there's no need to filter them out."

---

*[pkg/sql/drop.go, line 1132 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmNBjZ8nmTTj1tSchU1:-KmNBjZ8nmTTj1tSchU2:b5t0loq) ([raw file](https://github.com/cockroachdb/cockroach/blob/090ab8d9acafd768594c3183bda3fa8e954423bd/pkg/sql/drop.go#L1132)):*
> ```Go
> 		// TODO: Remove the privileges granted to the user
> 		//   notes: The current remove user from CLI just deletes the entry from system.users,
> 		//          keeping the functionality same for now
> ```

Yikes. That's not ideal. But given that this is consistent with the CLI, probably fine to start!

---

*[pkg/sql/drop.go, line 1140 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmNEQsfwk-Ev2y7ZQWd:-KmNEQsfwk-Ev2y7ZQWe:bkw6pwb) ([raw file](https://github.com/cockroachdb/cockroach/blob/090ab8d9acafd768594c3183bda3fa8e954423bd/pkg/sql/drop.go#L1140)):*
> ```Go
> 			"DELETE FROM system.users WHERE username=$1",
> 			normalizedUsername,
> 		)
> ```

It's unfortunate that we need to execute one statement per user, but probably fine in practice.

---

*[pkg/sql/drop.go, line 1147 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmNBTk1yVA_-BOhC9Ye:-KmNBTk2Wx1O5NOgpWKG:b5s7i86) ([raw file](https://github.com/cockroachdb/cockroach/blob/090ab8d9acafd768594c3183bda3fa8e954423bd/pkg/sql/drop.go#L1147)):*
> ```Go
> 
> 		if rowsAffected == 0 {
> 			if !n.n.IfExists {
> ```

`if rowsAffected == 0 && !n.n.IfExists {`

---

*[pkg/sql/parser/sql.y, line 1187 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmNAkg_uFOHFL0rO-Ec:-KmNAkg_uFOHFL0rO-Ed:bb7cazf) ([raw file](https://github.com/cockroachdb/cockroach/blob/090ab8d9acafd768594c3183bda3fa8e954423bd/pkg/sql/parser/sql.y#L1187)):*
> ```Yacc
>   {
>     $$.val = append($1.nameList(), Name($3))
>   }
> ```

You can just reuse `name_list` here instead of introducing a new production.

---

*[pkg/sql/testdata/logic_test/drop_user, line 116 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmNApcAix2Kjz9N6B5z:-KmNApcAix2Kjz9N6B6-:b3qjjmo) ([raw file](https://github.com/cockroachdb/cockroach/blob/090ab8d9acafd768594c3183bda3fa8e954423bd/pkg/sql/testdata/logic_test/drop_user#L116)):*
> ```
> 
> statement error pq: user testuser does not have DELETE privilege on table users
> DROP USER user2
> ```

Mind throwing a trailing new line on this file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-:-KmNEWm4HQ0m-Js349fu:bwztlkp)*

**Comment by mpoornima** [comment]
Review status: 0 of 13 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/sql/drop.go, line 1117 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmNAC_n9yKvHvrlqp9y:-KmQ8C_zYHNR2h6feSs5:bxonkht) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e4830061f904443a24deb333ad7801716e1cbda/pkg/sql/drop.go#L1117)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

No, I think the way you've implemented it is better. It's also consistent with Postgres's convention.
</blockquote></details>

Cool. Removing this comment then!!

---

*[pkg/sql/drop.go, line 1127 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmNBB-yx_v_4k_LDFrD:-KmQ8XdrrVQQLuGfRi1V:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e4830061f904443a24deb333ad7801716e1cbda/pkg/sql/drop.go#L1127)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

We probably should use `%q`, but we use `%s` when printing similar messages in `CREATE USER`, and you use `%s` in an error message below, so I'd make this one `%s` too for consistency.

Actually, on second thought, this entire check is probably unnecessary. For better or worse, the `root` user isn't included in `system.users`. Perhaps leave a comment like "protected users, like security.RootUser, aren't included in the `system.users` table, so there's no need to filter them out."
</blockquote></details>

Done.

---

*[pkg/sql/drop.go, line 1132 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmNBjZ8nmTTj1tSchU1:-KmQ8bFqIanlLrrN4Iyj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e4830061f904443a24deb333ad7801716e1cbda/pkg/sql/drop.go#L1132)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Yikes. That's not ideal. But given that this is consistent with the CLI, probably fine to start!
</blockquote></details>

Done.

---

*[pkg/sql/drop.go, line 1140 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmNEQsfwk-Ev2y7ZQWd:-KmQ8c_19W7Gr5uf8GTh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e4830061f904443a24deb333ad7801716e1cbda/pkg/sql/drop.go#L1140)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

It's unfortunate that we need to execute one statement per user, but probably fine in practice.
</blockquote></details>

Done.

---

*[pkg/sql/drop.go, line 1147 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmNBTk1yVA_-BOhC9Ye:-KmQ8dxpI91EJuYrSpAv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e4830061f904443a24deb333ad7801716e1cbda/pkg/sql/drop.go#L1147)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

`if rowsAffected == 0 && !n.n.IfExists {`
</blockquote></details>

Done.

---

*[pkg/sql/parser/sql.y, line 1187 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmNAkg_uFOHFL0rO-Ec:-KmQaS37qla-Io5xVJv8:b-svqtie) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e4830061f904443a24deb333ad7801716e1cbda/pkg/sql/parser/sql.y#L1187)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

You can just reuse `name_list` here instead of introducing a new production.
</blockquote></details>

Done. Thanks for pointing this out. :smiley: 

---

*[pkg/sql/testdata/logic_test/drop_user, line 116 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmNApcAix2Kjz9N6B5z:-KmQAHZy7Xikxcg0Ihm2:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e4830061f904443a24deb333ad7801716e1cbda/pkg/sql/testdata/logic_test/drop_user#L116)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Mind throwing a trailing new line on this file?
</blockquote></details>

Done. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442)*

**Comment by knz** [comment]
Very good work indeed.

I would kindly request the statement to have StatementType `RowsAffected` and make the planNode implement the `planNodeFastPath` interface and have its `FastPathResults` method return the number of users that were deleted. This will allow the client to check how many users have been ignored by the IF NOT EXISTS clause.

---

Reviewed 12 of 13 files at r1, 3 of 6 files at r2.
Review status: 11 of 14 files reviewed at latest revision, 13 unresolved discussions, all commit checks successful.

---

*[pkg/sql/drop.go, line 1122 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmQf06FwbVuHbI9j-ZG:-KmQf06FwbVuHbI9j-ZH:b1esn4y) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2d238f17c3737fac44192e5045f01fd3578a65/pkg/sql/drop.go#L1122)):*
> ```Go
> 		}
> 
> 		//  notes: protected users like security.RootUser are not included in system.users,
> ```

"Note" with capital, also no "s" because there is just one note here.

---

*[pkg/sql/drop.go, line 1123 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmQf8m7ZNwE70Sz8t-t:-KmQf8m7ZNwE70Sz8t-u:bo5tzog) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2d238f17c3737fac44192e5045f01fd3578a65/pkg/sql/drop.go#L1123)):*
> ```Go
> 
> 		//  notes: protected users like security.RootUser are not included in system.users,
> 		//    so there is no need to filter them out
> ```

Period missing at end of sentence.

---

*[pkg/sql/drop.go, line 1125 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmQfAXVjn_awFkRdvZ0:-KmQfAXVjn_awFkRdvZ1:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2d238f17c3737fac44192e5045f01fd3578a65/pkg/sql/drop.go#L1125)):*
> ```Go
> 		//    so there is no need to filter them out
> 
> 		// TODO: Remove the privileges granted to the user
> ```

ditto

---

*[pkg/sql/drop.go, line 1127 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmQfBIUaLvc_n6liAR9:-KmQfBIUaLvc_n6liARA:b-o7rxhu) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2d238f17c3737fac44192e5045f01fd3578a65/pkg/sql/drop.go#L1127)):*
> ```Go
> 		// TODO: Remove the privileges granted to the user
> 		//   notes: The current remove user from CLI just deletes the entry from system.users,
> 		//          keeping the functionality same for now
> ```

ditto, also "Note"

---

*[pkg/sql/drop.go, line 1137 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmQgNrfPa7QLOxxLm0z:-KmQgNrfPa7QLOxxLm1-:bj44xba) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2d238f17c3737fac44192e5045f01fd3578a65/pkg/sql/drop.go#L1137)):*
> ```Go
> 		)
> 
> 		if err != nil {
> ```

Remove the empty line before this line.

---

*[pkg/sql/parser/sql_union.sh, line 2 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmQeF_JqyNmOA08988q:-KmQeF_KYXCSjZdnai7Q:b-dj5tye) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2d238f17c3737fac44192e5045f01fd3578a65/pkg/sql/parser/sql_union.sh#L2)):*
> ```Shell
> #!/usr/bin/env bash
> set +x
> ```

Please submit a different PR for this change

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-:-KmQffu_2gb75I194cTY:b-gz2dgw)*

**Comment by mpoornima** [comment]
Done. 

---

Review status: 7 of 13 files reviewed at latest revision, 13 unresolved discussions.

---

*[pkg/sql/drop.go, line 1122 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmQf06FwbVuHbI9j-ZG:-KmRJtQwItEkqiEazvqQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2d238f17c3737fac44192e5045f01fd3578a65/pkg/sql/drop.go#L1122)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

"Note" with capital, also no "s" because there is just one note here.
</blockquote></details>

Done.

---

*[pkg/sql/drop.go, line 1123 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmQf8m7ZNwE70Sz8t-t:-KmRJrnfOTvSIUT3MohM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2d238f17c3737fac44192e5045f01fd3578a65/pkg/sql/drop.go#L1123)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Period missing at end of sentence.
</blockquote></details>

Done.

---

*[pkg/sql/drop.go, line 1125 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmQfAXVjn_awFkRdvZ0:-KmRJq7SMH0HY1WBifyW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2d238f17c3737fac44192e5045f01fd3578a65/pkg/sql/drop.go#L1125)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

---

*[pkg/sql/drop.go, line 1127 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmQfBIUaLvc_n6liAR9:-KmRJpOHd2aycrG35yju:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2d238f17c3737fac44192e5045f01fd3578a65/pkg/sql/drop.go#L1127)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto, also "Note"
</blockquote></details>

Done.

---

*[pkg/sql/drop.go, line 1137 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmQgNrfPa7QLOxxLm0z:-KmRJnv1LTHmUJreW_Sg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2d238f17c3737fac44192e5045f01fd3578a65/pkg/sql/drop.go#L1137)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Remove the empty line before this line.
</blockquote></details>

Done.

---

*[pkg/sql/parser/sql_union.sh, line 2 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmQeF_JqyNmOA08988q:-KmRJbEM4WhvBNyu1kJE:b-lymjk6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2d238f17c3737fac44192e5045f01fd3578a65/pkg/sql/parser/sql_union.sh#L2)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please submit a different PR for this change
</blockquote></details>

This was committed by mistake. Apologies.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-:-KmRQpC7_L79r7Ve5pFY:bs7wumx)*

**Comment by knz** [comment]
Very nice! Just cosmetic issues remaining.

---

Reviewed 3 of 6 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks pending.

---

*[pkg/sql/drop.go, line 1122 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmQf06FwbVuHbI9j-ZG:-KmRW5bAeHmMstS5Rtk2:b-rge7if) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2d238f17c3737fac44192e5045f01fd3578a65/pkg/sql/drop.go#L1122)):*
<details><summary><i>Previously, mpoornima (Poornima) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks, please also trim the space on the left.

---

*[pkg/sql/drop.go, line 1127 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmQfBIUaLvc_n6liAR9:-KmRWChNlYWuJ74hAL17:bjj7z9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2d238f17c3737fac44192e5045f01fd3578a65/pkg/sql/drop.go#L1127)):*
<details><summary><i>Previously, mpoornima (Poornima) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks, please also trim spaces on the left.

---

*[pkg/sql/drop.go, line 1113 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmRW0rbrUD1Qojfi08S:-KmRW0rbrUD1Qojfi08T:b-d7ko2o) ([raw file](https://github.com/cockroachdb/cockroach/blob/0454a8dcd4094c042f3812e7bc5ed9a888c08ad2/pkg/sql/drop.go#L1113)):*
> ```Go
> 	p          *planner
> 	n          *parser.DropUser
> 	numDeleted int // The number of users deleted
> ```

Place the comment above the member variable. Also, add a period.

---

*[pkg/sql/testdata/logic_test/drop_user, line 50 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmRWMufJAko2g3SJY_-:-KmRWMufJAko2g3SJY_0:b-u1rt0r) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e4830061f904443a24deb333ad7801716e1cbda/pkg/sql/testdata/logic_test/drop_user#L50)):*
> ```
> DROP USER IF EXISTS user1
> 
> statement error username "root" cannot be deleted
> ```

Out of curiosity, why did you remove this test? It seems useful to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-:-KmRWVfvaedw4taeIwZK:bsrlpb4)*

**Comment by mpoornima** [comment]
Review status: 12 of 13 files reviewed at latest revision, 11 unresolved discussions.

---

*[pkg/sql/drop.go, line 1122 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmQf06FwbVuHbI9j-ZG:-KmR_Fep-pPkJ-FDfkeu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2d238f17c3737fac44192e5045f01fd3578a65/pkg/sql/drop.go#L1122)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Thanks, please also trim the space on the left.
</blockquote></details>

Done.

---

*[pkg/sql/drop.go, line 1127 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmQfBIUaLvc_n6liAR9:-KmR_DzdcwrsBlQ6gAFB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2d238f17c3737fac44192e5045f01fd3578a65/pkg/sql/drop.go#L1127)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Thanks, please also trim spaces on the left.
</blockquote></details>

Done.

---

*[pkg/sql/drop.go, line 1113 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmRW0rbrUD1Qojfi08S:-KmR_HppIeFp59xQfBZF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0454a8dcd4094c042f3812e7bc5ed9a888c08ad2/pkg/sql/drop.go#L1113)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Place the comment above the member variable. Also, add a period.
</blockquote></details>

Done.

---

*[pkg/sql/testdata/logic_test/drop_user, line 50 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmRWMufJAko2g3SJY_-:-KmRY0NUMlz_RqjW17SQ:b6e6drq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e4830061f904443a24deb333ad7801716e1cbda/pkg/sql/testdata/logic_test/drop_user#L50)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Out of curiosity, why did you remove this test? It seems useful to me.
</blockquote></details>

That test was to validate that we are not allowing the user to delete the `root` user. But as @benesch pointed out, `root` user is not part of the `system.users` table. The statement would now error out saying "user root does not exist". I suppose I can add a test validating that behaviour. Let me know if that is okay with you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442)*

**Comment by knz** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/sql/testdata/logic_test/drop_user, line 50 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-KmRWMufJAko2g3SJY_-:-KmRbR5r2JzUbFiN7swE:bb6mt9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e4830061f904443a24deb333ad7801716e1cbda/pkg/sql/testdata/logic_test/drop_user#L50)):*
<details><summary><i>Previously, mpoornima (Poornima) wrote…</i></summary><blockquote>

That test was to validate that we are not allowing the user to delete the `root` user. But as @benesch pointed out, `root` user is not part of the `system.users` table. The statement would now error out saying "user root does not exist". I suppose I can add a test validating that behaviour. Let me know if that is okay with you.
</blockquote></details>

:+1:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442)*

**Comment by knz** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16442#-:-KmRbW4AxhHD-_Zt_bDX:bnfp4nl)*

**Comment by knz** [comment]
Thank you enormously for your contribution!

**Pull request merged**
