### PR TITLE
kvclient: fiddle with assertions and rollbacks

### PR DESCRIPTION
**Pull request by andreimatei**
See individual commits.

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 10 of 10 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48297#-:-M6T7ctY87sZ-ZxS9Vox:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @irfansharif, and @tbg)

___
*[pkg/kv/txn_external_test.go, line 117 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/48297#-M6T1szT4mfhesfgc4Dn:-M6T1szT4mfhesfgc4Do:b3ybv36) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a1057448c456c608d02ab5d110fa15bc7a5c2db/pkg/kv/txn_external_test.go#L117)):*
> ```Go
> 			atomic.StoreInt64(&filterSet, 1)
> 
> 			// This test uses a cluster with two nodes. It'll create a transaction
> ```

Is this going to be flaky if the lease moves around?
___
*[pkg/kv/txn_external_test.go, line 137 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/48297#-M6T2J152zO98n6lz414:-M6T2J152zO98n6lz415:bz2f6fq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a1057448c456c608d02ab5d110fa15bc7a5c2db/pkg/kv/txn_external_test.go#L137)):*
> ```Go
> 			require.NoError(t, txn.Put(ctx, key, "val"))
> 
> 			// If the test we want the transaction to be committed and cleaned up,
> ```

"If the test we want" sounds wrong.
___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 806 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/48297#-M6T7WWJ7EZazAsCYWal:-M6T7WWJ7EZazAsCYWam:b-v59gin) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a1057448c456c608d02ab5d110fa15bc7a5c2db/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L806)):*
> ```Go
> }
> 
> func sanityCheckCommittedErr(ctx context.Context, pErr *roachpb.Error, ba roachpb.BatchRequest) {
> ```

Give this a comment indicating what it's sanity checking.

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48297#-:-M6Vzwyx3v2YM9aM24IR:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @irfansharif, @nvanbenschoten, and @tbg)

___
*[pkg/kv/txn_external_test.go, line 117 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/48297#-M6T1szT4mfhesfgc4Dn:-M6VjNSD7MCCIJEwpO2L:bgtjvlj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a1057448c456c608d02ab5d110fa15bc7a5c2db/pkg/kv/txn_external_test.go#L117)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this going to be flaky if the lease moves around?
</blockquote></details>

well yeah, but why would the lease move? It'd better not move; we have plenty of tests like this.
___
*[pkg/kv/txn_external_test.go, line 137 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/48297#-M6T2J152zO98n6lz414:-M6VlB0TArxan73yPclB:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a1057448c456c608d02ab5d110fa15bc7a5c2db/pkg/kv/txn_external_test.go#L137)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"If the test we want" sounds wrong.
</blockquote></details>

done
___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 806 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/48297#-M6T7WWJ7EZazAsCYWal:-M6VlyjQ5xpt7g77hi47:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a1057448c456c608d02ab5d110fa15bc7a5c2db/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L806)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Give this a comment indicating what it's sanity checking.
</blockquote></details>

done

**Review by irfansharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48297)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 802 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48297#-M6WJRpm5fPuPkl_LpCP:-M6WJRpm5fPuPkl_LpCQ:b-q9lvpr) ([raw file](https://github.com/cockroachdb/cockroach/blob/26a9a4c72b5193d433f52da80e2ef9ff218b0a68/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L802)):*
> ```Go
> 			// bug. Requests are not supposed to be sent on transactions after they
> 			// are committed.
> 			log.Errorf(ctx, "transaction unexpectedly committed: %s. ba: %s. txn: %s.", pErr, ba, errTxn)
> ```

Sorry for not getting to it earlier, so feel free to ignore this (doubly so because it's nothing to do with this diff): I'm surprised this isn't a log.Fatal given it's a "serious bug".

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48297)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @irfansharif, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 802 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48297#-M6WJRpm5fPuPkl_LpCP:-M6WKLnbDU4JnviVLrmT:b-k3y9zj) ([raw file](https://github.com/cockroachdb/cockroach/blob/26a9a4c72b5193d433f52da80e2ef9ff218b0a68/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L802)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Sorry for not getting to it earlier, so feel free to ignore this (doubly so because it's nothing to do with this diff): I'm surprised this isn't a log.Fatal given it's a "serious bug".
</blockquote></details>

see what's going in later commits

**Pull request merged**
