### PR TITLE
roachtest: fix infrastructure flake on cdc/bank

### LINKED ISSUE #86979: roachtest: cdc/bank failed
roachtest.cdc/bank [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6260325?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6260325?buildTab=artifacts#/cdc/bank) on master @ [770ff3c545a51752490403da64d56fb397f49c5e](https://github.com/cockroachdb/cockroach/commits/770ff3c545a51752490403da64d56fb397f49c5e):

```
test artifacts and logs in: /artifacts/cdc/bank/run_1
	cdc.go:320,cdc.go:891,test_runner.go:897: admin client: kafka: controller is not available
		(1) attached stack trace
		  -- stack trace:
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.kafkaManager.createTopic
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cdc.go:1542
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.runCDCBank
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cdc.go:319
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerCDC.func12
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cdc.go:891
		  | main.(*testRunner).runTest.func2
		  | 	main/pkg/cmd/roachtest/test_runner.go:897
		  | runtime.goexit
		  | 	GOROOT/src/runtime/asm_amd64.s:1571
		Wraps: (2) admin client
		Wraps: (3) kafka: controller is not available
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *errors.errorString

	cluster.go:1940,cdc.go:1466,cdc.go:1898,panic.go:838,test_impl.go:259,cdc.go:320,cdc.go:891,test_runner.go:897: cluster.RunE: context canceled
		(1) attached stack trace
		  -- stack trace:
		  | main.(*clusterImpl).RunE
		  | 	main/pkg/cmd/roachtest/cluster.go:1957
		  | main.(*clusterImpl).Run
		  | 	main/pkg/cmd/roachtest/cluster.go:1938
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.kafkaManager.stop
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cdc.go:1466
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.setupKafka.func1
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cdc.go:1898
		  | runtime.gopanic
		  | 	GOROOT/src/runtime/panic.go:838
		  | main.(*testImpl).Fatal
		  | 	main/pkg/cmd/roachtest/test_impl.go:259
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.runCDCBank
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cdc.go:320
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerCDC.func12
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cdc.go:891
		  | main.(*testRunner).runTest.func2
		  | 	main/pkg/cmd/roachtest/test_runner.go:897
		  | runtime.goexit
		  | 	GOROOT/src/runtime/asm_amd64.s:1571
		Wraps: (2) cluster.RunE
		Wraps: (3) context canceled
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *errors.errorString
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #70386 roachtest: cdc/bank failed [C-test-failure O-roachtest O-robot T-cdc branch-release-21.2]
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/bank.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-19065

### LINKED ISSUE #86987: roachtest: tpccbench/nodes=12/cpu=16 failed
roachtest.tpccbench/nodes=12/cpu=16 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyBazel/6260294?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyBazel/6260294?buildTab=artifacts#/tpccbench/nodes=12/cpu=16) on master @ [770ff3c545a51752490403da64d56fb397f49c5e](https://github.com/cockroachdb/cockroach/commits/770ff3c545a51752490403da64d56fb397f49c5e):

```
test artifacts and logs in: /artifacts/bazel-20220827-6260294/tpccbench/nodes=12/cpu=16/run_1
	monitor.go:127,tpcc.go:1111,tpcc.go:948,test_runner.go:897: monitor failure: monitor task failed: Non-zero exit code: 1
		(1) attached stack trace
		  -- stack trace:
		  | main.(*monitorImpl).WaitE
		  | 	main/pkg/cmd/roachtest/monitor.go:115
		  | main.(*monitorImpl).Wait
		  | 	main/pkg/cmd/roachtest/monitor.go:123
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.runTPCCBench
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/tpcc.go:1111
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerTPCCBenchSpec.func1
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/tpcc.go:948
		  | [...repeated from below...]
		Wraps: (2) monitor failure
		Wraps: (3) attached stack trace
		  -- stack trace:
		  | main.(*monitorImpl).wait.func2
		  | 	main/pkg/cmd/roachtest/monitor.go:171
		  | runtime.goexit
		  | 	GOROOT/src/runtime/asm_amd64.s:1571
		Wraps: (4) monitor task failed
		Wraps: (5) Non-zero exit code: 1
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *install.NonZeroExitCode
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=16</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*tpccbench/nodes=12/cpu=16.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-19072

### PR DESCRIPTION
**Pull request by renatolabs**
When trying to create a Kafka topic immediately after setting it up on
a node, we sometimes see the `kafka controller not available`
error. Retrying the topic creation is sufficient to make progress on
the test.

This was supposed to be included in #86468, but was missed. Now the
retry logic lives in the `createTopic` function itself, so callers no
longer have to remember to wrap this function in a retry loop.

Fixes #86979.

Release justification: test-only change.
Release note: None.

### CODE REVIEW

**Review by srosenberg — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87025#-:-NAf6keo4aerPBhMy-4Z:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @renatolabs and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1546 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87025#-NAf6vX70P7KYHlXblgX:-NAf6vX70P7KYHlXblgY:b-ye6e8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/0553c29d128a2b11aeb2e1586be0830bc6774884/pkg/cmd/roachtest/tests/cdc.go#L1546)):*
> ```Go
> 	kafkaAddrs := []string{k.consumerURL(ctx)}
> 	config := sarama.NewConfig()
> 	return retry.ForDuration(kafkaCreateTopicRetryDuration, func() error {
> ```

Thanks for refactoring!

**Comment by renatolabs** [comment]
bors=srosenberg

TFTR!

**Comment by renatolabs** [comment]
bors r=srosenberg

TFTR!

**Comment by renatolabs** [comment]
bors r=srosenberg

**Pull request merged**
