### PR TITLE
sql: display limit hint for EXPLAIN when limit hint is nonzero

### LINKED ISSUE #69564: sql: display limit hint in EXPLAIN output for scans
The `EXPLAIN` output for a scan currently includes the estimated row count but not the limit hint. This can lead to confusion, as highlighted by #67971. In the example in that issue, it looks like the optimizer's row count estimate for one of the scans is extremely inaccurate:
```
            actual row count: 1,024
            ...
            estimated row count: 1,000,000 (100% of the table; stats collected 3 minutes ago)

```
However, this misses that fact that we actually use a limit hint, both when estimating the cost of the scan in the optimizer, and when executing the scan to avoid reading too many rows. To avoid this source of confusion, any time the limit hint is non-zero, it should be displayed along with the estimated row count (or perhaps instead of the estimated row count).

### PR DESCRIPTION
**Pull request by Azhng**
Previously, the EXPLAIN output only included the estimated
row count but not the limit hint. This could lead to confusions
when the actual output row count is significantly less than the
estimated row count due to the limit hint.
This commit displays the limit hint for EXPLAIN output as
part of the 'estimated row count' field when the limit hint
is greater than zero.

Example output:

```
estimated row count: 100 - 1,001 (100% of the table; sta....
```

Resolves #69564

Release note (sql change): EXPLAIN output now displays limit hint
when limit hint is nonzero as part of the 'estimated row count' field.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71299)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71299#-MlS4YYN76PdNfwU5uPI):*
nit: "previously ... currently includes" -> maybe "Previously, the EXPLAIN output only included..."? Then "can lead" -> "could lead" in the next sentence.
___
*[pkg/sql/opt/exec/factory.go, line 309 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71299#-MlS4wYCB1YJkhjbHalf:-MlS4wYCB1YJkhjbHalg:b3mptpb) ([raw file](https://github.com/cockroachdb/cockroach/blob/0be4d86f107a28f8b7c608198e1ce6d87ed71ba8/pkg/sql/opt/exec/factory.go#L309)):*
> ```Go
> 
> 	// LimitHint is the "soft limit" of the number of result rows that may be
> 	// required. See physical.Required pkg/sql/opt/props/physical/required.go for
> ```

nit: we usually don't specify the code path, so mentioning only `physical.Required` should be sufficient.
___
*[pkg/sql/opt/exec/explain/emit.go, line 442 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71299#-MlS5BGw6IwotZwxB_XR:-MlS5BGw6IwotZwxB_XS:b-fn2xzx) ([raw file](https://github.com/cockroachdb/cockroach/blob/0be4d86f107a28f8b7c608198e1ce6d87ed71ba8/pkg/sql/opt/exec/explain/emit.go#L442)):*
> ```Go
> 			}
> 		}
> 		if s.LimitHint > 0.0 {
> ```

super nit: no need for `0.0`, `0` should work for floats.
___
*[pkg/sql/opt/exec/explain/emit.go, line 443 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71299#-MlS5HgOEzXGrLIc3dnc:-MlS5HgOEzXGrLIc3dnd:bf2itg7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0be4d86f107a28f8b7c608198e1ce6d87ed71ba8/pkg/sql/opt/exec/explain/emit.go#L443)):*
> ```Go
> 		}
> 		if s.LimitHint > 0.0 {
> 			e.ob.AddField("limit hint", humanizeutil.Count(uint64(math.Round(s.LimitHint))))
> ```

Maybe use `math.Ceil` instead of `Round` (since `Required.LimitHint` mentions that)?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71299)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @yuzefovich)

___
*[pkg/sql/opt/exec/execbuilder/testdata/limit, line 457 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71299#-MlSTtMD48Cr1JnM6UgR:-MlSTtMD48Cr1JnM6UgS:bfu9t98) ([raw file](https://github.com/cockroachdb/cockroach/blob/0be4d86f107a28f8b7c608198e1ce6d87ed71ba8/pkg/sql/opt/exec/execbuilder/testdata/limit#L457)):*
> ```
>     │   │   │   └── • scan
>     │   │   │         estimated row count: 5 (0.05% of the table; stats collected <hidden> ago)
>     │   │   │         limit hint: 5
> ```

We should hide it when it's the same with the row count (or when it's larger, if that's possible)
___
*[pkg/sql/opt/exec/explain/emit.go, line 443 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71299#-MlS5HgOEzXGrLIc3dnc:-MlSTS-S7l1XrUPUfSfA:b-cixs4m) ([raw file](https://github.com/cockroachdb/cockroach/blob/0be4d86f107a28f8b7c608198e1ce6d87ed71ba8/pkg/sql/opt/exec/explain/emit.go#L443)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Maybe use `math.Ceil` instead of `Round` (since `Required.LimitHint` mentions that)?
</blockquote></details>

I think "limit hint" is not very self-explanatory to a user (which is the target audience for the vanilla EXPLAIN). Wondering if there is a better way of showing it. Maybe as a range like `estimated row count: 1 - 100`.

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71299)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @yuzefovich)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71299#-MlS4YYN76PdNfwU5uPI):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: "previously ... currently includes" -> maybe "Previously, the EXPLAIN output only included..."? Then "can lead" -> "could lead" in the next sentence.
</blockquote></details>

Done
___
*[pkg/sql/opt/exec/factory.go, line 309 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71299#-MlS4wYCB1YJkhjbHalf:-MlrX1ZFCS78n7H-zzQq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0be4d86f107a28f8b7c608198e1ce6d87ed71ba8/pkg/sql/opt/exec/factory.go#L309)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: we usually don't specify the code path, so mentioning only `physical.Required` should be sufficient.
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/testdata/limit, line 457 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71299#-MlSTtMD48Cr1JnM6UgR:-MlrXUgj1SluOj8xS3qJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0be4d86f107a28f8b7c608198e1ce6d87ed71ba8/pkg/sql/opt/exec/execbuilder/testdata/limit#L457)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We should hide it when it's the same with the row count (or when it's larger, if that's possible)
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/testdata/limit, line 497 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71299#-MlrXYbJ1SaOtXQAgbz6:-MlrXYbJ1SaOtXQAgbz7:b9rsyr3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ebdb8b779762e5af34add903e85b8ef56f723cb/pkg/sql/opt/exec/execbuilder/testdata/limit#L497)):*
> ```
> 
> statement ok
> CREATE TABLE a AS (SELECT i, i AS j FROM generate_series(0, 1000) AS gen(i));
> ```

This test case uses the example lifted from [this issue](https://github.com/cockroachdb/cockroach/issues/67971)
___
*[pkg/sql/opt/exec/explain/emit.go, line 442 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71299#-MlS5BGw6IwotZwxB_XR:-MlrXeTi7jMHYqqjlP7q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0be4d86f107a28f8b7c608198e1ce6d87ed71ba8/pkg/sql/opt/exec/explain/emit.go#L442)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

super nit: no need for `0.0`, `0` should work for floats.
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/explain/emit.go, line 443 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71299#-MlS5HgOEzXGrLIc3dnc:-MlrXfkv5Kpl2lEPLOyl:b-qkajn9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0be4d86f107a28f8b7c608198e1ce6d87ed71ba8/pkg/sql/opt/exec/explain/emit.go#L443)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I think "limit hint" is not very self-explanatory to a user (which is the target audience for the vanilla EXPLAIN). Wondering if there is a better way of showing it. Maybe as a range like `estimated row count: 1 - 100`.
</blockquote></details>

Done. Updated the output to show a range when `limit hint` is nonzero and different from the estimated row count.

**Review by maryliag — COMMENTED** [review]
can you add an example of a result on this description? thanks

> Reviewed 2 of 5 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71299#-:-Mltpi9w4fJToxR1hD8B:bjyy1zq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, @RaduBerinde, and @yuzefovich)

___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior, line 1247 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71299#-MltqlH14ScH9Dh_O159:-MltqlH14ScH9Dh_O15A:bh8j5p5) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ebdb8b779762e5af34add903e85b8ef56f723cb/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior#L1247)):*
> ```
>                 │   │         ordering: +a,+b
>                 │   │         estimated row count: 333,333 (33% of the table; stats collected <hidden> ago)
>                 │   │         limit hint: 3
> ```

on another comment you mentioned you changed to show a range when the limit hint is not 0, but here it's a single value. Is that correct?

**Review by rytaft — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71299)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior, line 1247 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71299#-MltqlH14ScH9Dh_O159:-MltthzK2LhPuz1fzwaJ:b-5cjj36) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ebdb8b779762e5af34add903e85b8ef56f723cb/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior#L1247)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

on another comment you mentioned you changed to show a range when the limit hint is not 0, but here it's a single value. Is that correct?
</blockquote></details>

Looks like maybe you just need to update this test file?
___
*[pkg/sql/opt/exec/factory.go, line 307 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71299#-MltsiCwE7f56zHSZoT1:-MltsiCwE7f56zHSZoT2:b2syfk4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ebdb8b779762e5af34add903e85b8ef56f723cb/pkg/sql/opt/exec/factory.go#L307)):*
> ```Go
> 	// the child operators.
> 	Cost float64
> ```

nit: remove blank line to match formatting above

**Review by Azhng — COMMENTED** [review]
Example result added 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71299#-:-Mlu7JMq62Ck4wLvh8sO:byids8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag, @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior, line 1247 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71299#-MltqlH14ScH9Dh_O159:-Mlu7FZS3EuBAENSF4qy:btdgfog) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ebdb8b779762e5af34add903e85b8ef56f723cb/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior#L1247)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Looks like maybe you just need to update this test file?
</blockquote></details>

Test file updated
___
*[pkg/sql/opt/exec/factory.go, line 307 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71299#-MltsiCwE7f56zHSZoT1:-Mlu7HieAmy19j5-KUOs:ba3dfob) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ebdb8b779762e5af34add903e85b8ef56f723cb/pkg/sql/opt/exec/factory.go#L307)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: remove blank line to match formatting above
</blockquote></details>

Removed

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71299#-:-Mlu7zTj8z8tv2NpRJTb:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag, @RaduBerinde, @rytaft, and @yuzefovich)

**Review by yuzefovich — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71299)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag, @RaduBerinde, @rytaft, and @yuzefovich)

**Pull request merged**
