### PR TITLE
storage: Add test for setting zone configs on system ranges

### LINKED ISSUE #14807: storage: Add unit test that verifies zone configs behave properly on system ranges
Some follow-up work from #14740. We should have unit tests around this to prevent future regressions. While in theory the existing zone config tests should mostly cover this, the system range configs are special enough that they probably merit their own high-level tests in addition to what was added in #14740.

### LINKED ISSUE #16691: storage: Adding to replica GC queue upon removal can race with scanner's call to shouldQueue
If a replica gets added to the replica GC queue due to another member of its range telling it that it's been removed, then normally it'll fairly quickly get processed and GC'ed. However, if the scanner happens to call into `replicaGCQueue.shouldQueue` between when it gets added and when it gets popped off the queue for processing, `shouldQueue` will say that it doesn't need to be queued and the base queue will remove it. This is because `shouldQueue` bases its decision almost entirely on time since last processing and not on whether the replica is still a member of the range. We could fix it by also taking the replica's local range descriptor copy into account in `shouldQueue`.

This is hardly urgent (if we even care to fix it at all), but I'm making note of it since it was causing some troubles with trying to test that the number of replicas on each store in a test dropped back down to a correct number.

### PR DESCRIPTION
**Pull request by a-robinson**
**storage: GC replicas that aren't members of their own range descriptor**

Fixes #16691

**storage: Add test for setting zone configs on system ranges**

This also stresses our replication/replicaGC logic pretty hard, as a
side benefit. It shouldn't be run as part of testshort since it takes
nearly 2 seconds in a typical run.

Fixes #14807

### CODE REVIEW

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/storage/client_replica_test.go, line 1523 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16692#-KnPZWGbCqVndPfYurrw:-KnPZWGbCqVndPfYurrx:b-rny2tw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8bebce41377954047285a841df31500fa305e6/pkg/storage/client_replica_test.go#L1523)):*
> ```Go
> 	// Before moving forward, pre-split the keys for the system zone configs.
> 	// If we don't do this, the test can flake on the splits happening at an
> 	// innopportune time (or on the replicate queue blocking on a needed split
> ```

s/inn/in

---

*[pkg/storage/client_replica_test.go, line 1539 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16692#-KnPZr0H-fS_gvgtgpld:-KnPZr0H-fS_gvgtgple:b-u6iokn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8bebce41377954047285a841df31500fa305e6/pkg/storage/client_replica_test.go#L1539)):*
> ```Go
> 	// Allow for inserting zone configs without having to go through (or
> 	// duplicate the logic from) the CLI.
> 	config.TestingSetupZoneConfigHook(tc.Stopper())
> ```

Mind moving this down closer to where you actually change the ZoneConfig?

---

*[pkg/storage/client_replica_test.go, line 1574 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16692#-KnP_ZkXj5Uq0byfii1o:-KnP_ZkXj5Uq0byfii1p:bhi89n6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8bebce41377954047285a841df31500fa305e6/pkg/storage/client_replica_test.go#L1574)):*
> ```Go
> 	}
> 
> 	// Wait until we're down to the expected number of replicas (this is
> ```

What is downreplicating here? Did we do anything else but start up a new cluster and run some splits? What caused overreplication? I would expect that we'd wait for upreplication here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16692#-:-KnPaXvz-LLbkCG183X4:bnfp4nl)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/storage/client_replica_test.go, line 1515 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16692#-KnPaawA1WKWG9vQ2Vz-:-KnPaawA1WKWG9vQ2Vz0:b-v5t9r9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8bebce41377954047285a841df31500fa305e6/pkg/storage/client_replica_test.go#L1515)):*
> ```Go
> 			// Scan like a bat out of hell to ensure replication and replica GC
> 			// happen in a timely manner.
> 			ScanInterval: 200 * time.Millisecond,
> ```

Almost feel like you could go a little more aggressive here to get the test runtime down... WDYT?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16692)*

**Comment by a-robinson** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/storage/client_replica_test.go, line 1515 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16692#-KnPaawA1WKWG9vQ2Vz-:-KngcsoeEDVwe36_DTh0:b-cv2z31) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8bebce41377954047285a841df31500fa305e6/pkg/storage/client_replica_test.go#L1515)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Almost feel like you could go a little more aggressive here to get the test runtime down... WDYT?
</blockquote></details>

Good call, I've bumped it down to 50ms, which puts the runtime in the 1-1.5 second range. I previously had it lower but raising it helped reduce some of the flakiness I was seeing before I added in the first commit.

---

*[pkg/storage/client_replica_test.go, line 1523 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16692#-KnPZWGbCqVndPfYurrw:-KngbFybFJpzY-X2AdXQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8bebce41377954047285a841df31500fa305e6/pkg/storage/client_replica_test.go#L1523)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

s/inn/in
</blockquote></details>

Done.

---

*[pkg/storage/client_replica_test.go, line 1539 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16692#-KnPZr0H-fS_gvgtgpld:-KngbPwb1n5zHY5rBnhI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8bebce41377954047285a841df31500fa305e6/pkg/storage/client_replica_test.go#L1539)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Mind moving this down closer to where you actually change the ZoneConfig?
</blockquote></details>

Done.

---

*[pkg/storage/client_replica_test.go, line 1574 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16692#-KnP_ZkXj5Uq0byfii1o:-KngbRzsxCTRItaMrRwg:bp9knk9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8bebce41377954047285a841df31500fa305e6/pkg/storage/client_replica_test.go#L1574)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

What is downreplicating here? Did we do anything else but start up a new cluster and run some splits? What caused overreplication? I would expect that we'd wait for upreplication here.
</blockquote></details>

Rebalancing amongst the five nodes causes there to be inactive replicas around on stores until the replica GC queue runs. The first node ends up with a copy of all of the ranges after the initial splitting is done, but a couple tend to get moved away in rebalancing. Does the expanded comment clarify things?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16692)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/client_replica_test.go, line 1574 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16692#-KnP_ZkXj5Uq0byfii1o:-KngscXxTVCpn9VvEOCV:b-af183f) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8bebce41377954047285a841df31500fa305e6/pkg/storage/client_replica_test.go#L1574)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Rebalancing amongst the five nodes causes there to be inactive replicas around on stores until the replica GC queue runs. The first node ends up with a copy of all of the ranges after the initial splitting is done, but a couple tend to get moved away in rebalancing. Does the expanded comment clarify things?
</blockquote></details>

Yep, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16692)*

**Pull request merged**
