### PR TITLE
upgrade: remove buggy TTL repair

### LINKED ISSUE #110363: upgrade: automated catalog repairs incorrectly removes TTL from the table descriptor
During a cluster upgrade TTL is incorrectly removed from table descriptors [here](https://github.com/cockroachdb/cockroach/blob/v23.1.9/pkg/sql/catalog/tabledesc/table_desc_builder.go#L250) because the TTL job schedule ID from the table descriptor is incorrectly being searched for in a set of job IDs [here](https://github.com/cockroachdb/cockroach/blob/v23.1.9/pkg/sql/sem/builtins/builtins.go#L5216).

Later on when the TTL job runs, it panics (stack trace here https://github.com/cockroachlabs/support/issues/2593#issuecomment-1713899436) and crashes the node.

**Remove the TTL "repair" for now:** https://cockroachlabs.slack.com/archives/C05RE28U495/p1694456292147979?thread_ts=1694454150.432349&cid=C05RE28U495

See also:
https://github.com/cockroachlabs/support/issues/2593#issuecomment-1714377621

Jira issue: CRDB-31400

### PR DESCRIPTION
**Pull request by ecwall**
Fixes #110363

The TTL descriptor repair in FirstUpgradeFromReleasePrecondition incorrectly
removes TTL fields from table descriptors after incorrectly comparing the
table descriptor's TTL job schedule ID to a set of job IDs.

This change removes the repair until tests are properly added.

Release note (bug fix): Remove buggy TTL descriptor repair. Previously,
upgrading from 22.2.X to 23.1.9 incorrectly removed TTL storage params from
tables (visible via `SHOW CREATE TABLE <ttl-table>;`) while attempting to
repair table descriptors. This resulted in the node that attempts to run the
TTL job crashing due to a panic caused by the missing TTL storage params.
Clusters currently on 22.2.X should NOT be upgraded to 23.1.9 and should
be upgraded to 23.1.10 or later directly.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
code lgtm!, but please include this test: https://cockroachlabs.slack.com/archives/C05RE28U495/p1694457604827269

**Comment by ecwall** [comment]
> code lgtm!, but please include this test: https://cockroachlabs.slack.com/archives/C05RE28U495/p1694457604827269

Ah missed that, added.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110364)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @rafiss)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110364#-Ne4m2MB7QQKs4W7BPKx):*
Please extend the release note:
- what is the symptom of the bug a customer would see.
- what version the bug was introduced in.
- what, if anything, does the customer need to do if they encounter the bug other than upgrade to the version containing the fix.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110364)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @knz)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110364#-Ne4m2MB7QQKs4W7BPKx):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Please extend the release note:
- what is the symptom of the bug a customer would see.
- what version the bug was introduced in.
- what, if anything, does the customer need to do if they encounter the bug other than upgrade to the version containing the fix.
</blockquote></details>

the bug was introduced in v23.1.9
___
*[`pkg/sql/logictest/testdata/logic_test/upgrade` line 0 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110364#-Ne4nCTe79bMRI_How0Y:-Ne4nCTe79bMRI_How0Z:bd8u0wz) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb07d940462755df6b6970f58aeb4066b62dc244/pkg/sql/logictest/testdata/logic_test/upgrade#L0)):*
nit: let's rename the file to something more descriptive. perhaps `mixed_version_upgrade_repair_descriptors` or `mixed_version_row_level_ttl`

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110364)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @rafiss)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110364#-Ne4m2MB7QQKs4W7BPKx):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

the bug was introduced in v23.1.9
</blockquote></details>

I am personally aware, yes. I am just pointing out that this information should be included in the release note too.

as per https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/186548364/Release+notes#Bug-fix

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110364)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @rafiss)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110364#-Ne4m2MB7QQKs4W7BPKx):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I am personally aware, yes. I am just pointing out that this information should be included in the release note too.

as per https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/186548364/Release+notes#Bug-fix
</blockquote></details>

Probably worth mentioning in the RN as well that "clusters using TTL should not be upgraded to 23.1.9 at all and should be upgraded to 23.1.10 or later directly".

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110364)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @knz)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110364#-Ne4m2MB7QQKs4W7BPKx):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Probably worth mentioning in the RN as well that "clusters using TTL should not be upgraded to 23.1.9 at all and should be upgraded to 23.1.10 or later directly".
</blockquote></details>

 i thought you were probably aware, but added the comment to help with amending the note :) 
___
*[`pkg/sql/catalog/tabledesc/table_desc_builder.go` line 246 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110364#-Ne5-3u77izwOLoJRrRO:-Ne5-3u77izwOLoJRrRP:b-wsu3by) ([raw file](https://github.com/cockroachdb/cockroach/blob/716848be7847c068d5ee366eaff3a5d599df0e7e/pkg/sql/catalog/tabledesc/table_desc_builder.go#L246)):*
> ```Go
> 			tdb.changes.Add(catalog.StrippedDanglingBackReferences)
> 		}
> 	}
> ```

one more thing i forgot from the first review; let's add a short-circuit here: https://github.com/cockroachdb/cockroach/blob/3b00ec64ff965cffc5c752a625f6dcdb67043ea8/pkg/upgrade/upgrades/first_upgrade.go#L39

for 23.1, let's make this repair logic only happen if a certain environment variable is set

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110364)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110364#-Ne4m2MB7QQKs4W7BPKx):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i thought you were probably aware, but added the comment to help with amending the note :)
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/upgrade` line  at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110364#-Ne4nCTe79bMRI_How0Y:-Ne4yFT71dNil4qTmxLT:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb07d940462755df6b6970f58aeb4066b62dc244/pkg/sql/logictest/testdata/logic_test/upgrade#L)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: let's rename the file to something more descriptive. perhaps `mixed_version_upgrade_repair_descriptors` or `mixed_version_row_level_ttl`
</blockquote></details>

Done

**Review by knz — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110364)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @rafiss)

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110364)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

___
*[`pkg/sql/catalog/tabledesc/table_desc_builder.go` line 246 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110364#-Ne5-3u77izwOLoJRrRO:-Ne5Rzk07HYAKo9_6JB0:b-g0pid0) ([raw file](https://github.com/cockroachdb/cockroach/blob/716848be7847c068d5ee366eaff3a5d599df0e7e/pkg/sql/catalog/tabledesc/table_desc_builder.go#L246)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

one more thing i forgot from the first review; let's add a short-circuit here: https://github.com/cockroachdb/cockroach/blob/3b00ec64ff965cffc5c752a625f6dcdb67043ea8/pkg/upgrade/upgrades/first_upgrade.go#L39

for 23.1, let's make this repair logic only happen if a certain environment variable is set
</blockquote></details>

Should this be a separate PR that is made against the release-23.1 branch and backported to 23.1.10?

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110364)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

___
*[`pkg/sql/catalog/tabledesc/table_desc_builder.go` line 246 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110364#-Ne5-3u77izwOLoJRrRO:-Ne5SIDbAbYknqoFM49w:b753tk) ([raw file](https://github.com/cockroachdb/cockroach/blob/716848be7847c068d5ee366eaff3a5d599df0e7e/pkg/sql/catalog/tabledesc/table_desc_builder.go#L246)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

Should this be a separate PR that is made against the release-23.1 branch and backported to 23.1.10?
</blockquote></details>

Also it looks like this is only used for 23.2
```
firstUpgradeTowardsV23_2 = upgrade.NewTenantUpgrade(  
  "prepare upgrade to v23.2 release",  
  toCV(clusterversion.V23_2Start),  
  FirstUpgradeFromReleasePrecondition,  
  FirstUpgradeFromRelease,  
)
```

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110364)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @knz)

___
*[`pkg/sql/catalog/tabledesc/table_desc_builder.go` line 246 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110364#-Ne5-3u77izwOLoJRrRO:-Ne5sJZlCQYvMHeVBZbl:bq94y36) ([raw file](https://github.com/cockroachdb/cockroach/blob/716848be7847c068d5ee366eaff3a5d599df0e7e/pkg/sql/catalog/tabledesc/table_desc_builder.go#L246)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

Also it looks like this is only used for 23.2
```
firstUpgradeTowardsV23_2 = upgrade.NewTenantUpgrade(  
  "prepare upgrade to v23.2 release",  
  toCV(clusterversion.V23_2Start),  
  FirstUpgradeFromReleasePrecondition,  
  FirstUpgradeFromRelease,  
)
```
</blockquote></details>

this upgrade exists in 23.1 also.  https://github.com/cockroachdb/cockroach/blob/83bdbccb5a7566759daed3e8cadd7f0de6b16567/pkg/upgrade/upgrades/upgrades.go#L330-L335

anyway, sure, let's only add the short-circuit logic in the backport

**Review by rafiss — CHANGES_REQUESTED** [review]
looks like TestStripDanglingBackReferences needs to be updated

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110364#-:-Ne5t-oLBjYxtPdloPgF:b3rz6cp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @knz)

___
*[`pkg/sql/logictest/testdata/logic_test/mixed_version_upgrade_repair_descriptors` line 9 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110364#-Ne5stAIBlJT2bDriLeJ:-Ne5stAIBlJT2bDriLeK:bfckssk) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d4a27f4d91db443569b1ff37d5cf0603cc20ec2/pkg/sql/logictest/testdata/logic_test/mixed_version_upgrade_repair_descriptors#L9)):*
> ```
> 
> query T
> SELECT crdb_internal.node_executable_version()
> ```

you can remove this assertion, or if you keep it, the expected value on this branch is `23.1`

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110364)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

___
*[`pkg/sql/logictest/testdata/logic_test/mixed_version_upgrade_repair_descriptors` line 9 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110364#-Ne5stAIBlJT2bDriLeJ:-Ne5y3V2A2qQC7djUEtQ:b-a02du5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d4a27f4d91db443569b1ff37d5cf0603cc20ec2/pkg/sql/logictest/testdata/logic_test/mixed_version_upgrade_repair_descriptors#L9)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

you can remove this assertion, or if you keep it, the expected value on this branch is `23.1`
</blockquote></details>

I'll remove that.

Is this needed below? 
```
query B retry
SELECT version LIKE '22.2-%' FROM [SHOW CLUSTER SETTING version]
----
true
```

Shouldn't the version be 23.1 after the upgrade?

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110364)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @knz)

___
*[`pkg/sql/logictest/testdata/logic_test/mixed_version_upgrade_repair_descriptors` line 9 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110364#-Ne5stAIBlJT2bDriLeJ:-Ne6JEE26XsJkHkQgwGj:b-e3yope) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d4a27f4d91db443569b1ff37d5cf0603cc20ec2/pkg/sql/logictest/testdata/logic_test/mixed_version_upgrade_repair_descriptors#L9)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

I'll remove that.

Is this needed below? 
```
query B retry
SELECT version LIKE '22.2-%' FROM [SHOW CLUSTER SETTING version]
----
true
```

Shouldn't the version be 23.1 after the upgrade?
</blockquote></details>

ah, i had this check from when i was testing on the 23.1 branch.

when testing on master, the check should be:
```
query B retry
SELECT version LIKE '23.1-%' FROM [SHOW CLUSTER SETTING version]
----
true
```

Note that this is looking at the logical cluster version, not the binary version.

On master, the previous logical version starts at 23.1, and the check for `23.1-%` makes sure that the first upgrade migration (the one that runs all repairs) has finished running. (after all upgrade migrations run, `SHOW CLUSTER SETTING version` would show 23.2)

On the 23.1 branch, this check should be looking for `22.2-%` instead

**Review by rafiss — APPROVED** [review]
lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110364#-:-Ne938jpEf6XpDrUzySL:b-7nbn20)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @knz)

**Comment by ecwall** [comment]
bors r=rafiss

**Pull request merged**
