### PR TITLE
sql: make the JSON column in EXPLAIN(DISTSQL)'s output hidden

### PR DESCRIPTION
**Pull request by knz**

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Thank you! LGTM

**Comment by knz** [comment]
cc @nstewart

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17386#-:-KqYaMVVsodsm42c64aq:bnfp4nl)*

**Comment by RaduBerinde** [comment]
What did this actually accomplish? As far as I can tell, the Hidden field is ignored for the top-level node; a bare `EXPLAIN (DISTSQL)` still shows the JSON..

**Comment by knz** [comment]
Oh then there might be a regression!

**Comment by knz** [comment]
back then when this PR was merged the column was hidden properly.

**Comment by RaduBerinde** [comment]
Cool, thanks, I filed an issue.

**Pull request merged**
