### PR TITLE
ioutil: remove most references to ioutil

### PR DESCRIPTION
**Pull request by jeffswenson**
This change removes most references to `ioutil` and replaces them with
equivalent methods in `io` and `os`. All of the changes in this PR were
made by the attached script. The script was used to migrate the
cockroach cloud repository.

The script does not migrate `ioutil.ReadDir` to os.ReadDir. os.ReadDir has a
different type and is not a drop in replacement.

```bash
function rewrite {
    fastmod -F "${1?}" "${2?}" -g '!vendor/' -g '*go'
}

rewrite ioutil.ReadAll io.ReadAll
rewrite ioutil.ReadFile os.ReadFile
rewrite ioutil.TempDir os.MkdirTemp
rewrite ioutil.TempFile os.CreateTemp
rewrite ioutil.WriteFile os.WriteFile

goimports -w .
```

Release justification: required by go1.19 linter
Release note: None

### CODE REVIEW

**Review by rickystewart — APPROVED** [review]
Awesome, thanks for this. :)

**Comment by yuzefovich** [comment]
Looks like this needs a rebase.

bors r-

**Comment by yuzefovich** [comment]
Courtesy rebase.

bors r+

**Pull request merged**
