### PR TITLE
sql: Refactoring structured.proto. Renaming ColumnType Kind enum to SemanticType.

### LINKED ISSUE #10705: sql: bikeshed on renaming ColumnType, ColumnType_Kind, ColumnType_Kind_value
`ColumnType`, `ColumnType_Kind`, `ColumnType_Kind_value` are badly named. It abuses the term `Kind` (`ColumnType_Kind` is not a kind[1]), it is just the base type). `ColumnType` is currently a wrapper around `ColumnType_Kind` with some additional metadata specific to certain types (for instance, `DECIMAL` and `FLOAT` use the `Precision` metadata).

`ColumnType_Kind_value` is an unfortunate effect of the fact that any `XXX` enum protos generate maps for `XXX_name` and `XXX_value`, but we should choose proto names being mindful of the fact that this is going to happen. and that it will be confusing to have `_value` appended to something named `XXXType_Kind`, because `XXXType_Kind_value` starts to sound like a cruel joke on type theorists.

I propose that we rename the protos in the following way:

Rename `ColumnType_Kind` -> `ColumnBaseType`. To achieve this, we move the `enum` proto in `sql/structured.proto` which is currently defined inside `ColumnType` outside (otherwise it is saddled with the `ColumnType_` prefix).

`ColumnType` stays the same.

Sadly, we are saddled with the `_value` suffixes, but `ColumnBaseType_value` is somewhat acceptable.

This is somewhat cleaner. A column has a `ColumnType`, which has a `ColumnBaseType` (`INT`, `DECIMAL`, `DATE`, etc.), which is potentially annotated with some other information, such as a `Precision`, or a `Width`. Sadly, this isn't statically type checkable as we don't have option types. Ideally we'd have the equivalent of the following OCaml type: 
`type ColumnType = BOOL | INT of width | FLOAT of precision | DECIMAL of width * precision | ...`

If anyone has strong objections to such a renaming, or a better proposal with better names, or some secret protobuf powers that would get us option times, I'd be happy to hear it. I am happy to carry out the renaming myself once we have consensus. I hope that we don't have too much bikeshedding on this...

cc @knz @RaduBerinde @paperstreet @andreimatei 

[1]: https://en.wikipedia.org/wiki/Kind_(type_theory)

### PR DESCRIPTION
**Pull request by m-schneider**
The current use of the the word kind to denote type, in the ColunmType message
is confusing. The upcoming changes to intoduce new enums to seperate semantic
types from visible types will only make this worse.

Closes #10705

### CODE REVIEW

**Comment by knz** [comment]
Oh my. A dream come true. @arjunravinarayan come check this out!

Masha:
- please update the existing RFCs that mention the term "kind" to be consistent with the new naming ( can see two at least)
- please also rename the field parser.DOid.kind
- extend your commit message (and possibly the PR description) with a rationale for this change. You can take inspiration from our discussion on the other PR.

---

Reviewed 29 of 29 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16606#-:-Kn0pljbCVDDMyEBbS7z:b-sojzb3)*

**Comment by arjunravinarayan** [comment]
Wonderful! Will give a thorough review shortly, but a quick note that "Closes #10705" would be useful in the commit message.

**Comment by arjunravinarayan** [comment]
@knz, what is the "other PR"?

**Comment by m-schneider** [comment]
Raphael:
* Updated every RFC that references kind.
* renamed Doid.kind.
* Extended the commit message with some inspiration from https://github.com/cockroachdb/cockroach/pull/16548 and https://github.com/cockroachdb/cockroach/issues/10705.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16606#-:-Kn1KybT-XTYTcBf3g0Y:b27emr9)*

**Comment by m-schneider** [comment]
Arjun, added the issue to the commit message.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16606#-:-Kn1Mk1mPCg_W-Svlp11:b-knr5fx)*

**Comment by knz** [comment]
@arjunravinarayan the renaming discussion started in https://github.com/cockroachdb/cockroach/pull/16548#issuecomment-308974099

**Comment by knz** [comment]
@m-schneider you need to write literally "Fixes #10705." or "Closes #10705." on a line by itself in either the PR description or the commit message for Github to pick it up when you'll merge this.

**Comment by knz** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16606#-:-Kn1XPlTggGGRjASRQfP:bnfp4nl)*

**Comment by arjunravinarayan** [comment]
:lgtm:

---

Reviewed 28 of 29 files at r1, 6 of 6 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16606#-:-Kn4WB_4AqybpohAxswn:bnfp4nl)*

**Comment by m-schneider** [comment]
@knz, didn't know that thanks for the tip!
Done.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16606#-:-Kn4xKCEb3ntF_c0RYDu:b-df69ub)*

**Pull request merged**
