### PR TITLE
ccl: Attempt at fixing flaky zone logic test.

### PR DESCRIPTION
**Pull request by rohany**
Addressing #38864

I couldn't get the errors to appear locally with make stress and stressrace.

Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
Hmm... I don't feel particularly great about just retrying til it works. Why was it not working in the first place? Thanks for taking a look. How long did you run stress for? Try doing it for like 20 minutes on a gceworker.

**Comment by rohany** [comment]
I think it's some sort of race -- alot of the tests around it use the retry flag as well, so it seemed like this test was just missing it. I ran both for around 15 minutes on my laptop -- how do I set up a gce worker?

**Comment by jordanlewis** [comment]
https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/65077811/Building+with+gceworker

**Comment by danhhz** [comment]
I also highly recommend roachprod-stress, which is like a bunch of parallel gceworkers, with none of the setup cost

```
roachprod create dan-stress -n 10 --gce-machine-type=n1-standard-8 --local-ssd=false
make roachprod-stress TESTS=Foo PKG=./pkg/foo CLUSTER=dan-stress
```

**Pull request closed without merging**
