### PR TITLE
sqlstats: include regions in statement_statistics

### PR DESCRIPTION
**Pull request by matthewtodd**
Part of #89949.

This completes the work abandoned in #92259, properly storing the regions in which a statement was executed, rather than waiting until UI render time to try to map (dangerously ephemeral) node IDs to their respective regions.

With this work in place, we will be able to remove both the UI mapping code (usages of this [selector][]) and the stop-gap work of #93268.

[selector]: https://github.com/cockroachdb/cockroach/blob/0f6333cbd6c78264a59dc435324c0c33d75ea148/pkg/ui/workspaces/cluster-ui/src/store/nodes/nodes.selectors.ts#L52-L64

Release note (sql change): A regions field was added to the statistics column of crdb_internal.statement_statistics, reporting the regions of the nodes on which the statement was executed.

### CODE REVIEW

**Comment by matthewtodd** [comment]
Test failure looks like #96149, possibly related to the unified SQL address resolver?

**Review by maryliag — CHANGES_REQUESTED** [review]
just a small request, otherwise :lgtm: 

> Reviewed 19 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95449#-:-NPrR41VEJB4Q0qcrOX6:b-1e6hlg)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @matthewtodd and @yuzefovich)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95449#-NPrQcDHCAXgOjKXonbW):*
can you create an issue to track this?

**Review by maryliag — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95449#-:-NPrRAR54ADv6p3Uzq6X:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @matthewtodd and @yuzefovich)

**Review by matthewtodd — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95449#-:-NPra2db2vFRNPI0TjiP:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag and @yuzefovich)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95449#-NPrQcDHCAXgOjKXonbW):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

can you create an issue to track this?
</blockquote></details>

Done! #98056 and #98057. I'll tackle the first one early this week.

**Pull request merged**
