### PR TITLE
roachtest: after test, fail (or complain) if any CRDB nodes are dead

### PR DESCRIPTION
**Pull request by tbg**
Do what's in the title. This will help us ensure that no test leaves dead
nodes behind (maybe some tests do that today, perhaps some chaos ones, but
it'll be easy enough to fix). This gives us confidence that when a test
passes, none of the nodes died. Additionally, for tests that fail, it will
always be obvious that a node died because it is now printed as part of the
test output including what gets posted into a Github issue.

Example:

I changed the test below so that it would start nodes 1-3, immediately stop
node 1, and return, resulting in the following test failure:

```
--- FAIL: tpcc/nodes=3/w=max (7.24s)
cluster.go:956,context.go:90,cluster.go:942,test.go:1160,test.go:1219: dead
node detection: 4: skipped
	1: dead
	2: 83220
	3: 83229
	Error:  1: dead
```

Release note: None

### CODE REVIEW

**Review by andreimatei — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36224)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @petermattis, and @tbg)

___
*[pkg/cmd/roachprod/main.go, line 1573 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-Lb-9HhW3xaLULPrpCRK:-Lb-9HhW3xaLULPrpCRL:b-lwipx1) ([raw file](https://github.com/cockroachdb/cockroach/blob/34bd57eed674b2c6f9add722e687f32fb8459958/pkg/cmd/roachprod/main.go#L1573)):*
> ```Go
> 	monitorCmd.Flags().BoolVar(
> 		&monitorAuto,
> 		"auto",
> ```

how about `ignore-empty-stores`
___
*[pkg/cmd/roachprod/install/cluster_synced.go, line 266 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-Lb-9V9s3KBuXInGIHcy:-Lb-9V9s3KBuXInGIHcz:b-griysa) ([raw file](https://github.com/cockroachdb/cockroach/blob/34bd57eed674b2c6f9add722e687f32fb8459958/pkg/cmd/roachprod/install/cluster_synced.go#L266)):*
> ```Go
> }
> 
> // NodeMonitorInfo TODO(peter): document
> ```

let's put some docs here. What's `msg`?
___
*[pkg/cmd/roachprod/install/cluster_synced.go, line 274 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-Lb-9_aN0uw0YceADt7G:-Lb-9_aN0uw0YceADt7H:by0eexd) ([raw file](https://github.com/cockroachdb/cockroach/blob/34bd57eed674b2c6f9add722e687f32fb8459958/pkg/cmd/roachprod/install/cluster_synced.go#L274)):*
> ```Go
> 
> // Monitor TODO(peter): document
> func (c *SyncedCluster) Monitor(auto bool, oneShot bool) chan NodeMonitorInfo {
> ```

please comment the args, and maybe make `auto` more descriptive
___
*[pkg/cmd/roachprod/install/cluster_synced.go, line 335 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-Lb-AUJ613Fu05hsBA4I:-Lb-AUJ613Fu05hsBA4J:b-drmsil) ([raw file](https://github.com/cockroachdb/cockroach/blob/34bd57eed674b2c6f9add722e687f32fb8459958/pkg/cmd/roachprod/install/cluster_synced.go#L335)):*
> ```Go
> 			cmd := fmt.Sprintf(`
> lastpid=0
> %s
> ```

oh boy this script has become a bit unreadable.
Have you tried using a `text.Template`?
___
*[pkg/cmd/roachtest/cluster.go, line 935 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-Lb-BDcgDe6ZetkQXEY8:-Lb-BDcgDe6ZetkQXEY9:bknqhte) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a6af9b8cc843cc9a332cbaab0df9f0d0be0d35d/pkg/cmd/roachtest/cluster.go#L935)):*
> ```Go
> // FailOnDeadNodes fails the test if nodes that have a populated data dir are
> // found to be not running. It prints both to t.l and the test output.
> func (c *cluster) FailOnDeadNodes(ctx context.Context, t *test) {
> ```

don't take `t` as an arg. Just return an error.
___
*[pkg/cmd/roachtest/cluster.go, line 943 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-Lb-Aof913db5qbC2xnX:-Lb-Aof913db5qbC2xnY:b-ykf6s) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a6af9b8cc843cc9a332cbaab0df9f0d0be0d35d/pkg/cmd/roachtest/cluster.go#L943)):*
> ```Go
> 	// Don't hang forever.
> 	_ = contextutil.RunWithTimeout(ctx, "detect dead nodes", 20*time.Second, func(ctx context.Context) error {
> 		output, err := execCmdWithBuffer(
> ```

Can't we use the `Monitor` as a library instead of running a different process?
___
*[pkg/cmd/roachtest/cluster.go, line 946 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-Lb-BN-R0TSu5SaWBhbX:-Lb-BN-R0TSu5SaWBhbY:b-8g8vyu) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a6af9b8cc843cc9a332cbaab0df9f0d0be0d35d/pkg/cmd/roachtest/cluster.go#L946)):*
> ```Go
> 			ctx, c.l, roachprod, "monitor", c.name, "--oneshot", "--auto",
> 		)
> 		// Make this show up in `test.log` as well as the test runner's
> ```

what is "this"? What's in that output in the success case? Do we really need to log it when successful?

**Review by tbg — COMMENTED** [review]
RFAL!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-:-Lb-gzQ6EQkAj5YbWENJ:b-828fnn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @petermattis)

___
*[pkg/cmd/roachprod/main.go, line 1573 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-Lb-9HhW3xaLULPrpCRK:-Lb-ZqAaEGv7wYI6CDnS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/34bd57eed674b2c6f9add722e687f32fb8459958/pkg/cmd/roachprod/main.go#L1573)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

how about `ignore-empty-stores`
</blockquote></details>

Done.
___
*[pkg/cmd/roachprod/install/cluster_synced.go, line 266 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-Lb-9V9s3KBuXInGIHcy:-Lb-Xyu-5TuRS74WgCoL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/34bd57eed674b2c6f9add722e687f32fb8459958/pkg/cmd/roachprod/install/cluster_synced.go#L266)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

let's put some docs here. What's `msg`?
</blockquote></details>

Done.
___
*[pkg/cmd/roachprod/install/cluster_synced.go, line 274 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-Lb-9_aN0uw0YceADt7G:-Lb-Zr7Y9dJNXRH0erfu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/34bd57eed674b2c6f9add722e687f32fb8459958/pkg/cmd/roachprod/install/cluster_synced.go#L274)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

please comment the args, and maybe make `auto` more descriptive
</blockquote></details>

Done.
___
*[pkg/cmd/roachprod/install/cluster_synced.go, line 335 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-Lb-AUJ613Fu05hsBA4I:-Lb-fPZ8DO9JIX993EV3:bjta84n) ([raw file](https://github.com/cockroachdb/cockroach/blob/34bd57eed674b2c6f9add722e687f32fb8459958/pkg/cmd/roachprod/install/cluster_synced.go#L335)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

oh boy this script has become a bit unreadable.
Have you tried using a `text.Template`?
</blockquote></details>

Done. A lot better, thanks for coaxing me into it.
___
*[pkg/cmd/roachtest/cluster.go, line 935 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-Lb-BDcgDe6ZetkQXEY8:-Lb-gjbq8374AITPR24u:b-eligz7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a6af9b8cc843cc9a332cbaab0df9f0d0be0d35d/pkg/cmd/roachtest/cluster.go#L935)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

don't take `t` as an arg. Just return an error.
</blockquote></details>

No, I need to call `printfAndFail` and I don't want to feed it the error because that contains a lot more noise. (And before you ask, `c.t` is behind an interface so I don't want to use that because I'd randomly have to type assert it).

Roachtest is really a mess.
___
*[pkg/cmd/roachtest/cluster.go, line 943 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-Lb-Aof913db5qbC2xnX:-Lb-fkxu5LRLV1xk5X-u:b30rt3y) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a6af9b8cc843cc9a332cbaab0df9f0d0be0d35d/pkg/cmd/roachtest/cluster.go#L943)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Can't we use the `Monitor` as a library instead of running a different process?
</blockquote></details>

In theory you can. In practice literally everything in `roachtest` shells out to `roachprod` because it isn't a library. Won't change in this PR, neither.
___
*[pkg/cmd/roachtest/cluster.go, line 946 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-Lb-BN-R0TSu5SaWBhbX:-Lb-gQbm3aegs7SPBLhJ:bujyodi) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a6af9b8cc843cc9a332cbaab0df9f0d0be0d35d/pkg/cmd/roachtest/cluster.go#L946)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what is "this"? What's in that output in the success case? Do we really need to log it when successful?
</blockquote></details>

You can see sample output in the commit message introducing the `monitor` flags. It's one line per node (with the PID). We already print the invocation of the command (courtesy of `execCmdWithBuffer`) so it's weird not to print the output. And generally I have hated how things don't end up in `test.log` sometimes even though that's the only place anyone ever wants to look.

**Review by andreimatei — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-:-Lb-siSM3BLfjxpHM2aR:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @petermattis, and @tbg)

___
*[pkg/cmd/roachprod/install/cluster_synced.go, line 335 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-Lb-AUJ613Fu05hsBA4I:-Lb-nvJu3G45KEkcKr19:bb7lbs2) ([raw file](https://github.com/cockroachdb/cockroach/blob/34bd57eed674b2c6f9add722e687f32fb8459958/pkg/cmd/roachprod/install/cluster_synced.go#L335)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Done. A lot better, thanks for coaxing me into it.
</blockquote></details>

nice
___
*[pkg/cmd/roachtest/cluster.go, line 935 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-Lb-BDcgDe6ZetkQXEY8:-Lb-pJMc8X83esOIchE9:b-93g8i) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a6af9b8cc843cc9a332cbaab0df9f0d0be0d35d/pkg/cmd/roachtest/cluster.go#L935)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

No, I need to call `printfAndFail` and I don't want to feed it the error because that contains a lot more noise. (And before you ask, `c.t` is behind an interface so I don't want to use that because I'd randomly have to type assert it).

Roachtest is really a mess.
</blockquote></details>

I definitely don't want you to use `c.t`. That'd be worse :). That field should not exist.

But this method bothers me.
How about:

- Put a `t.l.PrintfCtxDepth(context.TODO(), skip+1, "test failure: %s", msg)` inside `printfAndFail()`. I already had that in my roachtest branch.
- Move the `c.FailOnDeadNodes(ctx, t)` call to another `defer`, below where you put it now.
- modify this `FailOnDeadNodes()` to use `t.Fatal(...)`, not the lower level `t.printfAndFail()`. This way `runtime.GoExit()` will be called but that will be immaterial because the other `defer` (the one where you currently put the call to `FailOnDeadNodes()`) will still run - I've checked that running `runtime.GoExit()` in a defer still runs the other defers.

And reconsider renaming this to `CheckForDeadNodes()` and have it return an err and not take t. It doesn't need to be the `err` you get from `execCmdWithBuf`, it can be a new error just with the message you want. The idea is to stop coupling tests and clusters.
___
*[pkg/cmd/roachtest/cluster.go, line 956 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-Lb-q0on2BTwv4Qa3N6u:-Lb-q0on2BTwv4Qa3N6v:b-advh5t) ([raw file](https://github.com/cockroachdb/cockroach/blob/df8a8897a80e99c8313968006618dcd7e51d02cc/pkg/cmd/roachtest/cluster.go#L956)):*
> ```Go
> 		// at the same time plus the horrible teamcity formatting that gets
> 		// added and that can't be undone.
> 		c.l.Printf("%s", output)
> ```

if nothing else use `t.l`here, not `c.l`.

**Review by tbg — COMMENTED** [review]
TFTRs! I'm going to be extra attentive to tonight's roachtest runs to catch any weirdness I may have intro'ed.

Heh, looks like I first need to fix up those in CI:



> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-:-Lb2dp3P7gDfY8kol8vG:bf1i9fm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @petermattis)

___
*[pkg/cmd/roachtest/cluster.go, line 935 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-Lb-BDcgDe6ZetkQXEY8:-Lb2_FZF9KWVLjHm6DL6:b52huqm) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a6af9b8cc843cc9a332cbaab0df9f0d0be0d35d/pkg/cmd/roachtest/cluster.go#L935)):*
> Put a t.l.PrintfCtxDepth(context.TODO(), skip+1, "test failure: %s", msg) inside printfAndFail(). I already had that in my roachtest branch.

Good idea. That method doesn't exist, but I did the next best thing using `c.l.Printf`.

I did the rest, too. Not 100% sure it's better (now things are less transparent at the caller), but it's probably good overall. I also checked that the result still works.
___
*[pkg/cmd/roachtest/cluster.go, line 956 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-Lb-q0on2BTwv4Qa3N6u:-Lb2aTVTAjM4L_n-mBGb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/df8a8897a80e99c8313968006618dcd7e51d02cc/pkg/cmd/roachtest/cluster.go#L956)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

if nothing else use `t.l`here, not `c.l`.
</blockquote></details>

Done.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36224)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @petermattis)

___
*[pkg/cmd/roachtest/cluster.go, line 935 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-Lb-BDcgDe6ZetkQXEY8:-Lb2etn7229wxD-grbY3:b8nsqvo) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a6af9b8cc843cc9a332cbaab0df9f0d0be0d35d/pkg/cmd/roachtest/cluster.go#L935)):*
> Good idea. That method doesn't exist, but I did the next best thing using c.l.Printf.

I actually went back and additionally did something better: `r.out` (the thing that writes to stdout) is replaced by `out` which is a `MultiWriter` into `test.log` and `r.out`. So now you get this at the end of `test.log`

```
--- FAIL: acceptance/cli/node-status (6.37s)
        cluster.go:951,context.go:90,cluster.go:942,test.go:1225: dead node detection: 4: skipped
                2: dead
                3: 31937
                1: 31919
                Error:  2: dead
```

I'm leaving the earlier Printf in, too, because it's good to see *when* which error was emitted. That line looks a little wonky though, so you'll probably feel the urge to refactor it when you get there, but that's fine by me.

**Review by tbg — COMMENTED** [review]
Okay I fixed them all up, I think. The most interesting one was `kv/splits` which showed that we were closing the `done` channel too early, while we were still grabbing debug stuff from the cluster, which led to my `roachprod monitor` being killed spuriously sometimes. Not sure why that didn't affect anything earlier. I reshuffled some code to make this all more copacetic. I also had to move the expiration-based skip code up a bit because the `expired` (registry unit test) needs that (and because it makes sense to not grab debug info from a cluster we never used for that test).

There's enough movement here to hold off on the merge, so please take another look @andreimatei so that we can get it in for tonight's runs.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-:-Lb2p-Q8BC_8OhxfIlNU:b-j2cpaw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @petermattis)

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36224)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @petermattis)

___
*[pkg/cmd/roachtest/cluster.go, line 935 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-Lb-BDcgDe6ZetkQXEY8:-Lb2vXfd7MRsHkPEAZd1:bywpfok) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a6af9b8cc843cc9a332cbaab0df9f0d0be0d35d/pkg/cmd/roachtest/cluster.go#L935)):*
> And reconsider renaming this to ...

I'm not gonna touch that stuff, but my understanding is that you're basically going to rewrite roachtest in the near future, and I'm happy to review those changes then. Don't want to get dragged to deep into the rabbit hole, every time I change something now I have to reconvince myself that things still work and that takes too much time.

**Review by tbg — COMMENTED** [review]
Got my green build. I'm triggering another 3 and when they come back green (or tests genuinely fail) I'll consider myself satisfied that this actually works.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-:-Lb3VxW8BQtuBr_SuA3I:b-ri2hho)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @petermattis)

**Review by tbg — COMMENTED** [review]
Got my three greens without a hitch.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-:-Lb3lSj31GHYvUnBYrYi:b-3voc8w)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @petermattis)

**Review by andreimatei — APPROVED** [review]
nit: please edit the PR message

LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-:-Lb3vQuM0xUJEhz3IQjs:b-nuxwbe)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @petermattis, and @tbg)

___
*[pkg/cmd/roachtest/cluster.go, line 948 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-Lb3w1vV87ehw84f8YyQ:-Lb3w1vV87ehw84f8YyR:b-152da7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7a87ebe277a25feb2351dde653bee29e276432d/pkg/cmd/roachtest/cluster.go#L948)):*
> ```Go
> 		// If there's an error, it means either that the monitor command failed
> 		// completely, or that it found a dead node worth complaining about.
> 		// Neither should happen (though if there are spurious failures here
> ```

nit: I'd strike the `Neither...` sentence; doesn't add anything. I think sometimes expressing uncertainty in comments is useful, but here if the test fails, whether or not the author of the check was certain about the check at the time he added it will be irrelevant.
___
*[pkg/cmd/roachtest/cluster.go, line 950 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-Lb3wiunD6o_dpgB_PVn:-Lb3wiunD6o_dpgB_PVo:bg6e6qi) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7a87ebe277a25feb2351dde653bee29e276432d/pkg/cmd/roachtest/cluster.go#L950)):*
> ```Go
> 		// Neither should happen (though if there are spurious failures here
> 		// unrelated to dead nodes we'll have to be smarter about it).
> 		if err != nil {
> ```

well as long as you're using the `RunWithTimeout` function (which I don't like much), I think what you want to do is handle errors outside of the function (instead of swallowing the return value which makes using that function completely unnecessary), and watch for `TimeoutError`. And so move the call to `t.Fatal()` outside too.
___
*[pkg/cmd/roachtest/cluster.go, line 955 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-Lb3ygvK8TI8FxXVw4GX:-Lb3ygvK8TI8FxXVw4GY:b-7ex19k) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7a87ebe277a25feb2351dde653bee29e276432d/pkg/cmd/roachtest/cluster.go#L955)):*
> ```Go
> 				return nil
> 			}
> 			// The output is usually nicer, but we don't want to swallow the
> ```

I barely know what this comment is telling me now. I definitely will have no idea in like 5 minutes. The `t.Fatalf()` call seems natural. I'd strike the comment.

**Review by tbg — COMMENTED** [review]
Done, TFTRs!

bors r=andreimatei

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-:-Lb4I_dJ79qazsXGqJJ_:bp5o7fl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @petermattis)

___
*[pkg/cmd/roachtest/cluster.go, line 950 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-Lb3wiunD6o_dpgB_PVn:-Lb4ItBc1kyJZGgNJHan:b-kj8t8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7a87ebe277a25feb2351dde653bee29e276432d/pkg/cmd/roachtest/cluster.go#L950)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

well as long as you're using the `RunWithTimeout` function (which I don't like much), I think what you want to do is handle errors outside of the function (instead of swallowing the return value which makes using that function completely unnecessary), and watch for `TimeoutError`. And so move the call to `t.Fatal()` outside too.
</blockquote></details>

I will leave that beautiful yak for you to shave.
___
*[pkg/cmd/roachtest/cluster.go, line 955 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/36224#-Lb3ygvK8TI8FxXVw4GX:-Lb4IsuC-1yFsoYw-oQy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7a87ebe277a25feb2351dde653bee29e276432d/pkg/cmd/roachtest/cluster.go#L955)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I barely know what this comment is telling me now. I definitely will have no idea in like 5 minutes. The `t.Fatalf()` call seems natural. I'd strike the comment.
</blockquote></details>

Done.

**Pull request merged**
