### PR TITLE
sql/parser: improve the inline help text for ALTER TENANT

### LINKED ISSUE #105055: multi-tenant: Improve the help message for ALTER TENANT
Currently, the help text for `ALTER TENANT` looks like this:

```
demo@127.0.0.1:26257/system/?> \h alter tenant                                                                                                                                          
Command:     ALTER TENANT
Description: alter tenant configuration
Syntax:
```
with the `Syntax` field blank.  We should improve this so that the syntax describes that this command can be used to start/stop tenants (and that we support both shared and separate process modes).

Epic: CRDB-26691

Jira issue: CRDB-28840

### PR DESCRIPTION
**Pull request by knz**
Fixes #105055.

Before:
```
Command:     ALTER TENANT
Description: alter tenant configuration
Syntax:


See also:
  ALTER TENANT REPLICATION
  ALTER TENANT CLUSTER SETTING
  ALTER TENANT CAPABILITY
  ALTER TENANT RENAME
```

After:
```
Command:     ALTER TENANT
Description: alter tenant configuration
Syntax:
ALTER TENANT REPLICATION, ALTER TENANT CLUSTER SETTING, ALTER TENANT CAPABILITY, ALTER TENANT RENAME, ALTER TENANT SERVICE
```

See the individual commits for details.

Epic: CRDB-26691

### CODE REVIEW

**Review by ajstorm — COMMENTED** [review]
Changes LGTM, but are there some tests we could add here?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105117#-:-NYIdcHMDmFK3vAh6cOM:bmbbird)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by knz** [comment]
Yes, the PR already contains exactly the test for the problem you had reported.

**Review by ajstorm — APPROVED** [review]
Ahh, my bad.  I was just looking at the first commit.  This LGTM.

Very minor nit: You might want to add the new help text to the PR description so it's clear how we're solving the problem.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105117#-:-NYO-T_p5NQfTsamu0QW:b-4c5oeo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by knz** [comment]
> you might want to add the new help text to the PR description so it's clear how we're solving the problem.

Done

bors r=ajstorm

**Pull request merged**
