### PR TITLE
copy: optimize date parsing memory usage

### LINKED ISSUE #91834: pgdate: pgdate.ParseDate allocates a lot of temporary heap memory
The fieldExtract struct escapes to the heap and the textChunks and numbers slices in fieldExtract.Extract are allocated every time, pulling these allocations into a reusable struct that can be passed to ParseDate would greatly speed up date parsing.

Jira issue: CRDB-21450

### PR DESCRIPTION
**Pull request by cucaroach**
- pgdate: benchmark ParseDate
- pgdate: optimize bulk date parsing
- sql: wire up pgdate optimization to ParseAndRequireString and colexec.

Fixes: #91834

I'll squash the last two commits but thought for review purposes they'd be better separate.

Epic: CRDB-18892

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 5 of 5 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92252#-:-NHVCtCF4mfcdGpEP2fs:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @otan)

___
*[`pkg/sql/colexec/execgen/cmd/execgen/cast_gen_util.go` line 398 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/92252#-NHVCI-3Blby2S5uOBPs:-NHVCI-40btXlHcyWhqL:bnv6kwq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f12108bcd2e307bc7e209513a335564f2225d531/pkg/sql/colexec/execgen/cmd/execgen/cast_gen_util.go#L398)):*
> ```Go
> 		_now := %[3]s.GetRelativeParseTime()
> 		_dateStyle := %[3]s.GetDateStyle()
> 		_d, _, err := pgdate.ParseDate(_now, _dateStyle, string(%[2]s), &evalCtx.ParseHelper)
> ```

nit: replace `evalCtx` with `%[3]s` as we do for `_now` and `_dateStyle`. The rationale is trying to keep the templating more flexible (although in this case the flexibility is probably not worth it since I don't foresee us generating multiple files based on `cast_tmpl`, still it's better for consistency sake).
___
*[`pkg/sql/sem/tree/datum.go` line 2008 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/92252#-NHVCp6UD6Rm2i61N6lr:-NHVCp6UD6Rm2i61N6ls:bgxdl6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/f12108bcd2e307bc7e209513a335564f2225d531/pkg/sql/sem/tree/datum.go#L2008)):*
> ```Go
> 	// GetDateStyle returns the date style in the session.
> 	GetDateStyle() pgdate.DateStyle
> 	// GetParseHelper returns a helper to optmize date parsing
> ```

nit: missing period.
___
*[`pkg/util/timeutil/pgdate/field_extract.go` line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92252#-NHVBT9Y2xEtb6b6Ewag:-NHVBT9Z9WqpAFJlDBL6:b-jy77pn) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ec6df9efdbec52ac8df0b318b57b31d5d770774/pkg/util/timeutil/pgdate/field_extract.go#L78)):*
> ```Go
> 	// This indicates that the value in the year field was only
> 	// two digits and should be adjusted to make it recent.
> 	tweakYear bool
> ```

nit: I'm assuming that the fields are re-arranged to get the object size under some threshold. Consider adding an assertion in `init()` method that verifies that the size doesn't exceed that threshold.

**Review by cucaroach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92252)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan and @yuzefovich)

___
*[`pkg/util/timeutil/pgdate/field_extract.go` line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92252#-NHVBT9Y2xEtb6b6Ewag:-NHW3O249D5uxQoO0xI2:b-o7yzwx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ec6df9efdbec52ac8df0b318b57b31d5d770774/pkg/util/timeutil/pgdate/field_extract.go#L78)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I'm assuming that the fields are re-arranged to get the object size under some threshold. Consider adding an assertion in `init()` method that verifies that the size doesn't exceed that threshold.
</blockquote></details>

Seems like overkill, I just wanted to save 16 bytes by collapsing bools, it probably didn't move the needle, just seemed like a good idea.

**Review by otan — APPROVED** [review]

**Comment by cucaroach** [comment]
TFTRs!
bors r+

**Pull request merged**
