### PR TITLE
colexec: run logic test of batch size 1

### LINKED ISSUE #46185: colexec: run logictests with batch size of 1
Since data sets are usually relatively small in logictests, most of the time operators will only use a single batch. Running logic tests with a batch size of 1 will artificially simulate what operators will do when running large queries (i.e. with large amounts of data) and stress e.g. correct batch reuse.

### PR DESCRIPTION
**Pull request by Azhng**
Previously, we run logic test of vectorize engine with default
batch size. This is difficult to expose bugs that caused by
improper batch reuse.
By reducing the batch size to 1 in logic test simulates large
input size for vectorize engine.

Closes #46185

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
I would randomly choose to either reduce it or not so it gets tested both ways. Single row batches virtually eliminate testing of any intra-batch logic/handling.

BTW this needs a rebase.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46881)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/sql/logictest/logic.go, line 987 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46881#-M4FQk4l49wLsGngbGPO:-M4FQk4l49wLsGngbGPP:bhrkcl5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b14a94520c33dc61b2df274184d65db3562b2f5/pkg/sql/logictest/logic.go#L987)):*
> ```Go
> 	// overridingVectorizeBatchSize indicates whether or not the
> 	// logic test is going to be run with batch size set to 1.
> 	overridingVectorizeBatchSize bool
> ```

I feel like this should not be a separate variable on `testClusterConfig`.
___
*[pkg/sql/logictest/logic.go, line 1266 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46881#-M4FRQ0D3zIOp343afuF:-M4FRQ0D3zIOp343afuG:b4i4a42) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b14a94520c33dc61b2df274184d65db3562b2f5/pkg/sql/logictest/logic.go#L1266)):*
> ```Go
> 		}
> 	}
> 	if t.overridingVectorizeBatchSize {
> ```

I think we should check whether `cfg.overrideVectorize` is not `off` since there is no point in randomizing batch size for that config.

Also, I would actually make a random decision whether to override the batch size here (and would log this here as well). Additionally, I think we would benefit from overriding to a small size other than 1, so maybe something like:
0.5 probability - no override
0.25 probability - override to 1
0.25 probability - override to random value in (2, 3).
___
*[pkg/sql/logictest/logic.go, line 1268 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46881#-M4FRGVO32OMgGhwxCzd:-M4FRGVO32OMgGhwxCze:bidczej) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b14a94520c33dc61b2df274184d65db3562b2f5/pkg/sql/logictest/logic.go#L1268)):*
> ```Go
> 	if t.overridingVectorizeBatchSize {
> 		if _, err := t.cluster.ServerConn(0).Exec(
> 			"SET CLUSTER SETTING sql.testing.vectorize.batch_size to 1",
> ```

Huh, I didn't know you could do `SET <some setting> to ...`, TIL.

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46881)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/logictest/logic.go, line 987 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46881#-M4FQk4l49wLsGngbGPO:-M4FhpFC-OEOU1Qvse8B:b9ki73i) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b14a94520c33dc61b2df274184d65db3562b2f5/pkg/sql/logictest/logic.go#L987)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I feel like this should not be a separate variable on `testClusterConfig`.
</blockquote></details>

This variable is stored inside `logicTest` struct. What do you suggest alternatively ? 

(also changed this variable to `randomizeVectorizeBatchSize` and the type from `bool` to `int`) 
___
*[pkg/sql/logictest/logic.go, line 1266 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46881#-M4FRQ0D3zIOp343afuF:-M4FinwYBKTkj6t2f_Zb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b14a94520c33dc61b2df274184d65db3562b2f5/pkg/sql/logictest/logic.go#L1266)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think we should check whether `cfg.overrideVectorize` is not `off` since there is no point in randomizing batch size for that config.

Also, I would actually make a random decision whether to override the batch size here (and would log this here as well). Additionally, I think we would benefit from overriding to a small size other than 1, so maybe something like:
0.5 probability - no override
0.25 probability - override to 1
0.25 probability - override to random value in (2, 3).
</blockquote></details>

Done.
___
*[pkg/sql/logictest/logic.go, line 1268 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46881#-M4FRGVO32OMgGhwxCzd:-M4FhmILBlwpm3sEUntm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b14a94520c33dc61b2df274184d65db3562b2f5/pkg/sql/logictest/logic.go#L1268)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Huh, I didn't know you could do `SET <some setting> to ...`, TIL.
</blockquote></details>

Done.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46881)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @yuzefovich)

___
*[pkg/sql/logictest/logic.go, line 987 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46881#-M4FQk4l49wLsGngbGPO:-M4FnOr17zrWzJeF1ERh:bkgcl7z) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b14a94520c33dc61b2df274184d65db3562b2f5/pkg/sql/logictest/logic.go#L987)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

This variable is stored inside `logicTest` struct. What do you suggest alternatively ? 

(also changed this variable to `randomizeVectorizeBatchSize` and the type from `bool` to `int`) 
</blockquote></details>

I suggest removing this variable entirely, then moving new code that is currently in `RunLogicTest` into `if strings.Compare(cfg.overrideVectorize, "off") != 0 {` block within `setup` function, right before we're setting the cluster setting. Is this not possible for some reason?

I'm thinking something like this:
```
	if strings.Compare(cfg.overrideVectorize, "off") != 0 {
		// Determining whether or not to randomize vectorize batch size.
		rng, _ := randutil.NewPseudoRand()
		randVal := rng.Float64()
		randomizedVectorizeBatchSize := coldata.BatchSize()
		if randVal < 0.25 {
			randomizedVectorizeBatchSize = 1
		} else if randVal < 0.375 {
			randomizedVectorizeBatchSize = 2
		} else if randVal < 0.5 {
			randomizedVectorizeBatchSize = 3
		}
		if _, err := t.cluster.ServerConn(0).Exec(
			fmt.Sprintf("SET CLUSTER SETTING sql.testing.vectorize.batch_size to %d",
				t.randomizeVectorizeBatchSize),
		); err != nil {
			t.Fatal(err)
		}
		t.t().Log(fmt.Sprintf("randomize batchSize to %d\n", t.randomizeVectorizeBatchSize))
	}
```

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46881)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/logictest/logic.go, line 987 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46881#-M4FQk4l49wLsGngbGPO:-M4FpD6OB2RHbY3n7Z7z:briolpc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b14a94520c33dc61b2df274184d65db3562b2f5/pkg/sql/logictest/logic.go#L987)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I suggest removing this variable entirely, then moving new code that is currently in `RunLogicTest` into `if strings.Compare(cfg.overrideVectorize, "off") != 0 {` block within `setup` function, right before we're setting the cluster setting. Is this not possible for some reason?

I'm thinking something like this:
```
	if strings.Compare(cfg.overrideVectorize, "off") != 0 {
		// Determining whether or not to randomize vectorize batch size.
		rng, _ := randutil.NewPseudoRand()
		randVal := rng.Float64()
		randomizedVectorizeBatchSize := coldata.BatchSize()
		if randVal < 0.25 {
			randomizedVectorizeBatchSize = 1
		} else if randVal < 0.375 {
			randomizedVectorizeBatchSize = 2
		} else if randVal < 0.5 {
			randomizedVectorizeBatchSize = 3
		}
		if _, err := t.cluster.ServerConn(0).Exec(
			fmt.Sprintf("SET CLUSTER SETTING sql.testing.vectorize.batch_size to %d",
				t.randomizeVectorizeBatchSize),
		); err != nil {
			t.Fatal(err)
		}
		t.t().Log(fmt.Sprintf("randomize batchSize to %d\n", t.randomizeVectorizeBatchSize))
	}
```
</blockquote></details>

The issue here is that each logic test will potentially have a different batch size. All in-memory test clusters we spin up for each logic test ***shares*** the `coldata.BatchSize` variable. 
When we run the logic tests in parallel each logic test will race to set the `coldata.BatchSize` variable and this can cause very weird issues such as index out of bound in some unexpected places. Since the batch size can change when some other operators are still in the middle of running.
Personally I think the solution here is to ensure that the entire logic test suite to run with a consistent batch size such that such interference is totally avoided.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46881#-:-M4FvfcE99SlaOmiitc6:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/sql/logictest/logic.go, line 987 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46881#-M4FQk4l49wLsGngbGPO:-M4FufF-BOsfUIno5UgK:b-ac77g) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b14a94520c33dc61b2df274184d65db3562b2f5/pkg/sql/logictest/logic.go#L987)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

The issue here is that each logic test will potentially have a different batch size. All in-memory test clusters we spin up for each logic test ***shares*** the `coldata.BatchSize` variable. 
When we run the logic tests in parallel each logic test will race to set the `coldata.BatchSize` variable and this can cause very weird issues such as index out of bound in some unexpected places. Since the batch size can change when some other operators are still in the middle of running.
Personally I think the solution here is to ensure that the entire logic test suite to run with a consistent batch size such that such interference is totally avoided. 
</blockquote></details>

Oh yeah, makes sense.
___
*[pkg/sql/logictest/logic.go, line 986 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46881#-M4FuoSC-9WZbaFKXjXX:-M4FuoSC-9WZbaFKXjXY:be9aigv) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1f07eab66af1534e079916641fe37b4426f2918/pkg/sql/logictest/logic.go#L986)):*
> ```Go
> 	curLineNo int
> 
> 	// randomizedVectorizeBatchSize stores the randomized batch size for vectorize
> ```

nit: `s/Vectorize/Vectorized/g` and `s/vectorize/vectorized/g`.
___
*[pkg/sql/logictest/logic.go, line 987 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46881#-M4Fus_j23y0RWj6rKBd:-M4Fus_j23y0RWj6rKBe:b-cllzsn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1f07eab66af1534e079916641fe37b4426f2918/pkg/sql/logictest/logic.go#L987)):*
> ```Go
> 
> 	// randomizedVectorizeBatchSize stores the randomized batch size for vectorize
> 	// engine if it not turned off. The batch size will randomly be set to
> ```

nit: `s/it not/it is not/g`.
___
*[pkg/sql/logictest/logic.go, line 990 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46881#-M4Fv89p00za4YJM6fFU:-M4Fv89p00za4YJM6fFV:bgv6rad) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1f07eab66af1534e079916641fe37b4426f2918/pkg/sql/logictest/logic.go#L990)):*
> ```Go
> 	// 1 with 25% probability, {2, 3} with 25% probability or default batch size
> 	// with 50% probability.
> 	randomizeVectorizeBatchSize int
> ```

nit: `s/randomizeVectorizeBatchSize/randomizedVectorizedBatchSize/g`.

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46881)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[pkg/sql/logictest/logic.go, line 987 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46881#-M4FQk4l49wLsGngbGPO:-M4G13xLEpAyg1wRy65-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b14a94520c33dc61b2df274184d65db3562b2f5/pkg/sql/logictest/logic.go#L987)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Oh yeah, makes sense.
</blockquote></details>

Done.

**Pull request merged**
