### PR TITLE
workload/sqlsmith: properly extract the table schema

### LINKED ISSUE #51578: ccl/workloadccl/allccl: TestAllRegisteredSetup failed
[(ccl/workloadccl/allccl).TestAllRegisteredSetup failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2098784&tab=buildLog) on [master@d79679f3e4e86d3f85c60f5431b8d5874a95735e](https://github.com/cockroachdb/cockroach/commits/d79679f3e4e86d3f85c60f5431b8d5874a95735e):

```
=== RUN   TestAllRegisteredSetup/bank
    TestAllRegisteredSetup/bank: test_log_scope.go:77: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestAllRegisteredSetup_bank262355168
    TestAllRegisteredSetup/bank: test_log_scope.go:58: use -show-logs to present logs inline


ERROR: signal: segmentation fault (core dumped)

5 runs completed, 1 failures, over 1m0s
context canceled

```

<details><summary>More</summary><p>
Parameters:

- TAGS=
- GOFLAGS=-parallel=4

```
make stressrace TESTS=TestAllRegisteredSetup PKG=./pkg/ccl/workloadccl/allccl TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestAllRegisteredSetup.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

Jira issue: CRDB-4030

### PR DESCRIPTION
**Pull request by knz**
Fixes #51578.
Epic: CRDB-28893

The workload tests want the SQL for the table schema excluding the initial `CREATE TABLE "xxx"`. Previously, the sqlsmith code was extracting the table definition by truncating the string at the first `(` encountered. This obviously won't do if the table name itself contains a `(` too. This patch fixes it.

Release note: None

### CODE REVIEW

**Review by cucaroach — APPROVED** [review]
:lgtm:

**Comment by knz** [comment]
TFYR!

bors r=cucaroach

**Comment by msbutler** [comment]
@knz is it easy to backport this 23.1? just hit it here [TestAllRegisteredSetup/sqlsmith](https://teamcity.cockroachdb.com/viewLog.html?buildId=9347123&buildTypeId=Cockroach_BazelEssentialCi#testNameId5757413372086760171)

**Comment by knz** [comment]
blathers backport 23.1

**Pull request merged**
