### PR TITLE
wip: computeRaftLogSizeDelta

### PR DESCRIPTION
**Pull request by andreimatei**
Release note: None

### CODE REVIEW

**Comment by andreimatei** [comment]
@tbg @petermattis is this how one computes the size of the Raft log?

I have yet to see exactly when to trigger this computation; that's not done yet.

@tbg you've asked to not grab `raftMu` (and accept a potentially incorrect size computation) and I can do that if you want, but thought I'd check with concrete code, cause it seems harmless to me...

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34753)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/storage/replica_raft.go, line 2394 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34753#-LYDm6IP9GFrLKumlfKR:-LYDm6IP9GFrLKumlfKS:b-oeizlg) ([raw file](https://github.com/cockroachdb/cockroach/blob/dad271b7f62270c7b559c911452a38eb17a16423/pkg/storage/replica_raft.go#L2394)):*
> ```Go
> 	startKey := keys.MakeRangeIDPrefixBuf(r.RangeID).RaftLogPrefix()
> 	endKey := startKey.PrefixEnd()
> 	r.raftMu.Lock()
> ```

I don't think you need to hold `raftMu` here. `readOnlyCmdMu.RLock` should be sufficient, though maybe things get funky if there is a current write. 
___
*[pkg/storage/replica_raft.go, line 2395 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34753#-LYDludO-_wf0U7c3mGE:-LYDludO-_wf0U7c3mGF:by06245) ([raw file](https://github.com/cockroachdb/cockroach/blob/dad271b7f62270c7b559c911452a38eb17a16423/pkg/storage/replica_raft.go#L2395)):*
> ```Go
> 	endKey := startKey.PrefixEnd()
> 	r.raftMu.Lock()
> 	iter := r.Engine().NewSnapshot().NewIterator(
> ```

Every snapshot needs to be closed. Also, you don't need a snapshot if you're just going to create an iterator as the iterator holds an implicit snapshot.
___
*[pkg/storage/replica_raft.go, line 2407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34753#-LYDm_JcAZMQbGrrqocc:-LYDm_JcAZMQbGrrqocd:bgag3tr) ([raw file](https://github.com/cockroachdb/cockroach/blob/dad271b7f62270c7b559c911452a38eb17a16423/pkg/storage/replica_raft.go#L2407)):*
> ```Go
> 		engine.MakeMVCCMetadataKey(startKey),
> 		engine.MakeMVCCMetadataKey(endKey),
> 		0 /* nowNanos */)
> ```

I'm not sure if it is correct to use `ComputeStats` like this. It might be, but you'll have to double-check with testing code. If this works, this is fairly ideal as `Iterator.ComputeStats` is implemented on C++ and very fast.

**Comment by tbg** [comment]
Unfortunately, it's really difficult to get these stats correct efficiently due to sideloading. You're computing the entries actually stored under Raft log keys, but the raftLogSize also tries to account for the SSTs that reside on disk (most of the time; they can also be inlined). For example, when we apply a snapshot:

https://github.com/cockroachdb/cockroach/blob/d0aa09e6afc802ee9d02f367925220c0e1f9a0aa/pkg/storage/replica_raftstorage.go#L892-L911

And when we apply entries "normally": https://github.com/cockroachdb/cockroach/blob/965525a5deb3c4fab5ab232e069846ecc08f632d/pkg/storage/replica_raft.go#L651-L663

On the other hand we don't account for sideloading at all when we reduce (i.e. truncate the log):

https://github.com/cockroachdb/cockroach/blob/d0aa09e6afc802ee9d02f367925220c0e1f9a0aa/pkg/storage/batcheval/cmd_truncate_log.go#L103-L131

The reason we track sideloaded size (well, one of them) is that they get inlined into the Raft log in snapshots. We're going to stop sending historical log entries in snaps soon, and while there could still be too much data in the non-historical range `[applied+1, lastIndex)` it's less likely. Plus, our considerations for scalability dictate that we allow larger snapshots than today, and the infra for it is mostly in place. So I would say that more complexity to address this case is not warranted.

On the other hand, if we're not worried about snapshots, then all we want is to make sure that the raft log eventually gets truncated (ideally sooner rather than later). I think we can achieve that more easily without all of the queue coordination:

1. remove the queue and instead make truncation decisions locally
2. keep the raft log size around, but account only for in-memory contributions (much easier to track)
3. ditto sideloaded size
4. never subtract from these; they're either added to or recomputed (this makes this system much more resilient to bugs, and also simpler to understand)
3. on quiesce, if there's anything that can be truncated, truncate it (a truncation now is just a local engine write; no Raft necessary)
4. when raft log gets "too long" or in-mem > X or sideloaded > Y, consider a truncation (on the followers it will happen, on the leader we use heuristics similar to today's raft log queue)
5. a truncation also recomputes the counters.

**Comment by tbg** [comment]
Actually the truncation does take into account the sideloading:

**Comment by tbg** [comment]
(I also have a bit of an agenda here -- #34287 actually makes it impossible to keep the stats synced as they are now because followers will have different prefixes of the log) unless we already introduce recomputations)

**Comment by andreimatei** [comment]
Hold up, I'm not sure I follow everything you're saying.

About the sideload data: it seems to me that we want to account for it in the "size of the raft log", right? At least for log entries that were already applied, their sideloaded SSTs are logically part of the entries and should be deleted when the log is truncated, right? I'm not sure about SSTs for which the corresponding log entry has not been applied yet. And in fact I'm also confused about log entries that have not yet been applied. Those exist, right? How are they accounted 
for? Are they included in `r.mu.raftLogSize`?

What are the "in-memory contributions" in:
"keep the raft log size around, but account only for in-memory contributions (much easier to track)" ?

It seems to me that maybe we should table this discussion and PR until #34287. I'm starting to believe we won't backport anything here, and #34287 might change things. What do you think?

**Comment by tbg** [comment]
I agree on tabling, I'm already finding myself looking at that issue and
seeing the problem I mentioned in the tests. I'll follow up on your
questions tomorrow.

**Pull request closed without merging**
