### PR TITLE
kv: route present-time reads to global_read follower replicas

### PR DESCRIPTION
**Pull request by nvb**
This commit updates the kv client routing logic to account for the new `LEAD_FOR_GLOBAL_READS` `RangeClosedTimestampPolicy` added in #59505. In enterprise builds, non-stale read-only requests to ranges with this closed timestamp policy can now be routed to follower replicas, just like stale read-only requests to normal ranges currently are.

In addition to this main change, there are a few smaller changes in this PR that were hard to split out, so are included in this commit.

First, non-transactional requests are no longer served by followers even if the follower replica detects that the request can be. Previously, non-transactional requests would never be routed intentionally to a follower replica, but `Replica.canServeFollowerRead` would allow them through if their timestamp was low enough. This change was made in order to keep the client and server logic in-sync and because this does not seem safe for non-transactional requests that get their timestamp assigned on the server. We're planning to remove non-transactional requests soon anyway (#58459), so this isn't a big deal. It mostly just caused some testing fallout.

Second, transactional requests that had previously written intents are now allowed to have their read-only requests served by followers, as long as those followers have a closed timestamp above the transaction's read *and* write timestamp. Previously, we had avoided this because it seemed to cause issues with read-your-writes. However, it appears safe as long as the write timestamp is below the closed timestamp, because we know all of the transaction's intents are at or below its write timestamp. This is very important for multi-region work, where we want a transaction to be able to write to a REGIONAL table and then later perform local reads (maybe foreign key checks) on GLOBAL tables.

Third, a max clock offset shift in `canUseFollowerRead` was removed. It wasn't exactly clear what this was doing. It was introduced in the original 70be833 and seemed to allow a follower read in cases where they otherwise shouldn't be expected to succeed. I thought at first that it was accounting for the fact that the kv client's clock might be leading the kv server's clock and so it was being pessimistic about the expected closed timestamp, but it actually seems to be shifting the other way, so I don't know. I might be missing something.

Finally, the concept of a `replicaoracle.OracleFactoryFunc` was removed and the existing `replicaoracle.OracleFactory` takes its place. We no longer need the double-factory approach because the transaction object is now passed directly to `Oracle.ChoosePreferredReplica`. This was a necessary change, because the process of determining whether a follower read can be served now requires transaction information and range information (i.e. the closed timestamp policy), so we need to make it in the Oracle itself instead of in the OracleFactory. This all seems like a simplification anyway.

This is still waiting on changes to the closed timestamp system to be able to write end-to-end tests using this new functionality.

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm_strong: :rocket: :rocket: 

> Reviewed 18 of 18 files at r1, 17 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-:-MSDsNVh2kZy1lEI5kVo:b-w1mwjx)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MSDrrc87KNLkOZ0bGPT:-MSDrrc989Go37FxtxWi:bf78x9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/11a7493ed651b8cb22a506a1f234e584ea894c3b/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go#L97)):*
> ```Go
> }
> 
> // closedTimestampLikelySufficient determines if a request at a given timestamp
> ```

much clearer 
___
*[pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go, line 265 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MSDsDByDXlR_qTeMAiC:-MSDsDByDXlR_qTeMAiD:b-8f656o) ([raw file](https://github.com/cockroachdb/cockroach/blob/11a7493ed651b8cb22a506a1f234e584ea894c3b/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go#L265)):*
> ```Go
> 
> // TestOracle tests the OracleFactory exposed by this package.
> func TestOracleFactory(t *testing.T) {
> ```

nit: `TestOracle` and comment

**Review by aayushshah15 — COMMENTED** [review]
> Reviewed 1 of 19 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59571)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go, line 89 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTDy-MBBbYZwZWzl3O7:-MTDy-MBBbYZwZWzl3O8:b-iyp4k5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go#L89)):*
> ```Go
> 		return 0, err
> 	}
> 	return getFollowerReadLag(st), nil
> ```

Should we add a comment here (or near the `follower_read_timestamp()` builtin definition)  mentioning that `AS OF SYSTEM TIME follower_read_timestamp()` will always return a negative offset regardless of whether the range(s) serving the query close timestamps in the past?
___
*[pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go, line 99 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTEIl8w8ycZ63mFhmtN:-MTEIl8w8ycZ63mFhmtO:b53cpr3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go#L99)):*
> ```Go
> 
> // closedTimestampLikelySufficient determines if a request at a given timestamp
> // is likely to be below a follower's closed timestamp and servicable as a
> ```

`s/servicable/serviceable`
___
*[pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go, line 117 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTE4JEN-yjdx2vlJMhs:-MTE4JEN-yjdx2vlJMht:b-s7cmpi) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go#L117)):*
> ```Go
> 	}
> 	expectedClosedTS := clock.Now().Add(offset.Nanoseconds(), 0)
> 	return maxObservableTS.LessEq(expectedClosedTS)
> ```

Until this point, I was under the impression that historical queries (via `AOST`) don't have a notion of uncertainty and that they can observe causal inversion. However, I see that both this and the previous implementation were accounting for the max-offset here. Is this so we preserve linearizability for long running txns?
___
*[pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go, line 313 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTE-4FY0K69QRE26RYB:-MTE-4FZ4xWTC4lILXiI:b-x2b49i) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go#L313)):*
> ```Go
> 	setLatency("3", 80*time.Millisecond)
> 
> 	testCases := []struct {
> ```

The test is very cool!
___
*[pkg/roachpb/data.go, line 932 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTDbfn_CGOqjEELMwME:-MTDbfn_CGOqjEELMwMF:bwrng4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/roachpb/data.go#L932)):*
> ```Go
> 	//
> 	// There is a case where an intent written by a transaction is above the
> 	// transactions write timestamp — after a successful intent push. Such cases
> ```

minor nit: `transaction's`
___
*[pkg/roachpb/data.go, line 937 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTEJeCwDXGPo0oTGQMd:-MTEJeCx99olTeSvxybO:b-8szm6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/roachpb/data.go#L937)):*
> ```Go
> 	//
> 	// WIP: something about how the intent will be present on followers with a
> 	// sufficiently high closed timestamp, either in its pre or post push state.
> ```

I was really confused about how reading an intent in its post-push state on a follower would be correct until I found: https://github.com/cockroachdb/cockroach/blob/d67299e08975b50c5c73c997ee3144674326f439/pkg/storage/pebble_mvcc_scanner.go#L441-L444

It might just be because I'm unfamiliar with this stuff but do you think we should point to something like this from here?

However, if own-intents are the only reason we're `Forward`ing by `WriteTimestamp`, then I wonder if we can just do without it. It seems like it only "hurts" us by making follower-reads less likely. Am I misunderstanding something?

**Comment by aayushshah15** [comment]
___
*[pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go, line 117 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTE4JEN-yjdx2vlJMhs:-MTEiNTG30ZL9TeQ0oxW:b-mcph0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go#L117)):*
> I thought at first that it was accounting for the fact that the kv client's clock might be leading the kv server's clock and so it was being pessimistic about the expected closed timestamp, but it actually seems to be shifting the other way, so I don't know.

Oh, I missed this before. The previous implementation seems to be shifting the wrong(?) way.

**Review by andreimatei — COMMENTED** [review]
> First, non-transactional requests are no longer served by followers even if the follower replica detects that the request can be. Previously, non-transactional requests would never be routed intentionally to a follower replica, but Replica.canServeFollowerRead would allow them through if their timestamp was low enough. This change was made in order to keep the client and server logic in-sync and because this does not seem safe for non-transactional requests that get their timestamp assigned on the server. 

Why do you say this isn't safe for requests that get their timestamp on the server? I understand that these request don't have an uncertainty interval (so I don't understand how they're linearizable at all) but why does it matter who assigns the timestamp?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-:-MTLwBnCExTgjwvgNQIG:bx7lo0l)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-:-MTM2AC1ERZVkuKhxlg9:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, and @nvanbenschoten)

___
*[pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go, line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTLxcGqCIgYORWxPbj3:-MTLxcGqCIgYORWxPbj4:brcg8st) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go#L98)):*
> ```Go
> }
> 
> // closedTimestampLikelySufficient determines if a request at a given timestamp
> ```

I'd make it a point of explaining that the decision is range-specific, and introduce `ctPolicy`. Maybe name `ctPolicy -> range[Ct]Policy`.
___
*[pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go, line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTLxx4E7KLU27pG9tVW:-MTLxx4E7KLU27pG9tVX:by6zux0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go#L98)):*
> ```Go
> }
> 
> // closedTimestampLikelySufficient determines if a request at a given timestamp
> ```

Also, the comment talks about :a request at a given ts", but the function takes a "maxObservableTS" which we generally don't call "the request's timestamp". Consider adding some words here, explaining that it's not the "request's timestamp" that matters, but this other thing.
___
*[pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go, line 106 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTLzO_t6FC2Bhwpw8Uk:-MTLzO_t6FC2Bhwpw8Ul:b-gl7y34) ([raw file](https://github.com/cockroachdb/cockroach/blob/81a2c26a104fa8cc7e8b530b837ffb6ff85ddc5a/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go#L106)):*
> ```Go
> // canSendToFollower implements the logic for checking whether a batch request
> // may be sent to a follower.
> // TODO(aayush): We should try to bind clusterID to the function here, rather
> ```

this todo is in the wrong place, but deleting it is just a slap in the face :)
___
*[pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go, line 117 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTE4JEN-yjdx2vlJMhs:-MTLydks0dZtVqfVf2mP:b-ivjvzs) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go#L117)):*
> Until this point, I was under the impression that historical queries (via AOST) don't have a notion of uncertainty and that they can observe causal inversion

You're still under this impression, right?
___
*[pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go, line 123 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTLx63j8kpY7GLQrEHV:-MTLx63j8kpY7GLQrEHW:bq7p68f) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go#L123)):*
> ```Go
> // may be sent to a follower.
> func canSendToFollower(
> 	clusterID uuid.UUID,
> ```

if you're interested, consider taking the opportunity (perhaps different patch) to bind this damn `clusterID`
___
*[pkg/roachpb/data.go, line 912 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTM-mRu9ADYUuGFB6P9:-MTM-mRu9ADYUuGFB6PA:b3oi3vz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/roachpb/data.go#L912)):*
> ```Go
> func (t Transaction) LastActive() hlc.Timestamp {
> 	ts := t.LastHeartbeat
> 	// Only forward by the ReadTimestamp if it is a clock timestamp.
> ```

nit: this comment is useless now that the todo is gone; delete it
___
*[pkg/roachpb/data.go, line 920 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTM00qP6aIJtLHX-f0F:-MTM00qP6aIJtLHX-f0G:b-cfe19r) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/roachpb/data.go#L920)):*
> ```Go
> 
> // MaxObservableTimestamp returns the largest timestamp at which the transaction
> // may observe when performing a read-only operation. This is the maximum of the
> ```

nit: "may observe" is weird because it sounds like "transactions observing" is a term of art. Maybe "read values".
___
*[pkg/roachpb/data.go, line 923 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTM0alNEZ8IvVf6P-J3:-MTM0alNEZ8IvVf6P-J4:b27erb7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/roachpb/data.go#L923)):*
> ```Go
> // transaction's read timestamp, its write timestamp, and its global uncertainty
> // limit.
> func (t Transaction) MaxObservableTimestamp() hlc.Timestamp {
> ```

you sure you don't want a pointer receiver on this? And maybe on other methods around, but that can wait.
___
*[pkg/roachpb/data.go, line 934 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTM1R8b6ajroypQCufV:-MTM1R8b6ajroypQCufW:b3lfsy3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/roachpb/data.go#L934)):*
> ```Go
> 	// transactions write timestamp — after a successful intent push. Such cases
> 	// do allow a transaction to operate above its max observable timestamp.
> 	// However, this is fine...
> ```

don't forget to expand on the "this is fine".
___
*[pkg/roachpb/data.go, line 937 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTEJeCwDXGPo0oTGQMd:-MTM16PNDl1IWzcGYfOV:bosvtnk) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/roachpb/data.go#L937)):*
> However, if own-intents are the only reason we're Forwarding by WriteTimestamp, then I wonder if we can just do without it. It seems like it only "hurts" us by making follower-reads less likely. Am I misunderstanding something?

Well but how are you suggesting we make sure we read our own writes when going to a follower?
___
*[pkg/roachpb/data.go, line 938 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTM1I2QB64FWhEY0VxD:-MTM1I2QB64FWhEY0VxE:bbi0rz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/roachpb/data.go#L938)):*
> ```Go
> 	// WIP: something about how the intent will be present on followers with a
> 	// sufficiently high closed timestamp, either in its pre or post push state.
> 	// Either works. Do we need to change the contract of MaxObservableTimestamp
> ```

yeah, `MaxObservable` seems to not describe this well (and I personally didn't really like the name to begin with). How about... `RequiredFrontier`?

**Review by andreimatei — COMMENTED** [review]
Random question - do we route batches with `QueryIntent` in them to followers?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-:-MTM2xwf-bd9RbOn6dUE:b-b4531z)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, and @nvanbenschoten)

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59571)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, and @nvanbenschoten)

___
*[pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go, line 117 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTE4JEN-yjdx2vlJMhs:-MTMkVlY4ah1z9CE0UB7:b-ryyp40) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go#L117)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> Until this point, I was under the impression that historical queries (via AOST) don't have a notion of uncertainty and that they can observe causal inversion

You're still under this impression, right?
</blockquote></details>

Yes. So would it be worth it to plumb a flag down here and disregard the max offset if the request was sent from an `AOST` query? 

If not, we could just spell out the reasoning for accounting for the max-offset in a comment here.
___
*[pkg/roachpb/data.go, line 937 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTEJeCwDXGPo0oTGQMd:-MTMgfo-1kb8X1o2XBvY:bn04n33) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/roachpb/data.go#L937)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> However, if own-intents are the only reason we're Forwarding by WriteTimestamp, then I wonder if we can just do without it. It seems like it only "hurts" us by making follower-reads less likely. Am I misunderstanding something?

Well but how are you suggesting we make sure we read our own writes when going to a follower?
</blockquote></details>

OK, I think I understand. Without `Forward`ing to the `WriteTimestamp`, we can't guarantee that an intent is even present on the follower replica serving the request.

**Review by nvb — COMMENTED** [review]
TFTRs!

> Why do you say this isn't safe for requests that get their timestamp on the server? I understand that these request don't have an uncertainty interval (so I don't understand how they're linearizable at all) but why does it matter who assigns the timestamp?

Because if it isn't the leaseholder who is assigning the timestamp then the replica's clock may trail the commit timestamp of a write with a happens-before relation to the read. This is all kind of broken though. See #58459.

> do we route batches with QueryIntent in them to followers?

Discussed offline. We currently don't because we take a fairly pessimistic view of what can happen during async consensus. We assume that an in-flight write can be pushed to a higher timestamp between the time that pipelining begins and when the intent first "lands". And so we don't use a similar argument to the one we're using in `RequiredFrontier` to guarantee read-your-writes.

I think this is probably too pessimistic of a view and it may be ok to route QueryIntent requests to followers if we loosen its semantics a little bit. But that isn't needed here, so I'll defer that investigation.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-:-MTmCvcT2Yoeqs9kYJFj:b-vov3k)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @ajwerner, and @andreimatei)

___
*[pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go, line 89 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTDy-MBBbYZwZWzl3O7:-MTmEi0h6tLBlurPFRos:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go#L89)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Should we add a comment here (or near the `follower_read_timestamp()` builtin definition)  mentioning that `AS OF SYSTEM TIME follower_read_timestamp()` will always return a negative offset regardless of whether the range(s) serving the query close timestamps in the past?
</blockquote></details>

Done.
___
*[pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go, line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTLxcGqCIgYORWxPbj3:-MTmEpbw7YN0AV3uOMGI:berp5qm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go#L98)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'd make it a point of explaining that the decision is range-specific, and introduce `ctPolicy`. Maybe name `ctPolicy -> range[Ct]Policy`.
</blockquote></details>

You don't think the name of the type makes that clear enough?
___
*[pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go, line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTLxx4E7KLU27pG9tVW:-MTmJENv3dexLGUkVQGB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go#L98)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Also, the comment talks about :a request at a given ts", but the function takes a "maxObservableTS" which we generally don't call "the request's timestamp". Consider adding some words here, explaining that it's not the "request's timestamp" that matters, but this other thing.
</blockquote></details>

Done.
___
*[pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go, line 99 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTEIl8w8ycZ63mFhmtN:-MTmF-9GDul2dsPoUVO1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go#L99)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

`s/servicable/serviceable`
</blockquote></details>

Done.
___
*[pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go, line 106 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTLzO_t6FC2Bhwpw8Uk:-MTmFgcf2BMZYIcH4kdt:b-jc74ns) ([raw file](https://github.com/cockroachdb/cockroach/blob/81a2c26a104fa8cc7e8b530b837ffb6ff85ddc5a/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go#L106)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

this todo is in the wrong place, but deleting it is just a slap in the face :)
</blockquote></details>

:wave: 

I don't see anything better we can do. `utilccl.CheckEnterpriseEnabled` requires a cluster ID. Hiding it in some object and then turning these static functions into methods just makes things even less clear.
___
*[pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go, line 117 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTE4JEN-yjdx2vlJMhs:-MTmF4uJ2L8bMOiLRVI-:b-3llv84) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go#L117)):*
A request sent with AOST will have no uncertainty interval, that's correct. That will be reflected in the transaction's `GlobalUncertaintyLimit`, which will be equal to its `ReadTimestamp`. So we don't need to plumb anything else down here.

> The previous implementation seems to be shifting the wrong(?) way.

That's what it looks like. It confused me too.

> If not, we could just spell out the reasoning for accounting for the max-offset in a comment here.

We aren't accounting for max offset here anymore. This is now handled in `RequiredFrontier`.
___
*[pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go, line 123 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTLx63j8kpY7GLQrEHV:-MTmG0nn39oZMuJxuQ5N:batpsfx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go#L123)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

if you're interested, consider taking the opportunity (perhaps different patch) to bind this damn `clusterID`
</blockquote></details>

Bind it to what? I don't love this, but I don't like introducing some pointless object even more. It just adds even more noise. Functions are at least easy to test and this doesn't get plumbed too far.
___
*[pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go, line 265 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MSDsDByDXlR_qTeMAiC:-MTmGR5N19dM8nzOSOMt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/11a7493ed651b8cb22a506a1f234e584ea894c3b/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go#L265)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: `TestOracle` and comment
</blockquote></details>

Done.
___
*[pkg/roachpb/data.go, line 912 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTM-mRu9ADYUuGFB6P9:-MTmGXgPANrpvru70YCJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/roachpb/data.go#L912)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: this comment is useless now that the todo is gone; delete it
</blockquote></details>

Done.
___
*[pkg/roachpb/data.go, line 920 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTM00qP6aIJtLHX-f0F:-MTmHSXa87NEwkB8Q2j4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/roachpb/data.go#L920)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: "may observe" is weird because it sounds like "transactions observing" is a term of art. Maybe "read values".
</blockquote></details>

Done.
___
*[pkg/roachpb/data.go, line 923 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTM0alNEZ8IvVf6P-J3:-MTmHTHK0jeuPMzTgthD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/roachpb/data.go#L923)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

you sure you don't want a pointer receiver on this? And maybe on other methods around, but that can wait.
</blockquote></details>

Done.
___
*[pkg/roachpb/data.go, line 932 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTDbfn_CGOqjEELMwME:-MTmGlHN9AYZs6dpGw8j:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/roachpb/data.go#L932)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

minor nit: `transaction's`
</blockquote></details>

Done.
___
*[pkg/roachpb/data.go, line 934 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTM1R8b6ajroypQCufV:-MTmGlyj0lKd1tInpZft:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/roachpb/data.go#L934)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

don't forget to expand on the "this is fine".
</blockquote></details>

Done.
___
*[pkg/roachpb/data.go, line 937 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTEJeCwDXGPo0oTGQMd:-MTmHcObCwNCGkdslGXs:b2p04ax) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/roachpb/data.go#L937)):*
> we can't guarantee that an intent is even present on the follower replica serving the request.

Yes, exactly. Sorry for the confusion, I was lazy by leaving this WIP comment and skipping the most subtle point.

> but do you think we should point to something like this from here?

Done.
___
*[pkg/roachpb/data.go, line 938 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTM1I2QB64FWhEY0VxD:-MTmGfBC2JSO5iv_jvO2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/roachpb/data.go#L938)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

yeah, `MaxObservable` seems to not describe this well (and I personally didn't really like the name to begin with). How about... `RequiredFrontier`? 
</blockquote></details>

Done.

**Review by andreimatei — APPROVED** [review]
:lgtm: :train: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-:-MTmUN0CAutRScuS92tu:b2324gz)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @andreimatei, and @nvanbenschoten)

___
*[pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go, line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59571#-MTLxcGqCIgYORWxPbj3:-MTmTzmm7x_QcYbmh80w:bc0pkti) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5017360f6abed3b3b7545dc37fdce3bc1b2ddf3/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go#L98)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

You don't think the name of the type makes that clear enough?
</blockquote></details>

I guess it does, nvm.

**Pull request merged**
