### PR TITLE
server: separate listening/broadcast addresses

### LINKED ISSUE #4190: how to run a disk-based local node with TLS certs
I'm just trying to validate on a single local node, with disk storage and TLS certs.

Yet when I startup, cockroachdb complains about invalid cert.  How does one tell the db which ip address to use?

~~~
jaten@Jasons-MacBook-Pro:~/go/src/github.com/cockroachdb/cockroach$ git log|head
commit e83c0939857331471e913ba97a8b821b906161d9
Merge: 20e68e7 ef157d1
Author: Peter Mattis <peter@cockroachlabs.com>
Date:   Sat Feb 6 15:58:30 2016 -0500

    Merge pull request #4185 from petermattis/pmattis/bootstrap-fail
    
    Stop make if the .bootstrap target fails.

commit ef157d1b76e0ce8b81476b8b8d855adde7e0a1d7
jaten@Jasons-MacBook-Pro:~/go/src/github.com/cockroachdb/cockroach$ go build
jaten@Jasons-MacBook-Pro:~/go/src/github.com/cockroachdb/cockroach$ rm -rf certs
jaten@Jasons-MacBook-Pro:~/go/src/github.com/cockroachdb/cockroach$ cockroach cert create-ca
jaten@Jasons-MacBook-Pro:~/go/src/github.com/cockroachdb/cockroach$ cockroach cert create-node 127.0.0.1
jaten@Jasons-MacBook-Pro:~/go/src/github.com/cockroachdb/cockroach$ cockroach cert create-client root
jaten@Jasons-MacBook-Pro:~/go/src/github.com/cockroachdb/cockroach$ rm -rf /Users/jaten/cockroachdb.data
jaten@Jasons-MacBook-Pro:~/go/src/github.com/cockroachdb/cockroach$ cockroach start --stores=hdd=/Users/jaten/cockroachdb.data 
I0206 17:11:06.006020 49646 cli/start.go:104  [build]  @  (go1.5.1)
I0206 17:11:06.006447 49646 server/context.go:218  1 storage engine(s) specified
I0206 17:11:06.006467 49646 cli/start.go:125  starting cockroach node
I0206 17:11:06.012203 49646 storage/engine/rocksdb.go:106  opening rocksdb instance at "/Users/jaten/cockroachdb.data"
I0206 17:11:06.018714 49646 server/node.go:320  store store=0:0 ([hdd]=/Users/jaten/cockroachdb.data) not bootstrapped
I0206 17:11:06.024081 49646 storage/replica_command.go:1215  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1454807467.023s
I0206 17:11:06.024793 49646 server/node.go:263  **** cluster b2a4b220-9503-419e-acc0-7c0c7f31d6f9 has been created
I0206 17:11:06.024834 49646 server/node.go:264  **** add additional nodes by specifying --join=[::]:26257
I0206 17:11:06.026313 49646 server/node.go:333  initialized store store=1:1 ([hdd]=/Users/jaten/cockroachdb.data): {Capacity:367416967168 Available:150502281216 RangeCount:0}
I0206 17:11:06.026548 49646 server/node.go:236  node ID 1 initialized
I0206 17:11:06.026989 49646 gossip/gossip.go:218  setting node descriptor node_id:1 address:<network_field:"tcp" address_field:"[::]:26257" > attrs:<> 
I0206 17:11:06.031290 49646 storage/stores.go:277  read 0 node addresses from persistent storage
I0206 17:11:06.031324 49646 storage/split_queue.go:97  splitting range=1 [/Min-/Max) at keys [/Table/11/0 /Table/12/0]
I0206 17:11:06.031422 49646 server/node.go:446  connecting to gossip network to verify cluster ID...
I0206 17:11:06.031447 49646 server/node.go:463  node connected via gossip and verified as part of cluster "b2a4b220-9503-419e-acc0-7c0c7f31d6f9"
I0206 17:11:06.031538 49646 server/node.go:298  Started node with [[hdd]=/Users/jaten/cockroachdb.data] engine(s) and attributes []
I0206 17:11:06.032155 49646 server/server.go:262  starting https server at [::]:26257
I0206 17:11:06.032167 49646 storage/stores.go:292  wrote 1 node addresses to persistent storage
I0206 17:11:06.032604 49646 sql/pgwire/server.go:94  starting postgres server at [::]:15432
W0206 17:11:06.033808 49646 rpc/client.go:326  x509: certificate is valid for 127.0.0.1, not ::
I0206 17:11:06.058319 49646 server.go:1934  http: TLS handshake error from [::1]:56449: remote error: bad certificate
W0206 17:11:07.104533 49646 rpc/client.go:326  x509: certificate is valid for 127.0.0.1, not ::
I0206 17:11:07.108192 49646 server.go:1934  http: TLS handshake error from [::1]:56453: remote error: bad certificate
W0206 17:11:08.880371 49646 rpc/client.go:326  x509: certificate is valid for 127.0.0.1, not ::
I0206 17:11:08.885337 49646 server.go:1934  http: TLS handshake error from [::1]:56456: remote error: bad certificate
  C-c C-cI0206 17:11:10.383716 49646 cli/start.go:148  initiating graceful shutdown of server
I0206 17:11:10.383829 49646 stopper.go:273  draining; tasks left:
1      storage/queue.go:334
E0206 17:11:11.033192 49646 storage/queue.go:124  [split] range=1 [/Min-/Max): error: storage/split_queue.go:100: unable to split range=1 [/Min-/Max) at key "/Table/11/0": failed to send RPC: too many errors encountered (1 of 1 total): kv/send.go:282: rpc to Node.Batch: client not ready after 5s
I0206 17:11:11.033302 49646 storage/engine/rocksdb.go:140  closing rocksdb instance at "/Users/jaten/cockroachdb.data"
I0206 17:11:11.033520 49646 cli/start.go:172  server drained and shutdown completed
jaten@Jasons-MacBook-Pro:~/go/src/github.com/cockroachdb/cockroach$
~~~

attaching generated certs
[certs.tar.gz](https://github.com/cockroachdb/cockroach/files/120519/certs.tar.gz)

### PR DESCRIPTION
**Pull request by tamird**
We should pick one of the last two commits here, the rest is cleanup.

Currently we listen (and advertise via gossip) on the unspecified address by default, which is nice because it has us listening on all interfaces, but this has two problems:
- in a real deployment, other nodes will not be able to find us
- our readme does not advise folks to generate TLS certs with the ipv6 unspecified address

The second-last commit here addresses the readme issue, but obviously not the deployment issue.
The last commit reverts to defaulting to `hostname` for both listening and advertising via gossip.

Note that lib/pq's (and thus our sql shell's) ipv6 handling is also currently broken: https://github.com/lib/pq/pull/427.

Fixes #4190.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4197)

### CODE REVIEW

**Comment by bdarnell** [comment]
Please put the random cleanup in a separate PR.

IPv6 `::` is equivalent to IPv4 `0.0.0.0` and is meaningless to put in a cert (since no client can connect using that address). The other part of the readme change is good, though - any time we advise people to create a cert for `127.0.0.1` we should also include `::1` (I'm not sure if this is a recommendation we want to continue making, but that's a separate matter).

I think we're going to need to separate the address we bind on from the address we broadcast in gossip. Servers are generally expected to bind to localhost in addition to one or more real interfaces (see #3358), so I think we should default to binding on all interfaces but broadcast `os.Hostname()`

**Comment by tamird** [comment]
> IPv6 `::` is equivalent to IPv4 `0.0.0.0` and is meaningless to put in a cert (since no client can connect using that address).

In Go, at least, it seems that clients can connect using that address. From my logs:
```
W0207 12:42:12.462021 90634 rpc/client.go:326  x509: certificate is valid for 127.0.0.1, ::1, not ::
I0207 12:42:12.467570 90634 server.go:1934  http: TLS handshake error from [::1]:49811: remote error: bad certificate
```

These errors are logged when the node is attempting to connect to itself. Adding `::` to the certificate silences these errors.

I agree though, that we'll need to separate the addresses. Added a commit that does that.

**Comment by bdarnell** [comment]
> These errors are logged when the node is attempting to connect to itself. Adding :: to the certificate silences these errors.

I think that's a bug in which something is interpreting the `1` in `::1` as a port number and stripping it off. Maybe we need to bracket the IP address somewhere, or maybe it's a bug in the go TLS code (because certificates are not normally issued for IP literals).

IP literals are supposed to go in a different field in the certificate than DNS hostnames; this may be the issue: https://github.com/golang/go/blob/fa5e5478c8791d644c3d7b07a73680f87eb5a43b/src/crypto/x509/verify.go#L416

**Comment by tamird** [comment]
@bdarnell not sure what you're getting at; we already put IP addresses in the right field in the certificate https://github.com/cockroachdb/cockroach/blob/master/security/x509.go#L154

**Comment by tamird** [comment]
@bdarnell in any case, I've removed the instruction to add `::` from the instructions in the readme. Does this LGTY?

**Comment by nvanbenschoten** [comment]
:lgtm:  from a code perspective

---

Reviewed 1 of 1 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/server.go, line 231 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4197#-K9xy3foHR7ppyN2a3Ws:-K9xy3foHR7ppyN2a3Wt:-1000867485) ([raw file](https://github.com/cockroachdb/cockroach/blob/3207a0b32f2e0b42e1d7a5cf131ab5ceccfb8c4b/server/server.go#L231)):*
The use/need for this block might be an indication that the address defaulting logic is complex enough and self-contained enough to be a separate function, your call though.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4197#-:-K9xypZttVYIhYXHGas2:-1771000595)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/server.go, line 231 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4197#-K9xy3foHR7ppyN2a3Ws:-K9y1c4a5tBMdi5rPxMq:-1832409838) ([raw file](https://github.com/cockroachdb/cockroach/blob/3207a0b32f2e0b42e1d7a5cf131ab5ceccfb8c4b/server/server.go#L231)):*
Yeah, I could extract a function - I don't think that improves the readability of the thing, though.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4197)*

**Comment by bdarnell** [comment]
Ah, I hadn't checked whether we were being clever about cert creation. LGTM, but I'd like to see the tests reinstated.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[server/server.go, line 231 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4197#-K9xy3foHR7ppyN2a3Ws:-K9y3d_QJpbwJbqDDX8R:1250610922) ([raw file](https://github.com/cockroachdb/cockroach/blob/3207a0b32f2e0b42e1d7a5cf131ab5ceccfb8c4b/server/server.go#L231)):*
I think it's worth extracting a function in order to have some tests for this logic. We keep breaking this, which is a clear sign that we need better testing. 

---

*[server/server.go, line 253 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4197#-K9y4MvtNkMgsrahPfNL:-K9y4MvtNkMgsrahPfNM:-1785024988) ([raw file](https://github.com/cockroachdb/cockroach/blob/3207a0b32f2e0b42e1d7a5cf131ab5ceccfb8c4b/server/server.go#L253)):*
Nit: s/kernel/system/

---

*[server/server.go, line 254 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4197#-K9y44U7p81rZ_scqabP:-K9y44U7p81rZ_scqabQ:277302638) ([raw file](https://github.com/cockroachdb/cockroach/blob/3207a0b32f2e0b42e1d7a5cf131ab5ceccfb8c4b/server/server.go#L254)):*
The commit message should mention this change in functionality (unless I'm missing where `os.Hostname` was called in the old version). 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4197#-:-K9y4m3SgOmPjizw6xlB:-1714831841)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[server/server.go, line 231 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4197#-K9xy3foHR7ppyN2a3Ws:-K9yE4R7ZfvLTxqH3DU2:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3207a0b32f2e0b42e1d7a5cf131ab5ceccfb8c4b/server/server.go#L231)):*
Done.

---

*[server/server.go, line 253 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4197#-K9y4MvtNkMgsrahPfNL:-K9yDsESJ_8isuuRoIU2:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3207a0b32f2e0b42e1d7a5cf131ab5ceccfb8c4b/server/server.go#L253)):*
Done.

---

*[server/server.go, line 254 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4197#-K9y44U7p81rZ_scqabP:-K9yDsylxuP42XGKd1NW:596625354) ([raw file](https://github.com/cockroachdb/cockroach/blob/3207a0b32f2e0b42e1d7a5cf131ab5ceccfb8c4b/server/server.go#L254)):*
The hostname bit is a partial reversal of https://github.com/cockroachdb/cockroach/pull/4161. I've called it out in the commit message.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4197)*

**Pull request merged**
