### PR TITLE
release-24.1: ttljob: log progress in TTL job

### PR DESCRIPTION
**Pull request by rafiss**
Backport 4/4 commits from #135142.

/cc @cockroachdb/release

Release justification: low risk high reward o11y change

---

This patch adds better o11y for tracking the progress of the TTL job.
Previously, the progress struct would be updated, but we would never
update the FractionCompleted measurement.

Now, the main loop of the TTL processor will periodically log the
number of spans that have been processed so far.

fixes https://github.com/cockroachdb/cockroach/issues/86884
Release note (ops change): The row-level TTL job now will periodically
log progress by showing the number of table spans that have been
processed so far.

---

Other commits are small refactors.

### CODE REVIEW

**Review by fqazi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135179#-:-OBfUwcs2dPJ8PutRE-M:bnfp4nl)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kev-cao)

**Comment by dt** [comment]
This appears to be new functionality that will add a new cadence of progress writes to the jobs system, right? Does this feel like a very quick backport for something like this before it has had a chance to run on master / new versions first?

If spans are processed very quickly (e.g. no rows requiring deletion), is there any enforcement of a minimum time between progress updates this will send to the job system or will every job potentially try to make all 100 updates in quick succession?

**Comment by msbutler** [comment]
i second david's opinon here. i think this sort of change really needs to bake on master /drt clusters before we backport. this could destabilize the job system if there's a bug, like lack of pacing on checkpoints.

**Comment by rafiss** [comment]
> This appears to be new functionality that will add a new cadence of progress writes to the jobs system, right? Does this feel like a very quick backport for something like this before it has had a chance to run on master / new versions first?

My thinking was to let this on on master for a few days before clicking merge. Sorry if something implied otherwise.

**Comment by rafiss** [comment]
> If spans are processed very quickly (e.g. no rows requiring deletion), is there any enforcement of a minimum time between progress updates this will send to the job system or will every job potentially try to make all 100 updates in quick succession?

This doesn't have any time enforcement. There will be some amount of time built-in, since it still takes time for the job to run the SELECT query that determines that there are no expired rows to delete. 

Is the concern you have around contention on the row in the `job_info` table? Would something like a 10-second minimum in between progress updates help address that?

**Comment by dt** [comment]
A few days before clicking merge still feels a bit quick to me for a new functionality that interacts with jobs in a new way to backport to existing branches, unless there is an element of urgency I'm missing.

My first choice for something adding a new interaction with the jobs system would be to go out in a new version (which could maybe be 24.3 in this case?) and then consider a backport if it is required only after it has been observed running happily in the wild on the new version.

Alternatively, I think our backport policy says new functionality can be backported when there is a "high priority business need for the functionality which cannot wait until the next release" if we can put it behind an opt-in flag. I would feel less strongly about needing to be opt-in though if we'd already had it running in 24.3 for a month or two before backporting to the older releases.

> something like a 10-second minimum

Exactly -- IIRC backup and IMPORT have 10 or 15s minimum time between update checks. However most (all?) jobs exclusively perform progress updates from a single coordinator node that is enforcing its minimum frequency; processors in the distsql flows of those jobs send partial progress information back to the coordinator via producer metas, which aggregates it and then, once every x seconds, update the job record once, regardless of how many processors are being run, with the aggregated total progress.

Is the progress update in this job happening directly from each processor?

**Comment by rafiss** [comment]
How about I rework the 24.1 and 24.2 backports so they _only_ have the additional logging -- that is the minimal thing needed for users to be able to see at least some measure of progress. I'll leave the fractionCompleted change for the 24.3 backport.

> Is the progress update in this job happening directly from each processor?

Yes, though it happens in a separate transaction, meaning it won't be contending with the job itself and also it will have internal auto-retries.

**Comment by dt** [comment]
I think this might only be working due to a bug in the jobs system; it is not supposed to allow progress updates to be written by nodes that don't hold the lease for the job, i.e. the coordinator.

**Comment by rafiss** [comment]
> I think this might only be working due to a bug in the jobs system; it is not supposed to allow progress updates to be written by nodes that don't hold the lease for the job, i.e. the coordinator.

Interesting. It would be useful if this API contract could be added to the interface docs/comments (unless I missed it).

By the way, even before my PR, the TTL job already had the behavior of each processor updating the progress. Except before my PR, the processor would only do that update after the processor was done with all the spans that had been assigned to it.

So this violation of the contract has been happening without issues since the job was made to be distributed in 23.1 (https://github.com/cockroachdb/cockroach/pull/84728).

**Comment by dt** [comment]
> violation of the contract

Yeah, we did a little digging into the history over in #job-infra-eng and realized the check we thought we had has been missing all along. It is partially enforced in multiple places, which gave us a mistaken impression that it was actually being enforced all the time, but a closer inspection of the code has made us realize it is not and never has been enforced the way we thought.

We'll need to update this processor to emit producer metas and combine those in the flow coordinator to issue a single aggregated progress update before we can fix the jobs API enforcement. I'll file an issue for that. 

In the meantime, while we still have every node in every job updating the job record concurrently, I think we might want a pretty conservative minimum delay between updates to try to keep the aggregate update rate in check; perhaps a minimum of 60s elapsed since last update or proc start, with a bit of jitter so they don't all update exactly 60s in.

**Comment by rafiss** [comment]
Out of curiosity, what failure mode are we preventing by only allowing the coordinator to update progress?

Asking just since, if we've been not doing things that way since 23.1, then it feels like we're adding a lot of extra work to fix something which apparently hasn't been a problem. Is there an issue, escalation, manual experiment I could take a look at to understand the impact of this better?

**Comment by rafiss** [comment]
I've updated this PR so that it just logs information, and removed the code that updates job progress.

I added the time-based rate limiter in this PR on master: https://github.com/cockroachdb/cockroach/pull/135192

**Review by fqazi — APPROVED** [review]
Looks good!

> Reviewed 2 of 3 files at r6, 2 of 2 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135179#-:-OBlHVWdDWI_4W-SvqgK:b-vs1prh)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kev-cao)

**Pull request merged**
