### PR TITLE
Enable grpc tracing. Goes into /debug/requests automatically

### PR DESCRIPTION
**Pull request by mberhault**
The default is `true`.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8069)

### CODE REVIEW

**Comment by BramGruneir** [comment]
LGTM

**Comment by tamird** [comment]
i believe there are performance implications here. let's use an environment variable.

**Comment by mberhault** [comment]
perhaps, but I would argue that we want this even if it costs us a bit. Unless someone wants the option to turn it off soon and quickly, I don't think we should add yet another env variable.

**Comment by tamird** [comment]
This came up in the original code review. If you're not going to add an environment variable, we need to see some benchmarks.

**Comment by mberhault** [comment]
Fair enough. Are you aware of any existing benchmarks that may be tickled, or would I be better off adding a new one?

**Comment by tamird** [comment]
Standard sql benchmarks should do the trick.

**Comment by mberhault** [comment]
ok, sql benchmarks without (old)/with (new) tracing: count=5, run on my machine.
There's a +7% for `Select2Multinode_Cockroach-8`, but all other increases are postgres/mysql benchmarks.

```
name                            old time/op  new time/op  delta
Bank2_Cockroach-8               3.31ms ±30%  2.58ms ±35%     ~     (p=0.151 n=5+5)
Bank2_Postgres-8                19.4ms ±25%  19.8ms ±24%     ~     (p=0.841 n=5+5)
Bank4_Cockroach-8               2.65ms ± 8%  2.70ms ± 9%     ~     (p=0.690 n=5+5)
Bank4_Postgres-8                17.6ms ±17%  16.6ms ±11%     ~     (p=0.393 n=3+5)
Bank8_Cockroach-8               2.19ms ±10%  1.84ms ±31%  -15.93%  (p=0.032 n=5+5)
Bank8_Postgres-8                16.1ms ±35%  18.0ms ±51%     ~     (p=0.841 n=5+5)
Bank16_Cockroach-8              1.41ms ±24%  1.37ms ±25%     ~     (p=0.841 n=5+5)
Bank16_Postgres-8               11.7ms ±78%  11.3ms ±54%     ~     (p=1.000 n=5+5)
Bank32_Cockroach-8              1.16ms ± 7%  1.15ms ± 7%     ~     (p=0.690 n=5+5)
Bank32_Postgres-8               9.84ms ±88%  6.18ms ±23%     ~     (p=0.222 n=5+5)
Bank64_Cockroach-8               930µs ± 9%   897µs ± 8%     ~     (p=0.310 n=5+5)
Bank64_Postgres-8               4.99ms ±16%  5.19ms ±30%     ~     (p=1.000 n=4+5)
Select1_Cockroach-8             65.4µs ± 5%  63.8µs ± 5%     ~     (p=0.310 n=5+5)
Select1Multinode_Cockroach-8    69.7µs ± 7%  67.8µs ± 3%     ~     (p=0.151 n=5+5)
Select1_Postgres-8              57.0µs ± 2%  83.3µs ± 4%  +46.14%  (p=0.016 n=4+5)
Select1_MySQL-8                 33.0µs ± 1%  40.9µs ±12%  +23.85%  (p=0.008 n=5+5)
Select2_Cockroach-8              569µs ± 3%   562µs ± 5%     ~     (p=0.690 n=5+5)
Select2Multinode_Cockroach-8     560µs ± 1%   599µs ± 3%   +7.05%  (p=0.008 n=5+5)
Select2_Postgres-8               159µs ± 1%   194µs ±16%  +21.66%  (p=0.008 n=5+5)
Select3_Cockroach-8              779µs ± 1%   773µs ± 2%     ~     (p=0.222 n=5+5)
Select3Multinode_Cockroach-8     779µs ± 1%   817µs ± 6%     ~     (p=0.151 n=5+5)
Select3_Postgres-8               218µs ± 1%   222µs ± 1%   +1.98%  (p=0.008 n=5+5)
Insert1_Cockroach-8              395µs ± 0%   398µs ± 1%   +0.98%  (p=0.016 n=5+5)
Insert1Multinode_Cockroach-8     838µs ± 2%   845µs ± 1%     ~     (p=0.310 n=5+5)
Insert1_Postgres-8              22.4ms ±12%  18.6ms ± 6%  -17.12%  (p=0.008 n=5+5)
Insert10_Cockroach-8             534µs ± 0%   524µs ± 2%   -1.87%  (p=0.008 n=5+5)
Insert10Multinode_Cockroach-8   1.03ms ± 2%  1.04ms ± 2%     ~     (p=0.690 n=5+5)
Insert10_Postgres-8             20.2ms ±18%  17.5ms ±49%     ~     (p=0.421 n=5+5)
Insert100_Cockroach-8           1.61ms ± 1%  1.64ms ± 4%     ~     (p=1.000 n=5+5)
```

**Comment by mberhault** [comment]
I'll see if I can add a lightweight rpc benchmark (maybe similar to the Hearbeat one in rpc/). That may give us a better idea

**Comment by mberhault** [comment]
actually, the raw numbers can be found from `grpc/benchmark/`:
```
name                       time/op
ClientStreamc1-8            114µs ± 9%
ClientStreamc8-8           26.9µs ± 9%
ClientStreamc64-8          15.9µs ± 3%
ClientStreamc512-8         12.7µs ± 2%
ClientUnaryc1-8             246µs ± 5%
ClientUnaryc8-8            58.6µs ± 7%
ClientUnaryc64-8           31.2µs ± 1%
ClientUnaryc512-8          28.1µs ± 6%
ClientStreamNoTracec1-8    91.9µs ±26%
ClientStreamNoTracec8-8    23.5µs ± 7%
ClientStreamNoTracec64-8   14.7µs ±10%
ClientStreamNoTracec512-8  11.9µs ± 4%
ClientUnaryNoTracec1-8      212µs ±10%
ClientUnaryNoTracec8-8     55.4µs ± 5%
ClientUnaryNoTracec64-8    29.4µs ± 2%
ClientUnaryNoTracec512-8   25.8µs ± 1%
```

Not too bad.

**Comment by petermattis** [comment]
Thanks for checking the benchmarks. I think these numbers look fine. LGTM.

**Pull request merged**
