### PR TITLE
cli/start,server: fix the "wait for init" msg

### PR DESCRIPTION
**Pull request by knz**
Release note (bug fix): Previously `cockroach start` would erroneously
hint that it was waiting for a join or `cockroach init` both for fresh
new nodes and re-starting nodes. This has been fixed and the message
now only appears for fresh new nodes.

### CODE REVIEW

**Comment by knz** [comment]
I wonder - should I test this? if so, how?

**Review by a-robinson — APPROVED** [review]
You should certainly manually test it, although it sounds like you already did. You could try stubbing out `s.cfg.ReadyFn` with something that checks the provided `waitForInit` value and then start servers with different engines/joinlists, although I'm not sure how much value that test would really add.

Honestly the most future-proof thing I could imagine doing here would be to either work the `ReadyFn` calls into the logic below

```
if len(bootstrappedEngines) > 0 {
  ...
} else if len(s.cfg.GossipBootstrapResolvers) == 0 {
  ...
} else {
  ...
}
```

Or to just move the log.Shout call into else block next to the code that actually waits for the bootstrap. That'd require more work to avoid shouting in things like tests, though.

Your call on how you want to do it. :lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30211#-:-LMJPAnF7MGsOs2MEO5N:b-pd3aeb)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by knz** [comment]
Reworked as suggested. PTAL

**Review by a-robinson — APPROVED** [review]
LGTM

**Comment by knz** [comment]
Thanks!

bors r+
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
