### PR TITLE
server.go: misc refactors

### PR DESCRIPTION
**Pull request by knz**
This moves code out of server.go into distinct files, to make the code easier to navigate/explore.

### CODE REVIEW

**Review by tbg — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 3 of 3 files at r2, 4 of 4 files at r3, 3 of 3 files at r4, 4 of 4 files at r5, 3 of 3 files at r6, 3 of 3 files at r7, 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75724)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gh-casper)

**Comment by knz** [comment]
TFYR!

bors r=tbg

**Comment by knz** [comment]
This needs to wait on top of #75735.

**Comment by knz** [comment]
bors r=tbg

**Pull request merged**
