### PR TITLE
sql: add rule to decorrelate Max1Row operator using DistinctOn

### LINKED ISSUE #47667: opt: decorrelate Max1Row operator using DistinctOn with ErrorOnDup=true
Currently we are not able to decorrelate joins that have a `Max1Row` as their right input, as in this case:
```
root@:26257/defaultdb> CREATE TABLE ab (a INT PRIMARY KEY, b INT);
CREATE TABLE

root@:26257/defaultdb> CREATE TABLE xy (x INT PRIMARY KEY, y INT);
CREATE TABLE

root@:26257/defaultdb> EXPLAIN (OPT) SELECT (SELECT b FROM ab WHERE b=x) FROM xy;
                text
-------------------------------------
  project
   ├── left-join-apply
   │    ├── scan xy
   │    ├── max1-row
   │    │    └── select
   │    │         ├── scan ab
   │    │         └── filters
   │    │              └── ab.b = x
   │    └── filters (true)
   └── projections
        └── ab.b
```
We should add a `TryDecorrelateMax1Row` rule that pulls the `Max1Row` operator above the `LeftJoinApply` operator as a `DistinctOn` with `ErrorOnDup=true`:
```
(DistinctOn
  (LeftJoinApply (Values ...) (Select ...) (True))
  [GroupingCols=(x), ErrorOnDup=true]
)
```
The `ErrorOnDup=true` option will cause `DistinctOn` to raise an error if it detects duplicates in the `x` column. Since `x` was a key in the join's left input, a duplicate value in that column indicates more than one row from the right input matched that value. That's equivalent to the semantics of `Max1Row`.

### PR DESCRIPTION
**Pull request by DrewKimball**
Previously, we could not decorrelate joins that have a Max1Row as their right input.
To address this, TryDecorrelateMax1Row 'pushes' the join operator through the 
Max1Row and maps the Max1Row operator to a DistinctOn with ErrorOnDup set 
to the Max1Row operator's error message.

The rule transforms a query that looks like this:
```
  project
   ├── left-join-apply
   │    ├── scan xy
   │    ├── max1-row
   │    │    └── select
   │    │         ├── scan ab
   │    │         └── filters
   │    │              └── ab.b = x
   │    └── filters (true)
   └── projections
        └── ab.b
```
To one that looks like this:
```
project
   ├── distinct-on
   │    ├── left-join-apply
   │    │    ├── scan xy
   │    │    └── select
   │    │         ├── scan ab
   │    │         └── filters
   │    │              └── ab.b = x
   │    └── aggregations
   │         └── const-agg
   │              └── ab.b
   └── projections
        └── ab.b
```

Fixes #47667

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48006)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 704 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48006#-M5gTF0cCNVWdYTSFhJl:-M5gTF0cCNVWdYTSFhJm:b-uefh5q) ([raw file](https://github.com/cockroachdb/cockroach/blob/84dcc23b24eda04a8fc2c79442907e8ef7f7cc60/pkg/sql/opt/norm/rules/decorrelate.opt#L704)):*
> ```
> # value. Or in other words, it indicates that the Max1Row's subquery input would
> # have returned more than one row corresponding to that value. Therefore, the
> # two formulations are equivalent.
> ```

I don't think these two formulations are equivalent. This comment correctly explains that a DistinctOn error implies the original formulation would have hit an error. But the converse is not true.

Specifically, `$input` might return multiple rows for a given left row, but if those rows fail the $on condition they never make it to `DistinctOn`. To keep these equivalent, we'd need to pull up the `$on` condition as a `Select` on top of the `DistinctOn` and use `True` for the on condition of the join.

I'd add a logictest case along these lines.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48006)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 704 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48006#-M5gTF0cCNVWdYTSFhJl:-M5gXfbZ7a4fqVcR3Oxv:b-5e7rhb) ([raw file](https://github.com/cockroachdb/cockroach/blob/84dcc23b24eda04a8fc2c79442907e8ef7f7cc60/pkg/sql/opt/norm/rules/decorrelate.opt#L704)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I don't think these two formulations are equivalent. This comment correctly explains that a DistinctOn error implies the original formulation would have hit an error. But the converse is not true.

Specifically, `$input` might return multiple rows for a given left row, but if those rows fail the $on condition they never make it to `DistinctOn`. To keep these equivalent, we'd need to pull up the `$on` condition as a `Select` on top of the `DistinctOn` and use `True` for the on condition of the join.

I'd add a logictest case along these lines.
</blockquote></details>

Can you give an example? I don't think it's necessary to pull $on outside the `DistinctOn`. If the $on filters left rows, then the `Max1Row` would never run in the "before" case for the filtered rows. Pulling $on outside the `DistinctOn` would effectively mean it *always* runs. This means that it would raise *more* errors than before, which doesn't seem right.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48006)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @RaduBerinde)

___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 704 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48006#-M5gTF0cCNVWdYTSFhJl:-M5gsECVE3WTjtKLotzQ:buesz43) ([raw file](https://github.com/cockroachdb/cockroach/blob/84dcc23b24eda04a8fc2c79442907e8ef7f7cc60/pkg/sql/opt/norm/rules/decorrelate.opt#L704)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Can you give an example? I don't think it's necessary to pull $on outside the `DistinctOn`. If the $on filters left rows, then the `Max1Row` would never run in the "before" case for the filtered rows. Pulling $on outside the `DistinctOn` would effectively mean it *always* runs. This means that it would raise *more* errors than before, which doesn't seem right.
</blockquote></details>

I think you're right, @RaduBerinde. The rule as it is will only be guaranteed to work in the case when the $on filter is true, like this:
````
  + ├── left-join-apply
  + │    ├── select
  + │    │    ├── scan xy
  + │    │    └── filters
  + │    │         └── y != 0
  + │    ├── max1-row
  + │    │    └── project
  + │    │         └── select
  + │    │              ├── scan ab
  + │    │              └── filters
  + │    │                   ├── ab.b = x
  + │    │                   └── a != 0
  + │    └── filters (true)
````
Currently, this will always be the case because HoistSelectSubquery and HoistProjectSubquery always set the $on filter to true, and TryDecorrelateMax1Row activates before any filters on a surrounding select can be pushed into the $on filter. Hypothetically, though, this could change, so I'll change the rule to only math cases where $on is true.

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 704 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48006#-M5gTF0cCNVWdYTSFhJl:-M5gpDy89pROkfva8sM_:bgglods) ([raw file](https://github.com/cockroachdb/cockroach/blob/84dcc23b24eda04a8fc2c79442907e8ef7f7cc60/pkg/sql/opt/norm/rules/decorrelate.opt#L704)):*
<details><summary><i>Previously, DrewKimball (Andrew Kimball) wrote…</i></summary><blockquote>

I think you're right, @RaduBerinde. The rule as it is will only be guaranteed to work in the case when the $on filter is true, like this:
````
  + ├── left-join-apply
  + │    ├── select
  + │    │    ├── scan xy
  + │    │    └── filters
  + │    │         └── y != 0
  + │    ├── max1-row
  + │    │    └── project
  + │    │         └── select
  + │    │              ├── scan ab
  + │    │              └── filters
  + │    │                   ├── ab.b = x
  + │    │                   └── a != 0
  + │    └── filters (true)
````
Currently, this will always be the case because HoistSelectSubquery and HoistProjectSubquery always set the $on filter to true, and TryDecorrelateMax1Row activates before any filters on a surrounding select can be pushed into the $on filter. Hypothetically, though, this could change, so I'll change the rule to only math cases where $on is true.
</blockquote></details>

`SELECT * FROM (SELECT x, y, (SELECT b FROM ab WHERE a=y) AS b FROM xy)`
vs
`SELECT * FROM (SELECT x, y, (SELECT b FROM ab WHERE a=y) AS b FROM xy) WHERE b < 10`

I expect the query to fail if ab has duplicate values. The second one would fail only if there are duplicate values with b < 10.

It's the conceptual difference between "make sure I have at most one value, then give it to me if it is < 10" vs "make sure I have at most one value if it is < 10, then give it to me"

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 704 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48006#-M5gTF0cCNVWdYTSFhJl:-M5gtqtc7H37QaO2KAT7:bevax8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/84dcc23b24eda04a8fc2c79442907e8ef7f7cc60/pkg/sql/opt/norm/rules/decorrelate.opt#L704)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`SELECT * FROM (SELECT x, y, (SELECT b FROM ab WHERE a=y) AS b FROM xy)`
vs
`SELECT * FROM (SELECT x, y, (SELECT b FROM ab WHERE a=y) AS b FROM xy) WHERE b < 10`

I expect the query to fail if ab has duplicate values. The second one would fail only if there are duplicate values with b < 10.

It's the conceptual difference between "make sure I have at most one value, then give it to me if it is < 10" vs "make sure I have at most one value if it is < 10, then give it to me"
</blockquote></details>

"duplicate" was not the right word - I meant multiple rows for some a=y

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 704 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48006#-M5gTF0cCNVWdYTSFhJl:-M5gu-wk7C4llXiy4Q8R:bs0la2q) ([raw file](https://github.com/cockroachdb/cockroach/blob/84dcc23b24eda04a8fc2c79442907e8ef7f7cc60/pkg/sql/opt/norm/rules/decorrelate.opt#L704)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

"duplicate" was not the right word - I meant multiple rows for some a=y
</blockquote></details>

@drewkimball even though the decorrelation rules create a True condition, a filter can then be pushed down from a select, as in my example above:
```
root@127.0.0.1:42387/defaultdb> EXPLAIN (opt) SELECT * FROM (SELECT x, y, (SELECT b FROM ab WHERE a=y) AS b FROM xy) WHERE b < 10;
                 text
---------------------------------------
  project
   ├── inner-join-apply
   │    ├── scan xy
   │    ├── max1-row
   │    │    └── project
   │    │         └── select
   │    │              ├── scan ab
   │    │              └── filters
   │    │                   └── a = y
   │    └── filters
   │         └── ab.b < 10
   └── projections
        └── ab.b
```

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48006)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @RaduBerinde)

___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 704 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48006#-M5gTF0cCNVWdYTSFhJl:-M5gv4yZD78RUzko3iNZ:b-s9mbpw) ([raw file](https://github.com/cockroachdb/cockroach/blob/84dcc23b24eda04a8fc2c79442907e8ef7f7cc60/pkg/sql/opt/norm/rules/decorrelate.opt#L704)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

@drewkimball even though the decorrelation rules create a True condition, a filter can then be pushed down from a select, as in my example above:
```
root@127.0.0.1:42387/defaultdb> EXPLAIN (opt) SELECT * FROM (SELECT x, y, (SELECT b FROM ab WHERE a=y) AS b FROM xy) WHERE b < 10;
                 text
---------------------------------------
  project
   ├── inner-join-apply
   │    ├── scan xy
   │    ├── max1-row
   │    │    └── project
   │    │         └── select
   │    │              ├── scan ab
   │    │              └── filters
   │    │                   └── a = y
   │    └── filters
   │         └── ab.b < 10
   └── projections
        └── ab.b
```
</blockquote></details>

I see the problem. I was thinking about filters on the left input, which should be fine. But the problem comes with filters on the right input.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48006)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @RaduBerinde)

___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 704 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48006#-M5gTF0cCNVWdYTSFhJl:-M5gvWd88SXQQIO2BI38:bb64myv) ([raw file](https://github.com/cockroachdb/cockroach/blob/84dcc23b24eda04a8fc2c79442907e8ef7f7cc60/pkg/sql/opt/norm/rules/decorrelate.opt#L704)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I see the problem. I was thinking about filters on the left input, which should be fine. But the problem comes with filters on the right input.
</blockquote></details>

In practice, since the TryDecorrelateMax1Row rule executes before the filter is pushed down, we end up with this instead:

```
root@:26257/defaultdb> EXPLAIN (opt) SELECT * FROM (SELECT x, y, (SELECT b FROM ab WHERE a=y) AS b FROM xy) WHERE b < 10;
               text
-----------------------------------
  project
   ├── select
   │    ├── ensure-distinct-on
   │    │    ├── left-join (hash)
   │    │    │    ├── scan xy
   │    │    │    ├── scan ab
   │    │    │    └── filters
   │    │    │         └── a = y
   │    │    └── aggregations
   │    │         ├── const-agg
   │    │         │    └── y
   │    │         └── const-agg
   │    │              └── ab.b
   │    └── filters
   │         └── ab.b < 10
   └── projections
        └── ab.b
```
But I do agree that simply pushing the $on into the EnsureDistinctOn isn't correct.

**Review by rytaft — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 20 of 20 files at r2, 40 of 40 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48006)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @DrewKimball, and @RaduBerinde)

___
*[pkg/sql/opt/memo/check_expr.go, line 299 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48006#-M5gkf0O2g-3ppkFRTJd:-M5gkf0P5-bK3akbP-0e:b-w3a54w) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9c6ad3c68d7ce911a5d15e8983c66bbddc57f78/pkg/sql/opt/memo/check_expr.go#L299)):*
> ```Go
> 	// Only UpsertDistinctOn should set the ErrorOnDup field to true.
> 	if e.Op() != opt.UpsertDistinctOnOp && e.Private().(*GroupingPrivate).ErrorOnDup != "" {
> 		panic(errors.AssertionFailedf("%s should never set ErrorOnDup to true", log.Safe(e.Op())))
> ```

[nit] true -> "a non-empty string"
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1942 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48006#-M5glMBZ7CEgabgXXsVu:-M5glMB_2wh5fUDjo1Dk:b4lgl1z) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9c6ad3c68d7ce911a5d15e8983c66bbddc57f78/pkg/sql/opt/norm/custom_funcs.go#L1942)):*
> ```Go
> // MakeDupErrorGrouping constructs a new GroupingPrivate using the given
> // grouping columns, OrderingChoice, and ErrorOnDup text.
> func (c *CustomFuncs) MakeDupErrorGrouping(
> ```

[nit] I'd call this `MakeErrorOnDupGrouping`
___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 704 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48006#-M5gTF0cCNVWdYTSFhJl:-M5gtxDf35JMILD2I_VH:bammjxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/84dcc23b24eda04a8fc2c79442907e8ef7f7cc60/pkg/sql/opt/norm/rules/decorrelate.opt#L704)):*
<details><summary><i>Previously, DrewKimball (Andrew Kimball) wrote…</i></summary><blockquote>

In practice, since the TryDecorrelateMax1Row rule executes before the filter is pushed down, we end up with this instead:

```
root@:26257/defaultdb> EXPLAIN (opt) SELECT * FROM (SELECT x, y, (SELECT b FROM ab WHERE a=y) AS b FROM xy) WHERE b < 10;
               text
-----------------------------------
  project
   ├── select
   │    ├── ensure-distinct-on
   │    │    ├── left-join (hash)
   │    │    │    ├── scan xy
   │    │    │    ├── scan ab
   │    │    │    └── filters
   │    │    │         └── a = y
   │    │    └── aggregations
   │    │         ├── const-agg
   │    │         │    └── y
   │    │         └── const-agg
   │    │              └── ab.b
   │    └── filters
   │         └── ab.b < 10
   └── projections
        └── ab.b
```
But I do agree that simply pushing the $on into the EnsureDistinctOn isn't correct.
</blockquote></details>

Here's another example where the previous rule failed (could be useful as a test case):
```
root@127.0.0.1:60395/movr> select * from a;
  x | y | z
----+---+----
  1 | 2 | 3
  4 | 5 | 6
(2 rows)

Time: 924µs

root@127.0.0.1:60395/movr> select * from b;
  x
-----
  1
  2
(2 rows)

Time: 570µs

root@127.0.0.1:60395/movr> explain (opt) select * from a where x = (select x from b where y > 0);
               text
----------------------------------
  project
   └── inner-join-apply
        ├── scan a
        ├── max1-row
        │    └── select
        │         ├── scan b
        │         └── filters
        │              └── y > 0
        └── filters
             └── a.x = b.x
(10 rows)

root@127.0.0.1:60395/movr> select * from a where x = (select x from b where y > 0);
ERROR: more than one row returned by a subquery used as an expression
SQLSTATE: 21000
```
If we apply this transformation we'd only get one row:
```
root@127.0.0.1:60395/movr> select * from a inner join lateral (select * from b where y > 0) as b(x)  on a.x = b.x;
  x | y | z | x
----+---+---+----
  1 | 2 | 3 | 1
(1 row)
```
___
*[pkg/sql/opt/ops/relational.opt, line 580 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48006#-M5gw-a7C2v653bZBcEc:-M5gw-a7C2v653bZBcEd:b-yr2kgr) ([raw file](https://github.com/cockroachdb/cockroach/blob/84dcc23b24eda04a8fc2c79442907e8ef7f7cc60/pkg/sql/opt/ops/relational.opt#L580)):*
> ```
> # that would otherwise trigger the EnsureDistinctOn error.
> [Relational, Grouping, Telemetry]
> define EnsureDistinctOn {
> ```

Do we need another operator? Could we combine this with `UpsertDistinctOn`? I know that `UpsertDistinctOn` has special null behavior, but that wouldn't be a problem for this use case, since the grouping columns in the Max1Row rule are always keys (which cannot be null).

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48006)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @DrewKimball, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/ops/relational.opt, line 580 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48006#-M5gw-a7C2v653bZBcEc:-M5h-b7m21p3FN7X50L9:bq58dx) ([raw file](https://github.com/cockroachdb/cockroach/blob/84dcc23b24eda04a8fc2c79442907e8ef7f7cc60/pkg/sql/opt/ops/relational.opt#L580)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Do we need another operator? Could we combine this with `UpsertDistinctOn`? I know that `UpsertDistinctOn` has special null behavior, but that wouldn't be a problem for this use case, since the grouping columns in the Max1Row rule are always keys (which cannot be null).
</blockquote></details>

I think another operator is preferable, in order to avoid bugs. These operators each behave in subtly different ways. You have to consider each variant separately when writing rules and when testing rules. This is similar to our reason for separating `ScalarGroupBy` from `GroupBy` rather than just adding a field. Subtle bugs would creep in if we relied on every developer to remember to check a flag, whereas if they forget to match one of the variants, it's just a perf problem, not a correctness problem.

Separately, I've been thinking whether we should break out `UpsertEnsureDistinctOn`, for consistency with this.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48006)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @DrewKimball, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/ops/relational.opt, line 580 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48006#-M5gw-a7C2v653bZBcEc:-M5h0ddZ-gUlSsv_HKIE:b-63p58a) ([raw file](https://github.com/cockroachdb/cockroach/blob/84dcc23b24eda04a8fc2c79442907e8ef7f7cc60/pkg/sql/opt/ops/relational.opt#L580)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I think another operator is preferable, in order to avoid bugs. These operators each behave in subtly different ways. You have to consider each variant separately when writing rules and when testing rules. This is similar to our reason for separating `ScalarGroupBy` from `GroupBy` rather than just adding a field. Subtle bugs would creep in if we relied on every developer to remember to check a flag, whereas if they forget to match one of the variants, it's just a perf problem, not a correctness problem.

Separately, I've been thinking whether we should break out `UpsertEnsureDistinctOn`, for consistency with this.
</blockquote></details>

As a concrete example, we can push filters down into `DistinctOn` and `UpsertDistinctOn`, but not into `EnsureDistinctOn` or `UpsertDistinctOn` (when ErrorOnDup=true). It'd be an easy bug to add `UpsertDistinctOn` to the `PushSelectIntoGroupBy` rule, and forget to check the `ErrorOnDup` flag.

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/ops/relational.opt, line 580 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48006#-M5gw-a7C2v653bZBcEc:-M5h1cGY56RHpXRyoqny:bl1rtvu) ([raw file](https://github.com/cockroachdb/cockroach/blob/84dcc23b24eda04a8fc2c79442907e8ef7f7cc60/pkg/sql/opt/ops/relational.opt#L580)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

As a concrete example, we can push filters down into `DistinctOn` and `UpsertDistinctOn`, but not into `EnsureDistinctOn` or `UpsertDistinctOn`. It'd be an easy bug to add `UpsertDistinctOn` to the `PushSelectIntoGroupBy` rule, and forget to check the `ErrorOnDup` flag.
</blockquote></details>

Keys can be null. E.g. the grouping columns from a groupby/distinct

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48006)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @DrewKimball, and @RaduBerinde)

___
*[pkg/sql/opt/ops/relational.opt, line 580 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48006#-M5gw-a7C2v653bZBcEc:-M5h1ZWU0l3LtNd0E3Q3:b-iuct0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/84dcc23b24eda04a8fc2c79442907e8ef7f7cc60/pkg/sql/opt/ops/relational.opt#L580)):*
> we can push filters down into `DistinctOn` and `UpsertDistinctOn`, but not into `EnsureDistinctOn` or `UpsertDistinctOn`

Do you mean that we can push filters down into `UpsertDistinctOn`, but only when `ErrOnDup` flag is false?

> Keys can be null. E.g. the grouping columns from a groupby/distinct

Whoops you're right!

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48006)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @DrewKimball, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/ops/relational.opt, line 580 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48006#-M5gw-a7C2v653bZBcEc:-M5h2To717WBTEjlKwb9:b-n9nlx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/84dcc23b24eda04a8fc2c79442907e8ef7f7cc60/pkg/sql/opt/ops/relational.opt#L580)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

> we can push filters down into `DistinctOn` and `UpsertDistinctOn`, but not into `EnsureDistinctOn` or `UpsertDistinctOn`

Do you mean that we can push filters down into `UpsertDistinctOn`, but only when `ErrOnDup` flag is false?

> Keys can be null. E.g. the grouping columns from a groupby/distinct

Whoops you're right!

</blockquote></details>

Right, only when `ErrorOnDup` is false (well, now it will be empty string rather than false). That restriction should apply to both `UpsertDistinctOn` when `ErrorOnDup` is true, and `EnsureDistinctOn` (where `ErrorOnDup` is always true).

Ultimately, we have null-handling behavior (which execution operator calls `nullsAreDistinct`) and dup-error behavior (which execution operator calls `errorOnDup`). So we have 2 * 2 = 4 interesting combos. Up until now, only 3/4 of the combos were interesting. This new rule shows that all 4 combos are interesting. While we could represent those 4 combos using 2 flags, I think it's probably better to use 4 separate top-level operators for reasons I gave above.

But I think the question should be open for debate, in case you and Radu think differently.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48006)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/memo/check_expr.go, line 299 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48006#-M5gkf0O2g-3ppkFRTJd:-M5gzsS56hiKA_N_nb7j:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9c6ad3c68d7ce911a5d15e8983c66bbddc57f78/pkg/sql/opt/memo/check_expr.go#L299)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] true -> "a non-empty string"
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1942 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48006#-M5glMBZ7CEgabgXXsVu:-M5h-BT9-79bV8C_UnyE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9c6ad3c68d7ce911a5d15e8983c66bbddc57f78/pkg/sql/opt/norm/custom_funcs.go#L1942)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] I'd call this `MakeErrorOnDupGrouping`
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 704 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48006#-M5gTF0cCNVWdYTSFhJl:-M5h4kvI-GcPq8jflBag:bh2yma7) ([raw file](https://github.com/cockroachdb/cockroach/blob/84dcc23b24eda04a8fc2c79442907e8ef7f7cc60/pkg/sql/opt/norm/rules/decorrelate.opt#L704)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Here's another example where the previous rule failed (could be useful as a test case):
```
root@127.0.0.1:60395/movr> select * from a;
  x | y | z
----+---+----
  1 | 2 | 3
  4 | 5 | 6
(2 rows)

Time: 924µs

root@127.0.0.1:60395/movr> select * from b;
  x
-----
  1
  2
(2 rows)

Time: 570µs

root@127.0.0.1:60395/movr> explain (opt) select * from a where x = (select x from b where y > 0);
               text
----------------------------------
  project
   └── inner-join-apply
        ├── scan a
        ├── max1-row
        │    └── select
        │         ├── scan b
        │         └── filters
        │              └── y > 0
        └── filters
             └── a.x = b.x
(10 rows)

root@127.0.0.1:60395/movr> select * from a where x = (select x from b where y > 0);
ERROR: more than one row returned by a subquery used as an expression
SQLSTATE: 21000
```
If we apply this transformation we'd only get one row:
```
root@127.0.0.1:60395/movr> select * from a inner join lateral (select * from b where y > 0) as b(x)  on a.x = b.x;
  x | y | z | x
----+---+---+----
  1 | 2 | 3 | 1
(1 row)
```
</blockquote></details>

I'll add some logic test cases similar to this one (filtering on a comparison between columns of different tables).

**Review by rytaft — COMMENTED** [review]
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48006)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/ops/relational.opt, line 580 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48006#-M5gw-a7C2v653bZBcEc:-M5hUeiM7vlyJyOfafZH:b-18ml45) ([raw file](https://github.com/cockroachdb/cockroach/blob/84dcc23b24eda04a8fc2c79442907e8ef7f7cc60/pkg/sql/opt/ops/relational.opt#L580)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Right, only when `ErrorOnDup` is false (well, now it will be empty string rather than false). That restriction should apply to both `UpsertDistinctOn` when `ErrorOnDup` is false, and `EnsureDistinctOn` (where `ErrorOnDup` is always false).

Ultimately, we have null-handling behavior (which execution operator calls `nullsAreDistinct`) and dup-error behavior (which execution operator calls `errorOnDup`). So we have 2 * 2 = 4 interesting combos. Up until now, only 3/4 of the combos were interesting. This new rule shows that all 4 combos are interesting. While we could represent those 4 combos using 2 flags, I think it's probably better to use 4 separate top-level operators for reasons I gave above.

But I think the question should be open for debate, in case you and Radu think differently.
</blockquote></details>

4 operators makes sense to me for the reasons you pointed out.

**Review by RaduBerinde — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48006)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/ops/relational.opt, line 580 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48006#-M5gw-a7C2v653bZBcEc:-M5hk7G6AcTU_xy7lZEH:btd51a6) ([raw file](https://github.com/cockroachdb/cockroach/blob/84dcc23b24eda04a8fc2c79442907e8ef7f7cc60/pkg/sql/opt/ops/relational.opt#L580)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

4 operators makes sense to me for the reasons you pointed out.
</blockquote></details>

I agree.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48006)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @DrewKimball, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 712 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48006#-M5njzSo7WoaCYQL4uw1:-M5njzSo7WoaCYQL4uw2:b-e0cahd) ([raw file](https://github.com/cockroachdb/cockroach/blob/65a8dff8bed1eba8bb87a793845dba487d12827d/pkg/sql/opt/norm/rules/decorrelate.opt#L712)):*
> ```
> # value. Or in other words, it indicates that the Max1Row's subquery input would
> # have returned more than one row corresponding to that value. Therefore, the
> # two formulations are equivalent.
> ```

Mention in the comment that the rule only works when we have a "true" On condition, and explain why.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48006)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 712 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48006#-M5njzSo7WoaCYQL4uw1:-M5nsJ3M1WT1rmKse6ro:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/65a8dff8bed1eba8bb87a793845dba487d12827d/pkg/sql/opt/norm/rules/decorrelate.opt#L712)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Mention in the comment that the rule only works when we have a "true" On condition, and explain why.
</blockquote></details>

Done.

**Pull request merged**
