### PR TITLE
roachtest: add tpch_concurrency test

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit adds a new `tpch_concurrency` test which restores the TPCH
data set for scale factor 1 and then attempts to find the largest number
of concurrent queries that the cluster can sustain. Note that we decided
to not include configs w/ and w/o the admission control enabled since
both options have about the same results.

For each iteration (for a given concurrency), the test runs each query
in turn once on each connection. Each query run (successful or
unsuccessful) counts towards that number, and this required adding a new
flag `--count-errors` to the workload.

The test currently has two configs: the default and another with the txn
stats sampling disabled (since the execution stats collection has
non-trivial impact). My hope is that overtime that impact will become
negligible, so only one config will be kept.

Additionally, TPCH Q15 (which creates and drops a view) has been slightly
adjusted to allow it to be executed concurrently (by adding IF NOT
EXISTS modifier when creating the view).

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I still need to figure out how to populate the roachperf dashboards based on the results of running this test, but it is RFAL.

**Comment by yuzefovich** [comment]
Okay, I've just added writing of "perf" artifacts which in combination with https://github.com/cockroachdb/roachperf/pull/75 should give us a couple of dashboards.

**Comment by yuzefovich** [comment]
Friendly ping @cockroachdb/sql-queries - this should be a pretty quick review.

**Review by michae2 — CHANGES_REQUESTED** [review]
Very cool!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71115#-:-MlIpBRI-eqlwIvzlPTD:b-jdo7t9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna and @yuzefovich)

___
*[pkg/cmd/roachtest/tests/tpch_concurrency.go, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71115#-MlIn29c-rENfp0cHGh6:-MlIn29c-rENfp0cHGh7:b-sl6nn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/371e99128ee317fd635f2a809e36b7dfbb7f36a6/pkg/cmd/roachtest/tests/tpch_concurrency.go#L27)):*
> ```Go
> 	setupCluster := func(ctx context.Context, t test.Test, c cluster.Cluster, admissionControl bool) {
> 		c.Put(ctx, t.Cockroach(), "./cockroach", c.Range(1, numNodes-1))
> 		c.Put(ctx, t.DeprecatedWorkload(), "./workload", c.Node(numNodes))
> ```

nit: Is this function deprecated? Should we be using it in new code?
___
*[pkg/cmd/roachtest/tests/tpch_concurrency.go, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71115#-MlIkCK33To3IIfO0b-G:-MlIkCK33To3IIfO0b-H:b-4cn9w6) ([raw file](https://github.com/cockroachdb/cockroach/blob/371e99128ee317fd635f2a809e36b7dfbb7f36a6/pkg/cmd/roachtest/tests/tpch_concurrency.go#L76)):*
> ```Go
> 			cmd := fmt.Sprintf(
> 				"./workload run tpch {pgurl:1-%d} --tolerate-errors "+
> 					"--duration=1h --concurrency=%d", numNodes-1, concurrency,
> ```

Is 1 hour necessary? I guess in the worst case this will take 6 or 7 hours which sounds like a lot of compute and a long time to wait.
___
*[pkg/cmd/roachtest/tests/tpch_concurrency.go, line 89 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71115#-MlIkNvy6yiTRdPTB8-x:-MlIkNvy6yiTRdPTB8-y:b-x0o6xo) ([raw file](https://github.com/cockroachdb/cockroach/blob/371e99128ee317fd635f2a809e36b7dfbb7f36a6/pkg/cmd/roachtest/tests/tpch_concurrency.go#L89)):*
> ```Go
> 		// crash a node in the cluster. The current range is represented by
> 		// [minConcurrency, maxConcurrency).
> 		for minConcurrency < maxConcurrency-1 {
> ```

Do we need to narrow it down to the exact concurrency? Would a slightly larger window (say 8 or 10) be acceptable? (I guess another way of asking is: what is the usual margin of error? Is it above 1 instance of the workload?) Would be nice to stop the binary search a little earlier if it is not useful past a certain delta.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71115)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @stevendanna)

___
*[pkg/cmd/roachtest/tests/tpch_concurrency.go, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71115#-MlIn29c-rENfp0cHGh6:-MlIqhoc2OTj5P0Qa0sN:b-tspo9y) ([raw file](https://github.com/cockroachdb/cockroach/blob/371e99128ee317fd635f2a809e36b7dfbb7f36a6/pkg/cmd/roachtest/tests/tpch_concurrency.go#L27)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: Is this function deprecated? Should we be using it in new code?
</blockquote></details>

I think the idea behind the deprecation of `workload` is that we want to move all features of `workload` binary into `cockroach` binary, and then we would use `cockroach workload` command to run things. However, TPCH workload hasn't been moved there, so I don't know of any workarounds to staging the actual `workload` binary.
___
*[pkg/cmd/roachtest/tests/tpch_concurrency.go, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71115#-MlIkCK33To3IIfO0b-G:-MlIqzYjCl3jnmzzrVp8:b-nsjs69) ([raw file](https://github.com/cockroachdb/cockroach/blob/371e99128ee317fd635f2a809e36b7dfbb7f36a6/pkg/cmd/roachtest/tests/tpch_concurrency.go#L76)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Is 1 hour necessary? I guess in the worst case this will take 6 or 7 hours which sounds like a lot of compute and a long time to wait.
</blockquote></details>

The reasoning behind choosing a pretty long duration is so that all queries get a chance to run at least once. Each connection is executing queries in order (i.e. q1, q2, etc), and because the cluster is totally overloaded, it might take really long time (like minutes or tens of minutes) for a single query to finish. There are 22 queries in the benchmark, so I chose 1 hour as a reasonable guess for the duration that should be sufficient (in most cases) for q22 to run on each connection at least once.

Let me add this context as a comment.

Yeah, it does take a while. I've just checked the last run I have, and after about 40 minutes only 40 or so connections out of 140 executed q22. I reduced the duration to 45 minutes.
___
*[pkg/cmd/roachtest/tests/tpch_concurrency.go, line 89 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71115#-MlIkNvy6yiTRdPTB8-x:-MlIvn7e8brWcuyRguCC:brivuxd) ([raw file](https://github.com/cockroachdb/cockroach/blob/371e99128ee317fd635f2a809e36b7dfbb7f36a6/pkg/cmd/roachtest/tests/tpch_concurrency.go#L89)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Do we need to narrow it down to the exact concurrency? Would a slightly larger window (say 8 or 10) be acceptable? (I guess another way of asking is: what is the usual margin of error? Is it above 1 instance of the workload?) Would be nice to stop the binary search a little earlier if it is not useful past a certain delta.
</blockquote></details>

There is quite a bit of variance for the max supported concurrency for the same binary, which I think is mostly because of different data placement. That's why I added the scatter of tables on each iteration - if there is an "unlucky" placement and a node crashes, but then we usually can support the number of concurrent workers.

I don't see much benefit from stopping the iteration early - are you mostly concerned about costs? If so, I'd rather remove the option with the admission control enabled since it doesn't seem to impact the number much.

**Review by michae2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71115)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna and @yuzefovich)

___
*[pkg/cmd/roachtest/tests/tpch_concurrency.go, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71115#-MlIn29c-rENfp0cHGh6:-MlJ8Y2l9nKYi0Xay8Io:b5rx3h9) ([raw file](https://github.com/cockroachdb/cockroach/blob/371e99128ee317fd635f2a809e36b7dfbb7f36a6/pkg/cmd/roachtest/tests/tpch_concurrency.go#L27)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I think the idea behind the deprecation of `workload` is that we want to move all features of `workload` binary into `cockroach` binary, and then we would use `cockroach workload` command to run things. However, TPCH workload hasn't been moved there, so I don't know of any workarounds to staging the actual `workload` binary.
</blockquote></details>

OK, thanks for explaining!
___
*[pkg/cmd/roachtest/tests/tpch_concurrency.go, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71115#-MlIkCK33To3IIfO0b-G:-MlJ9Pm8-pE7kbRAP-vk:bdyjmoi) ([raw file](https://github.com/cockroachdb/cockroach/blob/371e99128ee317fd635f2a809e36b7dfbb7f36a6/pkg/cmd/roachtest/tests/tpch_concurrency.go#L76)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

The reasoning behind choosing a pretty long duration is so that all queries get a chance to run at least once. Each connection is executing queries in order (i.e. q1, q2, etc), and because the cluster is totally overloaded, it might take really long time (like minutes or tens of minutes) for a single query to finish. There are 22 queries in the benchmark, so I chose 1 hour as a reasonable guess for the duration that should be sufficient (in most cases) for q22 to run on each connection at least once.

Let me add this context as a comment.

Yeah, it does take a while. I've just checked the last run I have, and after about 40 minutes only 40 or so connections out of 140 executed q22. I reduced the duration to 45 minutes.
</blockquote></details>

OK, thanks for the context. It makes sense, and I think either 45 min or an hour is fine.

For the purposes of this measurement, I wish the workload were synchronizing query execution so that all 140 connections executed q1, then all 140 connections executed q2, then q3, etc. And I wish we could wait for all connections to execute all 22 queries and then stop instead of stopping after 1 hour. Seems like it would be a more deterministic measurement than letting each connection run at a different speed. But oh well, this is fine, we will still get a useful signal from this.
___
*[pkg/cmd/roachtest/tests/tpch_concurrency.go, line 89 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71115#-MlIkNvy6yiTRdPTB8-x:-MlMbf056cmq0lNDSBQ5:bdio38r) ([raw file](https://github.com/cockroachdb/cockroach/blob/371e99128ee317fd635f2a809e36b7dfbb7f36a6/pkg/cmd/roachtest/tests/tpch_concurrency.go#L89)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

There is quite a bit of variance for the max supported concurrency for the same binary, which I think is mostly because of different data placement. That's why I added the scatter of tables on each iteration - if there is an "unlucky" placement and a node crashes, but then we usually can support the number of concurrent workers.

I don't see much benefit from stopping the iteration early - are you mostly concerned about costs? If so, I'd rather remove the option with the admission control enabled since it doesn't seem to impact the number much.
</blockquote></details>

Yes, mostly concerned about costs. (I'm assuming this would be run regularly as part of https://roachperf.crdb.dev/ but if that's not true then I'm less concerned.) And also just wondering how useful that last hour will be if 1 is below the margin of error. :slightly_smiling_face: Each iteration of the binary search provides half as much bang for the buck.

I like the idea of removing admission control if it's not a measurable difference.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71115)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @stevendanna)

___
*[pkg/cmd/roachtest/tests/tpch_concurrency.go, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71115#-MlIkCK33To3IIfO0b-G:-MlMsJ-r8awEuG-GfDRL:b2ns8hv) ([raw file](https://github.com/cockroachdb/cockroach/blob/371e99128ee317fd635f2a809e36b7dfbb7f36a6/pkg/cmd/roachtest/tests/tpch_concurrency.go#L76)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

OK, thanks for the context. It makes sense, and I think either 45 min or an hour is fine.

For the purposes of this measurement, I wish the workload were synchronizing query execution so that all 140 connections executed q1, then all 140 connections executed q2, then q3, etc. And I wish we could wait for all connections to execute all 22 queries and then stop instead of stopping after 1 hour. Seems like it would be a more deterministic measurement than letting each connection run at a different speed. But oh well, this is fine, we will still get a useful signal from this.
</blockquote></details>

Hm, it's an interesting point.

I refactored the test so that on each iteration it runs each query in turn three times on all connections. Let me know what you think. I think once might not be sufficient, but three times seems like a reasonable number to "claim" that we can support running all TPCH queries with the fixed concurrency.

I'll manually check how long a single successful iteration (i.e. for a fixed concurrency without crashing) lasts for and might adjust the number of times for each query.
___
*[pkg/cmd/roachtest/tests/tpch_concurrency.go, line 89 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71115#-MlIkNvy6yiTRdPTB8-x:-MlMt1Fq6gX2bgnlP-KX:b-w7e3zl) ([raw file](https://github.com/cockroachdb/cockroach/blob/371e99128ee317fd635f2a809e36b7dfbb7f36a6/pkg/cmd/roachtest/tests/tpch_concurrency.go#L89)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Yes, mostly concerned about costs. (I'm assuming this would be run regularly as part of https://roachperf.crdb.dev/ but if that's not true then I'm less concerned.) And also just wondering how useful that last hour will be if 1 is below the margin of error. :slightly_smiling_face: Each iteration of the binary search provides half as much bang for the buck.

I like the idea of removing admission control if it's not a measurable difference.
</blockquote></details>

This would run every night, and each run would produce the artifacts, which then power the dashboard on roachperf.

Personally, I'm not too concerned about the costs here - we're using a 4 node cluster, each node is `n1-standard-4`, so the whole cluster costs on the order of $1 per hour. If we run this nightly for 7 hours, the cost of $10 seems like nothing in comparison to some other tests that we run on the nightly basis.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71115)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @stevendanna)

___
*[pkg/cmd/roachtest/tests/tpch_concurrency.go, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71115#-MlIkCK33To3IIfO0b-G:-MlNBIOBASKsmmrLoWIp:b-50xy6) ([raw file](https://github.com/cockroachdb/cockroach/blob/371e99128ee317fd635f2a809e36b7dfbb7f36a6/pkg/cmd/roachtest/tests/tpch_concurrency.go#L76)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Hm, it's an interesting point.

I refactored the test so that on each iteration it runs each query in turn three times on all connections. Let me know what you think. I think once might not be sufficient, but three times seems like a reasonable number to "claim" that we can support running all TPCH queries with the fixed concurrency.

I'll manually check how long a single successful iteration (i.e. for a fixed concurrency without crashing) lasts for and might adjust the number of times for each query.
</blockquote></details>

Aw, unfortunately the idea with `--max-ops` flag doesn't work because the query runs that result in errors aren't getting counted. I'll think about it a bit more.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71115)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @stevendanna)

___
*[pkg/cmd/roachtest/tests/tpch_concurrency.go, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71115#-MlIkCK33To3IIfO0b-G:-MlNFAoK7Iwt170g6P_x:btwcxb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/371e99128ee317fd635f2a809e36b7dfbb7f36a6/pkg/cmd/roachtest/tests/tpch_concurrency.go#L76)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Aw, unfortunately the idea with `--max-ops` flag doesn't work because the query runs that result in errors aren't getting counted. I'll think about it a bit more.
</blockquote></details>

Okay, added a flag to count the errors towards `--max-ops`. I think RFAL.

**Review by michae2 — COMMENTED** [review]
Thanks for those changes. I'm curious how long a full run takes now.

Something occurred to me today: supposing we make the system extremely resilient to OOMs (all memory allocations accounted for, admission control, queuing if the system is at capacity, etc). What will happen to this benchmark? Will the concurrency (and duration of the benchmark) go to infinity? Maybe we also need a timeout as a failure condition?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71115#-:-MlOGhcu2NP6Mtufc22l:b-aunaes)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @stevendanna)

___
*[pkg/cmd/roachtest/tests/tpch_concurrency.go, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71115#-MlIkCK33To3IIfO0b-G:-MlOEDSlC66Rca1JGK0k:b-c5j28o) ([raw file](https://github.com/cockroachdb/cockroach/blob/371e99128ee317fd635f2a809e36b7dfbb7f36a6/pkg/cmd/roachtest/tests/tpch_concurrency.go#L76)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Okay, added a flag to count the errors towards `--max-ops`. I think RFAL.
</blockquote></details>

Ha, clever!

**Review by yuzefovich — COMMENTED** [review]
A single successful iteration now takes about 2.5 hours, so I'll try reducing the number of query runs to be once (instead of three times) per query per connection.

> What will happen to this benchmark? Will the concurrency (and duration of the benchmark) go to infinity?

Note that there is a hard coded max boundary on the concurrency which we will never go past, so the test can make at most `log(max-min)` iterations (with currently `min=32, max=256`). 

> Maybe we also need a timeout as a failure condition?

Yeah, there is already a timeout, which is 10h by default.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71115#-:-MlQH_jd3gtp5WTZFvqO:bape8r9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @stevendanna)

___
*[pkg/cmd/roachtest/tests/tpch_concurrency.go, line 89 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71115#-MlIkNvy6yiTRdPTB8-x:-MlQHUoQA4QBIsNWAtui:b-lwp4xw) ([raw file](https://github.com/cockroachdb/cockroach/blob/371e99128ee317fd635f2a809e36b7dfbb7f36a6/pkg/cmd/roachtest/tests/tpch_concurrency.go#L89)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

This would run every night, and each run would produce the artifacts, which then power the dashboard on roachperf.

Personally, I'm not too concerned about the costs here - we're using a 4 node cluster, each node is `n1-standard-4`, so the whole cluster costs on the order of $1 per hour. If we run this nightly for 7 hours, the cost of $10 seems like nothing in comparison to some other tests that we run on the nightly basis.
</blockquote></details>

I'll remove the admission control option since it doesn't seem to offer much insight.

**Review by yuzefovich — COMMENTED** [review]
When running each query once on each connection, the whole test run took about 9 hours with a single iteration taking at most 1h 30min. I've looked into the logs and found that in many cases some connections executed some queries more than once, so I adjusted the workload arguments.

PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71115#-:-MlVb9xd3-gRMqycYhhp:b-dc0h3a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @stevendanna)

**Review by michae2 — CHANGES_REQUESTED** [review]
Ah right, there is already a timeout!

Good catch of the `--max-ops` behavior.

9 hours, hmm. :thinking: It seems kind of wasteful to search the entire space when we know that most of the time max concurrency will be close to an expected number (e.g. the max concurrency found the previous night). I noticed that `tpcc.go` and `kvbench.go` are also trying to find max concurrency of a workload, and they both use something called `search.NewLineSearcher` which takes an expected max concurrency as a starting point. I wonder if that would perform fewer iterations than a binary search?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71115#-:-MlVuC78B6aizZCXP5OR:bkt530d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

**Review by michae2 — APPROVED** [review]
I do see that `tpcc.go` has tests that run for 4 days, so I'm not worried about the duration or cost any more. But I am curious about `search.NewLineSearcher`. Anyway, consider that a suggestion, this :lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71115#-:-MlVxeJhB9E_0Xm7E1UH:b-k503wb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @stevendanna)

**Review by yuzefovich — COMMENTED** [review]
I did look into `search.NewLineSearcher` originally too but decided to not use it for now since I don't really know the stable lower bound for which we pass yet. I think after a couple of weeks we'll be able to adjust the boundaries and use the line searcher then. We can then also make the test fail if the lower bound isn't sustained. Added TODOs for this.

TFTR!

I'll wait for the current run (with the newest binaries) I have to finish and merge this afterwards if everything looks good.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71115#-:-MlW4zvv0gzYfG5MGc1f:b1wv2e4)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @stevendanna)

**Comment by yuzefovich** [comment]
So a single test run on c34dac2605 took about 2 hours and landed at max supported concurrency of 42.

I also finally tracked down the regression between 21.2 and master (#71351), so I'll add another variant to `tpch_concurrency` where we disable the sampling of statements.

**Pull request merged**
