### PR TITLE
sql: add LeakProof volatility

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change adds VolatilityLeakProof and changes a few hashing builtins to use
it (for consistency with postgres).

In postgres, `proleakproof` is a flag separate from `provolatile`, but all
instances of leak-proof operators are immutable.

We also change the volatility to a simple index since it no longer maps to the
postgres volatility directly. In the optimizer, we will need to have a bitfield
for which types of volatilities are contained in an expression so having them be
small consecutive integers is desirable.

Release note: None

image

### CODE REVIEW

**Review by otan — APPROVED** [review]
love the image, heh

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49680#-:-M8T4Tk5COlGmPyzkumX:b-i58pak)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @otan, and @RaduBerinde)

___
*[pkg/sql/sem/tree/volatility.go, line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49680#-M8T4S0T6gUzRHN493qG:-M8T4S0T6gUzRHN493qH:btj03fm) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b7d8f1b238a752a829db46515d7dad339b2c088/pkg/sql/sem/tree/volatility.go#L109)):*
> ```Go
> 		return VolatilityVolatile
> 	default:
> 		panic(errors.AssertionFailedf("invalid provolatile %s", provolatile))
> ```

nit: feels like this should be an error instead of a panic

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49680)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball)

___
*[pkg/sql/sem/tree/volatility.go, line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49680#-M8T4S0T6gUzRHN493qG:-M8T6-YhB1H5TdqyqBP9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b7d8f1b238a752a829db46515d7dad339b2c088/pkg/sql/sem/tree/volatility.go#L109)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: feels like this should be an error instead of a panic
</blockquote></details>

Done.

**Comment by RaduBerinde** [comment]
Had to make some fixes. I documented the values as being ordered so you could check `x > VolatilityImmutable`.

**Review by otan — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 3 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49680)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball)

**Comment by RaduBerinde** [comment]
TFTR!

bors r+

**Review by mgartner — APPROVED** [review]
Brilliant!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49680#-:-M8XCDAR8e7rK4EGQmQw:bo7sk6n)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball)

**Pull request merged**
