### PR TITLE
concurrency: add lock table verification for lock promotion state

### LINKED ISSUE #120909: concurrency: add lock table validation for lock promotions
**Describe the problem**

We should extend lock table validation to include runtime assertions around lock promotions. In particular, we should validate:

- A request in the lock's wait queue with `queueOrder.isPromoting = true ` should belong to a transaction that holds a lock 
- If a request is in the lock's wait queue and it belongs to a transaction that holds the lock, then it must be accessing the lock with a stronger lock strength than the strength it already holds the lock with.
- A request in the lock's wait queue with `queueOrder.isPromoting = false` should belong to a transaction that doesn't hold a lock

Jira issue: CRDB-36941

### PR DESCRIPTION
**Pull request by arulajmani**
Closes https://github.com/cockroachdb/cockroach/issues/120909

Release note: None

### CODE REVIEW

**Comment by arulajmani** [comment]
Ran `TestLockTableConcurrentRequests` for 3,000 runs and `KVNemesis` for 300, and so far so good. I'll stress `KVNemesis` a bit more.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122056#-:-Nv8lMfq61Znmc5-tbfl:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 3895 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122056#-Nv8kvmQ3GGxex1BxgG2:-Nv8kvmQ3GGxex1BxgG3:bsonnzz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c54029de9cc95dfbb5d3429e9774c6a18fbe3fb/pkg/kv/kvserver/concurrency/lock_table.go#L3895)):*
> ```Go
> 			}
> 		}
> 		// TODO(arul): uncomment once 115694 is resolved. This validation has been
> ```

Now that #115694 is resolved, should we try to recover this assertion?
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 3970 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122056#-Nv8l7WN5QXPUQLA3zu-:-Nv8l7WN5QXPUQLA3zu0:b-1jheaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c54029de9cc95dfbb5d3429e9774c6a18fbe3fb/pkg/kv/kvserver/concurrency/lock_table.go#L3970)):*
> ```Go
> 		// and requests that don't shouldn't.
> 		if _, held := kl.heldBy[e.Value.guard.txnMeta().ID]; held != e.Value.order.isPromoting {
> 			return errors.AssertionFailedf("mismatched notion of promoting and lock held status")
> ```

nit: is it worth indicating which direction this is mismatched to cut down on uncertainty if/when this fires? Or do we dump enough context elsewhere when these assertions fire that we'll be able to tell?

**Review by arulajmani — COMMENTED** [review]
TFTR!

bors r=nvanbenschoten

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122056#-:-Nv8p36sBQvYLMbEC5YN:b-l0r5kv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 3895 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122056#-Nv8kvmQ3GGxex1BxgG2:-Nv8oK-MARWqthic-IlS:btpu3u9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c54029de9cc95dfbb5d3429e9774c6a18fbe3fb/pkg/kv/kvserver/concurrency/lock_table.go#L3895)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Now that #115694 is resolved, should we try to recover this assertion?
</blockquote></details>

Even though that issue is closed (as a duplicate of https://github.com/cockroachdb/cockroach/issues/115598, initial failures of which haven't been addressed), we'll likely run into the same issue again if we uncomment this naively. We've spoken about this before, so you know this is one of the things I want to get to in stability, so I'll file a new GA-blocker issue to uncomment this bit. 
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 3970 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122056#-Nv8l7WN5QXPUQLA3zu-:-Nv8obqK091yTji625h3:bqnbns6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c54029de9cc95dfbb5d3429e9774c6a18fbe3fb/pkg/kv/kvserver/concurrency/lock_table.go#L3970)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: is it worth indicating which direction this is mismatched to cut down on uncertainty if/when this fires? Or do we dump enough context elsewhere when these assertions fire that we'll be able to tell?
</blockquote></details>

We dump out the entire lock table whenever there's a validation failure, so we should have enough to make sense of errors.

**Comment by arulajmani** [comment]
Failure looks unrelated, though I can't seem to find the artifacts to verify. I'll give this another go in bors.

bors retry

**Pull request merged**
