### PR TITLE
sql: use same precedence for |, #, &

### PR DESCRIPTION
**Pull request by madelynnblue**
This changes the precedence of these operators to match Postgres. As
described in #14968, we attempt to match Postgres unless we think there
is enough reason to differ from their choice. The logical equivalents
of `|` and `&` have differing precedence, which is common among
programming languages. However here there is also the `#` operator,
and it's not clear where that should bind in the ordering. Because
of that ambiguity (which wouldn't be predictable by users) I do not
think there is enough of a reason to differ from Postgres.

See also #14908

### CODE REVIEW

**Comment by knz** [comment]
Wait what what's going on here again :)
Is there an application that breaks because of our choices here?
I'm a bit less worried here than with `~` however I would like to highlight that from the algebraic standpoint OR is equivalent to `+` and AND is equivalent to `*` and that it is customary (read: every programming language under the sun with operand precedence) to have them associate in this way. I am not sure we want to do anything different unless we have a good reason to do so.

**Comment by knz** [comment]
Also, (what I would write regardless of whether I agree with the change or not) I would recommend that you write some more motivation in your commit messages for your changes -- in general.

**Comment by mjibson** [comment]
I think this will be abandoned based on how the RFC PR is going.

**Comment by mjibson** [comment]
I've updated the commit message with justification about why this should go in.

**Comment by bdarnell** [comment]
LGTM, although my preference for postgres-compatibility in this sort of thing is tempered by the fact that nearly everything but postgres uses different precedence. I wouldn't object to keeping things as they are now either.

**Comment by mjibson** [comment]
I'm also fine keeping things as they are. I don't see a super strong reason to change it. @jordanlewis do you have an opinion from ORM land?

**Comment by knz** [comment]
After digging a bit in pg's code I want to provide a little context for "why pg does it differently from everyone else". This has to do with pg's ability to extend the language via external modules. 

From an implementation standpoint it is slightly easier (and it used to be much easier) to make the priority of all operators the same at a level where plug-ins can add new operators; this avoids needing to invent an API for plug-ins to set custom operator precedences, with all the associated heartache ("how to make sure that plugin's operator precedence is always higher than that other one?" etc). However, since the pg  tea,made that decision, there was progress in parsing, software engineering and PL engineering techniques which make this mostly a non-problem. If this was to be done again today they would likely make different choices.

Regardless of whether we want to follow pg on this, it won't be because "the pg guys know what they're doing better than we do".

**Comment by jordanlewis** [comment]
Thanks for the analysis @knz! @mjibson and I came to the same conclusion based on their docs - in the [section on precedence](https://www.postgresql.org/docs/9.6/static/sql-syntax-lexical.html), there's a single catchall precedence for all custom operators.

I don't think that choosing our own path on this one will cause problems for any ORMs or other sources of programmatic queries, so I'm okay with this not going in as well.

**Comment by mjibson** [comment]
Great. Closing.

**Pull request closed without merging**
