### PR TITLE
kvserver: counters for intent resolution failures

### LINKED ISSUE #64267: kvserver: add metrics for intent cleanup failures
As seen in #60585, intents can accumulate over time, but it is not clear why this happens since we actively try to clean up intents via multiple mechanisms. We should add some relevant metrics that may help us debug this, e.g.:

* intent resolution failures (particularly after a successful EndTxn)
* EndTxn failures (particularly errors that can't be retried)
* Intent counts for ranged intent cleanup operations (variants of e.g. `intents.resolve-attempts`)

There are probably others that would be useful as well.

### PR DESCRIPTION
**Pull request by aliher1911**
We don't have enough visibility of what is causing intent build up.
To address the issue, this diff adds number of counters that would
track failures per case:
- when transaction fails to cleanup intents while handling EndTxn
  while succeeding or being cancelled by caller:
  intentresolver.finalized_txns.failed,
  intents.resolve_conflicting.rejected,
  intents.finalized_txns.timed_out
- when gc fails to cleanup intents or local transactions:
  queue.gc.info.resolvefailed,
  queue.gc.info.transactionresolvefailed
- when intents fail to push by conflicting transaction when locking
  intents.resolve_conflicting.rejected
- when transaction fails to send abort after failure:
  txn.rollbacks.failed, txn.rollbacks.async.failed

Release note: None

### CODE REVIEW

**Review by erikgrinaker — COMMENTED** [review]
Looks good overall!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-:-Ma86qeB6G8H1b6OgNsE:b-89nrqy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911)

___
*[pkg/kv/kvserver/gc_queue.go, line 476 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-Ma86smc4zYg5M9vrTrG:-Ma86smc4zYg5M9vrTrH:bf0wm0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ffa6eae074d9c4e8c8b3c6d2cebe4dffb4e8e28/pkg/kv/kvserver/gc_queue.go#L476)):*
> ```Go
> 			} else {
> 				// TODO(oleg): Cleanup failed on found garbage intents
> 				gcq.store.intentResolver.Metrics().GCIntentCleanupFailed.Inc(1)
> ```

I feel like these metrics should be stored on the components that emit them rather than the intent resolver, while the intent resolver metrics should cover metrics that are emitted by the intent resolver itself.

For example, we already have `GCResolveSuccess` on the store here, shouldn't the corresponding failure metric be `gcq.store.metrics.GCResolveFailure`?

**Comment by aliher1911** [comment]
___
*[pkg/kv/kvserver/gc_queue.go, line 476 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-Ma86smc4zYg5M9vrTrG:-Ma9N37L9x1quGuYAPPX:b-b8s9aq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ffa6eae074d9c4e8c8b3c6d2cebe4dffb4e8e28/pkg/kv/kvserver/gc_queue.go#L476)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I feel like these metrics should be stored on the components that emit them rather than the intent resolver, while the intent resolver metrics should cover metrics that are emitted by the intent resolver itself.

For example, we already have `GCResolveSuccess` on the store here, shouldn't the corresponding failure metric be `gcq.store.metrics.GCResolveFailure`?
</blockquote></details>

Yeah, I was actually torn on that. Should they be named/prefixed consistently to show that they belong to a certain area or should they be grouped together. I think another possibility is to have a single struct, store it inside store metrics and pass pointer to components as some of the metrics do.

**Comment by erikgrinaker** [comment]
I think for the external (user-facing) metric names, they should be grouped by area (e.g. all intent-related metrics should be `intent.`-prefixed or something). However, in the code I think each component should maintain their own relevant metrics to reduce coupling between components. That said, I haven't looked too closely at what the existing metrics code does, so if there is an established pattern then let's be consistent with that.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65402)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911)

___
*[pkg/kv/kvserver/gc_queue.go, line 476 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-Ma86smc4zYg5M9vrTrG:-Ma9Q1_a-vqmRRgzasie:b-eyuunr) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ffa6eae074d9c4e8c8b3c6d2cebe4dffb4e8e28/pkg/kv/kvserver/gc_queue.go#L476)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Yeah, I was actually torn on that. Should they be named/prefixed consistently to show that they belong to a certain area or should they be grouped together. I think another possibility is to have a single struct, store it inside store metrics and pass pointer to components as some of the metrics do.
</blockquote></details>

I think for the external (user-facing) metric names, they should be grouped by area (e.g. all intent-related metrics should be intent.-prefixed or something). However, in the code I think each component should maintain their own relevant metrics to reduce coupling between components. That said, I haven't looked too closely at what the existing metrics code does, so if there is an established pattern then let's be consistent with that.

**Review by aliher1911 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65402)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[pkg/kv/kvserver/gc_queue.go, line 476 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-Ma86smc4zYg5M9vrTrG:-MaEShxMAzhk6vO07_aF:btchj6m) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ffa6eae074d9c4e8c8b3c6d2cebe4dffb4e8e28/pkg/kv/kvserver/gc_queue.go#L476)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I think for the external (user-facing) metric names, they should be grouped by area (e.g. all intent-related metrics should be intent.-prefixed or something). However, in the code I think each component should maintain their own relevant metrics to reduce coupling between components. That said, I haven't looked too closely at what the existing metrics code does, so if there is an established pattern then let's be consistent with that.
</blockquote></details>

Moved them to store where applicable and passed metrics to concrete components where needed in line with what other components do. I think that is less coupling because they are linked together only at the time of creation.

**Review by aliher1911 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65402)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[pkg/kv/kvserver/gc_queue.go, line 476 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-Ma86smc4zYg5M9vrTrG:-MaTefPq96Sr4pxtw5lY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ffa6eae074d9c4e8c8b3c6d2cebe4dffb4e8e28/pkg/kv/kvserver/gc_queue.go#L476)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Moved them to store where applicable and passed metrics to concrete components where needed in line with what other components do. I think that is less coupling because they are linked together only at the time of creation.
</blockquote></details>

Done.

**Review by erikgrinaker — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65402)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911)

___
*[pkg/kv/kvserver/gc_queue.go, line 476 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-Ma86smc4zYg5M9vrTrG:-MaXowvc4lLKucIIlzHO:b-vqfcqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ffa6eae074d9c4e8c8b3c6d2cebe4dffb4e8e28/pkg/kv/kvserver/gc_queue.go#L476)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Shouldn't this be called `GCResolveFailed` since it's the inverse of `GCResolveSuccess`?  The units are also different: success uses number of intents, while failed uses number of attempts.

If I'm reading this correctly, the rest of the code basically just uses `len(intents)` so we should do the same here -- I don't think that's always accurate (there can be range intents or partial failures), but at least the numbers would mean the same thing across `GCResolve` metrics.
___
*[pkg/kv/kvserver/metrics.go, line 1048 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-MaXuA-BDOuBarkHM6wY:-MaXuA-BDOuBarkHM6wZ:b-4qaar) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ebd4c22e3301cde6992ceb485aeed3bbf6fc7b7/pkg/kv/kvserver/metrics.go#L1048)):*
> ```Go
> 
> 	metaConflictingIntentsResolveRejected = metric.Metadata{
> 		Name:        "intent_cleanup.resolve_conflicting.rejected",
> ```

We already have an existing `intents.` prefix, lets use that (and group these with the existing ones).
___
*[pkg/kv/kvserver/metrics.go, line 1054 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-MaXqMXk9ShFrI_a36-3:-MaXqMXk9ShFrI_a36-4:b-tz0ycw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ebd4c22e3301cde6992ceb485aeed3bbf6fc7b7/pkg/kv/kvserver/metrics.go#L1054)):*
> ```Go
> 	}
> 	metaGCIntentResolveFailed = metric.Metadata{
> 		Name:        "intents_cleanup.gc.failed",
> ```

This should be `queue.gc.info.resolvefailed`, and it should be grouped with the other relevant GC metrics.
___
*[pkg/kv/kvserver/metrics.go, line 1268 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-MaXqTNV6GjeWTn1Il-_:-MaXqTNV6GjeWTn1Il-a:bwhozfz) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ebd4c22e3301cde6992ceb485aeed3bbf6fc7b7/pkg/kv/kvserver/metrics.go#L1268)):*
> ```Go
> 	ConflictingIntentResolveRejected *metric.Counter
> 	FinalizedTxnCleanupTimedOut      *metric.Counter
> 	GCIntentResolveFailed            *metric.Counter
> ```

Ditto, group with GC metrics.
___
*[pkg/kv/kvserver/replica_write.go, line 323 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-MaXtOF2Drp0H-GMCvu_:-MaXtOF2Drp0H-GMCvua:b-oxwly2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ebd4c22e3301cde6992ceb485aeed3bbf6fc7b7/pkg/kv/kvserver/replica_write.go#L323)):*
> ```Go
> 						if err != nil {
> 							log.Warningf(ctx, "transaction cleanup failed: %v", err)
> 							r.store.metrics.FinalizedTxnCleanupTimedOut.Inc(1)
> ```

It seems a bit excessive to have a dedicated metric only for this case alone, since we expect this case to be very rare. I think what we care about here are `EndTxn` requests that fail (in this case the request would have failed with a context error), I don't think we've added any metrics for that?
___
*[pkg/kv/kvserver/intentresolver/intent_resolver.go, line 695 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-MaXx7LG3l3mzuqTK91a:-MaXx7LG3l3mzuqTK91b:bkrvpgp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ebd4c22e3301cde6992ceb485aeed3bbf6fc7b7/pkg/kv/kvserver/intentresolver/intent_resolver.go#L695)):*
> ```Go
> 		},
> 	); err != nil {
> 		ir.Metrics.GCTxnIntentsCleanupFailed.Inc(1)
> ```

I think we'll want to handle these in the GC queue, since all the other relevant metrics (`GCPushTxn` and `GCResolveSuccess`) are handled there via the `onComplete` hook.
___
*[pkg/kv/kvserver/intentresolver/metrics.go, line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-MaXw1ut-oOZNpnUeyIY:-MaXw1ut-oOZNpnUeyIZ:b9vpqlw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ebd4c22e3301cde6992ceb485aeed3bbf6fc7b7/pkg/kv/kvserver/intentresolver/metrics.go#L24)):*
> ```Go
> 	}
> 	metaGCTxnIntentsCleanupFailed = metric.Metadata{
> 		Name:        "intent_cleanup.gc.transaction_intents.failed",
> ```

These should use either the `intentresolver` prefix or `intents` prefix, to be consistent with existing metrics.
___
*[pkg/ts/catalog/chart_catalog.go, line 906 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-MaXx4NDBDyEEoUtI1Gf:-MaXx4NDBDyEEoUtI1Gg:b-807afe) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ebd4c22e3301cde6992ceb485aeed3bbf6fc7b7/pkg/ts/catalog/chart_catalog.go#L906)):*
> ```Go
> 					"intent_cleanup.finalized_txns.failed",
> 					"intent_cleanup.resolve_conflicting.rejected",
> 					"intents_cleanup.gc.failed",
> ```

Typo?

**Review by aliher1911 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65402)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[pkg/kv/kvserver/gc_queue.go, line 476 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-Ma86smc4zYg5M9vrTrG:-Mahx-wN1E3pPFssbvFF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ffa6eae074d9c4e8c8b3c6d2cebe4dffb4e8e28/pkg/kv/kvserver/gc_queue.go#L476)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Shouldn't this be called `GCResolveFailed` since it's the inverse of `GCResolveSuccess`?  The units are also different: success uses number of intents, while failed uses number of attempts.

If I'm reading this correctly, the rest of the code basically just uses `len(intents)` so we should do the same here -- I don't think that's always accurate (there can be range intents or partial failures), but at least the numbers would mean the same thing across `GCResolve` metrics.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/metrics.go, line 1048 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-MaXuA-BDOuBarkHM6wY:-MahxQvG9ueCbP5TRrHq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ebd4c22e3301cde6992ceb485aeed3bbf6fc7b7/pkg/kv/kvserver/metrics.go#L1048)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

We already have an existing `intents.` prefix, lets use that (and group these with the existing ones).
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/metrics.go, line 1054 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-MaXqMXk9ShFrI_a36-3:-MahxRJg1cmN4ol7SMQu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ebd4c22e3301cde6992ceb485aeed3bbf6fc7b7/pkg/kv/kvserver/metrics.go#L1054)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

This should be `queue.gc.info.resolvefailed`, and it should be grouped with the other relevant GC metrics.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/metrics.go, line 1268 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-MaXqTNV6GjeWTn1Il-_:-MahxSXE0ldvIg-2674U:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ebd4c22e3301cde6992ceb485aeed3bbf6fc7b7/pkg/kv/kvserver/metrics.go#L1268)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Ditto, group with GC metrics.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_write.go, line 323 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-MaXtOF2Drp0H-GMCvu_:-Mai4hJW6-2_okKcL97W:b-cunqrf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ebd4c22e3301cde6992ceb485aeed3bbf6fc7b7/pkg/kv/kvserver/replica_write.go#L323)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

It seems a bit excessive to have a dedicated metric only for this case alone, since we expect this case to be very rare. I think what we care about here are `EndTxn` requests that fail (in this case the request would have failed with a context error), I don't think we've added any metrics for that?
</blockquote></details>

Do you mean we need a metric to track if the actual proposal fails? Isn't that tracked by distsender per request stats?

We currently track cleanup failures:
- in this place (context was cancelled while waiting for proposal and we try to cleanup) - so we cleanup but fail to get cleanup results.
- errors during cleanup tracked inside resolver for failed or cancelled calls
___
*[pkg/kv/kvserver/intentresolver/intent_resolver.go, line 695 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-MaXx7LG3l3mzuqTK91a:-MajUslKEs1BrXQp03lT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ebd4c22e3301cde6992ceb485aeed3bbf6fc7b7/pkg/kv/kvserver/intentresolver/intent_resolver.go#L695)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I think we'll want to handle these in the GC queue, since all the other relevant metrics (`GCPushTxn` and `GCResolveSuccess`) are handled there via the `onComplete` hook.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/intentresolver/metrics.go, line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-MaXw1ut-oOZNpnUeyIY:-MajUxrl4Ht-XRG5_z9l:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ebd4c22e3301cde6992ceb485aeed3bbf6fc7b7/pkg/kv/kvserver/intentresolver/metrics.go#L24)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

These should use either the `intentresolver` prefix or `intents` prefix, to be consistent with existing metrics.
</blockquote></details>

Done.
___
*[pkg/ts/catalog/chart_catalog.go, line 906 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-MaXx4NDBDyEEoUtI1Gf:-MajXvC68uaVSr5erEla:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ebd4c22e3301cde6992ceb485aeed3bbf6fc7b7/pkg/ts/catalog/chart_catalog.go#L906)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Typo?
</blockquote></details>

Done.

**Review by aliher1911 — COMMENTED** [review]
I commit and PR message by which metrics and where they are updated for clarity.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-:-Mami2w_CdqccXnnIiwP:bhagndc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

**Review by erikgrinaker — COMMENTED** [review]
> Reviewed 11 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65402)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911)

___
*[pkg/kv/kvserver/replica_write.go, line 323 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-MaXtOF2Drp0H-GMCvu_:-Majekzm8qtyvB-IlGTc:b-l0w5xt) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ebd4c22e3301cde6992ceb485aeed3bbf6fc7b7/pkg/kv/kvserver/replica_write.go#L323)):*
> Do you mean we need a metric to track if the actual proposal fails? Isn't that tracked by distsender per request stats?

We want to know about EndTxn requests that fail, for whatever reason (possibly even separated by commit=true/false?). From what I can tell, the distsender only tracks per-method sent counts and per-errortype error counts?

It's great that we track these other metrics, but if the EndTxn request fails then it may never even get to the point where it starts intent cleanup.

**Review by aliher1911 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65402)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[pkg/kv/kvserver/replica_write.go, line 323 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-MaXtOF2Drp0H-GMCvu_:-Mb7eo4P0Uj3BeZYThoY:bywgau8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ebd4c22e3301cde6992ceb485aeed3bbf6fc7b7/pkg/kv/kvserver/replica_write.go#L323)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

> Do you mean we need a metric to track if the actual proposal fails? Isn't that tracked by distsender per request stats?

We want to know about EndTxn requests that fail, for whatever reason (possibly even separated by commit=true/false?). From what I can tell, the distsender only tracks per-method sent counts and per-errortype error counts?

It's great that we track these other metrics, but if the EndTxn request fails then it may never even get to the point where it starts intent cleanup.
</blockquote></details>

Ah I see! I was so confused by those two arrays of metrics so I thought they are indexed by the same. So adding it to dist sender seems completely unjustifiable. Tracking it where request is created is probably more appropriate in that case. Let me add it then.

**Review by aliher1911 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65402)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[pkg/kv/kvserver/replica_write.go, line 323 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-MaXtOF2Drp0H-GMCvu_:-MbBYcQM3RYglfkPPIaX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ebd4c22e3301cde6992ceb485aeed3bbf6fc7b7/pkg/kv/kvserver/replica_write.go#L323)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Ah I see! I was so confused by those two arrays of metrics so I thought they are indexed by the same. So adding it to dist sender seems completely unjustifiable. Tracking it where request is created is probably more appropriate in that case. Let me add it then.
</blockquote></details>

Done.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65402)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @erikgrinaker)

___
*[pkg/kv/kvserver/replica_write.go, line 323 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-MaXtOF2Drp0H-GMCvu_:-MbC0s2jD0cvBYXio4Fk:bt0mohe) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ebd4c22e3301cde6992ceb485aeed3bbf6fc7b7/pkg/kv/kvserver/replica_write.go#L323)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks, looks good! A couple of questions:

* Is this the right place in the stack for this? For example, we already have a metrics interceptor (`txnMetricRecorder`) right below `txnCommitter`. On the other hand, we have interceptors above (e.g. `txnSpanRefresher`) that does internal retries. Also, what about errors that originate further up in the stack, do we care about those?
* Maybe we should add success metrics as well? Or do we already have relevant metrics for this?

**Review by aliher1911 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65402)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[pkg/kv/kvserver/replica_write.go, line 323 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-MaXtOF2Drp0H-GMCvu_:-MbCJEbT73UP_FK7p0eV:b-hpbwvk) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ebd4c22e3301cde6992ceb485aeed3bbf6fc7b7/pkg/kv/kvserver/replica_write.go#L323)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Thanks, looks good! A couple of questions:

* Is this the right place in the stack for this? For example, we already have a metrics interceptor (`txnMetricRecorder`) right below `txnCommitter`. On the other hand, we have interceptors above (e.g. `txnSpanRefresher`) that does internal retries. Also, what about errors that originate further up in the stack, do we care about those?
* Maybe we should add success metrics as well? Or do we already have relevant metrics for this?
</blockquote></details>

Fair question, maybe we could simplify that. I was trying to avoid getting too deep into the error handling logic of committer where it can distinguish different types of errors that might need replicating to understand what is going on. On the other hand metric collector already tells us final state of transaction and updates counters based on that, so maybe just adding a less granular metric for failures is good enough? It currently measures committed and aborted transactions which also include "pending" ones when sender is destroyed.

https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvclient/kvcoord/txn_interceptor_metric_recorder.go#L114

If we treat it as an error to commit that would give us enough info i think.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65402)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @erikgrinaker)

___
*[pkg/kv/kvserver/replica_write.go, line 323 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-MaXtOF2Drp0H-GMCvu_:-MbCPRkU7EbxIx5sCdNq:b-rvk0t8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ebd4c22e3301cde6992ceb485aeed3bbf6fc7b7/pkg/kv/kvserver/replica_write.go#L323)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Fair question, maybe we could simplify that. I was trying to avoid getting too deep into the error handling logic of committer where it can distinguish different types of errors that might need replicating to understand what is going on. On the other hand metric collector already tells us final state of transaction and updates counters based on that, so maybe just adding a less granular metric for failures is good enough? It currently measures committed and aborted transactions which also include "pending" ones when sender is destroyed.

https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvclient/kvcoord/txn_interceptor_metric_recorder.go#L114

If we treat it as an error to commit that would give us enough info i think.
</blockquote></details>

I'm not sure if that will do what we want. For example, if you look at this piece of code:

https://github.com/cockroachdb/cockroach/blob/cfb4b95d94e717e985423d5313c58187fbde5da4/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L788-L796

Here, we set the txn status to ABORTED, but then asynchronously send off an EndTxn(commit=false) and also call cleanupTxnLocked() which will call closeLocked(). From the point of view of the txnMetricRecorder it will consider the txn successfully rolled back, but we don't know if the EndTxn request succeeded or not (because it's async, so it hasn't been sent yet -- it's waiting to acquire the TxnCoordSender.mu lock).

It seems like we have a couple of options: either record the raw EndTxn errors in txnMetricRecorder as they happen (doesn't take into account retries), or record them at the top of the stack in TxnCoordSender (can take into account retries and stuff, but will not notice the txnHeartbeater requests). I'm leaning towards just keeping it simple and recording every error in txnMetricRecorder, but haven't looked at this in any detail and I'm curious to get your thoughts.

**Review by aliher1911 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65402)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[pkg/kv/kvserver/replica_write.go, line 323 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-MaXtOF2Drp0H-GMCvu_:-Mb_xYU21BGL_PwjBgkZ:bbd60kd) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ebd4c22e3301cde6992ceb485aeed3bbf6fc7b7/pkg/kv/kvserver/replica_write.go#L323)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I'm not sure if that will do what we want. For example, if you look at this piece of code:

https://github.com/cockroachdb/cockroach/blob/cfb4b95d94e717e985423d5313c58187fbde5da4/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L788-L796

Here, we set the txn status to ABORTED, but then asynchronously send off an EndTxn(commit=false) and also call cleanupTxnLocked() which will call closeLocked(). From the point of view of the txnMetricRecorder it will consider the txn successfully rolled back, but we don't know if the EndTxn request succeeded or not (because it's async, so it hasn't been sent yet -- it's waiting to acquire the TxnCoordSender.mu lock).

It seems like we have a couple of options: either record the raw EndTxn errors in txnMetricRecorder as they happen (doesn't take into account retries), or record them at the top of the stack in TxnCoordSender (can take into account retries and stuff, but will not notice the txnHeartbeater requests). I'm leaning towards just keeping it simple and recording every error in txnMetricRecorder, but haven't looked at this in any detail and I'm curious to get your thoughts.
</blockquote></details>

Good catch, this seem to be the only place where we set abort specifically and break the normal flow. I added it as a separate metric. The inconvenience there is that we use async cleanup in two ways, send it out and ignore the result and send it out and wait for result if another abort is sent which would wait for this one and return its error for retry. But I think it should be ok if we just count those async failures regardless if it goes into failed transactions or not in another counter.

**Review by erikgrinaker — APPROVED** [review]
:lgtm: @andreimatei may want to have a quick look as well.

> Reviewed 9 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-:-MbaNGO2DfKyBcfCDAab:b-taupaz)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aliher1911)

**Review by andreimatei — APPROVED** [review]
:lgtm: 

Nit: I think the commit text diverged from the merge message; please copy it over to make them the same.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-:-MbbLt3A60DGgjEmLCrj:b-53cp6x)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @aliher1911)

___
*[pkg/kv/kvclient/kvcoord/txn_metrics.go, line 53 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-MbbM26Y3Gbfye6gR0Gw:-MbbM26Z17f55C0t0p65:b-hbqz88) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a56c37f8b0645ec215c096cec50d47433e5c046/pkg/kv/kvclient/kvcoord/txn_metrics.go#L53)):*
> ```Go
> 
> 	// End transaction failure counters.
> 	AbortsFailed      *metric.Counter
> ```

nit: I'd prefer s/Abort/Rollback everywhere. I think "abort" is can mean different things; "rollback" is specific to a client action (i.e sending an `EndTxn{commit:false}` request) , which I think is nice.
___
*[pkg/kv/kvserver/metrics.go, line 1250 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-MbbPTSO59YPasniE3br:-MbbPTSPAbLjR-SSdEsV:b-xdqm1g) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a56c37f8b0645ec215c096cec50d47433e5c046/pkg/kv/kvserver/metrics.go#L1250)):*
> ```Go
> 	GCResolveTotal               *metric.Counter
> 	GCResolveSuccess             *metric.Counter
> 	GCResolveFailed              *metric.Counter
> ```

please add a comment here explaining the differences between these two metrics

**Review by aliher1911 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65402)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @aliher1911 and @andreimatei)

___
*[pkg/kv/kvclient/kvcoord/txn_metrics.go, line 53 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65402#-MbbM26Y3Gbfye6gR0Gw:-MbbYo2iE82_uWqMiiK_:b-1ftbfl) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a56c37f8b0645ec215c096cec50d47433e5c046/pkg/kv/kvclient/kvcoord/txn_metrics.go#L53)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: I'd prefer s/Abort/Rollback everywhere. I think "abort" is can mean different things; "rollback" is specific to a client action (i.e sending an `EndTxn{commit:false}` request) , which I think is nice.
</blockquote></details>

In this case I don't think we refer to a rollback by client, because it could also be result of transaction restarting with new id and we do async rollback of original one. So I was not sure what would be the better name. I'll rename as you suggest!

**Comment by aliher1911** [comment]
bors r=andreimatei,erikgrinaker

**Pull request merged**
