### PR TITLE
roachprod: handle nodeIPPorts map update atomicity

### LINKED ISSUE #124400: roachprod: fails with concurrent update on map error
nightly failed with error:
05:51:29   === RUN   acceptance/gossip/restart  [metrics: https://go.crdb.dev/roachtest-grafana/teamcity-15320942/acceptance-gossip-restart/1716097889536/1716099689536
05:51:30   fatal error: concurrent map writes
05:51:30   
05:51:30   goroutine 2812 [running]:
05:51:30   github.com/cockroachdb/cockroach/pkg/roachprod.updatePrometheusTargets.func1(_, {{0xc002c314a0, 0x2b}, {0x44aa200, 0xedddb899c, 0xc002ffc4d0}, {0x0, 0x0, 0x0}, 0x274a48a78000, ...})
05:51:30     github.com/cockroachdb/cockroach/pkg/roachprod/roachprod.go:811 +0x2c8
05:51:30   created by github.com/cockroachdb/cockroach/pkg/roachprod.updatePrometheusTargets in goroutine 2445
05:51:30     github.com/cockroachdb/cockroach/pkg/roachprod/roachprod.go:802 +0x27f

Jira issue: CRDB-38873

### PR DESCRIPTION
**Pull request by nameisbhaskar**
when creating cluster config service discovery
for each node happens concurrently, and the
information is added to a common map. If the
map getting updated at the same time, roachprod
panics for concurrent update.
the fix is to have a mutex to protect the same.

Fixes: #124400
Epic: none

### CODE REVIEW

**Review by srosenberg — APPROVED** [review]

**Comment by srosenberg** [comment]
Linter failed with,

```
gen-lint_test.go:705: 
        roachprod/roachprod.go:798:	nodeIPPortsMutex := sync.RWMutex{} <- forbidden; use 'syncutil.{,RW}Mutex' instead
```

**Comment by nameisbhaskar** [comment]
Thanks @srosenberg for reviewing it!

**Review by renatolabs — APPROVED** [review]

**Comment by nameisbhaskar** [comment]
bors r=@srosenberg

**Comment by nameisbhaskar** [comment]
Thanks @renatolabs!

**Pull request merged**
