### PR TITLE
hlc: remove the Synthetic field from Timestamp and LegacyTimestamp

### LINKED ISSUE #101938: kv: remove synthetic timestamps
Synthetic timestamps have been deprecated since v22.2 and the introduction of `ClockTimestamps`. We can now remove them.

Jira issue: CRDB-27190

### PR DESCRIPTION
**Pull request by nvb**
Closes #101938.

This PR completes the work to remove the `Synthetic` field from `Timestamp` and `LegacyTimestamp`. It removes the remaining uses, removes the fields from the proto definitions, and removes all access to the fields in methods.

Release note: None

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
`TestBelowRaftProtosDontChange/RangeAppliedState` is failing, correctly detecting that we store synthetic timestamps in the `RangeAppliedState`. Specifically, `RangeAppliedState.RaftClosedTimestamp.Synthetic` can be set to true for GLOBAL tables. This is going to make the migration difficult, because while we don't include the `RangeAppliedState` in [full range consistency checks](https://github.com/cockroachdb/cockroach/blob/1cb6120af50d59a0db7d171cd026716b8174e59e/pkg/storage/mvcc.go#L7150), we do include it in [stats-only consistency checks](https://github.com/cockroachdb/cockroach/blob/1cb6120af50d59a0db7d171cd026716b8174e59e/pkg/kv/kvserver/replica_consistency.go#L665).

**Comment by nvanbenschoten** [comment]
Extracted 5 of these commits into https://github.com/cockroachdb/cockroach/pull/117015, https://github.com/cockroachdb/cockroach/pull/117016, and https://github.com/cockroachdb/cockroach/pull/117018.

**Comment by nvanbenschoten** [comment]
Extracted another 6 of these commits into #117098, #117118, #117119, and #117120.

**Review by erikgrinaker — APPROVED** [review]
:lgtm: Nice cleanup!

> Reviewed 3 of 3 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, 9 of 9 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, 15 of 15 files at r7, 8 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116830#-:-Nni0X4m5cwivye4Swj4:b-d43tfz)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani, @miretskiy, @nvanbenschoten, and @RaduBerinde)

___
*[`pkg/sql/sem/asof/as_of.go` line 249 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/116830#-Nni-YgEDoSLadHwPxus:-Nni-YgEDoSLadHwPxut:b-l394z1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bd4ca0cce6bf2358f05ee0cb2a6cd2533ad435c/pkg/sql/sem/asof/as_of.go#L249)):*
> ```Go
> 		// Parse synthetic flag.
> 		syn := false
> 		if strings.HasSuffix(s, "?") {
> ```

This is strictly a breaking SQL change. Do we need a release note for it?
___
*[`pkg/ccl/changefeedccl/helpers_test.go` line 635 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/116830#-NnhzbLo7njWWYTJLiOi:-NnhzbLo7njWWYTJLiOj:b-6jmpxc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bd4ca0cce6bf2358f05ee0cb2a6cd2533ad435c/pkg/ccl/changefeedccl/helpers_test.go#L635)):*
> ```Go
> 	}
> 	if !options.disableSyntheticTimestamps && rand.Intn(2) == 0 {
> 		// Offset all timestamps a random (but consistent per test) amount into the
> ```

Do we want to keep this test coverage of future timestamps around? I see that the actual offsetting is commented out anyway, so it's not currently in effect, but seems like it might be useful to fix that at some point and keep the deactivated code around.

@miretskiy Do you have an opinion on this? If not, let's axe it.

**Review by nvb — COMMENTED** [review]
TFTR!

bors r=erikgrinaker

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116830#-:-NnkQwFr2fDIb26qHp5C:bl9ovuv)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani, @erikgrinaker, @miretskiy, and @RaduBerinde)

___
*[`pkg/sql/sem/asof/as_of.go` line 249 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/116830#-Nni-YgEDoSLadHwPxus:-NnkQUDOE5ww5JbJ3A-l:bombmv2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bd4ca0cce6bf2358f05ee0cb2a6cd2533ad435c/pkg/sql/sem/asof/as_of.go#L249)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

This is strictly a breaking SQL change. Do we need a release note for it?
</blockquote></details>

Good call. Done.
___
*[`pkg/ccl/changefeedccl/helpers_test.go` line 635 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/116830#-NnhzbLo7njWWYTJLiOi:-NnkQhlc27LbTXLLlwuP:bq8dqts) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bd4ca0cce6bf2358f05ee0cb2a6cd2533ad435c/pkg/ccl/changefeedccl/helpers_test.go#L635)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Do we want to keep this test coverage of future timestamps around? I see that the actual offsetting is commented out anyway, so it's not currently in effect, but seems like it might be useful to fix that at some point and keep the deactivated code around.

@miretskiy Do you have an opinion on this? If not, let's axe it.
</blockquote></details>

I'll remove for now, as this is dead code without synthetic timestamps and removing it allows us to remove a decent amount of test infrastructure. I'll reintroduce it if @miretskiy thinks it's valuable.

**Pull request merged**
