### PR TITLE
sql/catalog: TestKVWriterMatchesIEWriter fails intermittently

### LINKED ISSUE #120768: sql/catalog/lease: TestKVWriterMatchesIEWriter failed
sql/catalog/lease.TestKVWriterMatchesIEWriter [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/14475747?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/14475747?buildTab=artifacts#/) on master @ [5c26990f19a8f83c0a4848cc4245ac1823cb376a](https://github.com/cockroachdb/cockroach/commits/5c26990f19a8f83c0a4848cc4245ac1823cb376a):

```
        	            	+  Key: (roachpb.Key) (len=47) {
        	            	+   00000000  8b 12 80 00 01 91 91 12  27 32 32 35 35 2d 30 32  |........'2255-02|
        	            	+   00000010  2d 30 36 20 30 35 3a 31  38 3a 35 39 2e 36 30 32  |-06 05:18:59.602|
        	            	+   00000020  38 39 33 27 5f 73 65 73  73 69 6f 6e 00 01 88     |893'_session...|
        	            	+  },
        	            	+  Value: (roachpb.Value) {
        	            	+   RawBytes: ([]uint8) (len=7) {
        	            	+    00000000  00 00 00 00 0a 33 08                              |.....3.|
        	            	+   },
        	            	+   Timestamp: (hlc.Timestamp) {
        	            	+    WallTime: (int64) 0,
        	            	+    Logical: (int32) 0
        	            	+   }
        	            	+  }
        	            	+ },
        	            	+ (roachpb.KeyValue) {
        	            	+  Key: (roachpb.Key) (len=47) {
        	            	+   00000000  8b 12 80 00 01 91 91 12  27 32 32 35 37 2d 30 32  |........'2257-02|
        	            	+   00000010  2d 31 32 20 32 32 3a 30  31 3a 31 32 2e 36 38 37  |-12 22:01:12.687|
        	            	+   00000020  32 30 37 27 5f 73 65 73  73 69 6f 6e 00 01 88     |207'_session...|
        	            	+  },
        	            	+  Value: (roachpb.Value) {
        	            	+   RawBytes: ([]uint8) {
        	            	+   },
        	            	+   Timestamp: (hlc.Timestamp) {
        	            	+    WallTime: (int64) 0,
        	            	+    Logical: (int32) 0
        	            	+   }
        	            	+  }
        	            	+ },
        	            	+ (roachpb.KeyValue) {
        	            	+  Key: (roachpb.Key) (len=47) {
        	            	+   00000000  8b 12 80 00 01 91 91 12  27 32 32 35 37 2d 30 32  |........'2257-02|
        	            	+   00000010  2d 31 32 20 32 32 3a 30  31 3a 31 32 2e 36 38 37  |-12 22:01:12.687|
        	            	+   00000020  32 30 37 27 5f 73 65 73  73 69 6f 6e 00 01 88     |207'_session...|
        	            	+  },
        	            	+  Value: (roachpb.Value) {
        	            	+   RawBytes: ([]uint8) (len=7) {
        	            	+    00000000  00 00 00 00 0a 33 00                              |.....3.|
        	            	+   },
        	            	+   Timestamp: (hlc.Timestamp) {
        	            	+    WallTime: (int64) 0,
        	            	+    Logical: (int32) 0
        	            	+   }
        	            	+  }
        	            	+ }
        	            	+}
        	            	 
        	Test:       	TestKVWriterMatchesIEWriter/mode=SessionBasedOnly
    --- FAIL: TestKVWriterMatchesIEWriter/mode=SessionBasedOnly (10.46s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestKVWriterMatchesIEWriter.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-36864

### PR DESCRIPTION
**Pull request by fqazi**
Previously, the TestKVWriterMatchesIEWriter test would fail intermittently because the test was using the server wide internal executor. As a result if internal server operations used the internal executor we would have race condition against that. To address this, this patch will create new internal executor for the test to avoid this race condition.

Fixes: #120768

Release note: None

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
nice find!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120846#-:-NtYTJZU6GIQkkMRGZE9:b-jee1py)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/catalog/lease/kv_writer_test.go` line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120846#-NtYSyIg87rT3CFrdgPX:-NtYSyIg87rT3CFrdgPY:b-kuorlq) ([raw file](https://github.com/cockroachdb/cockroach/blob/667d6f1875c2af20e3f63d953905db8fb25c4066/pkg/sql/catalog/lease/kv_writer_test.go#L95)):*
> ```Go
> 			schema := systemschema.LeaseTableSchema
> 			if mode == SessionBasedOnly {
> 				schema = systemschema.LeaseTableSchema_V24_1
> ```

might make more sense to put the replace here, since only the 24.1 schema has the flag set:
```
schema = strings.Replace(
  systemschema.LeaseTableSchema_V24_1,
  "exclude_data_from_backup = true",
  "exclude_data_from_backup = false",
)
```

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120846)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/catalog/lease/kv_writer_test.go` line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120846#-NtYVxkV2kh06XfcNiI_:-NtYVxkV2kh06XfcNiIa:btej2u8) ([raw file](https://github.com/cockroachdb/cockroach/blob/667d6f1875c2af20e3f63d953905db8fb25c4066/pkg/sql/catalog/lease/kv_writer_test.go#L116)):*
> ```Go
> 			lease1ID := makeTable("lease1")
> 			lease2ID := makeTable("lease2")
> 			idb := s.InternalDB().(isql.DB)
> ```

super nit: `ie := s.InternalDB().(isql.DB).Executor()` would save a line

**Review by fqazi — COMMENTED** [review]
@rafiss TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120846#-:-NtYpCCA3sUiG1vtnOnJ:b-8f33ia)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/catalog/lease/kv_writer_test.go` line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120846#-NtYSyIg87rT3CFrdgPX:-NtYpDPfEIoIU9VHoL6g:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/667d6f1875c2af20e3f63d953905db8fb25c4066/pkg/sql/catalog/lease/kv_writer_test.go#L95)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

might make more sense to put the replace here, since only the 24.1 schema has the flag set:
```
schema = strings.Replace(
  systemschema.LeaseTableSchema_V24_1,
  "exclude_data_from_backup = true",
  "exclude_data_from_backup = false",
)
```
</blockquote></details>

Done.
___
*[`pkg/sql/catalog/lease/kv_writer_test.go` line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120846#-NtYVxkV2kh06XfcNiI_:-NtYpXd-DIiHZYbZNcu5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/667d6f1875c2af20e3f63d953905db8fb25c4066/pkg/sql/catalog/lease/kv_writer_test.go#L116)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

super nit: `ie := s.InternalDB().(isql.DB).Executor()` would save a line
</blockquote></details>

Done.

**Pull request merged**
