### PR TITLE
sql: remove unnecessary accesses to system.descriptors

### PR DESCRIPTION
**Pull request by knz**
(First commit from #35558.)

The following two patches aim to reduce contention on system.namespace and possibly reduce the overall rate of txn retries on newly minted clusers.

Informs #35549.
Also possibly informs #35293.

### sql: avoid a db descriptor lookup on every table name resolution

Prior to this patch, all _table_ name resolution lookups were also
fetching (and decoding) the database descriptor - incurring an extra
KV get to `system.descriptor` where only the database ID (obtained via
a lookup to `system.namespace`) is sufficient.

This patch simplifies the interface and removes the unnecessary
lookups. This is expected to reduce contention on `system.namespace`.

Before:

```
| querying next range at /Table/2/1/0/"system"/3/1 | look up db ID for system
| r6: sending batch 1 Get to (n1,s1):1             |
| querying next range at /Table/3/1/1/2/1          | look up desc for system
| r6: sending batch 1 Get to (n1,s1):1             |
| querying next range at /Table/2/1/1/"lease"/3/1  | look up table ID for lease
| r6: sending batch 1 Get to (n1,s1):1             |
| querying next range at /Table/3/1/11/2/1         | look up desc for lease
```

After:

```
| querying next range at /Table/2/1/0/"system"/3/1 | look up db ID for system
| r6: sending batch 1 Get to (n1,s1):1             |
| querying next range at /Table/2/1/1/"lease"/3/1  | look up table ID for lease
| r6: sending batch 1 Get to (n1,s1):1             |
| querying next range at /Table/3/1/11/2/1         | look up desc for lease
```

### sql,sqlbase: bypass KV to look up system descriptor IDs

Prior to this patch, both the low-level descriptor lookup functions
and the table cache were using KV operations to look up the IDs for
the system database and system tables. This is unnecessary, since the
name -> ID mapping never thanges for them.

This patch bypasses KV in these cases.

Before:

```
dist sender send  querying next range at /Table/2/1/0/"system"/3/1
dist sender send  r6: sending batch 1 Get to (n1,s1):1
dist sender send  querying next range at /Table/2/1/1/"eventlog"/3/1
dist sender send  r6: sending batch 1 Get to (n1,s1):1
dist sender send  querying next range at /Table/3/1/12/2/1
dist sender send  r6: sending batch 1 Get to (n1,s1):1
dist sender send  querying next range at /Table/3/1/1/2/1
dist sender send  r6: sending batch 1 Get to (n1,s1):1
dist sender send  querying next range at /Table/12/1
dist sender send  r8: sending batch 1 Scan to (n1,s1):1
```

After:

```
dist sender send  querying next range at /Table/3/1/12/2/1
dist sender send  r6: sending batch 1 Get to (n1,s1):1
dist sender send  querying next range at /Table/3/1/1/2/1
dist sender send  r6: sending batch 1 Get to (n1,s1):1
dist sender send  querying next range at /Table/12/1
dist sender send  r8: sending batch 1 Scan to (n1,s1):1
```

### CODE REVIEW

**Comment by knz** [comment]
The insight here is that the database descriptor was never used anyway.

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Very nice, thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35555#-:-L_UBNGe7x2pCxKFk4TH:bhwos30)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @bobvawter, @knz, and @RaduBerinde)

___
*[pkg/sql/logictest/testdata/planner_test/show_trace, line 307 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/35555#-L_UApECDtVbYxTy0_it:-L_UApECDtVbYxTy0_iu:btnt8ut) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9ebace6d1ba78d2bca68c793b7e719027c81742/pkg/sql/logictest/testdata/planner_test/show_trace#L307)):*
> ```
> subtest system_table_lookup
> 
> # We use ASOT to bypass the table cache.
> ```

[nit] AOST
___
*[pkg/sql/opt/exec/execbuilder/testdata/show_trace, line 303 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/35555#-L_UAs8O3-90xHPU1Pqd:-L_UAs8O3-90xHPU1Pqe:btnt8ut) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9ebace6d1ba78d2bca68c793b7e719027c81742/pkg/sql/opt/exec/execbuilder/testdata/show_trace#L303)):*
> ```
> subtest system_table_lookup
> 
> # We use ASOT to bypass the table cache.
> ```

[nit] AOST
___
*[pkg/sql/sqlbase/metadata.go, line 217 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/35555#-L_UAv-AEnTDzigbvEYh:-L_UAv-AEnTDzigbvEYi:bjdpt56) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9ebace6d1ba78d2bca68c793b7e719027c81742/pkg/sql/sqlbase/metadata.go#L217)):*
> ```Go
> 
> 	return cache
> }()
> ```

Interesting way to initialize!

**Comment by knz** [comment]
Thanks for your review! Made the ASOT->AOST replacement.

bors r+

**Comment by ajwerner** [comment]
Cool, I need to run some more large cluster benchmarks so I'll see what I see after this lands and update  #35293 accordingly.

**Comment by knz** [comment]
typo; will wait for TC green before merge

**Review by RaduBerinde — COMMENTED** [review]
Latest changes LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35555#-:-L_cvoPd8Sfo64x4WQqw:b-tp0rmj)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @bobvawter, and @knz)

**Comment by knz** [comment]
Thanks; I had to root a regression out (#35590) - but it's all good now. I'm now stress testing this before it merges.

**Comment by knz** [comment]
ok this seems to be stable now. let's let it fly

bors r+

**Pull request merged**
