### PR TITLE
server: default epoch range leases to on

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13653)

### CODE REVIEW

**Comment by spencerkimball** [comment]
Lgtm

**Comment by petermattis** [comment]
`TestNodeRestart` is failing consistently with:

```
--- FAIL: TestNodeRestart (12.68s)
        zchaos_test.go:279: pq: storage/replica_range_lease.go:128: couldn't request lease for {NodeID:1 StoreID:1 ReplicaID:1}: node not in the liveness table
        zchaos_test.go:150: pq: storage/replica_range_lease.go:128: couldn't request lease for {NodeID:1 StoreID:1 ReplicaID:1}: node not in the liveness table
```

**Comment by petermattis** [comment]
@spencerkimball Can you take a look at that test failure? Or provide some guidance on what the error is indicating?

**Comment by petermattis** [comment]
I took another look at this tonight and am not clear on what is going on. The test failure is very reproducible:

```
~ make acceptance TESTS=TestNodeRestart
--- FAIL: TestNodeRestart (12.38s)
        zchaos_test.go:279: pq: storage/replica_range_lease.go:128: couldn't request lease for {NodeID:1 StoreID:1 ReplicaID:1}: node not in the liveness table
        zchaos_test.go:150: pq: storage/replica_range_lease.go:128: couldn't request lease for {NodeID:1 StoreID:1 ReplicaID:1}: node not in the liveness table
```

I can see similar errors in the logs even before the restart:

```
E170219 01:49:06.121894 67 storage/store.go:1375  [n1,s1] error gossiping system config: storage/replica_range_lease.go:128: couldn't request lease for {NodeID:1 StoreID:1 ReplicaID:1}: node not in the liveness table
```

Notice that it is `n1` complaining that `n1` is not in the liveness table. And this happens when the node is first started.

**Comment by petermattis** [comment]
@spencerkimball Can you take a look at the test failure here? Or comment on what is causing those log messages?

**Comment by spencerkimball** [comment]
I will, but today is going to be tough as I have a presentation to prepare and deliver. This is on my TODO list though.

**Comment by spencerkimball** [comment]
See #13826

**Pull request closed without merging**
