### PR TITLE
roachtest: add tpccbench configurations that have caused instability

### PR DESCRIPTION
**Pull request by tbg**
See #31409.

Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31466)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/tpcc.go, line 768 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31466#-LOxJrVw2v1AckztUjr4:-LOxJrVw2v1AckztUjr5:bq9jri1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebb9b9b71eda1b669698e53bfa30777010fa3e2d/pkg/cmd/roachtest/tpcc.go#L768)):*
> ```Go
> 			EstimatedMax:   12000,
> 			LoadConfig:     singlePartitionedLoadgen,
> 		},
> ```

These additional configurations might cause us to run over quota. Not sure what to do about that. @andreimatei's work to add CPU-level quota scheduling would help.

**Comment by tschottdorf** [comment]
Are these run during nightlies? I really just want them in there so that we can take a look at them. If they run during nightlies, do they have a realistic failure criterion? Would be surprising given the problems we've seen in these.

**Review by petermattis — APPROVED** [review]
Oh, good point. I don't think these are run during nightlies. Carry on.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31466#-:-LOxQJw2BeED_eRvvqrI:b7nrkuo)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by nvb — APPROVED** [review]
No, these aren't run nightly.

**Comment by petermattis** [comment]
@tschottdorf Do you want to merge this?

**Pull request merged**
