### PR TITLE
concurrency: hoist TxnMeta from {,un}replicatedLockInfo into the holder 

### PR DESCRIPTION
**Pull request by arulajmani**
Previously, we were storing the TxnMeta separately for both
{,un}replicatedLockInfo. The lock table is quite dumb when it comes to
replicated locks -- for good reason. As a result, tracking TxnMeta's
for replicated locks isn't of much use, as we don't make use of it,
and this patch does exactly that. This also allows us to hoist the
TxnMeta object one level higher, into the holder struct.

Epic: none

Release note: None

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
This is all rebased now, should be ready for a look! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105474#-:-NZ1uvq_1rJ0F4gR15QG:bqr1zv7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2345 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/105474#-NZ1u2xS811aL7CfZ3DK:-NZ1u2xS811aL7CfZ3DL:b-5074s9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d556b025b0953a10a1b0081cd9e7e4b7c0b34199/pkg/kv/kvserver/concurrency/lock_table.go#L2345)):*
> ```Go
> 			l.holder.txn = &acq.Txn
> 		case l.holder.txn.Epoch < acq.Txn.Epoch: // lock is being acquired at a newer epoch
> 			// The txn meta tracked here corresponds to unreplicated locks. When the
> ```

@nvanbenschoten just wanted to call out that this behavior is different from what we spoke about on call yesterday. I've tried to capture why the initial approach I was suggesting doesn't work in this comment.

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 7 of 7 files at r2, 1 of 1 files at r3, 43 of 43 files at r4, 1 of 1 files at r5, 1 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105474)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2906 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105474#-NZD5xRpCwwE7ETqBtfs:-NZD5xRq8T2nCvcSCZGg:b-tr36js) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b30f4a8c776076e79abdfd25e25fdb5cea87456/pkg/kv/kvserver/concurrency/lock_table.go#L2906)):*
> ```Go
> 
> 	// Bail if not locked with only the Unreplicated durability.
> 	if !l.holder.locked || !l.holder.replicatedInfo.isEmpty() {
> ```

Does it make sense for this to be `if !l.holder.locked || l.isHeldReplicated() {`?

Also, does it make sense to add an `(l *lockState) isHeld() bool` method?

EDIT: the 5th commit read my mind :)
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 3019 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105474#-NZD69Jg8JRU0Rf87GoH:-NZD69Jg8JRU0Rf87GoI:b-x2kttu) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b30f4a8c776076e79abdfd25e25fdb5cea87456/pkg/kv/kvserver/concurrency/lock_table.go#L3019)):*
> ```Go
> }
> 
> // isHeldReplicated returns true if the receiver is held as a replicated lock.
> ```

Let's keep these methods near the rest of the `lockState` accessor methods, maybe right below `assertEmptyLockUnlocked`. Without this kind of grouping, the structure in a large, multi-type file like this can deteriorate.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 3019 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105474#-NZD6UeS3qDisdnjEI5g:-NZD6UeS3qDisdnjEI5h:b-6y9et) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b30f4a8c776076e79abdfd25e25fdb5cea87456/pkg/kv/kvserver/concurrency/lock_table.go#L3019)):*
> ```Go
> }
> 
> // isHeldReplicated returns true if the receiver is held as a replicated lock.
> ```

`// REQUIRES: l.mu is locked.`

And below.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1683 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/105474#-NZD80G20Bn2equXSh6Z:-NZD80G20Bn2equXSh6_:b-ad1z83) ([raw file](https://github.com/cockroachdb/cockroach/blob/42c027c5b4e1009e74f313c382c548347ee2ccdd/pkg/kv/kvserver/concurrency/lock_table.go#L1683)):*
> ```Go
> 	// the unreplicated lock.
> 	if l.isHeldReplicated() && l.isHeldUnreplicated() {
> 		if l.holder.unreplicatedInfo.ts.Less(l.holder.replicatedInfo.ts) {
> ```

nit: I think you could make this logic look even more intentional by structuring it like:
```go
txnMeta := l.holder.unreplicatedInfo.txn
minTs := l.holder.unreplicatedInfo.ts
minTs.Backward(l.holder.replicatedInfo.ts)
return txnMeta, minTs
```
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1003 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/105474#-NZDB1EdDYgYS7-T53ku:-NZDB1EdDYgYS7-T53kv:b5s0gje) ([raw file](https://github.com/cockroachdb/cockroach/blob/d556b025b0953a10a1b0081cd9e7e4b7c0b34199/pkg/kv/kvserver/concurrency/lock_table.go#L1003)):*
> ```Go
> 		//
> 		// 1. The epoch of the TxnMeta stored here must be monotonically increasing.
> 		// 2. The tracking in unreplicatedLockInfo corresponds to the epoch of the
> ```

"The tracking of sequence numbers"?

If so, could you spell out what effect this has.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1007 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/105474#-NZDBB3O7WEtd0Me2HbB:-NZDBB3O7WEtd0Me2HbC:b-w8zusb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d556b025b0953a10a1b0081cd9e7e4b7c0b34199/pkg/kv/kvserver/concurrency/lock_table.go#L1007)):*
> ```Go
> 		//
> 		// As a result, the TxnMeta stored here may not correspond to the latest
> 		// call to acquire/update the lock.
> ```

Is this only referring to cases where an acquire/update call had an earlier epoch?
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1304 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/105474#-NZDBQ0RCRGiRa_-Jgx4:-NZDBQ0RCRGiRa_-Jgx5:b-9yvy00) ([raw file](https://github.com/cockroachdb/cockroach/blob/d556b025b0953a10a1b0081cd9e7e4b7c0b34199/pkg/kv/kvserver/concurrency/lock_table.go#L1304)):*
> ```Go
> 	if l.isHeld() {
> 		txnHolder = l.holder.txn
> 		switch {
> ```

Is the purpose of this switch statement now just to set `durability = lock.Replicated` if `isHeldReplicated()`?
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2345 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/105474#-NZDBvrKBHH1EQVW7FNW:-NZDBvrKBHH1EQVW7FNX:b7epwsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d556b025b0953a10a1b0081cd9e7e4b7c0b34199/pkg/kv/kvserver/concurrency/lock_table.go#L2345)):*
> ```Go
> 			l.holder.txn = &acq.Txn
> 		case l.holder.txn.Epoch < acq.Txn.Epoch: // lock is being acquired at a newer epoch
> 			// The txn meta tracked here corresponds to unreplicated locks. When the
> ```

"when the we"
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2345 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/105474#-NZ1u2xS811aL7CfZ3DK:-NZDCv1S8ZX3gSC4kZoS:bswxbin) ([raw file](https://github.com/cockroachdb/cockroach/blob/d556b025b0953a10a1b0081cd9e7e4b7c0b34199/pkg/kv/kvserver/concurrency/lock_table.go#L2345)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

@nvanbenschoten just wanted to call out that this behavior is different from what we spoke about on call yesterday. I've tried to capture why the initial approach I was suggesting doesn't work in this comment. 
</blockquote></details>

I don't think I understand this. Why does option 1 create a situation that is different than (using the language of the referenced comment) "the first time a lock is added to the lockTable"? Unreplicated locks can be dropped and then re-acquired by a transaction with a lower timestamp, can't they?

**Review by arulajmani — COMMENTED** [review]
Sorry for letting this sit for a while. RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105474#-:-N_dkXZ62tNDfAQWi2oF:b-50zn6q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 3019 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105474#-NZD69Jg8JRU0Rf87GoH:-N__jugq-7Bk1aJe6ksZ:b-9k0cc2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b30f4a8c776076e79abdfd25e25fdb5cea87456/pkg/kv/kvserver/concurrency/lock_table.go#L3019)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's keep these methods near the rest of the `lockState` accessor methods, maybe right below `assertEmptyLockUnlocked`. Without this kind of grouping, the structure in a large, multi-type file like this can deteriorate.
</blockquote></details>

Moved, thanks for the nudge.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1683 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/105474#-NZD80G20Bn2equXSh6Z:-N_dLs3H3GEgJkUS3-zq:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/42c027c5b4e1009e74f313c382c548347ee2ccdd/pkg/kv/kvserver/concurrency/lock_table.go#L1683)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: I think you could make this logic look even more intentional by structuring it like:
```go
txnMeta := l.holder.unreplicatedInfo.txn
minTs := l.holder.unreplicatedInfo.ts
minTs.Backward(l.holder.replicatedInfo.ts)
return txnMeta, minTs
```
</blockquote></details>

Done. 
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1007 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/105474#-NZDBB3O7WEtd0Me2HbB:-N_dg5rQEbZQeElf_wih:b-ceb5qx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d556b025b0953a10a1b0081cd9e7e4b7c0b34199/pkg/kv/kvserver/concurrency/lock_table.go#L1007)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this only referring to cases where an acquire/update call had an earlier epoch?
</blockquote></details>

Yeah, clarified the comment. 
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1304 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/105474#-NZDBQ0RCRGiRa_-Jgx4:-N_dev2CDDBz4YLYGR-N:byzzsdg) ([raw file](https://github.com/cockroachdb/cockroach/blob/d556b025b0953a10a1b0081cd9e7e4b7c0b34199/pkg/kv/kvserver/concurrency/lock_table.go#L1304)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is the purpose of this switch statement now just to set `durability = lock.Replicated` if `isHeldReplicated()`?
</blockquote></details>

Hahah fixed :sweat_smile: 
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2345 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/105474#-NZ1u2xS811aL7CfZ3DK:-N_dOw3DBgZdsprYcA0j:b-c1zx1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/d556b025b0953a10a1b0081cd9e7e4b7c0b34199/pkg/kv/kvserver/concurrency/lock_table.go#L2345)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I don't think I understand this. Why does option 1 create a situation that is different than (using the language of the referenced comment) "the first time a lock is added to the lockTable"? Unreplicated locks can be dropped and then re-acquired by a transaction with a lower timestamp, can't they?
</blockquote></details>

I was referring to this bit from the comment: 

```
// A lock's timestamp at a given durability level is not allowed to  
// regress, so by forwarding its timestamp during the second acquisition  
// instead if assigning to it blindly, it remains at 20.
```

Now that I think of this a bit more, I wonder if this invariant ("a lock's timestamp at a given durability level is not allowed to regress") should only apply to intents. After all, that's the only lock strength where timestamps are meaningful[*].

[*] Assuming exclusive locks do not block non-locking reads. 

----

I think this makes both these options viable, and I can make arguments for both. On one hand, option 2 preserves unreplicated locks across epochs (which is in the spirit of epochs). 

However, we don't preserve unreplicated locks across epochs in `tryUpdateLock`, so option 1 keeps things symmetrical. 

Do you have a preference either way?

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105474)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2345 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/105474#-NZ1u2xS811aL7CfZ3DK:-N_f9P5o-jsumTBC7vph:b-4bwmb0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3c6db4086cfbe0f50e814c2f8ea94623cd5c3f7/pkg/kv/kvserver/concurrency/lock_table.go#L2345)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I was referring to this bit from the comment: 

```
// A lock's timestamp at a given durability level is not allowed to  
// regress, so by forwarding its timestamp during the second acquisition  
// instead if assigning to it blindly, it remains at 20.
```

Now that I think of this a bit more, I wonder if this invariant ("a lock's timestamp at a given durability level is not allowed to regress") should only apply to intents. After all, that's the only lock strength where timestamps are meaningful[*].

[*] Assuming exclusive locks do not block non-locking reads. 

----

I think this makes both these options viable, and I can make arguments for both. On one hand, option 2 preserves unreplicated locks across epochs (which is in the spirit of epochs). 

However, we don't preserve unreplicated locks across epochs in `tryUpdateLock`, so option 1 keeps things symmetrical. 

Do you have a preference either way? 

</blockquote></details>

Switched over to clearing out `unreplicatedLockHolderInfo`, like we spoke about earlier today.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 39 of 43 files at r10, 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105474#-:-N_lvgx7BTXTPJaighDD:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2368 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/105474#-N_lujle2SYly_PolW7e:-N_lujle2SYly_PolW7f:b-5081rv) ([raw file](https://github.com/cockroachdb/cockroach/blob/661e46a2dff9be89cdf8ed3d94272ee6ef61eec5/pkg/kv/kvserver/concurrency/lock_table.go#L2368)):*
> ```Go
> 			// learn about a newer epoch during lock acquisition of a replicated lock,
> 			// we clear out the unreplicatedLockInfo state being tracked from the
> 			// older epoch.
> ```

Do you want to mention why we don't clear out the replicatedInfo in the unreplicated acquisition case?

**Review by arulajmani — COMMENTED** [review]
TFTR! 

bors r=nvanbenschoten

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105474#-:-N_nxRlW5sHjSWd8cIR7:b-ieq29z)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2368 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/105474#-N_lujle2SYly_PolW7e:-N_nxMl16jysZ0dInM-m:bo29s34) ([raw file](https://github.com/cockroachdb/cockroach/blob/661e46a2dff9be89cdf8ed3d94272ee6ef61eec5/pkg/kv/kvserver/concurrency/lock_table.go#L2368)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you want to mention why we don't clear out the replicatedInfo in the unreplicated acquisition case?
</blockquote></details>

Good call; added some words.

**Pull request merged**
