### PR TITLE
sql/parser: fix verification of '+' and '-' signs in interval parts

### LINKED ISSUE #17308: sql: SELECT INTERVAL '+' produces CLI panic
Found with an experiment I'm doing with [go fuzz](https://github.com/dvyukov/go-fuzz).

```
root@:26257/> select interval '+';
E170730 00:08:07.727755 1 util/log/crash_reporting.go:82  a panic has occurred!
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 1 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.RecoverAndReportPanic(0x9562858, 0xc4200783f0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:59 +0x95
panic(0x5486ae0, 0x656b650)
	/usr/local/Cellar/go/1.8/libexec/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql/parser.sqlStdToDuration(0xc4201bad80, 0x1, 0x5731e58, 0xffffffffffffffff, 0x60e0840, 0xc42074c0c0, 0xc420696e60)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/interval.go:205 +0x1136
github.com/cockroachdb/cockroach/pkg/sql/parser.parseDInterval(0xc4201bad80, 0x1, 0x6, 0xc420696f10, 0xc420696f08, 0xc420204000)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/datum.go:1596 +0x1ef
github.com/cockroachdb/cockroach/pkg/sql/parser.ParseDInterval(0xc4201bad80, 0x1, 0xc42021e5e0, 0x3b, 0x161)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/datum.go:1513 +0x3e
github.com/cockroachdb/cockroach/pkg/sql/parser.(*sqlParserImpl).Parse(0xc42021e5e0, 0x60e5300, 0xc42021e500, 0x0)
	sql.y:5262 +0x53af9
github.com/cockroachdb/cockroach/pkg/sql/parser.(*Parser).Parse(0xc42021e500, 0xc42024e1e0, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/parse.go:62 +0x6d
github.com/cockroachdb/cockroach/pkg/sql/parser.Parse(0xc42024e1e0, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/parse.go:127 +0x4f
github.com/cockroachdb/cockroach/pkg/cli.(*cliState).doCheckStatement(0xc42063a900, 0x2, 0x4, 0xb, 0xb)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/cli/sql.go:774 +0x56
github.com/cockroachdb/cockroach/pkg/cli.runInteractive(0xc4205b0800, 0xc4204a1f00, 0x0, 0x0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/cli/sql.go:941 +0x70a
github.com/cockroachdb/cockroach/pkg/cli.runTerm(0x6584320, 0xc4201f2440, 0x0, 0x1, 0x0, 0x0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/cli/sql.go:996 +0x162
github.com/cockroachdb/cockroach/pkg/cli.MaybeDecorateGRPCError.func1(0x6584320, 0xc4201f2440, 0x0, 0x1, 0x0, 0x0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/cli/error.go:35 +0x5a
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).execute(0x6584320, 0xc4201f2400, 0x1, 0x1, 0x6584320, 0xc4201f2400)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:644 +0x3f8
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x65808a0, 0x402cf0e, 0xc42007e3b0, 0xc42069bf10)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:734 +0x339
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).Execute(0x65808a0, 0xc42069bf00, 0xc42007e380)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:693 +0x2b
github.com/cockroachdb/cockroach/pkg/cli.Run(0xc42007c0a0, 0x2, 0x2, 0xc4200783f0, 0xc4200783f0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:136 +0x6d
github.com/cockroachdb/cockroach/pkg/cli.Main()
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:51 +0x17f
main.main()
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/main.go:28 +0x20
```

### PR DESCRIPTION
**Pull request by isitinschi**
interval.sqlStdToDuration didn't check that interval part can be '+' or start with '++', '--', "+++", "---" etc

fixes #17308

### CODE REVIEW

**Comment by isitinschi** [comment]
CLA is signed but the status is not updated here. I don't know why

**Comment by knz** [comment]
Thank you for your contribution!
As a tiny cosmetic fix, please prefix the commit message with `sql/parser: `
Then I have a small request about the test, see comment below.
Otherwise, well done.

---

Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/parser/interval_test.go, line 81 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17344#-KqSWP0h4-KdqnU5zaLP:-KqSWP0i2lRqt3gBH0z_:b-opzoui) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cc875ae1a78db3b854002e86e63c56d2fd9cd9c/pkg/sql/parser/interval_test.go#L81)):*
> ```Go
> 		{`1- 3:`, `1y3h`, ``},
> 		{`1- 3:4`, `1y3h4m`, ``},
> 		{`+`, ``, `invalid input syntax for type interval +`},
> ```

Can you instead please split this test in two, one that checks valid intervals and another, separate test that checks for invalid intervals.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17344#-:-KqSWXDFFxMRqYqghK2I:b-a3v9bv)*

**Comment by knz** [comment]
For the CLA error I think you need to add the email address you committed with to your github user account.

**Comment by knz** [comment]
Please squash the two commits together before we can merge this.

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[pkg/sql/parser/interval_test.go, line 81 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17344#-KqSWP0h4-KdqnU5zaLP:-KqT6BMzqC75Yf9h40K_:b-9755fn) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cc875ae1a78db3b854002e86e63c56d2fd9cd9c/pkg/sql/parser/interval_test.go#L81)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can you instead please split this test in two, one that checks valid intervals and another, separate test that checks for invalid intervals.
</blockquote></details>

Thank you!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17344#-:-KqT6HDVK4NEzCVhfxAR:bde89o8)*

**Comment by isitinschi** [comment]
Thank you for your review!

**Comment by knz** [comment]
Thank you for your contribution :)

**Pull request merged**
