### PR TITLE
opt: Add optgen code generation tool.

### PR DESCRIPTION
**Pull request by andy-kimball**
This PR adds the optgen code generator command-line tool. It uses
the Optgen language to generate a compiled expression, and then can
generate expressions, ops, and a factory from that. This PR does
not generate pattern matching or replacement code - a future PR will
add that support.

This PR also contains additional functionality in the datadriven
package to support output with blank lines. This is used to test
code generation.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
If you run the `sql/opt` test with `--rewrite`, you will see diffs, and they don't look right. It seems that we're losing every testcase after a test with a blank result.

---

Review status: 0 of 26 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/optgen/lang/testdata/scanner, line 16 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L3uYUQwAQhl3uo25de_:-L3uYUQwAQhl3uo25dea:bpyucja) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d4389ebcfe9deaab8979c7ada6881e884209e4/pkg/sql/opt/optgen/lang/testdata/scanner#L16)):*
> ```
> (COMMENT # comment ()[])
> ```

Do we really want these extra blank lines?

---

*[pkg/sql/opt/testutils/datadriven/datadriven.go, line 44 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L3uXaZ-XOmDxfIwRo4v:-L3uXaZ0zSEUQceKcjir:b2ptfpk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d4389ebcfe9deaab8979c7ada6881e884209e4/pkg/sql/opt/testutils/datadriven/datadriven.go#L44)):*
> ```Go
> //   ----
> //   <expected results>
> //
> ```

Can you update this comment to explain the new syntax? Also add that we support statements with no results (no ----), e.g. `exec-raw`.

---

*[pkg/sql/opt/testutils/datadriven/datadriven.go, line 59 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L3uZEJScXqrBC4v13yp:-L3uZEJScXqrBC4v13yq:b-z4gr2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d4389ebcfe9deaab8979c7ada6881e884209e4/pkg/sql/opt/testutils/datadriven/datadriven.go#L59)):*
> ```Go
> 			// Ensure actual result always ends with a newline, since expected
> 			// always will.
> 			actual += "\n"
> ```

Note that `emit()` also adds a newline.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-:-L3uZxyiGTHbgTcZWvsY:b6zkam)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 26 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/optgen/cmd/optgen/exprs_gen.go, line 58 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L3u_asQWes860BvTefX:-L3u_asQWes860BvTefY:bx1l6bb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d4389ebcfe9deaab8979c7ada6881e884209e4/pkg/sql/opt/optgen/cmd/optgen/exprs_gen.go#L58)):*
> ```Go
> 	fmt.Fprintf(g.w, "type childCountLookupFunc func(ev *ExprView) int\n")
> 
> 	fmt.Fprintf(g.w, "var childCountLookup = []childCountLookupFunc{\n")
> ```

This could be `[...]` so it's a static array; there might be a perf benefit to doing that, but I'm not sure.

---

*[pkg/sql/opt/optgen/cmd/optgen/testdata/exprs, line 10 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L3uaqwzCGn31y4cCi7c:-L3uaqwzCGn31y4cCi7d:bbzmwaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d4389ebcfe9deaab8979c7ada6881e884209e4/pkg/sql/opt/optgen/cmd/optgen/testdata/exprs#L10)):*
> ```
> ----
> ----
> // Code generated by optgen; DO NOT EDIT.
> ```

These tests are really cool. Very good documentation for what code we generate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 26 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/optgen/cmd/optgen/testdata/factory, line 14 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L3yHjdDmhZ-8oT78uiL:-L3yHjdDmhZ-8oT78uiM:bb5v7gj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d4389ebcfe9deaab8979c7ada6881e884209e4/pkg/sql/opt/optgen/cmd/optgen/testdata/factory#L14)):*
> ```
> ----
> ----
> // Code generated by optgen; DO NOT EDIT.
> ```

Reviewable is not showing the diffs for these tests by default because of these markers. I wonder if you should add a `-nomarker` flag.

---

*[pkg/sql/opt/xform/ops/enforcer.opt, line 7 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L3yIIO_5F32dt3Rijuw:-L3yIIO_5F32dt3Rijux:bn9k80h) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d4389ebcfe9deaab8979c7ada6881e884209e4/pkg/sql/opt/xform/ops/enforcer.opt#L7)):*
> ```
> 
> [Relational, Enforcer]
> define Arrange {
> ```

Probably worthwhile to start adding commentary about these operators. I can infer what `Sort` is, but `Arrange` is not as obvious.

---

*[pkg/sql/opt/xform/ops/scalar.opt, line 320 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L3yImH_qudwPp94uRIU:-L3yImH_qudwPp94uRIV:bqzeo7l) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d4389ebcfe9deaab8979c7ada6881e884209e4/pkg/sql/opt/xform/ops/scalar.opt#L320)):*
> ```
> 
> [Scalar]
> define True {
> ```

I'm curious why you're modeling `True` and `False` as different expression types instead of global `Const` expressions. Do you need to model `Null` this way too? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-:-L3yJ0xU5NJcAgH87tea:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 26 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/xform/ops/scalar.opt, line 320 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L3yImH_qudwPp94uRIU:-L3yekHlBiMqjhDfeQU9:b-b26jc9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d4389ebcfe9deaab8979c7ada6881e884209e4/pkg/sql/opt/xform/ops/scalar.opt#L320)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm curious why you're modeling `True` and `False` as different expression types instead of global `Const` expressions. Do you need to model `Null` this way too? 
</blockquote></details>

My guess: to enable things like `(True)` in transformation rules. A comment explaining the reasoning would help though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847)*

**Comment by andy-kimball** [comment]
I added comments and cleaned up a few things in response to the comments.

---

Review status: 0 of 31 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/sql/opt/optgen/cmd/optgen/exprs_gen.go, line 58 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L3u_asQWes860BvTefX:-L41KpzUpSllK0IJJELu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d4389ebcfe9deaab8979c7ada6881e884209e4/pkg/sql/opt/optgen/cmd/optgen/exprs_gen.go#L58)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This could be `[...]` so it's a static array; there might be a perf benefit to doing that, but I'm not sure.
</blockquote></details>

Done.

---

*[pkg/sql/opt/optgen/cmd/optgen/testdata/factory, line 14 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L3yHjdDmhZ-8oT78uiL:-L41M0klmzRoyoTh5gpu:bu5q387) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d4389ebcfe9deaab8979c7ada6881e884209e4/pkg/sql/opt/optgen/cmd/optgen/testdata/factory#L14)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Reviewable is not showing the diffs for these tests by default because of these markers. I wonder if you should add a `-nomarker` flag.
</blockquote></details>

I changed the test to replace `DO NOT EDIT` with:
```
//  Code generated by optgen; [omitted]
```

---

*[pkg/sql/opt/optgen/lang/testdata/scanner, line 16 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L3uYUQwAQhl3uo25de_:-L41MLC8EmyvC_tylpAW:b-rb0sye) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d4389ebcfe9deaab8979c7ada6881e884209e4/pkg/sql/opt/optgen/lang/testdata/scanner#L16)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Do we really want these extra blank lines?
</blockquote></details>

I liked them just because they help my eye pick out the next test case. But maybe I'll just expand the comments more, like this:
```
(IDENT foo)
(COMMENT # comment ()[])

#
# Symbols
#
scan
()[]{}$:*==>&,^|.. ...
----
```
Also, I made another change to allow blank lines within the command "input" section of the datadriven test format. Now, the code will only break once it finds "----". This makes my tests that use blank lines look neater. Do you see any issues with making that change?

---

*[pkg/sql/opt/testutils/datadriven/datadriven.go, line 44 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L3uXaZ-XOmDxfIwRo4v:-L41SyJrKiKBLjVELlET:b-72nno) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d4389ebcfe9deaab8979c7ada6881e884209e4/pkg/sql/opt/testutils/datadriven/datadriven.go#L44)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Can you update this comment to explain the new syntax? Also add that we support statements with no results (no ----), e.g. `exec-raw`.
</blockquote></details>

I added a comment about the new syntax. However, I think that we should always require a '----', even for statements with no results. This would allow blank lines to be used in the command input, which right now I work around using dummy comment lines.
```
exec-raw
CREATE DATABASE t
----

optgen compile test.opt
define {}

[Name]
(Foo) => ()

[Name]
(Foo) =>
----
```
What do you think about requiring a '----' separator?

---

*[pkg/sql/opt/testutils/datadriven/datadriven.go, line 59 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L3uZEJScXqrBC4v13yp:-L41TueSEc8xCLBoRC4o:b-2og4hu) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d4389ebcfe9deaab8979c7ada6881e884209e4/pkg/sql/opt/testutils/datadriven/datadriven.go#L59)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Note that `emit()` also adds a newline.
</blockquote></details>

I cleaned up the newline handling and got rid of the code that adds a newline character if one didn't exist. However, I can't use `emit()` in the case of the new syntax that allows blank lines, because emit adds an extra blank line before the closing '----' separator, which causes a feedback loop each time --rewrite is used (blank line added each time).

---

*[pkg/sql/opt/xform/ops/enforcer.opt, line 7 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L3yIIO_5F32dt3Rijuw:-L41f7v7reFXS0AfRenz:btwm0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d4389ebcfe9deaab8979c7ada6881e884209e4/pkg/sql/opt/xform/ops/enforcer.opt#L7)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Probably worthwhile to start adding commentary about these operators. I can infer what `Sort` is, but `Arrange` is not as obvious.
</blockquote></details>

Good idea. I decided to rename it to `Present`, and added the following comment:
```
# Present enforces physical properties related to column presentation, which
# includes column ordering, column naming, and duplicate columns. While the
# input expression must project the columns used by Present, it can project
# a superset of columns in any order and using any names. Whereas the Project
# operator modifies logical properties (i.e. the set of columns returned), the
# Present operator enforces physical properties (i.e. the presentation of the
# set of columns returned). See the Presentation field in the PhysicalProps
# struct.
# TODO(andyk): Add the Presentation field.
```

I also added comments for several other operators that use private fields, as a downpayment on further documentation down the line.

---

*[pkg/sql/opt/xform/ops/scalar.opt, line 320 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L3yImH_qudwPp94uRIU:-L41moUrCbg2xk64U2MO:b-ghetp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d4389ebcfe9deaab8979c7ada6881e884209e4/pkg/sql/opt/xform/ops/scalar.opt#L320)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

My guess: to enable things like `(True)` in transformation rules. A comment explaining the reasoning would help though.
</blockquote></details>

Radu is correct. It's really convenient (and more efficient) to make True/False separate operators. I suspect Null will be useful as well, but we can wait until we verify this before adding it. I've added comments to the operators to explain this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-:-L423PJ5V3FbaKlIJPdQ:b-eqkqk6)*

**Comment by andy-kimball** [comment]
Also, @radu, I'd like to allow blank lines in the command input section of a data-driven test. Do you have concerns if we require the "----" for cases similar to `exec-raw`, so that we can accept blank lines?

---

Review status: 0 of 31 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-:-L423r8GEsSS0TXzWCpN:b-rqoftw)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 14 of 26 files at r1, 19 of 19 files at r2.
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[Makefile, line 359 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L41p4Yt_5BLOWyYDH-F:-L41p4Yt_5BLOWyYDH-G:b-f346an) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d4389ebcfe9deaab8979c7ada6881e884209e4/Makefile#L359)):*
> ```Makefile
> 		./vendor/golang.org/x/tools/cmd/goyacc \
> 		./vendor/golang.org/x/tools/cmd/stringer \
> 		./pkg/sql/opt/optgen/cmd/langgen
> ```

Does this need a backslash at the end of the line?

---

*[pkg/sql/opt/optgen/cmd/optgen/exprs_gen.go, line 133 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L41wWxx4GbbSJcTujBC:-L41wWxx4GbbSJcTujBD:bi3vdl5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d4389ebcfe9deaab8979c7ada6881e884209e4/pkg/sql/opt/optgen/cmd/optgen/exprs_gen.go#L133)):*
> ```Go
> 		fmt.Fprintf(g.w, "    %s := (*%s)(ev.mem.lookupExpr(ev.loc))\n\n", varName, exprType)
> 
> 		fmt.Fprintf(g.w, "  switch n {\n")
> ```

[nit] I think this whole switch statement should be indented by one level

---

*[pkg/sql/opt/optgen/cmd/optgen/main.go, line 75 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L42-3h4Z_4KGi1oDrPs:-L42-3h4Z_4KGi1oDrPt:b-ixru7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d4389ebcfe9deaab8979c7ada6881e884209e4/pkg/sql/opt/optgen/cmd/optgen/main.go#L75)):*
> ```Go
> 	err := g.cmdLine.Parse(args)
> 	if err != nil {
> 		return false
> ```

Should you report an error here with `g.reportError(...)`?

---

*[pkg/sql/opt/optgen/cmd/optgen/main.go, line 227 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L424QDt0IWUSnqOGgky:-L422uTN87WAXyoKTDDE:b-q3ap6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d4389ebcfe9deaab8979c7ada6881e884209e4/pkg/sql/opt/optgen/cmd/optgen/main.go#L227)):*
> ```Go
> }
> 
> func unTitle(name string) string {
> ```

[nit] `main.go` doesn't seem like the best place for all of these utility functions. Maybe it's worth adding a utils file?

---

*[pkg/sql/opt/xform/ops/relational.opt, line 1 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L42ArMN8jEyfHXSjeIi:-L42ArMOhtXJmsMfY6qe:b-yzywj) ([raw file](https://github.com/cockroachdb/cockroach/blob/89d51327765e4ba4508057fd9f95486c40443ca5/pkg/sql/opt/xform/ops/relational.opt#L1)):*
> ```
> # Scan returns a resultset containing every row in the specifieid table. Rows
> ```

specifieid -> specified

---

*[pkg/sql/opt/xform/ops/relational.opt, line 74 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L42BJDEe7lXDcLkVq1n:-L42BJDEe7lXDcLkVq1o:bux1kes) ([raw file](https://github.com/cockroachdb/cockroach/blob/89d51327765e4ba4508057fd9f95486c40443ca5/pkg/sql/opt/xform/ops/relational.opt#L74)):*
> ```
> }
> 
> [Relational, Join, JoinApply]
> ```

Can you add a quick comment to explain the difference between Join and JoinApply?

---

*[pkg/sql/opt/xform/ops/scalar.opt, line 329 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L42CMwDkNou7dnpM09K:-L42CMwDkNou7dnpM09L:bkubvxw) ([raw file](https://github.com/cockroachdb/cockroach/blob/89d51327765e4ba4508057fd9f95486c40443ca5/pkg/sql/opt/xform/ops/scalar.opt#L329)):*
> ```
> [Scalar]
> define False {
> }
> ```

No need to add them to this PR, but we are going to need JSON operators like contains, etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-:-L42CbkQI2jLSajFKFS7:bnfp4nl)*

**Comment by andy-kimball** [comment]
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[Makefile, line 359 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L41p4Yt_5BLOWyYDH-F:-L42E_J3mVoUpMMPMeNb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d4389ebcfe9deaab8979c7ada6881e884209e4/Makefile#L359)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Does this need a backslash at the end of the line?
</blockquote></details>

Done.

---

*[pkg/sql/opt/optgen/cmd/optgen/exprs_gen.go, line 133 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L41wWxx4GbbSJcTujBC:-L42Edw8i_7KQebyMjDK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d4389ebcfe9deaab8979c7ada6881e884209e4/pkg/sql/opt/optgen/cmd/optgen/exprs_gen.go#L133)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] I think this whole switch statement should be indented by one level
</blockquote></details>

Done.

---

*[pkg/sql/opt/optgen/cmd/optgen/main.go, line 75 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L42-3h4Z_4KGi1oDrPs:-L42FStnUfn1mcLny8fi:b-ffkf2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d4389ebcfe9deaab8979c7ada6881e884209e4/pkg/sql/opt/optgen/cmd/optgen/main.go#L75)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Should you report an error here with `g.reportError(...)`?
</blockquote></details>

The golang CommandLine.Parse method already reports the error and calls usage. I'm not sure why it does that, because then the behavior can't be easily overridden, but it is what it is...

---

*[pkg/sql/opt/optgen/cmd/optgen/main.go, line 227 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L424QDt0IWUSnqOGgky:-L42GKQNiVSMP0y2y-99:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d4389ebcfe9deaab8979c7ada6881e884209e4/pkg/sql/opt/optgen/cmd/optgen/main.go#L227)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] `main.go` doesn't seem like the best place for all of these utility functions. Maybe it's worth adding a utils file?
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/ops/relational.opt, line 1 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L42ArMN8jEyfHXSjeIi:-L42GSJ3zjvaqTyr0Ct1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/89d51327765e4ba4508057fd9f95486c40443ca5/pkg/sql/opt/xform/ops/relational.opt#L1)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

specifieid -> specified
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/ops/relational.opt, line 74 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L42BJDEe7lXDcLkVq1n:-L42N0XcBRPu_rCYpVwz:b-qggq94) ([raw file](https://github.com/cockroachdb/cockroach/blob/89d51327765e4ba4508057fd9f95486c40443ca5/pkg/sql/opt/xform/ops/relational.opt#L74)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Can you add a quick comment to explain the difference between Join and JoinApply?
</blockquote></details>

I added comments at the top of each .opt file that include a section that describes tags it uses.

---

*[pkg/sql/opt/xform/ops/scalar.opt, line 329 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L42CMwDkNou7dnpM09K:-L42N8jonovIm9fCWSTs:bbuvxht) ([raw file](https://github.com/cockroachdb/cockroach/blob/89d51327765e4ba4508057fd9f95486c40443ca5/pkg/sql/opt/xform/ops/scalar.opt#L329)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

No need to add them to this PR, but we are going to need JSON operators like contains, etc.
</blockquote></details>

Right. We'll also eventually need a bunch of physical operators like HashJoin, MergeJoin, etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847)*

**Comment by petermattis** [comment]
Review status: 25 of 32 files reviewed at latest revision, 14 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/xform/ops/enforcer.opt, line 2 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L42P2ekYNcEENXhlHzN:-L42P2ekYNcEENXhlHzO:bmwlr8e) ([raw file](https://github.com/cockroachdb/cockroach/blob/e167b317f5f6a65aa05b206ae1c53a75255c47f8/pkg/sql/opt/xform/ops/enforcer.opt#L2)):*
> ```
> # enforcer.opt contains Optgen language definitions for "enforcer" operators
> # that ensure resultsets provide requested physical properties like row sort
> ```

`s/resultsets/result sets/g`

---

*[pkg/sql/opt/xform/ops/scalar.opt, line 320 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L3yImH_qudwPp94uRIU:-L42PImEqjGqXWFfvZpp:b-nec2kw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d4389ebcfe9deaab8979c7ada6881e884209e4/pkg/sql/opt/xform/ops/scalar.opt#L320)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Radu is correct. It's really convenient (and more efficient) to make True/False separate operators. I suspect Null will be useful as well, but we can wait until we verify this before adding it. I've added comments to the operators to explain this.
</blockquote></details>

Ok, makes sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847)*

**Comment by andy-kimball** [comment]
Review status: 22 of 38 files reviewed at latest revision, 14 unresolved discussions.

---

*[pkg/sql/opt/xform/ops/enforcer.opt, line 2 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L42P2ekYNcEENXhlHzN:-L42X_wnKzXdE3TnUR7Z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e167b317f5f6a65aa05b206ae1c53a75255c47f8/pkg/sql/opt/xform/ops/enforcer.opt#L2)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/resultsets/result sets/g`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/testutils/datadriven/datadriven.go, line 44 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L3uXaZ-XOmDxfIwRo4v:-L439zUMfH8R72jxliOS:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d4389ebcfe9deaab8979c7ada6881e884209e4/pkg/sql/opt/testutils/datadriven/datadriven.go#L44)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I added a comment about the new syntax. However, I think that we should always require a '----', even for statements with no results. This would allow blank lines to be used in the command input, which right now I work around using dummy comment lines.
```
exec-raw
CREATE DATABASE t
----

optgen compile test.opt
define {}

[Name]
(Foo) => ()

[Name]
(Foo) =>
----
```
What do you think about requiring a '----' separator?
</blockquote></details>

:thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/optgen/lang/testdata/scanner, line 16 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847#-L3uYUQwAQhl3uo25de_:-L439r7JO0PtbZ27qyrf:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d4389ebcfe9deaab8979c7ada6881e884209e4/pkg/sql/opt/optgen/lang/testdata/scanner#L16)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I liked them just because they help my eye pick out the next test case. But maybe I'll just expand the comments more, like this:
```
(IDENT foo)
(COMMENT # comment ()[])

#
# Symbols
#
scan
()[]{}$:*==>&,^|.. ...
----
```
Also, I made another change to allow blank lines within the command "input" section of the datadriven test format. Now, the code will only break once it finds "----". This makes my tests that use blank lines look neater. Do you see any issues with making that change?
</blockquote></details>

:thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21847)*

**Pull request merged**
