### PR TITLE
ui: update url params when switching tabs on sql activity

### PR DESCRIPTION
**Pull request by maryliag**
When the user clicks on a tab on the new SQL Activity page
now the search params on the url is updated with the tab
selection.
This commit also create a common function to sync history
so all the pages can use it and remove duplicate code.

Release note: None

### CODE REVIEW

**Review by lindseyjin — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71762)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lindseyjin and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/util/query/query.ts, line 74 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71762#-MmUUEEc717AIwwkJcIo:-MmUUEEc717AIwwkJcIp:b-vg4rf1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5734152172cee5b7383c1aa16ccb3df258ebebd/pkg/ui/workspaces/cluster-ui/src/util/query/query.ts#L74)):*
> ```XML
>   const nextSearchParams = new URLSearchParams(history.location.search);
> 
>   Object.entries(params).forEach(([key, value]) => {
> ```

Hi, I'm just a little bit confused about how this code works. Why do we need to delete keys in nextSearchParams if they're undefined in params? Is this because we want to keep old param values and only clear them if we explicitly pass in undefined values?

**Review by lindseyjin — COMMENTED** [review]
I tried running this locally, and everything works well!

One quick question though: I noticed that the sql activity page defaults to the Sessions tab, but 'tab=sessions' doesn't appear in the url when you first click into the page. Is that intentional/expected behaviour?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71762#-:-MmUV6k8DoawUb2c6VYk:buk7hqt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lindseyjin and @maryliag)

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71762)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lindseyjin)

___
*[pkg/ui/workspaces/cluster-ui/src/util/query/query.ts, line 74 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71762#-MmUUEEc717AIwwkJcIo:-MmUV_D7E50GmYmYxStg:b-cocr19) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5734152172cee5b7383c1aa16ccb3df258ebebd/pkg/ui/workspaces/cluster-ui/src/util/query/query.ts#L74)):*
<details><summary><i>Previously, lindseyjin (Lindsey Jin) wrote…</i></summary><blockquote>

Hi, I'm just a little bit confused about how this code works. Why do we need to delete keys in nextSearchParams if they're undefined in params? Is this because we want to keep old param values and only clear them if we explicitly pass in undefined values? 
</blockquote></details>

Exactly, if a param is undefined we want to remove from here (no need to keep things in the url that don't add information), if we have a value we want to add/update this value. 
For example, if you go to the statement page and do a search, it will add `q=abc`, then you filter based on app, this will add `app=def` so now you have `q=abc&app=def`, now you want to remove the search, for this on the Statement page we set the value of `q` to undefined and call this function, so now the params will be updated to have just `app=def`

**Review by maryliag — COMMENTED** [review]
It's intentional, since the default value is session, just so we get a cleaner first url, since at that point it won't add any new information

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71762#-:-MmUX6vuD6P3DKh4zYnR:b-kas1a3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lindseyjin)

**Review by lindseyjin — APPROVED** [review]
Thanks for clearing up my questions! LGTM :)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71762#-:-MmUZNdfCVnp9NyWFwY3:bk02m3k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lindseyjin)

**Pull request merged**
