### PR TITLE
tabledesc: stop promoting encoding version counters for secondary idxs

### LINKED ISSUE #78426: sql: a table created on 22.1 cannot be accessed by 21.2 nodes if it has a secondary index
**Describe the problem**
If we create a table on 22.2, the version number for secondary indexes is 4, which is disallowed/invalid on the 21.2 release as index version for secondary indexes. This was due to the lack of a version gate when we decided to simplify the index versioning scheme, leading to validation failures on 21.2.

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**
Setup a mixed version setup where you have one node on 22.2 and one 22.1. 

On the 22.2 node create a new table with a secondary index:
1) `CREATE TABLE IF NOT EXISTS public.table223 (col223_224 TIMESTAMPTZ NOT NULL, col223_225 FLOAT8 NOT NULL, col223_226 REGNAMESPACE NOT NULL, col223_227 TIMESTAMP NOT NULL, col223_228 BIT(11) NOT NULL, col223_229 BYTES NOT NULL, col223_230 STRING NOT NULL AS (CASE WHEN col223_226 IS NULL THEN 'VAgA':::STRING ELSE 'e':::STRING END) STORED, PRIMARY KEY (col223_228 ASC, col223_226 DESC, col223_225 DESC, col223_230 DESC, col223_229, col223_224, col223_227 DESC), INDEX (col223_228 DESC), UNIQUE (col223_228 ASC, col223_227, (CASE WHEN col223_226 IS NULL THEN e'47u\\x7fO3\\t\\x0b':::STRING ELSE '??q':::STRING END), col223_229 DESC), UNIQUE (col223_228 ASC, col223_230, col223_226 DESC, col223_224), UNIQUE (col223_224 ASC, col223_227 ASC, col223_230, col223_229 DESC, col223_228 DESC, col223_226 DESC), UNIQUE (col223_225 ASC, (CASE WHEN col223_226 IS NULL THEN '':::STRING ELSE e'.iu\\x13':::STRING END), col223_229 ASC, col223_228 ASC, col223_227 DESC, col223_230, col223_224), INDEX (col223_230, col223_228, col223_226, col223_229 ASC, col223_227), UNIQUE (col223_228 DESC, col223_229, col223_227 ASC, col223_230, col223_224, col223_226 DESC), UNIQUE (col223_229 ASC, col223_224 ASC, col223_230 DESC, col223_228, col223_225), INDEX (col223_230, col223_224 ASC, col223_225 DESC, col223_227, col223_226 ASC, (CASE WHEN col223_226 IS NULL THEN e'8vV\\x11':::STRING ELSE e'Y\\x04\\x01':::STRING END) ASC));`

On the 21.2
2) Select from the problematic table:
```
root@localhost:26259/defaultdb> select * from public.table224;
*
* ERROR: [n3,client=127.0.0.1:62898,hostssl,user=root] Queued as error df98c1cc1f5b47b6b972ab5656e57951
*
ERROR: internal error: relation "table224" (53): secondary index "table224_col223_228_idx" has invalid version 4 which is for primary indexes
SQLSTATE: XX000
DETAIL: stack trace:
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc/validate.go:1093: validateTableIndexes()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc/validate.go:559: ValidateSelf()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/validate.go:48: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/validate.go:256: validateDescriptorsAtLevel()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/validate.go:44: Validate()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/catalogkv/catalogkv.go:174: descriptorFromKeyValue()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/catalogkv/catalogkv.go:464: getDescriptorByID()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/catalogkv/catalogkv.go:556: MustGetDescriptorByID()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/lease/storage.go:111: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:836: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:908: exec()
/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:835: runTxn()
/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:817: Txn()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/lease/storage.go:90: acquire()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/lease/lease.go:343: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:128: doCall()
/usr/local/go/src/runtime/asm_amd64.s:1371: goexit()

```

What did you do? Describe in your own words.
Create a table on 22.2 with a secondary index, and attempt to access it from 22.1 node.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...
2. Send SQL ... / CLI command ...
3. Look at UI / log file / client app ...

**Expected behavior**

Select should work like normal

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version [e.g. 2.0.x]
 - Server OS: [e.g. Linux/Distrib]
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**
What was the impact?

This is also causing the current failure inside the schema change mixed version workload: https://github.com/cockroachdb/cockroach/issues/78304

Jira issue: CRDB-14128

### PR DESCRIPTION
**Pull request by postamar**
This commit fixes a bug which prevents the correct operation of
a mixed-version cluster: when a table is created with a secondary index
on a 22.1 node, its descriptor will fail validation on a 21.2 node.

To prevent this, this commit no longer sets the encoding version of
secondary indexes to the latest version, but to the version below it.
This is functionally exactly identical for secondary indexes, the latest
version only changes expectations for primary indexes.

Fixes #78426.

Release justification: correctness bug fix
Release note: None

### CODE REVIEW

**Comment by postamar** [comment]
No version-gating necessary. It's just as well, plumbing the cluster version into `RunPostDeserializationChanges` isn't appealing.

**Review by chengxiong-ruan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78670)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/catalog/tabledesc/validate.go, line 1244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78670#-MzHR4_39ccBPwHHoTwU:-MzHR4_49wWniJU_c976:b-kl8g4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/6865e574f6fd5da94b2bf87e9dc9a3f01ae2f695/pkg/sql/catalog/tabledesc/validate.go#L1244)):*
> ```Go
> 		}
> 		if idx.Primary() {
> 			if idx.GetVersion() < descpb.PrimaryIndexWithStoredColumnsVersion {
> ```

good catch!

**Review by ajwerner — COMMENTED** [review]
:thumbsup: this works. We weren't in any real hurry to unify these constants

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78670#-:-MzHTESL2ihmeORbaV3H:b-ibot06)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan and @postamar)

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78670)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @chengxiong-ruan)

___
*[pkg/sql/catalog/tabledesc/validate.go, line 1244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78670#-MzHR4_39ccBPwHHoTwU:-MzHVUQ102B1qXdVs-v2:b-twk5xv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6865e574f6fd5da94b2bf87e9dc9a3f01ae2f695/pkg/sql/catalog/tabledesc/validate.go#L1244)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

good catch!
</blockquote></details>

wait, how is this valid? we can't always auto-promote. Consider a table descriptor with an index that has a much older version that implies a different on-disk layout. What then?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78670)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @chengxiong-ruan)

___
*[pkg/sql/catalog/tabledesc/validate.go, line 1244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78670#-MzHR4_39ccBPwHHoTwU:-MzHVoOhCjZ5fspnFcGz:b-cjxv1z) ([raw file](https://github.com/cockroachdb/cockroach/blob/6865e574f6fd5da94b2bf87e9dc9a3f01ae2f695/pkg/sql/catalog/tabledesc/validate.go#L1244)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

wait, how is this valid? we can't always auto-promote. Consider a table descriptor with an index that has a much older version that implies a different on-disk layout. What then? 
</blockquote></details>

Or did we figure out that we can always auto-promote primary indexes? If so, this is still deeply nuanced and deserves commentary

**Comment by postamar** [comment]
When I originally introduced these changes, I assumed that the field named "index descriptor version" was a version counter on the metadata, when in reality, it's a counter on the encoding scheme for secondary indexes. The damage is done now and this field now conflates both. 

> wait, how is this valid?

It's valid because this field always used to be 0 for primary indexes (it was, after all, denoting the encoding scheme _for secondary indexes_) but now when it's `descpb.PrimaryIndexWithStoredColumnsVersion` this means that its stored column slices have been properly updated.

Really what should have happened is I leave this counter alone and introduce a new one to track upgrades to the descriptor:
- 0 : no upgrade
- 1 : ID slices in the index descriptor are disjoint sets
- 2 : store column ID slice is populated for primary indexes

**Comment by chengxiong-ruan** [comment]
___
*[pkg/sql/catalog/tabledesc/validate.go, line 1244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78670#-MzHR4_39ccBPwHHoTwU:-MzIBRNF-TwvYXX9NIvX:b-5o4hjy) ([raw file](https://github.com/cockroachdb/cockroach/blob/6865e574f6fd5da94b2bf87e9dc9a3f01ae2f695/pkg/sql/catalog/tabledesc/validate.go#L1244)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Or did we figure out that we can always auto-promote primary indexes? If so, this is still deeply nuanced and deserves commentary
</blockquote></details>

Oh, my initial thought was that this fix made it not to fail if we introduced a new version in the future. And also note that this code block is only for `Primary Key` I don't think we don't have a older version for it right?

**Comment by postamar** [comment]
I forgot to update a few tests it seems. No big deal.

**Comment by postamar** [comment]
All good now. Thanks for the reviews!

bors r+

**Pull request merged**
