### PR TITLE
opt: introduce PushLimitIntoOrdinality rule

### PR DESCRIPTION
**Pull request by savoie**
This optimizer rule is the first of several that will push limit
operators as far down the tree as possible, in order to remove the need
for logic in `opt_limits.go` that currently recurses down the plan
tree ensuring that leaf scan nodes have hard limits set even when a
limit operator is much higher up in the tree. The following explanation
is also included as a comment above the rule:

> PushLimitIntoOrdinality pushes the Limit operator into the Ordinality
> operator when the ordering associated with both operators allows it.
>
> Pushing the limit as far as possible down the tree shouldn't have
> negative effects, but will reduce the number of rows processed by
> operators higher up, and if the limit is pushed all the way down to a
> scan, the scan can be limited directly.
>
> In order to prevent this rule from affecting:
> 1. the set of rows kept by the limit,
> 2. the ordinals assigned to those rows by the ordinality, and
> 3. the final ordering of the rows,
> the rule should only be applied if the ordinality's ordering implies
> the original limit's ordering (see OrderingChoice.Implies).
>
> The new limit's ordering must also be "extended" to imply the
> ordinality's ordering, which is done by setting it to be the
> intersection of the old limit's ordering and the ordinality's ordering
> (see OrderingChoice.Intersection).

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Looks good overall!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41908#-:-LryqAc63MySYJx0la8s:b-89nrqy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @savoie)

___
*[pkg/sql/opt/norm/custom_funcs.go, line 408 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41908#-LrypJprEAFoBNgDv0Oh:-LrypJprEAFoBNgDv0Oi:bli4yyl) ([raw file](https://github.com/cockroachdb/cockroach/blob/884a8800e6b838f5aebe070a254a6d73b292625c/pkg/sql/opt/norm/custom_funcs.go#L408)):*
> ```Go
> }
> 
> // Returns whether <ordering1> implies <ordering2>.
> ```

[nit] exported function comments should start with the function name (`OrderingImplies returns ..`).
___
*[pkg/sql/opt/norm/custom_funcs.go, line 413 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41908#-LryoQPOEJHrEUlZvfiL:-LryoQPOEJHrEUlZvfiM:b-my7isv) ([raw file](https://github.com/cockroachdb/cockroach/blob/884a8800e6b838f5aebe070a254a6d73b292625c/pkg/sql/opt/norm/custom_funcs.go#L413)):*
> ```Go
> // is a valid intersection), though it is possible that an intersection exists
> // even if neither ordering implies the other (see OrderingChoice.Intersects).
> func (c *CustomFuncs) OrderingImplies(ordering1, ordering2 physical.OrderingChoice) bool {
> ```

I thought we would be using `Intersects` instead of `Implies`, am I missing something?

As an example, if either of the operator has `a+` while the other has `a+,b+`, we should be able to push down with `a+,b+`
___
*[pkg/sql/opt/norm/rules/limit.opt, line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41908#-LryoBXgDkJGT7PLUisD:-LryoBXh11FcxTCp2dzn:b-vxpztq) ([raw file](https://github.com/cockroachdb/cockroach/blob/884a8800e6b838f5aebe070a254a6d73b292625c/pkg/sql/opt/norm/rules/limit.opt#L109)):*
> ```
>     (Const $limit:*)
>     $limitOrdering:*
>     & (HasColsInOrdering $input $limitOrdering)
> ```

[nit] `&` at the end and next line indented (for consistency with existing style)
___
*[pkg/sql/opt/norm/testdata/rules/limit, line 513 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41908#-LrypdJT4a01_pD_HLXB:-LrypdJT4a01_pD_HLXC:ba3olgt) ([raw file](https://github.com/cockroachdb/cockroach/blob/884a8800e6b838f5aebe070a254a6d73b292625c/pkg/sql/opt/norm/testdata/rules/limit#L513)):*
> ```
> 
> # Complex example of a limit that should be pushed down, since the ordinality's ordering implies
> # the limit ordering: +3 +4 opt(2) => +3 +2.
> ```

[nit] should use the column names in the comment (the col id assignments could change in the future)

**Review by justinj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41908)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @savoie)

___
*[pkg/sql/opt/norm/rules/limit.opt, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41908#-Lryihz_-6sm7OV91az8:-Lryihz_-6sm7OV91az9:b-e3oadi) ([raw file](https://github.com/cockroachdb/cockroach/blob/884a8800e6b838f5aebe070a254a6d73b292625c/pkg/sql/opt/norm/rules/limit.opt#L107)):*
> ```
>         $private:*
>     )
>     (Const $limit:*)
> ```

how come this has to be a `Const`?
___
*[pkg/sql/opt/norm/testdata/rules/limit, line 513 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41908#-LryiyApA3fX2ve5BKeU:-LryiyApA3fX2ve5BKeV:b5son5d) ([raw file](https://github.com/cockroachdb/cockroach/blob/884a8800e6b838f5aebe070a254a6d73b292625c/pkg/sql/opt/norm/testdata/rules/limit#L513)):*
> ```
> 
> # Complex example of a limit that should be pushed down, since the ordinality's ordering implies
> # the limit ordering: +3 +4 opt(2) => +3 +2.
> ```

Is this implication true? The comment above `Implies` seems to indicate no? They do have nonempty intersection (`+3 +2 +4`) which might be what you mean?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41908)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj and @savoie)

___
*[pkg/sql/opt/norm/testdata/rules/limit, line 513 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41908#-LryiyApA3fX2ve5BKeU:-LrywB8M0az7NkCzorGU:b8760xq) ([raw file](https://github.com/cockroachdb/cockroach/blob/884a8800e6b838f5aebe070a254a6d73b292625c/pkg/sql/opt/norm/testdata/rules/limit#L513)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Is this implication true? The comment above `Implies` seems to indicate no? They do have nonempty intersection (`+3 +2 +4`) which might be what you mean?
</blockquote></details>

I'd expect the limit's ordering to also have `opt(i)` since we reduce it using the input FDs (I believe that's what's happening in the plan)

**Review by savoie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41908)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj and @RaduBerinde)

___
*[pkg/sql/opt/norm/custom_funcs.go, line 413 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41908#-LryoQPOEJHrEUlZvfiL:-Lrytb6a0KKYLkGgwmyl:beyyxmf) ([raw file](https://github.com/cockroachdb/cockroach/blob/884a8800e6b838f5aebe070a254a6d73b292625c/pkg/sql/opt/norm/custom_funcs.go#L413)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I thought we would be using `Intersects` instead of `Implies`, am I missing something?

As an example, if either of the operator has `a+` while the other has `a+,b+`, we should be able to push down with `a+,b+`
</blockquote></details>

The minimal counter-example to `Intersects` working that I found was using the orderings `x-` and `<empty>` (which intersect: `x-` is an intersection) on this table `foo`:

```
 x
===
 a
 b
```

```
SELECT * FROM (SELECT * FROM foo WITH ORDINALITY) ORDER BY x DESC LIMIT 1
```

should give the result

```
 x | ordinality
================
 b | 2
```

but if the `LIMIT 1` is pushed into the ordinality you get

```
 x | ordinality
================
 b | 1
```

since only 1 row is ever provided to the ordinality; we're never going to get it to assign the ordinal 2.

On the other hand, with the same orderings but with the _ordinality_ ordering implying the _limit_ ordering, we're OK to push down (if we replace the limit's ordering with the intersection of the two orderings):

```
SELECT * FROM (SELECT * FROM foo ORDER BY x DESC) WITH ORDINALITY LIMIT 1
```
and 
```
SELECT * FROM (SELECT * FROM foo ORDER BY x DESC LIMIT 1) WITH ORDINALITY
```

give the same result:

```
 x | ordinality
================
 b | 1
```

I don't have a perfect proof of why intersection isn't sufficient but implication is, but here's my intuition:

Let's say that the limit is for 10 rows. The limit can only be pushed down into the ordinality if those 10 rows are _exactly_ the first 10 rows (numbered 1-10) of the ordinality ordering. If the rows are the ones that, without applying the rule, would be numbered 2-11, the limit can't be pushed down, since there's no way to tell the ordinality to begin its numbering at 2.

So if (prior to pushing down the limit), the result of the ordinality operation needs to be reordered at all when applying the limit, the limit operator can't be pushed down into the ordinality. (Strictly, the limit could still be pushed down if the set of rows actually selected by the limit remained unchanged, but this can't be known as far as I'm aware.) So it's not enough that an intersection of the two orderings exists; the ordinality ordering needs to imply the limit ordering.
___
*[pkg/sql/opt/norm/rules/limit.opt, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41908#-Lryihz_-6sm7OV91az8:-Lrz4UbX6NM3B1ifvdY4:bj6heec) ([raw file](https://github.com/cockroachdb/cockroach/blob/884a8800e6b838f5aebe070a254a6d73b292625c/pkg/sql/opt/norm/rules/limit.opt#L107)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

how come this has to be a `Const`?
</blockquote></details>

...sometimes I blindly copy existing code without thinking it through; fixed
___
*[pkg/sql/opt/norm/testdata/rules/limit, line 513 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41908#-LryiyApA3fX2ve5BKeU:-Lrz4a3m3GS2BKaArjXN:b-dtgxer) ([raw file](https://github.com/cockroachdb/cockroach/blob/884a8800e6b838f5aebe070a254a6d73b292625c/pkg/sql/opt/norm/testdata/rules/limit#L513)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I'd expect the limit's ordering to also have `opt(i)` since we reduce it using the input FDs (I believe that's what's happening in the plan)
</blockquote></details>

You're both right; I updated the test to include an optional ordering and didn't think the comment through fully. The limit's ordering has an `opt(i)` when the rule is applied, so I've updated the comment.

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/norm/custom_funcs.go, line 413 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41908#-LryoQPOEJHrEUlZvfiL:-Lrz7FUB5nUNBdxB1Nnp:b-6h3owk) ([raw file](https://github.com/cockroachdb/cockroach/blob/884a8800e6b838f5aebe070a254a6d73b292625c/pkg/sql/opt/norm/custom_funcs.go#L413)):*
<details><summary><i>Previously, savoie (Céline O'Neil) wrote…</i></summary><blockquote>

The minimal counter-example to `Intersects` working that I found was using the orderings `x-` and `<empty>` (which intersect: `x-` is an intersection) on this table `foo`:

```
 x
===
 a
 b
```

```
SELECT * FROM (SELECT * FROM foo WITH ORDINALITY) ORDER BY x DESC LIMIT 1
```

should give the result

```
 x | ordinality
================
 b | 2
```

but if the `LIMIT 1` is pushed into the ordinality you get

```
 x | ordinality
================
 b | 1
```

since only 1 row is ever provided to the ordinality; we're never going to get it to assign the ordinal 2.

On the other hand, with the same orderings but with the _ordinality_ ordering implying the _limit_ ordering, we're OK to push down (if we replace the limit's ordering with the intersection of the two orderings):

```
SELECT * FROM (SELECT * FROM foo ORDER BY x DESC) WITH ORDINALITY LIMIT 1
```
and 
```
SELECT * FROM (SELECT * FROM foo ORDER BY x DESC LIMIT 1) WITH ORDINALITY
```

give the same result:

```
 x | ordinality
================
 b | 1
```

I don't have a perfect proof of why intersection isn't sufficient but implication is, but here's my intuition:

Let's say that the limit is for 10 rows. The limit can only be pushed down into the ordinality if those 10 rows are _exactly_ the first 10 rows (numbered 1-10) of the ordinality ordering. If the rows are the ones that, without applying the rule, would be numbered 2-11, the limit can't be pushed down, since there's no way to tell the ordinality to begin its numbering at 2.

So if (prior to pushing down the limit), the result of the ordinality operation needs to be reordered at all when applying the limit, the limit operator can't be pushed down into the ordinality. (Strictly, the limit could still be pushed down if the set of rows actually selected by the limit remained unchanged, but this can't be known as far as I'm aware.) So it's not enough that an intersection of the two orderings exists; the ordinality ordering needs to imply the limit ordering.
</blockquote></details>

`SELECT * FROM foo WITH ORDINALITY`means that the ordinality can be assigned in any order, so both `b 1` and `b 2` are correct results for the query..

**Review by savoie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41908)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj and @RaduBerinde)

___
*[pkg/sql/opt/norm/custom_funcs.go, line 413 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41908#-LryoQPOEJHrEUlZvfiL:-LsNXUyT0WU4zKXwdhbg:bfhgt74) ([raw file](https://github.com/cockroachdb/cockroach/blob/884a8800e6b838f5aebe070a254a6d73b292625c/pkg/sql/opt/norm/custom_funcs.go#L413)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`SELECT * FROM foo WITH ORDINALITY`means that the ordinality can be assigned in any order, so both `b 1` and `b 2` are correct results for the query..
</blockquote></details>

Updated to use intersection, and removed ambiguity in the allowed ordering of the logic tests.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41908#-:-LsNbklj91xoV-VujtAH:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj and @RaduBerinde)

**Review by justinj — COMMENTED** [review]
:lgtm: nice job!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41908#-:-LsXazaD3i4HiNQk7K8w:bxpgx20)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @justinj and @RaduBerinde)

**Pull request merged**
