### PR TITLE
sql,kvserver: stop gossiping the system config

### LINKED ISSUE #54477: sql: cannot perform schema change in transaction after write
**Describe the problem**

Somewhat surprisingly, this long-standing issue has not been represented on its own but rather has been lumped into #26508. Cockroach today broadcasts information about changes to descriptors, zone configs, cluster settings, and tenants via a special commit trigger on the `SystemConfigSpan`. This trigger, set by calling `SetSystemConfigTrigger` necessitates that the transaction's key be a special key (the start of the `SystemConfigSpan`). The `EndTransaction` request then ensures that the trigger is run at application time. The trigger scans the entire span and publishes it to gossip. This gossip used to be used for three purposes but is now used for just two.

* Notifying KV of the system config to power the split queue, merge queue, and zone configs
* Notifying nodes of cluster settings
* (no longer true as of 20.2) notifying nodes of changes to descriptor versions.

The downside of this architecture is that one cannot change a transactions key. A transaction's key is set upon the first write. This leads to the below limitation that is surprising and a problem for compatibility.

```
root@127.0.0.1:40165/movr> CREATE TABLE foo (i INT PRIMARY KEY);
CREATE TABLE
root@127.0.0.1:40165/movr> BEGIN;
BEGIN
root@127.0.0.1:40165/movr  OPEN> INSERT INTO foo VALUES (1);
INSERT 1
root@127.0.0.1:40165/movr  OPEN> ALTER TABLE foo ADD COLUMN j INT;
ERROR: unimplemented: schema change statement cannot follow a statement that has written in the same transaction
SQLSTATE: 0A000
HINT: You have attempted to use a feature that is not yet implemented.
See: https://go.crdb.dev/issue-v/26508/v20.2
```

**Expected behavior**

Ideally we'd support arbitrary mixes of statements in transactions.

**Proposed solution**

There are two classes of solution as far as I'm concerned:

### Rework the zone-configuration and cluster setting infrastructure

In this set of solution I'd like to see us move away from the monolithic, gossipped system config. There are a variety of problems with it which will be discussed in a forthcoming RFC. The current setup really does not work in the context of separate tenants.

My ideal solution would involve rangefeeds and would enable reasonably trivial incremental updates to be broadcasted and cached in a coherent way on all nodes.

### Rework the trigger to occur at intent resolution time rather than commit time

This approach is almost certainly more focused and pragmatic. There would be some concerns about ensuring that the trigger continues to run in `O(txns)` rather than `O(intents)`. Furthermore there's questions about whether this can be feasibly achieved without a change to the protocol. Perhaps a small change to the protocol would be acceptable. 

Epic: CRDB-10489

### LINKED ISSUE #70560: *: stop gossiping the system config span
And start allowing writes before DDLs in transactions. This is tracking issue for what should be the last piece of  #66348 -- work we've been doing so that we no longer need to gossip the system config span. Once all the PRs in #67679 have settled, we should be able to flip the envvar introduced in #69658, and soon after decide to stop gossiping the system config span entirely.

Epic CRDB-10489

### PR DESCRIPTION
**Pull request by ajwerner**
The first commit removes the system config gossip trigger and the client code to set it,
after a version gate has been passed. The primary major change is that in 22.1 binaries, we
no longer rely on the gossip data at any point, instead we adopt the systemconfigwatcher which
is backed by a rangefeed. Part of this change is to adopt that separate data source in the
`GossipSubscription` implementation of the `Connector` API. 

Subsequently, a number of tests needed updating. 

Remove sql.catalog.unsafe_skip_system_config_trigger.enabled
This cluster setting is no longer useful.

Fixes #54477.
Fixes #70560.

Release note (sql change): The limitation that schema change statements in a transaction could not follow
DML statements has been lifted.

### CODE REVIEW

**Review by irfansharif — APPROVED** [review]
:lgtm: 

> Reviewed 59 of 72 files at r1, 6 of 6 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76279#-:-MvuDNWrEICQ0ADf3yKx:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @miretskiy, @nvanbenschoten, and @stevendanna)

___
*[pkg/clusterversion/cockroach_versions.go, line 274 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76279#-MvuAMFD5r7OzdKIsLfq:-MvuAMFE03hExjLXrbBi:b-37inn1) ([raw file](https://github.com/cockroachdb/cockroach/blob/37e04e4f9c176561909bcff56984d857f7997f0b/pkg/clusterversion/cockroach_versions.go#L274)):*
> ```Go
> 	// DisableSystemConfigGossipTrigger is a follow-up to EnableSpanConfigStore
> 	// to disable the data propagation mechanism it and the entire spanconfig
> 	// infrastructure obviate.
> ```

obviates?
___
*[pkg/config/system.go, line 193 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76279#-MvuAd2G3ZsXc2d8zuKP:-MvuAd2G3ZsXc2d8zuKQ:b-nhbsf) ([raw file](https://github.com/cockroachdb/cockroach/blob/37e04e4f9c176561909bcff56984d857f7997f0b/pkg/config/system.go#L193)):*
> ```Go
> func (s *SystemConfig) getIndexBound(key roachpb.Key) int {
> 	if s == nil {
> 		panic("here")
> ```

Looks like debugging holdover.
___
*[pkg/sql/plan.go, line 545 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76279#-MvuCtI50qluVYm4BLN2:-MvuCtI6C5ricnfzB1u9:b-83sjo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/37e04e4f9c176561909bcff56984d857f7997f0b/pkg/sql/plan.go#L545)):*
> ```Go
> func (p *planner) maybeSetSystemConfig(id descpb.ID) error {
> 	if !descpb.IsSystemConfigID(id) || p.execCfg.Settings.Version.IsActive(
> 		p.EvalContext().Ctx(), clusterversion.DisableSystemConfigGossipTrigger,
> ```

Nice.
___
*[pkg/kv/kvserver/client_lease_test.go, line 109 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76279#-MvuE8u07hK7pMtpgKlg:-MvuE8u07hK7pMtpgKlh:b273g33) ([raw file](https://github.com/cockroachdb/cockroach/blob/37e04e4f9c176561909bcff56984d857f7997f0b/pkg/kv/kvserver/client_lease_test.go#L109)):*
> ```Go
> 	zcfg := zonepb.DefaultZoneConfig()
> 	settings := cluster.MakeTestingClusterSettingsWithVersions(
> 		clusterversion.TestingBinaryMinSupportedVersion,
> ```

[pedant] Here and below: should these test be running at DisableSystemConfigGossipTrigger - 1?
___
*[pkg/kv/kvserver/client_split_test.go, line 1021 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76279#-MvuF1ay2rR8h2nXRuG0:-MvuF1ay2rR8h2nXRuG1:b-n353v) ([raw file](https://github.com/cockroachdb/cockroach/blob/3be8121ad9e96416c49c27947facfa18831794b9/pkg/kv/kvserver/client_split_test.go#L1021)):*
> ```Go
> 	ctx := context.Background()
> 	serv, _, _ := serverutils.StartServer(t, base.TestServerArgs{
> 		// This test was written with the SystemConfigSpan in mind.
> ```

There are a handful of tests that make use of DisableSpanConfigs. Some of them, like this one, were too specific to the system config span. Others were just flakey with span config asynchrony and are still being investigated by the home teams. What were you thinking to do for the latter kind?
___
*[pkg/kv/kvserver/client_split_test.go, line 3384 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76279#-MvuFKxI8C2nLNKzoycG:-MvuFKxI8C2nLNKzoycH:b-rkfiq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/37e04e4f9c176561909bcff56984d857f7997f0b/pkg/kv/kvserver/client_split_test.go#L3384)):*
> ```Go
> 	ctx := context.Background()
> 	serv, sqlDB, _ := serverutils.StartServer(t, base.TestServerArgs{
> 		DisableSpanConfigs: true,
> ```

Do we still need this testing flag?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76279)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @irfansharif, @miretskiy, @nvanbenschoten, and @stevendanna)

___
*[pkg/kv/kvserver/client_split_test.go, line 1021 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76279#-MvuF1ay2rR8h2nXRuG0:-Mvut-Yh-mRzLu3O10Zn:bh9nete) ([raw file](https://github.com/cockroachdb/cockroach/blob/3be8121ad9e96416c49c27947facfa18831794b9/pkg/kv/kvserver/client_split_test.go#L1021)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

There are a handful of tests that make use of DisableSpanConfigs. Some of them, like this one, were too specific to the system config span. Others were just flakey with span config asynchrony and are still being investigated by the home teams. What were you thinking to do for the latter kind?
</blockquote></details>

I wasn't really thinking about the latter kind. FWIW, I don't think this specific test is necessarily too specific for span configs. It's a nice integration of a lot of pieces. Perhaps too many, but that's neither here nor there. What's amazing is how old this test is. I could be convinced we cover this whole story elsewhere, but i wouldn't want to be tasked with figuring out where. 
___
*[pkg/kv/kvserver/client_split_test.go, line 3384 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76279#-MvuFKxI8C2nLNKzoycG:-Mvuse_Q-NgjhgAhgp3N:br398i6) ([raw file](https://github.com/cockroachdb/cockroach/blob/37e04e4f9c176561909bcff56984d857f7997f0b/pkg/kv/kvserver/client_split_test.go#L3384)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Do we still need this testing flag?
</blockquote></details>

Yes, the `config.TestingSetupZoneConfigHook` doesn't seem to obviously apply in the same way with the span config ecosystem. The lowering of the closed timestamp stuff is about making the `systemconfigwatcher` faster. It's pretty lame. I considered going all the way to using span config infra for this test but then backed off.

**Review by nvb — APPROVED** [review]
> Reviewed 54 of 72 files at r1, 4 of 6 files at r2, 14 of 14 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76279)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @arulajmani, @irfansharif, @miretskiy, and @stevendanna)

___
*[pkg/config/provider.go, line 28 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76279#-MvyPd8984NVrMu8hvJN:-MvyPd8984NVrMu8hvJO:b-lnhmax) ([raw file](https://github.com/cockroachdb/cockroach/blob/b23b3defa5bb57852627ba1284253f619be79831/pkg/config/provider.go#L28)):*
> ```Go
> 
> // ConstantSystemConfigProvider is an implementation of SystemConfigProvider that
> // never provides a system config.
> ```

This comment is now stale.
___
*[pkg/config/provider.go, line 38 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76279#-MvyPjHBDzZtVC4TAHAW:-MvyPjHBDzZtVC4TAHAX:b5pzbt8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9514f13d0190849eda12b39e272c278b82c269f4/pkg/config/provider.go#L38)):*
> ```Go
> // RegisterSystemConfigChannel implements the SystemConfigProvider interface.
> func (EmptySystemConfigProvider) RegisterSystemConfigChannel() <-chan struct{} {
> 	// The system config will never be updated, so return a nil channel.
> ```

Consider keeping this comment.
___
*[pkg/gossip/gossip.go, line 1151 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76279#-MvyPrfbCmeJyq1vJ_FX:-MvyPrfbCmeJyq1vJ_FY:b-4vpim5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b23b3defa5bb57852627ba1284253f619be79831/pkg/gossip/gossip.go#L1151)):*
> ```Go
> // Returns nil if the system config hasn't been set yet.
> //
> // TODO(ajwerner): Remove this in 22.2.
> ```

Is it worth opening an issue to track all of these follow-up tasks?
___
*[pkg/gossip/keys.go, line 73 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76279#-MvyQ2371N1RA5v_5U7m:-MvyQ2371N1RA5v_5U7n:b4bhkf6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b23b3defa5bb57852627ba1284253f619be79831/pkg/gossip/keys.go#L73)):*
> ```Go
> 	// in 22.1.
> 	//
> 	// TODO(ajwerner): Delete in 22.2.
> ```

In a cluster that only performs rolling upgrades and that adds information to gossip with no ttl, can we guarantee that the information won't stick around in the gossip network forever? If not, then we should probably mark this as a retired gossip key but keep it around in v22.2, instead of removing it entirely, as it would be incorrect to ever use the key again.
___
*[pkg/migration/migrations/descriptor_utils.go, line 60 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76279#-MvyRSPO8GfLwIVAoerL:-MvyRSPO8GfLwIVAoerM:b-a7mzmb) ([raw file](https://github.com/cockroachdb/cockroach/blob/9514f13d0190849eda12b39e272c278b82c269f4/pkg/migration/migrations/descriptor_utils.go#L60)):*
> ```Go
> 		b.CPut(tKey, desc.GetID(), nil)
> 		b.CPut(catalogkeys.MakeDescMetadataKey(codec, desc.GetID()), desc.DescriptorProto(), nil)
> 		if err := txn.SetSystemConfigTrigger(codec.ForSystemTenant()); err != nil {
> ```

What allows us to remove this unconditionally?
___
*[pkg/server/node.go, line 1330 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76279#-MvyS1PA7DW3jtMRu-7Q:-MvyS1PA7DW3jtMRu-7R:b-buh6qf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b23b3defa5bb57852627ba1284253f619be79831/pkg/server/node.go#L1330)):*
> ```Go
> 	var systemConfigUpdateCh <-chan struct{}
> 	for _, pattern := range args.Patterns {
> 		switch pattern := pattern; pattern {
> ```

nit: keep `pattern := pattern` on a separate line, and may even give it a comment:
```go
pattern := pattern // copy for callback
```
___
*[pkg/server/node.go, line 1333 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76279#-MvySYJq7-mp79X_s-0m:-MvySYJq7-mp79X_s-0n:b-9wnh0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/b23b3defa5bb57852627ba1284253f619be79831/pkg/server/node.go#L1333)):*
> ```Go
> 		// Note that we need to support clients subscribing to the system config
> 		// over this RPC even if the system config is no longer stored in gossip
> 		// in the host cluster. To achieve this, we special-case the system config
> ```

Could you add a sentence about why we need to continue to support this?
___
*[pkg/server/node.go, line 1337 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76279#-MvyRnifCyJKr2iwcUAb:-MvyRnifCyJKr2iwcUAc:btyue49) ([raw file](https://github.com/cockroachdb/cockroach/blob/b23b3defa5bb57852627ba1284253f619be79831/pkg/server/node.go#L1337)):*
> ```Go
> 		//
> 		// TODO(ajwerner): Remove support for the system config key in the
> 		// in 22.2, or leave it and make it a no-op.
> ```

Could you remind me what the migration story is for multi-tenant clusters? By the time we roll out a v22.2 host cluster, all SQL pods will be running v22.1?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76279)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @arulajmani, @irfansharif, @miretskiy, @nvanbenschoten, and @stevendanna)

___
*[pkg/clusterversion/cockroach_versions.go, line 274 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76279#-MvuAMFD5r7OzdKIsLfq:-MvzRY1FCZcTdCAi4X7T:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/37e04e4f9c176561909bcff56984d857f7997f0b/pkg/clusterversion/cockroach_versions.go#L274)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

obviates?
</blockquote></details>

Done.
___
*[pkg/config/provider.go, line 28 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76279#-MvyPd8984NVrMu8hvJN:-MvzaS8UBiKjEjiJ_RQy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b23b3defa5bb57852627ba1284253f619be79831/pkg/config/provider.go#L28)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This comment is now stale.
</blockquote></details>

Done.
___
*[pkg/config/provider.go, line 38 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76279#-MvyPjHBDzZtVC4TAHAW:-MvzaUZIB-qHW5Cy8rKw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9514f13d0190849eda12b39e272c278b82c269f4/pkg/config/provider.go#L38)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Consider keeping this comment.
</blockquote></details>

Done.



_Code quote:_
```Go
// The system config will never be updated, so return a nil channel.
```
___
*[pkg/gossip/gossip.go, line 1151 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76279#-MvyPrfbCmeJyq1vJ_FX:-MvzTcvHCgVjnPe7Mw3L:b-l4iubk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b23b3defa5bb57852627ba1284253f619be79831/pkg/gossip/gossip.go#L1151)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is it worth opening an issue to track all of these follow-up tasks?
</blockquote></details>

https://github.com/cockroachdb/cockroach/issues/76625
___
*[pkg/gossip/keys.go, line 73 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76279#-MvyQ2371N1RA5v_5U7m:-MvzWmOg6SZ3_VwMfJkc:b-nvox8o) ([raw file](https://github.com/cockroachdb/cockroach/blob/b23b3defa5bb57852627ba1284253f619be79831/pkg/gossip/keys.go#L73)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

In a cluster that only performs rolling upgrades and that adds information to gossip with no ttl, can we guarantee that the information won't stick around in the gossip network forever? If not, then we should probably mark this as a retired gossip key but keep it around in v22.2, instead of removing it entirely, as it would be incorrect to ever use the key again.
</blockquote></details>

For now, I've adopted your suggestion, though it doesn't seem too wild to write a migration to just remove the information. 
___
*[pkg/migration/migrations/descriptor_utils.go, line 60 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76279#-MvyRSPO8GfLwIVAoerL:-MvzXU6y34gIV7136_xE:b-k5dpa4) ([raw file](https://github.com/cockroachdb/cockroach/blob/9514f13d0190849eda12b39e272c278b82c269f4/pkg/migration/migrations/descriptor_utils.go#L60)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What allows us to remove this unconditionally?
</blockquote></details>

We haven't added any system tables before the migration which enables all of the span config infrastructure. It's admittedly subtle. 
___
*[pkg/server/node.go, line 1333 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76279#-MvySYJq7-mp79X_s-0m:-Mvza07h1IUmgWTGMcmE:b-tiohf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b23b3defa5bb57852627ba1284253f619be79831/pkg/server/node.go#L1333)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could you add a sentence about why we need to continue to support this?
</blockquote></details>

Well, I said something, but it lead to me thinking more deeply about it, and I'm not pleased with the current situation. https://cockroachlabs.slack.com/archives/C020NSBH63F/p1644965222776869
___
*[pkg/server/node.go, line 1337 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76279#-MvyRnifCyJKr2iwcUAb:-Mvz_XMLBuJtswKbWxq_:b-1ul8s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b23b3defa5bb57852627ba1284253f619be79831/pkg/server/node.go#L1337)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could you remind me what the migration story is for multi-tenant clusters? By the time we roll out a v22.2 host cluster, all SQL pods will be running v22.1?
</blockquote></details>

That's correct. 
___
*[pkg/kv/kvserver/client_lease_test.go, line 109 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76279#-MvuE8u07hK7pMtpgKlg:-MvzaNM77FCyhhnaLqy7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/37e04e4f9c176561909bcff56984d857f7997f0b/pkg/kv/kvserver/client_lease_test.go#L109)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

[pedant] Here and below: should these test be running at DisableSystemConfigGossipTrigger - 1?
</blockquote></details>

Done.
___
*[pkg/config/system.go, line 193 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76279#-MvuAd2G3ZsXc2d8zuKP:-MvzTGvv9dENwmzbtWNL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/37e04e4f9c176561909bcff56984d857f7997f0b/pkg/config/system.go#L193)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Looks like debugging holdover.
</blockquote></details>

Done.

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Pull request merged**
