### PR TITLE
config/storage: Add lease placement preferences to ZoneConfigs

### PR DESCRIPTION
**Pull request by a-robinson**
Lease preferences can be specified in a mostly similar format to
constraints. For example, to first prefer putting the lease in
`region=us-east`, then to prefer putting it in
`region=us-west,zone=us-west1-b`, you'd specify:

lease_preferences: [[+region=us-east], [+region=us-west,+zone=us-west1-b]]

Touches (but doesn't strictly resolve) #21420 and #17119

Release note (cli change): Replication zone configs now allow for
specifying an ordered list of lease placement preferences. Whenever
possible, CockroachDB will attempt to put the lease for a range on a
store that satisfies the first set of constraints. If that's not
possible, it'll attempt to put the lease on a store that satisfies the
second set of constraints, and so on. If none of the preferences can be
met, the lease will be placed as it is today.

------------------------

I'm sending this out to show it's actually quite easy to support this. There's a reasonable debate to have over the basic YAML format I've chosen, and I'll have to spend a few hours writing tests to add on to the bit of manual testing I've done, but if product thinks this is critical for the partitioning use cases customers have, getting this in for 2.0 is very doable.

cc @awoods187 @petermattis @BramGruneir

### CODE REVIEW

**Comment by BramGruneir** [comment]
Awesome!   I'll give it a review tomorrow.

**Comment by a-robinson** [comment]
As an example from my local testing, I spun up a 4 node cluster where each node had a different locality. This screenshot shows the change from me specifying `lease_preferences: [["+dc=4"], ["+dc=3"]]` to `lease_preferences: [["+dc=1"], ["+dc=4"]]` on the .default zone while all other zones (.meta, .liveness, system.jobs) were pinned to `dc=4` because I had set both `constraints` and `lease_preferences` appropriately:

screen shot 2018-02-27 at 10 48 08 pm

**Comment by petermattis** [comment]
Neat. I think we should chat with @danhhz and @benesch and @awoods187. If we don't want to squeeze this into 2.0, we might consider it for cherry-picking into a patch release. 

---

Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/config/zone.proto, line 112 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23202#-L6Rhz4t3x-0kYORVyE8:-L6Rhz4t3x-0kYORVyE9:b-jglt2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/37a5fbaade034dc7b3f3f4a85fe65f2a1ec77367/pkg/config/zone.proto#L112)):*
> ```protobuf
>   // most preferred to lease preferred. The first preference that an existing
>   // replica of a range matches will take priority.
>   repeated LeasePreference lease_preferences = 9 [(gogoproto.nullable) = false, (gogoproto.moretags) = "yaml:\"lease_preferences,flow\""];
> ```

Rather than a separate array of constraints for lease preferences, I would have added a `Constraints.lease_priority` field. Perhaps you considered that and found it lacking. Seeing that the changes to lease placement in this PR are relatively small, my biggest concern is that we get the right semantics in the `ZoneConfig`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23202#-:-L6RhfVyYGohdaHokwXu:b-brx154)*

**Comment by a-robinson** [comment]
> Neat. I think we should chat with @danhhz and @benesch and @awoods187. If we don't want to squeeze this into 2.0, we might consider it for cherry-picking into a patch release.

Finding time for a scheduled chat is tough given your full calendar, but I'll set something up for tomorrow in case people prefer a meeting to deciding on github/slack.

**Comment by bdarnell** [comment]
We should be very careful about adding new features in a patch release. In particular, we really don't want to add features that require a new cluster version in a patch release unless it's *really* important. I think we should get this in to 2.0 or wait until 2.1.

In most cases, wouldn't follow-the-workload do the right thing here? I'm slightly wary of exposing new knobs for this - how confident are we that manual control is necessary?

---

Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23202#-:-L6S_e3ubEMON-dVRQYY:b-38nf2)*

**Comment by BramGruneir** [comment]
When chatting with a potential client, this was a large concern for them.  The only thing we could give them at this time was the aggression setting `kv.allocator.lease_rebalancing_aggressiveness` and the assurance that "it would move quickly" wasn't good enough. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23202#-:-L6SeTCH7gxAIpkOiqQ9:bh430rr)*

**Comment by BramGruneir** [comment]
The change itself LGTM and is really quite simple, but it requires a lot of testing.

I have no opinion on the format.  I'll leave that to others.

As mentioned in the meeting, adding experimental to this somehow would be good (if it's not too crazy).

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/set_zone_config.go, line 196 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23202#-L6TC4rCWx1nqPSbLrXo:-L6TC4rCWx1nqPSbLrXp:bcz0oy3) ([raw file](https://github.com/cockroachdb/cockroach/blob/37a5fbaade034dc7b3f3f4a85fe65f2a1ec77367/pkg/sql/set_zone_config.go#L196)):*
> ```Go
> 		}
> 	}
> 	if len(zone.LeasePreferences) > 1 {
> ```

`> 1` ?  Shouldn't this be `> 0`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23202#-:-L6TEFyq47Mta7AcKqxo:bo30lqf)*

**Comment by a-robinson** [comment]
Review status: 14 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/config/zone.proto, line 112 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23202#-L6Rhz4t3x-0kYORVyE8:-L6TPyN7h2DFgkR8ieOq:bn6c37k) ([raw file](https://github.com/cockroachdb/cockroach/blob/37a5fbaade034dc7b3f3f4a85fe65f2a1ec77367/pkg/config/zone.proto#L112)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Rather than a separate array of constraints for lease preferences, I would have added a `Constraints.lease_priority` field. Perhaps you considered that and found it lacking. Seeing that the changes to lease placement in this PR are relatively small, my biggest concern is that we get the right semantics in the `ZoneConfig`.
</blockquote></details>

I agree that getting the right API here is the toughest problem.

I had/have two main issues with doing something like adding a `lease_priority` field to the existing `Constraints` object:

1. How do we continue to shoehorn more fields into the already clunky yaml format for constraints?
2. It gets a little awkward if your lease preferences don't directly align with your constraints. Say you manually put a replica in `region=us-west1,zone=us-west1-a` and in `region=us-west1,zone=us-west1-b` but just want to make sure the lease is in `us-west1`. We have to define a form of priority that allows for ties, and then educate users on it. Or say you don't actually want to deal with constraining your replicas at all and just want to trust diversity for that, but still want to make sure the lease is put in a certain region.

---

*[pkg/sql/set_zone_config.go, line 196 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23202#-L6TC4rCWx1nqPSbLrXo:-L6XXS4LXM4OJT2R-ZG8:b2nxmgo) ([raw file](https://github.com/cockroachdb/cockroach/blob/37a5fbaade034dc7b3f3f4a85fe65f2a1ec77367/pkg/sql/set_zone_config.go#L196)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

`> 1` ?  Shouldn't this be `> 0`?
</blockquote></details>

Indeed, good catch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23202)*

**Comment by BramGruneir** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23202)*

**Comment by a-robinson** [comment]
PTAL. Updated to make the field experimental and hidden by default and to add tests. I also made one change to the existing lease transfer target selection behavior in certain edge cases in the first commit. If you object I think we'll be ok without it, but on the balance I think we're better off with it.

---

Review status: 0 of 18 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23202#-:-L6mkeg22rSp1eKpeG9t:b-uybckr)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 18 of 18 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/allocator.go, line 706 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23202#-L6neoYG5geE1bMWAPYi:-L6neoYH8RE5Xos6MwpJ:b66ra6q) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee1723e91d25d3e307ebeac3fbb76c82ec4da0ac/pkg/storage/allocator.go#L706)):*
> ```Go
> 		// If we aren't supposed to be considering the current leaseholder (e.g.
> 		// because we need to remove this replica for some reason), return
> 		// our best option if it we otherwise wouldn't want to do anything.
> ```

Too many pronouns.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23202#-:-L6nf7sm33b1Vb034tOG:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/config/zone.proto, line 112 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23202#-L6Rhz4t3x-0kYORVyE8:-L6mrEaJ8x5t9kJgDKjV:b-icvrpe) ([raw file](https://github.com/cockroachdb/cockroach/blob/37a5fbaade034dc7b3f3f4a85fe65f2a1ec77367/pkg/config/zone.proto#L112)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

I agree that getting the right API here is the toughest problem.

I had/have two main issues with doing something like adding a `lease_priority` field to the existing `Constraints` object:

1. How do we continue to shoehorn more fields into the already clunky yaml format for constraints?
2. It gets a little awkward if your lease preferences don't directly align with your constraints. Say you manually put a replica in `region=us-west1,zone=us-west1-a` and in `region=us-west1,zone=us-west1-b` but just want to make sure the lease is in `us-west1`. We have to define a form of priority that allows for ties, and then educate users on it. Or say you don't actually want to deal with constraining your replicas at all and just want to trust diversity for that, but still want to make sure the lease is put in a certain region.
</blockquote></details>

Ack. Yeah, `Constraints.lease_priority` comes with drawbacks. Glad this is being marked as experimental. Carry on.

---

*[pkg/storage/allocator.go, line 659 at r4](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23202#-L6ms96a1n3bWULr2kOy:-L6ms96a1n3bWULr2kOz:b-keyja4) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d093e120e9b9c8b69b78d77fa8d777a3236124e/pkg/storage/allocator.go#L659)):*
> ```Go
> 		// existing when checkTransferLeaseSource is false? I'd do it now, but
> 		// it's too big a change to make right before a major release.
> 		var options []roachpb.ReplicaDescriptor
> ```

Nit: the name `options` is confusing here. Looking at the code below I thought it referred to some sort of `options` struct. Perhaps `candidates` which is a term we use elsewhere. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23202)*

**Comment by a-robinson** [comment]
TFTRs! I'll merge this afternoon if I don't hear from anyone else.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/storage/allocator.go, line 706 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23202#-L6neoYG5geE1bMWAPYi:-L6qeaY08dMclbwrP-iw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee1723e91d25d3e307ebeac3fbb76c82ec4da0ac/pkg/storage/allocator.go#L706)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Too many pronouns.
</blockquote></details>

Done.

---

*[pkg/storage/allocator.go, line 659 at r4](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23202#-L6ms96a1n3bWULr2kOy:-L6qeb8B6xfeDKLJiijB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d093e120e9b9c8b69b78d77fa8d777a3236124e/pkg/storage/allocator.go#L659)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: the name `options` is confusing here. Looking at the code below I thought it referred to some sort of `options` struct. Perhaps `candidates` which is a term we use elsewhere. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23202#-:-L6qedel-duQczvtebwg:b2p1nt0)*

**Pull request merged**
