### PR TITLE
distsql: distribute GROUP BY aggregations

### PR DESCRIPTION
**Pull request by RaduBerinde**
We now distribute aggregations that have a GROUP BY (by hash of the GROUP BY
columns).

CC @asubiotto - hopefully this helps some of the TPC-H queries that run out of memory.

### CODE REVIEW

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 986 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15016#-Ki0ah1JdoSm1t8E1yR2:-Ki0ah1JdoSm1t8E1yR3:b-lm71qp) ([raw file](https://github.com/cockroachdb/cockroach/blob/53518d61b7b05825a7479e2af8125c2f8e257504/pkg/sql/distsql_physical_planner.go#L986)):*
> ```Go
> 	}
> 
> 	// TODO(radu): we could distribute the final stage by hash.
> ```

TODO is being addressed :)
But please leave a comment that the code is dealing with the global stage now.

---

*[pkg/sql/distsql_physical_planner.go, line 1012 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15016#-Ki0cIk67JuQduRU0_uG:-Ki0cIk67JuQduRU0_uH:bujg7et) ([raw file](https://github.com/cockroachdb/cockroach/blob/53518d61b7b05825a7479e2af8125c2f8e257504/pkg/sql/distsql_physical_planner.go#L1012)):*
> ```Go
> 		)
> 	} else {
> 		// Distribute (by group columns) to multiple processors; we have one
> ```

it's a pretty arbitrary decision to have one global aggregator per node in the previous stage. Consider saying this in the comment.

---

*[pkg/sql/distsql_physical_planner.go, line 1033 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15016#-Ki0c9PHC-Qd8mtkenzl:-Ki0c9PHC-Qd8mtkenzm:b-6748ta) ([raw file](https://github.com/cockroachdb/cockroach/blob/53518d61b7b05825a7479e2af8125c2f8e257504/pkg/sql/distsql_physical_planner.go#L1033)):*
> ```Go
> 		}
> 
> 		// Set up the output routers from the previous stage.
> ```

nit: set up the output routers before the global stage aggregator procs above, to reflect the data flow.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15016#-:-Ki0ccJDp8MKSMdjH2IU:bnfp4nl)*

**Comment by RaduBerinde** [comment]
TFTR!

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 986 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15016#-Ki0ah1JdoSm1t8E1yR2:-Ki0wlfkFZATOu1pz3YL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/53518d61b7b05825a7479e2af8125c2f8e257504/pkg/sql/distsql_physical_planner.go#L986)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

TODO is being addressed :)
But please leave a comment that the code is dealing with the global stage now.
</blockquote></details>

Done.

---

*[pkg/sql/distsql_physical_planner.go, line 1012 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15016#-Ki0cIk67JuQduRU0_uG:-Ki0x2Zj2RKN0qStnUnJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/53518d61b7b05825a7479e2af8125c2f8e257504/pkg/sql/distsql_physical_planner.go#L1012)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

it's a pretty arbitrary decision to have one global aggregator per node in the previous stage. Consider saying this in the comment.
</blockquote></details>

Done.

---

*[pkg/sql/distsql_physical_planner.go, line 1033 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15016#-Ki0c9PHC-Qd8mtkenzl:-Ki0xJaCSCasRC9Lrdu6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/53518d61b7b05825a7479e2af8125c2f8e257504/pkg/sql/distsql_physical_planner.go#L1033)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: set up the output routers before the global stage aggregator procs above, to reflect the data flow.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15016#-:-Ki10sEXV3s4qP5O35Bv:b-814g8k)*

**Comment by arjunravinarayan** [comment]
:lgtm_strong: the example plans look great, I did a local checkout and tried a few others and it all checks out.

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15016#-:-Ki1UF4IOrpP2H2LfCTY:bnb80td)*

**Comment by RaduBerinde** [comment]
Thanks for checking!

---

Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15016#-:-Ki1Wmt3sHHsQYYyVGhI:b-nav91e)*

**Pull request merged**
