### PR TITLE
backupccl: simplify the restore pause test

### PR DESCRIPTION
**Pull request by dt**
This simplifies the pause/resume test: it now requires only that the job
be paused and resumed more than once while it was making progress.
Previously the restore/pause test watched until the watermark moved to
do a pause and resume -- however with unpredictable chunk execution
order, the watermark sometimes moved too soon or late, making it flaky.

With this change, I no longer get the unepected state error or hanging,
thought I still see the usual occassional liveness failures.

### CODE REVIEW

**Comment by mjibson** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/ccl/backupccl/backup_test.go, line 940 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24604#-L9f_Pdt1JyLTeei4meP:-L9f_Pdt1JyLTeei4meQ:bgvo9o) ([raw file](https://github.com/cockroachdb/cockroach/blob/83040f8aee5db982ba5f4b3d609b9197f18417b1/pkg/ccl/backupccl/backup_test.go#L940)):*
> ```Go
> 				t.Fatalf("%d: expected 'job paused' error, but got %+v", i, err)
> 			}
> 			if i == 1 {
> ```

Can you document in the commit message why this code block can be removed? Does the test still test what it is supposed to? From my read of it, a PAUSE/RESUME/PAUSE can be the same as just PAUSE since the executor may not see the middle RESUME state.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24604)*

**Comment by dt** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/ccl/backupccl/backup_test.go, line 940 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24604#-L9f_Pdt1JyLTeei4meP:-L9fbodb6NQZ2FtTQ1ho:b-1jsyp9) ([raw file](https://github.com/cockroachdb/cockroach/blob/83040f8aee5db982ba5f4b3d609b9197f18417b1/pkg/ccl/backupccl/backup_test.go#L940)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Can you document in the commit message why this code block can be removed? Does the test still test what it is supposed to? From my read of it, a PAUSE/RESUME/PAUSE can be the same as just PAUSE since the executor may not see the middle RESUME state.
</blockquote></details>

reworded. also added a send on the ch to ensure we wait between steps.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24604)*

**Review by madelynnblue — APPROVED** [review]
Ok, I think this works now because `jobs.TestingSetProgressThreshold(-1.0)` is set. BACKUP and RESTORE call the job progress func after every request, so the chan wait between pause/resume/pause should work there. Documenting here for the archives and my own understanding.

**Pull request merged**
