### PR TITLE
sql: add support for `IF NOT EXISTS` for `ALTER TABLE ADD CONSTRAINT`

### LINKED ISSUE #53007: Add syntax for to use "IF NOT EXISTS" modifier to "ALTER TABLE add CONSTRAINT"
To simplify pre-check coding, it would be great to have the "IF NOT EXISTS" modifier added.  Consider the following example:

```
root@localhost:26257/defaultdb> CREATE TABLE feedback (id uuid primary key, hash string);
CREATE TABLE

Time: 9.601966ms

root@localhost:26257/defaultdb> ALTER TABLE feedback ADD CONSTRAINT feedback_hash_key UNIQUE (hash);
ALTER TABLE

Time: 166.699451ms

root@localhost:26257/defaultdb> ALTER TABLE feedback ADD CONSTRAINT feedback_hash_key UNIQUE (hash);
ERROR: duplicate constraint name: "feedback_hash_key"
SQLSTATE: 42710
```
Would like to have the following return without throwing an error:

```
ALTER TABLE feedback ADD CONSTRAINT IF NOT EXISTS feedback_hash_key UNIQUE (hash);
```

### PR DESCRIPTION
**Pull request by ekalinin**
Fixes #53007 

This commit adds the option `IF NOT EXISTS` to the `ALTER TABLE ADD
CONSTRAINT`. With this option `pgcode.DuplicateObject` will not be raised.

Release note (sql change): Add support for `IF NOT EXISTS` option for
`ALTER TABLE ADD CONSTRAINT` command.

### CODE REVIEW

**Comment by rohany** [comment]
I'm hesitant to accept this because of my concern on the issue. I'll review it once we come to a conclusion there

**Comment by ajwerner** [comment]
And 12 months later, I think we're up for this. Let's get @vy-ton to sign off. Any reason not to? The accepted workaround in postgres is to drop in `plpgsql` which isn't something we can do at this point. @ekalinin are you up for rebasing this?

**Comment by vy-ton** [comment]
+1 to adding this, thanks for the contribution!

**Comment by ekalinin** [comment]
> And 12 months later, I think we're up for this. Let's get @vy-ton to sign off. Any reason not to? The accepted workaround in postgres is to drop in `plpgsql` which isn't something we can do at this point. @ekalinin are you up for rebasing this?

Sure, will do it!

**Pull request closed without merging**
