### PR TITLE
build: default release builds to "linux-gnu"

### PR DESCRIPTION
**Pull request by petermattis**
Change mkrelease to use "linux-gnu" as the release configuration if no
argument was specified. This provides a minor simplification for
building a linux release binary for testing (`mkrelease` vs `mkrelease
linux-gnu`).

Release note: None

### CODE REVIEW

**Review by benesch — APPROVED** [review]
:lgtm:

Everything below is an optional nit.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27547#-:-LHOaCrt6n6hY4jZx2xX:bqe811p)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[build/builder/mkrelease.sh, line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27547#-LHO_wKKCwS28dtPj-t8:-LHO_wKKCwS28dtPj-t9:b-pt0uff) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e04e5cfc74b5faa26e29f207a60236321db7b40/build/builder/mkrelease.sh#L6)):*
> ```Shell
> # for a different platform. It must be run in the cockroachdb/builder docker
> # image, as it depends on cross-compilation toolchains available there.
> #
> ```

Consider adding usage information here now that the invoking the script with no arguments doesn't print usage.

```
Usage:
    
    mkrelease TARGET [MAKE-ARGS...]
```
___
*[build/builder/mkrelease.sh, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27547#-LHO_V0nELnvYLiK3nYh:-LHO_V0nELnvYLiK3nYi:b-osr9b3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e04e5cfc74b5faa26e29f207a60236321db7b40/build/builder/mkrelease.sh#L30)):*
> ```Shell
> 
> case "${1-linux-gnu}" in
>   ?(amd64-)linux?(-gnu))
> ```

Consider:

```shell
case "${1-}" in
  ""|?(amd64-)linux?(-gnu))
  # ...
```
___
*[build/builder/mkrelease.sh, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27547#-LHO_ObE4cGDA8ukhpqS:-LHO_ObF7ocONgp1cL87:bt6qawm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e04e5cfc74b5faa26e29f207a60236321db7b40/build/builder/mkrelease.sh#L90)):*
> ```Shell
>     ) ;;
> 
>   "") die "usage: $0 RELEASE-CONFIGURATION [MAKE-GOALS...]" ;;
> ```

This line is now unreachable. Consider removing it.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27547)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[build/builder/mkrelease.sh, line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27547#-LHO_wKKCwS28dtPj-t8:-LHOpyR4EntpZ9M5Jx00:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e04e5cfc74b5faa26e29f207a60236321db7b40/build/builder/mkrelease.sh#L6)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Consider adding usage information here now that the invoking the script with no arguments doesn't print usage.

```
Usage:
    
    mkrelease TARGET [MAKE-ARGS...]
```
</blockquote></details>

Done.

**Review by benesch — APPROVED** [review]
Thanks for the s/target/configuration/ fix. That was bothering me too.

**Comment by petermattis** [comment]
bors r=benesch

**Pull request merged**
