### PR TITLE
release-22.2: gossip: remove frequent gossiping of gossip client connections

### PR DESCRIPTION
**Pull request by irfansharif**
Backport 1/1 commits from #89613.

/cc @cockroachdb/release

---

These gossip-clients keys make up two thirds or more of the gossip traffic in various large clusters I've inspected, consuming almost an entire CPU core in the worst case I've seen. They don't provide enough value to justify that sort of ongoing cost, so this commit removes them entirely as well as the periodic logging of the gossip network and the crdb_internal.gossip_network table, both of which relied on them.

These gossip-clients keys make up two thirds or more of the gossip traffic in various large clusters I've inspected, consuming almost an entire CPU core in the worst case I've seen. They don't provide enough value to justify that sort of  ongoing cost, so this commit removes them entirely as well as the periodic logging of the gossip network and the crdb_internal.gossip_network table, both of which relied on them.

Release note (backward-incompatible change): We've stopped supporting/populating the crdb_internal.gossip_network table. It was an internal table with no API guarantees (so perhaps no meriting a release note?).

Release note (performance improvement): Significantly reduced CPU usage of the underlying gossip network in large clusters.

Release justification: performance improvement for large clusters.

### CODE REVIEW

**Review by tbg — APPROVED** [review]
Couple weeks of bake time, right?

**Review by kvoli — APPROVED** [review]
The CI failure looks like a `vendor` issue, happening on other backports as well. A fix is in the  works? ([internal slack](https://cockroachlabs.slack.com/archives/CJ0H8Q97C/p1671570121246449)).

**Review by a-robinson — APPROVED** [review]
Thanks for getting this across the finish line, @irfansharif !

**Comment by irfansharif** [comment]
Been two weeks.

**Pull request merged**
