### PR TITLE
sql: add feature flag checking for UDF statements

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
Release note: None
Release justification: low risk feature flags for DDL statements.

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
LGTM

**Review by Xiang-Gu — APPROVED** [review]
Should we also add this check for `CREATE FUNCTION`?

**Comment by chengxiong-ruan** [comment]
> Should we also add this check for `CREATE FUNCTION`?

oh, that has been added before this pr : https://github.com/cockroachdb/cockroach/blob/04c6a1af89679bfe1f7f45720511a793f42c00a7/pkg/sql/opt_exec_factory.go#L1850-L1850

**Comment by chengxiong-ruan** [comment]
TFTR! 🙏 
bors r+

**Pull request merged**
