### PR TITLE
sql: DRY the declaration of comparison operators

### PR DESCRIPTION
**Pull request by jordanlewis**
Also, sort them alphabetically within their sections.

### CODE REVIEW

**Comment by solongordon** [comment]
One quibble about whether your function needs to be quite so fancy. Otherwise :lgtm:! Significantly more legible.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/sem/tree/eval.go, line 1365 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20335#-L-8l0B5ZQsb6as4sg2g:-L-8l0B5ZQsb6as4sg2h:bo76zl8) ([raw file](https://github.com/cockroachdb/cockroach/blob/95fea20e45a15215bf6ac74a10e104790b2f31f6/pkg/sql/sem/tree/eval.go#L1365)):*
> ```Go
> 
> func makeCmpOpOverload(
> 	fn func(ctx *EvalContext, left, right Datum) (Datum, error), t ...types.T,
> ```

Minor: I'm not convinced making this function variadic is worth the complexity. `makeEqFn(types.Bool, types.Bool)` doesn't seem so offensive to me. Or you could just add another helper function for the single type case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20335#-:-L-8mSfC-48uQ0HippZF:b-dlkagk)*

**Comment by jordanlewis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/sem/tree/eval.go, line 1365 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20335#-L-8l0B5ZQsb6as4sg2g:-L-8nHzla8MqtTqAmo9h:b-cly3b2) ([raw file](https://github.com/cockroachdb/cockroach/blob/95fea20e45a15215bf6ac74a10e104790b2f31f6/pkg/sql/sem/tree/eval.go#L1365)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Minor: I'm not convinced making this function variadic is worth the complexity. `makeEqFn(types.Bool, types.Bool)` doesn't seem so offensive to me. Or you could just add another helper function for the single type case.
</blockquote></details>

Fair enough - I went slightly overboard. I took your first suggestion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20335)*

**Comment by jordanlewis** [comment]
TFTR!

**Comment by knz** [comment]
Many conciseness, much DRY. Wow, amaze. :dog: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20335#-:-L-CnwIfhQfgb_tjrVd3:b-p8a1qe)*

**Pull request merged**
