### PR TITLE
sql/parser: Move DatumToOid map to Oid() method on parser.Type

### PR DESCRIPTION
**Pull request by nvb**
This initial change removes a map from `parser.Type` to `oid.Oid` and
replaces it with a method on `parser.Type`. This allows us to avoid a
previous issue with reflection, and allows us to simplify some code that
was performing the same mapping in pgwire.

This is the first commit of #12641, but is a nice cleanup in isolation as well.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12642)

### CODE REVIEW

**Comment by knz** [comment]
:lgtm: modulo the two comments

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/type.go, line 410 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12642#-K_YsEcdwc6atqQ4GBXJ:-K_YsEcecsL4aS9ExrM1:bo4go9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/8531abb6f2c1b1f172bb34581b4a0b617ec22b80/pkg/sql/parser/type.go#L410)):*
> ```Go
> 	case TypeString:
> 		return oid.T__text
> 	case TypeAny:
> ```

See my comment about this in https://github.com/cockroachdb/cockroach/pull/12641#issuecomment-270083666

---

*[pkg/sql/parser/type.go, line 449 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12642#-K_YsGWzYeAIfwA6tDi_:-K_YsGWzYeAIfwA6tDia:b-x6otw8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8531abb6f2c1b1f172bb34581b4a0b617ec22b80/pkg/sql/parser/type.go#L449)):*
> ```Go
> // Oid implements the Type interface.
> func (TTable) Oid() oid.Oid {
> 	panic("TODO(knz) unknown Oid for TTable")
> ```

`T_anyelement` See my comment about this in https://github.com/cockroachdb/cockroach/pull/12641#issuecomment-270083666

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12642#-:-K_YsLhfu20henmUhL2E:b-qxxi6m)*

**Comment by jordanlewis** [comment]
Nice!

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/type.go, line 126 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12642#-K_ZpDW6pWdKaCB4-wZY:-K_ZpDW6pWdKaCB4-wZZ:by8ykng) ([raw file](https://github.com/cockroachdb/cockroach/blob/8531abb6f2c1b1f172bb34581b4a0b617ec22b80/pkg/sql/parser/type.go#L126)):*
> ```Go
> 	oid.T_text:        TypeString,
> 	oid.T__text:       TypeStringArray,
> 	oid.T__int2:       TypeIntArray,
> ```

Not sure if it matters but you're missing an entry for `oid.T_unknown` here. I see that it's not a unique mapping - perhaps that's an issue?

Also missing an entry for `T_record`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12642#-:-K_Zpl049NIJmonvYGvH:b-83sjoh)*

**Comment by nvanbenschoten** [comment]
TFTRs!

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/type.go, line 126 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12642#-K_ZpDW6pWdKaCB4-wZY:-Ka5zagiUBPfxl6J1TRb:b-jc9ig) ([raw file](https://github.com/cockroachdb/cockroach/blob/8531abb6f2c1b1f172bb34581b4a0b617ec22b80/pkg/sql/parser/type.go#L126)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Not sure if it matters but you're missing an entry for `oid.T_unknown` here. I see that it's not a unique mapping - perhaps that's an issue?

Also missing an entry for `T_record`.
</blockquote></details>

Yeah I'm not quite sure that it makes sense to add an entry for `oid.T_unknown`, based on how we use this mapping. For now, I'll leave it out and wait to see if it's ever needed.

Good catch on the `T_record`. Done.

---

*[pkg/sql/parser/type.go, line 410 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12642#-K_YsEcdwc6atqQ4GBXJ:-Ka6-djRejHUbxd822pq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8531abb6f2c1b1f172bb34581b4a0b617ec22b80/pkg/sql/parser/type.go#L410)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

See my comment about this in https://github.com/cockroachdb/cockroach/pull/12641#issuecomment-270083666
</blockquote></details>

Done.

---

*[pkg/sql/parser/type.go, line 449 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12642#-K_YsGWzYeAIfwA6tDi_:-Ka6-e81UX3xPvmK62oj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8531abb6f2c1b1f172bb34581b4a0b617ec22b80/pkg/sql/parser/type.go#L449)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`T_anyelement` See my comment about this in https://github.com/cockroachdb/cockroach/pull/12641#issuecomment-270083666
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12642#-:-Ka61jOROre_0aEQMuYG:bz5mair)*

**Comment by knz** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12642)*

**Pull request merged**
