### PR TITLE
sql: add unimplemented support for drop type

### PR DESCRIPTION
**Pull request by rohany**
This PR adds unimplemented support for the DROP TYPE command,
as well as adding some missing help/annotations for the CREATE
TYPE command.

Release note: None

### CODE REVIEW

**Comment by otan** [comment]
is it intentional that this has ENUM stuff in it?

**Comment by rohany** [comment]
Yeah i changed the order of one of the parse rules so the generated bnf files are a little different

**Review by otan — APPROVED** [review]

**Comment by rohany** [comment]
bors r=otan

**Comment by rohany** [comment]
bors r=otan

**Comment by rohany** [comment]
this is a flake #47546 

bors r=otan

**Pull request merged**
