### PR TITLE
[prototype] ui: replica matrix screen

### PR DESCRIPTION
**Pull request by vilterp**
See where your data lives: shows mapping between your tables and your nodes. Columns and rows with children are collapsible; cells in collapsed rows and columns show sums.

At `/#/replicamatrix`:

screen shot 2017-12-08 at 7 31 56 pm

(here we can see a zone config on database `test`, which has taken effect, putting all replicas in the US)

Future work:
- [ ] show partitions: expand table names to see partitions under them
- [ ] linking between zone configs & matrix:
  - mouse over node or locality: highlight applicable zone configs
  - mouse over schema object: highlight applicable zone configs
  - mouse over zone config: highlight applicable schema objects and nodes
  - highlight in red cells which are "in violation" of zone configs
- [ ] show leaseholder count in cells (=> see follow the workload)
- [ ] other stats than replica count: workload stats like # reads & writes. Not sure how to get this data, since we don't store read & write stats on this level in time series…
- [ ] heatmap: color-code cells on a scale. same info as the numbers in the cells, but quicker to get a gist
- [ ] (design): figure out where this lives in the UI, what it links to, how it should be styled, etc

Implementation notes:
- Added internal table `crdb_internal.replicas`
- Data is extracted by a SQL query which joins `crdb_internal.replicas` with `crdb_internal.ranges`. (The UI already has code for fetching nodes). See the SQL query in `admin.go`

### CODE REVIEW

**Comment by knz** [comment]
Good initiative. The end result is lovely and useful.

Just a nit about the design SQL-side.

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r4.
Review status: 2 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/crdb_internal.go, line 1333 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20500#-L-cGZyXzxTblNc0wPPB:-L-cGZyXzxTblNc0wPPC:by2az71) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1deb0c49fbabeda03e975f3a9ee501b9f50c4dd/pkg/sql/crdb_internal.go#L1333)):*
> ```Go
>   "table"      STRING NOT NULL,
>   "index"      STRING NOT NULL,
>   replicas     JSONB NOT NULL,
> ```

Using JSONB here doesn't make me happy. The data is structured, so there's no reason to use an unstructured data type.
Moreso if you're adding a separate `replicas` table, then you should just have replica_ids here and use a SQL join to get the rest of the data.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20500#-:-L-cGmWjJC8Zbl9nZOx7:b-ert2pr)*

**Comment by vilterp** [comment]
Glad you like it :)

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 3 of 4 files at r5, 7 of 7 files at r6, 4 of 4 files at r7, 3 of 3 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/crdb_internal.go, line 1333 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20500#-L-cGZyXzxTblNc0wPPB:-L-cHl57BYf046iscCnD:b-hgo8c3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1deb0c49fbabeda03e975f3a9ee501b9f50c4dd/pkg/sql/crdb_internal.go#L1333)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Using JSONB here doesn't make me happy. The data is structured, so there's no reason to use an unstructured data type.
Moreso if you're adding a separate `replicas` table, then you should just have replica_ids here and use a SQL join to get the rest of the data.


</blockquote></details>

Good point, this should be removed, and you can just join onto replicas to get what you want.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20500#-:-L-cHtWxUK4YDj8jxtW-:bqq6wq7)*

**Comment by couchand** [comment]
good work.  I want to fight over some of the component structure to make it simpler, but for the most part this is great.

---

Review status: 12 of 15 files reviewed at latest revision, 19 unresolved discussions, some commit checks failed.

---

*[pkg/ui/src/redux/cachedDataReducer.ts, line 140 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/20500#-L-hKk2nsvrhxXRK4hKb:-L-hKk2nsvrhxXRK4hKc:bb7dl0z) ([raw file](https://github.com/cockroachdb/cockroach/blob/a616af1f8bf16f4263ef7885a19694068d7be355/pkg/ui/src/redux/cachedDataReducer.ts#L140)):*
> ```XML
>   // errorData is the ERROR action creator.
>   errorData = (error: Error, request?: TRequest): PayloadAction<WithRequest<Error, TRequest>> => {
>     console.error(error);
> ```

beep

---

*[pkg/ui/src/util/api.ts, line 12 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/20500#-L-hL8ZapmEXNvcVB3Wz:-L-hL8ZapmEXNvcVB3X-:bpwpk9o) ([raw file](https://github.com/cockroachdb/cockroach/blob/a616af1f8bf16f4263ef7885a19694068d7be355/pkg/ui/src/util/api.ts#L12)):*
> ```XML
> import { FixLong } from "src/util/fixLong";
> import {cockroach} from "oss/src/js/protos";
> import ReplicaMatrixRequest = cockroach.server.serverpb.ReplicaMatrixRequest;
> ```

looks like these two lines are extraneous

---

*[pkg/ui/src/views/cluster/containers/replicaMatrix/index.tsx, line 36 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/20500#-L-hkgzDrVpMyD31xJa_:-L-hkgzE5FpUgNOty_fY:bb7dl0z) ([raw file](https://github.com/cockroachdb/cockroach/blob/a616af1f8bf16f4263ef7885a19694068d7be355/pkg/ui/src/views/cluster/containers/replicaMatrix/index.tsx#L36)):*
> ```XML
>   nodes.forEach((node) => {
>     const path = node.locality.tiers.map((tier) => `${tier.key}=${tier.value}`);
>     console.log('SAP', path);
> ```

beep

---

*[pkg/ui/src/views/cluster/containers/replicaMatrix/index.tsx, line 54 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/20500#-L-hlCz-4uXbWiGR5Xzp:-L-hlCz-4uXbWiGR5Xzq:bl0btfx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a616af1f8bf16f4263ef7885a19694068d7be355/pkg/ui/src/views/cluster/containers/replicaMatrix/index.tsx#L54)):*
> ```XML
>     this.props.replicaMatrix.cells.forEach((cell) => {
>       _.set(byDbByTableByNode, [cell.database_name, cell.table_name, cell.node_id], cell.count);
>     });
> ```

I'm a big fan of https://github.com/d3/d3-3.x-api-reference/blob/master/Arrays.md#d3_nest

---

*[pkg/ui/src/views/cluster/containers/replicaMatrix/index.tsx, line 71 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/20500#-L-hlywLiIlD5UsuLljo:-L-hlywLiIlD5UsuLljp:bb7qx3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/a616af1f8bf16f4263ef7885a19694068d7be355/pkg/ui/src/views/cluster/containers/replicaMatrix/index.tsx#L71)):*
> ```XML
>     };
> 
>     interface IReplicaMatrix { new(): Matrix<TableDesc, NodeDescriptor>; }
> ```

wat?

---

*[pkg/ui/src/views/cluster/containers/replicaMatrix/index.tsx, line 73 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/20500#-L-hM2hsMy3ZhBbhfD_L:-L-hM2hsMy3ZhBbhfD_M:b-4wi6io) ([raw file](https://github.com/cockroachdb/cockroach/blob/a616af1f8bf16f4263ef7885a19694068d7be355/pkg/ui/src/views/cluster/containers/replicaMatrix/index.tsx#L73)):*
> ```XML
>     interface IReplicaMatrix { new(): Matrix<TableDesc, NodeDescriptor>; }
>     // tslint:disable-next-line:variable-name
>     const ReplicaMatrix = Matrix as IReplicaMatrix;
> ```

this shadowing is super confusing

---

*[pkg/ui/src/views/cluster/containers/replicaMatrix/index.tsx, line 80 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/20500#-L-hmCn9tY0Wu34UeLp-:-L-hmCn9tY0Wu34UeLp0:b-qem7pa) ([raw file](https://github.com/cockroachdb/cockroach/blob/a616af1f8bf16f4263ef7885a19694068d7be355/pkg/ui/src/views/cluster/containers/replicaMatrix/index.tsx#L80)):*
> ```XML
>       }
> 
>       const val = byDbByTableByNode[tableDesc.dbName][tableDesc.tableName][nodeDesc.node_id.toString()];
> ```

maybe put the count on the TableDesc?

---

*[pkg/ui/src/views/cluster/containers/replicaMatrix/Matrix.tsx, line 16 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/20500#-L-hnVjTME4ZbL96CcXe:-L-hnVjTME4ZbL96CcXf:b165kn1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a616af1f8bf16f4263ef7885a19694068d7be355/pkg/ui/src/views/cluster/containers/replicaMatrix/Matrix.tsx#L16)):*
> ```XML
> 
> interface MatrixProps<R, C> {
>   label?: JSX.Element;
> ```

maybe `ReactNode`?

---

*[pkg/ui/src/views/cluster/containers/replicaMatrix/Matrix.tsx, line 20 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/20500#-L-hms0KiN_H6GrR2042:-L-hms0KiN_H6GrR2043:b7ikfq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a616af1f8bf16f4263ef7885a19694068d7be355/pkg/ui/src/views/cluster/containers/replicaMatrix/Matrix.tsx#L20)):*
> ```XML
>   rows: TreeNode<R>;
>   renderCell: (row: R, col: C) => JSX.Element | null;
>   rowLeafLabel?: ((row: R, path: TreePath) => string) | ((row: R) => string);
> ```

`path?`

---

*[pkg/ui/src/views/cluster/containers/replicaMatrix/Matrix.tsx, line 36 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/20500#-L-hnlGuY6Z2xYbwF2d3:-L-hnlGuY6Z2xYbwF2d4:bdvpphc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a616af1f8bf16f4263ef7885a19694068d7be355/pkg/ui/src/views/cluster/containers/replicaMatrix/Matrix.tsx#L36)):*
> ```XML
>   }
> 
>   _handleUnCollapseRow(path: TreePath) {
> ```

expand?

---

*[pkg/ui/src/views/cluster/containers/replicaMatrix/Matrix.tsx, line 57 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/20500#-L-hpGt5b2mo--tmsZsG:-L-hpGt5b2mo--tmsZsH:bv10vdh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a616af1f8bf16f4263ef7885a19694068d7be355/pkg/ui/src/views/cluster/containers/replicaMatrix/Matrix.tsx#L57)):*
> ```XML
>     const {
>       collapsedRows,
>     } = this.state;
> ```

y u no collapse col

---

*[pkg/ui/src/views/cluster/containers/replicaMatrix/Matrix.tsx, line 74 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/20500#-L-hp0xYh4JqO4ki_KYg:-L-ho3Zc2G_Ph_HOq_4w:be536op) ([raw file](https://github.com/cockroachdb/cockroach/blob/a616af1f8bf16f4263ef7885a19694068d7be355/pkg/ui/src/views/cluster/containers/replicaMatrix/Matrix.tsx#L74)):*
> ```XML
>       <table className="replica-matrix">
>         <thead>
>         {headerRows.slice(1).map((row, idx) => (
> ```

that slice is weird

---

*[pkg/ui/src/views/cluster/containers/replicaMatrix/Matrix.tsx, line 94 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/20500#-L-hp1W-e6mkYYzrF-aH:-L-hp1W-e6mkYYzrF-aI:b-hhzcol) ([raw file](https://github.com/cockroachdb/cockroach/blob/a616af1f8bf16f4263ef7885a19694068d7be355/pkg/ui/src/views/cluster/containers/replicaMatrix/Matrix.tsx#L94)):*
> ```XML
>         </thead>
>         <tbody>
>         {flattenedRows.filter((n) => n.depth > 0).map((row) => {
> ```

that filter is weird

---

*[pkg/ui/src/views/cluster/containers/replicaMatrix/Matrix.tsx, line 99 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/20500#-L-hpYbVop7hamH_NP2p:-L-hpYbWs1mu7-2z-PKE:b-yotxh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a616af1f8bf16f4263ef7885a19694068d7be355/pkg/ui/src/views/cluster/containers/replicaMatrix/Matrix.tsx#L99)):*
> ```XML
>           return (
>             <tr
>               key={JSON.stringify(row)}
> ```

i like the `.path.join("/")` above better

---

*[pkg/ui/src/views/cluster/containers/replicaMatrix/Matrix.tsx, line 109 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/20500#-L-hprwGmR0G6bJOJVQ8:-L-hprwGmR0G6bJOJVQ9:b2ni2xm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a616af1f8bf16f4263ef7885a19694068d7be355/pkg/ui/src/views/cluster/containers/replicaMatrix/Matrix.tsx#L109)):*
> ```XML
>               <th
>                 style={{
>                   paddingLeft: (row.depth - 1) * 30 + 5,
> ```

fun

---

*[pkg/ui/src/views/cluster/containers/replicaMatrix/Matrix.tsx, line 120 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/20500#-L-hq3CD1WSuKkcL1QkP:-L-hq3CD1WSuKkcL1QkQ:bw0ckvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a616af1f8bf16f4263ef7885a19694068d7be355/pkg/ui/src/views/cluster/containers/replicaMatrix/Matrix.tsx#L120)):*
> ```XML
>               {flattenedCols.map((col, idx) => {
>                 return (
>                   <td key={idx} style={{textAlign: "right"}}>
> ```

key={idx} makes dan abramov sad

---

*[pkg/ui/src/views/cluster/containers/replicaMatrix/tree.ts, line 27 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/20500#-L-hqTNKnWtTZ18SaqEC:-L-hqTNL4eH6ufHLJhRK:bbm1ejb) ([raw file](https://github.com/cockroachdb/cockroach/blob/a616af1f8bf16f4263ef7885a19694068d7be355/pkg/ui/src/views/cluster/containers/replicaMatrix/tree.ts#L27)):*
> ```XML
>     }
>     for (const child of node.children) {
>       recur(child, 0);
> ```

so depth isn't used?

---

*[pkg/ui/src/views/cluster/containers/replicaMatrix/tree.ts, line 103 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/20500#-L-hobegIKchd4ci75PT:-L-hobegIKchd4ci75PU:beizxh3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a616af1f8bf16f4263ef7885a19694068d7be355/pkg/ui/src/views/cluster/containers/replicaMatrix/tree.ts#L103)):*
> ```XML
>       path: pathToThis,
>     });
>     const isExpanded = _.filter(collapsedPaths, (p) => _.isEqual(p, pathToThis)).length === 0;
> ```

may as well stick this on there as another property, eh?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20500#-:-L-hr1DjUXbmYYKQ8JGp:b-on8cd9)*

**Comment by mrtracy** [comment]
Review status: 12 of 15 files reviewed at latest revision, 20 unresolved discussions, some commit checks failed.

---

*[pkg/ui/src/views/cluster/containers/replicaMatrix/Matrix.tsx, line 36 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/20500#-L-hnlGuY6Z2xYbwF2d3:-L-i2c9cfMJBnSCwS49A:b-evxlvq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a616af1f8bf16f4263ef7885a19694068d7be355/pkg/ui/src/views/cluster/containers/replicaMatrix/Matrix.tsx#L36)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

expand?
</blockquote></details>

Use active verbs "expandRow", "collapseRow".

Make them explicitly `private` instead of using the underscore.

Write them as bound functions:
```typescript
expandRow  = (path: TreePath) => {

}
```
Then you do not need to bind them in the render function.

Note that tslint might complain at you to re-order these methods within the class when you make them private.

---

*[pkg/ui/src/views/cluster/containers/replicaMatrix/Matrix.tsx, line 74 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/20500#-L-hp0xYh4JqO4ki_KYg:-L-i3Qx2DWXRZTPmsGbm:bwfp9bj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a616af1f8bf16f4263ef7885a19694068d7be355/pkg/ui/src/views/cluster/containers/replicaMatrix/Matrix.tsx#L74)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

that slice is weird
</blockquote></details>

Agreed, not clear why its doing this.  At least needs a comment.

---

*[pkg/ui/src/views/cluster/containers/replicaMatrix/tree.ts, line 27 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/20500#-L-hqTNKnWtTZ18SaqEC:-L-i4P7I7qM52F7wTrfm:bafwwjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a616af1f8bf16f4263ef7885a19694068d7be355/pkg/ui/src/views/cluster/containers/replicaMatrix/tree.ts#L27)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

so depth isn't used?
</blockquote></details>

Either remove it or use it (and set maxDepth to some sanity-check number like 1M). I lean towards removing it, i'm not sure off the top of my head if this is the best way to guard against a cyclic tree.

---

*[pkg/ui/src/views/cluster/containers/replicaMatrix/tree.ts, line 41 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/20500#-L-i5hufBaOluU06cMzV:-L-i5hufBaOluU06cMzW:b2k3fdu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a616af1f8bf16f4263ef7885a19694068d7be355/pkg/ui/src/views/cluster/containers/replicaMatrix/tree.ts#L41)):*
> ```XML
> }
> 
> export function layoutTree<T>(tree: TreeNode<T>): LayoutNode<T>[][] {
> ```

Need some comments on these functions, it was not clear what the goal of this function is (specifically, I don't know *how* its trying to lay out the resulting data structure, so it's difficult to evaluate whether it's working.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20500)*

**Comment by vilterp** [comment]
TFTRs… Sry, forgot to push a couple commits until just now. They make the columns collapsable, as in the screenshot. The review comments still apply.

**Comment by vilterp** [comment]
TODO: surface lat/longs on locality hierarchy (maybe in the next PR)

**Comment by vilterp** [comment]
Split into:
- backend: https://github.com/cockroachdb/cockroach/pull/22344
- frontend: https://github.com/vilterp/cockroach/pull/2

**Pull request closed without merging**
