### PR TITLE
*: liberate descriptor structs from sqlbase

### PR DESCRIPTION
**Pull request by jordanlewis**
This is a large, mostly mechanical refactor that moves several central
sql structs out of the monolithic sqlbase package.

Highlights:

- descriptor structs moved into a new `catpb` package.
- sql error constructors moved into a new `sqlerrors` package
- `sqlbase.ID` became `descid.T`
- privilege protos moved to a new `privilegepb` package
- virtual table ids moved to a new `virtualid` package
- some index encoding methods moved to a new `idxencoding` package

The proximal cause for this change is to begin the code movement that
will eventually permit the optimizer to be able to look at column types
more directly, and to untangle the dependency web that caused the
optimizer to be unable to look at the descriptor structs directly due to
all of the things that `sqlbase` needs to pull in.

Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
First of all, thanks for doing all this tedious work.

I've been thinking about the factoring, and find I'm not yet sold on the `catpb`, `privilegepb`, etc. naming. It doesn't feel like Go to be naming packages based on how they were generated, rather than naming them based on their semantic purpose. I get that you want to make sure we don't add cruft into these packages, which is a good goal, but I'm not sure it's worth polluting the name. I'd rather use linting or some other mechanism to ensure that these packages have a minimal number of dependencies.

One thing that has pushed me more in this direction is the thinking I've been doing on how we might unify the type system. My best ideas all center around having a single `types` package that includes both the `ColumnType` protobuf and the `types.T` interface (and we get rid of `coltypes.T`). In other words, I'm seeing this larger pattern of creating packages centered around a few protobuf-generated files, plus support interfaces, methods, and tests. As another example, do we really want separate `privilege` and `privilegepb` packages? I can't think of a reason why that's desirable. In fact, I think it will be a pain to have them separate, since developers will get confused as to which privilege-related interfaces/structs/enums live in which package.

From the optimizer's point of view, the important thing is that each package does just one thing, and has minimal dependencies on other CRDB packages. There's no requirement that they contain only protobufs.

**Comment by RaduBerinde** [comment]
A heads up that @knz is also adding a `sqlerrors` package in his PR.

**Comment by jordanlewis** [comment]
Thanks for the comments. Regarding `catpb`, I was "doing as the Romans do" - all of our protobuf packages are named with a `pb` prefix. I'm happy to change it if anyone has a better suggestion, but for now it seems appropriate.

Separate `privilege` was a mistake that I'll correct if this idea is deemed a good one.

The work about the type system seems separate from this. The idea of this PR is to incrementally untangle the dependencies of the `sqlbase` package, not necessarily to make a final product. Any PR that tries to do work with the type system will need to contend with the dependency issue here - it's not simple - so I view this as a step forward.

@RaduBerinde, thanks for the heads up.

If either of you wouldn't mind, could you say directly whether you think a change like this is a good idea? It will rot very quickly, so I'd like to either push hard on merging it or abandon it.

**Comment by danhhz** [comment]
I'm certainly in favor of untangling dependencies. If this is an incremental step, do we have a written description somewhere of what the goalpost is/where we'd like to end up? I'd love to see something like that before evaluating the concrete changes in this PR

**Comment by jordanlewis** [comment]
I haven't written a description. Concretely, the current problem is that the optimizer cannot depend on sqlbase to pull in the columntype protobufs. This PR literally tried to do the minimal thing necessary to extract those protobufs into a new package. It was very difficult!

**Comment by danhhz** [comment]
Sure, I understand that and applaud and appreciate the effort (and prototype). My concern is that this PR introduces a lot of new packages that people will have to learn and renames some very common sql types, which is quite disruptive, and it's not clear to me if they'll be sticking around in that form long enough for that disruption to be worth it. If we all agreed on what the end goal was, then it would be easier to talk about the best path to that point.

**Comment by jordanlewis** [comment]
Sorry, by me saying it was very difficult it wasn't trying to garner appreciation - I was trying to say that the resultant giant PR was necessary in my estimation to get to the goal of moving out the protos.

I see what you're saying regarding trying to nail down what the final picture will look like. Unfortunately, I don't know and I haven't thought about it. Perhaps that's a reason to postpone this, but to be honest, I think it'll be pretty hard to envision a final picture with the state of things as they are right now!

**Comment by knz** [comment]
I'm OK reviewing this however I'd like to serialize the two reviews, between this PR and #36598 (i.e. I want the first one to merge and the other one rebased before I review the second). Please advise which of the two should be reviewed/merged first.

**Comment by jordanlewis** [comment]
Forget this PR, I'd still like to do it but I'll just redo the work later after the type system change goes in.

**Pull request closed without merging**
