### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by tamird**
@mjibson for dump changes (why is there so much conversion between `string` and `[]byte`?)
@tschottdorf for opentracing

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7776)

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM on `opentracing-go`.

**Comment by mjibson** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[cli/dump.go, line 196 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7776#-KMV8ODuOu8vGwsoWbGq:-KMV8ODuOu8vGwsoWbGr:153885343) ([raw file](https://github.com/cockroachdb/cockroach/blob/96e46b9c7e5fadca5ab8ae005afefadf15247209/cli/dump.go#L196)):*
> ```Go
> 						ivals[si] = fmt.Sprintf("%s", t)
> 					default:
> 						// STRING and BYTES types can have optional length suffixes, so only examine
> ```

I don't think removing this logic is safe because in the future other types may be added that use `[]byte` as their underlying storage, but are not of the `DBytes` type, and thus shouldn't use the byte escape.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7776)*

**Comment by tamird** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[cli/dump.go, line 196 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7776#-KMV8ODuOu8vGwsoWbGq:-KMVD5QHG8xxeqvW9ZK8:851369245) ([raw file](https://github.com/cockroachdb/cockroach/blob/96e46b9c7e5fadca5ab8ae005afefadf15247209/cli/dump.go#L196)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> I don't think removing this logic is safe because in the future other types may be added that use `[]byte` as their underlying storage, but are not of the `DBytes` type, and thus shouldn't use the byte escape.
</details>
Sure, reverted.

---

*[cli/dump_test.go, line 268 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7776#-KMVDADpP9xPlpdSI6yA:-KMVDADpP9xPlpdSI6yB:-1171565524) ([raw file](https://github.com/cockroachdb/cockroach/blob/04ded542896caf678f769cca62de2159039d6202/cli/dump_test.go#L268)):*
> ```Go
> 						fetchedVal = t.UTC()
> 					case string:
> 						if _, ok := generatedVal.([]byte); ok {
> ```

@mjibson PTAL, removed the shady stuff here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7776)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cli/dump_test.go, line 268 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7776#-KMVDADpP9xPlpdSI6yA:-KMVKFVbXJo7oT1TDHvZ:-1577145142) ([raw file](https://github.com/cockroachdb/cockroach/blob/04ded542896caf678f769cca62de2159039d6202/cli/dump_test.go#L268)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> @mjibson PTAL, removed the shady stuff here
</details>
This block LGTM.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7776#-:-KMVKd207DRoVLHNNlx2:1417088721)*

**Pull request merged**
