### PR TITLE
sql: add support for partial statistics to the parser

### PR DESCRIPTION
**Pull request by faizaanmadhani**
See commit messages for details.

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
This is nice :100: 

> Reviewed 7 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90068#-:-NFIweWW-Hp3lFObnJ-v:b2pyiyv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @faizaanmadhani, @mgartner, and @rytaft)

___
*[`pkg/sql/parser/sql.y` line 873 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90068#-NFIvhTH4EqgmMddalH9:-NFIvhTH4EqgmMddalHA:b-9r6crf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e48835deafbf6187c03c634b0163aeaf60869c/pkg/sql/parser/sql.y#L873)):*
> ```Yacc
> %token <str> EXPERIMENTAL_FINGERPRINTS EXPERIMENTAL_REPLICA
> %token <str> EXPERIMENTAL_AUDIT EXPERIMENTAL_RELOCATE
> %token <str> EXPIRATION EXPLAIN EXPORT EXTENSION EXTERNAL EXTRACT EXTRACT_DURATION EXTREMES
> ```

nit: you're not using EXTREMES in the first commit of this PR. So you may want to move its definition to the 2nd commit.
___
*[`pkg/sql/parser/sql.y` line 4736 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90068#-NFIwNplAOTdR63jZxWv:-NFIwNplAOTdR63jZxWw:bh3kax7) ([raw file](https://github.com/cockroachdb/cockroach/blob/bac479578c6c0df3ad4adec2537fe4f9560df6f4/pkg/sql/parser/sql.y#L4736)):*
> ```Yacc
>   {
>     $$.val = &tree.CreateStatsOptions{
> 			Where: tree.NewWhere(tree.AstWhere, $1.expr()),
> ```

nit: use spaces not tabs
___
*[`pkg/sql/sem/tree/create.go` line 2084 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90068#-NFIw6V9BUyLzVm_3QkI:-NFIw6V9BUyLzVm_3QkJ:b8u8vtw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e48835deafbf6187c03c634b0163aeaf60869c/pkg/sql/sem/tree/create.go#L2084)):*
> ```Go
> // Format implements the NodeFormatter interface.
> func (o *CreateStatsOptions) Format(ctx *FmtCtx) {
> 	sep := " "
> ```

Can I recommend that you pretty-print using the WITH OPTIONS prefix, so that the "canonical" form as reported in various places includes the keywords. That will make it more readable overall.

(General principle: "be flexible on input, be strict on output")
___
*[`pkg/sql/sem/tree/create.go` line 2074 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90068#-NFIwQ9_6N9momZvJsxC:-NFIwQ9_6N9momZvJsxD:b-llhk1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/bac479578c6c0df3ad4adec2537fe4f9560df6f4/pkg/sql/sem/tree/create.go#L2074)):*
> ```Go
> 
> 	// WHERE will specify statistics collection in a set of rows of the table
> 	// or index specified
> ```

nit: missing period at end of sentence.

**Review by faizaanmadhani — COMMENTED** [review]
Hey @knz, thanks for the review! I've addressed your comments. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90068#-:-NFJdTA21IhyrTFeHBQT:b4vxaz7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @mgartner, and @rytaft)

___
*[`pkg/sql/sem/tree/create.go` line 2084 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90068#-NFIw6V9BUyLzVm_3QkI:-NFJcqiBDrhwEbl7U83o:b-31c653) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e48835deafbf6187c03c634b0163aeaf60869c/pkg/sql/sem/tree/create.go#L2084)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Can I recommend that you pretty-print using the WITH OPTIONS prefix, so that the "canonical" form as reported in various places includes the keywords. That will make it more readable overall.

(General principle: "be flexible on input, be strict on output")
</blockquote></details>

Done. I added the pretty printing of the `WITH OPTIONS` prefix, and the change can be seen in the parser tests in `create_misc`. Now, `WITH OPTIONS` will always be printed before the list of stats options in the output from the parser, whether or not the user specified them in the input.

**Review by rytaft — COMMENTED** [review]
This is great! I just have a few nits below. I'd also request that you clean up the separation between the two commits, since it seems like you only applied the latest changes to the second commit.

When you are making changes to specific commits, it's best to apply those changes back to the relevant original commit. You can do that by:
1. Make the change, then commit using `git commit --fixup <original commit sha>`
2. Squash the fixup commit with the original using `git rebase -i --autosquash <ref point>`

This is important for a few reasons. First, if you don't do this, any reviewers that are reviewing your PR after you make changes won't see the new updates right away if they review each commit separately, and might waste time making the same comments that the earlier reviewers already made. Second, it should be possible to build/test each commit independently for the purposes of running `git bisect` later on. Finally, anyone going back and looking at the commits later should be able to directly map the commit message to the changes in the code.

> Reviewed 3 of 7 files at r1, 4 of 4 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90068#-:-NFJexUFEmE4yc0Nso3j:b-d22awn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @faizaanmadhani, @knz, and @mgartner)

___
*[`pkg/sql/parser/sql.y` line 4712 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90068#-NFJeGl_-1W4hWgmne-F:-NFJeGl_-1W4hWgmne-G:bxf5wv3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d7e399d2f651465e98e85a8eac90b322cba1bbe/pkg/sql/parser/sql.y#L4712)):*
> ```Yacc
>   {
>    /* SKIP DOC */
>        value, _ := constant.Float64Val($2.numVal().AsConstantValue())
> ```

nit: remove these whitespace changes
___
*[`pkg/sql/sem/tree/create.go` line 2069 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90068#-NFJeXCp6SFqvGG8d43V:-NFJeXCp6SFqvGG8d43W:b-29n79w) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d7e399d2f651465e98e85a8eac90b322cba1bbe/pkg/sql/sem/tree/create.go#L2069)):*
> ```Go
> 	AsOf AsOfClause
> 
> 	// AT EXTREMES specifies the statistics collection to be at the
> ```

nit: AT EXTREMES -> USING EXTREMES
___
*[`pkg/sql/sem/tree/create.go` line 2074 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90068#-NFJjARcDn2bazObdwSH:-NFJjARcDn2bazObdwSI:b-ilkbrm) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d7e399d2f651465e98e85a8eac90b322cba1bbe/pkg/sql/sem/tree/create.go#L2074)):*
> ```Go
> 
> 	// WHERE will specify the statistics collection in a range
> 	Where *Where
> ```

nit: these changes should probably be in the second commit, not the first

**Review by mgartner — COMMENTED** [review]
Very nice!

> Reviewed 3 of 7 files at r1, 4 of 4 files at r3, 4 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90068#-:-NFJrekO9rSg-p-DOj9l:b-j7qk9t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @faizaanmadhani and @knz)

___
*[`pkg/sql/sem/tree/create.go` line 2133 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/90068#-NFJrHeV2aSYkO3d8CVa:-NFJrHeV2aSYkO3d8CVb:bnot4u2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a8036627166c34af36d17d99f1601b336b74d27/pkg/sql/sem/tree/create.go#L2133)):*
> ```Go
> 		o.AsOf = other.AsOf
> 	}
> 	if other.UsingExtremes {
> ```

nit: IMO it reads nicer to have throttling and AOST at the end like:

```
CREATE STATISTICS ... WHERE a > 100 AS OF SYSTEM TIME now() - '1 hr';
CREATE STATISTICS ... WHERE a > 100 THROTTLING 0.5;
```
___
*[`pkg/sql/sem/tree/create.go` line 2140 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/90068#-NFJqmMHESMQZq0R8qc-:-NFJqmMHESMQZq0R8qc0:b3hwkx3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a8036627166c34af36d17d99f1601b336b74d27/pkg/sql/sem/tree/create.go#L2140)):*
> ```Go
> 	}
> 	if other.Where != nil {
> 		if other.Where != nil {
> ```

nit: remove duplicate `if other.Where != nil {`
___
*[`pkg/sql/opt/optbuilder/testdata/misc_statements` line 192 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90068#-NFJq2r61lHnikqHY6Zd:-NFJq2r61lHnikqHY6Ze:b-rlr7e5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b1c8da55be48c174b7b370b305f42622546209f/pkg/sql/opt/optbuilder/testdata/misc_statements#L192)):*
> ```
> ----
> create-statistics
>  └── CREATE STATISTICS "" FROM ab WITH OPTIONS AS OF SYSTEM TIME '-0.001ms'
> ```

I don't think this change belongs in this commit, does it?
___
*[`pkg/sql/parser/testdata/create_misc` line 79 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90068#-NFJq9CE9UXKo4qZQ8p_:-NFJq9CE9UXKo4qZQ8pa:b3f29nn) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b1c8da55be48c174b7b370b305f42622546209f/pkg/sql/parser/testdata/create_misc#L79)):*
> ```
> CREATE STATISTICS a ON col1 FROM t WITH OPTIONS THROTTLING 0.9
> ----
> CREATE STATISTICS a ON col1 FROM t WITH OPTIONS THROTTLING 0.9
> ```

nit:  I think these should be undone in this commit.

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 6 files at r6, 3 of 5 files at r7, 2 of 4 files at r8, 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90068#-:-NFK5VdLD1TvVq4G6wwl:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @faizaanmadhani and @knz)

**Review by faizaanmadhani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90068)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz, @mgartner, and @rytaft)

___
*[`pkg/sql/sem/tree/create.go` line 2069 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90068#-NFJeXCp6SFqvGG8d43V:-NFK2bwb8LSrl_zg2Fpu:bc6klgb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d7e399d2f651465e98e85a8eac90b322cba1bbe/pkg/sql/sem/tree/create.go#L2069)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: AT EXTREMES -> USING EXTREMES
</blockquote></details>

Moved to second commit, and first word of comment renamed to `UsingExtremes`
___
*[`pkg/sql/opt/optbuilder/testdata/misc_statements` line 192 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90068#-NFJq2r61lHnikqHY6Zd:-NFK4eQA-zITRyclvrNW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b1c8da55be48c174b7b370b305f42622546209f/pkg/sql/opt/optbuilder/testdata/misc_statements#L192)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I don't think this change belongs in this commit, does it?
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r8, 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90068#-:-NFK8hDW4AhGPWCdKfa2:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @knz and @mgartner)

**Comment by faizaanmadhani** [comment]
TFTRs!!! 🎉 

bors r=mgartner,rytaft

**Pull request merged**
