### PR TITLE
sql: include stmt into distsql_flows virtual tables

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit plumbs the information about the statement that corresponds
to a DistSQL remote flow so that it could be added to the
`distsql_flows` virtual tables. This information is populated on a best
effort basis (it'll be set for the user-issued queries that are not
BulkIO/CDC related). The reasoning behind not propagating some
information in all cases is so that this commit could be backportable.
Since it only changes the virtual table schema, no migrations nor
version checks are needed.

Release note (sql change): New column `stmt` has been added to
`crdb_internal.(cluster|node)_distsql_flows` virtual table. It is
populated on a best effort basis.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73522)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @yuzefovich)

___
*[pkg/server/serverpb/status.proto, line 919 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73522#-MqGsaqK34bVs7ax2S12:-MqGsaqK34bVs7ax2S13:b-20tc6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/a472682a6adcb7db439ad8988d3914b39224b7dc/pkg/server/serverpb/status.proto#L919)):*
> ```protobuf
>     Status status = 3;
> 
>     // Stmt is the statement the physical plan for which this flow is part of.
> ```

[nit] the SQL statement for which this flow is executing.
___
*[pkg/sql/distsql_running.go, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73522#-MqGrzaz-VGaYLSf7nVc:-MqGrzaz-VGaYLSf7nVd:btaqw3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a472682a6adcb7db439ad8988d3914b39224b7dc/pkg/sql/distsql_running.go#L289)):*
> ```Go
> 		TraceKV:           evalCtx.Tracing.KVTracingEnabled(),
> 		CollectStats:      collectStats,
> 		Stmt:              stmt,
> ```

I'd strongly consider setting a hard length limit here. The statement could be huge for all we know.
___
*[pkg/sql/execinfrapb/api.proto, line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73522#-MqGrnRABBeCDwNuDePn:-MqGrnRABBeCDwNuDePo:b-i2hri4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a472682a6adcb7db439ad8988d3914b39224b7dc/pkg/sql/execinfrapb/api.proto#L53)):*
> ```protobuf
>   // observed, since the resulting stats are added as structured data to a
>   // trace.
>   optional bool CollectStats = 9 [(gogoproto.nullable) = false];
> ```

[nit] these fields should not be capitalized (they should be `trace_kv` (with customname=TraceKV), `collect_stats` etc
___
*[pkg/sql/execinfrapb/api.proto, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73522#-MqGrjFe686Fup89GD35:-MqGrjFe686Fup89GD36:b-poceh4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a472682a6adcb7db439ad8988d3914b39224b7dc/pkg/sql/execinfrapb/api.proto#L57)):*
> ```protobuf
>   // Stmt is the statement the physical plan for which this flow is part of. It
>   // is populated on a best effort basis.
>   optional string Stmt = 10 [(gogoproto.nullable) = false];
> ```

[nit] statement_sql
___
*[pkg/sql/execinfrapb/data.proto, line 335 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73522#-MqGrQx12z37_07BzlK0:-MqGrQx12z37_07BzlK1:b-rvpkjy) ([raw file](https://github.com/cockroachdb/cockroach/blob/a472682a6adcb7db439ad8988d3914b39224b7dc/pkg/sql/execinfrapb/data.proto#L335)):*
> ```protobuf
> // DistSQLRemoteFlowInfo contains some information about a single DistSQL remote
> // flow.
> message DistSQLRemoteFlowInfo {
> ```

Does this need to be a proto? (would we ever send it over the wire?)
___
*[pkg/sql/flowinfra/flow.go, line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73522#-MqGraSL0OAcB22XO-Wv:-MqGraSL0OAcB22XO-Ww:b-o8ucgd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a472682a6adcb7db439ad8988d3914b39224b7dc/pkg/sql/flowinfra/flow.go#L116)):*
> ```Go
> 	IsVectorized() bool
> 
> 	// Stmt is the statement the physical plan for which this flow is part of.
> ```

[nit] `Stmt` is very generic. Maybe `StatementSQL`?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73522)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @RaduBerinde)

___
*[pkg/sql/distsql_running.go, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73522#-MqGrzaz-VGaYLSf7nVc:-MqGwFgGCCbe-Q-_SQOg:b-g6kr8l) ([raw file](https://github.com/cockroachdb/cockroach/blob/a472682a6adcb7db439ad8988d3914b39224b7dc/pkg/sql/distsql_running.go#L289)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I'd strongly consider setting a hard length limit here. The statement could be huge for all we know.
</blockquote></details>

That's a good point. Added 500 character limit.
___
*[pkg/sql/execinfrapb/data.proto, line 335 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73522#-MqGrQx12z37_07BzlK0:-MqGuItEAv_tK76Wqkbr:b-j2eyww) ([raw file](https://github.com/cockroachdb/cockroach/blob/a472682a6adcb7db439ad8988d3914b39224b7dc/pkg/sql/execinfrapb/data.proto#L335)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Does this need to be a proto? (would we ever send it over the wire?)
</blockquote></details>

Good point - no, it won't be sent, refactored.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73522#-:-MqGzOmkBPTYXQhvD7xl:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @yuzefovich)

___
*[pkg/sql/execinfrapb/api.proto, line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73522#-MqGzBJWCfxl-UiaoUIJ:-MqGzBJWCfxl-UiaoUIK:bcq6uc2) ([raw file](https://github.com/cockroachdb/cockroach/blob/77e7e74318988425111fc7d526d610ac34d8ee1a/pkg/sql/execinfrapb/api.proto#L45)):*
> ```protobuf
>   optional FlowSpec flow = 3 [(gogoproto.nullable) = false];
> 
>   optional EvalContext evalContext = 6 [(gogoproto.nullable) = false];
> ```

[nit] eval_context

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73522#-:-MqHQb_oBwgqXqhtlrZO:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @mgartner)

**Pull request merged**
