### PR TITLE
cli: Add hot-ranges.sh to debug.zip

### PR DESCRIPTION
**Pull request by bobvawter**
This change adds a helper script to summarize the hottest ranges in a cluster.
Example output follows:

```
./nodes/5/ranges/184.json:    "queries_per_second": 834.9839788735895,
./nodes/1/ranges/108538.json:    "writes_per_second": 808.8465367945909
./nodes/8/ranges/108538.json:    "writes_per_second": 799.2414339808118
./nodes/6/ranges/108538.json:    "writes_per_second": 791.5053333333333
./nodes/6/ranges/99346.json:    "queries_per_second": 783.0177951986692,
```

Release justification: No impact to CRDB itself, improves post-facto debugging.

Release note (cli change): A debug.zip file now includes a script,
hot-ranges.sh, which will summarize the hottest ranges in the cluster.

### CODE REVIEW

**Review by knz — APPROVED** [review]

**Review by tbg — APPROVED** [review]
Thank you!

**Comment by bobvawter** [comment]
bors r-

(Test skew, will rebase)

**Pull request merged**
