### PR TITLE
storage: wire up pebble key validation func

### PR DESCRIPTION
**Pull request by nicktrav**
To guard against invalid keys being written to the storage engine, make
use of the experimental `KeyValidationFunc` Pebble option. The
validation func checks that the key can be decoded as an `EngineKey` in
addition to also being a valid `MVCCKey` (i.e. the engine key version
has a valid version length).

See cockroachdb/pebble#1202.

Release note: None

### CODE REVIEW

**Comment by nicktrav** [comment]
Open to thoughts / advice on how to best test this.

It's slightly complicated in that a "bad key" will cause the engine to panic when a compaction is triggered, and this happens on a separate Goroutine.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Open to thoughts / advice on how to best test this.
> It's slightly complicated in that a "bad key" will cause the engine to panic when a compaction is triggered, and this happens on a separate Goroutine.

I'm at a loss on how to test this. It is the same issue as the pebble change in that we don't have an ability to corrupt the in-memory state of a versionEdit, without adding some sort of testing hook (maybe we should).
@jbowens @itsbilal for any ideas

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69176#-:-MhYgvcj2HqPasBM5uj1:b-myatv6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @nicktrav)

___
*[pkg/storage/pebble.go, line 371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69176#-MhYfaba4ahOSYbCBCD3:-MhYfaba4ahOSYbCBCD4:b-pjh94m) ([raw file](https://github.com/cockroachdb/cockroach/blob/5121c177daa1f89e2ccc9b0a75fed578b765d8ca/pkg/storage/pebble.go#L371)):*
> ```Go
> 
> 		// Validate that the version length matches one of the expected values.
> 		if !engineKey.IsMVCCKey() {
> ```

it's not necessarily a `MVCCKey`. The issue is that `DecodeEngineKey` does not validate that the versions are valid for either kind of `EngineKey`, i.e., `MVCCKey` or `LockTableKey`. I don't think we should necessarily change `DecodeEngineKey` since it is used in various performance sensitive paths. Let's add a separate `EngineKey.Validate` function that confirms that the key is one of MVCCKey or LockTableKey and exercises ToMVCCKey and ToLockTableKey.

**Review by jbowens — COMMENTED** [review]
> It's slightly complicated in that a "bad key" will cause the engine to panic when a compaction is triggered, and this happens on a separate Goroutine.

If the panic goes through the logger, you could replace the logger with one with a non-panicking `Fatalf` implementation: https://github.com/jbowens/pebble/blob/6a415c9fc875b73b500eec938c44eefd2133e3fb/filenames_test.go#L93-L106

Not sure about corrupting the in-memory state though. Seems trickier

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69176#-:-Mh_AgSbCu3W9MT6BBhO:b-b84opy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nicktrav)

**Review by nicktrav — COMMENTED** [review]
This was super useful, thanks! I'm going to push another change that adds a test using this pattern.

> Not sure about corrupting the in-memory state though. Seems trickier

Yeah, I might punt on this for now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69176#-:-Mhp5ZUHBdBuaFLh3AuJ:b1m4vb0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/storage/pebble.go, line 371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69176#-MhYfaba4ahOSYbCBCD3:-Mhp5GZh1utNNtZeoT1N:b-cuzofh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a55c0317a632d1f46642de35658e15de187805a6/pkg/storage/pebble.go#L371)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

it's not necessarily a `MVCCKey`. The issue is that `DecodeEngineKey` does not validate that the versions are valid for either kind of `EngineKey`, i.e., `MVCCKey` or `LockTableKey`. I don't think we should necessarily change `DecodeEngineKey` since it is used in various performance sensitive paths. Let's add a separate `EngineKey.Validate` function that confirms that the key is one of MVCCKey or LockTableKey and exercises ToMVCCKey and ToLockTableKey.
</blockquote></details>

Pushed a new change that addresses this, picking up the change I added in #69211.

**Review by nicktrav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69176)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/storage/pebble.go, line 371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69176#-MhYfaba4ahOSYbCBCD3:-Mhp5w681X2-UzjDampT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a55c0317a632d1f46642de35658e15de187805a6/pkg/storage/pebble.go#L371)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Pushed a new change that addresses this, picking up the change I added in #69211.
</blockquote></details>

Done.

**Review by nicktrav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69176)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/storage/pebble.go, line 598 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69176#-MhpGoaAApLt7SbVtoDd:-MhpGoaAApLt7SbVtoDe:b2kc7rc) ([raw file](https://github.com/cockroachdb/cockroach/blob/25ecf55985ad84f56d17cc36cde3c62616615f01/pkg/storage/pebble.go#L598)):*
> ```Go
> 	logCtx = logtags.AddTag(logCtx, "s", storeIDContainer)
> 
> 	if cfg.Opts.Logger == nil {
> ```

This felt a little smelly (there's another use of a logger a few lines below, when setting up the `EventListener`). The problem this solves is allowing tests to specify their own custom logger, and not have it overridden when constructing a new `Pebble` instance.

**Review by nicktrav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69176)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/69176#-Mhsz8Yr2dDIjkhSXMM_:-Mhsz8Yr2dDIjkhSXMMa:bod6sgg) (no related file):*
While I was able to add some test coverage for this change, I wanted to check if there was a better way of structuring the test to avoid both the flush and the compaction - in the real-world, the flush would result in a panic, which would prevent the second from occurring. Maybe this isn't too big an issue.

```
I210823 23:06:21.968582 6 storage/open.go:60  [-] 1  engine creation is randomly setting disableSeparatedIntents: false
I210823 23:06:21.969179 6 3@vendor/github.com/cockroachdb/pebble/event.go:593  [pebble,s?] 2  [JOB 1] MANIFEST created 000001
I210823 23:06:21.969720 6 3@vendor/github.com/cockroachdb/pebble/event.go:617  [pebble,s?] 3  [JOB 1] WAL created 000002
I210823 23:06:21.969890 8 3@vendor/github.com/cockroachdb/pebble/event.go:613  [pebble,s?] 4  [JOB 2] all initial table stats loaded
I210823 23:06:21.970028 6 3@vendor/github.com/cockroachdb/pebble/event.go:617  [pebble,s?] 5  [JOB 3] WAL created 000004
I210823 23:06:21.970147 10 3@vendor/github.com/cockroachdb/pebble/event.go:585  [pebble,s?] 6  [JOB 4] flushing 1 memtable to L0
I210823 23:06:21.970208 10 3@vendor/github.com/cockroachdb/pebble/event.go:601  [pebble,s?] 7  [JOB 4] flushing: sstable created 000005
    pebble_test.go:749: pebble: version edit validation failed: key="foo"/00; file=000005:foo\x00\x00\x02#1,1-foo\x00\x00\x02#1,1: key "foo"/00 is not a valid EngineKey
I210823 23:06:21.970470 10 3@vendor/github.com/cockroachdb/pebble/event.go:589  [pebble,s?] 8  [JOB 4] flushed 1 memtable to L0 [000005] (1015 B), in 0.0s, output rate 3.6 M/s
I210823 23:06:21.970563 11 3@vendor/github.com/cockroachdb/pebble/event.go:573  [pebble,s?] 9  [JOB 5] compacting(move) L0 [000005] (1015 B) + L6 [] (0 B)
    pebble_test.go:749: pebble: version edit validation failed: key="foo"/00; file=000005:foo\x00\x00\x02#1,1-foo\x00\x00\x02#1,1: key "foo"/00 is not a valid EngineKey
I210823 23:06:21.970706 11 3@vendor/github.com/cockroachdb/pebble/event.go:577  [pebble,s?] 10  [JOB 5] compacted(move) L0 [000005] (1015 B) + L6 [] (0 B) -> L6 [000005] (1015 B), in 0.0s, output rate 11 M/s
```

---

**Review by jbowens — APPROVED** [review]
:LGTM:

> Reviewed 1 of 2 files at r1, 3 of 4 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69176#-:-MhuH4t-8MnEXtC7J95y:b-24bekv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal, @nicktrav, and @sumeerbhola)

___
*[pkg/storage/in_mem.go, line 52 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69176#-MhuFq4l-x7p4PmNrUHJ:-MhuFq4l-x7p4PmNrUHK:b-goztzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a301f2d473982ad28a9a7ebf56955657f15bd300/pkg/storage/in_mem.go#L52)):*
> ```Go
> 	pebbleOpts = append(pebbleOpts, opts...)
> 
> 	eng, err := Open(context.Background(), InMemory(), pebbleOpts...)
> ```

nit: you could keep the options inline by using `CombineOptions`:

```
eng, err := Open(context.Background(), InMemory(), ForTesting, MaxSize(1<<20), CombineOptions(opts...))
```

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69176#-:-MhuXIs94m859nWkXuYY:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @itsbilal, @nicktrav, and @sumeerbhola)

___
*[pkg/storage/pebble.go, line 369 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69176#-MhuWS2L6qX4OjSJ1Osq:-MhuWS2M0t4Lo7KcSqqS:bwrb62x) ([raw file](https://github.com/cockroachdb/cockroach/blob/a301f2d473982ad28a9a7ebf56955657f15bd300/pkg/storage/pebble.go#L369)):*
> ```Go
> 		}
> 		if err := engineKey.Validate(); err != nil {
> 			return errors.Newf("key %s is not a valid EngineKey", engineKey)
> ```

should this be `errors.Wrapf` so that we use the error returned?

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69176)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @itsbilal, @nicktrav, and @sumeerbhola)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/69176#-Mhsz8Yr2dDIjkhSXMM_:-MhuXg0d-KQxoGcCk0iW:bgfeh2b) (no related file):*
>  I wanted to check if there was a better way of structuring the test to avoid both the flush and the compaction - in the real-world, the flush would result in a panic, which would prevent the second from occurring

This is fine. The DB should be free to do what it wants if the Fatalf that it helpfully raised was ignored.

---

**Review by nicktrav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69176)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @itsbilal, @jbowens, and @sumeerbhola)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/69176#-Mhsz8Yr2dDIjkhSXMM_:-MhuZYmqAQ0iZTzz4IG-:b-qn5lay) (no related file):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

>  I wanted to check if there was a better way of structuring the test to avoid both the flush and the compaction - in the real-world, the flush would result in a panic, which would prevent the second from occurring

This is fine. The DB should be free to do what it wants if the Fatalf that it helpfully raised was ignored.
</blockquote></details>

Perfect.

---
___
*[pkg/storage/in_mem.go, line 52 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69176#-MhuFq4l-x7p4PmNrUHJ:-MhuZ9EtElUvU2tKSGQz:b-vlluv3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a301f2d473982ad28a9a7ebf56955657f15bd300/pkg/storage/in_mem.go#L52)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

nit: you could keep the options inline by using `CombineOptions`:

```
eng, err := Open(context.Background(), InMemory(), ForTesting, MaxSize(1<<20), CombineOptions(opts...))
</blockquote></details>

Nice. Fixed!
___
*[pkg/storage/pebble.go, line 369 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69176#-MhuWS2L6qX4OjSJ1Osq:-MhuZE875Itk_4kDckmr:bfo5pxw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a301f2d473982ad28a9a7ebf56955657f15bd300/pkg/storage/pebble.go#L369)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

should this be `errors.Wrapf` so that we use the error returned?
</blockquote></details>

I altered this to just return the underlying error.


<!-- Sent from Reviewable.io -->

**Pull request merged**
