### PR TITLE
roachtest: automatically profile rebalance load roachtests

### PR DESCRIPTION
**Pull request by kvoli**
When there is a mismatch between allocation signals (QPS/replica CPU) and hardware signals the `rebalance/by-load/*` tests assert on, it is difficult to root cause why.

Enable automatic CPU profiling (2s) once CPU exceeds 90% utilization.

Informs: #111900
Release note: None

### CODE REVIEW

**Comment by kvoli** [comment]
Failures appear unrelated, I'll rebase tomorrow.

**Review by andrewbaptist — APPROVED** [review]
:lgtm:

One question is whether you should set `server.cpu_profile.interval` lower also to something like 30s from the default of 5m. Without setting that if there is an "early trigger" for high CPI, you might miss the important profile we'd want to get. I'm not sure what the impact of taking a profile is, so maybe we don't want to do that.

**Review by kvoli — COMMENTED** [review]
Nice idea, I updated to add this in at 2 minutes. In the previous [failures](https://teamcity.cockroachdb.com/repository/download/Cockroach_Nightlies_RoachtestNightlyGceBazel/12074343:id/rebalance/by-load/leases/run_1/artifacts.zip!/test.log), the CPU distribution stays constant after the 1-3 minute mark and the test times out after 10 minutes. For a previous failure, we should expect approx. 3-4 profiles captured during the test run with a 2 minute interval.

Rebased on master.

TYFTR

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112232#-:-NgeQogo7pRlq18J5qzr:b8u0egs)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DarrylWong and @herkolategan)

**Comment by kvoli** [comment]
bors r=andrewbaptist

**Comment by kvoli** [comment]
blathers backport release-23.2

**Comment by kvoli** [comment]
blathers backport release-23.1

**Comment by kvoli** [comment]
blathers backport release-22.2

**Pull request merged**
