### PR TITLE
demo: fix --global option

### PR DESCRIPTION
**Pull request by jordanlewis**
The --global option broke somewhere during the 20.2 cycle. This patch
revives it. --global simulates geo-latencies between nodes. Best used
with `--global --geo-partitioned-replicas`.

Release note (cli change): fix cockroach demo --global from crashing
with "didn't get expected magic bytes header".

### CODE REVIEW

**Comment by jordanlewis** [comment]
Still no tests for this, sorry.

**Review by nvb — COMMENTED** [review]
Nice! Now that we handle the `ArtificialLatencyMap` knob in `grpcDialOptions`, do we still need to also handle the knob in `grpcDialRaw`? Seems like the latter calls the former.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58466#-:-MQJZm8C2Jjlp6SfZ_ne:b-9agp1g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @nvanbenschoten)

**Comment by otan** [comment]
Tests?!

Rename https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/interactive_tests/test_demo_global.tcl.disabled to `test_demo_global.tcl` and run `expect -f pkg/cli/interactive_tests/test_demo_global.tcl ./cockroach`!

**Review by ajstorm — COMMENTED** [review]
I'm with Nathan - Nice!  

Any chance you could add this to your PR?  I wasn't able to test with the `--global` flag when I  built `add node`, and realized in testing your change that the error message doesn't print out correctly.

```diff --git a/pkg/cli/sql.go b/pkg/cli/sql.go
index bebc3b0abf..27785de1b7 100644
--- a/pkg/cli/sql.go
+++ b/pkg/cli/sql.go
@@ -562,7 +562,7 @@ func (c *cliState) handleDemoAddNode(cmd []string, nextState, errState cliStateE
     }
 
     if demoCtx.simulateLatency {
-        fmt.Printf("add command is not supported in --global configurations")
+        fmt.Printf("add command is not supported in --global configurations\n")
         return nextState
     }```
```


> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58466#-:-MQS6dmB25GrUfja3VRm:bhg4qf9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm)

**Review by otan — APPROVED** [review]
image

bors r+

**Comment by otan** [comment]
that's a flake

bors r+

**Pull request merged**
