### PR TITLE
opgen: ensure GC jobs for temp indexes have proper description

### LINKED ISSUE #82169: sql/schemachanger: proper job description for GC Job dropping temporary index
**Is your feature request related to a problem? Please describe.**

Right now it just has the sad string `"GC for"`. This comes indirectly from not populating the below field. We probably need a bit more sophistication to get it right. 

https://github.com/cockroachdb/cockroach/blob/1b01f419a22b974522e3c8e651009b29c30dbbc9/pkg/sql/schemachanger/scop/mutation.go#L131

The solution here is to ensure that we only create a single GC job. The current thinking is to model the GC job explicitly. 

Jira issue: CRDB-16234

### PR DESCRIPTION
**Pull request by postamar**
Fixes #82169.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
Do we want to say something about the index ID or temporary indexes or something to differentiate the jobs?

> Reviewed 1 of 143 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89189#-:-NDTJTjYB9KIE7fKiWrp:b84lvgx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by postamar** [comment]
I don't really have an opinion, I can if you want. What are the user's expectations here? I expect that they don't care about index IDs, but they conceivably might care about index type.

**Review by ajwerner — APPROVED** [review]
:lgtm: this works for this release 

> Reviewed 15 of 155 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89189#-:-NDTVpEt1moAOaDSrnjP:b-2szzwt)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by postamar** [comment]
Thanks for the review!

bors r+

**Pull request merged**
