### PR TITLE
backupccl: support restoring views with into_db

### PR DESCRIPTION
**Pull request by dt**
The `RESTORE ... into_db = 'foo'` option allows overriding the
destination database for all restored tables, views and sequences.

Previously this option could not be used when restoring views, as the
view query string could contain references to tables qualified with
their original database name(s), and we did not support rewriting that
query to reflect the overridden destination for those tables.

This change adds that rewriting (except for tables/sequences named in
strings, see #24556).

Since a destination override is applied to all tables being restored,
and since restoring a view requires restoring all tables it references,
any table refernced by the view query -- regardless of its prior
qualification -- can be re-qualified with the override DB.

Release note (enterprise change): support restoring views when using the 'into_db' option.

### CODE REVIEW

**Comment by dt** [comment]
There's a slight backwards compat issue here: if you resume this job on a 2.0 node, it'll ignore the new proto field and then restore the non-rewritten view query. However I think that this is still better than the current state where you can't restore at all, since at least with a broken view, you are able to get the view query via `information_schema`, edit it and create the correct view yourself.

**Comment by knz** [comment]
Thanks for the preliminary PR.

1) I am not too fond of `WITH into_db`. SQL already has a perfectly workable syntax pattern for this using the INTO keyword (INSERT INTO, SELECT INTO) and I think it would make sense to reuse that here.

2) The logic for renaming the db name in the view queries is partially incorrect, see my comments below.

3) The logic for handling dependencies is flawed because of orthogonal issue #24556. Please add a TODO in the new function to refer to that issue and explain why the replacement scheme is incomplete.

4) The commit message is super incomplete. This should provide, in that order:

4.1) a reminder of the problem at the beginning, including an example SQL syntax that showcases what you are talking about. It's far from obvious what "into_db" is.
4.2) a reminder of why the current code fails to address the problem.
4.3) an overview of the solution.
4.4) an argument which explains why the solution is sufficient, by explicitly listing:
   - the set of all constructs in CockroachDB that create dependencies between objects (tip: not only views)
   - where and how each of the possible dependencies are addressed, prior to this patch and in this patch, to make the problem go away
4.5) references to unresolved questions, for example a link to #24556.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[pkg/ccl/backupccl/restore.go, line 172 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24555#-L9QprgP8QUUND9jVK0T:-L9QprgP8QUUND9jVK0U:blxp9fu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6991789be3ccc15e6cc011ab5d3f473bbda0745/pkg/ccl/backupccl/restore.go#L172)):*
> ```Go
> 				return
> 			}
> 			tn.CatalogName = tree.Name(newDB)
> ```

You need to conditionalize this replacement. A view defined as e.g. `SELECT * FROM "".information_schema.tables` (catalog name = empty string) would become incorrect if you were to change this empty string.

Also before you do that I'd ask you to extend the comment above this function and also the commit message to discuss what happens with views (and possibly other objects) that span multiple databases.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24555#-:-L9QqG271s8FuL-vgi_M:b-sb6tw0)*

**Comment by dt** [comment]
Thanks for the review!
1) is not applicable -- this isn't adding or changing syntax, just fixing the handling of views in the existing syntax.
2) Done.
3) Done.
4) Done.

---

Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/ccl/backupccl/restore.go, line 172 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24555#-L9QprgP8QUUND9jVK0T:-L9QwypT1WRSv4QwMXV1:b78514m) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6991789be3ccc15e6cc011ab5d3f473bbda0745/pkg/ccl/backupccl/restore.go#L172)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

You need to conditionalize this replacement. A view defined as e.g. `SELECT * FROM "".information_schema.tables` (catalog name = empty string) would become incorrect if you were to change this empty string.

Also before you do that I'd ask you to extend the comment above this function and also the commit message to discuss what happens with views (and possibly other objects) that span multiple databases.
</blockquote></details>

Done.

I think the comment on the function itself, by saying it replaces *all* db qualifiers with `newDB`, is already saying about as much as it can about what it specifically does to cross-database references -- it points them at `newDB`. Ramifications beyond that are dependent on where it is called, so I added a longer comment at the call-site about what's going on in the case of `into_db`. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24555#-:-L9R2mdh46PnhpwGoYzg:bm4um20)*

**Comment by knz** [comment]
:lgtm: thanks!

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24555#-:-L9R8YKE5VcWZpTbqRqE:brfqlux)*

**Pull request merged**
