### PR TITLE
rfcs: add an RFC for enum types

### PR DESCRIPTION
**Pull request by rohany**
Release note: None

### CODE REVIEW

**Comment by rohany** [comment]
I wanted to open a draft PR for the RFC before opening it up to the rest of the team. The topics here are based on our discussions yesterday and today. Let me know if more stuff needs detailed / examples

**Review by jordanlewis — COMMENTED** [review]
Nice going!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46866#-:-M3skjex7yP8BZ8XRqeI:b-4zxdq3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jordanlewis, @lucy-zhang, and @rohany)

___
*[docs/RFCS/20200331_enums.md, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46866#-M3sRyFI6rheBVlIs1dJ:-M3sRyFI6rheBVlIs1dK:b-jg7hw0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4113bc947585490fa8c058764e59a1c1c94f90e4/docs/RFCS/20200331_enums.md#L5)):*
> ```Markdown
> - Start Date: 2020-03-31
> - Authors: Rohan Yadav, Lucy Zhang, Andrew Werner, Jordan Lewis
> - RFC PR: #TODO (rohany): Fill this out.
> ```

magic: it's now 46866!
___
*[docs/RFCS/20200331_enums.md, line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46866#-M3sS5pl3gKLU4hKbF6M:-M3sS5pm8jGJJ_fikLh1:bbmtx1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/4113bc947585490fa8c058764e59a1c1c94f90e4/docs/RFCS/20200331_enums.md#L6)):*
> ```Markdown
> - Authors: Rohan Yadav, Lucy Zhang, Andrew Werner, Jordan Lewis
> - RFC PR: #TODO (rohany): Fill this out.
> - Cockroach Issue: #TODO (rohany): Fill this out.
> ```

#24873
___
*[docs/RFCS/20200331_enums.md, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46866#-M3sSCNt0CZe8vvFDk_s:-M3sSCNt0CZe8vvFDk_t:bq5g038) ([raw file](https://github.com/cockroachdb/cockroach/blob/4113bc947585490fa8c058764e59a1c1c94f90e4/docs/RFCS/20200331_enums.md#L26)):*
> ```Markdown
> CREATE TYPE day ENUM AS ('monday', 'tuesday', 'wednesday'...);
> CREATE TABLE events (id INT, dayofweek day);
> INSERT INTO events VALUES (1, 'monday')
> ```

super nit: you need a ; at the end of this line to make it look like the other lines.
___
*[docs/RFCS/20200331_enums.md, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46866#-M3sUmOE7OQw4ByXAg_8:-M3sUmOE7OQw4ByXAg_9:bf7918b) ([raw file](https://github.com/cockroachdb/cockroach/blob/4113bc947585490fa8c058764e59a1c1c94f90e4/docs/RFCS/20200331_enums.md#L49)):*
> ```Markdown
> We propose storing the metadata about an enum in a new descriptor called 
> an `EnumDescriptor`. This descriptor will be added to the descriptor union
> along side Table and Database descriptors and will reuse the same leasing
> ```

just as a note of warning, i believe that adding to that union is irritating in practice, because there are a lot of users of it? I believe this is why we didn't make a ViewDescriptor, and instead piggybacked off  TableDescriptor. But, I don't know. I think making a new descriptor type is more than likely the right choice...

Also, Database descriptors are not properly leased right now, so we'll need to work with the schema team on making this a thing.
___
*[docs/RFCS/20200331_enums.md, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46866#-M3sfbmn7zMP6H7W87xP:-M3sfbmoD_fC4kIsLWbH:b-2fmfjk) ([raw file](https://github.com/cockroachdb/cockroach/blob/4113bc947585490fa8c058764e59a1c1c94f90e4/docs/RFCS/20200331_enums.md#L67)):*
> ```Markdown
> and invalidate entries when the lease is invalidated. 
> 
> Enums are scoped within a database, and are created within a schema.
> ```

aren't they also scoped by schema?
___
*[docs/RFCS/20200331_enums.md, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46866#-M3sgLOyAok8kbRpFipJ:-M3sgLOyAok8kbRpFipK:b-n56f1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4113bc947585490fa8c058764e59a1c1c94f90e4/docs/RFCS/20200331_enums.md#L83)):*
> ```Markdown
> There are a few ways that enums can change over time.
> * The name can change.
> * The resident schema can change.
> ```

What do you mean by changing the resident schema?
___
*[docs/RFCS/20200331_enums.md, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46866#-M3si2fk5SeyWePDPCWc:-M3si2fk5SeyWePDPCWd:b-yb2t82) ([raw file](https://github.com/cockroachdb/cockroach/blob/4113bc947585490fa8c058764e59a1c1c94f90e4/docs/RFCS/20200331_enums.md#L95)):*
> ```Markdown
> just add the new enum value to the enum metadata, it is possible that another node 
> reads a newly written enum from disk and is unsure how to decode it. (TODO rohany: maybe 
> write down an explicit example of how this could happen?).
> ```

Hmm, can't we do this with a WaitForOneVersion? Oh, I guess you're saying that:

1. Node 1 adds a new enum element 'foo' to the enum descriptor, and calls WaitForOneVersion, blocking.
2. Node 2 receives the enum descriptor update, and begins accepting writes of 'foo'
3. Node 3 reads a write of 'foo' before it got its enum descriptor update, which leads to unknown-ness.

Yeah... true, I think.
___
*[docs/RFCS/20200331_enums.md, line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46866#-M3sixAM-9seTzhHqcIe:-M3sixAM-9seTzhHqcIf:b-iios8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/4113bc947585490fa8c058764e59a1c1c94f90e4/docs/RFCS/20200331_enums.md#L199)):*
> ```Markdown
> of this approach is that adding a new enum to the beginning or end of the set requires only
> an increment/decrement of an integer rather than creating a new and possibly longer byte array.
> A drawback of this strategy is that more space is used in the case where there are not many enum
> ```

I don't understand this strategy, and it seems more complicated than the byte array strategy. Integers are themselves just byte arrays, right? Not sure I follow this.
___
*[docs/RFCS/20200331_enums.md, line 209 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46866#-M3sjHEg6Ps1aJVyJ7XH:-M3sjHEg6Ps1aJVyJ7XI:btd0dqo) ([raw file](https://github.com/cockroachdb/cockroach/blob/4113bc947585490fa8c058764e59a1c1c94f90e4/docs/RFCS/20200331_enums.md#L209)):*
> ```Markdown
> onto the ID of the enum that it represents as well as the physical layout 
> discussed above. Operations on two `DEnum` datums will succeed only if the
> two `DEnum`s have the same enum ID.
> ```

by "enum ID" here I guess we mean the byte array?
___
*[docs/RFCS/20200331_enums.md, line 216 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46866#-M3sjZ5YCfIIZGt98dn0:-M3sjZ5YCfIIZGt98dn1:bvur6ki) ([raw file](https://github.com/cockroachdb/cockroach/blob/4113bc947585490fa8c058764e59a1c1c94f90e4/docs/RFCS/20200331_enums.md#L216)):*
> ```Markdown
> a column being of an enum type. Additionally, it will need to be taught how
> to convert enum values from their input string representation into their
> `Datum` physical representation.
> ```

This involves the leasing system - probably should mention that.
___
*[docs/RFCS/20200331_enums.md, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46866#-M3sje1Z03MWFP-kNwbq:-M3sje1Z03MWFP-kNwbr:bpttjod) ([raw file](https://github.com/cockroachdb/cockroach/blob/4113bc947585490fa8c058764e59a1c1c94f90e4/docs/RFCS/20200331_enums.md#L225)):*
> ```Markdown
> joining or rendering the enums, a join would be produced against this
> reference table. This allows for easy changing of enum data, but
> results in a variety of complexity during planning.
> ```

Planning sure, but the worse part IMO is the execution latency!

Also, the ordering and enum ID stuff have to be the same, right? So we'd have to have the byte array bisection stuff no matter what. Maybe you just mean avoiding the EnumDescriptor stuff?
___
*[pkg/sql/sem/tree/enum.go, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46866#-M3sjylz32FHFLjfEumh:-M3sjylz32FHFLjfEumi:b-gsf6z5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4113bc947585490fa8c058764e59a1c1c94f90e4/pkg/sql/sem/tree/enum.go#L16)):*
> ```Go
> 
> const minByte byte = 0
> const maxByte byte = 4
> ```

Why not just use 0x00 and 0xff here to make it real?

**Review by ajwerner — COMMENTED** [review]
:tada: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46866#-:-M3vCPjd6KdOhTCsep1S:bjwa7hh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jordanlewis, @lucy-zhang, and @rohany)

___
*[docs/RFCS/20200331_enums.md, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46866#-M3sUmOE7OQw4ByXAg_8:-M3suiH35pphp9OwBRCi:bxjplet) ([raw file](https://github.com/cockroachdb/cockroach/blob/4113bc947585490fa8c058764e59a1c1c94f90e4/docs/RFCS/20200331_enums.md#L49)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

just as a note of warning, i believe that adding to that union is irritating in practice, because there are a lot of users of it? I believe this is why we didn't make a ViewDescriptor, and instead piggybacked off  TableDescriptor. But, I don't know. I think making a new descriptor type is more than likely the right choice...

Also, Database descriptors are not properly leased right now, so we'll need to work with the schema team on making this a thing.
</blockquote></details>

Indeed. We'll work through the details of whether we're going to lift the required leasing fields up into some parent of `Descriptor` or whether we'll rename `TableDescriptor` into something like `ObjectDescriptor`.

Let's leave this as an open question for the time being. 
___
*[docs/RFCS/20200331_enums.md, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46866#-M3sfbmn7zMP6H7W87xP:-M3t3oyY712X9NcIZfil:b-59gel5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4113bc947585490fa8c058764e59a1c1c94f90e4/docs/RFCS/20200331_enums.md#L67)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

aren't they also scoped by schema?
</blockquote></details>

Yes to name a schema you need to name the schema if the enum is in a different schema than the table using it. More correctly, the schema in which the type resides will need to be in the `search_path` of the connection creating the table which uses the enum. 

This raises an interesting point:

Today we allow things like fk relations across databases. It is illegal in postgres to refer to a table in a different database. Should it be legal to refer to an enum in a different database? 

Should we kick off the conversation about the long deprecation cycle we're sure to face to disallow `<database>.<name>` and cross-db relations?
___
*[docs/RFCS/20200331_enums.md, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46866#-M3sgLOyAok8kbRpFipJ:-M3vBfFSEqNzX_y-w_s1:b-5ci4od) ([raw file](https://github.com/cockroachdb/cockroach/blob/4113bc947585490fa8c058764e59a1c1c94f90e4/docs/RFCS/20200331_enums.md#L83)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

What do you mean by changing the resident schema?
</blockquote></details>

`ALTER TYPE name SET SCHEMA new_schema`
___
*[docs/RFCS/20200331_enums.md, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46866#-M3si2fk5SeyWePDPCWc:-M3vAfxHBMY5hxZgk_Qj:btqqu5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/4113bc947585490fa8c058764e59a1c1c94f90e4/docs/RFCS/20200331_enums.md#L95)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Hmm, can't we do this with a WaitForOneVersion? Oh, I guess you're saying that:

1. Node 1 adds a new enum element 'foo' to the enum descriptor, and calls WaitForOneVersion, blocking.
2. Node 2 receives the enum descriptor update, and begins accepting writes of 'foo'
3. Node 3 reads a write of 'foo' before it got its enum descriptor update, which leads to unknown-ness.

Yeah... true, I think.
</blockquote></details>

Correct.
___
*[docs/RFCS/20200331_enums.md, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46866#-M3vAthx2ZKd1fBlXZj_:-M3vAthx2ZKd1fBlXZja:b-lvnsqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/4113bc947585490fa8c058764e59a1c1c94f90e4/docs/RFCS/20200331_enums.md#L97)):*
> ```Markdown
> write down an explicit example of how this could happen?).
> 
> In order to avoid these situations, we propose to apply a similar strategy
> ```

nit: rather than saying a similar strategy, I'd make the language here say that it's an extension of online schema changes. 
___
*[docs/RFCS/20200331_enums.md, line 216 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46866#-M3sjZ5YCfIIZGt98dn0:-M3vAJvJ7mb3RJ3BAJet:bwxuhf4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4113bc947585490fa8c058764e59a1c1c94f90e4/docs/RFCS/20200331_enums.md#L216)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This involves the leasing system - probably should mention that.
</blockquote></details>

For now the plan is to first add the enums to the `opt/cat` with an incoherent cache and then pop it out for leased enums. 
___
*[docs/RFCS/20200331_enums.md, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46866#-M3sje1Z03MWFP-kNwbq:-M3t4Vp-57OzepEVR3pk:bkqnljs) ([raw file](https://github.com/cockroachdb/cockroach/blob/4113bc947585490fa8c058764e59a1c1c94f90e4/docs/RFCS/20200331_enums.md#L225)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Planning sure, but the worse part IMO is the execution latency!

Also, the ordering and enum ID stuff have to be the same, right? So we'd have to have the byte array bisection stuff no matter what. Maybe you just mean avoiding the EnumDescriptor stuff?
</blockquote></details>

You don't necessarily need to do the same fancy bisection stuff. It's probably reasonable to rewrite the collation value if it's just an `O(values)` write rather than `O(rows)` using the enum

It's also worth noting that you couldn't ever have ordered ranged scans over multiple enum values.

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46866)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @lucy-zhang)

___
*[docs/RFCS/20200331_enums.md, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46866#-M3sRyFI6rheBVlIs1dJ:-M3vMs-C213T4gzTxQXL:bp956mz) ([raw file](https://github.com/cockroachdb/cockroach/blob/4113bc947585490fa8c058764e59a1c1c94f90e4/docs/RFCS/20200331_enums.md#L5)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

magic: it's now 46866!
</blockquote></details>

I have to open a real PR (not a draft one) before I can fill this out.
___
*[docs/RFCS/20200331_enums.md, line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46866#-M3sS5pl3gKLU4hKbF6M:-M3vN4xVBMqWKvCqbkQD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4113bc947585490fa8c058764e59a1c1c94f90e4/docs/RFCS/20200331_enums.md#L6)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

#24873
</blockquote></details>

Done.
___
*[docs/RFCS/20200331_enums.md, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46866#-M3sSCNt0CZe8vvFDk_s:-M3vN7oi8cQRF8HDtbHv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4113bc947585490fa8c058764e59a1c1c94f90e4/docs/RFCS/20200331_enums.md#L26)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

super nit: you need a ; at the end of this line to make it look like the other lines.
</blockquote></details>

Done.
___
*[docs/RFCS/20200331_enums.md, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46866#-M3sfbmn7zMP6H7W87xP:-M3vNGzt-DzO9Z74ZxA6:b-87pi9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/4113bc947585490fa8c058764e59a1c1c94f90e4/docs/RFCS/20200331_enums.md#L67)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Yes to name a schema you need to name the schema if the enum is in a different schema than the table using it. More correctly, the schema in which the type resides will need to be in the `search_path` of the connection creating the table which uses the enum. 

This raises an interesting point:

Today we allow things like fk relations across databases. It is illegal in postgres to refer to a table in a different database. Should it be legal to refer to an enum in a different database? 

Should we kick off the conversation about the long deprecation cycle we're sure to face to disallow `<database>.<name>` and cross-db relations?
</blockquote></details>

From playing around in psql you just cant access enums from other databases, only from schemas in the same database.
___
*[docs/RFCS/20200331_enums.md, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46866#-M3sgLOyAok8kbRpFipJ:-M3vNt6gAJEtMLMCblWZ:bx0he7n) ([raw file](https://github.com/cockroachdb/cockroach/blob/4113bc947585490fa8c058764e59a1c1c94f90e4/docs/RFCS/20200331_enums.md#L83)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

`ALTER TYPE name SET SCHEMA new_schema`
</blockquote></details>

I can word this better though
___
*[docs/RFCS/20200331_enums.md, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46866#-M3si2fk5SeyWePDPCWc:-M3vOW2zCr6SC6MBl7WR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4113bc947585490fa8c058764e59a1c1c94f90e4/docs/RFCS/20200331_enums.md#L95)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Correct.
</blockquote></details>

Done.
___
*[docs/RFCS/20200331_enums.md, line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46866#-M3sixAM-9seTzhHqcIe:-M3vPHzO55W1lrk_UqI_:b-g552so) ([raw file](https://github.com/cockroachdb/cockroach/blob/4113bc947585490fa8c058764e59a1c1c94f90e4/docs/RFCS/20200331_enums.md#L199)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I don't understand this strategy, and it seems more complicated than the byte array strategy. Integers are themselves just byte arrays, right? Not sure I follow this.
</blockquote></details>

I'm trying to say that we use a tuple to hold the enum -- a tuple of an integer and a byte array. That way operations on the beginning and end of the enum value list just increment and decrement integers, rather than add more bytes. Adding at the beginning and the end is the worst case for this bisect the space kind of algorithm.
___
*[docs/RFCS/20200331_enums.md, line 209 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46866#-M3sjHEg6Ps1aJVyJ7XH:-M3vPz1gDwXNhRIdHSD1:b-bzr0c0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4113bc947585490fa8c058764e59a1c1c94f90e4/docs/RFCS/20200331_enums.md#L209)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

by "enum ID" here I guess we mean the byte array?
</blockquote></details>

no, its the ID of the enum type that they are part of.
___
*[docs/RFCS/20200331_enums.md, line 216 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46866#-M3sjZ5YCfIIZGt98dn0:-M3vQEOg3xzgirH6fzAL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4113bc947585490fa8c058764e59a1c1c94f90e4/docs/RFCS/20200331_enums.md#L216)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

For now the plan is to first add the enums to the `opt/cat` with an incoherent cache and then pop it out for leased enums. 
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/enum.go, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46866#-M3sjylz32FHFLjfEumh:-M3vQOQY4Nshl9C-ygxO:b-uzb6c0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4113bc947585490fa8c058764e59a1c1c94f90e4/pkg/sql/sem/tree/enum.go#L16)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Why not just use 0x00 and 0xff here to make it real?
</blockquote></details>

They were the values I was using in my notebook to test :) I'll update this with some larger tests before opening the real PR.

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46866)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @lucy-zhang)

___
*[docs/RFCS/20200331_enums.md, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46866#-M3sje1Z03MWFP-kNwbq:-M3vpZkMEhP8It55d2UM:b-f02ks0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4113bc947585490fa8c058764e59a1c1c94f90e4/docs/RFCS/20200331_enums.md#L225)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

You don't necessarily need to do the same fancy bisection stuff. It's probably reasonable to rewrite the collation value if it's just an `O(values)` write rather than `O(rows)` using the enum

It's also worth noting that you couldn't ever have ordered ranged scans over multiple enum values. 
</blockquote></details>

enum ID != ordering. The enum ID is the id of the enum type itself, not its members.

**Comment by rohany** [comment]
Going to close this and open a real PR now.

**Pull request closed without merging**
