### PR TITLE
sql: add precision support for TIMESTAMP/TIMESTAMPTZ

### LINKED ISSUE #32098: sql: support optional TIMESTAMP precision
**Is your feature request related to a problem? Please describe.**

`CREATE TABLE t(x TIMESTAMP(6))` should work

See: https://www.postgresql.org/docs/11/static/datatype-datetime.html#DATATYPE-TIMEZONES

> time, timestamp, and interval accept an optional precision value p which specifies the number of fractional digits retained in the seconds field. By default, there is no explicit bound on precision. The allowed range of p is from 0 to 6.

**Describe the solution you'd like**

MVP: An optional precision of 6 should be recognized and ignored (this is the default in CockroachDB)

Optionally: support for other precisions than 6.

**Workaround**

If the desired precision is 6, then the precision can be omitted altogether to obtain equivalent behavior.

### PR DESCRIPTION
**Pull request by otan**
Resolves #32098.

Add precision support for TIMESTAMP/TIMESTAMPTZ, supporting precisions
from 0 to 6 inclusive.

When storing types, we use the value `0` to mean `DEFAULT` (which will
be a precision of 6). A precision of `0` will be stored as `-1`. This
allows backwards compatibility with older versions of
TIMESTAMP/TIMESTAMPTZ, which had a precision of 0 when persisted.
This detail is abstracted away in the Make* and Precision() functions.

Note this change is not backwards compatible for those who have set
`TIMESTAMP(0)/TIMESTAMPTZ(0)`, as this is stored as `-1`. If someone
does this in v20.1, it does not cover them well in case of a downgrade back
to v19.2.

Release note (sql change): Introduces precision support for TIMESTAMP
and TIMESTAMPTZ, supporting precisions from 0 to 6 inclusive. Previous
versions of TIMESTAMP and TIMESTAMPTZ will default to 6 units of
precision.

### CODE REVIEW

**Review by rohany — CHANGES_REQUESTED** [review]
A few comments, but I'd also like @solongordon to take a look at this PR just in case.

> Reviewed 11 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42552#-:-Lu3IwX0-1EdghZhAAEY:bbpj0w1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rohany)

___
*[pkg/sql/sem/tree/time.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42552#-Lu3FCo2B7eKi-ZPz8cz:-Lu3FCo2B7eKi-ZPz8d-:b9o1ziu) ([raw file](https://github.com/cockroachdb/cockroach/blob/da55069b9da144ce9d9893e9848fe99e9f0df9de/pkg/sql/sem/tree/time.go#L23)):*
> ```Go
> // duration to use to pass into time.Truncate to truncate to that duration.
> // Panics if the precision is not supported.
> func precisionToTruncDuration(precision int32) time.Duration {
> ```

i feel like this should be a method on the DTimeStamp and DTimeStampTZ so that its clear this is only meant to be used on timestamps. or maybe just change the name so its clear for use on the time precisions only.
___
*[pkg/sql/sem/tree/time.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42552#-Lu3FNh9BWDBh4qd2I0S:-Lu3FNh9BWDBh4qd2I0T:b-spj6x5) ([raw file](https://github.com/cockroachdb/cockroach/blob/da55069b9da144ce9d9893e9848fe99e9f0df9de/pkg/sql/sem/tree/time.go#L26)):*
> ```Go
> 	switch precision {
> 	case types.DefaultTimePrecision:
> 		return time.Microsecond
> ```

maybe make this a constant too, time.DefaultPrecision or something
___
*[pkg/sql/sem/tree/time.go, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42552#-Lu3FUFNDFQ79AfVEOkR:-Lu3FUFNDFQ79AfVEOkS:b8bqgd0) ([raw file](https://github.com/cockroachdb/cockroach/blob/da55069b9da144ce9d9893e9848fe99e9f0df9de/pkg/sql/sem/tree/time.go#L30)):*
> ```Go
> 		return time.Second
> 	case 1:
> 		return time.Millisecond * 100
> ```

tfw time.Decisecond is missing
___
*[pkg/sql/types/types.go, line 677 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42552#-Lu3FiBdCeudTd1mw7yK:-Lu3FiBdCeudTd1mw7yL:b-v7ncgw) ([raw file](https://github.com/cockroachdb/cockroach/blob/da55069b9da144ce9d9893e9848fe99e9f0df9de/pkg/sql/types/types.go#L677)):*
> ```Go
> 		return Time
> 	}
> 	if precision != 6 {
> ```

whats the reason we aren't also adding precision to the time type?
___
*[pkg/sql/types/types.go, line 837 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42552#-Lu3I0Yh-wkLcSfsUoWR:-Lu3I0Yh-wkLcSfsUoWS:bu39od3) ([raw file](https://github.com/cockroachdb/cockroach/blob/da55069b9da144ce9d9893e9848fe99e9f0df9de/pkg/sql/types/types.go#L837)):*
> ```Go
> // PrecisionExpandDefault returns the Precision, but for default
> // values it will return the precision with default set.
> func (t *T) PrecisionExpandDefault() int32 {
> ```

it looks like this is unused
___
*[pkg/sql/types/types_test.go, line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42552#-Lu3IpodCU0lqJHjZKj7:-Lu3IpodCU0lqJHjZKj8:b-9mnu18) ([raw file](https://github.com/cockroachdb/cockroach/blob/da55069b9da144ce9d9893e9848fe99e9f0df9de/pkg/sql/types/types_test.go#L227)):*
> ```Go
> 		// TIMESTAMP
> 		{MakeTimestamp(-1), Timestamp},
> 		{MakeTimestamp(-1), MakeScalar(TimestampFamily, oid.T_timestamp, -1, 0, emptyLocale)},
> ```

is there some way you can explicitly test that the 19.2 disk table descriptor is read correctly?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42552)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @solongordon)

___
*[pkg/sql/sem/tree/time.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42552#-Lu3FCo2B7eKi-ZPz8cz:-Lu3h_l6-y3qoNFg7auU:b-9vkotj) ([raw file](https://github.com/cockroachdb/cockroach/blob/da55069b9da144ce9d9893e9848fe99e9f0df9de/pkg/sql/sem/tree/time.go#L23)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

i feel like this should be a method on the DTimeStamp and DTimeStampTZ so that its clear this is only meant to be used on timestamps. or maybe just change the name so its clear for use on the time precisions only.
</blockquote></details>

I will change the naming.
___
*[pkg/sql/sem/tree/time.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42552#-Lu3FNh9BWDBh4qd2I0S:-Lu3i3gQALXL6QHl4TjE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da55069b9da144ce9d9893e9848fe99e9f0df9de/pkg/sql/sem/tree/time.go#L26)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

maybe make this a constant too, time.DefaultPrecision or something
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/time.go, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42552#-Lu3FUFNDFQ79AfVEOkR:-Lu3hK1_2P2lILJyUaPD:b32viz) ([raw file](https://github.com/cockroachdb/cockroach/blob/da55069b9da144ce9d9893e9848fe99e9f0df9de/pkg/sql/sem/tree/time.go#L30)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

tfw time.Decisecond is missing
</blockquote></details>

:P
___
*[pkg/sql/types/types.go, line 677 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42552#-Lu3FiBdCeudTd1mw7yK:-Lu3i4ag9HQbz9BE5WX_:bxbi2ph) ([raw file](https://github.com/cockroachdb/cockroach/blob/da55069b9da144ce9d9893e9848fe99e9f0df9de/pkg/sql/types/types.go#L677)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

whats the reason we aren't also adding precision to the time type?
</blockquote></details>

Needed more plumbing, and it's a separate issue. Was planning to do as a follow up.
___
*[pkg/sql/types/types.go, line 837 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42552#-Lu3I0Yh-wkLcSfsUoWR:-Lu3iB8q-VDmfRweo7JO:bfcrord) ([raw file](https://github.com/cockroachdb/cockroach/blob/da55069b9da144ce9d9893e9848fe99e9f0df9de/pkg/sql/types/types.go#L837)):*
> ```
> PrecisionExpandDefault
> ```
should be

pkg/sql/schemachange/alter_column_type.go
148:	oldPrecision := oldType.PrecisionExpandDefault()
149:	newPrecision := newType.PrecisionExpandDefault()
___
*[pkg/sql/types/types_test.go, line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42552#-Lu3IpodCU0lqJHjZKj7:-Lu3hPPw4V6uddR-oQP1:bb3bmmk) ([raw file](https://github.com/cockroachdb/cockroach/blob/da55069b9da144ce9d9893e9848fe99e9f0df9de/pkg/sql/types/types_test.go#L227)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

is there some way you can explicitly test that the 19.2 disk table descriptor is read correctly?
</blockquote></details>

I'm not sure, suggestions welcome.
Worst case, I can manually try upgrading... (if there's a wiki to do that lmk)

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42552)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan, @rohany, and @solongordon)

___
*[pkg/sql/sem/tree/time.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42552#-Lu3FNh9BWDBh4qd2I0S:-Lu3l9uoCuWPVdBuhzJV:b-ax11zj) ([raw file](https://github.com/cockroachdb/cockroach/blob/da55069b9da144ce9d9893e9848fe99e9f0df9de/pkg/sql/sem/tree/time.go#L26)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This doesn't look changed?
___
*[pkg/sql/types/types.go, line 837 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42552#-Lu3I0Yh-wkLcSfsUoWR:-Lu3lUIa0wDsAXmRPIG7:b-zayv74) ([raw file](https://github.com/cockroachdb/cockroach/blob/da55069b9da144ce9d9893e9848fe99e9f0df9de/pkg/sql/types/types.go#L837)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

> ```
> PrecisionExpandDefault
> ```
should be

pkg/sql/schemachange/alter_column_type.go
148:	oldPrecision := oldType.PrecisionExpandDefault()
149:	newPrecision := newType.PrecisionExpandDefault()
</blockquote></details>

ah cmd f is lying to me
___
*[pkg/sql/types/types_test.go, line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42552#-Lu3IpodCU0lqJHjZKj7:-Lu3lYWe4bCZh_yhu7Ef:btkncd2) ([raw file](https://github.com/cockroachdb/cockroach/blob/da55069b9da144ce9d9893e9848fe99e9f0df9de/pkg/sql/types/types_test.go#L227)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

I'm not sure, suggestions welcome.
Worst case, I can manually try upgrading... (if there's a wiki to do that lmk)
</blockquote></details>

i guess what would convince me is explicitly make the type as it was before this commit (without the precision), and make sure that it reads the default precision.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42552)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @solongordon)

___
*[pkg/sql/sem/tree/time.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42552#-Lu3FNh9BWDBh4qd2I0S:-Lu3pAVQEQD7VJdVhWAH:b50qp6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/da55069b9da144ce9d9893e9848fe99e9f0df9de/pkg/sql/sem/tree/time.go#L26)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

This doesn't look changed?
</blockquote></details>

sigh, didn't press save.
___
*[pkg/sql/types/types.go, line 837 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42552#-Lu3I0Yh-wkLcSfsUoWR:-Lu3pOGf4vLWadgccV62:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da55069b9da144ce9d9893e9848fe99e9f0df9de/pkg/sql/types/types.go#L837)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

ah cmd f is lying to me
</blockquote></details>

Done.
___
*[pkg/sql/types/types_test.go, line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42552#-Lu3IpodCU0lqJHjZKj7:-Lu3pYEh1ybWC3ELAmtf:b6gn1t5) ([raw file](https://github.com/cockroachdb/cockroach/blob/da55069b9da144ce9d9893e9848fe99e9f0df9de/pkg/sql/types/types_test.go#L227)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

i guess what would convince me is explicitly make the type as it was before this commit (without the precision), and make sure that it reads the default precision.
</blockquote></details>

I can try the manual upgrade technique in lieu of making a test suite of upgrading versions of cockroach :)

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42552)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan, @rohany, and @solongordon)

___
*[pkg/sql/types/types_test.go, line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42552#-Lu3IpodCU0lqJHjZKj7:-Lu3qMSZ7s-DkQT2HZQR:b-wnt15f) ([raw file](https://github.com/cockroachdb/cockroach/blob/da55069b9da144ce9d9893e9848fe99e9f0df9de/pkg/sql/types/types_test.go#L227)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

I can try the manual upgrade technique in lieu of making a test suite of upgrading versions of cockroach :)
</blockquote></details>

sorry i wasn't clear -- i meant in this test, make an instance of the timestamp struct as it was defined before this commit -- (without the precision)

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42552)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @solongordon)

___
*[pkg/sql/types/types_test.go, line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42552#-Lu3IpodCU0lqJHjZKj7:-Lu3sS4q1vobNK63uGI5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da55069b9da144ce9d9893e9848fe99e9f0df9de/pkg/sql/types/types_test.go#L227)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

sorry i wasn't clear -- i meant in this test, make an instance of the timestamp struct as it was defined before this commit -- (without the precision)
</blockquote></details>

Done.

**Comment by otan** [comment]
just realised this ain't backwards compatible, so going to close this off for review for a second.

**Comment by otan** [comment]
will note it in the PR message

**Comment by otan** [comment]
Oops, had another idea. Gimme a sec.

**Pull request closed without merging**
