### PR TITLE
jobs: remove unnecessary StatusPending job state

### PR DESCRIPTION
**Pull request by spaskob**
StatusPending and StatusRunning are essentially the same after
we enabled pending jobs to be resumable so there is no need
for this state and this will simplify all sanity checks in the
jobs codebase.

Release note: none.

### CODE REVIEW

**Review by thoszhang — COMMENTED** [review]
To clarify, is the plan to later add a new "pending" state to the state machine with different semantics than the old one? What is the intended status of jobs that have been created in a committed transaction but not yet adopted?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43929#-:-LyWZssQ3edoCeL4SU8T:b-39qyel)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @lucy-zhang)

**Comment by rytaft** [comment]
How will this interact with an old cluster that has an existing job in the DB with `StatusPending`? Maybe you need to add a cluster version for this change?

**Review by spaskob — COMMENTED** [review]
There is no plan to add new pending state, as soon as a job is created it is eligible for adoption so we are assuming it is running and yes created jobs will be directly in state running.
@rytaft that's good point that I missed; I can make the code more defensive by:
1. Not creating new jobs in state pending
2. Still treating correctly status pending if it is found that a job is in this case.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43929#-:-LyZk46z4OJK6Gp7NcvS:b-ate4gg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

**Comment by rytaft** [comment]
Sounds good thanks!

**Review by thoszhang — COMMENTED** [review]
I thought we wanted to eventually distinguish between "adoptable but not running" and "having the job resumer actually being executed on some node" (implying that we also have to change the semantics of the `running` state).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43929#-:-LyZuPXi9dsQ2E5mfgVn:b-q3opiq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

**Comment by dt** [comment]
That _was_ the plan but that really only tells you it _was_ being executed on some node at some point, but once any node has tried to start it, it would still be "running" even if that node crashed or otherwise isn't running it, so it doesn't _really_ do what we want. I think to distinguish between "this job exists and is runnable" and "this job is running" we need to look at for a valid lease as opposed to the status.

**Review by dt — APPROVED** [review]

**Review by thoszhang — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43929)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
