### PR TITLE
storage/engine: adjust default rocksdb.min_wal_sync_interval to 0.5ms

### PR DESCRIPTION
**Pull request by petermattis**
Release note (performance improvement): Adjust the default value of
"rocksdb.min_wal_sync_interval" to 0.5ms which significantly reduces the
number of disk write operations while have a negligible impact on
latency. This is particularly important in cloud deployments where
virtualized storage may have IOPS limitations.

### CODE REVIEW

**Comment by petermattis** [comment]
I'm not 100% sure we want to do this. @ajwerner mentioned he made this adjustment when he did the TPCC-100k run. In testing on `tpccbench` just now, making this adjustment cuts the number of Write IOPS in half. On the other hand, any artificial delay in the WAL sync path can only increase latency. Are we better off with a default tuned for cloud environments, or one tuned for local hardware?

**Comment by nvanbenschoten** [comment]
For reference, here are some results from prior testing with this setting on local SSDs:

plot2

> On the other hand, any artificial delay in the WAL sync path can only increase latency.

Interestingly, we don't see the setting have a measurable effect on average or tail latency when set below 1ms. Of course, that was with sustained load and this would likely have an effect with more bursty load. On the other hand, throughput was impacted once this setting went above 100us and it eventually fell off a cliff above 1ms.

There's certainly a trade-off here. I'd be ok with giving this a default anywhere between 100us and 500us, with a slight preference for somewhere in the middle. Even set at 100us, we'd expect this to halve IOPS for sustained write workloads.

**Comment by petermattis** [comment]
> For reference, here are some results from prior testing with this setting on local SSDs:

Interesting. How long ago were these results collected? What workload were you running?

> There's certainly a trade-off here. I'd be ok with giving this a default anywhere between 100us and 500us, with a slight preference for somewhere in the middle. Even set at 100us, we'd expect this to halve IOPS for sustained write workloads.

I'm not set on the 500us value. I think it is worthwhile to re-run some experiments on current master with various settings. My thinking is to test `kv0`, `ycsb` and `sysbench`, with values of 100us, 250us, 500us, and 1ms.

**Comment by nvanbenschoten** [comment]
> How long ago were these results collected?

This was from the [Delaying RockDB WAL syncs to Reduce Write IOPS on CockroachCloud](https://groups.google.com/a/cockroachlabs.com/forum/#!search/sync$20wal/eng/IlzUyak8YOg/g7vFUS3yAgAJ) thread, so it looks like this was run on 9/27/19. 

> What workload were you running?

`kv0` with value sizes of 64 bytes at what I assume was a fixed concurrency.

> I think it is worthwhile to re-run some experiments on current master with various settings. My thinking is to test kv0, ycsb and sysbench, with values of 100us, 250us, 500us, and 1ms.

Those workload configurations sound reasonable to me.

One thing that's not clear to me is whether this setting will impact the optimal concurrency level at which to run these workloads. I doubt it will affect ycsb, but it may have a sizable impact on kv0 and sysbench. I'd guess that as the delay increases, you'll want to increase workload concurrency as well.

**Comment by petermattis** [comment]
> One thing that's not clear to me is whether this setting will impact the optimal concurrency level at which to run these workloads. I doubt it will affect ycsb, but it may have a sizable impact on kv0 and sysbench. I'd guess that as the delay increases, you'll want to increase workload concurrency as well.

I'll experiment with adjusting concurrency for `kv0` when I do this experimentation. Probably won't happen until next week.

**Comment by ajwerner** [comment]
> One thing that's not clear to me is whether this setting will impact the optimal concurrency level at which to run these workloads. I doubt it will affect ycsb, but it may have a sizable impact on kv0 and sysbench. I'd guess that as the delay increases, you'll want to increase workload concurrency as well.

Could we try using the `kvbench` roachtest that @aayushshah15 wrote to explore the concurrency space? https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/kvbench.go

**Comment by petermattis** [comment]
I ran a bunch of experiments using `kv0` and `ycsb` this weekend. I still have to analyze the results, but it looks like 100us would be the reasonable setting, or leave this unchanged. Here is a graph of `kv0/enc=false/nodes=1` where I adjust `rocksdb.min_wal_sync_interval` every 3 min. The values used are `0us`, `100us`, `250us`, `500us` and `1000us`.

Screen Shot 2020-03-10 at 9 18 36 AM

Hovering over the graph showed that following approximate disk write ops:

| min-wal-sync-interval | disk-write-ops |
| --- | --- |
| 0us | 1400 |
| 100us | 750 |
| 250us | 650 |
| 500us | 550 |
| 1000us | 450 |

This matches up with what @nvanbenschoten saw earlier.

**Comment by petermattis** [comment]
The charts below show percentage difference from the baseline of 10 runs with various settings of `rocksdb.min_wal_sync_interval` on a handful of tests. Even a value of 100us affects throughput and latency. Are the wins worth the losses? I'm undecided. @nvanbenschoten, @ajwerner what do you think?

PS If we decide not to merge this, I'll add a comment explaining why the current setting is good, and a pointer to this analysis.

Screen Shot 2020-03-10 at 2 31 10 PM

Screen Shot 2020-03-10 at 2 31 20 PM

Screen Shot 2020-03-10 at 2 31 37 PM

**Comment by ajwerner** [comment]
Did you run this only on `c5d.4xlarge` machines with local SSDs? If so, I'm not sure it's representative of what our customers will always see. In particular if using EBS with io1, the performance implications of running up against the iop limits are dramatic compared to the costs of waiting a bit. I bet you'll find something similar on gp2. 

At the end of the day there's a tradeoff. I'd be fine not changing the default but making more explicit callouts in production checklists, especially when dealing with EBS or slower devices storage devices.

**Comment by petermattis** [comment]
> Did you run this only on c5d.4xlarge machines with local SSDs? If so, I'm not sure it's representative of what our customers will always see. In particular if using EBS with io1, the performance implications of running up against the iop limits are dramatic compared to the costs of waiting a bit. I bet you'll find something similar on gp2.

I explicitly ran with local SSDs because I didn't want to hit the IOPS limits. Clearly, delaying for a bit is better than hitting the IOPS limits, but what is the right default here? 

> At the end of the day there's a tradeoff. I'd be fine not changing the default but making more explicit callouts in production checklists, especially when dealing with EBS or slower devices storage devices.

Ack. This should definitely be on a production checklist. The above is good ammo for what value to choose. I might try re-rerunning these experiments on `io1` devices to see if there is any difference. I presume that the workloads will stay under the IOPS limits, though.

**Comment by knz** [comment]
Has this PR been obviated by innovation inside pebble?

**Comment by petermattis** [comment]
> Has this PR been obviated by innovation inside pebble?

No. There hasn't been any change in Pebble which obviates this PR. Increasing `min_wal_sync_interval` can reduce IOPs but it does so at the expense of slightly lower throughput and slightly higher latency. I suspect that the current default for that setting is fine, and the outcome from this PR should be documentation about the effects of this setting and why you might want to set it.

**Comment by knz** [comment]
> the outcome from this PR should be documentation about the effects of this setting and why you might want to set it.

cool. @taroface is that something that's inside your scope?

**Pull request closed without merging**
