### PR TITLE
opt: add exploretrace test facility

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: add exploretrace test facility

Adding a tester facility that shows exploration transforms in detail:
it shows the expression the rule ran on, and all expressions that were
added (well, it shows full expression trees which contain these
expressions).

This will be useful for debugging exploration rules and writing tests
for them.

Sample output: https://gist.github.com/RaduBerinde/a76feb7ed5c79ad9b8c14256c205d488

Release note: None

#### opt: add rule flag to exploretrace

Add a rule=XX flag to exploretrace which restricts the output to
applications of that rule. Meant to be used when developing a specific
rule. A few example test cases using this have been added.

Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
:lgtm:, nice work

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/testutils/explore_trace.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27136#-LGWvRL42yHHfW1j2ZGa:-LGWvRL55OQhRHEpKmB0:b10zz62) ([raw file](https://github.com/cockroachdb/cockroach/blob/4731c713a5f924c1eec3ba893f0e78e275688fd8/pkg/sql/opt/testutils/explore_trace.go#L47)):*
> ```Go
> }
> 
> func (et *exploreTracer) LastRuleName() opt.RuleName {
> ```

I thought it's not advisable to use capitalized method names in un-exported struct? If it's fine to do, I'll probably start doing it more. : )

---

*[pkg/sql/opt/testutils/explore_trace.go, line 59 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27136#-LGWvZelD9Y-ggo2Bd96:-LGWvZelD9Y-ggo2Bd97:b-6fuv3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/4731c713a5f924c1eec3ba893f0e78e275688fd8/pkg/sql/opt/testutils/explore_trace.go#L59)):*
> ```Go
> }
> 
> // done returns true if there are no more rules to apply. Further calls to the
> ```

NIT: done -> Done

---

*[pkg/sql/opt/testutils/forcing_opt.go, line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27136#-LGWw8zo97bHLSGGU3To:-LGWw8zo97bHLSGGU3Tp:b5wig3l) ([raw file](https://github.com/cockroachdb/cockroach/blob/4731c713a5f924c1eec3ba893f0e78e275688fd8/pkg/sql/opt/testutils/forcing_opt.go#L65)):*
> ```Go
> // rules don't count against this limit.
> func newForcingOptimizer(
> 	tester *OptTester, steps int, ignoreNormRules bool,
> ```

NIT: `ignoreNormRules` would be much better as a method/field on `forcingOptimizer`. I'd have probably made `newForcingOptimizer` only init the struct, and then `optimize` would do the real work of hooking up the notifications, building the expr, etc. Then usage would be:
```
opt := newForcingOptimizer(tester, steps)
opt.ignoreNormRules = true
ev, err := opt.optimize()
if err != nil {
  panic(err)
}
```
I'm not stuck on this, but wanted to bring it up, b/c it's a more extensible pattern to be able to set options after construction, before you actually do any real work.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27136#-:-LGWxWFb4ME6BawYfNWe:b-qyf0xd)*

**Comment by RaduBerinde** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/testutils/explore_trace.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27136#-LGWvRL42yHHfW1j2ZGa:-LGX8OVb95zoYylRhnZB:b-m41d5r) ([raw file](https://github.com/cockroachdb/cockroach/blob/4731c713a5f924c1eec3ba893f0e78e275688fd8/pkg/sql/opt/testutils/explore_trace.go#L47)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I thought it's not advisable to use capitalized method names in un-exported struct? If it's fine to do, I'll probably start doing it more. : )
</blockquote></details>

It's fine AFAIK, we've been doing it in various places to help separate the "interface" from internal stuff (even if it's not used from outside the package).

---

*[pkg/sql/opt/testutils/forcing_opt.go, line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27136#-LGWw8zo97bHLSGGU3To:-LGXCzS03Q1ErJTVGmPf:b-mpkcik) ([raw file](https://github.com/cockroachdb/cockroach/blob/4731c713a5f924c1eec3ba893f0e78e275688fd8/pkg/sql/opt/testutils/forcing_opt.go#L65)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: `ignoreNormRules` would be much better as a method/field on `forcingOptimizer`. I'd have probably made `newForcingOptimizer` only init the struct, and then `optimize` would do the real work of hooking up the notifications, building the expr, etc. Then usage would be:
```
opt := newForcingOptimizer(tester, steps)
opt.ignoreNormRules = true
ev, err := opt.optimize()
if err != nil {
  panic(err)
}
```
I'm not stuck on this, but wanted to bring it up, b/c it's a more extensible pattern to be able to set options after construction, before you actually do any real work.
</blockquote></details>

I tried to do this but it gets complicated. `restrictToExprs` needs the root so we can't move the build to `optimize`. I spent some time trying to make it work but it's not worth the marginal benefit.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27136)*

**Comment by RaduBerinde** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

---

*[pkg/sql/opt/xform/testdata/rules/join, line 424 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27136#-LGY66_e0oi4UFA4ojUF:-LGY9jWp9jJC2NWpmsVz:banj9c1) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ad9a86a8b0a97e5adb9e2be8ec737580ca0d8cd/pkg/sql/opt/xform/testdata/rules/join#L424)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Is `exploretrace` useful without a rule specified? If so, could you add one test case to show what that looks like?
</blockquote></details>

Yes, it shows all the exploration rule applications (there was a link to a sample output in the commit message). I added a `combo` test file with one.

---

*[pkg/sql/opt/xform/testdata/rules/join, line 445 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27136#-LGY5Y6T1YPUs4kZdjlv:-LGYCGvKCfKQDdpSnHXM:b-luvtpb) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ad9a86a8b0a97e5adb9e2be8ec737580ca0d8cd/pkg/sql/opt/xform/testdata/rules/join#L445)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I feel like it might be useful to show the cost here, so it's easy to see why an expression was chosen or not.
</blockquote></details>

Exploration is not currently guided by cost (nothing in this output is about what gets or doesn't get chosen). BTW if it is needed in a specific case, `format=show-all` can be added to the directive line.

---

*[pkg/sql/opt/xform/testdata/rules/join, line 465 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27136#-LGY5svDBXvYrRk4gqlE:-LGYC8XI7hRKxXRacA93:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ad9a86a8b0a97e5adb9e2be8ec737580ca0d8cd/pkg/sql/opt/xform/testdata/rules/join#L465)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] one blank line or some other separator between expressions would be helpful
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27136)*

**Comment by rytaft** [comment]
Reviewed 1 of 4 files at r5, 3 of 3 files at r6.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

---

*[pkg/sql/opt/xform/testdata/rules/join, line 424 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27136#-LGY66_e0oi4UFA4ojUF:-LG_jq6XAhb52xxZOlmb:blgnl2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ad9a86a8b0a97e5adb9e2be8ec737580ca0d8cd/pkg/sql/opt/xform/testdata/rules/join#L424)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yes, it shows all the exploration rule applications (there was a link to a sample output in the commit message). I added a `combo` test file with one.
</blockquote></details>

Looks good - thanks!

---

*[pkg/sql/opt/xform/testdata/rules/join, line 445 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27136#-LGY5Y6T1YPUs4kZdjlv:-LG_jvjX9eCHk_x03Lyl:b5vjmdl) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ad9a86a8b0a97e5adb9e2be8ec737580ca0d8cd/pkg/sql/opt/xform/testdata/rules/join#L445)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Exploration is not currently guided by cost (nothing in this output is about what gets or doesn't get chosen). BTW if it is needed in a specific case, `format=show-all` can be added to the directive line.
</blockquote></details>

Got it - thanks!

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27136)*

**Pull request merged**
