### PR TITLE
storage: de-flake TestReplicateQueueDownReplicate

### PR DESCRIPTION
**Pull request by tbg**
Reproduced via

```
make stressrace PKG=./pkg/storage/ TESTS=TestReplicateQueueDownReplicate STRESSFLAGS='-stderr=false -p 12'
```

in a few minutes (on a gceworker).

The test would sometimes fail since the range log verification was
overly aggressive in the sense that it would fail on all but the
expected reasons. However we have learners now and sometimes they're
rolled back, which also causes events.

The range log checks were overly complicated to, so boil them down a
bunch to something more manageable.

Release note: None

### CODE REVIEW

**Review by danhhz — APPROVED** [review]

**Comment by tbg** [comment]
TFTR!

bors r=danhhz

**Comment by danhhz** [comment]
`bank.go:387,bank.go:502,acceptance.go:69,test_runner.go:691: after 2.7s: pq: cannot transfer lease to replica of type LEARNER`

looks like the test tries to manually run EXPERIMENTAL_RELOCATE, so I could see us getting this error from there

**Comment by danhhz** [comment]
I'll look into that flake separately, but it's not an issue introduced by this deflake

bors r+

**Comment by tbg** [comment]
Thanks Dan

**Pull request merged**
