### PR TITLE
sql: decompose vtable to allow pushing down filters

### PR DESCRIPTION
**Pull request by changangela**
Related to #29165.

This change sets up the structure for splitting up the current `virtualTableNode` into two different nodes:
- the `virtualTableNode` which is responsible for generating the "cheap" datum fields in the row. In the example of `crdb_internal.ranges`, this node would return the `range_id`, `start_key`, and `end_key`, etc
- the `virtualTableAugmenterNode` is responsible for generating the "expensive" datum fields in the row (ie. the fields not resolved by the corresponding `virtualTableNode`). In the example of `crdb_internal.ranges`, this node would add the `lease` field which is obtained through an expensive request.

The purpose of this change is to be able to perform a filter on the "cheap" information of the virtual table rows, before loading the more expensive data.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Hi Angela,
Could you write down some high level notes in the commit message about what it's doing and how? It's pretty hard to understand what the change is doing, particularly for folks who are not superfamiliar with this area of the code.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30478#-:-LMscufA0rDtIWlQiE15:bj5s46d)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by RaduBerinde — COMMENTED** [review]
Which piece of code will figure out what part of the filter to push down in-between the `virtualTableNode` and the `virtualTableAugmenterNode`? Would the optimizer have to understand these separate nodes and what they do? It seems we would need to add new filter pushdown rules just for this use-case. Or would this all be somehow hidden inside `execFactory.ConstructVirtualScan`? CC @justinj 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30478#-:-LMsr0Ou93iQ-8O9yWGC:bxcotsb)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by justinj — COMMENTED** [review]
I'll need to take a deeper look when I have a chance, but my thoughts with the initial issue were that we would be able to plan (exclusively in the optimizer) a projection using some internal-only builtins to populate the missing fields, I haven't inspected the code too thoroughly yet so I don't know what exactly it does, but is there a reason we need a new node to do this, and can't use a regular projection? Then we'd be able to treat it like we do any other projection in the optimizer.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30478#-:-LMstOPN9vhg5mnvE5nD:b-iukauz)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by RaduBerinde — COMMENTED** [review]
This code does not go the internal-only builtins route for populating the missing columns.. It creates a separate `virtaulTableAugmenterNode` that fills them in (kind of like an index join).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30478#-:-LMsun_I55tRWMf1E4aS:b-9xuhcb)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by changangela** [comment]
Are there any advantages or disadvantages to using this approach vs using internal-only builtins? I'm thinking that creating this `virtualTableAugmenter` allows us to conveniently manually define these "augmenter" functions, and this node would serve the simple purpose of augmenting virtual tables.

**Review by RaduBerinde — COMMENTED** [review]
With respect to impact on the optimizer - the augmenter node implements a new operation, which is similar to an index/lookup join but would need to be a new operator (which has a bunch of implementation aspects, plus it would need filter pushdown rules). Builtins would be treated transparently, it would just be a query like `SELECT x, y, f(x) FROM vtable`. The optimizer would push down whatever part of the filters it can before the projection.

I don't have a good sense whether these builtins would be much harder to write though.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30478#-:-LMsxMU1BAvGFu7pmG9a:b-7vf29i)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by jordanlewis** [comment]
The main trouble with writing this kind of thing as a builtin is that builtins would now need access to the `txn`, which they don't have as of today. I'm not sure how bad that is though.

Also, it would preclude you from doing batching. Having a dedicated node would permit keeping state and requesting a whole batch of leases at once, instead of one per row.

**Comment by changangela** [comment]
After some discussion with @justinj and @jordanlewis , we have decided to go with the builtins approach because it better integrates with the existing execution/optimizer structure.

Specifically pertaining to `crdb_internal.ranges`, the idea is to add a builtin called `fetch_leases`. We can then delegate the query `SELECT * FROM crdb_internal.ranges` to something like `SELECT id, fetch_leases(id) FROM crdb_internal.ranges_no_lease`.

**Pull request closed without merging**
