### PR TITLE
syncutil,storage: Introduce TimedMutex.AssertHeld and fix TestSkipLargeReplicaSnapshot

### PR DESCRIPTION
**Pull request by bdarnell**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10894)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica_raftstorage_test.go, line 95 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10894#-KX5TXCxI3AVHKn1sshM:-KX5TXCxI3AVHKn1sshN:b7fp42) ([raw file](https://github.com/cockroachdb/cockroach/blob/b01b2c11155b6f0de9ee514a8310de6aff1e4b74/pkg/storage/replica_raftstorage_test.go#L95)):*
> ```Go
> 	if err != raft.ErrSnapshotTemporarilyUnavailable {
> 		rep.mu.Lock()
> 		after := rep.mu.state.Stats.Total()
> ```

does this want to be atomic with the snapshot above?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10894#-:-KX5TbryPeQrQziPW6pc:bnfp4nl)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica_raftstorage_test.go, line 95 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10894#-KX5TXCxI3AVHKn1sshM:-KX5pTAe4Yj9h71_YcHp:bhls72t) ([raw file](https://github.com/cockroachdb/cockroach/blob/b01b2c11155b6f0de9ee514a8310de6aff1e4b74/pkg/storage/replica_raftstorage_test.go#L95)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> does this want to be atomic with the snapshot above?
</details>
It doesn't really matter; it's just being used in the error message (and two separate locks is what the code thought it was doing before).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10894)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/util/syncutil/timedmutex.go, line 32 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10894#-KX63mTPsZc-b_SNiPe1:-KX63mTPsZc-b_SNiPe2:b1617gw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b01b2c11155b6f0de9ee514a8310de6aff1e4b74/pkg/util/syncutil/timedmutex.go#L32)):*
> ```Go
> 	mu       *Mutex       // intentionally pointer to make zero value unusable
> 	lockedAt time.Time    // protected by mu
> 	isLocked atomic.Value // contains a bool, or nil before first use
> ```

Would this be better as a `int32` that is atomically set? I think the `atomic.Value` implies an allocation in order to store the `bool` an an `interface{}`. (I'm not actually sure about that, though).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10894)*

**Comment by bdarnell** [comment]
Yeah, I think atomic.value does imply an allocation. Changed. Simpler that way too since the uninitialized case is no longer special.

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10894#-:-KX6b5bXRiG4zgSzwp2A:bnfp4nl)*

**Pull request merged**
