### PR TITLE
[CRDB-2743] sql: create builltin generator crdb_internal.probe_range

### LINKED ISSUE #61695: kvprober: allow a manual probe of the entire keyspace
**Is your feature request related to a problem? Please describe.**
While the [kvprober](https://github.com/cockroachdb/cockroach/blob/0dd1e5547452e715db9db999df1f2e592cb17a4f/pkg/kv/kvprober/kvprober.go#L11-L18) probes "random" kv ranges at intervals, when in an incident one also wants to conclusively establish health of the KV layer by proactively probing the entire keyspace as quickly as possible. This would either result in specific ranges that fail the probe (and thus an indication that there is an issue at the KV layer or below) or not (thus indicating a failure above the KV layer or a failure not caught by the probe).

**Describe the solution you'd like**

I think it would make sense to run something like

```go
select crdb_internal.probe_range(start_key) from crdb_internal.ranges_no_leases;
  range_id | pass | details
-----------+------+----------
        1  | true | {"read_ns": 150031, "write_ns": ...}
[...]
```

So the task at hand becomes implementing `crdb_internal.probe`.

**Describe alternatives you've considered**

One could likely come up with many alternative designs. 

**Additional context**

Currently, in practice I believe we (or at least I) ascertain KV health by looking through the logs of messages of the form `have been waiting X for Y` which are emitted on slow replication, slow latching, slow DistSender RPCs, and a few others. With probes becoming suitably powerful, they should be able to catch most of these. These log messages are also hooked up to the `slow.*` family of gauges, which however don't let you figure out which ranges have the issue.

Jira issue: CRDB-2743

### PR DESCRIPTION
**Pull request by Santamaura**
Previously there was difficulty in diagnosing kv layer health when
an incident occurs. This patch introduces the new virtual table
crdb_internal.probe_range which utilizes the kvprober to probe
each range to determine if the range can be reached or not.

resolves #61695

Release note: None

Screen Shot 2022-04-20 at 1 15 17 PM

### CODE REVIEW

**Comment by Santamaura** [comment]
One thing I am unsure of is in the case of a timeout whether the `Prober.writePlanner` will update the next step or not. If it doesn't and we are iterating through ranges we've already visited we may end up in an infinite loop.

**Review by tbg — CHANGES_REQUESTED** [review]
Thanks Alex! I left some conceptual comments that I think will simplify things a bit, and will also address your question (by removing it).

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79546#-:-N-NlZRxC_soEI060itO:bl675ao)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @joshimhoff, @koorosh, @Santamaura, and @zachlite)

___
*[pkg/sql/sem/builtins/generator_builtins.go, line 478 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79546#-N-NfA_h6np3tENWrOh0:-N-NfA_h6np3tENWrOh1:bcaac2h) ([raw file](https://github.com/cockroachdb/cockroach/blob/4da1cbcb7cbf42909d5020a6586b62ce75cc66b6/pkg/sql/sem/builtins/generator_builtins.go#L478)):*
> ```Go
> 		makeGeneratorOverload(
> 			tree.ArgTypes{
> 				{Name: "timeout", Typ: types.Int},
> ```

shouldn't this be something like `types.IntervalDurationType` or `types.Interval`?
___
*[pkg/sql/sem/builtins/generator_builtins.go, line 1749 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79546#-N-NfVXQ18Q_ECmesXpu:-N-NfVXQ18Q_ECmesXpv:b3kre) ([raw file](https://github.com/cockroachdb/cockroach/blob/4da1cbcb7cbf42909d5020a6586b62ce75cc66b6/pkg/sql/sem/builtins/generator_builtins.go#L1749)):*
> ```Go
> // rangeKeyIterator is a ValueGenerator that iterates over all
> // SQL keys in a target range.
> // REFER TO HERE
> ```

?
___
*[pkg/sql/sem/builtins/generator_builtins.go, line 2436 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79546#-N-Ng-rYAWSEsM4wGCT7:-N-Ng-rYAWSEsM4wGCT8:b-x9kdj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4da1cbcb7cbf42909d5020a6586b62ce75cc66b6/pkg/sql/sem/builtins/generator_builtins.go#L2436)):*
> ```Go
> 	if err != nil {
> 		return nil, pgerror.Newf(
> 			pgcode.InFailedSQLTransaction,
> ```

Is this really the right code?
___
*[pkg/sql/sem/builtins/generator_builtins.go, line 2465 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79546#-N-Nfjus4VmQqlchFd-C:-N-Nfjus4VmQqlchFd-D:b-vpe295) ([raw file](https://github.com/cockroachdb/cockroach/blob/4da1cbcb7cbf42909d5020a6586b62ce75cc66b6/pkg/sql/sem/builtins/generator_builtins.go#L2465)):*
> ```Go
> 		prober:          *kvProber,
> 		ranges:          make(map[int64]int),
> 		remainingRanges: int64(numRanges),
> ```

This doesn't seem right. The range count changes out from under you through splits and merges, so any code that stores it like this is likely fishy.
___
*[pkg/sql/sem/builtins/generator_builtins.go, line 2481 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79546#-N-NgBYbA226xKNQI4ru:-N-NgBYbA226xKNQI4rv:bm7id7b) ([raw file](https://github.com/cockroachdb/cockroach/blob/4da1cbcb7cbf42909d5020a6586b62ce75cc66b6/pkg/sql/sem/builtins/generator_builtins.go#L2481)):*
> ```Go
> // Next implements the tree.ValueGenerator interface.
> func (p *probeRangeGenerator) Next(ctx context.Context) (bool, error) {
> 	if p.remainingRanges == 0 {
> ```

Yeah this isn't going to be correct. If a range splits while the probe is underway, you'll end up stopping short. I'm not sure what will happen if a range merges but it doesn't really matter, we need to fix this.

I think the root problem is that this code wants to use the planner "as is". Instead, we should refactor the planner to make the interesting parts of it more reusable, and then reuse only those parts. We need only two things here: iterate through all range descriptors (i.e. discover all of the ranges in the system, with a consistent view) and then probe each of them.

Thinking this through a bit, there actually isn't a good reason to use the planner's ability to discover ranges, as it's too complex and prober-specific for what we need. The code we want is really this:

https://github.com/cockroachdb/cockroach/blob/d4daa99f6bcae263ba351e2b101901dae8bb110f/pkg/sql/crdb_internal.go#L3224-L3227

This isn't streaming which isn't ideal, but it's also what is used by `crdb_internal.ranges_no_leases`, so when we fix that we'll automatically fix it here. It is fine to use for now.

I'm also noticing that the `internal_no_leases` [generator](https://github.com/cockroachdb/cockroach/blob/d4daa99f6bcae263ba351e2b101901dae8bb110f/pkg/sql/crdb_internal.go#L3179-L3350) is much more compact and doesn't seem to need to define a new  type, so maybe you can adopt this pattern here and forfeit a bunch of boilerplate? I might be missing something.

As for the probing itself, we "just" need to export `proberOpsImpl`:

https://github.com/cockroachdb/cockroach/blob/18b95cbb23c005e816b3b3f8747b43cc311509ca/pkg/kv/kvprober/kvprober.go#L160-L186

because that's what we want to invoke for the probe.

So in this PR, I would expect:

- get list of descs (just like `ranges_no_leases`)
- for each desc, invoke `kvProbe{}.Write` (or read depending on options), with much of the garnish that you have here already, and produce a row

**Review by Santamaura — COMMENTED** [review]
The comments did help thanks :thumbsup: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79546#-:-N-Tgx4E88k_-qJV8hc1:bvwut9j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @joshimhoff, @koorosh, @tbg, and @zachlite)

___
*[pkg/sql/sem/builtins/generator_builtins.go, line 478 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79546#-N-NfA_h6np3tENWrOh0:-N-Th2UrCBYU1fi22uz-:bj6n3k5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4da1cbcb7cbf42909d5020a6586b62ce75cc66b6/pkg/sql/sem/builtins/generator_builtins.go#L478)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

shouldn't this be something like `types.IntervalDurationType` or `types.Interval`?
</blockquote></details>

Yeah makes more sense to be interval, changed.
___
*[pkg/sql/sem/builtins/generator_builtins.go, line 1749 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79546#-N-NfVXQ18Q_ECmesXpu:-N-Th8fzB8iXfnjHG7y6:b5alms7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4da1cbcb7cbf42909d5020a6586b62ce75cc66b6/pkg/sql/sem/builtins/generator_builtins.go#L1749)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

?
</blockquote></details>

A comment from when I was figuring out how builtin generators worked, removed.
___
*[pkg/sql/sem/builtins/generator_builtins.go, line 2436 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79546#-N-Ng-rYAWSEsM4wGCT7:-N-ThbKhDKqbPQUrXpz4:bgisszx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4da1cbcb7cbf42909d5020a6586b62ce75cc66b6/pkg/sql/sem/builtins/generator_builtins.go#L2436)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Is this really the right code?
</blockquote></details>

The error code is irrelevant now, removed.
___
*[pkg/sql/sem/builtins/generator_builtins.go, line 2465 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79546#-N-Nfjus4VmQqlchFd-C:-N-ThmU9EdhGjOyvy1Vp:b-mx9h11) ([raw file](https://github.com/cockroachdb/cockroach/blob/4da1cbcb7cbf42909d5020a6586b62ce75cc66b6/pkg/sql/sem/builtins/generator_builtins.go#L2465)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This doesn't seem right. The range count changes out from under you through splits and merges, so any code that stores it like this is likely fishy.
</blockquote></details>

Right that makes sense.
___
*[pkg/sql/sem/builtins/generator_builtins.go, line 2481 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79546#-N-NgBYbA226xKNQI4ru:-N-Thtn53z7xTe8-yW1h:b-3a57w1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4da1cbcb7cbf42909d5020a6586b62ce75cc66b6/pkg/sql/sem/builtins/generator_builtins.go#L2481)):*
>I think the root problem is that this code wants to use the planner "as is". Instead, we should refactor the planner to make the interesting parts of it more reusable, and then reuse only those parts. We need only two things here: iterate through all range descriptors (i.e. discover all of the ranges in the system, with a consistent view) and then probe each of them.

Yeah I was iffy about using the current planner but wasn't sure if we should get the ranges how `crdb_internal.ranges_no_leases` does it. I've refactored the generator to use this way and then also just use `Read` or `Write` now. 

>I'm also noticing that the internal_no_leases generator is much more compact and doesn't seem to need to define a new type, so maybe you can adopt this pattern here and forfeit a bunch of boilerplate? I might be missing something.

When I was looking over those, there didn't seem to be a way of passing arguments into generators created in that way, if it turns out they can have arguments passed I can move it over.

**Comment by tbg** [comment]
I pushed a commit with some fixes and a bunch of TODO(alex)es which are basically my review comments.

**Review by tbg — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79546)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @joshimhoff, @koorosh, @tbg, and @zachlite)

**Review by tbg — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79546)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @joshimhoff, @koorosh, and @zachlite)

**Comment by Santamaura** [comment]
I think I covered everything from the TODOs, let me know if there's any outstanding

**Review by tbg — APPROVED** [review]
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79546)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @joshimhoff, @koorosh, @Santamaura, and @zachlite)

___
*[pkg/sql/sem/builtins/generator_probe_ranges.go, line 74 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/79546#-N07_5w990sqoQ2y2bhC:-N07_5w990sqoQ2y2bhD:b9e3scs) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea1b2ef3d4bb303d5195222fea592d9918dca03/pkg/sql/sem/builtins/generator_probe_ranges.go#L74)):*
> ```Go
> 				A write probe will effectively probe reads as well.
> 			`,
> 			// TODO(alex): add unit tests of this via a LogicTest. Make sure that the test doesn't verify anything that changes
> ```

Here's a TODO still. You have this test, though the "trace matches the string ..." part doesn't seem to be in it.
___
*[pkg/sql/sem/builtins/generator_probe_ranges.go, line 91 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/79546#-N07_Add87iVU1ZJSVei:-N07_Add87iVU1ZJSVej:bw4w6p1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea1b2ef3d4bb303d5195222fea592d9918dca03/pkg/sql/sem/builtins/generator_probe_ranges.go#L91)):*
> ```Go
> 		EnumData: &types.EnumMetadata{
> 			LogicalRepresentations: enumMembers,
> 			PhysicalRepresentations: [][]byte{
> ```

I have no idea what's going on here, you may want to get a SQL person's review as well at least for these generator parts.
___
*[pkg/sql/sem/builtins/generator_probe_ranges.go, line 194 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/79546#-N07_bd83btO3UoJZAPr:-N07_bd83btO3UoJZAPs:by1ox6q) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea1b2ef3d4bb303d5195222fea592d9918dca03/pkg/sql/sem/builtins/generator_probe_ranges.go#L194)):*
> ```Go
> 	}()
> 
> 	ops := &kvprober.ProberOps{}
> ```

nit: you can make this a field on `probeRangeGenerator`. `ProberOps` is a `struct{}` so this line technically doesn't allocate but it saves future readers a double take.
___
*[pkg/sql/logictest/testdata/logic_test/generator_probe_ranges, line 17 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/79546#-N07ceaEEfMYavGNIMEX:-N07ceaEEfMYavGNIMEY:b-qn7g0q) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea1b2ef3d4bb303d5195222fea592d9918dca03/pkg/sql/logictest/testdata/logic_test/generator_probe_ranges#L17)):*
> ```
> 
> query T
> SELECT substring('$trace_str', 33, 34)
> ```

What's this doing?  We want to check for evidence of a trace event that comes out of KV which I am sure this isn't doing.

**Review by Santamaura — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79546)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @joshimhoff, @koorosh, @tbg, and @zachlite)

___
*[pkg/sql/sem/builtins/generator_probe_ranges.go, line 74 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/79546#-N07_5w990sqoQ2y2bhC:-N0CuUTB8jqZt0MgTMO7:bup2yho) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea1b2ef3d4bb303d5195222fea592d9918dca03/pkg/sql/sem/builtins/generator_probe_ranges.go#L74)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Here's a TODO still. You have this test, though the "trace matches the string ..." part doesn't seem to be in it.
</blockquote></details>

:smile: I didn't realize we wanted to actually match 'proposing command'. Fixed.
___
*[pkg/sql/sem/builtins/generator_probe_ranges.go, line 91 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/79546#-N07_Add87iVU1ZJSVei:-N0CudnY4lAQZVsGegY-:bhzwhxx) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea1b2ef3d4bb303d5195222fea592d9918dca03/pkg/sql/sem/builtins/generator_probe_ranges.go#L91)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I have no idea what's going on here, you may want to get a SQL person's review as well at least for these generator parts.
</blockquote></details>

Good idea, if nobody reviews in some time I'll reach out to someone on SQL.
___
*[pkg/sql/sem/builtins/generator_probe_ranges.go, line 194 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/79546#-N07_bd83btO3UoJZAPr:-N0CutiCEMSlmn_5hey_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea1b2ef3d4bb303d5195222fea592d9918dca03/pkg/sql/sem/builtins/generator_probe_ranges.go#L194)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

nit: you can make this a field on `probeRangeGenerator`. `ProberOps` is a `struct{}` so this line technically doesn't allocate but it saves future readers a double take.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/generator_probe_ranges, line 17 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/79546#-N07ceaEEfMYavGNIMEX:-N0CuyjP-4kc-Lv_TWrO:b-ky0rp5) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea1b2ef3d4bb303d5195222fea592d9918dca03/pkg/sql/logictest/testdata/logic_test/generator_probe_ranges#L17)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

What's this doing?  We want to check for evidence of a trace event that comes out of KV which I am sure this isn't doing.
</blockquote></details>

Changed so that we confirm the verbose trace includes 'proposing command'

**Review by tbg — APPROVED** [review]
:lgtm: thank you! Still think this is worth a glance from SQL but this may even happen after the merge IMO.

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79546#-:-N0FBABV5KXymfQjNt9b:b-lowyj0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @joshimhoff, @koorosh, @Santamaura, and @zachlite)

___
*[pkg/sql/sem/builtins/generator_probe_ranges.go, line 74 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/79546#-N07_5w990sqoQ2y2bhC:-N0FArXU6wKsFPpi5tGA:bjesgho) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea1b2ef3d4bb303d5195222fea592d9918dca03/pkg/sql/sem/builtins/generator_probe_ranges.go#L74)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

:smile: I didn't realize we wanted to actually match 'proposing command'. Fixed.
</blockquote></details>

Wanna remove the TODO?
___
*[pkg/sql/sem/builtins/generator_probe_ranges.go, line 125 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/79546#-N0FAv9O3PbXpiNiCNNw:-N0FAv9O3PbXpiNiCNNx:buc1v3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/1521bedd2967f00a767a91c7eaea0230f551b094/pkg/sql/sem/builtins/generator_probe_ranges.go#L125)):*
> ```Go
> 	// The below are updated during calls to Next() throughout the lifecycle of
> 	// probeRangeGenerator.
> 	ops    *kvprober.ProberOps
> ```

I was thinking `ops kvprober.ProberOps` and then in `makeProbeRangeGenerator` you can omit the field since the zero value is already good to go.
___
*[pkg/sql/logictest/testdata/logic_test/generator_probe_ranges, line 14 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/79546#-N0FB1tV4oMrk2FjjqbT:-N0FB1tV4oMrk2FjjqbU:b-jm2nbl) ([raw file](https://github.com/cockroachdb/cockroach/blob/1521bedd2967f00a767a91c7eaea0230f551b094/pkg/sql/logictest/testdata/logic_test/generator_probe_ranges#L14)):*
> ```
> 
> # test that the trace has a string matching `proposing command` to verify trace events
> # from the kvserver write path are received
> ```

Nit:

```
# Test that .... are received.
```

**Review by tbg — APPROVED** [review]
I also filed https://github.com/cockroachdb/cockroach/issues/80360, which is the logical next thing to do to surface this information during troubleshooting sessions.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79546#-:-N0FCAKJ4dKfg9Bb7246:bvyrh9b)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @joshimhoff, @koorosh, @Santamaura, and @zachlite)

**Review by Santamaura — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79546)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @joshimhoff, @koorosh, @tbg, and @zachlite)

___
*[pkg/sql/sem/builtins/generator_probe_ranges.go, line 74 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/79546#-N07_5w990sqoQ2y2bhC:-N0HeTwEDc8e80jgBADC:b-ep2dlx) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea1b2ef3d4bb303d5195222fea592d9918dca03/pkg/sql/sem/builtins/generator_probe_ranges.go#L74)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Wanna remove the TODO?
</blockquote></details>

Oops forgot. Removed.
___
*[pkg/sql/sem/builtins/generator_probe_ranges.go, line 125 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/79546#-N0FAv9O3PbXpiNiCNNw:-N0HeVmCAooGnT3xjH3_:b-wme84n) ([raw file](https://github.com/cockroachdb/cockroach/blob/1521bedd2967f00a767a91c7eaea0230f551b094/pkg/sql/sem/builtins/generator_probe_ranges.go#L125)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I was thinking `ops kvprober.ProberOps` and then in `makeProbeRangeGenerator` you can omit the field since the zero value is already good to go.
</blockquote></details>

:thumbsup: done.
___
*[pkg/sql/logictest/testdata/logic_test/generator_probe_ranges, line 14 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/79546#-N0FB1tV4oMrk2FjjqbT:-N0HeadGDF6_kLvFgxWz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1521bedd2967f00a767a91c7eaea0230f551b094/pkg/sql/logictest/testdata/logic_test/generator_probe_ranges#L14)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Nit:

```
# Test that .... are received.
```
</blockquote></details>

Done.

**Comment by joshimhoff** [comment]
I wonder if this tool would be available during a full cluster SQL outage such as the recent one involving a down `system.lease`? Maybe I'll run a test today!

**Comment by joshimhoff** [comment]
It worked fine:

```
root@:26257/?> select range_id, error, end_to_end_latency_ms from crdb_internal.probe_ranges(INTERVAL '1s', 'write');
  range_id | error | end_to_end_latency_ms
-----------+-------+------------------------
         1 |       |                    21
         2 |       |                    37
         3 |       |                    36
         4 |       |                    36
         5 |       |                    37
         6 |       |                    35
         7 | boom  |         9223372036854
         8 |       |                    34
         9 |       |                    36
        10 |       |                    37
        11 |       |                    35
        12 |       |                    36
        13 |       |                    35
        14 |       |                    36
        15 |       |                    18
        16 |       |                    36
        17 |       |                    37
        18 |       |                    36
        19 |       |                    35
        20 |       |                    37
        21 |       |                    35
        22 |       |                    35
        23 |       |                    37
        24 |       |                    35
        25 |       |                    36
        26 |       |                    36
        27 |       |                    36
        28 |       |                    38
        29 |       |                    35
        30 |       |                    35
        31 |       |                    36
        32 |       |                    35
        33 |       |                    35
        34 |       |                    36
        35 |       |                    35
        36 |       |                    35
        37 |       |                    37
        38 |       |                    35
        39 |       |                    35
        40 |       |                    36
        41 |       |                    35
        42 |       |                    36
        43 |       |                    35
        54 |       |                    36
        64 |       |                    36
(45 rows)
```

Here is the change I made locally to test:

```
~/g/s/g/c/cockroach [master] $ git diff
diff --git a/pkg/kv/kvserver/replica_send.go b/pkg/kv/kvserver/replica_send.go
index 3295886e91..78ccc46b7f 100644
--- a/pkg/kv/kvserver/replica_send.go
+++ b/pkg/kv/kvserver/replica_send.go
@@ -126,6 +126,10 @@ func (r *Replica) sendWithoutRangeID(
 ) (_ *roachpb.BatchResponse, rErr *roachpb.Error) {
        var br *roachpb.BatchResponse
 
+       if ba.RangeID == 7 {
+               return nil, roachpb.NewError(errors.New("boom"))
+       }
+
        if r.leaseholderStats != nil && ba.Header.GatewayNodeID != 0 {
                r.leaseholderStats.RecordCount(r.getBatchRequestQPS(ctx, ba), ba.Header.GatewayNodeID)
        }
```

I'm going to keep exploring this Q, but I'll hold off on posting anything, unless I learn something interesting.

**Comment by joshimhoff** [comment]
Maybe I'll write an integration test that makes all system ranges that we don't expect to be hard deps of `crdb_internal.probe_range` unavailable and sees what happens. Not sure if we should merge it, but it'll be fun at least.

**Comment by joshimhoff** [comment]
With all ranges with range IDs >= 2 unavailable, connecting to an insecure five node cluster + querying `crdb_internal.probe_range` is possible.

```
root@:26257/defaultdb> select range_id, error from crdb_internal.probe_ranges(INTERVAL '1s', 'write');
  range_id | error
-----------+--------
         1 |
         2 | boom
         3 | boom
         4 | boom
         5 | boom
         6 | boom
         7 | boom
         8 | boom
         9 | boom
        10 | boom
        11 | boom
        12 | boom
        13 | boom
        14 | boom
        15 | boom
        16 | boom
        17 | boom
        18 | boom
        19 | boom
        20 | boom
        21 | boom
        22 | boom
        23 | boom
        24 | boom
        25 | boom
        26 | boom
        27 | boom
        28 | boom
        29 | boom
        30 | boom
        31 | boom
        32 | boom
        33 | boom
        34 | boom
        35 | boom
        36 | boom
        37 | boom
        38 | boom
        39 | boom
        40 | boom
        41 | boom
        42 | boom
        43 | boom
        44 | boom
(44 rows)


Time: 68ms total (execution 68ms / network 0ms)
```

OTOH, if range with range ID = 1 is down also, we get an error. This makes sense, since probing requires an available meta2 range.

```
root@:26257/defaultdb> select range_id, error from crdb_internal.probe_ranges(INTERVAL '1s', 'write');
ERROR: boom
```

This is really awesome!

Some Qs:

1. Have we considered backporting this? I feel pretty confident that having this in CC will both improve time to fix and reduce bogus KV escalations.
2. Does anyone here have desired for me to write an integration test to make sure we maintain the nice availability property of `crdb_internal.probe_range`? The property is: `crdb_internal.probe_range` should be available unless meta2 is down.
3. Will connecting to a secure cluster work, assuming I use the root user plus a client credential, regardless of what ranges are down? I hope so.

**Comment by joshimhoff** [comment]
Tiny follow up: https://github.com/cockroachdb/cockroach/pull/81107

**Comment by joshimhoff** [comment]
> If all ranges but meta2 are down, will connecting to a secure cluster work, assuming I use the root user plus a client credential? I hope so.

I tested this. I could connect as root with root client credentials. Even with all ranges down including meta2. Yay! And this comment confirms that this behavior is a design goal:

> // - if the user is root, the user is reported to exist immediately
//   without querying system.users at all. The password retrieval
//   is delayed until actually needed by the authentication method.
//   This way, if the client presents a valid TLS certificate
//   the password is not even needed at all. This is useful for e.g.
//   `cockroach node status`.

**Comment by jreut** [comment]
@Santamaura Is it possible to backport this function to v22.1? We would love to use it sooner than later!

**Comment by Santamaura** [comment]
> @Santamaura Is it possible to backport this function to v22.1? We would love to use it sooner than later!

Sure, backport PR has been opened.

**Comment by jreut** [comment]
> > @Santamaura Is it possible to backport this function to v22.1? We would love to use it sooner than later!
> 
> Sure, backport PR has been opened.

Out of curiosity, could I have done this myself? Are there docs I should have read first?

**Comment by Santamaura** [comment]
I made the backport via our backport tool doc on backports is here: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/900005932/Backporting+a+change+to+a+release+branch

So for this particular PR possibly (since there were no complicated merge conflicts) for large PRs it's usually better for the author to do it since they have better context.

**Comment by joshimhoff** [comment]
Assuming not difficult, can we also backport to 21.2? Thanks for this great tool.

**Comment by Santamaura** [comment]
Sorry @joshimhoff was working on something and completely forgot about the 21.2 backport request, I've opened one now.

**Pull request merged**
