### PR TITLE
cli: adding column redaction to selected system and crdb_internal tables

### PR DESCRIPTION
**Pull request by kousiknath**
DB dump tables contain un-redacted information which might contain crucial customer
data like hostname / ip addresses etc. Some of these table data is served to debug zip
through APIs. But many self hosted customers would not like to pass these information
out of their network. This PR solves this issue and introduces un-redacted query
support for few of such tables.

Epic: https://cockroachlabs.atlassian.net/browse/CRDB-19369
Release note: None

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121448)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @kousiknath)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121448#-NuP0BrYCULuVaIzDK_D):*
Commit message should contain detailed description of change and a release note.

On CRDB PRs we link to the github issue, not the Jira ticket since this is a public repo. Use the text `Part of: #87487` to link it to the issue. I assume there will be more work to be done for that ticket, otherwise use `Fixes: #xxx` so that merging the PR closes the ticket.

**Review by abarganier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121448)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @kousiknath)

___
*[`pkg/cli/zip_table_registry.go` line 457 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121448#-NuPDds47cCgSVQ5PGzR:-NuPDds47cCgSVQ5PGzS:bn2mv15) ([raw file](https://github.com/cockroachdb/cockroach/blob/4865fa98243bb4e72ceeaa66912ad2f2609f0947/pkg/cli/zip_table_registry.go#L457)):*
> ```Go
> 		// `env` column can contain sensitive node environment variable values,
> 		// such as AWS_ACCESS_KEY.
> 		customQueryUnredacted: `SELECT 
> ```

nit: If `customQueryRedacted` is defined, and there's no special query required for the *un*redacted case, then we don't need to define `customQueryUnredacted`.

This is because in the absence of `customQueryUnredacted`, the code using this config will simply do a `SELECT * FROM <table>`, which should have the same result. 



_Code quote:_
```Go
		customQueryUnredacted: `SELECT
```
___
*[`pkg/cli/zip_table_registry.go` line 480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121448#-NuPE0aJ7yxv467R9N5e:-NuPE0aJ7yxv467R9N5f:b-6w7m2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/4865fa98243bb4e72ceeaa66912ad2f2609f0947/pkg/cli/zip_table_registry.go#L480)):*
> ```Go
> 			FROM crdb_internal.kv_node_status
> 		`,
> 		customQueryRedacted: `SELECT 
> ```

nit: In the comments for this table, we note that the `env` column is sensitive and redacted.

Since we're now adding a custom redacted query, can we include the `env` column similar to how we do for the other redacted columns? e.g. `<redacted> AS env`. 



_Code quote:_
```Go
		customQueryRedacted: `SELECT
```
___
*[`pkg/cli/zip_table_registry.go` line 702 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121448#-NuPEPcY4UoDj1Z-__nJ:-NuPEPcZEIdHf8Q-syG2:b-uv743w) ([raw file](https://github.com/cockroachdb/cockroach/blob/4865fa98243bb4e72ceeaa66912ad2f2609f0947/pkg/cli/zip_table_registry.go#L702)):*
> ```Go
> 				node_id, 
> 				network, 
> 				'<redacted>' as address, 
> ```

nit: Small comments explaining why each field is redacted would be helpful. We can just note that this is motivated by redaction of hostnames. 



_Code quote:_
```Go
				'<redacted>' as address,
```
___
*[`pkg/cli/zip_table_registry.go` line 840 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121448#-NuPE_C6CvfEcLJFmiIc:-NuPE_C6CvfEcLJFmiId:b-ze6323) ([raw file](https://github.com/cockroachdb/cockroach/blob/4865fa98243bb4e72ceeaa66912ad2f2609f0947/pkg/cli/zip_table_registry.go#L840)):*
> ```Go
> 	},
> 	"crdb_internal.node_runtime_info": {
> 		customQueryRedacted: `SELECT * FROM (
> ```

nit: the indentation looks off in this query. Query looks good, though! 
___
*[`pkg/cli/zip_table_registry.go` line 1333 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121448#-NuPEoKmBDYEZvui0jLE:-NuPEoKmBDYEZvui0jLF:byw21yx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4865fa98243bb4e72ceeaa66912ad2f2609f0947/pkg/cli/zip_table_registry.go#L1333)):*
> ```Go
> 				"locality"
> 			FROM system.sql_instances
> 		`,
> ```

nit: ditto here, we don't need to define `customQueryUnredacted` when we have `customQueryRedacted`. This is partially my fault, I could have made this clearer in the comments on the struct. 



_Code quote:_
```Go
		customQueryUnredacted: `SELECT
				"id",
				"addr",
				"session_id",
				"locality"
			FROM system.sql_instances
		`,
```

**Review by kousiknath — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121448)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @kousiknath)

___
*[`pkg/cli/zip_table_registry.go` line 480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121448#-NuPE0aJ7yxv467R9N5e:-NuSrCRt10Ryr2I7H0CA:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4865fa98243bb4e72ceeaa66912ad2f2609f0947/pkg/cli/zip_table_registry.go#L480)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: In the comments for this table, we note that the `env` column is sensitive and redacted.

Since we're now adding a custom redacted query, can we include the `env` column similar to how we do for the other redacted columns? e.g. `<redacted> AS env`.
</blockquote></details>

Done
___
*[`pkg/cli/zip_table_registry.go` line 702 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121448#-NuPEPcY4UoDj1Z-__nJ:-NuSvCYl8kn8grBOun4J:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4865fa98243bb4e72ceeaa66912ad2f2609f0947/pkg/cli/zip_table_registry.go#L702)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: Small comments explaining why each field is redacted would be helpful. We can just note that this is motivated by redaction of hostnames.
</blockquote></details>

Done
___
*[`pkg/cli/zip_table_registry.go` line 840 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121448#-NuPE_C6CvfEcLJFmiIc:-NuSwfM208hwag3YFckr:bee7qp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4865fa98243bb4e72ceeaa66912ad2f2609f0947/pkg/cli/zip_table_registry.go#L840)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: the indentation looks off in this query. Query looks good, though!
</blockquote></details>

Changed the indentation.
___
*[`pkg/cli/zip_table_registry.go` line 1333 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121448#-NuPEoKmBDYEZvui0jLE:-NuSwnXd9cwsvE7_EwGf:b-hahrlw) ([raw file](https://github.com/cockroachdb/cockroach/blob/4865fa98243bb4e72ceeaa66912ad2f2609f0947/pkg/cli/zip_table_registry.go#L1333)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: ditto here, we don't need to define `customQueryUnredacted` when we have `customQueryRedacted`. This is partially my fault, I could have made this clearer in the comments on the struct.
</blockquote></details>

I see there are some extra columns added to table - `crdb_region` (BYTES) , `binary_version` (STRING) which are omitted in this redacted query. Since we are not using custom unredacted query, those columns will be by default included in the unredacted result. So, shouldn't we include these columns in redacted query too ? @abarganier

**Review by abarganier — COMMENTED** [review]
Looking better! 

To test these changes, you'll need to re-record the datadriven tests in `pkg/cli/zip_test.go` and `pkg/cli/zip_tenant_test.go`, and verify that the diffs made to the recorded test files (if any) look correct. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121448#-:-NuUVnFSD3s5J3PDLk7e:b-qd5lq4)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @kousiknath)

___
*[`pkg/cli/zip_table_registry.go` line 1333 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121448#-NuPEoKmBDYEZvui0jLE:-NuUVNlg3Hz8WRCHgHRt:b-q1h2sc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4865fa98243bb4e72ceeaa66912ad2f2609f0947/pkg/cli/zip_table_registry.go#L1333)):*
<details><summary><i>Previously, kousiknath (Kousik Nath) wrote…</i></summary><blockquote>

I see there are some extra columns added to table - `crdb_region` (BYTES) , `binary_version` (STRING) which are omitted in this redacted query. Since we are not using custom unredacted query, those columns will be by default included in the unredacted result. So, shouldn't we include these columns in redacted query too ? @abarganier
</blockquote></details>

Ah, this is a result of the columns/queries becoming out of date with changes made to the system table schema.

In order to add these columns to the redacted query, we first need to determine if they *need* redaction or not. That work to audit the table is out of scope for this PR, I think.

**Review by kousiknath — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121448)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)

___
*[`pkg/cli/zip_table_registry.go` line 1333 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121448#-NuPEoKmBDYEZvui0jLE:-NucFyxOCa_TholKziZ1:bmpa519) ([raw file](https://github.com/cockroachdb/cockroach/blob/4865fa98243bb4e72ceeaa66912ad2f2609f0947/pkg/cli/zip_table_registry.go#L1333)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Ah, this is a result of the columns/queries becoming out of date with changes made to the system table schema.

In order to add these columns to the redacted query, we first need to determine if they *need* redaction or not. That work to audit the table is out of scope for this PR, I think.
</blockquote></details>

By the name of these columns, it does not look like the columns need any redaction. These columns will be included in the unredacted query, but not in the redacted query unless we mention here. So, the question is more about parity of the queries here.

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121448)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @kousiknath)

___
*[`-- commits` line 5 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/121448#-NuiSH9H7rQTOC__AqTz):*
commit updates on CRDB are always squashed before merge.
___
*[`-- commits` line 8 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/121448#-NuiSNz04m7hlEg6xkzo):*
This should be a separate PR. The description and message here is too generic and should contain more detail.
___
*[`pkg/server/status.go` line 2354 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/121448#-NuiSx7C4k5Qc1ZQrryt:-NuiSx7C4k5Qc1ZQrryu:b9tsrdz) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d9294a7bd72a840fca3a94d312f70812f7834b9/pkg/server/status.go#L2354)):*
> ```Go
> 	}
> 
> 	return resp
> ```

lots of changes in this file with no tests. please add them for each modified request.

One thing that might help is `testutils.RunTrueAndFalse` which is a helper you can leverage to test with and without redaction.
___
*[`pkg/server/serverpb/status.proto` line 95 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/121448#-NuiSioR8zIgJiJOwr--:-NuiSioR8zIgJiJOwr-0:b-iplsfp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d9294a7bd72a840fca3a94d312f70812f7834b9/pkg/server/serverpb/status.proto#L95)):*
> ```proto
>   string node_id = 1;
>   reserved 2;
>   bool redacted = 3;
> ```

Field should have docstring on every proto.

**Review by abarganier — COMMENTED** [review]
Not much to add on top of what David already said. I agree we should split the API stuff into a separate PR to help keep conversations/scope of changes focused. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121448#-:-Nuiseb1-sFoh72DStJA:bc7ueg7)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @kousiknath)

___
*[`pkg/cli/zip_table_registry.go` line 1333 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121448#-NuPEoKmBDYEZvui0jLE:-NuisArXAZqZtzWhn6jN:b-e1tqk4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4865fa98243bb4e72ceeaa66912ad2f2609f0947/pkg/cli/zip_table_registry.go#L1333)):*
<details><summary><i>Previously, kousiknath (Kousik Nath) wrote…</i></summary><blockquote>

By the name of these columns, it does not look like the columns need any redaction. These columns will be included in the unredacted query, but not in the redacted query unless we mention here. So, the question is more about parity of the queries here.
</blockquote></details>

I think that's fine for now - introducing new columns into the redacted data is out of scope for this PR in my opinion.
___
*[`pkg/server/serverpb/status.proto` line 95 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/121448#-NuisRA_D_YMDcmytUYt:-NuisRA_D_YMDcmytUYu:b-xtgq6z) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d9294a7bd72a840fca3a94d312f70812f7834b9/pkg/server/serverpb/status.proto#L95)):*
> ```proto
>   string node_id = 1;
>   reserved 2;
>   bool redacted = 3;
> ```

nit: can we change this and the others to `redact` instead of `redacted`? 



_Code quote:_
```proto
  bool redacted = 3;
```

**Review by kousiknath — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121448)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[`-- commits` line 5 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/121448#-NuiSH9H7rQTOC__AqTz):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

commit updates on CRDB are always squashed before merge.
</blockquote></details>

This PR was supposed be a draft PR, not a final one, my bad I did not convert it to Draft earlier. It's still WIP. I just wanted to get some preliminary feedback so that we don't end up taking a complete detour just in case. I have converted it to Draft PR and will add test cases and other stuffs as necessary.
___
*[`pkg/server/status.go` line 2354 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/121448#-NuiSx7C4k5Qc1ZQrryt:-NuwKN7j2fcEQzO2TRsT:brouy0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d9294a7bd72a840fca3a94d312f70812f7834b9/pkg/server/status.go#L2354)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

lots of changes in this file with no tests. please add them for each modified request.

One thing that might help is `testutils.RunTrueAndFalse` which is a helper you can leverage to test with and without redaction.
</blockquote></details>

This is a Draft PR, I am working on them.

**Review by kousiknath — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121448)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[`pkg/server/serverpb/status.proto` line 95 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/121448#-NuiSioR8zIgJiJOwr--:-Nux09JDEqLZry0DhALf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d9294a7bd72a840fca3a94d312f70812f7834b9/pkg/server/serverpb/status.proto#L95)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Field should have docstring on every proto.
</blockquote></details>

Done.

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121448)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @kousiknath)

___
*[`pkg/server/status.go` line 2345 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/121448#-Nv8xjci6-bsvPmg9y3a:-Nv8xjci6-bsvPmg9y3b:b-c5yj9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d9294a7bd72a840fca3a94d312f70812f7834b9/pkg/server/status.go#L2345)):*
> ```Go
> }
> 
> func (s *statusServer) redactRangesResponse(resp *serverpb.RangesResponse) *serverpb.RangesResponse {
> ```

I think something a bit more structured would help here. If you're working with protobufs anyway, add a custom annotation to the fields that require redaction like is done here for example:
https://github.com/cockroachdb/cockroach/blob/d0d20afec038752e60aa16e80ec9093980e4a8fd/pkg/util/log/eventpb/telemetry.proto#L46-L57

Then you can iterate over the generic message and redact fields as necessary.

Alternatively, you could have a `RedactableProto` interface that has a single method: `Redact()` that redacts the fields. There could be a default implementation for each object that's a no-op.

**Review by kousiknath — COMMENTED** [review]
Regarding testing, I don't see any test files is changed after the changes. They are as they are. Is there any way to actually run this in  local? or the better way is to merge to master and then check in stage?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121448#-:-Nvp_4dyEgG8Ynx4DIOD:bct31a3)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)

___
*[`-- commits` line 8 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/121448#-NuiSNz04m7hlEg6xkzo):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

This should be a separate PR. The description and message here is too generic and should contain more detail.
</blockquote></details>

Done.

**Review by kousiknath — COMMENTED** [review]
@abarganier @dhartunian I tested the changes in local and updated the result in the ticket: https://cockroachlabs.atlassian.net/browse/CRDB-19369?focusedCommentId=223182 

Could you please approve the PR unless I am not missing anything here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121448#-:-NwAZtvH4e7Lo0dB-DKb:b37rm1r)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)

**Review by abarganier — APPROVED** [review]
:lgtm: modulo one small nit. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121448#-:-NwAeXoFETtIXZM_ukeC:b-xaw2yr)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dhartunian and @kousiknath)

___
*[`pkg/cli/zip_table_registry.go` line 696 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/121448#-NwAe1o146FsrNFSRyHm:-NwAe1o146FsrNFSRyHn:bhrjitv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab5c60d625e42d38bdf5ff922a65d32de43de45c/pkg/cli/zip_table_registry.go#L696)):*
> ```Go
> 				started_at, 
> 				is_live, 
> 				ranges, leases
> ```

nit: newline for each column name



_Code quote:_
```Go
				ranges, leases
```

**Pull request merged**
