### PR TITLE
opt: Add support for building filters in the `Expr` tree

### PR DESCRIPTION
**Pull request by rytaft**
This commit continues the work of supporting relational operators
when building expressions for the optimizer. We now support
queries which contain filters in the `WHERE` clause, such as
`SELECT * FROM t WHERE x > 5`.

As part of this change, we are adding the concept of `scope`, which
is a representation of the query tree. `scope` allows us to walk
through the query tree to perform name resolution and type checking.
It also allows us to propagate the unique representation of a column,
a `columnProps` object, throughout the query tree.

This code is based on code originally written by @petermattis in the
opttoy project.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/opt/scope.go, line 29 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-L2RNs9tyfv4NmCLPYKd:-L2RNs9tyfv4NmCLPYKe:bkfvvmz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a04a6459949a6d01cc983302f9022db30f7c07c/pkg/sql/opt/scope.go#L29)):*
> ```Go
> type scope struct {
> 	parent *scope
> 	props  *relationalProps
> ```

Note that the `v4` approach takes a different approach and puts `props.columns` in here directly. Arguably that approach is more correct as we need a list of columns with names during name resolution, but after the expr-tree has been built the `relationalProps` only needs bitmaps. Part of the reason for using `relationalProps` here in `opttoy/v3` was convenience.

Cc @andy-kimball

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352)*

**Comment by petermattis** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/expr.go, line 99 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-L2RrSBwridNpYMMXpbz:-L2RrSBwridNpYMMXpc-:b-6xiwm0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a04a6459949a6d01cc983302f9022db30f7c07c/pkg/sql/opt/expr.go#L99)):*
> ```Go
> 	// Optional filters. Filters are boolean expressions usually found in the
> 	// WHERE clause or HAVING clause (e.g., WHERE x < 5).
> 	filters []*Expr
> ```

I'm not sure about this as an intermediate step. We want to have filters stored in `children`. I realize there is more stuff to pull over to make that happen, but a reviewer would get an understanding seeing this field here which will quickly be broken.

The `exprLayout` code is relatively contained. I think we should add it now. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352)*

**Comment by rytaft** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/expr.go, line 99 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-L2RrSBwridNpYMMXpbz:-L2RseSUaR144iRa9Arc:b-if96m9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a04a6459949a6d01cc983302f9022db30f7c07c/pkg/sql/opt/expr.go#L99)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm not sure about this as an intermediate step. We want to have filters stored in `children`. I realize there is more stuff to pull over to make that happen, but a reviewer would get an understanding seeing this field here which will quickly be broken.

The `exprLayout` code is relatively contained. I think we should add it now. 
</blockquote></details>

I found the `exprLayout` code and corresponding `aux` functions a bit confusing/convoluted, which is why I avoided adding them.  But as a go newbie I'm probably missing something important.  Why do the filters and other auxiliary expressions need to be in children?

---

*[pkg/sql/opt/scope.go, line 29 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-L2RNs9tyfv4NmCLPYKd:-L2RqH54FUO-ELUwICA_:b-obd7m6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a04a6459949a6d01cc983302f9022db30f7c07c/pkg/sql/opt/scope.go#L29)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Note that the `v4` approach takes a different approach and puts `props.columns` in here directly. Arguably that approach is more correct as we need a list of columns with names during name resolution, but after the expr-tree has been built the `relationalProps` only needs bitmaps. Part of the reason for using `relationalProps` here in `opttoy/v3` was convenience.

Cc @andy-kimball
</blockquote></details>

The issue with putting the `[]columnProps` here directly and removing them from `relationalProps` is that we don't have a good way of accessing the name for printing.  `v4` seems to be getting around the issue by storing it as metadata.  Should we adopt this approach as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352)*

**Comment by petermattis** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/expr.go, line 99 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-L2RrSBwridNpYMMXpbz:-L2RuLDmkKwI6Doy05g_:b-eq40kg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a04a6459949a6d01cc983302f9022db30f7c07c/pkg/sql/opt/expr.go#L99)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I found the `exprLayout` code and corresponding `aux` functions a bit confusing/convoluted, which is why I avoided adding them.  But as a go newbie I'm probably missing something important.  Why do the filters and other auxiliary expressions need to be in children?
</blockquote></details>

The `exprLayout` idea definitely evolved over time. It is allowing each operator to specify the layout of children. This is more regular efficient and clean than allowing each operator to add fields to `expr`. Consider what happens when you add `projections`, `aggregations`, `grouping`, etc.

The details of `exprLayout` are not too bad. Each operator has a variable number of `input` expressions and a fixed number of auxiliary expressions. The auxiliary expressions always occur at the end of the `expr.children` slice.  Auxiliary children are only present for operators which have a fixed number of inputs and relational operators have at most 2 children so the indexing is simple. Consider `select`: it has 1 input and 1 auxiliary expression (the filters). The input occurs at `expr.children[0]` while the filters are stored at `expr.children[1]`. The corresponding `exprLayout` looks like:

```
func (selectClass) layout() exprLayout {
	return exprLayout{
		filters: 1,
	}
}
```

I can describe this more in person if necessary.

---

*[pkg/sql/opt/scope.go, line 29 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-L2RNs9tyfv4NmCLPYKd:-L2Ru1mIhzV4NLXzPfJY:btlsnjs) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a04a6459949a6d01cc983302f9022db30f7c07c/pkg/sql/opt/scope.go#L29)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

The issue with putting the `[]columnProps` here directly and removing them from `relationalProps` is that we don't have a good way of accessing the name for printing.  `v4` seems to be getting around the issue by storing it as metadata.  Should we adopt this approach as well?
</blockquote></details>

For this PR, I'd propose that we store the column props both here and in `relationalProps`. Then we can follow up with something similar to the approach in `v4` where we remove the columns from `relationalProps` and use another method for printing. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352)*

**Comment by knz** [comment]
I would probably enjoy reviewing this but given how many areas are being touched I would prefer an interactive review (i.e. talking over the code together so I can more easily ask questions.) If you consider this acceptable, please get in touch :)

**Comment by rytaft** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/expr.go, line 99 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-L2RrSBwridNpYMMXpbz:-L2SB2QCLzTBjpgYvBoQ:bl3sgzb) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a04a6459949a6d01cc983302f9022db30f7c07c/pkg/sql/opt/expr.go#L99)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The `exprLayout` idea definitely evolved over time. It is allowing each operator to specify the layout of children. This is more regular efficient and clean than allowing each operator to add fields to `expr`. Consider what happens when you add `projections`, `aggregations`, `grouping`, etc.

The details of `exprLayout` are not too bad. Each operator has a variable number of `input` expressions and a fixed number of auxiliary expressions. The auxiliary expressions always occur at the end of the `expr.children` slice.  Auxiliary children are only present for operators which have a fixed number of inputs and relational operators have at most 2 children so the indexing is simple. Consider `select`: it has 1 input and 1 auxiliary expression (the filters). The input occurs at `expr.children[0]` while the filters are stored at `expr.children[1]`. The corresponding `exprLayout` looks like:

```
func (selectClass) layout() exprLayout {
	return exprLayout{
		filters: 1,
	}
}
```

I can describe this more in person if necessary.
</blockquote></details>

Fair enough - the `exprLayout` code isn't *that* complex, and it's reasonably contained.  But just so I understand, why is it better than having a separate field for each type of auxiliary expression?  If we don't want to clutter `Expr` with extra fields, we could add a separate structure like this:

```
type Expr struct {
  ...
  children []*Expr
  auxExprs *auxiliaryExprs
  ...
}

type auxiliaryExprs struct { 
  filters []*Expr
  ...
}
```

It seems like there are only 5 different types of auxiliary expressions (at least that's the case in `opttoy/v3` at the moment), so it's not that crazy to have a field for each of them.  And this way the operators wouldn't need to each have a `layout()` function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352)*

**Comment by knz** [comment]
After a good night's sleep I had another look and actually I understand this all right. It's rather clear.

LGTM for the code as-is, unless Peter things there must be further structural changes which I can then subsequently re-review.

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/relational_props.go, line 83 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-L2VPKhw-MBJ7X-RkPCU:-L2VPKhx0V3mKA2aEJ5I:b-kqd283) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a04a6459949a6d01cc983302f9022db30f7c07c/pkg/sql/opt/relational_props.go#L83)):*
> ```Go
> func (c columnProps) String() string {
> 	if c.name == "" {
> 		return fmt.Sprintf("%d", c.indexedVar)
> ```

We use "@d" to represent numeric variable references - This disambiguates numeric literals from variable references in printouts.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-:-L2VPuGM97n2mfzuszZl:bry3h3w)*

**Comment by rytaft** [comment]
Great - thanks for the review!

---

Review status: 7 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/opt/scope.go, line 29 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-L2RNs9tyfv4NmCLPYKd:-L2VQs0yx9CxIUJgMcf8:b-7njdar) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a04a6459949a6d01cc983302f9022db30f7c07c/pkg/sql/opt/scope.go#L29)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

For this PR, I'd propose that we store the column props both here and in `relationalProps`. Then we can follow up with something similar to the approach in `v4` where we remove the columns from `relationalProps` and use another method for printing. 
</blockquote></details>

Sounds good - done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-:-L2VR4SxJPJs6GIAZKYu:b-6gn8kp)*

**Comment by petermattis** [comment]
Review status: 7 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/expr.go, line 99 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-L2RrSBwridNpYMMXpbz:-L2VQ5_zHAVyj_tebGvA:b-n5bfyu) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a04a6459949a6d01cc983302f9022db30f7c07c/pkg/sql/opt/expr.go#L99)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Fair enough - the `exprLayout` code isn't *that* complex, and it's reasonably contained.  But just so I understand, why is it better than having a separate field for each type of auxiliary expression?  If we don't want to clutter `Expr` with extra fields, we could add a separate structure like this:

```
type Expr struct {
  ...
  children []*Expr
  auxExprs *auxiliaryExprs
  ...
}

type auxiliaryExprs struct { 
  filters []*Expr
  ...
}
```

It seems like there are only 5 different types of auxiliary expressions (at least that's the case in `opttoy/v3` at the moment), so it's not that crazy to have a field for each of them.  And this way the operators wouldn't need to each have a `layout()` function.
</blockquote></details>

`exprLayout` is a somewhat low-level optimization, but it is significant when you consider how frequently we'll be creating these `Expr` structures during optimization. The most number of auxiliary expressions for an operator is 2 (`groupBy`). `join`, `project` and `select` have only 1 auxiliary expression and all other operators have 0. Effort has been made to keep `Expr` small and the addition of `Expr.auxiliaryExprs` is non-trivial. Also keep in mind that `sizeof([]*Expr) == 24` so that `auxiliaryExprs` structure itself would be a bit bloated.

Outside of performance considerations, separating auxiliary expressions would make certain work in the memo more tedious because we want to loop over all children independent of whether they are inputs or auxiliary expressions. 

Adding a `layout()` function per operator doesn't seem that onerous.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352)*

**Comment by petermattis** [comment]
Review status: 7 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/scope.go, line 72 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-L2VT9QCix_DT3n4ChFj:-L2VT9QCix_DT3n4ChFk:b2pjahl) ([raw file](https://github.com/cockroachdb/cockroach/blob/86cb2afd99db3ba388454919e56ed1bed340d223/pkg/sql/opt/scope.go#L72)):*
> ```Go
> 				col := &s.cols[i]
> 				if col.hasColumn(tblName, colName) {
> 					if tblName == "" && col.table != "" {
> ```

Can you add a `TODO(peter): what is this doing?` here. We're "normalizing" the `tree.ColumnItem` but I don't think this is necessary anymore and this is leftover from earlier iterations of `opttoy`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352)*

**Comment by rytaft** [comment]
Review status: 7 of 9 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/expr.go, line 99 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-L2RrSBwridNpYMMXpbz:-L2VZOXOpw4aO9j58mQ0:bk3g0o5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a04a6459949a6d01cc983302f9022db30f7c07c/pkg/sql/opt/expr.go#L99)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`exprLayout` is a somewhat low-level optimization, but it is significant when you consider how frequently we'll be creating these `Expr` structures during optimization. The most number of auxiliary expressions for an operator is 2 (`groupBy`). `join`, `project` and `select` have only 1 auxiliary expression and all other operators have 0. Effort has been made to keep `Expr` small and the addition of `Expr.auxiliaryExprs` is non-trivial. Also keep in mind that `sizeof([]*Expr) == 24` so that `auxiliaryExprs` structure itself would be a bit bloated.

Outside of performance considerations, separating auxiliary expressions would make certain work in the memo more tedious because we want to loop over all children independent of whether they are inputs or auxiliary expressions. 

Adding a `layout()` function per operator doesn't seem that onerous.
</blockquote></details>

Ok - thanks for the explanation! I'll add the `exprLayout` code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352)*

**Comment by rytaft** [comment]
I've made the changes but I think we should hold off merging or going further with this PR until we make a decision about `opttoy/v3` v. `opttoy/v4`.  Most of this code will quickly become obsolete if we move forward with `v4`.

---

Review status: 1 of 11 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/expr.go, line 99 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-L2RrSBwridNpYMMXpbz:-L2WJLqQfPuZOmaP4nlY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a04a6459949a6d01cc983302f9022db30f7c07c/pkg/sql/opt/expr.go#L99)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Ok - thanks for the explanation! I'll add the `exprLayout` code.
</blockquote></details>

Done.

---

*[pkg/sql/opt/relational_props.go, line 83 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-L2VPKhw-MBJ7X-RkPCU:-L2WJP5D4aFIPmLpDGNL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a04a6459949a6d01cc983302f9022db30f7c07c/pkg/sql/opt/relational_props.go#L83)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

We use "@d" to represent numeric variable references - This disambiguates numeric literals from variable references in printouts.
</blockquote></details>

Done.

---

*[pkg/sql/opt/scope.go, line 72 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-L2VT9QCix_DT3n4ChFj:-L2WK8IDKHprbAydS8ql:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/86cb2afd99db3ba388454919e56ed1bed340d223/pkg/sql/opt/scope.go#L72)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Can you add a `TODO(peter): what is this doing?` here. We're "normalizing" the `tree.ColumnItem` but I don't think this is necessary anymore and this is leftover from earlier iterations of `opttoy`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-:-L2WKDz7q7q2ebEaTuPz:bivvq51)*

**Comment by petermattis** [comment]
:lgtm:

I'm fine with merging this as-is. I think what I'd like to see is that we adopt the v4 "factory" approach for building `Expr`. That is, building takes a `ExprFactory` interface with various methods to construct expressions of the desired types. The actual `Expr`-tree is hidden from the builder so there is no chance of the builder using the `Expr`-tree itself to aid building given us a clean separation between building (which is name resolution, type checking and semantic analysis) and the resulting output.

Probably easier to hash this out in person.

Cc @andy-kimball 

---

Review status: 1 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-:-L2WOZc53TTVvNMOjA0C:bbnyuii)*

**Comment by RaduBerinde** [comment]
Review status: 1 of 11 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/expr.go, line 83 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-L2WU19EvjVaewfvSVgm:-L2WU19EvjVaewfvSVgn:b-97k04l) ([raw file](https://github.com/cockroachdb/cockroach/blob/2819ae6b5a31357f9576e9c82b0fd99d1e44c579/pkg/sql/opt/expr.go#L83)):*
> ```Go
> //      +----| scan a |
> //           +--------+
> type Expr struct {
> ```

This description should mention how auxiliary inputs/exprLayout works

---

*[pkg/sql/opt/expr.go, line 111 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-L2WV2TfXvvwxG6BRAs5:-L2WV2TfXvvwxG6BRAs6:b-sgpvq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2819ae6b5a31357f9576e9c82b0fd99d1e44c579/pkg/sql/opt/expr.go#L111)):*
> ```Go
> // exprLayout describes the layout of auxiliary children expressions. The layout
> // is operator specific and accessed via the operatorTab table.
> type exprLayout struct {
> ```

Should mention what these int8s are (offsets into the children slice?)

---

*[pkg/sql/opt/expr.go, line 112 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-L2WV343XQsLOUCVh9i-:-L2WV343XQsLOUCVh9i0:b-v4gsxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/2819ae6b5a31357f9576e9c82b0fd99d1e44c579/pkg/sql/opt/expr.go#L112)):*
> ```Go
> // is operator specific and accessed via the operatorTab table.
> type exprLayout struct {
> 	numAux       int8 // used internally, no need to specify manually
> ```

this comment needs clarification ("no need to specify manually" doesn't mean much without some context).

---

*[pkg/sql/opt/expr.go, line 187 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-L2WURHOv7-xDlHQibXI:-L2WURHOv7-xDlHQibXJ:b-dwzlal) ([raw file](https://github.com/cockroachdb/cockroach/blob/2819ae6b5a31357f9576e9c82b0fd99d1e44c579/pkg/sql/opt/expr.go#L187)):*
> ```Go
> // aux returns the auxiliary expression(s) at location i in the children of
> // Expr e.
> func (e *Expr) aux(i int8, op operator) []*Expr {
> ```

[nit] the semantics of this function should be documented, they are not intuitive.. it returns a 1-element slice,  unless that element is `op` in which case it returns the children? An example of why this is useful would help.

---

*[pkg/sql/opt/operator.go, line 36 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-L2WTZEUT5WzfatGmwch:-L2WTZEUT5WzfatGmwci:bx99ce6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2819ae6b5a31357f9576e9c82b0fd99d1e44c579/pkg/sql/opt/operator.go#L36)):*
> ```Go
> 	scanOp
> 
> 	// selectOp is a pass-through operator, which may optionally apply filters to
> ```

I don't get the "optionally" part. When would we use a selectOp without any filter?

---

*[pkg/sql/opt/operator.go, line 53 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-L2WTnvLcLtCwP86czTL:-L2WTnvLcLtCwP86czTM:b1fpmfo) ([raw file](https://github.com/cockroachdb/cockroach/blob/2819ae6b5a31357f9576e9c82b0fd99d1e44c579/pkg/sql/opt/operator.go#L53)):*
> ```Go
> 
> 	// listOp is an operator used to combine auxiliary expressions of the same
> 	// type.  For example, multiple filters can be implicitly AND'ed together
> ```

[nit] I don't see why we wouldn't just use an `andOp` for that case.

---

*[pkg/sql/opt/operator.go, line 131 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-L2WVU6ze7nIuZNxw_w9:-L2WVU6ze7nIuZNxw_wA:bt41v9o) ([raw file](https://github.com/cockroachdb/cockroach/blob/2819ae6b5a31357f9576e9c82b0fd99d1e44c579/pkg/sql/opt/operator.go#L131)):*
> ```Go
> 	// class of the operator (see operatorClass).
> 	class operatorClass
> 	// operator-specific layout of auxiliary expressions.
> ```

Why is this both inside `class` and in here? Shouldn't we make sure every op has a class and use class.layout?

---

*[pkg/sql/opt/relational_props.go, line 83 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-L2VPKhw-MBJ7X-RkPCU:-L2WTMvigsIp2Br55Z_2:b-9ybrrm) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a04a6459949a6d01cc983302f9022db30f7c07c/pkg/sql/opt/relational_props.go#L83)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Unfortunately `@x` is 1-based so we would need `c.indexedVar+1`. Maybe we should make indexedVar 1-based too..

---

*[pkg/sql/opt/scope.go, line 24 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-L2WRq7KsMAyrNlnrvre:-L2WRq7KsMAyrNlnrvrf:b-8bizvx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2819ae6b5a31357f9576e9c82b0fd99d1e44c579/pkg/sql/opt/scope.go#L24)):*
> ```Go
> )
> 
> // scope implements the tree.Visitor interface, which allows us to
> ```

[nit] this could use a better description of what it is at a high level (what you wrote in the commit message). In there you say "which is a representation of the query tree"; how is it represented?

It feels more like a path down the query tree than a tree (not sure I'm understanding correctly how it is used though).

---

*[pkg/sql/opt/scope.go, line 53 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-L2WT88M3apQcmD-_VJv:-L2WT88M3apQcmD-_VJw:b-hp2iwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/2819ae6b5a31357f9576e9c82b0fd99d1e44c579/pkg/sql/opt/scope.go#L53)):*
> ```Go
> 
> // VisitPre is part of the tree.Visitor interface.
> // NB: This code is adapted from sql/select_name_resolution.go and
> ```

[nit] could use a description of how it modifies the Expr

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352)*

**Comment by rytaft** [comment]
Thanks for the reviews, all.  Before I address @RaduBerinde's comments/ merge this PR, I think it would be good to make sure we're all on the same page.  Based on my meeting with @andy-kimball this morning, it sounds like he thinks we should change more than just the approach to building `Expr`.  Perhaps a meeting tomorrow morning would be worthwhile?

---

Review status: 1 of 11 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-:-L2WYa4dRINkxElX5xpm:b-uyokhj)*

**Comment by petermattis** [comment]
> Perhaps a meeting tomorrow morning would be worthwhile?

Done.

---

Review status: 1 of 11 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-:-L2WiRj0VtcVuOGRi4Hk:b8le95p)*

**Comment by rytaft** [comment]
:thumbsup: 

---

Review status: 1 of 11 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-:-L2Wk97Mt3mhnGkR7mOR:b4c9lyr)*

**Comment by RaduBerinde** [comment]
It would help the planNode conversion work to merge this, even if things will change soon. What do you think? (CC @andy-kimball too). You can skip addressing my comments though (except maybe correcting `@0` to `@1`)

**Comment by rytaft** [comment]
@RaduBerinde I've made a few of your suggested changes.  I'm holding off on addressing the comments related to documentation of `exprLayout` and `scope`, since both of those are going to change significantly very soon.

---

Review status: 0 of 11 files reviewed at latest revision, 10 unresolved discussions.

---

*[pkg/sql/opt/operator.go, line 36 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-L2WTZEUT5WzfatGmwch:-L2gF7RMjW4IeS8iufOG:b-ynwl21) ([raw file](https://github.com/cockroachdb/cockroach/blob/2819ae6b5a31357f9576e9c82b0fd99d1e44c579/pkg/sql/opt/operator.go#L36)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I don't get the "optionally" part. When would we use a selectOp without any filter?
</blockquote></details>

I removed it.

---

*[pkg/sql/opt/operator.go, line 53 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-L2WTnvLcLtCwP86czTL:-L2gEo9Wpa6jhGcs-JN_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2819ae6b5a31357f9576e9c82b0fd99d1e44c579/pkg/sql/opt/operator.go#L53)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I don't see why we wouldn't just use an `andOp` for that case.
</blockquote></details>

Done.

---

*[pkg/sql/opt/relational_props.go, line 83 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-L2VPKhw-MBJ7X-RkPCU:-L2gFEExFq9ilfly28SI:b-gs03rr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a04a6459949a6d01cc983302f9022db30f7c07c/pkg/sql/opt/relational_props.go#L83)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Unfortunately `@x` is 1-based so we would need `c.indexedVar+1`. Maybe we should make indexedVar 1-based too..
</blockquote></details>

Done. It seemed easiest to just add +1 here...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-:-L2gFQ6kQdug-OJXSH4L:b-5hot0w)*

**Comment by RaduBerinde** [comment]
:lgtm: Thanks!

---

Review status: 0 of 11 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21352#-:-L2gKLq8x4wGX1fT890F:b-g2a5fb)*

**Pull request merged**
