### PR TITLE
sql: misc pretty-printing fixes

### LINKED ISSUE #26920: sql: SHOW doesn't double round trip with double quotes
```
root@:26257/defaultdb> show syntax 'show "TIMEZONE"';                                                                                                         +-------+---------------+
| field |    message    |
+-------+---------------+
| sql   | SHOW TIMEZONE |
+-------+---------------+
(1 row)

Time: 502.371µs

root@:26257/defaultdb> show syntax 'show TIMEZONE';                                                                                                           
+-------+---------------+
| field |    message    |
+-------+---------------+
| sql   | SHOW timezone |
+-------+---------------+
(1 row)

Time: 445.031µs
```

SHOW SYNTAX (I hear) is supposed to return some canonical version of a syntax. `SHOW thing` will lowercase thing. Unless thing is in double quotes in which case it won't. But then if you run that through `SHOW SYNTAX` it doesn't print out the double quotes, so it doesn't double round trip. Or rather, here's a specific case where SHOW SYNTAX doesn't round trip its output exactly.

A small deal for sure, but found when testing the upcoming pretty printer.

### LINKED ISSUE #26921: sql: inverted index formats wrong
```
root@:26257/defaultdb> show syntax 'create table t (inverted index (a))';
+-------+-------------------------------------+
| field |               message               |
+-------+-------------------------------------+
| sql   | CREATE TABLE t (INDEX (a)INVERTED ) |
+-------+-------------------------------------+
(1 row)
```

### PR DESCRIPTION
**Pull request by knz**
Fixes #26920.
Fixes #26921.

### CODE REVIEW

**Review by madelynnblue — COMMENTED** [review]
Could you add a test for the third commit to illustrate what was broken?

**Comment by knz** [comment]
> Could you add a test for the third commit to illustrate what was broken?

No I can't - nothing was broken (yet). The problem being solved here is that no pretty-printing code should ever take a string for an identifier and print it as-is. The `SQLString()` API was mis-designed. This patch fixes it.

**Comment by knz** [comment]
(The risk is that in the future we find a new use of `SQLString()` where it is applied to non-simple identifiers and then the output becomes incorrect)

**Review by madelynnblue — APPROVED** [review]

**Comment by knz** [comment]
thank you

bors r+

**Pull request merged**
