### PR TITLE
rac2: exclude replicas with send-queue from quorum

### PR DESCRIPTION
**Pull request by sumeerbhola**
Also, replicas not in StateReplicate are excluded from the quorum,
as outlined in
https://docs.google.com/document/d/1ROE1lpRVhfLxP39rs8J5mKoUfgsoiJyEkUkoNPhBJUk/edit#heading=h.7c7mxg7g2gsy

Informs https://github.com/cockroachdb/cockroach/issues/130433

Epic: CRDB-37515

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
First commit is from https://github.com/cockroachdb/cockroach/pull/131413

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131432#-:-O7j4UQ48GoisKHmqrks:bnwbt6t)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/wait_for_eval_send_q` line 136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131432#-O7j4Z7t1HKiQgXKwZx_:-O7j4Z7t1HKiQgXKwZxa:b26vmhs) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffbe1555b1ba98756793cbb5ccad44de308fcc62/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/wait_for_eval_send_q#L136)):*
> ```
> ++++
> 
> # TODO: wait for eval should complete.
> ```

This is a bug that I need to fix.

**Review by sumeerbhola — COMMENTED** [review]
Rebased on master

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131432#-:-O7jzM193cqtNq9Itzfe:b-fna0si)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/wait_for_eval_send_q` line 136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131432#-O7j4Z7t1HKiQgXKwZx_:-O7jzOPtAzseGtablLpQ:b-9ihj5d) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffbe1555b1ba98756793cbb5ccad44de308fcc62/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/wait_for_eval_send_q#L136)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This is a bug that I need to fix.
</blockquote></details>

Bug is fixed

**Review by kvoli — APPROVED** [review]
:lgtm:

> Reviewed 6 of 7 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131432#-:-O7k6cob76lMp9YNh1ro:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 397 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131432#-O7jFlKO0e_UM7gE9qu9:-O7jFlKO0e_UM7gE9quA:bts7uls) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffbe1555b1ba98756793cbb5ccad44de308fcc62/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L397)):*
> ```Go
> 	replicaID roachpb.ReplicaID
> 	// !isStateReplicate replicas are not required to be waited on for
> 	// evaluating elastic work. For voters, !isStateReplicate => hasSendQ, so
> ```

nit: it wasn't immediately obvious to me why `!isStateReplicate => hasSendQ`, if it is because there will always be at least some outgoing messages required to transition the replica to `StateReplicate`, or it can only enter `!isStateReplicate` if there is some queue of messages to send.

Consider expanding this comment.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/wait_for_eval_non_voters` line 108 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131432#-O7k4yVb6jxsr3dlEQDP:-O7k4yVb6jxsr3dlEQDQ:b-l1ff03) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd8a43d7c58ad2936aa9253c5f168a22ec32b871/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/wait_for_eval_non_voters#L108)):*
> ```
> # (1) The leader has elastic tokens (already true)
> # (2) The leaseholder has elastic tokens (already true)
> # (3) A quorum of voting replicas have elastic tokens and are in StateReplicate e.g., s1 + (s2|s3)
> ```

nit: wrap line and space the start below `A quorum...`.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/wait_for_eval_not_replicate` line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131432#-O7k5O5t2qz3oNoDn5uI:-O7k5O5t2qz3oNoDn5uJ:bds3i29) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd8a43d7c58ad2936aa9253c5f168a22ec32b871/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/wait_for_eval_not_replicate#L1)):*
> ```
> # Initialize a range with voters on s1,s2 and s3. The local replica and
> ```

Nice test!
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/wait_for_eval_send_q` line 3 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131432#-O7k5k_i4cxnBGsq83iF:-O7k5k_i4cxnBGsq83iG:btn8gy3) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd8a43d7c58ad2936aa9253c5f168a22ec32b871/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/wait_for_eval_send_q#L3)):*
> ```
> # Initialize a range with voters on s1,s2 and s3. The local replica and
> # leaseholder will be s1. The leaseholder is denoted by the '*' suffix. Also
> # set all streams to initially have 1 tokens and a limit of 1 token to
> ```

nit: the regular limit and initial tokens are 8 MiB.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/wait_for_eval_send_q` line 20 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131432#-O7k60qp5HtMLAuEL_Ow:-O7k60qp5HtMLAuEL_Ox:b1980g9) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd8a43d7c58ad2936aa9253c5f168a22ec32b871/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/wait_for_eval_send_q#L20)):*
> ```
>        send reg=+8.0 MiB/+8.0 MiB ela=+1 B/+1 B
> 
> # Start a high priority evaluation. It should not complete due to lack of
> ```

Could you add `stream_state` before the `wait_for_eval` to make the send queue show up too.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller_test.go` line 454 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131432#-O7k6X7q5wQ12h8hydj2:-O7k6X7q5wQ12h8hydj3:b-bg2kdx) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd8a43d7c58ad2936aa9253c5f168a22ec32b871/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller_test.go#L454)):*
> ```Go
> 			require.True(t, strings.HasPrefix(parts[3], "next_raft_index="))
> 			parts[3] = strings.TrimPrefix(strings.TrimSpace(parts[3]), "next_raft_index=")
> 			nextRaftIndex, err = strconv.Atoi(parts[3])
> ```

:) I guess we only ever used `local_replica_id=1` and `next_raft_index=1` up until now.

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131432#-:-O7l8oqV7JVkcL6dx6Yu:b-814g8k)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kvoli)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 397 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131432#-O7jFlKO0e_UM7gE9qu9:-O7l6tet9DgGCE6LXkZH:bsljvjn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffbe1555b1ba98756793cbb5ccad44de308fcc62/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L397)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: it wasn't immediately obvious to me why `!isStateReplicate => hasSendQ`, if it is because there will always be at least some outgoing messages required to transition the replica to `StateReplicate`, or it can only enter `!isStateReplicate` if there is some queue of messages to send.

Consider expanding this comment.
</blockquote></details>

I expanded this comment. This is for the reason discussed in https://docs.google.com/document/d/1ROE1lpRVhfLxP39rs8J5mKoUfgsoiJyEkUkoNPhBJUk/edit#bookmark=id.w2r50ghkwa0m
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/wait_for_eval_non_voters` line 108 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131432#-O7k4yVb6jxsr3dlEQDP:-O7l7Oak9KU3gio6C43U:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd8a43d7c58ad2936aa9253c5f168a22ec32b871/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/wait_for_eval_non_voters#L108)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: wrap line and space the start below `A quorum...`.
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/wait_for_eval_send_q` line 3 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131432#-O7k5k_i4cxnBGsq83iF:-O7l7ppM9X9vmmYaW_a_:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd8a43d7c58ad2936aa9253c5f168a22ec32b871/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/wait_for_eval_send_q#L3)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: the regular limit and initial tokens are 8 MiB.
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/wait_for_eval_send_q` line 20 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131432#-O7k60qp5HtMLAuEL_Ow:-O7l83M4-xlzFRl4gdXd:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd8a43d7c58ad2936aa9253c5f168a22ec32b871/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/wait_for_eval_send_q#L20)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Could you add `stream_state` before the `wait_for_eval` to make the send queue show up too.
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller_test.go` line 454 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131432#-O7k6X7q5wQ12h8hydj2:-O7l86tl6zEBkY3amjQt:b32vhw) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd8a43d7c58ad2936aa9253c5f168a22ec32b871/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller_test.go#L454)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

:) I guess we only ever used `local_replica_id=1` and `next_raft_index=1` up until now.
</blockquote></details>

:)

**Comment by sumeerbhola** [comment]
pkg/ccl/testccl/workload/schemachange failure is a flake

**Comment by sumeerbhola** [comment]
bors r=kvoli

**Pull request merged**
