### PR TITLE
sql: use ContentionRegistry in DistSQLReceiver

### PR DESCRIPTION
**Pull request by asubiotto**
This PR plumbs a ContentionRegistry down to the DistSQLReceiver. `roachpb.ContentionEvent`s observed in the receiver are added to this nodelocal `ContentionRegistry`.

Release note: None

Addresses #57114

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 20 of 20 files at r1, 16 of 16 files at r2, 7 of 7 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58703#-:-MSa7XSmCLYKEZqrfv-s:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @RaduBerinde)

___
*[pkg/ccl/backupccl/backup_processor_planning.go, line 181 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58703#-MSa78t3E7S8tTattDwI:-MSa78t3E7S8tTattDwJ:b76dwmd) ([raw file](https://github.com/cockroachdb/cockroach/blob/517745439675d852b58623bc2afcbfc9123d1cd7/pkg/ccl/backupccl/backup_processor_planning.go#L181)):*
> ```Go
> 		nil,   /* clockUpdater */
> 		evalCtx.Tracing,
> 		evalCtx.ExecCfg.ContentionRegistry,
> ```

I wonder whether we should be leaving the registry as `nil` in cases when the range cache is `nil`. I guess there isn't much benefit to do so though, thoughts?

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58703)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @yuzefovich)

___
*[pkg/ccl/backupccl/backup_processor_planning.go, line 181 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58703#-MSa78t3E7S8tTattDwI:-MScGhjC5x_HwYrFnEBd:bpjdt6c) ([raw file](https://github.com/cockroachdb/cockroach/blob/517745439675d852b58623bc2afcbfc9123d1cd7/pkg/ccl/backupccl/backup_processor_planning.go#L181)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I wonder whether we should be leaving the registry as `nil` in cases when the range cache is `nil`. I guess there isn't much benefit to do so though, thoughts?
</blockquote></details>

I think these are different cases. We're probably not interested in using a range cache because we're manually planning processors here, but if this backup produces contention events, I think that's interesting to know about.

**Review by yuzefovich — APPROVED** [review]
> Reviewed 6 of 7 files at r5, 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58703)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @RaduBerinde)

___
*[pkg/ccl/backupccl/backup_processor_planning.go, line 181 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58703#-MSa78t3E7S8tTattDwI:-MSchLjQ1CA4-jeCONeU:b8uqcav) ([raw file](https://github.com/cockroachdb/cockroach/blob/517745439675d852b58623bc2afcbfc9123d1cd7/pkg/ccl/backupccl/backup_processor_planning.go#L181)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think these are different cases. We're probably not interested in using a range cache because we're manually planning processors here, but if this backup produces contention events, I think that's interesting to know about.
</blockquote></details>

Yeah, makes sense.
___
*[pkg/sql/contention/registry_test.go, line 138 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/58703#-MSchnCN2VrcBr0v_opC:-MSchnCO7R6Q4tzBngXs:bn5tcha) ([raw file](https://github.com/cockroachdb/cockroach/blob/702ebe02ab6f7b9ee09e45fcc8998a8da5c34d72/pkg/sql/contention/registry_test.go#L138)):*
> ```Go
> 	wg.Add(numGoroutines)
> 	registry := NewRegistry()
> 	errCh := make(chan error, 10)
> ```

nit: `s/10/numGoroutines/`.

**Review by asubiotto — COMMENTED** [review]
TFTR

bors r=yuzefovich

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58703#-:-MSgPSgj8zPZe6dSzpBL:bsvne40)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @RaduBerinde, and @yuzefovich)

**Pull request merged**
