### PR TITLE
sql/opt/exec: various cleanup in execbuilder

### PR DESCRIPTION
**Pull request by nvb**
This commit contains a few different cleanups I noticed while
familiarizing myself with the execbuilder structure, which I'll
need to touch for some of the upcoming SELECT FOR UPDATE work.

Release note: None

### CODE REVIEW

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43865#-:-LyCKsNv-UKqYlfAvN_S:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball)

**Comment by nvanbenschoten** [comment]
`TestExecBuild/local/select` appeared to flake due to an assumption about column families. I suspect that it fell prey to @mjibson's randomized column family injector, although I haven't been able to reproduce under stress and I don't think that secondary indexes can even have multiple column families yet.

```
testdata/select:1463: EXPLAIN SELECT b FROM b WHERE b = 10 OR b = 20
                expected:
                    ·     distributed  false
                    ·     vectorized   true
                    scan  ·            ·
                    ·     table        b@b_b_key
                    ·     spans        /10-/11 /20-/21
                    ·     parallel     ·
                    
                but found (query options: "") :
                    ·     distributed  false
                    ·     vectorized   true
                    scan  ·            ·
                    ·     table        b@b_b_key
                    ·     spans        /10/0-/10/1 /20/0-/20/1
                    ·     parallel     ·
```

**Comment by mjibson** [comment]
I think this was fixed in #43867 and is related to @rohany's recent work on column families.

**Comment by nvanbenschoten** [comment]
Ok, thanks.

bors r+

**Comment by nvanbenschoten** [comment]
Same failure. The fix is now merged.

bors r+

**Pull request merged**
