### PR TITLE
kvserver: fix and unskip TestCheckConsistencyInconsistent

### LINKED ISSUE #81819: kvserver: `TestCheckConsistencyInconsistent` failed, data race in `TestingSetRedactable`
```
=== RUN   TestCheckConsistencyInconsistent
    test_log_scope.go:79: test logs captured to: /home/erik/.cache/bazel/_bazel_erik/58b8816bb117734f0a0eaaef7fcef95b/sandbox/linux-sandbox/11283/execroot/com_github_cockroachdb_cockroach/_tmp/33e1d369c27b9c01b2b6009c561815a3/logTestCheckConsistencyInconsistent3070084177
    test_log_scope.go:80: use -show-logs to present logs inline
==================
WARNING: DATA RACE
Write at 0x00c0007d9b68 by goroutine 47:
  github.com/cockroachdb/cockroach/pkg/util/log.TestingSetRedactable.func1()
      github.com/cockroachdb/cockroach/pkg/util/log/redact.go:199 +0xe4
  github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestCheckConsistencyInconsistent()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver_test/pkg/kv/kvserver/consistency_queue_test.go:477 +0x242b
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).WaitForFullReplication()
      github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:1244 +0x4f7
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).Start()
      github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:370 +0xa24
  github.com/cockroachdb/cockroach/pkg/server.(*TestServer).Start()
      github.com/cockroachdb/cockroach/pkg/server/testserver.go:498 +0x109
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).startServer()
      github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:501 +0x10a
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).Start()
      github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:327 +0x4b5
  github.com/cockroachdb/cockroach/pkg/server.(*TestServer).Start()
      github.com/cockroachdb/cockroach/pkg/server/testserver.go:498 +0x109
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).startServer()
      github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:501 +0x10a
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).Start()
      github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:327 +0x4b5
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.StartTestCluster()
      github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:196 +0xa8
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.NewTestCluster()
      github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:292 +0xcec
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.NewTestCluster()
      github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:292 +0xcec
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.StartTestCluster()
      github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:195 +0x8b
  github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestCheckConsistencyInconsistent()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver_test/pkg/kv/kvserver/consistency_queue_test.go:336 +0x9e4
  testing.tRunner()
      GOROOT/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      GOROOT/src/testing/testing.go:1306 +0x47

Previous read at 0x00c0007d9b68 by goroutine 42:
  github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry()
      github.com/cockroachdb/cockroach/pkg/util/log/clog.go:312 +0x7f5
  github.com/cockroachdb/cockroach/pkg/util/log.logfDepth()
      github.com/cockroachdb/cockroach/pkg/util/log/channels.go:60 +0x385
  github.com/cockroachdb/cockroach/pkg/util/log.Infof()
      github.com/cockroachdb/cockroach/bazel-out/k8-fastbuild/bin/pkg/util/log/log_channels_generated.go:263 +0x1f0
  github.com/cockroachdb/cockroach/pkg/util/admission.(*GrantCoordinator).CPULoad()
      github.com/cockroachdb/cockroach/pkg/util/admission/granter.go:956 +0x3e
  github.com/cockroachdb/cockroach/pkg/util/admission.(*GrantCoordinator).CPULoad-fm()
      github.com/cockroachdb/cockroach/pkg/util/admission/granter.go:951 +0x57
  github.com/cockroachdb/cockroach/pkg/util/goschedstats.(*schedStatsTicker).getStatsOnTick()
      github.com/cockroachdb/cockroach/pkg/util/goschedstats/runnable.go:236 +0x3fa
  github.com/cockroachdb/cockroach/pkg/util/goschedstats.init.0.func1()
      github.com/cockroachdb/cockroach/pkg/util/goschedstats/runnable.go:169 +0x1c4

Goroutine 47 (running) created at:
  testing.(*T).Run()
      GOROOT/src/testing/testing.go:1306 +0x726
  testing.runTests.func1()
      GOROOT/src/testing/testing.go:1598 +0x99
  testing.tRunner()
      GOROOT/src/testing/testing.go:1259 +0x22f
  testing.runTests()
      GOROOT/src/testing/testing.go:1596 +0x7ca
  testing.(*M).Run()
      GOROOT/src/testing/testing.go:1504 +0x9d1
  github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestMain()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver_test/pkg/kv/kvserver/main_test.go:49 +0x105
  main.main()
      main/bazel-out/k8-fastbuild/bin/pkg/kv/kvserver/kvserver_test_/testmain.go:1435 +0x5c6

Goroutine 42 (running) created at:
  github.com/cockroachdb/cockroach/pkg/util/goschedstats.init.0()
      github.com/cockroachdb/cockroach/pkg/util/goschedstats/runnable.go:157 +0x2b
==================
I220525 12:44:18.543257 1 (gostd) testmain.go:1414  [-] 1  Test //pkg/kv/kvserver:kvserver_test exited with error code 66
```

Jira issue: CRDB-16183

### PR DESCRIPTION
**Pull request by pav-kv**
This PR unskips `TestCheckConsistencyInconsistent` which was skipped for a reason that no longer holds.

It also fixes the race possible in `TestCheckConsistencyInconsistent`:
- Node 2 is corrupted.
- The second phase of `runConsistency` check times out on node 1, and returns early when only nodes 2 and 3 have created the storage checkpoint.
- Node 1 haven't created the checkpoint, but has started doing so.
- Node 2 "fatals" (mocked out in the test) shortly after the check is complete.
- Node 1 is still creating its checkpoint, but has probably created the directory by now.
- Hence, the test assumes that the checkpoint has been created, and proceeds to open it and compute the checksum of the range.

The test now waits for the moment when all the checkpoint are known to be fully populated.

Fixes #81819
Epic: none
Release note: none

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
LGTM, thanks!

**Comment by pavelkalinnikov** [comment]
bors r=erikgrinaker

**Comment by pavelkalinnikov** [comment]
bors r=erikgrinaker

**Comment by pavelkalinnikov** [comment]
bors retry

**Comment by pavelkalinnikov** [comment]
bors retry

**Comment by pavelkalinnikov** [comment]
bors retry

**Pull request merged**
