### PR TITLE
sql: changed schema change backfill to not use a planner

### PR DESCRIPTION
**Pull request by vivekmenezes**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14510)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 5 of 5 files at r1, 16 of 16 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/database.go, line 152 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510#-Kg_Cpmi-nERLlUfwBPa:-Kg_Cpmi-nERLlUfwBPb:bkp1c7z) ([raw file](https://github.com/cockroachdb/cockroach/blob/1febef8b90ed3978fb4c3ec91872863077a0e51b/pkg/sql/database.go#L152)):*
> ```Go
> func (dc *databaseCache) getCachedDatabaseDesc(name string) (*sqlbase.DatabaseDescriptor, error) {
> 	if dc == nil {
> 		return nil, fmt.Errorf("database %q does not exist in empty system cache", name)
> ```

is this exercised anywhere?

---

*[pkg/sql/database.go, line 207 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510#-Kg_CxZOCccqM2gIJokP:-Kg_CxZOCccqM2gIJokQ:bpejyx4) ([raw file](https://github.com/cockroachdb/cockroach/blob/1febef8b90ed3978fb4c3ec91872863077a0e51b/pkg/sql/database.go#L207)):*
> ```Go
> }
> 
> // getDatabaseID returns the ID of a database given its name.  It
> ```

there are two spaces after the period.

---

*[pkg/sql/session.go, line 157 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510#-Kg_v_dk4hU80bUhAAFz:-Kg_v_dlbdp2fC24UygR:b-2wclen) ([raw file](https://github.com/cockroachdb/cockroach/blob/cde62b3e0c254cb9591f0776924f743f43029c7f/pkg/sql/session.go#L157)):*
> ```Go
> 	sessionMon mon.MemoryMonitor
> 
> 	// leases is the collection of leases owned by the session.
> ```

remove this comment, it's not helpful - the type is already called LeaseCollection

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 17 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/database.go, line 152 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510#-Kg_Cpmi-nERLlUfwBPa:-KgenVrS4-uIJ1uFDFE5:b-a36ue2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1febef8b90ed3978fb4c3ec91872863077a0e51b/pkg/sql/database.go#L152)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

is this exercised anywhere?
</blockquote></details>

originally the session would use a default empty systemConfig at startup. Now with the systemConfig  inside the databaseCache and the cache created with each systemConfig update, the system starts of with a nil cache initially. This error is exercised in tests and the follow is the same, the cache is nil, so the test reads the database descriptor from the kv store in getDatabaseID()

---

*[pkg/sql/database.go, line 207 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510#-Kg_CxZOCccqM2gIJokP:-KgaCZIMJo8cK95-zu2s:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1febef8b90ed3978fb4c3ec91872863077a0e51b/pkg/sql/database.go#L207)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

there are two spaces after the period.
</blockquote></details>

Done.

---

*[pkg/sql/session.go, line 157 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510#-Kg_v_dk4hU80bUhAAFz:-KgaDDstckGMx0wznPnr:byiay3j) ([raw file](https://github.com/cockroachdb/cockroach/blob/cde62b3e0c254cb9591f0776924f743f43029c7f/pkg/sql/session.go#L157)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

remove this comment, it's not helpful - the type is already called LeaseCollection
</blockquote></details>

changed the comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510)*

**Comment by tamird** [comment]
Reviewed 17 of 17 files at r3, 16 of 16 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/database.go, line 152 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510#-Kg_Cpmi-nERLlUfwBPa:-Kgf0kLEgYplyx1n2kQ9:b-4evtb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1febef8b90ed3978fb4c3ec91872863077a0e51b/pkg/sql/database.go#L152)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

originally the session would use a default empty systemConfig at startup. Now with the systemConfig  inside the databaseCache and the cache created with each systemConfig update, the system starts of with a nil cache initially. This error is exercised in tests and the follow is the same, the cache is nil, so the test reads the database descriptor from the kv store in getDatabaseID()
</blockquote></details>

Could you make that more explicit in those tests? They must be matching on the prefix currently, such that the word "empty" isn't being looked at.

---

*[pkg/sql/lease.go, line 1291 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510#-Kgf12xFwKU02pbZDmuG:-Kgf12xFwKU02pbZDmuH:bdpag1f) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccd5b706358300b6fb8140f89a4e9e2c78401fb1/pkg/sql/lease.go#L1291)):*
> ```Go
> 
> // LeaseCollection is a collection of leases held by a single session that
> // serves SQL requests, or a background job using table descriptor.
> ```

missing article after "using"

---

*[pkg/sql/session.go, line 157 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510#-Kg_v_dk4hU80bUhAAFz:-Kgf1AuOKZZ39FBBryYU:b-kf9ayq) ([raw file](https://github.com/cockroachdb/cockroach/blob/cde62b3e0c254cb9591f0776924f743f43029c7f/pkg/sql/session.go#L157)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

changed the comment
</blockquote></details>

OK, but why? The struct comment now prescribes where it is used, which is asking for rot. I would rather that comment describe only the behaviour of that structure, not its use.

Separately, I don't think this comment here is useful, but you seem to feel strongly, so I rescind my objection.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510)*

**Comment by nvanbenschoten** [comment]
Very nice refactoring! :lgtm: other than the "missing article" comment.

---

Reviewed 6 of 17 files at r3, 16 of 16 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510#-:-Kgn9dNv9cEugo0-lvE5:b-7mrtse)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 17 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/database.go, line 152 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510#-Kg_Cpmi-nERLlUfwBPa:-Kgo082SqQZ5l-cXeRcD:bc6fvt2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1febef8b90ed3978fb4c3ec91872863077a0e51b/pkg/sql/database.go#L152)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Could you make that more explicit in those tests? They must be matching on the prefix currently, such that the word "empty" isn't being looked at.
</blockquote></details>

actually this is a nil exception in tests. The error returned from here is only logged. I've changed the error message so it's very different.

---

*[pkg/sql/lease.go, line 1291 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510#-Kgf12xFwKU02pbZDmuG:-Kgo0RXzHsxFCvcKaAlE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccd5b706358300b6fb8140f89a4e9e2c78401fb1/pkg/sql/lease.go#L1291)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

missing article after "using"
</blockquote></details>

Done.

---

*[pkg/sql/session.go, line 157 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510#-Kg_v_dk4hU80bUhAAFz:-Kgo0nT7jKIA-rwcf1YJ:b-n4qcwz) ([raw file](https://github.com/cockroachdb/cockroach/blob/cde62b3e0c254cb9591f0776924f743f43029c7f/pkg/sql/session.go#L157)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

OK, but why? The struct comment now prescribes where it is used, which is asking for rot. I would rather that comment describe only the behaviour of that structure, not its use.

Separately, I don't think this comment here is useful, but you seem to feel strongly, so I rescind my objection.
</blockquote></details>

Removed the comment. I do appreciate you rescinding your objection even though I now accept it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510)*

**Comment by tamird** [comment]
Reviewed 16 of 16 files at r5, 17 of 17 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/database.go, line 152 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510#-Kg_Cpmi-nERLlUfwBPa:-Kgo4h6Tfg1lrHgH96Vl:bxk5ktn) ([raw file](https://github.com/cockroachdb/cockroach/blob/1febef8b90ed3978fb4c3ec91872863077a0e51b/pkg/sql/database.go#L152)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

actually this is a nil exception in tests. The error returned from here is only logged. I've changed the error message so it's very different.
</blockquote></details>

So then the origin question again: where is this exercised?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510)*

**Comment by vivekmenezes** [comment]
Review status: 14 of 17 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/database.go, line 152 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510#-Kg_Cpmi-nERLlUfwBPa:-Kgo6IJn0VxAl43UYynU:b7t9uvg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1febef8b90ed3978fb4c3ec91872863077a0e51b/pkg/sql/database.go#L152)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

So then the origin question again: where is this exercised?
</blockquote></details>

it breaks a large number of tests because the InternalPlanner doesn't the databaseCache in its session. I've added a new commit to this PR as another alternative

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/executor.go, line 397 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510#-KgoN82lJJQymtUTgFOw:-KgoN82lJJQymtUTgFOx:b-38kyy5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba541b308585349f21baaa565645120308f7cf45/pkg/sql/executor.go#L397)):*
> ```Go
> 	e.systemConfig = cfg
> 	// The database cache gets reset whenever the system config changes.
> 	e.databaseCache = &databaseCache{
> ```

should this be
```
*e.databaseCache = databaseCache{
...
}
```
now that `databaseCache` is never nil?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510)*

**Comment by vivekmenezes** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/executor.go, line 397 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510#-KgoN82lJJQymtUTgFOw:-KgoNw3n9Li7JPhES5lp:b-ksyr1r) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba541b308585349f21baaa565645120308f7cf45/pkg/sql/executor.go#L397)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

should this be
```
*e.databaseCache = databaseCache{
...
}
```
now that `databaseCache` is never nil?
</blockquote></details>

problem is databaseCache has a mutex

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/executor.go, line 397 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510#-KgoN82lJJQymtUTgFOw:-KgoOlC8F-2OoQTyy9D3:b-1zxs0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba541b308585349f21baaa565645120308f7cf45/pkg/sql/executor.go#L397)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

problem is databaseCache has a mutex
</blockquote></details>

I think that's still legal, since the mutex is never copied.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510)*

**Comment by vivekmenezes** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/executor.go, line 397 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510#-KgoN82lJJQymtUTgFOw:-KgoQUMk-oa_u3Z55pNs:b-m3e5vn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba541b308585349f21baaa565645120308f7cf45/pkg/sql/executor.go#L397)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I think that's still legal, since the mutex is never copied.
</blockquote></details>

true, but there is the other issue of overriding the existing cache without holding on to the cache's mutex. The only way around that is to hold on to the cache's mutex and reinitialize it with a new config. But I don't think it's worth it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/executor.go, line 397 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510#-KgoN82lJJQymtUTgFOw:-KgoRXsY3EhaQmoO1zsu:b-2g64g3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba541b308585349f21baaa565645120308f7cf45/pkg/sql/executor.go#L397)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

true, but there is the other issue of overriding the existing cache without holding on to the cache's mutex. The only way around that is to hold on to the cache's mutex and reinitialize it with a new config. But I don't think it's worth it
</blockquote></details>

Is that actually a problem? Does `updateSystemConfig` ever contend with accesses of this structure? Anyway, leave it as-is, I might experiment with it in a followup.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510)*

**Comment by vivekmenezes** [comment]
*[pkg/sql/executor.go, line 397 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510#-KgoN82lJJQymtUTgFOw:-KgoUIbuJcBJEeyICu-o:bpmd9e6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba541b308585349f21baaa565645120308f7cf45/pkg/sql/executor.go#L397)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Is that actually a problem? Does `updateSystemConfig` ever contend with accesses of this structure? Anyway, leave it as-is, I might experiment with it in a followup.
</blockquote></details>

I've pushed a new version that cleans this up a bit.

The basic issue here is that the cache can be in use by the SQL layer and just overwriting it while it is in use when a system config update happens is illegal. TFTR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/database.go, line 63 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510#-KgoVCsk5T5CrsTSgRgo:-KgoVCsk5T5CrsTSgRgp:b-e7jpne) ([raw file](https://github.com/cockroachdb/cockroach/blob/de8ce4db88f8ee6c89f4757114e35a61c488d786/pkg/sql/database.go#L63)):*
> ```Go
> 
> // NewDatabaseCache create a databaseCache with a cfg.
> func NewDatabaseCache(cfg config.SystemConfig) *databaseCache {
> ```

s/New/new/? then you can remove the comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510#-:-KgoVHcXrVZTCaOX20uN:bnfp4nl)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/database.go, line 63 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510#-KgoVCsk5T5CrsTSgRgo:-KgoYgNuQj6bji83uXgn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/de8ce4db88f8ee6c89f4757114e35a61c488d786/pkg/sql/database.go#L63)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

s/New/new/? then you can remove the comment.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510)*

**Comment by tamird** [comment]
Reviewed 14 of 17 files at r10, 3 of 3 files at r11.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14510)*

**Pull request merged**
