### PR TITLE
roachtest: enable version skipping in c2c test

### LINKED ISSUE #132336: roachtest: enable version skipping in mixed version c2c test
Currently the c2c mixed version test only runs a single version upgrade because we explicitly disable version skipping[ here ](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/tests/mixed_version_c2c.go#L81)and [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/tests/mixed_version_c2c.go#L92). To properly enable these, we need to think through, update, and test if all the cross version compatibility guardrails the test imposes will work. 

The only version skip we need to support is 24.1->24.3

Jira issue: CRDB-42985

### PR DESCRIPTION
**Pull request by jeffswenson**
Previously, the C2C test did not support version skipping because it
expected exactly one major upgrade. The test needs to control the
upgrade process because the destination must upgrade before the source.
Now, it compares the finalized version to the expected final version to
determine if it should upgrade the source and cutover.

This fixes a flake where the replicated_time can be null when PCR is
starting up.

Fixes: https://github.com/cockroachdb/cockroach/issues/132336
Release Note: None

### CODE REVIEW

**Comment by jeffswenson** [comment]
I'm hitting an error when I run this with the seed (-5591480852801371240). The seed triggers a version skipping upgrade.

```
[dest/mixed-version-test/28_run-cutover-and-allow-source-to-finalize] 2024/10/24 17:53:24 mixed_version_c2c.go:366: Retained time 2024-10-24 17:48:58.510302 +0000 UTC; cutover time 2024-10-24 17:48:58.510301482 +0000 UTC
[dest/mixed-version-test/28_run-cutover-and-allow-source-to-finalize] 2024/10/24 17:53:24 helper.go:349: running SQL
Node:      7 (<current>)
Tenant:    system
Statement: SELECT fingerprint FROM [SHOW EXPERIMENTAL_FINGERPRINTS FROM VIRTUAL CLUSTER $1 WITH START TIMESTAMP = '1729792138510302000.0000000000'] AS OF SYSTEM TIME '1729792138510301482.0000000000'
Arguments: [dest]
[dest/mixed-version-test/28_run-cutover-and-allow-source-to-finalize] 2024/10/24 17:53:24 runner.go:381: mixed-version test failure while running step 28 (run "cutover and allow source to finalize"): pq: start timestamp 1729792138.510302000,0 is greater than the end timestamp 1729792138.510301482,0
(1) test failed:
  | test random seed: -5591480852801371240 (use COCKROACH_RANDOM_SEED to reproduce)
```

**Comment by jeffswenson** [comment]
I found the source of the failure. I messed up the boolean logic on this branch. Should have been !(a && b) instead of (a && !b).

image

**Comment by jeffswenson** [comment]
```
➜  cockroach git:(jeffswenson-cross-cluster-test-version-skipping) roachtest run c2c/mixed-version --cockroach ./artifacts/cockroach --count 5
Locating and verifying binaries for os="linux", arch="amd64"
WARN: unable to find "cockroach-ea" for "amd64": binary or library "cockroach-ea" not found (or was not executable)
WARN: unable to find library libgeos, ignoring: binary or library "libgeos" not found (or was not executable)
WARN: unable to find library libgeos_c, ignoring: binary or library "libgeos_c" not found (or was not executable)

Found the following binaries:
        cockroach "amd64" at: /Users/swenson/Code/cockroach/artifacts/cockroach
AMD64 clusters will be provisioned with probability 1.00

Running tests which match regex "c2c/mixed-version" and are compatible with cloud "gce".

test runner logs in: artifacts/_runner-logs/test_runner-1729795869.log
HTTP server listening on port 56373 on localhost: http://localhost:56373/
test_run_id: swenson-1729795869
=== RUN   c2c/mixed-version#2  [metrics: https://go.crdb.dev/roachtest-grafana/swenson-1729795869/c2c-mixed-version-2/1729795986672/1729797786672]
=== RUN   c2c/mixed-version#3  [metrics: https://go.crdb.dev/roachtest-grafana/swenson-1729795869/c2c-mixed-version-3/1729795997980/1729797797980]
=== RUN   c2c/mixed-version#4  [metrics: https://go.crdb.dev/roachtest-grafana/swenson-1729795869/c2c-mixed-version-4/1729796004385/1729797804385]
=== RUN   c2c/mixed-version#5  [metrics: https://go.crdb.dev/roachtest-grafana/swenson-1729795869/c2c-mixed-version-5/1729796009112/1729797809112]
=== RUN   c2c/mixed-version#1  [metrics: https://go.crdb.dev/roachtest-grafana/swenson-1729795869/c2c-mixed-version-1/1729796014787/1729797814787]
--- PASS: c2c/mixed-version#4 (835.17s)
No work remaining; runWorker is bailing out...
--- PASS: c2c/mixed-version#2 (860.56s)
No work remaining; runWorker is bailing out...
--- PASS: c2c/mixed-version#3 (867.95s)
No work remaining; runWorker is bailing out...
--- PASS: c2c/mixed-version#5 (892.57s)
No work remaining; runWorker is bailing out...
--- PASS: c2c/mixed-version#1 (889.12s)
No work remaining; runWorker is bailing out...
```

**Comment by msbutler** [comment]
Reran with my additional commit and 5 rounds of the test passed.

**Review by dt — APPROVED** [review]

**Comment by msbutler** [comment]
TFTR!

bors r=dt

**Comment by msbutler** [comment]
blathers backport 24.3

**Pull request merged**
