### PR TITLE
opt: show compact scalars in stats tests

### PR DESCRIPTION
**Pull request by RaduBerinde**
Release note: None

### CODE REVIEW

**Review by justinj — COMMENTED** [review]
:lgtm:

is there a nice way to turn these off? sometimes it can be nice to see the full expanded form+types etc for debugging

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28868#-:-LKOAjvc9yJz9mO8AN56:b-jg2pfs)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by RaduBerinde — COMMENTED** [review]
`format=show-all`

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28868#-:-LKOK5jGASD8xrr55K-H:bbony9w)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28868#-:-LKOLCWSC8rdB3OqUE8F:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/memo/testdata/stats/values, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28868#-LKOL4mSCLpprNCtk3p8:-LKOL4mSCLpprNCtk3p9:b-dk3scs) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd5b7fc10c641df79574ab0408f6c72a8fc96811/pkg/sql/opt/memo/testdata/stats/values#L46)):*
> ```
>  ├── cardinality: [4 - 4]
>  ├── stats: [rows=4]
>  ├── (1,) [type=tuple{int}]
> ```

Why are all of these printing out with a trailing comma?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28868)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/testdata/stats/values, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28868#-LKOL4mSCLpprNCtk3p8:-LKOPS3E2VunkpqoJxqI:b-e2cdw6) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd5b7fc10c641df79574ab0408f6c72a8fc96811/pkg/sql/opt/memo/testdata/stats/values#L46)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why are all of these printing out with a trailing comma?
</blockquote></details>

I think that's the SQL syntax, otherwise `(1)` is just `1`

**Review by rytaft — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28868)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/testdata/stats/values, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28868#-LKOL4mSCLpprNCtk3p8:-LKOPcro4f7XjCHYwn9a:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd5b7fc10c641df79574ab0408f6c72a8fc96811/pkg/sql/opt/memo/testdata/stats/values#L46)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I think that's the SQL syntax, otherwise `(1)` is just `1`
</blockquote></details>

:thumbsup:

**Pull request merged**
