### PR TITLE
sql: Add spans to flow diagrams for TableReader operations

### LINKED ISSUE #32373: distsql: physical plan diagram should contain TableReader spans
The diagrams (`explain (distsql)...`) contain some info for the TableReaders: the index and table name, the limit, but they don't contain the key span that's being read. It'd be most useful.

### PR DESCRIPTION
**Pull request by georgeutsin**
Fixes #32373 

Adding spans info to the TableReader ops in the flow diagrams for distsql explains.

The span information string only includes first span if there are multiple spans to save space and make the diagram less cluttered in complex scenarios: [example](https://cockroachdb.github.io/distsqlplan/decode.html#eJzcWF1vo0YUfe-vGM1TqsWCGXDiIFVi26e0G7vKx0NVWREJUwetDdaAuxut8t8rsLu2wZ47E8YzbN4MhrnnHi6HM-cbzvKEjeMFK3D4NybYwRQ72McODrCDh3jq4CXPn1hR5Ly6ZH3DVfIVh56D02y5KqvTUwc_5Zzh8Bsu03LOcIjv4sc5u2FxwrjrYQcnrIzTeV1mydNFzF-iz_9iB98u46wI0cCtCk9WZYiiCgbPvxSIszgJUXVYlPF8jsp0wULkFXj66uB8VW6qb4s-vqDnuHjeLxcRPH2d1mvMGA7Jq_O2Ls6PdPFl24VLzPVBj_axXSfnCeMsaa7zoSosddUBSq4Zn7Hf8zRj3CWNJztn_5RnEfnw8y88nT2vf27pcKKKm-oa1KClPtfgxsH1Gs1L1ydb1y7ir2jBFjl_QauCJSGiHvoj_bXB8JY9X2UKPs5mnM3iMucuGbYeioMnawI3j_zj-K-H8eTuYXz_6dNZRCoCbu-vzyJa_fptcj--2_wWz8aBnsihntSmJug2NWJyqNeNnNv764erih6_OrphWcJ4PTgoom7ka6NsS8dQgo5VdoiQg1yM80G-dOmwceXh2ud7tYm8EBFYTl06cH0rgqrQx4WEoBrsgx7tw6Cgku6C6skLqqcgqB6SVVNgBHbV9PwkaupJSUO7oS5SqjwvgJQSg1L6Vr6O6SiV1wAqoWX-wA2saJlCHyMJLTPYBz3ah0Eto-9Ay4AR2NWyi3ejZcrzAmgZ_YG1zJfXAF9Cy4KBO7SiZQp9XEpomcE-6NE-DGqZ313LAnktC0610QWmYFfORieRs8DORld5agBF8w0qWgfKjolaIC8GgYSoDQdWJE2hiyEsaQOXoDhLEEF5-cy4FXEL7Ihb8A6MGjAMu8p2-W6MmvK8ALIW_MBGDchwb1ixzLOCSUVzXkUUS2ZsTWyRr_gT-5PnT3WZ9eGkvq_e-CesKNf_0vXBVfb_X0UZ12tvOs9XJdv03m51czJJi8_fT9WvuHz9ke76Dn58KVmBCpaVb8BD_L4BkmSImAJEzTNEFEaYnmCExfVHuut35KMxwj0AJMmQxhEGJsY8Q7QJyNsFtI_Ha97sC7sJdAtEC7y4PvGMCwIAaNgzQLRvDFHzDAXCF6CBp3nzUHgzPd9_fU7wBTg3a6JANsV4tJsqxfoWTBQAyLyJAibGPEMXZk1URzzaTZVifQsmCgBk3kQBE2OeoZHwM3ApNlGXOkyUxmbEePSbKlUA5i2CGJAFEwUAMs8QaW3NRS5qBxC0rsoO20ijKlvuHgDS73iUEZi3ONDUWAiKWttsyyYHAGQhOhID0m97lBFYCIuAqbGQp7W273s6TwKx1SGtzbZlrwMAspAgQYi0f9tVEViwOxAiC35HHPy83e_0Lc8BAFnwO71LeCBE2v2P8tRY4KRvoQ4AyILf6V3MAyHS7n-Up8YCJ-JkhwDRDulbtgMAsuF3epf2AIhk_U_Q4T3oXb5DT5TvUC35jsYtFwDIvN8BAFnwOxCi3nGk3_-0EWjJd3TOcd_yHQCQBb8DIeodR_r9TxuBON-hQL5D-5bvAIAs-B0IkYVve-_yHgjR6TMwqivfmb7-9F8AAAD__wP4iaQ=)

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
This is looking great.

Can you regenerate the test files and add them to the PR?

You should get in the habit of squashing your commits as you do them like we were talking about - make the commit message what it would be at the end of the process, and instead of adding small wip commits, amend your changes to that same commit and force push. I'll show you Reviewable and how it's easier to work in this workflow a bit later.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33571#-:-LVn8UY29MBtVmJqYA6D:b2iv6dl)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlpb/flow_diagram.go, line 141 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/33571#-LVn89O64AJ7j4ZJ04fz:-LVn89O64AJ7j4ZJ04g-:b-vbshos) ([raw file](https://github.com/cockroachdb/cockroach/blob/62c0caac60299bc11f440d1cb6c0baf2612a6cb6/pkg/sql/distsqlpb/flow_diagram.go#L141)):*
> ```Go
> 	}
> 
> 	idx :=  &tr.Table.PrimaryIndex
> ```

I'm surprised that the linter didn't catch this - but it looks like you didn't run `gofmt` on the code, which would have remove the extra space. You should configure your IDE to let that happen automatically - I can show you how, or ask someone.
___
*[pkg/sql/distsqlpb/flow_diagram.go, line 150 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/33571#-LVn80w04clDUr3lEud1:-LVn80w18b2_sPnGTgIF:bymgo5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/62c0caac60299bc11f440d1cb6c0baf2612a6cb6/pkg/sql/distsqlpb/flow_diagram.go#L150)):*
> ```Go
> 
> 	if len(tr.Spans) > 1 {
> 		spanStr.WriteString(" and others")
> ```

Can you add the number of others in here as well? Like, `" and %d others", len(tr.Spans)-1`.

**Comment by RaduBerinde** [comment]
Note that logic test files (planner, execbuilder) can be regenerated with `TESTFLAGS=--rewrite-results-in-testfiles`.

**Comment by georgeutsin** [comment]
Just for the record, I had to up the timeout to 20m to get the rewrites to complete without error.

I'm also currently looking into why `stage` attributes have begun creeping into output (caught by the  `flow_diagram_test`s)

**Review by jordanlewis — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33571)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlpb/flow_diagram.go, line 150 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/33571#-LVn80w04clDUr3lEud1:-LVom1xt6KMxEU3ytZkJ:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/62c0caac60299bc11f440d1cb6c0baf2612a6cb6/pkg/sql/distsqlpb/flow_diagram.go#L150)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Can you add the number of others in here as well? Like, `" and %d others", len(tr.Spans)-1`.
</blockquote></details>

Thanks!
___
*[pkg/sql/distsqlpb/flow_diagram.go, line 136 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33571#-LVomNRg10F7fmiDXhLg:-LVomNRg10F7fmiDXhLh:b-98a7l) ([raw file](https://github.com/cockroachdb/cockroach/blob/11259def8ee70200f18b043e1885e0208ec31c0b/pkg/sql/distsqlpb/flow_diagram.go#L136)):*
> ```Go
> 	details := indexDetails(tr.IndexIdx, &tr.Table)
> 
> 	var spans []roachpb.Span
> ```

This variable isn't used outside of the following if block. See my following suggestion.
___
*[pkg/sql/distsqlpb/flow_diagram.go, line 139 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33571#-LVomSRsEXR9bgOn0vG5:-LVomSRsEXR9bgOn0vG6:b-11md5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/11259def8ee70200f18b043e1885e0208ec31c0b/pkg/sql/distsqlpb/flow_diagram.go#L139)):*
> ```Go
> 	if len(tr.Spans) > 0 {
> 		// only show the first span in the diagram
> 		spans = append(spans, tr.Spans[0].Span)
> ```

Since this will only be length 1, and you're not using `spans` outside of this if block, you could (and should!) declare it like so:

`spans := []roachpb.Span{tr.Spans[0].Span}
___
*[pkg/sql/distsqlpb/flow_diagram.go, line 145 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33571#-LVombmf7Qt0eWZ-vpFc:-LVombmf7Qt0eWZ-vpFd:bp8ona5) ([raw file](https://github.com/cockroachdb/cockroach/blob/11259def8ee70200f18b043e1885e0208ec31c0b/pkg/sql/distsqlpb/flow_diagram.go#L145)):*
> ```Go
> 		if err != nil {
> 			// log something?
> 			return "TableReader", details
> ```

For now I would add the error text to the output here - something like `return fmt.Sprintf("TableReader (error rendering spans: %v)", err).

**Review by jordanlewis — COMMENTED** [review]
The diagram is looking great! It's really going to be much more usable now.

As far as commit messages, please review https://github.com/cockroachdb/cockroach/wiki/Git-Commit-Messages - those are good guideline, but in general you'll want to have some prose that explains the commit rather than a bullet list of things you've done over time.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33571#-:-LVompf66a5EZRxToQrO:b-skjql8)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by RaduBerinde — APPROVED** [review]
:lgtm: modulo some minor comments

Nice improvement. Eventually we may want to allow `EXPLAIN (DISTSQL,VERBOSE)` and hide some of the fields in non-verbose mode.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33571#-:-LVpJu-IBZqOsaNHaFbQ:b-8kqwjh)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/distsqlpb/flow_diagram.go, line 136 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33571#-LVomNRg10F7fmiDXhLg:-LVpJEYe0Dtw-5R08uI1:bdtc5mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/11259def8ee70200f18b043e1885e0208ec31c0b/pkg/sql/distsqlpb/flow_diagram.go#L136)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This variable isn't used outside of the following if block. See my following suggestion.
</blockquote></details>

I don't think we need this variable at all. Can't we just do `if len(tr.Spans) > 0 { panStr.WriteString(sqlbase.PrettySpans(idx, tr.Spans[:1], 2)) }` below?
___
*[pkg/sql/distsqlpb/flow_diagram.go, line 141 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33571#-LVpIi96DS-CDcX_bjZl:-LVpIi96DS-CDcX_bjZm:b88olkr) ([raw file](https://github.com/cockroachdb/cockroach/blob/11259def8ee70200f18b043e1885e0208ec31c0b/pkg/sql/distsqlpb/flow_diagram.go#L141)):*
> ```Go
> 		spans = append(spans, tr.Spans[0].Span)
> 
> 		idx, _, err := tr.Table.FindIndexByIndexIdx(int(tr.IndexIdx))
> ```

note that this is a bit redundant with `indexDetails`. In particular if `IndexIdx` is bogus, that would have already paniced; I would just ignore the err here.

[nit] FindIndexByIndexIdx is a misleading name since we're not searching for it, I'd rename to `IndexByIndexIdx`.

**Review by georgeutsin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33571)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsqlpb/flow_diagram.go, line 136 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33571#-LVomNRg10F7fmiDXhLg:-LVsLxDLATR3wMPqmBmO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/11259def8ee70200f18b043e1885e0208ec31c0b/pkg/sql/distsqlpb/flow_diagram.go#L136)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I don't think we need this variable at all. Can't we just do `if len(tr.Spans) > 0 { panStr.WriteString(sqlbase.PrettySpans(idx, tr.Spans[:1], 2)) }` below?
</blockquote></details>

Done.
___
*[pkg/sql/distsqlpb/flow_diagram.go, line 139 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33571#-LVomSRsEXR9bgOn0vG5:-LVsLvlb0wjjCe2i3LOQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/11259def8ee70200f18b043e1885e0208ec31c0b/pkg/sql/distsqlpb/flow_diagram.go#L139)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Since this will only be length 1, and you're not using `spans` outside of this if block, you could (and should!) declare it like so:

`spans := []roachpb.Span{tr.Spans[0].Span}
</blockquote></details>

Done.
___
*[pkg/sql/distsqlpb/flow_diagram.go, line 145 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33571#-LVombmf7Qt0eWZ-vpFc:-LVsLkFJA0tnoko-TLrE:bs7wumb) ([raw file](https://github.com/cockroachdb/cockroach/blob/11259def8ee70200f18b043e1885e0208ec31c0b/pkg/sql/distsqlpb/flow_diagram.go#L145)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

For now I would add the error text to the output here - something like `return fmt.Sprintf("TableReader (error rendering spans: %v)", err).
</blockquote></details>

Done.

**Comment by georgeutsin** [comment]
RFAL <3

**Review by yuzefovich — APPROVED** [review]
Nice work! :lgtm: 

> Reviewed 2 of 27 files at r4, 26 of 26 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33571#-:-LVt6zZBEdZuI_0ZdSph:bnahwna)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Review by jordanlewis — APPROVED** [review]
Great work. LGTM - merge at your leisure!

**Comment by georgeutsin** [comment]
bors r=jordanlewis

**Pull request merged**
