### PR TITLE
roachtest: use hibernate fork in nightlies

### PR DESCRIPTION
**Pull request by rafiss**
While we are creating the CockroachDB dialect for Hibernate,
the roachtest will use the fork so we can more easily make incremental
progress on creating the dialect.

Release note: None

### CODE REVIEW

**Review by apantel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42807)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @apantel, @jordanlewis, and @rafiss)

___
*[pkg/cmd/roachtest/hibernate.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42807#-Ludp9M1A-ofprMh0z2q:-Ludp9M1A-ofprMh0z2r:brmirku) ([raw file](https://github.com/cockroachdb/cockroach/blob/6226843efbda74502ce8335d4a6d5bdadc2c6c6c/pkg/cmd/roachtest/hibernate.go#L90)):*
> ```Go
> 		}
> 
> 		// In order to get Hibernate's test suite to connect to cockroach, we have
> ```

Do we still want to do this to be consistent with how it will work when we merge back?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42807)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @apantel and @jordanlewis)

___
*[pkg/cmd/roachtest/hibernate.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42807#-Ludp9M1A-ofprMh0z2q:-LudpUmABsKNrzYjx4lK:b83dqea) ([raw file](https://github.com/cockroachdb/cockroach/blob/6226843efbda74502ce8335d4a6d5bdadc2c6c6c/pkg/cmd/roachtest/hibernate.go#L90)):*
<details><summary><i>Previously, apantel (Adam Pantel) wrote…</i></summary><blockquote>

Do we still want to do this to be consistent with how it will work when we merge back?
</blockquote></details>

We won't need this after our fork gets merged back, since the main hibernate repo will have the correct configs to connect to a local CRDB cluster. you can see the change here: https://github.com/hibernate/hibernate-orm/pull/3095

**Review by apantel — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42807)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

**Review by apantel — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42807)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

**Pull request merged**
