### PR TITLE
rowexec: correctly connect the distinct operator to a memory monitor

### PR DESCRIPTION
**Pull request by rohany**
The distinct operator was not connecting its allocators
to the memory bound account it had, so it wasn't verifying
that its allocations were within its alloted amount.

Release note (bug fix): Fix a bug where the distinct operation
in the row execution engine would fail to properly account
for its memory usage, potentially leading to OOM's on large tables.

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
Thanks!

**Comment by asubiotto** [comment]
🤦‍♂ what was the leftover memory in the end?

**Comment by rohany** [comment]
When we switched to a sorted distinct, we made a copy of the original distinct operator struct. This made the arena point to an old account, rather than the copied account, so closing the account wouldn't close the account connected to the arena. This is why pointers shouldn't exist

**Comment by rohany** [comment]
bors r=jordanlewis

**Pull request merged**
