### PR TITLE
kvtenant: move kv tenant connector out of ccl

### LINKED ISSUE #98226: kvtenant: move kv tenant connector out of ccl
We want to move the KV tenant connector out of `kvtenantccl` to `kvtenant` to enable wider test coverage of multi-tenant features. There should be two ways to instantiate the connector. A connector that connects to any supplied addresses and a connector that only connects to a loopback address.

Existing multi-tenant capable tests that reference the `ccl` package should be updated to use the appropriate connector, whether it be a connector that can connect only via loopback or one that can connect to remote nodes.

Epic: CRDB-16091

Jira issue: CRDB-25139

### PR DESCRIPTION
**Pull request by herkolategan**
This change moves the kv tenant connector out of `kvtenantccl` to enable wider
test coverage of multi-tenant outside `ccl`. There are now two versions of the
kv tenant connector factory, one that provides a connector that only connects
clients to a loopback address, and another that will allow both loopback and
remote addresses. If the loopback version is used in the wrong context an error
will be returned explaining license requirements.

To assist with testing, utilities have been added to instantiate the required kv
connector factory. Tests requiring a kv connector that can connect to remote
nodes can use a testing only factory that is available outside `ccl`. Existing
tests that fell into this category, and depended on `ccl`, have been updated to
use the appropriate utility and connector.

This change does not yet remove the license check for maybe starting a tenant
when a test server is started, since this will most likely break various
existing tests and will require a larger change to fix, it will be done
separately.

Additionally, there are a few other places where `TenantKVAddrs` is populated
with a loopback address, and we can rather favour the new `TenantLoopbackAddr`
to better let the connector factory know that it's only making a loopback
connection and choose the correct logic accordingly. This will be implemented as
part of the test changes mentioned above.

Resolves: https://github.com/cockroachdb/cockroach/issues/98226
Epic: [CRDB-16091](https://cockroachlabs.atlassian.net/browse/CRDB-16091)

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Excellent, thanks. I have only a few comments. Let's rebase this and have a look at CI before this can merge.

> Reviewed 25 of 41 files at r1, 2 of 7 files at r2, 1 of 1 files at r4, 4 of 11 files at r5, 15 of 15 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98203#-:-NSfFtZPE3pytiEDPYOL:bj90vxi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan)

___
*[`pkg/kv/kvclient/kvtenant/connector.go` line 139 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/98203#-NSfEkJ02j2Dzej8Jpt3:-NSfEkJ02j2Dzej8Jpt4:b5m0pvz) ([raw file](https://github.com/cockroachdb/cockroach/blob/39863b1a4853dea82c969da122ec18ee4b550041/pkg/kv/kvclient/kvtenant/connector.go#L139)):*
> ```Go
> 
> // connector mediates the communication of cluster-wide state to sandboxed
> // SQL-only tenant processes through a restricted interface.
> ```

through this comment and the other comments below replace "process" by "server".
___
*[`pkg/kv/kvclient/kvtenant/connector.go` line 143 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/98203#-NSfEoYW90eU6ldrZPR8:-NSfEoYW90eU6ldrZPR9:b660voh) ([raw file](https://github.com/cockroachdb/cockroach/blob/39863b1a4853dea82c969da122ec18ee4b550041/pkg/kv/kvclient/kvtenant/connector.go#L143)):*
> ```Go
> // A connector is instantiated inside a tenant's SQL process and is seeded with
> // a set of one or more network addresses that reference existing KV nodes in
> // the host cluster (or a load-balancer which fans out to some/all KV nodes). On
> ```

s/host/storage, here and below
___
*[`pkg/kv/kvclient/kvtenant/connector.go` line 148 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/98203#-NSfErf0Bc0Shg9BXngV:-NSfErf0Bc0Shg9BXngW:bhhrxx1) ([raw file](https://github.com/cockroachdb/cockroach/blob/39863b1a4853dea82c969da122ec18ee4b550041/pkg/kv/kvclient/kvtenant/connector.go#L148)):*
> ```Go
> // communication.
> //
> // The connector communicates with the host cluster through the roachpb.Internal
> ```

s/host/storage
___
*[`pkg/kv/kvclient/kvtenant/connector.go` line 191 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/98203#-NSfFIgJCcohOWDsBb3J:-NSfFIgJCcohOWDsBb3K:blzczny) ([raw file](https://github.com/cockroachdb/cockroach/blob/39863b1a4853dea82c969da122ec18ee4b550041/pkg/kv/kvclient/kvtenant/connector.go#L191)):*
> ```Go
> 
> // connector is capable of providing information on each of the KV nodes in the
> // cluster in the form of NodeDescriptors. This obviates the need for SQL-only
> ```

replace "SQL-only tenant processes" to "tenant SQL servers", here and below.
___
*[`pkg/kv/kvclient/kvtenant/connector_factory.go` line 36 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/98203#-NSfFavC8ATR3wRbhn45:-NSfFavC8ATR3wRbhn46:b77bpcv) ([raw file](https://github.com/cockroachdb/cockroach/blob/39863b1a4853dea82c969da122ec18ee4b550041/pkg/kv/kvclient/kvtenant/connector_factory.go#L36)):*
> ```Go
> }
> 
> type KVAddressConfig struct {
> ```

I think this needs a docstring.

**Review by herkolategan — COMMENTED** [review]
@knz Thanks for the excellent review! Addressing the comments and doing a rebase. During the rebase I saw that there are two new ccl packages that added tests under `kvtenantccl`. I have decided to leave those there, unless instructed otherwise.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98203#-:-NSkFRCY7qMRW2JkKlOb:b-5cbata)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/kv/kvclient/kvtenant/connector.go` line 139 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/98203#-NSfEkJ02j2Dzej8Jpt3:-NSkFW9T0MDwqRjqycf0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/39863b1a4853dea82c969da122ec18ee4b550041/pkg/kv/kvclient/kvtenant/connector.go#L139)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

through this comment and the other comments below replace "process" by "server".
</blockquote></details>

Done.
___
*[`pkg/kv/kvclient/kvtenant/connector.go` line 143 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/98203#-NSfEoYW90eU6ldrZPR8:-NSkFWcu5gah54FF586-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/39863b1a4853dea82c969da122ec18ee4b550041/pkg/kv/kvclient/kvtenant/connector.go#L143)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

s/host/storage, here and below
</blockquote></details>

Done.
___
*[`pkg/kv/kvclient/kvtenant/connector.go` line 148 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/98203#-NSfErf0Bc0Shg9BXngV:-NSkFWuEAR2s4QAY4FGt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/39863b1a4853dea82c969da122ec18ee4b550041/pkg/kv/kvclient/kvtenant/connector.go#L148)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

s/host/storage
</blockquote></details>

Done.
___
*[`pkg/kv/kvclient/kvtenant/connector.go` line 191 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/98203#-NSfFIgJCcohOWDsBb3J:-NSkFXTo3jnPDVcDTH5P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/39863b1a4853dea82c969da122ec18ee4b550041/pkg/kv/kvclient/kvtenant/connector.go#L191)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

replace "SQL-only tenant processes" to "tenant SQL servers", here and below.
</blockquote></details>

Done.
___
*[`pkg/kv/kvclient/kvtenant/connector_factory.go` line 36 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/98203#-NSfFavC8ATR3wRbhn45:-NSkFY6H1LAz1ntn43xZ:b-5k85ju) ([raw file](https://github.com/cockroachdb/cockroach/blob/39863b1a4853dea82c969da122ec18ee4b550041/pkg/kv/kvclient/kvtenant/connector_factory.go#L36)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I think this needs a docstring.
</blockquote></details>

True, adding.

**Review by knz — APPROVED** [review]
Thank you.

We can move tests in a later PR.

> Reviewed 27 of 27 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98203#-:-NSkdgsu91V196LZbKsT:b-ix84b0)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by herkolategan** [comment]
bors r=knz

**Comment by herkolategan** [comment]
@knz yip, seems like this one needs to be done manually, I'll get on that.

**Pull request merged**
