### PR TITLE
kvserver: sensitize `AdminScatter` to force replica movement

### LINKED ISSUE #74542: kvserver: force replica movement under `AdminScatter`
At the moment, calling `AdminScatter` on a index/table [simply enqueues its ranges into replicate queue](https://github.com/cockroachdb/cockroach/blob/ac332ffd82864c9b5843709505f16a15db6274b7/pkg/kv/kvserver/replica_command.go#L3179-L3201). The `replicateQueue` will only move replicas around if there are stores more than `kv.allocator.range_rebalance_threshold` away from the mean (by default, this is 0.05). This means that `AdminScatter` only causes replica movement if there is already a significant replica count imbalance among the stores in the cluster (or equivalence class). This is not what its clients intuitively expect. 

We've repeatedly noticed that several bulk operations can create single store hotspots inside KV. This contradicts expectations because these bulk operations proactively try to split and scatter ranges before SSTables are sent to them. Since in most cases, scatter doesn't actually cause any replica movement, bulk operations which create a new keyspace or shrink a table's keyspace (index backfills, imports, and truncates) are likely to send all their traffic to a tiny set of stores. Furthermore, because of https://github.com/cockroachdb/cockroach/issues/73731, the store rebalancer doesn't do much to move these replicas around either.

We'd like to change `AdminScatter` to make stronger guarantees about its behavior by making it force replica movement even in a well balanced cluster. One low hanging fruit to solve this would be to make it such that `AdminScatter` enqueues replicas into the replicate queue without any "padding" (i.e. by assuming a 0 value for `kv.allocator.range_rebalance_threshold`) and with some jitter added to the existing replica counts of the stores in the cluster. This should make it such that we're ~randomly moving replicas away to other viable stores in the cluster that aren't too far away from the mean. 

/cc. @nvanbenschoten 
/cc. @cockroachdb/kv-notifications

### PR DESCRIPTION
**Pull request by aayushshah15**
This patch makes it such that `AdminScatter` now triggers a ~mostly random
rebalance action. This has always been the contract that the `SSTBatcher` 
assumed.

Previously, calling `AdminScatter` would simply enqueue that range into the
`replicateQueue`. The `replicateQueue` only cares about reconciling
replica-count differences between stores in the cluster if there are stores
that are more than 5% away from the mean. If all candidate stores were within
5% of the mean, then calling `AdminScatter` wouldn't do anything.

Now, `AdminScatter` still enqueues the range into the `replicateQueue` but with
an option to force it to:
1. Ignore the 5% padding provided by `kv.allocator.range_rebalance_threshold`.
2. Add some jitter to the existing replica-counts of all candidate stores.

This means that `AdminScatter` now forces mostly randomized rebalances to
stores that are reasonable targets (i.e. we still won't rebalance to stores
that are too far above the mean in terms of replica-count, or stores that don't
meet the constraints placed on the range, etc).

Fixes https://github.com/cockroachdb/cockroach/issues/74542

Release note (performance improvement): IMPORTs and index backfills
should now do a better job of spreading their load out over the nodes in
the cluster.

### CODE REVIEW

**Comment by aayushshah15** [comment]
I'm running two clusters side by side, one based on `master` (with `48mb` `SplitAndScatter` threshold in the `SSTBatcher`) and one based on this PR (also with the same `48mb` threshold). The results are encouraging.

These are the graphs of `AdminScatter` requests against the number of rebalancing operations by the `replicateQueue` (these include the rebalances that happened due to scatter). The yellow line is the number of rebalances.

**On `master`**
master_48mb_scatter_vs_rebalances

**With this patch**
with_fix_48mb_scatter_vs_rebalances

cc @nvanbenschoten, @dt

**Comment by aayushshah15** [comment]
These are the corresponding read-amplification charts. This is also very encouraging.

**`master`**
master_48mb_read_amp

**With this patch**
with_fix_48mb_read_amp

**Comment by dt** [comment]
what explains the spike vs smooth number of AdminScatter requests between the two?

**Comment by aayushshah15** [comment]
>what explains the spike vs smooth number of AdminScatter requests between the two?

I was wondering the same thing, but notice that those valleys in the rate of `AdminScatter` requests seem to line up very well with the spikes in read-amplification on that one node. My guess is that that node slows the import down a bit. 

It looks like we have a similar pattern in the rate of `AddSSTableRequests`. 
image

**Comment by dt** [comment]
if you still have that cluster, can you plot addsstable.delay.total vs the scatter reqs ?

**Review by nvb — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75894)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15)

___
*[pkg/kv/kvserver/allocator_scorer.go, line 158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75894#-MvKpoczCfZ83bNyDOZe:-MvKpoczCfZ83bNyDOZf:b2dimq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5dec7fd885c84dfc2579ab7249e7bb81daeb7832/pkg/kv/kvserver/allocator_scorer.go#L158)):*
> ```Go
> 	perturbedStoreDescs := make([]roachpb.StoreDescriptor, 0, len(sl.stores))
> 	for _, store := range sl.stores {
> 		jitter := float64(store.Capacity.RangeCount) * o.rangeRebalanceThreshold * (0.25 + allocRand.Float64())
> ```

Why the `+ 0.25`?
___
*[pkg/kv/kvserver/allocator_scorer.go, line 158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75894#-MvKqdGh5RrIHS-FU65S:-MvKqdGh5RrIHS-FU65T:btnfepq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5dec7fd885c84dfc2579ab7249e7bb81daeb7832/pkg/kv/kvserver/allocator_scorer.go#L158)):*
> ```Go
> 	perturbedStoreDescs := make([]roachpb.StoreDescriptor, 0, len(sl.stores))
> 	for _, store := range sl.stores {
> 		jitter := float64(store.Capacity.RangeCount) * o.rangeRebalanceThreshold * (0.25 + allocRand.Float64())
> ```

Could we add a comment here explaining why we're jittering by a function of the range rebalance threshold?
___
*[pkg/kv/kvserver/allocator_scorer.go, line 165 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75894#-MvKqkvxByNblBTamZOB:-MvKqkvxByNblBTamZOC:b-ajnkrh) ([raw file](https://github.com/cockroachdb/cockroach/blob/5dec7fd885c84dfc2579ab7249e7bb81daeb7832/pkg/kv/kvserver/allocator_scorer.go#L165)):*
> ```Go
> 		perturbedStoreDescs = append(perturbedStoreDescs, store)
> 	}
> 	o.rangeRebalanceThreshold = 0
> ```

Also, call this out in a comment. It's not entirely clear to me why this is needed if we already jittered. Shouldn't the jitter be enough to push two candidates that we're previously within the threshold out of it?

All else being equal, it would be best to keep the options struct immutable. This would also mean we wouldn't need the first commit, though implementing the interface on a pointer seems fine either way.
___
*[pkg/kv/kvserver/allocator_test.go, line 7285 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75894#-MvKrcPsD9sOSvBxX0v8:-MvKrcPsD9sOSvBxX0v9:b-7lha2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/5dec7fd885c84dfc2579ab7249e7bb81daeb7832/pkg/kv/kvserver/allocator_test.go#L7285)):*
> ```Go
> 			rangeRebalanceThreshold: 0.05,
> 		},
> 		true, /* scatter */
> ```

Should the test call this function twice with different values for `scatter` to prove that the allocator normally would not make the move?

**Comment by aayushshah15** [comment]
___
*[pkg/kv/kvserver/allocator_scorer.go, line 165 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75894#-MvKqkvxByNblBTamZOB:-MvL_TkXE2vNpqu3ACus:b-o8fk5s) ([raw file](https://github.com/cockroachdb/cockroach/blob/5dec7fd885c84dfc2579ab7249e7bb81daeb7832/pkg/kv/kvserver/allocator_scorer.go#L165)):*
>Shouldn't the jitter be enough to push two candidates that we're previously within the threshold out of it?

Just to check my understanding: If we keep the padding provided by `kv.allocator.range_rebalance_threshold`, the only candidates we'll ever push towards the "underfull" side will be the ones that already have fewer-than-mean replicas. Furthermore, the likelihood of these candidates being pushed out will be determined by how far away from the mean they already are. 

I think this all makes it a bit more unlikely to scatter but quite a bit harder to explain / understand. I personally feel that we should have this thing be more on the aggressive side since:
1. Internally, its only ever called on empty ranges. So there's no real cost to the aggressiveness.
2. If called through the SQL `SCATTER` command, IMO the aggressiveness is desirable and more congruent with what a caller would expect.

What do you think?

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75894)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15)

___
*[pkg/kv/kvserver/allocator_scorer.go, line 165 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75894#-MvKqkvxByNblBTamZOB:-MvLe2B8BczCllnTPsdu:b-mxtng2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5dec7fd885c84dfc2579ab7249e7bb81daeb7832/pkg/kv/kvserver/allocator_scorer.go#L165)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

>Shouldn't the jitter be enough to push two candidates that we're previously within the threshold out of it?

Just to check my understanding: If we keep the padding provided by `kv.allocator.range_rebalance_threshold`, the only candidates we'll ever push towards the "underfull" side will be the ones that already have fewer-than-mean replicas. Furthermore, the likelihood of these candidates being pushed out will be determined by how far away from the mean they already are. 

I think this all makes it a bit more unlikely to scatter but quite a bit harder to explain / understand. I personally feel that we should have this thing be more on the aggressive side since:
1. Internally, its only ever called on empty ranges. So there's no real cost to the aggressiveness.
2. If called through the SQL `SCATTER` command, IMO the aggressiveness is desirable and more congruent with what a caller would expect.

What do you think?
</blockquote></details>

I see what you're saying here. I think it's fine if we set this threshold to 0 then, but it feels wrong to do so here. It actually feels a little strange that the allocator knows anything about the `scatter` flag. Did you consider a scheme where you teach the `rangeCountScorerOptions` about scatter and then pass that in to the allocator from `(replicateQueue).considerRebalance`? Or implement an entirely new `scatterScorerOptions`?

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75894)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/allocator_scorer.go, line 158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75894#-MvKpoczCfZ83bNyDOZe:-MvM34KV4SliT1iV75ls:bgnijv6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5dec7fd885c84dfc2579ab7249e7bb81daeb7832/pkg/kv/kvserver/allocator_scorer.go#L158)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why the `+ 0.25`?
</blockquote></details>

No real reason, removed. 
___
*[pkg/kv/kvserver/allocator_scorer.go, line 158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75894#-MvKqdGh5RrIHS-FU65S:-MvM35zNCP2I4z6JMac5:b-9y2l0i) ([raw file](https://github.com/cockroachdb/cockroach/blob/5dec7fd885c84dfc2579ab7249e7bb81daeb7832/pkg/kv/kvserver/allocator_scorer.go#L158)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could we add a comment here explaining why we're jittering by a function of the range rebalance threshold?
</blockquote></details>

Added before the `jitter` attribute is set in `scatterScorerOptions`. 
___
*[pkg/kv/kvserver/allocator_scorer.go, line 165 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75894#-MvKqkvxByNblBTamZOB:-MvM3A_8A8fafo75OJW9:b-oia5ad) ([raw file](https://github.com/cockroachdb/cockroach/blob/5dec7fd885c84dfc2579ab7249e7bb81daeb7832/pkg/kv/kvserver/allocator_scorer.go#L165)):*
>implement an entirely new scatterScorerOptions

This seems much nicer, how do you feel about the latest revision?
___
*[pkg/kv/kvserver/allocator_test.go, line 7285 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75894#-MvKrcPsD9sOSvBxX0v8:-MvM3KVUCGJcDuR_gVf8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5dec7fd885c84dfc2579ab7249e7bb81daeb7832/pkg/kv/kvserver/allocator_test.go#L7285)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should the test call this function twice with different values for `scatter` to prove that the allocator normally would not make the move?
</blockquote></details>

Done.

**Review by nvb — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75894)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15)

___
*[pkg/kv/kvserver/allocator.go, line 914 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75894#-MvP8Bow0TrxXbt4VS-E:-MvP8Bow0TrxXbt4VS-F:b-ftupc5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a459d700d1cc12d9c0d9b0ec24e9bdcec1612b6/pkg/kv/kvserver/allocator.go#L914)):*
> ```Go
> }
> 
> func (a Allocator) storeListForCandidates(candidates []roachpb.ReplicationTarget) StoreList {
> ```

It feels like we're running circles around a progression like `[]ReplicationTarget` -> `StoreList` -> `[]ReplicaDescriptor` -> `StoreList`. Is this all principled? Does the typing make sense at each level?
___
*[pkg/kv/kvserver/allocator.go, line 1291 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75894#-MvP0P1ZEgHI9Xl_kV6c:-MvP0P1ZEgHI9Xl_kV6d:b6d65wz) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a459d700d1cc12d9c0d9b0ec24e9bdcec1612b6/pkg/kv/kvserver/allocator.go#L1291)):*
> ```Go
> }
> 
> func (a *Allocator) scorerOptionsForScatter() *scatterScorerOptions {
> ```

nit: move this below the main `scorerOptions` method.
___
*[pkg/kv/kvserver/allocator_scorer.go, line 165 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75894#-MvKqkvxByNblBTamZOB:-MvPAUqZ0IBzxVCnVK-7:b-y8xlro) ([raw file](https://github.com/cockroachdb/cockroach/blob/5dec7fd885c84dfc2579ab7249e7bb81daeb7832/pkg/kv/kvserver/allocator_scorer.go#L165)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

>implement an entirely new scatterScorerOptions

This seems much nicer, how do you feel about the latest revision?
</blockquote></details>

Yeah, this is much nicer.
___
*[pkg/kv/kvserver/allocator_scorer.go, line 143 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75894#-MvP8pFnDSRFOXa5VzFu:-MvP8pFnDSRFOXa5VzFv:bsq15oz) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a459d700d1cc12d9c0d9b0ec24e9bdcec1612b6/pkg/kv/kvserver/allocator_scorer.go#L143)):*
> ```Go
> }
> 
> func jittered(val float64, jitter float64, rand allocatorRand) float64 {
> ```

Do we need to lock and unlock `rand`? That feels pretty fragile, and yet it's what we do elsewhere. Maybe we should clean that up and push the locking inside of an API that mirrors (but does not directly expose) `rand.Rand`.

Or better yet (in a separate commit), let's remove `allocatorRand`, replace it with a raw `*rand.Rand`, and make it thread-safe by wrapping its `rand.Source` in a:
```go
type lockedSource struct {
	m  sync.Mutex
	src rand.Source64
}

// TODO: implement rand.Source64.
```

This is what `math/rand.globalRand` does in the standard library.

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75894)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/allocator.go, line 914 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75894#-MvP8Bow0TrxXbt4VS-E:-MvRwZRO3zyYBvkqujc-:b-to5t1f) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a459d700d1cc12d9c0d9b0ec24e9bdcec1612b6/pkg/kv/kvserver/allocator.go#L914)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It feels like we're running circles around a progression like `[]ReplicationTarget` -> `StoreList` -> `[]ReplicaDescriptor` -> `StoreList`. Is this all principled? Does the typing make sense at each level?
</blockquote></details>

It is kind of unfortunate the way we're converting from one type to another in so many of these methods. 

One low hanging fruit to improve here was the fact that the `Allocator.Remove{Non}Voter` and the `Allocator.Allocate{Non}Voter` methods were returning a `ReplicaDescriptor` instead of a `ReplicationTarget` (I believe this was just a vestige). Aside from that, I don't see any obvious wins. The issue is that some of these methods have multiple callers, not all of whom have access to the same input types.

We might now be going from `[]ReplicationTarget` -> `StoreList` -> `ReplicationTarget`, but we shouldn't be doing what you mentioned.
___
*[pkg/kv/kvserver/allocator.go, line 1291 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75894#-MvP0P1ZEgHI9Xl_kV6c:-MvPJEFd2emr9O3G5xz5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a459d700d1cc12d9c0d9b0ec24e9bdcec1612b6/pkg/kv/kvserver/allocator.go#L1291)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: move this below the main `scorerOptions` method.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/allocator_scorer.go, line 143 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75894#-MvP8pFnDSRFOXa5VzFu:-MvPNoYn79YGFvavalpC:bfxcqw1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a459d700d1cc12d9c0d9b0ec24e9bdcec1612b6/pkg/kv/kvserver/allocator_scorer.go#L143)):*
>That feels pretty fragile, and yet it's what we do elsewhere

oh, good catch. I'll do the proper locking with `allocatorRand` now and add a TODO to clean this up later (unless you insist we do it in this PR).

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75894#-:-MveFG244us5N_EsINvN:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15)

___
*[pkg/kv/kvserver/allocator_scorer.go, line 143 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75894#-MvP8pFnDSRFOXa5VzFu:-Mve6fm61y1my5Jw4ImK:b54r1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a459d700d1cc12d9c0d9b0ec24e9bdcec1612b6/pkg/kv/kvserver/allocator_scorer.go#L143)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

>That feels pretty fragile, and yet it's what we do elsewhere

oh, good catch. I'll do the proper locking with `allocatorRand` now and add a TODO to clean this up later (unless you insist we do it in this PR).
</blockquote></details>

Seems fine to do in a separate PR.
___
*[pkg/kv/kvserver/allocator_scorer.go, line 150 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/75894#-Mve6eSs46nG9pADSola:-Mve6eSs46nG9pADSolb:b6i8m5h) ([raw file](https://github.com/cockroachdb/cockroach/blob/73734cbebf25535f210028ef39b4e5dee264e6ad/pkg/kv/kvserver/allocator_scorer.go#L150)):*
> ```Go
> 		result *= -1
> 	}
> ```

nit: stray line
___
*[pkg/roachpb/metadata_replicas.go, line 472 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/75894#-MveEuAkA9Mg7G4dhRWR:-MveEuAkA9Mg7G4dhRWS:b1p8vyp) ([raw file](https://github.com/cockroachdb/cockroach/blob/60b80c4c2d886b38def04b18246861c22a2c3087/pkg/roachpb/metadata_replicas.go#L472)):*
> ```Go
> }
> 
> // EmptyReplicationTarget returns true if `target` is an empty replication
> ```

It would be slightly more standard to make this a method called `Empty`. That would also make it easier to use. We have many instances of that.

**Review by aayushshah15 — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75894#-:-MveJa0m6-SDhlhyb4sD:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15 and @nvanbenschoten)

___
*[pkg/kv/kvserver/allocator_scorer.go, line 150 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/75894#-Mve6eSs46nG9pADSola:-MveJWMQ5xwdbiww1iY7:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/73734cbebf25535f210028ef39b4e5dee264e6ad/pkg/kv/kvserver/allocator_scorer.go#L150)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: stray line
</blockquote></details>

Fixed.
___
*[pkg/roachpb/metadata_replicas.go, line 472 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/75894#-MveEuAkA9Mg7G4dhRWR:-MveJY5a8Wg6CFYuRKje:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/60b80c4c2d886b38def04b18246861c22a2c3087/pkg/roachpb/metadata_replicas.go#L472)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It would be slightly more standard to make this a method called `Empty`. That would also make it easier to use. We have many instances of that.
</blockquote></details>

Done.

**Pull request merged**
