### PR TITLE
opt,sql: disallow column references in ROWS/RANGE

### LINKED ISSUE #38286: sql: internal error: indexed var must be bound to a container before evaluation
```
CREATE TABLE table1 (
	col0  TIMESTAMPTZ,
	col1  BIT(22),
	col2  NAME,
	col3  INT8 NULL,
	col4  "char" NOT NULL,
	col5  CHAR NOT NULL,
	col6  CHAR NOT NULL,
	col7  INET NOT NULL,
	col8  INT2 NULL,
	col9  REGNAMESPACE NOT NULL,
	col10 REGTYPE NULL,
	col11 OID NOT NULL,
	col12 REGTYPE NULL,
	col13 BIT(42) NOT NULL,
	col14 INT8 NULL,
	col15 FLOAT8 NULL,
	FAMILY fam0 (col9, col4, col0, col1, col6),
	FAMILY fam1 (col10, col2, col5, col14, col15, col7, col11, col13, col12, col3, col8),
	PRIMARY KEY (col6 ASC),
	INDEX (col7 DESC, col2, col5 DESC, col1, col12 ASC, col0 DESC, col15 ASC)
);

    WITH with_124059 (col_1570955) AS (
									SELECT *
									  FROM (
											VALUES (NULL),
											       (2609206515:::OID),
											       (4037323730:::OID),
											       (1711655002:::OID),
											       (3423528832:::OID)
									       ) AS tab_536190 (col_1570955)
                                   )
  SELECT tab_536191.col11 AS col_1570956,
         ARRAY[
			2917945630780613107:::INT8,
			6992170413345928079:::INT8,
			5859734096475146714:::INT8,
			(-6072750870110614877):::INT8
         ] AS col_1570957,
         tab_536191.col11 AS col_1570958,
         stddev(tab_536191.col8::INT8)::DECIMAL AS col_1570959,
         min(tab_536191.col5::STRING) OVER (
			PARTITION BY tab_536191.col13, tab_536191.col4
			    ORDER BY tab_536191.col1, tab_536191.col13 DESC, tab_536191.col11, tab_536191.col5
			        ROWS BETWEEN tab_536191.col8 FOLLOWING AND 9223372036854775807:::INT8 FOLLOWING
         )::STRING AS col_1570960,
         (-0.45292767816968504):::FLOAT8 AS col_1570961,
         current_timestamp():::DATE::DATE AS col_1570962
    FROM defaultdb.public.table1 AS tab_536191
GROUP BY tab_536191.col4, tab_536191.col8, tab_536191.col11, tab_536191.col1, tab_536191.col13, tab_536191.col5
ORDER BY tab_536191.col13 DESC, tab_536191.col8 DESC, tab_536191.col11
   LIMIT 9:::INT8;
```

```
github.com/cockroachdb/cockroach/pkg/sql/sem/tree/indexed_vars.go:77: Eval()
github.com/cockroachdb/cockroach/pkg/sql/distsqlpb/processors.go:92: initFromAST()
github.com/cockroachdb/cockroach/pkg/sql/distsqlpb/processors.go:195: InitFromAST()
github.com/cockroachdb/cockroach/pkg/sql/distsql_plan_window.go:141: createWindowFnSpec()
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:3113: createPlanForWindow()
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2401: createPlanForNode()
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2332: createPlanForNode()
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2350: createPlanForNode()
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2312: createPlanForNode()
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2312: createPlanForNode()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:834: PlanAndRun()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:896: execWithDistSQLEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:732: dispatchToExecutionEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:419: execStmtInOpenState()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:101: execStmt()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1206: execCmd()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1142: run()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:444: ServeConn()
github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:582: func1()
runtime/asm_amd64.s:1337: goexit()
```

### PR DESCRIPTION
**Pull request by justinj**
Fixes #38286.

This is a departure from the behaviour of the heuristic planner but is
actually the same behaviour as Postgres:

```
d=# create table x (a int primary key);
CREATE TABLE
d=# select rank() over (order by a range between a preceding and unbounded following) from x;
ERROR:  argument of RANGE must not contain variables
LINE 1: select rank() over (order by a range between a preceding and...
```

Our behaviour now:
```
root@127.0.0.1:60679/movr> CREATE TABLE x (a INT8 PRIMARY KEY)
CREATE TABLE

root@127.0.0.1:60679/movr> SELECT
    rank() OVER (ORDER BY a RANGE BETWEEN a PRECEDING AND UNBOUNDED FOLLOWING)
FROM
    x
pq: ROWS or RANGE cannot contain variables
```

Release justification: Category 2: Fixes a bug and brings behaviour more
in-line with Postgres.

Release note (sql change): column references are no longer allowed in
ROWS/RANGE clauses in window functions.

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40832#-:-Lp-6ey648yJDzDVSavj:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/sql/opt/norm/testdata/rules/prune_cols, line 1660 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40832#-Lp-6JRf6KKx3SMNp6_a:-Lp-6JRg979UmO1lk-2P:bm2eu3j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6994e2ff384b714ad34ac2358a33d236bb09f0b/pkg/sql/opt/norm/testdata/rules/prune_cols#L1660)):*
> ```
>                 └── variable: t.public.a.i [type=int]
> 
> # Ensure OFFSET expressions don't get pruned.
> ```

This condition is no longer tested by this.. We should either remove or replace with one that does.
___
*[pkg/sql/opt/optbuilder/testdata/window, line 1548 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40832#-Lp-6ZRz39zcpkqV_d_u:-Lp-6ZS-2FHgZS05--Ba:b9dievo) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6994e2ff384b714ad34ac2358a33d236bb09f0b/pkg/sql/opt/optbuilder/testdata/window#L1548)):*
> ```
> build
> SELECT
> 	min(tab_536191.col5) OVER (
> ```

[nit] remove tabs

**Review by yuzefovich — COMMENTED** [review]
Thanks for looking into this! I know this issue has been popping up a lot in the nightly SQLSmith runs.

> Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40832#-:-Lp-EPHrDckediWXQCxR:bnkcr2u)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj and @rytaft)

___
*[pkg/sql/opt/optbuilder/window.go, line 172 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40832#-Lp-D6z1BxHbEY5r1NFc:-Lp-D6z2EzuY5Yc90BwL:bvct63n) ([raw file](https://github.com/cockroachdb/cockroach/blob/79d0a24f831d87958d76ec816fbd3adc6e1d4f5a/pkg/sql/opt/optbuilder/window.go#L172)):*
> ```Go
> 				pgerror.Newf(
> 					pgcode.InvalidColumnReference,
> 					"ROWS or RANGE cannot contain variables",
> ```

I think it should be the same for `GROUPS` mode, no? I believe we had a PR that fixed it for `GROUPS` mode, maybe we need to combine with that?

[nit]: I'd also customize the message for a particular mode (i.e. `ROWS cannot contain variables` and `RANGE cannot contain variables`). Also, I thought we attempted our best to match even the error message of Postgres, so maybe use `argument of RANGE must not contain variables`?

**Review by justinj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40832)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj, @rytaft, and @yuzefovich)

___
*[pkg/sql/opt/norm/testdata/rules/prune_cols, line 1660 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40832#-Lp-6JRf6KKx3SMNp6_a:-Lp-eAfuChD5DkcujFv6:burx239) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6994e2ff384b714ad34ac2358a33d236bb09f0b/pkg/sql/opt/norm/testdata/rules/prune_cols#L1660)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This condition is no longer tested by this.. We should either remove or replace with one that does.
</blockquote></details>

Done, removed since I don't think it's relevant any more.
___
*[pkg/sql/opt/optbuilder/window.go, line 172 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40832#-Lp-D6z1BxHbEY5r1NFc:-Lp-eECp7JE78xJlNpqT:b-l4xrx9) ([raw file](https://github.com/cockroachdb/cockroach/blob/79d0a24f831d87958d76ec816fbd3adc6e1d4f5a/pkg/sql/opt/optbuilder/window.go#L172)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think it should be the same for `GROUPS` mode, no? I believe we had a PR that fixed it for `GROUPS` mode, maybe we need to combine with that?

[nit]: I'd also customize the message for a particular mode (i.e. `ROWS cannot contain variables` and `RANGE cannot contain variables`). Also, I thought we attempted our best to match even the error message of Postgres, so maybe use `argument of RANGE must not contain variables`?
</blockquote></details>

Ah yeah, good catch! Those can be unified.

I made the change here, but personally I don't think it's very important that our error messages match Postgres, and I'm not aware of any guidelines that dictate that? I think it's important that the error _codes_ match, but the messages should be purely for human consumption.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40832#-:-Lp3w8Ua6kXQdATbHToL:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj and @rytaft)

___
*[pkg/sql/opt/optbuilder/scope.go, line 1185 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40832#-Lp3vX-m-7apZZeDvIOW:-Lp3vX-m-7apZZeDvIOX:bc4amdw) ([raw file](https://github.com/cockroachdb/cockroach/blob/99bed2718a9b5d1c6b94ce0d65dc40d1e746de16/pkg/sql/opt/optbuilder/scope.go#L1185)):*
> ```Go
> 		if endBound != nil && endBound.HasOffset() {
> 			if tree.ContainsVars(endBound.OffsetExpr) {
> 				return errVarOffsetGroups
> ```

[nit]: this error might no longer be used I think.
___
*[pkg/sql/opt/optbuilder/window.go, line 172 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40832#-Lp-D6z1BxHbEY5r1NFc:-Lp3vapOCJQfzxtEGEPV:b-fh36o7) ([raw file](https://github.com/cockroachdb/cockroach/blob/79d0a24f831d87958d76ec816fbd3adc6e1d4f5a/pkg/sql/opt/optbuilder/window.go#L172)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Ah yeah, good catch! Those can be unified.

I made the change here, but personally I don't think it's very important that our error messages match Postgres, and I'm not aware of any guidelines that dictate that? I think it's important that the error _codes_ match, but the messages should be purely for human consumption.
</blockquote></details>

Thanks.

The "trying to match error message" is the impression I got when I was working on window functions in 2018. The error code was "best effort" and the error message was "nice to have." Personally, I also don't feel strongly about it.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 1 of 2 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40832#-:-Lp40OpYDbjhonSEhEm_:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj)

___
*[pkg/sql/sem/tree/select.go, line 927 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40832#-Lp409niB_6S1RQKIFHx:-Lp409niB_6S1RQKIFHy:b2hpb9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/27ca53c773f2bf32a2898668b7da3d0345021471/pkg/sql/sem/tree/select.go#L927)):*
> ```Go
> 
> // ModeName returns the name of the window frame mode.
> func ModeName(mode WindowFrameMode) string {
> ```

[nit] I'd name this WindowModeName or something like that to make it clear it relates to window functions

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40832)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale) (waiting on @justinj, @rytaft, and @yuzefovich)

___
*[pkg/sql/sem/tree/select.go, line 927 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40832#-Lp409niB_6S1RQKIFHx:-Lp4GqolEzqke-8750ov:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/27ca53c773f2bf32a2898668b7da3d0345021471/pkg/sql/sem/tree/select.go#L927)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] I'd name this WindowModeName or something like that to make it clear it relates to window functions
</blockquote></details>

+1

**Review by justinj — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40832#-:-Lp95qcHDo_FKuAxcj0w:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale) (waiting on @justinj, @rytaft, and @yuzefovich)

___
*[pkg/sql/opt/optbuilder/scope.go, line 1185 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40832#-Lp3vX-m-7apZZeDvIOW:-Lp4I3y22EjVW8FUkgIK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/99bed2718a9b5d1c6b94ce0d65dc40d1e746de16/pkg/sql/opt/optbuilder/scope.go#L1185)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: this error might no longer be used I think.
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/select.go, line 927 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40832#-Lp409niB_6S1RQKIFHx:-Lp95xHD3jfFxxYASH_U:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/27ca53c773f2bf32a2898668b7da3d0345021471/pkg/sql/sem/tree/select.go#L927)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Pull request merged**
