### PR TITLE
sql,server: add admission control for DistSQL responses

### PR DESCRIPTION
**Pull request by sumeerbhola**
The admission.WorkQueue is plumbed through via execinfra.ServerCfg
to colrpc.Inbox and flowinfra.processProducerMessage, and the
AdmissionInfo is initialized using FlowCtx.Txn when possible.

The admission control point for KV=>SQL response processing
is tweaked to move it after the memory accounting for the
response bytes.

Informs #65948

Release note (ops change): DistSQL response admission control
can be enabled using admission.sql_sql_response.enabled.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67531)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @sumeerbhola)

___
*[pkg/sql/colflow/vectorized_flow.go, line 873 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67531#-MeVp4YJBwmv8Jg7Nwj6:-MeVp4YJBwmv8Jg7Nwj7:bg4mi95) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ff14f226a662342bc2d05148f3368edd6b7d3fd/pkg/sql/colflow/vectorized_flow.go#L873)):*
> ```Go
> 	}
> 
> 	admissionInfo := admission.WorkInfo{TenantID: roachpb.SystemTenantID}
> ```

Should this always be a system tenant?
___
*[pkg/sql/colflow/colrpc/inbox.go, line 354 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67531#-MeVpXnr6FV0QZFZ3mbN:-MeVpXnr6FV0QZFZ3mbO:bfu9oag) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ff14f226a662342bc2d05148f3368edd6b7d3fd/pkg/sql/colflow/colrpc/inbox.go#L354)):*
> ```Go
> 		}
> 		atomic.AddInt64(&i.statsAtomics.bytesRead, int64(len(m.Data.RawBytes)))
> 		// Do admission control before deserialization.
> ```

Is receiving metadata considered to not be limited by the admission control?
___
*[pkg/sql/colflow/colrpc/inbox.go, line 357 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67531#-MeVpHfxCbE53F5epj55:-MeVpHfxCbE53F5epj56:bg3ue4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ff14f226a662342bc2d05148f3368edd6b7d3fd/pkg/sql/colflow/colrpc/inbox.go#L357)):*
> ```Go
> 		if i.admissionQ != nil {
> 			if _, err := i.admissionQ.Admit(i.Ctx, i.admissionInfo); err != nil {
> 				// TODO: err includes context cancellation while waiting for
> ```

Yeah, I think it's reasonable, and `ExpectedError` is used correctly here.
___
*[pkg/sql/flowinfra/flow.go, line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67531#-MeVq4M12SmkJoyMpJrD:-MeVq4M12SmkJoyMpJrE:b-2svgqm) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ff14f226a662342bc2d05148f3368edd6b7d3fd/pkg/sql/flowinfra/flow.go#L188)):*
> ```Go
> 	spec *execinfrapb.FlowSpec
> 
> 	admissionInfo admission.WorkInfo
> ```

I think I'd export this field and reuse it in the vectorized flow by passing into `newVectorizedFlowCreator`.

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67531#-:-Me_LuucE7QYG-OwrWWA:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @yuzefovich)

___
*[pkg/sql/colflow/vectorized_flow.go, line 873 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67531#-MeVp4YJBwmv8Jg7Nwj6:-Me_9KGE0aUmvOHOa1H-:b-yzdbec) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ff14f226a662342bc2d05148f3368edd6b7d3fd/pkg/sql/colflow/vectorized_flow.go#L873)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Should this always be a system tenant?
</blockquote></details>

I've added a code comment justifying this. I'll add it in the other place we do the same if we don't eliminate one of the two based on your other suggestion.
___
*[pkg/sql/colflow/colrpc/inbox.go, line 354 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67531#-MeVpXnr6FV0QZFZ3mbN:-Me_6Npc4pMG7cAuokC0:bi9ixko) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ff14f226a662342bc2d05148f3368edd6b7d3fd/pkg/sql/colflow/colrpc/inbox.go#L354)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Is receiving metadata considered to not be limited by the admission control?
</blockquote></details>

If something is extremely cheap, we don't really need to intercept it. The main reason now is that we want to admission control after we've adjusted the memory accounting to account for the response bytes.
___
*[pkg/sql/colflow/colrpc/inbox.go, line 357 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67531#-MeVpHfxCbE53F5epj55:-Me_8ebr27uUybobLA1P:b-zcjvte) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ff14f226a662342bc2d05148f3368edd6b7d3fd/pkg/sql/colflow/colrpc/inbox.go#L357)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Yeah, I think it's reasonable, and `ExpectedError` is used correctly here.
</blockquote></details>

Thanks
___
*[pkg/sql/flowinfra/flow.go, line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67531#-MeVq4M12SmkJoyMpJrD:-Me_IChk9fiJPo6TKjiF:b-sdswhm) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ff14f226a662342bc2d05148f3368edd6b7d3fd/pkg/sql/flowinfra/flow.go#L188)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I think I'd export this field and reuse it in the vectorized flow by passing into `newVectorizedFlowCreator`.
</blockquote></details>

Trying to fully understand this suggestion.

Currently, I am doing this `WorkInfo` initialization in 2 places, here and in `vectorizedFlowCreator.setupInput`. The latter could be eliminated if it could use `FlowBase.admissionInfo`. Is my understanding correct?
I see a number of tests that don't use `NewFlowBase` and initialize the struct directly. That is probably fine -- we can get away with a zero value for the `WorkInfo` struct. 
There are two non-test callers of `newVectorizedFlowCreator`:
- `vectorizedFlow.Setup`: `vectorizedFlow` has a `*FlowBase`. Will that always be non-nil?
- `convertToVecTree` in `explain_vec.go`: It doesn't seem to have a `FlowBase`. How would that path get fixed?

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67531)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @sumeerbhola)

___
*[pkg/sql/flowinfra/flow.go, line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67531#-MeVq4M12SmkJoyMpJrD:-Me_gEeJ0a6uaAXvwfD3:bw1eoht) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ff14f226a662342bc2d05148f3368edd6b7d3fd/pkg/sql/flowinfra/flow.go#L188)):*
> Is my understanding correct?

Yep, that's what I'm thinking.

> `vectorizedFlow.Setup`: `vectorizedFlow` has a `*FlowBase`. Will that always be non-nil?

Yes.

> `convertToVecTree` in `explain_vec.go`: It doesn't seem to have a `FlowBase`. How would that path get fixed?

This path doesn't actually execute anything (in a sense it creates all necessary infrastructure for the vectorized flows but doesn't run them), so it doesn't matter that this path won't get the admission control stuff (the admission control things wouldn't have any impact anyway).
___
*[pkg/sql/lex/BUILD.bazel, line 7 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67531#-Me_g-8q4yRe9W_tP5lp:-Me_g-8r7z-TIBnUCRr7:be4ybtz) ([raw file](https://github.com/cockroachdb/cockroach/blob/435d1275667e7f584e211d49a8f9746f0a08a924/pkg/sql/lex/BUILD.bazel#L7)):*
> ```Starlark
>     srcs = [
>         "encode.go",
>         "keywords.go",
> ```

Hm, this seems unrelated.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67531)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @yuzefovich)

___
*[pkg/sql/flowinfra/flow.go, line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67531#-MeVq4M12SmkJoyMpJrD:-MeaiBEd8MhvH1ssCVsC:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ff14f226a662342bc2d05148f3368edd6b7d3fd/pkg/sql/flowinfra/flow.go#L188)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

> Is my understanding correct?

Yep, that's what I'm thinking.

> `vectorizedFlow.Setup`: `vectorizedFlow` has a `*FlowBase`. Will that always be non-nil?

Yes.

> `convertToVecTree` in `explain_vec.go`: It doesn't seem to have a `FlowBase`. How would that path get fixed?

This path doesn't actually execute anything (in a sense it creates all necessary infrastructure for the vectorized flows but doesn't run them), so it doesn't matter that this path won't get the admission control stuff (the admission control things wouldn't have any impact anyway).
</blockquote></details>

Done
___
*[pkg/sql/lex/BUILD.bazel, line 7 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67531#-Me_g-8q4yRe9W_tP5lp:-Meai8Xk-8J73yX9l_Gd:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/435d1275667e7f584e211d49a8f9746f0a08a924/pkg/sql/lex/BUILD.bazel#L7)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Hm, this seems unrelated.
</blockquote></details>

Fixed

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67531#-:-MeatdnD-DsrvsfMh2QZ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Comment by RaduBerinde** [comment]
Belated :lgtm:

**Pull request merged**
