### PR TITLE
asim: add load splits

### PR DESCRIPTION
**Pull request by kvoli**
This patch adds load based splitting to the allocation simulator. It
uses the production code path, `pkg/kv/kvserver/split`, to decide when
and which key to split on. To enable split recommendations from this
package, load events are recorded to the splitter and split suggestions
enqueued into the simulator split queue. Split keys are likewise found
via consulting the split decider first and when not found, the split
queue wil instead split evenly (50/50) on the number of keys instead.

resolves https://github.com/cockroachdb/cockroach/issues/82630

Release note: None

### CODE REVIEW

**Review by lidorcarmel — APPROVED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84306)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/asim/asim.go` line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84306#-N6tq7s81JCkk-9FjI7j:-N6tq7s81JCkk-9FjI7k:b-x383q9) ([raw file](https://github.com/cockroachdb/cockroach/blob/127814bea55cf9479e71b3178fafde5b9594b192/pkg/kv/kvserver/asim/asim.go#L183)):*
> ```Go
> 
> 		// Tick the split queue.
> 		s.sqs[storeID].Tick(ctx, tick, state)
> ```

these calls used to be paced and now they are not, is that a problem? I can ask you tomorrow..
___
*[`pkg/kv/kvserver/asim/replicate_queue.go` line 366 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84306#-N6tgj8fAaWsvwSzpnTJ:-N6tgj8fAaWsvwSzpnTK:b9rnbd9) ([raw file](https://github.com/cockroachdb/cockroach/blob/127814bea55cf9479e71b3178fafde5b9594b192/pkg/kv/kvserver/asim/replicate_queue.go#L366)):*
> ```Go
> ) (state.Key, bool) {
> 	// Try and use the split key suggested by the load based splitter, if one
> 	// // exists.
> ```

nit: extra slashes.



_Code quote:_
```Go
// // exists.
```
___
*[`pkg/kv/kvserver/asim/replicate_queue.go` line 368 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84306#-N6th9_N8vc88bcXVVdC:-N6th9_N8vc88bcXVVdD:bygvggd) ([raw file](https://github.com/cockroachdb/cockroach/blob/127814bea55cf9479e71b3178fafde5b9594b192/pkg/kv/kvserver/asim/replicate_queue.go#L368)):*
> ```Go
> 	// // exists.
> 	if loadSplitKey, ok := s.LoadSplitterFor(sq.storeID).SplitKey(tick, rangeID); ok {
> 		fmt.Println(loadSplitKey)
> ```

probably not intentional?
___
*[`pkg/kv/kvserver/asim/state/split_decider.go` line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84306#-N6tsQpFAVyOhphU6uVi:-N6tsQpFAVyOhphU6uVj:b5ikqh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/127814bea55cf9479e71b3178fafde5b9594b192/pkg/kv/kvserver/asim/state/split_decider.go#L33)):*
> ```Go
> 	SplitKey(time.Time, RangeID) (Key, bool)
> 	// ClearSplitKeys returns a suggested list of ranges that should be split
> 	// due to load. Calling this function resets the list of suggestions
> ```

nit: period at the end.
___
*[`pkg/kv/kvserver/asim/state/split_decider_test.go` line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84306#-N6tpVSNCRIkrj-kwBOH:-N6tpVSNCRIkrj-kwBOI:b-d58wq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/127814bea55cf9479e71b3178fafde5b9594b192/pkg/kv/kvserver/asim/state/split_decider_test.go#L113)):*
> ```Go
> 				func() time.Duration { return tc.retention },
> 			)
> 			lastTick := 0
> ```

should we update lastTick in the loop?
maybe something like
```
tickDelta := tick - int64(lastTick)
lastTick = tick
```
___
*[`pkg/kv/kvserver/asim/config/settings.go` line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84306#-N6tiBio4_7IdUzovdjW:-N6tiBio4_7IdUzovdjX:b-7ilvgb) ([raw file](https://github.com/cockroachdb/cockroach/blob/127814bea55cf9479e71b3178fafde5b9594b192/pkg/kv/kvserver/asim/config/settings.go#L122)):*
> ```Go
> 
> // SplitQPSThresholdFn returns a function that returns the current QPS split
> // threshold for load based splittting of a range.
> ```

typo.



_Code quote:_
```Go
splittting
```

**Review by kvoli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84306)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lidorcarmel)

___
*[`pkg/kv/kvserver/asim/asim.go` line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84306#-N6tq7s81JCkk-9FjI7j:-N6x-r--EDN2GYXoRIw6:bn0qj8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/127814bea55cf9479e71b3178fafde5b9594b192/pkg/kv/kvserver/asim/asim.go#L183)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

these calls used to be paced and now they are not, is that a problem? I can ask you tomorrow..
</blockquote></details>

They are ticking the whole queue for processing, they didn't need to be in the pacing loop before. I realized and moved them out. They only need to be called once.
___
*[`pkg/kv/kvserver/asim/replicate_queue.go` line 366 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84306#-N6tgj8fAaWsvwSzpnTJ:-N6x07EN1GThUzbvoGU4:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/127814bea55cf9479e71b3178fafde5b9594b192/pkg/kv/kvserver/asim/replicate_queue.go#L366)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

nit: extra slashes.
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/asim/replicate_queue.go` line 368 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84306#-N6th9_N8vc88bcXVVdC:-N6x09rL5rOO7xSeE076:b6xj2j9) ([raw file](https://github.com/cockroachdb/cockroach/blob/127814bea55cf9479e71b3178fafde5b9594b192/pkg/kv/kvserver/asim/replicate_queue.go#L368)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

probably not intentional?
</blockquote></details>

Yup not intentional.
___
*[`pkg/kv/kvserver/asim/state/split_decider.go` line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84306#-N6tsQpFAVyOhphU6uVi:-N6x17GaC5nLmYCRxf6J:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/127814bea55cf9479e71b3178fafde5b9594b192/pkg/kv/kvserver/asim/state/split_decider.go#L33)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

nit: period at the end.
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/asim/state/split_decider_test.go` line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84306#-N6tpVSNCRIkrj-kwBOH:-N6x2sDR5-JgKmLrKX8N:bib8hbx) ([raw file](https://github.com/cockroachdb/cockroach/blob/127814bea55cf9479e71b3178fafde5b9594b192/pkg/kv/kvserver/asim/state/split_decider_test.go#L113)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

should we update lastTick in the loop?
maybe something like
```
tickDelta := tick - int64(lastTick)
lastTick = tick
```
</blockquote></details>

Seems incorrect currently. Good suggestion, updated.
___
*[`pkg/kv/kvserver/asim/config/settings.go` line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84306#-N6tiBio4_7IdUzovdjW:-N6x0zFa9EJSLzSQvjwR:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/127814bea55cf9479e71b3178fafde5b9594b192/pkg/kv/kvserver/asim/config/settings.go#L122)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

typo.
</blockquote></details>

Updated.

**Review by lidorcarmel — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84306)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lidorcarmel)

**Comment by kvoli** [comment]
bors r=lidorcarmel

**Pull request merged**
