### PR TITLE
settings: add validations functions to settings

### PR DESCRIPTION
**Pull request by BramGruneir**
Two commits:
The first splits up the setting types into their own files, the second adds validation for the settings which were missing them.

### CODE REVIEW

**Comment by dt** [comment]
Is there another piece to this in pkg/sql/set.go that validations attempts to set? I'm guessing you either want to export Validate, or rename it validateFn and move the `if validate != nil` checks into an exported `Validate(v) error` method. 

---

Reviewed 9 of 9 files at r1, 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/settings/duration.go, line 72 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15581#-Kj92zlW5C44p-xX4ybG:-Kj92zlW5C44p-xX4ybH:bqcsgds) ([raw file](https://github.com/cockroachdb/cockroach/blob/26df7dc80eb4bc4d341b52c062e67d3daae600cf/pkg/settings/duration.go#L72)):*
> ```Go
> 	key, desc string, defaultValue time.Duration, validate func(time.Duration) error,
> ) *DurationSetting {
> 	setting := &DurationSetting{
> ```

is it worth adding an explicit `if err := validate(defautValue); err != nil { panic errors.Wrap(err, "invalid default") }` check to these?

`register` will call `setToDefault` and it should panic anyway, just a little less clear why -- and indeed, relying on that somewhat indirect validation of defaults should probably be backstopped with tests that recover the validation errors.

Up to you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15581#-:-Kj95gjvitagRhQtCsEG:bj5v3z6)*

**Comment by BramGruneir** [comment]
Done, and I've threaded this through set.

---

Review status: 2 of 12 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/settings/duration.go, line 72 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15581#-Kj92zlW5C44p-xX4ybG:-Kj9xchqPs-hrbMnSqlu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26df7dc80eb4bc4d341b52c062e67d3daae600cf/pkg/settings/duration.go#L72)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

is it worth adding an explicit `if err := validate(defautValue); err != nil { panic errors.Wrap(err, "invalid default") }` check to these?

`register` will call `setToDefault` and it should panic anyway, just a little less clear why -- and indeed, relying on that somewhat indirect validation of defaults should probably be backstopped with tests that recover the validation errors.

Up to you.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15581#-:-Kj9oSnja36J7xfoICs_:b-hp95r)*

**Comment by BramGruneir** [comment]
Ready to go, PTAL

---

Review status: 2 of 12 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15581#-:-Kj9xiMXrblTu-sbGDYG:b-uvn3si)*

**Comment by dt** [comment]
:lgtm: mod adding test that `SET CLUSTER SETTING` rejects invalid (w.r.t validation) values -- probably want to add test to `settingsworker_test.go`.

---

Review status: 2 of 12 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15581#-:-Kj9zc7dDvc3Sp06M_tF:b-ltqd7d)*

**Comment by BramGruneir** [comment]
Ah, excellent, I was looking for set_test.go, but couldn't find it.  Done.

---

Review status: 2 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15581#-:-KjA-c2n2sS4E8m_5bVH:b-56hsqw)*

**Pull request merged**
