### PR TITLE
ui: Add a new Settings Debug page

### LINKED ISSUE #23923: ui: page displaying cluster settings
The admin UI should have a page displaying the cluster settings (i.e. `show all cluster settings`). I'm a bit surprised we don't already have such a page.

### PR DESCRIPTION
**Pull request by BramGruneir**
Closes #23923.

Release note (admin ui change): Added a new debug page to display all cluster
settings.

image

### CODE REVIEW

**Comment by BramGruneir** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/ui/src/index.tsx, line 55 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24064#-L82UaZkXbiUVgOJpaQ1:-L82UaZkXbiUVgOJpaQ2:bsah877) ([raw file](https://github.com/cockroachdb/cockroach/blob/b713e0d48118eae55a70e0c2e2032326f54d7e1d/pkg/ui/src/index.tsx#L55)):*
> ```XML
> import ReduxDebug from "src/views/reports/containers/redux";
> import Range from "src/views/reports/containers/range";
> import Settings from "src/views/reports/containers/settings";
> ```

Only settings was added here, I just reordered everything else since it was just super messy.

This whole page needs a proper cleanup, but I'll save that for another PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24064)*

**Comment by couchand** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/ui/src/index.tsx, line 55 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24064#-L82UaZkXbiUVgOJpaQ1:-L82nXXNXDdhgPBIXear:byz8y99) ([raw file](https://github.com/cockroachdb/cockroach/blob/b713e0d48118eae55a70e0c2e2032326f54d7e1d/pkg/ui/src/index.tsx#L55)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Only settings was added here, I just reordered everything else since it was just super messy.

This whole page needs a proper cleanup, but I'll save that for another PR.
</blockquote></details>

:+1: for the cleanup :-1: for only one commit

---

*[pkg/ui/src/redux/apiReducers.ts, line 226 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24064#-L82oDuRuvSfBNeyfnmq:-L82oDuRuvSfBNeyfnmr:b-2sgalr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b713e0d48118eae55a70e0c2e2032326f54d7e1d/pkg/ui/src/redux/apiReducers.ts#L226)):*
> ```XML
>   api.getSettings,
>   "settings",
>   moment.duration(0),
> ```

weird but fine I guess

---

*[pkg/ui/src/views/reports/containers/settings/index.tsx, line 19 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24064#-L82pNe6aoRcNmq4rfeI:-L82pNe6aoRcNmq4rfeJ:bxl57ul) ([raw file](https://github.com/cockroachdb/cockroach/blob/b713e0d48118eae55a70e0c2e2032326f54d7e1d/pkg/ui/src/views/reports/containers/settings/index.tsx#L19)):*
> ```XML
> }
> 
> type SettingsProps = SettingsOwnProps & RouterState;
> ```

is `RouterState` needed here?

---

*[pkg/ui/src/views/reports/containers/settings/index.tsx, line 30 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24064#-L82pTegGu5LRfXC09IG:-L82pTehPjHc5ylYAQDV:bec4xz0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b713e0d48118eae55a70e0c2e2032326f54d7e1d/pkg/ui/src/views/reports/containers/settings/index.tsx#L30)):*
> ```XML
> 
>   componentWillMount() {
>     // Refresh nodes status query when mounting.
> ```

copy-pasta

---

*[pkg/ui/src/views/reports/containers/settings/index.tsx, line 35 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24064#-L82q9hlhnMpy67sX1nn:-L82q9hmbmtrqchTpk1t:bkx0p3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b713e0d48118eae55a70e0c2e2032326f54d7e1d/pkg/ui/src/views/reports/containers/settings/index.tsx#L35)):*
> ```XML
> 
>   renderTable() {
>     if (_.isNil(this.props.settings.data)) {
> ```

too bad this is necessary despite the loading condition below... something to think about when we redo `Loading`

---

*[pkg/ui/src/views/reports/containers/settings/index.tsx, line 82 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24064#-L82pCH_6QGEvJwm3hQt:-L82pCH_6QGEvJwm3hQu:b-lku4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/b713e0d48118eae55a70e0c2e2032326f54d7e1d/pkg/ui/src/views/reports/containers/settings/index.tsx#L82)):*
> ```XML
>       <div className="section">
>         <h1>Cluster Settings</h1>
>         <h2>List of all cluster settings</h2>
> ```

seems excessive

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24064#-:-L82qH7rot9gEwIU3EY0:bnfp4nl)*

**Comment by BramGruneir** [comment]
Review status: 5 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/ui/src/index.tsx, line 55 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24064#-L82UaZkXbiUVgOJpaQ1:-L83GQYKgX1GM3H2BV6-:b-71nhhg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b713e0d48118eae55a70e0c2e2032326f54d7e1d/pkg/ui/src/index.tsx#L55)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

:+1: for the cleanup :-1: for only one commit
</blockquote></details>

If I did anything more I would have split it out.  

---

*[pkg/ui/src/redux/apiReducers.ts, line 226 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24064#-L82oDuRuvSfBNeyfnmq:-L83GcKiJ7uP1si3FtiC:b-f43nca) ([raw file](https://github.com/cockroachdb/cockroach/blob/b713e0d48118eae55a70e0c2e2032326f54d7e1d/pkg/ui/src/redux/apiReducers.ts#L226)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

weird but fine I guess
</blockquote></details>

This just means refresh it every time.  See a number of the other reducers that do the same.

---

*[pkg/ui/src/views/reports/containers/settings/index.tsx, line 19 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24064#-L82pNe6aoRcNmq4rfeI:-L83GnXz9xbF5JmtMQ8c:bzi1hnh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b713e0d48118eae55a70e0c2e2032326f54d7e1d/pkg/ui/src/views/reports/containers/settings/index.tsx#L19)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

is `RouterState` needed here?
</blockquote></details>

Nope, removed.

---

*[pkg/ui/src/views/reports/containers/settings/index.tsx, line 30 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24064#-L82pTegGu5LRfXC09IG:-L83U6wORphhvhkIJHGn:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/b713e0d48118eae55a70e0c2e2032326f54d7e1d/pkg/ui/src/views/reports/containers/settings/index.tsx#L30)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

copy-pasta
</blockquote></details>

fixed

---

*[pkg/ui/src/views/reports/containers/settings/index.tsx, line 35 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24064#-L82q9hlhnMpy67sX1nn:-L83SyxVv2Hbhg3P8wBu:b-pb9bue) ([raw file](https://github.com/cockroachdb/cockroach/blob/b713e0d48118eae55a70e0c2e2032326f54d7e1d/pkg/ui/src/views/reports/containers/settings/index.tsx#L35)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

too bad this is necessary despite the loading condition below... something to think about when we redo `Loading`
</blockquote></details>

indeed

---

*[pkg/ui/src/views/reports/containers/settings/index.tsx, line 82 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24064#-L82pCH_6QGEvJwm3hQt:-L83T-ZUgoykj7DOJIqX:b-ax47e6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b713e0d48118eae55a70e0c2e2032326f54d7e1d/pkg/ui/src/views/reports/containers/settings/index.tsx#L82)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

seems excessive
</blockquote></details>

To be honest, it was mostly for spacing purposes.  I removed the wording but left in a blank h2.  This keeps the same spacing as the other debug pages.  I'm not going to mess with the css for it right now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24064)*

**Comment by couchand** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24064)*

**Pull request merged**
