### PR TITLE
jobs: record creation cluster ID and version

### PR DESCRIPTION
**Pull request by dt**
Release note: none.

### CODE REVIEW

**Comment by dt** [comment]
added comments to the fields

**Comment by miretskiy** [comment]
To confirm: Do we want this on jobs level? and not per-job implementation?

**Comment by dt** [comment]
> Do we want this on jobs level?  and not per-job implementation?

Jobs level here is just capturing the info about when a job was made; what to do with it is up to per-job logic.

**Review by irfansharif — APPROVED** [review]

**Comment by dt** [comment]
@miretskiy did you have a concern about it or just curious about the expected usage?

**Comment by dt** [comment]
TFTR!

bors r+

**Pull request merged**
