### PR TITLE
build: fix testlogic targets

### PR DESCRIPTION
**Pull request by jordanlewis**
Previously, the testlogic targets were broken - their dependency
analysis did not work properly. This was the result of the behavior of
bin/prereqs: it generates a target based on the basename of the package
you pass it. Despite this, the Makefile expected that the target would
be generated based on the name of the resultant output binary - a
tautology.

This bug is corrected by introducing an optional flag to bin/prereqs,
-bin-name, that permits customization of the binary name that's being
targeted for dependency analysis.

Release note: None

### CODE REVIEW

**Comment by benesch** [comment]
Why can’t logictestbase and logictestplanner continue to share a dependency
on bin/logictest?

P.S. yayayaya nice find

**Comment by jordanlewis** [comment]
Hmm, seems like they should be able to. What I don't understand is why `testplannerlogic` was broken despite having the correct mapping from package to bin, though.

**Comment by jordanlewis** [comment]
Either way, restored the old targets, and things seem to work still!

**Review by benesch — APPROVED** [review]
Thanks for tracking this down!! 🎉🎉🎉

**Comment by jordanlewis** [comment]
TFTR!

bors r+

**Comment by jordanlewis** [comment]
Flake?

bors r+

**Comment by benesch** [comment]
Definite flake.

**Comment by knz** [comment]
thank you jordan!

**Pull request merged**
