### PR TITLE
release-2.1: distsql: fix memory accounting in StreamGroupAccumulator

### PR DESCRIPTION
**Pull request by rjnn**
Backport 1/1 commits from #30085.

/cc @cockroachdb/release

Release note (bug fix): fix a bug where certain queries, like merge
joins, would fail due to appearing to run out of memory due to
incorrect memory accounting.

### CODE REVIEW

**Review by asubiotto — APPROVED** [review]

**Comment by arjunravinarayan** [comment]
@petermattis how would you like this regression tested? In general we don't have good test coverage of our memory accounting because its difficult to test it without throwing lots of data at it. We could theoretically carefully set up a small query, and set up the memory limits just low enough that it would be tripped by incorrect memory usage, but that seems like a lot of work. It's certainly not something we do throughout our codebase.

**Comment by RaduBerinde** [comment]
I'd say let's file an issue to work on some tests for this, and other processors with memory accounting. Yes, the general approach for would be to run queries against small limits, but figuring out exactly how to do it is not trivial.

**Comment by petermattis** [comment]
> @petermattis how would you like this regression tested? In general we don't have good test coverage of our memory accounting because its difficult to test it without throwing lots of data at it. We could theoretically carefully set up a small query, and set up the memory limits just low enough that it would be tripped by incorrect memory usage, but that seems like a lot of work. It's certainly not something we do throughout our codebase.

I don't have a concrete suggestion right now, but I'll note that sometimes adding a test for a fix is more involved than the fix itself. The fact that we don't have good infrastructure for testing that memory accounting is being done properly is likely a huge cause of the number of problems we continue to encounter with it. Seems to me that we should be able to test `streamGroupAccumulator` in isolation and to verify that each call to `nextGroup` leaves the memory account at 0.

**Comment by arjunravinarayan** [comment]
OK. @petermattis I will file an issue to do more comprehensive followup testing as @RaduBerinde suggests, and otherwise merge this PR.

@asubiotto there was a test failure due to the `EXPLAIN ANALYZE` plans changing (and using less memory, heh), which I've fixed up. PTAL, just to be absolutely sure.

**Pull request merged**
