### PR TITLE
descs: fix in-memory uncommitted descriptor check-out bug

### LINKED ISSUE #77769: sql/catalog: race found by TestClusterVersionUpgrade
`TestClusterVersionUpgrade` failed twice in a row on CI for me with the following race.
@postamar you seem to have touched the relevant code the other day.,

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/4565533?buildTab=artifacts#%2Ftest;%2Ftestrace%2FlogTestClusterVersionUpgrade2390230646;%2Ftestrace%2Fraw.0.json.txt.tgz

```
WARNING: DATA RACE
Read at 0x00000b85b460 by goroutine 1196:
  runtime.racereadrange()
      <autogenerated>:1 +0x1b
  github.com/cockroachdb/cockroach/pkg/sql/catalog/nstree.makeByNameItem()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/nstree/by_name.go:30 +0x6a
  github.com/cockroachdb/cockroach/pkg/sql/catalog/nstree.byNameMap.upsert()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/nstree/by_name_map.go:24 +0x69
  github.com/cockroachdb/cockroach/pkg/sql/catalog/nstree.(*Map).Upsert()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/nstree/map.go:39 +0x67
  github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*uncommittedDescriptors).maybeAddSystemDatabase()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/uncommitted_descriptors.go:375 +0x104
  github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*uncommittedDescriptors).getByName()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/uncommitted_descriptors.go:256 +0xa1
  github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getByName()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:293 +0x2e4
  github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getDatabaseByName()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/database.go:63 +0xcf
  github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).GetImmutableDatabaseByName()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/database.go:45 +0x16c
  github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getObjectByNameIgnoringRequiredAndType()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/object.go:157 +0x111
  github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getObjectByName()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/object.go:64 +0x264
  github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).GetObjectDesc()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/object.go:39 +0x12b
  github.com/cockroachdb/cockroach/pkg/sql.(*planner).LookupObject()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/resolver.go:200 +0x78c
  github.com/cockroachdb/cockroach/pkg/sql/catalog/resolver.ResolveExisting()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/resolver/resolver.go:435 +0x605
  github.com/cockroachdb/cockroach/pkg/sql/catalog/resolver.ResolveExistingObject()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/resolver/resolver.go:194 +0x1ec
  github.com/cockroachdb/cockroach/pkg/sql/catalog/resolver.ResolveExistingTableObject()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/resolver/resolver.go:122 +0x39c
  github.com/cockroachdb/cockroach/pkg/sql.(*optCatalog).ResolveDataSource()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt_catalog.go:208 +0x2e9
  github.com/cockroachdb/cockroach/pkg/sql/opt.(*Metadata).CheckDependencies()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/metadata.go:293 +0x1b8
  github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*Memo).IsStale()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/memo/memo.go:333 +0x14b2
  github.com/cockroachdb/cockroach/pkg/sql.(*planner).prepareUsingOptimizer()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:119 +0xd51
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).populatePrepared()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:278 +0x257
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).prepare.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:235 +0x7e4
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).prepare()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:240 +0x421
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).addPreparedStmt()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:102 +0x14f
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPrepare()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:63 +0x4da
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1948 +0x1ba5
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1779 +0x4f5
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).initConnEx.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:205 +0xcd

Previous write at 0x00000b85b460 by goroutine 1231:
  github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*uncommittedDescriptor).checkOut()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/uncommitted_descriptors.go:92 +0x36
  github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*uncommittedDescriptors).checkOut()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/uncommitted_descriptors.go:181 +0x22d
  github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*byIDLookupContext).lookupUncommitted()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:217 +0x177
  github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*byIDLookupContext).lookupUncommitted-fm()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:208 +0x44
  github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getDescriptorsByID()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:119 +0xa4c
  github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).GetMutableDescriptorsByID()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:40 +0xd5
  github.com/cockroachdb/cockroach/pkg/migration/migrations.runPostDeserializationChangesOnAllDescriptors.func1.1()
      /go/src/github.com/cockroachdb/cockroach/pkg/migration/migrations/descriptor_utils.go:81 +0xa4
  github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*CollectionFactory).Txn.func2()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/txn.go:85 +0x49c
  github.com/cockroachdb/cockroach/pkg/kv.runTxn.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:948 +0x51
  github.com/cockroachdb/cockroach/pkg/kv.(*Txn).exec()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:980 +0xb0
  github.com/cockroachdb/cockroach/pkg/kv.runTxn()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:947 +0x84
  github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:910 +0xbd
  github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*CollectionFactory).Txn()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/txn.go:71 +0x20a
  github.com/cockroachdb/cockroach/pkg/migration/migrations.runPostDeserializationChangesOnAllDescriptors.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/migration/migrations/descriptor_utils.go:78 +0xc4
  github.com/cockroachdb/cockroach/pkg/migration/migrations.runPostDeserializationChangesOnAllDescriptors()
      /go/src/github.com/cockroachdb/cockroach/pkg/migration/migrations/descriptor_utils.go:134 +0x529
  github.com/cockroachdb/cockroach/pkg/migration/migrations.runRemoveInvalidDatabasePrivileges()
      /go/src/github.com/cockroachdb/cockroach/pkg/migration/migrations/remove_invalid_database_privileges.go:29 +0x87
  github.com/cockroachdb/cockroach/pkg/migration.(*TenantMigration).Run()
      /go/src/github.com/cockroachdb/cockroach/pkg/migration/tenant_migration.go:93 +0x1ed
  github.com/cockroachdb/cockroach/pkg/migration/migrationjob.resumer.Resume()
      /go/src/github.com/cockroachdb/cockroach/pkg/migration/migrationjob/migration_job.go:97 +0x804
  github.com/cockroachdb/cockroach/pkg/migration/migrationjob.(*resumer).Resume()
      <autogenerated>:1 +0x85
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func2()
      /go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1124 +0x164
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine()
      /go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1125 +0x8db
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob()
      /go/src/github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:408 +0x6ab
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).resumeJob.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:329 +0x125
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:494 +0x235
```

Jira issue: CRDB-13761

### PR DESCRIPTION
**Pull request by postamar**
For performance reasons, the system database descriptor is never read
from storage. It never changes significantly so we use an in-memory copy
which is immutable and is shared by all descriptor collection instances.
Recent changes added a check-out status to the uncommitted descriptor
wrapper which is set when a mutable descriptor is requested. This never
happens for the system database, except, it turns out, during descriptor
migrations which operate on all descriptors. This is turn causes a data
race.

This commit fixes this race by not setting the check-out status for
these in-memory descriptors. This has no impact on functionality.

Fixes #77769

Release justification: bug fix
Release note: None

### CODE REVIEW

**Comment by postamar** [comment]
CI failure appears to be a flake. Re-running.

**Review by ajwerner — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77782#-:-My8h1t16hzVDEYbFDM2:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/catalog/descs/uncommitted_descriptors.go, line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77782#-My8h9aLCGroDnNLCVK6:-My8h9aLCGroDnNLCVK7:b3aze6e) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a7e116016387e6fddca9c8be07584412e3441d9/pkg/sql/catalog/descs/uncommitted_descriptors.go#L92)):*
> ```Go
> // checkOut is how the mutable descriptor should be accessed.
> func (u *uncommittedDescriptor) checkOut() catalog.MutableDescriptor {
> 	if u.mutable == nil {
> ```

Can we note that this case indicates that this is a special in-memory descriptor? Without commentary, it takes a good bit of context to understand this.

**Review by postamar — COMMENTED** [review]
Thanks for the review.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77782#-:-My8iXAiAsNo4Q4Qh-pR:b-9qdoyq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/catalog/descs/uncommitted_descriptors.go, line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77782#-My8h9aLCGroDnNLCVK6:-My8iTpA3h8F40KIlek0:b-8n327p) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a7e116016387e6fddca9c8be07584412e3441d9/pkg/sql/catalog/descs/uncommitted_descriptors.go#L92)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Can we note that this case indicates that this is a special in-memory descriptor? Without commentary, it takes a good bit of context to understand this. 
</blockquote></details>

Yes, good point.

**Pull request merged**
