### PR TITLE
sql, cli/sql: provide a "safe updates" mode for interactive sessions

### LINKED ISSUE #3943: cli: interactive client lets user drop entire non-empty database or table without confirmation
Currently, you can run `drop database` on a db that contains tables. When chatting with @vivekmenezes, he suggested that we might want that intention to be explicit in the command; in other words, running just `drop database` on a database containing tables would return an error. 

Also, noticed that you can drop a database even when you're connected to it. Postgres doesn't let you do that: "This command cannot be executed when connected to the target database." http://www.postgresql.org/docs/9.5/static/sql-dropdatabase.html

```
JESSEs-MBP.home:26257> set database = test;
OK
JESSEs-MBP.home:26257> show database;
+----------+
| DATABASE |
+----------+
| test     |
+----------+
JESSEs-MBP.home:26257> CREATE TABLE weather (
                    ->     city            string(80),
                    ->     temp_lo         int,           -- low temperature
                    ->     temp_hi         int,           -- high temperature
                    ->     prcp            float,          -- precipitation
                    ->     date            date
                    -> );
OK
JESSEs-MBP.home:26257> show tables;
+---------+
|  Table  |
+---------+
| weather |
+---------+
JESSEs-MBP.home:26257> drop database test;
OK
JESSEs-MBP.home:26257> show databases;
+----------+
| Database |
+----------+
| system   |
+----------+
JESSEs-MBP.home:26257> show tables;
query error: database "test" does not exist
```

### LINKED ISSUE #17546: sql: SELECT * FROM generate_series() vs SELECT FROM generate_series()
I was surprised with @tso to find out that there's a difference between the two. The 2nd one doesn't seem to produce results until the function terminates producing the whole result table, whereas the first one "streams" results out. Is that expected?

### PR DESCRIPTION
**Pull request by knz**
New SQL session variable `sql_safe_updates` to prevent users from having data accidents. Enable with `cockroach sql --safe-updates` or the SET statement.

Fixes #3943.

cc @bdarnell

### CODE REVIEW

**Comment by bdarnell** [comment]
Review status: 0 of 23 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/alter_table.go, line 174 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17604#-KrTrcZ0GkhaXYEqbGd3:-KrTrcZ0GkhaXYEqbGd4:b-5w2ndn) ([raw file](https://github.com/cockroachdb/cockroach/blob/c853e9141e999d82e5282b6f1a60b9c81b8d787e/pkg/sql/alter_table.go#L174)):*
> ```Go
> 		case *parser.AlterTableDropColumn:
> 			if params.p.session.SafeUpdates {
> 				return pgerror.NewDangerousStatementErrorf("ALTER TABLE DROP COLUMN will remove all data in that column")
> ```

MySQL's version of this option only applies to DELETE and UPDATE without a where clause, and not all potentially-destructive statements. This is because `DELETE FROM tbl` could have been intended as a prefix of a less-destructive `DELETE FROM tbl WHERE ...`.  That's not true for the `DROP` statements; a user typing `DROP` must have intended to drop something (also, DROP requires different permissions). I think we should do the same if we implement this feature, and apply it only to "missing where clauses" instead of all destructive commands. 

---

*[pkg/sql/session.go, line 162 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17604#-KrTaWa3V8GSPX9eDw6p:-KrTaWa3V8GSPX9eDw6q:b3nta9y) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fe7c8fb527c26dd480486fd869c77f6a46bf64a/pkg/sql/session.go#L162)):*
> ```Go
> 	// PedanticSQL causes errors when the client sends syntax that
> 	// CockroachDB supports for compatibility but which we'd rather
> 	// them not use. The error should suggest an alternative.
> ```

Why would we rather they not use it? Because it's error-prone, because it's going to be removed in the future, because it's not standard, because it's not portable? Why would a user opt in to this mode?  

I don't think a "pedantic" option is a good idea. It's not worth the complexity (which includes both a user-visible session variable that will need to be documented and code that is prone to rot like our verbose log messages) and doesn't offer clear value to the user.

Also, I think the pgwire protocol can return "notices" along with query results, so that's another way to get warnings if we want to do that.

---

*[pkg/sql/parser/type_check.go, line 160 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17604#-KrT_za0dDKLgqFIr3u0:-KrT_za0dDKLgqFIr3u1:b-dlyx5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7e350c136d7c9bb46653fb11f21221be694ef4d/pkg/sql/parser/type_check.go#L160)):*
> ```Go
> 		return nil,
> 			pgerror.NewErrorf(pgerror.CodeAmbiguousFunctionError,
> 				ambiguousBinaryOpErrFmt, sig).SetHintf(candidatesHintFmt, fnsStr)
> ```

I'm slightly concerned that moving information from the error text to "hints" or "details" will make it less accessible if client libraries require additional effort to display this information. Nothing here seems too crucial, but it's something to watch out for (and to compare with postgres)

---

*[pkg/sql/pgwire/pgerror/errors.go, line 51 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17604#-KrTrFmhiDnCw1u6udbu:-KrTrFmhiDnCw1u6udbv:b-pf6sm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c853e9141e999d82e5282b6f1a60b9c81b8d787e/pkg/sql/pgwire/pgerror/errors.go#L51)):*
> ```Go
> 	buf.WriteString("rejected: ")
> 	fmt.Fprintf(&buf, format, args...)
> 	buf.WriteString(" (reject_dangerous_statements = true)")
> ```

`reject_dangerous_statements` appears nowhere but this message (and comments). Should probably be `sql_safe_updates` instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17604)*

**Comment by knz** [comment]
I dropped the commit adding a pedantic mode in favor of #17835 which addresses the original motivation for it.

**Comment by knz** [comment]
Review status: 0 of 19 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/sql/alter_table.go, line 174 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17604#-KrTrcZ0GkhaXYEqbGd3:-KsEHUqcT0mI5TnQmnCe:b-z4dqyy) ([raw file](https://github.com/cockroachdb/cockroach/blob/c853e9141e999d82e5282b6f1a60b9c81b8d787e/pkg/sql/alter_table.go#L174)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

MySQL's version of this option only applies to DELETE and UPDATE without a where clause, and not all potentially-destructive statements. This is because `DELETE FROM tbl` could have been intended as a prefix of a less-destructive `DELETE FROM tbl WHERE ...`.  That's not true for the `DROP` statements; a user typing `DROP` must have intended to drop something (also, DROP requires different permissions). I think we should do the same if we implement this feature, and apply it only to "missing where clauses" instead of all destructive commands. 
</blockquote></details>

So I agree for DROP TABLE / DROP COLUMN.

However I maintain my position that specifically ALTER TABLE DROP COLUMN should be handled here. 

That's because ALTER merely requires the permission "CREATE" which in its name implies "adding new data and not destroying anything". In Postgres, actually ALTER TABLE is not subject to privileges, instead only the superuser and the "owner" (a concept that doesn't exist yet in CockroachDB, but is akin to "root for this specific table") can use ALTER TABLE. 

Until we teach CockroachDB to be somewhat more strict like pg, I believe that there will be users who will prefer to be guarded against ALTER TABLE DROP COLUMN.

---

*[pkg/sql/drop.go, line 77 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/17604#-KsEI7vvqtkJT93b29Rn:-KsEI7vvqtkJT93b29Ro:b-acl81) ([raw file](https://github.com/cockroachdb/cockroach/blob/3eab21644d6f215a0f9da81d4aa38c791cef2573/pkg/sql/drop.go#L77)):*
> ```Go
> 		return nil, pgerror.NewDangerousStatementErrorf(
> 			"database is not empty; DROP DATABASE will delete all contents recursively")
> 	}
> ```

In addition to the permission check on DROP DATABASE, this protection addresses #3943 which motivated the change in the first place.

---

*[pkg/sql/session.go, line 162 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17604#-KrTaWa3V8GSPX9eDw6p:-KsEIIRS0wDb1w-PW6So:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fe7c8fb527c26dd480486fd869c77f6a46bf64a/pkg/sql/session.go#L162)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Why would we rather they not use it? Because it's error-prone, because it's going to be removed in the future, because it's not standard, because it's not portable? Why would a user opt in to this mode?  

I don't think a "pedantic" option is a good idea. It's not worth the complexity (which includes both a user-visible session variable that will need to be documented and code that is prone to rot like our verbose log messages) and doesn't offer clear value to the user.

Also, I think the pgwire protocol can return "notices" along with query results, so that's another way to get warnings if we want to do that.
</blockquote></details>

Removed.

---

*[pkg/sql/parser/type_check.go, line 160 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17604#-KrT_za0dDKLgqFIr3u0:-KsEISjGvUnLxUbumZD-:b8lj1cy) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7e350c136d7c9bb46653fb11f21221be694ef4d/pkg/sql/parser/type_check.go#L160)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I'm slightly concerned that moving information from the error text to "hints" or "details" will make it less accessible if client libraries require additional effort to display this information. Nothing here seems too crucial, but it's something to watch out for (and to compare with postgres)
</blockquote></details>

Yes in this case I did look at pg. pg doesn't show which overloads caused the error at all, so here we provide strictly more information. I do not want to see the overload list in the summary message, because it can get quite long in some cases.

---

*[pkg/sql/pgwire/pgerror/errors.go, line 51 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17604#-KrTrFmhiDnCw1u6udbu:-KsEIbuvQXbIvFYE3aNf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c853e9141e999d82e5282b6f1a60b9c81b8d787e/pkg/sql/pgwire/pgerror/errors.go#L51)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

`reject_dangerous_statements` appears nowhere but this message (and comments). Should probably be `sql_safe_updates` instead.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17604)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 1 of 22 files at r4, 17 of 17 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17604#-:-KsFrsltKaA9K6YLiTc4:bnfp4nl)*

**Comment by knz** [comment]
TFYR!

**Pull request merged**
