### PR TITLE
util: fastintset fixes and improvements

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### util: fix FastIntSet.Next and ForEach with negative numbers

These methods assume that we only insert non-negative elements
(whereas the rest of the API allows that case). This commit fixes this
and improves the test to include negative elements.

Release note: None

#### util: remove FastIntSet.Shift

This method is not used anymore.

Release note: None

#### util: fix FastIntSet.Encode edge case

Encode has an edge case where we incorrectly encode a set that has the
large field set but which is empty. This commit fixes this and adds
tests for Encode/Decode.

Also, before this change Encode could choose either encoding for a
"small" set depending whether `large` was allocated. Although this
doesn't break the documented contract, it is not ideal to leak this
internal detail.

This change also cleans up the code a bit (the semantics of
`largeToSmall` are left over from an earlier implementation).

Release note: None

#### fastintset: reduce allocations from FastIntSet.Encode

The current implementation of Encode causes allocations: the temporary
array escapes to the heap because it is passed through an opaque
interface call.

This change fixes this by passing a `bytes.Buffer` specifically.

`Prepared/ExecBuild` benchmark results:
```
name                                                   old time/op    new time/op    delta
Phases/kv-read/Prepared/ExecBuild                        1.46µs ± 2%    1.40µs ± 2%   -4.04%  (p=0.000 n=10+10)
Phases/kv-read-const/Prepared/ExecBuild                  1.24µs ± 2%    1.14µs ± 2%   -8.03%  (p=0.000 n=10+10)
Phases/tpcc-new-order/Prepared/ExecBuild                 1.79µs ± 2%    1.69µs ± 2%   -5.67%  (p=0.000 n=10+9)
Phases/tpcc-delivery/Prepared/ExecBuild                  33.0µs ± 1%    33.7µs ± 5%   +2.19%  (p=0.001 n=10+10)
Phases/tpcc-stock-level/Prepared/ExecBuild                143µs ± 2%     141µs ± 2%     ~     (p=0.280 n=10+10)
Phases/many-columns-and-indexes-a/Prepared/ExecBuild      511µs ± 1%     515µs ± 2%     ~     (p=0.218 n=10+10)
Phases/many-columns-and-indexes-b/Prepared/ExecBuild      529µs ± 1%     543µs ± 4%   +2.77%  (p=0.004 n=10+10)
Phases/ored-preds-100/Prepared/ExecBuild                  116µs ± 1%     118µs ± 4%   +1.35%  (p=0.029 n=10+10)
Phases/ored-preds-using-params-100/Prepared/ExecBuild    1.41ms ± 2%    1.41ms ± 3%     ~     (p=0.971 n=10+10)
name                                                   old alloc/op   new alloc/op   delta
Phases/kv-read/Prepared/ExecBuild                          704B ± 0%      656B ± 0%   -6.82%  (p=0.000 n=10+10)
Phases/kv-read-const/Prepared/ExecBuild                    520B ± 0%      472B ± 0%   -9.23%  (p=0.000 n=10+10)
Phases/tpcc-new-order/Prepared/ExecBuild                   768B ± 0%      720B ± 0%   -6.25%  (p=0.000 n=10+10)
Phases/tpcc-delivery/Prepared/ExecBuild                  11.1kB ± 0%    11.1kB ± 0%   -0.39%  (p=0.000 n=10+6)
Phases/tpcc-stock-level/Prepared/ExecBuild               39.5kB ± 0%    39.5kB ± 0%   -0.12%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-a/Prepared/ExecBuild     5.02kB ± 0%    4.98kB ± 0%   -0.80%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-b/Prepared/ExecBuild     7.46kB ± 0%    7.42kB ± 0%   -0.53%  (p=0.000 n=10+10)
Phases/ored-preds-100/Prepared/ExecBuild                 29.6kB ± 0%    29.6kB ± 0%   -0.16%  (p=0.000 n=10+10)
Phases/ored-preds-using-params-100/Prepared/ExecBuild     765kB ± 0%     765kB ± 0%   -0.01%  (p=0.005 n=10+10)
name                                                   old allocs/op  new allocs/op  delta
Phases/kv-read/Prepared/ExecBuild                          11.0 ± 0%       9.0 ± 0%  -18.18%  (p=0.000 n=10+10)
Phases/kv-read-const/Prepared/ExecBuild                    8.00 ± 0%      6.00 ± 0%  -25.00%  (p=0.000 n=10+10)
Phases/tpcc-new-order/Prepared/ExecBuild                   11.0 ± 0%       9.0 ± 0%  -18.18%  (p=0.000 n=10+10)
Phases/tpcc-delivery/Prepared/ExecBuild                    75.0 ± 0%      73.0 ± 0%   -2.67%  (p=0.000 n=10+10)
Phases/tpcc-stock-level/Prepared/ExecBuild                  249 ± 0%       247 ± 0%   -0.80%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-a/Prepared/ExecBuild       34.0 ± 0%      32.0 ± 0%   -5.88%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-b/Prepared/ExecBuild       53.0 ± 0%      51.0 ± 0%   -3.77%  (p=0.000 n=10+10)
Phases/ored-preds-100/Prepared/ExecBuild                    415 ± 0%       413 ± 0%   -0.48%  (p=0.000 n=10+10)
Phases/ored-preds-using-params-100/Prepared/ExecBuild     3.29k ± 0%     3.29k ± 0%   -0.06%  (p=0.000 n=10+10)
```

Release note: None

#### fastintset: fix fast_int_set_small/fast_int_set_large test builds

This commit adds Encode/Decode to the test-only implementation which
unbreaks the test builds with `fast_int_set_small` or
`fast_int_set_large` tags.

Release note: None

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73627#-:-MqRYtBi7UjNYsJFEn78:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach)

**Review by cucaroach — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73627)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/util/fast_int_set.go, line 299 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73627#-MqUwlLYE_d2ffYRIrve:-MqUwlLYE_d2ffYRIrvf:b-7z4gkk) ([raw file](https://github.com/cockroachdb/cockroach/blob/569dc372a2f598024a24ebc4526227902152edb8/pkg/util/fast_int_set.go#L299)):*
> ```Go
> 	}
> 	if s.fitsInSmall() {
> 		return rhs.fitsInSmall()
> ```

Shouldn't this be doing an equality comparison?   Unit test opportunity?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73627)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach)

___
*[pkg/util/fast_int_set.go, line 299 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73627#-MqUwlLYE_d2ffYRIrve:-MqVETDq0Q1Q6L5brIci:bf2sx61) ([raw file](https://github.com/cockroachdb/cockroach/blob/569dc372a2f598024a24ebc4526227902152edb8/pkg/util/fast_int_set.go#L299)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

Shouldn't this be doing an equality comparison?   Unit test opportunity?
</blockquote></details>

We already checked `s.small != rhs.small` above.

**Comment by RaduBerinde** [comment]
___
*[pkg/util/fast_int_set.go, line 299 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73627#-MqUwlLYE_d2ffYRIrve:-MqVEWxxDLxubcolcoVY:b-994evd) ([raw file](https://github.com/cockroachdb/cockroach/blob/569dc372a2f598024a24ebc4526227902152edb8/pkg/util/fast_int_set.go#L299)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We already checked `s.small != rhs.small` above.
</blockquote></details>

I'll add a comment though.

**Review by cucaroach — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73627)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @RaduBerinde)

___
*[pkg/util/fast_int_set.go, line 299 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73627#-MqUwlLYE_d2ffYRIrve:-MqVdLm24euJ8COB8Sms:bc4vnq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/569dc372a2f598024a24ebc4526227902152edb8/pkg/util/fast_int_set.go#L299)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I'll add a comment though.
</blockquote></details>

What if they are both large ones that lost bits and now fit in small but are still using large rep?  Won't small be equal in that case?   Or is there some invariant that if it fits in small we convert it immediately back from large rep to small?

**Comment by RaduBerinde** [comment]
___
*[pkg/util/fast_int_set.go, line 299 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73627#-MqUwlLYE_d2ffYRIrve:-MqW0MOKBF_BmRkBfieE:b-xwscl6) ([raw file](https://github.com/cockroachdb/cockroach/blob/569dc372a2f598024a24ebc4526227902152edb8/pkg/util/fast_int_set.go#L299)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

What if they are both large ones that lost bits and now fit in small but are still using large rep?  Won't small be equal in that case?   Or is there some invariant that if it fits in small we convert it immediately back from large rep to small?
</blockquote></details>

The `small` field always reflects the elements 0..63, regardless if we have a large set. If `fitsInSmall()` is true, then `x.small` contains all the information (even if we also have a large set).

**Review by cucaroach — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73627#-:-MqWexcsA5lyaomFDHYf:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

___
*[pkg/util/fast_int_set.go, line 299 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73627#-MqUwlLYE_d2ffYRIrve:-MqWdS1o3wcAdVc35qTH:b8da0i7) ([raw file](https://github.com/cockroachdb/cockroach/blob/569dc372a2f598024a24ebc4526227902152edb8/pkg/util/fast_int_set.go#L299)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The `small` field always reflects the elements 0..63, regardless if we have a large set. If `fitsInSmall()` is true, then `x.small` contains all the information (even if we also have a large set).
</blockquote></details>

Ah makes sense.

**Pull request merged**
