### PR TITLE
util/log,cli: channel abstraction; new configuration system

### PR DESCRIPTION
**Pull request by knz**
(This PR chips away at #51987 to make it smaller. Still, it's a large-ish change. To ease the review, I added an "incremental changes" summary below which the reviewer can use as reading guide.)

tldr: this patch refactors the logging code to use channels instead of
secondary loggers, and applies a new YAML-based configuration system.

**Background**

Previously, log channels were defined via secondary loggers: there
were separate secondary loggers for audit logs, for
Pebble, etc. This infrastructure was unsatisfactory:

- certain users have expressed the desire to refine logging streams,
  by splitting e.g. configuration changes and monitoring data
  into their dedicated logging outputs.

  As we foresee that the number of distinct streams may increase over
  time, the requirement to define a secondary logger object for each
  stream becomes cumbersome: we then need to hold into each logger's
  state (multiple `*SecondaryLogger` pointers stored at every
  component that logs multiple streams) and for each make separate
  choices wrt logging directory, etc.

- the secondary logger abstraction excessively conflates logical event
  channels, which correspond to different “categories” of events,
  together with the separation of logging outputs.

  In practice, we find that some users want multiple event categories go
  to e.g. the same file. Later, as we introduce more various sinks,
  we want to offer the option to redirect multiple event categories
  to the same sink.

- it was possible to define multiple loggers using the same filenames
  and the same directory destination, but with competing GC and
  rotation parameters.

**Channels**

To address these shortcomings, this patch de-publicizes the secondary
logger abstraction and supersedes it with the notion of
logging *channel*, which is a logical/virtual log stream. Each event
in a given logger (logging output) belongs to exactly one
channel. There can be events from multiple channels emitted to one
logger.

In accordance with expressed user requirements, the following streams
are defined here:

- DEV (current “default” log): development logging.
- STORAGE (current RocksDB/pebble log): low-level storage events.
  This will include events currently sent to the current "pebble"
  and "rocksdb" secondary logger.
- SESSIONS: client connections and session/query cancellation.
  This will include events currently sent to the current "auth"
  secondary logger.
- SENSITIVE_ACCESS: operations that access sensitive data (when enabled).
  This will include events currently sent to the current "sql audit"
  secondary logger.
- SQL_EXEC: SQL execution logging (when enabled).
  This will include events currently sent to the current "sql exec"
  secondary logger.
- SQL_PERF: SQL performance events (when enabled)
  This will include events currently sent to the current "sql slow"
  secondary logger ("Slow query log").
- SQL_INTERNAL_PERF: ditto SQL_PERF, for internal queries.

**File output**

The file logging format now embeds the channel ID numerically as a
prefix to the filename.

The location of the prefix on the log line is chosen to be
backward-compatible with log parsers built for previous versions of
CockroachDB, which would be unable to handle additional fields on the
line.

For example:

```
E200727 11:57:22.907515 1392 1@sql/conn_executor.go:492  [n1] panic: woo
                             ^^ channel ID 1 = OPS
```

This prefix is omitted if the ID is 0 (DEV). Conversely, when parsing
an existing log file, a missing ID is considered to be an event on the
DEV channel. This makes the parser in the new version able to parse
entries emitted by previous versions.

**Configuration format**

The configuration can now be specified via YAML,
using a new command line flag `--log`.

The format works as follows:

```
file-defaults: #optional
  dir: <path>          # output directory, defaults to first store dir
  filter: <severity>   # min severity level for file output, default INFO
  redact: <bool>       # whether to remove sensitive info, default false
  redactable: <bool>   # whether to strip redaction markers, default false
  max-file-size: <sz>  # max log file size, default 10MB
  max-group-size: <sz> # max log file group size, default 100MB

sinks: #optional
 stderr: #optional
  filter: <severity>   # min severity level for stderr output, default NONE
  channels: <chans>    # channel selection for stderr output, default ALL
  redact: <bool>       # whether to remove sensitive info, default false
  redactable: <bool>   # whether to strip redaction markers, default false
  nocolor: <bool>      # disable VT color codes, default is to enable color

 file-groups: #optional
   <filename>:
     channels: <chans>    # channel selection for this file output, mandatory
     filter: <severity>   # defaults to file-defaults.filter
     dir: <path>          # defaults to file-defaults.dir
     redact: <bool>       # defaults to file-defaults.redact
     redactable: <bool>   # defaults to file-defaults.redactable
     max-file-size: <sz>  # defaults to file-defaults.max-file-size
     max-group-size: <sz> # defaults to file-defaults.max-group-size

   ... repeat ...

capture-stray-errors: #optional
  enable: <bool>   # whether to enable internal fd2 capture
  dir: <path>      # output directory, defaults to file-defaults.dir
```

The channel selection (`channels` in each sink) can be:

- `ALL` for all channels;
- a comma-delimited list of specific channels;
- `ALL EXCEPT <list>` for all channels except the provided
  channel names.

A CLI utility to validate the configuration is also provided:
`cockroach debug check-log-config`.

**Incremental changes**

The change was carried out as follows (this may guide the review):

1. `logpb/log.proto`: introduce a new protobuf enum Channels
2. `log/gen.sh`: auto-generate channel aliases in new sub-package `channel`
3. `log/gen.sh`: auto-generate per-channel APIs in `log_channels.go`
4. `log`: rework `clog.go` and other files to pass the channel as argument
5. `log/logconfig`: new package for log config data structures + parser + tests
6. `log/flags.go`: apply the configuration
7. `cli/{context,flags}.go`: read log config via `--log`, mark other flags deprecated
8. `cli/logconfig.go`: new command `cockroach check-log-config` for demos & checks

Release note (cli change): The logging configuration can now be
specified via the `--log` parameter. See the documentation for
details. The flags `--log-dir`, `--log-file-max-size`,
`--log-file-verbosity`, `--log-group-max-size` are now deprecated.

Release note (cli change): A new command `cockroch debug
check-log-config` prints out the logging configuration that results
from the provided combination of `--store`, `--log` and other
logging-related flags on the command line.

Release note (doc change): A report of the possible logging severities
and channels is now automatically generated in
`docs/generated/logging.md`.

### CODE REVIEW

**Review by itsbilal — APPROVED** [review]
:lgtm:

This is a massive overhaul and my experience with a lot of this code isn't all that deep, but overall it looks great save for some minor comments.

> Reviewed 79 of 85 files at r1, 13 of 13 files at r2, 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57134#-:-MNPeDRB5CuP2xcBMcYI:b-tw83oz)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @itsbilal, and @knz)

___
*[pkg/cli/log_flags.go, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57134#-MN5DwK3-r9UNJztjqW9:-MN5DwK3-r9UNJztjqWA:b-nlxfs5) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b487041359188a557bf7b5d379afc605520048/pkg/cli/log_flags.go#L45)):*
> ```Go
> 	if cliCtx.deprecatedLogOverrides.anySet() &&
> 		cliCtx.logConfigInput.isSet {
> 		return errors.New("--" + cliflags.Log.Name + " is incompatible with legacy discrete logging flags")
> ```

Nit: Can use `Newf` here.
___
*[pkg/cli/log_flags_test.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57134#-MN5JmdmC8Xl9-enIA5a:-MN5JmdmC8Xl9-enIA5b:b235m0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b487041359188a557bf7b5d379afc605520048/pkg/cli/log_flags_test.go#L89)):*
> ```Go
> 	const defaultLogDir = `PWD/cockroach-data/logs`
> 
> 	testData := []struct {
> ```

Did you consider doing these (and the string generation methods above) as datadriven tests? They might be slightly easier to understand and extend that way. I'm fine with them this way too, just wondering if you thought about it.
___
*[pkg/util/log/test_log_scope.go, line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57134#-MNP82wP7TD4YvgCm_sK:-MNP82wP7TD4YvgCm_sL:bb70w76) ([raw file](https://github.com/cockroachdb/cockroach/blob/e31d60c1882cfae57e169177c3a17fdb272c9150/pkg/util/log/test_log_scope.go#L92)):*
> ```Go
> // not just debugLog. This would be necessary because loggers don't
> // necessarily have the same config. Until that is implemented,
> // we prevent the use case altogether.
> ```

Nice
___
*[pkg/util/log/logconfig/config.go, line 135 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57134#-MNPd6TzB7ZMlaTbGNfo:-MNPd6TzB7ZMlaTbGNfp:b-xohbyk) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd76ced25c4b033e058d3c559e65cf232ffd0cd8/pkg/util/log/logconfig/config.go#L135)):*
> ```Go
> 	NoColor bool `yaml:"no-color,omitempty"`
> 
> 	CommonSinkConfig `yaml:",inline"`
> ```

Shouldn't this be at the top by convention?
___
*[pkg/util/log/logconfig/config.go, line 203 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57134#-MNPaCRL1iFPRl7dYHRa:-MNPaCRM1LQTpdE3yk2d:bxjdkoc) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd76ced25c4b033e058d3c559e65cf232ffd0cd8/pkg/util/log/logconfig/config.go#L203)):*
> ```Go
> 
> 	// MaxFileSize indicates the approximate maximum size of
> 	// individual files generated by this sinks.
> ```

s/sinks/sink/
___
*[pkg/util/log/logconfig/validate.go, line 198 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57134#-MNPddTM8a7Ku0Dxsh62:-MNPddTM8a7Ku0Dxsh63:b-uconbb) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd76ced25c4b033e058d3c559e65cf232ffd0cd8/pkg/util/log/logconfig/validate.go#L198)):*
> ```Go
> 	c.Sinks.sortedFileGroupNames = fileGroupNames
> 
> 	return nil
> ```

You'd have to do `return resErr` here for the defer-time set to work, right?

**Comment by itsbilal** [comment]
Looks like you did a rebase push right as I submitted my review. Let me know if parts of the old review aren't valid anymore / there are large parts still left to review after the force-push.

**Review by itsbilal — APPROVED** [review]
Now with the post-rebase review.

> Reviewed 16 of 91 files at r4, 85 of 89 files at r5, 9 of 9 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57134#-:-MNPiB3bAJGhZepqF5yP:b-armc0j)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru and @knz)

**Review by knz — COMMENTED** [review]
> Reviewed 1 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57134)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru and @itsbilal)

___
*[pkg/cli/log_flags.go, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57134#-MN5DwK3-r9UNJztjqW9:-MNPg0QKARMPLCWbNC6b:b4kqnq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b487041359188a557bf7b5d379afc605520048/pkg/cli/log_flags.go#L45)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Nit: Can use `Newf` here.
</blockquote></details>

Not just a nit - in fact I have to, the linter tells me so. Done.
___
*[pkg/cli/log_flags_test.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57134#-MN5JmdmC8Xl9-enIA5a:-MNPja8W8hzCcCiV9LzF:b-q189wf) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b487041359188a557bf7b5d379afc605520048/pkg/cli/log_flags_test.go#L89)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Did you consider doing these (and the string generation methods above) as datadriven tests? They might be slightly easier to understand and extend that way. I'm fine with them this way too, just wondering if you thought about it.
</blockquote></details>

I'll try it.
___
*[pkg/util/log/logconfig/config.go, line 135 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57134#-MNPd6TzB7ZMlaTbGNfo:-MNPh77j8GkG96SvKNF8:b-b8wlxh) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd76ced25c4b033e058d3c559e65cf232ffd0cd8/pkg/util/log/logconfig/config.go#L135)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Shouldn't this be at the top by convention?
</blockquote></details>

Explained in comment.
___
*[pkg/util/log/logconfig/config.go, line 203 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57134#-MNPaCRL1iFPRl7dYHRa:-MNPiEHZ7XroUCDdzRpZ:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd76ced25c4b033e058d3c559e65cf232ffd0cd8/pkg/util/log/logconfig/config.go#L203)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

s/sinks/sink/
</blockquote></details>

Fixed.
___
*[pkg/util/log/logconfig/validate.go, line 198 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57134#-MNPddTM8a7Ku0Dxsh62:-MNPiQIe4J2fZ2YPvUnf:buaniz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd76ced25c4b033e058d3c559e65cf232ffd0cd8/pkg/util/log/logconfig/validate.go#L198)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

You'd have to do `return resErr` here for the defer-time set to work, right?
</blockquote></details>

Nope: the defer is run after the assignment to the return value by the `return` statement.

**Comment by knz** [comment]
@itsbilal I changed the test to datadriven. Can you have another look?

**Review by itsbilal — APPROVED** [review]
:lgtm:

Really like how the tests turned out! Thanks for all the text processing stuff there.

> Reviewed 18 of 18 files at r7, 9 of 9 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57134#-:-MN_1BvN5PdEoRqh-LA6:b-fh17c0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru and @itsbilal)

**Comment by knz** [comment]
thanks :) 

bors r=itsbilal

**Pull request merged**
