### PR TITLE
sql: use declarative schemachange for add column sequence exprs

### LINKED ISSUE #81781: sql/schemachanger: use declarative schemachange for add column sequence expr
Currently when adding columns with the declarative schema changer, we fallback to the legacy schema changer when sequence expressions are observed inside newly added columns this was done because:

1. We didn't support properly surfacing errors from the backfiller (this was addressed in the original PR)
2. We lacked support for updating error related telemetry during executing

Once these two points are addressed we can enable support for the declarative schema changer for all expressions.

### PR DESCRIPTION
**Pull request by fqazi**
Fixes: #81781

Previously, the declarative schema changer was disabled for
add column expressions with sequence references (i.e. default,
on update, computed) because we were missing telemetry
from the legacy schema changer for during backfill related failures.
This was inadequate because the lack of telemetry from these
areas could be seen as a usability issue. To address this,
this patch adds in support for missing telemetry and enables
supports for add column operations with sequence operations.

Release note: None

### CODE REVIEW

**Review by Xiang-Gu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81782)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @Xiang-Gu)

___
*[`pkg/sql/schemachanger/scexec/exec_backfill.go` line 256 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81782#-N2v_A5U1VJt4dkbZCTe:-N2v_A5U1VJt4dkbZCTf:bvebqhm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0836b4ae03507e80198728a41a7f10eb9ca2501/pkg/sql/schemachanger/scexec/exec_backfill.go#L256)):*
> ```Go
> 	}); err != nil {
> 		// We ran into an  uncategorized schema change error.
> 		deps.Telemetry().IncrementSchemaChangeErrorType("uncategorized")
> ```

so all we need to do is add a Telemetry interface for declarative schema changer, and invoke it during backfill if the backfill fails? I saw only the "uncategorized" error. Are there any other types of errors?

**Review by ajwerner — COMMENTED** [review]
There's something funny going on in the restore case 

> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81782#-:-N2wDyTq1Vo_fGuU21B8:bh7cq5a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @fqazi, and @Xiang-Gu)

___
*[`-- commits` line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81782#-N2wDxFl3FieM0ohCjSh):*
detritus

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81782)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, and @Xiang-Gu)

___
*[`-- commits` line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81782#-N2wDxFl3FieM0ohCjSh):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

detritus
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/scexec/exec_backfill.go` line 256 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81782#-N2v_A5U1VJt4dkbZCTe:-N30J58n5mRgOaQi2HWT:bcyblp6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0836b4ae03507e80198728a41a7f10eb9ca2501/pkg/sql/schemachanger/scexec/exec_backfill.go#L256)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

so all we need to do is add a Telemetry interface for declarative schema changer, and invoke it during backfill if the backfill fails? I saw only the "uncategorized" error. Are there any other types of errors?
</blockquote></details>

The only other type we have is for constraint validation failures. These can be extended later on

**Review by ajwerner — COMMENTED** [review]
This is very close, nice 

> Reviewed 2 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81782#-:-N3tUNDT7i26qijAbSE_:bsv3crs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @fqazi, and @Xiang-Gu)

___
*[`pkg/sql/catalog/rewrite/rewrite.go` line 397 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81782#-N3tV1E62BE8xzTVY0QU:-N3tV1E62BE8xzTVY0QV:bd0mcz8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9bd08e674db862b5bfc0cc54535c291fa999d6e/pkg/sql/catalog/rewrite/rewrite.go#L397)):*
> ```Go
> }
> 
> // SchemaChangerStateInDescs goes over all mutable descriptors and cleans any
> ```

Can you expand this commentary to make it more clear what this does? I feel like the name could also be clearer. How about `MaybeClearSchemaChangerStateInDescs`? Explain why it exists and how it ought to be used. 



_Code quote:_
```Go
// SchemaChangerStateInDescs goes over all mutable descriptors and cleans any
// empty state information.
func SchemaChangerStateInDescs(descriptors []catalog.MutableDescriptor) error {
```
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go` line 170 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81782#-N3tU_f87C8SM7IhfWsy:-N3tU_f87C8SM7IhfWsz:boazv6w) ([raw file](https://github.com/cockroachdb/cockroach/blob/95616f9b5da734e3a8b82baeb1078a2bf774243c/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go#L170)):*
> ```Go
> 	if desc.HasDefault() {
> 		expression := b.WrapExpression(tbl.TableID, cdd.DefaultExpr)
> 		// Sequence references inside expressions are unsupported, since these will
> ```

Is this no longer true?
___
*[`pkg/sql/schemachanger/testdata/alter_table_add_column` line 15 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81782#-N3tUfHT1LLlB7wZjZLY:-N3tUfHT1LLlB7wZjZLZ:b-pismi1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9bd08e674db862b5bfc0cc54535c291fa999d6e/pkg/sql/schemachanger/testdata/alter_table_add_column#L15)):*
> ```
> test
> ALTER TABLE db.public.tbl ADD COLUMN j INT NOT NULL DEFAULT nextval('db.public.sq1')
> ----
> ```

nit: add a separate test

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81782)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, and @Xiang-Gu)

___
*[`pkg/sql/catalog/rewrite/rewrite.go` line 397 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81782#-N3tV1E62BE8xzTVY0QU:-N3toSVgBwYCLlNZ5e40:b4b8gg4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9bd08e674db862b5bfc0cc54535c291fa999d6e/pkg/sql/catalog/rewrite/rewrite.go#L397)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Can you expand this commentary to make it more clear what this does? I feel like the name could also be clearer. How about `MaybeClearSchemaChangerStateInDescs`? Explain why it exists and how it ought to be used. 
</blockquote></details>

// MaybeClearSchemaChangerStateInDescs goes over all mutable descriptors and
// cleans any state information from descriptors which have no targets associated
// with the corresponding jobs. Not having any targets in an individual state
// is not enough, since the descriptor in question could be a dependent (for
// example a type reference in a wider schema change).
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go` line 170 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81782#-N3tU_f87C8SM7IhfWsy:-N3tq6TW7XWnTISL0W9I:b-dpblc8) ([raw file](https://github.com/cockroachdb/cockroach/blob/95616f9b5da734e3a8b82baeb1078a2bf774243c/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go#L170)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Is this no longer true?
</blockquote></details>

Yes, this limitation is now lifted, we allowed sequence expressions inside default expressions.
___
*[`pkg/sql/schemachanger/testdata/alter_table_add_column` line 15 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81782#-N3tUfHT1LLlB7wZjZLY:-N3tqCB40oYe5cifYItG:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9bd08e674db862b5bfc0cc54535c291fa999d6e/pkg/sql/schemachanger/testdata/alter_table_add_column#L15)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: add a separate test
</blockquote></details>

Done

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r2, 6 of 9 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81782#-:-N3wBSnc193xYnUZ7H_M:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @fqazi, and @Xiang-Gu)

___
*[`pkg/sql/schemachanger/testdata/alter_table_add_column` line 2049 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/81782#-N3wBC_DCiLxN7zF6LMT:-N3wBC_DCiLxN7zF6LMU:bqky0zt) ([raw file](https://github.com/cockroachdb/cockroach/blob/760f93a9af19211062b06027d0e722bc52c68d20/pkg/sql/schemachanger/testdata/alter_table_add_column#L2049)):*
> ```
>          - i
>   -      name: crdb_internal_index_7_name_placeholder
>   +      name: tbl_pkey
> ```

Should this still be called `tbl_pkey` here?

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81782)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @dt, and @Xiang-Gu)

___
*[`pkg/sql/schemachanger/testdata/alter_table_add_column` line 2049 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/81782#-N3wBC_DCiLxN7zF6LMT:-N3wIKfg-BgUCnhpvkM3:bdtyvxt) ([raw file](https://github.com/cockroachdb/cockroach/blob/760f93a9af19211062b06027d0e722bc52c68d20/pkg/sql/schemachanger/testdata/alter_table_add_column#L2049)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Should this still be called `tbl_pkey` here? 
</blockquote></details>

That does look fishy, the existing rules have this issue. Let me handle this in the other PR where I'm adding UNIQUE support.

**Comment by fqazi** [comment]
@ajwerner TFTR!

**Comment by fqazi** [comment]
bots r+

**Pull request merged**
