### PR TITLE
roachtest: run kv roachtest with encryption turned on and off

### PR DESCRIPTION
**Pull request by ghost**
Now roachtest kv will be run with encryption at rest turned on and turned off
during roachtest nightly run. This is done for analyzing the impact of encryption
on performance.

Part of encryption at rest benchmakring: #19783.
Release note: None

### CODE REVIEW

**Comment by windchan7** [comment]
Do not merge. Haven't run manually.

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[pkg/cmd/roachtest/kv.go, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26103#-LDNzra78WtxBDnbyjX_:-LDNzra84z2a17sKsVht:b2g5r1h) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf36b150eff54c0971109a87e0b3f747d44e4f5f/pkg/cmd/roachtest/kv.go#L54)):*
> ```Go
> 		p := p
> 		for _, n := range []int{1, 3} {
> 			for _, e := range []bool{false, true} {
> ```

You need to add a line like `e := e` so that the closures below properly capture the encryption setting. 

---

*[pkg/cmd/roachtest/kv.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26103#-LDNzZlj2QUCdxvW3yOb:-LDNzZlj2QUCdxvW3yOc:buss2de) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf36b150eff54c0971109a87e0b3f747d44e4f5f/pkg/cmd/roachtest/kv.go#L70)):*
> ```Go
> 	for _, e := range []bool{false, true} {
> 		r.Add(testSpec{
> 			Name:   fmt.Sprintf("kv/splits/encrypt=%t/nodes=3", e),
> ```

There is no need to run this test with encryption. It is testing splitting a range repeatedly (calling it `kv/splits` is perhaps misleading). 

---

*[pkg/cmd/roachtest/kv.go, line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26103#-LDNzhkl9rVnLcAwxFxv:-LDNzhkl9rVnLcAwxFxw:b-6lis3l) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf36b150eff54c0971109a87e0b3f747d44e4f5f/pkg/cmd/roachtest/kv.go#L103)):*
> ```Go
> 	runScalability := func(ctx context.Context, t *test, c *cluster, percent int, encryption bool) {
> 		nodes := c.nodes - 1
> 		encrypt = encryption
> ```

Ditto about not needing to change these tests as they are not enabled right now and I'm probably going to delete them.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26103)*

**Comment by windchan7** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/cmd/roachtest/kv.go, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26103#-LDNzra78WtxBDnbyjX_:-LDRzhbK97qYIhbOkOIM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf36b150eff54c0971109a87e0b3f747d44e4f5f/pkg/cmd/roachtest/kv.go#L54)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

You need to add a line like `e := e` so that the closures below properly capture the encryption setting. 
</blockquote></details>

Done.

---

*[pkg/cmd/roachtest/kv.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26103#-LDNzZlj2QUCdxvW3yOb:-LDRzlL3Axw0RDwJjPAi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf36b150eff54c0971109a87e0b3f747d44e4f5f/pkg/cmd/roachtest/kv.go#L70)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

There is no need to run this test with encryption. It is testing splitting a range repeatedly (calling it `kv/splits` is perhaps misleading). 
</blockquote></details>

Done.

---

*[pkg/cmd/roachtest/kv.go, line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26103#-LDNzhkl9rVnLcAwxFxv:-LDRzlox8dZH-dYtc0Fi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf36b150eff54c0971109a87e0b3f747d44e4f5f/pkg/cmd/roachtest/kv.go#L103)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ditto about not needing to change these tests as they are not enabled right now and I'm probably going to delete them.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26103)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26103#-:-LDb6XD_3NgoDGpQmX5Y:bnfp4nl)*

**Comment by windchan7** [comment]
Bors failed because of `TestVersionUpgrade`, known issue: https://github.com/cockroachdb/cockroach/issues/25444.

**Comment by mberhault** [comment]
This broke quite a few of the nightly roachtest runs.
Two things need to be fixed:
* don't enable encryption on 2.0 (there's a convenient `t.IsBuildVersion("2.0") ...` to check that)
* the `encrypt` variable shouldn't be a global. Once KV sets it, all tests after it run with encryption enabled.

**Comment by petermattis** [comment]
> don't enable encryption on 2.0 (there's a convenient t.IsBuildVersion("2.0") ... to check that)

`t.IsBuildVersion()` is for disabling part of a test. Use `testSpec.MinVersion = "2.1"` to skip a test on "2.0".

**Comment by windchan7** [comment]
`encrypt` is made global and checked in `cluster.Start` to avoid the individual check in each roachtest. I think I will still keep it a global variable but after kv calls `Start`, I will set `encrypt` back to `false`. The point of enabling roachtest start encrypted cluster is not really to have individual test toggle with `encrypt`. Instead, I originally thought it should be a command line flag.

**Comment by petermattis** [comment]
> But after kv calls Start, I will set encrypt back to false.

This won't work for tests that are started in parallel.

**Comment by windchan7** [comment]
Ok, so the only way would be checking `encrypt` in individual test and passing `--encrypt` flag to `cluster.Start`?

**Comment by mberhault** [comment]
Another possibility would be to have a test spec settings called `canUseEncryption` (default to false for now). This can then be selectively turned on for various tests.

**Pull request merged**
