### PR TITLE
storage: recompute raft log size in Raft log queue when zero

### LINKED ISSUE #33071: storage: inability to up-replicate if Raft log is too large
This is fallout from #32896.

If the Raft log is too large, preemptive snapshots will not be sent which prevents up-replication. If a range is not experiencing write traffic, it can stay in this state for an extended period of time (perhaps forever) because the Raft log truncation heuristics will refuse to truncate the Raft log. This shows up in the logs as:

```
I181212 18:07:58.829705 90221 storage/replicate_queue.go:260  [n1,replicate,s1,r3437/1:/Table/428/1/"\x0{2\vP…-3A\x…}] snapshot failed: aborting snapshot because raft log is too large (24801729 bytes after processing 12 of 1422 entries)
E181212 18:07:58.829748 90221 storage/queue.go:839  [n1,replicate,s1,r3437/1:/Table/428/1/"\x0{2\vP…-3A\x…}] failed to replicate after 5 retries
```

The full scenario of how this happened is that a large transaction was performed on a 3 node cluster. While the system was digesting the transaction, one of the nodes was taken down and decommissioned while another node was added. This resulted in an excessively large Raft log (2.25 GB) on 3 ranges. The 3 ranges with large Raft logs have now caught up, but they are refusing to up-replicate to the newly added node because the Raft log is too large. The Raft log is not being truncated because the Raft log size is only cached in memory and the size is not recomputed when the Range is loaded. The effect is that the range status debug page (and the `Replica`) think the Raft log is a few hundred kilobytes, while the snapshot machinery knows that the real Raft log size is 2+ GB. 

@bdarnell Any thoughts on what to do here?

### PR DESCRIPTION
**Pull request by tbg**
When a node starts, it has no knowledge of the true size of its replicas'
Raft logs. However, without this knowledge, log truncations on replicas
that have no regular write activity will not take place (unless the log is
too long).

This doesn't matter in most circumstances (though it wastes a bit of space)
but if it does (reliably hit by users) it can be problematic since
snapshots contain the historical Raft log, and snapshots are refused when
they contain a large amount of logs. In particular in conjunction with
IMPORT/RESTORE (which reliably creates log entries weighing in at 25mb
each) this often resulted in ranges that were unable to rebalance until
somehow convinced to truncate their logs. More generally, any workload in
which ~100 entries could combine to a size of more than 16mb would trigger
this problem if a node was restarted and became leaseholder after the
restart while retaining such a log.

We are planning to omit the historical log from snapshots in the near
future (solving this problem), but in the interim, add a mechanism that
recomputes the raft log size if it is zero (and thus definitely unknown).

Fixes #33071.

Release note (bug fix): Prevent a situation in which snapshots would be
refused repeatedly over long periods of time, with error messages such as
"aborting snapshot because raft log is too large" appearing in the logs,
and often accompanied by under-replicated ranges in the UI.

### CODE REVIEW

**Comment by tbg** [comment]
PS I'm almost on the fence for this change because my WIP to not send the log in snapshots seems to indicate that that "just works" -- but the Raft log size semantics become trickier to the point where I want to spend some time thinking about what they should actually be, and I might get distracted enough to miss the release for this.

**Review by petermattis — COMMENTED** [review]
The general idea seems reasonable. I'd like to see `ComputeRaftLogSize` added even if we don't hook this up to the Raft log queue. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-:-LZMA4gPAfRhqyz4yngZ:bxly86b)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @petermattis, and @tbg)

___
*[pkg/storage/client_replica_gc_test.go, line 108 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZM7B9_1phajGQG8TGs:-LZM7B9_1phajGQG8TGt:bimyfy2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bada3589b53433f80170db87edf1c79d2b1b076/pkg/storage/client_replica_gc_test.go#L108)):*
> ```Go
> 		// storage is now empty (in other words, GC'ing the Replica took care of
> 		// cleanup).
> 		dir := repl1.SideloadedRaftMuLocked().Dir()
> ```

Eh? You don't seem to be holding `raftMu` here.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35136)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @petermattis)

___
*[pkg/storage/client_replica_gc_test.go, line 108 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZM7B9_1phajGQG8TGs:-LZZRRAE1cEbjmkblc5O:b-a4wcvi) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bada3589b53433f80170db87edf1c79d2b1b076/pkg/storage/client_replica_gc_test.go#L108)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Eh? You don't seem to be holding `raftMu` here.
</blockquote></details>

Oops. Done.

**Comment by tbg** [comment]
Added the missing test, RFAL.

**Review by andreimatei — CHANGES_REQUESTED** [review]
thanks for taking this over

in r11 pls add to the comments on `r.mu.raftLogSize` explaining when the field is recomputed

> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-:-LZf8D5e--9jblTJMwcn:b-9ubxf7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @petermattis, and @tbg)

___
*[pkg/storage/client_raft_test.go, line 656 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf678DEuJU7YERbhY1:-LZf678DEuJU7YERbhY2:bllrcvd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2ee8e2b46ce482a8995d1bfbc432e9c2c25702/pkg/storage/client_raft_test.go#L656)):*
> ```Go
> 	}
> 
> 	assertCorrectRaftLogSize := func() error {
> ```

pls comment that we check reality versus a maintained stat
___
*[pkg/storage/client_raft_test.go, line 664 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf53LK0WniXJC66tZm:-LZf53LK0WniXJC66tZn:b-ppxq6m) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2ee8e2b46ce482a8995d1bfbc432e9c2c25702/pkg/storage/client_raft_test.go#L664)):*
> ```Go
> 
> 			repl.RaftLock()
> 			realSize, err := storage.ComputeRaftLogSize(repl.RangeID, repl.Engine(), repl.SideloadedRaftMuLocked())
> ```

long line bro
___
*[pkg/storage/client_raft_test.go, line 666 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf5HpgBOyv4NhNVNHV:-LZf5HpgBOyv4NhNVNHW:bnh9mt9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2ee8e2b46ce482a8995d1bfbc432e9c2c25702/pkg/storage/client_raft_test.go#L666)):*
> ```Go
> 			realSize, err := storage.ComputeRaftLogSize(repl.RangeID, repl.Engine(), repl.SideloadedRaftMuLocked())
> 			size := repl.GetRaftLogSize()
> 			repl.RaftUnlock()
> ```

can we release `raftMu` earlier? At lease one line up.
It's unclear to me if `ComputeRaftLogSize()` needs the mutex held. I think it'd be worth documenting that. If it doesn't, I'd say let's release it before calling it.
___
*[pkg/storage/client_raft_test.go, line 679 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf6JRx7DvxHorhEWrx:-LZf6JRx7DvxHorhEWry:b-qyzgib) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2ee8e2b46ce482a8995d1bfbc432e9c2c25702/pkg/storage/client_raft_test.go#L679)):*
> ```Go
> 	}
> 
> 	testutils.SucceedsSoon(t, assertCorrectRaftLogSize)
> ```

how come this needs to be async? And below.
___
*[pkg/storage/client_replica_gc_test.go, line 108 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZM7B9_1phajGQG8TGs:-LZf5q-RAkv8zcxyUtkD:bmcgo3b) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bada3589b53433f80170db87edf1c79d2b1b076/pkg/storage/client_replica_gc_test.go#L108)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Oops. Done.
</blockquote></details>

done? how?
___
*[pkg/storage/client_replica_gc_test.go, line 123 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf5yiN0Ak28tSTsvaf:-LZf5yiN0Ak28tSTsvag:b-73k17t) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2ee8e2b46ce482a8995d1bfbc432e9c2c25702/pkg/storage/client_replica_gc_test.go#L123)):*
> ```Go
> 				testutils.SucceedsSoon(t, func() error {
> 					// Verify that the whole directory for the replica is gone.
> 					dir := repl1.SideloadedRaftMuLocked().Dir()
> ```

is the mutex held here?
...
I now see you've added in a future commit. You might want to move the patch ealier.
___
*[pkg/storage/raft_log_queue.go, line 345 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf8ztm-8T1jOm-5VW_:-LZf8ztm-8T1jOm-5VWa:bqebhii) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d1f1092370d22c783d6bdd79726c65d1373e449/pkg/storage/raft_log_queue.go#L345)):*
> ```Go
> func (td *truncateDecision) NumTruncatableIndexes() int {
> 	if td.NewFirstIndex < td.Input.FirstIndex {
> 		return 0
> ```

why this change?
___
*[pkg/storage/raft_log_queue.go, line 493 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf99rU3Fzt3GTAaQtW:-LZf99rU3Fzt3GTAaQtX:b-pdxnpy) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d1f1092370d22c783d6bdd79726c65d1373e449/pkg/storage/raft_log_queue.go#L493)):*
> ```Go
> }
> 
> func (rlq *raftLogQueue) shouldQueueImpl(
> ```

comment the ret vals pls
And say that `recompute == true` => `shouldQ == true`

But actually it seems to me that `recompute` belongs better in the `decision` than in this method, no?
___
*[pkg/storage/raft_log_queue.go, line 495 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf9wib38_5fD9do4tA:-LZf9wib38_5fD9do4tB:b4oz0t2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d1f1092370d22c783d6bdd79726c65d1373e449/pkg/storage/raft_log_queue.go#L495)):*
> ```Go
> func (rlq *raftLogQueue) shouldQueueImpl(
> 	ctx context.Context, decision truncateDecision,
> ) (shouldQ bool, recompute bool, priority float64) {
> ```

s/recompute/measureRaftLogSize
___
*[pkg/storage/raft_log_queue.go, line 503 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZfASrX3kEGIcKjRSZW:-LZfASrX3kEGIcKjRSZX:bxgd0r6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d1f1092370d22c783d6bdd79726c65d1373e449/pkg/storage/raft_log_queue.go#L503)):*
> ```Go
> 		decision.Input.LastIndex == decision.Input.FirstIndex {
> 
> 		return false, false, 0
> ```

this is new code from before, isn't it? How come the previous code didn't care about `StateLeader`?
___
*[pkg/storage/raft_log_queue.go, line 505 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZfA3E86YwHTaClabzA:-LZfA3E86YwHTaClabzB:b-ix4ix7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d1f1092370d22c783d6bdd79726c65d1373e449/pkg/storage/raft_log_queue.go#L505)):*
> ```Go
> 		return false, false, 0
> 	}
> 	// We have a nonempty log and think that its size is zero, which can't be
> ```

can you add more words on the "nonempty log" part? How do we know it's not empty?
___
*[pkg/storage/replica.go, line 257 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf79dBEEtfyHnESJly:-LZf79dBEEtfyHnESJlz:b-263zhc) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dd9789ae45df7c9cd6a1a5a649d8629515cba2c/pkg/storage/replica.go#L257)):*
> ```Go
> 		// of the raft log. This will be correct when all log entries predating this
> 		// process have been truncated.
> 		raftLogSize int64
> ```

can you please clarify whether this includes the sideload or not? And also for `GetRaftLogSize()`in `helpers_test.go`
___
*[pkg/storage/replica_raft.go, line 2464 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf4GqXDKXkaEZfNrQI:-LZf4GqXDKXkaEZfNrQJ:b-ugvuo6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2ee8e2b46ce482a8995d1bfbc432e9c2c25702/pkg/storage/replica_raft.go#L2464)):*
> ```Go
> }
> 
> // ComputeRaftLogSize computes the size of the Raft log from the storage engine.
> ```

please comment the unit of the result
___
*[pkg/storage/replica_raft.go, line 2480 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf4j5mEfvtiBWEAqnM:-LZf4j5mEfvtiBWEAqnN:b-kkbydn) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2ee8e2b46ce482a8995d1bfbc432e9c2c25702/pkg/storage/replica_raft.go#L2480)):*
> ```Go
> 	defer iter.Close()
> 	from := engine.MakeMVCCMetadataKey(prefix)
> 	to := engine.MakeMVCCMetadataKey(prefix.PrefixEnd())
> ```

nit: consider finding a way to remove the duplication of `prefix.PrefixEnd()`. Are the bounds on the iterator worth it for this use case? Maybe we could not do that.
___
*[pkg/storage/replica_raft.go, line 2488 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf4B3v3mwWnWOcsQPp:-LZf4B3v3mwWnWOcsQPq:bygtmdf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2ee8e2b46ce482a8995d1bfbc432e9c2c25702/pkg/storage/replica_raft.go#L2488)):*
> ```Go
> 	if sideloaded != nil {
> 		var err error
> 		_, totalSideloaded, err = sideloaded.TruncateTo(context.TODO(), 1)
> ```

oh come on, pass a ctx to this function.

Also the 1 deserves a comment. Why not 0?
___
*[pkg/storage/replica_sideload_disk.go, line 261 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf2RfD1A2VtJ3u_BZj:-LZf2RfD1A2VtJ3u_BZk:bc43v2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/caf3a66f84d8f32eab8b70a97523c1d8c59ec765/pkg/storage/replica_sideload_disk.go#L261)):*
> ```Go
> }
> 
> func (ss *diskSideloadStorage) TruncateTo(
> ```

please comment that this method is part of the `sideloadStorage` iface
___
*[pkg/storage/replica_sideload_disk.go, line 287 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf2zAl3kfd7877zPFZ:-LZf2zAl3kfd7877zPF_:b-gmha8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/caf3a66f84d8f32eab8b70a97523c1d8c59ec765/pkg/storage/replica_sideload_disk.go#L287)):*
> ```Go
> 	if deletedAll {
> 		err := os.Remove(ss.dir)
> 		if !os.IsNotExist(err) {
> ```

how come we're swallowing "not exist" errors?
___
*[pkg/storage/replica_sideload_disk.go, line 308 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf3JC8Bwsvh8dabcaS:-LZf3JC8Bwsvh8dabcaT:b5nc4sf) ([raw file](https://github.com/cockroachdb/cockroach/blob/caf3a66f84d8f32eab8b70a97523c1d8c59ec765/pkg/storage/replica_sideload_disk.go#L308)):*
> ```Go
> 		base = base[1:]
> 		upToDot := strings.SplitN(base, ".", 2)
> 		i, err := strconv.ParseUint(upToDot[0], 10, 64)
> ```

s/i/logIdx ?

**Review by tbg — COMMENTED** [review]
TFTR, addressed more comments. Will do another pass tomorrow.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-:-LZg3cQ0BPj7g19Ri60B:b-nr29c7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @petermattis)

___
*[pkg/storage/client_raft_test.go, line 656 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf678DEuJU7YERbhY1:-LZftZwK2DBuQJ0Pg8jD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2ee8e2b46ce482a8995d1bfbc432e9c2c25702/pkg/storage/client_raft_test.go#L656)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls comment that we check reality versus a maintained stat
</blockquote></details>

Done.
___
*[pkg/storage/client_raft_test.go, line 664 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf53LK0WniXJC66tZm:-LZftcjA0d-PkaFq28oa:bpfzjrn) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2ee8e2b46ce482a8995d1bfbc432e9c2c25702/pkg/storage/client_raft_test.go#L664)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

long line bro
</blockquote></details>

Done. (But if you care about this generally I'd appreciate you sending a patch to crlfmt because I will violate this again and again and it's going to waste both of our time)
___
*[pkg/storage/client_raft_test.go, line 666 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf5HpgBOyv4NhNVNHV:-LZfthau8-za6Zzd5qFt:b-g7lofw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2ee8e2b46ce482a8995d1bfbc432e9c2c25702/pkg/storage/client_raft_test.go#L666)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

can we release `raftMu` earlier? At lease one line up.
It's unclear to me if `ComputeRaftLogSize()` needs the mutex held. I think it'd be worth documenting that. If it doesn't, I'd say let's release it before calling it.
</blockquote></details>

`ComputeRaftLogSize` doesn't care, but if you allow changing the log while you're recomputing it, then you can't trust the result (or rather, you can't ask for the in-mem size to match what's actually stored). I added a comment. Besides sideloaded storages aren't thread safe so you need the lock for that as well.
___
*[pkg/storage/client_raft_test.go, line 679 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf6JRx7DvxHorhEWrx:-LZfumRo4zV5yI9mXHbN:b-rfydlq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2ee8e2b46ce482a8995d1bfbc432e9c2c25702/pkg/storage/client_raft_test.go#L679)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

how come this needs to be async? And below.
</blockquote></details>

Honestly I don't know and I don't see a reason to. Thanks for catching that, I think this must've slipped in uninvited from my send-no-log-in-snaps-wip.
___
*[pkg/storage/client_replica_gc_test.go, line 108 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZM7B9_1phajGQG8TGs:-LZfvTIz8qYLSVe_yfTq:bxnk14x) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bada3589b53433f80170db87edf1c79d2b1b076/pkg/storage/client_replica_gc_test.go#L108)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

done? how?
</blockquote></details>

Not sure where that went, actually done now though.
___
*[pkg/storage/client_replica_gc_test.go, line 123 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf5yiN0Ak28tSTsvaf:-LZfvuOzDqpA4ALLqxWZ:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2ee8e2b46ce482a8995d1bfbc432e9c2c25702/pkg/storage/client_replica_gc_test.go#L123)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

is the mutex held here?
...
I now see you've added in a future commit. You might want to move the patch ealier.
</blockquote></details>

Good point, done.
___
*[pkg/storage/raft_log_queue.go, line 345 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf8ztm-8T1jOm-5VW_:-LZfx3DF9Y6wVC2Mxblo:b-vcmgpw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d1f1092370d22c783d6bdd79726c65d1373e449/pkg/storage/raft_log_queue.go#L345)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

why this change?
</blockquote></details>

The assertion was basically a bad idea, it's not the right place to randomly exit the process. Besides, truncations moving the first index backwards are a thing already (they don't do any harm).
___
*[pkg/storage/raft_log_queue.go, line 493 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf99rU3Fzt3GTAaQtW:-LZfxzuN9AP_MPizducB:bsk1kvd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d1f1092370d22c783d6bdd79726c65d1373e449/pkg/storage/raft_log_queue.go#L493)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

comment the ret vals pls
And say that `recompute == true` => `shouldQ == true`

But actually it seems to me that `recompute` belongs better in the `decision` than in this method, no?
</blockquote></details>

Hmm, you're probably right. Going to do it tomorrow.
___
*[pkg/storage/raft_log_queue.go, line 495 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf9wib38_5fD9do4tA:-LZfyCXd3qexQhcgkSSR:b-y8e3qv) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d1f1092370d22c783d6bdd79726c65d1373e449/pkg/storage/raft_log_queue.go#L495)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/recompute/measureRaftLogSize
</blockquote></details>

I don't see how that's better. Renamed to recomputeRaftLogSize hoping that that'll appease you.
___
*[pkg/storage/raft_log_queue.go, line 503 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZfASrX3kEGIcKjRSZW:-LZfykag66KFz-gqqjOp:bt9kfp4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d1f1092370d22c783d6bdd79726c65d1373e449/pkg/storage/raft_log_queue.go#L503)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

this is new code from before, isn't it? How come the previous code didn't care about `StateLeader`?
</blockquote></details>

Yeah, this is a bit obscure. It doesn't matter if you're leader or not. I just didn't want (readers) to have to think about the case in which you're not the leader.
___
*[pkg/storage/raft_log_queue.go, line 505 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZfA3E86YwHTaClabzA:-LZfyrdQ0hyuapXgHvXS:b-e4ncon) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d1f1092370d22c783d6bdd79726c65d1373e449/pkg/storage/raft_log_queue.go#L505)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

can you add more words on the "nonempty log" part? How do we know it's not empty?
</blockquote></details>

Its first index is not equal to the last index. Added to the comment.
___
*[pkg/storage/replica.go, line 257 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf79dBEEtfyHnESJly:-LZg-H-E3iotqBniEmya:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dd9789ae45df7c9cd6a1a5a649d8629515cba2c/pkg/storage/replica.go#L257)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

can you please clarify whether this includes the sideload or not? And also for `GetRaftLogSize()`in `helpers_test.go`
</blockquote></details>

Done.
___
*[pkg/storage/replica_raft.go, line 2464 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf4GqXDKXkaEZfNrQI:-LZg-Yy73uQAIs_zT6g1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2ee8e2b46ce482a8995d1bfbc432e9c2c25702/pkg/storage/replica_raft.go#L2464)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

please comment the unit of the result
</blockquote></details>

Done.
___
*[pkg/storage/replica_raft.go, line 2488 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf4B3v3mwWnWOcsQPp:-LZg-wDX9lI1YLGrqZb6:b-pzcdyx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2ee8e2b46ce482a8995d1bfbc432e9c2c25702/pkg/storage/replica_raft.go#L2488)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

oh come on, pass a ctx to this function.

Also the 1 deserves a comment. Why not 0?
</blockquote></details>

0 is better, done.
___
*[pkg/storage/replica_sideload_disk.go, line 261 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf2RfD1A2VtJ3u_BZj:-LZg1GugBie7b5M5-rTe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/caf3a66f84d8f32eab8b70a97523c1d8c59ec765/pkg/storage/replica_sideload_disk.go#L261)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

please comment that this method is part of the `sideloadStorage` iface
</blockquote></details>

Done.
___
*[pkg/storage/replica_sideload_disk.go, line 287 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf2zAl3kfd7877zPFZ:-LZg24wT5Y44pK8WYBH9:b-fa8jcl) ([raw file](https://github.com/cockroachdb/cockroach/blob/caf3a66f84d8f32eab8b70a97523c1d8c59ec765/pkg/storage/replica_sideload_disk.go#L287)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

how come we're swallowing "not exist" errors?
</blockquote></details>

If the storage is empty, the directory may not exist. Or it may. Added a comment.
___
*[pkg/storage/replica_sideload_disk.go, line 308 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf3JC8Bwsvh8dabcaS:-LZg2RAx38p0gLaw7rRA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/caf3a66f84d8f32eab8b70a97523c1d8c59ec765/pkg/storage/replica_sideload_disk.go#L308)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/i/logIdx ?
</blockquote></details>

Done.

**Review by andreimatei — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35136)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @petermattis, and @tbg)

___
*[pkg/storage/client_raft_test.go, line 664 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf53LK0WniXJC66tZm:-LZgJ_eBAYaN4BfpwZVQ:b-evv96k) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2ee8e2b46ce482a8995d1bfbc432e9c2c25702/pkg/storage/client_raft_test.go#L664)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Done. (But if you care about this generally I'd appreciate you sending a patch to crlfmt because I will violate this again and again and it's going to waste both of our time)
</blockquote></details>

well it's in the style guide. How any of us feel about it is immaterial :)

**Review by tbg — COMMENTED** [review]
RFAL!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-:-LZjGB1p-zN64E8L2QPy:b-828fnn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @petermattis)

___
*[pkg/storage/client_raft_test.go, line 664 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf53LK0WniXJC66tZm:-LZjEHf61zluqtbS50tB:bw63w0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c2ee8e2b46ce482a8995d1bfbc432e9c2c25702/pkg/storage/client_raft_test.go#L664)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

well it's in the style guide. How any of us feel about it is immaterial :)
</blockquote></details>

Fair point.
___
*[pkg/storage/raft_log_queue.go, line 493 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf99rU3Fzt3GTAaQtW:-LZjEXi31pIL6dzA5x35:b-348vsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d1f1092370d22c783d6bdd79726c65d1373e449/pkg/storage/raft_log_queue.go#L493)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Hmm, you're probably right. Going to do it tomorrow.
</blockquote></details>

Hmm, reconsidering because of the log size -- the log size is an input to the truncate decision, but in this case we need to pull one out of thin air. Will leave as is.
___
*[pkg/storage/raft_log_queue.go, line 503 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZfASrX3kEGIcKjRSZW:-LZjFs0N7rtUdGJTF9Sk:bcrqmux) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d1f1092370d22c783d6bdd79726c65d1373e449/pkg/storage/raft_log_queue.go#L503)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Yeah, this is a bit obscure. It doesn't matter if you're leader or not. I just didn't want (readers) to have to think about the case in which you're not the leader.
</blockquote></details>

I removed this condition.

**Comment by tbg** [comment]
Friendly ping, @andreimatei.

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-:-LZoonydClYyIdqNofB5:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @petermattis, and @tbg)

___
*[pkg/storage/replica.go, line 257 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf79dBEEtfyHnESJly:-LZoofDP77j-HVJHIYfy:b-lyo4wo) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dd9789ae45df7c9cd6a1a5a649d8629515cba2c/pkg/storage/replica.go#L257)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

can you please also clarify if this includes sideloads?

**Review by tbg — COMMENTED** [review]
TFTR!

bors r=andreimatei

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-:-LZpu2je8JCBvwKXzN42:b-h7m1bg)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @petermattis)

___
*[pkg/storage/replica.go, line 257 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/35136#-LZf79dBEEtfyHnESJly:-LZptwnJCivTP1cZX-OD:b-cqhwly) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dd9789ae45df7c9cd6a1a5a649d8629515cba2c/pkg/storage/replica.go#L257)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

can you please also clarify if this includes sideloads?
</blockquote></details>

I did, you were looking at an old revision:

```
		// raftLogSize is the approximate size in bytes of the persisted raft
		// log, including sideloaded entries' payloads. The value itself is not
		// persisted and is computed lazily, paced by the raft log truncation
		// queue which will recompute the log size when it finds it
		// uninitialized. This recomputation mechanism isn't relevant for ranges
		// which see regular write activity (for those the log size will deviate
		// from zero quickly, and so it won't be recomputed but will undercount
		// until the first truncation is carried out), but it prevents a large
		// dormant Raft log from sitting around forever, which has caused problems
		// in the past.
		raftLogSize int64
```

**Comment by tbg** [comment]
bors r=andreimatei

Flaked on acceptance/decommission, I filed https://github.com/cockroachdb/cockroach/issues/35307

**Pull request merged**
