### PR TITLE
concurrency: allow multiple txns to acquire shared locks on a single key 

### PR DESCRIPTION
**Pull request by arulajmani**
See individual commits for details.

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109366)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1627 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109366#-Nc_TeqO4UcGL5JjeULP:-Nc_TeqO4UcGL5JjeULQ:b-z57kc2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ea7503c140f67c3bc4b23c6144f65262581811e/pkg/kv/kvserver/concurrency/lock_table.go#L1627)):*
> ```Go
> 					pluralSuffix = "s"
> 				}
> 				sb.Printf("  holder%s: txn: %v epoch: %d, iso: %s, ts: %v, info: ",
> ```

Do you think it would be worthwhile to eliminate the redundancy in formatting each lock? It would be nice not to have to change the formatting in two places. Maybe something like:
```go
var prefix redact.SafeString
if first {
    first = false
    if kl.holders.Len() > 1 {
        prefix = "  holders: "
    } else {
        prefix = "  holder: "
    }
} else {
    prefix = "\n           "
}
sb.Printf("%stxn: %v epoch: %d, iso: %s, ts: %v, info: ", prefix, ...)
```
___
*[`pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks` line 27 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109366#-Nc_XG-V0q6sKAuI3wBq:-Nc_XG-V0q6sKAuI3wBr:bjm0yno) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a360a1c7225e998d2604d0b85231f399ca85527/pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks#L27)):*
> ```
> # ------------------------------------------------------------------------------
> # Ensure conflict resolution semantics for shared locks are sane -- that is,
> # if a shared lock is held on a key, {shared, non} locking requests are allowed
> ```

s/non/none/
___
*[`pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks` line 38 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109366#-Nc_WCE4Buakzb7q9naI:-Nc_WCE4Buakzb7q9naJ:byxv71v) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a360a1c7225e998d2604d0b85231f399ca85527/pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks#L38)):*
> ```
> start-waiting: false
> 
> new-request r=req3 txn=txn2 ts=10 spans=shared@a
> ```

I confused myself for a moment and thought this wasn't actually performing any requests. But it is, this is the `TestLockTableBasic`, not `TestConcurrencyManagerBasic`. Do we want to add a concurrency manager-level test for shared locks as well at some point? The will be especially helpful to test which requests push which other requests when shared locks are involved.
___
*[`pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks` line 62 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109366#-Nc_XKMr2TrmXuMjFEBv:-Nc_XKMr2TrmXuMjFEBw:brs276w) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a360a1c7225e998d2604d0b85231f399ca85527/pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks#L62)):*
> ```
>   holder: txn: 00000000-0000-0000-0000-000000000001 epoch: 0, iso: Serializable, ts: 10.000000000,0, info: unrepl [(str: Shared seq: 0)]
>    queued writers:
>     active: false req: 2, txn: 00000000-0000-0000-0000-000000000002
> ```

This tripped me up. "req: 2" is actually referring to req3 and "req: 3" is actually referring to req4. Do you mind adding on a commit to `scan r=req1` up above so that it gets sequenced in the lock table and corrects the indexing?
___
*[`pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks` line 72 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109366#-Nc_WymN6CuxVOGHpgPp:-Nc_WymN6CuxVOGHpgPq:b9ch5fl) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a360a1c7225e998d2604d0b85231f399ca85527/pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks#L72)):*
> ```
>            txn: 00000000-0000-0000-0000-000000000002 epoch: 0, iso: Serializable, ts: 10.000000000,0, info: unrepl [(str: Shared seq: 0)]
> 
> # Re-acquisition of the shared lock by req4 should work as well.
> ```

nit: remind the reader that req4 is part of the same txn as req3. They're both part of txn2.
___
*[`pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks` line 126 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109366#-Nc_Ye9d3MRv2d_jxMtu:-Nc_Ye9d3MRv2d_jxMtv:bvh0w3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a360a1c7225e998d2604d0b85231f399ca85527/pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks#L126)):*
> ```
>            txn: 00000000-0000-0000-0000-000000000002 epoch: 0, iso: Serializable, ts: 10.000000000,0, info: unrepl [(str: Shared seq: 0)]
>    queued writers:
>     active: true req: 4, txn: 00000000-0000-0000-0000-000000000002
> ```

Should we include the `queuedGuard` strength in this output?
___
*[`pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks` line 154 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109366#-Nc_Yu_w931_rkag_MYz:-Nc_Yu_w931_rkag_MZ-:b-6v2voj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a360a1c7225e998d2604d0b85231f399ca85527/pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks#L154)):*
> strength  until

nit: double space between words.
___
*[`pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks` line 154 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109366#-Nc_ZWk75MyRILTPCOA4:-Nc_ZWk75MyRILTPCOA5:b-9ph71k) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a360a1c7225e998d2604d0b85231f399ca85527/pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks#L154)):*
> ```
> 
> # ------------------------------------------------------------------------------
> # Ensure a key is locked with SHARED locking strength  until the all
> ```

Should we add a test for the opposite? That if an exclusive lock is released with multiple shared locks behind it, all of them are allowed to grab claims? Or does that case not work yet? I think actually not, based on `maybeReleaseFirstTransactionalWriter`.

Do you have a list of the state transitions that we don't yet support? We wouldn't want to forget one. If not, we could add a TODO at the bottom of this file that enumerates each case that we need to add support for.
___
*[`pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks` line 252 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109366#-Nc_ZFFi76akvH6FvMqj:-Nc_ZFFi76akvH6FvMqk:bc0irgz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a360a1c7225e998d2604d0b85231f399ca85527/pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks#L252)):*
> ```
> 
> # Now that all shared locks have been released, the exclusive locking request is
> # free to proceed.
> ```

:clap:

**Review by arulajmani — COMMENTED** [review]
TFTR, this should be good for another look. 

I added 2 more commits -- one to sequence req1 like you suggested, and another to print a `queuedWriter's` strength as well. The latter churned a lot of tests, so apologies for that. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109366#-:-NccK6BL73GCSsFnq1vi:bszcpc4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1627 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109366#-Nc_TeqO4UcGL5JjeULP:-NccCEBM5kBFJzOXIDXZ:btemjlm) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ea7503c140f67c3bc4b23c6144f65262581811e/pkg/kv/kvserver/concurrency/lock_table.go#L1627)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you think it would be worthwhile to eliminate the redundancy in formatting each lock? It would be nice not to have to change the formatting in two places. Maybe something like:
```go
var prefix redact.SafeString
if first {
    first = false
    if kl.holders.Len() > 1 {
        prefix = "  holders: "
    } else {
        prefix = "  holder: "
    }
} else {
    prefix = "\n           "
}
sb.Printf("%stxn: %v epoch: %d, iso: %s, ts: %v, info: ", prefix, ...)
```
</blockquote></details>

Good call, thanks for the suggestion! I ended up keeping the optPlural stuff around to save an `else`. 
___
*[`pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks` line 38 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109366#-Nc_WCE4Buakzb7q9naI:-NccGNG-1NOn_Df7NlK9:bqnuqml) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a360a1c7225e998d2604d0b85231f399ca85527/pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks#L38)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I confused myself for a moment and thought this wasn't actually performing any requests. But it is, this is the `TestLockTableBasic`, not `TestConcurrencyManagerBasic`. Do we want to add a concurrency manager-level test for shared locks as well at some point? The will be especially helpful to test which requests push which other requests when shared locks are involved.
</blockquote></details>

I was planning on adding concurrency manager-level tests once we've addressed https://github.com/cockroachdb/cockroach/issues/102264. That's because `TestConcurrencyManagerBasic` uses the actual latch manager.

 > The will be especially helpful to test which requests push which other requests when shared locks are involved.

I agree!
___
*[`pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks` line 62 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109366#-Nc_XKMr2TrmXuMjFEBv:-NccGwOI4wTX4B1SzGQK:b-9rv2n0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a360a1c7225e998d2604d0b85231f399ca85527/pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks#L62)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This tripped me up. "req: 2" is actually referring to req3 and "req: 3" is actually referring to req4. Do you mind adding on a commit to `scan r=req1` up above so that it gets sequenced in the lock table and corrects the indexing?
</blockquote></details>

Added a commit to fix the indexing.
___
*[`pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks` line 126 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109366#-Nc_Ye9d3MRv2d_jxMtu:-NccH5L8AroOHUD2uaCv:b-ef0o3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a360a1c7225e998d2604d0b85231f399ca85527/pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks#L126)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we include the `queuedGuard` strength in this output?
</blockquote></details>

We should. I added a commit that does that. 
___
*[`pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks` line 154 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109366#-Nc_Yu_w931_rkag_MYz:-NccERW19KGe02W-hRTR:b-goth8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a360a1c7225e998d2604d0b85231f399ca85527/pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks#L154)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> strength  until

nit: double space between words.
</blockquote></details>

:eagle: :eyes: 
___
*[`pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks` line 154 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109366#-Nc_ZWk75MyRILTPCOA4:-NccEWC82Ix6o2T-MDBx:b5970aj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a360a1c7225e998d2604d0b85231f399ca85527/pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks#L154)):*
> That if an exclusive lock is released with multiple shared locks behind it, all of them are allowed to grab claims? Or does that case not work yet? I think actually not, based on `maybeReleaseFirstTransactionalWriter`.

Yeah, it's not. The plan is to address that case as part of https://github.com/cockroachdb/cockroach/issues/102272. 

> Do you have a list of the state transitions that we don't yet support? We wouldn't want to forget one. If not, we could add a TODO at the bottom of this file that enumerates each case that we need to add support for.

I added a few off the top of my head, but maybe let's brainstorm these together later today and add to this TODO.
___
*[`pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks` line 252 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109366#-Nc_ZFFi76akvH6FvMqj:-NccHNuc73UDTd05zmkk:b-kpxwys) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a360a1c7225e998d2604d0b85231f399ca85527/pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks#L252)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

:clap:
</blockquote></details>

It's getting there!!

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, 31 of 31 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109366#-:-NccNUv02e4IWd60V-VE:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks` line 275 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/109366#-NccMPoo4W41Pvo1avxH:-NccMPoo4W41Pvo1avxI:b2eqw2k) ([raw file](https://github.com/cockroachdb/cockroach/blob/79fd17377271f48fd24b9bd846ff8ee032387ffe/pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks#L275)):*
> ```
> # Once the exclusive lock is released, only the head of the queue that is
> # compatible (the first three shared lock requests) should be able to acquire
> # a joint claim.
> ```

Some other cases off the top of my head:
- lock holder: none, wait queue: (shared, shared), some other shared lock breaks reservations and enters the front of the queue
- lock holder: none, wait queue: (shared, shared), some other shared lock breaks reservations and enters the middle of the queue
- lock holder: none, wait queue: (shared, shared), some other exclusive lock breaks reservations and enters the front of the queue
- lock holder: none, wait queue: (shared, shared), some other exclusive lock breaks reservations and enters the middle of the queue
- lock holder: none, wait queue: (exclusive, shared, shared), exclusive acquires lock and exits queue
- lock holder: none, wait queue: (exclusive, shared, shared), exclusive exits queue without acquiring lock
- various lock promotion cases where the lock is acquired/held in shared and is being acquired by the same txn in exclusive further back in the queue
- various lock promotion cases where the lock is acquired/held in exclusive and is being acquired by the same txn in shared further back in the queue
- various cases with non-transactional (intent strength) waiters

Some of these might already be supported.

**Review by arulajmani — COMMENTED** [review]
Thanks! 

bors r=nvanbenschoten 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109366#-:-NccOHyGCzj1UqJn_KLW:bm4w30g)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by arulajmani** [comment]
I missed the comment about other test cases. I'll bors again once I've added the one's that haven't been already tested in the TODO.

**Review by arulajmani — COMMENTED** [review]
TFTR! 

bors r=nvanbenschoten

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109366#-:-NccYh0d2HIqfxh1zF1P:b-ieq29z)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks` line 275 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/109366#-NccMPoo4W41Pvo1avxH:-NccYYszDjCGZi56OWh4:brvkslo) ([raw file](https://github.com/cockroachdb/cockroach/blob/79fd17377271f48fd24b9bd846ff8ee032387ffe/pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks#L275)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Some other cases off the top of my head:
- lock holder: none, wait queue: (shared, shared), some other shared lock breaks reservations and enters the front of the queue
- lock holder: none, wait queue: (shared, shared), some other shared lock breaks reservations and enters the middle of the queue
- lock holder: none, wait queue: (shared, shared), some other exclusive lock breaks reservations and enters the front of the queue
- lock holder: none, wait queue: (shared, shared), some other exclusive lock breaks reservations and enters the middle of the queue
- lock holder: none, wait queue: (exclusive, shared, shared), exclusive acquires lock and exits queue
- lock holder: none, wait queue: (exclusive, shared, shared), exclusive exits queue without acquiring lock
- various lock promotion cases where the lock is acquired/held in shared and is being acquired by the same txn in exclusive further back in the queue
- various lock promotion cases where the lock is acquired/held in exclusive and is being acquired by the same txn in shared further back in the queue
- various cases with non-transactional (intent strength) waiters

Some of these might already be supported.
</blockquote></details>

These are all great! I added all of these and added to some of them. B

**Pull request merged**
