### PR TITLE
release-23.2: log: change fingerprint_id type to string

### PR DESCRIPTION
**Pull request by kyle-a-wong**
Backport 2/2 commits from #124628.

/cc @cockroachdb/release

---

Previously, transaction_fingerprint_id and statement_fingerprint_id were typed as uint64. Somewhere downstream, these uint64 fields were truncated into int64 max ints. As a result, telemetry logs had the same fingerprint id for different sql statements.

To fix, the field name was re-typed as a string to ensure no truncation / type conversion happens.

Epic: none
Fixes: #123665
Release note (bug fix): Fixed a bug where telemetry logs were had the same statement fingerprint id for different sql statements.

---

This backport required the following changes that aren't in the original commits from #124628:

1. reserved field number 78. This field was used in #124681, but doesn't need to be backported. Instead of including this field in the `SampledQuery` message, we are just reserving the field number
2. the signature of `ConstructStatementFingerprintID` changed in `24.1` so `telemetry_datadriven_test.go` has been updated to reflect this.

### CODE REVIEW

**Comment by yuzefovich** [comment]
I think you'll need to run `./dev gen docs` on 23.2 branch since `KVNodeIDs` is added on master but not on 23.2.

**Comment by kyle-a-wong** [comment]
> I think you'll need to run `./dev gen docs` on 23.2 branch since `KVNodeIDs` is added on master but not on 23.2.

@yuzefovich I think the docs in this PR is correct. This backport is adding `KvNodeIDs` to telemetry.proto because the PR being backported adds a field after `KvNodeIDs`.

**Review by yuzefovich — COMMENTED** [review]
This PR should not be backporting `KVNodeIDs` field because it is orthogonal to this change. Instead, you should remove inclusion of `KVNodeIDs` to the proto but keep the same proto field number 79 for new field - this is backwards- and forward- compatible way of doing things.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125043#-:-NzZOcHj2opacYjcGcge:b1h6e7y)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @mgartner, @nkodali, and @rafiss)

**Review by kyle-a-wong — COMMENTED** [review]
okay i can remove `KVNodeIDs`.  I thought I would leave it in just for visibility instead of just skipping over the field number, but I can remove it, reserve 78,  and leave a comment instead. Does that sound good?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125043#-:-NzZQf6l2LrqRjJ4fD9e:b-3wch4w)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @mgartner, @nkodali, and @rafiss)

**Review by yuzefovich — COMMENTED** [review]
It's somewhat common to skip over fields in the backports. Leaving a comment sounds good to me, thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125043#-:-NzZSBRECKmyEvF3Vj25:b-veh5vv)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @mgartner, @nkodali, and @rafiss)

**Review by kyle-a-wong — COMMENTED** [review]
Cool, this is done. TFTR

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125043#-:-NzZTUQ8CClsksxUTHV3:bfekfga)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @mgartner, @nkodali, and @rafiss)

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125043)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @kyle-a-wong, @mgartner, @nkodali, and @rafiss)

___
*[`pkg/util/log/eventpb/telemetry.proto` line 305 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/125043#-NzZUq_88ofCee4sj-gr:-NzZUq_88ofCee4sj-gs:b-ebym1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/d18f050ab7efed7789472a193cc11670cc8dc32d/pkg/util/log/eventpb/telemetry.proto#L305)):*
> ```proto
>   // PR #124681 used this field for KVNodeIDs, but isn't being backported to 23.2. Instead, it
>   // is reserved for visibility and to ensure compatability in the future.
>   reserved 78;
> ```

Hm, actually I'm not sure whether explicitly reserving this field is forward-compatible (I think it is but haven't seen this pattern before). In other words, the common pattern I've seen is "used" -> "reserved" and then the field number is never used again, but in this case it'll be "reserved" -> "used".

Personally, I'd remove the reservation since it's quite unlikely that we'll be backporting telemetry proto changes to 23.2 branch, and in any case the field numbers must be preserved between versions, so having 78 field used on master should be sufficient to prevent conflicts for backports too. That said, this might be fine, but someone more familiar with protobufs than me should sign off on this.

**Review by dhartunian — APPROVED** [review]
I think it's fine to keep the `reserved` entry for forward compatibility.

**Review by rafiss — APPROVED** [review]

**Pull request merged**
