### PR TITLE
storage: move rangeDesc out of replica.mu, and use it in Desc()

### PR DESCRIPTION
**Pull request by rjnn**
509c454 made replica.String() readable without locks, and prepended
all logs and errors with it. Prepend panics as well.

In #7871, replica.String() was refactored to use a new atomically
readable copy of the RangeDescriptor. replica.Desc() could use this as
well (so as to not lock replica.mu), but this change was
conservatively deferred. However, with the issue of replica.Desc()
acquiring locks being raised in #7888, and after discussion with
@bdarnell, it should be safe to refactor replica.Desc() as well.

Finally replica.mu.rangeDesc is moved outside mu to replica.rangeDesc
to maintain the semantics of replica.mu

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7904)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/replica.go, line 203 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7904#-KN-Z-jIiqM6tcKHCrcW:-KN-Z-jIiqM6tcKHCrcX:154803611) ([raw file](https://github.com/cockroachdb/cockroach/blob/95d559095fe378d8c2f78a4c7e41664584590ef1/storage/replica.go#L203)):*
> ```Go
> 	// replica.Desc() without needing to acquire the replica.mu lock. All
> 	// updates to state.Desc should be duplicated here (as is done in
> 	// updateRangeDescriptorLocked())
> ```

`updateRangeDescriptorLocked` no longer exists. I'd just remove that parenthetical.

---

*[storage/replica.go, line 811 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7904#-KN-ZQmOJ9Rv4-OM6aD2:-KN-ZQmOJ9Rv4-OM6aD3:1286599159) ([raw file](https://github.com/cockroachdb/cockroach/blob/95d559095fe378d8c2f78a4c7e41664584590ef1/storage/replica.go#L811)):*
> ```Go
> 	diskState, err := loadState(reader, r.mu.state.Desc)
> 	if err != nil {
> 		panic(fmt.Sprintf("%s: %v", r, err))
> ```

You can add a `Replica.panic(err error)` method which encapsulates this boilerplate and then call `r.panic(err)` everywhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7904#-:-KN-ZleEkVpyURQU3AFy:1417088721)*

**Comment by arjunravinarayan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/replica.go, line 203 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7904#-KN-Z-jIiqM6tcKHCrcW:-KN-zQgTFeHeYSUIU4FR:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/95d559095fe378d8c2f78a4c7e41664584590ef1/storage/replica.go#L203)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `updateRangeDescriptorLocked` no longer exists. I'd just remove that parenthetical.
</details>
Done.

---

*[storage/replica.go, line 811 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7904#-KN-ZQmOJ9Rv4-OM6aD2:-KN02ZNxU6W9T1h_1F4n:-1040668367) ([raw file](https://github.com/cockroachdb/cockroach/blob/95d559095fe378d8c2f78a4c7e41664584590ef1/storage/replica.go#L811)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> You can add a `Replica.panic(err error)` method which encapsulates this boilerplate and then call `r.panic(err)` everywhere.
</details>
Done. Somewhat unsatisfying since we have to handle `panic(err Error)`, `panic(s String)`, and `panic(f fmt, ...)`, which are all used. I've used the `%v` to combine the former two cases. Not completely sure I got it right though, PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7904)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/replica.go, line 811 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7904#-KN-ZQmOJ9Rv4-OM6aD2:-KN0IfdTHpNtTsRy83_c:533905157) ([raw file](https://github.com/cockroachdb/cockroach/blob/95d559095fe378d8c2f78a4c7e41664584590ef1/storage/replica.go#L811)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Ravi Narayan) wrote…</i></summary>
> Done. Somewhat unsatisfying since we have to handle `panic(err Error)`, `panic(s String)`, and `panic(f fmt, ...)`, which are all used. I've used the `%v` to combine the former two cases. Not completely sure I got it right though, PTAL.
</details>
This could be a pair of `panic` and `panicf` methods. But it doesn't seem to be used often enough to be worth the trouble.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7904#-:-KN0IdB85d2kQ8aGP62u:1417088721)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/replica.go, line 2649 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7904#-KN2LEg6-6n8XivmUC7M:-KN2LEg6-6n8XivmUC7N:117353106) ([raw file](https://github.com/cockroachdb/cockroach/blob/00699200313bfd5d05831aa711e42261bc3d9599/storage/replica.go#L2649)):*
> ```Go
> }
> 
> func (r *Replica) panic(i interface{}) {
> ```

Per @bdarnell's comment, this could be:

```
func (r *Replica) panicf(format string, vals ...interface{}) {
  panic(r.String() + ": " + fmt.Sprintf(string, vals...))
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7904)*

**Comment by tschottdorf** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/replica.go, line 811 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7904#-KN-ZQmOJ9Rv4-OM6aD2:-KN2PKL6hje4_Gz-i-TN:243517372) ([raw file](https://github.com/cockroachdb/cockroach/blob/95d559095fe378d8c2f78a4c7e41664584590ef1/storage/replica.go#L811)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> This could be a pair of `panic` and `panicf` methods. But it doesn't seem to be used often enough to be worth the trouble.
</details>
I agree that `panicf` isn't worth it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7904)*

**Comment by arjunravinarayan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/replica.go, line 811 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7904#-KN-ZQmOJ9Rv4-OM6aD2:-KN2rDiK1mo4QhCsZqnt:-1910861519) ([raw file](https://github.com/cockroachdb/cockroach/blob/95d559095fe378d8c2f78a4c7e41664584590ef1/storage/replica.go#L811)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> I agree that `panicf` isn't worth it.
</details>
I went ahead and did it anyway. IMO its cleaner and I learned some useful things about variadics so it wasn't wasted time.

---

*[storage/replica.go, line 2649 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7904#-KN2LEg6-6n8XivmUC7M:-KN2rHsmERkZwl_QpO7M:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/00699200313bfd5d05831aa711e42261bc3d9599/storage/replica.go#L2649)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Per @bdarnell's comment, this could be:
> 
> ```
> func (r *Replica) panicf(format string, vals ...interface{}) {
>   panic(r.String() + ": " + fmt.Sprintf(string, vals...))
> }
> ```
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7904)*

**Comment by arjunravinarayan** [comment]
*[storage/replica.go, line 811 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7904#-KN-ZQmOJ9Rv4-OM6aD2:-KN3PYlQE0JW10kzqfUS:-1899975299) ([raw file](https://github.com/cockroachdb/cockroach/blob/95d559095fe378d8c2f78a4c7e41664584590ef1/storage/replica.go#L811)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Ravi Narayan) wrote…</i></summary>
> I went ahead and did it anyway. IMO its cleaner and I learned some useful things about variadics so it wasn't wasted time.
</details>
Done. @tschottdorf PTAL just to ensure there isn't any regression due to the dual `panic` and `panicf` methods?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7904)*

**Pull request merged**
