### PR TITLE
cli: deflake TestPartialZip

### PR DESCRIPTION
**Pull request by tbg**
- cli: improve TestPartialZip
- cli: don't cpu profile local cluster in zip test

Release justification: testing fix
Release note: None

### CODE REVIEW

**Comment by knz** [comment]
LGTM moduly my suggestion to use `log.ScopeWithoutShowLogs`

**Review by knz — APPROVED** [review]

**Comment by tbg** [comment]
bors r=knz

Added the suggested change.

**Review by knz — APPROVED** [review]

**Comment by tbg** [comment]
bors r=knz

Looks like we want a rel justification in the PR message, not just on each commit. Alright.

**Comment by otan** [comment]
bors r-

still looks flaky

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/2228301?
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/2228256?

**Comment by tbg** [comment]
Both are

```
retrieving SQL data for crdb_internal.cluster_transactions... writing: debug/crdb_internal.cluster_transactions.txt
+(error encountered after some results were delivered)
+writing: debug/crdb_internal.cluster_transactions.txt.err.txt
+  ^- resulted in ...
retrieving SQL data for crdb_internal.jobs... writing: debug/crdb_internal.jobs.txt
retrieving SQL data for system.jobs... writing: debug/system.jobs.txt
retrieving SQL data for system.descriptor... writing: debug/system.descriptor.txt
retrieving SQL data for system.namespace... writing: debug/system.namespace.txt
retrieving SQL data for system.namespace2... writing: debug/system.namespace2.txt
@@ -251,6 +254,7 @@
requesting table details for system.ui... writing: debug/schema/system/ui.json
requesting table details for system.users... writing: debug/schema/system/users.json
requesting table details for system.web_sessions... writing: debug/schema/system/web_sessions.json
requesting table details for system.zones... writing: debug/schema/system/zones.json
writing: debug/pprof-summary.sh
+writing: debug/hot-ranges.sh
```

That's very odd - have never seen this before. I guess I'll try to repro.

**Comment by tbg** [comment]
Heh, this is actually merge skew. I don't understand what exactly happened but after a rebase it fails deterministically.

```
           retrieving SQL data for crdb_internal.cluster_transactions... writing: debug/crdb_internal.cluster_transactions.txt
        (error encountered after some results were delivered)
        writing: debug/crdb_internal.cluster_transactions.txt.err.txt
          ^- resulted in pq: internal error: datum row count and column count differ: 6 vs 9
```

the query run here is `     SET statement_timeout = '10s'; SELECT * FROM crdb_internal.cluster_transactions
`

**Comment by tbg** [comment]
Ok, this was accidentally broken in bae332dd5142a3a341870438c49d2c3aa2362dbe. Prepended a commit to fix it. Should turn green now.

bors r=knz

**Pull request merged**
