### PR TITLE
kvserver: introduce a hard cap on range sizes

### PR DESCRIPTION
**Pull request by arulajmani**
This patch introduces a new cluster setting called `kv.range.range_size_hard_cap`. It's configured in bytes and places an absolute value cap on how large we'll allow ranges to get before backpressuring writes. We default it to 8GB.

This setting is inteded to be the last defense against absurdly large ranges. In particular, it guards against risks where backpressure is otherwise disabled due to other cluster settings. See `kv.range.backpressure_byte_tolerance` for an explanation of how this is possible.

Informs https://github.com/cockroachdb/cockroach/issues/128082

Release note: None

### CODE REVIEW

**Review by kvoli — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129450)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[`pkg/kv/kvserver/replica_backpressure.go` line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129450#-O4uWqUv6TMoB4wiBUTT:-O4uWqUv6TMoB4wiBUTU:bvzijv6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2150c51d5fd2a0a76d7d3d8074a95033c45d66d8/pkg/kv/kvserver/replica_backpressure.go#L43)):*
> ```Go
> 	"hard cap on the maximum size a range is allowed to grow to without"+
> 		"splitting before writes to the range are blocked. Takes precedence over all other configurations",
> 	8<<30, /* 8 GiB */
> ```

I couldn't find any places where we previously capped the max range size, a user could previously specify an arbitrarily large max range size in their zone configuration. 

https://github.com/cockroachdb/cockroach/blob/ee0510dbec58583d31b77bfa3c83338cc3f09898/pkg/config/zonepb/zone.go#L400-L411

Does this deserve a release note/docs?

**Review by arulajmani — COMMENTED** [review]
TFTR! @kvoli could you have another look at the most recent push? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129450#-:-O4ugNMp2UpG915cUMuG:b9gmp2g)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @nvanbenschoten)

___
*[`pkg/kv/kvserver/replica_backpressure.go` line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129450#-O4uWqUv6TMoB4wiBUTT:-O4uchhK8Ve71eal5aZg:brd5qvk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2150c51d5fd2a0a76d7d3d8074a95033c45d66d8/pkg/kv/kvserver/replica_backpressure.go#L43)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

I couldn't find any places where we previously capped the max range size, a user could previously specify an arbitrarily large max range size in their zone configuration. 

https://github.com/cockroachdb/cockroach/blob/ee0510dbec58583d31b77bfa3c83338cc3f09898/pkg/config/zonepb/zone.go#L400-L411

Does this deserve a release note/docs?
</blockquote></details>

Good point, I think this deserves a release note and I think we should make this setting public as well (so that it's included in the docs). 

I also added some zone config guardrails.

**Review by kvoli — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129450#-:-O4ukdrC3zxVfujCxxAF:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by arulajmani** [comment]
Thanks!

bors r=kvoli

**Comment by arulajmani** [comment]
blathers backport 23.2 23.1 24.1 24.2

**Pull request merged**
