### PR TITLE
sql: check that Publish() increments the table version once

### PR DESCRIPTION
**Pull request by vivekmenezes**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14131)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/lease.go, line 367 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131#-KfDXK8nPXORjktMWzkO:-KfDXK8oTpXzSJeDasCH:b-elbop7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b811a3a8da68ce92db7ce2791955de9115124504/pkg/sql/lease.go#L367)):*
> ```Go
> 			now := s.clock.Now()
> 			tableDesc.ModificationTime = now
> 			if log.V(3) {
> ```

why did this change in this commit?

---

*[pkg/sql/lease_test.go, line 417 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131#-KfDXRFnCjOTgpOysE6v:-KfDXRFnCjOTgpOysE6w:b-tskdfe) ([raw file](https://github.com/cockroachdb/cockroach/blob/66b1056e2fa24e28650aaaef03a8839ebe3ab2e6/pkg/sql/lease_test.go#L417)):*
> ```Go
> 	if _, err := t.node(1).Publish(
> 		context.TODO(), keys.LeaseTableID, func(table *sqlbase.TableDescriptor) error {
> 			table.Version++
> ```

what about decrementing?

---

*[pkg/sql/schema_changer_test.go, line 1191 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131#-KfDXVsBjGKvmVIAk1lU:-KfDXVsBjGKvmVIAk1lV:bylgh2s) ([raw file](https://github.com/cockroachdb/cockroach/blob/66b1056e2fa24e28650aaaef03a8839ebe3ab2e6/pkg/sql/schema_changer_test.go#L1191)):*
> ```Go
> 	upTableVersion = func() {
> 		leaseMgr := s.LeaseManager().(*sql.LeaseManager)
> 		if _, err := leaseMgr.Publish(ctx, id, func(table *sqlbase.TableDescriptor) error {
> ```

nit: s/table //

is it legal to pass a nil callback?

---

*[pkg/sql/schema_changer_test.go, line 1201 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131#-KfDXkL7scf4zt7dqzuO:-KfDXkL7scf4zt7dqzuP:b29iez) ([raw file](https://github.com/cockroachdb/cockroach/blob/66b1056e2fa24e28650aaaef03a8839ebe3ab2e6/pkg/sql/schema_changer_test.go#L1201)):*
> ```Go
> 		// that all future leases will be taken at the latest version.
> 		tableDesc := sqlbase.GetTableDescriptor(kvDB, "t", "test")
> 		testutils.SucceedsSoon(t, func() error {
> ```

why does this need a retry loop? add a comment.

---

*[pkg/sql/schema_changer_test.go, line 1202 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131#-KfDXdeVq4t7lHWfpE65:-KfDXdeVq4t7lHWfpE66:b5alklo) ([raw file](https://github.com/cockroachdb/cockroach/blob/66b1056e2fa24e28650aaaef03a8839ebe3ab2e6/pkg/sql/schema_changer_test.go#L1202)):*
> ```Go
> 		tableDesc := sqlbase.GetTableDescriptor(kvDB, "t", "test")
> 		testutils.SucceedsSoon(t, func() error {
> 			err := kvDB.Txn(ctx, func(txn *client.Txn) error {
> ```

nit: `return kvDB.Txn(...)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131)*

**Comment by vivekmenezes** [comment]
Review status: 1 of 4 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/sql/lease.go, line 367 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131#-KfDXK8nPXORjktMWzkO:-KfEsqDqfefNEuuKBbnB:bn3tzfb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b811a3a8da68ce92db7ce2791955de9115124504/pkg/sql/lease.go#L367)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why did this change in this commit?
</blockquote></details>

I felt this was worth logging. We do log whenever we're waiting for a version in WaitForOneVersion().

---

*[pkg/sql/lease_test.go, line 417 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131#-KfDXRFnCjOTgpOysE6v:-KfEtuvr4pv50LmndBJW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/66b1056e2fa24e28650aaaef03a8839ebe3ab2e6/pkg/sql/lease_test.go#L417)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

what about decrementing?
</blockquote></details>

Done.

---

*[pkg/sql/schema_changer_test.go, line 1191 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131#-KfDXVsBjGKvmVIAk1lU:-KfEuD4ZUhsTRiIjnWIb:b-2ww78) ([raw file](https://github.com/cockroachdb/cockroach/blob/66b1056e2fa24e28650aaaef03a8839ebe3ab2e6/pkg/sql/schema_changer_test.go#L1191)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: s/table //

is it legal to pass a nil callback?
</blockquote></details>

No. Not worth adding support for that just for this test.

---

*[pkg/sql/schema_changer_test.go, line 1201 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131#-KfDXkL7scf4zt7dqzuO:-KfHgK1cDZi7pSW192_L:bjyuxaq) ([raw file](https://github.com/cockroachdb/cockroach/blob/66b1056e2fa24e28650aaaef03a8839ebe3ab2e6/pkg/sql/schema_changer_test.go#L1201)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why does this need a retry loop? add a comment.
</blockquote></details>

The retry loop was not needed. acquire() already had a retry loop.

---

*[pkg/sql/schema_changer_test.go, line 1202 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131#-KfDXdeVq4t7lHWfpE65:-KfEuK3Dc03lyXpWtFdS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/66b1056e2fa24e28650aaaef03a8839ebe3ab2e6/pkg/sql/schema_changer_test.go#L1202)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: `return kvDB.Txn(...)`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131)*

**Comment by vivekmenezes** [comment]
Thanks for reviewing this change. Ready for another review

---

Review status: 1 of 4 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131#-:-KfHgSE-7vmVqJAMA7aR:b-a96g8i)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/schema_changer_test.go, line 1191 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131#-KfDXVsBjGKvmVIAk1lU:-KfHh1dnCBn6vfpEhKHf:bkgfxs3) ([raw file](https://github.com/cockroachdb/cockroach/blob/66b1056e2fa24e28650aaaef03a8839ebe3ab2e6/pkg/sql/schema_changer_test.go#L1191)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

No. Not worth adding support for that just for this test.
</blockquote></details>

Agreed. How about the s/table // bit?

---

*[pkg/sql/schema_changer_test.go, line 1208 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131#-KfHh8qNrPi-sLsleFYD:-KfHh8qNrPi-sLsleFYE:b6pg9e5) ([raw file](https://github.com/cockroachdb/cockroach/blob/0efd7de95751cd7e4ddf5202f745767502c027db/pkg/sql/schema_changer_test.go#L1208)):*
> ```Go
> 			return leaseMgr.Release(lease)
> 		}); err != nil {
> 			t.Error(err)
> ```

not Fatal?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131)*

**Comment by vivekmenezes** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/schema_changer_test.go, line 1191 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131#-KfDXVsBjGKvmVIAk1lU:-KfHxgceIl03bPRQ85vm:bj7e5ty) ([raw file](https://github.com/cockroachdb/cockroach/blob/66b1056e2fa24e28650aaaef03a8839ebe3ab2e6/pkg/sql/schema_changer_test.go#L1191)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Agreed. How about the s/table // bit?
</blockquote></details>

ah ha, I now use the table to read the previous version that's used down below. In a previous incarnation, we would call sqlbase.GetTableDescriptor() just to get the latest version.
I've also updated the comment in lease.go that updates the version.

---

*[pkg/sql/schema_changer_test.go, line 1208 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131#-KfHh8qNrPi-sLsleFYD:-KfHxsb8ZFdMN3OLfOYS:b-x7qxgc) ([raw file](https://github.com/cockroachdb/cockroach/blob/0efd7de95751cd7e4ddf5202f745767502c027db/pkg/sql/schema_changer_test.go#L1208)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

not Fatal?
</blockquote></details>

Yeah, upTableVersion is called from a different thread.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/lease.go, line 368 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131#-KfI1BXSpsfnab49S3HR:-KfI1BXSpsfnab49S3HS:blln5mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b14b198621cb08b0eed1a057ea526991f90ca481/pkg/sql/lease.go#L368)):*
> ```Go
> 			}
> 
> 			// Bump the version and modification time. Bump the version
> ```

why "bump the version" twice?

this comment doesn't seem useful at all (including the old one); I'd rather you just remove it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131#-:-KfI1OvYkjqr67CHDFDb:bnfp4nl)*

**Comment by vivekmenezes** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/lease.go, line 368 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131#-KfI1BXSpsfnab49S3HR:-KfI2IrNe4qeCbDghmtw:b-ubva1i) ([raw file](https://github.com/cockroachdb/cockroach/blob/b14b198621cb08b0eed1a057ea526991f90ca481/pkg/sql/lease.go#L368)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why "bump the version" twice?

this comment doesn't seem useful at all (including the old one); I'd rather you just remove it.
</blockquote></details>

Removed! TFTR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/schema_changer_test.go, line 1113 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131#-KfIFbTEV_acprMjXXEb:-KfIFbTEV_acprMjXXEc:bpsd2q8) ([raw file](https://github.com/cockroachdb/cockroach/blob/548e4ebf3f2f5f377be8a8fe55519acfff88a809/pkg/sql/schema_changer_test.go#L1113)):*
as we were talking in the PR comments on https://reviewable.io/reviews/cockroachdb/cockroach/13900#-
I don't understand the need for this test - how can a descriptor version be incremented during a schema change?
You've said
> I think the main problem here is that we don't have a way to control two nodes not run the schema changer, since the
lease is not guaranteed to be held by one. I had added this test because when a table gets dropped in the middle of a schema change, the drop can get activated by another node, if it is able to somehow gain the lease. I think it's worth creating an issue to drop this test of figure out a way in which we can eliminate the need for this test in the future.

What do you mean by "the lease is not guaranteed to be held by one (node)"? Isn't that the point of the lease?

---

*[pkg/sql/schema_changer_test.go, line 1117 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131#-KfIFSRcfSi6QR0yYFCt:-KfIFSRdwckDuIo1m7PB:bg9onvw) ([raw file](https://github.com/cockroachdb/cockroach/blob/548e4ebf3f2f5f377be8a8fe55519acfff88a809/pkg/sql/schema_changer_test.go#L1117)):*
> ```Go
> 	params, _ := createTestServerParams()
> 	var upTableVersion func()
> 	attempts := 0
> ```

I think `attempts` is a bad name. I think it should be `curChunk`.

---

*[pkg/sql/schema_changer_test.go, line 1199 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131#-KfIDLZolUz6cSo-t78w:-KfIDLZolUz6cSo-t78x:b-z4ifmu) ([raw file](https://github.com/cockroachdb/cockroach/blob/548e4ebf3f2f5f377be8a8fe55519acfff88a809/pkg/sql/schema_changer_test.go#L1199)):*
> ```Go
> 			t.Error(err)
> 		}
> 		// Grab a lease at the latest version so that we are confident
> ```

mind explaining why this is necessary? Would the test otherwise not detect that the descriptor has been changed, and hence not retry?

And also how come this has changed from using `leaseMgr.WaitForOneVersion()`? Doesn't that more directly express the intent of making sure that future leases are at the new version?
Better yet, to properly trigger the conflict between a descriptor update and the backfill, could we integrate with gossip/the lease manager and wait until gossip causes a lease on the new version to be acquired by the node?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131)*

**Comment by vivekmenezes** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/schema_changer_test.go, line 1113 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131#-KfIFbTEV_acprMjXXEb:-KfIJUnD3FSY9hnpjl7F:b-vjoyv3) ([raw file](https://github.com/cockroachdb/cockroach/blob/548e4ebf3f2f5f377be8a8fe55519acfff88a809/pkg/sql/schema_changer_test.go#L1113)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

as we were talking in the PR comments on https://reviewable.io/reviews/cockroachdb/cockroach/13900#-
I don't understand the need for this test - how can a descriptor version be incremented during a schema change?
You've said
> I think the main problem here is that we don't have a way to control two nodes not run the schema changer, since the
lease is not guaranteed to be held by one. I had added this test because when a table gets dropped in the middle of a schema change, the drop can get activated by another node, if it is able to somehow gain the lease. I think it's worth creating an issue to drop this test of figure out a way in which we can eliminate the need for this test in the future.

What do you mean by "the lease is not guaranteed to be held by one (node)"? Isn't that the point of the lease?
</blockquote></details>

The point of the lease so far is to limit the duplicate work done, see the comment in structured.proto https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sqlbase/structured.proto#L414

 Our schema change lease does not guarantee that they are held by one node. For instance a node can use an expired lease and that is still valid. This is even more possible thanks to bugs like https://github.com/cockroachdb/cockroach/issues/13940

I agree that we should probably make leases and their use robust, but until then we have to accommodate more than one node potentially running a schema change.

---

*[pkg/sql/schema_changer_test.go, line 1117 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131#-KfIFSRcfSi6QR0yYFCt:-KfIKdkF6-TCKOm54IIG:bb03zas) ([raw file](https://github.com/cockroachdb/cockroach/blob/548e4ebf3f2f5f377be8a8fe55519acfff88a809/pkg/sql/schema_changer_test.go#L1117)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think `attempts` is a bad name. I think it should be `curChunk`.
</blockquote></details>

okay will send out a followup PR

---

*[pkg/sql/schema_changer_test.go, line 1199 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131#-KfIDLZolUz6cSo-t78w:-KfIKhLf6jhpjif8cg5H:bku1gne) ([raw file](https://github.com/cockroachdb/cockroach/blob/548e4ebf3f2f5f377be8a8fe55519acfff88a809/pkg/sql/schema_changer_test.go#L1199)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

mind explaining why this is necessary? Would the test otherwise not detect that the descriptor has been changed, and hence not retry?

And also how come this has changed from using `leaseMgr.WaitForOneVersion()`? Doesn't that more directly express the intent of making sure that future leases are at the new version?
Better yet, to properly trigger the conflict between a descriptor update and the backfill, could we integrate with gossip/the lease manager and wait until gossip causes a lease on the new version to be acquired by the node?
</blockquote></details>

we do this to ensure that we always see exactly one retry. So when we retry and acquire a new lease we see the latest version and therefore don't hit another version incompatibility error.

We cannot use leaseMgr.WaitForOneVersion() because distsql based schema changes hold on to a lease before running, and this code is run on a remote node while a lease on a priori version is being held, therefore leaseMgr.WaitForOneVersion() will hang indefinitely.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/schema_changer_test.go, line 1113 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131#-KfIFbTEV_acprMjXXEb:-KfJ4HfpPRlEghItyRqf:b-lm71d1) ([raw file](https://github.com/cockroachdb/cockroach/blob/548e4ebf3f2f5f377be8a8fe55519acfff88a809/pkg/sql/schema_changer_test.go#L1113)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

The point of the lease so far is to limit the duplicate work done, see the comment in structured.proto https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sqlbase/structured.proto#L414

 Our schema change lease does not guarantee that they are held by one node. For instance a node can use an expired lease and that is still valid. This is even more possible thanks to bugs like https://github.com/cockroachdb/cockroach/issues/13940

I agree that we should probably make leases and their use robust, but until then we have to accommodate more than one node potentially running a schema change.
</blockquote></details>

I see, thanks.
But I still don't see why this test is important :). So ok, let's say node B can take the  schema change lease while node A was running a backfill. This means that B will apply the mutations that A was working on. So now you have two guys trying to apply the same mutation. That's cool, right? What's the risk that this test is trying to prevent?
It seems to me that we specifically don't want the same mutation to be retried, if someone else has run it. And that's not what would happen in production if a backfill would encounter the situation tested here - a table's version being incremented while the backfill is ongoing. What would happen is that, since the version has been incremented, the `mutationID` being processed by the `schemaChanger` in question has also been removed from the descriptor. So, on a retry, the `schemaChanger`would detect this and abort:
https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/backfill.go#L138
Also, on a retry, we'd also detect that someone else has the schema change lease and that's another reason for not retrying the backfill, right?

If that's correct, it seems to me that that's what we should be testing - that we *don't* retry a mutation (the opposite of this test).

Or, otherwise, if it is somehow possible for the version to change while the backfill is ongoing without the corresponding mutation also being removed from the descriptor, then the backfill should probably be allowed to continue in the face of this condition, and not have to be retried. So again I'm not sure of the point of this test.

---

*[pkg/sql/schema_changer_test.go, line 1199 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131#-KfIDLZolUz6cSo-t78w:-KfJ71tJ13krtAS4JTNP:b-ywclcj) ([raw file](https://github.com/cockroachdb/cockroach/blob/548e4ebf3f2f5f377be8a8fe55519acfff88a809/pkg/sql/schema_changer_test.go#L1199)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

we do this to ensure that we always see exactly one retry. So when we retry and acquire a new lease we see the latest version and therefore don't hit another version incompatibility error.

We cannot use leaseMgr.WaitForOneVersion() because distsql based schema changes hold on to a lease before running, and this code is run on a remote node while a lease on a priori version is being held, therefore leaseMgr.WaitForOneVersion() will hang indefinitely.
</blockquote></details>

The more I look at this test, the more questions I have... Sorry :)

1. How come the distsql backfill doesn't succeed in the first attempt of `sc.distSQLPlanner.Run(&planCtx, txn, &plan, &recv);`? Is it because you're setting the `WriteCheckpointInterval`? If so, a comment there is really needed.
2. Is there any reason why do we get a new lease after every distsql iteration, as opposed to holding one for as long as possible? Not that one would be better than the other necessarily (although I do think that just holding one lease would be cleaner), but I'm curious.
https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/backfill.go#L643

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131)*

**Comment by vivekmenezes** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/schema_changer_test.go, line 1113 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131#-KfIFbTEV_acprMjXXEb:-KfJeMzmxox710Q8NzK_:b-7zs3np) ([raw file](https://github.com/cockroachdb/cockroach/blob/548e4ebf3f2f5f377be8a8fe55519acfff88a809/pkg/sql/schema_changer_test.go#L1113)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I see, thanks.
But I still don't see why this test is important :). So ok, let's say node B can take the  schema change lease while node A was running a backfill. This means that B will apply the mutations that A was working on. So now you have two guys trying to apply the same mutation. That's cool, right? What's the risk that this test is trying to prevent?
It seems to me that we specifically don't want the same mutation to be retried, if someone else has run it. And that's not what would happen in production if a backfill would encounter the situation tested here - a table's version being incremented while the backfill is ongoing. What would happen is that, since the version has been incremented, the `mutationID` being processed by the `schemaChanger` in question has also been removed from the descriptor. So, on a retry, the `schemaChanger`would detect this and abort:
https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/backfill.go#L138
Also, on a retry, we'd also detect that someone else has the schema change lease and that's another reason for not retrying the backfill, right?

If that's correct, it seems to me that that's what we should be testing - that we *don't* retry a mutation (the opposite of this test).

Or, otherwise, if it is somehow possible for the version to change while the backfill is ongoing without the corresponding mutation also being removed from the descriptor, then the backfill should probably be allowed to continue in the face of this condition, and not have to be retried. So again I'm not sure of the point of this test.
</blockquote></details>

the version check is mainly to prevent a table that has been dropped from being continued to be acted on by the schema changer. But yes even the table drop code must hold on to the schema change lease in order to increment the version and then subsequently delete the data from the table.

The point of this test is to test that a version change is detected and a full retry is initiated. It's not a very important test, but we do have code that is checking versions and that needs to be tested which is being tested by this test.

I'm not saying you don't have points here, I'm just saying that the implementation has to change for this test to be changed/removed. I think guaranteeing the exclusive use of the lease could be a good first step to reduce complexity here.

---

*[pkg/sql/schema_changer_test.go, line 1199 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131#-KfIDLZolUz6cSo-t78w:-KfJgjWsjBKFIyWMcOmg:ben06zo) ([raw file](https://github.com/cockroachdb/cockroach/blob/548e4ebf3f2f5f377be8a8fe55519acfff88a809/pkg/sql/schema_changer_test.go#L1199)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

The more I look at this test, the more questions I have... Sorry :)

1. How come the distsql backfill doesn't succeed in the first attempt of `sc.distSQLPlanner.Run(&planCtx, txn, &plan, &recv);`? Is it because you're setting the `WriteCheckpointInterval`? If so, a comment there is really needed.
2. Is there any reason why do we get a new lease after every distsql iteration, as opposed to holding one for as long as possible? Not that one would be better than the other necessarily (although I do think that just holding one lease would be cleaner), but I'm curious.
https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/backfill.go#L643
</blockquote></details>

1. Yes it's because of WriteCheckpointInterval
2. you're not allowed to hold a lease for an extended period of time (> 5 minutes). we have to have a mechanism to expire leases held by nodes and version changes are disallowed until then, and schema changes will all get queued up until expiration of leases.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14131)*

**Pull request merged**
