### PR TITLE
slstorage: support regional by row system.sqlliveness

### PR DESCRIPTION
**Pull request by jeffswenson**
The COCKROACH_MR_SYSTEM_DATABASE environment variable was introduced to
control features added as part of #85736. The variable will be removed
once migrations and version gates are implemented for the multi-region
system database optimizations.

The sqlliveness table now supports an index format compatible with
regional by row tables. Multi region serverless is the motivation for
this change. When a sql server starts up, it must write its session to
the sqlliveness table. The remote session write can add ~400ms to a
servers startup time.

```
$ COCKROACH_MR_SYSTEM_DATABASE=1 ./cockroach-short demo
demo@127.0.0.1:26257/movr> SELECT * FROM system.sqlliveness;
  crdb_region |            session_uuid            |           expiration
--------------+------------------------------------+---------------------------------
  \x80        | \x5895d5d121984d86bcb81d6a89d5635d | 1667511355275484444.0000000000

$ COCKROACH_MR_SYSTEM_DATABASE=0 ./cockroach-short demo
demo@127.0.0.1:26257/movr> select * from system.sqlliveness;
                 session_id                |           expiration
-------------------------------------------+---------------------------------
  \x0101805fc92bdb0e8d4cb4aec3e1527a3052b8 | 1667511392212781946.0000000000
```

Part of #85736

Release note: None

### CODE REVIEW

**Comment by JeffSwenson** [comment]
Marking this as a draft for now. I'll remove the draft label once I implement the upgrade job.

**Review by ajwerner — COMMENTED** [review]
Nice work and nice tests. Sorry I didn't give this a look until now. I'll give it a deeper read when I find a gap later this morning. One thing we'll need to sort out after this is the story to plumb the region for the current process into this code. 

Another thing to note is some of this code is shifting underneath you with #90875 and #90586. 

Regarding the system table literal test. I think there's a few options. One would be to do as you suggest with `SHOW CREATE TABLE`. I think that's a good fine idea either way. Another thing we can do is attach some special cases to muck with things and then make sure it matches. Like just for this case, attach a closure in a map that might go in and adjust the IDs after calling `CreateTestTableDescriptor`. 

> Reviewed 7 of 7 files at r1, 5 of 5 files at r2, 4 of 19 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90408#-:-NFiJF1W66Uv57tD_W_b:bqzpu01)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jaylim-crl and @JeffSwenson)

___
*[`pkg/sql/sqlliveness/slstorage/table.go` line 49 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90408#-NFiIg5J7-1qYlahSrpX:-NFiIg5J7-1qYlahSrpY:bt5e6nl) ([raw file](https://github.com/cockroachdb/cockroach/blob/9707e5e8a5251ae6c302fd970f52d8424b0b269f/pkg/sql/sqlliveness/slstorage/table.go#L49)):*
> ```Go
> // After the version gate is flipped, servers stop dual writing. The legacy RBT
> // index is eventually cleaned up by deleteExpiredSessions.
> type Table struct {
> ```

do the concepts in this file need to be exported?
___
*[`pkg/sql/catalog/systemschema_test/testdata/bootstrap` line 283 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90408#-NFiIOHVCHewSv8KJ5dk:-NFiIOHVCHewSv8KJ5dl:b-35z90z) ([raw file](https://github.com/cockroachdb/cockroach/blob/9707e5e8a5251ae6c302fd970f52d8424b0b269f/pkg/sql/catalog/systemschema_test/testdata/bootstrap#L283)):*
> ```
> 	FAMILY other (schedule_name, created, owner, schedule_expr, schedule_details, executor_type, execution_args)
> );
> CREATE TABLE public.sqlliveness (
> ```

one thing we could do is put a unique without index constraint on the primary index. That's implicitly what an RBR table does IIRC. 
___
*[`pkg/sql/sqlliveness/slstorage/sessionid_test.go` line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90408#-NFiHluK12bSi5Y2FP1K:-NFiHluK12bSi5Y2FP1L:b-iz8noc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e826e39775e114e8ac634a7b879b32e80f4df17d/pkg/sql/sqlliveness/slstorage/sessionid_test.go#L25)):*
> ```Go
> )
> 
> func FuzzSessionIDEncoding(f *testing.F) {
> ```

Cool! This is the first use of this I've seen

**Review by jeffswenson — COMMENTED** [review]
I've significantly changed the details of the implementation, but the end result is nearly the same. The big changes are:
1. I removed the version gates and added the COCKROACH_MR_SYSTEM_DATABASE environment variable.
2. I replaced `Table` with `keyCodec`. As I was refactoring to support both index formats, I decided Table wasn't really pulling it's weight as an abstraction, so I replaced it with the more minimum keyCodec API. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90408#-:-NFzSEWW9m81G5DfxxH4:b-y21f45)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @jaylim-crl)

___
*[`pkg/sql/catalog/systemschema_test/testdata/bootstrap` line 283 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90408#-NFiIOHVCHewSv8KJ5dk:-NFzV1-D5Fv5ixN7Qqgn:b-mewyed) ([raw file](https://github.com/cockroachdb/cockroach/blob/9707e5e8a5251ae6c302fd970f52d8424b0b269f/pkg/sql/catalog/systemschema_test/testdata/bootstrap#L283)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

one thing we could do is put a unique without index constraint on the primary index. That's implicitly what an RBR table does IIRC. 
</blockquote></details>

Can you elaborate? How would I define that in SQL and what is the advantage compared to the explicit primary key?
___
*[`pkg/sql/sqlliveness/slstorage/table.go` line 49 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90408#-NFiIg5J7-1qYlahSrpX:-NFzS0lR64v_YoVEjBre:b-e6z92d) ([raw file](https://github.com/cockroachdb/cockroach/blob/9707e5e8a5251ae6c302fd970f52d8424b0b269f/pkg/sql/sqlliveness/slstorage/table.go#L49)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

do the concepts in this file need to be exported?
</blockquote></details>

Done

I was exporting Table so it could be used for tests. I replaced `Table` with `keyCodec` and now use slstorage.Storage in the multi region table test.

**Review by ajwerner — APPROVED** [review]
This is satisfyingly more simple! Just nits from me. 

> Reviewed 1 of 23 files at r5, 6 of 8 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90408#-:-NGItLY1ERfZv43XW2Vz:bq9z1gt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jaylim-crl and @JeffSwenson)

___
*[`pkg/sql/catalog/systemschema/system.go` line 2010 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/90408#-NGIt_KT949RzUvZb2nn:-NGIt_KT949RzUvZb2no:bqfcdas) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f64385e6fd78677aa113c8b6b37d60c1674196/pkg/sql/catalog/systemschema/system.go#L2010)):*
> ```Go
> 	// SqllivenessTable is the descriptor for the sqlliveness table.
> 	SqllivenessTable = func() catalog.TableDescriptor {
> 		if SupportMultiRegion() {
> ```

can you add another sentence for any wayward souls who find themselves in this file to answer what this ceremony is about and to inform them that this is not intended to be long for this world. Or just direct them to `SupportsMultiRegion`. 



_Code quote:_
```Go
	SqllivenessTable = func() catalog.TableDescriptor {
		if SupportMultiRegion() {
```
___
*[`pkg/sql/catalog/systemschema/system.go` line 2689 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/90408#-NGIuInh2OtcCNvjqkwE:-NGIuInh2OtcCNvjqkwF:b-qz71h6) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f64385e6fd78677aa113c8b6b37d60c1674196/pkg/sql/catalog/systemschema/system.go#L2689)):*
> ```Go
> // TODO(jeffswenson): remove SupportMultiRegion after implementing migrations
> // and version gates to migrate to the new regional by row compatible schemas.
> func SupportMultiRegion() bool {
> ```

How about calling this thing `TestingSupportMultiRegion` or something like that to make it double clear it's a hack 
___
*[`pkg/sql/catalog/systemschema/system.go` line 2690 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/90408#-NGIwYi_CZwmuYFqn-r5:-NGIwYi_CZwmuYFqn-r6:b-36ewa9) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f64385e6fd78677aa113c8b6b37d60c1674196/pkg/sql/catalog/systemschema/system.go#L2690)):*
> ```Go
> // and version gates to migrate to the new regional by row compatible schemas.
> func SupportMultiRegion() bool {
> 	val, ok := envutil.EnvString("COCKROACH_MR_SYSTEM_DATABASE", 0)
> ```

Why not `envutil.EnvOrDefaultBool`?
___
*[`pkg/sql/sqlliveness/slstorage/key_encoder.go` line 30 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/90408#-NGIt8Vd4r2k5YKCr8HN:-NGIt8Vd4r2k5YKCr8HO:bbz0nr0) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f64385e6fd78677aa113c8b6b37d60c1674196/pkg/sql/sqlliveness/slstorage/key_encoder.go#L30)):*
> ```Go
> 	encode(sid sqlliveness.SessionID) (roachpb.Key, error)
> 	decode(key roachpb.Key) (sqlliveness.SessionID, error)
> 	prefix() roachpb.Key
> ```

use some commentary to describe the meaning of `prefix` and its relationship to what you pass to `decode` and what comes out of `encode`. 
___
*[`pkg/sql/sqlliveness/slstorage/key_encoder.go` line 40 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/90408#-NGIup784PGTGtPlel-8:-NGIup784PGTGtPlel-9:bkvsaxg) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f64385e6fd78677aa113c8b6b37d60c1674196/pkg/sql/sqlliveness/slstorage/key_encoder.go#L40)):*
> ```Go
> 		return &rbrEncoder{codec.IndexPrefix(uint32(tableID), uint32(rbrIndex))}
> 	}
> 	return &rbtEncoder{codec.IndexPrefix(uint32(tableID), 1)}
> ```

nit: using consts for the index ID and the 0 family ID below will make the code feel a touch less magical. 
___
*[`pkg/ccl/multiregionccl/multiregion_system_table_test.go` line 68 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/90408#-NGIst5VC0dbRJbX5SPr:-NGIst5W4u_5lIMWG0rT:b73qcra) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f64385e6fd78677aa113c8b6b37d60c1674196/pkg/ccl/multiregionccl/multiregion_system_table_test.go#L68)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 	defer log.Scope(t).Close(t)
> 	defer envutil.TestSetEnv(t, "COCKROACH_MR_SYSTEM_DATABASE", "1")()
> ```

This works because we aren't using the system database's table, right?

**Review by jeffswenson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90408)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @jaylim-crl)

___
*[`pkg/sql/catalog/systemschema/system.go` line 2010 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/90408#-NGIt_KT949RzUvZb2nn:-NGO55Rj29Z_5kGDDZLU:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f64385e6fd78677aa113c8b6b37d60c1674196/pkg/sql/catalog/systemschema/system.go#L2010)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

can you add another sentence for any wayward souls who find themselves in this file to answer what this ceremony is about and to inform them that this is not intended to be long for this world. Or just direct them to `SupportsMultiRegion`. 
</blockquote></details>

Done
___
*[`pkg/sql/catalog/systemschema/system.go` line 2689 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/90408#-NGIuInh2OtcCNvjqkwE:-NGO56ucCZ3RK7oHZNak:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f64385e6fd78677aa113c8b6b37d60c1674196/pkg/sql/catalog/systemschema/system.go#L2689)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

How about calling this thing `TestingSupportMultiRegion` or something like that to make it double clear it's a hack 
</blockquote></details>

Done
___
*[`pkg/sql/catalog/systemschema/system.go` line 2690 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/90408#-NGIwYi_CZwmuYFqn-r5:-NGO57XG9q7m4biDbR-A:bj4ac0v) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f64385e6fd78677aa113c8b6b37d60c1674196/pkg/sql/catalog/systemschema/system.go#L2690)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Why not `envutil.EnvOrDefaultBool`?
</blockquote></details>

Done

Thanks! I did not know about EnvOrDefaultBool.
___
*[`pkg/sql/sqlliveness/slstorage/key_encoder.go` line 30 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/90408#-NGIt8Vd4r2k5YKCr8HN:-NGO5DNg3hMG4W0Pzv0V:b-70mw4u) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f64385e6fd78677aa113c8b6b37d60c1674196/pkg/sql/sqlliveness/slstorage/key_encoder.go#L30)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

use some commentary to describe the meaning of `prefix` and its relationship to what you pass to `decode` and what comes out of `encode`. 
</blockquote></details>

Done

I also renamed the method to `indexPrefix`
___
*[`pkg/sql/sqlliveness/slstorage/key_encoder.go` line 40 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/90408#-NGIup784PGTGtPlel-8:-NGO5Gd87IOxHKZcMTa-:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f64385e6fd78677aa113c8b6b37d60c1674196/pkg/sql/sqlliveness/slstorage/key_encoder.go#L40)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: using consts for the index ID and the 0 family ID below will make the code feel a touch less magical. 
</blockquote></details>

Done
___
*[`pkg/ccl/multiregionccl/multiregion_system_table_test.go` line 68 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/90408#-NGIst5VC0dbRJbX5SPr:-NGO5KbGBCH0Mdhceue-:bp6kkkg) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f64385e6fd78677aa113c8b6b37d60c1674196/pkg/ccl/multiregionccl/multiregion_system_table_test.go#L68)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This works because we aren't using the system database's table, right?
</blockquote></details>

Exactly. The actual system database table is determined by the value of the environment variable set at process start time.

**Pull request merged**
