### PR TITLE
server: add cluster organization attribute

### PR DESCRIPTION
**Pull request by dt**

### CODE REVIEW

**Comment by mberhault** [comment]
I like the addition of a cluster name. However, I think we should make it a required argument specified at init time (once we have the command) and, combined with the generated cluster ID, would make up a unique ID.

A few places where this would come in handy:
* a wrong `--join` address would refuse to join if the cluster name doesn't match (and is less cumbersome than having to know the ID)
* exported in metrics for easy multi-cluster management (see #15888) 
* used in generated SSL certificates. allows same CA to be used for multiple clusters.
* pretty!

**Comment by dt** [comment]
When we have the ability to provision settings during init, I think this is a perfect candidate.

I think you should be allowed to rename or set a name after init though, so I don't think we can/should check it during join?

I was just thinking it would be nice in exported metrics, and monitoring / license / mgmt emails we send, etc, but not something that changed behavior.

**Comment by mberhault** [comment]
Yeah, I'm actually thinking something much more strict. For the `<name, clusterid>` pair, and checked certificate fields, you definitely would never want to change those, it would be a massive hassle.
You could change it for metrics but even then that's a pretty terrible idea as it'll break your history.

**Comment by dt** [comment]
I guess I'm not sure what that gets over cluster ID alone -- since that is where we'll eat uniqueness and can't change.

WRT to rename breaking metrics history, I think I'm okay with leaving that to the operator to decide (plus some metrics storage lets you rewrite), so I don't see that as something that prevents renaming, just a point of consideration to document?

**Comment by mberhault** [comment]
We don't have to enforce name matching, but I think it would be a nice safety feature on joins. If we do, renaming means you have to make sure all your restarting nodes now use the new name. Not too difficult, but a bit annoying.

Certs are even worse. Having some type of cluster identifier in there would be really useful, both from a reuse-of-CA point of view and to be able to tell what the cert is for just by looking at it (seeing a "cluster=foo" is pretty nice). Changing the name basically means your cluster is broken as soon as the switch occurs and until certs have been updated.

**Comment by knz** [comment]
Okay so:

1) let's *not* use this new cluster name in certificates - this new cluster name is about licensing, and if companies use this for licensing this is bound to carry the org name. If the org ever changes names (acquisitions etc) there will be a requirement that renames are possible without destroying data.
2) we can use the existing cluster ID for certificate and join check, as follows:
  - we can start by using the hex representation of the cluster ID for identification purposes (certs, join). This would already be a net improvement. 
  - if that is deemed to be poor UX, there are multiple algorithms that establish a bijection between numbers and word sequences, which are more readable and/or memorizable. I personally recommend the standard word lists from the [Diceware](https://en.wikipedia.org/wiki/Diceware) method, which have been internationalized (so we can offer a human representation of the cluster ID in different languages) This is incidentally the approach taken in PGP to vocalize key fingerprints (https://en.wikipedia.org/wiki/PGP_word_list)

**Comment by knz** [comment]
That previous comment of mine was my reaction to the discussion so far, I hadn't read the code yet.

After reading the code, I have some more radical feedback: I would rather we only have a single "org name" string for the purpose of licensing. I think the "cluster name" string is not necessary. Unless you can convince me otherwise?

I buy that a user also, independently, needs to annotate a cluster with metadata for the purpose of DB management. But then how can we say that just org and cluster name are sufficient? What about department? manager? project? DBA in charge? If the ability to annotate is what we are running after, then the correct approach is to equip the cluster with a `map[string]string` of metadata annotations that the user can customize via admin UI endpoints. This is important, but IMHO not in scope if you're currently working on licensing.

**Comment by knz** [comment]
(sorry bad button click)

**Comment by mberhault** [comment]
Ok, if this is about licensing, then I agree with your previous post: let's drop the cluster name entirely and have some more generic identifier that could be anything (we can give examples, eg: "MyCompany Inc. Production Cluster Foo"). This will only be related to licensing and be exposed only there on the admin UI, it is not meant to be a cluster identifier, either for humans or machines.

The cluster name discussion warrants its own thread, I've created #16784 for that.

**Comment by dt** [comment]
Only org name is checked in lic checks.

Cluster name was intended entirely for display (potentially when communicating *about* a lic expiring), in exported metrics, monitoring, etc.

We can drop cluster name from this change and I still have what I need for license work, but I'd prefer to keep it so we have a pretty, human readable name by which we can refer to a cluster.

**Comment by mberhault** [comment]
I get that, but if we're going to do cluster name now, I think we need to figure out exactly what it will be used for and add the constraints right away. eg: if we use it for join safety, it needs to be a per-node flag.

**Comment by dt** [comment]
I've removed `name` from this for now, since I don't need it right away, and we can revisit after discussion on #16784

**Review by knz — APPROVED** [review]
Thank you!

**Comment by knz** [comment]
(codacy suggests adding a comment)

**Comment by dt** [comment]
yep, just fixed that, thanks! also `make lint` caught the same thing in our existing CI, so not sure what value Codacy was providing there?

**Pull request merged**
