### PR TITLE
TEAMS: rename sql-experience to sql-sessions

### PR DESCRIPTION
**Pull request by rafiss**
Epic: None
Release note: None

### CODE REVIEW

**Comment by renatolabs** [comment]
The changes on `conn_test.go` seem unrelated.

**Comment by rafiss** [comment]
whoops that was from debugging https://github.com/cockroachdb/cockroach/pull/93538

**Review by renatolabs — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93607#-:-NJGJtZA-7Dmtksuh6eN:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @srosenberg)

**Comment by rafiss** [comment]
tftr!

bors r+

**Pull request merged**
