### PR TITLE
sql: RETURNING for DELETE and UPDATE

### PR DESCRIPTION
**Pull request by madelynnblue**
Refactor from INSERT to use some common code.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4339)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
LGreatTM

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339#-:-KAHb4c-NEBTE9pdrMYc:-848653345)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/parser/returning.go, line 24 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339#-KAHbXKQDc0lRtPf7RnO:-KAHbXKRjhcZuquJzsF2:-2013831066) ([raw file](https://github.com/cockroachdb/cockroach/blob/66719e3441e184c3d08c875e0ba405ccc83480e4/sql/parser/returning.go#L24)):*
`len(r) == 0` would be a more encompassing check

---

*[sql/parser/update.go, line 39 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339#-KAHbrASkojhqMlChvuQ:-KAHbrASkojhqMlChvuR:1274045329) ([raw file](https://github.com/cockroachdb/cockroach/blob/66719e3441e184c3d08c875e0ba405ccc83480e4/sql/parser/update.go#L39)):*
Too many `%s`s

---

*[sql/returning.go, line 21 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339#-KAH_5INokJkS34TS2nv:-KAH_5INokJkS34TS2nw:-555547830) ([raw file](https://github.com/cockroachdb/cockroach/blob/66719e3441e184c3d08c875e0ba405ccc83480e4/sql/returning.go#L21)):*
Can this function return the valuesNode instead of having it as an input/output parameter? We always pass an empty one.

The qvalMap seems pretty much opaque to the caller.. We could have a `ReturningData` struct that contains `qvalMap` and `result` and make InitReturning and PopulateReturing methods on that type. Minor difference though so feel free to ignore this suggestion.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339)*

**Comment by petermattis** [comment]
LGTM

---

Review status: 0 of 13 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[sql/parser/sql.y, line 336 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339#-KAI8Ovp6aoRcVAPhthE:-KAI8Ovp6aoRcVAPhthF:-1391824902) ([raw file](https://github.com/cockroachdb/cockroach/blob/66719e3441e184c3d08c875e0ba405ccc83480e4/sql/parser/sql.y#L336)):*
@nvanbenschoten I imagine these comments will rot if we don't check them. How hard do you think it would be to do something like what Tobias suggested and preprocess this file and rewrite the `%type` declarations and edit the semantic actions so that `yacc` can do its type checking? Feels like this could be done using some sed or awk elbow grease. Or perhaps there is a better tool for the job. 

More concretely, we could get rid of the comments and make this grammar contain the desired `%type` declarations (e.g. `%type <ReturningExprs>`) and then before running yacc on this file to generate `sql.go` we replace any of the types that are part of the union with `%type <union>`. And if we want `yacc` to do its type checking, we remove all of the `.val`and `.retExprs()`, etc accessors. 

---

*[sql/returning.go, line 21 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339#-KAH_5INokJkS34TS2nv:-KAI7rP9TjiyhKYAF4cw:1015624852) ([raw file](https://github.com/cockroachdb/cockroach/blob/66719e3441e184c3d08c875e0ba405ccc83480e4/sql/returning.go#L21)):*
Does this method need to be exported? I think you can `s/InitReturning/initReturning/g`. 

---

*[sql/returning.go, line 53 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339#-KAI7vC460EMbaUoTwC3:-KAI7vC5MxA7dg08KF1U:-1475356153) ([raw file](https://github.com/cockroachdb/cockroach/blob/66719e3441e184c3d08c875e0ba405ccc83480e4/sql/returning.go#L53)):*
Ditto about unexporting.

---

*[sql/testdata/update, line 175 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339#-KAI89JvrUvbj-wJqZdb:-KAI89JvrUvbj-wJqZdc:-373613419) ([raw file](https://github.com/cockroachdb/cockroach/blob/66719e3441e184c3d08c875e0ba405ccc83480e4/sql/testdata/update#L175)):*
I'd also test returning a value that isn't being updated. Can't see why that wouldn't work, but it would be good to verify.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339#-:-KAI9nxC4zUu-SiQN3zp:676834233)*

**Comment by mjibson** [comment]
Review status: 0 of 13 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[sql/parser/returning.go, line 24 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339#-KAHbXKQDc0lRtPf7RnO:-KAJHuLW1D1MuSKG6Jkn:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/66719e3441e184c3d08c875e0ba405ccc83480e4/sql/parser/returning.go#L24)):*
Done.

---

*[sql/parser/update.go, line 39 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339#-KAHbrASkojhqMlChvuQ:-KAJI8CBMTe2AyQyeGV7:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/66719e3441e184c3d08c875e0ba405ccc83480e4/sql/parser/update.go#L39)):*
Done.

---

*[sql/returning.go, line 21 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339#-KAH_5INokJkS34TS2nv:-KAJJBfcCDTzWUpZWJJf:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/66719e3441e184c3d08c875e0ba405ccc83480e4/sql/returning.go#L21)):*
Done.

---

*[sql/returning.go, line 53 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339#-KAI7vC460EMbaUoTwC3:-KAJIOPZjdNT-brkYDY9:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/66719e3441e184c3d08c875e0ba405ccc83480e4/sql/returning.go#L53)):*
Done.

---

*[sql/testdata/update, line 175 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339#-KAI89JvrUvbj-wJqZdb:-KAJJOZ4sOkjRzgY2CbU:-1973564418) ([raw file](https://github.com/cockroachdb/cockroach/blob/66719e3441e184c3d08c875e0ba405ccc83480e4/sql/testdata/update#L175)):*
This doesn't work (consistent with our INSERT test: https://github.com/cockroachdb/cockroach/blob/4a3586f0cd239de793ce7fb5cf579890024c81cd/sql/testdata/insert#L332). I'm inclined to leave it not working. It doesn't work because only the specified columns are in the target list: https://github.com/cockroachdb/cockroach/blob/4a3586f0cd239de793ce7fb5cf579890024c81cd/sql/update.go#L130

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339)*

**Comment by tamird** [comment]
Reviewed 6 of 13 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[sql/testdata/update, line 194 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339#-KAKP0B27NDoMIZAzse8:-KAKP0B3sHakxRSKigyJ:895250132) ([raw file](https://github.com/cockroachdb/cockroach/blob/932ebf38092388c1fc56ad5b06a0169058d0188e/sql/testdata/update#L194)):*
is this the right error message?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[sql/testdata/update, line 175 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339#-KAI89JvrUvbj-wJqZdb:-KAKT6MLU2cC7-YSSs9V:1162703895) ([raw file](https://github.com/cockroachdb/cockroach/blob/66719e3441e184c3d08c875e0ba405ccc83480e4/sql/testdata/update#L175)):*
Oh, that seems like a surprising limitation. Not being able to return `a` here feels like a bug. If it's not fixed in this PR, file an issue. 

---

*[sql/testdata/update, line 194 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339#-KAKP0B27NDoMIZAzse8:-KAKTMT5gqE9ywnAXoVq:-1531152042) ([raw file](https://github.com/cockroachdb/cockroach/blob/932ebf38092388c1fc56ad5b06a0169058d0188e/sql/testdata/update#L194)):*
You're assigning to `b` twice. That's not allowed. What else should the error message say?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[sql/testdata/update, line 175 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339#-KAI89JvrUvbj-wJqZdb:-KAKV9FCYDF3wwAPcoL_:1877411032) ([raw file](https://github.com/cockroachdb/cockroach/blob/66719e3441e184c3d08c875e0ba405ccc83480e4/sql/testdata/update#L175)):*
Seems to work in postgres.
```
test=# update table1 set column_b = '' returning column_a;
 column_a
----------
        1
(1 row)

UPDATE 1
```

---

*[sql/testdata/update, line 194 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339#-KAKP0B27NDoMIZAzse8:-KAKVBTzZ5qR5SL1mmEs:-497813318) ([raw file](https://github.com/cockroachdb/cockroach/blob/932ebf38092388c1fc56ad5b06a0169058d0188e/sql/testdata/update#L194)):*
I think you're seeing this comment anchored somewhere different than I do. I meant for it to be anchored on `statement error pq: qualified name """.a" not found`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[sql/testdata/update, line 194 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339#-KAKP0B27NDoMIZAzse8:-KAKdBCVGSkFWVbTPCKV:-489129069) ([raw file](https://github.com/cockroachdb/cockroach/blob/932ebf38092388c1fc56ad5b06a0169058d0188e/sql/testdata/update#L194)):*
Yep. Reviewable fail.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339)*

**Comment by RaduBerinde** [comment]
Reviewed 6 of 13 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/parser/sql.y, line 336 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339#-KAI8Ovp6aoRcVAPhthE:-KAMqBU8gE6nDQgH2sJe:1819875820) ([raw file](https://github.com/cockroachdb/cockroach/blob/66719e3441e184c3d08c875e0ba405ccc83480e4/sql/parser/sql.y#L336)):*
Yeah I think what Tobias suggested is the right thing to do. I just created #4364, which does a lot of what you suggested and should help clean this up quire a bit. Note that we actually don't even need to touch the `.val` and `.retExprs()` for the yacc type checker to work the first time, because it doesn't do type checking on the arbitrary Go code inside rules.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339)*

**Comment by mjibson** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/testdata/update, line 175 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339#-KAI89JvrUvbj-wJqZdb:-KAOb2w73o7t0u6SNyUf:212543140) ([raw file](https://github.com/cockroachdb/cockroach/blob/66719e3441e184c3d08c875e0ba405ccc83480e4/sql/testdata/update#L175)):*
Opened #4368 to track this.

---

*[sql/testdata/update, line 194 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339#-KAKP0B27NDoMIZAzse8:-KAOg1gtqMz7SigaRalb:-1835226655) ([raw file](https://github.com/cockroachdb/cockroach/blob/932ebf38092388c1fc56ad5b06a0169058d0188e/sql/testdata/update#L194)):*
Yes, this error message is currently the best we can do. It's not an easy fix if we wanted to change that.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339)*

**Comment by bdarnell** [comment]
Review status: 12 of 13 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[sql/returning.go, line 28 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339#-KARKnd15bAKGSwuAwqe:-KARKnd2HSp-a82bvpYZ:-2015283800) ([raw file](https://github.com/cockroachdb/cockroach/blob/374b51682c455d251153f621b3af77d21b84fa62/sql/returning.go#L28)):*
The `tableInfo.alias` field needs to be filled in to support qualified names in the `RETURNING` clause (see #4363)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[sql/testdata/update, line 194 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339#-KAKP0B27NDoMIZAzse8:-KARVAK3RUpTRBJv1SwP:-186725734) ([raw file](https://github.com/cockroachdb/cockroach/blob/932ebf38092388c1fc56ad5b06a0169058d0188e/sql/testdata/update#L194)):*
Let's file an issue. Fixing #4368 will fix this specific case, but we should have a better error message when the name is indeed not found.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339)*

**Comment by mjibson** [comment]
Review status: 5 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/returning.go, line 28 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339#-KARKnd15bAKGSwuAwqe:-KAfFg5LH4UBr7j4gCgJ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/374b51682c455d251153f621b3af77d21b84fa62/sql/returning.go#L28)):*
Done.

---

*[sql/testdata/update, line 194 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339#-KAKP0B27NDoMIZAzse8:-KAfFc4q49MZAOImA4TS:1235377285) ([raw file](https://github.com/cockroachdb/cockroach/blob/932ebf38092388c1fc56ad5b06a0169058d0188e/sql/testdata/update#L194)):*
This has been fixed instead with Ben's help.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339)*

**Comment by tamird** [comment]
Reviewed 8 of 8 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339)*

**Comment by RaduBerinde** [comment]
Hi Matt,
I noticed WalkStmt does not walk through the Returning expressions.. That means that visitors like FillArgs won't go through these expressions.

Was this an oversight or is it intentional? I'm asking because I'm rewriting most of that stuff and want to understand the correct behavior.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4339#-:-KAwWVAb4GwG7TNwZT9C:-1867910119)*

**Comment by mjibson** [comment]
That was an oversight. It should do that I think.

**Comment by RaduBerinde** [comment]
Cool, no worries, I will do that in my change. Can you think of a statement that would fail so I can add it as a test? I guess a prepared statement that has a placeholder inside the RETURNING part, `RETURNING x + _1` or something like that?

**Comment by mjibson** [comment]
Yes, I think that would do it. `insert into t values ($1) returning $1`. The first `$1` will have its type inferred during prepare, but then the second `$1` will not be replaced during execute which should trigger an error.

**Comment by RaduBerinde** [comment]
Hi Matt,

I am finally finishing up my change and want to add this test but I'm not
sure where.. I couldn't find a set of tests specific to prepared statements.

-Radu

**Comment by tamird** [comment]
@RaduBerinde they're in pgwire_test.go

**Comment by RaduBerinde** [comment]
@tamird thanks!

**Pull request merged**
