### PR TITLE
sql: track references for user defined types in expressions

### LINKED ISSUE #59019: sql: user defined type references in expressions are not tracked
**Describe the problem**

Cockroach tracks backreferences for user-defined types when they appear as the type for columns (or used in array or alias types). We do not, however, track them when they occur inside of expressions or view statements. For example:

Postgres:
```
postgres=# CREATE TYPE typ as ENUM ('a');
CREATE TYPE
postgres=# CREATE VIEW v AS (SELECT 'a'::typ < 'a'::typ);
CREATE VIEW
postgres=# SELECT * FROM v;
 ?column? 
----------
 f
(1 row)

postgres=# DROP TYPE typ CASCADE;
NOTICE:  drop cascades to view v
DROP TYPE
postgres=# SELECT * FROM v;
ERROR:  relation "v" does not exist
```

Cockroach:
```
demo@127.0.0.1:26257/db> CREATE TYPE typ AS ENUM('a');
CREATE TYPE
demo@127.0.0.1:26257/db> CREATE VIEW v AS (SELECT 'a'::typ < 'a'::typ);
CREATE VIEW
demo@127.0.0.1:26257/db> SELECT * FROM v;
  ?column?
------------
   false
(1 row)
demo@127.0.0.1:26257/db> DROP TYPE typ CASCADE;
ERROR: unimplemented: DROP TYPE CASCADE is not yet supported
SQLSTATE: 0A000
HINT: You have attempted to use a feature that is not yet implemented.
See: https://go.crdb.dev/issue-v/51480/v21.1
demo@127.0.0.1:26257/db> DROP TYPE typ RESTRICT;
DROP TYPE
demo@127.0.0.1:26257/db> SELECT * FROM v;
ERROR: type "sc.typ" does not exist
SQLSTATE: 42704
```

Relates to #51480.

### PR DESCRIPTION
**Pull request by the-ericwang35**
Fixes https://github.com/cockroachdb/cockroach/issues/59019.

Previously, we tracked references for user-defined types
when they appear as the type for columns (or used in array
or alias types). However, we did not track them when they
occur inside of expressions or view statements.
This patch addresses this by tracking user-defined types
inside of expressions and view statements.

This patch also changes the way we collect these type
references. Previously, we would collect other references 
(tables, views, sequences) during the construction of the 
view query's logical plan, and then collect type references
after the construction. This PR changes this to collect 
the type references during construction as well.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
@rytaft can you look at the optbuilder changes or assign a victim? 

@the-ericwang35 sorry I didn't submit this sooner, missed some error because I had a pending comment on GitHub

> Reviewed 22 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62096#-:-MW2h-Mf49p4ViTVN6PW:bqngk7k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @the-ericwang35)

___
*[pkg/sql/create_view.go, line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62096#-MW2hrwB6bs8wh_cFpjO:-MW2hrwB6bs8wh_cFpjP:b9f8xpf) ([raw file](https://github.com/cockroachdb/cockroach/blob/503b07051f5c7f0f16721fc33f6b1a00a8d6c6bd/pkg/sql/create_view.go#L271)):*
> ```Go
> 
> 	for id := range n.typeDeps {
> 		// In case that we are replacing a view that already depends on
> ```

Can you help me understand this logic better? What does already mean? How do we know the set of type deps did not change? Why would you just add and remove the same dep?
___
*[pkg/sql/drop_view.go, line 230 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62096#-MW2i42r3uYPUpIsDL-w:-MW2i42r3uYPUpIsDL-x:b733kue) ([raw file](https://github.com/cockroachdb/cockroach/blob/503b07051f5c7f0f16721fc33f6b1a00a8d6c6bd/pkg/sql/drop_view.go#L230)):*
> ```Go
> 		}
> 		backRefJobDesc := fmt.Sprintf("updating type back reference %d for table %d", typeID, viewDesc.ID)
> 		if err := p.removeTypeBackReference(ctx, typeID, viewDesc.ID, backRefJobDesc); err != nil {
> ```

can we batch this? Like, can we make the API take a set of type IDs to go update?

**Review by the-ericwang35 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62096)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/create_view.go, line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62096#-MW2hrwB6bs8wh_cFpjO:-MWPvKcoADSn4pZS4caA:bv417ry) ([raw file](https://github.com/cockroachdb/cockroach/blob/503b07051f5c7f0f16721fc33f6b1a00a8d6c6bd/pkg/sql/create_view.go#L271)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Can you help me understand this logic better? What does already mean? How do we know the set of type deps did not change? Why would you just add and remove the same dep?
</blockquote></details>

Sorry this was bad copy pasta and re-reading it, it makes no sense. I've removed the line that removes the type dep since it makes no sense here, as further down the line, `AddReferencingDescriptorID` already checks for duplicate dependencies. 
___
*[pkg/sql/drop_view.go, line 230 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62096#-MW2i42r3uYPUpIsDL-w:-MWQ0CM27ZuORTGK737G:b-yyvn0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/503b07051f5c7f0f16721fc33f6b1a00a8d6c6bd/pkg/sql/drop_view.go#L230)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

can we batch this? Like, can we make the API take a set of type IDs to go update? 
</blockquote></details>

Yep, changed `removeTypeBackReference` to take in a slice of IDs.

**Review by rytaft — COMMENTED** [review]
optbuilder stuff :lgtm:

> Reviewed 14 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62096#-:-MWQkHVxErIQ-jKQBNSO:b8l4wff)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @the-ericwang35)

___
*[pkg/sql/opt/view_dependencies.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62096#-MWQfwI6AqPwe6JcEdb1:-MWQfwI6AqPwe6JcEdb2:byke3pz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2271b45a887228bdaef6b66427851b704f744bf5/pkg/sql/opt/view_dependencies.go#L47)):*
> ```Go
> // ViewTypeDeps contains a set of the IDs of types that
> // this view depends on.
> type ViewTypeDeps map[descpb.ID]struct{}
> ```

I think making this a `FastIntSet` would be a better choice to reduce allocations.
___
*[pkg/sql/opt/optbuilder/builder.go, line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62096#-MWQh25x4h1LJnjwGetg:-MWQh25y3UT1hcDPFVkE:b-ovd39l) ([raw file](https://github.com/cockroachdb/cockroach/blob/2271b45a887228bdaef6b66427851b704f744bf5/pkg/sql/opt/optbuilder/builder.go#L152)):*
> ```Go
> 		evalCtx:      evalCtx,
> 		catalog:      catalog,
> 		viewTypeDeps: make(map[descpb.ID]struct{}),
> ```

it would be better not to allocate the map unless `b.trackViewDeps` is true (or you could just use a `FastIntSet` and not need to worry)

**Review by the-ericwang35 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62096)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @rytaft)

___
*[pkg/sql/opt/view_dependencies.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62096#-MWQfwI6AqPwe6JcEdb1:-MWR-OJg4MdkbJAWc_9e:b8twu5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/2271b45a887228bdaef6b66427851b704f744bf5/pkg/sql/opt/view_dependencies.go#L47)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think making this a `FastIntSet` would be a better choice to reduce allocations.
</blockquote></details>

Done, I didn't know `FastIntSet` was a thing. TIL, thanks!
___
*[pkg/sql/opt/optbuilder/builder.go, line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62096#-MWQh25x4h1LJnjwGetg:-MWR-V9h-fr8UVyJua8l:b1lnjwe) ([raw file](https://github.com/cockroachdb/cockroach/blob/2271b45a887228bdaef6b66427851b704f744bf5/pkg/sql/opt/optbuilder/builder.go#L152)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

it would be better not to allocate the map unless `b.trackViewDeps` is true (or you could just use a `FastIntSet` and not need to worry)
</blockquote></details>

Yep, changed to use `FastIntSet`.

**Review by rytaft — COMMENTED** [review]
> Reviewed 5 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62096)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @the-ericwang35)

___
*[pkg/sql/opt/view_dependencies.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62096#-MWQfwI6AqPwe6JcEdb1:-MWR31Br7CrqKz_woN9C:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2271b45a887228bdaef6b66427851b704f744bf5/pkg/sql/opt/view_dependencies.go#L47)):*
<details><summary><i>Previously, the-ericwang35 (Eric Wang) wrote…</i></summary><blockquote>

Done, I didn't know `FastIntSet` was a thing. TIL, thanks!
</blockquote></details>

:thumbsup: 
___
*[pkg/sql/opt/memo/interner.go, line 576 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62096#-MWR4rZF6vVpp10EkLNi:-MWR4rZG2ofm5hTTvrud:b-iv2f8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c1f62c6a045b0a579843e2141a43e38590cbfb9/pkg/sql/opt/memo/interner.go#L576)):*
> ```Go
> 	hash := h.hash
> 	val.ForEach(func(i int) {
> 		hash ^= internHash(int64(i))
> ```

I think you can get rid of this int64 cast now
___
*[pkg/sql/opt/memo/interner.go, line 995 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62096#-MWR5-KE3iZEG9UpMptf:-MWR5-KFExsDmITJaEG_:bws8j0j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c1f62c6a045b0a579843e2141a43e38590cbfb9/pkg/sql/opt/memo/interner.go#L995)):*
> ```Go
> 		}
> 	})
> 	return isEqual
> ```

can't you just do `return l.Equals(r)`?
___
*[pkg/sql/opt/optbuilder/create_view.go, line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62096#-MWR4Ehi31c1H3Wq-st4:-MWR4Ehj1O6y_mN1bgNv:b6yqukb) ([raw file](https://github.com/cockroachdb/cockroach/blob/2271b45a887228bdaef6b66427851b704f744bf5/pkg/sql/opt/optbuilder/create_view.go#L38)):*
> ```Go
> 		b.trackViewDeps = false
> 		b.viewDeps = nil
> 		b.viewTypeDeps = nil
> ```

should you set `b.viewTypeDeps` to `FastIntSet{}` here?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62096)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @the-ericwang35)

___
*[pkg/sql/create_view.go, line 368 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62096#-MWRv7MJC7wdLXDgdLtq:-MWRv7MJC7wdLXDgdLtr:b-1w76yx) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c1f62c6a045b0a579843e2141a43e38590cbfb9/pkg/sql/create_view.go#L368)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> // replaceViewDesc modifies and returns the input view descriptor changed
> // to hold the new view represented by n. Note that back references from
> // tables that the new view depends on still need to be added. This function
> // will additionally drop backreferences from tables the old view depended
> // on that the new view no longer depends on.
> func (p *planner) replaceViewDesc(
> ```
</details>

Do you need to do something down here? Can you add tests for replacing views with `CREATE OR REPLACE VIEW`?

**Review by the-ericwang35 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62096)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @rytaft)

___
*[pkg/sql/create_view.go, line 368 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62096#-MWRv7MJC7wdLXDgdLtq:-MWRyhjP6p0EDHJuOo_K:bxuenb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c1f62c6a045b0a579843e2141a43e38590cbfb9/pkg/sql/create_view.go#L368)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> // replaceViewDesc modifies and returns the input view descriptor changed
> // to hold the new view represented by n. Note that back references from
> // tables that the new view depends on still need to be added. This function
> // will additionally drop backreferences from tables the old view depended
> // on that the new view no longer depends on.
> func (p *planner) replaceViewDesc(
> ```
Do you need to do something down here? Can you add tests for replacing views with `CREATE OR REPLACE VIEW`?
</blockquote></details>

Yes, good catch. I thought I already added the logic there but I must've been thinking of the previous views/sequences PR. Added in logic for this, and added some tests with `CREATE OR REPLACE VIEW`.
___
*[pkg/sql/opt/memo/interner.go, line 576 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62096#-MWR4rZF6vVpp10EkLNi:-MWRyBLh6qit4Cx9wEGS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c1f62c6a045b0a579843e2141a43e38590cbfb9/pkg/sql/opt/memo/interner.go#L576)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think you can get rid of this int64 cast now
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/interner.go, line 995 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62096#-MWR5-KE3iZEG9UpMptf:-MWRyNy17Y4f0mDKAGdb:bmekbff) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c1f62c6a045b0a579843e2141a43e38590cbfb9/pkg/sql/opt/memo/interner.go#L995)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

can't you just do `return l.Equals(r)`?
</blockquote></details>

Yes :facepalm: done.
___
*[pkg/sql/opt/optbuilder/create_view.go, line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62096#-MWR4Ehi31c1H3Wq-st4:-MWRy_D98Y-yU-5YMk20:b-f06h8g) ([raw file](https://github.com/cockroachdb/cockroach/blob/2271b45a887228bdaef6b66427851b704f744bf5/pkg/sql/opt/optbuilder/create_view.go#L38)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

should you set `b.viewTypeDeps` to `FastIntSet{}` here?
</blockquote></details>

Yes, good catch.

**Review by ajwerner — COMMENTED** [review]
> Reviewed 1 of 12 files at r2, 3 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62096)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @rytaft, and @the-ericwang35)

___
*[pkg/sql/create_view.go, line 500 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/62096#-MWVEhOY9JXlDffjQS4N:-MWVEhOY9JXlDffjQS4O:bvy1g1f) ([raw file](https://github.com/cockroachdb/cockroach/blob/0087c16e180e98471a95e339623468b7b6d9bf18/pkg/sql/create_view.go#L500)):*
> ```Go
> 	// Remove the back reference from all tables that the view depended on.
> 	for _, id := range toReplace.DependsOn {
> 		fmt.Printf("ID: %v\n", id)
> ```

detritus 
___
*[pkg/sql/logictest/testdata/logic_test/views, line 941 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/62096#-MWW2fG46v_oDCjsXAjQ:-MWW2fG46v_oDCjsXAjR:bfudto7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0087c16e180e98471a95e339623468b7b6d9bf18/pkg/sql/logictest/testdata/logic_test/views#L941)):*
> ```
> db2  public  vm    db1     public  rv          view references table
> ```

Can you add some tests involving the `_<typ>` array aliases and rename tracking? I'm not really clear on what we're doing there.

**Review by rytaft — APPROVED** [review]
opt stuff LGTM

> Reviewed 5 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62096#-:-MWW8NlCEkSnoBzv9u_M:bl4wfqq)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @the-ericwang35)

**Review by the-ericwang35 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62096)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @rytaft)

___
*[pkg/sql/create_view.go, line 500 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/62096#-MWVEhOY9JXlDffjQS4N:-MWWSIGk5zHbfK5Y9qEA:b-rpahry) ([raw file](https://github.com/cockroachdb/cockroach/blob/0087c16e180e98471a95e339623468b7b6d9bf18/pkg/sql/create_view.go#L500)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

detritus 
</blockquote></details>

:grimacing: 
___
*[pkg/sql/logictest/testdata/logic_test/views, line 941 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/62096#-MWW2fG46v_oDCjsXAjQ:-MWWSqSG0IdGWJXGHMxG:b-gnktku) ([raw file](https://github.com/cockroachdb/cockroach/blob/0087c16e180e98471a95e339623468b7b6d9bf18/pkg/sql/logictest/testdata/logic_test/views#L941)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Can you add some tests involving the `_<typ>` array aliases and rename tracking? I'm not really clear on what we're doing there. 
</blockquote></details>

Regarding the array alias, I've added a call to `typedesc.GetTypeDescriptorClosure()` during the part where we get the type dependency IDs in `maybeTrackUserDefinedTypeDepsForViews` to track these array alias types as well. This results in a new row in the `crdb_internal.cross_db_references` query above, which shows this dependency is tracked. Are there any other tests that you'd like me to add regarding this?

As for renaming types, it seems like right now renaming a type just corrupts the table (this is the same behaviour as on master), presumably my next task of storing types by ID will address this issue. But, the dependency still stays with the new type name (which makes sense these dependencies are just IDs). This behaviour is the same whether it's used as an expression or if it's the actual type of the column (see below). I've added a test to show this now. 

```
CREATE TYPE typ AS ENUM('a');
CREATE VIEW v AS SELECT 'a'::typ; # Same behaviour if 'a'::typ::string
ALTER TYPE typ RENAME TO typ2;
SELECT * FROM v; # ERROR: type "public.typ" does not exist
DROP TYPE typ2; # ERROR: cannot drop type "typ2" because other objects ([movr.public.v]) still depend on it
```

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62096#-:-MWZFghB6tVo9OTZ3owz:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @the-ericwang35)

___
*[pkg/sql/alter_table_locality.go, line 639 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/62096#-MWZEG4G0pbAXDCerY1Y:-MWZEG4H9eBDjZc9w6Ek:b-llkswg) ([raw file](https://github.com/cockroachdb/cockroach/blob/91c2f29b57876175892284acdf47ab2dd5adfa47/pkg/sql/alter_table_locality.go#L639)):*
> ```Go
> ) error {
> 	if tableDesc.GetMultiRegionEnumDependencyIfExists() {
> 		typesDependedOn := append([]descpb.ID(nil), regionEnumID)
> ```

nit: `[]descpb.ID{regionEnumID}`
___
*[pkg/sql/catalog/descpb/structured.proto, line 961 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/62096#-MWZF2QZ8LLW09khG9MJ:-MWZF2QZ8LLW09khG9MK:bax76hw) ([raw file](https://github.com/cockroachdb/cockroach/blob/91c2f29b57876175892284acdf47ab2dd5adfa47/pkg/sql/catalog/descpb/structured.proto#L961)):*
> ```protobuf
>   // The IDs of all types that this depends on.
>   // Only ever populated if this descriptor is for a view.
>   repeated uint32 dependsOnTypes = 45 [(gogoproto.customname) = "DependsOnTypes",
> ```

I'm wondering if we should think towards default and computed exprs. We're going to want to track type usage for those too. What is that going to look like? I suspect what it is going to look like is a method on the table descriptor that goes and explores its exprs. This isn't an actionable comment, just something for you to keep in mind.

**Review by the-ericwang35 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62096)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner)

___
*[pkg/sql/alter_table_locality.go, line 639 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/62096#-MWZEG4G0pbAXDCerY1Y:-MWZfioX8Bg3MVCb7XzB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/91c2f29b57876175892284acdf47ab2dd5adfa47/pkg/sql/alter_table_locality.go#L639)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: `[]descpb.ID{regionEnumID}`
</blockquote></details>

Done.
___
*[pkg/sql/catalog/descpb/structured.proto, line 961 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/62096#-MWZF2QZ8LLW09khG9MJ:-MW_-T6_1fVmeJjxw_MI:b-6yvrc9) ([raw file](https://github.com/cockroachdb/cockroach/blob/91c2f29b57876175892284acdf47ab2dd5adfa47/pkg/sql/catalog/descpb/structured.proto#L961)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I'm wondering if we should think towards default and computed exprs. We're going to want to track type usage for those too. What is that going to look like? I suspect what it is going to look like is a method on the table descriptor that goes and explores its exprs. This isn't an actionable comment, just something for you to keep in mind. 
</blockquote></details>

There's already a method on the table descriptor called `GetAllReferencedTypeIDs` that explores its exprs and looks for types, is this sort of what you had in mind? Now that I think about it, I missed adding the newly captured type dependencies in this method, so I've added code to do that now.

**Comment by the-ericwang35** [comment]
TFTRs! 

bors r=ajwerner,rytaft

**Pull request merged**
