### PR TITLE
schema: add insert/update/delete DML injection test

### LINKED ISSUE #108181: Schema: Add support for UPDATES/DELETEs and non empty tables within schema DML injection tests
Extend DML injection for the declarative schema changer to do the following

- Add UPDATES/DELETE into existing tests (constraints, ADD/DROP column, CREATE/DROP index)
- Start using non-empty tables for end-to-end testing for some tests

Testing was written in https://github.com/cockroachdb/cockroach/pull/98692 but this never got merged.

The bug came up in this support case: https://github.com/cockroachlabs/support/issues/2457. The above testing would have prevented the escalation.

Jira issue: CRDB-30351

Epic CRDB-30350

### PR DESCRIPTION
**Pull request by ecwall**
Fixes #108181

Adds a new test that runs insert/update/delete statements during
every phase and stage of a schema change and verifies that correct
DML changes can be seen externally.

Each subtest creates a table, runs optional setup DDL, then runs a schema
change. Before the schema change a single record is inserted so that the
table is not empty. During each schema change stage, the expected state of
the table is verified and records are inserted/updated/deleted as follows:
- insert an immutable operation="n/a" row that later stages will never modify
- insert an operation="delete" row for each later stage - each later stage
  will delete these rows that previous stages inserted for it
- insert an operation="update" row for each later stage - each later stage
  will update these rows that previous stages inserted for it

A new test is added instead of changing existing tests to avoid needing to
manually specify the expected output and DML injection at each stage as it
is determined programatically.

Release note: None

### CODE REVIEW

**Comment by rafiss** [comment]
Could you say more why we needed a new test instead of injecting the DML in the existing tests (e.g. like in #110216 or #98692)

**Comment by ecwall** [comment]
> Fixes #108181
> 
> Adds a new test that runs insert/update/delete statements during every phase and stage of a schema change and verifies that correct DML changes can be seen externally.
> 
> Release note: None



> Could you say more why we needed a new test instead of injecting the DML in the existing tests (e.g. like in #110216 or #98692)

Added.

**Review by rharding6373 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111623#-:-NfqNG1e6b_BjdNonMTg:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111623)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ecwall)

___
*[`pkg/sql/schemachanger/dml_injection_test.go` line 195 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111623#-NfvoQg65SU18OvalU7d:-NfvoQg65SU18OvalU7e:bw4a553) ([raw file](https://github.com/cockroachdb/cockroach/blob/8971520104198acbfcb615aad7829528d9a933f9/pkg/sql/schemachanger/dml_injection_test.go#L195)):*
> ```Go
> 		},
> 		{
> 			desc:         "add column stored",
> ```

can there also be a test for adding a virtual column?

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111623)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rafiss)

___
*[`pkg/sql/schemachanger/dml_injection_test.go` line 195 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111623#-NfvoQg65SU18OvalU7d:-Nfw0jbO8A2qHlfFYD2A:b-8b11j9) ([raw file](https://github.com/cockroachdb/cockroach/blob/8971520104198acbfcb615aad7829528d9a933f9/pkg/sql/schemachanger/dml_injection_test.go#L195)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

can there also be a test for adding a virtual column?
</blockquote></details>

Added

**Review by rafiss — APPROVED** [review]

**Pull request merged**
