### PR TITLE
sql: Parse (and ignore) "drop behavior" options

### PR DESCRIPTION
**Pull request by bdarnell**
These options are used by the Django ORM. These options apply to
features that we do not yet support (like foreign keys and views), so we
have nothing to do with them but to parse them.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5957)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5957#-:-KEsgwdGdN1F-zVL79u1:1417088721)*

**Comment by petermattis** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/parser/parse_test.go, line 106 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5957#-KEvzMwdCinCLFl34D-m:-KEvzMwdCinCLFl34D-n:70380504) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb16e5fa677bfa3ab7295c71e27f53e5563fd56/sql/parser/parse_test.go#L106)):*
Mind filing an issue to implement `CASCADE/RESTRICT` but note that it is dependent on `FOREIGN KEYs/VIEWs` being implement?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5957)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5957#-:-KEvzrvo2_WTjUdNkOLC:1417088721)*

**Comment by bdarnell** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/parser/parse_test.go, line 106 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5957#-KEvzMwdCinCLFl34D-m:-KFFhrgM-FQw9rdTBheI:-1737972546) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb16e5fa677bfa3ab7295c71e27f53e5563fd56/sql/parser/parse_test.go#L106)):*
Added comments to the issues tracking FK (#2968) and view (#2971) support.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5957)*

**Pull request merged**
