### PR TITLE
Show the current database name on sql prompt.

### PR DESCRIPTION
**Pull request by pmamatsis**
Changes have been done in /pkg/cli/sql.go in refreshPrompts function.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12660)

### CODE REVIEW

**Comment by andreimatei** [comment]
Thanks for the patch!

@knz is most familiar with this code, he should give the go ahead

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/cli/sql.go, line 403 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12660#-K__jzlZ8zhqoxoZdDWB:-K__jzlZ8zhqoxoZdDWC:btd2zwk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7faed6b9c3ed084a6d7410e11fde79bae05afa49/pkg/cli/sql.go#L403)):*
> ```Go
> 	query := makeQuery(`SHOW DATABASE`)
> 	rows, _ := query(c.conn)
> 	val := make([]driver.Value, len(rows.Columns()))
> ```

rename `val` to something more suggestive - `dbVals` - and declare it as `[1]driver.Value, assign `dbName := dbVals[0]` and assert that a) `len(rows.Columns) == 0` and b) `rows.Next()` returns `io.EOF` when called a second time.

---

*[pkg/cli/sql.go, line 408 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12660#-K__kJuYQQQUrLgKSqHP:-K__kJuYQQQUrLgKSqHQ:b-fkm6mz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7faed6b9c3ed084a6d7410e11fde79bae05afa49/pkg/cli/sql.go#L408)):*
> ```Go
> 	c.fullPrompt = c.promptPrefix + promptSuffix
> 	c.continuePrompt = strings.Repeat(" ", len(c.fullPrompt)-1) + "-> "
> 	c.fullPrompt += "/" + formatVal(val[0], false, false) + "> "
> ```

please comment inline the names of the `false` arguments .

---

*[pkg/cli/sql.go, line 408 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12660#-K__lQpZfaHeFEgfWA8m:-K__lQpZfaHeFEgfWA8n:b6lrmk6) ([raw file](https://github.com/cockroachdb/cockroach/blob/7faed6b9c3ed084a6d7410e11fde79bae05afa49/pkg/cli/sql.go#L408)):*
> ```Go
> 	c.fullPrompt = c.promptPrefix + promptSuffix
> 	c.continuePrompt = strings.Repeat(" ", len(c.fullPrompt)-1) + "-> "
> 	c.fullPrompt += "/" + formatVal(val[0], false, false) + "> "
> ```

how is the prompt going to look when there's no database selected?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12660#-:-K__lUTjOxQXnY3OmLwS:brdzse0)*

**Comment by pmamatsis** [comment]
Guys hang on...I am working as fast as i can !!! :)

**Comment by pmamatsis** [comment]
....."and declare it as [1]driver.Value"

In the above mentioned line the function call rows.Next() accepts a slice. If i declare it as [1]driver.Value then build fails...

**Comment by andreimatei** [comment]
> > ..."and declare it as [1]driver.Value"  
> In the above mentioned line the function call rows.Next() accepts a slice. If i declare it as [1]driver.Value then build fails...

I think you'd be able to pass `vals[:]`to `Next()`. I believe that syntax will convert the array to an equivalent slice.

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12660#-:-K_a5YDlq8mMitaLt3Hw:b-pztawj)*

**Comment by pmamatsis** [comment]
Hi @andreimatei yes you are correct...it was right in front of me....i really feel stupid now... :(

**Comment by knz** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/cli/sql.go, line 400 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12660#-K_aTNmrVPzcHJNlt9Ge:-K_aTNmsP4r8Zs4ijGbQ:bxsz0z5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f021c62c7ca4af3f56d9228b59d5c44d3c6e4a49/pkg/cli/sql.go#L400)):*
> ```Go
> }
> 
> func (c *cliState) refreshDatabaseName() string {
> ```

Ok sorry for coming late to the party.
I am not too happy about the asymmetry betweeen `refreshDatabaseName` and `refreshPrompts`.

If you look at the overall structure of the code in this file, you will notice that it follows a particular style: no matter what happens, a function doesn't return its value to its caller but instead "returns" by calling another function with its return value. This style is called "continuation passing" and creates confidence for the (experimented) reader that the overall state machine of the shell is running properly.

Now here the pattern is broken: `refreshPrompts()` calls `refreshDatabaseName()`, waits on its effects, then does something else. That's the asymmetry I mentioned.

To fix this do as follows:

1. make `refreshDatabaseName` take a `promptSuffix` and `nextState` as argument.
2. in `doRefreshPrompts`, replace all calls to `refreshPrompts` with a call to `refreshDatabaseName` with the proper arguments.
3. make `refreshPrompts` take another argument `dbName`
4. in `refreshDatabaseName` replace all the computations of `retVal` by a `return c.refreshPrompts(..., promptSuffix, nextState)`
5. also call `formatVal` inside `refreshDatabaseName` and pass the formatted string as argument to `refreshPrompts`.


(Note: if `libpq` supported returning multiple results sets per query, I would ask you to use a single query to retrieve both the database and transaction status and all this code should sit in a single function, say `doRefreshPrompts`. However since `libpq` doesn't know how to do this yet, I will not insist on that point here.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12660)*

**Comment by pmamatsis** [comment]
Hi @knz i just came back from the office. I will do the necessary changes and revert back with the updated version. First of all let me offer my apologies for this break in code...and also thank you so much for explaining in so detail to me about the "continuation passing" :+1:

**Comment by pmamatsis** [comment]
@knz is there anything else that i can do in order to merge this into the main branch? Shall i consider my job done on this one ?

Best regards,
Panos.

**Comment by knz** [comment]
Hi Panos, thanks for the late answer.
You've created a little mess in your branch right now but it's easy enough to fix.

1. remove the marge commit that simply must not be there: `git reset --hard 242d6e3f7776a35e4ebccd57d02edee18fd09232`
2. perform the necessary changes:
    1. make the changes suggested by my review comments below.
    2. (I assume that you've run `make test` already.)
    3. run `make acceptance`. Use the output of the failing test as input to fix the tests in `pkg/cli/interactive_tests` that need to be modified due to your patch.
    4. run `make check`. Then perform the changes required by `make check`, if any.
    5. commit the changes
3. flatten your history to a single commit:
    1. run `git reset 7faed6b9c3ed084a6d7410e11fde79bae05afa49` (*not* `--hard` this time!)
    2. run `git add` as needed, then `git commit --amend` to modify your first commit instead of adding new commits every time you change something.
4. rebase your tree off the most recent master branch:
    1. run `git checkout master; git pull`
    2. run `git checkout <yourbranch>; git rebase master`

---

Review status: 0 of 1 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[pkg/cli/sql.go, line 411 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12660#-K_n_QPjGHT9SHDkK6ad:-K_n_QPjGHT9SHDkK6ae:bntnzey) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ebfd1097c078e53e52165c74bd51dc3ae7ca13f/pkg/cli/sql.go#L411)):*
> ```Go
> 
> 	if err != nil {
> 		return c.refreshPrompts(promptSuffix, nextState)
> ```

add `fmt.Fprintf(osStderr, "error retrieving the database name: %v", err)` just before `return` here.

---

*[pkg/cli/sql.go, line 412 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12660#-K_n_bg4RmVz4S658LkE:-K_n_bg4RmVz4S658LkF:b24dwy7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ebfd1097c078e53e52165c74bd51dc3ae7ca13f/pkg/cli/sql.go#L412)):*
> ```Go
> 	if err != nil {
> 		return c.refreshPrompts(promptSuffix, nextState)
> 	} else {
> ```

Remove `else {` and the end `}` (`return` in the `if` branch guarantees the rest of the function runs only in the `else` case.

---

*[pkg/cli/sql.go, line 416 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12660#-K_n_m3aPLD6a0yL4IZm:-K_n_m3bthZP-oIeuwEV:b6tj5ha) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ebfd1097c078e53e52165c74bd51dc3ae7ca13f/pkg/cli/sql.go#L416)):*
> ```Go
> 			fmt.Fprintf(osStderr, "cannot get the database name")
> 			return c.refreshPrompts(promptSuffix, nextState)
> 		} else {
> ```

Same here: remove `else {` and the final `}`

---

*[pkg/cli/sql.go, line 419 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12660#-K_n_XHSERzSy7WcJbqE:-K_n_XHSERzSy7WcJbqF:bsenj1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ebfd1097c078e53e52165c74bd51dc3ae7ca13f/pkg/cli/sql.go#L419)):*
> ```Go
> 			err = rows.Next(dbVals[:])
> 			if err != nil {
> 				promptSuffix = ""
> ```

add `fmt.Fprintf(osStderr, "error retrieving the database name: %v", err)`  here.

---

*[pkg/cli/sql.go, line 419 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12660#-K_n_rn7rw-9_abJ4_Gx:-K_n_rn7rw-9_abJ4_Gy:bbt49q5) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ebfd1097c078e53e52165c74bd51dc3ae7ca13f/pkg/cli/sql.go#L419)):*
> ```Go
> 			err = rows.Next(dbVals[:])
> 			if err != nil {
> 				promptSuffix = ""
> ```

Replace `promptSuffix = ""` by `return c.refreshPrompts(promptSuffix, nextState)`

---

*[pkg/cli/sql.go, line 420 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12660#-K_n_oaYQ3yi5MOYZi_T:-K_n_oaZ2SIXKQ5bzr7j:bypvbt5) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ebfd1097c078e53e52165c74bd51dc3ae7ca13f/pkg/cli/sql.go#L420)):*
> ```Go
> 			if err != nil {
> 				promptSuffix = ""
> 			} else {
> ```

Again here same remove `else {` and final `}`

---

*[pkg/cli/sql.go, line 421 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12660#-K_na-CRq2_CKfl_lSOW:-K_na-CRq2_CKfl_lSOX:bw3ho34) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ebfd1097c078e53e52165c74bd51dc3ae7ca13f/pkg/cli/sql.go#L421)):*
> ```Go
> 				promptSuffix = ""
> 			} else {
> 				promptSuffix = "/" + formatVal(dbVals[0].(string) /* showPrintableUnicode */, false /*showNewLinesAndTabs */, false)
> ```

Replace `promptSuffix = ...` by:
```go
   dbName := formatVal(dbVals[0].(string), false /* showPrintableUnicode */, false /* shownewLinesAndTabs */)
   return c.refreshPrompts(promptSuffix + ":/" + dbName, nextState)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12660#-:-K_naWpP9cw01LjaK3_e:b-ft6svk)*

**Comment by knz** [comment]
You're currently making the situation worse. These commits:	9f4ca65  		50c4de6  	
	b32d91e  	
	0fcdeea must not be there.

**Comment by knz** [comment]
I suggest you spend some time reading about `git rebase` and `git reset` to really understand what's going on :)

**Comment by pmamatsis** [comment]
Hi @knz my apologies.

**Comment by knz** [comment]
Don't worry, we all have been there one day.

**Comment by knz** [comment]
Also remember if you're confused about the state of your tree, or if you think you "lost" a commit, you can always use `git reflog`.

**Comment by knz** [comment]
Superseded by #12747

**Pull request closed without merging**
