### PR TITLE
pgwire: return NoData instead of RowDescription when statement has no results

### LINKED ISSUE #4538: sql: JDBC not happy about results for DROP and CREATE
After applyting #4537, I run into the next error:

```
  actual: org.postgresql.util.PSQLException: A result was returned when none was expected.
 at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate (AbstractJdbc2Statement.java:417)
    clojure.java.jdbc$db_do_execute_prepared_statement$fn__7266.invoke (jdbc.clj:731)
    clojure.java.jdbc$db_transaction_STAR_.doInvoke (jdbc.clj:587)
    clojure.lang.RestFn.invoke (RestFn.java:425)
    clojure.java.jdbc$db_do_execute_prepared_statement.invoke (jdbc.clj:730)
    clojure.java.jdbc$db_do_prepared.doInvoke (jdbc.clj:764)
    clojure.lang.RestFn.invoke (RestFn.java:442)
    clojure.java.jdbc$execute_BANG_$execute_helper__7299.invoke (jdbc.clj:867)
    clojure.java.jdbc$execute_BANG_.doInvoke (jdbc.clj:869)
    clojure.lang.RestFn.invoke (RestFn.java:425)
    jepsen.cockroach$atomic_client$reify__7900.setup_BANG_ (cockroach.clj:281)
    jepsen.core$run_case_BANG_$fn__6884$fn__6885.invoke (core.clj:288)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.core$apply.invoke (core.clj:630)
    jepsen.core$fcatch$wrapper__6776.doInvoke (core.clj:55)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.core$pmap$fn__6744$fn__6745.invoke (core.clj:6729)
    clojure.core$binding_conveyor_fn$fn__4444.invoke (core.clj:1916)
    clojure.lang.AFn.call (AFn.java:18)
    java.util.concurrent.FutureTask.run (FutureTask.java:266)
    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
    java.lang.Thread.run (Thread.java:745)
```

This issue is occuring when JDBC sends "DROP TABLE IF NOT EXISTS TEST" to the db.

The network trace for the CockroachDB connection ( [test.cdb.txt](https://github.com/cockroachdb/cockroach/files/139249/test.cdb.txt) ) and a reference using PostgreSQL ( [test.pg.txt](https://github.com/cockroachdb/cockroach/files/139250/test.pg.txt) ) are attached.

### PR DESCRIPTION
**Pull request by knz**
Fixes #4538.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4548)

### CODE REVIEW

**Comment by knz** [comment]
Note that the proposed logic was taken from pg's code (tcpop/postgres.c, exec_describe_statement_message).

**Comment by tamird** [comment]
Can you add corresponding test coverage?

**Comment by knz** [comment]
@tamird: No, I can't :)
Literally, though. I don't know how. Care to point to an example code that looks at the pgwire packet format provided in responses? There is no way to test this with the SQL cli client.

**Comment by knz** [comment]
Also any suggestion as to what the CI check is complaining about?

**Comment by tamird** [comment]
Are you saying that there's no discernable difference in client behaviour before/after this change, and that it was discovered only by reading the PG sources? If that's the case, we need a comment indicating that, and a pointer to the upstream source location.

Usually, though, these changes result in client behaviour differences. In those cases, we've added tests in `sql/pgwire_test.go` using the Go driver to exercise that code path.

Looks to me like CI is complaining that you haven't run `go generate ./...` and committed the result.

**Comment by knz** [comment]
@tamird thanks for the suggestion to use `go generate`. 

Re the other thing. The problem is detected by the JDBC driver, and is not visible is neither lib/pq nor the command-line psql (nor our sql cli). The issue is that neither of the latter report a discernible difference between NoData and a RowDesc with 0 columns. In order to detect it you have to talk pgwire directly, or use JDBC.

I think the lack of test for this in the cockroach repo is not an issue since we are planning to run our Jepsen tests more or less regularly, and these will definitely exercise this code path.

**Comment by tamird** [comment]
Ah, I see. However, I disagree that it's OK to not have a test for this.

We have some infrastructure in the acceptance tests for running other languages' drivers. See if you can add this case to `acceptance/java_test.go`.

**Comment by knz** [comment]
Ok will do.

**Comment by knz** [comment]
Now I *have* run `go generate` and committed the results yet CI is not happy because of something in `ui/embedded.go`. What's going on? :sob:

**Comment by tamird** [comment]
`ui/embedded.go` seems to be generated incorrectly on your machine.

Try `git reset ui && git commit --amend && git push -f` - that should fix it, since no changes to the `ui` directory were made here.

**Comment by knz** [comment]
Tests implemented/committed separately as part of #4557.

**Comment by mjibson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/pgwire/v3.go, line 709 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4548#-KB9QEvj7SxO3V6k-Vny:-KB9QEvj7SxO3V6k-Vnz:-1255847612) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef713d9b499a54df47a8874a3bce2dc4d7dacc7/sql/pgwire/v3.go#L709)):*
How about `return` here, then there's no need to have the else block and extra indentation.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4548)*

**Comment by knz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/pgwire/v3.go, line 709 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4548#-KB9QEvj7SxO3V6k-Vny:-KB9Ssj88qTuqYS4tkfs:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef713d9b499a54df47a8874a3bce2dc4d7dacc7/sql/pgwire/v3.go#L709)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4548)*

**Comment by mjibson** [comment]
Code LGTM, but I'd prefer the test is committed with the fix.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4548#-:-KB9TeF82QQVpHQvBM0I:19450694)*

**Comment by knz** [comment]
Waiting for #4578 to merge the test from #4557.

**Comment by knz** [comment]
The commit currently sideloads #4578 until it gets merged. I will squash the sideload before merging this one.

**Comment by knz** [comment]
Ok the test was added in acceptance/java_test.go. @mjibson care to comment?

**Comment by knz** [comment]
Ok the tests work now! :relieved:

**Comment by tamird** [comment]
LGTM

---

Reviewed 1 of 2 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[acceptance/java_test.go, line 70 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4548#-KBDZfPrAPbDn9Q2nhbn:-KBDZfPrAPbDn9Q2nhbo:1726587524) ([raw file](https://github.com/cockroachdb/cockroach/blob/2233901147a4c11be570345da766c2b8075ad486/acceptance/java_test.go#L70)):*
why not log what you got here?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4548#-:-KBDZim-Ju-XogYqiLHK:676834233)*

**Comment by knz** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[acceptance/java_test.go, line 70 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4548#-KBDZfPrAPbDn9Q2nhbn:-KBD_ojsVOOgtZ_p8SQE:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/2233901147a4c11be570345da766c2b8075ad486/acceptance/java_test.go#L70)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4548)*

**Pull request merged**
