### PR TITLE
sql: support SHOW DEFAULT PRIVILEGES IN SCHEMA

### LINKED ISSUE #77256: sql: support show default privileges in schema and update crdb_internal.default_privileges with schema level default privileges
null

Jira issue: CRDB-13501
Epic CRDB-1521

### PR DESCRIPTION
**Pull request by RichardJCai**
fixes #77256

Release note (sql change): Add support for show default privileges
in schema.

The SHOW DEFAULT PRIVILEGES clause now supports optionally passing a
schema name.

SHOW DEFAULT PRIVILEGES [opt_for_role] [opt_schema_name]

Example:

```
SHOW DEFAULT PRIVILEGES IN SCHEMA s2
----
role      for_all_roles  object_type  grantee    privilege_type
testuser  false          tables       testuser2  DROP
testuser  false          tables       testuser2  SELECT
testuser  false          tables       testuser2  UPDATE

SHOW DEFAULT PRIVILEGES FOR ROLE testuser IN SCHEMA s2
----
role      for_all_roles  object_type  grantee    privilege_type
testuser  false          tables       testuser2  DROP
testuser  false          tables       testuser2  SELECT
testuser  false          tables       testuser2  UPDATE
```

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78959)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/sql/crdb_internal.go, line 4998 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78959#-MzS70AkCqJiN3GAUnBS:-MzS70AkCqJiN3GAUnBT:bx9m1t5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dd4d80aa814834129061463d15c7b0098b73162/pkg/sql/crdb_internal.go#L4998)):*
> ```Go
> 		return forEachDatabaseDesc(ctx, p, nil /* all databases */, true, /* requiresPrivileges */
> 			func(descriptor catalog.DatabaseDescriptor) error {
> 				addRowHelper := func(defaultPrivilegesForRole catpb.DefaultPrivilegesForRole, schema tree.Datum) error {
> ```

nit: should it be named `addRowsHelper`?
___
*[pkg/sql/crdb_internal.go, line 5032 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78959#-MzRwu4cDCSlj0MN-YtH:-MzRwu4cDCSlj0MN-YtI:bng7jkm) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dd4d80aa814834129061463d15c7b0098b73162/pkg/sql/crdb_internal.go#L5032)):*
> ```Go
> 							if catprivilege.GetRoleHasAllPrivilegesOnTargetObject(&defaultPrivilegesForRole, objectType) {
> 								if err := addRow(
> 									tree.NewDString(descriptor.GetName()),
> ```

could you add inline comments here and below to say what the column name is for each argument to `addRow`
___
*[pkg/sql/crdb_internal.go, line 5061 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78959#-MzS6xHo7umbrb0D4aYz:-MzS6xHo7umbrb0D4aZ-:bwomiua) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dd4d80aa814834129061463d15c7b0098b73162/pkg/sql/crdb_internal.go#L5061)):*
> ```Go
> 				}
> 
> 				addRowForRole := func(role catpb.DefaultPrivilegesRole, defaultPrivilegeDescriptor catalog.DefaultPrivilegeDescriptor, schema tree.Datum) error {
> ```

nit: should it be named `addRowsForRole`?
___
*[pkg/sql/crdb_internal.go, line 5092 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78959#-MzS6DKD0_h2Lkz9zNOB:-MzS6DKD0_h2Lkz9zNOC:b3w374g) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dd4d80aa814834129061463d15c7b0098b73162/pkg/sql/crdb_internal.go#L5092)):*
> ```Go
> 				}
> 
> 				if err := forEachSchema(ctx, p, descriptor, func(schema catalog.SchemaDescriptor) error {
> ```

i think this bit could be factored out, since it seems like the same logic is written twice (once with NULL schema, and again inside of forEachSchema)

maybe add a helper funciton named something like `addRowsForSchema`

```
				if err := forEachRole(ctx, p, func(username security.SQLUsername, isRole bool, options roleOptions, settings tree.Datum) error {
					role := catpb.DefaultPrivilegesRole{
						Role: username,
					}
					return addRowForRole(role, descriptor.GetDefaultPrivilegeDescriptor(), tree.DNull)
				}); err != nil {
					return err
				}

				// Handle ForAllRoles outside of forEachRole since it is a pseudo role.
				role := catpb.DefaultPrivilegesRole{
					ForAllRoles: true,
				}
				if err := addRowForRole(role, descriptor.GetDefaultPrivilegeDescriptor(), tree.DNull); err != nil {
					return err
				}

```
___
*[pkg/sql/delegate/show_default_privileges.go, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78959#-MzS1W-R8fr6Mox6nd7h:-MzS1W-T44ByAOOu81tn:b-42fosu) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dd4d80aa814834129061463d15c7b0098b73162/pkg/sql/delegate/show_default_privileges.go#L32)):*
> ```Go
> 	schemaClause := " AND schema_name IS NULL"
> 	if n.Schema != "" {
> 		schemaClause = fmt.Sprintf(" AND schema_name = '%s'", n.Schema.String())
> ```

pretty sure we use this pattern a lot, but just had a random question about it: is it resilient to SQL injection? (i.e. what happens if the user puts in single quotes in the schema name?)
___
*[pkg/sql/sem/tree/show.go, line 881 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78959#-MzS7_ne7VNePbaNlY0H:-MzS7_ne7VNePbaNlY0I:bl2fmr4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dd4d80aa814834129061463d15c7b0098b73162/pkg/sql/sem/tree/show.go#L881)):*
> ```Go
> 	Roles       RoleSpecList
> 	ForAllRoles bool
> 	// If Schema is not specified, ALTER DEFAULT PRIVILEGES is being
> ```

nit: comment should say `SHOW DEFAULT PRIVILEGES` i think
___
*[pkg/sql/sem/tree/show.go, line 904 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78959#-MzS2zAg0Zbq1uAxfxnj:-MzS2zAh14RFmHx6YPkC:bkk7jbg) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dd4d80aa814834129061463d15c7b0098b73162/pkg/sql/sem/tree/show.go#L904)):*
> ```Go
> 	}
> 	if n.Schema.String() != "" {
> 		ctx.WriteString("IN SCHEMA ")
> ```

could you add a test for this in pkg/sql/parser/testdata ?

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78959)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/crdb_internal.go, line 5032 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78959#-MzRwu4cDCSlj0MN-YtH:-MzVdcjx3zg6Pcj71RZp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dd4d80aa814834129061463d15c7b0098b73162/pkg/sql/crdb_internal.go#L5032)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could you add inline comments here and below to say what the column name is for each argument to `addRow`
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 5092 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78959#-MzS6DKD0_h2Lkz9zNOB:-MzVinRa1fRS666T2d2z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dd4d80aa814834129061463d15c7b0098b73162/pkg/sql/crdb_internal.go#L5092)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think this bit could be factored out, since it seems like the same logic is written twice (once with NULL schema, and again inside of forEachSchema)

maybe add a helper funciton named something like `addRowsForSchema`

```
				if err := forEachRole(ctx, p, func(username security.SQLUsername, isRole bool, options roleOptions, settings tree.Datum) error {
					role := catpb.DefaultPrivilegesRole{
						Role: username,
					}
					return addRowForRole(role, descriptor.GetDefaultPrivilegeDescriptor(), tree.DNull)
				}); err != nil {
					return err
				}

				// Handle ForAllRoles outside of forEachRole since it is a pseudo role.
				role := catpb.DefaultPrivilegesRole{
					ForAllRoles: true,
				}
				if err := addRowForRole(role, descriptor.GetDefaultPrivilegeDescriptor(), tree.DNull); err != nil {
					return err
				}

```
</blockquote></details>

Done.
___
*[pkg/sql/delegate/show_default_privileges.go, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78959#-MzS1W-R8fr6Mox6nd7h:-MzVmFuY9G8thEVTTbDO:b-us4esk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dd4d80aa814834129061463d15c7b0098b73162/pkg/sql/delegate/show_default_privileges.go#L32)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

pretty sure we use this pattern a lot, but just had a random question about it: is it resilient to SQL injection? (i.e. what happens if the user puts in single quotes in the schema name?)
</blockquote></details>

I don't think this is resilient to SQL injection. You can do some funny stuff but InternalExec only expects one statement

```
demo@127.0.0.1:26257/movr> show default privileges in schema "'; drop database test; SELECT '";
SELECT role, for_all_roles, object_type, grantee, privilege_type FROM crdb_internal.default_privileges WHERE database_name = 'movr' AND schema_name = '"'; drop database test; SELECT '"'
ERROR: internal error: expected 1 statement, but found 3
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/parser/parse.go:131: parseOneWithInt()
github.com/cockroachdb/cockroach/pkg/sql/parser/parse.go:264: ParseOneWithInt()
github.com/cockroachdb/cockroach/pkg/sql/parser/parse.go:257: ParseOne()
github.com/cockroachdb/cockroach/pkg/sql/delegate/delegate.go:197: parse()
github.com/cockroachdb/cockroach/pkg/sql/delegate/show_default_privileges.go:66: delegateShowDefaultPrivileges()
github.com/cockroachdb/cockroach/pkg/sql/delegate/delegate.go:166: TryDelegate()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:364: buildStmt()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:241: buildStmtAtRoot()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:215: Build()
github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:540: buildExecMemo()
github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:213: makeOptimizerPlan()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1319: makeExecPlan()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1013: dispatchToExecutionEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:684: execStmtInOpenState()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:143: execStmt()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1860: func1()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1864: execCmd()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1786: run()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:747: ServeConn()
github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:724: func1()
runtime/asm_amd64.s:1581: goexit()
```
___
*[pkg/sql/sem/tree/show.go, line 881 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78959#-MzS7_ne7VNePbaNlY0H:-MzVkylhD_9IxgtzkEb8:bhcptxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dd4d80aa814834129061463d15c7b0098b73162/pkg/sql/sem/tree/show.go#L881)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: comment should say `SHOW DEFAULT PRIVILEGES` i think
</blockquote></details>

Yeah, done
___
*[pkg/sql/sem/tree/show.go, line 904 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78959#-MzS2zAg0Zbq1uAxfxnj:-MzVm5zJ4GycwoYi55rZ:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dd4d80aa814834129061463d15c7b0098b73162/pkg/sql/sem/tree/show.go#L904)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could you add a test for this in pkg/sql/parser/testdata ?
</blockquote></details>

Done

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78959)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/sql/parser/testdata/show_default_privileges, line 4 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78959#-MzWCwhjANQ-OG8zsw-M:-MzWCwhjANQ-OG8zsw-N:blnhxrd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f197b5e1c8b6b8a8b421f914844300797e61000/pkg/sql/parser/testdata/show_default_privileges#L4)):*
> ```
> SHOW DEFAULT PRIVILEGES
> ----
> SHOW DEFAULT PRIVILEGES IN SCHEMA "" -- normalized!
> ```

hm, i'm a bit surprised. i thougth with the formatting change you made, we wouldn't show `IN SCHEMA` if the schema name is an empty string. is the condition supposed to be `if n.Schema != ""`?

not a big deal though

**Comment by RichardJCai** [comment]
TFTR!
bors r=rafiss

**Pull request merged**
