### PR TITLE
schemachanger: small fixes

### PR DESCRIPTION
**Pull request by postamar**
These are best reviewed commit-by-commit.

### CODE REVIEW

**Comment by postamar** [comment]
I'm still working on the plan validation. It's uncovered all kinds of bugs. Following that, I'll finish https://github.com/cockroachdb/cockroach/pull/73142

**Review by ajwerner — APPROVED** [review]
LGTM

**Comment by postamar** [comment]
Thanks for the review!

bors r+

**Comment by postamar** [comment]
bors cancel

**Comment by postamar** [comment]
bors cancel

ugh, linter error

**Comment by postamar** [comment]
bors r+

third time's the charm

**Pull request merged**
