### PR TITLE
execinfra: remove MetadataTest* processors

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit removes `MetadataTestSender` and `MetadataTestReceiver`
processors since they no longer provide much value. I believe they were
introduced when we added a `ProducerMetadata` as a return parameter to
`Next` method in order to ensure that at least some artificial metadata
is propagated correctly throughout the whole flow.

The main goal of this commit is the removal of `fakedist-metadata` and
`5node-metadata` logic test configs in order to speed up the CI time.

The justification for removal of these processors without putting anything
in their place is that these processors are not that useful - the only
thing they can test is that *some* metadata is propagated through the
row-based flows. Note that they don't test whether all necessary
metadata is emitted (for example, whether `LeafTxnFinalState`). We've
been using the vectorized engine as the default for a while now, and these
processors don't get planned with the vectorized flows. Thus, it seems
silly to have a logic test config like `fakedist-metadata` that is part
of the default configs.

Addresses: #57268.

Release note: None

### CODE REVIEW

**Comment by asubiotto** [comment]
What's the motivation for removing this now rather than waiting until we have the testing you mention in your comment?

**Comment by yuzefovich** [comment]
The motivation is that these processors are not that useful - the only thing they can test is that *some* metadata is propagated through the row-based flow, note that they don't test whether all necessary metadata is emitted (for example, whether `LeafTxnFinalState`). I think originally these processors were introduced to make sure that processors don't swallow the received metadata and, instead, propagate it further.

I believe having the testing framework I mentioned for the vectorized engine and having these processors are orthogonal issues since they would work in different scenarios, so the question is whether it is ok to remove these processors at all without introducing some other testing mechanism for the row-based flow and when it is ok to do so.

I think it is ok to remove these processors without putting anything in their place since they already don't provide much value, but it is not urgent to do so, so we can keep this PR in the backlog for now if you prefer.

**Comment by yuzefovich** [comment]
Ok, let's put it on the backlog for now.

**Comment by yuzefovich** [comment]
I revived this PR and would like to push it over the line. Previously, there was a pushback from Alfonso that we shouldn't remove testing infra without putting anything in place, but I'm arguing that the existing testing infra that is being removed here has essentially zero value:
```
The justification for removal of these processors without putting anything
in their place is that these processors are not that useful - the only
thing they can test is that some metadata is propagated through the
row-based flows. Note that they don't test whether all necessary
metadata is emitted (for example, whether LeafTxnFinalState). We've
been using the vectorized engine as the default for a while now, and these
processors don't get planned with the vectorized flows. Thus, it seems
silly to have a logic test config like fakedist-metadata that is part
of the default configs.
```

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57838#-:-N5jc05yE41zaT2kQBOk:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2)

**Pull request merged**
