### PR TITLE
storage: trigger GC based on SysCount/SysBytes

### PR DESCRIPTION
**Pull request by tbg**
If there is "a lot" of data in Sys{Bytes,Count}, then we are likely
experiencing a large abort span. The abort span is not supposed to
become that large, but it does happen and causes stability fallout,
usually due to a combination of shortcomings:

1. there's no trigger for GC based on abort span size alone (before
   this commit)
2. transaction aborts tended to create unnecessary abort span entries,
   fixed (and 19.2-backported) in:
   https://github.com/cockroachdb/cockroach/pull/42765
3. aborting transactions in a busy loop:
   https://github.com/cockroachdb/cockroach/issues/38088
   (and we suspect this also happens in user apps occasionally)
4. large snapshots would never complete due to the queue time limits
   (addressed in https://github.com/cockroachdb/cockroach/pull/44952).

In an ideal world, we would factor in the abort span into this method
directly, but until then the condition guarding this block will do.
At worst, there is some other reason for SysBytes become that large
while also incurring a large SysCount, but I'm not sure how this
would happen. The only other things in this span are the versioned
range descriptors (which follow regular GC and it's only ever adding
a SysCount of one), or transaction records (which expire like abort
span records).

Release note (bug fix): Range garbage collection will now trigger
based on a large abort span, adding defense-in-depth against ranges
growing large (and eventually unstable).

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
How do you feel about adding a check for the time since last GC? My specific concern is that we somehow dump megabytes of abort spans in some bug but then cannot GC them because they don't expire for an hour. I'd be okay with time since last GC just being that hour. 

Otherwise, :LGTM:

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45573#-:-M1QrvxF4MhXFXjDvGDY:blzojr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @tbg)

___
*[pkg/storage/gc_queue.go, line 343 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45573#-M1QsE831I0PVlkx-mOP:-M1QsE831I0PVlkx-mOQ:b-wv12kr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3dd7eeacc0ed81d5f150fe1f4b996ea14c4f36d/pkg/storage/gc_queue.go#L343)):*
> ```Go
> 	r.FinalScore = r.FuzzFactor * (valScore + r.IntentScore)
> 
> 	if probablyLargeAbortSpan(ms) {
> ```

nit: `if probablyLargeAbortSpan(ms) && !r.ShouldQueue {`?

**Comment by tbg** [comment]
Good idea, done. PTAL @ajwerner

**Review by ajwerner — APPROVED** [review]
:lgtm: mod the test failure

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45573#-:-M1_ZKmU3kbW6jPuYdF7:b-cb4vvs)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/storage/gc_queue_test.go, line 150 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45573#-M1_Z5V4C3AiHYXCK9KD:-M1_Z5V5Auq5ZC7rs4W9:b-agffcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bff2f5bebed5ba7b23101f00fee66bbcb9bcfda/pkg/storage/gc_queue_test.go#L150)):*
> ```Go
> 		r := makeGCQueueScoreImpl(
> 			context.Background(), seed,
> 			hlc.Timestamp{WallTime: thresh + 1},
> ```

I think this is off by 1. Either change your condition to be `>= r.LikelyLastGC > storagebase.TxnCleanupThreshold` or make this `+ 2`?

**Comment by tbg** [comment]
TFTR! I fixed the test (and cleaned it up while I was there).

bors r=ajwerner

**Pull request merged**
