### PR TITLE
builtins: implement parse_ident function

### LINKED ISSUE #93159: builtins: implement parse_ident function
https://www.postgresql.org/docs/current/functions-string.html

` parse_ident ( qualified_identifier text [, strict_mode boolean DEFAULT true ] ) → text[]`
Splits `qualified_identifier` into an array of identifiers, removing any quoting of individual identifiers. By default, extra characters after the last identifier are considered an error; but if the second parameter is `false`, then such extra characters are ignored. (This behavior is useful for parsing names for objects like functions.) Note that this function does not truncate over-length identifiers. If you want truncation you can cast the result to name[].

```
parse_ident('"SomeSchema".someTable') → {SomeSchema,sometable}
```

Jira issue: CRDB-22193

Epic CRDB-17785

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/93159

The implementation was adapted from the Postgres one.

Release note (sql change): Implemented the parse_ident builtin. The function splits a qualified identifier into an array of identifiers, removing any quoting of individual identifiers. By default, extra characters after the last identifier are considered an error; but if the second parameter is false, then such extra characters are ignored.

### CODE REVIEW

**Comment by ZhouXing19** [comment]
:lgtm_strong: ! I just have a small question about the test.

**Review by ZhouXing19 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93300)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/sem/builtins/parse_ident_builtin_test.go` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93300#-NJGTdIA2Gf2PfoWlbSh:-NJGTdIA2Gf2PfoWlbSi:b4mdqv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1847c6d18e52b0a017ee7397249ac3ed0915d9e1/pkg/sql/sem/builtins/parse_ident_builtin_test.go#L1)):*
> ```Go
> // Copyright 2022 The Cockroach Authors.
> ```

Just curious why not include these tests in the data-driven logic test as well.

**Review by rafiss — COMMENTED** [review]
tftr!

bors r=ZhouXing19

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93300#-:-NJGbgpNEJXxk4metcMg:bi9zvav)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ZhouXing19)

___
*[`pkg/sql/sem/builtins/parse_ident_builtin_test.go` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93300#-NJGTdIA2Gf2PfoWlbSh:-NJGbOQWDCF1IHkTg65T:b-ouzwgq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1847c6d18e52b0a017ee7397249ac3ed0915d9e1/pkg/sql/sem/builtins/parse_ident_builtin_test.go#L1)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Just curious why not include these tests in the data-driven logic test as well. 
</blockquote></details>

this is just a guess, but i don't think we really need to license any of our testing code. i think the `.go` test files just have them because our linter checks all `.go` files

**Comment by renatolabs** [comment]
```
[Run local roachtests] compilepkg: nogo: errors found by nogo during build-time code analysis:
[Run local roachtests] pkg/sql/sem/builtins/builtins.go:3176:32: github.com/cockroachdb/cockroach/pkg/sql/sem/tree.ParamType struct literal uses unkeyed fields (composites)
[Run local roachtests] pkg/sql/sem/builtins/builtins.go:3199:5: github.com/cockroachdb/cockroach/pkg/sql/sem/tree.ParamType struct literal uses unkeyed fields (composites)
[Run local roachtests] pkg/sql/sem/builtins/builtins.go:3200:5: github.com/cockroachdb/cockroach/pkg/sql/sem/tree.ParamType struct literal uses unkeyed fields (composites)
```

bors r-

**Comment by rafiss** [comment]
bors r=ZhouXing19

**Pull request merged**
