### PR TITLE
sql: fix dropping offline objects

### LINKED ISSUE #84137: schema: cascade interacting with offline tables
An `offline` table means nobody other than the job that moved it to or created it in the offline state is supposed to interact with it; doing so violates the assumptions that job makes about its exclusive interactions with that table, in particular safety of non-transactional and non-lease-holding interactions.

However currently it appears that `DROP ... CASCADE` is cascading to offline tables, violating this invariant.

To reproduce:
* Start a job that creates or moves a table into `OFFLINE`. (e.g. `RESTORE db.tbl`)
* While that job is running or paused, drop the database containing that table with cascade (`DROP DATABASE db CASCADE`).
* Observe that the job is still running but the table is now in DROP and its namespace entry has been removed.

Jira issue: CRDB-17485

### PR DESCRIPTION
**Pull request by postamar**
Fixes #84137.

I intend to base https://github.com/cockroachdb/cockroach/pull/83915 on this PR, backport the first two commits to 22.1, and backport only the first commit to 21.2.

### CODE REVIEW

**Review by fqazi — APPROVED** [review]
Looks good, a lot of the comments are superficial/nitty.

> Reviewed 4 of 4 files at r1, 4 of 4 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84189#-:-N6j7gON3-e-omYjoI1v:b-7iu61s)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @postamar)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go` line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84189#-N6j6cyC9lKsNiftmNV8:-N6j6cyC9lKsNiftmNV9:b22z6ej) ([raw file](https://github.com/cockroachdb/cockroach/blob/104c0fa2412c2c9213c0f3e7c1ebb27e674ca4ea/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go#L60)):*
> ```Go
> }
> 
> func undroppedElements(b BuildCtx, id catid.DescID) ElementResultSet {
> ```

Nit: Might be a bit cleaner to have a comment on this one its a shared helper function. Though we aren't good with that convention.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go` line 98 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84189#-N6j7EZSEraoytvZmeez:-N6j7EZSEraoytvZmef-:b-ewaqe3) ([raw file](https://github.com/cockroachdb/cockroach/blob/104c0fa2412c2c9213c0f3e7c1ebb27e674ca4ea/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go#L98)):*
> ```Go
> 	})
> 	if name == "" {
> 		return fmt.Sprintf("%s #%d", typ, id)
> ```

It feels like there should be something stricter, but I don't think there is a nice solution here. i.e. For any new element types that are missing logic in here.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go` line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84189#-N6j7RHS-WOuC-EMekvm:-N6j7RHS-WOuC-EMekvn:bc28hld) ([raw file](https://github.com/cockroachdb/cockroach/blob/104c0fa2412c2c9213c0f3e7c1ebb27e674ca4ea/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go#L117)):*
> ```Go
> // CASCADE.
> func dropCascadeDescriptor(b BuildCtx, id catid.DescID) {
> 	undropped := undroppedElements(b, id)
> ```

Nice, much cleaner than the old pattern!
___
*[`pkg/ccl/backupccl/backup_test.go` line 7851 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84189#-N6j5xNS5a60EV99Gi2E:-N6j5xNS5a60EV99Gi2F:b-jqs7kg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7e45aea9e23f94a9c3972b855bb83782f8d7eb4/pkg/ccl/backupccl/backup_test.go#L7851)):*
> ```Go
> 		{
> 			const re = `type .* is offline|relation .* is offline|cannot drop a database or a schema with OFFLINE`
> 			sqlDB.ExpectErr(t, re, `DROP TYPE newdb.sc.typ`)
> ```

Nit: Might be just cleaner to embed the individual for the first two, there is no real commonality except for the last one.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, 4 of 4 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84189#-:-N6j83TM7m9gYKyIUbqr:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @postamar)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go` line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84189#-N6j7_Bd2UZy20gemN0q:-N6j7_Bd2UZy20gemN0r:b-za66s0) ([raw file](https://github.com/cockroachdb/cockroach/blob/104c0fa2412c2c9213c0f3e7c1ebb27e674ca4ea/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go#L74)):*
> ```Go
> }
> 
> func errMsgPrefix(b BuildCtx, id catid.DescID) string {
> ```

Can you comment the intention of this function, it's not obvious
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go` line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84189#-N6j7VIC06oofxXQTMHz:-N6j7VID2qsDMmNH_FGo:b-b4mw0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/104c0fa2412c2c9213c0f3e7c1ebb27e674ca4ea/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go#L92)):*
> ```Go
> 			typ = "type"
> 		case *scpb.Namespace:
> 			if name == "" || target != scpb.ToPublic {
> ```

this `!= scpb.ToPublic` deserves commentary
___
*[`pkg/sql/importer/import_stmt_test.go` line 1231 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84189#-N6j7-AHDHIcP8mY9weY:-N6j7-AHDHIcP8mY9weZ:b8y638q) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7e45aea9e23f94a9c3972b855bb83782f8d7eb4/pkg/sql/importer/import_stmt_test.go#L1231)):*
> ```Go
> 				defer func() {
> 					_, _ = db.Exec(fmt.Sprintf("DROP DATABASE %s", dbName))
> 				}()
> ```

This change doesn't leave me feeling great. I understand why you're doing it: sometimes the drop is going to fail due to offline descriptors, but I have to assume that it was here for a reason. Perhaps some of it was to validate the state of the database. Maybe augment this test with a scan of `crdb_internal.invalid_objects`? 



_Code quote:_
```Go
				defer sqlDB.Exec(t, fmt.Sprintf(`DROP DATABASE %s`, dbName))
```

**Review by chengxiong-ruan — COMMENTED** [review]
thanks for fixing this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84189#-:-N6jDbZO800QisNsyeWW:b-d0pxcq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @postamar)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go` line 50 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84189#-N6jBhZR7sohLJp9TyK1:-N6jBhZR7sohLJp9TyK2:bvqw3uv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b19cd9981991badcffac0d4f40270bc464912c8/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go#L50)):*
> ```Go
> func dropRestrictDescriptor(b BuildCtx, id catid.DescID) (hasChanged bool) {
> 	undroppedElements(b, id).ForEachElementStatus(func(_ scpb.Status, target scpb.TargetStatus, e scpb.Element) {
> 		if target == scpb.ToAbsent || target == scpb.Transient {
> ```

nit, looks like we don't need this check since everything is from `undroppedElements`?
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go` line 62 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84189#-N6jD6Ie7jEMMHhubJXq:-N6jD6Ie7jEMMHhubJXr:b2ls25o) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b19cd9981991badcffac0d4f40270bc464912c8/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go#L62)):*
> ```Go
> func undroppedElements(b BuildCtx, id catid.DescID) ElementResultSet {
> 	return b.QueryByID(id).Filter(func(current scpb.Status, target scpb.TargetStatus, e scpb.Element) bool {
> 		if target == scpb.InvalidTarget {
> ```

could you add a comment that why `target ==scpb.InvalidTarget` indicate a non-public element?

**Comment by postamar** [comment]
Thanks for the reviews! I've addressed most comments. I added a bunch of commentary. Thank you all for suggesting it, it needed it, and I didn't notice from the tunnel vision of hammering this change through the tests all day.

I'll wait for a green CI light and bors.

**Pull request merged**
