### PR TITLE
catalog/lease: Improve reliability of TestLeaseRenewedAutomatically

### LINKED ISSUE #133030: sql/catalog/lease: TestLeaseRenewedAutomatically failed
sql/catalog/lease.TestLeaseRenewedAutomatically [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/17386684?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/17386684?buildTab=artifacts#/) on release-23.2.13-rc @ [f00c152761838e05049d293198840b12605b545b](https://github.com/cockroachdb/cockroach/commits/f00c152761838e05049d293198840b12605b545b):

```
=== RUN   TestLeaseRenewedAutomatically
    test_log_scope.go:170: test logs captured to: /artifacts/tmp/_tmp/ce8d73b4a4081f39d36a7fa2c2508fcc/logTestLeaseRenewedAutomatically85802723
    test_log_scope.go:81: use -show-logs to present logs inline
    test_server_shim.go:159: automatically injected an external process virtual cluster under test; see comment at top of test_server_shim.go for details.
    lease_test.go:1375: expected repeated lease acquisition to not block, but blockCount is: 1
    panic.go:523: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/ce8d73b4a4081f39d36a7fa2c2508fcc/logTestLeaseRenewedAutomatically85802723
--- FAIL: TestLeaseRenewedAutomatically (8.13s)
```

Parameters:
 - <code>TAGS=bazel,gss</code>
 - <code>stress=true</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLeaseRenewedAutomatically.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-43424

### PR DESCRIPTION
**Pull request by spilchen**
The TestLeaseRenewedAutomatically test is designed to verify that an expired lease is reacquired automatically. However, background processes acquiring leases caused occasional test flakiness. Efforts to limit this interference, such as disabling autostats, were only partially effective, as other background activity still sometimes caused issues. Rather than attempting to track every background process, I modified the test to focus lease checks exclusively on the two tables under test. This improved reliability in my local runs since it was the database descriptor lease, not the leases for the two tables, that was being acquired. This adjustment preserves the test’s intent while enhancing its stability.

Epic: none
Closes #133030
Release note: none

### CODE REVIEW

**Review by fqazi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134665)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/sql/catalog/lease/lease_test.go` line 1327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134665#-OBBDFby1yJhStpoOWNF:-OBBDFby1yJhStpoOWNG:b-e21hf4) ([raw file](https://github.com/cockroachdb/cockroach/blob/46251af4e2b6abc52bbe81164f68abc9a86adc13/pkg/sql/catalog/lease/lease_test.go#L1327)):*
> ```Go
> 				log.Infof(ctx,
> 					"Lease acquisition of ID %d resulted in a block event. Stack trace to follow:\n%s",
> 					id, buf[:n])
> ```

use debug.Stack()
___
*[`pkg/sql/catalog/lease/lease_test.go` line 1382 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134665#-OBBDQAR02BIOS-yFPC0:-OBBDQAR02BIOS-yFPC1:b-xdlq7o) ([raw file](https://github.com/cockroachdb/cockroach/blob/46251af4e2b6abc52bbe81164f68abc9a86adc13/pkg/sql/catalog/lease/lease_test.go#L1382)):*
> ```Go
> 	// Save off the IDs of the two tables so that we increment testAcquisitionBlockCount
> 	// if we ever block waiting for those leases to expire.
> 	atomic.StoreInt32(&test1ID, int32(test1Desc.GetID()))
> ```

Ah we counted everything before. I'm guessing this good under stress?

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134665)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @spilchen)

___
*[`pkg/sql/catalog/lease/lease_test.go` line 1327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134665#-OBBDFby1yJhStpoOWNF:-OBBFyLP1IVcn_lzNZrM:b-vjr6f0) ([raw file](https://github.com/cockroachdb/cockroach/blob/46251af4e2b6abc52bbe81164f68abc9a86adc13/pkg/sql/catalog/lease/lease_test.go#L1327)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

use debug.Stack()
</blockquote></details>

Cool. I wasn't aware of this function.
___
*[`pkg/sql/catalog/lease/lease_test.go` line 1382 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134665#-OBBDQAR02BIOS-yFPC0:-OBBG4sUBwnAoSw17o-8:b-q23x2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/46251af4e2b6abc52bbe81164f68abc9a86adc13/pkg/sql/catalog/lease/lease_test.go#L1382)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Ah we counted everything before. I'm guessing this good under stress?
</blockquote></details>

Yes, I’ve been running this test under continuous stress, which eventually reproduces the issue. When it does flake out, it’s always due to a lease on the database descriptor, occasionally acquired by other background threads. So, I'm simply omitting that descriptor and only checking for the lease on the tables.

**Review by fqazi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134665)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/sql/catalog/lease/lease_test.go` line 1324 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134665#-OBBHaj53MyrnwMFyLR0:-OBBHaj53MyrnwMFyLR1:bmg46la) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d991337e41a8809ed44db910260bcdfefcb2e9f/pkg/sql/catalog/lease/lease_test.go#L1324)):*
> ```Go
> 				log.Infof(ctx,
> 					"Lease acquisition of ID %d resulted in a block event. Stack trace to follow:\n%s",
> 					id, string(debug.Stack()))
> ```

You don't need the string cast, the %s is sufficient.

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134665)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @spilchen)

___
*[`pkg/sql/catalog/lease/lease_test.go` line 1324 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134665#-OBBHaj53MyrnwMFyLR0:-OBBJhrb6aQeHHvkuGAu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d991337e41a8809ed44db910260bcdfefcb2e9f/pkg/sql/catalog/lease/lease_test.go#L1324)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

You don't need the string cast, the %s is sufficient.
</blockquote></details>

Done.

**Comment by spilchen** [comment]
TFTR!

bors r+

**Pull request merged**
