### PR TITLE
storage: make RelocateRanges robust

### LINKED ISSUE #15646: distsql: flaky range relocation in test
From https://teamcity.cockroachdb.com/viewLog.html?buildId=240651&buildTypeId=Cockroach_UnitTests:

```
TestLogic/5node/distsql_agg 	
 	Already fixed in:	15612	#14725 	eisen (1) 	03 May 17 15:19
First failure:	15612	#14642 	eisen (1) 	02 May 17 19:32
 logic_test.go:1625: 
    testdata/logic_test/distsql_agg:353: expected success, but found
    pq: snapshot failed: (n1,s1):?: remote couldn't accept snapshot with error: [n1,s1],r21: cannot apply snapshot: snapshot intersects existing range [n1,s1,r10/1:/{Table/51/1/9-Max}]
logic_test.go:1635: 
    testdata/logic_test/distsql_agg:353: error in statement, skipping to next file
```

### LINKED ISSUE #16010: testdata/logic_test/distsql_agg:353: expected success, but found     pq: snapshot failed: (n1,s1)
https://teamcity.cockroachdb.com/viewLog.html?buildId=251631&buildTypeId=Cockroach_UnitTests_Test

```
logic_test.go:1625: 
    testdata/logic_test/distsql_agg:353: expected success, but found
    pq: snapshot failed: (n1,s1):?: remote couldn't accept snapshot with error: [n1,s1],r21: cannot apply snapshot: snapshot intersects existing range [n1,s1,r10/1:/{Table/51/1/9-Max}]
logic_test.go:1635: 
    testdata/logic_test/distsql_agg:353: error in statement, skipping to next file
```

### LINKED ISSUE #16400: teamcity: failed tests on master: test/TestLogic, test/TestLogic/5node, test/TestLogic/5node/distsql_agg, acceptance/TestAdminLossOfQuorum
The following tests appear to have failed:

[#266803](https://teamcity.cockroachdb.com/viewLog.html?buildId=266803):

```
--- FAIL: test/TestLogic (26.020s)
test_log_scope.go:80: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestLogic497036230
test_log_scope.go:63: use -show-logs to present logs inline
--- FAIL: test/TestLogic/5node (0.000s)
null
--- FAIL: test/TestLogic/5node/distsql_agg (3.180s)
logic_test.go:1718: 
	testdata/logic_test/distsql_agg:373: expected success, but found
	pq: snapshot failed: (n1,s1):?: remote couldn't accept snapshot with error: [n1,s1],r21: cannot apply snapshot: snapshot intersects existing range [n1,s1,r10/1:/{Table/51/1/9-Max}]
logic_test.go:1728: 
	testdata/logic_test/distsql_agg:373: error in statement, skipping to next file
--- FAIL: acceptance/TestAdminLossOfQuorum (10.130s)
test_log_scope.go:80: test logs captured to: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/logTestAdminLossOfQuorum369153985
test_log_scope.go:63: use -show-logs to present logs inline
admin_test.go:71: Get https://127.0.0.1:32967/_status/nodes: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
------- Stdout: -------
xenial-20170214: Pulling from library/ubuntu
Digest: sha256:dd7808d8792c9841d0b460122f1acf0a2dd1f56404f8d1e56298048885e45535
Status: Image is up to date for ubuntu:xenial-20170214
test logs left over in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/logTestAdminLossOfQuorum369153985

```
Please assign, take a look and update the issue accordingly.

### LINKED ISSUE #16729: teamcity: failed tests on master: test/TestLogic, test/TestLogic/5node, test/TestLogic/5node/distsql_agg
The following tests appear to have failed:

[#281518](https://teamcity.cockroachdb.com/viewLog.html?buildId=281518):

```
--- FAIL: test/TestLogic (47.280s)
test_log_scope.go:80: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestLogic260096466
test_log_scope.go:63: use -show-logs to present logs inline
--- FAIL: test/TestLogic/5node (0.000s)
null
--- FAIL: test/TestLogic/5node/distsql_agg (5.810s)
logic_test.go:1718: 
	testdata/logic_test/distsql_agg:373: expected success, but found
	pq: snapshot failed: (n1,s1):?: remote couldn't accept snapshot with error: [n1,s1],r21: cannot apply snapshot: snapshot intersects existing range [n1,s1,r10/1:/{Table/51/1/9-Max}]
logic_test.go:1728: 
	testdata/logic_test/distsql_agg:373: error in statement, skipping to next file

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by tbg**
... by retrying aggressively. I don't know how test-only this is, so I did not
go overboard. As is, it may retry forever on permanent errors (barring context
cancellation). Perhaps this is enough? Let the review decide.

Fixes #16729.
Fixes #15646.
Fixes #16010.
Fixes #16400.

### CODE REVIEW

**Comment by tschottdorf** [comment]
Ok, definitely seems that it is used by backup/restore and locks up the process because it runs into 

> [n1,s1,r12/3:/Table/51/{2-3}] while removing target n4,s4: [n3,s3,r12/2:/Table/51/{2-3}]: unable to remove replica (n4,s4):? which is not present

So we definitely need an authoritative whitelist.

**Comment by a-robinson** [comment]
We should mark this more explicitly as test only if we're going to add dangerous shenanigans like this, but would it work to just retry the `RelocateRange` call in the sql layer in the only place it's used? The backup/restore use of it in `Scatter` will soon be removed (#16249).

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16780#-:-KnlnGKsNPhA7p4C_7KX:bqiyw8p)*

**Comment by bdarnell** [comment]
If this is test-only code, then making the change here is appealing to avoid touching production, but aside from that I think this probably is not the right place to handle this error. I think it would be better to move the retry into ChangeReplicas or sendSnapshot. Or for the particular case of "snapshot intersects existing range", maybe we could synchronously attempt a replica GC in Store.canApplySnapshotLocked. (it would also be fine as a quick fix to make this change as-is with a whitelist of "snapshot intersects existing range")

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16780#-:-KnpAoyXxpnx4m0-Hmj3:b-6l8e4o)*

**Comment by tschottdorf** [comment]
@bdarnell I'm hesitant to make changes to production code as many callers don't need explicit retries (the various queues will just move on, and try again later, which I think is fine as is) and my main focus is fixing the flaky test.

@a-robinson: I'll take a look - afaict the only remaining caller (post scatter) is `*relocateNode` which I think is only used for `TESTING_RELOCATE`, ie test-ish code.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16780#-:-KnpEU1zkJDAxtjGnum5:b-2o8bn8)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 13 of 13 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/replica_command.go, line 3869 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16780#-KoJsUUrrRdNjDQZ-Pqk:-KoJsUUrrRdNjDQZ-Pql:b-q4hdr5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3844ffda5a48a30b13a98c46e35f640db5c7a1b7/pkg/storage/replica_command.go#L3869)):*
> ```Go
> 
> 	canRetry := func(err error) bool {
> 		// FIXME: retry only on whitelisted errors. Known examples: snapshot
> ```

Remove the `FIXME`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16780#-:-KoJsalx01EMWzt228Us:bnfp4nl)*

**Comment by RaduBerinde** [comment]
:lgtm:  (just squash the commits)

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/storage/replica_command.go, line 3887 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16780#-KoKCd70TVo5gPTeSYIT:-KoKCd70TVo5gPTeSYIU:b-jom8tv) ([raw file](https://github.com/cockroachdb/cockroach/blob/55b2459b39bca54294b2d0af6e228c94336f43ac/pkg/storage/replica_command.go#L3887)):*
> ```Go
> 	}
> 
> 	if err := ctx.Err(); err != nil {
> ```

[nit] can move this inside the loop and remove `&& ctx.Err() == nil`

---

*[pkg/storage/replica_command.go, line 3931 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16780#-KoKCkT-CoTtGKAM_zZ_:-KoKCkT-CoTtGKAM_zZa:blmhdto) ([raw file](https://github.com/cockroachdb/cockroach/blob/55b2459b39bca54294b2d0af6e228c94336f43ac/pkg/storage/replica_command.go#L3931)):*
> ```Go
> 			log.Warningf(ctx, "while removing target %v: %s", target, err)
> 			if !canRetry(err) {
> 				return err
> ```

[nit] perhaps log another Warning that mentions that we are retrying. Anything that would help speed up debugging if investigating a test timeout due to this loop.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16780#-:-KoKCuROf1GLnEKCVQEK:beofuao)*

**Comment by a-robinson** [comment]
:lgtm:

---

Reviewed 13 of 13 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16780#-:-KoKOlNwnLGB5Mz8MMzL:bnfp4nl)*

**Comment by tschottdorf** [comment]
Squashed. TFTRs!

---

Review status: 11 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/storage/replica_command.go, line 3887 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16780#-KoKCd70TVo5gPTeSYIT:-KoOi_HywQAyCLfKGSda:b-o70hmt) ([raw file](https://github.com/cockroachdb/cockroach/blob/55b2459b39bca54294b2d0af6e228c94336f43ac/pkg/storage/replica_command.go#L3887)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] can move this inside the loop and remove `&& ctx.Err() == nil`
</blockquote></details>

Good point, done (here and in the other place).

---

*[pkg/storage/replica_command.go, line 3931 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16780#-KoKCkT-CoTtGKAM_zZ_:-KoOisGwMnKaymube-OD:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/55b2459b39bca54294b2d0af6e228c94336f43ac/pkg/storage/replica_command.go#L3931)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] perhaps log another Warning that mentions that we are retrying. Anything that would help speed up debugging if investigating a test timeout due to this loop.
</blockquote></details>

Good point, done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16780#-:-KoOizLca0xGGlmV6hec:b6vh0z)*

**Comment by tschottdorf** [comment]
Review status: 11 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/storage/replica_command.go, line 3869 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16780#-KoJsUUrrRdNjDQZ-Pqk:-KoOj0LvWw3tSV30emig:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3844ffda5a48a30b13a98c46e35f640db5c7a1b7/pkg/storage/replica_command.go#L3869)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Remove the `FIXME`. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16780)*

**Pull request merged**
