### PR TITLE
Revert "rangefeed: unconditionally use rangefeed scheduler"

### PR DESCRIPTION
**Pull request by erikgrinaker**
This reverts 3/4 commits from #114410, only leaving 1dbdbe9ad37 which enabled the scheduler by default.

There was significant code drift in tests, but I think I've been able to address the conflicts.

This revert does not integrate with the changes from #120347, so the legacy rangefeed processor will not use the improved memory accounting. We still shouldn't leak budget allocations, since the processor implementations are entirely independent, but it's worth having a second look to make sure the registry (which is used by both processors) don't make assumptions about this.

Touches #121054.
Epic: none.
Release note: the following release note from #114410 should be reverted/ignored: "the setting kv.rangefeed.scheduler.enabled has been removed, as the rangefeed scheduler is now unconditionally enabled".

### CODE REVIEW

**Comment by erikgrinaker** [comment]
I've run a few roachtests to verify, seems to work fine. I think this should be good to go.

> it's worth having a second look to make sure the registry (which is used by both processors) don't make assumptions about this

`SharedBudgetAllocation.Use()` and `Release()` handle `nil` allocations just fine, so it's ok for the legacy processor to not attach allocations to all events.

**Comment by wenyihu6** [comment]
re: memory accounting part, legacy and scheduled processor seem to handle everything the same way, except for my recent changes (which is just an improvement, no memory leaks without it), so it looks fine. 

I will defer the stamp to those who reviewed the original PRs though.

**Review by rharding6373 — APPROVED** [review]
:lgtm: Why were the reverts in store.go and testing_knobs.go no longer needed?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121164#-:-Nu-NLqh7B8Yb5Y-Lq_y:b-mv0gd1)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @erikgrinaker, @nvanbenschoten, @renatolabs, and @wenyihu6)

___
*[`pkg/kv/kvclient/rangefeed/rangefeed_external_test.go` line 69 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/121164#-Nu-M33e0OPeezw5luxQ:-Nu-M33e0OPeezw5luxR:b537eov) ([raw file](https://github.com/cockroachdb/cockroach/blob/662f8372db07557f8669a59cb30f0ba226f8bb21/pkg/kv/kvclient/rangefeed/rangefeed_external_test.go#L69)):*
> ```Go
> 
> func (t feedProcessorType) String() string {
> 	return fmt.Sprintf("single/scheduler=%t", t.useScheduler)
> ```

Should this be mux instead of single?

**Review by erikgrinaker — COMMENTED** [review]
It didn't seem useful to revert those changes -- I think we want the scheduler to be responsive to testing knobs regardless.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121164#-:-Nu-TFPs5-_v5pB1IAQT:b-hnt0p2)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DarrylWong, @nvanbenschoten, @renatolabs, @rharding6373, and @wenyihu6)

___
*[`pkg/kv/kvclient/rangefeed/rangefeed_external_test.go` line 69 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/121164#-Nu-M33e0OPeezw5luxQ:-Nu-TBZ55V4lhN17bHD7:bg9zbzd) ([raw file](https://github.com/cockroachdb/cockroach/blob/662f8372db07557f8669a59cb30f0ba226f8bb21/pkg/kv/kvclient/rangefeed/rangefeed_external_test.go#L69)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Should this be mux instead of single?
</blockquote></details>

It should, good catch -- thanks!

**Comment by erikgrinaker** [comment]
I'm going to optimistically bors this to get it in before the branch cut, as I only changed a string since the last CI run.

bors r+

**Pull request merged**
