### PR TITLE
distsql: simplification of DISTINCT spec

### PR DESCRIPTION
**Pull request by irfansharif**
We can simply specify the ordered columns for `DISTINCT` without the
need for the heavier weight `Ordering` equivalent. Note that the
specific ordering of the column (asc/desc) itself is not important, nor
is the order in which the columns are specified.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12301)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsql/processors.proto, line 130 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12301#-KYqFsHsWn6ioxyEs9q2:-KYqFsHsWn6ioxyEs9q3:bs9xil0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f24d654c2bc4d67c3c312f2d138e368e051643b/pkg/sql/distsql/processors.proto#L130)):*
> ```protobuf
> 
> message DistinctSpec {
>   // The ordered columns in the input stream can be optionally specified for
> ```

This is not optional anymore.. In fact it has to exactly match the size of the rows in the input (which we should also check in the code). I think the old way was more convenient from a planning perspective..  We could just replace the `Ordering` with a `repeated uint32` and mention that the order in which the columns are specified is not important.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12301)*

**Comment by irfansharif** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsql/processors.proto, line 130 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12301#-KYqFsHsWn6ioxyEs9q2:-KYqM6JUNMuMHI_E1Tnf:bjv7fps) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f24d654c2bc4d67c3c312f2d138e368e051643b/pkg/sql/distsql/processors.proto#L130)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is not optional anymore.. In fact it has to exactly match the size of the rows in the input (which we should also check in the code). I think the old way was more convenient from a planning perspective..  We could just replace the `Ordering` with a `repeated uint32` and mention that the order in which the columns are specified is not important.
</blockquote></details>

I meant optional in that you can either specify it or not, but yes I think that makes sense. Will make that change shortly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12301)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/distsql/processors.proto, line 130 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12301#-KYqFsHsWn6ioxyEs9q2:-KYqVHbBYr-3_TkMCdnx:b-w1q3sd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f24d654c2bc4d67c3c312f2d138e368e051643b/pkg/sql/distsql/processors.proto#L130)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

I meant optional in that you can either specify it or not, but yes I think that makes sense. Will make that change shortly.
</blockquote></details>

Ah, I see, I had missed the `orderedCols != nil` check

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12301)*

**Comment by irfansharif** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/distsql/processors.proto, line 130 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12301#-KYqFsHsWn6ioxyEs9q2:-KYtwWaKn_Dr9JSi85jN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f24d654c2bc4d67c3c312f2d138e368e051643b/pkg/sql/distsql/processors.proto#L130)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Ah, I see, I had missed the `orderedCols != nil` check
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12301)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12301#-:-KYtx1c79wl8CH2lKBKm:bnfp4nl)*

**Pull request merged**
