### PR TITLE
changefeedccl, kv: Add few metrics

### PR DESCRIPTION
**Pull request by miretskiy**
See commits for details.

Release Notes: None
Release justification: Low impact observability improvement

### CODE REVIEW

**Review by HonoreDB — APPROVED** [review]
> Reviewed 6 of 6 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77711)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

**Review by erikgrinaker — APPROVED** [review]
:lgtm: with some nits.

> Reviewed 6 of 6 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77711#-:-My85nKNBXL5NoKp09z2:bw51gr7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[pkg/ccl/changefeedccl/metrics.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77711#-My857tVCqVpdHqZCT3U:-My857tVCqVpdHqZCT3V:bs2b3c9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d463445b8b2fbc014888532d52fa26909289c89/pkg/ccl/changefeedccl/metrics.go#L90)):*
> ```Go
> const sinkDoesNotCompress = -1
> 
> type recordEmittedMessagesCallback func(numMessages int, mvcc hlc.Timestamp, bytes int, compressedBytes int)
> ```

Can we get rid of this now, and only use `recordOneMessageCallback`?
___
*[pkg/ccl/changefeedccl/metrics.go, line 346 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77711#-My85EBr90Ci1r_JWoOz:-My85EBr90Ci1r_JWoP-:b-3qrdt9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d463445b8b2fbc014888532d52fa26909289c89/pkg/ccl/changefeedccl/metrics.go#L346)):*
> ```Go
> 		EmittedMessages: b.Counter(metaChangefeedEmittedMessages),
> 		MessageSize: b.Histogram(metaMessageSize,
> 			histogramWindow, 10<<20 /* 10MB max message size */, 1),
> ```

What happens for messages >10MB? Are they ignored, or do we have a bucket for those that exceed the limit?
___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 143 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77711#-My85RnO6NwHKe4zb6Dz:-My85RnO6NwHKe4zb6E-:b-3ywte6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9915960a9beae50aa057b46983b43be610512b8/pkg/kv/kvclient/kvcoord/dist_sender.go#L143)):*
> ```Go
> 	}
> 	metaDistSenderRangefeedTotalRanges = metric.Metadata{
> 		Name: "distsender.rangefeed.catchup_ranges",
> ```

This should be `total_ranges`.
___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 146 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77711#-My85XlsCMR9lZN7Pphs:-My85XlsCMR9lZN7Ppht:b-50yhz6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9915960a9beae50aa057b46983b43be610512b8/pkg/kv/kvclient/kvcoord/dist_sender.go#L146)):*
> ```Go
> 		Help: `Number of ranges executing rangefeed
> 
> This counts the total number of rangefeed ranges.
> ```

nit: reword as "number of ranges with an active rangefeed" or something.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77711)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[pkg/ccl/changefeedccl/metrics.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77711#-My857tVCqVpdHqZCT3U:-My89l6p4xwxZURZeq1c:b7mcahn) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d463445b8b2fbc014888532d52fa26909289c89/pkg/ccl/changefeedccl/metrics.go#L90)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Can we get rid of this now, and only use `recordOneMessageCallback`?
</blockquote></details>

Nice.  And it's gone.
___
*[pkg/ccl/changefeedccl/metrics.go, line 346 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77711#-My85EBr90Ci1r_JWoOz:-My88O3AErrFPF56Bowo:b-d9siru) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d463445b8b2fbc014888532d52fa26909289c89/pkg/ccl/changefeedccl/metrics.go#L346)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

What happens for messages >10MB? Are they ignored, or do we have a bucket for those that exceed the limit?
</blockquote></details>

Just a normal histogram nonsense -- these will be truncated; honestly, if your events are more than 10MB... it just a matter of how bad things are.. Cause they are bad.
___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 143 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77711#-My85RnO6NwHKe4zb6Dz:-My88lcL7odMNzfC0Cms:b-s3vgxz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9915960a9beae50aa057b46983b43be610512b8/pkg/kv/kvclient/kvcoord/dist_sender.go#L143)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

This should be `total_ranges`.
</blockquote></details>

Nice.  Thanks.
___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 146 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77711#-My85XlsCMR9lZN7Pphs:-My88uvC0rduzTQav2YJ:b-qvurwz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9915960a9beae50aa057b46983b43be610512b8/pkg/kv/kvclient/kvcoord/dist_sender.go#L146)):*
> number of ranges with an active rangefeed
Done.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r1, 2 of 5 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77711#-:-My9LrT_6tGCk0muEget:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @erikgrinaker)

**Pull request merged**
