### PR TITLE
cast: disallow int to 0-length bit or varbit casts

### LINKED ISSUE #79262: sql: explicit cast of int to varbit results in zero-length bit-string
When we explicitly cast an integer to `VARBIT` (without a length) the resulting bit-string has length 0. This doesn't match what we do for int to `VARBIT(n)` or string to `VARBIT`. I would expect a cast to `VARBIT` to match the cast to `VARBIT(n)` (assuming n is large enough).

Some cases:

```sql
SELECT 0::VARBIT(1);
SELECT 1::VARBIT(1);
SELECT 9::VARBIT(4);
SELECT 0::VARBIT;
SELECT 1::VARBIT;
SELECT 9::VARBIT;
SELECT '0'::VARBIT;
SELECT '1'::VARBIT;
SELECT '1001'::VARBIT;
```

CockroachDB v22.1.0-alpha:

```
demo@127.0.0.1:26257/defaultdb> SELECT 0::VARBIT(1);                                                                                                                                                                                                                                                                                                                                                                                        SELECT 1::VARBIT(1);                                                                                                                                                                                                                                                                                                                                                                                                                        SELECT 9::VARBIT(4);                                                                                                                                                                                                                                                                                                                                                                                                                        SELECT 0::VARBIT;                                                                                                                                                                                                                                                                                                                                                                                                                           SELECT 1::VARBIT;                                                                                                                                                                                                                                                                                                                                                                                                                           SELECT 9::VARBIT;                                                                                                                                                                                                                                                                                                                                                                                                                           SELECT '0'::VARBIT;                                                                                                                                                                                                                                                                                                                                                                                                                         SELECT '1'::VARBIT;                                                                                                                                                                                                                                                                                                                                                                                                                         SELECT '1001'::VARBIT;
  varbit
----------
       0
(1 row)


Time: 0ms total (execution 0ms / network 0ms)

  varbit
----------
       1
(1 row)


Time: 0ms total (execution 0ms / network 0ms)

  varbit
----------
    1001
(1 row)


Time: 0ms total (execution 0ms / network 0ms)

  varbit
----------

(1 row)


Time: 0ms total (execution 0ms / network 0ms)

  varbit
----------

(1 row)


Time: 0ms total (execution 0ms / network 0ms)

  varbit
----------

(1 row)


Time: 0ms total (execution 0ms / network 0ms)

  varbit
----------
       0
(1 row)


Time: 0ms total (execution 0ms / network 0ms)

  varbit
----------
       1
(1 row)


Time: 0ms total (execution 0ms / network 0ms)

  varbit
----------
    1001
(1 row)


Time: 0ms total (execution 0ms / network 0ms)
```

Jira issue: CRDB-14661

### PR DESCRIPTION
**Pull request by aeekayy**
Removing the ability to cast int, int2 and int8 to a 0 length bit or
varbit. If the bit or varbit has a 0 length, LookupCast will return
false. Otherwise, LookupCast will return true with the Cast.

Resolves: https://github.com/cockroachdb/cockroach/issues/79262

Release note (sql change): Removing the ability to cast int, int2 and
int8 to a 0 length bit or varbit.

### CODE REVIEW

**Review by michae2 — CHANGES_REQUESTED** [review]
Thanks for working on this! We really appreciate it!

I think you'll need to make some changes to these tests:
* `pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index:527` which you can check by running `./dev test pkg/sql/opt/exec/execbuilder -f=TestExecBuild/local/hash_sharded_index`
* `pkg/sql/logictest/testdata/logic_test/cross_join:5` and `pkg/sql/logictest/testdata/logic_test/srfs:1235` which you can check by running `./dev testlogic --config=local --files='cross_join|srfs'`
* `pkg/sql/sem/eval/cast_test/testdata/explicit_casts_skip.csv` which you can check by running `./dev test pkg/sql/sem/eval/cast_test -f=TestExplicitCastsMatchPostgres`

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81266#-:-N2DCKeP9YasLM86ihb2:b4bqkhx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aeekayy)

___
*[`pkg/sql/sem/cast/cast.go` line 294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81266#-N2DA3il8lpwAwtbX8dP:-N2DA3im64CAdVTDu2Bj:b-e5mgeh) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec617791ba9e8b3aae5d3d5ae0303a58d9267c2b/pkg/sql/sem/cast/cast.go#L294)):*
> ```Go
> 	// is define
> 	if srcFamily == types.IntFamily &&
> 		(tgtFamily == types.BitFamily) &&
> ```

Checking that `tgtFamily == types.BitFamily` means this logic also applies to `BIT` as well as `VARBIT`. (I.e. this will also disallow casts from int to `BIT(0)` while allowing all other casts from int to `BIT(N)`.) This is fine, as we don't allow usage of `BIT(0)` anyway. But this means you should also remove the three `oid.T_bit` lines from `castMap` that correspond with the three `oid.T_varbit` lines you removed.

Also, nit: you don't need the parentheses around `tgtFamily == types.BitFamily`.
___
*[`pkg/sql/sem/cast/cast_map.go` line 355 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81266#-N2DC8XR517jBry9FtgO:-N2DC8XR517jBry9FtgP:b-vws6b3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec617791ba9e8b3aae5d3d5ae0303a58d9267c2b/pkg/sql/sem/cast/cast_map.go#L355)):*
> ```Go
> 	},
> 	oid.T_int2: {
> 		oid.T_bit:          {MaxContext: ContextExplicit, origin: ContextOriginLegacyConversion, Volatility: volatility.Immutable},
> ```

You can also remove this line.
___
*[`pkg/sql/sem/cast/cast_map.go` line 381 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81266#-N2DCDEe27cGaEtYt9eU:-N2DCDEe27cGaEtYt9eV:b1p0ou4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec617791ba9e8b3aae5d3d5ae0303a58d9267c2b/pkg/sql/sem/cast/cast_map.go#L381)):*
> ```Go
> 	},
> 	oid.T_int4: {
> 		oid.T_bit:          {MaxContext: ContextExplicit, origin: ContextOriginPgCast, Volatility: volatility.Immutable},
> ```

And this one.
___
*[`pkg/sql/sem/cast/cast_map.go` line 407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81266#-N2DCF24Dn3QA5bybKwt:-N2DCF24Dn3QA5bybKwu:b-1ec2im) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec617791ba9e8b3aae5d3d5ae0303a58d9267c2b/pkg/sql/sem/cast/cast_map.go#L407)):*
> ```Go
> 	},
> 	oid.T_int8: {
> 		oid.T_bit:          {MaxContext: ContextExplicit, origin: ContextOriginPgCast, Volatility: volatility.Immutable},
> ```

And this.

**Comment by aeekayy** [comment]
@michae2 thanks for the assist and for nitpicking 👍

**Comment by aeekayy** [comment]
@michae2 are you familiar with this error:
```

**Comment by aeekayy** [comment]
@michae2 are you familiar with this error:
```

**Review by michae2 — CHANGES_REQUESTED** [review]
Looking great! This is almost done. (You can probably mark it as "Ready for review" if you'd like.) I left a couple comments below.

> @michae2 are you familiar with this error:

I think this is probably a flaky test similar to https://github.com/cockroachdb/cockroach/issues/74653 which we can ignore for now. Next push will probably be green.

> Also, how can I join the Slack channel? The link [here](https://www.cockroachlabs.com/join-community/) is stale.

Ah, shoot, thanks for pointing that out! Ok, I think we've fixed it. Sorry about that!

> Reviewed 7 of 7 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81266#-:-N2OKJzH6wRvaQcGDZBq:b-vuugf4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aeekayy)

___
*[`-- commits` line 2 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/81266#-N2OOfeQA1r2KKXvMzkN):*
This is a fine commit message, but we have a couple [formatting rules](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages#General-structure-of-a-commit-message) for commit messages that we have to follow for automation purposes. This needs:
* to be wrapped to 72 columns
* a title, maybe something like "cast: disallow int to 0-length varbit casts" or similar
* "Resolves: #79262" near the bottom
* "Release note (sql change): " at the bottom followed by a description of what will change (a single sentence is fine)

Thank you!
___
*[`pkg/sql/sem/cast/cast.go` line 292 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/81266#-N2OQbaYEkubWc10XK3G:-N2OQbaYEkubWc10XK3H:b-1tgs0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/5358432f0edab247588d9ea53b0d3e1b5a1a7b13/pkg/sql/sem/cast/cast.go#L292)):*
> ```Go
> 
> 	// Casts from int types to varbit types only if the the length of the varbit
> 	// is define
> ```

Let's make this comment a full sentence, something like "Casts from int types to bit and varbit types are allowed only if the length of the bit or varbit type is defined."



_Code quote:_
```Go
	// Casts from int types to varbit types only if the the length of the varbit
	// is define
```
___
*[`pkg/sql/sem/cast/cast_map.go` line 382 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/81266#-N2ONGM0EfWVvxxHNS8k:-N2ONGM1DZT3tkMD_wnv:b-cbeyf0) ([raw file](https://github.com/cockroachdb/cockroach/blob/16c484aa84d3718bfc82557f8e935ab78e6753b6/pkg/sql/sem/cast/cast_map.go#L382)):*
> ```Go
> 	},
> 	oid.T_int4: {
> 		oid.T_bit:          {MaxContext: ContextExplicit, origin: ContextOriginPgCast, Volatility: volatility.Immutable},
> ```

I was wrong about removing this line, we need to keep it for `pg_catalog.pg_cast` to be correct, see below. Sorry!
___
*[`pkg/sql/sem/cast/cast_map.go` line 409 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/81266#-N2OO9prD2koMWlbA8PA:-N2OO9ps8AxB7DYcPI6v:bc506i9) ([raw file](https://github.com/cockroachdb/cockroach/blob/16c484aa84d3718bfc82557f8e935ab78e6753b6/pkg/sql/sem/cast/cast_map.go#L409)):*
> ```Go
> 	},
> 	oid.T_int8: {
> 		oid.T_bit:          {MaxContext: ContextExplicit, origin: ContextOriginPgCast, Volatility: volatility.Immutable},
> ```

I was also wrong about removing this line, again we need to keep it for `pg_catalog.pg_cast`.
___
*[`pkg/sql/logictest/testdata/logic_test/pg_catalog` line 5777 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/81266#-N2OMtxX9ViLbD7xIabC:-N2OMtxX9ViLbD7xIabD:b-r2kuij) ([raw file](https://github.com/cockroachdb/cockroach/blob/16c484aa84d3718bfc82557f8e935ab78e6753b6/pkg/sql/logictest/testdata/logic_test/pg_catalog#L5777)):*
> ```
> 2084734765  1560        23          NULL      e            NULL
> 2084734766  1560        20          NULL      e            NULL
> 2091037769  23          1560        NULL      e            NULL
> ```

Ah, shoot, looks like I was wrong about removing those `oid.T_bit` lines from `castMap`. Sorry! We need to keep the two lines with `origin: ContextOriginPgCast` (but we can still remove the first one with `origin: ContextOriginLegacyConversion`). After putting those two lines back, we shouldn't have to change this testcase.
___
*[`pkg/sql/sem/eval/cast_test/testdata/explicit_casts.csv` line 634 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/81266#-N2OR8Df7cEaWc09WokE:-N2OR8Df7cEaWc09WokF:balyfrw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5358432f0edab247588d9ea53b0d3e1b5a1a7b13/pkg/sql/sem/eval/cast_test/testdata/explicit_casts.csv#L634)):*
> ```CSV
> "'null'","VARBIT(64)",error
> "'true'","VARBIT(64)",error
> "+0","VARBIT(64)",'0000000000000000000000000000000000000000000000000000000000000000'
> ```

This file is generated by a script; we can't make changes to it. Instead, I think you just need to put back three of the removed lines in `pkg/sql/sem/eval/cast_test/testdata/explicit_casts_skip.csv` (the three lines with `VARBIT(64)` instead of `VARBIT`).
___
*[`pkg/sql/sem/eval/cast_test/testdata/explicit_casts_skip.csv` line 3 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/81266#-N2ORYts7W35Elwbd7V-:-N2ORYts7W35Elwbd7V0:bpgkpsj) ([raw file](https://github.com/cockroachdb/cockroach/blob/16c484aa84d3718bfc82557f8e935ab78e6753b6/pkg/sql/sem/eval/cast_test/testdata/explicit_casts_skip.csv#L3)):*
> ```CSV
> # Testcases that are ok for TestExplicitCastsMatchPostgres to skip.
> literal,type,note,issue
> +0,VARBIT(64),"postgres doesn't cast between varbit and integers","https://github.com/cockroachdb/docs/issues/13459"
> ```

Whoops, we need to keep this line.
___
*[`pkg/sql/sem/eval/cast_test/testdata/explicit_casts_skip.csv` line 111 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/81266#-N2ORcBH1URLAELDM0bk:-N2ORcBH1URLAELDM0bl:b48cozw) ([raw file](https://github.com/cockroachdb/cockroach/blob/16c484aa84d3718bfc82557f8e935ab78e6753b6/pkg/sql/sem/eval/cast_test/testdata/explicit_casts_skip.csv#L111)):*
> ```CSV
> SMALLINT '0',BIT,"postgres doesn't cast between bit and smallint","https://github.com/cockroachdb/docs/issues/13459"
> SMALLINT '0',BOOL,"postgres cannot cast smallint to boolean","https://github.com/cockroachdb/docs/issues/13419"
> SMALLINT '0',VARBIT(64),"postgres doesn't cast between varbit and integers","https://github.com/cockroachdb/docs/issues/13459"
> ```

And let's keep this line.
___
*[`pkg/sql/sem/eval/cast_test/testdata/explicit_casts_skip.csv` line 117 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/81266#-N2ORg5wCUqYrFBiJf2X:-N2ORg5wCUqYrFBiJf2Y:bd9rbcg) ([raw file](https://github.com/cockroachdb/cockroach/blob/16c484aa84d3718bfc82557f8e935ab78e6753b6/pkg/sql/sem/eval/cast_test/testdata/explicit_casts_skip.csv#L117)):*
> ```CSV
> SMALLINT '1',BIT,"postgres doesn't cast between bit and smallint","https://github.com/cockroachdb/docs/issues/13459"
> SMALLINT '1',BOOL,"postgres cannot cast smallint to boolean","https://github.com/cockroachdb/docs/issues/13419"
> SMALLINT '1',VARBIT(64),"postgres doesn't cast between varbit and integers","https://github.com/cockroachdb/docs/issues/13459"
> ```

And let's keep this line as well.

**Review by michae2 — CHANGES_REQUESTED** [review]
Just a few last things! :)

> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81266#-:-N2PNbg412B3aI8ji_-g:b-17noqh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aeekayy)

___
*[`pkg/sql/logictest/testdata/logic_test/pg_catalog` line 5806 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/81266#-N2PN85_4FjhH04gOy0V:-N2PN85_4FjhH04gOy0W:b9t6ax) ([raw file](https://github.com/cockroachdb/cockroach/blob/16c484aa84d3718bfc82557f8e935ab78e6753b6/pkg/sql/logictest/testdata/logic_test/pg_catalog#L5806)):*
> ```
> 2250108210  20          2206        NULL      i            NULL
> 2250108214  20          2202        NULL      i            NULL
> 2350774022  20          1560        NULL      e            NULL
> ```

One more removed line to add back here.
___
*[`pkg/sql/sem/eval/cast_test/testdata/explicit_casts.csv` line 680 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/81266#-N2PNJwn2KpyRZSwjibD:-N2PNJwn2KpyRZSwjibE:b6nl3p6) ([raw file](https://github.com/cockroachdb/cockroach/blob/49d3cc9f988d3c45bdd854c7b68c7b7403671fb3/pkg/sql/sem/eval/cast_test/testdata/explicit_casts.csv#L680)):*
> ```CSV
> "VARBIT(16) '1111111111111111'","VARBIT(64)",'1111111111111111'
> "false","VARBIT(64)",error
> "true","VARBIT(64)",error
> ```

Needs a newline at the end of the last line.
___
*[`pkg/sql/sem/eval/cast_test/testdata/explicit_casts_skip.csv` line 3 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/81266#-N2PNPzW3eNShA8UB6yh:-N2PNPzW3eNShA8UB6yi:balappg) ([raw file](https://github.com/cockroachdb/cockroach/blob/16c484aa84d3718bfc82557f8e935ab78e6753b6/pkg/sql/sem/eval/cast_test/testdata/explicit_casts_skip.csv#L3)):*
> ```CSV
> # Testcases that are ok for TestExplicitCastsMatchPostgres to skip.
> literal,type,note,issue
> +0,VARBIT(64),"postgres doesn't cast between varbit and integers","https://github.com/cockroachdb/docs/issues/13459"
> ```

Here's another removed line that we need to add back.

**Review by michae2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81266)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aeekayy)

___
*[`pkg/sql/sem/eval/cast_test/testdata/explicit_casts_skip.csv` line 126 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/81266#-N2PNgEjEu01yvjFjBXG:-N2PNgEjEu01yvjFjBXH:b6nl3p6) ([raw file](https://github.com/cockroachdb/cockroach/blob/49d3cc9f988d3c45bdd854c7b68c7b7403671fb3/pkg/sql/sem/eval/cast_test/testdata/explicit_casts_skip.csv#L126)):*
> ```CSV
> true,INT2,"postgres cannot cast boolean to smallint","https://github.com/cockroachdb/docs/issues/13419"
> true,INT8,"postgres cannot cast boolean to bigint","https://github.com/cockroachdb/docs/issues/13419"
> true,SMALLINT,"postgres cannot cast boolean to smallint","https://github.com/cockroachdb/docs/issues/13419"
> ```

Needs a newline at the end of the last line.

**Comment by aeekayy** [comment]
@michae2 PTAL

**Review by michae2 — APPROVED** [review]
:lgtm: Thank you!

> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81266#-:-N2S63803lMd1c9Q-jK0:b-ae66e1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aeekayy)

**Comment by michae2** [comment]
I'm going to try re-running the GitHub CI. Let's see if we can get a green run before merging.

**Comment by michae2** [comment]
@aeekayy when you get the chance, could you rebase this on latest master and force push? I think that will help get us past this `TestComposeGSS` flake.

**Comment by aeekayy** [comment]
@michae2 there's a different error now after rebasing with master:

```
------- Stdout: -------
=== RUN   TestPartitionedStreamReplicationClient
    test_log_scope.go:79: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestPartitionedStreamReplicationClient2528988951
    test_log_scope.go:80: use -show-logs to present logs inline
    partitioned_stream_client_test.go:185: 
        	Error Trace:	partitioned_stream_client_test.go:185
        	Error:      	Target error should be in err chain:
        	            	expected: "context canceled"
        	            	in chain: "pq: query execution canceled"
        	Test:       	TestPartitionedStreamReplicationClient
    panic.go:642: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestPartitionedStreamReplicationClient2528988951
--- FAIL: TestPartitionedStreamReplicationClient (4.47s)
```

Looks like a test needs updating?

**Comment by michae2** [comment]
Looks like we're good! Thanks again for the contribution, @aeekayy!

bors r=michae2

**Pull request merged**
