### PR TITLE
Ignore VS Code directory for those of us who use the editor.

### PR DESCRIPTION
**Pull request by BramGruneir**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6617)

### CODE REVIEW

**Comment by dt** [comment]
:lgtm:

<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary>
> #### Ignore VS Code directory for those of us who use the editor\.
> 
> 
> 
> 
> </details>


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[.gitignore, line 25 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6617#-KHR6QoUWwnlJIWFACJ_:-KHR6QoV49_Ex4ZMZ6Y5:677826698) ([raw file](https://github.com/cockroachdb/cockroach/blob/90164d06ee806f589750a6b84af1c15397397ed9/.gitignore#L25)):*
> ```
> certs
> 
> # Architecture specific extensions/prefixes
> ```

lol.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6617#-:-KHR6Rtt22tZXdk_Ib8g:1417088721)*

**Comment by bdarnell** [comment]
In general editor-specific files should go in a personal `gitignore` file instead of adding this to the `.gitignore` file of every repo you work in. (Unfortunately there's no default location for this; use `git config --global core.excludesfile ~/.gitignore` to tell git where to look for yours)

**Comment by BramGruneir** [comment]
There are enough of us using the editor that this seems like a sensible solution.  But if you're that opposed to polluting our .gitignore, I'll drop it.

**Comment by tamird** [comment]
Seems to me that we don't have special support for other editors, so I'd
agree with Ben.

**Comment by RaduBerinde** [comment]
How do you like vscode? Does it work well with go?

**Comment by dt** [comment]
The Go support is extremely good.

**Comment by knz** [comment]
I think it does not hurt to have some entries in the common .gitignore for the most popular editors. 
Since we *do* already have this, namely the two entries `*.swp` (vim) and `*~` and `.#*` (emacs), having .vscode does not seem unfair to me. Although I would then move the vim and emacs patterns to the same section for clarity. And perhaps move `.DS_Store` to there as well.

<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> The Go support is extremely good.</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6617#-:-KHUawVKze8wps9aStXp:-51382000)*

**Comment by tschottdorf** [comment]
Ping

**Comment by BramGruneir** [comment]
I don't think we're going to ever get to an consensus on this, so I'll close it.

**Pull request closed without merging**
