### PR TITLE
colexec: miscellaneous cleanups of aggregates

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: add a test comparing aggregator against processor**

This commit adds a test that compares columnar aggregator against
processor. It also improves the output of the input in case any of the
operator vs processor tests fails - now, the input types as well as
input rows will be attempted to be printed as statements that can be
copy-pasted for reproduction.

Release note: None

**colexec: minor refactor of planning of aggregates**

This commit extracts the check whether aggregate functions with given
input types are supported by the vectorized engine into a separate
function. This is useful for TestAggregateAgainstProcessor because this
way, when unsupported, we will fallback to wrapping the processor
(without this change the test would get an "unsupported error" message).
This doesn't have any impact on the users though.

Release note: None

**colexec: fix interaction between min/max and Bytes with NULLs**

Previously, an internal error could be returned when performing min/max
aggregation over Bytes column when NULLs are present. The problem was
that regardless of whether we found a non-null for the group, we were
always "resetting" curAgg value. (This is actually unnecessary, and I'll
fix it in the follow-up commit.)

I believe only flat bytes implementation was affected by it, so only
20.1 alpha had this issue.

Release note (bug fix): Previously, an internal error could be returned
when performing MIN/MAX aggregation over STRING column that contains
NULL values when executed via the vectorized engine, and now this is
fixed. Only 20.1 alpha release was affected.

**colexec: template out count aggregate**

This commit templates out the logic of accumulating a value into
countAgg. The generated code is almost identically the same (the only
difference is explicit declaration of a local variable).

Release note: None

**colexec: clean up some aggregates**

This commit cleans up several aggregates so that they are setting the
value *only* if it is non-null. It also removes zeroing out of the
output vector since it is not necessary - if the output value is NULL,
then Nulls bitmap is set correctly and we don't care about the value; if
the output value is non-NULL, we were zeroing it out anyway when a new
group is encountered.

Release note: None

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 4 of 4 files at r2, 2 of 2 files at r3, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43429)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/distsql/columnar_operators_test.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43429#-Lx2jYDoC_PE0JWS77FA:-Lx2jYDoC_PE0JWS77FB:bhci91f) ([raw file](https://github.com/cockroachdb/cockroach/blob/96deab3ab37fdccb21de92375c9be37fc1a09298/pkg/sql/distsql/columnar_operators_test.go#L59)):*
> ```Go
> 	for run := 0; run < nRuns; run++ {
> 		var rows sqlbase.EncDatumRows
> 		// We will be grouping based on the zeroth column which we'll override to
> ```

Technically we already overrode the zeroth column above to be int. The comment confused me slightly.
___
*[pkg/sql/opt/exec/execbuilder/testdata/aggregate, line 514 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43429#-Lx2jtUQ5nmAA-ZPjc-c:-Lx2jtUQ5nmAA-ZPjc-d:bz8a51g) ([raw file](https://github.com/cockroachdb/cockroach/blob/8add3280c752c928d2a0d265fb24c8bce16a8f4c/pkg/sql/opt/exec/execbuilder/testdata/aggregate#L514)):*
> ```
> ----
> ·          distributed  false        ·                   ·
> ·          vectorized   true         ·                   ·
> ```

How come these became true? The commit message says this commit doesn't change things for users.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43429)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/distsql/columnar_operators_test.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43429#-Lx2jYDoC_PE0JWS77FA:-Lx2lK9p8skWWrw97YvD:b-5nnfnl) ([raw file](https://github.com/cockroachdb/cockroach/blob/96deab3ab37fdccb21de92375c9be37fc1a09298/pkg/sql/distsql/columnar_operators_test.go#L59)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Technically we already overrode the zeroth column above to be int. The comment confused me slightly.
</blockquote></details>

Yes, you're right. It's partially stale comment - I refactored the code but forgot to update the comment. Fixed.
___
*[pkg/sql/opt/exec/execbuilder/testdata/aggregate, line 514 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43429#-Lx2jtUQ5nmAA-ZPjc-c:-Lx2m7S089l1n3mI2pH7:bu422lb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8add3280c752c928d2a0d265fb24c8bce16a8f4c/pkg/sql/opt/exec/execbuilder/testdata/aggregate#L514)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

How come these became true? The commit message says this commit doesn't change things for users.
</blockquote></details>

What changed here is that `isAggregateSupported` now fails earlier which then wraps `rowexec.Aggregator` into the vectorized flow. I didn't think it was worth calling out in a release note. (This is not related to templatizing of `count_agg`.)

**Comment by jordanlewis** [comment]
Ah makes sense. LGTM

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
