### PR TITLE
upgrade to rocksdb v5.5.1, not master

### LINKED ISSUE #16843: stability: SIGILL in rocksdb::LRUCache
Starting with sha a7d51cc5326cafc197248cada1c3d75d7279f8ad (PR #16808, bumps rocksdb to 5.5.1), linux binaries SIGILL on xeon E5-2660 architectures:
```
$ gdb cockroach
> run
Program received signal SIGILL, Illegal instruction.
0x00000000015f24bf in rocksdb::LRUCache::LRUCache(unsigned long, int, bool, double) ()
```

This does not happen on E5-2673, one of the differences being the avx2 instruction.

We saw this before in #13345 which was due to rocksdb being built with `-march=native`.
I'm guessing some build flags got reverted in there somewhere.

### PR DESCRIPTION
**Pull request by benesch**
While looking deeper into #16850, it dawned on me that we somehow weren't building against RocksDB v5.5.1, because the actual v5.5.1 release tarball does _not_ have the SIGILL issue. Looks like #16843 updated `import.sh` to v5.5.1 without actually updating the tarball. Yikes! We need to teach CI to detect this.

----

PR #16808 shipped a tarball that contained a snapshot of the master branch, not v5.5.1. The actual release tarball does not contain the build system changes that caused SIGILLs on some target machines (see #16843).

Fixes #16843.
Closes #16850.

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

Yikes is right.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16852#-:-KoIJ0IgHoSU9V5-LNiU:b-s3kxcw)*

**Comment by benesch** [comment]
Needed to import two upstream commits that didn't make it into v5.5.1. PTAL. cc @petermattis.

**Comment by petermattis** [comment]
:lgtm:

Would be nice if @danhhz could like at the ingest-file patch (and if others are necessary), but he's away this week.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16852#-:-KoIo_GvhaCfV64ewy3A:bfb2a8q)*

**Comment by tamird** [comment]
:lgtm: I'll feel better about this stuff once we move to submodules :|

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16852#-:-KoIozUi1PkBEHR_u5ou:bb2yvcw)*

**Comment by benesch** [comment]
Yeah, I'll be sure to have @danhhz look everything over once he's back! Figured #16843 was important enough to press on without him.

**Comment by danhhz** [comment]
When I tried to patch these two on top of 5.4.7, I was missing the util refactor and https://github.com/facebook/rocksdb/commit/e6725e8c8d7735e2e5fe0efa898b51d7448d8e4c, both of which are in 5.5.1, so I think we're good

**Pull request merged**
