### PR TITLE
opt: add opttester command to check rule applications and memo size

### LINKED ISSUE #59192: opt: add opttester mode that checks number of expressions/groups created
An opttester directive that doesn't output anything but results in a test error if the given statement generates more than X groups or expressions, or applies more than X rules. This would be useful for regression tests for things like https://github.com/cockroachdb/cockroach/issues/59076.

### PR DESCRIPTION
**Pull request by DrewKimball**
Previously, it was difficult to test that the number of rule
applications and/or memo groups remains reasonable during
optimization of a query.

This patch adds the `check-size` command, which outputs the number
of rules applied and memo groups created during optimization. 
The `rule-limit` and `group-limit` flags can be used to throw an 
error if the number of rule applications or memo groups exceed
the given limit.

Release note: None

Fixes #59192

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Very nice, thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59276#-:-MRcTMgE8GePRbmoh9Po:bhwos30)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by mgartner — APPROVED** [review]
Cool! :lgtm: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59276#-:-MRfTZXECaECJndH5Fci:b-dp13x5)* status: :shipit: complete! 2 of 0 LGTMs obtained

**Review by rytaft — APPROVED** [review]
:lgtm: Thanks, @drewkimball!

I'm going to go ahead and merge this...

bors r+

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59276#-:-MRtmSsZE2Xw_-F-FY_8:bji09p8)* status: :shipit: complete! 3 of 0 LGTMs obtained

**Comment by rytaft** [comment]
looks like a flake

bors r+

**Pull request merged**
