### PR TITLE
cli/zip: emit SQL table data using JSON by default

### LINKED ISSUE #102605: cli/zip: output SQL table dumps using JSON by default
Requested by @tbg: `debug zip` forces the table display format for SQL table dumps to `tsv`.

This is not a good default: oftentimes a human is looking at the file and tsv output is hard to grok.
It's also not particularly easy to parse in a script.

We may prefer to use HTML or JSON instead.

Jira issue: CRDB-27556

### PR DESCRIPTION
**Pull request by knz**
Fixes #102605.
All commits except the last are from this PR: #102595.

Release note (backward-incompatible change): The command `cockroach
debug zip` now stores data retrieved from SQL tables in the remote
cluster using the JSON format by default. The previous version
behavior can be obtained by passing `--format=tsv` explicitely.

The JSON data is easier to explore programmatically; and it
can also be explored in a web browser using the
[JsonDiscovery extension](https://github.com/discoveryjs/browser-extension-json-discovery).

Release note (cli change): `cockroach debug zip` now supports the
command-line flag `--format` to select the format used to store SQL
table data, in the same way as `cockroach sql`. In contrast to
`cockroach sql` however, its default value is `json` (resulting in
files named `.json`) and the default is not dependent on whether
the terminal is interactive.

### CODE REVIEW

**Comment by knz** [comment]
will update tests before marking PR as ready to review

**Comment by tbg** [comment]
How would you suggest to consume this data? My browser doesn't even parse this as JSON, and neither does the JsonDiscovery plugin work:

image

To be honest, this seems _more difficult_ rather than easier to consume ad-hoc? Granted, we can now build `jq` pipelines on this data, that is great, but this a very low-velocity way to explore the data dump.

Ideally we'd have both a structured format but also something browsable. But if we can't have both, intuitively for now I think something browsable may be the better choice.

**Comment by knz** [comment]
Oh so regular json instead of ndjson?

**Comment by knz** [comment]
done - ready for review.

**Review by tbg — APPROVED** [review]
LGTM on the last commit and thanks for exploring this! I reviewed the other commits on the separate PR and they're LGTM there as well.

**Comment by knz** [comment]
TFYR! 

bors r=tbg

**Comment by knz** [comment]
bors r=tbg

**Comment by knz** [comment]
bors r=tbg

**Pull request merged**
