### PR TITLE
opt: add remaining plan nodes as opaque operators

### PR DESCRIPTION
**Pull request by RaduBerinde**
Allow all misc plan nodes to be created through the optimizer via an
Opaque operator. The code for `Grant/Revoke` needed some reworking
because it did its work during planning (!) instead of execution.

Release note: None

### CODE REVIEW

**Review by justinj — COMMENTED** [review]
:lgtm_strong: awesome!

> The code for `Grant/Revoke` needed some reworking because it did its work during planning (!) instead of execution.

yikes, does that mean it would take effect if you ran an `EXPLAIN`?

I also think we should either:
* document fairly extensively the steps required now to add a new statement, or
* advise other teams against giving new statements as starter projects

since it feels like there's a lot of places that need to be touched at this point

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39333#-:-LlY6_6b5b9EAH0CMHVX:b79h4tw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/sem/tree/stmt.go, line 286 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39333#-LlY9wBnAECxVst2_chg:-LlY9wBnAECxVst2_chh:b-be3a9y) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa2b2382152011c93066241f45f81934f2c42af2/pkg/sql/sem/tree/stmt.go#L286)):*
> ```Go
> }
> 
> func (*CreateChangefeed) cclOnlyStatement() {}
> ```

Did this cause problems? I guess only if someone tried to use changefeeds with an OSS binary (which is an intersection of two small-ish sets?)

**Review by RaduBerinde — COMMENTED** [review]
Yeah, it would take effect under an EXPLAIN.

I agree. I think we should advise not adding new statements if possible until we remove the heuristic planner altogether, and we need to write up a guide for adding new statements. Jordan has a code lab for adding a new statement which has an optimizer part that needs to be filled in.

I had to make a fix to prevent HP fallback in the case of a specific error.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39333#-:-LlYFQSC3vsj64TEw-Rx:b-ehdw8m)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj and @rytaft)

___
*[pkg/sql/sem/tree/stmt.go, line 286 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39333#-LlY9wBnAECxVst2_chg:-LlYG1xUAcZkSr8iCb_d:bvoingx) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa2b2382152011c93066241f45f81934f2c42af2/pkg/sql/sem/tree/stmt.go#L286)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Did this cause problems? I guess only if someone tried to use changefeeds with an OSS binary (which is an intersection of two small-ish sets?)
</blockquote></details>

It's just the wrong error message if you try to use changefeeds from a non-CCL binary (you get an assertion error with "unknown statement"). Added a test for it in `logictest/ccl`. Also consolidated that file with `backup`.

**Comment by RaduBerinde** [comment]
Had to make some more fixes. One was preserving the `curPlan.avoidBuffering` flag (which is set by CREATE CHANGEFEED). Another was to avoid invoking the optimizer during prepare for DDL statements and such.

**Review by rytaft — APPROVED** [review]
:lgtm: very exciting!

> Reviewed 11 of 13 files at r1, 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39333#-:-Llb-4IO2KHylSfcghYu:b-svalmp)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @justinj and @RaduBerinde)

___
*[pkg/sql/conn_executor_exec.go, line 822 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39333#-LlaxBFZCtD6klJQsKQP:-LlaxBF_1-6JNflOb57K:b-njhrx6) ([raw file](https://github.com/cockroachdb/cockroach/blob/481c8057623da49a473fbeb33114e8ce09718894/pkg/sql/conn_executor_exec.go#L822)):*
> ```Go
> 		return false
> 	}
> 	if err.Error() == "unimplemented: schema change statement cannot follow a statement that has written in the same transaction" {
> ```

Is this tested anywhere?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39333)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj and @rytaft)

___
*[pkg/sql/conn_executor_exec.go, line 822 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39333#-LlaxBFZCtD6klJQsKQP:-Llb0xmYDgd5QqeLBExE:b-sm0wjt) ([raw file](https://github.com/cockroachdb/cockroach/blob/481c8057623da49a473fbeb33114e8ce09718894/pkg/sql/conn_executor_exec.go#L822)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Is this tested anywhere?
</blockquote></details>

Yes, without it we fail many logictests. I will remove the fallback very soon, I considered doing it in this PR but it requires some other in-flight PRs.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39333)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj)

**Comment by RaduBerinde** [comment]
TFTRs!

bors r+

**Pull request merged**
