### PR TITLE
WIP: jobs: improve job adoption code

### PR DESCRIPTION
**Pull request by spaskob**
Currently we fetch the jobs to adopt and pick a few of them to resume in
the same function. This has caused us to use several hacks to accelerate
the adoption of a particular job. We take a principled approach here
instead that splits this function into two functions:

`fetchJobsToAdopt`: reads the jobs table and filters the jobs that are
adoptable on this node.

`maybeAdoptJob`: evaluates a job for adoption and runs it.

The communication between the two is decoupled via a channel that
`fetchJobsToAdopt` sends to.

Release note: none.

### CODE REVIEW

**Review by ajwerner — CHANGES_REQUESTED** [review]
Here's some initial comments

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48600#-:-M6pmjjx7ChUzl_StXbu:br6h1nh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @spaskob)

___
*[pkg/jobs/registry.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48600#-M6plISK1frkup605Shu:-M6plISK1frkup605Shv:b-d9cg41) ([raw file](https://github.com/cockroachdb/cockroach/blob/df44f0afcfaa65333bbbfb0528c926e94db59fa8/pkg/jobs/registry.go#L55)):*
> ```
> 	// How many jobs to fetched on a single node at any time.
> 	// Note that this is pretty arbitrary chosen.
> 	maxJobsToFetch = 500
> ```
Generally best to start with no bufferring on channels. Bufferring almost always hides deadlock bugs. You can add it later if a channel becomes a performance bottleneck. 

Occaisionally it can make sense to have a buffer size of one but 
___
*[pkg/jobs/registry.go, line 510 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48600#-M6pllb03AfQ7pTKpNZm:-M6pllb1-wxBAAUwJ2_x:b-kh0a0d) ([raw file](https://github.com/cockroachdb/cockroach/blob/df44f0afcfaa65333bbbfb0528c926e94db59fa8/pkg/jobs/registry.go#L510)):*
> ```Go
> 	stopper.RunWorker(context.Background(), func(ctx context.Context) {
> 		for {
> 			var allJobsCancelled bool
> ```

I don't think I understand this `allJobsCanceled` business. 
___
*[pkg/jobs/registry.go, line 523 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48600#-M6pmdZGCvrr_NVGssMY:-M6pmdZGCvrr_NVGssMZ:b61kxfm) ([raw file](https://github.com/cockroachdb/cockroach/blob/df44f0afcfaa65333bbbfb0528c926e94db59fa8/pkg/jobs/registry.go#L523)):*
> ```Go
> 			case <-stopper.ShouldStop():
> 				return
> 			case <-r.fetchJobsCh:
> ```

we won't need this any more, right?
___
*[pkg/jobs/registry.go, line 1017 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48600#-M6plwikEUhtQKCtg1oW:-M6plwikEUhtQKCtg1oX:bkbdt6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/df44f0afcfaa65333bbbfb0528c926e94db59fa8/pkg/jobs/registry.go#L1017)):*
> ```Go
> }
> 
> func (r *Registry) fetchJobsToAdopt(ctx context.Context, randomizeJobOrder bool) error {
> ```

fetch to me usually implies that the jobs will be returned. This fetches and then potentially sends one on the channel. 

Maybe call this something like `fetchAndMaybeAdoptJob`?
___
*[pkg/jobs/registry.go, line 1041 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48600#-M6poBt2EAv3b4K3p4Rq:-M6poBt2EAv3b4K3p4Rr:b-a4tp61) ([raw file](https://github.com/cockroachdb/cockroach/blob/df44f0afcfaa65333bbbfb0528c926e94db59fa8/pkg/jobs/registry.go#L1041)):*
> ```Go
> 	var fetched int
> 	for _, row := range rows {
> 		if fetched >= maxAdoptionsPerLoop {
> ```

This is a pretty different condition than what we had before. Imagine we have a large number of running jobs. The fetch loop as written here will just pick one and send it to maybe adopt and then return. If there are a large number of running jobs and not a lot of unclaimed jobs, it will take a very long time with randomness to find an unclaimed job. 
___
*[pkg/jobs/registry.go, line 1106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48600#-M6pnhoF-plYeyPRMx1R:-M6pnhoF-plYeyPRMx1S:b-a7vxwt) ([raw file](https://github.com/cockroachdb/cockroach/blob/df44f0afcfaa65333bbbfb0528c926e94db59fa8/pkg/jobs/registry.go#L1106)):*
> ```Go
> 		}
> 
> 		r.jobIdsToAdoptCh <- *id
> ```

What we've lost with this decoupling is the ability to limit how many jobs we adopt per iteration. That's sort of a bummer. I'm sort of wondering why we want to send on this channel in the first place. Couldn't we just call `maybeAdoptJob` from two different goroutines? It seems to already be thread-safe (or at least I don't see where it isn't). Then we could retain the `adoptedCounter`

**Review by ajwerner — COMMENTED** [review]
did you verify that it fixes the slow schema changes we observed manually?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48600#-:-M6poP_v79qnKTRb44iD:b-qu208v)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @spaskob)

**Review by spaskob — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48600)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/jobs/registry.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48600#-M6plISK1frkup605Shu:-M7c4sti7x00iSRB5VcH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/df44f0afcfaa65333bbbfb0528c926e94db59fa8/pkg/jobs/registry.go#L55)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	// How many jobs to fetched on a single node at any time.
> 	// Note that this is pretty arbitrary chosen.
> 	maxJobsToFetch = 500
> ```
Generally best to start with no bufferring on channels. Bufferring almost always hides deadlock bugs. You can add it later if a channel becomes a performance bottleneck. 

Occaisionally it can make sense to have a buffer size of one but 
</blockquote></details>

Done.
___
*[pkg/jobs/registry.go, line 510 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48600#-M6pllb03AfQ7pTKpNZm:-M7c5TIn4LPyFAIYR43S:b-p1i752) ([raw file](https://github.com/cockroachdb/cockroach/blob/df44f0afcfaa65333bbbfb0528c926e94db59fa8/pkg/jobs/registry.go#L510)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I don't think I understand this `allJobsCanceled` business. 
</blockquote></details>

added comment
___
*[pkg/jobs/registry.go, line 523 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48600#-M6pmdZGCvrr_NVGssMY:-M7c5ustDuAISWbQUfBc:blt5hz2) ([raw file](https://github.com/cockroachdb/cockroach/blob/df44f0afcfaa65333bbbfb0528c926e94db59fa8/pkg/jobs/registry.go#L523)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

we won't need this any more, right?
</blockquote></details>

this is still useful (in tests or elsewhere) to trigger the registry to fetch more jobs instantly
___
*[pkg/jobs/registry.go, line 1017 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48600#-M6plwikEUhtQKCtg1oW:-M7c66YK7I4_VzM6CVTf:b-d56fu3) ([raw file](https://github.com/cockroachdb/cockroach/blob/df44f0afcfaa65333bbbfb0528c926e94db59fa8/pkg/jobs/registry.go#L1017)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

fetch to me usually implies that the jobs will be returned. This fetches and then potentially sends one on the channel. 

Maybe call this something like `fetchAndMaybeAdoptJob`?
</blockquote></details>

This function fetches them and sends them on a channel, it does not adopt any jobs
___
*[pkg/jobs/registry.go, line 1041 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48600#-M6poBt2EAv3b4K3p4Rq:-M7c6VFI4QfFdPvNdbIo:b2f0hp7) ([raw file](https://github.com/cockroachdb/cockroach/blob/df44f0afcfaa65333bbbfb0528c926e94db59fa8/pkg/jobs/registry.go#L1041)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This is a pretty different condition than what we had before. Imagine we have a large number of running jobs. The fetch loop as written here will just pick one and send it to maybe adopt and then return. If there are a large number of running jobs and not a lot of unclaimed jobs, it will take a very long time with randomness to find an unclaimed job. 
</blockquote></details>

it does not pick just one any more but `maxAdoptionsPerLoop`.
___
*[pkg/jobs/registry.go, line 1106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48600#-M6pnhoF-plYeyPRMx1R:-M7c6yNc9PiiGV-_Jhqz:bkjjkp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/df44f0afcfaa65333bbbfb0528c926e94db59fa8/pkg/jobs/registry.go#L1106)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

What we've lost with this decoupling is the ability to limit how many jobs we adopt per iteration. That's sort of a bummer. I'm sort of wondering why we want to send on this channel in the first place. Couldn't we just call `maybeAdoptJob` from two different goroutines? It seems to already be thread-safe (or at least I don't see where it isn't). Then we could retain the `adoptedCounter` 
</blockquote></details>

We do limit up to `maxAdoptionsPerLoop`.

**Review by ajwerner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48600)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @spaskob)

___
*[pkg/jobs/registry.go, line 1041 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48600#-M6poBt2EAv3b4K3p4Rq:-M7cqL0Y8Pl87F-TgEBI:bixaps0) ([raw file](https://github.com/cockroachdb/cockroach/blob/df44f0afcfaa65333bbbfb0528c926e94db59fa8/pkg/jobs/registry.go#L1041)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

it does not pick just one any more but `maxAdoptionsPerLoop`.
</blockquote></details>

I think we're talking past eachother here. Don't fixate on the number one, replace it with `maxAdoptionsPerLoop`. The problem still holds. 
___
*[pkg/jobs/registry.go, line 1106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48600#-M6pnhoF-plYeyPRMx1R:-M7cqR7TB78bLMhJ0ZDj:b-23zanu) ([raw file](https://github.com/cockroachdb/cockroach/blob/df44f0afcfaa65333bbbfb0528c926e94db59fa8/pkg/jobs/registry.go#L1106)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

We do limit up to `maxAdoptionsPerLoop`.
</blockquote></details>

I think you're missing my point. Go read this comment and the one above again and let me know if you still don't think there's a problem.

**Pull request closed without merging**
