### PR TITLE
sql: groupNode cleanups and improvements

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change is a big step toward cleaning up the nightmare in `groupNode`:

 - we were storing expressions in `aggregateFuncHolder.arg` and `.filter` and
   evaluating them for every input row; these are expressions which have
   IndexedVars associated with the underlying `renderNode` and they are already
   being rendered by that node; but we re-evaluate them instead of just using
   `Values()`.  I'm not even sure how this works if the `renderNode` gets
   optimized out (I assume the `IndexedVars` get rebound). Anyway, now we simply
   store the index of the render and use the value directly.

 - for non-trivial GROUP BY expressions that we need to output (e.g.
   `SELECT SUM(k), v+w FROM t GROUP BY v+w`), we were creating an ident
   aggregator for every variable inside (`v`, `w`) and evaluating the expression
   in the post-render. Not only is this silly because we already have the calculated
   value `v+w` available (we are grouping by it), but it also causes unnecessary
   renders to be added below - in this case `v` and `w` in addition to `v+w`.
   Fixing this by just making an ident aggregator for the entire expression. To
   implement this, we rearrange the renders of the `renderNode` below: the first
   columns are always the ones we GROUP BY.

 - The two visitors are consolidated into a single one.

As a consequence of the changes, at the groupNode level we now support the
single-row optimization even if the argument is not a trivial expression.  This
has no practical consequences because a `renderNode` never promises an ordering
on a rendered expression (though it could conceivably in some cases, by
detecting that e.g. if `v` is ordered, so is `v+1`),

Updates #12525.

### CODE REVIEW

**Comment by knz** [comment]
Thanks for moving forward with this.
I can't review this thoroughly today because it's late, but there's a small thing about stars (see my comment below) which you can already look at.
I'll review the rest tomorrow.

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/group.go, line 35 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15749#-KjZRGyW7Yx245E-m6N8:-KjZRGyW7Yx245E-m6N9:b-ykr4v6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8431ec90314f79bfe16ed22256f81fd08dfb070a/pkg/sql/group.go#L35)):*
> ```Go
> // groupByStrMap maps each GROUP BY expression string to the index of the column
> // in the underlying renderNode that renders this expression.
> // For stars (GROUP BY k.*) the special value -1 is used.
> ```

Here and below, I think you are forgetting something...
`SELECT * FROM a, b GROUP BY b.*` does not mean "group by all columns" but rather just those from `b`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15749#-:-KjZRqKE2fIBNwGVxG5_:b-c81zmm)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/group.go, line 35 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15749#-KjZRGyW7Yx245E-m6N8:-KjZWTo-TMy1F1hT6yo1:bw6dpug) ([raw file](https://github.com/cockroachdb/cockroach/blob/8431ec90314f79bfe16ed22256f81fd08dfb070a/pkg/sql/group.go#L35)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Here and below, I think you are forgetting something...
`SELECT * FROM a, b GROUP BY b.*` does not mean "group by all columns" but rather just those from `b`. 
</blockquote></details>

That's fine. This map is used to detect render expressions that also appear in the GROUP BY. Stars cannot appear in the renders. And when you use stars in GROUP BY, you can't render any of those columns by name (not in the existing code, and not in PG).

I could keep these out of the map entirely instead of using the special value. It's there just to assert that we never match those.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15749)*

**Comment by knz** [comment]
Houston, we have a problem!

in pg:

```
kena=# create table ta(x int, y int);
CREATE TABLE
kena=# insert into ta(x,y) values(1,2);
INSERT 0 1
kena=# insert into ta(x,y) values(1,3);
INSERT 0 1
kena=# create table tb(x int, y int);
CREATE TABLE
kena=# insert into tb values(1,2);
INSERT 0 1
kena=# selecT count(distinct ta.*) from ta, tb group by tb.*;
 count
-------
     2
(1 row)
```

in CockroachDB:

```
root@:26257/t> create table ta(x int, y int);
CREATE TABLE
root@:26257/t> insert into ta(x,y) values(1,2);
INSERT 1
root@:26257/t> insert into ta(x,y) values(1,3);
INSERT 1
root@:26257/t> create table tb(x int, y int);
CREATE TABLE
root@:26257/t> insert into tb values(1,2);
INSERT 1
root@:26257/t> selecT count(distinct ta.*) from ta, tb group by tb.*;
+----------------------+
| count(DISTINCT ta.*) |
+----------------------+
|                    1 |
+----------------------+
(1 row)
```

**Comment by RaduBerinde** [comment]
Interesting. I think what is happening is that `ta.*` is being interpreted as the special `*` in `COUNT(*)`. We are doing `DISTINCT` on that special "datum". Note that `SUM(ta.*)` doesn't work in CRDB (`pq: sum(): cannot use "ta.*" in this context`). Can you file a separate issue about this? I don't think it has anything to do with this change.

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15749#-:-KjZfAi-ej7FvQnWinyw:b-91g6x7)*

**Comment by knz** [comment]
done

**Comment by RaduBerinde** [comment]
Added a commit that renames `s` to `r` for `*renderNode`.

**Comment by knz** [comment]
:lgtm: The code is *so* much more readable this way.
Minor nits

---

Reviewed 6 of 9 files at r1, 2 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/sql/group.go, line 52 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15749#-KjcCGrBcQGCd0HREfky:-KjcCGrCGlT0QLV3gp_U:blgtclp) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cb35d688f60927d40dc7497cfb6aea1daa59c3/pkg/sql/group.go#L52)):*
> ```Go
> 	groupByExprs := make([]parser.Expr, len(n.GroupBy))
> 
> 	// A SELECT clause is valid if all its expressions are valid as well, one
> ```

This entire comment is difficult to read and, I believe, partially incorrect.
Perhaps it would be better to remove it or simplify it to a single sentence.

---

*[pkg/sql/group.go, line 89 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15749#-KjcD448pXTHo2FzZrcc:-KjcD448pXTHo2FzZrcd:birjcdz) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cb35d688f60927d40dc7497cfb6aea1daa59c3/pkg/sql/group.go#L89)):*
> ```Go
> 			// We do not need to fully analyze the GROUP BY expression here
> 			// (as per analyzeExpr) because this is taken care of by computeRender
> 			// below.
> ```

Extend the comment: "The call to resolveNames here is necessary however so that AssertNoAggregationOrWindowing below can find resolved FunctionDefs in the AST instead of UnresolvedNames."

---

*[pkg/sql/group.go, line 125 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15749#-KjcDKVBGQ_ykhe_Otw1:-KjcDKVBGQ_ykhe_Otw2:b-3n1a6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cb35d688f60927d40dc7497cfb6aea1daa59c3/pkg/sql/group.go#L125)):*
> ```Go
> 	}
> 
> 	// We replaces the columns in the underlying renderNode with what the
> ```

we replaces -> we replace

---

*[pkg/sql/group.go, line 209 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15749#-KjcDwaD7Fh3XHK6RO4R:-KjcDwaEVZSU9xMIUB_3:b3im1ms) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cb35d688f60927d40dc7497cfb6aea1daa59c3/pkg/sql/group.go#L209)):*
> ```Go
> 	planner *planner
> 
> 	// The "wrapped" node (which returns ungrouped results).
> ```

"wrapped" -> source

---

*[pkg/sql/group.go, line 220 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15749#-KjcDykAF-p9wSkjxd8T:-KjcDykAF-p9wSkjxd8U:b4k02fv) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cb35d688f60927d40dc7497cfb6aea1daa59c3/pkg/sql/group.go#L220)):*
> ```Go
> 
> 	// The group-by columns are the first numGroupCols columns of
> 	// the wrapped plan.
> ```

of the source plan

---

*[pkg/sql/group.go, line 480 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15749#-KjcJv8x85KSZsHtjRRn:-KjcJv8x85KSZsHtjRRo:b-evwljk) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cb35d688f60927d40dc7497cfb6aea1daa59c3/pkg/sql/group.go#L480)):*
> ```Go
> 			// We use this special value to indicate a star group by. This cannot be
> 			// part of a valid expression
> 			panic(fmt.Sprintf("star render in expression %s", expr))
> ```

Curious: I don't understand why it's impossible (why you chose to panic here - it seems that an error is more future-proof).
What about this variant of the example from yesterday `select count(t.*) from t group by t.*`? (I understand that currently we don't encode `t.*` properly in the AST, but once #15750 is fixed we will)

---

*[pkg/sql/group.go, line 498 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15749#-KjcLL_hwbxBBYpA2vGY:-KjcLL_in5F0VAA99cvh:bfmxfak) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cb35d688f60927d40dc7497cfb6aea1daa59c3/pkg/sql/group.go#L498)):*
> ```Go
> 				// checker is not functioning correctly as it should have
> 				// panicked there.
> 				panic("query checker did not detect multiple arguments for aggregator")
> ```

nit: while you are here please convert this panic to an error "aggregate functions with multiple arguments are not supported yet" with a TODO referencing #10495.

---

*[pkg/sql/group_test.go, line 44 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15749#-KjcMMKgtka-EOE7NnbR:-KjcMMKhTExEkGTyyiGE:b-6fva1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cb35d688f60927d40dc7497cfb6aea1daa59c3/pkg/sql/group_test.go#L44)):*
> ```Go
> 		{`(MIN(a), COUNT(a))`, nil},
> 		{`(MIN(a), SUM(a))`, nil},
> 		// TODO(pmattis): This could/should return []int{1} (or perhaps []int{2}),
> ```

I think this TODO can be removed, now that you are reusing renders and aggregateFuncHolders.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15749#-:-KjcMwfKdAwJIWKJx7VJ:bog7p4b)*

**Comment by RaduBerinde** [comment]
TFTR!

---

Review status: 8 of 10 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/sql/group.go, line 52 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15749#-KjcCGrBcQGCd0HREfky:-KjcUfuEpAOyn1wI-VfA:blzs844) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cb35d688f60927d40dc7497cfb6aea1daa59c3/pkg/sql/group.go#L52)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This entire comment is difficult to read and, I believe, partially incorrect.
Perhaps it would be better to remove it or simplify it to a single sentence.
</blockquote></details>

Done, I left the last paragraph.

---

*[pkg/sql/group.go, line 89 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15749#-KjcD448pXTHo2FzZrcc:-KjcUwE0U3Pp0qxEqfL4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cb35d688f60927d40dc7497cfb6aea1daa59c3/pkg/sql/group.go#L89)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Extend the comment: "The call to resolveNames here is necessary however so that AssertNoAggregationOrWindowing below can find resolved FunctionDefs in the AST instead of UnresolvedNames."
</blockquote></details>

Done.

---

*[pkg/sql/group.go, line 125 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15749#-KjcDKVBGQ_ykhe_Otw1:-KjcUykEtK9xpm_sO7r2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cb35d688f60927d40dc7497cfb6aea1daa59c3/pkg/sql/group.go#L125)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

we replaces -> we replace
</blockquote></details>

Done.

---

*[pkg/sql/group.go, line 209 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15749#-KjcDwaD7Fh3XHK6RO4R:-KjcV2wyznz6pnHyBnG3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cb35d688f60927d40dc7497cfb6aea1daa59c3/pkg/sql/group.go#L209)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

"wrapped" -> source
</blockquote></details>

Done.

---

*[pkg/sql/group.go, line 220 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15749#-KjcDykAF-p9wSkjxd8T:-KjcV5cX2Uc4nBtpZbDL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cb35d688f60927d40dc7497cfb6aea1daa59c3/pkg/sql/group.go#L220)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

of the source plan
</blockquote></details>

Done.

---

*[pkg/sql/group.go, line 480 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15749#-KjcJv8x85KSZsHtjRRn:-KjcOiwH2qioCzs9rsLL:bdxpk4m) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cb35d688f60927d40dc7497cfb6aea1daa59c3/pkg/sql/group.go#L480)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Curious: I don't understand why it's impossible (why you chose to panic here - it seems that an error is more future-proof).
What about this variant of the example from yesterday `select count(t.*) from t group by t.*`? (I understand that currently we don't encode `t.*` properly in the AST, but once #15750 is fixed we will)
</blockquote></details>

All the expressions I tried failed checks and never got to this point. But I agree an error is more appropriate, will switch.

The expressions I tried with stars failed checks before we get to this point. In particular, I had no idea what we would want to return for stars. For `COUNT(DISTINCT a.*)` I guess we want to make a Tuple with all the columns (in PG it's equivalent to `COUNT(DISTINCT (col1, col2))`. To implement that, we will have to change the map to store a slice of renders instead of a single one (as part of #15750). I left a TODO.

---

*[pkg/sql/group.go, line 498 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15749#-KjcLL_hwbxBBYpA2vGY:-KjcVO6TvsbehfXcQ49J:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cb35d688f60927d40dc7497cfb6aea1daa59c3/pkg/sql/group.go#L498)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: while you are here please convert this panic to an error "aggregate functions with multiple arguments are not supported yet" with a TODO referencing #10495.
</blockquote></details>

Done.

---

*[pkg/sql/group_test.go, line 44 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15749#-KjcMMKgtka-EOE7NnbR:-KjcQW1dKs92x3hS1V1T:b-b3vdeb) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cb35d688f60927d40dc7497cfb6aea1daa59c3/pkg/sql/group_test.go#L44)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think this TODO can be removed, now that you are reusing renders and aggregateFuncHolders.
</blockquote></details>

We are reusing pre-aggregation renders, but not aggregateFuncHolders. I'll leave this until we do.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15749#-:-KjcXGrH_QkHcKC0j51Z:b-814g8k)*

**Comment by RaduBerinde** [comment]
Removed the 1.0.1 label, I don't think this needs to go into 1.0.1 (it doesn't fix any known functional issue).

**Comment by knz** [comment]
ok; I still think it's good to go (onto master)

**Pull request merged**
