### PR TITLE
release: pick SHA should work for baking and extraordinary releases

### PR DESCRIPTION
**Pull request by rail**
Previously, we used only one branch to find potential release SHAs. Extraordinary and baking releases use different branch patterns, so the automation ignored them.

This PR adds the missing branch patterns into the logic.

Fixes: RE-609
Release note: None

### CODE REVIEW

**Review by celiala — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122196)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rail)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122196#-NvCm19tBpqRPfkqOG4d):*
tiny nit: s/pich/pick/
;).
___
*[`pkg/cmd/release/git.go` line 235 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122196#-NvCmZxy5gZcBjVjdT1F:-NvCmZxy5gZcBjVjdT1G:b8lajwj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1cf1c8d3be0f72b669ac4bcb56e793cae1a6307/pkg/cmd/release/git.go#L235)):*
> // Old style branch name, probably not used anymore.

"release-%d.%d" - release-24.1 will be used for later alphas, betas, and maybe even early RCs.
___
*[`pkg/cmd/release/git.go` line 243 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122196#-NvCnE5K1KmMj7Lys3x6:-NvCnE5K1KmMj7Lys3x7:b-md1snp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1cf1c8d3be0f72b669ac4bcb56e793cae1a6307/pkg/cmd/release/git.go#L243)):*
> if len(remoteBranches) > 1 {

(maybe I need to look at `listRemoteBranches()`?)
but will this return 2 for a patch? 
i.e. v23.2.4 would return both
- release-23.2.4-rc (staging branch)
- release-23.2 (main release branch)

**Review by rail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122196)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @celiala)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122196#-NvCm19tBpqRPfkqOG4d):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

tiny nit: s/pich/pick/
;).
</blockquote></details>

blech :)
___
*[`pkg/cmd/release/git.go` line 235 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122196#-NvCmZxy5gZcBjVjdT1F:-NvCoGkbCiZBylz-xlwX:b-80bnvp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1cf1c8d3be0f72b669ac4bcb56e793cae1a6307/pkg/cmd/release/git.go#L235)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

> // Old style branch name, probably not used anymore.

"release-%d.%d" - release-24.1 will be used for later alphas, betas, and maybe even early RCs.
</blockquote></details>

True.
___
*[`pkg/cmd/release/git.go` line 243 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122196#-NvCnE5K1KmMj7Lys3x6:-NvCoK2230_9oz48NdlR:beip6j4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1cf1c8d3be0f72b669ac4bcb56e793cae1a6307/pkg/cmd/release/git.go#L243)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

> if len(remoteBranches) > 1 {

(maybe I need to look at `listRemoteBranches()`?)
but will this return 2 for a patch? 
i.e. v23.2.4 would return both
- release-23.2.4-rc (staging branch)
- release-23.2 (main release branch)
</blockquote></details>

Good point... Let me rethink this.

**Review by rail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122196)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @celiala)

___
*[`pkg/cmd/release/git.go` line 243 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122196#-NvCnE5K1KmMj7Lys3x6:-NvCpBV1EfFM7ZMTKoN7:b-m015kj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1cf1c8d3be0f72b669ac4bcb56e793cae1a6307/pkg/cmd/release/git.go#L243)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Good point... Let me rethink this.
</blockquote></details>

just verified that this should just work. We don't use globbing for searching (unless it's explicitly passed):
```
$ git ls-remote --refs origin refs/heads/release-23.1
961f1b4c184e804a8cace39a961dc70cddc5dc2e	refs/heads/release-23.1
```

**Review by rail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122196)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @celiala)

___
*[`pkg/cmd/release/git.go` line 243 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122196#-NvCnE5K1KmMj7Lys3x6:-NvCq-3cCtCiiyaKIKpu:bx6g7cx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1cf1c8d3be0f72b669ac4bcb56e793cae1a6307/pkg/cmd/release/git.go#L243)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

just verified that this should just work. We don't use globbing for searching (unless it's explicitly passed):
```
$ git ls-remote --refs origin refs/heads/release-23.1
961f1b4c184e804a8cace39a961dc70cddc5dc2e	refs/heads/release-23.1
```
</blockquote></details>

vs
```
$ git ls-remote --refs origin "refs/heads/release-23.1*"
961f1b4c184e804a8cace39a961dc70cddc5dc2e	refs/heads/release-23.1
84cf36a2a05dcfcf6dfccf4014aad8f703ff6cef	refs/heads/release-23.1.18-rc
```

**Review by celiala — APPROVED** [review]
LGTM  - wooo! thanks for making Pick SHA great again :)

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122196#-:-NvCrhRN6zmd95mSjfAH:b-81sfrp)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rail)

___
*[`pkg/cmd/release/git.go` line 243 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122196#-NvCnE5K1KmMj7Lys3x6:-NvCrcK61GctKVIUhYJa:b-aislnd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1cf1c8d3be0f72b669ac4bcb56e793cae1a6307/pkg/cmd/release/git.go#L243)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

vs
```
$ git ls-remote --refs origin "refs/heads/release-23.1*"
961f1b4c184e804a8cace39a961dc70cddc5dc2e	refs/heads/release-23.1
84cf36a2a05dcfcf6dfccf4014aad8f703ff6cef	refs/heads/release-23.1.18-rc
```
</blockquote></details>

ah, gotcha. thanks for clarifying :)

**Comment by rail** [comment]
bors r=celiala

**Pull request merged**
