### PR TITLE
release-23.1.20-rc: opt: add GenerateTrigramSimilarityInvertedIndexScans rule

### LINKED ISSUE #112675: sql: trigram-index-accelerated fuzzy string matching slow for long search strings
When using trigram indexes to accelerate string operations, the optimizer usually constructs a plan like:

```
filter
    index join
        inverted filter
            scan trigram index
```

The inverted filter aggregates trigram matches to produce a set of PKs for the index join. In the case of `=` and `LIKE` the aggregation is an AND of all of the searched-for trigrams, that is, in order for a PK to match it must have been found in all of the trigram spans. But in the case of `%` (fuzzy string matching, or similarity matching) the aggregation is an OR of all of the searched-for trigrams, that is, any PK that was found in any of the trigram spans matches. This can lead to very large index joins, which are then immediately filtered out. Here's an example:

```sql
CREATE TABLE s (s STRING, INVERTED INDEX (s gin_trgm_ops));
INSERT INTO s SELECT to_hex(generate_series(0, 65535));

-- In both of these cases the AND inverted filter reduces the 64 matched trigrams to 1 PK.
EXPLAIN ANALYZE SELECT s FROM s WHERE s = 'abcd';
EXPLAIN ANALYZE SELECT s FROM s WHERE s LIKE '%abcd%';

-- With the similarity threshold set to max, only one row should match.
SET pg_trgm.similarity_threshold = 1;

-- But the OR inverted filter only reduces the 4962 matched trigrams to 4638 PKs,
-- even though the final filter will end up producing just a single row.
EXPLAIN ANALYZE SELECT s FROM s WHERE s % 'abcd';
```

This effect gets worse for longer search strings, such that trigram index acceleration for very long search strings is probably slower than a full-table scan. This is discussed a bit in #93830.

But I think there's a way to make the inverted filter step smarter for fuzzy string matching. Instead of a plain OR, the inverted filter could require PKs to appear in at least N trigram spans (where N = 1 is equivalent to OR, and N > 1 is more selective). We can calculate N based on the value of `pg_trgm.similarity_threshold` and the number of trigrams in the search string, L, as simply:

N = pg_trgm.similarity_threshold * L

For the example above, I think this would cause the inverted filter to produce only a single row instead of 4638.

Jira issue: CRDB-32547

### PR DESCRIPTION
**Pull request by mgartner**
Backport 5/5 commits from #121973.

/cc @cockroachdb/release

---

#### sql: add optimizer_use_trigram_similarity_optimization setting

This commit adds a new session setting called
`optimizer_use_trigram_similarity_optimization`. It currently has no
effect, but in future commits it will allow control over a new
optimization for queries with trigram similarity filters.

Release note: None

#### sql: disable inverted scans when similarity optimization is enabled

The `GenerateInvertedIndexScans` rule is now disabled for similarity
filters on trigram indexes when the
`optimizer_use_text_similarity_optimization` session setting is enabled.
In a future commit this setting will enable a new rule that makes
`GenerateInvertedIndexScans` obsolete. There is no reason to trigger
both rules.

Release note: None

#### opt: add GenerateTrigramSimilarityInvertedIndexScans rule

The `GenerateTrigramSimilarityInvertedIndexScans` exploration rule has
been added, which index-accelerates trigram similarity filters. See the
comment above the newly added custom function for more details. In
future commits, this rule will be optimized further.

The tests for this rule break from convention: they are added to a new
file rather than to the `select` test file corresponding to the location
of the rule in `select.opt`. This proposed new method of organization is
motivated by the huge growth of the `select` file over the years. If
there is agreement on this, we can incrementally reorganize all existing
tests to match.

Release note (performance improvement): More efficient query plans are
now generated for queries with text similarity filters, e.g.,
`text_col % 'foobar'`. These plans are generated if the
`optimizer_use_trigram_similarity_optimization` session setting is
enabled. It is disabled by default.

#### opt: reduce scanned trigrams for similarity filters

The `GenerateSimilarityInvertedIndexScans` exploration rule now
generates plans that scan fewer trigrams. See the added code comments
for more details.

Release note: None

#### opt: consolidate logic for constraining inverted index prefix columns

The logic for building constraints on prefix columns of multi-column
inverted indexes has been refactored and consolidated.

Fixes #112675

Release note: None

---

Release justification: Performance improvements gated behind a
session setting.

### CODE REVIEW

**Review by michae2 — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, 2 of 2 files at r2, 14 of 14 files at r3, 10 of 10 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122683#-:-Nvrfdua9UbuYohh5tcZ:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

**Review by DrewKimball — APPROVED** [review]
> Reviewed 8 of 8 files at r1, 2 of 2 files at r2, 14 of 14 files at r3, 10 of 10 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122683)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Review by rytaft — APPROVED** [review]
:lgtm: just a few nits -- feel free to ignore or open another PR on master. This can be merged as-is.

> Reviewed 8 of 8 files at r1, 2 of 2 files at r2, 14 of 14 files at r3, 10 of 10 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122683#-:-NvszaxR32_UFKKPjqsi:b-7nqmf8)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/opt/invertedidx/inverted_index_expr.go` line 272 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/122683#-NvssEAbCXCHi2LY1Kjl:-NvssEAbCXCHi2LY1Kjm:b3vj53s) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef0a04cdf7e5cde0bf0534cc4fd64c280b606f08/pkg/sql/opt/invertedidx/inverted_index_expr.go#L272)):*
> ```Go
> 		con = &constraint.Constraint{}
> 		con.Init(&keyCtx, &spans)
> 		break
> ```

What if there are multiple similarity filters? Is it worth generating a different scan expression in the memo for each one?
___
*[`pkg/sql/opt/xform/select_funcs.go` line 997 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/122683#-NvstkAU8SBnGASmqmNN:-NvstkAU8SBnGASmqmNO:b4ip83j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef0a04cdf7e5cde0bf0534cc4fd64c280b606f08/pkg/sql/opt/xform/select_funcs.go#L997)):*
> ```Go
> 
> 		newScanPrivate := *scanPrivate
> 		newScanPrivate.Distribution.Regions = nil
> ```

nit: maybe add a TODO to calculate the regions here? There are some cases where we should be able to determine the regions statically (e.g., REGIONAL BY TABLE).
___
*[`pkg/sql/opt/xform/testdata/rules/generate_trigram_similarity_inverted_index_scans` line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/122683#-Nvsukv9BdLvbUvcFpCk:-NvsukvA1udlcJ4dZJS7:b-3rbr11) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef0a04cdf7e5cde0bf0534cc4fd64c280b606f08/pkg/sql/opt/xform/testdata/rules/generate_trigram_similarity_inverted_index_scans#L1)):*
> ```
> exec-ddl
> ```

nice tests! 

nit: would help to add some comments about what functionality each test is exercising

**Comment by mgartner** [comment]
*[`pkg/sql/opt/invertedidx/inverted_index_expr.go` line 272 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/122683#-NvssEAbCXCHi2LY1Kjl:-Nw0_-8VCHo82Vnh86Ol:b-o0e8xc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef0a04cdf7e5cde0bf0534cc4fd64c280b606f08/pkg/sql/opt/invertedidx/inverted_index_expr.go#L272)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

What if there are multiple similarity filters? Is it worth generating a different scan expression in the memo for each one?
</blockquote></details>

Yes, this is naively for now. I've added a TODO here: #122775

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122683)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @rytaft)

___
*[`pkg/sql/opt/xform/select_funcs.go` line 997 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/122683#-NvstkAU8SBnGASmqmNN:-Nw0WIqhCncmubzf8dTb:bgqs2d7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef0a04cdf7e5cde0bf0534cc4fd64c280b606f08/pkg/sql/opt/xform/select_funcs.go#L997)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: maybe add a TODO to calculate the regions here? There are some cases where we should be able to determine the regions statically (e.g., REGIONAL BY TABLE).
</blockquote></details>

It looks like custom functions never set the distribution directly, and it's done here instead: https://github.com/cockroachdb/cockroach/blob/9514555730fa951a2c72c6ba8b2df6f099c8a720/pkg/sql/opt/xform/optimizer.go#L818
___
*[`pkg/sql/opt/xform/testdata/rules/generate_trigram_similarity_inverted_index_scans` line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/122683#-Nvsukv9BdLvbUvcFpCk:-Nw0Z-hDEOFwaNuTSD6N:b-vsbtm0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef0a04cdf7e5cde0bf0534cc4fd64c280b606f08/pkg/sql/opt/xform/testdata/rules/generate_trigram_similarity_inverted_index_scans#L1)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nice tests! 

nit: would help to add some comments about what functionality each test is exercising
</blockquote></details>

Done here: #122775

**Pull request merged**
