### PR TITLE
distsql: Refactor aggregator into a state machine

### PR DESCRIPTION
**Pull request by abhimadan**
This lays the groundwork for extending the aggregator to stream results
if some of the group columns have an ordering.

Release note: None

----

This is the first commit from #24113, extracted into its own PR.

### CODE REVIEW

**Comment by asubiotto** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/sql/distsqlrun/aggregator.go, line 360 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573#-L9Ru2421gJn4ML6m8An:-L9Ru2421gJn4ML6m8Ao:bmcjpu2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92426e466915fd4df7fd37ad71dbf9d473c7ed2/pkg/sql/distsqlrun/aggregator.go#L360)):*
> ```Go
> 		var row sqlbase.EncDatumRow
> 		var meta *ProducerMetadata
> 		switch ag.state {
> ```

It seems that these three functions have the same signature. Have you considered having these implement an interface? The aggregator could then have a field of this interface that it delegates to instead of the switch statement. This field would be overwritten to point to the next stage once a stage is done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573)*

**Comment by asubiotto** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsqlrun/aggregator.go, line 360 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573#-L9Ru2421gJn4ML6m8An:-L9S3lVLAHvBQBglAFys:byos89k) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92426e466915fd4df7fd37ad71dbf9d473c7ed2/pkg/sql/distsqlrun/aggregator.go#L360)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It seems that these three functions have the same signature. Have you considered having these implement an interface? The aggregator could then have a field of this interface that it delegates to instead of the switch statement. This field would be overwritten to point to the next stage once a stage is done.
</blockquote></details>

Sorry, I've been thinking about interfaces too much. What I mean is have a member of the aggregator with the function signature and assign that with these depending on the stage.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsqlrun/aggregator.go, line 360 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573#-L9Ru2421gJn4ML6m8An:-L9VDqnUDq9Gl7ILaqli:b-2c0qln) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92426e466915fd4df7fd37ad71dbf9d473c7ed2/pkg/sql/distsqlrun/aggregator.go#L360)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Sorry, I've been thinking about interfaces too much. What I mean is have a member of the aggregator with the function signature and assign that with these depending on the stage.
</blockquote></details>

The switch statement might be faster that an indirect call through a function pointer (the CPU branch prediction should predict the case taken very reliably). Not sure if it matters here or not, but something to pay attention to.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573)*

**Comment by abhimadan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsqlrun/aggregator.go, line 360 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573#-L9Ru2421gJn4ML6m8An:-L9fIx-J5-UgwlOtecXI:b9qcju) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92426e466915fd4df7fd37ad71dbf9d473c7ed2/pkg/sql/distsqlrun/aggregator.go#L360)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The switch statement might be faster that an indirect call through a function pointer (the CPU branch prediction should predict the case taken very reliably). Not sure if it matters here or not, but something to pay attention to.
</blockquote></details>

Here's the `benchstat` output from comparing the switch statement to the function pointer version:
```name                    old time/op    new time/op    delta
Aggregation/IDENT-8       54.9µs ± 3%    52.6µs ± 2%   -4.26%  (p=0.000 n=10+9)
Aggregation/AVG-8         80.2µs ± 2%    78.6µs ± 1%   -1.93%  (p=0.000 n=9+9)
Aggregation/COUNT-8       54.2µs ± 2%    54.4µs ± 4%     ~     (p=0.481 n=10+10)
Aggregation/MAX-8         61.3µs ± 6%    61.2µs ± 1%     ~     (p=0.353 n=10+10)
Aggregation/MIN-8         59.6µs ± 1%    61.4µs ± 3%   +2.95%  (p=0.001 n=10+10)
Aggregation/STDDEV-8      1.76ms ± 5%    1.74ms ± 2%     ~     (p=0.315 n=10+8)
Aggregation/SUM-8         68.6µs ± 1%    71.4µs ± 4%   +4.12%  (p=0.000 n=9+10)
Aggregation/SUM_INT-8     67.1µs ± 1%    70.2µs ± 4%   +4.64%  (p=0.000 n=10+10)
Aggregation/VARIANCE-8    1.64ms ± 2%    1.68ms ± 1%   +2.00%  (p=0.000 n=10+8)
Aggregation/XOR_AGG-8     53.4µs ± 1%    54.1µs ± 1%   +1.24%  (p=0.000 n=9+9)

name                    old speed      new speed      delta
Aggregation/IDENT-8      146MB/s ± 3%   152MB/s ± 2%   +4.39%  (p=0.000 n=10+9)
Aggregation/AVG-8        100MB/s ± 2%   102MB/s ± 1%   +1.97%  (p=0.000 n=9+9)
Aggregation/COUNT-8      148MB/s ± 2%   147MB/s ± 4%     ~     (p=0.481 n=10+10)
Aggregation/MAX-8        131MB/s ± 6%   131MB/s ± 1%     ~     (p=0.353 n=10+10)
Aggregation/MIN-8        134MB/s ± 1%   130MB/s ± 3%   -2.84%  (p=0.001 n=10+10)
Aggregation/STDDEV-8    4.56MB/s ± 5%  4.60MB/s ± 2%     ~     (p=0.283 n=10+8)
Aggregation/SUM-8        117MB/s ± 1%   112MB/s ± 4%   -3.93%  (p=0.000 n=9+10)
Aggregation/SUM_INT-8    119MB/s ± 1%   114MB/s ± 4%   -4.39%  (p=0.000 n=10+10)
Aggregation/VARIANCE-8  4.87MB/s ± 2%  4.76MB/s ± 2%   -2.23%  (p=0.000 n=10+9)
Aggregation/XOR_AGG-8    150MB/s ± 1%   148MB/s ± 1%   -1.23%  (p=0.000 n=9+9)

name                    old alloc/op   new alloc/op   delta
Aggregation/IDENT-8       3.10kB ± 0%    3.14kB ± 0%   +1.55%  (p=0.000 n=10+10)
Aggregation/AVG-8         3.87kB ± 0%    3.92kB ± 0%   +1.24%  (p=0.000 n=10+10)
Aggregation/COUNT-8       3.29kB ± 0%    3.34kB ± 0%   +1.46%  (p=0.000 n=10+10)
Aggregation/MAX-8         3.31kB ± 0%    3.36kB ± 0%   +1.45%  (p=0.000 n=10+10)
Aggregation/MIN-8         3.31kB ± 0%    3.36kB ± 0%   +1.45%  (p=0.000 n=10+10)
Aggregation/STDDEV-8       407kB ± 0%     407kB ± 0%   +0.01%  (p=0.000 n=9+10)
Aggregation/SUM-8         3.47kB ± 0%    3.52kB ± 0%   +1.38%  (p=0.000 n=10+10)
Aggregation/SUM_INT-8     3.30kB ± 0%    3.34kB ± 0%   +1.46%  (p=0.000 n=10+10)
Aggregation/VARIANCE-8     404kB ± 0%     404kB ± 0%   +0.01%  (p=0.000 n=10+9)
Aggregation/XOR_AGG-8     3.31kB ± 0%    3.36kB ± 0%   +1.45%  (p=0.000 n=10+10)

name                    old allocs/op  new allocs/op  delta
Aggregation/IDENT-8         16.0 ± 0%      19.0 ± 0%  +18.75%  (p=0.000 n=10+10)
Aggregation/AVG-8           33.0 ± 0%      36.0 ± 0%   +9.09%  (p=0.000 n=10+10)
Aggregation/COUNT-8         23.0 ± 0%      26.0 ± 0%  +13.04%  (p=0.000 n=10+10)
Aggregation/MAX-8           23.0 ± 0%      26.0 ± 0%  +13.04%  (p=0.000 n=10+10)
Aggregation/MIN-8           23.0 ± 0%      26.0 ± 0%  +13.04%  (p=0.000 n=10+10)
Aggregation/STDDEV-8       9.11k ± 0%     9.11k ± 0%   +0.03%  (p=0.000 n=10+10)
Aggregation/SUM-8           24.0 ± 0%      27.0 ± 0%  +12.50%  (p=0.000 n=10+10)
Aggregation/SUM_INT-8       23.0 ± 0%      26.0 ± 0%  +13.04%  (p=0.000 n=10+10)
Aggregation/VARIANCE-8     9.04k ± 0%     9.04k ± 0%   +0.03%  (p=0.000 n=10+10)
Aggregation/XOR_AGG-8       24.0 ± 0%      27.0 ± 0%  +12.50%  (p=0.000 n=10+10)
```
So there doesn't seem to be a significant speed difference, though there is a slight (expected) bump in memory allocations.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573)*

**Comment by andreimatei** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsqlrun/aggregator.go, line 96 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573#-L9fYB8j3qke-scQ4jNN:-L9fYB8j3qke-scQ4jNO:bogyjj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/719da1370d1a37c3aa91b69022e83eaef181247e/pkg/sql/distsqlrun/aggregator.go#L96)):*
> ```Go
> 	rowSourceBase
> 
> 	accumulating aggregatorState
> ```

please spinkle some comments here. How do these fields interact with each other and why are they function pointers? Do the values ever change? Why do these fields exist exactly?

---

*[pkg/sql/distsqlrun/aggregator.go, line 245 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573#-L9fYStm1GIoiFYU2wNJ:-L9fYStm1GIoiFYU2wNK:b18phqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/719da1370d1a37c3aa91b69022e83eaef181247e/pkg/sql/distsqlrun/aggregator.go#L245)):*
> ```Go
> // accumulateRows continually reads rows from the input and accumulates them
> // into intermediary aggregate results. If it encounters metadata, the metadata
> // is immediately returned. Subsequent calls of this function will resume row
> ```

please document the first ret val

---

*[pkg/sql/distsqlrun/aggregator.go, line 358 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573#-L9fZKph1RlhCVuixx-6:-L9fZKph1RlhCVuixx-7:b-frlolw) ([raw file](https://github.com/cockroachdb/cockroach/blob/719da1370d1a37c3aa91b69022e83eaef181247e/pkg/sql/distsqlrun/aggregator.go#L358)):*
> ```Go
> 
> 		// If row == nil and meta == nil, but we aren't done, we have a state
> 		// transition without any output. As a result, we need to execute the next
> ```

this comment is confusing because it talks about what the code doesn't do (return), instead of what it does. Consider rephrasing somehow.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573)*

**Comment by abhimadan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsqlrun/aggregator.go, line 96 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573#-L9fYB8j3qke-scQ4jNN:-L9fguWnEr420IlNJnGq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/719da1370d1a37c3aa91b69022e83eaef181247e/pkg/sql/distsqlrun/aggregator.go#L96)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

please spinkle some comments here. How do these fields interact with each other and why are they function pointers? Do the values ever change? Why do these fields exist exactly?
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/aggregator.go, line 245 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573#-L9fYStm1GIoiFYU2wNJ:-L9fgw__4Pr14RgAkQc5:b-iwa2uh) ([raw file](https://github.com/cockroachdb/cockroach/blob/719da1370d1a37c3aa91b69022e83eaef181247e/pkg/sql/distsqlrun/aggregator.go#L245)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

please document the first ret val
</blockquote></details>

I put a more detailed comment by the type definition, and I'm just mentioning that this is an `aggregatorState` so that the reader knows the description there holds.

---

*[pkg/sql/distsqlrun/aggregator.go, line 358 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573#-L9fZKph1RlhCVuixx-6:-L9fhAxO2cdNI8cCgrMn:brurbkh) ([raw file](https://github.com/cockroachdb/cockroach/blob/719da1370d1a37c3aa91b69022e83eaef181247e/pkg/sql/distsqlrun/aggregator.go#L358)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

this comment is confusing because it talks about what the code doesn't do (return), instead of what it does. Consider rephrasing somehow.
</blockquote></details>

I moved this explanation to the `aggregatorState` type definition.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573)*

**Comment by andreimatei** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/aggregator.go, line 96 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573#-L9fYB8j3qke-scQ4jNN:-L9gG7j93AqNnG1wI5bD:b-rd3uw4) ([raw file](https://github.com/cockroachdb/cockroach/blob/719da1370d1a37c3aa91b69022e83eaef181247e/pkg/sql/distsqlrun/aggregator.go#L96)):*
<details><summary><i>Previously, abhimadan (Abhishek Madan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

So you're trying to avoid the allocation in a `return agg.drainInput`, for example?
You can do that by declaring `aggregatorState` as `type aggregatorState func(*Aggregator) (...)`, and then you return `*aggregator.drainInput` without any allocation.

But I think the simpler and clearer way to do this is to have the state as an enum and the switch over it in `Next()` and call the right method.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573)*

**Comment by andreimatei** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/aggregator.go, line 96 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573#-L9fYB8j3qke-scQ4jNN:-L9gKuOtCGwuI1kwm1Cy:b-e7b6wp) ([raw file](https://github.com/cockroachdb/cockroach/blob/719da1370d1a37c3aa91b69022e83eaef181247e/pkg/sql/distsqlrun/aggregator.go#L96)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

So you're trying to avoid the allocation in a `return agg.drainInput`, for example?
You can do that by declaring `aggregatorState` as `type aggregatorState func(*Aggregator) (...)`, and then you return `*aggregator.drainInput` without any allocation.

But I think the simpler and clearer way to do this is to have the state as an enum and the switch over it in `Next()` and call the right method.
</blockquote></details>

s/*aggregator.drainInput/(*aggregator).drainInput

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573)*

**Comment by andreimatei** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/aggregator.go, line 268 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573#-L9ggP3y4O_bTGexHr6l:-L9ggP3y4O_bTGexHr6m:bw9rel5) ([raw file](https://github.com/cockroachdb/cockroach/blob/39eb793bcdd6b40e80e0cdc7170a16cf4cc3a70f/pkg/sql/distsqlrun/aggregator.go#L268)):*
> ```Go
> 		if meta != nil {
> 			if meta.Err != nil {
> 				return ag.draining, nil, ag.producerMeta(meta.Err)
> ```

As I was telling you, I'm interested in adding some facilities to `processorBase` to help all processors manage their states. That'd be at least conceptually analogous to what you're doing here for this particular processor.
To help make this processor as a model, I'd be great if you could clean up the `producerMeta()` part. As written, there's a couple of thinks that are funky:
- it looks to me like we never call `ag.input.ConsumerClosed()`. One way or another, `ag.ConsumerClosed()` should call it.
- `producerMeta()` is broken - if an error is passed, the trace is never returned. Also, at this call site for example, we're starting to drain, but we're also closing the span. We shouldn't close the span while we're still reading from the input.

I think we should distinguish the draining state from the trailing metadata state. Are you interested in doing something about this?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573)*

**Comment by abhimadan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsqlrun/aggregator.go, line 96 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573#-L9fYB8j3qke-scQ4jNN:-L9k9Xzf8lmkX9sdAmG9:b6y8g4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/719da1370d1a37c3aa91b69022e83eaef181247e/pkg/sql/distsqlrun/aggregator.go#L96)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/*aggregator.drainInput/(*aggregator).drainInput
</blockquote></details>

Thanks, TIL method function pointers are a thing in go, (though it looks like the type would be `func(*aggregator, ...)`). Regardless, I reverted back to using enums.

---

*[pkg/sql/distsqlrun/aggregator.go, line 268 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573#-L9ggP3y4O_bTGexHr6l:-L9kA0aY4asXeFbYEJRH:b-rla7lq) ([raw file](https://github.com/cockroachdb/cockroach/blob/39eb793bcdd6b40e80e0cdc7170a16cf4cc3a70f/pkg/sql/distsqlrun/aggregator.go#L268)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

As I was telling you, I'm interested in adding some facilities to `processorBase` to help all processors manage their states. That'd be at least conceptually analogous to what you're doing here for this particular processor.
To help make this processor as a model, I'd be great if you could clean up the `producerMeta()` part. As written, there's a couple of thinks that are funky:
- it looks to me like we never call `ag.input.ConsumerClosed()`. One way or another, `ag.ConsumerClosed()` should call it.
- `producerMeta()` is broken - if an error is passed, the trace is never returned. Also, at this call site for example, we're starting to drain, but we're also closing the span. We shouldn't close the span while we're still reading from the input.

I think we should distinguish the draining state from the trailing metadata state. Are you interested in doing something about this?
</blockquote></details>

I'd be interested in making this a good model for future work. I made the following changes:
- added a call to `ag.input.ConsumerClosed` in `ConsumerClosed`.
- made `producerMeta` a state execution function. Now, instead of calling `producerMeta` when something goes wrong, processors simply emit error metadata and start draining the input for its metadata (though it would probably be necessary to call `input.ConsumerDone` or something, which I haven't added yet). Once the input is drained, the processor emits trailing metadata (which in the case of the aggregator is just tracing data) via `producerMeta`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573)*

**Comment by abhimadan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/aggregator.go, line 268 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573#-L9ggP3y4O_bTGexHr6l:-L9kPSXt7vsHD6HMELht:b-d21oqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/39eb793bcdd6b40e80e0cdc7170a16cf4cc3a70f/pkg/sql/distsqlrun/aggregator.go#L268)):*
<details><summary><i>Previously, abhimadan (Abhishek Madan) wrote…</i></summary><blockquote>

I'd be interested in making this a good model for future work. I made the following changes:
- added a call to `ag.input.ConsumerClosed` in `ConsumerClosed`.
- made `producerMeta` a state execution function. Now, instead of calling `producerMeta` when something goes wrong, processors simply emit error metadata and start draining the input for its metadata (though it would probably be necessary to call `input.ConsumerDone` or something, which I haven't added yet). Once the input is drained, the processor emits trailing metadata (which in the case of the aggregator is just tracing data) via `producerMeta`.
</blockquote></details>

Added a new `errMeta` method that calls `ConsumerDone` on the input and kicks off the input draining process. PTAL.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsqlrun/aggregator.go, line 235 at r4](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573#-L9kRBRy0dTOsHIKwlUl:-L9kRBRy0dTOsHIKwlUm:bt2xxs7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2963cf255bf31f0b242f0808ee9b7a7e0fc5dff8/pkg/sql/distsqlrun/aggregator.go#L235)):*
> ```Go
> func (ag *aggregator) producerMeta() (aggregatorState, sqlbase.EncDatumRow, *ProducerMetadata) {
> 	var meta *ProducerMetadata
> 	if !ag.closed {
> ```

is checking `ag.closed` still necessary? I think you can drop it; this method should only be called once

---

*[pkg/sql/distsqlrun/aggregator.go, line 307 at r4](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573#-L9kQ1n76bug8PrDg2dG:-L9kQ1n76bug8PrDg2dH:bq02o6u) ([raw file](https://github.com/cockroachdb/cockroach/blob/2963cf255bf31f0b242f0808ee9b7a7e0fc5dff8/pkg/sql/distsqlrun/aggregator.go#L307)):*
> ```Go
> // the processor to the draining state. If given an error, it will produce error
> // metadata as well.
> func (ag *aggregator) errMeta(err error) (aggregatorState, sqlbase.EncDatumRow, *ProducerMetadata) {
> ```

it's weird that a method called `errMeta` has the err be optional.
Rename to `moveToDraining(err)` or smth.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573#-:-L9kS9s2AvHqS9PcwIfI:bnfp4nl)*

**Comment by abhimadan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsqlrun/aggregator.go, line 235 at r4](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573#-L9kRBRy0dTOsHIKwlUl:-L9kauEW65K-YxC8Vqxc:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/2963cf255bf31f0b242f0808ee9b7a7e0fc5dff8/pkg/sql/distsqlrun/aggregator.go#L235)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

is checking `ag.closed` still necessary? I think you can drop it; this method should only be called once
</blockquote></details>

Removed.

---

*[pkg/sql/distsqlrun/aggregator.go, line 307 at r4](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573#-L9kQ1n76bug8PrDg2dG:-L9kawKt6SXVGCEf2GGK:blofq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2963cf255bf31f0b242f0808ee9b7a7e0fc5dff8/pkg/sql/distsqlrun/aggregator.go#L307)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

it's weird that a method called `errMeta` has the err be optional.
Rename to `moveToDraining(err)` or smth.
</blockquote></details>

Renamed to `startDrain`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24573)*

**Comment by couchand** [comment]
preempted by a green button merge
bors r+

**Comment by andreimatei** [comment]
@couchand we don't like green button merges any more? What are their consequences on bors, exactly?

**Comment by couchand** [comment]
@andreimatei Bors enforces that the exact commit going into master is actually built in CI successfully beforehand.  The merge is created on the staging branch, built in CI, then only if it can fast-forward master to that commit will it go in.  If master moves while CI is building, Bors can't fast-forward, so the guarantee is lost, so it restarts the batch. (Or rather, it's supposed to, but often doesn't, issue tracked at bors-ng/bors-ng#301).

**Comment by andreimatei** [comment]
Is that bug happening often enough that we should tell people to stop using the button? (e.g. I use the button when I can and use bors when I don't yet have a green build)

**Comment by RaduBerinde** [comment]
We will probably disable merging without bors at some point, better to get used to it :)

**Pull request merged**
