### PR TITLE
storage: Drop all but the last MsgAppResp per raft.Ready

### LINKED ISSUE #19423: storage: Dropped raft messages
Certain workloads result in a steady stream of "dropped" raft messages (measured [at the server](https://github.com/cockroachdb/cockroach/blob/c82e2c816f45a8984b6f7f0ee68f4cf3a368a4ff/pkg/storage/store.go#L2931) after receiving the messages from the network). #18657 is one such workload; I also have a binary load generator from a customer that exhibits this symptom. 

It is unclear whether these dropped messages are having any significant impact - increasing buffer sizes causes the dropped messages to go away without changing the performance of the workload in #18657. Still, there shouldn't be any dropped messages in normal usage so we should figure out what's going on here.

### PR DESCRIPTION
**Pull request by bdarnell**
Each new MsgAppResp makes all prior ones unnecessary, so when we get
more than one in the same batch we can discard them. Some workloads
have been seen to generate a significant number of these redundant
messages, leading to queue overflows, dropped messages, and reduced
performance. In one such test, this improved write throughput and
p99 latency by 30%.

Release note: Eliminated some redundant raft messages, improving write
performance for some workloads by up to 30%.

Fixes #19423

### CODE REVIEW

**Comment by a-robinson** [comment]
:lgtm:, nice! On the #18657 workload the improvement isn't as pronounced -- it's giving a 5-10% throughput increase if I'm generous interpreting the graph -- but it does completely get rid of the dropped raft messages.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica.go, line 3550 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19540#-KxKG_rVYPbvPOgolZvI:-KxKG_rVYPbvPOgolZvJ:b-7g1iiw) ([raw file](https://github.com/cockroachdb/cockroach/blob/93152cad47829e5dbcce1771e212797431fc8468/pkg/storage/replica.go#L3550)):*
> ```Go
> 			// although MsgAppResp is the only one that has been seen as a
> 			// problem in practice.
> 			if !message.Reject && message.Index > lastAppResp.Index {
> ```

I'm pretty sure raft doesn't depend on the transport being ordered, but just to double check: the fact that this could potentially reorder messages if one of them has the `Reject` flag set is ok, right? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19540#-:-KxKGlBX839CPJDxFL5T:b-eqdsjm)*

**Comment by tschottdorf** [comment]
:lgtm: :thumbsup: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica.go, line 3550 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19540#-KxKG_rVYPbvPOgolZvI:-KxKHZUu6Ns-jIMzpnim:bhh1jap) ([raw file](https://github.com/cockroachdb/cockroach/blob/93152cad47829e5dbcce1771e212797431fc8468/pkg/storage/replica.go#L3550)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

I'm pretty sure raft doesn't depend on the transport being ordered, but just to double check: the fact that this could potentially reorder messages if one of them has the `Reject` flag set is ok, right? 
</blockquote></details>

That should be OK, but I think it's worth a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19540#-:-KxKHxhicGRfKoRh1Ujn:b-wpm7nb)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica.go, line 3550 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19540#-KxKG_rVYPbvPOgolZvI:-KxKHbcAuKO86u69Y47Q:b11evir) ([raw file](https://github.com/cockroachdb/cockroach/blob/93152cad47829e5dbcce1771e212797431fc8468/pkg/storage/replica.go#L3550)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

That should be OK, but I think it's worth a comment.
</blockquote></details>

Raft tolerates reordered messages. In some cases reordering can reduce performance, but it will never produce incorrect results. The main issue is that the order of MsgApps should be preserved (with respect to other MsgApps). Reordering MsgAppResps shouldn't be a problem (and rejections are rare in practice). I'll add a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19540)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/storage/replica.go, line 3500 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/19540#-KxKKPyy_9RWYBiboQoy:-KxKKPyy_9RWYBiboQoz:b-l890px) ([raw file](https://github.com/cockroachdb/cockroach/blob/56886292f92f1f2f0cd3d945d4bd65d9add8a10d/pkg/storage/replica.go#L3500)):*
> ```Go
> 
> 	var lastAppResp raftpb.Message
> 	for _, message := range rd.Messages {
> ```

Rather than adjusting the logic in this loop, another way to implement this would have been to add a new function which takes and returns a `raft.Ready` and trims off any unnecessary `MsgAppResp` from `raft.Ready.Messages`. That approach would alleviate the continued bloat of this method and allow for easier testing and an obvious path for upstreaming this change into `etcd/raft`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19540#-:-KxKKMnlvto94fewo5To:bnfp4nl)*

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/storage/replica.go, line 3500 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/19540#-KxKKPyy_9RWYBiboQoy:-KxKLTKwHrfa81Hv8Qln:b-l4uj8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/56886292f92f1f2f0cd3d945d4bd65d9add8a10d/pkg/storage/replica.go#L3500)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Rather than adjusting the logic in this loop, another way to implement this would have been to add a new function which takes and returns a `raft.Ready` and trims off any unnecessary `MsgAppResp` from `raft.Ready.Messages`. That approach would alleviate the continued bloat of this method and allow for easier testing and an obvious path for upstreaming this change into `etcd/raft`. 
</blockquote></details>

That seems less efficient since you'd need to copy everything into a smaller array (or would you just leave gaps?). I'll reduce bloat by factoring this loop out into a separate method. 

My envisioned upstream solution would be to avoid adding MsgAppResp to the outgoing message queue at all (and synthesize it in `newReady()` instead). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19540)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/storage/replica.go, line 3500 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/19540#-KxKKPyy_9RWYBiboQoy:-KxKQSr39Qqlzwf4RaF8:b-mftw5a) ([raw file](https://github.com/cockroachdb/cockroach/blob/56886292f92f1f2f0cd3d945d4bd65d9add8a10d/pkg/storage/replica.go#L3500)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

That seems less efficient since you'd need to copy everything into a smaller array (or would you just leave gaps?). I'll reduce bloat by factoring this loop out into a separate method. 

My envisioned upstream solution would be to avoid adding MsgAppResp to the outgoing message queue at all (and synthesize it in `newReady()` instead). 
</blockquote></details>

Go supports a very concise way to do this trimming in an efficient manner:

```
func trimRaftReady(rd raft.Ready) raft.Ready {
  messages := rd.Messages
  rd.Messages = rd.Messages[:0]
  for _, msg := rd.Messages {
    if !dropMessage(msg) {
      rd.Messages = append(rd.Messages, msg)
    }
  }
  return rd
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19540)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/storage/replica.go, line 3500 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/19540#-KxKKPyy_9RWYBiboQoy:-KxKR9ajnV18ydo8kz6i:b-e654pg) ([raw file](https://github.com/cockroachdb/cockroach/blob/56886292f92f1f2f0cd3d945d4bd65d9add8a10d/pkg/storage/replica.go#L3500)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Go supports a very concise way to do this trimming in an efficient manner:

```
func trimRaftReady(rd raft.Ready) raft.Ready {
  messages := rd.Messages
  rd.Messages = rd.Messages[:0]
  for _, msg := rd.Messages {
    if !dropMessage(msg) {
      rd.Messages = append(rd.Messages, msg)
    }
  }
  return rd
}
```
</blockquote></details>

Err, that should be `for _, msg := range messages`, but I'm sure you would have caught that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19540)*

**Comment by nvanbenschoten** [comment]
:lgtm: nice!

---

Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19540#-:-KxKVEevrLOPXxjCYxPl:b-7yytuz)*

**Pull request merged**
