### PR TITLE
cli/demo: make multi-tenant login work for 'cockroach demo' too

### PR DESCRIPTION
**Pull request by knz**
I just noticed that Alex' code also works for the demologin endpoint. Let's use it!

Before:
```
demo@127.0.0.1:26257/defaultdb> \demo ls
node 1:
  Application tenant:
   (webui)    http://127.0.0.1:8080/demologin?password=demo96132&tenant_name=demo-tenant&username=demo
   (cli)      cockroach sql --certs-dir=/data/home/kena/.cockroach-demo -u demo
   ...

  System tenant:
   (webui)    http://127.0.0.1:8080/demologin?password=demo96132&tenant_name=system&username=demo
   (cli)      cockroach sql --certs-dir=/data/home/kena/.cockroach-demo -u demo -p 26258
   ....
```

After:
```
demo@127.0.0.1:26257/defaultdb> \demo ls
node 1:
   (webui)    http://127.0.0.1:8080/demologin?password=demo96312&username=demo

  Application tenant:
   (cli)      cockroach sql --certs-dir=/data/home/kena/.cockroach-demo -u demo
   ...

  System tenant:
   (cli)      cockroach sql --certs-dir=/data/home/kena/.cockroach-demo -u demo -p 26258
```

Epic: None

### CODE REVIEW

**Review by Santamaura — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94849#-:-NLMbmoJ-zHLMPVwshn4:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian)

**Review by dhartunian — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94849)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

**Comment by knz** [comment]
tfyrs!

bors r=Santamaura,dhartunian

**Comment by knz** [comment]
bors r=Santamaura,dhartunian

**Comment by knz** [comment]
bors r=Santamaura,dhartunian single on

**Comment by knz** [comment]
bors r=Santamaura,dhartunian single on

**Comment by rail** [comment]
bors single on

**Comment by rail** [comment]
bors r-
We have temporarily disabled bors for merges. Please merge the PR manually when all required checks pass.

**Pull request merged**
