### PR TITLE
backupccl: fix bug due to transaction restart while publishing descri…

### PR DESCRIPTION
**Pull request by ajwerner**
…ptors

Before this patch, if a restart occurred while trying to publish descriptors,
we would short-circuit publishing the descriptors on the subsequent attempt.

The approach was validated by stressing `TestBackupRestoreResume` with the
patch in https://github.com/cockroachdb/cockroach/pull/54695 which previously
reproduced the failure immediately.

Release note (bug fix): Fixed a bug whereby a transaction restart at the
wrong moment during a restore could leave descriptors offline after the
restore completed successfully.

### CODE REVIEW

**Review by thoszhang — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54748)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru)

**Review by adityamaru — APPROVED** [review]

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Comment by pbardea** [comment]
Just catching up on this, does this need a backport into 20.2?

**Comment by ajwerner** [comment]
> Just catching up on this, does this need a backport into 20.2?

Yes indeed. We could potentially go further back too.

**Pull request merged**
