### PR TITLE
opt: change the catalog API for foreign keys

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: move catalog.Table utilities to utils.go

This makes it easier to focus on just the interfaces.

Release note: None

#### opt: change the catalog API for foreign keys

The catalog API mirrors the current implementation where foreign keys
are stored in (and refer to) indexes. In the near future, the foreign
keys will no longer be tied to indexes. We change the catalog APIs
accordingly:
 - remove the foreign key from Index
 - add lists of outbound and inbound foreign keys in Table.
 - ForeignKeyReference is now an interface. There was an interesting
   problem here: we don't have complete information about column
   ordinals until we look up the other table. To solve this, we pass
   the resolved Table when requesting information about columns.

Release note: None

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
The interface changes :lgtm: and match what Lucy and I were doing to the descriptors. Verified that the changes make it possible to modify execbuilder in the way that I was expecting to be able to.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37808#-:-LfwZZOP81kmpaIsFQp3:b-m724fb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @jordanlewis, @justinj, @lucy-zhang, and @RaduBerinde)

___
*[pkg/sql/opt_catalog.go, line 1109 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37808#-LfwZnYN0jUzASwijB9e:-LfwZnYN0jUzASwijB9f:b4j2bct) ([raw file](https://github.com/cockroachdb/cockroach/blob/caccabe295b841de45f2ddf580ccd38ef619f963/pkg/sql/opt_catalog.go#L1109)):*
> ```Go
> }
> 
> type optForeignKeyRef struct {
> ```

Comments on this are important, especially because there's some confusion with symmetry. This same struct is used in both directions.

I would consider making 2 structs, one for forward and one for backward refs. This was really helpful in the descriptor side of things.

Also, you might want to include a name in the ref? Do you ever need to print out things based on the constraint? The name would help for the user.
___
*[pkg/sql/opt/cat/table.go, line 188 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37808#-Lfw_IqjDZLQhqIV_pAc:-Lfw_IqjDZLQhqIV_pAd:bj1zw3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/caccabe295b841de45f2ddf580ccd38ef619f963/pkg/sql/opt/cat/table.go#L188)):*
> ```Go
> // Here o is the origin table, r is the referenced table, and we have two pairs
> // of columns: (o.a,r.a) and (o.b,r.b).
> type ForeignKeyReference interface {
> ```

I do think it will eventually be better to have 2 of these, one forward one back... when we plan the checks and cascades, behavior is very different depending on direction. But maybe it'll always be unambiguous in opt?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37808)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @jordanlewis, @justinj, and @lucy-zhang)

___
*[pkg/sql/opt_catalog.go, line 1109 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37808#-LfwZnYN0jUzASwijB9e:-Lfy4f0p6LE5XXHXQXmT:b-2l1j9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/caccabe295b841de45f2ddf580ccd38ef619f963/pkg/sql/opt_catalog.go#L1109)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Comments on this are important, especially because there's some confusion with symmetry. This same struct is used in both directions.

I would consider making 2 structs, one for forward and one for backward refs. This was really helpful in the descriptor side of things.

Also, you might want to include a name in the ref? Do you ever need to print out things based on the constraint? The name would help for the user.
</blockquote></details>

Where is the confusion about symmetry? The struct has an origin table/idx and a referenced table/idx. The foreign key constraint has a fixed origin and referenced side, no matter which side you're looking at it from.

We would have 2 structs if we wanted to optimize it to store the index descriptor that we know already (and avoid search-index-by-id for that side). But I figured this might change altogether with your refactoring?

Added Name(), good idea.
___
*[pkg/sql/opt/cat/table.go, line 188 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37808#-Lfw_IqjDZLQhqIV_pAc:-Lfy3gloEMrnM7pGGuVm:bror462) ([raw file](https://github.com/cockroachdb/cockroach/blob/caccabe295b841de45f2ddf580ccd38ef619f963/pkg/sql/opt/cat/table.go#L188)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I do think it will eventually be better to have 2 of these, one forward one back... when we plan the checks and cascades, behavior is very different depending on direction. But maybe it'll always be unambiguous in opt?
</blockquote></details>

This represents the foreign key constraint itself. It's explicit about returning info about the origin and the referenced table (which would be swapped if the direction would be reversed). How would two interfaces even look? What would be different between them?

Note that this is different (and IMO is much better) than how the current sqlbase struct has a field for the "other" Table, which can be either the origin or referencing table depending how you use the struct.

BTW maybe Reference is not the right word here? (reference indeed suggests something that's different depending from which side you're looking at it) Maybe ForeignKeyConstraint makes more sense?

**Review by justinj — COMMENTED** [review]
:lgtm_strong:

> Reviewed 2 of 2 files at r1, 12 of 12 files at r2, 16 of 16 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37808#-:-LfyyLsf8uloB4lDy4kX:b-jbsf8z)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @jordanlewis, and @lucy-zhang)

___
*[pkg/sql/opt/cat/table.go, line 188 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37808#-Lfw_IqjDZLQhqIV_pAc:-LfyvvHY4wJc1uFCRN3h:b-vtrda2) ([raw file](https://github.com/cockroachdb/cockroach/blob/caccabe295b841de45f2ddf580ccd38ef619f963/pkg/sql/opt/cat/table.go#L188)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This represents the foreign key constraint itself. It's explicit about returning info about the origin and the referenced table (which would be swapped if the direction would be reversed). How would two interfaces even look? What would be different between them?

Note that this is different (and IMO is much better) than how the current sqlbase struct has a field for the "other" Table, which can be either the origin or referencing table depending how you use the struct.

BTW maybe Reference is not the right word here? (reference indeed suggests something that's different depending from which side you're looking at it) Maybe ForeignKeyConstraint makes more sense?
</blockquote></details>

+1, this is so much better than the status quo. I also like `ForeignKeyConstraint` as a name

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37808)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @jordanlewis, and @lucy-zhang)

___
*[pkg/sql/opt/cat/table.go, line 188 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37808#-Lfw_IqjDZLQhqIV_pAc:-Lfz6OH0-Otq9_vA_EFy:b-gzdzar) ([raw file](https://github.com/cockroachdb/cockroach/blob/caccabe295b841de45f2ddf580ccd38ef619f963/pkg/sql/opt/cat/table.go#L188)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

+1, this is so much better than the status quo. I also like `ForeignKeyConstraint` as a name
</blockquote></details>

We called it `ForeignKeyConstraint` and `ForeignKeyBackreference` in the protobuf definitions, as a point of reference.

cc @lucy-zhang - I think there was a good reason to keep these separate, right? It would be more convenient to have them both be the same, but there's reasons (atomic schema changes?) why it's hard.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37808)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @jordanlewis, @justinj, and @lucy-zhang)

___
*[pkg/sql/opt/cat/table.go, line 188 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37808#-Lfw_IqjDZLQhqIV_pAc:-Lg-ONDf3uhOFNYOkURX:b-jaisw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/caccabe295b841de45f2ddf580ccd38ef619f963/pkg/sql/opt/cat/table.go#L188)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

We called it `ForeignKeyConstraint` and `ForeignKeyBackreference` in the protobuf definitions, as a point of reference.

cc @lucy-zhang - I think there was a good reason to keep these separate, right? It would be more convenient to have them both be the same, but there's reasons (atomic schema changes?) why it's hard.
</blockquote></details>

Updated to `ForeignKeyConstraint`.

**Review by jordanlewis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37808)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @justinj, @lucy-zhang, and @RaduBerinde)

___
*[pkg/sql/opt_catalog.go, line 1109 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37808#-LfwZnYN0jUzASwijB9e:-Lg4FtaU901a0RzNRZrT:b6dvfgx) ([raw file](https://github.com/cockroachdb/cockroach/blob/caccabe295b841de45f2ddf580ccd38ef619f963/pkg/sql/opt_catalog.go#L1109)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Where is the confusion about symmetry? The struct has an origin table/idx and a referenced table/idx. The foreign key constraint has a fixed origin and referenced side, no matter which side you're looking at it from.

We would have 2 structs if we wanted to optimize it to store the index descriptor that we know already (and avoid search-index-by-id for that side). But I figured this might change altogether with your refactoring?

Added Name(), good idea.
</blockquote></details>

Ah, now I understand that both sides store the same struct. Makes sense now. I wonder if we should consider just doing that on the descriptor side as well. I do think it would make things simpler.

**Comment by RaduBerinde** [comment]
TFTRs!

bors r+

**Pull request merged**
