### PR TITLE
kv/bulk,kv: track time/bytes moved in SplitAndScatter

### PR DESCRIPTION
**Pull request by dt**
Release note: none.

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77346#-:-MxGJF4n8qHs0NT21rQM:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15, @adityamaru, and @dt)

___
*[pkg/kv/db.go, line 588 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77346#-MxGIBrj8jaa5bgild2e:-MxGIBrkCHUn_ZjphDB8:b-gkkar5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b9eb3420d08e52448c3fe22d1aec314a4a48a25/pkg/kv/db.go#L588)):*
> ```Go
> }
> 
> type SplitAndScatterReply struct {
> ```

nit: commentary. Also, `Reply` feels just a tad awkward to me. `SplitAndScatterResult` feels more parallel to the [`Result`](https://github.com/cockroachdb/cockroach/blob/f313d66886cccef7e3407c95a0d3fa78a21e1379/pkg/kv/db.go#L122) struct we already have?
___
*[pkg/kv/bulk/buffering_adder.go, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77346#-MxGIfH71v0zfL9zmr1G:-MxGIfH71v0zfL9zmr1H:behtgqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b9eb3420d08e52448c3fe22d1aec314a4a48a25/pkg/kv/bulk/buffering_adder.go#L64)):*
> ```Go
> 
> 	// name of the BufferingAdder for the purpose of logging only.
> 	name string
> ```

make this and the opt field a `redact.SafeString` so it doesn't get redacted. I feel like it's always a constant, no? 
___
*[pkg/kv/bulk/buffering_adder.go, line 334 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77346#-MxGJ8i518WD6ucSe6CJ:-MxGJ8i518WD6ucSe6CK:bl640gb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b9eb3420d08e52448c3fe22d1aec314a4a48a25/pkg/kv/bulk/buffering_adder.go#L334)):*
> ```Go
> 		created++
> 	}
> 	log.Infof(ctx, "%s created %d initial splits from %d keys in %s buffer", b.name, created, b.curBuf.Len(), sz(b.curBuf.MemSize))
> ```

log the duration while you're here?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77346)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15 and @adityamaru)

___
*[pkg/kv/bulk/buffering_adder.go, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77346#-MxGIfH71v0zfL9zmr1G:-MxGQPfEB_-RN2Y24oJU:b6jrv86) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b9eb3420d08e52448c3fe22d1aec314a4a48a25/pkg/kv/bulk/buffering_adder.go#L64)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

make this and the opt field a `redact.SafeString` so it doesn't get redacted. I feel like it's always a constant, no? 
</blockquote></details>

I was intended to have table name in it and we just never added it since there's a little weirdness around multi-table imports.

**Review by aayushshah15 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77346#-:-MxGu7NnCV7kJH3fnNeT:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru)

**Comment by dt** [comment]
TFTRs!

prior ci including testrace was green except for `lint` on commit message and lint is now green on this one, so not waiting around for another testrace hour.

bors r+

**Pull request merged**
