### PR TITLE
sql: add max active queries per node cluster setting

### LINKED ISSUE #54652: sql: add max active transactions
We should add a cluster setting and session variable that allows users to set a `MAX ACTIVE TRANSACTIONS.` This can help provide rough protection to the database from excessive workload. The value would default to infinite and be configurable to users. If a transaction would be sent to the database that exceeds the number of active max transactions, we would return a unique error to the clients. 

Jira issue: CRDB-3732

### PR DESCRIPTION
**Pull request by asubiotto**
This commit adds a sql.max_active_queries cluster setting that can be used to
limit the number of active queries per node. This setting is off by default
(value of 0). Any user with the admin roles is not affected and does not
contribute to this limit. Internal executor use is also not affected.

If a new txn would exceed this limit, a pgerror is returned with the message
"sorry, too many active queries" with the ConfigurationLimitExceeded error
code.

Release note (sql change): add the sql.max_active_queries cluster setting that
limits the number of active queries at one time. admin users are not affected.

Closes #54652

cc @awoods187

### CODE REVIEW

**Comment by asubiotto** [comment]
It didn't seem right to make this a CLI flag since it's more SQL than server related.

**Comment by asubiotto** [comment]
I'm also looking for feedback on the approach @andreimatei, not sure if I'm using the state machine correctly.

**Review by andreimatei — COMMENTED** [review]
I think we want to replace all uses of the root users with the admin role, don't we?

Is there any way to observe the current number of open txns per gateway? If there's a limit on it, there should be an easy way to check how I'm standing against the limit. Consider adding a timeseries to the SQL dashboard.

You sure you want to go with such a simplistic limit, and not with an extensible DSL or system table that will let us add per-app or per-user limits? Also are you sure you want to make this a cluster setting affecting gateways individually? It's a weird setting because it combines limits on per-gateway resources (query processing) with shared ones (transaction locks). The first make sense to be specified on a per-gateway basis (although I'd still want a way to customize them on a per-node basis for heterogeneous deployments) but a direct way to express it would be a limit on the number of concurrent queries, not transactions. The shared ones don't scale with the number of gateways, so don't make sense as a per-gateway limit. I'm not sure it would even make sense as a global limit either; maybe only as a per-app or perhaps per-table, or really per-transaction type (so, you'd go to the transaction's page in the AdminUI and say that for this transaction fingerprint, I only want to allow so many concurrently). The feature that I've really wanted when I was using databases was a way for the client to pre-declare the type of a transaction (for example through a comment on the `BEGIN`) and then have limits on individual types. I guess that if I wanted to do something about limiting locking, I'd start with time limits on holding individual locks.

As implemented, I don't think I like this feature very much. You'll have to get your LGTM from someone else who wants it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54785#-:-MI4hWES7AxFcd1GERjv:b-9q9u0i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @asubiotto, and @jordanlewis)

___
*[pkg/sql/conn_fsm.go, line 440 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54785#-MI4ie-wB2tkqjTEc1c6:-MI4ie-wB2tkqjTEc1c7:b-u5gcvw) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ff38b240330f556d79c6ce11a6ed86a9aa6b1cf/pkg/sql/conn_fsm.go#L440)):*
> ```Go
> 	ts := args.Extended.(*txnState)
> 
> 	if payload.tranCtx.numOpenTxns != nil &&
> ```

I don't think any of this stuff belongs in the state machine. Was there a particular reason you didn't put it in `execStmtInNoTxnState`? It's better to keep the state machine as mechanical as possible.
For decrementing the counter, you can do it in the `onTxnFinish` callback or directly in `resetExtraTxnState`.
___
*[pkg/sql/txn_state.go, line 440 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54785#-MI4iNjTB1pH-YuXaIfF:-MI4iNjTB1pH-YuXaIfG:b-vobh2) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ff38b240330f556d79c6ce11a6ed86a9aa6b1cf/pkg/sql/txn_state.go#L440)):*
> ```Go
> 	user string
> 	// execType specifies whether the executor is user-facing or internal.
> 	execType *executorType
> ```

why is this a pointer?

**Comment by andreimatei** [comment]
Remind me again please why I'd set this do anything else then the max open
connections setting?

**Review by asubiotto — COMMENTED** [review]
> I think we want to replace all uses of the root users with the admin role, don't we?
 
I initially wanted to do it this way but checking for an admin role outside a transaction is not allowed (not sure why). I'm tempted to delete the check in `UserHasAdminRole` but unsure whether this implies that I'm using the API wrong. cc @knz 

> Is there any way to observe the current number of open txns per gateway? 

Yes, but it looks like it's only for explicit transactions.

> You sure you want to go with such a simplistic limit, and not with an extensible DSL or system table that will let us add per-app or per-user limits?

Yes, this limit is simplistic but useful. However, I'm not sure what your suggestion is.

> Also are you sure you want to make this a cluster setting affecting gateways individually?

Yes. I agree it's a bit crude, but it's better than what we have right now which is no system in place at all to limit usage.

> Remind me again please why I'd set this do anything else then the max open connections setting?

I'm still unclear on this. @awoods187 or @jordanlewis do one of you mind answering this? I think it's to do with being able to allow reuse of idle connections in a connection pool without them affecting a limit.

Ultimately, I agree that it's a crude limit but I think it's important to have *something* in place. We can debate what the perfect solution for this is but I think this is something we can get done quickly and addresses a customer need. A good middle ground might be to make this cluster setting experimental.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54785#-:-MIJGA9rBEoOUGsnyoDA:b-t6j41x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @jordanlewis)

___
*[pkg/sql/conn_fsm.go, line 440 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54785#-MI4ie-wB2tkqjTEc1c6:-MIJKYF1BjyWjPY_wcJE:b73jspz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ff38b240330f556d79c6ce11a6ed86a9aa6b1cf/pkg/sql/conn_fsm.go#L440)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't think any of this stuff belongs in the state machine. Was there a particular reason you didn't put it in `execStmtInNoTxnState`? It's better to keep the state machine as mechanical as possible.
For decrementing the counter, you can do it in the `onTxnFinish` callback or directly in `resetExtraTxnState`.
</blockquote></details>

I didn't put it in `execStmtInNoTxnState` because of what seems like two code paths for explicit vs implicit txns. Thanks for the `onTxnFinish` pointer.
___
*[pkg/sql/txn_state.go, line 440 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54785#-MI4iNjTB1pH-YuXaIfF:-MIJKhTH3qs89wUCKVSA:b-jyfqdu) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ff38b240330f556d79c6ce11a6ed86a9aa6b1cf/pkg/sql/txn_state.go#L440)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

why is this a pointer?
</blockquote></details>

It points to a `connExecutor` field so that callers don't need to worry about setting this field as well as the `connExecutor` one.

**Review by knz — COMMENTED** [review]
> I initially wanted to do it this way but checking for an admin role outside a transaction is not allowed (not sure why).

The reason why is to prevent an API usage mistake and a corresponding possible security vulnerability:
- if *there is* a txn, 
- and some earlier SQL statement performs a GRANT or REVOKE inside the txn
- but the code forgets to pass the txn properly to the admin check function
- then the check function will not properly "see" the GRANt or REVOKE function

Generally, the `(*planner).XXX()` functions are meant for use from within statement execution, for which there is always a txn (initialized by the executor).

>  I'm tempted to delete the check in UserHasAdminRole but unsure whether this implies that I'm using the API wrong. 

Yeah I'd recommend keeping `(*planner).UserHasAdminRole()` (notice: "planner") as a txn-only API.

But I agree it'd be better to check the admin role here. How to achieve that? It's a bit of a mess I agree (which is why I would like to propose some API refactor in v21.1)

What you can do in the meantime:

1. extract the `struct adminPrivilegeChecker` from `pkg/server` into some other package (`sql`?) and export it 
2. chang ethe code in `pkg/server` to use the now-exported API
3. use its `hasAdminRole()` method in your code here (notice how it uses an internal executor, for reason above)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54785#-:-MIJcCy700gfOuV_xuMl:b9sdqun)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @jordanlewis)

**Review by knz — COMMENTED** [review]
Hn I'm now realizing my previous suggested change would be on the hot path of every new txn. The change I just provided is just a little bit overweight.

Then I'd recommend creating a *variant* of `UserHasAdminRole` called `UserHasAdminRoleNoTxn` which asserts that *there is no txn defined yet* and only peeks at the role membership cache.


But what to do if the cache is not yet populated?

This is particularly tricky because the role membership cache looks up a descriptor for the `role_members` table. Without a txn, the descriptor cache is --- I think -- unused (or can't be used)? How does the descriptor even get out of KV before the txn is created?

Ideally, the membership of the current user to the admin role should be set as a flag on the session, initialized when the user logs in. This way we wouldn't even need to re-check role membership every time.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54785#-:-MIJey7tDHx35q00BusV:bqp6mq6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @jordanlewis)

___
*[pkg/sql/conn_fsm.go, line 440 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54785#-MI4ie-wB2tkqjTEc1c6:-MIJekXBCvW84vWbPGNV:b-h9kont) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ff38b240330f556d79c6ce11a6ed86a9aa6b1cf/pkg/sql/conn_fsm.go#L440)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I didn't put it in `execStmtInNoTxnState` because of what seems like two code paths for explicit vs implicit txns. Thanks for the `onTxnFinish` pointer.
</blockquote></details>

Is there a way to restrict this code to only work for *client* initiated SQL txns.
We don't want any limit to apply for internal txns (created by internal executor) otherwise the schema changer and bulk i/o will go haywire.

**Comment by jordanlewis** [comment]
The reason we want this setting is to help clients avoid overload. Certain people are interested in creating a maximum cap on the number of "active transactions" in their cluster, as a multiple of the vCPUs in each node. They want queries/transactions that exceed that limit to return an error, as a way of producing backpressure.

**Comment by knz** [comment]
> They want queries/transactions that exceed that limit to return an error, as a way of producing backpressure.

I am comfortable with that. I agree it would be a good value-add.

I do think however this mechanism must only limit txns initiated from a client connection. internal txns (generated when the internal executor gets a nil txn as argument) must not be limited in this way.

**Comment by asubiotto** [comment]
> I do think however this mechanism must only limit txns initiated from a client connection. internal txns (generated when the internal executor gets a nil txn as argument) must not be limited in this way.

Note that this is already implemented (through the `execType` field in the `transitionCtx` struct)

**Comment by andreimatei** [comment]
> The reason we want this setting is to help clients avoid overload. Certain people are interested in creating a maximum cap on the number of "active transactions" in their cluster, as a multiple of the vCPUs in each node. They want queries/transactions that exceed that limit to return an error, as a way of producing backpressure.

But, again, why would I set this active transactions limit differently than the connection limit? Why allow more connections than transactions? Conversely, setting this limit higher than the connections one is useless, right?

When you're talking about multiples of vCPUs, it seems to me like you want limits on concurrent queries not open transactions. I'd find that much more palatable, and would also help with the question above.

**Comment by jordanlewis** [comment]
> But, again, why would I set this active transactions limit differently than the connection limit? Why allow more connections than transactions? Conversely, setting this limit higher than the connections one is useless, right?

The reason that you would want to set a higher connection limit than transaction limit is that it is common and useful pattern to use a client-side connection pool that has more open connections than active connections. You want to make it possible for clients to have lots of connections open to the database, and make sure that not too many of them are active at once.

Yes, setting this limit higher than the connections one is completely useless.

> When you're talking about multiples of vCPUs, it seems to me like you want limits on concurrent queries not open transactions. I'd find that much more palatable, and would also help with the question above.

Yes, I agree. In general, having an "open transaction" feels like an better proxy for "currently working" than concurrent queries, to me. But maybe you're right and we ought to limit the number of concurrent active queries.

**Comment by andreimatei** [comment]
> You want to make it possible for clients to have lots of connections open to the database, and make sure that not too many of them are active at once.

Why? Just so that you have to prepare your statements on more connections than you need to?

**Comment by jordanlewis** [comment]
> Why? Just so that you have to prepare your statements on more connections than you need to?

To avoid the high cost of establishing a new connection. The cost includes preparing statements, as you say, as well as authentication. These things add up.

**Comment by andreimatei** [comment]
Do you want to allow more connections to be opened than can be used concurrently because you want to over-subscribe the database across multiple client applications in situations where the client apps don't go through a load balancer and instead talk directly to the db nodes?

Anyway, if we can all agree to avoid this conversation by switching to limiting queries instead of transactions, I'd be all for that.

**Comment by jordanlewis** [comment]
Even if client apps go through the load balancer, you have the same problem. Client side connection pools prefer to keep open many connections to the database for the reasons I listed. Most load balancers do not implement a connection pool of their own to multiplex the many input connections from clients to fewer output connections to the database. Some do (pgpool/pgbouncer), but they have other issues: session state is not preserved for clients.

I'm okay with switching this to be max open queries though. @asubiotto any complaints with this strategy? What about @a-entin, any concerns with using "active query" as the proxy for "active connection", and not "active transaction"?

**Comment by awoods187** [comment]
What's the difference in behavior with queries verse transactions? Aren't all queries implicit transactions or explicit transactions anyway?

**Comment by jordanlewis** [comment]
```
BEGIN
SELECT 1;
-- the app idles for 5 minutes
SELECT 5;
```

In this case, the "active transactions" heuristic would use that transaction as a point against the max active transactions, even though the transaction isn't doing anything. In the "active queries" model, during the idle 5 minutes, nothing will count against our limit.

**Comment by asubiotto** [comment]
I'm in favor of changing this to active queries, the implementation is a lot cleaner and it's nice to not have open inactive transactions contributing towards the limit. Made the change.

**Review by knz — APPROVED** [review]
:lgtm: lovely :100: 

> Reviewed 1 of 6 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54785#-:-MIP0-HlDbug1muIZmU7:b7zhlcr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @asubiotto, and @jordanlewis)

___
*[pkg/sql/conn_executor_exec.go, line 551 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54785#-MIP-j7i4MtD_6UI73KO:-MIP-j7i4MtD_6UI73KP:buyav9q) ([raw file](https://github.com/cockroachdb/cockroach/blob/11169ec04706bd9f8f38f3cd9114fa2d81cf5457/pkg/sql/conn_executor_exec.go#L551)):*
> ```Go
> 			if ex.metrics.ActiveQueries.Value() > maxActiveQueries {
> 				// There are too many active queries. Any users without an admin role
> 				// will be rejected.
> ```

Can you extend the comment to explain why you chose to only pull `HasAdminRole` "under" the metric check. Something about only paying the price of the lookup in the special case instead of the common case.
___
*[pkg/sql/exec_util.go, line 634 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54785#-MIP-uwcEocfLQbDme8B:-MIP-uwcEocfLQbDme8C:b-cu62qu) ([raw file](https://github.com/cockroachdb/cockroach/blob/11169ec04706bd9f8f38f3cd9114fa2d81cf5457/pkg/sql/exec_util.go#L634)):*
> ```Go
> 	MetaActiveSQLQueries = metric.Metadata{
> 		Name: "sql.query.active",
> 		Help: "Number of active SQL queries",
> ```

@jordanlewis @awoods187 the query count may be a good addition to the query stats charts in the UI.

**Comment by a-entin** [comment]
An open transaction that lingers for a long time is more likely than not being an application transaction scope bug failing to close thx txn. E.g. autocommit off and forgetting to commit, or even more commonly getting a warning and failing to rollback in error handling. While an open transaction maybe holding a large amounts of memory. I'll try to sketch a more holistic proposal after speaking with the customer today, need a bit of time.

**Review by asubiotto — COMMENTED** [review]
Added an open explicit txn + internal executor test for sanity.

> While an open transaction maybe holding large amounts of memory. The "right" handling of a lingering txn, albeit idling, is not that obvious. On a hunch, limiting the number of current transactions may not be a bad idea. I'll try to sketch a more holistic proposal after speaking with the customer today, need a bit of time.

The new version of this PR does not count idle txns towards the limit which I believe is the desired behavior in the case you're describing (misbehaved applications won't affect the limit). I think doing any more towards this problem is out of scope of this PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54785#-:-MIPH-xm5N1XYHlxlyvG:b-2w4z7g)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @asubiotto, @jordanlewis, and @knz)

___
*[pkg/sql/conn_executor_exec.go, line 551 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54785#-MIP-j7i4MtD_6UI73KO:-MIPGUoECrGXozLvh3XE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/11169ec04706bd9f8f38f3cd9114fa2d81cf5457/pkg/sql/conn_executor_exec.go#L551)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can you extend the comment to explain why you chose to only pull `HasAdminRole` "under" the metric check. Something about only paying the price of the lookup in the special case instead of the common case.
</blockquote></details>

Done.
___
*[pkg/sql/conn_fsm.go, line 440 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54785#-MI4ie-wB2tkqjTEc1c6:-MIPGUCH-4Lxhhvpz3EZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ff38b240330f556d79c6ce11a6ed86a9aa6b1cf/pkg/sql/conn_fsm.go#L440)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Is there a way to restrict this code to only work for *client* initiated SQL txns.
We don't want any limit to apply for internal txns (created by internal executor) otherwise the schema changer and bulk i/o will go haywire.

</blockquote></details>

Done.

**Comment by asubiotto** [comment]
Since the customer finds an open txn limit more useful, I opened another PR with an improved version of the initial version of this PR that moves the check outside of the state machine, allows all admin users through, and adds a metric for these implicit/explicit open txns: #55173

**Comment by asubiotto** [comment]
Closing as stale

**Pull request closed without merging**
