### PR TITLE
docs: fix backticks and comments in SQL code snippet of table lease RFC

### PR DESCRIPTION
**Pull request by richardwu**

### CODE REVIEW

**Review by lgo — COMMENTED** [review]
👏 awesome. LGTM.

**Review by lgo — APPROVED** [review]
👏 awesome. LGTM.

**Comment by vivekmenezes** [comment]
LGTM

**Comment by knz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19764#-:-Ky1irMM4ofaZn2co6BU:bnfp4nl)*

**Pull request merged**
