### PR TITLE
exec: cancel limit op's input when limit reached

### LINKED ISSUE #39029: exec: TestDrainingProcessorSwallowsUncertaintyError hangs with vectorized enabled
When vectorized execution is enabled by default, `TestDrainingProcessorSwallowsUncertaintyError` hangs until it times out. To reproduce, change the default `sql.defaults.experimental_vectorize` value to `on` in `exec_util.go` and then run
```
make test PKG=./pkg/sql/distsqlrun TESTS=TestDrainingProcessorSwallowsUncertaintyError TESTFLAGS='-v'
```

### PR DESCRIPTION
**Pull request by solongordon**
The TestDrainingProcessorSwallowsUncertaintyError unit test demonstrated
that if a limit operator was planned on top of an unordered
synchronizer, query execution could hang. This was because once the
limit was fulfilled, the limit operator would stop calling Next on its
input, so the unordered synchronizer ended up with stuck goroutines.

I fixed this by making the limit operator explicitly cancel its input's
context when the limit is reached.

Fixes #39029

Release note: None

### CODE REVIEW

**Comment by solongordon** [comment]
I don't feel very confident in this fix but I'm putting it up as a strawman. It feels like the context cancellation should happen further up the stack, but I don't have a good mental model of how cancellation is intended to work here. Would appreciate other thoughts.

**Review by yuzefovich — APPROVED** [review]
Yeah, this seems hacky to me too. Also, there might be other cases when an operator stops calling `Next` (i.e. it is `done`) before getting a zero-length batch from its input. But since it unblocks "streaming" setting, let's merge this now and figure out the correct cancellation mechanism later.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39080#-:-Lk_E41yCa_QWDe19_a1:brna2uh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @solongordon)

___
*[pkg/sql/exec/limit.go, line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39080#-Lk_DnP28J-oX6ShfQ7K:-Lk_DnP28J-oX6ShfQ7L:b-l5axa2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6675aebc89f8170c6eac8663d9795fe7bcb28cb/pkg/sql/exec/limit.go#L53)):*
> ```Go
> func (c *limitOp) Next(ctx context.Context) coldata.Batch {
> 	if c.done {
> 		c.inputCancelFunc()
> ```

[nit]: I'd leave a TODO here.

**Comment by yuzefovich** [comment]
Oh, and another suggestion is - if possible - to add a regression test.

**Comment by asubiotto** [comment]
Hmm, this is interesting. I guess the goroutines are blocked on writing to the batch channel. This approach works but I think that we skip the metadata step (writing this on my phone so haven't looked at the PR). I'm not too sure how to solve this problem properly. I would also merge to unblock and give it more thought.

**Comment by solongordon** [comment]
Yeah, the goroutines are blocked waiting on `s.readNextBatch` or `ctx.Done()`, here: https://github.com/cockroachdb/cockroach/blob/d170ae7ef5205239d650bfca892e2cb42f9c45bc/pkg/sql/exec/unorderedsynchronizer.go#L142-L153
I did a quick check that `DrainMeta` was still being called on the colBatchScan and it seemed to be, but I'll double-check.

**Review by jordanlewis — APPROVED** [review]
I'm also not exactly sure how we're meant to deal with cancellation. Perhaps it would be worth spending some time soon coming up with a principled approach.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39080#-:-LkaDtCy-wYetxXiDbs9:bufqkdh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @solongordon)

**Comment by asubiotto** [comment]
> I did a quick check that DrainMeta was still being called on the colBatchScan and it seemed to be, but I'll double-check.
My biggest worry is canceling a context that an inbox is using to hold an inbound stream active. If we do that before asking for metadata from the remote node, we won't be able to get any remote metadata. I think this is bad, but better than what we currently have.

**Comment by yuzefovich** [comment]
I ran into a similar problem when running logic test on up-to-date "streaming" setting branch on `overflow` logic test. Here are the relevant logs:
```
I190725 04:10:21.654369 1636 sql/distsqlrun/server.go:561  received SetupFlow request from n1 for flow 8785c8d1-9a6d-409a-9791-580e4748d533
I190725 04:10:21.654370 1805 sql/distsqlrun/server.go:561  received SetupFlow request from n1 for flow 8785c8d1-9a6d-409a-9791-580e4748d533
I190725 04:10:21.654732 1636 sql/distsqlrun/column_exec_setup.go:146  [n3] made op *distsqlrun.colBatchScan
I190725 04:10:21.654742 1805 sql/distsqlrun/column_exec_setup.go:146  [n2] made op *distsqlrun.colBatchScan
I190725 04:10:21.654792 1760 sql/exec/colrpc/outbox.go:111  [n3,streamID=1] Outbox Dialing 1
I190725 04:10:21.654846 1593 sql/exec/colrpc/outbox.go:111  [n2,streamID=0] Outbox Dialing 1
I190725 04:10:21.654858 1760 sql/exec/colrpc/outbox.go:133  [n3,streamID=1] Outbox sending header
I190725 04:10:21.654889 1593 sql/exec/colrpc/outbox.go:133  [n2,streamID=0] Outbox sending header
I190725 04:10:21.654938 1760 sql/exec/colrpc/outbox.go:146  [n3,streamID=1] Outbox starting normal operation
I190725 04:10:21.654953 1593 sql/exec/colrpc/outbox.go:146  [n2,streamID=0] Outbox starting normal operation
I190725 04:10:21.655001 1862 sql/distsqlrun/server.go:597  [n1] connecting inbound stream 8785c8d1/1
I190725 04:10:21.655004 1638 sql/distsqlrun/server.go:597  [n1] connecting inbound stream 8785c8d1/0
I190725 04:10:21.655271 1724 sql/distsqlrun/column_exec_setup.go:146  [n1,client=127.0.0.1:49792,user=root] made op *distsqlrun.colBatchScan
I190725 04:10:21.655293 1863 sql/exec/colrpc/outbox.go:268  [n3,streamID=1] Outbox received handshake: consumer_scheduled:false consumer_schedule_deadline:<seconds:1564027831 nanos:655018000 > version:23 min_accepted_version:23 
I190725 04:10:21.655305 1724 sql/distsqlrun/column_exec_setup.go:1068  [n1,client=127.0.0.1:49792,user=root] created Inbox with types [Int64]
I190725 04:10:21.655318 1724 sql/distsqlrun/column_exec_setup.go:1068  [n1,client=127.0.0.1:49792,user=root] created Inbox with types [Int64]
I190725 04:10:21.655328 1724 sql/distsqlrun/column_exec_setup.go:1115  [n1,client=127.0.0.1:49792,user=root] created *exec.UnorderedSynchronizer
[n1,client=127.0.0.1:49792,user=root] made op *exec.orderedAggregator
I190725 04:10:21.655644 1638 sql/distsqlrun/server.go:606  [n1] connected inbound stream 8785c8d1/0
I190725 04:10:21.655674 1862 sql/distsqlrun/server.go:606  [n1] connected inbound stream 8785c8d1/1
I190725 04:10:21.655676 1638 sql/exec/colrpc/inbox.go:168  [n1] Inbox 0xc0021938c0 handling stream
I190725 04:10:21.655692 1862 sql/exec/colrpc/inbox.go:168  [n1] Inbox 0xc002193a20 handling stream
I190725 04:10:21.655693 1638 sql/exec/colrpc/inbox.go:178  [n1] Inbox 0xc0021938c0 reader arrived
I190725 04:10:21.655703 1862 sql/exec/colrpc/inbox.go:178  [n1] Inbox 0xc002193a20 reader arrived
I190725 04:10:21.655714 1863 sql/exec/colrpc/outbox.go:268  [n3,streamID=1] Outbox received handshake: consumer_scheduled:true version:23 min_accepted_version:23 
I190725 04:10:21.655714 1785 sql/exec/colrpc/outbox.go:268  [n2,streamID=0] Outbox received handshake: consumer_scheduled:true version:23 min_accepted_version:23 
I190725 04:10:21.655894 1922 sql/exec/unorderedsynchronizer.go:144  [n1,client=127.0.0.1:49792,user=root] unordered synchronizer is about to block
I190725 04:10:21.656140 1760 sql/exec/colrpc/outbox.go:166  [n3,streamID=1] Outbox moved to draining
I190725 04:10:21.656225 1593 sql/exec/colrpc/outbox.go:166  [n2,streamID=0] Outbox moved to draining
I190725 04:10:21.656260 1809 sql/exec/unorderedsynchronizer.go:144  [n1,client=127.0.0.1:49792,user=root] unordered synchronizer is about to block
I190725 04:10:21.656435 1638 sql/exec/colrpc/inbox.go:189  [n1] Inbox 0xc0021938c0 exited stream handler
I190725 04:10:21.656652 1724 sql/exec/colrpc/inbox.go:286  [n1,client=127.0.0.1:49792,user=root] Inbox sending drain signal to Outbox
I190725 04:10:21.656675 1724 sql/exec/colrpc/inbox.go:292  [n1,client=127.0.0.1:49792,user=root] Inbox 0xc002193a20 is calling Recv
I190725 04:10:21.656952 1724 sql/exec/colrpc/inbox.go:294  [n1,client=127.0.0.1:49792,user=root] Inbox 0xc002193a20 received
err %!s(<nil>)
I190725 04:10:21.657012 1724 sql/exec/colrpc/inbox.go:292  [n1,client=127.0.0.1:49792,user=root] Inbox 0xc002193a20 is calling Recv
I190725 04:10:21.657024 1724 sql/exec/colrpc/inbox.go:294  [n1,client=127.0.0.1:49792,user=root] Inbox 0xc002193a20 received
err EOF
I190725 04:10:21.657103 1862 sql/exec/colrpc/inbox.go:189  [n1] Inbox 0xc002193a20 exited stream handler
```
Everything terminates gracefully except for the unordered synchronizer which remains blocked.
Here is my understanding of why:
- an aggregator encounters an overflow error and `panic`s with it
- the panic is caught by `materializer` which moves into `Draining` state
- all metadata sources are drained correctly
- but the unordered synchronizer was never notified in any way that it should exit, so it hangs forever in the lines Solon posted above.

We need some way to handle such a cancellation. I would now hold off on merging this PR.

**Comment by yuzefovich** [comment]
Filed #39092.

**Comment by solongordon** [comment]
Superseded by #39100.

**Pull request closed without merging**
