### PR TITLE
sql: Add support for drop table inside the new schema changer

### PR DESCRIPTION
**Pull request by fqazi**
sql: Initial support for DROP TABLE in new schema changer

  Previously, the logic for DROP table was completely imperative,
  which would make it hard to implement features like transactional
  schema changes in the future. To address this, this patch
  adds initial support for DROP TABLE with support for clearing
  out type back references and foreign key. Basic structures for
  tracking and adding secondary indexes are also introduced.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
I think you picked up an extra commit by accident. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65525#-:-Mae75-L89Ww9HLJ5aoG:b-irbp7w)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by fqazi** [comment]
Fixed. Should be fixed accidentally messed up a rebase.

**Review by ajwerner — COMMENTED** [review]
Here's a first pass, let me know what you think. 

> Reviewed 16 of 16 files at r1, 9 of 9 files at r2, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65525#-:-MbHQI9T00aWok1vkWU0:bc6gvjg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go, line 479 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65525#-MbHLdcoC82Pcp-4PJSH:-MbHLdcoC82Pcp-4PJSI:bvm9p70) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b7abfd27f160e99a6f3925eedfe3cd4f28c4d4a/pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go#L479)):*
> ```Go
> 		fks = table.TableDesc().InboundFKs
> 	}
> 	newFks := make([]descpb.ForeignKeyConstraint, 0, len(fks))
> ```

`len(fks)-1`?
___
*[pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go, line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65525#-MbHNcOx-AeQnfdQTuky:-MbHNcOx-AeQnfdQTukz:bloh57t) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3dd9c0be7c5b7b151f8bb2fd42a4145ae41c15b/pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go#L41)):*
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
> // MutableDescGetter encapsulates the logic to retrieve descriptors.
> // All retrieved descriptors are modified.
> type MutableDescGetter interface {
> 	GetMutableTypeByID(ctx context.Context, id descpb.ID) (*typedesc.Mutable, error)
> 	GetImmutableDatabaseByID(ctx context.Context, id descpb.ID) (catalog.DatabaseDescriptor, error)
> 	GetMutableTableByID(ctx context.Context, id descpb.ID) (*tabledesc.Mutable, error)
> 	AddDrainedName(id descpb.ID, nameInfo descpb.NameInfo)
> 	SubmitDrainedNames(ctx context.Context, codec keys.SQLCodec, ba *kv.Batch) error
> 	RemoveObjectComments(ctx context.Context, id descpb.ID) error
> }
> ```
</details>

This name is starting to feel pretty inappropriate. What if we have sub-interfaces:

```
type Catalog interface {
    DescriptorReader
    NamespaceWriter
    CommentWriter
}
```
___
*[pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go, line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65525#-MbHO5RE05zjKTtr7hyw:-MbHO5RE05zjKTtr7hyx:b-d5w88z) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3dd9c0be7c5b7b151f8bb2fd42a4145ae41c15b/pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go#L41)):*
> ```Go
> 	GetMutableTableByID(ctx context.Context, id descpb.ID) (*tabledesc.Mutable, error)
> 	AddDrainedName(id descpb.ID, nameInfo descpb.NameInfo)
> 	SubmitDrainedNames(ctx context.Context, codec keys.SQLCodec, ba *kv.Batch) error
> ```

In retrospect I feel pretty bad about exposing `*kv` or `codec` here. This comment doesn't need to be dealt with here but I think we're walking down a very bad path. The hope was that all of the dependencies of `scexec` could be mocked. I think that's a really important principle. Today some of the catalog stuff makes that somewhat hard. What I do feel strongly about is that we try to keep the dependencies inside of its subpackages narrow. Importantly, I never want us to be talking about `kv` construct. We're going to at some point want to be able to run this entire subsystem based on descriptors that just sit in memory. 

I'm actively working on knocking the `*kv.Txn` out of the various descriptor retrieval interfaces which should then make it straightforward to knock that out of the `scexec` package. 
___
*[pkg/sql/schemachanger/scop/mutation.go, line 103 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65525#-MbHMB6-6JEfePv2-mpR:-MbHMB609j4_hu1VUTyn:b-gnksus) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ebf6720393043f7cb39b16564bb9cb022ac2b2/pkg/sql/schemachanger/scop/mutation.go#L103)):*
> ```Go
> 	TableID     descpb.ID
> 	ColumnID    descpb.ColumnID
> 	SequenceIDs []descpb.ID
> ```

I'd prefer if this were a separate op to remove the back-reference. I'd go so far as to ask whether it's possible to make every op act on at most one descriptor. I would like that very much. 

I'll even go so far as to say that the descriptor retrieval we do at the top of each op is an eye-sore and my hope here has been to have the layer above actually fetch the descriptor for a given op. 
___
*[pkg/sql/schemachanger/scpb/elements.go, line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65525#-MbHK8Yz7YdRFzSSlZyx:-MbHK8Yz7YdRFzSSlZyy:byy6vbp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b7abfd27f160e99a6f3925eedfe3cd4f28c4d4a/pkg/sql/schemachanger/scpb/elements.go#L246)):*
> ```
> // DescriptorSet implements the Element interface.
> func (e *ForeignKey) DescriptorSet() []descpb.ID { return []descpb.ID{e.OriginID, e.ReferenceID} }
> ```

Rather than this, how do you feel about making a `ForeignKeyBackreference` an element on its own? Or, perhaps, `OutboundForeignKey` and `InboundForeignKey`? They should always end up being paired but each one is attached to just one descriptor. My sense is that keeping a 1:1 mapping between elements and descriptor IDs is valuable, so if we can avoid breaking that, I'd prefer it. 


Perhaps we should put up some declarative correctness rules like if you've got one `OutboundForeignKey` then you should have a parallel `InboundForeignKey` in the same direction. FWIW I do not thing they have the same lifecycle in terms of operations, so this decomposition is likely to be nice for planning purposes.
___
*[pkg/sql/schemachanger/scpb/scpb.proto, line 118 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65525#-MbHMhpcBEOqv3r7n-Cl:-MbHMhpcBEOqv3r7n-Cm:b-3a4eo1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ebf6720393043f7cb39b16564bb9cb022ac2b2/pkg/sql/schemachanger/scpb/scpb.proto#L118)):*
> ```protobuf
>   option (gogoproto.equal) = true;
>   uint32 table_id = 1 [(gogoproto.customname) = "TableID", (gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/sql/catalog/descpb.ID"];
>   uint32 owner_table_id = 2  [(gogoproto.customname) = "OwnerTableID", (gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/sql/catalog/descpb.ID"];
> ```

Would it be wild to have `SequenceOwnership` as an element?
As it stands, it's not obvious to me that. We'll be locking the table that's being upgraded in the back-reference. I think that's interesting and maybe fine. This brings up the whole "locking" thing that we've not formally specified yet. nx

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65525)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go, line 479 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65525#-MbHLdcoC82Pcp-4PJSH:-MbI--86EokzkAPAc60Y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b7abfd27f160e99a6f3925eedfe3cd4f28c4d4a/pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go#L479)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

`len(fks)-1`?
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go, line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65525#-MbHNcOx-AeQnfdQTuky:-MbHzomiBkPwEJVb16CC:bbb82ai) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3dd9c0be7c5b7b151f8bb2fd42a4145ae41c15b/pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go#L41)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> // MutableDescGetter encapsulates the logic to retrieve descriptors.
> // All retrieved descriptors are modified.
> type MutableDescGetter interface {
> 	GetMutableTypeByID(ctx context.Context, id descpb.ID) (*typedesc.Mutable, error)
> 	GetImmutableDatabaseByID(ctx context.Context, id descpb.ID) (catalog.DatabaseDescriptor, error)
> 	GetMutableTableByID(ctx context.Context, id descpb.ID) (*tabledesc.Mutable, error)
> 	AddDrainedName(id descpb.ID, nameInfo descpb.NameInfo)
> 	SubmitDrainedNames(ctx context.Context, codec keys.SQLCodec, ba *kv.Batch) error
> 	RemoveObjectComments(ctx context.Context, id descpb.ID) error
> }
> ```
This name is starting to feel pretty inappropriate. What if we have sub-interfaces:

```
type Catalog interface {
    DescriptorReader
    NamespaceWriter
    CommentWriter
}
```

</blockquote></details>

Renamed this, will rework the interfaces later.
___
*[pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go, line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65525#-MbHO5RE05zjKTtr7hyw:-MbHzqnH7XAVQmZA45DA:bn3ta3j) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3dd9c0be7c5b7b151f8bb2fd42a4145ae41c15b/pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go#L41)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

In retrospect I feel pretty bad about exposing `*kv` or `codec` here. This comment doesn't need to be dealt with here but I think we're walking down a very bad path. The hope was that all of the dependencies of `scexec` could be mocked. I think that's a really important principle. Today some of the catalog stuff makes that somewhat hard. What I do feel strongly about is that we try to keep the dependencies inside of its subpackages narrow. Importantly, I never want us to be talking about `kv` construct. We're going to at some point want to be able to run this entire subsystem based on descriptors that just sit in memory. 

I'm actively working on knocking the `*kv.Txn` out of the various descriptor retrieval interfaces which should then make it straightforward to knock that out of the `scexec` package. 
</blockquote></details>

Currently there isn't a clean path here. Maybe this should be popped out of the interface side, and let submit be on the implementation only?
___
*[pkg/sql/schemachanger/scpb/scpb.proto, line 118 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65525#-MbHMhpcBEOqv3r7n-Cl:-MbI-2QC3wf54LbQhRCz:b23oaxh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ebf6720393043f7cb39b16564bb9cb022ac2b2/pkg/sql/schemachanger/scpb/scpb.proto#L118)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Would it be wild to have `SequenceOwnership` as an element?
As it stands, it's not obvious to me that. We'll be locking the table that's being upgraded in the back-reference. I think that's interesting and maybe fine. This brings up the whole "locking" thing that we've not formally specified yet. nx
</blockquote></details>

Added one the way I have it setup is that drop SequenceOwner -> Sequence (DROPPING) being dropped and Table -> SequenceOwner. For alters, we will need to think a bit about how to handle that better.

**Review by ajwerner — COMMENTED** [review]
Looking good! Just minor things

> Reviewed 5 of 12 files at r5, 1 of 2 files at r9, 2 of 7 files at r11, 1 of 4 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65525#-:-MbbfGs67j8HUbEuCKnA:b5sr152)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[pkg/sql/schemachanger/scbuild/sequence.go, line 28 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/65525#-Mbbe_da3p2gYNax1-qK:-Mbbe_da3p2gYNax1-qL:bt0am6u) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e633f2261149e17e92b81dec563934da941b71/pkg/sql/schemachanger/scbuild/sequence.go#L28)):*
> ```Go
> // dropSequenceDesc builds targets and transformations using a descriptor.
> func (b *buildContext) dropSequenceDesc(
> 	ctx context.Context, table catalog.TableDescriptor, cascade tree.DropBehavior,
> ```

It's confusing to me that this is called `table`. I know it is a `TableDescriptor`, but that feels historical. Can we call the variable `sequence` or `seq` to clarify that it's the sequence being dropped and not some table involved in a back-reference?
___
*[pkg/sql/schemachanger/scbuild/sequence.go, line 70 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/65525#-MbbeVYJEuyj3QsZ_uOB:-MbbeVYJEuyj3QsZ_uOC:b-4rtir5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e633f2261149e17e92b81dec563934da941b71/pkg/sql/schemachanger/scbuild/sequence.go#L70)):*
> ```
> 	sequenceOwnedBy := &scpb.SequenceOwnedBy{
> 		TableID:      table.GetID(),
> 		OwnerTableID: table.GetSequenceOpts().SequenceOwner.OwnerTableID}
> ```
This should only be set if the sequence owner is non-zero, right?
___
*[pkg/sql/schemachanger/scbuild/table.go, line 579 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/65525#-MbbdlFK-ptxZyMDBPba:-MbbdlFK-ptxZyMDBPbb:b-c77cob) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e633f2261149e17e92b81dec563934da941b71/pkg/sql/schemachanger/scbuild/table.go#L579)):*
> ```Go
> func (b *buildContext) dropTable(ctx context.Context, n *tree.DropTable) {
> 	// Find the table first.
> 	for _, name := range n.Names {
> ```

How would you feel about making a helper for the body of this loop. It's a lot of code to be indented and I find myself forgetting I'm in a loop. 

More generally, I could see this logic chunked up a bit more into functions. It's hard to see the big picture when reading the code. 
___
*[pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go, line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65525#-MbHO5RE05zjKTtr7hyw:-MbIDOi42ecXAhORYH4d:b-v1m5xr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3dd9c0be7c5b7b151f8bb2fd42a4145ae41c15b/pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go#L41)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Currently there isn't a clean path here. Maybe this should be popped out of the interface side, and let submit be on the implementation only?
</blockquote></details>

Do we call `SubmitDrainedNames` or `SubmitAllJobs` in this package? Seems like it gets called only in `scexec`. I think we can just remove those methods from this interface. 
___
*[pkg/sql/schemachanger/scpb/scpb.proto, line 169 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/65525#-MbbdDrG98Vh1DvzsnAh:-MbbdDrG98Vh1DvzsnAi:bvakxll) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e633f2261149e17e92b81dec563934da941b71/pkg/sql/schemachanger/scpb/scpb.proto#L169)):*
> ```protobuf
> 
> message SequenceOwnedBy {
>   uint32 table_id = 1 [(gogoproto.customname) = "TableID", (gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/sql/catalog/descpb.ID"];
> ```

nit: `sequence_id`? I feel like the fact that it's a table is a crufty implementation detail.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 16 files at r4, 2 of 4 files at r13, 6 of 9 files at r15.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65525#-:-MbbrkExBEN3ewZI0c3G:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/schemachanger/scbuild/testdata/drop_table, line 41 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/65525#-MbbraMaCP-wFMd-a0Bs:-MbbraMaCP-wFMd-a0Bt:b-h0dgxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/45159232962b48253fbf8cb9292b6811afe7ddcb/pkg/sql/schemachanger/scbuild/testdata/drop_table#L41)):*
> ```
> DROP TABLE defaultdb.shipments CASCADE;
> ----
> - target:
> ```

These are hard to read. Let's do something about that (later).

**Comment by fqazi** [comment]
bors r=ajwerner

**Pull request merged**
