### PR TITLE
metric: Add Alert and Aggregation Rule interface.

### PR DESCRIPTION
**Pull request by rimadeodhar**
This PR contains two commits. The first one updates
the vendor submodule to update the prometheus 
version to a more recent one.
The second commit outlines the interfaces for Alert and 
Aggregation rule. These interfaces will be used
by a new endpoint which will expose these rules in a YAML
format. This endpoint can be used by our end users to
configure alerts/monitoring for CockroachDB clusters.

Release note: None

### CODE REVIEW

**Review by abarganier — COMMENTED** [review]
Nice work, great to see this work being kicked off! Just a couple small comments/questions

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70773#-:-Mm-KVY-7U7IQuZNXJWU:b-4pih7v)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @rimadeodhar)

___
*[pkg/util/metric/rule.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70773#-Mm-J9Px5_sZ9EIE1eWt:-Mm-J9Px5_sZ9EIE1eWu:bewn12e) ([raw file](https://github.com/cockroachdb/cockroach/blob/af31085b425da2630a22c4acdacc283b5acce783/pkg/util/metric/rule.go#L31)):*
> ```
> 	// IsKV returns true if the metrics involved in the
> 	// rule are for the KV layer.
> 	IsKV() bool
> ```
Will there ever be more nuance required here? e.g. storage layer vs. KV layer vs. SQL layer? Just wondering if a boolean will last the test of time.
___
*[pkg/util/metric/rule.go, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70773#-Mm-Jri05R_Sg-eFoZTU:-Mm-Jri05R_Sg-eFoZTV:bqyyozc) ([raw file](https://github.com/cockroachdb/cockroach/blob/af31085b425da2630a22c4acdacc283b5acce783/pkg/util/metric/rule.go#L64)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
> func NewAlertingRule(
> 	name string,
> 	expr string,
> 	annotations []LabelPair,
> 	labels []LabelPair,
> 	recommendedHoldDuration time.Duration,
> 	help string,
> 	isKV bool,
> ) (*AlertingRule, error) {
> ```
</details>

nit: can we add some comments here? We should probably specify that `expr` will be parsed & validated.

Same for `NewAggregationRule` below.
___
*[pkg/util/metric/rule.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70773#-Mm-K9gq5VH0Um3t0paN:-Mm-K9gq5VH0Um3t0paO:b-96v8bk) ([raw file](https://github.com/cockroachdb/cockroach/blob/af31085b425da2630a22c4acdacc283b5acce783/pkg/util/metric/rule.go#L80)):*
> ```
> 		help:                    help,
> ```
nit: should we validate that this isn't an empty string? Same for in `NewAggregationRule`. Not sure if we want to enforce this as always being present.

**Review by rimadeodhar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70773)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier)

___
*[pkg/util/metric/rule.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70773#-Mm-J9Px5_sZ9EIE1eWt:-Mm4MuyfBSCAOdp70HJz:b-aco7gv) ([raw file](https://github.com/cockroachdb/cockroach/blob/af31085b425da2630a22c4acdacc283b5acce783/pkg/util/metric/rule.go#L31)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

> ```
> 	// IsKV returns true if the metrics involved in the
> 	// rule are for the KV layer.
> 	IsKV() bool
> ```
Will there ever be more nuance required here? e.g. storage layer vs. KV layer vs. SQL layer? Just wondering if a boolean will last the test of time.
</blockquote></details>

I don't think so. This distinction is mainly for multitenant architecture as we want to create a boundary between KV metrics and SQL metrics. So it makes sense to extend that boundary to alerts too so as to avoid exposing alerts that are based on KV metrics. I'm not sure if we might need more such boundaries in the future but I feel it will be easy enough to extend it in the future should the need arise. 
___
*[pkg/util/metric/rule.go, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70773#-Mm-Jri05R_Sg-eFoZTU:-Mm4NLziBYvdR5vySuJa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/af31085b425da2630a22c4acdacc283b5acce783/pkg/util/metric/rule.go#L64)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

> ```
> func NewAlertingRule(
> 	name string,
> 	expr string,
> 	annotations []LabelPair,
> 	labels []LabelPair,
> 	recommendedHoldDuration time.Duration,
> 	help string,
> 	isKV bool,
> ) (*AlertingRule, error) {
> ```
nit: can we add some comments here? We should probably specify that `expr` will be parsed & validated.

Same for `NewAggregationRule` below.
</blockquote></details>

Done.
___
*[pkg/util/metric/rule.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70773#-Mm-K9gq5VH0Um3t0paN:-Mm4NNKN7iWiwA8SMPlR:b-blmpfz) ([raw file](https://github.com/cockroachdb/cockroach/blob/af31085b425da2630a22c4acdacc283b5acce783/pkg/util/metric/rule.go#L80)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

> ```
> 		help:                    help,
> ```
nit: should we validate that this isn't an empty string? Same for in `NewAggregationRule`. Not sure if we want to enforce this as always being present. 
</blockquote></details>

Not really. This field will be used to add a comment about the rule and is meant to be optional.

**Review by abarganier — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70773#-:-Mm4hZB6EN1wbVm1xBoJ:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier and @rimadeodhar)

___
*[pkg/util/metric/rule.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70773#-Mm-J9Px5_sZ9EIE1eWt:-Mm4hGe_395CsETv7JVb:b-yyl2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/af31085b425da2630a22c4acdacc283b5acce783/pkg/util/metric/rule.go#L31)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

I don't think so. This distinction is mainly for multitenant architecture as we want to create a boundary between KV metrics and SQL metrics. So it makes sense to extend that boundary to alerts too so as to avoid exposing alerts that are based on KV metrics. I'm not sure if we might need more such boundaries in the future but I feel it will be easy enough to extend it in the future should the need arise. 
</blockquote></details>

SGTM, thanks for clarifying! 
___
*[pkg/util/metric/rule.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70773#-Mm-K9gq5VH0Um3t0paN:-Mm4hQYu9sVWpC-YC0qq:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/af31085b425da2630a22c4acdacc283b5acce783/pkg/util/metric/rule.go#L80)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Not really. This field will be used to add a comment about the rule and is meant to be optional.
</blockquote></details>

Ack.

**Comment by RaduBerinde** [comment]
Hi @rimadeodhar - I am working to backport roachprod changes to older release branches. I can't merge the vendor change, I will need to recreate it. I was wondering if you remember exactly what package(s) you updated - was it just `github.com/prometheus/client_golang` ?

**Comment by rimadeodhar** [comment]
Hi @RaduBerinde, it was the `github.com/prometheus/prometheus@37468d88dce85` package. Let me know if you need any help with the backport.

**Comment by RaduBerinde** [comment]
Thanks! I'm having some problems with the zipkin dependency but I'll figure it out.

**Pull request merged**
