### PR TITLE
pgwire/pgerror: Generate all errcodes from Postgres

### PR DESCRIPTION
**Pull request by nvb**
This change introduces a new `sql/pgwire/pgerror` package to store all
constant Postgres error codes. It was created from Postgres'
`errcodes.txt`.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6756)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> #### pgwire/pgerror: Generate all errcodes from Postgres
> 
> This change introduces a new `sql/pgwire/pgerror` package to store all
> 
> constant Postgres error codes. It was created from Postgres'
> 
> `errcodes.txt`.
> 
> 
> </details>


---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/pgwire/pgerror/codes.go, line 20 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756#-KI-OVu0VMJWdoTvhZMr:-KI-OVu0VMJWdoTvhZMs:383749307) ([raw file](https://github.com/cockroachdb/cockroach/blob/04a908f663c55090ccb8ec1c9c9b151a6e1145b1/sql/pgwire/pgerror/codes.go#L20)):*
> ```Go
> 
> // PG error codes from:
> // http://www.postgresql.org/docs/9.5/static/errcodes-appendix.html
> ```

can you include generation instructions here? even better if you include a script. also, you're gonna need to whitelist this with the linters.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756#-:-KI-Oe5TeHuzbsKWREDQ:1417088721)*

**Comment by nvanbenschoten** [comment]
TFTR

<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> :lgtm:</details>


---

Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/pgwire/pgerror/codes.go, line 20 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756#-KI-OVu0VMJWdoTvhZMr:-KI-RFkHJfggCqDKAPND:799633237) ([raw file](https://github.com/cockroachdb/cockroach/blob/04a908f663c55090ccb8ec1c9c9b151a6e1145b1/sql/pgwire/pgerror/codes.go#L20)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can you include generation instructions here? even better if you include a script. also, you're gonna need to whitelist this with the linters.</details>
I began writing a script, but there were a few edge cases that made it not straightforward and I figured it would be deemed overkill. The codes aren't expected to change, and hardcoding it is common in [some](https://github.com/lib/pq/blob/master/error.go#L75) drivers. I'll revive the script that I had hooked into `go:generate` if you disagree.

Also, PTAL with the linter changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756#-:-KI-ThG916zYi8xtQlwa:677071605)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/pgwire/pgerror/codes.go, line 20 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756#-KI-OVu0VMJWdoTvhZMr:-KI-X6-rbMIvTGhjhm1N:725386137) ([raw file](https://github.com/cockroachdb/cockroach/blob/04a908f663c55090ccb8ec1c9c9b151a6e1145b1/sql/pgwire/pgerror/codes.go#L20)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> I began writing a script, but there were a few edge cases that made it not straightforward and I figured it would be deemed overkill. The codes aren't expected to change, and hardcoding it is common in [some](https://github.com/lib/pq/blob/master/error.go#L75) drivers. I'll revive the script that I had hooked into `go:generate` if you disagree.
> 
> Also, PTAL with the linter changes.</details>
Don't hook it in to go generate, but still include it. Do you really want the next person to have to figure this out from scratch?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/pgwire/pgerror/codes.go, line 20 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756#-KI-OVu0VMJWdoTvhZMr:-KI-_QNZ3nIgPO-3tAax:1142453675) ([raw file](https://github.com/cockroachdb/cockroach/blob/04a908f663c55090ccb8ec1c9c9b151a6e1145b1/sql/pgwire/pgerror/codes.go#L20)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Don't hook it in to go generate, but still include it. Do you really want the next person to have to figure this out from scratch?</details>
My point is, what next person? These codes are highly unlikely to change.

And I dont think it's worth the effort to make a script that encompasses all of the manual tweaks I needed to make (eg. Prefix certain codes with their class name to prevent duplicates, change a few names to pass Golint, strip double "Errors" from the end of a few codes, capitalize initialisms and acronyms).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/pgwire/pgerror/codes.go, line 20 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756#-KI-OVu0VMJWdoTvhZMr:-KI3N8wz0UAA-2NLwzpX:825152010) ([raw file](https://github.com/cockroachdb/cockroach/blob/04a908f663c55090ccb8ec1c9c9b151a6e1145b1/sql/pgwire/pgerror/codes.go#L20)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> My point is, what next person? These codes are highly unlikely to change.
> 
> And I dont think it's worth the effort to make a script that encompasses all of the manual tweaks I needed to make (eg. Prefix certain codes with their class name to prevent duplicates, change a few names to pass Golint, strip double "Errors" from the end of a few codes, capitalize initialisms and acronyms).
</details>
The script doesn't need to be perfect - it just needs to serve as a breadcrumb for the next person. Even if unlikely, it's possible that someone will need to update this. Literally anything is better than nothing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756)*

**Comment by andreimatei** [comment]
LGTM

<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> TFTR
</details>


---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/errors.go, line 40 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756#-KI3v2PEud-ixVU-Epkf:-KI3v2PEud-ixVU-Epkg:-1344183066) ([raw file](https://github.com/cockroachdb/cockroach/blob/04a908f663c55090ccb8ec1c9c9b151a6e1145b1/sql/errors.go#L40)):*
> ```Go
> 	// CodeTransactionCommittedError signals that the SQL txn is in the
> 	// COMMIT_WAIT state and a COMMIT statement should be issued.
> 	CodeTransactionCommittedError string = "CR001"
> ```

maybe take the chance to include TODOs for the two codes that you think work for both these errors

---

*[sql/pgwire/pgerror/codes.go, line 20 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756#-KI-OVu0VMJWdoTvhZMr:-KI3un0yCWnAEsub_5Qk:1110217308) ([raw file](https://github.com/cockroachdb/cockroach/blob/04a908f663c55090ccb8ec1c9c9b151a6e1145b1/sql/pgwire/pgerror/codes.go#L20)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> The script doesn't need to be perfect - it just needs to serve as a breadcrumb for the next person. Even if unlikely, it's possible that someone will need to update this. Literally anything is better than nothing.
</details>
I guess you can put the script in a gist and include a link

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756#-:-KI3vA_2xDIJiPLig68c:676834233)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/pgwire/pgerror/codes.go, line 20 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756#-KI-OVu0VMJWdoTvhZMr:-KI3vTUtNDPBeZWl87to:-1355612866) ([raw file](https://github.com/cockroachdb/cockroach/blob/04a908f663c55090ccb8ec1c9c9b151a6e1145b1/sql/pgwire/pgerror/codes.go#L20)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> I guess you can put the script in a gist and include a link
</details>
please no. let's not make it ephemeral.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/pgwire/pgerror/codes.go, line 20 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756#-KI-OVu0VMJWdoTvhZMr:-KI3wxW9nbzFRq2Z9AVg:-1760320732) ([raw file](https://github.com/cockroachdb/cockroach/blob/04a908f663c55090ccb8ec1c9c9b151a6e1145b1/sql/pgwire/pgerror/codes.go#L20)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> please no. let's not make it ephemeral.
</details>
well the repo is probably also no place for broken and dead code

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756)*

**Comment by nvanbenschoten** [comment]
TFTR!

<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> LGTM
</details>


---

Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/errors.go, line 40 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756#-KI3v2PEud-ixVU-Epkf:-KI4D3kuV_hwpXkjojHY:-494564639) ([raw file](https://github.com/cockroachdb/cockroach/blob/04a908f663c55090ccb8ec1c9c9b151a6e1145b1/sql/errors.go#L40)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> maybe take the chance to include TODOs for the two codes that you think work for both these errors
</details>
I was going to follow up this PR with that change.

---

*[sql/pgwire/pgerror/codes.go, line 20 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756#-KI-OVu0VMJWdoTvhZMr:-KI4D7GMcsHtNkDp2YR7:668824133) ([raw file](https://github.com/cockroachdb/cockroach/blob/04a908f663c55090ccb8ec1c9c9b151a6e1145b1/sql/pgwire/pgerror/codes.go#L20)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> well the repo is probably also no place for broken and dead code
</details>
Added a script. It's not broken, but I noted that a bit of manual tweaking is required

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756#-:-KI4D6Acmf6xKAjsdm42:-485616692)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/pgwire/pgerror/errcodes.txt, line 5 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756#-KI4JXd9e66sjneAIbLP:-KI4JXd9e66sjneAIbLQ:2071119197) ([raw file](https://github.com/cockroachdb/cockroach/blob/360be6e12ff74050934cc7d388ea2c444035a5ea/sql/pgwire/pgerror/errcodes.txt#L5)):*
> ```
> #      PostgreSQL error codes
> #
> # Copyright (c) 2003-2016, PostgreSQL Global Development Group
> ```

i don't think you need to check this file in (i'd have your script take a path to this file as an argument), but i'll leave that decision to you.

---

*[sql/pgwire/pgerror/generate.sh, line 1 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756#-KI4JfZF42L3u0mPHP8O:-KI4JfZF42L3u0mPHP8P:-1555179354) ([raw file](https://github.com/cockroachdb/cockroach/blob/360be6e12ff74050934cc7d388ea2c444035a5ea/sql/pgwire/pgerror/generate.sh#L1)):*
> ```Shell
> #!/bin/bash
> ```

either /bin/sh or /usr/bin/env bash

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/pgwire/pgerror/codes.go, line 20 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756#-KI-OVu0VMJWdoTvhZMr:-KI4JnWyhVmLn9O3LHz1:-993876366) ([raw file](https://github.com/cockroachdb/cockroach/blob/04a908f663c55090ccb8ec1c9c9b151a6e1145b1/sql/pgwire/pgerror/codes.go#L20)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Added a script. It's not broken, but I noted that a bit of manual tweaking is required
</details>
This file should reference that script in a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756)*

**Comment by nvanbenschoten** [comment]
Review status: 4 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/pgwire/pgerror/codes.go, line 20 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756#-KI-OVu0VMJWdoTvhZMr:-KI4UBwPSOMm8jbG6E7r:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/04a908f663c55090ccb8ec1c9c9b151a6e1145b1/sql/pgwire/pgerror/codes.go#L20)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> This file should reference that script in a comment.
</details>
Done.

---

*[sql/pgwire/pgerror/errcodes.txt, line 5 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756#-KI4JXd9e66sjneAIbLP:-KI4TVQ9ay-lX02Cm6zv:-508647648) ([raw file](https://github.com/cockroachdb/cockroach/blob/360be6e12ff74050934cc7d388ea2c444035a5ea/sql/pgwire/pgerror/errcodes.txt#L5)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> i don't think you need to check this file in (i'd have your script take a path to this file as an argument), but i'll leave that decision to you.
</details>
I kind of like having it here. It makes it clear where the generated variables came from. 

---

*[sql/pgwire/pgerror/generate.sh, line 1 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756#-KI4JfZF42L3u0mPHP8O:-KI4THpqTtJgnnCMkqvp:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/360be6e12ff74050934cc7d388ea2c444035a5ea/sql/pgwire/pgerror/generate.sh#L1)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> either /bin/sh or /usr/bin/env bash
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/pgwire/pgerror/codes.go, line 23 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756#-KI4dHlDRNNh_2boWfH8:-KI4dHlDRNNh_2boWfH9:-1915453153) ([raw file](https://github.com/cockroachdb/cockroach/blob/588d70589bb771996da404453293a812c2dea257/sql/pgwire/pgerror/codes.go#L23)):*
> ```Go
> //
> // The error definitions were generated using the generate.sh script,
> // with a bit of manual tweaking performed afterwords.
> ```

afterwards. do you even speak english?

---

*[sql/pgwire/pgerror/errcodes.txt, line 5 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756#-KI4JXd9e66sjneAIbLP:-KI4dMNrA8Goior3Kb6Y:-1023596854) ([raw file](https://github.com/cockroachdb/cockroach/blob/360be6e12ff74050934cc7d388ea2c444035a5ea/sql/pgwire/pgerror/errcodes.txt#L5)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> I kind of like having it here. It makes it clear where the generated variables came from. 
</details>
Yes, but not where this file came from!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/pgwire/pgerror/codes.go, line 23 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756#-KI4dHlDRNNh_2boWfH8:-KI4f5SbSb3tD4Tyy5iz:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/588d70589bb771996da404453293a812c2dea257/sql/pgwire/pgerror/codes.go#L23)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> afterwards. do you even speak english?
</details>
Done.

---

*[sql/pgwire/pgerror/errcodes.txt, line 5 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756#-KI4JXd9e66sjneAIbLP:-KI4faH3iXk3DSBvCbZP:-698231926) ([raw file](https://github.com/cockroachdb/cockroach/blob/360be6e12ff74050934cc7d388ea2c444035a5ea/sql/pgwire/pgerror/errcodes.txt#L5)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Yes, but not where this file came from!
</details>
Better?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756)*

**Comment by tamird** [comment]
:lgtm:

<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> TFTR!
</details>


---

Reviewed 1 of 2 files at r3, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6756#-:-KI4hLA5hdR2FmqyXWcU:1417088721)*

**Pull request merged**
