### PR TITLE
server: support protobuf-over-HTTP

### PR DESCRIPTION
**Pull request by tamird**
---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6754)

### CODE REVIEW

**Comment by tamird** [comment]
@maxlang @mrtracy this is ready for a look!

**Comment by tamird** [comment]
Turns out the tests were broken because isomorphic-fetch is no good - node and browsers are different, who knew!

This now only changes server code, so should be good to go.

**Comment by d4l3k** [comment]
Reviewed 3 of 4 files at r3, 7 of 7 files at r6.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[server/status_test.go, line 86 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6754#-KI91wj34AtTv3e0ZxC0:-KI91wj4MKmlf_1UvgFf:1361476610) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbb0756a0c44e35c238da810ed9b48fe09282260/server/status_test.go#L86)):*
> ```Go
> 
> 	var nodes NodesResponse
> 	if err := getRequestProto(t, s, statusNodesPrefix, &nodes); err != nil {
> ```

Consider adding a check that `len(nodes.Nodes) > 0` since that's what the previous code was indirectly testing by checking for `"nodes":`.

---

*[server/status_test.go, line 95 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6754#-KI92JJucRTnLBEkwf-o:-KI92JJucRTnLBEkwf-p:-1018131791) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbb0756a0c44e35c238da810ed9b48fe09282260/server/status_test.go#L95)):*
> ```Go
> 		"/_status/details/" + strconv.FormatUint(uint64(nodeID), 10),
> 	} {
> 		var details DetailsResponse
> ```

Any reason you decided to get rid of the multiple content type checks? Though, YAML seems kind of useless to check for. 

Maybe should check for raw Proto and JSON formats?

---

*[ui/next/Makefile, line 33 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6754#-KI95GVHrpIqRB9OvSsX:-KI95GVHrpIqRB9OvSsY:-794401902) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbb0756a0c44e35c238da810ed9b48fe09282260/ui/next/Makefile#L33)):*
> ```Makefile
> 
> .PHONY: lint
> lint: $(GENERATED) npm.installed typings.installed
> ```

Where is `GENERATED` defined? Or is that internal to Make?

---

*[util/jsonpb_marshal.go, line 30 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6754#-KI9043DqEe64dkAaqm9:-KI9043DqEe64dkAaqmA:-505464820) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbb0756a0c44e35c238da810ed9b48fe09282260/util/jsonpb_marshal.go#L30)):*
> ```Go
> var _ gwruntime.Marshaler = (*JSONPb)(nil)
> 
> // JSONPb is a gwruntime.Marshaler that uses github.com/gogo/protobuf/jsonpb.
> ```

Doesn't this make it harder for people to use this type since they have to go elsewhere for docs about it?

---

*[util/jsonpb_marshal.go, line 31 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6754#-KI90fJV8Qc2lvbwHWLM:-KI90fJV8Qc2lvbwHWLN:1705004094) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbb0756a0c44e35c238da810ed9b48fe09282260/util/jsonpb_marshal.go#L31)):*
> ```Go
> 
> // JSONPb is a gwruntime.Marshaler that uses github.com/gogo/protobuf/jsonpb.
> type JSONPb jsonpb.Marshaler
> ```

How does this differ from https://godoc.org/github.com/gengo/grpc-gateway/runtime#JSONPb ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6754)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[server/status_test.go, line 86 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6754#-KI91wj34AtTv3e0ZxC0:-KIA6CVvz35KunJlaPys:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbb0756a0c44e35c238da810ed9b48fe09282260/server/status_test.go#L86)):*
<details><summary><i>Previously, d4l3k (Tristan Rice) wrote…</i></summary>
> Consider adding a check that `len(nodes.Nodes) > 0` since that's what the previous code was indirectly testing by checking for `"nodes":`.
</details>
Done.

---

*[server/status_test.go, line 95 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6754#-KI92JJucRTnLBEkwf-o:-KIA6E-LgWTkc73aXYnv:-1681687776) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbb0756a0c44e35c238da810ed9b48fe09282260/server/status_test.go#L95)):*
<details><summary><i>Previously, d4l3k (Tristan Rice) wrote…</i></summary>
> Any reason you decided to get rid of the multiple content type checks? Though, YAML seems kind of useless to check for. 
> 
> Maybe should check for raw Proto and JSON formats?
</details>
Yeah, I considered adding the proto handling, but that seems to be testing grpc-gateway? Anyway, I'd like to do that for all the methods centrally once they're all ported over to grpc-gateway.

YAML is useless, as you say.

---

*[ui/next/Makefile, line 33 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6754#-KI95GVHrpIqRB9OvSsX:-KIA5Yn6owsovONNAkkM:-44188342) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbb0756a0c44e35c238da810ed9b48fe09282260/ui/next/Makefile#L33)):*
<details><summary><i>Previously, d4l3k (Tristan Rice) wrote…</i></summary>
> Where is `GENERATED` defined? Or is that internal to Make?
</details>
Ah, it was removed. Removed this.

---

*[util/jsonpb_marshal.go, line 30 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6754#-KI9043DqEe64dkAaqm9:-KIA6SaB9prOAGhA4s0U:-1956427603) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbb0756a0c44e35c238da810ed9b48fe09282260/util/jsonpb_marshal.go#L30)):*
<details><summary><i>Previously, d4l3k (Tristan Rice) wrote…</i></summary>
> Doesn't this make it harder for people to use this type since they have to go elsewhere for docs about it?
</details>
Not sure what you mean; in your sentence, what is "this"? The docs are reachable via go-to-definition from just two lines up from here.

---

*[util/jsonpb_marshal.go, line 31 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6754#-KI90fJV8Qc2lvbwHWLM:-KIA5iB6FNdrloGC89n-:926716402) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbb0756a0c44e35c238da810ed9b48fe09282260/util/jsonpb_marshal.go#L31)):*
<details><summary><i>Previously, d4l3k (Tristan Rice) wrote…</i></summary>
> How does this differ from https://godoc.org/github.com/gengo/grpc-gateway/runtime#JSONPb ?
</details>
Upstream uses `golang/protobuf/jsonpb`; this uses `gogo/protobuf/jsonpb`. The former doesn't correctly handle protobuf structs generated by the latter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6754)*

**Comment by d4l3k** [comment]
Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[util/jsonpb_marshal.go, line 30 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6754#-KI9043DqEe64dkAaqm9:-KIDeOTEDQ3kZAQsFKnW:-1024557721) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbb0756a0c44e35c238da810ed9b48fe09282260/util/jsonpb_marshal.go#L30)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Not sure what you mean; in your sentence, what is "this"? The docs are reachable via go-to-definition from just two lines up from here.
</details>
Fair enough.

---

*[util/jsonpb_marshal.go, line 31 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6754#-KI90fJV8Qc2lvbwHWLM:-KIDeS-ZdwXofJlK0ZUp:1826585197) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbb0756a0c44e35c238da810ed9b48fe09282260/util/jsonpb_marshal.go#L31)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Upstream uses `golang/protobuf/jsonpb`; this uses `gogo/protobuf/jsonpb`. The former doesn't correctly handle protobuf structs generated by the latter.
</details>
Make sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6754)*

**Comment by d4l3k** [comment]
:lgtm:

<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Turns out the tests were broken because isomorphic-fetch is no good - node and browsers are different, who knew!
> 
> 
> 
> This now only changes server code, so should be good to go.
</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6754#-:-KIDeyfHiy0LczlHLSrH:1417088721)*

**Comment by maxlang** [comment]
@tamird Another option for getting the tests to work in the short term could be using proxyquire to mock out/modify the protos.

**Pull request merged**
