### PR TITLE
roachprod: add cost estimation to list (gcp only)

### PR DESCRIPTION
**Pull request by jordanlewis**
This commit adds cost estimation to roachprod list. It currently supports GCP only.

Example image:
image

cc @udnay @kenliu-crl @srosenberg 

Epic: None
Release note: None

### CODE REVIEW

**Review by srosenberg — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98955)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @jordanlewis)

___
*[`pkg/roachprod/vm/gce/gcloud.go` line 1015 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98955#-NR4cB3IE-3EGDU2ojav:-NR4cB3IE-3EGDU2ojaw:b-za2ic3) ([raw file](https://github.com/cockroachdb/cockroach/blob/685d1617778f7527411830ac83ba4f76e8249e23/pkg/roachprod/vm/gce/gcloud.go#L1015)):*
> ```Go
> }
> 
> func populateCostPerHour(vms vm.List) error {
> ```

It would be nice to describe the assumptions. E.g., boot disk and egress cost (based on VM locations) are not tracked. Also, this doesn't factor in sustained usage, or any other type of discount, right?
___
*[`pkg/roachprod/vm/gce/gcloud.go` line 1033 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98955#-NR4aDtN1TNB16z5cH2_:-NR4aDtN1TNB16z5cH2a:b-qm8f6) ([raw file](https://github.com/cockroachdb/cockroach/blob/685d1617778f7527411830ac83ba4f76e8249e23/pkg/roachprod/vm/gce/gcloud.go#L1033)):*
> ```Go
> 	// Workload estimation service can handle 100 workloads at a time, so page
> 	// 100 VMs at a time.
> 	for len(vms) > 0 {
> ```

Why not bail immediately when `vms` is empty? i.e., it's a precondition failure. There isn't much to do in that case.
___
*[`pkg/roachprod/vm/gce/gcloud.go` line 1082 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98955#-NR4bG18CYha_ASwN7ez:-NR4bG18CYha_ASwN7f-:bh6zv2z) ([raw file](https://github.com/cockroachdb/cockroach/blob/685d1617778f7527411830ac83ba4f76e8249e23/pkg/roachprod/vm/gce/gcloud.go#L1082)):*
> ```Go
> 			scenario.CostScenario.Workloads = append(scenario.CostScenario.Workloads, &workload)
> 		}
> 		estimate, err := beta.EstimateCostScenario(&scenario).Do()
> ```

Do we have a sense of latency for these API calls? I assume they are on the order of 100ms? Also, the API rate limiting is probably a non-issue, but good to confirm.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98955)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @srosenberg)

___
*[`pkg/roachprod/vm/gce/gcloud.go` line 1015 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98955#-NR4cB3IE-3EGDU2ojav:-NR6VqZz2jUfO5_Y0n8q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/685d1617778f7527411830ac83ba4f76e8249e23/pkg/roachprod/vm/gce/gcloud.go#L1015)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

It would be nice to describe the assumptions. E.g., boot disk and egress cost (based on VM locations) are not tracked. Also, this doesn't factor in sustained usage, or any other type of discount, right?
</blockquote></details>

Done.
___
*[`pkg/roachprod/vm/gce/gcloud.go` line 1033 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98955#-NR4aDtN1TNB16z5cH2_:-NR6UgxwETJGm72fLbH0:bgctb7k) ([raw file](https://github.com/cockroachdb/cockroach/blob/685d1617778f7527411830ac83ba4f76e8249e23/pkg/roachprod/vm/gce/gcloud.go#L1033)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Why not bail immediately when `vms` is empty? i.e., it's a precondition failure. There isn't much to do in that case.
</blockquote></details>

I'm using it as a loop condition, vms is shrunk every time we page through.
___
*[`pkg/roachprod/vm/gce/gcloud.go` line 1082 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98955#-NR4bG18CYha_ASwN7ez:-NR6UsQ64kWsJtjS_Xm1:b-5b67jh) ([raw file](https://github.com/cockroachdb/cockroach/blob/685d1617778f7527411830ac83ba4f76e8249e23/pkg/roachprod/vm/gce/gcloud.go#L1082)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Do we have a sense of latency for these API calls? I assume they are on the order of 100ms? Also, the API rate limiting is probably a non-issue, but good to confirm.
</blockquote></details>

Unfortunately it's quite slow, more like a second and a half on average. I haven't seen any rate limiting.

**Review by srosenberg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98955)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @jordanlewis)

___
*[`pkg/roachprod/vm/gce/gcloud.go` line 1033 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98955#-NR4aDtN1TNB16z5cH2_:-NRECWvzEOF6o_4hWYDy:bcbvjar) ([raw file](https://github.com/cockroachdb/cockroach/blob/685d1617778f7527411830ac83ba4f76e8249e23/pkg/roachprod/vm/gce/gcloud.go#L1033)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I'm using it as a loop condition, vms is shrunk every time we page through.
</blockquote></details>

I see it now. In that case, the preceding allocs is not a big deal in the degenerate case (`len(vms) == 0`).
___
*[`pkg/roachprod/vm/gce/gcloud.go` line 1082 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98955#-NR4bG18CYha_ASwN7ez:-NRECt_OBO2JYW8ckc-m:b-xzt5e9) ([raw file](https://github.com/cockroachdb/cockroach/blob/685d1617778f7527411830ac83ba4f76e8249e23/pkg/roachprod/vm/gce/gcloud.go#L1082)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Unfortunately it's quite slow, more like a second and a half on average. I haven't seen any rate limiting.
</blockquote></details>

So, listing everything could take tens of seconds? Let me test it out locally.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98955)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @srosenberg)

___
*[`pkg/roachprod/vm/gce/gcloud.go` line 1082 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98955#-NR4bG18CYha_ASwN7ez:-NREERoyDZU9Y-bqrYTB:b-60wiv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/685d1617778f7527411830ac83ba4f76e8249e23/pkg/roachprod/vm/gce/gcloud.go#L1082)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

So, listing everything could take tens of seconds? Let me test it out locally.
</blockquote></details>

It takes a couple of seconds total, each call is 100 resources. It would scale with how many active roachprod instances we have, we could add parallelism later if we need.

**Comment by srosenberg** [comment]
I've been testing the billing API. It seems to be mostly reliable. After fixing the issue with missing persistent disks and adding local ssds to the estimate; the figures agree with [1]. I saw a few 503s (service unavailable), but it doesn't break anything, only estimates don't show up. The paging API takes only a few seconds, which doesn't seem like a big deal. Unless `roachprod list` is invoked, the billing API is now bypassed, so it doesn't affect any other commands. The commit msg has more details. Below is a screenshot of the new look.
roachprod_cost_estimation




[1] https://cloud.google.com/products/calculator

**Comment by srosenberg** [comment]
@jordanlewis PTAL.

**Comment by srosenberg** [comment]
Note to self: after the merge, update wiki [1] to require `gcloud auth application-default login`.

[1] https://cockroachlabs.atlassian.net/wiki/spaces/TE/pages/144408811/Roachprod+Tutorial#Setting-up-Roachprod

**Comment by jordanlewis** [comment]
Looks great! I had a thought, we might be able to prevent the new application-default login by having the program look for credentials in the environment first. Not sure how that would work, but maybe worth looking into.

I'm also fine merging this and seeing if there's fallout.

Maybe we should add a --no-estimate-costs flag to make sure people can opt out if access control isn't working.

**Review by smg260 — COMMENTED** [review]
This is cool. 

Minor suggestions:
- is it easy to right justify the numbers?
- perhaps move `~` to the header and omit from each value, since everything is an estimate?

> Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98955#-:-NRZnDLtCojB-x31u6ZR:b6tuva2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @jordanlewis, and @srosenberg)

**Comment by srosenberg** [comment]
> Other option let's make API auth failures not stop the program.

It doesn't. The error and fix suggestions are displayed; then, everything else is rendered modulo the cost estimates.

>  we might be able to prevent the new application-default login by having the program look for credentials in the environment first

I think we'll need to refactor roachprod permissions in a separate PR. Ideally, it should use a service account. For now, if `application-default` is not found, it errors out and suggests a fix,

```
04:19:47 gcloud.go:1041: Error during cost estimation (will continue without): google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
04:19:47 gcloud.go:1043: To fix this, run `gcloud auth application-default login`
```

**Comment by srosenberg** [comment]
Right-aligned all columns with the exception of the cluster name; looks odd, otherwise. Here is a new screenshot. I think this is ready for (live) beta testing :)

roachprod_right_aligned

**Comment by jordanlewis** [comment]
LGTM!

**Review by srosenberg — APPROVED** [review]

**Comment by srosenberg** [comment]
TFTR!

bors r+

**Comment by srosenberg** [comment]
bors retry

**Pull request merged**
