### PR TITLE
sqlccl: restore into different DB name than owned backup table

### PR DESCRIPTION
**Pull request by dt**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13961)

### CODE REVIEW

**Comment by mjibson** [comment]
The code here LGTM, but we need to do something safer with the KVOptions. They have two problems currently: you can specify a single key multiple times and you can specify keys that are not used (although these are kind of the same problem). I propose some kind of mutating fetcher where you can ask KVOptions for a key. It removes that key from itself and returns it. At the end of backup or restore, an error is produced is the KVOptions is not empty.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13961#-:-KeeOwd2colaVIE8Ltys:b7hvmel)*

**Comment by dt** [comment]
hm, I'm not crazy about mutating the query AST in the process of evaluating it -- AFAIK, we don't do that anywhere else.

**Comment by mjibson** [comment]
I agree the query AST shouldn't be mutated. But something can make a copy of the KVOptions or move them into a different data structure that makes this easier to do.

**Comment by dt** [comment]
Eh, I don't have a better idea, so I went ahead with marking as `read` as suggested.

**Comment by mjibson** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/sqlccl/backup.go, line 904 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13961#-KeedB0S36Qupii3N1SZ:-KeedB0S36Qupii3N1S_:b18lsq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/458a556ca5f5f0c04491bb96de96dd04954e325b/pkg/ccl/sqlccl/backup.go#L904)):*
> ```Go
> 		}
> 
> 		if err := backup.Options.CheckAllRead(); err != nil {
> ```

Putting this check here will still perform all the work, but just print an error at the end. Can we instead error before any work is done?

---

*[pkg/ccl/sqlccl/backup.go, line 939 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13961#-KeedK3KOBcxOo39tv6b:-KeedK3KOBcxOo39tv6c:b-816h6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/458a556ca5f5f0c04491bb96de96dd04954e325b/pkg/ccl/sqlccl/backup.go#L939)):*
> ```Go
> 			return nil, err
> 		}
> 		if err := restore.Options.CheckAllRead(); err != nil {
> ```

Same.

---

*[pkg/sql/parser/backup.go, line 106 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13961#-Keed1cHb7OXbumi0grK:-Keed1cI_KJ6O_XP4zgo:b-rngvx) ([raw file](https://github.com/cockroachdb/cockroach/blob/458a556ca5f5f0c04491bb96de96dd04954e325b/pkg/sql/parser/backup.go#L106)):*
> ```Go
> 
> // Get returns value for requested key and if it was found or not.
> // Returns an error if more than one value for key is found.
> ```

One other option is to remove this "only one value for the key" check, and just use CheckAllRead below to verify that if there was more than one option, it was used. Get should then be changed to return the first unread option.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13961)*

**Comment by dt** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/sqlccl/backup.go, line 904 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13961#-KeedB0S36Qupii3N1SZ:-KeedmkbRPmpk8DjYeFS:b-56hmqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/458a556ca5f5f0c04491bb96de96dd04954e325b/pkg/ccl/sqlccl/backup.go#L904)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Putting this check here will still perform all the work, but just print an error at the end. Can we instead error before any work is done?
</blockquote></details>

Eh, the that would we read all the params we'll need up front, rather than passing them all around... at which point why not just go back to adding each to the grammar and getting them at parse time? also, we might not know until we start evaluating some params what other ones we'll actually use -- e.g. an s3 option should only be read once we parse the uri and determine it is s3.... so i'm not sure an all-up-front approach can correctly track what is actually used.

---

*[pkg/sql/parser/backup.go, line 106 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13961#-Keed1cHb7OXbumi0grK:-KeedhEzFhT102bPIpWo:b-kuizn1) ([raw file](https://github.com/cockroachdb/cockroach/blob/458a556ca5f5f0c04491bb96de96dd04954e325b/pkg/sql/parser/backup.go#L106)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

One other option is to remove this "only one value for the key" check, and just use CheckAllRead below to verify that if there was more than one option, it was used. Get should then be changed to return the first unread option.
</blockquote></details>

I think Get enforcing one is fine -- we'll add GetAll when we need it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13961)*

**Comment by mjibson** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/sqlccl/backup.go, line 904 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13961#-KeedB0S36Qupii3N1SZ:-KeegEoTlXVVm-wmHS3p:b-66o4rh) ([raw file](https://github.com/cockroachdb/cockroach/blob/458a556ca5f5f0c04491bb96de96dd04954e325b/pkg/ccl/sqlccl/backup.go#L904)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Eh, the that would we read all the params we'll need up front, rather than passing them all around... at which point why not just go back to adding each to the grammar and getting them at parse time? also, we might not know until we start evaluating some params what other ones we'll actually use -- e.g. an s3 option should only be read once we parse the uri and determine it is s3.... so i'm not sure an all-up-front approach can correctly track what is actually used.
</blockquote></details>

If there's no way to check all the options before we do the work then I think we can just remove all these checks and revert to your first revision. I think it's worse to complete the work but then report an error because of some unused options than to allow unused options.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13961)*

**Comment by dt** [comment]
@mjibson Okay, let's go with the initial revision, then revisit handling these once we have a couple concrete use-cases to examine.

**Review by madelynnblue — APPROVED** [review]

**Pull request merged**
