### PR TITLE
sql: humanize counts and durations in EXPLAIN ANALYZE

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change humanizes all statistics showed in EXPLAIN and EXPLAIN
ANALYZE (both the text and the diagram):
 - byte values were already humanized
 - row counts are shown with commas (e.g. 1,000,000);
 - durations are rounded out in a more friendly way. Most importantly,
   we no longer show a lot of decimals for multi-second times, and the
   zero value is now shown as "0µs" instead of "0s" (the latter can be
   confusing, e.g. is it hiding a 100ms time?).

Release note (sql change): EXPLAIN and EXPLAIN ANALYZE now show counts
and durations in a more user-friendly way.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 47 of 47 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57420#-:-MNd64kKBZsGsNaLJG22:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @RaduBerinde)

___
*[pkg/sql/execinfrapb/component_stats.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57420#-MNd5c1D5GA7xaeV3m04:-MNd5c1D5GA7xaeV3m05:b-qnn6qb) ([raw file](https://github.com/cockroachdb/cockroach/blob/37398fbdac25002c3a8349795288712f4fedeb7a/pkg/sql/execinfrapb/component_stats.go#L57)):*
> ```Go
> 	}
> 	if s.NetRx.TuplesReceived.HasValue() {
> 		fn("network tuples received", humanize.Comma(int64(s.NetRx.TuplesReceived.Value())))
> ```

[nit] what do you think about adding a function `humanizeutil.Count` that calls `humanize.Comma`? That would be more consistent with `humanizeutil.Duration`.
___
*[pkg/util/humanizeutil/duration_test.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57420#-MNd53fe7AWphYr1cu44:-MNd53fe7AWphYr1cu45:b-igwwae) ([raw file](https://github.com/cockroachdb/cockroach/blob/37398fbdac25002c3a8349795288712f4fedeb7a/pkg/util/humanizeutil/duration_test.go#L25)):*
> ```Go
> 		{val: 0, exp: "0µs"},
> 		{val: 12, exp: "0µs"},
> 		{val: 1234, exp: "1µs"},
> ```

What about checking that 501 rounds up to 1 microsecond?

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57420#-:-MNdcvJf9RvKJimGLHpy:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @rytaft)

___
*[pkg/sql/execinfrapb/component_stats.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57420#-MNd5c1D5GA7xaeV3m04:-MNdcq6W4HERCctS8Kut:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/37398fbdac25002c3a8349795288712f4fedeb7a/pkg/sql/execinfrapb/component_stats.go#L57)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] what do you think about adding a function `humanizeutil.Count` that calls `humanize.Comma`? That would be more consistent with `humanizeutil.Duration`.
</blockquote></details>

Done.
___
*[pkg/util/humanizeutil/duration_test.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57420#-MNd53fe7AWphYr1cu44:-MNdct_Z-as3nDiSooRH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/37398fbdac25002c3a8349795288712f4fedeb7a/pkg/util/humanizeutil/duration_test.go#L25)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

What about checking that 501 rounds up to 1 microsecond?
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57420)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @RaduBerinde)

___
*[pkg/util/humanizeutil/count.go, line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57420#-MNdykCzDPwDavoJymhd:-MNdykD-0A8nVZ-50Z-o:b-m3opox) ([raw file](https://github.com/cockroachdb/cockroach/blob/5658763dd20ee9035ceabaa41d2ab4507f1e96e0/pkg/util/humanizeutil/count.go#L15)):*
> ```Go
> import "github.com/dustin/go-humanize"
> 
> // Count formats a unitless iteger value like a row count. It uses separating
> ```

[nit] iteger -> integer

**Pull request merged**
