### PR TITLE
migrations: temporarily disable TestUpdateViewDependenciesMigration

### PR DESCRIPTION
**Pull request by knz**
Disabling test while I investigate the problem.

Updates #17438.

### CODE REVIEW

**Review by tamird — APPROVED** [review]

**Comment by knz** [comment]
Could you merge if green? I'm on mobile and can't log in to github.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dt** [comment]
not green, lint failure.

**Comment by knz** [comment]
If the linter has something to say about a skipped test, we have a linter problem.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tamird** [comment]
The linter is complaining about the fact that leaktest is no longer at the
top of the test.

**Comment by tamird** [comment]
(if we're complaining about the linter without looking at its complaint, we
have a complaining-about-linters problem)

**Comment by dt** [comment]
amended and pushed.

**Review by tamird — APPROVED** [review]

**Comment by knz** [comment]
Thanks to both for your help. (I was out for dinner)

**Pull request merged**
