### PR TITLE
sqlproxyccl: fix the run proxy sample script

### LINKED ISSUE #71385: sqlproxyccl: the reference script `run_proxy.sh` is outdated
I was trying to test things out with #71248 and I ran into the following issues:

- `mt start-sql` now needs a separate `--store` flag from the server (since it uses disk storage now)
- proxy does not support `--target-addr` any more
- `--logtostderr` is not the correct log flag any more
- the proxy attempts to start a listener on port 8080, and this fails because there's already a server on that port, and I could not find a way to configure it

It would also be useful if the script was updated to use separate certs directories to reflect realistic deployment usage.

### PR DESCRIPTION
**Pull request by darinpp**
The pkg/ccl/sqlproxyccl/run_proxy_(in)direct_crdb.sh sets a
multi-instance environment with a host server, proxy server and a test
directory server that can start tenant processes on demand.

This PR does the following:
- changes the script so it uses secure connections between all processes
- uses separate CAs when possible
- adds a cert directory option to the test directory server so tenant
  processes can be started with the correct set of certs
- adds a KV addrs flag to the test directory so the tenant processes can
  target the correct host server
- changes the capturing of the tenant processes output to continiously
  flow into test directory server log. Previously that was happening
  when the tenant process terminates.
- adds a store argument to the tenant process
- removes the --logtostderr proxy option
- changes the proxy http listen port to not interfere with default
  cockroach db port
- minor fix for the "tenant client cert not found" message to show the
  directory that is being searched for the cert
- separates the run_proxy.sh script into two script -
  run_proxy_direct_crdb and run_proxy_indirect_crdb. The first one relies
  on the test directory server to launch tenant sql processes by
  using the cockroach executable directly. The second does that by
  executing a shell script run_tenant. Using a shell script allows a
  better customization of the tenant startup, just in time cert generation
  and allows multiple tenants (vs just one tenant in the first case).
- adds a trap to the shell scripts to shutdown all processes started by
  the script
- the scripts will now wait for a key press and then do the shutdown and the
  cleanup once a key is pressed.

Fixes #71385

Release note: None

```
$ ./run_proxy_indirect_crdb.sh 
Create node CA and node cert
Create client CA
Create tenant CA
Create client tenant root cert
Start KV layer
Create client host root cert
Start test directory server
Start the sql proxy server (with self signed client facing cert)
All files are in /tmp/tenant-test-Wgl3
To connect to a specific tenant (123 for example):
  cockroach sql --url="postgresql://root:secret@127.0.0.1:55506?sslmode=require&sslrootcert=a&options=--cluster%3Dtenant-cluster-123"
Press any key to shutdown all processes and cleanup.

initiating graceful shutdown of server
server drained and shutdown completed
server shutdown completed
cleaning up...
```
```
cockroach sql --url="postgresql://root:secret@127.0.0.1:55506?sslmode=require&sslrootcert=a&options=--cluster%3Dtenant-cluster-123" -e 'select 1'
  ?column?
------------
         1
(1 row)


Time: 1ms

```

### CODE REVIEW

**Review by knz — APPROVED** [review]
:lgtm: but I'd like a review from Jay too.

> Reviewed 9 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71760#-:-Mms-mkB5qN1S5rLYaHI:b-5pi9q2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @darinpp, and @jaylim-crl)

___
*[pkg/ccl/sqlproxyccl/run_proxy.sh, line 5 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71760#-MmrzsdX3RhzqkRYoeqp:-MmrzsdX3RhzqkRYoeqq:b-7u0zf9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c6e52607907e98587bc6ca4324490aeff2e546a/pkg/ccl/sqlproxyccl/run_proxy.sh#L5)):*
> ```Shell
> 
> COCKROACH=${1:-'cockroach'}
> BASE=${2:-$(mktemp -d -t 'tenant-test-XXXX')}
> ```

I'm not fond of the auto-generated temp dir unless you can also ensure it's deleted when the script terminates.

To achieve this you can use `trap` 
___
*[pkg/ccl/sqlproxyccl/run_proxy.sh, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71760#-Mms-4sG5b-gogrGRbZ9:-Mms-4sG5b-gogrGRbZA:b-2hj2cp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c6e52607907e98587bc6ca4324490aeff2e546a/pkg/ccl/sqlproxyccl/run_proxy.sh#L30)):*
> ```Shell
> 
> echo Create node CA and node cert
> COCKROACH_CA_KEY=$HOST/ca.key COCKROACH_CERTS_DIR=$HOST $COCKROACH cert create-ca 
> ```

nit: trailing spaces
___
*[pkg/ccl/sqlproxyccl/run_proxy.sh, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71760#-Mms-9YI9rceMQmaybF8:-Mms-9YI9rceMQmaybF9:b-4h00zd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c6e52607907e98587bc6ca4324490aeff2e546a/pkg/ccl/sqlproxyccl/run_proxy.sh#L34)):*
> ```Shell
> 
> echo Create client CA
> COCKROACH_CA_KEY=$CLIENT/ca.key COCKROACH_CERTS_DIR=$CLIENT $COCKROACH cert create-client-ca
> ```

you'd make this more readable with 
```
ca_flags="--ca-key $CLIENT/ca.key --certs-dir=$CLIENT"
```

and expand `$ca_flags` on the relevant commands.
___
*[pkg/ccl/sqlproxyccl/tenantdirsvr/test_directory_svr.go, line 445 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71760#-Mms-c158uzRItW4c1Me:-Mms-c158uzRItW4c1Mf:bex2frk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c6e52607907e98587bc6ca4324490aeff2e546a/pkg/ccl/sqlproxyccl/tenantdirsvr/test_directory_svr.go#L445)):*
> ```Go
> 	c.Env = append(os.Environ(), "COCKROACH_TRUST_CLIENT_PROVIDED_SQL_REMOTE_ADDR=true")
> 	var f writerFunc = func(p []byte) (int, error) {
> 		sc := bufio.NewScanner(strings.NewReader(string(p)))
> ```

I don't understand this. what does it do?

**Review by jaylim-crl — APPROVED** [review]
:lgtm: with a few comments.

How difficult would it be to convert this to a TCL test? Something similar to https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/interactive_tests/test_demo.tcl. Can be in a follow-up PR.

This script broke a couple of times, and I wonder if it's time to change to something more future-proof.

> Reviewed 1 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71760#-:-Mms_76IBMYWePLff0Ay:b6c5bdd)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andy-kimball and @darinpp)

___
*[pkg/ccl/sqlproxyccl/run_proxy.sh, line 44 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71760#-MmsYAFM3CFsr3qcms6b:-MmsYAFM3CFsr3qcms6c:b-ar9i8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c6e52607907e98587bc6ca4324490aeff2e546a/pkg/ccl/sqlproxyccl/run_proxy.sh#L44)):*
> ```
> cp $TENANT/ca.crt $HOST/ca-client-tenant.crt
> cat $HOST/ca.crt >> $TENANT/ca.crt
> ```

Is this on purpose? How come we copy a concatenated version for ca-client.crt earlier, but just ca-client-tenant.crt here?
___
*[pkg/ccl/sqlproxyccl/run_proxy.sh, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71760#-MmsZMt74-KsEcwYmdmh:-MmsZMt74-KsEcwYmdmi:bijw8s9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c6e52607907e98587bc6ca4324490aeff2e546a/pkg/ccl/sqlproxyccl/run_proxy.sh#L78)):*
> ```Shell
> 
> echo "Start the sql proxy server (with self signed client facing cert)"
> $COCKROACH mt start-proxy  --listen-addr=localhost:$PROXY_P --listen-cert=* --listen-key=* --directory=:$DIR_P --listen-metrics=:$PROXY_HTTP_P --skip-verify --log="{sinks: {file-groups: {default: {dir: $PROXY, channels: ALL}}}}" 2>$PROXY/stderr.log &
> ```

Does the proxy work without `--skip-verify` here? Chris merged this PR here, so I suspect it should work if we configured it right: https://github.com/cockroachdb/cockroach/pull/69959. If it works, I don't see a harm verifying it here.

**Review by darinpp — COMMENTED** [review]
That's a good idea. I'll try a simpler version in another PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71760#-:-MqHHW-DCn0iZnh_B0Ud:b-vgeazn)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andy-kimball, @jaylim-crl, and @knz)

___
*[pkg/ccl/sqlproxyccl/tenantdirsvr/test_directory_svr.go, line 445 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71760#-Mms-c158uzRItW4c1Me:-MqHNtHxDYhhufORkQXq:b-a7jh6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c6e52607907e98587bc6ca4324490aeff2e546a/pkg/ccl/sqlproxyccl/tenantdirsvr/test_directory_svr.go#L445)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I don't understand this. what does it do?
</blockquote></details>

This grabs lines from the output of the child process as they are being generated and logs them in its own log in real time. In a few places where we do child processes we either make the child log into a separate log or we hold the child output into a buffer and only after the process finishes - we dump them in the log. So if you are trailing the log, you won't see anything being added for many seconds and then suddenly few dozen lines get added with the same timestamp. With this change lines are added as they are coming with correct timestamps.
___
*[pkg/ccl/sqlproxyccl/run_proxy.sh, line 5 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71760#-MmrzsdX3RhzqkRYoeqp:-MqHHaQ77VqULLSIfK0_:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c6e52607907e98587bc6ca4324490aeff2e546a/pkg/ccl/sqlproxyccl/run_proxy.sh#L5)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I'm not fond of the auto-generated temp dir unless you can also ensure it's deleted when the script terminates.

To achieve this you can use `trap` 
</blockquote></details>

done
___
*[pkg/ccl/sqlproxyccl/run_proxy.sh, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71760#-Mms-4sG5b-gogrGRbZ9:-MqHIhw--jHJ59CE_v6e:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c6e52607907e98587bc6ca4324490aeff2e546a/pkg/ccl/sqlproxyccl/run_proxy.sh#L30)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: trailing spaces
</blockquote></details>

fixed
___
*[pkg/ccl/sqlproxyccl/run_proxy.sh, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71760#-Mms-9YI9rceMQmaybF8:-MqHImV_5QHd1TlBGhFM:b-admpo0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c6e52607907e98587bc6ca4324490aeff2e546a/pkg/ccl/sqlproxyccl/run_proxy.sh#L34)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

you'd make this more readable with 
```
ca_flags="--ca-key $CLIENT/ca.key --certs-dir=$CLIENT"
```

and expand `$ca_flags` on the relevant commands.
</blockquote></details>

Different CA for different components. Once we migrate to single CA I'll fix.
___
*[pkg/ccl/sqlproxyccl/run_proxy.sh, line 44 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71760#-MmsYAFM3CFsr3qcms6b:-MqHJMQWBkBgg5ysaVm9:b2yatv8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c6e52607907e98587bc6ca4324490aeff2e546a/pkg/ccl/sqlproxyccl/run_proxy.sh#L44)):*
<details><summary><i>Previously, jaylim-crl (Jay Lim) wrote…</i></summary><blockquote>

> ```
> cp $TENANT/ca.crt $HOST/ca-client-tenant.crt
> cat $HOST/ca.crt >> $TENANT/ca.crt
> ```

Is this on purpose? How come we copy a concatenated version for ca-client.crt earlier, but just ca-client-tenant.crt here?
</blockquote></details>

The host has a separate CA for the tenants and also the host never connects as a tenant. This is different from the host and the host clients. The host nodes connect to one another as clients.
___
*[pkg/ccl/sqlproxyccl/run_proxy.sh, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71760#-MmsZMt74-KsEcwYmdmh:-MqHNNsX2spJfQttGymY:b-3dl8ih) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c6e52607907e98587bc6ca4324490aeff2e546a/pkg/ccl/sqlproxyccl/run_proxy.sh#L78)):*
<details><summary><i>Previously, jaylim-crl (Jay Lim) wrote…</i></summary><blockquote>

Does the proxy work without `--skip-verify` here? Chris merged this PR here, so I suspect it should work if we configured it right: https://github.com/cockroachdb/cockroach/pull/69959. If it works, I don't see a harm verifying it here.
</blockquote></details>

Chris' fix I think allows for the proxy to check tenant's cert against the name it got from the directory. But the proxy still needs some way to trust the tenant's cert to do that and currently there isn't an explicit parameter to set a CA cert.

**Comment by darinpp** [comment]
The PR is now changed to allow much more flexibility in how tenant's are being started. You can provide your own script that does that the startup. Or run it statically and just forward connections. It should take care of https://cockroachlabs.atlassian.net/browse/CC-5552
@RaduBerinde @andy-kimball

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71760)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andy-kimball, @darinpp, @jaylim-crl, and @knz)

___
*[pkg/ccl/sqlproxyccl/run_proxy_indirect_crdb.sh, line 41 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71760#-MqL2Bd18rP1M9BmHg4u:-MqL2Bd244IHARGau43Z:b-6urar6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ff7660a15002a9b82de9fa32ed2c9c120b822fb/pkg/ccl/sqlproxyccl/run_proxy_indirect_crdb.sh#L41)):*
> ```Shell
> PROXY_HTTP_P=55507
> 
> echo Create node CA and node cert
> ```

[nit] The steps up to `Create client host root cert` are the same, we should extract them in a common script

**Pull request merged**
