### PR TITLE
server: hide automatic jobs from the UI

### LINKED ISSUE #69611: jobs: hide automatic jobs from the UI
**Describe the problem**

We currently hide the `AUTO STATS CREATION JOB` from the UI by explicitly excluding it from here: https://github.com/cockroachdb/cockroach/blob/e2cd3ae015c1f86d188ace3650db2ea622ec58b4/pkg/server/admin.go#L1840. 

We've recently added other automatic jobs, such as the `AUTO SPANCONFIG RECONCILIATION` JOB. It makes sense to hide this and other automatic jobs that may be added going forward from the UI as well by tweaking the query linked above. 

Jira issue: CRDB-9684

### PR DESCRIPTION
**Pull request by THardy98**
Resolves: #69611

Previously, only the auto create stats job was hidden from the UI. This
change hides all automatic jobs from the UI.

Release justification: Category 2: Bug fixes and low-risk updates to new
functionality.

Release note (bug fix): hide automatic jobs from the UI.

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77331)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @THardy98)

___
*[pkg/server/admin_test.go, line 1440 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77331#-MxagLEz4sDBqQbNqMhf:-MxagLEz4sDBqQbNqMhg:b-u7cn4z) ([raw file](https://github.com/cockroachdb/cockroach/blob/773d54f23460d93f16b46f0523cd953faebf6750/pkg/server/admin_test.go#L1440)):*
> ```Go
> // getSystemJobIDsForNonAutoJobs queries the jobs table for all job IDs that have
> // the given status. Sorted by decreasing creation time.
> func getSystemJobIDsForNonAutoJobs(
> ```

can you add a test that uses the function you changed above? To make sure the function works as expected and also to make it easier to align here (so you don't need to update the query in 2 places).

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77331)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @maryliag)

___
*[pkg/server/admin_test.go, line 1440 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77331#-MxagLEz4sDBqQbNqMhf:-MxjLTKI2jhXxHz6c_OR:b-2fb7uz) ([raw file](https://github.com/cockroachdb/cockroach/blob/773d54f23460d93f16b46f0523cd953faebf6750/pkg/server/admin_test.go#L1440)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

can you add a test that uses the function you changed above? To make sure the function works as expected and also to make it easier to align here (so you don't need to update the query in 2 places).
</blockquote></details>

It's being used by `TestAdminAPIJobs` on line 1472, which checks that we get that the use of the AdminAPI returns the job IDs we expect. With this change, `TestAdminAPIJobs` now expects only non-auto job IDs.

**Review by maryliag — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77331#-:-MxjNS8d5hFnmOkXm6CJ:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @maryliag)

**Review by arulajmani — APPROVED** [review]
Thanks for doing this! :lgtm: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77331#-:-MxjO5RR0dlyYd1w5uJ0:bkqkww5)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @maryliag)

**Comment by THardy98** [comment]
Sweet, TYFR :)

**Pull request merged**
