### PR TITLE
opt/idxconstraint: refactor the simplify filter code

### PR DESCRIPTION
**Pull request by RaduBerinde**
Uncommenting and refactoring the simplify filter code.

Release note: None

### CODE REVIEW

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 957 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22954#-L5zDWuRWaUr98RUeJWx:-L5zDWuRWaUr98RUeJWy:b-a4owpk) ([raw file](https://github.com/cockroachdb/cockroach/blob/47327e1fdcf4349ca313cc387fc107e3c7ce808b/pkg/sql/opt/idxconstraint/index_constraints.go#L957)):*
> ```Go
> }
> 
> // simplifyFilter is the internal (recursive) implementation of simplifyFilter.
> ```

I think this needs to be updated - now there is only one `simplifyFilter`

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 1018 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22954#-L5zCIQtDoiSw0RYd-Wa:-L5zCIQtDoiSw0RYd-Wb:bug2g8f) ([raw file](https://github.com/cockroachdb/cockroach/blob/47327e1fdcf4349ca313cc387fc107e3c7ce808b/pkg/sql/opt/idxconstraint/index_constraints.go#L1018)):*
> ```Go
> 		}
> 
> 		// Note: if nothing changed, the factory will detect that it's the same
> ```

Then why do you need the above code to check if anything was simplified?

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 1076 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22954#-L5zCflZQBjscTLskCdJ:-L5zCflZQBjscTLskCdK:b9n4uzu) ([raw file](https://github.com/cockroachdb/cockroach/blob/47327e1fdcf4349ca313cc387fc107e3c7ce808b/pkg/sql/opt/idxconstraint/index_constraints.go#L1076)):*
> ```Go
> //   spans, ok := ic.Spans()
> //   remFilterGroup := ic.RemainingFilter(&iVarHelper)
> //	 remFilter := o.Optimize(remFilterGroup, &opt.PhysicalProps{})
> ```

[nit] remove extra spaces in front of `remFilter`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22954#-:-L5zEtbt6woZH5Nm5rjN:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 957 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22954#-L5zDWuRWaUr98RUeJWx:-L5zYxkEC8kilZ77R8SG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/47327e1fdcf4349ca313cc387fc107e3c7ce808b/pkg/sql/opt/idxconstraint/index_constraints.go#L957)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I think this needs to be updated - now there is only one `simplifyFilter`
</blockquote></details>

Done.

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 1018 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22954#-L5zCIQtDoiSw0RYd-Wa:-L5zYzvApc7lk1sA4bBr:b7dr8qf) ([raw file](https://github.com/cockroachdb/cockroach/blob/47327e1fdcf4349ca313cc387fc107e3c7ce808b/pkg/sql/opt/idxconstraint/index_constraints.go#L1018)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Then why do you need the above code to check if anything was simplified?
</blockquote></details>

Good question, I think I intended to remove it. Done.

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 1076 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22954#-L5zCflZQBjscTLskCdJ:-L5zZDJZjfrnxttMpAWM:b-ucllao) ([raw file](https://github.com/cockroachdb/cockroach/blob/47327e1fdcf4349ca313cc387fc107e3c7ce808b/pkg/sql/opt/idxconstraint/index_constraints.go#L1076)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] remove extra spaces in front of `remFilter`
</blockquote></details>

I scratched my head on this one for a bit, it looked fine to me both here and in the editor. There was a tab haha, fixed.

FYI you can set tabs to 2 spaces in reviewable by putting the URL below in "Custom syntax highlighting stylesheet URL"
https://rawgit.com/dt/5f35fdaf9ecdc6bdadf74995e7ffb421/raw/84beb6e137e3b9132a0644f1afa1fbd08a246a07/reviewable_tabs_2space.css

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22954)*

**Comment by rytaft** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 1076 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22954#-L5zCflZQBjscTLskCdJ:-L5zb8B9p1Iyh5fSqnVx:b5v8wme) ([raw file](https://github.com/cockroachdb/cockroach/blob/47327e1fdcf4349ca313cc387fc107e3c7ce808b/pkg/sql/opt/idxconstraint/index_constraints.go#L1076)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I scratched my head on this one for a bit, it looked fine to me both here and in the editor. There was a tab haha, fixed.

FYI you can set tabs to 2 spaces in reviewable by putting the URL below in "Custom syntax highlighting stylesheet URL"
https://rawgit.com/dt/5f35fdaf9ecdc6bdadf74995e7ffb421/raw/84beb6e137e3b9132a0644f1afa1fbd08a246a07/reviewable_tabs_2space.css
</blockquote></details>

cool thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22954)*

**Comment by andy-kimball** [comment]
:lgtm: Conversion to `ExprView` looks correct.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22954#-:-L5zrxlRpdgyUBl0gOL-:b-j6b5wg)*

**Pull request merged**
