### PR TITLE
sql: add logic for `GRANT ... ON seq_names`

### LINKED ISSUE #82414: GRANT privilege ON sequence incorrect behavior
Unable to grant on a sequence using `GRANT privilege ON sequence` syntax

```
statement ok
create sequence seq;

statement ok
create user testuser;

# should be statement ok
statement error pgcode 0LP01 invalid privilege type USAGE for table
GRANT SELECT ON seq TO testuser WITH GRANT OPTION

# should be true
query B
SELECT has_sequence_privilege('testuser', 'seq', 'SELECT WITH GRANT OPTION')
----
false
```

Jira issue: CRDB-16364
Epic CRDB-14491

### PR DESCRIPTION
**Pull request by ZhouXing19**
Currently, the `GRANT ... ON names` syntax by default take all the target
as table, while in Postgres 14, the `names` field accepts names for both
table and sequence. This commit is to add similar sementics.

Given that a table's privilege list is the subset of a sequence's, if the
targets list contains any table, the allowed privilege should be the table
privilege. Only when all targets are of the type sequence, the allowed list
is the sequence privilege.

Since the target list may contain both tables and sequences, when validating,
we need to sepcify the privilege type for each target descriptor.

fixes #82414
fixes #82465

Release note (sql): add logic for GRANT ... ON seq_names

### CODE REVIEW

**Comment by rafiss** [comment]
sorry, i didn't realize it was ready to be reviewed since it looks like there's still a test faliure to address
```
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/logictest/testdata/logic_test/privilege_builtins:769: SELECT has_sequence_privilege('seq', 'USAGE'),
               has_sequence_privilege('seq', 'SELECT'),
               has_sequence_privilege('seq', 'UPDATE')
        expected:
            true  true  false
        but found (query options: "") :
            false  true  false
```

also, it needs to be rebased

**Comment by ZhouXing19** [comment]
Ah thanks! I didn't noticed that test error.
Rebased and fixed the test.

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82458)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @ZhouXing19)

___
*[`pkg/sql/grant_revoke.go` line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82458#-N4YcgZQA-OoWq0omMZL:-N4YcgZQA-OoWq0omMZM:b8xkqun) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a9ea594d2f487b0aa94fdba48ea8c7325ade082/pkg/sql/grant_revoke.go#L167)):*
> ```Go
> 
> 	var err error
> 	var descriptorsWithTypes []DescriptorWithType
> ```

nit: i think to avoid confusion with type descriptors, we could name this `DescriptorWithObjectType`
___
*[`pkg/sql/grant_revoke.go` line 433 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82458#-N4YczH77RY1RkNZGYYR:-N4YczH77RY1RkNZGYYS:bug1oo1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a9ea594d2f487b0aa94fdba48ea8c7325ade082/pkg/sql/grant_revoke.go#L433)):*
> ```Go
> // privilege.Table. Only when all objects in the target list are sequence, it
> // returns the privilege.Sequence.
> func getGrantOnObject(
> ```

nit: this feels like it should be defined as `func (p *planner) getGrantOnObject(ctx, targets, ...)`
___
*[`pkg/sql/grant_revoke.go` line 457 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82458#-N4YdTKJDUnuSKlf4dWM:-N4YdTKJDUnuSKlf4dWN:b1xotnm) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a9ea594d2f487b0aa94fdba48ea8c7325ade082/pkg/sql/grant_revoke.go#L457)):*
> ```Go
> 			return privilege.Any, errors.Wrap(
> 				err,
> 				"cannot check the composition of the grant target's table patterns",
> ```

nit: this error message would be hard for a user to understand. maybe just a message of "cannot determine the target type of the GRANT statement" would work
___
*[`pkg/sql/grant_revoke.go` line 469 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82458#-N4YdmqWA_1STZFKT5Ze:-N4YdmqWA_1STZFKT5Zf:b-dqb4l5) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a9ea594d2f487b0aa94fdba48ea8c7325ade082/pkg/sql/grant_revoke.go#L469)):*
> ```Go
> }
> 
> type tableAttrsComposition int8
> ```

nit: add a comment
___
*[`pkg/sql/grant_revoke.go` line 482 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82458#-N4YdERz-tk5fPIe0bUh:-N4YdERz-tk5fPIe0bUi:b-tms4q0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a9ea594d2f487b0aa94fdba48ea8c7325ade082/pkg/sql/grant_revoke.go#L482)):*
> ```Go
> // list; if any target is of type table, we should use the table privilege.
> // This is because the table privilege is the subset of sequence privilege.
> func checkTablePatternsComposition(
> ```

nit: this feel like it should be defined as `func (p *planner) checkTablePatternsComposition(ctx, targets, ...)`

also, i feel like it could be changed to return `(bool, error)` if it's named something like `checkTargetsAreAllSequences`
___
*[`pkg/sql/resolver.go` line 404 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82458#-N4YeIUVEu7jxkEXr8dr:-N4YeIUVEu7jxkEXr8ds:b-rzaz4m) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a9ea594d2f487b0aa94fdba48ea8c7325ade082/pkg/sql/resolver.go#L404)):*
> ```Go
> // getDescriptorsFromTargetListForPrivilegeChange fetches the descriptors
> // for the targets. Each descriptor is marked along with the corresponding
> // privilege type.
> ```

nit: it's "object type" not "privilege type"

**Review by ZhouXing19 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82458)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @rafiss)

___
*[`pkg/sql/grant_revoke.go` line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82458#-N4YcgZQA-OoWq0omMZL:-N4YmYZb4MMknKgMv982:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a9ea594d2f487b0aa94fdba48ea8c7325ade082/pkg/sql/grant_revoke.go#L167)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: i think to avoid confusion with type descriptors, we could name this `DescriptorWithObjectType`
</blockquote></details>

done.
___
*[`pkg/sql/grant_revoke.go` line 433 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82458#-N4YczH77RY1RkNZGYYR:-N4YmZlFBzKiszEZgQgT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a9ea594d2f487b0aa94fdba48ea8c7325ade082/pkg/sql/grant_revoke.go#L433)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: this feels like it should be defined as `func (p *planner) getGrantOnObject(ctx, targets, ...)`
</blockquote></details>

Done.
___
*[`pkg/sql/grant_revoke.go` line 457 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82458#-N4YdTKJDUnuSKlf4dWM:-N4Ym_dcALr-BNarSEev:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a9ea594d2f487b0aa94fdba48ea8c7325ade082/pkg/sql/grant_revoke.go#L457)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: this error message would be hard for a user to understand. maybe just a message of "cannot determine the target type of the GRANT statement" would work
</blockquote></details>

Done.
___
*[`pkg/sql/grant_revoke.go` line 469 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82458#-N4YdmqWA_1STZFKT5Ze:-N4YmaOB3PMFtGtL3evo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a9ea594d2f487b0aa94fdba48ea8c7325ade082/pkg/sql/grant_revoke.go#L469)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: add a comment
</blockquote></details>

Done.
___
*[`pkg/sql/grant_revoke.go` line 482 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82458#-N4YdERz-tk5fPIe0bUh:-N4YmbMTEBAZHp4uT0Ci:be88blm) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a9ea594d2f487b0aa94fdba48ea8c7325ade082/pkg/sql/grant_revoke.go#L482)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: this feel like it should be defined as `func (p *planner) checkTablePatternsComposition(ctx, targets, ...)`

also, i feel like it could be changed to return `(bool, error)` if it's named something like `checkTargetsAreAllSequences`
</blockquote></details>

made it as a method for `planner`, and renamed it with `getTablePatternsComposition` so that the returned (`tablePatternsComposition, error`) looks more intuitive. 
___
*[`pkg/sql/resolver.go` line 404 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82458#-N4YeIUVEu7jxkEXr8dr:-N4Ymg129lnNDQFWnFa2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a9ea594d2f487b0aa94fdba48ea8c7325ade082/pkg/sql/resolver.go#L404)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: it's "object type" not "privilege type"
</blockquote></details>

Done.

**Review by rafiss — COMMENTED** [review]
nice, the code lgtm! it looks like there is still a test failure to fix though

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82458#-:-N4ZHWqd9qAc5tpTR7sq:b1lw3in)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall)

**Comment by ZhouXing19** [comment]
Thanks! It passed the CI, and the bazel CI seemed to fail with irrelevant reason.
bors r=rafiss

**Comment by rafiss** [comment]
A backport shouldn't be needed, since https://github.com/cockroachdb/cockroach/pull/79862 is not in 22.1

**Pull request merged**
