### PR TITLE
backupccl: allow appending incremental layers to backups

### PR DESCRIPTION
**Pull request by dt**
This changes the behavior when running BACKUP to a destination already
containing a backup. Previously attempting to do so would result in an
error saying that the destination already contained a backup. After this
change, it will instead result in implicitly producing an _incremental
backup_ in an automatically chosen subdirectory of the specified backup.

More specifically, if the destination already contains a BACKUP, trying
to backup to it again will instead backup to a subdirectory with a date-
based name. Additionally, it will search for existing incremental
backups in any similarly created subdirectories, choosing the latest as
the basis from which it will be incremental.

The essentially turns `BACKUP TO x` into a create-or-append operation:
The first time it is run it creates a full backup in x. The next time
it discovers what is currently covered by x and adds an incremental
backup from x in x/day/time1. When run again, it creates another, this
time in x/day/time2, which is incremental from x/day/time1, etc.

`RESTORE FROM x` is modified slightly, such that if x contains such
automatically created subdirectories, it is implicitly transformed to
`RESTORE FROM x, x/day/time1, x/day/time2, ...`.

Release note (enterprise change): BACKUP can be re-run with the same destination path to automatically append an incremental backup to that path.

### CODE REVIEW

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45255)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @pbardea)

___
*[pkg/ccl/backupccl/backup_planning.go, line 381 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45255#-M0YY2q65V__IZSOOnhq:-M0YY2q65V__IZSOOnhr:b-ragvbb) ([raw file](https://github.com/cockroachdb/cockroach/blob/12c8522054da49a744144a0d19ff902325559284/pkg/ccl/backupccl/backup_planning.go#L381)):*
> ```Go
> 			return err
> 		}
> 		defer defaultStore.Close()
> ```

I think this may need to be thrown in an anonymous function to pick up the new store: `defer func() { defaultStore.Close() }()` Otherwise it tried to close the store that was initialized at the time of the defer.
___
*[pkg/ccl/backupccl/manifest_handling.go, line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45255#-M0YYhqn4E4tOsnY3hx2:-M0YYhqn4E4tOsnY3hx3:b-3lu35z) ([raw file](https://github.com/cockroachdb/cockroach/blob/12c8522054da49a744144a0d19ff902325559284/pkg/ccl/backupccl/manifest_handling.go#L103)):*
> ```Go
> 	r, err := exportStore.ReadFile(ctx, BackupManifestName)
> 	if err != nil {
> 		return false, nil /* TOODO(dt): only silence non-exists errors */
> ```

[nit] TOODO

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45255)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea)

___
*[pkg/ccl/backupccl/backup_planning.go, line 381 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45255#-M0YY2q65V__IZSOOnhq:-M0Y_XxN6QJScFbirgB3:bmfgwdm) ([raw file](https://github.com/cockroachdb/cockroach/blob/12c8522054da49a744144a0d19ff902325559284/pkg/ccl/backupccl/backup_planning.go#L381)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I think this may need to be thrown in an anonymous function to pick up the new store: `defer func() { defaultStore.Close() }()` Otherwise it tried to close the store that was initialized at the time of the defer.
</blockquote></details>

Oh, good point!

Done.
___
*[pkg/ccl/backupccl/manifest_handling.go, line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45255#-M0YYhqn4E4tOsnY3hx2:-M0Y_X5u8t7S2RGXZ0Gk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/12c8522054da49a744144a0d19ff902325559284/pkg/ccl/backupccl/manifest_handling.go#L103)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

[nit] TOODO
</blockquote></details>

Done.

**Comment by dt** [comment]
I have https://github.com/cockroachdb/cockroach/commit/df5adbb106aa8f77c23788780408d0467a4ad052 ready to PR as well but I imagine it is easier to review if I want to send it separately.

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45255)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @pbardea)

___
*[pkg/ccl/backupccl/backup_planning.go, line 470 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45255#-M0rzzKz6acT5IQmSvvc:-M0rzzKz6acT5IQmSvvd:b-pb0mp9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d4115c70e3f2b660afe188d6db0932741364524/pkg/ccl/backupccl/backup_planning.go#L470)):*
> ```Go
> 					return errors.Wrap(err, "re-opening layer-specific destination location")
> 				}
> 				// Note tha a Close() is already deferred above.
> ```

[nit] typo: tha -> that
___
*[pkg/ccl/backupccl/backup_test.go, line 414 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45255#-M0s-9OA8cAqCP0tD_38:-M0s-9OA8cAqCP0tD_39:b4wuhlc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d4115c70e3f2b660afe188d6db0932741364524/pkg/ccl/backupccl/backup_test.go#L414)):*
> ```Go
> 	var tsBefore, ts1, ts2 string
> 	sqlDB.QueryRow(t, "SELECT cluster_logical_timestamp()").Scan(&tsBefore)
> 	//rowsBefore := sqlDB.QueryStr(t, "SELECT * from data.bank ORDER BY id")
> ```

Can we remove these commented out lines?
___
*[pkg/ccl/backupccl/manifest_handling.go, line 304 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45255#-M0s-ISb68MvbOGdw2KG:-M0s-ISb68MvbOGdw2KH:bk6s7r2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d4115c70e3f2b660afe188d6db0932741364524/pkg/ccl/backupccl/manifest_handling.go#L304)):*
> ```Go
> }
> 
> func findPriorBackups(ctx context.Context, store cloud.ExternalStorage) ([]string, error) {
> ```

Have you considered storing the previous backups as a property of the backup manifest? The advantage I see of doing it that way would be that we could arbitrarily change the naming structure of the incremental backup files in the future. (e.g. say we wanted to change them to be a hash of their contents, or just a UUID.)
___
*[pkg/ccl/backupccl/manifest_handling.go, line 387 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45255#-M0s-mKu9GjM7avEI3Wh:-M0s-mKu9GjM7avEI3Wi:bx9qdri) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d4115c70e3f2b660afe188d6db0932741364524/pkg/ccl/backupccl/manifest_handling.go#L387)):*
> ```Go
> 		defaultURIs[0] = from[0][0]
> 		mainBackupManifests[0] = baseManifest
> 		localityInfo[0], err = getLocalityInfo(ctx, baseStores, from[0], baseManifest, encryption, "")
> ```

[nit] could you add a `/* prefix */` comment on the last arg?
___
*[pkg/ccl/backupccl/partitioned_backup_test.go, line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45255#-M0sAfAF3WU5ZBQevdh-:-M0sAfAG5EYs2LHOKXXG:bv9jy59) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d4115c70e3f2b660afe188d6db0932741364524/pkg/ccl/backupccl/partitioned_backup_test.go#L96)):*
> ```Go
> 	for _, tc := range testCases {
> 		t.Run(tc.name, func(t *testing.T) {
> 			defaultURI, urisByLocality, err := getURIsByLocalityKV(tc.input, "")
> ```

[nit] could you add a `/* appendPath */` comment to the last arg?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45255)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea)

___
*[pkg/ccl/backupccl/backup_planning.go, line 470 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45255#-M0rzzKz6acT5IQmSvvc:-M0smAdVA-YVSbzAgZFX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d4115c70e3f2b660afe188d6db0932741364524/pkg/ccl/backupccl/backup_planning.go#L470)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

[nit] typo: tha -> that
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/backup_test.go, line 414 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45255#-M0s-9OA8cAqCP0tD_38:-M0skYBD35XpY8i74qJl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d4115c70e3f2b660afe188d6db0932741364524/pkg/ccl/backupccl/backup_test.go#L414)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Can we remove these commented out lines?
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/manifest_handling.go, line 304 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45255#-M0s-ISb68MvbOGdw2KG:-M0skj9t1y3R7b2Zk-V1:b-e4qxbt) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d4115c70e3f2b660afe188d6db0932741364524/pkg/ccl/backupccl/manifest_handling.go#L304)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Have you considered storing the previous backups as a property of the backup manifest? The advantage I see of doing it that way would be that we could arbitrarily change the naming structure of the incremental backup files in the future. (e.g. say we wanted to change them to be a hash of their contents, or just a UUID.)
</blockquote></details>

I thought about this, but I really _don't_ want to rewrite/modify the original manifest. We could make a meta-manifest but I thought it might be useful to allow manual movement of the directories -- ie you can move/delete the layers if you want to do something fancy. Added a comment.
___
*[pkg/ccl/backupccl/manifest_handling.go, line 387 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45255#-M0s-mKu9GjM7avEI3Wh:-M0sm6_jEnPT8oK11syN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d4115c70e3f2b660afe188d6db0932741364524/pkg/ccl/backupccl/manifest_handling.go#L387)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

[nit] could you add a `/* prefix */` comment on the last arg?
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/partitioned_backup_test.go, line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45255#-M0sAfAF3WU5ZBQevdh-:-M0slS4q8YJI-7u0z3Q5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d4115c70e3f2b660afe188d6db0932741364524/pkg/ccl/backupccl/partitioned_backup_test.go#L96)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

[nit] could you add a `/* appendPath */` comment to the last arg?
</blockquote></details>

Done.

**Review by pbardea — APPROVED** [review]

**Comment by dt** [comment]
TFTR!

I saw a failure in the new test on the first CI run, but it went away on re-run.
I threw my laptop at stressing this for an hour and couldn't reproduce the flake, and thenn threw `roachprod-stressrace PKG=./pkg/ccl/backupccl TESTS=TestBackupRestoreAppend`  at it for an hour as well and haven't seen that txn restart error again, so maybe it was actually just a one-time fluke?

bors r+

**Pull request merged**
