### PR TITLE
sql: Remove GRANT privilege

### PR DESCRIPTION
**Pull request by ecwall**
The GRANT privilege has been replaced by the more granular WITH GRANT OPTION
that gives control over which privileges are allowed to be granted.

Release note (sql change): Remove deprecated GRANT privilege.

### CODE REVIEW

**Review by Xiang-Gu — COMMENTED** [review]
Can you give me a bit of context about deprecating GRANT as I'm trying to learn something from pr reviews? 

We initially had the `GRANT` option but later decided to deprecate it and introduced `GRANT OPTION`. I saw that the majority of this PR deletes codes pertaining to the support of both concepts. Does this mean, prior to 22.2, we allow users to grant/revoke `GRANT` privileges (with of course certain reminders)? And, starting in 22.2, this will be completed removed and users must use `GRANT OPTION`? In general, I'm not familiar about how to deprecate something in software engineering. Do you mind also telling a bit on CRL's approach to deprecating something using this as an example? And how does it work together with the migration framework we had in CRL?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81310#-:-N3QkcVu6EluPtkX45iU:ba5kadj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan, @rafiss, @RichardJCai, and @stevendanna)

**Comment by RichardJCai** [comment]
> Can you give me a bit of context about deprecating GRANT as I'm trying to learn something from pr reviews?
> 
> We initially had the `GRANT` option but later decided to deprecate it and introduced `GRANT OPTION`. I saw that the majority of this PR deletes codes pertaining to the support of both concepts. Does this mean, prior to 22.2, we allow users to grant/revoke `GRANT` privileges (with of course certain reminders)? And, starting in 22.2, this will be completed removed and users must use `GRANT OPTION`? In general, I'm not familiar about how to deprecate something in software engineering. Do you mind also telling a bit on CRL's approach to deprecating something using this as an example? And how does it work together with the migration framework we had in CRL?
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81310#-:-N3QkcVu6EluPtkX45iU:ba5kadj)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan, @rafiss, @RichardJCai, and @stevendanna)



> Can you give me a bit of context about deprecating GRANT as I'm trying to learn something from pr reviews?
> 
> We initially had the `GRANT` option but later decided to deprecate it and introduced `GRANT OPTION`. I saw that the majority of this PR deletes codes pertaining to the support of both concepts. Does this mean, prior to 22.2, we allow users to grant/revoke `GRANT` privileges (with of course certain reminders)? And, starting in 22.2, this will be completed removed and users must use `GRANT OPTION`? In general, I'm not familiar about how to deprecate something in software engineering. Do you mind also telling a bit on CRL's approach to deprecating something using this as an example? And how does it work together with the migration framework we had in CRL?
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81310#-:-N3QkcVu6EluPtkX45iU:ba5kadj)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan, @rafiss, @RichardJCai, and @stevendanna)

I can sync with you offline about these questions.

**Review by rafiss — CHANGES_REQUESTED** [review]
> Reviewed 5 of 26 files at r1, 11 of 48 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81310)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall, @otan, @RichardJCai, and @stevendanna)

___
*[`pkg/sql/privilege/privilege.go` line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81310#-N3R9piu3KukUO8hHuJr:-N3R9piu3KukUO8hHuJs:bd9h7vx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56398e7933084e2492a08acb885a841b52d92e1/pkg/sql/privilege/privilege.go#L39)):*
> ```Go
> 	// Deprecated: GRANT is a placeholder to make sure that 4 is not reused.
> 	// It was previously used for the GRANT privilege that has been replaced with the more granular Privilege.GrantOption.
> 	GRANT      Kind = 4
> ```

nit: to make this even louder, can you rename it to `GRANT_DEPRECATED`?

i think you'd the need to make a custom string for it, so it still is formatted as `GRANT` in strings. see the "linecomment" docs at https://pkg.go.dev/golang.org/x/tools/cmd/stringer?utm_source=godoc
___
*[`pkg/sql/privilege/privilege.go` line 79 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81310#-N3RANMI6vcleJQELKiD:-N3RANMJ5ShSuMXfpebW:b-mg7wgn) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dcd87f64630db5613dbb63958cbbe67ad3728f3/pkg/sql/privilege/privilege.go#L79)):*
> ```Go
> // Predefined sets of privileges.
> var (
> 	AllPrivileges    = List{ALL, CONNECT, CREATE, DROP, GRANT, SELECT, INSERT, DELETE, UPDATE, USAGE, ZONECONFIG}
> ```

i believe we cannot remove the GRANT privilege from these lists unless we also write an upgrade migration that removes GRANT from existing descriptors. this can be achieved by updating `catprivilege.MaybeFixPrivileges` to remove GRANT. (otherwise `validateDesc` would fail on any object that used to have GRANT on it)

however, that might be more trouble than its worth (the  schema team might have an opinion here). if we don't do that, then we should just leave GRANT here with a comment
___
*[`pkg/upgrade/upgrades/upgrades.go` line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81310#-N3RBAwt0TCUlkg7XbPf:-N3RBAwt0TCUlkg7XbPg:b-tha6m) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dcd87f64630db5613dbb63958cbbe67ad3728f3/pkg/upgrade/upgrades/upgrades.go#L96)):*
> ```Go
> 	upgrade.NewTenantUpgrade(
> 		"track grant options on users and enable granting/revoking with them",
> 		toCV(clusterversion.ValidateGrantOption),
> ```

i think we should leave the clusterversion in the code until they are all cleaned up later
___
*[`pkg/sql/logictest/testdata/logic_test/alter_default_privileges_for_all_roles` line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81310#-N3RBKEW6nscTW8gZZoi:-N3RBKEW6nscTW8gZZoj:b-hh43ev) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56398e7933084e2492a08acb885a841b52d92e1/pkg/sql/logictest/testdata/logic_test/alter_default_privileges_for_all_roles#L92)):*
> ```
> test           public       t6          admin      ALL             true
> test           public       t6          root       ALL             true
> test           public       t6          testuser   ALL             false
> ```

ah i see what you mean. this used to be true because `HasPrivilege(GRANT)` would be true for the owner, always

lets double check what PG does. i'm guessing either way, it should be fine for us to return true for the owner having the grant option

**Review by RichardJCai — CHANGES_REQUESTED** [review]
> Reviewed 5 of 26 files at r1, 37 of 48 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81310)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall, @otan, @rafiss, and @stevendanna)

___
*[`pkg/sql/privilege/privilege.go` line 79 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81310#-N3RANMI6vcleJQELKiD:-N3_v5fqAdSdY1pfGeMK:b-nfsxrs) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dcd87f64630db5613dbb63958cbbe67ad3728f3/pkg/sql/privilege/privilege.go#L79)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i believe we cannot remove the GRANT privilege from these lists unless we also write an upgrade migration that removes GRANT from existing descriptors. this can be achieved by updating `catprivilege.MaybeFixPrivileges` to remove GRANT. (otherwise `validateDesc` would fail on any object that used to have GRANT on it)

however, that might be more trouble than its worth (the  schema team might have an opinion here). if we don't do that, then we should just leave GRANT here with a comment
</blockquote></details>

+1

I'd be okay with just leaving it as `DEPRECATED_GRANT` in this PR.
___
*[`pkg/sql/logictest/testdata/logic_test/alter_default_privileges_with_grant_option` line 514 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81310#-N3_tPm5D2t8S1VN4_SF:-N3_tPm5D2t8S1VN4_SG:b-353tew) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56398e7933084e2492a08acb885a841b52d92e1/pkg/sql/logictest/testdata/logic_test/alter_default_privileges_with_grant_option#L514)):*
> ```
> test           public       seq1        testuser2  CREATE          true
> 
> # TODO: implement the grant/revoke for sequence? Can't do much more that this in terms of testing otherwise
> ```

Don't we already support syntax for `grant/revoke` on sequence?
___
*[`pkg/sql/logictest/testdata/logic_test/grant_database` line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81310#-N3_taPQEs-Ca1kYUOEF:-N3_taPQEs-Ca1kYUOEG:b3prc0i) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56398e7933084e2492a08acb885a841b52d92e1/pkg/sql/logictest/testdata/logic_test/grant_database#L41)):*
> ```
> a  admin      ALL      true
> a  public     CONNECT  false
> a  readwrite  ALL      false
> ```

nit: Maybe we should just grant ALL with grant option in cases like this to reduce churn? I don't think it really matters though.
___
*[`pkg/sql/logictest/testdata/logic_test/grant_sequence` line 94 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81310#-N3_u6g_E14Wfh4lJUPu:-N3_u6g_E14Wfh4lJUPv:b-8m7fp4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dcd87f64630db5613dbb63958cbbe67ad3728f3/pkg/sql/logictest/testdata/logic_test/grant_sequence#L94)):*
> ```
> 
> query T noticetrace
> GRANT CREATE, DROP, USAGE ON SEQUENCE a TO readwrite
> ```

nit: WITH GRANT OPTION here?
___
*[`pkg/sql/logictest/testdata/logic_test/pg_catalog_pg_default_acl` line 22 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81310#-N3_uJecEaxbPckNGigu:-N3_uJecEaxbPckNGigv:b-958x7h) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56398e7933084e2492a08acb885a841b52d92e1/pkg/sql/logictest/testdata/logic_test/pg_catalog_pg_default_acl#L22)):*
> ```
> 
> statement ok
> ALTER DEFAULT PRIVILEGES GRANT ALL ON TABLES TO foo, bar;
> ```

Do WITH GRANT OPTION here so the `*` formatting cases are tested.
___
*[`pkg/sql/logictest/testdata/logic_test/privilege_builtins` line 775 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81310#-N3_uRkn25qw1AI5D7x4:-N3_uRkn25qw1AI5D7x5:b-mkh2hl) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56398e7933084e2492a08acb885a841b52d92e1/pkg/sql/logictest/testdata/logic_test/privilege_builtins#L775)):*
> ```
>        has_sequence_privilege('seq', 'UPDATE WITH GRANT OPTION')
> ----
> false  false  false
> ```

We should test the true case here as well
___
*[`pkg/sql/catalog/descs/collection_test.go` line 562 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81310#-N3_uftB1ino-LJF8U3E:-N3_uftB1ino-LJF8U3F:b-8so11) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56398e7933084e2492a08acb885a841b52d92e1/pkg/sql/catalog/descs/collection_test.go#L562)):*
> ```Go
> 			return err
> 		}
> 		// Set version lower than minimum to force post-deserialization change
> ```

nit: period
___
*[`pkg/upgrade/upgrades/remove_invalid_database_privileges_external_test.go` line 122 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81310#-N3_un4l8xL52OKHBr5_:-N3_un4l8xL52OKHBr5a:b-ewpj8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56398e7933084e2492a08acb885a841b52d92e1/pkg/upgrade/upgrades/remove_invalid_database_privileges_external_test.go#L122)):*
> ```Go
> 		[][]string{{clusterversion.ByKey(clusterversion.RemoveIncompatibleDatabasePrivileges).String()}})
> 
> 	tdb.CheckQueryResults(t, "SHOW GRANTS ON DATABASE test", [][]string{
> ```

As a side note we can remove this migration and test as well

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81310)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall, @otan, @rafiss, @RichardJCai, and @stevendanna)

___
*[`pkg/sql/privilege/privilege.go` line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81310#-N3R9piu3KukUO8hHuJr:-N3aBqu6CnY6PSrs5u7N:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56398e7933084e2492a08acb885a841b52d92e1/pkg/sql/privilege/privilege.go#L39)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: to make this even louder, can you rename it to `GRANT_DEPRECATED`?

i think you'd the need to make a custom string for it, so it still is formatted as `GRANT` in strings. see the "linecomment" docs at https://pkg.go.dev/golang.org/x/tools/cmd/stringer?utm_source=godoc
</blockquote></details>

Done.
___
*[`pkg/sql/privilege/privilege.go` line 79 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81310#-N3RANMI6vcleJQELKiD:-N3aAeTr24q3pVqjrZE1:by31y6e) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dcd87f64630db5613dbb63958cbbe67ad3728f3/pkg/sql/privilege/privilege.go#L79)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

+1

I'd be okay with just leaving it as `DEPRECATED_GRANT` in this PR.
</blockquote></details>

I restored the migration code which already was already removing any privileges not present in these lists.
___
*[`pkg/upgrade/upgrades/upgrades.go` line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81310#-N3RBAwt0TCUlkg7XbPf:-N3aBvSd5hN7IIcn9jU4:buxsxio) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dcd87f64630db5613dbb63958cbbe67ad3728f3/pkg/upgrade/upgrades/upgrades.go#L96)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think we should leave the clusterversion in the code until they are all cleaned up later
</blockquote></details>

I changed this to `clusterversion.Start22_2` so that it is run for 22.2, but it is calling the same migration function. What does leaving the old cluster version do?
___
*[`pkg/sql/logictest/testdata/logic_test/alter_default_privileges_for_all_roles` line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81310#-N3RBKEW6nscTW8gZZoi:-N3aCe2p8FgHwLIRDrBN:b-yxlyaw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56398e7933084e2492a08acb885a841b52d92e1/pkg/sql/logictest/testdata/logic_test/alter_default_privileges_for_all_roles#L92)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ah i see what you mean. this used to be true because `HasPrivilege(GRANT)` would be true for the owner, always

lets double check what PG does. i'm guessing either way, it should be fine for us to return true for the owner having the grant option
</blockquote></details>

I created another ticket to address this since I wasn't sure where the fix would go. https://github.com/cockroachdb/cockroach/issues/82162
___
*[`pkg/sql/logictest/testdata/logic_test/alter_default_privileges_with_grant_option` line 514 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81310#-N3_tPm5D2t8S1VN4_SF:-N3aCChU342eWBdUWBZz:b-fxe8w5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56398e7933084e2492a08acb885a841b52d92e1/pkg/sql/logictest/testdata/logic_test/alter_default_privileges_with_grant_option#L514)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Don't we already support syntax for `grant/revoke` on sequence?
</blockquote></details>

I based this test file on an old version which had this comment and I accidentally left it in.  Deleted this line since it no longer applies.
___
*[`pkg/sql/logictest/testdata/logic_test/grant_database` line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81310#-N3_taPQEs-Ca1kYUOEF:-N3aDyGxDo2oNS7Jw9SX:by6rfuk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56398e7933084e2492a08acb885a841b52d92e1/pkg/sql/logictest/testdata/logic_test/grant_database#L41)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

nit: Maybe we should just grant ALL with grant option in cases like this to reduce churn? I don't think it really matters though.
</blockquote></details>

Good idea, updated.

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81310)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan, @rafiss, @RichardJCai, and @stevendanna)

___
*[`pkg/sql/logictest/testdata/logic_test/grant_sequence` line 94 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81310#-N3_u6g_E14Wfh4lJUPu:-N3e9AYg7yfv8m5CP2vM:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dcd87f64630db5613dbb63958cbbe67ad3728f3/pkg/sql/logictest/testdata/logic_test/grant_sequence#L94)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

nit: WITH GRANT OPTION here?
</blockquote></details>

Done
___
*[`pkg/sql/logictest/testdata/logic_test/pg_catalog_pg_default_acl` line 22 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81310#-N3_uJecEaxbPckNGigu:-N3e9k0N8KDvbeCPhb_n:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56398e7933084e2492a08acb885a841b52d92e1/pkg/sql/logictest/testdata/logic_test/pg_catalog_pg_default_acl#L22)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Do WITH GRANT OPTION here so the `*` formatting cases are tested.
</blockquote></details>

Done
___
*[`pkg/sql/logictest/testdata/logic_test/privilege_builtins` line 775 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81310#-N3_uRkn25qw1AI5D7x4:-N3eV0TVEw5wK9S6xpxB:b3sfcxu) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56398e7933084e2492a08acb885a841b52d92e1/pkg/sql/logictest/testdata/logic_test/privilege_builtins#L775)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

We should test the true case here as well
</blockquote></details>

It looks like this is partially broken.  I created this issue to look into it more https://github.com/cockroachdb/cockroach/issues/82414
___
*[`pkg/sql/catalog/descs/collection_test.go` line 562 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81310#-N3_uftB1ino-LJF8U3E:-N3eBIQr9F0NMYeefqP5:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56398e7933084e2492a08acb885a841b52d92e1/pkg/sql/catalog/descs/collection_test.go#L562)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

nit: period
</blockquote></details>

Done
___
*[`pkg/upgrade/upgrades/remove_invalid_database_privileges_external_test.go` line 122 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81310#-N3_un4l8xL52OKHBr5_:-N3eDABo4unSWkxo_Gi_:biaqi5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56398e7933084e2492a08acb885a841b52d92e1/pkg/upgrade/upgrades/remove_invalid_database_privileges_external_test.go#L122)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

As a side note we can remove this migration and test as well
</blockquote></details>

I created an issue to do this separately https://github.com/cockroachdb/cockroach/issues/82407

**Review by RichardJCai — APPROVED** [review]
> Reviewed 7 of 9 files at r3, 2 of 2 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81310)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall, @otan, @rafiss, @RichardJCai, and @stevendanna)

___
*[`pkg/upgrade/upgrades/remove_grant_migration.go` line 21 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/81310#-N3u0Ddg9vqhv4Iq65tF:-N3u0DdhDxAc-u8AnoHQ:b-95m1dp) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fef87595963aad57dca2c41d6e36470d2832e83/pkg/upgrade/upgrades/remove_grant_migration.go#L21)):*
> ```Go
> )
> 
> // removeGrantMigration iterates through every descriptor and sets a user's grant option bits
> ```

Comment is out of date now.
___
*[`pkg/upgrade/upgrades/upgrades.go` line 96 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/81310#-N3u-LUkCcYOlp0HJZZ1:-N3u-LUkCcYOlp0HJZZ2:b-ii0ab) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fef87595963aad57dca2c41d6e36470d2832e83/pkg/upgrade/upgrades/upgrades.go#L96)):*
> ```Go
> 	upgrade.NewTenantUpgrade(
> 		"remove grant privilege from users",
> 		toCV(clusterversion.Start22_2),
> ```

You should add a new cluster version

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81310)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan, @rafiss, @RichardJCai, and @stevendanna)

___
*[`pkg/upgrade/upgrades/remove_grant_migration.go` line 21 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/81310#-N3u0Ddg9vqhv4Iq65tF:-N3uDhBK2AK4GzBIsVVP:b-oz8o77) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fef87595963aad57dca2c41d6e36470d2832e83/pkg/upgrade/upgrades/remove_grant_migration.go#L21)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Comment is out of date now.
</blockquote></details>

Good catch
___
*[`pkg/upgrade/upgrades/upgrades.go` line 96 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/81310#-N3u-LUkCcYOlp0HJZZ1:-N3uDflHAO2qlyVmkvuT:b-8b11j9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fef87595963aad57dca2c41d6e36470d2832e83/pkg/upgrade/upgrades/upgrades.go#L96)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

You should add a new cluster version
</blockquote></details>

Added

**Comment by ecwall** [comment]
bors r=RichardJCai

**Comment by lnhsingh** [comment]
@ecwall @rafiss - is this a new deprecation that should be called out in our v22.2.0 release notes? If so, would the following be a sufficient release note describing the deprecation?

> The `GRANT` privilege has been removed and replaced by the more granular `WITH GRANT OPTION`, which provides control over which privileges are allowed to be granted.

(This assumes that it was removed this version)

For more examples, you can check out [previous GA release notes](https://www.cockroachlabs.com/docs/releases/v22.1.html#v22-1-0-deprecations).

**Comment by rafiss** [comment]
@lnhsingh that's right - v22.2 is where GRANT is first removed, and that note looks good!

**Pull request merged**
