### PR TITLE
cli: fix a data race with the pgx dialer

### LINKED ISSUE #82333: cli/clisqlclient: TestConnRecover failed
cli/clisqlclient.TestConnRecover [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/5348745?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/5348745?buildTab=artifacts#/) on master @ [5a54758ce89e866b4fe28c0df74bd610973c6918](https://github.com/cockroachdb/cockroach/commits/5a54758ce89e866b4fe28c0df74bd610973c6918):

```
=== RUN   TestConnRecover
    test_log_scope.go:79: test logs captured to: /artifacts/tmp/_tmp/a2a154a9341514ba494a763a055d74bf/logTestConnRecover3829431345
    test_log_scope.go:80: use -show-logs to present logs inline
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
Parameters in this failure:

- TAGS=bazel,gss
</p>
</details>
/cc @cockroachdb/server
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestConnRecover.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-16347

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/82333

Release note: None

### CODE REVIEW

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82410)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/cli/clisqlclient/conn.go` line 160 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82410#-N3eOjmZEsQ_lHbMcBbE:-N3eOjmZEsQ_lHbMcBbF:b-p2qmmv) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b7807ba1f596dc30a9db67f73e481b44a8bc879/pkg/cli/clisqlclient/conn.go#L160)):*
> ```Go
> 
> // The default pgx dialer uses a KeepAlive of 5 minutes, which we don't want.
> var defaultDialer = struct {
> ```

i feel like i might be using the wrong language conventions here. should i factor this differently?

i went with this since i wanted defaultDialer to be a singleton. but maybe it would be better to define a custom struct type instead of an anonymous one.

**Review by knz — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82410)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

___
*[`pkg/cli/clisqlclient/conn.go` line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82410#-N3eWVBt0418L1nuN59b:-N3eWVBu3u0c8wSWllHG:b-2hb489) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b7807ba1f596dc30a9db67f73e481b44a8bc879/pkg/cli/clisqlclient/conn.go#L199)):*
> ```Go
> 		defaultDialer.mu.d.Timeout = 0
> 		if base.ConnectTimeout > 0 {
> 			defaultDialer.mu.d.Timeout = base.ConnectTimeout
> ```

That doesn't seem right: if there are concurrent calls to EnsureConn with different timeout settings, they will stomp over each other.

May I suggest this instead:
- no global variable
- here, the following:

dialer := &net.Dialer{Timeout: base.ConnectTimeout}
base.DialFunc = func(ctx context.Context, network, addr string) (net.Conn, error) {
		return dialer.DialContext(ctx, network, addr)
}

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82410)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/cli/clisqlclient/conn.go` line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82410#-N3eWVBt0418L1nuN59b:-N3eWxhoA9X3c5MLCYyE:b-9u0m53) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b7807ba1f596dc30a9db67f73e481b44a8bc879/pkg/cli/clisqlclient/conn.go#L199)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

That doesn't seem right: if there are concurrent calls to EnsureConn with different timeout settings, they will stomp over each other.

May I suggest this instead:
- no global variable
- here, the following:

dialer := &net.Dialer{Timeout: base.ConnectTimeout}
base.DialFunc = func(ctx context.Context, network, addr string) (net.Conn, error) {
		return dialer.DialContext(ctx, network, addr)
}

</blockquote></details>

ok yeah, this probably is the right move

now that i think of it, the variable was only global because i thought it needed to resoveb those "cannot assign address" errors.

**Review by knz — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82410)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Comment by rafiss** [comment]
tftr!

bors r=knz

**Pull request merged**
