### PR TITLE
.github: update CODEOWNERS

### PR DESCRIPTION
**Pull request by tbg**
We've had the Replication team for a while and it's about time it
started formally owning some files.

I arrived at these updates by going through

```
go run ./pkg/cmd/whoownsit --walk ./pkg/kv/kvserver/
```

I then noticed Github's validation of the CODEOWNERs file failed, which inspired the subsequent commits. They introduce a `#!` syntax such that we can selectively hide teams from Github.

cc @dt and @nickvigilante, the @cockroachdb/tenant-streaming and @cockroachdb/docs-infra-prs need the repo added to them so that Github accepts them. I worked around that for now by using the newly introduced `#!` but the teams won't get PR pings.

Epic: none
Release note: None

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
Nice, thanks!

**Comment by erikgrinaker** [comment]
We should probably own `kv/kvclient/rangefeed` and `kv/kvclient/kvcoord/dist_sender*rangefeed*.go` too.

**Comment by dt** [comment]
> the tenant-streaming ... team needs the repo added

Eh, this should just be the DR PRs team, not a distinct GitHub team.

**Comment by renatolabs** [comment]
Tests need to be fixed, but otherwise LGTM!

**Comment by tbg** [comment]
> > the tenant-streaming ... team needs the repo added
> 
> Eh, this should just be the DR PRs team, not a distinct GitHub team.

🤷🏽 https://github.com/cockroachdb/cockroach/commit/667b46adb3138af795867fd17c196c01af049993

I'll avoid meddling with this further for now.

**Comment by tbg** [comment]
bors r=erikgrinaker

**Pull request merged**
