### PR TITLE
bazel: upgrade `rules_foreign_cc` to 0.7

### LINKED ISSUE #71306: bazel: apply gcc10 fix to kerberos build in bazel
Original commit: 0de1fd4d19b9cf39ea2c4cce668714c8ec9394b4

Epic CRDB-8036

### PR DESCRIPTION
**Pull request by rickystewart**
Also add `-fcommon` to compile flags for `krb5`.

Closes #71306.

Release note: None

### CODE REVIEW

**Comment by rickystewart** [comment]
whoops, the `geos` definition needs to be tweaked a bit. i'll get it tomorrow.

**Review by rail — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73819#-:-Mr3mq0s9IrgniNy_u4k:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rail)

**Comment by rickystewart** [comment]
bors r=rail

**Comment by irfansharif** [comment]
This might've broken bazel builds. Things work just fine in the commit before (and `dev doctor` turns up nothing).

```
$ dev build short -- --verbose_failures --sandbox_debug
$ bazel build //pkg/cmd/cockroach-short:cockroach-short --verbose_failures --sandbox_debug
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
INFO: Analyzed target //pkg/cmd/cockroach-short:cockroach-short (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_irfansharif/99e666e4e674209ecdb66b46371278df/external/com_google_protobuf/BUILD:154:11: Compiling src/google/protobuf/any.cc failed: (Exit 1): sandbox-exec failed: error executing command
  (cd /private/var/tmp/_bazel_irfansharif/99e666e4e674209ecdb66b46371278df/sandbox/darwin-sandbox/186/execroot/cockroach && \
  exec env - \
    PATH=/bin:/usr/bin:/usr/local/bin \
    PWD=/proc/self/cwd \
    TMPDIR=/var/folders/3j/6fxg9ckn21g5xm0z_06r7gzr0000gn/T/ \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_irfansharif/99e666e4e674209ecdb66b46371278df/sandbox/darwin-sandbox/186/sandbox.sb /var/tmp/_bazel_irfansharif/install/d3bd16a8b22c859ba58f5dca04a9b1aa/process-wrapper '--timeout=0' '--kill_delay=15' external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/_objs/protobuf/any.d '-frandom-seed=bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/_objs/protobuf/any.o' -iquote external/com_google_protobuf -iquote bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/com_google_protobuf -iquote external/zlib -iquote bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/zlib -isystem external/com_google_protobuf/src -isystem bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/src -isystem external/zlib/zlib/include -isystem bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/zlib/zlib/include -g0 -g0 -DHAVE_PTHREAD -DHAVE_ZLIB -Woverloaded-virtual -Wno-sign-compare -Wno-unused-function -Wno-write-strings -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/com_google_protobuf/src/google/protobuf/any.cc -o bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/_objs/protobuf/any.o)
external/com_google_protobuf/src/google/protobuf/any.cc:48:19: error: out-of-line definition of 'PackFrom' does not match any declaration in 'google::protobuf::internal::AnyMetadata'
void AnyMetadata::PackFrom(const Message& message,
                  ^~~~~~~~
external/com_google_protobuf/src/google/protobuf/any.cc:50:14: error: no member named 'SetNoArena' in 'google::protobuf::internal::ArenaStringPtr'
  type_url_->SetNoArena(
  ~~~~~~~~~  ^
external/com_google_protobuf/src/google/protobuf/any.cc:53:37: error: no member named 'MutableNoArena' in 'google::protobuf::internal::ArenaStringPtr'
  message.SerializeToString(value_->MutableNoArena(
                            ~~~~~~  ^
external/com_google_protobuf/src/google/protobuf/any.cc:61:43: error: no member named 'GetNoArena' in 'google::protobuf::internal::ArenaStringPtr'
  return message->ParseFromString(value_->GetNoArena());
                                  ~~~~~~  ^
4 errors generated.
Target //pkg/cmd/cockroach-short:cockroach-short failed to build
ERROR: /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/storage/enginepb/BUILD.bazel:35:11 GoCompilePkg pkg/storage/enginepb/enginepb.a failed: (Exit 1): sandbox-exec failed: error executing command
  (cd /private/var/tmp/_bazel_irfansharif/99e666e4e674209ecdb66b46371278df/sandbox/darwin-sandbox/186/execroot/cockroach && \
  exec env - \
    PATH=/bin:/usr/bin:/usr/local/bin \
    PWD=/proc/self/cwd \
    TMPDIR=/var/folders/3j/6fxg9ckn21g5xm0z_06r7gzr0000gn/T/ \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_irfansharif/99e666e4e674209ecdb66b46371278df/sandbox/darwin-sandbox/186/sandbox.sb /var/tmp/_bazel_irfansharif/install/d3bd16a8b22c859ba58f5dca04a9b1aa/process-wrapper '--timeout=0' '--kill_delay=15' external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/_objs/protobuf/any.d '-frandom-seed=bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/_objs/protobuf/any.o' -iquote external/com_google_protobuf -iquote bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/com_google_protobuf -iquote external/zlib -iquote bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/zlib -isystem external/com_google_protobuf/src -isystem bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/src -isystem external/zlib/zlib/include -isystem bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/zlib/zlib/include -g0 -g0 -DHAVE_PTHREAD -DHAVE_ZLIB -Woverloaded-virtual -Wno-sign-compare -Wno-unused-function -Wno-write-strings -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/com_google_protobuf/src/google/protobuf/any.cc -o bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/_objs/protobuf/any.o)
INFO: Elapsed time: 2.294s, Critical Path: 2.03s
INFO: 17 processes: 17 internal.
FAILED: Build did NOT complete successfully
ERROR: exit status 1
```

**Comment by irfansharif** [comment]
Getting rid of `--incompatible_enable_cc_toolchain_resolution` fixed it, do you know what to make of it? I couldn't quite figure out from https://github.com/bazelbuild/bazel/issues/7260.

**Pull request merged**
