### PR TITLE
roachtest: check metrics during multi-region TPC-C runs

### LINKED ISSUE #65911: multiregion: setup DRTs
This issue is for coordinating work required to get somewhere closer to [automatic DRTs](https://docs.google.com/document/d/1vKnX6QWcDEekPjg4UK3B_lrcjbo_C3032jOgri5LHC0/edit).

In particular, our MVP here is to setup a way of making a DRT for multi-region work using TPC-C.

Steps:
* [ ] Setup `--client-partitions` to correctly send local traffic to all the tables. As of #65600, the new TPC-C workload is initialised on all cockroach machines, but the workload inserts data into other nodes resulting in un-optimised results. We should ensure the ./cockroach workload talks to the local region in the same node.
* [ ] Instrument workload to [export prometheus metrics](https://prometheus.io/docs/guides/go-application/) NOTE: unclear whether we should be using metrics.PrometheusExporter instead, but that's heavily tied to `pkg/server/status` which has a bunch of cruft we do NOT need
* [ ] Update the [Chaos](https://github.com/cockroachdb/cockroach/blob/5fb0e29d1da5d09d1d869c2324d14160c0fbd71f/pkg/cmd/roachtest/chaos.go#L37) tooling to also log metrics and check that metrics perform as expect.

### LINKED ISSUE #66953: roachtest: tpcc/multiregion/survive=region/chaos=true failed
roachtest.tpcc/multiregion/survive=region/chaos=true [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3125303&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3125303&tab=artifacts#/tpcc/multiregion/survive=region/chaos=true) on master @ [d43d9fddbebac7eff03804a7d86f7b6af119f24f](https://github.com/cockroachdb/cockroach/commits/d43d9fddbebac7eff03804a7d86f7b6af119f24f):

```
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2456
		  | golang.org/x/sync/errgroup.(*Group).Go.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:57
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1371
		Wraps: (2) output in run_122208.770_n10_cockroach_workload_run_tpcc
		Wraps: (3) /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-3125303-1624860639-76-n10cpu4-geo:10 -- ./cockroach workload run tpcc --warehouses=15 --histograms=perf/stats.json --method=simple --wait=false --tolerate-errors --survival-goal=region --regions=us-east1,us-west1,europe-west2 --partitions=3 --ramp=5m0s --duration=1h30m0s --prometheus-port=2120 --pprofport=33334 --partition-affinity=0 {pgurl:1-3} returned
		  | stderr:
		  | I210628 12:22:13.555772 1 workload/cli/run.go:396  [-] 1  creating load generator...
		  |
		  | stdout:
		  | Initializing 150 connections...
		Wraps: (4) secondary error attachment
		  | signal: killed
		  | (1) signal: killed
		  | Error types: (1) *exec.ExitError
		Wraps: (5) context canceled
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *main.withCommandDetails (4) *secondary.withSecondaryError (5) *errors.errorString

	cluster.go:2478,tpcc.go:247,tpcc.go:564,test_runner.go:758: monitor failure: monitor task failed: t.Fatal() was called
		(1) attached stack trace
		  -- stack trace:
		  | main.(*monitor).WaitE
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2466
		  | main.(*monitor).Wait
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2474
		  | main.runTPCC
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tpcc.go:247
		  | main.registerTPCC.func9
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tpcc.go:564
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:758
		Wraps: (2) monitor failure
		Wraps: (3) attached stack trace
		  -- stack trace:
		  | main.(*monitor).wait.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2522
		Wraps: (4) monitor task failed
		Wraps: (5) attached stack trace
		  -- stack trace:
		  | main.init
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2436
		  | runtime.doInit
		  | 	/usr/local/go/src/runtime/proc.go:6309
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:208
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1371
		Wraps: (6) t.Fatal() was called
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *withstack.withStack (6) *errutil.leafError
```
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
# From https://go.crdb.dev/p/roachstress, perhaps edited lightly.
caffeinate ./roachstress.sh tpcc/multiregion/survive=region/chaos=true
```
</p>
</p>
</details>
/cc @cockroachdb/multiregion
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*tpcc/multiregion/survive=region/chaos=true.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by otan**
See individual commits for details.

Resolves #65911
Resolves #66953

### CODE REVIEW

**Review by ajstorm — CHANGES_REQUESTED** [review]
I'm not a prometheus expert, so I may have missed something nitty-gritty in there, but overall this looks good.  A few comments added.

> Reviewed 1 of 1 files at r1, 11 of 11 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-:-Mdr8t_n45nsXSLz86GP:b-aruu2m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/cmd/roachtest/chaos.go, line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-MdS9yvGEBb0WpYspwqH:-MdS9yvGEBb0WpYspwqI:b6nm1se) ([raw file](https://github.com/cockroachdb/cockroach/blob/de74b9027abd45be7752354ca7513042d7ab8643/pkg/cmd/roachtest/chaos.go#L52)):*
> ```Go
> 	// first and shutting down gracefully.
> 	DrainAndQuit bool
> 	// ChaosEventCh is a channel that the chaos runner will send events when the
> ```

Super nit: "will send events _on_"?
___
*[pkg/cmd/roachtest/chaos.go, line 85 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-MdSBbbjCp0QFv_y_Xu2:-MdSBbbjCp0QFv_y_Xu3:b-iswk4t) ([raw file](https://github.com/cockroachdb/cockroach/blob/de74b9027abd45be7752354ca7513042d7ab8643/pkg/cmd/roachtest/chaos.go#L85)):*
> ```Go
> 
> func (ch *Chaos) sendEvent(t ChaosEventType, target option.NodeListOption) {
> 	if ch.ChaosEventCh != nil {
> ```

Should this error if the channel is nil?  I'd think the caller might want to know if their event is going to be dropped.
___
*[pkg/cmd/roachtest/chaos.go, line 105 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-MdSCLHpASpoG-lWQJXy:-MdSCLHpASpoG-lWQJXz:bspm1ut) ([raw file](https://github.com/cockroachdb/cockroach/blob/de74b9027abd45be7752354ca7513042d7ab8643/pkg/cmd/roachtest/chaos.go#L105)):*
> ```Go
> 		defer func() {
> 			ch.sendEvent(ChaosEventTypeEnd, nil)
> 			if ch.ChaosEventCh != nil {
> ```

Why are we closing the channel here?  Shouldn't that be done in the caller (which created the channel)?
___
*[pkg/cmd/roachtest/drt.go, line 123 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-Mdr2QJX2_Mw00YN5bh5:-Mdr2QJX2_Mw00YN5bh6:b2uwu9s) ([raw file](https://github.com/cockroachdb/cockroach/blob/de74b9027abd45be7752354ca7513042d7ab8643/pkg/cmd/roachtest/drt.go#L123)):*
> ```Go
> 		},
> 	} {
> 		// Add 10 seconds to fromTime to account for the first data point
> ```

Nit: Should this say "Add one extra interval" instead of 10 seconds?
___
*[pkg/cmd/roachtest/drt.go, line 153 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-Mdr3lk7B7zhWkirGF10:-Mdr3lk7B7zhWkirGF11:b-7fjap0) ([raw file](https://github.com/cockroachdb/cockroach/blob/de74b9027abd45be7752354ca7513042d7ab8643/pkg/cmd/roachtest/drt.go#L153)):*
> ```Go
> 		}
> 		if len(warnings) > 0 {
> 			return errors.Newf("found warnings querying prometheus: %s", warnings)
> ```

Seems a bit odd here that we're escalating warnings to errors.  Would it not be better to log these warnings and continue?
___
*[pkg/cmd/roachtest/drt.go, line 164 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-Mdr3xcl8wCFoYz_x5co:-Mdr3xcl8wCFoYz_x5cp:b-ed9ok9) ([raw file](https://github.com/cockroachdb/cockroach/blob/de74b9027abd45be7752354ca7513042d7ab8643/pkg/cmd/roachtest/drt.go#L164)):*
> ```Go
> 		}
> 		if len(warnings) > 0 {
> 			return errors.Newf("found warnings querying prometheus: %s", warnings)
> ```

Same escalation comment here.
___
*[pkg/cmd/roachtest/drt_test.go, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-Mdr55eLEOjAIG_r6_AJ:-Mdr55eLEOjAIG_r6_AK:by1cm9q) ([raw file](https://github.com/cockroachdb/cockroach/blob/de74b9027abd45be7752354ca7513042d7ab8643/pkg/cmd/roachtest/drt_test.go#L27)):*
> ```Go
> func TestTPCCChaosEventProcessor(t *testing.T) {
> 	ctx := context.Background()
> 	startTime := time.Date(2020, 12, 25, 0, 0, 0, 0, time.UTC)
> ```

:santa: 
___
*[pkg/cmd/roachtest/drt_test.go, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-Mdr68V52XB_g_upQqNo:-Mdr68V66shB7GLhCs0z:b-7vvr3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/de74b9027abd45be7752354ca7513042d7ab8643/pkg/cmd/roachtest/drt_test.go#L50)):*
> ```Go
> 
> 				// Shutdown and restart region1.
> 				{Type: ChaosEventTypePreShutdown, Time: startTime.Add(90 * time.Second), Target: region1},
> ```

Would it be better to have these times defined with intervals/increments rather than hard code them?  (e.g. startDuration = 90, shutdownCompleteTime = startDuration+DefaultScrapeTimeout, etc)
___
*[pkg/cmd/roachtest/drt_test.go, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-Mdr6cv-6IwbeWcGEBLz:-Mdr6cv-6IwbeWcGEBM-:b-gl0nkf) ([raw file](https://github.com/cockroachdb/cockroach/blob/de74b9027abd45be7752354ca7513042d7ab8643/pkg/cmd/roachtest/drt_test.go#L66)):*
> ```Go
> 			mockPromQueries: []expectPromQuery{
> 				// Restart region1.
> 				{q: `workload_tpcc_newOtan_success_total{instance=":2110"}`, t: startTime.Add(105 * time.Second), retVal: 100},
> ```

Above comment applies here too.  I'm not sure how to interpret the numbers here.
___
*[pkg/cmd/roachtest/drt_test.go, line 131 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-Mdr6rBt6WHNjPKL_kpw:-Mdr6rBt6WHNjPKL_kpx:b9frd8o) ([raw file](https://github.com/cockroachdb/cockroach/blob/de74b9027abd45be7752354ca7513042d7ab8643/pkg/cmd/roachtest/drt_test.go#L131)):*
> ```Go
> 				{
> 					nodes:          region1,
> 					prometheusPort: 2110,
> ```

Can we make 2110/1 constants, and use them in the queries above too?
___
*[pkg/cmd/roachtest/drt_test.go, line 173 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-Mdr7Lj-4yFngCV73J75:-Mdr7Lj-4yFngCV73J76:bxiomhl) ([raw file](https://github.com/cockroachdb/cockroach/blob/de74b9027abd45be7752354ca7513042d7ab8643/pkg/cmd/roachtest/drt_test.go#L173)):*
> ```Go
> 				{q: `workload_tpcc_otanLevel_success_total{instance=":2111"}`, t: startTime.Add(180 * time.Second), retVal: 1000},
> 				{q: `workload_tpcc_otanLevel_error_total{instance=":2111"}`, t: startTime.Add(105 * time.Second), retVal: 0},
> 				{q: `workload_tpcc_otanLevel_error_total{instance=":2111"}`, t: startTime.Add(180 * time.Second), retVal: 1000}, // unexpected errors detected
> ```

I'm not following what generates the unexpected errors here.  Can you expand on this comment?
___
*[pkg/cmd/roachtest/drt_test.go, line 206 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-Mdr7U-V8WXlZtIt_pU9:-Mdr7U-V8WXlZtIt_pUA:b-ozwfb7) ([raw file](https://github.com/cockroachdb/cockroach/blob/de74b9027abd45be7752354ca7513042d7ab8643/pkg/cmd/roachtest/drt_test.go#L206)):*
> ```Go
> 				// Restart region1.
> 				{q: `workload_tpcc_newOtan_success_total{instance=":2110"}`, t: startTime.Add(105 * time.Second), retVal: 100},
> 				{q: `workload_tpcc_newOtan_success_total{instance=":2110"}`, t: startTime.Add(180 * time.Second), retVal: 1000}, // successes unexpected
> ```

Same comment here on expanding on this comment.  Why are the successes unexpected?
___
*[pkg/cmd/roachtest/tpcc.go, line 592 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-Mdr-sU55hVjNI_boNGa:-Mdr-sU69Apcx7IimROb:b-q8q34o) ([raw file](https://github.com/cockroachdb/cockroach/blob/de74b9027abd45be7752354ca7513042d7ab8643/pkg/cmd/roachtest/tpcc.go#L592)):*
> ```Go
> 
> 					iter := 0
> 					chaosEventCh := make(chan ChaosEvent)
> ```

Defer close the channel here?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66989)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[pkg/cmd/roachtest/chaos.go, line 85 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-MdSBbbjCp0QFv_y_Xu2:-MdsaDzjBxj43k2-RBnJ:b-bnqtrq) ([raw file](https://github.com/cockroachdb/cockroach/blob/de74b9027abd45be7752354ca7513042d7ab8643/pkg/cmd/roachtest/chaos.go#L85)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Should this error if the channel is nil?  I'd think the caller might want to know if their event is going to be dropped.
</blockquote></details>

there are other places that use chaos that don't need a channel.
it will panic if the channel is nil.
___
*[pkg/cmd/roachtest/chaos.go, line 105 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-MdSCLHpASpoG-lWQJXy:-Mdsa3XwAVnNsf-nM8Bd:bbe3s1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/de74b9027abd45be7752354ca7513042d7ab8643/pkg/cmd/roachtest/chaos.go#L105)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Why are we closing the channel here?  Shouldn't that be done in the caller (which created the channel)?
</blockquote></details>

we want it to be closed when the runner is complete, the caller has no way of knowing that.
___
*[pkg/cmd/roachtest/drt.go, line 153 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-Mdr3lk7B7zhWkirGF10:-Mdsaah_44uYPV3xhlzM:btyhsss) ([raw file](https://github.com/cockroachdb/cockroach/blob/de74b9027abd45be7752354ca7513042d7ab8643/pkg/cmd/roachtest/drt.go#L153)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Seems a bit odd here that we're escalating warnings to errors.  Would it not be better to log these warnings and continue?
</blockquote></details>

I'd rather error here because otherwise there may be a warning that affects the results, from which we have no way of having visibility to without inspecting the logs.
___
*[pkg/cmd/roachtest/drt.go, line 164 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-Mdr3xcl8wCFoYz_x5co:-Mdsak7Y0mLNnKd9oDQi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/de74b9027abd45be7752354ca7513042d7ab8643/pkg/cmd/roachtest/drt.go#L164)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Same escalation comment here.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/drt_test.go, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-Mdr55eLEOjAIG_r6_AJ:-Mdsal-A0dVnIMPmw7yu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/de74b9027abd45be7752354ca7513042d7ab8643/pkg/cmd/roachtest/drt_test.go#L27)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

:santa: 
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/drt_test.go, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-Mdr68V52XB_g_upQqNo:-Mdsc2V7DjqViLx_6H9-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/de74b9027abd45be7752354ca7513042d7ab8643/pkg/cmd/roachtest/drt_test.go#L50)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Would it be better to have these times defined with intervals/increments rather than hard code them?  (e.g. startDuration = 90, shutdownCompleteTime = startDuration+DefaultScrapeTimeout, etc)
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/drt_test.go, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-Mdr6cv-6IwbeWcGEBLz:-Mdsc3UoD7TZK2ce2W6J:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/de74b9027abd45be7752354ca7513042d7ab8643/pkg/cmd/roachtest/drt_test.go#L66)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Above comment applies here too.  I'm not sure how to interpret the numbers here.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/drt_test.go, line 131 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-Mdr6rBt6WHNjPKL_kpw:-MdsdyvC9OvbCiDcBBPv:b-e8hoxt) ([raw file](https://github.com/cockroachdb/cockroach/blob/de74b9027abd45be7752354ca7513042d7ab8643/pkg/cmd/roachtest/drt_test.go#L131)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Can we make 2110/1 constants, and use them in the queries above too?
</blockquote></details>

it's easier for me reading this hardcodedly, the fmt.Sprintf and constant mashing makes it harder.
___
*[pkg/cmd/roachtest/drt_test.go, line 173 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-Mdr7Lj-4yFngCV73J75:-Mdse1Ft97-cCnCBHXi4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/de74b9027abd45be7752354ca7513042d7ab8643/pkg/cmd/roachtest/drt_test.go#L173)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

I'm not following what generates the unexpected errors here.  Can you expand on this comment?
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/drt_test.go, line 206 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-Mdr7U-V8WXlZtIt_pU9:-Mdse1aF-rqVArAB9sGJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/de74b9027abd45be7752354ca7513042d7ab8643/pkg/cmd/roachtest/drt_test.go#L206)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Same comment here on expanding on this comment.  Why are the successes unexpected?
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/tpcc.go, line 592 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-Mdr-sU55hVjNI_boNGa:-MdsaoRj2OI_2KjpSEAY:b-8himhe) ([raw file](https://github.com/cockroachdb/cockroach/blob/de74b9027abd45be7752354ca7513042d7ab8643/pkg/cmd/roachtest/tpcc.go#L592)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Defer close the channel here?
</blockquote></details>

see comment above - the responsibility is deferred to chaos.

**Review by ajstorm — APPROVED** [review]
:lgtm: 

> Reviewed 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-:-MdvZROV0ymwG8QTXjy8:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/cmd/roachtest/drt.go, line 153 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-Mdr3lk7B7zhWkirGF10:-MdvXn9iD__OokIJdbKJ:bylsrc9) ([raw file](https://github.com/cockroachdb/cockroach/blob/de74b9027abd45be7752354ca7513042d7ab8643/pkg/cmd/roachtest/drt.go#L153)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

I'd rather error here because otherwise there may be a warning that affects the results, from which we have no way of having visibility to without inspecting the logs.
</blockquote></details>

OK.  I guess we'll have to see what types of warnings show up, and whether their worth working around.
___
*[pkg/cmd/roachtest/drt_test.go, line 40 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-MdvY7ISBhCC-onebE_M:-MdvY7ISBhCC-onebE_N:b-5qall5) ([raw file](https://github.com/cockroachdb/cockroach/blob/56af30cc0be0b708fb0c3b295b44993dae069cdc/pkg/cmd/roachtest/drt_test.go#L40)):*
> ```Go
> 
> 	firstPreShutdown := startTime.Add(90 * time.Second)
> 	firstShutdownComplete := startTime.Add(95 * time.Second)
> ```

Does it makes sense for this to be `firstShutdownComplete + (DefaultScrapeTimeout * time.Second)`
___
*[pkg/cmd/roachtest/drt_test.go, line 42 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-MdvYM5C5k0YUL2fXb_l:-MdvYM5C5k0YUL2fXb_m:b-vnh2vp) ([raw file](https://github.com/cockroachdb/cockroach/blob/56af30cc0be0b708fb0c3b295b44993dae069cdc/pkg/cmd/roachtest/drt_test.go#L42)):*
> ```Go
> 	firstShutdownComplete := startTime.Add(95 * time.Second)
> 	firstPreStartup := startTime.Add(180 * time.Second)
> 	firstStartupComplete := startTime.Add(185 * time.Second)
> ```

Same comment as above for this one, and a couple below.
___
*[pkg/cmd/roachtest/drt_test.go, line 77 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-MdvYvzA7Ch6m5YsJGgS:-MdvYvzA7Ch6m5YsJGgT:biio5h2) ([raw file](https://github.com/cockroachdb/cockroach/blob/56af30cc0be0b708fb0c3b295b44993dae069cdc/pkg/cmd/roachtest/drt_test.go#L77)):*
> ```Go
> 
> 				// Shutdown and restart region2.
> 				{Type: ChaosEventTypePreShutdown, Time: secondPreShutdown, Target: region2},
> ```

Nit: With the rework, these numbers changed.  Was that intentional?
___
*[pkg/cmd/roachtest/drt_test.go, line 194 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-MdvZ6a26DQTJU72_toX:-MdvZ6a26DQTJU72_toY:b-91yvns) ([raw file](https://github.com/cockroachdb/cockroach/blob/56af30cc0be0b708fb0c3b295b44993dae069cdc/pkg/cmd/roachtest/drt_test.go#L194)):*
> ```Go
> 				{q: makeMetric(metricB, "success", portRegion2), t: firstPreStartup, retVal: 1000},
> 				{q: makeMetric(metricB, "error", portRegion2), t: firstShutdownComplete.Add(prometheus.DefaultScrapeInterval), retVal: 0},
> 				{q: makeMetric(metricB, "error", portRegion2), t: firstPreStartup, retVal: 1000}, // should have been had errors during shutdown.
> ```

Nit: probably best to choose one of "been" or "had".

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66989)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[pkg/cmd/roachtest/drt_test.go, line 40 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-MdvY7ISBhCC-onebE_M:-MdxkrkuEsl_GRAVE3jZ:b-prtlrv) ([raw file](https://github.com/cockroachdb/cockroach/blob/56af30cc0be0b708fb0c3b295b44993dae069cdc/pkg/cmd/roachtest/drt_test.go#L40)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Does it makes sense for this to be `firstShutdownComplete + (DefaultScrapeTimeout * time.Second)`
</blockquote></details>

nope, because we had +10s logic
___
*[pkg/cmd/roachtest/drt_test.go, line 77 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66989#-MdvYvzA7Ch6m5YsJGgS:-MdxkvAc44aQ6mPL4ktU:b2nign3) ([raw file](https://github.com/cockroachdb/cockroach/blob/56af30cc0be0b708fb0c3b295b44993dae069cdc/pkg/cmd/roachtest/drt_test.go#L77)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: With the rework, these numbers changed.  Was that intentional?
</blockquote></details>

yep

**Comment by otan** [comment]
bors r=ajstorm

**Pull request merged**
