### PR TITLE
allocator2: change rate limiter etc.

### PR DESCRIPTION
**Pull request by sumeerbhola**
storeChangeRateLimiter and storeEnactedHistory are introduced to ensure
that N distributed allocators operating concurrently do not add or remove
more than 50% of the cluster mean load at a store.

storeState.computePendingChangesReflectedInLatestLoad is a heuristic
introduced to decide when a pendingReplicaChange that has been enacted,
can be assumed to be reflected in the StoreCapacity that is gossiped.

Informs #103320

Epic: CRDB-25222

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
First commit from https://github.com/cockroachdb/cockroach/pull/104334

The changes here illustrate what we were discussing this morning.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104559#-:-NXMyaCI5-pmqfViJzZh:b-r39k2r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

**Review by sumeerbhola — COMMENTED** [review]
rebased on master

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104559#-:-NXVfUpJCtqhH1ZuDzh-:b-9r6maq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

**Review by kvoli — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104559)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 186 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104559#-NXrkcPR8mbpD-_BPZ_Y:-NXrkcPSDJZNT4YNj1Dy:bzbe37d) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9b308d9b48043525d796575236e95d311f9424d/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L186)):*
> ```Go
> 	}
> 	for i, l := range c.loadDelta {
> 		if l < 0 {
> ```

What is this for?
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 267 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104559#-NXrl-f0D0Kgn2ZUt2_W:-NXrl-f18bBOlXfxkG4y:b-omnhwa) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9b308d9b48043525d796575236e95d311f9424d/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L267)):*
> ```Go
> 		// Another situation that can present a problem is cluster configurations
> 		// where a significant number of nodes will only have follower replicas.
> 		// We can add a cluster setting effective_fraction_allocators, that
> ```

It is pessimistic of me but I don't think we could rely on an operator setting this. Could we use each store's gossiped lease count to determine a similar number?
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 361 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104559#-NXrhUWx8ODxfJS92SoY:-NXrhUWx8ODxfJS92SoZ:bgcnuzt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9b308d9b48043525d796575236e95d311f9424d/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L361)):*
> ```Go
> //
> // TODO(sumeer): set this based on an understanding of ReplicaStats etc.
> const lagForChangeReflectedInLoad = 5 * time.Second
> ```

It is 5s
https://github.com/cockroachdb/cockroach/blob/fdf04ffe5403daab580ab0a6fb0ad407ccc23c2e/pkg/kv/kvserver/replicastats/replica_stats.go#L26-L30

It could worst case take gossip frequency (10s) + reflected lag (5s) + gossip latency (<1s).   
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 365 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104559#-NXrjSH61DiHWZCUBppE:-NXrjSH61DiHWZCUBppF:b-muz17d) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9b308d9b48043525d796575236e95d311f9424d/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L365)):*
> ```Go
> // NB: this is a heuristic.
> //
> // TODO(sumeer): this interface is just a placeholder. We should integrate
> ```

For the changes returned here, would the store and node load adjustments remain until the next load update from the store? 
___
*[`pkg/kv/kvserver/allocator/allocator2/load.go` line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104559#-NXrk9723RVDVepj-E_Q:-NXrk9723RVDVepj-E_R:bdit7p7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9b308d9b48043525d796575236e95d311f9424d/pkg/kv/kvserver/allocator/allocator2/load.go#L45)):*
> ```Go
> type loadVector [numLoadDimensions]loadValue
> 
> func (lv *loadVector) add(other loadVector) {
> ```

Would making this immutable (i.e. return a new vector) be cheap enough?

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104559)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 186 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104559#-NXrkcPR8mbpD-_BPZ_Y:-NXuyX_C8kaSg86SqTHn:b-uw7fh1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9b308d9b48043525d796575236e95d311f9424d/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L186)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

What is this for?
</blockquote></details>

We only accumulate positive deltas, since we are trying to throttle based on absolute value of what has being changed. This should typically not matter since we shouldn't be both adding and removing, but if we are worried about overall magnitude of changes then taking the absolute value makes sense. This is very debatable.
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 267 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104559#-NXrl-f0D0Kgn2ZUt2_W:-NXuzFoA6eYc-_N3z-ha:b71yb81) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9b308d9b48043525d796575236e95d311f9424d/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L267)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

It is pessimistic of me but I don't think we could rely on an operator setting this. Could we use each store's gossiped lease count to determine a similar number?
</blockquote></details>

This sounds good. Updated the comment.
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 361 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104559#-NXrhUWx8ODxfJS92SoY:-NXuzr3LDTkCUgOeOA2Z:b-xoyh1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9b308d9b48043525d796575236e95d311f9424d/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L361)):*
How much smoothing is happening because of `records    [6]*replicaStatsRecord`?

> It could worst case take gossip frequency (10s) + reflected lag (5s) + gossip latency (<1s).

Ack. The assumption here is that `latestLoadTime` is the timestamp assigned at the source, hence the 5s lag.
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 365 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104559#-NXrjSH61DiHWZCUBppE:-NXv-drpAINYBN_2kcL3:b-pfq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9b308d9b48043525d796575236e95d311f9424d/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L365)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

For the changes returned here, would the store and node load adjustments remain until the next load update from the store? 
</blockquote></details>

These changes are ones we assume are reflected in the load provided with the timestamp `latestLoadTime`. So we will discard them from `storeState.adjusted.loadPendingChanges` and so they won't be in `storeState.adjusted.load`.
___
*[`pkg/kv/kvserver/allocator/allocator2/load.go` line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104559#-NXrk9723RVDVepj-E_Q:-NXv021L0Bi8H-u44CZ8:b-33drjg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9b308d9b48043525d796575236e95d311f9424d/pkg/kv/kvserver/allocator/allocator2/load.go#L45)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Would making this immutable (i.e. return a new vector) be cheap enough? 
</blockquote></details>

We can do that. I was't trying to optimize -- this seemed natural since the callers do want to update their state.

**Review by kvoli — APPROVED** [review]
:lgtm:

Discussed offline, going to merge and then refactor https://github.com/cockroachdb/cockroach/pull/104842 with this change incorporated.

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104559#-:-NXw1NWv3wWJMdqSxSKe:b-zcymkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 186 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104559#-NXrkcPR8mbpD-_BPZ_Y:-NXw0Vwb5cYRrMGwUzC-:b1y24ww) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9b308d9b48043525d796575236e95d311f9424d/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L186)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We only accumulate positive deltas, since we are trying to throttle based on absolute value of what has being changed. This should typically not matter since we shouldn't be both adding and removing, but if we are worried about overall magnitude of changes then taking the absolute value makes sense. This is very debatable.
</blockquote></details>

Got it, okay that makes sense.
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 361 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104559#-NXrhUWx8ODxfJS92SoY:-NXw0_IT49aku_YP2qDU:b5xh1a3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9b308d9b48043525d796575236e95d311f9424d/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L361)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

How much smoothing is happening because of `records    [6]*replicaStatsRecord`?

> It could worst case take gossip frequency (10s) + reflected lag (5s) + gossip latency (<1s).

Ack. The assumption here is that `latestLoadTime` is the timestamp assigned at the source, hence the 5s lag.
</blockquote></details>

Each bucket is a 5 minute window. After a lease transfer or 
___
*[`pkg/kv/kvserver/allocator/allocator2/load.go` line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104559#-NXrk9723RVDVepj-E_Q:-NXw0yQG00aEPN6p7CYi:b-yn12dg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9b308d9b48043525d796575236e95d311f9424d/pkg/kv/kvserver/allocator/allocator2/load.go#L45)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We can do that. I was't trying to optimize -- this seemed natural since the callers do want to update their state.
</blockquote></details>

Ack - It seems useful for chaining binary operations over the load but more convenience.

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104559#-:-NXyvMrMDSyacv54wM0F:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 361 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104559#-NXrhUWx8ODxfJS92SoY:-NXyu36l6nV0XmWo59Lf:bx7i1k6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9b308d9b48043525d796575236e95d311f9424d/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L361)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Each bucket is a 5 minute window. After a lease transfer or 
</blockquote></details>

"After a lease transfer or"?

So if the replica has been initialized 6s ago, we will have accurate smoothed load information for that replica, but only smoothed over that 6s? And if it has been initialized 40min ago, are we getting smoothed information over 5m*6=30min?

What about smoothing for the aggregate node cpu and other aggregate store load dimensions? If they are smoothing over a long interval, we would incorrectly discount the effect of recent load additions.
___
*[`pkg/kv/kvserver/allocator/allocator2/load.go` line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104559#-NXrk9723RVDVepj-E_Q:-NXyvVCIBXPB3B3UFYiJ:b-91gali) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9b308d9b48043525d796575236e95d311f9424d/pkg/kv/kvserver/allocator/allocator2/load.go#L45)):*
> It seems useful for chaining binary operations over the load

makes sense

**Comment by sumeerbhola** [comment]
bors r=kvoli

**Pull request merged**
