### PR TITLE
sql,roachpb: relocate app_stats proto from sql to roachpb

### PR DESCRIPTION
**Pull request by benesch**
To share the `StatementStatistics` type with the registration server, we
need it to live in a package without any C dependencies.

### CODE REVIEW

**Comment by dt** [comment]
:lgtm:

Optional: export and move the three `*Info` structs to roachpb too (don't particularly protnbuf them), so they can get reused too, since it all logically goes together.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15566#-:-Kj4kRZ2V1kI1VpLDNnl:b-2cezld)*

**Comment by benesch** [comment]
Do you mean the `versionInfo`, `reportingInfo`, `nodeInfo`, and `storeInfo` structs that currently live in `pkg/server`?

**Comment by dt** [comment]
Yep, sorry, I should have been more specific. I'm also 👍 on this as-is too.

**Comment by benesch** [comment]
Ok, perfect. I'll deal with the other structs in another PR, because moving them into `roachpb` causes an import cycle. Grrrrr.

**Pull request merged**
