### PR TITLE
roachpb: Transaction.Clone by value

### PR DESCRIPTION
**Pull request by tamird**
second commit includes random cleanup I ran into while fixing fallout.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4193)

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM

---

Reviewed 10 of 10 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4193#-:-K9u_7xok5qvAUsdn6i5:676834233)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[roachpb/data.go, line 589 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4193#-K9wBigF-R3q0bsrsdfe:-K9wBigGV_DwhiUtl1tD:-714473427) ([raw file](https://github.com/cockroachdb/cockroach/blob/17af032b7b316ca6bbe6f4c650ac97d07a5222df/roachpb/data.go#L589)):*
I'm not sure about changing the signature of `Transaction.Clone` like this. You've pushed the checking of whether `t` is nil to the caller, which isn't providing any benefit as far as I can tell. If I saw this implementation and the usage, I would change the signature to take a pointer receive and return a new `*Transaction`. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4193)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[roachpb/errors.go, line 185 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4193#-K9wCFIROABYqe0wZw-v:-K9wCFIROABYqe0wZw-w:2052005901) ([raw file](https://github.com/cockroachdb/cockroach/blob/17af032b7b316ca6bbe6f4c650ac97d07a5222df/roachpb/errors.go#L185)):*
This is what seems odd. If all of the callers have to check `txn != nil`, let's put that check inside `Transaction.Clone`. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4193)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[roachpb/data.go, line 589 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4193#-K9wBigF-R3q0bsrsdfe:-K9wCIuyBTrHKz0EK0AB:300763916) ([raw file](https://github.com/cockroachdb/cockroach/blob/17af032b7b316ca6bbe6f4c650ac97d07a5222df/roachpb/data.go#L589)):*
> I would change the signature to take a pointer receive and return a new `*Transaction`.

That's not the same, since that approach would allocate on nil receiver.

---

*[roachpb/errors.go, line 185 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4193#-K9wCFIROABYqe0wZw-v:-K9wCZ8L8w7dbwgjzZs7:-1126815188) ([raw file](https://github.com/cockroachdb/cockroach/blob/17af032b7b316ca6bbe6f4c650ac97d07a5222df/roachpb/errors.go#L185)):*
Only pointer callers, not all callers. Those other callers aren't shown in this diff, for obvious reasons.

Also note that this method is marked for removal, so its ergonomics are perhaps not so important.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4193)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[roachpb/data.go, line 589 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4193#-K9wBigF-R3q0bsrsdfe:-K9wEDUE3Di6qeZ6wDQ4:-1182600764) ([raw file](https://github.com/cockroachdb/cockroach/blob/17af032b7b316ca6bbe6f4c650ac97d07a5222df/roachpb/data.go#L589)):*
You mean allocate if the caller only needs a value. Sure. Those cases seem rare, but perhaps I'm wrong about that. Maybe have both `Clone` and `ClonePtr`, the latter calls the former and a `nil` receiver properly.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4193)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[roachpb/data.go, line 589 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4193#-K9wBigF-R3q0bsrsdfe:-K9wIV3w6x6BjozUh25V:1528377620) ([raw file](https://github.com/cockroachdb/cockroach/blob/17af032b7b316ca6bbe6f4c650ac97d07a5222df/roachpb/data.go#L589)):*
Is that really worth it? There is just one non-test caller that has to do this nil check, in a method marked for removal.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4193)*

**Comment by tamird** [comment]
Review status: 6 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[roachpb/errors.go, line 185 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4193#-K9wCFIROABYqe0wZw-v:-K9wKYQwW-bM_YqjkW2E:-706738236) ([raw file](https://github.com/cockroachdb/cockroach/blob/17af032b7b316ca6bbe6f4c650ac97d07a5222df/roachpb/errors.go#L185)):*
Pushed another commit that makes this perhaps less odd looking.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4193)*

**Comment by petermattis** [comment]
LGTM

---

Review status: 6 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[roachpb/data.go, line 589 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4193#-K9wBigF-R3q0bsrsdfe:-K9wM0lQyOpy_qPCwIRs:-1209616781) ([raw file](https://github.com/cockroachdb/cockroach/blob/17af032b7b316ca6bbe6f4c650ac97d07a5222df/roachpb/data.go#L589)):*
Probably not.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4193#-:-K9wM5KPcQhDTkWdEjAh:676834233)*

**Pull request merged**
