### PR TITLE
server: add ui-only status endpoint for node info

### LINKED ISSUE #70702: ui: DB Console metric panels do not load for non-admins
Tracking for Cluster UI team backlog - picked up from [cockroachlabs/support/issues/1233](https://github.com/cockroachlabs/support/issues/1233) 

CRDB non-root user metric panels do not load. Some load - but not all. We do not have fine-grained metric panel controls - they should all load.

I have tried this on two clusters running 21.1.7+ with the same outcome. This does NOT occur on 20.2.8.

user created with :
```
CREATE ROLE "username" WITH LOGIN VIEWACTIVITY PASSWORD "password";
```

**Context**
Some background - according to @rafiss:
In [cockroachdb/cockroach#67068](https://github.com/cockroachdb/cockroach/pull/67068) -- the `/_status/nodes` endpoint now requires ADMIN privileges, and that endpoint powers these charts.

It shows up in the v21.1.8 release notes https://www.cockroachlabs.com/docs/releases/v21.1.8.html#security-updates

That means starting in v21.1.8, this creates a regression for DB Console users who can no longer see these panels. (This behavior is also in v20.2.14 and v21.2.0)

### PR DESCRIPTION
**Pull request by dhartunian**
Previously, a change was made to the `_status/nodes` endpoint to secure
it behind an Admin role in order to limit the spread of sensitive
information in node payloads to non-Admins. This included data such as
crdb args, env variables, and addresses. This change created a
regression in the DB Console because the cluster overview page relies
heavily on information gleaned from the nodes endpoint. The page became
useless for non-Admins since it couldn't receive any response from the
endpoint.

This change creates a new gRPC endpoint and payload types to mirror
those found in the `roachpb` package for the purpose of continuing to
expose node information to the DB Console. These endpoints are under the
`_status/nodes_ui` prefix and convert internal `roachpb` payloads to the
external facing ones (currently the payload types match exactly, but now
they can change freely), adding in sensitive data only when the caller
has the Admin role.

The DB Console has been modified to only use the new `nodes_ui` endpoint
which will dynamically return more data when the logged-in user is an
Admin.

non-UI callers on the `_status/nodes` gRPC endpoint such as the debug
zip commands and others have not been modified.

Resolves #70702

Release note (ui change): Non-Admin users of the DB Console have
regained the ability to view the cluster overview page. Users without
the Admin role will still see most data about their nodes but
information such as command line arguments, environment variables, and
IP addresses and DNS names of nodes will be hidden.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
> Reviewed 5 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71181)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @knz)

___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71181#-MlHh1no6JEDNsA_dfud):*
"This change" -> "That previous change"
___
*[-- commits, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71181#-MlHl8Tf1qaQeWiUMF-d):*
why did you create new endpoints instead of overridding the existing endpoint? 
___
*[pkg/server/serverpb/status.proto, line 250 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71181#-MlHksT64pm67J_XcMq4:-MlHksT64pm67J_XcMq5:b-nfqp73) ([raw file](https://github.com/cockroachdb/cockroach/blob/26354b04e57ac47e786fd3585fdbbdfada08a1bc/pkg/server/serverpb/status.proto#L250)):*
> ```protobuf
>   repeated StoreStatus store_statuses = 6 [(gogoproto.nullable) = false];
> 
>   // args is the list of command-line arguments used to last start the node.
> ```

maybe explain in the docstring that this is only available to the admin role.
Same for the other admin-only fields.

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71181)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @knz)

___
*[-- commits, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71181#-MlHl8Tf1qaQeWiUMF-d):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

why did you create new endpoints instead of overridding the existing endpoint? 
</blockquote></details>

I went that route initially but the existing endpoints have quite a few uses internally (in debug zip for instance) and I was nervous about changing a sprawl of call sites in a PR that I'd like to backport for release ideally. I assumed that a more "append-only" PR with ui-limited usage would be easier to get comfortable with at this stage.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71181)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @knz)

___
*[-- commits, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71181#-MlHl8Tf1qaQeWiUMF-d):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I went that route initially but the existing endpoints have quite a few uses internally (in debug zip for instance) and I was nervous about changing a sprawl of call sites in a PR that I'd like to backport for release ideally. I assumed that a more "append-only" PR with ui-limited usage would be easier to get comfortable with at this stage.
</blockquote></details>

The beauty of it is that all "internal" uses (debug zip etc) use an admin role, so they can see everything. :)

I'm OK with a new endpoint, but then you need to change the front-end code too to use the new endpoint I think.

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71181)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @knz)

___
*[-- commits, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71181#-MlHl8Tf1qaQeWiUMF-d):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

The beauty of it is that all "internal" uses (debug zip etc) use an admin role, so they can see everything. :)

I'm OK with a new endpoint, but then you need to change the front-end code too to use the new endpoint I think.


</blockquote></details>

Yes, this PR contains those changes as well

**Review by knz — COMMENTED** [review]
LGTM on the approach but there are open review comments

> Reviewed 3 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71181#-:-MlKzoX06AQMm_ijn_75:bxom9x8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @knz)

___
*[pkg/server/serverpb/status.proto, line 197 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71181#-MlKzjqT4AqCoOvgjeAQ:-MlKzjqU-sz2mgu2u-xx:b-dlskgq) ([raw file](https://github.com/cockroachdb/cockroach/blob/26354b04e57ac47e786fd3585fdbbdfada08a1bc/pkg/server/serverpb/status.proto#L197)):*
> ```protobuf
> // a distribution.
> message Percentiles {
>   optional double p10 = 1;
> ```

You'll need to remove the `optional` keyword throughout, to fix the build

**Review by kzh — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71181#-:-MlL_cGK5OPkcsjL7bRQ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian and @knz)

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71181)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian and @knz)

___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71181#-MlHh1no6JEDNsA_dfud):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

"This change" -> "That previous change"
</blockquote></details>

Done.
___
*[pkg/server/serverpb/status.proto, line 197 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71181#-MlKzjqT4AqCoOvgjeAQ:-MlLzmKL9ith1SiYA5Gb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26354b04e57ac47e786fd3585fdbbdfada08a1bc/pkg/server/serverpb/status.proto#L197)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

You'll need to remove the `optional` keyword throughout, to fix the build
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71181)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian)

**Review by Santamaura — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71181)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @srosenberg)

**Pull request merged**
