### PR TITLE
c-deps/geos: add geos to c libraries

### PR DESCRIPTION
**Pull request by danhhz**
Release note: None

### CODE REVIEW

**Review by otan — CHANGES_REQUESTED** [review]
i think we shouldn't do this now, considering we're going with the `dlopen` approach.

(we'll have to do this for proj though and man that does look painful...)

**Comment by danhhz** [comment]
Yeah, I was just hoping to get us CI while we were prototyping, but I never managed to get it to work

**Comment by petermattis** [comment]
@danhhz I assume this is the PR you were talking about yesterday. While this isn't quite what we want to do for the `dlopen` approach, it is a fine start. I'm going to pick this up and adjust it so that it builds geos as a shared library.

**Comment by danhhz** [comment]
Yup, this was it. Sorry I forgot to send it to you yesterday, nice sleuthing

**Pull request closed without merging**
