### PR TITLE
jobs, backupccl: redact output of SHOW CREATE SCHEDULE

### LINKED ISSUE #71281: SHOW CREATE SCHEDULE output redact secret keys
When running `SHOW CREATE SCHEDULE` on either a <schedule_id> or as `SHOW CREATE ALL SCHEDULES` the output shows secret access keys in the `CREATE` statement.

This was testing only on AWS — showing the secret access key

**To Reproduce**

Created a scheduled backup to AWS S3:

`root@localhost:26257/defaultdb> CREATE SCHEDULE scheduled_first_run FOR BACKUP TABLE movr.vehicles INTO 's3://kathrynh-bulkio/backup-test?AWS_ACCESS_KEY_ID=[my_access_key_id]&AWS_SECRET_ACCESS_KEY=[my_secret_access_key]' RECURRING '@daily' WITH SCHEDULE OPTIONS ignore_existing_backups;`

Output from this `CREATE` statement shows redacted secret access key:

```
     schedule_id     |        label        |                     status                     |           first_run           | schedule |                                                                          backup_stmt
---------------------+---------------------+------------------------------------------------+-------------------------------+----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------
  699246220072812545 | scheduled_first_run | PAUSED: Waiting for initial backup to complete | NULL                          | @daily   | BACKUP TABLE movr.public.vehicles INTO 's3://kathrynh-bulkio/backup-test?AWS_ACCESS_KEY_ID=[my_access_key_id]&AWS_SECRET_ACCESS_KEY=redacted' WITH detached
  699246220077694977 | scheduled_first_run | ACTIVE                                         | 2021-10-05 19:50:11.497459+00 | @weekly  | BACKUP TABLE movr.public.vehicles INTO 's3://kathrynh-bulkio/backup-test?AWS_ACCESS_KEY_ID=[my_access_key_id]&AWS_SECRET_ACCESS_KEY=redacted' WITH detached
(2 rows)
```

Used the `SHOW CREATE SCHEDULE 699246220072812545;` on the top schedule id, received statement with non-redacted secret access key:

```
  schedule_id     |                                                                                                                                                                                                 create_statement
---------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  699246220072812545 | CREATE SCHEDULE 'scheduled_first_run' FOR BACKUP TABLE movr.public.vehicles INTO 's3://kathrynh-bulkio/backup-test?AWS_ACCESS_KEY_ID=[my_access_key_id]&AWS_SECRET_ACCESS_KEY=[my_secret_access_key]' WITH detached RECURRING '@daily' FULL BACKUP '@weekly' WITH SCHEDULE OPTIONS first_run = '2021-10-08 00:00:00+00:00', on_execution_failure = 'RESCHEDULE', on_previous_running = 'WAIT'
(1 row)
```

Expected the secret access key to be redacted on running `SHOW CREATE SCHEDULE`.

### PR DESCRIPTION
**Pull request by adityamaru**
This change redacts some of the fields that are displayed as
part of `SHOW CREATE SCHEDULE`. It uses an existing helper method
to process the underlying backup node and redact sensitive fields
from it.

Fixes: https://github.com/cockroachdb/cockroach/issues/71281

Release note (bug fix): Fixes a bug where SHOW CREATE SCHEDULES
was not redacting sensitive fields before displaying the `CREATE SCHEDULE`
query.

### CODE REVIEW

**Review by miretskiy — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71339)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @miretskiy)

___
*[pkg/ccl/backupccl/schedule_exec.go, line 282 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71339#-MlWGLM_Db9dkLr4u9Up:-MlWGLM_Db9dkLr4u9Uq:bhpfmk2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d34da9332f8db0504b8cc4df9dab61d0fbd3ff34/pkg/ccl/backupccl/schedule_exec.go#L282)):*
> ```Go
> 		return "", errors.AssertionFailedf("unexpected PlanHookState type: %T", p)
> 	}
> 	toFn, err := p.TypeAsStringArray(ctx, tree.Exprs(backupNode.To), scheduleBackupOp)
> ```

I'm not sure this is needed.  Any placeholders must have been evaluated when creating the schedule.
Any expressions were evaluated as well.  I believe it's safe to call tree.MustBeDString() (or if you insist, AsDstring)
to convert those expressions into strings.

**Comment by adityamaru** [comment]
Thanks for catching that, I don't think its a DString but I see other parts of the scheduled backup code use a similar casting. This way we don't have to plumb the planHookState too 🥳

**Review by miretskiy — APPROVED** [review]
> Reviewed 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71339)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @miretskiy)

**Comment by adityamaru** [comment]
TFTR!

bors r=miretskiy

**Pull request merged**
