### PR TITLE
roachpb,sql: limit the syntax of tenant names

### LINKED ISSUE #92613: sql,server: add a validation to tenant names to mandate a specific lexical structure
This is coming up when implementing tenant routing for SQL clients. As requested/suggested by andyk, it would be good to allow routing tenants using a prefix in the dbname provided by clients, for example `postgres://.../mytenant.mydb`. This is what the SQL proxy does in serverless too.   However, we can only do this reliably if the tenant name is guaranteed to not contain a period. 

@JeffSwenson suggests:
> If we want to support SNI on dedicated clusters, then we also need to prohibit ‘_’, since it is not a valid character in dns names.

Proposal: valid DNS identifier, but `.` forbidden.

Jira issue: CRDB-21884

### PR DESCRIPTION
**Pull request by knz**
Fixes #92613.

This commit limits the lexicographical structure of tenant names to be that of DNS hostnames: start with a letter, followed by a combination of letters, digits or hyphens. In particular periods and underscores are not allowed.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
cc @adityamaru

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93269)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @knz, and @stevendanna)

___
*[`pkg/roachpb/tenant.go` line 153 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93269#-NJ7CNF91ngLHDh23Uo3:-NJ7CNF91ngLHDh23Uo4:b-f6u3v2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d66012012bd662dd495f5c948a59c6f1fa44822/pkg/roachpb/tenant.go#L153)):*
> ```Go
> // to a database name in connection strings. However there cannot
> // be a hyphen at the end.
> var tenantNameRe = regexp.MustCompile(`^[a-z0-9]([a-z0-9---]{0,98}[a-z0-9])?$`)
> ```

What does the `---` do in `[a-z0-9---]`? Is it different from just `[a-z0-9-]`?

**Comment by knz** [comment]
> What does the `---` do in `[a-z0-9---]`? Is it different from just `[a-z0-9-]`?

A standalone `-` in a regexp `[...]` pattern is dangerous: if someone ever decides to add just 1 letter to the pattern, for example `[a-z0-9X-]` suddenly the pattern changes meaning.

By writing `---` it becomes impervious to adding characters on the left in the future.

**Review by ecwall — APPROVED** [review]
Looks good, just a request for some more test cases.
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93269#-:-NJBc8XfC78Kki5qWZZh:b-wuzva7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @knz, and @stevendanna)

___
*[`pkg/sql/logictest/testdata/logic_test/tenant` line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93269#-NJBbhCQ7gorJ1BtIIUP:-NJBbhCRBxJR3HTnanFR:b60unjs) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d66012012bd662dd495f5c948a59c6f1fa44822/pkg/sql/logictest/testdata/logic_test/tenant#L16)):*
> ```
> CREATE TENANT "two"
> 
> statement error invalid tenant name
> ```

Can you add test cases for length boundaries
0 -> invalid
1 -> valid
100 -> valid
101 -> valid

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93269)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @knz, and @stevendanna)

___
*[`pkg/sql/logictest/testdata/logic_test/tenant` line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93269#-NJBbhCQ7gorJ1BtIIUP:-NJBce530rzys7bxkdc4:b5j5q9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d66012012bd662dd495f5c948a59c6f1fa44822/pkg/sql/logictest/testdata/logic_test/tenant#L16)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

Can you add test cases for length boundaries
0 -> invalid
1 -> valid
100 -> valid
101 -> valid
</blockquote></details>

* 101 -> invalid

**Review by knz — COMMENTED** [review]
TFYR!

bors r=ecwall

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93269#-:-NJCFaNEB0r3MMpV4Ljr:bs7wjis)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @ecwall, and @stevendanna)

___
*[`pkg/sql/logictest/testdata/logic_test/tenant` line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93269#-NJBbhCQ7gorJ1BtIIUP:-NJCEs0J-nZYlLu2c0tU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d66012012bd662dd495f5c948a59c6f1fa44822/pkg/sql/logictest/testdata/logic_test/tenant#L16)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

* 101 -> invalid
</blockquote></details>

Done.

**Pull request merged**
