### PR TITLE
kvserver: deflake TestRangeTransferLeaseExpirationBased

### LINKED ISSUE #47561: kv/kvserver: TestRangeTransferLeaseExpirationBased failed
[(kv/kvserver).TestRangeTransferLeaseExpirationBased failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=1879773&tab=buildLog) on [master@de48c6d13431061a6227697a917e574464b80983](https://github.com/cockroachdb/cockroach/commits/de48c6d13431061a6227697a917e574464b80983):

```
=== RUN   TestRangeTransferLeaseExpirationBased
--- FAIL: TestRangeTransferLeaseExpirationBased (5.39s)
W200416 06:58:52.483671 582344 kv/kvserver/store.go:1202  [drain] unable to drain cleanly within 5s, service might briefly deteriorate: operation "wait for raft leadership transfer" timed out after 5s: waiting for 1 replicas to transfer their lease away
(1) operation "wait for raft leadership transfer" timed out after 5s
Wraps: (2) secondary error attachment
  | context deadline exceeded
  | (1) context deadline exceeded
  | Error types: (1) context.deadlineExceededError
Wraps: (3) attached stack trace
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).SetDraining.func3
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/store.go:1186
  | github.com/cockroachdb/cockroach/pkg/util/contextutil.RunWithTimeout
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/util/contextutil/context.go:135
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).SetDraining
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/store.go:1169
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestRangeTransferLeaseExpirationBased.func4.2
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/client_replica_test.go:892
  | runtime.goexit
  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
Wraps: (4) 2 safe details enclosed
Wraps: (5) waiting for 1 replicas to transfer their lease away
Error types: (1) *contextutil.TimeoutError (2) *secondary.withSecondaryError (3) *withstack.withStack (4) *safedetails.withSafeDetails (5) *errors.errorString

```

<details><summary>More</summary><p>
Parameters:

- TAGS=
- GOFLAGS=-parallel=4

```
make stressrace TESTS=TestRangeTransferLeaseExpirationBased PKG=./pkg/kv/kvserver TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestRangeTransferLeaseExpirationBased.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by knz**
Fixes #47561.

### CODE REVIEW

**Review by tbg — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48714)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by tbg — APPROVED** [review]
Thanks for the fix! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48714#-:-M77vrw47kNDnhFOdovG:b4zdbp8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48714#-:-M78w-V_7F2ooKxFZitV:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by knz** [comment]
thanks!

bors r=tbg,nvanbenschoten

**Comment by knz** [comment]
bors r=tbg,nvanbenschoten

**Pull request merged**
