### PR TITLE
acceptance: revert to previous naming scheme

### PR DESCRIPTION
**Pull request by tbg**
There's some magic baked into teamcity-post-failures
and we don't have plans to add with a different number
of nodes anyway.

Release note: None

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33546#-:-LVdXY92DiQzIhXYKSD_:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by tbg** [comment]
TFTR!

bors r=petermattis

**Comment by tbg** [comment]
third time's the charm (finally fixed the code, for real)

bors r=petermattis

**Comment by tbg** [comment]
bors r=petermattis

**Pull request merged**
