### PR TITLE
ui: add full scan filter to statements page

### LINKED ISSUE #50354: webui: add filters to the statements page
In https://github.com/cockroachdb/cockroach/issues/45618 we discussed wholsale adding the slow query log (which is available in endpoints) to the webui. Instead, we settled on improving the statements page by adding filtering because it also includes distribution information.

We can add filters to statement stats that let you do things like filter out all queries that take longer than x, or all non-full table scans. We could also have a page the prepopulates some of these filters but I think just having them available on the statement stats page will be a win.

cc @piyush-singh i filed this so we don't lose track of it since we close #45618

### PR DESCRIPTION
**Pull request by barryhe2000**
Release justification: Low risk, high benefit
changes to existing functionality.

Fixes: #50354

UI changes that allows for filtering of full table or index
scans on the statements page.

Release note (ui change): add filter for full scans to statement page

### CODE REVIEW

**Comment by awoods187** [comment]
I'm very excited for this work! Can you post a screenshot?

**Comment by barryhe2000** [comment]
Screen Shot 2021-02-17 at 8 23 07 PM
Screen Shot 2021-02-17 at 8 23 19 PM

full table scan filter unchecked vs checked. UI is rudimentary right now but just as a starting point. This PR is the backend side but needs to be merged first in order for me to merge the cluster-ui changes otherwise the cluster-ui tests will keep failing due to the proto changes from the backend not being in master.

**Review by asubiotto — COMMENTED** [review]
Nice! cc @dhartunian 

> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60670#-:-MToyqm70kjz-RGMb41M:b-udvs73)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @barryhe2000)

___
*[pkg/ui/src/views/statements/statementsPage.tsx, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60670#-MToyzgcDw_a0RoOHXGz:-MToyzgcDw_a0RoOHXH-:bnydvrv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4863a9e149969280b7dd873ed7426e536d0d1eb2/pkg/ui/src/views/statements/statementsPage.tsx#L72)):*
> ```XML
>     props: RouteComponentProps<any>,
>     diagnosticsReportsPerStatement,
>   ): AggregateStatistics[] => {
> ```

Curious about two things:
1) Why did this return type have to be added?
2) Why did you have to do this addition in `pkg/ui`? Where is this code called? Is a similar thing done in `cluster-ui` or does `cluster-ui` use this code?

**Comment by awoods187** [comment]
Nice--seems like a good first start. I look forward to testing it.

**Comment by barryhe2000** [comment]
Yeah the pkg/ui code was necessarily since passing the fullScan value through there was the only way I could get it through to the frontend. I added the return type just to mirror what was in cluster-ui just for clarity, since the createSelector function also has a comment at the top that specifies returning AggregateStatistics

**Review by dhartunian — COMMENTED** [review]
> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60670)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/ui/src/views/statements/statementsPage.tsx, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60670#-MToyzgcDw_a0RoOHXGz:-MTqzm_aAcMDQf3tmyNk:be92htl) ([raw file](https://github.com/cockroachdb/cockroach/blob/4863a9e149969280b7dd873ed7426e536d0d1eb2/pkg/ui/src/views/statements/statementsPage.tsx#L72)):*
I can help shed some light here:

> Why did this return type have to be added?
TypeScript isn't currently set to require return types on functions but adding them can help with type inference and to document the code. I assume Barry added it here to check his assumptions and understanding. I would like to eventually require return types on all functions.

> Why did you have to do this addition in pkg/ui? Where is this code called? Is a similar thing done in cluster-ui or does cluster-ui use this code?
The `createSelector` helper constructs a connection between the global app state and the specific piece of it that your component requires via its `props`. In this case the state is transformed in the selector before it gets to the component.

A similar thing is done in `cluster-ui` but the Redux layer in that project is built to integrate specifically with the CC app. We'll be moving that code into CC for clarity in the near future.

**Review by dhartunian — COMMENTED** [review]
@barryhe2000 I just pushed up your protobuf client with the version `0.0.7-beta.0`. You can use it in your `ui` repo work to get tests passing. Once you merge this PR we can push up a non-beta before you merge.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60670#-:-MTr0ZrtEZWzj1eEv3dh:b-aeo8yw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60670)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @barryhe2000)

___
*[pkg/roachpb/app_stats.proto, line 186 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60670#-MTrgPV4-k95K2uDZ8yg:-MTrgPV4-k95K2uDZ8yh:bocyy4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/4863a9e149969280b7dd873ed7426e536d0d1eb2/pkg/roachpb/app_stats.proto#L186)):*
> ```protobuf
>   optional bool implicit_txn = 6 [(gogoproto.nullable) = false];
>   optional bool vec = 7 [(gogoproto.nullable) = false];
>   optional bool fullScan = 8 [(gogoproto.nullable) = false];
> ```

super nit: in proto files we tend to use lower case with underscores in the variable names, i.e `full_scan`. The generated code then correctly will have `FullScan` as we want.

**Review by barryhe2000 — COMMENTED** [review]
RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60670#-:-MUA42-5-4rV4tJzunRT:bb72pd0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @dhartunian, and @yuzefovich)

___
*[pkg/roachpb/app_stats.proto, line 186 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60670#-MTrgPV4-k95K2uDZ8yg:-MUA1bd91mBm3AfYnE8I:b-7rl0jq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4863a9e149969280b7dd873ed7426e536d0d1eb2/pkg/roachpb/app_stats.proto#L186)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

super nit: in proto files we tend to use lower case with underscores in the variable names, i.e `full_scan`. The generated code that correctly will have `FullScan` as we want.
</blockquote></details>

done!

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60670#-:-MUAylgL3U7CzGcVVq-m:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @dhartunian, and @yuzefovich)

**Comment by barryhe2000** [comment]
TFTR

bors r+

**Comment by yuzefovich** [comment]
bors r-

Needs a rebase and force-push to resolve the merge conflict.

**Comment by asubiotto** [comment]
There will probably be another conflict with #60791 in the `app_stats.proto`. You'll have to rebase and regenerate the proto. I can take care of publishing a new version for the UI with both these proto changes once this is in.

**Comment by barryhe2000** [comment]
Rebased.

bors r+

**Comment by barryhe2000** [comment]
Flake.

bors r+

**Comment by asubiotto** [comment]
OK, I'll take care of publishing a new `0.0.7` version

**Comment by asubiotto** [comment]
Done, you can now use `0.0.7` in your `cockroachdb/ui` PRs

**Pull request merged**
