### PR TITLE
sql: simplify the subquery typing rules

### PR DESCRIPTION
**Pull request by petermattis**
The simplification allows Cockroach to support a strict superset of the
queries Postgres supports.

Release note: None

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
:lgtm_strong: 

---

Reviewed 1 of 1 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/subquery.go, line 404 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21114#-L1V8NdICkoLFhXP7M3v:-L1V8NdICkoLFhXP7M3w:b-5zstxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fe1e914c05d8c4dbb406ae122c05572bcc78289/pkg/sql/subquery.go#L404)):*
> if the subquery returns on a single column, use the type of that column as the type for the subquery.

How does `SELECT 1 IN (SELECT 1);` still work then?

---

*[pkg/sql/logictest/testdata/logic_test/subquery, line 114 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21114#-L1V82mjlPMI8RnCG-46:-L1V82mki6XD2pCiJeB2:bc2rxyi) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fe1e914c05d8c4dbb406ae122c05572bcc78289/pkg/sql/logictest/testdata/logic_test/subquery#L114)):*
> ```
> ----
> true
> ```

Could you add the case `SELECT (SELECT 1, 2) IN (SELECT 1, 2);`? It's another one that we support (and MySQL supports) but PG doesn't.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21114#-:-L1V8AqXyEtJJ8SRdRdJ:b-uwkowd)*

**Comment by petermattis** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/subquery.go, line 404 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21114#-L1V8NdICkoLFhXP7M3v:-L1VNDJdBmXHystDMA4a:bj3xydo) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fe1e914c05d8c4dbb406ae122c05572bcc78289/pkg/sql/subquery.go#L404)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> if the subquery returns on a single column, use the type of that column as the type for the subquery.

How does `SELECT 1 IN (SELECT 1);` still work then?
</blockquote></details>

The comment was inaccurate. In a multi-row context (such as the right-hand side of an `IN` expression), we always wrap the inner type `U` in a `tuple` resulting in `tuple{U}`. If the subquery returns a single column, the type `U` is the type of that column. If the subquery returns multiple columns `C`, the type is `tuple{C}`. So for the above query, the type of the subquery will be `tuple{int}`.

I've rewritten the comment to make it clearer what the subquery typing rules ares.

---

*[pkg/sql/logictest/testdata/logic_test/subquery, line 114 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21114#-L1V82mjlPMI8RnCG-46:-L1VN3IC3N0qT66wQr5-:bl0r0qk) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fe1e914c05d8c4dbb406ae122c05572bcc78289/pkg/sql/logictest/testdata/logic_test/subquery#L114)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could you add the case `SELECT (SELECT 1, 2) IN (SELECT 1, 2);`? It's another one that we support (and MySQL supports) but PG doesn't.
</blockquote></details>

We already have that case on line 227.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21114)*

**Comment by petermattis** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/subquery.go, line 404 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21114#-L1V8NdICkoLFhXP7M3v:-L1VR-h8dQp3QrVIJNsY:b-clw9bo) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fe1e914c05d8c4dbb406ae122c05572bcc78289/pkg/sql/subquery.go#L404)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The comment was inaccurate. In a multi-row context (such as the right-hand side of an `IN` expression), we always wrap the inner type `U` in a `tuple` resulting in `tuple{U}`. If the subquery returns a single column, the type `U` is the type of that column. If the subquery returns multiple columns `C`, the type is `tuple{C}`. So for the above query, the type of the subquery will be `tuple{int}`.

I've rewritten the comment to make it clearer what the subquery typing rules ares.
</blockquote></details>

I hope @knz will appreciate my the irony of my earlier comments about comments in light of the verbose comments present in this PR. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21114)*

**Comment by knz** [comment]
:lgtm: for the code change -- even though you're looking into the tuple/vtuple distinction separately, could you expand the comment here to make a note this is a concern?

---

Reviewed 1 of 1 files at r1, 1 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/subquery.go, line 404 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21114#-L1V8NdICkoLFhXP7M3v:-L1WyHOpl7AFZ-JvJ374:b-9xm4nh) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fe1e914c05d8c4dbb406ae122c05572bcc78289/pkg/sql/subquery.go#L404)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I hope @knz will appreciate my the irony of my earlier comments about comments in light of the verbose comments present in this PR. 
</blockquote></details>

I think there is wisdom in investing both in exhaustive, up-to-date comments and also learning how to read code effectively (and learning to verify code matches comments). I am working on it.

---

*[pkg/sql/subquery.go, line 411 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21114#-L1Wy4NMNzlxD7oHfOt4:-L1Wy4NOx3dWpYPVmTBL:byv2718) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e9a257ef05b55fd6baecec6af50bc38e23f02ad/pkg/sql/subquery.go#L411)):*
> ```Go
> 	//
> 	//   - If the subquery returns multiple columns, the type of the subquery is
> 	//     "tuple{tuple{C}}" where "C expands to all of the types of the columns
> ```

aw the outer tuple{...} here should be vtuple, or at least since you're making a major improvement to this code you could also add a note here that reusing the base "tuple" type is technically incorrect because it requires fixed arity, and instead we'd like something with variable arity.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21114#-:-L1WyWKOLJ6NciHGa9dw:b8jcexh)*

**Comment by petermattis** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/subquery.go, line 411 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21114#-L1Wy4NMNzlxD7oHfOt4:-L1Xd0cO4Pe4CbhueJHZ:b7helhn) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e9a257ef05b55fd6baecec6af50bc38e23f02ad/pkg/sql/subquery.go#L411)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

aw the outer tuple{...} here should be vtuple, or at least since you're making a major improvement to this code you could also add a note here that reusing the base "tuple" type is technically incorrect because it requires fixed arity, and instead we'd like something with variable arity.
</blockquote></details>

I've added a `TODO` about the misuse of the `tuple` type below where it gets added in the multi-row case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21114)*

**Pull request merged**
