### PR TITLE
sql: drop locks before waiting for concurrent schema changes

### LINKED ISSUE #78144: roachtest: tpch_concurrency failed
roachtest.tpch_concurrency [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4614418&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4614418&tab=artifacts#/tpch_concurrency) on release-22.1 @ [f5b42a4e3bbdadb25aee89a41871239a624d538d](https://github.com/cockroachdb/cockroach/commits/f5b42a4e3bbdadb25aee89a41871239a624d538d):

```
The test failed on branch=release-22.1, cloud=gce:
test artifacts and logs in: /artifacts/tpch_concurrency/run_1
	test_runner.go:997,test_runner.go:896: test timed out (18h0m0s)
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*tpch_concurrency.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-13992

### PR DESCRIPTION
**Pull request by ajwerner**
Before this change, it was possible for a deadlock to occur when
one schema change was waiting on a previously committed schema change
but the job due to that previously committed schema change was
waiting on the current transaction. It is critical that when waiting
for a concurrent schema change, that the transaction doing the waiting
not hold any locks.

Along the way, this change reworks how "old" schema changes interact
with the declarative schema changer. Before this change, they would return
an error. Now they'll wait. I don't think the error that we were returning was
going to be a good experience for anybody, so this seems like a strictly good
change.

Fixes #78144

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
The flake is `TestUncertaintyErrorIsReturned` which does not feel like this change.

**Review by postamar — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78576)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/conn_executor.go, line 2932 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78576#-MzG2-xQ0sBcPNcq6NHa:-MzG2-xQ0sBcPNcq6NHb:b6rxukt) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e2b65e434a23d32ecee95a880f2ef91a2173009/pkg/sql/conn_executor.go#L2932)):*
> ```Go
> 		return err
> 	}
> 	return ex.resetTransactionOnSchemaChangeRetry(ctx)
> ```

Shouldn't this `ex.state.mu.Lock()` either here or in that method?
___
*[pkg/sql/schema_changer_test.go, line 8205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78576#-MzG46al56GsMpLqCk_n:-MzG46al56GsMpLqCk_o:bp99cjl) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e2b65e434a23d32ecee95a880f2ef91a2173009/pkg/sql/schema_changer_test.go#L8205)):*
> ```Go
> 				return
> 			}
> 			if !runStmt(`DROP VIEW IF EXISTS v`) {
> ```

Should we preface this DDL plus the CREATE VIEW above with `SET` calls which explicitly enable and disable the declarative schema changer, respectively? I'm concerned that this test will not age well otherwise.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78576)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

___
*[pkg/sql/conn_executor.go, line 2932 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78576#-MzG2-xQ0sBcPNcq6NHa:-MzHO_yTEX9aHH3K4cfL:b3ciwob) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e2b65e434a23d32ecee95a880f2ef91a2173009/pkg/sql/conn_executor.go#L2932)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Shouldn't this `ex.state.mu.Lock()` either here or in that method?
</blockquote></details>

Yes indeed, done. 
___
*[pkg/sql/schema_changer_test.go, line 8205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78576#-MzG46al56GsMpLqCk_n:-MzHOhXv27Jq2ZkFhZQk:bb6p55e) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e2b65e434a23d32ecee95a880f2ef91a2173009/pkg/sql/schema_changer_test.go#L8205)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Should we preface this DDL plus the CREATE VIEW above with `SET` calls which explicitly enable and disable the declarative schema changer, respectively? I'm concerned that this test will not age well otherwise.
</blockquote></details>

in that you'd like to make sure it works for both the old and new schema changer implementations of `DROP VIEW` as opposed to just the new one?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78576)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

___
*[pkg/sql/schema_changer_test.go, line 8205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78576#-MzG46al56GsMpLqCk_n:-MzHvA2x7SZ_jzZYRbi5:bnx597m) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e2b65e434a23d32ecee95a880f2ef91a2173009/pkg/sql/schema_changer_test.go#L8205)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

in that you'd like to make sure it works for both the old and new schema changer implementations of `DROP VIEW` as opposed to just the new one? 
</blockquote></details>

Alright, I made it more explicit

**Pull request merged**
