### PR TITLE
server/profiler: add periodic memory monitoring dump

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit adds periodic "memory monitoring" dump as another profiler.
It uses exactly the same heuristic as the heap profiler to be triggered,
and the dump contains human-readable view of the memory monitoring
system. Monitors that don't have any usage are omitted from the output.
In conjunction with the heap profiles it should give us better insight
into why OOMs / significant memory usage occurred.

The output is written into new files in `heap_profiler` directory and
are of the form:
```
root 0 B (8.0 GiB / 0 B)
    sql 265 MiB
        session root 264 MiB (21 KiB / 84 KiB)
            txn 264 MiB
                flow 211b7d29 264 MiB
                    joinreader-mem 220 KiB
                    distinct-7-limited-17 90 KiB
                    fetcher-mem 1.9 MiB
                    joinreader-mem 3.3 MiB
                    hash-aggregator-4-unlimited-16 218 MiB
                    hash-joiner-3-unlimited-5 70 KiB
                    hash-joiner-3-limited-4 26 MiB
                    index-join-1-unlimited-2 510 KiB
                    cfetcher-2-unlimited-1 2.0 MiB
                    cfetcher-0-unlimited-0 12 MiB
            session 90 KiB
        internal sql executor 90 KiB
        conn 105 KiB
        internal SQL executor 40 KiB
        internal SQL executor 30 KiB
        SQLStats 220 KiB
    pre-conn 105 KiB
    closed-session-cache 30 KiB
        rangefeed-system-monitor 0 B (128 MiB / 0 B)
```
(this was collected on a single node cluster running one TPCH query).

This feature is enabled by default but can be disabled via a public
cluster setting.

Addresses: #35097.

Epic: None

Release note (general change): CockroachDB will now periodically dump
the state of its internal memory accounting system into `heap_profiler`
directory, at the same time as the heap profiles are taken. This
behavior can be disabled by changing `diagnostics.memory_monitoring_dumps.enabled`
cluster setting to `false`.

### CODE REVIEW

**Comment by yuzefovich** [comment]
Not sure who would be a good person to review this.

Perhaps someone from obs infra team? @dhartunian @abarganier
Also perhaps someone from queries team? @DrewKimball @michae2

**Review by abarganier — COMMENTED** [review]
Things overall look good to me. There's one piece of context I wanted to bring up re: the heuristic that we're sharing with `heapprofiler`. LMK what you think.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114275#-:-Njhuutk-BQAtwGAAz_3:b-1nxmtv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @DrewKimball, @michae2, and @yuzefovich)

___
*[`pkg/server/env_sampler.go` line 120 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114275#-Njhs1hh4Q9YBBHEqgKT:-Njhs1hh4Q9YBBHEqgKU:b-h2njzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/db314113ed1777547ed2c609de3275c9c3df6217/pkg/server/env_sampler.go#L120)):*
Just wanted to note: by sharing the `heapProfileDirName` here with all the other profiles, this means we share a "store" with the other profiles. 

A store in this case is a directory with a total size limit imposed on it, where older files are GC'd/deleted to make room for new ones once the limit is reached.

IIUC this means that this will introduce another profile type competing for its share of that size limit. Of course, since we're using the same heuristic as the `heapprofiler`, if one profiler generates a dump, so will the other.

There's been an open issue for a while now talking about how the existing heapprofiler dumps pretty aggressively: https://github.com/cockroachdb/cockroach/issues/91392

This means that this new `MemoryMonitoringProfiler` will be equally as aggressive with its heuristic. Any chance we can devise a less aggressive heuristic for this new one? Maybe using Raphael's suggestions in the issue:

> -   only take new heap dumps when the memory increase is "significant" in some way - e.g. more than 1% of total memory (TBD)
> -   apply "smoothing" when determining what to keep: if the difference between min and max of RSS during a period is less than 1% (TBD) of total memory, consider this to be a single upramp

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114275)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, @DrewKimball, and @michae2)

___
*[`pkg/server/env_sampler.go` line 120 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114275#-Njhs1hh4Q9YBBHEqgKT:-NjjtpP2A5caG5FrfT_r:b-c8tgx8) ([raw file](https://github.com/cockroachdb/cockroach/blob/db314113ed1777547ed2c609de3275c9c3df6217/pkg/server/env_sampler.go#L120)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Just wanted to note: by sharing the `heapProfileDirName` here with all the other profiles, this means we share a "store" with the other profiles. 

A store in this case is a directory with a total size limit imposed on it, where older files are GC'd/deleted to make room for new ones once the limit is reached.

IIUC this means that this will introduce another profile type competing for its share of that size limit. Of course, since we're using the same heuristic as the `heapprofiler`, if one profiler generates a dump, so will the other.

There's been an open issue for a while now talking about how the existing heapprofiler dumps pretty aggressively: https://github.com/cockroachdb/cockroach/issues/91392

This means that this new `MemoryMonitoringProfiler` will be equally as aggressive with its heuristic. Any chance we can devise a less aggressive heuristic for this new one? Maybe using Raphael's suggestions in the issue:

> -   only take new heap dumps when the memory increase is "significant" in some way - e.g. more than 1% of total memory (TBD)
> -   apply "smoothing" when determining what to keep: if the difference between min and max of RSS during a period is less than 1% (TBD) of total memory, consider this to be a single upramp
</blockquote></details>

Interesting, thanks for the context. I think we actually do want to keep the heuristic for this new mem-monitoring profiler in sync with the existing heap profiler, so I'd argue any deviation from the current heuristic of the latter is undesirable. The rationale for keeping these in sync is that on its own the state of memory monitoring system at any point in time is mildly useful, but when we have a heap profile taken at the same time, then we can see how good our memory accounting was in comparison to live objects managed by Go runtime, which makes the new profiler more useful. So I think we should tackle #91392 and then this new profiler will inherit the improvements. I expect that the new mem-monitoring profiler should be less heavy in terms of impact on the system, but it would still increase the priority of addressing #91392.

Sharing the heap profiler store is now done by 5 different profilers. Its size is limited by `server.mem_profile.total_dump_size_limit` which is 128MiB by default which hasn't changed in at least 3 years. At the same time CPU profiler is the only one that has a separate setting which is also 128MiB by default. Thus, I wonder whether we should bump the default for `server.mem_profile.total_dump_size_limit` to 192MiB or 256MiB as part of this PR?

**Review by abarganier — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114275)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian, @DrewKimball, @michae2, and @yuzefovich)

___
*[`pkg/server/env_sampler.go` line 120 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114275#-Njhs1hh4Q9YBBHEqgKT:-NjmVdBzCdY8gsmOuR-7:b-5niqq0) ([raw file](https://github.com/cockroachdb/cockroach/blob/db314113ed1777547ed2c609de3275c9c3df6217/pkg/server/env_sampler.go#L120)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Interesting, thanks for the context. I think we actually do want to keep the heuristic for this new mem-monitoring profiler in sync with the existing heap profiler, so I'd argue any deviation from the current heuristic of the latter is undesirable. The rationale for keeping these in sync is that on its own the state of memory monitoring system at any point in time is mildly useful, but when we have a heap profile taken at the same time, then we can see how good our memory accounting was in comparison to live objects managed by Go runtime, which makes the new profiler more useful. So I think we should tackle #91392 and then this new profiler will inherit the improvements. I expect that the new mem-monitoring profiler should be less heavy in terms of impact on the system, but it would still increase the priority of addressing #91392.

Sharing the heap profiler store is now done by 5 different profilers. Its size is limited by `server.mem_profile.total_dump_size_limit` which is 128MiB by default which hasn't changed in at least 3 years. At the same time CPU profiler is the only one that has a separate setting which is also 128MiB by default. Thus, I wonder whether we should bump the default for `server.mem_profile.total_dump_size_limit` to 192MiB or 256MiB as part of this PR?
</blockquote></details>

Thanks for your thoughts - that plan SGTM!

Regarding increasing the default size limit, I think doubling to 256MiB is okay. As they say, disk is cheap(er) :sweat_smile: 

Anyway, things here re: use of the the runtime stats sampler system :lgtm:!

**Review by yuzefovich — COMMENTED** [review]
It looks like both @michae2 and @DrewKimball were writing something, so I let them push their feedback.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114275#-:-Njn4eOS79MRnHqNEJmQ:beqxius)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier, @dhartunian, @DrewKimball, and @michae2)

___
*[`pkg/server/env_sampler.go` line 120 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114275#-Njhs1hh4Q9YBBHEqgKT:-Njn4ZaS0wJOxLNCRH9p:b-9mpr2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/db314113ed1777547ed2c609de3275c9c3df6217/pkg/server/env_sampler.go#L120)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Thanks for your thoughts - that plan SGTM!

Regarding increasing the default size limit, I think doubling to 256MiB is okay. As they say, disk is cheap(er) :sweat_smile: 

Anyway, things here re: use of the the runtime stats sampler system :lgtm:!
</blockquote></details>

Sounds good, added another commit to bump the default to 256MiB.

**Review by DrewKimball — APPROVED** [review]
Sorry for the delay, :lgtm:

> Reviewed 8 of 8 files at r1, 14 of 14 files at r3, 13 of 13 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114275#-:-NjsJpNZ5HH_KTgXGDYR:bg1jfsl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier, @dhartunian, and @michae2)

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Pull request merged**
