### PR TITLE
storage: trim backpressurable request methods

### LINKED ISSUE #34210: storage: more discriminate write backpressure on large ranges
@nvanbenschoten I'd like to discuss a couple of thinks around `backpressurableReqMethods`:
https://github.com/cockroachdb/cockroach/blob/5c1ffd19e0dc7e99c1d4425949899d0fab88af19/pkg/storage/replica_backpressure.go#L50

1) Should `QueryIntent` be in that list?
2) Should we exempt rollbacks?
3) Should we exempt commits?

### PR DESCRIPTION
**Pull request by nvb**
Fixes #34210.

This change makes two adjustments to the `backpressurableReqMethods`:
1. it removes ClearRange from the set of methods that can be backpressured
   because this request type can't write data.
2. it removes transaction management requests from the set of methods
   that can be backpressured because these requests on their own should
   only add short-lived state to a range. Backpressuring the transactions'
   writing ops is sufficient.

Release note: None

### CODE REVIEW

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34292)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/storage/replica_backpressure.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34292#-LXK6tX_CZbcz74BcBzL:-LXK6tXaATZMMDwx8467:b6sc7he) ([raw file](https://github.com/cockroachdb/cockroach/blob/04059cdaee1fe9bd668e94aa5439438890ee6cb2/pkg/storage/replica_backpressure.go#L49)):*
> ```Go
> // backpressurableReqMethods is the set of all request methods that can
> // be backpressured. If a batch contains any method outside of this set,
> // it will not be backpressured.
> ```

In particular, `BeginTransaction; Put x 1000; EndTransaction` won't be backpressured now, right? That might've been the original reason to add `{Begin,End}Transaction`. Should this mechanism work the other way around? If any of the methods are backpressurable, the whole batch will be affected.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34292)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)

___
*[pkg/storage/replica_backpressure.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34292#-LXK6tX_CZbcz74BcBzL:-LY3TcKZBE6WkBCrL_JM:bwjfmm6) ([raw file](https://github.com/cockroachdb/cockroach/blob/04059cdaee1fe9bd668e94aa5439438890ee6cb2/pkg/storage/replica_backpressure.go#L49)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

In particular, `BeginTransaction; Put x 1000; EndTransaction` won't be backpressured now, right? That might've been the original reason to add `{Begin,End}Transaction`. Should this mechanism work the other way around? If any of the methods are backpressurable, the whole batch will be affected.
</blockquote></details>

+1 to inverting the mechanism
An maybe also have a white-list for splits and gc, ensuring those are never back-pressured?

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34292)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/storage/replica_backpressure.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34292#-LXK6tX_CZbcz74BcBzL:-LZaKUUwCVTr2gVN68l9:b-fubek6) ([raw file](https://github.com/cockroachdb/cockroach/blob/04059cdaee1fe9bd668e94aa5439438890ee6cb2/pkg/storage/replica_backpressure.go#L49)):*
Good point. Done. Also added a test that would have caught this.

> An maybe also have a white-list for splits and gc, ensuring those are never back-pressured?

The whitelist for splits is already there. GC shouldn't need one because it only sends GC requests.

**Review by andreimatei — COMMENTED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34292#-:-LZfSzvsENzve6JQ2iCn:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

**Pull request merged**
