### PR TITLE
changefeedccl: add a fine-grained checkpoint test

### PR DESCRIPTION
**Pull request by rharding6373**
This test generates 100 random non-overlapping spans with random
timestamps within a minute of each other and turns them into checkpoint
spans. It then does some sanity checks. It also compares the total
catchup time between the checkpoint timestamp and the high watermark.
This will form the basis to explore other fine-grain checkpointing
algorithms.

Epic: None

Release note: None

### CODE REVIEW

**Review by andyyang890 — COMMENTED** [review]
Nice test!

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129530#-:-O5ZclWZ49Ej6jhFDzmX:bds3i29)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rharding6373 and @wenyihu6)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129530#-O5ZWcJ-85ZDblo_X2zC):*
nit: s/fine grain/fine-grained/
___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129530#-O5ZWgNr7QP4RuAln23v):*
nit: ditto as above
___
*[`pkg/ccl/changefeedccl/changefeed_processors_test.go` line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129530#-O5ZZtKN-uRcRJSRXgiY:-O5ZZtKN-uRcRJSRXgiZ:bf1210t) ([raw file](https://github.com/cockroachdb/cockroach/blob/671bf9edb562de99971e8f40c8463ff1fa2457d4/pkg/ccl/changefeedccl/changefeed_processors_test.go#L158)):*
> ```Go
> }
> 
> type spanCP struct {
> ```

nit: consider renaming to `cpSpan` or even `checkpointSpan` for clarity and consistency
___
*[`pkg/ccl/changefeedccl/changefeed_processors_test.go` line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129530#-O5Zcs-Z3_9BzkVdqvCj:-O5Zcs-Z3_9BzkVdqvCk:b2mfkom) ([raw file](https://github.com/cockroachdb/cockroach/blob/671bf9edb562de99971e8f40c8463ff1fa2457d4/pkg/ccl/changefeedccl/changefeed_processors_test.go#L177)):*
> ```Go
> }
> 
> func TestGetCheckpointSpans(t *testing.T) {
> ```

Could you copy/adapt the commit message as a comment on top of this test?
___
*[`pkg/ccl/changefeedccl/changefeed_processors_test.go` line 178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129530#-O5ZYH-P8hOPIhkDxWQR:-O5ZYH-P8hOPIhkDxWQS:bu74atm) ([raw file](https://github.com/cockroachdb/cockroach/blob/671bf9edb562de99971e8f40c8463ff1fa2457d4/pkg/ccl/changefeedccl/changefeed_processors_test.go#L178)):*
> ```Go
> 
> func TestGetCheckpointSpans(t *testing.T) {
> 	numSpans := 100
> ```

nit: use `const`
___
*[`pkg/ccl/changefeedccl/changefeed_processors_test.go` line 203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129530#-O5ZcDHFDP4CBTVRVf6P:-O5ZcDHFDP4CBTVRVf6Q:b-ij7k3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/671bf9edb562de99971e8f40c8463ff1fa2457d4/pkg/ccl/changefeedccl/changefeed_processors_test.go#L203)):*
> ```Go
> 
> 	// Compute the checkpoint.
> 	resSpans, ts := getCheckpointSpans(hwm, forEachSpan, maxBytes)
> ```

Could you rename these `checkpointSpans` and `checkpointTS`?
___
*[`pkg/ccl/changefeedccl/changefeed_processors_test.go` line 223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129530#-O5ZcQTtEiqlJDR9bW6r:-O5ZcQTtEiqlJDR9bW6s:b-rhq3vw) ([raw file](https://github.com/cockroachdb/cockroach/blob/671bf9edb562de99971e8f40c8463ff1fa2457d4/pkg/ccl/changefeedccl/changefeed_processors_test.go#L223)):*
> ```Go
> 		100*(1-float64(catchupFromCheckpoint.Nanoseconds())/float64(catchupFromHWM.Nanoseconds())))
> 	require.Less(t, catchupFromCheckpoint, catchupFromHWM)
> 	require.Less(t, len(resSpans), numSpans)
> ```

Seems like this assertion and the one below it could be moved up to right under the `getCheckpointSpans` call
___
*[`pkg/sql/schemachanger/comparator_generated_test.go` line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129530#-O5ZW6745PE8eP8vvxmF:-O5ZW6745PE8eP8vvxmG:b6zfi7k) ([raw file](https://github.com/cockroachdb/cockroach/blob/671bf9edb562de99971e8f40c8463ff1fa2457d4/pkg/sql/schemachanger/comparator_generated_test.go#L211)):*
> ```Go
> 	runSchemaChangeComparatorTest(t, logicTestFile)
> }
> func TestSchemaChangeComparator_cdc_eval(t *testing.T) {
> ```

Was this accidentally included?

**Review by rharding6373 — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129530#-:-O5aPdUW5BU-oenGrc6m:b-814g8k)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andyyang890 and @wenyihu6)

___
*[`pkg/ccl/changefeedccl/changefeed_processors_test.go` line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129530#-O5ZZtKN-uRcRJSRXgiY:-O5aNBUGAeP0uIm1YuOV:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/671bf9edb562de99971e8f40c8463ff1fa2457d4/pkg/ccl/changefeedccl/changefeed_processors_test.go#L158)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

nit: consider renaming to `cpSpan` or even `checkpointSpan` for clarity and consistency
</blockquote></details>

done
___
*[`pkg/ccl/changefeedccl/changefeed_processors_test.go` line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129530#-O5Zcs-Z3_9BzkVdqvCj:-O5aNiql6b73ohSkJ1Jy:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/671bf9edb562de99971e8f40c8463ff1fa2457d4/pkg/ccl/changefeedccl/changefeed_processors_test.go#L177)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Could you copy/adapt the commit message as a comment on top of this test?
</blockquote></details>

done
___
*[`pkg/ccl/changefeedccl/changefeed_processors_test.go` line 178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129530#-O5ZYH-P8hOPIhkDxWQR:-O5aNoop9fMqP7kXdnxn:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/671bf9edb562de99971e8f40c8463ff1fa2457d4/pkg/ccl/changefeedccl/changefeed_processors_test.go#L178)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

nit: use `const`
</blockquote></details>

done
___
*[`pkg/ccl/changefeedccl/changefeed_processors_test.go` line 203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129530#-O5ZcDHFDP4CBTVRVf6P:-O5aO3IAACf4yYLQFG3K:b-t28bxt) ([raw file](https://github.com/cockroachdb/cockroach/blob/671bf9edb562de99971e8f40c8463ff1fa2457d4/pkg/ccl/changefeedccl/changefeed_processors_test.go#L203)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Could you rename these `checkpointSpans` and `checkpointTS`?
</blockquote></details>

Sorry for the terrible names. `checkpointSpans` was taken so I used `cpSpans` and `cpTS` instead.
___
*[`pkg/ccl/changefeedccl/changefeed_processors_test.go` line 223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129530#-O5ZcQTtEiqlJDR9bW6r:-O5aOEK0-jU93YuSV8xC:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/671bf9edb562de99971e8f40c8463ff1fa2457d4/pkg/ccl/changefeedccl/changefeed_processors_test.go#L223)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Seems like this assertion and the one below it could be moved up to right under the `getCheckpointSpans` call
</blockquote></details>

done

**Review by andyyang890 — APPROVED** [review]
Thanks for making the changes!

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129530#-:-O5aW-WY47N9Wdgr4fdQ:bl137vd)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rharding6373 and @wenyihu6)

___
*[`pkg/ccl/changefeedccl/changefeed_processors_test.go` line 177 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129530#-O5aVHEK9wjshu9T24w_:-O5aVHEK9wjshu9T24wa:b52u9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d5d595e670a08b8b10e4e68442e28d705f1c24d/pkg/ccl/changefeedccl/changefeed_processors_test.go#L177)):*
> ```Go
> }
> 
> // This test generates 100 random non-overlapping spans with random
> ```

nit: s/This test/TestGetCheckpointSpans/
___
*[`pkg/sql/schemachanger/comparator_generated_test.go` line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129530#-O5ZW6745PE8eP8vvxmF:-O5aVmfh4BFbV-Qga1Pm:b-ttmzdd) ([raw file](https://github.com/cockroachdb/cockroach/blob/671bf9edb562de99971e8f40c8463ff1fa2457d4/pkg/sql/schemachanger/comparator_generated_test.go#L211)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Was this accidentally included?
</blockquote></details>

Bump, I think this file needs to be removed

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129530)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andyyang890 and @wenyihu6)

___
*[`pkg/ccl/changefeedccl/changefeed_processors_test.go` line 177 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129530#-O5aVHEK9wjshu9T24w_:-O5aYw1DABC-AYfxR03C:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d5d595e670a08b8b10e4e68442e28d705f1c24d/pkg/ccl/changefeedccl/changefeed_processors_test.go#L177)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

nit: s/This test/TestGetCheckpointSpans/
</blockquote></details>

done
___
*[`pkg/sql/schemachanger/comparator_generated_test.go` line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129530#-O5ZW6745PE8eP8vvxmF:-O5aYx0I2sh-LRsxaw_M:bhjr9g4) ([raw file](https://github.com/cockroachdb/cockroach/blob/671bf9edb562de99971e8f40c8463ff1fa2457d4/pkg/sql/schemachanger/comparator_generated_test.go#L211)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Bump, I think this file needs to be removed
</blockquote></details>

Sorry missed this comment somehow, thanks for bumping it. Should be gone now.

**Comment by rharding6373** [comment]
TFTR!

**Comment by rharding6373** [comment]
bors r=andyyang890

**Pull request merged**
