### PR TITLE
loopvarcapture: do not flag `defer` within local closure

### PR DESCRIPTION
**Pull request by renatolabs**
Previously, handling of `defer` statements in the `loopvarcapture`
linter was naive: whenever a `defer` statement in the body of a loop
referenced a loop variable, the linter would flag it as an invalid
reference. However, that can be overly restrictive, as a relatively
common idiom is to create literal functions and immediately call them
so as to take advantage of `defer` semantics, as in the example below:

```go
for _, n := range numbers {
    // ...
    func() {
           // ...
           defer func() { doSomewithing(n) }() // always safe
           // ...
    }()
}
```

The above reference is valid because it is guaranteed to be called
with the correct value for the loop variable.

A similar scenario occurs when a closure is assigned to a local
variable for use within the loop:

```go
for _, n := range numbers {
    // ...
    helper := func() {
           // ...
           defer func() { doSomething(n) }()
           // ...
    }
    // ...
    helper() // always safe
}
```

In the snippet above, calling the `helper` function is also always
safe because the `defer` statement is scoped to the closure containing
it. However, it is still *not* safe to call the helper function within
a Go routine.

This commit updates the `loopvarcapture` linter to recognize when a
`defer` statement is safe because it is contained in a local
closure. The two cases illustrated above will no longer be flagged,
allowing for that idiom to be used freely.

Release note: None.

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
I can confirm that this fixes the linter issue with https://github.com/cockroachdb/cockroach/pull/79663. Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83418#-:-N5fVpSv67HblBefKeLB:bz90v1f)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @srosenberg)

**Review by dhartunian — APPROVED** [review]
friendly ping! can we merge this so I can unblock my PR? the test case looks straightforward to me.

**Review by srosenberg — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83418#-:-N5pJrgq28O4JwxFpdCY:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @renatolabs)

**Comment by renatolabs** [comment]
bors r=srosenberg,dhartunian

Thanks!

**Pull request merged**
