### PR TITLE
De-generalize the kv.send interface.

### PR DESCRIPTION
**Pull request by petermattis**
[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4127)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1, 6 of 6 files at r2, 6 of 6 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 6 of 6 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[kv/send.go, line 84 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4127#-K9hAQuY6d66ufuujRRB:-K9hAQuZ1VCKQRRJU-Ex:-327615458) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7ae2cae899e07eb9210217377c4b7cf1509f383/kv/send.go#L84)):*
There's something subtly off here but I don't remember. I made a similar comment on other code which ended up as
```
	// Randomize the order in which the keys are written.
	for i, n := 0, len(order)-2; i < n; i++ {
		j := i + rng.Intn(n-i)
		order[i], order[j] = order[j], order[i]
	}
```
It's in rocksdb_test.go

---

*[kv/send_test.go, line 167 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4127#-K9h9lOcbwhsM4EleX0O:-K9h9lOcbwhsM4EleX0P:1371699866) ([raw file](https://github.com/cockroachdb/cockroach/blob/e90589b5041d56b2043379801e8458b9ce8f4e7d/kv/send_test.go#L167)):*
weird to comment this all out in this commit, was that intended?

I see now that it has a commit dedicated to re-enabling it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4127)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[kv/send.go, line 84 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4127#-K9hAQuY6d66ufuujRRB:-K9hKEQK_fHRWP6uLL2S:-1478627543) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7ae2cae899e07eb9210217377c4b7cf1509f383/kv/send.go#L84)):*
I think the `rocksdb_test.go` code is wrong. If `len(order) = 2` it won't shuffle anything. The pseudo-code about fisher-yates shuffling on wikipedia is mildly confusing. It iterates using `for i from 0 to n−2 do` which I think should translate to `for i:= 0; i < n-1; i++`. 

Back to the code below, if `len(order) = 2` we'll perform a single iteration of the loop. We'll choose `j` as `0 + rand.Intn(2)` which is in the range `[0, 2)`.

I'll fix the `rocksdb_test.go` code in a separate PR.

---

*[kv/send_test.go, line 167 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4127#-K9h9lOcbwhsM4EleX0O:-K9hJg-2E3lEau4pJ_TN:233270356) ([raw file](https://github.com/cockroachdb/cockroach/blob/e90589b5041d56b2043379801e8458b9ce8f4e7d/kv/send_test.go#L167)):*
Yeah, I wasn't sure how to fix it when I commented out, then later I figured out what was needed. Didn't seem worth the effort to go back and patch up the original commit.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4127)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 2 files at r1, 4 of 6 files at r7, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[kv/dist_sender.go, line 342 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4127#-K9hOB9ww_jiyT52zkgJ:-K9hOB9ww_jiyT52zkgK:667859356) ([raw file](https://github.com/cockroachdb/cockroach/blob/29f7180964b3912fc45780157c1bd4eba2ee3f38/kv/dist_sender.go#L342)):*
Contrary to what I said before, sure this isn't racing? `getArgs` is called out-of-band by `rpcSend`. If you send one request and you give up on it (but the goroutine might still do something), sending the next request will use a shallow copy, so it'll share a lot of the underlying proto and that seems racy.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4127)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[kv/dist_sender.go, line 342 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4127#-K9hOB9ww_jiyT52zkgJ:-K9hQXNf5SqYptp8tzT1:20945345) ([raw file](https://github.com/cockroachdb/cockroach/blob/29f7180964b3912fc45780157c1bd4eba2ee3f38/kv/dist_sender.go#L342)):*
Pretty sure this isn't racing.  The goroutine only marshals the request. I looked at the tests as well and they don't seem to mutate the request. And the tests all pass with `testrace`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4127)*

**Comment by bdarnell** [comment]
LGTM

---

Review status: 6 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[kv/dist_sender.go, line 342 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4127#-K9hOB9ww_jiyT52zkgJ:-K9hzdGW-PXNb8D2bI60:-2015101889) ([raw file](https://github.com/cockroachdb/cockroach/blob/29f7180964b3912fc45780157c1bd4eba2ee3f38/kv/dist_sender.go#L342)):*
s/shall/shallow/

---

*[kv/dist_sender.go, line 344 \[r9\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4127#-K9i-2zyjyZ5JryWhJzw:-K9i-2zyjyZ5JryWhJzx:-1038391570) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8999e814719a3868014378e47279f022ec1bf9/kv/dist_sender.go#L344)):*
Does this need to be a pointer? (as opposed to `a := ba` and `return &a`)

---

*[kv/dist_sender.go, line 475 \[r9\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4127#-K9i-iTzxE99toYmq1sw:-K9i-iTzxE99toYmq1sx:1813465627) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8999e814719a3868014378e47279f022ec1bf9/kv/dist_sender.go#L475)):*
How many TODOs can one line of code accumulate before any of them get done? :)

---

*[kv/dist_sender_test.go, line 695 \[r9\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4127#-K9i0UVEm737HEarzAwN:-K9i0UVEm737HEarzAwO:458464381) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8999e814719a3868014378e47279f022ec1bf9/kv/dist_sender_test.go#L695)):*
I don't see how this comment applies any more (but then I'm not sure what the previous version of this test was doing either)

---

*[kv/send.go, line 84 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4127#-K9hAQuY6d66ufuujRRB:-K9i1b-eU1r_ePlu-Uk4:-1053159250) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7ae2cae899e07eb9210217377c4b7cf1509f383/kv/send.go#L84)):*
Maybe we should be using `math/rand.Perm` instead?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4127#-:-K9i2WFr2RkLP_BqD-9O:676834233)*

**Comment by tamird** [comment]
Review status: 6 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[kv/dist_sender.go, line 344 \[r9\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4127#-K9i-2zyjyZ5JryWhJzw:-K9i4bSzMZONfrJ9CjdM:58747186) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8999e814719a3868014378e47279f022ec1bf9/kv/dist_sender.go#L344)):*
I'm guessing @petermattis is trying to be explicit about the allocation.

---

*[kv/send.go, line 84 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4127#-K9hAQuY6d66ufuujRRB:-K9i4k7Eo2urRHWwOGZ-:-1913890567) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7ae2cae899e07eb9210217377c4b7cf1509f383/kv/send.go#L84)):*
That function allocates, which I guess is why we're avoiding it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4127)*

**Comment by tschottdorf** [comment]
LGTM. We should file an issue about the discussion we had regarding clearly separating out the mutable portion of BatchRequest.

---

Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[kv/dist_sender.go, line 475 \[r9\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4127#-K9i-iTzxE99toYmq1sw:-K9iOI0BiQzMMyatW5e5:-1870270125) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8999e814719a3868014378e47279f022ec1bf9/kv/dist_sender.go#L475)):*
I've wanted to refactor DistSender for a while, but there have always been other things to do (also, nudges to not refactor).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4127#-:-K9iOa-yNcadRdZ_o_t9:959370996)*

**Comment by petermattis** [comment]
Yep. I'll file an issue.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[kv/dist_sender.go, line 342 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4127#-K9hOB9ww_jiyT52zkgJ:-K9ixh7rmeTF-3aZx0h1:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/29f7180964b3912fc45780157c1bd4eba2ee3f38/kv/dist_sender.go#L342)):*
Done.

---

*[kv/dist_sender.go, line 344 \[r9\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4127#-K9i-2zyjyZ5JryWhJzw:-K9ixi4q_d28rsZ152kb:2110558342) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8999e814719a3868014378e47279f022ec1bf9/kv/dist_sender.go#L344)):*
Yes, just being explicit about the allocation. Doing a `return &a` would force `a` onto the heap which is equivalent, though less obvious than this code.

---

*[kv/dist_sender.go, line 475 \[r9\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4127#-K9i-iTzxE99toYmq1sw:-K9ixqfbbMMA9qGgoSkR:1351018659) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8999e814719a3868014378e47279f022ec1bf9/kv/dist_sender.go#L475)):*
Heh, this was added a Toby's request.

---

*[kv/dist_sender_test.go, line 695 \[r9\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4127#-K9i0UVEm737HEarzAwN:-K9ixw4_aVxe6RUqAJKV:1000276587) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8999e814719a3868014378e47279f022ec1bf9/kv/dist_sender_test.go#L695)):*
Yeah, I'm not sure what the previous test was doing either. Deleted the comment.

---

*[kv/send.go, line 84 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4127#-K9hAQuY6d66ufuujRRB:-K9iy8-K9f-ntX4bXTjF:-156465803) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7ae2cae899e07eb9210217377c4b7cf1509f383/kv/send.go#L84)):*
Yep, `rand.Perm` allocates. The previous code for shuffling the clients was doing several allocations. Now we do zero.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4127#-:-K9ixYmKOkfJYAtISYHd:61588565)*

**Pull request merged**
