### PR TITLE
ldapccl,sql: validate ldap options provided in HBA config entry

### PR DESCRIPTION
**Pull request by souravcrl**
fixes CRDB-41624
Epic: CRDB-33829

Currently, we validate ldap configuration provided as HBA entry options at the time an auth request comes in for ldap. This prevents us from disallowing invalid/incomplete list of ldap options in HBA. This PR fixes the issue.

Release note(security, ops): HBA config entry for LDAP will be evaluated with validations for proper ldap config parameter values and any invalid/incomplete options list will be disallowed to amend the HBA setting. We will validate all fields provided as ldap auth method options in HBA entry.

### CODE REVIEW

**Review by souravcrl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132086)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pritesh-lahoti)

___
*[`pkg/ccl/ldapccl/ldap_test_util.go` line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132086#-O8b7pvF1iXuTUTD-NyA:-O8b7pvF1iXuTUTD-NyB:b-8sqbh2) ([raw file](https://github.com/cockroachdb/cockroach/blob/948be6849e7c0fb47b745ce13d604def92c59518/pkg/ccl/ldapccl/ldap_test_util.go#L31)):*
> ```Go
> }
> 
> var _ ILDAPUtil = &mockLDAPUtil{}
> ```

@rafiss I had to revert the commit https://github.com/cockroachdb/cockroach/commit/829011184ac26d8a6d8a9ec327c40b75a13eb35a#diff-778d7debed4f62a13dfa1790c041bd2e42101d67ec4fca08c20dde9abc9886d5R68 to make this a test file as I need the mockLDAPUtil in `pkg/ccl/testccl/authccl` to run the LDAP test and did not want to duplicate this. Also the duplication would need ldapConfig to be made a public struct and wanted to avoid that. Is there a cleaner way to do this or are you okay with the change?

**Review by pritesh-lahoti — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132086)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pritesh-lahoti and @souravcrl)

___
*[`pkg/ccl/ldapccl/ldap_manager.go` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132086#-O8bH6DgElsb6tJR7tVg:-O8bH6DgElsb6tJR7tVh:bnjn5mi) ([raw file](https://github.com/cockroachdb/cockroach/blob/948be6849e7c0fb47b745ce13d604def92c59518/pkg/ccl/ldapccl/ldap_manager.go#L32)):*
> ```Go
> var (
> 	enableUseCounter = telemetry.GetCounterOnce(enableCounterName)
> 	ldapSearchRe     = regexp.MustCompile(`\(\s*\S+\s*=\s*\S+.*\)`)
> ```

nit: could we add details around how we came to this regex?
___
*[`pkg/ccl/ldapccl/ldap_manager.go` line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132086#-O8bJ3wk26IonXdbhkml:-O8bJ3wl-FnJQloKT8qX:b-gtl40z) ([raw file](https://github.com/cockroachdb/cockroach/blob/948be6849e7c0fb47b745ce13d604def92c59518/pkg/ccl/ldapccl/ldap_manager.go#L176)):*
> ```Go
> 		entryOptions[opt[0]] = true
> 	}
> 	// check for missing ldap options
> ```

nit: should this validation happen before the individual option parsing?
___
*[`pkg/sql/pgwire/auth_methods.go` line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132086#-O8bIQN1DVAhJHe2CyET:-O8bIQN1DVAhJHe2CyEU:bfgi52n) ([raw file](https://github.com/cockroachdb/cockroach/blob/948be6849e7c0fb47b745ce13d604def92c59518/pkg/sql/pgwire/auth_methods.go#L88)):*
> ```Go
> 	// with a LDAP server. The remaining connection parameters are provided in hba
> 	// conf options. This auth method is re-registered in ldapccl module with
> 	// proper handler for CheckHBAEntry.
> ```

Do we still need to register it here in that case?
The func reads `loadDefaultMethods` and ldap is probably not one of those.
___
*[`pkg/ccl/testccl/authccl/auth_test.go` line 208 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132086#-O8bKRlDEsJSMCVttyX4:-O8bKRlDEsJSMCVttyX5:bb7lc5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/948be6849e7c0fb47b745ce13d604def92c59518/pkg/ccl/testccl/authccl/auth_test.go#L208)):*
> ```Go
> 			t.Fatal(err)
> 		}
> 		httpHBAUrl := httpScheme + s.HTTPAddr() + "/debug/hba_conf"
> ```

nit:



_Suggestion:_
```Go
	httpHBAUrl := s.AdminURL().WithPath("/debug/hba_conf").String()
```
___
*[`pkg/ccl/testccl/authccl/auth_test.go` line 444 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132086#-O8bKsxaDwEzKW-kB199:-O8bKsxaDwEzKW-kB19A:b-fnvevt) ([raw file](https://github.com/cockroachdb/cockroach/blob/948be6849e7c0fb47b745ce13d604def92c59518/pkg/ccl/testccl/authccl/auth_test.go#L444)):*
> ```Go
> 					return strconv.Itoa(resp.StatusCode), nil
> 
> 				case "set_hba":
> ```

I don't quite see the `set_hba` command in the testdata file.

**Review by souravcrl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132086)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pritesh-lahoti)

___
*[`pkg/ccl/ldapccl/ldap_manager.go` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132086#-O8bH6DgElsb6tJR7tVg:-O8epY69A2W_NSrw6IHU:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/948be6849e7c0fb47b745ce13d604def92c59518/pkg/ccl/ldapccl/ldap_manager.go#L32)):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

nit: could we add details around how we came to this regex?
</blockquote></details>

done
___
*[`pkg/ccl/ldapccl/ldap_manager.go` line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132086#-O8bJ3wk26IonXdbhkml:-O8eppC--JoIdlyRuQ3F:b-zg53hy) ([raw file](https://github.com/cockroachdb/cockroach/blob/948be6849e7c0fb47b745ce13d604def92c59518/pkg/ccl/ldapccl/ldap_manager.go#L176)):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

nit: should this validation happen before the individual option parsing?
</blockquote></details>

Umm I am populating the `entryOptions` map at the time of validating the option. This would need additional logic to populate the map before validating but eventually we will end up validating both number and correctness of options.
___
*[`pkg/sql/pgwire/auth_methods.go` line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132086#-O8bIQN1DVAhJHe2CyET:-O8erGCUCKUULhBrqlQP:bc5kf4t) ([raw file](https://github.com/cockroachdb/cockroach/blob/948be6849e7c0fb47b745ce13d604def92c59518/pkg/sql/pgwire/auth_methods.go#L88)):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

Do we still need to register it here in that case?
The func reads `loadDefaultMethods` and ldap is probably not one of those.
</blockquote></details>

removed from here, we might risk registering an auth method for which doesn't have a check entry if auth method did not get re-registered.
___
*[`pkg/ccl/testccl/authccl/auth_test.go` line 208 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132086#-O8bKRlDEsJSMCVttyX4:-O8esMZA91oeYXRXVDz0:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/948be6849e7c0fb47b745ce13d604def92c59518/pkg/ccl/testccl/authccl/auth_test.go#L208)):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

nit:
</blockquote></details>

done
___
*[`pkg/ccl/testccl/authccl/auth_test.go` line 444 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132086#-O8bKsxaDwEzKW-kB199:-O8esNut4JAUt48DJ9Oz:b65bz0) ([raw file](https://github.com/cockroachdb/cockroach/blob/948be6849e7c0fb47b745ce13d604def92c59518/pkg/ccl/testccl/authccl/auth_test.go#L444)):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

I don't quite see the `set_hba` command in the testdata file.
</blockquote></details>

goland did not add the ldap test file. Have updated the commit now.

**Review by pritesh-lahoti — APPROVED** [review]
Nice exhaustive tests! Thank you, Sourav!

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132086#-:-O8gMTTf9x9JT52K8YZI:b-vf9xum)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pritesh-lahoti)

**Comment by souravcrl** [comment]
Thank you for the review!

bors r=pritesh-lahoti

**Comment by souravcrl** [comment]
blathers backport 24.2

**Pull request merged**
