### PR TITLE
ui: jobs page: render API call errors

### LINKED ISSUE #31396: ui: jobs page: handle API call errors
**Describe the problem**

I'm reproing https://github.com/cockroachdb/cockroach/issues/31094#issuecomment-429793161 on 10/08 beta. It was taking a while so I went to the adminui and saw the screenshot below. I then went to the sql shell and ran show jobs.

```
root@localhost:26257/defaultdb> show jobs;
        job_id       |   job_type    |                            description                             | user_name | status  |             created              |             started              | finished |             modified             | fraction_completed | error | coordinator_id  
+--------------------+---------------+--------------------------------------------------------------------+-----------+---------+----------------------------------+----------------------------------+----------+----------------------------------+--------------------+-------+----------------+
  391774989978042369 | SCHEMA CHANGE | CREATE INVERTED INDEX ix_vehicle_ext ON movr.public.vehicles (ext) | root      | running | 2018-10-15 19:10:37.747692+00:00 | 2018-10-15 19:10:48.879045+00:00 | NULL     | 2018-10-15 19:11:07.780042+00:00 |                  0 |       |           NULL  
(1 row)

Time: 2m20.308769578s
```

It took a long time for show jobs to finish. Once it finished, the admin ui functioned again.

**To Reproduce**

Same repro as https://github.com/cockroachdb/cockroach/issues/31094#issuecomment-429793161

**Additional data / screenshots**
image
image

**Environment:**
 - CockroachDB version 2.1 beta 1008

Logs
[cockroach.log](https://github.com/cockroachdb/cockroach/files/2480200/cockroach.log)

### PR DESCRIPTION
**Pull request by vilterp**
In the case of a timeout, instead of seeing a spinner forever, you'd see:
image

And in a 500 response from the backend, instead of a spinner forever you'd see:
image

We can improve the error messages themselves in a separate PR.

This the `Loading` component error rendering functionality introduced here can be used on other pages as well.

Fixes #31396

### CODE REVIEW

**Review by couchand — CHANGES_REQUESTED** [review]
Thanks! A couple minor comments but looks almost ready to go.

Please update the second commit release note with something like "Fixes a bug where errors while loading jobs would not be shown blah blah blah"

The gnoming is useful, could probably stand to be it's own commit.

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31865#-:-LPfa-k91vDamAL0WgrS:b90o6bz)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ui/src/views/jobs/index.tsx, line 362 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31865#-LPfcHrX2DsvOEYWywrx:-LPfcHrY2MWk5RsfF7D5:b-7nlllb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fd1b1e62c75615747083b1cef23b906d95c1e75/pkg/ui/src/views/jobs/index.tsx#L362)):*
> ```XML
>         <Loading
>           loading={_.isNil(this.props.jobs.data)}
>           error={this.props.jobs.lastError}
> ```

Previously, this was resilient to `this.props.jobs` being `null`.  I think it makes sense that it's actually always initialized but just wanted to check that's true.
___
*[pkg/ui/src/views/shared/components/loading/index.styl, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31865#-LPf_qdU9PrV629Fq9Lm:-LPf_qdV06WNy_c-05uV:b-s6z4qw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ba0db8900de0ad881722ec70b5dfd9cf4817881/pkg/ui/src/views/shared/components/loading/index.styl#L19)):*
> ```Stylus
> .loading-error
>   padding 10px
>   background $notification-alert-fill-color
> ```

maybe to match the other alerts style this should also have `border thin solid $notification-alert-border-color`?
___
*[pkg/ui/src/views/shared/components/loading/index.tsx, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31865#-LPfawV2Cs0N68gkzqdc:-LPfawV36dvqCr_PHVzR:b-4gdnmh) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ba0db8900de0ad881722ec70b5dfd9cf4817881/pkg/ui/src/views/shared/components/loading/index.tsx#L22)):*
> ```XML
> interface LoadingProps {
>   loading: boolean;
>   error?: Error;
> ```

I think this type is not quite right.  I suppose it is as long as we have implicit nulls, but you could make the intent clearer with `Error | null`.  This property has tri-state logic - an `Error` value means we got an error while loading, `null` means we didn't get an error, and `undefined` means we aren't using this feature (though we don't really distinguish the last two cases in practice).
___
*[pkg/ui/src/views/shared/components/loading/index.tsx, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31865#-LPfaVce4Gt1IrFsjUiw:-LPfaVce4Gt1IrFsjUix:b-6pjf3d) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ba0db8900de0ad881722ec70b5dfd9cf4817881/pkg/ui/src/views/shared/components/loading/index.tsx#L23)):*
> ```XML
>   loading: boolean;
>   error?: Error;
>   renderError?: (err: Error) => React.ReactNode;
> ```

This seems like an overcomplicated API for our usage.
___
*[pkg/ui/src/views/shared/components/loading/index.tsx, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31865#-LPfbe4e5GqFz3HBQnHZ:-LPfbe4e5GqFz3HBQnH_:buhzmvd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ba0db8900de0ad881722ec70b5dfd9cf4817881/pkg/ui/src/views/shared/components/loading/index.tsx#L44)):*
> ```XML
>     if (props.renderError) {
>       return (
>         <React.Fragment>
> ```

doesn't need to be wrapped (though I'm not sure we need this clause anyway)

**Review by vilterp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31865)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ui/src/views/jobs/index.tsx, line 362 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31865#-LPfcHrX2DsvOEYWywrx:-LPgX_GJ-BUxJ0kAbJds:bubpz8s) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fd1b1e62c75615747083b1cef23b906d95c1e75/pkg/ui/src/views/jobs/index.tsx#L362)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

Previously, this was resilient to `this.props.jobs` being `null`.  I think it makes sense that it's actually always initialized but just wanted to check that's true.
</blockquote></details>

This actually wasn't safe. Fixed & squashed. Would be fine for a normal reducer, but this is a `CachedDataReducer`.
___
*[pkg/ui/src/views/shared/components/loading/index.styl, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31865#-LPf_qdU9PrV629Fq9Lm:-LPgXhAo4hws3Xh-nesf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ba0db8900de0ad881722ec70b5dfd9cf4817881/pkg/ui/src/views/shared/components/loading/index.styl#L19)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

maybe to match the other alerts style this should also have `border thin solid $notification-alert-border-color`?
</blockquote></details>

Done.
___
*[pkg/ui/src/views/shared/components/loading/index.tsx, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31865#-LPfawV2Cs0N68gkzqdc:-LPgXn-A5OPSWAiXDYHC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ba0db8900de0ad881722ec70b5dfd9cf4817881/pkg/ui/src/views/shared/components/loading/index.tsx#L22)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

I think this type is not quite right.  I suppose it is as long as we have implicit nulls, but you could make the intent clearer with `Error | null`.  This property has tri-state logic - an `Error` value means we got an error while loading, `null` means we didn't get an error, and `undefined` means we aren't using this feature (though we don't really distinguish the last two cases in practice).
</blockquote></details>

Done.
___
*[pkg/ui/src/views/shared/components/loading/index.tsx, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31865#-LPfaVce4Gt1IrFsjUiw:-LPgXjyx5j8qGaTobs3W:b-vg6rci) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ba0db8900de0ad881722ec70b5dfd9cf4817881/pkg/ui/src/views/shared/components/loading/index.tsx#L23)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

This seems like an overcomplicated API for our usage.
</blockquote></details>

Done. Removed `renderError`. Can add back in if needed.
___
*[pkg/ui/src/views/shared/components/loading/index.tsx, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31865#-LPfbe4e5GqFz3HBQnHZ:-LPgXpsM9Bjg3zsTLoOm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ba0db8900de0ad881722ec70b5dfd9cf4817881/pkg/ui/src/views/shared/components/loading/index.tsx#L44)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

doesn't need to be wrapped (though I'm not sure we need this clause anyway)
</blockquote></details>

Done.

**Review by couchand — APPROVED** [review]
LGTM, thanks!

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31865#-:-LQ-W8AU6lzxIcUcEThB:b2c0zcb)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ui/src/views/jobs/index.tsx, line 362 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31865#-LPfcHrX2DsvOEYWywrx:-LQ-VknQ5cl-FtNFOXP8:bb6mt9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fd1b1e62c75615747083b1cef23b906d95c1e75/pkg/ui/src/views/jobs/index.tsx#L362)):*
<details><summary><i>Previously, vilterp (Pete Vilter) wrote…</i></summary><blockquote>

This actually wasn't safe. Fixed & squashed. Would be fine for a normal reducer, but this is a `CachedDataReducer`.
</blockquote></details>

:+1:

**Review by vilterp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31865)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ui/src/views/jobs/index.tsx, line 362 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31865#-LPfcHrX2DsvOEYWywrx:-LQ-gZ0H9__NV70jN8at:b-7clj0j) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fd1b1e62c75615747083b1cef23b906d95c1e75/pkg/ui/src/views/jobs/index.tsx#L362)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

:+1:
</blockquote></details>

meant "would be fine in a normal `CachedDataReducer`, but this is a `KeyedCachedDataReducer`"

**Pull request merged**
