### PR TITLE
acceptance: fix and re-enable TestPartitionBank

### PR DESCRIPTION
**Pull request by andreimatei**
- make the test commit its transactions
- stop the nemesis before the final verification

The test does not seem flaky any more after ##9234, which remove the
distsender timeouts. The verification of this test now seems to pass
reliably, althought it can still take a long time due to a combination
of exponential backoffs and intents from other transactions that are not
cleaned up because of the partitioning.

Fixes #9182

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9681)

### CODE REVIEW

**Comment by tamird** [comment]
Why not reopen https://github.com/cockroachdb/cockroach/pull/9295 ?

**Comment by andreimatei** [comment]
Oh didn't realize that's an option. Doing that, thanks.

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[acceptance/partition_test.go, line 154 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9681#-KTAR7L9dwfPsytCJ4bR:-KTAR7L9dwfPsytCJ4bS:bv5djc7) ([raw file](https://github.com/cockroachdb/cockroach/blob/69e9c14a8105e737aa18b6432b18060b68cdac43/acceptance/partition_test.go#L154)):*
> ```Go
> 	{
> 		rFrom := txn.QueryRow(fmt.Sprintf(
> 			`/* %d: sel1 */ SELECT balance FROM bank.accounts WHERE id = $1`, i),
> ```

can you revert all this stuff? it's not clear to me how it's useful without additional logging in the sql package.

---

*[acceptance/partition_test.go, line 182 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9681#-KTARRL4mdfbNt61ghwc:-KTARRL4mdfbNt61ghwd:bcvt8a6) ([raw file](https://github.com/cockroachdb/cockroach/blob/69e9c14a8105e737aa18b6432b18060b68cdac43/acceptance/partition_test.go#L182)):*
> ```Go
> 		b.Init(accounts, 10)
> 		runTransactionsAndNemeses(t, c, b, cfg.Duration, nemeses...)
> 		log.Warningf(context.Background(), "verifying")
> ```

no need for `f`. also, why is this a warning? finally, shouldn't this be in `Verify()`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9681)*

**Comment by tschottdorf** [comment]
:lgtm: mod what @tamird says.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[acceptance/partition_test.go, line 172 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9681#-KTAvyGLwDKcfAtd3diz:-KTAvyGMXH6xXm4US6JL:b-1hsizs) ([raw file](https://github.com/cockroachdb/cockroach/blob/69e9c14a8105e737aa18b6432b18060b68cdac43/acceptance/partition_test.go#L172)):*
> ```Go
> 		bTo+amount, to)
> 	handle(err)
> 	err = txn.Commit()
> ```

`handle(txn.Commit())`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9681#-:-KTAwXCRJ60L5mUzKaCR:b-lrty0e)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9681)*

**Comment by tschottdorf** [comment]
Not sure what's missing here, but has my LGTM, unassigning.

**Comment by andreimatei** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[acceptance/partition_test.go, line 154 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9681#-KTAR7L9dwfPsytCJ4bR:-K_BS3ODpUbeGGy06Ccp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/69e9c14a8105e737aa18b6432b18060b68cdac43/acceptance/partition_test.go#L154)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can you revert all this stuff? it's not clear to me how it's useful without additional logging in the sql package.
</blockquote></details>

Done.

---

*[acceptance/partition_test.go, line 172 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9681#-KTAvyGLwDKcfAtd3diz:-K_BQDzBUm6i3FMZX6r3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/69e9c14a8105e737aa18b6432b18060b68cdac43/acceptance/partition_test.go#L172)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

`handle(txn.Commit())`
</blockquote></details>

Done.

---

*[acceptance/partition_test.go, line 182 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9681#-KTARRL4mdfbNt61ghwc:-K_BS4ELy4Zf-QwBPYx3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/69e9c14a8105e737aa18b6432b18060b68cdac43/acceptance/partition_test.go#L182)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

no need for `f`. also, why is this a warning? finally, shouldn't this be in `Verify()`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9681)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9681#-:-K_Bjd2-2FOvXXTQrJLH:bnfp4nl)*

**Pull request merged**
