### PR TITLE
sql: prevent connection closure with nested arrays and binary format

### LINKED ISSUE #118206: roachtest: npgsql failed [crashes with unsupported binary serialization of multidimensional arrays]
roachtest.npgsql [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13656934?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13656934?buildTab=artifacts#/npgsql) on master @ [585ffa0acfa6dd771aad8320d3a9e219acf56656](https://github.com/cockroachdb/cockroach/commits/585ffa0acfa6dd771aad8320d3a9e219acf56656):

```
--- FAIL: Npgsql.Tests.Types.MiscTypeTests(Multiplexing).Send_unknown -  (unexpected)
--- FAIL: Npgsql.Tests.Types.NumericTests(NonMultiplexing).Read("1E+24::numeric",1000000000000000000000000m) -  (unexpected)
--- FAIL: Npgsql.Tests.Types.JsonTests(NonMultiplexing,Jsonb).Write_as_ArraySegment_of_char -  (unexpected)
--- FAIL: Npgsql.Tests.Replication.PgOutputReplicationTests(V2,DefaultReplicationDataMode,StreamingTransactionMode).Truncate(Cascade) -  (unexpected)
--- FAIL: Npgsql.Tests.Types.NumericTests(Multiplexing).Read("1111.2222333344445555666677778::numeric",1111.2222333344445555666677778m) -  (unexpected)
--- FAIL: Npgsql.Tests.Types.NumericTests(Multiplexing).Write_BigInteger("1E+28::numeric",10000000000000000000000000000m) -  (unexpected)
--- FAIL: Npgsql.Tests.Types.CompositeHandlerTests.Read_type_with_more_properties_than_attributes -  (unexpected)
--- FAIL: Npgsql.Tests.Types.NumericTests(NonMultiplexing).Read_BigInteger("-2.5::numeric(10,0)",-3m) -  (unexpected)
--- FAIL: Npgsql.Tests.Types.NumericTests(NonMultiplexing).Read_BigInteger("-1.4::numeric(10,0)",-1m) -  (unexpected)
--- FAIL: Npgsql.Tests.Types.NumericTests(Multiplexing).Read("-2.4::numeric(10,0)",-2m) -  (unexpected)
--- FAIL: Npgsql.Tests.Types.NumericTypeTests(NonMultiplexing).Double -  (unexpected)
--- FAIL: Npgsql.Tests.Replication.PgOutputReplicationTests(V3,DefaultReplicationDataMode,DefaultTransactionMode).CompositeType -  (unexpected)
--- FAIL: Npgsql.Tests.Types.NumericTests(NonMultiplexing).Read_BigInteger("100000000000000000000::numeric",100000000000000000000m) -  (unexpected)
--- FAIL: Npgsql.Tests.Types.NumericTests(NonMultiplexing).Read("1000000000000000000000000::numeric",1000000000000000000000000m) -  (unexpected)
--- FAIL: Npgsql.Tests.Types.NumericTests(NonMultiplexing).Read("1E-4::numeric",0.0001m) -  (unexpected)
--- FAIL: Npgsql.Tests.Types.CompositeHandlerTests.Write_type_without_getter_throws -  (unexpected)
--- FAIL: Npgsql.Tests.Types.TextTests(NonMultiplexing).Text_as_array_of_chars -  (unexpected)
--- FAIL: Npgsql.Tests.Types.NumericTests(Multiplexing).Read_BigInteger("-2.5::numeric(10,0)",-3m) -  (unexpected)
--- FAIL: Npgsql.Tests.Types.NumericTests(NonMultiplexing).Write("1111.2222333344445555666677778::numeric",1111.2222333344445555666677778m) -  (unexpected)
--- FAIL: Npgsql.Tests.Types.NumericTests(Multiplexing).Write_BigInteger("100000000::numeric",100000000m) -  (unexpected)
--- FAIL: Npgsql.Tests.Types.CompositeHandlerTests.Read_type_with_private_setter_throws -  (unexpected)
--- FAIL: Npgsql.Tests.Types.NumericTests(Multiplexing).Read("+79228162514264337593543950335::numeric",decimal.MaxValue) -  (unexpected)
--- FAIL: Npgsql.Tests.Types.DateTimeTests.Date_as_DateOnly -  (unexpected)
--- FAIL: Npgsql.Tests.Types.NumericTests(NonMultiplexing).Read("1.5::numeric(10,0)",2m) -  (unexpected)
--- FAIL: Npgsql.Tests.Types.NumericTests(NonMultiplexing).Write("0.000000000001::numeric",0.000000000001m) -  (unexpected)
--- FAIL: Npgsql.Tests.Types.NumericTests(Multiplexing).Write_BigInteger("1.5::numeric(10,0)",2m) -  (unexpected)
--- FAIL: Npgsql.Tests.FunctionTests.Void -  (unexpected)
--- FAIL: Npgsql.Tests.Types.NumericTests(NonMultiplexing).Write("1.2::numeric(10,4)",1.2000m) -  (unexpected)
--- FAIL: Npgsql.Tests.Types.CompositeHandlerTests.Write_type_without_setter -  (unexpected)
--- FAIL: Npgsql.Tests.Types.NumericTests(NonMultiplexing).Write_BigInteger("1000000000000000000000000::numeric",1000000000000000000000000m) -  (unexpected)
--- FAIL: Npgsql.Tests.Types.NumericTests(NonMultiplexing).Read_BigInteger("-2.4::numeric(10,0)",-2m) -  (unexpected)
--- FAIL: Npgsql.Tests.Types.MiscTypeTests(NonMultiplexing).Write_Record_is_not_supported -  (unexpected)
--- FAIL: Npgsql.Tests.Types.NumericTests(NonMultiplexing).Read("0.0001::numeric",0.0001m) -  (unexpected)
--- FAIL: Npgsql.Tests.Types.NumericTests(NonMultiplexing).Write("0.0001::numeric",0.0001m) -  (unexpected)
--- FAIL: Npgsql.Tests.Types.NumericTests(NonMultiplexing).Read("10000000000000000::numeric",10000000000000000m) -  (unexpected)
--- FAIL: Npgsql.Tests.Types.DateTimeTests.Datemultirange_as_array_of_NpgsqlRange_of_DateTime -  (unexpected)
--- FAIL: Npgsql.Tests.Types.ArrayTests(NonMultiplexing).IEnumerable_throws_friendly_exception -  (unexpected)
--- FAIL: Npgsql.Tests.Types.NumericTests(NonMultiplexing).Write("2.4::numeric(10,0)",2m) -  (unexpected)
--- FAIL: Npgsql.Tests.Types.NumericTests(NonMultiplexing).Write_BigInteger("-1.5::numeric(10,0)",-2m) -  (unexpected)
--- FAIL: Npgsql.Tests.Types.NumericTests(Multiplexing).Read("0.000000000001::numeric",0.000000000001m) -  (unexpected)
--- FAIL: Npgsql.Tests.Types.CompositeHandlerTests.Write_struct_with_property -  (unexpected)
--- FAIL: Npgsql.Tests.Types.NumericTests(NonMultiplexing).Write_BigInteger("100000000000000000000::numeric",100000000000000000000m) -  (unexpected)
--- FAIL: Npgsql.Tests.Types.MiscTypeTests(Multiplexing).Boolean -  (unexpected)
--- FAIL: Npgsql.Tests.Replication.PgOutputReplicationTests(V1,BinaryReplicationDataMode,DefaultTransactionMode).TextReader -  (unexpected)
--- FAIL: Npgsql.Tests.Types.DateTimeTests.Timestamp_as_long -  (unexpected)
--- FAIL: Npgsql.Tests.FunctionTests.DeriveParameters_non_existing_function -  (unexpected)
--- FAIL: Npgsql.Tests.Replication.PgOutputReplicationTests(V3,DefaultReplicationDataMode,DefaultTransactionMode).LogicalDecodingMessage(False) -  (unexpected)
For a full summary look at the npgsql artifacts 
An updated blocklist (npgsqlBlocklist) is available in the artifacts' npgsql log
test artifacts and logs in: /artifacts/npgsql/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-13656934/npgsql/1706020185997/1706020475108)

</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*npgsql.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-35609

### PR DESCRIPTION
**Pull request by yuzefovich**
Currently, whenever the multidimensional arrays gets serialized into the binary format, an error is returned, and because it's considered a "communication error", it results in the connection shutdown. Until recently we simply prohibited creating statement results with nested arrays, but now we allow it. This commit fixes the ungraceful connection closure by reverting to the old behavior of returning an error in `checkResultType` function for nested arrays whenever binary formatting is requested.

Fixes: #118206.

Release note: None

### CODE REVIEW

**Review by michae2 — COMMENTED** [review]
The approach makes sense to me, but I would feel more comfortable if @rafiss looks at it, too.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118376#-:-NpLpTfD2lHP-7WgHNir:bioeqc5)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @yuzefovich)

___
*[`pkg/sql/pgwire/command_result.go` line 224 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118376#-NpLntzt-1txIeQqEiDe:-NpLntzt-1txIeQqEiDf:b-7p3j3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e81c99c231624d37b7e4262e70b04d44adc7828/pkg/sql/pgwire/command_result.go#L224)):*
> ```Go
> 	if r.formatCodes != nil {
> 		if colIdx >= len(r.formatCodes) {
> 			if len(r.formatCodes) == 1 && r.cmdCompleteTag == "EXPLAIN" {
> ```

Do we need to add this case because of the new call in `initStatementResult`?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118376)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @rafiss)

___
*[`pkg/sql/pgwire/command_result.go` line 224 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118376#-NpLntzt-1txIeQqEiDe:-NpMOR32DTKD-ZSfHnPv:b5qmwv1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e81c99c231624d37b7e4262e70b04d44adc7828/pkg/sql/pgwire/command_result.go#L224)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Do we need to add this case because of the new call in `initStatementResult`?
</blockquote></details>

Yes, exactly. We now call this new method `GetFormatCode` in `checkResultType` which is called in two places:
- in `initStatementResult`, whenever creating the command result that will be used to communicate data to the client
- and in `prepareUsingOptimizer`, whenever we're evaluating the PREPARE command (equivalent to `Parse` directive in the pgwire tests).

The need for this additional check arises when we're executing a prepared statement that is an EXPLAIN ANALYZE. When we evaluate EXPLAIN ANALYZE, we have format codes specified for the output of EXPLAIN ANALYZE (which has a single string column), but then during the execution in `execStmtInOpenState` we unwrap the SELECT that is behind EXPLAIN ANALYZE, so the execution engine only sees the SELECT. In `dispatchToExecutionEngine` we create a new command result (that is mostly ignored), and this is when we have the mismatch of format codes - our SELECT can return any number of columns whereas format codes specify output of EXPLAIN ANALYZE, which we kinda lost all knowledge of at this point.

"Vanilla" EXPLAIN doesn't have this problem (because it doesn't unwrap the SELECT and the query doesn't actually get executed), but both EXPLAIN and EXPLAIN ANALYZE share the command complete tag. This change abuses `cmdCompleteTag` a bit, but I didn't see anything else that would tell us whether this command result is being used in EXPLAIN ANALYZE context or not, and plumbing some new information for this specific use case to the pgwire commands seemed less than desirable.

Added a bit more details to the comment.

**Review by rafiss — APPROVED** [review]
this is a really nice cleanup. thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118376#-:-NpV1DC450Z-50IczuMz:b-khwrko)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @michae2)

**Review by mgartner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 7 of 8 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118376#-:-NpV9zQyEPE4DIq1gyYU:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @michae2)

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Pull request merged**
