### PR TITLE
sql: Show direction (ASC/DESC) of inverted index columns in SHOW CREATE TABLE output.

### LINKED ISSUE #73533: sql: direction of Inverted Index Columns is not displayed in `SHOW CREATE TABLE`
**Describe the problem**
In cockroach db, we do respect directions when storing inverted indexes. However, we don't show them with `SHOW CREATE TABLE` results. This is bad because we're giving out indication that direction doesn't matter for inverted indexes.

When formatting a AST node we do show it: http://github.com/cockroachdb/cockroach/blob/8b696d17241b2eb2d333e23750cf6fdc433897d8/pkg/sql/sem/tree/create.go#L147-L147

However this is dropped in `SHOW CREATE TABLE` for inverted index:
http://github.com/cockroachdb/cockroach/blob/8b696d17241b2eb2d333e23750cf6fdc433897d8/pkg/sql/catalog/catformat/index.go#L148-L148 

**To Reproduce**
```sql
create table t (
    id int primary key,
    note jsonb,
    nverted index idx_t_note (note)
);

select @2 as table_def from [ show create table t ];
                   table_def
-----------------------------------------------
  CREATE TABLE public.t (
      id INT8 NOT NULL,
      note JSONB NULL,
      CONSTRAINT t_pkey PRIMARY KEY (id ASC),
      INVERTED INDEX idx_t_note (note), -- direction is missing!
      FAMILY "primary" (id, note)
  )
```

**Expected behavior**
Show correction direction value for inverted indexes.

Jira issue: CRDB-11625

### PR DESCRIPTION
**Pull request by changhanlee**
fixes https://github.com/cockroachdb/cockroach/issues/73533
See commit message.

Release justification: Low impact, adds inverted index direction to SHOW CREATE TABLE output.

### CODE REVIEW

**Comment by changhanlee** [comment]
@ajwerner I'm not sure who to ask for a review. Would you be willing or is there someone else who I should be asking?

**Comment by changhanlee** [comment]
Or @chengxiong-ruan could I ask you to review?

**Comment by changhanlee** [comment]
Hello @otan, is there a way to find the correct reviewer for this? I've referenced the person who triaged the issue and a previous committer, but not sure if they're the right persons.

**Review by chengxiong-ruan — APPROVED** [review]
:lgtm: 
Thanks for fixing this :)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78549#-:-MzQO2XN9vKZje3NAWp7:bnjp9gx)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by changhanlee** [comment]
bors r=chengxiong-ruan

**Review by otan — CHANGES_REQUESTED** [review]
someone on our side will needs to bors for you. i can; but i noticed there's no test for the DESC case. mind adding one?

**Comment by changhanlee** [comment]
@chengxiong-ruan TFYR!
@otan OK, I will add some. Thank you.

**Comment by rafiss** [comment]
@changhanlee thanks! looks close, but one issue needs to be fixed:
```
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/logictest/testdata/logic_test/inverted_index:1481: SELECT @2 FROM [SHOW CREATE TABLE table_desc_inverted_index];
        expected:
            CREATE TABLE public.table_desc_inverted_index (
               id INT8 NOT NULL,
               testdata JSONB NULL,
               CONSTRAINT table_desc_inverted_index_pkey PRIMARY KEY (id ASC),
               INVERTED INDEX inv_idx_testdata (testdata DESC),
               FAMILY fam_0_id (id),
               FAMILY fam_1_testdata (testdata)
            )
        but found (query options: "") :
            CREATE TABLE public.table_desc_inverted_index (
               id INT8 NOT NULL,
               testdata JSONB NULL,
               CONSTRAINT table_desc_inverted_index_pkey PRIMARY KEY (id ASC),
               INVERTED INDEX inv_idx_testdata (testdata DESC),
               FAMILY fam_0_id_testdata (id, testdata)
            )
```

**Comment by rafiss** [comment]
this should be resolved by explicitly adding `FAMILY` clause to the `CREATE TABLE table_desc_inverted_index` statement.

we have some randomization in the tests that adds `FAMILY` if it was not explicitly specified.

**Comment by changhanlee** [comment]
Thank you for your explanation @rafiss!

**Review by otan — APPROVED** [review]

**Pull request merged**
