### PR TITLE
deps: upgrade golang.org/x/{crypto,mod,net,sys,text,tools,term}

### PR DESCRIPTION
**Pull request by andyyang890**
This patch updates the following core dependencies as follows:
* golang.org/x/crypto from v0.6.0 to v0.7.0
* golang.org/x/mod from v0.7.0 to v0.8.0
* golang.org/x/net from v0.7.0 to v0.8.0
* golang.org/x/sys from v0.5.0 to v0.6.0
* golang.org/x/text from v0.7.0 to v0.8.0
* golang.org/x/tools from v0.1.12 to v0.6.0
* golang.org/x/term from v0.5.0 to v0.6.0

Also update `rules_go` to a compatible version (0.38).

Informs #21001

Release note: None

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
lgtm!

**Comment by knz** [comment]
looking at the diffs in each repo,

- [ ]    golang.org/x/crypto from v0.6.0 to v0.7.0
- [ ]    golang.org/x/mod from v0.7.0 to v0.8.0
- [ ]    golang.org/x/net from v0.7.0 to v0.8.0
- [ ]    golang.org/x/sys from v0.5.0 to v0.6.0
- [ ]    golang.org/x/text from v0.7.0 to v0.8.0
- [ ]    golang.org/x/tools from v0.1.12 to v0.6.0
- [ ]    golang.org/x/term from v0.5.0 to v0.6.0

**Review by knz — APPROVED** [review]

**Comment by knz** [comment]
For references:

- in each of the packages, I ran `go log --patch vOLD...vNEW` and inspected the results:
  - for any changes to APIs that would impact our code
  - for any impl changes that could impact semantics we care about
  - didn't find anything worrying.
- for x/tools, that was way too many changes, so instead I ran `go log --patch vOLD...vNEW | diffstat` to first get a sense of which sub-packages saw most movement and focus the review there. This is how I noticed most of the changes were on `gopls`
- so I re-ran `go log vOLD...vNEW -- go/` in x/tools to get just the subset of changes pertaining to the go sub-directory, which is the one we used. Then I inspected that and satisfied myself that none of the changes impact our production code.

**Comment by andyyang890** [comment]
Thanks for the in-depth review!

bors r=rafiss,knz

**Comment by rickystewart** [comment]
blathers backport 23.1

**Pull request merged**
