### PR TITLE
kv: add comment explaining why an error is ignored

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7743)

### CODE REVIEW

**Comment by tschottdorf** [comment]
You could still `!testutils.IsError(err, "expected1|expected2")`, though I wouldn't if the array of possible errors is large.

**Comment by petermattis** [comment]
I'm not sure what all of the possible errors are.

**Comment by tamird** [comment]
Yeah, what @tschottdorf said. LGTM if the array of possible errors is unpleasantly learge.

**Comment by petermattis** [comment]
PTAL

**Comment by tschottdorf** [comment]
LGTM

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7743#-:-KMQjeVygiFs0BOSGuqm:1417088721)*

**Pull request merged**
