### PR TITLE
all: use deterministic marshalling of protos

### PR DESCRIPTION
**Pull request by tamird**
cc @tschottdorf

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5312)

### CODE REVIEW

**Comment by vivekmenezes** [comment]
Review status: 0 of 31 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/protoc-gen-gogoroach/main.go, line 50 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5312#-KD-p8jHDtLgOF4aQC_J:-KD-p8jHDtLgOF4aQC_K:1812417091) ([raw file](https://github.com/cockroachdb/cockroach/blob/722a8d77c180e75fc40da336bff1c385937c133e/cmd/protoc-gen-gogoroach/main.go#L50)):*
Can you add a comment here that we need this to ensure that the same protobuf when stored on disk on different machines will be byte for byte compatible.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5312)*

**Comment by vivekmenezes** [comment]
LGTM

---

Review status: 0 of 31 files reviewed at latest revision, 2 unresolved discussions.

---

*[roachpb/data_test.go, line 525 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5312#-KD-pi81rDHX6qvydivn:-KD-pi82ebFuHm5ArJm-:-1374821656) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c38a32304fb8bff5a2100e17f04996eead2f913/roachpb/data_test.go#L525)):*
Can you leave this in

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5312#-:-KD-pnwjhSg5BrAE0eYK:676834233)*

**Comment by tamird** [comment]
Review status: 0 of 31 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/protoc-gen-gogoroach/main.go, line 50 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5312#-KD-p8jHDtLgOF4aQC_J:-KD-qEXjql5F_GQmLdCV:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/722a8d77c180e75fc40da336bff1c385937c133e/cmd/protoc-gen-gogoroach/main.go#L50)):*
Done.

---

*[roachpb/data_test.go, line 525 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5312#-KD-pi81rDHX6qvydivn:-KD-rSvyHjEcqEBmC44r:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c38a32304fb8bff5a2100e17f04996eead2f913/roachpb/data_test.go#L525)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5312)*

**Comment by tschottdorf** [comment]
:lgtm:
Didn't look at the generated code, were you able to use that optimization that avoids the extra slice/sorting work if there's only one entry in the map? That'll be pretty common for us.

---

Reviewed 9 of 9 files at r1, 23 of 23 files at r2, 4 of 4 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5312#-:-KD-vFWYLj_A7UCDm5tB:868161761)*

**Comment by tamird** [comment]
I didn't. I ended up partially reverting an old commit upstream. I'm skeptical that this will cause a visible performance change, but we can always implement that upstream if we determine it's worth - at least the interfaces won't change.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5312#-:-KD-vYaaJPAxGYJ31bn-:-35676519)*

**Pull request merged**
