### PR TITLE
export: remove deprecated parquet library

### LINKED ISSUE #104278: export: clean up old parquet writer
https://github.com/cockroachdb/cockroach/pull/104234 introduces a new parquet writer to `EXPORT INTO PARQUET`, but does not clean up the old test code to ensure backward compatibility - dependencies and production code used by tests still remain as well. This should all be cleaned up. The old dependencies should be removed from the project. 

Jira issue: CRDB-28442

### PR DESCRIPTION
**Pull request by jayshrivastava**
This change removes the github.com/fraugster/parquet-go dependency and all code which uses it. This library has been unused since #104234 landed. This change officially removes the code and dependency from the repo.

This change also adds support for Oid-like types such as regrole, regtype etc to util/parquet. These types are
used in export parquet testing and were previously not supported by util/parquet.

Closes: #104278
Release note: None
Epic: None

### CODE REVIEW

**Comment by jayshrivastava** [comment]
@rharding6373 I believe CDC owns export now, so this should fall under our team for review.

**Review by rharding6373 — APPROVED** [review]
:lgtm: Nice to see so much code deletion.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120834#-:-NtWaav_8-0GDc2Ct6Lu:b6wmuvu)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

**Comment by jayshrivastava** [comment]
bors r=rharding6373

**Comment by jayshrivastava** [comment]
TYFR!

**Comment by rickystewart** [comment]
bors r-

Need to run `./dev gen bazel`

**Comment by rickystewart** [comment]
The problem here is `check_generated_code` flaked so you couldn't see the legitimate failure until you `bors`'ed. I'm going to take some steps to address the flakiness.

**Review by rickystewart — CHANGES_REQUESTED** [review]
Looks like `TestRandomParquetExports` [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/14499584?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildDeploymentsSection=true&expandBuildProblemsSection=true&expandBuildChangesSection=true&expandBuildTestsSection=true) in CI. It seems like it's flaky.

**Review by rickystewart — APPROVED** [review]

**Comment by jayshrivastava** [comment]
TYFR!

**Pull request merged**
