### PR TITLE
roachtest: port follower-reads/mixed-version/single-region to new framework

### LINKED ISSUE #115133: roachtest: port follower-reads/mixed-version/single-region to the new mixed-version framework
See the parent issue [1] for details.

[1] https://github.com/cockroachdb/cockroach/issues/110528

Jira issue: CRDB-33903

### PR DESCRIPTION
**Pull request by nvb**
Fixes #115133.

This commit ports the `follower-reads/mixed-version/single-region` roachtest to the new mixed-version framework, as described in #110528.

One note for reviewers is that the new mixed-version framework requires clusters to have 4 nodes (unless we want to disable fixtures), so part of the work here was to adapt the test to work with 4 nodes. That's worthwhile anyway, because testing the case where a gateway has no replica (leaseholder or follower) for the table is interesting.

Release note: None

### CODE REVIEW

**Review by srosenberg — COMMENTED** [review]
> new mixed-version framework requires clusters to have 4 nodes (unless we want to disable fixtures)

I thought any subset of the fixtures is usable; i.e., `InstallFixtures` should work for `1<= |node| <= 4`, no?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115317#-:-NkcDzbF5Yd4duUqLMNu:bsknpk8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @kvoli, @nvanbenschoten, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/follower_reads.go` line 899 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115317#-NkcEgUk-5J6oQ1DP4P-:-NkcEgUk-5J6oQ1DP4P0:btrx2wy) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7312a5fe4423683816648517806e98805d60333/pkg/cmd/roachtest/tests/follower_reads.go#L899)):*
> ```Go
> 		// well with secure clusters. As of the time of writing, they return
> 		// either of the following errors:
> 		//  tls: failed to verify certificate: x509: “node” certificate is not standards compliant
> ```

@renatolabs Do we have a fix for this? Perhaps, something like,

```go
tls.Config{InsecureSkipVerify: true}
```

since generating client certs signed by known authority sounds like more work.

**Review by srosenberg — COMMENTED** [review]
> I thought any subset of the fixtures is usable; i.e., `InstallFixtures` should work for `1<= |node| <= 4`, no?

Answering my own question, unfortunately the answer is "no". The fixtures contain the gossiped metadata which refers to `n4`. Thus, while it's in theory possible to bootstrap 3-node clusters, upgrade and other things may fail until the reference to `n4` is removed. We could attempt to remove it via,

```
s.db.PutInline(ctx, keys.NodeStatusKey(nodeID), nil)
```

as is done in the node decommissioning logic, but it seems like a can of worms. I suppose sticking with 4-nodes in this case is _not_ a deficiency. For future use-cases, we could also generate fixtures for 3-nodes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115317#-:-Nkl_Eu_CVfPU-OmP_2d:b-hswbp9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @kvoli, @nvanbenschoten, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/follower_reads.go` line 899 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115317#-NkcEgUk-5J6oQ1DP4P-:-NklZ8p5ELgLkIUkhjpd:be5l9x3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7312a5fe4423683816648517806e98805d60333/pkg/cmd/roachtest/tests/follower_reads.go#L899)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

@renatolabs Do we have a fix for this? Perhaps, something like,

```go
tls.Config{InsecureSkipVerify: true}
```

since generating client certs signed by known authority sounds like more work.
</blockquote></details>

Unfortunately, it goes much deeper than that. `getFollowerReadCounts` (uses `$adminURL/_status/vars`) doesn't actually require authentication, which seem a bit surprising... I guess we allow metrics to be read by the whole internet?! However, `verifySQLLatency` (uses `$adminURL/ts/query`) requires password-based authentication. We currently don't have a nice programmatic API for doing that. I've documented the findings [1].

[1] https://github.com/cockroachdb/cockroach/issues/63145#issuecomment-1837591351

**Review by kvoli — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115317)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @nvanbenschoten, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/follower_reads.go` line 741 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115317#-Nkpyv_E1pWCszDPyG-i:-Nkpyv_E1pWCszDPyG-j:b-mf3589) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7312a5fe4423683816648517806e98805d60333/pkg/cmd/roachtest/tests/follower_reads.go#L741)):*
> ```Go
> 
> 	var response tspb.TimeSeriesQueryResponse
> 	if err := httputil.PostProtobuf(ctx, http.Client{}, url, &request, &response); err != nil {
> ```

This may begin failing when querying v22.2 versions or earlier from https://github.com/cockroachdb/cockroach/pull/98077:

```
                                           n1          n2          n3
#released versions           v22.1.7    v22.1.7     v22.1.7
#logical binary versions      22.1        22.1        22.1
#cluster versions                 22.1        22.1        22.1
# Querying n1 here
....
400 Bad Request, content-type: application/json, body: {
  "error": "unknown field \"tenantId\" in tspb.Query",
  "code": 3,
  "message": "unknown field \"tenantId\" in tspb.Query",
  "details": [
  ]
}
```

A workaround is limiting the max upgrades, to prevent the cluster version from starting pre-22.2. 

```
mixedversion.MaxUpgrades(1)
```

**Review by kvoli — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115317#-:-Nkqctq_CnI8T4NWE3wK:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @nvanbenschoten, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/follower_reads.go` line 741 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115317#-Nkpyv_E1pWCszDPyG-i:-NkqLnH56rvAYDdSuA7Z:b-dmi3tz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7312a5fe4423683816648517806e98805d60333/pkg/cmd/roachtest/tests/follower_reads.go#L741)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

This may begin failing when querying v22.2 versions or earlier from https://github.com/cockroachdb/cockroach/pull/98077:

```
                                           n1          n2          n3
#released versions           v22.1.7    v22.1.7     v22.1.7
#logical binary versions      22.1        22.1        22.1
#cluster versions                 22.1        22.1        22.1
# Querying n1 here
....
400 Bad Request, content-type: application/json, body: {
  "error": "unknown field \"tenantId\" in tspb.Query",
  "code": 3,
  "message": "unknown field \"tenantId\" in tspb.Query",
  "details": [
  ]
}
```

A workaround is limiting the max upgrades, to prevent the cluster version from starting pre-22.2. 

```
mixedversion.MaxUpgrades(1)
```
</blockquote></details>

This is only an issue with the JSON http method used by `roachtests/tests/ts_utils.go`, ignore the above suggestion.

**Review by nvb — COMMENTED** [review]
> Answering my own question, unfortunately the answer is "no".

Thanks for looking into this. Sticking with 4-nodes is actually a nice improvement to test coverage, so I'll keep it here. For other tests which are more sensitive to the node count, I imagine we will be more motivated to generate fixtures for 3-nodes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115317#-:-Nkw5ROX6_obu1CGceC6:b-h1dpht)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @kvoli, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/follower_reads.go` line 741 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115317#-Nkpyv_E1pWCszDPyG-i:-Nkw5mwX-HY5Ah-95trt:b-qki77q) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7312a5fe4423683816648517806e98805d60333/pkg/cmd/roachtest/tests/follower_reads.go#L741)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

This is only an issue with the JSON http method used by `roachtests/tests/ts_utils.go`, ignore the above suggestion.
</blockquote></details>

This test does use `httputil.PostJSON` up above in `verifySQLLatency`. I'll switch that to `PostProtobuf` like you're doing in https://github.com/cockroachdb/cockroach/pull/115559.

I'm not sure why I didn't run into issues while stressing.

**Review by renatolabs — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115317#-:-NkwwQ5SDQSW3_HaSwpn:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @DarrylWong, @kvoli, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/follower_reads.go` line 741 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115317#-Nkpyv_E1pWCszDPyG-i:-Nkwu1aM-az4F1FwlLHH:b7uad5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7312a5fe4423683816648517806e98805d60333/pkg/cmd/roachtest/tests/follower_reads.go#L741)):*
> I'm not sure why I didn't run into issues while stressing.

I believe that's because `verifySQLLatency` is only called in multi-region mode, which is not used in the mixed-version test.
___
*[`pkg/cmd/roachtest/tests/follower_reads.go` line 899 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115317#-NkcEgUk-5J6oQ1DP4P-:-NkwsNQo4J8dFC00gG5V:bhnxkir) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7312a5fe4423683816648517806e98805d60333/pkg/cmd/roachtest/tests/follower_reads.go#L899)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Unfortunately, it goes much deeper than that. `getFollowerReadCounts` (uses `$adminURL/_status/vars) doesn't actually require authentication, which seem a bit surprising... I guess we allow metrics to be read by the whole internet?! However, `verifySQLLatency` (uses `$adminURL/ts/query`) requires password-based authentication. We currently don't have a nice programmatic API for doing that. I've documented the findings [1].

[1] https://github.com/cockroachdb/cockroach/issues/63145#issuecomment-1837591351
</blockquote></details>

FWIW, we have some prior art in calling HTTP endpoints in secure roachtests in [1]. Not a big deal in this case, at least for now. We should package this functionality in a more consumable way and at that point we can come back and update this test.

[1] https://github.com/cockroachdb/cockroach/blob/release-23.1/pkg/cmd/roachtest/tests/mixed_version_tenant_span_stats.go#L140

**Comment by nvanbenschoten** [comment]
TFTRs!

bors r+

**Comment by nvanbenschoten** [comment]
Fixed unused lint warning for `upgradeNodes`, which was due to skew with 55e2d6f9ef0c27b776bca32822b27c539208252d.

bors r+

**Comment by renatolabs** [comment]
Should we backport this to 23.2 (or even 23.1)?

**Comment by nvanbenschoten** [comment]
Backported to v23.2 and v23.1.

**Pull request merged**
