### PR TITLE
mon: nil BoundAccount acts as an unlimited account

### PR DESCRIPTION
**Pull request by sumeerbhola**
Release note: None

### CODE REVIEW

**Comment by sumeerbhola** [comment]
@yuzefovich this is needed for https://github.com/cockroachdb/cockroach/pull/66362#pullrequestreview-707811212

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68340#-:-Mg7EB4T-ws-_my62jTK:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Comment by sumeerbhola** [comment]
TFTR!

**Pull request merged**
