### PR TITLE
kv: added TestMultiRangeBoundedBatchReverseScan

### PR DESCRIPTION
**Pull request by vivekmenezes**
also refactored TestMultiRangeBoundedBatchScan to check
for multiple results that are computed concurrently.
#8245

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8268)

### CODE REVIEW

**Comment by vivekmenezes** [comment]
@bdarnell  any comments on this? Thanks

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[kv/dist_sender_server_test.go, line 121 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8268#-KOQh_kW5HwBlkyx6Gxb:-KOQh_kW5HwBlkyx6Gxc:b40gq0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/41529d1ad50a8142980c674aebe05885570eb12e/kv/dist_sender_server_test.go#L121)):*
> ```Go
> 	}
> 	// The bound was respected.
> 	if count != bound {
> ```

This should probably be `count > bound`. Then you could get rid of the `maxExpCount` stuff below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8268#-:-KOQi8fC855Ff8G3cCmy:bnfp4nl)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[kv/dist_sender_server_test.go, line 121 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8268#-KOQh_kW5HwBlkyx6Gxb:-KOQo5THh9DTOeaw_Zi6:bmnsrzy) ([raw file](https://github.com/cockroachdb/cockroach/blob/41529d1ad50a8142980c674aebe05885570eb12e/kv/dist_sender_server_test.go#L121)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> This should probably be `count > bound`. Then you could get rid of the `maxExpCount` stuff below.
</details>
I'm leaving it as is because I want to check that the count == bound

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8268)*

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[kv/dist_sender_server_test.go, line 121 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8268#-KOQh_kW5HwBlkyx6Gxb:-KOQqb_qT_DRcTYXaG2y:b4wvqa7) ([raw file](https://github.com/cockroachdb/cockroach/blob/41529d1ad50a8142980c674aebe05885570eb12e/kv/dist_sender_server_test.go#L121)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> I'm leaving it as is because I want to check that the count == bound
</details>
Then rename the argument from `bound` to `expCount`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8268)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[kv/dist_sender_server_test.go, line 121 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8268#-KOQh_kW5HwBlkyx6Gxb:-KOROg49ByB7hLuGwc9x:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/41529d1ad50a8142980c674aebe05885570eb12e/kv/dist_sender_server_test.go#L121)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Then rename the argument from `bound` to `expCount`
</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8268)*

**Pull request merged**
