### PR TITLE
roachtest: update version map and test fixtures for 21.2

### PR DESCRIPTION
**Pull request by abarganier**
Release justification: Non-production code change.
Release note: None

### CODE REVIEW

**Review by tbg — COMMENTED** [review]
I think this isn't quite right. You are doing this as part of the 21.2 release, right? Then you are supposed to update the 22.1 key, i.e. point to `21.2.0` instead of `21.2.0-beta.2`. Normally the fixtures also don't have to be mutated once they exist (which they do here) but I remember that they were created under dubious circumstances so please do replace them (this PR currently also updates the wrong fixtures). I'm not sure why a file mode of `+x` was added to them, make sure this doesn't happen when you update the correct fixtures. Also, consider updating the runbook that you're following to clarify which entry to update.
Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72765#-:-MoZw0g4DI7MB96Qfs9f:b-knzaf7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @celiala and @stevendanna)

**Review by abarganier — COMMENTED** [review]
To clarify, this is for the 21.1.12 release. Do these concerns still stand (aside from the `+x` issue, which I'll fix)? Happy to make any necessary changes, thanks for the feedback!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72765#-:-MoZxF4m6JfDNwD0TzBG:b-t1fnd4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @celiala and @stevendanna)

**Comment by tbg** [comment]
For 21.1.12 everything is fine, except you don't need to update the fixtures 👍🏽

**Review by abarganier — COMMENTED** [review]
Appreciate the catch! Removed all the fixtures updates and kept the `predecessor_version.go` change. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72765#-:-Mo_2cxsCD_wYkkEGTIk:b-ljz2gs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @celiala and @stevendanna)

**Review by tbg — APPROVED** [review]
:shipit:

**Pull request merged**
