### PR TITLE
pkg/ts: `can_view_tsdb_metrics` capability aggs system tenant metrics

### LINKED ISSUE #102378: server: tenants should read their own timeseries without capabilities + can_view_tsdb_metrics capability should control access to storage-level metrics
**Is your feature request related to a problem? Please describe.**

In the first implementation of the `can_view_tsdb_metrics`, the following behavior was implemented:

- by default, a secondary tenant cannot read timeseries at all.
- if they are granted the `can_view_tsdb_metrics` capability, they become able to read their _own_ timeseries.

This is overly restrictive.

**Describe the solution you'd like**

- make tenants able to observe their own timeseries without a capability
- make the new capability control access to system-wide metrics by a tenant (but not that of other tenants)

Also as a result we will probably want to _rename_ that capability to `can_view_storage_metrics`.

**Additional context**

* Related comment: https://github.com/cockroachdb/cockroach/pull/86524#issuecomment-1523734065

Jira issue: CRDB-27417
Epic CRDB-34076

### PR DESCRIPTION
**Pull request by abarganier**
Previously, we had the `can_view_tsdb_metrics` tenant capability determine whether secondary tenants had the ability to query TSDB in any capacity. By default, secondary tenants did not have this capability and therefore did not have access to tsdb metrics.

Given feedback, we want to make the following changes:

1. By default, *all* secondary tenants have the ability to query TSDB for *their own* metrics. This ability should not be tied to the `can_view_tsdb_metrics` capability.
2. If a secondary tenant has the `can_view_tsdb_metrics` capability enabled, TSDB should include both tenant-level metrics *and* system tenant level metrics. Results across both tenants for the same metric will be aggregated.

This patch implements the above default behavior. The tenant authorizer step will now indicate on the request object whether the tenant has the appropriate capability. Having the capability then alters the query strategy of TSDB, which will include & aggregate the system tenant metrics into the tenant-level metrics for the secondary tenant.

Tenants without the capability will be able to query TSDB for only their own metrics.

Fixes: https://github.com/cockroachdb/cockroach/issues/102378

Release note (general change): Previously, the `can_view_tsdb_metrics` tenant capability determined whether secondary tenants had the ability to query TSDB in any capacity for their own tenant-level metrics. By default, secondary tenants did not have this capability and therefore did not have access to tsdb metrics.

This patch updates the meaning of the capability, as well as the default behavior, as follows:

1. By default, *all* secondary tenants have the ability to query TSDB for *their own* metrics. This ability should not be tied to the `can_view_tsdb_metrics` capability.
2. If a secondary tenant has the `can_view_tsdb_metrics` capability enabled, TSDB should include both tenant-level metrics *and* system tenant level metrics. Results across both tenants for the same metric will be aggregated.

### CODE REVIEW

**Review by dhartunian — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102703)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @abarganier, and @knz)

___
*[`pkg/rpc/auth_tenant.go` line 413 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102703#-NUhO63MEXdwL1ecQM1h:-NUhO63MEXdwL1ecQM1i:bxgqz2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/b93a30cdce27febdaf6765002138c2e295701d5a/pkg/rpc/auth_tenant.go#L413)):*
> ```Go
> 		}
> 	}
> 	request.TenantCanViewSystem = hasTSDBCapability
> ```

Why not inspect the queries and gate the request here? Would be nice for `tsdb` to not know anything about capabilities or do "auth" logic inside. 
___
*[`pkg/ts/query.go` line 563 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102703#-NUhOHb3BV7ETIgtQRRH:-NUhOHb3BV7ETIgtQRRI:b8yg0s7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b93a30cdce27febdaf6765002138c2e295701d5a/pkg/ts/query.go#L563)):*
> ```Go
> 	dest *[]tspb.TimeSeriesDatapoint,
> 	sourceSet map[string]struct{},
> 	opts QueryOpts,
> ```

As mentioned above I'd like to avoid this opts struct.
___
*[`pkg/ts/query.go` line 943 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102703#-NUhOPNeBQNc7f7FYL4Y:-NUhOPNeBQNc7f7FYL4Z:b-lhua2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/b93a30cdce27febdaf6765002138c2e295701d5a/pkg/ts/query.go#L943)):*
> ```Go
> 		if tenantSource == query.TenantID.String() {
> 			rows = append(rows, row)
> 		} else if opts.tenantCanViewSystem && tenantSource == tsutil.SystemTenantIDSource {
> ```

as I said above, you should just do this in the authorizer and reject the payload if it contains system sources without the capability.

**Review by knz — COMMENTED** [review]
> Reviewed 6 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102703)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi and @abarganier)

___
*[`-- commits` line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102703#-NVFmhyV2QgHBx0ZQAFD):*
As discussed, we need to refine this to only include the storage-level metrics, not the other SQL-level metrics from the system tenant.
I'll re-review after this change.
___
*[`-- commits` line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102703#-NVFmp7eA5_ULHMf2fkS):*
Have we started documenting capabilities and tenant management as user-facing? (I don't remember we did). If not, the release note is not necessary nor desirable.

**Review by yuzefovich — COMMENTED** [review]
Thanks Alex for working on this! I'll take this over the finish line.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102703#-:-N_CB6P347pKh6gcNh6_:b-lx43zv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @abarganier, @dhartunian, and @knz)

___
*[`-- commits` line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102703#-NVFmhyV2QgHBx0ZQAFD):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

As discussed, we need to refine this to only include the storage-level metrics, not the other SQL-level metrics from the system tenant.
I'll re-review after this change.
</blockquote></details>

I looked around the code for a bit to understand how to distinguish storage-level metrics from others. IIUC we need to make the determination based `tsdb.Query.Name`, but I don't see how we'd do that - it seems like we have a couple of pre-defined prefixes (`nodeTimeSeriesPrefix` and `storeTimeSeriesPrefix`), and they don't uniquely distinguish between storage- and SQL-level metrics. Do we need to create such a registry? Do we need to refactor how each metric is defined to indicate whether it's storage- or SQL-level metric?
___
*[`-- commits` line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102703#-NVFmp7eA5_ULHMf2fkS):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Have we started documenting capabilities and tenant management as user-facing? (I don't remember we did). If not, the release note is not necessary nor desirable.
</blockquote></details>

I agree - it seems like there should be no release note.
___
*[`pkg/rpc/auth_tenant.go` line 413 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102703#-NUhO63MEXdwL1ecQM1h:-N_CAgRg63Y-9SisEChe:bmft7ez) ([raw file](https://github.com/cockroachdb/cockroach/blob/b93a30cdce27febdaf6765002138c2e295701d5a/pkg/rpc/auth_tenant.go#L413)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Why not inspect the queries and gate the request here? Would be nice for `tsdb` to not know anything about capabilities or do "auth" logic inside. 
</blockquote></details>

Do I understand your suggestion correctly: inside of `authTSDBQuery` method, if we see that the tenant has - now named -`can_view_storage_metrics` capability and `query.Name` is the storage-level metric, then we'd include both the tenant itself as well as the system tenant into `Sources`. Then, in `ts/query.go` we won't have to do any auth checking. Does this sound right?

**Comment by abarganier** [comment]
Closing, as this approach is quite stale and even when it was fresh, it wasn't the correct approach.

Refer to https://github.com/cockroachdb/cockroach/issues/102378 for future progress.

**Pull request closed without merging**
