### PR TITLE
sql: deflake TestDropTableDeleteData

### LINKED ISSUE #111723: sql: flake in TestDropTableDeleteData
Seen on unrelated change under race [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=12040252&buildTypeId=Cockroach_BazelExtendedCi):
```
Failed
=== RUN   TestDropTableDeleteData
    test_log_scope.go:170: test logs captured to: /artifacts/tmp/_tmp/b287de7194e17a0386ee1775f0d198ba/logTestDropTableDeleteData2309674462
    test_log_scope.go:81: use -show-logs to present logs inline
    drop_test.go:724: descriptor exists = true
    panic.go:540: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/b287de7194e17a0386ee1775f0d198ba/logTestDropTableDeleteData2309674462
--- FAIL: TestDropTableDeleteData (143.66s)
```

Jira issue: CRDB-32046

### PR DESCRIPTION
**Pull request by rafiss**
This blocks the GC job from running while we assert that the descriptor was not yet deleted.

fixes https://github.com/cockroachdb/cockroach/issues/111723
Release note: None

### CODE REVIEW

**Review by annrpom — COMMENTED** [review]
noob q: could we also change the following cluster setting `sql.gc_job.wait_for_gc.interval` to be longer? i think one disadvantage of this is that if we play it safe and go for an even longer interval, this will increase the time that the test takes (is that why we don't change the following cluster setting, assuming i am getting the implications of the name correct)

**Comment by rafiss** [comment]
> could we also change the following cluster setting sql.gc_job.wait_for_gc.interval to be longer? 

we could - but relying on that alone to be sure that the GC occurs later is very likely to lead to flakes. in general, no test should ever be written based on an assumption that something will happen X seconds later. the various operations that occur during those X seconds have no timing guarantees of their own, so they could end up taking longer, so the assertion could still fail. if a strict ordering between concurrent operations is needed, then the only non-flaky way to do that is to have the concurrent goroutines communicate with each other. in this PR, we use a channel to do that communication.

> i think one disadvantage of this is that if we play it safe and go for an even longer interval, this will increase the time that the test takes

this is also true. using a channel avoids the need to sleep for longer than we need. but reducing the time the test needs is a seconday benefit compared to the flakiness point above.

**Review by annrpom — APPROVED** [review]
slay - thanks for the explanation! lgtm

**Comment by rafiss** [comment]
tftr!

bors r+

**Pull request merged**
