### PR TITLE
ui: Preserve search/sorting on Statements page

### LINKED ISSUE #45404: ui: persist searches and sorts on statement list page
Sorting order and searches are not preserved on statements list page when navigating to statement details and back.

To reproduce:
1. Start on the statements list page with some statements showing in the table
2. Sort the table using a column other than the default "Time" / Type into the search box an hit enter
3. Click into a specific statement
4. Go back to the statement list page by clicking the breadcrumb or clicking your browser back button
5. Sort order or search/filter is lost, showing all of the statements

cc @Annebirzin

### PR DESCRIPTION
**Pull request by koorosh**
Resolves: #45404

Search query and sorting params are preserved as URL search
params. It doesn't break existing routing configuration and
allows restore custom state from URL.

Release justification: bug fixes and low-risk updates to new functionality

### CODE REVIEW

**Review by dhartunian — CHANGES_REQUESTED** [review]
When I select a different app in the dropdown, it clears the search query param. I assume we'd want to preserve it in that case. Can you take a look at that @koorosh?

> Reviewed 1 of 1 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45649#-:-M2t8eAIBIkY6VKWQ4wc:b1rky0d)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by koorosh** [comment]
> Can you take a look at that

@dhartunian , thanks for pointing on this.
Described issue and one more missed place (when search statement filter is cleared) are fixed.

**Review by dhartunian — CHANGES_REQUESTED** [review]
Discussed this in-person. @koorosh will be following up either either extracting a sync-query-params function to centralize the logic and/or add some tests to verify that the behavior here is consistent.

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45649#-:-M3DXhOq6lkqENSNuGl0:b7r2f7g)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by koorosh** [comment]
> Discussed this in-person. @koorosh will be following up either either extracting a sync-query-params function to centralize the logic and/or add some tests to verify that the behavior here is consistent.
> 
> > Reviewed 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45649#-:-M3DXhOq6lkqENSNuGl0:b7r2f7g)_ status: :shipit: complete! 0 of 0 LGTMs obtained

Done, the logic related to retrieving/updating history params is refactored to separated methods.
Regarding tests, I'd like to work on tests as separate task, because current testing env doesn't allow
to write tests for interaction components with history and might take some time.

**Review by dhartunian — APPROVED** [review]
@koorosh really like how this reads now. Thanks for making these changes.

A few linting issues:

```
[11:47:18][Test web UI] START:
[11:47:25][Test web UI] 
[11:47:25][Test web UI] ERROR: /go/src/github.com/cockroachdb/cockroach/pkg/ui/src/views/statements/statementsPage.tsx:106:6 - Missing semicolon
[11:47:25][Test web UI] ERROR: /go/src/github.com/cockroachdb/cockroach/pkg/ui/src/views/statements/statementsPage.tsx:118:7 - misplaced 'else'
```

> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45649#-:-M3S4diqCpkNSxfrZZe5:b-k0va7e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

**Comment by koorosh** [comment]
> @koorosh really like how this reads now. Thanks for making these changes.
> 
> A few linting issues:
> 
> ```
> [11:47:18][Test web UI] START:
> [11:47:25][Test web UI] 
> [11:47:25][Test web UI] ERROR: /go/src/github.com/cockroachdb/cockroach/pkg/ui/src/views/statements/statementsPage.tsx:106:6 - Missing semicolon
> [11:47:25][Test web UI] ERROR: /go/src/github.com/cockroachdb/cockroach/pkg/ui/src/views/statements/statementsPage.tsx:118:7 - misplaced 'else'
> ```
> 
> > Reviewed 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45649#-:-M3S4diqCpkNSxfrZZe5:b-k0va7e)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

Done!

**Review by dhartunian — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45649#-:-M3fnEzr19gazA-JFJZH:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian)

**Pull request merged**
