### PR TITLE
sqlccl: flesh out IMPORT syntax, swap default impl to old version

### PR DESCRIPTION
**Pull request by dt**
This fleshes out the SQL syntax for CSV bulk loading based on our discusions,
closely following a syntax devised in collaboration with Sean.

It also changes the default implementation of the hook to call the previous
implementation of LoadCSV, which is executed locally rather than via distsql.

This still just does the transform, not the ingest though -- a followup will
do that, but I wanted to checkpoint early since we have multiple authors
working on the same code here.

### CODE REVIEW

**Comment by knz** [comment]
"a syntax devised in collaboration with Sean" - any notes from that discussion?
I have several suggestions to improve the specific syntactic elements used here. I will not let these suggestions get in the way of this PR, however if this merges as-is please expect a follow-up discussion -- we may need some polishing before 1.1 is released.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17496#-:-KqydMC53LqDHiDpnD37:b1iyuvh)*

**Comment by danhhz** [comment]
:lgtm: modulo getting everyone onboard with the syntax

might be worth doing a quick `git grep -i load pkg` to see if any other LOAD references were missed

---

Review status: 0 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/ccl/sqlccl/csv.go, line 615 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17496#-KqyeyiIWAPfeE4SsSCQ:-KqyeyiIWAPfeE4SsSCR:bu1wdey) ([raw file](https://github.com/cockroachdb/cockroach/blob/34fcaf5f644a13baad6231dff729e07e0019c976/pkg/ccl/sqlccl/csv.go#L615)):*
> ```Go
> 		return nil, nil, nil
> 	}
> 	// No enterprise check here: LOAD is always available.
> ```

IMPORT

---

*[pkg/ccl/sqlccl/csv.go, line 664 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17496#-KqyfY5pwrI1B3eiIEHq:-KqyfY5pwrI1B3eiIEHr:b-79d7s0) ([raw file](https://github.com/cockroachdb/cockroach/blob/34fcaf5f644a13baad6231dff729e07e0019c976/pkg/ccl/sqlccl/csv.go#L664)):*
> ```Go
> 
> 		comma := ','
> 		if commaOverride, ok := importStmt.Options.Get("comma"); ok {
> ```

i think we were asked to keep all these constants (the keys in options) together. they're currently in restore.go, search for restoreOptIntoDB

---

*[pkg/ccl/sqlccl/csv.go, line 671 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17496#-KqyfOaW-PsDgMAALgMf:-KqyfOaW-PsDgMAALgMg:bof4vih) ([raw file](https://github.com/cockroachdb/cockroach/blob/34fcaf5f644a13baad6231dff729e07e0019c976/pkg/ccl/sqlccl/csv.go#L671)):*
> ```Go
> 		}
> 
> 		comment := ','
> ```

this should probably be the 0 value (which indicates no comment to the csv library) by default

---

*[pkg/ccl/sqlccl/csv.go, line 684 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17496#-KqygHH-e_cHJ8zZzk0R:-KqygHH-e_cHJ8zZzk0S:b30kfhm) ([raw file](https://github.com/cockroachdb/cockroach/blob/34fcaf5f644a13baad6231dff729e07e0019c976/pkg/ccl/sqlccl/csv.go#L684)):*
> ```Go
> 		}
> 
> 		sstMaxSize := int64(1024 * 1024 * 50)
> ```

`config.DefaultZoneConfig().RangeMaxBytes / 2`

---

*[pkg/ccl/sqlccl/csv.go, line 763 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17496#-KqygbLMJP1uqWrRA2cS:-KqygbLMJP1uqWrRA2cT:b-3m3x1i) ([raw file](https://github.com/cockroachdb/cockroach/blob/34fcaf5f644a13baad6231dff729e07e0019c976/pkg/ccl/sqlccl/csv.go#L763)):*
> ```Go
> 			}
> 		} else {
> 			_, _, total, err = doLocalCSVTransform(ctx, parentID, tableDesc, temp, files,
> ```

wrapping on this is weird. i think we usually do

```
_, _, total, err = doLocalCSVTransform(
    ctx, parentID, tableDesc, temp, files, comma, comment,
    nullif, sstMaxSize
)
```

---

*[pkg/sql/parser/import.go, line 19 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17496#-Kqyddt-p7pupcF-XpGK:-Kqyddt-p7pupcF-XpGL:bu1wdey) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bc712c6cf6befb2c81a4db0cf34cbd9b68189cb/pkg/sql/parser/import.go#L19)):*
> ```Go
> import "bytes"
> 
> // Import represents a BACKUP statement.
> ```

IMPORT

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17496#-:-KqygzkYobXVXo4-eniq:b-cswqtj)*

**Comment by mjibson** [comment]
Review status: 0 of 9 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/sqlccl/csv.go, line 153 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17496#-Kr-NcI0C_kpmnblNNOb:-Kr-NcI0C_kpmnblNNOc:b-eep4ef) ([raw file](https://github.com/cockroachdb/cockroach/blob/34fcaf5f644a13baad6231dff729e07e0019c976/pkg/ccl/sqlccl/csv.go#L153)):*
> ```Go
> 	if err != nil {
> 		return nil, err
> 	}
> ```

defer store.Close()

---

*[pkg/ccl/sqlccl/csv.go, line 176 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17496#-Kr-M1NVqO9ul5Yo6fkm:-Kr-M1NVqO9ul5Yo6fkn:bfhxzqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/34fcaf5f644a13baad6231dff729e07e0019c976/pkg/ccl/sqlccl/csv.go#L176)):*
> ```Go
> // parseCSVTableDescriptor creates a table descriptor from a string and
> // checks it for features not supported during CSV loading.
> func parseCSVTableDescriptor(
> ```

Do we need both this and readCreateTableFromStore? Seems like we should just have one.

---

*[pkg/ccl/sqlccl/csv.go, line 665 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17496#-Kr-O4uElu521UCT3hMB:-Kr-O4uElu521UCT3hMC:b-ygb2fe) ([raw file](https://github.com/cockroachdb/cockroach/blob/34fcaf5f644a13baad6231dff729e07e0019c976/pkg/ccl/sqlccl/csv.go#L665)):*
> ```Go
> 		comma := ','
> 		if commaOverride, ok := importStmt.Options.Get("comma"); ok {
> 			if len(commaOverride) > 1 {
> ```

This doesn't correctly fetch the first rune out of the string since runes can be up to 4 bytes long. I guess it's probably ok because the parser will guarantee that the string is valid utf8, and thus will fail if it's like a 1 byte value that's > 127 or something. But still, I think we should correctly extract the first rune, and also allow any valid rune instead of just a single ascii char.  There's an implementation that does exactly this when fetching these settings from the CLI at https://github.com/cockroachdb/cockroach/blob/63ff64e676a905efed9551084326d69f4fe9e457/pkg/ccl/cliccl/load.go#L92. We should probably export that function or copy it, whichever. Thinking about this more broadly it'd kinda be cool if the CLI and the SQL statement could use the same argument verification code.

---

*[pkg/ccl/sqlccl/csv.go, line 671 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17496#-KqyfOaW-PsDgMAALgMf:-Kr-OglJQBakfh3MoxtA:bb77ufg) ([raw file](https://github.com/cockroachdb/cockroach/blob/34fcaf5f644a13baad6231dff729e07e0019c976/pkg/ccl/sqlccl/csv.go#L671)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

this should probably be the 0 value (which indicates no comment to the csv library) by default
</blockquote></details>

Yes.

---

*[pkg/ccl/sqlccl/csv.go, line 685 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17496#-Kr-PXeeh2Slfv-DIYsu:-Kr-PXeeh2Slfv-DIYsv:b-xrpo2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/34fcaf5f644a13baad6231dff729e07e0019c976/pkg/ccl/sqlccl/csv.go#L685)):*
> ```Go
> 
> 		sstMaxSize := int64(1024 * 1024 * 50)
> 		if override, ok := importStmt.Options.Get("sstmaxsize"); ok {
> ```

Calling this sstmaxsize might not be a good choice since SSTs can be larger when using the distributed implementation since it has to guess about the split points. I'm not opposed to `sstsize`.

---

*[pkg/ccl/sqlccl/csv_test.go, line 397 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17496#-Kr-R-x-XERC6zynEa1Z:-Kr-R-x-XERC6zynEa1_:bkp30do) ([raw file](https://github.com/cockroachdb/cockroach/blob/34fcaf5f644a13baad6231dff729e07e0019c976/pkg/ccl/sqlccl/csv_test.go#L397)):*
> ```Go
> 		).Scan(&result)
> 
> 		if expected := 1; result < expected {
> ```

These tests are largely the same except for the invocation string. Could we change them to use the same init and expected check block to make changing the interface easier? Currently it just returns the number of ssts created, but that will likely change, and it'd be nice to only fix the test in one place.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17496)*

**Comment by mjibson** [comment]
Review status: 0 of 11 files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/sqlccl/csv_test.go, line 397 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17496#-Kr-R-x-XERC6zynEa1Z:-Kr1znjL8UQV0OHi598h:b6ovop6) ([raw file](https://github.com/cockroachdb/cockroach/blob/34fcaf5f644a13baad6231dff729e07e0019c976/pkg/ccl/sqlccl/csv_test.go#L397)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

hm, it isn't just the string, since they use a different number of bound args. I'll see if I can do something with ...args though that looks better.
</blockquote></details>

Oh yeah this is much better.

---

*[pkg/util/strings.go, line 24 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17496#-Kr2-4MdVZnt702tbYqr:-Kr2-4MeSGn3rEf_aCHr:bbx2qye) ([raw file](https://github.com/cockroachdb/cockroach/blob/e970045caf86d9a1be6a1e58363b8bc49666e1fa/pkg/util/strings.go#L24)):*
> ```Go
> 
> // GetSingleRune decodes the string s as a single rune if possible.
> func GetSingleRune(s string) (rune, error) {
> ```

The stuff in cliccl should use this instead of its own.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17496)*

**Comment by dt** [comment]
Review status: 0 of 12 files reviewed at latest revision, 12 unresolved discussions.

---

*[pkg/util/strings.go, line 24 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17496#-Kr2-4MdVZnt702tbYqr:-Kr2Hq4bSRe87XE37GBJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e970045caf86d9a1be6a1e58363b8bc49666e1fa/pkg/util/strings.go#L24)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

The stuff in cliccl should use this instead of its own.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17496)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 12 files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17496#-:-Kr2JCCCnVaiI7hMXliI:bnfp4nl)*

**Pull request merged**
