### PR TITLE
sql/parser: Clean up memoized function handling for TypedExprs

### PR DESCRIPTION
**Pull request by nvb**
This change simplifies how memoized functions are handled for `UnaryExprs`, `BinaryExprs`,
`ComparisonExprs`, and `FuncExprs`. We now maintain the memoized function throughout normilization and analysis so that we can make the guarantee that once an expression is type checked, it will always hold onto its function reference.

The change also cleans up some of the aggregate function semantics dealing with constant literal arguments.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6588)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1, 6 of 6 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[sql/parser/builtins.go, line 631 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6588#-KHLykuyBbYNHs4FU8Hw:-KHLykuzsl9U4OGCceYz:369921464) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c0f59ae46776b4c59e8b0773d73eb04f1616def/sql/parser/builtins.go#L631)):*
> ```Go
> 	// literal arguments. If the result of the aggregate function with constant
> 	// arguments is dependent on the number of rows it is run across (eg. SUM(1)),
> 	// it should be marked as impure. If the results of the aggregate function with
> ```

results...is?

---

*[sql/parser/builtins.go, line 1019 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6588#-KHLyaCfQGr-JhuzHnfP:-KHLyaCfQGr-JhuzHnfQ:1331345966) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c0f59ae46776b4c59e8b0773d73eb04f1616def/sql/parser/builtins.go#L1019)):*
> ```Go
> 
> // identityFn returns the first argument provided.
> var identityFn = func(_ EvalContext, args DTuple) (Datum, error) {
> ```

why is this a `var`?

---

*[sql/parser/eval.go, line 1830 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6588#-KHLx0mG_h8gbK-v8FOk:-KHLx0mG_h8gbK-v8FOl:676269983) ([raw file](https://github.com/cockroachdb/cockroach/blob/689c501a0ce4a56eaedf7eeab0799d6327f1e1b1/sql/parser/eval.go#L1830)):*
> ```Go
> 	d, err := expr.Expr.(TypedExpr).Eval(ctx)
> 	if err != nil {
> 		return nil, err
> ```

:+1:

---

*[sql/parser/eval.go, line 1832 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6588#-KHLx7lk1dC-4_fBffCZ:-KHLx7llZEcvKgJKLlzI:1481495856) ([raw file](https://github.com/cockroachdb/cockroach/blob/689c501a0ce4a56eaedf7eeab0799d6327f1e1b1/sql/parser/eval.go#L1832)):*
> ```Go
> 		return nil, err
> 	}
> 	if d == DNull {
> ```

how come this is correct?

---

*[sql/parser/normalize.go, line 506 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6588#-KHLyI2p3-QvFf5eIdgl:-KHLyI2p3-QvFf5eIdgm:655979593) ([raw file](https://github.com/cockroachdb/cockroach/blob/689c501a0ce4a56eaedf7eeab0799d6327f1e1b1/sql/parser/normalize.go#L506)):*
> ```Go
> // stripMemoizedFuncs strips memoized function references from expression trees.
> // This is necessary to permit equality checks using reflect.DeepEqual.
> func stripMemoizedFuncs(expr Expr) Expr {
> ```

used only in tests, yes? should be in a _test.go file.

---

*[sql/parser/type_check.go, line 418 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6588#-KHLxEgzUAITuuhMo3Rm:-KHLxEgzUAITuuhMo3Rn:-1514523824) ([raw file](https://github.com/cockroachdb/cockroach/blob/689c501a0ce4a56eaedf7eeab0799d6327f1e1b1/sql/parser/type_check.go#L418)):*
> ```Go
> }
> 
> // qualifiedNameTypes is a mapping of QualifiedNames to types that can be mocked out
> ```

s/QualifiedNames/qualified names/

You're implying a type here but these are just strings.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6588)*

**Comment by nvanbenschoten** [comment]
Review status: 3 of 8 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[sql/parser/builtins.go, line 631 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6588#-KHLykuyBbYNHs4FU8Hw:-KHM5iEFJTsIe7cRLf2n:676759881) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c0f59ae46776b4c59e8b0773d73eb04f1616def/sql/parser/builtins.go#L631)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> results...is?</details>
Huh?

---

*[sql/parser/builtins.go, line 1019 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6588#-KHLyaCfQGr-JhuzHnfP:-KHM6-CHEmzoREW8BL7f:-680264147) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c0f59ae46776b4c59e8b0773d73eb04f1616def/sql/parser/builtins.go#L1019)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> why is this a `var`?</details>
No good reason. Done.

---

*[sql/parser/eval.go, line 1832 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6588#-KHLx7lk1dC-4_fBffCZ:-KHM6Sbyn6eS25JuhZB1:1611902226) ([raw file](https://github.com/cockroachdb/cockroach/blob/689c501a0ce4a56eaedf7eeab0799d6327f1e1b1/sql/parser/eval.go#L1832)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> how come this is correct?</details>
It used to be [like this](https://github.com/cockroachdb/cockroach/blob/3729719a0410aac354de20e423f3fdc39dfc0ee9/sql/parser/eval.go#L1495) but I temporarily removed it when refactoring.

---

*[sql/parser/normalize.go, line 506 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6588#-KHLyI2p3-QvFf5eIdgl:-KHM7DfT9eME7cYHygNP:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/689c501a0ce4a56eaedf7eeab0799d6327f1e1b1/sql/parser/normalize.go#L506)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> used only in tests, yes? should be in a _test.go file.</details>
Done.

---

*[sql/parser/type_check.go, line 418 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6588#-KHLxEgzUAITuuhMo3Rm:-KHM7Mwfjx3lDx_CQ77q:926693478) ([raw file](https://github.com/cockroachdb/cockroach/blob/689c501a0ce4a56eaedf7eeab0799d6327f1e1b1/sql/parser/type_check.go#L418)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> s/QualifiedNames/qualified names/
> 
> You're implying a type here but these are just strings.</details>
Good point, done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6588)*

**Comment by tamird** [comment]
Reviewed 5 of 5 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/parser/builtins.go, line 631 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6588#-KHLykuyBbYNHs4FU8Hw:-KHMBggWvFD1j630NKVw:1310353722) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c0f59ae46776b4c59e8b0773d73eb04f1616def/sql/parser/builtins.go#L631)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Huh?</details>
you are mixing plural and singular.

---

*[sql/parser/eval.go, line 1832 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6588#-KHLx7lk1dC-4_fBffCZ:-KHMBzXTlwkrl9UNUfz0:-632829233) ([raw file](https://github.com/cockroachdb/cockroach/blob/689c501a0ce4a56eaedf7eeab0799d6327f1e1b1/sql/parser/eval.go#L1832)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> It used to be [like this](https://github.com/cockroachdb/cockroach/blob/3729719a0410aac354de20e423f3fdc39dfc0ee9/sql/parser/eval.go#L1495) but I temporarily removed it when refactoring.</details>
I'm not following. What should I be seeing?j

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6588)*

**Comment by nvanbenschoten** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/parser/builtins.go, line 631 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6588#-KHLykuyBbYNHs4FU8Hw:-KHMCx-2ooBXzfm9ry2_:535545294) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c0f59ae46776b4c59e8b0773d73eb04f1616def/sql/parser/builtins.go#L631)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> you are mixing plural and singular.</details>
Ah yeah, I was reading the sentence above. Done.

---

*[sql/parser/eval.go, line 1832 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6588#-KHLx7lk1dC-4_fBffCZ:-KHMDLSANoiV6iTF1Xuv:1396797989) ([raw file](https://github.com/cockroachdb/cockroach/blob/689c501a0ce4a56eaedf7eeab0799d6327f1e1b1/sql/parser/eval.go#L1832)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I'm not following. What should I be seeing?j</details>
The `expr.dtype != reflect.TypeOf(d)` line, which was an excessive way to perform a NULL check.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6588)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/parser/eval.go, line 1832 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6588#-KHLx7lk1dC-4_fBffCZ:-KHMDmjNxD-vAPQfkC4w:2067063801) ([raw file](https://github.com/cockroachdb/cockroach/blob/689c501a0ce4a56eaedf7eeab0799d6327f1e1b1/sql/parser/eval.go#L1832)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> The `expr.dtype != reflect.TypeOf(d)` line, which was an excessive way to perform a NULL check.</details>
Oh. There used to be a nice descriptive comment here; can you revive it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6588)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/parser/eval.go, line 1832 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6588#-KHLx7lk1dC-4_fBffCZ:-KHMG7k1xp07r1PWoyFv:1988455245) ([raw file](https://github.com/cockroachdb/cockroach/blob/689c501a0ce4a56eaedf7eeab0799d6327f1e1b1/sql/parser/eval.go#L1832)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Oh. There used to be a nice descriptive comment here; can you revive it?</details>
It's not really an accurate statement. If the argument evaluates to the value NULL, the type of the argument **DOES** still match the argument type of the memoized function. However, the NULL value is propagate up so we just evaluate the `UnaryExpr` to NULL as well. I'm planning on making the distinction between the type NULL and the value NULL (with an actual type) much more clear in coming changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6588)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/parser/eval.go, line 1832 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6588#-KHLx7lk1dC-4_fBffCZ:-KHMIQhx7CBNmyLfKsxU:2089253973) ([raw file](https://github.com/cockroachdb/cockroach/blob/689c501a0ce4a56eaedf7eeab0799d6327f1e1b1/sql/parser/eval.go#L1832)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> It's not really an accurate statement. If the argument evaluates to the value NULL, the type of the argument **DOES** still match the argument type of the memoized function. However, the NULL value is propagate up so we just evaluate the `UnaryExpr` to NULL as well. I'm planning on making the distinction between the type NULL and the value NULL (with an actual type) much more clear in coming changes.</details>
okie dokie.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6588)*

**Pull request merged**
