### PR TITLE
ui: use TimeScaleState reducer to align time window across pages

### PR DESCRIPTION
**Pull request by koorosh**
Before, there was `globalTimeScale` local setting that was
used to track time window changes in different places (ie
statements, transactions and metrics pages). But Metrics
page has many components that still rely on logic
implemented in TimeScaleState reducer and `MetricsTimeManager`
component that manages how to update moving time window in
Db Console. As result, two places exist that track time
window changes and they are not synced.
It caused issues related to selecting custom time ranges on
Metrics page.

This change does following:
- remove `globalTimeScale` local setting as a duplicate of
`TimeScaleState` reducer.
- use `TimeScaleState`'s logic to set and get current values
of time window in SQL Activity pages.

Release note: None

On a video below you can see the result where changing time range
in different places updates it across all pages. Also it shows that 
it works if user selects predefined relative time option or selects
custom time range.

https://user-images.githubusercontent.com/3106437/183712012-23d966e9-07d6-4c83-8476-bf1a7ed1c4db.mov

### CODE REVIEW

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85826#-:-N930csD7SSR6-tFY14a:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @koorosh)

**Comment by xinhaoz** [comment]
This PR undoes the proper object construction from local settings that existed in `globalTimeScale.ts`. This means if a user refreshes the page and we construct the timescale from session storage, certain properties of the timescale won't function properly, and the page will actually crash if `fixedWindowEnd` is non-null. I'll reintroduce this construction in another PR that should be backported.

**Comment by maryliag** [comment]
FYI @xinhaoz this PR was followed by this other PR https://github.com/cockroachdb/cockroach/pull/86157 that did some fixes for the reload part

**Pull request merged**
