### PR TITLE
opt: Prune unnecessary columns in UNION ALL operators.

### LINKED ISSUE #34019: opt: Prune unnecessary columns for set operators
I recently encountered a customer query that highlighted a missing optimizer rule. The query performs a COUNT(*) over a UNION, similar to this:
```
SELECT COUNT(*)
FROM
(
  SELECT * FROM abc WHERE b IN [1, 2, 3]
  UNION
  SELECT * FROM xyz WHERE y IN [4, 5, 6]
)
```

The performance did not meet expectations because the tables had a large number of columns, and the columns were all being projected by the UNION operator, even though the COUNT does not need them.

The solution is to add new prune column rules for the set operators, such as `PruneUnionCols`, `PruneIntersectCols`, etc. Like other similar rules, this rule will discard columns that are not needed to compute the result.

### PR DESCRIPTION
**Pull request by savoie**
Fixes #34019 (in that UNION ALL is currently the only set operator that
would support this kind of column pruning, since it preserves duplicate
rows)

In cases where all columns of the output of a UNION ALL are not
required, such as in

```
SELECT a FROM (
  SELECT a,b,c FROM abc
  UNION ALL
  SELECT x,y,z FROM xyz
)
```

it is useful to prune any extraneous columns before performing the
operation (in this case, columns b, c, y, and z are not ever needed,
so they can be pruned).

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: That was fast!

[nit] your commit message has Release note twice

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40891#-:-Lp5MOec5MQIlbVOnsSg:b1noloz)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @savoie)

___
*[pkg/sql/opt/norm/custom_funcs.go, line 1175 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40891#-Lp5MtSh1V6V0WTJcNdy:-Lp5MtSh1V6V0WTJcNdz:bnan9h1) ([raw file](https://github.com/cockroachdb/cockroach/blob/212afbca58e17c4cafdcecb4ed42f1cb702b8d6c/pkg/sql/opt/norm/custom_funcs.go#L1175)):*
> ```Go
> }
> 
> // PruneSetPrivate returns a SetPrivate based on the given SetPrivate, but with unneeded input
> ```

[nit] comments should be limited to 80 columns wide
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40891#-Lp5NQj94aLwnAZnRM2w:-Lp5NQj94aLwnAZnRM2x:b-t96578) ([raw file](https://github.com/cockroachdb/cockroach/blob/212afbca58e17c4cafdcecb4ed42f1cb702b8d6c/pkg/sql/opt/norm/custom_funcs.go#L1178)):*
> ```Go
> // and output columns discarded.
> func (c *CustomFuncs) PruneSetPrivate(needed opt.ColSet, set *memo.SetPrivate) *memo.SetPrivate {
> 	prunedSet := memo.SetPrivate{}
> ```

To reduce allocations below, you could do something like this:
```
length := needed.Len()
prunedSet := memo.SetPrivate{
  LeftCols:  make(opt.ColList, 0, length),
  RightCols: make(opt.ColList, 0, length),
  OutCols:   make(opt.ColList, 0, length),
}
```
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40891#-Lp5P8mX5UhL6YZuglQJ:-Lp5P8mX5UhL6YZuglQK:b-ue1n88) ([raw file](https://github.com/cockroachdb/cockroach/blob/212afbca58e17c4cafdcecb4ed42f1cb702b8d6c/pkg/sql/opt/norm/custom_funcs.go#L1203)):*
> ```Go
> // neededColMapSide implements the logic for NeededColMapLeft and NeededColMapRight.
> func (c *CustomFuncs) neededColMapSide(needed opt.ColSet, toList, fromList opt.ColList) opt.ColSet {
> 	neededFromCols := opt.ColSet{}
> ```

[nit] `var neededFromCols opt.ColSet`

**Comment by knz** [comment]
nit: since this has a user-visible change (some queries will become faster) this deserves a release note.

**Review by RaduBerinde — COMMENTED** [review]
Nice job! :lgtm_strong: (but merging needs to wait until after branching)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40891#-:-Lp8b-f2CjD0q3UyU5_K:b-7ggd6q)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft and @savoie)

**Review by justinj — COMMENTED** [review]
Looks great!

nit: commit message title should be prefixed with `opt:` (I and probably others use this to set up email filters)

@knz: I don't object to a release note but do we really include them for *any performance change*? I'm skeptical that an optimization like this qualifies as a "user visible change".

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40891#-:-Lp8y5_67RM9z9E9FCP_:b-2kkvqm)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft and @savoie)

___
*[pkg/sql/opt/norm/custom_funcs.go, line 1202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40891#-Lp8qaHrDNGiyHMZ1WLu:-Lp8qaHrDNGiyHMZ1WLv:bohj0ao) ([raw file](https://github.com/cockroachdb/cockroach/blob/212afbca58e17c4cafdcecb4ed42f1cb702b8d6c/pkg/sql/opt/norm/custom_funcs.go#L1202)):*
> ```Go
> 
> // neededColMapSide implements the logic for NeededColMapLeft and NeededColMapRight.
> func (c *CustomFuncs) neededColMapSide(needed opt.ColSet, toList, fromList opt.ColList) opt.ColSet {
> ```

nit: maybe we can extract and re-use `translateColSet` for this? depending on how easy that extraction is (from the stats code)
___
*[pkg/sql/opt/norm/rules/prune_cols.opt, line 533 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40891#-Lp8r0Ue3nN_LpOZt_i0:-Lp8r0Uf67aC9_0_hn26:b-cpw9k4) ([raw file](https://github.com/cockroachdb/cockroach/blob/212afbca58e17c4cafdcecb4ed42f1cb702b8d6c/pkg/sql/opt/norm/rules/prune_cols.opt#L533)):*
> ```
>         $left:*
>         $right:*
>         $colmap:*)
> ```

nit: `)` should go on a new line (our parentheses are indeed all lonely)
___
*[pkg/sql/opt/norm/rules/prune_cols.opt, line 545 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40891#-Lp8ret2Ev_YLyEN9NQs:-Lp8ret2Ev_YLyEN9NQt:bxlxdty) ([raw file](https://github.com/cockroachdb/cockroach/blob/212afbca58e17c4cafdcecb4ed42f1cb702b8d6c/pkg/sql/opt/norm/rules/prune_cols.opt#L545)):*
> ```
>             )
>         ) &
>         (CanPruneCols $right $neededRight:(NeededColMapRight $needed $colmap))
> ```

Can this rule result in a case where we prune more columns from one side than the other? Say we can prune one column from the left and two from the right, we should only *actually* prune the intersection of the two sets of prunable columns, I think?
___
*[pkg/sql/opt/norm/testdata/rules/prune_cols, line 2813 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40891#-Lp8u2Ty3kbuHRT6r9QR:-Lp8u2Ty3kbuHRT6r9QS:buzm8b4) ([raw file](https://github.com/cockroachdb/cockroach/blob/212afbca58e17c4cafdcecb4ed42f1cb702b8d6c/pkg/sql/opt/norm/testdata/rules/prune_cols#L2813)):*
> ```
> 
> # --------------------------------------------------
> # PruneUnionAllCols
> ```

I think this could use a couple more tests, what about:
* a test with an extra operator on top, like a join
* a test where we have a different prunable set of columns on the left and the right
___
*[pkg/sql/opt/norm/testdata/rules/prune_cols, line 2834 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40891#-Lp8t3yX3JQeIbkVx4yx:-Lp8t3yX3JQeIbkVx4yy:bqzrsvk) ([raw file](https://github.com/cockroachdb/cockroach/blob/212afbca58e17c4cafdcecb4ed42f1cb702b8d6c/pkg/sql/opt/norm/testdata/rules/prune_cols#L2834)):*
> ```
>       └── key: (6)
> 
> opt expect=PruneUnionAllCols
> ```

hehe, maybe someday we will turn this into:
`=> SELECT (SELECT count(*) FROM abcde) + (SELECT count(*) FROM xy)`
___
*[pkg/sql/opt/xform/testdata/external/hibernate, line 1596 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40891#-Lp8urAS-qljbFfjTe-G:-Lp8urAS-qljbFfjTe-H:bzbv0m5) ([raw file](https://github.com/cockroachdb/cockroach/blob/212afbca58e17c4cafdcecb4ed42f1cb702b8d6c/pkg/sql/opt/xform/testdata/external/hibernate#L1596)):*
> ```
>  │    │    ├── key: (1)
>  │    │    └── fd: (1)-->(2)
>  │    ├── inner-join (hash)
> ```

nice! always like seeing these random tests improve.

**Comment by rytaft** [comment]
___
*[pkg/sql/opt/norm/rules/prune_cols.opt, line 545 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40891#-Lp8ret2Ev_YLyEN9NQs:-Lp9WpkXATwUqSkaZC_C:bpy6th9) ([raw file](https://github.com/cockroachdb/cockroach/blob/212afbca58e17c4cafdcecb4ed42f1cb702b8d6c/pkg/sql/opt/norm/rules/prune_cols.opt#L545)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Can this rule result in a case where we prune more columns from one side than the other? Say we can prune one column from the left and two from the right, we should only *actually* prune the intersection of the two sets of prunable columns, I think?
</blockquote></details>

Good call -- a good test case for this is something like `select a from ((select a, b, c from abc) union (select x, x, y from xy))`

**Comment by savoie** [comment]
> _[pkg/sql/opt/norm/rules/prune_cols.opt, line 545 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40891#-Lp8ret2Ev_YLyEN9NQs:-Lp9WpkXATwUqSkaZC_C:bpy6th9) ([raw file](https://github.com/cockroachdb/cockroach/blob/212afbca58e17c4cafdcecb4ed42f1cb702b8d6c/pkg/sql/opt/norm/rules/prune_cols.opt#L545)):_
> 
> Previously, justinj (Justin Jaffray) wrote…
> Good call -- a good test case for this is something like `select a from ((select a, b, c from abc) union (select x, x, y from xy))`

I think I may not be understanding this case right: I'd expect `select a from ((select a, b, c from abc) union all (select x, x, y from xy))` to be pruned down to `select a from ((select a from abc) union all (select x from xy))` which would be the same number of columns on each side.

**Comment by rytaft** [comment]
___
*[pkg/sql/opt/norm/rules/prune_cols.opt, line 545 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40891#-Lp8ret2Ev_YLyEN9NQs:-Lp9lxQD9ITtFx8j-7yT:b4spoyz) ([raw file](https://github.com/cockroachdb/cockroach/blob/212afbca58e17c4cafdcecb4ed42f1cb702b8d6c/pkg/sql/opt/norm/rules/prune_cols.opt#L545)):*
<details><summary><i>Previously, savoie (Céline O'Neil) wrote…</i></summary><blockquote>

I think I may not be understanding this case right: I'd expect `select a from ((select a, b, c from abc) union all (select x, x, y from xy))` to be pruned down to `select a from ((select a from abc) union all (select x from xy))` which would be the same number of columns on each side. 
</blockquote></details>

Yes, but you're pruning different numbers of columns -- you're pruning b and c from abc, but only y from xy.

**Comment by savoie** [comment]
> _[pkg/sql/opt/norm/rules/prune_cols.opt, line 545 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40891#-Lp8ret2Ev_YLyEN9NQs:-Lp9lxQD9ITtFx8j-7yT:b4spoyz) ([raw file](https://github.com/cockroachdb/cockroach/blob/212afbca58e17c4cafdcecb4ed42f1cb702b8d6c/pkg/sql/opt/norm/rules/prune_cols.opt#L545)):_
> 
> Previously, savoie (Céline O'Neil) wrote…
> Yes, but you're pruning different numbers of columns -- you're pruning b and c from abc, but only y from xy.

Ah I follow, I was thinking entirely in terms of how many to _keep_.

**Comment by knz** [comment]
> I don't object to a release note but do we really include them for any performance change? 

rule number one of nits is that they can be ignored. Release notes are not only warnings of things they should beware; they are also reasons to celebrate. IMHO user-facing change should be _advertised_, if only to have users recognize all the hard work being done, that they directly benefit from.

**Review by rytaft — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40891)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj and @savoie)

___
*[pkg/sql/opt/norm/rules/prune_cols.opt, line 545 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40891#-Lp8ret2Ev_YLyEN9NQs:-LpEB9du4feX5EkQE0G8:b-pcstjq) ([raw file](https://github.com/cockroachdb/cockroach/blob/212afbca58e17c4cafdcecb4ed42f1cb702b8d6c/pkg/sql/opt/norm/rules/prune_cols.opt#L545)):*
<details><summary><i>Previously, savoie (Céline O'Neil) wrote…</i></summary><blockquote>

Ah I follow, I was thinking entirely in terms of how many to _keep_.

@justinj I haven't touched the `translateColSet` stuff but I've added a few tests and better handled the case of unequal column pruning. 
</blockquote></details>

You could also tweak the example to keep different numbers of columns (e.g., `select a, b from ((select a, b, c from abc) union (select x, x, y from xy))`.)

**Comment by savoie** [comment]
@justinj would you mind taking another look at this to be sure I addressed all your comments?

**Review by justinj — COMMENTED** [review]
:lgtm: great job!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40891#-:-LrBDmsj6PTSRCUwpuv6:b-g547tm)* status: :shipit: complete! 2 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj, @rytaft, and @savoie)

___
*[pkg/sql/opt/norm/custom_funcs.go, line 1202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40891#-Lp8qaHrDNGiyHMZ1WLu:-LrBCz3S8IjW79IPLncv:b2modi2) ([raw file](https://github.com/cockroachdb/cockroach/blob/212afbca58e17c4cafdcecb4ed42f1cb702b8d6c/pkg/sql/opt/norm/custom_funcs.go#L1202)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

nit: maybe we can extract and re-use `translateColSet` for this? depending on how easy that extraction is (from the stats code)
</blockquote></details>

nice :thumbsup:

**Pull request merged**
