### PR TITLE
githooks: remove pre push crlfmt

### PR DESCRIPTION
**Pull request by madelynnblue**
More annoying than useful. Various complaints, including me.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9937)

### CODE REVIEW

**Comment by tschottdorf** [comment]
Then I ask that you go the whole way and make `TestCrlfmt` optional.

**Comment by bdarnell** [comment]
LGTM

**Comment by tamird** [comment]
Instead, consider removing the `go test -i ./...` at the head of `make check`. That will get this hook down to about 2s.

**Comment by petermattis** [comment]
LGTM. I'm not a fan of the pre-push check. It gets in the way of my workflow without adding anything. I've almost always done a `make check` before pushing and if I haven't, CI will catch the problem.

**Comment by tschottdorf** [comment]
> LGTM. I'm not a fan of the pre-push check. It gets in the way of my workflow without adding anything. I've almost always done a make check before pushing and if I haven't, CI will catch the problem.

I disagree, I eat CI way too often because Crlfmt errors out on me there, and `make check` takes about 2 minutes on my machine and while I do run it, for small fixes I often don't deem it worth it.

Let's just make `Crlfmt` optional while removing the check. The style enthusiasts can still run it periodically and commit the result.

**Comment by petermattis** [comment]
>  I eat CI way too often because Crlfmt errors out on me there

I think this is an indication that the `crlfmt` check is too onerous, not that a pre-push check is a good idea.

**Comment by petermattis** [comment]
Another thought: `make check` is annoyingly slow so I often run `make test`. Perhaps we should separate out a few quick checks that are always run as part of `make test`. I assume you are running `make test` before pushing, right?

**Comment by tschottdorf** [comment]
> I think this is an indication that the crlfmt check is too onerous, not that a pre-push check is a good idea.

Yes, but that's just what my comment said.

> Another thought: make check is annoyingly slow so I often run make test. Perhaps we should separate out a few quick checks that are always run as part of make test. I assume you are running make test before pushing, right?

Yes, but not necessarily all of them. I like the idea of separating out the fast and short tests, but I don't think that it's obvious that the short ones are really the ones that always catch the problem. For example, `vet` isn't super fast but often spot on.

I think enough time has sunk into making `Crlfmt` useful that we should just make it optional and accept PRs that fix up the formatting periodically.

**Comment by dt** [comment]
fwiw, just solving #9919 would make the exiting hook _much_ faster and thus potentially more palatable without outright killing it

**Comment by tamird** [comment]
@dt yes, and in fact it may be possible to remove that altogether. We've changed our Go toolchain version since that was introduced.

**Comment by andreimatei** [comment]
+1 to making the `TestCrlfmt` optional until the open bugs are fixed.

**Comment by RaduBerinde** [comment]
I agree it should be optional until we have an established way of running it automatically from our editors, and the outstanding bugs are fixed.

And I agree with Peter on `make check` slowness. It would be very beneficial if there was a way to skip some of the slower check tests like the imports checking (which hits rarely anyway) when you run `make` (e.g. through an env var that you can set once, something more specific thatn `TESTS`).

**Comment by RaduBerinde** [comment]
I also run into problems with this hook as it doesn't check what I'm actually pushing. I am trying to push a branch and I can't because my current tree (which is work-in-progress on a different branch) doesn't build.

**Comment by RaduBerinde** [comment]
LGTM

**Comment by mjibson** [comment]
I'm unsure how to make that test optional. Changing the t.Errors to t.Logs doesn't work because then nothing would ever get printed. Using fmt.Print seems like not a great solution either.

**Comment by tamird** [comment]
I think optional means "remove". -1 on it personally, but I might be in the
minority.

**Pull request merged**
