### PR TITLE
sql: pool allocate scanNode

### PR DESCRIPTION
**Pull request by petermattis**
scanNode, despite going on a recent diet, is still fairly heavy weighing
in at 1408 bytes. Use pool allocation to reduce GC pressure. For simple
read operations, this reduces allocated bytes by 6.5%.

```
name                  old time/op    new time/op    delta
KV/Scan/SQL/rows=1-8     181µs ± 1%     180µs ± 1%    ~     (p=0.050 n=9+9)

name                  old alloc/op   new alloc/op   delta
KV/Scan/SQL/rows=1-8    21.1kB ± 0%    19.8kB ± 0%  -6.58%  (p=0.000 n=9+8)

name                  old allocs/op  new allocs/op  delta
KV/Scan/SQL/rows=1-8       283 ± 0%       282 ± 0%  -0.35%  (p=0.000 n=10+9)
```

Ignore the lack of change in time/op. The reduced GC pressure adds up.

See #14927

### CODE REVIEW

**Comment by petermattis** [comment]
Replaces #17099. Interestingly, `*n = scanNode{}` is allowed despite the presence of `util.NoCopy`. 

I wonder if we should use pool allocation for other common plan nodes and structures such as `insertNode`, `tableInserter` and `tableUpserter`.

**Comment by petermattis** [comment]
Cc @jordanlewis

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17127#-:-KpSev3XeJv00Xna0TCk:bnfp4nl)*

**Comment by petermattis** [comment]
@RaduBerinde Any thoughts about:

> I wonder if we should use pool allocation for other common plan nodes and structures such as insertNode, tableInserter and tableUpserter.

```
sizeof(insertNode) == 312
sizeof(tableInserter) == 272
sizeof(tableUpdater) == 808
sizeof(tableUpserter) == 1976
sizeof(tableDeleter) == 216
```

**Comment by RaduBerinde** [comment]
I'm not terribly familiar with the write paths in SQL, but my guess is yes (especially for `tableUpserter`, given that upsert is the closest thing to a KV put).

**Comment by petermattis** [comment]
Expanded this PR to include pool allocation of `{delete,insert,update}Node` and `table{Inserter,Upserter}`. Commit includes new benchmark numbers. The effect on allocated bytes is smaller for `{delete,insert,update}` because those ops perform more allocations.

**Comment by RaduBerinde** [comment]
Nice! :lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17127#-:-KpUza12-j8y4jQi63yc:be8rotp)*

**Review by knz — COMMENTED** [review]
Thanks!

**Pull request merged**
