### PR TITLE
kv,allocator: allow rebalances that make targets hotter than sources

### LINKED ISSUE #81638: roachtest: rebalance/by-load/replicas failed
roachtest.rebalance/by-load/replicas [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=5230951&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=5230951&tab=artifacts#/rebalance/by-load/replicas) on release-22.1.0 @ [3abc7eeade10df4b59b0fb24236992f95bf46d9b](https://github.com/cockroachdb/cockroach/commits/3abc7eeade10df4b59b0fb24236992f95bf46d9b):

```
The test failed on branch=release-22.1.0, cloud=gce:
test artifacts and logs in: /artifacts/rebalance/by-load/replicas/run_1
	rebalance_load.go:149,rebalance_load.go:193,test_runner.go:875: timed out before leases were evenly spread
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #81131 roachtest: rebalance/by-load/replicas/mixed-version failed [C-test-failure O-roachtest O-robot T-kv branch-master]
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*rebalance/by-load/replicas.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-16001

### PR DESCRIPTION
**Pull request by lidorcarmel**
The allocator had a feature to prevent lease and replica moves if that move
would make the target store hotter than the source store.

Consider 2 stores:
s1 with 2 ranges, 5K QPS each.
s2 with 1 range, 1K QPS.
The allocator would take no action here because by moving one of the ranges
from s1 to s2, we would make s2 hotter than s1 (6K QPS on s2 vs 5K for s1).

This PR removes this check, so that the allocator would be more aggressive and
move a lease even if it will make the other store hotter.

Fixes #81638

Release note: None

### CODE REVIEW

**Review by kvoli — APPROVED** [review]
:lgtm_strong: 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82365#-:-N3_ns-z2RWK-WJnh_Ce:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lidorcarmel)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82365#-N3_nRO2AoKg0qh6n9yw):*
nit: I think this line is truncated on gh > 80 chars.

**Comment by lidorcarmel** [comment]
Thanks Austen!
cc @aayushshah15

bors r+

**Comment by aayushshah15** [comment]
Just to confirm, did we stress `rebalance/by-load/{leases,replicas}` with this? If not, I can spin up a few of those runs since those roachtests were pretty critical in flushing a lot of bugs out in this logic before.

**Comment by lidorcarmel** [comment]
define stress? I ran this a few times, less than 10.

**Pull request merged**
