### PR TITLE
plpgsql: implement OPEN statements

### PR DESCRIPTION
**Pull request by DrewKimball**
#### plpgsql: add parser support for cursors

This patch adds support in the PLpgSQL parser for the following commands
related to cursors: `DECLARE`, `OPEN`, `FETCH`, `MOVE`, and `CLOSE`.
The `OPEN ... FOR EXECUTE ...` syntax is not currently implemented.

Informs #105254

Release note: None

#### plpgsql: add execution support for OPEN statements

This patch adds support for executing PLpgSQL OPEN statements, which
open a SQL cursor in the current transaction. The name of the cursor
is supplied through a PLpgSQL variable. Since the `REFCURSOR` type
hasn't been implemented yet, this patch uses `STRING` in the
meantime.

Limitations that will be lifted in future PRs:
1. Unnamed cursor declarations are not supported. If a cursor is opened
   with no name supplied, a name should be automatically generated.
2. Bound cursors are not yet supported. It should be possible to declare
   a cursor in the `DECLARE` block with the query already defined, at
   which point it can be opened with `OPEN <cursor>;`.
3. A cursor cannot be opened in a routine with an exception block. This
   is because correct handling of this case is waiting on separate work
   to implement rollback of changes to database state on exceptions.

Informs #109709

Release note (sql change): Added initial support for executing the
PLpgSQL `OPEN` statement, which allows a PLpgSQL routine to create a
cursor. Currently, opening bound or unnamed cursors is not supported.
In addition, `OPEN` statements cannot be used in a routine with an
exception block.

### CODE REVIEW

**Review by rharding6373 — COMMENTED** [review]
Nice work! I mostly have test suggestions and clarification questions.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110709#-:-NedG6RT45wyKb7Do4gt:bwvoxjs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 526 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110709#-NePtaKJ-WITfn2PkIb6:-NePtaKJ-WITfn2PkIb7:b-61cemw) ([raw file](https://github.com/cockroachdb/cockroach/blob/575c3b5457cf63d0464d3bab722fbacbeafbf97f/pkg/sql/opt/optbuilder/plpgsql.go#L526)):*
> ```Go
> 				panic(unimplemented.New("bound cursor", "opening a bound cursor is not yet supported"))
> 			}
> 			if _, ok := t.Query.(*tree.Select); !ok {
> ```

Does this include queries with CTEs? I know we don't support CTEs in UDFs yet (and there are tests for this), but if you had a CTE in a cursor declared outside of a UDF, would it work?
___
*[`pkg/sql/plpgsql/parser/plpgsql.y` line 473 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110709#-NePcJNF6oXyDRFQE5Yk:-NePcJNF6oXyDRFQE5Yl:b-1yrcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a725fa969087f241f4f862d98142ed98befff711/pkg/sql/plpgsql/parser/plpgsql.y#L473)):*
> ```Yacc
>     $$.val = tree.UnspecifiedScroll
>   }
> | NO_SCROLL SCROLL
> ```

Should this be `NO SCROLL`? Based on the syntax in https://www.postgresql.org/docs/current/plpgsql-cursors.html#PLPGSQL-CURSOR-DECLARATIONS, but I see that the parser test seems to work so maybe I'm missing where `NO_SCROLL` maps to `NO`.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 1977 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110709#-NedERlYBQeV2Bc5iDcF:-NedERlYBQeV2Bc5iDcG:b-gryaar) ([raw file](https://github.com/cockroachdb/cockroach/blob/575c3b5457cf63d0464d3bab722fbacbeafbf97f/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L1977)):*
> ```
> 
> query II rowsort
> FETCH FORWARD 10 FROM foo;
> ```

Test ideas: 
* Fetch from foo twice with a smaller value and return rows both times to test continuity.
* Modify the table after declaring the cursor to test that fetch doesn't return inserted or updated rows.
___
*[`pkg/sql/plpgsql/parser/testdata/stmt_fetch_move` line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110709#-NePjxji5g7SHdRkJg6P:-NePjxji5g7SHdRkJg6Q:b-jer4zk) ([raw file](https://github.com/cockroachdb/cockroach/blob/a725fa969087f241f4f862d98142ed98befff711/pkg/sql/plpgsql/parser/testdata/stmt_fetch_move#L26)):*
> ```
> DECLARE
> BEGIN
> FETCH NEXT FROM emp_cur INTO x,y;
> ```

Testing idea: add tests for all the direction types (either in parsing or logic tests) (`NEXT`, `PRIOR`, `FIRST`, `LAST`, `ABSOLUTE` _`count`_, `RELATIVE` _`count`_, `FORWARD`, or `BACKWARD`) and an invalid direction for both `MOVE` and `FETCH`.

**Review by mgartner — COMMENTED** [review]
Very cool!

> Reviewed 9 of 9 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110709#-:-NejQDVvBNio8LOYyP02:b-jdo7t9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @rharding6373)

___
*[`-- commits` line 26 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110709#-NejIpm53gKwBiHzaMVZ):*
Are 1 and 2 needed immediately or can we address in 24.1?
___
*[`pkg/sql/routine.go` line 246 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110709#-NejJUZa5ln-SAsqz-Qq:-NejJUZa5ln-SAsqz-Qr:bkohr6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/575c3b5457cf63d0464d3bab722fbacbeafbf97f/pkg/sql/routine.go#L246)):*
> ```Go
> 		// We can use a droppingResultWriter for all statements in a procedure
> 		// because we do not yet allow OUT or INOUT parameters, so a procedure
> 		// never returns values.
> ```

nit: update the two paragraphs in this comment and/or combine with the newly added ones below.
___
*[`pkg/sql/routine.go` line 385 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110709#-NejPKwn6HBmg4G6cwpR:-NejPKwo8fA9yRWbu57L:b-c0nml4) ([raw file](https://github.com/cockroachdb/cockroach/blob/575c3b5457cf63d0464d3bab722fbacbeafbf97f/pkg/sql/routine.go#L385)):*
> ```Go
> }
> 
> func (g *routineGenerator) makeCursorHelper(
> ```

nit: functions that allocate a new struct and return a pointer we usually name `new...` instead of `make...` I believe
___
*[`pkg/sql/opt/memo/expr.go` line 730 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110709#-NejKA0r8fxU_RhRB53j:-NejKA0r8fxU_RhRB53k:b-mrgzos) ([raw file](https://github.com/cockroachdb/cockroach/blob/575c3b5457cf63d0464d3bab722fbacbeafbf97f/pkg/sql/opt/memo/expr.go#L730)):*
> ```Go
> 
> 	// CursorDeclaration contains the information needed to open a SQL cursor with
> 	// the result of the *first* body statement. It may be unset.
> ```

Is it an invariant that there should only be a single statement in the body if CursorDeclaration is set? If so, mention that here. 

EDIT: After looking at the optbuilder tests, it looks like that's not the case—it looks like there's always 2 statements in the body. But it's unclear to me why that's the case. Is there any more explanation you can provide to better reason about this?
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 554 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110709#-NejMoqC8Kij-Q8JhYPW:-NejMoqC8Kij-Q8JhYPX:b-q5c8sd) ([raw file](https://github.com/cockroachdb/cockroach/blob/575c3b5457cf63d0464d3bab722fbacbeafbf97f/pkg/sql/opt/optbuilder/plpgsql.go#L554)):*
> ```Go
> 				// Cursors with mutations are invalid.
> 				panic(pgerror.Newf(pgcode.FeatureNotSupported,
> 					"DECLARE CURSOR must not contain data-modifying statements in WITH",
> ```

Why is the error message specific to `WITH` but the comment mentions mutations, presumably in general.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 1977 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110709#-NedERlYBQeV2Bc5iDcF:-NejNOhv2mDuG1k2JVm4:b-jobukt) ([raw file](https://github.com/cockroachdb/cockroach/blob/575c3b5457cf63d0464d3bab722fbacbeafbf97f/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L1977)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Test ideas: 
* Fetch from foo twice with a smaller value and return rows both times to test continuity.
* Modify the table after declaring the cursor to test that fetch doesn't return inserted or updated rows.
</blockquote></details>

+1 Good ideas!
___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 2267 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110709#-NejNwuS7f9AOypNSJp2:-NejNwuS7f9AOypNSJp3:b-pahdsa) ([raw file](https://github.com/cockroachdb/cockroach/blob/575c3b5457cf63d0464d3bab722fbacbeafbf97f/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L2267)):*
> ```
> 
> statement error pgcode 42P03 pq: cursor \"foo\" already exists
> SELECT f();
> ```

nit: might be worthwhile to put these tests in a new logic test file singe this is getting lengthy

**Review by DrewKimball — COMMENTED** [review]
Thanks for taking a look!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110709#-:-NfFltY9AtZGUjTC8FRG:bubxju8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`-- commits` line 26 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110709#-NejIpm53gKwBiHzaMVZ):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Are 1 and 2 needed immediately or can we address in 24.1?
</blockquote></details>

Good question that I should have asked before implementing these. I think we could probably get away with avoiding either of them, although unnamed cursors are probably more convenient to have if we had to chose.
___
*[`pkg/sql/routine.go` line 246 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110709#-NejJUZa5ln-SAsqz-Qq:-NfFihHxAgmDs8wKADBU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/575c3b5457cf63d0464d3bab722fbacbeafbf97f/pkg/sql/routine.go#L246)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: update the two paragraphs in this comment and/or combine with the newly added ones below.
</blockquote></details>

Done.
___
*[`pkg/sql/routine.go` line 385 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110709#-NejPKwn6HBmg4G6cwpR:-NfFj1Px5DtDUxA0zZmt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/575c3b5457cf63d0464d3bab722fbacbeafbf97f/pkg/sql/routine.go#L385)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: functions that allocate a new struct and return a pointer we usually name `new...` instead of `make...` I believe
</blockquote></details>

Done.
___
*[`pkg/sql/opt/memo/expr.go` line 730 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110709#-NejKA0r8fxU_RhRB53j:-NfFj9UW6G7QW3jW4Kik:b-dvw4cf) ([raw file](https://github.com/cockroachdb/cockroach/blob/575c3b5457cf63d0464d3bab722fbacbeafbf97f/pkg/sql/opt/memo/expr.go#L730)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Is it an invariant that there should only be a single statement in the body if CursorDeclaration is set? If so, mention that here. 

EDIT: After looking at the optbuilder tests, it looks like that's not the case—it looks like there's always 2 statements in the body. But it's unclear to me why that's the case. Is there any more explanation you can provide to better reason about this?
</blockquote></details>

There will always be at least two body statements if CursorDeclaration is set. This is enforced when the routine is constructed (and it's volatile so that it can't be inlined). I've added this detail to the comment, LMK what you think.
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 526 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110709#-NePtaKJ-WITfn2PkIb6:-NfFaO0y70gf6afUrjXs:b-liazvx) ([raw file](https://github.com/cockroachdb/cockroach/blob/575c3b5457cf63d0464d3bab722fbacbeafbf97f/pkg/sql/opt/optbuilder/plpgsql.go#L526)):*
Yes, CTEs are allowed (and are included in `tree.Select`).

>if you had a CTE in a cursor declared outside of a UDF, would it work?

Do you mean a cursor declared with SQL syntax? In that case, it's already open, and can't be re-opened with a different query.
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 554 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110709#-NejMoqC8Kij-Q8JhYPW:-NfFb8t0Eck7mpcBuE4I:bw7x04c) ([raw file](https://github.com/cockroachdb/cockroach/blob/575c3b5457cf63d0464d3bab722fbacbeafbf97f/pkg/sql/opt/optbuilder/plpgsql.go#L554)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Why is the error message specific to `WITH` but the comment mentions mutations, presumably in general.
</blockquote></details>

I copied this from the SQL cursor declaration message. That being said, I _think_ the only case where a mutation could have reached this point would be a CTE, since we check that the statement is a `tree.Select` and don't allow calling other UDFs.
___
*[`pkg/sql/plpgsql/parser/plpgsql.y` line 473 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110709#-NePcJNF6oXyDRFQE5Yk:-NfFc2zbC-OXZ5qWV5GA:bmkkzu8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a725fa969087f241f4f862d98142ed98befff711/pkg/sql/plpgsql/parser/plpgsql.y#L473)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Should this be `NO SCROLL`? Based on the syntax in https://www.postgresql.org/docs/current/plpgsql-cursors.html#PLPGSQL-CURSOR-DECLARATIONS, but I see that the parser test seems to work so maybe I'm missing where `NO_SCROLL` maps to `NO`.
</blockquote></details>

Yeah, `NO_SCROLL` just means `NO`, but in the specific case where the following token is `SCROLL`. See `Lex()` in `plpgsql/parser/lexer.go`.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 1977 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110709#-NedERlYBQeV2Bc5iDcF:-NfFglDR3K5Za3Bav5Ch:b3zso51) ([raw file](https://github.com/cockroachdb/cockroach/blob/575c3b5457cf63d0464d3bab722fbacbeafbf97f/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L1977)):*
>Fetch from foo twice with a smaller value and return rows both times to test continuity.

Done.

>Modify the table after declaring the cursor to test that fetch doesn't return inserted or updated rows.

This is tested at the line starting with `The cursor should reflect changes to the database state...`. I added an UPDATE as well.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 2267 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110709#-NejNwuS7f9AOypNSJp2:-NfFh__352KZC_4NSLJl:bk29t5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/575c3b5457cf63d0464d3bab722fbacbeafbf97f/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L2267)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: might be worthwhile to put these tests in a new logic test file singe this is getting lengthy
</blockquote></details>

Done - the new file is `plpgsql_cursor`.
___
*[`pkg/sql/plpgsql/parser/testdata/stmt_fetch_move` line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110709#-NePjxji5g7SHdRkJg6P:-NfFji3N0pYgXPfPkM-g:b-3gumkl) ([raw file](https://github.com/cockroachdb/cockroach/blob/a725fa969087f241f4f862d98142ed98befff711/pkg/sql/plpgsql/parser/testdata/stmt_fetch_move#L26)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Testing idea: add tests for all the direction types (either in parsing or logic tests) (`NEXT`, `PRIOR`, `FIRST`, `LAST`, `ABSOLUTE` _`count`_, `RELATIVE` _`count`_, `FORWARD`, or `BACKWARD`) and an invalid direction for both `MOVE` and `FETCH`.
</blockquote></details>

Good idea. I'll do this in the parser tests for now, and for logic tests when implementing MOVE and FETCH.

**Review by rharding6373 — APPROVED** [review]
Looks great! :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110709#-:-NfSNATxBENi5gWknWQw:blerph5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/plpgsql/parser/plpgsql.y` line 473 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110709#-NePcJNF6oXyDRFQE5Yk:-NfSKC09EnnVZu7KD6TW:b-5kbax0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a725fa969087f241f4f862d98142ed98befff711/pkg/sql/plpgsql/parser/plpgsql.y#L473)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Yeah, `NO_SCROLL` just means `NO`, but in the specific case where the following token is `SCROLL`. See `Lex()` in `plpgsql/parser/lexer.go`.
</blockquote></details>

Thanks for the pointer!
___
*[`pkg/sql/plpgsql/parser/testdata/stmt_fetch_move` line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110709#-NePjxji5g7SHdRkJg6P:-NfSKoBW0k5bdNNAyjX-:bbecdf3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a725fa969087f241f4f862d98142ed98befff711/pkg/sql/plpgsql/parser/testdata/stmt_fetch_move#L26)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Good idea. I'll do this in the parser tests for now, and for logic tests when implementing MOVE and FETCH.
</blockquote></details>

Nice, looks good.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 1977 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110709#-NedERlYBQeV2Bc5iDcF:-NfSN6J16to3lXu1kQNa:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/575c3b5457cf63d0464d3bab722fbacbeafbf97f/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L1977)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

>Fetch from foo twice with a smaller value and return rows both times to test continuity.

Done.

>Modify the table after declaring the cursor to test that fetch doesn't return inserted or updated rows.

This is tested at the line starting with `The cursor should reflect changes to the database state...`. I added an UPDATE as well.
</blockquote></details>

Thanks!

**Comment by DrewKimball** [comment]
TFTRs!

bors r+

**Pull request merged**
