### PR TITLE
changefeedccl: support changefeeds with user defined types

### LINKED ISSUE #49981: sql: investigate interaction between user defined types and changefeeds
At the very least we need some tests here to ensure that everything works as expected.

### PR DESCRIPTION
**Pull request by rohany**
Fixes #49981.

Support changefeeds on tables that contain user defined types.

Release justification: fixes for high-severity bugs in existing
functionality

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
I would love to see the nemesis test extended to support enums. That thing catches bugs like it's its job. Let's do that as a follow-up. 

> Reviewed 9 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53489#-:-MG60q-d7sVPECPm_yZz:b-8k3b42)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @miretskiy, and @rohany)

___
*[pkg/ccl/changefeedccl/rowfetcher_cache.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53489#-MG61JwV2lDIRpgaLuZn:-MG61JwV2lDIRpgaLuZo:b-b7vw25) ([raw file](https://github.com/cockroachdb/cockroach/blob/73c542c12b23faa7807c080f45015d2d382dd30f/pkg/ccl/changefeedccl/rowfetcher_cache.go#L83)):*
> ```Go
> 		}
> 
> 		// Retrieve the target TableDesc. We open a txn here, but only because
> ```

This is going to be expensive :/ 

I'd love if we could pass a timestamp in addition to the txn and then make the txn optional, at least on an immutable table descriptor path. 

If that's too big for right now, let's add a TODO. I think this one is going to hurt pretty bad. Transactions have a bunch of state associated with them.

**Comment by rohany** [comment]
> I would love to see the nemesis test extended to support enums. That thing catches bugs like it's its job. Let's do that as a follow-up.

Yeah, that was a goal but i felt it would be too much to do in this PR

> I'd love if we could pass a timestamp in addition to the txn and then make the txn optional, at least on an immutable table descriptor path.

Hmm, I only went down this route because we discussed offline and you said that a txn that doesn't actually read anything would be cheap.

Though I'm not sure of the alternative, I haven't looked into how changing the collection interface to not take in txn's would be.

**Review by ajwerner — COMMENTED** [review]
It doesn't read anything but it does allocate a bunch. This gets called per row. I think changing the interface to also take a timestamp and an optional txn should be easy. Let me know if you find otherwise and just put a TODO. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53489#-:-MG68cYK0UNXjAmCvtVJ:b-nmkzv6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @rohany)

**Review by ajwerner — COMMENTED** [review]
I'm not even that enthusiastic about the append to leasedDescriptors. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53489#-:-MG68yGm1QeQ1WS5yE1N:bmvfmrz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @rohany)

**Review by ajwerner — COMMENTED** [review]
I think we can mitigate that one by making releaseAll truncate the slice and write `nil` into it. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53489#-:-MG696oHDBCU39tvzM3h:bcb09b2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @rohany)

**Review by ajwerner — COMMENTED** [review]
err, I guess we do that, carry on

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53489#-:-MG69F1_AGR-36PAafy8:b-yfuzze)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @rohany)

**Comment by rohany** [comment]
The fact that it is getting called per row is an impetus to give it a shot. I'll try it tomorrow.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53489#-:-MGEryrz9u0rK_9w7hNQ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @miretskiy and @rohany)

**Pull request merged**
