### PR TITLE
upgrade: don't blindly run permanent migrations

### PR DESCRIPTION
**Pull request by andreimatei**
This patch makes the "primordial" permanent upgrades not run in clusters
being upgraded from 22.2 or lower.

Startup migrations were recently replaced with "permanent upgrades", in #91627.
The permanent new upgrades were running on node startup regardless of
whether it was a "new cluster" or an existing one - i.e. regardless of
whether the previous startupmigrations had also run, on the argument
that startupmigrations and upgrades are supposed to be idempotent
anyway. But, alas, there's idempotency and then there's idempotency:
startupmigrations/upgrades are supposed to be OK with running multiple
times at the same BinaryVersion in a "new cluster", but not necessarily
across BinaryVersions and in a cluster that has been in use. There are
different things that can go wrong when one of these migrations runs
multiple times in these general conditions, because the migration
might makes implicit assumptions about the schema and data of the
cluster it's running in:
1. A migration might assume that all the data in a system table was
   created before a CRDB version changed some semantics. For example,
   the migration deleted in #92597 was assuming that `CREATEROLE` role
   option had a certain meaning for all the users who have it and was doing
   a backfill across all these users. Running this migration again at an
   arbitrary later point would affect unintended new users.
2. A migration assumes the schema of system tables it operates on. As
   this schema (which is part of the bootstrap image for new cluster)
   changes with new versions, the code of the upgrade changes also. This
   means that the upgrade is no longer suitable for running against
   clusters that don't have the upgraded schema - i.e. clusters that have
   not yet been upgraded to the latest schema. This is a real problem
   because we're adding a column to system.users, and the addRootUser
   upgrade can no longer run against 22.2 clusters.

This patch guards all upgrades on checking that the old corresponding
startupmigration has not run, thus enabling the mentioned system schema
change in 23.1.

Release note: None
Epic: None

### CODE REVIEW

**Comment by andreimatei** [comment]
cc @andyyang890

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93071#-:-NInX7cJ3tXAJ_A3NLf5:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[`pkg/upgrade/doc.go` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93071#-NInWsxc0fss_k-k4VKg:-NInWsxd2gajYHtI5goL:bexw89h) ([raw file](https://github.com/cockroachdb/cockroach/blob/0be9c228de6caeade6cc9419bd2e2e1ed7227347/pkg/upgrade/doc.go#L13)):*
> ```Go
> package upgrade
> 
> // Package upgrade contains infrastructure for migrating a cluster from a
> ```

nit: this reads like a doc comment, why not put it above `package upgrade`?

**Review by andreimatei — COMMENTED** [review]
TFTR

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93071#-:-NIneQKi1AQa1YMSTHed:b-4as1hm)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

___
*[`pkg/upgrade/doc.go` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93071#-NInWsxc0fss_k-k4VKg:-NIneMYY7kw9dRzpgaIa:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0be9c228de6caeade6cc9419bd2e2e1ed7227347/pkg/upgrade/doc.go#L13)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: this reads like a doc comment, why not put it above `package upgrade`?
</blockquote></details>

done

**Review by andyyang890 — COMMENTED** [review]
Thanks for fixing this! Just had one small style comment.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93071#-:-NInjpJi0Fo5AHeLT3Mu:b8anyr)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @andreimatei)

___
*[`pkg/upgrade/doc.go` line 73 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93071#-NInjkgp4MzkMJim4z9w:-NInjkgp4MzkMJim4z9x:bfnnhsr) ([raw file](https://github.com/cockroachdb/cockroach/blob/33431136b1b5f19f6d1d2e86cfc6a032c80462c0/pkg/upgrade/doc.go#L73)):*
> ```Go
> bootstrap schema that has "foo".
> */
> ```

nit: there should be no newline between the package comment and the declaration

**Pull request merged**
