### PR TITLE
sqlbase: add the missing comments and group functions by purpose

### PR DESCRIPTION
**Pull request by knz**
First commits from #28942 and priors.
Forked from #28690.

The file `table.go` was getting unwieldy and was containing functions
from different area of concern. This was making maintenance
particularly burdensome.

This patch splits the functionality in the following files:

- `index_encoding.go`: index key prefixes, differences between primary
  and secondary encodings, how to organize columns in an index.

- `column_type_encoding.go`: encoding of SQL values into bytes
  towards KV.

- `column_type_properties.go`: conversions between various
  representations of types in the SQL layer; derivation of properties
  from SQL types.

- `datum_alloc.go`: the `DatumAlloc` helper.

Release note: None

### CODE REVIEW

**Review by BramGruneir — APPROVED** [review]
:lgtm: With some requested changes.

I love the code reorganizing and adding comments to it. 

However, next time, please split this into multiple commits:
- 1 commit to move the code
- 1 commit to add the comments

It makes the reviewers life a lot easier to skip the code movement (besides where it lands) and concentrate on the updated descriptions.

> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, 18 of 18 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-:-LKXxHJnEnVZuTdNRcY9:bp4gysn)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsqlplan/physical_plan.go, line 900 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXfxQ58AZ2eTLojyxx:-LKXfxQ58AZ2eTLojyxy:b-bafn6s) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/distsqlplan/physical_plan.go#L900)):*
> ```Go
> // another, excluding its VisibleType type alias, which doesn't effect
> // equality.
> func equivalentTypes(c, other *sqlbase.ColumnType) bool {
> ```

This seems out of place in this file.  Unless this is the only place where it is used.
___
*[pkg/sql/sqlbase/column_type_encoding.go, line 930 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXi78jA_Y2b8ViMCWB:-LKXi78k-mjuI4V6PB5b:b-5p10et) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/column_type_encoding.go#L930)):*
> ```Go
> }
> 
> func numBytesInBitArray(numBits int) int {
> ```

this could use a comment
___
*[pkg/sql/sqlbase/column_type_encoding.go, line 1031 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXiPbBAZ9tgfPvShxF:-LKXiPbC4SoEYl7keLxC:breqpjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/column_type_encoding.go#L1031)):*
> ```Go
> }
> 
> func encodeArrayElement(b []byte, d tree.Datum) ([]byte, error) {
> ```

could use a comment here too while you're at it 
___
*[pkg/sql/sqlbase/column_type_properties.go, line 48 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXd9hTB9ALxpclb5Eg:-LKXd9hU0xI8Gx86recO:b-kbwd5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/column_type_properties.go#L48)):*
> ```Go
> // Some notional complexity arises from the fact there are fewer
> // different types.T than different coltypes.T/ColumnTypes. This is
> // because some distinctions important at the time of data persistence
> ```

some distinctions **which are** important at the 
___
*[pkg/sql/sqlbase/column_type_properties.go, line 51 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXcfBECU78eMR3WT_S:-LKXcfBF8hTHgsOmwp9x:b-9jq6rc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/column_type_properties.go#L51)):*
> ```Go
> // (or casts) are not useful to keep for in-flight values; for example
> // the final required precision for DECIMAL values.
> //
> ```

nit: extra blank comment lines
___
*[pkg/sql/sqlbase/column_type_properties.go, line 129 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXctUH-Zzts0gMOUpx:-LKXctUH-Zzts0gMOUpy:b-6g406k) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/column_type_properties.go#L129)):*
> ```Go
> 		base.Width = int32(t.Scale)
> 		base.Precision = int32(t.Prec)
> ```

nit: remove this extra line, and add one after the switch to match the earlier blanks.  Or just remove all blank lines, since the style changed again later.
___
*[pkg/sql/sqlbase/column_type_properties.go, line 255 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXe6_A-61_gSTav6Hs:-LKXe6_A-61_gSTav6Ht:b4wh2fn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/column_type_properties.go#L255)):*
> ```Go
> // type is not a character or bit string, or if the string's length is not bounded.
> //
> // This is used to populate information_schema.columns.character_maximum_length.
> ```

Generally, it's advisable not to declare in a function where it is being used.  Since that is likely to rot and doesn't provide much extra info.  

For example, if we have a new use for it, should we add it here?  If we remove that primary use of it, this comment also has to be changed.

(This comment applies to this whole file)
___
*[pkg/sql/sqlbase/column_type_properties.go, line 266 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXeY4x1Q9Z12z4ESRd:-LKXeY4x1Q9Z12z4ESRe:b-9kmrl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/column_type_properties.go#L266)):*
> ```Go
> }
> 
> // MaxOctetLength returns the maximum the maximum possible length in octets of a
> ```

the maximum is repeated
___
*[pkg/sql/sqlbase/column_type_properties.go, line 313 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXefMXBTKk638meCnD:-LKXefMXBTKk638meCnE:b-qr3ufe) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/column_type_properties.go#L313)):*
> ```Go
> }
> 
> // NumericPrecisionRadix returns implicit precision radix of numeric
> ```

returns **the** implicit
___
*[pkg/sql/sqlbase/column_type_properties.go, line 349 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXeoQA-LphmZDUiekX:-LKXeoQA-LphmZDUiekY:b-qjcuv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/column_type_properties.go#L349)):*
> ```Go
> //
> // This function is for internal use in this package and only exported
> // for testing in pgwire. Avoid using directly!
> ```

If this is only used for testing, we should move it to column_type_properties_test.go to ensure it is not used in any main codepath.
___
*[pkg/sql/sqlbase/column_type_properties.go, line 409 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXf3PHEZ2RtyPABYW7:-LKXf3PHEZ2RtyPABYW8:bjsyl7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/column_type_properties.go#L409)):*
> ```Go
> 
> // columnSemanticTypeToDatumType determines a types.T that can be used
> // to instantiate in-memory representation of values of the given
> ```

instantiate **an** in-memory representation of values **for** the given
___
*[pkg/sql/sqlbase/column_type_properties.go, line 463 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXfMRLDD8NYcnI8jJ6:-LKXfMRLDD8NYcnI8jJ7:btsaby3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/column_type_properties.go#L463)):*
> ```Go
> 
> // ToDatumType converts the ColumnType to a types.T suitable to instantiate
> // in-memory representations of the values of a column of the given ColumnType.
> ```

This sentence is confusing and needs work.
___
*[pkg/sql/sqlbase/column_type_properties.go, line 496 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXfUKXBfeg-c3aSje7:-LKXfUKXBfeg-c3aSje8:b-my4zu2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/column_type_properties.go#L496)):*
> ```Go
> 
> // CheckValueWidth checks that the width (for strings, byte arrays, and
> // bit string) and scale (for decimals) of the value fits the specified
> ```

bit string**s**) and
___
*[pkg/sql/sqlbase/index_encoding.go, line 58 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXuOem8iyQsEiNYnOG:-LKXuOen-_SRK_TO7MC1:b-ejd7cu) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/index_encoding.go#L58)):*
> ```Go
> // /<parent_table_id>/<parent_index_id>/<field_1>/<field_2>/NullDesc/<table_id>/<index_id>/<field_3>/<family>
> //
> // Returns the key and whether any of the encoded values were NULLs.
> ```

This comment should be with the first sentence, since it describes the function.
___
*[pkg/sql/sqlbase/index_encoding.go, line 246 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXulnm1_R5LROCdqQH:-LKXulnm1_R5LROCdqQI:b-foms0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/index_encoding.go#L246)):*
> ```Go
> }
> 
> func appendEncDatumsToKey(
> ```

Could use a comment.
___
*[pkg/sql/sqlbase/index_encoding.go, line 272 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXutpY26JJviIk3H1Y:-LKXutpY26JJviIk3H1Z:bqnutuz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/index_encoding.go#L272)):*
> ```Go
> // index.ExtraColumnIDs respectively.
> //
> // MakeKeyFromEncDatums (see above) does not allow you to create a key
> ```

remove the `(see above)` and add `Note:` or `Note that ` at the start
___
*[pkg/sql/sqlbase/index_encoding.go, line 319 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXv64D9shIj3mzUVx1:-LKXv64D9shIj3mzUVx2:blw3t06) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/index_encoding.go#L319)):*
> ```Go
> // EncodeDatumKeyAscending encodes a datum using an order-preserving
> // encoding.
> // The encoding is lossy -- some datums need composite encoding where the
> ```

nit: the -- is strange.  Perhaps a semicolon?

Similar for the datums version as well.
___
*[pkg/sql/sqlbase/index_encoding.go, line 666 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXvsal3b8Sx-bKz_Ro:-LKXvsal3b8Sx-bKz_Rp:bu1i9zt) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/index_encoding.go#L666)):*
> ```Go
> // EncodeInvertedIndexKeys creates a list of inverted index keys
> // by concatenating keyPrefix with the encodings of the column in the index.
> //
> ```

Nit: remove space here.  What this returns should be part of the main description.
___
*[pkg/sql/sqlbase/index_encoding.go, line 690 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXw0RDBIoQZBghjwR9:-LKXw0RDBIoQZBghjwRA:b-n493l3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/index_encoding.go#L690)):*
> ```Go
> }
> 
> // EncodeInvertedIndexTableKeys encodes the paths in a JSON `val` and concatenates it with `inKey`and returns
> ```

lint: This comment seems like it is longer than our normal max.
___
*[pkg/sql/sqlbase/index_encoding.go, line 838 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXC9ME2lIs36E-tQ1N:-LKXC9ME2lIs36E-tQ1O:b-1hbxvq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/index_encoding.go#L838)):*
> ```Go
> //  - int (converts to DInt)
> //  - string (converts to DString)
> func TestingMakePrimaryIndexKey(desc *TableDescriptor, vals ...interface{}) (roachpb.Key, error) {
> ```

This should be declared in index_encoding_test.go so it can never be used in non-test code.
___
*[pkg/sql/sqlbase/index_encoding.go, line 890 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXwOBy5-BEwOUDq7sc:-LKXwOBy5-BEwOUDq7sd:blfdcfw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/index_encoding.go#L890)):*
> ```Go
> // belongs to a table where its equivalence signature and all its interleave
> // ancestors' signatures can be found in validEquivSignatures.
> // validEquivSignatures: a map containing equivalence signatures of valid
> ```

remove the colon and turn this into a sentence, the colon just makes it look like you'll have a list of explanations but there is only one.
___
*[pkg/sql/sqlbase/index_encoding.go, line 1039 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXwykn-cjVBlF453o5:-LKXwykn-cjVBlF453o6:bt1uyfc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/index_encoding.go#L1039)):*
> ```Go
> //    /table/index/<parent-pk1>/.../<parent-pkX>
> //
> // We return the maximum number of <tokens> in this prefix.
> ```

`We` -> `This`

**Review by knz — COMMENTED** [review]
Thanks Bram for pushing me for the extra mile. I have split the commits to distinguish the movement and the documentation, as you recommended.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-:-LK_wmDn1u5IKCr2jvVV:b-af0924)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/distsqlplan/physical_plan.go, line 900 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXfxQ58AZ2eTLojyxx:-LK_wkH3A6mLRuSQGni7:b42bcpe) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/distsqlplan/physical_plan.go#L900)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

This seems out of place in this file.  Unless this is the only place where it is used.
</blockquote></details>

It is, clarified in commit message.
___
*[pkg/sql/sqlbase/column_type_encoding.go, line 930 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXi78jA_Y2b8ViMCWB:-LK_u9pD60zgDsBlQMcq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/column_type_encoding.go#L930)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

this could use a comment
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/column_type_encoding.go, line 1031 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXiPbBAZ9tgfPvShxF:-LK_uHVp2oK3W8GZJ-5Y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/column_type_encoding.go#L1031)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

could use a comment here too while you're at it 
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/column_type_properties.go, line 48 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXd9hTB9ALxpclb5Eg:-LK_nCq92X7DrfOztlPo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/column_type_properties.go#L48)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

some distinctions **which are** important at the 
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/column_type_properties.go, line 129 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXctUH-Zzts0gMOUpx:-LK_nu2J1G2ZOyZIVIt7:b-i1l69p) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/column_type_properties.go#L129)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

nit: remove this extra line, and add one after the switch to match the earlier blanks.  Or just remove all blank lines, since the style changed again later.
</blockquote></details>

I made them all consistent. Thanks for noticing.
___
*[pkg/sql/sqlbase/column_type_properties.go, line 255 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXe6_A-61_gSTav6Hs:-LK_o1yX06pR2Z06KzhU:b-pjokku) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/column_type_properties.go#L255)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Generally, it's advisable not to declare in a function where it is being used.  Since that is likely to rot and doesn't provide much extra info.  

For example, if we have a new use for it, should we add it here?  If we remove that primary use of it, this comment also has to be changed.

(This comment applies to this whole file)
</blockquote></details>

I think it's more subtle than that: the behavior of this function is *constrained* by what is required of information_schema, that is, future uses may not modify its semantics unless they double check the information_schema is not affected. Updated the comment accordingly.
___
*[pkg/sql/sqlbase/column_type_properties.go, line 266 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXeY4x1Q9Z12z4ESRd:-LK_oZhj2-5o3mM0A80w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/column_type_properties.go#L266)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

the maximum is repeated
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/column_type_properties.go, line 313 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXefMXBTKk638meCnD:-LK_ocXWAYQQfZoTGAJn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/column_type_properties.go#L313)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

returns **the** implicit
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/column_type_properties.go, line 349 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXeoQA-LphmZDUiekX:-LK_ofL2BbQXK84vf_06:bh6t42c) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/column_type_properties.go#L349)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

If this is only used for testing, we should move it to column_type_properties_test.go to ensure it is not used in any main codepath.
</blockquote></details>

Unfortunately Go does not allow us to place a function in a _test.go file if it's used in a different package.
Besides as explained in the comment it is also used by other functions in this file.
But you're right, this deserved a small improvement. Done.
___
*[pkg/sql/sqlbase/column_type_properties.go, line 409 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXf3PHEZ2RtyPABYW7:-LK_p8Ib7tq9FW6TKQPd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/column_type_properties.go#L409)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

instantiate **an** in-memory representation of values **for** the given
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/column_type_properties.go, line 463 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXfMRLDD8NYcnI8jJ6:-LK_pLLe67-JOOTI95CG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/column_type_properties.go#L463)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

This sentence is confusing and needs work.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/column_type_properties.go, line 496 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXfUKXBfeg-c3aSje7:-LK_pNjW0E_Sh7suG_AO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/column_type_properties.go#L496)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

bit string**s**) and
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/index_encoding.go, line 58 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXuOem8iyQsEiNYnOG:-LK_xHKl8jnDN6HKmA5x:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/index_encoding.go#L58)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

This comment should be with the first sentence, since it describes the function.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/index_encoding.go, line 246 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXulnm1_R5LROCdqQH:-LK_xKF05ni_lQu0Kvg4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/index_encoding.go#L246)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Could use a comment.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/index_encoding.go, line 272 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXutpY26JJviIk3H1Y:-LK_xPxt3Q87WaJeZw6k:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/index_encoding.go#L272)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

remove the `(see above)` and add `Note:` or `Note that ` at the start
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/index_encoding.go, line 690 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXw0RDBIoQZBghjwR9:-LK_xacdBrgmk2iaO_L6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/index_encoding.go#L690)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

lint: This comment seems like it is longer than our normal max.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/index_encoding.go, line 838 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXC9ME2lIs36E-tQ1N:-LK_xjW2CnDKmcviDDQV:b1vsq0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/index_encoding.go#L838)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

This should be declared in index_encoding_test.go so it can never be used in non-test code.
</blockquote></details>

Again, unfortunately Go does not allow us to place a function in a _test.go file if it's used in a different package.
But I moved it to `testutils.go` to clarify.
___
*[pkg/sql/sqlbase/index_encoding.go, line 890 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXwOBy5-BEwOUDq7sc:-LK_yAJu3ADb_BjGWQAT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/index_encoding.go#L890)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

remove the colon and turn this into a sentence, the colon just makes it look like you'll have a list of explanations but there is only one.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/index_encoding.go, line 1039 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28943#-LKXwykn-cjVBlF453o5:-LK_yDbcEo15chdyZRXR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c0125b52aca091ebc61de5abb278d4d4b283cf/pkg/sql/sqlbase/index_encoding.go#L1039)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

`We` -> `This`
</blockquote></details>

Done.

**Pull request merged**
