### PR TITLE
Add support for parsing timestamps in pgwire

### PR DESCRIPTION
**Pull request by danhhz**
Fixes 4872.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5280)

### CODE REVIEW

**Comment by petermattis** [comment]
Shouldn't there be a test case or two added to `pgwire_test.go`.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5280#-:-KCw5bVWv5XG0kjfrl7a:1269223766)*

**Comment by paperstreet** [comment]
Ah, there it is! I was looking for a test file in sql/pgwire to add to and didn't see it. I'll add some shortly

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5280#-:-KCw6Vyx9yCfxibVHnOK:-1630884389)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/pgwire/types.go, line 424 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5280#-KCw6xJmK-9QtNvOu15k:-KCw6xJmK-9QtNvOu15l:-1043009166) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7a85aed1b818ca50cc7593db9818c37b9bc10b9/sql/pgwire/types.go#L424)):*
looks like some debugging code got left behind

---

*[sql/pgwire/types.go, line 437 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5280#-KCw7--tqGqu0jjWK8at:-KCw7--tqGqu0jjWK8au:-469765787) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7a85aed1b818ca50cc7593db9818c37b9bc10b9/sql/pgwire/types.go#L437)):*
ditto

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5280)*

**Comment by paperstreet** [comment]
Done

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5280#-:-KCwBl59wdkkHSrCyfU2:676635175)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/pgwire_test.go, line 361 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5280#-KCwEatQDFGZW0ZhNGrI:-KCwEatQDFGZW0ZhNGrJ:-1682048733) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea5aadecd6321060196ee60c06d0ca3911ed97bc/sql/pgwire_test.go#L361)):*
s/FixedZone("", 0)/UTC/

can you add another test which exercises type inference, perhaps by inserting into a table?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5280)*

**Comment by spencerkimball** [comment]
Fixes #4872

**Comment by petermattis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5280#-:-KCzccsq2CYx5xk4eteR:1417088721)*

**Comment by paperstreet** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/pgwire_test.go, line 361 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5280#-KCwEatQDFGZW0ZhNGrI:-KCwRcJ9_V3k2V8tz9PC:-1803490144) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea5aadecd6321060196ee60c06d0ca3911ed97bc/sql/pgwire_test.go#L361)):*
UTC doesn't work because the names don't match

    pgwire_test.go:425: SELECT $1::timestamp, $2::date: [2001-01-02 03:04:05 2006-07-08]: expected [2001-01-02 03:04:05 +0000 UTC 2006-07-08 00:00:00 +0000 UTC], got [2001-01-02 03:04:05 +0000 +0000 2006-07-08 00:00:00 +0000 +0000]

Added an insert test.

---

*[sql/pgwire/types.go, line 424 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5280#-KCw6xJmK-9QtNvOu15k:-KCwRTRI0UHdm_Ve8-O0:676634921) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7a85aed1b818ca50cc7593db9818c37b9bc10b9/sql/pgwire/types.go#L424)):*
Doh!

---

*[sql/pgwire/types.go, line 437 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5280#-KCw7--tqGqu0jjWK8at:-KCwRUUnPmj_SCIluuFC:676634921) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7a85aed1b818ca50cc7593db9818c37b9bc10b9/sql/pgwire/types.go#L437)):*
Doh!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5280)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/pgwire_test.go, line 361 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5280#-KCwEatQDFGZW0ZhNGrI:-KD-VF5gupjf-U-rRjhZ:1201592253) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea5aadecd6321060196ee60c06d0ca3911ed97bc/sql/pgwire_test.go#L361)):*
Oh, so the upstream parsing code just puts it in a 0-offset anonymous timezone? or does it assume local time? i'm afraid

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5280)*

**Comment by paperstreet** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/pgwire_test.go, line 361 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5280#-KCwEatQDFGZW0ZhNGrI:-KD-Xj34x2MxCsLYYr48:2081981497) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea5aadecd6321060196ee60c06d0ca3911ed97bc/sql/pgwire_test.go#L361)):*
You can specify the offset in the timestamp, it defaults to 0 if unspecified. (https://github.com/cockroachdb/pq/blob/master/encode.go#L419) I could change the parse code to differentiate between unset (and return UTC) and "+000" (return time.NamedZone("", 0))

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5280)*

**Comment by tamird** [comment]
Huh, OK, seems fine.

**Pull request merged**
