### PR TITLE
rpc opt: if sends to the local node, call the function directly.

### PR DESCRIPTION
**Pull request by thundercw**
if sends to the local node, call the function directly. This optimization is only suitable for `dist_sender`.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3209)

### CODE REVIEW

**Comment by bdarnell** [comment]
I have some concerns about this optimization:

First, because it doesn't serialize/deserialize the messages, it is possible for the RPC method to modify the requests and have those modifications affect the caller. We've had problems with this in the past (although maybe we've fixed all of them now since most of our tests use a local sender which doesn't have this safeguard either).

Second, it blocks the caller while the method is invoked. This might not be an issue for write-heavy workloads (since writes get serialized by raft anyway), but mixed read/write workloads rely on this parallelism. I think it could also deadlock multiraft if the incoming request channel fills up (this change affects the raft transport in addition to `DistSender`).

How much of a difference does this change make in performance?

**Comment by petermattis** [comment]
I think the Ben's concerns can and should be addressed. I'm also interested in the performance improvements. I imagine some of the existing benchmarks (e.g. `sql.BenchmarkBank`) might show an improvement.

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[rpc/rpc.go, line 18 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3209#-K3wNOneAUHiTLGHQNPk:-K3wNOneAUHiTLGHQNPl:1820560267) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b2ea19e51c24ba4b80fea00f403912b03b24882/rpc/rpc.go#L18)):*
Any reason this field is not exported like the other fields in `Context`? It doesn't look like `SetLocalServer` is doing anything interesting.

---

*[rpc/send.go, line 279 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3209#-K3wNyeXgaMKg_Xx-cos:-K3wNyeXgaMKg_Xx-cot:-785903449) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b2ea19e51c24ba4b80fea00f403912b03b24882/rpc/send.go#L279)):*
Perhaps either the handler, or `localCall` should be run in a goroutine so that local calls do not block the caller.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3209#-:-K3wOhE6hR61IIM1126i:-999531908)*

**Comment by thundercw** [comment]
@bdarnell 
Q1: In my previous implementation, I cloned the `args` by `argv :=proto.Clone(args)`. I removed it After checked the code and found that the `args` is not modified. I have tested that the performance of clone a instance is poor. The code will be restored, and use `argv` for RPC method. 
Q2:  The RPC method registered  by `node` is asynchronous, 'meth.Handler' will create a go routine to run the RPC method. So It can't blocks the caller.
Can you explain in more detail about this concerns ?
 `I think it could also deadlock multiraft if the incoming request channel fills up`

**Comment by thundercw** [comment]
I will do a benchmark use `sql.BenchmarkBank`.

**Comment by bdarnell** [comment]
`method.handler` will create a goroutine in most cases, but not for `server/rpcTransport` (`raft_transport.go`). The `RaftMessage` RPC writes to a buffered channel without starting a goroutine. Since we send raft messages from the same goroutine that reads from that channel, it will deadlock if the buffer fills up. 

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[rpc/rpc.go, line 18 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3209#-K3wNOneAUHiTLGHQNPk:-K3y9LsR1zxTZdRodoN_:1247879713) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b2ea19e51c24ba4b80fea00f403912b03b24882/rpc/rpc.go#L18)):*
The interesting thing is that `localServer` can be changed after the fact (look at how `SetLocalServer` is used in the server package). It turns out we don't need a lock in this case, but I like going through a method instead of accessing the field directly in this case.

Alternately, we could use separate `rpc.Contexts` for client and server operations so the struct can remain immutable and `LocalServer` would just be a normal field.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3209#-:-K3yAGHpT9l2m4zASw4b:-1701862825)*

**Comment by thundercw** [comment]
## benchmark:  `sql.BenchmarkBank`
I add some counters to count total execute times for 300 times checks:
```
counters:
tTrans = tTrans + transfers  //total transfers
tr = tr + aggr.read    // total read time                                           
tw = tw + aggr.write   //totol wriete time                                           
tt = tt + aggr.total   //totol txn time

Output:
d := time.Duration(tTrans)                                                  
log.Printf("total check: 300 times, ,total transfers: %d ", tTrans)         
log.Printf("total read time: %v, avg : %v", tr, tr/d)                       
log.Printf("total write time: %v, avg : %v ", tw, tw/d)                     
log.Printf("total txn time: %v, avg : %v ", tt, tt/d)   
```
## Deployment 1
1 range
1 replicas
1 nodes/(1 store) [common HDD]

### RPC
Server CPU: about 270%
2015/11/26 10:54:30 total check: 300 times, ,total transfers: 157638
2015/11/26 10:54:30 total read time: 4m56.837073257s, avg : 1.883029ms
2015/11/26 10:54:30 total write time: 9m46.755676146s, avg : 3.722171ms
2015/11/26 10:54:30 total txn time: 20m39.718216873s, avg : 7.864336ms
### Local Call
Server CPU: about 250%
2015/11/26 11:04:04 total check: 300 times, ,total transfers: 167963
2015/11/26 11:04:04 total read time: 4m51.061747721s, avg : 1.732892ms
2015/11/26 11:04:04 total write time: 9m37.03373322s, avg : 3.435481ms
2015/11/26 11:04:04 total txn time: 20m34.225353719s, avg : 7.348197ms

## Deployment 2
1 range
3 replicas
3 nodes/(1 store) [common HDD]

### RPC    
2015/11/26 09:04:26 total check: 300 times, ,total transfers: 109690
2015/11/26 09:04:26 total read time: 3m54.707022997s, avg : 2.13973ms
2015/11/26 09:04:26 total write time: 10m44.874090333s, avg : 5.879059ms
2015/11/26 09:04:26 total txn time: 21m45.487509801s, avg : 11.901609ms

### Local Call
2015/11/26 11:12:44 total check: 300 times, ,total transfers: 110101
2015/11/26 11:12:44 total read time: 3m57.776407846s, avg : 2.15962ms
2015/11/26 11:12:44 total write time: 10m37.325290455s, avg : 5.788551ms
2015/11/26 11:12:44 total txn time: 21m40.794962899s, avg : 11.81456ms

**Comment by thundercw** [comment]
@petermattis  @bdarnell  There is no strong reason why not exported like the other fields, now it is only referenced in RPC package.  The `Server.methods` may be changed after start and the `rpc.context` of client needs consistent with the server.

**Comment by petermattis** [comment]
FYI, I've forked this branch and rebased this to master. Still on my TODO list to look at the perf improvement again. See https://github.com/petermattis/cockroach/tree/pr/3209.

**Pull request closed without merging**
