### PR TITLE
ui: Empty state

### LINKED ISSUE #45264: ui: 'empty' and 'no results' states (statements, jobs, tables)
Update the `empty` and `no results` states. [Designs here](https://www.figma.com/file/uU9C1XSleeAu26CvTWwekX/obsrv_admin-ui-empty-states?node-id=2%3A3169):

- [x] Statement list `empty` and `no results` states
- [x] Statement list on Table detail page `empty` state
- [x] Job List `empty` and `no results` states
- [x] Table List `empty` state

### PR DESCRIPTION
**Pull request by vladlos**
tables empty state redesign, created reusable component for no results state

Resolves: #45264

Release justification: bug fixes and low-risk updates to new functionality

Release note (ui): new design of empty state on Jobs, Diagnostics, Statements and StatementsDetails pages

### CODE REVIEW

**Review by dhartunian — CHANGES_REQUESTED** [review]
> ui: Empty state

This is not descriptive enough. Please keep it to 50 chars but mention what was done.

I really like that this change moves a component from `src/views/app/...` into the upper level components directory. :clap: 

The commit message needs more detail.
I'd like to see:
- what the `Empty` component is and where we should use it. Is it only for tables, for instance, or can I use it anywhere?
- a list of components that the Empty component is now being used in
- discussion of new props being added to components that facilitate use of `Empty` component

> Reviewed 15 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45981#-:-M2ofD-q3--_lBqIvkQk:b-isy7wx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @elkmaster)

___
*[pkg/ui/src/util/docs.ts, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45981#-M2ofqNICCUws3qaSlHD:-M2ofqNICCUws3qaSlHE:b-fwi6rd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a47f3494c53f96eb674a51dfe0d2f2415de4784/pkg/ui/src/util/docs.ts#L35)):*
> ```XML
> export const adminUIAccess = docsURL("admin-ui-overview.html#admin-ui-access");
> export const statementDiagnostics = docsURLNoVersion("admin-ui-statements-page.html#diagnostics");
> export const databaseTable = docsURLNoVersion("admin-ui-databases-page.html");
> ```

Why are these links `noVersion`? I would assume we would link to the versioned one.
___
*[pkg/ui/src/views/databases/containers/tableDetails/index.tsx, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45981#-M2ogCq_5RjcVq08tb1_:-M2ogCq_5RjcVq08tb1a:b6o26ay) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a47f3494c53f96eb674a51dfe0d2f2415de4784/pkg/ui/src/views/databases/containers/tableDetails/index.tsx#L34)):*
> ```XML
> import { databaseDetails } from "../databaseSummary";
> import { Button, BackIcon } from "oss/src/components/button";
> import { databaseTable } from "oss/src/util/docs";
> ```

We need to stop using `oss/` as a prefix for imports. Import should always come from /src. The `oss` or `ccl` prefix is added by webpack. This is to allow `ccl` directory to override. Can you change just the ones in this PR for now? I will file a ticket to fix the rest.
___
*[pkg/ui/src/views/databases/containers/tableDetails/index.tsx, line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45981#-M2ogatEEgytLxQfeDZk:-M2ogatEEgytLxQfeDZl:bp7pna8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a47f3494c53f96eb674a51dfe0d2f2415de4784/pkg/ui/src/views/databases/containers/tableDetails/index.tsx#L103)):*
> ```XML
>       return statements.filter((statement: AggregateStatistics) => statement.label.indexOf(title) !== -1);
>     }
>     return [];
> ```

thanks for this, we should explore turning on strict null checks :thinking: 
___
*[pkg/ui/src/views/databases/containers/tableDetails/index.tsx, line 166 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45981#-M2oiH_x2U74lyx2JeNV:-M2oiH_x2U74lyx2JeNW:by5q00x) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a47f3494c53f96eb674a51dfe0d2f2415de4784/pkg/ui/src/views/databases/containers/tableDetails/index.tsx#L166)):*
> ```XML
>               </TabPane>
>               <TabPane tab="Statements" key="2">
>                 <StatementsSortedTable
> ```

Did you explore a different style of API where the `Empty` component wraps an existing component? We could have:

```
<Empty showWhen={statementsData.length === 0} ... >
  <StatementsSortedTable ... />
</Empty>
```

Then you can avoid having to implement the `if (empty) { return <Empty...` inside every other component.

What do you think?
___
*[pkg/ui/src/views/databases/containers/tableDetails/index.tsx, line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45981#-M2ohgw7BuRdFzVxXASl:-M2ohgw8AgTuwJ7hmjui:bqlbg3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a47f3494c53f96eb674a51dfe0d2f2415de4784/pkg/ui/src/views/databases/containers/tableDetails/index.tsx#L179)):*
> ```XML
>               </TabPane>
>               <TabPane tab="Grants" key="3">
>                 <GrantsSortedTable
> ```

Why doesn't this have `empty` prop?
___
*[pkg/ui/src/views/jobs/jobTable.tsx, line 161 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45981#-M2ohlMa7AIwtWh9CXcm:-M2ohlMa7AIwtWh9CXcn:bvhxcgp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a47f3494c53f96eb674a51dfe0d2f2415de4784/pkg/ui/src/views/jobs/jobTable.tsx#L161)):*
> ```XML
>           columns={jobsTableColumns}
>           renderNoResult={this.noJobResult()}
>           empty={_.isEmpty(jobs) && !this.props.isUsedFilter}
> ```

Why do we need `empty` and `renderNoResult`? Couldn't we do both with just the empty functionality?
___
*[pkg/ui/src/views/shared/components/sortabletable/index.tsx, line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45981#-M2ohxfrCYjbH7rbUJpk:-M2ohxfrCYjbH7rbUJpl:b-6rpuv2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a47f3494c53f96eb674a51dfe0d2f2415de4784/pkg/ui/src/views/shared/components/sortabletable/index.tsx#L17)):*
> ```XML
> import { DrawerComponent } from "../drawer";
> import "./sortabletable.styl";
> import Empty, { IEmptyProps } from "oss/src/components/empty/empty";
> ```

this import looks weird, no? can we just import from /components/empty?

**Comment by dhartunian** [comment]
One last comment: the change is failing the linter because of a missing Release justification.

**Comment by elkmaster** [comment]
> Did you explore a different style of API where the Empty component wraps an existing component? We could have…

In my opinion "wrapping" components should be used only when there is no other way, for example for real wrappers, like layout or anything that adds something before and\or after {children}. In current case it will just add unnecessary complexity.

> Why doesn’t this have empty prop?

Some screens have empty prop implementations as separated prs.

>  Why do we need empty and renderNoResult? Couldn’t we do both with just the empty functionality?

No result state is only for tables with filters, when we have data, but nothing is matching filter criteria. Maybe make sense to create another ticket for moving it out in component too.

**Review by dhartunian — COMMENTED** [review]
@elkmaster can you update the release note to explain exactly which pages on the site are changing. I assume it's just the 4 mentioned in the issue.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45981#-:-M3fpbuoB7Mv12djiQka:b-7iamxn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @elkmaster)

**Comment by elkmaster** [comment]
databases
diagnostics
jobs
statements

**Review by dhartunian — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r2, 8 of 8 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45981)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @elkmaster)

___
*[pkg/ui/src/components/empty/empty.tsx, line 36 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/45981#-M4VvK-b2RpfVNM4_mbe:-M4VvK-c9dqGMM6aqJUw:bcbeh0a) ([raw file](https://github.com/cockroachdb/cockroach/blob/faee5c4a79ac361a3cc50dfdef9f40d5a42a2f69/pkg/ui/src/components/empty/empty.tsx#L36)):*
> ```XML
>   backgroundImage,
> }: IEmptyProps) => (
>   <div className="cl-empty-view" style={{ backgroundImage: `url(${backgroundImage})` }}>
> ```

Is this currently overridden by any user of this component? Why not have it set in the CSS?

**Comment by elkmaster** [comment]
> Is this currently overridden by any user of this component? Why not have it set in the CSS?

Now it not used but I think I seen some designs with different images, so for easier customisation in future it was done with inline styles.

**Review by dhartunian — APPROVED** [review]
@elkmaster this looks good! thanks for the edits.

It looks like you have an edit to `yarn-vendor` that should not be there. Can you remove that, rebase and resolve conflicts so we can merge?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45981#-:-M5Ty9sFA-jwUuucK9u7:b-j1raam)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @elkmaster)

**Review by dhartunian — APPROVED** [review]
:lgtm: thanks for the update

> Reviewed 15 of 15 files at r5, 7 of 7 files at r6, 2 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45981#-:-M5XZFDcEsZxeK2WhuGq:b-5nh6mh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian and @elkmaster)

**Pull request merged**
