### PR TITLE
sql: use CommandResult for displaying ParameterStatus updates

### PR DESCRIPTION
**Pull request by otan**
We were previously sending ParameterStatus using a listener. This
is refactored to talk using CommandResult instead, with results only
being buffered if "Close()" is called. To do this, a new
`AppendParamStatusUpdate` function to `RestrictedCommandResult`.

Since setting vars live in `sessionDataMutator`, we add a new
`paramStatusUpdater` interface which uses the `RestrictedCommandResult`.
This var is reset each time we execute with an openTxn with the
CommandResult used for it.

Also renamed "StatusParam" to "ParamStatus", which is closer to the name
"ParameterStatus".

Release note: None

### CODE REVIEW

**Review by andreimatei — CHANGES_REQUESTED** [review]
Nit: No need for this in the commit msg "No release note as there is no functional difference."
Also "The existing pgwire tests still pass." Of course they pass, otherwise you wouldn't be sending the PR :).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45140#-:-M18Z4VJDvC2KRFn-ALY:bkc10rp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @otan)

___
*[pkg/sql/conn_executor.go, line 1651 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45140#-M18bAFIEd97a-fsqFwI:-M18bAFIEd97a-fsqFwJ:b2i7fx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8095486b55d0e6b9c7833307b54e6d31f19b0518/pkg/sql/conn_executor.go#L1651)):*
> ```Go
> // and writing up to the CommandComplete message.
> func (ex *connExecutor) execCopyIn(
> 	ctx context.Context, cmd CopyIn, res CommandResultCommBase,
> ```

do you really need this `res`?
___
*[pkg/sql/conn_executor_exec.go, line 825 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45140#-M18bE9C1PoyVZHs2QCW:-M18bE9C1PoyVZHs2QCX:b-cvhvyk) ([raw file](https://github.com/cockroachdb/cockroach/blob/8095486b55d0e6b9c7833307b54e6d31f19b0518/pkg/sql/conn_executor_exec.go#L825)):*
> ```Go
> // non-nil historicalTimestamp implies a ReadOnly rwMode.
> func (ex *connExecutor) beginTransactionTimestampsAndReadMode(
> 	ctx context.Context, s *tree.BeginTransaction, res RestrictedCommandResult,
> ```

do you really need the `res`?
___
*[pkg/sql/conn_executor_prepare.go, line 175 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45140#-M18_bVNB2knqYt4wb1H:-M18_bVNB2knqYt4wb1I:b-dcrvil) ([raw file](https://github.com/cockroachdb/cockroach/blob/8095486b55d0e6b9c7833307b54e6d31f19b0518/pkg/sql/conn_executor_prepare.go#L175)):*
> ```Go
> 	ex.statsCollector.reset(&ex.server.sqlStats, ex.appStats, &ex.phaseTimes)
> 	p := &ex.planner
> 	ex.resetPlanner(ctx, p, txn, ex.server.cfg.Clock.PhysicalTime() /* stmtTS */, stmt.NumAnnotations, res)
> ```

long line
___
*[pkg/sql/conn_executor_prepare.go, line 175 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45140#-M18akM34knyE9xggpOw:-M18akM34knyE9xggpOx:bhc35n3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8095486b55d0e6b9c7833307b54e6d31f19b0518/pkg/sql/conn_executor_prepare.go#L175)):*
> ```Go
> 	ex.statsCollector.reset(&ex.server.sqlStats, ex.appStats, &ex.phaseTimes)
> 	p := &ex.planner
> 	ex.resetPlanner(ctx, p, txn, ex.server.cfg.Clock.PhysicalTime() /* stmtTS */, stmt.NumAnnotations, res)
> ```

Does this guy ever need this res? Give it a no-op one and remove the new method arg and above.
___
*[pkg/sql/conn_io.go, line 635 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45140#-M18_3tR93OXlkeGgNy6:-M18_3tR93OXlkeGgNy7:b-y6dw8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/8095486b55d0e6b9c7833307b54e6d31f19b0518/pkg/sql/conn_io.go#L635)):*
> ```Go
> }
> 
> // CommandResultCommBase represents communication with the client for
> ```

This name... 
How about `ParamStatusSender`?
___
*[pkg/sql/conn_io.go, line 877 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45140#-M18aA7WEcE0bQrAxJZD:-M18_tp9-_9Ny1GAbpoG:b-uv4x3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/8095486b55d0e6b9c7833307b54e6d31f19b0518/pkg/sql/conn_io.go#L877)):*
> ```Go
> 
> // BufferParamStatus is part of the RestrictedCommandResult interface.
> func (r *bufferedCommandResult) BufferParamStatus(key string, val string) {}
> ```

I'd say either accumulate the key/value and give access to it, or `panic("unimplemented")`
___
*[pkg/sql/exec_util.go, line 1793 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45140#-M18Z_vnBtqqFYtFzEHx:-M18Z_vnBtqqFYtFzEHy:b-81j2x1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8095486b55d0e6b9c7833307b54e6d31f19b0518/pkg/sql/exec_util.go#L1793)):*
> ```Go
> 	defaults SessionDefaults
> 	settings *cluster.Settings
> 	// commResultComm communicates results through the CommandResult to the client.
> ```

name in comment doesn't match

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45140)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/sql/conn_executor.go, line 1651 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45140#-M18bAFIEd97a-fsqFwI:-M195hAe501FHQUUWtgL:b-sh6up4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8095486b55d0e6b9c7833307b54e6d31f19b0518/pkg/sql/conn_executor.go#L1651)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

do you really need this `res`?
</blockquote></details>

the base, yes. I want to send notices at one point (https://github.com/cockroachdb/cockroach/compare/master...otan-cockroach:buf_notice_2).
___
*[pkg/sql/conn_executor_exec.go, line 825 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45140#-M18bE9C1PoyVZHs2QCW:-M195moy44ow61AAI7EF:b-xaycks) ([raw file](https://github.com/cockroachdb/cockroach/blob/8095486b55d0e6b9c7833307b54e6d31f19b0518/pkg/sql/conn_executor_exec.go#L825)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

do you really need the `res`?
</blockquote></details>

yes, see above.
___
*[pkg/sql/conn_executor_prepare.go, line 175 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45140#-M18_bVNB2knqYt4wb1H:-M195aM7BzJTrkV2gMqL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8095486b55d0e6b9c7833307b54e6d31f19b0518/pkg/sql/conn_executor_prepare.go#L175)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

long line
</blockquote></details>

Done.
___
*[pkg/sql/conn_executor_prepare.go, line 175 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45140#-M18akM34knyE9xggpOw:-M195akn6Lbx75MpwNsB:b24qam) ([raw file](https://github.com/cockroachdb/cockroach/blob/8095486b55d0e6b9c7833307b54e6d31f19b0518/pkg/sql/conn_executor_prepare.go#L175)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Does this guy ever need this res? Give it a no-op one and remove the new method arg and above.
</blockquote></details>

yes, because I want to be able to send notices through this one too.
___
*[pkg/sql/conn_io.go, line 635 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45140#-M18_3tR93OXlkeGgNy6:-M1953QM44Hg7w1li41s:b-x5dkal) ([raw file](https://github.com/cockroachdb/cockroach/blob/8095486b55d0e6b9c7833307b54e6d31f19b0518/pkg/sql/conn_io.go#L635)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

This name... 
How about `ParamStatusSender`?
</blockquote></details>

I do want to re-use this for https://github.com/cockroachdb/cockroach/compare/master...otan-cockroach:buf_notice_2, so `ParamStatusSender` won't do.
___
*[pkg/sql/conn_io.go, line 877 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45140#-M18aA7WEcE0bQrAxJZD:-M195vpQ6MIT0NRJCGEy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8095486b55d0e6b9c7833307b54e6d31f19b0518/pkg/sql/conn_io.go#L877)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'd say either accumulate the key/value and give access to it, or `panic("unimplemented")`
</blockquote></details>

Done.
___
*[pkg/sql/exec_util.go, line 1793 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45140#-M18Z_vnBtqqFYtFzEHx:-M195Gf6CH93jQJAWZQr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8095486b55d0e6b9c7833307b54e6d31f19b0518/pkg/sql/exec_util.go#L1793)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

name in comment doesn't match
</blockquote></details>

Done.

**Review by andreimatei — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45140)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @otan)

___
*[pkg/sql/conn_executor.go, line 1651 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45140#-M18bAFIEd97a-fsqFwI:-M1CJO__65unO9qg-8QN:b-ymmyao) ([raw file](https://github.com/cockroachdb/cockroach/blob/8095486b55d0e6b9c7833307b54e6d31f19b0518/pkg/sql/conn_executor.go#L1651)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

the base, yes. I want to send notices at one point (https://github.com/cockroachdb/cockroach/compare/master...otan-cockroach:buf_notice_2).
</blockquote></details>

future plans should generally be left to the future :)
But even with that PR - do you really need to send notices from `execCopyIn`?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45140)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/sql/conn_executor.go, line 1651 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45140#-M18bAFIEd97a-fsqFwI:-M1CZLNG6C55i0YCxBHw:bxqvda9) ([raw file](https://github.com/cockroachdb/cockroach/blob/8095486b55d0e6b9c7833307b54e6d31f19b0518/pkg/sql/conn_executor.go#L1651)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

future plans should generally be left to the future :)
But even with that PR - do you really need to send notices from `execCopyIn`?
</blockquote></details>

I mean I'd rather leave that option open haha - seems annoying to debug if someone is adding it. Flexible either way; if you feel strongly about it I'll make it be silent instead.

**Review by andreimatei — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45140)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @otan)

___
*[pkg/sql/conn_executor.go, line 1651 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45140#-M18bAFIEd97a-fsqFwI:-M1CaVEwC2sLLrmkDUdb:b-jzmigt) ([raw file](https://github.com/cockroachdb/cockroach/blob/8095486b55d0e6b9c7833307b54e6d31f19b0518/pkg/sql/conn_executor.go#L1651)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

I mean I'd rather leave that option open haha - seems annoying to debug if someone is adding it. Flexible either way; if you feel strongly about it I'll make it be silent instead. 
</blockquote></details>

I see this passing of `res` everywhere as significant pollution, so I'd much rather keep it to a minimum. Because the more places we pass it through, the more I'd have to litigate the name - `res` doesn't seem appropriate.
But see below, maybe these arguments can go away from everywhere and then this point might be moot.
___
*[pkg/sql/conn_executor.go, line 2083 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45140#-M1CbCLM-UTXo7FUqYqM:-M1CbCLNBMVCcB9g5Ha2:byqdmtb) ([raw file](https://github.com/cockroachdb/cockroach/blob/203848e6f339b2cc7cb90ead42601f2b9c154caf/pkg/sql/conn_executor.go#L2083)):*
> ```Go
> 	stmtTS time.Time,
> 	numAnnotations tree.AnnotationIdx,
> 	res CommandResultCommBase,
> ```

I'd take out this arg from `resetPlanner()` unless there was a particular reason to put it here. You want to modify the `sessionDataMutator`, not the `planner`. The fact that the `planner` even knows about the `sessionDataMutator` is unfortunate. I'd assign `p.sessionDataMutator` explicitly at the beginning of executing each statement (in `execStmtInOpenState()` or such) - and then I think the proliferation of `res` everywhere can stop.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45140)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @otan)

___
*[pkg/sql/conn_executor.go, line 1651 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45140#-M18bAFIEd97a-fsqFwI:-M1Cd01QDeWTeCAKt4gs:bfj6k2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/8095486b55d0e6b9c7833307b54e6d31f19b0518/pkg/sql/conn_executor.go#L1651)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I see this passing of `res` everywhere as significant pollution, so I'd much rather keep it to a minimum. Because the more places we pass it through, the more I'd have to litigate the name - `res` doesn't seem appropriate.
But see below, maybe these arguments can go away from everywhere and then this point might be moot.
</blockquote></details>

I can change the name, but I need it in the planner to send notices. I guess the split makes it seem unnecessary but it is in the immediate follow up.

**Review by andreimatei — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45140)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @otan)

___
*[pkg/sql/conn_executor.go, line 1651 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45140#-M18bAFIEd97a-fsqFwI:-M1CeoMc9nCHdfvpVwvJ:b-w9rrr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8095486b55d0e6b9c7833307b54e6d31f19b0518/pkg/sql/conn_executor.go#L1651)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

I can change the name, but I need it in the planner to send notices. I guess the split makes it seem unnecessary but it is in the immediate follow up. 
</blockquote></details>

We really need to stop putting execution-related stuff in the `planner`. Can you put it in `runParams` instead?

If you want me to have more context than what's in this commit, I think that's a sign you've split the commits wrong. Just squash them.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45140)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/sql/conn_executor.go, line 1651 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45140#-M18bAFIEd97a-fsqFwI:-M1CfneH-NGyHnf0kiKW:boblp6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/8095486b55d0e6b9c7833307b54e6d31f19b0518/pkg/sql/conn_executor.go#L1651)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

We really need to stop putting execution-related stuff in the `planner`. Can you put it in `runParams` instead?

If you want me to have more context than what's in this commit, I think that's a sign you've split the commits wrong. Just squash them.
</blockquote></details>

Seems like I have to thread that through to DistSQL / Planning context. Is that okay? It also seems much more helpful to have it in a place more universally easy to access (i.e. my original desire to have it in the evalCtx), but it seems we prefer it as locked down as possible (which is fine, the abstraction boundaries and desires of others I'm, less familiar with).

Seemed like this PR's  would make sense on its own with some futureproofing for notices I was trying to do but looks like it didn't play out. We can discuss over it when I put the next PR over it.
___
*[pkg/sql/conn_executor.go, line 2083 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45140#-M1CbCLM-UTXo7FUqYqM:-M1Chmlx3owVkMciVuYy:bjdfth9) ([raw file](https://github.com/cockroachdb/cockroach/blob/203848e6f339b2cc7cb90ead42601f2b9c154caf/pkg/sql/conn_executor.go#L2083)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'd take out this arg from `resetPlanner()` unless there was a particular reason to put it here. You want to modify the `sessionDataMutator`, not the `planner`. The fact that the `planner` even knows about the `sessionDataMutator` is unfortunate. I'd assign `p.sessionDataMutator` explicitly at the beginning of executing each statement (in `execStmtInOpenState()` or such) - and then I think the proliferation of `res` everywhere can stop.
</blockquote></details>

I can remove the controversy of putting this inside resetPlanner in this PR, but it seemed to be killing two birds with one stone.

If it's controversial I can take it out for this PR and do the suggestion of `setting p.sessionDataMutator explicitly at the beginning of executing each statement (in execStmtInOpenState() or such)`. Personally feels like it's dirtier and more error prone, since you could mutate the session somewhere else by accident and not have the param status sent properly, but /shrug

**Comment by otan** [comment]
stripped out all the passing of res into everything, keeping it `CommandResultCommBase` so i can share the interface with `BufferNotice`, but if you feel strongly can name it `ParamStatusSender` instead, and have a separate interface for `BufferNotice` in the near future.

**Review by andreimatei — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45140#-:-M1R7BanC5udmpV--ToA:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @otan)

___
*[pkg/sql/conn_io.go, line 635 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45140#-M18_3tR93OXlkeGgNy6:-M1R6NHk5XMdQf-yDZam:b-xchxfi) ([raw file](https://github.com/cockroachdb/cockroach/blob/8095486b55d0e6b9c7833307b54e6d31f19b0518/pkg/sql/conn_io.go#L635)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

I do want to re-use this for https://github.com/cockroachdb/cockroach/compare/master...otan-cockroach:buf_notice_2, so `ParamStatusSender` won't do.
</blockquote></details>

I wouldn't introduce a new interface here for this. I'd define the method in `RestrictedCommandResult`, and then I'd define the interface in `sql` as `ParamStatusSender`.  And when the notices come, I'd define another interface for that also in `sql` - `Noticer` or something.
The fact that the comment on this interface seems nonsensical I think is a hint that some abstraction is not quite right: a command result already "represents communication with the client".
___
*[pkg/sql/conn_io.go, line 640 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45140#-M1R5pZKBzbxXZhfRyUc:-M1R5pZKBzbxXZhfRyUd:b-c4wvre) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a4cf166ec1f44c3b39ea2d59a53123c1b7898f1/pkg/sql/conn_io.go#L640)):*
> ```Go
> 	// BufferParamStatus buffers any updates to a parameter status.
> 	// This gets flushed only when the CommandResult is closed.
> 	BufferParamStatus(string, string)
> ```

I think `SetParamStatus` would be better. The buffering aspects of the command results are hidden from clients; that's what the rewind capabilities are supposed to abstract.

**Comment by otan** [comment]
___
*[pkg/sql/conn_io.go, line 640 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45140#-M1R5pZKBzbxXZhfRyUc:-M1R7uILDGU50ZND2Icl:b94qpb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a4cf166ec1f44c3b39ea2d59a53123c1b7898f1/pkg/sql/conn_io.go#L640)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think `SetParamStatus` would be better. The buffering aspects of the command results are hidden from clients; that's what the rewind capabilities are supposed to abstract.
</blockquote></details>

hmm, what about `AddParamStatusUpdate`? the problem for me is `Set` ignores the fact that multiple param status updates may be sent (even for the same key - which I think is possible).

**Review by andreimatei — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45140)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @otan)

___
*[pkg/sql/conn_io.go, line 640 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45140#-M1R5pZKBzbxXZhfRyUc:-M1RAmM_-BNj_6rkxFJm:bb7ohn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a4cf166ec1f44c3b39ea2d59a53123c1b7898f1/pkg/sql/conn_io.go#L640)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

hmm, what about `AddParamStatusUpdate`? the problem for me is `Set` ignores the fact that multiple param status updates may be sent (even for the same key - which I think is possible).
</blockquote></details>

sgtm

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45140)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/sql/conn_io.go, line 635 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45140#-M18_3tR93OXlkeGgNy6:-M1R7xCx4b2MF95Nb6s-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8095486b55d0e6b9c7833307b54e6d31f19b0518/pkg/sql/conn_io.go#L635)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I wouldn't introduce a new interface here for this. I'd define the method in `RestrictedCommandResult`, and then I'd define the interface in `sql` as `ParamStatusSender`.  And when the notices come, I'd define another interface for that also in `sql` - `Noticer` or something.
The fact that the comment on this interface seems nonsensical I think is a hint that some abstraction is not quite right: a command result already "represents communication with the client".
</blockquote></details>

Done.
___
*[pkg/sql/conn_io.go, line 640 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45140#-M1R5pZKBzbxXZhfRyUc:-M1RPG6gBlIyeLDSno78:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a4cf166ec1f44c3b39ea2d59a53123c1b7898f1/pkg/sql/conn_io.go#L640)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

sgtm
</blockquote></details>

Done.

**Comment by andreimatei** [comment]
feel free to merge

**Comment by otan** [comment]
bors r=andreimatei

**Comment by otan** [comment]
bors r=andreimatei

**Pull request merged**
