### PR TITLE
flowinfra: make max_running_flows default depend on the number of CPUs

### PR DESCRIPTION
**Pull request by yuzefovich**
We think that it makes sense to scale the default value for
`max_running_flows` based on how beefy the machines are, so we make it a
multiple of the number of available CPU cores. We do so in
a backwards-compatible fashion by treating the positive values of
`sql.distsql.max_running_flows` as absolute values (the previous
meaning) and the negative values as multiples of the number of the CPUs.

The choice of 128 as the default multiple is driven by the old default
value of 500 and is such that if we have 4 CPUs, then we'll get the value
of 512, pretty close to the old default.

Informs: #34229.

Release note (ops change): The meaning of
`sql.distsql.max_running_flows` cluster setting has been extended so
that when the value is negative, it would be multiplied by the number of
CPUs on the node to get the maximum number of concurrent remote flows on
the node. The default value is -128, meaning that on a 4 CPU machine we
will have up to 512 concurrent remote DistSQL flows, but on a 8 CPU
machine up to 1024. The previous default was 500.

### CODE REVIEW

**Review by michae2 — COMMENTED** [review]
If we're changing the default to be a multiple of cores, it might be simpler semantically to change the meaning of the variable to be per-core, and then make the default a constant 128.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71787#-:-MmYeubh6tks_Xzy9PfQ:bx7ror4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Review by RaduBerinde — COMMENTED** [review]
Yeah it would be nice to make the 128 itself configurable.

What I did elsewhere (https://github.com/cockroachdb/cockroach/pull/70328)  was keep the "absolute" meaning for positive values and add a "per-CPU" meaning for negative value (e.g. 500 means limit=500, -100 means 100*GOMAXPROCS). It's a bit hacky but handles previously changed values well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71787#-:-MmYzNiaEurK5tz08bqY:b-81dko4)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by michae2 — COMMENTED** [review]
> What I did elsewhere (#70328) was keep the "absolute" meaning for positive values and add a "per-CPU" meaning for negative value (e.g. 500 means limit=500, -100 means 100*GOMAXPROCS).

:exploding_head: Nice.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71787#-:-MmZ-Aq16asvb8HRdKqt:b-p5e78j)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by yuzefovich — COMMENTED** [review]
Oh, these are interesting ideas, implemented both suggestions.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71787#-:-MmYuXQe8hd7INtws0j3:b-txyezx)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by michae2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71787#-:-MmZJOIt5rY2hhS_FEDN:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
blathers backport 21.2

**Pull request merged**
