### PR TITLE
storage: Convert 'nodeStatus' enumeration to proto

### PR DESCRIPTION
**Pull request by mrtracy**
Converts the nodeStatus enumeration (used by the store pool and
allocator) to a protocol buffer. The purpose is that we intend to expose
this information the Admin UI in a subsequent commit.

Works towards #17840

### CODE REVIEW

**Comment by a-robinson** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/liveness.proto, line 54 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20086#-Kz4MOcCCpXYPc0lkiw0:-Kz4MOcCCpXYPc0lkiw1:brs4b3p) ([raw file](https://github.com/cockroachdb/cockroach/blob/4260be51052b7c35a0b8e5d1c9880fef4c5697b4/pkg/storage/liveness.proto#L54)):*
> ```protobuf
>   LIVE = 3;
>   // DECOMMISSIONING indicates a node that is in the decommissioning process.
>   DECOMMISSIONING = 5;
> ```

Why not 4?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20086)*

**Comment by a-robinson** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20086#-:-Kz4NLMYaVkChDZXyzlm:bnfp4nl)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20086#-:-Kz4ZS3PfXAuSJ41lDdh:bnfp4nl)*

**Comment by mrtracy** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/liveness.proto, line 54 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20086#-Kz4MOcCCpXYPc0lkiw0:-Kz4wGlGXJchquh-MWuH:bfgka95) ([raw file](https://github.com/cockroachdb/cockroach/blob/4260be51052b7c35a0b8e5d1c9880fef4c5697b4/pkg/storage/liveness.proto#L54)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Why not 4?
</blockquote></details>

https://youtu.be/xOrgLj9lOwk?t=128

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20086)*

**Pull request merged**
