### PR TITLE
dev: add ./dev ui lint subcommand

### PR DESCRIPTION
**Pull request by sjbarag**
Sibling to #77710, in which a `./dev ui lint` subcommand is added to run static checks on UI repos.  Specifically:

* In pkg/ui/workspaces/db-console:
  * stylint (linting for CSS and several "compiles to CSS" dialects)
  * eslint (linting for JavaScript and TypeScript)
  * prettier (through eslint; formatting for JavaScript and TypeScript)
* In pkg/ui/workspaces/cluster-ui:
  * eslint (linting for JavaScript and TypeScript)
  * prettier (through eslint; formatting for JavaScript and TypeScript)
  * tsc (the TypeScript compiler, for type-checking only)

### CODE REVIEW

**Review by rickystewart — CHANGES_REQUESTED** [review]
Looks like you need to `dev gen bazel` and just tweak the `dev` tests and then you'll be all set 👍

**Comment by sjbarag** [comment]
> Looks like you need to `dev gen bazel` and just tweak the `dev` tests and then you'll be all set 👍

Fixed!  Thanks for the review — I had a few silly typos in the tests 🤦

**Review by rickystewart — APPROVED** [review]
Looks like one more little lint thing to address:

```
------- Stdout: -------
=== RUN   TestLint/TestGofmtSimplify
=== PAUSE TestLint/TestGofmtSimplify
=== CONT  TestLint/TestGofmtSimplify
=== CONT  TestLint/TestGofmtSimplify
    lint_test.go:1332:
        /go/src/github.com/cockroachdb/cockroach/pkg/cmd/dev/ui.go
        diff -u /go/src/github.com/cockroachdb/cockroach/pkg/cmd/dev/ui.go.orig /go/src/github.com/cockroachdb/cockroach/pkg/cmd/dev/ui.go
        --- /go/src/github.com/cockroachdb/cockroach/pkg/cmd/dev/ui.go.orig  2022-03-15 16:19:40.943675533 +0000
        +++ /go/src/github.com/cockroachdb/cockroach/pkg/cmd/dev/ui.go  2022-03-15 16:19:40.943675533 +0000
        @@ -217,7 +217,7 @@
                 "//pkg/ui:lint",
               }
               args = append(args,
        -        d.getTestOutputArgs(false /* stream */, isVerbose, false /* showLogs */)...
        +        d.getTestOutputArgs(false /* stream */, isVerbose, false /* showLogs */)...,
               )
               logCommand("bazel", args...)
    --- FAIL: TestLint/TestGofmtSimplify (17.90s)
```

**Comment by sjbarag** [comment]
Gah I'm the worst.  Good catch — should be fixed now.

**Pull request merged**
