### PR TITLE
roachtest: allow specifying a sample rate of roachtests to run

### LINKED ISSUE #105386: roachtest: ability run a sample of roachtests
Currently, when developing features across roachtest/roachprod, it is often necessary to run the nightly suite to ensure nothing has broken. This is time consuming and costly. 

We could mitigate this by being able to specify a percentage of tests to run randomly, to be sampled after the name and tag filters. e.g. `roachtest run --sample-pct 0.25` to run a 1/4 of all matching tests. 

Considerations:
- we should try to ensure coverage across the range of existing tests when sampling (e.g. across teams, types)
- TeamCity logging would need to be emitted to report skipping of tests due to sampling

Another approach is to specify certain tests as `canary` tests via a tag, a representative subset to ensure coverage, however there are 100s of existing tests, and identifying good ones will be a time consuming exercise.

### PR DESCRIPTION
**Pull request by smg260**
This PR allows users to randomly run a subset of roachtests via the `select-probability` flag to `roachtest run`. The select takes place after any tag or name filters.

Furthermore, the initial default behaviour is to include at least one test from each prefix, so the effective probability will be higher. At a later date, we can choose to expose the boolean to disable this behaviour, in which case the probability will apply to across all tests. 

Appropriate print statements for TeamCity have also been added.

Release note: none
Epic: none
Resolves: #105386

### CODE REVIEW

**Comment by smg260** [comment]
[TeamCity Job](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10643614?hideProblemsFromDependencies=false&expandBuildTestsSection=true&hideTestsFromDependencies=false&expandBuildChangesSection=true) running with `select-probability=0.01`

Note there are far more than 1% of tests running, due to the 1 per prefix minimum

**Review by renatolabs — APPROVED** [review]
:lgtm:

Nice feature! Minor comments.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105388#-:-NYcg0XTCPUas2Ua5HGf:bhc4frg)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @smg260, and @srosenberg)

___
*[`build/teamcity/cockroach/nightlies/roachtest_nightly_gce.sh` line 10 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105388#-NYcfwuE0dAW3sYbPCR0:-NYcfwuE0dAW3sYbPCR1:by4y9ey) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cbdf6b7733ff062da608071289676f1e139d5be/build/teamcity/cockroach/nightlies/roachtest_nightly_gce.sh#L10)):*
> ```Shell
> source "$dir/teamcity-bazel-support.sh"  # For run_bazel
> 
> BAZEL_SUPPORT_EXTRA_DOCKER_ARGS="-e LITERAL_ARTIFACTS_DIR=$root/artifacts -e BUILD_VCS_NUMBER -e CLOUD -e COCKROACH_DEV_LICENSE -e TESTS -e COUNT -e GITHUB_API_TOKEN -e GITHUB_ORG -e GITHUB_REPO -e GOOGLE_EPHEMERAL_CREDENTIALS -e GOOGLE_KMS_KEY_A -e GOOGLE_KMS_KEY_B -e GOOGLE_CREDENTIALS_ASSUME_ROLE -e GOOGLE_SERVICE_ACCOUNT -e SLACK_TOKEN -e TC_BUILDTYPE_ID -e TC_BUILD_BRANCH -e TC_BUILD_ID -e TC_SERVER_URL -e SELECT_PROBABILITY" \
> ```

Should we also add this to the other builds (FIPS, AWS, ...)?
___
*[`pkg/cmd/roachtest/main.go` line 331 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105388#-NYccNW_EL2WeyWCHw4x:-NYccNW_EL2WeyWCHw4y:bsk3b93) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5d72e0945942b2656ea2a18fc744b532f800991/pkg/cmd/roachtest/main.go#L331)):*
> ```Go
> 	runCmd.Flags().Float64Var(
> 		&selectProbability, "select-probability", 1.0,
> 		"the probability of a matched tests to run (default 1.0). Note: this will return at least one test per prefix.")
> ```

Nit: the `default 1` part is already added by cobra, so we don't need to include it in the description string.
___
*[`pkg/cmd/roachtest/main.go` line 697 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105388#-NYccZmW4VKzdqVj1fmX:-NYccZmW4VKzdqVj1fmY:b-ocqgqo) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5d72e0945942b2656ea2a18fc744b532f800991/pkg/cmd/roachtest/main.go#L697)):*
> ```Go
> // TODO(smg260): Perhaps expose `atLeastOnePerPrefix` via CLI
> func selectSpecs(
> 	specs []registry.TestSpec, samplePct float64, atLeastOnePerPrefix bool, print bool,
> ```

This function also relies on the `specs` being sorted by name, right? Where does the sorting happen? Might be worth adding that assumption to the comments too.

**Review by smg260 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105388)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @herkolategan, @renatolabs, and @srosenberg)

___
*[`build/teamcity/cockroach/nightlies/roachtest_nightly_gce.sh` line 10 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105388#-NYcfwuE0dAW3sYbPCR0:-NYcleUj6eJ61F55TJLp:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cbdf6b7733ff062da608071289676f1e139d5be/build/teamcity/cockroach/nightlies/roachtest_nightly_gce.sh#L10)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Should we also add this to the other builds (FIPS, AWS, ...)?
</blockquote></details>

Done
___
*[`pkg/cmd/roachtest/main.go` line 331 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105388#-NYccNW_EL2WeyWCHw4x:-NYclkmJ5JfQx50_3sOM:b-sk8x3j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5d72e0945942b2656ea2a18fc744b532f800991/pkg/cmd/roachtest/main.go#L331)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Nit: the `default 1` part is already added by cobra, so we don't need to include it in the description string.
</blockquote></details>

Ah thanks.
___
*[`pkg/cmd/roachtest/main.go` line 697 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105388#-NYccZmW4VKzdqVj1fmX:-NYclmexEgemAFH238Qc:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5d72e0945942b2656ea2a18fc744b532f800991/pkg/cmd/roachtest/main.go#L697)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

This function also relies on the `specs` being sorted by name, right? Where does the sorting happen? Might be worth adding that assumption to the comments too.
</blockquote></details>

Good idea. Done.

**Comment by smg260** [comment]
TFTR
bors r=renatolabs

**Pull request merged**
