### PR TITLE
sql: add system.hot_ranges table

### PR DESCRIPTION
**Pull request by koorosh**
This change creates hot_ranges system table that will
store information about historical hot ranges in
aggregated way.
This patch doesn't include changes required for
tenants tables.

Release note: None

### CODE REVIEW

**Review by Santamaura — COMMENTED** [review]
It :lgtm: but I'd like someone with more familiarity in this area to review

> Reviewed 46 of 47 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80096#-:-N0gs4y54tiEq31yMaeG:bvrwdhv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @koorosh and @zachlite)

___
*[`pkg/sql/logictest/testdata/logic_test/distsql_enum` line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80096#-N0grBpK-3ZkduNwl3MS:-N0grBpLBSICnh1E86K2:bygvm58) ([raw file](https://github.com/cockroachdb/cockroach/blob/68f335c3e978722485507596cbe53e736c4a2cb6/pkg/sql/logictest/testdata/logic_test/distsql_enum#L73)):*
> ```
> ----
> │
> └ Node 2
> ```

Could you clarify why we remove this?

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80096)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Santamaura and @zachlite)

___
*[`pkg/sql/logictest/testdata/logic_test/distsql_enum` line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80096#-N0grBpK-3ZkduNwl3MS:-N0patRfBrS923JLwy37:b-cpzf4b) ([raw file](https://github.com/cockroachdb/cockroach/blob/68f335c3e978722485507596cbe53e736c4a2cb6/pkg/sql/logictest/testdata/logic_test/distsql_enum#L73)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

Could you clarify why we remove this?
</blockquote></details>

Good catch! Reverted this change. Thanks!

**Comment by irfansharif** [comment]
We're meeting next week to discuss internal interfaces for #76895, some of which I suspect will have implications for the schema here (especially if we are to work towards multi-tenancy as a goal for 22.2). I'll defer to youse for what we want to do with this PR, but if the intent was to help with prototyping things in earnest, in that past we've used long-lived branches until we have a clearer idea of what's needed before checking things in -- see [here](https://github.com/cockroachdb/cockroach/pulls?q=is%3Apr+is%3Aclosed+%22%5Bprototype%5D%22+in%3Atitle++author%3Airfansharif) and [here](https://github.com/cockroachdb/cockroach/pulls?q=is%3Apr+is%3Aclosed+%22%5Bprototype%5D%22+in%3Atitle++author%3Aarulajmani+) between me and Arul.

It can be faster too, you're not too worried about CI/bors and the like.

**Review by koorosh — COMMENTED** [review]
You're right, and this PR won't be merged until the table schema and everything around will be agreed upon. 
I'll set it as a draft PR to make it clear!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80096#-:-N0puxiP7p17gpZ8IXzO:b-a76ivm)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Santamaura and @zachlite)

**Comment by koorosh** [comment]
Closing as not actual anymore.

**Pull request closed without merging**
