### PR TITLE
Allow fast path insert into unique indices with implicit partitioning columns under read-committed

### PR DESCRIPTION
**Pull request by mw5h**
See commit messages for details.

### CODE REVIEW

**Review by DrewKimball — COMMENTED** [review]
BTW, @mgartner has a nice way to generate a PR message using commits, described [here](https://github.com/cockroachdb/cockroach/pull/96045#pullrequestreview-1331533626).

> Reviewed 1 of 1 files at r1, 8 of 8 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126504#-:-O0kMLYx4q7Cgj-dH7j0:bws9x5a)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @mw5h)

___
*[`-- commits` line 14 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126504#-O0kMyJN6WKyUSB_U2qA):*
Maybe just a Reviewable artifact, but it looks like a commit was duplicated, or something.
___
*[`pkg/sql/insert_fast_path.go` line 220 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126504#-O0kUsio3UD9zFhdYrVU:-O0kUsio3UD9zFhdYrVV:b-px6w3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/2820ec3b1fefc8df0cf0320aa4efe73400c2ce53/pkg/sql/insert_fast_path.go#L220)):*
> ```Go
> 				if c.Locking.Form == tree.LockPredicate {
> 					if !isInputRow {
> 						err := row.PutUniqLock(ctx, &r.ti.putter, c.Locking.WaitPolicy, span.Key, r.traceKV)
> ```

I believe this will execute the unique checks for the other partitions in the same batch as the insert, rather than with other unique checks / FK checks. Is that intentional? If so, we should call it out in a comment here.

[nit] Along the lines of the above comment, I think it might be helpful to inline the logic from `PutUniqueLock` here unless there's some dependency issue, so it's clear what request we're sending and in what batch. It's fine if you think it's better this way, though.
___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 192 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126504#-O0kS_rj12adGRXqnrrd:-O0kS_rk3PzMJfbQMf4z:b-ea7jh2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2820ec3b1fefc8df0cf0320aa4efe73400c2ce53/pkg/sql/opt/exec/execbuilder/mutation.go#L192)):*
> ```Go
> 		// If there is a unique index with a implicit partitioning columns, the fast
> 		// path can write tombstones to lock the row in all partitions.
> 		allowPredicateLocks := execFastPathCheck.ReferencedTable.Unique(execFastPathCheck.CheckOrdinal).HasIndexWithImplicitPartitioningColumn()
> ```

[nit] Since we have access to the index here, is it necessary to add `HasIndexWithImplicitPartitioningColumn`? Could we just check if `ImplicitPartitioningColumnCount() > 0` instead?
___
*[`pkg/sql/opt/exec/execbuilder/relational.go` line 3141 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126504#-O0kW-FcEv68PiC672rF:-O0kW-FcEv68PiC672rG:b-2vodqp) ([raw file](https://github.com/cockroachdb/cockroach/blob/2820ec3b1fefc8df0cf0320aa4efe73400c2ce53/pkg/sql/opt/exec/execbuilder/relational.go#L3141)):*
> ```Go
> }
> 
> // TODO: Delete this function once predicate locks are universally supported.
> ```

[nit] Is there an issue we can associate the TODO with, like `TODO(#foo):`?

**Review by DrewKimball — COMMENTED** [review]
Nice work figuring this out!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126504#-:-O0kYNk9El3EE1crW34w:b-dzw8m1)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @mw5h)

**Review by michae2 — COMMENTED** [review]
Awesome!! :fire: This is tricky stuff!

It's very satisfying that the error message for the tombstone CPut works exactly for the whole INSERT statement!

> Reviewed 1 of 1 files at r1, 8 of 8 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126504#-:-O0kbQM4Alqi_IldCbXT:b67vnx)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mw5h)

___
*[`-- commits` line 47 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126504#-O0kdEEE-CO7-PwTIfan):*
nit: Maybe add "when using the insert fast path" to make it clear when it applies.
___
*[`pkg/sql/insert_fast_path.go` line 220 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126504#-O0kUsio3UD9zFhdYrVU:-O0k_nx-5KOJePug_QOI:bql3526) ([raw file](https://github.com/cockroachdb/cockroach/blob/2820ec3b1fefc8df0cf0320aa4efe73400c2ce53/pkg/sql/insert_fast_path.go#L220)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I believe this will execute the unique checks for the other partitions in the same batch as the insert, rather than with other unique checks / FK checks. Is that intentional? If so, we should call it out in a comment here.

[nit] Along the lines of the above comment, I think it might be helpful to inline the logic from `PutUniqueLock` here unless there's some dependency issue, so it's clear what request we're sending and in what batch. It's fine if you think it's better this way, though.
</blockquote></details>

I was wondering about this, too. I'm guessing it's because the logic to handle the response is not the same as in `runUniqChecks` (because the tombstone CPut error message can simply become the statement error message) so it doesn't make sense to include in the `uniqBatch`. Agree that a comment would help.
___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 190 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126504#-O0kQ-M-8wHu22WVQIlg:-O0kQ-M-8wHu22WVQIlh:ba04v0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/2820ec3b1fefc8df0cf0320aa4efe73400c2ce53/pkg/sql/opt/exec/execbuilder/mutation.go#L190)):*
> ```Go
> 		execFastPathCheck.CheckOrdinal = c.CheckOrdinal
> 
> 		// If there is a unique index with a implicit partitioning columns, the fast
> ```

typo: "implicit" instead of "a implicit"
___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 192 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126504#-O0kS_rj12adGRXqnrrd:-O0k_aN68-XQ2TxZ4x7o:b-57qkq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2820ec3b1fefc8df0cf0320aa4efe73400c2ce53/pkg/sql/opt/exec/execbuilder/mutation.go#L192)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Since we have access to the index here, is it necessary to add `HasIndexWithImplicitPartitioningColumn`? Could we just check if `ImplicitPartitioningColumnCount() > 0` instead?
</blockquote></details>

Is there a reason we can't always use `true` here? Oh, right, is it because this tombstone technique only works for single-row predicate locks, and unique checks from `UNIQUE WITHOUT INDEX` might require range predicate locks? :thinking:

I wonder if checking for implicit partitioning is enough to always prevent range predicate locks? For example, would it catch something like this? (Which I think will have a unique check for the `UNIQUE WITHOUT INDEX (b)` that uses the implicitly-partitioned index on (b, c).)

```sql
SET experimental_enable_unique_without_index_constraints = true;
SET experimental_enable_implicit_column_partitioning = true;

CREATE TABLE abc (
  a INT NOT NULL CHECK (a IN (4, 5, 6)),
  b INT NOT NULL,
  c INT NOT NULL,
  INDEX (b, c),
  UNIQUE WITHOUT INDEX (b)
) PARTITION ALL BY LIST (a) (
  PARTITION p1 VALUES IN ((4)),
  PARTITION p2 VALUES IN ((5)),
  PARTITION p3 VALUES IN ((6))
);
EXPLAIN INSERT INTO abc VALUES (6, 7, 8);
```
___
*[`pkg/sql/opt/exec/execbuilder/relational.go` line 3143 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126504#-O0kalfc7QjM_7Tf1wMs:-O0kalfc7QjM_7Tf1wMt:b-sthjcg) ([raw file](https://github.com/cockroachdb/cockroach/blob/2820ec3b1fefc8df0cf0320aa4efe73400c2ce53/pkg/sql/opt/exec/execbuilder/relational.go#L3143)):*
> ```Go
> // TODO: Delete this function once predicate locks are universally supported.
> func (b *Builder) buildLocking(toLock opt.TableID, locking opt.Locking) (opt.Locking, error) {
> 	return b.buildLockingImpl(toLock, locking, false)
> ```

nit: Usually literal arguments are decorated with a comment like `..., false /* allowPredicateLocks */)`.
___
*[`pkg/sql/row/locking.go` line 85 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126504#-O0kciNx3zy53FzbU64D:-O0kciNx3zy53FzbU64E:bp03p9z) ([raw file](https://github.com/cockroachdb/cockroach/blob/2820ec3b1fefc8df0cf0320aa4efe73400c2ce53/pkg/sql/row/locking.go#L85)):*
> ```Go
> ) error {
> 	if waitPolicy != tree.LockWaitBlock {
> 		return errors.Errorf("Non-blocking predicate locks are not implemented")
> ```

Could this check be moved to `buildLockingImpl`?
___
*[`pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_read_committed` line 223 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126504#-O0mB24E2KqplXF8S2Pq:-O0mB24E2KqplXF8S2Pr:b-suvi6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/2820ec3b1fefc8df0cf0320aa4efe73400c2ce53/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_read_committed#L223)):*
> ```
> 
> statement async conflict error pgcode 23505 pq: duplicate key value violates unique constraint "university_pkey"
> INSERT INTO university VALUES ('CMU', 'Chippewas', '97858');
> ```

Haha, I appreciate this!

**Review by mw5h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126504)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 192 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126504#-O0kS_rj12adGRXqnrrd:-O0nzSTKB7mVCKkfL_mJ:b90kfku) ([raw file](https://github.com/cockroachdb/cockroach/blob/2820ec3b1fefc8df0cf0320aa4efe73400c2ce53/pkg/sql/opt/exec/execbuilder/mutation.go#L192)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Is there a reason we can't always use `true` here? Oh, right, is it because this tombstone technique only works for single-row predicate locks, and unique checks from `UNIQUE WITHOUT INDEX` might require range predicate locks? :thinking:

I wonder if checking for implicit partitioning is enough to always prevent range predicate locks? For example, would it catch something like this? (Which I think will have a unique check for the `UNIQUE WITHOUT INDEX (b)` that uses the implicitly-partitioned index on (b, c).)

```sql
SET experimental_enable_unique_without_index_constraints = true;
SET experimental_enable_implicit_column_partitioning = true;

CREATE TABLE abc (
  a INT NOT NULL CHECK (a IN (4, 5, 6)),
  b INT NOT NULL,
  c INT NOT NULL,
  INDEX (b, c),
  UNIQUE WITHOUT INDEX (b)
) PARTITION ALL BY LIST (a) (
  PARTITION p1 VALUES IN ((4)),
  PARTITION p2 VALUES IN ((5)),
  PARTITION p3 VALUES IN ((6))
);
EXPLAIN INSERT INTO abc VALUES (6, 7, 8);
```
</blockquote></details>

```
demo@127.0.0.1:26257/demoapp/movr> SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL READ COMMITTED;
SET

Time: 1ms total (execution 1ms / network 0ms)

demo@127.0.0.1:26257/demoapp/movr> EXPLAIN INSERT INTO abc VALUES (6, 7, 8);
ERROR: unimplemented: explicit unique checks are not yet supported under read committed isolation
SQLSTATE: 0A000
HINT: You have attempted to use a feature that is not yet implemented.
See: https://go.crdb.dev/issue-v/110873/v24.2
```

**Review by mw5h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126504)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @DrewKimball, @herkolategan, @michae2, and @msbutler)

___
*[`-- commits` line 14 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126504#-O0kMyJN6WKyUSB_U2qA):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Maybe just a Reviewable artifact, but it looks like a commit was duplicated, or something.
</blockquote></details>

I think it's just Reviewable.
___
*[`pkg/sql/insert_fast_path.go` line 220 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126504#-O0kUsio3UD9zFhdYrVU:-O0oSHVJ2u4jgX6OAbB5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2820ec3b1fefc8df0cf0320aa4efe73400c2ce53/pkg/sql/insert_fast_path.go#L220)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

I was wondering about this, too. I'm guessing it's because the logic to handle the response is not the same as in `runUniqChecks` (because the tombstone CPut error message can simply become the statement error message) so it doesn't make sense to include in the `uniqBatch`. Agree that a comment would help.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/exec/execbuilder/relational.go` line 3141 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126504#-O0kW-FcEv68PiC672rF:-O0oSJOu2C5PguzeoUpc:b-j2zdsn) ([raw file](https://github.com/cockroachdb/cockroach/blob/2820ec3b1fefc8df0cf0320aa4efe73400c2ce53/pkg/sql/opt/exec/execbuilder/relational.go#L3141)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Is there an issue we can associate the TODO with, like `TODO(#foo):`?
</blockquote></details>

There isn't yet an issue for predicate locks, though maybe I should file one.

**Review by DrewKimball — APPROVED** [review]
:LGTM:

> Reviewed 1 of 1 files at r8, 4 of 8 files at r9, 10 of 10 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126504#-:-O0pBOe58emhRNwuVtJ7:bmxilld)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @herkolategan, @msbutler, and @mw5h)

___
*[`pkg/sql/insert_fast_path.go` line 226 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/126504#-O0pBGG_10oaNNvGlUC1:-O0pBGG_10oaNNvGlUC2:b-4dmofp) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a82ae6f4a32fc38a0864d56e76659ffb6c07828/pkg/sql/insert_fast_path.go#L226)):*
> ```Go
> 				if c.Locking.Form == tree.LockPredicate {
> 					if !isInputRow {
> 						r.ti.putter.CPut(span.Key, nil, nil)
> ```

Did you mean to remove the tracing messages from before? Did it turn out that we already write to logs for `CPut`?

**Comment by mw5h** [comment]
> Did you mean to remove the tracing messages from before? Did it turn out that we already write to logs for `CPut`?

I did because I thought there was already tracing around the CPut, but I was mistaken.

**Review by michae2 — APPROVED** [review]
:lgtm: Very nice!

> Reviewed 1 of 1 files at r8, 4 of 8 files at r9, 6 of 10 files at r11, 4 of 4 files at r12, 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126504#-:-O0rJKR66DwpzUoL792i:b-kerl87)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DarrylWong, @DrewKimball, @herkolategan, @msbutler, and @mw5h)

**Pull request merged**
