### PR TITLE
cli: use tenant specific default store path on SQL nodes

### LINKED ISSUE #72518: multitenant: unable to start secondary tenant pod with single node cluster
**Describe the problem**

When looking to start a single node cluster with a secondary tenant, I'm running into the following error:
```
ERROR: could not cleanup temporary directories from record file: could not lock temporary directory /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/cockroach-data/cockroach-temp699668176, may still be in use: resource temporarily unavailable
Failed running "mt start-sql"
```

It goes away when `rm -rf`-ing the directory; are we forgetting to clean up somewhere? I think it was previously seen in https://github.com/cockroachdb/cockroach/issues/71269#issuecomment-937945362.

**To Reproduce**

```
# start the host tenant
make buildshort; rm -rf cockroach-data; cockroachshort start-single-node --insecure --logtostderr=INFO --accept-sql-without-tls

# create the tenant
cockroach sql --insecure -e 'select crdb_internal.create_tenant(123);'

# start the tenant pod
rm -rf logs; cockroachshort mt start-sql --insecure --tenant-id 123 --http-addr 127.0.0.1:8081 --kv-addrs 127.0.0.1:26257 --sql-addr 127.0.0.1:36257 --log-dir=logs/mt-123 --logtostderr=INFO
```

### PR DESCRIPTION
**Pull request by aliher1911**
Previously `mt start-sql` command defaulted store to cockroach-data.
This was causing problems if server and sql pods are running on the same
host and share disk. SQL pod needs to track its temp dirs and that is
bound to first configured store.
To address this, this patch adds are command pre-run callback to set
different path if --store was not explicitly provided. Default path is
cockroach-data-tenant-X where X is tenant ID.

Release note: None

Fixes #72518

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Where are the unit tests for this change?

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72819#-:-MoeLZbZ0SZaTk9BYnY2:b-2wl2ii)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

**Review by aliher1911 — COMMENTED** [review]
Thanks for the read @knz, I wanted to just verify if this approach to having conditional defaults looks sound before diving in writing a tests as they seem to be more elaborate than change itself.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72819#-:-Moh3A2r10HUhc7XY5-_:b-bil0l8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

**Review by knz — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72819)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

**Review by stevendanna — APPROVED** [review]
Nice, thanks!  Might be worth double-checking that this cc is aware of this change, in case they need to change any of their automation.

**Review by jaylim-crl — COMMENTED** [review]
One small note: we may want to update the help text too. It's currently showing the following:

```

                                                    Commas are forbidden in all values, since they are used to separate fields.
                                                    Also, if you use equal signs in the file path to a store, you must use the
                                                    "path" field label.
                                                    (default --store=path=/cockroach/cockroach-data)
```

The default won't apply to tenants since we do the override.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72819#-:-Mp8HoQc3rAEN369iqDh:bpvyonm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911)

___
*[pkg/cli/flags.go, line 1242 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72819#-Mp8I4az4cdw7tUuU8mt:-Mp8I4az4cdw7tUuU8mu:b-718u9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/cea8a6ac9ee4299c6bab61266cf81bf26069d9f9/pkg/cli/flags.go#L1242)):*
> ```Go
> 		// We assume that we only need to change top level store as temp dir configs are
> 		// initialized when start is executed.
> 		serverCfg.Stores.Specs[0].Path = server.DefaultSQLNodeStorePathPrefix + cmd.Flag(cliflags.TenantID.Name).Value.String()
> ```

How does the help text look like if one does not specify a tenant ID?
e.g. `cockroach mt start-sql --help`

**Review by aliher1911 — COMMENTED** [review]
This is a tricky one! Nice catch. Not sure what is the best way to fix that, default value is not part of the help message, but is added by cobra lib itself if value is set. And the value is generated upfront outside of command resolution. Tenant path is substituted only once the command is parsed and starts evaluating.
We can add a note at the end of path help regarding tenants, that they would use a different path. And that would be in the form of ./cockroach-data-tenant-X rather than full path. Our flags framework is not flexible in this terms.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72819#-:-Mp8nuaCE2FfBUhI5KSN:bg9t3ql)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911)

**Review by jaylim-crl — COMMENTED** [review]
> We can add a note at the end of path help regarding tenants, that they would use a different path. And that would be in the form of ./cockroach-data-tenant-X rather than full path

If we do end up with that, is there a way to disable the default message for the `--store` flag in `mt start-sql`? If we could, then that, together with the custom message at the end (e.g. default would be `/cockroach/cockroach-data-tenant-N`, where N is the tenant-id) would also solve the problem here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72819#-:-MpA5oLG2JIXrURmt136:b-ehwo3e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911)

**Review by aliher1911 — COMMENTED** [review]
I can create separate flag definition with different help message that would just describe relevant bit. But that wouldn't fix the problem of default value. For default we'll need a separate flag. We can then copy this "proxy" value onto the KVServer.Stores value in preexec.
That brings a bit of complexity, but if we are going to use this command in future, something has to be done at some point and now is the right moment.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72819#-:-MpCMuX58ZTTJjQ5cUaG:b893w9y)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jaylim-crl)

___
*[pkg/cli/flags.go, line 1242 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72819#-Mp8I4az4cdw7tUuU8mt:-MpCMIwJ490-6mnANB7q:bciy05m) ([raw file](https://github.com/cockroachdb/cockroach/blob/cea8a6ac9ee4299c6bab61266cf81bf26069d9f9/pkg/cli/flags.go#L1242)):*
<details><summary><i>Previously, jaylim-crl (Jay Lim) wrote…</i></summary><blockquote>

How does the help text look like if one does not specify a tenant ID?
e.g. `cockroach mt start-sql --help`
</blockquote></details>

I tried it and it always shows original
```
 (default --store=path=/cockroachdb/cockroach/cockroach-data)
```
which is understandable since this path is generated before we invoke cobra and preexec hook that populates tenant specific path is only invoked when executing command. help only shows what's populated in structs before parsing anything.

**Comment by knz** [comment]
Look at how `--log-dir` was handled in v20.1 and prior versions:

```
      --log-dir string
                                                            If non-empty, write log files in this directory. If empty, write log
                                                            files to <store-dir>/logs where <store-dir> is the directory of the
                                                            first on disk store.
```

I think we can do the same for `--store`: explain the default in the help text, don't populate a default in the flag, and compute the default if the `.Changed` field of the flag is not set.

**Review by aliher1911 — COMMENTED** [review]
Since you wrote a bit of things in flags maybe you have some insights on how it could evolve.
Currently we have global serverConfig which is populated by defaults in initCLIDefaults(). this init is used by cli as well as tests to have sane defaults in tests. Subsequently we initialize flags using references to configs and that's how defaults end up in help.
To remove path defaults, they need to be removed from initCLIDefaults() and populated in a hook afterwards.
One way is have two init methods - cli and tests calling same set of methods, but cli omitting options that we want to exclude from defaults. Subsequently post hook would populate the rest if they were not provided.
Does it sound sane?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72819#-:-MpCmsrS-idWbH99aCWz:b1mdkbc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jaylim-crl)

**Review by aliher1911 — COMMENTED** [review]
Oh it's even worse. Initial serverCfg also pre-populates storage and temp dir with sane defaults as part of module init. So separating CLIDefaults for tests and cli invocation doesn't cut it. Needs total rewrite :laughing:! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72819#-:-MpD0lqv7GTmyRKGafbk:b-n3zqqf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jaylim-crl)

**Comment by knz** [comment]
Look what is done with `localityAdvertiseHosts` in `cli/flags.go`. Is there a way to do something similar?

Or `serverHTTPAddr` and how `changed()` is used in `extraServerFlagInit()`.

**Comment by aliher1911** [comment]
@knz I followed your advice and did it the same way we do for flags like localityAdvertiseHosts.
Works fine despite being quite convoluted.
Can you have a quick glance?

**Review by knz — APPROVED** [review]
Nice. LGTM with nits.

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72819#-:-Mqy3DNWDqBm7hOeP6Bs:b-7nqvji)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @jaylim-crl)

___
*[pkg/cli/flags.go, line 1217 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72819#-Mqy2QxS4lMLD29BRfnw:-Mqy2QxS4lMLD29BRfnx:b-5r2t9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/9900a80494bb6494f1eb0db00d8cc83bd80d6c42/pkg/cli/flags.go#L1217)):*
> ```Go
> 	// If it isn't populated, default from server config is used for server commands or
> 	// alternative default is generated by PreRun multi-tenant hook.
> 	f := cmd.Flag(cliflags.Store.Name)
> ```

idiomatic go: `if f := fmt.Flag(...); f != nil && f.Changed`

Also why don't you simply use the helper function defined above: `if changed(fs, cliflags.Store.Name)`? 
___
*[pkg/cli/flags.go, line 1260 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72819#-Mqy32id0aFkVhdgLXUf:-Mqy32id0aFkVhdgLXUg:bptzf7h) ([raw file](https://github.com/cockroachdb/cockroach/blob/9900a80494bb6494f1eb0db00d8cc83bd80d6c42/pkg/cli/flags.go#L1260)):*
> ```Go
> 		// We assume that we only need to change top level store as temp dir configs are
> 		// initialized when start is executed.
> 		serverCfg.Stores.Specs[0].Path = server.DefaultSQLNodeStorePathPrefix + cmd.Flag(cliflags.TenantID.Name).Value.String()
> ```

for readability, please extract the value of the flag on a temp var on a previous line.
Also I encourage you to use `flagSetForCmd` instead of `cmd.Flag` because there's a bug in cobra that will make this break if we ever add sub-commands to the start cmd.

**Review by jaylim-crl — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72819#-:-MqycYIL2SeXJ2pfPs9v:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aliher1911)

___
*[pkg/cli/cliflags/flags.go, line 885 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72819#-MqycbYvDEc8DQ5numIq:-MqycbYvDEc8DQ5numIr:b-6cgxl7) ([raw file](https://github.com/cockroachdb/cockroach/blob/315fd76c1cc6e195fb74922cb2fdf65ae7489933/pkg/cli/cliflags/flags.go#L885)):*
nit: not sure what cockroach here means unless you're referring to the binary. Maybe the following?

> (default is cockroach-data for non-tenant specific commands and
> cockroach-data-tenant-X for tenant 'X' specific commands)

**Comment by aliher1911** [comment]
bors r=stevendanna,knz,jaylim-crl

**Pull request merged**
