### PR TITLE
sql: backfill index using InitPut()

### LINKED ISSUE #5817: sql: schema change probably doesn't work in practice
Discussed with @vivekmenezes today: since we use CPut when backfilling schema changes, we are likely to encounter an already-written-and-correct key and fail to write to it. The solution is to filter out already-present keys, yet we currently do not do this. All the code is in sql/backfill.go.

### PR DESCRIPTION
**Pull request by vivekmenezes**
Ignore the first commit. It is being reviewed separately. There is value to putting these two commits in different PRs, in case we want to roll them out in different Beta releases for backwards compatibility reasons.

Added a lot more testing.

closes #5817

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5996)

### CODE REVIEW

**Comment by bdarnell** [comment]
Isn't it possible for indexes to become inconsistent in ways other than an incorrect number of index records? What if rows were being updated, or deleted, not just inserted? This seems like it could result in inconsistent numbers of rows even for non-unique indexes, or incorrect data without the wrong number of rows.

**Comment by tschottdorf** [comment]
I'm also not convinced you really want to go back and spend that much work on verification. Sure, you **want** only the number of elements, but you're scanning all of it. Whatever happens here should be smart for an index with 100b elements, and this isn't. Going the `CPut` route looks more ergonomical.

**Comment by vivekmenezes** [comment]
@bdarnell I believe this approach is correct because it's wrapped up within a transaction.

@tschottdorf I do not like the approach of changing CPut. I'm happy to create a new Init() method or modify Put() to accept an initialize boolean. Both above would initialize the k:v to the value and will barf whenever they encounter an existing value that is not the initialized value.

I'm also happy to check this in for 1. It fixes the issue in the interim, and 2. We do plan to periodically run these kinds of long winding verifications eventually.

**Comment by tschottdorf** [comment]
I'm not too attached to which alternative to changing `CPut` semantics you prefer, but what you're trying to do **is** at heart a conditional put - just that you're willing to accept more than one possible value. What do you not like about it? If there is a change of `Put` or a new `Init` command that makes sense, that's fine by me (though I'd like to see what their intended semantics are before I make my personal judgment call on whether they're more appropriate than an augmented `CPut`).

While I agree that an okay solution is better than no solution, I do think that an okay solution does not need an additional pass through (which amounts to technical debt). Nobody is running these index creations at a serious scale right now, but it is the intention that people should be able to. #5981 will immediately run into this when the index creation is postponed to after the creation of the table, which is something that I want to test out.
For that reason, I would prefer a solution that fails eagerly.

**Comment by vivekmenezes** [comment]
Let's follow up on this discussion in the issue

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/schema_changer_test.go, line 509 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5996#-KFdbjVhydG6PF-OISxl:-KFdbjVhydG6PF-OISxm:1452331323) ([raw file](https://github.com/cockroachdb/cockroach/blob/391bafceaf95369db9f0c928a9f093721f44a7dc/sql/schema_changer_test.go#L509)):*
Add punctuation on this comment and the one below.

---

*[sql/schema_changer_test.go, line 562 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5996#-KFdbodRcgtTujhH0g2x:-KFdbodRcgtTujhH0g2y:-1398264585) ([raw file](https://github.com/cockroachdb/cockroach/blob/391bafceaf95369db9f0c928a9f093721f44a7dc/sql/schema_changer_test.go#L562)):*
The `e = ?, v = ?` style isn't terribly explicit. Another PR was recently sent to change an occurrence of this to `expected ?, found ?`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5996#-:-KFdcGrBwiqSUHePikDf:1417088721)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/schema_changer_test.go, line 509 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5996#-KFdbjVhydG6PF-OISxl:-KFdmntuz3N1s2184708:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/391bafceaf95369db9f0c928a9f093721f44a7dc/sql/schema_changer_test.go#L509)):*
done

---

*[sql/schema_changer_test.go, line 562 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5996#-KFdbodRcgtTujhH0g2x:-KFdmpBqYNZ-yHNqhm-e:1147198399) ([raw file](https://github.com/cockroachdb/cockroach/blob/391bafceaf95369db9f0c928a9f093721f44a7dc/sql/schema_changer_test.go#L562)):*
I've left this as is because we do use this convention all over this file. I actually like the e = ?, v = ? convention because it's short and sweet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5996)*

**Pull request merged**
