### PR TITLE
pgwire: support hba.conf auth configuration

### PR DESCRIPTION
**Pull request by madelynnblue**
The upcoming GSSAPI support requires that we have configurable
authentication. Today, pgwire auth uses certs if a client has a TLS client
cert, otherwise it uses a password. Adding GSSAPI as a third kind of login
forces us to allow administrators to configure how their auth should
function. Postgres already has a well documented and straightforward
pg_hba.conf specification. We have chosen to implement some of it in
order to make transition easy, and because it is a good format.

The hba package is a hba.conf file parser. The parser is implemented
in ragel which is a state machine generator from regular expressions to
actions. This format is complicated enough that writing a parser by hand
(due to, for example, the different kinds of strings and IP addresses)
is annoying, and ragel is able to accomplish that work with a simpler
format. It is not hooked up to the Makefile so it is possible the .rl
file could be out-of-sync with its generated .go file, but we don't
expect this file to change often and that is an acceptable risk.

A new cluster setting "server.hba_conf" has been added. The default
(empty string) preserves the old behavior of cert-then-password. We
have some differences from Postgres' hba.conf (although we can easily
expand to support more as needed). We only support the 'host' connection
method and database must be 'all' (since our database security mechanism
is somewhat different than postgres'. We do not support the @ or +
modifiers. Addresses must be IPs, or 'all', but arbitrary hostnames
or domains are unsupported. The auth methods we support are cert and
password which work the same as postgres. In addition, the cert-password
method does the cockroach default of cert-then-password. Thus, "host
all all all cert-password" is a configuration that is identical to our
unchanged default auth method.

Root is hard coded to require a certificate, preventing users from ever
setting a hba.conf file accidentally preventing all logins.

Release note (sql change): add support for configuring authentication
via a hba.conf cluster setting.

### CODE REVIEW

**Comment by mjibson** [comment]
So kinda big PR, but most lines of code are auto generated. Happy to sit down with someone if you'd like a quick session about ragel or whatever.

**Review by knz — COMMENTED** [review]
I like it!! 

A few suggestions:

1) Remind the reader in the commit message (and throughout the code) what the acronym HBA stands for: Host-Based Authentication. Consequently, check that you're not duplicating duplicating words words in in the the code code.

2) I am not fond of referring to the cluster setting as "hba_conf". It's not because the file in postgres is called this way (a choice made in the old days where filenames longer than 8 characters were problematic) that we should do the same. I recommend a setting called `server.host_based_authentication.configuration`

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32892#-:-LT3PDn58onuNULO6T1q:b-5nrmkd)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/pgwire/pgwire_test.go, line 1934 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32892#-LT3O_345mnTySJknHOp:-LT3O_345mnTySJknHOq:bvbhnyx) ([raw file](https://github.com/cockroachdb/cockroach/blob/3146d768efd6d23f24f418851d02ea0b4187a6ee/pkg/sql/pgwire/pgwire_test.go#L1934)):*
> ```Go
> }
> 
> func TestHBAAuth(t *testing.T) {
> ```

"TestHBAuth" or "TestHBA"

(same as "TestPINNumber" -> "TestPINumber" / "TestPIN"; "TestATMMachine" -> "TestATMachine" / "TestATM")
___
*[pkg/sql/pgwire/hba/conf.rl, line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32892#-LT3OqQo6H89bo-6JrZs:-LT3OqQo6H89bo-6JrZt:b-q0fhtk) ([raw file](https://github.com/cockroachdb/cockroach/blob/3146d768efd6d23f24f418851d02ea0b4187a6ee/pkg/sql/pgwire/hba/conf.rl#L18)):*
> ```Ragel
> 
> import (
> 	"net"
> ```

nit: whitespace?
___
*[pkg/sql/pgwire/hba/hba.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32892#-LT3OxQdBGEJY7-pIqOb:-LT3OxQdBGEJY7-pIqOc:bouoidl) ([raw file](https://github.com/cockroachdb/cockroach/blob/3146d768efd6d23f24f418851d02ea0b4187a6ee/pkg/sql/pgwire/hba/hba.go#L23)):*
> ```Go
> // dependency checker, and thus ragel isn't a dependency for all developers.
> 
> //go:generate ragel -Z conf.rl
> ```

Don't use `go:generate` - make Makefile rules instead. You can ask @benesch or myself for advice.
___
*[pkg/sql/pgwire/hba/hba.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32892#-LT3P3Eu8JCNEwEEM9bH:-LT3P3Eu8JCNEwEEM9bI:b-8240mv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3146d768efd6d23f24f418851d02ea0b4187a6ee/pkg/sql/pgwire/hba/hba.go#L60)):*
> ```Go
> 	sb.WriteString("host ")
> 	for i, s := range h.Database {
> 		if i > 0 {
> ```

`comma := ""; for ... { WriteString(comma); ...; comma = "," }`

here and below

**Comment by benesch** [comment]
> It is not hooked up to the Makefile so it is possible the .rl
file could be out-of-sync with its generated .go file, but we don't
expect this file to change often and that is an acceptable risk.

How would you feel if I hooked it up to the Makefile? I am really trying to excise go:generate directives from our codebase, because they don't scale.

**Comment by mjibson** [comment]
My concern with the makefile is then everyone has to have the correct version of ragel installed, which seems like a needless requirement to do for our dozens of engineers. Is there a way to do this where you only need to have ragel installed IF the .rl file changes? That'd work.

**Comment by benesch** [comment]
Oh no. I didn't realize Ragel was written in C, not Go. Never mind.

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32892)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/pgwire/pgwire_test.go, line 1934 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32892#-LT3O_345mnTySJknHOp:-LT49ZtCD_-ildE1U6yY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3146d768efd6d23f24f418851d02ea0b4187a6ee/pkg/sql/pgwire/pgwire_test.go#L1934)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

"TestHBAuth" or "TestHBA"

(same as "TestPINNumber" -> "TestPINumber" / "TestPIN"; "TestATMMachine" -> "TestATMachine" / "TestATM")
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/hba/conf.rl, line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32892#-LT3OqQo6H89bo-6JrZs:-LT49a7M4Gc7-QSjab3I:b-dpaoou) ([raw file](https://github.com/cockroachdb/cockroach/blob/3146d768efd6d23f24f418851d02ea0b4187a6ee/pkg/sql/pgwire/hba/conf.rl#L18)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: whitespace?
</blockquote></details>

not sure what you're referring to here. this is copied from the gofmt'd file.
___
*[pkg/sql/pgwire/hba/hba.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32892#-LT3OxQdBGEJY7-pIqOb:-LT4F14j2aK3BDVQ30Bx:bc6nizb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3146d768efd6d23f24f418851d02ea0b4187a6ee/pkg/sql/pgwire/hba/hba.go#L23)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Don't use `go:generate` - make Makefile rules instead. You can ask @benesch or myself for advice.
</blockquote></details>

I've written a makefile for this directory. I don't think it should be in the top level Makefile because that would require ragel to be installed everywhere. It also can't be go generate because that is also executed by our top level Makefile.
___
*[pkg/sql/pgwire/hba/hba.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32892#-LT3P3Eu8JCNEwEEM9bH:-LT4ADEY1SlLYpzcyU5C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3146d768efd6d23f24f418851d02ea0b4187a6ee/pkg/sql/pgwire/hba/hba.go#L60)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`comma := ""; for ... { WriteString(comma); ...; comma = "," }`

here and below
</blockquote></details>

Done.

**Review by benesch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32892)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/pgwire/hba/hba.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32892#-LT3OxQdBGEJY7-pIqOb:-LT4GY1D8A5cjm2vbmC7:b-fe9frp) ([raw file](https://github.com/cockroachdb/cockroach/blob/3146d768efd6d23f24f418851d02ea0b4187a6ee/pkg/sql/pgwire/hba/hba.go#L23)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I've written a makefile for this directory. I don't think it should be in the top level Makefile because that would require ragel to be installed everywhere. It also can't be go generate because that is also executed by our top level Makefile.
</blockquote></details>

The more I think about it, perhaps we should just make Ragel a build dependency. We require autoconf and CMake. This isn't much different. How much does Ragel change release to release?

No need for this discussion to hold up this PR though.

**Comment by mjibson** [comment]
Raphael came up with another solution: check in the generated file and put its dependency into our top level Makefile. This will only trigger if the ragel file changes, so the only people who need to have ragel installed are those working on it. If we expand our ragel use we can do the same thing we do elsewhere and remove the generated file from the repo and require ragel as a build dep.

ragel changes pretty slowly (last stable release was march 2017).

**Review by knz — APPROVED** [review]
:lgtm: modulo resolution of the build mechanism

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32892#-:-LT8xKXmCWKXWHtidAGd:b9w2nzc)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/pgwire/conn.go, line 1372 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32892#-LT8x6IR7tQsDmEIJnNG:-LT8x6IR7tQsDmEIJnNH:b-jhrk3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d6aad293215bd7d6f6d2c3c80f11b25de700cee/pkg/sql/pgwire/conn.go#L1372)):*
> ```Go
> var connAuthConf = settings.RegisterValidatedStringSetting(
> 	"server.host_based_authentication.configuration",
> 	"hba.conf file to use during connection authentication",
> ```

maybe the description needs to be updated as well :)

**Comment by mjibson** [comment]
Had a discussion with Nikhil. He says that we can't put it in the top level Makefile because during git checkout the timestamps can occasionally vary enough that it will needlessly retrigger the build step, which would essentially randomly require ragel. Further discussion with him and we agreed the best thing to do today is leave it as is in the current version of the PR.

**Comment by knz** [comment]
:+1:

**Review by bdarnell — APPROVED** [review]
> Reviewed 2 of 9 files at r1, 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32892)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/pgwire/conn.go, line 1325 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32892#-LTOU7AH1laT81EOgGwz:-LTOU7AH1laT81EOgGx-:bypraha) ([raw file](https://github.com/cockroachdb/cockroach/blob/39dc4aea1e1ce3c5fa3c3dac5a215946c4e10dc7/pkg/sql/pgwire/conn.go#L1325)):*
> ```Go
> 			for _, entry := range auth.Entries {
> 				switch a := entry.Address.(type) {
> 				case *net.IPNet:
> ```

What if it's not an IP? This needs to handle all cases explicitly and fail closed if it's not a known type.
___
*[pkg/sql/pgwire/conn.go, line 1371 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32892#-LTOTPwTCL9jK_uGMFkl:-LTOTPwTCL9jK_uGMFkm:b-5kk6hh) ([raw file](https://github.com/cockroachdb/cockroach/blob/39dc4aea1e1ce3c5fa3c3dac5a215946c4e10dc7/pkg/sql/pgwire/conn.go#L1371)):*
> ```Go
> var connAuthConf = settings.RegisterValidatedStringSetting(
> 	"server.host_based_authentication.configuration",
> 	"host-based authentication configuration file to use during connection authentication",
> ```

"File" sounds like it's going to be a filename, not a blob of data. 
___
*[pkg/sql/pgwire/server.go, line 228 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32892#-LTOKpii91B899Ml1b09:-LTOKpii91B899Ml1b0A:blnb4m6) ([raw file](https://github.com/cockroachdb/cockroach/blob/39dc4aea1e1ce3c5fa3c3dac5a215946c4e10dc7/pkg/sql/pgwire/server.go#L228)):*
> ```Go
> 			server.auth.conf = nil
> 		} else {
> 			server.auth.conf, _ = hba.Parse(val)
> ```

Silently swallowing this error seems like a bad idea. We may not be able to do anything but log here, but we should do that (and guarantee that `server.auth.conf` is set to nil instead of whatever bogus value may have been returned with the error).

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32892)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/pgwire/conn.go, line 1372 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32892#-LT8x6IR7tQsDmEIJnNG:-LTObg1A4l0W7hZRamXd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d6aad293215bd7d6f6d2c3c80f11b25de700cee/pkg/sql/pgwire/conn.go#L1372)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

maybe the description needs to be updated as well :)
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/conn.go, line 1325 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32892#-LTOU7AH1laT81EOgGwz:-LTObf7uElWS8GztrluC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/39dc4aea1e1ce3c5fa3c3dac5a215946c4e10dc7/pkg/sql/pgwire/conn.go#L1325)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

What if it's not an IP? This needs to handle all cases explicitly and fail closed if it's not a known type.
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/conn.go, line 1371 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32892#-LTOTPwTCL9jK_uGMFkl:-LTObgMWEhMeWYeHegxL:b31xtcg) ([raw file](https://github.com/cockroachdb/cockroach/blob/39dc4aea1e1ce3c5fa3c3dac5a215946c4e10dc7/pkg/sql/pgwire/conn.go#L1371)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

"File" sounds like it's going to be a filename, not a blob of data. 
</blockquote></details>

Removed the word file.
___
*[pkg/sql/pgwire/server.go, line 228 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32892#-LTOKpii91B899Ml1b09:-LTOfVbb6XRa_de59f86:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/39dc4aea1e1ce3c5fa3c3dac5a215946c4e10dc7/pkg/sql/pgwire/server.go#L228)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Silently swallowing this error seems like a bad idea. We may not be able to do anything but log here, but we should do that (and guarantee that `server.auth.conf` is set to nil instead of whatever bogus value may have been returned with the error). 
</blockquote></details>

Done.

**Pull request merged**
