### PR TITLE
roachprod: retry GetInternalIP on error

### LINKED ISSUE #98285: roachtest: pghosts: GetInternalIP: failed to execute hostname on <host>: exit status 255
We sometimes see the following kind of errors in roachtests (e.g. #97905, #91188, and #91904). According to https://github.com/cockroachdb/cockroach/issues/91904#issuecomment-1315763550, this should have been fixed by SSH retries, but apparently it wasn't.

```
	            	monitor failure: monitor task failed: output in run_073753.698451067_n8_workload-run-kv-dbsm: ./workload run kv --db=smallwrites --read-percent=0 --min-block-bytes=1024 --max-block-bytes=1024 --max-rate=8000 --tolerate-errors --concurrency=512 --duration=30m0s {pgurl:1-7} returned: parallel execution failure: parallel execution failure: pghosts: GetInternalIP: failed to execute hostname on teamcity-8893784-1677737775-23-n8cpu8:2:: SSH_PROBLEM: ssh verbose log retained in ssh_073753.703143564_n2_get-internal-ip.log: exit status 255
	            	(1) attached stack trace
	            	  -- stack trace:
	            	  | main.(*monitorImpl).WaitE
	            	  | 	main/pkg/cmd/roachtest/monitor.go:115
	            	  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.runAllocationBenchSample
	            	  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/allocation_bench.go:410
	            	  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.runAllocationBench
	            	  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/allocation_bench.go:359
	            	  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerAllocationBenchSpec.func1
	            	  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/allocation_bench.go:279
	            	  | main.(*testRunner).runTest.func2
	            	  | 	main/pkg/cmd/roachtest/test_runner.go:979
	            	Wraps: (2) monitor failure
	            	Wraps: (3) attached stack trace
	            	  -- stack trace:
	            	  | main.(*monitorImpl).wait.func2
	            	  | 	main/pkg/cmd/roachtest/monitor.go:171
	            	Wraps: (4) monitor task failed
	            	Wraps: (5) attached stack trace
	            	  -- stack trace:
	            	  | main.(*clusterImpl).RunE
	            	  | 	main/pkg/cmd/roachtest/cluster.go:2010
	            	  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.kvAllocBenchEventRunner.run
	            	  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/allocation_bench.go:190
	            	  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.runAllocationBenchEvent
	            	  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/allocation_bench.go:343
	            	  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.runAllocationBenchSample.func1
	            	  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/allocation_bench.go:407
	            	  | main.(*monitorImpl).Go.func1
	            	  | 	main/pkg/cmd/roachtest/monitor.go:105
	            	  | golang.org/x/sync/errgroup.(*Group).Go.func1
	            	  | 	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75
```

Jira issue: CRDB-25169

### PR DESCRIPTION
**Pull request by smg260**
Epic: none
Fixes: #98285, #98342

Release note: None

### CODE REVIEW

**Review by srosenberg — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99236#-:-NRAgLWy7z6vXWYgVgXr:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @renatolabs and @smg260)

___
*[`pkg/roachprod/install/cluster_synced.go` line 1109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99236#-NRAgMpJ7f6iRjLt52WY:-NRAgMpJ7f6iRjLt52WZ:bbpfujr) ([raw file](https://github.com/cockroachdb/cockroach/blob/509aeb33cf3ac03cb2f2357fcf5528a22c8b3bb2/pkg/roachprod/install/cluster_synced.go#L1109)):*
> ```Go
> 			if err != nil {
> 				res.Err = errors.Wrapf(err, "pgurls")
> 				// By returning a nil error here, we'll retry the command.
> ```

I had to peek inside the guts of `runWithMaybeRetry` to remind myself how this works. It's not a standard contract, so it has a confounding factor. I think we should update the comment for `Parallel` and `ParallelE` to describe the contract for the user-defined function wrt error retries.

**Review by smg260 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99236)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @renatolabs and @srosenberg)

___
*[`pkg/roachprod/install/cluster_synced.go` line 1109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99236#-NRAgMpJ7f6iRjLt52WY:-NRDvB7zB6g_6hf8IGwF:boj3zlp) ([raw file](https://github.com/cockroachdb/cockroach/blob/509aeb33cf3ac03cb2f2357fcf5528a22c8b3bb2/pkg/roachprod/install/cluster_synced.go#L1109)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

I had to peek inside the guts of `runWithMaybeRetry` to remind myself how this works. It's not a standard contract, so it has a confounding factor. I think we should update the comment for `Parallel` and `ParallelE` to describe the contract for the user-defined function wrt error retries.
</blockquote></details>

Fair point. Updating.

**Comment by smg260** [comment]
bors retry

**Comment by knz** [comment]
should this be backported?

**Comment by srosenberg** [comment]
> should this be backported?

Probably, although the near-term plan is to fix another issue [1] which will also remove the source of these flakes.

[1] https://github.com/cockroachdb/cockroach/issues/99277

**Pull request merged**
