### PR TITLE
storage/sql: change sticky bit to represent time of expiration

### PR DESCRIPTION
**Pull request by jeffrey-xiao**
This PR does the following:

- Revert the cluster setting for manual split ttl. It was agreed that this is probably too coarse to be useful.
- Change sticky bit to represent time of expiration instead of time of split.
- The expiration time displayed in `crdb_internal.ranges` is `NULL` if the range is permanent (I.E. has sticky bit of `hlc.MaxTimestamp`), otherwise it is the expiration time. This means that for static splits and splits performed by the split queue, it is displayed as `1970-01-01 00:00:00+00:00` (`hlc.Timestamp{}`).
- Add `WITH EXPIRATION` option to `SPLIT AT` that accepts the same values as `AS OF SYSTEM TIME`.

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 40 of 40 files at r2, 10 of 10 files at r3, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38004)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @jeffrey-xiao)

___
*[pkg/roachpb/api.proto, line 669 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38004#-LgYnapr7DcJKaZ_V5OR:-LgYnapr7DcJKaZ_V5OS:b-6dpwey) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9c7f65e004f7ba2632b3f75675527072fcf27b/pkg/roachpb/api.proto#L669)):*
> ```protobuf
>   RequestHeader header = 1 [(gogoproto.nullable) = false, (gogoproto.embed) = true];
>   bytes split_key = 2 [(gogoproto.casttype) = "Key"];
>   util.hlc.Timestamp expiration_time = 3 [(gogoproto.nullable) = false];
> ```

I think we're going to need to `reserve 3;` and use `4` here, otherwise, this change will be incompatible with the previous alpha. We probably don't need a full migration here, but lets at least ensure that the migration doesn't crash a node.
___
*[pkg/sql/crdb_internal.go, line 1795 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38004#-LgYo26K8K2O3O5ECikf:-LgYo26K8K2O3O5ECikg:b-64ezth) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9c7f65e004f7ba2632b3f75675527072fcf27b/pkg/sql/crdb_internal.go#L1795)):*
> ```Go
> 
> 			expirationTime := tree.DNull
> 			if !desc.StickyBit.Equal(hlc.MaxTimestamp) {
> ```

I'm surprised that we have NULL representing the maximum split time (never merge) instead of the minimum split time (always merge). I would have thought you would go the other way with this. Keep in mind that most ranges will not be manually split, so the value here should make sense for automatic splits.
___
*[pkg/sql/split.go, line 117 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38004#-LgYphvJA4YzkCSfPRO1:-LgYphvK4vXhUPZcScjg:b8ln6q8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4720a955c33b324459a5be3cee97cfb4296c8ba2/pkg/sql/split.go#L117)):*
> ```Go
> func (n *splitNode) startExec(params runParams) error {
> 	stickyBitEnabled := params.EvalContext().Settings.Version.IsActive(cluster.VersionStickyBit)
> 	// TODO(jeffreyxiao): Remove this error in v20.1.
> ```

Could you add to this comment that we can also remove `splitNode.Force` and `experimental_force_split_at` in v20.1?
___
*[pkg/sql/split.go, line 191 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38004#-LgYpwuq0D4U2UJ5i5bc:-LgYpwur2WjIC8ct_KF7:b9nnvou) ([raw file](https://github.com/cockroachdb/cockroach/blob/4720a955c33b324459a5be3cee97cfb4296c8ba2/pkg/sql/split.go#L191)):*
> ```Go
> // the expiration time of the split.
> func parseExpirationTime(
> 	expireExpr tree.Expr, semaCtx *tree.SemaContext, evalCtx *tree.EvalContext,
> ```

nit: put `expireExpr` as the last arg.
___
*[pkg/sql/split.go, line 208 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38004#-LgYq3cAECtZpmZ76Lxx:-LgYq3cAECtZpmZ76Lxy:b-8tphvf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4720a955c33b324459a5be3cee97cfb4296c8ba2/pkg/sql/split.go#L208)):*
> ```Go
> 	var convErr error
> 	switch d := d.(type) {
> 	case *tree.DString:
> ```

A lot of this is copied from somewhere, right? Should we try to unify the code?
___
*[pkg/sql/split_test.go, line 150 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38004#-LgYqPBkDST_UoBftRZN:-LgYqPBkDST_UoBftRZO:b-sq7dxh) ([raw file](https://github.com/cockroachdb/cockroach/blob/dab6353133cab5c96a5ac0d0d9ba8fef31130f46/pkg/sql/split_test.go#L150)):*
> ```Go
> 		var key roachpb.Key
> 		var pretty string
> 		var expirationTimestamp *string
> ```

Does this need to be a `*string`?
___
*[pkg/sql/unsplit_test.go, line 60 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38004#-LgYqShsBZcTzccPoyEq:-LgYqShsBZcTzccPoyEr:b-sq7dxh) ([raw file](https://github.com/cockroachdb/cockroach/blob/dab6353133cab5c96a5ac0d0d9ba8fef31130f46/pkg/sql/unsplit_test.go#L60)):*
> ```Go
> 		var key roachpb.Key
> 		var pretty string
> 		var expirationTimestamp *string
> ```

Does this need to be a `*string`?
___
*[pkg/storage/merge_queue.go, line 295 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38004#-LgYocmZ8qc0zIoQKzo1:-LgYocm_CVcFVRTgfecZ:b-9coxjj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9c7f65e004f7ba2632b3f75675527072fcf27b/pkg/storage/merge_queue.go#L295)):*
> ```Go
> 
> 	// Range was manually split and not expired, so skip merging.
> 	if rhsDesc.StickyBit.GoTime().After(mq.store.Clock().PhysicalTime()) {
> ```

Why strip the logical component before performing the comparison? We should be able to use the `hlc.Timestamp.Less` method.
___
*[pkg/storage/replica_command.go, line 227 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38004#-LgYor32-Of8jMqKuzch:-LgYor33C4K4ltzpXI8P:bbaey44) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9c7f65e004f7ba2632b3f75675527072fcf27b/pkg/storage/replica_command.go#L227)):*
> ```Go
> 		log.Event(ctx, "range already split")
> 		// Even if the range is already split, we should still update the sticky
> 		// bit if it is different.
> ```

I think we only want to do this if the expiration timestamp is less, not if it's different.
___
*[pkg/storage/replica_command.go, line 397 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38004#-LgYp0b62cM8Vfms7oNT:-LgYp0b62cM8Vfms7oNU:b-ca8akq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9c7f65e004f7ba2632b3f75675527072fcf27b/pkg/storage/replica_command.go#L397)):*
> ```Go
> 	// unsplit command as a no-op and return success instead of throwing an
> 	// error.
> 	if desc.StickyBit.Equal(hlc.Timestamp{}) {
> ```

nit: No need for `Equal` here, `hlc.Timestamp` is comparable so `==` will work.
___
*[pkg/storage/replica_command.go, line 420 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38004#-LgYp9224uhFipnDw9KF:-LgYp9232M1bMVOYY7tf:b-xk1vz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/79cc7c0f6b592590581cd421e2b06b15b1632ccd/pkg/storage/replica_command.go#L420)):*
> ```Go
> 			InternalCommitTrigger: &roachpb.InternalCommitTrigger{
> 				StickyBitTrigger: &roachpb.StickyBitTrigger{
> 					// Setting StickyBit to nil unsets the sticky bit.
> ```

Leave a similar comment here.

**Review by jeffrey-xiao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38004)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/sql/crdb_internal.go, line 1795 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38004#-LgYo26K8K2O3O5ECikf:-LgZ8ONzDP6Rud28mmSR:b6c8ffk) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9c7f65e004f7ba2632b3f75675527072fcf27b/pkg/sql/crdb_internal.go#L1795)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm surprised that we have NULL representing the maximum split time (never merge) instead of the minimum split time (always merge). I would have thought you would go the other way with this. Keep in mind that most ranges will not be manually split, so the value here should make sense for automatic splits.
</blockquote></details>

I thought it made more sense for the maximum split time to be represented as `NULL` since it's the expiration time. If there is no expiration time, I expect that the range would never expire.
___
*[pkg/sql/split.go, line 208 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38004#-LgYq3cAECtZpmZ76Lxx:-LgZ9G660TMnJKQwaE6c:bffj2m2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4720a955c33b324459a5be3cee97cfb4296c8ba2/pkg/sql/split.go#L208)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

A lot of this is copied from somewhere, right? Should we try to unify the code?
</blockquote></details>

Yes, this is mostly from `AS OF SYSTEM TIME`. I think it does different error checking though (I.E. `AS OF SYSTEM TIME` should only take in timestamps in the past). I'm okay with extracting this logic into a common function. Where should it go?
___
*[pkg/sql/split_test.go, line 150 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38004#-LgYqPBkDST_UoBftRZN:-LgZ9hZg82YEsNVs_4fS:bfw6wtm) ([raw file](https://github.com/cockroachdb/cockroach/blob/dab6353133cab5c96a5ac0d0d9ba8fef31130f46/pkg/sql/split_test.go#L150)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does this need to be a `*string`?
</blockquote></details>

`expiration_timestamp` could be NULL.
___
*[pkg/sql/unsplit_test.go, line 60 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38004#-LgYqShsBZcTzccPoyEq:-LgZ5mpCDlXAtIkQHGWn:bfw6wtm) ([raw file](https://github.com/cockroachdb/cockroach/blob/dab6353133cab5c96a5ac0d0d9ba8fef31130f46/pkg/sql/unsplit_test.go#L60)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does this need to be a `*string`?
</blockquote></details>

`expiration_timestamp` could be NULL.
___
*[pkg/storage/merge_queue.go, line 295 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38004#-LgYocmZ8qc0zIoQKzo1:-LgZ67WACWjB_2-8w7-r:bnzxsm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9c7f65e004f7ba2632b3f75675527072fcf27b/pkg/storage/merge_queue.go#L295)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why strip the logical component before performing the comparison? We should be able to use the `hlc.Timestamp.Less` method.
</blockquote></details>

I don't see an option to compare a `hlc.Timestamp` with a `time.Time`. If you mean to use `Clock().Now()` instead of `Clock().PhysicalTime()`, I thought it would better to avoid the mutex lock in `Clock().PhysicalTime()`, since the logical component isn't significant in this case.
___
*[pkg/storage/replica_command.go, line 227 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38004#-LgYor32-Of8jMqKuzch:-LgZ76VmATWYxjwPHNyS:bbf13zp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9c7f65e004f7ba2632b3f75675527072fcf27b/pkg/storage/replica_command.go#L227)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think we only want to do this if the expiration timestamp is less, not if it's different.
</blockquote></details>

Shouldn't we give users the ability to push expiration timestamps later? E.G. manual load operation is taking longer than expected, so push the sticky bits in the future.

**Review by nvb — COMMENTED** [review]
> Reviewed 50 of 50 files at r5, 40 of 40 files at r6, 10 of 10 files at r7, 5 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38004)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @jeffrey-xiao)

___
*[pkg/sql/crdb_internal.go, line 1795 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38004#-LgYo26K8K2O3O5ECikf:-LgcEug14ThjNz9YfY-f:bayxzrr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9c7f65e004f7ba2632b3f75675527072fcf27b/pkg/sql/crdb_internal.go#L1795)):*
<details><summary><i>Previously, jeffrey-xiao (Jeffrey Xiao) wrote…</i></summary><blockquote>

I thought it made more sense for the maximum split time to be represented as `NULL` since it's the expiration time. If there is no expiration time, I expect that the range would never expire.
</blockquote></details>

We'll definitely want the value of an automatic split to be `NULL` because auto-splits are so much more common than manual splits, but you might be right that "expiration time" doesn't express exactly the right semantics to allow this. What name for this column would naturally fit with a `NULL` value for an automatic split?
___
*[pkg/sql/split.go, line 208 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38004#-LgYq3cAECtZpmZ76Lxx:-LgcHuRX1HWw21ociLcL:b-u1vffs) ([raw file](https://github.com/cockroachdb/cockroach/blob/4720a955c33b324459a5be3cee97cfb4296c8ba2/pkg/sql/split.go#L208)):*
<details><summary><i>Previously, jeffrey-xiao (Jeffrey Xiao) wrote…</i></summary><blockquote>

Yes, this is mostly from `AS OF SYSTEM TIME`. I think it does different error checking though (I.E. `AS OF SYSTEM TIME` should only take in timestamps in the past). I'm okay with extracting this logic into a common function. Where should it go?
</blockquote></details>

I think we could pull out just the `Datum -> hlc.Timestamp` conversion and even that would be a nice win. Just remove the error prefix and use `errors.Wrap` at both callers. I'm not sure where a good place for this logic to live is. For now, maybe right below `EvalAsOfTimestamp`.
___
*[pkg/sql/unsplit_test.go, line 60 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38004#-LgYqShsBZcTzccPoyEq:-LgcIO0i3KAEIj_1dML4:bw05kw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/dab6353133cab5c96a5ac0d0d9ba8fef31130f46/pkg/sql/unsplit_test.go#L60)):*
<details><summary><i>Previously, jeffrey-xiao (Jeffrey Xiao) wrote…</i></summary><blockquote>

`expiration_timestamp` could be NULL.
</blockquote></details>

Then I think we want `sql.NullString`.
___
*[pkg/storage/merge_queue.go, line 295 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38004#-LgYocmZ8qc0zIoQKzo1:-LgcG4Jc0TmXkE_99Gy5:b-5024o5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9c7f65e004f7ba2632b3f75675527072fcf27b/pkg/storage/merge_queue.go#L295)):*
> If you mean to use Clock().Now() instead of Clock().PhysicalTime()

Yes, this is what I meant. I don't think we need to be worried about mutex contention for a single call to the clock in `mergeQueue.Process`. If you want though, we can pull out a `now := mq.store.Clock().Now()` variable and use it here and below so we're not adding any new clock accesses.
___
*[pkg/storage/replica_command.go, line 227 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38004#-LgYor32-Of8jMqKuzch:-LgcGxfV0EHQqaN6jhO0:b5zvppl) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9c7f65e004f7ba2632b3f75675527072fcf27b/pkg/storage/replica_command.go#L227)):*
<details><summary><i>Previously, jeffrey-xiao (Jeffrey Xiao) wrote…</i></summary><blockquote>

Shouldn't we give users the ability to push expiration timestamps later? E.G. manual load operation is taking longer than expected, so push the sticky bits in the future.
</blockquote></details>

My wording was ambiguous, but that's exactly what I was trying to allow. What I don't think we should allow if for a user to move an expiration timestamp earlier, because then the two `ADMIN SPLIT WITH EXPIRATION` statements aren't commutative.

**Review by jeffrey-xiao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38004)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/sql/crdb_internal.go, line 1795 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38004#-LgYo26K8K2O3O5ECikf:-LgcWUEo8aiRrtK4jr0e:bo9ysfi) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9c7f65e004f7ba2632b3f75675527072fcf27b/pkg/sql/crdb_internal.go#L1795)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We'll definitely want the value of an automatic split to be `NULL` because auto-splits are so much more common than manual splits, but you might be right that "expiration time" doesn't express exactly the right semantics to allow this. What name for this column would naturally fit with a `NULL` value for an automatic split?
</blockquote></details>

How about something like `time_to_live` or `lifetime`?
___
*[pkg/storage/replica_command.go, line 227 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38004#-LgYor32-Of8jMqKuzch:-LgcW2ec9iIbeBkD2e3Y:b-skwaqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9c7f65e004f7ba2632b3f75675527072fcf27b/pkg/storage/replica_command.go#L227)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

My wording was ambiguous, but that's exactly what I was trying to allow. What I don't think we should allow if for a user to move an expiration timestamp earlier, because then the two `ADMIN SPLIT WITH EXPIRATION` statements aren't commutative. 
</blockquote></details>

Okay that makes sense.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 4 of 16 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38004#-:-Lgh8ZMmEKI8CgjXayBO:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @jeffrey-xiao, and @nvanbenschoten)

___
*[pkg/sql/crdb_internal.go, line 1795 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38004#-LgYo26K8K2O3O5ECikf:-Lgh8MfuDNjP-HE22rLf:b-bh5j6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9c7f65e004f7ba2632b3f75675527072fcf27b/pkg/sql/crdb_internal.go#L1795)):*
<details><summary><i>Previously, jeffrey-xiao (Jeffrey Xiao) wrote…</i></summary><blockquote>

How about something like `time_to_live` or `lifetime`?
</blockquote></details>

We decided on `split_enforced_until` offline.

**Review by ajwerner — APPROVED** [review]
:lgtm: too

> Reviewed 1 of 50 files at r5, 6 of 40 files at r6, 3 of 16 files at r9, 8 of 12 files at r10, 5 of 5 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38004#-:-LghGGvz8FVK3mk5By0z:b4xzfr9)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @ajwerner and @jeffrey-xiao)

___
*[pkg/internal/client/db.go, line 484 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/38004#-LghFLMj3brhWsw8dj2_:-LghFLMj3brhWsw8dj2a:b-jyhnv0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9071a9a419d21225a070c0cd6288a3c37f91cff1/pkg/internal/client/db.go#L484)):*
> ```Go
> // never be eligible, set expirationTime to hlc.MaxTimestamp.
> //
> // The keys can be either byte slices or a strings.
> ```

This is more of a philosphical question than a request. At what level is the DB API supposed to operate? Is it intended to expose all the capabilities of the underlying request or just the ones we might want clients above kv to use? It is the case right now that splits for load-based splitting manually construct the AdminSplitRequest rather than using the DB method, but should they? Should this be take a *hlc.Timestamp?
___
*[pkg/sql/logictest/testdata/logic_test/crdb_internal, line 337 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/38004#-LghEJGG-RH7x9-R3Qd-:-LghEJGI3AGdp7RNYpIG:b-8engn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9071a9a419d21225a070c0cd6288a3c37f91cff1/pkg/sql/logictest/testdata/logic_test/crdb_internal#L337)):*
> ```
> ----
> start_pretty   end_pretty  split_enforced_until
> /Table/56/1/2  /Max        2262-04-11 23:47:16.854776 +0000 +0000
> ```

I appreciate the constant reminder that our time representation will only last us another 243 years.

**Comment by jeffrey-xiao** [comment]
___
*[pkg/internal/client/db.go, line 484 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/38004#-LghFLMj3brhWsw8dj2_:-LghI5kU2fpQQIyKa6xR:b-1ird0m) ([raw file](https://github.com/cockroachdb/cockroach/blob/9071a9a419d21225a070c0cd6288a3c37f91cff1/pkg/internal/client/db.go#L484)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This is more of a philosphical question than a request. At what level is the DB API supposed to operate? Is it intended to expose all the capabilities of the underlying request or just the ones we might want clients above kv to use? It is the case right now that splits for load-based splitting manually construct the AdminSplitRequest rather than using the DB method, but should they? Should this be take a *hlc.Timestamp?
</blockquote></details>

Before the presence of a sticky bit indicated that it was manually split, and now it represents the expiration time so the semantics has changed a bit. I think it's reasonable for all splits to have _some_ expiration time which is why I changed it from being a pointer. This fits nicely with the fact that automatic splits should a expiration timestamp of`hlc.Timestamp{}`.

**Comment by andreimatei** [comment]
friendly reminder to stick the docs-todo label on PRs that need docs.

**Pull request merged**
