### PR TITLE
schemachanger: reduce unnecessary validation for complex schemas

### PR DESCRIPTION
**Pull request by fqazi**
We noticed scenarios with complex schemas where validation can lead to high CPU usage and poor drop performance, so to help with these issues:
1.  Disable validation during lease renewal
2. Disable validation for the spanconfig reconciler
3. Disable validation for operations during WaitForOneVersion

Release justification: low risk and disables unnecessary validation checks that can lead to high CPU usage

These issues also exist in the previous release, so it's not much of a release blocker and more of an enhancement.

Jira issue: CRDB-14854

### CODE REVIEW

**Comment by ajwerner** [comment]
@postamar can you see how this lines up with what you've been trying?

**Comment by postamar** [comment]
You can't skip validation when reading via the collection, because the descriptors we read in that way will get added to the uncommitted descriptors layer.

As for what to do, let me think about this some more.

**Comment by postamar** [comment]
I also don't agree with:
1. Skipping validation in `WaitForOneVersion`: you can only skip it in the lookups before the last one in the for loop. Since we don't know ahead of time which one is the last one, it seems like what needs to be done is add a function in `catkv` which does cross-reference validation on a descriptor.
2. Skipping validation when acquiring the lease: we upsert that descriptor in the descriptor version state, so we can't just not validate it. You can only skip validating it if you're not actually inserting it, from what I can tell.
3. spanconfig reconciler: rather than do anything funky we might as well call `GetImmutableDescriptorsByID` instead

**Comment by fqazi** [comment]
> 1. Skipping validation in `WaitForOneVersion`: you can only skip it in the lookups before the last one in the for loop. Since we don't know ahead of time which one is the last one, it seems like what needs to be done is add a function in `catkv` which does cross-reference validation on a descriptor.
Good point


> 2\. Skipping validation when acquiring the lease: we upsert that descriptor in the descriptor version state, so we can't just not validate it. You can only skip validating it if you're not actually inserting it, from what I can tell.
@postamar The intent was to only focus on cases where we are renewing the expiry.  Not cases where we are getting fresh leases. I'll double. check the code paths, but I think the current setup should only impact renewals.



> 3\. spanconfig reconciler: rather than do anything funky we might as well call `GetImmutableDescriptorsByID` instead
Yes, let me change the call being used and reprofile.

**Pull request closed without merging**
