### PR TITLE
Added test to connection_latency, and added password to security tag

### PR DESCRIPTION
**Pull request by e-mbrown**
Release note: none

### CODE REVIEW

**Review by ajstorm — CHANGES_REQUESTED** [review]
Very excited to see your first PR come out.  Congrats! :tada: 

Can you add a bit more of a description to the commit record?  Also, the "Release note" hasn't been filled in.  It should probably read "Release note: None".

I left a high level comment, but I think that someone else on the team who's more familiar with these tests should have a look.

> Reviewed 2 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67027#-:-MdRlZ_71G_kJg3oXydh:b3w6uar)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown)

___
*[scripts/gceworker.sh, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67027#-MdRmgtJ1GpvHCAAwT_E:-MdRmgtJ1GpvHCAAwT_F:b-twqble) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed8eb49dc079e595d261e2b98de73355c482691f/scripts/gceworker.sh#L11)):*
> ```Shell
> export CLOUDSDK_COMPUTE_ZONE=${GCEWORKER_ZONE-${CLOUDSDK_COMPUTE_ZONE-us-east1-b}}
> NAME=${GCEWORKER_NAME-gceworker-$(id -un)}
> # $(id -un)
> ```

Was this intentional?

**Review by RichardJCai — CHANGES_REQUESTED** [review]
Looks pretty good, just some misc stuff. Gratz on the first PR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67027#-:-MdSG6_w6BkC4B719pX0:b-xjw6q1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown)

___
*[pkg/sql/opt/memo/typing.go, line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67027#-MdSFzKF4WHuvTYP5MCu:-MdSFzKF4WHuvTYP5MCv:b4ff824) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed8eb49dc079e595d261e2b98de73355c482691f/pkg/sql/opt/memo/typing.go#L116)):*
> ```Go
> // with the given name and argument types matching the children of the given
> // input.
> func FindFunction(e opt.ScalarExpr, name string, my_bool bool, ) (props *tree.FunctionProperties, overload *tree.Overload, ok bool) {
> ```

Was this change intended / necessary?
___
*[pkg/sql/opt/memo/typing_test.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67027#-MdSFmxWEkOeNHUjQZqQ:-MdSFmxWEkOeNHUjQZqR:b-pe0tce) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed8eb49dc079e595d261e2b98de73355c482691f/pkg/sql/opt/memo/typing_test.go#L51)):*
> ```Go
> }
> ```

Added unnecessary spacing here.
___
*[pkg/workload/cli/run.go, line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67027#-MdSFs_f8seJvDYd4jFM:-MdSFs_f8seJvDYd4jFN:bvm23am) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed8eb49dc079e595d261e2b98de73355c482691f/pkg/workload/cli/run.go#L201)):*
> ```Go
> 		urls := args
> ```

Extra spacing

**Review by e-mbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67027)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @RichardJCai)

___
*[pkg/sql/opt/memo/typing.go, line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67027#-MdSFzKF4WHuvTYP5MCu:-MdScqkO3Jt1a8QUOtg9:bh49h1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed8eb49dc079e595d261e2b98de73355c482691f/pkg/sql/opt/memo/typing.go#L116)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Was this change intended / necessary?
</blockquote></details>

No, looks like some changes from a demo branch were committed. Ill change them all back
___
*[pkg/workload/cli/run.go, line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67027#-MdSFs_f8seJvDYd4jFM:-MdSceRDELqkVIvWjc6T:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed8eb49dc079e595d261e2b98de73355c482691f/pkg/workload/cli/run.go#L201)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Extra spacing
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/typing_test.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67027#-MdSFmxWEkOeNHUjQZqQ:-MdScbs062nhFP5u9gKV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed8eb49dc079e595d261e2b98de73355c482691f/pkg/sql/opt/memo/typing_test.go#L51)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Added unnecessary spacing here.
</blockquote></details>

Done.
___
*[scripts/gceworker.sh, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67027#-MdRmgtJ1GpvHCAAwT_E:-MdScgSwCBdyhzSOE0Q8:bx48fys) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed8eb49dc079e595d261e2b98de73355c482691f/scripts/gceworker.sh#L11)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Was this intentional?
</blockquote></details>

No, changing it now.

**Review by RichardJCai — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67027)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @e-mbrown, and @RichardJCai)

___
*[pkg/cmd/roachtest/connection_latency.go, line 107 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67027#-MdSxJzl0CVWjEnAqYyZ:-MdSxJzl0CVWjEnAqYy_:b-e9zpid) ([raw file](https://github.com/cockroachdb/cockroach/blob/c409e9249e3c39ec671a0e2d17348c37af416f81/pkg/cmd/roachtest/connection_latency.go#L107)):*
> ```Go
> 		Cluster:    r.makeClusterSpec(numNodes + 1), // Add one for load node.
> 		Run: func(ctx context.Context, t *test, c Cluster) {
> 			runConnectionLatencyTest(ctx, t, c, numNodes, 1, false)
> ```

Can you add `/* password */` to `, false /* password */` same for the others below.
___
*[pkg/sql/opt/memo/typing.go, line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67027#-MdSFzKF4WHuvTYP5MCu:-MdSxCQwBD9k53I_kFN2:b-q9hzsq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed8eb49dc079e595d261e2b98de73355c482691f/pkg/sql/opt/memo/typing.go#L116)):*
<details><summary><i>Previously, e-mbrown wrote…</i></summary><blockquote>

No, looks like some changes from a demo branch were committed. Ill change them all back
</blockquote></details>

No need to change the formatting here, can revert all the changes completely.
___
*[pkg/workload/cli/run.go, line 87 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67027#-MdSxZ6tBgXZJWokRzjJ:-MdSxZ6tBgXZJWokRzjK:b-wib8n6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c409e9249e3c39ec671a0e2d17348c37af416f81/pkg/workload/cli/run.go#L87)):*
> ```Go
> 		"For example when using root, certs/client.root.crt certs/client.root.key should exist.")
> var user = securityFlags.String("user", "root", "Specify a user to run the workload as")
> var password = securityFlags.String("password", "", "Please provide password")
> ```

Nit: Change "Please provide password" to "Optionally specify a password for the user"

**Review by e-mbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67027)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @e-mbrown, and @RichardJCai)

___
*[pkg/cmd/roachtest/connection_latency.go, line 107 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67027#-MdSxJzl0CVWjEnAqYyZ:-MdT4_ft6GwGkVc-8SCb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c409e9249e3c39ec671a0e2d17348c37af416f81/pkg/cmd/roachtest/connection_latency.go#L107)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Can you add `/* password */` to `, false /* password */` same for the others below.
</blockquote></details>

Done.

**Review by RichardJCai — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67027)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @e-mbrown, and @RichardJCai)

___
*[pkg/cmd/roachtest/connection_latency.go, line 68 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67027#-MdYRItD0AmFfJYZ8KoE:-MdYRItE5q2J-ia35uKs:b-s9aaoc) ([raw file](https://github.com/cockroachdb/cockroach/blob/afc66ba1443de3b9b3b6c6de3afd09d6bd8f52b1/pkg/cmd/roachtest/connection_latency.go#L68)):*
> ```Go
> 	}
> 
> 	err = c.RunE(ctx, c.Node(1), "./workload init connectionlatency --user testuser --secure")
> ```

If password is specified, we have to pass `--password` to this command here. 

Does this roachtest fail right now if password is true? I'd expect it to since the password isn't passed in here.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67027)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @e-mbrown, and @RichardJCai)

___
*[pkg/cmd/roachtest/connection_latency.go, line 122 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67027#-Me5eFgMDAJbMYlm8Lpk:-Me5eFgMDAJbMYlm8Lpl:bcjb3zr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4945e9f752b24c8bdd94f69b2b688364040b6b55/pkg/cmd/roachtest/connection_latency.go#L122)):*
> ```Go
> 
> 	r.Add(registry.TestSpec{
> 		Name:       fmt.Sprintf("connection_latency/nodes=%d/multiregion", numMultiRegionNodes),
> ```

nit: can we name this one `connection_latency/nodes=%d/multiregion/cert`
___
*[pkg/cmd/roachtest/connection_latency.go, line 131 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67027#-Me5eWpGC5UJqWeaNm-s:-Me5eWpGC5UJqWeaNm-t:b-k7lpgg) ([raw file](https://github.com/cockroachdb/cockroach/blob/4945e9f752b24c8bdd94f69b2b688364040b6b55/pkg/cmd/roachtest/connection_latency.go#L131)):*
> ```Go
> 
> 	r.Add(registry.TestSpec{
> 		Name:       fmt.Sprintf("connection_latency/nodes=%d/password", numMultiRegionNodes),
> ```

nit: can we name this one `connection_latency/nodes=%d/multiregion/password`

**Review by RichardJCai — APPROVED** [review]
Great work! :lgtm: once the nits are addressed.

Also the linter is failing right now, I recommend getting crlfmt setup in Goland to automatically format code.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67027#-:-Me76gfsB3OiB7SBoBQE:bw6qjhv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @e-mbrown, @rafiss, and @RichardJCai)

___
*[pkg/cmd/roachtest/connection_latency.go, line 103 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67027#-Me76L9c5vLpMrS7O-wU:-Me76L9c5vLpMrS7O-wV:b-32cjjl) ([raw file](https://github.com/cockroachdb/cockroach/blob/c409e9249e3c39ec671a0e2d17348c37af416f81/pkg/cmd/roachtest/connection_latency.go#L103)):*
> ```Go
> 	r.Add(testSpec{
> 		MinVersion: "v20.1.0",
> 		Name:       fmt.Sprintf("connection_latency/nodes=%d", numNodes),
> ```

change to
`connection_latency/certs/nodes=3`
___
*[pkg/cmd/roachtest/connection_latency.go, line 122 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67027#-Me5eFgMDAJbMYlm8Lpk:-Me76FdH26dWBDwCSebn:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/4945e9f752b24c8bdd94f69b2b688364040b6b55/pkg/cmd/roachtest/connection_latency.go#L122)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: can we name this one `connection_latency/nodes=%d/multiregion/cert`
</blockquote></details>

ditto

**Comment by RichardJCai** [comment]
Also you'll have to rebase onto master to fix the merge conflict.

**Review by e-mbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67027)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm, @e-mbrown, and @RichardJCai)

___
*[pkg/cmd/roachtest/connection_latency.go, line 68 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67027#-MdYRItD0AmFfJYZ8KoE:-MeAtL7k47vaGVAPRFBw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/afc66ba1443de3b9b3b6c6de3afd09d6bd8f52b1/pkg/cmd/roachtest/connection_latency.go#L68)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

If password is specified, we have to pass `--password` to this command here. 

Does this roachtest fail right now if password is true? I'd expect it to since the password isn't passed in here.
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
nice work!

**Comment by e-mbrown** [comment]
bors r=RichardJCai,rafiss

**Pull request merged**
