### PR TITLE
roachtest: benchmark encryption at rest.

### PR DESCRIPTION
**Pull request by ghost**
This roachtest runs the kv workload against a cluster with encryption turned on
and a cluster with encryption turned off. The max number of operations of the
workload is incrementally increased and the resulting time elapsed for each
workload run is recorded and logged to show the impact of encryption at rest
on performance. It serves as a very basic benchmarking for encryption.

Encryption benchmark: #19783.
Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/cmd/roachtest/encryption_benchmark.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26056#-LDIqQsz5hf6FR4N3hi5:-LDIqQsz5hf6FR4N3hi6:bfj1hxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/148f0e2fb7ba4cceb3b074fe20270a6a8a961578/pkg/cmd/roachtest/encryption_benchmark.go#L57)):*
> ```Go
> 
> 		const minNumOps = 1000
> 		const maxNumOps = 2000
> ```

That's not many ops. Doesn't each iteration only take a second or two? Rather than ramping up the number of ops performed, I would have run `workload run kv` against a cluster both with and without encryption and manually looked at the output from `workload run`. Shortly we'll be able to hook up `workload run kv --histograms=file` which will output workload metrics to the specified file, but no need to worry about that now. 

Note that the above feels like a variant of the `kv{0,95}` roachtests which already exist. That is, we could extend those tests to optionally enable encryption. The encrypted vs unencrypted runs would be subtests which would allow apples-to-apples comparison on the same set of nodes. 

---

*[pkg/cmd/roachtest/encryption_benchmark.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26056#-LDIq3o85SwKjeN17rKx:-LDIq3o85SwKjeN17rKy:b4rt94b) ([raw file](https://github.com/cockroachdb/cockroach/blob/148f0e2fb7ba4cceb3b074fe20270a6a8a961578/pkg/cmd/roachtest/encryption_benchmark.go#L104)):*
> ```Go
> 
> 		for i := 1; i <= nodes; i++ {
> 			if err := stopAndWipe(i); err != nil {
> ```

Is there a reason you're not using `c.Wipe(ctx, c.All())`? Perhaps the `keys` should be stored in the `/mnt/data1/cockroach` directory so they will automatically be removed by a wipe as well.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26056)*

**Comment by windchan7** [comment]
*[pkg/cmd/roachtest/encryption_benchmark.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26056#-LDIqQsz5hf6FR4N3hi5:-LDIt9n29lxDmy9krWkr:bp1vcpy) ([raw file](https://github.com/cockroachdb/cockroach/blob/148f0e2fb7ba4cceb3b074fe20270a6a8a961578/pkg/cmd/roachtest/encryption_benchmark.go#L57)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

That's not many ops. Doesn't each iteration only take a second or two? Rather than ramping up the number of ops performed, I would have run `workload run kv` against a cluster both with and without encryption and manually looked at the output from `workload run`. Shortly we'll be able to hook up `workload run kv --histograms=file` which will output workload metrics to the specified file, but no need to worry about that now. 

Note that the above feels like a variant of the `kv{0,95}` roachtests which already exist. That is, we could extend those tests to optionally enable encryption. The encrypted vs unencrypted runs would be subtests which would allow apples-to-apples comparison on the same set of nodes. 
</blockquote></details>

Yes, that's a good point! I think right now we just want some very basic benchmarking for encryption at rest to know that it works. Marc actually has a plan to turn encryption on by default and run workload against it later.

The number of ops in this roachtest is just a placeholder that can be adjusted. So no worries here. I will increase it to a point where it can stress the CPU later.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26056)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/cmd/roachtest/encryption_benchmark.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26056#-LDIqQsz5hf6FR4N3hi5:-LDIvjgEAtmIRaiIqb6w:b-kie11s) ([raw file](https://github.com/cockroachdb/cockroach/blob/148f0e2fb7ba4cceb3b074fe20270a6a8a961578/pkg/cmd/roachtest/encryption_benchmark.go#L57)):*
<details><summary><i>Previously, windchan7 (Victor Chen) wrote…</i></summary><blockquote>

Yes, that's a good point! I think right now we just want some very basic benchmarking for encryption at rest to know that it works. Marc actually has a plan to turn encryption on by default and run workload against it later.

The number of ops in this roachtest is just a placeholder that can be adjusted. So no worries here. I will increase it to a point where it can stress the CPU later.
</blockquote></details>

Extending `kv{0,95}` would be very basic benchmarking as those are the most basic benchmarks we have. I'm pushing on this point because work is afoot to visualize the output from those tests which this PR would then automatically take advantage of. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26056)*

**Comment by mberhault** [comment]
I think the right approach here is to add a flag to cause roachtest/roachprod to startup with encryption enabled. This will make it easy to flip on arbitrary tests.

**Comment by windchan7** [comment]
See these 2 PR:
https://github.com/cockroachdb/cockroach/pull/26094
https://github.com/cockroachdb/roachprod/pull/170

**Comment by petermattis** [comment]
@windchan7 Now that `cockroachdb/roachprod#170`, I think you should extend the `kv{0,95}` tests with an additional "encrypted" configuration. This will give us nightly roachtests that use encryption-at- rest, and allow us to look at the perf difference between the encrypted and non-encrypted versions.

**Comment by windchan7** [comment]
See here: https://github.com/cockroachdb/cockroach/pull/26103.

**Pull request closed without merging**
