### PR TITLE
kv: delete txnIntentCollector, track intent spans in txnPipeliner as "write footprint"

### PR DESCRIPTION
**Pull request by nvb**
This primary purpose of this PR is to address the impedance mismatch discussed in https://github.com/cockroachdb/cockroach/pull/35763#pullrequestreview-218024651 between tracking in-flight writes and tracking a transaction's intent "footprint". These are two related but fundamentally different concepts and it's best to be explicit about how they relate and how they differ.

To this end, this PR moves all intent tracking into the txnPipeliner. The pipeliner now tracks two separate sets: the "in-flight writes" and the "write footprint". The former is morally a subset of the latter, but for the sake of avoiding duplication, in-flight writes are not included in the write footprint. Instead, the write footprint includes:
1. write from the current epoch that have already succeeded (point writes that were pipelined and already proved and ranged writes)
2. writes from the current epoch that may or may not have succeeded
3. all writes from prior epochs

Structuring the two sets this way has a major benefit -- it is exactly how we would like to represent the writes that a transaction has performed on `EndTransactionRequests` and on STAGING `Transaction` records. This will simplify client-logic in #36012 significantly.

The PR also addresses @ajwerner's comment from https://github.com/cockroachdb/cockroach/pull/36012#pullrequestreview-221890867 about renaming "outstanding writes" to "in-flight writes" so that we can unify the concept with the "in-flight writes" that play an important role in parallel commits.

### CODE REVIEW

**Review by tbg — APPROVED** [review]
> Reviewed 7 of 7 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 7 of 7 files at r4, 7 of 7 files at r5, 18 of 18 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37302)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/txn_interceptor_pipeliner.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeBbUwN6uZOVDTEYvCm:-LeBbUwOB-IklgQDRKKF:b-fryvk1) ([raw file](https://github.com/cockroachdb/cockroach/blob/fab6e4f5612e0fa5ec70e67c183088256bf952e1/pkg/kv/txn_interceptor_pipeliner.go#L67)):*
> ```Go
> // The interceptor also ensures that when committing a transaction all writes
> // that have been proposed but not proven to have succeeded are first checked
> // before committing. These async writes are referred to as "in-fight writes"
> ```

typo :crossed_swords: 
___
*[pkg/kv/txn_interceptor_pipeliner.go, line 175 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeBdeYy4dYpdBJ6AIF8:-LeBdeYy4dYpdBJ6AIF9:b86hlug) ([raw file](https://github.com/cockroachdb/cockroach/blob/32b8009da294a085930d034e27a3deb0f9a910e2/pkg/kv/txn_interceptor_pipeliner.go#L175)):*
> ```Go
> 	}
> 
> 	// TODO(nvanbenschoten): It's currently possible for this response to be
> ```

Was this just obsolete?
___
*[pkg/kv/txn_interceptor_pipeliner.go, line 464 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeBcY-f1lGUb_13Svcr:-LeBcY-f1lGUb_13Svcs:b-nhba3p) ([raw file](https://github.com/cockroachdb/cockroach/blob/32b8009da294a085930d034e27a3deb0f9a910e2/pkg/kv/txn_interceptor_pipeliner.go#L464)):*
> ```Go
> // inFlightWriteSet is an ordered set of in-flight point writes. The structure
> // supports O(log n) insertion of new in-flight writes, O(log n) removal of
> // existing in-flight writes, and O(log n) retrieval over in-flight writes that
> ```

Sure about that `O(log n)` for retrieval? A single lookup is `O(log n)`, but the retrieval might need to retrieve the whole tree, so it's `O(n)` at best.
___
*[pkg/kv/txn_interceptor_pipeliner.go, line 591 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeBdJqFDuVCKDnka64N:-LeBdJqG0hksvuJJWVTp:bextfhu) ([raw file](https://github.com/cockroachdb/cockroach/blob/32b8009da294a085930d034e27a3deb0f9a910e2/pkg/kv/txn_interceptor_pipeliner.go#L591)):*
> ```Go
> 	}
> 	s.t.Clear(reuse /* addNodesToFreelist */)
> 	s.bytes = 0
> ```

you access `s.bytes` somewhere from somewhere, consider adding an accessor similar to `len()`.
___
*[pkg/kv/txn_interceptor_pipeliner.go, line 165 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeBf7NGDSOaZIsRNnVy:-LeBf7NH2WVHnuWyi2Sq:bs8ehnz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8c3be595e40f311a6c4013080c7fdd9c14944fa/pkg/kv/txn_interceptor_pipeliner.go#L165)):*
> ```Go
> type txnPipeliner struct {
> 	st       *cluster.Settings
> 	ri       *RangeIterator // optional
> ```

Please add more verbiage around why this is optional and what the implications of not specifying it are.
___
*[pkg/kv/txn_interceptor_pipeliner.go, line 181 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeBfJMOCnYSLkqrzRNZ:-LeBfJMOCnYSLkqrzRN_:bj36vyo) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8c3be595e40f311a6c4013080c7fdd9c14944fa/pkg/kv/txn_interceptor_pipeliner.go#L181)):*
> can be an overestimate (i.e. the spans may cover keys never written to)
___
*[pkg/kv/txn_interceptor_pipeliner.go, line 428 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeBjxcjBB1bTEM2j6ME:-LeBjxcjBB1bTEM2j6MF:b-23u2iu) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8c3be595e40f311a6c4013080c7fdd9c14944fa/pkg/kv/txn_interceptor_pipeliner.go#L428)):*
> ```Go
> //    the in-flight writes set to the write footprint.
> //
> // If an error is provided, all writes from the batch are added directly
> ```

This is assuming that the txn is finished for the current epoch after any error, right? I.e. you can't `CPut`-probe a value and just keep going on mismatch. I know we don't support this and discussed this elsewhere, but might be worth an inline comment in the early return.

I also think this description would read better if you mentioned the error case first, and then the three steps (which don't apply to the error case).
___
*[pkg/kv/txn_interceptor_pipeliner.go, line 438 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeBjiYAAXqbzqkUAmLw:-LeBjiYAAXqbzqkUAmLx:b-i8ibps) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8c3be595e40f311a6c4013080c7fdd9c14944fa/pkg/kv/txn_interceptor_pipeliner.go#L438)):*
> ```Go
> 	ctx context.Context, ba roachpb.BatchRequest, br *roachpb.BatchResponse, pErr *roachpb.Error,
> ) {
> 	// After adding new writes to the write footprint, check whether we need to
> ```

Worth mentioning that in the method comment as well.
___
*[pkg/kv/txn_interceptor_pipeliner.go, line 567 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeBka6H4sayBplY4ezG:-LeBka6H4sayBplY4ezH:b-489jz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8c3be595e40f311a6c4013080c7fdd9c14944fa/pkg/kv/txn_interceptor_pipeliner.go#L567)):*
> precisely
___
*[pkg/kv/txn_interceptor_pipeliner.go, line 581 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeBkkF11vG-aUy0aqBI:-LeBkkF11vG-aUy0aqBJ:b73fms3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8c3be595e40f311a6c4013080c7fdd9c14944fa/pkg/kv/txn_interceptor_pipeliner.go#L581)):*
> // haveWrites returns whether the interceptor has observed any writes, including currently in-flight ones.
___
*[pkg/kv/txn_interceptor_pipeliner.go, line 769 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeBkxgrBZOy-fomA5X3:-LeBkxgrBZOy-fomA5X4:b77wyf3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8c3be595e40f311a6c4013080c7fdd9c14944fa/pkg/kv/txn_interceptor_pipeliner.go#L769)):*
> ```Go
> }
> 
> // condensableSpanSet is a set of key spans that is compressable in order to
> ```

s/compressable/condensable/
___
*[pkg/kv/txn_interceptor_pipeliner.go, line 773 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeBl7cl5tVSidjcjHJG:-LeBl7cl5tVSidjcjHJH:bcnzhx0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8c3be595e40f311a6c4013080c7fdd9c14944fa/pkg/kv/txn_interceptor_pipeliner.go#L773)):*
> ```Go
> // ways. Initially, overlapping spans are merged together to deduplicate
> // redundant keys. If that alone isn't sufficient to stay below the byte limit,
> // spans within the same range will be merged together. This can cause the
> ```

capitalize `range` in the hope that that makes it clear that you're not just talking about some anonymous "key range".
___
*[pkg/kv/txn_interceptor_pipeliner.go, line 815 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeBlQtn50ye6ouotnpB:-LeBlQtn50ye6ouotnpC:b-n9ask6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8c3be595e40f311a6c4013080c7fdd9c14944fa/pkg/kv/txn_interceptor_pipeliner.go#L815)):*
> ```Go
> 
> 	if ri == nil {
> 		// If we were not given a RangeIterator, we cannot condense the spans.
> ```

Are we ever not given one?
___
*[pkg/kv/txn_interceptor_pipeliner.go, line 854 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeBpPAH6mE--hzJ1GYe:-LeBpPAI0OWrXy8jL3cX:bvt2ovb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8c3be595e40f311a6c4013080c7fdd9c14944fa/pkg/kv/txn_interceptor_pipeliner.go#L854)):*
> ```Go
> 	// until total size of uncondensed spans no longer exceeds threshold.
> 	sort.Slice(buckets, func(i, j int) bool { return buckets[i].bytes > buckets[j].bytes })
> 	s.s = localSpans // reset to hold just the local spans; will add newly condensed and remainder
> ```

Any error return below (there's one right now) this is going to be problematic, because we might be missing intents. If the txn commits, this means that the txn record will be missing intents, which means it could be removed too early, and a write could be lost. I think this is worth writing down, but also the error return needs to either become an assertion (should be fine?) or propagate an error to the caller, or at the very least restore `s.s` to something legitimate (i.e. throw an append). The assertion seems most appropriate unless there's some good reason it would be hit.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37302)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)

___
*[pkg/kv/txn_interceptor_pipeliner.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeBbUwN6uZOVDTEYvCm:-LeCmCkB2UO6L8Bw1ynF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fab6e4f5612e0fa5ec70e67c183088256bf952e1/pkg/kv/txn_interceptor_pipeliner.go#L67)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

typo :crossed_swords: 
</blockquote></details>

Done.
___
*[pkg/kv/txn_interceptor_pipeliner.go, line 175 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeBdeYy4dYpdBJ6AIF8:-LeCmEeT4RNNqyYRC8ax:b-uyubp2) ([raw file](https://github.com/cockroachdb/cockroach/blob/32b8009da294a085930d034e27a3deb0f9a910e2/pkg/kv/txn_interceptor_pipeliner.go#L175)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Was this just obsolete?
</blockquote></details>

Yes, it had to do with parallel statement execution.
___
*[pkg/kv/txn_interceptor_pipeliner.go, line 464 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeBcY-f1lGUb_13Svcr:-LeCmMoLDMc3wTD5oQ-2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/32b8009da294a085930d034e27a3deb0f9a910e2/pkg/kv/txn_interceptor_pipeliner.go#L464)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Sure about that `O(log n)` for retrieval? A single lookup is `O(log n)`, but the retrieval might need to retrieve the whole tree, so it's `O(n)` at best.
</blockquote></details>

Done.
___
*[pkg/kv/txn_interceptor_pipeliner.go, line 591 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeBdJqFDuVCKDnka64N:-LeCmNDaBLHPmYdbARWh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/32b8009da294a085930d034e27a3deb0f9a910e2/pkg/kv/txn_interceptor_pipeliner.go#L591)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

you access `s.bytes` somewhere from somewhere, consider adding an accessor similar to `len()`.
</blockquote></details>

Done.
___
*[pkg/kv/txn_interceptor_pipeliner.go, line 165 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeBf7NGDSOaZIsRNnVy:-LeCnt8W4h1mOjyVWF2H:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8c3be595e40f311a6c4013080c7fdd9c14944fa/pkg/kv/txn_interceptor_pipeliner.go#L165)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Please add more verbiage around why this is optional and what the implications of not specifying it are.
</blockquote></details>

Done.
___
*[pkg/kv/txn_interceptor_pipeliner.go, line 181 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeBfJMOCnYSLkqrzRNZ:-LeCo-iZ1KNGOB97nEHT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8c3be595e40f311a6c4013080c7fdd9c14944fa/pkg/kv/txn_interceptor_pipeliner.go#L181)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> can be an overestimate (i.e. the spans may cover keys never written to)
</blockquote></details>

Done.
___
*[pkg/kv/txn_interceptor_pipeliner.go, line 428 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeBjxcjBB1bTEM2j6ME:-LeHfomD5d2wq2OO9OFd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8c3be595e40f311a6c4013080c7fdd9c14944fa/pkg/kv/txn_interceptor_pipeliner.go#L428)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This is assuming that the txn is finished for the current epoch after any error, right? I.e. you can't `CPut`-probe a value and just keep going on mismatch. I know we don't support this and discussed this elsewhere, but might be worth an inline comment in the early return.

I also think this description would read better if you mentioned the error case first, and then the three steps (which don't apply to the error case).
</blockquote></details>

Done.
___
*[pkg/kv/txn_interceptor_pipeliner.go, line 438 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeBjiYAAXqbzqkUAmLw:-LeCoI815DaNmB4v-5mS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8c3be595e40f311a6c4013080c7fdd9c14944fa/pkg/kv/txn_interceptor_pipeliner.go#L438)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Worth mentioning that in the method comment as well.
</blockquote></details>

Done.
___
*[pkg/kv/txn_interceptor_pipeliner.go, line 567 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeBka6H4sayBplY4ezG:-LeCoLHHCuO1EhYVryaC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8c3be595e40f311a6c4013080c7fdd9c14944fa/pkg/kv/txn_interceptor_pipeliner.go#L567)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> precisely
</blockquote></details>

Done.
___
*[pkg/kv/txn_interceptor_pipeliner.go, line 581 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeBkkF11vG-aUy0aqBI:-LeCoQid1ZL7dsmiq2Ju:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8c3be595e40f311a6c4013080c7fdd9c14944fa/pkg/kv/txn_interceptor_pipeliner.go#L581)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> // haveWrites returns whether the interceptor has observed any writes, including currently in-flight ones.
</blockquote></details>

Done.
___
*[pkg/kv/txn_interceptor_pipeliner.go, line 769 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeBkxgrBZOy-fomA5X3:-LeCoZxkCxPw9RR9QY3N:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8c3be595e40f311a6c4013080c7fdd9c14944fa/pkg/kv/txn_interceptor_pipeliner.go#L769)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

s/compressable/condensable/
</blockquote></details>

Done.
___
*[pkg/kv/txn_interceptor_pipeliner.go, line 773 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeBl7cl5tVSidjcjHJG:-LeCocC80OR2dssM_4Kr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8c3be595e40f311a6c4013080c7fdd9c14944fa/pkg/kv/txn_interceptor_pipeliner.go#L773)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

capitalize `range` in the hope that that makes it clear that you're not just talking about some anonymous "key range".
</blockquote></details>

Done.
___
*[pkg/kv/txn_interceptor_pipeliner.go, line 815 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeBlQtn50ye6ouotnpB:-LeCp-qd-VjJj5-x682p:bdctyan) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8c3be595e40f311a6c4013080c7fdd9c14944fa/pkg/kv/txn_interceptor_pipeliner.go#L815)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Are we ever not given one?
</blockquote></details>

Yes, we have unit tests that don't provide `TxnCoordSender` with a wrapped `DistSender`:
https://github.com/cockroachdb/cockroach/blob/f55431c30734eebca11bfb289a2ca1eb64e58016/pkg/kv/txn_coord_sender.go#L481-L483
___
*[pkg/kv/txn_interceptor_pipeliner.go, line 854 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeBpPAH6mE--hzJ1GYe:-LeHgGn57oDX9fqMPwYL:bhr0avg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8c3be595e40f311a6c4013080c7fdd9c14944fa/pkg/kv/txn_interceptor_pipeliner.go#L854)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Any error return below (there's one right now) this is going to be problematic, because we might be missing intents. If the txn commits, this means that the txn record will be missing intents, which means it could be removed too early, and a write could be lost. I think this is worth writing down, but also the error return needs to either become an assertion (should be fine?) or propagate an error to the caller, or at the very least restore `s.s` to something legitimate (i.e. throw an append). The assertion seems most appropriate unless there's some good reason it would be hit.
</blockquote></details>

Great point! Done here and commented about this above.

**Review by tbg — APPROVED** [review]
It was tough to verify the latest round of changes (just can't seem to find the right diffs), but they didn't contain anything substantial anyway.

:lgtm: 

> Reviewed 25 of 25 files at r7, 2 of 2 files at r8, 1 of 1 files at r9, 7 of 7 files at r10, 7 of 7 files at r11, 18 of 18 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-:-LeHkqN594M-AxC9oSMx:bb9wyov)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @nvanbenschoten, and @tbg)

___
*[pkg/kv/txn_interceptor_pipeliner.go, line 815 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeBlQtn50ye6ouotnpB:-LeHjHFU7yUntXvYo6nH:b-8dx1wv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8c3be595e40f311a6c4013080c7fdd9c14944fa/pkg/kv/txn_interceptor_pipeliner.go#L815)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yes, we have unit tests that don't provide `TxnCoordSender` with a wrapped `DistSender`:
https://github.com/cockroachdb/cockroach/blob/f55431c30734eebca11bfb289a2ca1eb64e58016/pkg/kv/txn_coord_sender.go#L481-L483
</blockquote></details>

:-(

ok, carry on

ps would be better to have `tcf.wrapped` be an interface that also implements `.RangeIterator()` and then these tests can wrap into a dummy object that returns a single-range-contains-all iter, but this seems like something we're better off not stuffing into this PR.

**Comment by nvanbenschoten** [comment]
TFTR! Now we get to see the payoff in #36012, where the client logic should be much simpler.

bors r+

**Comment by nvanbenschoten** [comment]
Bors crashed.

bors r+

**Review by andreimatei — COMMENTED** [review]
very nice PR! But I had a question (which I think might not even be specific to this PR)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-:-LeXjLAhE3ybhhTy-H_T:b-sudnaw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[pkg/kv/txn_coord_sender_test.go, line 1506 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeXf3TA8f6NHa9-8kNi:-LeXf3TBDxvkxlaq1yX_:b5uxj4m) ([raw file](https://github.com/cockroachdb/cockroach/blob/d26b0eaf5681fc196f18b7f5087f0b217d28f04a/pkg/kv/txn_coord_sender_test.go#L1506)):*
> ```Go
> }
> 
> // Test that the TxnCoordSender accumulates intents even if it hasn't seen a
> ```

how come you've deleted this test? Just because it's harder to test now that `tcs.GetMeta()` can't be used any more?
___
*[pkg/kv/txn_interceptor_pipeliner.go, line 393 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeXikxL5AlhUos5gAVN:-LeXikxL5AlhUos5gAVO:b3a9o85) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c886e8a30650c2558558f1d30a181f5580971f9/pkg/kv/txn_interceptor_pipeliner.go#L393)):*
> ```Go
> 	// We can't pass in a batch response here to better limit the key spans as
> 	// we don't know what is going to be affected. This will affect queries such
> 	// as `DELETE FROM my.table LIMIT 10` when executed as a 1PC transaction.
> ```

I'm confused here... How is this case going to work? We're going to give the `EndTransaction` the whole table as an `IntentSpan`, right? What's the `EndTransaction` going to do with it? It's not gonna perform cleanup on the whole table is it?

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37302)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @nvanbenschoten, and @tbg)

___
*[pkg/kv/txn_coord_sender_test.go, line 1506 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeXf3TA8f6NHa9-8kNi:-LeXsQid38H2nqN1Fci3:bdocpvq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d26b0eaf5681fc196f18b7f5087f0b217d28f04a/pkg/kv/txn_coord_sender_test.go#L1506)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

how come you've deleted this test? Just because it's harder to test now that `tcs.GetMeta()` can't be used any more?
</blockquote></details>

Well we don't even send `BeginTransaction` requests anymore, so the test didn't make sense to keep.
___
*[pkg/kv/txn_interceptor_pipeliner.go, line 393 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeXikxL5AlhUos5gAVN:-LeXsVcN8RIum3PNlAI9:b-8zzvgb) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c886e8a30650c2558558f1d30a181f5580971f9/pkg/kv/txn_interceptor_pipeliner.go#L393)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'm confused here... How is this case going to work? We're going to give the `EndTransaction` the whole table as an `IntentSpan`, right? What's the `EndTransaction` going to do with it? It's not gonna perform cleanup on the whole table is it?
</blockquote></details>

Yes, that's exactly what it will do. It's pretty unfortunate. Note that this isn't anything new.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37302)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @nvanbenschoten, and @tbg)

___
*[pkg/kv/txn_interceptor_pipeliner.go, line 393 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/37302#-LeXikxL5AlhUos5gAVN:-LeXv2HmACK_Vl9FDDfn:bdougqa) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c886e8a30650c2558558f1d30a181f5580971f9/pkg/kv/txn_interceptor_pipeliner.go#L393)):*
I've filed #37457. After freaking out I've verified that `DELETE FROM my.table LIMIT 10` does not get turned into a `DeleteRange` - so this comment is wrong and more alarming than it needs to be. Also, if anything is actually "executed as a 1PC", then we'd also be fine cause the intent tracking doesn't matter.
But the problem still seems pretty bad to me.

> Note that this isn't anything new.

noted

**Pull request merged**
