### PR TITLE
raft: make unstable a logSlice

### PR DESCRIPTION
**Pull request by pav-kv**
This PR refactors `raft.unstable` data structure to be a type-safe `logSlice`, and equips it with safety checks protecting the log append stack from appends that do not comply with the expected raft behaviours.

One immediate benefit of doing so is that `unstable` now knows the `lastEntryID` at all times, whereas previously it would fall back to fetching it from `Storage` interface when empty.

The second benefit is introducing the `logSlice.term` field, which carries strong semantics: the log is consistent with the leader log at this term. This allows implementing safety checks in append methods, preventing log truncations when not expected. Log truncations in raft can only happen when accepting a higher-term log append.

The `logSlice.term` field replaces `raft.accTerm`.

Part of #124440

### CODE REVIEW

**Comment by pav-kv** [comment]
@nvanbenschoten PTAL. Commit-by-commit review recommended.

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 2 of 2 files at r4, 5 of 5 files at r5, 1 of 1 files at r6, 5 of 5 files at r7, 2 of 2 files at r8, 1 of 1 files at r9, 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126783)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv)

___
*[`-- commits` line 65 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/126783#-O1IbYNA4U7npoYS-SEg):*
"truncated truncated"
___
*[`pkg/raft/log.go` line 137 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126783#-O1IV9KsDzXv7TuCo6_D:-O1IV9KsDzXv7TuCo6_E:b-9nlmv2) ([raw file](https://github.com/cockroachdb/cockroach/blob/89afb179c1569677d8328850eb9935d9593dd7a2/pkg/raft/log.go#L137)):*
> ```Go
> 		return true
> 	}
> 	if first := a.entries[0].Index; first <= l.committed {
> ```

Do we no longer want this check in `append`?
___
*[`pkg/raft/log.go` line 138 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126783#-O1IUNFREjEfFGsKgp-5:-O1IUNFREjEfFGsKgp-6:bqg1d4t) ([raw file](https://github.com/cockroachdb/cockroach/blob/34b3a94310c566270d031e6c7bdbc942ddaef3fc/pkg/raft/log.go#L138)):*
> ```Go
> 
> // append adds the given log slice to the end of the log. Returns false if this
> // can not be done.
> ```

Could you spell out the case where the append can no be done, like you did above with `maybeAppend`?
___
*[`pkg/raft/log.go` line 117 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/126783#-O1IdUdJ8WHfKWlrL3Lm:-O1IdUdJ8WHfKWlrL3Ln:b-cv8enj) ([raw file](https://github.com/cockroachdb/cockroach/blob/029f074e17ed0846f1d3da214be045a4d7ac5a74/pkg/raft/log.go#L117)):*
> ```Go
> //
> // Invariant: the log is a prefix of the accTerm's leader log
> // Invariant: lastEntryID().term <= accTerm <= Term
> ```

Is `Term` a reference to `raft.Term`? If so, should we call that out explicitly, given that `raftLog` otherwise does not know about the `raft` struct?
___
*[`pkg/raft/log_unstable.go` line 29 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/126783#-O1IWOUR7Tj7V7evxq9c:-O1IWOUR7Tj7V7evxq9d:b-dvyy08) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c58f611406f922a34233dd22b8f68a0716e107/pkg/raft/log_unstable.go#L29)):*
> ```Go
> //     is fully in Storage. The logSlice.prev is the lastEntryID of the log.
> //  2. The snapshot is empty, and the entries logSlice is non-empty. The state
> //     up to logSlice.prev is in Storage, and the logSlice is pending.
> ```

`s/up to/up to and including/` to avoid ambiguity.
___
*[`pkg/raft/log_unstable.go` line 45 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/126783#-O1IWjtC0fGrCrbgy5OI:-O1IWjtC0fGrCrbgy5OJ:bubf84n) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c58f611406f922a34233dd22b8f68a0716e107/pkg/raft/log_unstable.go#L45)):*
> expects acknowledgments from the storage to arrive in the same order

Is this true? What will happen if acks from storage arrive out of order?
___
*[`pkg/raft/log_unstable.go` line 81 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/126783#-O1IXJWKEkySBVFNa2ok:-O1IXJWKEkySBVFNa2ol:b-vaiyn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c58f611406f922a34233dd22b8f68a0716e107/pkg/raft/log_unstable.go#L81)):*
> ```Go
> 	// the leader whose append (either entries or snapshot) we accepted last. Our
> 	// state is consistent with the leader log at this term.
> 	logSlice
> ```

Are you sure we want to embed this and inherit all methods from `logSlice` onto `unstable`? Do all of the methods on `logSlice` make sense in the context of an `unstable`?
___
*[`pkg/raft/log_unstable.go` line 151 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/126783#-O1IYOlv3maMltDHgCRh:-O1IYOlv3maMltDHgCRi:b-14hdp2) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c58f611406f922a34233dd22b8f68a0716e107/pkg/raft/log_unstable.go#L151)):*
> ```Go
> func (u *unstable) acceptInProgress() {
> 	if u.snapshot != nil {
> 		u.snapshotInProgress = true
> ```

nit: might as well switch to `u.snapshotInProgress = u.snapshot != nil`.
___
*[`pkg/raft/log_unstable.go` line 165 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/126783#-O1IYXucAurhrGSiIGW9:-O1IYXucAurhrGSiIGWA:b-6e79hf) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c58f611406f922a34233dd22b8f68a0716e107/pkg/raft/log_unstable.go#L165)):*
> ```Go
> 	if u.snapshot != nil && id.index == u.snapshot.Metadata.Index {
> 		// Index matched unstable snapshot, not unstable entry. Ignore.
> 		u.logger.Infof("entry at index %d matched unstable snapshot; ignoring", id.index)
> ```

Missing a `return` here?
___
*[`pkg/raft/log_unstable.go` line 285 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/126783#-O1IZLHO5SIly598qf0a:-O1IZLHO5SIly598qf0b:b-2zkro5) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c58f611406f922a34233dd22b8f68a0716e107/pkg/raft/log_unstable.go#L285)):*
> ```Go
> }
> 
> // u.offset <= lo <= hi <= u.offset+len(u.entries)
> ```

This comment is now out of date.
___
*[`pkg/raft/log_unstable.go` line 245 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/126783#-O1IZz0q38n6G8q9KsiC:-O1IZz0q38n6G8q9KsiD:bu2lqyv) ([raw file](https://github.com/cockroachdb/cockroach/blob/789fd77a0ad41af30d00d2755041e335f298393b/pkg/raft/log_unstable.go#L245)):*
> If a.prev.index == last.index, then the last entry term did not match in the check above, so we must reject this case too.

Does this mean that we're rejecting on `a.term > u.term && a.prev.index == last.index && a.prev.term > last.term`? That's needed because we haven't found a common prefix, right? Even though in practice we won't even reach this code from `raftLog.maybeAppend` if `matchTerm` fails. Can we update this comment to spell it out?
___
*[`pkg/raft/log_unstable.go` line 272 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/126783#-O1IbFCB80feLMCs6BBd:-O1IbFCB80feLMCs6BBe:bwg8yaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/789fd77a0ad41af30d00d2755041e335f298393b/pkg/raft/log_unstable.go#L272)):*
> ```Go
> 	// Truncate the log and append new entries. Regress the entryInProgress mark
> 	// to reflect that the truncated entries are no longer considered in progress.
> 	u.entryInProgress = min(u.entryInProgress, a.prev.index)
> ```

nit: elsewhere, we update `entries` before `entryInProgress`, so consider doing the same here.
___
*[`pkg/raft/log_unstable.go` line 232 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/126783#-O1Ic_-k8Vwwmi7LnwXy:-O1Ic_-k8Vwwmi7LnwXz:b-3bobrn) ([raw file](https://github.com/cockroachdb/cockroach/blob/8289b8e751e2b1449f57615f73dac1a788b3bba1/pkg/raft/log_unstable.go#L232)):*
> ```Go
> 	// written such that a snapshot always clears the log.
> 	if s.term <= u.term && s.lastIndex() < u.lastIndex() {
> 		return false
> ```

I'm mildly concerned that these `return false` cases are going to be hard to debug if we ever get one wrong. We aren't logging a message or returning an error for the upper levels to log, so we'll just silently drop the context around why the snapshot/log append/etc. was ignored. What do you think?

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126783)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`-- commits` line 65 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/126783#-O1IbYNA4U7npoYS-SEg):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"truncated truncated"
</blockquote></details>

Done
___
*[`pkg/raft/log.go` line 137 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126783#-O1IV9KsDzXv7TuCo6_D:-O1IjGEe4I57uu419yUK:b-ix5fmy) ([raw file](https://github.com/cockroachdb/cockroach/blob/89afb179c1569677d8328850eb9935d9593dd7a2/pkg/raft/log.go#L137)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we no longer want this check in `append`?
</blockquote></details>

This check ensures that we don't overwrite committed entries. We don't need it in `append` because it now only handles the "append-only" case when no entries are overwritten.
___
*[`pkg/raft/log.go` line 138 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126783#-O1IUNFREjEfFGsKgp-5:-O1Iydw1DhJyJ1pJXsse:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/34b3a94310c566270d031e6c7bdbc942ddaef3fc/pkg/raft/log.go#L138)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could you spell out the case where the append can no be done, like you did above with `maybeAppend`?
</blockquote></details>

Done
___
*[`pkg/raft/log.go` line 117 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/126783#-O1IdUdJ8WHfKWlrL3Lm:-O1InXPS3PO9ygRB7ZMV:bwaa9nw) ([raw file](https://github.com/cockroachdb/cockroach/blob/029f074e17ed0846f1d3da214be045a4d7ac5a74/pkg/raft/log.go#L117)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is `Term` a reference to `raft.Term`? If so, should we call that out explicitly, given that `raftLog` otherwise does not know about the `raft` struct?
</blockquote></details>

Yes, done.

Btw, for future, it would be a good idea to include the phase 1 term into `raftLog` so that the term checks in it are stronger, and `raftLog` fully implements the Acceptor logic (which right now is scattered between `raft` and `raftLog`). Technically, there is a slight difference between `raft.Term` and phase 1 term: a candidate bumps its `raft.Term` before its acceptor gave a phase 1 promise (voted). I.e. there is a logical difference between `bump(raft.Term)` and `bump(promised term)`.
___
*[`pkg/raft/log_unstable.go` line 29 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/126783#-O1IWOUR7Tj7V7evxq9c:-O1IzrgU3VIyeG_lJzNu:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c58f611406f922a34233dd22b8f68a0716e107/pkg/raft/log_unstable.go#L29)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/up to/up to and including/` to avoid ambiguity.
</blockquote></details>

Done
___
*[`pkg/raft/log_unstable.go` line 45 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/126783#-O1IWjtC0fGrCrbgy5OI:-O1Ik49kB2L4vGWlQNlN:b25u722) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c58f611406f922a34233dd22b8f68a0716e107/pkg/raft/log_unstable.go#L45)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> expects acknowledgments from the storage to arrive in the same order

Is this true? What will happen if acks from storage arrive out of order?
</blockquote></details>

Reworded. I think what we care about is the guarantee: if we receive an ack, all the writes <= this ack have been done. It's possible that acks are dropped (for optimization purposes; not done today, but it's possible), or delivered out of order (because of some legitimate races/concurrency in the ack delivery path). I.e. we care about the writes being done in order, and the latest ack being delivered to us.
___
*[`pkg/raft/log_unstable.go` line 151 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/126783#-O1IYOlv3maMltDHgCRh:-O1J1CUm9Hbi8hNKB1LD:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c58f611406f922a34233dd22b8f68a0716e107/pkg/raft/log_unstable.go#L151)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: might as well switch to `u.snapshotInProgress = u.snapshot != nil`.
</blockquote></details>

Done
___
*[`pkg/raft/log_unstable.go` line 165 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/126783#-O1IYXucAurhrGSiIGW9:-O1J1KvOCioHDTsgQK7J:b-ko1vnr) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c58f611406f922a34233dd22b8f68a0716e107/pkg/raft/log_unstable.go#L165)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Missing a `return` here?
</blockquote></details>

Done

It would have been caught by the next check (because snapshot index == `prev.index`), but we don't want both log messages in this case.
___
*[`pkg/raft/log_unstable.go` line 285 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/126783#-O1IZLHO5SIly598qf0a:-O1J303oAKcOETbmjguK:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c58f611406f922a34233dd22b8f68a0716e107/pkg/raft/log_unstable.go#L285)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This comment is now out of date.
</blockquote></details>

Done
___
*[`pkg/raft/log_unstable.go` line 245 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/126783#-O1IZz0q38n6G8q9KsiC:-O1Imkm55CCkVRC-Z7xH:b-owtxj1) ([raw file](https://github.com/cockroachdb/cockroach/blob/789fd77a0ad41af30d00d2755041e335f298393b/pkg/raft/log_unstable.go#L245)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> If a.prev.index == last.index, then the last entry term did not match in the check above, so we must reject this case too.

Does this mean that we're rejecting on `a.term > u.term && a.prev.index == last.index && a.prev.term > last.term`? That's needed because we haven't found a common prefix, right? Even though in practice we won't even reach this code from `raftLog.maybeAppend` if `matchTerm` fails. Can we update this comment to spell it out?
</blockquote></details>

Right, we haven't found a common prefix. It's also possible that `a.prev.term < last.term` here. There is no guarantee that a higher-term leader has a higher-term entry at `index`, it could fork the log in such a way that some entries are from the past leaders.

Yeah, in practice the caller already made sure `matchTerm` at this `prev.index`. But this check is cheap here, and guards `unstable` invariants.
___
*[`pkg/raft/log_unstable.go` line 272 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/126783#-O1IbFCB80feLMCs6BBd:-O1J3bch99USY0lJ6Oxg:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/789fd77a0ad41af30d00d2755041e335f298393b/pkg/raft/log_unstable.go#L272)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: elsewhere, we update `entries` before `entryInProgress`, so consider doing the same here.
</blockquote></details>

Done

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126783)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/raft/log_unstable.go` line 81 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/126783#-O1IXJWKEkySBVFNa2ok:-O1JAgZs4Al9OTDZyd_-:boeczct) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c58f611406f922a34233dd22b8f68a0716e107/pkg/raft/log_unstable.go#L81)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Are you sure we want to embed this and inherit all methods from `logSlice` onto `unstable`? Do all of the methods on `logSlice` make sense in the context of an `unstable`?
</blockquote></details>

The idea is that `unstable` is mostly a `logSlice` by definition. Definitely methods like `lastIndex/EntryID` and `termAt` are good to inherit. The `valid()` and `forward()` methods are a bit questionable.

Would you prefer an explicit `entries logSlice` field?
___
*[`pkg/raft/log_unstable.go` line 232 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/126783#-O1Ic_-k8Vwwmi7LnwXy:-O1J8Roj43KOJ53crx6h:b-xg1ti4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8289b8e751e2b1449f57615f73dac1a788b3bba1/pkg/raft/log_unstable.go#L232)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm mildly concerned that these `return false` cases are going to be hard to debug if we ever get one wrong. We aren't logging a message or returning an error for the upper levels to log, so we'll just silently drop the context around why the snapshot/log append/etc. was ignored. What do you think?
</blockquote></details>

There are perhaps 3 categories of `return false` in these paths:

- Legitimate rejections. For example, we handle an append that is out-of-bounds, or `a.term > u.term` && `prev` doesn't match our log. We could log an info on those.
- Internal invariants broken. Raft isn't broken yet, but it would be unsafe to proceed. E.g. `restore(snap)` wants to truncate the log when it should not do so.
- Raft/safety invariants already broken. Probably a panic case.

Not sure how to handle all these gracefully / uniformly. Maybe return `(ok, error)`, and log the errors? Or return an enum with all possible outcomes? Or `(enum, error)`?

**Comment by pav-kv** [comment]
@nvanbenschoten addressed all the nits. Left 2 threads open for discussion.

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 5 files at r15, 1 of 5 files at r17, 1 of 1 files at r19, 4 of 4 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126783)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv)

___
*[`pkg/raft/log_unstable.go` line 45 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/126783#-O1IWjtC0fGrCrbgy5OI:-O1JOSYW8d_5b4JClQim:b-naycg7) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c58f611406f922a34233dd22b8f68a0716e107/pkg/raft/log_unstable.go#L45)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Reworded. I think what we care about is the guarantee: if we receive an ack, all the writes <= this ack have been done. It's possible that acks are dropped (for optimization purposes; not done today, but it's possible), or delivered out of order (because of some legitimate races/concurrency in the ack delivery path). I.e. we care about the writes being done in order, and the latest ack being delivered to us.
</blockquote></details>

Agreed about that being the guarantee we care about. The rewording LGTM.
___
*[`pkg/raft/log_unstable.go` line 81 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/126783#-O1IXJWKEkySBVFNa2ok:-O1JO_yCDQF9dRBcK_o2:b-u43rag) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c58f611406f922a34233dd22b8f68a0716e107/pkg/raft/log_unstable.go#L81)):*
> Would you prefer an explicit `entries logSlice` field?

I can see benefits to each approach, so I'll defer to you.

The only things that really stand out to me as unfortunate with embedding are:
1. some unrelated methods being inherited from `logSlice` onto `unstable`
2. the definition of `unstable.prev` being confusing when `snapshot != nil`

On the other hand, I think it's nice to embed since `unstable.term` refers to the accepted term of the snapshot as well as the log entries. That could go away if you replaced `*pb.Snapshot` with a `snapshot`. I'm not sure whether that would clean up the `term := max(u.term, s.term)` in `restore`, or make it worse.
___
*[`pkg/raft/log_unstable.go` line 232 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/126783#-O1Ic_-k8Vwwmi7LnwXy:-O1JQcvE9v25Afx0ZD7P:b-9ltfyj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8289b8e751e2b1449f57615f73dac1a788b3bba1/pkg/raft/log_unstable.go#L232)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

There are perhaps 3 categories of `return false` in these paths:

- Legitimate rejections. For example, we handle an append that is out-of-bounds, or `a.term > u.term` && `prev` doesn't match our log. We could log an info on those.
- Internal invariants broken. Raft isn't broken yet, but it would be unsafe to proceed. E.g. `restore(snap)` wants to truncate the log when it should not do so.
- Raft/safety invariants already broken. Probably a panic case.

Not sure how to handle all these gracefully / uniformly. Maybe return `(ok, error)`, and log the errors? Or return an enum with all possible outcomes? Or `(enum, error)`?
</blockquote></details>

For the legitimate rejections, it would be good to log an info. Currently, these rejections are caught (and logged) a few levels up though, so I guess most of case 1 paths are actually case 2 paths. For those, logging an error might be appropriate. For the third case, I guess panic. Raft currently doesn't distinguish between cases 2 and 3, and panics for both of them.

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126783)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/raft/log_unstable.go` line 81 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/126783#-O1IXJWKEkySBVFNa2ok:-O1JUY3y7z_wvJwJ4VH7:bkyyequ) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c58f611406f922a34233dd22b8f68a0716e107/pkg/raft/log_unstable.go#L81)):*
I'm leaning to leave as is, because the slightly unrelated methods (`forward` and `valid`) are not mutating the `logSlice` state (it was deliberate to make `logSlice` immutable), so there is no footgun; also, there is no incentive to accidentally use these methods.

> the definition of `unstable.prev` being confusing when `snapshot != nil`

Actually, this is quite in line with the semantics of `Storage` interface (if you think of storage as state + log suffix). There is `Storage.FirstIndex` method which essentially returns `prev.index+1`, and the `Storage.Term` method has a documented special case that it can return the term of `FirstIndex - 1`. Instead of `FirstIndex`, it could be `Prev()`, and `Term` would say that it returns a term for `Prev.index <= index <= LastIndex`, just like `logSlice.termAt`.

> On the other hand, I think it's nice to embed since `unstable.term` refers to the accepted term of the snapshot as well as the log entries. That could go away if you replaced `*pb.Snapshot` with a `snapshot`. I'm not sure whether that would clean up the `term := max(u.term, s.term)` in `restore`, or make it worse.

Today, probably it would make it worse because it denormalizes the struct (there would be two `term` fields which mostly need to be in sync).

This would perhaps be a better approach when we get to separate raft log project again. There is a lot we can do inside `raft` package to implement it better than when we tried to do it all outside raft. E.g. the order between `snapshot` and `logSlice` would be laxer, and some denormalization could be needed.

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126783)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/raft/log_unstable.go` line 81 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/126783#-O1IXJWKEkySBVFNa2ok:-O1JbvxvA4Pw1PkM9mCQ:bfngiku) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c58f611406f922a34233dd22b8f68a0716e107/pkg/raft/log_unstable.go#L81)):*
> Actually, this is quite in line with the semantics of `Storage` interface

Not entirely though. In `Storage`, the first index can be behind the applied index (but not behind the last applied snapshot), whereas in `unstable` the entries are always tailing the snapshot.

**Review by nvb — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126783#-:-O1SFb5u-3fXIuYfwSQ3:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv)

**Comment by pav-kv** [comment]
TFTR!

bors r=nvanbenschoten

**Pull request merged**
