### PR TITLE
bazel: update the foreign_cc dependency

### PR DESCRIPTION
**Pull request by knz**
Trying this out as discussed in https://github.com/cockroachdb/cockroach/issues/64334#issuecomment-828818194

### CODE REVIEW

**Comment by knz** [comment]
Here's the error:

```
[15:23:27]W:		 [Run Bazel test] ERROR: /root/.cache/bazel/_bazel_root/c5a4e7d36696d9cd970af2045211a7df/external/rules_foreign_cc/toolchains/BUILD.bazel:77:22: @platforms//os:windows is not a valid configuration key for @rules_foreign_cc//toolchains:built_make
[15:23:28]W:		 [Run Bazel test] ERROR: While resolving toolchains for target //c-deps:libjemalloc: @platforms//os:windows is not a valid configuration key for @rules_foreign_cc//toolchains:built_make
[15:23:28]W:		 [Run Bazel test] ERROR: Analysis of target '//pkg/server/status:status_test' failed; build aborted: @platforms//os:windows is not a valid configuration key for @rules_foreign_cc//toolchains:built_make
```

**Comment by knz** [comment]
If I build with the same CI script but using bazel 4 locally (instead of v3, as is used in CI I think?) I do not observe the error.

Is it possible that the newer version of foreign_cc only works properly with bazel 4?

**Comment by rickystewart** [comment]
I agree that upgrading to Bazel 4.0.0 fixes the issue. I'll put in a PR for that.

**Review by rickystewart — APPROVED** [review]
Please rebase against `master` and make sure CI passes.

**Comment by knz** [comment]
> Please rebase against master and make sure CI passes.

done

**Comment by knz** [comment]
thanks

bors r=rickystewart

**Pull request merged**
