### PR TITLE
flowinfra: use the flow context in FlowStream RPC in outbox

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, we used the background context when performing the
`FlowStream` RPC in the row-based outbox rather than the flow context.
This has been the case for like four years now, but I believe it is
incorrect. In particular, if the flow context is canceled, this would
not shutdown the gRPC stream, possibly leaking some of the goroutines
(e.g. the goroutine listening for the drain signal from the inbox). This
is now fixed by correctly using the flow context.

This commit also fixes the outbox to satisfy the gRPC contract hidden in
[1] where the listener goroutine would not `Recv` everything from the
stream which could result in leakage of gRPC goroutines.

This required the cleanup of the outbox infrastructure to bring it more
in line with what we have in the vectorized engine (which has been
updated some time ago with recent learnings). In particular, the
following problems have been fixed:
- `CloseSend` signal from the main goroutine of the outbox previously
could have been omitted in some cases (I'm not sure what the impact of
this is though)
- the listener ("watchdog") goroutine is now tracked by the wait group
of the flow which makes it so that `Flow.Wait` blocks until the watchdog
exits. That goroutine now exits only after it `Recv`es an error from the
server side (the inbox) of `FlowStream` RPC.

[1] https://pkg.go.dev/google.golang.org/grpc#ClientConn.NewStream

Informs: #90841.

Epic: None

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I think the CI should be green with the latest push (there was a hang in a benchmark previously) plus I added another commit to fix a test (exposed in #93840). RFAL.

Not that it matters much, but the benchmarks seem to have improved:
```
name                 old time/op    new time/op     delta
Outbox/numCols=1-24     205ns ±32%      216ns ±15%     ~     (p=0.511 n=10+9)
Outbox/numCols=2-24     271ns ± 4%      224ns ± 3%  -17.10%  (p=0.000 n=10+10)
Outbox/numCols=4-24     331ns ± 4%      280ns ± 2%  -15.29%  (p=0.000 n=10+10)
Outbox/numCols=8-24     464ns ± 3%      406ns ± 2%  -12.53%  (p=0.000 n=10+10)

name                 old speed      new speed       delta
Outbox/numCols=1-24  39.9MB/s ±43%   37.3MB/s ±17%     ~     (p=0.497 n=10+9)
Outbox/numCols=2-24  59.1MB/s ± 4%   71.3MB/s ± 3%  +20.62%  (p=0.000 n=10+10)
Outbox/numCols=4-24  96.9MB/s ± 4%  114.3MB/s ± 2%  +17.99%  (p=0.000 n=10+10)
Outbox/numCols=8-24   138MB/s ± 3%    158MB/s ± 2%  +14.30%  (p=0.000 n=10+10)

name                 old alloc/op   new alloc/op    delta
Outbox/numCols=1-24      275B ±54%       274B ±54%     ~     (p=0.811 n=10+10)
Outbox/numCols=2-24      379B ± 4%       433B ± 2%  +14.10%  (p=0.000 n=10+9)
Outbox/numCols=4-24      462B ± 5%       544B ± 1%  +17.89%  (p=0.000 n=10+10)
Outbox/numCols=8-24      646B ± 4%       773B ± 2%  +19.61%  (p=0.000 n=10+9)

name                 old allocs/op  new allocs/op   delta
Outbox/numCols=1-24      3.56 ±44%       3.56 ±44%     ~     (p=1.000 n=9+9)
Outbox/numCols=2-24      5.00 ± 0%       6.00 ± 0%  +20.00%  (p=0.000 n=10+9)
Outbox/numCols=4-24      6.00 ± 0%       7.00 ± 0%  +16.67%  (p=0.000 n=10+10)
Outbox/numCols=8-24      8.70 ± 8%      10.70 ± 7%  +22.99%  (p=0.000 n=10+10)
```

**Review by cucaroach — APPROVED** [review]
:lgtm:   Although I'm not super familiar with this code.

> Reviewed 5 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90864#-:-NJoeGyeAJMSgkPwzqnh:b-px9fv8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

**Comment by yuzefovich** [comment]
TFTR!

@andreimatei are you interested in reviewing this? Unfortunately, you might actually be the one with the most context on this except for me.

**Review by andreimatei — APPROVED** [review]
:lgtm: 

but can you spell out for me what the difference is between the `flowCtxCancel` and the `outboxCtxCancel`?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90864#-:-NJpeU8U3Vn1o67tw-Fn:bfag68b)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/sql/flowinfra/outbox.go` line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90864#-NJpYep_82st3XsSYfXQ:-NJpYep_82st3XsSYfXR:b-x2i92m) ([raw file](https://github.com/cockroachdb/cockroach/blob/22d38eeabdca14ddea20e1ccaf88ded83b558945/pkg/sql/flowinfra/outbox.go#L228)):*
> ```Go
> 	// this outbox.
> 	ctx, m.outboxCtxCancel = context.WithCancel(ctx)
> 	// Calling outboxCtxCancel is not strictly necessary, but we do it just to
> ```

if you write this comment, say why it's not necessary; who's guaranteed to do it?
___
*[`pkg/sql/flowinfra/outbox.go` line 379 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90864#-NJpbcI93w6hmMnSZ9RE:-NJpbcI93w6hmMnSZ9RF:b-9lxpif) ([raw file](https://github.com/cockroachdb/cockroach/blob/22d38eeabdca14ddea20e1ccaf88ded83b558945/pkg/sql/flowinfra/outbox.go#L379)):*
> // as another channel which will be signaled when draining is requested. The
// caller is responsible to not exit before the "wait" channel is closed in
// order to not leak resources.


I think this comment is a bit unclear; consider saying more. What does it mean for the caller to "exit"? And what does it mean for resources to be leaked / how come that's avoided by the caller waiting more than it would otherwise?
https://www.youtube.com/watch?v=C2CuAVAERjs
___
*[`pkg/sql/flowinfra/outbox.go` line 380 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90864#-NJpZcL_2p9buQP-148i:-NJpZcL_2p9buQP-148j:blfn5rq) ([raw file](https://github.com/cockroachdb/cockroach/blob/22d38eeabdca14ddea20e1ccaf88ded83b558945/pkg/sql/flowinfra/outbox.go#L380)):*
> ```Go
> // It returns a channel that will be closed once the new goroutine exits as well
> // as another channel which will be signaled when draining is requested. The
> // caller is responsible to not exit before the "wait" channel is closed in
> ```

consider putting names on the retvals; which one is the `"wait" channel` ?
___
*[`pkg/sql/flowinfra/outbox.go` line 386 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90864#-NJpadhMB4eAqQkt-zbk:-NJpadhMB4eAqQkt-zbl:bpzzpf) ([raw file](https://github.com/cockroachdb/cockroach/blob/22d38eeabdca14ddea20e1ccaf88ded83b558945/pkg/sql/flowinfra/outbox.go#L386)):*
> ```Go
> ) (<-chan struct{}, <-chan struct{}, error) {
> 	waitCh := make(chan struct{})
> 	drainCh := make(chan struct{}, 1)
> ```

since you're deep in this, mind putting a note about why `drainCh` is buffered?
___
*[`pkg/sql/flowinfra/outbox.go` line 407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90864#-NJp_qO94ZWoXGBgEjZw:-NJp_qO94ZWoXGBgEjZx:b1r5cwr) ([raw file](https://github.com/cockroachdb/cockroach/blob/22d38eeabdca14ddea20e1ccaf88ded83b558945/pkg/sql/flowinfra/outbox.go#L407)):*
> ```Go
> 			switch {
> 			case signal.Handshake != nil:
> 				log.VEventf(ctx, 2, "Outbox received handshake: %v", signal.Handshake)
> ```

`%v` is unusual (mostly useful for nil pointers). Are we getting anything out of it here compared to the usual `%s`? 
Also, we don't implement stringer on `signal.Handshake`, so you sure you want to use the autogenerate proto one?
We don't seem to use this signal at all, so consider dropping the logging.

**Review by yuzefovich — COMMENTED** [review]
`flowCtxCancel` is called when we're shutting down the whole distributed plan ungracefully because we encountered some "fatal" (from the query execution perspective) error. In particular, this will mean that all trees of operators on the current node will be shutdown (because each tree should be using a child of the "flow" context), e.g. we can have multiple outboxes with separate trees on a single node.

`outboxCtxCancel` is called during the graceful shutdown of a single tree of operators. This is the case when the consumer communicated to the outbox that no more data is needed, so we just want to shutdown all of the operator chain that is pushing into the outbox.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90864#-:-NJppZ2GAanwDkWXbPgO:b9clsg9)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andreimatei and @cucaroach)

___
*[`pkg/sql/flowinfra/outbox.go` line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90864#-NJpYep_82st3XsSYfXQ:-NJphiL7EU_HjkVzScZV:b-ptiqgj) ([raw file](https://github.com/cockroachdb/cockroach/blob/22d38eeabdca14ddea20e1ccaf88ded83b558945/pkg/sql/flowinfra/outbox.go#L228)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

if you write this comment, say why it's not necessary; who's guaranteed to do it?
</blockquote></details>

Actually, I'll remove this call and expand the comment.
___
*[`pkg/sql/flowinfra/outbox.go` line 379 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90864#-NJpbcI93w6hmMnSZ9RE:-NJpk0Gr8wKNdRN6PeTW:bugu5iq) ([raw file](https://github.com/cockroachdb/cockroach/blob/22d38eeabdca14ddea20e1ccaf88ded83b558945/pkg/sql/flowinfra/outbox.go#L379)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> // as another channel which will be signaled when draining is requested. The
// caller is responsible to not exit before the "wait" channel is closed in
// order to not leak resources.


I think this comment is a bit unclear; consider saying more. What does it mean for the caller to "exit"? And what does it mean for resources to be leaked / how come that's avoided by the caller waiting more than it would otherwise?
https://www.youtube.com/watch?v=C2CuAVAERjs
</blockquote></details>

Reworded. Mentioning leaking resources was incorrect.

The main idea is that at least currently we only include the main goroutine of the outbox (the one running `mainLoop`) into the wait group of the `Flow`, so once that main goroutine exits, `Flow.Wait` can be unblocked. This could then lead to `Flow.Cleanup` be called which calls `flowCtxCancel` which breaks the gRPC stream, and the consumer of `FlowStream` RPC (the inbox) would see it as an ungraceful termination making the query fail with the gRPC stream cancellation error.

I thought about including this watchdog goroutine into the wait group which would solve this problem. However, we also would like for the watchdog to notify the main goroutine of the outbox when the gRPC stream is closed so that the outbox can exit too. For this purposes closing a channel works well.

Now that I typed this all out I think we should just add the watchdog goroutine into the wait group and keep the wait channel's purpose only to signal when the outbox should shutdown. Actually, we can just have a single channel now.

PTAL.
___
*[`pkg/sql/flowinfra/outbox.go` line 380 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90864#-NJpZcL_2p9buQP-148i:-NJpoAmlAmwmSoZFXH6t:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/22d38eeabdca14ddea20e1ccaf88ded83b558945/pkg/sql/flowinfra/outbox.go#L380)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

consider putting names on the retvals; which one is the `"wait" channel` ?
</blockquote></details>

Done.
___
*[`pkg/sql/flowinfra/outbox.go` line 386 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90864#-NJpadhMB4eAqQkt-zbk:-NJpoWz62slaAOAtEium:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/22d38eeabdca14ddea20e1ccaf88ded83b558945/pkg/sql/flowinfra/outbox.go#L386)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

since you're deep in this, mind putting a note about why `drainCh` is buffered?
</blockquote></details>

Done.
___
*[`pkg/sql/flowinfra/outbox.go` line 407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90864#-NJp_qO94ZWoXGBgEjZw:-NJpp8I_0B7HRO-QYBbi:b-snxeew) ([raw file](https://github.com/cockroachdb/cockroach/blob/22d38eeabdca14ddea20e1ccaf88ded83b558945/pkg/sql/flowinfra/outbox.go#L407)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

`%v` is unusual (mostly useful for nil pointers). Are we getting anything out of it here compared to the usual `%s`? 
Also, we don't implement stringer on `signal.Handshake`, so you sure you want to use the autogenerate proto one?
We don't seem to use this signal at all, so consider dropping the logging.
</blockquote></details>

Indeed, no need for `%v`, this was copy-pasta. `%s` still seems useful since it carries the DistSQL version information from the gateway node.

**Comment by yuzefovich** [comment]
Alright, updated the commit message. I don't think another look is needed, so will merge on green CI.

**Review by andreimatei — COMMENTED** [review]
> we can have multiple outboxes with separate trees on a single node.

Got it, this was not clear to me. Consider including this hint in a comment somewhere.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90864#-:-NJqYeVFBWvo_GmP65vh:b-3kcid2)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @cucaroach)

**Review by yuzefovich — COMMENTED** [review]
Mentioned this in the comment.

TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90864#-:-NJqoEgL1o0a3iX6pxTn:bm7fne)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andreimatei and @cucaroach)

**Pull request merged**
