### PR TITLE
sql: fix misuse of errDidntUpdateDescriptor

### PR DESCRIPTION
**Pull request by tamird**

### CODE REVIEW

**Review by jordanlewis — CHANGES_REQUESTED** [review]
This does fix the problem but I think the bug is actually returning errDidntUpdateDescriptor from `exec` in the first place, something that I introduced. It should just return `nil` - schema_changer.go:372

**Comment by vivekmenezes** [comment]
@jordanlewis can you review this pr. I'm with my kids

**Comment by tamird** [comment]
@jordanlewis done, but how do you propose I test it?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16673#-:-KnBuLSZ4PECbtAqVZQC:b2h4yt5)*

**Comment by jordanlewis** [comment]
This is not a great answer, but that condition will be pretty difficult to test. You'd have to build up an entire fake table descriptor with some funny conditions in it, and the code isn't properly factored to allow that sort of testing. I would be okay with merging this without a test.

**Review by jordanlewis — APPROVED** [review]

**Comment by tamird** [comment]
Bummer, but OK.

**Pull request merged**
