### PR TITLE
update icon font

### PR DESCRIPTION
**Pull request by maxlang**
Add new icon font from Division Of. No visual change.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4251)

### CODE REVIEW

**Comment by BramGruneir** [comment]
Would be really useful if you showed a before and after screenshot for style changes.

**Comment by maxlang** [comment]
This one has no visual change - we just got some new icons so I switched the old ones over.

**Comment by maxlang** [comment]
changed dark to filled for the aliases

**Comment by BramGruneir** [comment]
LGTM

**Pull request merged**
