### PR TITLE
workload/schemachange: limit size of ints

### LINKED ISSUE #119122: pkg/ccl/testccl/workload/schemachange/schemachange_test: TestWorkload failed
pkg/ccl/testccl/workload/schemachange/schemachange_test.TestWorkload [failed](https://tanzanite.cluster.engflow.com/invocations/default/0defa141-bf03-43d3-8060-146cfb8af383?testReportRun=30&testReportShard=1&testReportAttempt=1#targets-Ly9wa2cvY2NsL3Rlc3RjY2wvd29ya2xvYWQvc2NoZW1hY2hhbmdlOnNjaGVtYWNoYW5nZV90ZXN0) on master @ [814a375d4c0e79d875c42452725f05f6c27294e3](https://github.com/cockroachdb/cockroach/commits/814a375d4c0e79d875c42452725f05f6c27294e3):

```
   {
    "query": "SELECT EXISTS (SELECT schema_name FROM information_schema.schemata WHERE schema_name = $1)",
    "queryArgs": [
     "schema_w0_21"
    ],
    "result": true
   }
  ],
  "previousStatements": [
   "DROP SCHEMA \"schema_w0_21\" CASCADE"
  ]
 }
}
    schema_change_external_test.go:132: 
        	Error Trace:	pkg/ccl/testccl/workload/schemachange/schemachange_test_test/pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go:132
        	Error:      	Received unexpected error:
        	            	***UNEXPECTED ERROR; Received an unexpected execution error.: ERROR: unimplemented: cannot drop type "schemachange.schema_w0_21._enum_w1_56" because other objects ([schemachange.public.udf_w1_74]) still depend on it (SQLSTATE 0A000)
        	            	(1) forced error mark
        	            	  | "fatal error when running txn"
        	            	  | github.com/cockroachdb/errors/withstack/*withstack.withStack::
        	            	Wraps: (2)
        	            	Wraps: (3) attached stack trace
        	            	  -- stack trace:
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*opStmt).executeStmt
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/operation_generator.go:3113
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).runInTxn
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:462
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).run
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:544
        	            	  | pkg/ccl/testccl/workload/schemachange/schemachange_test_test.TestWorkload.TestWorkload.func4.func6
        	            	  | 	pkg/ccl/testccl/workload/schemachange/schemachange_test_test/pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go:121
        	            	  | golang.org/x/sync/errgroup.(*Group).Go.func1
        	            	  | 	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75
        	            	  | runtime.goexit
        	            	  | 	src/runtime/asm_amd64.s:1650
        	            	Wraps: (4) ***UNEXPECTED ERROR; Received an unexpected execution error.
        	            	Wraps: (5) ERROR: unimplemented: cannot drop type "schemachange.schema_w0_21._enum_w1_56" because other objects ([schemachange.public.udf_w1_74]) still depend on it (SQLSTATE 0A000)
        	            	Error types: (1) *markers.withMark (2) *schemachange.ErrorState (3) *withstack.withStack (4) *errutil.withPrefix (5) *pgconn.PgError
        	Test:       	TestWorkload
Schema Workload Stats
Total Schema Statements Executed = 157
Total Schema Statements Succeeded = 157
Total Schema Statement Expected Failures = 0
Total Transactions Committed = 88
Total Transactions Rolled Back = 77
Total Transactions Executed = 165
    schema_change_external_test.go:98: backup, tracing data, and system table dumps in /var/lib/engflow/worker/work/3/exec/bazel-out/k8-fastbuild/testlogs/pkg/ccl/testccl/workload/schemachange/schemachange_test/run_30_of_30/test.outputs/logTestWorkload827641397
    panic.go:523: -- test log scope end --
test logs left over in: outputs.zip/logTestWorkload827641397
--- FAIL: TestWorkload (23.76s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=30</code>
 - <code>shard=1</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #118879 pkg/ccl/testccl/workload/schemachange/schemachange_test: TestWorkload failed [C-test-failure O-robot P-3 T-sql-foundations branch-release-23.1.15-rc]
- #117782 pkg/ccl/testccl/workload/schemachange/schemachange_test: TestWorkload failed [C-test-failure O-robot P-3 T-sql-foundations branch-release-23.2.0-rc]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestWorkload.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-36041

### PR DESCRIPTION
**Pull request by annrpom**
We have seen cases where randomly generated ints easily hit an
integer overflow in our schemachange workload when we allow 
large numbers. Since there is no real advantage to testing these
large numbers, this patch limits the largeness by ensuring the 
range of numbers we generate from will be very unlikely to catch 
up with even the `smallint` type - INT2.

Fixes: #119122
Epic: None

Release note: None

### CODE REVIEW

**Review by rafiss — COMMENTED** [review]
thanks for the quick fix!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119178#-:-Nq_ScHm0tkZ5a_nun-N:bn0ld3r)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom, @herkolategan, and @srosenberg)

___
*[`pkg/workload/schemachange/operation_generator.go` line 2867 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119178#-Nq_SGvfDO09OK5JOglh:-Nq_SGvfDO09OK5JOgli:bvm2hqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/46eef4c157b9ae4927ac529dbe94f8fb2eafa37f/pkg/workload/schemachange/operation_generator.go#L2867)):*
> ```Go
> 			// Since there is no real advantage to testing these large numbers,
> 			// limit the number by flooring the width to 16 (-32768 to 32767).
> 			if col.typ.Family() == types.IntFamily && col.typ.Width() > int32(16) {
> ```

just curious, why did we need the `&& col.typ.Width() > int32(16)`? it seems like this could mean that the `INT2` type could still overflow kind of easily

**Review by annrpom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119178)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @rafiss, and @srosenberg)

___
*[`pkg/workload/schemachange/operation_generator.go` line 2867 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119178#-Nq_SGvfDO09OK5JOglh:-Nq_Yahd90KEJlLKfjfV:b54flb5) ([raw file](https://github.com/cockroachdb/cockroach/blob/46eef4c157b9ae4927ac529dbe94f8fb2eafa37f/pkg/workload/schemachange/operation_generator.go#L2867)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

just curious, why did we need the `&& col.typ.Width() > int32(16)`? it seems like this could mean that the `INT2` type could still overflow kind of easily
</blockquote></details>

we only need it in a world where i can't do math! fixed

**Review by rafiss — APPROVED** [review]
lgtm! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119178#-:-NqcBZxU270_Ns-la6Ua:b-nzoors)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @srosenberg)

**Comment by annrpom** [comment]
TFTR! ('-')7 

bors r=rafiss

**Pull request merged**
