### PR TITLE
sql: add more sql tests for system tables and some refactoring

### PR DESCRIPTION
**Pull request by vivekmenezes**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7589)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/sqlbase/privilege.go, line 83 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7589#-KLc_6LMGIV4THIjzgC8:-KLc_6LMGIV4THIjzgC9:411700498) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc1e0407d9bf8ff403179b12f4624be5ba275314/sql/sqlbase/privilege.go#L83)):*
> ```Go
> 
> // NewPrivilegeDescriptor returns a privilege descriptor for the given ID.
> func NewPrivilegeDescriptor(id ID) *PrivilegeDescriptor {
> ```

is this really a better API?

---

*[sql/sqlbase/privilege.go, line 88 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7589#-KLc_9zivr1jg4WHryOm:-KLc_9zivr1jg4WHryOn:658986358) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc1e0407d9bf8ff403179b12f4624be5ba275314/sql/sqlbase/privilege.go#L88)):*
> ```Go
> 			{
> 				User:       security.RootUser,
> 				Privileges: (SystemConfigAllowedPrivileges[id]).ToBitField(),
> ```

are the parentheses here required?

---

*[sql/sqlbase/system.go, line 80 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7589#-KLc_UVSf5VQBQFzVsh3:-KLc_UVSf5VQBQFzVsh4:-2025623552) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc1e0407d9bf8ff403179b12f4624be5ba275314/sql/sqlbase/system.go#L80)):*
> ```Go
> 		Name: "system",
> 		ID:   keys.SystemDatabaseID,
> 		// Assign max privileges to root user.
> ```

root user is now nowhere in sight

---

*[sql/sqlbase/system.go, line 120 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7589#-KLc_YiLVJq9ORGVIqFX:-KLc_YiMOPE950MM6FAC:-2025623552) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc1e0407d9bf8ff403179b12f4624be5ba275314/sql/sqlbase/system.go#L120)):*
> ```Go
> 
> 	// System tables have the system database as a parent, with privileges from
> 	// the SystemAllowedPrivileges table assigned to the root user.
> ```

root user is now nowhere in sight

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7589)*

**Comment by vivekmenezes** [comment]
Review status: 1 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/sqlbase/privilege.go, line 83 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7589#-KLc_6LMGIV4THIjzgC8:-KLrvVuWQd3TWRF981MW:-2111018244) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc1e0407d9bf8ff403179b12f4624be5ba275314/sql/sqlbase/privilege.go#L83)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> is this really a better API?
</details>
The old one was always called with the same user. I think it's a better API for how it's being used, besides it's an internal API so we can change it whenever we want.

---

*[sql/sqlbase/privilege.go, line 88 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7589#-KLc_9zivr1jg4WHryOm:-KLrw21386TAsQuQvsn9:-1563104645) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc1e0407d9bf8ff403179b12f4624be5ba275314/sql/sqlbase/privilege.go#L88)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> are the parentheses here required?
</details>
Not needed. Fixed

---

*[sql/sqlbase/system.go, line 80 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7589#-KLc_UVSf5VQBQFzVsh3:-KLrwYXCoF5z-50DR0aS:-1090835252) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc1e0407d9bf8ff403179b12f4624be5ba275314/sql/sqlbase/system.go#L80)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> root user is now nowhere in sight
</details>
changed to "Assign SystemConfigAllowedPrivileges"

---

*[sql/sqlbase/system.go, line 120 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7589#-KLc_YiLVJq9ORGVIqFX:-KLrxC0Yc455Xx_z8XhU:1406347332) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc1e0407d9bf8ff403179b12f4624be5ba275314/sql/sqlbase/system.go#L120)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> root user is now nowhere in sight
</details>
true, but leaving the comment as is makes it easier to read.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7589)*

**Comment by vivekmenezes** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/sqlbase/privilege.go, line 83 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7589#-KLc_6LMGIV4THIjzgC8:-KLvOfW6mSIMGhzq-iTd:436578787) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc1e0407d9bf8ff403179b12f4624be5ba275314/sql/sqlbase/privilege.go#L83)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Looks like pointless churn to me.
</details>
It's unlikely to change anytime soon. I can rename it NewRootPrivilegeDescriptor and s/NewDefaultPrivilegeDescriptor/NewDefaultRootPrivilegeDescriptor for the other routine to make it more explicit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7589)*

**Comment by tamird** [comment]
why change it at all?

**Comment by vivekmenezes** [comment]
reverted. Also s/SystemConfigAllowedPrivileges/systemConfigAllowedPrivileges

---

Review status: 1 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7589#-:-KLvX9iJxMAC3a1lasOo:1376417704)*

**Comment by vivekmenezes** [comment]
@tamird I've assigned this to you because marc is not around this week and you've already taken a look at it. Thanks!

**Comment by tamird** [comment]
second commit message should no longer mention `NewPrivilegeDescriptor()`.

:lgtm:

---

Reviewed 8 of 8 files at r5, 8 of 8 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7589#-:-KLvLfwy86iFHdM1xAF_:-274859941)*

**Pull request merged**
