### PR TITLE
ui: use new React ref API

### PR DESCRIPTION
**Pull request by janowsiany**
Solves #28845
Currently can not run test due to #30619, any workarounds?

### CODE REVIEW

**Comment by vilterp** [comment]
Thanks @janowsiany!

One nitpick and then we can merge this — can you change the commit message to

```
ui: use new React ref API

Release note (admin ui change): None
```

Should just be able to rebase, make the change, and force push. Thanks!

**Comment by vilterp** [comment]
Actually, I just noticed that there are some type errors which caused the CI to fail for this PR. I don't think the CI server is visible to non-CR employees, so pasted below:

```
ccl/src/views/clusterviz/containers/map/mapLayout.tsx(204,10): error TS2322: Type '{ ref: RefObject<Node>; children: (Element | Element[])[]; }' is not assignable to type 'SVGProps<SVGGElement>'.
[17:12:30]  Types of property 'ref' are incompatible.
[17:12:30]    Type 'RefObject<Node>' is not assignable to type 'Ref<SVGGElement>'.
[17:12:30]      Type 'RefObject<Node>' is not assignable to type 'RefObject<SVGGElement>'.
[17:12:30]        Type 'Node' is not assignable to type 'SVGGElement'.
[17:12:30]          Property 'farthestViewportElement' is missing in type 'Node'.
[17:12:30]ccl/src/views/clusterviz/containers/map/nodeCanvas.tsx(150,13): error TS2322: Type '{ style: { width: string; height: string; marginBottom: number; position: "absolute"; }; classNam...' is not assignable to type 'SVGProps<SVGSVGElement>'.
[17:12:30]  Types of property 'ref' are incompatible.
[17:12:30]    Type 'RefObject<SVGElement>' is not assignable to type 'Ref<SVGSVGElement>'.
[17:12:30]      Type 'RefObject<SVGElement>' is not assignable to type 'RefObject<SVGSVGElement>'.
[17:12:30]        Type 'SVGElement' is not assignable to type 'SVGSVGElement'.
[17:12:30]          Property 'contentScriptType' is missing in type 'SVGElement'.
[17:12:30]src/views/cluster/components/linegraph/index.tsx(197,16): error TS2322: Type '{ className: string; color?: string; height?: string | number; id?: string; lang?: string; max?: ...' is not assignable to type 'SVGProps<SVGSVGElement>'.
[17:12:30]  Types of property 'ref' are incompatible.
[17:12:30]    Type 'string | RefObject<SVGElement> | ((instance: SVGSVGElement) => any) | RefObject<SVGSVGElement>' is not assignable to type 'Ref<SVGSVGElement>'.
[17:12:30]      Type 'RefObject<SVGElement>' is not assignable to type 'Ref<SVGSVGElement>'.
[17:12:30]        Type 'RefObject<SVGElement>' is not assignable to type 'RefObject<SVGSVGElement>'.
[17:12:30]src/views/shared/components/sql/box.tsx(27,12): error TS2322: Type '{ className: "sql-highlight"; ref: RefObject<Node>; children: string; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLPreElement>, HTMLPreElement>'.
[17:12:30]  Type '{ className: "sql-highlight"; ref: RefObject<Node>; children: string; }' is not assignable to type 'ClassAttributes<HTMLPreElement>'.
[17:12:30]    Types of property 'ref' are incompatible.
[17:12:30]      Type 'RefObject<Node>' is not assignable to type 'Ref<HTMLPreElement>'.
[17:12:30]        Type 'RefObject<Node>' is not assignable to type 'RefObject<HTMLPreElement>'.
[17:12:30]          Type 'Node' is not assignable to type 'HTMLPreElement'.
[17:12:30]            Property 'width' is missing in type 'Node'.
```

I'm not sure what the root issues are here; think you could investigate? You can run the typechecker locally with `make ui-lint` to verify that they are fixed.

**Comment by janowsiany** [comment]
ping @vilterp

**Comment by vilterp** [comment]
Looks good, thanks!

bors r+

**Pull request merged**
