### PR TITLE
sql: several compatibility features

### LINKED ISSUE #15006: sql: support quote_ident builtin
Add support for the [`quote_ident`](https://www.postgresql.org/docs/9.6/static/functions-string.html) builtin, which

> Return the given string suitably quoted to be used as an identifier in an SQL statement string. Quotes are added only if necessary (i.e., if the string contains non-identifier characters or would be case-folded). Embedded quotes are properly doubled.

This should be fairly straightforward, as we already have internal formatters that do this same work properly in `parser/format.go`.

This is used by at least one ORM-like tool, FlywayDB.

### PR DESCRIPTION
**Pull request by jordanlewis**
Fixes #15006.

- For PostgreSQL compatibility, we shouldn't have several type names in
the restricted keyword list. This causes several adverse effects.
Specifically, during operations like `SHOW CREATE TABLE`, these
miscategorized type names would be erroneously quoted even though they
don't need to be quoted on an actual `CREATE TABLE` statement.
- Add the `quote_ident` builtin
- Support `_foo` array typenames, as well as quoted typenames
- Don't include `IN` in `pg_operator`
- Correctly mark pseudotypes with `typtype='p'` in `pg_type`

This is all in the name of unblocking sqlsmith (#21852).

### CODE REVIEW

**Comment by jordanlewis** [comment]
n.b. while the restricted name changes may look scary, they shouldn't be. This doesn't actually change what users can and cannot do for column and table names. Taking the `name` type as an example (which this PR moves to be an unrestricted name), users before this patch could create a table like:

```
CREATE TABLE name (name text);
```

But the `SHOW CREATE TABLE` would incorrectly quote `name` (as `"name"`) for both the table name and column name.

Now, `SHOW CREATE TABLE` doesn't quote `name`, as expected.

**Comment by knz** [comment]
I'll review this early next week - mind fixing the remaining broken test until then?

**Comment by nvanbenschoten** [comment]
Awesome! Nice compat changes.

---

Reviewed 6 of 6 files at r1, 3 of 3 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/pg_catalog.go, line 1191 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/24190#-L8YRmiUQLCWPz0TZcFQ:-L8YRmiUQLCWPz0TZcFR:b-56uizu) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4440a331c2318b761495e028e6a5d00747180d9/pkg/sql/pg_catalog.go#L1191)):*
> ```Go
> 		for cmpOp, overloads := range tree.CmpOps {
> 			if cmpOp == tree.In {
> 				continue
> ```

Add a comment explaining this. 

Also, does it belong somewhere else now? If it's not considered an operator, what is it considered?

---

*[pkg/sql/pg_catalog.go, line 1713 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/24190#-L8YSJzVuizCFiyeW9CX:-L8YSJzVuizCFiyeW9CY:b-3jevia) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa31e10b8554d9d401933a3d8338c230c5252757/pkg/sql/pg_catalog.go#L1713)):*
> ```Go
> 	_ = typCategoryGeometric
> 	_ = typCategoryNetworkAddr
> 	_ = typCategoryPseudo
> ```

We can remove this now too, right?

---

*[pkg/sql/parser/parse_test.go, line 1581 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/24190#-L8YRGILbkC9HtlktZbE:-L8YRGILbkC9HtlktZbF:bi9estx) ([raw file](https://github.com/cockroachdb/cockroach/blob/84c16f7bb1671b27ff9948c0214a7f1ea4ac453e/pkg/sql/parser/parse_test.go#L1581)):*
> ```Go
> HINT: try \h SELECT`},
> 		{"SELECT foo''",
> 			`type does not exist at or near ""
> ```

:pray: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24190#-:-L8YSuKxwm-GvV2k7gxO:bsnsq0z)*

**Comment by jordanlewis** [comment]
Review status: 5 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/pg_catalog.go, line 1191 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/24190#-L8YRmiUQLCWPz0TZcFQ:-L8YVg6rLkzXcAbmmUuG:b-tom8rj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4440a331c2318b761495e028e6a5d00747180d9/pkg/sql/pg_catalog.go#L1191)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Add a comment explaining this. 

Also, does it belong somewhere else now? If it's not considered an operator, what is it considered?
</blockquote></details>

`In` is not a generalized operator because it only allows a special kind of expression on its RHS: a parenthesized subquery or a row expression. All the other operators are syntactically permitted anywhere a comparison could happen.

Added an explanatory comment. I don't think it belongs in other tables, as Postgres (AFAICT) doesn't export any kind of metadata about its own syntax.

---

*[pkg/sql/pg_catalog.go, line 1713 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/24190#-L8YSJzVuizCFiyeW9CX:-L8Ym4O0ta-VcuzLzI5j:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa31e10b8554d9d401933a3d8338c230c5252757/pkg/sql/pg_catalog.go#L1713)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We can remove this now too, right?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24190)*

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Review status: 5 of 13 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24190#-:-L8Z2jP_kODXB0L9msJs:bnfp4nl)*

**Comment by jordanlewis** [comment]
TFTR!

**Comment by knz** [comment]
:lgtm: with nit! you can followup in a separate PR or file an issue.

---

Reviewed 5 of 6 files at r1, 8 of 8 files at r6, 2 of 3 files at r7, 3 of 3 files at r8, 1 of 1 files at r9, 1 of 3 files at r10.
Review status: 11 of 13 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/sql.y, line 5469 at r8](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24190#-L8axjCQ3sGeVOWPgnQG:-L8axjCQ3sGeVOWPgnQH:bphlhms) ([raw file](https://github.com/cockroachdb/cockroach/blob/23d7d9f46f4c3d74e9fa85eb32521ed767f9590d/pkg/sql/parser/sql.y#L5469)):*
> ```Yacc
>     } else {
>       var err error
>       $$.val, err = coltypes.TypeForNonKeywordTypeName($1)
> ```

Mind swallowing the case for "char" above into this? "char" can be part of the map too.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24190#-:-L8ay1KjBNjk88EF20v3:bmf9y4)*

**Pull request merged**
