### PR TITLE
sql/schemachanger: introduce benchmark for dropping complex schemas

### PR DESCRIPTION
**Pull request by fqazi**
Previously, we lacked testing for dropping schemas
with a complex web of dependencies. In a real world
scenario we noticed problematic performance with
complex schemas when trying to drop or even do validation
operations on them leading to high CPU usage. To help
get some testing focus on this problem, we are going
to introduce a new test focused on dropping complex
schemas.

Release justification: no real risk only introduces a new test
Release note: None

### CODE REVIEW

**Comment by fqazi** [comment]
I have a branch with also some CPU reduction fixes for validation, but I pulled those out for now. I'll make a separate PR for those

**Review by postamar — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77610)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[pkg/sql/sqltestutils/large_schema.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77610#-Mxu_oOGBBZ4LkcGABcV:-Mxu_oOGBBZ4LkcGABcW:b-7j8e5g) ([raw file](https://github.com/cockroachdb/cockroach/blob/6438e7d8ab05a4bc2865e17c6917267d6bf8d739/pkg/sql/sqltestutils/large_schema.go#L23)):*
> ```Go
> 
> // GenerateViewBasedGraphSchema generates a large nested schema with a number
> // of nested references.
> ```

Can you reword this and provide a more substantial explanation? What kind of nesting? References of what? This stuff is obvious to us now but I guarantee it won't be to anyone outside of you me and Andrew.
___
*[pkg/sql/sqltestutils/large_schema.go, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77610#-Mxu_Zog3C4xPfcMn95L:-Mxu_Zog3C4xPfcMn95M:b-fqtlhl) ([raw file](https://github.com/cockroachdb/cockroach/blob/6438e7d8ab05a4bc2865e17c6917267d6bf8d739/pkg/sql/sqltestutils/large_schema.go#L30)):*
> ```Go
> 	numTablesPerDepth int,
> 	numColumnsPerTable int,
> 	graphDepth int,
> ```

Suggestion: put these last 3 or 4 arguments in a struct, that way when calling this function it's more obvious what each number refers to.
___
*[pkg/sql/sqltestutils/large_schema.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77610#-MxubM6z-7OK05fyNAwq:-MxubM6z-7OK05fyNAwr:b-ro2sz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6438e7d8ab05a4bc2865e17c6917267d6bf8d739/pkg/sql/sqltestutils/large_schema.go#L59)):*
> ```Go
> 		tblColumnCache[tableName] = columns.String()
> 		createStatement.WriteString(")")
> 		sqlDB.Exec(t, "use largedb;")
> ```

I'm guessing this is unintentional
___
*[pkg/sql/sqltestutils/large_schema.go, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77610#-MxuaKWMBZ_Q4RHd9u_4:-MxuaKWMBZ_Q4RHd9u_5:b-tsghom) ([raw file](https://github.com/cockroachdb/cockroach/blob/6438e7d8ab05a4bc2865e17c6917267d6bf8d739/pkg/sql/sqltestutils/large_schema.go#L117)):*
> ```Go
> 	sqlDB.Exec(t,
> 		`COMMIT;`)
> }
> ```

I would much prefer this function to produce a `parser.Statements` instead and feed that to a `SQLRunner` in a subsequent step. This way you can (and should!) unit-test your statement generator to make sure it produces what you expect.
___
*[pkg/sql/drop_test.go, line 1407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77610#-MxubfN01waFz-xa9H6D:-MxubfN01waFz-xa9H6E:b-cpwwvr) ([raw file](https://github.com/cockroachdb/cockroach/blob/6438e7d8ab05a4bc2865e17c6917267d6bf8d739/pkg/sql/drop_test.go#L1407)):*
> ```Go
> 	// each other, which can lead to long DROP times specially if there
> 	// is anything takes quadratic time.
> 	TestDropLargeDatabaseWithSchemaChanger := func(useDeclarative bool) {
> ```

You probably want to have two different top-level tests here (one for the legacy and one for the declarative schema changer) so that they time out separately, if they do time out. 
___
*[pkg/sql/drop_test.go, line 1431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77610#-MxucGFeDees5K-oEtjV:-MxucGFf0O-3v6GatAqx:bcp6lrx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6438e7d8ab05a4bc2865e17c6917267d6bf8d739/pkg/sql/drop_test.go#L1431)):*
> ```Go
> 	// TODO(fqazi): Currently this takes more than 5 minutes, so disabled for now.
> 	// Test complex schema with declarative.
> 	//TestDropLargeDatabaseWithSchemaChanger(true)
> ```

Perhaps we can enable it by making the graph less complex? That way your test doesn't time out and your TODO becomes something along the lines of "TODO: increase graph complexity"

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77610)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

___
*[pkg/sql/sqltestutils/large_schema.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77610#-Mxu_oOGBBZ4LkcGABcV:-MxwTG5Q0VZelq2M3cBn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6438e7d8ab05a4bc2865e17c6917267d6bf8d739/pkg/sql/sqltestutils/large_schema.go#L23)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Can you reword this and provide a more substantial explanation? What kind of nesting? References of what? This stuff is obvious to us now but I guarantee it won't be to anyone outside of you me and Andrew.
</blockquote></details>

Done.
___
*[pkg/sql/sqltestutils/large_schema.go, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77610#-Mxu_Zog3C4xPfcMn95L:-MxwTGlU5B7SErqbMIJf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6438e7d8ab05a4bc2865e17c6917267d6bf8d739/pkg/sql/sqltestutils/large_schema.go#L30)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Suggestion: put these last 3 or 4 arguments in a struct, that way when calling this function it's more obvious what each number refers to.
</blockquote></details>

Done.
___
*[pkg/sql/sqltestutils/large_schema.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77610#-MxubM6z-7OK05fyNAwq:-MxwTHVwCzMX2cioh0QS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6438e7d8ab05a4bc2865e17c6917267d6bf8d739/pkg/sql/sqltestutils/large_schema.go#L59)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I'm guessing this is unintentional
</blockquote></details>

Done.
___
*[pkg/sql/sqltestutils/large_schema.go, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77610#-MxuaKWMBZ_Q4RHd9u_4:-MxwTIFq0MehnnVcnuHG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6438e7d8ab05a4bc2865e17c6917267d6bf8d739/pkg/sql/sqltestutils/large_schema.go#L117)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I would much prefer this function to produce a `parser.Statements` instead and feed that to a `SQLRunner` in a subsequent step. This way you can (and should!) unit-test your statement generator to make sure it produces what you expect.
</blockquote></details>

Done.
___
*[pkg/sql/drop_test.go, line 1407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77610#-MxubfN01waFz-xa9H6D:-MxwTLgc5Jhr-eka8_cu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6438e7d8ab05a4bc2865e17c6917267d6bf8d739/pkg/sql/drop_test.go#L1407)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

You probably want to have two different top-level tests here (one for the legacy and one for the declarative schema changer) so that they time out separately, if they do time out. 
</blockquote></details>

Done.
___
*[pkg/sql/drop_test.go, line 1431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77610#-MxucGFeDees5K-oEtjV:-MxwTMZb3dFu5uti4EJr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6438e7d8ab05a4bc2865e17c6917267d6bf8d739/pkg/sql/drop_test.go#L1431)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Perhaps we can enable it by making the graph less complex? That way your test doesn't time out and your TODO becomes something along the lines of "TODO: increase graph complexity"
</blockquote></details>

Done.

**Review by postamar — APPROVED** [review]
:lgtm_strong: 

Very nice.

Can you add a unit test or a data driven test specifically for `GenerateViewBasedGraphSchema` please? I'm fine if this is in a follow-up PR. It's always nice to see an example of what the SQL is going to look like for these schemas.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77610#-:-MyCo9PK4qe7Vv0jYBNx:bdwdw19)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @fqazi and @postamar)

___
*[pkg/sql/sqltestutils/large_schema.go, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77610#-Mxu_Zog3C4xPfcMn95L:-MyCnpxsDbb6J6FXEhd9:b-jw6wf8) ([raw file](https://github.com/cockroachdb/cockroach/blob/6438e7d8ab05a4bc2865e17c6917267d6bf8d739/pkg/sql/sqltestutils/large_schema.go#L30)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks, I like what you did.

**Comment by postamar** [comment]
👍 on the new test

**Comment by fqazi** [comment]
@postamar TFTR!

**Pull request merged**
