### PR TITLE
sql: don't remove renders during exec planning

### LINKED ISSUE #131785: sql: renders can be removed during physical planning
As an optimization, we can avoid adding a new render node in some cases by just [re-ordering existing renders](https://github.com/cockroachdb/cockroach/blob/67dbb78134a5a1abbaa0ff795a24cf873a25fd2d/pkg/sql/opt_exec_factory.go#L269-L272) during physical planning. However, this optimization can cause some render expressions to be dropped if their results aren't required by the parent operator. In rare cases, the renders may be needed for their side effects (e.g. a function call), and so dropping them is incorrect. We've actually encountered the same problem in #108901 - but the fix for that was in a different stage of planning.

I am not aware of existing cases where this causes incorrect results, but we should fix it anyway, since it could lead to bugs down the line.

Jira issue: CRDB-42700

### PR DESCRIPTION
**Pull request by DrewKimball**
Previously, exec planning through the `execFactory` could remove a rendered expression if its result was not needed for the parent operator. This was the result of an optimization that avoids adding a new `renderNode` if one already exists. However, there are some cases that rely on renders being evaluated even if the result is ignored (see #108901).

This commit tightens the restriction on when the optimization is applied, so that we avoid adding a `renderNode` only when render expressions are projected exactly once. In addition to avoiding hidden bugs, this improvement also makes optimization barriers (`BarrierExpr`) easier to use, since we can rely on it to make sure a given expression is evaluated.

Fixes #131785

Release note: None

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
Nice!

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131626#-:-O83xryk4plrDv4jHtLp:b-83sjoh)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131626#-O83vmNi-A1tn_008V7D):*
Should there be another issue to describe what this PR is fixing?
___
*[`-- commits` line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131626#-O83xnf00nev9SYtYq1Q):*
Does this need a release note?
___
*[`pkg/sql/opt_exec_factory.go` line 330 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131626#-O83wwiM63eVFMaYk4kd:-O83wwiM63eVFMaYk4ke:b-pdzxrb) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b00e573956b91e64229da79f77c7c5ff22090be/pkg/sql/opt_exec_factory.go#L330)):*
> ```Go
> 		}
> 		set.Add(int(c))
> 	}
> ```

do you still need this block given that you added `colsSeen` below?

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131626)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131626#-O83vmNi-A1tn_008V7D):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Should there be another issue to describe what this PR is fixing?
</blockquote></details>

I've opened one here: #131785.
___
*[`-- commits` line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131626#-O83xnf00nev9SYtYq1Q):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Does this need a release note?
</blockquote></details>

I can be convinced otherwise, but I don't think so. We don't know of any actual bugs caused by this - the fix is just to make sure it doesn't cause a bug to be introduced later, and also makes it easier to break up #131552 into multiple commits.
___
*[`pkg/sql/opt_exec_factory.go` line 330 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131626#-O83wwiM63eVFMaYk4kd:-O8EDQCm4m8DjvwY08Lm:b4r8myg) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b00e573956b91e64229da79f77c7c5ff22090be/pkg/sql/opt_exec_factory.go#L330)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

do you still need this block given that you added `colsSeen` below?
</blockquote></details>

Nope, my mistake. Removed it.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131626#-:-O8HziWy6gDmupN3CZgX:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

**Comment by DrewKimball** [comment]
TFTR!

bors r+

**Pull request merged**
