### PR TITLE
cli,sql: improve the UX for viewing and updating zone configurations

### LINKED ISSUE #23791: sql: stabilize configuring zones through SQL
Our current syntax for configuring zone configs through SQL is clunky and very much intended to be temporary:

```
ALTER TABLE ... EXPERIMENTAL CONFIGURE ZONE 'constraints: ["+foo=bar"]
num_replicas: 2'
```

I propose stabilizing a very similar command with a thin layer of syntax sugar:

```
ALTER TABLE ... CONFIGURE ZONE WITH gc.ttlseconds = 90, num_replicas = 5;
```

This reuses the `WITH ...` options syntax that we use in `BACKUP` and `RESTORE`, and feels very similar to cluster settings. The only sticking point is handling constraints. The simple approach is to keep the existing constraint syntax:

```
ALTER TABLE ... CONFIGURE ZONE WITH constraints = '{"+a=1,+b=2": 2}';
```

That's pretty gross, though. We could introduce custom syntax:

```
ALTER TABLE ... CONFIGURE ZONE ADD POSITIVE CONSTRAINT a = 1 AND b = 2 FOR 2 REPLICAS;
```

Or we could just call the `constraints` field a JSON config value. That opens some cool possibilities

```
ALTER TABLE ... CONFIGURE ZONE WITH constraints = zone_constraint("+a=1, +b=2", 2) || zone_constraint("region=germany");
```

where `zone_constraint(reqs[, num_replicas])` is a built-in that produces the JSON object `{"reqs": num_replicas}`. I think I have a preference for this option.

/cc @petermattis @a-robinson @BramGruneir

### PR DESCRIPTION
**Pull request by knz**
Fixes  #23791.

Summary of visible changes:

- new statement forms:
  - `ALTER ... CONFIGURE ZONE USING num_replicas = 123, ...` to edit a zone config. The compact constraint syntax is still supported, e.g. `USING constraints = '[+foo]'`.
  - `ALTER ... CONFIGURE ZONE USING DEFAULT` to reset a zone config to inherited defaults
  - `ALTER ... CONFIGURE ZONE DISCARD` to remove a zone config

- compatibility forms with previous versions of CockroachDB, probably should not be documented but will ease transition:
  - `ALTER ... CONFIGURE ZONE = '...yaml...'` to set multiple zone parameters at once using YAML
  - `ALTER ... CONFIGURE ZONE = ''` ensures the zone config exists but is otherwise a no-op (it does not reset it to defaults if it already existed)
  - `ALTER ... CONFIGURE ZONE = NULL` to remove a zone config

- the `ALTER ... CONFIGURE ZONE` statement forms now can be prepared on pgwire and accept placeholders.

- `crdb_internal.zones` and `SHOW ZONE CONFIGURATION(s)` have a new column `config_sql` in addition to the existing `config_yaml` and `config_protobuf`. This new columns reports the ALTER syntax that reproduces the zone config with the new syntax.

- `cockroach zone` sub-commands are now deprecated.

- `cockroach zone rm` now prints no output unless there is an error.

### CODE REVIEW

**Comment by knz** [comment]
@benesch this is what I have so far. You mentioned I can do something with something called "sources" to not have to rewrite the import paths? how does that work?

**Comment by benesch** [comment]
Yes, you would just do what we did with e.g. go-bindata: https://github.com/cockroachdb/cockroach/blob/master/Gopkg.toml#L55

You just list a constraint in Gopkg.toml that tells Dep to use a different repository for that import path. Then you don't need to rewrite import paths anywhere.

What you've done here looks fine to me too though!

**Comment by knz** [comment]
yes that worked, thanks

**Comment by knz** [comment]
@a-robinson  @benesch can you start reviewing the first commits in this PR while I work on the 2nd part (expressivity of the SQL syntax)

**Review by benesch — CHANGES_REQUESTED** [review]
Looks good so far. Thanks for taking this on, @knz!

I do fear that you're causing unnecessary pain by removing `EXPERIMENTAL`. Can't we spread that pain over two versions? Is replacing it with an optional grammar rule

```
opt_experimental: EXPERIMENTAL | / * empty */
```

somehow intractable? That way the 2.0 client would continue to work against 2.1 with no extra effort, as would our roachtests.

> Reviewed 3 of 3 files at r1, 28 of 29 files at r2, 3 of 3 files at r3, 10 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28612#-:-LKNW7gB13c8wZdsOCD_:b-5l38ie)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/cli_test.go, line 528 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28612#-LKNTwGy4S1Z5DA2NNOt:-LKNTwGy4S1Z5DA2NNOu:b-qkalww) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c891d6532e3aeb781d6be9d4256e393d1967a4/pkg/cli/cli_test.go#L528)):*
> ```Go
> 	// num_replicas: 1
> 	// constraints: [+zone=us-east-1a, +ssd]
> 	// "
> ```

I'm not a huge fan of the new formatting. The old formatting isn't great, but I'm worried you're breaking backwards compatibility here for little benefit. Someone who wants to parse this YAML will now need to strip out the `"` and the extra line.
___
*[pkg/sql/set_zone_config.go, line 52 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28612#-LKNVHg_-aK-K4VlB41M:-LKNVHg_-aK-K4VlB41N:bd8siuy) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1ad8e0e2a34770c787be23afb64a16e9144c7e8/pkg/sql/set_zone_config.go#L52)):*
> ```Go
> 
> 	typ := yamlConfig.ResolvedType()
> 	switch typ {
> ```

totally optional nit

```
switch typ := yamlConfig.ResolvedType(); switch typ {
```
___
*[pkg/sql/set_zone_config.go, line 166 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28612#-LKNVrUp6KFHpaNfADSd:-LKNVrUp6KFHpaNfADSe:bigqc9g) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1ad8e0e2a34770c787be23afb64a16e9144c7e8/pkg/sql/set_zone_config.go#L166)):*
> ```Go
> 		); err != nil {
> 			return err
> 		}
> ```

I haven't fully verified whether moving this stanza up and removing the reprising in the func itself is equivalent to the old code. @a-robinson should double-check this.
___
*[pkg/sql/show_zone_config.go, line 123 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28612#-LKNV3la60vsDSCQupVZ:-LKNV3lb2k7jCqf1qy4x:b1vvmed) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1ad8e0e2a34770c787be23afb64a16e9144c7e8/pkg/sql/show_zone_config.go#L123)):*
> ```Go
> // generateZoneConfigIntrospectionValues creates a result row
> // suitable for populating crdb_internal.zones or SHOW ZONE CONFIG.
> // The values are populates into the `values` first argument.
> ```

"populated"

**Review by knz — COMMENTED** [review]
Thanks for the early feedback.

I am very strongly against accomnodating EXPERIMENTAL. This is *experimental* after all which means "no guarantees". I do not want to create a precedent for us starting to accommodate backward compatibility for experimental syntax -- that's defeating the point of having the experimental bit in the first place.

There was a mistake made here, which was to start relying on an experimental feature as a client/server API. This *was* a a mistake and the approach I am taking in this PR is the price we have to pay today for this past mistake. 

The grammar accommodation you propose, while technically apparently minor, would have a much higher price because it would set a nasty precedent.

Will address the other comments in a next iteration.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28612#-:-LKNXEn0B1QhHXQ5G66E:brxslhv)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/cli_test.go, line 528 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28612#-LKNTwGy4S1Z5DA2NNOt:-LKNX0QKC7Px0bMNHYrl:bs3ovih) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c891d6532e3aeb781d6be9d4256e393d1967a4/pkg/cli/cli_test.go#L528)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I'm not a huge fan of the new formatting. The old formatting isn't great, but I'm worried you're breaking backwards compatibility here for little benefit. Someone who wants to parse this YAML will now need to strip out the `"` and the extra line.
</blockquote></details>

`--format=raw` is suitable for automation.

When the output is a terminal, the result can still be copy-pasted.
___
*[pkg/sql/set_zone_config.go, line 166 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28612#-LKNVrUp6KFHpaNfADSd:-LKNX9vF8JH2glfpd9Pu:bnptyl8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1ad8e0e2a34770c787be23afb64a16e9144c7e8/pkg/sql/set_zone_config.go#L166)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I haven't fully verified whether moving this stanza up and removing the reprising in the func itself is equivalent to the old code. @a-robinson should double-check this.
</blockquote></details>

It seems to not be equivalent according to the tests :)

I need to work on this a little more.

**Review by benesch — COMMENTED** [review]
> I am very strongly against accomnodating EXPERIMENTAL. This is experimental after all which means "no guarantees". I do not want to create a precedent for us starting to accommodate backward compatibility for experimental syntax -- that's defeating the point of having the experimental bit in the first place.

I see your point, but here we're introducing a unforced backwards incompatibility for the sole purpose of preserving the sanctity of `EXPERIMENTAL`. That's extremely unfortunate. I see `EXPERIMENTAL` as a license to change, not a mandate to change. 

> There was a mistake made here, which was to start relying on an experimental feature as a client/server API. This was a a mistake and the approach I am taking in this PR is the price we have to pay today for this past mistake.

Partitioning wouldn't have landed without this approach. Perhaps we need a different keyword for statements that are not suitable for external users but that we're willing to at least go through a deprecation cycle with for our own CLI's sake?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28612#-:-LKNeTqy2r2jyH1TrEpE:b-tbrlyf)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/cli_test.go, line 528 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28612#-LKNTwGy4S1Z5DA2NNOt:-LKNmS2K4YLiV3BJLCSP:b48nbz4) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c891d6532e3aeb781d6be9d4256e393d1967a4/pkg/cli/cli_test.go#L528)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`--format=raw` is suitable for automation.

When the output is a terminal, the result can still be copy-pasted.

</blockquote></details>

I'm still not convinced that's reason enough to change the default output format.

**Comment by knz** [comment]
> Perhaps we need a different keyword for statements that are not suitable for external users but that we're willing to at least go through a deprecation cycle with for our own CLI's sake?

There's something even better: no keyword, but mandate some session variable is set to use the feature.

**Comment by benesch** [comment]
> There's something even better: no keyword, but mandate some session variable is set to use the feature.

Ack. That is a nice solution.

**Review by knz — COMMENTED** [review]
Still iterating; I need to unbork a rebase due to outdated `dep`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28612#-:-LKScI7SEOATcZ1OAMU0:b-x3j4l3)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/cli_test.go, line 528 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28612#-LKNTwGy4S1Z5DA2NNOt:-LKScEKWD2X_dAL4UIvf:b2eii9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c891d6532e3aeb781d6be9d4256e393d1967a4/pkg/cli/cli_test.go#L528)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I'm still not convinced that's reason enough to change the default output format.
</blockquote></details>

All right I'll revert that; we can discuss formats in a separate CLI PR.
___
*[pkg/sql/show_zone_config.go, line 123 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28612#-LKNV3la60vsDSCQupVZ:-LKSaYMO91CUCjWi-v2R:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1ad8e0e2a34770c787be23afb64a16e9144c7e8/pkg/sql/show_zone_config.go#L123)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

"populated"
</blockquote></details>

Done.

**Review by a-robinson — COMMENTED** [review]
> I am very strongly against accomnodating EXPERIMENTAL. This is experimental after all which means "no guarantees". I do not want to create a precedent for us starting to accommodate backward compatibility for experimental syntax -- that's defeating the point of having the experimental bit in the first place.

I understand the desire to not accommodate `EXPERIMENTAL` syntax long term, but it seems incredibly harsh to go directly from requiring the `EXPERIMENTAL` keyword in one version to disallowing it in the next. That makes it impossible to do a rolling upgrade of your cluster without rewriting your clients to handle retrying with/without the keyword, given that during the upgrade some requests could hit old nodes and while others hit new ones. That's a terrible user experience for anyone who's written code that uses the feature.

I thought the general flow would be to only support `EXPERIMENTAL` in version x, then make the `EXPERIMENTAL` keyword optional in version x+1, then remove it in x+2.

**Comment by a-robinson** [comment]
I'm of the same understanding as @benesch - "I see EXPERIMENTAL as a license to change, not a mandate to change."

Intentionally breaking something does less good and causes more pain than just being more explicit about the guarantees in our documentation and recommendations of such features.

**Review by knz — COMMENTED** [review]
I fully agree with the license to change. EXPERIMENTAL is indeed *my* license to change this in the way that I find better for the product. 

I'd also like to point out we're making a storm in a bottle of this: the feature *has* been advertised as experimental to our users, and they know already it can change without prior notice.

It seems that we're having this discussion only because of internal tooling.

Which, as you can see, I am also patching here. And I have volunteered to adapt the remainder of our tooling in the other branches (v2.0, v2.1). 

It's not so clear to me what exactly we (I) am disrupting with this PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28612#-:-LKV9WZs5qGmgIejW9JB:b-qox1fx)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28612)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/cli_test.go, line 528 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28612#-LKNTwGy4S1Z5DA2NNOt:-LLAfJoE4VyWFseLOm4J:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c891d6532e3aeb781d6be9d4256e393d1967a4/pkg/cli/cli_test.go#L528)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

All right I'll revert that; we can discuss formats in a separate CLI PR.
</blockquote></details>

Done.
___
*[pkg/sql/set_zone_config.go, line 166 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28612#-LKNVrUp6KFHpaNfADSd:-LLBMR_VAiy-EKs8BsjD:bovf69e) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1ad8e0e2a34770c787be23afb64a16e9144c7e8/pkg/sql/set_zone_config.go#L166)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

It seems to not be equivalent according to the tests :)

I need to work on this a little more.
</blockquote></details>

Ok I had made a mistake in some unrelated location. This seems fine.

**Comment by knz** [comment]
OK This should be done now. I have written a summary of the changes in the top PR description. 

RFAL

**Review by benesch — COMMENTED** [review]
:lgtm_strong: pending the resolution of the one blocking comment below. This new syntax is really nice!

On the `EXPERIMENTAL` question: my big objection to removing support for the keyword is that I feel like we're doing it spitefully. We're telling our users, "you used this experimental syntax that we didn't find any problems with, but we're going to punish you anyway with a zero-release deprecation cycle just to remind you you're living on the edge." Maybe I don't fully understand your argument for setting precedent, though.

I think I'd actually feel better if we used this opportunity to drop support for the old-style `ALTER ... CONFIGURE ZONE 'yaml'` syntax. That way we're actually making use of the `EXPERIMENTAL` license to remove some crufty and gross syntax—syntax that requires a lot of extra code in setZoneConfig to support! And then we just support the old syntax under the experimental prefix (i.e., `ALTER ... EXPERIMENTAL CONFIGURE ZONE 'yaml'`) in v2.1, and remove the old syntax and the `./cockroach zone` command entirely in v2.2. 

That said, I think squeezing this into v2.1 is top priority so I'm happy to let you proceed as-is.

> Reviewed 29 of 29 files at r5, 17 of 17 files at r6, 40 of 40 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28612#-:-LL_OF9d0h6kAyNbJk-4:bwy3t5h)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cli/zone.go, line 101 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28612#-LL_5E-u34oBW39vK8K6:-LL_5E-u34oBW39vK8K7:b-xnrio3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f53b48821c75c0578ac641199e455c74fa39eb0/pkg/cli/zone.go#L101)):*
> ```Go
> func getCliSpecifierAndZoneConf(
> 	zs *tree.ZoneSpecifier, runQuery runQueryRawFn,
> ) ([][]string, error) {
> ```

nit: `getCLISpecifierAndZoneConf` (Cli vs CLI)
___
*[pkg/cli/zone.go, line 108 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28612#-LL_5Gx84jq2UQ5vb9nL:-LL_5Gx84jq2UQ5vb9nM:b-iipjm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f53b48821c75c0578ac641199e455c74fa39eb0/pkg/cli/zone.go#L108)):*
> ```Go
> }
> 
> func printCliSpecifierAndZoneConf(zs *tree.ZoneSpecifier, vals [][]string) error {
> ```

nit: ditto
___
*[pkg/sql/crdb_internal.go, line 1645 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28612#-LL_L8F54LnKQa7poXKP:-LL_L8F54LnKQa7poXKQ:b-ozqlg8) ([raw file](https://github.com/cockroachdb/cockroach/blob/103d58685f335cca025cf9c596aabd44ad954a46/pkg/sql/crdb_internal.go#L1645)):*
> ```Go
>   cli_specifier    STRING,
>   config_yaml      STRING NOT NULL,
>   config_sql       STRING,
> ```

Can this be null?
___
*[pkg/sql/parser/sql.y, line 1346 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/28612#-LL_MyTbE7t9lvixdjr2:-LL_MyTbE7t9lvixdjr3:b-ed1bv6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95128e1cdf4c5c43aa8d3d269d3c79591e595e4/pkg/sql/parser/sql.y#L1346)):*
> ```Yacc
>   {
>     $$.val = &tree.SetZoneConfig{SetDefault: true}
>   }
> ```

I'm a little bit concerned that `USING DEFAULT` is not a common case and will be confusing to explain. In the tests I used `ALTER ... EXPERIMENTAL CONFIGURE ZONE ''` as a hack to install a zone config that changed no fields from the parent zone config. Would a user ever want to do that? If you're installing a zone config, it's almost always so you can override some field from the parent.

I guess the one case is where you're planning to change some default in, say, a database config, and you want to prevent that default from applying to one or two tables in that database. So you run `ALTER ... CONFIGURE ZONE USING DEFAULT` on those two tables. But the wording here doesn't do a good job of indicating what's going on. And you could just as well run `ALTER ... CONFIGURE ZONE USING param_i_want_to_change = value_i_want_to_keep`.

Put another way: how will we explain to users the difference between `DISCARD` and `USING DEFAULT`?
___
*[pkg/sql/sem/tree/zone.go, line 64 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28612#-LL_4Jm-3enYwTlPqS0p:-LL_4Jm-3enYwTlPqS0q:b-1phiel) ([raw file](https://github.com/cockroachdb/cockroach/blob/17df73423521b2ce2d06dc464c22bef4c1e2f020/pkg/sql/sem/tree/zone.go#L64)):*
> ```Go
> func (node *ZoneSpecifier) String() string { return AsString(node) }
> 
> // ShowZoneConfig represents an EXPERIMENTAL SHOW ZONE CONFIGURATION...
> ```

tiny tiny nit: "represents a", not "represents an"

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28612)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cli/zone.go, line 101 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28612#-LL_5E-u34oBW39vK8K6:-LLfbahwB2wQ1N1DE7Yl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f53b48821c75c0578ac641199e455c74fa39eb0/pkg/cli/zone.go#L101)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

nit: `getCLISpecifierAndZoneConf` (Cli vs CLI)
</blockquote></details>

Done.
___
*[pkg/cli/zone.go, line 108 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28612#-LL_5Gx84jq2UQ5vb9nL:-LLfbe9BDRCunV3DR7ft:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f53b48821c75c0578ac641199e455c74fa39eb0/pkg/cli/zone.go#L108)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

nit: ditto
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 1645 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28612#-LL_L8F54LnKQa7poXKP:-LLfcBpz1kR2uo_ekYPV:b-rptp7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/103d58685f335cca025cf9c596aabd44ad954a46/pkg/sql/crdb_internal.go#L1645)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Can this be null?
</blockquote></details>

Yes; added a comment.
___
*[pkg/sql/parser/sql.y, line 1346 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/28612#-LL_MyTbE7t9lvixdjr2:-LLfcwD9CL9wrrcV8LGE:b-jatksl) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95128e1cdf4c5c43aa8d3d269d3c79591e595e4/pkg/sql/parser/sql.y#L1346)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I'm a little bit concerned that `USING DEFAULT` is not a common case and will be confusing to explain. In the tests I used `ALTER ... EXPERIMENTAL CONFIGURE ZONE ''` as a hack to install a zone config that changed no fields from the parent zone config. Would a user ever want to do that? If you're installing a zone config, it's almost always so you can override some field from the parent.

I guess the one case is where you're planning to change some default in, say, a database config, and you want to prevent that default from applying to one or two tables in that database. So you run `ALTER ... CONFIGURE ZONE USING DEFAULT` on those two tables. But the wording here doesn't do a good job of indicating what's going on. And you could just as well run `ALTER ... CONFIGURE ZONE USING param_i_want_to_change = value_i_want_to_keep`.

Put another way: how will we explain to users the difference between `DISCARD` and `USING DEFAULT`?
</blockquote></details>

You're right; it's hard to explain and also unjustifiable for users until we do cascading zone configs.

I'm hiding them away from docs.
___
*[pkg/sql/sem/tree/zone.go, line 64 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28612#-LL_4Jm-3enYwTlPqS0p:-LLfe6ZxDULmDnEBTCgK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/17df73423521b2ce2d06dc464c22bef4c1e2f020/pkg/sql/sem/tree/zone.go#L64)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

tiny tiny nit: "represents a", not "represents an"
</blockquote></details>

Done.

**Comment by knz** [comment]
rebased; rfal

**Review by benesch — APPROVED** [review]
> Reviewed 53 of 53 files at r9, 17 of 17 files at r10, 41 of 41 files at r11, 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28612)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by knz** [comment]
thanks

bors r+

**Pull request merged**
