### PR TITLE
sql: drop index using ClearRange

### LINKED ISSUE #20696: sql: use ClearRange for index deletion
As of #20601 we are using `ClearRange` to efficiently wipe table data after `DROP`. We should be making use of a similar mechanism for deleting indexes wholesale.

One complication is that all index operations are serialized through the surrounding table descriptor, so that the naive approach of waiting for the TTL is not great (as it holds up unrelated schema changes).

@vivekmenezes [suggested](https://github.com/cockroachdb/cockroach/pull/20601#issuecomment-350927820) dropping the index immediately, the reasoning being that the data is derived from the primary index anyway (and thus a fat-finger just means having to rebuild the index).

On the other hand, it violates time travel queries which would still try to use the index and would fail (i.e. dropping an index will only make regular queries more inefficient, but will completely screw up any time travel queries that try to use it). This may be enough reason to discuss whether the schema changer can "lookahead" and make use of the commutativity of the index drop with other unrelated operations.

### PR DESCRIPTION
**Pull request by vivekmenezes**
This change runs the DROP INDEX state machine through all its
steps without running through the bulk incremental delete of
all the index data at the end. The DROP INDEX mutation instead
is moved to a GCMutations list which is processed offline. Once
the GC deadline for the data has expired the offline processor
calls ClearRange() on the data that runs through a fast bulk
deletion of the data. If the GC TTL is set to 0 in the zone config,
the data is delete immediately.

fixes #20696

Release note: Speedup DROP INDEX through bulk deletion of index data

### CODE REVIEW

**Comment by vivekmenezes** [comment]
Looks like one of the tests is failing. I'm taking a look at it.

**Comment by dt** [comment]
Huh, I just looked and realized this matches how drop table gcdeadline works, but I'm a little surprised: we eagerly evaluate the deadline? What if the TTL is changed before that time? 

---

Review status: 0 of 14 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[test, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22752#-L5QET6LiatAJv1ox1Qm:-L5QET6LiatAJv1ox1Qn:bd7wmwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b40ebce10677f9c2c542e00d4ff6d944a242e6/test#L1)):*
> ```
> (0,1)  starting plan  querying next range at /Table/2/1/0/"t"/3/1
> ```

What's this file?

---

*[pkg/sql/alter_table.go, line 130 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22752#-L5QFUQRwISaZZzY805d:-L5QFUQRwISaZZzY805e:b-pljzoc) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b40ebce10677f9c2c542e00d4ff6d944a242e6/pkg/sql/alter_table.go#L130)):*
> ```Go
> 			if idx != nil {
> 				if err := n.tableDesc.AddIndexMutation(
> 					*idx, sqlbase.DescriptorMutation_ADD, 0,
> ```

here, and elsewhere, i'd suggest using a named const `NoGCDeadline` or something for readability.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22752#-:-L5QGvkKOPvU3CNrVV7s:bwtqrm6)*

**Comment by vivekmenezes** [comment]
David,

I'm gonna change the protobuf to store the time of.drop so at least we have
a better place to fix the dynamic zonecfg issue from. I'll do it for the
drop table case as well

**Comment by dt** [comment]
@eriktrinh implemented this, right?

**Comment by vivekmenezes** [comment]
@dt yes! closing this PR

**Pull request closed without merging**
