### PR TITLE
server: Add qps/wps stats to range debug info

### LINKED ISSUE #14038: server: Include info about request counts to each range on debug page(s)
We now have info in the `replicaStats` member of each Replica about how many requests the replica has processed (and from which localities). This info would be useful to put in the new range debug page, if not elsewhere as well.

It would have helped debug the load generation problem in #13627, as one example.

@BramGruneir @a-robinson

### PR DESCRIPTION
**Pull request by a-robinson**
The range debug page now looks like this:

screen shot 2017-07-19 at 5 13 37 pm

Fixes #14038

### CODE REVIEW

**Comment by a-robinson** [comment]
Switched from "Leaseholder Queries Per Second" to "Leaseholder QPS" to fit smaller screens better.

**Comment by BramGruneir** [comment]
LGTM

Any idea why the key range is highlighted as wrong?  It looks the same to me.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17124#-:-KpVTdLRY3SgzapCwftt:bvhdk6j)*

**Comment by a-robinson** [comment]
No, I don't have any idea. It certainly looks the same to me.

**Comment by BramGruneir** [comment]
Hmm..  Maybe an off by a space or something.  Don't matter, I'm going to be moving that page to the admin ui next week and re-writing most of it.

**Pull request merged**
