### PR TITLE
workload/schemachange: add enum support

### PR DESCRIPTION
**Pull request by ajwerner**
This commit adds support for creating enums, adding enum columns, and using
enums to insert data into rows. This found a bug so I'm pleased.

Release note: None

### CODE REVIEW

**Review by otan — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54351)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @otan)

___
*[pkg/workload/schemachange/schemachange.go, line 1104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54351#-MHCTtCm4Xo8JP9hEfjf:-MHCTtCm4Xo8JP9hEfjg:b-xngto9) ([raw file](https://github.com/cockroachdb/cockroach/blob/904adaaedf7ceee783362a8792392fc739cb36fe/pkg/workload/schemachange/schemachange.go#L1104)):*
> ```Go
>          AND typcategory = 'E'
>          AND typname = $1
> ORDER BY gen_random_uuid();`, name.Object())
> ```

should we sort by enum order here, and make`rng` would be in charge of picking a randomly assigned element (for reproducible runs)?
(also, not sure I follow why we are sorting by random)

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54351)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/workload/schemachange/schemachange.go, line 1104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54351#-MHCTtCm4Xo8JP9hEfjf:-MHCUrpc5m5FIe_0VdH3:b6e77gz) ([raw file](https://github.com/cockroachdb/cockroach/blob/904adaaedf7ceee783362a8792392fc739cb36fe/pkg/workload/schemachange/schemachange.go#L1104)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

should we sort by enum order here, and make`rng` would be in charge of picking a randomly assigned element (for reproducible runs)?
(also, not sure I follow why we are sorting by random)
</blockquote></details>

No good reason. Done.

**Review by otan — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54351)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

**Comment by ajwerner** [comment]
TFTR!

bors r=otan

**Pull request merged**
