### PR TITLE
release-21.1: sql: add txn rows written/read guardrails

### PR DESCRIPTION
**Pull request by yuzefovich**
Backport:
  * 2/2 commits from "sql: add txn rows written/read guardrails" (#69202)
  * 2/2 commits from "sql: adjust recently added logging events for txn row count guardrails" (#69945)
  * 1/1 commits from "execbuilder: restore auto commit for internal queries" (#70174)
  * 1/1 commits from "sql: allow auto commit when rows written limit is reached, not exceeded" (#70196)

Please see individual PRs for details.

/cc @cockroachdb/release

### CODE REVIEW

**Comment by yuzefovich** [comment]
Note that the fifth commit is from the not yet merged PR #70174 which I found when creating this PR.

**Comment by yuzefovich** [comment]
There were quite a few merge conflicts (which actually prompted me to find #70176), and I had to tweak `TestPerfLogging` a bit, but otherwise I didn't make any changes since these guardrails are off by default anyway.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 38 of 38 files at r2, 8 of 8 files at r3, 8 of 8 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70175#-:-MjZNJAO6Bqq4xnCuq8P:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2)

**Comment by yuzefovich** [comment]
@rytaft could you please take a look at the last commit that I just added from #70196?

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70175#-:-Mj_DCUi42zodK1zit7J:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2)

**Pull request merged**
