### PR TITLE
issues: use per-branch labels for issues

### PR DESCRIPTION
**Pull request by tbg**
This is part of the work outlined in #43920 to improve the release process.

Prior to this commit, the logic for deciding between posting into an
existing issue vs opening a new one was based on a fairly permissive search
on the test name.

In #43920, it is suggested to prevent "mixing" of issues/comments relating
to failures on different release branches (i.e. master and release-X). This
necessitated a rework of the issue search. An issue is now re-used only if

- the title matches (as a Github search query, i.e. it's not an exact
 match but that's the best we can do given the existing API), and
- the C-test-failure label and the C-branch-<X> label are present and
 match.

To facilitate cross-referencing of failures across branches, the test
failure templates are given access to a list of "related issues", that is,
issues that fail only the condition on the branch label above.

Note that "extra labels" provided to `Post` are ignored for the purpose of
searching, but they are used in the event of the creation of a new issue.
This behavior makes sense in most cases, for example we would like a
human-created issue about a test failure to be picked up by the issue
poster even if the O-robot label were missing. Similarly, we want to
continue using an issue even if an initially supplied
`release-blocker` label is removed.

Note that while #43920 makes suggestions only for roachtest issues, this
commit generalizes the approach to unit test failures as well. Thanks to
the labeling introduced in this PR, cross-referencing is largely automatic
already, and we can use the reminders to backport our fixes to the release
branches.

Closes #44011.

Release note: None

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
:lgtm: 

I salute this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44155#-:-Lz7pYKS1rXQGPfAFO0p:bh4yhjy)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @dt, and @tbg)

___
*[pkg/cmd/internal/issues/issues_test.go, line 256 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44155#-Lz7onJfDq7iQ3bnHRlW:-Lz7onJfDq7iQ3bnHRlX:b1z1kgo) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd093d5ef60047aae5b7e9fecc8246e15b49a8a5/pkg/cmd/internal/issues/issues_test.go#L256)):*
> ```Go
> }
> 
> func setEnv(kv map[string]string) func() {
> ```

nit: give the return value a name (`cleanup`) or put a comment

**Comment by dt** [comment]
Wow, thank you sir!

I'm extremely excited about this and happy to LGTM it based on the prose description. I don't know the code super well so I'll mostly defer to @andreimatei there (or, if you wanted a proper second reviewer, I might recommend cc'ing dev-inf?).

**Review by tbg — COMMENTED** [review]
TFTR! @dt I was looking mostly for validation on the prose for you. But I should've looped in @bobvawter regardless (there isn't a team I can CC, is there?)

bors r=andreimatei,dt

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44155#-:-LzC-dIx7g6en3_hxLqm:b3epmr9)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dt)

**Comment by tbg** [comment]
I went through the test failures we have open right now and slapped
`branch-master` labels on them. This should make sure we're not getting any
dupes, but going forward release branch issues should end up on the release
branch.

**Pull request merged**
