### PR TITLE
roachpb,kv: new TxnCoordSender API for step-wise execution

### PR DESCRIPTION
**Pull request by knz**
Supports #42864.

This patch introduces the following methods on `client.TxnSender`:

```go
	// Step creates a sequencing point in the current transaction. A
	// sequencing point establishes a snapshot baseline for subsequent
	// read operations: until the next sequencing point, read operations
	// observe the data at the time the snapshot was established and
	// ignore writes performed since.
	//
	// Before the first step is taken, the transaction operates as if
	// there was a step after every write: each read to a key is able to
	// see the latest write before it. This makes the step behavior
	// opt-in and backward-compatible with existing code which does not
	// need it.
	// The method is idempotent.
	Step() error

	// DisableStepping disables the sequencing point behavior and
	// ensures that every read can read the latest write. The
	// effect remains disabled until the next call to Step().
	// The method is idempotent.
	DisableStepping() error
```

Additionally it implements it in the `TxnCoordSender`.

`Step()` is the most important and will be used to introduce sequence
points between SQL statements.

`DisableStepping()` is a convenience function, so as to avoid
introducing many `Step()` calls in the code that performs schema
changes.

Release note: none

### CODE REVIEW

**Comment by knz** [comment]
@nvanbenschoten I think I will need your help on this one. I have tried two different approaches and each of them breaks for an "interesting" reason.

1) use the special value `readSeq == 0` to disable step-wise execution. (this is the current choice of the PR).

   The first valid read seq is then 1. To hold the invariant `readSeq <= seqGen`, this forces to assign `seqGen := 1` if there were no writes yet in the txn.

   Pros: just 1 extra field in the seqno allocator and TxnCoordMeta.

   Cons: **this breaks the 1PC optimization**, as demonstrated by `TestUpsertFastPath`.

2) use a separate boolean to enable step-wise execution, and make `readSeq == 0` a valid read seqnum.

   Pros: code perhaps easier to read.

   Cons: 

   - the **MVCC read-at-fixed-seqnum logic does not activate if the seqnum of a read operation is 0.** So the logic breaks for a SQL mutation that executes first thing in a txn.
   - 2 extra fields in seqno allocator + TxnCoordMeta.

I think I really want to take approach (1) but I don't understand how/where to preserve the 1PC optimization.

**Review by andreimatei — COMMENTED** [review]
Can you spell out why 1PC batches need sequence number 0? Is there a good reason?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-:-Lv6xw1J9iRz74KtoMjZ:banr432)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by knz** [comment]
> Can you spell out why 1PC batches need sequence number 0? Is there a good reason?

No — I can't spell it out because I don't understand the optimization completely and I did not design it.

However my working theory is that the thing checks that there was just 1 batch by verifying that the operation that sets the sequence number (e.g. 1) is also present in the batch — with the logic proposed here, it won't find it.

However I don't know where this code lives. I really hope you or Nathan can help.

**Comment by andreimatei** [comment]
Oh I see. Check this out:
https://github.com/cockroachdb/cockroach/blob/6e1d241720245a97a1b859622282c98e131ca642/pkg/roachpb/batch.go#L256-L255

Would making it expect 2 instead of 1 fix your problem?

**Comment by knz** [comment]
> Would making it expect 2 instead of 1 fix your problem?

Maybe. My problem is that my code _currently_ lets `seqGen` start at 0 _by default_ and so it only starts at 1 when step-wise execution is requested.

But I could change the default to become 1. 

The problem I see with that is cross-version clusters. If I change the code you point me to, then during an upgrade the optimization will be disabled for all requests coming from pre-upgrade nodes. Is that acceptable?

**Comment by knz** [comment]
I have updated the PR after chatting with Nathan and Andrei:

- the logic is modified to adopt alternative 2 described above, so that the value 0 remains a valid sequence number. The seqnum interceptor now uses a separate internal field to make this happen.

- I have fixed the storage bug which did not respect the seqnum for read operations when it was initialized to 0, as discussed offline.

**Comment by knz** [comment]
Ok this and #42862 now do the job properly. RFAL

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42854)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @nvanbenschoten)

___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LvMfy-A3KEKViQyERoG:-LvMfy-B0d-5YWEXxFKc:bdkwb8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03d50b6a91761b42c8fe6b288e02385f4747d80/pkg/kv/txn_interceptor_seq_num_allocator.go#L67)):*
> ```Go
> 	writeSeq enginepb.TxnSeq
> 
> 	// readSeqPlusOne is either:
> ```

This plus one business is a bit confusing. I'd try grouping `writeSeq` and `readSeq` into a separate `seqCounter` struct, with a `IncWriteSeq()`, `LockReadSeq()`, `GetReadSeq()` methods, have a bool for whether the stepping is enabled, and have `GetReadSeq()` return `writeSeq` or `readSeq` depending on the bool.
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LvMC9xiB6t_deXw7FCO:-LvMC9xiB6t_deXw7FCP:blr94e) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03d50b6a91761b42c8fe6b288e02385f4747d80/pkg/kv/txn_interceptor_seq_num_allocator.go#L104)):*
> ```Go
> 			// enabled, then we want the read operation to read at the read
> 			// seqnum, not the latest write seqnum.
> 			oldHeader.Sequence = s.readSeqPlusOne - 1
> ```

Let's make put a note here about read+write requests operating at writeSeq because they're special, to make it clear that it's intentional.
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LvMCWidCRVdCBe6Bjpq:-LvMCWidCRVdCBe6Bjpr:b-dcrvil) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03d50b6a91761b42c8fe6b288e02385f4747d80/pkg/kv/txn_interceptor_seq_num_allocator.go#L139)):*
> ```Go
> func (s *txnSeqNumAllocator) stepLocked() error {
> 	if s.readSeqPlusOne-1 > s.writeSeq {
> 		return errors.AssertionFailedf("cannot step() after mistaken initialization (%d,%d)", s.writeSeq, s.readSeqPlusOne)
> ```

long line
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LvMCi5B77COxFW2RQJ7:-LvMCi5B77COxFW2RQJ8:bngrpjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03d50b6a91761b42c8fe6b288e02385f4747d80/pkg/kv/txn_interceptor_seq_num_allocator.go#L139)):*
> ```Go
> func (s *txnSeqNumAllocator) stepLocked() error {
> 	if s.readSeqPlusOne-1 > s.writeSeq {
> 		return errors.AssertionFailedf("cannot step() after mistaken initialization (%d,%d)", s.writeSeq, s.readSeqPlusOne)
> ```

nit: I'd just say "invalid read seq" or such
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LvMfKz44aeNSDgnLrzY:-LvMfKz44aeNSDgnLrzZ:btfcldq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03d50b6a91761b42c8fe6b288e02385f4747d80/pkg/kv/txn_interceptor_seq_num_allocator.go#L148)):*
> ```Go
> // restores read-latest-write behavior.
> // Used by the TxnCoordSender's DisableStepping() method.
> func (s *txnSeqNumAllocator) disableSteppingLocked() error {
> ```

get rid of the error return
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LvMgKb685kYo1W0cwzs:-LvMgKb685kYo1W0cwzt:bv1h3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03d50b6a91761b42c8fe6b288e02385f4747d80/pkg/kv/txn_interceptor_seq_num_allocator.go#L157)):*
> ```Go
> 	s.commandCount = 0
> 	s.writeSeq = 0
> 	if s.readSeqPlusOne > 0 {
> ```

Wouldn't a more natural behavior be for `epochBumpedLocked()` to imply `disableSteppingLocked()`? Like, let's start every epoch with stepping disabled in the spirit of forgetting everything that was done on the transaction before the restart.
As it stands, the behavior is inconsistent with what happens to a txn after a `TransactionAbortedError` where I don't see code to enable stepping on the new txn.
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LvMgSZk95dS9QjyhTVS:-LvMgSZk95dS9QjyhTVT:b-ghq80w) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03d50b6a91761b42c8fe6b288e02385f4747d80/pkg/kv/txn_interceptor_seq_num_allocator.go#L159)):*
> ```Go
> 	if s.readSeqPlusOne > 0 {
> 		s.readSeqPlusOne = 1
> 	} else {
> ```

I think the else is unnecessary.
___
*[pkg/roachpb/data.proto, line 636 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LvMhLSoBVUG0zKlUFZ7:-LvMhLSoBVUG0zKlUFZ8:b-xs1gtr) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03d50b6a91761b42c8fe6b288e02385f4747d80/pkg/roachpb/data.proto#L636)):*
> ```protobuf
>   // Current read seqnum, plus 1. The special value of zero indicates synchronous
>   // read-own-writes, where every KV read is able to observe the latest writes.
>   // As soon as the value is increased past 0, (value - 1) becomes the sequence number
> ```

nit: bad wrapping

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42854)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @nvanbenschoten)

___
*[pkg/storage/replica_evaluate.go, line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LvMi211-ZARdAeaiF7s:-LvMi211-ZARdAeaiF7t:b-j79ce0) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03d50b6a91761b42c8fe6b288e02385f4747d80/pkg/storage/replica_evaluate.go#L246)):*
> ```Go
> 		args := union.GetInner()
> 		if baHeader.Txn != nil {
> 			// Set the Request's sequence number on the TxnMeta for this
> ```

`TxnMeta` will no longer be accurate here, right?

**Review by nvb — COMMENTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42854)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @knz)

___
*[pkg/internal/client/sender.go, line 210 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LvCeW-P32aNc_UGP3cM:-LvCeW-P32aNc_UGP3cN:b-ol6uii) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03d50b6a91761b42c8fe6b288e02385f4747d80/pkg/internal/client/sender.go#L210)):*
> ```Go
> 	SerializeTxn() *roachpb.Transaction
> 
> 	// Step creates a sequencing point in the current transaction. A
> ```

Could you replace "read operations" with "read-only operations" throughout these descriptions?
___
*[pkg/internal/client/sender.go, line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LvCelN72w6GUOoXuj3k:-LvCelN72w6GUOoXuj3l:b-a76ksu) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03d50b6a91761b42c8fe6b288e02385f4747d80/pkg/internal/client/sender.go#L228)):*
> ```Go
> 	// effect remains disabled until the next call to Step().
> 	// The method is idempotent.
> 	DisableStepping() error
> ```

Make it clear somewhere that transactions start with stepping disabled.
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LvMfy-A3KEKViQyERoG:-LvMlQDFAOn1KtyPEvpI:bcd52zp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03d50b6a91761b42c8fe6b288e02385f4747d80/pkg/kv/txn_interceptor_seq_num_allocator.go#L67)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

This plus one business is a bit confusing. I'd try grouping `writeSeq` and `readSeq` into a separate `seqCounter` struct, with a `IncWriteSeq()`, `LockReadSeq()`, `GetReadSeq()` methods, have a bool for whether the stepping is enabled, and have `GetReadSeq()` return `writeSeq` or `readSeq` depending on the bool.
</blockquote></details>

Yeah, I like this idea. The "plus one" business seems to spread across a lot of places.
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LvMl_24-p2Wjwnl2gC_:-LvMl_24-p2Wjwnl2gCa:bfusgka) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03d50b6a91761b42c8fe6b288e02385f4747d80/pkg/kv/txn_interceptor_seq_num_allocator.go#L100)):*
> ```Go
> 		// Default case: operate at the current seqnum.
> 		oldHeader.Sequence = s.writeSeq
> 		if s.readSeqPlusOne > 0 && roachpb.IsReadOnly(req) {
> ```

How do you feel about restructuring this to something like:
```go
var seq enginepb.TxnSeq
if roachpb.IsTransactionWrite(req) || req.Method() == roachpb.EndTransaction {
	s.writeSeq++
	seq = s.writeSeq
} else /* if roachpb.IsReadOnly(req) */ {
	if s.readSeqPlusOne > 0 {
		seq = s.readSeqPlusOne - 1
	} else {
		seq = s.writeSeq
	}
}
```

**Comment by knz** [comment]
Guys if you want me to do something else than `readSeqPlusOne` then I _need_ you to tell me what I should put in the `TxnCoordMeta` and the logic you recommend for the `Update` function. Thank you in advance.

**Comment by knz** [comment]
discussed with Andrei: the proposed structure works because we only care about Root->Leaf conversion

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42854)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/internal/client/sender.go, line 210 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LvCeW-P32aNc_UGP3cM:-LvSBIHq9m_XNWHOqMYT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03d50b6a91761b42c8fe6b288e02385f4747d80/pkg/internal/client/sender.go#L210)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could you replace "read operations" with "read-only operations" throughout these descriptions?
</blockquote></details>

Done.
___
*[pkg/internal/client/sender.go, line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LvCelN72w6GUOoXuj3k:-LvSBD_a7Zu7g_5XYv00:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03d50b6a91761b42c8fe6b288e02385f4747d80/pkg/internal/client/sender.go#L228)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Make it clear somewhere that transactions start with stepping disabled.
</blockquote></details>

Done.
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LvMfy-A3KEKViQyERoG:-LvSFF2Q3yCj4E27zdvB:b-f3d62l) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03d50b6a91761b42c8fe6b288e02385f4747d80/pkg/kv/txn_interceptor_seq_num_allocator.go#L67)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah, I like this idea. The "plus one" business seems to spread across a lot of places.
</blockquote></details>

I simplified this. PTAL.
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LvMl_24-p2Wjwnl2gC_:-LvSC87Y4g1prob-xeLE:blwfafb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03d50b6a91761b42c8fe6b288e02385f4747d80/pkg/kv/txn_interceptor_seq_num_allocator.go#L100)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

How do you feel about restructuring this to something like:
```go
var seq enginepb.TxnSeq
if roachpb.IsTransactionWrite(req) || req.Method() == roachpb.EndTransaction {
	s.writeSeq++
	seq = s.writeSeq
} else /* if roachpb.IsReadOnly(req) */ {
	if s.readSeqPlusOne > 0 {
		seq = s.readSeqPlusOne - 1
	} else {
		seq = s.writeSeq
	}
}
```
</blockquote></details>

I can't do this: The complement of `IsTransactionWrite` is not `IsReadOnly`.
Anyway with the new field usage, the code is slightly easier on the eye.
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LvMC9xiB6t_deXw7FCO:-LvSCMeVEWhz6IYd_sod:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03d50b6a91761b42c8fe6b288e02385f4747d80/pkg/kv/txn_interceptor_seq_num_allocator.go#L104)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Let's make put a note here about read+write requests operating at writeSeq because they're special, to make it clear that it's intentional.
</blockquote></details>

Done.
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LvMCWidCRVdCBe6Bjpq:-LvSCPAl4xW_nNYuTwfs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03d50b6a91761b42c8fe6b288e02385f4747d80/pkg/kv/txn_interceptor_seq_num_allocator.go#L139)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

long line
</blockquote></details>

Done.
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LvMfKz44aeNSDgnLrzY:-LvSCRe281mXEjSY3GAh:bs9od3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03d50b6a91761b42c8fe6b288e02385f4747d80/pkg/kv/txn_interceptor_seq_num_allocator.go#L148)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

get rid of the error return
</blockquote></details>

I'd rather not. I want to add an assert in here when #43032 lands.
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LvMgKb685kYo1W0cwzs:-LvSCd_217D9VScqlLf8:bourfqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03d50b6a91761b42c8fe6b288e02385f4747d80/pkg/kv/txn_interceptor_seq_num_allocator.go#L157)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Wouldn't a more natural behavior be for `epochBumpedLocked()` to imply `disableSteppingLocked()`? Like, let's start every epoch with stepping disabled in the spirit of forgetting everything that was done on the transaction before the restart.
As it stands, the behavior is inconsistent with what happens to a txn after a `TransactionAbortedError` where I don't see code to enable stepping on the new txn.
</blockquote></details>

Thanks for explaining. Done.
___
*[pkg/roachpb/data.proto, line 636 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LvMhLSoBVUG0zKlUFZ7:-LvSCuLV7dArJGbwFgxY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03d50b6a91761b42c8fe6b288e02385f4747d80/pkg/roachpb/data.proto#L636)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: bad wrapping
</blockquote></details>

Done.
___
*[pkg/storage/replica_evaluate.go, line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LvMi211-ZARdAeaiF7s:-LvSD-L78a0oyXJLRJsh:b-lbut5x) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03d50b6a91761b42c8fe6b288e02385f4747d80/pkg/storage/replica_evaluate.go#L246)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

`TxnMeta` will no longer be accurate here, right?
</blockquote></details>

What do you mean?

**Comment by knz** [comment]
Rebased this on top of now-ready #43032. RFAL.

@andreimatei check that the API definition works for you (and complies to RFC)

@nvanbenschoten (optionally) check that the sequence number allocation is correct. I think you've checked that before and I haven't changed the logic since your last review.

**Comment by knz** [comment]
Friendly ping.

**Review by andreimatei — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-:-Lxv_78VBYNW0h4LSgwL:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @knz, and @nvanbenschoten)

___
*[pkg/internal/client/sender.go, line 228 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LxvX2Bj9Qbhgs-gIchT:-LxvX2Bj9Qbhgs-gIchU:b-w2xe2d) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb8f4e59544ff9beb110505897530217d5e4653d/pkg/internal/client/sender.go#L228)):*
> ```Go
> 	// Step creates a sequencing point in the current transaction. A
> 	// sequencing point establishes a snapshot baseline for subsequent
> 	// read-only operations: until the next sequencing point, read-only operations
> ```

pretty please wrap the lines
___
*[pkg/internal/client/sender.go, line 244 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LxvWPYu-iCFKuo09FwW:-LxvWPYu-iCFKuo09FwX:bgwv3o3) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb8f4e59544ff9beb110505897530217d5e4653d/pkg/internal/client/sender.go#L244)):*
> ```Go
> 	// effect remains disabled until the next call to Step().
> 	// The method is idempotent.
> 	// Note that a TxnCoordSender is initially in the non-
> ```

I don't think we should mention the TCS in this comment. All implementors of this interface must be in "non-stepping mode" initially.
___
*[pkg/kv/txn_coord_sender.go, line 337 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LxvY1KD33LUCilr-zVv:-LxvY1KD33LUCilr-zVw:b-51440) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb8f4e59544ff9beb110505897530217d5e4653d/pkg/kv/txn_coord_sender.go#L337)):*
> ```Go
> 	// Load the in-flight writes in the pipeliner.
> 	tcs.interceptorAlloc.txnPipeliner.initializeLeaf(tis)
> 	// Load the read seqnum into the seq num allocator.
> ```

nit: I think this comment and the one above are bound to go stale. They also duplicate the comments on the respective methods.
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LvMfKz44aeNSDgnLrzY:-LxvWn5SBl0x6XyqoBDE:bn8dhn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03d50b6a91761b42c8fe6b288e02385f4747d80/pkg/kv/txn_interceptor_seq_num_allocator.go#L148)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I'd rather not. I want to add an assert in here when #43032 lands.
</blockquote></details>

#43032 and I see no assertion...
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 62 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LxvYal48uYUnwt2-seu:-LxvYal48uYUnwt2-sev:bfsbfzf) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb8f4e59544ff9beb110505897530217d5e4653d/pkg/kv/txn_interceptor_seq_num_allocator.go#L62)):*
> ```Go
> 	wrapped lockedSender
> 
> 	// writeSeq is the current write seqnum, or the value last assigned
> ```

nit: the "or" is ambiguous, it'd replace it with a "(...)" to make it clear that what follows is an explanation.
___
*[pkg/roachpb/data.proto, line 623 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LxvZuc5-FzbPpegpuU1:-LxvZuc5-FzbPpegpuU2:bvjiad6) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb8f4e59544ff9beb110505897530217d5e4653d/pkg/roachpb/data.proto#L623)):*
> ```protobuf
>   // regardless of the current seqnum generated for writes. This is
>   // updated via the (client.TxnSender).Step() operation.
>   int32 read_seq_num_plus_one = 9 [
> ```

you don't want to add the bool here too instead of the plus one business?
___
*[pkg/storage/replica_evaluate.go, line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LvMi211-ZARdAeaiF7s:-LxvZiH8EOVAZyIdRPdi:b-xdwn8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03d50b6a91761b42c8fe6b288e02385f4747d80/pkg/storage/replica_evaluate.go#L246)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

What do you mean?
</blockquote></details>

I don't know what I meant :). nvm.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42854)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @knz, and @nvanbenschoten)

___
*[pkg/internal/client/sender.go, line 228 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LxvX2Bj9Qbhgs-gIchT:-Lxvh0_xB6S_zNopihIS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb8f4e59544ff9beb110505897530217d5e4653d/pkg/internal/client/sender.go#L228)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pretty please wrap the lines
</blockquote></details>

Done.
___
*[pkg/internal/client/sender.go, line 244 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LxvWPYu-iCFKuo09FwW:-Lxvh1HY2BSG2GAR6TGZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb8f4e59544ff9beb110505897530217d5e4653d/pkg/internal/client/sender.go#L244)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't think we should mention the TCS in this comment. All implementors of this interface must be in "non-stepping mode" initially.
</blockquote></details>

Done.
___
*[pkg/kv/txn_coord_sender.go, line 337 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LxvY1KD33LUCilr-zVv:-LxvhUWxCgHhXdOvQNgV:bquqo7e) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb8f4e59544ff9beb110505897530217d5e4653d/pkg/kv/txn_coord_sender.go#L337)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: I think this comment and the one above are bound to go stale. They also duplicate the comments on the respective methods.
</blockquote></details>

Thanks. Changed the comment to hint about what to do in the future.
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LvMfKz44aeNSDgnLrzY:-LxvigGVAjsrzLSmOpFX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03d50b6a91761b42c8fe6b288e02385f4747d80/pkg/kv/txn_interceptor_seq_num_allocator.go#L148)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

#43032 and I see no assertion...
</blockquote></details>

Done.
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 62 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LxvYal48uYUnwt2-seu:-LxvhbRC2YstWeBvPKuy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb8f4e59544ff9beb110505897530217d5e4653d/pkg/kv/txn_interceptor_seq_num_allocator.go#L62)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: the "or" is ambiguous, it'd replace it with a "(...)" to make it clear that what follows is an explanation.
</blockquote></details>

Done.
___
*[pkg/roachpb/data.proto, line 623 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LxvZuc5-FzbPpegpuU1:-LxvihhX8WrVxpR72Cs7:b-su7fkp) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb8f4e59544ff9beb110505897530217d5e4653d/pkg/roachpb/data.proto#L623)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

you don't want to add the bool here too instead of the plus one business?
</blockquote></details>

I don't have strong feelings for either. What is best?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42854)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/roachpb/data.proto, line 623 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42854#-LxvZuc5-FzbPpegpuU1:-Lxw9rV858FPwaMTmewr:bdn61vi) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb8f4e59544ff9beb110505897530217d5e4653d/pkg/roachpb/data.proto#L623)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I don't have strong feelings for either. What is best?
</blockquote></details>

Separated the fields as per previous suggestion.

**Comment by knz** [comment]
TFYRs!

bors r+

**Pull request merged**
