### PR TITLE
opt: disable `GenerateParameterizedJoin` when forcing custom plans

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: remove documentation of old flags

In #85935 we introduced the `set` flag to set session settings in
optimizer tests and a few flags that were already controlling session
settings were removed. The documentation of those old flags has been
removed.

Release note: None

#### opt: disable `GenerateParameterizedJoin` when forcing custom plans

The exploration rule `GenerateParameterizedJoin` is now disabled when
the `plan_cache_mode` session setting is set to `force_custom_plan`.
This prevents possible regressions in plans for this mode in the rare
case that a stable function is not folded during normalization (due to
an error encountered during folding). In most cases, the check for
placeholders and stable functions in `GenerateParameterizedJoin` is
sufficient for preventing the rule from firing when a generic query plan
is not being built—before optimizing a custom plan placeholders are
always replaced with constants and stable functions are usually folded
to constants.

Epic: None

Release note: None

#### sql: fix minor typo in plan_opt.go

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
Only the second commit needs to be backported.

**Review by michae2 — APPROVED** [review]
> This prevents possible regressions in plans for this mode in the rare  
> case that a stable function is not folded during normalization (due to  
> an error encountered during folding). In most cases, the check for  
> placeholders and stable functions in `GenerateParameterizedJoin` is  
> sufficient for preventing the rule from firing when a generic query plan  
> is not being built—before optimizing a custom plan placeholders are  
> always replaced with constants and stable functions are usually folded  
> to constants.

Thanks for this description!

When optimizing a custom plan, if a stable function is not folded during normalization, is it possible that we would actually want this rule to fire? Could it turn a FTS with a filter involving an unfolded stable function into a lookup join? (I'm not sure what an example would be... maybe a call to a stable UDF?)

Anyway, this :lgtm: if we want to disable the rule.

> Reviewed 1 of 1 files at r1, 8 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129050#-:-O4LzIp0B3sz0VkZ3_6Z:b-pvi13z)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @rytaft)

___
*[`pkg/sql/opt/testutils/opttester/opt_tester.go` line 485 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129050#-O4M2V_x8Jt2_i56oZ6T:-O4M2V_x8Jt2_i56oZ6U:b-pddi6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0693acdd5fc2fae79a6679301ae2a29f9526519/pkg/sql/opt/testutils/opttester/opt_tester.go#L485)):*
> ```Go
> //
> //   - generic: enables optimizations for generic query plans.
> //     NOTE: This flag sets the plan_cache_mode session setting to "auto", which
> ```

Just curious: any particular reason for auto instead of force_generic_plan?

**Comment by mgartner** [comment]
> When optimizing a custom plan, if a stable function is not folded during normalization, is it possible that we would actually want this rule to fire? Could it turn a FTS with a filter involving an unfolded stable function into a lookup join? (I'm not sure what an example would be... maybe a call to a stable UDF?)

Yes great point. I thought of that a bit, and I do think we would want it to fire. It could unlock optimizations that are otherwise impossible. But we do not want it to fire in the backported version of generic query plans, to reduce risk. So we'll stick with this for now, and maybe remove it soon.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129050)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @michae2, and @rytaft)

___
*[`pkg/sql/opt/testutils/opttester/opt_tester.go` line 485 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129050#-O4M2V_x8Jt2_i56oZ6T:-O4MasQ7AgxDBkuFiVs4:b-tm6foh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0693acdd5fc2fae79a6679301ae2a29f9526519/pkg/sql/opt/testutils/opttester/opt_tester.go#L485)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Just curious: any particular reason for auto instead of force_generic_plan?
</blockquote></details>

Not really. Auto will become the default at some point though, so I thought I'd mimic that. When it does, we'll need to change this setting.

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 8 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129050#-:-O4MwhOwCbtkkwc48qA3:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @michae2 and @rytaft)

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 8 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129050#-:-O4TCw4D4XLKMhuJllQM:bnfp4nl)* status: <span>:shipit:</span> complete! 3 of 0 LGTMs obtained (waiting on @michae2)

**Comment by mgartner** [comment]
TRTRs!

bors r+

**Pull request merged**
