### PR TITLE
release-20.2: sql: fix bug where bad mutation job state could block dropping tables

### PR DESCRIPTION
**Pull request by thoszhang**
Backport:
  * 1/1 commits from "sql: resolve error due to drop table after schema change in same txn" (#56589)
  * 1/1 commits from "sql: fix bug where bad mutation job state could block dropping tables" (#57836)

Please see individual PRs for details.

/cc @cockroachdb/release

### CODE REVIEW

**Comment by lucy-zhang** [comment]
The race detector does not like this test. Let me fix it.

**Comment by lucy-zhang** [comment]
```
diff --git a/pkg/sql/schema_changer_test.go b/pkg/sql/schema_changer_test.go
index d45d242e9f..163da27d2a 100644
--- a/pkg/sql/schema_changer_test.go
+++ b/pkg/sql/schema_changer_test.go
@@ -6132,7 +6132,7 @@ INSERT INTO t.test VALUES (1, 2), (2, 2);
        g := ctxgroup.WithContext(ctx)
        g.GoCtx(func(ctx context.Context) error {
                // Try to create a unique index which won't be valid and will need a rollback.
-               _, err = sqlDB.Exec(`CREATE UNIQUE INDEX i ON t.test(v);`)
+               _, err := sqlDB.Exec(`CREATE UNIQUE INDEX i ON t.test(v);`)
                assert.Regexp(t, "violates unique constraint", err)
                return nil
        })
```

Should be fine now.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58255#-:-MPGw2t96vut1ma_3E_S:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by lucy-zhang** [comment]
This is hitting #51544. I'm just going to re-run the tests.

**Pull request merged**
