### PR TITLE
sql: remove parallel statement execution

### LINKED ISSUE #17504: sql: tracing of parallel statements is hard to read
Example:
```sql
CREATE TABLE kv(k INT PRIMARY KEY, v INT);
INSERT INTO kv VALUES (1,2),(3,4);

SET TRACING=on;
BEGIN;
UPDATE t.kv SET v =123 WHERE k %2 = 0 RETURNING NOTHING; 
UPDATE t.kv SET v=431 WHERE k%2 = 1 RETURNING NOTHING; 
COMMIT; 
SET TRACING=off; 

SELECT age,substring(message,1,80) AS message,span FROM [SHOW TRACE FOR SESSION];
```

Outputs:

```
+----------------+----------------------------------------------------------------------------+--------+
|      age       |                                  message                                   |  span  |
+----------------+----------------------------------------------------------------------------+--------+
| 0s             | === SPAN START: sql txn implicit ===                                       | (0,0)  |
| 137µs609ns     | client.Txn did AutoCommit. err: <nil>␤                                     | (0,0)  |
|                | txn: "sql txn implicit" id=<nil> key=/Min                                  |        |
| 152µs217ns     | === SPAN START: sql txn ===                                                | (1,0)  |
| 163µs556ns     | executing 1/6: BEGIN TRANSACTION                                           | (1,0)  |
| 187µs838ns     | executing 2/6: UPDATE t.kv SET v = 123 WHERE (k % 2) = 0 RETURNING NOTHING | (1,0)  |
| 220µs350ns     | client.Txn did AutoCommit. err: <nil>␤                                     | (1,0)  |
|                | txn: "unnamed" id=<nil> key=/Min rw=false                                  |        |
| 231µs827ns     | added table 't.kv' to table collection                                     | (1,0)  |
| 284µs78ns      | client.Txn did AutoCommit. err: <nil>␤                                     | (1,0)  |
|                | txn: "unnamed" id=<nil> key=/Min rw=false                                  |        |
| 289µs346ns     | found table in table collection for table 't.kv'                           | (1,0)  |
| 482µs51ns      | executing 3/6: UPDATE t.kv SET v = 431 WHERE (k % 2) = 1 RETURNING NOTHING | (1,0)  |
| 508µs389ns     | client.Txn did AutoCommit. err: <nil>␤                                     | (1,0)  |
|                | txn: "unnamed" id=<nil> key=/Min rw=false                                  |        |
| 513µs743ns     | found table in table collection for table 't.kv'                           | (1,0)  |
| 539µs903ns     | client.Txn did AutoCommit. err: <nil>␤                                     | (1,0)  |
|                | txn: "unnamed" id=<nil> key=/Min rw=false                                  |        |
| 544µs9ns       | found table in table collection for table 't.kv'                           | (1,0)  |
| 705µs222ns     | querying next range at /Table/76/1                                         | (1,0)  |
| 734µs353ns     | executing 4/6: COMMIT TRANSACTION                                          | (1,0)  |
| 754µs368ns     | r181: sending batch 1 Scan to (n1,s1):1                                    | (1,0)  |
| 770µs956ns     | sending request to localhost:26257                                         | (1,0)  |
| 793µs693ns     | === SPAN START: /cockroach.roachpb.Internal/Batch ===                      | (1,1)  |
| 1ms208µs95ns   | === SPAN START: /cockroach.roachpb.Internal/Batch ===                      | (1,7)  |
| 1ms267µs682ns  | 1 Scan                                                                     | (1,7)  |
| 1ms327µs156ns  | executing 1 requests                                                       | (1,7)  |
| 1ms341µs663ns  | read-only path                                                             | (1,7)  |
| 1ms356µs175ns  | command queue                                                              | (1,7)  |
| 1ms369µs297ns  | waiting for read lock                                                      | (1,7)  |
| 1ms520µs529ns  | read completed                                                             | (1,7)  |
| 1ms924µs230ns  | querying next range at /Table/76/1/2/0                                     | (1,0)  |
| 1ms961µs689ns  | r181: sending batch 2 Put, 1 BeginTxn to (n1,s1):1                         | (1,0)  |
| 1ms987µs100ns  | sending request to localhost:26257                                         | (1,0)  |
| 2ms1µs270ns    | === SPAN START: /cockroach.roachpb.Internal/Batch ===                      | (1,2)  |
| 2ms256µs156ns  | === SPAN START: /cockroach.roachpb.Internal/Batch ===                      | (1,8)  |
| 2ms295µs505ns  | 2 Put, 1 BeginTxn                                                          | (1,8)  |
| 2ms310µs911ns  | executing 3 requests                                                       | (1,8)  |
| 2ms317µs971ns  | read-write path                                                            | (1,8)  |
| 2ms329µs76ns   | command queue                                                              | (1,8)  |
| 2ms378µs26ns   | applied timestamp cache                                                    | (1,8)  |
| 2ms583µs77ns   | evaluated request                                                          | (1,8)  |
| 2ms596µs697ns  | acquired {raft,replica}mu                                                  | (1,8)  |
| 4ms742µs397ns  | applying command                                                           | (1,8)  |
| 5ms227µs736ns  | coordinator spawns                                                         | (1,0)  |
| 5ms237µs537ns  | kv.TxnCoordSender: heartbeat loop ===                                      | (1,3)  |
| 5ms404µs899ns  | querying next range at /Table/76/1                                         | (1,0)  |
| 5ms444µs706ns  | r181: sending batch 1 Scan to (n1,s1):1                                    | (1,0)  |
| 5ms465µs980ns  | sending request to localhost:26257                                         | (1,0)  |
| 5ms480µs156ns  | === SPAN START: /cockroach.roachpb.Internal/Batch ===                      | (1,4)  |
| 5ms747µs79ns   | === SPAN START: /cockroach.roachpb.Internal/Batch ===                      | (1,9)  |
| 5ms776µs283ns  | 1 Scan                                                                     | (1,9)  |
| 5ms787µs923ns  | executing 1 requests                                                       | (1,9)  |
| 5ms794µs445ns  | read-only path                                                             | (1,9)  |
| 5ms801µs145ns  | command queue                                                              | (1,9)  |
| 5ms808µs805ns  | waiting for read lock                                                      | (1,9)  |
| 5ms910µs485ns  | read completed                                                             | (1,9)  |
| 6ms196µs19ns   | querying next range at /Table/76/1/1/0                                     | (1,0)  |
| 6ms224µs750ns  | r181: sending batch 3 Put to (n1,s1):1                                     | (1,0)  |
| 6ms242µs299ns  | sending request to localhost:26257                                         | (1,0)  |
| 6ms255µs922ns  | === SPAN START: /cockroach.roachpb.Internal/Batch ===                      | (1,5)  |
| 6ms535µs859ns  | === SPAN START: /cockroach.roachpb.Internal/Batch ===                      | (1,10) |
| 6ms565µs86ns   | 3 Put                                                                      | (1,10) |
| 6ms576µs276ns  | executing 3 requests                                                       | (1,10) |
| 6ms582µs313ns  | read-write path                                                            | (1,10) |
| 6ms589µs205ns  | command queue                                                              | (1,10) |
| 6ms620µs876ns  | applied timestamp cache                                                    | (1,10) |
| 6ms715µs543ns  | evaluated request                                                          | (1,10) |
| 6ms724µs125ns  | acquired {raft,replica}mu                                                  | (1,10) |
| 8ms544µs886ns  | applying command                                                           | (1,10) |
| 9ms28µs742ns   | querying next range at /Table/76/1/2/0                                     | (1,0)  |
| 9ms54µs262ns   | r181: sending batch 1 EndTxn to (n1,s1):1                                  | (1,0)  |
| 9ms76µs865ns   | sending request to localhost:26257                                         | (1,0)  |
| 9ms91µs159ns   | === SPAN START: /cockroach.roachpb.Internal/Batch ===                      | (1,6)  |
| 9ms322µs159ns  | === SPAN START: /cockroach.roachpb.Internal/Batch ===                      | (1,11) |
| 9ms351µs56ns   | 1 EndTxn                                                                   | (1,11) |
| 9ms369µs757ns  | executing 1 requests                                                       | (1,11) |
| 9ms376µs128ns  | read-write path                                                            | (1,11) |
| 9ms384µs519ns  | command queue                                                              | (1,11) |
| 9ms406µs522ns  | applied timestamp cache                                                    | (1,11) |
| 9ms604µs457ns  | evaluated request                                                          | (1,11) |
| 9ms613µs313ns  | acquired {raft,replica}mu                                                  | (1,11) |
| 11ms467µs29ns  | applying command                                                           | (1,11) |
| 11ms812µs660ns | coordinator stops                                                          | (1,0)  |
| 11ms894µs771ns | === SPAN START: sql txn implicit ===                                       | (2,0)  |
| 11ms923µs919ns | executing 1/1: SET tracing = 'off'                                         | (2,0)  |
+----------------+----------------------------------------------------------------------------+--------+
(81 rows)
```

I can see there are multiple spans for the execution of UPDATE after the COMMIT message has been received (as expected, COMMIT waits for the parallel statements to complete) however I don't know how to map which span belongs to which statement.

cc @cockroachdb/sql-execution

### LINKED ISSUE #18226: sql: Add ASYNC/AWAIT or futures for parallel statements
This will allow a client to issue sql statements that can be executed asynchronously.

We can start working on this once there is a need.

### LINKED ISSUE #34789: sql: remove parallel statement execution and deprecate RETURNING NOTHING
_I was planning on making this change immediately but figured I'd get buy-in from relevant stakeholders beforehand so that there's not too much back and forth on the PR itself._

Parallel statement execution has served its role well, but with the introduction of transactional write pipelining, the cases where it is useful or should be recommended have dropped to near-zero. I think it's time to remove it. I also know others feel differently. Here's a list of reasons to remove the feature and reasons to keep it:

### Reasons to remove
- **Technical debt**. This is getting in the way of future development. For instance, it slowed down optimizer development and the team decided to ignore the feature. We also have issues tied to it (#17504 and #18226).
- The feature is rarely needed anymore. Txn pipelining takes almost all of the win away from parallel statement execution (see below)
- The feature is confusing to users. When should they use it? When not?
- Hard to use correctly. How does this work with ORMs? What are the error semantics again?
- Even if we want to allow some kind of concurrency between reads in a transaction, this isn't the way to do it. A better approach is permitting the use of multiple portals concurrently, as @andreimatei and @jordanlewis experimented with.
- Only ~2% of CRDB users have ever used the feature.

### Reasons to keep
- Removing it would be breaking compatibility.
- Removing the feature would prevent it from being extended further.
- There are still rare cases where `RETURNING NOTHING` will be faster than standard txn pipelining, such as when a gateway is far away from a leaseholder.

### Deprecation/Removal Plan

1. Remove all logic about executing statements in parallel (e.g. `ParallelizeQueue`, `DependencyAnalyzer`, `connExecutor.execStmtInParallel`, etc.)
2. Remove all tests for executing statements in parallel
3. Keep `RETURNING NOTHING` syntax but make it a no-op other than still discarding results on succesful queries. Doing this will prevent us from breaking client applications.
4. Remove documentation on parallel statement execution
5. (optional) In some later release, remove the `RETURNING NOTHING` syntax entirely

What do people think? 

cc. @bdarnell @andreimatei @jordanlewis @knz

### LINKED ISSUE #35780: runtime error: invalid memory address or nil pointer dereference
**Describe the problem**

I have a piece of Rust code that runs two SQL statements. These two statements, when executed, cause CockroachDB to crash.

**To Reproduce**

Unfortunately, I wasn't able to reproduce it outside of our code.

Table structure:
```
CREATE TABLE sample(key STRING NOT NULL, value BOOL NOT NULL);
```

Two statements (they are executed inside single transaction, one after another):

```
UPDATE sample SET value = true WHERE key NOT IN ('123') RETURNING NOTHING;
INSERT INTO sample(key) VALUES ('123') ON CONFLICT (key) DO UPDATE SET value = false WHERE value = true;
```

There is an error in the second statement (in WHERE clause, should be `sample.value`) which, I think, triggers the crash. If this error is fixed, everything works fine.

**Additional data / screenshots**

From logs:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4960ace]

goroutine 314 [running]:
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).ID(0x0, 0x0, 0x0)
        /private/tmp/cockroach-20190219-43186-1p8lwnc/cockroach-v2.1.5/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:163 +0x2e
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).synchronizeParallelStmts(0xc005ee3500, 0x6d19900, 0xc005f0e200, 0x0, 0x0)
        /private/tmp/cockroach-20190219-43186-1p8lwnc/cockroach-v2.1.5/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1631 +0xda
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).close(0xc005ee3500, 0x6d19900, 0xc005f0e200, 0x0)
        /private/tmp/cockroach-20190219-43186-1p8lwnc/cockroach-v2.1.5/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:673 +0xb3
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc005ee3500, 0x6d19900, 0xc005f0e200, 0x0, 0x0)
        /private/tmp/cockroach-20190219-43186-1p8lwnc/cockroach-v2.1.5/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:654 +0x70
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc005ee3500, 0x6d19900, 0xc005f0e200)
        /private/tmp/cockroach-20190219-43186-1p8lwnc/cockroach-v2.1.5/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:387 +0x61
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc0007b9ef0, 0x6d19900, 0xc005f0e200, 0xc005ee3500, 0x5400, 0x15000, 0xc0009fca70, 0xc0003e3d40, 0x0, 0x0)
        /private/tmp/cockroach-20190219-43186-1p8lwnc/cockroach-v2.1.5/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:389 +0xe9
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func4(0xc0007b9ef0, 0x6d19900, 0xc005f0e200, 0xc005ee3500, 0x5400, 0x15000, 0xc0009fca70, 0xc0003e3d40, 0xc0003e3d50, 0xc005ba3d14)
        /private/tmp/cockroach-20190219-43186-1p8lwnc/cockroach-v2.1.5/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:313 +0x81
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
        /private/tmp/cockroach-20190219-43186-1p8lwnc/cockroach-v2.1.5/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:312 +0x1018
```

**Environment:**
 - CockroachDB version: `CCL v2.1.5 @ 2019/02/19 16:38:43 (go1.11.5)`
 - Server OS: macOS
 - Client app: Rust postgres driver

### PR DESCRIPTION
**Pull request by nvb**
Fixes #34789.
Closes #17504.
Closes #18226.
Closes #35780.

This commit removes all logic supporting parallel statement execution.
It does so following the removal plan described in #34789. There is only
one deviation from the plan, which is that we don't do anything to
prevent statements with `RETURNING NOTHING` syntax from returning valid
results. Specifically, statements with `RETURNING NOTHING` may return
the actual number of rows affected instead of the dummy value of 1. It's
highly unlikely that anyone was relying on this behavior and it wasn't
documented.

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
:lgtm_strong: 

> Reviewed 2 of 2 files at r1, 120 of 120 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35959#-:-LaMT0Wa6oEHqyfU4BBY:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @nvanbenschoten)

___
*[pkg/sql/values.go, line 154 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35959#-LaMSTuf01vzSbMd65Iv:-LaMSTugBkqIIRvDFc4S:b-jpm6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aba654b593600c5f471637c219fe57bfe297919/pkg/sql/values.go#L154)):*
> ```Go
> 	if n.rows != nil {
> 		if !n.isConst {
> 			log.Fatalf(params.ctx, "valuesNode evaluated twice")
> ```

Hmm, I'm not sure about deleting this. valuesNode being evaluated twice is still a bad thing.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35959)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/values.go, line 154 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35959#-LaMSTuf01vzSbMd65Iv:-LaMgF0L6idA25PohOkS:btg3oke) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aba654b593600c5f471637c219fe57bfe297919/pkg/sql/values.go#L154)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Hmm, I'm not sure about deleting this. valuesNode being evaluated twice is still a bad thing.
</blockquote></details>

The `isConst` stuff was always pretty messy. It was added in https://github.com/cockroachdb/cockroach/commit/1a71f80dbcccb51b908089ee42ee41f2598866fb so that we could evaluate `valuesNode`s during span analysis. Now that we ripped span analysis out, I don't think we need it. Are there other reasons that a valuesNode would be evaluated twice?

**Comment by jordanlewis** [comment]
Bugs. I'd just prefer to see that Fatal left in unconditionally.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35959)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @nvanbenschoten)

___
*[pkg/sql/values.go, line 154 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35959#-LaMSTuf01vzSbMd65Iv:-LaN9MBTAgfWPrR10ozP:b-pudl2w) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aba654b593600c5f471637c219fe57bfe297919/pkg/sql/values.go#L154)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The `isConst` stuff was always pretty messy. It was added in https://github.com/cockroachdb/cockroach/commit/1a71f80dbcccb51b908089ee42ee41f2598866fb so that we could evaluate `valuesNode`s during span analysis. Now that we ripped span analysis out, I don't think we need it. Are there other reasons that a valuesNode would be evaluated twice?
</blockquote></details>

If you keep the path, please change this to `return pgerror.NewAssertionErrorf(....)`. This way we're not crashing a node for something that merely deserves a client close.
___
*[pkg/sql/values.go, line 195 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35959#-LaN9Rnb8y9GCyVkietW:-LaN9Rnb8y9GCyVkietX:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aba654b593600c5f471637c219fe57bfe297919/pkg/sql/values.go#L195)):*
> ```Go
> func (n *valuesNode) Reset(ctx context.Context) {
> 	if !n.isConst {
> 		log.Fatalf(ctx, "valuesNode.Reset can only be called on constant valuesNodes")
> ```

ditto

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35959)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @knz)

___
*[pkg/sql/values.go, line 154 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35959#-LaMSTuf01vzSbMd65Iv:-LbP3bY56aiHrp-fD23U:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aba654b593600c5f471637c219fe57bfe297919/pkg/sql/values.go#L154)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

If you keep the path, please change this to `return pgerror.NewAssertionErrorf(....)`. This way we're not crashing a node for something that merely deserves a client close.
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
> Reviewed 1 of 120 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35959)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @knz)

**Comment by knz** [comment]
Thank you!

This is good to go, moreover @BramGruneir needs it for an ongoing project.

**Comment by nvanbenschoten** [comment]
TFTRs!

bors r+

**Pull request merged**
