### PR TITLE
schemachanger: add statement tags and full resolve names in event logging

### PR DESCRIPTION
**Pull request by fqazi**
Previously, the declarative schema changer did not include
tags or fully resolve object names in event log entries. This was 
inadequate because the declarative schema changer did not 
have the same event logs as the existing schema changer. 
To address this, these patches will add a statement tags, 
fully resolve schema names and add the ability to annotate
the names inside the SQL AST inside the declarative schema 
change builder.

Release Note: None

### CODE REVIEW

**Comment by postamar** [comment]
I'm going to sit this one out for now and defer to @ajwerner, I know very little about AST annotations and how they're meant to be used.

**Review by ajwerner — CHANGES_REQUESTED** [review]
> Reviewed 7 of 16 files at r5, 3 of 20 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73692)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @postamar)

___
*[pkg/sql/schemachanger/scbuild/ast_annotator.go, line 19 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-Msf1Wy31ipRAFl2jQ6V:-Msf1Wy31ipRAFl2jQ6W:b-y5vd2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/46483acd2fdba7297e8e0438b859044a22197ec5/pkg/sql/schemachanger/scbuild/ast_annotator.go#L19)):*
> ```Go
> )
> 
> type astAnnotator struct {
> ```

comment this thing
___
*[pkg/sql/schemachanger/scbuild/ast_annotator.go, line 19 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-Msf1qFr2M0tStfYrtVP:-Msf1YA91y7Wem5vs5Rv:bkual50) ([raw file](https://github.com/cockroachdb/cockroach/blob/46483acd2fdba7297e8e0438b859044a22197ec5/pkg/sql/schemachanger/scbuild/ast_annotator.go#L19)):*
> ```Go
> )
> 
> type astAnnotator struct {
> ```

can you do the `var _ <interface> = (*astAnnotator)(nil)` ceremony? 
___
*[pkg/sql/schemachanger/scbuild/ast_annotator.go, line 22 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-Msf1TJ54z2j701AgTPy:-Msf1TJ54z2j701AgTPz:b4gsdga) ([raw file](https://github.com/cockroachdb/cockroach/blob/46483acd2fdba7297e8e0438b859044a22197ec5/pkg/sql/schemachanger/scbuild/ast_annotator.go#L22)):*
> ```Go
> 	statement        tree.Statement
> 	annotation       tree.Annotations
> 	nonExistentNames map[*tree.TableName]struct {
> ```

nit: `map[*tree.TableName]struct{}`



_Code quote:_
```Go
	nonExistentNames map[*tree.TableName]struct {
	}
```
___
*[pkg/sql/schemachanger/scbuild/ast_annotator.go, line 32 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-Msf1fcO1dPGgnZNsdfx:-Msf1fcO1dPGgnZNsdfy:b-7kooso) ([raw file](https://github.com/cockroachdb/cockroach/blob/46483acd2fdba7297e8e0438b859044a22197ec5/pkg/sql/schemachanger/scbuild/ast_annotator.go#L32)):*
> ```Go
> }
> 
> // SetStatementOnce implements scbuildstmt.AnnotationProvider
> ```

nit: periods
___
*[pkg/sql/schemachanger/scbuild/ast_annotator.go, line 34 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-Msf4LzbEJ-gg8WtiSQu:-Msf4LzbEJ-gg8WtiSQv:bqdyufc) ([raw file](https://github.com/cockroachdb/cockroach/blob/46483acd2fdba7297e8e0438b859044a22197ec5/pkg/sql/schemachanger/scbuild/ast_annotator.go#L34)):*
> ```Go
> // SetStatementOnce implements scbuildstmt.AnnotationProvider
> func (ann *astAnnotator) SetStatementOnce(original tree.Statement) tree.Statement {
> 	if ann.statement != nil {
> ```

I wonder if this is going to hurt when we do the view elements. I think we end up getting it annotated before we get to this point. 
___
*[pkg/sql/schemachanger/scbuild/ast_annotator.go, line 59 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-Msf1chQCsrzIdDy3Ri7:-Msf1chQCsrzIdDy3Ri8:b9532zv) ([raw file](https://github.com/cockroachdb/cockroach/blob/46483acd2fdba7297e8e0438b859044a22197ec5/pkg/sql/schemachanger/scbuild/ast_annotator.go#L59)):*
> ```Go
> // ValidateAnnotations implements scbuildstmt.AnnotationProvider
> func (ann *astAnnotator) ValidateAnnotations() {
> 	// Sanity: All the names are fully resolved inside the AST.
> ```

Can you use some more words on this comment. 
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go, line 40 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-Msf245r0p1rK1q9UroU:-Msf245r0p1rK1q9UroV:b-pim8gx) ([raw file](https://github.com/cockroachdb/cockroach/blob/46483acd2fdba7297e8e0438b859044a22197ec5/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go#L40)):*
> ```Go
> 		panic(sqlerrors.NewUndefinedRelationError(n.Table.ToUnresolvedObjectName()))
> 	}
> 	n.Table.ObjectNamePrefix = prefix.NamePrefix()
> ```

do we have to mutate the AST here? I imagine this is what's happening in the existing path so this is for parity? 
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go, line 287 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-Msf6-JzAfw1iK4fifdu:-Msf6-JzAfw1iK4fifdv:b6e8ja9) ([raw file](https://github.com/cockroachdb/cockroach/blob/46483acd2fdba7297e8e0438b859044a22197ec5/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go#L287)):*
> ```Go
> // AnnotationProvider provides interfaces to be able to modify the AST safely,
> // by providing a copy and support for adding annotations.
> type AnnotationProvider interface {
> ```

I think this is the wrong interface for `scbuildstmt`. Most of the methods are only used in the `scbuild` layer. Let's leave those methods just on the implementation. What do you think about this for the interface:

```go
type TreeAnnotator interface {
    // SetAnnotation sets the annotation for the provided tree node.
    SetAnnotation(tree.AnnotatedNode, annotation interface{})
    // MarkObjectAsNonExistent will indicate that a name does not correspond to
    // an existing object and will skip resolution for subsequent references to it.
    MarkNameAsNonExistent(name tree.ObjectName)
}
```
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go, line 288 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-Msf2FlU4eZg1BN15BMR:-Msf2FlU4eZg1BN15BMS:b-r69ut9) ([raw file](https://github.com/cockroachdb/cockroach/blob/46483acd2fdba7297e8e0438b859044a22197ec5/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go#L288)):*
> ```Go
> // by providing a copy and support for adding annotations.
> type AnnotationProvider interface {
> 	// SetStatementOnce sets the current AST, clone it and allocate space for
> ```

uber-nit: SetStatementOnce sets the current AST, clone**s** it and allocate**s** space for annotation**s**
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go, line 291 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-Msf2_5p40x_frA6b960:-Msf2_5p40x_frA6b961:b-ukbwxa) ([raw file](https://github.com/cockroachdb/cockroach/blob/46483acd2fdba7297e8e0438b859044a22197ec5/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go#L291)):*
> ```Go
> 	// annotation. This function returns a copy of the original AST that can be
> 	// safely modified by the caller.
> 	SetStatementOnce(original tree.Statement) tree.Statement
> ```

why is it `Once`? Can you note the behavior on subsequent calls? I revisited this, see my comment above. I think the answer is that we construct the implementation of this thing with the statement and avoid the method altogether. 
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go, line 81 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-Msf3Bzo34ZEGUz1rdSa:-Msf3Bzo34ZEGUz1rdSb:bpw0wji) ([raw file](https://github.com/cockroachdb/cockroach/blob/46483acd2fdba7297e8e0438b859044a22197ec5/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go#L81)):*
> ```Go
> 	// Clone the initial tree for the builder, which will inject
> 	// names inside the tree.
> 	n := b.SetStatementOnce(initialNode)
> ```

nit: keep just one `tree.Statement` variable. We never want to see the previous one after we've cloned it. 

```go
func Process(b BuildCtx, n tree.Statement) {
	// Clone the initial tree for the builder, which will inject
	// names inside the tree.
	n = b.SetStatementOnce(n)
```



_Code quote:_
```Go
func Process(b BuildCtx, initialNode tree.Statement) {
	// Clone the initial tree for the builder, which will inject
	// names inside the tree.
	n := b.SetStatementOnce(initialNode)
```

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73692)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/schemachanger/scbuild/ast_annotator.go, line 19 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-Msf1Wy31ipRAFl2jQ6V:-MskTaXC7Z3pzaB5hizt:b-ihwf4d) ([raw file](https://github.com/cockroachdb/cockroach/blob/46483acd2fdba7297e8e0438b859044a22197ec5/pkg/sql/schemachanger/scbuild/ast_annotator.go#L19)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

comment this thing
</blockquote></details>

Done.

Added: 
//astAnnotator creates a copy of the AST that can be annotated or modified
//safely without impacting the original statement. This structure will implement
//scbuildstmt.TreeAnnotator.
___
*[pkg/sql/schemachanger/scbuild/ast_annotator.go, line 34 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-Msf4LzbEJ-gg8WtiSQu:-MskTnrRDzf4OhuCWbId:b63ksiw) ([raw file](https://github.com/cockroachdb/cockroach/blob/46483acd2fdba7297e8e0438b859044a22197ec5/pkg/sql/schemachanger/scbuild/ast_annotator.go#L34)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I wonder if this is going to hurt when we do the view elements. I think we end up getting it annotated before we get to this point. 
</blockquote></details>

Done.

Added a TODO:
	// TODO(fqazi): The optimizer can end up already modifying the statement above
	// to fully resolve names. We need to take this into account for CTAS/CREATE
	// VIEW statements.
___
*[pkg/sql/schemachanger/scbuild/ast_annotator.go, line 59 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-Msf1chQCsrzIdDy3Ri7:-MskTs9-EVLlM9jt0W_P:bq6xbyt) ([raw file](https://github.com/cockroachdb/cockroach/blob/46483acd2fdba7297e8e0438b859044a22197ec5/pkg/sql/schemachanger/scbuild/ast_annotator.go#L59)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Can you use some more words on this comment. 
</blockquote></details>

Done.

Changed this to:
	// Sanity: Goes through the entire AST and confirms that and table names that
	// appear inside it are fully resolved, meaning that both the database and
	// schema are known.
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go, line 40 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-Msf245r0p1rK1q9UroU:-MskU9KG8E4m_jw5OOIY:b90ej7o) ([raw file](https://github.com/cockroachdb/cockroach/blob/46483acd2fdba7297e8e0438b859044a22197ec5/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go#L40)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

do we have to mutate the AST here? I imagine this is what's happening in the existing path so this is for parity? 
</blockquote></details>

Done.

Added the comment:
	// Mutate the AST to have the fully resolved name from above, which will be
	// used for both event logging and errors.
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go, line 287 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-Msf6-JzAfw1iK4fifdu:-MskUGmQ5p_w26r981wV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/46483acd2fdba7297e8e0438b859044a22197ec5/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go#L287)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think this is the wrong interface for `scbuildstmt`. Most of the methods are only used in the `scbuild` layer. Let's leave those methods just on the implementation. What do you think about this for the interface:

```go
type TreeAnnotator interface {
    // SetAnnotation sets the annotation for the provided tree node.
    SetAnnotation(tree.AnnotatedNode, annotation interface{})
    // MarkObjectAsNonExistent will indicate that a name does not correspond to
    // an existing object and will skip resolution for subsequent references to it.
    MarkNameAsNonExistent(name tree.ObjectName)
}
```
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go, line 288 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-Msf2FlU4eZg1BN15BMR:-MskUH9kChD8TwmL4ZrQ:b-cai6r8) ([raw file](https://github.com/cockroachdb/cockroach/blob/46483acd2fdba7297e8e0438b859044a22197ec5/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go#L288)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

uber-nit: SetStatementOnce sets the current AST, clone**s** it and allocate**s** space for annotation**s**
</blockquote></details>

Done.

Eliminated this method
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go, line 291 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-Msf2_5p40x_frA6b960:-MskUOK61A-sNlmtpiYB:bg5n5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/46483acd2fdba7297e8e0438b859044a22197ec5/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go#L291)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

why is it `Once`? Can you note the behavior on subsequent calls? I revisited this, see my comment above. I think the answer is that we construct the implementation of this thing with the statement and avoid the method altogether. 
</blockquote></details>

Done.

Removed the astAnnotator now does this.

**Review by postamar — CHANGES_REQUESTED** [review]
I did a pass now, and I noticed some oddities.

> Reviewed 1 of 11 files at r1, 1 of 31 files at r4, 1 of 20 files at r6, 13 of 15 files at r10, 20 of 20 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-:-Msp2cg_3XhTXl2Lf5_5:bg4pbzk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[pkg/sql/schemachanger/scbuild/ast_annotator.go, line 22 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-MsorRtbDFazu3Jms4mc:-MsorRtbDFazu3Jms4md:b-ele9pf) ([raw file](https://github.com/cockroachdb/cockroach/blob/975b32d33d188179ecae40ce6f4ebe46cdaa9c89/pkg/sql/schemachanger/scbuild/ast_annotator.go#L22)):*
> ```Go
> //astAnnotator creates a copy of the AST that can be annotated or modified
> //safely without impacting the original statement. This structure will implement
> //scbuildstmt.TreeAnnotator.
> ```

nit: missing space after `//`.

Also your `This structure will implement scbuildstmt.TreeAnnotator.` can be removed if you move up 
```
var _ scbuildstmt.TreeAnnotator = (*astAnnotator)(nil)
```
to below the `astAnnotator` definition. Self-explanatory code is always preferable.
___
*[pkg/sql/schemachanger/scbuild/ast_annotator.go, line 46 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-Msp1biw-mb36JYS4ifE:-Msp1biw-mb36JYS4ifF:b-555gtc) ([raw file](https://github.com/cockroachdb/cockroach/blob/975b32d33d188179ecae40ce6f4ebe46cdaa9c89/pkg/sql/schemachanger/scbuild/ast_annotator.go#L46)):*
> ```Go
> func (ann *astAnnotator) GetStatement() tree.Statement {
> 	return ann.statement
> }
> ```

This method is not necessary.
___
*[pkg/sql/schemachanger/scbuild/build.go, line 30 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-MsosxV20BqQc1ohMINs:-MsosxV20BqQc1ohMINt:bf7wz6c) ([raw file](https://github.com/cockroachdb/cockroach/blob/975b32d33d188179ecae40ce6f4ebe46cdaa9c89/pkg/sql/schemachanger/scbuild/build.go#L30)):*
> ```Go
> ) (_ scpb.State, err error) {
> 	bs := newBuilderState(initial)
> 	els := newEventLogState(dependencies, initial, n, dependencies.AstFormatter())
> ```

Isn't this argument redundant? You're already passing `dependencies`.
___
*[pkg/sql/schemachanger/scbuild/build.go, line 54 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-Msovf4q5ZUrzruQLY6U:-Msovf4q5ZUrzruQLY6V:b-t3kxhx) ([raw file](https://github.com/cockroachdb/cockroach/blob/975b32d33d188179ecae40ce6f4ebe46cdaa9c89/pkg/sql/schemachanger/scbuild/build.go#L54)):*
> ```Go
> 		}
> 	}()
> 	scbuildstmt.Process(b, an.GetStatement())
> ```

Why are we passing the current statement here? It's already readily available to `Process` via `b.an.GetStatement()`.
___
*[pkg/sql/schemachanger/scbuild/build.go, line 57 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-Msot_i7DCAwSJETRpmb:-Msot_i7DCAwSJETRpmc:bo71lid) ([raw file](https://github.com/cockroachdb/cockroach/blob/975b32d33d188179ecae40ce6f4ebe46cdaa9c89/pkg/sql/schemachanger/scbuild/build.go#L57)):*
> ```Go
> 	// Validate the annotations generated after processing the statement.
> 	an.ValidateAnnotations()
> 	// Finalize, the event log state for the current statement.
> ```

nit: spurious comma, also I'm not sure how useful this comment is in the first place. The same goes for the one above, it all seems pretty obvious given the names of the methods that are called.
___
*[pkg/sql/schemachanger/scbuild/event_log_state.go, line 54 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-MsovBGi3iz7Dby2wMon:-MsovBGi3iz7Dby2wMoo:bv12k0t) ([raw file](https://github.com/cockroachdb/cockroach/blob/975b32d33d188179ecae40ce6f4ebe46cdaa9c89/pkg/sql/schemachanger/scbuild/event_log_state.go#L54)):*
> ```Go
> 	e.statements[len(e.statements)-1].RedactedStatement =
> 		string(e.astFormatter.FormatAstAsRedactableString(statement, annotations))
> }
> ```

I'd prefer inlining this in `Build` to be honest. You have the entire lifecycle of the current statement AST in there already, it would feel natural (to me at least) to set this `RedactedStatement` directly in the returned state. This also allows you to get rid of `astFormatter` in `eventLogState`.
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go, line 60 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-MsoyHonCvhhWqJ88sxh:-MsoyHonCvhhWqJ88sxi:b-wfyo0j) ([raw file](https://github.com/cockroachdb/cockroach/blob/975b32d33d188179ecae40ce6f4ebe46cdaa9c89/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go#L60)):*
> ```Go
> 	})
> 	tn.ObjectNamePrefix = prefix.NamePrefix()
> 	n.Table.SetAnnotation(b.GetAnnotations(), &tn)
> ```

This feels like it should read `b.SetAnnotation(n.Table, &tn)` instead.
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go, line 41 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-MsoxPftCY9xKaYgD8L_:-MsoxPftCY9xKaYgD8La:buio7qi) ([raw file](https://github.com/cockroachdb/cockroach/blob/975b32d33d188179ecae40ce6f4ebe46cdaa9c89/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go#L41)):*
> ```Go
> 	// Mutate the AST to have the fully resolved name from above, which will be
> 	// used for both event logging and errors.
> 	n.Table.ObjectNamePrefix = prefix.NamePrefix()
> ```

Considering that we maintain a copied AST in `b.an`,  shouldn't we mutate that one instead of `n`? Or perhaps we don't actually need `b.an.statement` at all?
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go, line 287 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-Msp04kv1yaHyD4g-yFq:-Msp04kv1yaHyD4g-yFr:bw5hume) ([raw file](https://github.com/cockroachdb/cockroach/blob/975b32d33d188179ecae40ce6f4ebe46cdaa9c89/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go#L287)):*
> ```Go
> type TreeAnnotator interface {
> 	// GetAnnotations returns the set of annotations applied on the AST.
> 	GetAnnotations() *tree.Annotations
> ```

This follows up on a previous comment: it's weird to have a `TreeAnnotator` interface and then nothing in it that actually annotates a tree.
___
*[pkg/sql/schemachanger/scpb/scpb.proto, line 298 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-Msp0WTr3Ms4XLzjdoYW:-Msp0WTr3Ms4XLzjdoYX:bqeawsu) ([raw file](https://github.com/cockroachdb/cockroach/blob/975b32d33d188179ecae40ce6f4ebe46cdaa9c89/pkg/sql/schemachanger/scpb/scpb.proto#L298)):*
> ```protobuf
> message Statement {
>   string statement = 1;
>   string redactedStatement = 2;
> ```

use snake case

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73692)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/schemachanger/scbuild/ast_annotator.go, line 46 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-Msp1biw-mb36JYS4ifE:-Mt3fwGl7fb2fP_N3WAs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/975b32d33d188179ecae40ce6f4ebe46cdaa9c89/pkg/sql/schemachanger/scbuild/ast_annotator.go#L46)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

This method is not necessary.
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scbuild/build.go, line 30 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-MsosxV20BqQc1ohMINs:-Mt3fx4J7VcPGGyPa3K3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/975b32d33d188179ecae40ce6f4ebe46cdaa9c89/pkg/sql/schemachanger/scbuild/build.go#L30)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Isn't this argument redundant? You're already passing `dependencies`.
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scbuild/build.go, line 54 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-Msovf4q5ZUrzruQLY6U:-Mt3fxja3m4MfunRMtQx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/975b32d33d188179ecae40ce6f4ebe46cdaa9c89/pkg/sql/schemachanger/scbuild/build.go#L54)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Why are we passing the current statement here? It's already readily available to `Process` via `b.an.GetStatement()`.
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go, line 60 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-MsoyHonCvhhWqJ88sxh:-Mt3fzT83Y7pCccfLhVC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/975b32d33d188179ecae40ce6f4ebe46cdaa9c89/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go#L60)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

This feels like it should read `b.SetAnnotation(n.Table, &tn)` instead.
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go, line 41 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-MsoxPftCY9xKaYgD8L_:-Mt3g-n59pxUy3kykRlS:b-mbgrha) ([raw file](https://github.com/cockroachdb/cockroach/blob/975b32d33d188179ecae40ce6f4ebe46cdaa9c89/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go#L41)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Considering that we maintain a copied AST in `b.an`,  shouldn't we mutate that one instead of `n`? Or perhaps we don't actually need `b.an.statement` at all?
</blockquote></details>

This was supposed to be done when calling Build fetching the statement the tree annotator.
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go, line 287 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-Msp04kv1yaHyD4g-yFq:-Mt3ggI7Ecybvr5nDKYa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/975b32d33d188179ecae40ce6f4ebe46cdaa9c89/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go#L287)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

This follows up on a previous comment: it's weird to have a `TreeAnnotator` interface and then nothing in it that actually annotates a tree.
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scpb/scpb.proto, line 298 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-Msp0WTr3Ms4XLzjdoYW:-Mt3ghG50WBGTEo-k-0A:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/975b32d33d188179ecae40ce6f4ebe46cdaa9c89/pkg/sql/schemachanger/scpb/scpb.proto#L298)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

use snake case
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scbuild/event_log_state.go, line 54 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-MsovBGi3iz7Dby2wMon:-Mt3glpL2VWv8w4UaN2I:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/975b32d33d188179ecae40ce6f4ebe46cdaa9c89/pkg/sql/schemachanger/scbuild/event_log_state.go#L54)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I'd prefer inlining this in `Build` to be honest. You have the entire lifecycle of the current statement AST in there already, it would feel natural (to me at least) to set this `RedactedStatement` directly in the returned state. This also allows you to get rid of `astFormatter` in `eventLogState`.
</blockquote></details>

Done.

**Review by postamar — APPROVED** [review]
:lgtm:

> Reviewed 5 of 25 files at r12, 20 of 20 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73692#-:-Mt4d4Lv4HT3rItAAYem:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by fqazi** [comment]
@postamar TFTR!

**Pull request merged**
