### PR TITLE
forbiddenmethod: add (disabled) lint against  `(*errgroup.Group).Go` and `go`

### PR DESCRIPTION
**Pull request by tbg**
This helps move the needle on #58164 by introducing linters that
force both the use of a `ctxgroup` over an `errgroup` and prevent
direct use of the `go` keyword.

They are disabled by default because we need to fix the issues they
find first. This can be done (for development) in
`forbiddenmethod.Analyzers`. They can then also be invoked in a targeted
fashion:

```
go vet -vettool ./bin/roachvet -errgroupgo ./pkg/somewhere
go vet -vettool ./bin/roachvet -nakedgo ./pkg/somewhere
```

Release note: None

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
:lgtm: but I wonder if we maybe should exclude internal tooling such as `roachprod` and `workload` where this isn't really a concern.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62243#-:-MW94SpX0F_qIW2NtptE:b-phxicq)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by knz — APPROVED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62243)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

**Comment by tbg** [comment]
Thanks for the quick reviews! I have some WIP to actually fix a bunch of the lint failures but figured it was better to merge this as-is first, with the lints there but not part of `make lint`.

I also finally figured out how to make the `//nolint:nakedgo` thing work, PTAL.

**Review by jordanlewis — APPROVED** [review]
This is awesome, LGTM!

**Review by erikgrinaker — COMMENTED** [review]
> Reviewed 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62243)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz and @tbg)

___
*[pkg/testutils/lint/lint_test.go, line 2006 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62243#-MWAP92a0gQJ3klG9YwE:-MWAP92a0gQJ3klG9YwF:b-zg7wkb) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d4dcee033f14e7af3f882b478aab763c339819c/pkg/testutils/lint/lint_test.go#L2006)):*
> ```Go
> 
> 		nakedGoroutineExceptions := `(` + strings.Join([]string{
> 			`pkg/.*_test.go`,
> ```

Escape the `.`.
___
*[pkg/testutils/lint/passes/forbiddenmethod/naked_go.go, line 46 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62243#-MWAPsgnArqkqD27S5bH:-MWAPsgnArqkqD27S5bI:b-7jslx9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d4dcee033f14e7af3f882b478aab763c339819c/pkg/testutils/lint/passes/forbiddenmethod/naked_go.go#L46)):*
> ```
> 			// The approach here is inspired by `analysistest.check` - the
> 			// nolint comment has to be on the same line as the *end* of the
> 			// `*GoStmt`.
> ```

Hm, this is a bit unfortunate -- for inline large-body goroutines it'd be most natural to put the nolint above it. Although I suppose we won't be using a whole lot of go keywords anyway, so maybe it's ok if the ergonomics are a bit off. Happy to have an escape hatch at all!
___
*[pkg/testutils/lint/passes/forbiddenmethod/naked_go.go, line 67 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62243#-MWAQSg82nD-5r8qAE2r:-MWAQSg82nD-5r8qAE2s:b-vowihx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d4dcee033f14e7af3f882b478aab763c339819c/pkg/testutils/lint/passes/forbiddenmethod/naked_go.go#L67)):*
> ```Go
> 				}
> 			}
> 			if cc != nil && strings.Contains(cc.Text, "nolint:"+nakedGoPassName) {
> ```

This won't handle comma-separated components, but maybe that's ok.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62243)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @erikgrinaker and @knz)

___
*[pkg/testutils/lint/lint_test.go, line 2006 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62243#-MWAP92a0gQJ3klG9YwE:-MZXwqQwDa9tk_vgfgOy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d4dcee033f14e7af3f882b478aab763c339819c/pkg/testutils/lint/lint_test.go#L2006)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Escape the `.`.
</blockquote></details>

Done.
___
*[pkg/testutils/lint/passes/forbiddenmethod/naked_go.go, line 46 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62243#-MWAPsgnArqkqD27S5bH:-MZXwtq79tPXQAeE7QfX:b-nphmru) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d4dcee033f14e7af3f882b478aab763c339819c/pkg/testutils/lint/passes/forbiddenmethod/naked_go.go#L46)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

> ```
> 			// The approach here is inspired by `analysistest.check` - the
> 			// nolint comment has to be on the same line as the *end* of the
> 			// `*GoStmt`.
> ```

Hm, this is a bit unfortunate -- for inline large-body goroutines it'd be most natural to put the nolint above it. Although I suppose we won't be using a whole lot of go keywords anyway, so maybe it's ok if the ergonomics are a bit off. Happy to have an escape hatch at all!
</blockquote></details>

I'll leave as is - I agree, but also it's not easy to make these things happen and as you noted possibly not worth it.
___
*[pkg/testutils/lint/passes/forbiddenmethod/naked_go.go, line 67 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62243#-MWAQSg82nD-5r8qAE2r:-MZXx-XN0sVOMlpsIjCk:b-ypbihw) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d4dcee033f14e7af3f882b478aab763c339819c/pkg/testutils/lint/passes/forbiddenmethod/naked_go.go#L67)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

This won't handle comma-separated components, but maybe that's ok.
</blockquote></details>

It will, you just have to say `nolint:foo,nolint:bar` but also, hopefully these never need to stack and if so, I'd rather spend time fixing it when the time comes.

**Review by erikgrinaker — APPROVED** [review]
> Reviewed 3 of 7 files at r1, 2 of 5 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62243)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tbg)

**Review by knz — APPROVED** [review]
> Reviewed 3 of 5 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62243)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tbg)

___
*[pkg/testutils/lint/lint_test.go, line 2033 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62243#-MZY4oK43mi59bjyjdDe:-MZY4oK58sVfR-hEQApP:b-zfvowb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9c514c0ed92d00e1eddaa68f71c7cac73714762/pkg/testutils/lint/lint_test.go#L2033)):*
> ```Go
> 			`pkg/workload/`,
> 			`pkg/cli/systembench/`,
> 			`pkg/cmd/roachprod/`,
> ```

Feels to me like anything under `/pkg/cmd` can be ignored

**Review by tbg — COMMENTED** [review]
Thanks for the reviews! Going to shake out any remaining lint failures and merge.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62243#-:-MZYUgs_0bDnavEEJBfG:b-2k5yhs)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz)

___
*[pkg/testutils/lint/lint_test.go, line 2033 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62243#-MZY4oK43mi59bjyjdDe:-MZYNSs322ipc12oJygL:b-ewu4ml) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9c514c0ed92d00e1eddaa68f71c7cac73714762/pkg/testutils/lint/lint_test.go#L2033)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Feels to me like anything under `/pkg/cmd` can be ignored
</blockquote></details>

Maybe, but once we hang correctness guarantees of this lint I don't know if we want to take any chances. And definitely roachtest will want this hygiene too (since it needs to recover from all panics in the subtests) and that too sits fully in `cmd` right now. I'll leave as is and we can revisit.

**Review by knz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62243)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tbg)

___
*[pkg/testutils/lint/lint_test.go, line 2033 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62243#-MZY4oK43mi59bjyjdDe:-MZYW0323WcZV9UtCVAn:b-63kmvi) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9c514c0ed92d00e1eddaa68f71c7cac73714762/pkg/testutils/lint/lint_test.go#L2033)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Maybe, but once we hang correctness guarantees of this lint I don't know if we want to take any chances. And definitely roachtest will want this hygiene too (since it needs to recover from all panics in the subtests) and that too sits fully in `cmd` right now. I'll leave as is and we can revisit.
</blockquote></details>

no objection from me - my approval stands.

**Comment by tbg** [comment]
bors r=knz,erikgrinaker,jordanlewis

**Pull request merged**
