### PR TITLE
sql: implement row-level BEFORE triggers

### LINKED ISSUE #126360: sql: add support for row-level BEFORE triggers
This issue tracks adding support for row-level BEFORE triggers, which execute for each mutated row in an INSERT, UPDATE, UPSERT, or DELETE before the mutation occurs. Example:
```
CREATE TRIGGER t BEFORE INSERT ON table_1 FOR EACH ROW EXECUTE FUNCTION f();
```

Jira issue: CRDB-37296

Jira issue: CRDB-39860

### PR DESCRIPTION
**Pull request by DrewKimball**
#### sql: add basic support for executing row-level BEFORE triggers

This commit adds support for row-level BEFORE triggers, which fire on
each row before the mutation is applied to the row. The triggers are
implemented by projecting each trigger function in the input of the
mutation operator. The location of the trigger function in the query
plan is important, because triggers can observe old and new values of
the row, and even modify it. Each trigger function invocation is
surrounded by optimization barriers for this reason.

Fixes #126360

Release note (sql change): Added support for row-level BEFORE triggers.
A row-level trigger executes the trigger function for each row that is
being mutated. BEFORE triggers fire before the mutation operation.

#### sql: allow row-level BEFORE triggers to modify the row

This commit adds the logic needed for row-level BEFORE triggers to make
changes to a row that is being inserted or updated. The row is modified
via the return value of the trigger function. For example, to increment
a column, the returned expression may look like this:
```
RETURN ROW((NEW).x, (NEW).y + 10);
```

Informs #126360

Release note: None

#### sql: allow row-level BEFORE triggers to filter rows

Row-level BEFORE triggers can prevent rows from being inserted, updated,
or deleted by returning `NULL`. This commit implements this behavior by
adding a filter that checks the result of the trigger function.

Informs #126360

Release note: None

#### sql: add support for the WHEN clause in row-level BEFORE triggers

This commit adds support for the trigger WHEN clause, which determines
whether the trigger function should be executed for a given row.

Informs #126360

Release note: None

#### opt: add CREATE/DROP TRIGGER to the test catalog

This commit adds support for `CREATE TRIGGER` and `DROP TRIGGER` in the
test catalog. It also changes the ID allocation logic so that user-defined
types and routines get globally unique descriptor IDs, so that code that
relies on unique IDs works with the test catalog. Note that this is
already the case for the non-test catalog.

This commit also adds a few tests showing how row-level BEFORE triggers
are built into the plan of a mutation.

Informs: #126360

Release note: None

### CODE REVIEW

**Comment by DrewKimball** [comment]
The first commit contains the bulk of the changes (executing the trigger function for each mutated row), while the remaining ones make incremental improvements, like supporting the WHEN clause.

**Review by mgartner — CHANGES_REQUESTED** [review]
The first 4 commits looks great! I'm leaving some of the minor feedback now, and will review the last commit after lunch.

The breakdown of commits is a master class in breaking down commits in a way that makes reviewing more pleasant. Thank you for that!

> Reviewed 10 of 10 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-:-O9QFO1915hdh3WWSuVx:bszkl3u)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mw5h)

___
*[`pkg/sql/opt/optbuilder/insert.go` line 359 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-O9Pwac_ANKKiATAmd7O:-O9Pv6_g8_puB-ZrYlWn:b7e621z) ([raw file](https://github.com/cockroachdb/cockroach/blob/9284eb89263a00e516ae5a3920eeee912af3b3e8/pkg/sql/opt/optbuilder/insert.go#L359)):*
> ```Go
> 
> 		// Add a filter from the WHERE clause if one exists. This must happen after
> 		// the INSERT triggers are added.
> ```

It's not obvious to me why it must happen after the triggers are added. Would a more detailed comment be helpful here?

Thinking more about it, I'm not convinced that we should be filtering any rows with an `ON CONFLICT ... WHERE` clause. [Postgres's docs](https://www.postgresql.org/docs/current/sql-insert.html#SQL-ON-CONFLICT) on this clause are very brief and it only mentions using the `WHERE` clause to select partial, unique indexes as arbiters.

When a partial index arbiter is selected, we synthesize a filter [here](https://github.com/cockroachdb/cockroach/blob/9f61a38b670e57873509568f67bb665e50cd1935/pkg/sql/opt/optbuilder/mutation_builder_arbiter.go#L479-L490) so that the partial index can be used. So maybe this `WHERE` filter is completely redundant and we can remove it?

All that being said, it's been that way for 6+ years, and it's not something we should try to fix in this PR. I've created #132845 to track this. If you're updating this file or comment, can you add: `TODO(#132845): We may be able to remove this filter.`
___
*[`pkg/sql/opt/optbuilder/insert.go` line 463 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-O9Pszl_D5y1V9N1oKaB:-O9Pszla5kxk7BnC-Rze:brkp6ck) ([raw file](https://github.com/cockroachdb/cockroach/blob/9284eb89263a00e516ae5a3920eeee912af3b3e8/pkg/sql/opt/optbuilder/insert.go#L463)):*
> ```Go
> 		for j, m := 0, mb.tab.Trigger(i).EventCount(); j < m; j++ {
> 			eventType := mb.tab.Trigger(i).Event(j).EventType
> 			if eventType == tree.TriggerEventInsert || eventType == tree.TriggerEventUpdate {
> ```

Why do we check for an insert trigger event here? It seems like we only need existing columns for an update event, no?
___
*[`pkg/sql/opt/optbuilder/trigger.go` line 243 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-O9Q6eJ21wHU0R53yu7W:-O9Q6eJ21wHU0R53yu7X:b-fifwsk) ([raw file](https://github.com/cockroachdb/cockroach/blob/9284eb89263a00e516ae5a3920eeee912af3b3e8/pkg/sql/opt/optbuilder/trigger.go#L243)):*
> ```Go
> 	// Finally, project a column that invokes the trigger function.
> 	passThroughCols := triggerScope.colSet()
> 	colName := scopeColName("").WithMetadataName("def.Name")
> ```

nit: Is the generic `"def.Name"` metadata name here intentional?
___
*[`pkg/sql/opt/optbuilder/trigger.go` line 288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-O9Q7-wjB5BcEajb_RO0:-O9Q7-wjB5BcEajb_RO1:b-66q7ad) ([raw file](https://github.com/cockroachdb/cockroach/blob/9284eb89263a00e516ae5a3920eeee912af3b3e8/pkg/sql/opt/optbuilder/trigger.go#L288)):*
> ```Go
> 		}
> 	}
> 	return memo.ScalarListExpr{tgNew /* NEW */, tgOld, /* OLD */
> ```

optional nit: new and old on their own lines is more readable in this list, IMO.
___
*[`pkg/sql/opt/optbuilder/trigger.go` line 346 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-O9Q9dqN2BkfU_PR6GE_:-O9Q9dqN2BkfU_PR6GEa:bns96cf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2490935de9af49cdc374e38eebe181abab3c28b1/pkg/sql/opt/optbuilder/trigger.go#L346)):*
> ```Go
> 				// replacements will be resolved instead when referenced via the
> 				// special "excluded" data source.
> 				existing.clearName()
> ```

Should we be pushing a new scope instead of clearing the name here?
___
*[`pkg/sql/opt/optbuilder/trigger.go` line 296 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-O9QEOfo-JHEvzKD-GTh:-O9QEOfo-JHEvzKD-GTi:b-b1wm4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/0595f5b073e642156fb4b53acf4d1c73d56ffd71/pkg/sql/opt/optbuilder/trigger.go#L296)):*
> ```Go
> 		panic(err)
> 	}
> 	// The WHEN condition may reference OlD and NEW columns only.
> ```

nit: "OlD" => "OLD"
___
*[`pkg/sql/opt/optbuilder/trigger.go` line 300 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-O9QEalz1948mbETYOaN:-O9QEalz1948mbETYOaO:bn89v9i) ([raw file](https://github.com/cockroachdb/cockroach/blob/0595f5b073e642156fb4b53acf4d1c73d56ffd71/pkg/sql/opt/optbuilder/trigger.go#L300)):*
> ```Go
> 	if oldColID != 0 {
> 		whenScope.appendColumn(triggerScope.getColumn(oldColID))
> 		whenScope.getColumn(oldColID).name = scopeColName(triggerColOld)
> ```

It might be nice to add a `appendColumnWithName` function to avoid the lookup here. Maybe consider that in a little follow-up PR?
___
*[`pkg/ccl/logictestccl/testdata/logic_test/triggers` line 1296 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-O9Q8Wid7vt_-1bRFVNE:-O9Q8Wid7vt_-1bRFVNF:b-m12he) ([raw file](https://github.com/cockroachdb/cockroach/blob/9284eb89263a00e516ae5a3920eeee912af3b3e8/pkg/ccl/logictestccl/testdata/logic_test/triggers#L1296)):*
> ```
> # between triggers on different rows.
> statement ok
> SET vectorize=off;
> ```

We should add some tests that don't depend on the ordering so that we have some tests for triggers running in the vectorized engine. One idea is to have something like `skip-if` for vectorized/non-vectorized so that you can do `noticetrace` for non-vectorized, and then `statement ok` for vectorized and still check the results of the mutations.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/triggers` line 1394 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-O9Q7xIj8dvikoRO3apg:-O9Q7xIk21uMomweVdB-:b-ive95u) ([raw file](https://github.com/cockroachdb/cockroach/blob/9284eb89263a00e516ae5a3920eeee912af3b3e8/pkg/ccl/logictestccl/testdata/logic_test/triggers#L1394)):*
> ```
> ----
> NOTICE: INSERT: old: <NULL>, new: (1,2)
> NOTICE: UPDATE: old: (1,2), new: (1,12)
> ```

Interesting. So when there is a conflict the insert trigger still fires?
___
*[`pkg/ccl/logictestccl/testdata/logic_test/triggers` line 1547 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-O9QBAvsDl6bHJDkIKND:-O9QBAvsDl6bHJDkIKNE:b-mv2j7e) ([raw file](https://github.com/cockroachdb/cockroach/blob/2490935de9af49cdc374e38eebe181abab3c28b1/pkg/ccl/logictestccl/testdata/logic_test/triggers#L1547)):*
> ```
> # propagates to the special "excluded" data source.
> query T noticetrace
> INSERT INTO xy VALUES (1, 2), (3, 4), (5, 6) ON CONFLICT (x) DO UPDATE SET y = excluded.y;
> ```

It's hard to see where the propagation mentioned in the comment because the value isn't changing here. Can you add another cases like `... DO UPDATE SET y = excluded.y - 1`?
___
*[`pkg/ccl/logictestccl/testdata/logic_test/triggers` line 1753 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-O9QDNMY-J-3HQN8VwQk:-O9QDNMY-J-3HQN8VwQl:bprfw0q) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe67f976357de96e635bf3aecd2d788e8e5f59e0/pkg/ccl/logictestccl/testdata/logic_test/triggers#L1753)):*
> ```
> 
> query II rowsort
> SELECT * FROM nullable;
> ```

I think changing this to `SELECT *, bar ..` here and adding a `DEFAULT` for `bar` would be nice to show that the trigger does not change the value of `bar`.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/triggers` line 1791 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-O9QDt957KmJEVMgeqZy:-O9QDt964rno8uBQPkpN:b-3j8sj1) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe67f976357de96e635bf3aecd2d788e8e5f59e0/pkg/ccl/logictestccl/testdata/logic_test/triggers#L1791)):*
> True

You been writing some Python lately? :laughing:

**Review by mgartner — APPROVED** [review]
:lgtm: Fantastic work!

I'm slightly afraid to ask (in the event it complicates things), but how do before triggers interact with CHECK constraints, partial index predicates, and computed column expressions? Does it all _just work_ because these expressions are projected after the before triggers are? What happens if you try to update a computed column in a before trigger? We should probably have tests with a combination of these features, but those can be added in a future PR.

> Reviewed 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-:-O9QTA-h9NC4IS5I2Q4q:b-notfzs)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @mw5h)

___
*[`pkg/sql/opt/optbuilder/insert.go` line 359 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-O9Pwac_ANKKiATAmd7O:-O9QStNP5S4RKhiCIhtL:bn0n9rx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9284eb89263a00e516ae5a3920eeee912af3b3e8/pkg/sql/opt/optbuilder/insert.go#L359)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It's not obvious to me why it must happen after the triggers are added. Would a more detailed comment be helpful here?

Thinking more about it, I'm not convinced that we should be filtering any rows with an `ON CONFLICT ... WHERE` clause. [Postgres's docs](https://www.postgresql.org/docs/current/sql-insert.html#SQL-ON-CONFLICT) on this clause are very brief and it only mentions using the `WHERE` clause to select partial, unique indexes as arbiters.

When a partial index arbiter is selected, we synthesize a filter [here](https://github.com/cockroachdb/cockroach/blob/9f61a38b670e57873509568f67bb665e50cd1935/pkg/sql/opt/optbuilder/mutation_builder_arbiter.go#L479-L490) so that the partial index can be used. So maybe this `WHERE` filter is completely redundant and we can remove it?

All that being said, it's been that way for 6+ years, and it's not something we should try to fix in this PR. I've created #132845 to track this. If you're updating this file or comment, can you add: `TODO(#132845): We may be able to remove this filter.`
</blockquote></details>

Also, I don't think you have a test for this case - an insert/update trigger with an `INSERT .. ON CONFLICT .. WHERE` statement. We should probably have one, right?

**Review by DrewKimball — COMMENTED** [review]
TFTR!

Check constraints and partial index predicates should just work for the reason you mentioned. I'll add an item to test this to my TODO list :)

Good callout on computed columns. I think as things are, computed columns will not reflect changes made by triggers to the columns they depend on. Additionally, it will be possible to modify the value of a computed column within a trigger.

Contrast this with Postgres:
>-   Generated columns are, conceptually, updated after `BEFORE` triggers have run. Therefore, changes made to base columns in a `BEFORE` trigger will be reflected in generated columns. But conversely, it is not allowed to access generated columns in `BEFORE` triggers.

Example with direct modification of the computed column.
```
postgres=# create table t (x int primary key, y int generated always as (x * 10) stored);
CREATE TABLE
postgres=# create function f() returns trigger language plpgsql as $$ begin raise notice '%', new; new.y := -1; return new; end $$;
CREATE FUNCTION
postgres=# create trigger trig before insert on t for each row execute function f();
CREATE TRIGGER
postgres=# insert into t values (1), (2);
NOTICE:  (1,)
NOTICE:  (2,)
INSERT 0 2
postgres=# select * from t;
 x | y
---+----
 1 | 10
 2 | 20
(2 rows)
```
Example with modification of a referenced column.
```
postgres=# create function f() returns trigger language plpgsql as $$ begin raise notice '%', new; new.x := new.x + 10; return new; end $$;
CREATE FUNCTION
postgres=# create trigger trig before insert on t for each row execute function f();
CREATE TRIGGER
postgres=# insert into t values (1), (2);
NOTICE:  (1,)
NOTICE:  (2,)
INSERT 0 2
postgres=# select * from t;
 x  |  y
----+-----
 11 | 110
 12 | 120
(2 rows)
```
I'll fix that in a follow-up as well. I don't think it will complicate things too much.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-:-O9SApQ8BU2lsYn1NG9M:bulb8st)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @mw5h)

___
*[`pkg/sql/opt/optbuilder/insert.go` line 359 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-O9Pwac_ANKKiATAmd7O:-O9RWFjK9tFzqwdroozS:b-ebzwtu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9284eb89263a00e516ae5a3920eeee912af3b3e8/pkg/sql/opt/optbuilder/insert.go#L359)):*
>It's not obvious to me why it must happen after the triggers are added. Would a more detailed comment be helpful here?

This is because BEFORE INSERT triggers are called for every input row to the INSERT/UPSERT, even if the row doesn't end up being inserted into the table. I've added that to the comment.

>Thinking more about it, I'm not convinced that we should be filtering any rows with an `ON CONFLICT ... WHERE` clause. [Postgres's docs](https://www.postgresql.org/docs/current/sql-insert.html#SQL-ON-CONFLICT) on this clause are very brief and it only mentions using the `WHERE` clause to select partial, unique indexes as arbiters.

It's confusing, but this is actually handling the `WHERE` clause for the `conflict_action`, not the index arbiter for the `conflict_target`. It applies only to conflicting rows, and determines whether they will be updated or just ignored (DO NOTHING behavior, basically).

>Also, I don't think you have a test for this case - an insert/update trigger with an `INSERT .. ON CONFLICT .. WHERE` statement. We should probably have one, right?

Great point - I've added one now.
___
*[`pkg/sql/opt/optbuilder/insert.go` line 463 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-O9Pszl_D5y1V9N1oKaB:-O9Rvfdf7zWGA7s-TPq8:be0h94f) ([raw file](https://github.com/cockroachdb/cockroach/blob/9284eb89263a00e516ae5a3920eeee912af3b3e8/pkg/sql/opt/optbuilder/insert.go#L463)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Why do we check for an insert trigger event here? It seems like we only need existing columns for an update event, no?
</blockquote></details>

That's a good point... it'll slightly complicate the logic at the callsite, but it seems worth it to avoid doing extra joins. Done.
___
*[`pkg/sql/opt/optbuilder/trigger.go` line 243 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-O9Q6eJ21wHU0R53yu7W:-O9S-If29_lurCSx3H0d:b7msrt7) ([raw file](https://github.com/cockroachdb/cockroach/blob/9284eb89263a00e516ae5a3920eeee912af3b3e8/pkg/sql/opt/optbuilder/trigger.go#L243)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: Is the generic `"def.Name"` metadata name here intentional?
</blockquote></details>

Nope. I actually noticed that, but forgot to fix it...

Done.
___
*[`pkg/sql/opt/optbuilder/trigger.go` line 288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-O9Q7-wjB5BcEajb_RO0:-O9S01sh2GIKdts6Y8pL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9284eb89263a00e516ae5a3920eeee912af3b3e8/pkg/sql/opt/optbuilder/trigger.go#L288)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

optional nit: new and old on their own lines is more readable in this list, IMO.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/optbuilder/trigger.go` line 346 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-O9Q9dqN2BkfU_PR6GE_:-O9S0GR8EvmYt2fhKjw4:b-65raxr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2490935de9af49cdc374e38eebe181abab3c28b1/pkg/sql/opt/optbuilder/trigger.go#L346)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Should we be pushing a new scope instead of clearing the name here?
</blockquote></details>

I think we want to keep the previous columns in scope, but make sure that the correct one will be resolved by name. We do the same thing here: https://github.com/cockroachdb/cockroach/blob/b2e1d9a00915b6e835893120ff029592755c48ae/pkg/sql/opt/optbuilder/mutation_builder.go#L1042-L1047
___
*[`pkg/sql/opt/optbuilder/trigger.go` line 296 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-O9QEOfo-JHEvzKD-GTh:-O9S-W5t5kvFrt0qs3B6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0595f5b073e642156fb4b53acf4d1c73d56ffd71/pkg/sql/opt/optbuilder/trigger.go#L296)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: "OlD" => "OLD"
</blockquote></details>

Done.
___
*[`pkg/sql/opt/optbuilder/trigger.go` line 300 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-O9QEalz1948mbETYOaN:-O9S-etu1iBFwLjvZItv:b-chwnc9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0595f5b073e642156fb4b53acf4d1c73d56ffd71/pkg/sql/opt/optbuilder/trigger.go#L300)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It might be nice to add a `appendColumnWithName` function to avoid the lookup here. Maybe consider that in a little follow-up PR?
</blockquote></details>

Yeah that's a nice idea. I'll create a TODO-list for follow-ups.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/triggers` line 1296 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-O9Q8Wid7vt_-1bRFVNE:-O9S7848BUfJdlkv8fn6:b-mysjr0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9284eb89263a00e516ae5a3920eeee912af3b3e8/pkg/ccl/logictestccl/testdata/logic_test/triggers#L1296)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

We should add some tests that don't depend on the ordering so that we have some tests for triggers running in the vectorized engine. One idea is to have something like `skip-if` for vectorized/non-vectorized so that you can do `noticetrace` for non-vectorized, and then `statement ok` for vectorized and still check the results of the mutations.
</blockquote></details>

Another possibility would be to just have another test file for the vectorized engine, or find a way to make the vectorized engine produce the same results. I'll add this to my follow-ups list.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/triggers` line 1394 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-O9Q7xIj8dvikoRO3apg:-O9S7QKFC9z14ShWHQzs:b-fierg5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9284eb89263a00e516ae5a3920eeee912af3b3e8/pkg/ccl/logictestccl/testdata/logic_test/triggers#L1394)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Interesting. So when there is a conflict the insert trigger still fires?
</blockquote></details>

Yes, a row-level BEFORE INSERT trigger fires for every input row. Interestingly, AFTER triggers only fire for non-conflicting rows.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/triggers` line 1547 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-O9QBAvsDl6bHJDkIKND:-O9S7v8s6mMH6Pgj0tu2:b-1eh3wi) ([raw file](https://github.com/cockroachdb/cockroach/blob/2490935de9af49cdc374e38eebe181abab3c28b1/pkg/ccl/logictestccl/testdata/logic_test/triggers#L1547)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It's hard to see where the propagation mentioned in the comment because the value isn't changing here. Can you add another cases like `... DO UPDATE SET y = excluded.y - 1`?
</blockquote></details>

Sure, done.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/triggers` line 1753 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-O9QDNMY-J-3HQN8VwQk:-O9S9qAr09CbrOLc_q75:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe67f976357de96e635bf3aecd2d788e8e5f59e0/pkg/ccl/logictestccl/testdata/logic_test/triggers#L1753)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think changing this to `SELECT *, bar ..` here and adding a `DEFAULT` for `bar` would be nice to show that the trigger does not change the value of `bar`.
</blockquote></details>

Done.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/triggers` line 1791 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-O9QDt957KmJEVMgeqZy:-O9SA5bu8I5dpZnqM6iz:bjmc8b3) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe67f976357de96e635bf3aecd2d788e8e5f59e0/pkg/ccl/logictestccl/testdata/logic_test/triggers#L1791)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

> True

You been writing some Python lately? :laughing:
</blockquote></details>

:snake:

**Review by mgartner — COMMENTED** [review]
>I'll fix that in a follow-up as well. I don't think it will complicate things too much.

:+1: 

> Reviewed 11 of 16 files at r6, 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-:-O9VIcXU9Qg8hFaexMpQ:b-52uva3)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[`pkg/sql/opt/optbuilder/insert.go` line 359 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-O9Pwac_ANKKiATAmd7O:-O9VJ3O10EsWbogBPLzm:b8pu1cn) ([raw file](https://github.com/cockroachdb/cockroach/blob/9284eb89263a00e516ae5a3920eeee912af3b3e8/pkg/sql/opt/optbuilder/insert.go#L359)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

>It's not obvious to me why it must happen after the triggers are added. Would a more detailed comment be helpful here?

This is because BEFORE INSERT triggers are called for every input row to the INSERT/UPSERT, even if the row doesn't end up being inserted into the table. I've added that to the comment.

>Thinking more about it, I'm not convinced that we should be filtering any rows with an `ON CONFLICT ... WHERE` clause. [Postgres's docs](https://www.postgresql.org/docs/current/sql-insert.html#SQL-ON-CONFLICT) on this clause are very brief and it only mentions using the `WHERE` clause to select partial, unique indexes as arbiters.

It's confusing, but this is actually handling the `WHERE` clause for the `conflict_action`, not the index arbiter for the `conflict_target`. It applies only to conflicting rows, and determines whether they will be updated or just ignored (DO NOTHING behavior, basically).

>Also, I don't think you have a test for this case - an insert/update trigger with an `INSERT .. ON CONFLICT .. WHERE` statement. We should probably have one, right?

Great point - I've added one now.
</blockquote></details>

Oh wow that is subtle. The naming could probably be better. We should at least document `OnConflict.Where` better. I'll update #132845 to just be to clarify the difference between Where and ArbiterPredicate.

Thanks for adding the comment!
___
*[`pkg/sql/opt/optbuilder/insert.go` line 335 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-O9VJYWx6UbcTtYfJMwW:-O9VJYWx6UbcTtYfJMwX:bnhsqlm) ([raw file](https://github.com/cockroachdb/cockroach/blob/489d0573ff29abf2c7408b9a26348c4c65ef4b19/pkg/sql/opt/optbuilder/insert.go#L335)):*
> ```Go
> 			// NOTE: we avoid building INSERT triggers until after buildInputForUpsert
> 			// so that there are no buffering operators between INSERT and UPDATE
> 			// triggers. This helps preserve Postgres compatibility
> ```

FYI missing a period here if you want to fix it up in a follow-up PR
___
*[`pkg/sql/opt/optbuilder/trigger.go` line 346 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-O9Q9dqN2BkfU_PR6GE_:-O9VK4LEAXe_QTT4L6sU:b-h5ii65) ([raw file](https://github.com/cockroachdb/cockroach/blob/2490935de9af49cdc374e38eebe181abab3c28b1/pkg/sql/opt/optbuilder/trigger.go#L346)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I think we want to keep the previous columns in scope, but make sure that the correct one will be resolved by name. We do the same thing here: https://github.com/cockroachdb/cockroach/blob/b2e1d9a00915b6e835893120ff029592755c48ae/pkg/sql/opt/optbuilder/mutation_builder.go#L1042-L1047
</blockquote></details>

If we push a new scope on top of the previous scope, instead of replacing it, the previous columns are still in-scope, except for columns in the new scope with the same name. E.g., if the previous scope has `a, b, c` and the new scope has `b`, then `b` will resolve to the column in the new scope, and `a` and `c` will resolve to columns in the previous scope.

Maybe there's a more subtle reason why pushing a scope won't work here, but it's not obvious to me.

FWIW I think `disambiguateColumns` is a bit of a hack and relying on it has caused some problems in the past, like #104924. Over the years I've be slowly working to eliminate it, but it's been a bit tricky to iron out all the issues that it currently solves.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/triggers` line 1296 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-O9Q8Wid7vt_-1bRFVNE:-O9VMGX1EdxZEwW9Xp6m:b-nnxg2d) ([raw file](https://github.com/cockroachdb/cockroach/blob/9284eb89263a00e516ae5a3920eeee912af3b3e8/pkg/ccl/logictestccl/testdata/logic_test/triggers#L1296)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Another possibility would be to just have another test file for the vectorized engine, or find a way to make the vectorized engine produce the same results. I'll add this to my follow-ups list.
</blockquote></details>

That's a great option too.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/triggers` line 1394 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132511#-O9Q7xIj8dvikoRO3apg:-O9VMTPz9_AWW1BnflaN:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/9284eb89263a00e516ae5a3920eeee912af3b3e8/pkg/ccl/logictestccl/testdata/logic_test/triggers#L1394)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Yes, a row-level BEFORE INSERT trigger fires for every input row. Interestingly, AFTER triggers only fire for non-conflicting rows.
</blockquote></details>

:+1:

**Comment by DrewKimball** [comment]
>If we push a new scope on top of the previous scope, instead of replacing it, the previous columns are still in-scope, except for columns in the new scope with the same name. E.g., if the previous scope has a, b, c and the new scope has b, then b will resolve to the column in the new scope, and a and c will resolve to columns in the previous scope.
>
>Maybe there's a more subtle reason why pushing a scope won't work here, but it's not obvious to me.
>
>FWIW I think disambiguateColumns is a bit of a hack and relying on it has caused some problems in the past, like https://github.com/cockroachdb/cockroach/pull/104924. Over the years I've be slowly working to eliminate it, but it's been a bit tricky to iron out all the issues that it currently solves.

One difference I can think of is that `scope.makePresentation()` only looks at columns in that scope. I think there are some other methods on `scope` that are similar. Either way, I agree it seems hacky. I'll try out pushing the scope in a follow-up.

**Pull request merged**
