### PR TITLE
release-21.1: colexec: reuse buckets in the external hash aggregator

### PR DESCRIPTION
**Pull request by yuzefovich**
Backport 1/1 commits from #63731.

/cc @cockroachdb/release

---

The way external hash aggregator works is that it splits up the input
data set into partitions, and then each partition in isolation is
processed by an in-memory hash aggregator. The in-memory operator is
reset between each partition. Previously, the in-memory hash aggregator
would create new buckets on each run. This was suboptimal from the
performance perspective but also was leaky in terms of memory
accounting: whenever a new bucket is created, the memory footprint is
registered; however, we didn't shrink the memory account once the bucket
is no longer used. Such pattern could lead to the external hash
aggregator hitting the --max-sql-memory limit not because we were
actually using that much memory but because of this leaky pattern.

Now this problem is fixed by not discarding the buckets and reusing them
after the in-memory hash aggregator is reset. This allows us to continue
not shrink the memory account when a bucket is done for the current
iteration because we are keeping the reference to the bucket for the
next iteration. It also comes with the reduced allocations bringing
a minor perf benefit.

Addresses: #63619.

Release note: None (no stable release with this behavior)

### CODE REVIEW

**Comment by yuzefovich** [comment]
Thoughts on backporting this for 21.1.0? I'm kinda on the fence because it doesn't fix a GA-blocker, yet it is a low-risk fix to the new functionality.

**Comment by jordanlewis** [comment]
Let's follow the process and backport for the .1.1 release.

**Comment by yuzefovich** [comment]
Ack, will merge for 21.1.1.

**Comment by yuzefovich** [comment]
Friendly ping @jordanlewis

**Review by jordanlewis — APPROVED** [review]

**Pull request merged**
