### PR TITLE
docs: RFC for settings names and settings vs env vars

### LINKED ISSUE #15242: settings: standardize the interaction between env vars and settings
Right now we have a bit of a floating uncertainty about configuration:

1. when should a configuration knob have an env var or a cluster setting?
2. if both, in which order do we prioritize? e.g. should the env var be the default for the setting? Or override?
3. what about cmdline flags and session vars?

We need to clarify this in our docs, in our mind and throughout the code.

**We must ensure that users have a consistent experience of configuration, and not make different mechanisms for different configuration options, which would cause endless confusion and complexity in docs.** (let's - still - make data easy)

Proposal:

## A. env vars or setting?
    
Keep in mind:
- settings are cluster-wide, used for all nodes and all sessions.
- settings may not see their configured value appear until some non-deterministic delay after node startup.
- settings can change over time while a node is running, even in the middle of a session.
- settings are visible to users remotely (e.g. `show all cluster settings`), and configurable remotely by admins, whereas flags and env vars cannot.

General principles:

- env vars (or flags) for things that impact start-up (e.g. certs, `--join`)
- env vars (or flags) for things that must not (or cannot) change throughout node execution (e.g. `--port`, `--cache-size`)
- settings for thing that can be really convenient to change over time e.g. opt-out online registration
  - however (from Ben) "we only want to make settings that we reasonably expect *users* to need to change, and not to expose every knob that could be turned"

## B. if both, how to prioritize?

Say we have both an env var and a setting, what's the interaction?

Two choices: 

- env var has priority (override over the setting): this can be useful to override the setting for a specific node. For example we could have some general behavior set via the setting, and the use env var to do some local testing using a custom value on one (or several nodes) without impacting the rest of the cluster.

- setting has priority (override over the env var): conceptually this is as if the env var was the "default value" for the setting until the setting is set. This has weird semantics if the env var doesn't have the same value on every node: until the setting is set, after which it will have the same value everywhere, the nodes can observe different things.

My advice is to go for the first choice: **env var has priority over setting**: check if env var is set, and only if not set use the setting. We'd need a new `EnvOrDefaultSetting` for that.

## C. what about cmdline flags and session vars?

(or config files, if/when that happens)

1. we're already aligned with most other open source software regarding the interaction between cmd flags and env vars: env var value is default value for cmdline flag (flag can override). If/when we have config files, the order will (likely) be **env var lowest, then config file, then cmdline flag** (as is customary).

2. session vars vs cluster settings. Usually this is not difficult to decide -- either something that needs to change per session (or per user) or something global for the cluster. But sometime the question arises, for example as of this writing what do we do with the "distsql" flag? (#15045)

   **Likely pattern: session var at highest priority (session var always decides), but upon creating a new session the session var is initialized from something else, presumably the cluster setting.**

3. session vars vs env vars (when no cluster setting): same as above, set the session var upon session init with the value from the env var

4. what if we need to disable a session var value or something for testing/debugging? How to prevent clients from customizing the session default? If that need arises, then the mechanism would be to add a gate flag on session init and `set session var` (not `set cluster setting`) to prevent said session var to be configured in a specific way if some condition is met, presumably some debug knob

## D. woops the text above is inconsistent it seems?

So if you paid attention you'll see above two contradictory points, or rather something that yields an absurd situation:

- settings vs env vars, I suggested env vars override settings
- env vars vs flags/config files, I suggested flags override env vars

This would mean that flags/config files override settings; this does not sound right -- or rather, it will sound right to 50% of users and 50% will hate it.

What makes? **Proposal: avoid this dilemma entirely by being disciplined on not offering a customizable setting for things that are also customizable via cmdline flags or config files**

So we'd really have two sorts of customization knobs:
- things that have an env var and a cmdline flag / config file entry
- things that have an env var and a cluster setting
- but we'd have nothing that has both a cluster setting and a cmdline flag / config file entry

## E. The missing liink in the story

**settings: we actually need per-node customizable settings #15243**

Once we have per-node customizable settings then we can remove any remaining env var that overlaps with a setting, keeping env vars only in combination with cmdline flags.

### PR DESCRIPTION
**Pull request by knz**
Fixes #15242.

### CODE REVIEW

**Comment by dt** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[docs/tech-notes/setting_names.md, line 30 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15253#-KiGkboCefiSRidfqJLI:-KiGkboCefiSRidfqJLJ:b-t0rg6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/b92ca331aeb7668881ffc460d5b58d1334f4189d/docs/tech-notes/setting_names.md#L30)):*
> ```Markdown
> - `kv`: the top-level architecture layer in CockroachDB
> - `snapshot.recovery`: the tuning knob
> - `rate`: the type of the value
> ```

a minor nit, but I'm not sure I'd say we want to put "the type of the value" in the name -- it has a separate, explicit type already. I'd argue this is more knob names being "thing-knob-is-attached-to" and "what-knob-does", which is related but not quite the same, but the below discussion of noun vs verbs also falls out of this: you know the "what it does" part already if it is a verb, so you don't need to add another one.

$0.02.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15253)*

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[docs/tech-notes/setting_names.md, line 39 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15253#-KiMT5nXe2705dAQ2yV_:-KiMT5nXe2705dAQ2yVa:b6b6ra9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b92ca331aeb7668881ffc460d5b58d1334f4189d/docs/tech-notes/setting_names.md#L39)):*
> ```Markdown
> - `sql`: the top-level architecture layer
> - `trace`: the sub-system that's being configured (tracing)
> - `session.eventlog`, `txn`: the tuning knob / part
> ```

Should the dot between session.eventlog be a dash or other punctuation, or is the dot just a word separator? (You use `show-log.enabled` below, which seems inconsistent with this one)

Both mysql and postgres use underscores in their setting names; is there a particular reason we're using dots here? That is, do we plan to do anything with the hierarchy that the dots imply and sometimes have multiple words without a dot between them (either another separator as in `async-pan-zoom` or no separator as in `stmtstats`)

---

*[docs/tech-notes/setting_names.md, line 91 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15253#-KiMTpdNCne9we_IRZyZ:-KiMTpdNCne9we_IRZy_:b2ynbo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b92ca331aeb7668881ffc460d5b58d1334f4189d/docs/tech-notes/setting_names.md#L91)):*
> ```Markdown
> So naming should satisfy a couple high-level criteria:
> 
> - it must use words that can be shared in an audio conversation;
> ```

This goal implies some other things: minimize use of abbreviations, and separate words consistently. The use of `stmtstats` in #15252 is awkward for both of these reasons. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15253)*

**Comment by dt** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[docs/tech-notes/setting_names.md, line 39 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15253#-KiMT5nXe2705dAQ2yV_:-KiVfDcztD2EtvAV49jg:bx8ii4h) ([raw file](https://github.com/cockroachdb/cockroach/blob/b92ca331aeb7668881ffc460d5b58d1334f4189d/docs/tech-notes/setting_names.md#L39)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Should the dot between session.eventlog be a dash or other punctuation, or is the dot just a word separator? (You use `show-log.enabled` below, which seems inconsistent with this one)

Both mysql and postgres use underscores in their setting names; is there a particular reason we're using dots here? That is, do we plan to do anything with the hierarchy that the dots imply and sometimes have multiple words without a dot between them (either another separator as in `async-pan-zoom` or no separator as in `stmtstats`)
</blockquote></details>

I was using dot for hierarchy -- grouping areas together to give them their own area of the namespace, to allow later inspecting all "kv" or all "sql" settings, etc.

for word separators, i'd prefer to avoid `-` as it might look like subtraction to the parser. `_` or snakeCase could work, but i'm hesitant to use case-sensetiviety if we can avoid it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15253)*

**Comment by knz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[docs/tech-notes/setting_names.md, line 39 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15253#-KiMT5nXe2705dAQ2yV_:-KiVhcl7MoZedKRWaUa7:bdk0ycd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b92ca331aeb7668881ffc460d5b58d1334f4189d/docs/tech-notes/setting_names.md#L39)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I was using dot for hierarchy -- grouping areas together to give them their own area of the namespace, to allow later inspecting all "kv" or all "sql" settings, etc.

for word separators, i'd prefer to avoid `-` as it might look like subtraction to the parser. `_` or snakeCase could work, but i'm hesitant to use case-sensetiviety if we can avoid it.
</blockquote></details>

Gosh you're right about the dash and the parser. I also concur that case insensitivity is a good thing. So let's go for underscore. I'll update the text in a moment, but you can already go for it in #15252

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15253)*

**Comment by knz** [comment]
Moved the tech note to RFC where it belongs.

This adopts `max_rate` to replace `rate`. I'll go and scan our settings list to check if any other replacements are useful.

**Comment by arjunravinarayan** [comment]
I have a question that isn't answered in this RFC: what should we do for cluster settings that are enums? Right now we just have strings, which we can later parse, but this doesn't protect the user from setting a malformed string. For `distsql.mode` for example, we need the string to be one of `auto, always, on, off`. But if it's malformed, interpreting it as Auto by default is very unsatisfying, as its too late. We need the `set distsql.mode = offf` (sic) to fail on set time, rather than silently succeeding. For this we need enum support. Should we add that?

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15253#-:-KiVv6h_NxrPEV5QzRiP:b5sf1x1)*

**Comment by knz** [comment]
@arjunravinarayan yes enum settings seem to be a good idea. But how do you feel about a numeric enumeration for the time being? Like 0 for off, 1 for enable-auto, and 2 for enable-always?

**Comment by arjunravinarayan** [comment]
OK, I suppose that could work for now; we could explicitly say "0 = off, 1 = auto, 2 = on, 3+ = always".

**Comment by knz** [comment]
Yes, let's do that for now, and we can always add aliases later. I have some ideas for a design but that can wait for 1.1 since we will likely say that numeric values will be also be valid inputs when we have a native enum setting type.

**Comment by petermattis** [comment]
`server.debug.remote` takes the values `all`, `local` and `false`. I think it would be much less usable to use numeric values. My 2 cents.

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15253#-:-KiVwf4MnP56yzl1LiZt:b-blusow)*

**Comment by arjunravinarayan** [comment]
and what happens if I do `set cluster setting server.debug.remote = bleargh`?

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15253#-:-KiVxTJ1jv6SNjX-jZJP:bw9e9vd)*

**Comment by petermattis** [comment]
> set cluster setting server.debug.remote = bleargh

It sets that setting to `bleargh` which disables remote debugging. That seems acceptable to me.

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15253#-:-KiVxlPLCT-7wf1NyAcg:b-9pd52v)*

**Comment by arjunravinarayan** [comment]
OK fair point. The real problem is when someone loses 2 hours because they accidentally set `distsql.mode` to `awlays` (sic) and then bang their heads in frustration because its executing as if `auto`. Type safety is nice. I think the integers are almost a better solution because they force you to be careful.

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15253#-:-KiVy_COlZK1oTNAu9UF:bg3fg0j)*

**Comment by petermattis** [comment]
Seems straightforward do add an `EnumSetting` that validates the supplied strings against an allowed set. Doesn't feel 1.0-worthy, though, but perhaps someone will find the time.

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15253#-:-KiVzG6Hz0miUo_BrFCa:bacjoa5)*

**Comment by arjunravinarayan** [comment]
Yeah, that's what @knz and I just decided, and I'm doing it right now because its trivial enough and the DistSQL use case warrants it. Thanks for your input!

**Comment by knz** [comment]
new RFC merged into existing settings RFC upon request of @dt.

Enum setting suggestion integrated in text.

**Comment by dt** [comment]
:lgtm: I don't have very strong feeling about what our convention is so long as there is *a* convention.

**Comment by knz** [comment]
Ok let's go for this for now.

**Pull request merged**
