### PR TITLE
sql: cleanup exec factory mutation code

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### sql: remove bogus factory checks for RETURNING

These checks don't make much sense: first, it should be up to the
optimizer to determine the correct returning cols; second, checking
just the length would not be enough given that we can have fewer
returning columns.

Release note: None

#### sql: don't recalculate the list of returned delete columns

The exec factory code recalculates the list of columns internally
returned by the `Deleter` to figure out the correct mapping. The
`Deleter` already has these columns in `FetchCols`, which we can use
directly.

Release note: None

#### sql: minor cleanup in exec factory RETURNING code

Move the mapping function to `row` and make it use `FastIntMap`, and
make the RETURNING initialization code more clear.

Release note: None

#### sql: remove unused upserter implementations

Remove the `tableUpserter` implementations that were used by the
heuristic planner, and fold the `tableUpserterBase` into
`optTableUpserter`.

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: Nice! Lots more deleted code!

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42037#-:-LsTmcH16eaUTud7PZrG:bdd9251)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, and @RaduBerinde)

___
*[pkg/sql/opt_exec_factory.go, line 1605 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42037#-LsTk_QFBT6i3v-0jqsZ:-LsTk_QG-T0_3blGoLgD:b-r3y03v) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c36eddb41a200a5c72b3ba8c0586d9e09a77de2/pkg/sql/opt_exec_factory.go#L1605)):*
> ```Go
> 	}
> 
> 	// Determine the relational type of the generated delete node.
> ```

[nit] you deleted this line everywhere else

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42037)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @justinj, and @rytaft)

___
*[pkg/sql/opt_exec_factory.go, line 1605 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42037#-LsTk_QFBT6i3v-0jqsZ:-LsXVcpAAsw33SOXq6L8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c36eddb41a200a5c72b3ba8c0586d9e09a77de2/pkg/sql/opt_exec_factory.go#L1605)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] you deleted this line everywhere else
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 3 files at r7, 8 of 8 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42037)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @justinj)

**Pull request merged**
