### PR TITLE
vendor: bump Pebble to 4dc277f9d3a9

### PR DESCRIPTION
**Pull request by jbowens**
```
4dc277f9 crossversion: use op-count distribution with low lower bound
e1da16a7 *: Fix race in compactMarkedFilesLocked with concurrent compactions
dd12a228 vfs: default to Unix semantics in MemFS
caa5fcde db: adaptive size-based rollover logic for manifest
e3a60a87 sstable: fix twoLevelIterator SeekGE optimization
181258e4 db: integrate elastic cpu granter with pebble
f34af25a .github: renable crossversion metamorphic CI action
```

Epic: None
Release note: None

### CODE REVIEW

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90791#-:-NFPpe5H1W5ZUdR97o1e:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90791)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal)

___
*[`pkg/server/config.go` line 702 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90791#-NFPsafd25KxrWT3Pk44:-NFPsafd25KxrWT3Pk45:b-z4jdsv) ([raw file](https://github.com/cockroachdb/cockroach/blob/9897efac2d0b18b5921028ac450e0929df16cb5b/pkg/server/config.go#L702)):*
> ```Go
> 			pebbleConfig.Opts.Experimental.CPUWorkPermissionGranter = &cpuWorkPermissionGranter{
> 				cfg.SoftSlotGranter,
> 			}
> ```

@bananabrick — I ran into the backwards incompatible interface change when bumping the Pebble version. Are we able to disable CPU work granting altogether until we adjust for the new interface, or are there tests that depend on elastic CPU work?

**Comment by jbowens** [comment]
tftr!

bors r=itsbilal

**Comment by jbowens** [comment]
bors retry

**Pull request merged**
