### PR TITLE
storage: move ReplicaCorruption to Store

### PR DESCRIPTION
**Pull request by tbg**
Also lets a lot of test senders go through Store (which was
prompted by TestReplicaCorruption).

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9633)

### CODE REVIEW

**Comment by tschottdorf** [comment]
This is a low-priority PR.

**Comment by bdarnell** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/store.go, line 2329 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9633#-KSu6XbP9vM5NltNGgtK:-KSu6XbP9vM5NltNGgtL:bj6pgkk) ([raw file](https://github.com/cockroachdb/cockroach/blob/47098dfe3c493b046554ec7775215afc931d15f7/storage/store.go#L2329)):*
> ```Go
> }
> 
> // maybeSetCorrupt is a stand-in for proper handling of failing replicas. Such a
> ```

This comment could use an update; it may not be perfect but it's not really a stand-in any more. 

---

*[storage/store.go, line 2804 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9633#-KSu6I5CT9zIwc6X2oHl:-KSu6I5DGSDrL9yPR5UQ:b-coh102) ([raw file](https://github.com/cockroachdb/cockroach/blob/47098dfe3c493b046554ec7775215afc931d15f7/storage/store.go#L2804)):*
> ```Go
> 	}
> 
> 	s.maybeSetCorrupt(s.Ctx(), r, func() error {
> ```

`maybeSetCorrupt` silently ignores errors that are not ReplicaCorruptionError, which doesn't seem right here. Any error here is unexpected and needs to either turn into a panic or mark the replica corrupt. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9633)*

**Comment by tschottdorf** [comment]
Review status: 2 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/store.go, line 2329 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9633#-KSu6XbP9vM5NltNGgtK:-KTjVP-L54OX0awJAcAK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/47098dfe3c493b046554ec7775215afc931d15f7/storage/store.go#L2329)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> This comment could use an update; it may not be perfect but it's not really a stand-in any more. 
</details>
Done.

---

*[storage/store.go, line 2804 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9633#-KSu6I5CT9zIwc6X2oHl:-KTjVNe4zztv8GsZxfk7:b-l0q03n) ([raw file](https://github.com/cockroachdb/cockroach/blob/47098dfe3c493b046554ec7775215afc931d15f7/storage/store.go#L2804)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> `maybeSetCorrupt` silently ignores errors that are not ReplicaCorruptionError, which doesn't seem right here. Any error here is unexpected and needs to either turn into a panic or mark the replica corrupt. 
</details>
Done. Note that this means that I have to handle corrupted replicas in this path (easy, just return if it's marked as corrupted already).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9633)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9633#-:-KTmr8ffd4scyHKm6HKE:bnfp4nl)*

**Comment by tschottdorf** [comment]
Abandoning this for now.

**Pull request closed without merging**
