### PR TITLE
config: remove dependency from config to catalog/tabledesc

### PR DESCRIPTION
**Pull request by Xiang-Gu**
Previously, package pkg/config depends on pkg/sql/catalog/tabledesc
directly and via systemschema. Such dependencies were created to only
create some empty/simple descriptors.

This is not desirable because `config` is a low-level package that ought not
to depend on `sql`. This PR fixes it and further and BUILD rules to disallow 
alike dependencies.

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
I did some digging and I think that all of this logic can now be deleted. It is no longer in use. Give me a couple of minutes to poke around.

**Review by ajwerner — APPROVED** [review]
I took a stab at deleting all of this code, but it's a pain. I'll wait on https://github.com/cockroachdb/cockroach/pull/82281. 

This :lgtm: for now. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82848#-:-N4UMnbg47iSfM5-ehFX:bttd1b7)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by Xiang-Gu** [comment]
TFTR

bors r+

**Comment by postamar** [comment]
Perhaps this needs to be rebased? Not sure why this change would cause the kinds of test failures we're seeing in CI runs.

**Pull request merged**
