### PR TITLE
sql: add percent complete estimate to SHOW QUERIES

### PR DESCRIPTION
**Pull request by dt**
This change adds an estimate of a query execution's progress to the SHOW
QUERIES output, based on the optimizer's estimates of the number of rows
that the query will need to scan compared to how many it has scanned so
far.

This is done in four steps:
  1) Roll up the optimizer's estimates of the rows scanned by each scan
     node to a total for the whole physical plan.
  2) Emit incremental RowsRead producer meta during scans -- every 5k rows --
     instead of all-at-once when the scan completes.
  3) Plumb the expected total from (1) to DistSQLRowReciever, so that as
     it receives said incremental updates from (2), it can track the
     fraction of the overall rows the flow expects to scan that are
     complete -- i.e. a rough approximation of progress of executing the
     query.
 4) Add write that fraction (via an atomic) to the `queryMeta` in `ActiveQueries` so it can be collected and surfaced in `SHOW QUERIES`

Large scans, for example those used in validating CHECK and FOREIGN KEY
constraints or in running EXPORT, are frequently cited as completely
opaque to users -- they have no idea, after waiting for it for 5
minutes, if it is nearly done or if it will be running for another 10
hours (and accordingly if they should wait for it, cancel it, etc).

Note that this is a rough estimate: this is obviously the case as it is
based on an estimate of total rows scanned, but also because it is using
only rows scanned as a proxy for overall progress, but that may not be
accurate for all plans (consider a large, disk-buffered sort or
aggregation after a scan). Future work could likely attempt to
instrument additional nodes in the flow to improve the accuracy of this
estimate, but hopefully this initial implementation will still provide
some visibility into the progress of long-running, large queries (even
just knowing that they have finished reading seems useful).

Release note (sql change): add a rough estimation of execution progress to SHOW QUERIES.

### CODE REVIEW

**Comment by dt** [comment]
Was hoping to wrap this all up in a free-friday project but couldn't quite figure out how best to test it, other than by hand. In bulk-io we've struggled with similar -- we can test the progress of jobs in individual components with unit tests, or end-to-end with _heavy_ use of mocking/knobs, but it's hard to deterministically test the real thing. 

My inclination is that this probably isn't worth the fuss / mess of significant mocking/knobs for an automated end-to-end test and I should just unit-test the behavior in tableReader and DistSQLRowReciever, but I wanted to float this first to see if there are other suggestions.

**Comment by awoods187** [comment]
This is such a cool idea!

**Review by yuzefovich — CHANGES_REQUESTED** [review]
This is awesome!

I left some comments, but in regards to testing - I dunno. Maybe we could craft a long-running query the runtime of which we don't expect to change much (unless the underlying storage engine is replaced), measure how long it takes manually, and then check that the progress roughly follows what we expect.

> Reviewed 4 of 4 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42518#-:-LtlWvwtEeB7uADjFqwr:b-1p5xom)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @dt)

___
*[pkg/sql/conn_executor.go, line 2168 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42518#-LtlZmQS2nLdqV5rltO1:-LtlZmQS2nLdqV5rltO2:b5zk4xv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff5c1f2c3e66cf1f898f56f1eb0418d93db9020c/pkg/sql/conn_executor.go#L2168)):*
> ```Go
> 			IsDistributed: query.isDistributed,
> 			Phase:         (serverpb.ActiveQuery_Phase)(query.phase),
> 			Progress:      float32(progress),
> ```

Why is this `float32`?
___
*[pkg/sql/physicalplan/physical_plan.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42518#-LtlXXyV2YmwMYbjuRuI:-LtlXXyV2YmwMYbjuRuJ:b-parv5c) ([raw file](https://github.com/cockroachdb/cockroach/blob/c042998218aadaef0ecf4dd39f0974d03dce3628/pkg/sql/physicalplan/physical_plan.go#L129)):*
> ```Go
> 	// whether to use the vectorized execution engine.
> 	MaxEstimatedRowCount uint64
> 	// TotalEstimatedScannedRows is the sum of the row count estimate of the all
> ```

[nit]: too many `the` in "the all the table".
___
*[pkg/sql/physicalplan/physical_plan.go, line 898 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42518#-LtlXvp64TlZpKviHy_2:-LtlXvp64TlZpKviHy_3:b-4bhf7a) ([raw file](https://github.com/cockroachdb/cockroach/blob/c042998218aadaef0ecf4dd39f0974d03dce3628/pkg/sql/physicalplan/physical_plan.go#L898)):*
> ```Go
> 
> 	mergedPlan.TotalEstimatedScannedRows = left.TotalEstimatedScannedRows + right.TotalEstimatedScannedRows
> 	mergedPlan.MaxEstimatedRowCount = left.MaxEstimatedRowCount + right.MaxEstimatedRowCount
> ```

Do you need this change for this PR? The (current) definition of `MaxEstimatedRowCount` is the maximum expected size of a *single* scan, and adding the estimates for two sides of the plan deviates from it.
___
*[pkg/sql/rowexec/tablereader.go, line 203 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42518#-LtlZAnaEAhuPImf1Gu_:-LtlZAnaEAhuPImf1Gua:b-c5pj0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff5c1f2c3e66cf1f898f56f1eb0418d93db9020c/pkg/sql/rowexec/tablereader.go#L203)):*
> ```Go
> 			meta.Metrics = execinfrapb.GetMetricsMeta()
> 			meta.Metrics.RowsRead = tr.rowsRead
> 			tr.rowsRead = 0
> ```

I don't think that we should be resetting the number of rows read. It is used in `generateMeta` to report the total number of rows read by this `tableReader`.  Since `rowsRead` is incremented by 1, you could use the modulus in the condition to decide when to emit a progress update.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42518)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/conn_executor.go, line 2168 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42518#-LtlZmQS2nLdqV5rltO1:-LtpKn-d0V7fSwX6i0lM:b-g8sj2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff5c1f2c3e66cf1f898f56f1eb0418d93db9020c/pkg/sql/conn_executor.go#L2168)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Why is this `float32`?
</blockquote></details>

proto "float" becomes a float32 in Go. I guess I _could_ use a `double` in the proto / RPC? I dunno, didn't seem worth it for something that is only going to be rendered to 3rd decimal place.
___
*[pkg/sql/physicalplan/physical_plan.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42518#-LtlXXyV2YmwMYbjuRuI:-LtpJn5N76AsFyx_7ENP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c042998218aadaef0ecf4dd39f0974d03dce3628/pkg/sql/physicalplan/physical_plan.go#L129)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: too many `the` in "the all the table".
</blockquote></details>

Done.
___
*[pkg/sql/physicalplan/physical_plan.go, line 898 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42518#-LtlXvp64TlZpKviHy_2:-LtpJMdu8yzM0snnwJ3J:bswxl0q) ([raw file](https://github.com/cockroachdb/cockroach/blob/c042998218aadaef0ecf4dd39f0974d03dce3628/pkg/sql/physicalplan/physical_plan.go#L898)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Do you need this change for this PR? The (current) definition of `MaxEstimatedRowCount` is the maximum expected size of a *single* scan, and adding the estimates for two sides of the plan deviates from it.
</blockquote></details>

Oh, whoops, yeah, sum isn't the right aggregation here -- it should be max. Done.

Also, no, I don't need it at all -- it is just for completeness: it _felt_ like something a caller could reasonably expect MergePlan to do.

Left a comment to this effect.
___
*[pkg/sql/rowexec/tablereader.go, line 203 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42518#-LtlZAnaEAhuPImf1Gu_:-LtpFYjF-L3KyEKJGq09:b-58lq7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff5c1f2c3e66cf1f898f56f1eb0418d93db9020c/pkg/sql/rowexec/tablereader.go#L203)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I don't think that we should be resetting the number of rows read. It is used in `generateMeta` to report the total number of rows read by this `tableReader`.  Since `rowsRead` is incremented by 1, you could use the modulus in the condition to decide when to emit a progress update.
</blockquote></details>

I actually switched started with that, and switched to resetting the local counter and emitting deltas  specifically _because of_ `generateMeta` and how we aggregate the partial sums in the receiver.

Conceptually, this this is just emitting the same info _as we go_ instead of all at the end, but we want the total of emitted `RowsRead` metas to add up tot the same number, regardless if it was emitted all at once of in little pieces. Indeed, the aggression of the Meta that is done in RowReceiver is unchanged. If we naively simply emitted 5k without resetting the local counter, we'd in fact then re-emit the all the same rows at the end (since we already emitted them as we go) and end up over-counting by roughly 2x.

You _could_ argue for leaving the lump-sum meta emitted at the end alone (i.e. emitting the sum total) and introducing a new steam of meta for the partial sums that are emitted as we go... but the the fact that we can have many readers means that the "lump-sum" is actually _already_ partial sums and since readers can close at different times, they were also already emitted as we go. So functionally, emitting partial sums that are slightly more partial, and emitted slightly sooner, doesn't change that model -- it is still a stream of metas that add up to the total rows scanned across all readers.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r3, 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42518#-:-Ltzb_700Ak2z1H1gmci:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @dt, and @yuzefovich)

___
*[pkg/sql/conn_executor.go, line 2168 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42518#-LtlZmQS2nLdqV5rltO1:-LtzaYcQ8ZcZmfAtdow_:b-y0rp88) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff5c1f2c3e66cf1f898f56f1eb0418d93db9020c/pkg/sql/conn_executor.go#L2168)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

proto "float" becomes a float32 in Go. I guess I _could_ use a `double` in the proto / RPC? I dunno, didn't seem worth it for something that is only going to be rendered to 3rd decimal place.
</blockquote></details>

Forgot about `float -> float32` translation, never mind.
___
*[pkg/sql/physicalplan/physical_plan.go, line 898 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42518#-LtlXvp64TlZpKviHy_2:-LtzaR1f2O3d7PcVPdJY:bsqt64m) ([raw file](https://github.com/cockroachdb/cockroach/blob/c042998218aadaef0ecf4dd39f0974d03dce3628/pkg/sql/physicalplan/physical_plan.go#L898)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Oh, whoops, yeah, sum isn't the right aggregation here -- it should be max. Done.

Also, no, I don't need it at all -- it is just for completeness: it _felt_ like something a caller could reasonably expect MergePlan to do.

Left a comment to this effect.
</blockquote></details>

Ok, makes sense, thanks!
___
*[pkg/sql/rowexec/tablereader.go, line 203 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42518#-LtlZAnaEAhuPImf1Gu_:-LtzbJLl8w_pknKRop-y:b-1m8oyh) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff5c1f2c3e66cf1f898f56f1eb0418d93db9020c/pkg/sql/rowexec/tablereader.go#L203)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I actually switched started with that, and switched to resetting the local counter and emitting deltas  specifically _because of_ `generateMeta` and how we aggregate the partial sums in the receiver.

Conceptually, this this is just emitting the same info _as we go_ instead of all at the end, but we want the total of emitted `RowsRead` metas to add up tot the same number, regardless if it was emitted all at once of in little pieces. Indeed, the aggression of the Meta that is done in RowReceiver is unchanged. If we naively simply emitted 5k without resetting the local counter, we'd in fact then re-emit the all the same rows at the end (since we already emitted them as we go) and end up over-counting by roughly 2x.

You _could_ argue for leaving the lump-sum meta emitted at the end alone (i.e. emitting the sum total) and introducing a new steam of meta for the partial sums that are emitted as we go... but the the fact that we can have many readers means that the "lump-sum" is actually _already_ partial sums and since readers can close at different times, they were also already emitted as we go. So functionally, emitting slightly more partial sums slightly sooner doesn't change the model -- there's a stream of metas that add up to total rows scanned across all readers.
</blockquote></details>

I see it now, thanks for the explanation!

**Review by asubiotto — APPROVED** [review]
:lgtm: re testing it's unclear what we can really do at an integration level, but maybe we could put a callback as a testing knob in `execinfra.TestingKnobs` that is updated with progress as well. We could try to figure out some way to inject the actual row count for some query (selecting from a table created with `generate_series`) and assert that 1) progress is always increasing and 2) progress finishes at 100% for this case/total number of rows == what we injected? This wouldn't test actually displaying the progress in `SHOW QUERIES` but would test a large part of the underlying infrastructure. I'm thinking the test would be one of our "unit" tests that starts a server with a given configuration for which we use a driver to communicate with.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42518#-:-Lu-QRXY923RXbuL96NP:bjk8pfp)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @asubiotto, @dt, and @yuzefovich)

**Comment by dt** [comment]
Came up with a way to test this by stalling the KV scans using a store filter once I'd seen some fraction of them for a big scan, and it seems to work. Added a test that takes that approach and this is now ready for another look!

**Review by yuzefovich — APPROVED** [review]
Nice! :lgtm:

> Reviewed 2 of 10 files at r5, 9 of 9 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42518#-:-M-BP6n6A-vnO1PDgqnx:be8rotp)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @dt and @yuzefovich)

___
*[pkg/sql/conn_executor_test.go, line 482 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42518#-M-BMH9wBze-XjFzVnaO:-M-BMH9wBze-XjFzVnaP:b-t4mkso) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a9e239581b0004348c001a517981256305996a6/pkg/sql/conn_executor_test.go#L482)):*
> ```Go
> 	// requests issued to the test table and then, on the `stallAfterScans`
> 	// request will stall so the test can inspect the query progress. The filter
> 	// signals the test that it has reached the stall point by closign `stalled`
> ```

`s/closign/closing/g`.
___
*[pkg/sql/conn_executor_test.go, line 548 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42518#-M-BOyi76hgp3y65L804:-M-BOyi76hgp3y65L805:bve7r5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a9e239581b0004348c001a517981256305996a6/pkg/sql/conn_executor_test.go#L548)):*
> ```Go
> 		t.Fatal(err)
> 	}
> 	require.Regexp(t, `executing \([5,6,7]\d\.`, progress)
> ```

[nit]:  I don't think we need commas in the regex.

**Review by dt — COMMENTED** [review]
TFTRs! 

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42518#-:-M-C_JS64rYcNCdjYqAV:b-oe2moi)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @dt and @yuzefovich)

___
*[pkg/sql/conn_executor_test.go, line 482 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42518#-M-BMH9wBze-XjFzVnaO:-M-BZNFYBOIfFmeOxAof:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a9e239581b0004348c001a517981256305996a6/pkg/sql/conn_executor_test.go#L482)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

`s/closign/closing/g`.
</blockquote></details>

Done.
___
*[pkg/sql/conn_executor_test.go, line 548 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42518#-M-BOyi76hgp3y65L804:-M-BZNiaAWi4gOUrWB0Y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a9e239581b0004348c001a517981256305996a6/pkg/sql/conn_executor_test.go#L548)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]:  I don't think we need commas in the regex.
</blockquote></details>

Done.

**Pull request merged**
