### PR TITLE
sql: prevent dropping roles with synthetic privileges

### PR DESCRIPTION
**Pull request by RichardJCai**
Followup work to be done to support DROP OWNED BY and
REASSIGN OWNED BY here.

Release justification: Bug fix to newly introduced feature
Release note: None

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86499)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[`pkg/sql/drop_role.go` line 583 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86499#-N9wqI1L1EdbNZIzhZVm:-N9wqI1L1EdbNZIzhZVn:b-u0fxun) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eabad140701ba53e4aaa4cdeb7f7a9163c0cbb2/pkg/sql/drop_role.go#L583)):*
> ```Go
> 		names[i] = username.Normalized()
> 	}
> 	rows, err := p.QueryIteratorEx(ctx, `drop-role-get-system-privileges`, sessiondata.NodeUserSessionDataOverride,
> ```

should this go through the cache instead of querying the table?
___
*[`pkg/sql/drop_role.go` line 587 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86499#-N9wpaGo1xuXXGuwSARZ:-N9wpaGpA85haCg0OJME:bfck2gu) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eabad140701ba53e4aaa4cdeb7f7a9163c0cbb2/pkg/sql/drop_role.go#L587)):*
> ```Go
> 	if err != nil {
> 		return err
> 	}
> ```

need to add:
```
defer func() { retErr = errors.CombineErrors(retErr, rows.Close()) }()
```

(and make the return parameter be named)
___
*[`pkg/sql/drop_role.go` line 607 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86499#-N9wofGZ3srzmVpF_wUa:-N9wofGbEiZV3b4qrhzq:b-d4ncuj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eabad140701ba53e4aaa4cdeb7f7a9163c0cbb2/pkg/sql/drop_role.go#L607)):*
> ```Go
> 			privilegeObjectFormatter.FormatName(fmt.Sprintf("%s %s", obj.GetObjectType(), obj.GetName()))
> 		} else {
> 			privilegeObjectFormatter.FormatName(string(obj.GetObjectType()))
> ```

i don't think `FormatName` should be used for the ObjectType. maybe use:
```
privilegeObjectFormatter.WriteString(string(obj.GetObjectType()))
if obj.GetName() != "" {
  privilegeObjectFormatter.WriteString(" ")
  privilegeObjectFormatter.FormatNode(obj.GetName())
}
```
___
*[`pkg/sql/logictest/testdata/logic_test/synthetic_privileges` line 256 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86499#-N9wqd8W6ZMCXQyjnd8Z:-N9wqd8W6ZMCXQyjnd8_:b-p7n1hq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eabad140701ba53e4aaa4cdeb7f7a9163c0cbb2/pkg/sql/logictest/testdata/logic_test/synthetic_privileges#L256)):*
> ```
> GRANT USAGE ON EXTERNAL CONNECTION foo TO testuser
> 
> statement error pq: cannot drop role/user testuser: grants still exist on "external_connection foo", global, "virtual_table crdb_internal.tables"
> ```

the "global" here in this error message is a little confusing
___
*[`pkg/sql/logictest/testdata/logic_test/synthetic_privileges` line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86499#-N9wqVLbCZHFT2fNGHc6:-N9wqVLc45XR-pONf2gC:b-ls3wnb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eabad140701ba53e4aaa4cdeb7f7a9163c0cbb2/pkg/sql/logictest/testdata/logic_test/synthetic_privileges#L257)):*
> ```
> 
> statement error pq: cannot drop role/user testuser: grants still exist on "external_connection foo", global, "virtual_table crdb_internal.tables"
> DROP USER testuser
> ```

it looks like we should also test that if there are default privileges then the user can't be dropped

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86499)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/drop_role.go` line 583 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86499#-N9wqI1L1EdbNZIzhZVm:-NA5pnRm-gGqcDJTa5Jq:bs9tjc2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eabad140701ba53e4aaa4cdeb7f7a9163c0cbb2/pkg/sql/drop_role.go#L583)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should this go through the cache instead of querying the table?
</blockquote></details>

Yeah, don't have cache yet, I'll need to add an interface to get synthetic privileges.
___
*[`pkg/sql/drop_role.go` line 587 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86499#-N9wpaGo1xuXXGuwSARZ:-NA5q8BD7-ojSKFTyzrX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eabad140701ba53e4aaa4cdeb7f7a9163c0cbb2/pkg/sql/drop_role.go#L587)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

need to add:
```
defer func() { retErr = errors.CombineErrors(retErr, rows.Close()) }()
```

(and make the return parameter be named)
</blockquote></details>

Done.
___
*[`pkg/sql/drop_role.go` line 607 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86499#-N9wofGZ3srzmVpF_wUa:-NA5qOjo9-vOw5qUEFiG:b52xwaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eabad140701ba53e4aaa4cdeb7f7a9163c0cbb2/pkg/sql/drop_role.go#L607)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i don't think `FormatName` should be used for the ObjectType. maybe use:
```
privilegeObjectFormatter.WriteString(string(obj.GetObjectType()))
if obj.GetName() != "" {
  privilegeObjectFormatter.WriteString(" ")
  privilegeObjectFormatter.FormatNode(obj.GetName())
}
```
</blockquote></details>

`obj.GetName` returns a string so `FormatNode` won't work, updated to just use another writestring
___
*[`pkg/sql/logictest/testdata/logic_test/synthetic_privileges` line 256 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86499#-N9wqd8W6ZMCXQyjnd8Z:-NA5tNY49zXnlybF1VaW:bp9nwp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eabad140701ba53e4aaa4cdeb7f7a9163c0cbb2/pkg/sql/logictest/testdata/logic_test/synthetic_privileges#L256)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

the "global" here in this error message is a little confusing
</blockquote></details>

I've updated it to be more explicit
___
*[`pkg/sql/logictest/testdata/logic_test/synthetic_privileges` line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86499#-N9wqVLbCZHFT2fNGHc6:-NA5qhd08Bgy250OahDv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eabad140701ba53e4aaa4cdeb7f7a9163c0cbb2/pkg/sql/logictest/testdata/logic_test/synthetic_privileges#L257)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it looks like we should also test that if there are default privileges then the user can't be dropped
</blockquote></details>

Done.

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86499)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/drop_role.go` line 583 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86499#-N9wqI1L1EdbNZIzhZVm:-NA6-7aJ8jXfSoTuIFQm:b-injj3r) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eabad140701ba53e4aaa4cdeb7f7a9163c0cbb2/pkg/sql/drop_role.go#L583)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Yeah, don't have cache yet, I'll need to add an interface to get synthetic privileges.
</blockquote></details>

Wait sorry I did add the cache, still need to add an interface for cases like this though

**Review by rafiss — APPROVED** [review]
lgtm with one more nit if you agree with it

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86499#-:-NAGvvQa9T-OWuNErCNd:bqurnki)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[`pkg/sql/drop_role.go` line 607 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86499#-N9wofGZ3srzmVpF_wUa:-NAGveMa1Xtp-aDkH3nO:bn4larx) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eabad140701ba53e4aaa4cdeb7f7a9163c0cbb2/pkg/sql/drop_role.go#L607)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

`obj.GetName` returns a string so `FormatNode` won't work, updated to just use another writestring
</blockquote></details>

what about this
```
privilegeObjectFormatter.WriteString(string(obj.GetObjectType()))
if obj.GetName() != "" {
  privilegeObjectFormatter.WriteString(" ")
  privilegeObjectFormatter.FormatName(obj.GetName())
}
```

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86499)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/drop_role.go` line 607 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86499#-N9wofGZ3srzmVpF_wUa:-NAGxeIg3hxylPu302jr:b-be3f5d) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eabad140701ba53e4aaa4cdeb7f7a9163c0cbb2/pkg/sql/drop_role.go#L607)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

what about this
```
privilegeObjectFormatter.WriteString(string(obj.GetObjectType()))
if obj.GetName() != "" {
  privilegeObjectFormatter.WriteString(" ")
  privilegeObjectFormatter.FormatName(obj.GetName())
}
```
</blockquote></details>

Good call, should probably do this anyway, if for whatever reason we have to redact the error message (don't think this ever happens right now) then this would be correct.

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86499)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msbutler, @rafiss, and @RichardJCai)

___
*[`pkg/sql/drop_role.go` line 607 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86499#-N9wofGZ3srzmVpF_wUa:-NAGzVpVAJp5Tb3f7844:botauc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eabad140701ba53e4aaa4cdeb7f7a9163c0cbb2/pkg/sql/drop_role.go#L607)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Good call, should probably do this anyway, if for whatever reason we have to redact the error message (don't think this ever happens right now) then this would be correct.
</blockquote></details>

we are redacting the error message to use in telemetry logs now: https://github.com/cockroachdb/cockroach/pull/83807

**Comment by RichardJCai** [comment]
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86499)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msbutler, @rafiss, and @RichardJCai)
> 
> _[`pkg/sql/drop_role.go` line 607 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86499#-N9wofGZ3srzmVpF_wUa:-NAGzVpVAJp5Tb3f7844:botauc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eabad140701ba53e4aaa4cdeb7f7a9163c0cbb2/pkg/sql/drop_role.go#L607)):_
> 
> Previously, RichardJCai (Richard Cai) wrote…
> we are redacting the error message to use in telemetry logs now: #83807

Ah even more valid then

Also first commit is from: https://github.com/cockroachdb/cockroach/pull/86823
Gonna wait for that to merge.

**Comment by RichardJCai** [comment]
Thanks for reviewing!

bors r=rafiss

**Pull request merged**
