### PR TITLE
kvserver: move allocator logic out of replicate queue

### PR DESCRIPTION
**Pull request by kvoli**
The 2nd commit introduces any material changes. The 3rd commit wholesale
copies over code from the replicate queue into a new pkg, without any
changes.

The replicate queue processes replicas that require replication changes,
including recovery and rebalancing. Previously, a lot of the logic
associated with these replication changes existed within replicate
queue, as well as the allocator. This is not ideal as it confuses the
line between decision logic and application - making testing and
simulation much more difficult than necessary.

This patch introduces the `ReplicationPlanner`. The previous decision
logic that existed in the replicate queue is wholesale moved into the
`ReplicationPlanner`, with no behavior changes. The `AllocatorReplica`
interface is also introduced, to enable mocking a replica in testing and
simulation.

Part of https://github.com/cockroachdb/cockroach/issues/90141

Release note: None

### CODE REVIEW

**Comment by kvoli** [comment]
This should be good to look at @AlexTalks .

**Review by AlexTalks — APPROVED** [review]
:lgtm:
In general, this looks good and very beneficial to me.

The one thing I'd mention is that with some of the new flow, maybe it would be good to write in a comment in the replicate queue a bit of documentation about the flow of replicas?  I.e. something describing

```
(1) rq.shouldQueue(..) determines if should add to queue during replica scanning
(2) rq.process(..) called in queue processing
(3) rq.processOneChange(..) called by (2)
(4) rq.preProcessCheck(..) called by (3)
(5) planner.PlanOneChange(..) called by (3), uses allocator to determine replication changes
(6) rq.applyChange(..) called by (3), actually performs snapshot and replication changes
```

This is perhaps not a great example of documentation, and there are a bunch of comments in `processOneChange(..)` already annotating flow, but it may be a suggestion to help a newcomer (or a revisitor) to this code understand the flow a bit better.  Maybe even a breakdown of phases - "should" check, preprocess, planning (using allocator), application - would be helpful.

Also a note, we should actually handle the benign errors properly, as I found out recently in https://github.com/cockroachdb/cockroach/issues/102225.  I have a small PR I'm putting up shortly to handle these in the replicate queue.

> Reviewed 5 of 9 files at r1, 22 of 22 files at r4, 14 of 14 files at r5, 16 of 17 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99247#-:-NU7zDAh1S9nVpMdaoxj:b-p7mu3m)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/replica.go` line 2311 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/99247#-NU7xyyb1pNxS02c2mE_:-NU7xyyb1pNxS02c2mEa:b831wkv) ([raw file](https://github.com/cockroachdb/cockroach/blob/640eda9336f2bfb8cd2b470fdb33b9e6ad8c1676/pkg/kv/kvserver/replica.go#L2311)):*
> ```Go
> // usage information matches. Which is dubious in some cases but often
> // reasonable when we only consider the leaseholder.
> func (r *Replica) RangeUsageInfo() allocator.RangeUsageInfo {
> ```

Question: can this be called on any replica or just a leaseholder replica?  It seems like it can be called on any, but the only the leaseholder's values are the ones typically cared about?

**Review by kvoli — COMMENTED** [review]
Thanks for the review. There are some merge conflicts which I need to resolve. I'll add a description on thr flow.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99247#-:-NUCUbsq3fppEjpGjVFN:bizmvca)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @AlexTalks)

___
*[`pkg/kv/kvserver/replica.go` line 2311 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/99247#-NU7xyyb1pNxS02c2mE_:-NUCUOfJ9eythoc4bYJr:bfkh7fl) ([raw file](https://github.com/cockroachdb/cockroach/blob/640eda9336f2bfb8cd2b470fdb33b9e6ad8c1676/pkg/kv/kvserver/replica.go#L2311)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

Question: can this be called on any replica or just a leaseholder replica?  It seems like it can be called on any, but the only the leaseholder's values are the ones typically cared about?
</blockquote></details>

On any. Only the leaseholders values are used by the replicate queue.

**Comment by kvoli** [comment]
Added the suggested comment and rebased on master to resolve conflicts. ptal @AlexTalks.

**Pull request merged**
