### PR TITLE
sql: improve env collection in stmt bundles

### LINKED ISSUE #119786: stmtbundle: handle multi-line cluster setting values in recreate
When attempting to recreate a bundle from [here](https://github.com/cockroachlabs/support/issues/2846#issue-2161547699), we get a syntax error because the cluster setting `sql.log.user_audit` has non-default value that is multi-line. We should handle such cases gracefully.

A related improvement is to handle non-default session variables like `SET timezone = Etc/UTC` correctly too (currently missing quotes).

Jira issue: CRDB-36314

### LINKED ISSUE #123830: sql: include all non-default session variables into stmt bundle
We currently include a hard-coded list that we often forget to update - we should just include all session variables that have non-default values.

Jira issue: CRDB-38564

### PR DESCRIPTION
**Pull request by yuzefovich**
This PR improves stmt bundle collection to include all session variables and cluster settings that differ from their defaults.

Fixes: #119786
Fixes: #123830.

Release note: None

### CODE REVIEW

**Review by michae2 — APPROVED** [review]
Thank you for doing this! And nice fixes! I have some suggestions below but you can take or leave them. :lgtm:

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123794#-:-NxnCW3w7fFWeU9RsHog:bdq9gar)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`-- commits` line 62 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123794#-NxnB54HDm53BpNTQJ9v):*
Would it be simpler to print `SET` statements for all writable session variables, regardless of whether they had a non-default value? Admittedly, these `SET` statements would usually be unnecessary for most session variables, but I don't think it would hurt and would get us closer to being able to run `cockroach debug statement-bundle recreate` without any manual edits.
___
*[`pkg/sql/explain_bundle.go` line 847 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123794#-Nxn8KBl7QsLtN2nZT8S:-Nxn8KBl7QsLtN2nZT8T:b-or0p3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc5fdf595b21d67e5bc34d2d8a31fbbb6ac4e841/pkg/sql/explain_bundle.go#L847)):*
> ```Go
> 		if gen.Set == nil && gen.RuntimeSet == nil && gen.SetWithPlanner == nil {
> 			// Skip all read-only variables.
> 			continue
> ```

Some of the read-only variables could be interesting for analysis even though they are not writable. For example, `locality`, `results_buffer_size`, `node_id`, `session_id`, `session_user`, `transaction_priority`, `transaction_status` might come in handy if we're trying to understand why the query executed in a certain way, even though they don't have `Set` (or `GlobalDefault`).
___
*[`pkg/sql/explain_bundle.go` line 954 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123794#-Nxn9ldJ9vHt1kfw_6eC:-Nxn9ldJ9vHt1kfw_6eD:b-nee806) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc5fdf595b21d67e5bc34d2d8a31fbbb6ac4e841/pkg/sql/explain_bundle.go#L954)):*
> ```Go
> 			}
> 			fmt.Fprintf(
> 				w, "--   %s = %s  (default value: %s)\n",
> ```

Would it make sense to directly print `SET CLUSTER SETTING %s = %s;\n` here? (Seems like that would help if our goal is to run `cockroach debug statement-bundle recreate` without needing edits.)
___
*[`pkg/sql/explain_bundle_test.go` line 764 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123794#-NxnCKZ897q82ReFTROB:-NxnCKZ897q82ReFTROC:bdn3jme) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc5fdf595b21d67e5bc34d2d8a31fbbb6ac4e841/pkg/sql/explain_bundle_test.go#L764)):*
> ```Go
> 	vars := strings.Split(sb.String(), "\n")
> 	for _, line := range vars {
> 		_, err := sqlDB.ExecContext(ctx, line)
> ```

Is this how you caught the bugs fixed in the previous commits? If so, nice job!

**Review by mgartner — APPROVED** [review]
Nice! 
:lgtm:

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123794#-:-NxnMw2Y9TPVpWrkMsXE:bwuv9up)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @yuzefovich)

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123794)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @michae2)

___
*[`-- commits` line 62 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123794#-NxnB54HDm53BpNTQJ9v):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Would it be simpler to print `SET` statements for all writable session variables, regardless of whether they had a non-default value? Admittedly, these `SET` statements would usually be unnecessary for most session variables, but I don't think it would hurt and would get us closer to being able to run `cockroach debug statement-bundle recreate` without any manual edits.
</blockquote></details>

I also mention this in another comment (which I typed before this one), but one of my goals with this PR is reducing the amount of stuff we include into `env.sql` to only have useful information. This is because, at least personally, apart from using `debug sb recreate` I also look at `env.sql` directly, so having extra lines, even commented out, makes spotting important non-defaults harder. Can you expand on how having all writable variables would avoid / reduce manual editing?

----

Relatedly, I updated the PR to include necessary cluster setting statements, but there will still be some extra work needed to reconcile session variables and cluster settings in `sb recreate` command (with current approach, the go-to option will be connecting to the `demo` cluster from another shell and then copy-paste `SET` statements for session vars). My hope is that it'll be rare when we have many non-default values for both session vars and cluster settings, so in vast majority of bundles we'd either have no or little extra manual work.

Another idea I had for reconciling session vars and cluster settings would be to do a two-step modification of session vars. Namely:
1. run `SET` session variable statements for non-default session vars. Memorize all of these statements
2. run `SET CLUSTER SETTING` statements for non-default cluster settings.
3. collect all non-default session variable statements again. These should include those already executed in step 1. but should also include a new stmt for each one executed in step 2. Execute only new ones via `RESET session_var;`.

This should work, right? Thoughts on whether it'd be worth it?
___
*[`pkg/sql/explain_bundle.go` line 847 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123794#-Nxn8KBl7QsLtN2nZT8S:-NxoKp4529lnSuLipLXm:b-fu5jvq) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc5fdf595b21d67e5bc34d2d8a31fbbb6ac4e841/pkg/sql/explain_bundle.go#L847)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Some of the read-only variables could be interesting for analysis even though they are not writable. For example, `locality`, `results_buffer_size`, `node_id`, `session_id`, `session_user`, `transaction_priority`, `transaction_status` might come in handy if we're trying to understand why the query executed in a certain way, even though they don't have `Set` (or `GlobalDefault`).
</blockquote></details>

Hm, it's an interesting question I haven't really considered before.

I'd like for us to be conscious about what we include vs exclude. Having everything in `env.sql`, even commented out if matches the default or is read-only, at least for me creates more mental overhead when examining the bundle, so I think it's worth it to exclude things that we think are unlikely to be useful. At the moment there are 23 read-only session variables (and those that don't have `GlobalDefault` set are a subset of them):
```
crdb_version
integer_datetimes
is_superuser
lc_collate
lc_ctype
locality
max_connections
max_identifier_length
max_index_keys
node_id
results_buffer_size
server_encoding
server_version
server_version_num
session_authorization
session_id
session_user
ssl
system_identity
tracing
transaction_priority
transaction_status
virtual_cluster_name
```
Thoughts on which ones might be useful?

I looked at all of them and right now included `is_superuser`, `locality`, `node_id`, `results_buffer_size`, `ssl`, `transaction_priority`, `transaction_status`. `crdb_version` also is useful but it's already included separately. I didn't include `session_id` and `session_user` since I don't see how that can be useful - what scenario are you thinking about? Thoughts on what we should include vs exclude?
___
*[`pkg/sql/explain_bundle.go` line 954 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123794#-Nxn9ldJ9vHt1kfw_6eC:-NxoBxhbCaBRoFdLjuOf:b-bo644b) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc5fdf595b21d67e5bc34d2d8a31fbbb6ac4e841/pkg/sql/explain_bundle.go#L954)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Would it make sense to directly print `SET CLUSTER SETTING %s = %s;\n` here? (Seems like that would help if our goal is to run `cockroach debug statement-bundle recreate` without needing edits.)
</blockquote></details>

The difficulty with that is it wouldn't apply to the current session that was already created on `debug sb recreate` command, so we'd need to connect to the `demo` from another shell for these to take effect. Then, if we connect from another shell we'd lose all the session variables that were SET during `recreate`.

Still, I do see the value of having this in copy-pastable SQL format, so I made the corresponding change.
___
*[`pkg/sql/explain_bundle_test.go` line 764 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123794#-NxnCKZ897q82ReFTROB:-NxoIF5B1liVpIVq9v4e:b-dm93n7) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc5fdf595b21d67e5bc34d2d8a31fbbb6ac4e841/pkg/sql/explain_bundle_test.go#L764)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Is this how you caught the bugs fixed in the previous commits? If so, nice job!
</blockquote></details>

Some of them - `copy_num_retries_per_batch` bug was caught via this test, but "cost scans" one was caught by the linter (it wasn't used anywhere except in the old env bundle implementation). This test is also how I generated the maps for which ones need quotes.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123794)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @michae2)

___
*[`-- commits` line 62 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123794#-NxnB54HDm53BpNTQJ9v):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I also mention this in another comment (which I typed before this one), but one of my goals with this PR is reducing the amount of stuff we include into `env.sql` to only have useful information. This is because, at least personally, apart from using `debug sb recreate` I also look at `env.sql` directly, so having extra lines, even commented out, makes spotting important non-defaults harder. Can you expand on how having all writable variables would avoid / reduce manual editing?

----

Relatedly, I updated the PR to include necessary cluster setting statements, but there will still be some extra work needed to reconcile session variables and cluster settings in `sb recreate` command (with current approach, the go-to option will be connecting to the `demo` cluster from another shell and then copy-paste `SET` statements for session vars). My hope is that it'll be rare when we have many non-default values for both session vars and cluster settings, so in vast majority of bundles we'd either have no or little extra manual work.

Another idea I had for reconciling session vars and cluster settings would be to do a two-step modification of session vars. Namely:
1. run `SET` session variable statements for non-default session vars. Memorize all of these statements
2. run `SET CLUSTER SETTING` statements for non-default cluster settings.
3. collect all non-default session variable statements again. These should include those already executed in step 1. but should also include a new stmt for each one executed in step 2. Execute only new ones via `RESET session_var;`.

This should work, right? Thoughts on whether it'd be worth it?
</blockquote></details>

Thinking more about this - I don't think this idea is really feasible. In order to be able to identify session variables that have non-default values because of the corresponding cluster settings we would need to spin up a fresh `demo` shell in step 2, during bundle collection. In other words, during bundle collection we would include `SET CLUSTER SETTING` statements into `env.sql` and then we'd also need to execute each statement against fresh `demo` to see which session variable, if any, changed; if there is a change, then we'd include `RESET session_var` statement right after the corresponding `SET CLUSTER SETTING`. We cannot use the internal executor against the cluster on which we're collecting the bundle because this cluster already has the settings set. Using non-session-bound internal executor (i.e. jobs-like) also wouldn't work. So I think we would have to spin up a fresh `demo` shell for each.

The only approach to address this I see is extending each session var so that in addition to (or instead of) `GlobalDefault` getter method we would have to explicitly specify the cluster setting object that provides the default for a particular session variable. Effectively, this would move "session var -> cluster setting" mapping (that was incomplete) from the bundle collection to session variable declaration. I'll take a look at this - perhaps it's not that much work.

**Review by michae2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123794)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @yuzefovich)

___
*[`-- commits` line 62 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123794#-NxnB54HDm53BpNTQJ9v):*
> Can you expand on how having all writable variables would avoid / reduce manual editing?

I was thinking that if we have SET statements for all writable session vars, then executing all of them would be a lazy way to handle both (a) the case where the session var was set, and (b) the case where the session var came from a cluster setting that was set, without having to distinguish between the two cases.

> one of my goals with this PR is reducing the amount of stuff we include into `env.sql` to only have useful information.

That is a fair point.

> The only approach to address this I see is extending each session var so that in addition to (or instead of) `GlobalDefault` getter method we would have to explicitly specify the cluster setting object that provides the default for a particular session variable. Effectively, this would move "session var -> cluster setting" mapping (that was incomplete) from the bundle collection to session variable declaration. I'll take a look at this - perhaps it's not that much work.

Is there some way to call `GlobalDefault` with the default `settings.Values` instead of the current `settings.Values`?
___
*[`pkg/sql/explain_bundle.go` line 847 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123794#-Nxn8KBl7QsLtN2nZT8S:-NxtDGVv19WjsGj1GWnG:bna4t3b) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc5fdf595b21d67e5bc34d2d8a31fbbb6ac4e841/pkg/sql/explain_bundle.go#L847)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Hm, it's an interesting question I haven't really considered before.

I'd like for us to be conscious about what we include vs exclude. Having everything in `env.sql`, even commented out if matches the default or is read-only, at least for me creates more mental overhead when examining the bundle, so I think it's worth it to exclude things that we think are unlikely to be useful. At the moment there are 23 read-only session variables (and those that don't have `GlobalDefault` set are a subset of them):
```
crdb_version
integer_datetimes
is_superuser
lc_collate
lc_ctype
locality
max_connections
max_identifier_length
max_index_keys
node_id
results_buffer_size
server_encoding
server_version
server_version_num
session_authorization
session_id
session_user
ssl
system_identity
tracing
transaction_priority
transaction_status
virtual_cluster_name
```
Thoughts on which ones might be useful?

I looked at all of them and right now included `is_superuser`, `locality`, `node_id`, `results_buffer_size`, `ssl`, `transaction_priority`, `transaction_status`. `crdb_version` also is useful but it's already included separately. I didn't include `session_id` and `session_user` since I don't see how that can be useful - what scenario are you thinking about? Thoughts on what we should include vs exclude?
</blockquote></details>

Your list SGTM.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123794)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @michae2)

___
*[`-- commits` line 62 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123794#-NxnB54HDm53BpNTQJ9v):*
> I was thinking that if we have SET statements for all writable session vars, then executing all of them would be a lazy way to handle both (a) the case where the session var was set, and (b) the case where the session var came from a cluster setting that was set, without having to distinguish between the two cases.

Right, good point. For some reason, I missed this point since I was focused on reducing `env.sql` too much :smiley: 

> Is there some way to call `GlobalDefault` with the default `settings.Values` instead of the current `settings.Values`?

That's brilliant! Indeed, I think we can just use a "fresh" values container to get "binary defaults". I updated the commit to include a session variable whenever its value differs either from the "binary default" or the "cluster default" (the binary default is used in the commented out part of the SET statement as before this patch). I used `cluster.MakeTestingClusterSettings()` for that "fresh" container which should work (although this is a non-test code, should I refactor this?).

**Review by michae2 — APPROVED** [review]
:lgtm: Very nice! I left a few more suggestions, but LG!

> Reviewed 7 of 7 files at r9, 1 of 1 files at r10, 2 of 2 files at r11, 5 of 5 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123794#-:-NxyUaEk6P65IJleSK98:b4x0swt)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @yuzefovich)

___
*[`-- commits` line 62 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123794#-NxnB54HDm53BpNTQJ9v):*
Yay!

> I used `cluster.MakeTestingClusterSettings()` for that "fresh" container which should work (although this is a non-test code, should I refactor this?).

:man_shrugging: seems ok to me. It's also used by `genSettingsListCmd` for example.
___
*[`pkg/sql/explain_bundle.go` line 958 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/123794#-NxyTYdjEoZuXSiWJgpr:-NxyTYdjEoZuXSiWJgps:bny9bgu) ([raw file](https://github.com/cockroachdb/cockroach/blob/80a589240ed019683a7b354cc74ed2389e24d722/pkg/sql/explain_bundle.go#L958)):*
> ```Go
> 			// but aren't useful in stmt bundles.
> 			switch *setting {
> 			case "cluster.secret", "diagnostics.reporting.enabled", "version":
> ```

Maybe also skip `enterprise.license`?
___
*[`pkg/sql/explain_bundle.go` line 1175 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/123794#-NxxSJ5q0rTzNP0vqt3G:-NxxSJ5q0rTzNP0vqt3H:b8g34am) ([raw file](https://github.com/cockroachdb/cockroach/blob/80a589240ed019683a7b354cc74ed2389e24d722/pkg/sql/explain_bundle.go#L1175)):*
> ```Go
> 	"server_version_num":    {},
> 	"session_authorization": {},
> 	"session_id":            {},
> ```

`session_id` could help us match this bundle to a debug.zip taken at the same time. It might be worth keeping.
___
*[`pkg/sql/explain_bundle.go` line 1203 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/123794#-NxxT3iHBrcPEVl0gewL:-NxxT3iHBrcPEVl0gewM:blcuf4z) ([raw file](https://github.com/cockroachdb/cockroach/blob/80a589240ed019683a7b354cc74ed2389e24d722/pkg/sql/explain_bundle.go#L1203)):*
> ```Go
> // clusterSettingNeedsQuotes contains all cluster settings that have values that
> // need single quotes around them in SET CLUSTER SETTING statements.
> var clusterSettingNeedsQuotes = map[string]struct{}{
> ```

It might be hard to maintain this list (and the one above). Would it work to put quotes around the values for all `SET` and `SET CLUSTER SETTING` statements?

**Review by yuzefovich — COMMENTED** [review]
Thanks for the reviews!

I think this change is a low risk and high enough reward to be backported, so I added the corresponding labels, but we can discuss merits of the backport on the backport PRs.

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123794#-:-NxzCa778i-A8ftii66J:b-gcwcln)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @michae2)

___
*[`pkg/sql/explain_bundle.go` line 1175 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/123794#-NxxSJ5q0rTzNP0vqt3G:-Nxz8vQh-HSfd02Fypvr:b-umuw07) ([raw file](https://github.com/cockroachdb/cockroach/blob/80a589240ed019683a7b354cc74ed2389e24d722/pkg/sql/explain_bundle.go#L1175)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

`session_id` could help us match this bundle to a debug.zip taken at the same time. It might be worth keeping.
</blockquote></details>

Ack, let's keep it.
___
*[`pkg/sql/explain_bundle.go` line 1203 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/123794#-NxxT3iHBrcPEVl0gewL:-Nxz96V-5DWmfI9t7wDX:bx80aol) ([raw file](https://github.com/cockroachdb/cockroach/blob/80a589240ed019683a7b354cc74ed2389e24d722/pkg/sql/explain_bundle.go#L1203)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

It might be hard to maintain this list (and the one above). Would it work to put quotes around the values for all `SET` and `SET CLUSTER SETTING` statements?
</blockquote></details>

Thanks for asking! I also thought of this when working on session variables, and for them it doesn't work (e.g. `SET reorder_joins_limit = '1';` fails), but it seems to work for all cluster settings (which I assumed wouldn't work either so didn't try before), so I removed one of the maps :smile:

In terms of maintaining this list, I hope that the newly added test should help with that, but it is indeed incomplete - some session variables have `""` as their default which effectively by-passes the test. We'll need to adjust the list manually over time when we find variables that need quotes (I think it should be pretty rare - this would mean that we got a bundle with non-default config for a variable that needs quotes).

**Pull request merged**
