### PR TITLE
jobs: Implement job control for schedules.

### PR DESCRIPTION
**Pull request by miretskiy**
Informs  #51600

Add a `FOR SCHEDULES` clause to job control statements
to enable control over jobs created by the scheduled jobs.

```
PAUSE JOBS FOR SCHEDULE 123
RESUME JOBS FOR SCHEDULES (SELECT schedule_id ....)
CANCEL JOBS FOR SCHEDULE 321
```

Release Notes (enterprise change): Add `FOR SCHEDULES` clause to
the job control statements to enable management of the jobs created
by schedules.

### CODE REVIEW

**Comment by miretskiy** [comment]
@dt @spaskob friendly ping?

**Review by spaskob — COMMENTED** [review]
looks good to me but I am not expert on the grammar and parsing. You'd want to include Rapahel on the PR for this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52038#-:-MDUxXV2DwArP3-gPOdQ:bfivzuh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @spaskob)

**Review by rohany — COMMENTED** [review]
I'm hesitant on this approach to shove the parsed query in an `IN` clause in the delegate. It's going to give extremely cryptic error messages when something has gone wrong, and will be a hassle if we want to allow non-root users to control certain jobs.

**Review by miretskiy — COMMENTED** [review]
I hear you, @rohany .  I've tried different approaches around this; alas, without much success.
Going to discuss this w/ you offline.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52038#-:-MDVRn-O7MOxpUwMVTUw:b-ve9v5a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

**Comment by rohany** [comment]
I discussed with yevgeniy offline, and while I don't like the delegate approach i think that it's fine to do this for now. There is a good amount of work that can be done after this to move to utilizing the optimizer + planNode implementations to do this work and add features (like `RETURNING`). @miretskiy can you leave some TODO's around here for that?

**Review by miretskiy — COMMENTED** [review]
TODO comments added to the delegate implementation.  @rohany, ptal.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52038#-:-MDVphHd6a-pnXUwpxE1:b-b0qsns)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

**Review by rohany — APPROVED** [review]

**Pull request merged**
