### PR TITLE
backupccl: fix crash in SHOW BACKUP when types have cross-db references

### LINKED ISSUE #55772: backupccl: crash on SHOW BACKUP for database with table referencing type in other database
We have a bug that makes cross-database type references possible (https://github.com/cockroachdb/cockroach/issues/55709#issuecomment-712428505). This makes backups not work with RESTORE or SHOW BACKUP. SHOW BACKUP will crash the node:

```
root@:26257/defaultdb> create type t as enum('foo');
CREATE TYPE

Time: 93ms total (execution 93ms / network 0ms)

root@:26257/defaultdb> create table tbl (a t);
CREATE TABLE

Time: 198ms total (execution 78ms / network 120ms)

root@:26257/defaultdb> create database otherdb;
CREATE DATABASE

Time: 56ms total (execution 56ms / network 0ms)

root@:26257/defaultdb> alter table tbl rename to otherdb.tbl;
NOTICE: renaming tables with a qualification is deprecated
HINT: use ALTER TABLE tbl RENAME TO tbl instead
RENAME TABLE

Time: 185ms total (execution 57ms / network 128ms)

root@:26257/defaultdb> backup otherdb to 'nodelocal://backup';
ERROR: failed to resolve targets specified in the BACKUP stmt: table "otherdb" does not exist
root@:26257/defaultdb> backup database otherdb to 'nodelocal://backup';
ERROR: host component of nodelocal URI must be a node ID: nodelocal://backup
root@:26257/defaultdb> backup database otherdb to 'nodelocal://1/backup';
        job_id       |  status   | fraction_completed | rows | index_entries | bytes
---------------------+-----------+--------------------+------+---------------+--------
  600147520773095425 | succeeded |                  1 |    0 |             0 |     0
(1 row)

Time: 366ms total (execution 366ms / network 0ms)

root@:26257/defaultdb> restore otherdb from 'nodelocal://1/backup' with into_db=newdb;
ERROR: failed to resolve targets in the BACKUP location specified by the RESTORE stmt, use SHOW BACKUP to find correct targets: type "t" has unknown ParentID 50
root@:26257/defaultdb> show backup 'nodelocal://1/backup';
ERROR: driver: bad connection
warning: connection lost!
opening new connection: all session settings will be lost
warning: error retrieving the transaction status: dial tcp [::1]:26257: connect: connection refused
warning: connection lost!
opening new connection: all session settings will be lost
warning: error retrieving the database name: dial tcp [::1]:26257: connect: connection refused
```

### PR DESCRIPTION
**Pull request by pbardea**
Previously, SHOW BACKUP would expect that the database and schema it
references is in the backup. In the case that we had a cross-db
reference, the schema or database that it references would not be
included in the backup, and would crash. It now reports objects that it
cannot find as NULL.

Fixes #55772.

Release note (bug fix): Fix crash when performing a SHOW BACKUP against
a backup which contains a table that references a type in another
database. This state was only reachable in 20.2 release candidates and
earlier.

### CODE REVIEW

**Comment by pbardea** [comment]
cc @ajwerner @lucy-zhang 

This is a first attempt at it. It's getting close, but I'm running into issues with hydrating the descriptors in this cross-db reference state...

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5362921]

goroutine 3542 [running]:
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.HydrateGivenDescriptors.func1(0x93e8900, 0xc0024f8bd0, 0x36, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/pbardea/Developer/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:1601 +0xd1
github.com/cockroachdb/cockroach/pkg/sql/catalog/typedesc.TypeLookupFunc.GetTypeDescriptor(0xc0016135e0, 0x93e8900, 0xc0024f8bd0, 0x36, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/pbardea/Developer/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/typedesc/type_desc.go:521 +0x87
github.com/cockroachdb/cockroach/pkg/sql/catalog/typedesc.HydrateTypesInTableDescriptor.func1(0xc0005dcc00, 0xc001b2b638, 0x4011048)
        /Users/pbardea/Developer/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/typedesc/type_desc.go:555 +0x123
github.com/cockroachdb/cockroach/pkg/sql/catalog/typedesc.HydrateTypesInTableDescriptor(0x93e8900, 0xc0024f8bd0, 0xc001938000, 0x935ec40, 0xc0016135e0, 0x3, 0xc00223b748)
        /Users/pbardea/Developer/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/typedesc/type_desc.go:567 +0xd1
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.HydrateGivenDescriptors(0x93e8900, 0xc0024f8bd0, 0xc001a1ebc0, 0x4, 0x4, 0x0, 0x0)
        /Users/pbardea/Developer/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:1612 +0x1ee
github.com/cockroachdb/cockroach/pkg/sql.newInternalLookupCtxFromDescriptors(0x93e8900, 0xc0024f8bd0, 0xc001a1eb40, 0x4, 0x4, 0x0, 0x0, 0x0, 0xbb3bd10)
        /Users/pbardea/Developer/go/src/github.com/cockroachdb/cockroach/pkg/sql/resolver.go:709 +0x9bf
github.com/cockroachdb/cockroach/pkg/sql.(*planner).ShowCreate(0xc001856418, 0x93e8900, 0xc0024f8bd0, 0xc00223b748, 0x7, 0xc001a1eb40, 0x4, 0x4, 0xc002eab900, 0x3, ...)
        /Users/pbardea/Developer/go/src/github.com/cockroachdb/cockroach/pkg/sql/show_create.go:245 +0x163
github.com/cockroachdb/cockroach/pkg/ccl/backupccl.backupShowerDefault.func1(0xc001d40dc0, 0x1, 0x1, 0x1, 0x1, 0x1, 0x0, 0x0)
        /Users/pbardea/Developer/go/src/github.com/cockroachdb/cockroach/pkg/ccl/backupccl/show.go:328 +0x1542
github.com/cockroachdb/cockroach/pkg/ccl/backupccl.showBackupPlanHook.func1(0x93e8840, 0xc0024f0400, 0x0, 0x0, 0x0, 0xc001f7d320, 0x0, 0x0)
        /Users/pbardea/Developer/go/src/github.com/cockroachdb/cockroach/pkg/ccl/backupccl/show.go:186 +0x80e
github.com/cockroachdb/cockroach/pkg/sql.(*hookFnNode).startExec.func1(0xc0017cd580, 0x93e8840, 0xc0024f0400, 0xc00176bb80, 0xc001856418)
        /Users/pbardea/Developer/go/src/github.com/cockroachdb/cockroach/pkg/sql/planhook.go:146 +0x7d
created by github.com/cockroachdb/cockroach/pkg/sql.(*hookFnNode).startExec
        /Users/pbardea/Developer/go/src/github.com/cockroachdb/cockroach/pkg/sql/planhook.go:145 +0xcc
FAIL    github.com/cockroachdb/cockroach/pkg/ccl/backupccl      3.194s
```

**Comment by ajwerner** [comment]
Try:

```go
diff --git a/pkg/sql/catalog/descs/collection.go b/pkg/sql/catalog/descs/collection.go
index 1985efab32..ac8f123602 100644
--- a/pkg/sql/catalog/descs/collection.go
+++ b/pkg/sql/catalog/descs/collection.go
@@ -1585,8 +1585,17 @@ func HydrateGivenDescriptors(ctx context.Context, descs []catalog.Descriptor) er
                // we need to hydrate our types. Set up an accessor for the type hydration
                // method to look into the scanned set of descriptors.
                typeLookup := func(ctx context.Context, id descpb.ID) (tree.TypeName, catalog.TypeDescriptor, error) {
-                       typDesc := typDescs[id]
-                       dbDesc := dbDescs[typDesc.ParentID]
+                       typDesc, ok := typDescs[id]
+                       if !ok {
+                               n := tree.MakeUnresolvedName(fmt.Sprintf("[%d]", id))
+                               return tree.TypeName{}, nil, sqlerrors.NewUndefinedObjectError(&n,
+                                       tree.TypeObject)
+                       }
+                       dbDesc, ok := dbDescs[typDesc.ParentID]
+                       if !ok {
+                               n := fmt.Sprintf("[%d]", typDesc.ParentID)
+                               return tree.TypeName{}, nil, sqlerrors.NewUndefinedDatabaseError(n)
+                       }
```

**Comment by ajwerner** [comment]
Maybe that is bad because it now just omits the table altogether.

**Comment by ajwerner** [comment]
What's the right UX here?

**Comment by pbardea** [comment]
Latest change logs and silently ignores any error we get showing the create statement. I also played around with displaying an error message in that cell rather than "NULL"... but I'm not sure that's the right way to go here.

**Comment by ajwerner** [comment]
Silently ignoring the error is sort of good, right, because it leads to omitting the table, right? That seems sane because you can't restore that table.

**Comment by pbardea** [comment]
We can silently ignore it in 2 ways:
1) Show the table in the SHOW BACKUP command (what it does now, but show the parent db and schema as NULL). This leads to a bit of confusion since we list a table that we can't restore. However, we also show that the database doesn't resovle (NULL) which is the reason we can't restore it. I also like that it keeps the simplicity of `SHOW BACKUP` to show me all the descriptors in the backup.

2) We could omit the table from the output. I don't think we should do this since `SHOW BACKUP` is no longer "show me all the descriptors in the backup" but rather "show me everything I can restore from the backup", which is a lot trickier. I'm not sure if just skipping over rows where the references can't be resolved is enough to be able to claim that we can restore the tables.

**Comment by ajwerner** [comment]
SGTM

**Comment by pbardea** [comment]
Reworking the tests since this will fail once we disallow the rename.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55774#-:-MK7G2Ts81aOZy_Nq1gi:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @lucy-zhang, and @pbardea)

___
*[pkg/ccl/backupccl/restore_old_versions_test.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55774#-MK7FUzt45rAs73MXBax:-MK7FUzt45rAs73MXBay:b-s99tar) ([raw file](https://github.com/cockroachdb/cockroach/blob/58bd663b151d019b567bd1c8780f1d360171a47f/pkg/ccl/backupccl/restore_old_versions_test.go#L89)):*
> ```Go
> 
> 					CREATE TYPE t AS ENUM ('foo');
> 				  CREATE TABLE tbl (a t);
> ```

(I don't care enough for you to fix it tbh) nit: spacing

**Comment by pbardea** [comment]
Removed the map changes so that we have the minimal set of changes go in the backport.

**Review by thoszhang — APPROVED** [review]
> Reviewed 7 of 7 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55774)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dt and @pbardea)

___
*[pkg/ccl/backupccl/restore_old_versions_test.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55774#-MK7Bg5BC8WPw-5kSBth:-MK7Bg5BC8WPw-5kSBti:b-31q1eo) ([raw file](https://github.com/cockroachdb/cockroach/blob/58bd663b151d019b567bd1c8780f1d360171a47f/pkg/ccl/backupccl/restore_old_versions_test.go#L94)):*
> ```Go
> 				  BACKUP DATABASE otherdb TO 'nodelocal://1/xDbRef';
> 
> 					This was permitted on some release candidates of v20.2.
> ```

Add an issue number?
___
*[pkg/ccl/backupccl/restore_old_versions_test.go, line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55774#-MK7CkpE1-Oi9lL9FGVA:-MK7CkpE1-Oi9lL9FGVB:bmyhx2p) ([raw file](https://github.com/cockroachdb/cockroach/blob/58bd663b151d019b567bd1c8780f1d360171a47f/pkg/ccl/backupccl/restore_old_versions_test.go#L123)):*
> ```Go
> 			sqlDB.ExpectErr(t, `type "t" has unknown ParentID 50`, `RESTORE DATABASE otherdb FROM $1`, LocalFoo)
> 
> 			sqlDB.CheckQueryResults(t, `
> ```

Maybe briefly comment on what we're looking for here? (i.e., no crash, and we get some NULLs)

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55774)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dt and @pbardea)

___
*[pkg/ccl/backupccl/restore_old_versions_test.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55774#-MK7Bg5BC8WPw-5kSBth:-MK7KuXPAlxKkSxBzbgp:bo0n30p) ([raw file](https://github.com/cockroachdb/cockroach/blob/58bd663b151d019b567bd1c8780f1d360171a47f/pkg/ccl/backupccl/restore_old_versions_test.go#L94)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Add an issue number?
</blockquote></details>

(#55709)

**Review by pbardea — COMMENTED** [review]
Thanks for the reviews!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55774#-:-MK7aXDP9jU8UeGGqitS:b-hlc8bm)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @dt, and @lucy-zhang)

___
*[pkg/ccl/backupccl/restore_old_versions_test.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55774#-MK7FUzt45rAs73MXBax:-MK7aUUC5mkn-KxNjbwP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/58bd663b151d019b567bd1c8780f1d360171a47f/pkg/ccl/backupccl/restore_old_versions_test.go#L89)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

(I don't care enough for you to fix it tbh) nit: spacing
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/restore_old_versions_test.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55774#-MK7Bg5BC8WPw-5kSBth:-MK7aV8f-h3qcf-F0MUI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/58bd663b151d019b567bd1c8780f1d360171a47f/pkg/ccl/backupccl/restore_old_versions_test.go#L94)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

(#55709)
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/restore_old_versions_test.go, line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55774#-MK7CkpE1-Oi9lL9FGVA:-MK7aW3sB123mxO7ylTN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/58bd663b151d019b567bd1c8780f1d360171a47f/pkg/ccl/backupccl/restore_old_versions_test.go#L123)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Maybe briefly comment on what we're looking for here? (i.e., no crash, and we get some NULLs)
</blockquote></details>

Done.

**Comment by pbardea** [comment]
bors r=lucy-zhang,ajwerner

**Pull request merged**
