### PR TITLE
sql: augment statement logging with a txn counter

### LINKED ISSUE #41925: sql: add a txn identifier in SQL stmt/exec/audit logging
Requested by @rkruze: when troubleshooting performance it is useful to match statements that were issued as part of the same SQL txn.

Since the SQL logging does not show transaction boundaries, it would be useful that the log lines also list a txn identifier.

This needs not be the underlying KV txn UUID, just a way to identify separate txns inside the same session.

(This is beneficial regardless of whether the logging format is also extended to show txn boundaries, as having the txn identifer on every log line enables log parsers to remain stateless)

### PR DESCRIPTION
**Pull request by knz**
Fixes #41925.

Requested by customer success: when troubleshooting performance, it is
useful to match statements that were issued as part of the same SQL
transaction. Previously this is impossible because logging does
neither identify transaction boundaries nor display a transaction
identifier.

This patch improves the situation by extending the statement logging
format to include a txn counter since the beginning of the session.

(It is not feasible to print the low-level KV UUID of the txn in the
log, for both performance and usability reasons; in particular, due to
internal auto-retries the UUID may change throughout a single SQL txn.)

Release justification: bug fixes and low-risk updates to new functionality

Release note (sql change): the structured payloads used for
SQL audit and execution logs now include a transaction counter since
the beginning of the session. Statements issued inside the same SQL
transaction will thus be logged with the same counter value, thus
enabling per-transactions grouping during log analysis. Separate
sessions use independent counters.

### CODE REVIEW

**Comment by knz** [comment]
cc @piyush-singh

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41929)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @jordanlewis, and @knz)

___
*[pkg/sql/txn_state.go, line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41929#-Ls39CI82G-PhrVyHme1:-Ls39CI9-bXWuLzxy_EB:b-xuas7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/35a47b1f62499cb45fa9fad4fca8e59265c10030/pkg/sql/txn_state.go#L121)):*
> ```Go
> 	// hood with multiple KV txn UUIDs, so the KV UUID is not a good
> 	// txn identifier for SQL logging.
> 	txnCounter int
> ```

I think this is not the best place for this field. `txnState` is supposed to be about the state of the current transaction.
I'd try to put this in the executor. The increment can be driven by the events that the state machine returns to the executor (see `txnEvent`).

**Comment by knz** [comment]
> I'd try to put this in the executor.

I tried that but I wasn't able to. The method `resetForNewSQLTxn()` seems not to have access to the entire executor. In which method would I place the increment if not this one?

**Comment by andreimatei** [comment]
Right, not in `resetForNewSQLTxn`. The whole point is to not do any of this into the state machine.
I'd keep it exclusively in the executor, I think around here: https://github.com/cockroachdb/cockroach/blob/0e17a38a11d8065f8efbb42e9d61e7da7adeb1dc/pkg/sql/conn_executor.go#L1982

Notice how the state machine returns some events (different types of events) to the executor.

**Comment by knz** [comment]
Yep, that works. Thanks!

PTAL

**Comment by knz** [comment]
I rebased this. I think it's good to go. PTAL

**Review by rafiss — CHANGES_REQUESTED** [review]
glad to have this!  just had a question on int sizing

i am comfortable with including this in the stability period, so the PR needs release justification now

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41929#-:-MUKs3yb3gMZIOfOUHnn:bx94stq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @knz)

___
*[pkg/sql/exec_log.go, line 250 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41929#-MUKrqyhErmlpEKM0FiI:-MUKrqyhErmlpEKM0FiJ:b8rjrqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/487a6712683d913e294f752d80c4f8ccedac1b5e/pkg/sql/exec_log.go#L250)):*
> ```Go
> 		FullTableScan: p.curPlan.flags.IsSet(planFlagContainsFullTableScan),
> 		FullIndexScan: p.curPlan.flags.IsSet(planFlagContainsFullIndexScan),
> 		TxnCounter:    uint32(txnCounter),
> ```

is there a particular reason to keep this a 32 bit int? 

a maybe unrealistic example: 500 txns/second * 1 year exceeds 2^32.

if it needs to be 32 bits then perhaps the `txnCounter++` above should account for overflow and wrap around to 0.

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41929)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @knz)

___
*[pkg/sql/exec_log.go, line 250 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41929#-MUKrqyhErmlpEKM0FiI:-MUKsWjC9yxJso6StP63:b-ioldys) ([raw file](https://github.com/cockroachdb/cockroach/blob/487a6712683d913e294f752d80c4f8ccedac1b5e/pkg/sql/exec_log.go#L250)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

is there a particular reason to keep this a 32 bit int? 

a maybe unrealistic example: 500 txns/second * 1 year exceeds 2^32.

if it needs to be 32 bits then perhaps the `txnCounter++` above should account for overflow and wrap around to 0.
</blockquote></details>

1 year without any restarts, that is. i'd guess that isn't so common, but seems likely to happen at some point.

**Comment by knz** [comment]
> a maybe unrealistic example: 500 txns/second * 1 year exceeds 2^32.

The counter is per SQL session, I have a hard time imagining a SQL client maintaining their session for that long without a proxy or server restart.

**Review by rafiss — APPROVED** [review]
ah ok per-session, right. lgtm!

**Comment by knz** [comment]
TFYR!

bors r=rafiss,andreimatei

**Pull request merged**
