### PR TITLE
sql: support tenant creation and deletion, track in system.tenants table

### PR DESCRIPTION
**Pull request by nvb**
Most of #47904.

This commit implements the initial structure for tenant creation and deletion. It does so by introducing a new system table to track tenants in a multi-tenant cluster and two new builtin functions to manipulate this table and the overall multi-tenant state.

The change starts by introducing a new `system.tenants` table with the following schema:
```
CREATE TABLE system.tenants (
    id     INT8 NOT NULL PRIMARY KEY,
    active BOOL NOT NULL DEFAULT true,
    info   BYTES
);
```

The `id` column is self-explanatory. The `active` column is used to coordinate tenant destruction in an asynchronous job. The `info` column is an opaque byte slice to allow users to associate arbitrary information with specific tenants. I don't know exactly how this third field will be used (mapping tenants back to CockroachCloud user IDs?), but it seems like a good idea to add some flexibility since we do intend to eventually expose this externally.

The table is given an ID of 8, which means that it falls within the "system config span". I believe this is ok, because the entire concept of the "system config span" should be going away with #47150. The table is also only exposed to the system-tenant and is never created for secondary tenants.

The change then introduces two new builtin functions: `crdb_internal.create_tenant` and `crdb_internal.destroy_tenant`. These do what you would expect - creating and destroying tenant keyspaces, along with updating metadata in system.tenants.

### CODE REVIEW

**Comment by knz** [comment]
would a JSONB field for info not be more useful?

**Review by asubiotto — COMMENTED** [review]
I've looked at #48513 and I'm not sure I understand the thinking behind having a single `DescIDSequence` for all tenants. Why is it not better to have one per tenant and stored in tenant keyspace?

> Reviewed 10 of 10 files at r1, 3 of 3 files at r2, 6 of 6 files at r3, 17 of 17 files at r4, 3 of 3 files at r5, 4 of 4 files at r6, 29 of 29 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48778#-:-M7CK1qrB47JrZHamWZ8:b-rs32uc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

**Comment by tbg** [comment]
@asubiotto isn't the suggestion that each tenant uses a sequence? It's not sharing the sequence between tenants. So I think he's suggesting what you're suggesting, perhaps ambiguously framed.

**Review by tbg — APPROVED** [review]
:lgtm: (I did not look at first three commits). I assume you'll want to wait for @asubiotto's review though.

> Reviewed 10 of 10 files at r1, 3 of 3 files at r2, 6 of 6 files at r3, 17 of 17 files at r4, 3 of 3 files at r5, 4 of 4 files at r6, 29 of 29 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48778#-:-M7CYbqVAO54Gi1zEYrz:bk8ra2m)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[docs/generated/sql/functions.md, line 1061 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/48778#-M7CVLpF37dKc_ofwIi9:-M7CVLpF37dKc_ofwIiA:bjcdzv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db59776eeb1792433916a9687d82487b5c03e74/docs/generated/sql/functions.md#L1061)):*
> ```Markdown
> </table>
> 
> ### Multi-tenancy functions
> ```

Is this internal documentation? We'll want to avoid leaking anything about these into the official docs.
___
*[pkg/sql/descriptor.go, line 60 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/48778#-M7CRtZ_7_Pr8M3N_3_y:-M7CRtZa4anEBV5swPr8:bvlxft0) ([raw file](https://github.com/cockroachdb/cockroach/blob/d80bc2f36a0ae87f5bdaa7829fece2f8d732b6de/pkg/sql/descriptor.go#L60)):*
> ```Go
> func GenerateUniqueDescID(ctx context.Context, db *kv.DB) (sqlbase.ID, error) {
> 	// Increment unique descriptor counter.
> 	newVal, err := kv.IncrementValRetryable(ctx, db, keys.DescIDGenerator, 1)
> ```

Can DescIDGenerator be unexported?
___
*[pkg/sql/tenant.go, line 67 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/48778#-M7CW2YE8fwCl_ojHA5I:-M7CW2YE8fwCl_ojHA5J:b-ug9c9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db59776eeb1792433916a9687d82487b5c03e74/pkg/sql/tenant.go#L67)):*
> ```Go
> 		keys.MakeSQLCodec(roachpb.MakeTenantID(tenID)),
> 		zonepb.DefaultZoneConfigRef(),
> 		zonepb.DefaultSystemZoneConfigRef(),
> ```

These are unused, right? Can we avoid supplying them?
___
*[pkg/sql/tenant.go, line 100 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/48778#-M7CWVx70iMwkZ5nAH1M:-M7CWVx70iMwkZ5nAH1N:b-48hkh3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db59776eeb1792433916a9687d82487b5c03e74/pkg/sql/tenant.go#L100)):*
> ```Go
> 		// NOTE: even if we got this wrong, the rest of the function would fail
> 		// for a non-system tenant because they would be missing a system.tenant
> 		// table.
> ```

It would (at some point) also fail because the KV layer won't let them.
___
*[pkg/sql/tenant.go, line 129 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/48778#-M7CWeHE-AXbeXlmT9gP:-M7CWeHE-AXbeXlmT9gQ:b6wrp28) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db59776eeb1792433916a9687d82487b5c03e74/pkg/sql/tenant.go#L129)):*
> ```Go
> 
> 	// TODO(nvanbenschoten): actually clear tenant keyspace. Do we want to do
> 	// this synchronously or schedule it as a long-running job. Probably the
> ```

Definitely not in the same transaction. I would say `active = false` is irrevocable and we start ClearRanging one the txn commits (blocking return of `destroy_tenant`). If that fails too early, can just re-run the command. The `// tenant already destroyed` case would go away.

Are you intentionally keeping inactive tenants around? I thought they'd be gone once they're gone, but could be recreated.
___
*[pkg/sql/logictest/testdata/logic_test/grant_table, line 168 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/48778#-M7CY7eG5_THLNnSO8Zi:-M7CY7eG5_THLNnSO8Zj:b-m4hs9x) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db59776eeb1792433916a9687d82487b5c03e74/pkg/sql/logictest/testdata/logic_test/grant_table#L168)):*
> ```
> SELECT * FROM [SHOW GRANTS]
>  WHERE schema_name NOT IN ('crdb_internal', 'pg_catalog', 'information_schema')
> ORDER BY 1,2,3
> ```

Why the large diff in this method? Is that just bad diffing?
___
*[pkg/sql/sqlbase/metadata.go, line 231 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/48778#-M7CTZgP--xXDybquPmf:-M7CTZgP--xXDybquPmg:br9zrfg) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c1cbaa40120e3f27bcb44429e93c266fb4b946f/pkg/sql/sqlbase/metadata.go#L231)):*
> ```Go
> 	// this cache for system descriptors that are only found in non-system
> 	// tenants will not be found. That is ok for now, but we'll need to split
> 	// this cache or do something smarter should it become a problem.
> ```

I would rather fix this right now before we forget about it. The only caller into this cache is

https://github.com/cockroachdb/cockroach/blob/c08088d4cc4556ac82ef29451d53278c12970c5b/pkg/sql/physical_schema_accessors.go#L204

which has the codec available. So you can just pre-generate two maps here, and index into the right one. The only plumbing is passing the codec one layer down into `UncachedPhysicalAccessor.GetObjectDesc`, and that only affects eight call sites.
___
*[pkg/sql/sqlbase/system.go, line 108 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/48778#-M7CXi2H3MsE-PgGKiLp:-M7CXi2H3MsE-PgGKiLq:b-c3jbwk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db59776eeb1792433916a9687d82487b5c03e74/pkg/sql/sqlbase/system.go#L108)):*
> ```Go
> 	id     INT8 NOT NULL PRIMARY KEY,
> 	active BOOL NOT NULL DEFAULT true,
> 	info   BYTES,
> ```

It seems unclear what we ultimately want here. I'm fine leaving this info field in, but let's add a comment that it's just a placeholder and may be kept, replaced, or even just removed.

**Review by asubiotto — APPROVED** [review]

**Review by nvb — COMMENTED** [review]
TFTRs!

> would a JSONB field for info not be more useful?

I was thinking that we might want to store encoded protobufs in the field as well, so I think it's best to keep the data type more general. It's easy enough to go from JSON to BYTES and back.

> isn't the suggestion that each tenant uses a sequence? It's not sharing the sequence between tenants. So I think he's suggesting what you're suggesting, perhaps ambiguously framed.

Right, #48513 wasn't intending to mean that we use a "single SQL sequence as DescIDGenerator for all non-system tenants", it was intending to mean that we use a "SQL sequence as DescIDGenerator for each non-system tenants". I can see how that was ambiguous though.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48778#-:-M7J42p_EDUQ1w-nM6gJ:b-6j3to3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

___
*[docs/generated/sql/functions.md, line 1061 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/48778#-M7CVLpF37dKc_ofwIi9:-M7J9o9V4m9aN15qti4-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db59776eeb1792433916a9687d82487b5c03e74/docs/generated/sql/functions.md#L1061)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Is this internal documentation? We'll want to avoid leaking anything about these into the official docs.
</blockquote></details>

Done.
___
*[pkg/sql/descriptor.go, line 60 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/48778#-M7CRtZ_7_Pr8M3N_3_y:-M7JAJoRCHeoywuM9KnA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d80bc2f36a0ae87f5bdaa7829fece2f8d732b6de/pkg/sql/descriptor.go#L60)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Can DescIDGenerator be unexported?
</blockquote></details>

Done.
___
*[pkg/sql/tenant.go, line 67 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/48778#-M7CW2YE8fwCl_ojHA5I:-M7JGaUd6m3PHQIGIlon:by3gphd) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db59776eeb1792433916a9687d82487b5c03e74/pkg/sql/tenant.go#L67)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

These are unused, right? Can we avoid supplying them?
</blockquote></details>

Done by removing the `system.zones` table entirely from secondary tenants.
___
*[pkg/sql/tenant.go, line 100 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/48778#-M7CWVx70iMwkZ5nAH1M:-M7JGg6UClRfQWjB16C0:boump7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db59776eeb1792433916a9687d82487b5c03e74/pkg/sql/tenant.go#L100)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

It would (at some point) also fail because the KV layer won't let them.
</blockquote></details>

Good point. KV level verification of tenant key accesses is going to be a great way to flush out bugs.
___
*[pkg/sql/tenant.go, line 129 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/48778#-M7CWeHE-AXbeXlmT9gP:-M7JV_8W3w6qWK2D0gcy:bqxarxt) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db59776eeb1792433916a9687d82487b5c03e74/pkg/sql/tenant.go#L129)):*
> Definitely not in the same transaction. I would say active = false is irrevocable and we start ClearRanging one the txn commits (blocking return of destroy_tenant). If that fails too early, can just re-run the command. The // tenant already destroyed case would go away.

I like that. I updated https://github.com/cockroachdb/cockroach/issues/48775 and the comment with the idea.

> Are you intentionally keeping inactive tenants around? I thought they'd be gone once they're gone, but could be recreated.

No, I'm not intentionally keeping them around, I just figured that a soft delete would give us more flexibility until we decide on exactly how we want to implement space reclamation.
___
*[pkg/sql/logictest/testdata/logic_test/grant_table, line 168 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/48778#-M7CY7eG5_THLNnSO8Zi:-M7JHNny8TjxH_EPHl2Z:b-qbr038) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db59776eeb1792433916a9687d82487b5c03e74/pkg/sql/logictest/testdata/logic_test/grant_table#L168)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Why the large diff in this method? Is that just bad diffing?
</blockquote></details>

It looks like `rowsort` was hiding the fact that this output was in the completely wrong order (`ORDER BY 1,2,3`). Oliver also hit this in https://github.com/cockroachdb/cockroach/commit/86641f9078d79dbbbf6c8527e021818f04068a3b#diff-b254deb01f059b658ce2401c034f3bdfL169.

I've removed the `rowsort` because it's not needed with the explicit ordering.
___
*[pkg/sql/sqlbase/metadata.go, line 231 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/48778#-M7CTZgP--xXDybquPmf:-M7JTTQA5Zy-1NaQZizm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c1cbaa40120e3f27bcb44429e93c266fb4b946f/pkg/sql/sqlbase/metadata.go#L231)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I would rather fix this right now before we forget about it. The only caller into this cache is

https://github.com/cockroachdb/cockroach/blob/c08088d4cc4556ac82ef29451d53278c12970c5b/pkg/sql/physical_schema_accessors.go#L204

which has the codec available. So you can just pre-generate two maps here, and index into the right one. The only plumbing is passing the codec one layer down into `UncachedPhysicalAccessor.GetObjectDesc`, and that only affects eight call sites.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/system.go, line 108 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/48778#-M7CXi2H3MsE-PgGKiLp:-M7JTXHnCmwS_UrLQrgU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db59776eeb1792433916a9687d82487b5c03e74/pkg/sql/sqlbase/system.go#L108)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

It seems unclear what we ultimately want here. I'm fine leaving this info field in, but let's add a comment that it's just a placeholder and may be kept, replaced, or even just removed.
</blockquote></details>

Done.

**Pull request merged**
