### PR TITLE
kv: use response keys of ranged writes for lock tracking

### PR DESCRIPTION
**Pull request by nvb**
Informs #117978.

This PR updates the `txnPipeliner` to use the response keys from `Get`, `Scan`, `ReverseScan`, and `DeleteRange` requests to track pipelined and non-pipelined lock acquisitions / intent writes, instead of assuming that the requests could have left intents anywhere in their request span. This more precise tracking avoid broad ranged intent resolution when more narrow intent resolution is possible. It will also be used by #117978 to track in-flight replicated lock acquisition.

This is a WIP. Some tests need to be updated.

Release note: None

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
This looks good. Let me know when the tests are updated, and I'll give this one more look and stamp it!

> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121086#-:-NtvCSCh5yXY6f0Wiymg:bizpsod)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`-- commits` line 20 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/121086#-NtvAGiN2Sq4GbbdOHaD):*
Nice!
___
*[`-- commits` line 39 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/121086#-NtvAWrOARBKaPpERhgr):*
https://github.com/cockroachdb/cockroach/pull/121119 should help. I found it very cumbersome to update this test and still keep it meaningful while working on the DeleteRange pipelining PR yesterday, so I punted the problem to this PR (sorry!) 
___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go` line 758 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/121086#-NtvBorw1XbuDN08_qKW:-NtvBorw1XbuDN08_qKX:b-rwxl9r) ([raw file](https://github.com/cockroachdb/cockroach/blob/1136532c5cffa10811aa06ed231518318e654c76/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L758)):*
> ```Go
> 						log.Fatalf(ctx, "unexpected multi-key intent pipelined")
> 					}
> 					tp.ifWrites.insert(span.Key, seq)
> ```

nit: mind adding a TODO somewhere to rename this to `ifLocks` or something similar? 
___
*[`pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go` line 1107 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/121086#-NtvB2CP2tH11oCQ2FVm:-NtvB2CP2tH11oCQ2FVn:bwg0l04) ([raw file](https://github.com/cockroachdb/cockroach/blob/1136532c5cffa10811aa06ed231518318e654c76/pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go#L1107)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 	defer log.Scope(t).Close(t)
> 	skip.IgnoreLint(t, "WIP")
> ```

TIL this is a thing!

**Review by nvb — COMMENTED** [review]
TFTR! I've addressed the comments and updated all tests. This should be good for another look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121086#-:-NtyEpusEGo5foXwWWko:b-7inyq3)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`-- commits` line 39 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/121086#-NtvAWrOARBKaPpERhgr):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

https://github.com/cockroachdb/cockroach/pull/121119 should help. I found it very cumbersome to update this test and still keep it meaningful while working on the DeleteRange pipelining PR yesterday, so I punted the problem to this PR (sorry!)
</blockquote></details>

Thanks! This was failing before the rebase.
___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go` line 758 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/121086#-NtvBorw1XbuDN08_qKW:-NtxljcP9UF8hkGgrH4O:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1136532c5cffa10811aa06ed231518318e654c76/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L758)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: mind adding a TODO somewhere to rename this to `ifLocks` or something similar?
</blockquote></details>

Done.

**Review by arulajmani — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r5, 3 of 3 files at r6, 2 of 2 files at r7, 3 of 6 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121086#-:-Nu-5-edBqTGCcyeflzV:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by nvanbenschoten** [comment]
TFTR!

bors r+

**Pull request merged**
