### PR TITLE
sql: teach makeSpansForIndexConstraints about interleaving

### LINKED ISSUE #13451: sql: table scans over interleaved tables return incorrect results
Cockroach version: beta-20170126.

Copy-and-paste code from https://www.cockroachlabs.com/docs/interleave-in-parent.html into SQL console:
```
root@:26257> CREATE TABLE customers (
               id INT PRIMARY KEY,
               name STRING(50)
             );
CREATE TABLE

root@:26257> CREATE TABLE orders (
               customer INT, 
               id INT,
               total DECIMAL(20, 5), 
               PRIMARY KEY (customer, id), 
               CONSTRAINT fk_customer FOREIGN KEY (customer) REFERENCES customers
               ) INTERLEAVE IN PARENT customers (customer)
             ;
CREATE TABLE

root@:26257> INSERT INTO customers 
             (id, name) VALUES 
             (1, 'Ha-Yun'),
             (2, 'Emanuela');
INSERT 2

root@:26257> INSERT INTO orders 
             (customer, id, total) VALUES 
             (1, 1000, 100.00),
             (2, 1001, 90.00),
             (1, 1002, 80.00),
             (2, 1003, 70.00);
INSERT 4
```

Then try SELECT **(bug?!)**:

```
root@:26257> SELECT * FROM orders WHERE customer=1 AND id=1000;
+----------+----+-------+
| customer | id | total |
+----------+----+-------+
+----------+----+-------+
(0 rows)
```

But I expect:

```
root@:26257> SELECT * FROM orders WHERE customer=1 AND id=1000;
+----------+------+-------+
| customer |  id  | total |
+----------+------+-------+
|        1 | 1000 |   100 |
+----------+------+-------+
(1 row)
```

Why do I get an empty result?

### PR DESCRIPTION
**Pull request by eisenstatdavid**
Fixes #13451

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/index_selection.go, line 1056 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043#-Ki1P9d3Ej2OhtEReEag:-Ki1P9d3Ej2OhtEReEah:b-iyew6r) ([raw file](https://github.com/cockroachdb/cockroach/blob/df4f95b870d72bcd467396269dfb9743808cde5b/pkg/sql/index_selection.go#L1056)):*
> ```Go
> 	interstices[0] = sqlbase.MakeIndexKeyPrefix(tableDesc, index.ID)
> 	if len(index.Interleave.Ancestors) > 0 {
> 		// TODO(eisen): too much of this code is shared with EncodePartialIndexKey.
> ```

s/shared/duplicated/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043)*

**Comment by danhhz** [comment]
@RaduBerinde can you also look at this? I'm still grokking this file for the first time, really

**Comment by danhhz** [comment]
the interleaved part here lgtm (the way interstitials works is nice)

I'm science dogging on the span generation part too much for my own comfort, so we should find someone to review that (radu or someone else if he doesn't have time)

---

Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/index_selection.go, line 99 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043#-Ki670ndA0QgWFx-SV95:-Ki670ndA0QgWFx-SV96:b-7ck7r3) ([raw file](https://github.com/cockroachdb/cockroach/blob/df4f95b870d72bcd467396269dfb9743808cde5b/pkg/sql/index_selection.go#L99)):*
> ```Go
> 		s.spans, err = makeSpans(nil, &s.desc, s.index)
> 		if err != nil {
> 			return nil, errors.Wrap(err, "makeSpans")
> ```

this errors.Wrap doesn't add much information, given that "makeSpans" should already be in the stacktrace. maybe use errors.Wrapf to include information about the table and index (and below the constraints)?

---

*[pkg/sql/index_selection.go, line 1087 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043#-Ki65kQEgzNzEOAP-K4t:-Ki65kQEgzNzEOAP-K4u:b24kme5) ([raw file](https://github.com/cockroachdb/cockroach/blob/df4f95b870d72bcd467396269dfb9743808cde5b/pkg/sql/index_selection.go#L1087)):*
> ```Go
> func spanFromLogicalSpan(ls logicalSpan, interstices [][]byte) (roachpb.Span, error) {
> 	var s roachpb.Span
> 	for i := 0; true; i++ {
> ```

nit: don't need the true

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043#-:-Ki69Yf5taVN4aGM352h:bsf4oym)*

**Comment by RaduBerinde** [comment]
:lgtm_strong:

---

Review status: 1 of 3 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/sql/index_selection.go, line 892 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043#-Ki6M97DuNPeoQ2-mmVB:-Ki6M97EKbJzTWnrvYAP:b-5xjxbf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9574193e70ef812972da394473d09c9e26f55381/pkg/sql/index_selection.go#L892)):*
> ```Go
> 			inclusive: true,
> 		}
> 	default:
> ```

This should be like the function above: a case with the operators for which this actually makes sense (EQ, LE, LT) and a default case with a panic. Same below

---

*[pkg/sql/index_selection.go, line 1037 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043#-Ki6KoRKlrrcc0OS3q3k:-Ki6KoRKlrrcc0OS3q3l:bnoonf8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9574193e70ef812972da394473d09c9e26f55381/pkg/sql/index_selection.go#L1037)):*
> ```Go
> }
> 
> // logicalSpan is a higher-level representation of a span that uses Datums
> ```

This is great, it was on a wishlist (#6346). In the future, I think we probably want to remove the expressions in `indexConstraints` as well and directly put in `logicalKeyPart`s.

---

*[pkg/sql/index_selection.go, line 1092 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043#-Ki6PxhMvuZ7r8OI_bOY:-Ki6PxhMvuZ7r8OI_bOZ:b-kk4ncj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9574193e70ef812972da394473d09c9e26f55381/pkg/sql/index_selection.go#L1092)):*
> ```Go
> 	// x±1" for the last end constraint, depending on the encoding direction
> 	// (since this keeps the key nice and pretty-printable). However, we might not
> 	// be able to do the ±1.
> ```

When we use `PrefixEnd,` the resulting span will not be "tight", meaning it might include some results that we don't want. Does the rest of the code take this into account and keep the initial expression as an additional filter in this case? (This is worth mentioning in a comment)

---

*[pkg/sql/index_selection.go, line 1056 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043#-Ki1P9d3Ej2OhtEReEag:-Ki6TP3tsfWBbQ1AqB2K:b9rslx0) ([raw file](https://github.com/cockroachdb/cockroach/blob/df4f95b870d72bcd467396269dfb9743808cde5b/pkg/sql/index_selection.go#L1056)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

s/shared/duplicated/
</blockquote></details>

Why are we not just using that function directly, inside `spanFromLogicalSpan`/`encodeLogicalKeyPart`?
(by the way, looking at that function it seems broken because we don't exit when we finished the columns early, I can open up a PR to fix it)

---

*[pkg/sql/index_selection.go, line 1085 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043#-Ki6Yg2J7nQQE_kSEBfI:-Ki6Yg2J7nQQE_kSEBfJ:by0yfm9) ([raw file](https://github.com/cockroachdb/cockroach/blob/df4f95b870d72bcd467396269dfb9743808cde5b/pkg/sql/index_selection.go#L1085)):*
> ```Go
> }
> 
> func spanFromLogicalSpan(ls logicalSpan, interstices [][]byte) (roachpb.Span, error) {
> ```

this needs a comment explaining how the interstices array works (`interstices[i]` is inserted right before the `i`th value)

---

*[pkg/sql/testdata/logic_test/interleaved, line 248 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043#-Ki6ZbgF7yWv2KLPrEi4:-Ki6ZbgF7yWv2KLPrEi5:bwyjnbs) ([raw file](https://github.com/cockroachdb/cockroach/blob/df4f95b870d72bcd467396269dfb9743808cde5b/pkg/sql/testdata/logic_test/interleaved#L248)):*
> ```
> CREATE TABLE err (i INT PRIMARY KEY) INTERLEAVE IN PARENT p1_1 (i) RESTRICT
> 
> # Regression test for #13451
> ```

would be good to add some cases with multiple interleaved ancestors

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043#-:-Ki6_pjwGsnGyNWbnkh5:b-jbsf8z)*

**Comment by eisenstatdavid** [comment]
Review status: 1 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/sql/index_selection.go, line 892 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043#-Ki6M97DuNPeoQ2-mmVB:-Ki6rdSNO46cSHviZvHg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9574193e70ef812972da394473d09c9e26f55381/pkg/sql/index_selection.go#L892)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This should be like the function above: a case with the operators for which this actually makes sense (EQ, LE, LT) and a default case with a panic. Same below
</blockquote></details>

Done.

---

*[pkg/sql/index_selection.go, line 1037 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043#-Ki6KoRKlrrcc0OS3q3k:-Ki6dhKSZ_T_o0gnTB76:bykgn6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/9574193e70ef812972da394473d09c9e26f55381/pkg/sql/index_selection.go#L1037)):*
> In the future, I think we probably want to remove the expressions in indexConstraints as well and directly put in logicalKeyParts.
Added a TODO with this text.

---

*[pkg/sql/index_selection.go, line 1092 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043#-Ki6PxhMvuZ7r8OI_bOY:-Ki6eKj34PcpNtDjx5tq:b-fzjldm) ([raw file](https://github.com/cockroachdb/cockroach/blob/9574193e70ef812972da394473d09c9e26f55381/pkg/sql/index_selection.go#L1092)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

When we use `PrefixEnd,` the resulting span will not be "tight", meaning it might include some results that we don't want. Does the rest of the code take this into account and keep the initial expression as an additional filter in this case? (This is worth mentioning in a comment)
</blockquote></details>

I copied this comment verbatim from the defunct function "encodeInclusiveEndValue", but ISTM that none of the keys that come between the end keys produced by these two procedures (if both applicable) could be valid -- the +1 logic in general will make the span bigger. Perhaps I don't understand your comment.

---

*[pkg/sql/index_selection.go, line 99 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043#-Ki670ndA0QgWFx-SV95:-Ki6recS_HC8n7lyfx6z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/df4f95b870d72bcd467396269dfb9743808cde5b/pkg/sql/index_selection.go#L99)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

this errors.Wrap doesn't add much information, given that "makeSpans" should already be in the stacktrace. maybe use errors.Wrapf to include information about the table and index (and below the constraints)?
</blockquote></details>

Done.

---

*[pkg/sql/index_selection.go, line 1085 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043#-Ki6Yg2J7nQQE_kSEBfI:-Ki6eAFOIB7npT1sb7BO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/df4f95b870d72bcd467396269dfb9743808cde5b/pkg/sql/index_selection.go#L1085)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

this needs a comment explaining how the interstices array works (`interstices[i]` is inserted right before the `i`th value)
</blockquote></details>

Done.

---

*[pkg/sql/index_selection.go, line 1087 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043#-Ki65kQEgzNzEOAP-K4t:-Ki6eAqsynBWAoqerrol:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/df4f95b870d72bcd467396269dfb9743808cde5b/pkg/sql/index_selection.go#L1087)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: don't need the true
</blockquote></details>

Done.

---

*[pkg/sql/testdata/logic_test/interleaved, line 248 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043#-Ki6ZbgF7yWv2KLPrEi4:-Ki6rbLiQ2-QuOBkCKdh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/df4f95b870d72bcd467396269dfb9743808cde5b/pkg/sql/testdata/logic_test/interleaved#L248)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

would be good to add some cases with multiple interleaved ancestors
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043)*

**Comment by eisenstatdavid** [comment]
Review status: 1 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/sql/index_selection.go, line 1056 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043#-Ki1P9d3Ej2OhtEReEag:-Ki6rneoWDlN712aolvC:b-umiz8s) ([raw file](https://github.com/cockroachdb/cockroach/blob/df4f95b870d72bcd467396269dfb9743808cde5b/pkg/sql/index_selection.go#L1056)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Why are we not just using that function directly, inside `spanFromLogicalSpan`/`encodeLogicalKeyPart`?
(by the way, looking at that function it seems broken because we don't exit when we finished the columns early, I can open up a PR to fix it)
</blockquote></details>

I'll look into this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043)*

**Comment by eisenstatdavid** [comment]
Review status: 1 of 4 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/sql/index_selection.go, line 1056 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043#-Ki1P9d3Ej2OhtEReEag:-Ki6xlezYKywY0KUXEnS:b-r1rfu5) ([raw file](https://github.com/cockroachdb/cockroach/blob/df4f95b870d72bcd467396269dfb9743808cde5b/pkg/sql/index_selection.go#L1056)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

I'll look into this.
</blockquote></details>

There's an interaction between the inclusive flag and whether we emit the interstice (inclusive: yes interstice; exclusive: no interstice) that I don't think can be captured easily by `encodeLogicalKeyPart`. I'd prefer not to rush into refactoring here since (1) I'm not sure what the right interface is (2) `encodeLogicalKeyPart` is on the write hot path.

I'll send you a PR fixing `encodeLogicalKeyPart`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043)*

**Comment by eisenstatdavid** [comment]
Review status: 1 of 4 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/sql/index_selection.go, line 1056 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043#-Ki1P9d3Ej2OhtEReEag:-Ki74H5_JO0bv-Uhma_o:budsh80) ([raw file](https://github.com/cockroachdb/cockroach/blob/df4f95b870d72bcd467396269dfb9743808cde5b/pkg/sql/index_selection.go#L1056)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

There's an interaction between the inclusive flag and whether we emit the interstice (inclusive: yes interstice; exclusive: no interstice) that I don't think can be captured easily by `encodeLogicalKeyPart`. I'd prefer not to rush into refactoring here since (1) I'm not sure what the right interface is (2) `encodeLogicalKeyPart` is on the write hot path.

I'll send you a PR fixing `encodeLogicalKeyPart`.
</blockquote></details>

(You beat me to it -- #15185.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043)*

**Comment by RaduBerinde** [comment]
Review status: 1 of 4 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/sql/index_selection.go, line 1092 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043#-Ki6PxhMvuZ7r8OI_bOY:-Ki70GQdC2J5JnU-3FCr:b-76lks9) ([raw file](https://github.com/cockroachdb/cockroach/blob/9574193e70ef812972da394473d09c9e26f55381/pkg/sql/index_selection.go#L1092)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

I copied this comment verbatim from the defunct function "encodeInclusiveEndValue", but ISTM that none of the keys that come between the end keys produced by these two procedures (if both applicable) could be valid -- the +1 logic in general will make the span bigger. Perhaps I don't understand your comment.
</blockquote></details>

I am probably not taking into account some of the details of the encodings. My thought was that for something that has no next value (say a descending string, or decimal), there may be valid values with keys between `k` and `k.PrefixEnd()`. For example if `k` is `1.001`, would `PrefixEnd()` be something that's close to (say) `1.002`, and if so values like `1.0015` could be in the span.

I can't quite come up with an example so I am probably missing something. If it's not possible for any valid keys to exist between `k` and `k.PrefixEnd()` then ignore me.

---

*[pkg/sql/index_selection.go, line 1056 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043#-Ki1P9d3Ej2OhtEReEag:-Ki7-EXoZ8KGfU0yMka-:bziffbi) ([raw file](https://github.com/cockroachdb/cockroach/blob/df4f95b870d72bcd467396269dfb9743808cde5b/pkg/sql/index_selection.go#L1056)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

There's an interaction between the inclusive flag and whether we emit the interstice (inclusive: yes interstice; exclusive: no interstice) that I don't think can be captured easily by `encodeLogicalKeyPart`. I'd prefer not to rush into refactoring here since (1) I'm not sure what the right interface is (2) `encodeLogicalKeyPart` is on the write hot path.

I'll send you a PR fixing `encodeLogicalKeyPart`.
</blockquote></details>

I  know what you mean. I dithered between including that or not in the key in #15185. I think it's reasonable to add a flag to `EncodePartialIndexKey` to indicate if we want that last interstitial (perhaps explained that with a prefix of an interleaving, we can have a "low key" and a "high key"). The flag wouldn't be needed for `EncodeIndexKey` (which is the heavily used form).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043)*

**Comment by RaduBerinde** [comment]
Review status: 1 of 4 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/sql/index_selection.go, line 1092 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043#-Ki6PxhMvuZ7r8OI_bOY:-Ki7Hg7Gx1WrJ6nJklLI:b-nwdgfj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9574193e70ef812972da394473d09c9e26f55381/pkg/sql/index_selection.go#L1092)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I am probably not taking into account some of the details of the encodings. My thought was that for something that has no next value (say a descending string, or decimal), there may be valid values with keys between `k` and `k.PrefixEnd()`. For example if `k` is `1.001`, would `PrefixEnd()` be something that's close to (say) `1.002`, and if so values like `1.0015` could be in the span.

I can't quite come up with an example so I am probably missing something. If it's not possible for any valid keys to exist between `k` and `k.PrefixEnd()` then ignore me.
</blockquote></details>

Yeah the situation I am thinking of can only happen if two values can result in keys where one is a prefix of the other. This is by design never the case with key encodings. So never mind, sorry about that.

Then I wonder - why aren't we always using `PrefixEnd`? Why do we try to avoid it by doing the +1 thing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043)*

**Comment by eisenstatdavid** [comment]
Review status: 1 of 4 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/sql/index_selection.go, line 1092 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043#-Ki6PxhMvuZ7r8OI_bOY:-Ki7KbVfDJvxb1fon5Cc:bxjnv57) ([raw file](https://github.com/cockroachdb/cockroach/blob/9574193e70ef812972da394473d09c9e26f55381/pkg/sql/index_selection.go#L1092)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yeah the situation I am thinking of can only happen if two values can result in keys where one is a prefix of the other. This is by design never the case with key encodings. So never mind, sorry about that.

Then I wonder - why aren't we always using `PrefixEnd`? Why do we try to avoid it by doing the +1 thing?
</blockquote></details>

Human readability ("since this keeps the key nice and pretty-printable").

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043)*

**Comment by RaduBerinde** [comment]
:lgtm_strong: 

---

Review status: 1 of 4 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/sql/index_selection.go, line 1092 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043#-Ki6PxhMvuZ7r8OI_bOY:-Ki7KyJyXHkcSWlarlZl:bqr67wn) ([raw file](https://github.com/cockroachdb/cockroach/blob/9574193e70ef812972da394473d09c9e26f55381/pkg/sql/index_selection.go#L1092)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

Human readability ("since this keeps the key nice and pretty-printable").
</blockquote></details>

Got it, I missed that, thanks!

---

*[pkg/sql/testdata/logic_test/deep_interleaving, line 42 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043#-Ki7LKD47mNrOS8thsoV:-Ki7LKD47mNrOS8thsoW:bas4e8o) ([raw file](https://github.com/cockroachdb/cockroach/blob/8efdad16650da65bbadb8c876264036398e9b324/pkg/sql/testdata/logic_test/deep_interleaving#L42)):*
> ```
> 
> statement ok
> INSERT INTO level3 VALUES (1, 10, 100), (1, 10, 200), (1, 10, 300), (1, 20, 100), (1, 20, 200), (1, 20, 300), (1, 30, 100), (1, 30, 200), (1, 30, 300), (2, 10, 100), (2, 10, 200), (2, 10, 300), (2, 20, 100), (2, 20, 200), (2, 20, 300), (2, 30, 100), (2, 30, 200), (2, 30, 300), (3, 10, 100), (3, 10, 200), (3, 10, 300), (3, 20, 100), (3, 20, 200), (3, 20, 300), (3, 30, 100), (3, 30, 200), (3, 30, 300)
> ```

[nit] please break these up into multiple lines

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043#-:-Ki7LW2CKs-5MCLQnmGA:b-uwkowd)*

**Comment by eisenstatdavid** [comment]
Review status: 1 of 4 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/sql/index_selection.go, line 1056 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043#-Ki1P9d3Ej2OhtEReEag:-Ki7mZZsfjEy4f-HqIGa:b8dhfo3) ([raw file](https://github.com/cockroachdb/cockroach/blob/df4f95b870d72bcd467396269dfb9743808cde5b/pkg/sql/index_selection.go#L1056)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I  know what you mean. I dithered between including that or not in the key in #15185. I think it's reasonable to add a flag to `EncodePartialIndexKey` to indicate if we want that last interstitial (perhaps explained that with a prefix of an interleaving, we can have a "low key" and a "high key"). The flag wouldn't be needed for `EncodeIndexKey` (which is the heavily used form).
</blockquote></details>

I'll take a crack at this tomorrow.

---

*[pkg/sql/testdata/logic_test/deep_interleaving, line 42 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043#-Ki7LKD47mNrOS8thsoV:-Ki7mY7fp22Sd_JO5Y4T:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8efdad16650da65bbadb8c876264036398e9b324/pkg/sql/testdata/logic_test/deep_interleaving#L42)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] please break these up into multiple lines
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15043)*

**Pull request merged**
