### PR TITLE
Backup/Restore tweaks

### PR DESCRIPTION
**Pull request by danhhz**
Ignore the first commit, it's another PR

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8621)

### CODE REVIEW

**Comment by paperstreet** [comment]
cc @knz for name stuff

**Comment by paperstreet** [comment]
friendly ping?

**Comment by knz** [comment]
Yep, sorry for that. :lgtm: !

---

Reviewed 6 of 6 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8621#-:-KPmgtMDSTu19fg3cjuT:ba2ewk3)*

**Comment by dt** [comment]
:lgtm:

---

Reviewed 5 of 6 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/backup_test.go, line 179 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8621#-KPmg_9l1iw43s4efPPi:-KPmg_9l1iw43s4efPPj:brrm4l1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e6d65e2b7d15c941ae3e0b222a49d2a6e7ad98b/sql/backup_test.go#L179)):*
> ```Go
> 		t.Fatal(err)
> 	} else {
> 		approxDataSize := int64(backupRestoreApproxRowSize) * count
> ```

nit: doesn't our lint/style guide say this should be de-dented (and the above bind deinlined)? feel free to ignore, I this that linter is stupid and results in overly scoped binds.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8621#-:-KPmiK4GCbn9EWnK8SWn:bnfp4nl)*

**Comment by paperstreet** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/backup_test.go, line 179 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8621#-KPmg_9l1iw43s4efPPi:-KPmj4nCyRFCMMU5Qh_M:bayu0z3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e6d65e2b7d15c941ae3e0b222a49d2a6e7ad98b/sql/backup_test.go#L179)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> nit: doesn't our lint/style guide say this should be de-dented (and the above bind deinlined)? feel free to ignore, I this that linter is stupid and results in overly scoped binds.
</details>
Ah, you're right: https://github.com/golang/go/wiki/CodeReviewComments#indent-error-flow. I always thought that was just that one linter being dumb. Followup incoming.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8621)*

**Pull request merged**
