### PR TITLE
lint: rename roachlint to roachvet, fold std vet into it, run roachvet on every PR

### PR DESCRIPTION
**Pull request by ajwerner**
In #42595 we disabled the `roachlint` lint test from running on every commit.
This was done due to its outsized memory usage. This PR identifies that the root cause of
this memory usage was the decision to use [multichecker](https://godoc.org/golang.org/x/tools/go/analysis/multichecker) rather than [unitchecker](https://godoc.org/golang.org/x/tools/go/analysis/unitchecker) in the roachlint binary. Multichecker analyses all compilation units in a single phase whereas unitchecker analyzes each compilation unit separately. When run using the unitchecker frontend, roachlint does not seem to use more RAM than normal compilation. After making this observation I noticed that go vet is defined as a set of analysis passes. This change then rolls all of the go vet passes into our one vet binary.

The last second commit fixes a vet problem which was uncovered. 
The third commit enables vet for test files and fixes issues found in test files.

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
It's additionally worth noting that `roachlint` on my laptop takes a bit less than a minute. Relative to `staticcheck` or `shadow` this is short. I just ran the entire suite of linters and `staticcheck` is now the most memory hungry. It seems to use around 10GB at peak.

**Comment by knz** [comment]
Can you trigger the TC run so we see how long the lint CI target now takes?

**Comment by ajwerner** [comment]
> Can you trigger the TC run so we see how long the lint CI target now takes?


It finished and took `27m:55s` which is a bit longer than the average of `26m:21s` but just about lines up with my expectation.

**Comment by ajwerner** [comment]
Also perhaps of interest is the first iteration of this PR which did not include the conversion fix commit ran the lint stage in `24m:57s` and failed due to the lint failure.

**Comment by knz** [comment]
Ok so FYI this PR increases the duration of the CI "lint" target from 24m:24s to 27m:55s (+3mn).

**Comment by knz** [comment]
So that's 5%-15% increase depending on which measurement we take.

I'm all good for your specific PR here, but these times are really not great overall.

**Comment by ajwerner** [comment]
> I'm all good for your specific PR here, but these times are really not great overall.

I totally agree. There exists a `shadow` analyzer [here](https://godoc.org/golang.org/x/tools/go/analysis/passes/shadow). Adding a new pass to `roachlint` should be relatively cheap as the bulk of the work is the type checking. I'll see what replacing the explicit `shadow` command (which is based on the same logic) with an added pass does to the total duration.

**Comment by ajwerner** [comment]
I've learned some more things.

It turns out there are two ways to run analyzers: https://godoc.org/golang.org/x/tools/go/analysis/unitchecker and https://godoc.org/golang.org/x/tools/go/analysis/multichecker. Where the former does a single compilation unit at a time and the latter does them all at the same time. There's a runtime/memory tradeoff in that each time you analyze a compilation unit you at least analyze its direct dependencies.

It also turns out that go vet is just a collection of these analyzers run as a single `unitchecker` run: https://golang.org/src/cmd/vet/main.go

I'm going to attempt to roll all of our vet tasks into a single vettool and get rid of the existing vet step.

**Review by knz — COMMENTED** [review]
All these changes (especially the newly found lint problems in tests!) are really cool. Congrats on figuring out how to unify roachlint and go-vet.

The time now is 29mn, so we're going in the wrong direction wrt latency, but the code simplification is nice.

I'm still not too sure about the best strategy forward. Probably this PR is good to go but for the sake of our collective sanity it becomes really urgent to look into #42642.

> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43495#-:-LwtNT3e19i_k1sfY0b2:b-edewoi)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by ajwerner** [comment]
I did a little bit of digging and a lot of the variance is attributed to different portions of the build step than actually running the linters. In this run of [this](https://teamcity.cockroachdb.com/viewLog.html?buildId=1662222&buildTypeId=Cockroach_UnitTests_Check) PR it took 19m. It seems like whether the instance was just booted vs. already had run has some impact on the latency.

I believe that this is moving us in the right direction, or at least, not in the wrong direction in the way that the previous change was. Here's what a coarse breakdown on the fast build referenced above looks like:

```
Step 4/6: make lint (Command Line) (19m:14s)
[19:54:58]
[Step 4/6] Starting: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/build/teamcity-check.sh
[19:54:58]
[Step 4/6] in directory: /home/agent/work/.go/src/github.com/cockroachdb/cockroach
[19:54:58]
[Step 4/6] Prepare environment
[19:54:58]
[Step 4/6] Ensure dependencies are up-to-date (14s)
[19:55:12]
[Step 4/6] Ensure generated code is up-to-date (4m:52s)
[20:00:04]
[Step 4/6] Lint (13m:47s)
[20:13:52]
[Step 4/6] Test web UI (20s)
[20:14:12]
[Step 4/6] Process exited with code 0
```
In the 29m build you reference, 11m went to ensure that the generated code was up to date. It is true that the lint itself took over 15m. Look at the timings on this master build [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=1662212&buildTypeId=Cockroach_UnitTests_Check&tab=buildLog&_focus=166#_state=166):

```
Step 4/6: make lint (Command Line) (25m:28s)
[18:10:41]
[Step 4/6] Starting: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/build/teamcity-check.sh
[18:10:41]
[Step 4/6] in directory: /home/agent/work/.go/src/github.com/cockroachdb/cockroach
[18:10:41]
[Step 4/6] Prepare environment
[18:10:41]
[Step 4/6] Ensure dependencies are up-to-date (15s)
[18:10:57]
[Step 4/6] Ensure generated code is up-to-date (9m:35s)
[18:20:33]
[Step 4/6] Lint (15m:16s)
[18:35:49]
[Step 4/6] Test web UI (20s)
[18:36:10]
[Step 4/6] Process exited with code 0
```

**Comment by ajwerner** [comment]
In short, I don't believe that this change will have a meaningful impact on the runtime of the lint stage, not the 5-15% we anticipated for the first version. If anything I expect it to have a net negative impact because we won't be re-type checking every package twice due to the separate execution of `shadow`

**Comment by ajwerner** [comment]
@knz is there anything else you want on this PR? Would you like me to find an additional pair of eyes to give it a look?

**Comment by knz** [comment]
No further comment from me. As I said before from my perspective this is good to go.

**Comment by ajwerner** [comment]
Thanks!

bors r=knz

**Comment by tamird** [comment]
This is neat! Looking at the current state of these utilities in CRDB and at https://github.com/dominikh/go-tools/blob/master/cmd/staticcheck/staticcheck.go, it seems like most of staticcheck (all but `unused`) can also be folded into roachvet, potentially reducing some more duplicated work.

Finally, the comments [here](https://github.com/cockroachdb/cockroach/blob/02d9a94bf5cd94a83a48d72081fd28c9b1569cb8/pkg/testutils/lint/lint_test.go#L90-L111) still refer to megacheck, which I gather is long dead.

**Pull request merged**
