### PR TITLE
catalog: change hash-sharded indexes to use md5

### LINKED ISSUE #91109: sql: non-uniform hash-sharded index with power-of-2 number of buckets
Looks like the hash bucket calculation `mod(fnv32(crdb_internal.datums_to_bytes(x, y)), z)` is poorly distributed when x and y are INT8 columns with equal values, and z is a power of 2. For example:

```sql
CREATE TABLE ijk (i, j, k) AS SELECT x, x, x FROM generate_series(0, 1048575) s (x);
CREATE INDEX ON ijk (i) USING HASH WITH BUCKET_COUNT = 8;
CREATE INDEX ON ijk (i, j) USING HASH WITH BUCKET_COUNT = 8;
CREATE INDEX ON ijk (i, j, k) USING HASH WITH BUCKET_COUNT = 8;
SELECT crdb_internal_i_shard_8, COUNT(crdb_internal_i_shard_8) FROM ijk GROUP BY 1 ORDER BY 1;
SELECT crdb_internal_i_j_shard_8, COUNT(crdb_internal_i_j_shard_8) FROM ijk GROUP BY 1 ORDER BY 1;
SELECT crdb_internal_i_j_k_shard_8, COUNT(crdb_internal_i_j_k_shard_8) FROM ijk GROUP BY 1 ORDER BY 1;
```

Gives:

```
demo@127.0.0.1:26257/defaultdb> SELECT crdb_internal_i_shard_8, COUNT(crdb_internal_i_shard_8) FROM ijk GROUP BY 1 ORDER BY 1;
  crdb_internal_i_shard_8 | count
--------------------------+---------
                        0 | 131071
                        1 | 131071
                        2 | 131072
                        3 | 131072
                        4 | 131073
                        5 | 131073
                        6 | 131072
                        7 | 131072
(8 rows)


Time: 770ms total (execution 770ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> SELECT crdb_internal_i_j_shard_8, COUNT(crdb_internal_i_j_shard_8) FROM ijk GROUP BY 1 ORDER BY 1;
  crdb_internal_i_j_shard_8 | count
----------------------------+---------
                          1 | 376905
                          3 |  16348
                          5 | 638976
                          7 |  16347
(4 rows)


Time: 836ms total (execution 835ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> SELECT crdb_internal_i_j_k_shard_8, COUNT(crdb_internal_i_j_k_shard_8) FROM ijk GROUP BY 1 ORDER BY 1;
  crdb_internal_i_j_k_shard_8 | count
------------------------------+---------
                            0 | 131073
                            1 | 131071
                            2 | 131071
                            3 | 131072
                            4 | 131072
                            5 | 131073
                            6 | 131072
                            7 | 131072
(8 rows)


Time: 976ms total (execution 976ms / network 0ms)
```

The hash-sharded index is still unevenly distributed with 16 buckets:

```
demo@127.0.0.1:26257/defaultdb> CREATE INDEX ij16 ON ijk (i, j) USING HASH WITH BUCKET_COUNT = 16;
CREATE INDEX


Time: 5.629s total (execution 5.629s / network 0.000s)

demo@127.0.0.1:26257/defaultdb> SELECT crdb_internal_i_j_shard_16, COUNT(crdb_internal_i_j_shard_16) FROM ijk GROUP BY 1 ORDER BY 1;
  crdb_internal_i_j_shard_16 | count
-----------------------------+---------
                           1 | 184357
                           3 |  12224
                           5 | 487461
                           7 |   8174
                           9 | 192548
                          11 |   4124
                          13 | 151515
                          15 |   8173
(8 rows)


Time: 819ms total (execution 819ms / network 0ms)
```

With 14 it's evenly distributed across half the buckets:

```
demo@127.0.0.1:26257/defaultdb> CREATE INDEX ij14 ON ijk (i, j) USING HASH WITH BUCKET_COUNT = 14;
CREATE INDEX


Time: 6.913s total (execution 6.912s / network 0.000s)

demo@127.0.0.1:26257/defaultdb> SELECT crdb_internal_i_j_shard_14, COUNT(crdb_internal_i_j_shard_14) FROM ijk GROUP BY 1 ORDER BY 1;
  crdb_internal_i_j_shard_14 | count
-----------------------------+---------
                           1 | 149778
                           3 | 150045
                           5 | 149398
                           7 | 149531
                           9 | 150521
                          11 | 149379
                          13 | 149924
(7 rows)


Time: 846ms total (execution 846ms / network 0ms)
```

With a prime number of buckets it's fine:

```
demo@127.0.0.1:26257/defaultdb> CREATE INDEX ij17 ON ijk (i, j) USING HASH WITH BUCKET_COUNT = 17;
CREATE INDEX


Time: 6.533s total (execution 6.532s / network 0.000s)

demo@127.0.0.1:26257/defaultdb> SELECT crdb_internal_i_j_shard_17, COUNT(crdb_internal_i_j_shard_17) FROM ijk GROUP BY 1 ORDER BY 1;
  crdb_internal_i_j_shard_17 | count
-----------------------------+--------
                           0 | 61416
                           1 | 61852
                           2 | 61537
                           3 | 61534
                           4 | 61605
                           5 | 62347
                           6 | 61745
                           7 | 61611
                           8 | 61527
                           9 | 61494
                          10 | 62198
                          11 | 61752
                          12 | 61749
                          13 | 61353
                          14 | 61502
                          15 | 61921
                          16 | 61433
(17 rows)


Time: 849ms total (execution 849ms / network 0ms)
```

This example is (admittedly) contrived, but there could be other cases like this. Maybe we should default to creating a prime number of buckets?

Jira issue: CRDB-21107

Epic CRDB-27601

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/91109

Release note (sql change): The hash function used by hash-sharded indexes was changed to
`mod(fnv32(md5(crdb_internal.datums_to_bytes(columns))), bucket_count)`. (Previously, it did not use `md5`.) This change was made to enhance the uniformity of bucket distribution in cases when the bucket count is a power of 2, and the columns being sharded have numerical properties that make the fnv32 function return values with a non-uniformly distributed modulus.

### CODE REVIEW

**Comment by michae2** [comment]
Thank you for looking at this! Some things I'm wondering:
- Do we still need `fnv32` if we're also using `md5`? I guess Andrew was trying `fnv32(sha256(...))` so maybe that's what you're thinking?
- Is there any upgrade concern here? Or restore concern? I guess restores should already have the old formula baked into the saved `CREATE TABLE`?

**Comment by rafiss** [comment]
> Do we still need fnv32 if we're also using md5? I guess Andrew was trying fnv32(sha256(...)) so maybe that's what you're thinking?

we do unfortunately, since `md5` (and `shaX`) return a string.

> Is there any upgrade concern here? Or restore concern? I guess restores should already have the old formula baked into the saved CREATE TABLE?

there may be - i was hoping some tests would tell me, but they have not. so i will do a bit more investigation.

**Comment by rafiss** [comment]
@michae2 this is RFAL. i've confirmed that this is safe for restores and upgrades. the `MakeHashShardComputeExpr` function is only called by the gateway node at the time of executing a CREATE statement.

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109374#-:-NdfTcNy90E_Bjl7XzoZ:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2)

**Review by michae2 — APPROVED** [review]
:lgtm:

Could you add one (or both) of the poorly-distributed examples from #91109 to `pkg/sql/logictest/testdata/logic_test/hash_sharded_index`?

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109374#-:-NdfVKdb4NKXvYm0COpl:biydjwt)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @rafiss)

**Comment by rafiss** [comment]
> Could you add one (or both) of the poorly-distributed examples from https://github.com/cockroachdb/cockroach/issues/91109 to pkg/sql/logictest/testdata/logic_test/hash_sharded_index?

good idea. done!

tftrs!

bors r+

**Pull request merged**
