### PR TITLE
sql/catalog/descs: unify and fix TxnWithExecutor

### PR DESCRIPTION
**Pull request by ajwerner**
The code was bogus before because it was trying to use the transaction
after committing. That's not allowed. Also, the retry behavior was unsound.
We make it sound by tracking when the invariant violation has happened
and propagate that up for a true restart.

Release justification: fixes very broken and needed code

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
@ZhouXing19 and/or @rafiss can y'all review this? I'm reasonably pleased with where it ended up. @maryliag would very much like https://github.com/cockroachdb/cockroach/pull/86433 merged ASAP.

**Review by ZhouXing19 — COMMENTED** [review]
Thanks for fixing up the new interface, and LGTM! But maybe we want a stamp from @rafiss too.

Just wanted to confirm my understanding of some critical changes in this PR:
1. Previously there were 2 sets of logic for validating the schema changes, one in `CollectionFactory.Txn()` and the other in `ex.commitSQLTransactionInternal()`. And even worse, in `CollectionFactory.TxnWithExecutor()`, we used both of them. We now unify them to the latter one.
2. The retry invoked by a two-version invariant violation has been changed to first roll back the current `kv.Txn`, then propagate a retry error to the sql layer, and finally trigger the conn executor to reset the txn. 

Do I understand it correctly?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86427#-:-N9qn2RLAs6PyUSXpRog:bu88q7v)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @miretskiy)

___
*[`-- commits` line 20 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86427#-N9qmxOw-mbNp9aTJPVA):*
nit: release justification is missing

**Review by ZhouXing19 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86427)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @miretskiy)

___
*[`pkg/sql/internal.go` line 1042 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86427#-N9qurDBDgT0_7up7_U8:-N9qurDBDgT0_7up7_U9:bczld8d) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ec5ae08e878b8c4a70638f1a23c3a914c2d68e5/pkg/sql/internal.go#L1042)):*
> ```Go
> 	}
> 	defer ex.close(ctx, externalTxnClose)
> 	return ex.commitSQLTransactionInternal(ctx)
> ```

Should we call `ex.commitSQLTransaction()` instead? Otherwise we're not applying the changes to provoke conn executor to reset txn when the two-version invariant is violated.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86427)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @miretskiy, and @ZhouXing19)

___
*[`pkg/sql/internal.go` line 1042 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86427#-N9qurDBDgT0_7up7_U8:-N9qz1Rn-rtlD7jqVB1A:b4z1jx8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ec5ae08e878b8c4a70638f1a23c3a914c2d68e5/pkg/sql/internal.go#L1042)):*
> Otherwise we're not applying the changes to provoke conn executor to reset txn when the two-version invariant is violated.

The internal executor in question doesn't live past this function call, so what value does resetting its transaction have?

**Comment by ajwerner** [comment]
> The retry invoked by a two-version invariant violation has been changed to first roll back the current kv.Txn, then propagate a retry error to the sql layer, and finally trigger the conn executor to reset the txn.

This isn't quite right. We always rolled back the transaction when the invariant was violated, we just did it with a more confusing API. Before this change, we called `(*kv.Txn).CleanupOnError` and we had to synthesize an error to pass it. We then depended on how that error was handled implicitly rather than explicitly, but we also depended on an accompanying bool return value. 

See `CleanupOnError`:
https://github.com/cockroachdb/cockroach/blob/00af7d7089d90ccaf9d12724872881064c68e9aa/pkg/kv/txn.go#L691-L700

And `Rollback`:
https://github.com/cockroachdb/cockroach/blob/00af7d7089d90ccaf9d12724872881064c68e9aa/pkg/kv/txn.go#L835-L840

The code doesn't change the behavior in `CheckTwoVersionInvariant`, it just makes the way the result is communicated more explicit; rather than relying on a combination of a fake restart error and a boolean, it relies on an explicit error which can be detected.

**Review by rafiss — APPROVED** [review]
nice! thanks for the new datadriven test too

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86427#-:-N9r7E7H0Tlelid4asQp:bhpetvg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @ZhouXing19)

___
*[`-- commits` line 20 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86427#-N9qmxOw-mbNp9aTJPVA):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

nit: release justification is missing
</blockquote></details>

i believe the justification is only needed in the PR (but confusingly there is a git hook that adds it to the commit msg too)

**Review by ZhouXing19 — APPROVED** [review]
I see, thanks for the detailed explanation! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86427#-:-N9rFcdd4lizO_HRZRVL:b-9uud46)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @miretskiy, and @ZhouXing19)

___
*[`pkg/sql/internal.go` line 1042 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86427#-N9qurDBDgT0_7up7_U8:-N9rFZuUDkAP3bUct1xq:bwyc7um) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ec5ae08e878b8c4a70638f1a23c3a914c2d68e5/pkg/sql/internal.go#L1042)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> Otherwise we're not applying the changes to provoke conn executor to reset txn when the two-version invariant is violated.

The internal executor in question doesn't live past this function call, so what value does resetting its transaction have? 
</blockquote></details>

Ah I see, sorry I misunderstood.

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Pull request merged**
