### PR TITLE
colexechash: fix an internal error with distinct mode

### LINKED ISSUE #74795: ON CONFLICT leads to unexpected error from the vectorized engine: runtime error: index out of range [4] with length 4
**Describe the problem**

CRDB returns an internal error with the below panic stack trace:
```
ERROR: internal error: unexpected error from the vectorized engine: runtime error: index out of range [4] with length 4
SQLSTATE: XX000                                                                                                                                                                       
DETAIL: stack trace:                                                                              
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:88: func1()
/usr/local/go/src/runtime/panic.go:965: gopanic()                                   
/usr/local/go/src/runtime/panic.go:88: goPanicIndex()                                      
/go/src/github.com/cockroachdb/cockroach/pkg/col/coldata/bytes.go:131: Get()                            
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/colexechash/hashtable_distinct.eg.go:6248: checkColForDistinctTuples()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/colexechash/hashtable.go:531: checkColsForDistinctTuples()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/colexechash/hashtable.go:635: CheckBuildForDistinct()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/colexechash/hashtable.go:456: FindBuckets()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/colexechash/hashtable.go:471: RemoveDuplicates()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/colexechash/hashtable.go:383: DistinctBuild()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/unordered_distinct.go:105: Next()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/disk_spiller.go:197: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:91: CatchVectorizedRuntimeError()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/disk_spiller.go:195: Next()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/operator.go:137: Next()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/is_null_ops.eg.go:67: Next()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/operator.go:137: Next()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/is_null_ops.eg.go:67: Next()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase/simple_project.go:125: Next()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:98: Next()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:261: next()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:286: nextAdapter()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:91: CatchVectorizedRuntimeError()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:292: Next()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/row_source_to_plan_node.go:76: Next()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/insert.go:221: BatchedNext()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_batch.go:173: startExec()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:509: func2()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:112: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:289: visitInternal()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:79: visit()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:43: walkPlan()
```

It seems that this happens only when inserting very specific data into the table; many variations of the data inserted result in successful query execution. 
It also seems that removing the ON CONFLICT DO NOTHING clause or the index result in not hitting the problem.
The bug is NOT present on 21.1.13 but exists in 21.2.0-4

**To Reproduce**

1. `cockroach start-single-node --insecure --store=type=mem,size=1GB`
2. run the provided query (e.g. `cat bug.sql | cockroach sql --url postgresql://root@localhost:26257/defaultdb?sslmode=disable` )

**Expected behavior**
The query succeeds

**Additional data / screenshots**
```
cat > bug.sql <<EOF
BEGIN;                                                
CREATE SCHEMA auth;                          
CREATE TABLE auth.mytable (                 
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
    account_id TEXT NOT NULL,                       
    permission TEXT NOT NULL,                  
    creation_timestamp TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC') NOT NULL,
    creation_request_id TEXT UNIQUE NOT NULL,                        
    deletion_timestamp TIMESTAMP,
    deletion_request_id TEXT UNIQUE
);       
CREATE UNIQUE INDEX account_id_permission_deletion_timestamp ON auth.mytable USING BTREE (account_id, permission, deletion_request_id) ;
COMMIT;        
                                                
BEGIN;   
INSERT INTO                                                                                                                               
auth.mytable                                                                                                            
(account_id, permission, creation_request_id)                                                                         
VALUES                                                                                                                              
('1332952395110132214', '/access_control_api.*', '1'),                                                                                
('1332952395110132214', '/audit_api.*', '2'),                                                                               
('1332952395110132214', '/core_api.*', '3'),                                                                                  
('1332952395110132214', '/data_loader_api.*', '4'),                                                                             
('1332952395110132214', '/multi_entity_api.*', '5'),                                                                
('1332952395110132214', '/payment_hub.*', '6'),                                                                                 
('1332952395110132214', '/products_api.*', '7')                                                                            
ON CONFLICT (account_id, permission, deletion_request_id) DO NOTHING;
COMMIT;
EOF
```

Note that even minor changes in the values above for the first or second column result in the query succeeding.

**Environment:**
 - CockroachDB version 21.2.0 - 21.2.4
 - Server OS: Linux / Ubuntu
 - Client app `cockroach sql` , `psql`

I am new to the CockroachDB codebase but if this is a simple bug for which you could give me some pointers, I would be interested in fixing.

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexechash: fix an internal error with distinct mode**

This commit fixes a bug with the hash table when it is used by the
unordered distinct when NULLs are treated as different. This is the case
when UPSERT or INSERT ... ON CONFLICT queries have to perform
`upsert-distinct-on` operation.

The problem was that we were updating some internal state (`GroupID`
slice responsible for tracking what is the current duplicate candidate
for each row being probed) in more cases than necessary. The code path
in question is used for two purposes:
- first, when we're removing the duplicates from within the batch,
without looking at the state of the hash table at all. In this case we
do want the update mentioned above;
- next, when the batch only contains unique rows, we want to remove the
duplicates when comparing against the hash table. In this case we do not
want the update.

The bug is fixed by refactoring the code to not update the internal
state at all; instead, we now rely on the `distinct` flag for each row
to tell us that the row is distinct within the batch, and we then
correctly populate `HeadID` value for it (which was the ultimate goal
all the time, and previously we used `GroupID` value as an
intermediary).

This mistake would not result in incorrect results (because `distinct`
flag is still marked correctly) and could only result in an internal
error due to index out of bounds. In particular, for the error to occur
the last row in the vectorized batch must have a NULL value in any
column (except for the last one) used for the distinctness check.

Fixes: #74795.

Release note (bug fix): Previously, CockroachDB could encounter an
internal error when performing UPSERT or INSERT ... ON CONFLICT queries
in some cases when the new rows contained NULL values (either NULLS
explicitly specified or NULLs used since some columns were omitted).

**colexechash: cleanup the previous commit**

The idea behind this commit is to remove some dead code (and actually get
a minor performance improvement) by skipping the check of a conditional
that is always true as well as removing another conditional that is
always false.

We chose to not squash this commit into the previous one because the
latter will be backported, and we want to reduce the amount of code
changes for the backport.

Release note: None

**colexectestutils: increase test coverage by randomizing batch length**

We are already randomizing the max batch size used in a run of our unit
tests; however, previously it would be fixed for a single run. This
commit makes it so that on each batch produced by our test operators we
independently decide what length to use - with 50% chance we keep on
using the maximum while in the remaining cases we'll pick a random
length that doesn't exceed the maximum.

Release note: None

**colexechash: remove some dead code**

This commit takes advantage of the observation that `probeSel` argument
in some templated function calls is never `nil` and removes some code
that was present for the case when it is `nil`.

Release note: None

**colexechash: combine two conditionals into one in distinct mode**

Previously, we had the code of the form
```
if keyID != 0 {
...
}
if keyID == 0 {
...
}
```
being generated for the distinct mode. This commit adjusts the template
to generate
```
if keyID != 0 {
...
} else {
...
}
```
instead.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I intend to backport only the first commit.

It's also possible that the increase in the test coverage added in the second commit might expose some other problems (either bugs or test setup issues), but I think it is RFAL.

**Review by rharding6373 — CHANGES_REQUESTED** [review]
I have mostly a few trying-to-follow-template code kind of questions. Thanks for the quick turnaround on this issue, and leading the collaborative session on it.

> Reviewed 4 of 4 files at r1, 2 of 2 files at r2, 4 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74825#-:-MtKvSEM4qwnnq0D52l3:bqreslr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[pkg/sql/colexec/colexechash/hashtable_distinct.eg.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74825#-MtKqGZF0fNEqoOiix8m:-MtKqGZF0fNEqoOiix8n:b-8ls2mm) ([raw file](https://github.com/cockroachdb/cockroach/blob/786861744d4df5e293cf26175761c8d76bbbf94b/pkg/sql/colexec/colexechash/hashtable_distinct.eg.go#L112)):*
> ```Go
> 										}
> 									}
> 									if keyID == 0 {
> ```

Does this change mark rows with NULLs as distinct? I don't fully understand why this change is here.
___
*[pkg/sql/colexec/colexechash/hashtable_tmpl.go, line 307 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74825#-MtKjxiD7S8cNT2QiUXl:-MtKjxiD7S8cNT2QiUXm:b-wo04v2) ([raw file](https://github.com/cockroachdb/cockroach/blob/786861744d4df5e293cf26175761c8d76bbbf94b/pkg/sql/colexec/colexechash/hashtable_tmpl.go#L307)):*
> ```Go
> 
> // checkColAgainstItselfForDistinct is similar to checkCol, but it probes the
> // vector against itself for the purposes of the unordered distinct.
> ```

nit: s/of the unordered distinct/of finding matches to unordered distinct columns
___
*[pkg/sql/colexec/colexechash/hashtable_tmpl.go, line 87 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74825#-MtKuUMK3yA2MrYwKdX9:-MtKuUMK3yA2MrYwKdXA:baril2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/929a5807ab44800406babd1ba3911e7351cbb9ba/pkg/sql/colexec/colexechash/hashtable_tmpl.go#L87)):*
> ```Go
> // matched tuples as "deleted" so they won't get matched again.
> func _CHECK_COL_BODY(
> 	_GLOBAL interface{},
> ```

What does the _GLOBAL do?

**Review by yuzefovich — COMMENTED** [review]
I've refactored the first commit to make the code cleaner as well as added a WIP second commit that we might squash into the first one.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74825#-:-MtLiC8ZAluGRY9BNyhh:b3pdv9k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[pkg/sql/colexec/colexechash/hashtable_distinct.eg.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74825#-MtKqGZF0fNEqoOiix8m:-MtLd9JF40_LubxApcLU:b-w049td) ([raw file](https://github.com/cockroachdb/cockroach/blob/786861744d4df5e293cf26175761c8d76bbbf94b/pkg/sql/colexec/colexechash/hashtable_distinct.eg.go#L112)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Does this change mark rows with NULLs as distinct? I don't fully understand why this change is here.
</blockquote></details>

Generally speaking `keyID == 0` indicates that there was no hash match for the current row (or we have reached the end of the hash chain to which the current row belong without finding matches). This code block has just been added because we now propagate `.SelectDistinct` flag in all functions for the unordered distinct (previously we didn't do it one place).

However, this newly-added generated code is actually dead because `keyID` will never be 0 when probing the batch against itself - each row at least has a hash match with itself (and possibly with other rows), and once we find a match for a particular row, we remove it from being checked further. Only if we kept on checking that row further we could reach a case of `keyID == 0`.

I've just added a second commit that takes advantage of this observation. I'm thinking about squashing it into the first commit, but curious to hear your thoughts whether that second commit makes sense.
___
*[pkg/sql/colexec/colexechash/hashtable_tmpl.go, line 87 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74825#-MtKuUMK3yA2MrYwKdX9:-MtLk2yA8AxLfBwae_jx:bzf1v5s) ([raw file](https://github.com/cockroachdb/cockroach/blob/929a5807ab44800406babd1ba3911e7351cbb9ba/pkg/sql/colexec/colexechash/hashtable_tmpl.go#L87)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

What does the _GLOBAL do?
</blockquote></details>

That's a good question. It is a trick to pass down the NotEqual overload (represented as `twoArgsResolvedOverloadInfo` object) from one template to another. The difficulty is that the overload is at a "different path" in two template callsites. I added a comment about it, please let me know if it makes sense.

**Comment by yuzefovich** [comment]
I was able to construct a unit regression test (based on hash collisions). Also, the benchmarks of all commits are [here](https://gist.github.com/yuzefovich/f563e9ea889eab65c35badf02ce55a9a).

**Review by mgartner — APPROVED** [review]
:lgtm: Nice work!

I still don't fully understand the GroupID part - is there a good explanation anywhere? The comment for GroupID mentions joins, and it's not obvious how it works for distinct operators.

Good to see a performance boost from this too! Any ideas why this one case regressed:

```
Distinct/Unordered/hasNulls=true/newTupleProbability=0.001/rows=262144/ordCols=0/type=int-24       11.8ms ± 1%    14.0ms ± 1%  +18.42%
```

Did you look into whether it was possible to short circuit when we've determined one column is unique to avoid checking successive columns? (Not expecting this in this PR, just curious.)

> Reviewed 1 of 4 files at r1, 6 of 6 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, 4 of 4 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74825#-:-MtO0ybW0cdj1GfsUZva:b1ykkry)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rharding6373 and @yuzefovich)

___
*[-- commits, line 30 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74825#-MtNwtGPC0Y_YMveAAP2):*
nit: "in not" should be "not in" I think
___
*[-- commits, line 35 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74825#-MtNx0WRC9BnAJs2Mb2b):*
nit: missing a `)` to close the `(`
___
*[pkg/sql/colexec/distinct_test.go, line 306 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74825#-MtNyZZRCaH9Vv-L4TvS:-MtNyZZRCaH9Vv-L4TvT:b-6uw6he) ([raw file](https://github.com/cockroachdb/cockroach/blob/5190997e2ee737a29a98565d1d9e2fe50d0bbd68/pkg/sql/colexec/distinct_test.go#L306)):*
> ```Go
> 		// Tuples have been carefully constructed so that all of them had the
> 		// same hash, only one tuple among first three was inserted into the
> 		// hash table, and two of the last tuples were distinct. This is a
> ```

nit: did you mean "the last two tuples are distinct"?

**Review by rharding6373 — APPROVED** [review]
The second commit seems fine. My only concern is that it's better to keep the bug fix isolated and the rest of the optimizations/new behavior separate so that if it turns out there's a bug in the latter, we don't have to roll back the former, too. I think that's the main argument to not squash and keep the commit separate, like you've done for the other optimizations.

Benchmark looks good, but do you have any idea what happened to `Distinct/Unordered/hasNulls=true/newTupleProbability=0.001/rows=262144/ordCols=0/type=int-24`? It's definitely an outlier.

Overall, looks good. :lgtm: Nice job!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74825#-:-MtOomPTBy17vPYrYGqH:b-8suj37)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @rharding6373 and @yuzefovich)

___
*[-- commits, line 45 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74825#-MtOl8uADXVkNmUW7dsK):*
s/skiping/skipping
___
*[pkg/sql/colexec/colexechash/hashtable_tmpl.go, line 87 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74825#-MtKuUMK3yA2MrYwKdX9:-MtOog9-4Kir3fl4Sa8q:bjabcon) ([raw file](https://github.com/cockroachdb/cockroach/blob/929a5807ab44800406babd1ba3911e7351cbb9ba/pkg/sql/colexec/colexechash/hashtable_tmpl.go#L87)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

That's a good question. It is a trick to pass down the NotEqual overload (represented as `twoArgsResolvedOverloadInfo` object) from one template to another. The difficulty is that the overload is at a "different path" in two template callsites. I added a comment about it, please let me know if it makes sense.
</blockquote></details>

Thanks for the explanation and comment.
___
*[pkg/sql/colexec/colexechash/hashtable_tmpl.go, line 421 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74825#-MtOjK8d0B2el1ombZ5Q:-MtOjK8d0B2el1ombZ5R:b-p8l92g) ([raw file](https://github.com/cockroachdb/cockroach/blob/5190997e2ee737a29a98565d1d9e2fe50d0bbd68/pkg/sql/colexec/colexechash/hashtable_tmpl.go#L421)):*
> ```Go
> 			//     so we want to mark it as equal to itself only.
> 			// */}}
> 			ht.ProbeScratch.HeadID[toCheck] = toCheck + 1
> ```

This does seem cleaner. Nice!

**Review by yuzefovich — COMMENTED** [review]
Thanks for the reviews! I addressed all the nits and also added a new commit with more comments and an example. I intend to backport the first two commits (comments as well as the fix) without the commit I was thinking of squashing.

Please give the new first commit with comments a look to see whether it makes sense.

Re: benchmark regression: I wouldn't worry too much about it - the unordered distinct benchmarks have a [known](https://github.com/cockroachdb/cockroach/pull/69729#issuecomment-912187686) deficiency where we construct the input in fully ordered manner and run the unordered distinct on it, so it's not very representative. I'll probably revive some pieces of that PR later today.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74825#-:-MtPEa0s6CHiX7DPkyo4:be51pgy)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @rharding6373)

___
*[-- commits, line 45 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74825#-MtOl8uADXVkNmUW7dsK):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

s/skiping/skipping
</blockquote></details>

Done.

**Comment by yuzefovich** [comment]
Re: improvements: as part of the revival of #69729 I do wanna look into some more optimizations, including the one we mentioned during the collab session.

**Comment by yuzefovich** [comment]
I guess there is no point in backporting the commit with the comments, so I removed it from this PR, and we can discuss it separately.

bors r+

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 7 files at r11, 1 of 1 files at r13, 2 of 4 files at r14, 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74825#-:-MtPLQL31yH3AmbGDNPk:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @rharding6373 and @yuzefovich)

___
*[-- commits, line 47 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/74825#-MtPLA3XAG83bPWtD4p-):*
nit: you mean the first commit will be backported, correct?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74825)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rharding6373)

___
*[-- commits, line 47 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/74825#-MtPLA3XAG83bPWtD4p-):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: you mean the first commit will be backported, correct?
</blockquote></details>

Yeah, I meant "this commit" as the "former" and the "previous one" as the "latter".

**Pull request merged**
