### PR TITLE
sql: improve INSERT dependency tracking for UDFs and SPs

### LINKED ISSUE #102771: sql: udf insert schema dependency
When INSERT is enabled for UDFs, we should track dependencies for all table column that are being inserted. Here's an example:

```
CREATE TABLE t (a INT, b INT);

CREATE FUNCTION f(i INT, j INT) RETURNS RECORD AS
$$
  INSERT INTO t VALUES (i, j) RETURNING *;
$$ LANGUAGE SQL;

-- Dropping column b succeeds, even though function f depends on it.
ALTER TABLE t DROP COLUMN b;
```

Dropping a column that we have added since creating the insert function is ok, though:

```
CREATE TABLE t (a INT, b INT);

CREATE FUNCTION f(i INT, j INT) RETURNS RECORD AS
$$
  INSERT INTO t VALUES (i, j) RETURNING *;
$$ LANGUAGE SQL;

ALTER TABLE t ADD COLUMN c;

-- This is ok.
ALTER TABLE t DROP COLUMN c;
```

Jira issue: CRDB-27647
Epic CRDB-19496

### PR DESCRIPTION
**Pull request by mgartner**
#### sql/logictest: add tests for UDF dependency tracking with mutations

Release note: None

#### sql: track INSERT dependencies for UDFs and SPs

UDF and SP dependencies on tables and their columns through `INSERT`
statements are now tracked. Dropping or renaming these tables or
columns is prohibited while the UDF or SP exists.

Fixes #102771

Release note: None

#### sql/logictest: add tests for SP dependency tracking with mutations

These tests are identical to the tests in `udf_dep`, except the
functions have been replaced with procedures.

Release note: None

#### sql/logictest: add tests for UDF/SP with mutations and CASCADING drops

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
LGTM, but I'll defer to others for approval - only have a couple of questions for my own edification.

> Reviewed 11 of 11 files at r1, 16 of 16 files at r5, 6 of 6 files at r6, 11 of 11 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120773#-:-NtS_YZz7reBe58FJ1mQ:bf9gxwq)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @fqazi, and @mgartner)

___
*[`-- commits` line 7 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/120773#-NtSYPlAAVUg3DIsIOeV):*
Why do we only need to apply this to INSERTs and not UPDATEs / UPSERTs / DELETEs?
___
*[`pkg/sql/opt/optbuilder/mutation_builder.go` line 90 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/120773#-NtSZBcf2RD326z_HSwm:-NtSZBcf2RD326z_HSwn:b612eq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f39244f3d92f86393e8f84a53a2ecc3d07c484a/pkg/sql/opt/optbuilder/mutation_builder.go#L90)):*
> ```Go
> 	// It does not include columns that were explicitly given the value of
> 	// DEFAULT, e.g., INSERT INTO t VALUES (1, DEFAULT).
> 	defaultInsertCols opt.ColSet
> ```

Why do we not include "default insert columns" into deps?

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120773)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @fqazi, and @yuzefovich)

___
*[`-- commits` line 7 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/120773#-NtSYPlAAVUg3DIsIOeV):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Why do we only need to apply this to INSERTs and not UPDATEs / UPSERTs / DELETEs?
</blockquote></details>

I've updated the commit message to mention UPSERTs, since this commit applies to them too. There is remaining work for `UPDATE`s. I created #120836 to track this. Also see the TODO in `udf_deps` and `procedure_deps`. I don't think there is remaining work for DELETEs.
___
*[`pkg/sql/opt/optbuilder/mutation_builder.go` line 90 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/120773#-NtSZBcf2RD326z_HSwm:-NtWLYq50is0coLtnEy8:bharh31) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f39244f3d92f86393e8f84a53a2ecc3d07c484a/pkg/sql/opt/optbuilder/mutation_builder.go#L90)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Why do we not include "default insert columns" into deps?
</blockquote></details>

Do you mean columns given the explicit value of `DEFAULT`? It's because dropping the column would either break the routine (e.g., trying to insert too many columns into table, or trying to insert the wrong types), or change the semantics (another column now gets `DEFAULT` value). It also matches Postgres's behavior.

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 16 of 16 files at r5, 6 of 6 files at r6, 16 of 16 files at r9, 5 of 5 files at r10, 10 of 10 files at r11, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120773#-:-NtXtnTDEAPasLWBAVpC:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @fqazi, @mgartner, and @yuzefovich)

___
*[`pkg/sql/opt/optbuilder/mutation_builder.go` line 90 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/120773#-NtSZBcf2RD326z_HSwm:-NtXs3gc0J-wEumdT3ZH:b-igxfx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f39244f3d92f86393e8f84a53a2ecc3d07c484a/pkg/sql/opt/optbuilder/mutation_builder.go#L90)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Do you mean columns given the explicit value of `DEFAULT`? It's because dropping the column would either break the routine (e.g., trying to insert too many columns into table, or trying to insert the wrong types), or change the semantics (another column now gets `DEFAULT` value). It also matches Postgres's behavior.
</blockquote></details>

Could we call it `implicitInsertCols` or something instead to not get it confused with `DEFAULT`?
___
*[`pkg/sql/logictest/testdata/logic_test/procedure_deps` line 158 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/120773#-NtXtgaa9yGu6P37kjF9:-NtXtgaa9yGu6P37kjFA:bh6jor1) ([raw file](https://github.com/cockroachdb/cockroach/blob/450628312d832eb7964d59adbe2af7ac974f90f9/pkg/sql/logictest/testdata/logic_test/procedure_deps#L158)):*
> ```
> 
> # NOTE: Postgres allows this. We cannot until we can rewrite the column names in
> # the INSERT statement, or use column IDs instead.
> ```

[nit] `INSERT` -> `UPSERT`
___
*[`pkg/sql/logictest/testdata/logic_test/procedure_deps` line 201 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/120773#-NtXthhsB67jvQsDlvpm:-NtXthhsB67jvQsDlvpn:bh6jor1) ([raw file](https://github.com/cockroachdb/cockroach/blob/450628312d832eb7964d59adbe2af7ac974f90f9/pkg/sql/logictest/testdata/logic_test/procedure_deps#L201)):*
> ```
> 
> # NOTE: Postgres allows this. We cannot until we can rewrite the column names in
> # the INSERT statement, or use column IDs instead.
> ```

[nit] `INSERT` -> `UPSERT`
___
*[`pkg/sql/logictest/testdata/logic_test/udf_deps` line 149 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/120773#-NtXsZ_vD7j8a5EPSsSs:-NtXsZ_vD7j8a5EPSsSt:bh6jor1) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f39244f3d92f86393e8f84a53a2ecc3d07c484a/pkg/sql/logictest/testdata/logic_test/udf_deps#L149)):*
> ```
> 
> # NOTE: Postgres allows this. We cannot until we can rewrite the column names in
> # the INSERT statement, or use column IDs instead.
> ```

[nit] `INSERT` -> `UPSERT`
___
*[`pkg/sql/logictest/testdata/logic_test/udf_deps` line 192 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/120773#-NtXsjgPDZL2QF6asCgP:-NtXsjgPDZL2QF6asCgQ:bh6jor1) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f39244f3d92f86393e8f84a53a2ecc3d07c484a/pkg/sql/logictest/testdata/logic_test/udf_deps#L192)):*
> ```
> 
> # NOTE: Postgres allows this. We cannot until we can rewrite the column names in
> # the INSERT statement, or use column IDs instead.
> ```

[nit] `INSERT` -> `UPSERT`

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120773)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @fqazi, and @yuzefovich)

___
*[`pkg/sql/opt/optbuilder/mutation_builder.go` line 90 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/120773#-NtSZBcf2RD326z_HSwm:-Ntbe4Pl6AnuTdxLpRnm:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f39244f3d92f86393e8f84a53a2ecc3d07c484a/pkg/sql/opt/optbuilder/mutation_builder.go#L90)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Could we call it `implicitInsertCols` or something instead to not get it confused with `DEFAULT`?
</blockquote></details>

Good idea. Done.
___
*[`pkg/sql/logictest/testdata/logic_test/procedure_deps` line 158 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/120773#-NtXtgaa9yGu6P37kjF9:-NtbeCNA7tsdIdczsfXI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/450628312d832eb7964d59adbe2af7ac974f90f9/pkg/sql/logictest/testdata/logic_test/procedure_deps#L158)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] `INSERT` -> `UPSERT`
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/procedure_deps` line 201 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/120773#-NtXthhsB67jvQsDlvpm:-NtbeGkqCiJjratyoMht:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/450628312d832eb7964d59adbe2af7ac974f90f9/pkg/sql/logictest/testdata/logic_test/procedure_deps#L201)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] `INSERT` -> `UPSERT`
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_deps` line 149 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/120773#-NtXsZ_vD7j8a5EPSsSs:-NtbeRNWBcxSp_qtP0w2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f39244f3d92f86393e8f84a53a2ecc3d07c484a/pkg/sql/logictest/testdata/logic_test/udf_deps#L149)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] `INSERT` -> `UPSERT`
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_deps` line 192 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/120773#-NtXsjgPDZL2QF6asCgP:-NtbeRYo43df4uKqaQSS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f39244f3d92f86393e8f84a53a2ecc3d07c484a/pkg/sql/logictest/testdata/logic_test/udf_deps#L192)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] `INSERT` -> `UPSERT`
</blockquote></details>

Done.

**Review by DrewKimball — APPROVED** [review]
> Reviewed 13 of 13 files at r13, 10 of 10 files at r14, 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120773)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi and @yuzefovich)

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
