### PR TITLE
sql: add max open txns per node cluster setting

### LINKED ISSUE #54652: sql: add max active transactions
We should add a cluster setting and session variable that allows users to set a `MAX ACTIVE TRANSACTIONS.` This can help provide rough protection to the database from excessive workload. The value would default to infinite and be configurable to users. If a transaction would be sent to the database that exceeds the number of active max transactions, we would return a unique error to the clients. 

Jira issue: CRDB-3732

### PR DESCRIPTION
**Pull request by asubiotto**
This commit adds a sql.max_open_txns cluster setting that can be used to limit
the number of open txns per node. This setting is off by default (value of 0).
Any users with the admin role are not affected. Internal executor use is also
not affected.

If a new txn would exceed this limit, a pgerror is returned with the message
"sorry, too many open txns" with the ConfigurationLimitExceeded error code.

Release note (sql change): add the sql.max_open_txns cluster setting that
limits the number of open txns at one time. users with the admin role and
internal txns are not affected.

Closes #54652 

cc @a-entin

### CODE REVIEW

**Comment by a-entin** [comment]
Is the error numerically unique? A generic error ConfigurationLimitExceeded with a text reveling details is not actionable for the application perspective. It's an explicit requirement the cust shared. The error CODE must uniquely identify the condition. Upon this specific "limit exceeded" the application will enter a re-try loop. It is unreasonable to expect the application to parse text to determine the exact condition. Aside from being cumbersome, user visible message text can change

**Review by bdarnell — COMMENTED** [review]
Limits like this run the risk of deadlock (defeating our deadlock detector) if a user runs into the same kind of situation that motivates child transactions (#54633). @ajwerner would this feature ever be exposed to SQL users? If so, we may need to exempt child transactions from this limit. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55173#-:-MItctqN09-BBv4iZ3Nh:b-nhhvae)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/conn_executor.go, line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55173#-MIta28K8dqnINm2Rw3G:-MIta28K8dqnINm2Rw3H:bsh02ty) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6e61685a524e196ba955c1b3208cb913d0d420c/pkg/sql/conn_executor.go#L68)):*
> ```Go
> var noteworthyMemoryUsageBytes = envutil.EnvOrDefaultInt64("COCKROACH_NOTEWORTHY_SESSION_MEMORY_USAGE", 1024*1024)
> 
> const maxOpenTxnsClusterSettingName = "sql.max_open_txns"
> ```

The setting name should probably include something like `per_node` since that's the level at which the limit applies. 

We prefer to spell words in full in setting names instead of abbreviations like `txns`. The setting uses the word "open" while the metric uses the word "active"; be consistent. And I think we might prefer something like `sql.open_transactions.limit` but I'm not sure we have a very consistent convention for this. 
___
*[pkg/sql/conn_executor.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55173#-MItagnY2RiD_g6UDzZ_:-MItagnY2RiD_g6UDzZa:b-csts5w) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6e61685a524e196ba955c1b3208cb913d0d420c/pkg/sql/conn_executor.go#L75)):*
> ```Go
> 	maxOpenTxnsClusterSettingName,
> 	"the maximum number of open SQL transactions allowed on a gateway server "+
> 		"at once, disabled if 0. Note that this limit does not affect admin users "+
> ```

It does not affect admin and internal transactions, but it is affected by them. This means that in order to reliably avoid transaction-limit errors in your application you must add padding in this setting for any admin/internal transactions you may do on a regular basis. (is this something users can even know? Where do internal transactions come from?)

Alternately, we could replace the OpenTxn metric with one that only counts transactions that are subject to this limit (perhaps two metrics, one for all transactions and one only for those subject to the limit). 
___
*[pkg/sql/conn_executor_exec.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55173#-MItc8x0-6LNs5XXC7Kn:-MItc8x0-6LNs5XXC7Ko:b-2htuik) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6e61685a524e196ba955c1b3208cb913d0d420c/pkg/sql/conn_executor_exec.go#L104)):*
> ```Go
> 				// There are too many open transactions. Any users without an admin role
> 				// will be rejected. Note that this HasAdminRole check is done after the
> 				// metrics check because it's relatively more expensive.
> ```

This seems like something that could be cached. 
___
*[pkg/sql/conn_executor_exec.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55173#-MItdUwq4JbpOHK4sdWD:-MItdUwq4JbpOHK4sdWE:b-vqd143) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6e61685a524e196ba955c1b3208cb913d0d420c/pkg/sql/conn_executor_exec.go#L111)):*
> ```Go
> 					ev, payload = ex.makeErrEvent(
> 						errors.WithHint(
> 							pgerror.New(pgcode.ConfigurationLimitExceeded, "sorry, too many active transactions"),
> ```

Why are we returning an error instead of blocking until either a slot opens up or the connection is closed? Sending an error back to the client just puts the burden of correctly detecting and backing off on them, and since we can cheaply hold the connection open here it seems strictly better to do so. (Mostly. Unless the load on different nodes is imbalanced and bouncing an error back to the client gives them an opportunity to be reconnected to a different node on the retry. But in that case you'd really want to close the connection after returning the error to more reliably direct the client to a different node)
___
*[pkg/sql/conn_executor_test.go, line 960 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55173#-MItcRJ526QYUedH7czI:-MItcRJ526QYUedH7czJ:b-3fh9k3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6e61685a524e196ba955c1b3208cb913d0d420c/pkg/sql/conn_executor_test.go#L960)):*
> ```Go
> 
> 	openTx := func(db *gosql.DB) error {
> 		tx, err := db.Begin()
> ```

We need a test that implicit transactions are limited too.

**Comment by awoods187** [comment]
@asubiotto we will also need to provide a Prometheus endpoint for this cluster setting.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55173)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @bdarnell, and @jordanlewis)

___
*[pkg/sql/conn_executor_exec.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55173#-MItdUwq4JbpOHK4sdWD:-MJ4Kwya9RACMJuNRDd8:bn3ogfu) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6e61685a524e196ba955c1b3208cb913d0d420c/pkg/sql/conn_executor_exec.go#L111)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Why are we returning an error instead of blocking until either a slot opens up or the connection is closed? Sending an error back to the client just puts the burden of correctly detecting and backing off on them, and since we can cheaply hold the connection open here it seems strictly better to do so. (Mostly. Unless the load on different nodes is imbalanced and bouncing an error back to the client gives them an opportunity to be reconnected to a different node on the retry. But in that case you'd really want to close the connection after returning the error to more reliably direct the client to a different node)
</blockquote></details>

If we go with the blocking until a slot opens approach, how would we want that to interact with idle_in_session_timeout and idle_in_transaction_session_timeout?

**Comment by asubiotto** [comment]
Closing as stale, #57477 added the metric.

**Pull request closed without merging**
