### PR TITLE
sql: add count_rows aggregate function, remove star datum instance

### LINKED ISSUE #12615: sql: remove StarDatumInstance
In the following output, `render 1` is a star, which seems wrong. Not sure if this means we're actually rendering all the columns, but at the very least it's confusing output for the EXPLAIN command.

Originated from this conversation: https://reviewable.io/reviews/cockroachdb/cockroach/10146#-K_Bcg0mPxSRQgi1xXRB

```
root@:26257> EXPLAIN (exprs) SELECT 1+COUNT(*) FILTER (WHERE k > 5), MAX(k>5) FILTER (WHERE k > 5) FROM filter_test GROUP BY v;
+-------+---------------+-------------+-----------------------------------------------------------+
| Level |     Type      |    Field    |                        Description                        |
+-------+---------------+-------------+-----------------------------------------------------------+
|     0 | group         |             |                                                           |
|     0 |               | aggregate 0 |                                                         1 |
|     0 |               | aggregate 1 | count(*) FILTER (WHERE k > 5)                             |
|     0 |               | aggregate 2 | max(k > 5) FILTER (WHERE k > 5)                           |
|     0 |               | render 0    | [agg arg "1"] + [agg arg "count(*) FILTER (WHERE k > 5)"] |
|     0 |               | render 1    | [agg arg "max(k > 5) FILTER (WHERE k > 5)"]               |
|     1 | render/filter |             |                                                           |
|     1 |               | render 0    |                                                         1 |
|     1 |               | render 1    | *                                                         |
|     1 |               | render 2    | k > 5                                                     |
|     1 |               | render 3    | v                                                         |
|     2 | scan          |             |                                                           |
|     2 |               | table       | filter_test@primary                                       |
+-------+---------------+-------------+-----------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by RaduBerinde**
`COUNT(*)` is a special syntax for a function that's really not the same as
`COUNT`. We currently handle it by providing a dummy datum (`StarDatumInstance`)
as an input to `COUNT`. In DistSQL this means that we will actually transfer a
datum for each row between a table reader and an aggregator.

In this change we add a new `COUNT_ROWS()` aggregation function which takes no
arguments and counts how many times it is called. Some of the difficulty in the
DistSQL implementation is that we no longer have exactly one argument; we change
the protocol to accept an arbitrary number of arguments (currently 0 or 1,
perhaps one day we will have aggregation functions with multiple args).

We convert `COUNT(*)` to `COUNT_ROWS()` and remove the `StarDatumInstance` hack.
We also fix the incorrect handling of qualified stars: now things like
`COUNT(table.*)` or `COUNT(DISTINCT *)` fail instead of being handled
incorrectly (see #15750).

Performance was not the main driver for this change, but there is improvement:
about 1 second shaved off a 14 second `COUNT(*)` query on TPC-H.

Fixes #12615.

### CODE REVIEW

**Comment by knz** [comment]
Very nice. I am happy to this this code go.
Please check what is happening with the new render node in tests.
LGTM otherwise.

---

Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/select_name_resolution.go, line 134 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16533#-KmfiNdb5HVYuwGgIAnW:-KmfiNddi56Ul-RL_YfH:bk1fa5p) ([raw file](https://github.com/cockroachdb/cockroach/blob/964dfbcca7545fdf36744ce89a177ec80ddbc9e4/pkg/sql/select_name_resolution.go#L134)):*
> ```Go
> 				// count the number of rows; in this case * does NOT refer to a set of
> 				// columns. A * is invalid elsewhere (and will be caught by TypeCheck()).
> 				// Replace the function with COUNT_ROWS (which doesn't take any
> ```

`select count(t.*) from t` is valid and is using the regular count function (so it skips over null values).
Please add a TODO that explains this and mentions this need separate treatment.
The TODO text can also server a reminder that there is a difference between `select count(distinct t.*) from t,u` and `select count(distinct u.*) from t,u`.

---

*[pkg/sql/logictest/testdata/logic_test/aggregate, line 1007 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16533#-Kmfh0fjbHH7Edkz_UgC:-Kmfh0fkYtNg6sPzET2S:btluj2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/964dfbcca7545fdf36744ce89a177ec80ddbc9e4/pkg/sql/logictest/testdata/logic_test/aggregate#L1007)):*
> ```
> 1  render
> 1          render 0     v
> 1          render 1     count_rows()
> ```

Just curious, why is an extra render needed above the group node here?

---

*[pkg/sql/logictest/testdata/logic_test/aggregate, line 1098 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16533#-KmfhA7-FiWMJnt5fjGV:-KmfhA7-FiWMJnt5fjGW:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/964dfbcca7545fdf36744ce89a177ec80ddbc9e4/pkg/sql/logictest/testdata/logic_test/aggregate#L1098)):*
> ```
> 0  render
> 0          render 0     count_rows() FILTER (WHERE k > 5)
> 0          render 1     max(k > 5) FILTER (WHERE k > 5)
> ```

ditto

---

*[pkg/sql/logictest/testdata/logic_test/aggregate, line 1113 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16533#-KmfhGBTcqnq8yQD_9-b:-KmfhGBUp96gxJIjYCKu:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/964dfbcca7545fdf36744ce89a177ec80ddbc9e4/pkg/sql/logictest/testdata/logic_test/aggregate#L1113)):*
> ```
> ----
> 0  render                                                                               ("count(*) FILTER (WHERE k > 5)" int)
> 0          render 0     (count_rows() FILTER (WHERE k > 5))[int]
> ```

ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16533#-:-Kmfk24U0HzhIiKTQ7fA:b-j3o3ik)*

**Comment by RaduBerinde** [comment]
TFTR!

---

Review status: 19 of 20 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/sql/select_name_resolution.go, line 134 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16533#-KmfiNdb5HVYuwGgIAnW:-KmfqgdAWEMVu8E_GP7Y:b-1tjj23) ([raw file](https://github.com/cockroachdb/cockroach/blob/964dfbcca7545fdf36744ce89a177ec80ddbc9e4/pkg/sql/select_name_resolution.go#L134)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`select count(t.*) from t` is valid and is using the regular count function (so it skips over null values).
Please add a TODO that explains this and mentions this need separate treatment.
The TODO text can also server a reminder that there is a difference between `select count(distinct t.*) from t,u` and `select count(distinct u.*) from t,u`.
</blockquote></details>

Adding a TODO. Note that the semantics of the first one are murky. The thing is that COUNT doesn't take multiple arguments so it's not clear what `count(t.*)` means. Does it form a tuple with all the values? Because that tuple would never be NULL, even if all its members are NULL (so it would be equivalent to `COUNT(*)`). In PG the behavior seems to support this:

```
postgres=# select * from t;
select * from t;
 k  | v 
----+---
  1 | 1
  1 | 1
  1 | 2
  1 | 2
  1 | 3
    | 1
 10 |  
    |   
(8 rows)

postgres=# select count(t.*) from t;
select count(t.*) from t;
 count 
-------
     8       <---- includes last row which is NULL, NULL
(1 row)

postgres=# select count(*) from t;
select count(*) from t;
 count 
-------
     8
(1 row)
```

`count(distinct t.*)` does work as one would expect though.

---

*[pkg/sql/logictest/testdata/logic_test/aggregate, line 1007 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16533#-Kmfh0fjbHH7Edkz_UgC:-KmfuDLKdQFjwWkQLC4t:b-tog79d) ([raw file](https://github.com/cockroachdb/cockroach/blob/964dfbcca7545fdf36744ce89a177ec80ddbc9e4/pkg/sql/logictest/testdata/logic_test/aggregate#L1007)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Just curious, why is an extra render needed above the group node here?
</blockquote></details>

It renames the result column, from "count_rows()" to "count(*)". It's a bit unfortunate that we need a `renderNode` wherever we rename a column (e.g. using `AS`). Fortunately, this doesn't matter in DistSQL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16533#-:-KmfufhFPdEhoKM4zljw:b-814g8k)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/logictest/testdata/logic_test/aggregate, line 1113 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16533#-KmfhGBTcqnq8yQD_9-b:-KmfvKChLaSrd29BbnSa:bmgdsp4) ([raw file](https://github.com/cockroachdb/cockroach/blob/964dfbcca7545fdf36744ce89a177ec80ddbc9e4/pkg/sql/logictest/testdata/logic_test/aggregate#L1113)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

The rename is more visible here - note the different expressions `("count(*) FILTER (WHERE k > 5)" int)` vs `("count_rows() FILTER (WHERE k > 5)" int)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16533)*

**Comment by knz** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/select_name_resolution.go, line 134 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16533#-KmfiNdb5HVYuwGgIAnW:-KmgCODRhb0Wn0YsDzPS:bcpg9vb) ([raw file](https://github.com/cockroachdb/cockroach/blob/964dfbcca7545fdf36744ce89a177ec80ddbc9e4/pkg/sql/select_name_resolution.go#L134)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Adding a TODO. Note that the semantics of the first one are murky. The thing is that COUNT doesn't take multiple arguments so it's not clear what `count(t.*)` means. Does it form a tuple with all the values? Because that tuple would never be NULL, even if all its members are NULL (so it would be equivalent to `COUNT(*)`). In PG the behavior seems to support this:

```
postgres=# select * from t;
select * from t;
 k  | v 
----+---
  1 | 1
  1 | 1
  1 | 2
  1 | 2
  1 | 3
    | 1
 10 |  
    |   
(8 rows)

postgres=# select count(t.*) from t;
select count(t.*) from t;
 count 
-------
     8       <---- includes last row which is NULL, NULL
(1 row)

postgres=# select count(*) from t;
select count(*) from t;
 count 
-------
     8
(1 row)
```

`count(distinct t.*)` does work as one would expect though.
</blockquote></details>

:+1: thanks!

---

*[pkg/sql/logictest/testdata/logic_test/aggregate, line 1007 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16533#-Kmfh0fjbHH7Edkz_UgC:-KmgCSll_6W89QsACQFr:bek4im0) ([raw file](https://github.com/cockroachdb/cockroach/blob/964dfbcca7545fdf36744ce89a177ec80ddbc9e4/pkg/sql/logictest/testdata/logic_test/aggregate#L1007)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It renames the result column, from "count_rows()" to "count(*)". It's a bit unfortunate that we need a `renderNode` wherever we rename a column (e.g. using `AS`). Fortunately, this doesn't matter in DistSQL.
</blockquote></details>

Wait why is a render needed?! The column can be renamed simply by having the ResultColumns array contain the new name. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16533)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/logictest/testdata/logic_test/aggregate, line 1007 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16533#-Kmfh0fjbHH7Edkz_UgC:-KmgD73kTmD1Ya92BMRH:bs7dbkc) ([raw file](https://github.com/cockroachdb/cockroach/blob/964dfbcca7545fdf36744ce89a177ec80ddbc9e4/pkg/sql/logictest/testdata/logic_test/aggregate#L1007)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Wait why is a render needed?! The column can be renamed simply by having the ResultColumns array contain the new name. 
</blockquote></details>

Then maybe the code that removes `renderNode`s needs to do that. Note that this is a general issue, e.g.
```
root@:26257/> create table test.t (k INT PRIMARY KEY, v INT);
CREATE TABLE
root@:26257/> EXPLAIN (VERBOSE) select k, v FROM test.t;
+-------+------+-------+-------------+---------+----------+
| Level | Type | Field | Description | Columns | Ordering |
+-------+------+-------+-------------+---------+----------+
|     0 | scan |       |             | (k, v)  |          |
|     0 |      | table | t@primary   |         |          |
|     0 |      | spans | ALL         |         |          |
+-------+------+-------+-------------+---------+----------+
(3 rows)
root@:26257/> EXPLAIN (VERBOSE) SELECT k AS lol, v FROM test.t;
+-------+--------+----------+-------------+----------+----------+
| Level |  Type  |  Field   | Description | Columns  | Ordering |
+-------+--------+----------+-------------+----------+----------+
|     0 | render |          |             | (lol, v) |          |
|     0 |        | render 0 | test.t.k    |          |          |
|     0 |        | render 1 | test.t.v    |          |          |
|     1 | scan   |          |             | (k, v)   |          |
|     1 |        | table    | t@primary   |          |          |
|     1 |        | spans    | ALL         |          |          |
+-------+--------+----------+-------------+----------+----------+
(6 rows)
```

Or are you saying that we should add some special code to group.go to name this column with `count(*)` and avoid the renderNode in this particular case?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16533)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/logictest/testdata/logic_test/aggregate, line 1007 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16533#-Kmfh0fjbHH7Edkz_UgC:-KmgEcMrZICUqq-5MRw2:b-c1td9n) ([raw file](https://github.com/cockroachdb/cockroach/blob/964dfbcca7545fdf36744ce89a177ec80ddbc9e4/pkg/sql/logictest/testdata/logic_test/aggregate#L1007)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Then maybe the code that removes `renderNode`s needs to do that. Note that this is a general issue, e.g.
```
root@:26257/> create table test.t (k INT PRIMARY KEY, v INT);
CREATE TABLE
root@:26257/> EXPLAIN (VERBOSE) select k, v FROM test.t;
+-------+------+-------+-------------+---------+----------+
| Level | Type | Field | Description | Columns | Ordering |
+-------+------+-------+-------------+---------+----------+
|     0 | scan |       |             | (k, v)  |          |
|     0 |      | table | t@primary   |         |          |
|     0 |      | spans | ALL         |         |          |
+-------+------+-------+-------------+---------+----------+
(3 rows)
root@:26257/> EXPLAIN (VERBOSE) SELECT k AS lol, v FROM test.t;
+-------+--------+----------+-------------+----------+----------+
| Level |  Type  |  Field   | Description | Columns  | Ordering |
+-------+--------+----------+-------------+----------+----------+
|     0 | render |          |             | (lol, v) |          |
|     0 |        | render 0 | test.t.k    |          |          |
|     0 |        | render 1 | test.t.v    |          |          |
|     1 | scan   |          |             | (k, v)   |          |
|     1 |        | table    | t@primary   |          |          |
|     1 |        | spans    | ALL         |          |          |
+-------+--------+----------+-------------+----------+----------+
(6 rows)
```

Or are you saying that we should add some special code to group.go to name this column with `count(*)` and avoid the renderNode in this particular case?
</blockquote></details>

Wow interesting I never have seen this before. Please file the follow-up issue for the general simplification and assign it to me. The special case in `group.go` would be nice-to-have to ensure we don't degrade performance until the new issue is fixed. Your call.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16533)*

**Comment by RaduBerinde** [comment]
Review status: 17 of 20 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/logictest/testdata/logic_test/aggregate, line 1007 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16533#-Kmfh0fjbHH7Edkz_UgC:-KmgH1TfrwGCrnGd08GG:b-e9557c) ([raw file](https://github.com/cockroachdb/cockroach/blob/964dfbcca7545fdf36744ce89a177ec80ddbc9e4/pkg/sql/logictest/testdata/logic_test/aggregate#L1007)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Wow interesting I never have seen this before. Please file the follow-up issue for the general simplification and assign it to me. The special case in `group.go` would be nice-to-have to ensure we don't degrade performance until the new issue is fixed. Your call.
</blockquote></details>

Filed an issue and added a special case for `count_rows() -> count(*)`, now the renderNodes are elided when the query uses `count(*)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16533)*

**Pull request merged**
