### PR TITLE
sqlbase,cluster: add new FK representation, upgrade/downgrade methods, and a new cluster version

### PR DESCRIPTION
**Pull request by jordanlewis**
This PR adds the new FK representation to the descriptor protobufs, adds a new cluster version for the FK representation upgrade and introduces methods that upgrade and downgrade descriptors between the two representations.

See individual commits for details.

### CODE REVIEW

**Comment by jordanlewis** [comment]
Note: I am going to add unit tests for upgrade/downgrade idempotency next.

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39173)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @lucy-zhang)

___
*[pkg/sql/sqlbase/structured.go, line 856 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39173#-Ll3JA4NCQhS554PtXW7:-Ll3JA4NCQhS554PtXW8:bjhj5yb) ([raw file](https://github.com/cockroachdb/cockroach/blob/90486219f7bb93c6664aae584a201c4cab2382ab/pkg/sql/sqlbase/structured.go#L856)):*
> ```Go
> 		}
> 
> 		// XXX: Lucy, don't we want to *avoid* changing other table descriptors here?
> ```

Unless I'm missing something here, this doesn't change the other table descriptors; it puts the FK we just created on the appropriate index on the same table descriptor.
___
*[pkg/sql/sqlbase/structured.proto, line 49 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39173#-Ll3JtDWEi5U5ailg67o:-Ll3JtDWEi5U5ailg67p:b-pbvdcw) ([raw file](https://github.com/cockroachdb/cockroach/blob/90486219f7bb93c6664aae584a201c4cab2382ab/pkg/sql/sqlbase/structured.proto#L49)):*
> ```protobuf
>   }
> ```

Extra newline?

**Review by jordanlewis — COMMENTED** [review]
I added tests.

One question - @lucy-zhang do you think we should nix the new `OriginIndex` and `ReferencedIndex` fields now that we have the `UpgradedFromOriginReference` and `UpgradedFromReferencedReference` fields? :)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39173#-:-Ll9n0Gn5O2H6c5IsBJG:byjk5w5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[pkg/sql/sqlbase/structured.go, line 856 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39173#-Ll3JA4NCQhS554PtXW7:-Ll9mzBPCbnALaEPP4K5:b-qa4alu) ([raw file](https://github.com/cockroachdb/cockroach/blob/90486219f7bb93c6664aae584a201c4cab2382ab/pkg/sql/sqlbase/structured.go#L856)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Unless I'm missing something here, this doesn't change the other table descriptors; it puts the FK we just created on the appropriate index on the same table descriptor.
</blockquote></details>

Resolved offline.
___
*[pkg/sql/sqlbase/structured.proto, line 49 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39173#-Ll3JtDWEi5U5ailg67o:-Ll9mybd39Y2gHPSeEm7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/90486219f7bb93c6664aae584a201c4cab2382ab/pkg/sql/sqlbase/structured.proto#L49)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Extra newline?
</blockquote></details>

Done.

**Review by thoszhang — COMMENTED** [review]
Would we just get the index IDs from the other struct? That seems fine.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39173#-:-LlA6dFU3vvtJ9J0CK4t:b-4lawy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @lucy-zhang)

___
*[pkg/sql/sqlbase/structured.go, line 265 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/39173#-LlA7gue0YAphdyHpsNj:-LlA7gue0YAphdyHpsNk:bmuybjx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5cbe72017fe9ef6820b7907ad309670290809c2/pkg/sql/sqlbase/structured.go#L265)):*
> ```Go
> // ProtoGetter is a sub-interface of client.Txn that can fetch protobufs in a
> // transaction.
> type ProtoGetter interface {
> ```

Are there plans to start using this interface elsewhere, besides what we need to test right now? I think something like this is necessary but I'm concerned about introducing disorder if we don't use it in a principled way everywhere.
___
*[pkg/sql/sqlbase/structured.go, line 856 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/39173#-LlAA-3LED-UXPVuFyoS:-LlAA-3LED-UXPVuFyoT:b2amv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5cbe72017fe9ef6820b7907ad309670290809c2/pkg/sql/sqlbase/structured.go#L856)):*
> ```Go
> 		return false, desc, nil
> 	}
> 	// TODO (lucy): add check that all fields are actually populated
> ```

I'm not sure we actually need this now. If we get into a situation where this FK is not populated (and I can't think of a plausible bug/mistake that would cause this), the later validation will (indirectly) catch it. Maybe I'm forgetting why we originally wanted to do this.
___
*[pkg/sql/sqlbase/structured_test.go, line 1369 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/39173#-LlA8RDO-lFa838pjuuE:-LlA8RDP72-jEtT4o_uG:b-z6i0hl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5cbe72017fe9ef6820b7907ad309670290809c2/pkg/sql/sqlbase/structured_test.go#L1369)):*
> ```Go
> 
> // This test exercises the foreign key representation upgrade and downgrade
> // methods that were introduced in 19.2 to move foriegn key descriptors from
> ```

`foreign`
___
*[pkg/sql/sqlbase/structured_test.go, line 1424 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/39173#-LlA8snq38Smq5Pz0CvH:-LlA8snq38Smq5Pz0CvI:b9feuzi) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5cbe72017fe9ef6820b7907ad309670290809c2/pkg/sql/sqlbase/structured_test.go#L1424)):*
> ```Go
> 							OriginColumnIDs:     ColumnIDs{1},
> 							ReferencedColumnIDs: ColumnIDs{2},
> 							ReferencedTableID:   2,
> ```

nit: is there a reason to have the fields in this order? I would have expected `ReferencedColumnIDs` and `ReferencedTableID` to go in the opposite order.
___
*[pkg/sql/sqlbase/structured_test.go, line 1710 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/39173#-LlA9R_v7lozk_smLtNn:-LlA9R_v7lozk_smLtNo:bngok69) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5cbe72017fe9ef6820b7907ad309670290809c2/pkg/sql/sqlbase/structured_test.go#L1710)):*
> ```Go
> 				// The upgraded proto will also have a copy of the old foreign key
> 				// reference attached for each foreign key. Delete that for the purposes of
> 				// verifying equality.
> ```

Is there any downside to just keeping these extra fields (aside from the fact that it makes the test structs even more annoying and huge)?

**Review by yuzefovich — COMMENTED** [review]
This stuff seems quite tricky :)

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 5 of 5 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39173#-:-LlAI1iV6h3_R7ZKWA7j:b-mr49ox)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @lucy-zhang)

___
*[pkg/sql/sqlbase/structured.go, line 812 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39173#-LlAG2RJ4i_ARIauZNt7:-LlAG2RK2Equ_fVMXED8:b-jdi3c3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6746fe911539635461bd6d3af0f7584ab71fa13/pkg/sql/sqlbase/structured.go#L812)):*
> ```Go
> // maybeDowngradeForeignKeyRepresentation non-destructively downgrades the
> // receiver into the old foreign key representation (the ForeignKey
> // and ReferencedBy fields on IndexDescriptor if and only if the cluster version
> ```

[nit]: missing closing parenthesis.

**Review by jordanlewis — COMMENTED** [review]
> Would we just get the index IDs from the other struct? That seems fine.

Nevermind, this is not possible because the reference doesn't encode both origin and referenced index id. I left that alone for simplicity's sake.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39173#-:-LlCacIv0_MV5fVzaCe2:b-m70usy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @yuzefovich)

___
*[pkg/sql/sqlbase/structured.go, line 812 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39173#-LlAG2RJ4i_ARIauZNt7:-LlCWvu8BzcANw53Wr8j:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6746fe911539635461bd6d3af0f7584ab71fa13/pkg/sql/sqlbase/structured.go#L812)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: missing closing parenthesis.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured.go, line 265 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/39173#-LlA7gue0YAphdyHpsNj:-LlCWdt8D6ndKY6eafJ5:b-mph9an) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5cbe72017fe9ef6820b7907ad309670290809c2/pkg/sql/sqlbase/structured.go#L265)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Are there plans to start using this interface elsewhere, besides what we need to test right now? I think something like this is necessary but I'm concerned about introducing disorder if we don't use it in a principled way everywhere.
</blockquote></details>

No, I don't have any plans to do that. I agree that this is sketchy. I asked about it in #core and nobody had anything particularly good to say, so unless you really object, I'll leave this.
___
*[pkg/sql/sqlbase/structured.go, line 856 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/39173#-LlAA-3LED-UXPVuFyoS:-LlCWzIY4XUCY_gWimsw:b-5swf4v) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5cbe72017fe9ef6820b7907ad309670290809c2/pkg/sql/sqlbase/structured.go#L856)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

I'm not sure we actually need this now. If we get into a situation where this FK is not populated (and I can't think of a plausible bug/mistake that would cause this), the later validation will (indirectly) catch it. Maybe I'm forgetting why we originally wanted to do this.
</blockquote></details>

Done. I agree that it didn't seem necessary.
___
*[pkg/sql/sqlbase/structured_test.go, line 1369 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/39173#-LlA8RDO-lFa838pjuuE:-LlCXG345K1x3sCL5KgD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5cbe72017fe9ef6820b7907ad309670290809c2/pkg/sql/sqlbase/structured_test.go#L1369)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

`foreign`
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured_test.go, line 1424 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/39173#-LlA8snq38Smq5Pz0CvH:-LlCXHx2EjBwKc7bsgQX:be2t7ni) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5cbe72017fe9ef6820b7907ad309670290809c2/pkg/sql/sqlbase/structured_test.go#L1424)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

nit: is there a reason to have the fields in this order? I would have expected `ReferencedColumnIDs` and `ReferencedTableID` to go in the opposite order.
</blockquote></details>

Nope, just happenstance / carelessness - fixed everywhere.
___
*[pkg/sql/sqlbase/structured_test.go, line 1710 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/39173#-LlA9R_v7lozk_smLtNn:-LlCXXBi0lRTh1czso7A:b-g8u8n7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5cbe72017fe9ef6820b7907ad309670290809c2/pkg/sql/sqlbase/structured_test.go#L1710)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Is there any downside to just keeping these extra fields (aside from the fact that it makes the test structs even more annoying and huge)?
</blockquote></details>

Just the latter. It doesn't seem particularly important to me - I think messing this up would mess up the verification too.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39173)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @jordanlewis, @lucy-zhang, and @yuzefovich)

___
*[pkg/sql/sqlbase/structured.go, line 265 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/39173#-LlA7gue0YAphdyHpsNj:-LlIk55GBF83KDbXYxZo:b-900nyf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5cbe72017fe9ef6820b7907ad309670290809c2/pkg/sql/sqlbase/structured.go#L265)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

No, I don't have any plans to do that. I agree that this is sketchy. I asked about it in #core and nobody had anything particularly good to say, so unless you really object, I'll leave this.
</blockquote></details>

any reason for it to be exported?
___
*[pkg/sql/sqlbase/structured.proto, line 92 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/39173#-LlIkEvd1At47ZIN5Co5:-LlIkEvd1At47ZIN5Co6:b-43tbfg) ([raw file](https://github.com/cockroachdb/cockroach/blob/69410615848f63e08f64b6309f44c4fa48fd6298/pkg/sql/sqlbase/structured.proto#L92)):*
> ```protobuf
>   // is in a mixed-version state containing VersionTopLevelForeignKeys) was done
>   // without creating any accidental changes to the foreign key references.
>   optional uint32 origin_index = 10 [(gogoproto.nullable) = false, (gogoproto.casttype) = "IndexID", deprecated = true];
> ```

I might name these `legacy_` since otherwise `OriginIndex` looks like a perfect valid thing to use. AFAIK the `deprecated` annotation does nothing, right?

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39173)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lucy-zhang, and @yuzefovich)

___
*[pkg/sql/sqlbase/structured.go, line 265 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/39173#-LlA7gue0YAphdyHpsNj:-LlIopJc6ovTHYUTyerJ:b-ss7tb5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5cbe72017fe9ef6820b7907ad309670290809c2/pkg/sql/sqlbase/structured.go#L265)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

any reason for it to be exported?
</blockquote></details>

Nope. Done.
___
*[pkg/sql/sqlbase/structured.proto, line 92 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/39173#-LlIkEvd1At47ZIN5Co5:-LlIouHo4COxSOHWDpL1:b2lqelp) ([raw file](https://github.com/cockroachdb/cockroach/blob/69410615848f63e08f64b6309f44c4fa48fd6298/pkg/sql/sqlbase/structured.proto#L92)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I might name these `legacy_` since otherwise `OriginIndex` looks like a perfect valid thing to use. AFAIK the `deprecated` annotation does nothing, right?
</blockquote></details>

The deprecated annotation makes the field crossed out in my editor.

**Review by thoszhang — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39173)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @jordanlewis, @lucy-zhang, and @yuzefovich)

___
*[pkg/sql/sqlbase/structured.go, line 265 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/39173#-LlA7gue0YAphdyHpsNj:-LlJ0sZe0Aut5EHNNhlA:btq3e2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5cbe72017fe9ef6820b7907ad309670290809c2/pkg/sql/sqlbase/structured.go#L265)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Nope. Done.
</blockquote></details>

It's fine with me.
___
*[pkg/sql/sqlbase/structured.proto, line 92 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/39173#-LlIkEvd1At47ZIN5Co5:-LlJ18gs0x7T_hbm6bVS:b-86flnc) ([raw file](https://github.com/cockroachdb/cockroach/blob/69410615848f63e08f64b6309f44c4fa48fd6298/pkg/sql/sqlbase/structured.proto#L92)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

The deprecated annotation makes the field crossed out in my editor.
</blockquote></details>

Yeah, I think prefixing with `legacy_` couldn't hurt.
___
*[pkg/sql/sqlbase/structured_test.go, line 1710 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/39173#-LlA9R_v7lozk_smLtNn:-LlJ14ft9S-Gr09-G5FG:b76f16w) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5cbe72017fe9ef6820b7907ad309670290809c2/pkg/sql/sqlbase/structured_test.go#L1710)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Just the latter. It doesn't seem particularly important to me - I think messing this up would mess up the verification too.
</blockquote></details>

Seems fine.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39173)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @jordanlewis, @lucy-zhang, and @yuzefovich)

___
*[pkg/sql/sqlbase/structured.proto, line 92 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/39173#-LlIkEvd1At47ZIN5Co5:-LlJcfYz-oe_gWEyRrkP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/69410615848f63e08f64b6309f44c4fa48fd6298/pkg/sql/sqlbase/structured.proto#L92)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Yeah, I think prefixing with `legacy_` couldn't hurt.
</blockquote></details>

Done.

**Comment by jordanlewis** [comment]
TFTRs!

bors r+

**Pull request merged**
