### PR TITLE
docs,sql: Add docstrings to window function

### PR DESCRIPTION
**Pull request by yuzefovich**
Adds docstring to built-in window functions
so that docs could be autogenerated for them.

Resolves: #28066.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
cc @jseldess

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28140)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/docgen/funcs.go, line 197 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28140#-LIpv2Y2CHxFLfRVh2QM:-LIpv2Y2CHxFLfRVh2QN:b-42te1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1745a730ef6df561e680526a4fa1a21009b1ab9/pkg/cmd/docgen/funcs.go#L197)):*
> ```Go
> 				continue
> 			}
> 			if categorize && (fn.AggregateFunc != nil || fn.WindowFunc != nil) {
> ```

I'm not sure about this logic.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28140)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/docgen/funcs.go, line 197 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28140#-LIpv2Y2CHxFLfRVh2QM:-LIqQNSh30qQZ9xdfXUt:b-hvq7wh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1745a730ef6df561e680526a4fa1a21009b1ab9/pkg/cmd/docgen/funcs.go#L197)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I'm not sure about this logic.
</blockquote></details>

yeah, this logic is getting a tricky. I'm not immediately seeing why we now need to also skip aggregates here, or if we did need to, why that didn't change the content of functions.md? 

Maybe we should stop trying to decide what to filter here with the combination of categorize and looking at the funcs and instead just extend the block below to define another slice of the simple funcs, e.g. the rest after the two special-cased appends, then we just pass exactly the slice for which we actually want generation to occur?

Up to you.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28140)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/docgen/funcs.go, line 197 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28140#-LIpv2Y2CHxFLfRVh2QM:-LIqkUXX6sKcLAFk3FcA:b3dwyk1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1745a730ef6df561e680526a4fa1a21009b1ab9/pkg/cmd/docgen/funcs.go#L197)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

yeah, this logic is getting a tricky. I'm not immediately seeing why we now need to also skip aggregates here, or if we did need to, why that didn't change the content of functions.md? 

Maybe we should stop trying to decide what to filter here with the combination of categorize and looking at the funcs and instead just extend the block below to define another slice of the simple funcs, e.g. the rest after the two special-cased appends, then we just pass exactly the slice for which we actually want generation to occur?

Up to you.
</blockquote></details>

I don't quite understand the other approach you're suggesting, but I think I understood why `fn.WindowFunc != nil` was there - both aggregate builtins and window builtins contain that field, and when window builtins were introduced with no `info` strings, they needed to be skipped; aggregate builtins, on the other hand, generated a separate file. So now that I've added docstrings for window builtins, we can simply generate a separate file for them as well. Please let me know if another approach would be better (and if so, please paraphrase so that I get it :) ).

**Review by knz — CHANGES_REQUESTED** [review]
Good initiative. A few requests.

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28140#-:-LIviiTgClXTR8woatDM:btt3gqv)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/docgen/funcs.go, line 197 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28140#-LIpv2Y2CHxFLfRVh2QM:-LIvi9CgADjLgHSTMtZa:b8mqmkd) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1745a730ef6df561e680526a4fa1a21009b1ab9/pkg/cmd/docgen/funcs.go#L197)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I don't quite understand the other approach you're suggesting, but I think I understood why `fn.WindowFunc != nil` was there - both aggregate builtins and window builtins contain that field, and when window builtins were introduced with no `info` strings, they needed to be skipped; aggregate builtins, on the other hand, generated a separate file. So now that I've added docstrings for window builtins, we can simply generate a separate file for them as well. Please let me know if another approach would be better (and if so, please paraphrase so that I get it :) ).
</blockquote></details>

Window functions are identified with `props.Class == tree.WindowClass`. Don't use the `.WindowFunc` field.
___
*[pkg/sql/sem/builtins/all_builtins.go, line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28140#-LIvia22AN6MXsEd47Qd:-LIvia23EuseBQpFI7w0:b-f2yh6g) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbef3d060e8b7911356c28a9e49a9d7b390f27ec/pkg/sql/sem/builtins/all_builtins.go#L70)):*
> ```Go
> 	}
> 
> 	sort.Strings(AllBuiltinNames)
> ```

Please sort the new list here too.
___
*[pkg/sql/sem/builtins/window_builtins.go, line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28140#-LIvicr7D597enHiPLvP:-LIvicr7D597enHiPLvQ:b3mp4ek) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbef3d060e8b7911356c28a9e49a9d7b390f27ec/pkg/sql/sem/builtins/window_builtins.go#L58)):*
> ```Go
> var windows = map[string]builtinDefinition{
> 	"row_number": makeBuiltin(winProps(),
> 		makeWindowOverload(tree.ArgTypes{}, types.Int, newRowNumberWindow, "Calculates the number of the current row within its partition, counting from 1."),
> ```

Request for readability: please put the string on the next line to avoid long lines.

**Review by yuzefovich — COMMENTED** [review]
Thanks for the comments. I split up long `info` strings into multiple lines, please let me know if it is not the way to go.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28140#-:-LIw3aYD4aOquAh4jsSi:btt45ma)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/docgen/funcs.go, line 197 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28140#-LIpv2Y2CHxFLfRVh2QM:-LIw3L560r1gtj-asz3i:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1745a730ef6df561e680526a4fa1a21009b1ab9/pkg/cmd/docgen/funcs.go#L197)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Window functions are identified with `props.Class == tree.WindowClass`. Don't use the `.WindowFunc` field.
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/all_builtins.go, line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28140#-LIvia22AN6MXsEd47Qd:-LIw-yEX2-cn7zus-m4W:b-ubb87g) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbef3d060e8b7911356c28a9e49a9d7b390f27ec/pkg/sql/sem/builtins/all_builtins.go#L70)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please sort the new list here too.
</blockquote></details>

Good catch, thanks.
___
*[pkg/sql/sem/builtins/window_builtins.go, line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28140#-LIvicr7D597enHiPLvP:-LIw1PGR7wge-KLr4Wgv:bjb1bd0) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbef3d060e8b7911356c28a9e49a9d7b390f27ec/pkg/sql/sem/builtins/window_builtins.go#L58)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Request for readability: please put the string on the next line to avoid long lines.
</blockquote></details>

Sorry, I wanted to do that but forgot, thanks for pointing it out.

**Review by knz — APPROVED** [review]
LGTM

@jseldess @rmloveland are we ok with excluding the aggregate built-ins and window functions from the main builtin table?

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28140#-:-LIwBzCf7_OiH9kAAZKz:bc68uwm)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by jseldess** [comment]
@knz, don't we already break aggregate functions into its own table? https://www.cockroachlabs.com/docs/stable/functions-and-operators.html#aggregate-functions

I think it'd be fine to do the same thing for window functions. So it'll be a separate `.md` file alongside [these](https://github.com/cockroachdb/cockroach/tree/master/docs/generated/sql)?

**Comment by knz** [comment]
yes

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28140#-:-LIwWM1WARJgD3ZOPL4b:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
