### PR TITLE
sql: introduce PG-compatible access privilege inquiry functions

### LINKED ISSUE #20784: sql: support has_{schema,database,table}_privilege
https://www.postgresql.org/docs/10/static/functions-info.html

These are needed for `pgadmin`.

### LINKED ISSUE #22734: sql: implement privilege-related built-ins.
The postgresql list is: https://www.postgresql.org/docs/8.4/static/functions-info.html#FUNCTIONS-INFO-ACCESS-TABLE

name| return type | description
-- | -- | --
has_any_column_privilege(table, privilege) | boolean | does current user have privilege for any column of table
has_column_privilege(user, table, column, privilege) | boolean | does user have privilege for column
has_column_privilege(table, column, privilege) | boolean | does current user have privilege for column
has_database_privilege(user, database, privilege) | boolean | does user have privilege for database
has_database_privilege(database, privilege) | boolean | does current user have privilege for database
has_foreign_data_wrapper_privilege(user, fdw, privilege) | boolean | does user have privilege for foreign-data wrapper
has_foreign_data_wrapper_privilege(fdw, privilege) | boolean | does current user have privilege for foreign-data wrapper
has_function_privilege(user, function, privilege) | boolean | does user have privilege for function
has_function_privilege(function, privilege) | boolean | does current user have privilege for function
has_language_privilege(user, language, privilege) | boolean | does user have privilege for language
has_language_privilege(language, privilege) | boolean | does current user have privilege for language
has_schema_privilege(user, schema, privilege) | boolean | does user have privilege for schema
has_schema_privilege(schema, privilege) | boolean | does current user have privilege for schema
has_server_privilege(user, server, privilege) | boolean | does user have privilege for foreign server
has_server_privilege(server, privilege) | boolean | does current user have privilege for foreign server
has_table_privilege(user, table, privilege) | boolean | does user have privilege for table
has_table_privilege(table, privilege) | boolean | does current user have privilege for table
has_tablespace_privilege(user, tablespace, privilege) | boolean | does user have privilege for tablespace
has_tablespace_privilege(tablespace, privilege) | boolean | does current user have privilege for tablespace
pg_has_role(user, role, privilege) | boolean | does user have privilege for role
pg_has_role(role, privilege) | boolean | does current user have privilege for role

Obviously some do not apply to us, but we could easily implement table/schema/role related functions.

### PR DESCRIPTION
**Pull request by nvb**
Fixes #22734.
Fixes #20784.
Relates to #15441.

This change introduces a series of Postgres-compatible privilege-related
builtin functions:
- `has_any_column_privilege`
- `has_column_privilege`
- `has_database_privilege`
- `has_foreign_data_wrapper_privilege`
- `has_function_privilege`
- `has_language_privilege`
- `has_schema_privilege`
- `has_sequence_privilege`
- `has_server_privilege`
- `has_table_privilege`
- `has_tablespace_privilege`
- `has_type_privilege`
- `pg_has_role` (_coming soon!_)

These all follow the specification documented by Postgres in:
https://www.postgresql.org/docs/8.4/static/functions-info.html#FUNCTIONS-INFO-ACCESS-TABLE

These Access Privilege Inquiry Functions allow users to query object
access privileges programmatically. Each function has a number of
variants, which differ based on their function signatures. These
signatures have the following structure:
```
- optional "user" argument
  - if used, can be a STRING or an OID type
  - if not used, current_user is assumed
- series of one or more object specifier arguments
  - each can accept multiple types
- a "privilege" argument
  - must be a STRING
  - parsed as a comma-separated list of privilege
```

This means that in total, each function has at least 6 variants.

The main reason for adding these builtins in is because they were the
last remaining issue that was blocking full compatibility with [pgweb](http://sosedoff.github.io/pgweb/).
Pgweb is a web-based database browser written in Go, which means that
can run on OSX, Linux and Windows machines! Here's what TPC-C looks
like in pgweb:

screenshot-2018-3-2 pgweb 

Release note (sql change): Introduces a series of Postgres-compatible
privilege-related builtin functions.

### CODE REVIEW

**Comment by sosedoff** [comment]
Pgweb author here. Whats the main reasoning to get cockroachdb compatible with pgweb?

**Comment by nvanbenschoten** [comment]
@sosedoff CockroachDB aims to be Postgres compatible both in the wire protocol it speaks and the SQL semantics it exposes. As such, [people expect](https://github.com/cockroachdb/cockroach/issues/15441) that the same tools they use with Postgres will also work with CockroachDB.

There were a few reasons to focus on pgweb compatibility specifically here:
- pgweb looks nice and is highly functional! You've clearly done a great job with the project
- pgweb is cross-platform
- pgweb is written in Go and so is cockroach, for whatever that's worth
- pgweb was already very close to working because you have avoided relying on any obscure features of Postgres 
- pgweb compatibility required improving pg-compatibility in general, so the changes made here are progress towards a more general goal

**Comment by mberhault** [comment]
LGTM, just a few nits. I also find it odd that we're allowing queries for privileges we have no concept of, but I suppose it makes sense given that this is for compatibility.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/sql/logictest/testdata/logic_test/privilege_builtins, line 1 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23334#-L7PNTmO0bZuAAInF-mw:-L7PNTmO0bZuAAInF-mx:b-63cksz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae97d2f54673479bacd98ad69279ac287a7924d6/pkg/sql/logictest/testdata/logic_test/privilege_builtins#L1)):*
> ```
> # LogicTest: default distsql
> ```

It would be good to run a few of the builtins with `user testuser` to ensure that we allow everyone to query everything (postgres does, so as odd as it seems, we need to ensure we do the same).

---

*[pkg/sql/sem/tree/eval.go, line 2905 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23334#-L7PGkrHQsCAxqPJyuyc:-L7PGkrHQsCAxqPJyuyd:b-xu65gl) ([raw file](https://github.com/cockroachdb/cockroach/blob/f27c76997984972368da64319e42543dfb4271f1/pkg/sql/sem/tree/eval.go#L2905)):*
> ```Go
> 			return NewDName(s), nil
> 		default:
> 			panic(fmt.Sprintf("missing case for cast to string: %T", c))
> ```

If I'm reading this function correctly, this panic will be covered by the `CodeCannotCoerceError` at the end, correct?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23334#-:-L7PNfe66zzmo66J3irS:bikhp9g)*

**Comment by nvanbenschoten** [comment]
TFTR!

---

Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/logictest/testdata/logic_test/privilege_builtins, line 1 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23334#-L7PNTmO0bZuAAInF-mw:-L7VmoyL9aKfAfhaiZKW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae97d2f54673479bacd98ad69279ac287a7924d6/pkg/sql/logictest/testdata/logic_test/privilege_builtins#L1)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

It would be good to run a few of the builtins with `user testuser` to ensure that we allow everyone to query everything (postgres does, so as odd as it seems, we need to ensure we do the same).
</blockquote></details>

Done.

---

*[pkg/sql/sem/tree/eval.go, line 2905 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23334#-L7PGkrHQsCAxqPJyuyc:-L7Vmz4Z5_Sd2quTBCxY:bi4yk2s) ([raw file](https://github.com/cockroachdb/cockroach/blob/f27c76997984972368da64319e42543dfb4271f1/pkg/sql/sem/tree/eval.go#L2905)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

If I'm reading this function correctly, this panic will be covered by the `CodeCannotCoerceError` at the end, correct?
</blockquote></details>

Yep, exactly. I'm not sure why we had this panic here as well.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23334#-:-L7WzNSICc-oF2Pp9yt5:b-814g8k)*

**Pull request merged**
