### PR TITLE
storage: propagate tracing info through Raft proposals

### PR DESCRIPTION
**Pull request by andreimatei**
This patch propagates the SpanContext of the proposer to all the
replicas, which then decode it and create a "follows from" child span
for the application. The local replica does not use this, since it
already had direct access to the proposer's ctx and span.
Now tracing utilities will show us all the command applications for a
proposal tied to each other and we'll profit.

Release note: None

### CODE REVIEW

**Comment by andreimatei** [comment]
cc @spencerkimball

**Review by nvb — APPROVED** [review]
:lgtm: though I'm still a little confused why we're favoring the tracing of entry application over the tracing of entry sequencing in the Raft log. I would expect that appending to the Raft log would be the more interesting place to inject tracing on followers because it's synchronous with the client write.

I guess it's a little harder to pull out tracing spans at that stage because we don't decode the Raft command. Still, I'm curious whether there are any plans to do something like that?

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39431#-:-Lm5NDDh4SXYWEu695El:b-q194o4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/storage/replica_application_decoder.go, line 139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39431#-Lm5MIoO5BU9x5l-UoDd:-Lm5MIoO5BU9x5l-UoDe:b-ew16kp) ([raw file](https://github.com/cockroachdb/cockroach/blob/87e35e2fe2e7700a9f161b312d5a93b0e2dae2a3/pkg/storage/replica_application_decoder.go#L139)):*
> ```Go
> 	for it.init(&d.cmdBuf); it.Valid(); it.Next() {
> 		cmd := it.cur()
> 		parentCtx := ctx
> ```

Get rid of this variable.
___
*[pkg/storage/replica_application_decoder.go, line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39431#-Lm5MQcYE95xCkj3jeT0:-Lm5MQcYE95xCkj3jeT1:bpmp2wa) ([raw file](https://github.com/cockroachdb/cockroach/blob/87e35e2fe2e7700a9f161b312d5a93b0e2dae2a3/pkg/storage/replica_application_decoder.go#L142)):*
> ```Go
> 		if cmd.IsLocal() {
> 			parentCtx = cmd.proposal.ctx
> 			cmd.ctx, cmd.sp = tracing.ForkCtxSpan(parentCtx, "raft application")
> ```

Pull "raft application" into `const opName = "raft application"`

**Review by andreimatei — COMMENTED** [review]
bors r+

> I guess it's a little harder to pull out tracing spans at that stage because we don't decode the Raft command. Still, I'm curious whether there are any plans to do something like that?

Now there is :P
Once this merges, I'll file an issue for what you want.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39431#-:-Lm6E2DI-SJIq3HwTms0:b-tkemsh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[pkg/storage/replica_application_decoder.go, line 139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39431#-Lm5MIoO5BU9x5l-UoDd:-Lm6E_n05p7Wtmh0UMef:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/87e35e2fe2e7700a9f161b312d5a93b0e2dae2a3/pkg/storage/replica_application_decoder.go#L139)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Get rid of this variable.
</blockquote></details>

done
___
*[pkg/storage/replica_application_decoder.go, line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39431#-Lm5MQcYE95xCkj3jeT0:-Lm6Ej0V-8r1Wbm8wGci:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/87e35e2fe2e7700a9f161b312d5a93b0e2dae2a3/pkg/storage/replica_application_decoder.go#L142)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Pull "raft application" into `const opName = "raft application"`
</blockquote></details>

done

**Review by andreimatei — COMMENTED** [review]
hey @nvanbenschoten and @ajwerner , check out the increase in proposal size showed by `TestProposalOverhead`. We all still cool on this? (I am)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39431#-:-LqmL-gO1SpkBVubtZdK:b-o9qq24)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

**Comment by nvanbenschoten** [comment]
> We all still cool on this? (I am)

50 bytes of overhead to 133 bytes per Raft entry is a major regression. We need a lot to justify that kind of change. I thought this was only going to hurt when tracing is enabled.

**Review by andreimatei — COMMENTED** [review]
>  I thought this was only going to hurt when tracing is enabled.

yeah now that I think about it, that's the intention. Maybe `getTraceData()` needs to handle the noop span... I'll see.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39431#-:-LqmYEtd7ZBMIObvvZpC:biw1eek)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

**Review by andreimatei — COMMENTED** [review]
note to self: `TestProposalOverhead` fails because tracing is enabled for its purposes because nobody sets `trace.debug.enable` for the test's `testContext`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39431#-:-LqmkyGR9KXpdd40uapR:bko1b8g)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

**Review by andreimatei — COMMENTED** [review]
note to self: let's default `trace.debug.enable` to false and stop this nonsense

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39431#-:-LqmmNpB59yYeZVY9loZ:b607227)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

**Review by andreimatei — COMMENTED** [review]
Now `trace.debug.enable` defaults to false and the test correctly shows no overhead when tracing is off.

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39431#-:-LrkLIWp4WLMtpG68o7w:b-jdq8q8)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

**Pull request merged**
