### PR TITLE
server: expose SHOW JOBS in admin api server

### PR DESCRIPTION
**Pull request by benesch**
Since #17253 has quite a bit of review feedback to address, split out the admin endpoint, which is nearly ready to merge. This way, the riskier half is certain to make the code freeze. (FYI I've blindly requested review from all engineers who commented on #17253.)

---

Add a Jobs endpoint to the admin API server that will provide the data for the new jobs admin UI page (#13604).

### CODE REVIEW

**Comment by benesch** [comment]
Ok, test failures and conflicts addressed. This is ready to go!

**Comment by mrtracy** [comment]
This is LGTM, although might want an LGTM from @danhhz or @jordanlewis who reviewed this portion in more depth

**Comment by danhhz** [comment]
:lgtm:

---

Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/jobs/jobs.proto, line 63 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17260#-KqOzKOhsojXfFoUhMPN:-KqOzKOhsojXfFoUhMPO:bgnts0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff43dd551a2c5746e7d789859d61f6a01829477f/pkg/sql/jobs/jobs.proto#L63)):*
> ```protobuf
>   option (gogoproto.goproto_enum_prefix) = false;
>   option (gogoproto.goproto_enum_stringer) = false;
>   UNSPECIFIED = 0 [(gogoproto.enumvalue_customname) = "TypeUnspecified"];
> ```

are these used anywhere? this is an unsafe change if so (I'm also generally opposed to renumbering things in protos even if they haven't been used because being absolutely sure of that audit is usually difficult).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17260#-:-KqOzh45d_BN0BPpYuiL:bnfp4nl)*

**Comment by benesch** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/jobs/jobs.proto, line 63 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17260#-KqOzKOhsojXfFoUhMPN:-KqP0gqlTSSskH8UUD-2:b-ib2r2k) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff43dd551a2c5746e7d789859d61f6a01829477f/pkg/sql/jobs/jobs.proto#L63)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

are these used anywhere? this is an unsafe change if so (I'm also generally opposed to renumbering things in protos even if they haven't been used because being absolutely sure of that audit is usually difficult).
</blockquote></details>

Fortunately, I only added these three days ago (1b92b9c), so should totally safe. Didn't realize at the time that protobufs serialize enums to the first value if left unspecified. :disappointed:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17260)*

**Comment by jordanlewis** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17260#-:-KqP1ivGbzsQK1CUBgVf:bnfp4nl)*

**Pull request merged**
