### PR TITLE
release-23.2.4-rc: sql: collect table statistics on virtual computed columns

### PR DESCRIPTION
**Pull request by michae2**
Backport:
  * 2/2 commits from "sql: collect table statistics on virtual computed columns" (#118241)
  * 1/1 commits from "sql: guard against non-public mutation columns in CREATE STATISTICS" (#118930)

Please see individual PRs for details.

/cc @cockroachdb/release

Release justification: high priority business need for the functionality which cannot wait until the next release.

### CODE REVIEW

**Comment by michae2** [comment]
See https://github.com/cockroachdb/cockroach/pull/120923#issuecomment-2016393963 for backport questions.

**Comment by michae2** [comment]
The backport was clean, there were only minor differences from master:
- `sql.stats.virtual_computed_columns.enabled` is false by default
- had to add `SET CLUSTER SETTING sql.stats.virtual_computed_columns.enabled = true` to distsql_stats and distsql_misc logic tests

**Comment by michae2** [comment]
Failure looks like unrelated flake https://github.com/cockroachdb/cockroach/issues/120221.

**Review by mgartner — APPROVED** [review]
> Reviewed 7 of 7 files at r1, 4 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120933)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @rytaft)

**Pull request merged**
