### PR TITLE
telemetryccl: skip TestTelemetry under deadlock

### LINKED ISSUE #83495: pkg/ccl/telemetryccl/telemetryccl_test: TestTelemetry failed
pkg/ccl/telemetryccl/telemetryccl_test.TestTelemetry [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/5582830?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/5582830?buildTab=artifacts#/) on master @ [096ed43069fa5ce48e2fd276b9cc0342aaf7d223](https://github.com/cockroachdb/cockroach/commits/096ed43069fa5ce48e2fd276b9cc0342aaf7d223):

```
        ----
        sql.multiregion.zone_configuration.override.user
    telemetry.go:111: 
        testdata/telemetry/multiregion:450:
        feature-usage [0 args]
        ALTER TABLE t9 CONFIGURE ZONE USING gc.ttlseconds=5
        ----
    telemetry.go:111: 
        testdata/telemetry/multiregion:454:
        feature-usage [0 args]
        SET override_multi_region_zone_config = true;
        ALTER TABLE t9 SET LOCALITY GLOBAL;
        SET override_multi_region_zone_config = false
        ----
        sql.multiregion.zone_configuration.override.system.table
    telemetry.go:111: 
        testdata/telemetry/multiregion:462:
        feature-usage [0 args]
        ALTER TABLE t9 SET LOCALITY REGIONAL BY TABLE IN PRIMARY REGION;
        ----
    telemetry.go:111: 
        testdata/telemetry/multiregion:469:
        feature-usage [0 args]
        SET override_multi_region_zone_config = true;
        ALTER TABLE t9 SET LOCALITY GLOBAL;
        SET override_multi_region_zone_config = false
        ----
        sql.multiregion.zone_configuration.override.system.table
    telemetry.go:111: 
        testdata/telemetry/multiregion:476:
        feature-usage [0 args]
        SET override_multi_region_zone_config = true;
        ALTER DATABASE d CONFIGURE ZONE USING num_replicas=10;
        SET override_multi_region_zone_config = false
        ----
        sql.multiregion.zone_configuration.override.user
    telemetry.go:111: 
        testdata/telemetry/multiregion:483:
        feature-usage [0 args]
        ALTER DATABASE d CONFIGURE ZONE USING gc.ttlseconds=5;
        ----
    telemetry.go:111: 
        testdata/telemetry/multiregion:487:
        feature-usage [0 args]
        SET override_multi_region_zone_config = true;
        ALTER DATABASE d ADD REGION "us-east-1";
        SET override_multi_region_zone_config = false
        ----
        sql.multiregion.zone_configuration.override.system.database
        --- PASS: TestTelemetry/multiregion/server (156.92s)
```
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestTelemetry.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-17102

### PR DESCRIPTION
**Pull request by knz**
Fixes #83495.

This test is extremely large. It takes an unreasonable amount of time with the race or deadlock detector enabled.

Release note: None

### CODE REVIEW

**Review by msbutler — APPROVED** [review]

**Comment by knz** [comment]
TFYR!

bors r=msbutler

**Comment by rafiss** [comment]
@knz do we need the same for https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/telemetry_test.go ?

**Comment by knz** [comment]
The deadlock error is on the master branch and this PR is against the master branch

The other error is on the 23.1 branch and is a different error and so imho needs a separate investigation

**Comment by knz** [comment]
bors r=msbutler

**Comment by rafiss** [comment]
@knz should we do the same for pkg/sql/telemetry_test.go?

**Comment by knz** [comment]
>  should we do the same for pkg/sql/telemetry_test.go?

ok done

**Comment by knz** [comment]
bors r=msbutler

**Pull request merged**
