### PR TITLE
*: remove the `storage.mvcc.range_tombstones.enabled` cluster setting

### LINKED ISSUE #91147: storage: add unconditional range tombstone cluster version
Before 23.1, we should remove the `storage.mvcc.range_tombstones.enabled` setting, to ensure all clusters are always MVCC-compliant.

Jira issue: CRDB-21122

Epic CRDB-20465

### PR DESCRIPTION
**Pull request by nicktrav**
Range tombstones were gated behind a cluster setting in 22.2. They are currently enabled by default on the master branch with the intention of being enabled by default in the 23.1 release.

Remove the cluster setting entirely.

Closes #91147.

Release note: None.

### CODE REVIEW

**Comment by nicktrav** [comment]
Opening this up for a first round of review. This removes the cluster setting and the helper functions. I lacked context on some of the changes in higher layers (DR / SQL), so I did my best there. 

There's at least one test that is failing `pkg/ccl/backupccl.TestDataDriven/in-progress-import-rollback`, so would appreciate some eyes there.

@erikgrinaker - I also didn't touch the proto API here. It wasn't clear to me if we needed to keep the range tombstone fields around, or if they could be retired / moved to reserved. If we do need to remove, I can tackle that separately (the change looked much more nuanced).

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96966)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @jbowens, @miretskiy, @msbutler, @nicktrav, @renatolabs, and @smg260)

___
*[`pkg/storage/mvcc.go` line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96966#-NOAQ4vjCZzCwzpfkLph:-NOAQ4vkD3H9GSQGSH4C:b3a13xz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2bb35dfd3c769950d4c40b321408da853931573/pkg/storage/mvcc.go#L88)):*
> ```Go
> var MVCCRangeTombstonesEnabled = settings.RegisterBoolSetting(
> 	settings.TenantReadOnly,
> 	"storage.mvcc.range_tombstones.enabled",
> ```

This should be added to `settings.retiredSettings`

**Review by rafiss — CHANGES_REQUESTED** [review]
can you put the setting into the `retiredSettings` map of `pkg/settings/registry.go`?

**Review by rafiss — COMMENTED** [review]
ah i see, Radu commented on that already

**Review by nicktrav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96966)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @jbowens, @miretskiy, @msbutler, @rafiss, @renatolabs, and @smg260)

___
*[`pkg/storage/mvcc.go` line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96966#-NOAQ4vjCZzCwzpfkLph:-NOAmNKq5UNudcdszXG7:boyexb3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2bb35dfd3c769950d4c40b321408da853931573/pkg/storage/mvcc.go#L88)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This should be added to `settings.retiredSettings`
</blockquote></details>

Done. Thanks!

**Review by erikgrinaker — APPROVED** [review]
As I mentioned over on the issue, this change will mean that 23.1 nodes in a mixed 22.2/23.1 cluster will unconditionally send requests using MVCC range tombstones. I think that's fine, since we do expect them to work properly in 22.2 as well, but I suppose there's always a risk that we discover some bad bug in early 22.2 releases and users could hit this when upgrading to 23.1. The alternative would be to continue respecting the setting until the 23.1 upgrade is finalized, but that seems like overkill to me.

>I also didn't touch the proto API here. It wasn't clear to me if we needed to keep the range tombstone fields around, or if they could be retired / moved to reserved. If we do need to remove, I can tackle that separately (the change looked much more nuanced).

We'll need to keep `DeleteRangeRequest.UseRangeTombstone` around -- the non-range-tombstone variant is often used by SQL for range deletions, and we can't use range tombstones here yet because they're not transactional. And in any case, we'd have to set it for compatibility with 22.2 nodes.

> Reviewed 25 of 25 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96966#-:-NOBVNgN3dRPj9jo26rM:b-m7btgq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens, @miretskiy, @msbutler, @nicktrav, @rafiss, @renatolabs, and @smg260)

___
*[`pkg/sql/repair.go` line 743 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96966#-NOBPhS8BscPbRNfAUSO:-NOBPhS8BscPbRNfAUSP:b-pgz29y) ([raw file](https://github.com/cockroachdb/cockroach/blob/e86668f75ca38fdd219bd94c9fb8814c948bfac9/pkg/sql/repair.go#L743)):*
> ```Go
> 	}
> 	b := &kv.Batch{}
> 	if p.execCfg.Settings.Version.IsActive(ctx, clusterversion.TODODelete_V22_2UseDelRangeInGCJob) {
> ```

Should we get rid of `clusterversion.TODODelete_V22_2UseDelRangeInGCJob` while we're at it?
___
*[`pkg/sql/gcjob/gc_job.go` line 502 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96966#-NOBQcQL1z6t4NLvap4N:-NOBQcQL1z6t4NLvap4O:bq9nd14) ([raw file](https://github.com/cockroachdb/cockroach/blob/e86668f75ca38fdd219bd94c9fb8814c948bfac9/pkg/sql/gcjob/gc_job.go#L502)):*
> ```Go
> 	ctx context.Context, details *jobspb.SchemaChangeGCDetails, s *cluster.Settings,
> ) bool {
> 	// TODO(ajwerner): Adopt the DeleteRange protocol for tenant GC.
> ```

@ajwerner @stevendanna  Do you know the implications of this for C2C replication and unified architecture? Is it possible to replicate entire clusters with C2C, including all tenants, such that this tenant GC (using ClearRange) won't get replicated and the tenant will live on in the target cluster? Or is replication always done on a per-tenant basis, such that destroying the tenant will halt the C2C replication, making this moot?

**Comment by nicktrav** [comment]
We decided to keep the cluster setting around for 23.1. Going to close this out for now and revisit next cycle.

**Comment by erikgrinaker** [comment]
>We decided to keep the cluster setting around for 23.1. Going to close this out for now and revisit next cycle.

Did you check this with DR and schema? I think they wanted to rely on the MVCC history being unconditionally complete, for stuff like tenant backups and C2C replication.

**Comment by erikgrinaker** [comment]
Nevermind, just saw https://github.com/cockroachdb/cockroach/issues/91147#issuecomment-1447212024.

**Pull request closed without merging**
