### PR TITLE
backupccl: download pre restore data in cluster restore

### LINKED ISSUE #124330: roachtest: backup-restore/online-restore failed
roachtest.backup-restore/online-restore [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/15301919?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/15301919?buildTab=artifacts#/backup-restore/online-restore) on master @ [855b9cc97afa3df4f7e17f928c04ab0834b2630c](https://github.com/cockroachdb/cockroach/commits/855b9cc97afa3df4f7e17f928c04ab0834b2630c):

```
(monitor.go:154).Wait: monitor failure: backup 1_round-trip-test-backup_cluster: error verifying online restore: download job 969459392374472708 did not download all data
test artifacts and logs in: /artifacts/backup-restore/online-restore/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=true</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-15301919/backup-restore-online-restore/1715925382758/1715926152018)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backup-restore/online-restore.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-38828

### PR DESCRIPTION
**Pull request by msbutler**
This patch adds the pre restore data spans to the list of spans to download.
While these pre restore spans map to data in the temporary system table
database that are then rewwritten to the actual system table, the download job
ought to download all external data linked into the cluster out of principle.

Fixes #124330

Release note: none

### CODE REVIEW

**Comment by dt** [comment]
These tables are already dropped and awaiting GC by the time we write the download job; why are we using download bandwidth and iops on something just to delete it?

**Comment by msbutler** [comment]
I don't really have strong opinions here, but i have 3 reasons:
- it is nice to guarantee that after the download job completes, no external bytes are left on the cluster
-  It's also only a mbs of pre restore data, though perhaps it scales for larger clusters. 
- It would also be nice for our check to pass on cluster restore:
```
`SELECT
COALESCE(stats->>'external_file_bytes','0') FROM
crdb_internal.tenant_span_stats( ARRAY(SELECT(crdb_internal.tenant_span()[1], crdb_internal.tenant_span()[2])))`
```

I'm also happy to skip the check on cluster restores and move on though.

**Comment by dt** [comment]
As long as the "pre" spans are after the main spans I guess it doesn't matter; in a non-trivial restore they're already GC'ed and the vSSTs are gone anyway so it is a noop.

**Review by dt — APPROVED** [review]

**Comment by msbutler** [comment]
TFTR!

bors r=dt

**Pull request merged**
