### PR TITLE
storage: plumb AdminChangeReplicas request

### PR DESCRIPTION
**Pull request by RaduBerinde**
Plumbing an `AdminChangeReplicas` request. Refactoring the `testcluster` code
to issue this operation rather than calling into the `Replica` directly.

This request will be used to implement `SCATTER` and `TESTING_RELOCATE`
(#13665).

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14333)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

perhaps there's multiTestContext code that can use this as well.

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/testutils/testcluster/testcluster.go, line 272 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14333#-Kfv9PmNqGtF_lEXKzP1:-Kfv9PmOrDT6lQZGsa1N:b-44deaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/531f84bd6a33349c0989d58547d3eeeadf05d0d3/pkg/testutils/testcluster/testcluster.go#L272)):*
> ```Go
> 		ctx, startKey.AsRawKey(), changeType, targets,
> 	); err != nil {
> 		log.Errorf(ctx, "AdminChangeReplicas error: %s", err)
> ```

errors.Wrap the return value instead?

---

*[pkg/testutils/testcluster/testcluster.go, line 279 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14333#-Kfv9YIKEQvUO_YpLMT2:-Kfv9YIKEQvUO_YpLMT3:b-44deaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/531f84bd6a33349c0989d58547d3eeeadf05d0d3/pkg/testutils/testcluster/testcluster.go#L279)):*
> ```Go
> 		ctx, keys.RangeDescriptorKey(startKey), &rangeDesc,
> 	); err != nil {
> 		log.Errorf(ctx, "range descriptor lookup error: %s", err)
> ```

errors.Wrap the return value instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14333#-:-Kfv9mXTZw64l8J1n9Zb:bhcsyz5)*

**Comment by RaduBerinde** [comment]
TFTR!

I changed multiTestContext, please take a look.

---

Review status: 10 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/testutils/testcluster/testcluster.go, line 272 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14333#-Kfv9PmNqGtF_lEXKzP1:-KfvDtUDvxp6p673UniC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/531f84bd6a33349c0989d58547d3eeeadf05d0d3/pkg/testutils/testcluster/testcluster.go#L272)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

errors.Wrap the return value instead?
</blockquote></details>

Done.

---

*[pkg/testutils/testcluster/testcluster.go, line 279 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14333#-Kfv9YIKEQvUO_YpLMT2:-KfvDtEGQjZbNqTXhiwn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/531f84bd6a33349c0989d58547d3eeeadf05d0d3/pkg/testutils/testcluster/testcluster.go#L279)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

errors.Wrap the return value instead?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14333#-:-KfvDuDFJsvRAgDgFQCp:b-t7bs3e)*

**Comment by tamird** [comment]
Beautiful.

---

Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/storage/client_test.go, line 982 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14333#-KfvgAuWR0aQZLPuk3Ar:-KfvgAuWR0aQZLPuk3As:bq8afnp) ([raw file](https://github.com/cockroachdb/cockroach/blob/26fc04b9447107fa6c1d48c8afde2f788c93bc9f/pkg/storage/client_test.go#L982)):*
> ```Go
> 		}
> 
> 		if testutils.IsError(err, "snapshot failed: .*") {
> ```

comment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14333#-:-Kfvg6X10n9UrMe8B8tq:bxztp5u)*

**Comment by RaduBerinde** [comment]
*[pkg/storage/client_test.go, line 982 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14333#-KfvgAuWR0aQZLPuk3Ar:-KfvhzneY_IBLNOS3vz0:br66vt2) ([raw file](https://github.com/cockroachdb/cockroach/blob/26fc04b9447107fa6c1d48c8afde2f788c93bc9f/pkg/storage/client_test.go#L982)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

comment?
</blockquote></details>

Any suggestion? :dog: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14333)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/storage/client_test.go, line 982 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14333#-KfvgAuWR0aQZLPuk3Ar:-KfviHUL4_cvV4XaxtYW:b8g2gp) ([raw file](https://github.com/cockroachdb/cockroach/blob/26fc04b9447107fa6c1d48c8afde2f788c93bc9f/pkg/storage/client_test.go#L982)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Any suggestion? :dog: 
</blockquote></details>

I don't know - this is a pretty liberal regex. What concrete errors were you seeing? why is it OK to ignore snapshot errors?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14333)*

**Comment by andreimatei** [comment]
:lgtm:

Perhaps @bdarnell should take a look too.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/testutils/testcluster/testcluster.go, line 271 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14333#-KfvlFz69doEcAsBSkww:-KfvlFz69doEcAsBSkwx:b44i8r6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d5737c0f773105322171c3935f418eb0ec8c356/pkg/testutils/testcluster/testcluster.go#L271)):*
> ```Go
> 
> 	// TODO(andrei): the following code has been adapted from
> 	// multiTestContext.replicateRange(). Find a way to share.
> ```

looks like we found a way to share. good. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14333#-:-KfvlPOJj_7EJmFCSy1T:brp7iua)*

**Comment by andreimatei** [comment]
Consider adding an explicit test for this admin request, different from the tests using the multiTestContext and TestCluster methods for replication.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14333#-:-KfvlocePjgRZhLAIiKP:bago4vv)*

**Comment by RaduBerinde** [comment]
*[pkg/storage/client_test.go, line 982 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14333#-KfvgAuWR0aQZLPuk3Ar:-KfvwVcwSkxzTgptEwII:bei6009) ([raw file](https://github.com/cockroachdb/cockroach/blob/26fc04b9447107fa6c1d48c8afde2f788c93bc9f/pkg/storage/client_test.go#L982)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I don't know - this is a pretty liberal regex. What concrete errors were you seeing? why is it OK to ignore snapshot errors?
</blockquote></details>

This replaced the `if storage.IsSnapshotError(err)` check below. I have no idea what the reasoning is. I can confirm I see test failures with "snapshot failed" messages if I remove it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14333)*

**Comment by RaduBerinde** [comment]
Do you know any existing similar tests I can start from? I couldn't find anything for `AdminSplit` or `AdminTransferLease` for example

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14333#-:-Kfvx4fJHkU9R3Lu6q9I:bpoa3z5)*

**Comment by andreimatei** [comment]
The best I can think of is looking at `TestManualReplication` in `testcluster_test.go` and seeing if it makes sense to copy-paste and do the replication explicitly through the `client.DB`.

---

Review status: 10 of 12 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14333#-:-KfwBYkuiO-R7N3QulAv:b728mzm)*

**Comment by bdarnell** [comment]
Reviewed 9 of 11 files at r1, 1 of 1 files at r2, 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/client_test.go, line 982 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14333#-KfvgAuWR0aQZLPuk3Ar:-KfwCmRoYpdJLi0TnOOK:b-ms0b03) ([raw file](https://github.com/cockroachdb/cockroach/blob/26fc04b9447107fa6c1d48c8afde2f788c93bc9f/pkg/storage/client_test.go#L982)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This replaced the `if storage.IsSnapshotError(err)` check below. I have no idea what the reasoning is. I can confirm I see test failures with "snapshot failed" messages if I remove it.
</blockquote></details>

One way to handle this would be to make `storage.snapshotError` a `roachpb.Error`, so it could be passed over the wire in a machine-readable way. But for this one usage I don't think it's worth the effort. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14333)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14333#-:-KfwD61St2FJr-A9zrIS:bnfp4nl)*

**Comment by tamird** [comment]
Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/client_test.go, line 982 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14333#-KfvgAuWR0aQZLPuk3Ar:-KfvxwBmoj1THelkYxgE:b-2ubm6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/26fc04b9447107fa6c1d48c8afde2f788c93bc9f/pkg/storage/client_test.go#L982)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This replaced the `if storage.IsSnapshotError(err)` check below. I have no idea what the reasoning is. I can confirm I see test failures with "snapshot failed" messages if I remove it.
</blockquote></details>

Ah, and the reason that `IsSnapshotErr` can't be used is that the error is going over the network? Perhaps at least indicate that in a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14333)*

**Comment by RaduBerinde** [comment]
Review status: 11 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/storage/client_test.go, line 982 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14333#-KfvgAuWR0aQZLPuk3Ar:-KfwJdO2f7yNKP2xVjKB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26fc04b9447107fa6c1d48c8afde2f788c93bc9f/pkg/storage/client_test.go#L982)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Ah, and the reason that `IsSnapshotErr` can't be used is that the error is going over the network? Perhaps at least indicate that in a comment.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14333)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14333)*

**Pull request merged**
