### PR TITLE
sql: drop types as part of a `DROP DATABASE` statement

### LINKED ISSUE #49940: sql: drop types when a database is dropped
Once we support `DROP TYPE`, this needs to be done as well.

### PR DESCRIPTION
**Pull request by rohany**
Fixes #49940.

This commit adds logic to drop all types as part of a `DROP DATABASE`
cascade.

Release note: None

### CODE REVIEW

**Comment by rohany** [comment]
Take a look at the second commit please!

**Comment by rohany** [comment]
I've rebased this and it's ready for review

**Comment by rohany** [comment]
pinging @ajwerner and @lucy-zhang for review.

**Review by thoszhang — COMMENTED** [review]
> Reviewed 3 of 10 files at r2, 21 of 21 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51362)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @rohany)

___
*[pkg/sql/drop_table.go, line 324 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51362#-MDp-fVO6hGES_CLMteH:-MDp-fVO6hGES_CLMteI:bv0dyok) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72ec2b184e5a6ea6d383fad4edd6ae0722fd840/pkg/sql/drop_table.go#L324)):*
> ```Go
> 	// queued. If not, then the job that is handling the drop table will also
> 	// clean up all of the types to be dropped.
> 	if queueJob {
> ```

This parameter currently just indicates whether the object is being dropped as part of `DROP DATABASE CASCADE`, right? Maybe we should rename it accordingly. It's a little strange to have other behavior depend on the `queueJob` parameter.
___
*[pkg/sql/schema_changer.go, line 1793 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51362#-MDp0T-kBQ46XHO6wR3y:-MDp0T-l0WEgb9GS4UjC:b-r8y1kh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72ec2b184e5a6ea6d383fad4edd6ae0722fd840/pkg/sql/schema_changer.go#L1793)):*
> ```Go
> 	// multiple tables in a single job (e.g., TRUNCATE on multiple tables), so
> 	// it's possible for DroppedDatabaseID to be unset.
> 	if details.DroppedDatabaseID != sqlbase.InvalidID || len(details.DroppedTables) > 1 || len(details.DroppedTypes) > 0 {
> ```

When would `DroppedTypes` be non-nil when `DroppedDatabaseID` is unset?
___
*[pkg/sql/logictest/testdata/logic_test/drop_type, line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51362#-MDp0u-o057_zhPad6OQ:-MDp0u-o057_zhPad6OR:bae7zhy) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72ec2b184e5a6ea6d383fad4edd6ae0722fd840/pkg/sql/logictest/testdata/logic_test/drop_type#L1)):*
> ```
> # LogicTest: !3node-tenant
> ```

Why the configuration change? Does the current incoherent caching of databases make DROP DATABASE in logic tests in multi-node configurations unreliable or something?
___
*[pkg/sql/logictest/testdata/logic_test/drop_type, line 295 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51362#-MDp1Ra0ESH_Ze6nAAIP:-MDp1Ra0ESH_Ze6nAAIQ:bft46c3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72ec2b184e5a6ea6d383fad4edd6ae0722fd840/pkg/sql/logictest/testdata/logic_test/drop_type#L295)):*
> ```
> DROP DATABASE d RESTRICT
> 
> let $t_id
> ```

Interesting, I didn't know we supported this

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51362)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, and @rohany)

___
*[pkg/sql/drop_table.go, line 324 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51362#-MDp-fVO6hGES_CLMteH:-MDpIPzX0BV4FhBMNcNZ:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72ec2b184e5a6ea6d383fad4edd6ae0722fd840/pkg/sql/drop_table.go#L324)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

This parameter currently just indicates whether the object is being dropped as part of `DROP DATABASE CASCADE`, right? Maybe we should rename it accordingly. It's a little strange to have other behavior depend on the `queueJob` parameter.
</blockquote></details>

Good point, done.
___
*[pkg/sql/schema_changer.go, line 1793 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51362#-MDp0T-kBQ46XHO6wR3y:-MDpCeul7Jm5fl5j8Spm:b-mu9jbc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72ec2b184e5a6ea6d383fad4edd6ae0722fd840/pkg/sql/schema_changer.go#L1793)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

When would `DroppedTypes` be non-nil when `DroppedDatabaseID` is unset?
</blockquote></details>

Yeah, I don't think there is a case for that.
___
*[pkg/sql/logictest/testdata/logic_test/drop_type, line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51362#-MDp0u-o057_zhPad6OQ:-MDpCSpc2430f3MXzrU3:b3vsymg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72ec2b184e5a6ea6d383fad4edd6ae0722fd840/pkg/sql/logictest/testdata/logic_test/drop_type#L1)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Why the configuration change? Does the current incoherent caching of databases make DROP DATABASE in logic tests in multi-node configurations unreliable or something?
</blockquote></details>

There's some known issues with `DROP DATABASE` not working in the multitenant config due to some errors with range deletes.

**Review by thoszhang — APPROVED** [review]
> Reviewed 14 of 14 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51362)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @rohany)

**Pull request merged**
