### PR TITLE
build: use make builtins for determining obsolete execgen targets

### PR DESCRIPTION
**Pull request by petermattis**
Release justification (category 1): non-production code changes

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
There is no urgency behind this change. Just sending it out to show what I was thinking of regarding doing something more make-like. Note that this does fix one thing: it removes obsolete files in `sql/col/coldata` which were previously being left behind. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45987#-:-M29AeEPCKMSfTDlHwWo:b-rndbre)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Comment by knz** [comment]
I like this change but I don't understand its CI failure. Do you want to have a look?

**Comment by petermattis** [comment]
> I like this change but I don't understand its CI failure. Do you want to have a look?

I think I formatted the `Release justification` commit message wrong.

**Comment by knz** [comment]
I also see you're forcing the rule to execute by including it.
I wonder if that's the one and only way to do this. Why don't you make it a dependency of `build/defs.mk`?

(Like we do already for `build/defs.mk.sig` which is also always looked at)

**Comment by petermattis** [comment]
> I also see you're forcing the rule to execute by including it.
I wonder if that's the one and only way to do this. Why don't you make it a dependency of build/defs.mk?

Certainly could do that, though I'm not sure if that is any cleaner. It implies the rules are tied together in some manner when they are really independent. Perhaps I'm misunderstanding the motivation for your suggestion.

**Comment by knz** [comment]
What I don't like much is `include` of a file that's not meant to even exist.
That's in contrast to `build/defs.mk` which does exist (and is looked at every time, by virtue of being included).

**Comment by petermattis** [comment]
> What I don't like much is include of a file that's not meant to even exist.
That's in contrast to build/defs.mk which does exist (and is looked at every time, by virtue of being included).

Ah, got it. Yeah, that's just make hacking. I've done exactly this in the past so it doesn't bother me.  Hooking onto `build/defs.mk` is fine too, though it is slightly subtle why that always gets rebuilt (see `build/defs.mk.sig: .ALWAYS_REBUILD`). I'm not hung up on this part, though. I've switched to making `remove_obsolete_execgen` a dependency of `build/defs.mk`.

**Comment by knz** [comment]
>  I've done exactly this in the past so it doesn't bother me

It's my first time, please forgive me for the discomfort. Your experience is as good as mine in this case. 

LGTM

**Review by knz — APPROVED** [review]

**Comment by petermattis** [comment]
TFTR!

bors r+

**Pull request merged**
