### PR TITLE
clusterversion: remove 24.2 gates and checks

### PR DESCRIPTION
**Pull request by RaduBerinde**
Epic: REL-1292
Release note: None

### CODE REVIEW

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135578)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @celiala, @dhartunian, @dt, @nvanbenschoten, @RaduBerinde, and @yuzefovich)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135578#-OC54G2v44bwF0jRAByx:-OC54G2v44bwF0jRAByy:bqsype4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7b4b546e08cfc72f03b80a7749d1874e12999d6/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go#L41)):*
> ```Go
> 	reflect.TypeOf((*tree.AlterTableValidateConstraint)(nil)): {fn: alterTableValidateConstraint, on: true, checks: nil},
> 	reflect.TypeOf((*tree.AlterTableSetDefault)(nil)):         {fn: alterTableSetDefault, on: true, checks: nil},
> 	reflect.TypeOf((*tree.AlterTableAlterColumnType)(nil)):    {fn: alterTableAlterColumnType, on: true, checks: isV242Active},
> ```

I updated this in #135731 as well. The version should actually be v24.3. Once my change is merged and you rebase, you can simply undo your update.

**Review by yuzefovich — APPROVED** [review]
Thanks! :lgtm: but probably would be good to get a sign off from Foundations too (on the second commit).

> Reviewed 26 of 26 files at r1, 25 of 25 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135578#-:-OC58p0u4o1Z7S5Fm7Aq:bg0cing)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @celiala, @dhartunian, @dt, @nvanbenschoten, @RaduBerinde, and @spilchen)

___
*[`-- commits` line 8 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135578#-OC58mG-8e3l9pYgEfh0:-OC58mG-8e3l9pYgEfh1:b-oyv3oo):*
Can we do the same for 24.2 rules?
___
*[`pkg/sql/schemachanger/screl/scalars.go` line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135578#-OC584TZB3wX6e6KtlUE:-OC584TZB3wX6e6KtlUF:b-oxisq0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffada5cff06af2b17534903a44e32d59ae1bb184/pkg/sql/schemachanger/screl/scalars.go#L124)):*
> ```Go
> 		return true
> 	case *scpb.TypeComment, *scpb.DatabaseZoneConfig:
> 		return true
> ```

nit: perhaps here and two lines above add a comment about the version where the elements were introduced, for consistency with all cases above.

**Review by spilchen — APPROVED** [review]
The schema changer related changes look good to me.

> Reviewed 26 of 26 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135578#-:-OC5GrkI6s3uetGt_tzw:b-vx2gdu)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @celiala, @dhartunian, @dt, @nvanbenschoten, and @RaduBerinde)

**Review by RaduBerinde — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135578#-:-OC59Ji0606VPVgs4g4j:bz5mair)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @celiala, @dhartunian, @dt, @nvanbenschoten, @spilchen, and @yuzefovich)

___
*[`-- commits` line 8 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135578#-OC58mG-8e3l9pYgEfh0:-OC59EY8EZl4w36Y_kMl:b-vdlq9w):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Can we do the same for 24.2 rules?
</blockquote></details>

Not yet, we still have to bump the min version to 24.3 (will be done separately)

**Pull request merged**
