### PR TITLE
sqlbase: don't unset datums unless necessary

### PR DESCRIPTION
**Pull request by jordanlewis**
Previously, the row fetcher would unset every column in its EncDatumRow
on every new row it received. This was surprisingly inefficient -
restting the fields in an EncDatum requires a memory barrier, which is
slow enough to make a dent in performance when its in a tight loop.

Now, we calculate the set of nullable needed columns at plan time, and
only unset those.

NB: this has the potential to be unsafe if we have bad data on disk. If
there are some rows that are missing non-nullable columns, then the row
fetcher would mistakenly use stale data for those columns.

Is that okay? If not, we could either always unset needed columns regardless of nullability. Or, we could keep a `seen` slice for the nullable, needed columns in the fetch plan, and check it at the end of each row to see if there are any missing ones, returning an error at that point instead of wrong data.

```
name                                old time/op    new time/op    delta
WideTableIgnoreColumns/Cockroach-8    14.3ms ± 1%    12.8ms ± 1%  -10.19%  (p=0.000 n=10+10)

name                                old alloc/op   new alloc/op   delta
WideTableIgnoreColumns/Cockroach-8    2.11MB ± 0%    2.10MB ± 0%   -0.43%  (p=0.000 n=9+9)

name                                old allocs/op  new allocs/op  delta
WideTableIgnoreColumns/Cockroach-8     1.37k ±22%     1.17k ± 3%  -14.73%  (p=0.005 n=10+9)

name               old time/op    new time/op    delta
Count/Cockroach-8    49.8ms ± 2%    49.1ms ± 1%  -1.32%  (p=0.002 n=10+9)
```

Release note (performance improvement): improve the performance of scans
by doing less work

### CODE REVIEW

**Comment by petermattis** [comment]
I'm a little wary of this change as it seems like has the potential for a bug in the presence of schema changes. As an alternative, can we keep track in a `FastIntSet` which columns were set and only clear the ones that were set?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21572#-:-L3DhOjEP09-2QHq2VxF:b-m9a6c2)*

**Comment by nvanbenschoten** [comment]
@jordanlewis FWIW I'm seeing the following experiment give about a 3-4% speedup:

```
diff --git a/pkg/sql/sqlbase/encoded_datum.go b/pkg/sql/sqlbase/encoded_datum.go
index 3bfae8bc1..fe89fb4b1 100644
--- a/pkg/sql/sqlbase/encoded_datum.go
+++ b/pkg/sql/sqlbase/encoded_datum.go
@@ -422,6 +422,17 @@ func (r EncDatumRow) CompareToDatums(
        return 0, nil
 }

+const emptyDatumRowChunk = 128
+
+var emptyDatumRow = make(EncDatumRow, emptyDatumRowChunk)
+
+// UnsetAllDatums unsets all Datum values in the row.
+func (r EncDatumRow) UnsetAllDatums() {
+       for i := 0; i < len(r); i += emptyDatumRowChunk {
+               copy(r[i:], emptyDatumRow)
+       }
+}
+
 // EncDatumRows is a slice of EncDatumRows having the same schema.
 type EncDatumRows []EncDatumRow

diff --git a/pkg/sql/sqlbase/rowfetcher.go b/pkg/sql/sqlbase/rowfetcher.go
index a817b35cc..2d5f56a85 100644
--- a/pkg/sql/sqlbase/rowfetcher.go
+++ b/pkg/sql/sqlbase/rowfetcher.go
@@ -584,9 +584,7 @@ func (rf *RowFetcher) processKV(

                // Reset the row to nil; it will get filled in with the column
                // values as we decode the key-value pairs for the row.
-               for i := range table.row {
-                       table.row[i].UnsetDatum()
-               }
+               table.row.UnsetAllDatums()

                // Fill in the column values that are part of the index key.
                for i := range table.keyVals {
```

```
name                                old time/op  new time/op  delta
WideTableIgnoreColumns/Cockroach-4  11.4ms ± 1%  11.0ms ± 1%  -3.67%  (p=0.000 n=9+10)
```

It's not as much of an improvement as we're seeing here, but it might be a good alternative if we find this too risky.

**Comment by jordanlewis** [comment]
Thanks Nathan for the experiment! I want to play around to see if there's a way to unset only the things that we have to. `COUNT(*)` queries for example should never have to zero the memory, since none of the columns in the row are set at all.

I'm about to push a change that just gets rid of the nullability condition, and instead just unconditionally zeroes all needed columns. We could get fancy and have a hybrid approach I guess where if the needed columns form a contiguous block we zero them altogether, but I'm not sure if that's worth trying.

**Comment by jordanlewis** [comment]
The new numbers:

```
name                                old time/op    new time/op    delta
WideTableIgnoreColumns/Cockroach-8    12.2ms ± 1%    11.4ms ± 4%  -6.33%  (p=0.000 n=9+10)

name                                old alloc/op   new alloc/op   delta
WideTableIgnoreColumns/Cockroach-8    2.10MB ± 0%    2.09MB ± 0%  -0.22%  (p=0.034 n=10+8)

name                                old allocs/op  new allocs/op  delta
WideTableIgnoreColumns/Cockroach-8     1.37k ±25%     1.32k ±29%    ~     (p=0.352 n=10+10)
```

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21572#-:-L3EZxblgjwTzW40UV6Z:bnfp4nl)*

**Review by nvb — APPROVED** [review]
Nice!

**Pull request merged**
