### PR TITLE
workload/tpcc: move tpcc error checks before length checks

### LINKED ISSUE #102004: roachtest/tpcc: consistency check 3.3.2.4 failed with different lengths
roachtest.import/tpcc/warehouses=1000/nodes=32 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/9721214?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/9721214?buildTab=artifacts#/import/tpcc/warehouses=1000/nodes=32) on master @ [8124bff03d073f35f4d2b6a2048c7f4417d757d9](https://github.com/cockroachdb/cockroach/commits/8124bff03d073f35f4d2b6a2048c7f4417d757d9):

```
test artifacts and logs in: /artifacts/import/tpcc/warehouses=1000/nodes=32/run_1
(cluster.go:2008).Run: output in run_145238.588182591_n1_cockroach-workload-f: ./cockroach workload fixtures import tpcc --warehouses=1000 --csv-server='http://localhost:8081' returned: COMMAND_PROBLEM: ssh verbose log retained in ssh_145238.610230530_n1_cockroach-workload-f.log: exit status 1
(monitor.go:127).Wait: monitor failure: monitor task failed: t.Fatal() was called
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=true</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-sessions
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*import/tpcc/warehouses=1000/nodes=32.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-27212

### PR DESCRIPTION
**Pull request by DrewKimball**
Some of the TPCC consistency checks ensure that the number of rows returned by two queries is the same. This is done by checking that if one of the iterators returns false, they both do. However, if one of the iterators encounters an error, it will return false even though there are still rows left. This could cause the consistency check to seem as if it failed with incorrect results:
```
Error: check failed: 3.3.2.4: at 1682088974198157583.0000000000: length of order.sum(o_ol_cnt) != order_line.count(*)
```
when really one of the iterators just encountered an error. This patch moves the error-checking before the length checking, so that the correct error message is returned.

Fixes #102004

Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102081#-:-NTkUUmg65YK96zLfxNu:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2)

**Review by srosenberg — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102081)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @michae2)

___
*[`pkg/workload/tpcc/checks.go` line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102081#-NTko7Z48THxHa9iOhhc:-NTko7Z5CVmTdeKb0WlJ:bdxw6rf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0545913ede29a681dbeef9a6f1211d8b95395c5e/pkg/workload/tpcc/checks.go#L157)):*
> ```Go
> 	retErr = errors.CombineErrors(retErr, newOrderRows.Err())
> 	return errors.CombineErrors(retErr, orderRows.Err())
> }
> ```

Don't we want to keep this logic? What if there are multiple consistency check failures?

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102081)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @srosenberg)

___
*[`pkg/workload/tpcc/checks.go` line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102081#-NTko7Z48THxHa9iOhhc:-NW45ztMCLrHu6qsthwu:b-7ocrqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/0545913ede29a681dbeef9a6f1211d8b95395c5e/pkg/workload/tpcc/checks.go#L157)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Don't we want to keep this logic? What if there are multiple consistency check failures?
</blockquote></details>

Good point, I'll combine them.

**Comment by DrewKimball** [comment]
I don't think we've seen this failure again, so I'll merge this fix on master, and we can backport later if need be.

**Comment by DrewKimball** [comment]
TFTRs!

bors r+

**Comment by DrewKimball** [comment]
blathers backport 23.1 22.2

**Pull request merged**
