### PR TITLE
ttl: remove unused const expiredRowsPerRange

### LINKED ISSUE #86838: testutils/lint: TestLint failed
testutils/lint.TestLint [failed](https://server-url-not-found-in-env.com/buildConfiguration/Cockroach_UnitTests_Check/6230674?buildTab=log) with [artifacts](https://server-url-not-found-in-env.com/buildConfiguration/Cockroach_UnitTests_Check/6230674?buildTab=artifacts#/) on master @ [ec73c69d203f9018d308e7798b382f289d470092](https://github.com/cockroachdb/cockroach/commits/ec73c69d203f9018d308e7798b382f289d470092):

```
=== RUN   TestLint
--- FAIL: TestLint (1073.75s)
=== RUN   TestLint/TestStaticCheck
    lint_test.go:1773: 
        pkg/sql/ttl/ttljob/ttljob_test.go:423:10: const expiredRowsPerRange is unused (U1000)
    --- FAIL: TestLint/TestStaticCheck (863.73s)
```
<p>Parameters: <code>GOFLAGS=-json</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLint.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-18961

### PR DESCRIPTION
**Pull request by ecwall**
fixes https://github.com/cockroachdb/cockroach/issues/86838

Release justification: Linter fix.
Release note: None

### CODE REVIEW

**Review by knz — APPROVED** [review]

**Comment by ecwall** [comment]
bors r=knz

**Comment by knz** [comment]
@cockroachdb/dev-inf could you perhaps assist here, as to why the bazel essential CI fails?

**Comment by ecwall** [comment]
bors retry

**Pull request merged**
