### PR TITLE
jobs: tiny improvement to error handling

### LINKED ISSUE #56999: jobs: stray `log.ReportOrPanic` in adopt.go
This:

```go
       default:
        logcrash.ReportOrPanic(⋄, ∅, "unexpected job status")
```

Has two shortcomings:

- should probably `return errors.AssertionFailedf(...)` instead
- should include more details (e.g. the actual observed status and possibly some anonymized payload fields) to ease troubleshooting

### PR DESCRIPTION
**Pull request by jordanlewis**
Closes #56999

Release note: None

### CODE REVIEW

**Review by postamar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57307)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @knz)

___
*[pkg/jobs/adopt.go, line 312 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57307#-MNUSkN-0XRyYaz3o-FH:-MNUSkN-0XRyYaz3o-FI:b-wrpvkd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cec27be1e8cd171586cfeb2b68f5adf5363bd2a/pkg/jobs/adopt.go#L312)):*
> ```Go
> 					id, s.ID())
> 			default:
> 				return errors.AssertionFailedf("unexpected job status %s: %v", job)
> ```

Your format string expects two arguments here and you've only provided one. Did you mean `statusString, job` instead of only `job`?

**Review by ajwerner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57307#-:-MNUpwrlBS3Sly8GNK9i:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @knz)

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57307)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @postamar)

___
*[pkg/jobs/adopt.go, line 312 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57307#-MNUSkN-0XRyYaz3o-FH:-MNUqSHDCTHhI8q6wzQ_:bjgf9k0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cec27be1e8cd171586cfeb2b68f5adf5363bd2a/pkg/jobs/adopt.go#L312)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Your format string expects two arguments here and you've only provided one. Did you mean `statusString, job` instead of only `job`?
</blockquote></details>

Quite right - fixed.

**Review by postamar — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57307#-:-MNUrpxm8EXoioVzCVG4:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @knz)

**Review by knz — APPROVED** [review]
:lgtm: with nit

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57307#-:-MNYX6YaE1Obn_3vnQoU:b-xv64lu)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @jordanlewis)

___
*[pkg/jobs/adopt.go, line 262 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57307#-MNYXOUjD8GMamDmyQYr:-MNYXOUjD8GMamDmyQYs:bn2qzst) ([raw file](https://github.com/cockroachdb/cockroach/blob/4806820ae4a95712ad084ad4637190dae7b46c2a/pkg/jobs/adopt.go#L262)):*
> ```Go
> 		// comment this out.
> 		// if errors.HasAssertionFailure(err) {
> 		// 	logcrash.ReportOrPanic(ctx, nil, err.Error())
> ```

Can you update this comment too?
(ditto the one in `deprecated.go`)

**Comment by jordanlewis** [comment]
Hmm, I don't understand those comments. @lucy-zhang?

**Review by thoszhang — COMMENTED** [review]
The introduction of the `ReportOrPanic` calls was originally so that we could have tests crash in contexts where we don't actually want to crash or return errors in production. I commented it out because it was causing test crashes in contexts where we actually wanted failures (IIRC). So if we don't want to call `ReportOrPanic` anymore, then none of the commented-out lines are relevant anymore and should just be removed.

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57307#-:-MN_BzW3E7py4Q3B3Cnj:b-tsz9y6)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @jordanlewis)

**Pull request merged**
