### PR TITLE
roachtest: update 21.2 version map to v21.1.14

### PR DESCRIPTION
**Pull request by aliher1911**
Release note: None

### CODE REVIEW

**Review by celiala — CHANGES_REQUESTED** [review]
previous version map PRs haven't included `pkg/ui/yarn-vendor` or `vender` -- I think they should be left out?

**Review by jlinder — COMMENTED** [review]
Why are `pkg/ui/yarn-vendor` and `vendor` getting updated too?

**Comment by aliher1911** [comment]
Uh oh, let me take a look on why it was included.

**Review by celiala — APPROVED** [review]
:lgtm:

**Comment by aliher1911** [comment]
So when script changed branch from master, vendors dir didn't update. I can see that in the log, but not sure what caused that.

**Pull request merged**
