### PR TITLE
multitenant: re-enable admission control fairness tests

### LINKED ISSUE #82033: roachtest: re-enable admission control fairness tests
roachtest.multitenant/fairness/kv/concurrency-skew/no-admission [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/5305827?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/5305827?buildTab=artifacts#/multitenant/fairness/kv/concurrency-skew/no-admission) on master @ [e6815947a050e32f21e983aa30dc74ab2a247af3](https://github.com/cockroachdb/cockroach/commits/e6815947a050e32f21e983aa30dc74ab2a247af3):

```
	cluster.go:1913,multitenant_utils.go:92,panic.go:1047,test_impl.go:254,cluster.go:1913,multitenant_utils.go:92,panic.go:1047,test_impl.go:254,cluster.go:1913,multitenant_utils.go:92,panic.go:1047,test_impl.go:254,cluster.go:1913,multitenant_utils.go:92,panic.go:1047,test_impl.go:254,monitor.go:127,multitenant_fairness.go:243,multitenant_fairness.go:72,test_runner.go:884: cluster.RunE: context canceled
		(1) attached stack trace
		  -- stack trace:
		  | main.(*clusterImpl).RunE
		  | 	main/pkg/cmd/roachtest/cluster.go:1930
		  | main.(*clusterImpl).Run
		  | 	main/pkg/cmd/roachtest/cluster.go:1911
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*tenantNode).stop
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/multitenant_utils.go:92
		  | runtime.gopanic
		  | 	GOROOT/src/runtime/panic.go:1047
		  | main.(*testImpl).Fatal
		  | 	main/pkg/cmd/roachtest/test_impl.go:254
		  | main.(*clusterImpl).Run
		  | 	main/pkg/cmd/roachtest/cluster.go:1913
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*tenantNode).stop
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/multitenant_utils.go:92
		  | runtime.gopanic
		  | 	GOROOT/src/runtime/panic.go:1047
		  | main.(*testImpl).Fatal
		  | 	main/pkg/cmd/roachtest/test_impl.go:254
		  | main.(*clusterImpl).Run
		  | 	main/pkg/cmd/roachtest/cluster.go:1913
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*tenantNode).stop
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/multitenant_utils.go:92
		  | runtime.gopanic
		  | 	GOROOT/src/runtime/panic.go:1047
		  | main.(*testImpl).Fatal
		  | 	main/pkg/cmd/roachtest/test_impl.go:254
		  | main.(*clusterImpl).Run
		  | 	main/pkg/cmd/roachtest/cluster.go:1913
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*tenantNode).stop
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/multitenant_utils.go:92
		  | runtime.gopanic
		  | 	GOROOT/src/runtime/panic.go:1047
		  | main.(*testImpl).Fatal
		  | 	main/pkg/cmd/roachtest/test_impl.go:254
		  | main.(*monitorImpl).Wait
		  | 	main/pkg/cmd/roachtest/monitor.go:127
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.runMultiTenantFairness
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/multitenant_fairness.go:243
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerMultiTenantFairness.func3
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/multitenant_fairness.go:72
		  | main.(*testRunner).runTest.func2
		  | 	main/pkg/cmd/roachtest/test_runner.go:884
		  | runtime.goexit
		  | 	GOROOT/src/runtime/asm_amd64.s:1581
		Wraps: (2) cluster.RunE
		Wraps: (3) context canceled
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *errors.errorString
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*multitenant/fairness/kv/concurrency-skew/no-admission.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-16176

### PR DESCRIPTION
**Pull request by cucaroach**
Previously these tests were disabled for being flakey. Re-enable them
and increase tenant resource limits to prevent throughput collapse,
not sure why this wasn't an issue originally. Also disable running the
tests w/o admission control as that mode is flakey and no longer of
interest.

Also includes some commented out code to attempt to use prometheus
graphana, I couldn't get it to work but its probably close.

Fixes: #82033, #83994

Release note: None

### CODE REVIEW

**Comment by irfansharif** [comment]
Spoke to Tommy, going to take over this PR.

**Comment by irfansharif** [comment]
+cc @andrewbaptist, @sumeerbhola this is now ready for a look. https://www.loom.com/share/3fcbc44fd3f04650b5e5b702b6d9d21d is what the prometheus dashboard looks like. Probably a lot of the roachtest primitives for multi-tenant tests can be improved (it's a bit odd that the workload binary and the tenant SQL pods are physically colocated), but leaving things as is for now.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89721#-:-NIYoa6k83ylzXONIl8d:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach, @renatolabs, and @smg260)

___
*[`pkg/cmd/roachtest/tests/admission_control_multitenant_fairness.go` line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89721#-NIYo5MR36RL00AUohqA:-NIYo5MR36RL00AUohqB:b3dc7jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/184c154e778f0f1eeb860d6cca9ce36829a8444f/pkg/cmd/roachtest/tests/admission_control_multitenant_fairness.go#L40)):*
> ```Go
> //
> // [1]: Co-locating the SQL pod and the workload generator is a bit funky, but
> //
> ```

nit: remove empty line
___
*[`pkg/cmd/roachtest/tests/multitenant_fairness.go` line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89721#-NIYn5Vw9SctU38Rfeq3:-NIYn5Vw9SctU38Rfeq4:baqgnrh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6dcbb0b59836aaf263bd605aaf444735f3ab92d/pkg/cmd/roachtest/tests/multitenant_fairness.go#L55)):*
> ```Go
> 		{
> 			name:        "concurrency-skew",
> 			concurrency: func(i int) int { return i * 250 },
> ```

btw, do we see the same throughput across the different tenants for the concurrency-skew tests (both for the CPU and store overload setups)? IIRC, we had inconclusive results earlier and it was not clear to me why -- sometimes it seemed that the cause was that the minimum concurrency was insufficient to use 1/4th of the bottleneck resource.

**Review by irfansharif — COMMENTED** [review]
TFTR!

bors r+

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89721#-:-NIZ7_hYDL1uVvgARlfz:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @renatolabs, @smg260, and @sumeerbhola)

___
*[`pkg/cmd/roachtest/tests/admission_control_multitenant_fairness.go` line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89721#-NIYo5MR36RL00AUohqA:-NIZ9fGi4WXtFGPGlj0J:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/af396e7fefa573cbd73fa3b6a1eaeec42516334c/pkg/cmd/roachtest/tests/admission_control_multitenant_fairness.go#L40)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: remove empty line
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/tests/multitenant_fairness.go` line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89721#-NIYn5Vw9SctU38Rfeq3:-NIZ7cLX7mvG8S1oGydm:binlu6r) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6dcbb0b59836aaf263bd605aaf444735f3ab92d/pkg/cmd/roachtest/tests/multitenant_fairness.go#L55)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

btw, do we see the same throughput across the different tenants for the concurrency-skew tests (both for the CPU and store overload setups)? IIRC, we had inconclusive results earlier and it was not clear to me why -- sometimes it seemed that the cause was that the minimum concurrency was insufficient to use 1/4th of the bottleneck resource.
</blockquote></details>

We see the same throughput across the different tenants in `read-heavy/skewed`:



The second one, `write-heavy/skewed` is a bit more interesting. We see something like this. The periods where there is a skew in throughput are where we're not hitting the admission IO threshold (more apparent at the start), but as soon as we do, we do see that throughput is made identical. The oscillations between both regimes is interesting, and doesn't look desirable.

**Pull request merged**
