### PR TITLE
scripts/gceworker: fix auto shutdown

### LINKED ISSUE #9170: gceworker: auto-shutdown doesn't work
We switched the used image to ubuntu-xenial yesterday and the auto-shutdown snippet doesn't work any more. The reason is that we used to detect a pending shutdown via `pgrep -flx /lib/systemd/systemd-shutdownd`, but ubuntu doesn't have that process running.

It wasn't immediately obvious to me how to detect a scheduled shutdown in that setting, despite a bit of googling.

### PR DESCRIPTION
**Pull request by tamird**
Closes #9170.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9203)

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM. You gave this a test ride, right?

**Comment by tamird** [comment]
Sure did.

**Comment by tschottdorf** [comment]
Merging this for you.

**Comment by RaduBerinde** [comment]
I didn't see my worker power off.. This crontab line looks very broken to me. Doesn't it end up rescheduling the shutdown once per minute? And shouldn't that be a `||` instead of `&&` after the `grep`? We want to shutdown if `grep` *fails* to find `pts`..

Here's the output of running that command repeatedly while I'm logged in, and without `--no-wall`

```
root@gceworker171:~# rm -f /etc/nologin; (test -f /.active && /sbin/shutdown -c --no-wall || w -hs | grep -q pts && /sbin/shutdown -h +10)
Shutdown scheduled for Wed 2016-09-14 20:19:11 UTC, use 'shutdown -c' to cancel.
root@gceworker171:~# rm -f /etc/nologin; (test -f /.active && /sbin/shutdown -c --no-wall || w -hs | grep -q pts && /sbin/shutdown -h +10)
Shutdown scheduled for Wed 2016-09-14 20:19:12 UTC, use 'shutdown -c' to cancel.
root@gceworker171:~# rm -f /etc/nologin; (test -f /.active && /sbin/shutdown -c --no-wall || w -hs | grep -q pts && /sbin/shutdown -h +10)
Shutdown scheduled for Wed 2016-09-14 20:19:13 UTC, use 'shutdown -c' to cancel.
```

**Comment by RaduBerinde** [comment]
Oh sorry, I understand the intention. We do want to keep rescheduling the shutdown as long as we are logged in. Will try to investigate more.

**Comment by tschottdorf** [comment]
If you do `scripts/gceworker.sh start` but then never log in for one of the cron runs, I believe the worker wouldn't shut down.

We should make sure that `start` schedules a shutdown.

**Comment by RaduBerinde** [comment]
Ah good point, I think that was it. It did shut down now when I tried again.

**Comment by tschottdorf** [comment]
May I trouble you with a fix for this? Starting a gceworker and then forgetting that I ran that is one of my favorite pastimes and I'm probably not alone.

**Comment by RaduBerinde** [comment]
Yes, should be very easy.

**Comment by RaduBerinde** [comment]
Hm, I tried to add a call to `/sbin/shutdown --no-wall -h +10` after setting up the crontab but I get `Failed to call ScheduleShutdown in logind, proceeding with immediate shutdown: Interactive authentication required.`.  Will need to find a way to work around it.

**Comment by tschottdorf** [comment]
setting up the crontab only happens when you setup the machine, so that's the wrong place to begin with. I pictured you'd just add another invocation of `gcloud ... ssh` which explicitly schedules a shutdown.

**Comment by RaduBerinde** [comment]
Yeah I was thinking of creation. Running a `gcloud ssh` in the `start` section would work, but it would be ideal if we found something that also works if you power on the VM from the GCE console. Will try to find something.

**Comment by tschottdorf** [comment]
Tried `@reboot /path/to/script` in the crontab file?
You could simply shut down the instance at the end of creation.

**Comment by RaduBerinde** [comment]
Nice, that should work. I was going the route of writing a full blown script, and touching a file in /dev/shm to see if it's the first invocation this power cycle haha

**Pull request merged**
