### PR TITLE
ui: Add timescale component to statement details and transaction details pages

### PR DESCRIPTION
**Pull request by jocrl**
Addresses #74512

This commit adds the time selection component to the Statement Details
(Overview and Explain Plan tabs) and Transaction Details pages.

If staying on the same Statement/Transaction details page and switching to a
time that there is no data for, the Overview and Explain Plan tabs on the
Statement Details page, and the Transaction details page will continue to show
the statement/transaction text. The Diagnostics tab on the Statement Details
page will also continue to work as usual. However, these features are not
available if landing directly on a Statement/Transactions Details page for a
time frame with no data, without having previously switched from a time frame
that did have data for the same statement/transaction.

This commit also removes the aggregatedTs match param from the Transaction
Details page URL, since this is insufficient to specify a time frame and to bring
it in line with the Statement Details page.

This commit also fixes Transaction Details page stories that were previously out
of date and broken. The Statement Details Explain Plan tab story was already
previously broken and is not fixed here.

DB Console video: https://www.loom.com/share/545f6e0965914b17a0e05264ac95ad95
CC Console video: https://www.loom.com/share/85e83e24562d4a909b875c7c89d7baf9

The addition of this to CC Console needs to be coordinated with merging https://github.com/cockroachlabs/managed-service/pull/8592.

Release note (ui): The time selection component previously on the Statements and
Transactions Pages has been added to the Statement Details Overview and Explain
Plan tabs, and the Transaction Details page.

### CODE REVIEW

**Comment by jocrl** [comment]
Just wanted to check @Annebirzin  if these screenshots look good? In terms of styling and places that I've added it to. The Statements and Transactions pages have "reset time" though the mockups do not; should I add that to the Details pages as well?
779784 statement details - overview
779784 statement details - explain plan
779784 transaction details

**Comment by Annebirzin** [comment]
@jocrl The placement is looking good! A couple of notes:
- small nit but the caret down arrow on the time picker dropdown looks really small, can we match the designs? 
- for the reset/ now button, I had logged this issue a while back for us to update the 'Reset time' link on the Statements/Transactions overview pages: https://github.com/cockroachdb/cockroach/issues/70997. Looks like that issue is closed but not sure we ever replaced the 'Reset time' button with the 'Now' button? (Those pages should match what we have here)

**Comment by jocrl** [comment]
Hello @kevin-v-ngo and @Annebirzin,
Per [this conversation](https://www.figma.com/file/xdmwvnFQd6KkO9RJ0XLDH0?node-id=4015:90729#153119328), we concluded that time picker should be added to be "Overview" and "Explain Plans" tabs, but not the "Diagnostics" tab or the to-be-removed "Execution Stats".

Related, there is a question of what happens if the user is on the "Overview" tab, them modifies the time selection such that there is no data available for that statement during that interval. In this situation, could I clarify:

1) My understanding from the code is that if there is no data during that time interval, then we will not be able to show any of the four tabs. Is this correct?
2) We should show the time picker (so that the user can select something else), and a message saying that there is no information. Should I also show the four tabs? I think that keeping the tabs would make the experience smoother (since it would seem like only the tab content is changing, and you don't have to move your mouse position to click back another interval). On the other hand, would that mean that we would have empty "Diagnostics" and "Execution Stats" tabs that you could click on, but just have a message about no data and no time picker? Concretely, 

Option 1: no tabs (I will fix the positioning of the error message)
image

Option 2: with tabs
image

3) Is this wording for not having data fine, or what should it be? `No data available for this time interval. Please select a different time interval.`

**Comment by Annebirzin** [comment]
@jocrl 
1. I think this is correct for the `Overview`, `Explain Plans` and `Execution Stats` tabs but will let Kevin verify. (Side note: once we add the metrics charts on the `Overview` tab, maybe we can show the empty charts which would indicate no data).

- For the `Diagnostics` tab, I was thinking about an example where you triggered a diagnostics bundle in the past. Today we show that diagnostics bundle with a status of either `waiting for query` or `Ready` with a download button. Would we still want to show those bundles instead of the no data banner? If so, I think we could show the current empty state or any existing bundles as we do today (screenshot below). 
Screen Shot 2022-02-28 at 3 40 11 PM
Screen Shot 2022-02-28 at 4 18 15 PM

2. I agree with keeping the four tabs. For the `Execution Stats` tab, as you said, maybe we can update the messaging to remove the timeframe references (ie. "No data available."). For the `Overview` and `Explain Plans` tabs, I was also wondering if it would make sense to show the SQL text box so that users can still identify the SQL statement? (see screenshots below).
Screen Shot 2022-02-28 at 4 20 36 PM
Screen Shot 2022-02-28 at 4 20 45 PM
Screen Shot 2022-02-28 at 4 34 01 PM

3. I think this messaging sounds okay. cc @stbof for any feedback on the alert messaging.

**Comment by stbof** [comment]
No data available for this time frame. Please select a different time frame. -> Data not available for this time frame. Select a different time frame.

**Comment by jocrl** [comment]
Hi @Annebirzin,

As an update, I've got keeping the SQL box working, and also noticed that we have this other error message for when the statement is returned in the response, but there are no stats. I'm unclear about the use case significance of this particular error, but it looks like this:

image

Mirroring that, how's this? (and cc @stbof in case it changes the desired text)
image

**Comment by Annebirzin** [comment]
@jocrl I'm wondering if we can use the blue alert banner for both of these states for consistency? (we are also using the blue banner style on the Statement overview page for a loading state warning) 

So the first warning would look like this: 
Screen Shot 2022-03-01 at 2 20 01 PM

thoughts?

**Comment by stbof** [comment]
> Hi @Annebirzin,
> 
> As an update, I've got keeping the SQL box working, and also noticed that we have this other error message for when the statement is returned in the response, but there are no stats. I'm unclear about the use case significance of this particular error, but it looks like this:
> 
> image
> 
> Mirroring that, how's this? (and cc @stbof in case it changes the desired text) image

Please select a different time frame. -> Select a different time frame.

**Comment by jocrl** [comment]
Side notes for posterity:

1) Previously, I wrote in [this comment](https://github.com/cockroachdb/cockroach/pull/76687#issuecomment-1054720685) that I
> also noticed that we have this other error message for when the statement is returned in the response, but there are no stats ...

Marylia's changes to the statement details page has since removed this distinction, per the discussion here https://reviewable.io/reviews/cockroachdb/cockroach/77215#-MxBgW302pPezLpojMc3

So now there's only the time frame message.

2) Regarding not supporting the statement/transaction text/diagnostics tab if landing directly on the Statement/Transactions page for a time frame with no data, this is because our endpoint is currently structured to query for a specific time frame. In order to get data from the existing endpoint, one needs to know what time frame to query that would give back results, and the frontend currently doesn't know that. If do still want to show the statement if you hadn't previously loaded it before, I'm thinking it would probably be a backend change that we should break into a separate issue.

**Review by jocrl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76687)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[`pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx` line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76687#-N0fwgkR2XQ_WZ_pMyuL:-N0fwgkR2XQ_WZ_pMyuM:bmwfzjj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67668928b7d9bbfe3df5d293397585dca4ca9d6/pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx#L158)):*
> ```XML
>     if (
>       statementsForTransaction?.toString() !=
>         this.state.statementsForTransaction?.toString() ||
> ```

This `.toString` comparison was previously comparing something like `"[object Object]" != "[object Object]"`. It was also setting and storing an intermediate state, `statementsForTransaction`, that could be entirely derived via existing props. To fix the de-synced derived state caused by the faulty string comparison, I've pull this out of being "cached" on state and into `this.getStatementsForTransaction()`, to always be derived from props.



_Code quote:_
```XML
      statementsForTransaction?.toString() !=
        this.state.statementsForTransaction?.toString() ||
```
___
*[`pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetailsConnected.tsx` line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76687#-N0fwZ3HAt9gO7PDab22:-N0fwZ3HAt9gO7PDab23:bfq6n5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/92496a9099cf631279e75698d9e55d220f71d9a8/pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetailsConnected.tsx#L69)):*
> ```XML
>   state: AppState,
>   props: TransactionDetailsProps,
> ): TransactionDetailsStateProps => {
> ```

Prior to adding this `: TransactionDetailsStateProps` return type here, Typescript wasn't actually enforcing the type of the props being passed in `connect`. Which feels kinda scary - not sure if people have ideas about this.

In any case, adding the return type led to the complaint and realization that the `transaction` prop should really be of type `Transaction` and not of type `TransactionInfo`.



_Code quote:_
```XML
: TransactionDetailsStateProps
```

**Review by Azhng — COMMENTED** [review]
> Reviewed 12 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76687)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @jocrl)

___
*[`pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx` line 332 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76687#-N0koEmo0oGgzuoy8k-Z:-N0koEmo0oGgzuoy8k-_:b-4jdmec) ([raw file](https://github.com/cockroachdb/cockroach/blob/92496a9099cf631279e75698d9e55d220f71d9a8/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L332)):*
> ```XML
>   };
> 
>   getHasDiagnosticReports = (): boolean =>
> ```

small nit: probably just `hasDiagnosticsReports`? 
___
*[`pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx` line 424 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76687#-N0kpotu89fiBN2nA3k4:-N0kpotu89fiBN2nA3k5:b6j7vi5) ([raw file](https://github.com/cockroachdb/cockroach/blob/92496a9099cf631279e75698d9e55d220f71d9a8/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L424)):*
> ```XML
>       this.props.onStatementDetailsQueryChange("");
>       this.props.onStatementDetailsFormattedQueryChange("");
>     }
> ```

When statement fingerprint ID changes, it will also lead to change of `this.props.latestFormattedQuery` and `this.props.latestQuery` too as well, correct? It seems like the change has already being handled by the two `if` check above 
___
*[`pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx` line 637 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76687#-N0kxuI-2nuMAWzaSEYT:-N0kxuI-2nuMAWzaSEYU:bfor8n6) ([raw file](https://github.com/cockroachdb/cockroach/blob/92496a9099cf631279e75698d9e55d220f71d9a8/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L637)):*
> ```XML
>         <PageConfig>
>           <PageConfigItem>
>             <TimeScaleDropdown
> ```

Hmmm should the `TimeScaleDropDown` be pulled out and rendered at the top level `renderTabs()` ? Feels a bit more natural since this component is shared by all the tabs 
___
*[`pkg/ui/workspaces/cluster-ui/src/store/statementDetails/statementDetails.reducer.ts` line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76687#-N0kjGBwD3q7hWsOPaBb:-N0kjGBwD3q7hWsOPaBc:b-uf93gn) ([raw file](https://github.com/cockroachdb/cockroach/blob/92496a9099cf631279e75698d9e55d220f71d9a8/pkg/ui/workspaces/cluster-ui/src/store/statementDetails/statementDetails.reducer.ts#L88)):*
> ```XML
>         lastError: null,
>         inFlight: true,
>       };
> ```

Hm thoughts on just 

```typescript
delete state.cachedData[key]
```
___
*[`pkg/ui/workspaces/db-console/src/views/transactions/transactionDetails.tsx` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76687#-N0kwrzKA8yGYmkVyrlR:-N0kwrzKA8yGYmkVyrlS:bqhzu4h) ([raw file](https://github.com/cockroachdb/cockroach/blob/92496a9099cf631279e75698d9e55d220f71d9a8/pkg/ui/workspaces/db-console/src/views/transactions/transactionDetails.tsx#L32)):*
> ```XML
> import { setCombinedStatementsTimeScaleAction } from "src/redux/statements";
> 
> export const selectIsLoadingAndTransaction = createSelector(
> ```

nit: hmmm is this renaming necessary? I feel adding this `isLoading` flag is fine without this renaming
___
*[`pkg/ui/workspaces/db-console/src/views/transactions/transactionDetails.tsx` line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76687#-N0kxEim5aU2qtABMdQe:-N0kxEim5aU2qtABMdQf:b6nxpcq) ([raw file](https://github.com/cockroachdb/cockroach/blob/92496a9099cf631279e75698d9e55d220f71d9a8/pkg/ui/workspaces/db-console/src/views/transactions/transactionDetails.tsx#L81)):*
> ```XML
>           txnFingerprintIdAttr,
>         ),
>         isLoading,
> ```

minor nit: prefix it with props name? `isLoading: isLoading`

**Review by jocrl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76687)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[`pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx` line 332 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76687#-N0koEmo0oGgzuoy8k-Z:-N0lFBsQ5KyUsBBHA2H_:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/92496a9099cf631279e75698d9e55d220f71d9a8/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L332)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

small nit: probably just `hasDiagnosticsReports`? 
</blockquote></details>

Done



_Code quote:_
```XML
tementFingerprintI
```
___
*[`pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx` line 424 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76687#-N0kpotu89fiBN2nA3k4:-N0lFGXVCyjCLUL1IAJP:b4wm68q) ([raw file](https://github.com/cockroachdb/cockroach/blob/92496a9099cf631279e75698d9e55d220f71d9a8/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L424)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

When statement fingerprint ID changes, it will also lead to change of `this.props.latestFormattedQuery` and `this.props.latestQuery` too as well, correct? It seems like the change has already being handled by the two `if` check above 
</blockquote></details>

The two `if` checks above only replace the query and formatted query if the new one is not an empty string, which allows their preservation even if there is no data for the time frame. But if we switch fingerprint ids, we don't want to preserve them.

Does the added comment help?
___
*[`pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx` line 637 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76687#-N0kxuI-2nuMAWzaSEYT:-N0lG2wc3uulAXgG8mZg:b-a4vrnz) ([raw file](https://github.com/cockroachdb/cockroach/blob/92496a9099cf631279e75698d9e55d220f71d9a8/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L637)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmmm should the `TimeScaleDropDown` be pulled out and rendered at the top level `renderTabs()` ? Feels a bit more natural since this component is shared by all the tabs 
</blockquote></details>

It's only present in the overview and explain plan tabs. They both also have a sql box, but with different widths.
Would you still think of pulling the `TimeScaleDropDown` out? I think it'd just be the `<PageConfig>...</PageConfig>` bit.
___
*[`pkg/ui/workspaces/cluster-ui/src/store/statementDetails/statementDetails.reducer.ts` line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76687#-N0kjGBwD3q7hWsOPaBb:-N0lH4VU0NQu1uUK-JB0:bonv7hl) ([raw file](https://github.com/cockroachdb/cockroach/blob/92496a9099cf631279e75698d9e55d220f71d9a8/pkg/ui/workspaces/cluster-ui/src/store/statementDetails/statementDetails.reducer.ts#L88)):*
> delete state.cachedData[key]
Hmm, I'm thinking that if we refresh we want `inFlight: true`? Otherwise that would be like invalidating, but really we want to invalidate and get new stuff.
___
*[`pkg/ui/workspaces/db-console/src/views/transactions/transactionDetails.tsx` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76687#-N0kwrzKA8yGYmkVyrlR:-N0lI9Co8zrxbZTrgLS4:b-ty9qp) ([raw file](https://github.com/cockroachdb/cockroach/blob/92496a9099cf631279e75698d9e55d220f71d9a8/pkg/ui/workspaces/db-console/src/views/transactions/transactionDetails.tsx#L32)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: hmmm is this renaming necessary? I feel adding this `isLoading` flag is fine without this renaming
</blockquote></details>

Done; reverted



_Code quote:_
```XML
selectIsLoadingAndTransaction
```
___
*[`pkg/ui/workspaces/db-console/src/views/transactions/transactionDetails.tsx` line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76687#-N0kxEim5aU2qtABMdQe:-N0lIUkY3vGq0SShppyO:b-fpy49v) ([raw file](https://github.com/cockroachdb/cockroach/blob/92496a9099cf631279e75698d9e55d220f71d9a8/pkg/ui/workspaces/db-console/src/views/transactions/transactionDetails.tsx#L81)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

minor nit: prefix it with props name? `isLoading: isLoading` 
</blockquote></details>

Done, and done on both db-console and cluster-ui, and for statement details as well.

I'm not opinionated about this, but it seems like you would generally prefer not using the shorthand? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#new_notations_in_ecmascript_2015



_Code quote:_
```XML
timeScale: statementsTimeScaleLocalSetting.selector(state),
```

**Review by matthewtodd — APPROVED** [review]
:lgtm:

> Reviewed 19 of 24 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76687#-:-N14hlFY0emW7t9-5LJF:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng and @jocrl)

___
*[`pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx` line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76687#-N0fwgkR2XQ_WZ_pMyuL:-N14gzqe7AzAf9D1aJ5y:b-oxgb06) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67668928b7d9bbfe3df5d293397585dca4ca9d6/pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx#L158)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

This `.toString` comparison was previously comparing something like `"[object Object]" != "[object Object]"`. It was also setting and storing an intermediate state, `statementsForTransaction`, that could be entirely derived via existing props. To fix the de-synced derived state caused by the faulty string comparison, I've pull this out of being "cached" on state and into `this.getStatementsForTransaction()`, to always be derived from props.
</blockquote></details>

Good find!
___
*[`pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetailsConnected.tsx` line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76687#-N0fwZ3HAt9gO7PDab22:-N14hBkO-PbjXEjYz6IB:b44cckg) ([raw file](https://github.com/cockroachdb/cockroach/blob/92496a9099cf631279e75698d9e55d220f71d9a8/pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetailsConnected.tsx#L69)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

Prior to adding this `: TransactionDetailsStateProps` return type here, Typescript wasn't actually enforcing the type of the props being passed in `connect`. Which feels kinda scary - not sure if people have ideas about this.

In any case, adding the return type led to the complaint and realization that the `transaction` prop should really be of type `Transaction` and not of type `TransactionInfo`.

</blockquote></details>

Yes, +1 to adding return types like this.

**Review by maryliag — APPROVED** [review]
great job! :lgtm: 

> Reviewed 19 of 24 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76687#-:-N15pEz-CK_WJYg63pBe:bkn1jlc)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @Azhng and @jocrl)

**Comment by jocrl** [comment]
TFTR!
bump @Azhng

**Review by Azhng — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76687)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @jocrl)

___
*[`pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx` line 424 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76687#-N0kpotu89fiBN2nA3k4:-N19whbR9PzSUxZOXX-w:bb6mt9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/92496a9099cf631279e75698d9e55d220f71d9a8/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L424)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

The two `if` checks above only replace the query and formatted query if the new one is not an empty string, which allows their preservation even if there is no data for the time frame. But if we switch fingerprint ids, we don't want to preserve them.

Does the added comment help?
</blockquote></details>

:+1:
___
*[`pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx` line 637 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76687#-N0kxuI-2nuMAWzaSEYT:-N19wxJK9mN_MW2kFWsy:b3wfu30) ([raw file](https://github.com/cockroachdb/cockroach/blob/92496a9099cf631279e75698d9e55d220f71d9a8/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L637)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

It's only present in the overview and explain plan tabs. They both also have a sql box, but with different widths.
Would you still think of pulling the `TimeScaleDropDown` out? I think it'd just be the `<PageConfig>...</PageConfig>` bit.
</blockquote></details>

Ah I see, I guess there's no need then

**Comment by jocrl** [comment]
TFTR!
bump @Azhng

**Pull request merged**
