### PR TITLE
server: add comments and various cleanups

### LINKED ISSUE #90550: server: background tasks incorrectly hang off the `server start` context
(found while working on #90384)

During server startup, in `(*Server).PreStart()` we have 2 contexts of interest:

- `ctx` is bound to the top-level CLI command, and is tracing the initialization of the server. It has a tracing span attached.
- `workersCtx` is a background context with a few log tags but no tracing span.

The *intention* is to use `workersCtx` for all async tasks spawned from there. 

However, as of this writing the following do not use `workersCtx`:

- `s.startSystemLogsGC()`
- `startPurgeOldSessions()`
- `s.ctSender.Run()` (this one likely not affected, because it doesn't generate trace events)
- `s.startAttemptUpgrade()` -- this is likely intentional: we probably want the ability to inspect a trace if the auto-upgrade fails. However, this intention should be marked with a comment.
- `s.node.tenantSettingsWatcher.Start()`
- `s.kvProber.Start()`
- `publishPendingLossOfQuorumRecoveryEvents()`

Jira issue: CRDB-20832

### LINKED ISSUE #90607: server: dup init of grpc server in secondary tenants
(found while working on https://github.com/cockroachdb/cockroach/pull/90384)

If you look at pkg/server/tenant.go, you see:
- `grpcServer := newGRPCServer(rpcContext)`  called a first time in makeTenantSQLServerArgs, used to initialize obspb.RegisterObsServer
- also, `grpcMain := newGRPCServer(args.rpcContext)`  called later in StartTenant, used to initialize all the other things / APIs.
- also, grpcMain overwrites `args.grpcServer` but fails to overwrite `args.grpc`, which means that drainServer hangs off the first one and not the second one as probably intended.

Jira issue: CRDB-20857

### PR DESCRIPTION
**Pull request by knz**
This PR is extracted from #90384 for ease of review.

First two commits from #90523.

Fixes #90550. 
Fixes #90607.

### CODE REVIEW

**Comment by knz** [comment]
NB: CI is failing for an unrelated reason, this is still good for review.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90608)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @knz)

___
*[`pkg/server/server.go` line 746 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90608#-NFEV2NEBSZHku0alhPs:-NFEV2NF0LO9_k_vhCGm:blrkdsz) ([raw file](https://github.com/cockroachdb/cockroach/blob/415640aa9975ac28f314f95a8eaad700ffd81f2e/pkg/server/server.go#L746)):*
> ```Go
> 	lateBoundServer := &Server{}
> 
> 	// Instantiate the API privilege checker.
> ```

I don't think most of these comments add anything. Consider getting rid of the ones that just say "instantiate this" or "create that".
___
*[`pkg/server/server.go` line 749 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90608#-NFEVGolE09SB7RaOea3:-NFEVGolE09SB7RaOea4:bbcjxw) ([raw file](https://github.com/cockroachdb/cockroach/blob/415640aa9975ac28f314f95a8eaad700ffd81f2e/pkg/server/server.go#L749)):*
> ```Go
> 	//
> 	// TODO(tbg): give adminServer only what it needs (and avoid circular deps).
> 	adminAuthzCheck := &adminPrivilegeChecker{
> ```

you sure you want to take this blame?
___
*[`pkg/server/server.go` line 833 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90608#-NFEVjS43qBFw9-xjllK:-NFEVjS5CHwl7zGa91yN:b6yo3or) ([raw file](https://github.com/cockroachdb/cockroach/blob/415640aa9975ac28f314f95a8eaad700ffd81f2e/pkg/server/server.go#L833)):*
> ```Go
> 	}
> 
> 	// The settings cache writer is responsible for persisting
> ```

consider putting this comment on `settingsCacheWriter`
___
*[`pkg/server/server.go` line 1304 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90608#-NFEWVRpB3aOvHXWSO5l:-NFEWVRpB3aOvHXWSO5m:btpyivt) ([raw file](https://github.com/cockroachdb/cockroach/blob/415640aa9975ac28f314f95a8eaad700ffd81f2e/pkg/server/server.go#L1304)):*
> ```Go
> 			}
> 		}
> 		// TODO(knz): Do we really want to write the listener files
> ```

Is anybody reading these files? Why do we write them at all?
If we write them for human consumption, I think writing them in all the stores makes sense if we write them at all (but I'm not sure writing them in any store is worth it).
___
*[`pkg/server/server.go` line 1693 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90608#-NFEXdwnAmiBkWzMwJyP:-NFEXdwoAh3tVo9tQLVa:btcfd3p) ([raw file](https://github.com/cockroachdb/cockroach/blob/415640aa9975ac28f314f95a8eaad700ffd81f2e/pkg/server/server.go#L1693)):*
> ```Go
> 
> 	// Enable the Obs Server.
> 	s.eventsServer.SetResourceInfo(state.clusterID, int32(state.nodeID), build.BinaryVersion())
> ```

why did this move?

Btw, when does the `eventsServer` start receiving RPCs? Doesn't this need to happen before `s.grpc.setMode(modeOperational)` ?

**Review by dhartunian — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90608)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/server/server.go` line 1695 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90608#-NFE_-JVDfoMxIFeD2yp:-NFE_-JVDfoMxIFeD2yq:bhueb90) ([raw file](https://github.com/cockroachdb/cockroach/blob/415640aa9975ac28f314f95a8eaad700ffd81f2e/pkg/server/server.go#L1695)):*
> ```Go
> 	s.eventsServer.SetResourceInfo(state.clusterID, int32(state.nodeID), build.BinaryVersion())
> 
> 	// Connect the enginers to the disk stats map constructor.
> ```

nit: s/enginers/engines/

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90608)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[`pkg/server/server.go` line 746 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90608#-NFEV2NEBSZHku0alhPs:-NFEfHWuBWSL5nyVnCDx:bk98qcx) ([raw file](https://github.com/cockroachdb/cockroach/blob/415640aa9975ac28f314f95a8eaad700ffd81f2e/pkg/server/server.go#L746)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't think most of these comments add anything. Consider getting rid of the ones that just say "instantiate this" or "create that".
</blockquote></details>

Understood. I need them to ease the side-by-side comparison when reviewing the upcoming #90384. We can simplify after that.
___
*[`pkg/server/server.go` line 749 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90608#-NFEVGolE09SB7RaOea3:-NFEfRAK7VYdU6_SAQlI:b-hsh6ix) ([raw file](https://github.com/cockroachdb/cockroach/blob/415640aa9975ac28f314f95a8eaad700ffd81f2e/pkg/server/server.go#L749)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

you sure you want to take this blame?
</blockquote></details>

I'm OK with it.
___
*[`pkg/server/server.go` line 833 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90608#-NFEVjS43qBFw9-xjllK:-NFEfaGY6m60nk-aTy_H:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/415640aa9975ac28f314f95a8eaad700ffd81f2e/pkg/server/server.go#L833)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

consider putting this comment on `settingsCacheWriter`
</blockquote></details>

Done.
___
*[`pkg/server/server.go` line 1304 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90608#-NFEWVRpB3aOvHXWSO5l:-NFEfb-S5ucxWBwWoPfd:brwhv09) ([raw file](https://github.com/cockroachdb/cockroach/blob/415640aa9975ac28f314f95a8eaad700ffd81f2e/pkg/server/server.go#L1304)):*
> Is anybody reading these files?
the one on the first store yes, it was a customer request (originally)

The Q is why this loop does not `break`. I suspect there was a break and it was removed when this code was piggy-backed to populate `encryptedStore`.

However, I want this commit to be feature-neutral so I'm going to leave it as is (with this comment) and come back to this later after #90384 merges.
___
*[`pkg/server/server.go` line 1693 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90608#-NFEXdwnAmiBkWzMwJyP:-NFEg-AdBUc4es_i7Vfy:bocvcdp) ([raw file](https://github.com/cockroachdb/cockroach/blob/415640aa9975ac28f314f95a8eaad700ffd81f2e/pkg/server/server.go#L1693)):*
> why did this move?

In #90384 we want the tenant server PreStart to align block-by-block with this function, to ease the review. In that function, we can't call SetResourceInfo before `sqlServer.preStart` has been called. So to preserve the alignment, I've moved this one here.

> Doesn't this need to happen before s.grpc.setMode(modeOperational) ?

Not necessarily no. In fact, in tenant.go it's done afterwards.
___
*[`pkg/server/server.go` line 1695 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90608#-NFE_-JVDfoMxIFeD2yp:-NFEggmm5BwVlG-Ng9oK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/415640aa9975ac28f314f95a8eaad700ffd81f2e/pkg/server/server.go#L1695)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: s/enginers/engines/
</blockquote></details>

Done.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90608)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @knz)

___
*[`pkg/server/server.go` line 1693 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90608#-NFEXdwnAmiBkWzMwJyP:-NFEnh-_8sX5fqqGjoWz:b-pchpxs) ([raw file](https://github.com/cockroachdb/cockroach/blob/415640aa9975ac28f314f95a8eaad700ffd81f2e/pkg/server/server.go#L1693)):*
> In #90384 we want the tenant server PreStart to align block-by-block with this function, to ease the review. 

Mind putting something in the commit message?

> > Doesn't this need to happen before s.grpc.setMode(modeOperational) ?

> Not necessarily no. In fact, in tenant.go it's done afterwards.

How come it doesn't?
I see the `eventServer` has [protection](https://github.com/cockroachdb/cockroach/blob/2675c7c0481bb33eb9f43f1c2b52c152fca3ae2d/pkg/obs/event_exporter.go#L501) against RPCs called before this info is set, but I'm not sure why I've added that protection / I'd be happy to remove it and rely on the contract that the service is not yet exposed (because `s.grpc.setMode(modeOperational)` has not yet been called).
What's the deal with the tenant startup code? Is there a problem with how the instance ID is allocated that prevents this `SetResourceInfo()` from being called early?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90608)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @dhartunian)

___
*[`pkg/server/server.go` line 1693 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90608#-NFEXdwnAmiBkWzMwJyP:-NFFaYvK92FrKxmfx0tN:bs0f5cp) ([raw file](https://github.com/cockroachdb/cockroach/blob/415640aa9975ac28f314f95a8eaad700ffd81f2e/pkg/server/server.go#L1693)):*
> Mind putting something in the commit message?

Done.

>  Is there a problem with how the instance ID is allocated that prevents this SetResourceInfo() from being called early?

Yes: the instance ID is allocated in `sqlServer.preStart`, and is not available before then.

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90608#-:-NFFf517DkOv6y_cA03V:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian and @knz)

___
*[`pkg/server/server.go` line 833 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90608#-NFEVjS43qBFw9-xjllK:-NFFdOvnC5Axz-ZMpN8R:b-b2hmpd) ([raw file](https://github.com/cockroachdb/cockroach/blob/415640aa9975ac28f314f95a8eaad700ffd81f2e/pkg/server/server.go#L833)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant "*only* on settingsCacheWriter" :P
But if you really like these comments, I'll leave you alone.
___
*[`pkg/server/server.go` line 1693 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90608#-NFEXdwnAmiBkWzMwJyP:-NFFdaobCOgTpoVHbbOX:b-dbzeu6) ([raw file](https://github.com/cockroachdb/cockroach/blob/415640aa9975ac28f314f95a8eaad700ffd81f2e/pkg/server/server.go#L1693)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

> Mind putting something in the commit message?

Done.

>  Is there a problem with how the instance ID is allocated that prevents this SetResourceInfo() from being called early?

Yes: the instance ID is allocated in `sqlServer.preStart`, and is not available before then.

</blockquote></details>

You're avoiding the question :)
Shouldn't we do whatever needs to be done such that the `eventServer` is properly initialized before it starts accepting RPCs? Like, pull the `tenantConnect` and the allocation of the instanceID out of `SQLServer.preStart`?
Except that I'm changing that `SQLServer.preStart()` method a bunch, so I guess I would not actually welcome the churn. So, if you agree, maybe just add a TODO with my name to initialize the `eventServer` earlier.
___
*[`pkg/server/settings_cache.go` line 30 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/90608#-NFFez9E7SwPzehy8x28:-NFFez9F7fiySs_bSRbo:bv8a5r6) ([raw file](https://github.com/cockroachdb/cockroach/blob/90e0a18b8774fae2c9db31b874a38243df4bd1ae/pkg/server/settings_cache.go#L30)):*
> ```Go
> )
> 
> // settingsCacheWriter is responsible for persisting
> ```

I continue to suspect that you don't have 80 col wrapping set up correctly in your editor :P

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90608)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @dhartunian)

___
*[`pkg/server/server.go` line 1693 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90608#-NFEXdwnAmiBkWzMwJyP:-NFJ3R-G5Ss0TfjQeKTI:b-yowdi6) ([raw file](https://github.com/cockroachdb/cockroach/blob/415640aa9975ac28f314f95a8eaad700ffd81f2e/pkg/server/server.go#L1693)):*
>  Like, pull the tenantConnect and the allocation of the instanceID out of SQLServer.preStart?

Sure, but then what?

Remember, in #90384 we want to separate into:
- a constructor, which initializes structures but does not activate network services
- a PreStart function which activates network services (not the one on SQLServer: the one on the top level tenant server)

instanceID cannot happen until prestart  starts running. So the constructor is really too early anyway.

I can imagine a world where we split sqlserver prestart into 2 phases, but anyway both phases will need to be called in the top level PreStart, not in the constructor like currently.
___
*[`pkg/server/settings_cache.go` line 30 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/90608#-NFFez9E7SwPzehy8x28:-NFJ4KYzDuTtr5sZlYez:b-50jmm5) ([raw file](https://github.com/cockroachdb/cockroach/blob/90e0a18b8774fae2c9db31b874a38243df4bd1ae/pkg/server/settings_cache.go#L30)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I continue to suspect that you don't have 80 col wrapping set up correctly in your editor :P
</blockquote></details>

It's because i copy-pasted the comment from the other file where it was indented in a function.

Fixed.

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90608#-:-NFJlmh922yJr8t81DFF:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian and @knz)

___
*[`pkg/server/server.go` line 1304 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90608#-NFEWVRpB3aOvHXWSO5l:-NFJlMn718awJ-4g7J8E:b34wot2) ([raw file](https://github.com/cockroachdb/cockroach/blob/415640aa9975ac28f314f95a8eaad700ffd81f2e/pkg/server/server.go#L1304)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

> Is anybody reading these files?
the one on the first store yes, it was a customer request (originally)

The Q is why this loop does not `break`. I suspect there was a break and it was removed when this code was piggy-backed to populate `encryptedStore`.

However, I want this commit to be feature-neutral so I'm going to leave it as is (with this comment) and come back to this later after #90384 merges.
</blockquote></details>

consider dropping this TODO. I still think it should either say more or not say anything at all. As written, I think at best it serves as a reminder for you and you alone to do something.
___
*[`pkg/server/server.go` line 1693 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90608#-NFEXdwnAmiBkWzMwJyP:-NFJl01I1_R9DdiaUq0k:b484e8x) ([raw file](https://github.com/cockroachdb/cockroach/blob/415640aa9975ac28f314f95a8eaad700ffd81f2e/pkg/server/server.go#L1693)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

>  Like, pull the tenantConnect and the allocation of the instanceID out of SQLServer.preStart?

Sure, but then what?

Remember, in #90384 we want to separate into:
- a constructor, which initializes structures but does not activate network services
- a PreStart function which activates network services (not the one on SQLServer: the one on the top level tenant server)

instanceID cannot happen until prestart  starts running. So the constructor is really too early anyway.

I can imagine a world where we split sqlserver prestart into 2 phases, but anyway both phases will need to be called in the top level PreStart, not in the constructor like currently.
</blockquote></details>

OK, let's see how the code ends up looking.

**Comment by knz** [comment]
> it serves as a reminder for you and you alone to do something.

yes i'll do something about it

**Comment by knz** [comment]
TFYR

bors r=andreimatei

**Comment by knz** [comment]
We need to either backport this specific commit 521aceeadd0c60ae844fbd02497264f5cda40b81

or, and that would be my preferred solution, the entirety of #90789 which is also solving issue #90521 (which we also care about).

**Comment by knz** [comment]
I'll do the specific commit already now, so we get a clean roachtest report in the 22.2 branch.

**Comment by nvanbenschoten** [comment]
Is that tracked in a release blocker somewhere?

For what it's worth, we saw https://github.com/cockroachdb/cockroach/issues/90692 all over `master` last week, but never anywhere else.

**Comment by knz** [comment]
oh I thought you were asking because 22.2 had the problem too?

If not, then we don't urgently need a backport no. I care more about #90789 when it lands.

**Pull request merged**
