### PR TITLE
ttljob: introduce sql.ttl.default_select_rate_limit cluster setting, ttl_select_rate_limit storage param

### LINKED ISSUE #110742: ttljob: introduce sql.ttl.default_select_rate_limit cluster setting, ttl_select_rate_limit storage param
Ideally, admission control (AC) should handle all shaping of traffic that affects a bottleneck resource. And AC is well suited to shaping TTL traffic when the bottleneck is CPU or write bandwidth. But we have seen production cases where the TTL job is run frequently and scans a large table quickly and saturates the provisioned read bandwidth and read IOPS. These two resource dimensions are not currently considered by admission control and the work involved to change that is substantial (tracked in https://github.com/cockroachdb/cockroach/issues/107623).

For the TTL case, we need a quick workaround for the above cases. The TTL job has an optional `sql.ttl.default_delete_rate_limit` that can be set to shape the writes, but we need one for the reads too, in cases where there few writes (e.g. the TTL job running every 24h, but usual expiry happening after 365 days). We should introduce an optional `sql.ttl.default_select_rate_limit` for these scenarios.

@ecwall 

----

Additionally, add a ttl_select_rate_limit storage param similar to ttl_delete_rate_limit.

Jira issue: CRDB-31587

Epic CRDB-18322

### PR DESCRIPTION
**Pull request by ecwall**
Fixes #110742
    
Add sql.ttl.default_select_rate_limit cluster setting and ttl_select_rate_limit table storage param to set TTL select rate limit. This sets the number of records per table per second per node that can be selected by the TTL job.

### CODE REVIEW

**Review by rafiss — COMMENTED** [review]
the change lgtm, just had one comment. i'll leave the final signoff to andy so he can get more familiar with this code.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112119#-:-NgVRAxnD3oV9A4Lprgp:b-99y4p5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890, @ecwall, and @yuzefovich)

___
*[`pkg/sql/ttl/ttlbase/ttl_helpers.go` line 113 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112119#-NgVQr9nCyN4CvjsKnaB:-NgVQr9nCyN4CvjsKnaC:b-8zxt5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/8dacf45cd5e764e6bcbc868b7582f2b0ced1a139/pkg/sql/ttl/ttlbase/ttl_helpers.go#L113)):*
> ```Go
> 	// Put the maximum tokens possible if there is no rate limit.
> 	if rl == 0 {
> 		rl = math.MaxInt64
> ```

for both this and GetDeleteRateLimit, can we make it so a value of 0 results in `quotapool.Inf()` being returned? the return type of this function probably will need to change to `quotapool.Limit`

**Comment by yuzefovich** [comment]
I took a casual glance, and it seems good to me, will defer to Foundations for detailed review.

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112119)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890 and @rafiss)

___
*[`pkg/sql/ttl/ttlbase/ttl_helpers.go` line 113 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112119#-NgVQr9nCyN4CvjsKnaB:-NgeK9if9ML-liv93L--:b-9ao59o) ([raw file](https://github.com/cockroachdb/cockroach/blob/8dacf45cd5e764e6bcbc868b7582f2b0ced1a139/pkg/sql/ttl/ttlbase/ttl_helpers.go#L113)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

for both this and GetDeleteRateLimit, can we make it so a value of 0 results in `quotapool.Inf()` being returned? the return type of this function probably will need to change to `quotapool.Limit`
</blockquote></details>

This is stored in the `execinfrapb.TTLSpec` protobuf so we would need to add a new float64 field and populate both until 25.1 at which point we could remove the old one. I think this can be done separately if we decide to do it.

**Review by andyyang890 — COMMENTED** [review]
:lgtm: just had two small questions

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112119#-:-NgvDObG7Fg4OZ0VmYuS:b48o8qu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ecwall and @rafiss)

___
*[`pkg/sql/storageparam/tablestorageparam/table_storage_param.go` line 334 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/112119#-NgvCDgyDHPa-GybaYLt:-NgvCDgyDHPa-GybaYLu:brx2aup) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9ec826cd3f7f12cfd91793a023ccf3c6f6e27b4/pkg/sql/storageparam/tablestorageparam/table_storage_param.go#L334)):*
> ```Go
> 				return err
> 			}
> 			if err := tabledesc.ValidateTTLRateLimit(key, val); err != nil {
> ```

Out of curiosity, is there a reason we forbid someone from resetting the rate limit to 0 using the SET functionality and force them to use RESET? It seems like the end result would be the same.
___
*[`pkg/sql/ttl/ttljob/ttljob_processor.go` line 83 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/112119#-NgvD1zWClEs_aT7d7dn:-NgvD1zWClEs_aT7d7do:b-47lo1e) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9ec826cd3f7f12cfd91793a023ccf3c6f6e27b4/pkg/sql/ttl/ttljob/ttljob_processor.go#L83)):*
> ```Go
> 	// todo(sql-foundations): Remove this in 25.1 for consistency with
> 	//  deleteRateLimit.
> 	if selectRateLimit == 0 {
> ```

Is this check necessary? Wouldn't `GetSelectRateLimit` handle setting the default value?

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112119)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andyyang890 and @rafiss)

___
*[`pkg/sql/storageparam/tablestorageparam/table_storage_param.go` line 334 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/112119#-NgvCDgyDHPa-GybaYLt:-NgxjsqS7_2HI1G-pOO_:bxdylye) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9ec826cd3f7f12cfd91793a023ccf3c6f6e27b4/pkg/sql/storageparam/tablestorageparam/table_storage_param.go#L334)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Out of curiosity, is there a reason we forbid someone from resetting the rate limit to 0 using the SET functionality and force them to use RESET? It seems like the end result would be the same.
</blockquote></details>

I think it is to avoid confusion over 0 meaning unlimited instead of disabled.
___
*[`pkg/sql/ttl/ttljob/ttljob_processor.go` line 83 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/112119#-NgvD1zWClEs_aT7d7dn:-Ngxk2t1AIGUU1sdMyh-:b-ve6rab) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9ec826cd3f7f12cfd91793a023ccf3c6f6e27b4/pkg/sql/ttl/ttljob/ttljob_processor.go#L83)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Is this check necessary? Wouldn't `GetSelectRateLimit` handle setting the default value?
</blockquote></details>

If the job starts on a node in the old version then the protobuf will deserialize into `ttlSpec` with a 0 value.

**Review by andyyang890 — APPROVED** [review]

**Pull request merged**
