### PR TITLE
sql/schemachanger: implement COMMENT ON in new schema changer

### LINKED ISSUE #77327: schemachanger: implement COMMENT ON ... statements
This could be a good learning experience for getting acquainted with the declarative schema changer. Doing this will give exposure to all layers:
1. the COMMENT ON statements need to have hooks in `scbuildstmt`,
2. the `scbuildstmt` dependencies need to have some kind of interface or interface method for retrieving existing comments,
3. the internal executor needs to be plumbed into the `scbuild` dependencies to implement that,
4. the test dependencies therefore also need to mock the above
5. we can get rid of the placeholder string constant `__placeholder_comment__`
6. the `toPublic` paths for the comment elements need to be defined in `opgen`
7. new ops for setting comments need to be defined in `scop`
8. they need to be implemented in `scmutationexec`
9. which might in turn require some plumbing in the `mutationVisitorState` in `scexec`
10. there'll be a bunch of data-driven tests in `schemachanger/...` that need updating as a result of all this.

Epic: CRDB-13602

Jira issue: CRDB-13529

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
Fixes #77327

This pr includes 3 commits:
(1) adding a metadata fetcher interface for reading comments from system.comments.
(2) implement COMMENT ON statements within schema changer.
(3) data driven tests.

This pr does not turn on the `fully implemented` flag for these statements.
But I tested them by hand with the flags on.
I think it'd be better to turn the flags on in a separate pr even the risk is low enough
to make it happen within this pr.

Release justification: not for 22.1
Release note: None

### CODE REVIEW

**Review by postamar — CHANGES_REQUESTED** [review]
Nicely done. This is close. I have only one concern, which relates to how you query `system.comments`, the rest is just little things.

> Reviewed 25 of 25 files at r1, 27 of 27 files at r2, 18 of 19 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-:-MzvQxhH9ji0WggheRQr:b4586p4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan)

___
*[pkg/sql/descmetadata/metadata_fetcher.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-MzujFs73zoq9VGysKyJ:-MzujFs73zoq9VGysKyK:b7jspfb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3324c282def52a66eb87561daab3b40f541a7127/pkg/sql/descmetadata/metadata_fetcher.go#L28)):*
> ```Go
> 	txn *kv.Txn
> 	ie  sqlutil.InternalExecutor
> }
> ```

I don't care much either way but if would have been completely OK in my book to have the existing `metadataUpdater` implement the `DescriptorMetadataFetcher` interface. Such as it is, these two structs are going to have the same dependencies anyway.
___
*[pkg/sql/descmetadata/metadata_fetcher.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-MzujfEID_Vw-4Vxx25f:-MzujfEID_Vw-4Vxx25g:b96qp8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/3324c282def52a66eb87561daab3b40f541a7127/pkg/sql/descmetadata/metadata_fetcher.go#L41)):*
> ```Go
> 		"SELECT type, sub_id, comment FROM system.comments WHERE object_id=$1",
> 		objectID,
> 	)
> ```

These point lookups are really going to hurt us at scale. For instance, we should consider a DROP DATABASE CASCADE with a 1000 tables to be perfectly normal. Here this will require 1k+ roundtrips.

So, we need batch lookups instead. On the other hand, we don't want to load the whole `comments` table in memory either, we want the query results to be capped by a constant upper bound.

It's safe to assume that this table is going to be empty or near-empty most of the time. Perhaps instead of querying the table just for the desired ID, it could do so for the 1000 IDs before and/or after and stuff them in your cache. This is just an idea to get you started, I'm sure you can think of something more sophisticated which will scale well.
___
*[pkg/sql/schemachanger/scbuild/builder_state.go, line 686 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-MzuuqJ9DYMIK1p-JcW1:-MzuuqJA-yvWdedgv_eC:b-utiptp) ([raw file](https://github.com/cockroachdb/cockroach/blob/87eee63208b2052a1facccba6faa23fa0f9f527f/pkg/sql/schemachanger/scbuild/builder_state.go#L686)):*
> ```Go
> 	// Use public schema by default.
> 	if !prefix.ExplicitSchema {
> 		prefix.SchemaName = "public"
> ```

Use the constant it `catconstants` instead of the `"public"` literal please.
___
*[pkg/sql/schemachanger/scbuild/dependencies.go, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-MzvOti34YRttTdx_96O:-MzvOti34YRttTdx_96P:b-x31xwv) ([raw file](https://github.com/cockroachdb/cockroach/blob/87eee63208b2052a1facccba6faa23fa0f9f527f/pkg/sql/schemachanger/scbuild/dependencies.go#L106)):*
> ```Go
> 	// MayResolveIndex looks up an index using a naked index name with database
> 	// and schema prefix. Resolved index and the owner table name are returned.
> 	MayResolveIndex(ctx context.Context, indexName tree.Name, prefix tree.ObjectNamePrefix) (catalog.Index, tree.TableName)
> ```

Perhaps have this return `(catalog.ResolvedObjectPrefix, catalog.TableDescriptor, catalog.Index)` instead?
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/comment_on.go, line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-MzvLe6_0gEhWBHjdVeL:-MzvKvEj9OP6kVbdI7aK:b-aceur7) ([raw file](https://github.com/cockroachdb/cockroach/blob/87eee63208b2052a1facccba6faa23fa0f9f527f/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/comment_on.go#L24)):*
> ```Go
> 	if n.Comment != nil {
> 		dc.Comment = *n.Comment
> 	}
> ```

I don't think this correctly distinguishes between SET NULL and SET '', though this should be easy to fix.
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/comment_on.go, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-MzvLnKT6lvTBbgrbAX1:-MzvLnKT6lvTBbgrbAX2:bib44wu) ([raw file](https://github.com/cockroachdb/cockroach/blob/87eee63208b2052a1facccba6faa23fa0f9f527f/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/comment_on.go#L43)):*
> ```Go
> 	if len(dc.Comment) > 0 {
> 		b.Add(dc)
> 	}
> ```

Perhaps it's just me but I somehow feel this code could be made more straightforward. I was able to convince myself it was correct, in the end. Perhaps it would help to distinguish the add and the drop cases more clearly?
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/comment_on.go, line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-MzvPMeN3_mVfdFpCJ7S:-MzvPMeN3_mVfdFpCJ7T:b-oy93i5) ([raw file](https://github.com/cockroachdb/cockroach/blob/87eee63208b2052a1facccba6faa23fa0f9f527f/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/comment_on.go#L152)):*
> ```Go
> 		IsExistenceOptional: false,
> 		RequiredPrivilege:   privilege.CREATE,
> 	}
> ```

nit: Since comment resolution params are always the same, consider defining one struct at the top level called `commentParams` or something.
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go, line 265 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-MzvKHbP5U5Tt6DfGoK5:-MzvKHbP5U5Tt6DfGoK6:bh00ckf) ([raw file](https://github.com/cockroachdb/cockroach/blob/87eee63208b2052a1facccba6faa23fa0f9f527f/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go#L265)):*
> ```Go
> 
> 	// ResolveTableWithIndexBestEffort retrieves a table which contains the target index and returns its elements.
> 	ResolveTableWithIndexBestEffort(indexName tree.Name, prefix tree.ObjectNamePrefix, p ResolveParams) ElementResultSet
> ```

Can you put `prefix` before `indexName` please? Also why not have this return the elements pertaining to the index instead of the table? It's what we care about ultimately. If you do this, you'll need to rename the method, naturally.
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go, line 62 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-Mzuv7Ul-KCLGTy3zo1R:-Mzuv7Ul-KCLGTy3zo1S:b-e7hjis) ([raw file](https://github.com/cockroachdb/cockroach/blob/87eee63208b2052a1facccba6faa23fa0f9f527f/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go#L62)):*
> ```Go
> 	reflect.TypeOf((*tree.CommentOnColumn)(nil)):     {CommentOnColumn, false},
> 	reflect.TypeOf((*tree.CommentOnIndex)(nil)):      {CommentOnIndex, false},
> 	reflect.TypeOf((*tree.CommentOnConstraint)(nil)): {CommentOnConstraint, false},
> ```

It's time to jump into the deep end of the pool, Chengxiong :grinning: 

Come on, mark these as fully-supported.
___
*[pkg/sql/schemachanger/scdecomp/dependencies.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-Mzum5LtEQDV1VHhRN9_:-Mzum5LtEQDV1VHhRN9a:bgjgogo) ([raw file](https://github.com/cockroachdb/cockroach/blob/3324c282def52a66eb87561daab3b40f541a7127/pkg/sql/schemachanger/scdecomp/dependencies.go#L82)):*
> ```Go
> 	// GetAllCommentsOnObject fetches all comments related to an object such as a
> 	// database, a schema or a table.
> 	GetAllCommentsOnObject(ctx context.Context, objectID int64) (*CommentCache, error)
> ```

I'm concerned that returning a `CommentCache` introduces yet another layer of indirection which in turn introduces more complexity in the "business logic" so to speak, when really this cache is an implementation detail. Would it be possible to have the interface implementation worry about caching instead? This means the `CommentCache` type wouldn't exist (at least not publicly) and this interface would instead have methods like `MayGetDatabaseComment(ctx context.Context, dbID catid.DescID) (comment string, found bool)` etc etc. 

This pushes the complexity further down, of course, but the schema changer is complex enough for that tradeoff to usually be worth it.

Note: please use `catid.DescID` types for descriptor IDs.
Note: we have nice cache implementations in `pkg/util/cache`
___
*[pkg/sql/schemachanger/scdeps/build_deps.go, line 328 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-Mzuo7pR1f3nXVjLxduJ:-Mzuo7pR1f3nXVjLxduK:btjwiil) ([raw file](https://github.com/cockroachdb/cockroach/blob/3324c282def52a66eb87561daab3b40f541a7127/pkg/sql/schemachanger/scdeps/build_deps.go#L328)):*
> ```Go
> // DescriptorMetadataFetcher implements the scbuild.Dependencies interface.
> func (d *buildDeps) DescriptorMetadataFetcher() scdecomp.DescriptorMetadataFetcher {
> 	return d.metadataFetcher
> ```

I'm not advocating my way over yours but have you considered instead plumbing an internal executor into the `buildDeps` and have this method instantiate a `DescriptorMetadataFetcher `?
___
*[pkg/sql/schemachanger/scdeps/sctestdeps/test_deps.go, line 255 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-MzvOPns0QHr16YzHe9B:-MzvOPns0QHr16YzHe9C:b-jgvvf5) ([raw file](https://github.com/cockroachdb/cockroach/blob/87eee63208b2052a1facccba6faa23fa0f9f527f/pkg/sql/schemachanger/scdeps/sctestdeps/test_deps.go#L255)):*
> ```Go
> 	}
> 	return nil, tree.TableName{}
> }
> ```

The fact that this method implementation largely mirrors that of the non-test implementation indicates that this code should be factored out of the interface into a helper function.
___
*[pkg/sql/schemachanger/scdeps/sctestutils/sctestutils.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-MzuokGC3x6ecToeKSuc:-MzuokGC3x6ecToeKSud:b-xe0lf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3324c282def52a66eb87561daab3b40f541a7127/pkg/sql/schemachanger/scdeps/sctestutils/sctestutils.go#L81)):*
> ```Go
> 		planner, /* authAccessor */
> 		planner, /* astFormatter */
> 		planner, /* featureChecker */
> ```

Thank you for this.
___
*[pkg/sql/schemachanger/scop/mutation.go, line 416 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-MzutJmT1fPpY97OEvcp:-MzutJmT1fPpY97OEvcq:be8gif4) ([raw file](https://github.com/cockroachdb/cockroach/blob/87eee63208b2052a1facccba6faa23fa0f9f527f/pkg/sql/schemachanger/scop/mutation.go#L416)):*
> ```Go
> 
> // AddTableComment is used to add a comment to a table.
> type AddTableComment struct {
> ```

Shouldn't these be named `UpsertTableComment` instead? This applies to all other comment ops, and the method names in `scexec`/`scmutationexec`, etc. According to the postgresql documentation there can be only at most one comment per object.
___
*[pkg/sql/schemachanger/screl/attr.go, line 75 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-Mzurg6G6W10jgh8sKh7:-Mzurg6G6W10jgh8sKh8:b-2o652c) ([raw file](https://github.com/cockroachdb/cockroach/blob/87eee63208b2052a1facccba6faa23fa0f9f527f/pkg/sql/schemachanger/screl/attr.go#L75)):*
> ```Go
> 	Comment
> 	// AttrMax is the largest possible Attr value.
> 	// Note: add any new enum values before TargetStatus, leave these at the end.
> ```

Please observe this comment.
___
*[pkg/sql/schemachanger/sctest/cumulative.go, line 223 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-MzusNfvDNR3YevJpNQA:-MzusNfvDNR3YevJpNQB:brplikb) ([raw file](https://github.com/cockroachdb/cockroach/blob/87eee63208b2052a1facccba6faa23fa0f9f527f/pkg/sql/schemachanger/sctest/cumulative.go#L223)):*
> ```Go
> 		// stages.
> 		postCommit = 0
> 		nonRevertible = 0
> ```

Nice catch! Shouldn't this be right after `n :=` instead?
___
*[pkg/bench/rttanalysis/testdata/benchmark_expectations, line 49 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-MzvPZnR0kkMCV5bwH8V:-MzvPZnR0kkMCV5bwH8W:bcldi3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/d996e7ee653c95be312d2515a9c0fae9a28db8a8/pkg/bench/rttanalysis/testdata/benchmark_expectations#L49)):*
> ```
> 20,DropView/drop_1_view
> 23,DropView/drop_2_views
> 26,DropView/drop_3_views
> ```

This is a manifestation of the nasty round-trip performance regression I was talking about in an earlier comment.
___
*[pkg/sql/schemachanger/testdata/comment_on, line 180 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-MzvQ1zCDs0C8MT4kd88:-MzvQ1zCDs0C8MT4kd89:br6hkl7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d996e7ee653c95be312d2515a9c0fae9a28db8a8/pkg/sql/schemachanger/testdata/comment_on#L180)):*
> ```
> delete comment for constraint on #107, constraint id: 2
> # end PreCommitPhase
> commit transaction #1
> ```

I appreciate this test suite but I'm not sure it's particularly interesting. The one in `scplan` is enough I think.
___
*[pkg/sql/schemachanger/scbuild/builder_test.go, line 157 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-Mzup577-RaF95Ig7-E5:-Mzup577-RaF95Ig7-E6:byaqwen) ([raw file](https://github.com/cockroachdb/cockroach/blob/87eee63208b2052a1facccba6faa23fa0f9f527f/pkg/sql/schemachanger/scbuild/builder_test.go#L157)):*
> ```Go
> 				t.Fatal("not a supported descriptor metadata statement")
> 			}
> 		}
> ```

I reviewed this whole switch block and really you should replace all of these cases with just `case "setup":` and `case "build":`. As far as I can tell all we ever want out of this is to `tdb.Exec` some parsed statements. See the data-driven tests in `scdecomp` for inspiration.
___
*[pkg/sql/schemachanger/scplan/plan_test.go, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-MzupbF74u7Og1yhbO1n:-MzupbF8BVrb1NPy58Ex:bfk87u9) ([raw file](https://github.com/cockroachdb/cockroach/blob/87eee63208b2052a1facccba6faa23fa0f9f527f/pkg/sql/schemachanger/scplan/plan_test.go#L106)):*
> ```Go
> 					}
> 				}
> 				return ""
> ```

Similar comment as for the data-driven build tests.

**Comment by chengxiong-ruan** [comment]
*[pkg/sql/descmetadata/metadata_fetcher.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-MzujfEID_Vw-4Vxx25f:-N-OG-h79PulwOFmjUQx:b48ii6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/3324c282def52a66eb87561daab3b40f541a7127/pkg/sql/descmetadata/metadata_fetcher.go#L41)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

These point lookups are really going to hurt us at scale. For instance, we should consider a DROP DATABASE CASCADE with a 1000 tables to be perfectly normal. Here this will require 1k+ roundtrips.

So, we need batch lookups instead. On the other hand, we don't want to load the whole `comments` table in memory either, we want the query results to be capped by a constant upper bound.

It's safe to assume that this table is going to be empty or near-empty most of the time. Perhaps instead of querying the table just for the desired ID, it could do so for the 1000 IDs before and/or after and stuff them in your cache. This is just an idea to get you started, I'm sure you can think of something more sophisticated which will scale well.
</blockquote></details>

@postamar Good callout. I initially thought this `comments` table was probably not very popular. But you're right that point lookup is bad in `DROP DATABASE CASCADE`'s case.
I do like the idea reading the first 1000 obj IDs starting from the db/schema/table ID in interest. With that in mind we would need to make the cache more like a cache. Like, for any later cache miss, we read the next batch of 1000 obj IDs starting from the missed ID to refresh the cache(we definitely need to record the id ranges covered by the cache). Though we would only benefit from this if the tables are looped through in ordered when a db or schema is dropped cascaded. Looks like the ordering is guaranteed based on the fact that we're using `FastIntSet` to store table ids when walking through backrefs of schemas. So I guess that's a proper assumption to make :) ?

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78025)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan and @postamar)

___
*[pkg/sql/schemachanger/scbuild/builder_state.go, line 686 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-MzuuqJ9DYMIK1p-JcW1:-N-Y5h_R26NlMyzL8yCv:b9badmu) ([raw file](https://github.com/cockroachdb/cockroach/blob/87eee63208b2052a1facccba6faa23fa0f9f527f/pkg/sql/schemachanger/scbuild/builder_state.go#L686)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Use the constant it `catconstants` instead of the `"public"` literal please.
</blockquote></details>

apologies for my laziness
___
*[pkg/sql/schemachanger/scbuild/dependencies.go, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-MzvOti34YRttTdx_96O:-N-YGWZe6aZTL44o9nPN:bdrnter) ([raw file](https://github.com/cockroachdb/cockroach/blob/87eee63208b2052a1facccba6faa23fa0f9f527f/pkg/sql/schemachanger/scbuild/dependencies.go#L106)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Perhaps have this return `(catalog.ResolvedObjectPrefix, catalog.TableDescriptor, catalog.Index)` instead?
</blockquote></details>

good point...it looks more consistent to the others. changed it to what you suggested
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/comment_on.go, line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-MzvLe6_0gEhWBHjdVeL:-N-YdyYB-ILPkKAZUTKM:b-k8hevy) ([raw file](https://github.com/cockroachdb/cockroach/blob/87eee63208b2052a1facccba6faa23fa0f9f527f/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/comment_on.go#L24)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I don't think this correctly distinguishes between SET NULL and SET '', though this should be easy to fix.
</blockquote></details>

should be more clear now :)
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/comment_on.go, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-MzvLnKT6lvTBbgrbAX1:-N-Ye1vn19bf-Z6n61hb:b-9jeh9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/87eee63208b2052a1facccba6faa23fa0f9f527f/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/comment_on.go#L43)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Perhaps it's just me but I somehow feel this code could be made more straightforward. I was able to convince myself it was correct, in the end. Perhaps it would help to distinguish the add and the drop cases more clearly?
</blockquote></details>

I agree with you! I changed it to have more clear branches for drop and add separately. let me know how that feels.
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/comment_on.go, line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-MzvPMeN3_mVfdFpCJ7S:-N-Yeul_1Jv26CCREWYV:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/87eee63208b2052a1facccba6faa23fa0f9f527f/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/comment_on.go#L152)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

nit: Since comment resolution params are always the same, consider defining one struct at the top level called `commentParams` or something.
</blockquote></details>

done.
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go, line 265 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-MzvKHbP5U5Tt6DfGoK5:-N-Ygkhc2xkptHw5t5KU:b-sb95v3) ([raw file](https://github.com/cockroachdb/cockroach/blob/87eee63208b2052a1facccba6faa23fa0f9f527f/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go#L265)):*
:thumbsup: 
> why not have this return the elements pertaining to the index instead of the table
I guess no good reason other than I wanted my logic in `CommentOnIndex` like find the table first, then resolve index. I don't feel strong about this though...
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go, line 62 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-Mzuv7Ul-KCLGTy3zo1R:-N-Z9CQ8ARrMRxNlO1bo:b-7j86os) ([raw file](https://github.com/cockroachdb/cockroach/blob/87eee63208b2052a1facccba6faa23fa0f9f527f/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go#L62)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

It's time to jump into the deep end of the pool, Chengxiong :grinning: 

Come on, mark these as fully-supported.
</blockquote></details>

sure~
___
*[pkg/sql/schemachanger/scdecomp/dependencies.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-Mzum5LtEQDV1VHhRN9_:-N-YhZRO9j18BldPVF3-:b-rj2cwd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3324c282def52a66eb87561daab3b40f541a7127/pkg/sql/schemachanger/scdecomp/dependencies.go#L82)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I'm concerned that returning a `CommentCache` introduces yet another layer of indirection which in turn introduces more complexity in the "business logic" so to speak, when really this cache is an implementation detail. Would it be possible to have the interface implementation worry about caching instead? This means the `CommentCache` type wouldn't exist (at least not publicly) and this interface would instead have methods like `MayGetDatabaseComment(ctx context.Context, dbID catid.DescID) (comment string, found bool)` etc etc. 

This pushes the complexity further down, of course, but the schema changer is complex enough for that tradeoff to usually be worth it.

Note: please use `catid.DescID` types for descriptor IDs.
Note: we have nice cache implementations in `pkg/util/cache`

</blockquote></details>

this concern should be addressed now with the new implementation of single layer cache.
___
*[pkg/sql/schemachanger/scdeps/build_deps.go, line 328 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-Mzuo7pR1f3nXVjLxduJ:-N-YhhO3-TCADhY9mrN9:b-yomehf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3324c282def52a66eb87561daab3b40f541a7127/pkg/sql/schemachanger/scdeps/build_deps.go#L328)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I'm not advocating my way over yours but have you considered instead plumbing an internal executor into the `buildDeps` and have this method instantiate a `DescriptorMetadataFetcher `?
</blockquote></details>

good suggestion, I changed it to what you suggested. it's better now since it make more sense to init a comment cache here.
___
*[pkg/sql/schemachanger/scdeps/sctestdeps/test_deps.go, line 255 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-MzvOPns0QHr16YzHe9B:-N-YmFsh2ER2Tr5hDghi:b-yidxzt) ([raw file](https://github.com/cockroachdb/cockroach/blob/87eee63208b2052a1facccba6faa23fa0f9f527f/pkg/sql/schemachanger/scdeps/sctestdeps/test_deps.go#L255)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

The fact that this method implementation largely mirrors that of the non-test implementation indicates that this code should be factored out of the interface into a helper function.
</blockquote></details>

the logic is factored out into `FindTableContainsIndex()` helper function.
___
*[pkg/sql/schemachanger/scop/mutation.go, line 416 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-MzutJmT1fPpY97OEvcp:-N-YmfXN8uakQVPugPYz:b6lhh0) ([raw file](https://github.com/cockroachdb/cockroach/blob/87eee63208b2052a1facccba6faa23fa0f9f527f/pkg/sql/schemachanger/scop/mutation.go#L416)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Shouldn't these be named `UpsertTableComment` instead? This applies to all other comment ops, and the method names in `scexec`/`scmutationexec`, etc. According to the postgresql documentation there can be only at most one comment per object.
</blockquote></details>

yes, indeed :)
___
*[pkg/sql/schemachanger/screl/attr.go, line 75 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-Mzurg6G6W10jgh8sKh7:-N-Yn9wi68BuVTGwj8yi:b-kl8g4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/87eee63208b2052a1facccba6faa23fa0f9f527f/pkg/sql/schemachanger/screl/attr.go#L75)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Please observe this comment.
</blockquote></details>

good catch!
___
*[pkg/sql/schemachanger/sctest/cumulative.go, line 223 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-MzusNfvDNR3YevJpNQA:-N-YnVWc3X8gnE58-Hf2:b-lnn9ke) ([raw file](https://github.com/cockroachdb/cockroach/blob/87eee63208b2052a1facccba6faa23fa0f9f527f/pkg/sql/schemachanger/sctest/cumulative.go#L223)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Nice catch! Shouldn't this be right after `n :=` instead?
</blockquote></details>

ha yeah, it would have the same effect but probably easier to reason about. moved it there.
___
*[pkg/bench/rttanalysis/testdata/benchmark_expectations, line 49 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-MzvPZnR0kkMCV5bwH8V:-N-Z8tbZ2XU9-4_xsKnw:b-sh2c2u) ([raw file](https://github.com/cockroachdb/cockroach/blob/d996e7ee653c95be312d2515a9c0fae9a28db8a8/pkg/bench/rttanalysis/testdata/benchmark_expectations#L49)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

This is a manifestation of the nasty round-trip performance regression I was talking about in an earlier comment.
</blockquote></details>

hmm...I'll think about how to address these non-drop-cascade case...
___
*[pkg/sql/schemachanger/testdata/comment_on, line 180 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-MzvQ1zCDs0C8MT4kd88:-N-Z1wId8iFM9KkNz2yl:b9vaz47) ([raw file](https://github.com/cockroachdb/cockroach/blob/d996e7ee653c95be312d2515a9c0fae9a28db8a8/pkg/sql/schemachanger/testdata/comment_on#L180)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I appreciate this test suite but I'm not sure it's particularly interesting. The one in `scplan` is enough I think.
</blockquote></details>

haha..true, removed.
___
*[pkg/sql/schemachanger/scbuild/builder_test.go, line 157 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-Mzup577-RaF95Ig7-E5:-N-Z4bo_90I-PlqFva71:b-n952td) ([raw file](https://github.com/cockroachdb/cockroach/blob/87eee63208b2052a1facccba6faa23fa0f9f527f/pkg/sql/schemachanger/scbuild/builder_test.go#L157)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I reviewed this whole switch block and really you should replace all of these cases with just `case "setup":` and `case "build":`. As far as I can tell all we ever want out of this is to `tdb.Exec` some parsed statements. See the data-driven tests in `scdecomp` for inspiration.
</blockquote></details>

yeah, lol, I rename it to `setup` for now, will fix those `create-table` like things as well in a separate pr. don't want to pollute this pr further :).
___
*[pkg/sql/schemachanger/scplan/plan_test.go, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-MzupbF74u7Og1yhbO1n:-N-Z96Vd6fUPR58HjUPA:b-y41wpm) ([raw file](https://github.com/cockroachdb/cockroach/blob/87eee63208b2052a1facccba6faa23fa0f9f527f/pkg/sql/schemachanger/scplan/plan_test.go#L106)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Similar comment as for the data-driven build tests.
</blockquote></details>

same as the other case.
___
*[pkg/sql/descmetadata/metadata_fetcher.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78025#-MzujFs73zoq9VGysKyJ:-N-UnBTR8pr30VKtouVF:bk2yirj) ([raw file](https://github.com/cockroachdb/cockroach/blob/3324c282def52a66eb87561daab3b40f541a7127/pkg/sql/descmetadata/metadata_fetcher.go#L28)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I don't care much either way but if would have been completely OK in my book to have the existing `metadataUpdater` implement the `DescriptorMetadataFetcher` interface. Such as it is, these two structs are going to have the same dependencies anyway.
</blockquote></details>

ah yeah, I thought about that and imagined a name for it like `metadataAccessor`. But I didn't put it in the `metadataUpdater` because I didn't want to have a thing which give people illusion that it would also update the cache when doing upsert/delete which is not a thing we need, so I think it's better to separate them to avoid confusion. Now that I made it more like a "cache" cache...so probably make more sense to have it as separated.

**Comment by chengxiong-ruan** [comment]
@postamar I've update the how the comment cache behavior... and explicitly batch load comments for backref schema tables in the `builderState.BackReferences()`, this should address the `drop database/schema cascade` pain. But it still read comments for individual tables if you just drop multiple table in one transaction. Maybe that's fine?

**Comment by chengxiong-ruan** [comment]
closing this pr in favor of #80459

**Pull request closed without merging**
