### PR TITLE
sql: rewrite logic for constant lookup join columns

### LINKED ISSUE #47396: opt: map NOT bool_col to bool_col=FALSE so that lookup join can be used
Add a rule to map `NOT bool_col` to `bool_col=FALSE`. Something like:
```
(Not $input:*)
=>
(Eq $input (False))
```
Adding this rule would enable lookup joins in cases like this (including a case in the `trading` test):
```
root@:26257/defaultdb> CREATE TABLE vals (optional BOOL, val INT, PRIMARY KEY (optional, val));
root@:26257/defaultdb> EXPLAIN (opt) SELECT * FROM (VALUES (100,false), (200,true)) v(x,y) INNER JOIN vals ON val=x AND NOT optional;
                      text
-------------------------------------------------
  inner-join (hash)
   ├── scan vals
   │    └── constraint: /3/4: [/false - /false]
   ├── values
   │    ├── (100, false)
   │    └── (200, true)
   └── filters
        └── val = column1
```
EXPECTED: This should use a lookup join rather than a hash join. It uses a lookup join when manually updating `NOT optional` to be `optional=False`.

### PR DESCRIPTION
**Pull request by RaduBerinde**
When generating lookup joins, we try to extract equality constraints for index
columns in order to constrain more columns. This code only works for EqExpr
constraints.

This change rewrites this logic to look at the constraints in the scalar props
for FilerItem instead. This takes advantage of the existing logic in the
constraints builder. Instead of building a map, we look through filters for each
column (we optimize for the realistic case of finding at most one or two
useful constraints).

Fixes #47396.

Release note: None

### CODE REVIEW

**Review by andy-kimball — APPROVED** [review]
:lgtm: + a few non-blocking suggestions. Thanks for doing this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47412#-:-M4o0I8wCO_JNrqYDix9:b-uinyti)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 1371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47412#-M4nyQKcEtNmxoHD6w9S:-M4nyQKcEtNmxoHD6w9T:b-ecz0o4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4763eb1c78ec1b6188eac7df76131b00b308654c/pkg/sql/opt/xform/custom_funcs.go#L1371)):*
> ```Go
> 			}
> 
> 			// Try to find a filter that constraints this column to a non-NULL constant value.
> ```

constraints -> constrains
___
*[pkg/sql/opt/xform/custom_funcs.go, line 1506 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47412#-M4nz8lW0OVBCIFgQsmM:-M4nz8lW0OVBCIFgQsmN:b92u5zj) ([raw file](https://github.com/cockroachdb/cockroach/blob/4763eb1c78ec1b6188eac7df76131b00b308654c/pkg/sql/opt/xform/custom_funcs.go#L1506)):*
> ```Go
> 	for filterIdx := range filters {
> 		props := filters[filterIdx].ScalarProps()
> 		if props.TightConstraints && props.Constraints.Length() == 1 {
> ```

Should there be a helper method on `constraint.Set`/`constraint.Constraint` that does this? Maybe `IsSimpleEqConstraint` or similar? It'd be preferable to have such a method so that it could be unit-tested. There are some tricky cases that are difficult to test with our usual `opt` tests.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47412#-:-M4qQTZiCOChrflCB8Gs:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 1373 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47412#-M4qNsHl4yKyePIvfzxu:-M4qNsHm5anb6xcOPRTx:byqq4v) ([raw file](https://github.com/cockroachdb/cockroach/blob/4763eb1c78ec1b6188eac7df76131b00b308654c/pkg/sql/opt/xform/custom_funcs.go#L1373)):*
> ```Go
> 			// Try to find a filter that constraints this column to a non-NULL constant value.
> 			foundVal, onIdx, ok := c.findConstantFilter(on, idxCol)
> 			if !ok || foundVal == tree.DNull {
> ```

why does it matter if the value is null?

**Review by RaduBerinde — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47412#-:-M4qiqzH9aoiBqL7O0Xz:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andy-kimball and @rytaft)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 1371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47412#-M4nyQKcEtNmxoHD6w9S:-M4qZ6_rAVSatGPVPtDW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4763eb1c78ec1b6188eac7df76131b00b308654c/pkg/sql/opt/xform/custom_funcs.go#L1371)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

constraints -> constrains
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 1373 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47412#-M4qNsHl4yKyePIvfzxu:-M4qZO4Z5C6x9X7SNqgM:bd7gcns) ([raw file](https://github.com/cockroachdb/cockroach/blob/4763eb1c78ec1b6188eac7df76131b00b308654c/pkg/sql/opt/xform/custom_funcs.go#L1373)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

why does it matter if the value is null?
</blockquote></details>

We'd effectively convert `a IS NULL` to `a = NULL`.. Added to the comment.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 1506 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47412#-M4nz8lW0OVBCIFgQsmM:-M4qdy8F0k2dFlyBV-cO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4763eb1c78ec1b6188eac7df76131b00b308654c/pkg/sql/opt/xform/custom_funcs.go#L1506)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Should there be a helper method on `constraint.Set`/`constraint.Constraint` that does this? Maybe `IsSimpleEqConstraint` or similar? It'd be preferable to have such a method so that it could be unit-tested. There are some tricky cases that are difficult to test with our usual `opt` tests.
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47412#-:-M4sjCPd0_4QurZNXL_y:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball)

**Review by RaduBerinde — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47412#-:-M4t_Esw9aw2K_sTCaHw:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball)

**Pull request merged**
