### PR TITLE
roachtests: print DistSQL diagram in tpch_concurrency

### PR DESCRIPTION
**Pull request by yuzefovich**
This will help with reproducing failures.

Informs: #79870.

Release note: None

### CODE REVIEW

**Review by rharding6373 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79980)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Review by yuzefovich — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79980#-:-N-xy3drDawrL4k22zwr:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2)

**Comment by yuzefovich** [comment]
blathers backport 22.1

**Pull request merged**
