### PR TITLE
sql: full scan statements filter fix

### PR DESCRIPTION
**Pull request by barryhe2000**
ui: backend fix for full table scan filter checkbox

Backend fix for full table scan filter checkbox.

Release justification: bug fix/low risk high impact work.

Release note (ui change): full table scan checkbox

### CODE REVIEW

**Comment by barryhe2000** [comment]
Really quick fix that I need merged into master in order to pass some flaking tests on cluster-ui, just a few import statement fixes.

**Comment by asubiotto** [comment]
This PR can be closed, right? We deduced that the problem was that you local `cluster-ui` version was pulling in `cockroachdb/cockroach`.

**Review by barryhe2000 — COMMENTED** [review]
I think it's best if this PR still goes in because I reverted those changes but made some tiny fixes to match the DB console side with cluster-ui for full_scan, these changes are just for consistency

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61270#-:-MUsvQPj15mfl-x8-FCN:b8d9cfx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

**Comment by asubiotto** [comment]
But aren't those changes are for a later version of `cluster-ui` that hasn't been merged yet? Once your `cluster-ui` PR goes in, we'll have to bump the version in `pkg/ui/package.json` and make these changes, but not before.

**Review by barryhe2000 — COMMENTED** [review]
Yeah, sounds good, we can let these changes sit for now or close this PR until cluster-ui goes in, but I think these changes will still end up being necessary afterwards.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61270#-:-MUt24wzAeTnZFdnNitW:b-9rxup)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

**Comment by asubiotto** [comment]
Yep, let's keep it open but put the "do-not-merge" label on it until then

**Review by barryhe2000 — COMMENTED** [review]
cluster-ui is merged!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61270#-:-MUuZ5x16G5Q4HYPlYhw:b-x94v71)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

**Review by asubiotto — COMMENTED** [review]
Do we need to also bump the `cluster-ui` version in `pkg/ui/package.json`?

> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61270#-:-MUxfDM4-zB5cZEsDAVi:bh72yr4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by barryhe2000** [comment]
Yes I think so in order to see the filter changes.

**Comment by asubiotto** [comment]
@barryhe2000 friendly ping to do the version bump. I think @awoods187 would like to have this for his demo.

**Review by barryhe2000 — COMMENTED** [review]
RFAL! Bumped the cluster-ui version.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61270#-:-MVHa0vw3Tx7WAdnbvEb:b-owpjbc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

**Review by asubiotto — COMMENTED** [review]
:lgtm: cc @dhartunian We should probably also backport this to the 21.1 branch. You can use the backport tool here: https://github.com/benesch/backport

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61270#-:-MVHcQoIDl64TqNfwpKU:b-w09wdq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Review by dhartunian — COMMENTED** [review]
@barryhe2000 you will need to add a bump to the `yarn-vendored` submodule. There is a README in there with instructions on how to manage version bumps for JS dependencies. In the CRDB repo all dependencies are local to the repo to facilitate building without any internet dependencies.

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61270#-:-MVI3ph9Bhwy4tCXwXVd:bpwvkst)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

**Comment by dhartunian** [comment]
re: my earlier comment, this what it looks like in the build log

Screen Shot 2021-03-08 at 1 24 37 PM

**Comment by barryhe2000** [comment]
TFTR!

bors r+

**Pull request merged**
