### PR TITLE
opt: execution for selectOp

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: consolidate column index and indexedVar fields

Use only the index field. Currently, we only use IndexedVars when we
are provided with an expression for index constraints, so we never mix
"real" variables with indexed vars.

Release note: None

#### opt: move TypedExpr conversion code

Move the `scalarToTypedExpr` code to a separate file.

Release note: None

#### opt: allow mapping of variables to IndexedVars

This change adds a map for converting a `columnIndex` to an
`IndexedVar` index during `scalarToTypedExpr`.

This will be used during creation of execution plans.

Release note: None

#### sql: consolidate "types only" IndexedVarContainers

We have multiple sites where we implement an `IndexedVarHelper` with a
set of types. This change consolidates these into a helper in `tree`.

Release note: None

#### opt: execution for selectOp

We implement execution of selectOp via a ConstructFilter factory
primitive.

The relational operators are agnostic to the order in which a
corresponding execution node organizes the output columns, so it is
necessary to store extra "schema" information with execution plans.

Note that the exec builder could have a case for `filterOp -> scanOp`
"pattern" and put the filter in the scanNode; this may be done in a
future change.

CC @andy-kimball

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 4 of 4 files at r3, 7 of 7 files at r4.
Review status: 12 of 16 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/exec.go, line 69 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21457#-L2ve7wTYfcbdKOYJfb_:-L2ve7wTYfcbdKOYJfba:b-59jzwi) ([raw file](https://github.com/cockroachdb/cockroach/blob/a912029eda7507ff8f1201eaa08352132dbb59a4/pkg/sql/opt/exec.go#L69)):*
> ```Go
> 		if props.outputCols.Contains(props.columns[i].index) {
> 			s.outputCols[props.columns[i].index] = i
> 			s.outputTypes = append(s.outputTypes, props.columns[i].typ)
> ```

If/when we remove `relationalProps.columns` we'll need another way to lookup the type for a column. 

---

*[pkg/sql/opt/exec.go, line 97 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21457#-L2vdwrfU0KVkwKk5kMk:-L2vdwrfU0KVkwKk5kMl:b-t6j374) ([raw file](https://github.com/cockroachdb/cockroach/blob/a912029eda7507ff8f1201eaa08352132dbb59a4/pkg/sql/opt/exec.go#L97)):*
> ```Go
> 			break
> 		}
> 		plan.schema = underlying.schema
> ```

What is necessitating this? I would have thought that the schema for the `selectOp` is created from `e.relProps`. 

---

*[pkg/sql/opt/typed_expr.go, line 93 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21457#-L2vezWDOUractNHROxc:-L2vezWDOUractNHROxd:bej7vrh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a912029eda7507ff8f1201eaa08352132dbb59a4/pkg/sql/opt/typed_expr.go#L93)):*
> ```Go
> 	// varToIndexedVar is a map used when converting an variableOp into an
> 	// IndexedVar. It is optional: if it is nil, a 1-to-1 mapping is assumed.
> 	varToIndexedVar map[columnIndex]int
> ```

Could this be `[]int`? Or do we expect queries to contain enough column indexes to make a `map` more desirable. (For example, a query with a large number of column indexes but various relational operators only need to know about a handful of them).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21457#-:-L2vfYvXBszCga6k-g78:bnfp4nl)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 2 files at r2, 3 of 4 files at r3, 6 of 7 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/build.go, line 434 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21457#-L2w4CLXvT00zZa-tur9:-L2w4CLXvT00zZa-turA:bwy5zna) ([raw file](https://github.com/cockroachdb/cockroach/blob/a912029eda7507ff8f1201eaa08352132dbb59a4/pkg/sql/opt/build.go#L434)):*
> ```Go
> 		colProps := &columnProps{
> 			typ:   t.ResolvedType(),
> 			index: columnIndex(t.Idx),
> ```

I thought indexed variables were not necessarily unique across the query tree (e.g., in the case of a self-join).  But `index` should be unique - will this be a problem here?

I saw below that you created a `varToIndexedVar` map, but where is that getting used?

---

*[pkg/sql/opt/typed_expr.go, line 91 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21457#-L2wDSvl9WLM8Nq5qJF5:-L2wDSvl9WLM8Nq5qJF6:bfbronp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a912029eda7507ff8f1201eaa08352132dbb59a4/pkg/sql/opt/typed_expr.go#L91)):*
> ```Go
> 	ivh *tree.IndexedVarHelper
> 
> 	// varToIndexedVar is a map used when converting an variableOp into an
> ```

[nit] an variableOp -> a variableOp

---

*[pkg/sql/sem/tree/indexed_vars.go, line 303 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21457#-L2wPF-TtafQxNm5kWhx:-L2wPF-TtafQxNm5kWhy:brzm6ec) ([raw file](https://github.com/cockroachdb/cockroach/blob/a912029eda7507ff8f1201eaa08352132dbb59a4/pkg/sql/sem/tree/indexed_vars.go#L303)):*
> ```Go
> var _ IndexedVarContainer = &typeContainer{}
> 
> func (tc *typeContainer) IndexedVarEval(idx int, ctx *EvalContext) (Datum, error) {
> ```

Maybe add comments for this function and the ones below that they are part of the `IndexedVarContainer` interface?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21457#-:-L2wS3cc8_zyPmm1EfcA:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/exec.go, line 97 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21457#-L2vdwrfU0KVkwKk5kMk:-L2wPThTV1U52GfeqB6n:b-w7bo8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/a912029eda7507ff8f1201eaa08352132dbb59a4/pkg/sql/opt/exec.go#L97)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It's unclear to me what guarantees we have about the order of `relProps.columns` in general (I used the fact that they are in `TableDescriptor.Columns` order for scanOp).

At a high level the problem is that we can't determine a single planNode "schema" from a relational expression. By "schema" I mean the order in which the columns in `outputCols` show up. Here is an example: `SELECT a, b FROM t WHERE a = b`.  If `t` is defined as `(k INT PRIMARY KEY, a INT, b INT)`, the scan will return `(k, a, b)`; but if `t` is defined as `(k INT PRIMARY KEY, b INT, a INT)`, the scan will return `(k, b, a)`. The only difference in the Expr in the two cases is the order of `relProps.columns`.

I let the scanOp choose the "natural" order and keep track of it. An alternative to what I did would be to force the planNode for each operator to have a "canonical" schema: e.g. the columns ordered by their index. This would require adding projections all over the place though (unless, again, we have some kind of guarantees on how column indexes are set).
</blockquote></details>

Ok, I think some of that explanation could end up in a comment (even a TODO comment if we're not sure about this approach). I'd also include the "canonical" schema alternative. I've been staring at this for a bit and don't have any good thoughts to add, just circles that my mind is going in. 

---

*[pkg/sql/opt/typed_expr.go, line 93 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21457#-L2vezWDOUractNHROxc:-L2wP9aPN4vqM3aGjMny:b-4pehq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a912029eda7507ff8f1201eaa08352132dbb59a4/pkg/sql/opt/typed_expr.go#L93)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It could. It would be harder to size the allocation (we'd have to find the max index we are mapping).
</blockquote></details>

Let's leave it as-is for now. Maps are convenient, but a slice could be a lot faster. Just something to keep an eye on.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21457)*

**Comment by RaduBerinde** [comment]
TFTRs

---

Review status: 2 of 16 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/sql/opt/build.go, line 434 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21457#-L2w4CLXvT00zZa-tur9:-L2wbXJuhc6H7vQxgLHg:b-vmvdcf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a912029eda7507ff8f1201eaa08352132dbb59a4/pkg/sql/opt/build.go#L434)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I thought indexed variables were not necessarily unique across the query tree (e.g., in the case of a self-join).  But `index` should be unique - will this be a problem here?

I saw below that you created a `varToIndexedVar` map, but where is that getting used?
</blockquote></details>

When we use IndexedVars, we only use them with a scalar expression (without subqueries). I think it's fine. I agree all this stuff is confusing, but it's temporary, eventually we will remove IndexedVars altogether.

We use the map in `makeFilter`.

---

*[pkg/sql/opt/exec.go, line 97 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21457#-L2vdwrfU0KVkwKk5kMk:-L2wdyagyw_7saXgNkLe:bhdd7fx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a912029eda7507ff8f1201eaa08352132dbb59a4/pkg/sql/opt/exec.go#L97)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ok, I think some of that explanation could end up in a comment (even a TODO comment if we're not sure about this approach). I'd also include the "canonical" schema alternative. I've been staring at this for a bit and don't have any good thoughts to add, just circles that my mind is going in. 
</blockquote></details>

Added comment for `execNodeSchema`. I don't have a strong grasp on the issue.. I find it hard to think about and even harder to try to explain. Hopefully things will become more clear in time. I think that executing a plan with any backend requires choosing exactly how the columns are ordered between the various processes (whether planNodes, processors, or whatever).

---

*[pkg/sql/opt/typed_expr.go, line 91 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21457#-L2wDSvl9WLM8Nq5qJF5:-L2wel5MVbt6YYBrr9JS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a912029eda7507ff8f1201eaa08352132dbb59a4/pkg/sql/opt/typed_expr.go#L91)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] an variableOp -> a variableOp
</blockquote></details>

Done.

---

*[pkg/sql/opt/typed_expr.go, line 93 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21457#-L2vezWDOUractNHROxc:-L2waS_8RnqsUVE6aKQH:b-2mkw37) ([raw file](https://github.com/cockroachdb/cockroach/blob/a912029eda7507ff8f1201eaa08352132dbb59a4/pkg/sql/opt/typed_expr.go#L93)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Let's leave it as-is for now. Maps are convenient, but a slice could be a lot faster. Just something to keep an eye on.
</blockquote></details>

We should implement a type that chooses automatically, like we have FastIntSet. We could use a few words to pack in small values and avoid allocation altogether for small cases. We have many places where it would be useful. We use a slice with a special value for non-existing elements in a few places, but it's tedious to reimplement and document.

---

*[pkg/sql/sem/tree/indexed_vars.go, line 303 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21457#-L2wPF-TtafQxNm5kWhx:-L2wf4ZMvRp7TCc2qdJC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a912029eda7507ff8f1201eaa08352132dbb59a4/pkg/sql/sem/tree/indexed_vars.go#L303)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Maybe add comments for this function and the ones below that they are part of the `IndexedVarContainer` interface?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21457#-:-L2wgfmEXBNzQHcZDgLa:b-814g6a)*

**Comment by petermattis** [comment]
Review status: 2 of 16 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/sql/opt/typed_expr.go, line 93 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21457#-L2vezWDOUractNHROxc:-L2wjDt6JObqWyS038uu:b-cd5h5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/a912029eda7507ff8f1201eaa08352132dbb59a4/pkg/sql/opt/typed_expr.go#L93)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We should implement a type that chooses automatically, like we have FastIntSet. We could use a few words to pack in small values and avoid allocation altogether for small cases. We have many places where it would be useful. We use a slice with a special value for non-existing elements in a few places, but it's tedious to reimplement and document.
</blockquote></details>

:thumbsup: though this doesn't need to happen any time soon.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21457)*

**Comment by rytaft** [comment]
Reviewed 1 of 2 files at r7, 1 of 4 files at r8, 1 of 7 files at r9.
Review status: 5 of 16 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21457)*

**Pull request merged**
