### PR TITLE
sql: add estimated row count and cost in EXPLAIN

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change adds estimated row count information to EXPLAIN.

In verbose mode we show it for all operators (except for `values`
where it is redundant). We annotate the row count with `(missing
stats)` if not all tables involved had statistics.

In non-verbose mode we only show the row count for scan operators
(unless we had no statistics on the table, in which case we show a
`missing stats` note). There are three aspects to the reasoning here:
 - the row count is most important for scans in the majority of cases;
 - the row count estimate is fairly accurate for scans (whereas it is
   less and less accurate up a complex tree).
 - I'd rather be conservative with what we add, it's preferable to add
   more later than take things out.

Release note (sql change): EXPLAIN now shows estimated row count for
scans (when statistics are available). EXPLAIN (VERBOSE) now shows the
estimated row count for all operators.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Happy to take suggestions on when/where to show what, etc. CC @awoods187

**Review by yuzefovich — APPROVED** [review]
This is very cool! :lgtm:

Current logic on what to show and when sounds good to me.

super nit: in the release note, instead of "flags" I'd probably explicitly mention that `VERBOSE` option will show the data for every operator.

> Reviewed 46 of 46 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52798#-:-MEek6ygBjiWjEeRJKAq:b-d4bpn5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @jordanlewis, and @RaduBerinde)

___
*[pkg/sql/opt/exec/factory.go, line 288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52798#-MEeieHQBB2c6SichH5z:-MEeieHQBB2c6SichH6-:b-rdhcr1) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa1155a83f58164997e55d1d5fc808df683defc9/pkg/sql/opt/exec/factory.go#L288)):*
> ```Go
> // EstimatedStats  contains estimated statistics about a given operator.
> type EstimatedStats struct {
> 	// TablestatsAvailable is true if all the tables involved by this operator
> ```

nit: `s/Tablestats/TableStats/g`.

**Review by RaduBerinde — COMMENTED** [review]
Done, TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52798#-:-MEexHoB1zXhgKM55YiG:bexegmu)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @jordanlewis, and @yuzefovich)

**Review by jordanlewis — COMMENTED** [review]
This is great. To your point about preferring to be conservative, why add the cost now? We know that cost is a unitless, confusing quantity. Does it add any useful information to the plans? Could we avoid it, and replace with estimated input cardinality or something that is more likely to make sense to users?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52798#-:-MEf4HBv4NAF8GAtNPVC:bc2yyxs)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @jordanlewis, and @yuzefovich)

**Comment by RaduBerinde** [comment]
I think I am with you on that. I know that some of the SEs said they would want to see the costs (though maybe of the entire plan, not necessarily per-operator). It's why I added it but only in the VERBOSE variant. I am happy to remove for now though.

**Comment by jordanlewis** [comment]
I actually didn't realize you only added in VERBOSE. I think that makes sense to me.

**Comment by RaduBerinde** [comment]
Yeah, in non-verbose we only add the row count, and only for scans, and only when table stats are available.

**Comment by awoods187** [comment]
I'm very excited about this feature. I do think we should show that stats are missing in the regular explain tho because that could clue someone into a problem:
```SQL
root@127.0.0.1:60390/movr> explain select * from rides;
  tree |    field     |  description
-------+--------------+----------------
       | distribution | full
       | vectorized   | false
  scan |              |
       | table        | rides@primary
       | spans        | FULL SCAN
(5 rows)

Time: 1.432ms

root@127.0.0.1:60390/movr> explain (verbose) select * from rides;
  tree |        field        |     description      |                                                  columns                                                  | ordering
-------+---------------------+----------------------+-----------------------------------------------------------------------------------------------------------+-----------
       | distribution        | full                 |                                                                                                           |
       | vectorized          | false                |                                                                                                           |
  scan |                     |                      | (id, city, vehicle_city, rider_id, vehicle_id, start_address, end_address, start_time, end_time, revenue) |
       | estimated row count | 1000 (missing stats) |                                                                                                           |
       | estimated cost      | 1400.02              |                                                                                                           |
       | table               | rides@primary        |                                                                                                           |
       | spans               | FULL SCAN            |                                                                                                           |
(7 rows)

Time: 792µs
```

**Comment by awoods187** [comment]
I'm comfortable with hiding the opaque cost because ideally, we can give more developer-focused information that can be more easily reasoned about.

**Comment by awoods187** [comment]
It also looks nice in complicated statements:
```SQL
root@127.0.0.1:60390/art> explain SELECT
        DISTINCT c.custname
FROM
        customers AS c
        JOIN orders AS o ON
                        o.custid = c.custid
        JOIN orderdetail AS od ON
                        od.ordid = o.ordid
        JOIN articles AS a ON
                        a.artid = od.artid
WHERE
        c.city = 'GOTHAM'
        AND a.artname = 'BATMOBILE';
               tree              |        field        |      description
---------------------------------+---------------------+------------------------
                                 | distribution        | full
                                 | vectorized          | false
  distinct                       |                     |
   │                             | distinct on         | custname
   └── project                   |                     |
        └── hash join            |                     |
             │                   | type                | inner
             │                   | equality            | (artid) = (artid)
             │                   | right cols are key  |
             ├── hash join       |                     |
             │    │              | type                | inner
             │    │              | equality            | (custid) = (custid)
             │    │              | left cols are key   |
             │    ├── filter     |                     |
             │    │    │         | filter              | city = 'GOTHAM'
             │    │    └── scan  |                     |
             │    │              | estimated row count | 1
             │    │              | table               | customers@primary
             │    │              | spans               | FULL SCAN
             │    └── merge join |                     |
             │         │         | type                | inner
             │         │         | equality            | (ordid) = (ordid)
             │         │         | left cols are key   |
             │         │         | mergeJoinOrder      | +"(ordid=ordid)"
             │         ├── scan  |                     |
             │         │         | estimated row count | 1
             │         │         | table               | orders@primary
             │         │         | spans               | FULL SCAN
             │         └── scan  |                     |
             │                   | estimated row count | 1
             │                   | table               | orderdetail@primary
             │                   | spans               | FULL SCAN
             └── filter          |                     |
                  │              | filter              | artname = 'BATMOBILE'
                  └── scan       |                     |
                                 | estimated row count | 1
                                 | table               | articles@primary
                                 | spans               | FULL SCAN
(38 rows)

Time: 2.097ms
```

**Comment by RaduBerinde** [comment]
Thanks for testing it out!!

I will remove the cost for now.

> I do think we should show that stats are missing in the regular explain tho because that could clue someone into a problem

Intereseting. I would just add a "missing stats" entry, correct? And I'd hide it for virtual table scans, where we expect it.

**Comment by awoods187** [comment]
@RaduBerinde yeah exactly re missing stats! If you want to leave cost in verbose that's fine too I just meant I agreed with Jordan that we didn't need to feature it prominently.

**Comment by RaduBerinde** [comment]
Updated. Thanks!

**Pull request merged**
