### PR TITLE
turn on pretty printer in a few places

### PR DESCRIPTION
**Pull request by madelynnblue**

### CODE REVIEW

**Comment by knz** [comment]
Thanks for proposing this.

But Matt, as we discussed before I'd like us to iterate on the actual formatting before we start exposing the feature in CockroachDB. The moment the feature pops up in folks' screens they will get used to it immediately, and the specific syntax choices you've made so far will settle in stone. Here what you'll have to deal with:

https://en.wikipedia.org/wiki/Anchoring

https://en.wikipedia.org/wiki/Mere-exposure_effect

https://en.wikipedia.org/wiki/Choice-supportive_bias

https://en.wikipedia.org/wiki/Halo_effect

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27120#-:-LGUNJ3oA-z4U_o0Jl0k:b74njky)*

**Comment by knz** [comment]
Also, make a separate PR for the first commit, that is good and can be merged already.

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27120#-:-LGUPfP35t1KbLTMJPEY:b-iskgqv)*

**Comment by mjibson** [comment]
While I agree with your points about exposure and anchoring, I do not agree with your conclusion. I think that it is more important to turn this on so that users and us will start to see and use this and give feedback. I think there are some competing principles that it's ok to ship something that is good even if it is not perfect. We already ship features in incomplete state or change syntax. `gofmt` had a lot of changes early on as they figured out what it should look like. Some of the problems here are that for lots of syntaxes there are a good number of great choices, and I think we will be bikeshedding where to put whitespace for months and months. Waiting for all of those discussions to conclude will cripple this software into non-use.

I want to do a release early, release often style here and iterate the style over time. Prettier (or which this is based) has a [changelog](https://github.com/prettier/prettier/blob/master/CHANGELOG.md) that continues to iterate on style changes over time and its users are very happy with it.

**Review by knz — CHANGES_REQUESTED** [review]
Ok you changed my mind.

However I do request that you file 3 separate PRs for this. 

The first is a cleanup and LGTM.

The second one is a new feature and the release note must be extended to explain a bit more clearly what the command does and how to use it.

The third, the change to SHOW SYNTAX, needs a test. The commit message should also spell out what is the motivation for adding this feature there.

> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27120#-:-LG_AgEu-Rb8QBrlnE40:b1eh52i)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/pretty.go, line 69 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27120#-LG_ANJr8mSZbZWd992X:-LG_ANJs0LQ5vv27wzns:b9i4sv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1792046185032e0e424b22d06dcbff0ae5b80e9a/pkg/cli/pretty.go#L69)):*
> ```Go
> 
> func init() {
> 	sqlfmtCmd.Flags().IntVarP(&sqlfmtLen, "line-length", "n", tree.DefaultPrettyWidth, "target line length")
> ```

If we're introducing a new top-level commands, then its flags should be initialized with the others in `flags.go`.
___
*[pkg/cli/pretty_test.go, line 26 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27120#-LG_AUAi2vpe8ahDhKXl:-LG_AUAi2vpe8ahDhKXm:b8yck6e) ([raw file](https://github.com/cockroachdb/cockroach/blob/1792046185032e0e424b22d06dcbff0ae5b80e9a/pkg/cli/pretty_test.go#L26)):*
> ```Go
> )
> 
> func TestSQLFmt(t *testing.T) {
> ```

This functionality would be much more clearly tested with an `Example_xxx` test (see code in `cli_test.go` for examples).

**Review by knz — COMMENTED** [review]
Also the 2nd PR about the command must have label `docs-todo` so someone from docs picks it up later.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27120#-:-LG_B7dHBD3-hI0kcn4z:b-dtsr6m)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by knz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27120)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/pretty.go, line 69 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27120#-LG_ANJr8mSZbZWd992X:-LG_EgkLD9mHaTHHEjPn:bjqg4p8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1792046185032e0e424b22d06dcbff0ae5b80e9a/pkg/cli/pretty.go#L69)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

If we're introducing a new top-level commands, then its flags should be initialized with the others in `flags.go`.
</blockquote></details>

Also make it accept `-e` for symmetry with `cockroach sql` and `cockroach demo`.
___
*[pkg/cli/pretty_test.go, line 26 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27120#-LG_AUAi2vpe8ahDhKXl:-LG_El1D51hMgDo4P-nu:b-v8huew) ([raw file](https://github.com/cockroachdb/cockroach/blob/1792046185032e0e424b22d06dcbff0ae5b80e9a/pkg/cli/pretty_test.go#L26)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This functionality would be much more clearly tested with an `Example_xxx` test (see code in `cli_test.go` for examples).
</blockquote></details>

These tests can use `-e` too.

**Review by knz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27120)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/pretty_test.go, line 26 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27120#-LG_AUAi2vpe8ahDhKXl:-LG_cftI3g8mi25D4_77:bmt1l3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/1792046185032e0e424b22d06dcbff0ae5b80e9a/pkg/cli/pretty_test.go#L26)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

These tests can use `-e` too.
</blockquote></details>

Also make sure the test exercises formatting of multiple statements.

**Review by knz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27120)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/pretty.go, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27120#-LGiZUnyEUnNzQYXHsYf:-LGiZUnyEUnNzQYXHsYg:bsrmqpq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1792046185032e0e424b22d06dcbff0ae5b80e9a/pkg/cli/pretty.go#L1)):*
> ```Go
> // Copyright 2018 The Cockroach Authors.
> ```

Maybe also name the file `sqlfmt.go` instead, to follow the pattern we have for the other commands.

**Comment by mjibson** [comment]
Opened some other PRs. Closing.

**Pull request closed without merging**
