### PR TITLE
build: fix missing TMPDIR in builder

### LINKED ISSUE #50507: build: at least teamcity-test.sh fails to collect artifacts
(I believe this issue exists ever since the scripts were converted/improved to use JSON. I had noticed this already months ago. Wasn't sure before today)

Symptom: my Go unit tests fails after they create temporary artifacts in their $TMPDIR, however the "Artifacts" tabs in TeamCity remains empty.

Example here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_Test/2029726?buildTab=overview

(In contrast, roachtest failures do get their artifacts populated)

Compare:

- run `make test ... TESTFLAGS=-v` locally, see that the test creates temporary files/directories in $TMPDIR

- same failing test in CI: no artifacts collected

I am surprised because I seem to read in the scripts that TMPDIR is set to a sub-directory of `artifacts` which is mounted in the docker image? 

(But then maybe that directory just exists but does not get copied to the place TeamCity looks for artifacts?)

### PR DESCRIPTION
**Pull request by tbg**
We don't understand why, but `autouseradd` swallows the TMPDIR env
variable (it becomes unset).

Hat tip to @knz for in-person help with this.

Fixes #50507.
Touches https://github.com/benesch/autouseradd/issues/2.

Release note: None

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
Ugh... is it just `TMPDIR` that's lost? Bizarre, and this must have been a pain to track down.

**Comment by tbg** [comment]
Yes it's something particular to TMPDIR (maybe some other special snowflakes are also lost, but "generally" env stuff gets passed through).

**Comment by benesch** [comment]
autouseradd is a setuid binary and so is subject to ld.so’s secure execution mode, as described here: https://man7.org/linux/man-pages/man8/ld.so.8.html#ENVIRONMENT. There are a few other env vars that get filtered out, but none that seem particularly relevant.

This looks easy to work around with a wrapper script. Planning to get a patch out this afternoon.

**Comment by tbg** [comment]
Thanks! I'm still going to merge this to take you out of the critical path. Thanks a bunch for jumping in here! @knz suspected this was a low level "feature" but we would've had to dig for a long time to figure things out.

bors r=jordanlewis

**Pull request merged**
