### PR TITLE
ui: remove unused end-to-end UI tests

### PR DESCRIPTION
**Pull request by sjbarag**
The end-to-end UI tests written in Cypress weren't updated since October
2021, and haven't been run in at least as long. They in fact no longer
seemed to execute, and there were six major-version releases of
Cypress since the one used in this project. There had been enough skew
in both the CockroachDB product and in the Cypress platform that
upgrading to a newer version in-place is more work than simply tearing
out the old tests and starting from scratch. Remove the existing
db-console Cypress tests in preparation for a from-scratch
reimplementation.

Release note: None

### CODE REVIEW

**Review by nathanstilwell — COMMENTED** [review]
> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85037)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sjbarag)

___
*[`pkg/ui/workspaces/db-console/yarn.lock` line 0 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85037#-N7vHYCYDv4qyvGeaxNX:-N7vHYCYDv4qyvGeaxNY:bnlh8zw) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d171b234ba27294344abb70ef648d9f3385726f/pkg/ui/workspaces/db-console/yarn.lock#L0)):*
Did you mean to delete this lock file?

**Review by sjbarag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85037)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nathanstilwell)

___
*[`pkg/ui/workspaces/db-console/yarn.lock` line  at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85037#-N7vHYCYDv4qyvGeaxNX:-N7vIUNt4Hp-Rywe7Lrw:bn3dl87) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d171b234ba27294344abb70ef648d9f3385726f/pkg/ui/workspaces/db-console/yarn.lock#L)):*
<details><summary><i>Previously, nathanstilwell (Nathan Stilwell) wrote…</i></summary><blockquote>

Did you mean to delete this lock file?
</blockquote></details>

oof owie no, good catch!

**Review by sjbarag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85037)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nathanstilwell)

___
*[`pkg/ui/workspaces/db-console/yarn.lock` line  at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85037#-N7vHYCYDv4qyvGeaxNX:-N7vIs9XCoJ7CBfSvS4h:b-ejr0y5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d171b234ba27294344abb70ef648d9f3385726f/pkg/ui/workspaces/db-console/yarn.lock#L)):*
<details><summary><i>Previously, sjbarag (Sean Barag) wrote…</i></summary><blockquote>

oof owie no, good catch!
</blockquote></details>

Oh wait, the whole file isn't removed — just the cypress dependencies that were previously in this file :)

**Comment by nathanstilwell** [comment]
*[`pkg/ui/workspaces/db-console/yarn.lock` line  at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85037#-N7vHYCYDv4qyvGeaxNX:-N7vJFR_49IMe4bh2372:b-ou3y7c) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d171b234ba27294344abb70ef648d9f3385726f/pkg/ui/workspaces/db-console/yarn.lock#L)):*
<details><summary><i>Previously, sjbarag (Sean Barag) wrote…</i></summary><blockquote>

Oh wait, the whole file isn't removed — just the cypress dependencies that were previously in this file :)
</blockquote></details>

Ah, Reviewable totally choked on the size of this file. I finally found the diff though. :+1:

**Review by nathanstilwell — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85037)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sjbarag)

**Comment by sjbarag** [comment]
bors r=nathanstilwell

**Pull request merged**
