### PR TITLE
opt: test catalog improvements, fixes, tests

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: test catalog improvements

This commit makes the following changes to the test catalog:

 - `exec-ddl` now supports `SHOW CREATE` which prints information
   about a table; the information is extended to include
   column default/computed values, inbound foreign keys, zones.

 - we add specific datadriven tests for the test catalog.

 - other `exec-ddl` statements no longer output any information;
   outside of debugging the test catalog itself (for which
   `SHOW CREATE` can be used), this is unnecessary clutter.

This change was motivated by some bugs in the catalog (which will be
fixed in subsequent commits).

Release note: None

#### opt: update tests

Update test files with the catalog changes.

Release note: None

#### opt: fix UNIQUE column handling in test catalog

The test catalog was ignoring a UNIQUE specifier for a column. It now
creates a unique index as expected.

Release note: None

#### opt: fix foreign key issue in test catalog

The test catalog was incorrectly failing when the referenced column is
unique but can be null (in this case the index has the PK as extra key
columns).

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
In the last commit message:

> The test catalog was incorrectly failing when ...

Can you give a bit more detail about how it was failing?

Otherwise, :lgtm:, nice improvements!

> Reviewed 8 of 8 files at r1, 128 of 128 files at r2, 4 of 4 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38141#-:-LhHeebcET1MTp5x34NV:b-7vjlcp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj and @RaduBerinde)

___
*[pkg/sql/opt/cat/utils.go, line 233 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38141#-LhHUPjs3stR1fKXuWoF:-LhHUPjt1D_HTDjrpKKF:b-v091r0) ([raw file](https://github.com/cockroachdb/cockroach/blob/adfa297a6a87130b85509b7fd5d1719c6866f61a/pkg/sql/opt/cat/utils.go#L233)):*
> ```Go
> // treeprinter for debugging and testing.
> func formatCatalogFKRef(
> 	cat Catalog, title string, fkRef ForeignKeyConstraint, tp treeprinter.Node,
> ```

[nit] Instead of title, it seems like it would be clearer to just have a boolean for outbound/inbound. Then you can control the exact message inside this function.

**Review by RaduBerinde — COMMENTED** [review]
TFTR! I updated the commit message (the failure was `no unique constraint matching given keys for referenced table`).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38141#-:-LhJluiv7po0W6hWJTJU:bvxh68d)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj and @rytaft)

___
*[pkg/sql/opt/cat/utils.go, line 233 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38141#-LhHUPjs3stR1fKXuWoF:-LhJm-qv5htoaj1wCqw9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/adfa297a6a87130b85509b7fd5d1719c6866f61a/pkg/sql/opt/cat/utils.go#L233)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] Instead of title, it seems like it would be clearer to just have a boolean for outbound/inbound. Then you can control the exact message inside this function.
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 1 of 133 files at r5, 127 of 128 files at r6, 3 of 4 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38141#-:-LhLOzRV66JZrTeCiUy1:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj)

**Pull request merged**
