### PR TITLE
opt: reorganize FK checks optbuilder code

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change moves the FK checks build code to a separate file and moves the
`addInsertionCheck` / `addDeletionCheck` code to the `fkCheckHelper`.

Release note: None

### CODE REVIEW

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45684#-:-M1YdUoG7YYYcWahcZoJ:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball)

**Comment by tbg** [comment]
bors r-

(have a skewy PR in the queue that needs to go through, sorry about the interrupt)

**Pull request merged**
