### PR TITLE
release-22.2: add version gate for NOSQLLOGIN privilege check

### LINKED ISSUE #97178: sql: unfinalized upgrades to 22.2.4 return internal errors on login
Unfinalized upgrades to 22.2.4 from 22.1 return internal errors on login.

Reproduction:

Start a one-node 22.1 cluster
Create a non-admin user.
Set this: SET CLUSTER SETTING cluster.preserve_downgrade_option = '22.1';
Upgrade the node to 22.2.4.
Attempt to log in with the non-admin user created in step 2.
You get this:
```
$ cockroach sql --user nobody
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
ERROR: internal error while retrieving user account memberships: relation "system.public.privileges" does not exist
SQLSTATE: 28000
Failed running "sql"
```

### PR DESCRIPTION
**Pull request by ZhouXing19**
This commit is to add a version gate for checking user's NOSQLLOGIN privilege. 

Note that we haven't add tests yet and will do it in a follow-up pr. This patch has passed the following tests locally:

```
#!/bin/bash

pkill -f cockroach
rm -rf cockroach-data
sleep 2
./cockroach-22-1-14 start-single-node --insecure --background
./cockroach-22-1-14 sql --insecure -e "CREATE USER nobody"
./cockroach-22-1-14 sql --insecure -e "SET CLUSTER SETTING cluster.preserve_downgrade_option = '22.1';"
pkill -f cockroach
pkill -f cockroach-22-1-14
sleep 10
./cockroach start-single-node --insecure --background
./cockroach-22-1-14 sql --insecure --user nobody -e "SELECT 1"
if [ $? -eq 0 ]
then
    exit 0
else
    exit 1
fi
```

fixes #97178

Release note (bug fix): When upgrading from a 22.1 to 22.2.4 cluster, logging in with a new user would error that system.privilege doesn't exist, as we're trying to check the user privilege while starting up.  Note that only 22.2.4 is affected.
This commit is to add a version gate for this check. 

Release justification: important bug fix

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
lgtm! but can you update the commit message?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97183#-:-NOLDZaa2MyThmYG3Rfn:b-co8271)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ZhouXing19)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97183#-NOLDE5_-j1XWHQ-cYrc):*
can you mention here that only v22.2.4 is affected?

**Comment by ZhouXing19** [comment]
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97183#-NOLDE5_-j1XWHQ-cYrc):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

can you mention here that only v22.2.4 is affected?
</blockquote></details>

Done.

**Comment by ZhouXing19** [comment]
TFTR!

bors r=rafiss

**Comment by rafiss** [comment]
since this is a release branch, we'll just be able to merge on github without bors

**Pull request merged**
