### PR TITLE
ui: Refactor usage of `latency parse`

### LINKED ISSUE #46445: ui: refactor usage of `latency-parse` class name in non-latency settings
The code below uses the `latency-parse` class in situations where non-latency data is being shown. This should get cleaned up to use a different CSS class.

https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/src/views/statements/barCharts.tsx#L148-L169

### PR DESCRIPTION
**Pull request by vladlos**
Fixed `Retries` bar chart
Refactored code,
changed `latency-parse` class names for more clear

Resolves: #46445

Release justification: bug fixes and low-risk updates to new functionality

Release note (ui): fix and clean up code of barcharts on statements page

### CODE REVIEW

**Review by dhartunian — CHANGES_REQUESTED** [review]
@elkmaster can you add screenshots illustrating the fixed styling of bar charts?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46574#-:-M3IouFm2jgJtqbhZUR6:b-dn34pt)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by elkmaster** [comment]
latency-parce

**Review by dhartunian — CHANGES_REQUESTED** [review]
@elkmaster my concern here is that the word `latency` is being used in classnames to signify *non-latency* bar graphs. This was what I wanted to avoid since that was what led to my initial confusion.

The color looks correct now but can you adjust the classnames for non-latency bars?


> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46574#-:-M3lM73G3mSVmnsyMhx1:b-ohz7rq)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by dhartunian — CHANGES_REQUESTED** [review]
@elkmaster can you edit the release note? It should be worded in a customer-facing way. "fix and cleanup" does not communicate what the customer sees. This should work:

"bug fixed causing retries to show in gray color on statements page. they will now show as a red bar again."

Are there other customer-facing changes as a result of this fix or is it only that one bar that is now red?

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46574#-:-M3qCzNLAlIMkXLsROo7:b-parm65)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @elkmaster)

___
*[pkg/ui/src/views/statements/barCharts.tsx, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46574#-M3qDasp08pcX_ojpung:-M3qDasp08pcX_ojpunh:b-qyex0a) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bb841219db0096631bc90dc1ba5ffd91c15c719/pkg/ui/src/views/statements/barCharts.tsx#L42)):*
> ```XML
> 
> const latencyBars = [
>   bar("bar-chart__parse", (d: StatementStatistics) => d.stats.parse_lat.mean),
> ```

These are latency bar graphs, they can retain the `latency` prefix.
___
*[pkg/ui/src/views/statements/barCharts.tsx, line 261 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46574#-M3qCTP3-jHIMRKQhr_q:-M3qCTP3-jHIMRKQhr_r:bc2il4y) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bb841219db0096631bc90dc1ba5ffd91c15c719/pkg/ui/src/views/statements/barCharts.tsx#L261)):*
> ```XML
>             <div className="bar-chart__multiplebars">
>               <div
>                 className="bar-chart__parse bar-chart__bar"
> ```

I think you went a bit too far here and removed the `latency` prefix from actual latency graphs. I don't think we should stop using out altogether I just want the names to match the meaning.

**Comment by elkmaster** [comment]
That class is not latency bar specific, no sense to keep that name anymore

**Review by dhartunian — APPROVED** [review]
Merging this for now to fix the bug for release and filing a separate issue to continue to clean up this CSS. #47098

I don't agree with adding additional classnames and layers to fix this issue. Ideally we should have minimal nesting. Currently this PR creates styles for nested `.bar-chart` inside a `.bar-chart`.

I agree that the class you changed is not latency bar specific but the naming retains inconsistencies because of the use of `__parse` as a prefix to the bar chart classes. "parse" is one of the latency bars that we show and does not describe all graphs.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46574#-:-M4GPBHTC4pUlIgVbOhG:bb5ol7m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @elkmaster)

**Pull request merged**
