### PR TITLE
distsqlrun: release flow registry lock before Pushing timeout error

### LINKED ISSUE #34041: distsqlrun: possible deadlock in flowRegistry
I have a debug zip showing what I believe to be a deadlock, or at least a temporary denial of service of sorts. The call below is pushing an error to a RowChannel (a possibly blocking call) while holding `fr.Lock`. So if the `Push()` blocks, nobody can get into the registry.
In the particular case I'm looking at, the push was blocked for 2m by the time the goroutine dump was taken, and indeed many other queries were trying to get into the registry and blocking.
Not sure what to do exactly, haven't re-read the `flowRegistry` code. If it's not possible to push without the lock, maybe we can make a non-blocking push for errors in particular.

Some more details: `is.receiver` is a `RowChannel` and there's also a `routerBase` trying to push to it, also blocked for 2m.

Link to the debug.zip we got from the customer (internal only): https://drive.google.com/open?id=1fbexxTV9S7cn2rPAFp1TvweQ7rfUnjU7

@RaduBerinde, @jordanlewis who wants this?

### PR DESCRIPTION
**Pull request by asubiotto**
As this Push might block indefinitely, resulting in blocking new Flow
registration.

Fixes #34041

Release note (bug fix): Fix a back up in flow creation observed by "no
inbound stream connection" caused by not releasing a lock before
attempting a possibly blocking operation.

cc @tim-o 

Will backport to 2.1

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34218)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @asubiotto, and @RaduBerinde)

___
*[pkg/sql/distsqlrun/flow_registry.go, line 230 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LWzx0LK8Z_ki4kKyrUR:-LWzx0LK8Z_ki4kKyrUS:bvegjwn) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d1aab2492e223dfb362ea7c637bb23582f91f24/pkg/sql/distsqlrun/flow_registry.go#L230)):*
> ```Go
> 					receiver.ProducerDone()
> 					fr.Lock()
> 					fr.finishInboundStreamLocked(id, streamID)
> ```

Does this need to be called after the `Push`? (I looked for a bit and I don't think so, but I'm not 100% sure). If not I was thinking we could put the timed out receivers in a slice and then Push on them after releasing the lock.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34218)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @RaduBerinde)

___
*[pkg/sql/distsqlrun/flow_registry.go, line 230 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LWzx0LK8Z_ki4kKyrUR:-LX1-_1SEEE05gyP-jN8:b-1f9s58) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d1aab2492e223dfb362ea7c637bb23582f91f24/pkg/sql/distsqlrun/flow_registry.go#L230)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Does this need to be called after the `Push`? (I looked for a bit and I don't think so, but I'm not 100% sure). If not I was thinking we could put the timed out receivers in a slice and then Push on them after releasing the lock.
</blockquote></details>

Good call, done. I think this might also have introduced some badness.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34218)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @asubiotto, and @RaduBerinde)

___
*[pkg/sql/distsqlrun/flow_registry.go, line 213 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LX1KH2FDgS_YuaN8R9L:-LX1KH2G7PmpmNX1hsIX:b-cxvhxe) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a444fb6097facddf7e7d362665144558f6b3e26/pkg/sql/distsqlrun/flow_registry.go#L213)):*
> ```Go
> 			var timedOutReceivers []RowReceiver
> 			fr.Lock()
> 			defer func() {
> ```

Why the defer? Can't we unlock and do this after the loop?
___
*[pkg/sql/distsqlrun/flow_registry.go, line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LX1KQU96cTPlD9RN1-0:-LX1KQU96cTPlD9RN1-1:bloh87i) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a444fb6097facddf7e7d362665144558f6b3e26/pkg/sql/distsqlrun/flow_registry.go#L226)):*
> ```Go
> 				if !is.connected && !is.canceled {
> 					is.canceled = true
> 					numTimedOut++
> ```

we don't need this variable anymore (it's equal to `len(timedOutReceivers)`)

**Review by asubiotto — COMMENTED** [review]
The race failure was due to a test accessing a `RowBuffer`'s `ProducerClosed`. My change makes it more likely to hit this because the test in question locks the flow registry to check for that the inbound stream has been canceled (which happens under the same lock as calling ProducerDone and setting ProducerClosed). Added another commit to protect `ProducerClosed` with a mutex so that testing code can still check for `ProducerDone` without potential races. Had to also add a SucceedsSoon to `TestStreamConnectionTimeout`. This change also uncovered a test assumption that was incorrect, namely that one could call `Next` and `Push` concurrently on a `RowBuffer`. `TestInboundStreamTimeoutIsRetryable` now uses a `RowChannel`, as it should have done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-:-LX1_Ffl8weML3M1wlKW:b-3cwgdp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @RaduBerinde)

___
*[pkg/sql/distsqlrun/flow_registry.go, line 213 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LX1KH2FDgS_YuaN8R9L:-LX1_DB8A1MtiGJO2Tz2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a444fb6097facddf7e7d362665144558f6b3e26/pkg/sql/distsqlrun/flow_registry.go#L213)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Why the defer? Can't we unlock and do this after the loop?
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/flow_registry.go, line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LX1KQU96cTPlD9RN1-0:-LX1_E6s3VL9UYuZcINS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a444fb6097facddf7e7d362665144558f6b3e26/pkg/sql/distsqlrun/flow_registry.go#L226)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

we don't need this variable anymore (it's equal to `len(timedOutReceivers)`)
</blockquote></details>

Done.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34218)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @asubiotto, and @RaduBerinde)

___
*[pkg/sql/distsqlrun/base.go, line 571 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LX5LbQIA9q1iTz95HPC:-LX5LbQIA9q1iTz95HPD:b-fczpqc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d403a9becd0cee0cbae3b24cec320205a96058ae/pkg/sql/distsqlrun/base.go#L571)):*
> ```Go
> // Push is part of the RowReceiver interface.
> func (rb *RowBuffer) Push(row sqlbase.EncDatumRow, meta *ProducerMetadata) ConsumerStatus {
> 	if rb.ProducerClosed() {
> ```

It's unfortunate that Push now takes and releases an extra lock. Can't we change it to be an atomic instead?
___
*[pkg/sql/distsqlrun/flow_registry.go, line 238 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LX5Lpxd0VK1ECGjDwN3:-LX5Lpxd0VK1ECGjDwN4:b-nfskwa) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b5a244dc8a46284ca7929c8ca725ffe5e060f5b/pkg/sql/distsqlrun/flow_registry.go#L238)):*
> ```Go
> 				)
> 			}
> 			fr.Unlock()
> ```

I think this can be done before the `if` block above, no?

**Review by andreimatei — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34218)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @asubiotto, and @RaduBerinde)

___
*[pkg/sql/distsqlrun/base.go, line 571 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LX5LbQIA9q1iTz95HPC:-LX6UNJU4kPvt8npWbe5:bqyod9a) ([raw file](https://github.com/cockroachdb/cockroach/blob/d403a9becd0cee0cbae3b24cec320205a96058ae/pkg/sql/distsqlrun/base.go#L571)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It's unfortunate that Push now takes and releases an extra lock. Can't we change it to be an atomic instead?
</blockquote></details>

or rather, can't we just take the lock once in this function - instead of taking it in `storeRow`?
___
*[pkg/sql/distsqlrun/flow_registry.go, line 219 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LX6V4BHBYzTNLAx5t9s:-LX6V4BHBYzTNLAx5t9t:bd9pyyx) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b5a244dc8a46284ca7929c8ca725ffe5e060f5b/pkg/sql/distsqlrun/flow_registry.go#L219)):*
> ```Go
> 					// its consumer once we return and unlock the flow registry lock; the
> 					// error will propagate and eventually drain all the processors. We
> 					// don't Push directly here to avoid scenarios in which the Push
> ```

nit: s/.../We'll actually Push() after fr.Unlock().
___
*[pkg/sql/distsqlrun/flow_registry_test.go, line 614 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LX6VVUj8gLhlAjd45Tl:-LX6VVUj8gLhlAjd45Tm:bebe92l) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b5a244dc8a46284ca7929c8ca725ffe5e060f5b/pkg/sql/distsqlrun/flow_registry_test.go#L614)):*
> ```Go
> }
> 
> // TestUnlockBeforePush verifies that in the case of a timeout error, the flow
> ```

nit: I don't like the name of this test much, partly because it doesn't say anything about the crucial "timeout". How about `TestTimeoutPushDoesntBlockRegister`?
And I wouldn't talk about any particular locks, etc. Just say that we need to be able to register flows while the timeout errors are being pushed.
___
*[pkg/sql/distsqlrun/flow_registry_test.go, line 618 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LX6WiPME8vcFt_a_Csh:-LX6WiPME8vcFt_a_Csi:bviyeq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b5a244dc8a46284ca7929c8ca725ffe5e060f5b/pkg/sql/distsqlrun/flow_registry_test.go#L618)):*
> ```Go
> // This could otherwise result in holding the lock indefinitely (#34041).
> func TestUnlockBeforePush(t *testing.T) {
> 	defer leaktest.AfterTest(t)()
> ```

the implementation of this test seems a bit weird to me.
What I would do is implement my own RowChannel thingy that lets me trap calls to Push, then I'd expect a push of the timeout error, then I'd register another flow and see that that registration succeeds.
___
*[pkg/sql/distsqlrun/flow_registry_test.go, line 631 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LX6WNJD16xH0hsqoBNt:-LX6WNJD16xH0hsqoBNu:b-g3qca4) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b5a244dc8a46284ca7929c8ca725ffe5e060f5b/pkg/sql/distsqlrun/flow_registry_test.go#L631)):*
> ```Go
> 		},
> 	}
> 	rc.Push(makeIntRows(1, 1)[0], nil /* meta */)
> ```

some comments here would be good - this calls fills the buffer, right?
___
*[pkg/sql/distsqlrun/flow_registry_test.go, line 660 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LX6X5l6EI9thhR9FxUl:-LX6X5l6EI9thhR9FxUm:b161rd6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b5a244dc8a46284ca7929c8ca725ffe5e060f5b/pkg/sql/distsqlrun/flow_registry_test.go#L660)):*
> ```Go
> 	for i := 0; i < 5; i++ {
> 		if err := fr.RegisterFlow(
> 			ctx, distsqlpb.FlowID{UUID: uuid.MakeV4()}, &Flow{}, nil /* inboundStreams */, 0, /* timeout */
> ```

pls call attention to the 0 at the end, since it's of the essence (right?).
___
*[pkg/sql/distsqlrun/flow_registry_test.go, line 679 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LX6WEVX5mDuEWIHq8zt:-LX6WEVX5mDuEWIHq8zu:b2b9rjc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b5a244dc8a46284ca7929c8ca725ffe5e060f5b/pkg/sql/distsqlrun/flow_registry_test.go#L679)):*
> ```Go
> 	}
> 
> 	if meta.Err == nil {
> ```

can't we expect a particular error here?

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34218)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @RaduBerinde)

___
*[pkg/sql/distsqlrun/base.go, line 571 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LX5LbQIA9q1iTz95HPC:-LXAGCB17jZpGbhjjdYE:b-o84hih) ([raw file](https://github.com/cockroachdb/cockroach/blob/d403a9becd0cee0cbae3b24cec320205a96058ae/pkg/sql/distsqlrun/base.go#L571)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

or rather, can't we just take the lock once in this function - instead of taking it in `storeRow`?
</blockquote></details>

Done. Chose to lock just once in this function.
___
*[pkg/sql/distsqlrun/flow_registry.go, line 219 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LX6V4BHBYzTNLAx5t9s:-LXAHoct3ty1-yC0juDu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b5a244dc8a46284ca7929c8ca725ffe5e060f5b/pkg/sql/distsqlrun/flow_registry.go#L219)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: s/.../We'll actually Push() after fr.Unlock().
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/flow_registry.go, line 238 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LX5Lpxd0VK1ECGjDwN3:-LXAHprOATFHOMBIDuEC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b5a244dc8a46284ca7929c8ca725ffe5e060f5b/pkg/sql/distsqlrun/flow_registry.go#L238)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I think this can be done before the `if` block above, no?
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/flow_registry_test.go, line 614 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LX6VVUj8gLhlAjd45Tl:-LXAJlSvCjsJG0__nYF4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b5a244dc8a46284ca7929c8ca725ffe5e060f5b/pkg/sql/distsqlrun/flow_registry_test.go#L614)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: I don't like the name of this test much, partly because it doesn't say anything about the crucial "timeout". How about `TestTimeoutPushDoesntBlockRegister`?
And I wouldn't talk about any particular locks, etc. Just say that we need to be able to register flows while the timeout errors are being pushed.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/flow_registry_test.go, line 618 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LX6WiPME8vcFt_a_Csh:-LXATVvb-QFYPKGRmcDq:b-bjudbj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b5a244dc8a46284ca7929c8ca725ffe5e060f5b/pkg/sql/distsqlrun/flow_registry_test.go#L618)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

the implementation of this test seems a bit weird to me.
What I would do is implement my own RowChannel thingy that lets me trap calls to Push, then I'd expect a push of the timeout error, then I'd register another flow and see that that registration succeeds.
</blockquote></details>

Thanks for the suggestion! Done.
___
*[pkg/sql/distsqlrun/flow_registry_test.go, line 631 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LX6WNJD16xH0hsqoBNt:-LXAcmqK6f_gcgnLBL77:bilpgxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b5a244dc8a46284ca7929c8ca725ffe5e060f5b/pkg/sql/distsqlrun/flow_registry_test.go#L631)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

some comments here would be good - this calls fills the buffer, right?
</blockquote></details>

Done. Indeed
___
*[pkg/sql/distsqlrun/flow_registry_test.go, line 660 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LX6X5l6EI9thhR9FxUl:-LXAco915jOs9Gm9L3JA:b9hge0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b5a244dc8a46284ca7929c8ca725ffe5e060f5b/pkg/sql/distsqlrun/flow_registry_test.go#L660)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls call attention to the 0 at the end, since it's of the essence (right?).
</blockquote></details>

Called it out in a comment. It's actually irrelevant since the flow has no inbound streams.
___
*[pkg/sql/distsqlrun/flow_registry_test.go, line 679 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LX6WEVX5mDuEWIHq8zt:-LXAcsu03nQUL_G76Tqg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b5a244dc8a46284ca7929c8ca725ffe5e060f5b/pkg/sql/distsqlrun/flow_registry_test.go#L679)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

can't we expect a particular error here?
</blockquote></details>

Done.

**Comment by asubiotto** [comment]
TeamCity's failing build is not due to this PR: https://github.com/cockroachdb/cockroach/issues/34213

**Review by andreimatei — CHANGES_REQUESTED** [review]
just testing nits

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-:-LXKPDp4CWErJvpAlbCx:bfqj15)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @asubiotto, and @RaduBerinde)

___
*[pkg/sql/distsqlrun/flow_registry_test.go, line 627 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LXKMobZ4ew8fsYQONKO:-LXKMobZ4ew8fsYQONKP:b1o9wy) ([raw file](https://github.com/cockroachdb/cockroach/blob/0832989180159b26d3437bbf01742a5d1ed023a1/pkg/sql/distsqlrun/flow_registry_test.go#L627)):*

> The underlying channel will be created with a buffer size of 1 that we will fill up below so that the subsequent Push by the

Can't we just create an unbuffered channel? 
___
*[pkg/sql/distsqlrun/flow_registry_test.go, line 630 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LXKMdxt4wtwGM0PnxQA:-LXKMdxt4wtwGM0PnxQB:b-398pdn) ([raw file](https://github.com/cockroachdb/cockroach/blob/0832989180159b26d3437bbf01742a5d1ed023a1/pkg/sql/distsqlrun/flow_registry_test.go#L630)):*
> ```Go
> 	// size of 1 that we will fill up below so that the subsequent Push by the
> 	// flowRegistry blocks.
> 	rc.init(oneIntCol, func() { pushChan <- struct{}{} }, 1, 1)
> ```

pls comment the many 1s
___
*[pkg/sql/distsqlrun/flow_registry_test.go, line 653 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LXKOE8dA1dOYtP2VMKO:-LXKOE8dA1dOYtP2VMKP:bp9xq1n) ([raw file](https://github.com/cockroachdb/cockroach/blob/0832989180159b26d3437bbf01742a5d1ed023a1/pkg/sql/distsqlrun/flow_registry_test.go#L653)):*
> ```Go
> 	}
> 
> 	// Ensure RegisterFlow performs a Push.
> ```

What's going on here is pretty confusing. One would think that this unblocks the Push into the corresponding row receiver, but I guess it doesn't because there's also a limit on the buffer?
And so we have another `rc.Next()` below and a confusing comment about unblocking on it.

I think your new `callbackRowChannel` should just use a `RowBuffer` instead of `RowChannel`. In fact, I think we can just tweak the `RowBuffer` to take one more callback for the Push - it already takes a bunch of callbacks for similar purposes. I don't think there's much need for a new struct.
___
*[pkg/sql/distsqlrun/flow_registry_test.go, line 656 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LXKNQsZ62OLXGHZ_BhY:-LXKNQsZ62OLXGHZ_BhZ:b-wdkghf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0832989180159b26d3437bbf01742a5d1ed023a1/pkg/sql/distsqlrun/flow_registry_test.go#L656)):*
> ```Go
> 	<-pushChan
> 
> 	// Attempt to register a flow. Note that this flow has no inbound streams; a
> ```

nit: pass `time.Hour` to the timeout and then it's clear that it's irrelevant and this comment is not needed
___
*[pkg/sql/distsqlrun/utils_test.go, line 144 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LXKM8Lv8I-F1ITD5tW8:-LXKM8Lv8I-F1ITD5tW9:b-vhusv9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0832989180159b26d3437bbf01742a5d1ed023a1/pkg/sql/distsqlrun/utils_test.go#L144)):*
> ```Go
> var _ RowReceiver = &callbackRowChannel{}
> 
> func (c *callbackRowChannel) init(
> ```

sup with this `init()`? Why not a regular ctor `func newCallbackRowChannel(...) *callbackRowChannel"?

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34218)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @RaduBerinde)

___
*[pkg/sql/distsqlrun/flow_registry_test.go, line 627 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LXKMobZ4ew8fsYQONKO:-LXKWp3SB-l_R1PYkDiR:b-xg1932) ([raw file](https://github.com/cockroachdb/cockroach/blob/0832989180159b26d3437bbf01742a5d1ed023a1/pkg/sql/distsqlrun/flow_registry_test.go#L627)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>


> The underlying channel will be created with a buffer size of 1 that we will fill up below so that the subsequent Push by the

Can't we just create an unbuffered channel? 


</blockquote></details>

Didn't realize 0 was valid.
___
*[pkg/sql/distsqlrun/flow_registry_test.go, line 630 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LXKMdxt4wtwGM0PnxQA:-LXKadXm-kCyx5Ll0fX7:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/0832989180159b26d3437bbf01742a5d1ed023a1/pkg/sql/distsqlrun/flow_registry_test.go#L630)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls comment the many 1s
</blockquote></details>

Removed.
___
*[pkg/sql/distsqlrun/flow_registry_test.go, line 653 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LXKOE8dA1dOYtP2VMKO:-LXKaKne62E7wHbO0YwN:bg0swku) ([raw file](https://github.com/cockroachdb/cockroach/blob/0832989180159b26d3437bbf01742a5d1ed023a1/pkg/sql/distsqlrun/flow_registry_test.go#L653)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

What's going on here is pretty confusing. One would think that this unblocks the Push into the corresponding row receiver, but I guess it doesn't because there's also a limit on the buffer?
And so we have another `rc.Next()` below and a confusing comment about unblocking on it.

I think your new `callbackRowChannel` should just use a `RowBuffer` instead of `RowChannel`. In fact, I think we can just tweak the `RowBuffer` to take one more callback for the Push - it already takes a bunch of callbacks for similar purposes. I don't think there's much need for a new struct.

</blockquote></details>

Good call, used a `RowBuffer` instead. This however means that I can't verify that the correct timeout is pushed (there is no synchronization between `Next()` and `Push()`). I think that's fine.
___
*[pkg/sql/distsqlrun/flow_registry_test.go, line 656 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LXKNQsZ62OLXGHZ_BhY:-LXKY1XG2s0_4h8ECGjL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0832989180159b26d3437bbf01742a5d1ed023a1/pkg/sql/distsqlrun/flow_registry_test.go#L656)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: pass `time.Hour` to the timeout and then it's clear that it's irrelevant and this comment is not needed
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/utils_test.go, line 144 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LXKM8Lv8I-F1ITD5tW8:-LXKabGv1Sh-vf39SKwW:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/0832989180159b26d3437bbf01742a5d1ed023a1/pkg/sql/distsqlrun/utils_test.go#L144)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

sup with this `init()`? Why not a regular ctor `func newCallbackRowChannel(...) *callbackRowChannel"?
</blockquote></details>

Removed.

**Review by andreimatei — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-:-LXKukwF-ZElMRsxhc9q:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @asubiotto)

___
*[pkg/sql/distsqlrun/flow_registry_test.go, line 653 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LXKOE8dA1dOYtP2VMKO:-LXKsPqW3dQcXb9DbNkl:belxh4w) ([raw file](https://github.com/cockroachdb/cockroach/blob/0832989180159b26d3437bbf01742a5d1ed023a1/pkg/sql/distsqlrun/flow_registry_test.go#L653)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Good call, used a `RowBuffer` instead. This however means that I can't verify that the correct timeout is pushed (there is no synchronization between `Next()` and `Push()`). I think that's fine.
</blockquote></details>

You could pass the row/meta to the OnPush() callback and, through that, to this channel. And then the confusing comment about `Pushes can only occur with flows that...` can go away.
___
*[pkg/sql/distsqlrun/flow_registry_test.go, line 621 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LXKt4uU2JRrbgVog3l5:-LXKt4uU2JRrbgVog3l6:b4mc3xc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5114147c73e3f4ebf30d138ebf5130718d6f4fed/pkg/sql/distsqlrun/flow_registry_test.go#L621)):*
> ```Go
> 	ctx := context.Background()
> 	fr := makeFlowRegistry(0)
> 	wg := sync.WaitGroup{}
> ```

nit: move this down to where it's used, and also `Add()` to it before passing it to the `streamInfo` struct (that's the usual pattern - one first Adds to the wg before passing it to someone else)
But better yet, I'd make `inboundStreamInfo.wg` optional, and just not pass anything in this test.
___
*[pkg/sql/distsqlrun/flow_registry_test.go, line 633 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LXKtoXF-MK9c2PufS4g:-LXKtoXF-MK9c2PufS4h:bzaf173) ([raw file](https://github.com/cockroachdb/cockroach/blob/5114147c73e3f4ebf30d138ebf5130718d6f4fed/pkg/sql/distsqlrun/flow_registry_test.go#L633)):*
> ```Go
> 		RowBufferArgs{
> 			OnPush: func() {
> 				pushChan <- struct{}{}
> ```

nit: you can do with a single channel here, and the code would be more readable
```
pushCh <- struct{}{}
<-pushCh
```
___
*[pkg/sql/distsqlrun/flow_registry_test.go, line 668 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LXKteAD1gO61Sj33bJ4:-LXKteAD1gO61Sj33bJ5:b-5pxfxz) ([raw file](https://github.com/cockroachdb/cockroach/blob/5114147c73e3f4ebf30d138ebf5130718d6f4fed/pkg/sql/distsqlrun/flow_registry_test.go#L668)):*
> ```Go
> 	<-blockChan
> 
> 	// Wait for the goroutine spawned in the first RegisterFlow call.
> ```

Is this wait needed? I think everything would work just fine without it, no?

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34218)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/sql/distsqlrun/flow_registry_test.go, line 653 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LXKOE8dA1dOYtP2VMKO:-LXLQlfX9-HyTD9E2u_1:b6iw0jk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0832989180159b26d3437bbf01742a5d1ed023a1/pkg/sql/distsqlrun/flow_registry_test.go#L653)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

You could pass the row/meta to the OnPush() callback and, through that, to this channel. And then the confusing comment about `Pushes can only occur with flows that...` can go away.
</blockquote></details>

The comment was meant to explain why we do not need to read from the `pushChan` for the subsequent `RegisterFlow`, rephrased and moved above RegisterFlow. Changed the pushChan to accept meta so we can verify the error. 
___
*[pkg/sql/distsqlrun/flow_registry_test.go, line 621 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LXKt4uU2JRrbgVog3l5:-LXLRKtK8f95dDBxsa-o:byitrlp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5114147c73e3f4ebf30d138ebf5130718d6f4fed/pkg/sql/distsqlrun/flow_registry_test.go#L621)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: move this down to where it's used, and also `Add()` to it before passing it to the `streamInfo` struct (that's the usual pattern - one first Adds to the wg before passing it to someone else)
But better yet, I'd make `inboundStreamInfo.wg` optional, and just not pass anything in this test.
</blockquote></details>

I `Add` before passing it to `RegisterFlow` through `inboundStreams`. Moved all the code together.
___
*[pkg/sql/distsqlrun/flow_registry_test.go, line 633 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LXKtoXF-MK9c2PufS4g:-LXLRvdQ2zMpDVAO-xQt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5114147c73e3f4ebf30d138ebf5130718d6f4fed/pkg/sql/distsqlrun/flow_registry_test.go#L633)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: you can do with a single channel here, and the code would be more readable
```
pushCh <- struct{}{}
<-pushCh
```
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/flow_registry_test.go, line 668 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/34218#-LXKteAD1gO61Sj33bJ4:-LXLSZTuCPuFIuxls9LV:byfxg50) ([raw file](https://github.com/cockroachdb/cockroach/blob/5114147c73e3f4ebf30d138ebf5130718d6f4fed/pkg/sql/distsqlrun/flow_registry_test.go#L668)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Is this wait needed? I think everything would work just fine without it, no?
</blockquote></details>

It's not needed, but thought I might as well follow the pattern. Removed since it seems to be confusing.

**Pull request merged**
