### PR TITLE
kvserver, server: new implementation of SpanStats suitable for use with coalesced ranges

### PR DESCRIPTION
**Pull request by zachlite**
This commit provides a re-implementation of fetching the MVCC stats
and range count for a given span. The previous implementation relied on
the assumption that 1 range can contain at most 1 table/index. Since
GH-79700, this assumption is no longer true.

This re-implementation allows secondary tenants to access span stats
via the serverpb.TenantStatusServer interface.

If a roachpb.SpanStatsRequest has a node_id value of 0, instead of a specific
node id, the response will yield cluster-wide values. To achieve this,
the server does a fan-out to nodes that are known to have replicas for the
span requested.

The interaction between tenants is illustrated below:

```
 System Tenant
┌────────────────────────────────────────────────────┐
│                                                    │
│                                                    │
│                                    KV Node fan-out │
│                                     ┌──────────┐   │
│                                     │          │   │
│     ┌───────────────────────────────▼────┐     │   │
│     │                                    │     │   │
│     │      server.systemStatusServer     ├─────┘   │
│     │                                    │         │
│     └────────────────┬───────────────────┘         │
│                      │                             │
│                      │                             │
│                      │     via TenantStatusServer  │
│                      ├──────────────┐              │
│                      │              │              │
│                      │              │              │
│                      │              ▼              │
│                      │        ┌───────────┐        │
│                      │        │           │        │
│                      │        │ SQLServer │        │
│                      │        │           │        │
│                      │        └───────────┘        │
│                      │                             │
└──────────────────────▼─────────────────────────────┘
                       │
                       │
                       │
                       │   roachpb.SpanStatsResponse
                       │
                       │
 Secondary Tenant      │
┌──────────────────────┼──────────────────────────────┐
│                      │                              │
│         ┌────────────▼─────────────┐                │
│         │            │             │                │
│         │   kvtenantccl.Connector  │                │
│         │                          │                │
│         └────────────┬─────────────┘                │
│                      │                              │
│                      │    via TenantStatusServer    │
│                      ├────────────────────┐         │
│                      │                    │         │
│                      │                    │         │
│                      │                    │         │
│    ┌─────────────────▼───────┐     ┌──────▼──────┐  │
│    │                         │     │             │  │
│    │    server.statusServer  │     │  SQLServer  │  │
│    │                         │     │             │  │
│    └─────────────────────────┘     └─────────────┘  │
│                                                     │
│                                                     │
│                                                     │
└─────────────────────────────────────────────────────┘
```

Part of: https://cockroachlabs.atlassian.net/browse/CRDB-22711
Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
I am so happy to see this PR. Thank you zach.

As a minor point, would you be open to having this code inside the `sql` package or one of its sub-packages. This way we can also think about embedding this estimate in SQL functions that the SQL obs team is currently implementing (@THardy98)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-:-NN3GDQB9TGSlV0o-eGk:b3b88jc)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by zachlite — COMMENTED** [review]
> would you be open to having this code inside the sql package or one of its sub-packages.

Sure! Pending any feedback or issues with my implementation so far, I'll make this more accessible for other callers.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-:-NN3GkwICtrI_aHFlRsX:bbqccns)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96223)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @zachlite)

___
*[`pkg/server/status.go` line 3415 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-NN3N9Bg1T3Iv4Btw624:-NN3N9Bg1T3Iv4Btw625:bati7ut) ([raw file](https://github.com/cockroachdb/cockroach/blob/13ca09a763c228bbb4bad68887c494f0b6a9f360/pkg/server/status.go#L3415)):*
> ```Go
> 		return status.SpanStats(ctx, req)
> 	}
> 	fetcher := rangestats.NewFetcher(s.db)
> ```

Before we move forward with the review, may I suggest you extract this code into a separate function, with a clear API interface.
It should probably take start/end keys as parameters. And return StoreKeySpanStats. Probably something like the same API interface as the original Compute function you've removed.

Inside this function, it would also be good to avoid accumulating the descriptors in an array. You can interleave the iteration with the extraction of the stats below.

**Comment by THardy98** [comment]
> I am so happy to see this PR. Thank you zach.
> 
> As a minor point, would you be open to having this code inside the `sql` package or one of its sub-packages. This way we can also think about embedding this estimate in SQL functions that the SQL obs team is currently implementing (@THardy98)
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-:-NN3GDQB9TGSlV0o-eGk:b3b88jc)_ status: :shipit: complete! 0 of 0 LGTMs obtained

Nice :)

Looking a bit further ahead, it would be really nice to be able to get stats for multiple spans at once - which I understand is outside the scope of the initial issue description: 

> It is possible that we may want to allow for multiple spans in the same request, but that decision is out of scope for this initial issue statement.

but would be incredibly useful on the SQL Obs side to get stats for many table spans.

Currently, we have to get table stats **per table**, which means a node fanout for each table span, where we could be dealing with 100s or 1000s of tables. It would be great to issue a single fanout for a collection of table spans, considering that (as I understand it), the actual range stats collection for multiple spans can be done cheaply.

Perhaps not for this PR, but would be really nice in a followup.

**Review by zachlite — COMMENTED** [review]
@knz 
I've made span stats available for consumption by `pkg/sql` by putting the logic behind a new `spanstats.Accessor` interface. The idea is that there will be two implementations of `spanstats.Accessor`, because access to KV is dependent on the type and location of the tenant.

So far, this PR includes the first implementation: `spanstatsaccessor.LocalAccessor`.  This implementation is meant for consumers of span stats that are co-located on a KV node.
For the second implementation, I'm planning on `kvtenantccl.Connector` implementing the `spanstats.Accessor` interface.

And I'm sorry about the diff noise - I had to reclaim the name `span_stats_server` from my work on the Key Visualizer, so there's a file rename in this PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-:-NN9wy945CySE8HjxzTw:bbfhv82)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @knz, and @mgartner)

___
*[`pkg/server/status.go` line 3415 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-NN3N9Bg1T3Iv4Btw624:-NN9wh0yBj3bN2GMuly5:bb7cwne) ([raw file](https://github.com/cockroachdb/cockroach/blob/13ca09a763c228bbb4bad68887c494f0b6a9f360/pkg/server/status.go#L3415)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Before we move forward with the review, may I suggest you extract this code into a separate function, with a clear API interface.
It should probably take start/end keys as parameters. And return StoreKeySpanStats. Probably something like the same API interface as the original Compute function you've removed.

Inside this function, it would also be good to avoid accumulating the descriptors in an array. You can interleave the iteration with the extraction of the stats below.
</blockquote></details>

ack.

**Review by knz — COMMENTED** [review]
Okay this PR is in a much better shape now. Thanks for the investment.
The main remaining topic I'd like to cover is the selection of node IDs.

In the code you're replacing, we have this function `nodeIDsAndRangeCountForSpan()` in `pkg/server` which is used by `(s *adminServer) statsForSpan()` to avoid going to every node to ask about stats for just a few ranges.

Your solution as currently implemented goes to talk to every node in every case. That seems a bit expensive.
Is there a way to be more intelligent here, by discovering which nodes have ranges for the span under consideration, and only calling InternalSpanStats on these nodes?

> Reviewed 2 of 7 files at r1, 20 of 20 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-:-NNCzR6AEjgQd2VnGZwR:b-ia3il5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @mgartner, and @zachlite)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-NNCxQ0X2pqVgOfjaDt3):*
Please massage this commit title / message to give it more structure.
___
*[`pkg/kv/kvclient/spanstats/span_stats.go` line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-NNCxWq2-JiEClHKzAGR:-NNCxWq2-JiEClHKzAGS:bxgefqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/69b671427d8669dfc7f4af6c6b235ea586d928bb/pkg/kv/kvclient/spanstats/span_stats.go#L23)):*
> ```Go
> // boundary.
> type Accessor interface {
> ```

nit: remove empty line.
___
*[`pkg/kv/kvclient/spanstats/spanstatsaccessor/accessor.go` line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-NNCxZB96Z9pz75yj8-w:-NNCxZB96Z9pz75yj8-x:b-iipjm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/69b671427d8669dfc7f4af6c6b235ea586d928bb/pkg/kv/kvclient/spanstats/spanstatsaccessor/accessor.go#L27)):*
> ```Go
> 	endKey roachpb.Key, nodeID roachpb.NodeID,
> ) (*serverpb.InternalSpanStatsResponse, error) {
> ```

nit: ditto
___
*[`pkg/server/key_visualizer_server.go` line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-NNCxe4293i9v9nYbf5E:-NNCxe4293i9v9nYbf5F:b-iipjm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/69b671427d8669dfc7f4af6c6b235ea586d928bb/pkg/server/key_visualizer_server.go#L48)):*
> ```Go
> 	ctx context.Context, req *keyvispb.UpdateBoundariesRequest,
> ) error {
> ```

nit: ditto
___
*[`pkg/server/key_visualizer_server.go` line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-NNCxesl33jOcDlAX0xy:-NNCxesl33jOcDlAX0xz:bcjvhoz) ([raw file](https://github.com/cockroachdb/cockroach/blob/69b671427d8669dfc7f4af6c6b235ea586d928bb/pkg/server/key_visualizer_server.go#L50)):*
> ```Go
> 
> 	encoded, err := protoutil.Marshal(req)
> ```

nit: remove empty line here too.
___
*[`pkg/server/key_visualizer_server.go` line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-NNCxhiWDO2079r7LlFm:-NNCxhiWDO2079r7LlFn:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/69b671427d8669dfc7f4af6c6b235ea586d928bb/pkg/server/key_visualizer_server.go#L117)):*
> ```Go
> 		"iterating nodes for key visualizer samples", dialFn, nodeFn,
> 		responseFn, errorFn)
> ```

ditto
___
*[`pkg/server/key_visualizer_server.go` line 140 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-NNCxism6wgnqgpHhKXW:-NNCxism6wgnqgpHhKXX:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/69b671427d8669dfc7f4af6c6b235ea586d928bb/pkg/server/key_visualizer_server.go#L140)):*
> ```Go
> // spans.
> func verifySampleBoundariesEqual(fragments []keyvispb.Sample) bool {
> ```

ditto
___
*[`pkg/server/server.go` line 847 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-NNCyPBa0723Dmk5aJDc:-NNCyPBa0723Dmk5aJDd:bb78ix2) ([raw file](https://github.com/cockroachdb/cockroach/blob/69b671427d8669dfc7f4af6c6b235ea586d928bb/pkg/server/server.go#L847)):*
> ```Go
> 	// Instantiate the span stats server. There is a circular dependency
> 	// between server.spanStatsServer and server.systemStatusServer.
> 	spanStats := &spanStatsServer{
> ```

Can you coordinate with @dhartunian to double check how this is meant to work for secondary tenant servers.
___
*[`pkg/server/serverpb/span_stats.proto` line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-NNCxwIe1Ptn7C3w6lyK:-NNCxwIe1Ptn7C3w6lyL:bmxh7y3) ([raw file](https://github.com/cockroachdb/cockroach/blob/69b671427d8669dfc7f4af6c6b235ea586d928bb/pkg/server/serverpb/span_stats.proto#L43)):*
> ```protobuf
> service SpanStats {
>   rpc GetSpanStats(InternalSpanStatsRequest) returns (InternalSpanStatsResponse) {}
> }
> ```

nit: missing newline at end of file.
___
*[`pkg/kv/kvserver/client_status_test.go` line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-NNCyDoQ7MhFJPjZxdgp:-NNCyDoQ7MhFJPjZxdgq:b-gqosri) ([raw file](https://github.com/cockroachdb/cockroach/blob/69b671427d8669dfc7f4af6c6b235ea586d928bb/pkg/kv/kvserver/client_status_test.go#L81)):*
> ```Go
> 		_ = tcase
> 		t.Errorf("implement me")
> 		//start, end := tcase.startKey, tcase.endKey
> ```

Don't forget to do this.

**Review by zachlite — COMMENTED** [review]
Thanks for the feedback.  I'll take a look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-:-NND1Gy97AYRBNOSdsqW:b-mx2fqw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @mgartner)

**Review by zachlite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96223)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dhartunian, @knz, and @mgartner)

___
*[`pkg/kv/kvclient/spanstats/span_stats.go` line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-NNCxWq2-JiEClHKzAGR:-NNDUOgx8JeNtVtm4r6h:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/69b671427d8669dfc7f4af6c6b235ea586d928bb/pkg/kv/kvclient/spanstats/span_stats.go#L23)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: remove empty line.
</blockquote></details>

Done.
___
*[`pkg/kv/kvclient/spanstats/spanstatsaccessor/accessor.go` line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-NNCxZB96Z9pz75yj8-w:-NNDUTLr7XUCv-Nrue-m:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/69b671427d8669dfc7f4af6c6b235ea586d928bb/pkg/kv/kvclient/spanstats/spanstatsaccessor/accessor.go#L27)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: ditto
</blockquote></details>

Done.
___
*[`pkg/server/key_visualizer_server.go` line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-NNCxe4293i9v9nYbf5E:-NNDUYzG7t0N81O7ePBY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/69b671427d8669dfc7f4af6c6b235ea586d928bb/pkg/server/key_visualizer_server.go#L48)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: ditto
</blockquote></details>

Done.
___
*[`pkg/server/key_visualizer_server.go` line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-NNCxesl33jOcDlAX0xy:-NNDUacU96mn5z7bv35A:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/69b671427d8669dfc7f4af6c6b235ea586d928bb/pkg/server/key_visualizer_server.go#L50)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: remove empty line here too.
</blockquote></details>

Done.
___
*[`pkg/server/key_visualizer_server.go` line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-NNCxhiWDO2079r7LlFm:-NNDUcsJ5YbXzg_SlQ98:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/69b671427d8669dfc7f4af6c6b235ea586d928bb/pkg/server/key_visualizer_server.go#L117)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pkg/server/key_visualizer_server.go` line 140 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-NNCxism6wgnqgpHhKXW:-NNDUenz6aFOqrvaHz04:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/69b671427d8669dfc7f4af6c6b235ea586d928bb/pkg/server/key_visualizer_server.go#L140)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pkg/server/server.go` line 847 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-NNCyPBa0723Dmk5aJDc:-NNDYbEM-Xb0AxMnBuQT:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/69b671427d8669dfc7f4af6c6b235ea586d928bb/pkg/server/server.go#L847)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Can you coordinate with @dhartunian to double check how this is meant to work for secondary tenant servers.
</blockquote></details>

:thumbsup: 
___
*[`pkg/server/serverpb/span_stats.proto` line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-NNCxwIe1Ptn7C3w6lyK:-NNDUgYz1qF7nON1VTgP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/69b671427d8669dfc7f4af6c6b235ea586d928bb/pkg/server/serverpb/span_stats.proto#L43)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: missing newline at end of file.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/client_status_test.go` line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-NNCyDoQ7MhFJPjZxdgp:-NNdH1ZtEU8dFrd6xDd-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/69b671427d8669dfc7f4af6c6b235ea586d928bb/pkg/kv/kvserver/client_status_test.go#L81)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Don't forget to do this.
</blockquote></details>

Done.

**Review by knz — COMMENTED** [review]
nit: i've renamed the PR: the work is about enabling _coalesced ranges_ and is not specific to multi-tenancy. (Coalesced ranges are pretty much necessary to CC serverless, but they would be useful to everyone else too, but we can't enable them until the issue you're working on here is fixed.)

Beyond that, this mostly looks good. I'm generally happy with where you brought this.  Let's be extra careful about the authorization rule though.

After that, let's also be mindful that the folk who need to sign off on your approach (because they maintain this API infrastructure) are our obs-inf coworkers. So please go through the remaining review iterations with them as well.

> Reviewed 23 of 27 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-:-NNgaJkuD48ZRN-R3JOW:b-i93ig8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @mgartner, and @zachlite)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-NNgaX6M66qxl6dppaGs):*
NB: the first line in a commit message has a special role, it is called the "commit title" and shows up in many places - the git log summary, patch headers, etc.

So it needs to be structured like a title. See this for guidance:

https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages#Commit-title
___
*[`-- commits` line 8 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-NNgcruBEzudOv5zaNlJ):*
Thanks for enumerating the 3 components.
For each of them, can you also sketch what _client components_ use the new component and where in the source code this happens.

Generally, it would be useful to understand by reading the commit message which go interface / components you've connected to each other to make it work.
___
*[`pkg/rpc/auth_tenant.go` line 119 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-NNgdeeU1Vw1K_GzrmD3:-NNgdeeVCGrYYI0OvwEy:b-prpk42) ([raw file](https://github.com/cockroachdb/cockroach/blob/385d4ef4d5d1f2b7c8caccce584d6bf06353775e/pkg/rpc/auth_tenant.go#L119)):*
> ```Go
> 
> 	case "/cockroach.server.serverpb.Status/SpanStats":
> 		return a.authTenant(tenID)
> ```

That won't do. You need to extend the verification to the start/end keys in the request, that they are properly contained inside the tenant keyspace.
See `authRangeFeed` for an example.

**Review by zachlite — COMMENTED** [review]
:thumbsup: 

> Reviewed 1 of 20 files at r2, 18 of 27 files at r3, 2 of 4 files at r4, 13 of 13 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-:-NNhK0gM7KW3ylMQxciA:b4c9lyr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @knz, and @mgartner)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-NNCxQ0X2pqVgOfjaDt3):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Please massage this commit title / message to give it more structure.
</blockquote></details>

Done.
___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-NNgaX6M66qxl6dppaGs):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

NB: the first line in a commit message has a special role, it is called the "commit title" and shows up in many places - the git log summary, patch headers, etc.

So it needs to be structured like a title. See this for guidance:

https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages#Commit-title
</blockquote></details>

Done.
___
*[`-- commits` line 8 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-NNgcruBEzudOv5zaNlJ):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Thanks for enumerating the 3 components.
For each of them, can you also sketch what _client components_ use the new component and where in the source code this happens.

Generally, it would be useful to understand by reading the commit message which go interface / components you've connected to each other to make it work.
</blockquote></details>

Done.
___
*[`pkg/rpc/auth_tenant.go` line 119 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-NNgdeeU1Vw1K_GzrmD3:-NNhHdb71lUWVEMWzQr-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/385d4ef4d5d1f2b7c8caccce584d6bf06353775e/pkg/rpc/auth_tenant.go#L119)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

That won't do. You need to extend the verification to the start/end keys in the request, that they are properly contained inside the tenant keyspace.
See `authRangeFeed` for an example.
</blockquote></details>

Done.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96223)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @mgartner, and @zachlite)

___
*[`-- commits` line 84 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-NNhKvy1BdmWwfSpMDQ6):*
:sparkling_heart: :100:

**Comment by THardy98** [comment]
We're already doing the work to get the node IDs tied to these ranges as well. Would it be possible to return that as part of the SpanStats response?

**Review by dhartunian — COMMENTED** [review]
Status server stuff looks good.

I'd like to see a tenant-level tests for this. do you think you can add one like the one in `span_stats_test.go` to `statusccl/tenant_status_test.go`? I'm not sure we have tenant-level coverage.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-:-NNw3a171iQMp7foNjgQ:bikdzz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @knz, @mgartner, and @zachlite)

**Review by dhartunian — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-:-NOFgVkV9TZhQVrS492z:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @knz, @mgartner, and @zachlite)

**Review by dhartunian — CHANGES_REQUESTED** [review]
Actually, before moving forward want to check in re: changing the nodeID to an int. I'd like to avoid that with the protobufs. We can add a new field with a new ID but changing an existing one can really break stuff unless maybe we can prove nothing uses this endpoint.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-:-NOFh4ZG94wPVSr2ag2M:b4iz2de)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @knz, @mgartner, and @zachlite)

**Review by THardy98 — APPROVED** [review]
:lgtm:

> Reviewed 6 of 28 files at r6, 5 of 13 files at r7, 9 of 9 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-:-NOFs4fo2zXOPjyHlUDp:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @ajwerner, @knz, @mgartner, and @zachlite)

**Review by dhartunian — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96223#-:-NOG0uv31theAKxSfBL1:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @knz, @mgartner, @THardy98, and @zachlite)

**Pull request merged**
