### PR TITLE
colexec, colflow: fix router output and hash router when disk limit is hit

### LINKED ISSUE #47203: colexec: diskqueue nil pointer dereference
DiskQueue runs into nil pointer dereference error when running the sqlite logic test in [`select4.test`][1]

Using the tables created in `select4.test` , following query causes nil pointer dereference error:

```
SELECT e8, d7+959, a5*693, e2, e6*447, b1+778
  FROM t1, t6, t7, t5, t8, t2
 WHERE c5 in (489,250,927,855,697,130,856)
   AND (180=e8 OR 333=e8 OR e8=38)
   AND e7=462
   AND b2=b1
```

Error stack trace: 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5be6121]

goroutine 3154 [running]:
github.com/cockroachdb/cockroach/pkg/col/colserde.(*countingWriter).Write(...)
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/col/colserde/file.go:329
github.com/cockroachdb/cockroach/pkg/col/colserde.(*FileSerializer).Finish(0xc0054f3980, 0x0, 0x0)
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/col/colserde/file.go:139 +0x131
github.com/cockroachdb/cockroach/pkg/sql/colcontainer.(*diskQueue).writeFooterAndFlush(0xc004052480, 0x7f0dd20, 0xc003889400, 0xc00226dc10, 0x400855f)
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/sql/colcontainer/diskqueue.go:481 +0x36
github.com/cockroachdb/cockroach/pkg/sql/colcontainer.(*diskQueue).Close(0xc004052480, 0x7f0dd20, 0xc003889400, 0xc00226dcc8, 0x404252f)
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/sql/colcontainer/diskqueue.go:399 +0x36c
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*spillingQueue).close(0xc00328cc00, 0x7f0dd20, 0xc003889400, 0x4, 0xc003a29e60)
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/spilling_queue.go:271 +0x65
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*routerOutputOp).closeLocked(0xc0021f99e0, 0x7f0dd20, 0xc003889400)
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/routers.go:225 +0x4b
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*routerOutputOp).cancel(0xc0021f99e0, 0x7f0dd20, 0xc003889400)
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/routers.go:238 +0x58
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*HashRouter).Run.func1(0x7e9e3e0, 0xc005892b70)
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/routers.go:457 +0xa3
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*HashRouter).Run(0xc0021f9b00, 0x7f0dd20, 0xc003889400)
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/routers.go:497 +0x1b6
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreator).setupRouter.func1(0x7f0dd20, 0xc003889400, 0xc001ce1450)
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:676 +0xa5
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreatorHelper).accumulateAsyncComponent.func1.1(0xc003a6e1a0, 0x7f0dd20, 0xc003889400, 0xc001ce1450, 0xc004052f70)
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1171 +0x44
created by github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreatorHelper).accumulateAsyncComponent.func1
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1170 +0x6f


```

[1]: https://github.com/cockroachdb/sqllogictest/blob/master/test/select4.test

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec, colflow: make hash router catch panics during cancellation**

Previously, if a panic occurred during the cancellation of hash router's
outputs, it could crash the server because hash routers run in their own
goroutines. This is now fixed by wrapping the cancellation with the
panic-catcher. If any error occurs in that phase, it is buffered to be
propagated as metadata. We also now wrap the whole `Run` method with
a catcher just to be safe.

Addresses: #47203.

Release note: None

**colexec: prevent calls to disk queue in invalid state**

This commit fixes the interaction between hash router and router output
when the latter hits an error. Previously we could end up in a state
where router output's disk queue is invalid, but the hash router doesn't
know about it, so it would proceed to calling `addBatch` which could
attempt to enqueue another batch to the disk queue.

Now we introduce a new draining state of `routerOutputOp` in which it
returns zero-length batches on calls to `Next`. The output transitions
into draining state either when it is finished or when it encounters an
error. That error will be propagated to the hash router either on the
next call to `addBatch` or during draining of the hash router by calling
`routerOutputOp.drain()`.

Additionally, it makes memory accounting of disk queue more safe (by making
sure that we do not attempt to shrink the disk account by more than is
currently used).

Fixes: #47203.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Some thoughts on two commits:
1. to be honest, I do not fully understand why the first commit solves the bad state `diskQueue` could end in
2. for the second commit we might want to wrap the whole `HashRouter.Run` method with a panic-catcher (with a sub-panic-catcher inside around `processNextBatch`).

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47238)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colcontainer/diskqueue.go, line 666 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47238#-M4nqTn43QNva3x7_JG_:-M4nqTn43QNva3x7_JGa:bdkajno) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7da82ade1b74fd17493b0c2542e504ec0f35a09/pkg/sql/colcontainer/diskqueue.go#L666)):*
> ```Go
> func (d *diskQueue) Dequeue(ctx context.Context, b coldata.Batch) (bool, error) {
> 	if d.serializer != nil && d.numBufferedBatches > 0 {
> 		if err := d.rotateFile(ctx); err != nil {
> ```

Based on the stack trace of the issue something in the serializer is nil. Since `rotateFile` calls `writeFooterAndFlush` and then `resetWriters` with the new file I don't see how this would fix the nil pointer. Can this be reproduced in a test?
___
*[pkg/sql/colexec/routers.go, line 452 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47238#-M4nr5sx3HiXhQGXY6NX:-M4nr5sx3HiXhQGXY6NY:b-78bbhz) ([raw file](https://github.com/cockroachdb/cockroach/blob/350a9ba9e980b6078a0c289980bf13a5d84397d9/pkg/sql/colexec/routers.go#L452)):*
> ```Go
> 	// cancelOutputs buffers non-nil error as metadata, cancels all of the
> 	// outputs and returns any error if such occurs during the outputs'
> 	// cancellation.
> ```

I don't think we should return an error from `Run`. It seems better to me to add it to `bufferedMeta` and return it in `DrainMeta`, otherwise operators will have to go through log files rather than observing the error in the client. I also wonder whether we need to proceed to canceling all outputs regardless of whether one panics. Maybe we should move the panic catching into cancel and have that return an error.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47238)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colcontainer/diskqueue.go, line 666 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47238#-M4nqTn43QNva3x7_JG_:-M4oVWAm8JADmd1080iQ:b-nkcfur) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7da82ade1b74fd17493b0c2542e504ec0f35a09/pkg/sql/colcontainer/diskqueue.go#L666)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Based on the stack trace of the issue something in the serializer is nil. Since `rotateFile` calls `writeFooterAndFlush` and then `resetWriters` with the new file I don't see how this would fix the nil pointer. Can this be reproduced in a test?
</blockquote></details>

`FileSerializer.w` somehow ends up being `nil`. I've also seen `countingWriter.wrapped` being `nil`. Added a test that reproduces the problem reliably on master (you might wanna cut it out and run only with `fakedist-vec-disk` config for a quicker reproduction).
___
*[pkg/sql/colexec/routers.go, line 452 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47238#-M4nr5sx3HiXhQGXY6NX:-M4ocY45BO3eNXw3njvH:b-he52at) ([raw file](https://github.com/cockroachdb/cockroach/blob/350a9ba9e980b6078a0c289980bf13a5d84397d9/pkg/sql/colexec/routers.go#L452)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I don't think we should return an error from `Run`. It seems better to me to add it to `bufferedMeta` and return it in `DrainMeta`, otherwise operators will have to go through log files rather than observing the error in the client. I also wonder whether we need to proceed to canceling all outputs regardless of whether one panics. Maybe we should move the panic catching into cancel and have that return an error.
</blockquote></details>

Done. I also added a catcher around the whole `Run` method just to be safe (for example, `Init` method could panic as well).

**Comment by asubiotto** [comment]
We might be getting into a weird state where `writeFile` is nil but we don't set the serializer to nil or reset the number of buffered batches. I'll take a look

**Comment by asubiotto** [comment]
I'm pretty certain that what's going on here is the following:
- A `Dequeue` happens in `Next`.
- `Dequeue` tries to flush pending batches using `writeFooterAndFlush`, which calls `serializer.Finish` which has the side effect of resetting the underlying `writer` to nil. After actually flushing the data, we attempt to grow the disk monitor, which returns an error. This means we never actually call `resetWriters` so are left with a nil `writer` in the serializer. The error is propagated as a panic through `Next`
-  However, the `HashRouter` has no idea this error happened and tries to `Enqueue` a batch, which runs into this nil pointer error.

I think the change you made just makes this harder to hit since the `Dequeue` goroutine has to perform a system call to create a file, so the `Enqueue` goroutine is a lot more likely to hit the out of disk error.

What we should do here is probably save the error somewhere in `routerOutputOp` and return it during `addBatch` if non-nil. This will avoid us calling `Enqueue` after an error which should be prohibited. However, we might have a double error in this case, but we also want to make sure we're not calling `Dequeue` again from the `Next` goroutine. Maybe we should return a zero-length batch instead? I actually think I prefer that, and let the `HashRouter` propagate the OOM error.

**Review by yuzefovich — COMMENTED** [review]
I see, this explanation makes sense. I propose a different way to address this problem - by introducing an error tracking wrapper around the disk queue. Let me know what you think.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47238#-:-M4yVHFqE5u7RytFmMZZ:bphslup)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

**Review by asubiotto — COMMENTED** [review]
I'm not sure I like the error wrapper idea. In principle it's sound, but in practice there are a lot of components that shouldn't be accessed once an error is returned (I think). Philosophically speaking, I think it is the caller's responsibility to do this. In practice, I think we might also end up in cases where we're propagating the same error twice (through HashRouter draining and Next calls).

> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47238#-:-M4yksniCQyJOV-Y_XjG:b-n7rb03)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/vectorize_sqllite, line 429 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/47238#-M4ykdJZ2zKTemm8SLi0:-M4ykdJZ2zKTemm8SLi1:b-upr39u) ([raw file](https://github.com/cockroachdb/cockroach/blob/93b9bc63849ff1aaf1b93d8171d918e2bc215c98/pkg/sql/logictest/testdata/logic_test/vectorize_sqllite#L429)):*
> ```
> 13
> 
> subtest regression_47203
> ```

Per our offline discussion, I think we should delete this test and work on error injection in memory monitors separately. Could you create an issue for that?

**Review by yuzefovich — COMMENTED** [review]
Ok, I see merit in your reasoning, refactored.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47238#-:-M4yy3Ev06L85iKdsNRN:b-is9ben)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/logictest/testdata/logic_test/vectorize_sqllite, line 429 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/47238#-M4ykdJZ2zKTemm8SLi0:-M4yqK5NDoJp7AVQnrM2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/93b9bc63849ff1aaf1b93d8171d918e2bc215c98/pkg/sql/logictest/testdata/logic_test/vectorize_sqllite#L429)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Per our offline discussion, I think we should delete this test and work on error injection in memory monitors separately. Could you create an issue for that?
</blockquote></details>

Done.

**Review by asubiotto — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47238)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/routers.go, line 278 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/47238#-M56bTPE3l5RV1Sgx7TY:-M56bTPE3l5RV1Sgx7TZ:b-hxa81x) ([raw file](https://github.com/cockroachdb/cockroach/blob/872c7032cd680dbe6e5ae4c62000554127e7cf51/pkg/sql/colexec/routers.go#L278)):*
> ```Go
> 		// it, so we do so now - the error will get to the hash router which
> 		// will cancel all of its outputs.
> 		execerror.VectorizedInternalPanic(o.mu.dataDequeueErr)
> ```

It might be the case that no more `addBatch` calls will happen after an error is encountered in `Next`. I think we should probably add a small mechanism that "drains" outputs of this error. If an output already returned this error this way, the drain call would be a noop. What do you think?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47238)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/routers.go, line 278 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/47238#-M56bTPE3l5RV1Sgx7TY:-M58-_0NB_Yqo7twq71C:brfa6lj) ([raw file](https://github.com/cockroachdb/cockroach/blob/872c7032cd680dbe6e5ae4c62000554127e7cf51/pkg/sql/colexec/routers.go#L278)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It might be the case that no more `addBatch` calls will happen after an error is encountered in `Next`. I think we should probably add a small mechanism that "drains" outputs of this error. If an output already returned this error this way, the drain call would be a noop. What do you think?
</blockquote></details>

Good point, refactored.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47238#-:-M5M734TAElJqDPJqCPK:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
