### PR TITLE
tree: make BinaryOperator AST node aware of OPERATOR

### PR DESCRIPTION
**Pull request by otan**
This makes pretty printing preserve the order of operations. Push the
existing definition of BinaryOperator as BinaryOperatorSymbol, then make
BinaryOperator wrap that as well as a bool on whether or not it is an
OPERATOR operation. Then refactor everything else accordingly.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Do you have a reference where I can read about what `OPERATOR` does?

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66872#-:-MdIZRMq7jtGc3MvFh3V:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[pkg/sql/parser/sql.y, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66872#-MdIYPdP3XdePXd5quHt:-MdIYPdP3XdePXd5quHu:bd1enoi) ([raw file](https://github.com/cockroachdb/cockroach/blob/df88f43fe5da1b2f86ca77b956b11480970fbb2e/pkg/sql/parser/sql.y#L80)):*
> ```Yacc
>   rhs tree.Expr,
> ) (tree.Expr, int) {
>   e, code := processBinaryQualOpInternal(sqllex, op, lhs, rhs)
> ```

[nit] why separate an internal function when we can just add the new code to the BinaryOperator case?
___
*[pkg/sql/sem/tree/expr.go, line 1124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66872#-MdIY1ORBjX8dKIezfoN:-MdIY1ORBjX8dKIezfoO:b-w30qib) ([raw file](https://github.com/cockroachdb/cockroach/blob/df88f43fe5da1b2f86ca77b956b11480970fbb2e/pkg/sql/sem/tree/expr.go#L1124)):*
> ```Go
> 
> // BinaryOperatorSymbol is a symbol for a binary operator.
> type BinaryOperatorSymbol int
> ```

[nit] maybe make this int16 or int32 so we still use a single word for BinaryOperator
___
*[pkg/sql/sem/tree/pretty.go, line 434 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66872#-MdIYm3g2kgkX7-5T_KU:-MdIYm3g2kgkX7-5T_KV:b8wkf9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/df88f43fe5da1b2f86ca77b956b11480970fbb2e/pkg/sql/sem/tree/pretty.go#L434)):*
> ```Go
> }
> 
> func (node *BinaryExpr) doc(p *PrettyCfg) pretty.Doc {
> ```

This code should be kept in sync with the Format code.. if that one prints out `OPERATOR()` so should this. We are missing some testcases for pretty-printing (see sem/tree/testdata/pretty)

**Review by RaduBerinde — COMMENTED** [review]
It feels from your description that we could come up with a logic test that would show invalid output without this change?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66872#-:-MdIZcULA-I6l2BDbR1e:b-gjh3jq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan and @rafiss)

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66872)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rafiss)

___
*[pkg/sql/parser/sql.y, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66872#-MdIYPdP3XdePXd5quHt:-MdK8qjGAFK88HVVF1MY:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/df88f43fe5da1b2f86ca77b956b11480970fbb2e/pkg/sql/parser/sql.y#L80)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] why separate an internal function when we can just add the new code to the BinaryOperator case?
</blockquote></details>

fixed
___
*[pkg/sql/sem/tree/pretty.go, line 434 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66872#-MdIYm3g2kgkX7-5T_KU:-MdK9k3i1To4a0brGA86:boxeyo1) ([raw file](https://github.com/cockroachdb/cockroach/blob/df88f43fe5da1b2f86ca77b956b11480970fbb2e/pkg/sql/sem/tree/pretty.go#L434)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This code should be kept in sync with the Format code.. if that one prints out `OPERATOR()` so should this. We are missing some testcases for pretty-printing (see sem/tree/testdata/pretty)
</blockquote></details>

it should as it uses Operator.String(), tests added

**Comment by otan** [comment]
bors r=raduberinde

**Comment by otan** [comment]
bors r=raduberinde

**Pull request merged**
