### PR TITLE
fixes related to poison_after_push failures

### PR DESCRIPTION
**Pull request by RaduBerinde**
See the comment messages.

@tschottdorf (for the kv fix)
@petermattis (for the logic test changes)

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5323)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 1 of 4 files at r3.
Review status: 4 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[client/txn.go, line 174 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323#-KD0VR-LoaKY8BRxeBT5:-KD0VR-LoaKY8BRxeBT6:258228363) ([raw file](https://github.com/cockroachdb/cockroach/blob/9008eae0b26290b09d03757fb9c375d03b8baa68/client/txn.go#L174)):*
what's this change about?

---

*[kv/txn_coord_sender_test.go, line 960 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323#-KD0UqUqY4WApVFRJXPw:-KD0UqUqY4WApVFRJXPx:938447192) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d9f8cfa2fdd94186cdef8770e8a90020ea33aca/kv/txn_coord_sender_test.go#L960)):*
don't you want to just `t.Fatal` right here?

---

*[kv/txn_coord_sender_test.go, line 964 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323#-KD0UsKLO62MR17Undjo:-KD0UsKLO62MR17Undjp:-469765787) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d9f8cfa2fdd94186cdef8770e8a90020ea33aca/kv/txn_coord_sender_test.go#L964)):*
ditto

---

*[kv/txn_coord_sender_test.go, line 971 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323#-KD0UxBq0tzf5tguYLal:-KD0UxBq0tzf5tguYLam:1119185901) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d9f8cfa2fdd94186cdef8770e8a90020ea33aca/kv/txn_coord_sender_test.go#L971)):*
you can assert on the error right here, i don't think there's any reason to bubble stuff up

---

*[sql/logic_test.go, line 491 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323#-KD0Virzk7ijocdgVqN4:-KD0Virzk7ijocdgVqN5:724571370) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3c25c9e67a57f7868cf1ce655606e28b87ff8c4/sql/logic_test.go#L491)):*
I think this is getting to be too complicated for logic test. As far as I can tell, you just want two transactions with hardcoded priorities in a test - seems like we could use a plain Go test for this.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323)*

**Comment by tschottdorf** [comment]
Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[kv/txn_coord_sender.go, line 344 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323#-KD0Ylz5MdVHASFRxfuJ:-KD0Ylz5MdVHASFRxfuK:-487069179) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d9f8cfa2fdd94186cdef8770e8a90020ea33aca/kv/txn_coord_sender.go#L344)):*
s/is gone/timed out/

---

*[sql/logic_test.go, line 491 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323#-KD0Virzk7ijocdgVqN4:-KD0ZL4W8U-DuLZYW2o1:1987073581) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3c25c9e67a57f7868cf1ce655606e28b87ff8c4/sql/logic_test.go#L491)):*
well, this issue affects more than a few tests (basically all interleaved-txn-demonstrations) but I also think this is a little more structure than required - just `fix-txn-priority` which hard-codes LOW NORMAL and HIGH to pinned values should do. Plus, I really don't want more global mocks in the code (@andrei did the necessary work to get rid of them) - use plumbing similar to `TestingCommandFilter`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323)*

**Comment by tschottdorf** [comment]
LGTM on the kv stuff.

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[client/txn.go, line 174 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323#-KD0VR-LoaKY8BRxeBT5:-KD0_eccxugyhnn-Jcaa:-1483770288) ([raw file](https://github.com/cockroachdb/cockroach/blob/9008eae0b26290b09d03757fb9c375d03b8baa68/client/txn.go#L174)):*
I don't understand the old code, but what it did was not enough. We need to set it in the txn if it is to be passed through (e.g. to BatchRequest).

---

*[kv/txn_coord_sender_test.go, line 960 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323#-KD0UqUqY4WApVFRJXPw:-KD0a1oeJgP8zhSnQNoJ:-1442748497) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d9f8cfa2fdd94186cdef8770e8a90020ea33aca/kv/txn_coord_sender_test.go#L960)):*
I was thinking it might not be cool to call Fatal from this function which might run somewhere else (the surrounding tests I looked at don't)

---

*[sql/logic_test.go, line 491 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323#-KD0Virzk7ijocdgVqN4:-KD0bH6F6YOUVqCbwmwm:303515616) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3c25c9e67a57f7868cf1ce655606e28b87ff8c4/sql/logic_test.go#L491)):*
I went by Peter's suggestion in the PR. I'll wait for him to chip in before I start changing it. I'll take a look at how TestingCommandFilter is plumbed, I would like to avoid the global hacks as well

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[client/txn.go, line 174 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323#-KD0VR-LoaKY8BRxeBT5:-KD0euuu-X_IvnbOoT-2:28468434) ([raw file](https://github.com/cockroachdb/cockroach/blob/9008eae0b26290b09d03757fb9c375d03b8baa68/client/txn.go#L174)):*
The previous code was actually kind of weird. There are two places that have a `UserPriority`: The `*DB` and the `*Txn`. `*DB` is the more long-lived object - it creates Txns which run and then fade. But the old code was actually messing with the priority of `*DB` which means that it wouldn't actually (afaict) affect the current transaction. Instead it affected the UserPriority for future operations on `*DB` - in any case, this seems to do what we actually want.

---

*[kv/txn_coord_sender_test.go, line 960 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323#-KD0UqUqY4WApVFRJXPw:-KD0eBOc7YVqMcQl0yx2:126697486) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d9f8cfa2fdd94186cdef8770e8a90020ea33aca/kv/txn_coord_sender_test.go#L960)):*
You can `t.Fatal` there. The only reason to not do it is when you're in a different goroutine (just because it doesn't work the way it should). But that's not the case here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[sql/logic_test.go, line 491 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323#-KD0Virzk7ijocdgVqN4:-KD0tq2K9OU6mvFq-x7i:-1144783225) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3c25c9e67a57f7868cf1ce655606e28b87ff8c4/sql/logic_test.go#L491)):*
Another option to a global is to add methods into `server.TestServer` to retrieve the `sql.Executor` and allow setting the priorities there. That seems awkward enough to make the globals preferable. 

If we don't do something internal like `SetDeterministicPriorities`, the alternative is exposing deterministic priorities through SQL. I'm hesitant to do that as some user is surely to stumble across it.

---

*[sql/txn.go, line 34 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323#-KD0tW1Xc-r9veB7IP8j:-KD0tW1YyHOI2RK9JxVC:777078430) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3c25c9e67a57f7868cf1ce655606e28b87ff8c4/sql/txn.go#L34)):*
Let's renaming this `TestingSetDeterministicPriority`. Can this be moved to `txn_test.go` (the method, not `deterministicPriorities`)? I'm not sure if that will work given that `logic_test.go` is in a separate package.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[kv/txn_coord_sender.go, line 344 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323#-KD0Ylz5MdVHASFRxfuJ:-KD3gBTStVnxKOkbGGkR:1232424134) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d9f8cfa2fdd94186cdef8770e8a90020ea33aca/kv/txn_coord_sender.go#L344)):*
A question here - is this condition always due to a time out, or can it happen on txns that were aborted for other reasons?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323)*

**Comment by RaduBerinde** [comment]
Review status: 1 of 11 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[sql/logic_test.go, line 491 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323#-KD0Virzk7ijocdgVqN4:-KD3lyAgh7MNnnaCi2Bs:-326332942) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3c25c9e67a57f7868cf1ce655606e28b87ff8c4/sql/logic_test.go#L491)):*
I changed the knob to a single flag (we now have a `fix-txn-priorities` command) and I put it in the `ExecutorTestingMocker` which was plumbed for this purpose. BTW no idea why it's called "Mocker", should probably be "TestingKnobs" or "TestingControls".

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323)*

**Comment by tamird** [comment]
Reviewed 3 of 4 files at r3, 6 of 6 files at r4, 1 of 1 files at r5, 8 of 8 files at r6.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[client/txn.go, line 174 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323#-KD0VR-LoaKY8BRxeBT5:-KD3rkGxx75DGcz89CWq:782900691) ([raw file](https://github.com/cockroachdb/cockroach/blob/9008eae0b26290b09d03757fb9c375d03b8baa68/client/txn.go#L174)):*
OK, cool. Can you add a unit test for this while you're here?

---

*[kv/txn_coord_sender_test.go, line 958 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323#-KD3rw1vl4RP9uS4DNUJ:-KD3rw1vl4RP9uS4DNUK:2038485167) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2e8693db736c096af6b1fc26f8ba31cf9bd9433/kv/txn_coord_sender_test.go#L958)):*
unreachable

---

*[kv/txn_coord_sender_test.go, line 963 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323#-KD3rx3sMuSF6WbB3xRo:-KD3rx3sMuSF6WbB3xRp:2038485167) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2e8693db736c096af6b1fc26f8ba31cf9bd9433/kv/txn_coord_sender_test.go#L963)):*
unreachable

---

*[sql/logic_test.go, line 498 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323#-KD3ssCW-McvAaIIjXjI:-KD3ssCXYuyTAdCvZspq:-1874866006) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8749b4e92e3d58d925e28fd01d24bf359e82ac7/sql/logic_test.go#L498)):*
probably want `fields[1:]` here

---

*[sql/logic_test.go, line 500 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323#-KD3sulkv_W3xMiHMwhc:-KD3sulkv_W3xMiHMwhd:585758484) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8749b4e92e3d58d925e28fd01d24bf359e82ac7/sql/logic_test.go#L500)):*
nit: fmt.Println

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[sql/logic_test.go, line 491 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323#-KD0Virzk7ijocdgVqN4:-KD3yiAePchlafmTOcuS:1463464617) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3c25c9e67a57f7868cf1ce655606e28b87ff8c4/sql/logic_test.go#L491)):*
I agree, feel free to rename.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[client/txn.go, line 174 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323#-KD0VR-LoaKY8BRxeBT5:-KD3ypAnPJ_xHxgh7unn:-1945977943) ([raw file](https://github.com/cockroachdb/cockroach/blob/9008eae0b26290b09d03757fb9c375d03b8baa68/client/txn.go#L174)):*
What would the unit test do exactly? There are a few kv unittests depending on InternalSetPriority btw.

---

*[sql/logic_test.go, line 491 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323#-KD0Virzk7ijocdgVqN4:-KD3zcd1VvifTuyuJsX0:454545018) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3c25c9e67a57f7868cf1ce655606e28b87ff8c4/sql/logic_test.go#L491)):*
Cool, I will do it in a separate PR

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[client/txn.go, line 174 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323#-KD0VR-LoaKY8BRxeBT5:-KD40X11MDn6BGY1Nrwl:-2016004305) ([raw file](https://github.com/cockroachdb/cockroach/blob/9008eae0b26290b09d03757fb9c375d03b8baa68/client/txn.go#L174)):*
Literally confirm that `txn.UserPriority` has changed.

> There are a few kv unittests depending on InternalSetPriority btw.

Not sure I understand what you're trying to say. Obviously those tests didn't catch this mistake.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[client/txn.go, line 174 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323#-KD0VR-LoaKY8BRxeBT5:-KD41OO23cOBnuj3N_we:1592229818) ([raw file](https://github.com/cockroachdb/cockroach/blob/9008eae0b26290b09d03757fb9c375d03b8baa68/client/txn.go#L174)):*
Ah. I thought it was about verifying that this change is not breaking some existing functionality. I will add it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323)*

**Comment by RaduBerinde** [comment]
Review status: 9 of 12 files reviewed at latest revision, 8 unresolved discussions.

---

*[client/txn.go, line 174 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323#-KD0VR-LoaKY8BRxeBT5:-KD4AxUQpPJ7oNn0TqLM:-1322164940) ([raw file](https://github.com/cockroachdb/cockroach/blob/9008eae0b26290b09d03757fb9c375d03b8baa68/client/txn.go#L174)):*
Added a test that verifies that the user priority we set makes it into the BatchRequest (which was why the change to InternalSetPriority was necessary in the first place). This also tests the other minor fix I had to make in Send to pass the priority even if it's negative. TFTR!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 8 files at r6, 3 of 3 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5323#-:-KD4DJUQ1m2giwfnP_uh:1417088721)*

**Pull request merged**
