### PR TITLE
pkg/util/tracing: don't tag child spans when trimming spans recursively

### LINKED ISSUE #101559: pkg/upgrade/upgrademanager/upgrademanager_test: TestAlreadyRunningJobsAreHandledProperly failed
pkg/upgrade/upgrademanager/upgrademanager_test.TestAlreadyRunningJobsAreHandledProperly [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9607202?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9607202?buildTab=artifacts#/) on master @ [dcd920e4bb4d3c55271205d35dffde18da71ecc8](https://github.com/cockroachdb/cockroach/commits/dcd920e4bb4d3c55271205d35dffde18da71ecc8):

```
      GOROOT/src/database/sql/sql.go:1633 +0xfc
  pkg/upgrade/upgrademanager/upgrademanager_test_test.TestAlreadyRunningJobsAreHandledProperly()
      pkg/upgrade/upgrademanager/upgrademanager_test_test/pkg/upgrade/upgrademanager/manager_external_test.go:173 +0x1152
  github.com/cockroachdb/cockroach/pkg/server.(*TestServer).Start()
      github.com/cockroachdb/cockroach/pkg/server/testserver.go:619 +0x8f
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).startServer()
      github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:594 +0xd4
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).Start()
      github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:390 +0x8da
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.StartTestCluster()
      github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:234 +0xa8
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.NewTestCluster()
      github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:330 +0xe10
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.StartTestCluster()
      github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:233 +0x8b
  pkg/upgrade/upgrademanager/upgrademanager_test_test.TestAlreadyRunningJobsAreHandledProperly()
      pkg/upgrade/upgrademanager/upgrademanager_test_test/pkg/upgrade/upgrademanager/manager_external_test.go:71 +0x7d5
  testing.tRunner()
      GOROOT/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      GOROOT/src/testing/testing.go:1493 +0x47

Goroutine 63786 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).runWithEx()
      github.com/cockroachdb/cockroach/pkg/sql/internal.go:173 +0x344
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).execInternal()
      github.com/cockroachdb/cockroach/pkg/sql/internal.go:919 +0x13f6
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).ExecEx()
      github.com/cockroachdb/cockroach/pkg/sql/internal.go:672 +0x258
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).Exec()
      github.com/cockroachdb/cockroach/pkg/sql/internal.go:653 +0x186
  pkg/upgrade/upgrademanager/upgrademanager_test_test.TestAlreadyRunningJobsAreHandledProperly.func5()
      pkg/upgrade/upgrademanager/upgrademanager_test_test/pkg/upgrade/upgrademanager/manager_external_test.go:193 +0x1be

Goroutine 44 (running) created at:
  testing.(*T).Run()
      GOROOT/src/testing/testing.go:1493 +0x75d
  testing.runTests.func1()
      GOROOT/src/testing/testing.go:1846 +0x99
  testing.tRunner()
      GOROOT/src/testing/testing.go:1446 +0x216
  testing.runTests()
      GOROOT/src/testing/testing.go:1844 +0x7ec
  testing.(*M).Run()
      GOROOT/src/testing/testing.go:1726 +0xa84
  pkg/upgrade/upgrademanager/upgrademanager_test_test.TestMain()
      pkg/upgrade/upgrademanager/upgrademanager_test_test/pkg/upgrade/upgrademanager/main_test.go:28 +0x186
  main.main()
      main/bazel-out/k8-fastbuild/bin/pkg/upgrade/upgrademanager/upgrademanager_test_/testmain.go:117 +0x748
==================
```
<p>Parameters: <code>TAGS=bazel,gss,race</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-schema
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestAlreadyRunningJobsAreHandledProperly.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-27012

### PR DESCRIPTION
**Pull request by abarganier**
Fixes: https://github.com/cockroachdb/cockroach/issues/101559

To avoid racy tagging of child spans when trimming children of a trace to adhere to the max recorded spans per trace, this patch updates the recursive trim span operation to only tag the recursive root span with `_dropped_indirect_children` and `_dropped_children` tags.

It also updates the trimSpan tests to verify these tags are not added to child spans.

Release note: none

Reviewer hint: Explanation of the race condition here: https://github.com/cockroachdb/cockroach/issues/101559#issuecomment-1522454349

### CODE REVIEW

**Comment by benbardin** [comment]
LGTM, but please wait also for David. Thank you!

**Comment by abarganier** [comment]
@benbardin I wanted to get your take on this as you built the improved tracez UI.

This change prevents spans other than the root span from being tagged with `_dropped_indirect_children` or `_dropped_children` to avoid a race condition in the tracing library when collecting unfinished spans. 

I noticed we look for these tags when processing spans in the tracingui package: https://github.com/cockroachdb/cockroach/blob/fced789daf50c863c58da5eb421c107e1ce022b9/pkg/util/tracing/tracingui/span_registry_ui.go#L110-L111

I just wanted to get your opinion on the UX impact of doing this. Do you think it would significantly hinder the experience? Thanks for taking a look!

**Comment by benbardin** [comment]
No, I think it would be fine, though I'd be interested to see if @adityamaru has an opinion. It's also more important to fix a race condition anyway. Thanks!

**Review by dhartunian — APPROVED** [review]
:lgtm: to check my understanding here: since we hold a lock on the `crdbspan` that we're getting the recording of, the `EnsureTagGroup` call won't race even if someone else is getting a recording of the same `crdbspan` or a child of that span.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102370#-:-NTz7YRuEykLKYKPQHoG:b6aiw6b)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier, @adityamaru, and @benbardin)

___
*[`pkg/util/tracing/crdbspan.go` line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102370#-NTz6mEj0jcxF4EMxvdZ:-NTz6mEj0jcxF4EMxvd_:bppcqas) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0cf6115bb551aa4ac856b51fc5a01cb272c4fe9/pkg/util/tracing/crdbspan.go#L342)):*
> ```Go
> 			// To avoid multiple goroutines racing to add tags to child spans with unprotected tags structures,
> 			// we only indicate on the recursive root Trace's Root member that children have been dropped.
> 			t.Root.EnsureTagGroup(tracingpb.AnonymousTagGroupName).AddTag("_dropped_children", "")
> ```

is there a need for a TODO or a ticket filed for a further improvement here? do we want to eventually allow arbitrary tag setting here? I'm personally not sure. It does seem like we shouldn't be manipulating tags within the entire tree while we collect a `verboseRecording`.

**Review by abarganier — COMMENTED** [review]
> to check my understanding here: since we hold a lock on the crdbspan that we're getting the recording of, the EnsureTagGroup call won't race even if someone else is getting a recording of the same crdbspan or a child of that span.

Right. When we trim spans and add these tags, we're doing so to the tags held by `Trace.Root` which represents the root `crdbSpan`. As soon as we recurse into the children, we stop adding the tags. This is done in the critical section of the `crdbSpan.mu`, so it's protected, although admittedly it's very difficult to reason about since it's a separate object entirely. 

Where things get unsafe is with the **children** of that `crdbSpan`, which are only [partially copied](https://github.com/cockroachdb/cockroach/blob/b0cf6115bb551aa4ac856b51fc5a01cb272c4fe9/pkg/util/tracing/crdbspan.go#L535-L537) into the `Children` of the `Trace` object being operated on. The child logs/tags are not deep copied, so *those* are the structures that are not thread safe despite holding the root `crdbSpan` mutex. By updating the `trimSpanRecursive` to only add tags to that root `Trace.Root` (representing the root `crdbSpan` we're holding the mutex on), we avoid writing to these tag structures on the children, which aren't thread safe.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102370#-:-NTzClnBCXc3QTcCBIOM:bh8ke2o)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru and @benbardin)

**Review by abarganier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102370)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @benbardin, and @dhartunian)

___
*[`pkg/util/tracing/crdbspan.go` line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102370#-NTz6mEj0jcxF4EMxvdZ:-NTzMPy86p3OW5tBm3pa:byu8nnj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0cf6115bb551aa4ac856b51fc5a01cb272c4fe9/pkg/util/tracing/crdbspan.go#L342)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

is there a need for a TODO or a ticket filed for a further improvement here? do we want to eventually allow arbitrary tag setting here? I'm personally not sure. It does seem like we shouldn't be manipulating tags within the entire tree while we collect a `verboseRecording`.
</blockquote></details>

I'm still unsure myself. I feel like there's a broader TODO here that involves making things *more* thread safe, with clear-cut mutexes available to guard tags/logs/etc structures. Unfortunately, with the protobufs mixed in with the vanilla Go structs (e.g. `Trace.Root` being a `tracingpb.RecordedSpan`), I have yet to think of how we might achieve this. 

Maybe the concept of viewing in-flight/unfinished traces is new, so having multiple threads fetch a recording from the same span wasn't something we had to worry about when the library was first created. Newer features like the `tracez` page seem to have now introduced a need for deeper synchronization. I could be wrong - I still have a lot to learn about this library, but concurrency + recursion without obvious mutexes has definitely been painful to reason about. I'd like to make that better, but I don't have any concrete ideas.

**Comment by abarganier** [comment]
bors r=dhartunian

**Pull request merged**
