### PR TITLE
opt: project away unneeded groupby input columns

### PR DESCRIPTION
**Pull request by RaduBerinde**
The optimizer does not introduce `ProjectOp`s to remove unneeded
columns in all possible places (because they get in the way of various
transformations), and we are missing a mechanism for accounting for
this (e.g. in the physical properties) and adding projections at
execbuild time.

This is not a trivial problem to solve; this change addresses this in
just the specific case of GroupBy. Here `COUNT(*)` is a particularly
important case where we can project away all input columns. This
addresses a regression Andy noticed on this query:
`SELECT count(*) FROM lineitem@l_sk JOIN supplier@s_sk ON l_suppkey = s_suppkey`

Release note: None

### CODE REVIEW

**Review by rytaft — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30104)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 632 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30104#-LMDGtmv8guAzh6oe2jv:-LMDGtmw1qzOvH6zDA61:bxck8ey) ([raw file](https://github.com/cockroachdb/cockroach/blob/f494a6fc152d732a09595704b9eef56790b0f4e3/pkg/sql/opt/exec/execbuilder/relational_builder.go#L632)):*
> ```Go
> 	}
> 
> 	// See if the input columns is producing any columns that are not useful.
> ```

[nit] input columns -> input
___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 634 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30104#-LMDHAtB5LfUngxzlYPE:-LMDHAtB5LfUngxzlYPF:b-57nfr2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f494a6fc152d732a09595704b9eef56790b0f4e3/pkg/sql/opt/exec/execbuilder/relational_builder.go#L634)):*
> ```Go
> 	// See if the input columns is producing any columns that are not useful.
> 	projNeeded := false
> 	input.outputCols.ForEach(func(colID, ordinal int) {
> ```

why can't you just check `if ev.Child(0).Logical().Relational.OutputCols.SubsetOf(neededCols)`?
___
*[pkg/sql/opt/memo/extract.go, line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30104#-LMDKN4p7HGIoVNnJXWZ:-LMDKN4p7HGIoVNnJXW_:b-n99zzd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f494a6fc152d732a09595704b9eef56790b0f4e3/pkg/sql/opt/memo/extract.go#L87)):*
> ```Go
> 	var res opt.ColSet
> 	for i, n := 0, ev.ChildCount(); i < n; i++ {
> 		arg := ev.Child(0)
> ```

you're not using `i` here or below.

also, seems like this function could call `ExtractAggSingleInputColumn` since they are almost identical...

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30104)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 632 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30104#-LMDGtmv8guAzh6oe2jv:-LMDNGKxE6WyX55zsgf5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f494a6fc152d732a09595704b9eef56790b0f4e3/pkg/sql/opt/exec/execbuilder/relational_builder.go#L632)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] input columns -> input
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 634 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30104#-LMDHAtB5LfUngxzlYPE:-LMDNGvnDvQQSJdTY3-y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f494a6fc152d732a09595704b9eef56790b0f4e3/pkg/sql/opt/exec/execbuilder/relational_builder.go#L634)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

why can't you just check `if ev.Child(0).Logical().Relational.OutputCols.SubsetOf(neededCols)`?
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/extract.go, line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30104#-LMDKN4p7HGIoVNnJXWZ:-LMDNPpE8mlJY1Gp9xLc:b-jhes1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/f494a6fc152d732a09595704b9eef56790b0f4e3/pkg/sql/opt/memo/extract.go#L87)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

you're not using `i` here or below.

also, seems like this function could call `ExtractAggSingleInputColumn` since they are almost identical...
</blockquote></details>

Fixed and pulled out common code.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30104#-:-LMDQSLN602XkJVliddN:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
