### PR TITLE
insights: record more txn insights

### LINKED ISSUE #93076: insights: record missing txn insights
Record following into insights registry at txn-level:
- txn start time
- txn end time
- total contention time
- last retry reason
- retry_count
- rows_written
- rows_read

Jira issue: CRDB-22145

### PR DESCRIPTION
**Pull request by xinhaoz**
Closes https://github.com/cockroachdb/cockroach/issues/93076

This commit adds the following fields at the txn level when recording
insights in the sql insights system:
- contention: total txn contention time
- start_time: txn start time
- end_time: txn end time
- auto_retry_reason: last reason for auto txn retry
- retry_count
- rows_written
- rows_read

In addition, the following fields have been moved from recording at
the stmt level to recording at the txn level for insights:
- user
- application_name

Release note: None

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93079)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`pkg/sql/executor_statement_metrics.go` line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93079#-NIZ8kuHErdEQU5HOTAf:-NIZ8kuICHsmHb9Dx-xe:bbd3vkh) ([raw file](https://github.com/cockroachdb/cockroach/blob/591995a766f661754c7dec0d54f1995954e9f5e6/pkg/sql/executor_statement_metrics.go#L211)):*
> ```Go
> 		EndTime:              phaseTimes.GetSessionPhaseTime(sessionphase.PlannerStartExecStmt).Add(svcLatRaw),
> 		FullScan:             fullScan,
> 		SessionData:          planner.SessionData(),
> ```

I don't see the commit mentions the removal of the sessions data, is this what you mean by user/app/database?

**Comment by xinhaoz** [comment]
*[`pkg/sql/executor_statement_metrics.go` line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93079#-NIZ8kuHErdEQU5HOTAf:-NIc2-l5ALcqgC68d-yu:bnd8bdj) ([raw file](https://github.com/cockroachdb/cockroach/blob/591995a766f661754c7dec0d54f1995954e9f5e6/pkg/sql/executor_statement_metrics.go#L211)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I don't see the commit mentions the removal of the sessions data, is this what you mean by user/app/database? 
</blockquote></details>

Yes that's correct, that info was coming from the presence of the session data in the statements record.

**Review by matthewtodd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93079)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @xinhaoz)

___
*[`pkg/sql/crdb_internal.go` line 6697 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93079#-NIc7fkP4M8LE6UFF8qP:-NIc7fkP4M8LE6UFF8qQ:b-lxkg9q) ([raw file](https://github.com/cockroachdb/cockroach/blob/7129c3b05554c28057c073b2f65e6c0e09f2f275/pkg/sql/crdb_internal.go#L6697)):*
> ```Go
> 			tree.NewDString(insight.Transaction.User),
> 			tree.NewDString(insight.Transaction.ApplicationName),
> 			tree.NewDString(insight.Transaction.Database),
> ```

Great! Do you want to add the new values to the table, too, or is that for another commit?

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93079#-:-NIcbZhsBotzl6QFMqwL:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @matthewtodd)

**Review by j82w — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93079)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag, @matthewtodd, and @xinhaoz)

___
*[`pkg/sql/crdb_internal.go` line 6697 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93079#-NIcu82q6VgrbqOGDnUy:-NIcu82q6VgrbqOGDnUz:b-ki09hs) ([raw file](https://github.com/cockroachdb/cockroach/blob/7129c3b05554c28057c073b2f65e6c0e09f2f275/pkg/sql/crdb_internal.go#L6697)):*
> ```Go
> 			tree.NewDString(insight.Transaction.User),
> 			tree.NewDString(insight.Transaction.ApplicationName),
> 			tree.NewDString(insight.Transaction.Database),
> ```

Is it possible for a single transaction to span multiple dbs?

**Comment by xinhaoz** [comment]
*[`pkg/sql/crdb_internal.go` line 6697 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93079#-NIcu82q6VgrbqOGDnUy:-NId3OHi1vV1MyPNI-nI:b4p1h4j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7129c3b05554c28057c073b2f65e6c0e09f2f275/pkg/sql/crdb_internal.go#L6697)):*
<details><summary><i>Previously, j82w wrote…</i></summary><blockquote>

Is it possible for a single transaction to span multiple dbs?
</blockquote></details>

Hm I believe so, so this is probably more of a stmt-level stat. I'll move it back

**Review by matthewtodd — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93079#-:-NIdEW6IEz_8fePKzrXa:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @j82w and @maryliag)

**Pull request merged**
