### PR TITLE
raft: misc becomeFollower cleanups

### PR DESCRIPTION
**Pull request by arulajmani**
See individual commits.

### CODE REVIEW

**Comment by arulajmani** [comment]
@nvanbenschoten the first commit isn't strictly required, but I decided to pull the plug on one of the test files that was basically a mirror of another pre-vote version. I would've otherwise had to duplicate the change in the second commit where I change `testingStepDownLeader`.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137313#-:-ODrsx4cEzD4nA5S0MQI:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/raft/status.go` line 104 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/137313#-ODrsr9D8xy7NDVdDFRA:-ODrsr9D8xy7NDVdDFRB:b-czen5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/b88c57145abce498815742e3ee2822c3b45a9df7/pkg/raft/status.go#L104)):*
> ```Go
> 	s.SoftState = r.softState()
> 	s.Applied = r.raftLog.applied
> 	assertTrue((s.RaftState == pb.StateLeader && s.Lead == r.id) ||
> ```

nit: `(s.RaftState == pb.StateLeader) == (s.Lead == r.id)`

**Review by arulajmani — COMMENTED** [review]
I'll let CI run on this one to make sure nothing breaks before merging. TFTR. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137313#-:-ODrvV062rOGffcj7LVP:bcxefl7)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[`pkg/raft/status.go` line 104 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/137313#-ODrsr9D8xy7NDVdDFRA:-ODrvT8--tqaq6nYJ-K4:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b88c57145abce498815742e3ee2822c3b45a9df7/pkg/raft/status.go#L104)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: `(s.RaftState == pb.StateLeader) == (s.Lead == r.id)`
</blockquote></details>

Done.

**Comment by arulajmani** [comment]
CI is clean.

bors r=nvanbenschoten

**Pull request merged**
