### PR TITLE
kvcoord: fix DistSender circuit breaker `tripped` metrics leak

### LINKED ISSUE #121030: kvcoord: fix DistSender circuit breaker tripped metrics leak
Currently, if a tripped circuit breaker is GCed, it will continue to be considered tripped in the DistSender metrics until the node restarts. Fixing this requires synchronization with the probe, since it is normally responsible for increasing/decreasing the metric as the circuit breaker trips/untrips. The probe likely isn't running when the circuit breaker is GCed, but it may be if a probe is concurrently launching while GC is running, or the threshold/interval has been configured higher than the GC threshold. If there is a race, it can lead to persistent gauge leaks.

Jira issue: CRDB-37035

### PR DESCRIPTION
**Pull request by erikgrinaker**
If a tripped circuit breaker is GCed, the `tripped` metric will consider it tripped forever. This patch untrips the breaker during GC, taking care to properly shut down and synchronize with any concurrent probes to avoid metrics leaks.

Resolves https://github.com/cockroachdb/cockroach/issues/121030.
Epic: none
Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm: though it would be nice to have a test that exercises this logic.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121142#-:-NtwS9W7En_JrcMgpTAw:b-yjd5s)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist and @erikgrinaker)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go` line 361 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121142#-NtwRfEr5Ugzp1cWVuy2:-NtwRfEr5Ugzp1cWVuy3:bphaz6z) ([raw file](https://github.com/cockroachdb/cockroach/blob/c91274a328697273c0be097cc1e5af45261c6488/pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go#L361)):*
> ```Go
> 	// closedC is closed when the circuit breaker has been GCed. This will shut
> 	// down a running probe, and prevent new probes from launching.
> 	closedC chan struct{}
> ```

Should we be allocating this channel in `newReplicaCircuitBreaker`?
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go` line 938 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121142#-NtwS74q04bpibBvYSnH:-NtwS74q04bpibBvYSnI:b-866ps4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c91274a328697273c0be097cc1e5af45261c6488/pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go#L938)):*
> since it would also use an untripped breaker if it arrived after GC

:thumbsup: 
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go` line 941 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121142#-NtwS_zs1oGItEQXjy6I:-NtwS_zs1oGItEQXjy6J:bef75pv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c91274a328697273c0be097cc1e5af45261c6488/pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go#L941)):*
> ```Go
> 	if r.isClosed() {
> 		if r.isTripped() {
> 			r.breaker.Reset()
> ```

It's ok for an EventHandler function to call back into Reset, right? This won't cause any deadlocks?

**Review by erikgrinaker — COMMENTED** [review]
For sure, all of this needs testing. I'm going to add some tomorrow, but will likely need a bit more time to add comprehensive testing.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121142#-:-NtwVAGG9UBKGePvbB69:bdw7jyp)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andrewbaptist and @nvanbenschoten)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go` line 361 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121142#-NtwRfEr5Ugzp1cWVuy2:-NtwVKQ6BM76zgL_gefr:bdod1l6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c91274a328697273c0be097cc1e5af45261c6488/pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go#L361)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we be allocating this channel in `newReplicaCircuitBreaker`?
</blockquote></details>

Yes, forgot to add that.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go` line 941 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121142#-NtwS_zs1oGItEQXjy6I:-NtwVPFS5YdPUxDHixYH:b-s3d50q) ([raw file](https://github.com/cockroachdb/cockroach/blob/c91274a328697273c0be097cc1e5af45261c6488/pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go#L941)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It's ok for an EventHandler function to call back into Reset, right? This won't cause any deadlocks?
</blockquote></details>

Yes, afaict. `OnProbeDone` is called without holding the circuit breaker mutex, before the probe is recorded as shut down. This shouldn't be any different from the probe itself calling `report(nil)`.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121142#-:-NtwzPHQESu07d4tgdsS:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist)

**Comment by erikgrinaker** [comment]
I've seen a couple of CI failures in `TestTenantLogicCCL_crdb_internal_tenant`, unclear if it's related. Doing another run.

**Comment by erikgrinaker** [comment]
CI is passing now, going for it and catching up in the nightlies.

bors r+

**Pull request merged**
