### PR TITLE
auth: add autoLogin ability to OIDC configuration

### PR DESCRIPTION
**Pull request by dhartunian**
For customers who enable OIDC-based login to the Admin UI,
it's preferable to skip the username/password login prompt
entirely and provide a seamless login experience to CRDB users.

This change introduces a new boolean cluster setting called
`server.oidc_authentication.autologin`
When this flag is `true`, upon loading the login page in the
Admin UI, the browser will automatically initiate the OIDC
authentication process by redirecting to `/oidc/v1/login`
instead of waiting for the user to login manually or click the
OIDC login button.

This setting causes no server-side change in the behavior of
OIDC authentication functionality.

Along with the new setting, a few refactors were made:
- OIDC-related components are in `oidc.tsx` for clarity
- `displayPasswordLogin` flag which was added earlier in
  anticipation of this feature has been removed since we
  decided to create a flag to trigger autologin instead of
  worrying about hiding the password fields
- `displayOIDCButton` has been renamed to `oidcLoginEnabled`
  on the client-side to match the server-side flag. Earlier it
  was renamed on the client side since it only controlled the
  visibility of the OIDC button. Now the redirect depends on that
  flag **and** autoLogin to be enabled.

This change is part of #54619

Release note (admin ui change): added new cluster setting
called `server.oidc_authentication.autologin` which enables
automatic redirect to the OIDC login flow instead of showing
password login prompt.

### CODE REVIEW

**Review by taroface — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55552)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @knz, and @taroface)

___
*[docs/generated/settings/settings.html, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55552#-MJbsZDmBGZut8iO_FKa:-MJbsZDmBGZut8iO_FKb:bmuljkj) ([raw file](https://github.com/cockroachdb/cockroach/blob/54359ddf120e534e65adb67dd8ed4c9b122c0b5d/docs/generated/settings/settings.html#L41)):*
> ```HTML
> <tr><td><code>server.eventlog.ttl</code></td><td>duration</td><td><code>2160h0m0s</code></td><td>if nonzero, event log entries older than this duration are deleted every 10m0s. Should not be lowered below 24 hours.</td></tr>
> <tr><td><code>server.host_based_authentication.configuration</code></td><td>string</td><td><code></code></td><td>host-based authentication configuration to use during connection authentication</td></tr>
> <tr><td><code>server.oidc_authentication.autologin</code></td><td>boolean</td><td><code>false</code></td><td>when this setting is enabled logged-out visitors to the Admin UI will be automatically redirected to the OIDC login endpoint (this feature is experimental)</td></tr>
> ```

Suggest: `when this setting is enabled` -> `if true,`

I also wonder if there is a way not to refer to the "Admin UI", since we've recently been having conversations about moving away from this name. Maybe calling it "Console" would suffice? @piyush-singh wdyt
___
*[pkg/ccl/oidcccl/settings.go, line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55552#-MJbwdGO4jIazou9Mw9F:-MJbwdGP-icZ7GVeuvUV:bz2xc68) ([raw file](https://github.com/cockroachdb/cockroach/blob/54359ddf120e534e65adb67dd8ed4c9b122c0b5d/pkg/ccl/oidcccl/settings.go#L174)):*
> ```Go
> 	s := settings.RegisterPublicBoolSetting(
> 		OIDCAutoLoginSettingName,
> 		"when this setting is enabled logged-out visitors to the Admin UI will be "+
> ```

Same comments as on `settings.html`

**Review by knz — COMMENTED** [review]
Is it possible to redirect to the regular login form if the OIDC login fails? As a fallback?

> Reviewed 5 of 8 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55552#-:-MJkYtOiDqGGoY62vhlR:bh97qv7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

**Review by dhartunian — COMMENTED** [review]
> Is it possible to redirect to the regular login form if the OIDC login fails? As a fallback?

@knz I *could* do this but it introduces a few quirks: the two points where we can redirect to the regular login form are handled by the DB Server (the /oidc/v1/auth and /oidc/v1/callback endpoints). If I use them to redirect to the homepage, we would lose the ability to report the HTTP status code to the browser. Not sure if it _really_ matters here since it's user-facing, and not a programmable API that we're supporting. We could replace the HTTP error responses (500, 400, etc.) with a 302 redirect to the login page and put the error in a query param like this: `https://localhost:8080/#/login?error=OIDC%3A+some+random+error+message&oidc_auto_login=false` and show the login UI again with the error string in a box underneath the OIDC button.

What do you think? Maybe we can also throw the status code into a query param and render a nicer error box with more info.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55552#-:-MKvVUrH8D435xIJIpZ_:b17am4c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

**Review by dhartunian — COMMENTED** [review]
@knz just pushed up a WIP commit on top of this change that illustrates one approach to redirecting on errors. Looks like this in the browser:



> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55552#-:-MKvs2zKANqvwfV3jjv2:b-l7uqg9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @knz)

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55552)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @piyush-singh, and @taroface)

___
*[docs/generated/settings/settings.html, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55552#-MJbsZDmBGZut8iO_FKa:-MKvsJJx6CwP5Z2ESLH1:bcjdswp) ([raw file](https://github.com/cockroachdb/cockroach/blob/54359ddf120e534e65adb67dd8ed4c9b122c0b5d/docs/generated/settings/settings.html#L41)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Suggest: `when this setting is enabled` -> `if true,`

I also wonder if there is a way not to refer to the "Admin UI", since we've recently been having conversations about moving away from this name. Maybe calling it "Console" would suffice? @piyush-singh wdyt
</blockquote></details>

done. I'd prefer to make the naming switch in a separate PR if we need to but agree it needs discussion.
___
*[pkg/ccl/oidcccl/settings.go, line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55552#-MJbwdGO4jIazou9Mw9F:-MKvsNhJ6YzKpBTbevC6:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/54359ddf120e534e65adb67dd8ed4c9b122c0b5d/pkg/ccl/oidcccl/settings.go#L174)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Same comments as on `settings.html`
</blockquote></details>

done.

**Comment by knz** [comment]
@aaron-crl @bdarnell can either of you field this review? I am taking time off this week.

**Review by bdarnell — APPROVED** [review]
Looks good to me, but I can't think of other systems I've used that work this way - there's usually still some sort of landing/login page where you have to click a button to go to the OIDC page. Are we sure this is the desired user experience?

I don't think it makes sense to fall back to a user/password prompt on failure. OIDC users will generally not have passwords configured to fall back on. (your "in case of emergency break glass" path to get back in to a misconfigured cluster is a root certificate signed by the appropriate CA, which you can always do from outside a broken cluster even if you have to rotate the CA cert on the filesystem to do it)

> Reviewed 3 of 3 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55552#-:-MLEh7Yh4ssWBZT9uHhQ:bf1y2ep)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @piyush-singh and @taroface)

**Comment by dhartunian** [comment]
@bdarnell agree with you about not redirecting on failure. I will keep it as-is for now until we have more user feedback. I pushed an update removing that commit.

**Pull request merged**
