### PR TITLE
opt: fix node-crashing panics with correlated With exprs

### LINKED ISSUE #87733: sql: CTE causes panic that crashes nodes
A user has reported that a statement with multiple CTEs can cause panics that crash a node. The crash is reproducible on v21.2, v22.1, and a recent build off of `master`. We need to determine:

1. Why does the error crash the node?
2. What is causing the error?

To reproduce:

```
CREATE TABLE a (a INT);
CREATE TABLE b (b INT);
INSERT INTO a VALUES (1);

WITH
t1 AS (SELECT a FROM a),
t2 AS MATERIALIZED (SELECT a, b FROM t1 JOIN b ON true)
SELECT NULL
FROM t1
LEFT JOIN LATERAL (
  WITH t3 AS (SELECT * FROM t2 WHERE t2.a = t1.a)
  SELECT array_agg(CASE WHEN v = '' THEN b END)
  FROM (
    SELECT '' AS v, b FROM t3 ORDER BY b DESC
  )
) ON true;
```

Error message:

```
*
* ERROR: a SQL panic has occurred while executing the following statement:
* WITH t1 AS (SELECT a FROM a), t2 AS MATERIALIZED (SELECT a, b FROM t1 JOIN b ON true) SELECT NULL FROM t1 LEFT JOIN LATERAL (WITH t3 AS (SELECT * FROM t2 WHERE t2.a = t1.a) SELECT array_agg(CASE WHEN v = '' T
HEN b END) FROM (SELECT '' AS v, b FROM t3 ORDER BY b DESC)) ON true
*
*
* ERROR: a panic has occurred!
* no binding for WithID 1
* (1) attached stack trace
*   -- stack trace:
*   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
*   |   github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:761
*   | runtime.gopanic
*   |   GOROOT/src/runtime/panic.go:1038
*   | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
*   |   github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:58
*   | runtime.gopanic
*   |   GOROOT/src/runtime/panic.go:1038
*   | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
*   |   github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:58
*   | runtime.gopanic
*   |   GOROOT/src/runtime/panic.go:1038
*   | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
*   |   github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:58
*   | runtime.gopanic
*   |   GOROOT/src/runtime/panic.go:1038
*   | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
*   |   github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:58
*   | runtime.gopanic
*   |   GOROOT/src/runtime/panic.go:1038
*   | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
*   |   github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:58
*   | runtime.gopanic
*   |   GOROOT/src/runtime/panic.go:1038
*   | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
*   |   github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:58
*   | runtime.gopanic
*   |   GOROOT/src/runtime/panic.go:1038
*   | github.com/cockroachdb/cockroach/pkg/sql/opt.(*Metadata).WithBinding
*   |   github.com/cockroachdb/cockroach/pkg/sql/opt/metadata.go:749
*   | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).colStatWithScan
*   |   github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:2501
*   | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).colStat
*   |   github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:470
*   | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).colStatFromChild
*   |   github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:267
*   | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).colStatFromJoinLeft
*   |   github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:1608
*   | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).colStatJoin
*   |   github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:1447
*   | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).colStat
*   |   github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:438
*   | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).colStatWithScan
*   |   github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:2506
*   | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).colStat
*   |   github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:470
*   | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).colStatFromChild
*   |   github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:267
*   | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).colStatFromInput
*   |   github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:322
*   | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).ensureColStat
*   |   github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:2625
*   | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).updateDistinctCountsFromConstraint
*   |   github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:3454
*   | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).applyConstraintSet
*   |   github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:3291
*   | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).applyFiltersItem
*   |   github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:3080
*   | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).applyFilters
*   |   github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:3004
*   | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).filterRelExpr
*   |   github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:2957
```

Jira issue: CRDB-19505

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: prevent apply-join panics from crashing nodes

Previously, it was possible for the execution of an apply-join to crash
a node due to an uncaught optimizer panic when calling the
`planRightSideFn` closure. This closure is invoked for every input row
to the apply-join. It replaces variables in the expression on the right
side of the join with constants using `Factory.CopyAndReplace`, which
can panic. This panic won't be caught by the panic-catching logic in
`Optimizer.Optimize` because the closure is invoked outside the context
of `Optimizer.Optimize` - it's occurring during execution instead.

This commit copies the panic-catching logic of `Optimizer.Optimize` to
the apply-join's `planRightSideFn` closure to ensure that any panics are
caught.

Release Note (bug fix): A bug has been fixed that could cause nodes to
crash in rare cases when executing apply-joins in query plans.

#### opt: fix transitive references to With exprs in RHS of apply-join

This commit fixes an error that could occur when the RHS of an
apply-join referenced a With expression transitive through another With
expression. The error occurred because the optimizer could not access
the relational properties of the transitively referenced With expression
because the With was not added to the metadata. The commit fixes the
issue by adding all With expressions to the metadata if any With
expressions are referenced.

Fixes #87733

Release note (bug fix): A bug has been fixed that caused errors in rare
cases when executing queries with correlated WITH expressions. This bug
was present since correlated WITH expressions were introduced in
v21.2.0.

### CODE REVIEW

**Review by michae2 — APPROVED** [review]
:lgtm: Very tricky. Nice fix!

> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88396#-:-NCX5a5kD8LZcoPp35bX:b-ylp750)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @msirek)

___
*[`pkg/sql/opt/exec/execbuilder/relational.go` line 1085 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88396#-NCX53EHAPuiWt-9zH6m:-NCX53EHAPuiWt-9zH6n:bm7u8so) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb5eccd742618049b9cf58b4aa48363bcbbd06ce/pkg/sql/opt/exec/execbuilder/relational.go#L1085)):*
> ```Go
> 						memoExpr := b.mem.Metadata().WithBinding(i)
> 						f.Metadata().AddWithBinding(i, memoExpr)
> 					}
> ```

Does this work even if there is an ApplyJoin calling another ApplyJoin? (In other words, even if some of the with expressions originate from outside this `Builder`?) My feeling is yes, since the `Builder` of the outer ApplyJoin should have all With expressions bound, thanks to this.

**Review by msirek — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88396#-:-NCXnYJG870fg2pb1UGo:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88396)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @michae2 and @msirek)

___
*[`pkg/sql/opt/exec/execbuilder/relational.go` line 1085 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88396#-NCX53EHAPuiWt-9zH6m:-NC_et4L3Ac_6AbbQbw_:brrizf5) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb5eccd742618049b9cf58b4aa48363bcbbd06ce/pkg/sql/opt/exec/execbuilder/relational.go#L1085)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Does this work even if there is an ApplyJoin calling another ApplyJoin? (In other words, even if some of the with expressions originate from outside this `Builder`?) My feeling is yes, since the `Builder` of the outer ApplyJoin should have all With expressions bound, thanks to this.
</blockquote></details>

Yes it should work. This fetches with bindings from `b` which is the root builder, not `eb`. So even if there are nested apply-joins, the with bindings will all be populated from the root builder.

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
