### PR TITLE
storage: improve logging during range descriptor iteration

### PR DESCRIPTION
**Pull request by RaduBerinde**
We use `log.Event` during range descriptor iteration which happens while the node starts; traces are borderline useless here because the server is not initialized yet.

We switch to regular logs and we log updates periodically when we process large numbers of keys.

Epic: none
Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
I plan to backport to 23.1 and 22.2.

**Comment by RaduBerinde** [comment]
Friendly ping - I'd like to get this backported in time for 23.1.10.

**Comment by RaduBerinde** [comment]
Hold off on reviewing - I will implement some nice ideas from Sumeer (use time passed for deciding when to show progress, and show iterator stats).

**Comment by RaduBerinde** [comment]
RFAL. Sample output:
```
I230830 19:42:06.989949 82 kv/kvserver/kvstorage/init.go:311 ⋮ [T1,Vsystem,n1,s1] 58  range descriptor iteration done: 1708 keys, 1065 range descriptors (by suffix: map[qlpt:642 rdsc:1065 txn-:1]); scan stats: stepped 2.708k times (4.263k internal); seeked 6 times (5 internal); block-bytes: (total 565 KiB, cached 71 KiB); points: (count 4.265k, key-bytes 112 KiB, value-bytes 1.3 MiB, tombstoned: 0) ranges: (count 0), (contained-points 0, skipped-points 0) evaluated requests: 0 gets, 2 scans, 0 reverse scans separated: (count: 1.561k, bytes: 80 KiB, bytes-fetched: 0 B)
```

**Comment by RaduBerinde** [comment]
*[`pkg/kv/kvserver/kvstorage/testdata/init` line 30 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109682#-Nd6yC8B25mHKpZpIJ6c:-Nd6yC8C149o9ATX1jsr:b-nxspcq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d7265a3609368af9cfb7f27643261d5bdac045/pkg/kv/kvserver/kvstorage/testdata/init#L30)):*
> ```
> r8/80: r8:{c-f} [(n1,s1):80, next=81, gen=0]
> beginning range descriptor iteration
> range descriptor iteration done: 2 keys, 2 range descriptors (by suffix: map[rdsc:2]); scan stats: stepped 2 times (2 internal); seeked 2 times (2 internal); block-bytes: (total 0 B, cached 0 B); points: (count 2, key-bytes 40 B, value-bytes 58 B, tombstoned: 0) ranges: (count 0), (contained-points 0, skipped-points 0) evaluated requests: 0 gets, 1 scans, 0 reverse scans
> ```

I stressed the test and didn't see a failure, but I still wonder if these stats could be flaky..

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

sorry about the delay

> Reviewed 3 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109682#-:-NdAhBzY0nKA401nxp-1:b-d9phch)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens and @RaduBerinde)

___
*[`pkg/kv/kvserver/kvstorage/init.go` line 272 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109682#-NdAfQTL4IqghA835jXA:-NdAfQTL4IqghA835jXB:b-9ypq6q) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d7265a3609368af9cfb7f27643261d5bdac045/pkg/kv/kvserver/kvstorage/init.go#L272)):*
> ```Go
> 		const reportPeriod = 15 * time.Second
> 		if time.Since(lastReportTime) >= reportPeriod {
> 			lastReportTime = time.Now()
> ```

This is fine, but I slightly worry that someone may get confused by the batched manner in which ScanStats is updated, when the call to `mvccScanToKvs` completes with every 1000 keys.
Hmm, maybe this is not a problem. MVCCIterate will do the work for extracting 1000 keys, which is where we expect to spend an unknown amount of time (and not in this consumer), then feed this consumer 1000 keys, so if the 15s interval expires during that time we will print the stats, but won't print again for that batch of 1000 keys (since this consumer is expected to be fast). Then it will fetch another 1000 keys and if that is slow the next 15s interval expiry is on the next batch which has new stats.
___
*[`pkg/kv/kvserver/kvstorage/testdata/init` line 30 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109682#-Nd6yC8B25mHKpZpIJ6c:-NdAg_AFDNIa42hUKBUi:b-23iksr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d7265a3609368af9cfb7f27643261d5bdac045/pkg/kv/kvserver/kvstorage/testdata/init#L30)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I stressed the test and didn't see a failure, but I still wonder if these stats could be flaky..
</blockquote></details>

They won't be flaky unless we have flushes and compactions (which of course are non-deterministic in how long they take). Since the data being written is small, it looks like everything fits in the memtable (block-bytes are 0).

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109682#-:-NdBKtNa-Fh4LgR13r-v:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvstorage/init.go` line 272 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109682#-NdAfQTL4IqghA835jXA:-NdBJl0k0V1Gjz7S8VzJ:bsxrlyc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d7265a3609368af9cfb7f27643261d5bdac045/pkg/kv/kvserver/kvstorage/init.go#L272)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This is fine, but I slightly worry that someone may get confused by the batched manner in which ScanStats is updated, when the call to `mvccScanToKvs` completes with every 1000 keys.
Hmm, maybe this is not a problem. MVCCIterate will do the work for extracting 1000 keys, which is where we expect to spend an unknown amount of time (and not in this consumer), then feed this consumer 1000 keys, so if the 15s interval expires during that time we will print the stats, but won't print again for that batch of 1000 keys (since this consumer is expected to be fast). Then it will fetch another 1000 keys and if that is slow the next 15s interval expiry is on the next batch which has new stats.
</blockquote></details>

I added a comment to this effect.

**Comment by RaduBerinde** [comment]
*[`pkg/kv/kvserver/kvstorage/testdata/init` line 30 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109682#-Nd6yC8B25mHKpZpIJ6c:-NdBsLm_01Yn1rGUU8WM:b-swiiat) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d7265a3609368af9cfb7f27643261d5bdac045/pkg/kv/kvserver/kvstorage/testdata/init#L30)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

They won't be flaky unless we have flushes and compactions (which of course are non-deterministic in how long they take). Since the data being written is small, it looks like everything fits in the memtable (block-bytes are 0).
</blockquote></details>

It does look like there is something different under testrace:

```
        -range descriptor iteration done: 2 keys, 2 range descriptors (by suffix: map\[rdsc:2\]); scan stats: stepped 2 times (2 internal); seeked 2 times (2 internal); block-bytes: (total 0 B, cached 0 B); points: (count 2, key-bytes 40 B, value-bytes 58 B, tombstoned: 0) ranges: (count 0), (contained-points 0, skipped-points 0) evaluated requests: 0 gets, 1 scans, 0 reverse scans
        +range descriptor iteration done: 2 keys, 2 range descriptors (by suffix: map\[rdsc:2\]); scan stats: stepped 2 times (2 internal); seeked 2 times (2 internal); block-bytes: (total 0 B, cached 0 B); points: (count 2, key-bytes 40 B, value-bytes 72 B, tombstoned: 0) ranges: (count 0), (contained-points 0, skipped-points 0) evaluated requests: 0 gets, 1 scans, 0 reverse scans
         removed legacy uninitialized replica for r5
```

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109682)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvstorage/testdata/init` line 30 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109682#-Nd6yC8B25mHKpZpIJ6c:-NdBtyKx8jYoMXLIhoQM:b-2i3wpk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d7265a3609368af9cfb7f27643261d5bdac045/pkg/kv/kvserver/kvstorage/testdata/init#L30)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It does look like there is something different under testrace:

```
        -range descriptor iteration done: 2 keys, 2 range descriptors (by suffix: map\[rdsc:2\]); scan stats: stepped 2 times (2 internal); seeked 2 times (2 internal); block-bytes: (total 0 B, cached 0 B); points: (count 2, key-bytes 40 B, value-bytes 58 B, tombstoned: 0) ranges: (count 0), (contained-points 0, skipped-points 0) evaluated requests: 0 gets, 1 scans, 0 reverse scans
        +range descriptor iteration done: 2 keys, 2 range descriptors (by suffix: map\[rdsc:2\]); scan stats: stepped 2 times (2 internal); seeked 2 times (2 internal); block-bytes: (total 0 B, cached 0 B); points: (count 2, key-bytes 40 B, value-bytes 72 B, tombstoned: 0) ranges: (count 0), (contained-points 0, skipped-points 0) evaluated requests: 0 gets, 1 scans, 0 reverse scans
         removed legacy uninitialized replica for r5
```
</blockquote></details>

Updated to redact the scan stats in the datadrievn tests.

**Comment by nicktrav** [comment]
blathers backport 23.1

**Comment by nicktrav** [comment]
Will manually backport instead.

**Pull request merged**
