### PR TITLE
opt: interesting orderings property

### PR DESCRIPTION
**Pull request by RaduBerinde**
Introducing an InterestingOrderings rule property. These are orderings
that could potentially be generated by expressions in a certain group
cheaper than resorting. These will be used to create merge joins. In
the future, they can be useful for other things, like streaming
group-by.

The property is lazily calculated; in the test for the properties, we
make sure to fill them in so they appear in the test output.

Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
Neat stuff. This should do a good job identifying cases we care about.

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/opt/xform/interesting_orderings.go, line 68 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26727#-LF5cGRP-5vX5_Us2spv:-LF5cGRP-5vX5_Us2spw:bf5y992) ([raw file](https://github.com/cockroachdb/cockroach/blob/65119becf9c42223b2ee3a6f6ebb3bec921686af/pkg/sql/opt/xform/interesting_orderings.go#L68)):*
> ```Go
> 	ord := make([]props.Ordering, 0, tab.IndexCount())
> 	for i := 0; i < tab.IndexCount(); i++ {
> 		index := tab.Index(i)
> ```

Do you need to exclude inverted indexes here?

---

*[pkg/sql/opt/xform/interesting_orderings.go, line 90 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26727#-LF5dNx2C3V_Tat9q-b3:-LF5dNx2C3V_Tat9q-b4:b-vdj6dr) ([raw file](https://github.com/cockroachdb/cockroach/blob/65119becf9c42223b2ee3a6f6ebb3bec921686af/pkg/sql/opt/xform/interesting_orderings.go#L90)):*
> ```Go
> }
> 
> func interestingOrderingsForGroupBy(ev memo.ExprView) []props.Ordering {
> ```

If this is a scalar GroupBy that always returns 1 row, does it do any harm to get interesting orders?

---

*[pkg/sql/opt/xform/interesting_orderings.go, line 115 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26727#-LF5gYYgC927UV7BOzdc:-LF5gYYgC927UV7BOzdd:b-o8jfq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/65119becf9c42223b2ee3a6f6ebb3bec921686af/pkg/sql/opt/xform/interesting_orderings.go#L115)):*
> ```Go
> 	// hash-join, depending on which side we store).
> 	ordLeft := GetInterestingOrderings(ev.Child(0))
> 	ordRight := GetInterestingOrderings(ev.Child(1))
> ```

I don't think the right ordering is interesting for semi/anti joins. In addition, those operators don't project the right columns...

---

*[pkg/sql/opt/xform/interesting_orderings.go, line 124 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26727#-LF5bPay6sIKRjkxXBCw:-LF5bPay6sIKRjkxXBCx:b-sl30au) ([raw file](https://github.com/cockroachdb/cockroach/blob/65119becf9c42223b2ee3a6f6ebb3bec921686af/pkg/sql/opt/xform/interesting_orderings.go#L124)):*
> ```Go
> // addInterestingOrdering adds an ordering to the list, checking whether it is a
> // prefix of another ordering (or vice-versa). Can mutates the input slice.
> func addInterestingOrdering(in []props.Ordering, o props.Ordering) []props.Ordering {
> ```

These 3 methods are begging to be methods on an `InterestingOrders` type:
```
type InterestingOrders []props.Ordering

func (o *InterestingOrders) Add(o props.Ordering)

func (o *InterestingOrders) RestrictToPrefix(required props.Ordering)

func (o *InterestingOrders) RestrictToCols(cols opt.ColSet)
```
I think this class belongs in its own file, with a few unit tests to cover the uncommon edge cases, as it's awkward to test those edge cases in generic ruleprops tests.

---

*[pkg/sql/opt/xform/interesting_orderings.go, line 127 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26727#-LF5eMqY6UQP6fTNkMHg:-LF5eMqY6UQP6fTNkMHh:btiqcwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/65119becf9c42223b2ee3a6f6ebb3bec921686af/pkg/sql/opt/xform/interesting_orderings.go#L127)):*
> ```Go
> 	for i := range in {
> 		j := 0
> 		for ; j < len(o) && j < len(in[i]); j++ {
> ```

NIT: Should this be a `func (o Ordering) FindCommonPrefix(other Ordering) Ordering` utility method on `Ordering`? It'd return a slice of either `o` or `other`.

---

*[pkg/sql/opt/xform/interesting_orderings.go, line 133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26727#-LF5dyFd4StH1Cnw5q-F:-LF5dyFd4StH1Cnw5q-G:b6c63zg) ([raw file](https://github.com/cockroachdb/cockroach/blob/65119becf9c42223b2ee3a6f6ebb3bec921686af/pkg/sql/opt/xform/interesting_orderings.go#L133)):*
> ```Go
> 		}
> 		if j == len(o) {
> 			// o is equal to, or a prefix of res[i]. Do nothing.
> ```

NIT: comment needs updating since `res` isn't a variable

---

*[pkg/sql/opt/xform/interesting_orderings.go, line 148 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26727#-LF5fBTGD2AJ48XWRY2c:-LF5fBTGD2AJ48XWRY2d:b-oag9bq) ([raw file](https://github.com/cockroachdb/cockroach/blob/65119becf9c42223b2ee3a6f6ebb3bec921686af/pkg/sql/opt/xform/interesting_orderings.go#L148)):*
> ```Go
> // ordering as a prefix. If there isn't any, returns just the required ordering.
> func restrictToPrefix(in []props.Ordering, required props.Ordering) []props.Ordering {
> 	res := make([]props.Ordering, 0, len(in))
> ```

Can't we just mutate the existing list to avoid extra objects? The pattern I've seen us use before is found in `scope.removeHiddenCols`.

---

*[pkg/sql/opt/xform/testdata/ruleprops/orderings, line 244 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26727#-LF5a9v48uPt3IZgTF-X:-LF5a9v48uPt3IZgTF-Y:b-9w7q4y) ([raw file](https://github.com/cockroachdb/cockroach/blob/65119becf9c42223b2ee3a6f6ebb3bec921686af/pkg/sql/opt/xform/testdata/ruleprops/orderings#L244)):*
> ```
>  ├── columns: a:1(int) b:2(int) c:3(int) x:5(int) y:6(int) z:7(int)
>  ├── prune: (2,3,6,7)
>  ├── interesting orderings: +1,+2 +3 +7 +5,+6
> ```

I think it'd be good to enclose each ordering in parentheses or use some other kind of delimiter, as it's difficult to distinguish the multi-col orderings in that list:

 ├── interesting orderings: (+1,+2) (+3) (+7) (+5,+6)

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26727#-:-LF5h9aN1zXtKmA1uH88:btbho5z)*

**Comment by RaduBerinde** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/opt/xform/interesting_orderings.go, line 68 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26727#-LF5cGRP-5vX5_Us2spv:-LFCf75v9AfM2Qu4qy-H:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/65119becf9c42223b2ee3a6f6ebb3bec921686af/pkg/sql/opt/xform/interesting_orderings.go#L68)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Do you need to exclude inverted indexes here?
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/interesting_orderings.go, line 90 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26727#-LF5dNx2C3V_Tat9q-b3:-LFCfXIS-L4MNAdYDJ7-:b7f4v35) ([raw file](https://github.com/cockroachdb/cockroach/blob/65119becf9c42223b2ee3a6f6ebb3bec921686af/pkg/sql/opt/xform/interesting_orderings.go#L90)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

If this is a scalar GroupBy that always returns 1 row, does it do any harm to get interesting orders?
</blockquote></details>

Hm, we will get the empty list because we restrict the orderings to the grouping cols. I added a separate case for clarity though.

---

*[pkg/sql/opt/xform/interesting_orderings.go, line 115 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26727#-LF5gYYgC927UV7BOzdc:-LFCgHrYE0S7guKZeciO:b-2t8484) ([raw file](https://github.com/cockroachdb/cockroach/blob/65119becf9c42223b2ee3a6f6ebb3bec921686af/pkg/sql/opt/xform/interesting_orderings.go#L115)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I don't think the right ordering is interesting for semi/anti joins. In addition, those operators don't project the right columns...
</blockquote></details>

Good catch, added a separate case, with a TODO - We could conceivably use right-side interesting orderings on equality columns (and we can remap those to orderings on output columns).

---

*[pkg/sql/opt/xform/interesting_orderings.go, line 124 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26727#-LF5bPay6sIKRjkxXBCw:-LFCkzDj--xhc0OgqnDm:bgsznm9) ([raw file](https://github.com/cockroachdb/cockroach/blob/65119becf9c42223b2ee3a6f6ebb3bec921686af/pkg/sql/opt/xform/interesting_orderings.go#L124)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

These 3 methods are begging to be methods on an `InterestingOrders` type:
```
type InterestingOrders []props.Ordering

func (o *InterestingOrders) Add(o props.Ordering)

func (o *InterestingOrders) RestrictToPrefix(required props.Ordering)

func (o *InterestingOrders) RestrictToCols(cols opt.ColSet)
```
I think this class belongs in its own file, with a few unit tests to cover the uncommon edge cases, as it's awkward to test those edge cases in generic ruleprops tests.
</blockquote></details>

Should I put this in `props` and make this the type of the `Rule.InterestingOrderings` field?

---

*[pkg/sql/opt/xform/interesting_orderings.go, line 148 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26727#-LF5fBTGD2AJ48XWRY2c:-LFCkgF9A0jtjnoEOwdz:b-vyejdn) ([raw file](https://github.com/cockroachdb/cockroach/blob/65119becf9c42223b2ee3a6f6ebb3bec921686af/pkg/sql/opt/xform/interesting_orderings.go#L148)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Can't we just mutate the existing list to avoid extra objects? The pattern I've seen us use before is found in `scope.removeHiddenCols`.
</blockquote></details>

In the two cases where we use it, the input list is the `InterestingOrderings` of some child operator which we don't want to mutate.

---

*[pkg/sql/opt/xform/testdata/ruleprops/orderings, line 244 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26727#-LF5a9v48uPt3IZgTF-X:-LFChAVF84Jx5Uw7yRVV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/65119becf9c42223b2ee3a6f6ebb3bec921686af/pkg/sql/opt/xform/testdata/ruleprops/orderings#L244)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I think it'd be good to enclose each ordering in parentheses or use some other kind of delimiter, as it's difficult to distinguish the multi-col orderings in that list:

 ├── interesting orderings: (+1,+2) (+3) (+7) (+5,+6)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26727)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 6 of 8 files at r1, 1 of 2 files at r2, 5 of 5 files at r3.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/xform/interesting_orderings.go, line 123 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26727#-LF8rKlZ4pxenbNlgbRL:-LF8rKl_96nKRC7UlNct:byx8a1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/65119becf9c42223b2ee3a6f6ebb3bec921686af/pkg/sql/opt/xform/interesting_orderings.go#L123)):*
> ```Go
> 
> // addInterestingOrdering adds an ordering to the list, checking whether it is a
> // prefix of another ordering (or vice-versa). Can mutates the input slice.
> ```

[nit] mutates -> mutate

---

*[pkg/sql/opt/xform/testdata/ruleprops/orderings, line 148 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26727#-LFEteIt0AoP-i5tz1Xh:-LFEt9YX9IpibHOZ2EvS:bcaeop9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7aa03080a49fcb92af66090f339f36ac04fe1b93/pkg/sql/opt/xform/testdata/ruleprops/orderings#L148)):*
> ```
>  ├── keys: weak(3)
>  ├── prune: (2,3)
>  ├── interesting orderings: (+4) (+1,+2,+4)
> ```

why is +4 (`rowid`) included here, but not above in the `SELECT * FROM abc` test? Is this related to a previous PR where you automatically include the PK columns in the output of lookup join?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26727#-:-LFEu3Wo1cmic-he_snT:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/xform/interesting_orderings.go, line 123 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26727#-LF8rKlZ4pxenbNlgbRL:-LFIAhHU6ijnaFEzeWSg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/65119becf9c42223b2ee3a6f6ebb3bec921686af/pkg/sql/opt/xform/interesting_orderings.go#L123)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] mutates -> mutate
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/interesting_orderings.go, line 124 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26727#-LF5bPay6sIKRjkxXBCw:-LFJWeu0DeqT_CXkacTr:bnked3m) ([raw file](https://github.com/cockroachdb/cockroach/blob/65119becf9c42223b2ee3a6f6ebb3bec921686af/pkg/sql/opt/xform/interesting_orderings.go#L124)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Should I put this in `props` and make this the type of the `Rule.InterestingOrderings` field?
</blockquote></details>

Implemented this as  `opt.OrderingSet`.

---

*[pkg/sql/opt/xform/testdata/ruleprops/orderings, line 148 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26727#-LFEteIt0AoP-i5tz1Xh:-LFI2Wkt1iyP36K2Mfai:b-3m9y7t) ([raw file](https://github.com/cockroachdb/cockroach/blob/7aa03080a49fcb92af66090f339f36ac04fe1b93/pkg/sql/opt/xform/testdata/ruleprops/orderings#L148)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

why is +4 (`rowid`) included here, but not above in the `SELECT * FROM abc` test? Is this related to a previous PR where you automatically include the PK columns in the output of lookup join?
</blockquote></details>

Yes, the lookup-join now does output column 4 (it doesn't seem that way because of the final presentation). In the test above, we are not scanning column `4` at all. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26727)*

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

---

*[pkg/sql/opt/ordering.go, line 169 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/26727#-LFJz4NxCepOttKK1dua:-LFJz4NxCepOttKK1dub:btxqa6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c80f05cd9ddd89de48c97db8c86b8cbaca826a1/pkg/sql/opt/ordering.go#L169)):*
> ```Go
> }
> 
> // RestrictToPrefix keeps only the interesting orderings that have the required
> ```

NIT: update comment to not mention "interesting"

---

*[pkg/sql/opt/ordering.go, line 197 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/26727#-LFK-6XzEWv_WHmHnT4J:-LFK-6XzEWv_WHmHnT4K:b-mt0dbn) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c80f05cd9ddd89de48c97db8c86b8cbaca826a1/pkg/sql/opt/ordering.go#L197)):*
> ```Go
> 		}
> 		if prefix > 0 {
> 			o = o[:prefix]
> ```

Don't need this because you do `o[:prefix]` below.

---

*[pkg/sql/opt/ordering_test.go, line 75 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/26727#-LFJzFqw5OFc3eBQtHd_:-LFJzFqw5OFc3eBQtHda:b8y6ffm) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c80f05cd9ddd89de48c97db8c86b8cbaca826a1/pkg/sql/opt/ordering_test.go#L75)):*
> ```Go
> }
> 
> func TestOrderSet(t *testing.T) {
> ```

NIT: TestOrderingSet

---

*[pkg/sql/opt/testutils/opt_tester.go, line 177 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/26727#-LFK0I58B5e0hJ4FwFQz:-LFK0I58B5e0hJ4FwFR-:b6tqmo5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c80f05cd9ddd89de48c97db8c86b8cbaca826a1/pkg/sql/opt/testutils/opt_tester.go#L177)):*
> ```Go
> 			return fmt.Sprintf("error: %s\n", text)
> 		}
> 		if ot.Flags.PostProcessFn != nil {
> ```

Why not just always force lazy props to be populated rather than giving option?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26727#-:-LFK0frT-ZhFSV8NuILk:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

---

*[pkg/sql/opt/ordering.go, line 197 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/26727#-LFK-6XzEWv_WHmHnT4J:-LFN8XlO7s8oJuvzihdp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c80f05cd9ddd89de48c97db8c86b8cbaca826a1/pkg/sql/opt/ordering.go#L197)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Don't need this because you do `o[:prefix]` below.
</blockquote></details>

Done.

---

*[pkg/sql/opt/testutils/opt_tester.go, line 177 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/26727#-LFK0I58B5e0hJ4FwFQz:-LFN93nSBmUF7N1Mwpev:b-25q4yd) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c80f05cd9ddd89de48c97db8c86b8cbaca826a1/pkg/sql/opt/testutils/opt_tester.go#L177)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Why not just always force lazy props to be populated rather than giving option?
</blockquote></details>

Hm, good question. I think the reason I used a callback was because I initially thought that we'd need unexported stuff but that's not the case. Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26727)*

**Comment by RaduBerinde** [comment]
Hm seems like I will have to move `GetInterestingOrderings` into `xform/custom_funcs`

**Comment by RaduBerinde** [comment]
Oh, scratch that, for some reason I thought it's a separate package.

**Pull request merged**
