### PR TITLE
geomfn: implement validity operators

### LINKED ISSUE #48960: geo/geomfn: implement ST_IsValid({geometry,int4})
Implement `ST_IsValid` on arguments {geometry,int4}, which should adopt [PostGIS behaviour](https://postgis.net/docs/ST_IsValid.html).

_Observers: Please react to this issue if you need this functionality._

For Geometry builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geomfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geomfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
  * When using GEOS, you can reference the [C API](https://github.com/libgeos/geos/blob/master/capi/geos_c.h.in) for which functions are available. Unfortunately, Windows is not currently supported when using GEOS.
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go). Note that we currently do not support optional arguments, so we define functions that have optional arguments once without the optional argument (using the default value in the optional position), and once with the optional argument.
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output. Tests here should just ensure the builtin is linked end to end (your exhaustive unit tests go the above mentioned packages!).
* Ensure the documentation is regenerated by calling `make buildshort`. You can also play with it by calling `./cockroach demo --empty` afterwards.
* Submit your PR - make sure to follow the guidelines from [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

You can follow #48552 for an example PR.

The following additional guidance has been issued on implementing this function:

Implemented by GEOS.

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-06-30T05:29:57Z. Changes to titles, body and labels may be overwritten.</sub>

### LINKED ISSUE #48961: geo/geomfn: implement ST_IsValid({geometry})
Implement `ST_IsValid` on arguments {geometry}, which should adopt [PostGIS behaviour](https://postgis.net/docs/ST_IsValid.html).

_Observers: Please react to this issue if you need this functionality._

For Geometry builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geomfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geomfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
  * When using GEOS, you can reference the [C API](https://github.com/libgeos/geos/blob/master/capi/geos_c.h.in) for which functions are available. Unfortunately, Windows is not currently supported when using GEOS.
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go). Note that we currently do not support optional arguments, so we define functions that have optional arguments once without the optional argument (using the default value in the optional position), and once with the optional argument.
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output. Tests here should just ensure the builtin is linked end to end (your exhaustive unit tests go the above mentioned packages!).
* Ensure the documentation is regenerated by calling `make buildshort`. You can also play with it by calling `./cockroach demo --empty` afterwards.
* Submit your PR - make sure to follow the guidelines from [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

You can follow #48552 for an example PR.

The following additional guidance has been issued on implementing this function:

Implemented by GEOS.

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-06-30T05:29:57Z. Changes to titles, body and labels may be overwritten.</sub>

### LINKED ISSUE #48963: geo/geomfn: implement ST_IsValidReason({geometry})
Implement `ST_IsValidReason` on arguments {geometry}, which should adopt [PostGIS behaviour](https://postgis.net/docs/ST_IsValidReason.html).

_Observers: Please react to this issue if you need this functionality._

For Geometry builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geomfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geomfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
  * When using GEOS, you can reference the [C API](https://github.com/libgeos/geos/blob/master/capi/geos_c.h.in) for which functions are available. Unfortunately, Windows is not currently supported when using GEOS.
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go). Note that we currently do not support optional arguments, so we define functions that have optional arguments once without the optional argument (using the default value in the optional position), and once with the optional argument.
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output. Tests here should just ensure the builtin is linked end to end (your exhaustive unit tests go the above mentioned packages!).
* Ensure the documentation is regenerated by calling `make buildshort`. You can also play with it by calling `./cockroach demo --empty` afterwards.
* Submit your PR - make sure to follow the guidelines from [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

You can follow #48552 for an example PR.

The following additional guidance has been issued on implementing this function:

Implemented by GEOS.

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-06-30T05:29:57Z. Changes to titles, body and labels may be overwritten.</sub>

### LINKED ISSUE #48964: geo/geomfn: implement ST_IsValidReason({geometry,int4})
Implement `ST_IsValidReason` on arguments {geometry,int4}, which should adopt [PostGIS behaviour](https://postgis.net/docs/ST_IsValidReason.html).

_Observers: Please react to this issue if you need this functionality._

For Geometry builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geomfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geomfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
  * When using GEOS, you can reference the [C API](https://github.com/libgeos/geos/blob/master/capi/geos_c.h.in) for which functions are available. Unfortunately, Windows is not currently supported when using GEOS.
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go). Note that we currently do not support optional arguments, so we define functions that have optional arguments once without the optional argument (using the default value in the optional position), and once with the optional argument.
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output. Tests here should just ensure the builtin is linked end to end (your exhaustive unit tests go the above mentioned packages!).
* Ensure the documentation is regenerated by calling `make buildshort`. You can also play with it by calling `./cockroach demo --empty` afterwards.
* Submit your PR - make sure to follow the guidelines from [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

You can follow #48552 for an example PR.

The following additional guidance has been issued on implementing this function:

Implemented by GEOS.

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-06-30T05:29:57Z. Changes to titles, body and labels may be overwritten.</sub>

### PR DESCRIPTION
**Pull request by otan**
Unfortunately we cannot implement ST_IsValidDetail because it returns a
composite type, which we do not yet support.

Resolves #48960
Resolves #48961
Resolves #48963
Resolves #48964

Release note (sql change): Implements ST_IsValid, ST_IsValidReason and
ST_MakeValid operators for geometry types.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51484#-:-MCSEkJSBOnJLJ1cVLGx:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/geo/geomfn/validity_check.go, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51484#-MCSA1SNB42fRWZ6uJDB:-MCSA1SO1qQeqHW2EJkC:b-bs1729) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc09e28cd9f1b0a40ddc6bb331c7e89b10b8090e/pkg/geo/geomfn/validity_check.go#L21)):*
> ```Go
> type ValidDetail struct {
> 	IsValid bool
> 	// Reason is only populated if IsValid = true.
> ```

shouldn't this be IsValid=false?
___
*[pkg/geo/geomfn/validity_check.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51484#-MCSA42U5jNkUQkAMYoE:-MCSA42U5jNkUQkAMYoF:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc09e28cd9f1b0a40ddc6bb331c7e89b10b8090e/pkg/geo/geomfn/validity_check.go#L23)):*
> ```Go
> 	// Reason is only populated if IsValid = true.
> 	Reason string
> 	// InvalidLocation is only populated if IsValid = true.
> ```

ditto
___
*[pkg/geo/geos/geos.go, line 623 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51484#-MCSC2Sh9_9BbQ6YyaLV:-MCSC2Si-aUVgWwlEg6b:bk5yo3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc09e28cd9f1b0a40ddc6bb331c7e89b10b8090e/pkg/geo/geos/geos.go#L623)):*
> ```Go
> // means that self-intersecting rings forming holes are considered valid.
> // It returns a bool representing whether it is valid, a string giving a reason for
> // invalidity, an EWKB representing the location things are invalid at.
> ```

[nit] and an EWKB
___
*[pkg/sql/sem/builtins/geo_builtins.go, line 2352 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51484#-MCSE3G60204GJgGgeWt:-MCSE3G7BQYsM76BHRU4:b7uoriv) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc09e28cd9f1b0a40ddc6bb331c7e89b10b8090e/pkg/sql/sem/builtins/geo_builtins.go#L2352)):*
> ```Go
> 			infoBuilder{
> 				info:         `Returns whether the geometry is valid as defined by the OGC spec.`,
> 				libraryUsage: usesGEOS,
> ```

Just out of curiosity: is this field purely for documentation purposes? Is there a way we could test that this matches reality? (Obviously that would be a different PR...)
___
*[pkg/sql/sem/builtins/geo_builtins.go, line 2440 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51484#-MCSDqzRAQe2q8vANodw:-MCSDqzRAQe2q8vANodx:b-9ad7h2) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc09e28cd9f1b0a40ddc6bb331c7e89b10b8090e/pkg/sql/sem/builtins/geo_builtins.go#L2440)):*
> ```Go
> 			types.Geometry,
> 			infoBuilder{
> 				info:         "Returns a valid form of the given geometry.",
> ```

Do you need to mention the OGC spec here? Or not necessary?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51484)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/geo/geomfn/validity_check.go, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51484#-MCSA1SNB42fRWZ6uJDB:-MCSJIa04GOcnH-j7q3g:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc09e28cd9f1b0a40ddc6bb331c7e89b10b8090e/pkg/geo/geomfn/validity_check.go#L21)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

shouldn't this be IsValid=false?
</blockquote></details>

Done.
___
*[pkg/geo/geomfn/validity_check.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51484#-MCSA42U5jNkUQkAMYoE:-MCSJIqPCf8yKT3aFJ1d:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc09e28cd9f1b0a40ddc6bb331c7e89b10b8090e/pkg/geo/geomfn/validity_check.go#L23)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/geo/geos/geos.go, line 623 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51484#-MCSC2Sh9_9BbQ6YyaLV:-MCSJU1yDeAJtQdiD9h0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc09e28cd9f1b0a40ddc6bb331c7e89b10b8090e/pkg/geo/geos/geos.go#L623)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] and an EWKB
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/geo_builtins.go, line 2352 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51484#-MCSE3G60204GJgGgeWt:-MCSJUz55qF8Vx474bgI:b35gocu) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc09e28cd9f1b0a40ddc6bb331c7e89b10b8090e/pkg/sql/sem/builtins/geo_builtins.go#L2352)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Just out of curiosity: is this field purely for documentation purposes? Is there a way we could test that this matches reality? (Obviously that would be a different PR...)
</blockquote></details>

Yep - only docs.
Not sure about detection - requires some fancy go parsing i reckon.
___
*[pkg/sql/sem/builtins/geo_builtins.go, line 2440 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51484#-MCSDqzRAQe2q8vANodw:-MCSJdgB2kxeWBt10BM9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc09e28cd9f1b0a40ddc6bb331c7e89b10b8090e/pkg/sql/sem/builtins/geo_builtins.go#L2440)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Do you need to mention the OGC spec here? Or not necessary?
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51484#-:-MCSMB9x1R-pdt7eT3ab:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/sem/builtins/geo_builtins.go, line 2352 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51484#-MCSE3G60204GJgGgeWt:-MCSM2Qy4edk6_5xgXUI:b-15ii6s) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc09e28cd9f1b0a40ddc6bb331c7e89b10b8090e/pkg/sql/sem/builtins/geo_builtins.go#L2352)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Yep - only docs.
Not sure about detection - requires some fancy go parsing i reckon.
</blockquote></details>

Sounds good -- probably not high priority

**Comment by otan** [comment]
bors r=rytaft

**Comment by otan** [comment]
bors r=rytaft

**Pull request merged**
