### PR TITLE
sql: add support for hash and merge joins in the new factory

### LINKED ISSUE #50291: sql: implement ConstructHashJoin in the new factory
This issue tracks creating `HashJoinerSpec` directly by `distSQLSpecExecFactory` (see #47473).

### PR DESCRIPTION
**Pull request by yuzefovich**
**sql: minor cleanup of joiner planning**

`joinNode.mergeJoinOrdering` is now set to non-zero length by the
optimizer only when we can use a merge join (meaning that number of
equality columns is non-zero and equals the length of the ordering we
have). This allows us to slightly simplify the setup up of the merge
joiners.

Additionally, this commit switching to using `[]exec.NodeColumnOrdinal`
instead of `int` for equality columns in `joinPredicate` which allows us
to remove one conversion step when planning hash joiners.

Also we introduce a small helper that will be reused by the follow-up
work.

Release note: None

**sql: add support for hash and merge joins in the new factory**

This commit adds implementation of `ConstructHashJoin` and
`ConstructMergeJoin` in the new factory by mostly refactoring and
reusing already existing code in the physical planner. Notably,
interleaved joins are not supported yet.

Fixes: #50291.
Addresses: #47473.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Only the last 3 commits should be looked at, but they are RFAL.

**Comment by yuzefovich** [comment]
Rebased, RFAL.

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 7 of 8 files at r2, 8 of 8 files at r3, 8 of 8 files at r4, 7 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50450)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/distsql_physical_planner.go, line 2227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50450#-MAa5uU3680WdXrn9JRk:-MAa5uU3680WdXrn9JRl:bj8ioqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ca18d0df243beb4b66328e784d4aa176da5bcd/pkg/sql/distsql_physical_planner.go#L2227)):*
> ```Go
> 			RightEqColumnsAreKey: n.pred.rightEqKey,
> 		}
> 	} else {
> ```

Maybe add a comment that if the `mergeJoinOrdering` is non-zero, it must be the length of the equality columns. Perhaps we should also add an assertion to be safe.
___
*[pkg/sql/distsql_physical_planner.go, line 2123 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50450#-MAaAEohAwYa-fjzMA9s:-MAaAEohAwYa-fjzMA9t:b9yvjj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac073895e17a37839c18f5f24c66b3a936953aad/pkg/sql/distsql_physical_planner.go#L2123)):*
> ```Go
> type joinPlanningInfo struct {
> 	leftPlan, rightPlan                         *PhysicalPlan
> 	getCoreSpec                                 func(info *joinPlanningInfo) execinfrapb.ProcessorCoreUnion
> ```

Instead of having this be a field I think it'd be nicer for it to be a method:
```
func (i joinPlanningInfo) makeCoreSpec(n Ordering) ProcessorCoreUnion {
   // Check len(n) and return spec based on that and fields in `joinPlanningInfo`
}
```
___
*[pkg/sql/logictest/testdata/logic_test/distsql_join, line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50450#-MAahUm117BfA8KR_GKv:-MAahUm117BfA8KR_GKw:bkmhuhm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4e8fcae649fcd9b3ccd6d11ba9956214312208f/pkg/sql/logictest/testdata/logic_test/distsql_join#L61)):*
> ```
> SELECT feature_name FROM crdb_internal.feature_usage WHERE feature_name='sql.exec.query.is-distributed' AND usage_count > 0
> ----
> sql.exec.query.is-distributed
> ```

Did this fail with the new config?
___
*[pkg/sql/logictest/testdata/logic_test/experimental_distsql_planning_5node, line 156 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50450#-MAbLm_43-rA4CZMCbJw:-MAbLm_43-rA4CZMCbJx:b-pfbpuw) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b9eea5c68c41999150713ba6f2951128a02b00c/pkg/sql/logictest/testdata/logic_test/experimental_distsql_planning_5node#L156)):*
> ```
> 5  5
> 
> # Check that merge join is supported by the new factory.
> ```

Is it worth running expain to double check merge join is used?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50450)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/distsql_physical_planner.go, line 2227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50450#-MAa5uU3680WdXrn9JRk:-MAc5LZY4ge8Bh6cbsHJ:be873nx) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ca18d0df243beb4b66328e784d4aa176da5bcd/pkg/sql/distsql_physical_planner.go#L2227)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Maybe add a comment that if the `mergeJoinOrdering` is non-zero, it must be the length of the equality columns. Perhaps we should also add an assertion to be safe.
</blockquote></details>

When `mergeJoinOrdering` is non-zero, then we must be planning a merge join, the spec for which doesn't have equality columns, so I don't think it's important to sanity check that equality columns are of the same length as the merge join ordering.
___
*[pkg/sql/distsql_physical_planner.go, line 2123 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50450#-MAaAEohAwYa-fjzMA9s:-MAc59LEEoWYoZz8E83Y:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac073895e17a37839c18f5f24c66b3a936953aad/pkg/sql/distsql_physical_planner.go#L2123)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Instead of having this be a field I think it'd be nicer for it to be a method:
```
func (i joinPlanningInfo) makeCoreSpec(n Ordering) ProcessorCoreUnion {
   // Check len(n) and return spec based on that and fields in `joinPlanningInfo`
}
```
</blockquote></details>

Good point, done.
___
*[pkg/sql/logictest/testdata/logic_test/distsql_join, line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50450#-MAahUm117BfA8KR_GKv:-MAc0tpT5WpYsJF0vvlX:b54f0jg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4e8fcae649fcd9b3ccd6d11ba9956214312208f/pkg/sql/logictest/testdata/logic_test/distsql_join#L61)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Did this fail with the new config?
</blockquote></details>

Yes, because of the test deficiency - although `distsql_join` uses 5node configs, all the data lives on a single node, so the queries are not distributed. That's why I moved it to a file that manually distributes the data.
___
*[pkg/sql/logictest/testdata/logic_test/experimental_distsql_planning_5node, line 156 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50450#-MAbLm_43-rA4CZMCbJw:-MAbyD9q7_5cI94abucD:brzcnz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b9eea5c68c41999150713ba6f2951128a02b00c/pkg/sql/logictest/testdata/logic_test/experimental_distsql_planning_5node#L156)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is it worth running expain to double check merge join is used?
</blockquote></details>

I confirmed it manually and don't think it is worth adding an explain as well. The reason is that the optimizer definitely chooses a plan with a merge join because we have indexes on the equality columns. Additionally, we currently don't support `ConstructSort` method in the new factory, so if other join type is used, then a sort would be planned, and the query will error out.

Also, I think eventually this logic test file will only contain the plans that are partially distributed, everything else could be removed as redundant (or moved to the other logic test files).

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 12 of 12 files at r6, 13 of 13 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50450#-:-MAfvD-A8z1bGFfK2lmo:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/distsql_plan_join.go, line 58 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50450#-MAfuphZ9Snav4r7mlqC:-MAfuphZ9Snav4r7mlqD:bitn334) ([raw file](https://github.com/cockroachdb/cockroach/blob/d55f5eb675dbb2a374537f0d628bd2e16b36df2c/pkg/sql/distsql_plan_join.go#L58)):*
> ```Go
> 	if len(info.leftMergeOrd.Columns) != len(info.rightMergeOrd.Columns) {
> 		panic(fmt.Sprintf(
> 			"unexpectedly different merge join ordering lengths: left %d, right %d",
> ```

nit: `s/unexpectedly/unexpected`

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50450#-:-MAfz7pjEDLW8oKnrzbR:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/distsql_plan_join.go, line 58 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50450#-MAfuphZ9Snav4r7mlqC:-MAfynfFEFFCROYpHNN6:by7sl8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/d55f5eb675dbb2a374537f0d628bd2e16b36df2c/pkg/sql/distsql_plan_join.go#L58)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: `s/unexpectedly/unexpected`
</blockquote></details>

I did mean to use "unexpectedly" - to me an adverb sounds cleaner. Alternatively, it could be `unexpected: different ...`, but I'll keep the original wording.

**Pull request merged**
