### PR TITLE
catalog: protobuf and cluster versioning for table statistics forecasts

### PR DESCRIPTION
**Pull request by michae2**
Add a field to the TableDescriptor for per-table statistics forecasting.
We'll want this when backporting statistics forecasts to 22.1.

Release note: None

### CODE REVIEW

**Comment by michae2** [comment]
(Note that the first commit is https://github.com/cockroachdb/cockroach/pull/79009 which can be ignored.)

**Review by msirek — COMMENTED** [review]
Looks good to me.  I'll leave it to the experts to approve it though.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79025#-:-MzON3BI2JeAv7CiDT5M:b7ot9yw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @postamar, and @rytaft)

**Review by rytaft — APPROVED** [review]
:lgtm: (but wait for either @ajwerner or @postamar)

> Reviewed 7 of 7 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79025#-:-MzPntEY4zhJ_MvG1csY:bj6pxo8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

**Review by mgartner — APPROVED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79025)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @postamar)

**Review by ajwerner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79025#-:-MzVUKKQ61VCMAatX8YJ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @postamar)

**Review by rytaft — APPROVED** [review]
Thanks!

bors r+

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79025#-:-MzVUCpn6mScGxj7aPyO:b-voiyyw)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @postamar)

**Pull request merged**
