### PR TITLE
server: add NodeIds to DatabaseDetails and TableStats responses

### PR DESCRIPTION
**Pull request by xinhaoz**
Related to: #63391

Previously, DatabaseDetails and TableStats did not return a list
of nodes that store their data. This commit adds an ordered
list of node ids to each of the responses. This is necessary
to report node/region information in the DB console databases
pages. For the database details endpoint, we return the list
of nodes only if stats are requested.

Release justification: low risk, high benefit changes to existing
functionality

Release note (api change): A list of node ids representing the
nodes that store data for the database has been added to the
stats field in the databases details endpoint under `nodeIds`.
Database details must be requested with include_stats set to true,
e.g. `/_admin/v1/databases/{database}?include_stats=true`

Similarly, `nodeIds` has also been added to the table stats
endpoint, which is an ordered list of node ids which stores
the table data:
`/_admin/v1/databases/{database}/tables/{table}/stats`

### CODE REVIEW

**Comment by Azhng** [comment]
More of a general comment. The concept of `NodeID` is going away in the Serverless. The tenant nodes will only be able to have `SQLInstanceID` assigned to the SQL Pod, since all the actual nodes (the KV Pods in this case) are shared among all the tenants.

We already have a handful of RPC endpoints that need to deal with this awkwardness. Should even further pollute the `NodeID` concept into more RPC endpoints?

**Comment by maryliag** [comment]
This information will not be displayed on serverless, precisely because nodes don't make sense on it. But we need this for dedicated and specially multi-region, and on those cases the value is indeed `node`. So for the purpose of this issue, use NodeID.

**Review by maryliag — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69788)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[pkg/server/admin.go, line 560 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69788#-MicDBv93zgHLB3lq8s5:-MicDBv93zgHLB3lq8s6:b-zchgss) ([raw file](https://github.com/cockroachdb/cockroach/blob/21349eeb174476b816020defca3213366f0aa265/pkg/server/admin.go#L560)):*
> ```Go
> 	}
> 
> 	// Track all nodes storing database
> ```

nit: databases
nit: period

**Review by maryliag — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69788#-:-MicHvp78hw_UCPWb9dp:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

**Pull request merged**
