### PR TITLE
colexec: implement set operation hash and merge joins

### LINKED ISSUE #48505: colexec: extend joiners to support the remaining join types
Currently hash joiner and merge joiner support 6 out of 8 possible join types that we have. We should add the support for the remaining join types.
- Hash join
  - [x] `IntersectAll`
  - [x] `ExceptAll`
- Merge join
  - [x] `IntersectAll`
  - [x] `ExceptAll`

### PR DESCRIPTION
**Pull request by yuzefovich**
**sql: some cleanups (no logical changes)**

Use pretty aliases rather the protobuf generated ones for join types.
Also unify check whether right cols should be included for join type.

Release note: None

**rowexec: add NULLs into set op join test cases**

As well as a mixed ordering test case.

Release note: None

**colexec: add support of set operation joins to merge joiner**

This commit adds support for INTERSECT ALL and EXCEPT ALL joins to merge
joiner. These join types are similar to LEFT SEMI and LEFT ANTI,
respectively, with two crucial differences important to the
implementation:
- they treat NULLs as equals
- they can build from the buffered group "partially".

To address the first we introduce special null checking behavior when
vectors can have nulls, and if we find a null match or mismatch, we do
not attempt to compare the values (they are garbage anyway). The probing
phase has been adjusted accordingly.

To address the second we started tracking how many rows from the left
buffered group we've already used for building. Once that number reaches
the requested partial group size, we know that we're done with the
building phase on that buffered group, so we short-circuit the building
of the remaining rows but make sure to reset the builder state (for the
next building phase). For performance reasons we choose to output first
N rows for both set operation join type: e.g. if we have the following:
  left:  {1, 1}, {1, 2}, {1, 3}
  right: {1, 1}, {1, 1}
with equality on the zeroth column, we will output
  INTERSECT ALL: {1, 1}, {1, 2}
     EXCEPT ALL: {1, 1}.

One notable change is that in the test harness for comparing operators
against processors we will now be randomizing the batch size.

Addresses: #48505.

Release note: None

**colexec: add support of set operation joins to hash joiner**

This commit adds support of set operation joins (INTERSECT ALL and
EXCEPT ALL) in hash joiner by introducing a special "deleting" probe
mode to the hash table. The idea is that the hash table will be
"deleting" tuples once they get a single match so that consequent
probing tuples would not match against those ("deleting" is in quotes
because we don't actually delete anything, and rather mark build tuples
as "deleted" in the same `visited` array that is used in the default
probing mode). Hash joiner itself has been slightly adjusted to remap
IntersectAll to LeftSemi and ExceptAll to LeftAnti previously supported
joins.

Fixes: #48505.

Release note (sql change): Vectorized execution engine now natively
supports set operation joins (queries with `INTERSECT ALL` and `EXCEPT
ALL`).

### CODE REVIEW

**Comment by yuzefovich** [comment]
First two commits are in a separate PR, but it is RFAL.

**Comment by yuzefovich** [comment]
As anecdotal evidence on the performance, I have this: on tpcc with 100 warehouses 3.3.2.6 check (with an index hint) on single node local cluster I get [54s with vectorize=off](https://cockroachdb.github.io/distsqlplan/decode.html#eJycVF9v2j4Uff99Cus-wU8exXagLNKkUJp1SClhQLV2K4pSckejhZjZRi2q-t2nOEX8LV3HA1HuvcfnnnOSPIH-nYEL_nU_aHd7pN1rBzfffVI57w5Hw69BlVSGfuB3RkRGD1GaUCKj5OVa_sssmuSGfB6El-QWpEpQ3QIJB-f-gJzdHISRc3_YqRL_uuP3R6QdBGuSbDWereazqGSayEVuKv9XSybLE2Vpjt5cpbNYLcnFILzqF5SVV0-pbuz12ky5HFDIZYK9eIYa3B_AYExhruQEtZaqKD3ZgW7yCG6dQprPF6YojylMpEJwn8CkJkNwYRTfZTjAOEF1UgcKCZo4zeyxL7t7Vg5QGM7jXLvkA1AIF8YlnqAepx6j3ilQUPJBE4Vx4hJRtz-goE2cZcSkM3QJr4lmXXBHA4W7pcHVNBOcXKZnMH6mIBdmvao28RTBZc_03-SwI3JsOoc0MatJ7AtqfGw1dhSxRq3pMCH2JPEaIxdHJPH3SGpPpwqnsZHqhG8r2lg2LERhsg4FKLR7N1EvHEW9qyCoeKy6V-L7JVGUOuFVbxQNwm_DSnU_bOevvOGs1mg2HCYKb2bxI5nhTKolWehiyyZrHc1cvGrQ2pdFLkvRW6aMC-RbIwdc_hLr-yGacH4itk0eLefobnwOgEKGP01lZT71nOonlU7vt0u7D1TpW4EkB98U29k0UNTqTvNU8MI_e_xhXNnaArIaP23xlkVqIxUmRKcJusTOHozDsWmUnSTVv17qb7yZznse4wHqucw17qZ18OR6EREmUywj13KhJthXcmJpytvQ4mwhQW3Krihvurlt2U_HJpgdBfMtcH0XzN_BzHfB4ijY2WEeP__3JwAA__9YCSsa), [33s with vectorize=on on master](https://cockroachdb.github.io/distsqlplan/decode.html#eJysVF1v2koQfb-_YjVPcLWX-AsIlq5kQtwWycEUiJq0QZZjT4lV43V3101QlP9eeU0UPuy0qcoDls_M2ZlzZryPIL6nYIN7NfWG4wkZTobe9WeXtM7H88X8o9cmrbnruaMFYcF9kMSUsCDePqt_lgZRJsm7mX9BboDxGPkNEH927s7I2XUtjZy781GbuFcjd7ogQ897KZI-p6fP-WlQVYpYkcnWv-2qkqoTpEmGTs6Tdcg35P3Mv5yWJVuNp7R3-mrKqZoDChmLcRKuUYD9BXRYUsg5i1AIxkvoUSWM4wewNQpJlheyhJcUIsYR7EeQiUwRbFiEtynOMIyRn2hAIUYZJqk6dtu7o-QAhXkeZsIm_wEFv5A2cUzqGNTRqdMHCrehjO5QEFbIvIwaA7M8TxZ5uoOamvoBBYEpRjL5kciNTfROhckwTYlM1lhC3a5mDHoClk8UKv5Wg5DhCsHWn-if6dRf0anGVidWV2LNBqVmvdTu4LT7O1qNjt7TdNNqFmu8RexwteK4CiXjJ8a-1h0ZfikX45c5AoXh5DqY-Itgcul5LUdvH0HGMWSW0Mi_nCyCmf9p3mof74f1l_YDHzAqZMKyrW-mZXX6_XWza2ajay9mFRmrnNhzalkyf5VSY_2HUNzNUfr5ibnv_GKTo71zrQCFFL_K1vNEqGO1_-fJ6m4fOty_ejNrnDzyUKv3UB90et1TfSC2DRHO7gXhGMa701CR3ZU1OoZu9ftWSVNd1_Oq0N6umx2t17P6faE-AsYxJiKJ0SYqFyiswweyxjXjG1KIckF7FrlIzraROBHftrhpKLxp-NZbPpkZipxlAg-XoPZkrZw8xiusNkmwgkc45SxSZapXX_EUEKOQVdSsXsaZCqkLbJesv0o29sjaIdl4Q2XjkGy-SrYOKi-f_vkZAAD__-8YYZ4=), and [18s with this PR](https://cockroachdb.github.io/distsqlplan/decode.html#eJysVF1v2koQfb-_YjVPcLWX-IvcYKmSCXFbJAdTIGrSBlmOPSWrLl53d52GRvnvlW2i8GHSpioPWD47Z86eMyM_gPrGwQX_chz0hyPSH_WDq08-aZ0Np7Pph6BNWlM_8AczIqLvEUspEVG6ftb_gkdJpsnbSXhOrkHIFOU1kHBy5k_I6VUjjZz500Gb-JcDfzwj_SB4FuFP5fypnke1UiKKTLf-bddKlU7EWYZeLtkylivybhJejEvJ1sEu7Y17HaqpLwcUMpHiKF6iAvczmDCnkEuRoFJCltBDVTBM78E1KLAsL3QJzykkQiK4D6CZ5gguzOIbjhOMU5RHBlBIUceMV23Xd_cqO0BhmseZcsl_QCEstEs8m3oW9Uzq_Q8UbmKd3KIiotB5eWr17LKfLnK-gdpG9QMKCjkmmt0xvXKJ2akxHXNONFtiCR0f92zDUjB_pFDz1x6UjhcIrvlI_8yn-YLPamxNZs3KrH3Aqd1stds76f6OV6djd7tm1zxs1nqN2f5iIXERayGPrG2vGzbC0i6mz3MECv3RVTQKZ9HoIghantneg6x9yC6hQXgxmkWT8OO01d7fD-cv7QfeY1JoJrJ1bs6J0-mZzvJwbPbB2J7TKjJRR7EV1bxk_qqkIfv3sbqdog7zI3s7-tkqR3fjuwIUOH7RraeRUM9pv5FscbsN7S5gc5oNUe6FaDSHaHZObKNrdRVQWMb35A4TLST7gSlZ4lLIFYk5F0msy1057pFzdrpfmTL1dbPOcaq6Q2NxXrPNE1S5yBTujqexs1HOBNMF1jNWopAJjqVIKpn6Nax4FZCi0vWpXb8Ms-qo-rZsks0XydYW2dglW69QtnbJ9otkZ0d5_vjPzwAAAP__h-tGJw==).

The query has an aggregation and then set operation, so we roughly gain 20 seconds when doing ordered aggregation in the vectorized engine vs row-by-row engine, and another 15 seconds when doing set operation hash join in the vectorized engine vs wrapping `rowexec.hashJoiner`.

**Review by jordanlewis — COMMENTED** [review]
First 2 commits LGTM, the second 2 I'll try to look at later.

> Reviewed 13 of 13 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49159#-:-M7eyJ4p09TuwLT5zlQG:b-t5jto8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

**Review by asubiotto — CHANGES_REQUESTED** [review]
Was there any performance effect on non-set operation hash and merge joins?

> Reviewed 13 of 13 files at r1, 1 of 1 files at r2, 3 of 13 files at r3, 1 of 14 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49159#-:-M7hJWMJ6fjx5Eb8-Ywl:b-sl8ai4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/colexec/hashjoiner_test.go, line 900 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49159#-M7hNjzOA09dBUzM-3td:-M7hNjzOA09dBUzM-3te:bdufuox) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b5f64877e17f2bcf4a578128a84b6128c1d7714/pkg/sql/colexec/hashjoiner_test.go#L900)):*
> ```Go
> 		},
> 		{
> 			description: "25",
> ```

These descriptions should probably be improved. Not sure why they're numbers. I think we want to keep them short but understandable, so that we don't have to write a huge string for `TESTS=<testname>` when running a single one of these but we still know what the test is testing.
___
*[pkg/sql/colexec/hashtable_tmpl.go, line 268 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49159#-M7hOhmF9Qr8KcosRDxC:-M7hOhmF9Qr8KcosRDxD:b-dskyp5) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b5f64877e17f2bcf4a578128a84b6128c1d7714/pkg/sql/colexec/hashtable_tmpl.go#L268)):*
> ```Go
> } // */}}
> 
> // {{if not .HashTableMode.IsDistinct}}
> ```

Can this be a single `and` check?
___
*[pkg/sql/colexec/hashtable_tmpl.go, line 305 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49159#-M7hOm7BE35rCjQKJejv:-M7hOm7C7aiXVSd7vS3W:b5ll3sy) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b5f64877e17f2bcf4a578128a84b6128c1d7714/pkg/sql/colexec/hashtable_tmpl.go#L305)):*
> ```Go
> 
> // {{if not .HashTableMode.IsDistinct}}
> // {{if .HashTableMode.IsDeleting}}
> ```

Can we just check `IsDeleting`?
___
*[pkg/sql/colexec/mergejoiner_tmpl.go, line 186 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49159#-M7hJ7KhD11SDfD3Wv-f:-M7hJ7KiATMrEMmtLIg1:b-i8289r) ([raw file](https://github.com/cockroachdb/cockroach/blob/659efe42e9a21b6e157414d9fedafec6faabb191/pkg/sql/colexec/mergejoiner_tmpl.go#L186)):*
> ```Go
> 					// {{/*
> 					//     Non-set operation joins do not allow null equality,
> 					//     so if we either value is NULL, the tuples are not
> ```

nit: `s/we either/either`
___
*[pkg/sql/colexec/execgen/cmd/execgen/hashtable_gen.go, line 26 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49159#-M7hPQIcAFLmifRY4x8S:-M7hPQIcAFLmifRY4x8T:b-pv43te) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b5f64877e17f2bcf4a578128a84b6128c1d7714/pkg/sql/colexec/execgen/cmd/execgen/hashtable_gen.go#L26)):*
> ```Go
> 
> type hashTableInfo struct {
> 	IsDistinct bool
> ```

Instead of having several booleans, can we use an enum?
___
*[pkg/sql/distsql/columnar_operators_test.go, line 651 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49159#-M7hKOZSEq1-fMfXwMoi:-M7hKOZSEq1-fMfXwMoj:bti9jbb) ([raw file](https://github.com/cockroachdb/cockroach/blob/659efe42e9a21b6e157414d9fedafec6faabb191/pkg/sql/distsql/columnar_operators_test.go#L651)):*
> ```Go
> 							// arbitrary results, and we skip such
> 							// configuration.
> 							addFilter = false
> ```

I'm not sure I fully understand this, could you explain?
___
*[pkg/sql/distsql/columnar_utils_test.go, line 72 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49159#-M7hLPVL0FYOfGdhncTw:-M7hLPVL0FYOfGdhncTx:bw4upmo) ([raw file](https://github.com/cockroachdb/cockroach/blob/659efe42e9a21b6e157414d9fedafec6faabb191/pkg/sql/distsql/columnar_utils_test.go#L72)):*
> ```Go
> 		randomBatchSize := 1 + rng.Intn(3)
> 		fmt.Printf("coldata.BatchSize() is set to %d\n", randomBatchSize)
> 		if err := coldata.SetBatchSizeForTests(randomBatchSize); err != nil {
> ```

Why are we randomizing the batch size here?
___
*[pkg/sql/logictest/testdata/logic_test/vectorize_local, line 148 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49159#-M7hPF-O2UcMzaKExvSb:-M7hPF-O2UcMzaKExvSc:b4nuwk7) ([raw file](https://github.com/cockroachdb/cockroach/blob/91ee79ff3b7bdb3453be249761898d590df715b6/pkg/sql/logictest/testdata/logic_test/vectorize_local#L148)):*
> ```
> # we don't support.
> query T
> EXPLAIN (VEC) (SELECT y FROM xyz) EXCEPT ALL (SELECT x AS y FROM xyz) ORDER BY y
> ```

Maybe switch this to using a join with an ON expression

**Review by yuzefovich — COMMENTED** [review]
I ran the benchmarks of the whole `colexec` package [here](https://gist.github.com/yuzefovich/e3cb029527fc6070ce2b538b21f836d7), and there are minor regressions of about 8% in the inner merge join (I believe due to an additional field in `mjBuilderCrossProductState`). The field is only used in the set operation joins, so in other joins we copy that field pointlessly. Still the raw merge join speed is so high that I don't think this regression is that important at the moment. I'm worried about extracting the field out of this struct because we've had bugs when the builder state not being reset correctly, and if we move the field out, it can be error-prone. There are no visible hits in the hash joiner nor unordered distinct.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49159#-:-M7imrjvEL7CZwhQLZ6S:b-1qppmu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/colexec/hashjoiner_test.go, line 900 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49159#-M7hNjzOA09dBUzM-3td:-M7idKCA5Q3QrqHaXo42:b5d6bfp) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b5f64877e17f2bcf4a578128a84b6128c1d7714/pkg/sql/colexec/hashjoiner_test.go#L900)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

These descriptions should probably be improved. Not sure why they're numbers. I think we want to keep them short but understandable, so that we don't have to write a huge string for `TESTS=<testname>` when running a single one of these but we still know what the test is testing.
</blockquote></details>

Wow, I didn't realize you could run a single test case from the unit test - I was always simply commenting out test cases that I wanted to skip, this is a very nice option!

I added a fix to the harness to use the `description` field, but these description numbers are in line with what we have in this file, so I'd argue it's beyond the scope of this commit to change that.

They are numbers because I was lazy to write more descriptive versions when I was unifying the join unit test cases (the merge joiner always had the description field, so those cases have nice description - those are actually too long to type out to run a single test case).
___
*[pkg/sql/colexec/hashtable_tmpl.go, line 268 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49159#-M7hOhmF9Qr8KcosRDxC:-M7iekeiAtI5wg7iBzHh:b-sqcqhh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b5f64877e17f2bcf4a578128a84b6128c1d7714/pkg/sql/colexec/hashtable_tmpl.go#L268)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Can this be a single `and` check?
</blockquote></details>

Yes. I'm not sure whether it is easier to read though, but I don't have a strong preference here, done.
___
*[pkg/sql/colexec/hashtable_tmpl.go, line 305 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49159#-M7hOm7BE35rCjQKJejv:-M7ifAdiCKKQNSUBlfhK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b5f64877e17f2bcf4a578128a84b6128c1d7714/pkg/sql/colexec/hashtable_tmpl.go#L305)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Can we just check `IsDeleting`?
</blockquote></details>

Done.
___
*[pkg/sql/colexec/mergejoiner_tmpl.go, line 186 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49159#-M7hJ7KhD11SDfD3Wv-f:-M7imk8q7VhlZm3tToVJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/659efe42e9a21b6e157414d9fedafec6faabb191/pkg/sql/colexec/mergejoiner_tmpl.go#L186)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: `s/we either/either`
</blockquote></details>

Done.
___
*[pkg/sql/colexec/execgen/cmd/execgen/hashtable_gen.go, line 26 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49159#-M7hPQIcAFLmifRY4x8S:-M7ihfTtCYsFITSo838D:bcus9ab) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b5f64877e17f2bcf4a578128a84b6128c1d7714/pkg/sql/colexec/execgen/cmd/execgen/hashtable_gen.go#L26)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Instead of having several booleans, can we use an enum?
</blockquote></details>

Nice idea, done.
___
*[pkg/sql/distsql/columnar_operators_test.go, line 651 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49159#-M7hKOZSEq1-fMfXwMoi:-M7ii-6B1Gw1RDqhCL42:baq50os) ([raw file](https://github.com/cockroachdb/cockroach/blob/659efe42e9a21b6e157414d9fedafec6faabb191/pkg/sql/distsql/columnar_operators_test.go#L651)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I'm not sure I fully understand this, could you explain?
</blockquote></details>

Consider the following: we have `left_table` with two `INT` columns with two rows `(1, NULL), (1, 0)` and `right_table` with one `INT` column with a single row `(1)`. When we do `left_table INTERSECT ALL right_table`, there are two valid outputs: either `1, NULL` or `1, 0` (same goes for `EXCEPT ALL`).

Now, if we then have a filter after the intersection, for example, `IS NULL`, then we will get `1, NULL` in the former case and an empty set in the latter, and both of these are valid. I imagine that in the real world we will never have a join specification that is both a set operation and has a filter due to this nondeterminism.
___
*[pkg/sql/distsql/columnar_utils_test.go, line 72 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49159#-M7hLPVL0FYOfGdhncTw:-M7ijGnn2iW0MGBtxSI8:btwmwe5) ([raw file](https://github.com/cockroachdb/cockroach/blob/659efe42e9a21b6e157414d9fedafec6faabb191/pkg/sql/distsql/columnar_utils_test.go#L72)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why are we randomizing the batch size here?
</blockquote></details>

Because it increases out test coverage. I think it's a very good idea to do so because most of our `AgainstProcessor` tests have very small number of rows (say `10`), so randomization of batch size allows us exercise multi-batch logic more.

Or is your comment is more like "why in this file, and not in `sql/distsql/main_test.go`"? The reason for that is my desire to use the same `rng` - every `AgainstProcessor` test creates a separate rand source and prints out a seed if there is a failure, and reusing the same rand source will allow for easy reproduction.

On this note, I switched to `randutil.NewPseudoRand` throughout `columnar_operators_test`.
___
*[pkg/sql/logictest/testdata/logic_test/vectorize_local, line 148 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49159#-M7hPF-O2UcMzaKExvSb:-M7im1RD1i5fUXOB0Svq:b-gph11x) ([raw file](https://github.com/cockroachdb/cockroach/blob/91ee79ff3b7bdb3453be249761898d590df715b6/pkg/sql/logictest/testdata/logic_test/vectorize_local#L148)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Maybe switch this to using a join with an ON expression
</blockquote></details>

I'm not sure whether you can have set operation join with ON expression, but I switched to a query with FULL OUTER join and ON expression that is not supported currently.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49159)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/distsql/columnar_operators_test.go, line 651 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49159#-M7hKOZSEq1-fMfXwMoi:-M7jP6720KJvd-mysDC2:b-fwhqaa) ([raw file](https://github.com/cockroachdb/cockroach/blob/659efe42e9a21b6e157414d9fedafec6faabb191/pkg/sql/distsql/columnar_operators_test.go#L651)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Consider the following: we have `left_table` with two `INT` columns with two rows `(1, NULL), (1, 0)` and `right_table` with one `INT` column with a single row `(1)`. When we do `left_table INTERSECT ALL right_table`, there are two valid outputs: either `1, NULL` or `1, 0` (same goes for `EXCEPT ALL`).

Now, if we then have a filter after the intersection, for example, `IS NULL`, then we will get `1, NULL` in the former case and an empty set in the latter, and both of these are valid. I imagine that in the real world we will never have a join specification that is both a set operation and has a filter due to this nondeterminism.
</blockquote></details>

Oh, actually, I think the scenario when we have non-equality columns in the set operation join might not be possible, I'll ask optimizer friends.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49159)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/distsql/columnar_operators_test.go, line 651 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49159#-M7hKOZSEq1-fMfXwMoi:-M7kEVy83bbMv_Vb2V5a:boqo3ez) ([raw file](https://github.com/cockroachdb/cockroach/blob/659efe42e9a21b6e157414d9fedafec6faabb191/pkg/sql/distsql/columnar_operators_test.go#L651)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Oh, actually, I think the scenario when we have non-equality columns in the set operation join might not be possible, I'll ask optimizer friends.
</blockquote></details>

It seems like such scenario is currently not possible, but I'm leaning towards keeping it anyway because it increases our test coverage (although of hypothetical scenarios).

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 23 of 23 files at r5, 1 of 1 files at r6, 13 of 13 files at r7, 14 of 14 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49159#-:-M7rfoDh0GSE9wnBY4jT:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/execgen/cmd/execgen/hashtable_gen.go, line 28 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/49159#-M7rfbhRA3TI53H8PlbW:-M7rfbhRA3TI53H8PlbX:b-hdic92) ([raw file](https://github.com/cockroachdb/cockroach/blob/caeea8d4e9dc3b5816e84aaec3c4b037b6219e48/pkg/sql/colexec/execgen/cmd/execgen/hashtable_gen.go#L28)):*
> ```Go
> 
> const (
> 	hashTableFullBuildDefaultProbe hashTableMode = iota
> ```

These would benefit from comments.
___
*[pkg/sql/distsql/columnar_operators_test.go, line 651 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49159#-M7hKOZSEq1-fMfXwMoi:-M7reDam2RWqwKUL0L1f:ba7s052) ([raw file](https://github.com/cockroachdb/cockroach/blob/659efe42e9a21b6e157414d9fedafec6faabb191/pkg/sql/distsql/columnar_operators_test.go#L651)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

It seems like such scenario is currently not possible, but I'm leaning towards keeping it anyway because it increases our test coverage (although of hypothetical scenarios).
</blockquote></details>

ok. In that case, I would prefer to `continue` instead of rerun a test with `addFilter = false` since we'll ahve already run that in a previous iteration, right? Actually I think you might have an improvement in a following commit for this.

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49159#-:-M7sX0pKCIUOXUZFOTfe:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/colexec/execgen/cmd/execgen/hashtable_gen.go, line 28 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/49159#-M7rfbhRA3TI53H8PlbW:-M7sUHrV0ABiC2oma3Qn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/caeea8d4e9dc3b5816e84aaec3c4b037b6219e48/pkg/sql/colexec/execgen/cmd/execgen/hashtable_gen.go#L28)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

These would benefit from comments.
</blockquote></details>

Done.
___
*[pkg/sql/distsql/columnar_operators_test.go, line 651 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49159#-M7hKOZSEq1-fMfXwMoi:-M7sUXyo7Xs8ekltEtfT:b-89h0ob) ([raw file](https://github.com/cockroachdb/cockroach/blob/659efe42e9a21b6e157414d9fedafec6faabb191/pkg/sql/distsql/columnar_operators_test.go#L651)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

ok. In that case, I would prefer to `continue` instead of rerun a test with `addFilter = false` since we'll ahve already run that in a previous iteration, right? Actually I think you might have an improvement in a following commit for this.
</blockquote></details>

Hm, I'm a little confused by your comment. With the current code we will run all possible combinations of join types and `nEqCols vs nCols` with two options `addFilter = false` and `addFilter = true` except for this special combo of "set operation join and `nEqCols < nCols`" in which case we will run only `addFilter = false`. Maybe you're suggesting that rather than introducing this `getAddFilterOptions` function we would check the same condition and if `addFilter == true` and we have the special combo, then we'd skip such configuration? The behavior will be the same, but I decided to extract a helper function to reduce this special casing in two places. I think I'll keep it as is.

**Comment by yuzefovich** [comment]
Actually, I'll probably need to rebase on top of vec-datum work.

bors r-

**Pull request merged**
