### PR TITLE
opt: do not generate unnecessary cross-joins on join input

### LINKED ISSUE #79384: opt: unnecessary cross-joins with when generating a lookup join with a lookup expression
Notice in the query plan below that the cross-join to produce the `lookup_join_const_col_@7` column is unnecessary.

```
exec-ddl
CREATE TABLE t1234 (
  a INT,
  b INT,
  c INT,
  INDEX (a, b, c)
)
----

opt expect=GenerateLookupJoinsWithFilter
SELECT m FROM small JOIN t1234 ON b IN (1, 2, 3) AND c > 0 AND m = a
----
project
 ├── columns: m:1!null
 └── inner-join (lookup t1234@t1234_a_b_c_idx)
      ├── columns: m:1!null a:6!null b:7!null c:8!null
      ├── lookup expression
      │    └── filters
      │         ├── m:1 = a:6 [outer=(1,6), constraints=(/1: (/NULL - ]; /6: (/NULL - ]), fd=(1)==(6), (6)==(1)]
      │         ├── b:7 IN (1, 2, 3) [outer=(7), constraints=(/7: [/1 - /1] [/2 - /2] [/3 - /3]; tight)]
      │         └── c:8 > 0 [outer=(8), constraints=(/8: [/1 - ]; tight)]
      ├── fd: (1)==(6), (6)==(1)
      ├── inner-join (cross)
      │    ├── columns: m:1 "lookup_join_const_col_@7":12!null
      │    ├── multiplicity: left-rows(one-or-more), right-rows(zero-or-more)
      │    ├── scan small
      │    │    └── columns: m:1
      │    ├── values
      │    │    ├── columns: "lookup_join_const_col_@7":12!null
      │    │    ├── cardinality: [3 - 3]
      │    │    ├── (1,)
      │    │    ├── (2,)
      │    │    └── (3,)
      │    └── filters (true)
      └── filters (true)
```

Jira issue: CRDB-14777

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: do not generate unnecessary cross-joins on lookup join input

This commit fixes a bug that caused unnecessary cross-joins on the input
of lookup joins, causing both suboptimal query plans and incorrect query
results. The bug only affected lookup joins with lookup expressions.

Fixes #79384

Release note (bug fix): A bug has been fixed that caused the optimizer
to generate query plans with logically incorrect lookup joins. The bug
can only occur in queries with an inner join, e.g., `t1 JOIN t2`, if all
of the following are true:
  1. The join contains an equality condition between columns of both
     tables, e.g., `t1.a = t2.a`.
  2. A query filter or `CHECK` constraint constrains a column to a set
     of specific values, e.g., `t2.b IN (1, 2, 3)`. In the case of a
     `CHECK` constraint, the column must be `NOT NULL`.
  3. A query filter or `CHECK` constraint constrains a column to a
     range, e.g., `t2.c > 0`. In the case of a `CHECK` constraint, the
     column must be `NOT NULL`.
  4. An index contains a column from each of the criteria above, e.g.,
     `INDEX t2(a, b, c)`.
This bug has been present since version 21.2.0.

#### opt: do not cross-join input of inverted semi-join

In #78685, we prevented `GenerateLookupJoins` from incorrect creating a
cross-join on the input of a semi-join, addressing #78681. This commit
addresses the same issue with `GenerateInvertedJoins`, which we
originally forgot to fix.

Informs #78681

Release note (bug fix): A bug has been fixed which caused the optimizer
to generate invalid query plans which could result in incorrect query
results. The bug, which has been present since version 21.1.0, can
appear if all of the following conditions are true:
  1. The query contains a semi-join, such as queries in the form
     `SELECT * FROM a WHERE EXISTS (SELECT * FROM b WHERE a.a @> b.b)`.
  2. The inner table has a multi-column inverted index containing the
     inverted column in the filter.
  3. The index prefix columns are constrained to a set of values via the
     filter or a `CHECK` constraint, e.g., with an `IN` operator. In the
     case of a `CHECK` constraint, the column is `NOT NULL`.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79389#-:-MzqbvfXE5yQFsY0eEBH:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach)

**Comment by rytaft** [comment]
For cases (2) and (3) above -- could those also come from a check constraint?

**Review by mgartner — COMMENTED** [review]
> For cases (2) and (3) above -- could those also come from a check constraint?

Yes, if the column is `NOT NULL`. Great catch. I've updated the commit and PR description.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79389#-:-Mztq-sT0oPiN4MOgEfJ:b5z9os)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach)

**Review by rytaft — APPROVED** [review]
> I realized that #78685 fixed #78681 for GenerateLookupJoins, but not for GenerateInvertedJoins. I've added another commit to this PR that fixes that issue.

Good catch! In that case will we also need to backport this to 21.1, though? And maybe worth updating the other TA to include this case?

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79389#-:-MzuBuyS4F9bWD9Cl0_9:btbnh69)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @mgartner)

___
*[-- commits, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/79389#-MzuCBrN3E9eRYh5cgl7):*
nit: address -> addresses
___
*[pkg/sql/opt/xform/testdata/rules/join, line 9046 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/79389#-MzuCqitA0OJNljcl7Fy:-MzuCqitA0OJNljcl7Fz:buffbjb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1c961950cd364daecb32cb8d4d7f9e869e2fd67/pkg/sql/opt/xform/testdata/rules/join#L9046)):*
> ```
> # GenerateInvertedJoins fires in this case because the semi join is converted to
> # an inner join by ConvertSemiToInnerJoin.
> opt
> ```

nit: should you add `expect=GenerateInvertedJoins`?

**Review by mgartner — COMMENTED** [review]
> In that case will we also need to backport this to 21.1, though?

Yes, just the second commit though. I've added the label.

> And maybe worth updating the other TA to include this case?

Can we just update a TA? My concern is that the TA was already pushed out to customers and if we update it then some customers won't see the changes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79389#-:-MzvGZWh-oP0fe-unf8W:b-sprn3a)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @rytaft)

___
*[pkg/sql/opt/xform/testdata/rules/join, line 9046 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/79389#-MzuCqitA0OJNljcl7Fy:-MzvHfq7CF_dyOruGbt8:b-yvsa7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1c961950cd364daecb32cb8d4d7f9e869e2fd67/pkg/sql/opt/xform/testdata/rules/join#L9046)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: should you add `expect=GenerateInvertedJoins`?
</blockquote></details>

We don't really care whether `GenerateInvertedJoins` fires for the converted inner-join or not, only that it doesn't fire for the semi-join. So I've disabled `ConvertSemiToInnerJoin` and added `expect-not=GenerateInvertedJoins`.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Yes, just the second commit though. I've added the label.

Blathers will try to backport both commits for 21.1 (although I'm guessing it will fail on that branch anyway)

> Can we just update a TA? My concern is that the TA was already pushed out to customers and if we update it then some customers won't see the changes.

Sounds like you've resolved this offline, but let me know otherwise.

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79389#-:-MzvcefV0uNe5x3dW5gW:b-2au9bc)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach)

**Comment by mgartner** [comment]
> Blathers will try to backport both commits for 21.1 (although I'm guessing it will fail on that branch anyway)

I'll manually backport if that happens. TFTR!

bors r+

**Pull request merged**
