### PR TITLE
util/uuid: always handle UUIDs as values

### PR DESCRIPTION
**Pull request by tamird**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10566)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Thank you very much! Just curious about `enginepb.TxnMeta.ID` before giving this the thumbs up.

---

Reviewed 31 of 31 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/roachpb/data.go, line 675 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10566#-KW9JYZNvSTV1d8-R3JN:-KW9JYZNvSTV1d8-R3JO:b-iup8am) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1f6f465e4ac80b59d8bc39bde030bd1650436af/pkg/roachpb/data.go#L675)):*
> ```Go
> 		TxnMeta: enginepb.TxnMeta{
> 			Key:       baseKey,
> 			ID:        &u,
> ```

Is there a reason to keep `enginepb.TxnMeta.ID` as nullable? Does it need to be optional? If not, a lot of this could be simplified.

---

*[pkg/roachpb/data_test.go, line 398 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10566#-KW9I5EubUU7Ff9PGBTF:-KW9I5Ev6Nv_w9V-fzoq:blp2091) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1f6f465e4ac80b59d8bc39bde030bd1650436af/pkg/roachpb/data_test.go#L398)):*
> ```Go
> 		Isolation: enginepb.SNAPSHOT,
> 		Key:       Key("foo"),
> 		ID: func() *uuid.UUID {
> ```

yuck...

---

*[pkg/util/uuid/uuid.go, line 34 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10566#-KW9Iq9XE_xu6n36amii:-KW9Iq9XE_xu6n36amij:b-2b7m1z) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1f6f465e4ac80b59d8bc39bde030bd1650436af/pkg/util/uuid/uuid.go#L34)):*
> ```Go
> // String returns the canonical representation of the UUID. For nil UUIDs,
> // returns <nil>.
> func (u UUID) String() string {
> ```

This method isn't needed anymore, is it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10566#-:-KW9JlVygUhBJ7tGOwg7:b4m6hkj)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/roachpb/data.go, line 675 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10566#-KW9JYZNvSTV1d8-R3JN:-KW9LEZchpGtAjS6yz68:bp6d7zk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1f6f465e4ac80b59d8bc39bde030bd1650436af/pkg/roachpb/data.go#L675)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Is there a reason to keep `enginepb.TxnMeta.ID` as nullable? Does it need to be optional? If not, a lot of this could be simplified.
</details>
Unfortunately we couldn't change its nullability even if it made sense, since it is serialized "below" raft.

---

*[pkg/roachpb/data_test.go, line 398 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10566#-KW9I5EubUU7Ff9PGBTF:-KW9LO02WizZvOCsDUkC:bejmmzs) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1f6f465e4ac80b59d8bc39bde030bd1650436af/pkg/roachpb/data_test.go#L398)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> yuck...
</details>
or yum!

---

*[pkg/util/uuid/uuid.go, line 34 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10566#-KW9Iq9XE_xu6n36amii:-KW9LQmKM-ZGXL9nM-dW:b1r9ww0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1f6f465e4ac80b59d8bc39bde030bd1650436af/pkg/util/uuid/uuid.go#L34)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> This method isn't needed anymore, is it?
</details>
Good eye! Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10566)*

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Review status: 30 of 31 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/roachpb/data.go, line 675 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10566#-KW9JYZNvSTV1d8-R3JN:-KW9eP63JvMSZfr__Tev:bldtpqp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1f6f465e4ac80b59d8bc39bde030bd1650436af/pkg/roachpb/data.go#L675)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Unfortunately we couldn't change its nullability even if it made sense, since it is serialized "below" raft.
</details>
I didn't realize `gogoproto.nullable` affected the serialization format.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10566#-:-KW9emXr0-8Ty6bKpf5b:bnfp4nl)*

**Comment by tamird** [comment]
Review status: 30 of 31 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/roachpb/data.go, line 675 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10566#-KW9JYZNvSTV1d8-R3JN:-KW9i0t-13viR5avaln3:b522r9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1f6f465e4ac80b59d8bc39bde030bd1650436af/pkg/roachpb/data.go#L675)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> I didn't realize `gogoproto.nullable` affected the serialization format.
</details>
It doesn't, but it changes the message's zero value, and in proto2 there is a difference between null and empty, so the difference is the presence of the field tag.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10566)*

**Comment by bdarnell** [comment]
Review status: 30 of 31 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/util/uuid/uuid.go, line 43 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10566#-KWHoOqlr8fV_vxf2wzl:-KWHoOqlr8fV_vxf2wzm:bxvqwt7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2162490c8cf9571ed5ce0e37a79648cd7bf2a0ed/pkg/util/uuid/uuid.go#L43)):*
> ```Go
> //
> // TODO(tschottdorf): fix upstream.
> // TODO(tamird): what does fixing upstream even mean?
> ```

https://github.com/gogo/protobuf/issues/199 proposed changing the method name used by the `raw` interface, which upstream rejected (for backwards compatibility). I'm not sure if there is a fix that upstream would accept (maybe rearranging things so that TextMarshaler takes priority over `raw` if both are implemented?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10566)*

**Comment by tamird** [comment]
Review status: 30 of 31 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/util/uuid/uuid.go, line 43 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10566#-KWHoOqlr8fV_vxf2wzl:-KWKl9yMC4PaxxRhiiva:buvlc92) ([raw file](https://github.com/cockroachdb/cockroach/blob/2162490c8cf9571ed5ce0e37a79648cd7bf2a0ed/pkg/util/uuid/uuid.go#L43)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> https://github.com/gogo/protobuf/issues/199 proposed changing the method name used by the `raw` interface, which upstream rejected (for backwards compatibility). I'm not sure if there is a fix that upstream would accept (maybe rearranging things so that TextMarshaler takes priority over `raw` if both are implemented?)
</details>
Thanks for the pointer! I've opened https://github.com/gogo/protobuf/pull/227/files; let's see what they say.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10566)*

**Pull request merged**
