### PR TITLE
migrations part 2/2: persistence

### PR DESCRIPTION
**Pull request by tbg**
This finishes up the bulk of the remaining work for the [version migation
RFC][rfc]. There are two main changes:

1. Add `*ExposedClusterVersion` to the `cluster.Settings` struct. Internally,
   it wraps the `version` cluster setting, but it exposes it indirectly to
   synchronize version updates with the node's engines. More precisely,
   - `*ExposedClusterVersion` is initialized with the persisted version early
     in the `Node` startup sequence
   - the `Node` registers itself for notifications whenever the `version`
     changes
   - `*ExposedClusterVersion` only exposes a change in the underlying `version`
     variable to callers *after* calling the `Node` callback (which in turn
     persists the update to all engines).
   - The result is that whenever `IsActive()` or `Version()` is called, the
     returned version is safe to use or to migrate to without having to worry
     about backwards compatibility.
1. Add code that synthesizes from and writes the version to the engines.
   This mostly picks up #17155 with some code golf that refactors the node
   startup sequence appropriately, making sure that even when there are stores
   that need (asynchronous) bootstrapping, they'll still have the cluster
   version persisted at the end.

TODO:

- [ ] Testing.
- [ ] Update the RFC.
- [ ] Pave the way for future use of `UseVersion < MinVersion`, if still required.
- [ ] Migration that makes sure there's always a cluster version settings able
entry (@m-schneider).
- [ ] Disallow version bump if settings table has no value entry.
- [ ] Consider removing the reliance on gossip callback ordering. Gossip does
      not *guarantee* that version updates arrive in-order, and we currently
      persist the cluster version blindly. `*ExposedClusterVersion` would
      have to do its own synthesis to refuse illegal changes backwards. This
      may be a non-issue but needs some consideration (all of the cluster
      settings would be vulnerable to it).

[rfc]: https://github.com/cockroachdb/cockroach/pull/16977

### CODE REVIEW

**Comment by tschottdorf** [comment]
I added some folks who I know have migrations in the pipeline to check whether the approach works.

**Comment by tschottdorf** [comment]
Hmm, even with my hacks, there's still a bunch of problems with the cluster version singleton. I'll try to hack around it in a different way, but in the medium term, I'm not convinced that the settings stuff should stop being built around singletons.

**Comment by tschottdorf** [comment]
Ok, this is ready for a first real look. I'll be working on testing as the initial review is happening.

**Comment by bdarnell** [comment]
Reviewed 6 of 12 files at r1, 2 of 18 files at r2, 73 of 74 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[pkg/migration/empty.go, line 17 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411#-KrRDieAxZrvp-c6eQ6y:-KrRDieAxZrvp-c6eQ6z:bg7s43y) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdae0bd9359ae022ee8c6411f13c0825d3364a0f/pkg/migration/empty.go#L17)):*
> ```Go
> package migration
> 
> // TODO(tschottdorf): remove this package.
> ```

Why not do it now? Will `migration/sqlmigrations` move back after this change?

---

*[pkg/server/node.go, line 429 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411#-KrRK6lsDC5IQTbtjQX2:-KrRIuCPfgFSrecMar0V:b93jemb) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdae0bd9359ae022ee8c6411f13c0825d3364a0f/pkg/server/node.go#L429)):*
> ```Go
> }
> 
> func (n *Node) inspectEngines(
> ```

We should probably unify this with `Server.isAnyStoreBootstrapped`. (could be a separate PR if the refactoring is too much of a pain)

---

*[pkg/server/node.go, line 433 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411#-KrRJgvKBLJmv-ryTfRp:-KrRJgvKBLJmv-ryTfRq:bf19brv) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdae0bd9359ae022ee8c6411f13c0825d3364a0f/pkg/server/node.go#L433)):*
> ```Go
> ) (
> 	initEngines []engine.Engine,
> 	bootstrapEngines []engine.Engine,
> ```

These names are confusing: `initEngines` *are* initialized, but `bootstrapEngines` are *not* bootstrapped. 

---

*[pkg/settings/updater.go, line 142 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411#-KrR9wwVxDUEm5sB_MRM:-KrR9wwWyu72sD0JRhpj:b-2dxhqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdae0bd9359ae022ee8c6411f13c0825d3364a0f/pkg/settings/updater.go#L142)):*
> ```Go
> }
> 
> // PreservingUpdater is an Updater that does not reset the settings not
> ```

I may just be lacking context for this package but the presence of both ResettingUpdater and PreservingUpdater feels like a strange design. 

This comment should indicate what it *does*, not just what it doesn't do (or at least reference ResettingUpdater, not just "an Updater")). 

---

*[pkg/settings/updater.go, line 149 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411#-KrRBH2X_fQq0FxQz89S:-KrRBH2YDKKlbmDfhnrV:bh98sxy) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdae0bd9359ae022ee8c6411f13c0825d3364a0f/pkg/settings/updater.go#L149)):*
> ```Go
> 
> // Done is a no-op.
> func (pu PreservingUpdater) Done() {}
> ```

Maybe implement ResettingUpdater in terms of PreservingUpdater instead of the other way around?

---

*[pkg/settings/cluster/cluster_version.go, line 24 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411#-KrRBuLkY5aqzZKpSp8D:-KrRBuLkY5aqzZKpSp8E:berd89d) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdae0bd9359ae022ee8c6411f13c0825d3364a0f/pkg/settings/cluster/cluster_version.go#L24)):*
> ```Go
> 	// data marked with an earlier version than MinimumSupportedVersion,
> 	// then the binary will exit with an error.
> 	MinimumSupportedVersion = VersionMajorOneMinorZero
> ```

I think spelling out these names makes them harder to scan. Let's name them with digits: `Version1_0`, `Version1_1`. But I'd prefer to keep the name `VersionBase` for 1.0.

---

*[pkg/settings/cluster/cluster_version.go, line 38 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411#-KrRDIMsL-eBQeh95I9V:-KrRDIMsL-eBQeh95I9W:b-vac3hb) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdae0bd9359ae022ee8c6411f13c0825d3364a0f/pkg/settings/cluster/cluster_version.go#L38)):*
> ```Go
> 	// VersionMajorOneMinorOne is v1.1.
> 	// Note that 1.1-alpha versions already self-identify as v1.1.
> 	VersionMajorOneMinorOne = roachpb.Version{Major: 1, Minor: 1}
> ```

Isn't this premature? I think there's another migration or two coming before 1.1 is finalized.

---

*[pkg/settings/cluster/settings.go, line 724 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411#-KrRHpn7fs_N3L3aiIou:-KrRHpn7fs_N3L3aiIov:b-ohylhi) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdae0bd9359ae022ee8c6411f13c0825d3364a0f/pkg/settings/cluster/settings.go#L724)):*
> ```Go
> // that if the Setting has the Manual flag set, this Updater simply ignores all
> // updates.
> func (s *Settings) MakeUpdater() settings.Updater {
> ```

I think this may have been the only place we copy the Settings struct instead of passing a pointer. If so, Settings.Manual could just be an `atomic.Value` instead of a `*atomic.Value`. 

---

*[pkg/storage/stores_test.go, line 354 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411#-KrRPhCAL-5XL34NWJUS:-KrRPhCAL-5XL34NWJUT:beqwptq) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdae0bd9359ae022ee8c6411f13c0825d3364a0f/pkg/storage/stores_test.go#L354)):*
> ```Go
> }
> 
> // TestStoresClusterVersionReadWrite verifies that the cluster version is
> ```

Rename to match code.

---

*[pkg/storage/stores_test.go, line 494 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411#-KrRPcJsA1JJMQixM0uF:-KrRPcJsA1JJMQixM0uG:beqwptq) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdae0bd9359ae022ee8c6411f13c0825d3364a0f/pkg/storage/stores_test.go#L494)):*
> ```Go
> }
> 
> // TestStoresPersistedClusterVersionMismatch verifies an error occurs when
> ```

Rename to match code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[pkg/migration/empty.go, line 17 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411#-KrRDieAxZrvp-c6eQ6y:-KrWAR1GglSgvaPu07gU:b-un24mu) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdae0bd9359ae022ee8c6411f13c0825d3364a0f/pkg/migration/empty.go#L17)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Why not do it now? Will `migration/sqlmigrations` move back after this change?
</blockquote></details>

No, I'll do it in this PR. Just want to avoid spurious diff + rebase conflicts.

---

*[pkg/server/node.go, line 429 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411#-KrRK6lsDC5IQTbtjQX2:-KrWW94lIW0PqH3UJ1Tl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdae0bd9359ae022ee8c6411f13c0825d3364a0f/pkg/server/node.go#L429)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

We should probably unify this with `Server.isAnyStoreBootstrapped`. (could be a separate PR if the refactoring is too much of a pain)
</blockquote></details>

Done.

---

*[pkg/server/node.go, line 433 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411#-KrRJgvKBLJmv-ryTfRp:-KrWW9R5vF5EGvTnggpm:b-4xavcn) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdae0bd9359ae022ee8c6411f13c0825d3364a0f/pkg/server/node.go#L433)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

These names are confusing: `initEngines` *are* initialized, but `bootstrapEngines` are *not* bootstrapped. 
</blockquote></details>

Done (`bootstrappedEngines` and `emptyEngines`).

---

*[pkg/settings/updater.go, line 142 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411#-KrR9wwVxDUEm5sB_MRM:-KrWEl8nxyZe35JuSTyu:b-3xld0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdae0bd9359ae022ee8c6411f13c0825d3364a0f/pkg/settings/updater.go#L142)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I may just be lacking context for this package but the presence of both ResettingUpdater and PreservingUpdater feels like a strange design. 

This comment should indicate what it *does*, not just what it doesn't do (or at least reference ResettingUpdater, not just "an Updater")). 
</blockquote></details>

This is a bit spaghetti at the moment due to the fact. Does it make more sense now? I repurposed the `Done()` method which was really "reset everything that wasn't set".

---

*[pkg/settings/updater.go, line 149 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411#-KrRBH2X_fQq0FxQz89S:-KrWIkGiBgmwuwdebsx7:b-gcg583) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdae0bd9359ae022ee8c6411f13c0825d3364a0f/pkg/settings/updater.go#L149)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Maybe implement ResettingUpdater in terms of PreservingUpdater instead of the other way around?
</blockquote></details>

Obsolete, see new code. There's only one "real" updater now.

---

*[pkg/settings/cluster/cluster_version.go, line 24 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411#-KrRBuLkY5aqzZKpSp8D:-KrWCBuYuS_iuqi8B_L4:b-bav4wq) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdae0bd9359ae022ee8c6411f13c0825d3364a0f/pkg/settings/cluster/cluster_version.go#L24)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I think spelling out these names makes them harder to scan. Let's name them with digits: `Version1_0`, `Version1_1`. But I'd prefer to keep the name `VersionBase` for 1.0.
</blockquote></details>

That works for me, though I'm curious why you prefer `VersionBase` over something that describes itself?

---

*[pkg/settings/cluster/cluster_version.go, line 38 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411#-KrRDIMsL-eBQeh95I9V:-KrWB0WZxrnwzSBxuUCx:bi9mzcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdae0bd9359ae022ee8c6411f13c0825d3364a0f/pkg/settings/cluster/cluster_version.go#L38)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Isn't this premature? I think there's another migration or two coming before 1.1 is finalized.
</blockquote></details>

So? With the mechanism in place, these clusters will identify as max version = 1.1, but you have to migrate them. Initially it runs 1.0. If you add a new migration, you add a 1.0-x version, and when running the new binary you run `SET CLUSTER SETTING version = '1.0-x'`, repeat as desired. You're right that one could upgrade to `1.1` and then things get weird.

The upshot is that the cluster version logic tests, as written, are possible. I can probably reproduce them in a unittest-setting though, as I want to plumb the binary's version information anyway (so that I can test mixed-version clusters too). Let's revisit once I've done that.

---

*[pkg/settings/cluster/settings.go, line 724 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411#-KrRHpn7fs_N3L3aiIou:-KrWJDSG3xGRUg2FA8HA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdae0bd9359ae022ee8c6411f13c0825d3364a0f/pkg/settings/cluster/settings.go#L724)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I think this may have been the only place we copy the Settings struct instead of passing a pointer. If so, Settings.Manual could just be an `atomic.Value` instead of a `*atomic.Value`. 
</blockquote></details>

Done.

---

*[pkg/storage/stores_test.go, line 354 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411#-KrRPhCAL-5XL34NWJUS:-KrWBoUFIGjAMIUkBYdN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdae0bd9359ae022ee8c6411f13c0825d3364a0f/pkg/storage/stores_test.go#L354)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Rename to match code.
</blockquote></details>

Done.

---

*[pkg/storage/stores_test.go, line 494 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411#-KrRPcJsA1JJMQixM0uF:-KrWBuid7XzbOjXtkSzg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdae0bd9359ae022ee8c6411f13c0825d3364a0f/pkg/storage/stores_test.go#L494)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Rename to match code.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 13 of 19 files at r5, 3 of 4 files at r8, 8 of 8 files at r9, 1 of 1 files at r10, 2 of 3 files at r11, 1 of 1 files at r12.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/settings/updater.go, line 54 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411#-KrX0z_U90ws_lsZxn6X:-KrX0z_VShdVpruaIYof:b-rv64ia) ([raw file](https://github.com/cockroachdb/cockroach/blob/89c61c93a7f89a46034eb3d5cf5b24cdc5a92af0/pkg/settings/updater.go#L54)):*
> ```Go
> // settings -- e.g. the rows read from the system.settings table. We update the
> // wrapped atomic settings values as we go and note which settings were updated,
> // then set the rest to default in Done().
> ```

This comment is outdated.

---

*[pkg/settings/cluster/cluster_version.go, line 24 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411#-KrRBuLkY5aqzZKpSp8D:-KrX2D_7HCl6WjUJfHuI:b-6e2nvl) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdae0bd9359ae022ee8c6411f13c0825d3364a0f/pkg/settings/cluster/cluster_version.go#L24)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

That works for me, though I'm curious why you prefer `VersionBase` over something that describes itself?
</blockquote></details>

`Version1_0` describes its *value*, `VersionBase` describes its *semantics* as the default value filled in for a cluster that predates the versioning scheme. I don't feel strongly about this distinction.

---

*[pkg/settings/cluster/cluster_version.go, line 38 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411#-KrRDIMsL-eBQeh95I9V:-KrX2Sl8FKbBqcXsSB2E:b-uhtoar) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdae0bd9359ae022ee8c6411f13c0825d3364a0f/pkg/settings/cluster/cluster_version.go#L38)):*
>  You're right that one could upgrade to 1.1 and then things get weird.

Or you can bootstrap a new cluster which will have its version set to 1.1 from the start. This will cause problems for the next `1.0-x` migration. 

---

*[pkg/settings/cluster/cluster_version.go, line 41 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411#-KrX2_ZC7VMxQAlzBwQx:-KrX2_ZC7VMxQAlzBwQy:bsf95cj) ([raw file](https://github.com/cockroachdb/cockroach/blob/89c61c93a7f89a46034eb3d5cf5b24cdc5a92af0/pkg/settings/cluster/cluster_version.go#L41)):*
> ```Go
> 
> 	// Version1_0_0_2SplitHardStateBelowRaft is https://github.com/cockroachdb/cockroach/pull/17051.
> 	Version1_0_0_2SplitHardStateBelowRaft = roachpb.Version{Major: 1, Minor: 0, Unstable: 2}
> ```

I don't think these should include their values. The "unstable" versions should just be the feature names. (the general principle is that where there is a semantic meaning, we should use that. Values like `Version1_1` are just markers for the releases that are always independent of any particular feature, so they have no semantics other than their value)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411#-:-KrX3v6c79aus0UDVTaz:bnfp4nl)*

**Comment by tschottdorf** [comment]
TFTR so far, PTAL! Added mixed cluster tests that also highlight some of the shortcomings. I don't think much is gained by blocking the resolution of those on this PR, so unless you think otherwise I'd like to (squash and) merge this and then start knocking down the TODO list.

---

Review status: 43 of 85 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/settings/updater.go, line 54 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411#-KrX0z_U90ws_lsZxn6X:-KrXtHWjk6LDmdv3Ix98:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/89c61c93a7f89a46034eb3d5cf5b24cdc5a92af0/pkg/settings/updater.go#L54)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This comment is outdated.
</blockquote></details>

Done.

---

*[pkg/settings/cluster/cluster_version.go, line 24 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411#-KrRBuLkY5aqzZKpSp8D:-KrXtW8ewy1NCRBaVpMu:b-g1hs4j) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdae0bd9359ae022ee8c6411f13c0825d3364a0f/pkg/settings/cluster/cluster_version.go#L24)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

`Version1_0` describes its *value*, `VersionBase` describes its *semantics* as the default value filled in for a cluster that predates the versioning scheme. I don't feel strongly about this distinction.
</blockquote></details>

Makes sense, done!

---

*[pkg/settings/cluster/cluster_version.go, line 38 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411#-KrRDIMsL-eBQeh95I9V:-KrXuDLS3lRAF7F6DIAH:b-gm2rqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdae0bd9359ae022ee8c6411f13c0825d3364a0f/pkg/settings/cluster/cluster_version.go#L38)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

>  You're right that one could upgrade to 1.1 and then things get weird.

Or you can bootstrap a new cluster which will have its version set to 1.1 from the start. This will cause problems for the next `1.0-x` migration. 
</blockquote></details>

Yeah, I'll back this out. I have sufficient coverage now to not have to rely on a logic test.

---

*[pkg/settings/cluster/cluster_version.go, line 41 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411#-KrX2_ZC7VMxQAlzBwQx:-KrXtZE8kvAbIqF0GxEu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/89c61c93a7f89a46034eb3d5cf5b24cdc5a92af0/pkg/settings/cluster/cluster_version.go#L41)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I don't think these should include their values. The "unstable" versions should just be the feature names. (the general principle is that where there is a semantic meaning, we should use that. Values like `Version1_1` are just markers for the releases that are always independent of any particular feature, so they have no semantics other than their value)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411#-:-KrXtb2KXoOhLqXoTf6E:b-52zdnr)*

**Comment by bdarnell** [comment]
LGTM. We should probably also have an acceptance test to make sure that it works even when the nodes aren't all living in one process.

---

Reviewed 10 of 26 files at r13, 2 of 4 files at r16, 13 of 17 files at r21, 2 of 5 files at r22, 6 of 10 files at r23, 1 of 3 files at r24, 2 of 2 files at r25, 3 of 4 files at r26, 1 of 3 files at r27.
Review status: 83 of 85 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17411#-:-Krb-_dq07ZED15WiFfM:bgcr5nl)*

**Comment by tschottdorf** [comment]
Yep, I'll add an acceptance test as I figure out the empty cluster table entry. For example, I *know* that the 1.0 binary will just discard the `version` setting when it sees it gossiped because I've checked the code, but I definitely don't know if everything else works.

TFTR!

**Pull request merged**
