### PR TITLE
sql: Keep compatible with postgres when parsing interval

### LINKED ISSUE #12503: sql: interval input format differs from Postgres
We currently expect intervals in the SQL standard input format to be of the form `Y-M-D HH:MM:SS` when parsing them. There seems to be some disagreement about what the SQL standard says about this - Postgres doesn't parse intervals of this form, instead expecting `Y-M D HH:MM:SS` - note the missing dash between the `M` and the `D`.

The documentation here http://www.ibm.com/support/knowledgecenter/SSGU8G_12.1.0/com.ibm.esqlc.doc/ids_esqlc_0190.htm is also kind of confusing - both syntaxes are listed.  You can see why Postgres would expect no dash, because there are almost two separate input formats - `Y-M` and `D HH:MM:SS`.

I think we should accept both formats at minimum since we're aiming for Postgres compatibility. I would also be ok with not allowing `Y-M-D` format since Postgres doesn't.

### PR DESCRIPTION
**Pull request by hainesc**
Fixes #12503

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12559)

### CODE REVIEW

**Comment by hainesc** [comment]
Almost 100% compatible with postgres except that
```sql
# Not support but in postgres it results 01:02:00
select ':1:2'::interval;  
# Bad order but in postgres it results 1 year 2 mons 3 days 04:05:06
select '3 4:5:6 1-2'::interval;  
# Float value in day will be truncated but in postgres it results 1 year 2 mons 3 days 16:05:06.
# The 0.5 day = 12 hour has beed added to 4:5:6
select '3.5 4:5:6'::interval;  
```

**Comment by knz** [comment]
Thank you for tackling this. Much appreciated.
It's mostly good, just a few comments remaining.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/datum.go, line 1229 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12559#-KZf3IywpccCX4CLCWGs:-KZf3IywpccCX4CLCWGt:byeexh7) ([raw file](https://github.com/cockroachdb/cockroach/blob/98b1c115c7a62e9b8a7eaa31d43598f972089eed/pkg/sql/parser/datum.go#L1229)):*
> ```Go
> 		}
> 		return ret, nil
> 	} else if match, _ := regexp.MatchString("[a-zA-Z]+", s); !match {
> ```

Don't do regular expressions if you're just testing for letters. Use either `strings.IndexAny`, or `strings.IndexFunc` with `unicode.IsLetter`.

---

*[pkg/sql/parser/interval.go, line 126 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12559#-KZf4Bk4UymERkl1XLVw:-KZf4Bk5q8bLZyRvHGjb:b-2xg4dc) ([raw file](https://github.com/cockroachdb/cockroach/blob/98b1c115c7a62e9b8a7eaa31d43598f972089eed/pkg/sql/parser/interval.go#L126)):*
> ```Go
> 	// 2 for day parsed
> 	// 3 for year-month parsed
> 	var parsedIndex uint8
> ```

Make an enum for this.

---

*[pkg/sql/parser/interval.go, line 150 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12559#-KZf5CPg5R-FyebFVm-g:-KZf5CPg5R-FyebFVm-h:b9544gh) ([raw file](https://github.com/cockroachdb/cockroach/blob/98b1c115c7a62e9b8a7eaa31d43598f972089eed/pkg/sql/parser/interval.go#L150)):*
> ```Go
> 		}
> 
> 		if strings.ContainsRune(part, ':') {
> ```

I would suggest moving the two branches of this `if` to separate functions.

---

*[pkg/sql/parser/interval.go, line 176 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12559#-KZf53GK3OPw_2RhfGaq:-KZf53GK3OPw_2RhfGar:bcg2vso) ([raw file](https://github.com/cockroachdb/cockroach/blob/98b1c115c7a62e9b8a7eaa31d43598f972089eed/pkg/sql/parser/interval.go#L176)):*
> ```Go
> 			case 2:
> 				if neg {
> 					dur, err = time.ParseDuration("-" + hms[0] + "h" + hms[1] + "m")
> ```

```
toParse := hms[0] + "h" + hms[1] + "m"
if neg {
   toParse = "-" + toParse
}
dur, err = ...
```

---

*[pkg/sql/parser/interval.go, line 188 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12559#-KZf5868EKFsXAIUjKV0:-KZf5868EKFsXAIUjKV1:byr4ffv) ([raw file](https://github.com/cockroachdb/cockroach/blob/98b1c115c7a62e9b8a7eaa31d43598f972089eed/pkg/sql/parser/interval.go#L188)):*
> ```Go
> 				}
> 				if neg {
> 					dur, err = time.ParseDuration("-" + hms[0] + "h" + hms[1] + "m" + hms[2] + "s")
> ```

see above

---

*[pkg/sql/parser/interval.go, line 217 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12559#-KZf4qSho_edYLw9dJTH:-KZf4qSho_edYLw9dJTI:bdi21q3) ([raw file](https://github.com/cockroachdb/cockroach/blob/98b1c115c7a62e9b8a7eaa31d43598f972089eed/pkg/sql/parser/interval.go#L217)):*
> ```Go
> 			}
> 			if errYear == nil && errMonth == nil {
> 				if neg {
> ```

```
delta := duration.Duration{Months: 1}.Mul(int64(year)*12 + int64(month))
if neg {
   d = d.Sub(delta)
} else {
   d = d.Add(delta)
}
```

---

*[pkg/sql/parser/interval.go, line 237 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12559#-KZf4d3AOgjFOMSWGfUg:-KZf4d3BgKFjqxo66xzo:b-mr3h2) ([raw file](https://github.com/cockroachdb/cockroach/blob/98b1c115c7a62e9b8a7eaa31d43598f972089eed/pkg/sql/parser/interval.go#L237)):*
> ```Go
> 			if parsedIndex == 0 {
> 				// It must be 'Second' part because nothing has been parsed.
> 				if neg {
> ```

```
toParse := part + s
if neg {
   toParse = "-" + toParse
}
dur, err = ...
```

---

*[pkg/sql/parser/interval.go, line 252 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12559#-KZf4y7vSNWVu3JLfTNM:-KZf4y7vSNWVu3JLfTNN:b-2ueiss) ([raw file](https://github.com/cockroachdb/cockroach/blob/98b1c115c7a62e9b8a7eaa31d43598f972089eed/pkg/sql/parser/interval.go#L252)):*
> ```Go
> 				// TODO(hainesc): support float value in day part?
> 				if neg {
> 					d = d.Sub(duration.Duration{Days: 1}.Mul(int64(value)))
> ```

Factor this (see previous comment)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12559#-:-KZf5Lr5k_v-P8LZqyTO:bkppfhk)*

**Comment by hainesc** [comment]
Review status: 3 of 5 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[pkg/sql/parser/datum.go, line 1229 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12559#-KZf3IywpccCX4CLCWGs:-KZfHdKkk53_0OkmsHKV:b7kvf5w) ([raw file](https://github.com/cockroachdb/cockroach/blob/98b1c115c7a62e9b8a7eaa31d43598f972089eed/pkg/sql/parser/datum.go#L1229)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Don't do regular expressions if you're just testing for letters. Use either `strings.IndexAny`, or `strings.IndexFunc` with `unicode.IsLetter`.
</blockquote></details>

strings.ContainsAny seems better, thanks a lot.

---

*[pkg/sql/parser/interval.go, line 126 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12559#-KZf4Bk4UymERkl1XLVw:-KZfI0jr8dhFW4RHm7Ll:b-ido4d0) ([raw file](https://github.com/cockroachdb/cockroach/blob/98b1c115c7a62e9b8a7eaa31d43598f972089eed/pkg/sql/parser/interval.go#L126)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Make an enum for this.
</blockquote></details>

Good suggestion.

---

*[pkg/sql/parser/interval.go, line 150 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12559#-KZf5CPg5R-FyebFVm-g:-KZfIb7rA0Grtfe3ndNj:b-6h3byv) ([raw file](https://github.com/cockroachdb/cockroach/blob/98b1c115c7a62e9b8a7eaa31d43598f972089eed/pkg/sql/parser/interval.go#L150)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I would suggest moving the two branches of this `if` to separate functions.
</blockquote></details>

It seems a long function but 20 lines out of 50 lines are comments. And more, it is not general because it needs parsedIndex as parameter. I would not like a separate function, is that OK?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12559)*

**Comment by hainesc** [comment]
Review status: 3 of 5 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/datum.go, line 1229 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12559#-KZf3IywpccCX4CLCWGs:-KZfs22WrlSlGlCQ85KL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/98b1c115c7a62e9b8a7eaa31d43598f972089eed/pkg/sql/parser/datum.go#L1229)):*
<details><summary><i>Previously, hainesc (Haines Chan) wrote…</i></summary><blockquote>

strings.ContainsAny seems better, thanks a lot.
</blockquote></details>

Done.

---

*[pkg/sql/parser/interval.go, line 126 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12559#-KZf4Bk4UymERkl1XLVw:-KZfs0VBb3SQiiBqzUMc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/98b1c115c7a62e9b8a7eaa31d43598f972089eed/pkg/sql/parser/interval.go#L126)):*
<details><summary><i>Previously, hainesc (Haines Chan) wrote…</i></summary><blockquote>

Good suggestion.
</blockquote></details>

Done.

---

*[pkg/sql/parser/interval.go, line 150 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12559#-KZf5CPg5R-FyebFVm-g:-KZfs4RMklq7cqc0vPgb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/98b1c115c7a62e9b8a7eaa31d43598f972089eed/pkg/sql/parser/interval.go#L150)):*
<details><summary><i>Previously, hainesc (Haines Chan) wrote…</i></summary><blockquote>

It seems a long function but 20 lines out of 50 lines are comments. And more, it is not general because it needs parsedIndex as parameter. I would not like a separate function, is that OK?
</blockquote></details>

Done.

---

*[pkg/sql/parser/interval.go, line 176 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12559#-KZf53GK3OPw_2RhfGaq:-KZfs74eykmvOEhSeUpC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/98b1c115c7a62e9b8a7eaa31d43598f972089eed/pkg/sql/parser/interval.go#L176)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

```
toParse := hms[0] + "h" + hms[1] + "m"
if neg {
   toParse = "-" + toParse
}
dur, err = ...
```
</blockquote></details>

Done.

---

*[pkg/sql/parser/interval.go, line 188 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12559#-KZf5868EKFsXAIUjKV0:-KZfsBW8XOjSxkKuVv2L:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/98b1c115c7a62e9b8a7eaa31d43598f972089eed/pkg/sql/parser/interval.go#L188)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.

---

*[pkg/sql/parser/interval.go, line 217 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12559#-KZf4qSho_edYLw9dJTH:-KZfsD5gq0tPKmYbX3jX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/98b1c115c7a62e9b8a7eaa31d43598f972089eed/pkg/sql/parser/interval.go#L217)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

```
delta := duration.Duration{Months: 1}.Mul(int64(year)*12 + int64(month))
if neg {
   d = d.Sub(delta)
} else {
   d = d.Add(delta)
}
```
</blockquote></details>

Done.

---

*[pkg/sql/parser/interval.go, line 237 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12559#-KZf4d3AOgjFOMSWGfUg:-KZfsFSfq9u84xNQgFKc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/98b1c115c7a62e9b8a7eaa31d43598f972089eed/pkg/sql/parser/interval.go#L237)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

```
toParse := part + s
if neg {
   toParse = "-" + toParse
}
dur, err = ...
```
</blockquote></details>

Done.

---

*[pkg/sql/parser/interval.go, line 252 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12559#-KZf4y7vSNWVu3JLfTNM:-KZfsGMttt8eYF4a_9qz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/98b1c115c7a62e9b8a7eaa31d43598f972089eed/pkg/sql/parser/interval.go#L252)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Factor this (see previous comment)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12559)*

**Comment by knz** [comment]
Thanks again.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/datum.go, line 1229 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12559#-KZf3IywpccCX4CLCWGs:-KZg47EBTDj7a0oVY73b:by7llct) ([raw file](https://github.com/cockroachdb/cockroach/blob/98b1c115c7a62e9b8a7eaa31d43598f972089eed/pkg/sql/parser/datum.go#L1229)):*
<details><summary><i>Previously, hainesc (Haines Chan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm ok with this, but just so you know IndexFunc with unicode.IsLetter is probably faster because it does not need to scan the entire `letters` array every time it encounters (say) a `z`. 
But it's good either way. Thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12559#-:-KZg4b_fEJdL3pxT3-6E:bkuo2kg)*

**Comment by knz** [comment]
I think this is good to go but I'm asking one of the other guys to double check.

**Comment by hainesc** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/datum.go, line 1229 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12559#-KZf3IywpccCX4CLCWGs:-KZgFV1yGP1nSuHi5Jxv:b6y6tub) ([raw file](https://github.com/cockroachdb/cockroach/blob/98b1c115c7a62e9b8a7eaa31d43598f972089eed/pkg/sql/parser/datum.go#L1229)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I'm ok with this, but just so you know IndexFunc with unicode.IsLetter is probably faster because it does not need to scan the entire `letters` array every time it encounters (say) a `z`. 
But it's good either way. Thanks

</blockquote></details>

Thanks a lot. To me I think `strings.IndexFunc` with `unicode.IsLetter` is better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12559)*

**Comment by hainesc** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/parser/datum.go, line 1229 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12559#-KZf3IywpccCX4CLCWGs:-KZgKZL-r376gfpUsryK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/98b1c115c7a62e9b8a7eaa31d43598f972089eed/pkg/sql/parser/datum.go#L1229)):*
<details><summary><i>Previously, hainesc (Haines Chan) wrote…</i></summary><blockquote>

Thanks a lot. To me I think `strings.IndexFunc` with `unicode.IsLetter` is better.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12559)*

**Review by jordanlewis — APPROVED** [review]
LGTM - thank you very much for fixing this issue.

**Comment by knz** [comment]
Thanks for your contribution!

**Pull request merged**
