### PR TITLE
sql: remove heuristic planner optimization passes

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### sql: don't use optimizePlan for scrub check

The physical scrub code uses optimizePlan simply to initialize the
span in a scanNode; do that directly instead.

Release note: None

#### sql: remove heuristic planner optimization passes

Removing the "optimization" part of the heuristic planner, and any
code that becomes unused.

We still keep the limit propagation pass; it will go away when the
optimizer has intelligence around soft limits.

A small fix that happened naturally is to propagate limits on
`EXPLAIN` which more accurately reflects the actual execution.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
So much code deletion!!!

**Comment by knz** [comment]
This is great. Next step is to remove planNode altogether! 

(not reviewing in detail because I've lost touch of the specifics. But I'm 100% behind the change.)

**Comment by RaduBerinde** [comment]
Thanks! Yeah, I started trying to rip out the planning part (`makePlan`) altogether but hit a few roadblocks and it was easier to start a bit smaller.

**Review by jordanlewis — APPROVED** [review]
:lgtm_strong: 

Wow this is the dream!!1

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39766#-:-Lmk-lz07MHpAww_LPii:b-w9urq3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @knz, and @RaduBerinde)

___
*[pkg/sql/scan.go, line 469 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39766#-Lmk-apqDlDU0mGwytlv:-Lmk-apqDlDU0mGwytlw:bdyqltm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ea9427a8097e72f11bd3a561475c8dbae4bc9b4/pkg/sql/scan.go#L469)):*
> ```Go
> }
> 
> func isFilterTrue(expr tree.TypedExpr) bool {
> ```

nit: this feels random, any reason why it doesn't live next to its use in join_predicate?

**Review by jordanlewis — COMMENTED** [review]
Haha I didn't mean to put that sarcastic looking trailing 1 - only sincere happiness from me!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39766#-:-Lmk-oxL72ewO8Kef7zf:bvfkjr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @knz, and @RaduBerinde)

**Review by RaduBerinde — COMMENTED** [review]
Haha, TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39766#-:-Lmk76qB6NCZ-XlYs5RK:b5m4m12)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @knz)

___
*[pkg/sql/scan.go, line 469 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39766#-Lmk-apqDlDU0mGwytlv:-Lmk6ippBCsfIFyCBYK4:b-80z5o7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ea9427a8097e72f11bd3a561475c8dbae4bc9b4/pkg/sql/scan.go#L469)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: this feels random, any reason why it doesn't live next to its use in join_predicate?
</blockquote></details>

It's also used in this file. I believe the use in `join_predicate` will also go away soon. I moved it to `opt_limits.go` since it's used there more and the scanNode use is also related to limits.

**Pull request merged**
