### PR TITLE
rac2: return tracked deductions on close/removal

### LINKED ISSUE #130679: kv/kvserver/kvflowcontrol/rac2: TestRangeController failed
kv/kvserver/kvflowcontrol/rac2.TestRangeController [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/16873663?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/16873663?buildTab=artifacts#/) on master @ [40b449ac9639b6f364c17659c33bf37d96c1ff51](https://github.com/cockroachdb/cockroach/commits/40b449ac9639b6f364c17659c33bf37d96c1ff51):

```
          store_id=1 replica_id=1 type=VOTER_FULL state=StateReplicate
          store_id=2 replica_id=2 type=VOTER_FULL state=StateReplicate
          store_id=3 replica_id=3 type=VOTER_FULL state=StateProbe
        ----
        r1: [(n1,s1):1*,(n2,s2):2,(n3,s3):3]
    datadriven.go:144: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/9622/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/kv/kvserver/kvflowcontrol/rac2/rac2_test_/rac2_test.runfiles/com_github_cockroachdb_cockroach/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/handle_raft_event:99:
        tick [1 args]
        <no input to command>
        ----
        now=500ms
    datadriven.go:144: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/9622/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/kv/kvserver/kvflowcontrol/rac2/rac2_test_/rac2_test.runfiles/com_github_cockroachdb_cockroach/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/handle_raft_event:103:
        stream_state [1 args]
        <no input to command>
        ----
        (n1,s1):1: state=replicate closed=false
        ++++
        (n2,s2):2: state=replicate closed=false
        ++++
        (n3,s3):3: state=probeRecentlyReplicate closed=false
        NormalPri:
          term=1 index=1  tokens=1048576
          term=1 index=2  tokens=1048576
          term=1 index=3  tokens=1048576
        ++++
    datadriven.go:144: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/9622/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/kv/kvserver/kvflowcontrol/rac2/rac2_test_/rac2_test.runfiles/com_github_cockroachdb_cockroach/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/handle_raft_event:118:
        tick [1 args]
        <no input to command>
        ----
        now=1s
    datadriven.go:144: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/9622/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/kv/kvserver/kvflowcontrol/rac2/rac2_test_/rac2_test.runfiles/com_github_cockroachdb_cockroach/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/handle_raft_event:122:
         
        output didn't match expected:
        @@ -1,6 +1,11 @@
         (n1,s1):1: state=replicate closed=false
         ++++
         (n2,s2):2: state=replicate closed=false
         ++++
        -(n3,s3):3: closed
        +(n3,s3):3: state=probeRecentlyReplicate closed=false
        +NormalPri:
        +  term=1 index=1  tokens=1048576
        +  term=1 index=2  tokens=1048576
        +  term=1 index=3  tokens=1048576
        +++++
         
    --- FAIL: TestRangeController/handle_raft_event (0.08s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/storage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRangeController.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-42179

### LINKED ISSUE #130683: rac2: removing replica or closing range controller should return relevant tracked deduction
Currently the `RangeController` will not return any tracked deductions when `CloseRaftMuLocked` is called, or when `SetReplicasRaftMuLocked` is called, and a replica is removed from the replica set. They should.

### PR DESCRIPTION
**Pull request by kvoli**
When a replica was removed from a range, or the range controller closed, any tracked deductions did not return tokens to the respective stream token counts.

Update `CloseRaftMuLocked` and `SetReplicasRaftMuLocked` to close any replica send streams for replicas which are no longer part of the replica set, closing all when the range controller closes.

Also immediately close the send stream when a replica transitions to StateSnapshot.

Resolves: #130683
Release note: None

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130684#-:-O6g8MxT33_HynFevMNp:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 780 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130684#-O6g7yHC7gafp2q6wgk1:-O6g7yHC7gafp2q6wgk2:b-spmqzg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b24d6922e74ca5edd66f8959b1d8756a85d244e1/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L780)):*
> ```Go
> 			}() {
> 			case replicate, probeRecentlyReplicate:
> 				rs.closeSendStream(ctx)
> ```

This change is already doing part of the cleanup from https://github.com/cockroachdb/cockroach/pull/130168 which eliminated `snapshot` `connectedState`. May as well do this now, instead of leaving cruft like `changeToStateSnapshot{Locked}` around.

**Review by kvoli — COMMENTED** [review]
TYFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130684#-:-O6gLlWL6S6BZOa8-CX5:bzftgo7)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kvoli and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 780 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130684#-O6g7yHC7gafp2q6wgk1:-O6gLfJABkD9J3aYjHDY:b7sr6fl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b24d6922e74ca5edd66f8959b1d8756a85d244e1/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L780)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This change is already doing part of the cleanup from https://github.com/cockroachdb/cockroach/pull/130168 which eliminated `snapshot` `connectedState`. May as well do this now, instead of leaving cruft like `changeToStateSnapshot{Locked}` around.
</blockquote></details>

Yeah good idea, did the snapshot cleanup and delayed stream init now.

**Comment by kvoli** [comment]
```
=== RUN   TestLint/TestStaticCheck
    gen-lint_test.go:2079: 
        pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go:879:26: func connectedState.shouldWaitForElasticEvalTokens is unused (U1000)
    --- FAIL: TestLint/TestStaticCheck (1331.12s)
```

rm'd this function and pushed an amended the commit.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 3 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130684#-:-O6gYE8X5f0Nohhnnnd7:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

**Comment by kvoli** [comment]
TYFTR!

bors r=sumeerbhola

**Pull request merged**
