### PR TITLE
ui: allow SetUIData to set/update multiple keys

### PR DESCRIPTION
**Pull request by cuongdo**
This changes SetUIData so that instead of taking a single key & value
to store in system.uidata, it now takes a map of keys to values. This
allows the admin UI to set multiple pieces of uidata with a single HTTP
round-trip.

One motivation for this change is to allow the admin UI to store several
pieces of data individually, so that the server can access specific
fields without having to parse JSON.

cc @mrtracy, @maxlang for TS changes

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5532)

### CODE REVIEW

**Comment by maxlang** [comment]
Typescript LGTM.

Just a head's up this might have a minor conflict with https://github.com/cockroachdb/cockroach/pull/5485

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/admin.proto, line 185 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5532#-KDdbkqNLWWlthuVvQeR:-KDdbkqNLWWlthuVvQeS:1772658675) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8cd9343f396e0bdcf284533653f7ae35035585a/server/admin.proto#L185)):*
stale comment

---

*[server/admin.proto, line 188 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5532#-KDdbe-YEMov9ZUGa8tD:-KDdbe-YEMov9ZUGa8tE:1859346618) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8cd9343f396e0bdcf284533653f7ae35035585a/server/admin.proto#L188)):*
s/vaulue/value/

---

*[server/admin_test.go, line 545 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5532#-KDdcetvhlMiAZMOuEdp:-KDdcetvhlMiAZMOuEdq:-449865317) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8cd9343f396e0bdcf284533653f7ae35035585a/server/admin_test.go#L545)):*
`err` might be nil, so you want `%v` here

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5532#-:-KDdcofkWyfhN6a_lAjc:1417088721)*

**Comment by cuongdo** [comment]
Review status: 1 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/admin.proto, line 185 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5532#-KDdbkqNLWWlthuVvQeR:-KDdfnpbsI8urFja_BFc:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8cd9343f396e0bdcf284533653f7ae35035585a/server/admin.proto#L185)):*
Done.

---

*[server/admin.proto, line 188 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5532#-KDdbe-YEMov9ZUGa8tD:-KDdgRB9uk9LX82TDEjO:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8cd9343f396e0bdcf284533653f7ae35035585a/server/admin.proto#L188)):*
Done.

---

*[server/admin_test.go, line 545 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5532#-KDdcetvhlMiAZMOuEdp:-KDdgXgSYqH-Y4C2ZURw:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8cd9343f396e0bdcf284533653f7ae35035585a/server/admin_test.go#L545)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5532)*

**Comment by tamird** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5532)*

**Pull request merged**
