### PR TITLE
opt: fix logical properties calculation for locality optimized join

### PR DESCRIPTION
**Pull request by rytaft**
This commit fixes a bug when calculating the logical properties for a locality optimized lookup join where we would incorrectly determine that the `crdb_region` column was constant. In fact, `crdb_region` is only constant in the local lookup expr of the join; the remote lookup expr contains one or more other possible values for this column.

I don't know of any actual incorrect results caused by this issue, so I'm not setting a release note. However, incorrect logical properties are always bad and can in theory cause incorrect results.

Epic: None
Release note: None

### CODE REVIEW

**Comment by rytaft** [comment]
*[`pkg/sql/opt/memo/logical_props_builder.go` line 2304 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95713#-NMWjFgeAeX6wAAnyX-P:-NMWjFgeAeX6wAAnyX-Q:bnfnl3) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe3cacccc4ae4632e33f5455264af2c57e9475ab/pkg/sql/opt/memo/logical_props_builder.go#L2304)):*
> ```Go
> 			// logic similar to FindRedundantConjunct and ExtractRedundantConjunct
> 			// from the norm package. But that seems like overkill until we have a
> 			// compelling reason to.
> ```

I realize if I want to backport this change I may need to address this... thoughts? It shouldn't be that hard, just feels like overkill for logical props calculation. But maybe it's worth it to avoid any plan changes.

**Review by msirek — COMMENTED** [review]
Great find! I'm curious how you noticed this.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95713#-:-NMXUpgJDHYPYxyZhjUO:b-1oes0i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/memo/logical_props_builder.go` line 2304 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95713#-NMWjFgeAeX6wAAnyX-P:-NMXTZvH6QRi21hBjs_E:b-v3uusm) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe3cacccc4ae4632e33f5455264af2c57e9475ab/pkg/sql/opt/memo/logical_props_builder.go#L2304)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I realize if I want to backport this change I may need to address this... thoughts? It shouldn't be that hard, just feels like overkill for logical props calculation. But maybe it's worth it to avoid any plan changes.
</blockquote></details>

It's only `join.LookupExpr` and `join.RemoteLookupExpr` that need to be constructed without normalization rules, not `h.filters`, right? So, can we just call `ConstructAnd` and `ConstructOr` instead of `MemoizeAnd` and `MemoizeOr`? I don't see these latter functions called directly anywhere else.

**Comment by rytaft** [comment]
*[`pkg/sql/opt/memo/logical_props_builder.go` line 2304 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95713#-NMWjFgeAeX6wAAnyX-P:-NMZDCxDCdMwkg6jlS1j:b-h3fomq) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe3cacccc4ae4632e33f5455264af2c57e9475ab/pkg/sql/opt/memo/logical_props_builder.go#L2304)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

It's only `join.LookupExpr` and `join.RemoteLookupExpr` that need to be constructed without normalization rules, not `h.filters`, right? So, can we just call `ConstructAnd` and `ConstructOr` instead of `MemoizeAnd` and `MemoizeOr`? I don't see these latter functions called directly anywhere else. 
</blockquote></details>

The problem is we don't have access to the factory inside the memo package

**Review by rytaft — COMMENTED** [review]
Thanks for taking a look! I noticed it when I was playing around with adding a rule to eliminate unnecessary lookup joins under a project (I haven't actually opened a PR for this since it also requires calculating multiplicity for lookup joins, and it didn't seem worth it for now).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95713#-:-NMZDJ5q-0L-QKjhYg23:b-6z1dxq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @msirek)

**Comment by rytaft** [comment]
*[`pkg/sql/opt/memo/logical_props_builder.go` line 2304 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95713#-NMWjFgeAeX6wAAnyX-P:-NMZDrEl7UxTsijU9PEB:bbz3bv7) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe3cacccc4ae4632e33f5455264af2c57e9475ab/pkg/sql/opt/memo/logical_props_builder.go#L2304)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

The problem is we don't have access to the factory inside the memo package
</blockquote></details>

And actually I *do* want to apply normalization rules to extract the redundant conjuncts, but I think I'll need to just add some custom logic to do it instead.

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95713)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @msirek)

___
*[`pkg/sql/opt/memo/logical_props_builder.go` line 2304 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95713#-NMWjFgeAeX6wAAnyX-P:-NManxVXEcgSea348htK:b-nopd7m) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe3cacccc4ae4632e33f5455264af2c57e9475ab/pkg/sql/opt/memo/logical_props_builder.go#L2304)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

And actually I *do* want to apply normalization rules to extract the redundant conjuncts, but I think I'll need to just add some custom logic to do it instead.
</blockquote></details>

Fixed this. PTAL.

**Review by msirek — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95713)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/memo/logical_props_builder.go` line 2412 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95713#-NMavVGA8vz-SDZCeMzY:-NMavVGA8vz-SDZCeMzZ:bejvmcv) ([raw file](https://github.com/cockroachdb/cockroach/blob/46073a45e0ceceeeca78c5783ffae0d10edba89d/pkg/sql/opt/memo/logical_props_builder.go#L2412)):*
> ```Go
> 
> // extractRedundantFilters extracts filters that exist in both left and right.
> func extractRedundantFilters(left, right FiltersExpr) FiltersExpr {
> ```

This isn't really extracting filters because they're not being removed from `left` and `right`. Consider renaming it to `findRedundantFilters`, or something similar. I guess there's no benefit to removing the redundant conjuncts from the `lookupExpr` and `remoteLookupExpr` `AndExpr`s, is there?
___
*[`pkg/sql/opt/memo/logical_props_builder.go` line 2418 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95713#-NMaun3ZCCO3IypkTFMz:-NMaun3ZCCO3IypkTFN-:undefined) ([raw file](https://github.com/cockroachdb/cockroach/blob/46073a45e0ceceeeca78c5783ffae0d10edba89d/pkg/sql/opt/memo/logical_props_builder.go#L2418)):*
> ```Go
> 		for j := range right {
> 			if right[j].Condition == cond {
> 				redundant = append(redundant, left[i])
> ```

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95713)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @msirek)

___
*[`pkg/sql/opt/memo/logical_props_builder.go` line 2412 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95713#-NMavVGA8vz-SDZCeMzY:-NMdxCPp5jOQtfQ4GBLG:b-1uqrhp) ([raw file](https://github.com/cockroachdb/cockroach/blob/46073a45e0ceceeeca78c5783ffae0d10edba89d/pkg/sql/opt/memo/logical_props_builder.go#L2412)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

This isn't really extracting filters because they're not being removed from `left` and `right`. Consider renaming it to `findRedundantFilters`, or something similar. I guess there's no benefit to removing the redundant conjuncts from the `lookupExpr` and `remoteLookupExpr` `AndExpr`s, is there?
</blockquote></details>

Good point, done. Yea, it didn't seem worth the extra code/computation to remove the redundant copies from lookupExpr and remoteLookupExpr, since it's not needed to get the correct FDs.

**Review by msirek — APPROVED** [review]

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95713)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek and @rytaft)

___
*[`pkg/sql/opt/memo/logical_props_builder.go` line 2304 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95713#-NMWjFgeAeX6wAAnyX-P:-NMeJHQQDPpf87nZlUUm:b-ee3c5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe3cacccc4ae4632e33f5455264af2c57e9475ab/pkg/sql/opt/memo/logical_props_builder.go#L2304)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Fixed this. PTAL.
</blockquote></details>

Can we reuse `ConstFilters` for this purpose? They seem to serve a similar purpose. We could rename it `LogicalFilters` (or something) and use it for both statistics estimation and building logical properties. That way you wouldn't need to construct these conjunctions and disjunctions in the logical props builder. It would require that `LogicalFilters` were built correctly in xform rules, but a helper function might simplify that.

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95713)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @msirek)

___
*[`pkg/sql/opt/memo/logical_props_builder.go` line 2304 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95713#-NMWjFgeAeX6wAAnyX-P:-NMpWO7V1c9BA47uyblg:b55g1bi) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe3cacccc4ae4632e33f5455264af2c57e9475ab/pkg/sql/opt/memo/logical_props_builder.go#L2304)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can we reuse `ConstFilters` for this purpose? They seem to serve a similar purpose. We could rename it `LogicalFilters` (or something) and use it for both statistics estimation and building logical properties. That way you wouldn't need to construct these conjunctions and disjunctions in the logical props builder. It would require that `LogicalFilters` were built correctly in xform rules, but a helper function might simplify that.
</blockquote></details>

Good idea. It adds a little more complexity in some other places, but I think it's worth it. PTAL.

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95713)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/xform/join_funcs.go` line 773 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/95713#-NMpZp6K1bayaxbOV0w3:-NMpZp6L-Nca8FyjEITz:b-q1np4j) ([raw file](https://github.com/cockroachdb/cockroach/blob/aecdde98580fed8745428a1b8f9e851d5658e276/pkg/sql/opt/xform/join_funcs.go#L773)):*
> ```Go
> 	lookupJoin.Cols = lookupJoin.Cols.CopyAndMaybeRemap(srcColsToDstCols)
> 	allLookupFilters := c.e.f.RemapCols(&lookupJoin.AllLookupFilters, srcColsToDstCols).(*memo.FiltersExpr)
> 	lookupJoin.AllLookupFilters = *allLookupFilters
> ```

If the remapped filters are normalized, but the original filters are not, could we get different results from stats after remapping?

Maybe we should disable optimizations for the column remapping here and in `mapInputSideOfLookupJoin`, as is done when originally constructed, e.g.:
https://github.com/cockroachdb/cockroach/blob/aecdde98580fed8745428a1b8f9e851d5658e276/pkg/sql/opt/lookupjoin/constraint_builder.go#L331-L340

Or, would we want to build a normalized version of the original filters, and save that in `lookupJoin.AllLookupFilters`?

**Comment by rytaft** [comment]
*[`pkg/sql/opt/xform/join_funcs.go` line 773 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/95713#-NMpZp6K1bayaxbOV0w3:-NMpdFwOBATovKwu1Mgy:b-mf4dtp) ([raw file](https://github.com/cockroachdb/cockroach/blob/aecdde98580fed8745428a1b8f9e851d5658e276/pkg/sql/opt/xform/join_funcs.go#L773)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

If the remapped filters are normalized, but the original filters are not, could we get different results from stats after remapping?

Maybe we should disable optimizations for the column remapping here and in `mapInputSideOfLookupJoin`, as is done when originally constructed, e.g.:
https://github.com/cockroachdb/cockroach/blob/aecdde98580fed8745428a1b8f9e851d5658e276/pkg/sql/opt/lookupjoin/constraint_builder.go#L331-L340

Or, would we want to build a normalized version of the original filters, and save that in `lookupJoin.AllLookupFilters`?
</blockquote></details>

I think it's better if it's normalized -- I updated constraint_builder

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95713)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/xform/join_funcs.go` line 773 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/95713#-NMpZp6K1bayaxbOV0w3:-NMqgRTl4u_cRKACvJYO:bnfmyfh) ([raw file](https://github.com/cockroachdb/cockroach/blob/aecdde98580fed8745428a1b8f9e851d5658e276/pkg/sql/opt/xform/join_funcs.go#L773)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think it's better if it's normalized -- I updated constraint_builder
</blockquote></details>

OK. `ConstraintBuilder.findJoinConstantRangeFilter` is also building unnormalized filters that end up in `lookupJoin.AllLookupFilters`.  It may need to also return a normalized version of `rangeFilter`.

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95713)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @msirek)

___
*[`pkg/sql/opt/xform/join_funcs.go` line 773 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/95713#-NMpZp6K1bayaxbOV0w3:-NN2PBg-1GRYCN5TIqfu:b2dlsq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/aecdde98580fed8745428a1b8f9e851d5658e276/pkg/sql/opt/xform/join_funcs.go#L773)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

OK. `ConstraintBuilder.findJoinConstantRangeFilter` is also building unnormalized filters that end up in `lookupJoin.AllLookupFilters`.  It may need to also return a normalized version of `rangeFilter`.
</blockquote></details>

Done. Thanks for the thorough review!

**Review by msirek — COMMENTED** [review]
> Reviewed 4 of 6 files at r4, 1 of 1 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95713)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[`pkg/sql/opt/xform/join_funcs.go` line 773 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/95713#-NMpZp6K1bayaxbOV0w3:-NN2heFf-UiJiKIucgqj:bb6ywmx) ([raw file](https://github.com/cockroachdb/cockroach/blob/aecdde98580fed8745428a1b8f9e851d5658e276/pkg/sql/opt/xform/join_funcs.go#L773)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Done. Thanks for the thorough review!
</blockquote></details>

LGTM
___
*[`pkg/sql/opt/xform/join_funcs.go` line 1329 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/95713#-NN2mRRn8UXCLpzo9exo:-NN2mRRn8UXCLpzo9exp:b-n0boaj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a910c7148a370aca45049f42eef8d2a63f35ba9e/pkg/sql/opt/xform/join_funcs.go#L1329)):*
> ```Go
> 		// into two separate operators. Note that only lookupExpr is used for anti
> 		// joins, not remoteLookupExpr.
> 		newPrivate.AllLookupFilters = append(newPrivate.AllLookupFilters, lookupExpr...)
> ```

Since `CreateLocalityOptimizedLookupJoinPrivate` is called above, won't newPrivate.AllLookupFilters already contain the filters in `lookupExpr`?

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95713)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek)

___
*[`pkg/sql/opt/xform/join_funcs.go` line 1329 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/95713#-NN2mRRn8UXCLpzo9exo:-NN2xiZ04Ohxk84WDRs5:b-376vyo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a910c7148a370aca45049f42eef8d2a63f35ba9e/pkg/sql/opt/xform/join_funcs.go#L1329)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Since `CreateLocalityOptimizedLookupJoinPrivate` is called above, won't newPrivate.AllLookupFilters already contain the filters in `lookupExpr`?
</blockquote></details>

Done. Good catch!

**Review by msirek — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95713)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[`pkg/sql/opt/xform/join_funcs.go` line 1329 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/95713#-NN2mRRn8UXCLpzo9exo:-NN2yMS_D0xw1hm0aEuI:bb6ywmx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a910c7148a370aca45049f42eef8d2a63f35ba9e/pkg/sql/opt/xform/join_funcs.go#L1329)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Done. Good catch!
</blockquote></details>

LGTM

**Review by rytaft — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95713#-:-NMpX9RaB-gMj-M0XiP5:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek)

**Review by mgartner — APPROVED** [review]
Nicely done! :lgtm_strong: 

> Reviewed 1 of 2 files at r2, 3 of 6 files at r4, 1 of 1 files at r5, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95713#-:-NN36wUx0SDmxGCngWsm:b9wpkzk)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek)

___
*[`pkg/sql/opt/memo/logical_props_builder.go` line 2304 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95713#-NMWjFgeAeX6wAAnyX-P:-NN37-NEEoW-ukVPqSsT:b9bkkp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe3cacccc4ae4632e33f5455264af2c57e9475ab/pkg/sql/opt/memo/logical_props_builder.go#L2304)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Good idea. It adds a little more complexity in some other places, but I think it's worth it. PTAL.
</blockquote></details>

Looks great!

**Pull request merged**
