### PR TITLE
sql: fix bug where some session vars couldn't be set to "on" or "off"

### LINKED ISSUE #46161: experimental_enable_hash_sharded_indexes takes incorrect values
**Describe the problem**

The `experimental_enable_hash_sharded_indexes` session variable only takes boolean values. When you set `true`, it shows `on`, and when you set `false`, it shows `off`. 

You should be able to set `on` and `off` directly.

```
root@127.0.0.1:59143/movr> SET experimental_enable_hash_sharded_indexes=on;
ERROR: parameter "experimental_enable_hash_sharded_indexes" requires a Boolean value
SQLSTATE: 22023
DETAIL: 'on' is a string
```

```
root@127.0.0.1:59143/movr> SET experimental_enable_hash_sharded_indexes=true;
SET

Time: 225µs
```
```
root@127.0.0.1:59143/movr> SHOW experimental_enable_hash_sharded_indexes;
  experimental_enable_hash_sharded_indexes
--------------------------------------------
  on
(1 row)

Time: 488µs
```

```
root@127.0.0.1:59143/movr> SET experimental_enable_hash_sharded_indexes=off;
ERROR: parameter "experimental_enable_hash_sharded_indexes" requires a Boolean value
SQLSTATE: 22023
DETAIL: 'off' is a string
```

```
root@127.0.0.1:59143/movr> SET experimental_enable_hash_sharded_indexes=false;
SET

Time: 232µs
```

```
root@127.0.0.1:59143/movr> SHOW experimental_enable_hash_sharded_indexes;
  experimental_enable_hash_sharded_indexes
--------------------------------------------
  off
(1 row)
```

**Environment:**
 - CockroachDB version : [CockroachDB OSS v20.1.0-beta.2-846-ga94dfeb42c (x86_64-apple-darwin19.3.0, built 2020/03/16 18:08:45, go1.13.4)
 - Server OS: macOS
 - Client app: cockroach demo

### PR DESCRIPTION
**Pull request by rohany**
Session variables were incorrectly erroring out on
string inputs even though string values of "on" and
"off" are accepted.

Fixes #46161.

Release justification: bug fix
Release note (bug fix): This PR fixes a bug where various session
variables whose value would display as "on" or "off" could not be
set to the values "on" or "off", only true or false.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Sorry I don't understand the code change. Why was the previous code incorrect? Can you walk me through the analysis step by step?

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46163#-:-M2cOWP2Ay-fYf_LzCnt:bdmjalt)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by rohany** [comment]
all vars that had a `GetStringVal` function equal to `makeBoolGetStringVal` would have `GetStringVal` called on the input datum before `Set` was called. `makeBoolGetStringVal` would call into `getSingleBool` on the input datum, and would error out if the input datum wasn't a `DBool`. That's incorrect, because we allow for `DString` datums in these variables, as long as they are equal to `on` or `off`, which the `Set` function for these vars handles.

**Review by knz — COMMENTED** [review]
Thanks. Maybe would have helped to add this explanation to the commit message.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46163#-:-M2csybg7QOLP2gVLmDT:b-p8db6c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany)

___
*[pkg/sql/vars.go, line 902 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46163#-M2cssP8AlVuIffSOIvh:-M2cssP8AlVuIffSOIvi:bd2akch) ([raw file](https://github.com/cockroachdb/cockroach/blob/2567186494290b0e020a3f45a769ca8f96a883a6/pkg/sql/vars.go#L902)):*
> ```Go
> }
> 
> func makeBoolGetStringValFn(varName string) getStringValFn {
> ```

Please spell out the semantics of this function in a docstring above it.
___
*[pkg/sql/vars.go, line 1040 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46163#-M2csvkiEMJLcSDXAyfn:-M2csvkiEMJLcSDXAyfo:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/2567186494290b0e020a3f45a769ca8f96a883a6/pkg/sql/vars.go#L1040)):*
> ```Go
> }()
> 
> func getSingleBool(name string, val tree.Datum) (*tree.DBool, error) {
> ```

ditto

**Comment by rohany** [comment]
Updated. I think this should be backported, what do you think?

**Comment by awoods187** [comment]
+1 on backport

**Review by knz — APPROVED** [review]
:lgtm: yes to backport

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46163#-:-M2d99D5E0wPv-Kk9z_m:b-250m57)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46163#-:-M2dUs2XEMzgjYJ3rr0a:b-g2a5fb)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @knz and @rohany)

___
*[pkg/sql/logictest/testdata/logic_test/set, line 336 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/46163#-M2dUofc6AMCkCqpfY3-:-M2dUofc6AMCkCqpfY30:b-v0wd5c) ([raw file](https://github.com/cockroachdb/cockroach/blob/84657b2c0651cbe86de948ced59977633c6a7f6f/pkg/sql/logictest/testdata/logic_test/set#L336)):*
> ```
> # Ensure that we can set variables to on/off.
> statement ok
> SET enable_zigzag_join = 'on';
> ```

If we want true and false to work as well, we should add those tests too.

**Pull request merged**
