### PR TITLE
tenantcapabilitiespb,spanconfigbounds: introduce span config bounds

### PR DESCRIPTION
**Pull request by ajwerner**
This PR introduces a new concept in the tenant capabilities: `SpanConfigBounds`

These bounds are used to verify the conformance of a `roachpb.SpanConfig` relative to an explicitly stated capability. The idea is that we'll use these both on the sql side to check the integrity of zone config statements relative to capabiltiies (in order to provide a nice error) and we'll clamp the values on the kvserver to ensure that the client's requests are acceptable.

Epic CRDB-18604

Release note: None

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
Exciting to see this come together!  Haven't had a very thorough look, but publishing comments so far. A lot of these are questions for me that we can discuss when we meet later today. 

> Reviewed 8 of 8 files at r1, 7 of 26 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96692#-:-NOuoBew7_trLlsKf_I1:bd8hzjn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @benbardin)

___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.proto` line 69 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96692#-NOumeUy81m-qAx239Hg:-NOumeUy81m-qAx239Hh:btijida) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b72418c3513dcb3baa9b7a70573011380a642b9/pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.proto#L69)):*
> ```protobuf
> 
>   // GcTtlSeconds bounds the configuration of gc.ttl_seconds.
>   Int32Range gc_ttl_seconds = 1;
> ```

nit: Should we call this `GCTTLSeconds` to (pardon the pun) conform with the `{Span,Zone}Config` messages?
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.proto` line 102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96692#-NOun9vF1uXfaqqexIjT:-NOun9vF1uXfaqqexIjU:bzeh9lx) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b72418c3513dcb3baa9b7a70573011380a642b9/pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.proto#L102)):*
> ```protobuf
>   //
>   // The fallback constraints should conform to the allowed constraints; if
>   // they do not, then a clamped configuration will not conform. This is the
> ```

nit: I don't follow what the last sentence is saying here. 
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.proto` line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96692#-NOumHg913A73NtsmnLw:-NOumHg913A73NtsmnLx:bquc9fb) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b72418c3513dcb3baa9b7a70573011380a642b9/pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.proto#L111)):*
> ```protobuf
>   message ConstraintBounds {
>     option (gogoproto.equal) = true;
>     Int32Range num_replicas = 1;
> ```

What's the motivation behind putting `num_replicas' and `num_voters` in this message? Instead of nesting it here, could we put it on `SpanConfigBounds` like `RangeMinBytes` etc.? 
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.proto` line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96692#-NOuo0cI6hURuMOd7CGF:-NOuo0cI6hURuMOd7CGG:bojfh3p) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b72418c3513dcb3baa9b7a70573011380a642b9/pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.proto#L126)):*
> ```protobuf
>     // clamping a configuration which is out of conformance.
>     //
>     // If the existing constraint had just one entry with no numeric bound,
> ```

(For me) let's talk about this part when we meet. 
___
*[`pkg/spanconfig/spanconfigbounds/bounds.go` line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96692#-NOuefkR2zWoSO5LH3Jn:-NOuefkR2zWoSO5LH3Jo:b-r2pct0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b72418c3513dcb3baa9b7a70573011380a642b9/pkg/spanconfig/spanconfigbounds/bounds.go#L27)):*
> ```Go
> 	redact.SafeFormatter
> 
> 	// conforms checks whether the value conforms. It does not modify the value.
> ```

You have the "conforms" and "clamp" comments switched around. 
___
*[`pkg/spanconfig/spanconfigbounds/fields.go` line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96692#-NOudEaa-fNXbGUtYcA8:-NOudEaa-fNXbGUtYcA9:bw8v7oi) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b72418c3513dcb3baa9b7a70573011380a642b9/pkg/spanconfig/spanconfigbounds/fields.go#L43)):*
> ```Go
> 
> // Note that the order of fields in this slice matters. When clamping, fields
> // will be clamp4ed in order. This matters for fields like constraints and
> ```

nit: "clamp4ed"

**Review by ajwerner — COMMENTED** [review]
RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96692#-:-NPP4LHj2a0VetLLdjxQ:bb72pd0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @benbardin)

___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.proto` line 69 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96692#-NOumeUy81m-qAx239Hg:-NPOwT6053tB2QOS2X-4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b72418c3513dcb3baa9b7a70573011380a642b9/pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.proto#L69)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: Should we call this `GCTTLSeconds` to (pardon the pun) conform with the `{Span,Zone}Config` messages?
</blockquote></details>

Done.
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.proto` line 102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96692#-NOun9vF1uXfaqqexIjT:-NPOwROXCg0TdKC37UsZ:b-dos5wn) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b72418c3513dcb3baa9b7a70573011380a642b9/pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.proto#L102)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: I don't follow what the last sentence is saying here. 
</blockquote></details>

I lightly touched it up.
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.proto` line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96692#-NOumHg913A73NtsmnLw:-NPOwPziCu3ngAgJFh45:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b72418c3513dcb3baa9b7a70573011380a642b9/pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.proto#L111)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

What's the motivation behind putting `num_replicas' and `num_voters` in this message? Instead of nesting it here, could we put it on `SpanConfigBounds` like `RangeMinBytes` etc.? 
</blockquote></details>

Done.
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.proto` line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96692#-NOuo0cI6hURuMOd7CGF:-NPOwQRc52g8cE7Pc3Yp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b72418c3513dcb3baa9b7a70573011380a642b9/pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.proto#L126)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

(For me) let's talk about this part when we meet. 
</blockquote></details>

Done.
___
*[`pkg/spanconfig/spanconfigbounds/bounds.go` line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96692#-NOuefkR2zWoSO5LH3Jn:-NPOwVdP0CnDmkFVLny_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b72418c3513dcb3baa9b7a70573011380a642b9/pkg/spanconfig/spanconfigbounds/bounds.go#L27)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

You have the "conforms" and "clamp" comments switched around. 
</blockquote></details>

Done.
___
*[`pkg/spanconfig/spanconfigbounds/fields.go` line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96692#-NOudEaa-fNXbGUtYcA8:-NPOwUzo9X7LmICxnWKf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b72418c3513dcb3baa9b7a70573011380a642b9/pkg/spanconfig/spanconfigbounds/fields.go#L43)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: "clamp4ed"
</blockquote></details>

Done.

**Review by arulajmani — APPROVED** [review]
:lgtm:

> Reviewed 30 of 30 files at r3, 32 of 32 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96692#-:-NProUd_Cft1MaPsETWy:bg7igk9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @benbardin)

___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.proto` line 116 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96692#-NPrYg8D15PkKRS64TtK:-NPrYg8D15PkKRS64TtL:b-s5tqxk) ([raw file](https://github.com/cockroachdb/cockroach/blob/d87fe2a6bf4ee0772f42beaf202bb1d85a353d0f/pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.proto#L116)):*
> ```protobuf
> 
>   // ConstraintBounds represents bounds on voter_constraints, constraints,
>   // lease_preferences, num_voters, and num_replicas.
> ```

nit: just `voter_constraints`, `constraints`, and `lease_preferences` now?
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.proto` line 118 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96692#-NPro7wI8HxIfBUOu0VN:-NPro7wI8HxIfBUOu0VO:b-qt8q89) ([raw file](https://github.com/cockroachdb/cockroach/blob/d87fe2a6bf4ee0772f42beaf202bb1d85a353d0f/pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.proto#L118)):*
> ```protobuf
>   // lease_preferences, num_voters, and num_replicas.
>   //
>   // The behavior of ConstraintBounds in the case of non-conformance may be
> ```

Is this the right place to talk about the behavior of `ConstraintBounds` as it applies to the three fields? If not, we should direct the reader to inline comments in the `clamp` function. 


Alternatively, do you think it's worth adding a high level overview about "how clamping works" for all fields in the `SpanConfigBounds` proto in a `doc.go` as a single point of reference for future readers instead?
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.proto` line 151 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96692#-NPrXatX4o4f_J0yh4zp:-NPrXatX4o4f_J0yh4zq:b-y2xx88) ([raw file](https://github.com/cockroachdb/cockroach/blob/d87fe2a6bf4ee0772f42beaf202bb1d85a353d0f/pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.proto#L151)):*
> ```protobuf
>     // distribution of replicas, to the extent possible, but as applied to
>     // the fallback constraints.
>     repeated cockroach.roachpb.Constraint allowed = 3 [(gogoproto.nullable) = false];
> ```

nit: here, and below, 1 and 2 instead of 3 and 4?
___
*[`pkg/spanconfig/spanconfigbounds/bool_field.go` line 44 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96692#-NPU-SjF2RCUo2AEYGrW:-NPU-SjF2RCUo2AEYGrX:b4v5hlt) ([raw file](https://github.com/cockroachdb/cockroach/blob/d87fe2a6bf4ee0772f42beaf202bb1d85a353d0f/pkg/spanconfig/spanconfigbounds/bool_field.go#L44)):*
> ```Go
> 	case globalReads:
> 		return &c.GlobalReads
> 		// TODO(ajwerner, XXX): Decide what to do about these fields.
> ```

Should we just add an assertion failed here, given we never expect this to be called for either of these two fields? We could just uncomment what you have here, but maybe adding a panic here would nudge whoever ends up here to think more about the structure here (given this is tied to `SpanConfigBounds`, and we don't have these fields on the proto). 
___
*[`pkg/spanconfig/spanconfigbounds/constraints_field.go` line 174 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96692#-NPU4XfI952yBkknQf-3:-NPU4XfI952yBkknQf-4:b-sit1xp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d87fe2a6bf4ee0772f42beaf202bb1d85a353d0f/pkg/spanconfig/spanconfigbounds/constraints_field.go#L174)):*
> ```Go
> 	switch f {
> 	case voterConstraints:
> 		// In the common settings, voter constraints either attempt to state
> ```

Instead of being general with the "common settings" phrasing, could we phrase this (and some of the commentary below, which isn't already) explicitly in the context of MR primitives? 
___
*[`pkg/spanconfig/spanconfigbounds/lease_preferences_field.go` line 88 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96692#-NPrnw_uB4KNLzM_paVn:-NPrnw_uB4KNLzM_paVo:bbq3asf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d87fe2a6bf4ee0772f42beaf202bb1d85a353d0f/pkg/spanconfig/spanconfigbounds/lease_preferences_field.go#L88)):*
> ```Go
> }
> 
> func (c *leasePreferencesBound) clamp(t *roachpb.SpanConfig, f Field) (changed bool) {
> ```

The clamping behaviour here deserves a comment. 
___
*[`pkg/spanconfig/spanconfigbounds/testdata/regions` line 102 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96692#-NPrcFvG5983ewrVWls7:-NPrcFvG5983ewrVWls8:b3heuty) ([raw file](https://github.com/cockroachdb/cockroach/blob/d87fe2a6bf4ee0772f42beaf202bb1d85a353d0f/pkg/spanconfig/spanconfigbounds/testdata/regions#L102)):*
> ```
> 
> # Note that this case is interesting because we won't touch the out-of-bounds
> # num_replicas in the voter_constraints. It's invalid but it's okay because we
> ```

Is it even possible to end up with such a invalid zone/span config in the first place?
___
*[`pkg/spanconfig/spanconfigbounds/testdata/truncated_lease_prefs` line 19 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96692#-NPrmK2LAgxt_t3Qjrdc:-NPrmK2LAgxt_t3Qjrdd:b-ocjci3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d87fe2a6bf4ee0772f42beaf202bb1d85a353d0f/pkg/spanconfig/spanconfigbounds/testdata/truncated_lease_prefs#L19)):*
> ```
> # preferences are going to be clamped. What's weird about it is that
> # we're going to end up with a conflicting lease preference which conforms
> # but does not have any voters in it.
> ```

Could we end up with something unsatisfiable here? Whatever the construction, we're guaranteed to have a replica where the lease is being pinned. We're also guaranteed that voters won't be fully constrained to a different region -- so the replica in the region where the lease is pinned _can_ be a voter without violating any constraints. Are we smart enough to recognize it needs to be a voter though?
___
*[`pkg/spanconfig/spanconfigbounds/testdata/truncated_lease_prefs` line 66 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96692#-NPrhBJJ0vvq6m2C_3lu:-NPrhBJJ0vvq6m2C_3lv:b-59rdsz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d87fe2a6bf4ee0772f42beaf202bb1d85a353d0f/pkg/spanconfig/spanconfigbounds/testdata/truncated_lease_prefs#L66)):*
> ```
>    constraints: <
>      key: "region"
> @@ -21,21 +21,15 @@
> ```

nit: the default value for the diff context makes this case slightly hard to read -- you could consider making it configurable and increasing it for this test case in particular. FWIW, I found the error messages above much easier to follow anyway, so not doing so isn't a big deal. 
___
*[`pkg/spanconfig/spanconfigbounds/testdata/truncated_lease_prefs` line 97 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96692#-NPrjl901Y3-O0gRzmQN:-NPrjl901Y3-O0gRzmQO:b-bxzl6j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d87fe2a6bf4ee0772f42beaf202bb1d85a353d0f/pkg/spanconfig/spanconfigbounds/testdata/truncated_lease_prefs#L97)):*
> ```
>  >
> 
> # Exercise the logic to clamp the lease preferences in the other direction.
> ```

nit: Not sure what "other direction" means in this context. 
___
*[`pkg/spanconfig/spanconfigbounds/testdata/truncated_lease_prefs` line 143 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96692#-NPrjo-5EDWNZ8eHixz-:-NPrjo-5EDWNZ8eHixz0:b-4inhiq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d87fe2a6bf4ee0772f42beaf202bb1d85a353d0f/pkg/spanconfig/spanconfigbounds/testdata/truncated_lease_prefs#L143)):*
> ```
> -    key: "region"
>      value: "us-central1"
>    >
> ```

Could we also add a test for when none of the constraints in `lease_preferences` match what is allowed in the `bound`? For example, `bound_to_us` with something like:
```
lease_preferences: <constraints: <key: "region" value: "europe-west1">>
lease_preferences: <constraints: <key: "region" value: "europe-west2">>
```
___
*[`pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant` line 185 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96692#-NPY1dY43btaTcIXx7TB:-NPY1dY43btaTcIXx7TC:b-hay66i) ([raw file](https://github.com/cockroachdb/cockroach/blob/e828ba02c877cddedc85fdfc239e1cc2ca104d0f/pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant#L185)):*
> ```
> 90001
> 1
> 1
> ```

revert?

**Review by benbardin — COMMENTED** [review]
Approved for backupccl

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Pull request merged**
