### PR TITLE
sql/schemachanger: fix TableData element migration crash

### LINKED ISSUE #112208: schemachanger: TestBackupSuccessMixedVersion and TestBackupRollbacksMixedVersion fail with min supported version 23.1
`TestBackupSuccessMixedVersion_base_create_function_in_txn` and `TestBackupRollbacksMixedVersion_base_add_column_default_unique` tests fail once the minimum supported version is bumped to 23.1. I couldn't figure out right away how to fix them. I will be skipping them for now.

More details in this build:
https://teamcity.cockroachdb.com/viewLog.html?buildId=12145489&buildTypeId=Cockroach_BazelEssentialCi

Jira issue: CRDB-32294

### PR DESCRIPTION
**Pull request by fqazi**
Previously, the migration to inject TableData elements when migrating the schema changer state did not correctly populate metadata.  When attempting to execute any schema change after this change, the missing metadata could cause the execution to fail. To address this, this patch populates the metadata for the added TableData elements. Additionally, it updates the code to populate the statement metadata to ensure they are indexable by ID since, during backup, unrelated statements will get cleaned up. With these changes we can re-enable the mixed version backup/restore tests again.

Fixes: #112208

Release note: None

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
could you unskip the tests to make sure they pass now?

**Comment by fqazi** [comment]
@rafiss Yeah, I missed that, and there was another bug in this area with transient index columns which was causing another test to fail

**Review by rafiss — APPROVED** [review]
nice fixes. before merging, could you check if that second commit helps with any of these: https://github.com/cockroachdb/cockroach/issues/112421 https://github.com/cockroachdb/cockroach/issues/112418 or https://github.com/cockroachdb/cockroach/issues/112417? these are all issues with DML failing during index-related schema changes.

**Comment by fqazi** [comment]
@rafiss Unfortunately, the other tests aren't impacted by this. Let me pick those up. TFTR!

bors r+

**Pull request merged**
