### PR TITLE
rangefeed: don't publish empty resolved timestamps

### PR DESCRIPTION
**Pull request by erikgrinaker**
This patch prevents rangefeeds from emitting checkpoint events with
empty resolved timestamps. These may be emitted due to races during
processor startup, or because the range's closed timestamp is itself
empty. However, they are of little use to clients, and may be
unexpected.

This is an internal API change, because previously the rangefeed was
guaranteed to emit a checkpoint immediately after the initial catchup
scan (if any). However, this was not emitted across changefeeds, so
there should be no externally visible changes.

Release note: None

### CODE REVIEW

**Comment by erikgrinaker** [comment]
> this was not emitted across changefeeds, so there should be no externally visible changes.

@miretskiy Can you confirm the above? I understood that changefeeds already check for this and prevent emitting them.

**Comment by miretskiy** [comment]
> > this was not emitted across changefeeds, so there should be no externally visible changes.
> 
> @miretskiy Can you confirm the above? I understood that changefeeds already check for this and prevent emitting them.

Confirmed.

**Review by miretskiy — APPROVED** [review]

**Comment by erikgrinaker** [comment]
You sure about that @miretskiy? I'm getting test failures for `TestChangefeedBackfillCheckpoint` because changefeed jobs aren't updated with checkpoints, which indicates that externally visible changefeed behavior depends on these?

**Comment by miretskiy** [comment]
What I meant that 0 timestamp should not be emitted to the external
clients.  Internally, we definitely see
0 timestamp (and that's why I brought this issue up because I thought it
was confusing).
I wouldn't be surprised that some of the tests, such as the one you
mentioned, might become broken/flaky
because they are just so hard to write in the first place, and depend on
the checkpoints being generated
just so.

I'm going to take a poke at this test to see if I can fix/repro this on top
of your PR.
Give me some time.

**Comment by erikgrinaker** [comment]
Sure. I'll be OOO for a week, feel free to adopt this PR.

**Comment by nvanbenschoten** [comment]
I haven't looked at this code in a while, so I'm likely misremembering, but isn't the publication of an empty timestamp to signal the completion of the catch-up scan important to the client in some way? If I'm remembering correctly, rangefeed had different ordering semantics during a catch-up scan than during steady-state which forced the client to behave differently during the two phases. Is that still true?

**Comment by erikgrinaker** [comment]
> isn't the publication of an empty timestamp to signal the completion of the catch-up scan important to the client in some way? If I'm remembering correctly, rangefeed had different ordering semantics during a catch-up scan than during steady-state which forced the client to behave differently during the two phases. Is that still true?

Yeah, I thought the client might care about an initial checkpoint as some sort of readiness signal too, but it didn't seem like any of the clients actually did. I'll let @miretskiy have a look at this to confirm. See also #59728 which has some further discussion.

**Comment by erikgrinaker** [comment]
Given the [recent discussions](https://cockroachlabs.slack.com/archives/C0KB9Q03D/p1646870092763289) on catchup scan scalability, it seems like emitting these checkpoints immediately after catchup scan completion will be a central part of the solution, so let's not remove them.

**Pull request closed without merging**
