### PR TITLE
sql: add ZONECONFIG privilege for allowing users to edit zone config at the database level

### LINKED ISSUE #43309: sql: create zone config editor grant at the database level
Some customers require the ability to permit users who are not root to create, edit and delete zone configurations.

This ticket tracks adding a new grant at the database level called something (`ZONECONFIG`?) and adding permission checks to all places where users can create, edit or delete zone configs.

### PR DESCRIPTION
**Pull request by RichardJCai**
Fixes #43309

Release note (sql change): Allow users who are not admin to edit zone config at the database level using the ZONECONFIG privilege.

### CODE REVIEW

**Comment by otan** [comment]
were you meant to get a review on this first? calling bors immediately tries to land it.

also generally you should wait to bors after the TeamCity build completes to lessen the chance you block others in case this build is broken

**Comment by otan** [comment]
bors r-

this appears to be failing some tests, so moving it off the queue to be committed into master

**Comment by RichardJCai** [comment]
@otan Sorry my bad, didn't mean to run bors r+

**Review by solongordon — CHANGES_REQUESTED** [review]
Good start! As you know some of the logic test expected output needs to be updated. You can either do that manually or run logic tests with the `-rewrite` flag to automatically rewrite the expected outputs. Something like this:
```
make testlogic FILES='grant_database grant_table information_schema' TESTFLAGS=-rewrite
```

There is also going to be some additional work necessary to make this work properly for tables. Zone configs can be applied at various levels including databases and tables. Your current implementation gives users privileges at the database level but has no effect at the table level. I put a comment on the issue with my best guess at how we'll want this to work but we can confirm with Andy.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43941#-:-LyZbSsUEsOOvVmUDxjo:b-fifqkd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai and @solongordon)

___
*[pkg/sql/set_zone_config.go, line 192 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43941#-LyZb7H6608st61fayz_:-LyZb7H6608st61fayza:b-rducon) ([raw file](https://github.com/cockroachdb/cockroach/blob/96f9d25d797da4c678a6e8212f61919f64589eb7/pkg/sql/set_zone_config.go#L192)):*
> ```Go
> 
> 		return pgerror.Newf(pgcode.InsufficientPrivilege,
> 			"user %s does not have %s privilege on %s %s",
> ```

Minor: This would be easier to read without the nested printfs.  Just do `"user %s does not have %s or %s privilege on %s %s`.

**Review by solongordon — CHANGES_REQUESTED** [review]
Looking great. One minor testing request and then this is good to go.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43941#-:-LyfM91g9bhOwFhidrxY:b-wx7rnr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai and @solongordon)

___
*[pkg/ccl/logictestccl/testdata/logic_test/zone, line 748 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43941#-LyfLrf5A7rCpcLcNhOQ:-LyfLrf6Driv3pPmEteU:b-8faczs) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4e2479e68eec1495cbca5c34e7a32ee4057491d/pkg/ccl/logictestccl/testdata/logic_test/zone#L748)):*
> ```
> ALTER DATABASE auth CONFIGURE ZONE USING num_replicas = 3
> 
> user root
> ```

Great tests!
___
*[pkg/ccl/logictestccl/testdata/logic_test/zone, line 811 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43941#-LyfKPvN2maGvgyoipyd:-LyfKPvO44vGUUQ6xpEX:b-2489fs) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4e2479e68eec1495cbca5c34e7a32ee4057491d/pkg/ccl/logictestccl/testdata/logic_test/zone#L811)):*
> ```
> statement ok
> ALTER INDEX auth.t3@x CONFIGURE ZONE USING num_replicas=5;
> ALTER PARTITION p OF INDEX auth.t3@x CONFIGURE ZONE USING num_replicas = 3
> ```

Could you also test these two commands before `testuser` has privileges to make sure they fail?

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43941)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/ccl/logictestccl/testdata/logic_test/zone, line 811 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43941#-LyfKPvN2maGvgyoipyd:-LyfOpGo7VxUu-W1fxoZ:b-ffv0vd) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4e2479e68eec1495cbca5c34e7a32ee4057491d/pkg/ccl/logictestccl/testdata/logic_test/zone#L811)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Could you also test these two commands before `testuser` has privileges to make sure they fail?
</blockquote></details>

At line 727 theres tests before testuser has privileges checking that they fail - is this sufficient?
```statement error pq: user testuser does not have ZONECONFIG or CREATE privilege on relation t
ALTER PARTITION p OF TABLE auth.t CONFIGURE ZONE USING num_replicas = 3

statement error pq: user testuser does not have ZONECONFIG or CREATE privilege on relation t
ALTER PARTITION p OF INDEX auth.t@x CONFIGURE ZONE USING num_replicas = 3```
```

**Review by solongordon — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43941#-:-LyismQZ6g-M8HaS6vX7:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/ccl/logictestccl/testdata/logic_test/zone, line 811 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43941#-LyfKPvN2maGvgyoipyd:-Lyisin56_9WXWeGhO2A:b-dn2hjk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4e2479e68eec1495cbca5c34e7a32ee4057491d/pkg/ccl/logictestccl/testdata/logic_test/zone#L811)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

At line 727 theres tests before testuser has privileges checking that they fail - is this sufficient?
```statement error pq: user testuser does not have ZONECONFIG or CREATE privilege on relation t
ALTER PARTITION p OF TABLE auth.t CONFIGURE ZONE USING num_replicas = 3

statement error pq: user testuser does not have ZONECONFIG or CREATE privilege on relation t
ALTER PARTITION p OF INDEX auth.t@x CONFIGURE ZONE USING num_replicas = 3```
</blockquote></details>

Ah I missed that, looks good.


<!-- Sent from Reviewable.io -->

**Pull request merged**
