### PR TITLE
sql: sequences: respect MAXVALUE, MINVALUE, and CYCLE settings

### PR DESCRIPTION
**Pull request by vilterp**
…including detecting integer overflows.

Tracking issue: #19723

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/sequence.go, line 79 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-L-qUf3ZYduPVWVIFBTD:-L-qUf3ZYduPVWVIFBTE:b-w169vy) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6db4cab4044109c9ccc95941732d4ad3ae5eccd/pkg/sql/sequence.go#L79)):*
> ```Go
> 	seqOpts := descriptor.SequenceOpts
> 	if seqOpts.Cycle {
> 		err := p.txn.DB().Put(ctx, seqValueKey, seqOpts.Start)
> ```

This seems unsafe to me. If two transactions concurrently increment a sequence past `MaxValue`, they will both attempt to set the sequence back to the start value. Am I missing something about how this is working?

I suspect we'll have to put the handling of `MaxValue` and cycles into the `Increment` op itself. That is, extend `IncrementRequest` to contain the `MaxValue` and `Cycle` config so that the increment KV operation can internally handle the wrap around in an "atomic" manner. One complexity here is that we'd need to handle multi-version clusters which don't support the new fields in `IncrementRequest`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574)*

**Comment by vilterp** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/sequence.go, line 79 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-L-qUf3ZYduPVWVIFBTD:-L-s4usDNUbP5wfwbaIa:b-i02kml) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6db4cab4044109c9ccc95941732d4ad3ae5eccd/pkg/sql/sequence.go#L79)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This seems unsafe to me. If two transactions concurrently increment a sequence past `MaxValue`, they will both attempt to set the sequence back to the start value. Am I missing something about how this is working?

I suspect we'll have to put the handling of `MaxValue` and cycles into the `Increment` op itself. That is, extend `IncrementRequest` to contain the `MaxValue` and `Cycle` config so that the increment KV operation can internally handle the wrap around in an "atomic" manner. One complexity here is that we'd need to handle multi-version clusters which don't support the new fields in `IncrementRequest`.
</blockquote></details>

You're right; this is a bug. Should have thought of that!

Yes, pushing this logic into `Increment` seems like the only way to go. For mixed-version clusters (where the gateway node is running `IncrementSequence` but the node holding the value is old), it seems that the gateway node would have to check the value it gets back, and give an error if it's exceeded the MaxValue (because the value node, being old, didn't respect the setting). I suppose giving an error in this case would be better than cycling, to prevent the race condition you identified.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574)*

**Comment by petermattis** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/sequence.go, line 79 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-L-qUf3ZYduPVWVIFBTD:-L-sAMQ7Uk6ktzuSRnnu:b-pae70a) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6db4cab4044109c9ccc95941732d4ad3ae5eccd/pkg/sql/sequence.go#L79)):*
> I suppose giving an error in this case would be better than cycling, to prevent the race condition you identified.

Yeah, I think returning an error is appropriate if the `IncrementResponse` indicates that `Increment` ignored cycle/max-value settings. Another option is we could disallow creating a sequence with such settings if the cluster version is too low. I think I might prefer that option. Grep for `IsActive(` for examples of how to make such checks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574)*

**Comment by vilterp** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/sequence.go, line 79 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-L-qUf3ZYduPVWVIFBTD:-L-sCvojJqlzUDa3X2Pk:b-clw7vy) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6db4cab4044109c9ccc95941732d4ad3ae5eccd/pkg/sql/sequence.go#L79)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

> I suppose giving an error in this case would be better than cycling, to prevent the race condition you identified.

Yeah, I think returning an error is appropriate if the `IncrementResponse` indicates that `Increment` ignored cycle/max-value settings. Another option is we could disallow creating a sequence with such settings if the cluster version is too low. I think I might prefer that option. Grep for `IsActive(` for examples of how to make such checks.
</blockquote></details>

Yeah, I agree that seems like a better option. IsActive checks look straightforward; add a version such as `VersionIncrementWithOptions`? It would then be linked to a release; 1.1.5?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574)*

**Comment by petermattis** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/sequence.go, line 79 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-L-qUf3ZYduPVWVIFBTD:-L-sj5eahkXr-sp7WmS4:bp6s5qr) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6db4cab4044109c9ccc95941732d4ad3ae5eccd/pkg/sql/sequence.go#L79)):*
<details><summary><i>Previously, vilterp (Pete Vilter) wrote…</i></summary><blockquote>

Yeah, I agree that seems like a better option. IsActive checks look straightforward; add a version such as `VersionIncrementWithOptions`? It would then be linked to a release; 1.1.5?
</blockquote></details>

Yep. Note that all of the 1.1.x versions will get enabled when 1.2 (err, 2.0) gets released. That is, 1.1.5 does not correspond to cockroach-v1.1.5. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574)*

**Comment by vilterp** [comment]
note to self: don't merge before adding `IsActive` checks

**Comment by petermattis** [comment]
@tschottdorf Can you take a look at the additions to the KV api and the associated implementation?

---

Review status: 0 of 19 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-:-L0Cr94ddlUyIUFNcBe4:bgrfdik)*

**Comment by vilterp** [comment]
Review status: 0 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/storage/engine/mvcc.go, line 1205 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-L0Ct4qQYQaH8SqDp71s:-L0Ct4qQYQaH8SqDp71t:b711m0q) ([raw file](https://github.com/cockroachdb/cockroach/blob/f04e4c0d64a59495fc0964be287719a39796f817/pkg/storage/engine/mvcc.go#L1205)):*
> ```Go
> 	maxVal int64,
> 	cycle bool,
> 	start int64,
> ```

This is a lot of parameters to pass around; maybe it would be better to group them by using the `*BoundsOptions` struct here. If nil, this function would fall back to sensible defaults — `0, math.MaxInt64, false, 0`, which makes it behave as it does now. (Currently, this defaulting is happening in `cmd_increment.go`) For RPCs, the `*BoundsOptions` would be passed through directly from the `IncrementRequest`.

What do you think @tschottdorf? There seems to be a preference in this file for a bunch of explicit parameters.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574)*

**Comment by vilterp** [comment]
Review status: 0 of 30 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/storage/engine/mvcc.go, line 1205 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-L0Ct4qQYQaH8SqDp71s:-L0LolWqgZYNSO5Wvi7R:b-1be273) ([raw file](https://github.com/cockroachdb/cockroach/blob/f04e4c0d64a59495fc0964be287719a39796f817/pkg/storage/engine/mvcc.go#L1205)):*
<details><summary><i>Previously, vilterp (Pete Vilter) wrote…</i></summary><blockquote>

This is a lot of parameters to pass around; maybe it would be better to group them by using the `*BoundsOptions` struct here. If nil, this function would fall back to sensible defaults — `0, math.MaxInt64, false, 0`, which makes it behave as it does now. (Currently, this defaulting is happening in `cmd_increment.go`) For RPCs, the `*BoundsOptions` would be passed through directly from the `IncrementRequest`.

What do you think @tschottdorf? There seems to be a preference in this file for a bunch of explicit parameters.
</blockquote></details>

Update: refactored to pass a struct through. Apologies for all the rebasing; can make a new branch & PR if preferred.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574)*

**Comment by tschottdorf** [comment]
Left some comments on the kv changes (reviewed the rest, but very casually so not worth much). The semantics surprised me, especially in the overflow case. Try to clarify the comments so that they address all of that behavior too. I've held off on the MVCC test until I understand what the intended outcomes are.

---

Reviewed 19 of 19 files at r10, 1 of 1 files at r11, 3 of 3 files at r12, 27 of 27 files at r13, 3 of 3 files at r14.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[pkg/roachpb/api.proto, line 202 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-L0jT6_e0c5u1PfWcF2e:-L0jT6_e0c5u1PfWcF2f:b-dxkzru) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba9944349fd8bbae022e908179d13ab0cc1e72a4/pkg/roachpb/api.proto#L202)):*
> ```protobuf
>     int64 max_value = 2;
>     // Whether to go back to the start if min_value or max_value is exceeded.
>     bool cycle = 3;
> ```

It's weird that `cycle` doesn't allow to wrap around from `min_value` to `max_value`.
Comments need to address the overflow case that also confused me in the actual code.

I also think that you don't need to duplicate the comment that you have on all the methods that take this message. Just add a comment to this message itself (above the `message` line above) and then you can just refer to it.

---

*[pkg/roachpb/errors.proto, line 340 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-L0jRnw5kvbgFE1g6fvF:-L0jRnw5kvbgFE1g6fvG:b-h41u9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba9944349fd8bbae022e908179d13ab0cc1e72a4/pkg/roachpb/errors.proto#L340)):*
> ```protobuf
>   option (gogoproto.equal) = true;
> 
>   optional bytes key = 1 [(gogoproto.casttype) = "Key"];
> ```

I think you could just add (embed) the `BoundsOptions` that were active when the request failed. That seems more elegant, but it's up to you.

---

*[pkg/storage/engine/mvcc.go, line 1207 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-L0jS8-OpETsEZ5Hr0SP:-L0jS8-OpETsEZ5Hr0SQ:byho7fk) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba9944349fd8bbae022e908179d13ab0cc1e72a4/pkg/storage/engine/mvcc.go#L1207)):*
> ```Go
> 	defer iter.Close()
> 
> 	// Set defaults for bounds options.
> ```

nit: just rename opts from the signature to `incomingOpts` and then this code can simply be

```go
opts := roachpb.IncrementRequest_BoundsOptions{
  MinValue: 0,
  MaxValue: math.MaxInt64
}
if incomingOpts != nil {
  opts = *incomingOpts
}
```

---

*[pkg/storage/engine/mvcc.go, line 1232 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-L0jShiPrGMN-7Apq4WA:-L0jShiPrGMN-7Apq4WB:bka3677) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba9944349fd8bbae022e908179d13ab0cc1e72a4/pkg/storage/engine/mvcc.go#L1232)):*
> ```Go
> 		if willOverflow(curInt64Val, inc) {
> 			if cycle {
> 				newInt64Val = start
> ```

This strikes me as incorrect. If the current value is `MaxInt64-3` and the increment is `6`, you would want a result of `3`, right? And also only if your `MaxVal` is actually `MaxInt64`. If it's `MaxInt64-1`, you'd want `4` instead, etc.

Besides, this could be an underflow as well, which I think should be handled symmetrically (i.e. if `Cycle` is set, you wrap around in both directions; that is less one-offy).

---

*[pkg/storage/engine/mvcc.go, line 1235 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-L0jSua-MkaeXLoY_aJP:-L0jSua-MkaeXLoY_aJQ:beow5il) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba9944349fd8bbae022e908179d13ab0cc1e72a4/pkg/storage/engine/mvcc.go#L1235)):*
> ```Go
> 			} else {
> 				// Return the current value, since we failed to update it.
> 				newInt64Val = curInt64Val
> ```

What's this for? You don't seem to be using it.

---

*[pkg/storage/engine/mvcc.go, line 1238 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-L0jTa-wiMHGgMP0xPpM:-L0jTa-wiMHGgMP0xPpN:b-f61fjt) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba9944349fd8bbae022e908179d13ab0cc1e72a4/pkg/storage/engine/mvcc.go#L1238)):*
> ```Go
> 				return nil, &roachpb.BoundsExceededError{
> 					Key:            key,
> 					Overflow:       true,
> ```

Seems that you wouldn't need the `Overflow` field if you embedded the options (as the caller can find out itself that it overflowed. However, if this case is central to what you're doing, might as well make it explicit)

---

*[pkg/storage/engine/mvcc.go, line 1249 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-L0jUVfyNPxgmcvlpCfv:-L0jUVfyNPxgmcvlpCfw:b3wloi9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba9944349fd8bbae022e908179d13ab0cc1e72a4/pkg/storage/engine/mvcc.go#L1249)):*
> ```Go
> 			if newInt64Val > maxValue || newInt64Val < minValue {
> 				if cycle {
> 					newInt64Val = start
> ```

Again, don't you want to wrap around?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-:-L0jUdzgsy2G4Nst5kTM:bko6cjd)*

**Comment by vilterp** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[pkg/storage/engine/mvcc.go, line 1207 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-L0jS8-OpETsEZ5Hr0SP:-L0khUVGjL0Jg4RRsE0W:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba9944349fd8bbae022e908179d13ab0cc1e72a4/pkg/storage/engine/mvcc.go#L1207)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

nit: just rename opts from the signature to `incomingOpts` and then this code can simply be

```go
opts := roachpb.IncrementRequest_BoundsOptions{
  MinValue: 0,
  MaxValue: math.MaxInt64
}
if incomingOpts != nil {
  opts = *incomingOpts
}
```
</blockquote></details>

Done.

---

*[pkg/storage/engine/mvcc.go, line 1232 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-L0jShiPrGMN-7Apq4WA:-L0kiScjVeAc0PuE8w0V:b-z9ikpd) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba9944349fd8bbae022e908179d13ab0cc1e72a4/pkg/storage/engine/mvcc.go#L1232)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

This strikes me as incorrect. If the current value is `MaxInt64-3` and the increment is `6`, you would want a result of `3`, right? And also only if your `MaxVal` is actually `MaxInt64`. If it's `MaxInt64-1`, you'd want `4` instead, etc.

Besides, this could be an underflow as well, which I think should be handled symmetrically (i.e. if `Cycle` is set, you wrap around in both directions; that is less one-offy).
</blockquote></details>

I agree that that seems more intuitive. However, it's not the behavior of PG sequences:

```
test=# CREATE SEQUENCE wraparound_test MAXVALUE 15 INCREMENT 10 cycle;
CREATE SEQUENCE
test=# select nextval('wraparound_test');
 nextval
---------
       1
(1 row)

test=# select nextval('wraparound_test');
 nextval
---------
      11
(1 row)

test=# select nextval('wraparound_test');
 nextval
---------
       1
(1 row)
```

I'm a little uncomfortable with this, but it seems more important to just match the PG behavior here. I know this is the KV layer and Inc is used for other things than sequences, but they'll go on just getting an error when they hit `MaxInt64` and never need wraparound anyway.

---

*[pkg/storage/engine/mvcc.go, line 1235 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-L0jSua-MkaeXLoY_aJP:-L0mkG6YcVX3crFV2VP8:b-h80hm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba9944349fd8bbae022e908179d13ab0cc1e72a4/pkg/storage/engine/mvcc.go#L1235)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

What's this for? You don't seem to be using it.
</blockquote></details>

Without this line, the invalid (bounds-exceeding) value is returned; it causes the current value to be returned.

It looks like it's not used because the return statement directly after it doesn't use it, but it actually is used because that return statement is for the closure passed to `mvccPutUsingIter`, not `MVCCIncrement` itself, and `newInt64Val` is in the scope of `MVCCIncrement`. (i.e. the closure has the side effect of mutating variables in its parent scope). Don't immediately see a better way of writing this…

---

*[pkg/storage/engine/mvcc.go, line 1238 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-L0jTa-wiMHGgMP0xPpM:-L0kjFP8-mHfGz34hYao:bxoi33t) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba9944349fd8bbae022e908179d13ab0cc1e72a4/pkg/storage/engine/mvcc.go#L1238)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Seems that you wouldn't need the `Overflow` field if you embedded the options (as the caller can find out itself that it overflowed. However, if this case is central to what you're doing, might as well make it explicit)
</blockquote></details>

Yeah, I prefer it being explicit with this.

---

*[pkg/storage/engine/mvcc.go, line 1249 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-L0jUVfyNPxgmcvlpCfv:-L0kj_F7rb-4OfjSh3yq:ba6y7p4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba9944349fd8bbae022e908179d13ab0cc1e72a4/pkg/storage/engine/mvcc.go#L1249)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Again, don't you want to wrap around?
</blockquote></details>

Don't think so; see reply above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574)*

**Comment by tschottdorf** [comment]
Looks good so far! My nits mostly revolve about documenting and making it obvious that this is Postgres-ish behavior.

---

Reviewed 30 of 30 files at r15, 1 of 1 files at r16, 3 of 3 files at r17, 27 of 27 files at r18, 3 of 3 files at r19.
Review status: all files reviewed at latest revision, 16 unresolved discussions, all commit checks successful.

---

*[pkg/storage/engine/mvcc.go, line 1232 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-L0jShiPrGMN-7Apq4WA:-L0ocR9jSWMQUjMXzKHl:b-7fpbet) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba9944349fd8bbae022e908179d13ab0cc1e72a4/pkg/storage/engine/mvcc.go#L1232)):*
<details><summary><i>Previously, vilterp (Pete Vilter) wrote…</i></summary><blockquote>

I agree that that seems more intuitive. However, it's not the behavior of PG sequences:

```
test=# CREATE SEQUENCE wraparound_test MAXVALUE 15 INCREMENT 10 cycle;
CREATE SEQUENCE
test=# select nextval('wraparound_test');
 nextval
---------
       1
(1 row)

test=# select nextval('wraparound_test');
 nextval
---------
      11
(1 row)

test=# select nextval('wraparound_test');
 nextval
---------
       1
(1 row)
```

I'm a little uncomfortable with this, but it seems more important to just match the PG behavior here. I know this is the KV layer and Inc is used for other things than sequences, but they'll go on just getting an error when they hit `MaxInt64` and never need wraparound anyway.
</blockquote></details>

Yikes, ok. Please make sure to add ample commentary and reference to the behavior of the PG counters for this then, especially the overflow case.

Could you pull out the whole `if willOverflow() { } else { }` into a method, say,

```go
var err error
newInt64Val, err = pgBoundsCheck(curInt64val, inc, opts)
```

---

*[pkg/storage/engine/mvcc.go, line 1235 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-L0jSua-MkaeXLoY_aJP:-L0oc_ZpBMFCuRR-E2Gl:b-l7ipho) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba9944349fd8bbae022e908179d13ab0cc1e72a4/pkg/storage/engine/mvcc.go#L1235)):*
<details><summary><i>Previously, vilterp (Pete Vilter) wrote…</i></summary><blockquote>

Without this line, the invalid (bounds-exceeding) value is returned; it causes the current value to be returned.

It looks like it's not used because the return statement directly after it doesn't use it, but it actually is used because that return statement is for the closure passed to `mvccPutUsingIter`, not `MVCCIncrement` itself, and `newInt64Val` is in the scope of `MVCCIncrement`. (i.e. the closure has the side effect of mutating variables in its parent scope). Don't immediately see a better way of writing this…
</blockquote></details>

You're returning an error, so it shouldn't matter (and I'd prefer returning zero in the surrounding scope anyway).

---

*[pkg/storage/engine/mvcc.go, line 1202 at r18](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-L0od_FCzrWxi_yivdw3:-L0od_FCzrWxi_yivdw4:bexxkfg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2f6cc3af7eec14768e963e11f60133514a85497/pkg/storage/engine/mvcc.go#L1202)):*
> ```Go
> 	txn *roachpb.Transaction,
> 	inc int64,
> 	incomingOpts *roachpb.IncrementRequest_BoundsOptions,
> ```

Rename the message to something like `PGSequenceOptions` to make the relationship to Postgres obvious.

---

*[pkg/storage/engine/mvcc.go, line 1227 at r18](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-L0odMUdfmTKnLCBFze3:-L0odMUdfmTKnLCBFze4:bs8y2gy) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2f6cc3af7eec14768e963e11f60133514a85497/pkg/storage/engine/mvcc.go#L1227)):*
> // Check for overflow and underflow, and perform Postgres-style sequence bounds checking.

---

*[pkg/storage/engine/mvcc_test.go, line 2265 at r19](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-L0ofHhHRS1HZ_U2RzN7:-L0ofHhIF7QvX6Ui7sQJ:b-rx394i) ([raw file](https://github.com/cockroachdb/cockroach/blob/dff24b921d8f55698d0ec377f0486054fbc07294/pkg/storage/engine/mvcc_test.go#L2265)):*
> ```Go
> // TestMVCCIncrementBounds verifies MVCCIncrement's behavior with respect to
> // its minVal, maxVal, cycle, and start arguments.
> func TestMVCCIncrementBounds(t *testing.T) {
> ```

Rename accordingly after the PG-hinting rename. Perhaps throw a link in that explains the desired semantics in PG.

---

*[pkg/storage/engine/mvcc_test.go, line 2284 at r19](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-L0oge0Pn5ysfznA0qGw:-L0oge0Pn5ysfznA0qGx:b-fdyd55) ([raw file](https://github.com/cockroachdb/cockroach/blob/dff24b921d8f55698d0ec377f0486054fbc07294/pkg/storage/engine/mvcc_test.go#L2284)):*
> ```Go
> 		// Verify behavior with Cycle = false.
> 		{
> 			initialVal: 0,
> ```

make this non-zero to verify that `CurrentValue` is actually populated in the error.

---

*[pkg/storage/engine/mvcc_test.go, line 2286 at r19](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-L0ogiRUMiX0Nt95QeQQ:-L0ogiRUMiX0Nt95QeQR:bfq4bom) ([raw file](https://github.com/cockroachdb/cockroach/blob/dff24b921d8f55698d0ec377f0486054fbc07294/pkg/storage/engine/mvcc_test.go#L2286)):*
> ```Go
> 			initialVal: 0,
> 			incBy:      10,
> 			opts:       roachpb.IncrementRequest_BoundsOptions{MinValue: 0, MaxValue: 5, Cycle: false},
> ```

Make `MinValue=1` to verify it's actually populated in the error.

---

*[pkg/storage/engine/mvcc_test.go, line 2288 at r19](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-L0ofSs9g2_Hi9NtEKw4:-L0ofSs9g2_Hi9NtEKw5:b-s3vjom) ([raw file](https://github.com/cockroachdb/cockroach/blob/dff24b921d8f55698d0ec377f0486054fbc07294/pkg/storage/engine/mvcc_test.go#L2288)):*
> ```Go
> 			opts:       roachpb.IncrementRequest_BoundsOptions{MinValue: 0, MaxValue: 5, Cycle: false},
> 			expectedErr: &roachpb.BoundsExceededError{
> 				MinValue: 0, MaxValue: 5, CurrentValue: 0, IncrementValue: 10, Overflow: false,
> ```

Test the edge case `IncBy=5` as well. (and `6` can replace `10` for a tighter test).

---

*[pkg/storage/engine/mvcc_test.go, line 2294 at r19](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-L0ogLmZXysAS0Q1C884:-L0ogLmZXysAS0Q1C885:b-qxbg8l) ([raw file](https://github.com/cockroachdb/cockroach/blob/dff24b921d8f55698d0ec377f0486054fbc07294/pkg/storage/engine/mvcc_test.go#L2294)):*
> ```Go
> 			initialVal: 0,
> 			incBy:      -1,
> 			opts:       roachpb.IncrementRequest_BoundsOptions{MinValue: 0, MaxValue: 5, Cycle: false},
> ```

Just for fun, test also the case `MinValue > or >= MaxValue`.

---

*[pkg/storage/engine/mvcc_test.go, line 2303 at r19](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-L0ogs7DQfrS8UcuZigu:-L0ogs7DQfrS8UcuZigv:bnw8jtl) ([raw file](https://github.com/cockroachdb/cockroach/blob/dff24b921d8f55698d0ec377f0486054fbc07294/pkg/storage/engine/mvcc_test.go#L2303)):*
> ```Go
> 			incBy:      1,
> 			opts: roachpb.IncrementRequest_BoundsOptions{
> 				MinValue: 0, MaxValue: math.MaxInt64, Cycle: false,
> ```

Also test this case when `MaxValue` is smaller (but `initialVal` remains). I suppose this could happen if a sequence's `MaxValue` is changed but it's good to exercise it either way.

---

*[pkg/storage/engine/mvcc_test.go, line 2364 at r19](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-L0og4fsi6LBLho_pFX0:-L0og4fsi6LBLho_pFX1:b5hg31x) ([raw file](https://github.com/cockroachdb/cockroach/blob/dff24b921d8f55698d0ec377f0486054fbc07294/pkg/storage/engine/mvcc_test.go#L2364)):*
> ```Go
> 	// Assign a different key for each case.
> 	for idx, boundsCase := range cases {
> 		key := roachpb.Key(fmt.Sprintf("/Table/%d/seqVal", idx))
> ```

nit: it rubs me the wrong way to take a pretty-printed SQL key and write it onto the engine verbatim.. I know there's nothing wrong with this, but errors would look confusing. If you want to oblige me, just make this `seq%d` or something the like. :smile: 

---

*[pkg/storage/engine/mvcc_test.go, line 2372 at r19](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-L0ohHhn_bzHsH5-SGmo:-L0ohHhn_bzHsH5-SGmp:b-6z4q0v) ([raw file](https://github.com/cockroachdb/cockroach/blob/dff24b921d8f55698d0ec377f0486054fbc07294/pkg/storage/engine/mvcc_test.go#L2372)):*
> ```Go
> 
> 	for idx, c := range cases {
> 		// Set initial value.
> ```

Just do `t.Run("", func(t *testing.T) { /* all your code */ }` and then you don't need `idx` at all (because the subtests will be numbered).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20574#-:-L0oi-caikTWJ36qB5f8:b-zhodba)*

**Comment by vilterp** [comment]
Closing in favor of #20973, which is basically the same but without `CYCLE` (and thus without the KV changes).

This PR is getting close, but there's still work left, and I think other sequence features (and admin UI work) have higher priority.

**Pull request closed without merging**
