### PR TITLE
changefeedccl: add option to stop changefeeds on schema change

### LINKED ISSUE #44265: changefeedccl: provide an option to finish changefeed upon schema change
**Is your feature request related to a problem? Please describe.**

A common use case for changefeeds is to provide replication of data from one primary database (source) to another (sink). One complicating aspect of changefeeds is that the underlying schema of the table being watched may change [1]. For certain schema changes [2], those which we say require a backfill, when a change to the logical schema becomes public, all rows of the table are re-emitted at exactly the commit timestamp of the transaction which made that change public. Some users have found this behavior to be annoying (#31213). Without the backfill the correctness of the changefeed is somewhat in doubt; the addition of a column is fundamentally a change to all existing rows [3].

If the primary use case of the changefeed is to keep two clusters in sync, this backfill and the write load it would incur could necessitate more resources on the sink cluster than were available on the source. In terms of additional overhead, the writes due to the actual index backfill (not the synthesized backfill) will also be emitted (#35738). Furthermore, if the sink's schema is not changed to correspond with the backfill, the backfill will not be useful. This issue finds the backfill behavior to be unacceptable.

In the common case, tables being kept in sink do not experience schema changes and when they do it is an operator-involved, active process. For this use case we should provide a mechanism which enables operators to keep a sink cluster up-to-date with low RTO and similar resource requirements to the source cluster. Furthermore there should be a story for that operator to perform schema changes on both clusters and resume changefeed-based synchronization.

**Describe the solution you'd like**

A simple solution would be to provide an option for changefeeds whereby instead of emitting a backfill of all rows in a table [4] when a relevant schema change is detected, the changefeed should wait to resolve that timestamp's predecessor and then exit gracefully. That graceful exit should likely indicate that the changefeed finished due to a schema change and ideally would include information about that schema change. 

On the whole, this solution does not seem so complicated. In cases of "barriers" today we wait for all underlying span frontiers to move to at least the `scanBoundary` and then we break out of the polling and perform the backfill. Furthermore we ensure that we do not emit any resolved timestamps. In this strategy, when we encounter a `scanBoundary` we should do the same waiting and filtering but then at the end instead of performing a backfill, we should emit a final resolved timestamp and then exit cleanly. 

The relevant code can be found [here](https://github.com/cockroachdb/cockroach/blob/545c96573d36519c27115278187fdd441f54a64d/pkg/ccl/changefeedccl/poller.go#L292-L348).

**Describe alternatives you've considered**

We could imagine a higher-touch system to coordinate schema changes between multiple clusters. 

**Additional context**

[1] All rows are emitted under the schema they will eventually always apply. Imagine a column is dropped at time t2 leading to schema version 2. A transaction which commits at time t3 might see the column due to the online schema change protocol. I.e. We allow transactions which commit after a schema change to use a schema version which precedes the commit. This leads to the interesting case that if we later did a historical read at that transactions commit timestamps, it will (eventually) not see the column as it will read data using version 2. When it comes to changefeeds we don't currently permit this ambiguity. As far as I'm concerned, we should not. 

[2] Column renames do not trigger a backfill but maybe they should.

[3] Perhaps a future project to correlate emitted rows with schema versions and a mechanism to understand the implications of transitions between two versions could enable the client to implement the backfill accordingly.

[4] We actually emit a backfill of all tables in the changefeed whenever any of them change (#43896).

### PR DESCRIPTION
**Pull request by ajwerner**
This PR adds two new concepts to `CHANGEFEED`s

1) Schema change events
2) Schema change policies

The former classifies what sort of schema change events to trigger a behavior
determined by the latter. The two classes of schema change events are
`default` and `column_changes`. Default corresponds to all `DROP COLUMN`
events as well as `ADD COLUMN` events for columns which have a non-null
default or are computed. `default` is the current default

The policies are `backfill` (the current behavior), `skip` which will perform
no logical backfills, and `stop` which will wait for all data preceding
the schema change to be resolved before exiting with an error indicating
the timestamp at which the schema change occurred.

It is critical that the client be able to create a new `CHANGEFEED`
at the timestamp following the schema change and in so doing skip the
logical backfill that would accompany it. This skipping of the logical
backfill when you start with a cursor that occurs at exactly that
timestamp is controversial but is the current implementation.

An alternative that has been floated is to only skip the logical backfill
if the user provides a new option to do so (this option is coming in a different
PR). In that case we'd want to enforce that we only fail if the schema change
occurs at a timestamp other than the initial cursor timestamp. I'm fine with
doing it either way but find this approach to be expedient and we should move
forward with it. 

Another rough edge in this PR is that the error does not inform the user
of the nature of the schema change which caused the changfeed to exit.
I intend to address that in a later PR.

Fixes #44265

Release note (enterprise change): Changefeeds provide new options to
control the types of schema change events the changefeed should respond
to (`schema_change_events`) and and the behavior to take when such an event
occurs (`schema_change_policy`). This functionality allows users to halt
changefeeds upon schema changes or skip over the logical backfill that
is performed by default.

### CODE REVIEW

**Comment by ajwerner** [comment]
@danhhz do you have time to give this a look?

**Review by danhhz — COMMENTED** [review]
About to head into a bunch of meetings, but here's what I have so far.

> This skipping of the logical backfill when you start with a cursor that occurs
at exactly that timestamp is controversial but is the current implementation.

I'm fine with this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45652#-:-M1aUOef75qZIctGKxgT:b-l9up77)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 387 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45652#-M1aBLkN6mkdCtg6mbJk:-M1aBLkOAzN4I2XBhPk1:bb7qfli) ([raw file](https://github.com/cockroachdb/cockroach/blob/60244548d7d32aaaccf3cdb4ec6e6a1146d1abd1/pkg/ccl/changefeedccl/changefeed_processors.go#L387)):*
> ```Go
> 	// the span frontier to reach the boundary, will drain, and then will exit.
> 	//
> 	// boundary values are communicated to the changeFrontier view Resolved
> ```

via?
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 577 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45652#-M1aBOdQ94NDvd1pNePy:-M1aBOdQ94NDvd1pNePz:bd7r24s) ([raw file](https://github.com/cockroachdb/cockroach/blob/60244548d7d32aaaccf3cdb4ec6e6a1146d1abd1/pkg/ccl/changefeedccl/changefeed_processors.go#L577)):*
> ```Go
> // NB: We don't need to check if the frontier moved past the boundary
> // because it can't. The check below is defensive. If there's a scan
> // boundary for any existing scan then
> ```

then...
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 582 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45652#-M1aBPWZ2rNguKQTgtDU:-M1aBPWZ2rNguKQTgtDV:bb7doun) ([raw file](https://github.com/cockroachdb/cockroach/blob/60244548d7d32aaaccf3cdb4ec6e6a1146d1abd1/pkg/ccl/changefeedccl/changefeed_processors.go#L582)):*
> ```Go
> }
> 
> // failOnSchemaChange checks the job's spec to d
> ```

d...
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 583 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45652#-M1aBVqyAilaTgTCbOtX:-M1aBVqyAilaTgTCbOtY:b2o95o9) ([raw file](https://github.com/cockroachdb/cockroach/blob/60244548d7d32aaaccf3cdb4ec6e6a1146d1abd1/pkg/ccl/changefeedccl/changefeed_processors.go#L583)):*
> ```Go
> 
> // failOnSchemaChange checks the job's spec to d
> func (cf *changeFrontier) failOnSchemaChange() bool {
> ```

shouldFailOnSchemaChange?
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 550 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45652#-M1aC_mP8YTN8xeqNrl7:-M1aC_mP8YTN8xeqNrl8:b8u3o8w) ([raw file](https://github.com/cockroachdb/cockroach/blob/60244548d7d32aaaccf3cdb4ec6e6a1146d1abd1/pkg/ccl/changefeedccl/changefeed_test.go#L550)):*
> ```Go
> func TestChangefeedSchemaChangeNoAllowBackfill(t *testing.T) {
> 	defer leaktest.AfterTest(t)()
> 	t.Skip("TODO(mrtracy): Re-enable when allow-backfill option is added.")
> ```

can we unskip this test now?
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 550 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45652#-M1aDXJXA6ZaYd-9B2HF:-M1aDXJXA6ZaYd-9B2HG:bskxfat) ([raw file](https://github.com/cockroachdb/cockroach/blob/60244548d7d32aaaccf3cdb4ec6e6a1146d1abd1/pkg/ccl/changefeedccl/changefeed_test.go#L550)):*
> ```Go
> func TestChangefeedSchemaChangeNoAllowBackfill(t *testing.T) {
> 	defer leaktest.AfterTest(t)()
> 	t.Skip("TODO(mrtracy): Re-enable when allow-backfill option is added.")
> ```

looks like we'd originally imagined an allow-backfill option, thoughts on that naming vs what you have here? I find "fail on schema change" to be pretty awkward. allow-backfill could also eventually be a multi-way option with "skip" which is something people have requested
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 1009 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45652#-M1aDJur2u9uw2QAlR5G:-M1aDJur2u9uw2QAlR5H:byfp64x) ([raw file](https://github.com/cockroachdb/cockroach/blob/60244548d7d32aaaccf3cdb4ec6e6a1146d1abd1/pkg/ccl/changefeedccl/changefeed_test.go#L1009)):*
> ```Go
> 		sqlDB.Exec(t, "SET CLUSTER SETTING kv.closed_timestamp.target_duration = '20ms'")
> 		t.Run("add column with backfill", func(t *testing.T) {
> 			sqlDB.Exec(t, `CREATE TABLE foo (a INT PRIMARY KEY)`)
> ```

different table name per subtest please

also I'm generally a bit confused about the relationship between this test you're adding and the skipped one i commented on above
___
*[pkg/ccl/changefeedccl/kvfeed/buffer.go, line 167 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45652#-M1aHMIF6pVKrEAvzFJY:-M1aHMIF6pVKrEAvzFJZ:bbsp142) ([raw file](https://github.com/cockroachdb/cockroach/blob/60244548d7d32aaaccf3cdb4ec6e6a1146d1abd1/pkg/ccl/changefeedccl/kvfeed/buffer.go#L167)):*
> ```Go
> // AddResolved inserts a Resolved timestamp notification in the buffer.
> func (b *chanBuffer) AddResolved(
> 	ctx context.Context, span roachpb.Span, ts hlc.Timestamp, boundaryReached bool,
> ```

hmm this is a little gross but I don't have a better idea : - /

**Review by ajwerner — COMMENTED** [review]
> About to head into a bunch of meetings, but here's what I have so far.


Ack. I'd love your feedback on the interface rather than the code if you can find the time between meetings this afternoon. There's a frustrating amount of urgency here. Sorry for not pushing on this earlier. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45652#-:-M1aokym7HfLlRSFN1oy:biam69e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @danhhz, and @mwang1026)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 550 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45652#-M1aDXJXA6ZaYd-9B2HF:-M1aV9it1zL-M41ld9l2:b-gzi09g) ([raw file](https://github.com/cockroachdb/cockroach/blob/60244548d7d32aaaccf3cdb4ec6e6a1146d1abd1/pkg/ccl/changefeedccl/changefeed_test.go#L550)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

looks like we'd originally imagined an allow-backfill option, thoughts on that naming vs what you have here? I find "fail on schema change" to be pretty awkward. allow-backfill could also eventually be a multi-way option with "skip" which is something people have requested
</blockquote></details>

hmm,  I also intend to add a PR to just skip the backfill. I'm fine rolling it into a single option.

I've been wondering how far I should break this down. There's a question of what schema events to consider and then what to do about them. The options for which schema events are:

All - almost certainly not what anybody wants, we have a lot of events which are not user visible

Index creation
Index deletion
Constraint addition
Constraint deletion
Column addition (nullable w/out default vs. others)
Column deletion

The set of behaviors are

Backfill - only applies to column changes. Currently the policy is to backfill on non-nullable column addition and column drops
Stop/Fail
NoBackfill/Skip

I sort of want to keep the setting space small but I'm torn. I also need to get something in soon. Additional relevant context is the protected timestamp adoption builds on the propagation of the scan boundaries. 

cc @mwang1026

My concrete proposal is the following:

Two new no-value options:
    * fail_on_column_change (the current thing but with a clearer name to indicate that it's not going to stop on index changes)
    * skip_backfill

These two options will be mutually exclusive. This should be specific enough to allow more general settings later to be well defined.
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 550 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45652#-M1aC_mP8YTN8xeqNrl7:-M1aWlPt2kEyhDkin0EN:brfwz03) ([raw file](https://github.com/cockroachdb/cockroach/blob/60244548d7d32aaaccf3cdb4ec6e6a1146d1abd1/pkg/ccl/changefeedccl/changefeed_test.go#L550)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

can we unskip this test now?
</blockquote></details>

Okay well this is very similar to what I wrote - I'll rework it. 
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 1009 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45652#-M1aDJur2u9uw2QAlR5G:-M1aV4tK3DCih-YkmeWC:b-cuijfj) ([raw file](https://github.com/cockroachdb/cockroach/blob/60244548d7d32aaaccf3cdb4ec6e6a1146d1abd1/pkg/ccl/changefeedccl/changefeed_test.go#L1009)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

different table name per subtest please

also I'm generally a bit confused about the relationship between this test you're adding and the skipped one i commented on above
</blockquote></details>

I deleted that one. Sorry for the noise. 
___
*[pkg/ccl/changefeedccl/kvfeed/buffer.go, line 167 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45652#-M1aHMIF6pVKrEAvzFJY:-M1aoxQx-wpBXXLRGZBe:b-mk7knh) ([raw file](https://github.com/cockroachdb/cockroach/blob/60244548d7d32aaaccf3cdb4ec6e6a1146d1abd1/pkg/ccl/changefeedccl/kvfeed/buffer.go#L167)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

hmm this is a little gross but I don't have a better idea : - /
</blockquote></details>

Eventually I'd like to rework this interface to take structs but for now I'm going to leave it.

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45652)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @danhhz, and @mwang1026)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 550 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45652#-M1aDXJXA6ZaYd-9B2HF:-M1apvdZ0zhEshTy5ExI:b-pkfsgw) ([raw file](https://github.com/cockroachdb/cockroach/blob/60244548d7d32aaaccf3cdb4ec6e6a1146d1abd1/pkg/ccl/changefeedccl/changefeed_test.go#L550)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

hmm,  I also intend to add a PR to just skip the backfill. I'm fine rolling it into a single option.

I've been wondering how far I should break this down. There's a question of what schema events to consider and then what to do about them. The options for which schema events are:

All - almost certainly not what anybody wants, we have a lot of events which are not user visible

Index creation
Index deletion
Constraint addition
Constraint deletion
Column addition (nullable w/out default vs. others)
Column deletion

The set of behaviors are

Backfill - only applies to column changes. Currently the policy is to backfill on non-nullable column addition and column drops
Stop/Fail
NoBackfill/Skip

I sort of want to keep the setting space small but I'm torn. I also need to get something in soon. Additional relevant context is the protected timestamp adoption builds on the propagation of the scan boundaries. 

cc @mwang1026

My concrete proposal is the following:

Two new no-value options:
    * fail_on_column_change (the current thing but with a clearer name to indicate that it's not going to stop on index changes)
    * skip_backfill

These two options will be mutually exclusive. This should be specific enough to allow more general settings later to be well defined.

</blockquote></details>

I understand the need for urgency, but I dislike the two no-value options. It feels cluttered and inconsistent and we're going to have to support them if we add them. The feedback that I've heard from customers is not in terms of schema changes but in terms of backfills. Some don't want them. The ones that don't want them either want to stop the changefeed and manually deal with the schema change or just silently skip over it. What's the issue with having a backfill=true/stop/skip option that defaults to true?

As for which types of schema changes backfill vs not, the historical answer has been driven by the thought exercise of "If I was filling elasticsearch from this changefeed, what would I need to ensure that it stayed up to date." So, for example, we don't backfill on any index schema changes because they wouldn't affect anything in this elasticsearch example. We do have to backfill when a column with a default is added (because the default can be an impure function, it'd be impossible to predict exactly what value it'll resolve to for each row). This thought exercise is also why we don't backfill when adding a nullable column with no default. The missing value would just be null anyway in elasticsearch.

Given this behavior, I don't see a reason that a customer would need to distinguish between the various types of schema changes that cause a backfill. I also haven't seen a customer ask for that. Have they recently since I've been out of the loop? If someone does eventually need this, my inclination would be to add a more complex option for these complex cases and keep the simple thing simple.

**Comment by ajwerner** [comment]
> I also haven't seen a customer ask for that. Have they recently since I've been out of the loop? 

The motivation for this PR is to allow customers to keep two clusters in sync w.r.t. schema. They absolutely need the changefeed to stop when a nullable column is added. What's bothering me is that this behavior will now be distinct from the backfill behavior.

There are other problems not specifically addressed by this PR that makes the above somewhat difficult - namely the sink cluster will be notified about the new column once it's gone public - not when the backfill begins. Ideally we'd tell the customer that the column is being added so that they could start adding it on the sink and then we'd also stop once it become public to ensure that the sink cluster has finished its backfill. But alas, that's a somewhat different discussion.

**Comment by ajwerner** [comment]
cc @mwang1026 in general here

**Comment by ajwerner** [comment]
@danhhz this has been updated to reflect our conversation and is RFAL. Sorry for the distracting cosmetic changes, had I had more time I would have split them out into another commit.

It deserves more testing in the context of the anticipated use case but I'd rather merge it and add the testing later as I have another PR that relies on the boundary propagation. That being said, I'm not trying to force you to accept something you don't like and am happy to iterate further.

**Comment by ajwerner** [comment]
Flaked multiple times on https://github.com/cockroachdb/cockroach/issues/38257

**Review by danhhz — COMMENTED** [review]
:lgtm: Thanks for your patience in hashing out the public interface to this, I feel like it ended up in a much better place

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45652#-:-M1fSD1D2tzOjPMAr54R:b6jsvk0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @danhhz, and @mwang1026)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 913 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/45652#-M1fRg_mD_gdrPN_WCPV:-M1fRg_mD_gdrPN_WCPW:b-r9ysv7) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d94e938ef86ad7b9e4cfd4b21c3f6616e86c624/pkg/ccl/changefeedccl/changefeed_test.go#L913)):*
> ```Go
> }
> 
> func TestChangefeedStopOnSchemaChange(t *testing.T) {
> ```

can we get at least one end-to-end test of skip please?
___
*[pkg/ccl/changefeedccl/changefeedbase/options.go, line 53 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/45652#-M1fQZ0F5FX77yHL0qNc:-M1fQZ0F5FX77yHL0qNd:bbb73mz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d94e938ef86ad7b9e4cfd4b21c3f6616e86c624/pkg/ccl/changefeedccl/changefeedbase/options.go#L53)):*
> ```Go
> 	// OptSchemaChangePolicySkip indicates that when a schema change event occurs
> 	// no backfill should occur and the changefeed should continue.
> 	OptSchemaChangePolicySkip SchemaChangePolicy = `skip`
> ```

with fresh eyes, "skip" sounds a little ambiguous to me. "nobackfill" is wordy but very clear. maybe there's some better third option?
___
*[pkg/ccl/changefeedccl/kvfeed/kv_feed.go, line 102 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/45652#-M1fQxsl5hEHDOvDZabA:-M1fQxsl5hEHDOvDZabB:b48vzln) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d94e938ef86ad7b9e4cfd4b21c3f6616e86c624/pkg/ccl/changefeedccl/kvfeed/kv_feed.go#L102)):*
> ```Go
> 	// policy and tear everything down. Returning before the higher layers tear
> 	// down the changefeed exposes synchronization challenges.
> 	if e, isSchemaChangeDetected := err.(schemaChangeDetectedError); isSchemaChangeDetected {
> ```

is there an errors.Is or something we should be using here?
___
*[pkg/ccl/changefeedccl/schemafeed/schematestutils/schema_test_utils.go, line 22 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/45652#-M1fRZB34PhM2aBojWCx:-M1fRZB34PhM2aBojWCy:b-tmcitm) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d94e938ef86ad7b9e4cfd4b21c3f6616e86c624/pkg/ccl/changefeedccl/schemafeed/schematestutils/schema_test_utils.go#L22)):*
> ```Go
> )
> 
> // MakeTableDesc makes a generic tan;e descriptor with the provided properties.
> ```

"tan;e"->table?

**Review by ajwerner — COMMENTED** [review]
TFTR! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45652#-:-M1f_gSyDnSBZobAixVD:bz5m8k4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 387 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45652#-M1aBLkN6mkdCtg6mbJk:-M1cEqzMC7oSPv4cDYKb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/60244548d7d32aaaccf3cdb4ec6e6a1146d1abd1/pkg/ccl/changefeedccl/changefeed_processors.go#L387)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

via?
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 577 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45652#-M1aBOdQ94NDvd1pNePy:-M1cExG6-QMhNm01-3mH:b5iz9ce) ([raw file](https://github.com/cockroachdb/cockroach/blob/60244548d7d32aaaccf3cdb4ec6e6a1146d1abd1/pkg/ccl/changefeedccl/changefeed_processors.go#L577)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

then...
</blockquote></details>

whoops removed this defensive check.
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 582 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45652#-M1aBPWZ2rNguKQTgtDU:-M1cFg_VE340LK6Whrbf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/60244548d7d32aaaccf3cdb4ec6e6a1146d1abd1/pkg/ccl/changefeedccl/changefeed_processors.go#L582)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

d...
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 583 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45652#-M1aBVqyAilaTgTCbOtX:-M1cFhev39OrcKsV14m-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/60244548d7d32aaaccf3cdb4ec6e6a1146d1abd1/pkg/ccl/changefeedccl/changefeed_processors.go#L583)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

shouldFailOnSchemaChange?
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 913 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/45652#-M1fRg_mD_gdrPN_WCPV:-M1f_bDJ93b32fuxPPwo:b-i7xfhi) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d94e938ef86ad7b9e4cfd4b21c3f6616e86c624/pkg/ccl/changefeedccl/changefeed_test.go#L913)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

can we get at least one end-to-end test of skip please?
</blockquote></details>

Added a suite.
___
*[pkg/ccl/changefeedccl/changefeedbase/options.go, line 53 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/45652#-M1fQZ0F5FX77yHL0qNc:-M1f_aLN3CKJaO-IJkMr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d94e938ef86ad7b9e4cfd4b21c3f6616e86c624/pkg/ccl/changefeedccl/changefeedbase/options.go#L53)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

with fresh eyes, "skip" sounds a little ambiguous to me. "nobackfill" is wordy but very clear. maybe there's some better third option?
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/kvfeed/kv_feed.go, line 102 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/45652#-M1fQxsl5hEHDOvDZabA:-M1fTqoIDOs11aleqTkK:b-aei7oq) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d94e938ef86ad7b9e4cfd4b21c3f6616e86c624/pkg/ccl/changefeedccl/kvfeed/kv_feed.go#L102)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

is there an errors.Is or something we should be using here?
</blockquote></details>

There's a thing. It allocates which leads me to often not use it but this is far from performance critical. Done. 
___
*[pkg/ccl/changefeedccl/schemafeed/schematestutils/schema_test_utils.go, line 22 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/45652#-M1fRZB34PhM2aBojWCx:-M1f_ZmKBXVgtxM689WI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d94e938ef86ad7b9e4cfd4b21c3f6616e86c624/pkg/ccl/changefeedccl/schemafeed/schematestutils/schema_test_utils.go#L22)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

"tan;e"->table?
</blockquote></details>

Done.

**Comment by ajwerner** [comment]
TFTR!

bors r=danhhz

**Pull request merged**
