### PR TITLE
ui: add window titles for pages

### PR DESCRIPTION
**Pull request by couchand**
This updates the window title as a user navigates around the admin UI, making the browser history much more useful.

Fixes: #18408

screen shot 2018-04-10 at 12 48 34 pm

### CODE REVIEW

**Review by vilterp — APPROVED** [review]
LGTM! Browsed around for awhile and everywhere I went had a useful title.

Also `TitledComponent` was weird; glad to get rid of it.

**Comment by couchand** [comment]
unrelated flaky failed test
bors r+

**Pull request merged**
