### PR TITLE
Migrate from glock to govendor

### PR DESCRIPTION
**Pull request by madelynnblue**
[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4620)

### CODE REVIEW

**Comment by bdarnell** [comment]
I am strongly opposed to checking in a snapshot of all our dependencies' source like this. It bloats the repo and makes it difficult to make local changes in a way that can be contributed upstream. My preferences (in order) would be:

1. Use some tool to pull in the dependencies at build time like glock does
2. git submodules
3. git subtree (which still bloats the repo but has better tracking of upstream revisions)

**Comment by tamird** [comment]
+1 for the same reasons.

**Comment by mjibson** [comment]
Ok. Never mind I guess. I have zero interest in using git trickery.

**Comment by kardianos** [comment]
Remote dep fetch and sync is on govendor roadmap. Next item actually. This is one of the projects I will ensure works with current workflow.

Benefit over glock is use of vendor folder, which lets you share GOPATH with other projects.

**Comment by mjibson** [comment]
@kardianos Thanks. Can you either update this issue or provide one for us to track so we can try it out once it's done?

**Comment by mjibson** [comment]
https://medium.com/@azerbike/i-ve-just-liberated-my-modules-9045c06be67c#.vz5v94ygo is exactly why I think vendoring is a great idea. If we don't put all of the code into our repo, we can get into a situation exactly like this where cockroach is unbuildable from a fresh $GOPATH because someone just decided to unpublish their code.

**Comment by abh** [comment]
+2 on vendoring. The current scheme is really unfriendly to new users. In my experience it also has a side-effect of not appreciating the cost of adding dependencies; as a developer it feels too cheap to add "just one more".

**Comment by dt** [comment]
@abh there's another vendoring PR out that takes a slightly different approach -- adding a submodule -- but achieves mostly the same results: #8618

**Pull request closed without merging**
