### PR TITLE
gossip: test random peer selection for forwarding

### LINKED ISSUE #5912: gossip: add a test that a server does not return itself as an AlternateAddr
See #5901 which fixed the bug.

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #5912.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5917)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[gossip/server.go, line 144 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5917#-KEl7w1xNiRE9NGNknaT:-KEl7w1yah-R65i7YpAy:1605915490) ([raw file](https://github.com/cockroachdb/cockroach/blob/b56a3b907ced6618d996f22109542c257f13983f/gossip/server.go#L144)):*
incomplete comment

---

*[gossip/server.go, line 160 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5917#-KEl8NyUToCg3UrbOXSU:-KEl8NyUToCg3UrbOXSV:1558828907) ([raw file](https://github.com/cockroachdb/cockroach/blob/b56a3b907ced6618d996f22109542c257f13983f/gossip/server.go#L160)):*
I guess this is more a comment on the original fix, but if there are three nodes and we are number 3, then the second node will be chosen 2 out of 3 times..  We should first count how many nodes equal `selfID`.

By the way, would we in practice have multiple addresses for the same node? If so, do we want that node to be chosen more often than others? If not, maybe we want to build a map of IDs..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5917)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[gossip/server.go, line 144 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5917#-KEl7w1xNiRE9NGNknaT:-KElBOAUE6PxWf0ep10a:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/b56a3b907ced6618d996f22109542c257f13983f/gossip/server.go#L144)):*
Done.

---

*[gossip/server.go, line 160 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5917#-KEl8NyUToCg3UrbOXSU:-KElAtlQUCnU4S8SLXgF:549241727) ([raw file](https://github.com/cockroachdb/cockroach/blob/b56a3b907ced6618d996f22109542c257f13983f/gossip/server.go#L160)):*
Yeah, the random peer selection is not a uniform selection. Note that map iteration is randomized in Go (though that isn't guaranteed) which makes the analysis more confusing. I'm not sure if this is worth fixing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5917)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[gossip/server.go, line 160 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5917#-KEl8NyUToCg3UrbOXSU:-KElDv97WL3amkrcC5Eg:-1410424295) ([raw file](https://github.com/cockroachdb/cockroach/blob/b56a3b907ced6618d996f22109542c257f13983f/gossip/server.go#L160)):*
A haha I didn't know each iteration starts from an arbitrary offset. That pretty much fixes the concern I had.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5917#-:-KElES6QrjMKHENCFadS:1417088721)*

**Comment by tamird** [comment]
I don't think this is right way to go about this. I'll have an alternate PR out shortly

**Comment by RaduBerinde** [comment]
---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5917#-:-KElIe9Tr396Y5qEWA4m:1773909167)*

**Pull request closed without merging**
