### PR TITLE
*: update to use gogoproto v1.3

### LINKED ISSUE #56378: deps: go.mod announces compatibility with gogoproto v1.3 but hardwires v1.2
tldr: `go.mod` contains contradictory and invalid information, and endangers future dep upgrades.

See section "what we can do about this" below for suggested courses of action.

### Description of the problem

The `go.mod` does something illegal: it announces that the vendor tree provides gogoproto v1.3:

```
...
        github.com/gogo/protobuf v1.3.1
...
```

However it also pins the source code to our own fork which is anchored at v1.2:

```
replace github.com/gogo/protobuf => github.com/cockroachdb/gogoproto v1.2.1-0.20190102194534-ca10b809dba0
```

This contradicting specification creates a looming dependency breakage: if any package is upgraded to start depending on gogoproto  features specific to v1.3, then `go mod` will silently pick it up, and then the build will fail -- for example, with this error:

```
    variable or constant definition not found: proto.GoGoPackageIsVersion3
``` 

### Background (why this situation came to be)

CockroachDB was historically anchored to gogoproto v1.2. This is because when v1.2 came about, there was a bug in its implementation of generated `.Clone()` and `.Equal()` methods. So we forked the gogoproto repository at v1.2.4, and added a patch to this bug there. See [this upstream PR for details](https://github.com/gogo/protobuf/pull/529) 

Now, this particular bug was fixed in gogoproto v1.3, however since we used a forked repo we did not notice.

However, at some point in the last year we migrated from using `dep` to `go mod` to manage dependencies. During that upgrade, we mistakenly let `go mod` pick up version v1.3 as the *announced* tag in the list of dependencies, while retaining the  `replace` directive that was pinning the source code v1.2.

In effect, this mistake makes our `go.mod` "lie" to every other dependency about which version of gogoproto is available.

So if any other dependency starts using v1.3 features (as they could!), `go mod` would be unable to detect the incompatibility and we would get build failures without explanation.

### Why this is hard to fix

In addition to fixing the bug in v1.2 which prevented us from upgrading, v1.3 has introduced numerous optimizations and enhancements.

In particular, it introduces a new optimization to "optimize allocations when decoding protobufs": the new `Marshal()` methods *encode the fields from largest to smallest*, as opposed to increasing order of protobuf ID as previously.

This is causing a new / different problem in CockroachDB: we were assuming that the protobuf encoding is stable and deterministic for a given input data structure across all versions. This is because we want to be able to compare KV replicas byte-by-byte to determine equivalence; see `pkg/kv/kvserver/below_raft_protos_test.go`. This assumption is CockroachDB-specific -- protobuf allows different encoding orders in its spec, so the gogoproto optimization is legitimate.

Therefore, we are now unable to upgrade from v1.2 to a "native" gogoproto v1.3 because of this reordering.

### What we can do about this

- rewind the `go.mod` announced dependency to v1.2 so it does not "lie" anymore
  - pros: conceptually simple
  - cons: unclear whether this is supported at all by `go mod`
  - cons: makes us unable to benefit from the other optimizations in gogoproto

- upgrade to "native" gogoproto v1.3
  - pros: simplifies dep management
  - cons: requires new logic in cockroachdb to tolerate this reordering (i.e. introduce a "slow path" in the replica divergence detection code, that decodes the content to determine structural equivalence)
  - cons: makes replica consistency checks generally slower whenever we add new fields to protobufs that are larger than other fields

- fork gogoproto v1.3 and remove the specific undesirable reordering optimization
  - pros: minimal changes to cockroachdb
  - pros: some other optimizations in v1.3 are still available
  - cons: still need to manage a custom fork (but this is no worse than the status quo)

### PR DESCRIPTION
**Pull request by knz**
Fixes #56378. 

To achieve this version upgrade, some care needed to be taken:

- previously, `go.mod` was anchoring gogoproto to v1.2 and
  our own fork at github.com/cockroachdb/gogoproto.

  This fork was needed because the original v1.2 gogoproto
  had a bug, and our upstream PR was never merged:
  gogo/protobuf#529

  Thankfully, gogoproto did eventually fix that bug upstream (in a
  different way) so we do not need the custom patch anymore in v1.3.

  So this commit drops the anchor and lets the code start
  to depend on upstream gogoproto v1.3.1.

- doing so causes all `.pb.go` files to be updated, using the
  latest protobuf code generation changes in gogoproto v1.3.

  In particular, v1.3 extends its `Message` interface with a new
  method:

  ```go
  MarshalToSizedBuffer(data []byte) (int, error)
  ```

  This behaves like `MarshalTo()` but requires the buffer to have
  space already for at least `.Size()` more bytes.

- because of this new method, `.pb.go` code now requires all its
  recursively needed `Message` types to also implement the new method.

  In CockroachDB we have two "external" `.pb.go` dependencies and osome
  internal custom `Message` implementations (non-autogenerated):

  - `raftpb` for etcd's Raft protobuf messages
  - `errorspb` from `cockroachdb/errors`
  - the `sql/types.T` type.
  - the `util/hlc.ClockTimestamp` type.

  All these need to be upgraded to satisfy the new interface.

- to upgrade `sql/types.T`, this patch adds the missing method
  (by means of extending `util/protoutil/marshal.go` accordingly.

Because of the transitive minimum version dependencies in `etcd` and
`gogo/protobuf`, a couple of other packages were also updated:

- github.com/cockroachdb/errors
- github.com/gogo/protobuf
- github.com/golang/protobuf
- github.com/google/go-cmp
- github.com/google/uuid
- go.etcd.io/etcd/raft
- golang.org/x/net
- golang.org/x/sys
- golang.org/x/text
- golang.org/x/time

The changes seem fairly contained but the reviewer is invited to take
a cursory look nonetheless.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
Note that I purposefully did not entertain the idea to upgrade `etcd` to the latest version, which would liberate it from its hard dependency on an outdated `grpc` version (the one that also blocks crdb from upgrading to the latest `grpc`). 

We could do that as well but I would imagine we'd only want to do that in a separate/subsequent step to not see to many pieces moving simultaneously.

**Comment by knz** [comment]
@tbg will appreciate your extra scrutiny to the change in `kvserver/below_raft_protos_test.go`.

I am a bit worried that the fact this has to change is that the new encoding functions in gogoproto do their work differently. What would be a good way to determine what's up?

**Comment by tbg** [comment]
`etcd/raft` is now its own module with thin dependencies:

```
require (
	github.com/cockroachdb/datadriven v0.0.0-20200714090401-bf6692d28da5
	github.com/gogo/protobuf v1.3.1
	github.com/golang/protobuf v1.3.5
	github.com/pkg/errors v0.9.1 // indirect
	go.etcd.io/etcd/pkg/v3 v3.0.0-00010101000000-000000000000
)
```

I will check if we can move back to master.

**Comment by tbg** [comment]
re: the below raft protos test, I think you've already found the answers in Slack (https://cockroachlabs.slack.com/archives/C0KB9Q03D/p1604336170406900), and I hope that pans out.

**Comment by knz** [comment]
Here's the analysis: #56378

**Review by andreimatei — DISMISSED** [review]
You've probably seen that Tobi brought us back to using upstream Raft in https://github.com/cockroachdb/cockroach/pull/56233. But does this here PR mean that we either fork Raft again to regenerate the protos, or we push an upgrade upstream? Or perhaps some hackery in between where we keep using upstream but have the makefile refenerate their `pb.go`'s?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56147#-:-MY1dUvm73xpQ5JWQ1ey:b2xr1gs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @dt, @knz, @RaduBerinde, and @tbg)

___
*[pkg/kv/kvserver/below_raft_protos_test.go, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56147#-MY1ZDih8dh0NCQZb4UA:-MY1ZDih8dh0NCQZb4UB:bjvz21m) ([raw file](https://github.com/cockroachdb/cockroach/blob/7df90ca33fa8ac4d207244e6b8c11a46ce90bd12/pkg/kv/kvserver/below_raft_protos_test.go#L84)):*
> ```Go
> 				Vote                 uint64
> 				Commit               uint64
> 				XXX_NoUnkeyedLiteral struct{}
> ```

I think this is fishy here and below. Upstream Raft doesn't have these two new fields, as neither did the version we (obvi).
Upstream: https://github.com/etcd-io/etcd/blob/master/raft/raftpb/raft.pb.go#L436
I'm thinking perhaps when you've re-generated the protos for our raft fork, one way or another you haven't used the compiler options that upstream does?

FWIW, cockroach also doesn't have any of these fields, including `XXX_unrecognized` (although I think not having that one is a mistake) curtsy of passing these go the compiler:
```
vanity.TurnOffGoUnrecognizedAll,
vanity.TurnOffGoUnkeyedAll,
vanity.TurnOffGoSizecacheAll,
```

**Comment by knz** [comment]
I have rebased this and fixed up what needs to be fixed up.

Right now the code is broken however because of the `errorspb` dependency:

```
# github.com/cockroachdb/cockroach/pkg/roachpb
pkg/roachpb/errors.pb.go:4123:30: m.EncodedError.MarshalToSizedBuffer undefined (type errorspb.EncodedError has no field or method MarshalToSizedBuffer)
```

**Comment by knz** [comment]
Ok this should be ready for review (again) now.
cc @erikgrinaker @andreimatei @tbg

**Comment by andreimatei** [comment]
I'm wondering about what I was asking above - how do we deal with the protos in the etcd/raft dependency now that we've moved to using the upstream code and not our? What compiler version do those protos require? Did you have to fork it again?

**Comment by knz** [comment]
> how do we deal with the protos in the etcd/raft dependency now that we've moved to using the upstream code and not our?

This has been done by Tobias in #56233 and we don't need customizations any more.

> What compiler version do those protos require? Did you have to fork it again?

Apparently not.

**Comment by knz** [comment]
> I am a bit worried that the fact this has to change is that the new encoding functions in gogoproto do their work differently. What would be a good way to determine what's up?

As found out by @bdarnell the changes were due to the different random seed using by gogoproto to generate random payloads. There is otherwise no change in the marshalling, so no risk for crdb clusters.

**Comment by knz** [comment]
FWIW this passes CI :tada:

**Review by erikgrinaker — APPROVED** [review]
Love seeing this.

>As found out by @bdarnell the changes were due to the different random seed using by gogoproto to generate random payloads. There is otherwise no change in the marshalling, so no risk for crdb clusters.

Do we have (cross-version) tests in place that verify this, beyond `belowRaftGoldenProtos`?

> Reviewed 5 of 141 files at r1, 162 of 162 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56147#-:-MYFSBKb2GIDYEbEjKEf:b-yj7a4m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @dt, @knz, @RaduBerinde, and @tbg)

___
*[go.mod, line 170 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56147#-MYFQ7R08kjMZmgWyt05:-MYFQ7R08kjMZmgWyt06:b3axgw) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a73dc82f91fdb735e8ce89d68b014bc02f66d4d/go.mod#L170)):*
> ```XML
> )
> 
> replace github.com/gogo/protobuf => github.com/cockroachdb/gogoproto v1.2.1-0.20210111172841-8b6737fea948
> ```

❤️

**Comment by knz** [comment]
> Do we have (cross-version) tests in place that verify this, beyond belowRaftGoldenProtos?

There's the multi-version roachtest, which runs a cluster migrated across successive versions.

**Comment by knz** [comment]
I'm going to go ahead and merge this. If we need to polish this further, we can do this in subsequent PRs.

bors r=erikgrinaker

**Pull request merged**
