### PR TITLE
storage: Cap the size of raft logs included in preemptive snapshots

### PR DESCRIPTION
**Pull request by bdarnell**
The first of three PRs related to OOMs caused by large raft logs. 

Release note (bug fix): Fix out-of-memory errors caused by very large
raft logs.

### CODE REVIEW

**Comment by bdarnell** [comment]
I've added a second commit to this PR. The third will take a bit longer because it's an etcd change. It's also less critical because the cluster where these problems were observed managed to eventually recover without it.

**Review by nvb — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28293)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica_raftstorage.go, line 667 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28293#-LJKV6buAK60UY7WPGET:-LJKV6buAK60UY7WPGEU:b-6qfdec) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e09a7f7afada431cc8f81300f17d54b8b131a3c/pkg/storage/replica_raftstorage.go#L667)):*
> ```Go
> 	for _, keyRange := range keyRanges {
> 		// Peek into the range to see whether it's large enough to justify
> 		// ClearRange.
> ```

Add to this comment that this touches at most `clearRangeMinKeys` keys, so it should be cheap.
___
*[pkg/storage/store_snapshot.go, line 242 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28293#-LJKULZh2vOQdAY_ljOG:-LJKULZo7GJONbQvEacV:b-8r0l98) ([raw file](https://github.com/cockroachdb/cockroach/blob/dda4bc919fb5d0f898874c87547724b22fe41517/pkg/storage/store_snapshot.go#L242)):*
> ```Go
> 				// reasonable threshold. (Empirically, this is good enough:
> 				// the situations that result in large raft logs have not been
> 				// observed to result in raft-initiated snapshots).
> ```

If we no longer send preemptive snapshots for ranges with large raft logs then won't this just shift the problem over to raft-initiated snapshots once new replicas are added?

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28293)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica_raftstorage.go, line 667 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28293#-LJKV6buAK60UY7WPGET:-LJOzGwA31SO0vf0BB8P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e09a7f7afada431cc8f81300f17d54b8b131a3c/pkg/storage/replica_raftstorage.go#L667)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Add to this comment that this touches at most `clearRangeMinKeys` keys, so it should be cheap.
</blockquote></details>

Done.
___
*[pkg/storage/store_snapshot.go, line 242 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28293#-LJKULZh2vOQdAY_ljOG:-LJOyzFrAsHDx5csvFuA:b-8h4yud) ([raw file](https://github.com/cockroachdb/cockroach/blob/dda4bc919fb5d0f898874c87547724b22fe41517/pkg/storage/store_snapshot.go#L242)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

If we no longer send preemptive snapshots for ranges with large raft logs then won't this just shift the problem over to raft-initiated snapshots once new replicas are added?
</blockquote></details>

Blocking preemptive snapshots also blocks the addition of replicas. So if there is an underreplicated range with a large log, it will have to catch up on its log and truncate it before it will be able to upreplicate. (Unavailable ranges won't be able to do this, but they can't upreplicate either).

**Review by nvb — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28293#-:-LJPeNGaBPGE3KKS8592:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/store_snapshot.go, line 242 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28293#-LJKULZh2vOQdAY_ljOG:-LJPeKQYANw1cbjyN9A-:b-z824jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/dda4bc919fb5d0f898874c87547724b22fe41517/pkg/storage/store_snapshot.go#L242)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Blocking preemptive snapshots also blocks the addition of replicas. So if there is an underreplicated range with a large log, it will have to catch up on its log and truncate it before it will be able to upreplicate. (Unavailable ranges won't be able to do this, but they can't upreplicate either). 
</blockquote></details>

Got it. Could you add this to the comment?

**Comment by bdarnell** [comment]
bors r=nvanbenschoten

**Pull request merged**
