### PR TITLE
roachtest: use an interface instead of direct access to *cluster

### PR DESCRIPTION
**Pull request by tbg**
a.k.a "boiling the ocean". Roachtests now use `clusterI` instead of
`cluster`. The immediate benefit of this is that there is an interface
to look at that at least gives a basic idea of what `*cluster` can do,
without seeing all of the internals.

A second benefit is that this addresses a long-standing TODO, namely to
phase out `*cluster.{t,l}` (in favor of using the test's `t *test`).
These aren't quite removed yet - internals still touch them all over
the place - but the tests now don't have access to either any more.

- roachtest: extract an interface from `cluster`
- roachtest: use clusterI in runKVBench
- roachtest: use clusterI in allocator test
- roachtest: use clusterI in acceptance/*
- roachtest: use clusterI in ORM tests
- roachtest: take clusterI in `testSpec.Run`

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
Btw the battle plan here is to extract this interface into its own package as a main step towards teasing the roachtest monolith apart. This is going to require a few ounces of elbow grease. This is probably ~50 commits away, there are so many dependencies under this interface (`*test*, `nodeSpec`, `*logger`), etc, it will take time.

**Review by erikgrinaker — COMMENTED** [review]
Sure hope Goland gave you a hand with this. 😅

If the primary motivation is to remove access to e.g. `t` and `l`, isn't this better done with private fields? If we're never going to have more than one implementation of this interface it seems a bit heavy-handed, and I could see it get annoying to have to keep it in sync. For an overview of methods, I always use my IDEs struct outline anyway. Not a strongly held view though.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66355#-:-MbzSMIjCZ9ov_GsIJon:behywmp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

**Comment by tbg** [comment]
TFTR! Goland did a lot of the work here. The "extract interface" tool is great :-) But I did have to do a bunch of search+replace as well. Not the most three hours of my life but the result is satisfying enough.

> If the primary motivation is to remove access to e.g. t and l, isn't this better done with private fields?

I agree, but it's not the primary motivation. It's just something nice that's falling out of it. The primary motivation is for someone (currently myself) to go in and provide a clear contract to tests. This is inspired by our thinking about a higher-level test harness; I wanted to get an idea of what the current surface is like and extracting it into an interface is a useful exercise here.

In general I'm also not a fan of single-impl interfaces - they add this extra opaque hop if you want to look at the code - but note that

a) everything is in a single `main` package here, so there's no decent way to hide the internals, and you can't really pull things out into leaf packages because nobody's allowed to `import main`; I think the easiest way is to extract the interface and then try to get to the point where we can pull that elsewhere (at which point you can do the same with individual tests).
b) I hope this isn't going to be a single-impl interface! We currently don't have a second impl, but we currently also only have very weak testing of the `roachtest` harness itself. To change that, we need to mock out parts of it. Being able to mock out the physical cluster is the biggest challenge here. The interface + go-mock gets us there.
c) I haven't necessarily considered "all of the options" for cleaning up this package, but there's so much wrong with it that I just went with what felt right 😄 

bors r=erikgrinaker

**Review by erikgrinaker — APPROVED** [review]
Ah, I didn't connect this with the multi-test-runner idea at first -- makes sense!

**Pull request merged**
