### PR TITLE
roachtest: move cmd/zerosum to a roachtest

### PR DESCRIPTION
**Pull request by m-schneider**
closes: 29486

Release note: None

### CODE REVIEW

**Review by m-schneider — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31011)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/acceptance.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31011#-LO3tyC164opCfImS2rN:-LO3tyC29W3R-o3A7Vsp:b-2ovks6) ([raw file](https://github.com/cockroachdb/cockroach/blob/29f5594b9879f212f66bd6365e05554a2dcb6f76/pkg/cmd/roachtest/acceptance.go#L40)):*
> ```Go
> 		{"bank/cluster-recovery", runBankClusterRecovery},
> 		{"bank/node-restart", runBankNodeRestart},
> 		{"bank/zerosum", runBankNodeZeroSum},
> ```

There's already a test with basic chaos that restarts node, do we need another test the combines the splits and lease transfers and the restarts?
___
*[pkg/cmd/roachtest/bank.go, line 293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31011#-LO3tklU0zMmQ-y0hsCE:-LO3tklU0zMmQ-y0hsCF:b3x7uf7) ([raw file](https://github.com/cockroachdb/cockroach/blob/29f5594b9879f212f66bd6365e05554a2dcb6f76/pkg/cmd/roachtest/bank.go#L293)):*
> ```Go
> 			}
> 		case 1:
> 			zipF := partitionDistribution(r, partitions)
> ```

My biggest question on this test is whether or not partitioning and changing lease preferences is a reasonable alternative to the original lease transfers.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31011)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/acceptance.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31011#-LO3tyC164opCfImS2rN:-LO3v-sQ47VjqR482JHG:b-fxfx7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/29f5594b9879f212f66bd6365e05554a2dcb6f76/pkg/cmd/roachtest/acceptance.go#L40)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

There's already a test with basic chaos that restarts node, do we need another test the combines the splits and lease transfers and the restarts?
</blockquote></details>

Yes. Doing them all at the same time is what leads to interesting badness. In particular, splitting and lease transfers at the same time a node is being restarted is the interesting bit.
___
*[pkg/cmd/roachtest/bank.go, line 293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31011#-LO3tklU0zMmQ-y0hsCE:-LO3uHTa0u5y7tOCuR72:bipv58n) ([raw file](https://github.com/cockroachdb/cockroach/blob/29f5594b9879f212f66bd6365e05554a2dcb6f76/pkg/cmd/roachtest/bank.go#L293)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

My biggest question on this test is whether or not partitioning and changing lease preferences is a reasonable alternative to the original lease transfers.
</blockquote></details>

It's interesting, but different. The downside to adjust lease holder preferences is how asynchronous that is. I think you can use `ALTER TABLE ... EXPERIMENTAL_RELOCATE LEASE ...` in order to maintain the original behavior.

**Comment by m-schneider** [comment]
___
*[pkg/cmd/roachtest/bank.go, line 293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31011#-LO3tklU0zMmQ-y0hsCE:-LOJHFLu0vU4Vo9Ses37:b-76e0mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/29f5594b9879f212f66bd6365e05554a2dcb6f76/pkg/cmd/roachtest/bank.go#L293)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

It's interesting, but different. The downside to adjust lease holder preferences is how asynchronous that is. I think you can use `ALTER TABLE ... EXPERIMENTAL_RELOCATE LEASE ...` in order to maintain the original behavior.
</blockquote></details>

I added the ALTER TABLE ... EXPERIMENTAL_RELOCATE LEASE ... behavior, but I'm seeing a lot of errors of the form:

```
pq: change replicas of r24 failed: [n1,s1,r24/1:/Table/53/1/{258-408}]: received invalid ChangeReplicasTrigger REMOVE_REPLICA((n1,s1):1): updated=[(n2,s2):3 (n4,s4):2] next=4 to remove self (leaseholder)round 12: setting partition lease preferences for partition 582 to node 2

pq: change replicas of r29 failed: descriptor changed: [expected] r29:/Table/53/1/{265-319} [(n1,s1):1, (n4,s4):5, next=6, gen=0] != [actual] r29:/Table/53/1/{265-319} [(n1,s1):1, (n4,s4):5, (n2,s2):6, next=7, gen=0]: unexpected value: raw_bytes:"\023\240&K\003\010\035\022\005\275\211\367\001\t\032\005\275\211\367\001?\"\006\010\001\020\001\030\001\"\006\010\004\020\004\030\005\"\006\010\002\020\002\030\006(\007" timestamp:<wall_time:1539012778171889067 > round 46: setting partition lease preferences for partition 81 to node 1

```

Are these expected or a real failure?

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31011)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/bank.go, line 293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31011#-LO3tklU0zMmQ-y0hsCE:-LOJ_Xl82RwEqbK21r4M:byxhv2o) ([raw file](https://github.com/cockroachdb/cockroach/blob/29f5594b9879f212f66bd6365e05554a2dcb6f76/pkg/cmd/roachtest/bank.go#L293)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

I added the ALTER TABLE ... EXPERIMENTAL_RELOCATE LEASE ... behavior, but I'm seeing a lot of errors of the form:

```
pq: change replicas of r24 failed: [n1,s1,r24/1:/Table/53/1/{258-408}]: received invalid ChangeReplicasTrigger REMOVE_REPLICA((n1,s1):1): updated=[(n2,s2):3 (n4,s4):2] next=4 to remove self (leaseholder)round 12: setting partition lease preferences for partition 582 to node 2

pq: change replicas of r29 failed: descriptor changed: [expected] r29:/Table/53/1/{265-319} [(n1,s1):1, (n4,s4):5, next=6, gen=0] != [actual] r29:/Table/53/1/{265-319} [(n1,s1):1, (n4,s4):5, (n2,s2):6, next=7, gen=0]: unexpected value: raw_bytes:"\023\240&K\003\010\035\022\005\275\211\367\001\t\032\005\275\211\367\001?\"\006\010\001\020\001\030\001\"\006\010\004\020\004\030\005\"\006\010\002\020\002\030\006(\007" timestamp:<wall_time:1539012778171889067 > round 46: setting partition lease preferences for partition 81 to node 1

```

Are these expected or a real failure?
</blockquote></details>

The first error looks like a bug in what you did. The destination of the relocation has to be a node that has a replica of the range on it (and is not currently the leaseholder).

The second error is more curious. I think it might be expected if we're performing multiple operations concurrently. I'd sync with @nvanbenschoten to be sure about that.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31011)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/bank.go, line 293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31011#-LO3tklU0zMmQ-y0hsCE:-LOKM_v25TfcWokiGkl_:bm0wbpa) ([raw file](https://github.com/cockroachdb/cockroach/blob/29f5594b9879f212f66bd6365e05554a2dcb6f76/pkg/cmd/roachtest/bank.go#L293)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The first error looks like a bug in what you did. The destination of the relocation has to be a node that has a replica of the range on it (and is not currently the leaseholder).

The second error is more curious. I think it might be expected if we're performing multiple operations concurrently. I'd sync with @nvanbenschoten to be sure about that.
</blockquote></details>

Yeah, the second error is expected if we're performing concurrent descriptor changes. We usually have these operations in retry loops for exactly this reason. We probably need a retry loop for the operation that `ALTER TABLE ... EXPERIMENTAL_RELOCATE LEASE ...` performs.

For instance, see

https://github.com/cockroachdb/cockroach/blob/f4e4789ed4bdd77ab6c30149a66deccefd83b25e/pkg/storage/replica_command.go#L152

**Review by m-schneider — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31011)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/acceptance.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31011#-LO3tyC164opCfImS2rN:-LOKXJRjDQhlcXH-UO6K:bq9dfh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/29f5594b9879f212f66bd6365e05554a2dcb6f76/pkg/cmd/roachtest/acceptance.go#L40)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Yes. Doing them all at the same time is what leads to interesting badness. In particular, splitting and lease transfers at the same time a node is being restarted is the interesting bit.
</blockquote></details>

I added the combination of the splits, lease transfers and restarts.
___
*[pkg/cmd/roachtest/bank.go, line 293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31011#-LO3tklU0zMmQ-y0hsCE:-LOKW6B99AL-IhjAoYqi:b-t6was5) ([raw file](https://github.com/cockroachdb/cockroach/blob/29f5594b9879f212f66bd6365e05554a2dcb6f76/pkg/cmd/roachtest/bank.go#L293)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah, the second error is expected if we're performing concurrent descriptor changes. We usually have these operations in retry loops for exactly this reason. We probably need a retry loop for the operation that `ALTER TABLE ... EXPERIMENTAL_RELOCATE LEASE ...` performs.

For instance, see

https://github.com/cockroachdb/cockroach/blob/f4e4789ed4bdd77ab6c30149a66deccefd83b25e/pkg/storage/replica_command.go#L152
</blockquote></details>

Thanks! I think since the chaos in this file is mostly done in a loop, the other tests ignore retryable errors, so I can add this particular one to the list vs adding retry logic?

Also after trying a couple of different ways to move the leaseholder, the cleanest turned out to relocating the range onto multiple stores. Other implementations like querying for the replicas corresponding to a primary key and then shifting the leaseholder were pretty fragile, because replicas moved between the query to check and the query to move. This way the shift is more atomic.

**Review by petermattis — CHANGES_REQUESTED** [review]
I need to take another pass at this, but it is looking close to done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31011#-:-LOOzNjP8JsmyPy3xdzV:b-rrwvt1)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/bank.go, line 307 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31011#-LOOyj87566BGKjFiBbw:-LOOyj87566BGKjFiBbx:b-5ugyod) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f90464f514e40930c98774e47582ca52dc52c8d/pkg/cmd/roachtest/bank.go#L307)):*
> ```Go
> 			})
> 
> 			const zoneConfQuery = `ALTER TABLE bank.accounts EXPERIMENTAL_RELOCATE VALUES (ARRAY[%s], %d);`
> ```

`s/zoneConfQuery/relocateQuery/g`
___
*[pkg/cmd/roachtest/bank.go, line 308 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31011#-LOOz1IQ0qGO2t4NrPKQ:-LOOz1IQ0qGO2t4NrPKR:b5c9d7c) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f90464f514e40930c98774e47582ca52dc52c8d/pkg/cmd/roachtest/bank.go#L308)):*
> ```Go
> 
> 			const zoneConfQuery = `ALTER TABLE bank.accounts EXPERIMENTAL_RELOCATE VALUES (ARRAY[%s], %d);`
> 			finalQ := fmt.Sprintf(zoneConfQuery, strings.Join(nodes[1:], ", "), key)
> ```

Nit: odd to name this `finalQ` and the template `zoneConfQuery`. Odd due to the inconsistent terminology `final` vs `zoneConf` and `Q` vs `Query`. I'd go with something like `relocateQueryFormat` and `relocateQuery`.
___
*[pkg/cmd/roachtest/bank.go, line 310 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31011#-LOOyoeD6TLHMTM2Yutl:-LOOyoeD6TLHMTM2Yutm:bj0xi0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f90464f514e40930c98774e47582ca52dc52c8d/pkg/cmd/roachtest/bank.go#L310)):*
> ```Go
> 			finalQ := fmt.Sprintf(zoneConfQuery, strings.Join(nodes[1:], ", "), key)
> 			c.l.Printf("round %d: setting lease preferences for key %d to node %s\n",
> 				curRound, key, nodes[0])
> ```

This log message is no longer accurate (you're relocating ranges, not changing lease preferences) and it only logs `nodes[0]` while it should be logging all of the nodes.

**Review by m-schneider — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31011)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/bank.go, line 307 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31011#-LOOyj87566BGKjFiBbw:-LOP7l9hE3AwIuTiWtwJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f90464f514e40930c98774e47582ca52dc52c8d/pkg/cmd/roachtest/bank.go#L307)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/zoneConfQuery/relocateQuery/g`
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/bank.go, line 308 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31011#-LOOz1IQ0qGO2t4NrPKQ:-LOP82d_2ARHdnuiyt7h:b-34ka9z) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f90464f514e40930c98774e47582ca52dc52c8d/pkg/cmd/roachtest/bank.go#L308)):*
> relocateQueryFormat
Done
___
*[pkg/cmd/roachtest/bank.go, line 310 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31011#-LOOyoeD6TLHMTM2Yutl:-LOP83Gq92O8VRC7zqQJ:b-jxthgs) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f90464f514e40930c98774e47582ca52dc52c8d/pkg/cmd/roachtest/bank.go#L310)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This log message is no longer accurate (you're relocating ranges, not changing lease preferences) and it only logs `nodes[0]` while it should be logging all of the nodes.
</blockquote></details>

nodes[0] is the leaseholder, but I'll change it to log all of them

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31011)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/bank.go, line 308 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31011#-LOOz1IQ0qGO2t4NrPKQ:-LOPX6_vABgwQ_51tBPq:bgxwqf1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f90464f514e40930c98774e47582ca52dc52c8d/pkg/cmd/roachtest/bank.go#L308)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

> relocateQueryFormat
Done
</blockquote></details>

Heh, you have the variable names reversed. I was imagining `const relocateQueryFormat` because that is a format string used to construct the `relocateQuery` variable.
___
*[pkg/cmd/roachtest/bank.go, line 310 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31011#-LOOyoeD6TLHMTM2Yutl:-LOPXLTk-IZnk8btbgI3:bfir4hc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f90464f514e40930c98774e47582ca52dc52c8d/pkg/cmd/roachtest/bank.go#L310)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

nodes[0] is the leaseholder, but I'll change it to log all of them
</blockquote></details>

Don't you want `s/nodes[1:]/nodes/g`. 
___
*[pkg/cmd/roachtest/bank.go, line 488 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31011#-LOPXYIB4E4QQC1_SmCS:-LOPXYIB4E4QQC1_SmCT:b-680sc5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b45c75cde7306aff4af8d9f9dafd3b52f80a5dfa/pkg/cmd/roachtest/bank.go#L488)):*
> ```Go
> 
> 	for i := 1; i <= c.nodes; i++ {
> 		c.Start(ctx, c.Node(i), startArgs(fmt.Sprintf("-a=--attrs=node%d", i)))
> ```

Is the `--attrs` flag still necessary now that you are not using leaseholder preferences?
___
*[pkg/cmd/roachtest/bank.go, line 530 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31011#-LOPXbUHEu5QZWPFWLHt:-LOPXbUHEu5QZWPFWLHu:bxs4hxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b45c75cde7306aff4af8d9f9dafd3b52f80a5dfa/pkg/cmd/roachtest/bank.go#L530)):*
> ```Go
> 
> 	for i := 1; i <= c.nodes; i++ {
> 		c.Start(ctx, c.Node(i), startArgs(fmt.Sprintf("-a=--attrs=node%d", i)))
> ```

Ditto about the `--attrs` flag.

**Review by m-schneider — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31011)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/bank.go, line 308 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31011#-LOOz1IQ0qGO2t4NrPKQ:-LOP_Lyf23em7uQDvRN-:b-rboghu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f90464f514e40930c98774e47582ca52dc52c8d/pkg/cmd/roachtest/bank.go#L308)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Heh, you have the variable names reversed. I was imagining `const relocateQueryFormat` because that is a format string used to construct the `relocateQuery` variable.
</blockquote></details>

:) I did think about it.
___
*[pkg/cmd/roachtest/bank.go, line 310 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31011#-LOOyoeD6TLHMTM2Yutl:-LOP_S7xBba-ysuGsLoI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f90464f514e40930c98774e47582ca52dc52c8d/pkg/cmd/roachtest/bank.go#L310)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Don't you want `s/nodes[1:]/nodes/g`. 
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/bank.go, line 488 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31011#-LOPXYIB4E4QQC1_SmCS:-LOP_TJT26kJ49WJkncG:bon4sdj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b45c75cde7306aff4af8d9f9dafd3b52f80a5dfa/pkg/cmd/roachtest/bank.go#L488)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is the `--attrs` flag still necessary now that you are not using leaseholder preferences?
</blockquote></details>

Yep, that's not necessary anymore in both places.
___
*[pkg/cmd/roachtest/bank.go, line 530 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31011#-LOPXbUHEu5QZWPFWLHt:-LOP_Z7kEtrfv8VCxdxw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b45c75cde7306aff4af8d9f9dafd3b52f80a5dfa/pkg/cmd/roachtest/bank.go#L530)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ditto about the `--attrs` flag.
</blockquote></details>

Done.

**Review by petermattis — APPROVED** [review]
:lgtm: modulo final comment

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31011#-:-LOPa_6K9CITmZh-gTT9:b-59c39i)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/bank.go, line 310 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31011#-LOOyoeD6TLHMTM2Yutl:-LOPaQHmAXIoDFTylewa:b-b3c08m) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f90464f514e40930c98774e47582ca52dc52c8d/pkg/cmd/roachtest/bank.go#L310)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Did you forget to push the update? (still says `nodes[1:]` in reviewable).

**Comment by m-schneider** [comment]
___
*[pkg/cmd/roachtest/bank.go, line 310 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31011#-LOOyoeD6TLHMTM2Yutl:-LOPm9E08uK3a7PnaL0a:b-sh4jrq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f90464f514e40930c98774e47582ca52dc52c8d/pkg/cmd/roachtest/bank.go#L310)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Did you forget to push the update? (still says `nodes[1:]` in reviewable).
</blockquote></details>

It should, I got a bit confused when I first read your first comment. I used the shuffle function to randomize all of the nodes, but that still left me with 4 nodes, so I dropped the first one to move the range to 3 nodes vs 4.

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31011)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/bank.go, line 310 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31011#-LOOyoeD6TLHMTM2Yutl:-LOPxi1I3Xmwjsg4EHtk:b9sgjjt) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f90464f514e40930c98774e47582ca52dc52c8d/pkg/cmd/roachtest/bank.go#L310)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

It should, I got a bit confused when I first read your first comment. I used the shuffle function to randomize all of the nodes, but that still left me with 4 nodes, so I dropped the first one to move the range to 3 nodes vs 4.
</blockquote></details>

Ah, got it. Carry on.

**Comment by m-schneider** [comment]
I'm stressing the two tests before merging, just in case I didn't see more rare errors while testing.

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31011)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/acceptance.go, line 43 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31011#-LOZ7WZL6YL7scNVb_oO:-LOZLLwGB-krJAr-A-ST:b-45g7m8) ([raw file](https://github.com/cockroachdb/cockroach/blob/208602fc7de6ebef8df8c036f418fab365ef2f4e/pkg/cmd/roachtest/acceptance.go#L43)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

I did a rebase and ran the test 100 times and there were still failures and hangs. After talking to @nvanbenschoten, I think it would make sense to hold off on merging the test with restarts until the bank/node-restart is fixed.
</blockquote></details>

Ack. Just to be clear: all of the failures were stalls? I'm fine checking this in disabled.

**Comment by m-schneider** [comment]
___
*[pkg/cmd/roachtest/acceptance.go, line 43 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31011#-LOZ7WZL6YL7scNVb_oO:-LOZPl8k-dTNTopDetzt:b-e3m0fm) ([raw file](https://github.com/cockroachdb/cockroach/blob/208602fc7de6ebef8df8c036f418fab365ef2f4e/pkg/cmd/roachtest/acceptance.go#L43)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ack. Just to be clear: all of the failures were stalls? I'm fine checking this in disabled.
</blockquote></details>

Yes it stalled about 10% of the time.

**Pull request merged**
