### PR TITLE
kvserver: add TestElectionAfterRestart, remove roachtest/election-after-restart

### PR DESCRIPTION
**Pull request by tbg**
- kvserver: silence spammy logging
- roachtest: update election-after-restart
- kvserver: add TestElectionAfterRestart
- roachtest: remove election-after-restart

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 3 of 3 files at r3, 4 of 4 files at r5, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64774#-:-Mb1-Y2h9sh2_CHnreph:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/kv/kvserver/client_raft_test.go, line 5527 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/64774#-Mb0z5sb9-CgfMphcWId:-Mb0z5scAZF_UNQZT85e:b4frzgs) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a7c8e75417ca590198ff733d8531603080454fd/pkg/kv/kvserver/client_raft_test.go#L5527)):*
> ```Go
> 		t.Logf("created %d ranges", numRanges)
> 
> 		// Make sure that the ranges have all followers fully caught up. Otherwise,
> ```

This might be useful as a `TestCluster` helper, similar to `WaitForFullReplication()`.
___
*[pkg/kv/kvserver/replica_raft.go, line 1608 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/64774#-Mb1-3T90HSDGiMs-HUo:-Mb1-3T90HSDGiMs-HUp:b-sng856) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a7c8e75417ca590198ff733d8531603080454fd/pkg/kv/kvserver/replica_raft.go#L1608)):*
> ```Go
> // dormant state (either the initial "raftGroup == nil" state or after
> // being quiescent) and campaigns for raft leadership if appropriate.
> func (r *Replica) maybeCampaignOnWakeLocked(ctx context.Context) {
> ```

Since this doesn't actually campaign anymore, maybe we should rename it to `shouldCampaignOnWakeLocked()`?
___
*[pkg/kv/kvserver/replica_raft.go, line 1922 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/64774#-Mb0zwoAAliLTRyXn-bP:-Mb0zwoAAliLTRyXn-bQ:b-i0jlgf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a7c8e75417ca590198ff733d8531603080454fd/pkg/kv/kvserver/replica_raft.go#L1922)):*
> ```Go
> }
> 
> func maybeCampaignAfterConfChange(
> ```

Ditto, maybe rename to `shouldCampaignAfterConfChange()`?

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64774)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[pkg/kv/kvserver/client_raft_test.go, line 5527 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/64774#-Mb0z5sb9-CgfMphcWId:-Mb201NG8UJ-AkhSKAVl:bv8amig) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a7c8e75417ca590198ff733d8531603080454fd/pkg/kv/kvserver/client_raft_test.go#L5527)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

This might be useful as a `TestCluster` helper, similar to `WaitForFullReplication()`.
</blockquote></details>

I'm not sure it's that useful. It's pretty niche, often you want something else (like "wait until all replicas see this one particular write"). This test also doesn't use it (unless you up the `numNodes`, in which case it avoids a percentage of flakes), and it's hard to use correctly as entries can pop up from inside of raft on the leader.
___
*[pkg/kv/kvserver/replica_raft.go, line 1608 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/64774#-Mb1-3T90HSDGiMs-HUo:-Mb2-gK2AZCgQtJ90Kor:b-5mr22f) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a7c8e75417ca590198ff733d8531603080454fd/pkg/kv/kvserver/replica_raft.go#L1608)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Since this doesn't actually campaign anymore, maybe we should rename it to `shouldCampaignOnWakeLocked()`?
</blockquote></details>

This one does actually campaign.
___
*[pkg/kv/kvserver/replica_raft.go, line 1922 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/64774#-Mb0zwoAAliLTRyXn-bP:-Mb2-qEO9e-Ja80XRi-Q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a7c8e75417ca590198ff733d8531603080454fd/pkg/kv/kvserver/replica_raft.go#L1922)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Ditto, maybe rename to `shouldCampaignAfterConfChange()`?
</blockquote></details>

Done.

**Review by erikgrinaker — APPROVED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64774)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tbg)

___
*[pkg/kv/kvserver/replica_raft.go, line 1608 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/64774#-Mb1-3T90HSDGiMs-HUo:-Mb21L2C8UZqBe8L4OHS:btcfpnx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a7c8e75417ca590198ff733d8531603080454fd/pkg/kv/kvserver/replica_raft.go#L1608)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This one does actually campaign.
</blockquote></details>

Ah, right -- looked at the conf change one first. :)

**Comment by tbg** [comment]
bors r=erikgrinaker

**Comment by tbg** [comment]
bors r=erikgrinaker

flake was https://github.com/cockroachdb/cockroach/issues/65878

**Pull request merged**
