### PR TITLE
 exec: add support for LEFT SEMI and LEFT ANTI in merge joiner

### LINKED ISSUE #37166: exec: add outer, semi, antijoins to merge join
Currently, vectorized engine is missing:
 - [x] outer merge join
    - [x] left outer
    - [x] right outer
    - [x] full outer
 - [x] semi merge join
 - [x] anti merge join

### PR DESCRIPTION
**Pull request by yuzefovich**
First commit  is a fairly simple change to support left semi join.
It uses the same probing logic as inner join with the only difference being
that on the last equality column we add a special left semi group
to set up the builder. Also, building of right groups is omitted.

Second commit adds support for left anti which is quite similar to left outer
with an exception that only unmatched groups will be added to the output
and the right side being omitted completely.

Fixes: #37166.

### CODE REVIEW

**Comment by yuzefovich** [comment]
Rebased this, so it is now RFAL.

**Review by jordanlewis — APPROVED** [review]
:lgtm_strong: 

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38664#-:-LjauqKx8KEzfy2WiaMU:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @solongordon, and @yuzefovich)

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 303 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38664#-LjaqintC6aSEMyXsGZJ:-LjaqintC6aSEMyXsGZK:b-669gok) ([raw file](https://github.com/cockroachdb/cockroach/blob/92b4f4dbac83c18ae16f5efc2fd2521ba13c03d2/pkg/sql/distsqlrun/column_exec_setup.go#L303)):*
> ```Go
> 		if core.MergeJoiner.Type == sqlbase.JoinType_INTERSECT_ALL ||
> 			core.MergeJoiner.Type == sqlbase.JoinType_EXCEPT_ALL {
> 			return nil, nil, errors.Newf("unexpectedly %s merge join was planned", core.MergeJoiner.Type.String())
> ```

Make this an AssertionErrorf.

**Review by yuzefovich — COMMENTED** [review]
The reviewable shows that you have "seen" only revision r1. This PR contains two commits, so I just want to make sure you looked at both of them.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38664#-:-LjbDtynDVsbrwfdz9GX:b-acquxp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @solongordon)

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 303 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38664#-LjaqintC6aSEMyXsGZJ:-LjbDs_UBMvw4qFV7WvE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/92b4f4dbac83c18ae16f5efc2fd2521ba13c03d2/pkg/sql/distsqlrun/column_exec_setup.go#L303)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Make this an AssertionErrorf.
</blockquote></details>

Done.

**Review by jordanlewis — COMMENTED** [review]
I've seen them both, I think I just didn't click "mark as reviewed" at the right time. 

> Reviewed 6 of 7 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38664#-:-LjbFDN14Rq4EhBitCrI:bejcwnn)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @solongordon)

**Comment by yuzefovich** [comment]
Thanks for the review!

bors r+

**Pull request merged**
