### PR TITLE
util/json: don't put emojis in test names

### PR DESCRIPTION
**Pull request by jordanlewis**
TeamCity chokes on those.

### CODE REVIEW

**Review by a-robinson — COMMENTED** [review]
😢

**Review by lgo — APPROVED** [review]
LGTM :'(

**Comment by RaduBerinde** [comment]
Would have been better to keep the `Run`s and pass the loop index as the subtest name. Now if there's a failure, it's impossible to tell which case failed.

**Comment by jordanlewis** [comment]
You're right- will send a followup. Just wanted to get stuff unblocked.

**Pull request merged**
