### PR TITLE
ui/next: use generated protos

### PR DESCRIPTION
**Pull request by tamird**
cc @maxlang

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6363)

### CODE REVIEW

**Comment by maxlang** [comment]
Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
Review status: 1 of 22 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[ui/next/config.js, line 46 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6363#-KGOha7qY3L6ZHXRjerM:-KGOha7qY3L6ZHXRjerN:1485312182) ([raw file](https://github.com/cockroachdb/cockroach/blob/386a16ed8ca93f91149d96ee57af8c9cbd78698b/ui/next/config.js#L46)):*
I seem to remember this being an issue. @mrtracy says it doesn't work with bundling if you get rid of this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6363)*

**Comment by mrtracy** [comment]
Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 8 of 8 files at r5, 1 of 5 files at r6, 1 of 9 files at r7.
Review status: 11 of 22 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[ui/next/config.js, line 18 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6363#-KGOhzcTau_k-UNc50nQ:-KGOhzcTau_k-UNc50nR:223477083) ([raw file](https://github.com/cockroachdb/cockroach/blob/386a16ed8ca93f91149d96ee57af8c9cbd78698b/ui/next/config.js#L18)):*
Did you mean to get rid of this?  `jspm bundle` will not work here because of this bug: https://github.com/frankwallis/plugin-typescript/issues/107

Unfortunately we can't put a comment to this effect in this file, because it is normalized and stripped of comments whenever you run `jspm`. 

---

*[ui/next/app/redux/nodes.ts, line 152 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6363#-KGOlZMiASM2wbxou16I:-KGOlZMiASM2wbxou16J:485518544) ([raw file](https://github.com/cockroachdb/cockroach/blob/77c246d97fa2c5eb96da2000411feae2f290a0e1/ui/next/app/redux/nodes.ts#L152)):*
I've taken a look at the Proto2Typescript project, and here's what I gather from their example: the type of the "protos" module being imported here is equivalent to the ProtoBufBuilder type defined in that output file.

Based on their readme example, the .d.ts file they generate is NOT attempting to type a nodejs module; rather, it's generating the types of the dynamic objects being built by running the `ProtoBuf` builder.

The "proto.js" module you're referencing here is actually exporting the output of such a call to a ProtoBuf builder.

So therefore, the module shape of "proto.js" should be this:

```typescript
declare module "proto" {
   declare var builder: cockroach.ProtoBufBuilder;
   export = builder;
}
```

Rather than wrapping the entire proto.d.ts file in a `declare module`, that smaller `declare module` should be appended to the end of the file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6363)*

**Comment by tamird** [comment]
Review status: 11 of 22 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[ui/next/config.js, line 18 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6363#-KGOhzcTau_k-UNc50nQ:-KGSGr2pxSW-Zs7SsFFI:204400138) ([raw file](https://github.com/cockroachdb/cockroach/blob/386a16ed8ca93f91149d96ee57af8c9cbd78698b/ui/next/config.js#L18)):*
Are you sure? I ran `jspm bundle app` and things seemed to work.

---

*[ui/next/config.js, line 46 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6363#-KGOha7qY3L6ZHXRjerM:-KGSHAbrec9yjimgcjmy:1730978241) ([raw file](https://github.com/cockroachdb/cockroach/blob/386a16ed8ca93f91149d96ee57af8c9cbd78698b/ui/next/config.js#L46)):*
Discussion on @mrtracy's comment.

---

*[ui/next/app/redux/nodes.ts, line 152 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6363#-KGOlZMiASM2wbxou16I:-KGSJASNE3Lq37yFsWp7:1541059650) ([raw file](https://github.com/cockroachdb/cockroach/blob/77c246d97fa2c5eb96da2000411feae2f290a0e1/ui/next/app/redux/nodes.ts#L152)):*
I can't quite get this to work with the type aliases in `app/util/proto.ts`. Can you try this locally and send a diff? Happy to iterate in person as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6363)*

**Comment by tamird** [comment]
Review status: 0 of 27 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[ui/next/config.js, line 18 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6363#-KGOhzcTau_k-UNc50nQ:-KGT1dSQrXowD4L-PbFn:74062865) ([raw file](https://github.com/cockroachdb/cockroach/blob/386a16ed8ca93f91149d96ee57af8c9cbd78698b/ui/next/config.js#L18)):*
Reverted this part.

---

*[ui/next/app/redux/nodes.ts, line 152 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6363#-KGOlZMiASM2wbxou16I:-KGT1fTVOBOR7FsNUHYA:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/77c246d97fa2c5eb96da2000411feae2f290a0e1/ui/next/app/redux/nodes.ts#L152)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6363)*

**Comment by mrtracy** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r6, 7 of 9 files at r7, 19 of 22 files at r8, 2 of 2 files at r9, 1 of 2 files at r11, 12 of 14 files at r12, 14 of 14 files at r13.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[ui/next/config.js, line 18 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6363#-KGOhzcTau_k-UNc50nQ:-KGScNFfqsYa1rxzY8hH:-819191517) ([raw file](https://github.com/cockroachdb/cockroach/blob/386a16ed8ca93f91149d96ee57af8c9cbd78698b/ui/next/config.js#L18)):*
It works, but it silently ignores type-checking errors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6363#-:-KGT7T4OXtzP9KMJ0VD0:1417088721)*

**Comment by tamird** [comment]
Test failure is TestTxnDBLostUpdateAnomaly_Delete which is unrelated, merging.

**Comment by tamird** [comment]
Grrr! Can't. Rebased.

**Pull request merged**
