### PR TITLE
server: export machine-level CPU usage as a metric

### LINKED ISSUE #95473: metrics: track system/container CPU in addition to cockroach usage
**Is your feature request related to a problem? Please describe.**
Customers lack the ability to easily see system CPU usage in CRDB DB Console, and in our prometheus metrics which makes interpreting our existing CPU metric (which only measures CPU used by our process) sometimes challenging to interpret.

**Describe the solution you'd like**
We should publish a separate metric that contains system (or container) CPU usage based on OS reporting.

See #89514 for some relevant discussion.

Jira issue: CRDB-23532

### PR DESCRIPTION
**Pull request by andreimatei**
In addition to exporting the CPU usage of the cockroach process, this
patch now also exports the system-wide CPU usage and adds that metric to
the Hardware dashboard. This should help identify situations where the
whole machine is starved for CPU.
For the cockroach CPU usage we actually export multiple metrics (user vs
kernel time in absolute numbers and ratios). For the new system
measurement I've only added a normalized metric.

Fixes https://github.com/cockroachdb/cockroach/issues/95473

Release note (ui change): A new metric has been added to the Hardware
dashboard, showing the system-wide CPU usage in addition to the existing
cockroach CPU usage.
Epic: None

### CODE REVIEW

**Review by abarganier — APPROVED** [review]
:lgtm: modulo some small nits

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98187#-:-NQ0tSeq6bZ5AQQni50A:b-g5smvw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @dhartunian)

___
*[`pkg/server/status/runtime.go` line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98187#-NQ0pfsEDkB-d0fD2Gr_:-NQ0pfsEDkB-d0fD2Gra:b-5xfw2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/a68baf5bdd2f7c5ca0116c2666abecb971bc36c1/pkg/server/status/runtime.go#L97)):*
> ```Go
> 	metaCPUUserNS = metric.Metadata{
> 		Name:        "sys.cpu.user.ns",
> 		Help:        "Total user cpu time consumed by the CRDB node",
> ```

nit: thoughts on using the word "process" instead of "node"? I'm wondering if it has a bit less ambiguity, e.g. "node" could be misconstrued as the k8s node that the crdb process is running on. 



_Code quote:_
```Go
node
```
___
*[`pkg/util/tracing/span.go` line 482 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98187#-NQ0tMwT9lsVLYHJ7Hzo:-NQ0tMwT9lsVLYHJ7Hzp:b-vcbpgh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a68baf5bdd2f7c5ca0116c2666abecb971bc36c1/pkg/util/tracing/span.go#L482)):*
> ```Go
> 		return
> 	}
> 	sp.i.hasVerboseSink()
> ```

nit: leaked tracing work :slightly_smiling_face: 



_Code quote:_
```Go
sp.i.hasVerboseSink()
```

**Review by knz — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98187)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier, @andreimatei, and @dhartunian)

___
*[`pkg/server/status/runtime.go` line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98187#-NQ0pfsEDkB-d0fD2Gr_:-NQ0upPk7XJIqyEyZ8hR:b66nscb) ([raw file](https://github.com/cockroachdb/cockroach/blob/a68baf5bdd2f7c5ca0116c2666abecb971bc36c1/pkg/server/status/runtime.go#L97)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: thoughts on using the word "process" instead of "node"? I'm wondering if it has a bit less ambiguity, e.g. "node" could be misconstrued as the k8s node that the crdb process is running on. 
</blockquote></details>

:heavy_plus_sign: 
___
*[`pkg/server/status/runtime.go` line 480 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98187#-NQ0uvvL5XWQh6jiXGbC:-NQ0uvvM-qlyS3PrHpcO:b-fbgjf5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a68baf5bdd2f7c5ca0116c2666abecb971bc36c1/pkg/server/status/runtime.go#L480)):*
> ```Go
> 	userTimeMillis, sysTimeMillis, err := GetProcCPUTime(ctx)
> 	if err != nil {
> 		log.Ops.Errorf(ctx, "unable to get CRDB CPU usage: %v", err)
> ```

-CRDB +process
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/hardware.tsx` line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98187#-NQ0v-66-1Hu2XtFlhwM:-NQ0v-67AQQ4c4-YcIB9:b31nfo5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a68baf5bdd2f7c5ca0116c2666abecb971bc36c1/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/hardware.tsx#L40)):*
> ```XML
>       title="CPU Percent"
>       sources={nodeSources}
>       tooltip={<div>CPU usage for the CRDB nodes {tooltipSelection}</div>}
> ```

-"CRDB nodes" +"server processes"

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98187)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier, @dhartunian, and @knz)

___
*[`pkg/server/status/runtime.go` line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98187#-NQ0pfsEDkB-d0fD2Gr_:-NQ2Cnp9CXHQ4Dl_5CIf:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a68baf5bdd2f7c5ca0116c2666abecb971bc36c1/pkg/server/status/runtime.go#L97)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

:heavy_plus_sign: 
</blockquote></details>

done
___
*[`pkg/server/status/runtime.go` line 480 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98187#-NQ0uvvL5XWQh6jiXGbC:-NQ2CwKCBwQIB7T8DvGp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a68baf5bdd2f7c5ca0116c2666abecb971bc36c1/pkg/server/status/runtime.go#L480)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

-CRDB +process
</blockquote></details>

Done.
___
*[`pkg/util/tracing/span.go` line 482 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98187#-NQ0tMwT9lsVLYHJ7Hzo:-NQ2D1sPCGxYDuZ8moQn:b32vj2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a68baf5bdd2f7c5ca0116c2666abecb971bc36c1/pkg/util/tracing/span.go#L482)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: leaked tracing work :slightly_smiling_face: 
</blockquote></details>

:S

**Review by andreimatei — COMMENTED** [review]
TFTR

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98187#-:-NQ2cqJa7A7029I9tO4Y:b-4as1hm)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier, @dhartunian, and @knz)

**Pull request merged**
