### PR TITLE
distsql: support rendering in post-processing

### PR DESCRIPTION
**Pull request by RaduBerinde**
Support renderings in processor post-processing (mutually exclusive with
projection). The Evaluator processor is gone (it is equivalent to a no-op
processor with a rendering post-processing).

The planning code adds rendering to the previous stage when possible. The
exception is when the previous stage already has a rendering; in this case we
add a no-op processor. We also need to do the same when adding a filter to a
stage that has a rendering.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13120)

### CODE REVIEW

**Comment by andreimatei** [comment]
:lgtm:

---

Reviewed 1 of 10 files at r1.
Review status: 1 of 10 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 464 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13120#-KbQhnYj_pjw9z9xpO83:-KbQhnYk6_hJGyr4JN8K:br1r8en) ([raw file](https://github.com/cockroachdb/cockroach/blob/59b38ac3ac468f0e78cc016b6f785b4f20f1edb7/pkg/sql/distsql_physical_planner.go#L464)):*
> ```Go
> // Used when adding expressions (filtering, rendering) to a processor's
> // PostProcessSpec. The indexed variables in the expression - after remapping
> // via indexVarMap - refer to the output columns of the processor(s) in the last
> ```

s/last stage/previous stage

---

*[pkg/sql/distsql_physical_planner.go, line 465 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13120#-KbQjPnxe4UhqKmVlF3p:-KbQjPnxe4UhqKmVlF3q:bbzruev) ([raw file](https://github.com/cockroachdb/cockroach/blob/59b38ac3ac468f0e78cc016b6f785b4f20f1edb7/pkg/sql/distsql_physical_planner.go#L465)):*
> ```Go
> // PostProcessSpec. The indexed variables in the expression - after remapping
> // via indexVarMap - refer to the output columns of the processor(s) in the last
> // stage. These processors could have been already configured with projections.
> ```

I think it's unclear what you're saying with "These processors could have been already configured with projections". How about "refer to the output columns of the processor(s) in the last stage *(after the projection step of those processors)*"

---

*[pkg/sql/distsql_physical_planner.go, line 473 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13120#-KbQsSdNhU4NU7P4DKlf:-KbQsSdNhU4NU7P4DKlg:b-7hfwjb) ([raw file](https://github.com/cockroachdb/cockroach/blob/59b38ac3ac468f0e78cc016b6f785b4f20f1edb7/pkg/sql/distsql_physical_planner.go#L473)):*
> ```Go
> //  Expression:          IndexedVar(0) < IndexedVar(1)  //  A < C
> //  indexVarMap:         0, 1  // identity
> //  compositeMap:        0, 2
> ```

this is the first time "composite map" appears.
Also this function no longer remaps any expressions; I think the "remapped expression" line below is still useful to explain how this is used, but the word "remapping" should then appear somewhere in the phrase above about how "adding expressions".

---

*[pkg/sql/distsql_physical_planner.go, line 475 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13120#-KbQt02mHWGtZBAHbBuj:-KbQt02mHWGtZBAHbBuk:bh9ro2z) ([raw file](https://github.com/cockroachdb/cockroach/blob/59b38ac3ac468f0e78cc016b6f785b4f20f1edb7/pkg/sql/distsql_physical_planner.go#L475)):*
> ```Go
> //  compositeMap:        0, 2
> //  Remapped expression: IndexedVar(0) < IndexedVar(2)
> func reverseProjection(outputColumns []uint32, indexVarMap []int) []int {
> ```

this function is pretty confusing :(
Could we take `indexVarMap` out of it by doing a separate remapping of expressions according to that before calling this?

---

*[pkg/sql/distsql_physical_planner.go, line 835 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13120#-KbQwuQhOZxTLxoL4AWU:-KbQwuQhOZxTLxoL4AWV:b-zb6oeb) ([raw file](https://github.com/cockroachdb/cockroach/blob/59b38ac3ac468f0e78cc016b6f785b4f20f1edb7/pkg/sql/distsql_physical_planner.go#L835)):*
> ```Go
> 		}
> 
> 		if post.RenderExprs != nil {
> ```

how can this condition be true? We can call `addRendering` repeatedly for the same stage?

---

*[pkg/sql/distsql_physical_planner.go, line 837 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13120#-KbQz0jVHU3vZprvuolq:-KbQz0jWu0VIRy7aezDH:bu000dq) ([raw file](https://github.com/cockroachdb/cockroach/blob/59b38ac3ac468f0e78cc016b6f785b4f20f1edb7/pkg/sql/distsql_physical_planner.go#L837)):*
> ```Go
> 		if post.RenderExprs != nil {
> 			oldRenders := post.RenderExprs
> 			// Apply the new projection to the existing rendering.
> ```

"apply" seems a bit vague. What we're doing is "overwrite the existing projection with a new one containing only the expressions needed by the new expressions"

---

*[pkg/sql/distsql_physical_planner.go, line 843 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13120#-KbQzU2O72Nxqi-eo1k3:-KbQzU2O72Nxqi-eo1k4:bb4d77t) ([raw file](https://github.com/cockroachdb/cockroach/blob/59b38ac3ac468f0e78cc016b6f785b4f20f1edb7/pkg/sql/distsql_physical_planner.go#L843)):*
> ```Go
> 			}
> 		} else {
> 			// Set the new projection.
> ```

// We didn't have a rendering before and we also don't need one for the new render exprs. Simply overwrite the projection with the columns needed by the new exprs.

---

*[pkg/sql/distsqlrun/processors_test.go, line 31 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13120#-KbR-kByTXwPnbbewrAS:-KbR-kByTXwPnbbewrAT:bhpm87k) ([raw file](https://github.com/cockroachdb/cockroach/blob/59b38ac3ac468f0e78cc016b6f785b4f20f1edb7/pkg/sql/distsqlrun/processors_test.go#L31)):*
> ```Go
> )
> 
> func TestPostProcess(t *testing.T) {
> ```

nice test

---

*[pkg/sql/distsqlrun/processors_test.go, line 161 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13120#-KbR-I83YSlOfIStpF_m:-KbR-I84kVml-92WBqE3:b-hh3prt) ([raw file](https://github.com/cockroachdb/cockroach/blob/59b38ac3ac468f0e78cc016b6f785b4f20f1edb7/pkg/sql/distsqlrun/processors_test.go#L161)):*
> ```Go
> 
> 	for tcIdx, tc := range testCases {
> 		t.Run(strconv.Itoa(tcIdx), func(t *testing.T) {
> ```

I think you can make the first arg of `t.Run()` be `""` for the same effect.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13120#-:-KbR-laC--5DgI8L9f4e:bnfp4nl)*

**Comment by RaduBerinde** [comment]
TFTR!

---

Review status: 1 of 10 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 464 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13120#-KbQhnYj_pjw9z9xpO83:-KbRHDinYzJ8TQwUUt2F:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/59b38ac3ac468f0e78cc016b6f785b4f20f1edb7/pkg/sql/distsql_physical_planner.go#L464)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/last stage/previous stage
</blockquote></details>

Done.

---

*[pkg/sql/distsql_physical_planner.go, line 465 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13120#-KbQjPnxe4UhqKmVlF3p:-KbRHDUsrLIvDZCFQrBl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/59b38ac3ac468f0e78cc016b6f785b4f20f1edb7/pkg/sql/distsql_physical_planner.go#L465)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think it's unclear what you're saying with "These processors could have been already configured with projections". How about "refer to the output columns of the processor(s) in the last stage *(after the projection step of those processors)*"
</blockquote></details>

Done.

---

*[pkg/sql/distsql_physical_planner.go, line 473 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13120#-KbQsSdNhU4NU7P4DKlf:-KbRHDBiFyo4ZdoxC2Hh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/59b38ac3ac468f0e78cc016b6f785b4f20f1edb7/pkg/sql/distsql_physical_planner.go#L473)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

this is the first time "composite map" appears.
Also this function no longer remaps any expressions; I think the "remapped expression" line below is still useful to explain how this is used, but the word "remapping" should then appear somewhere in the phrase above about how "adding expressions".
</blockquote></details>

Done.

---

*[pkg/sql/distsql_physical_planner.go, line 475 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13120#-KbQt02mHWGtZBAHbBuj:-KbRCuFD2f1pJkwxCf_H:bgijeml) ([raw file](https://github.com/cockroachdb/cockroach/blob/59b38ac3ac468f0e78cc016b6f785b4f20f1edb7/pkg/sql/distsql_physical_planner.go#L475)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

this function is pretty confusing :(
Could we take `indexVarMap` out of it by doing a separate remapping of expressions according to that before calling this?
</blockquote></details>

We would need a visitor and we would end up reallocating most of the expression tree. More code and less efficient.

How can we make it less confusing? The function is just composing two column mappings, maybe it would be better to define it more generically? Here's another version I tried out,  is this better? https://gist.github.com/RaduBerinde/38ba798598fa15253d373705856e0860

---

*[pkg/sql/distsql_physical_planner.go, line 835 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13120#-KbQwuQhOZxTLxoL4AWU:-KbRDPXr48ANEBBtVbCl:bbnatpu) ([raw file](https://github.com/cockroachdb/cockroach/blob/59b38ac3ac468f0e78cc016b6f785b4f20f1edb7/pkg/sql/distsql_physical_planner.go#L835)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

how can this condition be true? We can call `addRendering` repeatedly for the same stage?
</blockquote></details>

sure, we could have renderNodes on top of each other, e.g. `SELECT 1+a FROM (SELECT 1+x FROM ..) AS foo(a)`

---

*[pkg/sql/distsql_physical_planner.go, line 837 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13120#-KbQz0jVHU3vZprvuolq:-KbRDeAfLOWFFIKXAo91:b-hkkya1) ([raw file](https://github.com/cockroachdb/cockroach/blob/59b38ac3ac468f0e78cc016b6f785b4f20f1edb7/pkg/sql/distsql_physical_planner.go#L837)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

"apply" seems a bit vague. What we're doing is "overwrite the existing projection with a new one containing only the expressions needed by the new expressions"
</blockquote></details>

We are not overwriting the projection (`OutputColumns`). There is no projection and we are not setting one. We are reshuffling `RenderExprs` according to the new projection, I think that's exactly what "applying the projection to the rendering" indicates no?

---

*[pkg/sql/distsql_physical_planner.go, line 843 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13120#-KbQzU2O72Nxqi-eo1k3:-KbRIRE7_qbEmyQdJQ1X:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/59b38ac3ac468f0e78cc016b6f785b4f20f1edb7/pkg/sql/distsql_physical_planner.go#L843)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

// We didn't have a rendering before and we also don't need one for the new render exprs. Simply overwrite the projection with the columns needed by the new exprs.
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/processors_test.go, line 161 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13120#-KbR-I83YSlOfIStpF_m:-KbRDtxslpKqwt9jKcsp:b-sd2qxy) ([raw file](https://github.com/cockroachdb/cockroach/blob/59b38ac3ac468f0e78cc016b6f785b4f20f1edb7/pkg/sql/distsqlrun/processors_test.go#L161)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think you can make the first arg of `t.Run()` be `""` for the same effect.
</blockquote></details>

Hm, interesting. This behavior is not documented though so I'll leave it as is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13120#-:-KbRJudnBIqye8RduzZT:b-814g8k)*

**Comment by andreimatei** [comment]
Review status: 1 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql_physical_planner.go, line 475 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13120#-KbQt02mHWGtZBAHbBuj:-KbkRb_qL41GPm7ITS-W:b-ogzi2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/59b38ac3ac468f0e78cc016b6f785b4f20f1edb7/pkg/sql/distsql_physical_planner.go#L475)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We would need a visitor and we would end up reallocating most of the expression tree. More code and less efficient.

How can we make it less confusing? The function is just composing two column mappings, maybe it would be better to define it more generically? Here's another version I tried out,  is this better? https://gist.github.com/RaduBerinde/38ba798598fa15253d373705856e0860
</blockquote></details>

well the code is pretty much the same in both versions; I don't think making it more generic helps, but I do slightly prefer the comment from the gist. I think because it spells out the stages and doesn't use identity for the indexVarMap.

I would do the following to make it easier for the reader:
- spell out that `indexVarMap` is a plan->stream col mapping. Maybe even name it as such.
- spell out that `outputColumns` is a mapping from output schema to internal schema.

---

*[pkg/sql/distsql_physical_planner.go, line 837 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13120#-KbQz0jVHU3vZprvuolq:-KbkU1gmbnJOrwL6uNN4:b-8jexlf) ([raw file](https://github.com/cockroachdb/cockroach/blob/59b38ac3ac468f0e78cc016b6f785b4f20f1edb7/pkg/sql/distsql_physical_planner.go#L837)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We are not overwriting the projection (`OutputColumns`). There is no projection and we are not setting one. We are reshuffling `RenderExprs` according to the new projection, I think that's exactly what "applying the projection to the rendering" indicates no?
</blockquote></details>

I see. Frankly "Apply the new projection to the existing rendering" doesn't mean anything to me when I read it, although now that I think about it, it is indeed accurate. I guess "applying a projection" is just not a phrase I use. I prefer talking about output columns. How about "Keep only the renders needed by the new output columns, and reorder them accordingly".

But feel free to keep it if you think the current comment is suggestive.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13120)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/distsql_physical_planner.go, line 475 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13120#-KbQt02mHWGtZBAHbBuj:-KbkmD5pXb1_89659tvW:b3zyb7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/59b38ac3ac468f0e78cc016b6f785b4f20f1edb7/pkg/sql/distsql_physical_planner.go#L475)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

well the code is pretty much the same in both versions; I don't think making it more generic helps, but I do slightly prefer the comment from the gist. I think because it spells out the stages and doesn't use identity for the indexVarMap.

I would do the following to make it easier for the reader:
- spell out that `indexVarMap` is a plan->stream col mapping. Maybe even name it as such.
- spell out that `outputColumns` is a mapping from output schema to internal schema.
</blockquote></details>

Done. I kept `indexVarMap` because it's used in the caller as well and it makes sense there (we have expressions there as well).

---

*[pkg/sql/distsql_physical_planner.go, line 837 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13120#-KbQz0jVHU3vZprvuolq:-KbkmK2-Z1qg2kQyo7jd:b-jcl522) ([raw file](https://github.com/cockroachdb/cockroach/blob/59b38ac3ac468f0e78cc016b6f785b4f20f1edb7/pkg/sql/distsql_physical_planner.go#L837)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I see. Frankly "Apply the new projection to the existing rendering" doesn't mean anything to me when I read it, although now that I think about it, it is indeed accurate. I guess "applying a projection" is just not a phrase I use. I prefer talking about output columns. How about "Keep only the renders needed by the new output columns, and reorder them accordingly".

But feel free to keep it if you think the current comment is suggestive.

</blockquote></details>

Done, kept both.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13120)*

**Pull request merged**
