### PR TITLE
roachtest: allow 10 second buffer before scraping toTime for DRT

### LINKED ISSUE #67303: roachtest: tpcc/multiregion/survive=region/chaos=true failed
roachtest.tpcc/multiregion/survive=region/chaos=true [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3154228&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3154228&tab=artifacts#/tpcc/multiregion/survive=region/chaos=true) on master @ [ba689f91a5bbd7737a8a229522048b2ba91b2ec0](https://github.com/cockroachdb/cockroach/commits/ba689f91a5bbd7737a8a229522048b2ba91b2ec0):

```
		  |   | main.(*tpccChaosEventProcessor).checkUptime
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/drt.go:48
		  |   | main.(*tpccChaosEventProcessor).listen.func1
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/drt.go:265
		  |   | runtime.goexit
		  |   | 	/usr/local/go/src/runtime/asm_amd64.s:1371
		  | Wraps: (4) expected 0 errors, found from 3763874.000000, to 3763875.000000
		  | Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.leafError
		Wraps: (3) secondary error attachment
		  | error at from 2021-07-07T12:30:29Z, to 2021-07-07T12:35:19Z on metric workload_tpcc_payment_error_total{instance="34.139.41.226:2120"}: expected 0 errors, found from 3752976.000000, to 3752977.000000
		  | (1) attached stack trace
		  |   -- stack trace:
		  |   | main.(*tpccChaosEventProcessor).checkMetrics
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/drt.go:190
		  |   | [...repeated from below...]
		  | Wraps: (2) error at from 2021-07-07T12:30:29Z, to 2021-07-07T12:35:19Z on metric workload_tpcc_payment_error_total{instance="34.139.41.226:2120"}
		  | Wraps: (3) attached stack trace
		  |   -- stack trace:
		  |   | main.(*tpccChaosEventProcessor).checkUptime.func2
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/drt.go:65
		  |   | main.(*tpccChaosEventProcessor).checkMetrics
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/drt.go:189
		  |   | main.(*tpccChaosEventProcessor).checkUptime
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/drt.go:48
		  |   | main.(*tpccChaosEventProcessor).listen.func1
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/drt.go:265
		  |   | runtime.goexit
		  |   | 	/usr/local/go/src/runtime/asm_amd64.s:1371
		  | Wraps: (4) expected 0 errors, found from 3752976.000000, to 3752977.000000
		  | Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.leafError
		Wraps: (4) attached stack trace
		  -- stack trace:
		  | main.(*tpccChaosEventProcessor).checkMetrics
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/drt.go:190
		  | [...repeated from below...]
		Wraps: (5) error at from 2021-07-07T12:10:25Z, to 2021-07-07T12:15:15Z on metric workload_tpcc_newOrder_error_total{instance="34.139.41.226:2110"}
		Wraps: (6) attached stack trace
		  -- stack trace:
		  | main.(*tpccChaosEventProcessor).checkUptime.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/drt.go:65
		  | main.(*tpccChaosEventProcessor).checkMetrics
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/drt.go:189
		  | main.(*tpccChaosEventProcessor).checkUptime
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/drt.go:48
		  | main.(*tpccChaosEventProcessor).listen.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/drt.go:265
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1371
		Wraps: (7) expected 0 errors, found from 1889934.000000, to 1889935.000000
		Error types: (1) *secondary.withSecondaryError (2) *secondary.withSecondaryError (3) *secondary.withSecondaryError (4) *withstack.withStack (5) *errutil.withPrefix (6) *withstack.withStack (7) *errutil.leafError
```
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
# From https://go.crdb.dev/p/roachstress, perhaps edited lightly.
caffeinate ./roachstress.sh tpcc/multiregion/survive=region/chaos=true
```
</p>
</p>
</details>
/cc @cockroachdb/multiregion
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*tpcc/multiregion/survive=region/chaos=true.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #67305: roachtest: tpcc/multiregion/survive=zone/chaos=true failed
roachtest.tpcc/multiregion/survive=zone/chaos=true [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3154228&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3154228&tab=artifacts#/tpcc/multiregion/survive=zone/chaos=true) on master @ [ba689f91a5bbd7737a8a229522048b2ba91b2ec0](https://github.com/cockroachdb/cockroach/commits/ba689f91a5bbd7737a8a229522048b2ba91b2ec0):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/tpcc/multiregion/survive=zone/chaos=true/run_1
	tpcc.go:276,tpcc.go:591,z_test_runner.go:765: error at from 2021-07-07T12:11:24Z, to 2021-07-07T12:16:14Z on metric workload_tpcc_newOrder_error_total{instance="34.138.187.236:2110"}: expected 0 errors, found from 3571872.000000, to 3571873.000000
		(1) secondary error attachment
		  | error at from 2021-07-07T12:31:29Z, to 2021-07-07T12:36:19Z on metric workload_tpcc_payment_error_total{instance="34.138.187.236:2112"}: expected 0 errors, found from 3655689.000000, to 3655690.000000
		  | (1) attached stack trace
		  |   -- stack trace:
		  |   | main.(*tpccChaosEventProcessor).checkMetrics
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/drt.go:190
		  |   | [...repeated from below...]
		  | Wraps: (2) error at from 2021-07-07T12:31:29Z, to 2021-07-07T12:36:19Z on metric workload_tpcc_payment_error_total{instance="34.138.187.236:2112"}
		  | Wraps: (3) attached stack trace
		  |   -- stack trace:
		  |   | main.(*tpccChaosEventProcessor).checkUptime.func2
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/drt.go:65
		  |   | main.(*tpccChaosEventProcessor).checkMetrics
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/drt.go:189
		  |   | main.(*tpccChaosEventProcessor).checkUptime
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/drt.go:48
		  |   | main.(*tpccChaosEventProcessor).listen.func1
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/drt.go:265
		  |   | runtime.goexit
		  |   | 	/usr/local/go/src/runtime/asm_amd64.s:1371
		  | Wraps: (4) expected 0 errors, found from 3655689.000000, to 3655690.000000
		  | Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.leafError
		Wraps: (2) attached stack trace
		  -- stack trace:
		  | main.(*tpccChaosEventProcessor).checkMetrics
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/drt.go:190
		  | [...repeated from below...]
		Wraps: (3) error at from 2021-07-07T12:11:24Z, to 2021-07-07T12:16:14Z on metric workload_tpcc_newOrder_error_total{instance="34.138.187.236:2110"}
		Wraps: (4) attached stack trace
		  -- stack trace:
		  | main.(*tpccChaosEventProcessor).checkUptime.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/drt.go:65
		  | main.(*tpccChaosEventProcessor).checkMetrics
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/drt.go:189
		  | main.(*tpccChaosEventProcessor).checkUptime
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/drt.go:48
		  | main.(*tpccChaosEventProcessor).listen.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/drt.go:265
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1371
		Wraps: (5) expected 0 errors, found from 3571872.000000, to 3571873.000000
		Error types: (1) *secondary.withSecondaryError (2) *withstack.withStack (3) *errutil.withPrefix (4) *withstack.withStack (5) *errutil.leafError
```
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
# From https://go.crdb.dev/p/roachstress, perhaps edited lightly.
caffeinate ./roachstress.sh tpcc/multiregion/survive=zone/chaos=true
```
</p>
</p>
</details>
/cc @cockroachdb/multiregion
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*tpcc/multiregion/survive=zone/chaos=true.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by otan**
The scrape we do after before the preShutdown or preStartup can be
slightly racey and may pick up an extra error or success when a node has
already begun to shutdown or restart. This commit adjusts for that by
scraping 10 seconds before the pre event.

Also increase the warehouses because we can now.

Resolves #67303 
Resolves #67305

Release note: None

### CODE REVIEW

**Review by ajstorm — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67417#-:-MeQHxp-4F-GEeYiw8ze:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/cmd/roachtest/tests/tpcc.go, line 593 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67417#-MeQHQwD44_PDTCuwmvG:-MeQHQwFCyArSWzyMCsp:bjwa7hh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4b52d316b441c3bbc1ca96a6c0516a2a7a7cff6/pkg/cmd/roachtest/tests/tpcc.go#L593)):*
> ```Go
> 					chaosEventCh := make(chan ChaosEvent)
> 					runTPCC(ctx, t, c, tpccOptions{
> 						Warehouses:     len(regions) * 20,
> ```

:tada: 
___
*[pkg/cmd/roachtest/tests/tpcc.go, line 183 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67417#-MeQHqJ85ddaUxgiQkjg:-MeQHqJ85ddaUxgiQkjh:b6khokv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0c304704e70117fc377588e3510dbad883c1e1e/pkg/cmd/roachtest/tests/tpcc.go#L183)):*
> ```Go
> 
> 	var ep *tpccChaosEventProcessor
> 	var p *prometheus.Prometheus
> ```

Nit: Why move this up here?

**Comment by otan** [comment]
bors r=ajstorm

**Comment by otan** [comment]
bors r=ajstorm

**Comment by otan** [comment]
bors r=ajstorm

**Comment by otan** [comment]
bors r=ajstorm

**Pull request merged**
