### PR TITLE
ttl: replace custom decoding with DecodeIndexKey

### LINKED ISSUE #101538: ttl: replace custom decoding with DecodeIndexKey
TTL defines its own key decoding in https://github.com/cockroachdb/cockroach/blob/c35a7f453ea424475fe9de85f810f6ee67c1d0df/pkg/sql/ttl/ttljob/ttljob_keydecoder.go

It works the same way as `DecodeIndexKeyPrefix`, except that it can handle partial keys.

Change `DecodeIndexKeyPrefix` to handle partial keys and return the number of `vals` used to handle both use cases.

Jira issue: CRDB-26999

Epic CRDB-18322

### PR DESCRIPTION
**Pull request by ecwall**
Fixes #101538

Previously the TTL job had its own encoding defined in ttljob_keydecoder.go
because DecodeIndexKey could not handle decoding partial keys.

This PR allows DecodeIndexKey to decode partial keys and returns numVals to
indicate how many values were decoded so that it can be used by the TTL job.

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
nice cleanup! lgtm, but if you'd like, it could be good to get sign off from the queries team

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101551#-:-NT0KIdPAIN0Q9wz2PDF:b-o3qzwd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

**Review by Shivs11 — COMMENTED** [review]
Looks good to me! Shall not sign this off as I am not extremely well versed in this portion of the codebase, but thank you for these changes!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101551#-:-NTEi5GEAA7PupD8A9o1:b-oa2yqz)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by mgartner — APPROVED** [review]
Nice cleanup! Thanks for the thoughtful commit organization - it made for a pleasant review experience. :lgtm: 

> Reviewed 11 of 11 files at r1, 2 of 2 files at r2, 9 of 9 files at r3, 9 of 9 files at r4, 2 of 2 files at r5, 9 of 9 files at r6, 5 of 5 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101551#-:-NTEqK-C-WRpRihJ7k0S:bbi4l9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ecwall)

___
*[`pkg/sql/rowenc/index_encoding.go` line 427 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/101551#-NTEoaE3-L2QBhbbM3sF:-NTEoaE45tyfSUE3uMXc:b-93zoem) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ba11d9fb2965a7902a52892845da730ba2d27ba/pkg/sql/rowenc/index_encoding.go#L427)):*
> ```Go
> // encoded column ID for the primary key index, the primary key suffix for
> // non-unique secondary indexes or unique secondary indexes containing NULL or
> // empty.
> ```

nit: remove "remaining bytes" description from comment and add descripton of "numVals".

**Comment by ecwall** [comment]
bors r=rafiss,mgartner

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101551)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[`pkg/sql/rowenc/index_encoding.go` line 427 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/101551#-NTEoaE3-L2QBhbbM3sF:-NTEzx2nC3P29XBQuJLy:b8gj3mz) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ba11d9fb2965a7902a52892845da730ba2d27ba/pkg/sql/rowenc/index_encoding.go#L427)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: remove "remaining bytes" description from comment and add descripton of "numVals".
</blockquote></details>

Good catch, fixed.

**Pull request merged**
