### PR TITLE
sql: gate setting IntervalStyle with a setting

### PR DESCRIPTION
**Pull request by otan**
See individual commits for details.

Refs: #67887

Note well that creating tables with generated columns with interval/string casts with this solution is not yet blocked if the cluster setting is enabled.

However, we need the cast volatility to be "correct" in the optimiser when resolving these IIUC, so i wonder if this contract is "good enough".

cc @vy-ton

### CODE REVIEW

**Review by knz — COMMENTED** [review]
I am not exactly sure this is the right approach.
I see two problems with this PR:

1. the change to thread the cluster settings through all the APIs is very intrusive.
2. cluster settings do not have a stable value over time. Nor do they update atomically across all nodes. So it's possible for one point in the execution of a given SQL session to observe one value, and then immediately afterwards somewhere else to observe another value. This raises plenty of questions about correctness.

I wonder if it wouldn't be wiser to use a session data variable instead, and have the value of the setting stored there when a SQL session is opened. Then use that session data variable everywhere instead of a cluster setting. The implementation would be simpler and also we would have certainty that the value is the same throughout the execution of a SQL session.

> Reviewed 38 of 38 files at r1, 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67792#-:-Mf2cnyy9nVtHMH6ATFg:b-vzch9m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea and @RaduBerinde)

**Comment by otan** [comment]
I think threading the session data variable is the same level of pain so not sure it buys us much. Even worse in tests because not much has session data pre set :/.

I can buy the argument for session variable for staleness but I don't imagine this to be a huge concern. It's definitely an experimental feature at the end for v21.2 because of the problems with stable volatility.

**Comment by otan** [comment]
Also given this is ultimately a cluster setting to use a session variable I wonder whether just a cluster setting is enough.

**Review by RaduBerinde — COMMENTED** [review]
Code change LGTM. If we want to reduce churn in tests, we can tolerate `sv=nil`.

If it's experimental, the cluster setting should contain `experimental`. I think that's a good idea given that there can be correctness issues here (create computed column, toggle setting, insert rows, toggle back, now optimizer thinks it can infer computed values).
If we want to ensure correctness, the casts should become stable on the cluster forever when the setting is first toggled on (not sure how to do that though).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67792#-:-Mf4Mc6O7ehXB9qF9bDQ:bazph3k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @pbardea)

___
*[pkg/sql/sem/tree/casts.go, line 363 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67792#-Mf4LytM8FlFqrVCgSOJ:-Mf4LytM8FlFqrVCgSOK:bd19gpf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a8b0f28460bfa4f24d9a49030fedb165010059b/pkg/sql/sem/tree/casts.go#L363)):*
> ```Go
> var IntervalStyleClusterSetting = settings.RegisterBoolSetting(
> 	IntervalStyleClusterSettingName,
> 	"enables the use of IntervalStyle, preventing interval / string casts from being used as computed columns",
> ```

If we go this way, we should add docs explaining how you can shoot yourself in the foot if you toggle this and use computed columns, and this description should contain a link to that doc.

**Comment by RaduBerinde** [comment]
There is another wrinkle here related to plan caching - we can cache memo expressions and reuse them. We normally pay attention to certain session variables and don't reuse if they changed (see `Memo.IsStale`). This introduces a cluster setting that (unbeknownst to the optimizer) affects planning. It is conceivable that after you turn the setting on, a cached plan that infers a computed value is reused.

Also, the optimizer currently doesn't handle virtual columns with stable expressions. We will get an internal error when querying against an existing table with a virtual column expression which (after toggling the setting) is non-immutable. This can be fixed but would need some work from the opt side

**Comment by vy-ton** [comment]
> If it's experimental, the cluster setting should contain experimental. 

I prefer to omit `experimental` and have the feature flag default to `off`. We want to move away from experimental to indicate known issues for a feature we would like to support eventually. The feature gate default to `off` signals use at your own risk given the known correctness issues.

**Comment by otan** [comment]
> Memo.IsStale

i think i can add that check. IIUC, store the cluster setting last seen value on memo during Init, and check against it during IsStale. is it more difficult than that?

**Comment by RaduBerinde** [comment]
> i think i can add that check. IIUC, store the cluster setting last seen value on memo during Init, and check against it during IsStale. is it more difficult than that?

Not perfect, the cluster setting can be updated asynchronously, so there is a race between setting the last seen value and looking up the cast.

BTW I pointed out a similar problem in https://github.com/cockroachdb/cockroach/pull/67730, maybe you and Marcus can come up with something. IMO we should keep to the existing pattern of session setting + cluster setting for default.

**Comment by otan** [comment]
>  IMO we should keep to the existing pattern of session setting + cluster setting for default.

ah, so plumb sessiondata everywhere instead SV? i can do that instead.

**Comment by knz** [comment]
I am curious: postgres also has computed columns and materialized views. It would be surprising to me if it's behavior was unsound wrt IntervalStyle. What does PG do?

**Comment by otan** [comment]
> I am curious: postgres also has computed columns and materialized views. It would be surprising to me if its behavior was unsound wrt IntervalStyle. What does PG do?

it disallows non-immutable casts, so this would block.

**Comment by otan** [comment]
alrighty, changed to a session variable

**Comment by knz** [comment]
The release note still mentions a cluster setting

**Comment by otan** [comment]
the cluster setting is used as the default for the session variable

**Comment by knz** [comment]
> the cluster setting is used as the default for the session variable

nice :100: 

Another question that came up as I was thinking more about this: what is the advantage of gating the configuration behind a configuration flag?

The alternative behavior, it seems to me, is to continue to allow storing conversions in descriptors but *refuse processing them in queries unless the IntervalStyle session var is exactly 'postgres'*

(both when the DDL is issued, and also when queries using the stored conversions are issued)

This way:

- pre-21.2 clients that do not customize IntervalStyle get the current behavior "for free"
- pg-compatible clients who do customize IntervalStyle can do so without setting anything else (which might be a chore), as long as they don't use DDL that stores conversions (but since they are pg-compatible, they would not do so anyway)

**Comment by otan** [comment]
We're doing option 4 of https://docs.google.com/document/d/1X_7nADuNY9zvBkNUWfN0rIQIPQRKr4snLTWopSdAKVI/edit?usp=drivesdk. We need to convert the cast to Stable eventually, but in 20.2 we're allowing users to use it under the proviso they don't use it in a computed column. In 20.2 the Immutable built-in (not yet implemented) will be available and in 21.1 we will block upgrades (similar to how we will block interleaved tables from upgrading in the upcoming version) if we detect this.

**Comment by knz** [comment]
hm what I was outlining in my comment is really something like an "option 5" which, visibly, has not been considered yet. I wonder how they weigh against each other.

Regarding the conversion functions.
It seems that PostgreSQL already has one, so maybe we shouldn't invent our own:
image

But anyway, let's imagine we had our own conversion function `convert_interval(interval, style) -> string` that takes the intervalstyle as explicit argument.

Let's be a bit creative on this one: what if (hypothetically) we re-defined the semantic analysis of casts inside stored descriptors, so that any apparent cast of interval to string would be automatically converted to a function application `convert_interval(X, 'postgres')`.

Then we'd document that interval casts inside stored expressions are always treated as if intervalstyle had not been customized.

This way we get the above properties:


- pre-21.2 clients that do not customize IntervalStyle get the current behavior "for free"
- pg-compatible clients that do customize IntervalStyle can do so without setting anything else (which might be a chore), as long as they don't use DDL that stores conversions (but since they are pg-compatible, they would not do so anyway)

**Comment by otan** [comment]
The postgres to_char has a custom format, I guess feasible as well but a style option seems prudent as well.

I'd argue it's surprising that your proposal doesn't respect IntervalStyle / DateStyle and seems like a gotcha for both implementation and the user. Rewriting things from the descriptor seems mildly unpleasant. at the same time I don't see interval::string casts being this common to warrant something that complex and this migration simplifies thing better for the long term. I'm not opposed but I prefer this way around, unless others have a stronger opinion too.

> pg-compatible clients that do customize IntervalStyle can do so without setting anything else (which might be a chore), as long as they don't use DDL that stores conversions (but since they are pg-compatible, they would not do so anyway)

From the doc, non compatible clients do it anyway :)

**Review by knz — CHANGES_REQUESTED** [review]
Ok I have read the PR from beginning to end again and I have learned a few things that were not clear (to me) before that.
I think it is rather important to spell this out inside the commit message, at the very least under a release note:

Current text: 
> IntervalStyle can now only be set if the CLUSTER SETTING `sql.intervalstyle.enabled` is set to true.

This is not what the code does. (If it did, it would be a regression! The problem is that we don't want to disallow no-op assignments of `IntervalStyle` to `postgres`.)

Also this needs to explain the session variable now.

The correct text could perhaps be:
```
CockroachDB now uses the value of the `IntervalStyle` session var when interpreting interval to string conversions stored in computed columns, CHECK clauses, views and other parts of SQL table/view definitions.
This means that the particular results returned by these queries can become incoherent when `IntervalStyle` is customized to a different value from its default, `postgres`.

In order to provide guardrails against this incoherence, CockroachDB now provides a new, separate configuration knob called `intervalstyle_enabled`, that applications can use to "opt in" the ability to customize IntervalStyle:

- by default, this knob is false and applications cannot customize `IntervalStyle`. Interval to string conversions that are already stored in the schema are unaffected and continue to produce results as per the default style `postgres`

- when the knob is true, three things happen:
  - apps can start customizing `IntervalStyle` in SQL sessions.
  - the ability to *define*  a conversion from interval to string inside a table/view is *removed*, as they now would become invalid.
  - a SQL session that has a custom `IntervalStyle` will start observing *incoherent results* when accessing tables that already contain a conversion from interval to string.

We thus define our **best practice** henceforth as follows:
- for **previously created clusters**, users should inspect their schema and remove conversions from interval to string in computed columns, CHECK clauses, views etc., *before* they start allowing their apps to customize `IntervalStyle`
- for **newly created clusters** we recommend setting the `intevalstyle_enabled` knob to 'true' upfront, before any tables/views are created, to ensure that no incoherent conversions can ever be defined.

The knob works as follows: the *primary* configuration mechanism is a new cluster setting called `sql.defaults.intervalstyle.enabled`. This is the knob that operators and DBAs should customize manually. Then as a *secondary* configuration mechanism, the value of the cluster setting is also copied to each SQL session as a new session var `intervalstyle_enabled`. This is a performance optimization. SQL apps should not modify this session var directly, except for temporary testing purposes.
```

Separately from all my comments above, I wonder if it would not be wiser to thread just the *session data* through all the APIs. Making the sql EvalContext visible everywhere seems to be an overreach in scope and risks creating tangles of dependencies which we'd rather not have.

> Reviewed 15 of 25 files at r3, 11 of 13 files at r4, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67792#-:-Mf82aISAB-OkcoKFl7A:b5fvpzb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @otan, and @pbardea)

___
*[pkg/sql/exec_util.go, line 523 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67792#-Mf85dzZ0TJkf0VO3eTr:-Mf85dz_7SysCIzspmmZ:bjoe0v2) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c9019c81f236014ba4ebe239ea4b872dda838f/pkg/sql/exec_util.go#L523)):*
> ```Go
> 	"sql.defaults.intervalstyle.enabled",
> 	"default value for enable_intervalstyle session setting",
> 	false,
> ```

add a TODO to suggest this will flip to `true` in a later version.
___
*[pkg/sql/vars.go, line 819 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67792#-Mf85nC23vMMlDfv-DZV:-Mf85nC23vMMlDfv-DZW:b-lkzemf) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c9019c81f236014ba4ebe239ea4b872dda838f/pkg/sql/vars.go#L819)):*
> ```Go
> 					pgerror.Newf(
> 						pgcode.FeatureNotSupported,
> 						"setting IntervalStyle is only supported when the intervalstyle_enabled setting is enabled",
> ```

the word "enabled" is repeated
___
*[pkg/sql/vars.go, line 821 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67792#-Mf85XwR6Prrz7Qr3-7T:-Mf85XwR6Prrz7Qr3-7U:b-lrez8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c9019c81f236014ba4ebe239ea4b872dda838f/pkg/sql/vars.go#L821)):*
> ```Go
> 						"setting IntervalStyle is only supported when the intervalstyle_enabled setting is enabled",
> 					),
> 					`Using an IntervalStyle other than POSTGRES requires a stable volatility for string casts. As a result, computed columns must not contain casts from interval to string or vice versa. If this is done, use SET intervalstyle_enabled = true, or SET CLUSTER SETTING sql.defaults.intervalstyle_enabled = true to be enabled by default for all sessions.`,
> ```

I think this documentation is a bit confused. Is there a way to make it more concise with an example?

Maybe try this:

```go
errors.WithHint(
  pgerror.Newf(..., "IntervalStyle customization is not enabled in this session"),
  "You can enable IntervalStyle customization for all sessions with the cluster setting sql.defaults.intervalstyle_enabled, or per session using intervalstyle_enabled"
)
```

NB: hint, not detail.
___
*[pkg/sql/sessiondata/session_data.go, line 281 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67792#-Mf84wrm4D1S5HL9LjZ0:-Mf84wrm4D1S5HL9LjZ1:b-99o20d) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c9019c81f236014ba4ebe239ea4b872dda838f/pkg/sql/sessiondata/session_data.go#L281)):*
> ```Go
> 	// IntervalStyleEnabled allows the setting of IntervalStyle to different
> 	// values.
> 	IntervalStyleEnabled bool
> ```

Can you double check if it's sufficient to have this here? Don't we need to know about this in distsql processors, i.e. need to have it in the sessiondatapb?

**Review by otan — COMMENTED** [review]
i've updated the commit message mostly as described - we don't yet have a good way of blocking tables with these properties from being blocked yet because it would involve threading sessiondata to TypeCheck, which is (as you'd expect) a PITA. thanks for most of the text. there is more work to do for this release so i've filed an issue (#67887) and deferred accordingly.

i've narrowed the scope outside the optimiser. i don't see the evalcontext dependency as that big a deal in the places it's needed, however. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67792#-:-MfAWxBu2CictpHDETL6:bn7kt5u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @pbardea)

___
*[pkg/sql/exec_util.go, line 523 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67792#-Mf85dzZ0TJkf0VO3eTr:-MfAM-Wb1knIhHzbKfI_:b-fshapw) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c9019c81f236014ba4ebe239ea4b872dda838f/pkg/sql/exec_util.go#L523)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

add a TODO to suggest this will flip to `true` in a later version.
</blockquote></details>

added a TODO to remove it; it will always be enabled in 21.1
___
*[pkg/sql/vars.go, line 819 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67792#-Mf85nC23vMMlDfv-DZV:-MfAMF3t5XsGLwPOLVS2:by478ol) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c9019c81f236014ba4ebe239ea4b872dda838f/pkg/sql/vars.go#L819)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

the word "enabled" is repeated
</blockquote></details>

eh, one is part of the session var name.
___
*[pkg/sql/vars.go, line 821 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67792#-Mf85XwR6Prrz7Qr3-7T:-MfAMvnF3RjuaKny0Xub:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c9019c81f236014ba4ebe239ea4b872dda838f/pkg/sql/vars.go#L821)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think this documentation is a bit confused. Is there a way to make it more concise with an example?

Maybe try this:

```go
errors.WithHint(
  pgerror.Newf(..., "IntervalStyle customization is not enabled in this session"),
  "You can enable IntervalStyle customization for all sessions with the cluster setting sql.defaults.intervalstyle_enabled, or per session using intervalstyle_enabled"
)
```

NB: hint, not detail.
</blockquote></details>

Done.
___
*[pkg/sql/sessiondata/session_data.go, line 281 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67792#-Mf84wrm4D1S5HL9LjZ0:-MfAMwsyD00sgICzy3az:bdes0c6) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c9019c81f236014ba4ebe239ea4b872dda838f/pkg/sql/sessiondata/session_data.go#L281)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can you double check if it's sufficient to have this here? Don't we need to know about this in distsql processors, i.e. need to have it in the sessiondatapb?
</blockquote></details>

i'm not sure it's needed because `IntervalStyle` is the real source of truth, but in the spirit of supporting

**Review by knz — COMMENTED** [review]
Your release note talks about "volatility". This is not a user-facing concept and it's going to confuse the doc writer. I would recommend you explain the volatility outside of the release note and use something simpler inside the release note.

> we don't yet have a good way of blocking tables with these properties from being blocked yet because it would involve threading sessiondata to TypeCheck, which is (as you'd expect) a PITA

Are you sure it's a PITA?

We've done a good job with the SemaContext. Other things from the session can be found there, for example the AOST timestamp. The case at hand is likely a good use case for the SemaRejectFlags field.

> Reviewed 2 of 13 files at r4, 3 of 20 files at r6, 16 of 17 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67792#-:-MfC1KCx4G-oF8OdZBmh:b-owzf3p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @otan, and @pbardea)

___
*[pkg/sql/sessiondata/session_data.go, line 281 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67792#-Mf84wrm4D1S5HL9LjZ0:-MfC1lm--g-sXwqtac5l:b-bk6blr) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c9019c81f236014ba4ebe239ea4b872dda838f/pkg/sql/sessiondata/session_data.go#L281)):*
> but in the spirit of supporting

your sentence is truncated. What did you mean to say?

**Review by otan — COMMENTED** [review]
> We've done a good job with the SemaContext. Other things from the session can be found there, for example the AOST timestamp. The case at hand is likely a good use case for the SemaRejectFlags field.

SemaRejectsFlag is the pain point, but I found a different way which aligns with how we use SearchPath. I will add it to a later commit.

> Your release note talks about "volatility".

It definitely is a user facing concept in my eyes. Postgres defines this well and uses it throughout it's docs -- https://www.postgresql.org/docs/8.2/xfunc-volatility.html. We should do the same.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67792#-:-MfC35Bg6m-5mEHcKy4L:b-nphju1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @pbardea)

___
*[pkg/sql/sessiondata/session_data.go, line 281 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67792#-Mf84wrm4D1S5HL9LjZ0:-MfC2qvg-X8Y5Nc9WNfH:b-vcb5wj) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c9019c81f236014ba4ebe239ea4b872dda838f/pkg/sql/sessiondata/session_data.go#L281)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

> but in the spirit of supporting

your sentence is truncated. What did you mean to say?
</blockquote></details>

*supporting sqlproxy migrating settings i've changed it

**Review by knz — APPROVED** [review]
> Reviewed 1 of 18 files at r9, 17 of 17 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67792)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @otan, and @pbardea)

___
*[pkg/sql/sessiondata/session_data.go, line 281 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67792#-Mf84wrm4D1S5HL9LjZ0:-MfCjV28DXsceTwPYccs:b-k73z76) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c9019c81f236014ba4ebe239ea4b872dda838f/pkg/sql/sessiondata/session_data.go#L281)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

*supporting sqlproxy migrating settings i've changed it
</blockquote></details>

thanks

**Review by pbardea — COMMENTED** [review]
(Import plumbing LGTM)

**Comment by otan** [comment]
thanks for taking a squiz!

bors r+

**Comment by otan** [comment]
bors r-

whoo, bors found something !

**Pull request merged**
