### PR TITLE
keys: remove compatibility with pre-VersionMeta2Splits nodes

### PR DESCRIPTION
**Pull request by nvb**
This change removes the compatibility layer introduced with
`VersionMeta2Splits` that conditionally decided whether
splitting meta2 ranges was permitted. In doing so, it cleans
up some plumbing code that is no longer needed in 2.1 binaries.

Release note: None

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
This change brings up an interesting question. We don't have a defined process for what to do when old `cluster.VersionKey`s are no longer needed. We could leave them as they are or we could delete the `VersionKey` and the associated `keyedVersion` struct in the `versionsSingleton`.

**Comment by bdarnell** [comment]
:lgtm:

I think it's good idea to go back and remove old VersionKeys (and their associated runtime checks) when they're no longer needed. But we should probably go in order - don't remove VersionMeta2Splits before we've removed all the old ones. 

---

Reviewed 12 of 12 files at r1.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26967#-:-LFx07MW6NZ2HBH-X_ce:bh7tash)*

**Comment by nvanbenschoten** [comment]
> I think it's good idea to go back and remove old VersionKeys (and their associated runtime checks) when they're no longer needed. But we should probably go in order - don't remove VersionMeta2Splits before we've removed all the old ones.

That sounds reasonable to me. I went through and marked unused version keys (those that have had their associated runtime checks removed) as such. I also added instructions on deleting unstable versions. PTAL @ the new commit.

**Comment by bdarnell** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/settings/cluster/cockroach_versions.go, line 37 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26967#-LFxYk1kC536VFqyL2qs:-LFxYk1kC536VFqyL2qt:btwzuv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1bfabd527d600155aa3da295ee554e4f09894e2/pkg/settings/cluster/cockroach_versions.go#L37)):*
> ```Go
> //     file.
> //   - If the version key after a major or minor version is unused, remove it
> //     and its associated keyedVersion. However, don't remove major or minor
> ```

Why shouldn't major or minor versions be removed? 

I realized this is missing a step: you need to adjust the starting point of the `iota`. Since that's easy to get catastrophically wrong, I now think we should keep entries in this `const` list forever (but maybe unexport them when they become unused).

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26967)*

**Comment by nvanbenschoten** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/settings/cluster/cockroach_versions.go, line 37 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26967#-LFxYk1kC536VFqyL2qs:-LFxkpTm9ez9VjpY9qg1:bexxykj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1bfabd527d600155aa3da295ee554e4f09894e2/pkg/settings/cluster/cockroach_versions.go#L37)):*
> Why shouldn't major or minor versions be removed?

Removed that.

> I realized this is missing a step: you need to adjust the starting point of the iota. Since that's easy to get catastrophically wrong, I now think we should keep entries in this const list forever (but maybe unexport them when they become unused).

I considered this but convinced myself that it's not actually an issue. `VersionKey`s are only used to index into `versionsSingleton`. They're not persisted and not communicated between nodes. As long as a given `VersionKey` still indexes to the same `roachpb.Version` in `versionsSingleton` between binaries, we won't have a problem.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26967)*

**Comment by bdarnell** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/settings/cluster/cockroach_versions.go, line 37 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26967#-LFxYk1kC536VFqyL2qs:-LFxmobx8AaVrTRB-DIO:b-pp5tb9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1bfabd527d600155aa3da295ee554e4f09894e2/pkg/settings/cluster/cockroach_versions.go#L37)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> Why shouldn't major or minor versions be removed?

Removed that.

> I realized this is missing a step: you need to adjust the starting point of the iota. Since that's easy to get catastrophically wrong, I now think we should keep entries in this const list forever (but maybe unexport them when they become unused).

I considered this but convinced myself that it's not actually an issue. `VersionKey`s are only used to index into `versionsSingleton`. They're not persisted and not communicated between nodes. As long as a given `VersionKey` still indexes to the same `roachpb.Version` in `versionsSingleton` between binaries, we won't have a problem.
</blockquote></details>

Ack. I forgot that the persisted values are elsewhere. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26967)*

**Pull request merged**
