### PR TITLE
sql: Add a SHOW webui command.

### LINKED ISSUE #39942: sql: create SHOW WEBUI command
Oftentimes I am in the SQL shell and realize that I would like to see the webui for different reasons such as debugging, checking performance, etc. It'd be great to have a command that shows the webui url so that I could go to the webui without having to leave the sql shell and go to the cli. It could also be returned on a per-node basis, so if I'm in the SQL shell on node 3 then I'd get the corresponding webui for that node. 

Strawman proposal:

SHOW WEBUI;
Web UI: http://XXX.X.X.X:XXXXX

This would also be beneficial in the context of Cockroach Demo if you didn't notice it when first accessing the SQL shell.

### PR DESCRIPTION
**Pull request by rohany**
Fixes #39942.

Release note (sql change): Add a SHOW webui command

### CODE REVIEW

**Comment by knz** [comment]
A couple comments.

1. regarding design. See my comment here: https://github.com/cockroachdb/cockroach/issues/39942#issuecomment-526073029 - you'd be better served with a SHOW statement that delegates as a query to `node_runtime_info` so that we don't use multiple paths to the configuration.

2. the name "webui" is a bit terse an uninformative. At the very least "webui_url". Also perhaps "web_ui_url".

3. you really need a test for the new feature that asserts that the new thing produces a URL that indeed connects to the web UI, so as to prevent regressions.

4. the commit message needs to be extended. The release note must indicate what the new thing does and why it needs to exist (especially considered that some other feature was already available to achieve the same).

**Comment by rohany** [comment]
Yeah, I can replace this with a show alias if it is actually needed. I was unsure how to test this as the url returned changes — do you have suggestions?

**Comment by knz** [comment]
> I was unsure how to test this as the url returned changes — do you have suggestions?

start test server, send SQL, get URL, connect with go http, check something valid comes back.

**Comment by rohany** [comment]
closing this as it's pretty out of date, and discussion on the main issue indicates this isn't a valid approach.

**Pull request closed without merging**
