### PR TITLE
storage: avoid potential crash on double ingestion

### PR DESCRIPTION
**Pull request by tbg**
cc @dt

I'm trying to push ahead with the migration RFC, so the test will have to wait
a bit, but the affected parties should cherry pick. Volunteer test writing is
also accepted.

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
LGTM

**Comment by dt** [comment]
How do you feel about merging now so we can keep stability testing from master builds, and leaving the test as a TODO (can be done in feature freeze?)

**Comment by danhhz** [comment]
+1. There's some higher priority things to finish in the next 7 days than the test for this. Maybe file an issue too so we don't forget tho

**Comment by tschottdorf** [comment]
Ok, just rebased. Will merge on green.

**Pull request merged**
