### PR TITLE
sql/importer: record plan diagram in job progress

### PR DESCRIPTION
**Pull request by dt**
Release note: none.

### CODE REVIEW

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79232)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @stevendanna)

___
*[pkg/sql/importer/import_processor_planning.go, line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79232#-MzaBvjs7YIXW-CyeH7f:-MzaBvjs7YIXW-CyeH7g:b-h9h5br) ([raw file](https://github.com/cockroachdb/cockroach/blob/15942b229c39d6ee8d0c177b70bde5ddcd618874/pkg/sql/importer/import_processor_planning.go#L122)):*
> ```Go
> 					}
> 				}
> 				prog.DebugFlowDiagram = diagram
> ```

how large could that get?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79232)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @miretskiy, and @stevendanna)

___
*[pkg/sql/importer/import_processor_planning.go, line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79232#-MzaBvjs7YIXW-CyeH7f:-MzaCEc-ADNo9AB6amWU:b-uji3xe) ([raw file](https://github.com/cockroachdb/cockroach/blob/15942b229c39d6ee8d0c177b70bde5ddcd618874/pkg/sql/importer/import_processor_planning.go#L122)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

how large could that get?
</blockquote></details>

it can be decently big -- few KB at least, maybe 1mb.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79232)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @miretskiy, and @stevendanna)

___
*[pkg/sql/importer/import_processor_planning.go, line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79232#-MzaBvjs7YIXW-CyeH7f:-MzaCTYAEkX_xz5ytA4w:b-fjgiyw) ([raw file](https://github.com/cockroachdb/cockroach/blob/15942b229c39d6ee8d0c177b70bde5ddcd618874/pkg/sql/importer/import_processor_planning.go#L122)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

it can be decently big -- few KB at least, maybe 1mb.
</blockquote></details>

it's basically going to track, almost exactly, the size of details.URIs



I ask because we're putting this stuff in jobs table...  Is this a concern?

**Comment by dt** [comment]
> I ask because we're putting this stuff in jobs table... Is this a concern?

(somehow eded up in my comment?)

Yeah, it's a good concern (and one which is just calling out for a better place to store things than the one-row-per-job jobs table). Each Time we update progress -- i.e. every minuet for the life of the job -- we'll rewrite this string which is roughy the sum of all the file name lengths, which, if they are each big, key-laden cloud URIs, could big-ish.

I suppose I could move it to details -- that already has the uri list in it, so it the same weight vs a few ints/floats in progress. I don't love writing to details a variable number of times though -- once for every flow plan, so once on every retry -- but I suppose that ship already sailed with the jobs system itself writing retry count / exec err backoff info in payload (for unknown reasons... maybe @ajwerner knows).

I'll try moving this to details.

**Comment by ajwerner** [comment]
> once for every flow plan, so once on every retry -- but I suppose that ship already sailed with the jobs system itself writing retry count / exec err backoff info in payload (for unknown reasons... maybe [@ajwerner](https://github.com/ajwerner) knows).

Well, we counters themselves are separate. Just the "error" log is in the details. It's probably regrettable. 

https://github.com/cockroachdb/cockroach/blob/90054c6b7b9629aeb904ffd4c0b9161f70e214b7/pkg/sql/catalog/systemschema/system.go#L195-L198

**Pull request closed without merging**
