### PR TITLE
bazel: unlist unsupported os+arch combos

### PR DESCRIPTION
**Pull request by irfansharif**
We don't support these for CRDB builds. Even windows is experimental,
but lets keep that around anyway since we publish binaries for it.

+cc #82625.

Release note: None

### CODE REVIEW

**Review by rickystewart — CHANGES_REQUESTED** [review]
`dev generate bazel`

**Review by irfansharif — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82635#-:-N44Tvj_BCuGnVyscgTo:b-896fix)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sjbarag)

**Review by rickystewart — APPROVED** [review]

**Comment by rickystewart** [comment]
Looks fine, you just have to resolve the conflicts.

**Comment by irfansharif** [comment]
Thanks!

bors r+

**Pull request merged**
