### PR TITLE
distsql: fix outer join problems

### PR DESCRIPTION
**Pull request by RaduBerinde**
### distsql: minor cleanup in hashjoiner

Clarifying and simplifying the return cases of the two phases.

### distsql: fix outer join problems
I was working on the hashjoiner and noticed that we incorrectly handle outer
joins if there are multiple rows with the same value on the equality columns.
Here is an example:

```
Left       Right
----------------
1 1        1 2
           1 3
           1 4
Equality columns:   Left(1) = Right(1)
Extra ON condition: Left(2) + Right(2) = 4
```

If we are doing a left outer join, the correct output is:
```
1 1 1 3
```
The current code makes the decision to emit an "outer" result for every pair of
rows we try to render; this incorrectly results in multiple "outer" results for
the same row:
```
1 1 NULL NULL
1 1 1    3
1 1 NULL NULL
```

Moving the decision at a higher level: keep track of whether there was any
"match" for a given left row, and only output the "outer" result if there
wasn't.

A similar fix is made for merge joins. The stream merger code is changed to
return sets of left and right rows for each group, rather than returning a
group cross-product.

### CODE REVIEW

**Comment by andreimatei** [comment]
LGTM

Any reason why you haven't added a logic test?

---

Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 36 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16372#-Km2AVyJRPIWsPgcfvXN:-Km2AVyK1j1yhZ0HabOs:b-s34q9s) ([raw file](https://github.com/cockroachdb/cockroach/blob/82961ed2f76ad58b81c946aa4750811324557261/pkg/sql/distsqlrun/hashjoiner.go#L36)):*
> ```Go
> 	// rows holds indices of rows into the hashJoiner's rows container.
> 	rows []int
> 	// seen is only used for outer joins; there is a entry for each row in `rows`
> ```

s/outer/right- and full-outer

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 262 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16372#-Km27-B-jaoAj5HlxWoI:-Km27-B01Ish6tM0hMUZ:b-8ociu7) ([raw file](https://github.com/cockroachdb/cockroach/blob/82961ed2f76ad58b81c946aa4750811324557261/pkg/sql/distsqlrun/hashjoiner.go#L262)):*
> ```Go
> 		matched := false
> 
> 		if !hasNull {
> ```

consider repeating the comment from the build phase about how, if the row has a null in an eq col, it can't match anything

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 278 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16372#-Km2BGL3kXGqpkRrUlVl:-Km2BGL3kXGqpkRrUlVm:b85suvw) ([raw file](https://github.com/cockroachdb/cockroach/blob/82961ed2f76ad58b81c946aa4750811324557261/pkg/sql/distsqlrun/hashjoiner.go#L278)):*
> ```Go
> 							b.seen[i] = true
> 						}
> 						if !emitHelper(ctx, &h.out, renderedRow, ProducerMetadata{}, h.leftSource) {
> ```

I suggest moving this `emitHelper()` call down, next to the `maybeEmitUnmatchedRow()` call. 
And also get rid of the `matched` variable and lift `renderedRow` up (and test it for !=nil to see if you have an unmatched row.
And then you can put a comment on this whole `if !hasNull` block about how it's all about finding a match (or even extract it in a different method).

---

*[pkg/sql/distsqlrun/joinerbase.go, line 62 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16372#-Km25vzjI-__zERkwQ9b:-Km25vzjI-__zERkwQ9c:bkzlgx6) ([raw file](https://github.com/cockroachdb/cockroach/blob/82961ed2f76ad58b81c946aa4750811324557261/pkg/sql/distsqlrun/joinerbase.go#L62)):*
> ```Go
> 	}
> 
> 	jb.combinedRow = make(sqlbase.EncDatumRow, len(leftTypes)+len(rightTypes))
> ```

I don't quite see why you allocate the size here, and not just capacity. Since you're always overwriting the whole array, it technically doesn't make a difference, but I think that just allocating capacity would express the intent better.

---

*[pkg/sql/distsqlrun/mergejoiner.go, line 139 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16372#-Km2CpcHtLQX2Q0XQvYz:-Km2CpcHtLQX2Q0XQvZ-:b-1mwo30) ([raw file](https://github.com/cockroachdb/cockroach/blob/82961ed2f76ad58b81c946aa4750811324557261/pkg/sql/distsqlrun/mergejoiner.go#L139)):*
> ```Go
> 	}
> 
> 	if matchedRight != nil {
> ```

// Produce results for unmatched right rows (for RIGHT OUTER or FULL OUTER).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16372#-:-Km2DOGRdaffLFrlYYaW:b-hoaemh)*

**Comment by arjunravinarayan** [comment]
*[pkg/sql/distsqlrun/hashjoiner.go, line 262 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16372#-Km27-B-jaoAj5HlxWoI:-Km2DzwjgRTCZ3wFfNUx:b3h44qd) ([raw file](https://github.com/cockroachdb/cockroach/blob/82961ed2f76ad58b81c946aa4750811324557261/pkg/sql/distsqlrun/hashjoiner.go#L262)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

consider repeating the comment from the build phase about how, if the row has a null in an eq col, it can't match anything
</blockquote></details>

The comment appears to be ~10 lines above?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16372)*

**Comment by arjunravinarayan** [comment]
*[pkg/sql/distsqlrun/hashjoiner.go, line 262 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16372#-Km27-B-jaoAj5HlxWoI:-Km2ERsbqHcWHun5m7uz:b-kjr60y) ([raw file](https://github.com/cockroachdb/cockroach/blob/82961ed2f76ad58b81c946aa4750811324557261/pkg/sql/distsqlrun/hashjoiner.go#L262)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

The comment appears to be ~10 lines above?
</blockquote></details>

NVM, my bad. I see your point now that I'm reviewing r2. This comment was showing up when I was reviewing r1 separately, and it made no sense in that context.

I agree with Andrei.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16372)*

**Comment by arjunravinarayan** [comment]
Healthy amount of :dog:, I focused mostly on replicating the behavior from your description, and walking through the tests, which make sense to me. I think this level of testing is good, I'm now wondering if we need to greatly expand the size of our logic test suite, to see if we would catch this sort of semantic difference (I hesitate to call it a 'bug') at an earlier stage of development. I concur with Andrei that at the very least we should add (or file an issue to add) more logic tests on the outer hash joins.

:lgtm: 

---

Reviewed 1 of 1 files at r1, 3 of 6 files at r2.
Review status: 3 of 6 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/joinerbase.go, line 91 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16372#-Km2_-waZ9B2Yf357GpT:-Km2_-wbyVFuTzodu72n:b9vmkbc) ([raw file](https://github.com/cockroachdb/cockroach/blob/82961ed2f76ad58b81c946aa4750811324557261/pkg/sql/distsqlrun/joinerbase.go#L91)):*
> ```Go
> 
> // maybeEmitUnmatchedRow is used for rows that don't match anything in the other
> // table; we emit them if it's the right kind of outer join, otherwise we
> ```

"right kind of outer join" is a weird phrase.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16372#-:-Km2ZDhWqr2I-nmTo_9J:b-bdum6u)*

**Comment by RaduBerinde** [comment]
TFTRs!

We don't currently run outer joins through distsql, so logic tests don't exercise this. This is not a functional issue currently, but hopefully we will plan outer joins soon. The main reason I'm fixing it now is that I'm refactoring some code in hashjoiner and I'd rather make it work right than come back to it later.

---

Review status: 3 of 6 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 36 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16372#-Km2AVyJRPIWsPgcfvXN:-Km2b6PVziuCnoq5NrtI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/82961ed2f76ad58b81c946aa4750811324557261/pkg/sql/distsqlrun/hashjoiner.go#L36)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/outer/right- and full-outer
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 262 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16372#-Km27-B-jaoAj5HlxWoI:-Km2bJD2bSFlMFWFfd1e:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/82961ed2f76ad58b81c946aa4750811324557261/pkg/sql/distsqlrun/hashjoiner.go#L262)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

NVM, my bad. I see your point now that I'm reviewing r2. This comment was showing up when I was reviewing r1 separately, and it made no sense in that context.

I agree with Andrei.
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 278 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16372#-Km2BGL3kXGqpkRrUlVl:-Km2bUZSYFNdY0fAio7h:bs0wvdw) ([raw file](https://github.com/cockroachdb/cockroach/blob/82961ed2f76ad58b81c946aa4750811324557261/pkg/sql/distsqlrun/hashjoiner.go#L278)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I suggest moving this `emitHelper()` call down, next to the `maybeEmitUnmatchedRow()` call. 
And also get rid of the `matched` variable and lift `renderedRow` up (and test it for !=nil to see if you have an unmatched row.
And then you can put a comment on this whole `if !hasNull` block about how it's all about finding a match (or even extract it in a different method).
</blockquote></details>

That does not work. We need to output a render row for each row that "matches". If I join
```
1 1
```
with
```
1 2
1 3
1 4
```
on column 1, we need to emit the following rendered rows:
```
1 1 1 2
1 1 1 3
1 1 1 4
```

---

*[pkg/sql/distsqlrun/joinerbase.go, line 62 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16372#-Km25vzjI-__zERkwQ9b:-Km2c35BxYJvw45hD8Mx:b-80tlqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/82961ed2f76ad58b81c946aa4750811324557261/pkg/sql/distsqlrun/joinerbase.go#L62)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't quite see why you allocate the size here, and not just capacity. Since you're always overwriting the whole array, it technically doesn't make a difference, but I think that just allocating capacity would express the intent better.
</blockquote></details>

Sure.

---

*[pkg/sql/distsqlrun/joinerbase.go, line 91 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16372#-Km2_-waZ9B2Yf357GpT:-Km2cLv47IdObwr46elt:b9dfuu3) ([raw file](https://github.com/cockroachdb/cockroach/blob/82961ed2f76ad58b81c946aa4750811324557261/pkg/sql/distsqlrun/joinerbase.go#L91)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

"right kind of outer join" is a weird phrase.
</blockquote></details>

Rephrased.

---

*[pkg/sql/distsqlrun/mergejoiner.go, line 139 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16372#-Km2CpcHtLQX2Q0XQvYz:-Km2cgvRbXcfCYzOqiQm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/82961ed2f76ad58b81c946aa4750811324557261/pkg/sql/distsqlrun/mergejoiner.go#L139)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

// Produce results for unmatched right rows (for RIGHT OUTER or FULL OUTER).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16372#-:-Km2aTJiqX-WnNbw1FGz:b-oeyj90)*

**Comment by andreimatei** [comment]
Review status: 3 of 6 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 278 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16372#-Km2BGL3kXGqpkRrUlVl:-Km2ehjQ1ZEWdlK9HF89:bkf0983) ([raw file](https://github.com/cockroachdb/cockroach/blob/82961ed2f76ad58b81c946aa4750811324557261/pkg/sql/distsqlrun/hashjoiner.go#L278)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

That does not work. We need to output a render row for each row that "matches". If I join
```
1 1
```
with
```
1 2
1 3
1 4
```
on column 1, we need to emit the following rendered rows:
```
1 1 1 2
1 1 1 3
1 1 1 4
```
</blockquote></details>

ah yeah. You could then accumulate matches in a temp array of indexes and do all the emitting down below, but now I don't really care.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16372)*

**Comment by RaduBerinde** [comment]
Review status: 3 of 6 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 278 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16372#-Km2BGL3kXGqpkRrUlVl:-Km2gohVGWVzJsYGbu0T:bvviwiq) ([raw file](https://github.com/cockroachdb/cockroach/blob/82961ed2f76ad58b81c946aa4750811324557261/pkg/sql/distsqlrun/hashjoiner.go#L278)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

ah yeah. You could then accumulate matches in a temp array of indexes and do all the emitting down below, but now I don't really care.
</blockquote></details>

What would be the benefit of that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16372)*

**Comment by andreimatei** [comment]
Review status: 3 of 6 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 278 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16372#-Km2BGL3kXGqpkRrUlVl:-Km2hUuxLhmUalgaP1uL:busbvuq) ([raw file](https://github.com/cockroachdb/cockroach/blob/82961ed2f76ad58b81c946aa4750811324557261/pkg/sql/distsqlrun/hashjoiner.go#L278)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

What would be the benefit of that?
</blockquote></details>

I was thinking it may be cleaner to have the emitting for both the "matched" and unmatched cases in one place. But no big deal, this is also fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16372)*

**Pull request merged**
