### PR TITLE
mvcc: benchmark conditional put

### PR DESCRIPTION
**Pull request by dt**
```
name                              time/op
MVCCConditionalPutCreate10-8        5.87µs ± 2%
MVCCConditionalPutCreate100-8       6.03µs ± 2%
MVCCConditionalPutCreate1000-8      8.29µs ±13%
MVCCConditionalPutCreate10000-8     29.6µs ± 7%
MVCCConditionalPutReplace10-8       8.73µs ± 4%
MVCCConditionalPutReplace100-8      9.02µs ± 2%
MVCCConditionalPutReplace1000-8     15.0µs ± 6%
MVCCConditionalPutReplace10000-8    56.6µs ± 3%

name                              speed
MVCCConditionalPutCreate10-8      1.70MB/s ± 1%
MVCCConditionalPutCreate100-8     16.6MB/s ± 2%
MVCCConditionalPutCreate1000-8     121MB/s ±11%
MVCCConditionalPutCreate10000-8    338MB/s ± 7%
MVCCConditionalPutReplace10-8     1.15MB/s ± 4%
MVCCConditionalPutReplace100-8    11.1MB/s ± 2%
MVCCConditionalPutReplace1000-8   66.7MB/s ± 6%
MVCCConditionalPutReplace10000-8   177MB/s ± 3%

name                              alloc/op
MVCCConditionalPutCreate10-8          128B ± 0%
MVCCConditionalPutCreate100-8         128B ± 0%
MVCCConditionalPutCreate1000-8        128B ± 0%
MVCCConditionalPutCreate10000-8       128B ± 0%
MVCCConditionalPutReplace10-8         192B ± 0%
MVCCConditionalPutReplace100-8        288B ± 0%
MVCCConditionalPutReplace1000-8     1.20kB ± 0%
MVCCConditionalPutReplace10000-8    10.7kB ± 0%

name                              allocs/op
MVCCConditionalPutCreate10-8          2.00 ± 0%
MVCCConditionalPutCreate100-8         2.00 ± 0%
MVCCConditionalPutCreate1000-8        2.00 ± 0%
MVCCConditionalPutCreate10000-8       2.00 ± 0%
MVCCConditionalPutReplace10-8         4.00 ± 0%
MVCCConditionalPutReplace100-8        4.00 ± 0%
MVCCConditionalPutReplace1000-8       4.00 ± 0%
MVCCConditionalPutReplace10000-8      4.00 ± 0%
```

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4303)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM.

Are all our benchmarks using in-memory `rocksdb`s? Perhaps we should benchmark both variants; who knows what surprises await.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4303#-:-KACkauZYRvIndPMHStP:14062796)*

**Comment by petermattis** [comment]
Most of our MVCC benchmarks use disk-based rocksdb engines.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/engine/rocksdb_test.go, line 413 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4303#-KACl9qNv-AbZT5POtF6:-KACl9qNv-AbZT5POtF7:828825103) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbb6676251df604ca4dc7732d62f3a7514053f54/storage/engine/rocksdb_test.go#L413)):*
This is only testing the case where nothing is being overwritten. Should probably also test a case where it performs a second conditional put operation on each iteration where it expects to see the previously written value.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4303#-:-KAClKKql2KXE-tfeUiO:1616720573)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/engine/rocksdb_test.go, line 413 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4303#-KACl9qNv-AbZT5POtF6:-KAClgrZLAbFSmPFrjPn:-1198446356) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbb6676251df604ca4dc7732d62f3a7514053f54/storage/engine/rocksdb_test.go#L413)):*
Maybe add an argument that controls the clean/overwrite/ConditionFailedError ratios.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4303)*

**Comment by dt** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/engine/rocksdb_test.go, line 413 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4303#-KACl9qNv-AbZT5POtF6:-KAFctHtU8ksPePfZ4f-:1785409403) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbb6676251df604ca4dc7732d62f3a7514053f54/storage/engine/rocksdb_test.go#L413)):*
updated with a simple create-vs-replace bool for now.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4303)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4303)*

**Comment by petermattis** [comment]
LGTM

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4303#-:-KAFn2HJgavLs3GWR5EL:676834233)*

**Pull request merged**
