### PR TITLE
cli: replace "cockroach" sql driver with "postgres" driver

### PR DESCRIPTION
**Pull request by petermattis**
[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4552)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM

**Comment by vivekmenezes** [comment]
LGTM

**Comment by andreimatei** [comment]
Does anything still use the cockroach sql driver? Can we delete it?
I'm asking because then we could change other random code, like making the Session not be a proto any more.

**Comment by tamird** [comment]
I believe the front end still uses it.

**Pull request merged**
