### PR TITLE
storage: move Store.AddReplicaTest out of production code

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9720)

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM

**Comment by tamird** [comment]
Rename it `AddReplica` while you're here?

**Comment by tamird** [comment]
LGTM

**Comment by petermattis** [comment]
Sure, renamed to `AddReplica`.

**Comment by tamird** [comment]
LGTM

**Pull request merged**
