### PR TITLE
logictest: skip `distsql_tenant_locality` under duress

### PR DESCRIPTION
**Pull request by rickystewart**
Flaky test: see #118627

Epic: None
Release note: None

### CODE REVIEW

**Review by michae2 — APPROVED** [review]
You beat me to it! Thanks, sorry I didn't do this earlier. :lgtm:

> Reviewed 1 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118769#-:-NpuO-fzD88tdIk83yd9:b-lii7dd)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rickystewart)

___
*[`pkg/cmd/generate-logictest/templates.go` line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118769#-NpuNeBK9gABfuK4g0sV:-NpuNeBK9gABfuK4g0sW:b2tun1z) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b5f45f42bc7daf96dead09a324ff27464d7ffa6/pkg/cmd/generate-logictest/templates.go#L76)):*
> ```Go
> 	defer sql.TestingOverrideExplainEnvVersion("CockroachDB execbuilder test version")()
> 	if file == "distsql_tenant_locality" {
> 		skip.WithIssue(t, 118627)
> ```

We've only seen the failures under stress. Would `skip.UnderStress` be more targeted?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118769)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @michae2)

___
*[`pkg/cmd/generate-logictest/templates.go` line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118769#-NpuNeBK9gABfuK4g0sV:-NpuOVDpEG_fCZQsh3Vd:bkhfl9q) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b5f45f42bc7daf96dead09a324ff27464d7ffa6/pkg/cmd/generate-logictest/templates.go#L76)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

We've only seen the failures under stress. Would `skip.UnderStress` be more targeted?
</blockquote></details>

I second this - I think skipping under stress is the right approach (some context is in https://github.com/cockroachdb/cockroach/pull/118559#issuecomment-1927572753).

**Comment by yuzefovich** [comment]
We should also revert 051191c2dbae7867122fbf20ad01d55bd0ba6619 as part of the skip.

**Comment by rickystewart** [comment]
How about skipping under duress? That would include stress as well as `race`.

**Comment by yuzefovich** [comment]
Sounds good to me.

**Comment by michae2** [comment]
Is there a way we could put the skip information into the logictest itself, rather than into the template? I know we have `skipif`, would that work?

**Review by michae2 — APPROVED** [review]
(That was just an idea, this is also fine with me.) LGTM

**Comment by rickystewart** [comment]
> Is there a way we could put the skip information into the distsql_tenant_locality logictest itself, rather than into the template? I know we have skipif, would that work?

AFAIK logictests have no "skip under X condition" directives or anything like that with functionality corresponding to the `skip` package. It would be very convenient.

**Review by yuzefovich — APPROVED** [review]
:lgtm: Thanks!

> Reviewed 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118769#-:-NpuRanK0Ta3Qjk4Qdgu:b-g2a5fb)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @rickystewart)

___
*[`pkg/sql/opt/exec/execbuilder/testdata/distsql_tenant_locality` line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118769#-NpuRIOuAw25vDopHlPt:-NpuRIOuAw25vDopHlPu:b-zhqdf0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b63d1a472cc8f8b1665bc01c5dadc7dbd2f75f6/pkg/sql/opt/exec/execbuilder/testdata/distsql_tenant_locality#L55)):*
> ```
> # - TableReader on SQL Instance 3 to scan Span /106/1/3/0
> # - TableReader on SQL Instance 1 to scan Span /106/1/5/0.
> query T retry
> ```

nit: we should remove `retry` here too (it was added in the previous attempt at fixing the test 85439c316a6f6f2e830e6dfe0a19bd155f02416a).

**Comment by rickystewart** [comment]
Should be good now.

**Comment by rickystewart** [comment]
TFTRs!

bors r=yuzefovich,michae2

**Pull request merged**
