### PR TITLE
sqlccl: make backup/restore work with sql placeholders

### PR DESCRIPTION
**Pull request by danhhz**
Introduces TypeAsString and TypeAsStringArray to encapsulate the logic
for registering the string as a placeholder and later getting its value.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14292)

### CODE REVIEW

**Comment by knz** [comment]
Nicely done! ;)

LGTM with nit over the test code

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/ccl/sqlccl/backup_test.go, line 226 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14292#-Kfm2C6ZZN6000OAYzfS:-Kfm2C6ZZN6000OAYzfT:b6ofo4y) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfd5401fecafda482053b5d75f76c34a061a0c7d/pkg/ccl/sqlccl/backup_test.go#L226)):*
> ```Go
> 	// and 4x in i1.
> 	for i := 0; i < numAccounts; i++ {
> 		_ = sqlDB.Exec(`INSERT INTO i0 VALUES ($1, 1), ($2, 2)`, i, i)
> ```

`Exec("VALUES ($1, 1), ($1, 2)", i)`
`Exec("INSERT INTO i0_0 VALUES ($1, 1, 1), ($1, 2, 2), ($1, 3, 3)", i)`

here and below

(Also, a tip from nikhil, who taught me this last week: `fmt.Printf("Hello, %[1]s and %[1]s!", "grandma")`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14292#-:-Kfm3-N6qwBD20MTWOg1:bsr9b79)*

**Comment by danhhz** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/ccl/sqlccl/backup_test.go, line 226 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14292#-Kfm2C6ZZN6000OAYzfS:-Kfm4Jr1GQpPgCQhV5j-:b7ctszk) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfd5401fecafda482053b5d75f76c34a061a0c7d/pkg/ccl/sqlccl/backup_test.go#L226)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`Exec("VALUES ($1, 1), ($1, 2)", i)`
`Exec("INSERT INTO i0_0 VALUES ($1, 1, 1), ($1, 2, 2), ($1, 3, 3)", i)`

here and below

(Also, a tip from nikhil, who taught me this last week: `fmt.Printf("Hello, %[1]s and %[1]s!", "grandma")`)
</blockquote></details>

Done. Did I catch all the ones you meant?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14292)*

**Comment by mjibson** [comment]
Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/planhook.go, line 45 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14292#-Kfm447ZJtYnH2DpofT9:-Kfm447ZJtYnH2DpofTA:b-af1wyc) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfd5401fecafda482053b5d75f76c34a061a0c7d/pkg/sql/planhook.go#L45)):*
> ```Go
> type PlanHookState interface {
> 	ExecCfg() *ExecutorConfig
> 	TypeAsString(e *parser.Expr) (func() string, error)
> ```

This seems not great. Why are these functions the only ones needed like this? That is, why aren't there other `TypeAsX` functions already? Is this what Raphael recommends?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14292)*

**Comment by mjibson** [comment]
Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/planhook.go, line 45 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14292#-Kfm447ZJtYnH2DpofT9:-Kfm4nqVjqldIbIk2COV:b-h8x2wq) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfd5401fecafda482053b5d75f76c34a061a0c7d/pkg/sql/planhook.go#L45)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

This seems not great. Why are these functions the only ones needed like this? That is, why aren't there other `TypeAsX` functions already? Is this what Raphael recommends?
</blockquote></details>

I guess if he LGTM'd it this is ok. But I'd like to understand why.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14292)*

**Comment by danhhz** [comment]
Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/planhook.go, line 45 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14292#-Kfm447ZJtYnH2DpofT9:-Kfm4zUX3WA9pfUfcw0w:b-dhnjnc) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfd5401fecafda482053b5d75f76c34a061a0c7d/pkg/sql/planhook.go#L45)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I guess if he LGTM'd it this is ok. But I'd like to understand why.
</blockquote></details>

I could have exposed the semantic context so the backup/restore hooks called TypeCheck directly (and subsequently `string(*(*e).(*parser.DString))`), but did it this way to hide some of the details

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14292)*

**Comment by danhhz** [comment]
Thanks for the reviews!

**Pull request merged**
