### PR TITLE
release-21.2: importccl: add IMPORT INTO UDT support for default+computed columns

### PR DESCRIPTION
**Pull request by adityamaru**
Backport 1/1 commits from #69779.

/cc @cockroachdb/release

Backport 1/1 commits from #69616.

/cc @cockroachdb/release
---

This change builds on the work in #69674 and uses the type
descriptors stored on the import job during planning to construct
a custom type resolver. This resolver is used when hydrating the
types used by the table being imported into, and when processing
default + computed columns.

Informs: #61133

Release note (sql change): IMPORT INTO now supports UDT for default
and computed columns.

Release justification: fixes for high-priority or high-severity bugs in existing functionality

importccl: add support for IMPORT INTO RBR table
This change overrides the `default_to_database_primary_region`
and `gateway_region` to always return the primary region of the
database of the table being imported into. This allows for
IMPORT INTO an RBR table.

To ensure that the import is idempotent across resumptions, we cache
the primary region of the database being imported into, during planning.
This information is store in the job details and flow spec to be used
when evaluating the relevant default expr/computed column

Since IMPORT is a job, it does not have an associated session data
and so it cannot rely on the planners' implementation of the regional
operator. This change also implements the relevant methods in the
`importRegionOperator` to allow resolution of the primary region
of the database being imported into.

Fixes: #69616

Release note (sql change): IMPORT INTO regional by row tables
is supported.

Release justification: fixes for high-priority or high-severity bugs in existing functionality

### CODE REVIEW

**Review by ajstorm — COMMENTED** [review]
I think we should bring this one to Monday's triage meeting.  @dt do you have thoughts as to whether or not we should backport now or wait until 21.2.1?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70270#-:-Mjm-9IZ3kC-jf5zeqE8:bvrjgz1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

**Comment by dt** [comment]
My leaning is towards now, which would imply classifying lack of RBR IMPORT as a ga-blocker if you/Andy concur with that severity assessment

**Comment by ajstorm** [comment]
While I *really *want to get this into 21.2, seeing as how we lived without
this in 21.1, I'm not sure how we could justify making this a ga-blocker
(i.e. we'd hold up the release if we couldn't get this in).  It just
doesn't seem to fit the definition.  Happy to have my mind changed on this
though.

**Comment by dt** [comment]
I don't feel strongly enough either way to go to bat here. If there was an argument for tagging as ga-blocker, I think it'd be  a) RBR and MR is a banner feature and differentiator that may be what draws someone to evaluate Cockroach b) IMPORT is often the database's doorstep, the first step someone crosses when they try to evaluate it, c) a major release often draws attention and encourages new people to evaluate it (on the .0 version). I don't know if that is enough to say, for example, that we would be willing to hypothetically delay .0 a day to fix it or not though.

(also, FWIW, the process _does_ recognize that blocker status is mutable, and importantly may depend on other unrelated factors e.g. if a potential release has an urgent fix in it, that might justify releasing it, even if it is missing other fixes, which implies the issues they would be fixing are no longer release-blocking. So you can say "yes, this is a blocker: I'd argue to block the release for up to a day to fix it" while recognizing you might change your mind later if it took longer or something else outweighed it. I don't know if that changes the math on this though).

**Comment by ajstorm** [comment]
@awoods187 Since neither David or I are convinced that this is backport worthy for the GA (by the strict release blocker definition), do you care to make the case for why it should be in the `.0` release?

**Comment by awoods187** [comment]
I think David outlined the case for why we would want to include this in the .0. I believe it is silent friction that makes it harder for people to try and use multi-region and we should fix it for that region for the .0. I'll defer to the two of you on how risky it would be to include it, and if its too risky, advocate for 20.2.1.

**Comment by dt** [comment]
Discussed today in release meeting. In light of Product advocating on basis of impact and eng okay with risk, we decided to move forward with backport.

**Pull request merged**
