### PR TITLE
storage: add latency statistics for commits to raft log / raft commands

### PR DESCRIPTION
**Pull request by spencerkimball**
Addresses #14108

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ui/src/containers/nodeGraphs.tsx, line 458 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15438#-Kim-4iiw62vca0EaIcM:-Kim-4iiw62vca0EaIcN:buq3rmb) ([raw file](https://github.com/cockroachdb/cockroach/blob/06dd275104a603adcc913e35388eac42d57e7067/pkg/ui/src/containers/nodeGraphs.tsx#L458)):*
> ```XML
>               }
>             </Axis>
>           </LineGraph>
> ```

Is this 2 separate graphs? Perhaps 1 graph with 2 separate lines would be more compact, though I have no idea how to do that properly.

Perhaps we should leave this off the admin UI for now until we see on Grafana whether it is useful. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15438#-:-Kim-MF5OfuYyCwPLINH:bnfp4nl)*

**Comment by a-robinson** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15438#-:-KimSp_DUt_kSHPIvVbv:bnfp4nl)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15438#-:-KimdRpxeM5aycNnn0yQ:bnfp4nl)*

**Comment by spencerkimball** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ui/src/containers/nodeGraphs.tsx, line 458 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15438#-Kim-4iiw62vca0EaIcM:-KioPXOkNVH7yRAxgZqn:bbmnrun) ([raw file](https://github.com/cockroachdb/cockroach/blob/06dd275104a603adcc913e35388eac42d57e7067/pkg/ui/src/containers/nodeGraphs.tsx#L458)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is this 2 separate graphs? Perhaps 1 graph with 2 separate lines would be more compact, though I have no idea how to do that properly.

Perhaps we should leave this off the admin UI for now until we see on Grafana whether it is useful. 
</blockquote></details>

Because these are latency graphs, there will be a line per node, making it necessary to have two.

If that's the way we decide to put things in the admin UI, why in The world does this page of graphs have rocksdb read amplification?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15438)*

**Comment by petermattis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ui/src/containers/nodeGraphs.tsx, line 458 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15438#-Kim-4iiw62vca0EaIcM:-KioZrPssOaad6uKg9gq:bcvcoku) ([raw file](https://github.com/cockroachdb/cockroach/blob/06dd275104a603adcc913e35388eac42d57e7067/pkg/ui/src/containers/nodeGraphs.tsx#L458)):*
> Because these are latency graphs, there will be a line per node, making it necessary to have two.

Ack.

> If that's the way we decide to put things in the admin UI, why in The world does this page of graphs have rocksdb read amplification?

We could likely remove the RocksDB read amplification graph. I see no need to put these graph in. I also see no particular harm. Really, we should have some debug page which allows graphing an arbitrary metric. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15438)*

**Comment by spencerkimball** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ui/src/containers/nodeGraphs.tsx, line 458 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15438#-Kim-4iiw62vca0EaIcM:-KioxfO5s6NMBJdrXVgf:b-ifhge3) ([raw file](https://github.com/cockroachdb/cockroach/blob/06dd275104a603adcc913e35388eac42d57e7067/pkg/ui/src/containers/nodeGraphs.tsx#L458)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

> Because these are latency graphs, there will be a line per node, making it necessary to have two.

Ack.

> If that's the way we decide to put things in the admin UI, why in The world does this page of graphs have rocksdb read amplification?

We could likely remove the RocksDB read amplification graph. I see no need to put these graph in. I also see no particular harm. Really, we should have some debug page which allows graphing an arbitrary metric. 
</blockquote></details>

I think we should have a "debug" version of the graph pages which if enabled, display a collection of debug-only graphs in addition to the ones for more public consumption.

I'm going to merge this with the graphs included right now and see about a debug option.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15438)*

**Pull request merged**
