### PR TITLE
opt: refactor custom match and replace functions

### PR DESCRIPTION
**Pull request by rytaft**
This PR contains 4 commits for the purpose of refactoring custom match and replace functions. The goal is to allow the `norm` and `xform` packages to share some custom match and replace functions in a new package called `xfunc`, without forcing `optgen` to know where the definition of a custom function is located.  In order to call a custom function from the `Factory`, the generated code from `optgen` simply calls `_f.funcs.CustomFunction(...)`, regardless of whether `CustomFunction` is located in `norm` or `xfunc`. Similarly, in order to call a custom function from the `explorer`, the generated code from `optgen` simply calls `_e.funcs.CustomFunction(...)`, regardless of whether `CustomFunction` is located in `xform` or `xfunc`.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm: Nice reorganization!

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26578#-:-LEj-DY0EFHts19YKMHM:bgvm4w7)*

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/norm/factory.go, line 225 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26578#-LEjDGUK5GWUUGDODq1F:-LEjDGUK5GWUUGDODq1G:b-l07h16) ([raw file](https://github.com/cockroachdb/cockroach/blob/eab3f9997d3fecc0854e32f720d40a05b4cefae3/pkg/sql/opt/norm/factory.go#L225)):*
> ```Go
> }
> 
> // ----------------------------------------------------------------------
> ```

Should the rest of these helper funcs go on `memo.CustomFuncs`? They seem like they'd be generally useful in both `norm.CustomFuncs` and `xform.CustomFuncs`. I don't think it's a problem that we don't actually call them from rules at this point.

I'm not hung up on this, as we could always do later, but I wanted to get thoughts on it.

---

*[pkg/sql/opt/xfunc/list_builder.go, line 38 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26578#-LEjBgjH0Z_Ppj2dV6ve:-LEjBgjH0Z_Ppj2dV6vf:b-e06eus) ([raw file](https://github.com/cockroachdb/cockroach/blob/eab3f9997d3fecc0854e32f720d40a05b4cefae3/pkg/sql/opt/xfunc/list_builder.go#L38)):*
> ```Go
> }
> 
> func MakeListBuilder(cf *CustomFuncs) ListBuilder {
> ```

NIT: needs comment.

---

*[pkg/sql/opt/xfunc/list_builder.go, line 54 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26578#-LEjBkzK84D3xDIz2HEW:-LEjBkzK84D3xDIz2HEX:b-e06eus) ([raw file](https://github.com/cockroachdb/cockroach/blob/eab3f9997d3fecc0854e32f720d40a05b4cefae3/pkg/sql/opt/xfunc/list_builder.go#L54)):*
> ```Go
> }
> 
> func (b *ListBuilder) Empty() bool {
> ```

NIT: needs comment.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26578#-:-LEjDlpa2jT_NJKVZvam:bnfp4nl)*

**Comment by rytaft** [comment]
*[pkg/sql/opt/norm/factory.go, line 225 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26578#-LEjDGUK5GWUUGDODq1F:-LEkUHf10Kxvs7f5KvBQ:b-tx6kbw) ([raw file](https://github.com/cockroachdb/cockroach/blob/eab3f9997d3fecc0854e32f720d40a05b4cefae3/pkg/sql/opt/norm/factory.go#L225)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Should the rest of these helper funcs go on `memo.CustomFuncs`? They seem like they'd be generally useful in both `norm.CustomFuncs` and `xform.CustomFuncs`. I don't think it's a problem that we don't actually call them from rules at this point.

I'm not hung up on this, as we could always do later, but I wanted to get thoughts on it.
</blockquote></details>

Do you mean `xfunc.CustomFuncs`? Or do you think we should add a `CustomFuncs` struct in the `memo` package as well?

I agree that it would probably be useful. Happy to do it now while we're doing all this refactoring anyway....

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26578)*

**Comment by rytaft** [comment]
Thanks!

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

---

*[pkg/sql/opt/xfunc/list_builder.go, line 38 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26578#-LEjBgjH0Z_Ppj2dV6ve:-LEkgoHn6AkLU50okogN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eab3f9997d3fecc0854e32f720d40a05b4cefae3/pkg/sql/opt/xfunc/list_builder.go#L38)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: needs comment.
</blockquote></details>

Done.

---

*[pkg/sql/opt/xfunc/list_builder.go, line 54 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26578#-LEjBkzK84D3xDIz2HEW:-LEkgkqf5SIRp6ZBHLtb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eab3f9997d3fecc0854e32f720d40a05b4cefae3/pkg/sql/opt/xfunc/list_builder.go#L54)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: needs comment.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26578#-:-LEkhIHg6xe1X0TxzN3M:b-ucfknh)*

**Comment by rytaft** [comment]
Added another commit to move some of the `Factory` helper functions to `xfunc` -- PTAL.

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

---

*[pkg/sql/opt/norm/factory.go, line 225 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26578#-LEjDGUK5GWUUGDODq1F:-LElQnnl7SDA9LlFoC6W:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eab3f9997d3fecc0854e32f720d40a05b4cefae3/pkg/sql/opt/norm/factory.go#L225)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Yeah, sorry, I meant `xfunc.CustomFuncs`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26578#-:-LElQpXJAcxeYH3suWeU:b-95for4)*

**Comment by andy-kimball** [comment]
Looks good, thanks for getting this done.

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26578#-:-LEq4c7rDqW8a06gGbQb:bslnpiq)*

**Comment by rytaft** [comment]
bors r+

---







*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26578#-:-LEq6TqeAQU_wLTbwmVw:b-ydi9ay)*

**Pull request merged**
