### PR TITLE
sql: improve expression index formatting

### PR DESCRIPTION
**Pull request by mgartner**
#### sql: follow Postgres convention for naming anonymous expression indexes

Anonymous expression indexes are now named using the same convention
that Postgres uses: For example:

    CREATE INDEX ON t ((a + b))
    => t_expr_idx

    CREATE INDEX ON t ((a + b), lower(c))
    => t_expr_expr1_idx

    CREATE INDEX ON t ((a + 10), b, lower(c))
    => t_expr_b_expr1_idx

There is no release note because expression-based indexes are not
enabled by default. They require the
experimental_enable_expression_indexes session setting until they are
fully supported.

Release note: None

#### sql: format expression index elements as expressions

Expressions in expression indexes are now formatted in the output of
`SHOW CREATE TABLE` and `pg_catalog` as expressions rather than as
the inaccessible computed column names that represent the expressions
internally.

There is no release note because expression-based indexes are not
enabled by default. They will be enabled when they are fully supported.

Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 8 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67042#-:-MdPjG44Cz7c8OBeA0q9:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/catalog/catformat/index.go, line 105 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67042#-MdPiwaG8dytqS0P3Y4A:-MdPiwaG8dytqS0P3Y4B:b-do48lv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e98bf7e710d00e026f13c3f2505eccf017ea2938/pkg/sql/catalog/catformat/index.go#L105)):*
> ```Go
> 	if index.IsPartial() {
> 		f.WriteString(" WHERE ")
> 		pred, err := schemaexpr.FormatExprForDisplay(ctx, table, index.Predicate, semaCtx, tree.FmtParsable)
> ```

nit: wrap the long line
___
*[pkg/sql/catalog/catformat/index.go, line 137 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67042#-MdPiqugEBxEiGRkrdOR:-MdPiqugEBxEiGRkrdOS:b-8wuvk4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e98bf7e710d00e026f13c3f2505eccf017ea2938/pkg/sql/catalog/catformat/index.go#L137)):*
> ```
> expr, err := schemaexpr.FormatExprForExpressionIndexDisplay(ctx, table, col.GetComputeExpr(), semaCtx, tree.FmtParsable)
> ```
nit: wrap the long line

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67042)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/catalog/catformat/index.go, line 105 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67042#-MdPiwaG8dytqS0P3Y4A:-MdQ-77u4HHFfFt2Cg12:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e98bf7e710d00e026f13c3f2505eccf017ea2938/pkg/sql/catalog/catformat/index.go#L105)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: wrap the long line
</blockquote></details>

Done.
___
*[pkg/sql/catalog/catformat/index.go, line 137 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67042#-MdPiqugEBxEiGRkrdOR:-MdQ-BIj96jgouSViHlE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e98bf7e710d00e026f13c3f2505eccf017ea2938/pkg/sql/catalog/catformat/index.go#L137)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> expr, err := schemaexpr.FormatExprForExpressionIndexDisplay(ctx, table, col.GetComputeExpr(), semaCtx, tree.FmtParsable)
> ```
nit: wrap the long line
</blockquote></details>

Done.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> Reviewed 6 of 9 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67042#-:-MdQIKPW2Uxz3FAcUPlA:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[pkg/sql/pg_catalog.go, line 1602 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67042#-MdQIPis4-EGlgG6uqs2:-MdQIPis4-EGlgG6uqs3:b84hvys) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b08dc8a258361be84bd536ce8de4fa85a6364ae/pkg/sql/pg_catalog.go#L1602)):*
> ```Go
> 			return "", err
> 		}
> 		if col.IsInaccessible() && col.IsComputed() {
> ```

`IsExpressionIndexColumn()`
___
*[pkg/sql/catalog/catformat/index.go, line 138 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67042#-MdQIxX3EZViuv9wzYN3:-MdQIxX3EZViuv9wzYN4:b84hvys) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b08dc8a258361be84bd536ce8de4fa85a6364ae/pkg/sql/catalog/catformat/index.go#L138)):*
> ```Go
> 			f.WriteString(", ")
> 		}
> 		if col.IsInaccessible() && col.IsComputed() {
> ```

`IsExpressionIndexColumn()`
___
*[pkg/sql/catalog/tabledesc/structured.go, line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67042#-MdQHNF4Em_8d-fToC63:-MdQHNF4Em_8d-fToC64:bvrzvbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/f03f97abe1905bccc27def742a1e8b821e3623d8/pkg/sql/catalog/tabledesc/structured.go#L168)):*
> ```Go
> 	segments = append(segments, tableDesc.Name)
> 
> 	// Add the key column segments. For inaccessible columns, use "expr" as the
> ```

Wondering about conflating columns for expression indexes with inaccessible columns.. (maybe there will be other usecases for inaccessible columns?)  I think I'd at least add a helper function `IsExpressionIndexColumn` (or something), even if it just does `IsInaccessible()` for now - it would at least make the intention clear and it would be easier to change later.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67042)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[pkg/sql/pg_catalog.go, line 1602 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67042#-MdQIPis4-EGlgG6uqs2:-MdTs5V3BhxwQ5TvIFaT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b08dc8a258361be84bd536ce8de4fa85a6364ae/pkg/sql/pg_catalog.go#L1602)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`IsExpressionIndexColumn()`
</blockquote></details>

Done.
___
*[pkg/sql/catalog/catformat/index.go, line 138 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67042#-MdQIxX3EZViuv9wzYN3:-MdTrub27PNIkSjJbmai:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b08dc8a258361be84bd536ce8de4fa85a6364ae/pkg/sql/catalog/catformat/index.go#L138)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`IsExpressionIndexColumn()`
</blockquote></details>

Done.
___
*[pkg/sql/catalog/tabledesc/structured.go, line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67042#-MdQHNF4Em_8d-fToC63:-MdTrwHJ1iTf22hz-wuU:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f03f97abe1905bccc27def742a1e8b821e3623d8/pkg/sql/catalog/tabledesc/structured.go#L168)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Wondering about conflating columns for expression indexes with inaccessible columns.. (maybe there will be other usecases for inaccessible columns?)  I think I'd at least add a helper function `IsExpressionIndexColumn` (or something), even if it just does `IsInaccessible()` for now - it would at least make the intention clear and it would be easier to change later.
</blockquote></details>

Good idea. Done.

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
