### PR TITLE
status: add locality information, additional lease info, to Ranges endpoint

### PR DESCRIPTION
**Pull request by abarganier**
This PR updates the `Ranges` response and associated UI to
display locality, `is_leaseholder`, and `lease_valid` information.

All these pieces of metadata are easily accessible within the Replica
or the metrics that are generated as part of the process of serving a
`Ranges` request. Since adding this information costs us very
little, and provides valuable info in the context of debugging,
this commit adds both fields to the `RangeInfo` proto included
in the `RangesResponse`.

The commit also surfaces this information in the problem ranges
/ranges UI within DB console.

Looking forwward, we can also provide this information in the
response for the upcoming `TenantRanges` endpoint, which acts as
a wrapper over the existing `Ranges` endpoint.

Release note (ui change); display locality information in problem
ranges and range status. Also display is_leaseholder and lease_valid
information in problem ranges and range status pages.

Release justification: Low risk, high benefit changes to existing functionality

### CODE REVIEW

**Review by dhartunian — APPROVED** [review]
:lgtm: just a tiny comment nit. 

> Reviewed 4 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76892#-:-Mwc0S4AElUZolE5CkYb:b-5f56qa)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier, @knz, and @rimadeodhar)

___
*[pkg/server/serverpb/status.proto, line 464 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76892#-Mwbq7m68OkR1pw7SKNa:-Mwbq7m68OkR1pw7SKNb:bdvpkni) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ffdf93ad316e1246f8809a2f0878c3b631521f8/pkg/server/serverpb/status.proto#L464)):*
> ```protobuf
>   // only_leaseholder_replicas causes the endpoint to only return
>   // metadata about leaseholder replicas on the provided node_id's
>   // KV stores. Ranges without a valid lease will also be filtered.
> ```

nit: filtered...out?

**Review by rimadeodhar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76892)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier and @knz)

___
*[pkg/server/status.go, line 2101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76892#-MwcAjViChi2PZQ7vruM:-MwcAjVjBvuXzFP9uuJW:bj53xj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ffdf93ad316e1246f8809a2f0878c3b631521f8/pkg/server/status.go#L2101)):*
> ```Go
> 			}
> 			metrics := rep.Metrics(ctx, now, isLiveMap, clusterNodes)
> 			if req.OnlyLeaseholderReplicas && (!metrics.Leaseholder || !metrics.LeaseValid) {
> ```

Nit: This conditional could be put into a helper function of some sort.

**Review by abarganier — COMMENTED** [review]
Thanks for the feedback all. As discussed in https://github.com/cockroachdb/cockroach/pull/76743 we are now going to show all replicas to the tenant and use locality information to discern between replicas.

I therefore removed the commit that introduced the `only_leaseholder_replicas` flag and replaced it with one that provides some additional bits of lease metadata for each replica in `Ranges` (`is_leaseholder` and `lease_valid`). This also gets surfaced in the UI.

PTAL, thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76892#-:-Mwm42ZnBruC5iU3-g2v:b-p1k8vo)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian, @knz, and @rimadeodhar)

___
*[pkg/server/status.go, line 2101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76892#-MwcAjViChi2PZQ7vruM:-Mwm3sJ18sv8ncrmQ5XB:b-9m2uer) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ffdf93ad316e1246f8809a2f0878c3b631521f8/pkg/server/status.go#L2101)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Nit: This conditional could be put into a helper function of some sort.
</blockquote></details>

This functionality has been removed, so no longer relevant.
___
*[pkg/server/serverpb/status.proto, line 464 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76892#-Mwbq7m68OkR1pw7SKNa:-Mwm3zyb-hL5riDt4wxz:b-9m2uer) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ffdf93ad316e1246f8809a2f0878c3b631521f8/pkg/server/serverpb/status.proto#L464)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: filtered...out?
</blockquote></details>

This functionality has been removed, so no longer relevant.

**Review by rimadeodhar — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76892#-:-MwmU0_U2uUjdZtDumHF:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian and @knz)

**Comment by knz** [comment]
Thanks for this work.
Can you also take care of teaching the members of the KV obs team how this works? They are working in this area too but still lack the experience.

**Pull request merged**
