### PR TITLE
kvserver: add end-to-end store liveness tests

### LINKED ISSUE #125066: storeliveness: end-to-end testing
Add end-to-end tests for the store liveness fabric, exercising some critical scenarios: node crashes and restarts, lost and reordered messages, replica movement, clock skew/drift. Verify the interface behavior of `Support{For|From}`.

### PR DESCRIPTION
**Pull request by miraradeva**
This commit adds store liveness tests with a real multi-store cluster.

In particular, the new tests exercise the happy path of all-to-all
support between stores, as well as the main failure modes: node crash,
disk stall and network partition.

Fixes: [#125066](https://github.com/cockroachdb/cockroach/issues/125066)

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, 7 of 7 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134529)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @miraradeva)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134529#-OBWU5Jr29U9k46j_TQQ:-OBWU5Jr29U9k46j_TQR:b9sljgb):*
nit: the convention in most of the code base is `testutils.go`.
___
*[`pkg/kv/kvserver/storeliveness/config.go` line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134529#-OBWW80M-eueVuVvTb97:-OBWW80M-eueVuVvTb98:b-8xjlkn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9ba7d75fbc866f640ccbf2c4a3e06a6b7a5a5df/pkg/kv/kvserver/storeliveness/config.go#L61)):*
> ```Go
> // TestingKnobs is a wrapper around TransportKnobs and SupportManagerKnobs.
> type TestingKnobs struct {
> 	*TransportKnobs
> ```

nit: embedding a nullable pointer is a somewhat error-prone endeavor, as users need to know to nil check the struct before accessing inner fields. Consider just embedding these by value.
___
*[`pkg/kv/kvserver/storeliveness/multi_store_test.go` line 202 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/134529#-OBW_rIk7djFyO_sATjv:-OBW_rIk7djFyO_sATjw:bau296h) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0df98022eaa9b4d04f5aaf24b2762c9ed65128c/pkg/kv/kvserver/storeliveness/multi_store_test.go#L202)):*
> ```Go
> 		// support from the remote node.
> 		if remoteID.NodeID == stoppedNode && localID.NodeID != stoppedNode {
> 			checkSupportFrom(t, localSM, remoteID, false /* supportExpected */)
> ```

We're missing assertions for `checkSupportFor` when the remote store is stopped, and `checkSupportFrom` when the local store is stopped. Are those useful to make? For instance, is it useful to assert that the dead node does not withdraw support from it?

Or are we not missing them because `checkSupport` is called in both directions? It might be easier to think through the cases that we are and aren't handling if we stop passing `remoteSM` to this visitor and only ever make assertions with `localSM`. I don't feel strongly though, if you're finding this easier to reason about.
___
*[`pkg/kv/kvserver/storeliveness/multi_store_test.go` line 206 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/134529#-OBWaVIzEJ9bOL6JNeq_:-OBWaVIzEJ9bOL6JNeqa:b-z5wwuq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0df98022eaa9b4d04f5aaf24b2762c9ed65128c/pkg/kv/kvserver/storeliveness/multi_store_test.go#L206)):*
> ```Go
> 		// If the local store is the stopped one, the remote store should withdraw
> 		// support for the local node.
> 		if localID.NodeID == stoppedNode && remoteID.NodeID != stoppedNode {
> ```

Should we test anything about the `localID.NodeID == stoppedNode && localID == remoteID` case?
___
*[`pkg/kv/kvserver/storeliveness/multi_store_test.go` line 218 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/134529#-OBWbrA_9cprpWurYEWZ:-OBWbrA_9cprpWurYEW_:b-bs7f22) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0df98022eaa9b4d04f5aaf24b2762c9ed65128c/pkg/kv/kvserver/storeliveness/multi_store_test.go#L218)):*
> ```Go
> 
> 	// Restart node 1 and ensure all-to-all support again.
> 	require.NoError(t, tc.RestartServer(serverIdxToStop))
> ```

This reminds me: do we want to add a test somewhere that gives us confidence that the withdrawal grace period on startup is sufficient so that a restarting store continues to support other stores at the same epoch it was supporting before it restarted?
___
*[`pkg/kv/kvserver/storeliveness/multi_store_test.go` line 281 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/134529#-OBWbM0S7hQQuENVXUCT:-OBWbM0S7hQQuENVXUCU:b-7t4wmj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0df98022eaa9b4d04f5aaf24b2762c9ed65128c/pkg/kv/kvserver/storeliveness/multi_store_test.go#L281)):*
> ```Go
> // TestStoreLivenessPartialPartition tests that a partially-partitioned store
> // loses all support from partitioned peers but keeps support from others.
> func TestStoreLivenessPartialPartition(t *testing.T) {
> ```

These are nice tests!
___
*[`pkg/kv/kvserver/storeliveness/multi_store_test.go` line 294 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/134529#-OBWbQK0D7PNwRdTh56N:-OBWbQK0D7PNwRdTh56O:b-uczsro) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0df98022eaa9b4d04f5aaf24b2762c9ed65128c/pkg/kv/kvserver/storeliveness/multi_store_test.go#L294)):*
> ```Go
> 	// right. The test will set up either a symmetric or an asymmetric partition
> 	// between them.
> 	// Connected: 					 left <----> right
> ```

nit: odd indentation here.
___
*[`pkg/kv/kvserver/storeliveness/support_manager.go` line 72 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134529#-OBWXg66Ettnjd_oohwV:-OBWXg66Ettnjd_oohwW:b872f9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9ba7d75fbc866f640ccbf2c4a3e06a6b7a5a5df/pkg/kv/kvserver/storeliveness/support_manager.go#L72)):*
> ```Go
> 	knobs *SupportManagerKnobs,
> ) *SupportManager {
> 	if knobs != nil && knobs.TestEngine != nil && knobs.TestEngine.storeID == storeID {
> ```

In what case would the store ID be different? In a multi-store setup? Should we just panic in that case, or is it useful for some tests to allow this knob to silently be ignored?
___
*[`pkg/kv/kvserver/store.go` line 2215 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134529#-OBWVkBIEQv5Ktf_VwH7:-OBWVkBIEQv5Ktf_VwH8:b59g8na) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9ba7d75fbc866f640ccbf2c4a3e06a6b7a5a5df/pkg/kv/kvserver/store.go#L2215)):*
> ```Go
> 	supportGracePeriod := s.cfg.RPCContext.StoreLivenessWithdrawalGracePeriod()
> 	options := storeliveness.NewOptions(livenessInterval, heartbeatInterval, supportGracePeriod)
> 	knobs := &storeliveness.SupportManagerKnobs{}
> ```

Should we just use a nil pointer by default? `var knobs *storeliveness.SupportManagerKnobs`

**Review by miraradeva — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134529)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134529#-OBWU5Jr29U9k46j_TQQ:-OBaeobzAxdRPSXQAkoc:b-896fix):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: the convention in most of the code base is `testutils.go`.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/store.go` line 2215 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134529#-OBWVkBIEQv5Ktf_VwH7:-OBaezzlElg0KWcNaxBN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9ba7d75fbc866f640ccbf2c4a3e06a6b7a5a5df/pkg/kv/kvserver/store.go#L2215)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we just use a nil pointer by default? `var knobs *storeliveness.SupportManagerKnobs`
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/storeliveness/config.go` line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134529#-OBWW80M-eueVuVvTb97:-OBafOngETGJ9_4cwJJZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9ba7d75fbc866f640ccbf2c4a3e06a6b7a5a5df/pkg/kv/kvserver/storeliveness/config.go#L61)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: embedding a nullable pointer is a somewhat error-prone endeavor, as users need to know to nil check the struct before accessing inner fields. Consider just embedding these by value.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/storeliveness/support_manager.go` line 72 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134529#-OBWXg66Ettnjd_oohwV:-OBafSGI5ST92Zj4yvyN:b-xhsoi2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9ba7d75fbc866f640ccbf2c4a3e06a6b7a5a5df/pkg/kv/kvserver/storeliveness/support_manager.go#L72)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

In what case would the store ID be different? In a multi-store setup? Should we just panic in that case, or is it useful for some tests to allow this knob to silently be ignored?
</blockquote></details>

Yeah, in the multi-store case it's convenient to pass one test engine to the entire node, with the storeID indicating which store the engine is for. Passing store-specific knobs is not very easy because `ServerArgs` takes a single `TestingKnobs` (which includes the store knobs).
___
*[`pkg/kv/kvserver/storeliveness/multi_store_test.go` line 202 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/134529#-OBW_rIk7djFyO_sATjv:-OBagvLX6UmYwcMqITcK:bi3v98x) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0df98022eaa9b4d04f5aaf24b2762c9ed65128c/pkg/kv/kvserver/storeliveness/multi_store_test.go#L202)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We're missing assertions for `checkSupportFor` when the remote store is stopped, and `checkSupportFrom` when the local store is stopped. Are those useful to make? For instance, is it useful to assert that the dead node does not withdraw support from it?

Or are we not missing them because `checkSupport` is called in both directions? It might be easier to think through the cases that we are and aren't handling if we stop passing `remoteSM` to this visitor and only ever make assertions with `localSM`. I don't feel strongly though, if you're finding this easier to reason about.
</blockquote></details>

I went back and forth on this a couple of times. 

If there is no stopped node, for a fixed local store, we can't do `checkSupportFrom(t, localSM, remoteID, true)` and then immediately `checkSupportFor(t, localSM, remoteID, true)` because the remote store hasn't started sending heartbeats to the local store. Hence, the need for both `localSM` and `remoteSM` to check support that the _local store_ is requesting and providing. When we loop around to where the remote store is the local store, we will make the same assertions for it.

But here all stores are already heartbeating (after `ensureAllToAllSupport`). So I think it's possible to simplify the logic and talk only about the local store's support manager.
___
*[`pkg/kv/kvserver/storeliveness/multi_store_test.go` line 206 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/134529#-OBWaVIzEJ9bOL6JNeq_:-OBajhMM7gu0t2W9lSMf:b-7pomz1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0df98022eaa9b4d04f5aaf24b2762c9ed65128c/pkg/kv/kvserver/storeliveness/multi_store_test.go#L206)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we test anything about the `localID.NodeID == stoppedNode && localID == remoteID` case?
</blockquote></details>

The main issue I hit here is that the support manager of a store on the stopped node is sort of frozen in time and it's hard to make any assertions based on it.
___
*[`pkg/kv/kvserver/storeliveness/multi_store_test.go` line 218 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/134529#-OBWbrA_9cprpWurYEWZ:-OBaxaZ1-QxL92-7-iQX:bdytkq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0df98022eaa9b4d04f5aaf24b2762c9ed65128c/pkg/kv/kvserver/storeliveness/multi_store_test.go#L218)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This reminds me: do we want to add a test somewhere that gives us confidence that the withdrawal grace period on startup is sufficient so that a restarting store continues to support other stores at the same epoch it was supporting before it restarted?
</blockquote></details>

There are a few basic cases in the `restart` data driven test but I'm happy to add something more end-to-end if you think we should test it better.
___
*[`pkg/kv/kvserver/storeliveness/multi_store_test.go` line 294 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/134529#-OBWbQK0D7PNwRdTh56N:-OBak3XP7BeqTmEOXNGX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0df98022eaa9b4d04f5aaf24b2762c9ed65128c/pkg/kv/kvserver/storeliveness/multi_store_test.go#L294)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: odd indentation here.
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r4, 7 of 7 files at r5, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134529#-:-OBgvFc44PGmD2mIz8Nn:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by miraradeva** [comment]
TFTR!

bors r=nvanbenschoten

**Pull request merged**
