### PR TITLE
engine: inline tempdir creation at MakeRocksDBSstFileReader callsites

### PR DESCRIPTION
**Pull request by dt**

### CODE REVIEW

**Comment by tamird** [comment]
2nd commit message doesn't make sense. is that commit fixing that? use the imperative as you did in the first commit.

---

Reviewed 5 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/storage/engine/rocksdb.go, line 1704 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14666#-Kh2YnCp2Mx3FpcXuyfx:-Kh2YnCp2Mx3FpcXuyfy:b-yyqp4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/09e520d3225e06432441975761baa7065acc30a3/pkg/storage/engine/rocksdb.go#L1704)):*
> ```Go
> 		roachpb.Attributes{}, dir, cache, 512<<20, DefaultMaxOpenFiles)
> 	if err != nil {
> 		// Usually the tempdir is cleaned up by Close below, but we need to do it
> ```

Where is the Close? it's not in this function.

---

*[pkg/storage/engine/rocksdb.go, line 1706 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14666#-Kh2YfUOeANNU3Bulo3Y:-Kh2YfUOeANNU3Bulo3Z:btv3y7r) ([raw file](https://github.com/cockroachdb/cockroach/blob/09e520d3225e06432441975761baa7065acc30a3/pkg/storage/engine/rocksdb.go#L1706)):*
> ```Go
> 		// Usually the tempdir is cleaned up by Close below, but we need to do it
> 		// ourselves in this err case.
> 		if rmErr := os.RemoveAll(dir); err != nil {
> ```

are you nil checking the wrong error? please use `err` instead of `rmErr` - `rmErr` buys you nothing here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14666#-:-Kh2YReJzl0NHDYUSF5R:b-4zla49)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/storage/engine/rocksdb.go, line 1704 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14666#-Kh2YnCp2Mx3FpcXuyfx:-Kh2ZmtR0U6C-ZzTvpfE:b-4vi7oo) ([raw file](https://github.com/cockroachdb/cockroach/blob/09e520d3225e06432441975761baa7065acc30a3/pkg/storage/engine/rocksdb.go#L1704)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Where is the Close? it's not in this function.
</blockquote></details>

RocksDBSstFileReader.Close.

---

*[pkg/storage/engine/rocksdb.go, line 1706 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14666#-Kh2YfUOeANNU3Bulo3Y:-Kh2_MJ-4e0uVIGQxhro:b46fsd3) ([raw file](https://github.com/cockroachdb/cockroach/blob/09e520d3225e06432441975761baa7065acc30a3/pkg/storage/engine/rocksdb.go#L1706)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

are you nil checking the wrong error? please use `err` instead of `rmErr` - `rmErr` buys you nothing here.
</blockquote></details>

Heh, in my fear of shadowing mistakes, I walked right into it.
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14666)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/engine/rocksdb.go, line 1704 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14666#-Kh2YnCp2Mx3FpcXuyfx:-Kh2b6XIla10o5KYtHwU:beb4ne1) ([raw file](https://github.com/cockroachdb/cockroach/blob/09e520d3225e06432441975761baa7065acc30a3/pkg/storage/engine/rocksdb.go#L1704)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

RocksDBSstFileReader.Close.
</blockquote></details>

Help me understand - where does this leak happen? In other words, where is `dir` being created without an accompanying deferred cleanup?

By the way, this is the kind of detail that would be useful to include in the commit message, especially when the fix occurs at significant distance from the problem.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14666)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/storage/engine/rocksdb.go, line 1704 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14666#-Kh2YnCp2Mx3FpcXuyfx:-Kh2bYN3nqrEcBoTASyy:bx4pjtr) ([raw file](https://github.com/cockroachdb/cockroach/blob/09e520d3225e06432441975761baa7065acc30a3/pkg/storage/engine/rocksdb.go#L1704)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Help me understand - where does this leak happen? In other words, where is `dir` being created without an accompanying deferred cleanup?

By the way, this is the kind of detail that would be useful to include in the commit message, especially when the fix occurs at significant distance from the problem.
</blockquote></details>

The leak happens right here -- we just created `dir` right above this, but when we return an error (on the next line) no one will ever call Close to clean it up.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14666)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/engine/rocksdb.go, line 1704 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14666#-Kh2YnCp2Mx3FpcXuyfx:-Kh2nt-0zLfhAYgd3i8x:b-r2ul1d) ([raw file](https://github.com/cockroachdb/cockroach/blob/09e520d3225e06432441975761baa7065acc30a3/pkg/storage/engine/rocksdb.go#L1704)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

The leak happens right here -- we just created `dir` right above this, but when we return an error (on the next line) no one will ever call Close to clean it up.
</blockquote></details>

Ah, I see. This function has 4 callers - can you move the directory creation to the caller, so that cleanup can be deferred in the standard manner?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14666)*

**Comment by dt** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/engine/rocksdb.go, line 1704 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14666#-Kh2YnCp2Mx3FpcXuyfx:-Kh2vSHmnziiOIXUiS0U:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/09e520d3225e06432441975761baa7065acc30a3/pkg/storage/engine/rocksdb.go#L1704)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Ah, I see. This function has 4 callers - can you move the directory creation to the caller, so that cleanup can be deferred in the standard manner?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14666)*

**Comment by tamird** [comment]
Reviewed 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/storageccl/export_test.go, line 64 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14666#-Kh3-165wuZATp-vU-yp:-Kh3-166vfunzBs5HlP5:bhoefir) ([raw file](https://github.com/cockroachdb/cockroach/blob/053ba693d3e562acaa2f308767b1ea5fb8429172/pkg/ccl/storageccl/export_test.go#L64)):*
> ```Go
> 			paths = append(paths, file.Path)
> 
> 			readerTempDir, err := ioutil.TempDir(dir, "RocksDBSstFileReader")
> ```

consider giving this a meaningful name from the caller, perhaps something mentioning TestExport. You can use t.Name(), too.

---

*[pkg/ccl/storageccl/import.go, line 120 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14666#-Kh3-BVRGLU7_kJJQwXX:-Kh3-BVRGLU7_kJJQwXY:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/053ba693d3e562acaa2f308767b1ea5fb8429172/pkg/ccl/storageccl/import.go#L120)):*
> ```Go
> 		}
> 
> 		readerTempDir, err := ioutil.TempDir(tempPrefix, "RocksDBSstFileReader")
> ```

ditto

---

*[pkg/ccl/storageccl/import_test.go, line 49 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14666#-Kh3-EIvu-UtmPsCLSW-:-Kh3-EIvu-UtmPsCLSW0:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/053ba693d3e562acaa2f308767b1ea5fb8429172/pkg/ccl/storageccl/import_test.go#L49)):*
> ```Go
> 
> 	for _, path := range paths {
> 		readerTempDir, err := ioutil.TempDir(dir, "RocksDBSstFileReader")
> ```

ditto

---

*[pkg/storage/engine/rocksdb_test.go, line 518 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14666#-Kh3-ULytyJ94yWgbh_8:-Kh3-ULytyJ94yWgbh_9:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/053ba693d3e562acaa2f308767b1ea5fb8429172/pkg/storage/engine/rocksdb_test.go#L518)):*
> ```Go
> 
> 	b.ResetTimer()
> 	readerTempDir, err := ioutil.TempDir(dir, "RocksDBSstFileReader")
> ```

ditto

---

*[pkg/storage/engine/rocksdb_test.go, line 535 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14666#-Kh3-X5Ih6XPFQBAHuRO:-Kh3-X5Ih6XPFQBAHuRP:bmro5bb) ([raw file](https://github.com/cockroachdb/cockroach/blob/053ba693d3e562acaa2f308767b1ea5fb8429172/pkg/storage/engine/rocksdb_test.go#L535)):*
> ```Go
> 		b.Fatal(err)
> 	}
> 	defer sst.Close()
> ```

isn't this in the wrong place again?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14666)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/storageccl/export_test.go, line 64 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14666#-Kh3-165wuZATp-vU-yp:-Kh3-rFXFriqYcV4uXyV:b21tjmd) ([raw file](https://github.com/cockroachdb/cockroach/blob/053ba693d3e562acaa2f308767b1ea5fb8429172/pkg/ccl/storageccl/export_test.go#L64)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

consider giving this a meaningful name from the caller, perhaps something mentioning TestExport. You can use t.Name(), too.
</blockquote></details>

It is already using the test-specific dir prefix, which has t.Name in it.

---

*[pkg/ccl/storageccl/import.go, line 120 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14666#-Kh3-BVRGLU7_kJJQwXX:-Kh30L61kZfBG7m__Y6o:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/053ba693d3e562acaa2f308767b1ea5fb8429172/pkg/ccl/storageccl/import.go#L120)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

---

*[pkg/ccl/storageccl/import_test.go, line 49 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14666#-Kh3-EIvu-UtmPsCLSW-:-Kh30299FbylEpU25S7u:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/053ba693d3e562acaa2f308767b1ea5fb8429172/pkg/ccl/storageccl/import_test.go#L49)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto

---

*[pkg/storage/engine/rocksdb_test.go, line 518 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14666#-Kh3-ULytyJ94yWgbh_8:-Kh303CvxbfM0uFAtTaX:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/053ba693d3e562acaa2f308767b1ea5fb8429172/pkg/storage/engine/rocksdb_test.go#L518)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto

---

*[pkg/storage/engine/rocksdb_test.go, line 535 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14666#-Kh3-X5Ih6XPFQBAHuRO:-Kh303gTDbQPy7Gs700e:b-r946wh) ([raw file](https://github.com/cockroachdb/cockroach/blob/053ba693d3e562acaa2f308767b1ea5fb8429172/pkg/storage/engine/rocksdb_test.go#L535)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

isn't this in the wrong place again?
</blockquote></details>

it is not changed by this commit

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14666)*

**Comment by tamird** [comment]
:lgtm:

---

Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/storage/engine/rocksdb_test.go, line 535 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14666#-Kh3-X5Ih6XPFQBAHuRO:-Kh30lSKlTXE7vi9WozB:b-15cjf7) ([raw file](https://github.com/cockroachdb/cockroach/blob/053ba693d3e562acaa2f308767b1ea5fb8429172/pkg/storage/engine/rocksdb_test.go#L535)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

it is not changed by this commit
</blockquote></details>

Right, but it was (rightly) changed in an earlier version of this commit - why revert it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14666#-:-Kh30j1qLcj2gXOv3gEH:bnfp4nl)*

**Comment by dt** [comment]
Review status: 4 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/storage/engine/rocksdb_test.go, line 535 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14666#-Kh3-X5Ih6XPFQBAHuRO:-Kh31N_J73MTRSZL5s-H:b-6rc0mp) ([raw file](https://github.com/cockroachdb/cockroach/blob/053ba693d3e562acaa2f308767b1ea5fb8429172/pkg/storage/engine/rocksdb_test.go#L535)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Right, but it was (rightly) changed in an earlier version of this commit - why revert it?
</blockquote></details>

it's unrelated to this change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14666)*

**Comment by tamird** [comment]
But isn't it worth fixing? Add a commit if you feel strongly about
change-hygiene.

**Comment by dt** [comment]
Done.

---

Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14666#-:-Kh33xuXH-ZgPfEguanB:b-896fix)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14666)*

**Pull request merged**
