### PR TITLE
logictest: disable workmem randomization with the --rewrite flag

### PR DESCRIPTION
**Pull request by mgartner**
This commit makes a minor ergonomic improvement to logic tests that
randomization of the `sql.distsql.temp_storage.workmem` setting is
disabled if the `--rewrite` flag is present. This reduces painfully slow
tests during development when the `--rewrite` flag is commonly used,
without having to pass the `--default-workmem` flag.

Epic: None

Release note: None

### CODE REVIEW

**Review by chengxiong-ruan — APPROVED** [review]
very nice!

**Comment by mgartner** [comment]
Hmm... I'm not sure this works with `./dev test`...

**Comment by rickystewart** [comment]
@mgartner Did you `dev build dev` to build the latest version of the code? The script doesn't pick up your changes automatically. You can also bump the version number in the top-level `dev` script to force everyone to rebuild it to pick up your changes.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Great idea!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97848#-:-NPTEXpN2JdvcoRINn6t:bodf5c8)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by mgartner** [comment]
> Did you dev build dev to build the latest version of the code?

Thanks for the tip. The problem was that I implemented this originally in `pkg/cmd/dev/testlogic.go`, but those code paths are executed during `./dev test ...`.

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
