### PR TITLE
sql: properly populate is_superuser

### PR DESCRIPTION
**Pull request by otan**
Release justification: low risk high benefit change

Last commit only. First two commits in #69224

See individual commits for details.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69355)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/ccl/serverccl/role_authentication_test.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69355#-MhxrQjK3Dn8W6D1cKu5:-MhxrQjK3Dn8W6D1cKu6:b-60dd3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb78c4068e82536f1b87fd577db6e75a2dfa7978/pkg/ccl/serverccl/role_authentication_test.go#L104)):*
> ```Go
> 		{"druidia", "12345", false, true, ""},
> 		{"druidia", "hunter2", false, false, "crypto/bcrypt"},
> 		{"root", "", true, false, "crypto/bcrypt"},
> ```

looks like `root` is the only true case in these tests. can we add more tests for other admin roles having `is_superuser` true also?
___
*[pkg/sql/authorization.go, line 403 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69355#-MhyDXz3BZd3OKwisZ_z:-MhyDXz3BZd3OKwisZa-:b4tn76s) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb78c4068e82536f1b87fd577db6e75a2dfa7978/pkg/sql/authorization.go#L403)):*
> ```Go
> // we could save detailed memberships (as opposed to fully expanded) and reuse them
> // across users. We may then want to lookup more than just this user.
> func (p *planner) resolveMemberOfWithAdminOption(
> ```

this function wasn't really supposed to be used externally, since it does a KV lookup -- the idea was to always go through the RoleMembershipCache to avoid unexpected round trips
___
*[pkg/sql/user.go, line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69355#-MhyEgam7WblvuVtaZy2:-MhyEgam7WblvuVtaZy3:bfrqdgv) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb78c4068e82536f1b87fd577db6e75a2dfa7978/pkg/sql/user.go#L257)):*
> ```Go
> 	)
> 	if err != nil {
> 		return sessioninit.AuthInfo{}, err
> ```

could this all be done outside of `retrieveAuthInfo`, so that it doesn't end up in the session init cache? instead, is there a way we could do this in the `GetUserSessionInitInfo` function, and reuse the `execCfg.RoleMemberCache`? it would address the concerns i had about cache inconsistency, and the danger of exposing a non-cached `ResolveMemberOfWithAdminOption` function
___
*[pkg/sql/sessioninit/cache.go, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69355#-MhyBHphEIa3mNBFw-Bk:-MhyBHphEIa3mNBFw-Bl:buximc8) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb78c4068e82536f1b87fd577db6e75a2dfa7978/pkg/sql/sessioninit/cache.go#L63)):*
> ```Go
> 	UserExists bool
> 	// IsSuperuser is set to true for any admin users.
> 	IsSuperuser bool
> ```

hm i think there's a cache consistency issue here now

when `GRANT admin TO user` happens, the role membership cache is invalidated: https://github.com/cockroachdb/cockroach/blob/8f82389f3e939fb8366de1e4b626adcb1ecf3b8e/pkg/sql/grant_role.go#L206

however, IsSuperUser is now going to be cached in the SessionInitCache, and as per the `clearCacheIfStale` method below, it won't be cleared out even if the role memberships change.

you should be able to repro with:

```
- login as testuser
- SHOW is_superuser should be false
- disconnect
- login as root
- GRANT admin TO testuser
- disconnect
- login as testuser
- SHOW is_superuser should be true at this point, but i think it will show false.
```

this points to the fact that this sessioninit cache is undertested right now -- i wanted to write tests for it during stability period
___
*[pkg/sql/sqlutil/auth.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69355#-MhyE2NzD08e8wJ4wVvl:-MhyE2NzD08e8wJ4wVvm:bxdpsps) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb78c4068e82536f1b87fd577db6e75a2dfa7978/pkg/sql/sqlutil/auth.go#L23)):*
> ```Go
> // ResolveMemberOfWithAdminOption explores all the memberships of the user.
> // It returns a map of memberships, as well as whether that membership
> // is an admin role.
> ```

i think this deserves some more disclaimers around how it can cause unexpected latency, and if possible you should use the cached version (see `sql.MemberOfWithAdminOption`)

even better would be to make this function here use the `RoleMemberCache`. see if we can pull the `sql.planner.MemberOfWithAdminOption` function in here and refactor it so it doesn't use the planner directly.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69355)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[pkg/ccl/serverccl/role_authentication_test.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69355#-MhxrQjK3Dn8W6D1cKu5:-Mi-WC9Y6SS_1ZOVTL8O:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb78c4068e82536f1b87fd577db6e75a2dfa7978/pkg/ccl/serverccl/role_authentication_test.go#L104)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

looks like `root` is the only true case in these tests. can we add more tests for other admin roles having `is_superuser` true also?
</blockquote></details>

Done.
___
*[pkg/sql/user.go, line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69355#-MhyEgam7WblvuVtaZy2:-Mi-W5MfBeKFYgJgE81W:b409f6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb78c4068e82536f1b87fd577db6e75a2dfa7978/pkg/sql/user.go#L257)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could this all be done outside of `retrieveAuthInfo`, so that it doesn't end up in the session init cache? instead, is there a way we could do this in the `GetUserSessionInitInfo` function, and reuse the `execCfg.RoleMemberCache`? it would address the concerns i had about cache inconsistency, and the danger of exposing a non-cached `ResolveMemberOfWithAdminOption` function
</blockquote></details>

urgh, that's annoying. not sure where to get `p.Descriptors()` from which is what held me back.

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69355)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[pkg/sql/user.go, line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69355#-MhyEgam7WblvuVtaZy2:-Mi-o5a86A-Q4Mqsz6aZ:b83481p) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb78c4068e82536f1b87fd577db6e75a2dfa7978/pkg/sql/user.go#L257)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

urgh, that's annoying. not sure where to get `p.Descriptors()` from which is what held me back. 
</blockquote></details>

i think what we can do (not the prettiest...) is change the signature of `retrieveSessionInitInfoWithCache` (in pkg/sql/user.go) to

```
func retrieveSessionInitInfoWithCache(
	ctx context.Context,
	execCfg *ExecutorConfig,
	ie *InternalExecutor,
	username security.SQLUsername,
	databaseName string,
) (aInfo sessioninit.AuthInfo, settingsEntries []sessioninit.SettingsCacheEntry, isSuperuser bool, err error) {
```

and somewhere in the impl of that you can use `execCfg.CollectionFactory.Txn()` which will give you the `descs.Collection` you need.

IMO, the `func (p *planner) MemberOfWithAdminOption(` method should actually be a method on the `RoleMemberCache`. similar to how `SessionInitCache` has a `GetAuthInfo` method.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69355)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/authorization.go, line 403 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69355#-MhyDXz3BZd3OKwisZ_z:-Mi18hDI2dawkoCmqR9P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb78c4068e82536f1b87fd577db6e75a2dfa7978/pkg/sql/authorization.go#L403)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this function wasn't really supposed to be used externally, since it does a KV lookup -- the idea was to always go through the RoleMembershipCache to avoid unexpected round trips
</blockquote></details>

Done.
___
*[pkg/sql/user.go, line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69355#-MhyEgam7WblvuVtaZy2:-Mi18fMt81FAW8M59Tq5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb78c4068e82536f1b87fd577db6e75a2dfa7978/pkg/sql/user.go#L257)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think what we can do (not the prettiest...) is change the signature of `retrieveSessionInitInfoWithCache` (in pkg/sql/user.go) to

```
func retrieveSessionInitInfoWithCache(
	ctx context.Context,
	execCfg *ExecutorConfig,
	ie *InternalExecutor,
	username security.SQLUsername,
	databaseName string,
) (aInfo sessioninit.AuthInfo, settingsEntries []sessioninit.SettingsCacheEntry, isSuperuser bool, err error) {
```

and somewhere in the impl of that you can use `execCfg.CollectionFactory.Txn()` which will give you the `descs.Collection` you need.

IMO, the `func (p *planner) MemberOfWithAdminOption(` method should actually be a method on the `RoleMemberCache`. similar to how `SessionInitCache` has a `GetAuthInfo` method.
</blockquote></details>

Done.
___
*[pkg/sql/sessioninit/cache.go, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69355#-MhyBHphEIa3mNBFw-Bk:-Mi18fugB2TZHIJ7yckB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb78c4068e82536f1b87fd577db6e75a2dfa7978/pkg/sql/sessioninit/cache.go#L63)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm i think there's a cache consistency issue here now

when `GRANT admin TO user` happens, the role membership cache is invalidated: https://github.com/cockroachdb/cockroach/blob/8f82389f3e939fb8366de1e4b626adcb1ecf3b8e/pkg/sql/grant_role.go#L206

however, IsSuperUser is now going to be cached in the SessionInitCache, and as per the `clearCacheIfStale` method below, it won't be cleared out even if the role memberships change.

you should be able to repro with:

```
- login as testuser
- SHOW is_superuser should be false
- disconnect
- login as root
- GRANT admin TO testuser
- disconnect
- login as testuser
- SHOW is_superuser should be true at this point, but i think it will show false.
```

this points to the fact that this sessioninit cache is undertested right now -- i wanted to write tests for it during stability period
</blockquote></details>

Done.
___
*[pkg/sql/sqlutil/auth.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69355#-MhyE2NzD08e8wJ4wVvl:-Mi18gO-BKGcfe2MvWDn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb78c4068e82536f1b87fd577db6e75a2dfa7978/pkg/sql/sqlutil/auth.go#L23)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think this deserves some more disclaimers around how it can cause unexpected latency, and if possible you should use the cached version (see `sql.MemberOfWithAdminOption`)

even better would be to make this function here use the `RoleMemberCache`. see if we can pull the `sql.planner.MemberOfWithAdminOption` function in here and refactor it so it doesn't use the planner directly.
</blockquote></details>

Done.

**Review by rafiss — CHANGES_REQUESTED** [review]
looking nice!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69355#-:-Mi4V7IJ-F7p98cs0Bqi:bdyuade)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[pkg/sql/user.go, line 109 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/69355#-Mi4UTcT0bMruuKMahUP:-Mi4UTcT0bMruuKMahUQ:b-r0vnsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/67b7349676786b684abc80cc0b368bfe6e3e817b/pkg/sql/user.go#L109)):*
> ```Go
> 	}
> 
> 	err = execCfg.CollectionFactory.Txn(
> ```

there's one sneaky thing here -- since this can result in a KV lookup and it's during the connection init flow, this is supposed to be behind the `server.user_login.timeout` setting. see the comment on `GetUserSessionInitInfo`. the timeout itself is applied inside of the `retrieveSessionInitInfoWithCache` function right now.

there's also a test for it in user_test.go (it's named `TestGetUserHashedPasswordTimeout` since i missed renaming it in my last refactor)

so could you move this lookup to be behind the timeout, and verify with that test that the timeout applies to this operation?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69355)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/user.go, line 109 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/69355#-Mi4UTcT0bMruuKMahUP:-Mi4ity0DPS-CS1qy32B:b-pqt33p) ([raw file](https://github.com/cockroachdb/cockroach/blob/67b7349676786b684abc80cc0b368bfe6e3e817b/pkg/sql/user.go#L109)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

there's one sneaky thing here -- since this can result in a KV lookup and it's during the connection init flow, this is supposed to be behind the `server.user_login.timeout` setting. see the comment on `GetUserSessionInitInfo`. the timeout itself is applied inside of the `retrieveSessionInitInfoWithCache` function right now.

there's also a test for it in user_test.go (it's named `TestGetUserHashedPasswordTimeout` since i missed renaming it in my last refactor)

so could you move this lookup to be behind the timeout, and verify with that test that the timeout applies to this operation?
</blockquote></details>

gotcha, done

**Review by rafiss — APPROVED** [review]
lgtm! thanks for the tests

> Reviewed 5 of 6 files at r10, 13 of 13 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69355#-:-Mi89ewpETFTKbj3Grqg:b-nu7s6c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Comment by otan** [comment]
bors r=rafiss

**Pull request merged**
