### PR TITLE
roachtest: delete `debug` tests

### LINKED ISSUE #35976: roachtest: debug/nodes=3 failed
SHA: https://github.com/cockroachdb/cockroach/commits/3a7ea2d8c9d4a3e0d97f8f106fcf95b3f03765ec

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=debug/nodes=3 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1187480&tab=buildLog

```
The test failed on master:
	debug.go:75,debug.go:95,test.go:1214: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-1187480-debug-nodes-3:2 -- grep 'epoch' ./debug/gossip/liveness returned:
		stderr:
		
		stdout:
		grep: ./debug/gossip/liveness: No such file or directory
		Error:  exit status 2
		: exit status 1

```

### PR DESCRIPTION
**Pull request by tbg**
These are not meaningful as roachtests, and aren't adding enough
coverage to justify keeping around.

Future functionality testing of debug zip should happen in unit tests.
In roachtests, we're going to want to verify that we get meaningful
contents of the debug zip, especially on clusters in poor health.
We know it currently doesn't though.

Closes #35976.

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
LGTM. Are you planning on replacing these with unit tests immediately? Is the code this tested already tested elsewhere?

**Comment by tbg** [comment]
> Is the code this tested already tested elsewhere?

We have a unit test in `cli` that matches on the output of the command. The roachtest should be replaced by meaningful roachtests down the line (i.e. ones in which lots of stuff is going on including chaos) but I'm not planning on working on that immediately.

**Comment by tbg** [comment]
bors r=nvanbenschoten

**Comment by tbg** [comment]
bors r=nvanbenschoten

Had to silence `unused`.

**Pull request merged**
