### PR TITLE
kvserver: use Timer in getChecksum

### PR DESCRIPTION
**Pull request by tbg**
Not a big deal, but I saw that we're leaking a 5s timer in the
happy case. Avoid this by using more idiomatic `*timeutil.Timer`
which can be stopped.

Epic: none
Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
Friendly ping, no rush.

**Review by pav-kv — APPROVED** [review]
LGTM.

[pre-existing] Don't much like the verbosity, could help to have `timeutil.StartTimer(dur)` with the same expectation as `Reset`.

**Comment by tbg** [comment]
bors r=pavelkalinnikov

**Comment by tbg** [comment]
bors r=pavelkalinnikov

Unrelated flake

**Pull request merged**
