### PR TITLE
release-21.1: Backport tsdump improvements 

### PR DESCRIPTION
**Pull request by rimadeodhar**
Backport:
  * 1/1 commits from "server: simplify use of COCKROACH_DEBUG_TS_IMPORT_FILE" (#69525)
  * 1/1 commits from "server: Allow bypass of tsdump's strict checks" (#77247)

Please see individual PRs for details.

/cc @cockroachdb/release

Release justification: low risk, high benefit changes to existing functionality

### CODE REVIEW

**Comment by tbg** [comment]
Looks like CI has some issues. LGTM when that is fixed, assuming the fixes are mundane.

**Comment by rimadeodhar** [comment]
@tbg: The build is passing now. The issue was that I had forgotten to delete the `maybeImportTS` definition from within `server.go` as a part of the backport. PTAL. Thanks!

**Comment by tbg** [comment]
LGTM, thanks!

**Review by abarganier — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78057#-:-Myi3TxbBdnFW55cWuT9:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

**Pull request merged**
