### PR TITLE
roachtest: adjust import-cancellation

### LINKED ISSUE #112826: roachtest: import-cancellation failed
roachtest.import-cancellation [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12281269?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12281269?buildTab=artifacts#/import-cancellation) on master @ [07915532f9a7def000127029c667c3a91ce90e47](https://github.com/cockroachdb/cockroach/commits/07915532f9a7def000127029c667c3a91ce90e47):

```
(import_cancellation.go:154).func2: full command output in run_200910.232468691_n1_workload-run-tpch-db.log: COMMAND_PROBLEM: exit status 1
(monitor.go:153).Wait: monitor failure: monitor user task failed: t.Fatal() was called
test artifacts and logs in: /artifacts/import-cancellation/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=32</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-12281269/import-cancellation/1697916257934/1697920552941)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*import-cancellation.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-32620

### PR DESCRIPTION
**Pull request by yuzefovich**
We recently changed `import-cancellation` to use `tpch` workload with `--enable-checks`. However, that flag only supports Scale Factor 1 while `import-cancellation` is using SF100, and there are some queries that legitimately return different results - 11, 13, 16, 18, 20 are now skipped. Additionally, this commit removes the perf artifacts and no longer marks the test as "benchmark" - I don't think we're benchmarking anything here.

Fixes: #112826.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I just kicked off a single run from gceworker to ensure this passes.

**Comment by yuzefovich** [comment]
That single run passed, so I think this should be good to go.

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112974#-:-Nh_LRAK9Nd8jRQ-1Pvg:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
