### PR TITLE
raft: use candidate's log term to determine inFortifyLease condition

### PR DESCRIPTION
**Pull request by arulajmani**
Previously, if a node received a Msg{,Pre}Vote request from a peer but it still supported a leader in StoreLiveness, the node would reject the request with the justification that it was fortified. However, if the campaigning peer is doing so with a higher log term than we're aware of, then this conclusively proves that the leadership term we're fortifying has actually ended. This then allows us to de-fortify, which ends our fortification lease, granting us the freedom to call elections and vote in the current (and future) campaigns. This patch recognizes this case and switches to this behavior.

Note that this is more than just an optimization -- one can craft scenarios where de-fortifying and voting in an election is the only way we'll ever elect a new leader. One such scenario is shown in the test case attached to this commit.

Epic: none

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131716)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @iskettaneh)

___
*[`pkg/raft/testdata/fortification_log_term_check` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131716#-O8AOio_9psjoGRNarXA:-O8AOio_9psjoGRNarXB:bqwpwt5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a11273dd8e0d4777d560dfe3092cca7e852f3c37/pkg/raft/testdata/fortification_log_term_check#L10)):*
> supporting each other in store liveness all this while

Could we say a little more about how this relates to their understanding of, and support for, the raft leader.
___
*[`pkg/raft/testdata/fortification_log_term_check` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131716#-O8APkKu62dZeq3hDByL:-O8APkKu62dZeq3hDByM:b2feusn) ([raw file](https://github.com/cockroachdb/cockroach/blob/a11273dd8e0d4777d560dfe3092cca7e852f3c37/pkg/raft/testdata/fortification_log_term_check#L10)):*
> ```
> # successfully become the leader.
> # - The test ensures that 4 is able to win an election, even though 1 and 5 have
> # still been supporting each other in store liveness all this while.
> ```

Can we discuss how this test creates a scenario that would be resolved independently by CheckQuorum and the leader stepping down + defortifying, but that there are related cases where this LogTerm check is needed because we can't rely on the leader defortifying all replicas (only a majority of replicas) in cases where it is getting demoted and removed from the raft group?
___
*[`pkg/raft/testdata/fortification_log_term_check` line 296 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131716#-O8AP39r2SjU2Q4c7N5o:-O8AP39r2SjU2Q4c7N5p:buebxqw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a11273dd8e0d4777d560dfe3092cca7e852f3c37/pkg/raft/testdata/fortification_log_term_check#L296)):*
> ```
>   INFO 2 has received 1 MsgVoteResp votes and 0 vote rejections
> 
> deliver-msgs drop=(1,5)
> ```

Worth showing that 1 and 5 both discard this MsgVote? We only need to drop the post-election messages from the new leader.
___
*[`pkg/raft/testdata/fortification_log_term_check` line 404 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131716#-O8APM_83DHfQR4MsGz7:-O8APM_83DHfQR4MsGz8:b-r36qtt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a11273dd8e0d4777d560dfe3092cca7e852f3c37/pkg/raft/testdata/fortification_log_term_check#L404)):*
> ```
> 5 1 1 1 1 1
> 
> # Note that when we heal the network partition, 2
> ```

This comment got cut off.

**Review by nvb — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131716#-:-O9k1rYA0O7zK8Fnn9KI:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @iskettaneh)

**Comment by arulajmani** [comment]
Thanks!

bors r=nvanbenschoten

**Comment by arulajmani** [comment]
blathers backport 24.3

**Pull request merged**
