### PR TITLE
roachtest: test AOST restore in backup-restore/* roachtests

### PR DESCRIPTION
**Pull request by msbutler**
This patch allows the backup-restore driver to run and validate AOST restores from revision history backups. If the driver created a revision history backup, there's a 50% chance it will restore from an AOST between the full backup end time and the last incremental start time. A future patch will allow for AOST restores from non-revision history backups.

Epic: none

Release note: none

### CODE REVIEW

**Comment by msbutler** [comment]
I took this PR for a few test drives and it seems to work.

**Review by renatolabs — APPROVED** [review]
:lgtm:

Made an optional comment about failure reproducibility but otherwise looks good!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113534#-:-NiBJ3ez43v-bQoxFWI4:b-ua52y2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru and @msbutler)

___
*[`pkg/cmd/roachtest/tests/mixed_version_backup.go` line 1043 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113534#-NiBHzpS9CILBPJrcsuC:-NiBHzpS9CILBPJrcsuD:b-grqwhq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1970d70486b78b445eac968c2cab4e6d8d5b7749/pkg/cmd/roachtest/tests/mixed_version_backup.go#L1043)):*
> ```Go
> 	// Choose a random aost between min and max
> 	restoreAOST := hlc.Timestamp{
> 		WallTime: rng.Int63n(max.WallTime-min.WallTime) + min.WallTime,
> ```

For consideration: instead of a completely arbitrary timestamp in this range (which could be large), consider dividing this duration in N parts (say, N=5) and picking the time at the beginning of one of these slices. I believe this should be pretty sufficient in terms of correctness coverage while preserving _some_ sense of similarity of runs when the same rng is used.

With the current implementation, each run will pick a potentially wildly different `restoreAOST` (since the `Int63n` argument will be different) even if run with the same seed. Say a bug only happens when a timestamp close to the full backup time is picked: re-running the test with the same seed will not help focus on that scenario.
___
*[`pkg/cmd/roachtest/tests/mixed_version_backup.go` line 2254 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113534#-NiBIwbt7sN7xIxHGPND:-NiBIwbt7sN7xIxHGPNE:bcxyevo) ([raw file](https://github.com/cockroachdb/cockroach/blob/1970d70486b78b445eac968c2cab4e6d8d5b7749/pkg/cmd/roachtest/tests/mixed_version_backup.go#L2254)):*
> ```Go
> 	restoreStmt := fmt.Sprintf(
> 		"%s FROM LATEST IN '%s'%s %s",
> 		restoreCmd, bc.uri(), aostClause, optionsStr,
> ```

Nit: you don't need the `aostClause` variable, you can just call `aostFor(bc.restoreAOST)` here.

**Comment by renatolabs** [comment]
While you have your hands in this test, maybe you can sneak in this request I had made previously 😄 Or maybe I'm the only one who misses that, hehe.

https://github.com/cockroachdb/cockroach/issues/112373#issuecomment-1782945597

**Review by msbutler — COMMENTED** [review]
done

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113534#-:-NiBS2ji1sNnvPIRTwdE:bb7f2mf)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/mixed_version_backup.go` line 1043 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113534#-NiBHzpS9CILBPJrcsuC:-NiBS09TBpBbe7SBEACF:b-hemjqh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1970d70486b78b445eac968c2cab4e6d8d5b7749/pkg/cmd/roachtest/tests/mixed_version_backup.go#L1043)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

For consideration: instead of a completely arbitrary timestamp in this range (which could be large), consider dividing this duration in N parts (say, N=5) and picking the time at the beginning of one of these slices. I believe this should be pretty sufficient in terms of correctness coverage while preserving _some_ sense of similarity of runs when the same rng is used.

With the current implementation, each run will pick a potentially wildly different `restoreAOST` (since the `Int63n` argument will be different) even if run with the same seed. Say a bug only happens when a timestamp close to the full backup time is picked: re-running the test with the same seed will not help focus on that scenario.
</blockquote></details>

ah very good call. fixed.
___
*[`pkg/cmd/roachtest/tests/mixed_version_backup.go` line 2254 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113534#-NiBIwbt7sN7xIxHGPND:-NiBS-36Cu8Mba8QDbVh:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1970d70486b78b445eac968c2cab4e6d8d5b7749/pkg/cmd/roachtest/tests/mixed_version_backup.go#L2254)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Nit: you don't need the `aostClause` variable, you can just call `aostFor(bc.restoreAOST)` here.
</blockquote></details>

done

**Review by renatolabs — COMMENTED** [review]
Thank you!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113534#-:-NiBYcdzEWs_H2LH08kk:b-9755fn)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru)

**Comment by msbutler** [comment]
TFTR!

bors r=renatolabs

**Comment by renatolabs** [comment]
blathers backport 23.1

**Pull request merged**
