### PR TITLE
maybe-stress: retry `bazel query`

### PR DESCRIPTION
**Pull request by rickystewart**
Unfortunately this can fail due to a UI flake.

Epic: none
Release note: None

### CODE REVIEW

**Review by arulajmani — APPROVED** [review]

**Comment by rickystewart** [comment]
bors r=arulajmani

**Comment by rickystewart** [comment]
bors r=arulajmani

**Review by rail — APPROVED** [review]

**Comment by knz** [comment]
this probably needs a backport?

**Comment by rickystewart** [comment]
blathers backport 23.1

**Pull request merged**
