### PR TITLE
opt: prefer sorting fewer columns

### LINKED ISSUE #32952: opt: derived projections shouldn't be pushed past sorts
Here's the plan for TPCH Q1:

```
root@:26257/tpch> explain(verbose) select
sum(l_quantity) as sum_qty,
sum(l_extendedprice) as sum_base_price,
sum(l_extendedprice * (l_discount - 1)) as sum_disc_price, 
sum(l_extendedprice * (l_discount -1) * (1 + l_tax)) as sum_charge, 
avg(l_quantity) as avg_qty,   
avg(l_extendedprice) as avg_price, 
avg(l_discount) as avg_disc
from lineitem                                                                                                                                                                                               group by l_returnflag, l_linestatus                                                                                                                                                                                           order by l_returnflag,  l_linestatus;
            tree           |    field    |                      description                       |                                          columns                                          |          ordering
+--------------------------+-------------+--------------------------------------------------------+-------------------------------------------------------------------------------------------+-----------------------------+
  render                   |             |                                                        | (sum_qty, sum_base_price, sum_disc_price, sum_charge, avg_qty, avg_price, avg_disc)       |
   │                       | render 0    | agg0                                                   |                                                                                           |
   │                       | render 1    | agg1                                                   |                                                                                           |
   │                       | render 2    | agg2                                                   |                                                                                           |
   │                       | render 3    | agg3                                                   |                                                                                           |
   │                       | render 4    | agg4                                                   |                                                                                           |
   │                       | render 5    | agg5                                                   |                                                                                           |
   │                       | render 6    | agg6                                                   |                                                                                           |
   └── group               |             |                                                        | (l_returnflag, l_linestatus, agg0, agg1, agg2, agg3, agg4, agg5, agg6)                    | +l_returnflag,+l_linestatus
        │                  | aggregate 0 | l_returnflag                                           |                                                                                           |
        │                  | aggregate 1 | l_linestatus                                           |                                                                                           |
        │                  | aggregate 2 | sum(l_quantity)                                        |                                                                                           |
        │                  | aggregate 3 | sum(l_extendedprice)                                   |                                                                                           |
        │                  | aggregate 4 | sum(column19)                                          |                                                                                           |
        │                  | aggregate 5 | sum(column21)                                          |                                                                                           |
        │                  | aggregate 6 | avg(l_quantity)                                        |                                                                                           |
        │                  | aggregate 7 | avg(l_extendedprice)                                   |                                                                                           |
        │                  | aggregate 8 | avg(l_discount)                                        |                                                                                           |
        │                  | group by    | @6,@7                                                  |                                                                                           |
        │                  | ordered     | @6,@7                                                  |                                                                                           |
        └── sort           |             |                                                        | (column19, column21, l_quantity, l_extendedprice, l_discount, l_returnflag, l_linestatus) | +l_returnflag,+l_linestatus
             │             | order       | +l_returnflag,+l_linestatus                            |                                                                                           |
             └── render    |             |                                                        | (column19, column21, l_quantity, l_extendedprice, l_discount, l_returnflag, l_linestatus) |
                  │        | render 0    | l_extendedprice * (l_discount - 1.0)                   |                                                                                           |
                  │        | render 1    | (l_extendedprice * (l_discount - 1.0)) * (l_tax + 1.0) |                                                                                           |
                  │        | render 2    | l_quantity                                             |                                                                                           |
                  │        | render 3    | l_extendedprice                                        |                                                                                           |
                  │        | render 4    | l_discount                                             |                                                                                           |
                  │        | render 5    | l_returnflag                                           |                                                                                           |
                  │        | render 6    | l_linestatus                                           |                                                                                           |
                  └── scan |             |                                                        | (l_quantity, l_extendedprice, l_discount, l_tax, l_returnflag, l_linestatus)              |
                           | table       | lineitem@primary                                       |                                                                                           |
                           | spans       | ALL                                                    |                                                                                           |
(33 rows)

Time: 2.552ms
```

As you can see, the optimizer pushes the "derived" render expressions (projections that aren't part of the scan) past the sort. This is inefficient, as it requires that the sort shuffle more memory.

Ideally, the optimizer should not materialize any extra projections below a sort, to avoid this kind of shuffling.

### PR DESCRIPTION
**Pull request by RaduBerinde**
Currently, if we have to sort results and project a new column, there
is no cost difference between the two orders and we happen to prefer
the sort on top. It is preferable to sort before adding new columns to
avoid storing the extra value in memory or on disk.

This change improves the sort costing by adding a cost proportional to
the total number of values.

Fixes #32952.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 30 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60469#-:-MTGlY2Z2C4JiCdBiAn3:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/testdata/limit, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60469#-MTGkSACAs4PWgsH6RRq:-MTGkSACAs4PWgsH6RRr:b-wy0w6e) ([raw file](https://github.com/cockroachdb/cockroach/blob/673a257ee1c1ed3125b82982b091a79e96f91d49/pkg/sql/opt/optbuilder/testdata/limit#L150)):*
> ```
>  │         ├── sort
>  │         │    ├── columns: k:1!null v:2 w:3
>  │         │    ├── ordering: -2
> ```

Are we losing an opportunity for a streaming groupby by removing the sort here? Or does it need to be sorted by both grouping columns?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60469)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/optbuilder/testdata/limit, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60469#-MTGkSACAs4PWgsH6RRq:-MTH03gU9DAmQclE7-q6:b-izz4v5) ([raw file](https://github.com/cockroachdb/cockroach/blob/673a257ee1c1ed3125b82982b091a79e96f91d49/pkg/sql/opt/optbuilder/testdata/limit#L150)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Are we losing an opportunity for a streaming groupby by removing the sort here? Or does it need to be sorted by both grouping columns?
</blockquote></details>

This is a "build" test so this wouldn't be the final plan.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60469)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[pkg/sql/opt/optbuilder/testdata/limit, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60469#-MTGkSACAs4PWgsH6RRq:-MTHOkyH6fLSy7guAUck:bwpu2bc) ([raw file](https://github.com/cockroachdb/cockroach/blob/673a257ee1c1ed3125b82982b091a79e96f91d49/pkg/sql/opt/optbuilder/testdata/limit#L150)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is a "build" test so this wouldn't be the final plan.
</blockquote></details>

got it - thanks

**Review by mgartner — APPROVED** [review]
:lgtm: Nice! Seems like a high leverage change.

I noticed that ordering of some group-by + sort operations changed, like [here](https://github.com/cockroachdb/cockroach/pull/60469/files#diff-baa13f8ff7b48b5f243e151761489b464d195d6334ef15de347b21ffaa0ee3ef). I think this is ok, but I'm curious: does group-by take advantage its input being already sorted by the group-by columns? Or, could group-by produce rows in order of the group by column, eliminating the need for an additional sort afterwards?

> Reviewed 30 of 30 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60469#-:-MTHQepD5vJ8c5gX211q:bvjm3ly)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Review by RaduBerinde — COMMENTED** [review]
The example you linked to is a `build` test so we don't expect a good plan.

Group-by does take advantage of sorted input (in which case it does preserve the ordering; hence the "old" plan you linked to). But that doesn't mean that it's always better to sort before - if the group-by reduces the number of rows a lot, it's better to sort after. (this is predicated on "unordered" groupby being cheaper than "ordered" groupby plus a sort; if it wasn't, we would use ordered groupbys in all cases)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60469#-:-MTHUGe45xuBWwa6FCud:bcirxwe)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Review by mgartner — APPROVED** [review]
:+1: Thanks for the explanation!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60469#-:-MTHjo-kDjXdeK7SipBZ:b-e5154s)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Comment by jordanlewis** [comment]
Nice - it's also worth noting that in vectorized an n-column sort is done in n passes. So this helps CPU too even without considering memory/disk.

**Comment by RaduBerinde** [comment]
When you say n-column sort, is `n` the number of key columns, or the total number of columns? (We already take the former into account when costing; this change adds a cost for the latter).

**Comment by jordanlewis** [comment]
Ah, I understand. Nevermind, it's about the key columns.

**Comment by RaduBerinde** [comment]
There is an interesting point there though - the sort costing is inspired by how the row processor does it, we should update it to better reflect the vectorized engine.

**Comment by RaduBerinde** [comment]
TFTRs!

bors r+

**Pull request merged**
