### PR TITLE
kvserver: avoid clobbering replica conf

### LINKED ISSUE #75109: kv/kvserver: TestBackpressureNotAppliedWhenReducingRangeSize failed
kv/kvserver.TestBackpressureNotAppliedWhenReducingRangeSize [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4146858&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4146858&tab=artifacts#/) on master @ [3b9a9579bed8288a7823d6caeebf692168987459](https://github.com/cockroachdb/cockroach/commits/3b9a9579bed8288a7823d6caeebf692168987459):

```
=== RUN   TestBackpressureNotAppliedWhenReducingRangeSize
    test_log_scope.go:79: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestBackpressureNotAppliedWhenReducingRangeSize3351118793
    test_log_scope.go:80: use -show-logs to present logs inline
=== CONT  TestBackpressureNotAppliedWhenReducingRangeSize
    client_replica_backpressure_test.go:310: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestBackpressureNotAppliedWhenReducingRangeSize3351118793
--- FAIL: TestBackpressureNotAppliedWhenReducingRangeSize (5.58s)
=== RUN   TestBackpressureNotAppliedWhenReducingRangeSize/backpressure_when_near_limit_on_new_node
    client_replica_backpressure_test.go:303: expected no error because the request should hang, got <nil>
    --- FAIL: TestBackpressureNotAppliedWhenReducingRangeSize/backpressure_when_near_limit_on_new_node (1.54s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
Parameters in this failure:

- GOFLAGS=-json
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #72970 kv/kvserver: TestBackpressureNotAppliedWhenReducingRangeSize failed [C-test-failure O-robot branch-release-21.2]
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestBackpressureNotAppliedWhenReducingRangeSize.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by irfansharif**
Fixes #75109. There are two ways to read the configuration applied over
a given replica:
  (a) the copy embedded in each replica struct
  (b) spanconfig.StoreReader, hanging off the store struct

The interface in (b) is implemented by both the span configs
infrastructure and the legacy system config span it's designed to
replace; it's typically used by KV queues (see #69172). When switching
between subsystems in KV (controlled by spanconfig.store.enabled), for
we transparently switch the source for (b). We also use then use the
right source to refresh (a) for every replica. Incremental updates
thereafter mutate (a) directly. As you'd expect, we need to take special
care that only one subsystem is writing to (a) at a given point in time,
a guarantee that was not upheld before this commit. This bug manifested
after we enabled span configs by default (see #73876), and likely
affected many tests.

To avoid the system config span from clobbering (a) when span configs
are enabled, we just need to check what spanconfig.store.enabled
holds at the right spot. To repro:

    # Reliably fails with 1-2m on my GCE worker before this patch,
    # doesn't after.
    dev test pkg/kv/kvserver \
      -f TestBackpressureNotAppliedWhenReducingRangeSize \
      -v --show-logs --timeout 15m --stress

Release note: None

### CODE REVIEW

**Comment by irfansharif** [comment]
PS: Looking at the CI failures here, merging this bug fix will probably surface more CI failures/improper test assumptions that were masked until now. Take a look at the following for e.g., definitely does not hold true anymore.

https://github.com/cockroachdb/cockroach/blob/5359e546359dc95acb36b226ca95f83b7001c389/pkg/kv/kvserver/replicate_queue_test.go#L264-L277

**Comment by irfansharif** [comment]
Outstanding CI failure is #75212.

**Review by arulajmani — CHANGES_REQUESTED** [review]
I have a couple questions for the second commit but otherwise everything else looks good. 

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75233#-:-MtyxzBTA4vVjGVdHq0S:b7vewyj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @nvanbenschoten)

___
*[-- commits, line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75233#-MtypoVZClV7FGQvmTHI):*
It's worth adding more words around what those assumptions were here. 
___
*[pkg/kv/kvserver/testing_knobs.go, line 378 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/75233#-Mtyxt56BZkz6no2r7ll:-Mtyxt56BZkz6no2r7lm:btlt8dp) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e2894ba88b24b685424f7ee5d5c49ca5c6ef43f/pkg/kv/kvserver/testing_knobs.go#L378)):*
> ```Go
> 	// is used only for (old) tests written with the system config span in mind.
> 	//
> 	// TODO(irfansharif): Get rid of this knob, maybe by first move
> ```

"maybe by first move"
___
*[pkg/kv/kvserver/client_store_test.go, line 30 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75233#-Mtywdvn-2fwXAXak89O:-Mtywdvn-2fwXAXak89P:blss9r0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4c6269f26c96ffd6de679bc417e303884907aa4/pkg/kv/kvserver/client_store_test.go#L30)):*
> ```Go
> // TestStoreSetRangesMaxBytes creates a set of ranges via splitting and then
> // sets the config zone to a custom max bytes value to verify the ranges' max
> // bytes are updated appropriately. // XXX:
> ```

// XXX: ?
___
*[pkg/kv/kvserver/replicate_queue_test.go, line 275 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75233#-MtyoqMZA8pZyBCXmCU1:-MtyoqMZA8pZyBCXmCU2:b-7jig1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a40796d81cbcdde90b5c32581745f91e7b48916/pkg/kv/kvserver/replicate_queue_test.go#L275)):*
> ```Go
> 	// config asks for 3x replication, and the replication queue will
> 	// down-replicate it.
> 	require.Len(t, desc.Replicas().Descriptors(), 5)
> ```

Do we know why this worked before and doesn't work now? Is that something we want to address or are we happy changing this test?

**Review by irfansharif — COMMENTED** [review]
Thanks, PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75233#-:-MuBOGC14zEj_BCCrnlL:bnsdipp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[-- commits, line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75233#-MtypoVZClV7FGQvmTHI):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

It's worth adding more words around what those assumptions were here. 
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/testing_knobs.go, line 378 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/75233#-Mtyxt56BZkz6no2r7ll:-MuBNfD5Boqwa4H3lFn7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e2894ba88b24b685424f7ee5d5c49ca5c6ef43f/pkg/kv/kvserver/testing_knobs.go#L378)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

"maybe by first move"
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/client_store_test.go, line 30 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75233#-Mtywdvn-2fwXAXak89O:-MuBNfvY5xNJZuLJ-3ww:bhdhx2d) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4c6269f26c96ffd6de679bc417e303884907aa4/pkg/kv/kvserver/client_store_test.go#L30)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

// XXX: ?
</blockquote></details>

Woops, forgot to remove. Done.
___
*[pkg/kv/kvserver/replicate_queue_test.go, line 275 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75233#-MtyoqMZA8pZyBCXmCU1:-MuBNl-D6v1WzWOxmV6e:b-3i759t) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a40796d81cbcdde90b5c32581745f91e7b48916/pkg/kv/kvserver/replicate_queue_test.go#L275)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Do we know why this worked before and doesn't work now? Is that something we want to address or are we happy changing this test?
</blockquote></details>

Yes, added to the commit message. Basically this test relied on the the internal behavior of the system config span where scratch range was split off from the system table ranges, and it "originally" applying the system database zone/span config. With "ConfigureScratchRange", we don't have any such lineage.

**Review by arulajmani — APPROVED** [review]
> Reviewed 5 of 5 files at r5, 3 of 3 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75233)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

**Comment by irfansharif** [comment]
CI failures are #75227 (unsure if span configs fallout) and #75080 (a bit surprising, this PR is rebased on top of #75146).

bors r+

**Pull request merged**
