### PR TITLE
roachtest: add a retry loop around network activity

### PR DESCRIPTION
**Pull request by BramGruneir**
This is a first attempt to try to address #31127 and #31298 by putting a retry
loop around anything that does any downloading. We've seen a number of flakes
because of iffy networking and this should hopefully solve the problem.

If this doesn't fix the issues, the next step it to add some alternative
sources to sources.list.d.

Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31508)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/hibernate.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31508#-LOyHvHl7hqwbtdYUi9S:-LOyHvHl7hqwbtdYUi9T:bn25ed3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e5d5588a5f4659598cc396bc322c76d8fb4e7dc/pkg/cmd/roachtest/hibernate.go#L108)):*
> ```Go
> 
> 			// Build hibernate, this step involves some downloading, so it gets added
> 			// to the retry loop.
> ```

Starting the retry loop from scratch at this point seems unfortunate. The earlier parts seem reasonable to keep in the same loop, but I'm thinking this should be pulled out to a separate loop.

**Review by BramGruneir — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31508)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/hibernate.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31508#-LOyHvHl7hqwbtdYUi9S:-LP276YC1A2ra9jssgI6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e5d5588a5f4659598cc396bc322c76d8fb4e7dc/pkg/cmd/roachtest/hibernate.go#L108)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Starting the retry loop from scratch at this point seems unfortunate. The earlier parts seem reasonable to keep in the same loop, but I'm thinking this should be pulled out to a separate loop.
</blockquote></details>

Done.

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31508)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/hibernate.go, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31508#-LP31WLo1jobuGo6Qqav:-LP31WLo1jobuGo6Qqaw:b88rtj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/27b0d93d40d107906ba283e62ae46dc6d2f101ac/pkg/cmd/roachtest/hibernate.go#L111)):*
> ```Go
> 		t.Status("building hibernate (without tests)")
> 		attempt = 0
> 		for r := retry.StartWithCtx(ctx, opts); r.Next(); {
> ```

I believe this can be `for attempt, r := 0, retry.StartWithCtx(...); r.Next(); { ... }`. Ditto for the loop above.

**Review by BramGruneir — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31508#-:-LP6ub8XDSilSghmvbK7:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/hibernate.go, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31508#-LP31WLo1jobuGo6Qqav:-LP6uYvr-SOC9jRU1A6l:bgztif1) ([raw file](https://github.com/cockroachdb/cockroach/blob/27b0d93d40d107906ba283e62ae46dc6d2f101ac/pkg/cmd/roachtest/hibernate.go#L111)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I believe this can be `for attempt, r := 0, retry.StartWithCtx(...); r.Next(); { ... }`. Ditto for the loop above.
</blockquote></details>

Yep.  Done.

**Pull request merged**
