### PR TITLE
workload/cli: stop including data-only generators in workload run

### PR DESCRIPTION
**Pull request by danhhz**
Release note(bug fix): `cockroach workload run` no longer includes
data-only generators

### CODE REVIEW

**Comment by danhhz** [comment]
paging @benesch : - )

**Review by benesch — APPROVED** [review]
Gah, sorry!

**Comment by danhhz** [comment]
No worries! Sorry you're stuck with doing these reviews. Doesn't seem worth getting someone else ramped up on so much workload stuff for such small PRs.

bors r=benesch

**Comment by jseldess** [comment]
@danhhz, I still see `startrek` and `intro` listed as possible commands in the help text for `cockroach workload run`. Is that an oversight or am I misunderstanding?

```
~/go/src/github.com/cockroachdb/cockroach$ cockroach workload run --help
[experimental] run a workload's operations against a cluster

Usage:
  cockroach workload run [flags]
  cockroach workload run [command]

Available Commands:
  bank        [experimental] Bank models a set of accounts with currency balances
  intro       [experimental] Intro contains a single table with a hidden message
  startrek    [experimental] Star Trek models episodes and quotes from the tv show
  tpcc        [experimental] TPC-C simulates a transaction processing workload using a rich schema of multiple tables

Flags:
  -h, --help   help for run

Global Flags:
      --logtostderr Severity[=DEFAULT]   logs at or above this threshold go to stderr (default NONE)
      --no-color                         disable standard error log colorization
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging (significantly hurts performance)

Use "cockroach workload run [command] --help" for more information about a command.
~/go/src/github.com/cockroachdb/cockroach$ cockroach workload run startrek
Error: no operations defined for startrek
~/go/src/github.com/cockroachdb/cockroach$ cockroach workload run intro
Error: no operations defined for intro
```

**Comment by jseldess** [comment]
Nevermind. I was using a 2.2 binary. 2.1 looks good.

**Comment by danhhz** [comment]
> Nevermind. I was using a 2.2 binary. 2.1 looks good.

@jseldess I just double-checked master and it works there too. Maybe we haven't released a 2.2 alpha since this went in?

**Pull request merged**
