### PR TITLE
sql: display postqueries in EXPLAIN

### LINKED ISSUE #38340: sql: display postqueries in EXPLAIN
We're introducing postqueries in #38281, but they won't show up in the output of EXPLAIN at the moment. We should fix that.

### PR DESCRIPTION
**Pull request by yuzefovich**
Postqueries are now displayed in the output of EXPLAIN statement.

Fixes: #38340.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Thanks for this!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38849#-:-Ljbg2a30MkzvmSZqMws:b-p2kyme)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/logictest/testdata/planner_test/postquery, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38849#-Ljbgkia77cvZ85SsuK1:-Ljbgkib5PszEcrWELIA:bffaa4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/13295ae47dfcbca7a9b67395cdeef629231228f1/pkg/sql/logictest/testdata/planner_test/postquery#L1)):*
> ```
> # LogicTest: local-opt fakedist-opt
> ```

This is great, except this should live in `opt/execbuilder/testdata` (everything in planner_test is non-opt). Can you also rename it to `fk_opt`? To correspond with the `fk_opt` file in logictests.
___
*[pkg/sql/logictest/testdata/planner_test/postquery, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38849#-LjbgwPa6RbsKkXLLACH:-LjbgwPa6RbsKkXLLACI:bl5voal) ([raw file](https://github.com/cockroachdb/cockroach/blob/13295ae47dfcbca7a9b67395cdeef629231228f1/pkg/sql/logictest/testdata/planner_test/postquery#L13)):*
> ```
> 
> statement ok
> INSERT INTO parent VALUES (1), (2)
> ```

[nit] remove this (data doesn't matter when we're just explaining)

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38849)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/sql/logictest/testdata/planner_test/postquery, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38849#-Ljbgkia77cvZ85SsuK1:-Ljbs-Ey2Zn1PozXspfB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/13295ae47dfcbca7a9b67395cdeef629231228f1/pkg/sql/logictest/testdata/planner_test/postquery#L1)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is great, except this should live in `opt/execbuilder/testdata` (everything in planner_test is non-opt). Can you also rename it to `fk_opt`? To correspond with the `fk_opt` file in logictests.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/planner_test/postquery, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38849#-LjbgwPa6RbsKkXLLACH:-LjbsCr0C9rHfY-6iOX9:b-9if036) ([raw file](https://github.com/cockroachdb/cockroach/blob/13295ae47dfcbca7a9b67395cdeef629231228f1/pkg/sql/logictest/testdata/planner_test/postquery#L13)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] remove this (data doesn't matter when we're just explaining)
</blockquote></details>

Indeed, done.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38849#-:-Ljd028P4CGdabV-yRTH:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/explain_plan.go, line 368 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38849#-Ljd-L-89lUj4CgBZ_CH:-Ljd-L-89lUj4CgBZ_CI:b-jnuchg) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cc321c1a650cf46ff33ada82de70939dbbcefb/pkg/sql/explain_plan.go#L368)):*
> ```Go
> 			return err
> 		}
> 		observer.attr("postquery", "id", fmt.Sprintf("@S%d", i+1))
> ```

[nit] I don't think this id is useful in the output. I will (after this PR merges) add a field to the node with a "description" of the postquery, (e.g. `FK-check-<fk-name>`).
___
*[pkg/sql/opt/exec/execbuilder/testdata/fk_opt, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38849#-Ljd-q76-Gar9oc6CD_o:-Ljd-q76-Gar9oc6CD_p:b6hqq26) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cc321c1a650cf46ff33ada82de70939dbbcefb/pkg/sql/opt/exec/execbuilder/testdata/fk_opt#L1)):*
> ```
> # LogicTest: local-opt fakedist-opt
> ```

remove fakedist-opt (local vs fakedist makes no difference in these tests where we just EXPLAIN)

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38849)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/sql/explain_plan.go, line 368 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38849#-Ljd-L-89lUj4CgBZ_CH:-Ljm3sWG0ZO-K3dWWmP5:b-adj05h) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cc321c1a650cf46ff33ada82de70939dbbcefb/pkg/sql/explain_plan.go#L368)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I don't think this id is useful in the output. I will (after this PR merges) add a field to the node with a "description" of the postquery, (e.g. `FK-check-<fk-name>`).
</blockquote></details>

Yeah, I was also thinking it's not useful. Removed.
___
*[pkg/sql/opt/exec/execbuilder/testdata/fk_opt, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38849#-Ljd-q76-Gar9oc6CD_o:-Ljm41HK5urtrJhlu_yq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cc321c1a650cf46ff33ada82de70939dbbcefb/pkg/sql/opt/exec/execbuilder/testdata/fk_opt#L1)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

remove fakedist-opt (local vs fakedist makes no difference in these tests where we just EXPLAIN)
</blockquote></details>

Done.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38849#-:-LjnaNtF-7OOO76-7SkV:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by yuzefovich** [comment]
Seems like a flake.

bors r+

**Pull request merged**
