### PR TITLE
Upgrade to Go 1.8

### PR DESCRIPTION
**Pull request by tamird**
- Remove crosstool-ng 1.22.0 and use HEAD for both glibc and musl
toolchains. This was made possible by recent upstream work[0]
which re-added CentOS 6 support to crosstool-ng HEAD.
- Enable crosstool-ng's CT_ALLOW_BUILD_AS_ROOT, which was not available
in 1.22.0, and build as root, avoiding creating an extra non-root user.
- Statically link libgcc and libstdc++ by default when using the
builder image. This is made necessary by the newer GCC now provided by
crosstool-ng; it produces binaries with which the builder's system
libraries are incompatible.

[0] https://github.com/crosstool-ng/crosstool-ng/pull/586

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13673)

### CODE REVIEW

**Comment by petermattis** [comment]
The changes to the `.pb.go` files will cause anyone who edits `.protos` to need to upgrade to go1.8. That seems worthy of a PSA. Btw, have we ever figured out what causes that? It sure is irritating.

---

Reviewed 3 of 3 files at r1.
Review status: 2 of 47 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[build/builder.sh, line 35 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13673#-KdO6LAiioLpTR3YEjvF:-KdO6LAiioLpTR3YEjvG:b1d7wsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e8b4f9d29dcf5ff58d09efe4662400358b0c5b8/build/builder.sh#L35)):*
> ```Shell
>   tag="$(date +%Y%m%d-%H%M%S)"
>   docker tag "${image}" "${image}:${tag}"
>   docker push "${image}:${tag}"
> ```

Why this change? I thought `docker push` pushed all of the local tags.

---

*[build/Dockerfile, line 81 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13673#-KdO6lHOQCgnChBUj3iQ:-KdO6lHOQCgnChBUj3iR:bokoah9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e8b4f9d29dcf5ff58d09efe4662400358b0c5b8/build/Dockerfile#L81)):*
> ```Dockerfile
>  && rm -rf crosstool-ng
> 
> COPY x86-linux-gnu.config x86-linux-musl.config ./
> ```

Eh? What's this about?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13673#-:-KdO6yTOP9YhJjPbp0JN:b-byay3c)*

**Comment by tamird** [comment]
I thought it was changes to the compression machinery in the standard library.

This time I think it's https://golang.org/doc/go1.8#compress_flate:
> There have been some minor fixes to the encoder to improve the compression ratio in certain situations. **As a result, the exact encoded output of DEFLATE may be different from Go 1.7. Since DEFLATE is the underlying compression of gzip, png, zlib, and zip, those formats may have changed outputs.**

---

Review status: 2 of 47 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[build/builder.sh, line 35 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13673#-KdO6LAiioLpTR3YEjvF:-KdOLLZbXMDVLpts2Q6q:bam2fik) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e8b4f9d29dcf5ff58d09efe4662400358b0c5b8/build/builder.sh#L35)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Why this change? I thought `docker push` pushed all of the local tags.
</blockquote></details>

It does - I found that annoying when iterating on the image; sometimes I wanted it to push only the given tag. I can back this out if you like this behaviour.

---

*[build/Dockerfile, line 81 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13673#-KdO6lHOQCgnChBUj3iQ:-KdOLVu8xyJrecTSyIpx:b6w721u) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e8b4f9d29dcf5ff58d09efe4662400358b0c5b8/build/Dockerfile#L81)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Eh? What's this about?
</blockquote></details>

OCD, just matching the order below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13673#-:-KdOLYzUr0sBdI09tO2P:b-t484x2)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 45 of 45 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13673#-:-KdOeF76TBA1f5pAiP8t:bnfp4nl)*

**Comment by petermattis** [comment]
:lgtm:, though let's give a PSA and everyone a day or two to prepare.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13673#-:-KdRDeuuAZY1SbcbbUBF:bnfc90z)*

**Pull request merged**
