### PR TITLE
ci: run at default verbosity

### LINKED ISSUE #9969: *: a full test run produces 25MB of logs
Our logs in teamcity are enormous, making it hard to investigate failures because the browser begins to lock up (!). We should reduce the verbosity of our logging in CI.

### PR DESCRIPTION
**Pull request by tbg**
Fixes #9969.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9979)

### CODE REVIEW

**Comment by tschottdorf** [comment]
The build log resulting from this is... drum roll: 11kb.

**Comment by tamird** [comment]
Nice! LGTM.

**Comment by tschottdorf** [comment]
I also made up that number. Still navigating teamcity. Will update this in a second...

**Comment by tschottdorf** [comment]
4.12mb for `testrace`. Eh, not too bad still.

**Pull request merged**
