### PR TITLE
sql: split out EvalSequence from EvalPlanner

### PR DESCRIPTION
**Pull request by vivekmenezes**
Release note: None

I think someone can just rubber stamp this

### CODE REVIEW

**Comment by vilterp** [comment]
:lgtm: Fine with splitting out an interface, but the naming is a little awkward. Is `SequencePlanner` more appropriate? `SequenceAccessor`? I don't know. Thoughts from @knz or @jordanlewis?

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/sem/tree/eval.go, line 2085 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22461#-L4lsFI3AqpGkLl3G5Ax:-L4lsFI3AqpGkLl3G5Ay:b4jsb3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c3d73a5fd39daa8fdf5627d7501033ddd1ef480/pkg/sql/sem/tree/eval.go#L2085)):*
> ```Go
> }
> 
> // EvalSequence is used for various SEQUENCE related function that can
> ```

nit: "various SQL related functions" (plural), not function

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22461#-:-L4lsVrVcze3pAe5jawE:bfu23hb)*

**Comment by vivekmenezes** [comment]
Changed to SequenceOperators

---

Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/sem/tree/eval.go, line 2085 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22461#-L4lsFI3AqpGkLl3G5Ax:-L4lyYD121BrdSZBakVb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c3d73a5fd39daa8fdf5627d7501033ddd1ef480/pkg/sql/sem/tree/eval.go#L2085)):*
<details><summary><i>Previously, vilterp (Pete Vilter) wrote…</i></summary><blockquote>

nit: "various SQL related functions" (plural), not function
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22461#-:-L4lyVCE8MA3h-Twe-nw:b-5l1aau)*

**Comment by jordanlewis** [comment]
:lgtm: except you put `SequenceOperator` in some place and `SequenceOperators` in others

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22461#-:-L4m-I3K7KZSJRO9k9dY:betnhoi)*

**Comment by vivekmenezes** [comment]
TFTRs

**Pull request merged**
