### PR TITLE
sql: SHOW RANGES delegates to crdb_internal.ranges

### PR DESCRIPTION
**Pull request by jordanlewis**
Previously, SHOW RANGES had a near identical implementation to
crdb_internal.ranges, which was also unoptimal as it always needed to
request leaseholder information.

Now, it delegates to crdb_internal.ranges, which deletes duplicate code
and also permits the optimizer to remove the fetching of leaseholder
information unless it's requested.

Release note (sql change): SHOW EXPERIMENTAL_RANGES is faster if no
columns are requested from it, like in SELECT COUNT(*) FROM [SHOW
EXPERIMENTAL_RANGES...].

### CODE REVIEW

**Review by knz — APPROVED** [review]
Very elegant. I love it.

**Comment by RaduBerinde** [comment]
Very nice! LGTM

**Pull request merged**
