### PR TITLE
sqlproxy: don't call BackendConfigFromParams twice

### PR DESCRIPTION
**Pull request by spaskob**
Function `BackendConfigFromParams` modifies its map argument `params`
and hence is not idempotent and should not be called more than once.

Release note: none.

### CODE REVIEW

**Review by imjching — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58681)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @alyshanjahani-crl, @darinpp, and @spaskob)

___
*[pkg/ccl/sqlproxyccl/proxy.go, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58681#-MQcJTqQDa-ybwYy5zE_:-MQcJTqQDa-ybwYy5zEa:b1vzjf3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cf549a850bec3694991f4c6b7de9f05ddb96632/pkg/ccl/sqlproxyccl/proxy.go#L202)):*
> ```Go
> 	ctx, cancel := context.WithCancel(context.Background())
> 	defer cancel()
> 	if backendDialer == nil {
> ```

Did you mean to say `backendConfig == nil`? `backendDialer` should never be nil here since we have already replaced it earlier.

**Review by darinpp — APPROVED** [review]
Looks Good. Thanks.

**Comment by spaskob** [comment]
TFTRs!

**Pull request merged**
