### PR TITLE
spanconfig: limit # of tenant span configs

### LINKED ISSUE #70555: kvserver: limit the number of kv spans configurable by a tenant
#66348 outlined a scheme to support zone configs for secondary tenants. Since the unit of what we can configure in KV is a Range, tenants now being able to set zone configs grants them the ability to induce an arbitrary number of splits in KV -- something we want to put guardrails against (see RFC for more details).

There's some discussion [elsewhere](https://github.com/cockroachdb/cockroach/pull/66348#pullrequestreview-692139971) for how we could achieve this, copying over one in particular:

> We could have each pod lease out a local quota, counting against the tenant's global limit. For N pods of a tenant, and a limit L, we could either lease out partial quotas L/N, or have a single pod lease out L entirely and require all DDLs/zcfgs to through that one pod. The scheme below describes the general case of each pod getting some fractional share of the total quota.
>
> - When each pod considers a DDL/zcfg txn, before committing it will attempt to acquire a quota from its local leased limit. The quota acquired is an over-estimate of how much the txn will cost (in terms of additional splits induced); we cannot under-estimate as KV could then later reject the committed zcfg.
>   - If there's insufficient quota, we'll abort the txn and error out accordingly.
>   - If there's sufficient quota, we'll commit the txn and rely on the eventual reconciliation to reliably succeed. We'll queue up a work item for the for the reconciliation job, marking alongside it the lease expiration of the quota it was accepted with.
> - When the local pool runs out of quota and has to request/lease more, it needs to ensure that all the txns that have been committed have been reconciled. We don't want it to be the case that a quota is leased, allocated to an operation in the work queue, it stays in the work queue past its lease expiration date, and we're able to lease the "same" quota again and queue up a second work item that will now get rejected. We need to make sure that when we lease a limit at t, there are no unprocessed work items with leased tokens expiring before t.
> - Whenever the work item is processed, the amount we over-estimated by could either be returned to the local quota pool (with the same expiration ts), or we could simply drop it entirely and rely on the local quota pool to eventually re-acquire it from the global pool.

The RFC also captures a possible schema we could use on the host tenant to store these limits:
```sql
CREATE TABLE system.spans_configurations_per_tenant (
    tenant_id               INT,
    max_span_configurations INT,
)
```

The actual RPCs/interfaces are TBD. Probably we also want the ability to configure these limits on a per-tenant basis.

Epic CRDB-10563

Jira issue: CRDB-10116

### PR DESCRIPTION
**Pull request by irfansharif**
Fixes #70555. In order to limit the number of span configs a tenant's
able to install, we introduce a tenant-side spanconfig.Limiter. It
presents the following interface:

    // Limiter is used to limit the number of span configs installed by
    // secondary tenants. It considers the committed and uncommitted
    // state of a table descriptor and computes the "span" delta, each
    // unit we can apply a configuration over. It uses these deltas to
    // maintain an aggregate counter, informing the caller if exceeding
    // the configured limit.
    type Limiter interface {
      ShouldLimit(
        ctx context.Context, txn *kv.Txn,
        committed, uncommitted catalog.TableDescriptor,
      ) (bool, error)
    }

This limiter only applies to secondary tenants. The counter is
maintained in a newly introduced (tenant-only) system table, using the
following schema:

    CREATE TABLE system.span_count (
      singleton  BOOL DEFAULT TRUE,
      span_count INT NOT NULL,
      CONSTRAINT "primary" PRIMARY KEY (singleton),
      CONSTRAINT single_row CHECK (singleton),
      FAMILY "primary" (singleton, span_count)
    );

We need just two integration points for spanconfig.Limiter:
- Right above CheckTwoVersionInvariant, where we're able to hook into
  the committed and to-be-committed descriptor state before txn commit.
- In the GC job, when gc-ing table state. We decrement a table's split
  count when GC-ing the table for good.

The per-tenant span config limit used is controlled by a new tenant
read-only cluster setting: spanconfig.tenant_limit. Multi-tenant cluster
settings (#73857) provides the infrastructure for the host tenant to be
able to control this setting cluster wide, or to target a specific
tenant at a time.

We also need a migration here, to start tracking span counts for
clusters with pre-existing tenants. We introduce a migration that scans
over all table descriptors and seeds system.span_count with the right
value. Given cluster version gates disseminate asynchronously, we also
need a preliminary version to start tracking incremental changes.

It's useful to introduce the notion of debt. This will be handy if/when
we lower per-tenant limits, and also in the migration above since it's
possible for pre-existing tenants to have committed state in violation
of the prescribed limit. When in debt, schema changes that add new
splits will be rejected (dropping tables/indexes/partitions/etc. will
work just fine).

When attempting a txn that goes over the configured limit, the UX is as
follows:

    > CREATE TABLE db.t2(i INT PRIMARY KEY);
    pq: exceeded limit for number of table spans

Release note: None
Release justification: low risk, high benefit change

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> Reviewed 31 of 52 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77337)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @irfansharif)

___
*[pkg/spanconfig/spanconfiglimiter/limiter.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77337#-MyrDAIo8Z4v9aI7cSGf:-MyrDAIo8Z4v9aI7cSGg:b37q6xp) ([raw file](https://github.com/cockroachdb/cockroach/blob/10058c8b6fc30be9ea95e8f43ee3edd22716f004/pkg/spanconfig/spanconfiglimiter/limiter.go#L75)):*
> ```Go
> func (l *Limiter) ShouldLimit(
> 	ctx context.Context, txn *kv.Txn, committed, uncommitted catalog.TableDescriptor,
> ) (bool, error) {
> ```

I don't think it's reasonable to do this update on a per-table basis. I think we need batching. This will add a ton of round-trip (two per table) if we don't batch. Is there a way to rework this interface to get all of the modified descriptors and sum up the change just once?



_Code quote:_
```Go
// ShouldLimit is part of the spanconfig.Limiter interface.
func (l *Limiter) ShouldLimit(
	ctx context.Context, txn *kv.Txn, committed, uncommitted catalog.TableDescriptor,
) (bool, error) {
```

**Review by arulajmani — COMMENTED** [review]
As I understand it, this `system.span_count` table we're adding for secondary tenants coupled with the `Limiter` interface is a mechanism for non-malicious secondary tenants avoid committing transactions that'll induce more splits than allowed. Should we be doing some sort of validation on the system tenant as well for malicious tenant cases? Do we need another table on the system tenant that tracks per-tenant # of splits and validates `KVAccessor` requests don't go over this limit? 

If you buy all of ^, then the migration here becomes interesting. Given that we allow tenants to "get into debt" only when running the `SeedSpanCountTable` migration, we'd somehow need to make an exception for this on the system tenant as well. I'm not entirely sure how hard that'll be/if we have the tools for this. 

> Reviewed 22 of 52 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77337#-:-MzGhOdT4gWTHwFT7aWx:bjty3w5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @irfansharif)

**Review by irfansharif — COMMENTED** [review]
Batching sounds reasonable+easy, we have the full set of uncommitted descriptors at the caller. I'll make that change soon. Is there anything else in this PR that's worth discussing? I'd like a fuller review before iterating since it's a large-ish change.

> Do we need another table on the system tenant that tracks per-tenant # of splits and validates KVAccessor requests don't go over this limit?

I don't think so, no. That sounds like a separate body of work and one worth decoupling from this PR. It might interest you knowing that the way we do tenant billing is using tenant pod reported RUs (without "KV validation"), so running afoul of the similar issue you've outlined. There are other more pressing modified-tenant-code issues I'd worry about I think, so I'm happy not being defensive at the outset.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77337#-:-MzLZcgiEl5ZHbXxc5WM:b-3bbxon)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @irfansharif)

**Comment by arulajmani** [comment]
> It might interest you knowing that the way we do tenant billing is using tenant pod reported RUs (without "KV validation"), so running afoul of the similar issue you've outlined.

My understanding of this is that we don't care about tenant billing being inaccurate because it only ever affects a single malicious tenant, which we can turn off. A tenant circumventing the limits this PR introduces and creating an obscene number of ranges affects other tenants running on the same host however. Which is why I was under the impression we wanted this "KV validation". Is that not the case? 

@ajwerner, @nvanbenschoten what's our current thinking around this?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77337)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @irfansharif)

___
*[pkg/spanconfig/spanconfig.go, line 262 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77337#-MzLrQlz5Ko33eyUQ37H:-MzLrQlz5Ko33eyUQ37I:b-7k8wto) ([raw file](https://github.com/cockroachdb/cockroach/blob/10058c8b6fc30be9ea95e8f43ee3edd22716f004/pkg/spanconfig/spanconfig.go#L262)):*
> ```Go
> 		ctx context.Context, txn *kv.Txn,
> 		committed, uncommitted catalog.TableDescriptor,
> 	) (bool, error)
> ```

my gut is that you're not getting all that much leverage out of this interface. If you look at your implementation of this function, it's like a bunch of work to compute the delta as a function of descriptors (which are pure data) and the splitter, and then interactions with the key-value store. It feels to me like you could easily rework this to just take an integer at this interface boundary and move the function of computing the split delta to be just a static function of the descriptors and the splitter. 

That should make testing easier and encapsulates the state behind a more direct interface. 



_Code quote:_
```Go

		ctx context.Context, txn *kv.Txn,
		committed, uncommitted catalog.TableDescriptor,
	) (bool, error)
```
___
*[pkg/sql/catalog/tabledesc/structured.go, line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77337#-MzLsLgeETasz3aPYk9f:-MzLsLgeETasz3aPYk9g:b-kjchvt) ([raw file](https://github.com/cockroachdb/cockroach/blob/10058c8b6fc30be9ea95e8f43ee3edd22716f004/pkg/sql/catalog/tabledesc/structured.go#L53)):*
> ```Go
> 	// ClusterVersion represents the version of the table descriptor read from the store.
> 	ClusterVersion descpb.TableDescriptor
> 	original       *immutable
> ```

what is this and how is it different from `ClusterVersion`?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77337)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @irfansharif)

___
*[pkg/spanconfig/spanconfig.go, line 262 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77337#-MzLrQlz5Ko33eyUQ37H:-MzN2v84CH7JG31-b74Q:buj4itg) ([raw file](https://github.com/cockroachdb/cockroach/blob/10058c8b6fc30be9ea95e8f43ee3edd22716f004/pkg/spanconfig/spanconfig.go#L262)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

my gut is that you're not getting all that much leverage out of this interface. If you look at your implementation of this function, it's like a bunch of work to compute the delta as a function of descriptors (which are pure data) and the splitter, and then interactions with the key-value store. It feels to me like you could easily rework this to just take an integer at this interface boundary and move the function of computing the split delta to be just a static function of the descriptors and the splitter. 

That should make testing easier and encapsulates the state behind a more direct interface. 
</blockquote></details>

Reworking the interface to be about a delta is also going to make the "batching" trivial. Instead of needing to pass a set of descriptors into this function, you can just process the split delta for all of the modified descriptors and then pass that into the limiter. That will also make treating `0` as a no-op incredibly simple. 
___
*[pkg/sql/catalog/systemschema/system.go, line 673 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77337#-MzN3F9X6d24GJymugmr:-MzN3F9X6d24GJymugms:b6852jy) ([raw file](https://github.com/cockroachdb/cockroach/blob/10058c8b6fc30be9ea95e8f43ee3edd22716f004/pkg/sql/catalog/systemschema/system.go#L673)):*
> ```Go
> 	SpanCountTableSchema = `
> CREATE TABLE system.span_count (
> 	singleton  BOOL DEFAULT TRUE,
> ```

one question which came up is whether we want to change the primary key here to be an integer or to allow for future limits to be applied. I don't think it's a bad idea. I already regret the `protected_ts_meta` data design. Then we can have a const enum for the property. Thoughts?

**Review by irfansharif — COMMENTED** [review]
Discussed offline about why KV-side validation isn't necessary yet, and certainly not worth doing as part of this PR. Copying a snippet:

> IIUC KV-side validation is only a safeguard against tenants running modified SQL code. I don’t think KV-side validation is as simple as maintaining per-tenant counters that are maintained for each KVAccessor request. That counter is going to be incremented/decremented by the reconciler, asynchronously after the schema elements have already been committed. For an unmodified tenant, if the KV side limit we’re checking against has been lowered since the tenant committed their schema elements, we have no recourse. Importantly, KV can’t distinguish between a malicious tenant abusing limits and a non-malicious tenant that’s rightfully committed within a recently-higher budget. To protect against modified tenant code here, we’d need something stronger — some sort of certificate from KV we associate with the schema commit and propagate it back up to KV during reconciliation for KV to then verify.
>
> Probably there are simpler approaches, I’m not sure, but it’s not just maintaining a per-tenant counter. IMO exporting a per-tenant metric on the KV side and setting up alerting rules on it seems much more pragmatic, at least for 22.1. In the future if we introduce leasing to claw back tenant schema creation concurrency, we could just do this then. I don’t think now is appropriate.

---

Added batching, a static function for computing deltas, and reduced spanconfig.Limiter to work with pre-computed deltas. Did it in an appended commit I'll squash once LGTM-ed. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77337#-:-MzakIApDsuPl4KfsNL0:b713zjw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @arulajmani)

___
*[pkg/spanconfig/spanconfig.go, line 262 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77337#-MzLrQlz5Ko33eyUQ37H:-Mzahrfq4OjYVxkklLi7:b-v3ytyo) ([raw file](https://github.com/cockroachdb/cockroach/blob/10058c8b6fc30be9ea95e8f43ee3edd22716f004/pkg/spanconfig/spanconfig.go#L262)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Reworking the interface to be about a delta is also going to make the "batching" trivial. Instead of needing to pass a set of descriptors into this function, you can just process the split delta for all of the modified descriptors and then pass that into the limiter. That will also make treating `0` as a no-op incredibly simple. 
</blockquote></details>

Made this take a delta instead.
___
*[pkg/spanconfig/spanconfiglimiter/limiter.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77337#-MyrDAIo8Z4v9aI7cSGf:-Mzai1bzEivs3Tu-6pBq:b6chyap) ([raw file](https://github.com/cockroachdb/cockroach/blob/10058c8b6fc30be9ea95e8f43ee3edd22716f004/pkg/spanconfig/spanconfiglimiter/limiter.go#L75)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I don't think it's reasonable to do this update on a per-table basis. I think we need batching. This will add a ton of round-trip (two per table) if we don't batch. Is there a way to rework this interface to get all of the modified descriptors and sum up the change just once?
</blockquote></details>

Added batching.
___
*[pkg/sql/catalog/systemschema/system.go, line 673 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77337#-MzN3F9X6d24GJymugmr:-Mzai4539s8dRk7LUpC7:b8d9c3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/10058c8b6fc30be9ea95e8f43ee3edd22716f004/pkg/sql/catalog/systemschema/system.go#L673)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

one question which came up is whether we want to change the primary key here to be an integer or to allow for future limits to be applied. I don't think it's a bad idea. I already regret the `protected_ts_meta` data design. Then we can have a const enum for the property. Thoughts? 
</blockquote></details>

Personally I prefer it this way. It's not clear to me what future limits will look like and whether they'll track just a single integer like we're doing here. We also no longer need to be frugal with our system table IDs so might be worth keeping various limiter-like storage tables separate for isolation reasons; just a bit wary of making this too generalized. If in the future we do build a general tenant-side limit-tracking table, it would also be easy to migrate the use of `system.span_count` into _that_ thing -- would be just copying over a row and start using it transactionally, dropping this table after all uses are removed.
___
*[pkg/sql/catalog/tabledesc/structured.go, line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77337#-MzLsLgeETasz3aPYk9f:-MzajF2p9SLAOEcEXoDZ:bs6w1gm) ([raw file](https://github.com/cockroachdb/cockroach/blob/10058c8b6fc30be9ea95e8f43ee3edd22716f004/pkg/sql/catalog/tabledesc/structured.go#L53)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

what is this and how is it different from `ClusterVersion`? 
</blockquote></details>

They're the same thing, except the immutable wrapper implements catalog.Descriptor. Would you structure this differently? Like constructing the immutable wrapper on the fly in OriginalDescriptor() itself? Something else?

```go
		ClusterVersion: *tdb.original,
		original:       makeImmutable(tdb.original),
```

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77337)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @irfansharif)

___
*[pkg/sql/catalog/tabledesc/structured.go, line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77337#-MzLsLgeETasz3aPYk9f:-Mzat0j03Ui1xR-qpI3x:b17hbri) ([raw file](https://github.com/cockroachdb/cockroach/blob/10058c8b6fc30be9ea95e8f43ee3edd22716f004/pkg/sql/catalog/tabledesc/structured.go#L53)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

They're the same thing, except the immutable wrapper implements catalog.Descriptor. Would you structure this differently? Like constructing the immutable wrapper on the fly in OriginalDescriptor() itself? Something else?

```go
		ClusterVersion: *tdb.original,
		original:       makeImmutable(tdb.original),
```
</blockquote></details>

I'd rather you just had the one. If you're sad that `ClusterVersion` is a field as opposed to a method, feel free to change it to be a method that exposes a value stored in an unexported field. I don't like having both.

**Review by irfansharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77337)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @arulajmani)

___
*[pkg/sql/catalog/tabledesc/structured.go, line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77337#-MzLsLgeETasz3aPYk9f:-Mzazzmk0OeFJNBo387C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/10058c8b6fc30be9ea95e8f43ee3edd22716f004/pkg/sql/catalog/tabledesc/structured.go#L53)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I'd rather you just had the one. If you're sad that `ClusterVersion` is a field as opposed to a method, feel free to change it to be a method that exposes a value stored in an unexported field. I don't like having both. 
</blockquote></details>

Done.

**Comment by irfansharif** [comment]
CI failure is an unrelated Google Cloud Storage flake, we've been playing around with stuff in TC I hear.

**Review by ajwerner — COMMENTED** [review]
Can you add a tenant logic test that shows the end-to-end behavior working as expected? 

> Reviewed 10 of 52 files at r1, 11 of 23 files at r2, 1 of 11 files at r4, 22 of 30 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77337#-:-MzolUma2orjlnSAeDoV:bbj5ox3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @irfansharif)

___
*[pkg/spanconfig/spanconfig.go, line 494 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77337#-MzojIJA4gTlMYh3vxje:-MzojIJB3qaetiJ_wSjx:b75ia4a) ([raw file](https://github.com/cockroachdb/cockroach/blob/54090d51f9395fd93bcea80aae2c4a447e03c80d/pkg/spanconfig/spanconfig.go#L494)):*
> ```Go
> }
> 
> func isNil(table catalog.TableDescriptor) bool {
> ```

this is upsetting, when do you find a value being returned for which the nil-check doesn't work because it's a non-nil concrete value? I guess it's the new method to return the original version? Can we fix that. I'm not cool with this sort of defensiveness creeping in. We should nil-check when dealing in concrete values before returning interfaces. I feel like we should put a linter in play to check for this. 
___
*[pkg/sql/catalog/tabledesc/structured.go, line 1014 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77337#-MzokXFP10h0y3jLCNDA:-MzokXFP10h0y3jLCNDB:b-dj66zj) ([raw file](https://github.com/cockroachdb/cockroach/blob/54090d51f9395fd93bcea80aae2c4a447e03c80d/pkg/sql/catalog/tabledesc/structured.go#L1014)):*
> ```Go
> 
> // ClusterVersion returns the version of the table descriptor read from the
> // store, if any.
> ```

Can you put a TODO with my name on it here to make this deal in `catalog.TableDescriptor`? IIRC the use of the raw struct was laziness on my part to not have to change as much code. 
___
*[pkg/sql/catalog/tabledesc/structured.go, line 1025 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77337#-MzokGO7BgVeIWfeT-fP:-MzokGO7BgVeIWfeT-fQ:bzah94o) ([raw file](https://github.com/cockroachdb/cockroach/blob/54090d51f9395fd93bcea80aae2c4a447e03c80d/pkg/sql/catalog/tabledesc/structured.go#L1025)):*
> ```Go
> // the mutations.
> func (desc *Mutable) OriginalDescriptor() catalog.Descriptor {
> 	return desc.original
> ```

let's avoid the nil value semantics by doing the following:
```go
if desc.original != nil {
    return desc.original
}
return nil
```

**Review by irfansharif — COMMENTED** [review]
> tenant logic test

Just double checking we saw the tests under `pkg/ccl/spanconfigccl/spanconfiglimiterccl/testdata/*`, they're doing what I think we'd do under a tenant logic test except with directives to re-configure the per-tenant limit dynamically. Are you asking to test something different? With the logic test framework running under a tenant, I think I'd need to introduce special commands/testing knobs to be able to re-configure the limit from the host tenant.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77337#-:-MzpE5ZE1567rUP94NDC:bfvf1si)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @arulajmani)

___
*[pkg/sql/catalog/tabledesc/structured.go, line 1025 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77337#-MzokGO7BgVeIWfeT-fP:-MzpCid3-x6usUiKVxsm:b-r00c7z) ([raw file](https://github.com/cockroachdb/cockroach/blob/54090d51f9395fd93bcea80aae2c4a447e03c80d/pkg/sql/catalog/tabledesc/structured.go#L1025)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

let's avoid the nil value semantics by doing the following:
```go
if desc.original != nil {
    return desc.original
}
return nil
```
</blockquote></details>

Done. Huh, looking at the diff I wouldn't have thought there was any behavioural difference; seems like Go footgun.

**Review by ajwerner — COMMENTED** [review]
https://github.com/cockroachdb/cockroach/issues/79426 I filed this to make it easier. 

What I'm looking for is a test that shows errors when trying to create tables or add partitioning or doing various other activities and then exercising recovery from these various scenarios. I see one test which exercises the error. It'd be good to have a test that shows that the GC job will recover some quota when it finishes. It'd be good to show that the user can, say, remove partitioning and find that that will allow it to create tables again.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77337#-:-MztwDw5-8AUxONz8mCf:brpti4b)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @irfansharif)

___
*[pkg/sql/catalog/descs/txn.go, line 262 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77337#-Mztxab758Le2ZRV5UiJ:-Mztxab758Le2ZRV5UiK:bl1ot0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/433df2effab8105936bd3c9693fab889a8ec97eb/pkg/sql/catalog/descs/txn.go#L262)):*
> ```Go
> 		}
> 		if shouldLimit {
> 			return errExceededSpanCountLimit
> ```

something, somewhere, should be putting a pgcode around this error. 
___
*[pkg/sql/catalog/tabledesc/structured.go, line 1025 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77337#-MzokGO7BgVeIWfeT-fP:-MztuHVZ9gpiEVMxGvbE:b8hdbap) ([raw file](https://github.com/cockroachdb/cockroach/blob/54090d51f9395fd93bcea80aae2c4a447e03c80d/pkg/sql/catalog/tabledesc/structured.go#L1025)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Done. Huh, looking at the diff I wouldn't have thought there was any behavioural difference; seems like Go footgun.
</blockquote></details>

This is the #**1** footgun in the language as far as I'm concerned. The mindset you need to have is that any time you see an interface, it should be thought of as a box with two values `[ptr to itable for type][ptr to value]`. With the old code, you'd be returning `[ptr to catalog.Descriptor itable for *immutable][nil]` and now you're returning `[nil][nil]`. Only the latter compares equally to `nil`. https://research.swtch.com/interfaces is worth a read every few years.

**Review by irfansharif — COMMENTED** [review]
>  It'd be good to show that the user can, say, remove partitioning and find that that will allow it to create tables again.

Added a few tests that show recovery of quota from repartitioning and dropping indexes. In writing these tests I'm running into something that feels like a bug outside of span configs. Running the following test:
```
exec-sql tenant=10
CREATE TABLE db.list_partitions(i INT PRIMARY KEY, j INT);
CREATE INDEX idx_i ON db.list_partitions (i);
CREATE INDEX idx_j ON db.list_partitions (j);
ALTER INDEX db.list_partitions@idx_i PARTITION BY LIST (i) (
  PARTITION one_and_five    VALUES IN (1, 5),
  PARTITION everything_else VALUES IN (DEFAULT)
);
```

Showed that the span count accounting only added a delta for the descriptor version between `CREATE INDEX idx_j ON db.list_partitions (j);` and `ALTER INDEX db.list_partitions@idx_i PARTITION BY LIST (i)`. Because the block above was being committed in the same txn, the "original descriptor" (which I would've expected to be nil) was one with `.GetVersion() == 1`. I'm not sure what's going on. Handling `.GetVersion() == 1` explicitly doesn't work either, since we need to distinguish between an original descriptor with version == 1 that was newly created in the current txn vs. an original descriptor with version == 1 created in a previously committed one. @ajwerner mentioned he'd play around with this repro to see if something stands out.

> It'd be good to have a test that shows that the GC job will recover some quota when it finishes.

`TestDropTableLowersSpanCount`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77337#-:-N--25Mj2g5TdWzfyfrF:b-z514wx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @arulajmani)

___
*[pkg/sql/catalog/descs/txn.go, line 262 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77337#-Mztxab758Le2ZRV5UiJ:-Mzv4uYL-H2xXLlDqHFk:b47exfe) ([raw file](https://github.com/cockroachdb/cockroach/blob/433df2effab8105936bd3c9693fab889a8ec97eb/pkg/sql/catalog/descs/txn.go#L262)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

something, somewhere, should be putting a pgcode around this error. 
</blockquote></details>

Done, just did it here (pgcode.ConfigurationLimitExceeded felt eerily appropriate).

**Review by irfansharif — COMMENTED** [review]
> In writing these tests I'm running into something that feels like a bug outside of span configs. 

Tests here work just fine after rebasing on top of #79561. I'll merge after that goes in. Is there anything outstanding in this PR?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77337#-:-N-1Iif_9fb2SrnDYqdy:b-k5f7cw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @arulajmani)

**Review by ajwerner — APPROVED** [review]
Do we have any tools to re-compute the count or to reset it manually? It'd make me feel a lot better if we did.  If there were a leak but we had an easy mitigation, that'd be nice. What is the writability of the column by `root`? What sort of access do serverless tenants have? I think ideally the table would only be writable by `node` and then we'd have a builtin or something to recompute the count by scanning all of the descriptors and another which does both a recompute and set operation, perhaps also requiring that it's a single-statement transaction. Can you file follow-up task to build something? 

Beyond that, :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77337#-:-N-4pien24x2eXx7hwyF:bmlmg1h)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @arulajmani)

**Review by irfansharif — COMMENTED** [review]
https://github.com/cockroachdb/cockroach/issues/79616, I'll bors on green. Thanks for reviewing and the speedy bug fix!

**Pull request merged**
