### PR TITLE
kvtenant: expose available regions to tenants

### PR DESCRIPTION
**Pull request by otan**
Resolves CRDB-2513

See individual commits for details.

### CODE REVIEW

**Review by ajstorm — COMMENTED** [review]
Nice!  Looks good to me, but I'm not very familiar with most of the code you've touched.  Hopefully @irfansharif and/or @arulajmani can have a look too.

> Reviewed 6 of 6 files at r1, 22 of 22 files at r2, 3 of 3 files at r3, 7 of 7 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67098#-:-Me58EpV1M4npsU-xkTw:b-srjnck)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @irfansharif, and @otan)

___
*[pkg/ccl/backupccl/testdata/backup-restore/multiregion, line 15 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67098#-Me57Kka-pTQlwSctAb5:-Me57Kka-pTQlwSctAb6:bozfl54) ([raw file](https://github.com/cockroachdb/cockroach/blob/29cafd762c866aced978260e7f02ddd10fef0e8a/pkg/ccl/backupccl/testdata/backup-restore/multiregion#L15)):*
> ```
> us-east-1
> us-west-1
> eu-central-1
> ```

Nit: hmm, why does "eu" come after "us" if we're ordering by region? :thinking:

**Comment by otan** [comment]
___
*[pkg/ccl/backupccl/testdata/backup-restore/multiregion, line 15 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67098#-Me57Kka-pTQlwSctAb5:-Me59HPY7bZ-d8hp6ZxU:b82rhvt) ([raw file](https://github.com/cockroachdb/cockroach/blob/29cafd762c866aced978260e7f02ddd10fef0e8a/pkg/ccl/backupccl/testdata/backup-restore/multiregion#L15)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: hmm, why does "eu" come after "us" if we're ordering by region? :thinking: 
</blockquote></details>

The outer select can reorder things iiuc

**Review by dhartunian — COMMENTED** [review]
> Reviewed 5 of 6 files at r1, 34 of 34 files at r6, 22 of 22 files at r7, 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67098)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @dhartunian, @irfansharif, and @otan)

___
*[pkg/server/serverpb/status.proto, line 1113 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/67098#-Me5d3t0Aq3mUdwQRVcc:-Me5d3t0Aq3mUdwQRVcd:bmdzyvd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e48819648e5c8259d793ec9db3308133d764bc37/pkg/server/serverpb/status.proto#L1113)):*
> ```protobuf
>   rpc Regions(RegionsRequest) returns (RegionsResponse) {
>     option (google.api.http) = {
>       get : "/_status/regions"
> ```

just trying to check my understanding here: we don't strictly need the http API annotation to enable this feature, right?

I think we're trying to avoid adding more HTTP endpoints under `_status` since we've moved ahead with the `v2` API tree which will eventually end up marking everything under `_status` as deprecated. maybe @itsbilal can opine.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67098)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @dhartunian, @irfansharif, and @itsbilal)

___
*[pkg/server/serverpb/status.proto, line 1113 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/67098#-Me5d3t0Aq3mUdwQRVcc:-Me6u3gL72HpIWX4Umng:bmzsngj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e48819648e5c8259d793ec9db3308133d764bc37/pkg/server/serverpb/status.proto#L1113)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

just trying to check my understanding here: we don't strictly need the http API annotation to enable this feature, right?

I think we're trying to avoid adding more HTTP endpoints under `_status` since we've moved ahead with the `v2` API tree which will eventually end up marking everything under `_status` as deprecated. maybe @itsbilal can opine.
</blockquote></details>

i've removed it, but it still shows up in the docs.

**Review by arulajmani — APPROVED** [review]
:lgtm: 

Sorry for taking so long on this, breather week and what not :)

> Reviewed 2 of 6 files at r1, 37 of 37 files at r11, 23 of 23 files at r12, 4 of 4 files at r13, 8 of 8 files at r14, 3 of 3 files at r15.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67098#-:-MeSJihVDtTHANaI4S56:byuptee)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @irfansharif, @itsbilal, and @otan)

___
*[pkg/server/status.go, line 1299 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/67098#-MeSD18n1cN2h20082Y7:-MeSD18n1cN2h20082Y8:b2k2xa1) ([raw file](https://github.com/cockroachdb/cockroach/blob/88b171181f55bbcd2a8805176a951a0cbc479c6e/pkg/server/status.go#L1299)):*
> ```Go
> 	ctx context.Context, req *serverpb.RegionsRequest,
> ) (*serverpb.RegionsResponse, error) {
> 	resp, _, err := s.nodesHelper(ctx, 0, 0)
> ```

nit: comments after constants

**Comment by otan** [comment]
thanks

bors r=arulajmani

**Pull request merged**
