### PR TITLE
sql: add user_id column to system.database_role_settings table

### PR DESCRIPTION
**Pull request by andyyang890**
This patch adds a new `role_id` column to the `system.database_role_settings`
table, which corresponds to the existing `role_name` column. Migrations are
also added to alter and backfill the table in older clusters.

Part of #87079

Release note: None

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
looks good overall! i just had one comment about using a STORING index

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97251#-:-NOz-3kU6IWrfSyCQ2Xl:b-lrjbld)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890)

___
*[`pkg/upgrade/upgrades/database_role_settings_table_user_id_migration.go` line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97251#-NOyzh036vXq9a_kXGTP:-NOyzh036vXq9a_kXGTQ:b-szra15) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7da5592802d3876cf781fc801a7000b7327be81/pkg/upgrade/upgrades/database_role_settings_table_user_id_migration.go#L31)):*
> ```Go
> const createUniqueIndexOnDatabaseIDAndRoleIDOnDatabaseRoleSettingsTableStmt = `
> CREATE UNIQUE INDEX IF NOT EXISTS database_role_settings_database_id_role_id_key
> ON system.database_role_settings (database_id, role_id)
> ```

similar to system.privileges, i think this would benefit from having `STORING (settings)` on it. (if you look at the query where the table is accessed, it always needs to fetch the settings column)

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97251)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/upgrade/upgrades/database_role_settings_table_user_id_migration.go` line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97251#-NOyzh036vXq9a_kXGTP:-NP-ceVq2JISTUFmv8BJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7da5592802d3876cf781fc801a7000b7327be81/pkg/upgrade/upgrades/database_role_settings_table_user_id_migration.go#L31)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

similar to system.privileges, i think this would benefit from having `STORING (settings)` on it. (if you look at the query where the table is accessed, it always needs to fetch the settings column)
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97251#-:-NP3AN_L4i-yLT-lQEaN:b-7nbn20)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by andyyang890** [comment]
TFTR!

bors r=rafiss

**Pull request merged**
