### PR TITLE
release-21.2: sql: clean up large row errors and events

### PR DESCRIPTION
**Pull request by michae2**
Backport 1/1 commits from #70102.

/cc @cockroachdb/release

---

Addresses: #67400, #69477

Remove ViolatesMaxRowSizeErr from CommonLargeRowDetails, as was done
for CommonTxnRowsLimitDetails in #69945.

Also remove the SafeDetails methods from CommonLargeRowDetails,
txnRowsReadLimitErr, and txnRowsWrittenLimitErr, as I don't think we
need them.

Release justification: low-risk update to new functionality.

Release note: None (there was no release between the introduction of the
LargeRow and LargeRowInternal events and this commit).

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70157)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Comment by yuzefovich** [comment]
@knz @rytaft do you think it is justifiable to treat #69477 as a beta release-blocker and, as a result, to merge this? I'm leaning towards treating #69477 as a GA-blocker, so I'd merge this once beta is out.

**Comment by knz** [comment]
agreed with your analysis

**Comment by rytaft** [comment]
Agree, seems like GA-blocker. In which case it can wait till we get approval to merge on Monday.

**Review by knz — APPROVED** [review]

**Review by rytaft — APPROVED** [review]
:lgtm:

You can go ahead and merge this

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70157#-:-Mk2qFKB3nMl_DWZKlLZ:b-8tlvcs)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2)

**Comment by michae2** [comment]
TFTRs! Merging.

**Pull request merged**
