### PR TITLE
sql: add "partial" label to formatted scans in EXPLAIN and EXPLAIN (opt)

### LINKED ISSUE #50233: opt: scan expr format should denote when the scan is over a partial index
This will make it easier to debug issues related to partial indexes in the future.

### PR DESCRIPTION
**Pull request by mgartner**
This commit adds a "partial" label when formatting scans over partial
indexes for both the standard `EXPLAIN` and the `EXPLAIN (opt)`
statements. This helps make it immediately obvious that the scan is
operating on a partial index, and may aid in future debugging.

Fixes #50233 

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
It would be good to add the same in the regular EXPLAIN (here: https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/walk.go#L184); the scanNode already has direct access to the index descriptor, so you don't need to plumb anything.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50279#-:-M9xomA211FU7WNI9QJO:b-yj0trj)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50279#-:-M9yF_07EvoknLyMnryb:b-g2a5fb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/walk.go, line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50279#-M9yFJ1ED4P2EvGtmQ4z:-M9yFJ1ED4P2EvGtmQ5-:bc27chd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b98586fbb472ef361c0e272906ec19db55506c47/pkg/sql/walk.go#L188)):*
> ```Go
> 			}
> 			if n.index.IsPartial() {
> 				v.observer.attr(name, "partial", "true")
> ```

Let's make this `"partial index", ""` (just partial is too ambiguous, and we don't need true or false if it only shows up when true, similar to "parallel" above).

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50279)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/walk.go, line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50279#-M9yFJ1ED4P2EvGtmQ4z:-M9yKLoTDFoFoVxVqRes:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b98586fbb472ef361c0e272906ec19db55506c47/pkg/sql/walk.go#L188)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Let's make this `"partial index", ""` (just partial is too ambiguous, and we don't need true or false if it only shows up when true, similar to "parallel" above).
</blockquote></details>

Done.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50279#-:-M9yrAeb0KHAhxdxOiNn:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
