### PR TITLE
multitenantccl/tenantcostserver: deflake TestDataDriven

### LINKED ISSUE #93462: multitenantccl: leaked goroutine in `TestDataDriven/cleanup`
```
--- FAIL: TestDataDriven (5.52s)
    test_log_scope.go:161: test logs captured to: /Users/rc/src/go/src/github.com/cockroachdb/cockroach/tmp/_tmp/50e33444d6d65b5a0bf1480b8c91c2a1/logTes
tDataDriven1245022510
    test_log_scope.go:79: use -show-logs to present logs inline
    --- FAIL: TestDataDriven/cleanup (5.50s)
        server_test.go:60: Leaked goroutine: goroutine 13 [select]:
            github.com/cockroachdb/cockroach/pkg/util/log.(*fileSink).gcDaemon(0x14000cbe8f0, {0x104f17750, 0x1400076cec0})
                github.com/cockroachdb/cockroach/pkg/util/log/file_log_gc.go:25 +0x70
            created by github.com/cockroachdb/cockroach/pkg/util/log.ApplyConfig
                github.com/cockroachdb/cockroach/pkg/util/log/flags.go:306 +0xdc8
            Leaked goroutine: goroutine 14 [select]:
            github.com/cockroachdb/cockroach/pkg/util/log.(*fileSink).gcDaemon(0x14000cbe9c0, {0x104f17750, 0x1400076cec0})
                github.com/cockroachdb/cockroach/pkg/util/log/file_log_gc.go:25 +0x70
            created by github.com/cockroachdb/cockroach/pkg/util/log.ApplyConfig
                github.com/cockroachdb/cockroach/pkg/util/log/flags.go:306 +0xdc8
            Leaked goroutine: goroutine 15 [select]:
            github.com/cockroachdb/cockroach/pkg/util/log.(*fileSink).gcDaemon(0x14000cbea90, {0x104f17750, 0x1400076cec0})
                github.com/cockroachdb/cockroach/pkg/util/log/file_log_gc.go:25 +0x70
            created by github.com/cockroachdb/cockroach/pkg/util/log.ApplyConfig
                github.com/cockroachdb/cockroach/pkg/util/log/flags.go:306 +0xdc8
            Leaked goroutine: goroutine 16 [select]:
            github.com/cockroachdb/cockroach/pkg/util/log.(*fileSink).gcDaemon(0x14000cbeb60, {0x104f17750, 0x1400076cec0})
                github.com/cockroachdb/cockroach/pkg/util/log/file_log_gc.go:25 +0x70
            created by github.com/cockroachdb/cockroach/pkg/util/log.ApplyConfig
                github.com/cockroachdb/cockroach/pkg/util/log/flags.go:306 +0xdc8
    server_test.go:61: -- test log scope end --
```

Problem is reproducible in a few seconds by stressing this test on `master`.

Jira issue: CRDB-22348

### PR DESCRIPTION
**Pull request by ajwerner**
Fixes #93462

The scope for the outer test instead of per file subtest was creating problems for leaktest.

Release note: None

### CODE REVIEW

**Comment by renatolabs** [comment]
Thanks!

To keep things documented (aka, I don't understand the fix): why is this the fix? I see other datadriven tests where the `log.Scope(t).Close(t)` call is outside the function passed to `Walk`, and that doesn't seem to cause problems. Moreover, this test hasn't really changed much recently.

I also started a bisection when I filed the issue, and apparently #92930 made this test flaky.

**Comment by ajwerner** [comment]
From what I could tell, the goroutines were logging goroutines which get launched from here:
https://github.com/cockroachdb/cockroach/blob/4640c585e7098c53ccc69f6096e8087b6d6007fd/pkg/util/log/flags.go#L91

The way that `leaktest` works is that it makes sure that all goroutines which exist after the test are done existed before it started. The race here was that we launched these goroutines under `log.Scope` ([here](https://github.com/cockroachdb/cockroach/blob/4640c585e7098c53ccc69f6096e8087b6d6007fd/pkg/util/log/flags.go#L203)) but they had not yet started by the time leaktest picked its snapshot. So, by choosing to not start the logging goroutines until after leaktest picks its snapshot, we remove the hazard of the async goroutines having not yet started.

**Review by renatolabs — APPROVED** [review]
Thanks!

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Pull request merged**
