### PR TITLE
workload: add scaleStats flag

### LINKED ISSUE #97983: workloads: add ability to scale stats for insights workload
There currently isn't an easy way to generate a large number of statistics. An option should be added to the insights workload to generate a large number to help test and validate everything works at scale.

### PR DESCRIPTION
**Pull request by j82w**
1. Add `scaleStats` option. 2 threads will do the normal insights queries that cause issues like contention. The remaining threads will do a basic
query and change the app name before each call. This will generate a large number of unique stat that will hit the limit in a few minutes.

2. Remove the database flag. Use the more optimal `crdb_internal.generate_test_objects`
instead. It can generate dbs faster if trying to
test scalability with dbs.

Example:
`./cockroach workload run insights 'postgresql://root@127.0.0.1:26257/insights?sslmode=disable'  --scaleStats`

Epic: none
Closes: https://github.com/cockroachdb/cockroach/issues/97983

Release note: None

### CODE REVIEW

**Review by ericharmeling — COMMENTED** [review]
Nice!

I had a nit/question re: the visibility of the workload and docs.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97982#-:-NPdBHV010bvcnxMn3-a:b-bcb0vn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w, @renatolabs, and @srosenberg)

___
*[`-- commits` line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97982#-NPd93a14w0TzZ1MlZ1w):*
No release note?

Related comment/question: if we don't have a release note for changes to this workload's flags (and if we don't have external user documentation in general for this workload), should we consider moving it out of the workloads built in the cockroach target (https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/cli.go#L38), so it just gets built with `workload` binary (like the `sqlsmith` one and others)?



_Code quote:_
```
 Release note: None
```

**Comment by j82w** [comment]
*[`-- commits` line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97982#-NPd93a14w0TzZ1MlZ1w):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

No release note?

Related comment/question: if we don't have a release note for changes to this workload's flags (and if we don't have external user documentation in general for this workload), should we consider moving it out of the workloads built in the cockroach target (https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/cli.go#L38), so it just gets built with `workload` binary (like the `sqlsmith` one and others)?
</blockquote></details>

I can add the release note. I just didn't think it was worth adding it since it's only a workload, and not part of the core CRDB product. It was put in workloads so sales could demo insights. I think you are correct that when we add ui e2e tests we should look into a way generating a lot of data to verify the page loads with in a certain time.

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97982#-:-NQBC0Gz95QiwaMtNUwZ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling, @renatolabs, and @srosenberg)

**Pull request merged**
