### PR TITLE
jobs,sql: introduce SHOW JOB...WITH EXECUTION DETAILS

### PR DESCRIPTION
**Pull request by adityamaru**
This change introduces a new option to the SHOW JOB and SHOW JOBS statements. By specifying `WITH EXECUTION DETAILS` users can render additional observability information about a job that is collected during the job's lifetime. Currently, the only piece of information is the URL to the latest DistSQL plan being run by the job. Going forward `EXECUTION DETAILS` is expected to be a relatively expensive operation that will scan select rows of the job_info table as determined by a specific job type.

The SHOW JOB query delegates to crdb_internal.job_execution_details that renders a JSONB of all the execution details collected over the lifetime of the job.

Release note: None
Informs: #101743
Epic: CRDB-8964

### CODE REVIEW

**Comment by adityamaru** [comment]
Screenshot 2023-04-16 at 9 23 08 AM

**Review by miretskiy — APPROVED** [review]
> Reviewed 27 of 27 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101607)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @yuzefovich)

___
*[`pkg/jobs/jobsprofiler/profiler.go` line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101607#-NT9DX0T73gxa_a13xl8:-NT9DX0T73gxa_a13xl9:bhj4rq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/59c0d51743898ae57d2472c474acf5d838ef7846/pkg/jobs/jobsprofiler/profiler.go#L65)):*
> ```Go
> 
> // TestingCheckForPlanDiagram is a method used in tests to check the existence
> // of a DSP diagram for jobID.
> ```

nit: it's not much of a "check" method, but more of a Wait method?
___
*[`pkg/jobs/jobsprofiler/profilerconstants/constants.go` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101607#-NT9DxrwCHiwsMODrLX1:-NT9DxrwCHiwsMODrLX2:b-vpg9aa) ([raw file](https://github.com/cockroachdb/cockroach/blob/59c0d51743898ae57d2472c474acf5d838ef7846/pkg/jobs/jobsprofiler/profilerconstants/constants.go#L12)):*
> ```Go
> 
> package profilerconstants
> ```

let's comment exported constants?
___
*[`pkg/jobs/jobsprofiler/profilerconstants/constants.go` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101607#-NT9Dzkp43YljXahUYav:-NT9Dzkp43YljXahUYaw:bnnv3uw) ([raw file](https://github.com/cockroachdb/cockroach/blob/59c0d51743898ae57d2472c474acf5d838ef7846/pkg/jobs/jobsprofiler/profilerconstants/constants.go#L13)):*
> ```Go
> package profilerconstants
> 
> const DSPDiagramInfoKeyPrefix = "dsp-diag-url-"
> ```

Probably for the future... It would be nice not to have the caller be responsible for
joining this prefix.  Would be nice to have a "Key" interface... something
like

```
type Key interface {
   MakeKey(parts ...string) string
}
```
and not expose these prefixes at all...
___
*[`pkg/sql/jobs_execution_details.go` line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101607#-NT9FvDQC8NBQ_C3DyOj:-NT9FvDQC8NBQ_C3DyOk:b-7isyom) ([raw file](https://github.com/cockroachdb/cockroach/blob/59c0d51743898ae57d2472c474acf5d838ef7846/pkg/sql/jobs_execution_details.go#L74)):*
> ```Go
> 	}
> 	j, err := gojson.Marshal(executionDetails)
> 	return string(j), err
> ```

return []byte?
___
*[`pkg/sql/row/expr_walker.go` line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101607#-NT9GK0S8laAJZq8qDXW:-NT9GK0S8laAJZq8qDXX:bb7r2f0) ([raw file](https://github.com/cockroachdb/cockroach/blob/59c0d51743898ae57d2472c474acf5d838ef7846/pkg/sql/row/expr_walker.go#L29)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/sql/pgwire/pgcode"
> 	"github.com/cockroachdb/cockroach/pkg/sql/pgwire/pgerror"
> 	_ "github.com/cockroachdb/cockroach/pkg/sql/sem/builtins"
> ```

why?
___
*[`pkg/sql/sem/eval/context.go` line 277 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101607#-NT9GnWV6x1XDiJD46lb:-NT9GnWV6x1XDiJD46lc:bbzwl1y) ([raw file](https://github.com/cockroachdb/cockroach/blob/59c0d51743898ae57d2472c474acf5d838ef7846/pkg/sql/sem/eval/context.go#L277)):*
> ```Go
> 	// GenerateExecutionDetailsJSON generates a JSON blob of the job specific
> 	// execution details.
> 	GenerateExecutionDetailsJSON(context.Context, *Context, jobspb.JobID) (string, error)
> ```

what's better than a context? Two context of course :)

Let's give args some names cause things are already confusing.
___
*[`pkg/testutils/jobutils/jobs_verification.go` line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101607#-NT9H0sF7y3tBSYFwUQ9:-NT9H0sF7y3tBSYFwUQA:bgmlj4j) ([raw file](https://github.com/cockroachdb/cockroach/blob/59c0d51743898ae57d2472c474acf5d838ef7846/pkg/testutils/jobutils/jobs_verification.go#L156)):*
> ```Go
> 			switch r := ru.GetInner().(type) {
> 			case *kvpb.ExportResponse, *kvpb.AddSSTableResponse:
> 				log.Infof(context.Background(), "received a response %s", r.String())
> ```

stray log line?
___
*[`pkg/sql/jobs_execution_details_test.go` line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101607#-NT9H7pf4hw3NNjX2_e5:-NT9H7pf4hw3NNjX2_e6:b-ckajiq) ([raw file](https://github.com/cockroachdb/cockroach/blob/59c0d51743898ae57d2472c474acf5d838ef7846/pkg/sql/jobs_execution_details_test.go#L64)):*
> ```Go
> 	runner.Exec(t, `INSERT INTO t SELECT generate_series(1, 100)`)
> 	var backupJobID int
> 	runner.QueryRow(t, `BACKUP TABLE t INTO 'userfile:///foo' WITH detached`).Scan(&backupJobID)
> ```

do we have to run backups? 
Would it make sense to write a "fake resumer" just to write a plan, and then check its existence?
We are not testing backup functionality here, so running backup seems a bit too heavy?
___
*[`pkg/sql/jobs_execution_details_test.go` line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101607#-NT9HJ8541fS-TlQob5b:-NT9HJ8541fS-TlQob5c:b-p3pkak) ([raw file](https://github.com/cockroachdb/cockroach/blob/59c0d51743898ae57d2472c474acf5d838ef7846/pkg/sql/jobs_execution_details_test.go#L86)):*
> ```Go
> 	})
> 
> 	t.Run("SHOW JOBS", func(t *testing.T) {
> ```

what's the difference between this test and the previous one name the same way?

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101607)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @yuzefovich)

___
*[`pkg/jobs/jobsprofiler/profilerconstants/constants.go` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101607#-NT9DxrwCHiwsMODrLX1:-NTBMb2MCw1FY1kwlaBe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/59c0d51743898ae57d2472c474acf5d838ef7846/pkg/jobs/jobsprofiler/profilerconstants/constants.go#L12)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

let's comment exported constants?
</blockquote></details>

Done.
___
*[`pkg/jobs/jobsprofiler/profilerconstants/constants.go` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101607#-NT9Dzkp43YljXahUYav:-NTBMbdP4oB97eYZlzYf:b-gqoef) ([raw file](https://github.com/cockroachdb/cockroach/blob/59c0d51743898ae57d2472c474acf5d838ef7846/pkg/jobs/jobsprofiler/profilerconstants/constants.go#L13)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Probably for the future... It would be nice not to have the caller be responsible for
joining this prefix.  Would be nice to have a "Key" interface... something
like

```
type Key interface {
   MakeKey(parts ...string) string
}
```
and not expose these prefixes at all...

</blockquote></details>

yeah i agree, i think as we add more info key types we need to tighten up the interface to interact with these keys
___
*[`pkg/sql/jobs_execution_details.go` line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101607#-NT9FvDQC8NBQ_C3DyOj:-NTBN1qRA2pKeHbd6zQ4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/59c0d51743898ae57d2472c474acf5d838ef7846/pkg/sql/jobs_execution_details.go#L74)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

return []byte?
</blockquote></details>

Done.
___
*[`pkg/sql/sem/eval/context.go` line 277 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101607#-NT9GnWV6x1XDiJD46lb:-NTBND53AVZzmiOXFFzG:b-7rl0jq) ([raw file](https://github.com/cockroachdb/cockroach/blob/59c0d51743898ae57d2472c474acf5d838ef7846/pkg/sql/sem/eval/context.go#L277)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

what's better than a context? Two context of course :)

Let's give args some names cause things are already confusing.
</blockquote></details>

done!
___
*[`pkg/sql/jobs_execution_details_test.go` line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101607#-NT9H7pf4hw3NNjX2_e5:-NTBNExw0hH-zueSXjde:b-i54b0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/59c0d51743898ae57d2472c474acf5d838ef7846/pkg/sql/jobs_execution_details_test.go#L64)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

do we have to run backups? 
Would it make sense to write a "fake resumer" just to write a plan, and then check its existence?
We are not testing backup functionality here, so running backup seems a bit too heavy?
</blockquote></details>

good point, changed to a fake resumer and deleted the testing knob too.
___
*[`pkg/sql/jobs_execution_details_test.go` line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101607#-NT9HJ8541fS-TlQob5b:-NTBNgqc7Q_MpuQv66v2:b-va9ca7) ([raw file](https://github.com/cockroachdb/cockroach/blob/59c0d51743898ae57d2472c474acf5d838ef7846/pkg/sql/jobs_execution_details_test.go#L86)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

what's the difference between this test and the previous one name the same way?
</blockquote></details>

One is `SHOW JOB` and the other is `SHOW JOBS`. I deleted the `t.Runs` though cause they felt unnecessary once I cleaned up the test using a fake resumer.
___
*[`pkg/sql/row/expr_walker.go` line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101607#-NT9GK0S8laAJZq8qDXW:-NTBN2X0Ej4PN1yNFMZP:b-frd7fx) ([raw file](https://github.com/cockroachdb/cockroach/blob/59c0d51743898ae57d2472c474acf5d838ef7846/pkg/sql/row/expr_walker.go#L29)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

why?
</blockquote></details>

Sorry, leftover from a previous commit I had cherrypicked from https://github.com/cockroachdb/cockroach/pull/101495 but didn't end up needing it.
___
*[`pkg/testutils/jobutils/jobs_verification.go` line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101607#-NT9H0sF7y3tBSYFwUQ9:-NTBNEKTEk9P061hnqdS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/59c0d51743898ae57d2472c474acf5d838ef7846/pkg/testutils/jobutils/jobs_verification.go#L156)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

stray log line?
</blockquote></details>

Done.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 13 of 27 files at r1, 17 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101607)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @miretskiy)

___
*[`pkg/jobs/jobsprofiler/profiler.go` line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101607#-NTKRezs-6m9gb2lcrdm:-NTKRezs-6m9gb2lcrdn:b-7ekb2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/55fe4b72abbaa81b9094071ea878fbcb3ad8c7b3/pkg/jobs/jobsprofiler/profiler.go#L66)):*
> ```Go
> // TestingCheckForPlanDiagram is a method used in tests to wait for the
> // existence of a DSP diagram for the provided jobID.
> func TestingCheckForPlanDiagram(ctx context.Context, t *testing.T, db isql.DB, jobID jobspb.JobID) {
> ```

nit: does this need to live in the non-test package? It doesn't look like it's using any of the unexported things from `jobsprofiler` package.
___
*[`pkg/sql/parser/sql.y` line 7800 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101607#-NTKTE0C1jN7LLhvoeHM:-NTKTE0C1jN7LLhvoeHN:b-v2c7sp) ([raw file](https://github.com/cockroachdb/cockroach/blob/55fe4b72abbaa81b9094071ea878fbcb3ad8c7b3/pkg/sql/parser/sql.y#L7800)):*
> ```Yacc
> | QUERIES
> 
> // %Help: SHOW JOBS - list background jobs
> ```

nit: should we include new syntax options here?
___
*[`pkg/sql/sem/builtins/builtins.go` line 4111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101607#-NTKTJwj6ULk45DReJ3b:-NTKTJwj6ULk45DReJ3c:b-2attvj) ([raw file](https://github.com/cockroachdb/cockroach/blob/55fe4b72abbaa81b9094071ea878fbcb3ad8c7b3/pkg/sql/sem/builtins/builtins.go#L4111)):*
> ```Go
> 			ReturnType: tree.FixedReturnType(types.Jsonb),
> 			Fn: func(ctx context.Context, evalCtx *eval.Context, args tree.Datums) (tree.Datum, error) {
> 				jobID := tree.MustBeDInt(args[0])
> ```

nit: check for `args[0] != tree.DNull`.
___
*[`pkg/sql/jobs_execution_details_test.go` line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101607#-NTKThn0CKObbRzsOvgd:-NTKThn0CKObbRzsOvge:bqgqgmc) ([raw file](https://github.com/cockroachdb/cockroach/blob/55fe4b72abbaa81b9094071ea878fbcb3ad8c7b3/pkg/sql/jobs_execution_details_test.go#L37)):*
> ```Go
> )
> 
> // FakeResumer calls optional callbacks during the job lifecycle.
> ```

nit: `s/FakeResumer/fakeExecResumer/g`.

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101607)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @yuzefovich)

___
*[`pkg/jobs/jobsprofiler/profiler.go` line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101607#-NTKRezs-6m9gb2lcrdm:-NTUvumBDAhSeWTq3f7p:bsoqi0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/55fe4b72abbaa81b9094071ea878fbcb3ad8c7b3/pkg/jobs/jobsprofiler/profiler.go#L66)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: does this need to live in the non-test package? It doesn't look like it's using any of the unexported things from `jobsprofiler` package.
</blockquote></details>

good point, no reason. Moved it to the test file where the test is written.



_Code quote:_
```Go
TestingCheckForPlanDiagram
```

**Comment by adityamaru** [comment]
Reviewable is being weird but I addressed all your comments Yahor

**Comment by adityamaru** [comment]
TFTR!

bors r=miretskiy

**Pull request merged**
