### PR TITLE
[wip,dnm,dnr] kvserver,kvcoord: batch txn heartbeats

### PR DESCRIPTION
**Pull request by irfansharif**
See #45013. Picking up from #52705 left off.

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
Exciting to see this! I'm wondering whether we can get this in a good enough state to try it out briefly on some of @aayushshah15's upcoming large-scale TPC-C tests next week. It would be interesting to see how much further we can push TPC-C now that the system won't collapse after txn latencies exceed 1s.

> Reviewed 24 of 24 files at r1, 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54263#-:-MGxzl1o5BsxZG0A418Z:b-9cwb6g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif)

___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender_factory.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54263#-MGxw_S5CL1NYk-Hefb9:-MGxw_S6DJEHfTK8BL4s:b-8jskb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cbd57bfcdcc60e06c657d10b6356bf50e5748d0/pkg/kv/kvclient/kvcoord/txn_coord_sender_factory.go#L29)):*
> ```Go
> 
> // TxnHeartbeatBatcher XXX:
> type TxnHeartbeatBatcher struct {
> ```

nit: I'd move this to a separate file.
___
*[pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go, line 299 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54263#-MGxwiC0DsAmAEOtGRbh:-MGxwiC0DsAmAEOtGRbi:b-skruem) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cbd57bfcdcc60e06c657d10b6356bf50e5748d0/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go#L299)):*
> ```Go
> 
> 	log.VEvent(ctx, 2, "heartbeat")
> 	rangeCacheEntry, err := h.heartbeatBatcher.rdc.Lookup(ctx, txn.Key)
> ```

It still seems to me like this should be hidden within a method on the `TxnHeartbeatBatcher`, along the lines of what's mentioned in https://github.com/cockroachdb/cockroach/issues/52415#issuecomment-675091585. Are there downsides to doing this?

Looking at this again, the method could be even cleaner and look something like: `func (*txnHeartbeatBatcher) Send(ctx context.Context, txn *roachpb.Transaction) (*roachpb.Transaction, *roachpb.Error)`. In other words, you could hide the Request/Response objects entirely. I think that would require you to give the batcher a clock, but that seems fine.
___
*[pkg/kv/kvclient/kvcoord/txn_lock_gatekeeper.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54263#-MGxxn5Y0RXFwlcYSawT:-MGxxn5Y0RXFwlcYSawU:b6i8m5h) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cbd57bfcdcc60e06c657d10b6356bf50e5748d0/pkg/kv/kvclient/kvcoord/txn_lock_gatekeeper.go#L86)):*
> ```Go
> 	gs.mu.Unlock()
> 	defer gs.mu.Lock()
> ```

nit: stray line
___
*[pkg/kv/kvserver/batcheval/cmd_heartbeat_txn.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54263#-MGxxuzN2MBwMCMeUS41:-MGxxuzN2MBwMCMeUS42:bwg8e7b) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cbd57bfcdcc60e06c657d10b6356bf50e5748d0/pkg/kv/kvserver/batcheval/cmd_heartbeat_txn.go#L49)):*
> ```Go
> 	reply := resp.(*roachpb.HeartbeatTxnResponse)
> 
> 	if err := VerifyTransaction(args.Txn, args, roachpb.PENDING, roachpb.STAGING); err != nil {
> ```

I'm sure you're aware, but there are likely some migration concerns we'll need to work out to introduce this.
___
*[pkg/kv/kvserver/batcheval/cmd_heartbeat_txn.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54263#-MGxy26LDzEyahRGSV11:-MGxy26LDzEyahRGSV12:bz45igm) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cbd57bfcdcc60e06c657d10b6356bf50e5748d0/pkg/kv/kvserver/batcheval/cmd_heartbeat_txn.go#L50)):*
> ```Go
> 
> 	if err := VerifyTransaction(args.Txn, args, roachpb.PENDING, roachpb.STAGING); err != nil {
> 		reply.Txn = args.Txn
> ```

Shouldn't we be setting errors here? Actually, it should be ok to fail the entire batch in cases of malformed input or problems reading from disk. We just don't want to do so for semantic errors about the state of the transactions like `TransactionAbortedErrors`.
___
*[pkg/kv/kvserver/batcheval/cmd_heartbeat_txn.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54263#-MGxybYM-tgxVx4Yviat:-MGxybYM-tgxVx4Yviau:b-cfesf0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cbd57bfcdcc60e06c657d10b6356bf50e5748d0/pkg/kv/kvserver/batcheval/cmd_heartbeat_txn.go#L78)):*
> ```Go
> 			// to the reply
> 			txn.Status = roachpb.ABORTED
> 			reply.Txn = &txn
> ```

I think we might need to introduce a new field on the `HeartbeatTxnResponse` instead of using the Txn in the `ResponseHeader`. That field seems to have weird behavior because it's used to set the `BatchResponse_Header.Txn` and is then unset after doing so in `evaluateBatch`. I guess we only reach that logic when the entire batch has a transaction set, but that seems fragile to rely upon.

Adding a separate txn field in the response has plenty of precedent. See `QueryTxnResponse`, `RecoverTxnResponse`, `PushTxnResponse`, etc.

**Comment by irfansharif** [comment]
Yup, I'm also hoping to shape this up better for our TPC-C runs. There are still a few rough edges in this branch (I haven't really changed much yet), so I'd hold off looking further until I'm able to clean it up a bit more. I think we're missing something with our error handling, and like you mentioned, the migration story will need ironing out.

**Comment by irfansharif** [comment]
Still need to do a bit of clean up here, and add tests + saner migrations. I'm going to punt it off to a friday again. @aayushshah15, if the intention with your experiments was to measure our 20.2 improvements, just wanted to give the heads up that this patch will not be backported there. I'd still be interested to actually measure the effect of heartbeat batching in our higher warehouse count runs, but I suspect they'll not get included in the marketing materials we generate from your runs. I was planning on benchmarking separately anyway, so I'll post back here when I do.

**Comment by aayushshah15** [comment]
SG, then we'll just do a run with txn heartbeats disabled entirely.

**Comment by irfansharif** [comment]
This PR has slowly died out of neglect. The original optimization is worth doing, but probably from scratch -- things have changed enough where I doubt anything here is salvageable.

**Pull request closed without merging**
