### PR TITLE
cli: support --experimental-shared-storage flag with debug pebble

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### go.mod: bump Pebble to c803105f8463

c803105f tool: add db io-bench command
95450180 sstable: optimize NewReadHandle allocations

Release note: None
Epic: none

#### cli: support --experimental-shared-storage flag with debug pebble

Epic: none
Release note: None

### CODE REVIEW

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102295#-:-NTzQTjN7CtDLPf2Y8oC:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @RaduBerinde)

___
*[`pkg/storage/shared_storage.go` line 84 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102295#-NTzQPtUAbtkwLKBj-xa:-NTzQPtUAbtkwLKBj-xb:b6bz52d) ([raw file](https://github.com/cockroachdb/cockroach/blob/53a7ca1c7f6a104af9a6b45953df2bf933e1f197/pkg/storage/shared_storage.go#L84)):*
> ```Go
> 
> // MakeExternalStorageWrapper returns a shared.Storage implementation that uses
> // wraps cloud.ExternalStorage.
> ```

nit: "uses wraps"

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102295#-:-NTzWZGV4bJfUiE2LTRh:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal and @jbowens)

**Pull request merged**
