### PR TITLE
util/mon: mark monitor name and stack trace as safe from redacting

### PR DESCRIPTION
**Pull request by yuzefovich**
Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Ran into this info being redacted in https://github.com/cockroachlabs/support/issues/1481.

**Review by michae2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-:-Mys-Hu-6EChGq2ilpcs:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

**Review by knz — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78352)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/util/mon/bytes_usage.go, line 299 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-Mys0Vjq7Sr5N4_eL_3Q:-Mys0Vjq7Sr5N4_eL_3R:b-ucydwm) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad964b08ecdff007b1bd022ba9ff69da44f7686/pkg/util/mon/bytes_usage.go#L299)):*
> ```Go
> 	}
> 	m := &BytesMonitor{
> 		name:                 redact.SafeString(name),
> ```

That's not safe. Either make the function argument a redact.SafeString (or RedactableString) or use redact.Sprint here.
___
*[pkg/util/mon/bytes_usage.go, line 378 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-Mys0cL46_NN8vCXZ3gJ:-Mys0cL46_NN8vCXZ3gK:bsop33g) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad964b08ecdff007b1bd022ba9ff69da44f7686/pkg/util/mon/bytes_usage.go#L378)):*
> ```Go
> ) *BytesMonitor {
> 	if log.V(2) {
> 		log.InfofDepth(ctx, 1, "%s: starting unlimited monitor", redact.SafeString(name))
> ```

not needed if the constructor takes a redact.SafeString or RedactableString.
___
*[pkg/util/mon/bytes_usage.go, line 762 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-Mys0hfd-DQElhaqEGFA:-Mys0hfd-DQElhaqEGFB:bl5umo1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad964b08ecdff007b1bd022ba9ff69da44f7686/pkg/util/mon/bytes_usage.go#L762)):*
> ```Go
> 				log.Infof(ctx, "%s: bytes usage increases to %s (+%d)",
> 					mm.name,
> 					humanizeutil.IBytes(mm.mu.curAllocated), redact.SafeInt(x))
> ```

ints should already be safe for reporting. Are they not? How come they are not?
___
*[pkg/util/mon/bytes_usage.go, line 771 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-Mys0phOE2hBKU2v15SL:-Mys0phOE2hBKU2v15SM:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad964b08ecdff007b1bd022ba9ff69da44f7686/pkg/util/mon/bytes_usage.go#L771)):*
> ```Go
> 		// trace string if there is nothing to log.
> 		log.Infof(ctx, "%s: now at %d bytes (+%d) - %s",
> 			mm.name, redact.SafeInt(mm.mu.curAllocated), redact.SafeInt(x),
> ```

ditto
___
*[pkg/util/mon/bytes_usage.go, line 772 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-Mys0ltV3T7-V0E5F8xJ:-Mys0ltV3T7-V0E5F8xK:b-n773le) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad964b08ecdff007b1bd022ba9ff69da44f7686/pkg/util/mon/bytes_usage.go#L772)):*
> ```Go
> 		log.Infof(ctx, "%s: now at %d bytes (+%d) - %s",
> 			mm.name, redact.SafeInt(mm.mu.curAllocated), redact.SafeInt(x),
> 			redact.SafeString(util.GetSmallTrace(3)),
> ```

ideally we'd make GetSmallTrace a RedactableString (or SafeString) and call it a day for all callers.
___
*[pkg/util/mon/bytes_usage.go, line 800 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-Mys0qQc3PQEKbxPcJ3K:-Mys0qQc3PQEKbxPcJ3L:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad964b08ecdff007b1bd022ba9ff69da44f7686/pkg/util/mon/bytes_usage.go#L800)):*
> ```Go
> 		log.Infof(ctx, "%s: now at %d bytes (-%d) - %s",
> 			mm.name, redact.SafeInt(mm.mu.curAllocated), redact.SafeInt(sz),
> 			redact.SafeString(util.GetSmallTrace(5)),
> ```

ditto
___
*[pkg/util/mon/bytes_usage.go, line 819 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-Mys0rPEEbGVSTi1IWp5:-Mys0rPEEbGVSTi1IWp6:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad964b08ecdff007b1bd022ba9ff69da44f7686/pkg/util/mon/bytes_usage.go#L819)):*
> ```Go
> 		log.Infof(
> 			ctx, "%s: requesting %d bytes from the pool",
> 			mm.name, redact.SafeInt(minExtra),
> ```

ditto
___
*[pkg/util/mon/bytes_usage.go, line 846 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-Mys0rvG-HXMK_GPOrlD:-Mys0rvG-HXMK_GPOrlE:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad964b08ecdff007b1bd022ba9ff69da44f7686/pkg/util/mon/bytes_usage.go#L846)):*
> ```Go
> 		log.Infof(
> 			ctx, "%s: releasing %d bytes to the pool",
> 			mm.name, redact.SafeInt(mm.mu.curBudget.allocated()),
> ```

ditto

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78352)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz)

___
*[pkg/util/mon/bytes_usage.go, line 299 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-Mys0Vjq7Sr5N4_eL_3Q:-MyseZAcD6tc47VJvx6R:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad964b08ecdff007b1bd022ba9ff69da44f7686/pkg/util/mon/bytes_usage.go#L299)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

That's not safe. Either make the function argument a redact.SafeString (or RedactableString) or use redact.Sprint here.
</blockquote></details>

Done.
___
*[pkg/util/mon/bytes_usage.go, line 378 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-Mys0cL46_NN8vCXZ3gJ:-MysfC3uB4IY6LhJFN8G:buefeba) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad964b08ecdff007b1bd022ba9ff69da44f7686/pkg/util/mon/bytes_usage.go#L378)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

not needed if the constructor takes a redact.SafeString or RedactableString.
</blockquote></details>

I'd rather not change the signature since I want this to be backported, so the least amount of changes seems preferrable.
___
*[pkg/util/mon/bytes_usage.go, line 762 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-Mys0hfd-DQElhaqEGFA:-MysgEVl0ujQ5sfCYSEJ:bfi37kr) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad964b08ecdff007b1bd022ba9ff69da44f7686/pkg/util/mon/bytes_usage.go#L762)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ints should already be safe for reporting. Are they not? How come they are not?
</blockquote></details>

You're right, reverted.
___
*[pkg/util/mon/bytes_usage.go, line 771 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-Mys0phOE2hBKU2v15SL:-Mysf_Nm5KfHyYA0ZiXR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad964b08ecdff007b1bd022ba9ff69da44f7686/pkg/util/mon/bytes_usage.go#L771)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/util/mon/bytes_usage.go, line 772 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-Mys0ltV3T7-V0E5F8xJ:-MysgH-g02LHPWHMxs_y:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad964b08ecdff007b1bd022ba9ff69da44f7686/pkg/util/mon/bytes_usage.go#L772)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ideally we'd make GetSmallTrace a RedactableString (or SafeString) and call it a day for all callers.
</blockquote></details>

Good point, done.
___
*[pkg/util/mon/bytes_usage.go, line 800 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-Mys0qQc3PQEKbxPcJ3K:-MysgS8I6tpBiyvoxGJ8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad964b08ecdff007b1bd022ba9ff69da44f7686/pkg/util/mon/bytes_usage.go#L800)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/util/mon/bytes_usage.go, line 819 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-Mys0rPEEbGVSTi1IWp5:-MysgSPz-tdaO8vFT6jX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad964b08ecdff007b1bd022ba9ff69da44f7686/pkg/util/mon/bytes_usage.go#L819)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/util/mon/bytes_usage.go, line 846 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-Mys0rvG-HXMK_GPOrlD:-Mysh2L_6rtHHbOQExGP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad964b08ecdff007b1bd022ba9ff69da44f7686/pkg/util/mon/bytes_usage.go#L846)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by knz — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78352)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[pkg/util/smalltrace.go, line 51 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-Myt67XB2HXTqz3i_JCK:-Myt67XB2HXTqz3i_JCL:bqid5ut) ([raw file](https://github.com/cockroachdb/cockroach/blob/704313f5d3e3c37a16ea7bc453fec19521f82919/pkg/util/smalltrace.go#L51)):*
> ```Go
> 	}
> 
> 	return redact.Sprint(strings.Join(callers, ","))
> ```

That's still going to make the entire stack sensitive and disappear during redaction.

May I suggest this: replace `callers` above by a `redact.StringBuilder` and write the strings directly to it, then call `.RedactableString()` on the buffer at the end.
___
*[pkg/util/mon/bytes_usage.go, line 299 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-Mys0Vjq7Sr5N4_eL_3Q:-Myt6skL0VoP04tmb84K:bs231nj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad964b08ecdff007b1bd022ba9ff69da44f7686/pkg/util/mon/bytes_usage.go#L299)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This choice will still elide the name in redacted logs.

Actually I do recommend you make the argument a redact.SafeString. I just grepped the entire source base for `NewMonitorWithLimit` and all the callers pass a constant literal string, so they would fit into a SafeString or RedactableString  without having to change the callers.
___
*[pkg/util/mon/bytes_usage.go, line 378 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-Mys0cL46_NN8vCXZ3gJ:-Myt7EzQ1CUbd3nH8Jyo:b-1oqgsz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad964b08ecdff007b1bd022ba9ff69da44f7686/pkg/util/mon/bytes_usage.go#L378)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I'd rather not change the signature since I want this to be backported, so the least amount of changes seems preferrable.
</blockquote></details>

I also grepped the source base for `NewUnlimitedMonitor` and I think all the callers use a constant literal, so it would fit in a SafeString or RedactableString without changes.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78352)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz and @yuzefovich)

___
*[pkg/sql/colexec/colexecargs/monitor_registry.go, line 50 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-Myu0oZ97fNp9GSajLh6:-Myu0oZ97fNp9GSajLh7:b-rvuirl) ([raw file](https://github.com/cockroachdb/cockroach/blob/d602a54e5bf0dbc38c0ffad941b662816ca45bf8/pkg/sql/colexec/colexecargs/monitor_registry.go#L50)):*
> ```Go
> 	// This way of constructing a string is more efficient than using
> 	// fmt.Sprintf.
> 	return redact.Sprint(opName, "-", processorID, "-", suffix, "-", len(r.monitors))
> ```

Is there a way to not incur an allocation here? I think the fact that we're passing var-len array of `interface{}` into `redact.Sprint` will incur an allocation.
___
*[pkg/util/smalltrace.go, line 51 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-Myt67XB2HXTqz3i_JCK:-Myu-nTY480dBx3jvh7Z:b8bw264) ([raw file](https://github.com/cockroachdb/cockroach/blob/704313f5d3e3c37a16ea7bc453fec19521f82919/pkg/util/smalltrace.go#L51)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

That's still going to make the entire stack sensitive and disappear during redaction.

May I suggest this: replace `callers` above by a `redact.StringBuilder` and write the strings directly to it, then call `.RedactableString()` on the buffer at the end.
</blockquote></details>

Thanks for the suggestion, done.
___
*[pkg/util/mon/bytes_usage.go, line 299 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-Mys0Vjq7Sr5N4_eL_3Q:-Myu-uzI3_w3fuRgUfG2:btc4r2s) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad964b08ecdff007b1bd022ba9ff69da44f7686/pkg/util/mon/bytes_usage.go#L299)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This choice will still elide the name in redacted logs.

Actually I do recommend you make the argument a redact.SafeString. I just grepped the entire source base for `NewMonitorWithLimit` and all the callers pass a constant literal string, so they would fit into a SafeString or RedactableString  without having to change the callers.
</blockquote></details>

Unfortunately, there are callers of the callers of these methods. I made the changes in a temporary WIP commit, let me know what you think.

**Review by knz — COMMENTED** [review]
:lgtm: modulo nits and minor fixes.

amazing, thanks for going the extra mile.

> Reviewed 1 of 1 files at r3, 15 of 15 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-:-Mywmuza96dGC6BB3XI_:b-msnl2r)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[pkg/sql/buffer_util.go, line 83 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-Mywn2j95SALdjfnRmeW:-Mywn2j95SALdjfnRmeX:b2it90n) ([raw file](https://github.com/cockroachdb/cockroach/blob/d602a54e5bf0dbc38c0ffad941b662816ca45bf8/pkg/sql/buffer_util.go#L83)):*
> ```Go
> 	)
> 	c.diskMonitor = execinfra.NewMonitor(
> 		evalContext.Context, distSQLCfg.ParentDiskMonitor, redact.Sprint("%s-disk", opName),
> ```

sprintf
___
*[pkg/sql/planner.go, line 362 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-MywfrRw87U6swF4Mqz5:-MywfrRx13AKrRHGVR6n:b808cq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d602a54e5bf0dbc38c0ffad941b662816ca45bf8/pkg/sql/planner.go#L362)):*
> ```Go
> 	p.semaCtx.IntervalStyle = sd.GetIntervalStyle()
> 
> 	plannerMon := mon.NewMonitor(redact.Sprint("internal-planner.%s.%s", user, opName),
> ```

sprintf,

also add a TODO comment to make opName a redactablestring too.
___
*[pkg/sql/colexec/colexecargs/monitor_registry.go, line 50 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-Myu0oZ97fNp9GSajLh6:-MywgBHo1N5UwPDsLkvX:b-ea9gp9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d602a54e5bf0dbc38c0ffad941b662816ca45bf8/pkg/sql/colexec/colexecargs/monitor_registry.go#L50)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Is there a way to not incur an allocation here? I think the fact that we're passing var-len array of `interface{}` into `redact.Sprint` will incur an allocation.
</blockquote></details>

vararg arrays are allocated on the stack in go. This won't incur an allocation.
___
*[pkg/sql/rowexec/sorter.go, line 63 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-MywgSqt504_QJJQXYSW:-MywgSqt504_QJJQXYSX:bpqz8pd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d602a54e5bf0dbc38c0ffad941b662816ca45bf8/pkg/sql/rowexec/sorter.go#L63)):*
> ```Go
> 	// Limit the memory use by creating a child monitor with a hard limit.
> 	// The processor will overflow to disk if this limit is not enough.
> 	memMonitor := execinfra.NewLimitedMonitor(ctx, flowCtx.EvalCtx.Mon, flowCtx, redact.Sprint("%s-limited", processorName))
> ```

sprintf here and below
___
*[pkg/sql/rowflow/routers.go, line 276 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-MywgQE65egP23L8lwVR:-MywgQE65egP23L8lwVS:bpqz8pd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d602a54e5bf0dbc38c0ffad941b662816ca45bf8/pkg/sql/rowflow/routers.go#L276)):*
> ```Go
> 		rb.outputs[i].memoryMonitor = execinfra.NewLimitedMonitor(
> 			ctx, evalCtx.Mon, flowCtx,
> 			redact.Sprint("router-limited-%d", rb.outputs[i].streamID),
> ```

sprintf here and below
___
*[pkg/util/smalltrace.go, line 46 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-MywgdpR71CZgcMq8pw7:-MywgdpR71CZgcMq8pw8:bnkd676) ([raw file](https://github.com/cockroachdb/cockroach/blob/d602a54e5bf0dbc38c0ffad941b662816ca45bf8/pkg/util/smalltrace.go#L46)):*
> ```Go
> 			file = file[index+1:]
> 		}
> 		_, _ = callers.WriteString(file + ":" + strconv.Itoa(f.Line) + ":" + function)
> ```

Simpler: `callers.Printf`
___
*[pkg/util/smalltrace.go, line 50 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-Mywggc3Bm1HZsy1cKoy:-Mywggc49faHRwnVfRl1:b-1aqdmd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d602a54e5bf0dbc38c0ffad941b662816ca45bf8/pkg/util/smalltrace.go#L50)):*
> ```Go
> 			first = false
> 		} else {
> 			_, _ = callers.WriteString(",")
> ```

WriteRune?

**Review by yuzefovich — COMMENTED** [review]
Thanks for the reviews!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-:-Myz15h4-4AJzL3WlDPT:bctxt4d)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @knz)

___
*[pkg/sql/buffer_util.go, line 83 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-Mywn2j95SALdjfnRmeW:-MyyzA7ZDhkhiTiYq9FS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d602a54e5bf0dbc38c0ffad941b662816ca45bf8/pkg/sql/buffer_util.go#L83)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

sprintf
</blockquote></details>

Done.
___
*[pkg/sql/planner.go, line 362 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-MywfrRw87U6swF4Mqz5:-MyyzMxd2AernQx5jaZ-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d602a54e5bf0dbc38c0ffad941b662816ca45bf8/pkg/sql/planner.go#L362)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

sprintf,

also add a TODO comment to make opName a redactablestring too.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/colexecargs/monitor_registry.go, line 50 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-Myu0oZ97fNp9GSajLh6:-Myz3_UP4T-fobYXy8B2:b-rzm5i4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d602a54e5bf0dbc38c0ffad941b662816ca45bf8/pkg/sql/colexec/colexecargs/monitor_registry.go#L50)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

vararg arrays are allocated on the stack in go. This won't incur an allocation.
</blockquote></details>

Hm, there do appear some allocations in `redact.Sprintf`.

I applied this diff:
```
diff --git a/pkg/sql/colexec/colexecargs/monitor_registry.go b/pkg/sql/colexec/colexecargs/monitor_registry.go
index b4d5f89dc3..a55faf3a1f 100644
--- a/pkg/sql/colexec/colexecargs/monitor_registry.go
+++ b/pkg/sql/colexec/colexecargs/monitor_registry.go
@@ -45,7 +45,7 @@ func (r *MonitorRegistry) NewStreamingMemAccount(flowCtx *execinfra.FlowCtx) *mo
 func (r MonitorRegistry) getMemMonitorName(
        opName redact.RedactableString, processorID int32, suffix redact.RedactableString,
 ) redact.RedactableString {
-       return redact.Sprintf("%s-%d-%s-%d", opName, processorID, suffix, len(r.monitors))
+       return opName
 }
 
 // CreateMemAccountForSpillStrategy instantiates a memory monitor and a memory
```
on top of this PR and got this (old is this PR, new is this PR plus the diff):
```
name                                           old time/op    new time/op    delta
FlowSetup/vectorize=true/distribute=true-24       167µs ± 2%     164µs ± 3%  -2.12%  (p=0.000 n=49+48)
FlowSetup/vectorize=true/distribute=false-24      166µs ± 2%     161µs ± 3%  -3.31%  (p=0.000 n=50+50)
FlowSetup/vectorize=false/distribute=true-24      162µs ± 3%     160µs ± 3%  -1.57%  (p=0.000 n=50+47)
FlowSetup/vectorize=false/distribute=false-24     158µs ± 2%     156µs ± 2%  -1.21%  (p=0.000 n=50+50)

name                                           old alloc/op   new alloc/op   delta
FlowSetup/vectorize=true/distribute=true-24      28.7kB ± 1%    28.6kB ± 1%  -0.67%  (p=0.000 n=40+40)
FlowSetup/vectorize=true/distribute=false-24     27.6kB ± 1%    27.4kB ± 0%  -0.72%  (p=0.000 n=41+42)
FlowSetup/vectorize=false/distribute=true-24     35.1kB ± 0%    35.1kB ± 0%    ~     (p=0.904 n=41+41)
FlowSetup/vectorize=false/distribute=false-24    33.9kB ± 0%    33.9kB ± 0%    ~     (p=0.370 n=43+42)

name                                           old allocs/op  new allocs/op  delta
FlowSetup/vectorize=true/distribute=true-24         251 ± 1%       245 ± 1%  -2.39%  (p=0.000 n=43+44)
FlowSetup/vectorize=true/distribute=false-24        246 ± 0%       240 ± 0%  -2.44%  (p=0.000 n=40+43)
FlowSetup/vectorize=false/distribute=true-24        249 ± 1%       249 ± 2%    ~     (p=0.399 n=49+47)
FlowSetup/vectorize=false/distribute=false-24       240 ± 0%       240 ± 0%    ~     (all equal)
```
Although somewhat unfortunate, I think it's acceptable.
___
*[pkg/sql/rowexec/sorter.go, line 63 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-MywgSqt504_QJJQXYSW:-Myyzm8f3bUZdXuWkhvA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d602a54e5bf0dbc38c0ffad941b662816ca45bf8/pkg/sql/rowexec/sorter.go#L63)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

sprintf here and below
</blockquote></details>

Done.
___
*[pkg/sql/rowflow/routers.go, line 276 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-MywgQE65egP23L8lwVR:-Myyzs9-7zuSzCr-DEHV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d602a54e5bf0dbc38c0ffad941b662816ca45bf8/pkg/sql/rowflow/routers.go#L276)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

sprintf here and below
</blockquote></details>

Done.
___
*[pkg/util/smalltrace.go, line 46 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-MywgdpR71CZgcMq8pw7:-Myz-QGXB6GYUFaVJZDA:bo3vl6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/d602a54e5bf0dbc38c0ffad941b662816ca45bf8/pkg/util/smalltrace.go#L46)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Simpler: `callers.Printf`
</blockquote></details>

Thanks, done.
___
*[pkg/util/smalltrace.go, line 50 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78352#-Mywggc3Bm1HZsy1cKoy:-Myz-R9H9j_CYSFpO61T:byg433c) ([raw file](https://github.com/cockroachdb/cockroach/blob/d602a54e5bf0dbc38c0ffad941b662816ca45bf8/pkg/util/smalltrace.go#L50)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

WriteRune?
</blockquote></details>

Refactored.

**Pull request merged**
