### PR TITLE
mixedversion: refactor test context

### PR DESCRIPTION
**Pull request by renatolabs**
This PR refactors the maintenance of mixed-version test contexts and the methods available on `mixedversion.Context`. Specifically (one bullet point per commit):

* A `Context` is now associated with every `singleStep`, instead of just `runHookStep`. In other words, even internal steps now have a context associated with them.
* With this change, it becomes trivial to display the current released binary versions for each node before we start executing each step, and also when an error occurs.
* Make `Context` a struct field instead of function call. This is mostly to indicate to the caller that the context is static and no computation happens. In fact, the test context is derived during planning time. This is specially important for background functions, where node restarts are happening concurrently.
* Improve formatting of logical and cluster versions on test failure and at the beginning of every step by displaying it in a tabular format.

The `Context` type and related functions were also moved to their own file, `context.go`, to make it easier for people to be able to see all public functions available when using the framework.

These changes pave the way for a higher level internal API that will allow us to change or insert steps in upgrade plans in mixedversion tests.

### CODE REVIEW

**Comment by renatolabs** [comment]
Opening this for review. A run with all mixed-version tests:

https://teamcity.cockroachdb.com/viewLog.html?buildId=12662928&buildTypeId=Cockroach_Nightlies_RoachtestNightlyGceBazel

**Review by DarrylWong — APPROVED** [review]
Oops, looks like `tpcc/mixed-headroom` wasn't hit by that regex. Not that big of a deal (don't think you _need_ to run it) but mildly annoying that it doesn't follow the `mixed-version` naming convention the others do.

Feel free to let someone else stamp this but it looks really good to me.

> Reviewed 1 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114286#-:-NjEtq1j2RdRDEjNLu3k:bic620e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs and @srosenberg)

___
*[`-- commits` line 11 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/114286#-NjIlUcTAOIzJXHr5r-5):*
nit: every step?
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/context.go` line 61 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/114286#-NjJ0F28DGOvmTE2OdDQ:-NjJ0F28DGOvmTE2OdDR:b-n0m2nh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c89c2de4a3600ad3f5801e84b61db7c9ecd9940/pkg/cmd/roachtest/roachtestutil/mixedversion/context.go#L61)):*
> ```Go
> // `FromVersion` and `ToVersion` correspond to, respectively, the
> // initial version the cluster is started at, and the final version
> // once the test finishes. Background functions should *not* rely on
> ```

Is there a reason we give background functions a context struct then? Other than to play nice with the framework? If not I wonder if we should guard users against using it, but maybe not worth the effort given the clear warning in this comment.

**Review by renatolabs — COMMENTED** [review]
> `tpcc/mixed-headroom` wasn't hit by that regex

Good catch, I'll kick off a run just in case.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114286#-:-NjJphv8En9aGSwn8Qib:b-8euad)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong and @srosenberg)

___
*[`-- commits` line 11 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/114286#-NjIlUcTAOIzJXHr5r-5):*
<details><summary><i>Previously, DarrylWong wrote…</i></summary><blockquote>

nit: every step?
</blockquote></details>

Ah yes, fixed.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/context.go` line 61 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/114286#-NjJ0F28DGOvmTE2OdDQ:-NjJog7R66hUKMvZgLr9:b-rwdxpa) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c89c2de4a3600ad3f5801e84b61db7c9ecd9940/pkg/cmd/roachtest/roachtestutil/mixedversion/context.go#L61)):*
<details><summary><i>Previously, DarrylWong wrote…</i></summary><blockquote>

Is there a reason we give background functions a context struct then? Other than to play nice with the framework? If not I wonder if we should guard users against using it, but maybe not worth the effort given the clear warning in this comment.
</blockquote></details>

There's _some_ value since these functions can still know what the starting version is (`Context.FromVersion`), in case that is relevant for what they are doing. I agree that this is a bit of a footgun but I don't want to proactively fix it until it's a clear problem (there are higher priority items for `mixedversion`).

**Comment by renatolabs** [comment]
Here's a run with `tpcc/mixed-headroom`:

https://teamcity.cockroachdb.com/viewLog.html?buildId=12701369&buildTypeId=Cockroach_Nightlies_RoachtestNightlyGceBazel&tab=buildResultsDiv

TFTR!

bors r=DarrylWong

**Pull request merged**
