### PR TITLE
exec: make sure that AND operator pays attention to whether a value is null

### PR DESCRIPTION
**Pull request by yuzefovich**
**exec: make sure that AND operator pays attention to whether a value is null**

Previously, AND operator would simply logically and two boolean vectors.
However, this is incorrect if we have actual null values in those
vectors. The underlying complication is that nulls are stored separately,
so we need to explicitly check for them. Now this is fixed.

**exec: add unit test for AND operator**

This commit adds a unit test for AND operator. It also extends our
testing infrastructure to be able to specify the types schema (this
was needed because nil values are treated as Int64 by default which
is incorrect for tests of AND operator).

Release note: None

### CODE REVIEW

**Review by jordanlewis — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40615)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @rafiss, and @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/vectorize, line 851 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40615#-LoQDLzPCbV9dflQGY1u:-LoQDLzQ3DHZsSrw1GW1:buanwye) ([raw file](https://github.com/cockroachdb/cockroach/blob/7953d9c48a22cff2b615ab54529d0a9d4c92223c/pkg/sql/logictest/testdata/logic_test/vectorize#L851)):*
> ```
> 
> # Test that AND'ing a true value with another true value while one of them is
> # actually NULL returns false.
> ```

Wait, but `true and null` is supposed to return `null`... the rules are confusing. It appears that if either side is `false`, the result is `false`, but if either side is `true` the result is null.

It makes sense if you think of `null` as being "unknown". if there's a false in the `and`, the result is definitely false even though we don't know what the unknown value is. But if there's a true, we can't tell what the outcome will be due to the unknown value so we're forced to return `null`.

**Comment by rafiss** [comment]
I would have guessed that there is some existing logic test that would catch this. I thought we were planning to enable all the existing logic tests that support vectorized to actually run with the vectorized engine? Or did we already do that, but this case isn't tested? Either way it seems like a really good thing to do before release.

**Comment by jordanlewis** [comment]
I don't see tests for that in the logic tests. There are tests for it in the eval tests, which we don't run through the vectorized engine because it's kind of tricky to do so - those just test expressions, and the expressions will get constant folded. We should try to figure out how to run those tests via the vectorized engine somehow for sure.  They're in `pkg/sql/sem/tree/testdata/eval`.

**Comment by rafiss** [comment]
Got it -- also I think we should create `and_test.go` and `case_test.go` unit tests soon. I made the following issues: #40634 #40635

**Review by yuzefovich — COMMENTED** [review]
I fixed the correctness issue and added unit tests. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40615#-:-LoRIz7i94cjfAlwU9LC:bkgjzmq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rafiss)

___
*[pkg/sql/logictest/testdata/logic_test/vectorize, line 851 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40615#-LoQDLzPCbV9dflQGY1u:-LoRIqlf0LIfdTpWzGyZ:bl7xs85) ([raw file](https://github.com/cockroachdb/cockroach/blob/7953d9c48a22cff2b615ab54529d0a9d4c92223c/pkg/sql/logictest/testdata/logic_test/vectorize#L851)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Wait, but `true and null` is supposed to return `null`... the rules are confusing. It appears that if either side is `false`, the result is `false`, but if either side is `true` the result is null.

It makes sense if you think of `null` as being "unknown". if there's a false in the `and`, the result is definitely false even though we don't know what the unknown value is. But if there's a true, we can't tell what the outcome will be due to the unknown value so we're forced to return `null`.
</blockquote></details>

Thanks for pointing this out! Your explanation makes sense to me, my intuition was wrong. Fixed.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40615)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @yuzefovich)

___
*[pkg/sql/exec/and_tmpl.go, line 79 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40615#-LoTOCAA8zY2_5dKfjfz:-LoTOCAA8zY2_5dKfjg-:b-r3aewq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6233dd688a1ca2bc12f1eb696a8a1c4d596f560e/pkg/sql/exec/and_tmpl.go#L79)):*
> ```Go
> 				// Rule 1: at least one boolean is FALSE.
> 				outputColVals[i] = false
> 				outputNulls.UnsetNull(i)
> ```

Isn't it the case that in principle we should not need to `UnsetNull` here? The contract is (or should be) that the column that a projection owns will be reset on each iteration by the batch owner. This is taken care of by `ResetInternalBatch`, which unsets all nulls. I would think and hope that only the last `SetNull` is needed.
___
*[pkg/sql/exec/and_tmpl.go, line 92 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40615#-LoTPJ2D4VdYG6lYWFrX:-LoTPJ2D4VdYG6lYWFrY:b-jwxvp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6233dd688a1ca2bc12f1eb696a8a1c4d596f560e/pkg/sql/exec/and_tmpl.go#L92)):*
> ```Go
> 		_ = rightColVals[n-1]
> 		_ = outputColVals[n-1]
> 		for i := range leftColVals[:n] {
> ```

This whole part is identical, right? Can you make it a template function? It's too much code duplication (potential for mistakes due to editing one and not the other) right now.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40615)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rafiss)

___
*[pkg/sql/exec/and_tmpl.go, line 79 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40615#-LoTOCAA8zY2_5dKfjfz:-LoWAcCZChYknL3gaLWM:b3fmxuc) ([raw file](https://github.com/cockroachdb/cockroach/blob/6233dd688a1ca2bc12f1eb696a8a1c4d596f560e/pkg/sql/exec/and_tmpl.go#L79)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Isn't it the case that in principle we should not need to `UnsetNull` here? The contract is (or should be) that the column that a projection owns will be reset on each iteration by the batch owner. This is taken care of by `ResetInternalBatch`, which unsets all nulls. I would think and hope that only the last `SetNull` is needed.
</blockquote></details>

You're right, only the last one is required. I thought of being on the safe side given that we've had multiple issues with nulls, but I guess it might hide a problem somewhere else, so I removed the other two.
___
*[pkg/sql/exec/and_tmpl.go, line 92 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40615#-LoTPJ2D4VdYG6lYWFrX:-LoWAUVK5Ta1C00OWelH:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/6233dd688a1ca2bc12f1eb696a8a1c4d596f560e/pkg/sql/exec/and_tmpl.go#L92)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This whole part is identical, right? Can you make it a template function? It's too much code duplication (potential for mistakes due to editing one and not the other) right now.
</blockquote></details>

Good point, done.

**Review by jordanlewis — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 1 of 2 files at r2, 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40615)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rafiss)

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Pull request merged**
