### PR TITLE
cmd: github-post will comment on identical issues

### PR DESCRIPTION
**Pull request by jordanlewis**
github-post now searches to see if there are any other open issues with
the same title as the one proposed. If so, no new issue will be posted -
the body of the new issue will be added to the old issue as a comment.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13329)

### CODE REVIEW

**Comment by tamird** [comment]
:fire: nice work

:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/cmd/github-post/main.go, line 40 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-Kbq_b6ysE0y3O9M3X0D:-Kbq_b6ysE0y3O9M3X0E:bo3d9gn) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72fae4fe2f6d3d64ceb46b9dd8527d432c8479f/pkg/cmd/github-post/main.go#L40)):*
> ```Go
> const teamcityBuildIDEnv = "TC_BUILD_ID"
> const teamcityServerURLEnv = "TC_SERVER_URL"
> const githubUser = "cockroachdb"
> ```

nit: githubOrg

---

*[pkg/cmd/github-post/main.go, line 48 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-Kbqa7BksxKd4TfWr1w-:-Kbq_eKQ7UVhdd-tLqwu:b-aidsyj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72fae4fe2f6d3d64ceb46b9dd8527d432c8479f/pkg/cmd/github-post/main.go#L48)):*
> ```Go
> const goFlagsEnv = "GOFLAGS"
> 
> var issueLabels = &[]string{"Robot", "test-failure"}
> ```

nit: make this a value, not a pointer; really weird to see `range *foo`

---

*[pkg/cmd/github-post/main.go, line 173 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-KbqaBqDjLBx0sm0Jfx4:-KbqaBqDjLBx0sm0Jfx5:b-1kdgaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72fae4fe2f6d3d64ceb46b9dd8527d432c8479f/pkg/cmd/github-post/main.go#L173)):*
> ```Go
> 				searchQuery := fmt.Sprintf(`"%s" user:%s repo:%s is:open`, issueRequest.Title, githubUser, githubRepo)
> 				for _, label := range *issueLabels {
> 					searchQuery = searchQuery + fmt.Sprintf(` label: %s`, label)
> ```

no quotes on this one?

---

*[pkg/cmd/github-post/main.go, line 182 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-KbqaMxH7OkwybDJz8dZ:-KbqaMxH7OkwybDJz8d_:b5rgoaa) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72fae4fe2f6d3d64ceb46b9dd8527d432c8479f/pkg/cmd/github-post/main.go#L182)):*
> ```Go
> 						PerPage: 1,
> 					},
> 				}); err == nil {
> ```

can you handle the error? If there's a sentinel error we need to ignore here, let's ignore it, but ignoring all errors globally makes me nervous.

---

*[pkg/cmd/github-post/main_test.go, line 44 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-KbqadJUov1JVqS_X2e3:-KbqadJUov1JVqS_X2e4:b-s4sl1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72fae4fe2f6d3d64ceb46b9dd8527d432c8479f/pkg/cmd/github-post/main_test.go#L44)):*
> ```Go
> 		issueID       = 1337
> 	)
> 	var issueNumber = 30
> ```

const?

---

*[pkg/cmd/github-post/main_test.go, line 98 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-KbqbGH3S-bfeUNCeOsp:-KbqbGH3S-bfeUNCeOsq:b-5xs336) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72fae4fe2f6d3d64ceb46b9dd8527d432c8479f/pkg/cmd/github-post/main_test.go#L98)):*
> ```Go
> 	} {
> 		for _, foundIssue := range []bool{true, false} {
> 			t.Run(fileName, func(t *testing.T) {
> ```

this subtest name should include `foundIssue`, now

---

*[pkg/cmd/github-post/main_test.go, line 125 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-Kbqba2n-KOYFHVvZ_j5:-Kbqba2n-KOYFHVvZ_j6:bvkk9m5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72fae4fe2f6d3d64ceb46b9dd8527d432c8479f/pkg/cmd/github-post/main_test.go#L125)):*
> ```Go
> 				}
> 
> 				issueCount := 0
> ```

use booleans please.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-:-KbqbcA3LFB6lxWWHF4K:b-cw9dzl)*

**Comment by jordanlewis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/cmd/github-post/main.go, line 40 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-Kbq_b6ysE0y3O9M3X0D:-KbqhgQf7ZTXfUdtrzVx:bkmlylk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72fae4fe2f6d3d64ceb46b9dd8527d432c8479f/pkg/cmd/github-post/main.go#L40)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: githubOrg
</blockquote></details>

Using `user` because that's what's in the `go-github` docs.

---

*[pkg/cmd/github-post/main.go, line 48 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-Kbqa7BksxKd4TfWr1w-:-KbqhseY9IaPE1NW0FBv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72fae4fe2f6d3d64ceb46b9dd8527d432c8479f/pkg/cmd/github-post/main.go#L48)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: make this a value, not a pointer; really weird to see `range *foo`
</blockquote></details>

Done.

---

*[pkg/cmd/github-post/main.go, line 173 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-KbqaBqDjLBx0sm0Jfx4:-Kbqk0_XtNOWK3IvZw3T:b-rwf5x7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72fae4fe2f6d3d64ceb46b9dd8527d432c8479f/pkg/cmd/github-post/main.go#L173)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

no quotes on this one?
</blockquote></details>

Done, also removed the erroneous space

---

*[pkg/cmd/github-post/main.go, line 182 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-KbqaMxH7OkwybDJz8dZ:-Kbqi-_ZsWXBM9Tt2Q3J:b-yuh4gv) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72fae4fe2f6d3d64ceb46b9dd8527d432c8479f/pkg/cmd/github-post/main.go#L182)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can you handle the error? If there's a sentinel error we need to ignore here, let's ignore it, but ignoring all errors globally makes me nervous.
</blockquote></details>

Just ignoring this because if the search fails we'll fall back to making a new issue. I'll log the error otherwise I suppose.

---

*[pkg/cmd/github-post/main_test.go, line 44 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-KbqadJUov1JVqS_X2e3:-Kbqi8keA_q0F8cvMt11:b-be69q6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72fae4fe2f6d3d64ceb46b9dd8527d432c8479f/pkg/cmd/github-post/main_test.go#L44)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

const?
</blockquote></details>

Need to take the address of it for the `go-github` api.

---

*[pkg/cmd/github-post/main_test.go, line 98 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-KbqbGH3S-bfeUNCeOsp:-KbqiCZbeHOvqfv88zZz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72fae4fe2f6d3d64ceb46b9dd8527d432c8479f/pkg/cmd/github-post/main_test.go#L98)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this subtest name should include `foundIssue`, now
</blockquote></details>

Done.

---

*[pkg/cmd/github-post/main_test.go, line 125 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-Kbqba2n-KOYFHVvZ_j5:-KbqiHEx6uCHwNdPOGsw:b7iz4dv) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72fae4fe2f6d3d64ceb46b9dd8527d432c8479f/pkg/cmd/github-post/main_test.go#L125)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

use booleans please.
</blockquote></details>

We want to make sure we don't post too many as well though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/cmd/github-post/main.go, line 182 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-KbqaMxH7OkwybDJz8dZ:-KbqmD4SQ90va7zJAPSK:b-okldk2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72fae4fe2f6d3d64ceb46b9dd8527d432c8479f/pkg/cmd/github-post/main.go#L182)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Just ignoring this because if the search fails we'll fall back to making a new issue. I'll log the error otherwise I suppose.
</blockquote></details>

I guess what I'm saying is: if the search fails, it's probably a network error, or something otherwise bad. I think this should return the error unless "no results" returns an error, which seems unlikely.

---

*[pkg/cmd/github-post/main_test.go, line 44 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-KbqadJUov1JVqS_X2e3:-KbqmtYH2L_7Nj_R6HS8:b-d5np0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72fae4fe2f6d3d64ceb46b9dd8527d432c8479f/pkg/cmd/github-post/main_test.go#L44)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Need to take the address of it for the `go-github` api.
</blockquote></details>

I think https://godoc.org/github.com/google/go-github/github#Int might be what you're looking for.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329)*

**Comment by bdarnell** [comment]
Some of the issue bodies can be huge. If you're posting a comment it would probably be a good idea to limit how much we post. (maybe just a link to the new CI run?)

**Comment by a-robinson** [comment]
:lgtm_strong: This is great, thanks @jordanlewis!

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/cmd/github-post/main.go, line 197 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-Kbu5XJA6Q7crodWi9Bo:-Kbu5XJA6Q7crodWi9Bp:bj9kkef) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa0be4f25551c717a6fcb852000b2cdc9328f113/pkg/cmd/github-post/main.go#L197)):*
> ```Go
> 					comment := &github.IssueComment{Body: issueRequest.Body}
> 					if _, _, err := createComment(githubUser, githubRepo, *foundIssue, comment); err != nil {
> 						return errors.Wrapf(err, "failed to update issue #%d with %s", *foundIssue, github.Stringify(comment))
> ```

Where will these errors show up? Once we know this code works well we won't have to check for them, but for the first few days we probably should.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-:-Kbu630pHSQ6g_Ci2eqR:b-buofcw)*

**Comment by jordanlewis** [comment]
Good point, Ben. Updated to just include the link. Sometimes these tests fail for several different reasons, and we've been keeping an issue open for each, but that doesn't seem particularly useful for me - I'd be happy if all the test failures for a given test were kept in a single issue.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/cmd/github-post/main.go, line 182 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-KbqaMxH7OkwybDJz8dZ:-Kbu8HAgND9R8LHLf98C:bqiygch) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72fae4fe2f6d3d64ceb46b9dd8527d432c8479f/pkg/cmd/github-post/main.go#L182)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I guess what I'm saying is: if the search fails, it's probably a network error, or something otherwise bad. I think this should return the error unless "no results" returns an error, which seems unlikely.
</blockquote></details>

Okay we'll just error out then.

---

*[pkg/cmd/github-post/main.go, line 197 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-Kbu5XJA6Q7crodWi9Bo:-Kbu8IgZA1vJEQn9UK2c:br7kxos) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa0be4f25551c717a6fcb852000b2cdc9328f113/pkg/cmd/github-post/main.go#L197)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Where will these errors show up? Once we know this code works well we won't have to check for them, but for the first few days we probably should.
</blockquote></details>

Good question. Probably in the TeamCity individual stress builds, but I've never actually gone hunting for those. @tamird would probably know  better.

---

*[pkg/cmd/github-post/main_test.go, line 44 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-KbqadJUov1JVqS_X2e3:-Kbu8_iQ485-A1AcxRBw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72fae4fe2f6d3d64ceb46b9dd8527d432c8479f/pkg/cmd/github-post/main_test.go#L44)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I think https://godoc.org/github.com/google/go-github/github#Int might be what you're looking for.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-:-Kbu90g88XrUCepZcBd0:b61dyv5)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3.
Review status: 1 of 2 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/cmd/github-post/main.go, line 197 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-Kbu5XJA6Q7crodWi9Bo:-KbuS42RDk8e2-IiKuh6:ba0w4yw) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa0be4f25551c717a6fcb852000b2cdc9328f113/pkg/cmd/github-post/main.go#L197)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Good question. Probably in the TeamCity individual stress builds, but I've never actually gone hunting for those. @tamird would probably know  better.
</blockquote></details>

Yeah, probably in there. Likely to go unnoticed in general, but at least it will be there if we go looking.

---

*[pkg/cmd/github-post/main.go, line 139 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-KbuRbd6pGynDB1EHqK3:-KbuRbd6pGynDB1EHqK4:b-x1iuyh) ([raw file](https://github.com/cockroachdb/cockroach/blob/239be76a1427b1aa7ba790c578e0fb3cc0de4c23/pkg/cmd/github-post/main.go#L139)):*
> ```Go
> 	newIssueRequest := func(packageName, testName, message string) *github.IssueRequest {
> 		title := fmt.Sprintf("%s: %s failed under stress", packageName, testName)
> 		body := fmt.Sprintf(bodyTemplate+"\n\n%s", sha, parametersStr, u.String(), "```\n%s\n```")
> ```

gosh, this is hard to read. how about

```
body := fmt.Sprintf(bodyTemplate, sha, parametersStr, u.String()) + "\n\n```\n%s\n```"
```

---

*[pkg/cmd/github-post/main.go, line 190 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-KbuRxLRi3Q1_2f19bit:-KbuRxLRi3Q1_2f19biu:bcxaxar) ([raw file](https://github.com/cockroachdb/cockroach/blob/239be76a1427b1aa7ba790c578e0fb3cc0de4c23/pkg/cmd/github-post/main.go#L190)):*
> ```Go
> 				})
> 				if err != nil {
> 					return errors.Wrapf(err, "failed to search GitHub", github.Stringify(searchQuery))
> ```

there needs to be a `%s` or something in here.

---

*[pkg/cmd/github-post/main_test.go, line 116 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-KbuStc7WXNux8ae0H2r:-KbuSWKCG1i5Od6MC2hd:b-4wb2br) ([raw file](https://github.com/cockroachdb/cockroach/blob/239be76a1427b1aa7ba790c578e0fb3cc0de4c23/pkg/cmd/github-post/main_test.go#L116)):*
> ```Go
> 					regexp.QuoteMeta(sha),
> 					regexp.QuoteMeta(parameters),
> 					regexp.QuoteMeta(fmt.Sprintf("%s/viewLog.html?buildId=%d&tab=buildLog", serverURL, buildID)))
> ```

closing paren on the next line, if it's all the same to you.

---

*[pkg/cmd/github-post/main_test.go, line 123 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-KbuSc3Bhs0-mTM6OxaA:-KbuSc3Bhs0-mTM6OxaB:bq4w68v) ([raw file](https://github.com/cockroachdb/cockroach/blob/239be76a1427b1aa7ba790c578e0fb3cc0de4c23/pkg/cmd/github-post/main_test.go#L123)):*
> ```Go
> .*
> %s
> `, regexp.QuoteMeta(expectations.body)))
> ```

closing paren on the next line please so that it lines up with the indentation of the `issueBodyRe, err :=` line, if it's all the same to you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329)*

**Comment by jordanlewis** [comment]
TFTRs

---

Review status: 1 of 2 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/cmd/github-post/main.go, line 139 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-KbuRbd6pGynDB1EHqK3:-KbuTn1cf5RKQXXeCNFY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/239be76a1427b1aa7ba790c578e0fb3cc0de4c23/pkg/cmd/github-post/main.go#L139)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

gosh, this is hard to read. how about

```
body := fmt.Sprintf(bodyTemplate, sha, parametersStr, u.String()) + "\n\n```\n%s\n```"
```
</blockquote></details>

Done.

---

*[pkg/cmd/github-post/main.go, line 190 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-KbuRxLRi3Q1_2f19bit:-KbuTnbPO1ovL-rIb79m:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/239be76a1427b1aa7ba790c578e0fb3cc0de4c23/pkg/cmd/github-post/main.go#L190)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

there needs to be a `%s` or something in here.
</blockquote></details>

Done.

---

*[pkg/cmd/github-post/main_test.go, line 116 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-KbuStc7WXNux8ae0H2r:-KbuTov-Vv5vDx9_OdEG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/239be76a1427b1aa7ba790c578e0fb3cc0de4c23/pkg/cmd/github-post/main_test.go#L116)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

closing paren on the next line, if it's all the same to you.
</blockquote></details>

Done.

---

*[pkg/cmd/github-post/main_test.go, line 123 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-KbuSc3Bhs0-mTM6OxaA:-KbuTpGSQr1F6xiHzXFa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/239be76a1427b1aa7ba790c578e0fb3cc0de4c23/pkg/cmd/github-post/main_test.go#L123)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

closing paren on the next line please so that it lines up with the indentation of the `issueBodyRe, err :=` line, if it's all the same to you.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329#-:-KbuTqHZrVWYqf7DEFi6:b-814g6a)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13329)*

**Comment by jordanlewis** [comment]
https://github.com/cockroachdb/cockroach/issues/13014#issuecomment-276890554 Aww yiss.

**Pull request merged**
