### PR TITLE
ui: update error messages on date picker

### PR DESCRIPTION
**Pull request by maryliag**
Update error messages on date picker on Statements
and Transaction pages to more specific error messages.

New error messages:
Screen Shot 2021-09-10 at 6 12 48 PM
Screen Shot 2021-09-10 at 6 12 59 PM

Release justification: Category 4
Release note (ui change): update error message on date picker
on Statements and Transactions page.

### CODE REVIEW

**Review by xinhaoz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70053#-:-MjGYgyo5Ontd171-wZ8:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Annebirzin and @kevin-v-ngo)

**Comment by kevin-v-ngo** [comment]
Thanks for quickly getting this fix in @maryliag. @Annebirzin/@ianjevans , any guidelines on error messages format?

I didn't give it much thought in the confluence page but here's my proposal:

Please select an end time that is after the start time.
Please select a date and time that is not in the future.

**Comment by Annebirzin** [comment]
Chatted with Marylia about the copy, we'll go with: 

```
Select an end time that is after the start time.
Select a date and time that is not in the future.
```

**Comment by maryliag** [comment]
Updated :) 
I also updated the images on the PR description

**Comment by maryliag** [comment]
Updated label to use "Start" and "End" from @Annebirzin feedback

**Review by kevin-v-ngo — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70053)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Annebirzin)

**Review by Annebirzin — APPROVED** [review]

**Pull request merged**
