### PR TITLE
changefeedccl: mark avro format as no longer experimental

### PR DESCRIPTION
**Pull request by HonoreDB**
The avro format for changefeeds now supports all column types
and has been in production use for several releases.
We'll now allow format=avro rather than format=experimental_avro
The old string will remain supported because job payloads can
persist across upgrades and downgrades.

Release note (enterprise change): changefeed avro format no longer marked experimental

### CODE REVIEW

**Review by miretskiy — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68818)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @spiffyyeng, and @stevendanna)

___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68818#-MgxKeVQEnmu0UqhFeyr:-MgxKeVQEnmu0UqhFeys:b-qfoy5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/2872f8d1940854bb89d82db00a7a44f6f246b519/pkg/ccl/changefeedccl/changefeed_stmt.go#L159)):*
> ```Go
> 
> 		if opts[changefeedbase.OptFormat] == changefeedbase.DeprecatedOptFormatAvro {
> 			//TODO(zinger): See if there's a way to make this work with sinkless
> ```

i guess no... i'd just drop this todo...
___
*[pkg/ccl/changefeedccl/helpers_test.go, line 654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68818#-MgxKr_C7BxZxxE2k7gY:-MgxKr_D856x0rbGdYiL:b-32h3g9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2872f8d1940854bb89d82db00a7a44f6f246b519/pkg/ccl/changefeedccl/helpers_test.go#L654)):*
> ```Go
> // a lot of cdc test framework, use with caution. Driver-agnostic tools don't
> // have clean ways of inspecting incoming notices.
> func expectNotice(t *testing.T, s serverutils.TestServerInterface, sql string, expected string) {
> ```

i won't mind if this very minor detail was left outside of tests...
Like: try it manually; see if you get the notice and don't blow anything up... I'm not sure i'd necessarily test for that.

**Review by spiffyy99 — APPROVED** [review]

**Comment by HonoreDB** [comment]
bors r=[miretskiy, spiffyeng]

**Review by HonoreDB — COMMENTED** [review]
Thanks for the reviews!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68818#-:-Mh-1eTZ7FPJKwAkGEa_:b-hlc8bm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @stevendanna)

___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68818#-MgxKeVQEnmu0UqhFeyr:-Mh-1h2Y7qAEe9pkGMNX:b-o6slzc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2872f8d1940854bb89d82db00a7a44f6f246b519/pkg/ccl/changefeedccl/changefeed_stmt.go#L159)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

i guess no... i'd just drop this todo...
</blockquote></details>

Ah well. Done.
___
*[pkg/ccl/changefeedccl/helpers_test.go, line 654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68818#-MgxKr_C7BxZxxE2k7gY:-Mh-1kc6Amj54WimQAwm:bchcgs2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2872f8d1940854bb89d82db00a7a44f6f246b519/pkg/ccl/changefeedccl/helpers_test.go#L654)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

i won't mind if this very minor detail was left outside of tests...
Like: try it manually; see if you get the notice and don't blow anything up... I'm not sure i'd necessarily test for that.
</blockquote></details>

Yeah, testing this was one of those things where I thought it'd be easy and it ended up taking way too long and being awkward but at that point I was emotionally committed. I usually just grumble and delete the code when that happens but eh, it's a cheap test.

**Comment by HonoreDB** [comment]
bors retry

**Pull request merged**
