### PR TITLE
jobs: ensure newly created adoptable jobs populate the job_type column

### PR DESCRIPTION
**Pull request by jayshrivastava**
The `job_type` column in the `system.jobs` table is not being populated when jobs are created by `CreateAdoptableJobWithTxn`. This change updates that function to populate the column.

Release note: none
Epic: none

### CODE REVIEW

**Review by jayshrivastava — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96747)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[`pkg/jobs/registry.go` line 636 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96747#-NNhm3yGBO46auu3na4g:-NNhm3yGBO46auu3na4h:b-a4ks) ([raw file](https://github.com/cockroachdb/cockroach/blob/abce491c3793522bbf83ccbf8585bb2eb8aaab77/pkg/jobs/registry.go#L636)):*
> ```Go
> 		values := [7]interface{}{jobID, StatusRunning, payloadBytes, progressBytes, createdByType, createdByID, typ}
> 		if !r.settings.Version.IsActive(ctx, clusterversion.V23_1AddTypeColumnToJobsTable) {
> 			nCols -= 1
> ```

@ajwerner, do you know what's going on [here](https://github.com/postamar/cockroach/blob/08f2dc4e4e523d97c228bb0665f3859d920084f4/pkg/jobs/registry.go#L548-L558) from [this commit](https://github.com/cockroachdb/cockroach/pull/94774/commits/08f2dc4e4e523d97c228bb0665f3859d920084f4)? 

It claims the version gate is not enough. From reading the commit description and code, I don't really see why. It looks like the commit fixes the problem mentioned in the commit message and the changes to the version gate are superfluous.

**Review by ajwerner — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96747)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava)

___
*[`pkg/jobs/registry.go` line 636 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96747#-NNhm3yGBO46auu3na4g:-NNi988T2avPC_HaQBMm:b-2adye0) ([raw file](https://github.com/cockroachdb/cockroach/blob/abce491c3793522bbf83ccbf8585bb2eb8aaab77/pkg/jobs/registry.go#L636)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

@ajwerner, do you know what's going on [here](https://github.com/postamar/cockroach/blob/08f2dc4e4e523d97c228bb0665f3859d920084f4/pkg/jobs/registry.go#L548-L558) from [this commit](https://github.com/cockroachdb/cockroach/pull/94774/commits/08f2dc4e4e523d97c228bb0665f3859d920084f4)? 

It claims the version gate is not enough. From reading the commit description and code, I don't really see why. It looks like the commit fixes the problem mentioned in the commit message and the changes to the version gate are superfluous.  
</blockquote></details>

Yeah, that seems right. At first I was worried about it implying that the gate did not wait for one version, but I think it it does wait for the leases to drain in the migration. I think what that means is that if the version is active, you must have the version of the table with the new column.

**Review by stevendanna — APPROVED** [review]

**Comment by jayshrivastava** [comment]
bors r=ajwerner,stevendanna

**Comment by jayshrivastava** [comment]
TYFRs!

**Pull request merged**
