### PR TITLE
backupccl, restoreccl: include system.privileges in full cluster restore

### LINKED ISSUE #84762: sql, bulkio: support backup restore for system.privileges table
Currently `system.privileges` is opt out of full cluster restores meaning certain privileges are not restored.

We should opt it in, there shouldn't be much work to do other than validating the privilege path.

Jira issue: CRDB-17851
Epic CRDB-11725

### PR DESCRIPTION
**Pull request by RichardJCai**
Release justification: Minor enhancement to not yet released feature

Release note: None

Fixes https://github.com/cockroachdb/cockroach/issues/84762

### CODE REVIEW

**Review by stevendanna — COMMENTED** [review]
:lgtm: 

There are a few other tests to update:

- TestClusterRestoreFailCleanup has a some lists of tables that should transition to a DROP state on revert. We need to add this new table to that list:

https://github.com/cockroachdb/cockroach/blob/1fadff69783c836ddfa391b02d85437be59bba2b/pkg/ccl/backupccl/full_cluster_backup_restore_test.go#L640
https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/backupccl/full_cluster_backup_restore_test.go#L732

If you are feeling generous, you could also add it to:

https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/backupccl/full_cluster_backup_restore_test.go#L732

**Comment by RichardJCai** [comment]
CI failure is flake
Thanks for reviewing!

bors r=stevendanna

**Comment by RichardJCai** [comment]
Nvm need github approval @stevendanna

**Review by stevendanna — APPROVED** [review]

**Comment by stevendanna** [comment]
bors r=stevendanna

**Pull request merged**
