### PR TITLE
sql: fix serialization of datums and prefix casts

### LINKED ISSUE #12532: TestLogic/testdata/views fails with COCKROACH_DISTSQL_MODE=on
In distsql mode, this pair of statements fails as below:
```
CREATE VIEW dt AS SELECT d, t FROM t WHERE d > DATE '1988-11-12' AND t < TIMESTAMP '2017-01-01'
SELECT * FROM dt
```

```
    	logic_test.go:1274: testdata/views:338: expected success, but found
    		pq: unsupported comparison operator: <date> > <string>
```

This likely has to do with the serialization of the expressions - `DATE`, `TIMESTAMP` disappear:
image

### PR DESCRIPTION
**Pull request by RaduBerinde**
Removing the "prefix" syntax for `CastExpr`s; we now prepend the type as part of
Datum formatting (conditional on a new `FmtFlag`). This ensures that expressions
that contain `DDInterval`, `DDate` etc (without a `CastExpr`) can be formatted
and re-parsed correctly.

To avoid a redundant cast, we elide the `CastExpr` during type checking if the
argument is a constant that can become the required type.

See #12532 for more context.

Fixed #12532.

Note: the current change breaks a lot of tests that encode expressions (like TestSimplifyExpr, parse tests), I want to get feedback on the change before I go through correcting them.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12836)

### CODE REVIEW

**Comment by knz** [comment]
What was the rationale for having the format flag negated? (why did you chose `noDatumTypes` instead of `showDatumTypes`? We could then have `showDatumTypes` only when printing out the things for view descs)

---

Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/parser/datum.go, line 396 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-Ka9UGwZrnIem2XIL-gq:-Ka9UGw_SKoCJ6m8C0ZX:b-ky5i5p) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae3de58fe9ec21e680636784bc7552b398dc4d92/pkg/sql/parser/datum.go#L396)):*
> ```Go
> // Format implements the NodeFormatter interface.
> func (d *DFloat) Format(buf *bytes.Buffer, f FmtFlags) {
> 	if !f.noDatumTypes {
> ```

Don't do this special casing here. Do it just once for all ambiguous datum types in `FormatNode` (format.go).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-:-Ka9UVqOeTUtEssY7JSM:b-k4wylo)*

**Comment by RaduBerinde** [comment]
I figured that without them the expression may not be valid and we shouldn't print out invalid expressions. I don't have a strong opinion here though..

---

Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-:-Ka9a_SOhOXWVIxVhE0N:b-xxz55l)*

**Comment by knz** [comment]
I think we ought to distinguish "pretty printing and expr for a human" and "serializing an expr in a format that is deserializable and also as much as possible readable by a human". Perhaps we should have different function names for these two things, and use them in the appropriate contexts.

**Comment by RaduBerinde** [comment]
*[pkg/sql/parser/datum.go, line 396 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-Ka9UGwZrnIem2XIL-gq:-KaCo-uWr9cT_6fMEeRN:blpjcue) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae3de58fe9ec21e680636784bc7552b398dc4d92/pkg/sql/parser/datum.go#L396)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Don't do this special casing here. Do it just once for all ambiguous datum types in `FormatNode` (format.go).
</blockquote></details>

But there is no generic way to do that since it applies only to some nodes (Datums with some types).. So we would have a big `switch` in `FormatNode`? Doesn't that go against the model of each node having its own `Format` function?

Or are you suggesting to include an explicit cast for all constants? (although that still requires a switch to only apply it to Datum nodes no?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836)*

**Comment by RaduBerinde** [comment]
Ok, take two. Please ignore the first two commits (I sent out a separate PR for those).

I reversed the meaning of the flag; it's now only enabled as part of a new `FmtParsable`, used by distsql and views. Let me know if this makes more sense.

I also found that we can't elide the `CastExpr` in all cases (e.g. `'hello'::char(2)`). I made the check more strict to only elide the cast for types that can't have any parameters.

---

Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-:-KaD3PvTvSqOIg3AG26X:bu45znn)*

**Comment by nvanbenschoten** [comment]
The changes here look good in general, but we should walk through all of the places where `Expr.String` is used and make sure it's being used correctly. I can imagine there are a number of places where it is being used when the properties of this new `FmtParsable` mode are actually desired.

Also, we are starting to overlap with #12611, which has related complications. It might not be worth worrying about yet, but does the second part of @knz's proposed plan there influence your design here at all? Perhaps instead of enforcing datum types through a formatting mode, we have a new tree transformation that can either annotate all expressions with `TypeAnnotations` ("full mode", needed for that issue) or only annotate enough to allow serialization-deserialization round-tripping ("parsable mode", needed for this issue). Just a thought, which may be mutual based on [this](https://github.com/cockroachdb/cockroach/issues/12532#issuecomment-271629335) comment from yesterday.

---

Reviewed 10 of 10 files at r4.
Review status: 10 of 14 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/create.go, line 387 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-KaDm92hcbY2xqBdVcJG:-KaDm92hcbY2xqBdVcJH:b-n9y3uu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a58315ee38cac39685aeda4eecae2e5892e21b6/pkg/sql/create.go#L387)):*
> ```Go
> 	var queryBuf bytes.Buffer
> 	var fmtErr error
> 	n.AsSource.Format(
> ```

I think we need to do the same thing with persisted expressions on `TableDescriptors`, like `DEFAULT`, `CHECK`, and `REFERENCED`.

---

*[pkg/sql/parser/datum.go, line 396 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-Ka9UGwZrnIem2XIL-gq:-KaDkWTjIaHqHJPJ67Jq:b-54x1lk) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae3de58fe9ec21e680636784bc7552b398dc4d92/pkg/sql/parser/datum.go#L396)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

But there is no generic way to do that since it applies only to some nodes (Datums with some types).. So we would have a big `switch` in `FormatNode`? Doesn't that go against the model of each node having its own `Format` function?

Or are you suggesting to include an explicit cast for all constants? (although that still requires a switch to only apply it to Datum nodes no?)
</blockquote></details>

I personally am fine with this approach FWIW.

---

*[pkg/sql/parser/type_check.go, line 211 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-KaDl5T9LFWYNhamzL8T:-KaDl5T9LFWYNhamzL8U:b-dcrvil) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a58315ee38cac39685aeda4eecae2e5892e21b6/pkg/sql/parser/type_check.go#L211)):*
> ```Go
> 			// precision), the CastExpr becomes a no-op and can be elided.
> 			switch expr.Type.(type) {
> 			case *BoolColType, *DateColType, *TimestampColType, *TimestampTZColType, *IntervalColType,
> ```

long line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-:-KaDn548xvy9xSWHmhDV:b-18wc2c)*

**Comment by RaduBerinde** [comment]
There is definitely overlap with #12611 - this change solves a big part of the problem, that of interpreting literals/constants with the same types. The other concerns - around a function changing its return type - are something that we hold more control over and might not be problems in practice; in any case, we could add on top of the infrastructure proposed here to output function return types as well.

---

Review status: 10 of 14 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-:-KaE0-2FE6XKPC8Q3POl:bddodov)*

**Comment by RaduBerinde** [comment]
Review status: 7 of 17 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/create.go, line 387 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-KaDm92hcbY2xqBdVcJG:-KaECjUaTQiVj7LqL_AH:bxphb7a) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a58315ee38cac39685aeda4eecae2e5892e21b6/pkg/sql/create.go#L387)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think we need to do the same thing with persisted expressions on `TableDescriptors`, like `DEFAULT`, `CHECK`, and `REFERENCED`.
</blockquote></details>

Thanks, great point! Done for default and check. I don't think FK references have any expressions.

---

*[pkg/sql/parser/type_check.go, line 211 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-KaDl5T9LFWYNhamzL8T:-KaECtXtyTkmMxv4tn0L:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a58315ee38cac39685aeda4eecae2e5892e21b6/pkg/sql/parser/type_check.go#L211)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

long line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836)*

**Comment by knz** [comment]
Mostly LGTM. Will want to have a look again when all the tests pass.

---

Reviewed 4 of 12 files at r2, 3 of 6 files at r3, 1 of 10 files at r4, 6 of 6 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/datum.go, line 396 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-Ka9UGwZrnIem2XIL-gq:-KaHZjfYS_Th8Bzz98QM:b-ifa7tj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae3de58fe9ec21e680636784bc7552b398dc4d92/pkg/sql/parser/datum.go#L396)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I personally am fine with this approach FWIW.
</blockquote></details>

Ok I've decided I'm fine either way too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-:-KaH_3R00i8UnaBfXkY0:b-70dhay)*

**Comment by RaduBerinde** [comment]
Thanks! Updated. The fixes around `INTERVAL` are basically a revert of my earlier misguided change #10712.

**Comment by nvanbenschoten** [comment]
:lgtm: My only remaining question is why the removal of the two `castSyntaxMode`s is still needed. Did the CastExpr nesting issue from #12532 not go away fully when we elided the `CastExpr` on constants?

---

Reviewed 1 of 6 files at r5, 7 of 7 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-:-KaJrIxbZlZ3QXpIT-sm:b6ijym8)*

**Comment by RaduBerinde** [comment]
I don't think it's necessary for the cases we've seen but I figured it's an incorrect way to format a cast in general and given that we have a lot of code that manipulates expressions it's hard to say for sure that the enclosed expression will always stay a constant.

By the way, `castPrefixParens` seems incorrect to me  - formats `INTERVAL ( .. ) '1h'` as `INTERVAL ('1h')`.


I was looking at writing some tests and I am realizing this doesn't quite work as intended.. It turns out that the `TYPENAME xx` notation only works if `xx` is a string. Things like `DECIMAL 1.2` don't parse.. So I think I should replace the annotations I added with actual casts `(1.2::DECIMAL`), what do you think?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-:-KaK9FKAh3sr25I4_moC:bemyqkp)*

**Comment by nvanbenschoten** [comment]
Ah good catch. We should almost certainly prefer type annotations to casts
in this situation then. The semantics might work out to be the same, but
each carries a different connotation.

**Comment by RaduBerinde** [comment]
So `1.2:::DECIMAL` correct?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-:-KaKHMuUb7CHTA9urKgz:b-f8v6zk)*

**Comment by nvanbenschoten** [comment]
Right. And actually the semantics wouldn't even be the same. Casts would only desire the type, while annotations would require it. We want the latter here.

If we're going to do this approach, we can probably unify the implementation ala @knz's suggestion about `FormatNode`.

**Comment by RaduBerinde** [comment]
What do you mean casts only desire the type? If the cast isn't possible, that is an "invalid cast" error no?

One thing I'm wondering about is whether we will end up with two annotations which doesn't work (unlike casts) - would it be possible to ever (after some expression manipulation perhaps) have a `DString` insidea a `TypeAnnotation` and end up with something like `'1s':::STRING:::INTERVAL'?

I was also thinking of switching these `INTERVAL 'xx'` casts to `TypeAnnotation` as well but I'm worried about the above.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-:-KaKHj0t8Mai2Szvk_Px:b-irlrkt)*

**Comment by nvanbenschoten** [comment]
What I mean is that a `CastExpr` will try to perform whatever transformation it can to create the desired type from its subexpression, after desiring that type during the type check recursion. On the other hand, the `AnnotateTypeExpr` will require that type during the type check recursion. In practice when dealing with `Constants`, this just means that the `CastExpr` will be a little more permissive. For example: `'123'::int` will work but `'123':::int` wont. In this situation, we don't need (or particularly want) the extra permissiveness.

I can't think of any situation where it would be possible to get a `DString` inside of an `AnnotateTypeExpr` like you mentioned for two reasons. First, a DString inside of a type annotation for a different type would throw a type error during type checking. Second, a datum inside of a type annotation for its type will be constant evaluated during normalization.

I had the same idea a little while ago about switching the `INTERVAL 'xx'` casts to `AnnotateTypeExpr` as well, but it seemed like a big jump back then. Now that it looks like we're converging to that idea, and especially because we're considering formatting datums with type annotations, I think it's worth some consideration.

**Comment by RaduBerinde** [comment]
Yeah I thought about it a bit and I don't think the case I mentioned could happen either. Sorry, you guys mentioned `TypeAnnotation` it in the issue but I was confused about what you meant (I was looking for that symbol instead of `AnnotateTypeExpr`). I'll give it a shot.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-:-KaMn1hpdZZPJJFTLrQr:bubdff7)*

**Comment by RaduBerinde** [comment]
Wait, it seems we will actually have the exact same problem. `AnnotateTypeExpr.TypeCheck` replaces `.Expr` in place with the type-checked expression. So `INTERVAL 'xx'` will become an `AnnotateTypeExpr` that wraps a `DInterval`, which would serialize as a double type annotation. This will also leak in the original expression since it's an in-place change (as we saw with cast).

Should we make `AnnotateTypeExpr.TypeCheck` just return the underlying expression instead?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-:-KaMq6_KzQfaIhP8VxWW:b-qm54ol)*

**Comment by RaduBerinde** [comment]
Argh.. I was just about to post a new version but I found the following case `DECIMAL '1.5'` (which we use in tests, and works in PG) doesn't work anymore if we change to a type annotation. So I guess we're stuck with using casts for these.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-:-KaNFB1Qk--jqgXuIUmF:bm3cb75)*

**Comment by RaduBerinde** [comment]
Ok, please check the latest version (and my ramblings above for context):
 - a new FmtFlag adds type annotations to datums and placeholders. This ensures
   that expressions that contain `DDInterval`, `DDate` can be formatted and
   re-parsed correctly. This replaces ad-hoc type prepending like
   `INTERVAL '..'` or `DATE '..'`.

 - `CastExpr.TypeCheck` now returns the underlying type-checked expression
   directly when it is a constant of the right type.

 - `castPrefix` (renamed to `castPrepend`) now only functions if the
   underlying expression is a string literal. `castPrefixParens` is removed (it
   was incorrect).

 - `AnnotateTypeExpr.TypeCheck` now returns the underlying type-checked
   expression rather than changing the `AnnotateTypeExpr` in-place and
   returning it (which could result in double annotations with the new
   `FmtFlag`). `AnnotateTypeExpr` is no longer a `TypedExpr` so it is never part
   of a type-checked expression (which makes sense).

 - type checking tests are extended to verify the serliazed type-checked 
   expression, which verifies both serialization and type resolution.

---

Review status: 8 of 17 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-:-KaNPcny-e-az80m2Cxa:blozit0)*

**Comment by nvanbenschoten** [comment]
Reviewed 8 of 9 files at r7.
Review status: 16 of 17 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/format.go, line 138 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-KaPJUcT8i89YoqRrhmG:-KaPJUcUyugmPP-4Ers8:b-edt6kt) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f87a27d20d2b12aba3bc1d02a5870f832613b23/pkg/sql/parser/format.go#L138)):*
> ```Go
> 	n.Format(buf, f)
> 	if f.disambiguateDatumTypes {
> 		// We don't need annotations for types like DBool, DInt, DNull, DTuple.
> ```

We do for `DInt`, as `1` is still ambiguous (it can become all numeric types if desired).

I would lean towards making this a method (`AmbiguousFormat() bool`) so that future datum types don't miss it.

---

*[pkg/sql/parser/type_check_test.go, line 38 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-KaPLvHoJGjvfURyb0k9:-KaPLvHoJGjvfURyb0kA:b-hdekiq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f87a27d20d2b12aba3bc1d02a5870f832613b23/pkg/sql/parser/type_check_test.go#L38)):*
> ```Go
> 		expected string
> 	}{
> 		{`NULL + 1`, `NULL`},
> ```

Why is this being normalized?

---

*[pkg/sql/parser/type_check_test.go, line 46 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-KaPL5cU4_qZmGHjAf3p:-KaPL5cU4_qZmGHjAf3q:b-4wvc7z) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f87a27d20d2b12aba3bc1d02a5870f832613b23/pkg/sql/parser/type_check_test.go#L46)):*
> ```Go
> 		{`NULL + 'hello'::bytes`, `NULL`},
> 		{`INTERVAL '1s'`, `'1s':::interval`},
> 		{`(1.1::decimal)::decimal`, `(1.1:::decimal::DECIMAL)::DECIMAL`},
> ```

The reason for the different case is because your `AnnotateTypeExpr` uses a `CastTargetType` (I think it should actually be a `ColumnType`, but ignore that for now) while your new `disambiguateDatumTypes` check uses a `Type`. Consider changing 
```
buf.WriteString(n.(Datum).ResolvedType().String())
```
to
```
FormatNode(buf, f, DatumTypeToColumnType(n.(Datum).ResolvedType()))
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/parser/type_check_test.go, line 38 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-KaPLvHoJGjvfURyb0k9:-KaPOqPpXoqt4tAWHhrf:b7yepi2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f87a27d20d2b12aba3bc1d02a5870f832613b23/pkg/sql/parser/type_check_test.go#L38)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why is this being normalized?
</blockquote></details>

I could ask you the same question sir! Looks like `BinaryEx[r.TypeCheck` [does that](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/parser/type_check.go#L124) when one of the operands has the null type.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/parser/format.go, line 138 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-KaPJUcT8i89YoqRrhmG:-KaPPpcaMbsA_xxcgBKt:bsxoe5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f87a27d20d2b12aba3bc1d02a5870f832613b23/pkg/sql/parser/format.go#L138)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We do for `DInt`, as `1` is still ambiguous (it can become all numeric types if desired).

I would lean towards making this a method (`AmbiguousFormat() bool`) so that future datum types don't miss it.
</blockquote></details>

I figured that if the expression type checks with `1`interpreted as an int, that is what it will be interpreted upon re-parsing and type-checking, am I incorrect? (I'm just curious, I will add it regardless)

I am hesitating between adding a new method and pushing this back down into `Format`.. Seems a bit odd to me to add a different method that controls formatting when we already have a `Format` method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836)*

**Comment by nvanbenschoten** [comment]
Review status: 16 of 17 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/format.go, line 138 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-KaPJUcT8i89YoqRrhmG:-KaPQnUEIo9UBqLbWzPg:b2z8nqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f87a27d20d2b12aba3bc1d02a5870f832613b23/pkg/sql/parser/format.go#L138)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I figured that if the expression type checks with `1`interpreted as an int, that is what it will be interpreted upon re-parsing and type-checking, am I incorrect? (I'm just curious, I will add it regardless)

I am hesitating between adding a new method and pushing this back down into `Format`.. Seems a bit odd to me to add a different method that controls formatting when we already have a `Format` method.
</blockquote></details>

I'm pretty sure you're correct in the case where nothing changes between formatting and parsing, although I still have #12611 on the back of my mind, in which case ambiguity could be introduced.

And that's a good point, though I do think a new method would help separate concerns. I'm fine with either approach, so go with whatever you like best.

---

*[pkg/sql/parser/type_check_test.go, line 38 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-KaPLvHoJGjvfURyb0k9:-KaPPlvn_vGmkzIRy6E1:b-mh5j5d) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f87a27d20d2b12aba3bc1d02a5870f832613b23/pkg/sql/parser/type_check_test.go#L38)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I could ask you the same question sir! Looks like `BinaryEx[r.TypeCheck` [does that](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/parser/type_check.go#L124) when one of the operands has the null type.
</blockquote></details>

Huh.. would you look at that. I guess overload resolution won't really work with NULL operands. I forsee an overhaul of NULL handling in the near future, but in the meantime, carry on!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836)*

**Comment by RaduBerinde** [comment]
Updated, TFTR and for the great suggestions!

---

Review status: 14 of 17 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/parser/format.go, line 138 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-KaPJUcT8i89YoqRrhmG:-KaPWzG57mwD83KNmCjC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f87a27d20d2b12aba3bc1d02a5870f832613b23/pkg/sql/parser/format.go#L138)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm pretty sure you're correct in the case where nothing changes between formatting and parsing, although I still have #12611 on the back of my mind, in which case ambiguity could be introduced.

And that's a good point, though I do think a new method would help separate concerns. I'm fine with either approach, so go with whatever you like best.
</blockquote></details>

Done.

---

*[pkg/sql/parser/type_check_test.go, line 46 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-KaPL5cU4_qZmGHjAf3p:-KaPWyWQ6uf18n8KPHmj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f87a27d20d2b12aba3bc1d02a5870f832613b23/pkg/sql/parser/type_check_test.go#L46)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The reason for the different case is because your `AnnotateTypeExpr` uses a `CastTargetType` (I think it should actually be a `ColumnType`, but ignore that for now) while your new `disambiguateDatumTypes` check uses a `Type`. Consider changing 
```
buf.WriteString(n.(Datum).ResolvedType().String())
```
to
```
FormatNode(buf, f, DatumTypeToColumnType(n.(Datum).ResolvedType()))
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-:-KaPX3XUEiyLcBrVBBF0:bhqbssa)*

**Comment by RaduBerinde** [comment]
Hm, I now see this for `TestShowCreateView`:
```
got: CREATE VIEW T5 AS SELECT s, count(*) FROM d.t GROUP BY s HAVING count(*) > 3:::INT
expected: CREATE VIEW T5 AS SELECT s, count(*) FROM d.t GROUP BY s HAVING count(*) > 3
```

Similar issue - `BinaryExpr.TypeCheck` modifies the expression in place and the operand becomes a `DInt`. Do you think this is ok from a user perspective? @knz, @a-robinson 

---

Review status: 14 of 17 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-:-KaPa1JHWpKecbqtHMr7:b6nm51x)*

**Comment by knz** [comment]
> |got: CREATE VIEW T5 AS SELECT s, count(*) FROM d.t GROUP BY s HAVING
> count(*) > 3:::INT expected: CREATE VIEW T5 AS SELECT s, count(*) FROM
> d.t GROUP BY s HAVING count(*) > 3 |
> 
> Similar issue - |BinaryExpr.TypeCheck| modifies the expression in place
> and the operand becomes a |DInt|. Do you think this is ok from a user
> perspective? 

OK with me

-- 
Raphael 'kena' Poss

**Comment by RaduBerinde** [comment]
I could serialize the expression before type-checking to go around this issue. But it seems that for #12611 we would actually need to go in the opposite direction and actually serialize the type-checked expression, right? Should I do that in this change?

**Comment by nvanbenschoten** [comment]
The failing test actually seems like a good thing to me. It means that the ambiguity of the untyped numeric literal will only be considered once, and from then on, will always be guaranteed to be treated as the same type.

---

Review status: 14 of 18 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-:-Kai8cd38Tks7C_RMEkD:bfm207w)*

**Comment by RaduBerinde** [comment]
Is the latest version good to go?

**Comment by nvanbenschoten** [comment]
:lgtm_strong: 

---

Review status: 14 of 18 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/datum.go, line 166 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-KamWyB4wJ4SfNGGHMDw:-KamWyB5j2_1TwG0hEdj:b3p9k26) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bd50dd1b48700f21c20ec1a626189261fca7bd5/pkg/sql/parser/datum.go#L166)):*
> ```Go
> 
> // AmbiguousFormat implements the Datum interface.
> func (*DBool) AmbiguousFormat() bool { return false }
> ```

nit: I'd move all of these directly above or below their type's respective `Format` methods.

---

*[pkg/sql/parser/type_check.go, line 211 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-KamX8lU0X29kh-m7-d-:-KamX8lU0X29kh-m7-d0:bqpy0bp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bd50dd1b48700f21c20ec1a626189261fca7bd5/pkg/sql/parser/type_check.go#L211)):*
> ```Go
> 			// precision), the CastExpr becomes a no-op and can be elided.
> 			switch expr.Type.(type) {
> 			case *BoolColType, *DateColType, *TimestampColType, *TimestampTZColType,
> ```

We can't do this for column types that can have parameters but don't in this case? Like `1::INT`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-:-KamXYbthnW69lBp5K37:b-uwkowd)*

**Comment by RaduBerinde** [comment]
Review status: 14 of 18 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/parser/datum.go, line 166 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-KamWyB4wJ4SfNGGHMDw:-Kan9mmDe-n4tcKSDFa_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bd50dd1b48700f21c20ec1a626189261fca7bd5/pkg/sql/parser/datum.go#L166)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: I'd move all of these directly above or below their type's respective `Format` methods.
</blockquote></details>

Done.

---

*[pkg/sql/parser/type_check.go, line 211 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-KamX8lU0X29kh-m7-d-:-Kan8ddDu8AD5YKsgZf-:bh4lwdx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bd50dd1b48700f21c20ec1a626189261fca7bd5/pkg/sql/parser/type_check.go#L211)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We can't do this for column types that can have parameters but don't in this case? Like `1::INT`?
</blockquote></details>

We could, do you think it's worth it?  I didn't do it because it would be a bunch of cases that depend on each type... pehaps we should add a method to `CastType` so each type can decide if a cast can be elided?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836)*

**Comment by nvanbenschoten** [comment]
Review status: 14 of 18 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/type_check.go, line 211 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-KamX8lU0X29kh-m7-d-:-KaxPXglBTI7XpqyfXAv:bqdsfi1) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bd50dd1b48700f21c20ec1a626189261fca7bd5/pkg/sql/parser/type_check.go#L211)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We could, do you think it's worth it?  I didn't do it because it would be a bunch of cases that depend on each type... pehaps we should add a method to `CastType` so each type can decide if a cast can be elided?
</blockquote></details>

I don't think so. Let's push this as is. I actually need to open an issue for CastExpr to handle column type parameters anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836)*

**Comment by nvanbenschoten** [comment]
Review status: 14 of 18 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/type_check.go, line 211 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836#-KamX8lU0X29kh-m7-d-:-KaxTVO1UEGZhw1ze4op:b-bjooch) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bd50dd1b48700f21c20ec1a626189261fca7bd5/pkg/sql/parser/type_check.go#L211)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I don't think so. Let's push this as is. I actually need to open an issue for CastExpr to handle column type parameters anyway.
</blockquote></details>

Follow up issue #13024.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12836)*

**Pull request merged**
