### PR TITLE
kvserver: add `leases.requests.latency` metric

### PR DESCRIPTION
**Pull request by erikgrinaker**
This patch adds a histogram of lease request latencies. It includes all request types (acquisitions, transfers, and extensions) and all outcomes (successes and errors), but only considers the coalesced lease requests regardless of the number of waiters and how long they have been waiting for.

Epic: none
Release note (ops change): Added a metric `leases.requests.latency` recording a histogram of lease request latencies.

### CODE REVIEW

**Review by andrewbaptist — APPROVED** [review]
:lgtm: Note that you need to update the chart_catalog also to get this to be mergeable (or wait for Tobi to delete it).

**Comment by erikgrinaker** [comment]
bors retry

**Comment by erikgrinaker** [comment]
bors retry

**Comment by erikgrinaker** [comment]
bors retry

**Comment by erikgrinaker** [comment]
bors retry

**Pull request merged**
