### PR TITLE
opt: rework tests involving scalar expressions

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: simplify execbuilder.BuildScalar

In all uses of BuildScalar, we map variables directly to columns in
the metadata. This change simplifies the interface and makes an
indexed var container internally.

Release note: None

#### opt: rework scalar optbuilder tests

This change reworks the infrastructure for tests involving scalars.
Instead of passing a list of types and using thing like `@1` to refer
to variables, we define variables with names. This makes the tests a
lot cleaner and doesn't rely on an obscure syntax. It will also allow
extending the variable definitions (e.g. computed column expressions).

The new infrastructure will be used for other scalar tests (most
importantly, index constraints and partial predicate implication).

Release note: None

#### opt: update memo/expr_test to use ScalarVars

Release note: None

#### opt: update composite_sensitive test to use ScalarVars

Release note: None

#### opt: update implicator tests to use ScalarVars

Release note: None

#### opt: update idxconstraint tests to use ScalarVars

Release note: None

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
This is beautiful. :lgtm: 

> Reviewed 4 of 4 files at r1, 4 of 4 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 6 of 6 files at r5, 15 of 15 files at r6, 4 of 4 files at r7, 2 of 2 files at r8, 2 of 2 files at r9, 6 of 6 files at r10, 9 of 9 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55792#-:-MKB9NT99w_sRMu-Gvkj:b-chor7a)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/idxconstraint/index_constraints_test.go, line 263 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/55792#-MKB8yj642PPIMv6e-mY:-MKB8yj642PPIMv6e-mZ:be2n5dx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2eb3ea3f0d59383f2816cfdb42b3c57a0ead0f94/pkg/sql/opt/idxconstraint/index_constraints_test.go#L263)):*
> ```Go
> 		fields := strings.Fields(colStrs[i])
> 		id := findCol(fields[0])
> 		columns[i] = opt.MakeOrderingColumn(opt.ColumnID(id), false /* descending */)
> ```

[nit] `opt.ColumnID(id)` should no longer be necessary here

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55792)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/idxconstraint/index_constraints_test.go, line 263 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/55792#-MKB8yj642PPIMv6e-mY:-MKB_XAs8A42ErU6qsBu:bexegmu) ([raw file](https://github.com/cockroachdb/cockroach/blob/2eb3ea3f0d59383f2816cfdb42b3c57a0ead0f94/pkg/sql/opt/idxconstraint/index_constraints_test.go#L263)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] `opt.ColumnID(id)` should no longer be necessary here
</blockquote></details>

Done, TFTR!

**Review by mgartner — APPROVED** [review]
> Reviewed 2 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55792)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

**Review by rytaft — APPROVED** [review]
:lgtm: looks like this was a lot of work!

> Reviewed 2 of 4 files at r1, 1 of 15 files at r6, 4 of 4 files at r14, 2 of 2 files at r15, 2 of 2 files at r16, 6 of 6 files at r17, 11 of 11 files at r18.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55792#-:-MKFGkAMC38h5gucMdBt:bf8ocf4)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
