### PR TITLE
opt: wrap virtual computed column projections in a cast

### LINKED ISSUE #91817: roachtest/sqlsmith: projected column has inconsistent type
roachtest.sqlsmith/setup=rand-tables/setting=no-ddl [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=7490759&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=7490759&tab=artifacts#/sqlsmith/setup=rand-tables/setting=no-ddl) on release-22.1 @ [4ca19806493494cfbe881cb86685079fe15a9f0d](https://github.com/cockroachdb/cockroach/commits/4ca19806493494cfbe881cb86685079fe15a9f0d):

```
The test failed on branch=release-22.1, cloud=gce:
test artifacts and logs in: /artifacts/sqlsmith/setup=rand-tables/setting=no-ddl/run_1
	sqlsmith.go:265,sqlsmith.go:324,test_runner.go:883: error: pq: internal error: unexpected error from the vectorized engine: interface conversion: coldata.Column is coldata.Int64s, not coldata.Int16s
		stmt:
		SELECT
			st_extent('BOX(-0.7749563079365274 0.41180487013507916,-0.19096830653024166 0.8891165377985752)':::BOX2D::GEOMETRY)::BOX2D
				AS col_193163,
			28728:::INT8 AS col_193164,
			tab_104592.col3_2 AS col_193165,
			var_pop(tab_104592.col3_3::INT8) OVER (PARTITION BY tab_104592.col3_3 ORDER BY tab_104592.col3_1, tab_104592.tableoid DESC)::DECIMAL
				AS col_193166,
			1529871493:::OID AS col_193167,
			tab_104592.col3_2 AS col_193168
		FROM
			defaultdb.public.table3@table3_pkey AS tab_104592
		GROUP BY
			tab_104592.col3_2,
			tab_104592.col3_1,
			tab_104592.col3_0,
			tab_104592.crdb_internal_mvcc_timestamp,
			tab_104592.col3_3,
			tab_104592.tableoid
		HAVING
			every(true::BOOL)::BOOL
		ORDER BY
			tab_104592.tableoid, tab_104592.crdb_internal_mvcc_timestamp DESC;
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=rand-tables/setting=no-ddl.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-21441

### PR DESCRIPTION
**Pull request by mgartner**
#### sql/logictest: remove assignment cast TODO

This commit removes a TODO that was partially addressed by #82022.

Informs #73743

Release note: None

#### sql/types: fix T.Identical

This commit fixes a bug in `types.T.Identical` which caused it to return
false for collated string types with a different string-representation
of locales that represents the same locale logically. For example,
collated string types with locales `en_US` and `en_us` would not be
identical, even though these are both valid representations of the same
locale.

There is no release note because this has not caused any known bugs.

Release note: None

#### opt: wrap virtual computed column projections in a cast

optbuilder wraps an assignment cast around a virtual computed column
expression when writing to the table if the expression does not have the
same type as the virtual column. This matches the behavior of all writes
to columns of expressions that don't match the target column type.

However, the same cast was not applied to the projection of the virtual
column expression when reading from the table. This cast is necessary in
order to produce the correct value of the column - the projection must
produce the same value that would have been written to the table if the
column was a stored computed column. This commit corrects optbuilder so
that the cast is correctly added to the projection.

Note that this commit adds a standard cast, not an assignment cast, as a
temporary workaround until #81698 is addressed. This is because an
assignment cast can fail in cases when a regular cast will not. Because
we don't validate that all existing rows can successfully produce a new
virtual column expression during a backfill, adding an assignment cast
to the projection of the virtual column could cause future reads to
error. Once #81698 is addressed, we can change these casts to assignment
casts so that they directly match the values that would be written to
the same column if it were stored.

Fixes #91817
Informs #81698

Release note (bug fix): A bug has been fixed that could produce incorrect
values for virtual computed columns in rare cases. The bug only
presented when the virtual column expression's type did not match the
type of the virtual column.

### CODE REVIEW

**Comment by mgartner** [comment]
Hold off on reviewing - looks like this regressed some query plans. I'll see if there's a way to fix that.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105736)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @msirek)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105736#-NZ2GZGt3Q1wuWgI1JMT):*
Probably #73743.

**Review by mgartner — COMMENTED** [review]
This should be ready for a look now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105736#-:-NZ7MpCJAz20zQ_LmD7B:bxck5mh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @msirek, and @yuzefovich)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105736#-NZ2GZGt3Q1wuWgI1JMT):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Probably #73743.
</blockquote></details>

Fixed, thanks.

**Review by msirek — APPROVED** [review]
:LGTM:

> Reviewed 1 of 1 files at r1, 6 of 6 files at r3, 2 of 2 files at r4, 7 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105736#-:-NZDZq6b2xA1fZ7FXiG6:bmxilld)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @yuzefovich)

___
*[`-- commits` line 34 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/105736#-NZD7uObEQSrv8xbLLL9):*
nit: "the correct the value" --> "the correct value"

**Review by msirek — COMMENTED** [review]
Is the fix for [#73743](https://github.com/cockroachdb/cockroach/issues/73743) coming in a separate PR?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105736#-:-NZD_zdDCu6A_juIfW80:b60g9ss)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @yuzefovich)

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 6 of 6 files at r3, 2 of 2 files at r4, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105736#-:-NZb0-S-6ktNvVVSBi8_:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

**Review by mgartner — COMMENTED** [review]
> Is the fix for [#73743](https://github.com/cockroachdb/cockroach/issues/73743) coming in a separate PR?

I have no plans to fix that one at the moment. I would like to address #81698 soon, though - it can cause lots of problems.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105736#-:-NZb0EXr01hoLwqPjcui:b-qvr7yq)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @yuzefovich)

___
*[`-- commits` line 34 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/105736#-NZD7uObEQSrv8xbLLL9):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

nit: "the correct the value" --> "the correct value"
</blockquote></details>

Done.

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Comment by mgartner** [comment]
blathers backport 23.1

**Pull request merged**
