### PR TITLE
storage: remove duplicate logging of *Replica

### PR DESCRIPTION
**Pull request by tamird**
The contexts are already annotated.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10546)

### CODE REVIEW

**Comment by a-robinson** [comment]
What do the log lines look like after this?

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/storage/replica_raftstorage.go, line 531 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10546#-KW4955SPPzno84k_gVQ:-KW4955SPPzno84k_gVR:betnql6) ([raw file](https://github.com/cockroachdb/cockroach/blob/26cf36fc82bf002015bc8e70c2c6ae00b40eaae0/pkg/storage/replica_raftstorage.go#L531)):*
> ```Go
> 		// or it expired. Let the gossip callback set the info.
> 		ctx := r.AnnotateCtx(context.TODO())
> 		log.Warningf(ctx, "no system config available, cannot determine range MaxBytes", r)
> ```

Need to remove the argument r

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10546#-:-KW49Dv7eH-g4L3d7D_q:b-mar6r9)*

**Comment by RaduBerinde** [comment]
Nice, thanks! :lgtm_strong: 

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10546#-:-KW4ANgiPX3n4Bjd8eZ8:buatl1o)*

**Comment by tamird** [comment]
Here are some samples:
```
I161108 13:21:35.790636 368 storage/replica_raftstorage.go:592  [s3,r1/?:{-}] with replicaID [?], applying preemptive snapshot at index 31 (id=6ebc5452, encoded size=16, 1 rocksdb batches, 21 log entries)
I161108 13:21:35.791530 368 storage/replica_raftstorage.go:595  [s3,r1/?:/M{in-ax}] with replicaID [?], applied preemptive snapshot in 0.001s
I161108 13:21:35.791724 275 storage/store.go:2978  [s3,r1/?:/M{in-ax}] added to replica GC queue (peer suggestion)
```

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/replica_raftstorage.go, line 531 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10546#-KW4955SPPzno84k_gVQ:-KW4AVyGAfhVz4c1vomL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26cf36fc82bf002015bc8e70c2c6ae00b40eaae0/pkg/storage/replica_raftstorage.go#L531)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> Need to remove the argument r
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10546#-:-KW4AN_G3hj_SRMcCuPS:bcu9a15)*

**Review by jordanlewis — APPROVED** [review]

**Comment by tamird** [comment]
Updated to remove duplicate replica ID logging as well.

**Pull request merged**
