### PR TITLE
opt: DISTINCT ON support

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### sql: change DISTINCT ON error message

Changing error message to the phrasing used by postgres.

Release note: None

#### opt: build DISTINCT ON

This change adds optbuilder code for DISTINCT ON.

New tests will be part of a separate commit.

Release note: None

#### opt: don't print ordering for group-by

We currently print the internal ordering for GroupBy et al. This entry
conflicts with the required ordering on the operator itself (soon to
be a problem for DistinctOn).

Removing the ordering; it is not necessary as it will show up as the
required ordering on the input. This behavior is consistent with other
operators with internal orderings (like limit, row-number).

Release note: None

#### opt: pass through stronger orderings for DistinctOn

Similar to Limit, DistinctOn can pass through stronger orderings.

Release note: None

#### opt: optbuilder tests for DISTINCT ON

Release note: None

#### opt: execbuilder tests for DISTINCT ON

Release note: None

#### opt: add more DistinctOn norm tests

Also removing DistinctOn from the reject nulls rule which can never
fire (because either the filter gets pushed through DistinctOn, or we
have FirstAgg aggregates).

Release note: None

### CODE REVIEW

**Review by rytaft — CHANGES_REQUESTED** [review]
:lgtm_strong:  very nice

> Reviewed 2 of 2 files at r1, 27 of 27 files at r8, 7 of 7 files at r9, 7 of 7 files at r10, 8 of 8 files at r11, 2 of 2 files at r12, 2 of 2 files at r13, 7 of 7 files at r14.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28265#-:-LJEbWxpAv2Cwi1JhSKF:b-th5d5y)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/execbuilder/testdata/distinct_on, line 163 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/28265#-LJEZRrLEg57Zmse8U0M:-LJEZRrMCqI_cbAwgJZm:bfhymq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/16b0b2601039814f88493d7349f668c24bdc5786/pkg/sql/opt/exec/execbuilder/testdata/distinct_on#L163)):*
> ```
> ·          spans        ALL          ·           ·
> 
> # Ensure order simplification on DISTINCT ON columns does not simplifying out
> ```

simplifying -> simplify
___
*[pkg/sql/opt/norm/rules/reject_nulls.opt, line 124 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28265#-LJEbNW49uhFeHp9orS6:-LJEbNW49uhFeHp9orS7:bczvwwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7be57ec6408515be82669c16b61ff0932416fe10/pkg/sql/opt/norm/rules/reject_nulls.opt#L124)):*
> ```
> [RejectNullsGroupBy, Normalize, LowPriority]
> (Select
>     $input:(GroupBy | DistinctOn
> ```

Can you add a comment about why this rule doesn't apply to DistinctOn?
___
*[pkg/sql/opt/norm/testdata/rules/groupby, line 78 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28265#-LJE_znF8XcO6_Nz6I0z:-LJE_znF8XcO6_Nz6I1-:btiskop) ([raw file](https://github.com/cockroachdb/cockroach/blob/7be57ec6408515be82669c16b61ff0932416fe10/pkg/sql/opt/norm/testdata/rules/groupby#L78)):*
> ```
>       └── columns: i:2(int!null)
> 
> # Distinct not eliminated because one column is nullable.
> ```

Why did you remove these?
___
*[pkg/sql/opt/optbuilder/distinct.go, line 59 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/28265#-LJEOi8q0w6UPN3P7sZw:-LJEOi8r8hcr_B9lpFJb:bavipdh) ([raw file](https://github.com/cockroachdb/cockroach/blob/8db3fd30ada2bb72bbe80b550ae59de16a28ae9e/pkg/sql/opt/optbuilder/distinct.go#L59)):*
> ```Go
> }
> 
> // buildDistinct builds a set of memo groups that represent a DISTINCT ON
> ```

buildDistinct -> buildDistinctOn
___
*[pkg/sql/opt/optbuilder/distinct.go, line 137 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/28265#-LJEQjEq2ep8p0cVByLR:-LJEQjEq2ep8p0cVByLS:bjfoj0i) ([raw file](https://github.com/cockroachdb/cockroach/blob/8db3fd30ada2bb72bbe80b550ae59de16a28ae9e/pkg/sql/opt/optbuilder/distinct.go#L137)):*
> ```Go
> 	for i, col := range inScope.physicalProps.Ordering.Columns {
> 		if !distinctOnCols.Intersects(col.Group) {
> 			outScope.physicalProps.Ordering.Truncate(i)
> ```

I think you can break out of the loop here. Truncate removes all columns after i.

**Review by andy-kimball — APPROVED** [review]
Overall, :lgtm:, would mostly like more commentary on how orderings work, since it seems non-trivial.

Can you add to the `DistinctOn` comment in `relational.opt`, giving more information on how the ordering field is treated if present? In particular, how its treatment differs from `GroupBy`/`ScalarGroupBy`. Also, explicitly specify that the ordering fields are about "intra-group" ordering rather than "inter-group" ordering. Related to that, add a note that the ordering columns do not have to be a subset of the grouping columns (or that a prefix of the ordering columns need to contain all the grouping columns).

> Reviewed 2 of 2 files at r1, 7 of 7 files at r2, 7 of 7 files at r3, 8 of 8 files at r4, 2 of 2 files at r5, 2 of 2 files at r6, 7 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28265#-:-LJ1KbeD6WCPkCb3sx06:b1jl0gd)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 566 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28265#-LJEo5_x1mFRuhIcltmt:-LJEo5_x1mFRuhIcltmu:buf1eeo) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2af0e17602ecf3ae5a0f8e058e0435b6ad7ec20/pkg/sql/opt/exec/execbuilder/relational_builder.go#L566)):*
> ```Go
> 
> 	// Use the ordering that we require on the child (this is the more restrictive
> 	// between def.Ordering and the ordering required on the DistinctOn itself).
> ```

Maybe:
```
// Use the ordering that we require on the child. This is the more restrictive
// between def.Ordering and the ordering required on the DistinctOn itself.
// Or, if neither ordering implies the other, then it is the def.Ordering.
```
___
*[pkg/sql/opt/exec/execbuilder/testdata/distinct, line 66 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28265#-LJ15qKh7uNW9riAyXKA:-LJ15qKi9J0FdB_9r0qb:bbmv64o) ([raw file](https://github.com/cockroachdb/cockroach/blob/306f0805b512c8e09403f2e246dd17e4f52e0858/pkg/sql/opt/exec/execbuilder/testdata/distinct#L66)):*
> ```
> 
> query TTT
> EXPLAIN SELECT DISTINCT y AS w, z FROM xyz ORDER BY z
> ```

NIT: this test doesn't have the `, z` in the planner tests. I think we modified because of limitations in `optbuilder`. Maybe remove it now, since it's more interesting not to have it?
___
*[pkg/sql/opt/xform/physical_props.go, line 176 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28265#-LJEmntN44es2XupwB0b:-LJEmntN44es2XupwB0c:bebqzxz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2af0e17602ecf3ae5a0f8e058e0435b6ad7ec20/pkg/sql/opt/xform/physical_props.go#L176)):*
> ```Go
> 	case opt.LimitOp, opt.OffsetOp, opt.DistinctOnOp:
> 		if nth == 0 {
> 			// These ops require the ordering in their private, but can pass through a
> ```

An example would be very nice here. I'd also add a comment explaining why `DistinctOn` differs from `GroupBy` in this case: the way the `DistinctOn` physical operator works allows it to retain ordering, whereas the `GroupBy` operator cannot (this might be covered in `relational.opt` instead?).

**Review by RaduBerinde — COMMENTED** [review]
I added some comments, I plan to add more in a follow-up change to make all grouping columns optional in the internal ordering, for both DistinctOn and GroupBy.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28265#-:-LJEwDGSDH-7FruLsYH8:bpg6vev)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 566 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28265#-LJEo5_x1mFRuhIcltmt:-LJEtuCs1N0ke58VWfgG:b-lbzqvd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2af0e17602ecf3ae5a0f8e058e0435b6ad7ec20/pkg/sql/opt/exec/execbuilder/relational_builder.go#L566)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Maybe:
```
// Use the ordering that we require on the child. This is the more restrictive
// between def.Ordering and the ordering required on the DistinctOn itself.
// Or, if neither ordering implies the other, then it is the def.Ordering.
```
</blockquote></details>

It's not possible that neither ordering implies the other. If we have a required ordering on DistinctOn, it's because we can provide it (otherwise an enforcer would be used).
___
*[pkg/sql/opt/exec/execbuilder/testdata/distinct, line 66 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28265#-LJ15qKh7uNW9riAyXKA:-LJEuBQKEjZIy0az9EN_:bbd0jln) ([raw file](https://github.com/cockroachdb/cockroach/blob/306f0805b512c8e09403f2e246dd17e4f52e0858/pkg/sql/opt/exec/execbuilder/testdata/distinct#L66)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: this test doesn't have the `, z` in the planner tests. I think we modified because of limitations in `optbuilder`. Maybe remove it now, since it's more interesting not to have it?
</blockquote></details>

I am retaining that limitation though (specifically that ORDER BY can only refer to projected columns when DISTINCT is used). It's consistent with postgres.
___
*[pkg/sql/opt/exec/execbuilder/testdata/distinct_on, line 163 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/28265#-LJEZRrLEg57Zmse8U0M:-LJEvvAO1k_7a6zjKtCQ:b-6y3qc2) ([raw file](https://github.com/cockroachdb/cockroach/blob/16b0b2601039814f88493d7349f668c24bdc5786/pkg/sql/opt/exec/execbuilder/testdata/distinct_on#L163)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

simplifying -> simplify
</blockquote></details>

I clarified the comment, I think there's actually a problem here but I'll work on that separately (left a TODO).
___
*[pkg/sql/opt/norm/rules/reject_nulls.opt, line 124 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28265#-LJEbNW49uhFeHp9orS6:-LJEoFEH1zNNJ1OPkY-M:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7be57ec6408515be82669c16b61ff0932416fe10/pkg/sql/opt/norm/rules/reject_nulls.opt#L124)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Can you add a comment about why this rule doesn't apply to DistinctOn?
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/testdata/rules/groupby, line 78 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28265#-LJE_znF8XcO6_Nz6I0z:-LJEoGPQCXPRU_zCK2FR:b5pembf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7be57ec6408515be82669c16b61ff0932416fe10/pkg/sql/opt/norm/testdata/rules/groupby#L78)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why did you remove these?
</blockquote></details>

Added the first one back and clarified the comment. Moved the other test to a new section for `ConvertGroupByToDistinct` and added another test there.
___
*[pkg/sql/opt/optbuilder/distinct.go, line 59 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/28265#-LJEOi8q0w6UPN3P7sZw:-LJEq1f-AMxuRbSznokB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8db3fd30ada2bb72bbe80b550ae59de16a28ae9e/pkg/sql/opt/optbuilder/distinct.go#L59)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

buildDistinct -> buildDistinctOn
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/distinct.go, line 137 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/28265#-LJEQjEq2ep8p0cVByLR:-LJEq6s424q3Ufyy_W3t:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8db3fd30ada2bb72bbe80b550ae59de16a28ae9e/pkg/sql/opt/optbuilder/distinct.go#L137)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I think you can break out of the loop here. Truncate removes all columns after i.
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/physical_props.go, line 176 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28265#-LJEmntN44es2XupwB0b:-LJErQdO1i9pUiaVOfmE:b8av69w) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2af0e17602ecf3ae5a0f8e058e0435b6ad7ec20/pkg/sql/opt/xform/physical_props.go#L176)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

An example would be very nice here. I'd also add a comment explaining why `DistinctOn` differs from `GroupBy` in this case: the way the `DistinctOn` physical operator works allows it to retain ordering, whereas the `GroupBy` operator cannot (this might be covered in `relational.opt` instead?).
</blockquote></details>

Done. Added some comments in `relational.opt` too.

**Review by rytaft — APPROVED** [review]
> Reviewed 6 of 7 files at r16, 3 of 7 files at r17, 8 of 9 files at r18, 2 of 2 files at r19, 2 of 2 files at r20, 7 of 7 files at r21.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28265)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
