### PR TITLE
dev: introduce a general purpose dev-tool for crdb engineers

### PR DESCRIPTION
**Pull request by irfansharif**
Our Makefile UX has grown organically over the last six years, and is
now home to various scripts that are orthogonal to simply building the
crdb binary. These include the ability to run linters, building various
useful binaries (such as roachprod, roachtest), running different kinds
of tests (unit tests, logic tests, acceptance tests), and much more.

Now that we're exploring a move towards Bazel for our build system
(#55687), we have a chance to tuck away Bazel specific under a general
purpose dev-tool, larva.

The intent here is to house all day-to-day dev operations under this
tool, written in Go. This will be the component that actually replaces
our Makefile in its entirety. It'll be (predictably) powered by bazel
underneath, but with much nicer UX. It should capturing all common usage
patterns in high-level docs.

Strawman UX (I've only really deliberated on the `test` subcommand):
```
	larva test --pkg=kv/kvserver --filter=TestReplicaGC* -v -show-logs --timeout=1m
	larva test --stress --race ...
	larva test --logic --files=prepare|fk --subtests=20042 --config=local
	larva test --fuzz --pkg=... --filter=Decimal`
	larva bench --pkg=sql/parser --filter=BenchmarkParse
	larva build cockroach --tags=deadlock
	larva build cockroach-oss
	larva build {opt,exec}gen
	larva generate bazel
	larva generate protobuf
	larva generate {opt,exec}gen
        larva lint --filter=TestLowercaseFunctionNames --short --timeout=1m
```

---

Aside: The naming here is cause of this tool's infancy, relation to
cockroaches, and it starting with the letter "l" (which is featured
prominently in "bazel"/"blaze"). Whatever.

Release note: None

### CODE REVIEW

**Comment by irfansharif** [comment]
@petermattis, @otan, @jlinder: what do youse think of this?

**Comment by knz** [comment]
before I can build an opinion, can you include in the PR description a table that maps side by side some of our key make invocations and the new invocation

I'd like to see at least:

- `build`, `buildshort`, `buildoss`
- the same, but with additional custom tags (e.g. "deadlock")
- `test PKG=.... TESTFLAGS=...` w/ and w/o additional build tags
- `stress PKG=....` w/ and w/o additional test flags
- `bench BENCHES=....` w/ and w/o additional test flags
- `testlogic FILES=a,b,c`
- `lint TESTS=a,b,c` (nb: there's a subtle remapping for lint test lists)

**Comment by irfansharif** [comment]
@knz: Done (they were previously included in the help text for each of the subcommands).

**Comment by knz** [comment]
ok sure that works for me :+1:

**Review by petermattis — COMMENTED** [review]
I'm :thumbsup: on doing this. One suggestion, which you're sort of following below: we want to replicate the functionality of the make targets, but we shouldn't constrain ourselves to make this tool behave identically. For instance, `larva test` should not take a `PKG` and `TESTS` flags. Possibly it shouldn't take `--pkg` either, but allow packages to be specified as positional parameters. That means there will necessarily be some amount of bikeshedding on what the UX is for these commands. So be it. 

I'm not keen on the name `larva`. I had a similar wrapper tool around `blaze` at Google and named it `b` as building is one of the most common operations a developer does. This is another good bikeshed topic.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56965#-:-MMbD8V_4w4Rt-ElOMSy:b-nudv5d)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by knz** [comment]
I think the name of the program does not matter (too) much because every user can use `alias` in their shell.

Generally single-letter commands have a higher risk of colliding with whatever alias folk alrady have defined in their workflow.

I don't know about `larva` in particular but FWIW I like command names that are self-explanatory. For example `build`.

**Comment by otan** [comment]
Heh liking it! Few things:

* Prefer `generate` to be just `gen`, or an alias of it. Minimise them characters.
* Ideally, the existing bazel commands would work "out of the box" -- e.g. for every `bazel build` command i can also run `larva build` with the same arguments.
* There's some extra functionality I really hope to achieve:
   * `larva tool ....` -- runs `bazel run` without needing `--`.
   * `larva roachprod scp,run,....`: wrappers around roachprod that allow building a target and then uploading it to machines for remote execution.
* Not a big fan of the word "larva", i much prefer "bob"/"bobthebuilder" :3. `bzl` is also not a bad one. 
🅱️ for meme value.

**Comment by irfansharif** [comment]
This is a bikeshedding friendly PR, so keep 'em coming. I'll drop `larva` (unless @spencerkimball decides to back me up here). I don't really want to tie the UX here super tightly with bazel, I really want it to be crdb first in its usage. I'm thinking of `dev` instead. I've seen it used at a [previous gig](https://devproductivity.io/dev-shopifys-all-purpose-development-tool/index.html) and it's nice and pithy and relevant to what it's doing.

**Comment by knz** [comment]
ooh I now get it :bulb: I did not previously understand "larva" was a followup on "cockroach"

I do not dislike the idea but then let's make it a bit more grammatically intuitive: the command is the agent that "makes" the cockroach, it's not a command that forks into a cockroach process.

So I'd be more inclined to go for "lay", "grow", "infest" or whatever.

**Comment by knz** [comment]
or "hatch"

**Comment by jlinder** [comment]
Sweet! 

Names that popped out for me: `molt`, `bob`, `bzl`. `molt` is particularly interesting since it the code is molting into a cockroach.

I don't think it should be any of these:

- `ant` (that's already a java build tool)
- `dev` (it's too overloaded already, like, the dev environment, dev accounts, dev of dev/staging/prod, ...)

**Comment by kenliu** [comment]
Since we're bikeshedding here...I will add that we could do without some of the gross verbs associated with cockroach reproduction. `dev` sounds fantastic 😆

**Comment by rickystewart** [comment]
@irfansharif I understand this is a pretty barebones PR, but can we get it merged anyway? Can't start iterating/improving on this until it's checked in :)

**Comment by irfansharif** [comment]
yup, mind stamping it as is?

**Comment by knz** [comment]
you'll need to rebase though

**Review by knz — APPROVED** [review]

**Comment by irfansharif** [comment]
TFTR! I had a few more (unpolished) commits locally that fleshed out `test/gen/build`, and I've pushed them out. Merging it as is without review as it's all going to change anyway.

bors r+

**Pull request merged**
