### PR TITLE
sql/sem/tree: eliminate types.T allocations in collated string comparison

### PR DESCRIPTION
**Pull request by mgartner**
#### sql/sem/tree: eliminate types.T allocations in collated string comparison

This commit eliminates allocations of `types.T` in the `CompareError`
method of `DCollatedString`. Instead of allocating a new collated string
type and calling the `Equivalent` method on the type, `CompareError`
simply checks that the locales of the collated string datums match. This
matches the behavior of `Equivalent`.

Epic: None

Release note (performance improvement): Queries that compare collated
strings now use less memory and may execute faster.

#### sql/sem/types: more efficiently order UserDefinedTypeMetadata fields

The order of fields of the `types.UserDefinedTypedMetadata` struct,
which is embedded in `types.T`, has been changed to reduce padding
required for word-alignment. The struct size has been reduced from 32
bytes to 24 bytes.

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
This should eliminate a sizable chunk of allocations as seen in https://github.com/cockroachlabs/support/issues/2579#issuecomment-1705641305.

**Comment by mgartner** [comment]
I tested with a contrived example and allocations were down significantly:

```
CREATE TABLE t (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    s STRING(200) COLLATE en_US_u_ks_level2 NOT NULL
);

INSERT INTO t(s) SELECT 'foo_123456' FROM generate_series(1, 10000);

-- Repeated many times:
SELECT * FROM t WHERE s = 'bar_123456' COLLATE en_US_u_ks_level2;
```

**Review by msirek — APPROVED** [review]
Very nice!
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110066#-:-NdbR-Lz0F4VrIpB6fiZ:b15lg1l)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110066#-:-NdbVxEPEMDtxJviAG1b:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
