### PR TITLE
colexec: add unit tests for the supported window functions

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: minor clean up**

This removes a couple of files by putting the non-templated code
into the template file.

Release justification: Category 1: Non-production code changes.

**colexec: add unit tests for the supported window functions**

Release justification: Category 1: Non-production code changes.

Addresses: #40634.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I forgot that I already had some work in progress for this, so I decided to finish it up and put it out as a PR. This PR is of a very low priority though.

**Comment by yuzefovich** [comment]
Friendly ping.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41051#-:-LqrOkmL-AeofgP-knbS:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
