### PR TITLE
kvclient: add metrics for txns with condensed intents

### PR DESCRIPTION
**Pull request by andreimatei**
Two new metrics - txn.condensed_intent_spans and
txn.condensed_intent_spans_gauge - tracking transactions whose intent
spans have been collapsed with a loss of fidelity because the respective
transaction has exceeded kv.transaction.max_intents_bytes. Such
transactions are a potential source of instability because resolving
their intents might cost significant CPU (and also latency => contention
footprint).

Also new logging aiming aiming to provide the IDs of some such
transactions.

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62540)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go, line 493 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62540#-MW_R8zsCa-iGZd4Ay_P:-MW_R8zsCa-iGZd4Ay_Q:b-gvqhr5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1673ca0e74b2ee48f508c6e700b278fb0e60e6cd/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L493)):*
> ```Go
> 	// After adding new writes to the lock footprint, check whether we need to
> 	// condense the set to stay below memory limits.
> 	defer func() {
> ```

Could you make sure this isn't causing any new heap allocations?
___
*[pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go, line 498 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62540#-MW_RbDp1M5fKIFaEBOW:-MW_RbDp1M5fKIFaEBOX:b-ndalz5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1673ca0e74b2ee48f508c6e700b278fb0e60e6cd/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L498)):*
> ```Go
> 		if condensed && !alreadyCondensed {
> 			if tp.condensedIntentsEveryN.ShouldLog() || log.ExpensiveLogEnabled(ctx, 2) {
> 				log.Warningf(ctx, "condensed the intents of txn %s after sending %s", ba.Txn, ba.Summary())
> ```

I agree more and more with you that log statements should be specific enough to not require a post to #kv asking "is this bad?" every time someone hits it. I don't think this meets that requirement. Want to add some more detail here to help guide users to either make changes if they aren't running bulk updates or feel comfortable ignoring this if they are?
___
*[pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go, line 500 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62540#-MW_RPW65V4n6O3UbHdA:-MW_RPW65V4n6O3UbHdB:b8syfyy) ([raw file](https://github.com/cockroachdb/cockroach/blob/1673ca0e74b2ee48f508c6e700b278fb0e60e6cd/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L500)):*
> ```Go
> 				log.Warningf(ctx, "condensed the intents of txn %s after sending %s", ba.Txn, ba.Summary())
> 			}
> 			tp.txnMetrics.TxnsWithCondensedIntents.Inc(1)
> ```

Let's add some unit tests for these metrics. Shouldn't be hard to do in `txn_interceptor_pipeliner_test.go`.
___
*[pkg/kv/kvclient/kvcoord/txn_metrics.go, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62540#-MW_SBB0CJKk5DAoqQXO:-MW_SBB0CJKk5DAoqQXP:b-g3bx32) ([raw file](https://github.com/cockroachdb/cockroach/blob/1673ca0e74b2ee48f508c6e700b278fb0e60e6cd/pkg/kv/kvclient/kvcoord/txn_metrics.go#L133)):*
> ```Go
> 	metaTxnsWithCondensedIntentSpans = metric.Metadata{
> 		Name: "txn.condensed_intent_spans",
> 		Help: "KV transactions currently that have exceeded their intent tracking" +
> ```

currently? Isn't that what the gauge is for?

**Review by nvb — COMMENTED** [review]
Thanks! What do you think about backporting this?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62540#-:-MW_SSeHAWIJl_hIWWfS:bw8xbn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

**Review by andreimatei — COMMENTED** [review]
>  What do you think about backporting this?

Yeah, will backport to 21.1, 20.2, 20.1

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62540#-:-MWaLykC2dkfln-ydFi6:bcn417e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go, line 493 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62540#-MW_R8zsCa-iGZd4Ay_P:-MWa0XKgEMiumBke5RMx:bme0ifo) ([raw file](https://github.com/cockroachdb/cockroach/blob/1673ca0e74b2ee48f508c6e700b278fb0e60e6cd/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L493)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could you make sure this isn't causing any new heap allocations?
</blockquote></details>

checked. The only thing reported around here is `ba.Summary() escapes to heap`
___
*[pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go, line 498 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62540#-MW_RbDp1M5fKIFaEBOW:-MWa-t7LEOxuDlhZmAh3:b26fiu8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1673ca0e74b2ee48f508c6e700b278fb0e60e6cd/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L498)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I agree more and more with you that log statements should be specific enough to not require a post to #kv asking "is this bad?" every time someone hits it. I don't think this meets that requirement. Want to add some more detail here to help guide users to either make changes if they aren't running bulk updates or feel comfortable ignoring this if they are?
</blockquote></details>

wise things I've allegedly said. See now.
___
*[pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go, line 500 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62540#-MW_RPW65V4n6O3UbHdA:-MWaLwFf1x5k96Fb0fBA:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1673ca0e74b2ee48f508c6e700b278fb0e60e6cd/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L500)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's add some unit tests for these metrics. Shouldn't be hard to do in `txn_interceptor_pipeliner_test.go`.
</blockquote></details>

done
___
*[pkg/kv/kvclient/kvcoord/txn_metrics.go, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62540#-MW_SBB0CJKk5DAoqQXO:-MWa0cWLDfEiLP2jQ8BN:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1673ca0e74b2ee48f508c6e700b278fb0e60e6cd/pkg/kv/kvclient/kvcoord/txn_metrics.go#L133)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

currently? Isn't that what the gauge is for?
</blockquote></details>

done

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62540#-:-MWaS-BF7q0Roz4dc4Gs:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go, line 498 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62540#-MW_RbDp1M5fKIFaEBOW:-MWaRkFuAxmUftKCnoXZ:bb7mkgj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1673ca0e74b2ee48f508c6e700b278fb0e60e6cd/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L498)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

wise things I've allegedly said. See now.
</blockquote></details>

you've said many wise things

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62540#-:-MXNcshL5GappC14hnja:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @nvanbenschoten)

**Pull request merged**
