### PR TITLE
sql: fix rename_database logic test

### LINKED ISSUE #24047: teamcity: failed tests on master: test/TestLogic
The following tests appear to have failed:

[#579972](https://teamcity.cockroachdb.com/viewLog.html?buildId=579972):

```
--- FAIL: test/TestLogic (156.590s)
test_log_scope.go:81: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestLogic180049643
test_log_scope.go:62: use -show-logs to present logs inline
--- FAIL: test/TestLogic: TestLogic/parallel-stmts (0.450s)

--- FAIL: test/TestLogic: TestLogic/parallel-stmts: TestLogic/parallel-stmts/rename_database (1.130s)
logic.go:2124: 
	testdata/logic_test/rename_database:41: error while processing
logic.go:2125: 
	testdata/logic_test/rename_database:41: 
	expected "relation \"kv\" does not exist", but found <nil>
------- Stdout: -------
=== PAUSE TestLogic/parallel-stmts/rename_database
--- FAIL: test/TestLogic (156.590s)
test_log_scope.go:81: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestLogic180049643
test_log_scope.go:62: use -show-logs to present logs inline
--- FAIL: test/TestLogic: TestLogic/parallel-stmts (0.450s)

--- FAIL: test/TestLogic: TestLogic/parallel-stmts: TestLogic/parallel-stmts/rename_database (1.130s)
logic.go:2124: 
	testdata/logic_test/rename_database:41: error while processing
logic.go:2125: 
	testdata/logic_test/rename_database:41: 
	expected "relation \"kv\" does not exist", but found <nil>
------- Stdout: -------
=== PAUSE TestLogic/parallel-stmts/rename_database

```

Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by vivekmenezes**
The database cache has a cached version of
the system config as well as a cached name to id
map which it uses to temporarily cache database
names potentially in the store but not in the
system config. When the database cache receives a
a new system config through a gossip update it zeros
out the name to id map.

The originally code would only check the
cached system config to see if the database
name had been dropped. It was assuming that if
the system config didn't contain the database name
the database cache would not be able to serve the name
and thus tests could depend on the DROP DATABASE
being observed.

However, if the system config didn't contain the name
and the name to id map did contain it, the name could
still be observed. This happens when the database cache
contains a system config from before the CREATE DATABASE
and then populates the name in the name to id map
after the CREATE DATABASE. Now if the
database cache  doesn't get a gossip update the
releaseTables() following a DROP TABLE can still
see the prior system config that doesn't contain the
database name. But a future command using getTableVersion()
will observe the name through the name to id map.

This problem is resolved by releaseTables using the same API
used by getTableVersion() that checks
the ID cache besides the system config for the
dropped database name.

fixes #24047

Release note: None

### CODE REVIEW

**Comment by vivekmenezes** [comment]
@andreimatei any thoughts on this?

**Comment by andreimatei** [comment]
Can you please explain more in the commit message what's going on here (#24047 doesn't have any explanation)? I don't know what we're fixing.
`dbCacheSubscriber.waitForCacheState()` seems like a weird place to wait for anything but the... cache state. Is that the right place to ask the database for anything? And why do we need to ask the database for anything - how can the cache not have a database name that actually exists in the store?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[pkg/sql/table.go, line 406 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25313#-LCdqJ7HBGqlrulRli0G:-LCdqJ7HBGqlrulRli0H:b7864th) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca7873b08f2668b7feb85a843df1530088a0635/pkg/sql/table.go#L406)):*
> ```Go
> 				continue
> 			}
> 			// The bottom code still suffers from the following problem for
> ```

sorry, I don't understand this comment very well. What's the "bottom code"? And what does "still" mean - what is it in relation to? (seems like you're making a temporal remark about this PR, but the reader will not have this PR in mind; consider removing that word)
And then the hazard is not made clear - does node 1's `drop database` succeed, even though it's a no-op?

And then I'm not sure if this comment belongs here: `blockForDBCacheUpdate` is documented as blocking this function until a dropped database is not in the cache any more. It's not clear to me how this is related to what this comment is trying to say.

I think I'm generally missing a bunch of context for this PR :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25313#-:-LCdrorT-Zt3RMMQUm5U:bul0px6)*

**Comment by vivekmenezes** [comment]
Thanks for taking a look at this change. I've updated the commit message to explain the motivation for this change.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/table.go, line 406 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25313#-LCdqJ7HBGqlrulRli0G:-LDDbu8b07xsMawWuVsY:bz6s7yv) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca7873b08f2668b7feb85a843df1530088a0635/pkg/sql/table.go#L406)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

sorry, I don't understand this comment very well. What's the "bottom code"? And what does "still" mean - what is it in relation to? (seems like you're making a temporal remark about this PR, but the reader will not have this PR in mind; consider removing that word)
And then the hazard is not made clear - does node 1's `drop database` succeed, even though it's a no-op?

And then I'm not sure if this comment belongs here: `blockForDBCacheUpdate` is documented as blocking this function until a dropped database is not in the cache any more. It's not clear to me how this is related to what this comment is trying to say.

I think I'm generally missing a bunch of context for this PR :)

</blockquote></details>

It's good you asked because while I was editing this comment explaining the problem I realize I had a fix for the problem. Instead of using dbID != uc.id , we just needed dbID > uc.id .

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25313#-:-LDDbmueEKIt_3Uw0cmA:b8jd3vl)*

**Comment by andreimatei** [comment]
nit: please don't forget to update the PR description when you update the commit message

Does this PR fix all possible races between dropping a database and gossip? Is it possible for a node to pass your `waitForCacheState()` condition (name is not in the system config or in the store) and then get a stale gossiped system config with the name in it? Since apparently it was happening that the system config was old enough to not have a database that existed and then was dropped, it seems to me that it's about as for another stale gossip with the db in it to come afterwards.
If this is so, I don't really know what to do about it, other than adding a mandatory wait in `waitForCacheState()`.

**Comment by andreimatei** [comment]
LGTM

**Comment by andreimatei** [comment]
Wait actually, I'm confused.
The commit talks about the need to check the name->id mapping in addition to the system config. But the code makes a big deal in a comment about checking the store. Checking the store has nothing to do with anything, does it? Is that comment misguided?

**Comment by vivekmenezes** [comment]
That comment was confusing. I've updated it to ```// Resolve the database name from the database cache.```

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25313#-:-LDh9e4v-BnLHkXvrgiW:b-5xbk3l)*

**Comment by andreimatei** [comment]
LGTM

**Pull request merged**
