### PR TITLE
descs: improve validation performance when reading descriptors

### PR DESCRIPTION
**Pull request by postamar**
catkv: allow ValidationDereferencer injection
    
    This commit adds a new dependency injection entry point to the descriptor
    lookup functions in the catkv functions. In itself, this change does not
    alter the current functionality at all. In a subsequent commit it will allow
    descriptor reads in the descriptor collection to leverage the latter
    for cross-reference descriptor validation.
    
    Release justification: low-risk update
    Release note: None

    descs: refine uncommitted descriptors layer
    
    When reading a descriptor from storage via the collection, we perform
    cross-reference validation on it. This implies reading all referenced
    descriptors from storage as well. Prior to this commit, these referenced
    descriptors were simply discarded. We now store them in the uncommitted
    descriptors layer of the descriptors collection. This can dramatically
    dramatically reduce the number of round-trips to storage when doing
    a sequence of descriptor lookups in the same transaction. This happens
    for instance when the declarative schema changer does a DROP DATABASE
    CASCADE on a large database.
    
    This commit adds qualifiers to the uncommitted descriptors stored in the
    descriptors collection to effectively use it as a cache.
    We now distinguish between:
    1. descriptors which have been read from storage and have since possibly
       been modified;
    2. descriptors which have been read from storage and validated but which
       we know haven't yet been modified in this transaction;
    3. descriptors which have been read from storage but only for the
       purpose of cross-reference validation of another descriptor.
    
    In this commit, right before attempting to read a descriptor from storage
    we look for it in (3). If we find it, we validate it (with
    cross-reference validation) and promote it to (2).
    
    When validating cross-references for a descriptor, we previously
    systematically read the referenced descriptors from storage. In this
    commit, we instead use any we can find in (2) or (3). Any of which we do
    end up reading from storage we then add to (3).
    
    The rest of the time, the descriptors in (3) are ignored.
    
    Release justification: low-risk high-benefit performance improvement
    Release note: None

### CODE REVIEW

**Comment by postamar** [comment]
The first commit just moves things around. The second actually injects the collection into catkv's validation and any referenced descriptors we read from storage (hence, previously unknown to the collection) get added to the collection's uncommitted layer (with a special status to prevent them from being used anywhere other than validation).

**Comment by ajwerner** [comment]
Flake was https://github.com/cockroachdb/cockroach/issues/77264

**Review by ajwerner — APPROVED** [review]
:lgtm_strong: The pieces are coming together!

> Reviewed 10 of 10 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77630#-:-MxqlEraD3YmwE-ABrm2:b-hqims3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @postamar)

**Comment by postamar** [comment]
Thanks for the review! I force-pushed on the branch to rebase & fixed some typos in the commit message but otherwise no change.

bors r+

**Pull request merged**
