### PR TITLE
sql: store TenantInfo proto in system.tenants.info

### LINKED ISSUE #52691: jobs: use enum for system.tenants.active
https://github.com/cockroachdb/cockroach/issues/48775#issuecomment-655215813

From @dt:

> I'd suggest changing active from a bool to an enum (ideally soon, before we need to do a migration) so it can be extended to capture more detail about the state, e.g. off the top of my head I think it would make sense to have at least 4 states: active, inactive, adding, and dropped. This could e.g. make it easier to identify tenants who have been destroyed but whose key-span has not been cleared, if we see a record in state dropped. The current bool's coarseness makes it impossible to tell a tenant that is restoring but is not yet active from one that is dropping.

We'll want to do this even if we don't immediately implement the job that performs the hard delete and moves a tenant from "dropping" to "dropped".

### PR DESCRIPTION
**Pull request by nvb**
Fixes #52691.
Informs #48775.
Informs #53477.

This commit replaces the opaque `info` column in the `system.tenants` table with a structured `TenantInfo` protobuf. This protobuf will allow for future extension of tenant rows without the corresponding complexity of structured SQL columns. For instance, this will ease the development of per-tenant rate limits. It also allows us to split the "active" flag into multiple states, which is needed for a DropTenant job to work correctly.

After this change, a tenant row consists of a TenantInfo proto, along with two columns that are effectively computed columns from the proto. We seem to follow the same pattern in the system.descriptor table.

This commit makes no attempt to maintain backwards compatibility with existing users of tenants, though it does maintain backwards compatibility with existing alphas and betas that have not created any tenants. Notably existing clusters will not have the correct value in their `tenants.info` column and existing backups will not have the correct information in their `BackupManifest.Tenants.Info` or `RestoreDetails.Tenants.Info` protos. I think this is ok because CC should be the only user of any of this and we don't have anything deployed yet. We could make this all backwards compatible, but that would be extra work which doesn't seem worth the effort.

I intend to backport this to release-20.2 with the same argument – this is safe for anyone not using multi-tenancy.

cc. @miretskiy the second commit is what we discussed on Slack.

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 5 of 5 files at r2, 17 of 17 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54811#-:-MIKuHJ4CRWTYzpsS1S8:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @nvanbenschoten)

___
*[pkg/sql/tenant.go, line 224 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54811#-MIKuBb0DNQ7nW6g9g7E:-MIKuBb0DNQ7nW6g9g7F:b-4u3wip) ([raw file](https://github.com/cockroachdb/cockroach/blob/10c5e1ddfacf557eeba5712be871472995555519/pkg/sql/tenant.go#L224)):*
> ```Go
> 	}
> 
> 	// Retrive the tenant's info.
> ```

nit: `Retrive`

**Comment by nvanbenschoten** [comment]
TFTR!

I realized that we can retain backwards compatibility with previous BACKUPs by replacing the `BackupManifest.Tenants` and `RestoreDetails.Tenants` messages with `TenantInfo`s directly. I'm going to make that change. @dt once I do, do you mind signing off on it?

**Comment by dt** [comment]
wouldn't you need to make `State` ID 3 if you want to drop-in replace the backupccl.Tenant message?

I don't particularly care about compatibility tenant backups from with the alphas though.

**Comment by nvanbenschoten** [comment]
> wouldn't you need to make State ID 3 if you want to drop-in replace the backupccl.Tenant message?

Technically, yes, though I confirmed that we've never provided an `info` field in the past, so that byte slice should always be missing from backups.

**Comment by nvanbenschoten** [comment]
> I'm going to make that change.

Done. That actually came out fairly well. @dt mind giving this a pass when you get a chance?

**Comment by nvanbenschoten** [comment]
Going to merge this so it can slip in before the backport cutoff. The code changes here are confined to multi-tenant related logic, so if there is an issue, it should be well isolated.

bors r+

**Review by dt — APPROVED** [review]

**Review by miretskiy — COMMENTED** [review]
👍 :lgtm: for emit defaults

**Pull request merged**
