### PR TITLE
tracing: assorted tracing fixes

### LINKED ISSUE #103052: tracing: safe formatting Structured trace event redacted in verbose trace
`spanInner.RecordStructured` has logic to record structured trace events as unstructured events in verbose traces:
https://github.com/cockroachdb/cockroach/blob/29523d3549402b7cdced8fe211e6c133822e5d5a/pkg/util/tracing/span_inner.go#L268-L272

However, because this logic passes through a raw `string`, it loses information about redaction and becomes entirely redacted if trace redaction is enabled. This is true even if the original structured event implements the `redact.SafeFormatter` interface.

Jira issue: CRDB-27814

Epic: CRDB-27642

### LINKED ISSUE #103227: tracing: the copy of structured events in verbose trace is not enclosed in redaction markers
**Describe the problem**

When emitting a structured payload to a verbose trace, a JSON copy of its representation is included as unstructured log event.

Currently this JSON copy can contain unsafe strings, but it is incorrectly not enclosed inside redaction markers because of a bug in the `redact` library.

**Expected behavior**

The JSON copy should be redactable.

Jira issue: CRDB-27892

Epic: CRDB-27642

### PR DESCRIPTION
**Pull request by knz**
Fixes #103052.
Fixes #103227.
Epic: CRDB-27642

Prior to this patch, structured items added to verbose traces were
improperly converted to an unsafe string prior to recording.
This was making the entire structured payload redactable in the
recording representation.

This patch fixes the situation by delegating the representation
to the structured item itself, which may implement a SafeFormat
method.

This patch also ensures that the JSON copy of structured events
is properly marked as redactable.

### CODE REVIEW

**Review by dhartunian — APPROVED** [review]
:lgtm: thx for splitting up the PRs nicely.

> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 3 of 3 files at r3, 3 of 3 files at r4, 6 of 6 files at r5, 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103225#-:-NVeBncn55jBHjv6tjld:bjd2iez)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier and @nvanbenschoten)

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103225#-:-NWDZ9QD-tZylFHCzj3-:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier, @dhartunian, @knz, and @nvanbenschoten)

___
*[`-- commits` line 24 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/103225#-NWDYYTv1tjlIoXTHOJ2):*
Does this mean we'll no longer see these values in eg `SHOW TRACES`? How about in query bundles or a collector like Jaeger?

**Comment by knz** [comment]
> Does this mean we'll no longer see these values in eg SHOW TRACES? How about in query bundles or a collector like Jaeger?

It depends. If *trace redaction* is enabled, they would be removed yes. But it's not enabled by default.

**Comment by knz** [comment]
FYI:
- when trace redaction is enabled (cluster setting), the redaction of trace data happens at the KV/SQL boundary
- it's enabled in Serverless. The reasoning is that unstructured data in trace can contain sensitive data about _other_ tenants than the one the trace is flowing to, and should be removed.
- trace data emitted within the SQL layer is thus not removed, regardless of whether redaction is enabled.

**Comment by knz** [comment]
TFYR

bors r=dhartunian,RaduBerinde

**Pull request merged**
